### ISSUE TITLE
[rllib] Custom policies crashes in multi-agent, tuple action space settings

### ISSUE THREAD

**Issue by MoggeM** [ray-project/ray#10009]
### What is the problem?
Custom policies crashes with the following error:

File "/home/mogge/.local/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 1004, in _process_policy_eval_results
    clipped_action = clip_action(action,
  File "/home/mogge/.local/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 526, in clip_action
    return tree.map_structure(map_, action, action_space)
  File "/home/mogge/.local/lib/python3.8/site-packages/tree/__init__.py", line 513, in map_structure
    assert_same_structure(structures[0], other, check_types=check_types)
  File "/home/mogge/.local/lib/python3.8/site-packages/tree/__init__.py", line 369, in assert_same_structure
    raise type(e)("%s\n"
ValueError: The two structures don't have the same nested structure.

First structure: type=ndarray str=[0 1 2]

Second structure: type=tuple str=(Discrete(2), Discrete(2), Discrete(5))

More specifically: Substructure "type=tuple str=(Discrete(2), Discrete(2), Discrete(5))" is a sequence, while substructure "type=ndarray str=[0 1 2]" is not
Entire first structure:
.
Entire second structure:
(., ., .)

It seems to be related to clip_actions where it compares the "raw" action space instead of whats returned from "get_base_struct_from_space".

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray==0.9.0.dev0
Tensorflow==2.2.0
Ubuntu 20.04

### Reproduction (REQUIRED)
"""
import ray
from ray import tune
from ray.rllib.examples.env.multi_agent import make_multiagent
from ray.rllib.policy import Policy
from ray.tune.registry import register_env
from ray.rllib.env.multi_agent_env import MultiAgentEnv

MultiAgentEnv = make_multiagent('DuplicatedInput-v0')

class RandomPolicy(Policy):
    """Hand-coded policy that returns random actions."""

    def compute_actions(self,
                        obs_batch,
                        state_batches=None,
                        prev_action_batch=None,
                        prev_reward_batch=None,
                        info_batch=None,
                        episodes=None,
                        **kwargs):
        """Compute actions on a batch of observations."""
        return [self.action_space.sample() for _ in obs_batch], [], {}

    def learn_on_batch(self, samples):
        """No learning."""
        return {}

if __name__ == '__main__':
    ray.init(ignore_reinit_error=True)
    register_env("multi_agent_simple",
                 lambda _: MultiAgentEnv({"num_agents": 2}))
    single_env = MultiAgentEnv({"num_agents": 2})
    obs_space = single_env.observation_space
    act_space = single_env.action_space

    tune.run(
        "PG",
        stop={"training_iteration": 25},
        config={
            "env": "multi_agent_simple",
            "multiagent": {
                "policies": {
                    "random": (RandomPolicy, obs_space, act_space, {}),
                    "random2": (RandomPolicy, obs_space, act_space, {})
                },
                "policy_mapping_fn": (
                    lambda agent_id: "random"),
            },
        },
    )
"""

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Yup, something's off. Taking a look now ...
Thanks for filing this!

**Comment by sven1977** [comment]
Can you try this in your policy?

```
        ...
        unbatched = [self.action_space.sample() for _ in obs_batch]
        actions = tuple(
            np.array([unbatched[j][i] for j in range(len(unbatched))]) for i in range(len(unbatched[0]))
        )
        return actions, [], {}
```

The thing is that your policy is supposed to return "batched" actions. So if we have a Tuple action space, the returned actions must be tuples of np.array batched values (in this case ints as the child-spaces are all discrete).

I'll leave this open and add a better error message to RLlib in case the policy violates this. Also let me know, if this does not work on your end.

**Comment by MoggeM** [comment]
Yes, this worked like a charm. Thank you very much for the help
