### ISSUE TITLE
[rllib] PPOTrainer pytorch version can only use one GPU?

### ISSUE THREAD

**Issue by wiljohnhong** [ray-project/ray#10002]
ray==0.8.6
python==3.7.4
torch==1.6.0

cuda 10.1
ubuntu 16.04

Hi, I'm new to use rllib, really amazing! But now I have 8 nvidia RTX 2080ti on my driver machine, and when I set `ppo.DEFAULT_CONFIG["framework"]="torch"`, just the first gpu is in use. This is not the case when I switch to the default tensorflow framework which uses up all the 8 gpus with orther configs remain the same. I can't figure out what's going wrong, does torch version in rllib not implement data parallel?

**Comment by ericl** [comment]
Yeah, we don't have multi-gpu for torch implemented (though you can try DD-PPO). This should probably be raising an error instead of silently ignoring the other GPUs.

**Comment by janblumenkamp** [comment]
I am also very interested in a Multi-GPU PyTorch version of PPO! What are the challenges? Is it busy-work or are there some other issues that need to be solved first?

**Comment by jsuarez5341** [comment]
Any news on this @ericl @sven1977 ? Even on a single machine, multi-GPU has become more important with the introduction of 64 core AMD chips

**Comment by sven1977** [comment]
Sorry, can't make any promises, but it's on our list for this quarter to cover multi-GPU torch + multi-GPU (algos other than PPO).

**Comment by jsuarez5341** [comment]
Thanks for the timeline update -- when you say algos other than PPO, do you mean excluding PPO, or PPO and other algs?
