### ISSUE TITLE
[rllib] Torch policy + non-empty custom_model_config errors out

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#10015]
### What is the problem?
On Ray 0.8.6, Torch policy + non-empty custom_model_config + custom model would crash.

### Reproduction (REQUIRED)
```
  File "/home/ubuntu/anaconda3/envs/exp/lib/python3.7/site-packages/ray/rllib/policy/torch_policy_template.py", line 120, in __init__
    **self.config["model"].get("custom_model_config", {}))
  File "/home/ubuntu/anaconda3/envs/exp/lib/python3.7/site-packages/ray/rllib/models/catalog.py", line 360, in get_model_v2
    model_config, name, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'pool'
```
Reproducible by any custom Torch model with a non-empty `custom_model_config`.

This error shows up if I set any `custom_model_config: {'pool': xxx}`, where `pool` is something my custom torch model can interpret; here, rllib torch template is unpacking this dict, causing erroring out.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Can you try getting the `pool` information in your Model class' c'tor from `config["model"]["custom_model_config"]["pool"]`, instead of an actual `pool` arg? It should work then.

**Comment by concretevitamin** [comment]
The problem is rllib unpacking this for me.

**Comment by ericl** [comment]
@sven1977 I think this is a bug, removed it for torch here: https://github.com/ray-project/ray/pull/10055
