### ISSUE TITLE
[TUNE/PBT]Maybe a bug  in tune/pbt example code?

### ISSUE THREAD

**Issue by noprohuangqi** [ray-project/ray#10038]
https://github.com/ray-project/ray/blob/65848201c348bb3fccd6e11d620626ec2480a2d0/python/ray/tune/examples/pbt_convnet_example.py#L135-L136

when I use RAY/PBT follow code above , I find in this code:
```
    best_checkpoint = max(
        analysis.get_trial_checkpoints_paths(best_trial, "mean_accuracy"))
```
the formula:
`analysis.get_trial_checkpoints_paths(best_trial, "mean_accuracy")`
in fact return a list like :
` lists = [['009' , 0.7] , ['007' , 0.9]]`
This mean the list's item is a list which first item is a file path , and second item is 'mean_accuracy'.
So when use max function , it is compare the file path ,but not the mean_accuracy.
Maybe it shoud change to:
```
    best_checkpoint = max(
        analysis.get_trial_checkpoints_paths(best_trial, "mean_accuracy") , key = lambda x:x[1])
```

**Comment by amogkam** [comment]
Yes this looks like a bug, good catch! If you don't mind could you submit a PR for this fix?

**Comment by rkooo567** [comment]
@amogkam Can you set the priority level and an assignee? If he doesn't respond, you can assign to yourself?

**Comment by amogkam** [comment]
Fixed with https://github.com/ray-project/ray/pull/9958
