### ISSUE TITLE
[GCS]Duplicate subscribe of node resource when resubscribe.

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#10039]
### What is the problem?
![image](https://user-images.githubusercontent.com/13081808/89863472-bd185d00-dbdc-11ea-861f-94c6e1af566c.png)

We will call `AsyncSubscribeToResources` in the callback of `AsyncSubscribeToNodeChange`.
If the connection between gcs client and gcs server is abnormal, the gcs client will reconnect and fetch data from gcs server and call the callback of `AsyncSubscribeToNodeChange` again. This causes duplicate subscribe of node resource.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@ffbin Isn't this done? I remember you submitted a PR regarding this before? Am I correct?

**Comment by ffbin** [comment]
We can close it now, the master code is ok.
