### ISSUE TITLE
Replay Buffer investigation

### ISSUE THREAD

**Issue by anguyenbus** [ray-project/ray#10033]
### What is your question?
[rllib] replay buffer.

Hi all,

I am doing a personal RL project in improvement of RNN. The issue is I really want to look into the experience sampled by SACTrainer pre-training. The reason why I want to do this is because I am not sure if the samples are in sequence order when fed into the RNN.

So do you know how can I play around with replay_buffer to print out the experience replay?

Kind Regards
An Nguyen 

*Ray version and other system information (Python version, TensorFlow version, OS): (ray 0.9.0Dev, Python 3.6, Torch

**Comment by rkooo567** [comment]
cc @sven1977
