### ISSUE TITLE
[RLLib] RLLib Customized Env do we have to put one action_space in environment?

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#10048]
I have a customized environment, where per state we have different numbers of actions. The idea is to create a dictionary where for each state, it has different set of number of actions. I know we can use parametric action space to handle this scenario. But we want to use a different model to handle it and customized the action distribution function. In that case, do we have to pass action_space in BaseEnv?  Or we can just put a dummy action_space there and customized the model and action distribution function the way we want. 

Thanks.

**Comment by ericl** [comment]
You must always define the action space as a `gym.Space`, perhaps you can use a Tuple of different action spaces, or a big action space that is the union of all possible child spaces.

**Comment by AprilXiaoyanLiu** [comment]
Thanks
