### ISSUE TITLE
[docs] Issue on `serve/tutorials/batch.rst`

### ISSUE THREAD

**Issue by alexcoca** [ray-project/ray#10045]
Hi, 

According to your documentation:

![image](https://user-images.githubusercontent.com/30216068/89919870-b5b07e00-dbf3-11ea-8e1c-a516664aa2ff.png)

This means that if a worker happens to be idle and there are 500 requests to serve with a batch size of 10 we would send them all to one worker. I hope what the writer meant is `min` instead of `max`.

(Created directly from the docs)

**Comment by rkooo567** [comment]
cc @simon-mo

**Comment by edoakes** [comment]
@simon-mo ping
