### ISSUE TITLE
Rllib cannot run on gpu

### ISSUE THREAD

**Issue by xlnwel** [ray-project/ray#10058]
I install ray[rllib] and tensorflow using the following commands

```python
pip install ray[rllib]==0.8.6
pip install tensorflow-gpu==2.3.0 # I've also tried tensorflow==2.3.0 and previous tensorflow versions, similar errors were reported
```
I run rllib's PPO and receive the following error message

>RuntimeError: GPUs were assigned to this worker by Ray, but TensorFlow reports GPU acceleration is disabled. This could be due to a bad CUDA or TF installation.

I've tested the environment using my own code and the GPU is used as expected. How can I fix it?

My system information:
```
Ubuntu: 18.04
cuda: 10.2
cudnn: 7.6.5
python: 3.8.3
```

**Comment by rkooo567** [comment]
cc @sven1977 Is it the known issue?

**Comment by ericl** [comment]
This is almost certainly due to a bad CUDA installation. Have you checked if tensorflow can use GPUs without Ray?

**Comment by xlnwel** [comment]
I don't think so. I've run several other programs written in TF and ray, they all used the GPU correctly. The error happens only when I use rllib.

**Comment by xlnwel** [comment]
I also found that if I build TF from source, the error will disappear.
