### ISSUE TITLE
[rllib] MARWIL does not convert SampleBatch state_in_* values to torch tensors

### ISSUE THREAD

**Issue by mvindiola1** [ray-project/ray#10068]
Ray [0.6.8] and Ray nightly wheel: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.wh

When training marwil with an LSTM layer using pytorch I get the following error:

> File ".../lib/python3.6/site-packages/ray/rllib/models/torch/recurrent_net.py", line 155, in forward_rnn:
>  [torch.unsqueeze(state[0], 0),
>   TypeError: unsqueeze(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

I do not get any errors in TF.

This is the script I used to test and generate the attached error log.
[torch_error.txt](https://github.com/ray-project/ray/files/5064082/error.txt)

```
import ray
import ray.rllib.agents.marwil as marwil
from ray import tune

ray.init(redis_port=6379)
config = marwil.DEFAULT_CONFIG.copy()
config["env"] = "CartPole-v0"
config["num_workers"] = 1
config["model"]["use_lstm"] = True

for framework in ["tf", "torch"]:
    print("Testing MARWIL with framework: {}".format(framework))
    input_file = "/tmp/marwil/cartpole_{}".format(framework)
    config["framework"] = framework

    # Create input file
    config["input"] = "sampler"
    config["output"] = input_file
    config["output_max_file_size"] = 50000000
    trainer = marwil.MARWILTrainer(config=config, env="CartPole-v0")
    tune.run("MARWIL", stop={"training_iteration": 10},
             config=config, local_dir="/tmp/marwil/logs/create_{}".format(framework), verbose=False)

    # Train with input file
    config["input"] = input_file
    config["output"] = None
    trainer = marwil.MARWILTrainer(config=config, env="CartPole-v0")
    tune.run("MARWIL", stop={"training_iteration": 10},
             config=config, local_dir="/tmp/marwil/logs/train_{}".format(framework), verbose=False)
ray.shutdown()



- [X ] I have verified my script runs in a clean environment and reproduces the issue.
- [X ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
@sven1977

**Comment by mvindiola1** [comment]
@ericl I just re-tested this with the nightly wheel. The result is the same as before. It works with tf but not with pytorch. The error seems to be in evaluation sampling. If I add this to the config `config["input_evaluation"] = []` then pytorch trains without issue. I tried it with `config["framework"]="tfe"` and that failed with a different type of error. 

I am willing to hunt the pytorch issue down and prepare a PR if I am given a nudge in the direction to look.

**Comment by mvindiola1** [comment]
I am thinking a change like this in torch_policy::compute_log_likelihoods:
```diff
@@ -306,6 +306,10 @@ class TorchPolicy(Policy):
             if prev_reward_batch is not None:
                 input_dict[SampleBatch.PREV_REWARDS] = prev_reward_batch
             seq_lens = torch.ones(len(obs_batch), dtype=torch.int32)
+            state_batches = [
+                convert_to_torch_tensor(s, self.device)
+                for s in (state_batches or [])
+            ]

             # Exploration hook before each forward pass.
             self.exploration.before_compute_actions(explore=False)
```

It is the same thing you did in torch_policy::compute_actions here:
https://github.com/ray-project/ray/blob/91fa7e0b4e8f2dd997b855952e4e8e3bdc0bdb5c/rllib/policy/torch_policy.py#L163-L170


I also noticed that torch_policy::compute_actions_from_input_dict might have the same issue.
https://github.com/ray-project/ray/blob/91fa7e0b4e8f2dd997b855952e4e8e3bdc0bdb5c/rllib/policy/torch_policy.py#L196-L198
