### ISSUE TITLE
[tune] ModuleNotFoundError for tuning script

### ISSUE THREAD

**Issue by guoxuxu** [ray-project/ray#10067]
### ModuleNotFoundError: No module named 'functions'

Does it seem the ray_tune.py file must stay in the same directory with data/ ??? Otherwise, it doesn't work even if I put ```'../'``` in the data loader function...
Specifically, I run the same ray_tune.py in the parent folder and child folder respectively, but only got success when I run under the parent folder.

Cannot provide reproducible code here, because I used my own dataset.
This issue occurred whenever I switched the ray_tune.py to a child directory (has ```../```)...

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.5
Python 3.7.4
Pytorch 1.6
TensorFlow: 2.2.0
OS linux

![image](https://user-images.githubusercontent.com/29363464/89991868-0937d000-dcb7-11ea-9637-e5bdf15f847b.png)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @amogkam

**Comment by richardliaw** [comment]
@guoxuxu sorry for the slow reply, can you jsut use an absolute path?

**Comment by richardliaw** [comment]
Also, it sounds like you're depending on a relative import in Python. 

For Ray, it is best that you use Absolute imports: https://realpython.com/absolute-vs-relative-python-imports/

**Comment by guoxuxu** [comment]
OK, I see. Thank you!
