### ISSUE TITLE
[tune] Cannot change sync_to_cloud frequency

### ISSUE THREAD

**Issue by annaluo676** [ray-project/ray#10076]
### What is the problem?

After setting `tune.syncer.NODE_SYNC_PERIOD = 60` and `tune.syncer.CLOUD_SYNC_PERIOD = 60`, files such as `progress.csv`, `result.json` and tensorboard event files under `upload_dir` (aws s3 in this case) are still updated every 300s, which is the default value as per https://github.com/ray-project/ray/blob/master/python/ray/tune/syncer.py

Note that `NODE_SYNC_PERIOD ` is hard-coded https://github.com/ray-project/ray/blob/master/python/ray/tune/syncer.py#L23

Ray version: 0.8.5
Python version: 3.7.4
Tensorflow version: 2.1.0

### Reproduction (REQUIRED)
```
import ray
from ray import tune

tune.syncer.NODE_SYNC_PERIOD = 60
tune.syncer.CLOUD_SYNC_PERIOD = 60

from ray.rllib.agents.ppo import PPOTrainer

config = {
    'cartpole-ppo-1': {
        'env': 'CartPole-v0',
        'run': 'PPO',
        'stop': {},
        'config': {
            'gamma': 0.99,
            'lr': 0.0003,
            'num_workers': 1,
            'observation_filter': 'MeanStdFilter',
            'num_sgd_iter': 6,
            'vf_share_layers': True,
            'vf_loss_coeff': 0.01,
            'model': {
                'fcnet_hiddens': [32], 
                'fcnet_activation': 'linear'
            }
        },
  'upload_dir': 's3://some_s3_bucket/annaluo-test-node-sync'
    }
}

from ray.tune import tune

tune.run_experiments(config)

```
The screen shot below shows the time when the files got updated the first time on s3. `params.json` stayed unchanged when the experiment began so its creation time can serve as a baseline.
<img width="1570" alt="Screen Shot 2020-08-12 at 4 51 31 PM" src="https://user-images.githubusercontent.com/45078924/90079271-481c5480-dcbc-11ea-935c-30bc3fee065d.png">

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by amogkam** [comment]
Hi @annaluo676, can you try upgrading your ray version and setting the `TUNE_CLOUD_SYNC_S` environment variable as described in https://docs.ray.io/en/master/tune/user-guide.html#uploading-results. If that still doesn't work I can investigate this further. Thanks!

**Comment by annaluo676** [comment]
Hi @amogkam, **with 0.8.6** I'm able to update the sync frequency with the following change:
```
import ray
TUNE_CLOUD_SYNC_S = 60
from ray import tune
tune.syncer.NODE_SYNC_PERIOD = 60
tune.syncer.CLOUD_SYNC_PERIOD = 60
```
Missing *any* line above will revert the frequency to 300s. It seems the constants get overwritten through the process. Any ideas?

**Comment by annaluo676** [comment]
Just noticed that 0.8.7 is out. Tested with that and the observation remained the same.

**Comment by richardliaw** [comment]
Actually, this should be fixed on master! Feel free to reopen if not.
