### ISSUE TITLE
Logging environment data [rllib]

### ISSUE THREAD

**Issue by xli4217** [ray-project/ray#10089]
### What is your question?
Hi, is there a preferred way to log statistics from a custom environment (i.e. state, action distributions) in tensorboard? Thanks 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.6

**Comment by rkooo567** [comment]
cc @ericl @sven1977

**Comment by albheim** [comment]
I'm looking for the same thing. Can I somehow plug in to the existing tensorboard logger from my environment so that the logs end up in the same trial?
