### ISSUE TITLE
[tune] save_to_object issue 

### ISSUE THREAD

**Issue by sungreong** [ray-project/ray#10098]
2020-08-13 19:30:02,883	ERROR worker.py:987 -- Possible unhandled error from worker: ray::TrainRegression.save_to_object() (pid=3357, ip=)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/ray/tune/trainable.py", line 385, in save_to_object
    checkpoint_path = self.save(tmpdir)
  File "<ipython-input-61-4e4e5f096546>", line 87, in save
  File "<ipython-input-61-4e4e5f096546>", line 91, in save_checkpoint
  File "/root/anaconda3/envs/pytorch/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

``  def save(self, checkpoint_dir= "./y_models/y1_model.pth") :
        checkpoint_dir = make_dir(checkpoint_dir)
        checkpoint_path = self.save_checkpoint(checkpoint_dir)
        return checkpoint_path
    
    def save_checkpoint(self, checkpoint_dir= "./y_models/y1_model.pth") :
        checkpoint_path = os.path.join(checkpoint_dir,"model.pth")
        checkpoint = torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'hyper-parameter' : self.config
        }, checkpoint_path)
        return checkpoint_dir
    
    def load_checkpoint(self, checkpoint_path):
        checkpoint = torch.load(checkpoint_path)
        self.model.load_state_dict(checkpoint["model_state_dict"])
        
    def _restore(self, checkpoint_path):
        print(f"ID: {self.trial_name}: Looking for checkpoint at  - {checkpoint_path}")
        self.load_checkpoint(checkpoint_path)
``

I Don't know why my custom class status is paused

![image](https://user-images.githubusercontent.com/22166391/90124840-ffd46380-dd9b-11ea-930d-46eb0d8d6e2e.png)

**Comment by amogkam** [comment]
Hi @sungreong, are you overriding `save` as well? You only need to override `save_checkpoint` in your Trainable. Can you try doing that and see if you still get the error.

**Comment by sungreong** [comment]
hi. it can work. but it can't not save the torch model

how can i save the torch model in experiment tag folder?

here is my code. 

```
class TrainRegression(tune.Trainable) :
    def _setup(self,config:dict) :
        input_dim = config.get("input_dim")
        output_dim = config.get("output_dim")
        self.config = config
        h1 = config.get("hidden_size_1", 25)
        h2 = config.get("hidden_size_2", 15)
        h3 = config.get("hidden_size_3", 10)
        lr = config.get("lr", 0.1)
        weight_decay = config.get("weight_decay", 1e-5)
        activation = config.get("activation", "selu")
        if isinstance(tr_x , (pd.DataFrame, np.ndarray)) :
            self.train_data_loader = get_data_loader(tr_x, tr_y,batch_size=16)

        self.model = torch_model(input_dim,output_dim, 
                                            act = activation,
                                            hidden_size=[h1,h2,h3])
        self.optimizer = torch.optim.AdamW(self.model.parameters(),
                                           lr=lr,weight_decay=weight_decay)
        self.best_metric = np.inf
        
    def _train(self) :
        report = collections.defaultdict(list)
        arbitrary_folder = os.path.join(cur_path , folder_name ,randomString(10))
        make_dir(arbitrary_folder)
        for epoch in range(10) :
            for i , (input_) in enumerate(self.train_data_loader) :
                self.optimizer.zero_grad()     
                y_hat = self.model(input_[0])
                loss = self.model.criterion(y_hat , input_[1])
                loss.backward()
                self.optimizer.step()
            eval_x , eval_y = iter(self.train_data_loader).next()
            result_dict = self._eval(eval_x, eval_y,"train")
            if epoch % 50 == 0 :
                [report[k].append(v) for k,v in result_dict.items()]
            if self.test_data_loader is not None :
                test_x , test_y = iter(self.test_data_loader).next()
                result_dict = self._eval(test_x, test_y,"test")
            else :
                pass
            if self.best_metric > result_dict["test_mae"] :
                self.save_checkpoint(arbitrary_folder)
                top_result = result_dict
        best_result = { "folder" : arbitrary_folder, "report" : report}
        best_result.update(top_result)
        return best_result
    
    def _eval(self, x , y, prefix = "train") :
        pred = self.model(x)
        pred = pred.detach().numpy()
        y_   = y.detach().numpy()
        result_dict = Check_Performance(self.y_transformer.inverse_transform(y_),
                                       self.y_transformer.inverse_transform(pred),
                                        threshold = 0.05 , 
                                        prefix = prefix)
        return result_dict
    
    def save_checkpoint(self, checkpoint_dir= "./y_models/y1_model.pth") :
        checkpoint_path = os.path.join(checkpoint_dir,"model.pth")
        torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'hyper-parameter' : self.config
        }, checkpoint_path)
        return checkpoint_dir
    
    def load_checkpoint(self, checkpoint_path):
        checkpoint = torch.load(checkpoint_path)
        self.model.load_state_dict(checkpoint["model_state_dict"])
        
    def _restore(self, checkpoint_path):
        print(f"ID: {self.trial_name}: Looking for checkpoint at  - {checkpoint_path}")
        self.load_checkpoint(checkpoint_path)
```

**Comment by amogkam** [comment]
Looking at your tune.run invocation in the other issue I don't think checkpointing is actually being called. You either have to manually checkpoint or periodically checkpoint as described here: https://docs.ray.io/en/master/tune/api_docs/trainable.html#class-api-checkpointing

If you have that set then there should be checkpoints under tune's log directory in ~/ray_results. If you want to save the checkpoint in a different directory you have to do it in addition to tune's checkpoint directory. For example:
```
def save_checkpoint(self, checkpoint_dir) :
        checkpoint_path = os.path.join(checkpoint_dir,"model.pth")
        torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'hyper-parameter' : self.config
        }, checkpoint_path)
        my_checkpoint_path = "./y_models/y1_model.pth"
        torch.save({
            'model_state_dict': self.model.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
            'hyper-parameter' : self.config
        }, my_checkpoint_path)
        return checkpoint_dir
```
Hope this helps.
