### ISSUE TITLE
[rllib] function unbatch in ray/rllib/utils/spaces/space_utils.py does not work as intended

### ISSUE THREAD

**Issue by gml16** [ray-project/ray#10100]
### What is the problem?

Function `unbatch` in `ray/rllib/utils/spaces/space_utils.py` produces an error when given the example input in the head-line comment.
Ray version: On master (latest commit hash is 66d204e0785619a6c9cef707b796e5804401b6ca)
Python version:  3.8.2

### Reproduction (REQUIRED)
```
from ray.rllib.utils.spaces.space_utils import unbatch
unbatch({"a": [1, 2, 3], "b": ([4, 5, 6], [7.0, 8.0, 9.0])})
```

Traceback is:
```
File "~/ray/rllib/utils/spaces/space_utils.py", line 124, in unbatch
    for batch_pos in range(len(flat_batches[0])):
TypeError: object of type 'int' has no len()
```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
cc @sven1977

**Comment by rusu24edward** [comment]
I just updated version of ray[rllib] and started getting this error too.

**Comment by rusu24edward** [comment]
Tracked it to [here](https://github.com/ray-project/ray/blame/releases/0.8.7/rllib/policy/policy.py#L196). In my example, I'm using PG. My `out` at this point is `([1], [], {})`. In [unbatch](https://github.com/ray-project/ray/blob/releases/0.8.7/rllib/utils/spaces/space_utils.py#L95), `flat_batches` is just [1], which causes the error.

**Comment by mehes-kth** [comment]
For _some_ custom policies, a potential workaround is to only return the action (i.e. omit `state` and `info`), and by virtue of [this `if` statement](https://github.com/ray-project/ray/blob/7916500c43de46721c51e6b95fb51cfa2c6078ba/rllib/policy/policy.py#L266) skip the call to `unbatch`...

**Comment by mehes-kth** [comment]
@richardliaw @ericl 
With this bug in the "critical path", does _any_ of the "standard" policies evaluate correctly in Ray 1.6.0?
Shouldn't this bug be marked "critical" (or some such) and fixed ASAP?

**Comment by mehes-kth** [comment]
A closer look at the actual code reveals an expectation that `tree.flatten` should _preserve_ the batches.
This is clearly not the case, when the batches are primitive lists, but it does work with `ndarray`:s...
```python
>>> import numpy as np
>>> from ray.rllib.utils.spaces.space_utils import unbatch
>>> unbatch({"a": np.array([1, 2, 3]), "b": (np.array([4, 5, 6]), np.array([7.0, 8.0, 9.0]))})
[{'a': 1, 'b': (4, 7.0)}, {'a': 2, 'b': (5, 8.0)}, {'a': 3, 'b': (6, 9.0)}]
```
So, another -and, perhaps, better- workaround may be to wrap `actions` in a `numpy` array...

And, of course, this issue is "only" critical for policies that return their batched `actions` as plain lists.
(Isn't that most of them, BTW? 😏)

**Comment by ericl** [comment]
This bug does seem to be breaking unbatch of normal lists, I'm just not sure why it doesn't cause test failures. @richardliaw @sven1977 can you guys triage this?

**Comment by sven1977** [comment]
Taking a look now.

**Comment by sven1977** [comment]
This is actually not a bug, only the example in the docstring of the function should be changed to use np.arrays instead of lists. Normally, if you do a (batched) forward pass through some model and compute your actions using that, your results would be dim-0 batched as torch/tf/numpy tensors, so this is ok.
This PR here enhances the docstring and gives a better example for using this function:
https://github.com/ray-project/ray/pull/18967

**Comment by mehes-kth** [comment]
> This is actually not a bug, only the example in the docstring of the function should be changed to use np.arrays instead of lists. Normally, if you do a (batched) forward pass through some model and compute your actions using that, your results would be dim-0 batched as torch/tf/numpy tensors, so this is ok. This PR here enhances the docstring and gives a better example for using this function: #18967

The world your describing, where all policies return dim-0 batched tensors, seems to be
outside our known universe.  Have you checked all policies, examples, and documentation?
I guarantee that simple Python lists are fairly common; especially in the custom policies
section, but also in bona fide RLlib omplementations.

If this is not a bug, then all RLlib policies should be converted; so, they _actually_ return
tensors not pure lists, and *all* examples and documentation needs to be adjusted as well.
Quite a bit of work, potentially...
