### ISSUE TITLE
[tune] better file-descriptor resource management for 21*c5.24xlarge (2000cores)

### ISSUE THREAD

**Issue by snmhaines** [ray-project/ray#10105]
I am trying to run a large cluster on EC2 (21 x c5.24xlarge for Ubuntu 18.04), using Ray 0.8.6  but experiencing this run-time error:-
```
"COULD NOT CREATE A LOGGINGFILE .... Could not create logging file: Too may open files"  
```
This has recently been reported before (issues #6583  and #7169), but neither of the solutions used therein seem to work.  I increased  ulimit in the head_start_ray_commands from 65536 to 1000000, then 10000000.  I also tried 1000000 in the worker config as well - neither made any difference: i.e. the fault occurred at about the same time in any case.  I presume that 2^16 is a hard limit determined elsewhere.

I also tried "sync_to_driver=False" in the head-node config, after Ray is started.  This did have a noticeable effect:  the error didn't occur, at least not until I aborted the test at 30 minutes, but the performance of the cluster was crippled  - estimate that it would have taken about 20 times as long to run the test.

The test itself only involves opening and then closing one small text input file (local to each worker) on initialization, and I have run it with no problem on a cluster with a head-node and two workers.  I am guessing that the overload is being caused by the generation of all the log files on the head node, so I need a way of effectively stopping that.

**Comment by richardliaw** [comment]
Can you try disabling logging? i.e. `tune.run(loggers=None`?

**Comment by snmhaines** [comment]
I haven't used tune before; is it in ray, or do I have to install it separately, and should the command be run as part of the setup, on all nodes, before or after starting ray?

By the way, I am actually attempting 1000 cores (1008, to be precise) because I have disabled hyperthreading.

**Comment by richardliaw** [comment]
Ah, I thought `sync_to_driver` was a Ray Tune specific thing. I'll close this issue in lieu of #10104
