### ISSUE TITLE
sourceforge.net dependency for building boost for manylinux whl

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#1012]
Seems like sourceforge is down (for downloads), maybe a list of mirrors would be good?  Maybe there isn't a good list - haven't looked.

**Comment by robertnishihara** [comment]
Good point, looks like it's back up now, but I was running into this issue yesterday as well.

**Comment by virtualluke** [comment]
guess I missed the window of it being up, down for me still

**Comment by robertnishihara** [comment]
Looks like we can download them from e.g., https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2.

**Comment by robertnishihara** [comment]
Hopefully this is fixed by #1019.
