### ISSUE TITLE
How about Further promote this project?

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [ray-project/ray#10132]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
I'd like write a chinese-version's docs about this docs,for more people can contribute this project,may i?

**Comment by richardliaw** [comment]
yeah sure! feel free to push a PR - https://www.slideshare.net/streetcleaner/writing-multi-language-documentation-using-sphinx

**Comment by simon-mo** [comment]
Totally! I would be more than happy to review it.

**Comment by Wheeeeeeeeels** [comment]
ok,thank you!
