### ISSUE TITLE
Ray got stuck on requesting more resources but actually needs less

### ISSUE THREAD

**Issue by zmonoid** [ray-project/ray#10144]
### Ray got stuck on requesting more resources but actually needs less.

Since my script only need one GPU, so I set:
```
export CUDA_VISIBLE_DEVICES=0
```

My script is given below, it shows the following warning and program stuck here:

>  INFO trainable.py:251 -- Trainable.setup took 21.559 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2020-08-17 03:33:33,853 WARNING worker.py:1134 -- The actor or task with ID ffffffffffffffff2512146c0100 is pending and cannot currently be scheduled. It requires {GPU: 0.100000}, {CPU: 1.000000} for execution and {GPU: 0.100000}, {CPU: 1.000000} for placement, but this node only has remaining {node:node_ip: 1.000000}, {GPUType:X: 1.000000}, {CPU: 19.000000}, {memory: 78.271484 GiB}, {object_store_memory: 25.878906 GiB}. In total there are 0 pending tasks and 5 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale

```
ray: 0.8.7
python: 3.6.7
pytorch: 1.4.0
os: ubuntu16.04
```
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ . ] I have verified my script runs in a clean environment and reproduces the issue.
- [ . ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

Below is a minimal example for reproduction:

```python
import os
os.environ['CUDA_VISIBLE_DEVICES']='0'
import ray
from ray import tune
import torch
import torch.nn as nn
import torch.nn.functional as F

@ray.remote(num_gpus=0.1)
class Actor:
    def __init__(self, rank):
        self.network = nn.Sequential(
            nn.Linear(32, 128),
            nn.ReLU(),
            nn.Linear(128, 128)
        )

        self.network.to(0)
        self.rank = rank

    def sample(self):
        x = torch.randn(32, 32).to(0)
        y = torch.randn(32, 10).to(0)
        z = self.network(x)
        return z.detach(), y, self.rank


class Agent:
    def __init__(self):
        self.network = nn.Sequential(
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )
        self.network.to(0)

        self.optimizer = torch.optim.Adam(self.network.parameters(), 1e-3)
    
    def train(self, z, y):
        z = self.network(z)
        loss = F.mse_loss(z, y)
        
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        return loss.detach()

class Trainer(tune.Trainable):

    def _setup(self, config):
        
        self.actors = [Actor.remote(rank=rank) for rank in range(5)]
        self.agent = Agent()
        self.sample_ops = [a.sample.remote() for a in self.actors]

    def _train(self):
        done_id, self.sample_ops = ray.wait(self.sample_ops)
        data = ray.get(done_id)
        z, y, rank = data[0]
        loss = self.agent.train(z, y)
        self.sample_ops.append(self.actors[rank].sample.remote())
        return dict(loss=loss.item())


if __name__ == '__main__':
    ray.init()
    tune.run(
        Trainer,
        name='test',
        verbose=1,
        stop=lambda trial_id, result: result['training_iteration'] > 100,
        resources_per_trial={"gpu": 1},
    )
    print("Done")
```

**Comment by richardliaw** [comment]
How many GPUs does `Agent` need? If 0, then the right way to do this is:

```python
if __name__ == '__main__':
	NUM_WORKERS = 5
    ray.init()
    tune.run(
        Trainer,
        name='test',
        verbose=1,
        stop=lambda trial_id, result: result['training_iteration'] > 100,
        resources_per_trial={"gpu": 0, "extra_gpu": 0.1 * NUM_WORKERS},
    )
    print("Done")

**Comment by richardliaw** [comment]
Here is some documentation - https://docs.ray.io/en/latest/tune/api_docs/trainable.html#advanced-resource-allocation

I am thinking about adding a guide for resource management in Tune. Let me know if you'd find that useful

**Comment by zmonoid** [comment]
@richardliaw ```Agent``` needs 0.5 gpu, each actor needs 0.1 gpu.

**Comment by richardliaw** [comment]
Got it; then try this:
```
if __name__ == '__main__':
	NUM_WORKERS = 5
    ray.init()
    tune.run(
        Trainer,
        name='test',
        verbose=1,
        stop=lambda trial_id, result: result['training_iteration'] > 100,
        resources_per_trial={"gpu": 0.5, "extra_gpu": 0.1 * NUM_WORKERS},
    )
    print("Done")
```

**Comment by zmonoid** [comment]
@richardliaw Thanks for your answer! It works.
