### ISSUE TITLE
[rllib] Add ability to register custom architectures in rllib train script (custom environments, models, etc)

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#10146]
### Describe your feature request
In the train.py script in rllib, it is not possible to add custom architectures. Although one could copy the train.py script and modify it to include the registration code, it is not intuitive for beginners what is the best practice. Alternatively, if a user wanted to create their own training script from scratch, it may be very cumbersome to learn all the boilerplate code necessary to get it working. As such, a feature-complete training script is desirable to empower users to test all custom functionality of rllib with minimal code modification and abstraction. The only necessary parts to change would be to create the custom functionality subclassing the API.
That being said, how would one go about implementing this? One possible solution could be to have the file path to the registration module be defined in the config. Another could simply load all registration scripts in the current directory of execution. Whatever the method, this would be up to the rllib team to decide which is easiest and intuitive to implement.
Thanks!

**Comment by ericl** [comment]
One option is to allow the model to be specified as a package path (e.g., "your.package.CustomModel"), and RLlib can try to auto import this. We already support this for custom envs, and it is quite convenient.

Of course, this still isn't as flexible as being able to register any arbitrary class/function.

cc @sven1977

**Comment by juliusfrost** [comment]
Could you point me to where this is implemented for custom envs? I couldn't find it in the docs

**Comment by ericl** [comment]
This is the line that does it, using the from_config utility:
https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L568
