### ISSUE TITLE
[RLLib] Torch Policy modification of action selection functions' input

### ISSUE THREAD

**Issue by raphaelavalos** [ray-project/ray#10158]
### Describe your feature request

Hello,

In its current form the action selection in PyTorch uses either `compute_actions_from_dict` or `compute_actions` (the latter creates an input dict). Both functions relies on `_compute_action_helper` that takes as input a dict and calls either:
* `action_sampler_function` which takes just the observation and there is no way provide a state.
* `action_distribution_fn` same as above.
* the model which takes the full dict.

IMO, it would make more sense if `action_sampler_function` and `action_distribution_fn` take as input the full input dict instead of just the observations. This would allow the use of RNNs in DQN, DDPG ... #9206

I can make a PR with those changes.

@ericl @sven1977 What do you think?

**Comment by ericl** [comment]
This will be resolved as we finish the trajectory view API (which will basically accomplish this)--- then we can remove the legacy compute_actions().
