### ISSUE TITLE
[rllib] IMPALA rmsprop throws error

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#10155]
### What is the problem?
Running IMPALA with `opt_type `set to "rmsprop" throws the following error.

AttributeError: 'RMSprop' object has no attribute 'compute_gradients'

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.7, Python 3.7, TF 2.2, OS Rhel 
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
[cart-pole-impala.txt](https://github.com/ray-project/ray/files/5084191/cart-pole-impala.txt)

**Comment by ericl** [comment]
cc @sven1977

**Comment by chwhiteley** [comment]
The error comes from the call of torch.optim.RMSProp when it should be torch.optim.RMSprop (there should be no capital letter in "prop") in the choose_optimizer function. I have solved this issue by overriding the choose_optimizer function and removing this capital letter in RMSProp.

As a side note, I would like to point the difference in the "eps" values given to torch.optim.RMSprop. This epsilon value is 0.1 in the impala config, while the default value is 1e-8 in torch.optim.RMSprop. Maybe you should check that this value is ok.
