### ISSUE TITLE
Potential memory leak of a local `ObjectRef` reference

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#10151]
I have some actor class and I want them to run some tasks in a while loop, or just complete some tasks and I don't want the result. So sometimes I don't call ray.get to get the result. Will it cause Redis memory to continually grow?
What will happen when I just call `foo.func.remote()`? And how ray set the expire protocol of Redis?

**Comment by stephanie-wang** [comment]
As of Ray 0.8, the majority of metadata is no longer stored in Redis, so Redis memory should only be an issue in extreme cases. Currently, it is used to store the actor and object directories. Actor entries are automatically cleaned up when the actor dies or goes out of scope. Object entries are automatically cleaned up when the `ObjectRef` goes out of scope.

So, as long as you're calling `del` on the return value of `foo.func.remote()` when you no longer need the result, system memory should stay low. Sounds like you don't need to do anything at all as long as you're not storing the `ObjectRef` returned by `foo.func.remote()`.

**Comment by Seraphli** [comment]
But actually we are having a slowly increasing memory problem. We can random get a key from redis using randomkey, and we find out that this key has a object prefix and it has been 35 hours since last modification. So the key definitely is a object that we don't want.

**Comment by Seraphli** [comment]
Is there any method that we can decode the real value from redis so that we can know what is stored and debug?

**Comment by stephanie-wang** [comment]
Are you sure that you're deleting the `ObjectRef` returned by `foo.func.remote()`?

> Is there any method that we can decode the real value from redis so that we can know what is stored and debug?

Unfortunately, this is a bit difficult. But you can use the `ray memory` bash [command](https://docs.ray.io/en/latest/package-ref.html?highlight=memory#ray-memory) to see if there are objects that are still in reference that you no longer want.

**Comment by Seraphli** [comment]
> Are you sure that you're deleting the `ObjectRef` returned by `foo.func.remote()`?
> 
> > Is there any method that we can decode the real value from redis so that we can know what is stored and debug?
> 
> Unfortunately, this is a bit difficult. But you can use the `ray memory` bash [command](https://docs.ray.io/en/latest/package-ref.html?highlight=memory#ray-memory) to see if there are objects that are still in reference that you no longer want.

Actually I don't save any return. Like I said I simply just call the remote function.
For example:
```
for _ in range(100000):
    foo.func.remote()
```
Something like this

**Comment by Seraphli** [comment]
![image](https://user-images.githubusercontent.com/1586755/90466484-82667580-e144-11ea-8437-4298218812ea.png)
I check the memory using `ray memory`, and it shows a lot of unknown function and size. I don't what is causing it.
```
        def method(self, *args, **kwargs):
            return ray.get(getattr(self.obj, n).remote(*args, **kwargs))
```
And some idle worker is also having a lot of unknown objects.
![image](https://user-images.githubusercontent.com/1586755/90467252-4fbd7c80-e146-11ea-93eb-c69afda32778.png)
![image](https://user-images.githubusercontent.com/1586755/90467290-6f54a500-e146-11ea-9d10-857f761fa3dc.png)

**Comment by rkooo567** [comment]
Btw, if you don't store the returned value of remote, the objects are supposed to be garbaged collected. We are doing reference counting for that.

**Comment by rkooo567** [comment]
@Seraphli Is there any way we can reproduce this result?

**Comment by Seraphli** [comment]
@rkooo567 I can try to make a minimal demonstration. But because we run the program for about 4 days, so we can notice the growth issue.

**Comment by rkooo567** [comment]
Also another note, local reference means you have a reference to the object in your drivers or workers.

**Comment by Seraphli** [comment]
I manage to find out why the call site is unknown and fix it. Now the call site is able to show. But another problem is I use a wrapper function to wrap `ray.get(obj.func.remote())`, so they all show the wrapper function. Can I change the call stack or the call site with arguments?

**Comment by Seraphli** [comment]
I try to make a minimal demo, but because I don't know the reason for this issue, I can hardly find a way to reproduce this. Perhaps you guys can provide some advice about the call site so that I can find the right spot that causing this problem. Right now I wrote almost all code based on the wrapper function, so completely remove the wrapper function will take a lot of time.

**Comment by stephanie-wang** [comment]
Hmm sorry there's not much more to say about the call site; it just records the line number where the `.remote()` call was made. Perhaps you could try "bisecting" by duplicating the wrapper function and changing the half the calls to that function, etc.

**Comment by mfitton** [comment]
@Seraphli quite a coincidence, but I'm planning to merge a PR to the Ray dashboard later today that will give 3 stack frames instead of one so that you can more easily find the call-site.
Perhaps you can check out the nightly build later today and see if the additional context helps you find the issue.

**Comment by Seraphli** [comment]
@mfitton Thank you for replying to me. I actually need a detailed call-site when analyzing memory. The dashboard is fine for now. It can show which actor is running. But it can not provide any detail about the memory.

**Comment by Seraphli** [comment]
I probably find the reason for the memory issue. Here is a minimal demo for reproducing this issue.
```
import ray
import time
import logging
import numpy as np
import sys
from multiprocessing import shared_memory


class NPSharedMemory(object):
    def __init__(self, arr, name=None):
        self.arr_shape = arr.shape
        self.arr_dtype = arr.dtype
        if name:
            self._attach(name)
        else:
            self._create(arr)

    def _create(self, arr):
        self.shm = shared_memory.SharedMemory(create=True, size=arr.nbytes)
        self.shm_name = self.shm.name
        self.array = np.ndarray(
            self.arr_shape, dtype=self.arr_dtype, buffer=self.shm.buf)
        np.copyto(self.array, arr)

    def _attach(self, name):
        self.shm = shared_memory.SharedMemory(name=name)
        self.shm_name = name
        self.array = np.ndarray(
            self.arr_shape, dtype=self.arr_dtype, buffer=self.shm.buf)

    def __getstate__(self):
        return {
            'shm_name': self.shm_name,
            'arr_shape': self.arr_shape,
            'arr_dtype': self.arr_dtype
        }

    def __setstate__(self, state):
        self.__dict__.update(state)
        self._attach(self.shm_name)


@ray.remote
class A(object):
    def __init__(self):
        self.storage = None
        self.size = 100000

    def create(self):
        array = np.zeros((self.size, 30, 20))
        self.storage = NPSharedMemory(array)
        self.b = B.remote(self.storage)

    def insert(self):
        for i in range(self.size):
            t = np.ones((30, 20))
            self.b.func.remote(i, t)


@ray.remote
class B(object):
    def __init__(self, storage):
        self.storage = storage

    def func(self, i, array):
        self.storage.array[i, ...] = array


ray.init(webui_host='0.0.0.0')
a = A.remote()
ray.get(a.create.remote())
print('waiting')
input()
ray.get(a.insert.remote())
print('waiting')
input()
```
Before running `insert` function, `A` created a shared memory which is 458M file in `/dev/shm`.
Memory displayed on dashboard
![image](https://user-images.githubusercontent.com/1586755/90609669-faad6380-e236-11ea-888a-df535dc740f5.png)
And after running `insert` function, B will overwrite all shared memory, and during that, the memory of B process will increase to 500MB.
![image](https://user-images.githubusercontent.com/1586755/90610476-0b120e00-e238-11ea-8bf3-df3e98674f21.png)
![image](https://user-images.githubusercontent.com/1586755/90610496-149b7600-e238-11ea-9a47-504b8186a649.png)
This issue is important for us because we will have several processes accessing one shared memory.

**Comment by Seraphli** [comment]
And I tried to use `ray memory` to see if there is a new object, but there is no useful information.

**Comment by Seraphli** [comment]
We reproduced this issue using multiprocessing in python. So it might be a python problem.

**Comment by Seraphli** [comment]
BTW, here is a code to reproduce this issue in python.
```
import os, psutil
import numpy as np
from multiprocessing import Process, shared_memory

SHM_SIZE = 100000 * 30 * 20


def f(name):
    print('[Sub] (Before) Used Memory of {}: {} MiB'.format(
        os.getpid(),
        psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024,
        ))
    shm = shared_memory.SharedMemory(name=name)
    b = np.ndarray(shape=(SHM_SIZE, 1), dtype=np.float64, buffer=shm.buf)
    for i in range(SHM_SIZE):
        b[i, 0] = 1
    print('[Sub] (After) Used Memory of {}: {} MiB'.format(
        os.getpid(),
        psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024,
        ))


def main():
    print('[Main] Used Memory of {}: {} MiB'.format(
        os.getpid(),
        psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024,
        ))
    shm = shared_memory.SharedMemory(create=True, size=8*SHM_SIZE, name='shm')
    p = Process(target=f, args=('shm',))
    p.start()
    p.join()
    print('[Main] Used Memory of {}: {} MiB'.format(
        os.getpid(),
        psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024,
        ))
    input()
    shm.close()
    shm.unlink()


if __name__ == '__main__':
    main()
```

**Comment by stephanie-wang** [comment]
I don't quite see the problem here. Isn't it expected that B's memory usage should also increase if it is accessing 500MB of shared memory? I believe that the way the dashboard (and also standard bash tools) report the memory usage includes shared memory. So if A and B both access the same shared memory, they will both appear to be using have that many bytes resident. Perhaps there is a memory leak in your end-to-end application, but I don't think the scripts that you've posted would actually produce that.

By the way, Ray also has native support for shared memory objects. You can find more info [here](https://docs.ray.io/en/latest/walkthrough.html#objects-in-ray). We do not support mutable objects, but if you're just using shared memory as a message bus, you can use Ray objects to do that.

**Comment by Seraphli** [comment]
I post an issue on python bug tracker and get the reply I want.
https://bugs.python.org/issue41587
It seems just a display problem. When I use one process to access the shared memory, `htop` displays a memory increment. But when I use 16 processes to access the shared memory, the total memory is not increasing. So it actually won't cause any problem. I will close this issue.
