### ISSUE TITLE
[core] [help] Running `ray start` on the same node in parallel would get port error

### ISSUE THREAD

**Issue by hkvision** [ray-project/ray#10154]
Hi,

I want to ask how is the port chosen and used for worker, within the range of [min_worker_port, max_worker_port]? Is it chosen randomly within this range? (Sorry that I don't go into the details of ray core and need some help on the implementation.)

When I call `ray start` for a raylet, it is starting one worker and one port is needed?

Does the following two errors mean the same thing?
```
# This error message is in 0.8.6; seems to be removed by 0.8.7?
(pid=1024090) F0817 16:07:46.085644 1024090 1024090 core_worker.cc:294]  Check failed: assigned_port != -1 Failed to allocate a port for the worker. Please specify a wider port range using the '--min-worker-port' and '--max-worker-port' arguments to 'ray start'.
(pid=1024090) *** Check failure stack trace: ***

# This is the root error of duplicate ports?
(pid=raylet) terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
(pid=raylet)   what():  bind: Address already in use
(pid=raylet) *** Aborted at 1597694865 (unix time) try "date -d @1597694865" if you are using GNU date ***
(pid=raylet) PC: @                0x0 (unknown)
(pid=raylet) *** SIGABRT (@0x3e8000f9fdf) received by PID 1023967 (TID 0x7fbbf1e81800) from PID 1023967; stack trace: ***
```

Thanks so much for your help in advance!

**Comment by rkooo567** [comment]
> port chosen and used for worker, within the range of [min_worker_port, max_worker_port]

Yes it is correct. The error is probably due to 
1. You have other processes that use the port within that range outside Ray.
2. Or you launched too many workers.

If you just run `ray start`, the default min_worker_port and max_worker_port is from 10000 ~ the end of the port I believe (could be wrong). It also starts `--num-cpus` number of workers by default.

**Comment by hkvision** [comment]
> > port chosen and used for worker, within the range of [min_worker_port, max_worker_port]
> 
> Yes it is correct. The error is probably due to
> 
> 1. You have other processes that use the port within that range outside Ray.
> 2. Or you launched too many workers.
> 
> If you just run `ray start`, the default min_worker_port and max_worker_port is from 10000 ~ the end of the port I believe (could be wrong). It also starts `--num-cpus` number of workers by default.

Hi @rkooo567 Thanks for your reply. Yeah, the port range should be large, so I doubt why this problem occurs...
So you mean for each cpu core, there would be a worker started. If I understand correctly, `ray start ... --num-cpus 10`, would start 10 workers and 10 random ports are needed? Is there any strategy for choosing these ports?
Also, for the workers that are already started, is there any API to get their ports?
Thanks so much.

**Comment by hkvision** [comment]
Hi @rkooo567 

I use `netstat -tupln` to check the ports and find the following is the result of just started ray:
```
tcp6   	0  	0 :::10000            	:::*                	LISTEN  	23542/ray::IDLE	 
tcp6   	0  	0 :::8080             	:::*                	LISTEN  	13988/java     	 
tcp6   	0  	0 :::10001            	:::*                	LISTEN  	23545/ray::IDLE	 
tcp6   	0  	0 :::8081             	:::*                	LISTEN  	14320/java     	 
tcp6   	0  	0 :::10002            	:::*                	LISTEN  	23550/ray::IDLE	 
tcp6   	0  	0 :::10003            	:::*                	LISTEN  	23544/ray::IDLE	 
tcp6   	0  	0 :::33363            	:::*                	LISTEN  	23478/redis-server  
tcp6   	0  	0 :::10004            	:::*                	LISTEN  	23549/ray::IDLE	 
tcp6   	0  	0 :::10005            	:::*                	LISTEN  	23540/ray::IDLE	
```
If I'm understanding correctly, each `ray::IDLE` is one worker corresponding to one core right?
As if I run for several times, the port always start from 10000 exactly and increments by 1 each time right?
So if I'm understanding correctly, the port is not randomly selected, but starting from min-worker-port, increments every time and skips the unavailable ports?
Hope to get some help! Thanks!

**Comment by hkvision** [comment]
Oh, after checking the code, I find setting `RAY_USE_RANDOM_PORTS` and `--min-worker-port 0 --max-worker-port 0` will use random ports. But the problem still exists... I'll further check it...

**Comment by hkvision** [comment]
Hi @rkooo567 After further investigations, I think the problem should be executing `ray start` to start raylets in parallel. To be more specific to reproduce this issue:
1. I run `ray start --head --include-webui true --num-cpus 4 --redis-password 123456` on the command line first.
2. I run the following Python code to start multiple raylets in parallel:
```
from multiprocessing import Pool

import time

command = "/home/kai/anaconda2/envs/ray/bin/python /home/kai/anaconda2/envs/ray/bin/ray start --address ip:port --redis-password 123456 --num-cpus 4"

def start_ray(work_data):
   # time.sleep(work_data[1])
   print(work_data[0])
   import subprocess
   import os
   pro = subprocess.Popen(
       work_data[0],
       shell=True)
   pro.communicate()

p = Pool(3)
p.map(start_ray, ((command, 1), (command, 2), (command, 3)))
import ray
ray.init(address='auto', redis_password='123456')
print(ray.available_resources())
```
When I run the above code, the total available CPUs is only 8, and when I check the logs for raylet under /tmp/logs, I got the port error described above.

But if I start the raylets sequentially, namely unremark the time.sleep line in the above code, everything is fine and I got 16 CPUs.

So is it the case that finding an available port is monopoly and can't be performed at the same time?
Hope to get some suggestions or comments on this.

**Comment by rkooo567** [comment]
> If I'm understanding correctly, each ray::IDLE is one worker corresponding to one core right?
As if I run for several times, the port always start from 10000 exactly and increments by 1 each time right?
So if I'm understanding correctly, the port is not randomly selected, but starting from min-worker-port, increments every time and skips the unavailable ports?

Yes. Everything here is correct.

- ray start will start --num-cpus number of IDLE workers of which occupy a single port respectively.
- from --min-worker-port to --max-worker-port, the port values are incremented by 1. 

I think you can probably resolve the issue by specifing different worker port range for each ray start commands.

**Comment by rkooo567** [comment]
I am sorry that I didn't notice your "run ray start in parallel".

**Comment by rkooo567** [comment]
Btw, if you use ray start in parallel, you should make sure all ports are not conflicted. You should specify these ports (as of 0.8.7)

```
--node-manager-port
--object-manager-port
--port
--gcs-server-port
--min-worker-port # range
--max-worker-port # range, should not include other ports in this range.
```

**Comment by hkvision** [comment]
Hi @rkooo567 Thanks so much for your quick reply.
I tried to add port constraints by modifying the code segments above to the following:
1. For ray master command: `ray start --head --include-webui true --num-cpus 4 --redis-password 12345 --port 50000 --min-worker-port 20000 --max-worker-port 25000 --gcs-server-port 40000 --node-manager-port 21000 --object-manager-port 31000`
2. For raylets parallel command:
```
/home/kai/anaconda2/envs/ray/bin/python /home/kai/anaconda2/envs/ray/bin/ray start --address 10.239.158.49:50000 --redis-password 12345 --num-cpus 4 --min-worker-port 10000 --max-worker-port 11000 --node-manager-port 22000 --object-manager-port 32000
/home/kai/anaconda2/envs/ray/bin/python /home/kai/anaconda2/envs/ray/bin/ray start --address 10.239.158.49:50000 --redis-password 12345 --num-cpus 4 --min-worker-port 12000 --max-worker-port 13000 --node-manager-port 23000 --object-manager-port 33000
/home/kai/anaconda2/envs/ray/bin/python /home/kai/anaconda2/envs/ray/bin/ray start --address 10.239.158.49:50000 --redis-password 12345 --num-cpus 4 --min-worker-port 14000 --max-worker-port 15000 --node-manager-port 24000 --object-manager-port 34000
```

After doing this, I still only got 8 CPUs, namely only one raylet is successfully started. After checking the port, I can find the worker ports 14000-14003, the node-manager-port 24000 and object-manager-port 34000 (So only the third raylet is successful).
There is still port conflict. What am I doing wrong?

**Comment by hkvision** [comment]
BTW, may I ask what is the strategy of choosing ports? If I set `--min-worker-port 0`, then everything would be random right? Then there are plenty of ports to choose from and in theory the probability that two workers get the same port would be minimal. But as I experiment, the probability is 100%. Just curious why is that?

**Comment by rkooo567** [comment]
Ah, I think I saw the issue. You just need to run `ray start --head` in a head node, and `ray start --address` only once in a worker node. What's the reason why you run `ray start --address` in parallel in the same node? Also, are you running those commands in the same node as the master node?

**Comment by hkvision** [comment]
Yeah, I'm running all the commands on the same node. Namely I have one machine, start one master first and start several raylets in parallel.

I'm working on [RayOnSpark](https://medium.com/riselab/rayonspark-running-emerging-ai-applications-on-big-data-clusters-with-ray-and-analytics-zoo-923e0136ed6a), not sure whether you have heard of our work. The details may be not easy to talk in several words, but simply speaking we use Spark tasks to start ray in parallel across the Spark cluster. For Spark standalone, the standalone cluster can be on a single machine and thus with our design it is happening that all the raylets are started on one node in parallel.

So normally, it is recommended to only run `ray start` once to create only one raylet on one node? I think running for multiple times on one node sequentially also has no problem. The problems only exists if I do this in parallel (since Spark does it in parallel). I can make our implementation not to execute in parallel, but I'm just curious why this port conflict happens in the parallel settings.

**Comment by rkooo567** [comment]
I definitely heard of that :)! It was the project from Intel right? 

> it is recommended to only run ray start once to create only one raylet on one node

Yes! It is definitely possible to have multiple ray instances in a single node, but there might not be any noticeable benefit other than that they are logically separated & used for testing to simulate multi nodes (lmk if you guys know anything else!). The typical workflow of Ray is to have a single instance per node (ray start --head for a head node, and ray start --address="head_node_address" on worker nodes). That says, we don't test parallel ray start as it is not a common use case (thus there might be bugs). We also have several issues in port assignment such as TOCTOU everywhere, so that could be the cause as well (this is what we are trying to improve). 

I might need to dig into this, but there's a possibility the worker ports are selected deterministically.

**Comment by hkvision** [comment]
Yeah, our team is working on RayOnSpark.

Yes, for a single node, I think `ray.init()` is good enough. I encounter this problem due to our implementation of RayOnSpark as for Spark standalone mode, the cluster can be a single node or several different nodes and RayOnSpark would start multiple raylets in parallel on one machine for the single node case. 

Since I'm not familiar with C++, I can't go further to debug the port assignment details =.= You can use the code I provide above to reproduce. Tell me if there's further progress :). This is not urgent, so hope I don't take too much of your time and you may take a look when you are free.
Again thanks so much for your help.

**Comment by gduvauchelle** [comment]
Hello,

We have a shared on-premises cluster managed by Slurm. Most of the time, Slurm starts multiple ray nodes at the same time on one physical machine, and I get the same exception as in this issue. I tried different combination of parameters related to ports but it did not work. It still does not work with the latest dev wheel. 
This bug is reproducible on a laptop by lanching two ray nodes at the same time in background processes with bash.

I have read the page about slurm in the ray documentation but we cannot afford to allocate an entire cluster node for each ray node, users have to ask for multiple but smaller ray nodes to optimise queuing and ressource usage.

This issue is preventing us from parallelizing our existing software that uses ray on our cluster, so this issue is critical for us. 

It is also important for Slurm support in general, since it is mandatory on a cluster managed by slurm shared among many users to have the possibility to start multiple ray nodes on one machine.

Is there an update on this or a workaround to make it work ?

**Comment by eedalong** [comment]
@rkooo567 hi, do we have any progress on this problem? We also encountered this problem when we want to start ray in different process, i.e. we view a machine node as multiple smaller virtual nodes
