### ISSUE TITLE
[core] Help regarding two warnings

### ISSUE THREAD

**Issue by Patol75** [ray-project/ray#10152]
Hi,

I am using Ray to parallelize a Python 3 script across a university cluster. The operating system is CentOS Linux release 8.2.2004 (Core) and the cluster executes PBS Pro 19.2.4.20190830141245. I am using Python 3.7.4 and Ray 0.8.7.

I start ray using
`/path/to/ray start --head --port=6379 --redis-password=$redis_password --memory $((90 * 1024 * 1024 * 1024)) --object-store-memory $((40 * 1024 * 1024 * 1024)) --redis-max-memory $((20 * 1024 * 1024 * 1024)) --num-cpus 48 --num-gpus`

then initialize with
`ray.init(address='auto', redis_password=args.pw, ignore_reinit_error=True, driver_object_store_memory=20 * 1024 * 1024 * 1024)`

and decorate the function of interest as below
`@ray.remote(memory=2 * 1024 * 1024 * 1024)`

The script executes with success and the results I obtain make sense, with an impressive speed-up. However, I get the following two warnings:

- 2020-08-17 17:16:44,289 WARNING worker.py:1134 -- Warning: The remote function `__main__.foo` has size 220019409 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.

- 2020-08-17 17:17:10,281 WARNING worker.py:1134 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.

With respect to the first warning, could anyone help me understand if there is something I can do to avoid it, and possibly explain how concerning the memory issues can be?

For the second warning, could someone point me toward the meaning of the warning and the reason why it is occurring?

Thank you for any help.

Thomas

**Comment by richardliaw** [comment]
What does your `foo` function look like? Are you including anything in its scope? For example,

```
x = Array()

@ray.remote
def test():
    y = x * x
```
^ this will cause the size of the function to grow significantly. In order to avoid this, you should do:

```
x = Array()
x_id = ray.put(x)

@ray.remote
def test(g):
    y = g * g

test.remote(x_id)
```

**Comment by Patol75** [comment]
@richardliaw Thank you for your input.

The function `foo` is sort of a `main` function which calls further functions which, in turn, can call other functions. `foo`, however, is the only function which is decorated with `@ray.remote`. Do I need to decorate all other functions as well?

I also have Scipy Interpolator objects that each worker needs to have access to. According to your answer, I have gathered them all in a dictionary, used `put` to generate a reference and passed the reference to the remote call. I have then used `locals().update(dict)` within the `foo` function to extract the dictionary entries as variables, but it looks like it is not the best idea as the code execution has significantly slowed down. Moreover, I still get the Warning, which I guess points toward the fact that `foo` calls other functions?

**Comment by Patol75** [comment]
@richardliaw Thank you for your help, and sorry for my previous answer (deleted) which was missing your point.

The `foo` function is the main function of the program: it calls other functions, which themselves can call additional functions and make use of objects defined in the outermost scope (either immutable or callable, such as Scipy Interpolator objects). Each call to `foo` is fully independent, hence why the program benefits from the distribution of this function over several workers. My current Ray implementation looks like the following:
`if __name__ == '__main__':
    ray.init(num_cpus=6, local_mode=False)
    futures = [foo.remote(i) for i in zip(*np.asarray(bar == 0).nonzero())]
    waitingIds = list(futures)
    while len(waitingIds) > 0:
        readyIds, waitingIds = ray.wait(
            waitingIds, num_returns=min([var, len(waitingIds)]))
        for tuple_of_results in ray.get(readyIds):
            # Do something with the results
    ray.shutdown()`
My understanding is that, as `foo` is in the only function that I require to execute in parallel (in the sense that all other functions will only be called by `foo`), it is the only one that I need to decorate with `remote`.

Now, if I modify this implementation (and the definition of all functions which make use of the objects in question) according to your template, I run into the following error:
`File "interpnd.pyx", line 150, in scipy.interpolate.interpnd.NDInterpolatorBase.__call__
  File "interpnd.pyx", line 850, in scipy.interpolate.interpnd.CloughTocher2DInterpolator._evaluate_double
  File "interpnd.pyx", line 858, in scipy.interpolate.interpnd.CloughTocher2DInterpolator._do_evaluate
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only`

This error occurs in the innermost function that is trying to use the object; the function is not decorated and I have not called `ray.put` on it (provided it makes sense).

Would you have further input on what is going on here?
Thank you.

**Comment by Patol75** [comment]
@richardliaw I think I have addressed all the Warnings and Errors mentioned in this thread by re-structuring my program as detailed [here](https://stackoverflow.com/a/63556897/10640534). Also, it is likely the `ValueError` yielded upon calling Scipy objects is not Ray-related but, instead, Scipy-related as described in this [thread](https://github.com/scipy/scipy/issues/9740). In any case, thank you for your help and, I guess, feel free to close the thread.
