### ISSUE TITLE
[rllib] Issues with PPO model performance after restoration (observation filter)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1016]
In the rl exercises https://github.com/ray-project/tutorial/tree/master/rl_exercises, some users noticed the restored PPO models had slightly lower performance when using MeanStdFilter. This is likely since the filter state is not correctly restored.

cc @robertnishihara @pcmoritz

**Comment by richardliaw** [comment]
This is likely related to #941

**Comment by ericl** [comment]
Fixed in https://github.com/ray-project/ray/pull/1018

**Comment by trevor-a-mccants** [comment]
Is there a chance this bug got re-introduced recently? I'm getting the same problem where my PPO checkpoints don't get the same rewards as it shows while training. When I disable the MeanStdFilter, the checkpoints give the same results that I see while training.
