### ISSUE TITLE
[RFC][tune] write output to ./ray_results instead of ~/ray_results

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10160]
#### Pros
- seems more intuitive (IMO): the output data of a script should be written to a folder as close to the script as possible unless specified otherwise
- it's a bad practice if a script writes to the home directory -@Maltimore 

#### Cons
- breaking change
    - https://github.com/search?q=%7E%2Fray_results&type=Code
- users will need to add `ray_results` to their .gitignore in order to prevent cluttering their git repos
    - most users don't really work on *that* many projects—at least not to the point where this becomes an issue worth complaining about -@Maltimore
    - if users use Tune a lot, they can [add to their global gitignore](https://docs.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) which will reduce the inconvenience
    - if users actually care about reproducibility/full transparency, they'll need to move ~/ray_results to their repo anyway with the current behavior
        - I will admit that most users probably don't want to push `ray_results` though
    - I have to add `.DS_Store` to all my gitignores anyway so I don't really mind

---

CC @richardliaw 

originally discussed in slack a little: https://ray-distributed.slack.com/archives/CNECXMW22/p1597415968294300

**Comment by ericl** [comment]
I'm opposed to this change; users can always set it manually but logging to an external directory such as /tmp, ~/ray_results, etc. is fairly standard.

**Comment by sumanthratna** [comment]
> logging to an external directory such as /tmp, ~/ray_results, etc. is fairly standard

I can see how one can make the argument for `/tmp` (although I would never want this), but I personally don't know of any projects that write to the home folder. 

Here's an imperfect analogy: front-end frameworks generally output builds to a `dist/` or `build/` folder *in the project folder*, right next to the source. Why wouldn't Ray follow suit? 

This is a breaking change, so I fully understand if this is something you won't fix; however, I really can't think of any benefits of writing to `~/ray_results` *over* `./ray_results`.

**Comment by ericl** [comment]
Well, one reason to use a well know folder is it let's infrastructure
automatically launch things like tensorboard to view ray results correctly.
If it's some random folder, it's difficult to provide global services like
this.

Anyways, you can always override it pretty easily to the folder of your
choice.

**Comment by waldroje** [comment]
even within /tmp it would be great in my mind if ray/rllib would put everything inside the /tmp/ray/ path... my /tmp get's littered with ray/rllib output logs... and makes it tough to manage other app outputs, my own usage, and to remove garbage.

**Comment by sumanthratna** [comment]
> even within /tmp it would be great in my mind if ray/rllib would put everything inside the /tmp/ray/ path...

My understanding is that ray already does this: https://docs.ray.io/en/latest/configure.html#logging-and-debugging.

**Comment by ericl** [comment]
We actually used to put things in tmp, but that caused issues since many machines automatically delete all tmp files on restart, causing lost data.

Closing this since status quo is preferred.

**Comment by ndvbd** [comment]
ray_results folder is always killing my server free space, gets huge quickly. Any idea why and how to stop it?
