### ISSUE TITLE
[rllib] Action mask support using -inf for PyTorch is broken

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#10165]
### What is the problem?

Ray 0.8.7

### Reproduction (REQUIRED)
```
# Set inside "num_gpus": 1.
rllib/examples$ p parametric_actions_cartpole.py  --torch
```
hits
```

  File "/home/ubuntu/anaconda3/envs/exp/lib/python3.7/site-packages/tree/__init__.py", line 516, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/ubuntu/anaconda3/envs/exp/lib/python3.7/site-packages/ray/rllib/utils/torch_ops.py", line 121, in mapping
    item.cpu().detach().numpy()
RuntimeError: CUDA error: device-side assert triggered
```

Using this same setup on my custom environment & (torch) model, the error manifests explicitly as: 
* Using StochasticSampling, plus making sure my model return -1e15 for invalid actions: works.
* Using EpsilonGreedy, plus making sure my model return -float('inf') for invalids: ERROR, model weights quickly get trained to NaN.

Suggestion: perhaps using float.min gives better numerical stability.

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
@concretevitamin does this fix the example https://github.com/ray-project/ray/pull/10168/files ?

**Comment by concretevitamin** [comment]
Just that change isn't enough.  See
https://github.com/ray-project/ray/blob/master/rllib/utils/exploration/epsilon_greedy.py#L142
.

**Comment by ericl** [comment]
Pushed another change to that file as well.
