### ISSUE TITLE
[rllib] Create random policy

### ISSUE THREAD

**Issue by Catypad** [ray-project/ray#10178]
Hi! I'm working with **batch RL** and I have an **external env** with two possible actions and I'm using **distributional_q_tf_model** and I would like to create a policy **that always acts randomly**. How can I do it? I have to use the build_tf_policy or I can just do this? Thank you!

`"exploration_config": {
            "type": "EpsilonGreedy",
            "initial_epsilon": 1.0,
            "final_epsilon": 1.0
}`

**Comment by ericl** [comment]
That setting looks like it should work, have you tried it? You can also create a totally custom policy that just returns action_space.sample() for actions: https://docs.ray.io/en/latest/rllib-concepts.html

**Comment by richardliaw** [comment]
Closing because answered.

**Comment by rusu24edward** [comment]
For anyone else who may come across this issue looking for a random policy, this has been done here: https://github.com/ray-project/ray/blob/master/rllib/examples/policy/random_policy.py
