### ISSUE TITLE
[tune] Please add more supports to skorch

### ISSUE THREAD

**Issue by UTUnex** [ray-project/ray#10201]
Skorch is a wrapper of pytorch which makes it have a sklearn API format for easy use. Currently, the support of ray tune to skorch is quite limited. I really hope the excellent algorithms in tune.suggest, and the tune.schedulars can all support skorch in the short future. The most important thing is, please add more examples on these supports.

Recently I have been searching for the ways to apply the (tune.schedulers.HyperBandForBOHB) for my skorch program but I didn't find any solutions and examples and I have to turn to other tools which is very disappointing...

Anyway, please consider my request:)

**Comment by richardliaw** [comment]
Please follow this PR here! https://github.com/ray-project/tune-sklearn/pull/68

**Comment by UTUnex** [comment]
> Please follow this PR here! [ray-project/tune-sklearn#68](https://github.com/ray-project/tune-sklearn/pull/68)

Thank you. I have checked that link and it seems very promising. I just think, though skorch has a sklearn-API format, it's a neural network after all and needs more consideration like parallelism with multiple GPUs, etc. If possible, please also consider these kind of things.

**Comment by richardliaw** [comment]
Right now we only support 1 GPU per model. Can you raise a feature request there?

**Comment by UTUnex** [comment]
> Right now we only support 1 GPU per model. Can you raise a feature request there?

Sorry, but I just found another issue : 'ModuleNotFoundError: No module named 'skopt' '. I read the PR :ray-project/tune-sklearn#68 and think that the skopt has been depreciated but now the error occurs, so I have to install skopt to use the updated tune_sklearn ? or should I wait for another update ?

**Comment by UTUnex** [comment]
Well, I have just installed the skopt and the error disappears, so skopt is indeed required here.

**Comment by richardliaw** [comment]
Hi @UTUnex, are you still running into issues here?
