### ISSUE TITLE
CLI logger silently swallows exceptions

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#10211]
### What is the problem?

If you run `ray up` on a file that does not exist, the exception is swallowed an you get some other random error down the line:
```
UnboundLocalError: local variable 'config' referenced before assignment
```

`ray up does_not_exist.yaml`

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
@richardliaw @maximsmol

**Comment by maximsmol** [comment]
I cannot reproduce on master:
![img](https://i.imgur.com/34j9KYY.png)

**Comment by richardliaw** [comment]
It's because his log_new_style is False - i can push a fix now.

**Comment by ericl** [comment]
Can we enable the new style by default? I am concerned we have an not well tested path enabled by default on master.

**Comment by ericl** [comment]
Can we enable the new style by default? It seems there is insufficient testing for the old version now.

**Comment by maximsmol** [comment]
This isn't related to logging actually, or to the file being missing

**Comment by maximsmol** [comment]
Ah wait nvm, I see how this happens

**Comment by richardliaw** [comment]
@ericl yes, @maximsmol and I will push a PR today

**Comment by maximsmol** [comment]
We actually broke this a while ago, for all uses of `abort` that do not have their own old-style handler. Might be good to try and fix all of them

**Comment by richardliaw** [comment]
Fix for the original issue - https://github.com/ray-project/ray/pull/10212/files
