### ISSUE TITLE
ray submit does not upload new version of code

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#10216]
Is ray submit supposed to upload new version of the "file_mounts" each time"?

Right now, it looks like it doesn't. The file_mounts are only uploaded once when you do "ray up".

So, you may say "just do ray down and ray up again".

But this is pretty inefficient because you have to redownload the docker... Code changes (where the code is in file_mounts) are usually small and quick to reupload versus the entire docker file.

**Comment by richardliaw** [comment]
Nope! try `ray rsync-up yaml`.

**Comment by rkooo567** [comment]
@richardrl Is the suggestion resolving the problem?

**Comment by richardrl** [comment]
@rkooo567 It doesn't work. I guess it's not propagating the rsync to all the worker nodes.

**Comment by richardrl** [comment]
@rkooo567 I verified that the rsync up does not propagate the new files to worker nodes.

**Comment by richardliaw** [comment]
@richardrl can you do `ray rsync-up -A clusteryaml`?

**Comment by richardrl** [comment]
> ray rsync-up -A clusteryaml

This seems to work as expected. Only problem is, and it may not be directly related, but I get a disk space error after running my cluster for a while and rsyncing up even if I'm not writing to disk.. I wonder if ray is constantly serializing logs somewhere that is filling up disk space.

**Comment by richardliaw** [comment]
The disk space might be due to your ray tune logs. Be sure to clean them up over time.

**Comment by richardrl** [comment]
Also, I believe ` ray rsync-up -A my_yaml.yaml` is currently completely reuploading all the mounts, its not incremental

**Comment by rkooo567** [comment]
@richardrl Can you create a feature request?

**Comment by richardliaw** [comment]
I did it just now.
