### ISSUE TITLE
Pin on a specific node or set of nodes in a cluster?

### ISSUE THREAD

**Issue by j4l-Shvn** [ray-project/ray#10237]
Is there a way to pin a remote on a specific node (or set of nodes) in a cluster? Eg. have a parallel (async) io handler on the localhost only.

**Comment by rkooo567** [comment]
1) Yes you are right. If that's the case scheduling will not happen (and the work will hang). So using the IP directly is usually a bad practice when you use autoscaler (especially if you allow downscaling). If you'd like to tackle the locality problem, consider using https://docs.ray.io/en/master/placement-group.html
2) Resources are just key-value pairs. When you specify resources in any way, that just gives the hint to the scheduler. If you say 0.01 to the node resource, that just means you want to schedule on the node that has the specific resource (node) and would like to consume 0.01 of them (as you can see from Richard's example, the default is 1.0 for each node resource). You can think it exists as a sort of hacky way to schedule to a specific node.
