### ISSUE TITLE
[Tune] Have some trials running on GPU and some trials on CPUs

### ISSUE THREAD

**Issue by abelien101** [ray-project/ray#10235]
I only have one GPU and 32 vCPUs on my machine.

When I use `resources_per_trial={'gpu': 1)`, I only have one trial executed at the time, as it waits for the GPU to be released to launch a new trial.

Is it possible to have other trials running in parallel on the available CPUs while one trial uses the GPU, and when the first trial on GPU finishes, it launches a new trial on GPU?

**Comment by richardliaw** [comment]
Unfortunately this isn't possible. You can do this yourself by checking in your training function and acquiring a lock on the gpu via `filelock`.
