### ISSUE TITLE
[ray] Redis CPU usage reach 100%, any way to reduce redis workload?

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#10234]
We open an experiment with over 1000 workers connected to the cluster. And the redis server seems can not handle too many workers. I want to ask how to reduce workload of redis server. May I ask what type of data will be sent to redis?

**Comment by richardliaw** [comment]
what type of experiment are you running? are you using Tune/rllib?

cc @stephanie-wang @wuisawesome @ericl

**Comment by Seraphli** [comment]
@richardliaw We only use ray on our cluster. We build our experiment based just on ray.

**Comment by rkooo567** [comment]
Hmm.. interesting. Redis is not supposed to use that much of cpu and memory. What version of Ray are you using?

**Comment by Seraphli** [comment]
0.8.6. Perhaps we create over 1000+ actor handler cause this problem.

**Comment by Seraphli** [comment]
Another problem is dashboard show `2266 workers / 2112 cores`.
![image](https://user-images.githubusercontent.com/1586755/90858570-104a9680-e3b9-11ea-9cf5-3649112958a1.png)

**Comment by rkooo567** [comment]
Ah, I see. What I explained was the case from 0.8.7 (we had pretty big change from 0.8.6 -> 0.8.7). Can you try bumping up the version? There’s a possibility it’d be fixed.

**Comment by Seraphli** [comment]
@rkooo567 We are using 0.8.7 right now. These issues happened also in 0.8.7.

**Comment by Seraphli** [comment]
I think ray can avoid Redis problem by using one or two backup Redis servers, which will handle some part of the actors' task.
We actually don't have any task for ray to assign to an IDLE worker. We know exactly which PID should handle this task. But it seems all task metadata first will be sent to the main Redis server, then sent to the actor process. I think this causes the overload of the main Redis server.

**Comment by rkooo567** [comment]
Did you try increasing the --num-shards of Redis btw?

**Comment by rkooo567** [comment]
> If raylet raises the timeout exception, does it mean that ray cluster is not ready? Or maybe a new machine joins in the cluster too quickly that Redis is not ready for raylet to create a new connection?

I think close to the latter. The issue looks like it is simply because Redis is too busy, the connection times out. Another suggestion I have is 

1. Increase shard number of Redis.
2. Join nodes more slowly, so that Redis would have less stress. Are you using autoscaler here? 
3. Also, create actors slowly => this might not be relevant anymore.

**Comment by Seraphli** [comment]
We haven't try to use --num-shards. We can try this out. I'm not familiar with Redis sharding. Will it create multiple Redis servers to reduce workload? Will it reduce interactions of the primary Redis server by redirect some interactions to other servers?

**Comment by rkooo567** [comment]
I think it is the latter. I also found this information from online. 

```
I was also having problems with redis CPU usage. My case was many redis connections (clients) and linux default ulimit of 1024 open files.
```

Are you setting ulimit when you run ray start?

**Comment by Seraphli** [comment]
We tried to use sharding, but the primary Redis still has a high workload. And ulimit is set to a very high number, 1024768,  so that is not a problem.
![image](https://user-images.githubusercontent.com/1586755/91001481-62302e00-e5fe-11ea-9b9b-8ba2d370b331.png)

**Comment by rkooo567** [comment]
Hmm interesting. Let me cc @stephanie-wang to see if she's seen anything similar before. Sorry that I cannot find the immediate solution!

**Comment by stephanie-wang** [comment]
@raulchen, is Redis sharding implemented for the GCS service? I don't think it is, right? Do you have any insight here for why the CPU usage is so high?

@Seraphli, can you give some more information about your cluster setup (how many machines) and workload? The relevant types of data that would get sent to redis are:
- actor directory - updated each time a new actor is created or dies
- object directory - updated each time an object > 100KB is created or used on a different node
- heartbeat data - increases with number of nodes

I think there is also profiling data that gets sent to Redis which may be relevant if you're sending many tasks (>100k/s as a ballpark).

**Comment by Seraphli** [comment]
I have tried to create a new connection to bypass this problem. I will send the data directly to some processes now. This greatly reduces the Redis workload.
BTW, the connection timeout is another problem related to our cluster containers. That is not a ray problem.

**Comment by Seraphli** [comment]
And yes, we are sending many tasks, about 50k/s I think.

**Comment by raulchen** [comment]
> @raulchen, is Redis sharding implemented for the GCS service? I don't think it is, right? Do you have any insight here for why the CPU usage is so high?

@stephanie-wang No, GCS service doesn't have sharding.  Besides the "actor/object/heartbeat" tables, there are also a lot of python code that directly accesses Redis, which might also cause issues.

@Seraphli  I'd suggest profiling Redis to find out which data is the culprit first. One tool I tried before is https://github.com/gamenet/redis-memory-analyzer. This can analyze the memory usage proportions of different key types. Another thing we can try is to `tcpdump` the traffic to redis when redis is busy. From the traffic, we can find the most frequent key words.

**Comment by stephanie-wang** [comment]
I think you could also just connect a redis client from command line and runs `KEYS *`. Let us know what you find!

**Comment by stephanie-wang** [comment]
Hey @Seraphli, you might want to try out this new [option](https://github.com/ray-project/ray/pull/10414) that we added to disable task profiling, which can add load to Redis.

You can try it out by installing from the nightly wheels and setting `_system_config={"enable_timeline": False}` in `ray.init()` (or by passing the equivalent json object to `ray start` on the head node).

**Comment by rkooo567** [comment]
@Seraphli I will close this issue since we've merged the possible fix. Please try it and reopen if issues still occur!
