### ISSUE TITLE
module 'ray' has no attribute 'compat' on windows

### ISSUE THREAD

**Issue by vikasmalik22** [ray-project/ray#10240]
### What is your question?
Hi Guys,

I am getting this error when trying to import ray in my notebook while running on windows. 
Is there a workaround or is this a known issue?

Thanks

![Capture](https://user-images.githubusercontent.com/6457663/90890930-72bd8a00-e3ed-11ea-987c-ef559437ae84.PNG)

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray Version 0.8.7

**Comment by ashoj** [comment]
Use conda,  and instead of  'pip install ray'   install with  'conda install ray'

Also don't forget VC++ dependencies,  https://aka.ms/vs/16/release/vc_redist.x64.exe
