### ISSUE TITLE
[tune] Add ConcurrencyLimiter to the Bayesian optimization code examples

### ISSUE THREAD

**Issue by michaelitvin** [ray-project/ray#10270]
As stated [here](https://docs.ray.io/en/latest/tune/api_docs/suggestion.html#concurrencylimiter-tune-suggest-concurrencylimiter), Bayesian optimization doesn't parallelize well and thus needs a `ConcurrencyLimiter`.

Need to add it to the code examples [here](https://docs.ray.io/en/master/tune/examples/bayesopt_example.html) and [here](https://docs.ray.io/en/latest/tune/api_docs/suggestion.html#bayesian-optimization-tune-suggest-bayesopt-bayesoptsearch).

**Comment by richardliaw** [comment]
Do you think it makes sense to do `tune.run(func, search_alg=Bayesian(), max_concurrent=12)` (i.e., just put it into tune.run)?
