### ISSUE TITLE
[Placement Group]Optimize Reschedule When Node Dead

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#10275]
### Describe your feature request
If we have a placement group bundle that requires a unique resource (for example gpu resource when there’s only one gpu node), this can postpone creating until a node with the resources is added.

**Comment by rkooo567** [comment]
cc @ffbin Is this in progress?

**Comment by ffbin** [comment]
I can work on it now since https://github.com/ray-project/ray/pull/13156/files is merged.

**Comment by rkooo567** [comment]
Duplicate https://github.com/ray-project/ray/issues/18309
