### ISSUE TITLE
[ray] Ray show an exception about object may have been evicted

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#10276]
I'm getting these two errors while running. What does it mean? The program seems to continue without any fatal error.
```
[2m[33m(pid=raylet)[0m E0823 17:27:37.349381  1162  1162 object_manager.cc:229] The object manager with ID 2918fec1712fa18a6774c2fff07829d6624c58ab is trying to pull object e62bf4e53cc5e0a0b1a939fb010000807e080000 but the object table suggests that this object manager already has the object. The object may have been evicted.
[2m[33m(pid=raylet)[0m E0823 17:27:37.625520  1162  1162 object_manager.cc:247] The object manager with ID 2918fec1712fa18a6774c2fff07829d6624c58ab is trying to pull object 020477c17e8b5615185a5999010000808f080000 but the object table suggests that this object manager already has the object.
```

**Comment by rkooo567** [comment]
This means GCS says the object is in the local machine, but it doesn't actually have that object, so object manager tries to pull objects from other nodes. 

Did you turn on `LRU_evict=True`? Otherwise, this could be a bug. cc @stephanie-wang

**Comment by stephanie-wang** [comment]
This can happen because the object directory is updated asynchronously, so an object manager may have received an object, evicted it (due to memory pressure), and requested it again before the eviction was reflected in the object directory. It should not be fatal but could indicate that there is memory pressure in the cluster.

**Comment by Seraphli** [comment]
If I call an actor method and pass some data to this actor, then this actor use ray.put to put this data into object store, will ray transfer this data to the local machine of this actor?

**Comment by Seraphli** [comment]
I have tried to create a new connection to bypass this problem.
