### ISSUE TITLE
[rllib] "conv_filters" calculation

### ISSUE THREAD

**Issue by FruechteBini** [ray-project/ray#10284]
Hello guys,
i am trying to use my own environment with rllib.
My observation space is of shape = (4,5,5)
I found this in the documentation regarding the observation shape:
![image](https://user-images.githubusercontent.com/33086953/91045089-9879a780-e616-11ea-88bd-b4455265fe62.png)

I guess the "dim" would be 5 in my case but how do I calculate the "conv_filters"?

Sorry if its a noob question, i am pretty new to RL.

And a follow up question: Is there a way to flatten gym.spaces and remain type gym.spaces, to use it with a fully connected network? Or do i have to do this in the environment itself?

I tried:

```
gym.spaces.flatdim() --> error: policy tuple value 1 (observation_space) must be a gym.Space, got <class 'int'>

gym.spaces.flatten() --> error: policy tuple value 1 (observation_space) must be a gym.Space, got <class 'numpy.ndarray'>
```

Thanks in advance, cheers!

**Comment by grbagwe** [comment]
Did you figure it out ?  I am having the same issue
