### ISSUE TITLE
Configure host for ray dashboard

### ISSUE THREAD

**Issue by tatianafrank** [ray-project/ray#10286]
I have the latest version of Ray and can configure the port but I also need to configure the host since right now it's set to 127.0.0.1 and I need it set to 0.0.0.0

**Comment by simon-mo** [comment]
You can call `ray.init(dashboard_host="0.0.0.0")` or `ray start --head --dashboard-host "0.0.0.0"`. Please let us know if this can solves your use case.

**Comment by wakandan** [comment]
how do I specify the host in command line? Right now I'm using `ray dashboard ...`
