### ISSUE TITLE
memory and object_store_memory units are wrong?

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#10298]
### What is the problem?

The `memory` and `object_store_memory` units seem off. For example, if I start ray with 1GiB of object store memory, the unit shows as 14.0.

### Reproduction (REQUIRED)

```
In [1]: import ray
ra
In [2]: ray.init(object_store_memory=1024**3)
2020-08-24 17:26:49,939 INFO resource_spec.py:250 -- Starting Ray with 24.71 GiB memory available for workers and up to 1.0 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-08-24 17:26:50,381 INFO services.py:1209 -- View the Ray dashboard at localhost:8265
Out[2]: 
{'metrics_export_port': 62197,
 'node_ip_address': '192.168.0.174',
 'object_store_address': '/tmp/ray/session_2020-08-24_17-26-49_931945_77669/sockets/plasma_store',
 'raylet_ip_address': '192.168.0.174',
 'raylet_socket_name': '/tmp/ray/session_2020-08-24_17-26-49_931945_77669/sockets/raylet',
 'redis_address': '192.168.0.174:6379',
 'session_dir': '/tmp/ray/session_2020-08-24_17-26-49_931945_77669',
 'webui_url': 'localhost:8265'}

In [3]: ray.cluster_resources()
Out[3]: 
{'CPU': 16.0,
 'memory': 506.0,
 'node:192.168.0.174': 1.0,
 'object_store_memory': 14.0}
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
We store then in 50MiB chunks (this is a limitation of the old scheduler, and can be fixed with the new one).

**Comment by edoakes** [comment]
I see. That seems to work out for the `memory` unit and for the `object_store_memory` unit it's the same but also multiplied by 0.7 to reserve some memory that can't be allocated to functions/actors (https://github.com/ray-project/ray/blob/master/python/ray/resource_spec.py#L90).

It’s pretty confusing from a user’s perspective that we expose this implementation detail here but not when requesting resources. We should probably try to make these consistent. I think a simple fix would be to multiply out the values in the public API calls so that we're exposing a raw count of bytes here.

**Comment by rkooo567** [comment]
Conclusion: Wait for new scheduler to be merged.

**Comment by wuisawesome** [comment]
> Conclusion: Wait for new scheduler to be merged.

Then change this to more reasonable units. Technically nothing is wrong though. 

I'm going to close this and create a new issue for changing the units to bytes.
