### ISSUE TITLE
Deleting actor crashes logical view in dashboard.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#10294]
This workload seems to crash the logical view in the dashboard.

I tried this on the latest master at 05c103af9480d459ce7d1eb246c059e17e77e5f1

```python
import ray
ray.init()

@ray.remote
class Foo:
    pass

f = Foo.remote()
del f
```

@mfitton

**Comment by mfitton** [comment]
I'll take a look, thanks.

**Comment by mfitton** [comment]
Hey @robertnishihara are you sure the script isn't terminating before you can load the dashboard? I added a sleep at the end and between the creation and deletion of the actor, and I'm unable to reproduce.

**Comment by mfitton** [comment]
Also, are you running this locally?

**Comment by robertnishihara** [comment]
@mfitton sorry looks like I forgot to rebuild the dashboard when I rebuilt Ray.
