### ISSUE TITLE
[tune] Make `Trainable` API clearer/cache state across workers

### ISSUE THREAD

**Issue by michaelitvin** [ray-project/ray#10305]
I need to pass params to the constructor of my `Trainable` subclass.
In the `Trainable.__init__` docstring it says that I should prefer providing a `build()` method rather than my own `__init__`.
Why? Who would use `build()` and when?

-> Also, there is the fact that PyCharm wouldn't appreciate any instance variables I'd declare inside `build()` but not inside `__init__()`.

**Comment by michaelitvin** [comment]
Another point is that the API methods are not precisely defined (at least not in the docstring).
For example, it's not clear from the documentation of `step()` what exactly the return value should hold (it just says `A dict that describes training progress.`).

**Comment by richardliaw** [comment]
Thanks for opening this Michael; these are really good points. I'll add some clarification to the documentation. 

BTW, the general recommendation is to go with the Function API moving forward. Is there anything specific about the class Trainable API that you cannot achieve with the function API?

**Comment by michaelitvin** [comment]
Well my hope was that I would be able to create an instance of my Trainable with all the big configuration already inside, and then do `setup` by passing only the hyper params each time. But I'm not sure anymore that it's possible... So if not, the function API would be equivalent.

**Comment by richardliaw** [comment]
hey @michaelitvin does #10679 help address your problem?

**Comment by michaelitvin** [comment]
Sounds great, thanks!

**Comment by richardliaw** [comment]
Merged then!
