### ISSUE TITLE
[tune] BOHB Max Concurrency

### ISSUE THREAD

**Issue by shaandesaiqb** [ray-project/ray#10348]
### What is your question?

Version: Ray 0.8.7

Tune now has functionality to handle maximum concurrency as a function on top of a search algorithm (via concurrency_limiter). This works perfectly well with hyperopt since the max_concurrency parameter in hyperopt is deprecated. However, the TuneBOHB search algorithm still has a max_concurrency parameter and I'm curious whether this is intentional or whether it should be deprecated.

**Comment by richardliaw** [comment]
This is currently intentional but will be deprecated in the future. I'll take a closer look at this sometime soon - is this currently causing an issue with your usage of Tune?

**Comment by shaandesaiqb** [comment]
it seems to work well in general. I am finding that BOHB occasionally yields an 'unknown trial state' error. However, I am struggling to reproduce it. I cannot be sure if it stems from max_concurrency but that is my initial guess.
