### ISSUE TITLE
[GCS]Limit the number of profile table 

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#10354]
### Describe your feature request
Now, there is no limit to the number of profile table writes, which causes excessive storage usage.

**Comment by rkooo567** [comment]
@ffbin Any progress on this?

**Comment by ffbin** [comment]
@rkooo567 I will finish it next week. I want to save 1-N IDs and recycle them from 1 to N to avoid deleting records. If GCS restarts, i will start with 1. What's your suggestion?
