### ISSUE TITLE
[rllib][tune] Each trial of tune with multi-agent sets the same config for all agents?

### ISSUE THREAD

**Issue by m3t4n01a** [ray-project/ray#10361]
Hi there. 
Sorry if I missed the answer to the question in the docs or issues.

If this is indeed so, how would I be able to have different configs for say two agents in a tune run?

Having a hierarchical system where maybe the observation and action space are quite different, even in scale, would it be reasonable to assume the same agent config for both? I think not. 

I tried first training one for a few iterations, saving the best config, restoring and then training both, but all trials which use different shapes than the restored one fail.

Thanks for any help.

**Comment by m3t4n01a** [comment]
up!

**Comment by richardliaw** [comment]
Can you post a small script, the console output, and your expected behavior?
