### ISSUE TITLE
Reducing message latency

### ISSUE THREAD

**Issue by nm-bls** [ray-project/ray#10360]
My use case is a locally distributed processing system where latency is paramount. 

To test whether Ray fits me, I made a simple benchmark running on a single machine. It initiates a couple of actors in a pipeline topology and runs a task, where the last actor in the pipeline merely passes back a string.

I found out that each nested actor adds 1ms on average, which is sadly too much for my use case.

### Question:
Is there a way to decrease message latency, for instance by adjusting the message polling rate?

*Tested with Ray 0.8.6 and Python 3.8.5 on Fedora 32*

**Comment by rkooo567** [comment]
Can you elaborate what you meant by "nested actors"?

**Comment by rkooo567** [comment]
This is the result from my machine. I added a "warmup" stage that runs this 30 times before.

```
step 0 took 1.373ms
step 1 took 1.349ms
step 2 took 1.411ms
step 3 took 1.618ms
step 4 took 1.48ms
step 5 took 1.406ms
step 6 took 1.438ms
step 7 took 1.321ms
step 8 took 1.651ms
step 9 took 1.352ms
step 10 took 1.362ms
step 11 took 1.176ms
step 12 took 1.186ms
step 13 took 1.313ms
step 14 took 1.213ms
step 15 took 1.233ms
step 16 took 1.299ms
step 17 took 1.183ms
step 18 took 1.412ms
step 19 took 1.186ms
step 20 took 1.173ms
step 21 took 1.429ms
step 22 took 1.318ms
step 23 took 1.188ms
step 24 took 1.163ms
step 25 took 1.187ms
step 26 took 1.84ms
step 27 took 2.412ms
step 28 took 1.792ms
step 29 took 1.906ms
processing took 0.3416416666666667ms per actor in average
```

So, it basically takes 0.3 ms per actor on my Mac machine, which makes sense to me because each actor call should have at least a single grpc round trip. Based on this post, https://groups.google.com/g/grpc-io/c/FO2rZMJP6M4, it looks like grpc round trip cost is around 200 us in Cpp, so 0.3ms is probably almost matching to a raw grpc calls (it didn't take into account of machine spec, so could be wrong, but for your scenario, it should almost match the performance of raw grpc round trip). 

What's the target latency you need? And when you say 1ms, this processing time per actor is 1 ms in your machine?

**Comment by nm-bls** [comment]
The result from my machine looks like this:

```
step 0 took 3.719181ms
step 1 took 4.135623ms
step 2 took 3.737155ms
step 3 took 3.758474ms
step 4 took 5.912392ms
step 5 took 4.32563ms
step 6 took 4.6074ms
step 7 took 5.774003ms
step 8 took 4.888909ms
step 9 took 4.42684ms
step 10 took 4.155671ms
step 11 took 3.720413ms
step 12 took 4.062155ms
step 13 took 4.067946ms
step 14 took 8.90111ms
step 15 took 4.16578ms
step 16 took 3.902595ms
step 17 took 4.152665ms
step 18 took 3.81464ms
step 19 took 3.861067ms
step 20 took 3.881977ms
step 21 took 6.006539ms
step 22 took 4.100167ms
step 23 took 3.20842ms
step 24 took 4.038451ms
step 25 took 3.944153ms
step 26 took 3.650782ms
step 27 took 3.954543ms
step 28 took 4.152625ms
step 29 took 5.477596ms
processing took 1.0732143416666666ms per actor in average
```

So the processing time per actor is ~3x slower on my machine than on yours.

I am on a Laptop with an AMD Ryzen 3700U @2.3Ghz.
By setting the Linux performance governor to "performance" I could slightly reduce the processing time to 0.8ms per actor.

The 0.3ms you are reporting are a bit more in line with what I would have expected.
(Now mind you, I am merely researching technologies right now. I felt that 1ms rtt with (almost) no processing and little serialization was a bit much, but it is just that, a feeling.)

_If you are on a proportionally faster system, I think the issue can be closed as everything works as expected. Thanks a lot for your anwers!_

--

I am building a realtime audio spatialization framework. In total, I got a soft limit of ~60ms total processing time. That includes head tracking, heavy processing and output via headphones. I usually need to pass 8kb of data between actors, which naturally increases serialization time and therefore rtt.

The prototype structure I had in mind includes 7 remote calls. (They don't have to await each others results as in the simple example above, though.)
All in all, this sums up to a latency of around 12ms total on my machine, which sadly is too much "wasted time" for my use case.
