### ISSUE TITLE
[Core] Submission-time task names.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#10371]
### Feature Request

Allow the user to specify submission-time task names, such that the task name is used as the process title (for displaying in the dashboard and debugging) and possibly other areas (e.g. core worker stats). Using the task function name as the user-friendly identifier results in poor UX when many tasks are executed using the same remote function, especially when there exists a semantically meaningful name that could be attached to the task at submission time.

### API and Semantics

The user can specify a task name at submission time:
```python
@ray.remote
def foo(x):
    return x + 1

foo.options(name="my_special_foo").remote(1)
```
Unlike Ray actor names, this would **not** "detach" the task, and global uniqueness of these task names would **not** be enforced. Given the existing semantics for `actor.options(name="foo").remote()`, I'm imagining that this new task name option would only apply for actor and non-actor tasks, not for actor creation.

When viewing the machine view of the Ray dashboard, the current task (in the workers/PID column) for a given core worker would be given by this task name, if set. The task name could also be included in other metrics/stats payloads, such as the core worker stats.

### Possible Implementation

I think that this semantically meaningful task name should be easy to propagate if there's a dedicated field on the `TaskSpec`. If the user supplies a `name` at task submission time, the `task_name` field is set to that; if not, it's set to the task function's name, the current behavior.

Flow - setting field in task spec + using said field to set proctitle:
1. Add a `task_name` field to the `TaskSpec` [class](https://github.com/ray-project/ray/blob/0178d6318ead643fff6d9ed873c88f71fdac52e7/src/ray/common/task/task_spec.h#L30-L216)/[proto](https://github.com/ray-project/ray/blob/fe6daef85e1f3cd2aef12b39487124a6e2dcc2b9/src/ray/protobuf/common.proto#L147-L189) and to the [`TaskOptions` class](https://github.com/ray-project/ray/blob/0178d6318ead643fff6d9ed873c88f71fdac52e7/src/ray/core_worker/common.h#L54-L64).
2. Properly set it on the task spec in [`CoreWorker::SubmitTask`](https://github.com/ray-project/ray/blob/0aec4cbccb5862a7808f98b90696236da9e2a03e/src/ray/core_worker/core_worker.cc#L1257-L1287) and [`CoreWorker::SubmitActorTask`](https://github.com/ray-project/ray/blob/0aec4cbccb5862a7808f98b90696236da9e2a03e/src/ray/core_worker/core_worker.cc#L1398-L1436) to either the user-provided `task_name` if given or set it to the function's name if not (current behavior).
3. Pull the `task_name` off of the `TaskSpec` class in [`CoreWorker::ExecuteTask`](https://github.com/ray-project/ray/blob/0aec4cbccb5862a7808f98b90696236da9e2a03e/src/ray/core_worker/core_worker.cc#L1635-L1757) and pass to language-specific task execution handler.
4. Use said `task_name` to [set the proctitle in the language-specific task execution handlers](https://github.com/ray-project/ray/blob/0aec4cbccb5862a7808f98b90696236da9e2a03e/python/ray/_raylet.pyx#L389).

### Concerns/Open Questions

1. Should the submission-time task name be appended or prepended to the function name, yielding something like `some_module.some_func:{task_name}` or `{task_name}:some_module.some_func`, instead of replacing the function name? Or should the user be expected to craft such a task name in their code and use _that_ as the `.options(name=task_name)` argument if that's what they want? I'm thinking the latter, but having to do that crafting for actor methods may be annoying.
2. Will this be confusing given the existence of named actors and the already established semantics thereof? Should a similar concept be provided for actors, and if so, how could we delineate between detached actors and named actors?

**Comment by rkooo567** [comment]
Btw, from 1.0 (the next version), you can name an actor that is not detached!
