### ISSUE TITLE
[sgd] TorchTrainer from ray.uitls.sgd getting "cuda runtime error (101) invalid device ordinal ray"

### ISSUE THREAD

**Issue by sarvesh211999** [ray-project/ray#10396]
System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04)
- Ray installed from (source or binary): pip
- Ray version: 0.8.7
- Python version: Python 3.8 :: Anaconda, Inc.

[Link to code](https://gist.github.com/sarvesh211999/3e8bdbc2d4a0b493d46a08cba5422991)

I am getting cuda runtime error (101) invalid device ordinal ray, Unable to set local device 
But when I am reducing num_workers to 1 it is running.

**Comment by amogkam** [comment]
@sarvesh211999 are you getting the same error as this? https://github.com/ray-project/ray/issues/9202

**Comment by sarvesh211999** [comment]
Yes I am getting the same error, I tried the fixes listed in this issue but still giving same error.
If I do ray,get_gpus_ids() inside a remote function by specifying resources it is giving 2 gpus.

**Comment by amogkam** [comment]
I see. We are currently working on an update to Ray SGD that should fix this issue. @richardliaw do you have any other ideas for a temporary workaround?

**Comment by dcela** [comment]
This is what I have been doing on an 8-GPU machine that seems to work consistently. 
```python
    cfg.gpu_ids = sorted([int(i) for i in os.getenv('CUDA_VISIBLE_DEVICES', '').split(',')])
    os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4,5,6,7,8'
    if len(cfg.gpu_ids) > 0:
        torch.cuda.set_device(cfg.gpu_ids[0])
```
