### ISSUE TITLE
numpy datetime64 and timedelta64 not serialized correctly

### ISSUE THREAD

**Issue by salsasepp** [ray-project/ray#1041]
I suspect a bug (or missing feature) in serialization. This reproduces the issue with ray 0.2.0:
```
import ray
import numpy as np
import datetime

ray.init()

t = np.datetime64(datetime.datetime.now())
print(type(t), t)

t1 = ray.get(ray.put(t))
print(type(t1), t1)
```
which prints
```
<class 'numpy.datetime64'> 2017-09-30T14:23:58.356175
<class 'int'> 0
```
The same applies to np.timedelta64.

Side note: When serializing datetime.datetime objects, ray outputs this warning:
`WARNING: Falling back to serializing objects of type <class 'datetime.datetime'> by using pickle. This may be inefficient.`
This has prompted me to use numpy.datetime64 in the first place, which apparently does not work.

**Comment by robertnishihara** [comment]
Thanks for bringing this up! I just filed an issue with Arrow. See https://issues.apache.org/jira/browse/ARROW-1628.

**Comment by robertnishihara** [comment]
Also see https://issues.apache.org/jira/browse/ARROW-1630.

**Comment by edoakes** [comment]
Fixed now that we're using pickle.
