### ISSUE TITLE
Always getting .nan reward while training with PPO or DQN

### ISSUE THREAD

**Issue by ashutosh1906** [ray-project/ray#10416]
### Can anyone please give me hints why I am always getting the following while training with PPO or DQN?
episode_len_mean: .nan
episode_reward_max: .nan
episode_reward_mean: .nan
episode_reward_min: .nan
episodes_this_iter: 0
episodes_total: 0

Ray Version: 0.8.7
OS: macOS

**Comment by ericl** [comment]
`episodes_total: 0`. This is the reason. Until an episode has finished, we can't calculate any rewards. Does your env eventually return done=True at some point?

**Comment by ashutosh1906** [comment]
Thank you. After putting "done = True" at some points, episodes_total becomes non-zero and does not return any .nan.
