### ISSUE TITLE
MacOS Python3.7 Ray>=0.8.0 Symbol not found: _Py_GetArgc_Argv

### ISSUE THREAD

**Issue by wdahab** [ray-project/ray#10428]
Using MacOS Catalina, in Python 3.7.3 (the xcode provided one) versions of Ray from 0.8.0 won't import on either my iMac or Macbook Pro. Traceback:

Python 3.7.3 (default, Apr 24 2020, 18:51:23) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>\>\>import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wdahab/Library/Python/3.7/lib/python/site-packages/ray/__init__.py", line 50, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 21, in init ray._raylet
ImportError: dlopen(/Users/wdahab/Library/Python/3.7/lib/python/site-packages/ray/thirdparty_files/setproctitle.cpython-37m-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
  Referenced from: /Users/wdahab/Library/Python/3.7/lib/python/site-packages/ray/thirdparty_files/setproctitle.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/wdahab/Library/Python/3.7/lib/python/site-packages/ray/thirdparty_files/setproctitle.cpython-37m-darwin.so

Python 3.7 works fine with 0.7.7 and earlier (just tested to confirm). I get the same error with 0.8.0, 0.8.7, and 0.9.0dev0. Python2.7 worked fine with 0.8.7.

Sorry if this is a duplicate, couldn't find it anywhere in the issues search, but not 100% it's not somewhere there.

**Comment by richardliaw** [comment]
Hmm, looks odd. Can you try installing setproctitle via `pip install setproctitle`?

**Comment by wdahab** [comment]
Yup, so it is indeed setproctitle throwing the ImportError when I just `import setproctitle`.  I'm guessing it's a new dependency added with 0.8.0 since I can make ray==0.7.7 and import ray, but import setproctitle throws the error. Since it's a different project, I can put up the issue over there. Obviously since it's having at least some impact on ray I'm glad to bring it up on your radar and help out if there's any other questions.

**Comment by winni2k** [comment]
Could this be related to the problem with psutil reported here https://github.com/giampaolo/psutil/issues/1399 (also initially reported with ray in a now closed issue)

The fix appeared to be to remove homebrew's installation of gcc. Unfortunately, that's not an option for me...

**Comment by winni2k** [comment]
My problem compiling psutil got fixed by deleting an old version of the MacOSK sdk (see https://github.com/giampaolo/psutil/issues/1632#issuecomment-564800186)

Perhaps that might help here.

**Comment by jovany-wang** [comment]
It does work that upgrade my python version from 3.8.2 to 3.8.5.  :)
