### ISSUE TITLE
Ray on AWS EMR Cluster

### ISSUE THREAD

**Issue by ericbugin** [ray-project/ray#10427]
Hey, I do a lot of work on EMR using Pyspark/Koalas/Pandas depending on use-case. Sometimes I'll use multiprocessing for distributing my python but this does not scale the whole cluster. Would launching Ray by simply using 'ray.init()' on EMR utilize the whole cluster and does Ray have a method of verifying the resources that it is running on that can be printed out? Thanks

**Comment by IsabelLafaia** [comment]
Hello! Is there a solution to the above?
I am also trying to use ray on an existing EMR cluster but the processing remains in the master node and it is not distributed to the other nodes of the cluster. Thanks in advance for any help.

**Comment by ericbugin** [comment]
Hey,
The solution for using Ray on Spark was made by analytics-zoo. 

https://analytics-zoo.github.io/master/#ProgrammingGuide/rayonspark/

I wasn't able to get it working because I could not set dynamicAllocation to false. 

https://github.com/intel-analytics/analytics-zoo/issues/2818

**Comment by maddy2u** [comment]
Any update on this?
