### ISSUE TITLE
[tune] How to run simple SHA (1 bracket of Hyperband)

### ISSUE THREAD

**Issue by chanshing** [ray-project/ray#10439]
How can I run a simple SHA -- in other words, one bracket of Hyperband? For example, I'd like to be able to run _only_ the bracket `s=3` in your example blog https://homes.cs.washington.edu/~jamieson/hyperband.html

Is this possible?

Edit: I think ASHA pretty much does this but I'm not 100% sure I want the eager promotion for asynchronicity (I have 8 GPUs, not hundreds).

**Comment by richardliaw** [comment]
hey @chanshing sorry for the late reply.

You can try something like this - the promotion here is 'semi-eager'. You can also adjust the implementation to your liking. https://github.com/ray-project/ray/issues/4401#issuecomment-535251835

The key place to adjust promotion is in `_Bracket`. Note that we will prioritize upstreaming this in a couple weeks.

**Comment by chanshing** [comment]
Thanks for the pointers. I will have a look :)
