### ISSUE TITLE
Simplify options users need to specify when starting a Java driver and connecting to an existing Ray cluster

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#10432]
Below options are unnecessary and hard to be understood by users:

* `ray.object-store.socket-name`
* `ray.raylet.socket-name`
* `ray.raylet.node-manager-port`
* `ray.node-ip`

**Comment by kfstorm** [comment]
#7291

**Comment by chaokunyang** [comment]
Addressed in #10394
