### ISSUE TITLE
Give `ActorHandle::kill(boolean noRestart)` a default option

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#10435]
In Python, the `ray.kill(...)` API has an option named `no_restart` and the default value is `True`. But in Java, we only have one `kill(...)` method in the `ActorHandle` class and users need to provide the `noRestart` argument explicitly. We should add an overloaded version of `kill` in Java with `noRestart` set to true by default.

**Comment by kfstorm** [comment]
#7291

**Comment by chaokunyang** [comment]
Will be addressed in #10473
