### ISSUE TITLE
[Core]ray.memory_monitor.RayOutOfMemoryError:More than 95% of the memory on node xx is used

### ISSUE THREAD

**Issue by gumupaier** [ray-project/ray#10431]
error info: ray.memory_monitor.RayOutOfMemoryError:More than 95% of the memory on node xx is used
Ray version: 0.8.7
os:centos7.5

The machine is 8C and 16G and there are three machines.
The error screenshot is shown below.

![image](https://user-images.githubusercontent.com/37896380/91674097-d708e800-eb69-11ea-943b-a0dfa45c1e19.png)
![image](https://user-images.githubusercontent.com/37896380/91674105-de2ff600-eb69-11ea-8f83-ca504052fd0d.png)

The head machine is all occupied and the node machine has a lot of free memory

### Reproduction (REQUIRED)
The problem is the same as this
https://stackoverflow.com/questions/60175137/out-of-memory-with-ray-python-framework

But I made changes according to the above and it didn't work

**Comment by rkooo567** [comment]
Hi, the information written there is kind of old. We are now supporting the distributed reference counting. The reason why your node OOM is because some of objects that take up large amount of memory is likely to be referenced by your local arguments or other Ray tasks/actors.

Unfortunately, it is extremely hard for us to troubleshoot the issue with the current information. I'd suggest you to 

1. Try the memory dashboard you can find it in the Ray dashboard. It will give you which objects are currently referenced. You can properly GC your Ray objectsRef to avoid OOM.
2. If you couldn't find the problem, please post the standalone reproducible script. This will help us troubleshoot your issue.

**Comment by gumupaier** [comment]
thanks for your reply, the standalone reproducible script  is as follows

[test.py.zip](https://github.com/ray-project/ray/files/5154896/test.py.zip)

**Comment by rkooo567** [comment]
Do you mind giving me gist or script on a comment?

**Comment by gumupaier** [comment]
This script is to calculate some data from the csv file and redis respectively until all the calculations are completed. The cal function is the main processing logic. @rkooo567

**Comment by rkooo567** [comment]
Hi, @gumupaier. Sorry for the confusion. My question is if you can create a github repo or gist instead of giving me the raw zip file

**Comment by gumupaier** [comment]
hi @rkooo567 ，the gist link is as follows
[https://gist.github.com/gumupaier/b4eefd796c2da7154bdb6ceb9d3e5762](ray_test.py)

**Comment by gumupaier** [comment]
hi @rkooo567 The current phenomenon is that the memory of the head node slowly increases as the running time increases until the oom error is thrown, and the node node still has a lot of free memory. Is there something wrong with my startup method?
head node start command
`ray start --head --dashboard-host=0.0.0.0 --port=6380
`
node node start command
`ray start --address='172.253.62.206:6380' --redis-password='5241590000000000'`

The next step is to execute the code of the gist above.

**Comment by gumupaier** [comment]
Now I changed the sample code again, you can reproduce this problem directly.
The gist link is as follows
https://gist.github.com/gumupaier/9435602dd3f326419fd7ef1a5235d390


The csv sample is as follows

`8989899
121344
3123414
3123`

**Comment by PidgeyBE** [comment]
In the screenshot you post you can see there is a python process using almost 16GB of ram... What's happening in `chewing/test/call_bak.py` ? The issue does not seem to be in ray, but in the stuff you run outside of ray....

**Comment by gumupaier** [comment]
> In the screenshot you post you can see there is a python process using almost 16GB of ram... What's happening in `chewing/test/call_bak.py` ? The issue does not seem to be in ray, but in the stuff you run outside of ray....

The following gist code is very brief, but after running for a period of time there will be oom problems
[https://gist.github.com/gumupaier/9435602dd3f326419fd7ef1a5235d390](https://gist.github.com/gumupaier/9435602dd3f326419fd7ef1a5235d390)

**Comment by rkooo567** [comment]
The given script is very short-lived. Do I need to add while loop somewhere?

**Comment by rkooo567** [comment]
I don't see any symptoms that it causes OOM with this.

**Comment by gumupaier** [comment]
> The given script is very short-lived. Do I need to add while loop somewhere?

@rkooo567  The amount of data in csv is very large, about 20 million rows.

The experimental environment is three 8-core 16G machines

**Comment by gumupaier** [comment]
After the script runs, you can find that the memory will continue to increase slowly @rkooo567

**Comment by rkooo567** [comment]
Hmm this script is done within one second with the csv input you provided. Are you saying Ray's memory is increased when there's no script running?

**Comment by gumupaier** [comment]
> Hmm this script is done within one second with the csv input you provided. Are you saying Ray's memory is increased when there's no script running?

Sorry, the information I provided is not comprehensive. The gist code has been modified, you can run it directly

**Comment by gumupaier** [comment]
Under normal circumstances, these variables are recovered after the run. But the current performance is that memory usage continues to increase.

**Comment by rkooo567** [comment]
Ah, I see. I think I understood the issue. It seems like you have too many tasks running in a short time, and each put objects are referenced by pending tasks (that are queued). Note that you can only process 16 tasks at a time, but you submit much higher number of tasks.

**Comment by rkooo567** [comment]
Maybe issue will be gone if you make each of remote tasks a little bit more computationally heavier

**Comment by rkooo567** [comment]
My recommendation is instead of processing data line by line, process more bigger chunks.

**Comment by rkooo567** [comment]
(or other solution is just not put your object. You can just pass line directly to remote tasks).

**Comment by rkooo567** [comment]
Also note that if your remote task is too cheap (like your gist), it will be much slower than using a single process.

**Comment by gumupaier** [comment]
Thanks, I understand what you mean. You mean that the speed of task generation is always greater than the speed of task processing, so memory usage will continue to increase. I try to limit the number of tasks to be processed in parallel or each task to try to handle heavier work. I will give you feedback later. @rkooo567

**Comment by rkooo567** [comment]
Yeah. This is a great resource to understand how Ray's memory management works. https://docs.ray.io/en/latest/memory-management.html

More precisely, the reason why memory usage is increasing is because the object you put to shared memory using `ray.put` is used by your tasks (`cal`), but those tasks were not quickly done because there are too many of them. When the object generated by `ray.put` is not referenced by any tasks or Python variables, it is garbage collected. The issue here is that your ray objects are not garbage collected until those tasks are done (because it is referenced by them).

**Comment by gumupaier** [comment]
I tried to limit max_call, the problem seems to be solved, the oom problem does not appear again, thank you for your help. @rkooo567

**Comment by raghuvarranvh** [comment]
Hello @gumupaier  - can you please post where you changed the max_call option? I am facing the same error in a similar situation and your inputs will be helpful.

**Comment by dingkh-at-github** [comment]
@raghuvarranvh 
**max_calls** can be used with specific keyword arguments as follows:
@ray.remote(max_calls=2)
def f():
    return 1,2
****max_calls** can only be used fro tasks. for actor as follows:**
remote(num_cpus=2, resources={"CustomResource": 1})
class Foo:
    def method(self):
        return 1
Bar = Foo.options(num_cpus=1, resources=None)

**Comment by dingkh-at-github** [comment]
I solve the RayOutOfMemoryError problem by expanding the ratio of CPU to memory, such as 8-core CPU and 16g memory, or even 8-core CPU and 24g memory. Even the maximum number of workers will not fill the memory,you can test it.
