### ISSUE TITLE
[rllib] Callbacks should be able to reference specific relevant environment within a _VectorEnvToBaseEnv

### ISSUE THREAD

**Issue by andrew-rosenfeld-ts** [ray-project/ray#10469]
If you run
https://github.com/ray-project/ray/blob/master/rllib/examples/custom_metrics_and_callbacks.py

the `base_env` parameter passed to the callbacks is of type `ray.rllib.env.base_env._VectorEnvToBaseEnv`.

There should be a way to get to the specific environment that just started/stepped/ended (depending on the callback), rather than the vectorized group of environments. This would be useful for custom metrics or logging.

One can get access to all of the individual environments via `base_env.get_unwrapped()`, but there is no way to know which of these is related to the callback.

**Comment by sven1977** [comment]
Good point. The env index should probably be part of the callback's signature. It'll require sub-classing defaultdict (that generates new episodes and thereby calls the on_episode_start). ...

**Comment by sven1977** [comment]
Hey @andrew-rosenfeld-ts
Please check out https://github.com/ray-project/ray/pull/10477
and let me know, whether this is what you had in mind. The example you mention above was extended to now run with 2 (vectorized) envs per worker.
Seems to work fine on my end. Lmk.

**Comment by andrew-rosenfeld-ts** [comment]
Hi @sven1977 , looks like this would work for me, but just curious if it works well for others not using a vectorized environment - might it be confusing? I wonder if the API would be cleaner if you somehow just passed the specific individual environment in the callback, rather than a vectorized env and an index. Not sure what the performance implications of that (continually extracting the single environment on every callback) would be.

**Comment by sven1977** [comment]
The env in our sampling loop is always vectorized (if num_envs_per_worker is not set, there will only be one env in the vector (with index=0)). So this should always work. Also the callbacks API is forward compatible due to the **kwargs we put in all the callback methods, so even if someone does not expect the env_index to come in in their older version of a Callback sub-class, it should be fine and they can just ignore the env_index in the kwargs.

**Comment by sven1977** [comment]
also, performance shouldn't matter. It's one more int (whose value we always have available anyways) to pass into the calls.

**Comment by andrew-rosenfeld-ts** [comment]
Yes, I agree the performance of your proposed implementation should be fine. I just meant that if you were instead to pass the individual non-vectorized environment, perhaps indexing to retrieve that and then making it adapt to BaseEnv might have some overhead.

At any rate, I'm fine with this API, it works for me - just wanted to make sure it would work for others.
