### ISSUE TITLE
[tune] How to setup parameters for BOHB/ASHA?

### ISSUE THREAD

**Issue by nscotto** [ray-project/ray#10474]
I recently setup a BOHB experiment (neural network training), the experiment looked like:

```python
        trial = 20  # I expected this to be the number of starting configurations
        experiment_metrics = dict(metric="accuracy", mode="max")
        search = TuneBOHB(
            config_space, **experiment_metrics)
        sched = HyperBandForBOHB(
            time_attr="training_iteration",
            max_t=100,
            reduction_factor=4,
            **experiment_metrics)

        analysis = tune.run(
            MyTrainable,
            name=f'ray_tune',
            stop={"training_iteration": self._epochs},
            search_alg=search,
            scheduler=sched,
            num_samples=trial,
            resources_per_trial={'gpu': 1},  # TODO: treat various cases
            reuse_actors=True,
            verbose=False,  # TODO: make this an option
            local_dir=self._export_dir,
        )
```
A step in my trainable is the training of one epoch.
After some analysis, I found the count of trials passing an epoch were:

|count | epoch|
|---|---|
| 20| 00|
| 16| 01|
| 16| 02|
| 16| 03|
| 4 |04|
|...|...|
|4 |15|
| 1|16|
|...|...|
|1| 59|

I can't really make sense of this series given the BOHB parameters I provided, can someone help me clarify it?
Is there a way to have more control on the step of the reduction? Like waiting a bit before starting to reducing, then maybe having a constant frequency of reduction.

The questions apply first to BOHB, then to ASHA.

PS: can someone explain to me was is the `max_t` parameters in the scheduler (BOHB/ASHA) and what does it do in this context?

Thanks!

ray 0.8.7, python 3.7, ubuntu 16.04

**Comment by richardliaw** [comment]
Hi @nscotto did you end up figuring this out? sorry for the slow reply.

**Comment by nscotto** [comment]
Him

**Comment by richardliaw** [comment]
@nscotto did you see this from the original BOHB paper? I think this would explain quite a bit.

<img width="337" alt="Screen Shot 2020-09-21 at 10 02 41 AM" src="https://user-images.githubusercontent.com/4529381/93797833-98f36700-fbf1-11ea-847c-dfa4f6b70a25.png">
