### ISSUE TITLE
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.

### ISSUE THREAD

**Issue by junliangyu96** [ray-project/ray#10491]
I'm using ray to predict large number of files.

The pytorch model is trained on GPU. The machine has one GPU. If I run torch.cuda.is_available(), it returns True.

But I still go the error:
```
File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 233, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 221, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 142, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 721, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 174, in default_restore_location
    result = fn(storage, location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 150, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 134, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

How do I use the model on GPU?

**Comment by richardliaw** [comment]
Did you start your ray actor/task with `ray.remote(num_gpus=1)`?

**Comment by junliangyu96** [comment]
ray.remote(num_cpus=32, num_gpus=1)

**Comment by richardliaw** [comment]
within that task, can you return `torch.cuda.is_available()` to check that it is true?

**Comment by junliangyu96** [comment]
if I run this line in the function mentioned in the error message, it returns False. But if I run it inside functions of @ray.remote, it returns True

**Comment by junliangyu96** [comment]
Do you know how to solve this problem?

**Comment by richardliaw** [comment]
Interesting... can you also post `ray.get_gpu_ids` before `torch.cuda.is_available()`?

**Comment by richardliaw** [comment]
Also repro example would be useful here

**Comment by junliangyu96** [comment]
ray.get_gpu_ids() returns empty list.

**Comment by richardliaw** [comment]
Can you post the code where you’re running this?

**Comment by junliangyu96** [comment]
[example.zip](https://github.com/ray-project/ray/files/5165805/example.zip)

I defined remote functions inside another remote functions.
This is the function to process batch of files. For each file I process each line. So I want to make the function parallel in line level within a file, and also file level. I don't know if this is allowed

**Comment by richardliaw** [comment]
Hey @junliangyu96, your code has `ray.init(num_cpus=32, num_gpus=1)`, which is not `ray.remote(num_gpus)`.

`ray.init` is a global value. `ray.remote` is per task. 

Everywhere you want to use a GPU, every function, you need to do the following:

```python
@ray.remote(num_gpus=1) # or 0.1
def func(...)
```

**Comment by junliangyu96** [comment]
[add_gpu.zip](https://github.com/ray-project/ray/files/5168881/add_gpu.zip)

I added num_gpus=1 in function

@ray.remote(num_gpus=1)
def contains_keywords(line, tagger):

the error msg is:

RayTaskError(RuntimeError)                Traceback (most recent call last)
<ipython-input-22-4cf4c0863050> in <module>
    151 ray.init(num_cpus=32, num_gpus=1)
    152 
--> 153 unlabeled_file_to_sentences, unlabeled_extract_from = file_preprocessing(tagger, lines)

<ipython-input-22-4cf4c0863050> in file_preprocessing(tagger, file_content, line_labels)
    106     file_content = ray.get(file_content)
    107     extracted_lines, extracted_labels, extract_from = \
--> 108         extract_entities(tagger, file_content, line_labels)
    109 
    110     file_to_sentences = [to_sentence.remote(file) for file in extracted_lines]

<ipython-input-22-4cf4c0863050> in extract_entities(tagger, files, labels, keep)
     87         print(torch.cuda.is_available())
     88         extracted_lines_single, extracted_labels_single, extract_from_single = \
---> 89             extract_from_file(tagger, files, labels, file_id, keep)
     90         extracted_lines_all.extend(extracted_lines_single)
     91         if labels:

<ipython-input-22-4cf4c0863050> in extract_from_file(tagger, files, labels, file_id, keep)
     51 
     52     found_list = [contains_keywords.remote(line, tagger) for line in lines]
---> 53     found_list = ray.get(found_list)
     54     while i < len(lines):
     55         print(i)

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_ids, timeout)
   1472                     worker.core_worker.dump_object_store_memory_usage()
   1473                 if isinstance(value, RayTaskError):
-> 1474                     raise value.as_instanceof_cause()
   1475                 else:
   1476                     raise value

RayTaskError(RuntimeError): ray::__main__.contains_keywords() (pid=97069, ip=192.168.0.15)
  File "python/ray/_raylet.pyx", line 410, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 427, in ray._raylet.execute_task
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 312, in deserialize_objects
    self._deserialize_object(data, metadata, object_id))
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 252, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 233, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 221, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 142, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 721, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 174, in default_restore_location
    result = fn(storage, location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 150, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/yujl/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 134, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

not working

**Comment by richardliaw** [comment]
@junliangyu96 can you please post your code on a Gist or in plain text? It seems very unsafe to be downloading your zip file.

**Comment by junliangyu96** [comment]
sure
[example.txt](https://github.com/ray-project/ray/files/5170713/example.txt)

**Comment by junliangyu96** [comment]
sure
https://github.com/junliangyu96/demo

**Comment by junliangyu96** [comment]
Hi

The problem is still not solved yet

if I run this
@ray.remote(num_gpus=0.1)
def use_gpu():
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
    print(torch.cuda.is_available())

the output would be
(pid=244822) ray.get_gpu_ids(): [0]
(pid=244822) CUDA_VISIBLE_DEVICES: 0
(pid=244822) False

the result of torch.cuda.is_available() is False

**Comment by richardliaw** [comment]
Sorry about that. Can you try `ray.init()` instead of `ray.init(num_cpus=32, num_gpus=1)`? 

`num_gpus` and `num_cpus` are generally used for override purposes.

**Comment by richardliaw** [comment]
The main script to run is:

```
import ray
import torch

ray.init()
print(torch.cuda.is_available())
print(ray.cluster_resources()

@ray.remote(num_gpus=0.1)
def use_gpu():
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
    print(torch.cuda.is_available())
```

**Comment by junliangyu96** [comment]
thanks I think It can run now.

but 
RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 10.76 GiB total capacity; 962.18 MiB already allocated; 175.69 MiB free; 1012.00 MiB reserved in total by PyTorch)

If I don't use ray I will not get this message

**Comment by richardliaw** [comment]
@junliangyu96 what was the fix?

Also cc @mfitton re: cuda out of memory

**Comment by junliangyu96** [comment]
I used ray.init(). Now the error becomes cuda out of memory

now I try to pass my model into the function

@ray.remote(num_gpus=1)
def use_gpu1(tagger):
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
    print(torch.cuda.is_available())

Then I got this error message with no output of printing.

I also tried 

tagger_ob = ray.put(tagger)
del tagger
torch.cuda.empty_cache()

and pass tagger_ob. doen't work.

checking gpu:
t = torch.cuda.get_device_properties(0).total_memory
c = torch.cuda.memory_cached(0)
a = torch.cuda.memory_allocated(0)
print(t,c,a)

get
11553341440 935329792 849871872

**Comment by junliangyu96** [comment]
And if I put the model on cpu, It is easy to use up all memory. Is it because the model is copied to every worker?

But if I put it to shared memory, then they original function doesn't work.

---> 59     tagger.eval()
     60 
     61 

AttributeError: 'ray._raylet.ObjectID' object has no attribute 'eval'

**Comment by GoingMyWay** [comment]
Same issue for Ray 1.12.1

**Comment by NorwegianGoat** [comment]
Hi, I encountered the exact same issue reported by @junliangyu96, and solved in a similar way as suggested by @richardliaw . In the following lines you can find a minimal code snippet.
```
class TextEncoder():    
    def __init__(self):
        self.model = SentenceTransformer("all-MiniLM-L6-v2")
    
    def __call__(self, text:Dict[str, str], colname:str) -> Dict:
        text[f"embeddings_{colname}"] = self.model.encode(text[colname], convert_to_numpy=True)
        return text

df = data.from_pandas(documents, override_num_blocks=50)

# This is not working
embeddings_df = df.map(TextEncoder, fn_args=["text"], concurrency=(1,ray_max_workers))  \
        .map(TextEncoder, fn_args=["titles"], concurrency=(1,ray_max_workers)) \
        .map(TextEncoder, fn_args=["category"], concurrency=(1,ray_max_workers))\
        .to_pandas()

# This works
num_cpus = num_gpus = 0 if not ray.cluster_resources()["GPU"] else ray.cluster_resources()["GPU"]/ray_max_workers
embeddings_df = df.map(TextEncoder, fn_args=["text"], concurrency=(1,ray_max_workers), num_cpus=num_cpus)  \
        .map(TextEncoder, fn_args=["titles"], concurrency=(1,ray_max_workers), num_cpus=num_cpus) \
        .map(TextEncoder, fn_args=["category"], concurrency=(1,ray_max_workers), num_cpus=num_cpus)\
        .to_pandas()
```
I wanted to ask if anyone knows what causes this strange behavior. The "standard" way of working of the `SentenceTransformers` library is to load the model on CPU if no GPUs are available, and to load the model on GPU if GPUs are detected.
So,  I would have expected the model to be loaded on GPU automatically.

I also made a minimal test by running the following lines:

```
import torch

print(torch.cuda.is_available()) # Prints True

@ray.remote
def ray_cuda():
        import torch
        return torch.cuda.is_available()

print(ray.get(ray.cuda.remote())) # Prints False

@ray.remote(num_gpus=0.1)
def ray_cuda():
        import torch
        return torch.cuda.is_available()

print(ray.get(ray.cuda.remote())) # Prints True
```

The cluster is formed by a single node with 4 GPUs (A100 64GB), so it is not a case of an "heterogeneous" cluster in which my function was scheduled to run on a CPU only node. Is ray interfering in some way with torch signaling that no GPU is available? I'm pretty confused at this point.

Thank you in advance.

**Comment by DongShangqun** [comment]
I also encountered this issue after modifying my code, so after recalling the modifications, I realized the problem I encountered here. I hope it can be helpful to everyone
The reason for my error is that the function decorated with `@ ray. remote()`  directly called external parameters inside, for example
```
#External parameter b
@ray.remote()
def parallel_test(a)
return a+b
```
Need to be modified to
```
#External parameter b
@ray.remote()
def parallel_test(a, c=b)
return a+c
```
