### ISSUE TITLE
Ray uses spdlog instead of glog

### ISSUE THREAD

**Issue by ashione** [ray-project/ray#10493]
I have talked with @rkooo567 in slack link https://ray-distributed.slack.com/archives/C016MPZE1L1/p1598937145003600.
Reasons:

- glog lacks features such as log rotation or custom formatting. Log rotation is critical function of long running job becase the disk will become full due to a large number of log files being written without daily or custom rotation configuration.

- glog only supports writing files to different sinks for different severity.

Solution:
Replace glog with spdlog. This is homepage in github https://github.com/gabime/spdlog
Its simple description:
```
Very fast (see benchmarks below).
Headers only or compiled
Feature rich formatting, using the excellent fmt library.
Asynchronous mode (optional)
Custom formatting.
Multi/Single threaded loggers.
Various log targets:
Rotating log files.
Daily log files.
Console logging (colors supported).
syslog.
Windows debugger (OutputDebugString(..))
Easily extendable with custom log targets (just implement a single function in the sink interface).
Log filtering - log levels can be modified in runtime as well as in compile time.
Support for loading log levels from argv or from environment var.
Backtrace support - store debug messages in a ring buffer and display later on demand.
```

Spdlog repo and deps will be introduced in @Basasuya PR  https://github.com/ray-project/ray/pull/10419

**Comment by rkooo567** [comment]
We'll try using it for event framework. We must need more discussion if we want to replace glog.

**Comment by ashione** [comment]
@rkooo567 I'll create a PR for making log tool configurable firstly and use glog by default. How about that?

**Comment by rkooo567** [comment]
How complicated is the PR? If it is simple enough, I think there's nothing to lose. Thought? @ericl

**Comment by ashione** [comment]
> How complicated is the PR? If it is simple enough, I think there's nothing to lose. Thought? @ericl

Spdlog compatible skeleton will be polished in this PR https://github.com/ray-project/ray/pull/10967

**Comment by rkooo567** [comment]
This is not done yet because spdlog is not the default logger yet.

**Comment by ashione** [comment]
> This is not done yet because spdlog is not the default logger yet.

It should be closed.

**Comment by rkooo567** [comment]
@ashione You mean that PR turns it on by default?

**Comment by ashione** [comment]
> @ashione You mean that PR turns it on by default?

I turn it on in https://github.com/ray-project/ray/pull/10967.

**Comment by kfstorm** [comment]
@rkooo567 Should we turn it off by default or close this issue?

**Comment by rkooo567** [comment]
No. Since it is not included in the next release, I think it’d be okay to turn it on by default.
