### ISSUE TITLE
[tune] Node scheduling before Trial scheduling

### ISSUE THREAD

**Issue by ozen** [ray-project/ray#10495]
Hi.

I'm new to Ray Tune and trying to understand how it can fit to different use cases.

If I understand correctly, the scheduler/runner/executor (I'm not sure about the terminology here) sees the cluster as a unified resource pool and can send the Trial to any node satisfying the resource requirements.

I would like to know if it's possible to first schedule an Experiment to a Node in the Cluster, then schedule Trials of the Experiment within the Node. 

For example, there are many nodes in the cluster with different number of GPUs. I create an Experiment that requires 4 GPUs. I first want to find a Node with at least 4 GPUs available; then run all Trials of the Experiment in that node.

Is this possible with the current implementation of Ray and Tune, with or without some custom coding? For example, by using Ray Core to schedule Nodes, than using Tune within the node.

If not, is there any other tool you know that can be combined with Ray Tune to achieve this scenario?

Finally, will placement groups help with this kind of scenarios?

Thank you.

**Comment by richardliaw** [comment]
Hey @ozen thanks for opening this issue - interesting use case! Could you tell me a bit more about why you need this? i.e., why can't you use all/any available nodes on the cluster?

**Comment by ozen** [comment]
It's mainly for job scheduling. If I run multiple experiments (i.e. call tune.run multiple times), their trials will run concurrently since they are scheduled individually. If I can schedule and allocate a node for Experiment A, trials of Experiment B won't cut in. That may be desirable if I want one experiment to finish as soon as possible while queuing other experiments.

I have just seen [Deploying on Slurm](https://docs.ray.io/en/latest/cluster/slurm.html) page, maybe that's the solution.

**Comment by richardliaw** [comment]
ok great! let me know if that works for you. Feel free to reopen if not.

**Comment by richardliaw** [comment]
Hypothetically you can provide a custom resource to Tune via `resources_per_trial={"custom_resource": {"node:<ip_address>":...}}`, but I think that might have some odd behavior right now. I can look into it if preferable.
