### ISSUE TITLE
[Placement Group] Support RayPlacementGroupError

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10508]
### Describe your feature request
When tasks are failed due to placement group removal, we should raise `RayPlacementGroupError` instead of worker dead error or actor dead error.

**Comment by chandramoulirajagopalan** [comment]
Can I work on this issue ?

**Comment by rkooo567** [comment]
@chandramoulirajagopalan Contribution is always welcomed :). But please describe your high-level implementation plan beforehand!

**Comment by chandramoulirajagopalan** [comment]
My plan of action would be 
1.) Reproduce the error.
2.) Find the source code where the Worker dead error or actor dead error has been raised rather than RayPlacementGroupError.
3.) Fix the source code and then commit.

**Comment by chandramoulirajagopalan** [comment]
Do we have any code to reproduce this error?

**Comment by rkooo567** [comment]
Duplicate https://github.com/ray-project/ray/issues/10232
