### ISSUE TITLE
[Placement Group] ray.wait([pg.ready()]) shouldn't warn.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10506]
### Describe your feature request
Currently, if you run 

`ray.wait([pg.ready()])`, it prints the warning message that the ready task is infeasible. This is an expected behavior, so we should not print warning messages. 

Impl Idea
- Have a magic number for pg.ready resources (for example, it always request 0.0231 requests) and don't warn if this value of resources are requested.

**Comment by ericl** [comment]
Hmm yeah, a magic number sounds good lol. I guess you still want the warning for normal placement group tasks, just not the ready task.
