### ISSUE TITLE
[ray] ray.get() UnpicklingError

### ISSUE THREAD

**Issue by HanbumKo** [ray-project/ray#10526]
### What is your question?

Hi I've made manual cluster with two nodes, and run code. But got an UnpicklingError when I do ray.get(), and I have no idea what it means. All things are totally fine without other nodes, but only that happens when I use manual cluster. Is there anything I miss?

<img width="1440" alt="Screen Shot 2020-09-03 at 4 09 29 PM" src="https://user-images.githubusercontent.com/37624747/92083962-b65abf80-ee01-11ea-8695-7a87e6bd1e22.png">
<img width="952" alt="Screen Shot 2020-09-03 at 4 09 53 PM" src="https://user-images.githubusercontent.com/37624747/92083989-bb1f7380-ee01-11ea-9ae5-8b7d6e2de520.png">
<img width="899" alt="Screen Shot 2020-09-03 at 4 10 04 PM" src="https://user-images.githubusercontent.com/37624747/92083997-bce93700-ee01-11ea-8d16-4ccd6b2dc498.png">

**Comment by rkooo567** [comment]
This is really weird. What version of Ray are you using? Also, what OS are you using?
