### ISSUE TITLE
Additional API changes for 1.0

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#10546]
Let me know if this is being tracked somewhere else. Also, if some of the items in this list are wrong, I'll update them.

**Python API**
- [ ] Improve wording for ray API documentation. **EDIT:** Can happen after code freeze
- [x] Should `enable_object_reconstruction` in `ray.init()` be moved to an unstable option? Wouldn't we want to always have this enabled in the future?
- [x] Undocument `ray.get_resource_ids`
- [x] Undocument `ray.get_dashboard_url`
- [x] Undocument `ray.experimental.set_resource`. **EDIT:** Won't do. It is already clear that it is experimental.

**CLI**
- [ ] Remove old `ray start` arguments (things referring to Redis, things that use the word webui, huge-pages, etc)
- [x] Remove --log-new-style and --log-old-style (#10255)

**Comment by edoakes** [comment]
@robertnishihara you wouldn't want object reconstruction if your tasks have side effects

**Comment by ericl** [comment]
Hmm @stephanie-wang should there a difference between max retries and object reconstruction?

**Comment by ericl** [comment]
Also, why remove dashboard url? The URL isn't stable so there needs to be a way to retrieve it programmatically.

**Comment by ericl** [comment]
Hmm in this case maybe we should make it private for now. It seems like we don't have an ideal picture of how to configure this yet, and in any case there doesn't seem to be any users of the setting: https://github.com/search?q=enable_object_reconstruction&type=Code

**Comment by stephanie-wang** [comment]
Ah I see, I thought it was already private since it's marked as such on the audit spreadsheet: https://docs.google.com/spreadsheets/d/1F6VZ1R_fgDzpRZjXI5_6gaUwW2CQKi431dCDTR-Vm8s/edit#gid=0

Yeah, I think that makes sense.

**Comment by ericl** [comment]
Made a PR... I opted to keep "ray.experimental.set_resource" documented. Actually, was considering moving that to stable, but we just don't have time to QA it at the moment I think.

Didn't touch ray start stuff yet.

**Comment by rkooo567** [comment]
@ericl Can I close it?

**Comment by ericl** [comment]
Yeah I think the main ones are in.

**Comment by robertnishihara** [comment]
@rkooo567 I *think* there is some ongoing work in https://github.com/ray-project/ray/pull/10659.

**Comment by wuisawesome** [comment]
yep, but it's being tracked so it's fine that this is closed. we just need to remember to look over the documentation later
