### ISSUE TITLE
Can't clean up named actor (non-detached)

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#10545]
### What is the problem?

Non-detached actor names don't seem to be reclaimed when the actor exits.

Discovered while refactoring Serve to support clusters scoped to the driver program.

### Reproduction (REQUIRED)

```
import time
import ray

ray.init()

@ray.remote
class A:
    pass

a = A.options(name="hello").remote()
ray.kill(a, no_restart=True)
del a

# This loop never exits.
while True:
    try:
        ray.get_actor("hello")
        print("Actor still alive")
    except:
        print("Actor was deleted")
        break
    time.sleep(1)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
@ericl Making this P0 because it is a pretty fundamental issue for the named actor API and it's a blocker for the serve change we want to get in for 1.0. LMK if you disagree.

**Comment by rkooo567** [comment]
Note that A.options(name="hello") is not detached anymore.

**Comment by rkooo567** [comment]
Why don't we make actors detached if name is provided but lifetime is not? It will secretly breaks lots of people's codebase otherwise.

**Comment by ericl** [comment]
Why is this a problem? You can simply name it if you want to manage its lifetime afterwards. Also, ant's "ray.cleanup_job()" proposal would let you clean up these actors.

I'm strongly opposed to this, since it would effectively disallow valid use cases in an attempt to prevent user error.

**Comment by ericl** [comment]
Ok I see, it's just an issue with removing the name label, only read the last comment.

**Comment by edoakes** [comment]
This seems like it's probably the culprit:
https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/gcs_actor_manager.h#L95
