### ISSUE TITLE
[Metrics] Custom metrics are not serializable.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10564]
### What is the problem?

Custom metrics cannot be passed to different tasks or actors because its tags are not pickleable. 

We should support passing metrics to tasks or other actors. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
Why do they need to be serializable? They belong to different core worker right?

**Comment by rkooo567** [comment]
Yeah. But it can be cumbersome when you are using tasks with actors because you should re-define them every time.

**Comment by rkooo567** [comment]
My idea is to reinitialize it when it is deserialize by setting __reduce__ (and I think it should work).

**Comment by rkooo567** [comment]
@architkulkarni I will assign this to you.
