### ISSUE TITLE
[Ray] Manual Cluster Setup (not bringing CPUs into available resources).

### ISSUE THREAD

**Issue by raoul-khour-ts** [ray-project/ray#10574]
[RAY CORE]
When following https://docs.ray.io/en/latest/cluster/index.html#manual-ray-cluster-setup 
on 0.8.7 Once I have connected the remote worker nodes I see the number of available CPUs go up. However on the current 0.9.0.dev CPUs stay at 0

*Ray version and other system information (Python version, TensorFlow version, OS):*
0.9.0.dev seems to currently prevent manual clusters

### Reproduction (REQUIRED)

install 0.9.0.dev latest
on main machine run: `ray start --head --num-cpus=0`
on worker machine run: `ray start --address=xxx --redis-password=xxx --num-cpus=24`
back on main machine run: 'python3 -c "import ray; ray.init(address='auto');print(ray.available_resources())"
see no cpus in available resources

in 0.8.7 and 0.8.6
after following above I see 24cpus

**Comment by wuisawesome** [comment]
I will investigate and mark as P0 once I can reproduce it

**Comment by wuisawesome** [comment]
Was unable to reproduce this. What I tried: 

1. In EC2 spin up 2 nodes and ensure they're in the same VPC, subnet, security group, etc. 

2. Installed the latest nightly wheel on each machine.

3. Ran 
```
ubuntu@ip~$ /home/ubuntu/.local/bin/ray start --head --num-cpus=0
Local node IP: 172.31.37.161
Available RAM
  Workers: 18.26 GiB
  Objects: 9.15 GiB
  
  To adjust these values, use
    ray.init(memory=<bytes>, object_store_memory=<bytes>)
Dashboard URL: http://localhost:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='xxx.xxx.xxx.xxx:6379' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', redis_password='5241590000000000')
  
  If connection fails, check your firewall settings other network configuration.
  
  To terminate the Ray runtime, run
    ray stop
```

4. On the other node:
```
ubuntu@ip:~$ .local/bin/ray start --address='xxx.xxx.xxx.xxx:6379' --redis-password='5241590000000000'Local node IP: 172.31.42.67
Available RAM
  Workers: 21.34 GiB
  Objects: 9.15 GiB
  
  To adjust these values, use
    ray.init(memory=<bytes>, object_store_memory=<bytes>)

--------------------
Ray runtime started.
--------------------

To terminate the Ray runtime, run
  ray stop
```

5. Check the resources from the head node:
```
ubuntu@ip:~$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init(address="auto")
2020-09-05 05:25:03,902	INFO worker.py:633 -- Connecting to existing Ray cluster at address: xxx.xxx.xxx.xxx:6379
{'node_ip_address': 'xxx.xxx.xxx.xxx', 'raylet_ip_address': 'xxx.xxx.xxx.xxx', 'redis_address': 'xxx.xxx.xxx.xxx:6379', 'object_store_address': '/tmp/ray/session_2020-09-05_05-24-24_528207_10923/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2020-09-05_05-24-24_528207_10923/sockets/raylet', 'webui_url': 'localhost:8265', 'session_dir': '/tmp/ray/session_2020-09-05_05-24-24_528207_10923', 'metrics_export_port': 62757}
>>> ray.available_resources()
{'memory': 811.0, 'node:xxx.xxx.xxx.xxx': 1.0, 'object_store_memory': 258.0, 'node:xxx.xxx.xxx.xxx': 1.0, 'CPU': 8.0}
>>> ray.cluster_resources()
{'CPU': 8.0, 'node:xxx.xxx.xxx.xxx': 1.0, 'memory': 811.0, 'object_store_memory': 258.0, 'node:xxx.xxx.xxx.xxx': 1.0} 
```

**Comment by robertnishihara** [comment]
> back on main machine run: 'python3 -c "import ray; print(ray.available_resources())"
@raoul-khour-ts Is that actually enough to reproduce the issue? Don't you need to call `ray.init(address=...)`? Note that if you call `ray.init()` then it won't attach to the cluster, so you'll just see one machine's resources.

**Comment by raoul-khour-ts** [comment]
Note that once I do call ray.init(address="auto") I keep getting this in my logs:
(pid=raylet, ip=xx) F0907 01:02:55.541476 3002484 3002484 service_based_gcs_client.cc:207] Couldn't reconnect to GCS server. The last attempted GCS server address was 127.0.0.1:46515
(pid=raylet, ip=xx) *** Check failure stack trace: ***
(pid=raylet, ip=xx)     @     0x55b39f7c395d  google::LogMessage::Fail()
(pid=raylet, ip=xx)     @     0x55b39f7c4abc  google::LogMessage::SendToLog()
(pid=raylet, ip=xx)     @     0x55b39f7c3639  google::LogMessage::Flush()
(pid=raylet, ip=xx)     @     0x55b39f7c3851  google::LogMessage::~LogMessage()
(pid=raylet, ip=xx)     @     0x55b39f77bf59  ray::RayLog::~RayLog()
(pid=raylet, ip=xx)     @     0x55b39f53041a  ray::gcs::ServiceBasedGcsClient::ReconnectGcsServer()
(pid=raylet, ip=xx)     @     0x55b39f53051f  ray::gcs::ServiceBasedGcsClient::GcsServiceFailureDetected()
(pid=raylet, ip=xx)     @     0x55b39f5306c1  ray::gcs::ServiceBasedGcsClient::PeriodicallyCheckGcsServerAddress()
(pid=raylet, ip=xx)     @     0x55b39f532a31  ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=xx)     @     0x55b39f3e87a3  main
(pid=raylet, ip=xx)     @     0x7f2f7ead52e1  __libc_start_main
(pid=raylet, ip=xx)     @     0x55b39f3ffa71  (unknown)

**Comment by wuisawesome** [comment]
@raoul-khour-ts can you try the steps I used and verify that works?

**Comment by raoul-khour-ts** [comment]
I did exactly that but in our environment (not EC2 but a local farm of machines) 

on 0.8.7 I can recreate your steps all fine and no logs.

on 0.9.0.dev no cpu's show up in the cluster and the above error message keeps getting logged.

**Comment by raoul-khour-ts** [comment]
The machine shows up on my ray dashboard... I just for some reason don't have access to its cpus...

**Comment by wuisawesome** [comment]
Could you do a fresh run of this, then share `/tmp/ray/session_latest/logs`? Also what's your OS, and python version?

**Comment by raoul-khour-ts** [comment]
Unfortunately I can not share all my logs. Is there a particular one of the files you are interested in?

**Comment by raoul-khour-ts** [comment]
One notable one is the gcs_server.err and out giving these lines:
 network_util.cc:62] Failed to find other valid local IP. Using 127.0.0.1, not possible to go distributed!

**Comment by raoul-khour-ts** [comment]
Is there a change between how this occurs between 0.8.7 and 9.0.0.dev?

**Comment by raoul-khour-ts** [comment]
I am running python 3.6.10 on a linux machine.

**Comment by raoul-khour-ts** [comment]
Just checked that downgrading to 0.8.7 again does not show that gcs_server.err. 

Interestingly I did notice that when I start python and run ray.init(address='auto') on 0.8.7 I get:
>>> import ray
>>> ray.init(address='auto')
WARNING: Logging before InitGoogleLogging() is written to STDERR
global_state_accessor.cc:25] Redis server address = xx:6379, is test flag = 0
redis_client.cc:146] RedisClient connected.
redis_gcs_client.cc:89] RedisGcsClient Connected.
service_based_gcs_client.cc:193] Reconnected to GCS server: xx:43483
service_based_accessor.cc:92] Reestablishing subscription for job info.
...
Reestablishing subscription for worker failures.
ServiceBasedGcsClient Connected.
>>> ray.cluster_resources()
{'object_store_memory': 1786.0, 'memory': 5849.0, 'node:172.23.170.106': 1.0, 'node:xx': 1.0, 'CPU': 24.0}

I dont seem to have that in 0.9.0.dev

**Comment by raoul-khour-ts** [comment]
> > back on main machine run: 'python3 -c "import ray; print(ray.available_resources())"
> 
> @raoul-khour-ts Is that actually enough to reproduce the issue? Don't you need to call `ray.init(address=...)`? Note that if you call `ray.init()` then it won't attach to the cluster, so you'll just see one machine's resources.

Hey yeah sorry I forgot to add that to my reproduce guide (but yes I did call ray.init(address='auto'). Updated it now.

**Comment by raoul-khour-ts** [comment]
another observance:
if I run the `ray start --address='xxx.xxx.xxx.xxx:6379' --redis-password='5241590000000000' --num-cpus=20` on the head then I see 20 cpus in the cluster...

**Comment by wuisawesome** [comment]
Are there any errors/stack traces in `raylet.err` or and of the worker logs?

**Comment by raoul-khour-ts** [comment]
raylet.err is empty
raylet.out looks normal

Not sure where the worker logs are. are those the python-core-driver-xxx.log?
if so then nothing different from the 0.8.7 runs.

**Comment by rkooo567** [comment]
Ah, I think you have an issue to connect to GCS from worker nodes, and that might be why your worker nodes cpus are not reported to Ray.

**Comment by rkooo567** [comment]
There were some changes in network translation from 0.8.7 => 0.9.0.dev0 

`network_util.cc:62] Failed to find other valid local IP. Using 127.0.0.1, not possible to go distributed!`

I believe this log is something we added lately. What OS are you currently using?

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/10004

One of possibilities is that your machines are not using any of network interface listed in the PR description. Can you elaborate more about your cluster environment?

**Comment by rkooo567** [comment]
The workaround is to manually set the Redis key so that raylets can find the IP address of GCS. look at this link https://github.com/ray-project/ray/issues/8648#issuecomment-664233815

**Comment by raoul-khour-ts** [comment]
I'm using Debian 9



> The workaround is to manually set the Redis key so that raylets can find the IP address of GCS. look at this link [#8648 (comment)](https://github.com/ray-project/ray/issues/8648#issuecomment-664233815)

I would be happy to test if this would fix my issue but. I actually have no idea how to set the GcsServerAddress to 10.251.231.121:40531 in redis manually,

**Comment by rkooo567** [comment]
In this case the gcs server address will be  [your head node private ip address]:[gcs_server port], and you can set this by connecting to the Redis in a head node.

**Comment by raoul-khour-ts** [comment]
so running "python3 -c "import redis; r = redis.Redis(host=xxx, port=yyy, db=0); r.set('GcsServerAddress', 'xxx:zzz')"

Ill try this tomorrow. Thank you @rkooo567 Ill let you know how that goes.

**Comment by rkooo567** [comment]
Yeah I think that should work. Don’t forget to specify gcs-server port with “ray start —head —gcs-port=“ so that you don’t need to worry about finding where gcs server has been bound to.

**Comment by rkooo567** [comment]
Btw, it is interesting the new version has some addresses it resolve while 0.8.7 could. We should probably find a solution for this.

**Comment by raoul-khour-ts** [comment]
@rkooo567
Sorry about the delay here but it worked!!!:

ray start --head --gcs-server-port=ddd --cpus=0
```python
import redis
r = redis.Redis(host=xxx, port=yyy, password=zzz, db=0)
r.get('GcsServerAddress')
>>> 127.0.0.1:ddd
r.set('GcsServerAddress', xxx:ddd)
```
ssh to other_machine
ray start --address=xxx --redis-password=zzz --num-cpus=24

back on main machine:
 'python3 -c "import ray; ray.init(address='auto');print(ray.available_resources())"
>>> {..., cpus:24}


Now the question is how do we make this work without having to do all this...

**Comment by rkooo567** [comment]
The issue here is your manual cluster’s network interface is probably not typical, and we have trouble resolving addresses. I think I can create a patch that allows you to specify GCS address. What do you think about this solution?

**Comment by raoul-khour-ts** [comment]
@rkooo567 honestly the gcs address is always going to be the --head ip_address for me at least. Shouldn't that be easy to resolve?

**Comment by rkooo567** [comment]
Ah, I see. So, the issue is gcs server address is not matching head ip address you specified right?

**Comment by raoul-khour-ts** [comment]
Well the gcs server address seems to for some reason fail to connect to head_ip_address then fall back to localhost. However that prevents remote machines from connecting.

**Comment by raoul-khour-ts** [comment]
but If i go back into redis and manually set it to head_ip_address everything is fine...

**Comment by raoul-khour-ts** [comment]
@rkooo567 and I have isolated the issue to being an issue with private networks. My machine can not ping out to 8.8.8.8 which makes the GCS configuration fail.

**Comment by rkooo567** [comment]
Note: I will make a PR to use Python code to resolve addresses of GCS servers

**Comment by raoul-khour-ts** [comment]
Was able to confirm that https://github.com/ray-project/ray/pull/10946 fixed the issue.

Thank you @rkooo567. This should make it out to the 1.1.0 release hopefully sometime in November?

**Comment by rkooo567** [comment]
@raoul-khour-ts Yes! We have a monthly release cycle, and the 1.0 target date is the end of September.

**Comment by raoul-khour-ts** [comment]
@rkooo567 I am starting to see issues like this again on 1.1.0.dev. Its a little stranger though that it seems like things end up dieing but with similar errors.

Have y'all moved 1.1.0.dev to distributed or spawning gcs or something? (could be a separate issue)

**Comment by raoul-khour-ts** [comment]
either way it seems like the gcs location is being lost...

**Comment by rkooo567** [comment]
Are there logs in gcs_server.err?
