### ISSUE TITLE
[tune] sample int from exponential function

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10571]
### Describe your feature request
currently, the [FAQ](https://docs.ray.io/en/master/tune/tutorials/overview.html) [says](https://docs.ray.io/en/master/tune/tutorials/overview.html#how-do-i-choose-hyperparameter-ranges):
> For **batch sizes**, we suggest trying **powers of 2**, for instance, 2, 4, 8, 16, 32, 64, 128, 256, etc. The magnitude depends on your problem. For easy problems with lots of data, use higher batch sizes, for harder problems with not so much data, use lower batch sizes.

since this is suggested in the FAQ, I think there should be a way to define such a sampling. 

something like this might have worked for the 0.8.7 API; will need to revisit the refactor to see how we should implement now

```python
def expuniformint(min_bound, max_bound, a=1, b=10):
    """Sugar for sampling an int from an exponential distribution.

    Useful for batch size, for example.

    Args:
        min_bound (float): Lower boundary of the output interval
        max_bound (float): Upper boundary of the output interval
        a (float): coefficient of the exp function. Defaults to 1.
        b (float): Exponent/power of the input variable. Defaults to 10.

    Example:
        >>> tune.expuniformint(2, 32, b=2)  # batch_size
    """
    # edit: loguniformint might be better than expuniformint
    # TODO: the args section of the docstring is bad
    logmin = np.log(min_bound) / np.log(base)
    logmax = np.log(max_bound) / np.log(base)

    def apply_log(_):
        return base**(np.random.randint(logmin, high=logmax))

    return sample_from(apply_log)
```

there are plenty of ways to do this without a built-in tune function (e.g., `2**tune.randint(1, 5).func(_)`, `tune.choice(*[2**i for i in range(1, 5)])`), so this issue can be safely closed. this is just a convenience benefit since I imagine lots of tune users will be tuning the batch size

**Comment by richardliaw** [comment]
Hmm, yeah - doesn't this work with `tune.loguniform`?

**Comment by sumanthratna** [comment]
doesn't `tune.loguniform` return floats? or at least that's what I understand from the source + numpy's docs, as I think `np.random.uniform` returns floats, not ints (and so `(base: int)**(exp: float)` would be a float)

`int(tune.loguniform(4, 32, base=2))` might work but that falls into the category of workarounds IMO

**Comment by richardliaw** [comment]
how about tune.qloguniform?

**Comment by sumanthratna** [comment]
oh right, that should work. 

closing as this was resolved in the search space refactor (#10444). I'll try to test it out eventually and let you know if it works (and I'll push a PR to add it to the docs)

**Comment by jonas27** [comment]
@sumanthratna did you figure it out eventually?
I am trying with the below code but it doesn't work. @richardliaw  do you have any suggestions?
```python
>>> a = tune.qloguniform(2,32,1, base=2)
>>> a.sample()
18.0
```

**Comment by sumanthratna** [comment]
> @sumanthratna did you figure it out eventually?
> I am trying with the below code but it doesn't work. @richardliaw do you have any suggestions?
> 
> ```python
> >>> a = tune.qloguniform(2,32,1, base=2)
> >>> a.sample()
> 18.0
> ```

Hi @jonas27, what's not working? I think it works as expected on my machine: 
```python
from ray import tune
data = {num: 0 for num in range(2, 32+1)}
for _ in range(202200):
    data[int(tune.qloguniform(2,32,1, base=2).sample())] += 1

import matplotlib.pyplot as plt
plt.bar(data.keys(), data.values())
plt.show()
```

![matplotlib output](https://python3-5-code.trinket.io/python3-generated/cy3tbj4i/trinket_plot.png)


From a glance, the bar graph looks reasonable but if you want to be sure, you can change the x-axis to be `lg(x)` and you should see a uniform distribution

P.S. you might want to post on the Ray forum: https://discuss.ray.io/

**Comment by jonas27** [comment]
@sumanthratna and I thought you wanted to sample on log_2 scale, so 2, 4, 8... Until 32.
Maybe I understood the feature request wrong. (But if you know how to do it, I would be grateful). 
Atm I sample from ranint and then take that 2^x, but as you said it would be nicer to sample from the exp function directly.

**Comment by sumanthratna** [comment]
> @sumanthratna and I thought you wanted to sample on log_2 scale, so 2, 4, 8... Until 32.
> Maybe I understood the feature request wrong. (But if you know how to do it, I would be grateful).
> Atm I sample from ranint and then take that 2^x, but as you said it would be nicer to sample from the exp function directly.

Oh right, I should have re-read my original feature request more clearly :)) @richardliaw I don't think qloguniform would work for the batch size example in the original post; do you think we should add a `expuniformint` sampler? I *think* it's the same as just sampling from a geometric distribution

**Comment by jonas27** [comment]
I think it would be cool, then all results and tensor board graphics etc.
would be "correct". I also can't imagine that we are the only ones sampling
from exp distribution...
