### ISSUE TITLE
[Dashboard] Access dashboard when using slurm

### ISSUE THREAD

**Issue by kiranvad** [ray-project/ray#10605]
### What is your question?
I am trying to access the ray Dashboard on my laptop when using ray with slurm. 
Following a suggestion from @richardliaw  I used this [example](https://stackoverflow.com/questions/38464559/how-to-locally-view-tensorboard-of-remote-server) but it doesn't display anything.
*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.7, Ray 0.8.6, OS: mac

**Comment by rkooo567** [comment]
Can you try `ray dashboard` command? This is doing port forwarding for you so that your laptop can access the dashboard in the head node.

**Comment by kiranvad** [comment]
Thanks for the suggestion.
I tried this but it requires `cluster.yaml` as an input which I haven't set up 
I am using the example: [deploying on slurm](https://docs.ray.io/en/releases-0.8.5/deploying-on-slurm.html)

Any suggestions on how to get this working in this case?

**Comment by richardliaw** [comment]
@kiranvad I think there are new instructions for port forwarding here: https://docs.ray.io/en/master/cluster/slurm.html
