### ISSUE TITLE
[rllib][tune] How to limit the number of allocated threads?

### ISSUE THREAD

**Issue by lacerdamarcelo** [ray-project/ray#10604]
Hello everyone,

I've run TD3 with Population Based Training in a single-thread environment.
However, I see that when I run my script, thousands of threads are created.
How can I limit the number of threads per worker to 1? A PBT sample is using 2
workers, so I expect 2 threads + 1 thread for the driver. Since I've used 16 PBT
samples, I would expect the whole thing create 48 threads and use 48 CPUs,
which is exactly the amount of CPUs allocated for this job. This is the setup used in the execution.

```
config={
        "env": MyEnvironment,
        "env_config": env_config,
        "target_network_update_freq": tune.grid_search([int(value) for value in np.arange(100, 5001, (5001-100) / 16)]), # This allocates 16 samples
        "timesteps_per_iteration": 45000,
        "learning_starts": 45000,
        "train_batch_size": 45000,
        "sample_batch_size": 300,
        "buffer_size": 45000,
        "num_workers": 2,
        "num_gpus": 0,
        "num_cpus_per_worker": 1,
        "num_cpus_for_driver": 1,
        "critic_lr": 1e-4,
        "actor_lr": 1e-4,
        "tau": 2e-4,
        "actor_hiddens": [300, 300, 300, 300],
        "critic_hiddens": [300, 300, 300, 300],
        "l2_reg": 1e-6,
        "local_tf_session_args": {
              "intra_op_parallelism_threads": 1,
              "inter_op_parallelism_threads": 1,
              }
        }

run(
    TrainableWrapper,
    name=pbt_run_name,
    scheduler=pbt,
    num_samples=1,
    config=config,
    resources_per_trial={"cpu": 1, "extra_cpu": 2}
)
```
Is there any concept about Ray I may have misunderstood? Am I doing anything wrong?

Ray version: 0.8.4
Tensorflow: 2.2.0
Python version: 3.6.6
OS: CentOS 7

**Comment by al-rigazzi** [comment]
Actually, can anyone address this question? It seems like Ray (and tune) launch a lot of threads. Is there a way to contain this number?
