### ISSUE TITLE
Slowdown after loading large DataFrame

### ISSUE THREAD

**Issue by austinmw** [ray-project/ray#10622]
### What is the problem?

This may be more of a question than a bug, but I'm not quite sure.

I'm using Ray to speed up annotating then saving out images. This has been working great up until now. However, if I load parquet files as a large Pandas DataFrame before running this operation, I see a huge slowdown in my `.remote()` calls. 

Are there known reasons and possibly remedies for this?

-----

My specific case is a machine with 488GB RAM, loading a DataFrame that takes 65GB, using pyarrow:

```python
import pyarrow.parquet as pq
df = pq.ParquetDataset(parquet_dir).read_pandas().to_pandas()
```

For example (although maybe the specifics aren't too important):
```python
# Iterate over annotated frames with Ray
@ray.remote
def _anno_ray(frame, frame_annos):
    jpeg_path = jpegs[frame]
    # Open jpeg      
    img = cv2.imread(jpeg_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = _draw_annos(img, frame_annos)
     _save_pil(img, frame)

# This "futures = ..." line is what gets slowed down drastically (slower than not using Ray at all)
# It looks like the rate at which `_anno_ray` kicks off processes becomes much slower,
# but each process seems to operate at normal speed once started.
futures = [_anno_ray.remote(frame, frame_annos) for frame, frame_annos in df.groupby('Frame#')]

def to_iterator(obj_ids):
    while obj_ids:
        done, obj_ids = ray.wait(obj_ids)
        yield ray.get(done[0])

with tqdm(total=len(frames)) as pbar:
    for n,_ in enumerate(to_iterator(futures)):
        pbar.update(1)
        pbar.set_description(f"Annotating Frame #{n}") 
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6, Ray 0.8.7

### Reproduction (REQUIRED)
I'm not sure how to provide a reproducible script, as this only happens when loading extremely large DataFrames. Please advise if there's a more appropriate way to submit this.

**Comment by simon-mo** [comment]
Hi @austinmw, thanks for submitting this issue. I have two questions that might help diagnose this issue:
- How big is the `jpegs` list in `jpeg_path = jpegs[frame]`. I noticed this might be a global variable getting serialized each time. If this is big, you can consider `ray.put(jpegs)` and pass it as an argument in `_anno_ray`.

- The `futures = ...` line is slow because Ray is submitting each task one after each other. When submitting one task, Ray tries to save `frame` and `frame_annos` to bytes, slowing things down. How big are each of these? To address these, you can use https://github.com/modin-project/modin to perform distributed groupby and parallel submission. So something like:
```python
import modin.pandas as pd

df = pd.read_parquet(parquet_dir)
...
# futures should be a distributed pandas series.
futures = df.groupby("Frame#").apply(
    lambda frame_annos: _anno_ray.remote(
        frame=frame_annos["Frame#"].iloc[0], frame_annos=frame_annos
    )
)
```

**Comment by austinmw** [comment]
Hi @simon-mo , thanks for your help!

- The `jpegs` list is only approximately 150 items long of str filepaths.
- The odd thing is that this `futures =` line runs almost instantly when I do not have a large dataframe loaded. 
    - `frames` is also about 150 items long (just ints), and `frame_annos` are dataframes that are about 1000x8. 

Also I've tried:
```python
df = df_large.iloc[:1000].copy()
del df_large
```
Then running on this small dataframe instead, but for some reason just the fact that I'd previously loaded this larger dataframe ends up causing this slowdown. Also I should have previously mentioned that I'm running in a Jupyter notebook.
