### ISSUE TITLE
[ray] Problematic pickle5 version check in ray.init()

### ISSUE THREAD

**Issue by sytelus** [ray-project/ray#10637]
On Windows, Python 3.7, ray.init() fails with error that pickle5 distribution was not found under certain conditions.

```
ray: 0.8.7
python: 3.7.7
conda: 4.8.4
OS: Windows 10
```

This error occurs in the following code in `ray.init()`:

```
if "pickle5" in sys.modules:
    import pkg_resources
    version_info = pkg_resources.require("pickle5")
```

The error occurs when some other module has added pickle5 from its private directory. In this case, `pkg_resources.require` fails because the pickle5 wasn't installed while it still exist in sys.modules. I think above is a bad way to check version and prone to failure in ray.init itself. I'm also not sure why this version check is even being done as ray uses its private pickle5 files in subsequent lines anyway. So this check should either be removed OR may be use [better methods](https://stackoverflow.com/questions/8880661/getting-package-version-using-pkg-resources).

Following is the error call stack:

```
  File "C:\Users\shitals\Anaconda3\lib\site-packages\ray\__init__.py", line 14, in <module>
    self._popen = self._Popen(self)
  File "C:\Users\shitals\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    version_info = pkg_resources.require("pickle5")
  File "C:\Users\shitals\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\shitals\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\shitals\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 787, in resolve
        return Popen(process_obj)raise DistributionNotFound(req, requirers)

  File "C:\Users\shitals\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
pkg_resources.DistributionNotFound: The 'pickle5' distribution was not found and is required by the application
    reduction.dump(process_obj, to_child)
  File "C:\Users\shitals\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by richardliaw** [comment]
cc @suquark 

@sytelus thanks a bunch for opening this issue! Could you also try the Ray master (nightly) wheels?

**Comment by suquark** [comment]
The main issue is that pickle5 itself doesn't provide anything for version check (like version string etc). This is the only fairly stable way to check the pickle5 version. We enforce the version check, because previous pickle5 versions would leak memory (a known python 3.8.0 bug), causing hidden but serious troubles for users.

**Comment by sytelus** [comment]
@suquark - I see you are using private pickle5 files anyway. So do you still need version checks? If you do, can we use [other methods](https://stackoverflow.com/questions/8880661/getting-package-version-using-pkg-resources)? If not, can we make warning instead of exception?

Currently ray.init() is straight out failing and we have no way to fix it because older pickle5 is loaded from some other dependency we use from their own private path. With this hard error, we simply cannot use ray.

**Comment by suquark** [comment]
I think maybe the better way is to give users a warning when failed to detect the pickle5 version. In this case we cannot forcefully unload user's pickle5 module and replace with ours private pickle5 copy anyway, and users have to accept possible memory leaks if they are using previous pickle5 versions.
