### ISSUE TITLE
[tune] [rllib] Custom checkpoint directory name 

### ISSUE THREAD

**Issue by yonkshi** [ray-project/ray#10648]
### Is it possible to change the trial/run's directory name which contains all the checkpoint sub directories? 

I am seeing my runs stored in names such as `local_dir/experiment_name/PPO_0_2020-09-08_15-53-412ace9358/checkpoint_1/`. `PPO_0_2020-09-08_15-53-412ace9358` is not a very intuitive name. I am not using asynchronous training across different clusters, so I'd like to name them something simpler, such as `run_1`. I found the `trial_name_creator` in tune.run's parameters, but it doesn't seem to change the actual output dir's name.

*Ray version and other system information (Python version, TensorFlow version, OS): Python 3.6, Tensorflow 1.15, Ubuntu 20.04 LTS*

**Comment by richardliaw** [comment]
Hey @yonkshi, thanks for opening this! Are you on master? there should be `trial_dirname_creator` now.

**Comment by yonkshi** [comment]
Thank you @richardliaw, that's exactly what I was looking for :)

**Comment by daviddwlee84** [comment]
Seems Ray Trainer creates TensorBoard checkpoint in a similar way ([ray.train.RunConfig — Ray 2.8.1](https://docs.ray.io/en/latest/train/api/doc/ray.train.RunConfig.html#ray.train.RunConfig)) e.g. `storage_path/experiment_name/TrainerClassName_unique_id_00000_0_datetime`

Do we have a similar config like `trial_dirname_creator` in [ray.tune.TuneConfig — Ray 2.8.1](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.TuneConfig.html) for Trainer?

Not found in any of the Train Configs [Ray Train API — Ray 2.8.1](https://docs.ray.io/en/latest/train/api/api.html#ray-train-configuration)

**Comment by daviddwlee84** [comment]
It seems Trainer's `fit()` creates Tuner but has no user-defined TuneConfig passed

Maybe we can have `trial_dirname_creator` in the RunConfig or be able to pass TuneConfig in the Trainer's `fit()`

https://github.com/ray-project/ray/blob/171b828177420b2530d9fbe07f6914cdbf6ee0ba/python/ray/train/base_trainer.py#L578-L617

https://github.com/ray-project/ray/blob/171b828177420b2530d9fbe07f6914cdbf6ee0ba/python/ray/tune/impl/tuner_internal.py#L430-L451

https://github.com/ray-project/ray/blob/171b828177420b2530d9fbe07f6914cdbf6ee0ba/python/ray/train/_internal/storage.py#L660-L671
