### ISSUE TITLE
How are the number of iterations of a rollout determined in an execution plan and can this be influenced?[rllib]

### ISSUE THREAD

**Issue by FabianSchuetze** [ray-project/ray#10649]
How are the number of iterations of a rollout determined in one execution plan and how can this be influenced?

I am working my way through the `dqn` example and am trying to understand how the execution plan is built. In particular, I try to understand the [execution plan](https://github.com/ray-project/ray/blob/master/rllib/agents/dqn/dqn.py#L174) for the dqn agent 

```Python
    rollouts = ParallelRollouts(workers, mode="bulk_sync")

    # We execute the following steps concurrently:
    # (1) Generate rollouts and store them in our local replay buffer. Calling
    # next() on store_op drives this.
    store_op = rollouts.for_each(
        StoreToReplayBuffer(local_buffer=local_replay_buffer))

    def update_prio(item):
        samples, info_dict = item
        if config.get("prioritized_replay"):
            prio_dict = {}
            for policy_id, info in info_dict.items():
                # TODO(sven): This is currently structured differently for
                #  torch/tf. Clean up these results/info dicts across
                #  policies (note: fixing this in torch_policy.py will
                #  break e.g. DDPPO!).
                td_error = info.get("td_error",
                                    info[LEARNER_STATS_KEY].get("td_error"))
                prio_dict[policy_id] = (samples.policy_batches[policy_id]
                                        .data.get("batch_indexes"), td_error)
            local_replay_buffer.update_priorities(prio_dict)
        return info_dict

    # (2) Read and train on experiences from the replay buffer. Every batch
    # returned from the LocalReplay() iterator is passed to TrainOneStep to
    # take a SGD step, and then we decide whether to update the target network.
    post_fn = config.get("before_learn_on_batch") or (lambda b, *a: b)
    replay_op = Replay(local_buffer=local_replay_buffer) \
        .for_each(lambda x: post_fn(x, workers, config)) \
        .for_each(TrainOneStep(workers)) \
        .for_each(update_prio) \
        .for_each(UpdateTargetNetwork(
            workers, config["target_network_update_freq"]))

    # Alternate deterministically between (1) and (2). Only return the output
    # of (2) since training metrics are not available until (2) runs.
    train_op = Concurrently(
        [store_op, replay_op],
        mode="round_robin",
        output_indexes=[1],
        round_robin_weights=calculate_rr_weights(config))

    return StandardMetricsReporting(train_op, workers, config)
```
I understand that during a call of `next(rollouts)` each worker will make `'rollout_fragment_length':` steps through the environment. At the end of the this function, the `rollouts` are implicitly combined in the iterator `train_op` which will call `store_op` and then call `replay_op`. The execution plan is build with the return of `StandardMetricsReporting` which determines the `train_exec_impl` in `trainer_template.py`:
```
self.train_exec_impl = execution_plan(self.workers, config)
```
When calling `self.train_exec_impl` in the DQN example about 1000 steps are taken through the environment so that `rollouts` must have been called multiple times. Can somebody kindly explain how the number of calls to `rollouts` is determined and whether I can in any way influence that? I am grateful for any hints and explanations!

  
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray version: 0.8.7

**Comment by ericl** [comment]
This is determined by `StandardMetricsReporting`, which throttles the metric reporting to once every timesteps_per_iteration:
```
    output_op = train_op \
        .filter(OncePerTimestepsElapsed(config["timesteps_per_iteration"])) \
        .filter(OncePerTimeInterval(config["min_iter_time_s"])) \
        .for_each(CollectMetrics(...
```

This means that the upstream steps are repeated until a sufficient amount of timesteps as configured has elapsed, only after do which we do a round of metrics collections and reporting.

**Comment by FabianSchuetze** [comment]
Thanks a lot for the kind and detailed reply @ericl ! Your explanations made things clear to me.
