### ISSUE TITLE
Ray nightly 0.9 linux python 3.6 missing module dataclasses which is in 3.7

### ISSUE THREAD

**Issue by rhamnett** [ray-project/ray#10641]
Using https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl

dataclasses exists in python 3.7 but not 3.6, see below

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-cd7dd781f6f9> in <module>
----> 1 from ray.tune.logger import DEFAULT_LOGGERS
      2 from ray.tune.integration.wandb import WandbLogger
      3 
      4 import wandb
      5 # wandb.init(project="tensortrade")

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/__init__.py in <module>
      1 from ray.tune.error import TuneError
----> 2 from ray.tune.tune import run_experiments, run
      3 from ray.tune.syncer import SyncConfig
      4 from ray.tune.experiment import Experiment
      5 from ray.tune.analysis import ExperimentAnalysis, Analysis

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/tune.py in <module>
      2 
      3 from ray.tune.error import TuneError
----> 4 from ray.tune.experiment import convert_to_experiment_list, Experiment
      5 from ray.tune.analysis import ExperimentAnalysis
      6 from ray.tune.suggest import BasicVariantGenerator, SearchGenerator

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/experiment.py in <module>
      6 
      7 from ray.tune.error import TuneError
----> 8 from ray.tune.function_runner import detect_checkpoint_function
      9 from ray.tune.registry import register_trainable, get_trainable_cls
     10 from ray.tune.result import DEFAULT_RESULTS_DIR

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/function_runner.py in <module>
     12 from ray.util.debug import log_once
     13 from ray.tune import TuneError, session
---> 14 from ray.tune.trainable import Trainable, TrainableUtil
     15 from ray.tune.result import (TIME_THIS_ITER_S, RESULT_DUPLICATE,
     16                              SHOULD_CHECKPOINT)

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/trainable.py in <module>
     21 import ray
     22 from ray.util.debug import log_once
---> 23 from ray.tune.logger import UnifiedLogger
     24 from ray.tune.result import (
     25     DEFAULT_RESULTS_DIR, TIME_THIS_ITER_S, TIMESTEPS_THIS_ITER, DONE,

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/logger.py in <module>
     13                              EXPR_PARAM_PICKLE_FILE, EXPR_PROGRESS_FILE,
     14                              EXPR_RESULT_FILE)
---> 15 from ray.tune.syncer import get_node_syncer
     16 from ray.tune.utils import flatten_dict
     17 

~/anaconda3/envs/tensortrade/lib/python3.6/site-packages/ray/tune/syncer.py in <module>
      5 import os
      6 import time
----> 7 from dataclasses import dataclass
      8 
      9 from inspect import isclass

ModuleNotFoundError: No module named 'dataclasses'

**Comment by rhamnett** [comment]
I can pip install dataclasses, but is this what you would expect?

**Comment by simon-mo** [comment]
cc @krfricke @richardliaw

**Comment by richardliaw** [comment]
@rhamnett thanks a bunch for raising this issue! We've fixed this in https://github.com/ray-project/ray/pull/10365/files.

```
pip install -U latest_ray.whl
pip install ray[tune] # this will only install deps without overriding your above ray install
```

**Comment by richardliaw** [comment]
feel free to reopen if this is still an issue!
