### ISSUE TITLE
[tune] include variants in experiment_state.json

### ISSUE THREAD

**Issue by 0luhancheng0** [ray-project/ray#10643]
It would be very useful to includes all the user-defined variants in experiment_state.json.
Currently if i need to get all the variables i would have to pattern match the trial names.However the trial pattern seems to varies across experiments
And this would also be very useful when it comes to loading data into pandas multi-index data frame, where I can directly set each variant as one index set and do analysis by marginalizing any index set i wanted.

**Comment by richardliaw** [comment]
Hi, can you provide an example of this?

**Comment by krfricke** [comment]
Each config parameter is available in the `Analysis.dataframe()` and can be used for filtering there. If you need more functionality, please elaborate and feel free to re-open.
