### ISSUE TITLE
ray.init() error - "Retrying to connect to socket for pathname tcp..."

### ISSUE THREAD

**Issue by frankstack** [ray-project/ray#10655]
### What is the problem?

*Unable to ray.init() on Spyder 4.0 for Windows.*

### Explanation
I've just try to initialize **ray** in my Spyder by `import ray` and later defining:

`ray.init()`

However, my Sypder 4.0 gives me back this error in the console:

> runfile('C:/Users/FRANK/Anaconda3/envs/testenv/test_ray.py', wdir='C:/Users/FRANK/Anaconda3/envs/testenv')
> 2020-09-08 16:35:42,212	INFO resource_spec.py:212 -- Starting Ray with 10.11 GiB memory available for workers and up to 5.07 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
> 2020-09-08 16:35:42,791	INFO services.py:1165 -- View the Ray dashboard at localhost:8265
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> E0908 16:36:06.085281 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 7, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> E0908 16:36:06.085281 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 7, num_retries = 10)
> E0908 16:36:09.089551 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 8, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> E0908 16:36:06.085281 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 7, num_retries = 10)
> E0908 16:36:09.089551 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 8, num_retries = 10)
> E0908 16:36:12.095350 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 9, num_retries = 10)
> 
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> E0908 16:36:06.085281 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 7, num_retries = 10)
> E0908 16:36:09.089551 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 8, num_retries = 10)
> E0908 16:36:12.095350 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 9, num_retries = 10)
> F0908 16:36:13.095970 16612 25632 raylet_client.cc:78] Could not connect to socket tcp://127.0.0.1:58478
> *** Check failure stack trace: ***
>     @   00007FFFD9794A4C  public: __cdecl google::LogMessage::~LogMessage(void) __ptr64
>     @   00007FFFD9609914  public: virtual __cdecl google::NullStreamFatal::~NullStreamFatal(void) __ptr64
>     @   00007FFFD96444DB  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
>     @   00007FFFD9646B1E  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
>     @   00007FFFD9554B58  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD9552BC0  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD95510AD  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD9550983  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD94C3A97  public: virtual __cdecl google::LogSink::~LogSink(void) __ptr64
>     @   00000000774A6BEF  type_call
>     @   00000000774A847A  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000775FE971  _PyFunction_FastCall
>     @   00000000774F6D3F  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774AF83F  builtin_exec_impl
>     @   00000000774AF717  builtin_exec
>     @   00000000774A7A55  _PyCFunction_FastCallDict
>     @   00000000774A8129  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774AF83F  builtin_exec_impl
> 
> Kernel died, restarting
> 
> 
>  
> E0908 16:35:48.064086 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 1, num_retries = 10)
> E0908 16:35:51.070680 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 2, num_retries = 10)
> E0908 16:35:54.073267 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 3, num_retries = 10)
> E0908 16:35:57.077841 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 4, num_retries = 10)
> E0908 16:36:00.080662 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 5, num_retries = 10)
> E0908 16:36:03.082468 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 6, num_retries = 10)
> E0908 16:36:06.085281 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 7, num_retries = 10)
> E0908 16:36:09.089551 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 8, num_retries = 10)
> E0908 16:36:12.095350 16612 25632 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:58478 (num_attempts = 9, num_retries = 10)
> F0908 16:36:13.095970 16612 25632 raylet_client.cc:78] Could not connect to socket tcp://127.0.0.1:58478
> *** Check failure stack trace: ***
>     @   00007FFFD9794A4C  public: __cdecl google::LogMessage::~LogMessage(void) __ptr64
>     @   00007FFFD9609914  public: virtual __cdecl google::NullStreamFatal::~NullStreamFatal(void) __ptr64
>     @   00007FFFD96444DB  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
>     @   00007FFFD9646B1E  public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
>     @   00007FFFD9554B58  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD9552BC0  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD95510AD  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD9550983  public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
>     @   00007FFFD94C3A97  public: virtual __cdecl google::LogSink::~LogSink(void) __ptr64
>     @   00000000774A6BEF  type_call
>     @   00000000774A847A  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000775FE971  _PyFunction_FastCall
>     @   00000000774F6D3F  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774AF83F  builtin_exec_impl
>     @   00000000774AF717  builtin_exec
>     @   00000000774A7A55  _PyCFunction_FastCallDict
>     @   00000000774A8129  call_function
>     @   00000000774A8B5E  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774A8597  call_function
>     @   00000000774A97B8  _PyEval_EvalFrameDefault
>     @   00000000774A5DF8  _PyEval_EvalCodeWithName
>     @   00000000774AF83F  builtin_exec_impl
> [SpyderKernelApp] WARNING | No such comm: 3c676a26f21b11ea91fae0d55e82eab0

It seems extremely strange for me because I tried `ray` in a Jupyter Notebook of the same environment (_testenv_) before, and it works without any problems. It works even doing `ray.init()` or `ray.init(include_webui=False)`. Nevertheless, there is a slightly difference between them.

For the `ray.init()` simple case in my Jupyter Notebook, it returns:

> 2020-09-08 16:53:14,543	INFO resource_spec.py:212 -- Starting Ray with 9.96 GiB memory available for workers and up to 5.0 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
> 2020-09-08 16:53:15,558	INFO services.py:1165 -- View the Ray dashboard at localhost:8265
> 
> {'node_ip_address': '192.168.0.3',
>  'raylet_ip_address': '192.168.0.3',
>  'redis_address': '192.168.0.3:6379',
>  'object_store_address': 'tcp://127.0.0.1:63559',
>  'raylet_socket_name': 'tcp://127.0.0.1:60862',
>  'webui_url': 'localhost:8265',
>  'session_dir': 'C:\\Users\\FRANK\\AppData\\Local\\Temp\\ray\\session_2020-09-08_16-53-14_531203_10492'}
> 
> 2020-09-08 16:53:18,457	WARNING worker.py:1047 -- The dashboard on node DESKTOP-N8JUB39 failed with the following error:
> Traceback (most recent call last):
>   File "C:\Users\FRANK\Anaconda3\envs\testenv\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
>     metrics_export_address=metrics_export_address)
>   File "C:\Users\FRANK\Anaconda3\envs\testenv\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
>     build_dir = setup_static_dir(self.app)
>   File "C:\Users\FRANK\Anaconda3\envs\testenv\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
>     "&& npm run build)", build_dir)
> FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\Users\\FRANK\\Anaconda3\\envs\\testenv\\lib\\site-packages\\ray\\dashboard\\client/build'
> 

For the `ray.init(include_webui=False)` case, the cell give me back just:

> 2020-09-08 14:53:09,994	INFO resource_spec.py:212 -- Starting Ray with 10.5 GiB memory available for workers and up to 5.26 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
> 
> {'node_ip_address': '192.168.0.3',
>  'raylet_ip_address': '192.168.0.3',
>  'redis_address': '192.168.0.3:6379',
>  'object_store_address': 'tcp://127.0.0.1:60655',
>  'raylet_socket_name': 'tcp://127.0.0.1:65214',
>  'webui_url': None,
>  'session_dir': 'C:\\Users\\FRANK\\AppData\\Local\\Temp\\ray\\session_2020-09-08_14-53-09_990619_17552'}

Perhaps the `ray.init()` Warning Message in the Jupyter Notebook is related with the problem in Spyder. I'm not sure.

Just to add. I've figure out that this problem was the pretty much the same that in a previous closed issue [#9410](https://github.com/ray-project/ray/issues/9410). But the answers were too lazy—basically, the conclusion was that the antivirus cause this problem. I tried disabling my Avast Free antivirus and including Anaconda and everything related with python into their exceptions, but nothing seems to work. Moreover, in this case, my kernel is trying to fits the requirement of `ray` by trying to initialize it. Maybe that's why my kernel is restarting until the message `[SpyderKernelApp] WARNING | No such comm: 3c676a26f21b11ea91fae0d55e82eab0` arrives.

Here I leave my `python -c "import sys; print(sys.version)"` result in the cmd for this environment:

> (testenv) C:\Users\FRANK>python -c "import sys; print(sys.version)"
> 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]

Finally, here is my complete environment list of dependencies:

> (testenv) C:\Users\FRANK>conda list
> packages in environment at C:\Users\FRANK\Anaconda3\envs\testenv:
> 
> Name                    Version                   Build  Channel
> aiohttp                   3.6.2                    pypi_0    pypi
> alabaster                 0.7.12                   py36_0
> argh                      0.26.2                   py36_0
> argon2-cffi               20.1.0           py36he774522_1
> asciitree                 0.3.3                    pypi_0    pypi
> astroid                   2.4.2                    py36_0
> async-timeout             3.0.1                    pypi_0    pypi
> atomicwrites              1.4.0                      py_0
> attrs                     20.2.0                   pypi_0    pypi
> autopep8                  1.5.4                      py_0
> babel                     2.8.0                      py_0
> backcall                  0.2.0                      py_0
> bcrypt                    3.2.0            py36he774522_0
> beautifulsoup4            4.9.1                    pypi_0    pypi
> bleach                    3.1.5                      py_0
> bokeh                     2.2.1                    pypi_0    pypi
> brotlipy                  0.7.0           py36he774522_1000
> ca-certificates           2020.7.22                     0
> certifi                   2020.6.20                py36_0
> cffi                      1.14.2           py36h7a1dbc1_0
> chardet                   3.0.4                 py36_1003
> click                     7.1.2                    pypi_0    pypi
> cloudpickle               1.6.0                      py_0
> colorama                  0.4.3                      py_0
> contextvars               2.4                      pypi_0    pypi
> cryptography              3.1              py36h7a1dbc1_0
> dask                      2.25.0                   pypi_0    pypi
> decorator                 4.4.2                      py_0
> defusedxml                0.6.0                      py_0
> diff-match-patch          20200713                   py_0
> distributed               2.25.0                   pypi_0    pypi
> docutils                  0.16                     py36_1
> entrypoints               0.3                      py36_0
> fasteners                 0.15                     pypi_0    pypi
> filelock                  3.0.12                   pypi_0    pypi
> flake8                    3.8.3                      py_0
> future                    0.18.2                   py36_1
> google                    3.0.0                    pypi_0    pypi
> grpcio                    1.31.0                   pypi_0    pypi
> heapdict                  1.0.1                    pypi_0    pypi
> icu                       58.2                 ha925a31_3
> idna                      2.10                       py_0
> idna-ssl                  1.1.0                    pypi_0    pypi
> imagesize                 1.2.0                      py_0
> immutables                0.14                     pypi_0    pypi
> importlib-metadata        1.7.0                    py36_0
> importlib_metadata        1.7.0                         0
> intervaltree              3.1.0                      py_0
> ipykernel                 5.3.4            py36h5ca1d4c_0
> ipython                   7.16.1           py36h5ca1d4c_0
> ipython_genutils          0.2.0                    py36_0
> isort                     5.4.2                    py36_0
> jedi                      0.17.1                   py36_0
> jinja2                    2.11.2                     py_0
> jpeg                      9b                   hb83a4c4_2
> jsonform                  0.0.2                    pypi_0    pypi
> jsonschema                3.2.0                    py36_0
> jsonsir                   0.0.2                    pypi_0    pypi
> jupyter_client            6.1.6                      py_0
> jupyter_core              4.6.3                    py36_0
> keyring                   21.4.0                   py36_0
> lazy-object-proxy         1.4.3            py36he774522_0
> libpng                    1.6.37               h2a8f88b_0
> libsodium                 1.0.18               h62dcd97_0
> libspatialindex           1.9.3                h33f27b4_0
> llvmlite                  0.34.0                   pypi_0    pypi
> m2w64-gcc-libgfortran     5.3.0                         6
> m2w64-gcc-libs            5.3.0                         7
> m2w64-gcc-libs-core       5.3.0                         7
> m2w64-gmp                 6.1.0                         2
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2
> markupsafe                1.1.1            py36he774522_0
> mccabe                    0.6.1                    py36_1
> mistune                   0.8.4            py36he774522_0
> modin                     0.8.0                    pypi_0    pypi
> monotonic                 1.5                      pypi_0    pypi
> msgpack                   1.0.0                    pypi_0    pypi
> msys2-conda-epoch         20160418                      1
> multidict                 4.7.6                    pypi_0    pypi
> nbconvert                 5.6.1                    py36_0
> nbformat                  5.0.7                      py_0
> notebook                  6.1.1                    py36_0
> numba                     0.51.2                   pypi_0    pypi
> numcodecs                 0.6.4                    pypi_0    pypi
> numpy                     1.19.1                   pypi_0    pypi
> numpydoc                  1.1.0                      py_0
> openssl                   1.1.1g               he774522_1
> packaging                 20.4                       py_0
> pandas                    1.0.5                    pypi_0    pypi
> pandas-market-calendars   1.4.2                    pypi_0    pypi
> pandoc                    2.10.1                        0
> pandocfilters             1.4.2                    py36_1
> paramiko                  2.7.2                      py_0
> parso                     0.7.0                      py_0
> pathtools                 0.1.2                      py_1
> pexpect                   4.8.0                    py36_0
> pickleshare               0.7.5                    py36_0
> pillow                    7.2.0                    pypi_0    pypi
> pip                       20.2.2                   py36_0
> pluggy                    0.13.1                   py36_0
> prometheus_client         0.8.0                      py_0
> prompt-toolkit            3.0.7                      py_0
> protobuf                  3.13.0                   pypi_0    pypi
> psutil                    5.7.2            py36he774522_0
> py-spy                    0.3.3                    pypi_0    pypi
> pyarrow                   0.16.0                   pypi_0    pypi
> pycodestyle               2.6.0                      py_0
> pycparser                 2.20                       py_2
> pydocstyle                5.1.1                      py_0
> pyflakes                  2.2.0                      py_0
> pygments                  2.6.1                      py_0
> pylint                    2.6.0                    py36_0
> pynacl                    1.4.0            py36h62dcd97_1
> pyopenssl                 19.1.0                     py_1
> pyparsing                 2.4.7                      py_0
> pyqt                      5.9.2            py36h6538335_2
> pyrsistent                0.16.0           py36he774522_0
> pysocks                   1.7.1                    py36_0
> python                    3.6.10               h9f7ef89_2
> python-dateutil           2.8.1                      py_0
> python-easyconfig         0.1.7                    pypi_0    pypi
> python-jsonrpc-server     0.3.4                      py_1
> python-language-server    0.34.1                   py36_0
> pytz                      2020.1                     py_0
> pywin32                   227              py36he774522_1
> pywin32-ctypes            0.2.0                 py36_1000
> pywinpty                  0.5.7                    py36_0
> pyyaml                    5.3.1                    pypi_0    pypi
> pyzmq                     19.0.1           py36ha925a31_1
> qdarkstyle                2.8.1                      py_0
> qt                        5.9.7            vc14h73c81de_0
> qtawesome                 0.7.2                      py_0
> qtconsole                 4.7.6                      py_0
> qtpy                      1.9.0                      py_0
> ray                       0.8.6                    pypi_0    pypi
> redis                     3.4.1                    pypi_0    pypi
> requests                  2.24.0                     py_0
> resource                  0.2.1                    pypi_0    pypi
> rope                      0.17.0                     py_0
> rtree                     0.9.4            py36h21ff451_1
> send2trash                1.5.0                    py36_0
> setproctitle              1.1.10                   pypi_0    pypi
> setuptools                49.6.0                   py36_0
> sip                       4.19.8           py36h6538335_0
> six                       1.15.0                     py_0
> snowballstemmer           2.0.0                      py_0
> sortedcontainers          2.2.2                      py_0
> soupsieve                 2.0.1                    pypi_0    pypi
> sphinx                    3.2.1                      py_0
> sphinxcontrib-applehelp   1.0.2                      py_0
> sphinxcontrib-devhelp     1.0.2                      py_0
> sphinxcontrib-htmlhelp    1.0.3                      py_0
> sphinxcontrib-jsmath      1.0.1                      py_0
> sphinxcontrib-qthelp      1.0.3                      py_0
> sphinxcontrib-serializinghtml 1.1.4                      py_0
> spyder                    4.1.5                    py36_0
> spyder-kernels            1.9.4                    py36_0
> sqlite                    3.33.0               h2a8f88b_0
> tblib                     1.7.0                    pypi_0    pypi
> terminado                 0.8.3                    py36_0
> testpath                  0.4.4                      py_0
> toml                      0.10.1                     py_0
> toolz                     0.10.0                   pypi_0    pypi
> tornado                   6.0.4            py36he774522_1
> traitlets                 4.3.3                    py36_0
> typed-ast                 1.4.1            py36he774522_0
> typing-extensions         3.7.4.3                  pypi_0    pypi
> ujson                     1.35             py36hfa6e2cd_0
> urllib3                   1.25.10                    py_0
> vc                        14.1                 h0510ff6_4
> vs2015_runtime            14.16.27012          hf0eaf9b_3
> watchdog                  0.10.3                   py36_0
> wcwidth                   0.2.5                      py_0
> webencodings              0.5.1                    py36_1
> wheel                     0.34.2                   py36_0
> whitehole                 0.0.3                    pypi_0    pypi
> win_inet_pton             1.1.0                    py36_0
> wincertstore              0.2              py36h7fe50ca_0
> winpty                    0.4.3                         4
> wrapt                     1.11.2           py36he774522_0
> xarray                    0.16.0                   pypi_0    pypi
> yaml                      0.2.5                he774522_0
> yapf                      0.30.0                     py_0
> yarl                      1.5.1                    pypi_0    pypi
> zarr                      2.4.0                    pypi_0    pypi
> zeromq                    4.3.2                ha925a31_2
> zict                      2.0.0                    pypi_0    pypi
> zipp                      3.1.0                      py_0
> zlib                      1.2.11               h62dcd97_4

I find `ray` very useful. However, I would like your help in solving this issue. 

Many thanks.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Hmm yeah @frankstack thanks a bunch for opening this issue. I wish we had a better diagnostic tool for this. cc @mehrdadn do you have any thoughts?

**Comment by mehrdadn** [comment]
@richardliaw Not anything beyond my comment on the other issue currently.  
@frankstack For what it's worth, it may still be your antivirus, as some antiviruses still keep their drivers loaded and don't entirely turn off despite what the GUI may tell you. It would be nice if you can reproduce this on a system that's never had any AV installed at all. However, if that doesn't seem to be the issue, what do [the other steps in my comment](/ray-project/ray/issues/9410#issuecomment-656936821) result in?

**Comment by mehrdadn** [comment]
Oh, also, it'd be nice to check if Python >= 3.8.2 behave similarly.

**Comment by frankstack** [comment]
@mehrdadn Oh no, sorry. There is nothing wrong with your previous answer. It's just that I thought maybe I could find more information. But don't worry. I just tried using a new environment with python 3.8.2 and it works without any problem. 

Many thanks for your support!
