### ISSUE TITLE
[rllib] Inform the agent a new episode starts

### ISSUE THREAD

**Issue by xlnwel** [ray-project/ray#10678]
### What is your question?
Is there a way to tell the agent that a new episode starts when I define a custom `action_sampler_fn` for rllib's Ape-X?

*Ray version and other system information (Python version, TensorFlow version, OS):*
`ray[rllib]==0.8.6`

**Comment by xlnwel** [comment]
I've tried to incorporate the signal into observation using environment wrapper as follows:

```python
class ResetSignal(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)

        self.observation_space = gym.spaces.Dict({
            'img': self.env.observation_space,
            'reset': gym.spaces.Discrete(2),
        })

    def reset(self):
        obs = self.env.reset()

        return {'img': obs, 'reset': 1}

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        obs = {'img': obs, 'reset': 0}
        return obs, reward, done, info
```

When using the above wrapper, I received an issue from `make_model` function(see [this](https://github.com/ray-project/ray/blob/a43817f34b5fe8cff784385be455883335ecb45c/rllib/agents/dqn/dqn_tf_policy.py#L133) for an example) and I print the observation space(the one passed to `make_model` ) which basically says that `observation_space` becomes `Box(49154,)`. 

I can make a temporary solution by hard-coding the observation space in `make_model` and ignore the parameter `obs_space`. Although this time no error is emitted, but I found `obs_batch` of [this function](https://github.com/ray-project/ray/blob/a43817f34b5fe8cff784385be455883335ecb45c/rllib/agents/dqn/dqn_tf_policy.py#L193) does not contain `reset`

**Comment by ericl** [comment]
@xlnwel thanks for posting this from slack. The way RLlib deals with complex observations is by flattening them into a vector, and then inside ModelV2, it unflattens them before calling forward() on your model: https://github.com/ray-project/ray/blob/master/rllib/models/modelv2.py#L199

Most likely, this means you shouldn't be looking at the obs space inside your custom policy at all -- only inside a custom ModelV2 class which will get the tensor input shape as input_dict["obs"]. Or, you can access the original unflattened space as `obs_space.original_space`.

In the rare case that you do need to access the unflattened observation in the policy as well (outside of your modelv2 subclass), then you should also be able to create the unflattened tensor by calling the restore_original_dimensions() utility as inhttps://github.com/ray-project/ray/blob/master/rllib/models/modelv2.py#L199

Hope this helps.

**Comment by xlnwel** [comment]
Hi @ericl 

I now can retrieve the original observation space using `observation_space.original_space` as you suggested. But in [this function](https://github.com/ray-project/ray/blob/a43817f34b5fe8cff784385be455883335ecb45c/rllib/agents/dqn/dqn_tf_policy.py#L193), `obs_batch` is still a tensor of shape `(1, 49154)`. This further propagates to the `forward` function of my custom ModelV2 class. It seems that `restore_original_dimensions` does not do its job: I've also tried to apply it inside forward using the following code

```
        from ray.rllib.models.modelv2 import restore_original_dimensions
        print('forward', self.obs_space)
        obs = restore_original_dimensions(obs, self.obs_space, 'tfe')
        print('restored1', obs)
```

It prints

>forward Dict(img:Box(64, 64, 12), reset:Discrete(2))
restored1 tf.Tensor(
[[-0.47931755 -0.24324611  0.09571177 ...  0.12295954  0.36106703
 -0.531775  ]], shape=(1, 49154), dtype=float32)

As you can see from the above code, the tensor does not changed.

**Comment by ericl** [comment]
Hmm input_dict['obs'] should definitely be already restored. I'm not sure what's going on exactly, I would recommend trying to see how it works in DQN etc, which definitely support Dict spaces.

(basically, try getting your custom model to work in a normal algorithm first, then debugging any differences with your custom algorithm

**Comment by xlnwel** [comment]
Hi @ericl 

Thank you for your advice. I finally find the source of the problem. It turns out that I should pass to my custom model the flatten `obs_space`, which has the `original_space` attribute. 

I also noticed that the `reset` I defined in the wrapper is somehow changed when I print it in `forward`. Do you think my `Wrapper` class is right?

```python
class ResetSignal(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)

        self.observation_space = gym.spaces.Dict({
            'img': self.env.observation_space,
            'reset': gym.spaces.Discrete(2),
        })

    def reset(self):
        obs = self.env.reset()

        return {'img': obs, 'reset': 1}

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        obs = {'img': obs, 'reset': 0}
        return obs, reward, done, info
```
