### ISSUE TITLE
[tune] Concurrent trials of tensorflow models on a single GPU

### ISSUE THREAD

**Issue by AlkaidCheng** [ray-project/ray#10677]
If the machine only has a single GPU, is it possible run multiple trials concurrently when dealing with tensorflow models?

I tried to do so by setting a fractional value of resources per trial for the gpu but ended up having the error
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

**Comment by krfricke** [comment]
Sorry for letting this slip @AlkaidCheng. Generally this should be possible, this is exactly what partial resources are for. Is this issue still there or did you find a different way to handle this in the meantime?

**Comment by nebraswarsi** [comment]
I have the exact same issue - not sure how to solve it still. Any advice would be appreciated!

Happy to share code snippets and etc. The error is the same: even though I’m setting fractional GPU resources, and only importing tf within my objective function, I still get a crash stating that all CUDA capable devices are unavailable ...
