### ISSUE TITLE
[rllib] Error when restoring checkpoint: 'TypeError: unhashable type: 'slice''

### ISSUE THREAD

**Issue by ZekiDorukErden** [ray-project/ray#10681]
Hello,

I get the following error when I try to restore a checkpoint:

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-d153901de529> in <module>()
    194       last_checkpoint_str = str(folder_list[-1])
    195       last_checkpoint_num = int(last_checkpoint_str.replace('_',' ').split()[-1]) 
--> 196       trainer.restore(checkpoint_folder + '/' + 'checkpoint_' + format(last_checkpoint_num) + '/checkpoint-' + format(last_checkpoint_num) )
    197       print('Restored checkpoint ' + str(last_checkpoint_num))
    198 

8 frames
/usr/local/lib/python3.6/dist-packages/ray/experimental/tf_utils.py in unflatten(vector, shapes)
     16     for shape in shapes:
     17         size = np.prod(shape, dtype=np.int)
---> 18         array = vector[i:(i + size)].reshape(shape)
     19         arrays.append(array)
     20         i += size

TypeError: unhashable type: 'slice'
`

The trainer definition that I use is as follows:

`trainer = PPOTrainer(
              env=env_title,
              config={
                "model": nw_model,
               "multiagent": {
                  "policy_graphs": policy_graphs,
                  "policy_mapping_fn": policy_mapping_fn,
                  "policies_to_train": ["ppo_policy{}".format(i) for i in range(n_agents)],
                },
                "callbacks": {
                  "on_episode_start": tune.function(on_episode_start),
                  "on_episode_step": tune.function(on_episode_step),
                  "on_episode_end": tune.function(on_episode_end),
                },
                "log_level": "ERROR",
              })"""`

The line that I restore the checkpoint, as it is also seen on the error traceback, is as:

`trainer.restore(checkpoint_folder + '/' + 'checkpoint_' + format(last_checkpoint_num) + '/checkpoint-' + format(last_checkpoint_num)`

I double checked that the argument is a valid path.

I tried to do it with multiple checkpoints. Still the same error.

The platform I use is Google CoLab.

Thank you in advance!

**Comment by alirezanobakht13** [comment]
I have this error too. does anyone know how to fix this?

**Comment by ZekiDorukErden** [comment]
I found it to be an issue with the version. On Colab I was using version 0.8.7, while the trainer checkpoint I was trying to load was obtained with a later version, apparently not backwards compatible. You may want to check if this is the case.
