### ISSUE TITLE
Update documentation to avoid deprecated fields 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#10697]
### What is the problem?

We currently have lots of documentation that refers to fields which are now removed or hidden in Ray 1.0 (`redis_password` is the worst offender). We should make sure we remove these before Ray 1.0 is released. This should involve no code changes. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
This task is P0, but it doesn't have an owner. Should we downgrade it?

**Comment by wuisawesome** [comment]
Only if you want documentation which refers to fields that don't exist in 1.0

**Comment by rkooo567** [comment]
I see my bad... Didn't read the description enough

**Comment by ericl** [comment]
Is this resolved now?

**Comment by wuisawesome** [comment]
I think we've removed all _wrong_ references, but there are still things we should improve like we shouldn't recommend people use `_redis_password`
