### ISSUE TITLE
Could not connect to socket /tmp/ray/session

### ISSUE THREAD

**Issue by PengLong666** [ray-project/ray#10704]
what should I do with ray.init()?  And I have tried to change object_memory, but it doesn't work. 
 python is 3.6.2,  ray is 0.8.6, torch is 1.6.0. 

2020-09-11 01:21:32,856	INFO resource_spec.py:212 -- Starting Ray with 293.85 GiB memory available for workers and up to 13.97 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-09-11 01:21:32,973	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-09-11 01:21:33,212	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-09-11 01:21:33,501	INFO services.py:1165 -- View the Ray dashboard at localhost:8268
E0911 01:21:34.567864 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 1, num_retries = 10)
E0911 01:21:35.568418 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 2, num_retries = 10)
E0911 01:21:36.568711 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 3, num_retries = 10)
E0911 01:21:37.569022 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 4, num_retries = 10)
^CE0911 01:21:38.298298 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 5, num_retries = 10)
^CE0911 01:21:38.474228 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 6, num_retries = 10)
^CE0911 01:21:38.634560 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 7, num_retries = 10)
^CE0911 01:21:38.778551 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 8, num_retries = 10)
^CE0911 01:21:38.938321 222608 222608 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-09-11_01-21-32_853982_222608/sockets/raylet (num_attempts = 9, num_retries = 10)

**Comment by stefanbschneider** [comment]
What's your "supercomputer"?

> ray.init(memory=10000000000,object_store_memory=5000000000)

Why would you do that?

---

I had a similar issue on Ubuntu 20 (WSL) with ray 0.8.7 but it works when downgrading to 0.8.6. You could give that a try.

**Comment by PengLong666** [comment]
> What's your "supercomputer"?
> 
> > ray.init(memory=10000000000,object_store_memory=5000000000)
> 
> Why would you do that?
> 
> I had a similar issue on Ubuntu 20 (WSL) with ray 0.8.7 but it works when downgrading to 0.8.6. You could give that a try.

Thanks for replying. The supercomputer is a computing resource given by my university. I found someone said that the error may be caused by the ray.init(), so I change it. And the ray in my computer is 0.8.7, i will try to change it. Thank you.
