### ISSUE TITLE
[autoscaler] ray submit check/rsync local and node code

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#10707]
One thing that's really important for reproducibility is making sure the training code on the cluster is exactly the same as the local dev environment. I believe we should have the option to make this check when calling "ray submit ... ", and either cancelling the job if the code on the cluster is different, or rsyncing to update the cluster code.

This option would check the cluster YAML file, and rsync the directories in file_mounts.

#10216

**Comment by wuisawesome** [comment]
We should probably be syncing consistently when executing anything on a cluster (including `ray exec`)

**Comment by richardrl** [comment]
Also another related thing that can be done is ensuring every code change is committed in Git before allowing ray submit something.

**Comment by richardliaw** [comment]
should be fixed
