### ISSUE TITLE
Why are the results when building a trainer from `ray.rllib.agents.trainer_template.build_trainer` so much worse than using `DQNTrainer` directly? [question]

### ISSUE THREAD

**Issue by FabianSchuetze** [ray-project/ray#10716]
I am working through the section [RLlib Concepts and Custom Algorithms](https://docs.ray.io/en/latest/rllib-concepts.html) and try to understand how to generate custom trainers.

I thereby realized that instantiating a trainer with a `DQNTorchPolicy` from `ray.rllib.agents.trainer_template.build_trainer` lead to much lower performance than when using a DQNTrainer (with `framework:torch`). Below is a simple example:

```Python
import ray
from ray.rllib.agents.trainer_template import build_trainer
from ray.rllib.agents.dqn import DQNTorchPolicy, DQNTrainer

if __name__ == "__main__":
    ray.init(num_cpus=1, ignore_reinit_error=True)
    ## == Results when using DQN trainer are good == ##
    dqn_trainer = DQNTrainer(config={'framework': 'torch'}, env='CartPole-v0')
    print('\n------------------------------------------------------')
    print("Trainer build from `DQNTrainer`:")
    for i in range(12):
        results = dqn_trainer.train()
        print("Iter %i avg reward %i" % (i, results['episode_reward_mean']))

    ## == Results when using `build_trainer` are not good == ##
    config = ray.rllib.agents.dqn.DEFAULT_CONFIG.copy()
    config['num_workers'] = 0
    trainer = build_trainer('my_dqn', default_policy=DQNTorchPolicy,
                            default_config=config)(env='CartPole-v0')
    print('\n------------------------------------------------------')
    print("Trainer build from `build_trainer`:")
    for i in range(12):
        results2 = trainer.train()
        print("Iter %i avg reward %i" % (i, results2['episode_reward_mean']))
```
At first, I create a trainer from `DQNTrainer` and the results are perfectly fine. When, I however create a policy with 
```
build_trainer('my_dqn', default_policy=DQNTorchPolicy, default_config=config)(env='CartPole-v0')
```
the results are much worse. Running the entire script prints the following output:
```Shell
------------------------------------------------------
The rewards for a trainer build from `DQNTrainer` are:
Iter 0 avg reward 19
Iter 1 avg reward 18
Iter 2 avg reward 19
Iter 3 avg reward 25
Iter 4 avg reward 33
Iter 5 avg reward 40
Iter 6 avg reward 49
Iter 7 avg reward 58
Iter 8 avg reward 67
Iter 9 avg reward 75
Iter 10 avg reward 85
Iter 11 avg reward 93

------------------------------------------------------
The rewards for a trainer build from `build_trainer` are:
Iter 0 avg reward 24
Iter 1 avg reward 23
Iter 2 avg reward 26
Iter 3 avg reward 22
Iter 4 avg reward 16
Iter 5 avg reward 21
Iter 6 avg reward 10
Iter 7 avg reward 9
Iter 8 avg reward 11
Iter 9 avg reward 12
Iter 10 avg reward 11
Iter 11 avg reward 10
```

 I expected, however, to be the policies in both examples the same (as I use the `DQNTorchPolicy` in the second example).

I thus wonder if I did not properly set some other configurations and if that might explain the difference in results? What do I need to do to create a trainer that is doing as well as the first one and still use `DQNTorchPolicy` directly? 

I am grateful for any hints and suggestions!  

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray Version: 0.8.7.

**Comment by ericl** [comment]
Great question. The difference is that DQNTrainer actually overrides some more aspects of training (mainly, adding a replay buffer). You can see this from dqn.py:
```
GenericOffPolicyTrainer = build_trainer(
    name="GenericOffPolicyAlgorithm",
    default_policy=None,
    get_policy_class=get_policy_class,
    default_config=DEFAULT_CONFIG,
    validate_config=validate_config,
    execution_plan=execution_plan)  <----------- overrides execution plan with one that uses replay buffers

DQNTrainer = GenericOffPolicyTrainer.with_updates(
    name="DQN", default_policy=DQNTFPolicy, default_config=DEFAULT_CONFIG)
```

If you instead build your trainer with `DQNTrainer.with_updates(get_policy_class=...)`, then that will inherit the replay buffer and config from DQN and should achieve the same performance.

**Comment by FabianSchuetze** [comment]
Thanks for this wonderful answers - you helped me a lot!
