### ISSUE TITLE
Will ray support distribute tensorflow feature engineerring component? 

### ISSUE THREAD

**Issue by csdingbin** [ray-project/ray#10714]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):
Such as https://github.com/tensorflow/models/blob/master/research/slim/datasets/build_imagenet_data.py, which was used to process the data of imagenet dataset. Will ray support to distribute it? Or How to distribute it on Ray. Hi @richardliaw or other guys, do you have any idea on this?

**Comment by rkooo567** [comment]
cc @richardliaw
