### ISSUE TITLE
Consider removing Redis clients from worker processes.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1071]
This could be done by having the global state APIs go through the local scheduler or perhaps through a different process.

This would help with the problem where we reach the maximum number of Redis clients.

**Comment by mitar** [comment]
You could probably increase the number of Redis clients somehow?

**Comment by robertnishihara** [comment]
Yes, from a redis client you can do something like `redis_client.config_set('maxclients', 65534)`. Before that, you need to do `ulimit -n 65536`. You can potentially increase this number further if you have `sudo`.

This gets us pretty far, although it'd be nice to do it automatically.

**Comment by robertnishihara** [comment]
Duplicate of #952.
