### ISSUE TITLE
`ray start` should error by default if there's already a ray cluster running

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#10717]
I often run into issues by accidentally starting a new cluster when one is already running. Then, this later causes problems when I try to connect and there are two running clusters. I'm then forced to `ray stop` both clusters and `ray start` my new one again.

My workflow would be improved if I just got an error when trying to start the second cluster and knew to immediately tear down the existing one. This behavior may be useful in some cases (e.g., for testing), so we could introduce a flag to permit multiple clusters, e.g., `ray start --allow-existing`.

**Comment by ericl** [comment]
I thought we actually used to raise an error, this might be a regression.

**Comment by ericl** [comment]
cc @stephanie-wang it might be related to the autoscaler issue you were investigating before.

**Comment by wuisawesome** [comment]
@ericl when was the last time you saw an error? We don't have that check in 0.8.7 (starting multiple clusters is fine)

**Comment by ericl** [comment]
Ah, this is it: if you run `ray start --head --port 6379` (specifying the port), it does indeed start successfully only once. So @edoakes you can just make sure to specify the port and this behavior will happen by default.

**Comment by oliverhu** [comment]
🙋  to help

**Comment by wuisawesome** [comment]
Closed by #10826
