### ISSUE TITLE
[autoscaler] No module named 'cryptography' (GCP)

### ISSUE THREAD

**Issue by qxcv** [ray-project/ray#10724]
### What is the problem?

`ray/autoscaler/gcp/config.py` imports something from `cryptography`, but this module is not installed by default (e.g. with `pip install ray[tune]`).

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 0.8.7, Python 3.8

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```bash
conda create -n test-ray-cryptography python=3.8
conda activate test-ray-cryptography
hash -r
pip install 'ray[tune]'
python -m ray.autoscaler.gcp.config  # fails
pip install -U 'https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp38-cp38-manylinux1_x86_64.whl'
python -m ray.autoscaler.gcp.config  # fails, same error
```

Output of the last command:

```
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/test-ray-cryptography/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sam/anaconda3/envs/test-ray-cryptography/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sam/anaconda3/envs/test-ray-cryptography/lib/python3.8/site-packages/ray/autoscaler/gcp/config.py", line 7, in <module>
    from cryptography.hazmat.primitives import serialization
ModuleNotFoundError: No module named 'cryptography'
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
non-critical dependencies are not packaged with Ray. since only the GCP autoscaler uses the `cryptography` package you will need to pip install it yourself.

**Comment by qxcv** [comment]
Can it be added to `extras` so that users don't have to guess which version is required?
(e.g. `pip install ray[gcp]`)

**Comment by richardliaw** [comment]
Yeah that'd be pretty useful.

**Comment by wuisawesome** [comment]
I think we do have `pip install ray[all]`. If `cryptography` isn't included in that, then that's a bug.

**Comment by qxcv** [comment]
I can't see it in setup.py. I also can't see google-api-python-client,
which is also required by the GCP stuff (it does appear in one of the
dockerfiles though).
The two deps I had to add are:

```
cryptography~=3.1
google-api-python-client~1.11.0
```

(`ray up` now runs without import errors, but I can't confirm that it works
for sure because I'm running into some Ray-unrelated permissions issues)
