### ISSUE TITLE
IDLE workers holding GPU resources

### ISSUE THREAD

**Issue by acdifran** [ray-project/ray#10739]
I am very new to ray and I recently updated some code from ray 0.8.0 to 0.8.6 and am running into an issue where my workers seem to be holding onto GPU resources after this update. Previously all submitted tasks would complete, but now after a few tasks run, the remaining tasks hang. I took a look at the dashboard and see some IDLE workers that have GPU resources assigned. I set "max_calls=1" for all remote functions, but I still see these IDLE workers holding onto portions of the GPU. It was my understanding that after completing a task, the worker should free the GPU resources it was holding if max_calls is set. Am I misunderstanding how this functions?

Ray 0.8.6
Ubuntu 16.4
Python 3.6
Pytorch 1.2.0

![Screen Shot 2020-09-10 at 5 02 34 PM](https://user-images.githubusercontent.com/25591626/92954639-a140ea80-f418-11ea-8056-f08ed396ecb1.png)

**Comment by rkooo567** [comment]
Can you post a reproduction script? I can try to figure out why it happens in that case.

**Comment by acdifran** [comment]
@rkooo567 After some more digging around, I was able to find the code in my project that is causing this and create a simple example to show what's going on. The issue seems to stem from directly putting and getting objects. Here is a code sample that produces the error I was seeing:

```python
import ray
import time

ray.init(include_webui=True, num_cpus=2)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, num_gpus=1, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, num_gpus=1, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) * 20

for _ in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
```

When I run this on a machine with 1 gpu, the first 4 tasks to start will use up all the gpu resources and never release them, so the program hangs and I end up with this on the dashboard:

![ray_bug_gpus](https://user-images.githubusercontent.com/25591626/93403354-2292e580-f83c-11ea-8959-87550ade4191.png)

If I remove "num_gpus" and just use cpus, all the tasks will run (since it seems cpu resources are given back/not blocked), but once the tasks are done running, I'm left with an IDLE task for each task that ran and they are all holding onto RAM:

![ray_bug_cpu](https://user-images.githubusercontent.com/25591626/93403428-5837ce80-f83c-11ea-9eb2-feb87d85f578.png)

For this simple example, I can use nested calls to avoid the direct put and get and this seems to resolve things, but this is difficult for me to do in my actual application since the code there is more complex.

**Comment by rkooo567** [comment]
Btw, you should also specify `num_gpus=1` in ray.init.

**Comment by rkooo567** [comment]
I couldn't reproduce this in the nightly with this script.

```
import ray
import time

ray.init(num_gpus=1, num_cpus=2)

sleep_seconds = 5

@ray.remote
def nested():
    return 11

@ray.remote(num_cpus=1, max_calls=1)
def do_something():
    time.sleep(sleep_seconds)
    return ray.get(nested.remote()) + 23

@ray.remote(num_cpus=1, max_calls=1)
def do_add():
    time.sleep(sleep_seconds)
    return ray.get(nested.remote()) + 119

for _ in range(3):
    print(ray.get(do_something.remote()))
    print(ray.get(do_add.remote()))
```

**Comment by acdifran** [comment]
@rkooo567 The above code snippet that you tried is the one that works by using the nested call. The code that fails is in the first block I posted. I've edited that comment to make that more clear. I also tested to make sure the same issues occurs on the nightly build. Just to reiterate, here is the code that causes the issue:

```python
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for _ in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
```

This causes my gpu resources to be held up as I described in my previous comment. Also, I can run that code without using gpus at all and while it does run, I'm left with 6 IDLE workers (one for each task) that are consuming RAM.

```python
import ray
import time

ray.init(num_cpus=2)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for _ in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
```

![Screen Shot 2020-09-17 at 12 52 26 PM](https://user-images.githubusercontent.com/25591626/93521257-a99b9880-f8e4-11ea-9fd9-c9f486f1027d.png)

**Comment by rkooo567** [comment]
The second issue will be resolved soon (we are implementing multi-tenancy of Ray, and IDLE workers will be all killed when the job is done). Unfortunately, I couldn't reproduce the first issue from the nightly Ray. Can you check

1. If you can still reproduce the same issue for the first script when you run it in non-gpu node. 
2. Run it with nightly and see if the issue still occurs.

**Comment by acdifran** [comment]
@rkooo567 

For the first issue, when I run that script using the nightly build, while the dashboard shows that GPUs are not being held, it seems they actually still are. Below is the exact code I just tried using the nightly build:

```python
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for i in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
    print(i, ray.available_resources())
```

After the loop runs twice I get this output:

```
2020-09-22 19:16:42,158	INFO resource_spec.py:234 -- Available RAM
2020-09-22 19:16:42,159	INFO resource_spec.py:235 -- Workers: 35.69 GiB
2020-09-22 19:16:42,159	INFO resource_spec.py:236 -- Objects: 17.87 GiB
2020-09-22 19:16:42,159	INFO resource_spec.py:238 -- To adjust these values, use
2020-09-22 19:16:42,159	INFO resource_spec.py:243 --   ray.init(memory=<bytes>, object_store_memory=<bytes>)
2020-09-22 19:16:42,639	INFO services.py:1172 -- Dashboard URL: http://127.0.0.1:8266
1000000
31
0 {'GPU': 0.5, 'node:10.15.161.9': 1.0, 'memory': 731.0, 'accelerator_type:K80': 1.0, 'CPU': 2.0, 'object_store_memory': 252.0}
1000000
31
1 {'CPU': 2.0, 'memory': 731.0, 'object_store_memory': 252.0, 'accelerator_type:K80': 1.0, 'node:10.15.161.9': 1.0}
```

From this, it shows that after the first 4 processes run (each using 0.25 GPUs) there are no GPU resources left even though the dashboard no longer shows the IDLE tasks as using any GPUs.

![Screen Shot 2020-09-22 at 12 15 37 PM](https://user-images.githubusercontent.com/25591626/93927966-75521e80-fcce-11ea-93e4-15599ee7e3a9.png)

**Comment by rkooo567** [comment]
It looks like there's something wrong when you have implicit capture of object reference (`X_id` for example) to remote tasks. Not sure if it is the expected behavior, or a bug. cc @stephanie-wang 

The workaround is just to pass `X_id` instead of having implicit capture and call `ray.get(X_id)` in your task. I will investigate the issue, but the best solution now is to go with the solution below.

Try this;

```
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

# When the object ref is passed to tasks, it is automatically `ray.get`ed.
@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_thing(X_id):
    time.sleep(sleep_seconds)
    return len(X_id))

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_sum(int_ref):
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for i in range(3):
    print(ray.get(do_thing.remote(X_id)))
    print(ray.get(do_sum.remote(int_ref)))
    print(i, ray.available_resources())
```

**Comment by rkooo567** [comment]
Close since there's already another issue reported, and there's a workaround solution proposed.
