### ISSUE TITLE
[rllib] Invalid input/output signatures in tf.saved_model from TFPolicy.export_model

### ISSUE THREAD

**Issue by neigh80** [ray-project/ray#10733]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
* Ray 0.8.7
* TensorFlow 2.1.1

I'd like to create ```tf.saved_model``` using a rllib checkpoint. ```TFPolicy.export_model``` works fine, but some input/output signatures are represented like ```default_policy/Placeholder:0```. These signatures are used for input/output to manage LSTM states. Since calling ```tf.saved_model``` with positional arguments is not allowed, it is impossible to use this ```tf.saved_model```.

#### Script

```python
import ray
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.examples.env.stateless_cartpole import StatelessCartPole

config = {
    'num_gpus': 1,
    "env": StatelessCartPole,
    "model": {
        "use_lstm": True,
        "lstm_use_prev_action_reward": False,
    },
    "framework": "tf",
}

ray.init()
agent = PPOTrainer(config)
agent.restore(CARTPOLE_LSTM_CHECKPOINT_PATH)
policy = agent.workers.local_worker().policy_map['default_policy']
policy.export_model(TF_SAVED_MODEL_PATH)

import tensorflow as tf
m = tf.saved_model.load(TF_SAVED_MODEL_PATH).signatures['serving_default']
print(f'tf.saved_model: {m}')
print(f'structured_outputs: {m.structured_outputs}')
```

#### Output
```
...
2020-09-11 16:32:49,464	INFO trainable.py:473 -- Restored on 192.168.50.11 from checkpoint: /home/neigh/ray_results/PPO/PPO_StatelessCartPole_0_2020-09-11_15-20-57k2x73u83/checkpoint_1/checkpoint-1
2020-09-11 16:32:49,464	INFO trainable.py:480 -- Current state after restoring: {'_iteration': 1, '_timesteps_total': None, '_time_total': 4.88869309425354, '_episodes_total': 176}
...
tf.saved_model: <ConcreteFunction pruned(prev_action, is_training, observations, prev_reward, default_policy/Placeholder:0, default_policy/Placeholder_1:0, seq_lens) at 0x7FD9E409CE10>
structured_outputs: {'action_prob': <tf.Tensor 'default_policy/Exp:0' shape=(?,) dtype=float32>, 'default_policy/functional_3/lstm/while/Exit_4:0': <tf.Tensor 'default_policy/functional_3/lstm/while/Exit_4:0' shape=(?, 256) dtype=float32>, 'vf_preds': <tf.Tensor 'default_policy/Reshape_2:0' shape=(?,) dtype=float32>, 'action_logp': <tf.Tensor 'default_policy/cond_1/Merge:0' shape=(?,) dtype=float32>, 'actions_0': <tf.Tensor 'default_policy/cond/Merge:0' shape=(?,) dtype=int64>, 'action_dist_inputs': <tf.Tensor 'default_policy/Reshape_1:0' shape=(?, 2) dtype=float32>, 'default_policy/functional_3/lstm/while/Exit_3:0': <tf.Tensor 'default_policy/functional_3/lstm/while/Exit_3:0' shape=(?, 256) dtype=float32>}
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ivallesp** [comment]
Same problem here... Any workaround?

**Comment by ivallesp** [comment]
@ericl is there any hacky way of exporting the model and having a different name for that placeholder so that I can use it?

If I manage to do that, what should I pass as arguments for default_policy/Placeholder:0, default_policy/Placeholder_1:0?

**Comment by ivallesp** [comment]
Ok, answering myself... For those getting blocked by this issue, a workaround would be:

```
    placeholders = {
        "is_training": foo1,
        "observations":foo2,
        "prev_action": foo3,
        "prev_reward": foo4,
        "seq_lens": foo5,
        "default_policy/Placeholder:0": foo6,
        "default_policy/Placeholder_1:0": foo7,
    }

    outputs = MODEL(**placeholders)
```

**Comment by KiloNovemberDelta** [comment]
Hello everyone,
Even if this issue is quit old, I write here because it seems to be still open. For my case, I succeed to import a model without LSTM. But with the config "use_lstm : True", I face the same problem. 

> 
> 
> Ok, answering myself... For those getting blocked by this issue, a workaround would be:
> 
> ```
>     placeholders = {
>         "is_training": foo1,
>         "observations":foo2,
>         "prev_action": foo3,
>         "prev_reward": foo4,
>         "seq_lens": foo5,
>         "default_policy/Placeholder:0": foo6,
>         "default_policy/Placeholder_1:0": foo7,
>     }
> 
>     outputs = MODEL(**placeholders)
> ```

This code helped me, however I don't know what to write for the Placeholder:0 and Placeholder_1:0 (foo6 and foo7). The structure output provide this information : 
`[<tf.Tensor 'policy_agent/Placeholder:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'policy_agent/Placeholder_1:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'policy_agent/Placeholder_2:0' shape=(?, 2) dtype=int64>, <tf.Tensor 'policy_agent/is_training:0' shape=() dtype=bool>, ... ]`
I tried something like : 
`foo6 = foo7 = tf.convert_to_tensor(np.asarray([np.zeros([256], np.float32) for _ in range(1)]), np.float32)`
But I get this type of error : 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError:   Max scatter index must be < array size (19 vs. 1)
	 [[{{node policy_agent/model_1/lstm/TensorArrayUnstack_1/TensorArrayScatter/TensorArrayScatterV3}}]]
	 [[StatefulPartitionedCall_1]]
```
Have you found any solution?
