### ISSUE TITLE
[java] Java usage is shown when importing from Python

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#10747]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
master

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
I get shown:
<img width="505" alt="Screen Shot 2020-09-11 at 12 50 54 PM" src="https://user-images.githubusercontent.com/4529381/92967051-701ee500-f42d-11ea-877c-c6ddc3fde1ef.png">

when calling `ray.init()`. The Python library should have no dependency on Java.

**Comment by barakmich** [comment]
That was easy to find:

```
git diff origin/releases/0.8.7..origin/master python/ray/services.py
```

I betcha dollars to donuts its afa0216280409ff9806640658605e24b64d81ea7, specifically https://github.com/ray-project/ray/commit/afa0216280409ff9806640658605e24b64d81ea7#diff-54ac27010a06993004bec4677c7e583eR1329-R1332
