### ISSUE TITLE
Prototype allowing actor handles to be passed to tasks.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1075]
- Clarify what the API should be
- Clarify what the consistency and fault-tolerance model is
- Clarify interaction with checkpointing

cc @stephanie-wang

**Comment by imzhenyu** [comment]
bookmark this for further comments :-)

**Comment by robertnishihara** [comment]
Prototyped in #1137. Still very experimental.

**Comment by danielsuo** [comment]
@mihaic seems like this functionality now exists in early form and we can check it out

**Comment by robertnishihara** [comment]
Yes, let us know if you have feedback on the API or other aspects. I've run into some performance issues (see #1149), but that should be addressable.
