### ISSUE TITLE
Ray is only using a single CPU core

### ISSUE THREAD

**Issue by n-gao** [ray-project/ray#10755]
### What is the problem?
I use ray to train using multiple GPUs with PyTorch though all processes only utilize a single core which impedes the GPU efficiency a lot (only about 20-30%).
Ray: 0.8.7
Python: 3.7.7
PyTorch: 1.5.1
![image](https://user-images.githubusercontent.com/9084670/92990041-02c88e00-f4d9-11ea-922d-a68cec8e10eb.png)

**Comment by amogkam** [comment]
@n-gao Could you please share your train.py script? It’ll help us diagnose what’s going on.

**Comment by richardliaw** [comment]
Also, is it possible that your Pytorch is installed via conda? Or to check whether there are settings for KMP/OMP threads pinning everything to 1 core?

**Comment by n-gao** [comment]
I installed PyTorch via pip. 
Due to copyright etc. I sadly can not share my training script. I will see whether I can produce another example.
Also, I tested this on two completely different GPU clusters and it happens in both.

**Comment by richardliaw** [comment]
is `CUDA_VISIBLE_DEVICES` set somewhere?

**Comment by n-gao** [comment]
The processes are properly distributed to the GPUs, but they only use a single core. Here is a simple example:
```python
import ray
import torch
import tqdm


@ray.remote(num_gpus=0.5)
class Actor():
    def __init__(self) -> None:
        torch.set_default_tensor_type('torch.cuda.FloatTensor')
        self.network = torch.nn.Sequential(
            torch.nn.Linear(1024, 2048),
            torch.nn.Sigmoid(),
            torch.nn.Linear(2048, 2048),
            torch.nn.Sigmoid(),
            torch.nn.Linear(2048, 2048),
            torch.nn.Sigmoid(),
            torch.nn.Linear(2048, 2048),
            torch.nn.Sigmoid(),
            torch.nn.Linear(2048, 2048),
            torch.nn.Sigmoid(),
            torch.nn.Linear(2048, 10)
        )

    def compute(self) -> torch.Tensor:
        inp = torch.randn(1000, 1024)
        return self.network(inp).detach().cpu()


if __name__ == '__main__':
    ray.init()
    actors = [Actor.remote() for _ in range(8)]
    for _ in tqdm.trange(10000):
        ray.get([a.compute.remote() for a in actors])
``` 
Nvidia-smi:
```+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:61:00.0 Off |                    0 |
| N/A   33C    P0    61W / 300W |   2457MiB / 16160MiB |     18%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:62:00.0 Off |                    0 |
| N/A   32C    P0   123W / 300W |   2457MiB / 16160MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   32C    P0    64W / 300W |   2457MiB / 16160MiB |     18%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   34C    P0   106W / 300W |   2457MiB / 16160MiB |     18%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     19167      C   ray::Actor                                  1223MiB |
|    0     19168      C   ray::Actor                                  1223MiB |
|    1     19164      C   ray::Actor                                  1223MiB |
|    1     19165      C   ray::Actor                                  1223MiB |
|    2     19162      C   ray::Actor                                  1223MiB |
|    2     19163      C   ray::Actor                                  1223MiB |
|    3     19160      C   ray::Actor                                  1223MiB |
|    3     19161      C   ray::Actor                                  1223MiB |
+-----------------------------------------------------------------------------+
```
Htop:
![image](https://user-images.githubusercontent.com/9084670/92991883-e3386200-f4e6-11ea-9b9d-2c7e397c2ab5.png)

**Comment by richardliaw** [comment]
That’s concerning - can you check if theres any explicit process affinity (
https://unix.stackexchange.com/questions/425065/linux-how-to-know-which-processes-are-pinned-to-which-core)
within the initialization of each actor?

Also can you check to unset any OMP and KMP environment variables?

Let me know it this leads to anything!

**Comment by n-gao** [comment]
```
pid 20036's current affinity list: 0
pid 20039's current affinity list: 0
pid 20044's current affinity list: 0
pid 20048's current affinity list: 0
pid 20049's current affinity list: 0
pid 20062's current affinity list: 0
pid 20063's current affinity list: 0
pid 20064's current affinity list: 0
pid 20065's current affinity list: 0
pid 20066's current affinity list: 0
```
These are the affinities for the ray processes. What OMP and KMP environment variables (sorry I am unfamiliar with these)?

**Comment by richardliaw** [comment]
Hey @n-gao, 

Thanks a bunch for that output. It seems like the affinity list is not ideal (everything is being pinned to core 0). Ray doesn't manage CPU affinity, so this seems like a problem with an underlying library or environment.

You can read about OMP/KMP variables here: https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/thread-affinity-interface-linux-and-windows.html

I think we are very close. To further diagnose your issue, right after `ray.init`, can you do something like:

```
def check_envs():
	print("scan..")
	for ev in os.environ:
	    if "KMP" in ev:
	        print(ev, os.environ[ev])
	    if "OMP" in ev:
	        print(ev, os.environ[ev])
	print(".. finished scan")

ray.init()
check_envs()
```

and provide the output? This will help me identify whether there is an automatic setting of the environment variables.

Also, if you could execute `check_envs()` in the initializer of the Actor class, that'd be also helpful too.

**Comment by n-gao** [comment]
Main thread:
```
scan..
CONDA_PROMPT_MODIFIER (base)
PROMPT_COMMAND history -a; history -c; history -r;
OMP_NUM_THREADS 1
.. finished scan
```
Every actor has the same environment variables (why is there no `CUDA_VISIBLE_DEVICES` set?):
```
(pid=15565) scan..
(pid=15565) CONDA_PROMPT_MODIFIER (base)
(pid=15565) PROMPT_COMMAND history -a; history -c; history -r;
(pid=15565) OMP_NUM_THREADS 1
(pid=15565) .. finished scan
```

**Comment by n-gao** [comment]
I found the issue on my system, the compute node was attributed to me by `slurm` and without specifying the number of cpu cores, slurm forces all processes to a single core. I could reproduce the same issue with `multiprocessing`, so this is completely `ray` unrelated. Sorry for the confusion and thank you for your time!

**Comment by richardliaw** [comment]
Awesome! That's a good catch - should we add it to the docs?

Also, be sure to do `ModelActorClass = ray.remote(num_gpus=1)(ModelClass)` <= to use CUDA VISIBLE DEVICES.

**Comment by n-gao** [comment]
FYI, this is not solely `Slurm` specifiy, it seems that `PBS` does the same (has the same issue on a `PBS` cluster).

**Comment by sheecegardezi** [comment]
@n-gao I am having the same issue on PBS cluster. How did you resolved this issue?

**Comment by n-gao** [comment]
I don't remember the exact code snippet but you simply have to request more cores.

**Comment by sheecegardezi** [comment]
Thanks for the hint Ill experiment with it :)

**Comment by sheecegardezi** [comment]
I am using this machine:

normalbw
Normal priority queue for standard computational intensive jobs on the Broadwell nodes
2 x 14-core Intel Xeon E5-2690v4 (Broadwell) 2.6GHz CPUs per node
128 or 256GB RAM per node
2 CPU sockets per node, each with 1 NUMA node
14 CPU cores per numa NODE
64 or 128 GB local RAM per NUMA node
400GB local SSD disk
https://opus.nci.org.au/display/Help/Queue+Structure

Ray just recognizes half the cpus 

ray start --head --num-cpus=56

It does not matter how much i increase num-cpus dashboard just shows 56 cores, no matter what parallel task I run CPU load is limited to 50%.
