### ISSUE TITLE
[autoscaler] Usability regressions in new autoscaler output

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#10763]
@richardliaw we've regressed the output here, it's a minor issue but super annoying.

```
Useful commands
  Monitor autoscaling with
    ray exec example-ml.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
  Connect to a terminal on the cluster head
    ray attach example-ml.yaml
```

It used to print the absolute path of the yaml, so you can copy paste into any terminal. Now, the user has to navigate to the directory YAML for the command to work.

**Comment by ericl** [comment]
Also, didn't we used to print the raw SSH command if you want to a direct shell? If we don't print that, then users will have a hard time figuring out how to get direct access if they want more custom command execution.

**Comment by richardliaw** [comment]
The first issue is fixed on master - https://github.com/ray-project/ray/commit/401195d9359b4d6641776f43706bc3ced414819e#diff-4fd45cbce68a36f9e4f5a688ac099228

**Comment by richardliaw** [comment]
If not please provide repro:
```

Useful commands
  Monitor autoscaling with
    ray exec /Users/rliaw/dev/cfgs/anyscale.yaml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'
  Connect to a terminal on the cluster head
    ray attach /Users/rliaw/dev/cfgs/anyscale.yaml

```

**Comment by ericl** [comment]
Thanks!

**Comment by ericl** [comment]
Actually, how about the raw SSH command?

**Comment by richardliaw** [comment]
the raw ssh command is not yet

**Comment by ericl** [comment]
Hm, maybe it was that when you run "ray attach etc.", it used to print the raw SSH command being executed. Can we ensure this is printed out so the commands aren't so "magic"?

**Comment by richardliaw** [comment]
Yeah - I'll add a line.

**Comment by richardliaw** [comment]
see #10767
