### ISSUE TITLE
[tune] Trainable leaks GPUtil monitor thread

### ISSUE THREAD

**Issue by Antymon** [ray-project/ray#10769]
### What is the problem?

Repeated creation-destruction of a PPO trainable results in exponential computation growth of each step of such a loop.

I have used such a loop in tests. With enough cases, exponential growth was able to bring down any server.

The problem seems related to the use of `GPutil` in conjunction with `rllib`. See the attachment below.

Perhaps this makes it more related to `tune`, feel free to change the title prefix.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray `0.8.7`
Python `3.6.9`
TF `2.2.0+nv`
Ubuntu `18.04`

### Reproduction (REQUIRED)

Download and unzip:
[bug_exp_time_growth.zip](https://github.com/ray-project/ray/files/5217040/bug_exp_time_growth.zip)

```
docker build -t bug_exp_time_growth .
docker run -p 8265:8265 -it bug_exp_time_growth bash
python trainable_creation_loop.py
```
Calling `python trainable_creation_loop.py` within will demonstrate the problem outputting time measurements to both stdout and a logfile. 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
What kind of times are you seeing? I'm still seeing <4 seconds at 50 iterations. I did move the ray.init() out of the main loop though, since that was slowing things down quite a lot.

This is ray==1.0.0rc0 btw.

**Comment by ericl** [comment]
Ah, I see this is gputil related. I'm guessing it's since we never kill this thread here: https://github.com/ray-project/ray/blob/09d4a3241ff872866e6c0573abe24305ab8deeab/python/ray/tune/trainable.py#L258

cc @richardliaw can that thread be a process-global singleton or otherwise stopped?

**Comment by richardliaw** [comment]
ah yeah, it can be process global.

**Comment by Antymon** [comment]
@ericl All good? Can repro?

**Comment by richardliaw** [comment]
@Antymon can you try this PR: https://github.com/ray-project/ray/pull/10947
