### ISSUE TITLE
[rllib] [tune] Running multiple trainers in parallel

### ISSUE THREAD

**Issue by ericzhao28** [ray-project/ray#10770]
### What is your question?
In the rllib example where two trainers are used for multiagent learning, both a ppotrainer and dqntrainer are called at each iteration. The current flow is sequential and synchronous, like this:
```
Repeat n times:
     dqn_trainer.train()
     ppo_trainer.train()
```
Is there anyway to run these two .train() calls asynchronously so they run in parallel? I couldn’t find anything in the Tune documentation regarding how to run trainables asynchronously either.

**Comment by ericl** [comment]
Great question. To do that, you'll actually need to build a hybrid trainer that composes the two workflows so they can run concurrently. There's an example here of that: https://github.com/ray-project/ray/blob/master/rllib/examples/two_trainer_workflow.py

**Comment by ericzhao28** [comment]
Is there a way to do this without merging them into a single trainer? In the example, the two trainers train disjoint sets of policies (the dqn trainer updates the dqn policies, the ppo trainer updates the ppo policies). In our use-case, each of the two trainers is used to train all agents---I periodically average the policy weights between the trainers. I'm not sure if that is possible in a single trainer.

Generally speaking, the trainer is just a Tune trainable right? I was hoping there was a way to call Trainable.train() without blocking so I can step through multiple Trainables simultaneously.

**Comment by ericl** [comment]
I see, you should be able to create those trainers as remote actors. For example
```
RemoteDQN = ray.remote(num_gpus=1)(DQNTrainer)
RemotePPO = ray.remote(num_gpus=1)(PPOTrainer)

dqn = RemoteDQN.remote(config=..., ...)
ppo = RemotePPO.remote(config=..., ...)

while True:
  fut1 = dqn.train.remote()
  fut2 = ppo.train.remote()
  ray.get([fut1, fut2])
```

**Comment by ericzhao28** [comment]
Thanks @ericl. Is it necessary to move the trainers into a remote worker? I tried the snippet below and it seems to be ok (as in doesn't immediately crash):
```
    from multiprocessing.dummy import Pool as ThreadPool
    def train_all(trainer):
          return trainer.train()
    pool = ThreadPool(len(trainers))
    while True:
          results = pool.map(train_all, trainers)
```
Does the use of multithreading on Ray introduce some bad side effect that I'm missing (I recall Ray being threadsafe)?

**Comment by ericl** [comment]
I think that should work as well. It might be a bit slower due to GIL contention though.

**Comment by ericzhao28** [comment]
Do the trainers actually do a significant amount of work locally? I was under the impression that evaluation rollouts and policy updates occurred in remote workers (called by the Trainers) which shouldn't be affected by any GIL contention. Is there some non-trivial local computation being done by the trainers?

**Comment by ericl** [comment]
Yeah, the gathering of results and learn() step occur locally typically. Though, these are calls into TF/Torch and would release the GIL, but you might see some contention concatenating data and such.
