### ISSUE TITLE
[docker] Support non-root container

### ISSUE THREAD

**Issue by Leemoonsoo** [ray-project/ray#10786]
### Describe your feature request

The Docker image created by `build-docker.sh` requires the root user to run.
Support non-root container is important to have better security. see

  - https://docs.docker.com/engine/security/security/
  - https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html

Currently, docker image installs python conda environment and libraries under `/root` directory, which non-root user doesn't have permission. Also, [some source code](https://github.com/ray-project/ray/blob/ray-0.8.7/python/ray/autoscaler/command_runner.py#L167) creates files under `/root` directory.

How about create a non-root user 'ray' in the docker image and use `/home/ray` for python conda environment under as well as file upload target directory?

**Comment by rkooo567** [comment]
cc @ijrsvt

**Comment by simon-mo** [comment]
Please feel free to contribute!

**Comment by Leemoonsoo** [comment]
Okay, let me prepare a pull request.

**Comment by ijrsvt** [comment]
#11407 introduced this change! The default user is `ray`!!
