### ISSUE TITLE
[rllib] Create rllib API for learning from offline data

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1080]
There are a lot of situations where you have tons and tons of offline data and you want to learn a policy from this, but you don't actually have a simulator for doing on-policy learning. Q learning and similar approaches are a natural fit in this setting, and it'd be nice for RLlib to support this out of the box (e.g., instead of providing agents that take an environment and output a policy, provide agents that take a dataset and output a policy).

cc @ericl @richardliaw @pcmoritz

**Comment by ericl** [comment]
Fixed by serving env (though we need to add docs).

**Comment by NarasimhaM3101** [comment]
Can you please clarify how to use offline datasets with DDPG and other examples?

**Comment by ericl** [comment]
You can find documentation and examples here: https://ray.readthedocs.io/en/latest/rllib-offline.html

**Comment by GoingMyWay** [comment]
> You can find documentation and examples here: https://ray.readthedocs.io/en/latest/rllib-offline.html

Hi, do you have a purely working code where a policy only learns from the offline data? I think many real-world problems need learning from offline data because building a simulator is expensive or impossible.

**Comment by felipeeeantunes** [comment]
@robertnishihara, I asked a question that would improve the documentation with suggestions on retraining your agent using this offline setup. Let me know your thoughts about the possibilities listed there.
https://discuss.ray.io/t/correct-approach-to-improve-retrain-an-offiline-model/125
