### ISSUE TITLE
[autoscaler] Support min_workers for multi node type

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#10814]
### Describe your feature request

Currently, you cannot request a static set of mixed node types in the autoscaler; it can only respond dynamically to load. It would be nice to be able to support this feature.

**Comment by wuisawesome** [comment]
What's the use case for this/should we also support `initial_workers`?

**Comment by ericl** [comment]
If you know ahead of time that you need say 3 GPU nodes and 2 CPU nodes, it allows the user to predefine that, instead of waiting for the autoscaler (saves time / easier to reason about).

I don't think we need initial_workers, tbh not sure if initial_workers is that useful now that we have other APIs such as request_resources() , maybe we should remove that in the future.

**Comment by ericl** [comment]
@AmeerHajAli this should be a nice starter task you might want to look at before https://github.com/ray-project/ray/issues/9800 cc @wuisawesome
