### ISSUE TITLE
[rllib] How to train beyond 2^31 timesteps?

### ISSUE THREAD

**Issue by jrtcppv** [ray-project/ray#10810]
I am using ray 0.8.5. I would like to continue training beyond 2 billion timesteps but am hitting an error related to the timesteps variable being of type `np.int32`. Is there a way to force the model to use `np.int64` without forking ray? Specifically I am using a `RecurrentTFModelV2` with APPO.

**Comment by ericl** [comment]
Hmm I think this is a bug we'd have to fix. Probably the tensor is defined as int32 somewhere? cc @sven1977

**Comment by sven1977** [comment]
Yeah, could be one of the timestep tensors used mainly for exploration that overflows. Taking a look. ...

**Comment by sven1977** [comment]
This PR fixes the problem:

https://github.com/ray-project/ray/pull/11301

There is also a test case now confirming good ts counting behavior by the different policies (`ray/rllib/tests/test_timesteps.py`).

**Comment by sven1977** [comment]
@jrtcppv

**Comment by sven1977** [comment]
Thanks for filing this issue! :)

**Comment by jrtcppv** [comment]
No problem, thank you for taking care of it and for all the work you do on this excellent library!
