### ISSUE TITLE
[tune] How to test if I'm running inside a tune session?

### ISSUE THREAD

**Issue by mi-lad** [ray-project/ray#10839]
Is there an API to test if I'm running inside a tune session? I'd like to conditionally call `tune.report()` in my code.

There are functions like `get_trial_dir`, `get_trial_name`, `get_trial_id`, that internally call `get_session()`. I guess I could use one of them see if they return `None` or not. But they also log a warning when they can't find a session which is not ideal.

**Comment by mi-lad** [comment]
Something like below works but I hope there's an official API for this?

```
def inside_tune():
    return ray.tune.session._session is None
```

**Comment by richardliaw** [comment]
Hey @mi-lad just pushed a fix in #10840 does that work for you?

**Comment by richardliaw** [comment]
Thanks a bunch for opening this issue BTW!

**Comment by mi-lad** [comment]
Thanks for the quick reply @richardliaw . Left some comments in #10840 .

**Comment by JustasB** [comment]
Since this issue ranks highly on google, the change above makes it so that one can check if inside a tune session with:

```
import ray
if ray.tune.is_session_enabled():
   # do ray stuff
```

**Comment by JustasB** [comment]
Per https://github.com/ray-project/ray/issues/44258#issuecomment-2028469091

`ray.tune.is_session_enabled()` is deprecated
^^ uses 
`ray.train._internal.session._get_session()` as an alternative -- not ideal though

**Comment by Petros626** [comment]
@JustasB could it be the case, that even `_get_session` is depreceated?

![Image](https://github.com/user-attachments/assets/9cff78c6-05c4-4c2d-b334-d06a0e4b30a0)
