### ISSUE TITLE
[rllib] Change RL agent classes to take function that creates env.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1083]
Currently the RL agent constructions take in a string with the name of the environment to train in, e.g.,

```python
env_name = 'Pong-v0'
agent = PPOAgent(env_name, DEFAULT_CONFIG)
```

The agent constructor then creates the environment by calling `gym.make('Pong-v0')`.

Following the discussion in https://groups.google.com/forum/#!topic/ray-dev/r4YrZXdCfw0, we should probably modify the API to be the following.

```python
def env_creator():
    return gym.make('Pong-v0')

agent = PPOAgent(env_creator, DEFAULT_CONFIG)
```

**Comment by ericl** [comment]
https://github.com/ray-project/ray/pull/1096
