### ISSUE TITLE
version flyout menu is hidden by table of contents rightbar in docs

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10841]
### What is the problem?

1. go to a doc page with many entries in the table of contents
2. click the version flyout menu in the bottom right corner

only on master, due to the theme change

screen share: https://gofile.io/d/hBMQtz (.mov, <10 s)

I haven't tried fixing this yet; it might be as simple as raising the version menu's z-index, or we might need to move the version menu back to the bottom left corner

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
Yeah I just ran into this... 

cc @simon-mo

**Comment by simon-mo** [comment]
Actually, @sumanthratna would you mind open a PR to push a quick fix? You can edit our custom css file here https://github.com/ray-project/ray/blob/master/doc/source/_static/css/custom.css

**Comment by richardliaw** [comment]
I just did it

**Comment by richardliaw** [comment]
<img width="601" alt="Screen Shot 2020-09-16 at 4 18 13 PM" src="https://user-images.githubusercontent.com/4529381/93401908-39cfd400-f838-11ea-9e37-8ec504dcba6f.png">
seems to work with zindex-1200, though not sure if that's the right fix. See #10843

**Comment by sumanthratna** [comment]
looks like the issue hasn't been resolved but the [custom CSS](https://docs.ray.io/en/master/_static/css/custom.css) file has been updated. `!important` will probably do the job but hopefully, there's a better solution. regardless, I'm pushing a PR with the important rule as a hotfix
