### ISSUE TITLE
ray.exceptions.RayTimeoutError: There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.

### ISSUE THREAD

**Issue by kocic11** [ray-project/ray#10842]
### What is the problem?
Running multiple processes in parallel connected to the same ray cluster fails with the same error when trying to create an actor.
````
Traceback (most recent call last):
  File "/opt/anaconda3/envs/VPPy/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/VPPy/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/sailgp/vppy/tests/Pytest/run.py", line 9, in run
    SomeClass.remote()
  File "/opt/anaconda3/envs/VPPy/lib/python3.7/site-packages/ray/actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/opt/anaconda3/envs/VPPy/lib/python3.7/site-packages/ray/actor.py", line 586, in _remote
    extension_data=str(actor_method_cpu))
  File "python/ray/_raylet.pyx", line 930, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 938, in ray._raylet.CoreWorker.create_actor
  File "python/ray/_raylet.pyx", line 147, in ray._raylet.check_status
ray.exceptions.RayTimeoutError: There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.
````
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.7
Python 3.7.7
Linux RH 7

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
````
import ray
import multiprocessing

@ray.remote
class SomeClass():
    pass

def run():
    SomeClass.remote()
    print('End')

if __name__ == '__main__':
    print('Start')
    ray.init()

    for i in range(5):
        job = multiprocessing.Process(target=run)
        job.start()
````
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @ericl I could reproduce this error. I will try to troubleshoot by today and decide if it is release blocker.

**Comment by ericl** [comment]
I think the issue is multiprocessing, that's not allowed to be used with ray. You might try ray.util.multiprocessing instead

**Comment by kocic11** [comment]
Can you elaborate a bit, what exactly is not allowed? It seems to me that I am creating 5 clients which should be a pretty common case.

**Comment by rkooo567** [comment]
Forking Ray drivers (script with ray.init) is not allowed (I assumes it somehow corrupts states of our drivers). Consider using `ray.util.multiprocessing` or just run 5 drivers instead.

**Comment by kocic11** [comment]
Thanks,

How do I run 5 drivers?

**Comment by rkooo567** [comment]
Just run scripts 5 times, or you can use `subprocess` module in one of your scripts.

**Comment by kocic11** [comment]
Thanks, 

Are there any issues using multithreading? The script above works just fine with Thread instead of Process.

**Comment by rkooo567** [comment]
As far as I know, multi threading would be fine, but I am not 100% sure about it.
