### ISSUE TITLE
[tune] ObjectStoreFullError:Failed to put object into object store

### ISSUE THREAD

**Issue by noprohuangqi** [ray-project/ray#10852]
#10792 # What is the problem?
ObjectStoreFullError:Failed to put object into object store

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray:0.8.6
Ubuntu:18.04
python:3.7

### Reproduction (REQUIRED)
Sorry , my script has so many dependencies.But the bug is easy to describe. 
When I try to use PBT to train my models , I found the 8 trails occupy more and more memory.And finally,raise memory error.
I think the reason is the 'tempfile' package make many checkpoints in memory .For example , in 40 epoch ,maybe a trail have made 40 checkpoints in tempfile , so the memory crash.
I can not confirm what caused this error , thanks for your any help.
![image](https://user-images.githubusercontent.com/35948614/93435146-9647f780-f8fb-11ea-8507-63dbf6837d72.png)

and my 'ray memory' as :(first page of 2 pages)
![image](https://user-images.githubusercontent.com/35948614/93442165-87b10e80-f902-11ea-92d1-5fe813ef78d7.png)

**Comment by amogkam** [comment]
@noprohuangqi this is the same as https://github.com/ray-project/ray/issues/10890 right? I'm going to close this, but if it's a different problem feel free to reopen.
