### ISSUE TITLE
[tune] New feature: callback support for Tune

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#10854]
### Describe your feature request

Callbacks are a very useful addition to tuning libraries, allowing to eg. measure progress of long tuning processes. Adding the possibility to use them in Ray Tune, with, for example:

```python
tune.run(
	callbacks=[func, func2]
)
```

would be very helpful and bring it in line with other hyperparameter tuning libraries like Optuna.

**Comment by Yard1** [comment]
@richardliaw

**Comment by richardliaw** [comment]
cc @ray-project/ray-tune

**Comment by krfricke** [comment]
Hi @Yard1, thanks for the issue. We're looking into supporting callbacks very soon. The main question I have is that there a many possibilities to inject callbacks. It would be great if you could provide some insight into your use case so we can make sure that we cover it with our implementation.

For instance, callbacks could be called every time when a result is received from a trial, i.e. after calling `tune.report()`. The callback would then receive the reference to the trial, and then has access to the last result and other properties. Would this be useful for you, or do you need callback support at other places or with other data?

Another possibility would be to support callbacks on the outer training loop of the trial runner, i.e. before and after trial events for all trials are executed. 

 It would be great to learn what you are trying to achieve with the callbacks. Thanks!

**Comment by Yard1** [comment]
For me, the most important thing is being able to measure progress. I would like to be able to tell how many trials have been completed out of total use that information by eg. incrementing a counter in a progress bar. I think that the simplest way would be to have a callback at the end of a trial, so after `tune.report()` sounds like something I want.

I imagine that some people would want callbacks before a trial starts, to eg. log parameters, but this isn't something I need myself.

**Comment by krfricke** [comment]
Thanks, that's helpful.

I started implementing a solution for this. The PR can be found here: #11001

There's a small usage example included in the PR description. It would be very helpful if you could take a look and confirm if you could use the callback API to do what you aim to do. If not, please let us know what we could improve here.

Thanks!

**Comment by Yard1** [comment]
This looks like everything I needed and more, @krfricke. Thank you a lot!
