### ISSUE TITLE
link to master version of docs in outputs

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10859]
### Describe your feature request

we often output links to the documentation. sometimes, we link to the latest version but other times, we link to master. e.g.:
https://github.com/ray-project/ray/blob/89da3f9ba7f68c16e7467dc545ed5c9510670400/python/ray/scripts/scripts.py#L1491
https://github.com/ray-project/ray/blob/89da3f9ba7f68c16e7467dc545ed5c9510670400/python/ray/util/joblib/__init__.py#L12

for consistency, we should use links such as `f'https://docs.ray.io/en/releases-{ray.__version__}/installation.html'`. the only downside is that renaming docs pages might break these links, so maybe we should just link to master. 

P3 because this isn't very important IMO

**Comment by richardliaw** [comment]
Linking to master sounds good.
