### ISSUE TITLE
[Dashboard] Add loading bar in memory view.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10863]
### Describe your feature request
It takes some time to load memory view page. In this case, it was confusing me if the memory view was
1. loading the table
2. or just empty.

To avoid this, I think it'll be great to have a rotating wheel or something while it is loading.

**Comment by rkooo567** [comment]
@mfitton 

Bumped up to P1 because I saw users who thought the memory dashboard is not working or buggy because it doesn't show the table right away when they clicked (in reality, it takes some time to load). 

We need two things.

1. Should have a huge loading bar or wheel to indicate it is loading.
2. When there's no result, this should be obvious. We shouldn't just not render anything.

**Comment by mfitton** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/3156716/95936660-1d29ac00-0da4-11eb-9fc5-61c7a5c7bb82.png">

Just wanted to let you know that something like this is already in place. We can swap it to a bar or a wheel if you think that people won't read the text that's there.

**Comment by mfitton** [comment]
(Was trying to take a screenshot of the actual UI but it switches from loading to loaded before I can capture it x.x)

**Comment by rkooo567** [comment]
Yeah I am aware of that (that’s why I set this to P2 initially)! I think the issue is it is not so obvious that it was loading (because the text wasn’t big enough), and there are actual users who didn’t use this view because of that. Having the bar or wheel that is larger sgtm!
