### ISSUE TITLE
[autoscaler] resource_demand_scheduler should take into account queue of tasks

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#10872]
Currently when scheduling tasks (not actors), the core worker will internally queue requests for the same type of resource. This means that, suppose it has queued 100 tasks of num_cpus=1, the autoscaler will only "see" a single task request of num_cpus=1. Hence, it cannot know to upscale more aggressively.

We should convey this information to the autoscaler to improve scheduling. At the same time, for tasks you probably don't want to instantaneously scale up to the max concurrency possible for the tasks, since the tasks may be finishing quickly, so we would want throttling on max number of concurrent node launches.

This is the first pre-req for removing the legacy algorithm (https://github.com/ray-project/ray/issues/10817)

**Comment by ericl** [comment]
fyi @AmeerHajAli

**Comment by ericl** [comment]
We need to enable the feature flag for https://github.com/ray-project/ray/pull/11261 by default before this issue is resolved.

@wuisawesome can you make a PR to flip the flag (and do some manual testing to ensure it works as expected?)

**Comment by wuisawesome** [comment]
@ericl @AmeerHajAli thinking about this now, we need a way of turning this off if it goes badly. We should probably hide the `monitor.py` stuff behind an environment variable for at least 1-2 stable releases just in case.

**Comment by wuisawesome** [comment]
#11615  closed this
