### ISSUE TITLE
ModuleNotFoundError: No module named 'ray.tune'; 'ray' is not a package

### ISSUE THREAD

**Issue by oroojlooy** [ray-project/ray#10875]
### What is the problem?
I get `ModuleNotFoundError: No module named 'ray.tune'; 'ray' is not a package` error once import `ray`. 

```
import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "home/rl/project/ray.py", line 2, in <module>
    import ray.tune as tune
ModuleNotFoundError: No module named 'ray.tune'; 'ray' is not a package

```

*Ray version and other system information (Python version, TensorFlow version, OS):*
I have ray `0.8.7`, pytorch 1.3, and tensorflow 1.13.1, installed on Anaconda python `3.6.8`, and the OS is Red Hat 7.8. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by amogkam** [comment]
It looks like it's trying to import `ray.tune` from your `ray.py` file and not the ray library. I think if you rename your file it should work.

**Comment by oroojlooy** [comment]
It solved the issue!
Thanks.!
