### ISSUE TITLE
Does tune.checkpoint_dir() have to be used a context?

### ISSUE THREAD

**Issue by mil-ad** [ray-project/ray#10870]
All the examples of `tune.checkpoint_dir()` use it as a context manager. As far as I can tell it returns `str` so is there anything special happening in `__exit__` (or the equivalent of exit in `@contextmanager`)? Do I _have to_ use it with `with`?

**Comment by richardliaw** [comment]
You could hypothetically just call with:

```
ctx = tune.checkpoint_dir()
checkpoint_dir = ctx.__enter__()
ctx.__exit__()
```

**Comment by mi-lad** [comment]
I'm assuming this is needed because `__exit__` calls `set_checkpoint()` for the session.

I think the documentation should make it clear that using `tune.checkpoint_dir(step)` without `with` is not ok.

**Comment by richardliaw** [comment]
Yeah, that sounds good. Would you be willing to push a quick fix? Let me know!

**Comment by mi-lad** [comment]
Yup I'll have a go today

**Comment by mi-lad** [comment]
Actually, there's not another thing that's not clear to me from reading the docs. 

There are functionalities that the class-based API provides such as `checkpoint_at_end`, `checkpoint_freq`, and `checkpoint_score_attr`. I'm happy to handle these myself in my own code but I'm not sure whether Tune has expectations about them or not. In particular, if I only want to keep for instance 3 checkpoints, does Tune expect that I always keep the "best" checkpoint? Or is storing the 3 last ones enough?

**Comment by mi-lad** [comment]
Another confusion: [the `tune.run` doc](https://docs.ray.io/en/latest/tune/api_docs/execution.html) mentions `local_checkpoint_dir` but it's not clear to me what that is. I can see a reference to it in `TrialRunner` class but that's supposed to be an internal API and I shouldn't have to know about it.

**Comment by richardliaw** [comment]
```
checkpoint_at_end, checkpoint_freq, and checkpoint_score_attr
```
In general checkpoints are expected to be entirely handled by Tune. Each checkpoint call should be in a new checkpoint subdirectory. If you want to keep 3 checkpoints, I think you will want to set `keep_checkpoint_num`.

Good point about `local_checkpoint_dir` - this should be fixed in master.
