### ISSUE TITLE
Assign different number of actors to different machines

### ISSUE THREAD

**Issue by Jspujol** [ray-project/ray#10887]
Dear Ray community,

I want to use Ray in a small computer cluster that I built, which consists of a powerful CPU machine, 80 cores, and another machine with 20 CPU cores and GPU, both connected in the same LAN network. Basically I am trying to run a deep RL solution on a heavy CPU demanding environment, so I would like to deploy 80 actors (which will gather the state from the environment and query a DNN actor for action and then implement the CPU demanding environment transition) in the powerful CPU machine and 10 actors in the GPU machine, with one actor that will update the DNN (that maps state to actions).

Is there a way to do that? If so how should I do it?

What I have tried so far is to "ray start --head --num-cpus=10" in the GPU node, and then in the powerful CPU machine "ray start --address="ip of the GPU machine" --redis-password=" password seen on GPU machine" --num-cpus=80", but doesn't seem to be working.

Many thanks in advance!

**Comment by jennicetao** [comment]
You may need to declare custom resources on your CPU node, and make your CPU bound tasks to require that. https://rise.cs.berkeley.edu/blog/ray-scheduling/

roughly, 

https://rise.cs.berkeley.edu/blog/ray-scheduling/
ray start --address="ip of the GPU machine" --redis-password=" password seen on GPU machine" --num-cpus=80 --resources '{"cpu_node": 80}'

@ray.remote(num_gpus=1, num_cpus=1)
class GPUActor:

#This won’t be scheduled on gpu nodes
@ray.remote(num_cpus=1, resources={'cpu_node': 1})
Class NonGPUActor:
