### ISSUE TITLE
[RLlib Trajectory View API] Trajectory View API allows easy multi-agent communication channel setup.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#10884]
Multi-agent communication channels (shared models) can be easily setup through the Trajectory View API.
This will require the current ViewRequirement class to be enhanced to allow for cross-agent/cross-policy referencing (i.e. one agent can see some other agents' observations for its forward pass and loss calculations).

**Comment by kiranikram** [comment]
Is this now possible (to set up the MARL communication channel)?
