### ISSUE TITLE
[core] Can the MemoryManager consider swap memory?

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#10895]
Ray is a great tool and especially useful due to its ability to develop locally. However, the MemoryManager will kill Ray if physical memory is full, disregarding swap memory. 

If Ray could consider swap, it would help me avoid OOM issues on less beefy PCs, which seriously speeds up my testing and development cycle.

I took a look at the feasibility of this, and turns out that the change simply amounted to adding `psutil.swap_memory()` to already used `psutil.virtual_memory()`, as well as changing `/sys/fs/cgroup/memory/memory` to `/sys/fs/cgroup/memory/memory.memsw`, which includes swap. 

It would be easy to expose to the user or even via env var. For example: 

```python
ray.init(
	use_swap_memory=False, # False by default
	...
)
```

**This would be a ~10 LOC code change.**

**Would the Ray maintainers be open to accepting a PR for this change?**

**Comment by richardliaw** [comment]
cc @rkooo567 @ericl @wuisawesome  thoughts?

**Comment by ericl** [comment]
If you're talking about the memory_monitor.py, you can disable this by setting RAY_DEBUG_DISABLE_MEMORY_MONITOR=1 to prevent early failing jobs entirely.

The reason we don't want to take into account swap is that for many systems hitting swap basically means your system becomes inoperable. If that happens a strange error (e.g., socket closed) will be raised, and the user won't realize the real error is due to memory.

**Comment by Yard1** [comment]
That is the reason for keeping the parameter False by default. I believe that giving choice to informed users would certainly not hurt, especially given the ease of implementation and maintenance.

**Comment by richardliaw** [comment]
Hmm sounds like `RAY_DEBUG_DISABLE_MEMORY_MONITOR=1` should basically do the same thing right?

**Comment by Yard1** [comment]
It would, though it would be convenient to have the ability to set it from script, and to have the correct memory usage logged.

**Comment by richardliaw** [comment]
Got it; I think you can do `os.environ["RAY_DEBUG_DISABLE_MEMORY_MONITOR"]="1"` for the same effect.

Question @Yard1 , is there a place where the memory usage gets logged?

**Comment by Yard1** [comment]
I'm not logging things just yet, but I am planning to in the future when I move to the next stage of the project. I would like to have accurate memory usage statistics, but if I just set the env variable then I will have none (unless I am mistaken).

**Comment by wuisawesome** [comment]
hmmm @Yard1 would it work to set the `RAY_MEMORY_MONITOR_ERROR_THRESHOLD` to something very high?

**Comment by Yard1** [comment]
@wuisawesome Haven't checked, will do

**Comment by kuihao** [comment]
So can we use swap to prevent oom now?

**Comment by rkooo567** [comment]
I don't think so. cc @clarence-wu for thoughts

**Comment by clarng** [comment]
It is up to your OS configuration on whether to enable swap. Though that is not recommended. When the node overloads it would slow down and stall, and the node would eventually fail if it cannot recover from the memory pressure. We have added a memory monitor to pre-empt worker processes when the memory is low, and that enabled by default since Ray 2.2 - I think we keep this issue closed since the monitor is there to prevent the OOM situation in the first place

**Comment by alvitawa** [comment]
I think the slow down depends on the situation. In my case memory usage is typically 60% (with swap empty) but it can spike to 120% (using swap) for short periods (if the memory-intensive operations of the workers overlap). In addition, I have a very fast SSD for swap space so it is fine to swap heavily AND not all memory is actually being used all the time so a lot of memory can be 'in use' but not actually.

I would still like OOM prevention however in case it reaches 190% (before the OS starts killing processes), which can also happen in very rare situations, and its fine to resolve these by killing one of the workers. If I understand correctly @Yard1 already proposed a working solution. Why not add it?

For context i am running ray tune.

**Comment by rkooo567** [comment]
I think it is already possible with `RAY_DEBUG_DISABLE_MEMORY_MONITOR=1`. I feel a little unituitive having swap_memory in ray.init because ray doesn't (and we don't want to) setup any swap memory. That's the oss level configuration. Maybe we can update a doc.

**Comment by alvitawa** [comment]
What exactly is already possible? From what I understand the flag you provide just disables memory monitoring entirely. This is different from considering swap usage in addition to ram usage.

A command line flag RAY_DEBUG_CONSIDER_SWAP_MEMORY would be a good solution in my opinion. I agree that 'use_swap_memory' is a confusing parameter name.
