### ISSUE TITLE
[rllib] Update rllib documentation to not reference example scripts

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1091]
https://github.com/ray-project/ray/blob/master/doc/source/example-a3c.rst
https://github.com/ray-project/ray/blob/master/doc/source/example-evolution-strategies.rst
https://github.com/ray-project/ray/blob/master/doc/source/example-policy-gradient.rst

One odd thing is that even though we support `pip install ray`, I don't think that gets you the train.py script, so you still need to clone the repo. Maybe that should be included or we can use the `ray` command line. @robertnishihara thoughts?

**Comment by ericl** [comment]
Also made https://github.com/ray-project/ray/compare/master...ericl:rllib-docs-2?expand=1

**Comment by robertnishihara** [comment]
The diff looks reasonable, any reason not to make a PR?

As for shipping `train.py`, I think cloning the repo is ok for now. If we were to hide it behind a command like `ray train ...` people would have a harder time finding the file to inspect it and see what's going on.

**Comment by ericl** [comment]
Made the pr.
