### ISSUE TITLE
[docs] clarify platforms for questions, bug reports, feature requests, etc.

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10917]
### Describe your feature request
on master, we currently say:
> Reach out to us if you have any questions or issues or feedback through the following channels:
> 1. [StackOverflow](https://stackoverflow.com/questions/tagged/ray): For questions about how to use Ray.
> 2. [GitHub Issues](https://github.com/ray-project/ray/issues): For bug reports and feature requests.

I think we should say something like the following:
1. GitHub Issues for bug reports, feature requests, and conceptual questions about Ray
2. StackOverflow for support with usage and debugging
3. Slack for discussing Ray

being consistent with platforms will probably make it easier for users to search previous questions + tickets

P3 because the current system works fine IMO

**Comment by rkooo567** [comment]
@sumanthratna @richardliaw Isn't it already there?

**Comment by richardliaw** [comment]
fixed i think as of october!
