### ISSUE TITLE
[RaySGD] mixed precision on PyTorch using torch.cuda.amp

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10919]
### Describe your feature request
on pytorch >= 1.6.0, torch.cuda.amp could be used for mixed precision training instead of apex (which would reduce a dependency)

PyTorch Lightning allows using either apex or pytorch's native mixed precision. https://pytorch-lightning.readthedocs.io/en/latest/amp.html

[slack](https://ray-distributed.slack.com/archives/CSX7HVB5L/p1598555758016800)

**Comment by amogkam** [comment]
Yes this makes total sense to do. We probably would still want to support apex for torch versions < 1.6. 

This is currently on our backlog, but please feel free to open a PR for this if you'd like!

**Comment by richardliaw** [comment]
cc @zhisbug
