### ISSUE TITLE
[RaySGD] multi-GPU training

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#10918]
### Describe your feature request
currently, both `ray.util.sgd.torch.TorchTrainer` and `ray.tune.integration.torch.DistributedTrainableCreator` accept `use_gpu: bool` instead of tune's `resources_per_trial: dict` because RaySGD only utilizes 1 GPU to store the models and optimizers. It would be nice if there was a `resources: dict` arg to enable multi-GPU training. 

[slack](https://ray-distributed.slack.com/archives/CSX7HVB5L/p1598556463019300)

**Comment by richardliaw** [comment]
cc @zhisbug
