### ISSUE TITLE
[ray] Redis memory increase on head

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#10927]
*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 0.8.7, Python 3.8.5, Debian

We notice a memory increase problem on head machine.
We have done some researches to find out what happened.
First, we find a lot of keys increased in the Redis server.
![image](https://user-images.githubusercontent.com/1586755/93778411-77799600-fc58-11ea-91cd-137d8fb3bc89.png)
Then we output the increased keys
![image](https://user-images.githubusercontent.com/1586755/93778691-c0c9e580-fc58-11ea-9aef-19b9665e3885.png)
All new keys seem to have a 'PROFILE' prefix. And I search this prefix in the source code and find out this is added by raylet.
Our Redis memory seems to continually increase and eventually, the whole system crashed. Any advice about this issue is welcomed.

**Comment by rkooo567** [comment]
Thanks for the report! There’s a PR to limit the number of profile table in Redis (, and it won’t be available in our next release, but will be included in the one after that). Are you using the nightly ray?

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/10888

**Comment by Seraphli** [comment]
We are not using the nightly ray. To use ray we have to build a docker image first. So it will be difficult to use nightly version.
Because we run ray on a cluster with 25 computers, we have to allocate the head machine with 900G memory in order to let the experiment run longger.

**Comment by Seraphli** [comment]
Can this be fixed more early? This memory issue I think is a major issue. This will make the system crash quickly.

**Comment by ericl** [comment]
These entries should start getting evicted once you hit the redis_max_memory config. Try lowering that config in ray.init()?

**Comment by Seraphli** [comment]
Okay, I will try this. We actually set redis_max_memory config equal to the whole memory. Any suggestions of this config? And BTW,  is the evict setting turned on default?

**Comment by Seraphli** [comment]
Another question, will this config only evict the key with `PROFILE` perfix, or will it evict the oldest key? Because we have a lot of actor class, I think some of them will stay longer than the profile keys. I don't know whether this will be a problem.

**Comment by ericl** [comment]
I would recommend either going with the default setting, or something small like 500 megabytes. Ray does not use Redis for primary storage, only metadata.

The critical metadata tables like Actors are placed on the primary shard and won't get evicted -- only secondary tables like PROFILE are eligible for eviction.

**Comment by Seraphli** [comment]
Okay, I will try that out.

**Comment by Seraphli** [comment]
After I remove all memory settings and let ray to choose all memory settings, the memory increases much slower than before.  I think the problem is solved.
