### ISSUE TITLE
ray cluster fails to start using ray/autoscaler/local/example-full.yaml

### ISSUE THREAD

**Issue by ankur6ue** [ray-project/ray#10920]
### What is the problem?
I modified the example-full.yaml file according to my local cluster (one master node, one slave node), see modified content below. The cluster fails to start. Not seeing any obvious errors. I'm able to use ray start to start the master node and then have the worker node join the master manually. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Latest version of Ray, Python 3.7.4. Ubuntu 18.04
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Here's my modified script:
``` (to disable markdown highlighting)

# An unique identifier for the head node and workers of this cluster.
cluster_name: shap

## NOTE: Typically for local clusters, min_workers == initial_workers == max_workers == len(worker_ips).

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
min_workers: 1
# The initial number of worker nodes to launch in addition to the head node.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
initial_workers: 1

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
max_workers: 1

# Autoscaling parameters.
# Ignore this if min_workers == initial_workers == max_workers.
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
docker:
    image: "" # e.g., rayproject/ray:0.8.7
    container_name: "" # e.g. ray_docker
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# Local specific configuration.
provider:
    type: local
    head_ip: 192.168.1.254
    worker_ips: [192.168.1.213]
    # Optional when running automatic cluster management on prem. If you use a coordinator server,
    # then you can launch multiple autoscaling clusters on the same set of machines, and the coordinator
    # will assign individual nodes to clusters as needed.
    #    coordinator_address: "<host>:<port>"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ankur
    # Optional if an ssh private key is necessary to ssh to the cluster.
    ssh_private_key: /home/ankur/.ssh/home_ubuntu_laptop/id_rsa

# Leave this empty.
head_node: {}

# Leave this empty.
worker_nodes: {}

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
  "/home/ankur/dev/apps/ML/Interpretability/myshap": "/home/ankur/dev/apps/ML/Interpretability/myshap",

#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands:
    - pip install -U ray

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
If we cannot run your script, we cannot fix your issue.

- [yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
```
The output is this:

(shap_py_env) ankur@master-node:~/dev/apps/ML/Interpretability/myshap/ray$ ray up config.yml
2020-09-20 22:15:14,457	INFO node_provider.py:38 -- ClusterState: Loaded cluster state: ['192.168.1.254', '192.168.1.213']
Updating cluster configuration and running full setup.
Cluster Ray runtime will be restarted. Confirm [y/N]: y

<1/1> Setting up head node
  Prepared bootstrap config
2020-09-20 22:15:20,789	INFO node_provider.py:82 -- ClusterState: Writing cluster state: ['192.168.1.254', '192.168.1.213']
  New status: waiting-for-ssh
  [1/6] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: 192.168.1.254
Warning: Permanently added '192.168.1.254' (ECDSA) to the list of known hosts.
ankur@192.168.1.254's password: 
 22:15:25 up 9 days, 10:46,  2 users,  load average: 0.26, 0.32, 0.41
Shared connection to 192.168.1.254 closed.
    Success.
  Updating cluster configuration. [hash=37b2552d92785186e57d869fdb192ded778e1f17]
2020-09-20 22:15:25,102	INFO node_provider.py:82 -- ClusterState: Writing cluster state: ['192.168.1.254', '192.168.1.213']
  New status: syncing-files
  [2/6] Processing file mounts
Shared connection to 192.168.1.254 closed.
sending incremental file list

sent 740,194 bytes  received 2,417 bytes  1,485,222.00 bytes/sec
total size is 726,271,230  speedup is 978.00
    /home/ankur/dev/apps/ML/Interpretability/myshap/ from /home/ankur/dev/apps/ML/Interpretability/myshap/
Shared connection to 192.168.1.254 closed.
sending incremental file list
ray-bootstrap-qq6_emwg

sent 273 bytes  received 47 bytes  640.00 bytes/sec
total size is 1,079  speedup is 3.37
Shared connection to 192.168.1.254 closed.
sending incremental file list

sent 58 bytes  received 12 bytes  140.00 bytes/sec
total size is 1,675  speedup is 23.93
  [3/6] No worker file mounts to sync
2020-09-20 22:15:26,218	INFO node_provider.py:82 -- ClusterState: Writing cluster state: ['192.168.1.254', '192.168.1.213']
  New status: setting-up
  [4/6] No initialization commands to run.
  [5/6] Running setup commands
    (0/1) pip install -U ray...
Requirement already up-to-date: ray in ./miniconda3/lib/python3.7/site-packages (0.8.7)
Requirement already satisfied, skipping upgrade: redis<3.5.0,>=3.3.2 in ./miniconda3/lib/python3.7/site-packages (from ray) (3.4.1)
Requirement already satisfied, skipping upgrade: py-spy>=0.2.0 in ./miniconda3/lib/python3.7/site-packages (from ray) (0.3.3)
Requirement already satisfied, skipping upgrade: filelock in ./miniconda3/lib/python3.7/site-packages (from ray) (3.0.12)
Requirement already satisfied, skipping upgrade: prometheus-client>=0.7.1 in ./miniconda3/lib/python3.7/site-packages (from ray) (0.8.0)
Requirement already satisfied, skipping upgrade: google in ./miniconda3/lib/python3.7/site-packages (from ray) (3.0.0)
Requirement already satisfied, skipping upgrade: aioredis in ./miniconda3/lib/python3.7/site-packages (from ray) (1.3.1)
Requirement already satisfied, skipping upgrade: opencensus in ./miniconda3/lib/python3.7/site-packages (from ray) (0.7.10)
Requirement already satisfied, skipping upgrade: gpustat in ./miniconda3/lib/python3.7/site-packages (from ray) (0.6.0)
Requirement already satisfied, skipping upgrade: requests in ./miniconda3/lib/python3.7/site-packages (from ray) (2.22.0)
Requirement already satisfied, skipping upgrade: click>=7.0 in ./miniconda3/lib/python3.7/site-packages (from ray) (7.0)
Requirement already satisfied, skipping upgrade: colorama in ./miniconda3/lib/python3.7/site-packages (from ray) (0.4.3)
Requirement already satisfied, skipping upgrade: colorful in ./miniconda3/lib/python3.7/site-packages (from ray) (0.5.4)
Requirement already satisfied, skipping upgrade: msgpack<2.0.0,>=1.0.0 in ./miniconda3/lib/python3.7/site-packages (from ray) (1.0.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.8.0 in ./miniconda3/lib/python3.7/site-packages (from ray) (3.11.3)
Requirement already satisfied, skipping upgrade: pyyaml in ./miniconda3/lib/python3.7/site-packages (from ray) (5.3.1)
Requirement already satisfied, skipping upgrade: jsonschema in ./miniconda3/lib/python3.7/site-packages (from ray) (3.2.0)
Requirement already satisfied, skipping upgrade: grpcio>=1.28.1 in ./miniconda3/lib/python3.7/site-packages (from ray) (1.32.0)
Requirement already satisfied, skipping upgrade: numpy>=1.16 in ./miniconda3/lib/python3.7/site-packages (from ray) (1.18.3)
Requirement already satisfied, skipping upgrade: aiohttp in ./miniconda3/lib/python3.7/site-packages (from ray) (3.6.2)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in ./miniconda3/lib/python3.7/site-packages (from google->ray) (4.8.2)
Requirement already satisfied, skipping upgrade: hiredis in ./miniconda3/lib/python3.7/site-packages (from aioredis->ray) (1.1.0)
Requirement already satisfied, skipping upgrade: async-timeout in ./miniconda3/lib/python3.7/site-packages (from aioredis->ray) (3.0.1)
Requirement already satisfied, skipping upgrade: google-api-core<2.0.0,>=1.0.0 in ./miniconda3/lib/python3.7/site-packages (from opencensus->ray) (1.16.0)
Requirement already satisfied, skipping upgrade: opencensus-context==0.1.1 in ./miniconda3/lib/python3.7/site-packages (from opencensus->ray) (0.1.1)
Requirement already satisfied, skipping upgrade: psutil in ./miniconda3/lib/python3.7/site-packages (from gpustat->ray) (5.6.7)
Requirement already satisfied, skipping upgrade: blessings>=1.6 in ./miniconda3/lib/python3.7/site-packages (from gpustat->ray) (1.7)
Requirement already satisfied, skipping upgrade: six>=1.7 in ./miniconda3/lib/python3.7/site-packages (from gpustat->ray) (1.15.0)
Requirement already satisfied, skipping upgrade: nvidia-ml-py3>=7.352.0 in ./miniconda3/lib/python3.7/site-packages (from gpustat->ray) (7.352.0)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./miniconda3/lib/python3.7/site-packages (from requests->ray) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./miniconda3/lib/python3.7/site-packages (from requests->ray) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ./miniconda3/lib/python3.7/site-packages (from requests->ray) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./miniconda3/lib/python3.7/site-packages (from requests->ray) (1.25.10)
Requirement already satisfied, skipping upgrade: setuptools in ./miniconda3/lib/python3.7/site-packages (from protobuf>=3.8.0->ray) (49.6.0.post20200814)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in ./miniconda3/lib/python3.7/site-packages (from jsonschema->ray) (0.16.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in ./miniconda3/lib/python3.7/site-packages (from jsonschema->ray) (1.7.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in ./miniconda3/lib/python3.7/site-packages (from jsonschema->ray) (19.3.0)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in ./miniconda3/lib/python3.7/site-packages (from aiohttp->ray) (1.4.2)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in ./miniconda3/lib/python3.7/site-packages (from aiohttp->ray) (4.7.5)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in ./miniconda3/lib/python3.7/site-packages (from beautifulsoup4->google->ray) (1.9.5)
Requirement already satisfied, skipping upgrade: pytz in ./miniconda3/lib/python3.7/site-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (2019.3)
Requirement already satisfied, skipping upgrade: googleapis-common-protos<2.0dev,>=1.6.0 in ./miniconda3/lib/python3.7/site-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (1.51.0)
Requirement already satisfied, skipping upgrade: google-auth<2.0dev,>=0.4.0 in ./miniconda3/lib/python3.7/site-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (1.21.2)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in ./miniconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema->ray) (3.1.0)
Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= "3.5" in ./miniconda3/lib/python3.7/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (3.4.2)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in ./.local/lib/python3.7/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (4.0.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in ./.local/lib/python3.7/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (0.2.8)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in ./.local/lib/python3.7/site-packages (from rsa<5,>=3.1.4; python_version >= "3.5"->google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (0.4.8)
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/home/ankur/miniconda3/bin/python -m pip install --upgrade pip' command.
Shared connection to 192.168.1.254 closed.
  [6/6] Starting the Ray runtime
Shared connection to 192.168.1.254 closed.
2020-09-20 22:15:29,423	INFO scripts.py:465 -- Using IP address 192.168.1.254 for this node.
2020-09-20 22:15:29,425	INFO resource_spec.py:231 -- Starting Ray with 3.76 GiB memory available for workers and up to 1.9 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-09-20 22:15:29,850	INFO services.py:1193 -- View the Ray dashboard at localhost:8265
2020-09-20 22:15:29,876	INFO scripts.py:495 -- 
Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --address='192.168.1.254:6379' --redis-password='5241590000000000'

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(address='auto', redis_password='5241590000000000')

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
Shared connection to 192.168.1.254 closed.
2020-09-20 22:15:30,050	INFO node_provider.py:82 -- ClusterState: Writing cluster state: ['192.168.1.254', '192.168.1.213']
  New status: up-to-date
2020-09-20 22:15:30,051	INFO commands.py:636 -- get_or_create_head_node: Head node up-to-date, IP address is: 192.168.1.254
To monitor auto-scaling activity, you can run:

  ray exec /home/ankur/dev/apps/ML/Interpretability/myshap/ray/config.yml 'tail -n 100 -f /tmp/ray/session_*/logs/monitor*'

To open a console on the cluster:

  ray attach /home/ankur/dev/apps/ML/Interpretability/myshap/ray/config.yml

To get a remote shell to the cluster manually, run:

  ssh -o IdentitiesOnly=yes -i /home/ankur/.ssh/home_ubuntu_laptop/id_rsa ankur@192.168.1.254

When I do ray status, I get ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.

**Comment by amogkam** [comment]
Are you running `ray status` on your laptop? In that case it's trying to identify a Ray cluster on your local machine; instead you want to run `ray status` on your cluster. You can do that by running `ray exec config.yml 'ray status'`, which will execute the `ray status` command on the cluster. Or, you can ssh into the head node of your cluster via `ray attach config.yml` and then run `ray status`. More info on how to interact with your cluster can be found here https://docs.ray.io/en/master/cluster/launcher.html.

If you're running `ray status` on your cluster and you are still getting that error then theres definitely a problem. In that case let us know and we can follow up again.

**Comment by ankur6ue** [comment]
Thanks for your response, I was indeed ray status on the laptop. Unfortunately I still get the cluster not running error after following your instructions:
```
(base) ankur@master-node:~/dev/apps/ML/Interpretability/myshap$ ray exec  /home/ankur/dev/apps/ML/Interpretability/myshap/ray/config.yml 'ray status'
2020-09-21 09:46:42,672	INFO cli_logger.py:388 -- Using cached config at /tmp/ray-config-876b66d5ea0c31a6fcb658dc93fc71ad1d07fbf0
2020-09-21 09:46:42,674	INFO node_provider.py:38 -- ClusterState: Loaded cluster state: ['192.168.1.254', '192.168.1.213']
2020-09-21 09:46:42,674	INFO node_provider.py:38 -- ClusterState: Loaded cluster state: ['192.168.1.254', '192.168.1.213']
2020-09-21 09:46:42,675	INFO log_timer.py:27 -- NodeUpdater: 192.168.1.254: Got IP  [LogTimer=0ms]
2020-09-21 09:46:42,675	INFO cli_logger.py:388 -- NodeUpdater: 192.168.1.254: Running ssh -tt -i /home/ankur/.ssh/home_ubuntu_laptop/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_f2490ad5cb/f7968361b2/%C -o ControlPersist=10s -o ConnectTimeout=120s ankur@192.168.1.254 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray status'
Traceback (most recent call last):
  File "/home/ankur/miniconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1237, in main
    return cli()
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1174, in status
    address = services.find_redis_address_or_die()
  File "/home/ankur/miniconda3/lib/python3.7/site-packages/ray/services.py", line 168, in find_redis_address_or_die
    "Could not find any running Ray instance. "
ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.
Shared connection to 192.168.1.254 closed.
Error: Command failed: 

  ssh -tt -i /home/ankur/.ssh/home_ubuntu_laptop/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_f2490ad5cb/f7968361b2/%C -o ControlPersist=10s -o ConnectTimeout=120s ankur@192.168.1.254 bash --login -c -i ''"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray status'"'"''

```
As I mentioned, I'm able to create a cluster by doing a ray start on my main laptop and then joining the main node from the other laptop. Conceptually, what is the difference between the two approaches?

**Comment by ankur6ue** [comment]
Here's a shell script that starts a head node, copies (project specific) files and then launches worker nodes that join the head nodes. It makes sure that an identical conda environment is created on all nodes (which is very important, and should be emphasized in the docs)

```
update_master_node() {
  # Master node
  # cd to project folder directory if necessary
  # update conda environment (create if necessary)
  NUM_CPUS=$1
  MASTER_IP=$2
  PORT=$3
  conda env update --file envs/environment.yml --name shap_py_env ./envs --prune
  # conda activate has issues from within a shell script, workaround is to use source activate
  source activate shap_py_env
  # -f option forcibly stops ray processes
  ray stop -f
  ray start --head --num-cpus=$NUM_CPUS --redis-password="password" --port=$PORT
}

update_worker_node() {
  # Master node
  # cd to project folder directory if necessary
  # update conda environment (create if necessary)
  NUM_CPUS=$1
  MASTER_IP=$2
  PORT=$3
  # change directory to where we copied files and update and then activate the conda environment
  # this is necessary because the master and workers must have the same conda environment for multi-node execution
  # to work
  cd ~/dev/apps/ML/Interpretability/myshap/
  conda env update --file envs/environment.yml --name shap_py_env ./envs --prune
  source activate shap_py_env
  # -f option forcibly stops ray processes
  ray stop -f
  # start ray on worker node
  ray start --num-cpus=$NUM_CPUS --address=$MASTER_IP:$PORT --redis-password="password"
}


master_node_address="$(hostname --ip-address)"
NUM_CPUS=4
NUM_CPUS_WORKERS=6
PORT=6378
SSH_KEY_LOCATION=~/.ssh/home_ubuntu_laptop/id_rsa

# step 1: run head node
update_master_node $NUM_CPUS $master_node_address $PORT

input="ray/cluster_config.txt"
while IFS= read -r line
do
  echo "$line"
  worker_ip=$line
  # step 2: copy any conda env and source files from master to worker nodes. This is obviously project specific
  scp -i $SSH_KEY_LOCATION -r ./source ankur@$worker_ip:~/dev/apps/ML/Interpretability/myshap/
  scp -i $SSH_KEY_LOCATION ./envs/environment.yml ankur@$worker_ip:~/dev/apps/ML/Interpretability/myshap/envs/environment.yml
  # step 3: attach worker nodes to master. Worker IPs are specified in cluster_config.txt
  # This line opens a SSH connection with each worker and calls update_slave_node with the arguments provided on the worker node
  ssh ankur@$worker_ip -i $SSH_KEY_LOCATION "$(typeset -f update_worker_node); update_worker_node $NUM_CPUS_WORKERS $master_node_address $PORT"
done < "$input"
```
I'd still like to understand why the ray up approach is not working, and also would like to understand what is it doing that is different from this shell script. Incidentally, this lack of understanding of what's happening under the hood is my major issue with DASK that led to my investigation of Ray.

**Comment by amogkam** [comment]
Ah sorry I misread your initial question. So you have a local cluster with 2 nodes, and the head node is your laptop correct? In that case both running `ray status` and `ray exec cluster.yaml "ray status"` from your laptop/head node are equivalent. From your output in the initial post it seems like Ray was started up properly so it's weird that you're getting an error when trying to connect to it. Can you try upgrading ray (`pip install -U ray==1.0.0rc0`) and trying again?

As for what `ray up` is doing vs your shell script they should be pretty much the same. `ray up` first sets up the head node by copying over the file mounts and running the setup commands. And then does the same for the worker node. Hope this helps.

**Comment by rkooo567** [comment]
Note Ray requires bi-directional network communication among nodes, so if you use your laptop as a node, it could cause troubles (because of personal laptop's firewall or other security-related features).

**Comment by amogkam** [comment]
@ankur6ue were you able to get this working?

**Comment by ankur6ue** [comment]
I haven't tried.. mostly because of a lack of full understanding of what's going on under the hood. Lacking this understanding, I'll likely run into other hard to debug issues. 

I build my own scripts to run ray inside docker images. Attaching them here, along with a few bugs I encountered along the way. 

```
1. Building ray docker image:
#git clone --branch releases/1.0.0 https://github.com/ray-project/ray.git
rm -rf ray
git clone https://github.com/ray-project/ray.git
cd ray
./build-docker.sh

Bug 1: Getting a particular labeled release (eg git clone --branch releases/1.0.0 https://github.com/ray-project/ray.git) and then building ray docker image fails. 

2. Starting with the ray docker image just built, copy your own application code and create another image, (ray/myshap in my case)

3. Launch docker container based on above image and launch ray in it. This turned out to be surprisingly tricky.. Here's my script:
update_master_node() {
  # Master node
  # cd to project folder directory if necessary

  NUM_CPUS=$1
  PORT=$2
  IMAGE_NAME=$3
  CONTAINER_NAME=$4

  docker build -t $IMAGE_NAME:latest .

  # stop running containers with name CONTAINER_NAME
  docker ps --filter "name=$CONTAINER_NAME" -aq | xargs docker stop | xargs docker rm

  # First run our docker container based on the image we just created, then run ray on it. Must be
  # done in this sequence for this to work..
  # -itd runs the container in interactive mode in the background
  # --rm removes the container when it is stopped
  # --network=host lets workers connect to ray master using the master machine's IP
  # /bin/bash lets the container running so we can run exec commands
  docker run -itd --rm --name=$CONTAINER_NAME --shm-size=2G --network=host $IMAGE_NAME /bin/bash
  # -f option forcibly stops ray processes
  docker exec $CONTAINER_NAME \
    ray start --head --num-cpus=$NUM_CPUS --redis-password="password" --port=$PORT
}

Bug 2: If I run 'ray status' in the above container, I get an authentication error. 

3. Launch docker containers on workers and connect with the head node:
update_worker_node() {
  # Worker node
  # cd to project folder directory if necessary
  # update conda environment (create if necessary)

  NUM_CPUS=$1
  PORT=$2
  MASTER_IP=$3
  IMAGE_NAME=$4
  CONTAINER_NAME=$5
  ROOT_DIR=$6
  # change directory to the location of Dockerfile
  cd $ROOT_DIR
  docker build -t $IMAGE_NAME:latest .
   # stop running containers with name CONTAINER_NAME
  docker ps --filter "name=$CONTAINER_NAME" -aq | xargs docker stop | xargs docker rm

  # First run our docker container based on the image we just created, then run ray on it. Must be
  # done in this sequence for this to work..
  # -itd runs the container in interactive mode in the background
  # --rm removes the container when it is stopped
  # --network=host lets workers connect to ray master using the master machine's IP
  # /bin/bash lets the container run so we can run exec commands later
  docker run -itd --rm --name=$CONTAINER_NAME --shm-size=2G --network=host $IMAGE_NAME /bin/bash

  docker exec $CONTAINER_NAME \
  ray start --num-cpus=$NUM_CPUS --redis-password="password" --address=$MASTER_IP:$PORT
}

Bug 3: With the setup above, I can use the ray dashboard to see the number of CPUs on the master and worker nodes, but the drop down list for the worker node flickers..

Now you can run your python code by doing an exec in the container:
docker exec -it myshap python source/kernel_shap_test_ray.py
```

**Comment by ankur6ue** [comment]
https://github.com/ray-project/ray/issues/9474 seems related to Bug# 2

**Comment by amogkam** [comment]
@ankur6ue thanks a lot for this! it would be great if you could raise a separate issue for the docker related bugs you are getting when trying to run ray with your own script. It'll be easier to track on our end, and also easier for others to search if they run into the same issue.

**Comment by ankur6ue** [comment]
Hi Amog, sounds good. I'll close this issue and raise a separate one. 

Btw, I've written up a blog post about how to run a DAG on Ray local cluster using docker images:
https://www.telesens.co/2020/10/05/speeding-up-shapley-value-computation-using-ray-a-distributed-computing-system/

I also talk about how to pass temporary AWS credentials to make Boto calls from inside the docker containers. 

The code is here: https://github.com/ankur6ue/myshap

Still a bit WIP, but is there any interest in featuring this on the Ray blogs page?  
https://medium.com/distributed-computing-with-ray

**Comment by amogkam** [comment]
@ankur6ue thanks! Also took a look over your blog post, and it looks great :). I'll confirm with the team about the next steps and get back to you.
