### ISSUE TITLE
[tune][rllib] Support switching between DurableTrainable and Trainable for RL jobs through Tune API

### ISSUE THREAD

**Issue by annaluo676** [ray-project/ray#10939]
### Describe your feature request
It is not uncommon for large scale RL jobs that one has to setup a complex cluster (e.g., mixture of CPU & GPU nodes). `DurableTrainable` supports checkpointing to and restoring from remote storage and removes the need to use `rsync` for checkpoints sync down. 

It would be very useful if there exists a flag using which RLlib users can switch between `DurableTrainable` and `Trainable`. That way the checkpoint sync is between remote nodes and remote storage (e.g. Amazon S3) directly and the error-prone `rsync` method can be bypassed.

**Comment by richardliaw** [comment]
cc @sven1977 @krfricke let's chat about how to best support this.

**Comment by krfricke** [comment]
From an API perspective, I'd imaging something like 

```
tune.run(
    durable("PPO"),
    ...)
```

with

```
def durable(trainable: Union[str, Trainable]):
    if isinstance(trainable, str):
        trainable_cls = get_trainable_cls(trainable)
    else:
        trainable_cls = trainable
    assert issubclass(trainable_cls, Trainable)

    def WrappedDurableTrainable(DurableTrainable, trainable_cls):
        pass
```

(this is just on the fly, but something like this should work).

Any thoughts?

**Comment by richardliaw** [comment]
That sounds quite nice...
