### ISSUE TITLE
[autoscaler] read_namespaced_pod vs. read_namespaced_pod_status

### ISSUE THREAD

**Issue by mkoh-asapp** [ray-project/ray#10932]
### What is the problem?

There’s a bunch of places where ray is doing `core_api().read_namespaced_pod_status()` but I don’t have the permission to read `pods/status`. It needs to be explicitly granted, so having permission to `get pods` does not give you permission to `get pods/status`.  Can I suggest that you use `read_namespaced_pod` instead? It returns the same information but it seems like it is more common to have that permission than the more specialized pods/status.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.7

### Reproduction (REQUIRED)
n/a (the default ray cluster config will replicate)

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @yiranwang52
