### ISSUE TITLE
[GCS Actor Management] Bug discovered by placement group stress tests.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10945]
### What is the problem?

From the PR https://github.com/ray-project/ray/pull/10924, if we comment in the actor creation, it causes check failures.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run https://github.com/ray-project/ray/pull/10924 script with actor creation commented in.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @ffbin Do you have some time to take a look at this issue? Check failure happened from dependency resolution method.

**Comment by ffbin** [comment]
@rkooo567 I will take a look.

**Comment by rkooo567** [comment]
Is this addressed? This still seemed to be broken. (I have too many open files errors now). 

```
E0930 00:55:26.042824 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = d67740bb01000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:26.091863 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = 4c2edd9c01000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:26.183753 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = cc1e4f4301000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:26.404335 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = 1a20447b01000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:27.239158 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = 7adb170101000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:27.245096 92523 286223808 gcs_actor_manager.cc:136] Failed to create actor, job id = 01000000, actor id = 4c7e16d401000000, status: Invalid: Actor may be already destroyed.
E0930 00:55:42.027187000 123145339547648 tcp_server_posix.cc:213]      Failed accept4: Too many open files
```

**Comment by ffbin** [comment]
I've had this problem, too. Sometimes I restart the Mac and it can run successfully.
