### ISSUE TITLE
Install ray release version from S3 wheel directly

### ISSUE THREAD

**Issue by jieru-hu** [ray-project/ray#10943]
### What is your question?

I want to be able to download ray's release wheels directly from S3 and install (due to firewall rules on my machine, I do not want to open 443 to for pip)

However I'm not sure what would the path be like, how does one know which SHA to use when trying to install the official releases? Thank you!

```
aws s3 ls s3://ray-wheels/releases/0.8.6/
                           PRE 051fdd8ee611e26950e104eeb9375d0d88a846d5/
                           PRE 16a18738808b6f207103628a37411da937c08d60/
                           PRE 29770cbb94c749d858fe7ac3dd2bd8743d67a4c3/
                           PRE 5a6dbcf1341336fd1caf88678f55166678880277/
                           PRE 70a081d542ef5b7f0903fa9ae23cfd928397c1b4/
                           PRE 925e9acd66dc6cd35b6b962ff2ea645c2a078e53/
                           PRE a69715e9aa0f1a24af6a3fedf3339f1d429115d1/
                           PRE cd75e9328519d570a7f85a736c94996b095eeb35/
                           PRE d50635057ce4132da678f29c814bcbaa41896f53/
                           PRE f6034fd12e52894f924ea5f752bb324bc43a05bb/
```

**Comment by wuisawesome** [comment]
`051fdd8ee611e26950e104eeb9375d0d88a846d5`

Essentially, you should match the wheel name to the latest commit in the release branch. https://github.com/ray-project/ray/tree/releases/0.8.6

**Comment by jieru-hu** [comment]
Thank you for the super fast response! Got it :)
