### ISSUE TITLE
[tune] Distributed Torch

### ISSUE THREAD

**Issue by luca310795** [ray-project/ray#10954]
https://docs.ray.io/en/releases-0.8.7/tune/api_docs/trainable.html#distributed-torch explains how to distribute training for a custom Trainable **function**. I'd like to distribute training for a custom Trainable **class**. The first step is to wrap my models with DistributedDataParallel, but of course it's not enough to make it work.
How should I modify my custom Trainable class to implement distributed training?

Thanks!

Ray version: 0.8.7

**Comment by richardliaw** [comment]
Hm, yeah this currently not supported yet. Is there a reason why you're using the custom trainable class instead of the function API?
