### ISSUE TITLE
[rllib] sample_batch_builder: pre batch is passed "by reference" (and not copied) to postprocessing function

### ISSUE THREAD

**Issue by bentzinir** [ray-project/ray#10969]
### What is the problem?
function `postprocess_batch_so_far` sends the batches to postprocessing. The batches from other agents are copied before sent (`other_batches = pre_batches.copy()`), while the "self" batch, i.e. the own batch of the agent is sent without being copied and is edited in place.
As a result, after iterating the first agent, the second agent will receive the post-processed batch of the first agent and not the pre-batch.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
Hmm, I realized that we never in fact deep copy the batches, only the dictionary containing them. If we were to add a copy, this could add a significant amount of overhead.

I assume you're running into this issue since your postprocessing is mutating the batch? Is it possible to add new fields instead of updating existing ones?

**Comment by bentzinir** [comment]
Yes, it's possible. 
Do you want to restrict postprocessing to allow addition and prohibit mutation?

**Comment by sven1977** [comment]
1) We should not copy just for the sake of having the exact pre-batch data available.
2) postprocessing is allowed to a) mutate and b) create new columns. Both are supported.

**Comment by bentzinir** [comment]
To my understanding mutation is not possible.
Say for example I want to average the rewards of two agents: `{r_0: 0, r_1:10}`.
When the batch of agent_0 is postprocessed, the reward field is edited **in place** to `r_0=5`.
When the batch of agent_1 is postprocessed, it will see `r_0=5` and not `r_0=0` as it should be.

**Comment by ericl** [comment]
In that case, how about defining a new avg_reward field and use that in the
policy loss instead of the original?

**Comment by bentzinir** [comment]
Of course. If the overhead of mutation is too expensive I'll go with that.

**Comment by ericl** [comment]
Closing this, since I think the copy is too expensive to support by default and there is a workaround.
