### ISSUE TITLE
[Core] Resources are not returned when implicitly capturing object reference with `max_call` arg.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#10960]
### What is the problem?

Reported from this https://github.com/ray-project/ray/issues/10739

When running the script below, GPU resources are never returned. There is a couple interesting behaviors.

1. We have local reference from our internal methods.
<img width="1665" alt="Screen Shot 2020-09-22 at 4 15 23 PM" src="https://user-images.githubusercontent.com/18510752/93946710-d1c53600-fcee-11ea-9b9f-1b7aedca2f30.png">

2. When we move `X_id` and `int_ref` into the task, or when we pass them by arg, the error disappeared. 

3. When we remove `max_call`, the error disappeared.

It might be some unknown bugs from ref counting, but I am not sure.

cc @stephanie-wang @ericl 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for i in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
    print(i, ray.available_resources())
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by yogeveran** [comment]
This issue caused us a lot of trouble.
Version 1.6 of ray (unable to update version at the moment).
Was this solved in a future release? If not what is holding the fix?

**Comment by ericl** [comment]
Minimal repro:
```
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

@ray.remote(num_cpus=0)
def g():
    time.sleep(.1)
    return 0

@ray.remote(num_cpus=1, num_gpus=1, max_calls=1, max_retries=0)
def f():
    return [g.remote()]

nested1 = ray.get(f.remote())
nested2 = ray.get(f.remote())  # Hangs.
```

The root cause is that we don't return the worker to the raylet per:

```
          if (reply.worker_exiting()) {
            RAY_LOG(DEBUG) << "Worker " << addr.worker_id
                           << " replied that it is exiting.";
            // The worker is draining and will shutdown after it is done. Don't return
            // it to the Raylet since that will kill it early.
```
