### ISSUE TITLE
centralized_critic example not working

### ISSUE THREAD

**Issue by vasnakh** [ray-project/ray#10965]
I tried to run centralized_critic.py from the example but  I see an error and am not able to run. Below is a screenshot of the error. Can someone please help me with this? I am running the code using python 3.7.9
![image](https://user-images.githubusercontent.com/11311208/93954004-78b2cd80-fd01-11ea-9788-3ee60e3380f9.png)

**Comment by ericl** [comment]
It works for me. Try upgrading Ray / TF?

**Comment by vasnakh** [comment]
I have upgraded to latest version and still does not work

**Comment by vasnakh** [comment]
> It works for me. Try upgrading Ray / TF?

I have upgraded to latest version and still does not work
