### ISSUE TITLE
Tests fail due to error on Ubuntu 17.04

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#1098]
Running `runtest.py` on Ubuntu 17.04 fails `APITest.testRegisterClass` and `APITestSharded.testRegisterClass` due to errors:
- Initial error -- `pyarrow.lib.SerializationCallbackError`: pyarrow does not know how to serialize objects of type `<class '_sre.SRE_Pattern'>`
- During handling of exception -- `TypeError:` can't pickle `getset_descriptor` objects

Steps to reproduce:
1. Clone ray
2. Build ray in a python3 virtual environment using `python3 setup.py develop`
3. Run tests using `python3 runtest.py`

Test output:
- [Complete test output](https://github.com/ray-project/ray/files/1370158/complete_test_output.txt)
- [APITest.testRegisterClass](https://github.com/ray-project/ray/files/1370164/apitest_test_register_class.txt)
- [APITestSharded.testRegisterClass](https://github.com/ray-project/ray/files/1370163/apitestsharded_test_register_class.txt)

**Comment by robertnishihara** [comment]
Interesting, this feels like more of a Python problem than an Ubuntu problem. Actually, it might be a cloudpickle problem. Can you try `pip install cloudpickle==0.3.0` and maybe also try `0.2.2` and some other versions and see if the problem occurs there?

**Comment by pschafhalter** [comment]
Running `pip install cloudpickle==0.3.0` fixed the issue. All tests pass now.
