### ISSUE TITLE
[tune] Simple examples are very slow/suffer from large overhead

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#11004]
### What is the problem?

Very simple objectives have a lot of overhead when run with Ray Tune. For instance, the original Optuna example:

```
import time

import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    return (x - 2) ** 2

start = time.time()
study = optuna.create_study()
study.optimize(objective, n_trials=100)

print(study.best_params)
print(f"Took {time.time() - start:.2f} seconds to run.")
```
takes about `0.10` seconds to run on my machine.

In contrast, an equivalent example in Ray Tune:

```
import time

from ray import tune
from ray.tune.suggest.optuna import OptunaSearch


def objective(config):
    x = config["x"]
    return (x - 2) ** 2

start = time.time()
analysis = tune.run(
    objective,
    metric="_metric",
    mode="min",
    config={"x": tune.uniform(-10, 10)},
    num_samples=100,
    search_alg=OptunaSearch()
)

print(analysis.best_config)
print(f"Took {time.time() - start:.2f} seconds to run.")
```

takes about `22.73` (!) seconds to run.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Note that this is similar to https://github.com/ray-project/ray/issues/7608

**Comment by Yard1** [comment]
@krfricke can this be closed?
