### ISSUE TITLE
[tune] How can one discard experiment results without raising an error from a trial?

### ISSUE THREAD

**Issue by ag-tcm** [ray-project/ray#11006]
When I use ray tune sometime I'll have an experiment that has an error while running my trainable function because the hyper-parameters used led to a model that won't converge. I can let the error propagate as a TuneError but I'd prefer to catch it within my trainable function, log it and then stop the experiment with the status of "error" so that the results will be discarded.

I can use the custom stopper (https://docs.ray.io/en/latest/_modules/ray/tune/stopper.html#Stopper) to stop the experiment, but how can I change the status of the experiment so that the results won't be used in the search?

**Comment by richardliaw** [comment]
Maybe `tune.run(raise_on_failed_trial=False`?
