### ISSUE TITLE
[rllib] Setting rewards to 0 in Callbacks doesn't affect training.

### ISSUE THREAD

**Issue by batu** [ray-project/ray#11007]
### What is the problem?
OS: Windows 10
Ray version: 0.8.7 [current latest on pip]
Python version: Python 3.6.12

The eventual goal is to create an interactive RL workflow, where the user is giving feedback to trajectory and that information is used in the ongoing training.

One way to give feedback is to change the rewards per trajectory. In order to do that I used the `on_postprocess_trajectory` callback and set all the rewards in `postprocessed_batch.data` to 0. Unintuitively this did not affect the training. 

I went ahead and tried to access the rewards using the other callbacks (`on_episode_step`, `on_episode_end`, `on_on_sample_end`) and also weren't able to disrupt the training. (except when I set `episode.total_reward = 0`, details are in the python file.)

If I set the observations to 0 in `postprocessed_batch.data`, then, as expected, the training fails. This leads me to believe there might be a bug in how rewards are handled in the callbacks.

Would you be able to suggest another better place to manipulate observations and reward for an interactive RL set up or help me fix the reward setting problem?

Thank you very much.

PS: If one directly downloads and runs the [custom_metrics_and_callbacks.py](https://github.com/ray-project/ray/blob/master/rllib/examples/custom_metrics_and_callbacks.py) example, it does not work.  The presence of `env_index` keyword in the function signatures cause an error.  Can potentially be related to: https://github.com/ray-project/ray/issues/10469

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

[callback_reward_intervention.txt](https://github.com/ray-project/ray/files/5277680/callback_reward_intervention.txt) --> This is a python file.

**Comment by ericl** [comment]
It's probably because advantages are already calculated; you'll need to change the batch before postprocessing or set the advantages directly.

**Comment by batu** [comment]
Thank you, that makes a lot of sense. What would be the proper way to go about doing that? Seems like the callsbacks are executed too late for the purpose

**Comment by ElenaZamaraeva** [comment]
> Thank you, that makes a lot of sense. What would be the proper way to go about doing that? Seems like the callsbacks are executed too late for the purpose

I have the same issue, still have not found how to modify rewards before processing.
