### ISSUE TITLE
[Placement Group] Not working with @ray.remote

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11018]
### What is the problem?

Although @ray.remote contains an argument for placement group, it doesn't work. We should either remove it or allow it. (placement_group_capture_child_task)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
I think we shouldn't allow adding placement group in @ray.remote. What do you think @ffbin?

**Comment by ffbin** [comment]
Yeah, I think so, too.
