### ISSUE TITLE
[rllib] Support custom MultiActionDistribution classes

### ISSUE THREAD

**Issue by ThomasLecat** [ray-project/ray#11016]
### Describe your feature request

Hi,

The function [get_action_dist](https://github.com/ray-project/ray/blob/07bdf062b97cfa0ca6477d6e70212eb92bd2637b/rllib/models/catalog.py#L113) as it is now doesn't allow users to use custom action distribution classes, i.e. classes that inherit from `MultiActionDistribution`, `MultiDiscrete` or their torch counterparts.

The reason is that the `__init___` of multi-action distribution classes need 3 additional keyword-only arguments: `action_space`, `child_distributions` and `input_lens`. The function `get_action_dist` deals with these classes differently than other action distributions and fills these extra arguments with a `partial` function:

https://github.com/ray-project/ray/blob/07bdf062b97cfa0ca6477d6e70212eb92bd2637b/rllib/models/catalog.py#L170-L185

However, this piece of code is unreachable when using custom action distributions, since `get_action_dist` treats all custom action distributions the same way:

 https://github.com/ray-project/ray/blob/07bdf062b97cfa0ca6477d6e70212eb92bd2637b/rllib/models/catalog.py#L139-L144

As discussed in #7341, custom MultiActionDistribution classes are the only way for now to implement differentiable communication channels ( / shared computational graphs) between agents in MARL systems, a very popular approach in the recent literature. The only way I found for now is to change the `policy.dist_class` in the `after_init` function of the policy, which is a bit dirty.

Happy to help with a PR if needed,
Thanks,

**Comment by ericl** [comment]
This sounds like a great idea; PR would be welcome!

**Comment by sven1977** [comment]
Could you take a look at this PR and let us know, whether this would be an acceptable fix?
Thanks!
https://github.com/ray-project/ray/pull/11311

@ThomasLecat @janblumenkamp

**Comment by janblumenkamp** [comment]
Thanks Sven, it looks good and I will give it a try soon!
