### ISSUE TITLE
[GCS server]Distributed mode does not work，beacuse GCS service address is wrong

### ISSUE THREAD

**Issue by GOnion** [ray-project/ray#11027]
When I start two nodes on the **virtual machine**，use the ray cmd ：`ray start --head --port=6397` and  the test file is shown below:
```
import time
import ray
ray.init(address="auto")

@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
ip_list = set(ray.get([f.remote() for _ in range(1000)]))
print(ip_list)
```

the log file like this：
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0925 00:55:40.221179 36519 36519 global_state_accessor.cc:25] Redis server address = 192.168.33.162:6397, is test flag = 0
I0925 00:55:40.223803 36519 36519 redis_client.cc:146] RedisClient connected.
I0925 00:55:40.327855 36519 36519 redis_gcs_client.cc:89] RedisGcsClient Connected.
I0925 00:55:40.330265 36519 36519 service_based_gcs_client.cc:193] Reconnected to GCS server: 192.168.33.162:41771
I0925 00:55:40.330713 36519 36519 service_based_accessor.cc:92] Reestablishing subscription for job info.
I0925 00:55:40.330729 36519 36519 service_based_accessor.cc:422] Reestablishing subscription for actor info.
I0925 00:55:40.330812 36519 36519 service_based_accessor.cc:797] Reestablishing subscription for node info.
I0925 00:55:40.330817 36519 36519 service_based_accessor.cc:1073] Reestablishing subscription for task info.
I0925 00:55:40.330821 36519 36519 service_based_accessor.cc:1248] Reestablishing subscription for object locations.
I0925 00:55:40.330822 36519 36519 service_based_accessor.cc:1368] Reestablishing subscription for worker failures.
I0925 00:55:40.330830 36519 36519 service_based_gcs_client.cc:86] ServiceBasedGcsClient Connected.
```
the GCS service  address is 192.168.33.162:41771, so distributed mode works very well。

But when I deployed it on two **physical machines**，the GCS service  address like this：
```
I0925 00:55:40.327855 36519 36519 redis_gcs_client.cc:89] RedisGcsClient Connected.
I0925 00:55:40.330265 36519 36519 service_based_gcs_client.cc:193] Reconnected to GCS server: 127.0.0.1:41771
I0925 00:55:40.330713 36519 36519 service_based_accessor.cc:92] Reestablishing subscription for job info.
```
Now the GCS service  address is 127.0.0.1:41771，and the other node cannot connect to the master node，because the address of the GSC service is a local address。
I am in a great quandary，How can I solve this problem？

**Comment by rkooo567** [comment]
This might be solved in nightly. Can you try?

**Comment by GOnion** [comment]
> This might be solved in nightly. Can you try?

Thank you for your reply 。Yes，I can

**Comment by rkooo567** [comment]
Let me know how it works!

**Comment by GOnion** [comment]
> Let me know how it works!

There may be something wrong with my previous description. In this paragraph, I try again. The reason for this problem may not be related to the virtual machine.
My work environment cannot be linked to the Internet. It is an offline environment. I can use ray distribution in the network environment, but it can't work in my work environment. So is the distribution of ray related to the network?
I tried many times，It always shows `Reconnected to GCS server: 127.0.0.1:41771`

**Comment by BugMaker-Boyan** [comment]
Could you please show how do you do to work well? I'm searching solution for this case now. Thanks!
