### ISSUE TITLE
address=auto does not work

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#11026]
Using ray 0.9.0

```
  File "/root/train_ray_simple.py", line 418, in tune_bandu
    upload_dir="s3://richard-ray-exps/" # TODO: only add an upload dir if the hyperparam is local
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/tune.py", line 355, in run
    runner.step()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 367, in step
    self.trial_executor.on_no_available_trials(self)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trial_executor.py", line 175, in on_no_available_trials
    trial.config)))
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 4 CPUs, 1 GPUs but the cluster has only 0
CPUs, 0 GPUs, 8.74 GiB heap, 2.98 GiB objects (1.0 node:172.31.9.195). Pass `queue_trials=True` in ray.tune.run() or on the command
line to queue trials until the cluster scales up or resources become available.

```

in my "train_ray_simple.py", I have:
    ray.init(local_mode=args.local_mode, address=args.address)

If I set args.address = "auto", it gives the above error. In other words, it's not connecting to REDIS server at all.

However, if I use the IP printed to stdout in "ray up ... ", it works as expected. 

I can run the exact same "ray submit ... --address=<new ip>" instead of "ray submit ... --address=auto". The former works, the latter gives the above error which looks like REDIS is not connected at all. I would expect these two versions of "ray submit ... " to do the same thing considering they are both using the same YAML.

**Comment by richardliaw** [comment]
hmm, can you try `pip install -U ray --pre` instead for your ray install?

**Comment by richardrl** [comment]
> hmm, can you try `pip install -U ray --pre` instead for your ray install?

Is this installing the latest version of ray from the repository? 

I'm using a version with custom modifications I developed such as file exclusion during syncing, so I don't think this would work.
