### ISSUE TITLE
possible plasma-related crashes on long jobs

### ISSUE THREAD

**Issue by danwallach** [ray-project/ray#11037]
### What is the problem?

Setup:
Ray 1.0rc2, running on Ubuntu 20.04, on Amazon c5.12xlarge VMs (roughly half of the bare metal, 48 virtual cores per node). The job is written in Python 3.8.5.

Source code here:
https://github.com/votingworks/arlo-e2e

The loop driving the cluster is here:
https://github.com/votingworks/arlo-e2e/blob/471fdd7f2fc11f57b58594fbd130a271859c902f/src/arlo_e2e/ray_tally.py#L434-L453

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

The job in question is launched by running:
`ray submit cloud/aws-config.yaml apps/ray_remote_bench.py -- --progress large-input-file.csv`

where the input file has roughly 100k "ballots" in it that we're going to be encrypting. On a single core, it takes about 6 CPU-seconds to do one encryption, so we're using Ray to scale this process up to huge clusters. All of the cluster nodes are configured using `s3fs-fuse` to mount some S3 buckets, but this particular "benchmark" app is not doing any IO. The head node is parsing the CSV file and handing out jobs to all the workers. 

If you remove the `--progress` flag, it disables the progress bar, which uses a Ray actor to gather progress information from all the remote tasks. Maybe it's just a fluke, but this seems to make things run longer without these failures. Similarly, going with smaller input sizes seems to help the jobs to complete without error.

### What are the failures?
The job will run for a few minutes, and then you get lots of stuff like this:
```
2020-09-25 20:59:16,153 WARNING worker.py:1072 -- A worker died or was killed while executing task c872a09429cd0af7ffffffff01000000.
2020-09-25 20:59:16,153 WARNING worker.py:1072 -- A worker died or was killed while executing task bd0f057cd3d9a8cfffffffff01000000.
2020-09-25 20:59:16,153 WARNING worker.py:1072 -- A worker died or was killed while executing task 525d92ab7835ca35ffffffff01000000.
2020-09-25 20:59:16,153 WARNING worker.py:1072 -- A worker died or was killed while executing task 34e211788f0f5242ffffffff01000000.
E0925 20:59:16.154194  1770  1785 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=arlo_e2e.ray_tally, class_name=, function_name=r_encrypt_and_write, function_hash=119039988a244dbe4487742868a24a201b962121}, task_id=3705af39722a2bd2ffffffff01000000, task_name=r_encrypt_and_write(), job_id=01000000, num_args=38, num_returns=1
E0925 20:59:16.156867  1770  1785 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=arlo_e2e.ray_tally, class_name=, function_name=r_encrypt_and_write, function_hash=119039988a244dbe4487742868a24a201b962121}, task_id=9841de07ac7e2bb5ffffffff01000000, task_name=r_encrypt_and_write(), job_id=01000000, num_args=38, num_returns=1
(pid=2067, ip=172.31.14.30) F0925 20:59:15.944625  2067  2067 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2067, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2060, ip=172.31.14.30) F0925 20:59:15.946677  2060  2060 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2060, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2063, ip=172.31.14.30) F0925 20:59:15.946650  2063  2063 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2063, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2073, ip=172.31.14.30) F0925 20:59:15.950402  2073  2073 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2073, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2070, ip=172.31.14.30) F0925 20:59:15.946482  2070  2070 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2070, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2069, ip=172.31.14.30) F0925 20:59:15.946113  2069  2069 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2069, ip=172.31.14.30) *** Check failure stack trace: ***
E0925 20:59:16.159703  1770  1785 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=arlo_e2e.ray_tally, class_name=, function_name=r_encrypt_and_write, function_hash=119039988a244dbe4487742868a24a201b962121}, task_id=501777a7291ae27fffffffff01000000, task_name=r_encrypt_and_write(), job_id=01000000, num_args=38, num_returns=1
```

The node mentioned with that IP address has memory usage that goes crazy, relative to the other nodes, and reports some crashes that look like this:
```
(pid=2066, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2066, ip=172.31.14.30)     @     0x7f344d0f96ed  google::LogMessage::Fail()
(pid=2066, ip=172.31.14.30)     @     0x7f344d0fa84c  google::LogMessage::SendToLog()
(pid=2066, ip=172.31.14.30)     @     0x7f344d0f93c9  google::LogMessage::Flush()
(pid=2061, ip=172.31.14.30) F0925 20:59:15.946403  2061  2061 plasma_store_provider.cc:43]  Check failed: _s.ok() Bad status: IOError: Broken pipe
(pid=2061, ip=172.31.14.30) *** Check failure stack trace: ***
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c4686ed  google::LogMessage::Fail()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c46984c  google::LogMessage::SendToLog()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c4683c9  google::LogMessage::Flush()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c4685e1  google::LogMessage::~LogMessage()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c41f789  ray::RayLog::~RayLog()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c11a4cc  ray::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c0e76c3  ray::CoreWorker::CoreWorker()
(pid=2061, ip=172.31.14.30)     @     0x7f7c2c0eac14  ray::CoreWorkerProcess::CreateWorker()
(pid=2067, ip=172.31.14.30)     @     0x7f47047c26ed  google::LogMessage::Fail()
(pid=2067, ip=172.31.14.30)     @     0x7f47047c384c  google::LogMessage::SendToLog()
(pid=2067, ip=172.31.14.30)     @     0x7f47047c23c9  google::LogMessage::Flush()
(pid=2067, ip=172.31.14.30)     @     0x7f47047c25e1  google::LogMessage::~LogMessage()
(pid=2067, ip=172.31.14.30)     @     0x7f4704779789  ray::RayLog::~RayLog()
(pid=2067, ip=172.31.14.30)     @     0x7f47044744cc  ray::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(pid=2067, ip=172.31.14.30)     @     0x7f47044416c3  ray::CoreWorker::CoreWorker()
(pid=2067, ip=172.31.14.30)     @     0x7f4704444c14  ray::CoreWorkerProcess::CreateWorker()
(pid=2067, ip=172.31.14.30)     @     0x7f4704445e82  ray::CoreWorkerProcess::CoreWorkerProcess()
(pid=2060, ip=172.31.14.30)     @     0x7f056a13e6ed  google::LogMessage::Fail()
(pid=2060, ip=172.31.14.30)     @     0x7f056a13f84c  google::LogMessage::SendToLog()
(pid=2060, ip=172.31.14.30)     @     0x7f056a13e3c9  google::LogMessage::Flush()
(pid=2060, ip=172.31.14.30)     @     0x7f056a13e5e1  google::LogMessage::~LogMessage()
(pid=2060, ip=172.31.14.30)     @     0x7f056a0f5789  ray::RayLog::~RayLog()
(pid=2060, ip=172.31.14.30)     @     0x7f0569df04cc  ray::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(pid=2060, ip=172.31.14.30)     @     0x7f0569dbd6c3  ray::CoreWorker::CoreWorker()
(pid=2060, ip=172.31.14.30)     @     0x7f0569dc0c14  ray::CoreWorkerProcess::CreateWorker()
(pid=2060, ip=172.31.14.30)     @     0x7f0569dc1e82  ray::CoreWorkerProcess::CoreWorkerProcess()
(pid=2063, ip=172.31.14.30)     @     0x7f10902db6ed  google::LogMessage::Fail()
(pid=2063, ip=172.31.14.30)     @     0x7f10902dc84c  google::LogMessage::SendToLog()
(pid=2063, ip=172.31.14.30)     @     0x7f10902db3c9  google::LogMessage::Flush()
(pid=2063, ip=172.31.14.30)     @     0x7f10902db5e1  google::LogMessage::~LogMessage()
(pid=2063, ip=172.31.14.30)     @     0x7f1090292789  ray::RayLog::~RayLog()
(pid=2073, ip=172.31.14.30)     @     0x7f3987c396ed  google::LogMessage::Fail()
(pid=2073, ip=172.31.14.30)     @     0x7f3987c3a84c  google::LogMessage::SendToLog()
(pid=2073, ip=172.31.14.30)     @     0x7f3987c393c9  google::LogMessage::Flush()
(pid=2073, ip=172.31.14.30)     @     0x7f3987c395e1  google::LogMessage::~LogMessage()
(pid=2073, ip=172.31.14.30)     @     0x7f3987bf0789  ray::RayLog::~RayLog()
(pid=2073, ip=172.31.14.30)     @     0x7f39878eb4cc  ray::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(pid=2073, ip=172.31.14.30)     @     0x7f39878b86c3  ray::CoreWorker::CoreWorker()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bec16ed  google::LogMessage::Fail()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bec284c  google::LogMessage::SendToLog()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bec13c9  google::LogMessage::Flush()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bec15e1  google::LogMessage::~LogMessage()
(pid=2070, ip=172.31.14.30)     @     0x7fa53be78789  ray::RayLog::~RayLog()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bb734cc  ray::CoreWorkerPlasmaStoreProvider::CoreWorkerPlasmaStoreProvider()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bb406c3  ray::CoreWorker::CoreWorker()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bb43c14  ray::CoreWorkerProcess::CreateWorker()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bb44e82  ray::CoreWorkerProcess::CoreWorkerProcess()
(pid=2070, ip=172.31.14.30)     @     0x7fa53bb4584b  ray::CoreWorkerProcess::Initialize()
(pid=2070, ip=172.31.14.30)     @     0x7fa53ba83448  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
(pid=2070, ip=172.31.14.30)     @     0x7fa53ba84ba5  __pyx_tp_new_3ray_7_raylet_CoreWorker()
(pid=2070, ip=172.31.14.30)     @           0x5f22eb  _PyObject_MakeTpCall
(pid=2070, ip=172.31.14.30)     @           0x56cb23  _PyEval_EvalFrameDefault
(pid=2070, ip=172.31.14.30)     @           0x565972  _PyEval_EvalCodeWithName
(pid=2070, ip=172.31.14.30)     @           0x5f1d85  _PyFunction_Vectorcall
(pid=2070, ip=172.31.14.30)     @           0x568819  _PyEval_EvalFrameDefault
(pid=2070, ip=172.31.14.30)     @           0x565972  _PyEval_EvalCodeWithName
(pid=2070, ip=172.31.14.30)     @           0x686053  PyEval_EvalCode
(pid=2070, ip=172.31.14.30)     @           0x6753d1  (unknown)
(pid=2070, ip=172.31.14.30)     @           0x67544f  (unknown)
(pid=2070, ip=172.31.14.30)     @           0x675507  PyRun_FileExFlags
(pid=2070, ip=172.31.14.30)     @           0x67758a  PyRun_SimpleFileExFlags
(pid=2070, ip=172.31.14.30)     @           0x6ae99e  Py_RunMain
(pid=2070, ip=172.31.14.30)     @           0x6aed29  Py_BytesMain
```

If necessary, I can provide you with non-public data that you can use to drive this on your own. In the unit tests, there's also a `hypothesis` data generator, that I could perhaps use to generate you a huge and completely synthetic dataset. That may or may not trigger the same sorts of failures.

FWIW, none of these failures are replicable on the local host, although every time I run the unit tests on my Mac, the `python` process will fail (after succeeding on the unit tests) with an "would you like to send this to Apple?" debug box, and inside that is a stack trace that looks a lot like the ones here, where we see a stack of C++ destructors running and blowing up somewhere at the bottom.

**Comment by rkooo567** [comment]
1. Does job finish with that error? 
2. Do you specify --plasma-store-memory when you run ray start? 
3. You can probably specify `memory` argument per each task. `task.options(memory=[bytes]).remote()` This will help you to control the number of tasks per node. 
4. Is that failure happens in one of nodes, a head node, or a node that runs a driver? 
5. Is returned `ptally` from `r_encrypt_and_write` using large memory? When you have references to the object (like the return value of ray.remote), those objects are not GC'ed until references are gone.

**Comment by danwallach** [comment]
I've provided tarballs of the logs to Anyscale privately via Slack.

I'm currently using all the default arguments to `ray start` (see cloud/aws-config.yaml in my project), but if you think it would help, I can try others.

Does it finish? Once these errors start, the computation will sometimes complete, other times reach a ceiling and just stop. It's not consistent. There's also a possible connection between my progress bar actor and the success or failure of the computation. Disabling the progress bar, seems to increase the odds of success for the job.

Memory usage: I've done a ton of work to reduce memory usage, both size and duration. Still, a partial tally is going to be 10-100kB, depending on the input to the job. If there are 100k inputs, there will be 10k results. Furthermore, by getting rid of the ray.wait() calls, whenever a group of those partial tallies is available, I can accumulate them, reducing the live data another 10x. 

The accumulation going on here is associative and commutative, so I could theoretically hack up a call to ray.wait that launches tallies immediately when enough data is available. That would further shorten object lifetimes.

The other thing I could try is to reduce the messaging volume with my progress bar. Those messages are fairly small, but are running around 200 per second. Would it help to group them and reduce the message rate?

**Comment by rkooo567** [comment]
Reducing object lifetimes sounds like a good start. My biggest question is which node has OOM? Is it the node that has a progress bar? driver? or something else? We should figure out which components of your code incur OOM.

Also, I don't think 200 calls to the progress bar per second with small objects matter.

**Comment by danwallach** [comment]
Tomorrow, I'll hack up the shorter lifetime idea and see what happens. It's going to turn into a loop that keeps calling ray.wait and dispatching new jobs based on whatever is ready. That'll be fun. Might even be "optimal" in some fashion.

So far as I can tell, the node that's exploding in memory usage isn't actually out of memory. It's just desperately leaking memory at the same time as it's producing all these error messages. The actor appears to be running elsewhere, but somehow makes the issue more likely to happen.

Anyway, I'm happy to set up a Zoom or whatever so you can watch over my shoulder and tell me to type things or whatever as the job is running.

**Comment by rkooo567** [comment]
Zoom call sounds great. But before that, I'd like to see the log files (because the error you saw seems to happen because raylet or plasma store crashes). You said you shared it in the anyscale private channel, but I am not sure where that is. Can you tag me to the comment?

**Comment by rkooo567** [comment]
It should be @sangcho

**Comment by rkooo567** [comment]
What's the difference between crash/old and just crash/?

**Comment by rkooo567** [comment]
Btw, when I looked into logs, it seems like it is what happened.

Around 21:00:00, there are some workers that failed to be initialized because of that error (broken pipe). I think around that time, those workers failed to be connected to `/tmp/ray/session_latest/sockets/plasma_store_socket`. It seems like after that other workers are started, and your job has finished. Am I correct?

**Comment by danwallach** [comment]
I'm pretty sure I hit ^C before the job completed, but yeah, it's looking like something is happening on that specific worker node that's making workers fail to initialize.

**Comment by danwallach** [comment]
Update: I now have a standalone repo with only one dependency (`tqdm`) that reliably reproduces the failure after about 3 minutes of runtime.

https://github.com/danwallach/arlo-e2e-noop

**Comment by rkooo567** [comment]
Thank you so much! I will try during this weekends!
