### ISSUE TITLE
Visionnet variable referenced before assignment

### ISSUE THREAD

**Issue by jdpena** [ray-project/ray#11038]
Hi, 

I'm trying to run MAPPO algorithm using PettingZoo's [Tiger-Deer environment](https://www.pettingzoo.ml/magent/tiger_deer), and I obtained the error, below. 

``` 
File "/home/python3.7/site-packages/ray/rllib/models/tf/visionnet.py", line 65, in __init__
    name="conv{}".format(i + 1))(last_layer)
UnboundLocalError: local variable 'i' referenced before assignment at time: 1.60107e+09
```
Taking a look at the file `visionnet.py`, it does appear like the variable should have been set in the for-loop #L29. The only way for it not to have been set is if `enumerate(filters[:-1], 1)` returned empty. The offending line is below. 

https://github.com/ray-project/ray/blob/8f79b4e45ee41565690c59769462c12208996c4a/rllib/models/tf/visionnet.py#L67

For reference, the obs shape for Tiger-Deer env is [9, 9, 146]. In the `model` configuration for running the Tune experiment, I set `conv_filters = [[128, [9, 9], 1]]`. If the issue is my conv_filters, could you please point me in the right direction?

I'm running `ray==0.8.7` and `PettingZoo==1.3.3` on Ubuntu 18.04.5 Bionic.

**Comment by sven1977** [comment]
@jdpena Yes, this seems like a bug. I guess we weren't thinking about these non-image yet image-like obs spaces when we wrote this loop (thinking that one would always use more than 1 conv layer). In your case, this is perfectly valid, though. Then again, more than 1 layers may still help here.
We'll provide a fix. ...

**Comment by sven1977** [comment]
Closing this.
PR has been merged:
https://github.com/ray-project/ray/pull/11330
