### ISSUE TITLE
Install ray from specific commit?

### ISSUE THREAD

**Issue by Karol-G** [ray-project/ray#11046]
Hi,

I want to install ray from the newest master commit. The documentation explains how to do it: https://docs.ray.io/en/latest/installation.html#installing-from-a-specific-commit. But I am unable to correctly determine the needed variables.

Hash: 
552ebdbedae7327b2e6f084c989bae6c1010f58d  (Should be correct)

Ray version: 
How do I know the ray version for the above commit?

Operating System: 
My OS is Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-42-generic x86_64). 
So is it "linux", "ubuntu" or "manylinux1_x86_64"?

Python version: 
cp38 (Should be correct)

Can someone help me out with the ray version and the os?

Best
Karol

**Comment by robertnishihara** [comment]
It should be similar to the filenames at https://pypi.org/project/ray/1.0.0rc2/#files!
