### ISSUE TITLE
[dashboard] SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#11069]
Dashboard throws a SyntaxError every 10 seconds when I create workers that more than the core number.
![image](https://user-images.githubusercontent.com/1586755/94423961-0d16a780-01bc-11eb-8049-7b8668ffb0ec.png)

**Comment by robertnishihara** [comment]
cc @mfitton

**Comment by mfitton** [comment]
Thanks for bringing this to my attention. I'll have a look for the cause today. We're imminently transitioning to a new dashboard backend (lots of code out for review right now), and I would expect the fix to come with the next release, which will have the new dashboard back-end code.

**Comment by Seraphli** [comment]
Ok, thanks
