### ISSUE TITLE
[Placement Group] APIs and feature parity between Python and Java APIs

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11062]
### Describe your feature request

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

@ffbin Can you fill up this?

**Comment by ffbin** [comment]
@rkooo567 Ok, no problem.

**Comment by rkooo567** [comment]
@ffbin What's the status of this?

**Comment by ffbin** [comment]
Java API lacks pg.ready API, i have submit a PR(https://github.com/ray-project/ray/pull/12499). cc @clay4444

**Comment by rkooo567** [comment]
I believe this is done
