### ISSUE TITLE
[rllib] PettingZoo's No-limit Texas Holdem environment compatibility

### ISSUE THREAD

**Issue by DoxakisCh** [ray-project/ray#11072]
Hello,

I am trying to use rllib's algorithms on PettingZoo's No-limit Texas Holdem environment. From what I understand in rllib's documentation, there is a PettingZooEnv class in order to make these environments compatible with rllib. But this class can be used only for agents that act simultaneously, and not for turn-based games like Poker or Chess, which fall under the classic category of PettingZoo's environments. Additionally, these games have also illegal moves that alter the action space in each step.

Therefore, is there any solution to this problem? Any workaround that would prove useful to this compatibility problem? Alternatively, is there any other library with the particular environment (No-limit Texas Holdem) that I could use instead with rllib?

Thank you in advance.

**Comment by ericl** [comment]
cc @justinkterry

**Comment by richardliaw** [comment]
cc @weepingwillowben
