### ISSUE TITLE
[rllib] questions about rollout fragment length and gae calculation in rllib

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#11077]
Hi, 

I have a simple question regarding rollout fragment length and gae. From my understanding, the rollout fragment length we set for PPO will determine how many steps back the return will be determined, or not?

**Comment by ericl** [comment]
That's correct, after that the return will be bootstrapped via value function estimation.

**Comment by AprilXiaoyanLiu** [comment]
Thanks for your response. In this case, it would be better to have rollout fragment length less than the max number of episode length, right? if we wanted to leverage TD(lambda). in this way, we don't have to wait until the end of episode to update the return. That is based on my understanding, the better way is to have rollout fragment length less than the max number of episode.  But from what I see in default config, the rollout fragment length is always very large. is there anything I missed there?  Hope this is the type of question we can ask here.
