### ISSUE TITLE
[rllib] how to change optimizer

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#11081]
Hello,

I'm still relatively new to rllib. I saw in one issues, it mentioned that different optimization algorithms may have different results on LSTM PPO. I wanted to try with different optimizer. I think the default optimizer for PPO is Adam based on what I see in torch_policy.py. Where should I change if I want to use RMSprop optimizer.  Thanks

**Comment by simonsays1980** [comment]
I would be happy to have this feature, as this enables us to replicate results from research papers more easily.
