### ISSUE TITLE
How to get Worker IP in "worker_start_ray_commands"? [autoscaler]

### ISSUE THREAD

**Issue by fahadh4ilyas** [ray-project/ray#11095]
## System Information

* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
* **Ray installed from (source or binary)**: source
* **Ray version**: 1.1.0.dev0
* **Python version**: 3.7.7

## Describe the Problem

In `ray/python/ray/autoscaler/local/example-full.yaml` every worker have identic `worker_start_ray_commands` but I want to modify it (adding custom resource using `--resources` flag) so it will be unique for every worker by using their own IP host. But there is no documentation about that. Is there a way to do that?

**Comment by rkooo567** [comment]
cc @allenyin55
