### ISSUE TITLE
AttributeError: 'ExperimentAnalysis' object has no attribute 'get_best_checkpoint'

### ISSUE THREAD

**Issue by LianShuaiLong** [ray-project/ray#11100]
### What is the problem?
when i type following command in the terminal:
       python pbt_convnet_function_example.py
i encountered problem :AttributeError: 'ExperimentAnalysis' object has no attribute 'get_best_checkpoint'
can you help me?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray_version:0.8.7
python:3.6.7
torch:1.6.0
torchvision:0.2.1
os:ubuntu16.04.5 LTS

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Are you using ray_version 0.8.7 while trying to use the master branch examples? If so, consider switching to the 0.8.7 branch and running those examples.

**Comment by LianShuaiLong** [comment]
> Are you using ray_version 0.8.7 while trying to use the master branch examples? If so, consider switching to the 0.8.7 branch and running those examples.

thanks for your reply, i just tried switching to the 0.8.7 branch ,however the problem still exists:

![image](https://user-images.githubusercontent.com/23699530/94531904-bec2e080-026f-11eb-9621-378ae88586a3.png)

**Comment by LianShuaiLong** [comment]
> Are you using ray_version 0.8.7 while trying to use the master branch examples? If so, consider switching to the 0.8.7 branch and running those examples.
thanks for your reply,
