### ISSUE TITLE
Why ray started more process than I set

### ISSUE THREAD

**Issue by dxu23nc** [ray-project/ray#11101]
I want to get the learning time of the Q-network.  I set the worker_num=1. 
Here is my script.
`import ray
from ray import tune

ray.init()
tune.run(
    "DQN",
    stop={"timesteps_total": 10000000 },
    config={
        "env": "Breakout-v0",
        "num_workers":1, 
        "lr": 0.00025,
        "eager": False,
        "double_q": False,
        "dueling": True,
        "num_atoms": 1,
        "noisy": False,
        "prioritized_replay": False,
        "n_step": 4,
        "target_network_update_freq": 10000,
        "hiddens":[512],
        # "lr": .0000625,
        "adam_epsilon": .00015,
        "learning_starts": 100,
        "buffer_size": 1000000,
        "sample_batch_size": 4,
        "train_batch_size": 32,
	    # "model":{"fcnet_hiddens":tune.grid_search([64])},
        "schedule_max_timesteps": 2000000,
        "exploration_final_eps": 0.01,
        "exploration_fraction": .1,
        "prioritized_replay_alpha": 0.5,
        "beta_annealing_fraction": 1.0,
        "final_prioritized_replay_beta": 1.0,
        "num_gpus_per_worker": 0.08,
        "timesteps_per_iteration": 10000,
    },
    local_dir="/home/dxu23/ray_results_xd/ri_train/",
    checkpoint_at_end=True,
    # checkpoint_freq=10,
    name="interference_test",
)
`
I used "top" to monitor the process. And I saw a lot of processes. Most of them are Ray:IDLE. 

![Screen Shot 2020-09-29 at 4 16 13 PM](https://user-images.githubusercontent.com/59181864/94531400-1ad93500-026f-11eb-8274-3e686ade4914.png)

Why ray needs to start so many workers.

**Comment by rkooo567** [comment]
`ray.init` starts IDLE processes. It creates as many as the number of your virtual CPUs when you don't specify any arg. If you want only a single IDLE process, you can specify `ray.init(num_cpus=1)`
