### ISSUE TITLE
Make it easier to clean the build directory

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1111]
Currently it is not that easy to get a clean build (partly due to our own copy of pyarrow which lives in pyarrow_files); we should have a shell script that cleans the build directory.

This came up when building Ray with Python 3, switching to building Ray with Python 2 (to fix some Jenkins test) and rebuilding for Python 3. There was some state left in the build directory which was hard to track down.

cc @royf

**Comment by robertnishihara** [comment]
One option is to do `git clean -f -f -x -d`.

**Comment by robertnishihara** [comment]
Fixed by #1114.
