### ISSUE TITLE
[autoscaler] Limit max launch concurrency per node type

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#11116]
(todo here): https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/autoscaler.py#L218

This solves the problem of launching too many nodes, e.g.:

```
for _ in range(10000):
   f.remote()   # f is short running task
```

With the current multi node type autoscaler, this will actually scale up to a large number of nodes (e.g., 100s) to allow all tasks to run at once. Ideally we'd scale up incrementally in case the tasks finish quickly. For example, start with 5 concurrent launches, then maybe more as the cluster size increases.

This should be per-node-type so that one node type doesn't block launch of others.

This will allow enabling @wuisawesome 's fix to here: https://github.com/ray-project/ray/issues/10872 (which properly tracks task queue length)

This is the second pre-req for removing the legacy algorithm (#10817)

**Comment by wuisawesome** [comment]
One interesting thought: this rate limiting looks a lot like congestion control in networking.

Aggressive auto scaling => multiplicative increase/additive decrease 

Conservative autoscaling => additive increase/multiplicative decrease
