### ISSUE TITLE
Add ray.list_named_actors() to API

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#11112]
### Describe your feature request

It is already possible to give actors a name: https://docs.ray.io/en/master/actors.html#named-actors and to retrieve the actor handle via `ray.get_actor("some_name")`.
It would however be very handy to have some kind of `ray.list_named_actors()` API method to get a list/dict of all currently available named actors.
It can be useful for:
* Better debugging
* Retrieving lost actors, e.g. after an application crash were actor handles are lost and not all actor names are 100% deterministic
* Cleaning up actors
* ...

Imagine you could only use `htop` if you remembered all your process names :)

Thanks for taking this into consideration!

BR, Pieterjan
@rkooo567

**Comment by kishansagathiya** [comment]
Hi @rkooo567, Have you started working on this? 
I am trying to do this, and wanted to confirm the flow with you.

- All the actors are stored in `registered_actors`  (src/ray/gcs/gcs_server/gcs_actor_manager.cc), which could be used to list actors.
- An rpc method could be created say `ListActors`, which would get all the actors using `GetRegisteredActors` and return useful information about actors from it.

Does that seem right?

**Comment by rkooo567** [comment]
Oh, I was thinking to implement this in this weekend. Is it a hard blocker for you guys? 

There's already an API called `ray.actors()`, which shows a list of actors in the cluster. We can probably add a name field there for actors that have names.

**Comment by PidgeyBE** [comment]
Hey @rkooo567 
@kishansagathiya  is in our team, we asked him to start working on this as we could definitely use this functionality and would love to have it in the next release.
