### ISSUE TITLE
Ray only uses one worker

### ISSUE THREAD

**Issue by sbuschjaeger** [ray-project/ray#11110]
Hi,

For some weird reason I cannot get Ray to use more than one worker at a time. I manually set-up a cluster environment via 

    ray start --head -port=6379 

on my master (20 CPUs, 1 GPU). On three slaves I ran

    ray start --address='192.168.2.14:6379' --redis-password='5241590000000000'

exactly how Ray told me to (also 20 CPUS, 1 GPU per worker) . I verified that "192.168.2.14" is the correct IP address here and all machines can access the master, e.g. via SSH. 

My driver code is the following:

    @ray.remote 
    def ray_eval_model(modelcfg):
        # Train and evaluate a model which is configured in modelcfg

    basecfg = {
        "ray_head": "auto",
        "redis_password":"5241590000000000",
        "num_cpus" : 5,
        "num_gpus": 1
        # and some more configs
    }
    models = [] # Define a list of models / parameter combinations to train and evaluate
    ray.init(address=basecfg.get("ray_head", None), redis_password=basecfg.get("redis_password", None))
    futures = [ray_eval_model.options( 
                        num_cpus=modelcfg.get("num_cpus", 1),
                        num_gpus=modelcfg.get("num_gpus", 1)
                    ).remote(modelcfg) for modelcfg in models ]

    while futures:
            result, futures = ray.wait(futures)
            eval_return = ray.get(result[0])
            # Do more stuff

The ray dashboard correctly shows me all worker nodes (including 20 cpus + 1 gpu for each node). If I understand the config correctly, I am requesting 5 CPUs + 1 GPU, so each worker should execute one model. However, executing the above driver code runs the first experiment on the head (where I execute the script), but does not schedule any other jobs on any other workers. The log-file shows some output, but no errors. 

I already tried different ray version (`0.8.7` , `0.8.6` and `0.8.5` without any luck)

**Comment by rkooo567** [comment]
You should specify GPU in `ray start --address="" --num_gpus=1`. Otherwise, remote tasks are not scheduleable on that node because it doesn't have the gpu resource that is needed to schedule your tasks.
