### ISSUE TITLE
[Multi Tenancy] Remove the feature flag and old code path.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11136]
### Describe your feature request

There's an already open PR from @kfstorm. After a single release cycle, if we validate the feature works well, we should remove the feature flag and the old code path. https://github.com/ray-project/ray/pull/10573

**Comment by rkooo567** [comment]
cc @kfstorm What's the progress for this issue?

**Comment by kfstorm** [comment]
@rkooo567 Thanks for the reminder. I hadn't had time to work on it. But I think I can update the existing PR and make it build pass within this week.
