### ISSUE TITLE
Support Python 3.7 and build wheels.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1115]
This also involves
- Extending https://github.com/ray-project/ray/blob/master/python/build-wheel-macos.sh to build wheels for Python 3.7 (note that this will cause our MAC_WHEELS Travis build to definitely time out, so we need to figure out what to do about that (see #1110).

**Comment by danielsuo** [comment]
While splitting out MacOS wheels, I thought I'd give 3.7 a try (why not, I was feeling alive). The plumbing in #1205 works, but the 3.7 build fails:

- Cython [claims](https://github.com/cython/cython/issues/1955) their latest release will build on CPython master, but I get fails for both Travis and locally using CPython 3.7a2
- The ```manylinux``` docker we're using doesn't have ```cp37-cp37m``` yet, which makes sense, though we probably want to work with the Arrow folks to put a beta / rc 3.7 into their image over the next few months

FYI: final release is [2018-06-15](https://www.python.org/dev/peps/pep-0537/#release-schedule)

**Comment by robertnishihara** [comment]
Related to apache/arrow#1125

**Comment by xhochy** [comment]
@danielsuo @robertnishihara if we can get a docker container of any linux distro that has a built version of Python 3.7, we should be able to set up a pipeline to build Arrow & Ray. apache/arrow#1125 is probably more related to some weird in the system setup than Python 3.7 itself, sadly I cannot reproduce it with Python 3.6 on ArchLinux so I'm struggling to narrow down the problem.

**Comment by danielsuo** [comment]
Would [these](https://hub.docker.com/_/python/) work?

**Comment by xhochy** [comment]
@danielsuo they look like a good option.

**Comment by danielsuo** [comment]
Another option: fork the ```manylinux``` image, add 3.7, and make a failed build for 3.7 not fatal.

That said, it may be cleaner to have a separate workflow for 3.7 that we simply remove / replace with updated a ```manylinux``` image when the time comes. Is that what you had in mind?

**Comment by austinnichols101** [comment]
Bump.  Python 3.7 is out (27-Jun).

**Comment by robertnishihara** [comment]
Yeah, we should do this for the next release (0.6).

**Comment by timonbimon** [comment]
do you already have a rough idea when 0.6 will be released? :)

**Comment by robertnishihara** [comment]
@timonbimon our more aggressive timeline is roughly 1 month.

**Comment by timonbimon** [comment]
awesome, thanks for the amazing work :)

**Comment by sadatnfs** [comment]
Looks like Miniconda's latest (default) version download 3.7 now. I feel a lot of installs breaking :(

**Comment by pcmoritz** [comment]
Good point, thanks for bringing that up. It's in the works here: https://github.com/ray-project/ray/pull/2546, we can prioritize merging it soon.

**Comment by robertnishihara** [comment]
Fixed by #2546.

**Comment by robertnishihara** [comment]
The wheels still haven't been uploaded to PyPI, but you can get them by following the instructions at https://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray and modifying the URL to use 3.7.

**Comment by manugarri** [comment]
any updates on this? Would like to be able to use ray on a windows machine. Maybe there is a conda binary available?

**Comment by robertnishihara** [comment]
@manugarri for Windows, the relevant issue is https://github.com/ray-project/ray/issues/631. We're working on it, but it isn't ready yet.

**Comment by manugarri** [comment]
got it, thanks!
