### ISSUE TITLE
[tune] Can an experiment run other experiments?

### ISSUE THREAD

**Issue by nscotto** [ray-project/ray#11157]
I would like to do an experiment for model selection which use `ray.tune` for hyper parameter selection of each model.

Is it possible? On the same machine?
How to work with `ray.init` in that case?

**Comment by sumanthratna** [comment]
@richardliaw not sure if this feature already exists—if it doesn't, I personally think this is an important feature to implement

@nscotto as a temporary workaround, I think you can use [nested configs](https://docs.ray.io/en/master/tune/tutorials/overview.html#how-can-i-used-nested-conditional-search-spaces), e.g.:
```python
config = {
    "model": tune.choice("rnn", "lstm"),
    "rnn": {
        "seq_length": tune.uniform(1, 30),
    },
    "lstm": {
        "num_layers": tune.uniform(12, 24),
    },
}
# ...
def trainable(config, checkpoint_dir=None):
    model_params = config[config["model"]]
    # if config["model"] == "rnn", then model_params will be {"seq_length": some_int}
    # if config["model"] == "lstm", then model_params will be {"num_layers": some_int}
```
(note that this an example for usage; these hparams probably not appropriate!)
