### ISSUE TITLE
[New Scheduler] Light heartbeats

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#11168]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
@wuisawesome please remove triage label for these one issues you're using for work-tracking

**Comment by wuisawesome** [comment]
whoops sorry, there's probably a bunch of these i need to change

**Comment by wuisawesome** [comment]
I think this was closed by mistake? It doesn't look like it's implemented yet.

**Comment by ericl** [comment]
I think this is fixed.

**Comment by wuisawesome** [comment]
It doesn't error, but it isn't implemented. We still send every resource on every heartbeat (see here https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/cluster_task_manager.cc#L275)
