### ISSUE TITLE
Built-in boto3 client ActorPool

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#11177]
I've struggled to create actor pools which effectively ingest million-scale files from S3 into Ray. I've tried to follow the AWS recommended design patterns and still do not get anywhere close to their advertised performance, or near the bandwidth limits of my EC2 instances. 

It would be very helpful if there was a built-in boto3 ActorPool which can use my whole cluster's bandwidth for fetching objects from S3.

cc @amogkam @wuisawesome

**Comment by edoakes** [comment]
cc @wuisawesome

**Comment by thomasdesr** [comment]
cc @pdames

**Comment by richardliaw** [comment]
You can now use ray datasets to achieve the above.
