### ISSUE TITLE
[Serve] Backend Actor can't scale up to 2 replicas if it uses an endpoint handle internally

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#11178]
### What is the problem?
A backend using an endpoint handle internally appears to hang when `client.update_backend_config` is called to change the number of replicas from 1 to 2.
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.0.0, Python 3.6, Mac OS (Also Py3.7 and Linux)

### Reproduction (REQUIRED)
There are three 
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```python
import ray
from ray import serve
from ray.serve import BackendConfig

ray.init()
client = serve.start() # serve.start(detached=True) fixes it

def hello_world(_):
    return b"Hello World"

class ForwardActor:
    def __init__(self):
        # client = serve.connect() fixes it
        self.handle = client.get_handle("hello_world") # replacing this with self.handle = 1 fixes it

    def __call__(self, _):
        return 1 

client.create_backend("hello_world", hello_world)
client.create_endpoint("hello_world", backend="hello_world")

client.create_backend("ForwardActor", ForwardActor)
client.create_endpoint("ForwardActor", backend="ForwardActor")

forwarders_config = BackendConfig(num_replicas=2) # replacing this with num_replicas = 1 fixes it

#Hangs on this line
client.update_backend_config("ForwardActor", forwarders_config)
```
Actually, the same problem happens if you set the num_replicas to 2 right from the start in `create_backend`.

This is the line where it hangs: https://github.com/ray-project/ray/blob/master/python/ray/serve/controller.py#L435

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
This looks pretty problematic. My initial guess would be that there's a deadlock between the code that starts the handle in the backend worker (which is calling into the controller) and the code that waits for the new replicas to start up.

**Comment by simon-mo** [comment]
I will try to isolated it into a Ray Core issue. Seems like something to do with actor ref counting

**Comment by simon-mo** [comment]
Minimal version from Serve:
```python
import ray
from ray import serve

ray.init()
client = serve.start()

class ForwardActor:
    def __init__(self):
        self.client = client

client.create_backend("ForwardActor", ForwardActor)
```
