### ISSUE TITLE
Dashboard is reading memory and other resources available on host and not virtual resources

### ISSUE THREAD

**Issue by jsanjay63** [ray-project/ray#11172]
### What is the problem?
I setup Ray kubernetes cluster following this doc: https://docs.ray.io/en/latest/cluster/kubernetes.html and using port forwarding, I was able to access Ray dashboard.
RAM metric values showed in dashboard are too huge(range of 180 to 350 GB per worker). But, I have configured in the config file to use only 1G memory per worker. It seems dashboard is reading memory available on host and not virtual resources.

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 1.0.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
@mfitton we should collect all of these docker-related issues and try to address them soon.

**Comment by Bhavya6187** [comment]
@DmitriGekhtman Any updates for this? Ray demo on k8s fall flat because of this dashboard bug :(

**Comment by DmitriGekhtman** [comment]
cc @rkooo567 

I've identified the problematic code, but haven't had a chance to address the issue. I'll attack this early next week.

**Comment by DmitriGekhtman** [comment]
Here's what the dashboard currently looks like when I launch a head and two workers on Minikube:
<img width="1778" alt="Screen Shot 2021-03-04 at 8 07 38 AM" src="https://user-images.githubusercontent.com/62982571/110009432-dc3e1f80-7cd1-11eb-9bd6-2f9d385ec95e.png">

Displaying correct memory usage (the specific topic of this issue) should be fairly straightforward.

Making the rest of the output more meaningful maybe a bit more subtle / might require a bit of external tooling.
Maybe the Kubernetes metric server could be used to track CPU usage? https://github.com/kubernetes-sigs/metrics-server
Thoughts/recommendations @yiranwang52 @edoakes @simon-mo ?

**Comment by yiranwang52** [comment]
I don't think k8s could know about per task data.

**Comment by edoakes** [comment]
The per-task metrics should still be fine. I think the main problem will be the per-node CPU/memory. Memory should be addressable, for CPU we could either do a simple average of per-worker memory usage or else possibly base it off of the cgroup request/limit

**Comment by DmitriGekhtman** [comment]
^ Expanded the scope of this issue.

**Comment by DmitriGekhtman** [comment]
Might just look to replicate docker client's logic..
https://github.com/docker/cli/blob/850845adabaf9845c1c03a9556f8f167ed117187/cli/command/container/stats_helpers.go#L166

**Comment by AmeerHajAli** [comment]
Since we resolved the CPU and memory, should we close this? @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Cpu, memory, and uptime fixed.
GPU already fine except for some non-K8s-specific issues documented here https://github.com/ray-project/ray/issues/14664.

I'll briefly look into removing disk altogether, as it's not too meaningful in this context -- k8s node disk usage should be monitored by other means.

At that point it will look pretty good.
There are a couple of other items that should be checked for consistency -- I'll come back to these later and in the meantime let's keep this open.
T

**Comment by edoakes** [comment]
Thanks for taking initiative on this @DmitriGekhtman!

**Comment by scottsun94** [comment]
cc: @alanwguo @DmitriGekhtman For the new default dashboard (previous experimental dashboard), do we still have those issues?

**Comment by DmitriGekhtman** [comment]
This issue has been resolved. I'll go ahead and close it.
