### ISSUE TITLE
ray dashboard doesn't work when using docker

### ISSUE THREAD

**Issue by noe-mis** [ray-project/ray#11171]
Since dashboard only sends port_forward and cmd=None, it crashes on this line. The line above would require something like:
`if run_env == "auto" and cmd is not None:`

https://github.com/ray-project/ray/blob/0d5b09f42646592222c5c4ade333ee9bb8807a6e/python/ray/autoscaler/_private/command_runner.py#L537

**Comment by rkooo567** [comment]
cc @mfitton

**Comment by mfitton** [comment]
I think this issue is still present based on a look at the code. Sorry it slipped off my radar @noe-mis
@ijrsvt would you be willing to help me fix this? I'm unfamiliar with the arguments that are causing this issue. Maybe we can pair on it.
