### ISSUE TITLE
[Core] Internal config is not set within the gcs_server process

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11182]
### What is the problem?

Currently, the global internal config is set when the raylet inside a head node starts up. This causes an issue that gcs_server itself won't have the correct internal config.

We should fix this by storing this value inside the gcs server.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ijrsvt** [comment]
Issue does not exist anymore!
GCS receives the correct configuration because the user-specified config is **available on the head node**. The only nodes that need to use GCS to retrieve the SystemConfig are non-head nodes.
