### ISSUE TITLE
[Core] Confusing warning message when scheduling is blocked.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11191]
### Describe your feature request

From https://github.com/ray-project/ray/issues/11179.

When running this script, 
```python3
import ray

ray.init()

actor_size = 0.7

@ray.remote(num_cpus=actor_size)
class TestActor():
    def __init__(self):
        pass

actor_list = []
for i in range(int(ray.cluster_resources()["CPU"] // actor_size)):  # mine is a 4 CPU system
    actor_list.append(TestActor.remote())
```

This raises this warning

```
The actor or task with ID ffffffffffffffff88866c7d01000000 is pending and cannot currently be scheduled. 
It requires {CPU: 0.700000} for execution and {CPU: 0.700000} for placement, but this node only has remaining 
{node:192.168.0.199: 1.000000}, 
{accelerator_type:GTX: 1.000000}, 
{CPU: 1.200000}, 
{memory: 6.933594 GiB}, 
{GPU: 1.000000}, 
{object_store_memory: 2.392578 GiB}. 
In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

And scheduling is blocked. It happens because we use resourceIdSet for CPU resources. Simply put, we won't allow resources to be allocated in 2 cpus concurrently, and that blocks scheduling. For example, in the above example,

num_cpus = 4, A, B, C, and D

5 actors requiring 0.7 CPUs

actor 1 requires 0.7 CPU for CPU A
actor 2 requires 0.7 CPU for CPU B
actor 3 requires 0.7 CPU for CPU C
actor 4 requires 0.7 CPU for CPU D
actor 5 cannot be scheduled because there are only 4 of 0.3 CPU id sets.

This behavior is extremely confusing for end users because the warning shows tasks or actors cannot be scheduled although there are enough resources (which just sum up available resource id sets, which in this case is 1.2).

We should either 

1. Improve error message to explain why this is not scheduled.
2. Do not allow 0.7 CPUs in this scenario.
3. Make CPU resources not use resource Id set (I think it makes sense not to because there could be single tasks that use multiple CPUs? ex, multi-threading). This doesn't solve GPU problems (but people may not require 0.7 GPUs most of time anyway)
4. Any other clever way to avoid user confusion.

**Comment by rkooo567** [comment]
cc @ericl @wuisawesome

**Comment by ericl** [comment]
@wuisawesome I believe you proposed (3) before right? That seems the most sensible solution to me, since CPUs are generally multiplexed and there are other ways to achieve CPU assignment even if we don't track ids.

**Comment by wuisawesome** [comment]
Yup this is #10818

**Comment by rkooo567** [comment]
duplicated issu
