### ISSUE TITLE
[Placement Group] Send placement group load through pull-based endpoints.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11204]
### Describe your feature request

Currently, the placement group load and resource shapes are reported to autoscaler through heartbeats.

Since they are not useful for every other raylet, it adds unnecessary overhead to the cluster. We should just add a pulling endpoint to the GCS server so that autoscaler can pull these data directly.

**Comment by rkooo567** [comment]
@ericl This is closeable right?

**Comment by rkooo567** [comment]
@WangTaoTheTonic It is okay to close this issue right?

**Comment by WangTaoTheTonic** [comment]
Yeah, this can be closed! Pg load are retrieved by pulling!
