### ISSUE TITLE
Need to get back intermediate results to driver

### ISSUE THREAD

**Issue by hrishikeshvganu** [ray-project/ray#1120]
I'm using ray  on a list of strings on which I apply several functions in succession. When I tried to pass lists returned by each remote function to it's successor ( without using `ray.get`) inside the functions I get an empty result.
My code looks like:
```
list1=f1.remote(list0)
list2=f2.remote(list1)
driver_list=ray.get(list2)

```
Shouldn't I just be able to pass lists of object IDs (e.g: `list1`) into the intermediate functions?

If I use `f2.remote(ray.get(list1))` this work perfectly

**Comment by robertnishihara** [comment]
Can you post the full example, so I can run it and see?

Is `list1` an object ID that refers to a list? Or is it a list of object IDs. If it is a list of object IDs, e.g., you defined `f1` with something like `@ray.remote(num_return_vals=3)`, then you may need to unpack the list of object IDs before passing it into `f2`, e.g., like `f2.remote(*list1)` if you want the objects to be unpacked under the hood.

**Comment by robertnishihara** [comment]
Closing for now since this was a while ago. Feel free to reopen if it's still a problem!
