### ISSUE TITLE
[Tune] Allow for Hierarchical Search Spaces in Ray1.0

### ISSUE THREAD

**Issue by timothynest** [ray-project/ray#11216]
[Tune] @richardliaw 

Both hyperopt and dragonfly documentation demonstrate applications with hierarchical search spaces. This sort of framework is beneficial for several reasons. Consistency of ray.tune between search spaces added as of  Ray1.0 is a very nice feature, but search spaces such as:
```
space4svm = {
    'C': hp.uniform('C', 0, 20),
    'kernel': hp.choice('kernel', [
            {'ktype': 'linear'},
            {'ktype': 'poly', 'degree': hp.lognormal('degree', 0, 1)},
            ]),
    'gamma': hp.uniform('gamma', 0, 20),
    'scale': hp.choice('scale', [0, 1]),
    'normalize': hp.choice('normalize', [0, 1])
}
HyperOptSearch(search_space=space4svm)
```
...are still unsupported. For example, when testing the hyperopt example provided at: https://docs.ray.io/en/releases-1.0.0/tune/examples/hyperopt_example.html, I added a the following config space as a toy example:

```
 tune_kwargs = {
        "num_samples": 4 ,
        "config": {
            "steps": 100,
            "width": tune.uniform(0, 20),
            "height": tune.uniform(-100, 100),
            # This is an ignored parameter.
            "activation": tune.choice(
                [
                    None,
                    {
                        "type":"relu",
                        "percent_ranking": tune.uniform(0,10),
                        "fun": tune.choice(["foo","bar"])},
                    {
                        "type":"tanh",
                        "percent_ranking": tune.uniform(0,10),
                        "fun" : tune.choice(["lorem","ipsum"])
                    }
                ])
    }}
```
when I run the same example (adapting functions to accommodate the new structure), ray does not properly cast the tune parameters inside the activation choices into e.g floats or strings. Instead, the percent ranking item is displayed as: <ray.tune.sample.Float object at 0x7fa4f02fdb70> and attempting to cast or add values yields something like: TypeError: unsupported operand type(s) for +: 'float' and 'Float'

It would be really nice to have some handling for this kind of space, even if it's limited to specific search algorithms.

**Comment by richardliaw** [comment]
cc @krfricke

**Comment by krfricke** [comment]
We added support for this in #11431.

Please note that the example you gave is not working with pure hyperopt - it will complain about duplicate parameter names `fun` and `percent_ranking`. I.e.

```
    space4svm = {
        'C': hp.uniform('C', 0, 20),
        'kernel': hp.choice('kernel', [
            {'ktype': 'linear'},
            {'ktype': 'poly', 'degree': hp.lognormal('degree', 0, 1)},
        ]),
        'gamma': hp.uniform('gamma', 0, 20),
        'scale': hp.choice('scale', [0, 1]),
        'normalize': hp.choice('normalize', [0, 1]),
        "activation": hp.choice("activation",
            [
                None,
                {
                    "type": "relu",
                    "fun": hp.choice("fun", ["foo", "bar"])},
                {
                    "type": "tanh",
                    "fun": hp.choice("fun", ["lorem", "ipsum"])
                }
            ])
    }
    best = fmin(easy_objective, space4svm, algo=tpe.suggest, max_evals=100)
```

leads to `hyperopt.exceptions.DuplicateLabel: fun` even when used in pure hyperopt without Ray Tune.

**Comment by krfricke** [comment]
It would be great if you could try it out and see if it solves your problem @timothynest :-)

**Comment by timothynest** [comment]
Hi Kai! I'm testing out your updates now. However I should mention that the major appeal of the new intercompatibility of various search algorithms with tune primitives was that it would in theory allow us to easily shift between search algorithms using a single config. These changes are nice for  hyperopt, but ultimately was hoping it would allow me to run the same space with BOHB and Dragonfly. In my case dragonfly fails because categorical variables are not supported, and BOHB (which presents additional problems due to the requirement of conditionals in ConfigSpace) likewise fails.

**Comment by krfricke** [comment]
I added a couple of follow-up issues for these. I hope to get to BOHB soon. Dragonfly would be a little lower priority. By the way, do you require hierarchical search spaces here, too (as I don't think they're supported by Dragonfly out of the box)? 

If so, we would probably need to think about a general approach to introduce hierarchical search spaces to algorithms. It might also be that some libraries don't support that - e.g. how does dragonfly fit an acquisition function if some of the parameters are missing? I can think of theoretical solutions here, but these might require some actual research.
