### ISSUE TITLE
[tune] Incomplete schedulers dict in tune.py

### ISSUE THREAD

**Issue by ttumiel** [ray-project/ray#11212]
### What is the problem?

The `_SCHEDULERS` dict in `tune/tune.py` only has 4 of the available schedulers. As a result only these 4 are available in rllib's train.py which uses the dict (in the `_make_schedulers` function)

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.5, but still present in master.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

See `rllib/train.py`, which uses the `_make_schedulers` function from tune.py.

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Hi @ttumiel thanks for raising this; would you be willing to contribute a fix?

Let me know - thanks in advance!

**Comment by ttumiel** [comment]
Sure!
