### ISSUE TITLE
Using gpu for inference ( rollout )

### ISSUE THREAD

**Issue by qorbanpour** [ray-project/ray#11220]
I was trying to figure out how I can distirbute all gpus available in my cluster to  my workers during rollout ( inference ) . I would like the   inference  to be executed  on gpus completely or partially for my workers (num_gpus_per_worker ? )  and   I  was not successful at it . I tried different combination of configurations and one of the configuration is as follow but it doesn't work as I get cuda out of memory  error. Btw  I have two cluster in my nodes  and total 3 gpus . two gpus in one node and third gpu on second node .  I was wondering if rllib  rollout supports this  feature !

One of my command was as follow : 

RAY_ADDRESS=auto **rllib rollout** /root/ray_results/IMPALA_PongNoFrameskip-v4_2020-10-05_16-49-13uggagx_1/checkpoint_31/checkpoint-31 --run IMPALA --env PongNoFrameskip-v4 --steps 5000 --config '{"num_workers":30  , "num_envs_per_worker":3 , "num_gpus":3,   "num_gpus_per_worker":0.05}'

changing num_gpus to 0  or removing num_gpus   didn't help  .  

Warmest,

**Comment by qorbanpour** [comment]
@ericl  can you shed some light on this topic ! I would appreciate that . Thank you .

**Comment by ericl** [comment]
> cuda out of memory error

This is probably since your model is fairly large and you're packing up to 20 workers per GPU with `"num_gpus_per_worker":0.05`. I would recommend increasing this to num_gpus_per_worker: 0.5 or 1. Note that the num_gpus setting only affects the learner not the rollout workers.
