### ISSUE TITLE
[ray] [bazel] build failure, error --experimental_ui_deduplicate unrecognized

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#11237]
### What is the problem?

When trying to build ray from source I am getting the following output:

<details>
  <summary>Error</summary>
  
  ```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Reading rc options for 'build' from /home/acxz/vcs/git/github/acxz/pkgbuilds/python-ray/src/ray-ray-1.0.0/.bazelrc:
  'build' options: --enable_platform_specific_config --action_env=PATH --compilation_mode=opt --experimental_ui_deduplicate --per_file_copt=\.pb\.cc$@-w --per_file_copt=-\.(asm|S)$,external/.*@-w --per_file_copt=-\.(asm|S)$,external/com_github_grpc_grpc/.*@-DGRPC_BAZEL_BUILD --http_timeout_scaling=5.0 --verbose_failures
ERROR: --experimental_ui_deduplicate :: Unrecognized option: --experimental_ui_deduplicate
Traceback (most recent call last):
  File "setup.py", line 450, in <module>
    setuptools.setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 443, in run
    return pip_run(self)
  File "setup.py", line 352, in pip_run
    build(True, BUILD_JAVA)
  File "setup.py", line 309, in build
    return bazel_invoke(
  File "setup.py", line 195, in bazel_invoke
    result = invoker([cmd] + cmdline, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '--', '//:ray_pkg']' returned non-zero exit status 2.

  ```

</details>

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 1.0.0
python: 3.8.5
gcc: 10.2.0
bazel: 3.5.0
os: Arch Linux

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

The above does not apply since this is a build issue.

**Comment by acxz** [comment]
Related issues:
https://github.com/ray-project/ray/discussions/9308
https://github.com/ray-project/ray/issues/10774

**Comment by rkooo567** [comment]
I guess your bazel version is not correct? I am using `bazel 3.2.0`

**Comment by acxz** [comment]
Yep seems that in the later bazel releases `--experimental_ui_deduplicate` has been removed.

**Comment by rkooo567** [comment]
We explicitly said the supported version of bazel is just 3.2.0 (https://github.com/ray-project/ray/blob/ce96b03b07a4a4bdd851aa84493c616cd291aff2/python/setup.py#L31). We should probably improve our documentation or error handling, but I don't consider this a bug. Let me add a doc tag here.

**Comment by rkooo567** [comment]
Task: Specify a bazel veresion in our doc.

**Comment by acxz** [comment]
I see, in any case I dont think my PR hurts, if anything it allows Ray to build on later bazel versions as well which I am sure will eventually be needed.

**Comment by rkooo567** [comment]
Oh, I didn't realize you pushed a PR! Thanks for doing that! 

One concern I have is that when people use 3.2.0, this flag will be on again. Do you know what the flag is exactly about? 

cc @simon-mo @mehrdadn Did you guys know why we added this flag in the first place? It seems to be off by default in bazel >= 3.5

**Comment by rkooo567** [comment]
I'd love to merge the PR, but let me verify this is fine from people who are familiar with our bazel config! Thanks for the contribution again :)

**Comment by mehrdadn** [comment]
@rkooo567 I think I added it for cleaning up the Bazel output. But you can remove it. It seems to have been removed in https://github.com/bazelbuild/bazel/commit/a6935cd0857a2008f7957b663ba1c7364ee9c0dc

**Comment by rkooo567** [comment]
Awesome! @acxz we will merge the PR shortly. Thanks again for the contribution!
