### ISSUE TITLE
[Doc] Documentation website points to master by default (not documentation of latest stable release)

### ISSUE THREAD

**Issue by deepaks4077** [ray-project/ray#11234]
# What is the problem?

The documentation website points to the master version and not latest:

https://docs.ray.io/ takes you to https://docs.ray.io/en/master/

The documentation link on https://ray.io/ takes you to https://docs.ray.io/en/latest/

Shouldn't https://docs.ray.io/ should take you to https://docs.ray.io/en/latest/ (since this is the documentation for the latest stable release)?

**Comment by richardliaw** [comment]
Hmm, is consistency the problem? Should we make `ray.io` point to `master` too?

**Comment by deepaks4077** [comment]
I thought ray.io should point to the latest release branch? Shouldn't the default documentation website be for the latest stable release?
