### ISSUE TITLE
[rllib] clarification on number or workers

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#11244]
Follow up on this https://github.com/ray-project/ray/issues/8825
Let's say if the rollout_fragment_length=100 and train_batch_size=1000.
We have two scenarios:
First scenario, number of workers = 5, num_envs_per_worker = 1
Second scenario, number of workers = 1, num_envs_per_worker = 1
With this example, how does rllib function?
For the first scenario, is it that the rllib collects 2 fragments of 100 * 5 and concatenate together? Or the each worker will collects 10 fragments of 100 steps so we have train batch size of 1000 * 5?
For the second scenario, is it that the rllib will collect 10 fragments of 100 steps, and concatenate to 1000?

**Comment by ericl** [comment]
Let's assume the PPO algorithm (so synchronous, no async):
- 1st scenario: 100 * 5 is only 500, so rllib will continue collecting until we get to 1000 (2 * 100 * 5).
- 2nd scenario: 100 * 1 is only 100, so rllib will continue collecting until we get to 1000 (10 * 100 * 1).

**Comment by AprilXiaoyanLiu** [comment]
Thanks
