### ISSUE TITLE
redis client on Windows error - Expected 1 Redis shard address, found 2

### ISSUE THREAD

**Issue by amitmeel** [ray-project/ray#11246]
### What is the problem?
**Ray** : 1.0.0
**Python**: 3.7.2
**OS**: Windows 10
____________________________________________________________________________________________________________________________
after initializing the ray with `ray.init()`, i'm getting an http url to open the Ray Dashboard. but when trying to open in the Browser, getting  "ERR_CONNECTION_REFUSED" Error.
Also i can see some logs in output node as shown below:

![94943184-e8406e00-04f4-11eb-9015-83748a2bf9f3](https://user-images.githubusercontent.com/32540863/95287865-9f860d80-0884-11eb-8b22-e0c0fd84e580.png)

Since Ray dashboard does not support the Windows platform. It's still odd to see the type of logs I can see on the output terminal. Hence raising an issue as suggested by @richard4912.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ yes] I have verified my script runs in a clean environment and reproduces the issue.
- [yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mattip** [comment]
Closing, the dashboard now works on windows. Please reopen if the problem still occurs.
