### ISSUE TITLE
[Test] Placement group scheduler test needs to guard the lock-protected attributes.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11267]
### What is the problem?

There's a vector lock that is supposed to lock some vector attributes, but they are not marked with GUARDED_BY as well as not actually protected properly. We should fix this. 

EX)
https://github.com/ray-project/ray/blob/47b7b76a5af13e0c8067d2425754ff29c8c99d0a/src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc#L160

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @ffbin

**Comment by rkooo567** [comment]
Actually, the idea solution is to just make the test single-threaded (by making Redis in memory update happen in the same thread). Is there any good way to achieve this?

**Comment by ffbin** [comment]
There is no good solution for the moment, because store client has its own io_service, which is not the same thread as the UT main thread.
