### ISSUE TITLE
[rllib] Install error: ray does not provide the extra 'rllib'

### ISSUE THREAD

**Issue by stefanbschneider** [ray-project/ray#11274]
### What is the problem?

When trying to install `ray[rllib]`, I get:

```
pip install ray[rllib]
Requirement already satisfied: ray[rllib] in ./venv/lib/python3.8/site-packages/ray-1.0.0-py3.8-linux-x86_64.egg (1.0.0)
  WARNING: ray 1.0.0 does not provide the extra 'rllib'
```

Trying to run my program, which requires RLlib then crashes because it's still missing dependencies, eg, `redis` and `yaml`.

*Ray version and other system information (Python version, TensorFlow version, OS):*

* ray 1.0
* python 3.8.5
* Ubuntu 20.04

---

It's easy to fix this by just uninstalling and reinstalling

```
pip uninstall ray
pip install ray[rllib]
```

But I can't get RLlib installed via a my `setup.py`.

**Comment by sven1977** [comment]
Hey @stefanbschneider what was the previous version you of ray you had installed in your env?
Also, do you use our git cloned-source-code-setup script? `python python/ray/setup-dev.py --yes`?
I think, what I'm asking is: Could you provide the detailed steps that always lead to this behavior starting from a totally clean env.

**Comment by sven1977** [comment]
This works fine:
```
$ conda create -n ray_test python=3.8
$ conda activate ray_test
$ pip install ray
$ pip install ray[rllib] tensorflow
$ python
>>>import ray
>>>ray.init()
>>>from ray.rllib.agents import ppo
```

**Comment by stefanbschneider** [comment]
Yes, directly installing via pip works for me, but via a `setup.py` doesn't. For example, with this `setup.py`:

```python
from setuptools import setup, find_packages


requirements = [
    'ray[rllib]>=1.0',
]

setup(
    name='test-rllib',
    install_requires=requirements,
)
```

Then on a clean Ubuntu 20.04 with Python 3.8 (install `python3-virtualenv` first):

```
virtualenv venv
source venv/bin/activate
python setup.py install
```

Fails with the error from above.

**Comment by sven1977** [comment]
Ok, I confirmed this is not working.
As a workaround, simply remove the `[rllib]` in your setup.py script:
```
from setuptools import setup, find_packages


requirements = [
    'ray>=1.0',
]

setup(
    name='test-rllib',
    install_requires=requirements,
)
```

**Comment by sven1977** [comment]
Then you should be able to do:
```
$ python
>>> import ray
>>> import ray.rllib.agents.ppo as ppo
>>> etc..
```

**Comment by sven1977** [comment]
@rkooo567 sorry, I assigned you to this issue (it's not really an rllib issue). I'm not exactly sure why it's saying that `ray 1.0.0 does not provide the extra 'rllib'`.
Let me know, if you need help fixing this.

**Comment by rkooo567** [comment]
Hmm I am not really familiar with this code path. cc @simon-mo Do you have any guess?

**Comment by stefanbschneider** [comment]
The error still persists with `ray 1.1.0`. Did you have any chance to look at this or does someone else have an idea what's the problem or solution here?
Am I the only one installing `ray[rllib]` via a `setup.py`?

**Comment by destin-v** [comment]
I noticed that the Github repository of Ray has more features in the RLLib library.  I would also like to be able to install ray[rllib] via a setup.py.  Any update on this issue?

**Comment by simon-mo** [comment]
You can just add `ray` to your setup.py. RLLib is bundled in it. The extra [rllib] just installs the following packages, which you should feel free to add as well.

https://github.com/ray-project/ray/blob/1dcdfe910161ec36a4544de2d0c200fb0c2c661a/python/setup.py#L110-L116

**Comment by stefanbschneider** [comment]
It seems like listing `ray[rllib]` inside `setup.py` works fine when installing with
```
pip install .
``` 
instead of 
```
python setup.py install
```

Or for development, `pip install -e .` instead of `python setup.py develop`.

This solves the issue for me; I'm closing it. But feel free to reopen it.
