### ISSUE TITLE
Ray Dashboard crashes when a node connects from Windows

### ISSUE THREAD

**Issue by abhayraw1** [ray-project/ray#11277]
### What is the problem?
The dashboard crashes when a node connects from a windows machine. Here is the message from the browser console:
![image](https://user-images.githubusercontent.com/14311538/95472130-490df180-09a0-11eb-87b7-65419074d876.png)
I'm using ray, version 1.0.0 installed through pip (python version 3.7.7). The remote machine where I start ray with the `--head` parameter is running Ubuntu 16.04. 

There seems to be no problem when I try running ray on my windows machine via WSL (Ubuntu 18.04). The only issue is that as there is no GPU support on WSL yet, I am more inclined towards using it through windows!

### Reproduction (REQUIRED)

On remote machine (Ubuntu 16.04):
```
ray start --head --port=6379 --node-manager-port=12345 --object-manager-port=12346
```
On Windows machine (or via WSL):
```
ray start --address <host-ip>:6379 --node-manager-port=12345 --object-manager-port=12346
```
 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mattip** [comment]
I think this has been fixed in the recent 1.9.1 release, could you try that version?

**Comment by dynamicwebpaige** [comment]
Potential also related: [#16781](https://github.com/ray-project/ray/issues/16781).

**Comment by mattip** [comment]
I don't think this is related to #16781. The issue here was that older versions of ray (the reporter was using 1.0.0) did not support the dashboard agent monitoring the gpu on windows. This was fixed in #19319, which was released as part of 1.8.0 and then refined to work better in later releases.

**Comment by scottsun94** [comment]
@abhayraw1 Is the issue fixed for you?

**Comment by scottsun94** [comment]
@abhayraw1  ^ bump it

**Comment by scottsun94** [comment]
Closing it for now. Please reopen if you still run into this issue.
