### ISSUE TITLE
[autoscaler] 120s timeout in uptime command causes delays when booting

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#11273]
### What is the problem?

Ray version: 1.0.0
Python version: 3.8.1
OS: Ubuntu 18.04

Hi all, I noticed a delay on some nodes when booting a cluster.  Specifically, the delay comes between system boot (as reported by psutil) and setup commands executing.  The issue appears to be fixed by changing the timeout parameter when running the uptime command:

```
diff --git a/python/ray/autoscaler/updater.py b/python/ray/autoscaler/updater.py
index 8040dbcbd..ccb0d1931 100644
--- a/python/ray/autoscaler/updater.py
+++ b/python/ray/autoscaler/updater.py
@@ -231,7 +231,7 @@ class NodeUpdater:
                                              self.log_prefix)
 
                         # Run outside of the container
-                        self.cmd_runner.run("uptime", run_env="host")
+                        self.cmd_runner.run("uptime", timeout=5, run_env="host")
                         cli_logger.old_debug(logger, "Uptime succeeded.")
                         cli_logger.success("Success.")
                         return True
```

Here's a histogram of the time to setup commands for 64 workers, both with and without the above change:

![image](https://user-images.githubusercontent.com/37295291/95451260-725a5d80-095f-11eb-8ef3-7dd83bd2dcbc.png)

As you can see, setting timeout=5 gets rid of the second mode around 60s.  I notice that historically the timeout used to be 5s but was reverted as part of this PR, but it's not clear why?  https://github.com/ray-project/ray/pull/9322/files#diff-2691ece495b9e3385c14189d8a32b54eL113

### Reproduction

Boot a cluster with 64 c5.12xlarge instances, measure the time between the setup commands executing, and that reported by psutil.boot_time().

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @wuisawesome @ijrsvt

**Comment by ijrsvt** [comment]
@richardliaw  Any reason for this change in #9322?

@mattearllongshot What does your cluster config look like?

**Comment by richardliaw** [comment]
@ijrsvt probably accidental, we should revert.

**Comment by ijrsvt** [comment]
@mattearllongshot would you like to contribute the fix =) 
Thanks again for finding this!!

**Comment by mattearllongshot** [comment]
I've raised the PR https://github.com/ray-project/ray/pull/11300
