### ISSUE TITLE
ray.wait doesn't prioritize returning tasks that have finished earlier

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1128]
This might be intended behavior, but naive use of ray.wait() can starve workers from having their results processed. For example, in this simple example where tasks take basically no time and the driver processes them slowly one at a time, some results can get delayed for hundreds of `wait` steps.

```
import ray
import sys
import time

@ray.remote
def f(i):
    return i

ray.init(num_cpus=4)

i = 0
remaining_ids = [f.remote(i) for _ in range(5)]

for _ in range(1000):
    [ready], remaining_ids = ray.wait(remaining_ids, 1)
    i_old = ray.get(ready)
    print(i - i_old, end=" ")
    sys.stdout.flush()
    time.sleep(.01)  # do some work e.g. apply gradients
    i += 1
    remaining_ids.append(f.remote(i))
```

Output:
```
0 1 2 1 4 4 1 4 1 9 1 1 1 1 1 1 1 1 1 11 1 1 16 1 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 21 1 1 1 1 1 1 1 48 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 49 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 74 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 223 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 75 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 
```

Note that you can work around this by waiting on only the first element of the list.

**Comment by virtualluke** [comment]
This might be what I was seeing in [#948](https://github.com/ray-project/ray/issues/947)

**Comment by robertnishihara** [comment]
Right, because `ray.wait` doesn't prioritize tasks that finished earlier (that's what you mean by fairness, right?), I think it actually just prioritizes objects that are earlier in the list of object IDs passed in (is that what you're seeing?).

Do you think this is a problem?

**Comment by ericl** [comment]
It's kind of odd, and basically means ray.wait() is unusable in stale-asynchronous models of communication without more effort (you will need to carefully manage which futures to pass to ray.wait to bound staleness).

We should at least document it; note also that Java concurrency primitives typically provide both a fair and unfair mode (unfair can be better for performance): https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ArrayBlockingQueue.html

**Comment by ericl** [comment]
Btw, it's not the case that objects earlier in the list are prioritized -- in the above example, I always append to the end of the list, but still see high variance in delays.

**Comment by ericl** [comment]
I think that's because the main loop can keep up with the tasks in that
case. If there is a backlog of tasks to fetch then the problem arises.
