### ISSUE TITLE
Error in ray tune docs

### ISSUE THREAD

**Issue by avandekleut** [ray-project/ray#11282]
This isn't a bug but also isn't a feature request or really a question. 

On this page of the docs: https://docs.ray.io/en/master/tune/user-guide.html it states that `tune.run` takes a `log_to_file` argument, which it no longer does.

(Also, how can I get that behaviour...?)

**Comment by richardliaw** [comment]
@avandekleut what version of Ray are you on? The latest pip release docs has it here:

https://docs.ray.io/en/latest/tune/api_docs/execution.html#tune-run

**Comment by avandekleut** [comment]
I did some debugging. When running
```sh
pip install "ray[tune]"
```
it was installing 0.8.7 instead of 1.0.0. I just tested that same pip install in a new environment and it **is** installing 1.0.0 and works with `log_to_file`. Not sure why it was being weird before.
