### ISSUE TITLE
[rllib] SAC (pytorch) log_alpha not optimizing with GPU enabled

### ISSUE THREAD

**Issue by anqixu** [ray-project/ray#11294]
### What is the problem?

The entropy regularization coefficient `alpha` (implemented as `sac_model.log_alpha` tensor) is not being updated by `sac_policy.alpha_optim`.

Verify by running the attached script, load tensorboard, and confirm that the alpha value does not change over training iterations.

### Suspected cause

I believe the culprit is due to an incorrect order of execution:

1. [`sac_model.log_alpha` is initially created as a tensor on CPU device](https://github.com/ray-project/ray/blob/b450cb030a5d316f04d4f6322e152335853d1a88/rllib/agents/sac/sac_torch_model.py#L134)
2. [`sac_policy.alpha_optim` is initialized with the `sac_model.log_alpha` param](https://github.com/ray-project/ray/blob/b450cb030a5d316f04d4f6322e152335853d1a88/rllib/agents/sac/sac_torch_policy.py#L380)
3. but then [sac_model.log_alpha is CLONED to the CUDA device](https://github.com/ray-project/ray/blob/b450cb030a5d316f04d4f6322e152335853d1a88/rllib/agents/sac/sac_torch_policy.py#L469), and [this copy is used during backprop](https://github.com/ray-project/ray/blob/b450cb030a5d316f04d4f6322e152335853d1a88/rllib/agents/sac/sac_torch_policy.py#L173)

To verify, put a debugger breakpoint [after `opt.step()`](https://github.com/ray-project/ray/blob/b450cb030a5d316f04d4f6322e152335853d1a88/rllib/policy/torch_policy.py#L402), then verify that `sac_model.log_alpha` does not match `sac_policy.alpha_optim.param_groups[0]["params"][0]`:

```python
self._optimizers[3].param_groups[0]["params"][0]
# DEBUGGER OUTPUT: tensor([-0.0003], requires_grad=True)

self.model.log_alpha
# DEBUGGER OUTPUT: tensor([0.], device='cuda:0', grad_fn=<CopyBackwards>)

self._optimizers[3].param_groups[0]["params"][0] is self.model.log_alpha
# DEBUGGER OUTPUT: False
```

Unfortunately, I don't know RLLib internals enough to know how to properly solve this issue.

### Related issue: unable to disable GPU usage in RLLib configs

According to [SAC configs](https://docs.ray.io/en/master/rllib-algorithms.html#sac), we should be able to disable GPU usage by the learner/driver by setting `"num_gpus": 0`. I also set `"num_gpus_per_worker": 0` just in case. But Ray still puts tensors onto CUDA. I don't know why this is the case.

To sidestep this issue, we can force Ray to start without GPUs: `ray.init(num_gpus=0, ...)`.

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Tested with ray 1.0.0 (via pip) and nightly (ray-1.1.0.dev0)
* Python 3.7.5 `(default, Nov  7 2019, 10:50:52) [GCC 8.3.0] on linux`
* Ubuntu 18.04: `Linux MIMIC-5530-UB1804 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

[torch_sac_alpha_unchanged.py.txt](https://github.com/ray-project/ray/files/5352388/torch_sac_alpha_unchanged.py.txt)

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
For a quick fix (PR to follow today):

Could try creating the sale.log_alpha property inside sac_torch_model.py like so?:

```
        log_alpha = nn.Parameter(
            torch.from_numpy(np.array([np.log(initial_alpha)])).float())
        self.register_parameter("log_alpha", log_alpha)
```

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/11298

**Comment by sven1977** [comment]
@anqixu 
Thanks for filing this issue! :)
