### ISSUE TITLE
[Cluster] Ray cluster did not distribute a task. to worker node

### ISSUE THREAD

**Issue by stayhungry7** [ray-project/ray#11304]
### Describe your feature request

I create a ray cluster with my 3 local machines manually, "ray start"
After checking the cluster is working through the dashboard, I ran a test program to see.

@ray.remote
def mywork():
    #time.sleep(0.01)
    sum_value = 0
    for index in range(random.randrange(10000)):
        sum_value += index

    a_ip = ray.services.get_node_ip_address()
    dic_result = {'sum':sum_value,'ip':a_ip}
    return dic_result

ray.init(address='auto', _redis_password='5241590000000000')

results = ray.get([mywork.remote() for _ in range(100)])
print(results)

When I check the result, I saw only one ip address which is the machine i ran the codes

Is there something I missed?
Thanks

 

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

**Comment by rkooo567** [comment]
Could be the same issue as https://github.com/ray-project/ray/issues/11295 or https://github.com/ray-project/ray/discussions/11290. Can you try our nightly?
