### ISSUE TITLE
[Dashboard] Some GPUs have gpu_utilization=null, breaking page

### ISSUE THREAD

**Issue by mfitton** [ray-project/ray#11313]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
1.0.0 release.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

This issue was reported by Pieterjan, and I believe it doesn't need reproduction, only to properly handle the case where that data is missing with something like an `N/A`. I hadn't realized that that field was optional from the gpustat library.
![image](https://user-images.githubusercontent.com/3156716/95609266-70aa9b80-0a2c-11eb-994f-e01e1bb66332.png)

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@mfitton I made it P0. Please feel free to change the priority if it doesn't look right to you!
