### ISSUE TITLE
How does ray copy all attributes of a model to remote?

### ISSUE THREAD

**Issue by jiangtianli91** [ray-project/ray#11329]
### Updated
I provided a minimal code that reproduces the problem.

### What is the problem?
Basically, I want a ray task to output the weight derivates given the model and a batch of training examples. 

```python 
@ray.remote
def ray_task(network, example):
    res = network.standard_net_train_example(example)
    groups = network.groups
    batch_errors = network.batch_errors
    return res, groups, batch_errors;
```
The network.groups is an attribute of the network which is a list of python objects containing weights and weight derivatives. However, the ray fails to copy this attributes when it is initialized as 
```
example_id = ray.put(example)
IDs += [ray_task.remote(network, example_id)] 
``` 
```network.groups``` ends up to be an empty list.

I wonder is there a way to copy the network including the list of objects(weights and weight derivatives).

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray ```1.0.0```
python ```3.8.5```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
If we cannot run your script, we cannot fix your issue.

The minimal scripts: [Github repo](https://github.com/jiangtianli91/ray_issue.git)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
Ray serializes the whole function under the hood. In particular, we use cloud pickle to serialize the function.

**Comment by jiangtianli91** [comment]
> Ray serializes the whole function under the hood. In particular, we use cloud pickle to serialize the function.
I am sorry. I don't really understand. Does it mean that this cannot be done?

**Comment by wuisawesome** [comment]
Oh I see what you mean. I'm assuming the issue here is that the function is serialized before the variable is initialized.

Since `network` is a state full object, you should try to make it an Actor. 


https://docs.ray.io/en/master/actors.html

**Comment by jiangtianli91** [comment]
> Oh I see what you mean. I'm assuming the issue here is that the function is serialized before the variable is initialized.
> 
> Since `network` is a state full object, you should try to make it an Actor.
> 
> https://docs.ray.io/en/master/actors.html

I find it is the same when I implement it as an actor. Here is how I do it.
```python
@ray.remote
class ray_network(object):
    def __init__(self, network):
        self.network = network

    def train(self, example):
        res = self.network.standard_net_train_example(example)
        return res

    def get_batch_errors(self):
        return self.network.batch_errors

    def get_errors(self):
        return self.network.errors

    def get_groups(self):
        return self.network.groups
```
The actor is initialized in a loop.
```python
for i in range(0, batch_size):
    example = example_set.iterate_example()
    self.max_example_time = example_set.max_time
    example_id = ray.put(example)
    actors += [ray_network.remote(self)]
    res_IDs += [actors[-1].train.remote(example_id)]
```

```ray.get(ray_network.get_groups.remote())``` still gives me an empty list.

**Comment by rkooo567** [comment]
When you pass your `network` object, it is copied to a separate process (either task or actor). They are not shared like you are programming in a single process (which shares the memory). If you'd like to keep the state, you should have a "single" actor that has network and modify the network object by calling a actor method.

**Comment by jiangtianli91** [comment]
> When you pass your `network` object, it is copied to a separate process (either task or actor). They are not shared like you are programming in a single process (which shares the memory). If you'd like to keep the state, you should have a "single" actor that has network and modify the network object by calling a actor method.

Thank you for your answer! My problem is more about why some of the attributes of the model are copied (attributes that are just a integer) while some (which are lists of objects) are not?

**Comment by wuisawesome** [comment]
@jiangtianli91 if you believe there's a bug, can you provide a script that reproduces the bug?

**Comment by rkooo567** [comment]
Only objects that are shared among ray tasks/actors are "ray objects". This is represented as an object reference in code. For example, try seeing the type of objects that are returned by Ray tasks. It must be a `ObjectRef` type, which is a Ray specific object that can be shared among processes. Note that these objects are "read-only". It is a programming model of Ray. This means you cannot modify these objects.

Other objects (like your network) are just copied to the process. Since processes don't share the address space, those objects are not in sync. If you'd like to sync them, you should either 
1. Make the object a Ray object using ray.put and pass them (but you still cannot modify them because it is read only).
2. Or store the value in an actor and modify them using actor methods.

**Comment by jiangtianli91** [comment]
@rkooo567  @wuisawesome 
Here is a minimal code that reproduces the bug I think. [Github repo](https://github.com/jiangtianli91/ray_issue.git)

I find that when I put all the classes in one file. Ray can copy all the attributes of the ```network``` object successfully. However, If I put the classes into a separate file and import them. Ray does not copy all of the attributes.

```python
$ python3 ray_issue_without_import.py
xor
[<__main__.Group object at 0x7f8b1b29e400>, <__main__.Group object at 0x7f8b1da0acd0>, <__main__.Group object at 0x7f8b1d9993d0>]
xor
[<__main__.Group object at 0x7f8b1da17f70>, <__main__.Group object at 0x7f8b1da17fd0>, <__main__.Group object at 0x7f8b1da61070>]
```
ray_issue_without import copy all the attributes.
```python
$ python3 ray_issue.py
xor
[<src.network.Group object at 0x7facc5c04670>, <src.network.Group object at 0x7facc6241550>, <src.network.Group object at 0x7facc60a3e80>]
xor
[]
```
ray_issue does not copy all the attributes.

**Comment by rkooo567** [comment]
@wuisawesome Do you mind taking a look at this issue?
