### ISSUE TITLE
[WebUi] Task Timeline Doesn't Appear in Firefox

### ISSUE THREAD

**Issue by Wapaul1** [ray-project/ray#1133]
If you launch the webui in Firefox and attempt to generate the task timeline, only a large blank area is shown. This occurs with Firefox 56.
Steps to reproduce:
Execute the following:
```
import ray
ray.init()
@ray.remote
def f():
  return 1
f.remote()
```
and go into the webui and attempt to generate the task timeline.

The issue appears to be that Firefox does not support the WebComponents that Catapult needs. There are two files `index.html` and `trace-viewer-full.html` that the task timeline is composed of. `index.html` imports `trace-viewer-full.html` via HTMLImports, which is [not supported](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports) by Firefox. Even if the content of `trace-viewer-full.html` is put into `index.html`, then you still need to enable webcomponents in `about:config` in firefox. If enabled, then some function calls still do not work as in [this issue](https://github.com/catapult-project/catapult/issues/2489).

I'm not certain if we can do anything to fix this in Ray beyond potentially including the right version of webcomponents.

**Comment by robertnishihara** [comment]
Interesting, thanks for looking into this!

**Comment by robertnishihara** [comment]
Closing because the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
