### ISSUE TITLE
[rllib] Pong tutorial - how to run the server

### ISSUE THREAD

**Issue by DanielWicz** [ray-project/ray#11343]
I'm trying to do finish this tutorial: `https://github.com/ray-project/tutorial/blob/master/rllib_exercises/rllib_exercise04_serving.ipynb`, yet I can't go with connecting to the server, I mean the part:

"$ python serving/pong_web_server.py

The web server will listen on port 8900 for HTTP connections. It will internally connect to the policy server already running on port 3000.
**In a new browser tab, you should go to a URL like https://hub.mybinder.org/user/ray-project-tutorial-YOUR_NOTEBOOK_ID/proxy/8900/serving/javascript-pong/static/index.html** "

I was trying to run the index.html from the bolded part through python's `http.server`, yet it does not work. How it should be done ?

**Comment by Rohan138** [comment]
Closing; here's an updated example of serving RLlib with Ray Serve: https://docs.ray.io/en/latest/serve/tutorials/rllib.html
