### ISSUE TITLE
[Placement Group] Automatic lifecycle management 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11346]
### Describe your feature request

Currently, the placement group lifecycle requires explicit user involvement. For example, users "should" delete placement groups when they don't need it anymore. @richardliaw requires this to be automatic as it is very important for user experience.

**Comment by richardliaw** [comment]
Thanks!

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/11347 (merging)
