### ISSUE TITLE
[RLlib] How to save/restore replay buffer in Ape-X-DQN ?

### ISSUE THREAD

**Issue by liuyuecheng-github** [ray-project/ray#11359]
#### System information
- ray : 0.8.6
- OS : CentOS
### Problem Description
I want to save/restore the replay buffer in Ape-X-dqn, following [This work](https://github.com/ray-project/ray/issues/2894),

I tried to overrite the `save` and `restore` function in `ray/rllib/optimizers/async_replay_optimizer`: `class AsyncReplayOptimizer(PolicyOptimizer)`, and I think that these functions should be called by the `trainer` in `ray/rllib/agents/trainer.py`: `Trainer._save() and Trainer._restore()` by calling `self.optimizer.save() and self.optimizer.restore()`.

However, I find that my `Ape-X Trainer` has no attribute `optimizer`. So, how can I save/restore the replay buffer?

Looking forward to your help.

**Comment by liuyuecheng-github** [comment]
I have realized this by my self.

**Comment by cedros23** [comment]
Hi YuechengLiu, 

How did you manage to save replay buffer eventually? Apex-dqn has default 4 asnyc replay buffers to my understanding, which would not be trivial to export during training.

Regards,

**Comment by YuechengLiu** [comment]
> Hi YuechengLiu,
> 
> How did you manage to save replay buffer eventually? Apex-dqn has default 4 asnyc replay buffers to my understanding, which would not be trivial to export during training.
> 
> Regards,

In my implementation, I only use 1 replay buffer (However, I think that it can be easily extended to the case which holds multiple replay buffers).  I have put some of the modified source code on [google Drive](https://drive.google.com/file/d/1vluNF15KuzF4lxLDcjzgml5Bpb4Tr4IB/view?usp=sharing), and my implementation is based on ray==0.8.6 (maybe 0.8.7, I forgot). Hope that this will help you.

**Comment by cedros23** [comment]
That is excellent! 

thanks for the help.
