### ISSUE TITLE
[Autoscaler] Cluster emulator for testing 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#11370]
### Describe your feature request

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

We should implement some sort of simple emulator to perform more realistic E2E testing of the autoscaler. 

Input:
* Autoscaler/Load metrics 
* Workload (TODO: define what this looks like in more detail.

Output:
* "Cluster state" should be inspectable 
* Realistic timing

**Comment by wuisawesome** [comment]
cc @AmeerHajAli @ericl

**Comment by rkooo567** [comment]
node provider for cluster_utils?

**Comment by ericl** [comment]
I think we want something much lighter weight here--- just a few helper functions in unit test to emulate load metrics for a workload of N tasks.
