### ISSUE TITLE
[rllib]how to use rllib without MuJoCo ?

### ISSUE THREAD

**Issue by sungreong** [ray-project/ray#11382]
[rllib]

I just want to use rllib library.
but, there is not working

```
OSError: Cannot find MuJoCo library at /root/.mujoco/mujoco200_linux/bin/libmujoco200.so.
```

how to use rllib without MuJoCo?

**Comment by sven1977** [comment]
It should be fine. I'm developing it on Mac and Win in python envs that both do not have MuJoCo installed.

**Comment by sven1977** [comment]
What exactly are you running (command line, etc..)? Could you give more specifics?

**Comment by sungreong** [comment]
Recently, the environment was created from scratch and the installation started, and it worked well.

Thanks
