### ISSUE TITLE
[Dashboard] Dashboard not available when cluster is being ready.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11384]
### What is the problem?

When this repo https://github.com/danwallach/arlo-e2e-noop/tree/main/src/arlo_e2e_noop starts and port-forward the ray dashboard, it has a json error on the screen until the cluster is ready. @danwallach can explain this better. 

This shouldn't be the case. Regardless of what the cluster is doing, as long as the head node is alive, dashboard shouldn't render any error. We might want to add some regression tests to prevent this (with cluster_utils). This might be resolved when the new dashboard is on though. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run the script in the repo. It doesn't require any additional setup :) 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mfitton** [comment]
This issue has been fixed with the new dashboard backend, released in https://github.com/ray-project/ray/pull/11510
