### ISSUE TITLE
Redis failed to start while running a program with Ray - RuntimeError: Couldn't start Redis

### ISSUE THREAD

**Issue by sreereju** [ray-project/ray#11395]
I am trying to use ray[tune] on a linux server where I am just a user without the root permission.

After installing ray[tune] and running python code ```from ray import tune``` , I got an error message:
```
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found
```
Followed the instructions online, I changed the environment variables:
```LD_LIBRARY_PATH=/home/USERNAME/dependency/glibc-2.17/lib/:/lib64/:/usr/local/gcc-5.3.0/lib64/```
```/home/USERNAME/dependency/glibc-2.17/lib/ld-2.17.so /home/USERNAME/python3.8.6/bin/python```

Then I was able to run the python code `from ray import tune`. 

But when I ran the below code in [link](https://docs.ray.io/en/master/tune/)
```
from ray import tune


def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100)**(-1) + beta * 0.1


def training_function(config):
    # Hyperparameters
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.
        tune.report(mean_loss=intermediate_score)


analysis = tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3])
    })

print("Best config: ", analysis.get_best_config(
    metric="mean_loss", mode="min"))

# Get a dataframe for analyzing trial results.
df = analysis.results_df
```
I got error: `RuntimeError: Couldn't start Redis`

logs/redis.err says:
thirdparty/redis/src/redis-server: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

*Ray version is 1.0.0, Python version is 3.8.6

Any fix/reason for this failure?

**Comment by rkooo567** [comment]
I think it is highly likely that it is an environment related issue. Can you elaborate your env setup? What OS/version are you using? Also, is there any error from ray logs? (/tmp/ray/session_latest/logs)

**Comment by sreereju** [comment]
Env set up :
Virtual environment set up for python. I followed the instructions in [link](https://towardsdatascience.com/virtual-environments-104c62d48c54)

OS/Version:
CentOS release 6.8, Linux 4.1.15.pnotify x86_64 

/tmp/ray/session_latest/logs:
thirdparty/redis/src/redis-server: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument

Python version is 3.8.6

**Comment by rkooo567** [comment]
This must be a env related issue. Can you check this stackoverflow and see if there's anything that is applied to your environment? https://stackoverflow.com/questions/40932215/error-while-using-a-newer-version-of-glibc

**Comment by sreereju** [comment]
Actually, I referred to that link for setting LD_LIBRARY_PATH.

**Comment by rkooo567** [comment]
Hmm then the upcoming issue you have now (Redis cannot start) follows the same pattern as this question? This person also mentioned about `ls: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument`, which is your error you can see from Redis error.

**Comment by rkooo567** [comment]
Unfortunately, I don't have any other thing I can help here if this is env related issue that caused Redis to fail. But let me cc other people who might be able to help. cc @barakmich @mehrdadn

**Comment by mehrdadn** [comment]
This might be similar to #6451. Perhaps see if you can resolve it in a similar way.

**Comment by sreereju** [comment]
Another observation when I followed the second solution(with conda set-up) in [link](https://stackoverflow.com/questions/40932215/error-while-using-a-newer-version-of-glibc).

I got the same result as mentioned in the description. i.e I am able to run `from ray import tune`, but not the python code with `tune.`

But now /tmp/ray/session_latest/logs says:
```
<home>/.local/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by <home>/.local/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server)
```

Any reason why it is looking for `.local` path?

Patchelf setup:
```
patchelf --set-rpath <home>/glibc-2.24/lib/:$HOME/.conda/envs/my_root/lib/:/usr/lib64:/lib64:/lib --set-interpreter <home>/glibc-2.24/lib/ld-linux-x86-64.so.2 <home>/.conda/envs/my_root/bin/python3.8
```

**Comment by sreereju** [comment]
In the cond env (my_root), I installed ray tune with command: `pip install 'ray[tune]'`.

But it got installed in `<home>/.local/lib/python3.8/site-packages/ray/` rather than `<home>/.conda/envs/my_root/lib/python3.8/site-packages/ray/`

Is this expected?

**Comment by sreereju** [comment]
Sorry. when I delete `.local` folder, it got installed in `.conda` folder.

Now I am getting /tmp/ray/session_latest/logs:
```
<home>/.conda/envs/my_root_ray/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by <home>/.conda/envs/my_root_ray/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server)
```

**Comment by sreereju** [comment]
One  more update:

I made changes to LD_LIBRARY_PATH to pick glibc-2.24
```
 export LD_LIBRARY_PATH=<home>/glibc-2.24/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
```

Still, it failed with: ``` Couldn't start Redis. Check log files:```

But now the files are empty in ```/tmp/ray/session_latest/log```

This looks similar to #6146. 

But even after ```unset LD_PRELOAD```, it failed with the same issue.

One more thing:
```ray stop``` resulted in:
```
Could not terminate `"<home>/redis-6.0.5/bin/redis-server *:51889" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=20557, name='redis-server')
Stopped only 0 out of 1 Ray processes. Set `-v` to see more details.
Try running the command again, or use `--force`.
```

**Comment by raymondren1982** [comment]
I have same question. I fix it last night. As following:
First find fun _start_redis_instance in file services.py. Then find this:
        command += (
            [--port", str(port), "--loglevel", "warning"] + load_module_args),
and change  change like this:
        command += (
            ["--bind","127.0.0.1","--port", str(port), "--loglevel", "warning"] + load_module_args)

OK

GOOD LUCK

**Comment by rkooo567** [comment]
Hmm interesting. Do you know why we need bind here?

**Comment by raymondren1982** [comment]
yes,we need bind here because redis server and client both need ip. The problem is one is 127.0.0.1,but the other is something else(such as 192.168.3.4).but the redis couldn't start is not this. It's because the ip ray gave is bad ip. redis-server.exe can't find it.
So we must bind a ip here.
