### ISSUE TITLE
[Serve] 60 second examples don't work if run as .py file

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#11404]
### What is the problem?
The two scripts at https://docs.ray.io/en/master/serve/ print the expected result (`"hello serve!"`, `{'current_counter': 1}`) if pasted into `ipython`, but not when run as a `.py` file.  Maybe everyone just pastes examples into their interpreter, but I wonder if this could be a bad first impression for those users that try to save them and run them.

Example:
```
❯ python quickstart_class.py
2020-10-14 17:17:30,101 INFO services.py:1088 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=62031) 2020-10-14 17:17:32,055     INFO controller.py:194 -- Starting router with name 'liItJb:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:10.0.0.99-0' on node 'node:10.0.0.99-0' listening on '127.0.0.1:8000'
(pid=62026) 2020-10-14 17:17:32,196     WARNING worker.py:1426 -- Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(pid=62026) INFO:     Started server process [62026]
(pid=62031) 2020-10-14 17:17:34,118     INFO controller.py:704 -- Registering route '/counter' to endpoint 'counter' with methods '['GET']'.
2020-10-14 17:17:36,486 INFO api.py:56 -- Shutting down Ray Serve because client went out of scope. To prevent this, either keep a reference to the client object or use serve.start(detached=True).
❯
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.0.0, but also on master.  py3.6, MacOS

### Reproduction (REQUIRED)
Linked above, but here's a paste:
```python
from ray import serve
import requests

client = serve.start()

def echo(flask_request):
    return "hello " + flask_request.args.get("name", "serve!")


client.create_backend("hello", echo)
client.create_endpoint("hello", backend="hello", route="/hello")

requests.get("http://127.0.0.1:8000/hello").text
# > "hello serve!"
```

```python
from ray import serve
import requests

client = serve.start()

class Counter:
    def __init__(self):
        self.count = 0

    def __call__(self, flask_request):
        return {"current_counter": self.count}


client.create_backend("counter", Counter)
client.create_endpoint("counter", backend="counter", route="/counter")

requests.get("http://127.0.0.1:8000/counter").json()
# > {"current_counter": self.count}
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
can you fix it by wrapping the requests in a for loop and print a shutting down near the end?
```
for _ in range(10):
    requests.get("....")

print("Shutting down")
client.shutdown()
```

**Comment by architkulkarni** [comment]
This is embarrassing, I just realized we don't call `print()` in the script, but when pasted into `ipython` the value of the last line is always printed.  I'll just wrap the last line in `print()`.  This is what's done in the examples on the front page of the Ray docs, so it'll be consistent.
