### ISSUE TITLE
Ray distributed multiprocessing.pool not distributing tasks on kubernetes ray cluster

### ISSUE THREAD

**Issue by jsanjay63** [ray-project/ray#11412]
### What is the problem?
Ray distributed multiprocessing.pool not distributing tasks on kubernetes ray cluster. All the tasks are executed on the head node itself and not distributing across multiple workers.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
Test example provided at https://docs.ray.io/en/master/multiprocessing.html

Kubernetes cluster setup using the doc: https://docs.ray.io/en/latest/cluster/kubernetes.html

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
Hi, please provide more information to troubleshoot the issue! There's nothing we can do with the current information. Please follow the format in the bug report! (Specifying how you setup your Kubernetes, what version of ray you are using, what's your config file looks like, and etc.).

**Comment by jsanjay63** [comment]
Sorry for the delayed response.
Kubernetes cluster setup using the doc: https://docs.ray.io/en/latest/cluster/kubernetes.html.

**Comment by jsanjay63** [comment]
@rkooo567 Could you please help with any updates on this.
