### ISSUE TITLE
Ray connection not working properly with multiple fork processes.

### ISSUE THREAD

**Issue by ehsandu15** [ray-project/ray#11419]
System specification:
  OSX Catalina 10.15.2
  Model Name:	MacBook Pro
  Processor Name:	6-Core Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  Activation Lock Status:	Enabled

I want to run ray using multiprocessing module, the set_start_method I use is 'fork'. The problem is when I start a new process I cannot connect to local cluster as it indicate I ran ray.init already; so I tried using ray.shutdown() on the process to check if ray detects that and it crashes immediately with the following traceback:

> 2020-10-16 00:04:20,437	INFO worker.py:634 -- Connecting to existing Ray cluster at address: 192.168.8.162:6379
> hi
> libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
> *** Aborted at 1602795860 (unix time) try "date -d @1602795860" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGABRT (@0x7fff6e5d27fa) received by PID 20207 (TID 0x10c84fdc0) stack trace: ***
>     @     0x7fff6e68442d _sigtramp
>     @ 0xffffffff00000400 (unknown)
>     @     0x7fff6e559a1c abort
>     @     0x7fff6b5f7be8 abort_message
>     @     0x7fff6b5f7d84 demangling_terminate_handler()
>     @     0x7fff6d11f792 _objc_terminate()
>     @     0x7fff6b604dc7 std::__terminate()
>     @     0x7fff6b604b6c __cxxabiv1::failed_throw()
>     @     0x7fff6b5f645d __cxa_throw
>     @     0x7fff6b5e82db std::__1::__throw_system_error()
>     @     0x7fff6b5e8369 std::__1::thread::join()
>     @        0x1027e02e4 ray::CoreWorker::WaitForShutdown()
>     @        0x1027dd16f ray::CoreWorkerProcess::RemoveWorker()
>     @        0x1027dcffd ray::CoreWorkerProcess::Shutdown()
>     @        0x1027482f8 __pyx_tp_dealloc_3ray_7_raylet_CoreWorker()
>     @        0x101fa5175 _PyDict_DelItem_KnownHash
>     @        0x101faa587 _PyObjectDict_SetItem
>     @        0x101fb7911 _PyObject_GenericSetAttrWithDict
>     @        0x101fb6cdc PyObject_SetAttr
>     @        0x1020499d0 _PyEval_EvalFrameDefault
>     @        0x101f7973d function_code_fastcall
>     @        0x10205068c call_function
>     @        0x10204cdf8 _PyEval_EvalFrameDefault
>     @        0x101f7973d function_code_fastcall
>     @        0x10204d0fe _PyEval_EvalFrameDefault
>     @        0x101f7973d function_code_fastcall
>     @        0x10205068c call_function
>     @        0x10204cddb _PyEval_EvalFrameDefault
>     @        0x101f7973d function_code_fastcall
>     @        0x10205068c call_function
>     @        0x10204cddb _PyEval_EvalFrameDefault
>     @        0x101f7973d function_code_fastcall
> 

The following code is what was used:
```
import ray
import multiprocessing as mp


def cxx():
    print("hi")
    ray.shutdown()
    print("shutdown")


if __name__ == '__main__':
    mp.set_start_method('fork')
    ray.init(address='auto')
    p = mp.Process(target=cxx)
    p.start()
    p.join()

```

**Comment by rkooo567** [comment]
Ray is not working with forking. We don't recommend you to use multiprocessing while you are using Ray.

**Comment by ehsandu15** [comment]
Thanks for the replay! I want to simulate multiple nodes connecting to the cluster from different processes, what module do you recommend?

**Comment by rkooo567** [comment]
Oh, you can do this by using our tool `cluster_utils`. We extensively use this for our internal testing.

Unfortunately, there's no documentation, but it is straightforward enough to understand. Let me give you the link and an example.

https://github.com/ray-project/ray/blob/master/python/ray/cluster_utils.py

```
from ray.cluster_utils import Cluster
c = Cluster()

head_node = c.add_node(/*some ray start args*/) # This starts a head node.
worker_node = c.add_node(/*some ray start args*/) # After the first node is created, it starts worker nodes.
c.wait_for_nodes() # Wait until nodes are up and running.
c.remove_node(worker_node) # remove a worker node from the cluster
```

**Comment by richardliaw** [comment]
Related to #33398
