### ISSUE TITLE
[dashboard] Dashboard breaks when creating new actors

### ISSUE THREAD

**Issue by Seraphli** [ray-project/ray#11411]
Dashboard breaks when creating new actors. This situation will disappear when there is no new actor being created.

https://youtu.be/MtMVT-k7aac

**Comment by rkooo567** [comment]
What version of ray are you using?

**Comment by rkooo567** [comment]
Also, it is a little unclear what's broken from that video. Can you elaborate a bit more and explain how to reproduce this?

**Comment by Seraphli** [comment]
Version 1.0
The machines joined the cluster are disappearing during creation. The total cores shouldn't be changing because the number of machines and cores is certain.

**Comment by Seraphli** [comment]
I actually don't know what caused it. Maybe it is caused by setting the number of cpus larger than the actual number of cores.

**Comment by rkooo567** [comment]
cc @mfitton

**Comment by mfitton** [comment]
Thanks for reporting. I hope the next release, which includes a new dashboard backend, will fix this problem.
