### ISSUE TITLE
Separate RL specifics from Trial in ray.tune

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1144]
Trial has references to agent which are arguably RL specific. Would be nice to get clean interface for general purpose ML .

@ericl

**Comment by ericl** [comment]
One way of doing this is to define a narrower `Trainable` interface which just has the train/save/restore methods.

**Comment by richardliaw** [comment]
This is partially addressed in #1226. One last todo is to separate `ScriptRunner` from `Agent`. Also, perhaps clean up the argument parsing.

**Comment by richardliaw** [comment]
Fixed in #1454.
