### ISSUE TITLE
[Doc] [Serve] Clarify that custom method calls do not propogate to all replicas

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#11444]
In the [How do I call a method on my backend class besides _call_?](https://docs.ray.io/en/master/serve/advanced.html) section, it makes no mention of the fact that this `handle.options` functionality only runs the class method on a single replica (although it would make my life a lot easier if it did propagate to all replicas).

Relevant discussion with @simon-mo : https://ray-distributed.slack.com/archives/CNCKBBRJL/p1601595205036400?thread_ts=1601586188.032700&cid=CNCKBBRJL

**Comment by rkooo567** [comment]
cc @architkulkarni  @simon-mo

**Comment by simon-mo** [comment]
Broadcasting to all worker is now a work in progress and owned by @architkulkarni!
