### ISSUE TITLE
ray.util.multiprocessing.Pool.starmap does not work with zip

### ISSUE THREAD

**Issue by HerculesJack** [ray-project/ray#11451]
### What is the problem?

It seems that `ray.util.multiprocessing.Pool.starmap` does not work with iterable created from zip, unless it's explicitly converted to a list etc. For example, this one works:

```
from ray.util.multiprocessing import Pool as RayPool

with RayPool(4) as pool:
    print(pool.starmap(lambda x, y: x + y, list(zip(range(0, 7, 2), range(1, 8, 2)))))
``` 

But this one gives me an error, saying that `TypeError: <lambda>() takes 2 positional arguments but 4 were given`.

```
from ray.util.multiprocessing import Pool as RayPool

with RayPool(4) as pool:
    print(pool.starmap(lambda x, y: x + y, zip(range(0, 7, 2), range(1, 8, 2))))
```

With python's own `multiprocessing.Pool` I don't need to explicitly convert it to a list, so I think it'd be better if the behavior of `ray.util.multiprocessing.Pool` can be the same here? I guess this issue would be easy to fix.

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 1.0.0 installed via pip, Python 3.6.11, SUSE 15.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

See above.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @edoakes 

Thanks for this report :). Btw, feel free to contribute to the fix!! That'll be really helpful
