### ISSUE TITLE
Ray placement group feature not releasing the resource when the actor dies in Java

### ISSUE THREAD

**Issue by selvaganesang** [ray-project/ray#11467]
I have used the placement group concept to have node affinity to actors. A resource is specified as part of ray start command --resources='{"hank01": 1}. When the actor created, it correctly placed the actor in the node where this resource is available. When the actor dies for some reason, the actor is removed from GCS. But, when I tried to create the actor with the same resource, the following error is continuously logged in gcs_server.log    
I1016 10:26:38.661249 24981 24981 gcs_placement_group_scheduler.cc:204] Scheduling placement group , id: 934fb933c8f616f3ccb29be8fa983e01, bundles size = 1
I1016 10:26:38.661300 24981 24981 gcs_placement_group_scheduler.cc:212] Failed to schedule placement group , id: 934fb933c8f616f3ccb29be8fa983e01

,because no resources are available.    It looks like when the actor is cleaned up, the resources associated with it are not cleared up to be used again. By increasing the --resources {"hank01": 2} I am able to call methods on this actor. What kind of problems will I have with just changing to high number of resources though I need to have one unit of the resource

In addition, setMaxRestarts(-1) doesn't seem to restart the actor. Is it because detached actor feature is not yet available in Ray for Java?

Steps to reproduce

1. Download the attached RayNamedActorTest.java.txt and rename it as RayNamedActorTest.java
2.  This program requires two parameters
            RayNamedActorTest <ray.config_file> hank01
3. Start Ray with parameter --resources={"hank01":  2}

Run this program 3 times.

For the first 2 times, this program displays the following
Pinging to actor Actor_hank01
Ping to actor Actor_hank01 succeeded

3rd time, the program will not return. It just displays
Pinging to actor Actor_hank01

And you will see the above error in gcs_server.log

If we cannot run your script, we cannot fix your issue.

[RayNamedActorTest.java.txt](https://github.com/ray-project/ray/files/5403292/RayNamedActorTest.java.txt)

I have copied the program here too

package com.elevo.ray;

import io.ray.api.ActorHandle;
import io.ray.api.BaseActorHandle;
import io.ray.api.ObjectRef;
import io.ray.api.Ray;
import io.ray.api.placementgroup.PlacementGroup;
import io.ray.api.placementgroup.PlacementStrategy;

import java.io.IOException;
import java.util.*;

public class RayNamedActorTest {
    public static class RayNamedActor {
        public String ping(String pingText) {
            return pingText;
        }
    }

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.out.println("$0 <configuration> <resource_name> ");
            System.exit(0);
        }
        String rayConfigFile = args[0];
        System.setProperty("ray.config-file", rayConfigFile);
        Ray.init();
        ActorHandle<RayNamedActorTest.RayNamedActor> actorHandle = null;
        String resource = args[1];
        String actorName = "Actor_" + resource;
        Optional<BaseActorHandle> tmpActorHandle;
        tmpActorHandle = Ray.getGlobalActor(actorName);
        if (tmpActorHandle.isPresent())
            throw new IOException("Actor " + actorName + " already created");
        List<Map<String, Double>> bundles = new ArrayList<>();
        Map<String, Double> bundle = new HashMap<>();
        bundle.put(resource, 1.0);
        bundles.add(bundle);
        PlacementStrategy strategy = PlacementStrategy.STRICT_PACK;
        PlacementGroup placementGroup = Ray.createPlacementGroup(bundles, strategy);
        actorHandle = Ray.actor(RayNamedActorTest.RayNamedActor::new).setGlobalName(actorName)
                .setMaxRestarts(-1)
                .setResource(resource, 1.0).setPlacementGroup(placementGroup, 0).remote();
        if (actorHandle != null) {
            System.out.println("Pinging to actor " + actorName);
            String pingText = "Ping to actor " + actorName + " succeeded";
            ObjectRef<String> objectRef = actorHandle.task(RayNamedActorTest.RayNamedActor::ping,
                    pingText).remote();
            String retStr = objectRef.get();
            System.out.println(retStr);
        }
    }
}

**Comment by rkooo567** [comment]
Thanks for posting this! @ffbin You guys don't have the remove API yet?

**Comment by ffbin** [comment]
> Thanks for posting this! @ffbin You guys don't have the remove API yet?

Yeah, we will add the remove Java API.

**Comment by rkooo567** [comment]
@ffbin This must have been resolved right?

**Comment by ffbin** [comment]
> @ffbin This must have been resolved right?

I think this has been resolved by the remove API.
