### ISSUE TITLE
[rllib] Unexpected key(s) in state_dic

### ISSUE THREAD

**Issue by wallneradam** [ray-project/ray#11468]
### What is the problem?

I'm playing with the new **Curiosity** exploration. I could make it work with PPO, but if I try to use it with other methods, such as DQN or SAC, I get the following error:
```
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FullyConnectedNetwork_as_SACTorchModel:
        Unexpected key(s) in state_dict: "_curiosity_feature_net._logits._model.0.weight", "_curiosity_feature_net._logits._model.0.bias", "_curiosity_feature_net._value_branch._model.0.weight", "_curiosity_feature_net._value_branch._model.0.bias", "_curiosity_inverse_fcnet.0._model.0.weight", "_curiosity_inverse_fcnet.0._model.0.bias", "_curiosity_inverse_fcnet.1._model.0.weight", "_curiosity_inverse_fcnet.1._model.0.bias", "_curiosity_forward_fcnet.0._model.0.weight", "_curiosity_forward_fcnet.0._model.0.bias", "_curiosity_forward_fcnet.1._model.0.weight", "_curiosity_forward_fcnet.1._model.0.bias".
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 1.0.0, Python 3.8.5, Ubuntu Linux, Torch 1.6.0

**Comment by wallneradam** [comment]
I could workaround the problem by placing `strict=False` arg to `load_state_dict` in `simple_q_torch_policy.py`. It is currently at line 34.

**Comment by zzcNEU** [comment]
> 我可以通过将`strict=False`arg放入`load_state_dict`in来解决此问题`simple_q_torch_policy.py`。目前在第34行。

Hello,Can you help me?
I try to add curiosity into ppo. But:
![image](https://user-images.githubusercontent.com/38434094/97182157-21f45400-17d7-11eb-9065-59376667f8c7.png)
![image](https://user-images.githubusercontent.com/38434094/97182193-2e78ac80-17d7-11eb-9fab-25e6c92451cd.png)

**Comment by DanielWicz** [comment]
I report the same behavior.
The version of Torch is 1.7, operating system Ubuntu 20.10 and version of RLLIB 1.0.1.
