### ISSUE TITLE
[autoscaler] EC2 instance type resources detection only works for first 100 instances

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#11484]
### What is the problem?

The AWS node provider's call to boto3.client("ec2").describe_instance_types() only returns 100 results. It seems we need to paginate through the full set of instance types, which exceeds 100: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_instance_types

Otherwise, instances like "m4.16xlarge" are not found in the list: dict_keys(['m2.2xlarge', 'r5a.12xlarge', 'c6g.16xlarge', 'm6g.xlarge', 'r5dn.8xlarge', 'm5dn.12xlarge', 'c5n.2xlarge', 'm5ad.8xlarge', 'c4.8xlarge', 't2.2xlarge', 'm5d.large', 'd2.2xlarge', 'c6g.xlarge', 'm5d.8xlarge', 'r5ad.24xlarge', 'inf1.xlarge', 'c5d.12xlarge', 't4g.nano', 'z1d.2xlarge', 't1.micro', 'r5a.xlarge', 'c5ad.16xlarge', 'c5ad.12xlarge', 'c5d.large', 'r6g.8xlarge', 'm5a.2xlarge', 'c5.4xlarge', 'c3.large', 'm5a.4xlarge', 'f1.2xlarge', 'r3.large', 'm5.24xlarge', 'x1e.8xlarge', 'c5ad.24xlarge', 'm5.8xlarge', 'c6gd.metal', 'r5ad.8xlarge', 'r5ad.12xlarge', 'm5a.16xlarge', 'm5n.16xlarge', 'm6g.metal', 'r6g.medium', 'm5d.16xlarge', 't3a.small', 'm6gd.metal', 'r4.16xlarge', 'a1.medium', 'i3en.3xlarge', 'c4.4xlarge', 'm2.4xlarge', 'r6gd.2xlarge', 'i3en.12xlarge', 'r3.8xlarge', 'r6gd.large', 'x1e.32xlarge', 'm5ad.4xlarge', 'm5dn.large', 'r6gd.xlarge', 'g3.16xlarge', 'm5dn.2xlarge', 'm5dn.8xlarge', 't3.2xlarge', 'g4dn.metal', 'r5.24xlarge', 'r6gd.medium', 't3a.2xlarge', 'm6gd.xlarge', 'c5ad.4xlarge', 'c5a.4xlarge', 't4g.medium', 'm5ad.2xlarge', 'i2.2xlarge', 'm4.4xlarge', 'm5ad.large', 'm5dn.xlarge', 'r6g.16xlarge', 'c3.8xlarge', 'm6gd.12xlarge', 'm5.12xlarge', 'r5a.large', 'm5ad.12xlarge', 'm5.xlarge', 'i3en.24xlarge', 'm5d.xlarge', 't3.xlarge', 'x1.16xlarge', 'm6gd.4xlarge', 'r5a.2xlarge', 'c5n.large', 'm6gd.medium', 'c5n.4xlarge', 'x1e.2xlarge', 'r5n.4xlarge', 'c6g.12xlarge', 'r5n.12xlarge', 'm5d.metal', 'd2.8xlarge', 'm5.metal', 'r6g.large', 'c5.xlarge'])

Btw, we should also be raising an error if an instance type is not found in this dict, instead of silently ignoring it.

### Reproduction (REQUIRED)

Try to create a cluster with m4.16xl instance type--- resources will not be auto filled.

**Comment by wuisawesome** [comment]
boto sucks

**Comment by wuisawesome** [comment]
> Btw, we should also be raising an error if an instance type is not found in this dict, instead of silently ignoring it.

Maybe we should consider a warning? That way if we're doing something wrong, the user can hard code these things in. I agree we shouldn't be silent though.

**Comment by ericl** [comment]
I can't think of a valid reason why the user would want to launch with an invalid instance type, so it seems fine to me to raise an error in this case.

Note that we already try-catch around the entire resource detection block, so it would get converted to a warning that it could not autodetect for that instance type.

**Comment by wuisawesome** [comment]
Ah yeah that's right, we do try-catch the whole thing. I'm happy with that, though I betcha boto will find a way to fail still :p (i wonder what instances will be returned if your default region doesn't have an instance type...)
