### ISSUE TITLE
[Object Spilling] Raylet should be more resilient to IO worker failures.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11496]
### What is the problem?

Currently, if IO worker dies unexpectedly, raylet receives SIGSEGV. This shouldn't happen. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by stephanie-wang** [comment]
Closed in #11673.
