### ISSUE TITLE
[C++ API] Complete the missing arguments in ray.init(..)

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#11490]
Currently, we support a fraction of the arguments under RayConfig class (`ray/api/ray_config.h`):
```
class RayConfig {
 public:
  WorkerType worker_type = WorkerType::DRIVER;

  RunMode run_mode = RunMode::SINGLE_PROCESS;

  std::string redis_ip;

  int redis_port = 6379;

  std::string redis_password = "5241590000000000";

  int node_manager_port = 62665;

  std::string lib_name = "";

  std::string store_socket = "";

  std::string raylet_socket = "";

  std::string session_dir = "";

  static std::shared_ptr<RayConfig> GetInstance();

 private:
  static std::shared_ptr<RayConfig> config_;
};
``` 

We should support the remaining arguments. 
We should start with min_workers/max_workers at least.
This should also support adding a ray address for example so that we do not start a new head node every time (because we should be able to hook up to an existing one).

**Comment by SongGuyang** [comment]
We already supported config now. Just like https://github.com/ray-project/ray/blob/master/cpp/example/example.cc#L47.
