### ISSUE TITLE
[autoscaler] Support AWS Fleet Mode

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#11506]
### Describe your feature request

from @markgoodhead:

Have you guys considered a version of the autoscaler that instead uses the EC2 Autoscaling? Some of the features there are kind of redundant/managed by the autoscaler right now but the killer feature I'm thinking of right now would be the ability to dynamically select different instance types based on availability / capacity. We're currently struggling to get spot instances in a number of different regions in AWS and it's really hurting our ability to manage our ray instances. 

cc @mattearllongshot

**Comment by markgoodhead** [comment]
https://github.com/ray-project/ray/pull/11498

**Comment by markgoodhead** [comment]
I'd still love to get this feature into Ray - we've got the PR for it done and we're happy to do any work required to make it mergeable. Previously we were waiting until some refactoring was complete on the autoscaler before merging - what's the timeline for this to be completed?
