### ISSUE TITLE
[RFC][k8s][autoscaler] Redesign Ray operator for k8s

### ISSUE THREAD

**Issue by yiranwang52** [ray-project/ray#11545]
Current Ray operator was deprecated since it wasn't maintained, and fell behind in terms of scaling features. Users are encouraged to use k8s autoscaler/cluster launcher but that option requires Ray to be installed locally and extra permission for head node (See #10293 for details).

We are proposing a few new Ray operator designs to address these problems and improve deployment UX of Ray on k8s.
The design options are described in this doc:
https://docs.google.com/document/d/1DPS-e34DkqQ4AeJpoBnSrUM8SnHnQVkiLlcmI4zWEWg/edit#
Please share your thoughts. We will appreciate any feedback!

**Comment by jsanjay63** [comment]
Not sure if I understand correctly or missing anything. As per this doc: https://docs.ray.io/en/latest/cluster/kubernetes.html we just need kubectl and config yaml files, we may not necessarily require Ray to be installed locally.

**Comment by ericl** [comment]
Closing as this feature is now implemented.
