### ISSUE TITLE
[core] Named Actor fault tolerance - faulty retry

### ISSUE THREAD

**Issue by fahadh4ilyas** [ray-project/ray#11544]
### What is the problem?

I was running ray in Kubernetes cluster with config like in `ray/doc/kubernetes/ray-cluster.yaml` with some change in container command. I added command to create named actors inside the container. I named the actor based on the IP of the pod where the actor was running. Everything was running smoothly until after all the actor was initiated, I tried to remove one of the pod to test if new pod would spawn. The new pod indeed spawned, but it crashed because an error occurred when creating named actors. The error said that

    ValueError: The name 10.244.3.123-0 is already taken. Please use a different name or get the existing actor using ray.get_actor('10.244.3.123-0')

The new pod continued to crash and restart until this warning

    WARNING worker.py:1091 -- The node with node id 44f9f7b2d3c5fd855c96b9573b402024c9150963 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.

I am guessing the error occurred because the old pod was not detected dead, but the weird thing is, the new pod and the old pod has different IP. How could Ray misname actor from old pod and said that it was named after the new pod's IP? 

### Reproduction (REQUIRED)

here is what I change from `spec.template.spec.containers[0].args`:

    ray start <same ray flag but I remove --block flag> && python create_actor.py

and here is what inside `create_actor.py`

```python
import os,ray,time

RAY_HEAD_HOST = os.environ['RAY_HEAD_SERVICE_HOST']
RAY_HEAD_PORT = os.environ['RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY']
MY_IP = os.environ['MY_POD_IP']
MY_CPU = int(os.environ['MY_CPU_REQUEST'])

ray.init(address=RAY_HEAD_HOST+':'+RAY_HEAD_PORT, log_to_driver=False)

from some_script import SomeClass

SomeClass = ray.remote(SomeClass)

for actor_num in range(MY_CPU):
    SomeClass.options(resources={'node:'+MY_IP:0.01},name=MY_IP+'-'+str(actor_num),lifetime="detached").remote()

# this is for so the container command would not exit
while True:
    try:
        time.sleep(10)
    except KeyboardInterrupt:
        pass
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
cc @rkooo567 @stephanie-wang

**Comment by rkooo567** [comment]
What version of ray are you using?

**Comment by fahadh4ilyas** [comment]
> What version of ray are you using?

@rkooo567 I'm using wheels from [here](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp36-cp36m-manylinux1_x86_64.whl "ray nightly")

**Comment by rkooo567** [comment]
@fahadh4ilyas One suspicion I have is that it takes some time to be clean the detached actors' name, and your node was up earlier. Can you add this code block and see if the error still exists? 

```python3
for actor_num in range(MY_CPU):
    i = 0
    while i < 30:
        try:
            actor = ray.get_actor(MY_IP+'-'+str(actor_num))
            i += 1
            time.sleep(1.0)
        except ValueError:
            # Wait until actor name is deleted.
            break
    SomeClass.options(resources={'node:'+MY_IP:0.01},name=MY_IP+'-'+str(actor_num),lifetime="detached").remote()
```

**Comment by fahadh4ilyas** [comment]
> @fahadh4ilyas One suspicion I have is that it takes some time to be clean the detached actors' name, and your node was up earlier. Can you add this code block and see if the error still exists?
> 
> ```python
> for actor_num in range(MY_CPU):
>     i = 0
>     while i < 30:
>         try:
>             actor = ray.get_actor(MY_IP+'-'+str(actor_num))
>             i += 1
>             time.sleep(1.0)
>         except ValueError:
>             # Wait until actor name is deleted.
>             break
>     SomeClass.options(resources={'node:'+MY_IP:0.01},name=MY_IP+'-'+str(actor_num),lifetime="detached").remote()
> ```

@rkooo567 It's working but I'm still confused why Ray rename my old actor from `<my_old_ip>-<index>` to `<new_ip>-<index>`?

**Comment by rkooo567** [comment]
Hmm I see your point. Can you print the logs from `/tmp/ray/session_latest/logs/gcs_server.out`?

**Comment by fahadh4ilyas** [comment]
> /tmp/ray/session_latest/logs/gcs_server.out

@rkooo567 sorry for the late respond. here is the link to the pastebin of [gcs_server.out](https://pastebin.com/mFEspzBn "gcs_server.out pastebin")

**Comment by rkooo567** [comment]
> @rkooo567 It's working but I'm still confused why Ray rename my old actor from <my_old_ip>-<index> to <new_ip>-<index>?
Actually, can you elaborate on this more? 

You mean when a new pod is spawned, it should have a different IP, meaning the name shouldn't have been registered right?

**Comment by fahadh4ilyas** [comment]
> > @rkooo567 It's working but I'm still confused why Ray rename my old actor from <my_old_ip>- to <new_ip>-?
> > Actually, can you elaborate on this more?
> 
> You mean when a new pod is spawned, it should have a different IP, meaning the name shouldn't have been registered right?

@rkooo567 yup... usually the IP differ by one segment like from 10.10.2.102 to 10.10.2.103.
