### ISSUE TITLE
local_mode=True provides insufficient emulation

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1155]
- `ray.put` and `ray.get` seem to do nothing, instead of creating fake object IDs or serializing/unserializing. It would be useful for them to emulate the object store, in terms of debugging issues with serialization and also with missing calls to `ray.get` or `ray.put`.
- If a remote function which raises an exception is called by the driver, then the exception is not deferred until `ray.get` is called.

With `PYTHON_MODE`:
```
>>> import ray
>>> ray.init(driver_mode=ray.PYTHON_MODE)
{'redis_address': None, 'node_ip_address': None}
>>> ray.get(ray.put(0))
0
>>> ray.get(0)
0
>>> @ray.remote
... def raises():
...     raise Exception
...
>>> raises.remote()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../ray/worker.py", line 2312, in func_call
    result = func(*copy.deepcopy(args))
  File "<stdin>", line 3, in raises
Exception
```

Without `PYTHON_MODE`:
```
>>> import ray
>>> ray.init()
>>> ray.get(ray.put(0))
0L
>>> ray.get(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../ray/worker.py", line 2053, in get
    value = worker.get_object([object_ids])[0]
  File "...ray/worker.py", line 394, in get_object
    "which is not an ObjectID.".format(object_id))
Exception: Attempting to call `get` on the value 0, which is not an ObjectID.
>>> @ray.remote
... def raises():
...     raise Exception
...
>>> raises.remote()
ObjectID(df68230187eb62dc5b50f359d7f648fb25d86045)
```

**Comment by robertnishihara** [comment]
The original intention of `ray.PYTHON_MODE` was to have a mode where that just runs your code as if you had written a serial program in order to make it easier to debug the application code.

Admittedly this probably won't help debug cases where ray is used improperly or where ray is not correctly serializing something.

As your example shows, `ray.PYTHON_MODE` is a bit too permissive and could successfully run some incorrect code.

Are you suggesting the following? In `ray.PYTHON_MODE`, `f.remote()` should execute `f` in a blocking manner and then return an object ID (wrapping the actual return value). Then `ray.get` should take an object ID and unwrap it?

**Comment by rshin** [comment]
In terms of what I would care about/what motivated me to file this issue, it would be nice to be able to use Python debuggers with Ray code (e.g. to be able to pause execution of a particular remote function and then use a REPL there). I imagine this is probably not entirely impossible, but also quite annoying to implement.

So instead I've been using PYTHON_MODE with a debugger, but that has also led me to make mistakes regarding `ray.put` and `ray.get` (which are usually quickly revealed when running without PYTHON_MODE). I'm also deliberately using deferred exceptions in remote functions, but that's largely not compatible with using PYTHON_MODE. I'm not sure how common these practices are.

So yes, I would suggest that `f.remote()` execute `f` in a blocking manner, return an object ID, and also suppress exceptions until `ray.get` is called on the object ID. I would also suggest that `ray.put` and `ray.get` can also create/unrwap object IDs. If feasible, you could also try to ensure that writes made to global variables in a remote function are not visible outside of that remote function (although I'm not sure what happens when multiple remote functions, reading/writing to the same global variable, are placed on the same worker or on different workers; will the behavior be different in these two cases?), although I haven't personally had any bugs caused by this.

This would help ensure that code which works with PYTHON_MODE still works when PYTHON_MODE is unset, and vice versa.

**Comment by robertnishihara** [comment]
I like the suggestion for what `f.remote()`, `ray.get`, and `ray.put` should do. That makes sense to me.

I'll have to think more about the feasibility of shielding global variables from being written by remote functions..
