### ISSUE TITLE
There may be an error in the doc

### ISSUE THREAD

**Issue by GTimothee** [ray-project/ray#11556]
Hi, 

I was reading this page: https://docs.ray.io/en/master/configure.html#logging-and-debugging

When they suggested me to "Specify temp_dir when call ray.init()". 

I tried it and I realized that there is not any temp_dir argument in ray.init, consistently with https://docs.ray.io/en/ray-0.3.0/api.html?highlight=ray%20init#ray.init Has this feature been removed or I am just missing something ?

**Comment by sumanthratna** [comment]
Hmm...in 0.8.7, `temp_dir` was a valid kwarg for `ray.init` but in 1.0 it was changed to `_temp_dir`. I think we should change that tip to "Specify _temp_dir when call ray.init()"
