### ISSUE TITLE
[Serve] PTL Example

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#11578]
Examples for deploying PyTorch Lightening modules.

**Comment by zhe-thoughts** [comment]
Deploying PTL modules or models?

**Comment by simon-mo** [comment]
I think PTL's term uses module that encapsulate all code related to training/inference on a model: https://github.com/PyTorchLightning/pytorch-lightning#step-1-define-a-lightningmodule-nnmodule-subclass

Just a terminology.
