### ISSUE TITLE
[Tune] Sigopt (multi-metric) api fails with 1.1.0 (tries to hash list)

### ISSUE THREAD

**Issue by raoul-khour-ts** [ray-project/ray#11581]
If you run 

py_test(
 name = "sigopt_prior_beliefs_example",
 size = "medium",
 srcs = ["examples/sigopt_prior_beliefs_example.py"],
 deps = [":tune_lib"],
 tags = ["exclusive", "example"],
 args = ["--smoke-test"]
)

in python/ray/tune/build (this part of the testing is commented out since you need a sigopt API key...)
You get an output that looks like this:

"""
...
  File "/usr/local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 737, in _process_trial
    self._validate_result_metrics(result)
  File "/usr/local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 818, in _validate_result_metrics
    elif search_metric and search_metric not in result:
TypeError: unhashable type: 'list'
...
"""
ray 1.1.0.dev

### Reproduction (REQUIRED)
in python/ray/tune/build  run the sigopt sections that are commented out.

**Comment by raoul-khour-ts** [comment]
This is a consequence of search metric being able to be multi-metric.

**Comment by richardliaw** [comment]
cc @krfricke 

Also, let me ping the sigopt folks for a working API key...

**Comment by richardliaw** [comment]
Should be fixed on #11583 . We'll pick this onto the release.
