### ISSUE TITLE
How can I read the source code of libcommon.a?

### ISSUE THREAD

**Issue by TeddyBear1314** [ray-project/ray#1159]
I am new to ray, I am interested in plasma store!
where can I read these codes:
#include "common.h"
#include "plasma/plasma.h"
#include "plasma/events.h"
#include "plasma/protocol.h"
#include "plasma/client.h"

also I couldn't find this executable:
    plasma_store_executable = os.path.join(os.path.abspath(
        os.path.dirname(__file__)),
        "../core/src/plasma/plasma_store")

are all these in libcommon.a, because I saw the CMAKE:
include(CMAKE_BINARY_DIR/.../libcommon.a),
can anyone help me ?

or answer me the question I am interested:
does plasma store use mmap files to share between other plasma manager??

**Comment by robertnishihara** [comment]
Those files are now being developed as part of Apache Arrow, and are at https://github.com/apache/arrow/tree/master/cpp/src/plasma.

If you built Ray from source, they are under `ray/src/thirdparty/arrow/cpp/src/plasma`.

The executable you're referring to is placed in `ray/python/ray/core/src/plasma/`. But it is moved there from `ray/src/thirdparty/arrow/cpp/build/release/`.

The plasma store uses `mmap` to create objects in shared memory and clients of the plasma store use mmap to map those objects into their own address spaces.

The plasma manager is a separate process which is used to transfer objects between plasma stores on different machines (there is one plasma manager on each machine). The plasma manager is a client of the plasma store on the same machine as it, so it uses `mmap` to read/write directly from/to shared memory when transferring objects from/to the plasma store on the same machine.

**Comment by TeddyBear1314** [comment]
thanks for your reply! solved my problem perfectly, I thought when the object is local, The worker can use PlasmaClient to read from Plasma Store directly, is there a need  to read local Object using Plasma Manager? @robertnishihara

**Comment by pcmoritz** [comment]
You don't need the plasma manager for reading local objects, having the worker connected to the plasma store via a plasma client is enough (i.e. the plasma manager argument in the connect method can be empty).

**Comment by TeddyBear1314** [comment]
Thanks! @pcmoritz I meet a new question, how can i read the code involving numpy array serialization and deserialization? Is it in Arrow now?

**Comment by robertnishihara** [comment]
Check out these files in pyarrow:

https://github.com/apache/arrow/blob/master/python/pyarrow/serialization.pxi
https://github.com/apache/arrow/blob/master/python/pyarrow/serialization.py

And these files in the C++ code:

https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/arrow_to_python.cc
https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/python_to_arrow.cc

Also this function.

https://github.com/apache/arrow/blob/a04301833f585a66fa371394c9ee33a4a59c2ed8/cpp/src/arrow/python/numpy_convert.cc#L242

**Comment by robertnishihara** [comment]
Closing since I think this is resolved. Feel free to reopen if there are more questions.
