### ISSUE TITLE
[RAY SGD] GPU memory is not released

### ISSUE THREAD

**Issue by Servon-Lee** [ray-project/ray#11608]
Ray version: 1.0.0

I run something like:
``` python
@ray.remote
class MyTrainer(object):
    def __init__(self):
        ...

    def train(self):
        ...
        trainer = self.algo.get_trainer(self.config)
        trainer.train()

mytrainer = MyTrainer.remote(self.config)
mytrainer.train.remote()
```
After the training, the actor handle `mytrainer` should not be referenced, so I think the GPU memory should be released with the help of gc. However, as shown in the figure below, there is not any process using GPU and the GPU memory is not released (2338Mib are occupied):
![image](https://user-images.githubusercontent.com/29559374/97151506-8b11a280-17aa-11eb-8ab9-bfe087a2ee79.png)

I tried `ray.actor.exit_actor()` as the last step of my training, but it did not work. What is worse is that after the death of the driver, when using `htop` command, I found many processes related to ray: 
![image](https://user-images.githubusercontent.com/29559374/97152759-569ee600-17ac-11eb-8c10-e7ecfbbfdef6.png)

To my best knowledge, Ray actors use non-detached mode as default, so I think actors should automatically die after the death of the driver. Is it correct? Why do those Ray related processes not disappear?

The only thing I know is to use `pkill -9 ray`. How can I graciously release GPU memory and kill all of Ray related processes after the death of the driver? Thx in advance!

**Comment by amogkam** [comment]
Hi @Servon-Lee can you do `trainer.shutdown()` after all your training is done (make sure to save any checkpoints before shutting down!) and see if you're still getting the same problem.

**Comment by Servon-Lee** [comment]
@amogkam Oh, I forgot about it. It works! Appreciate your help!!!
