### ISSUE TITLE
[rllib] TF Non-Trainable Variables Registered as Trainable

### ISSUE THREAD

**Issue by ttumiel** [ray-project/ray#11620]
### What is the problem?

TFModelV2 registers variables that are set to `trainable = False` as trainable. This means you can't freeze pretrained layers and leads to using more memory than expected.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: master
Tensorflow: 2.3.1

### Reproduction (REQUIRED)
Run script using: `python script.py --config '{"model":{"custom_model":"test_net"}}' --run PPO --env CartPole-v0`

```python
from ray.rllib.train import create_parser, run
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.utils.framework import try_import_tf
from ray.rllib.models import ModelCatalog
from ray.rllib.utils.annotations import override
from ray.rllib.models.modelv2 import ModelV2

tf1,tf,tfv = try_import_tf()


class Network(TFModelV2):
    def __init__(self, obs_space, action_space, num_outputs, model_config, name, **kwargs):
        super().__init__(obs_space, action_space, num_outputs, model_config, name)

        l1 = tf.keras.layers.Dense(32)
        l2 = tf.keras.layers.Dense(64)
        l1.trainable = False

        inputs = tf.keras.Input(16)
        x = l1(inputs)
        x = l2(x)
        self.base_model = tf.keras.Model(inputs, x)
        self.base_model.summary()
        self.register_variables(self.base_model.variables)

        print("base_model.trainable_variables:", len(self.base_model.trainable_variables))
        print("self.trainable_variables():", len(self.trainable_variables()))
        raise ValueError # Terminate script

ModelCatalog.register_custom_model("test_net", Network)

parser = create_parser()
args = parser.parse_args()
run(args, parser)

# Output:
# Total params: 2,656
# Trainable params: 2,112
# Non-trainable params: 544
# 
# base_model.trainable_variables: 2
# self.trainable_variables(): 4 
```

I think `self.trainable_variables()` should be equal to `base_model.trainable_variables`. The problem seems to come from `TFModelV2.trainable_variables` which uses the `tf.Variable.trainable` property. However, this property doesn't seem to be updated when calling `Layer.trainable = False` and you can't directly set the property on the Variable either. I think TF should probably update that property when you change the Layer to non-trainable but to get around this for now, you can override the `TFModelV2.trainable_variables` method:

```python
    @override(ModelV2)
    def trainable_variables(self, as_dict=False):
        if as_dict:
            return {v.name: v for v in self.base_model.trainable_variables}
        return self.base_model.trainable_variables
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this!
Also, ideally, it should work fully automatically - just like in torch - w/o even having to call register_variables().
Will fix as suggested for now ...

**Comment by sven1977** [comment]
The suggested solution above would not work well if a model does not have a base_model prop.
We should instead fully automate variable registration (using the keras model's trainable_variable() method to collect all sub-modules' variables). The use should not have to register variables manually anymore.
This would make tf models behave just like torch ones.
Milestone: https://github.com/ray-project/ray/milestone/20

**Comment by ttumiel** [comment]
Sorry, I didn't mean this as a general solution (since it assumes the use of base_model). Maybe we could use __setattr__ like pytorch to add variables to an internal dict (https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L798) or subclass keras's Layer class.

**Comment by sven1977** [comment]
I agree to your solution (see the linked milestone above: https://github.com/ray-project/ray/milestone/20).
We'll get this fixed.

**Comment by RocketRider** [comment]
It seems as I am having the same issue with the new API, without calling "register_variables".
Is this bug fixed?
