### ISSUE TITLE
[Dashboard] New dashboard crashes when looking at worker logs.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11630]
### What is the problem?

Not sure if it is reproducible in a single node. But when I ran multi-nodes clusters (59 nodes), the attempt to see worker logs from the UI crashed the frontend. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mfitton** [comment]
This doesn't seem reproducible. I checked to see whether I could reproduce in the `test_many_actors` stress test which runs a large cluster. I think this might have been related to what this PR fixed: https://github.com/ray-project/ray/pull/12660

Please let me know if you see it again or can reproduce.
