### ISSUE TITLE
[rllib] Could not find policy for agent

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#11644]
Hello, when my rllib was 0.8.7. It runs well. But when I update it into rllib 1.0.0, it occours:
valueError: Could not find policy for agent: agent policy id `0` not in policy map keys dict_keys(['default_policy']).

In my code, I set all of the agents was 0,

def policy_mapping(id):
    return '0'

trainer = PPOTrainer(env="2x2grid", config={
        "framework": "torch",
        "multiagent": {
            "policy_graphs": {
                '0': (PPOTorchPolicy, spaces.Box(low=np.zeros(21), high=np.array(['inf'] * 21)), spaces.Discrete(4), {})
            },
            "policy_mapping_fn": policy_mapping  
        },
        "lr": 0.001,
    })

Can I set it as this?

**Comment by sven1977** [comment]
Maybe a int (0) vs str ("0") problem?

**Comment by sven1977** [comment]
Oh, I see. Can you change "policy_graphs" into "policies"? The key "policy_graphs" has been deprecated.

**Comment by sven1977** [comment]
Also, make sure that your env is a valid RLlib MultiAgentEnv, ExternalMultiAgentEnv, or BaseEnv, not a plain gym.Env.
If you would like to use a plain gym.Env, you will have to wrap it first via e.g. `rllib/examples/env/multi_agent.py::make_multi_agent("CartPole-v0")`
Then pass the `num_agents=[int]` arg into your env_maker.

**Comment by zzchuman** [comment]
> 另外，请确保您的环境是有效的RLlib MultiAgentEnv，ExternalMultiAgentEnv或BaseEnv，而不是普通健身房。
> 如果您想使用普通的gym.Env，则必须先通过例如将其包装，`rllib/examples/env/multi_agent.py::make_multi_agent("CartPole-v0")`
> 然后将`num_agents=[int]`arg传递给您的env_maker。

Thank you! I have try to change the policy graphs to policies. It works! Thank you!
