### ISSUE TITLE
Async await not working when result is fetched from another node's object store

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#11649]
### What is the problem?

* ray 1.0.0

### Reproduction (REQUIRED)
Ray remote actor tasks can be `await`ed. However, this only works reliably when the driver and the actor run on the same ray node. If this is not the case, `await` statements can take infinitely long.

In the script below, the `OTHER_NODE` custom resource is to indicate that this actor should be scheduled a node that's different from the driver of the script.
```
import os
import numpy as np
import ray
import asyncio

head_service = os.environ.get('RAY_HEAD_SERVICE_HOST')
head_port = os.environ.get('RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY')
address = f"{head_service}:{head_port}" if head_service is not None else None
ray.init(address=address)

TOTAL_IMAGES = 10

@ray.remote(num_cpus=0,  resources={"OTHER_NODE": 1})
class ResultActor:
    def __init__(self):
        self.results = {}

    def predict(self, i, image):
        self.results[i] = image
    
    async def get_async_result(self, i):
        result = self.results.pop(i, None)
        while result is None:
            print(f"Awaiting {i}")
            result = self.results.pop(i, None)
            print(f"Done awaiting {i}")
            await asyncio.sleep(1)
        print(f"GOT RESULT FOR {i}")
        return result


result_actor = ResultActor.remote()

# SEND DATA TO ResultActor
for i in range(TOTAL_IMAGES):
    image = (np.random.random((192, 1080, 3)) * 255).astype(np.uint8)  # ~ 0.5MB
    result_actor.predict.remote(i, image)

# Async get all data
async def get_all_results():
    futs = []
    fails = 0
    for i in range(TOTAL_IMAGES):
        fut = result_actor.get_async_result.remote(i)
        futs.append(fut)
        try:
            await asyncio.wait_for(fut, timeout=5)
            print(f"SUCCESS {i}")
        except:
            print(f"FAIL {i}")
            fails += 1

    # ALTERNATIVE: Await all at the same time
    # done, pending = await asyncio.wait(futs, timeout=5)
    # if len(pending):
    #     print(f"FAILED! {int(100.*len(pending)/TOTAL_IMAGES)}% tasks not succeeded!")

    print(f"FAIL RATIO: {int(100.*fails/TOTAL_IMAGES)}%")


loop = asyncio.new_event_loop()
loop.run_until_complete(get_all_results())
```
The output of this script is:
```
2020-10-27 16:31:23,203	INFO worker.py:634 -- Connecting to existing Ray cluster at address: 10.43.87.248:6379
(pid=883, ip=10.42.0.8) GOT RESULT FOR 0
FAIL 0
(pid=883, ip=10.42.0.8) GOT RESULT FOR 1
FAIL 1
SUCCESS 2
(pid=883, ip=10.42.0.8) GOT RESULT FOR 2
(pid=883, ip=10.42.0.8) GOT RESULT FOR 3
FAIL 3
(pid=883, ip=10.42.0.8) GOT RESULT FOR 4
FAIL 4
(pid=883, ip=10.42.0.8) GOT RESULT FOR 5
FAIL 5
(pid=883, ip=10.42.0.8) GOT RESULT FOR 6
FAIL 6
SUCCESS 7
(pid=883, ip=10.42.0.8) GOT RESULT FOR 7
(pid=883, ip=10.42.0.8) GOT RESULT FOR 8
FAIL 8
(pid=883, ip=10.42.0.8) GOT RESULT FOR 9
FAIL 9
FAIL RATIO: 80%
```
As shown, we get print statements from the actor returning data, but the main process does not receive the data it is awaiting.

When the Actor is scheduled on the driver node, there is no issue.
When the data that is transfered is small (I assume <100kB) there also is no issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
This looks really problematic. We will try to repro and get back to you ASAP.

**Comment by simon-mo** [comment]
Here's a modified version that can reproduce this on a single node, using ray cluster utils:
```python
import os
import numpy as np
import ray
import asyncio
from ray.cluster_utils import Cluster

cluster = Cluster()
head_node = cluster.add_node()
child_node = cluster.add_node(resources={"OTHER_NODE": 100})

ray.init(address=head_node.address)

TOTAL_IMAGES = 10

@ray.remote(num_cpus=0,  resources={"OTHER_NODE": 1})
class ResultActor:
    def __init__(self):
        self.results = {}

    def predict(self, i, image):
        self.results[i] = image
    
    async def get_async_result(self, i):
        result = self.results.pop(i, None)
        while result is None:
            print(f"Awaiting {i}")
            result = self.results.pop(i, None)
            print(f"Done awaiting {i}")
            await asyncio.sleep(1)
        print(f"GOT RESULT FOR {i}")
        return result


result_actor = ResultActor.remote()

# SEND DATA TO ResultActor
for i in range(TOTAL_IMAGES):
    image = (np.random.random((192, 1080, 3)) * 255).astype(np.uint8)  # ~ 0.5MB
    result_actor.predict.remote(i, image)

# Async get all data
async def get_all_results():
    futs = []
    fails = 0
    for i in range(TOTAL_IMAGES):
        fut = result_actor.get_async_result.remote(i)
        futs.append(fut)
        try:
            await asyncio.wait_for(fut, timeout=5)
            print(f"SUCCESS {i}")
        except:
            print(f"FAIL {i}")
            fails += 1

    # ALTERNATIVE: Await all at the same time
    # done, pending = await asyncio.wait(futs, timeout=5)
    # if len(pending):
    #     print(f"FAILED! {int(100.*len(pending)/TOTAL_IMAGES)}% tasks not succeeded!")

    print(f"FAIL RATIO: {int(100.*fails/TOTAL_IMAGES)}%")


loop = asyncio.new_event_loop()
loop.run_until_complete(get_all_results())
\\\

**Comment by edoakes** [comment]
Did some more digging with @simon-mo, seems like this is a subtle race condition in the mess of callbacks we're using to async await for plasma objects. Think we've identified the root cause, should be able to open a PR with a fix soon.

**Comment by simon-mo** [comment]
The bug @edoakes is a false alarm. The race condition actually turned out to be somewhere between two instances of `object_manager_.CancelPull(object_id);` in:
- `TaskDependencyManager::HandleRemoteDependencyCanceled`
- `ObjectManager::HandleObjectAdded`

When we comment out the CancellPull in TaskDependencyManager, the script can run reliably 100% even when I increase the number of trials and size of images. 
```diff
diff --git a/src/ray/raylet/task_dependency_manager.cc b/src/ray/raylet/task_dependency_manager.cc
index e0b585f45..46e3af2cb 100644
--- a/src/ray/raylet/task_dependency_manager.cc
+++ b/src/ray/raylet/task_dependency_manager.cc
@@ -79,7 +79,7 @@ void TaskDependencyManager::HandleRemoteDependencyCanceled(const ObjectID &objec
   if (!required) {
     auto it = required_objects_.find(object_id);
     if (it != required_objects_.end()) {
-      object_manager_.CancelPull(object_id);
+      // object_manager_.CancelPull(object_id);
       reconstruction_policy_.Cancel(object_id);
       required_objects_.erase(it);
     }

```

Of course this won't the right fix. But this seems to identify the root cause reliably, TaskDependencyManager tries to cancel outstanding pull requests issued by CoreWorker::Get.

cc @edoakes, @stephanie-wang , @ijrsvt.

**Comment by stephanie-wang** [comment]
The TaskDependencyManager cancels outstanding pull requests once the raylet tells it the object is on longer needed by any worker on that node. This is to prevent a leak where the raylet will keep asking other nodes for an object even though no one needs it. That's also why pull requests get canceled for a ray.get with a timeout.

Took a quick look at the core worker code, and it seems like the [CoreWorker::PlasmaCallback](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L2282) never subscribes properly to the TaskDependencyManager. It does a Get with a timeout of 0 and then subscribes to local object notifications. But no one is pulling the object, so the local object notification never appears.

Seems like the right thing to do is to call TaskDependencyManager::SubscribeWaitDependencies in the raylet handler for subscribing to a plasma object. That should open a pull request to remote nodes until the objects are made local. But I'm not sure how to handle corner cases: calling `await` on an `ObjectRef` with a timeout and/or needing to reopen a pull request if the object gets evicted after it's made local.

**Comment by simon-mo** [comment]
That's awesome! I will try out using `SubscribeWaitDependencies`
