### ISSUE TITLE
[RLlib] [Tune] Can not restore Trainer when using tune.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#11658]
I was trying to load an already trained agent using restore. When I do not use tune, I can restore the agent without any issues. However, when I train an agent using ray tune, I get the following error: 

ValueError: Cannot feed value of shape (256, 256) for Tensor 'default_policy/Placeholder_default_policy/default_policy/fc_out/kernel/Adam:0', which has shape '(256, 2)'

Here is my code: 

import ray
from ray import tune
import ray.rllib.agents.dqn as dqn
from ray.rllib.utils.test_utils import check_learning_achieved

ray.shutdown()
ray.init()
config = dqn.SIMPLE_Q_DEFAULT_CONFIG.copy()
#config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0
config["num_workers"] = 1
config["env"] = "CartPole-v0"

stop = {
        "training_iteration": 50
    }

results = tune.run(
    "DQN",
    stop=stop,
    config=config,
    checkpoint_freq=20,
)

checkpoints = results.get_trial_checkpoints_paths(
    trial=results.get_best_trial("episode_reward_mean", mode="max"),
    metric="episode_reward_mean")

trainer = dqn.SimpleQTrainer(config=config, env="CartPole-v0") 
trainer.restore(checkpoints[1][0]).   [<------error]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-91-d19047ec3d57> in <module>
----> 1 trainer.restore(checkpoints[1][0])

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/tune/trainable.py in restore(self, checkpoint_path)
    474             self.load_checkpoint(checkpoint_dict)
    475         else:
--> 476             self.load_checkpoint(checkpoint_path)
    477         self._time_since_restore = 0.0
    478         self._timesteps_since_restore = 0

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py in load_checkpoint(self, checkpoint_path)
    669     def load_checkpoint(self, checkpoint_path: str):
    670         extra_data = pickle.load(open(checkpoint_path, "rb"))
--> 671         self.__setstate__(extra_data)
    672 
    673     @DeveloperAPI

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py in __setstate__(self, state)
    149         @override(Trainer)
    150         def __setstate__(self, state):
--> 151             Trainer.__setstate__(self, state)
    152             self.train_exec_impl.shared_metrics.get().restore(
    153                 state["train_exec_impl"])

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py in __setstate__(self, state)
   1154     def __setstate__(self, state: dict):
   1155         if "worker" in state:
-> 1156             self.workers.local_worker().restore(state["worker"])
   1157             remote_state = ray.put(state["worker"])
   1158             for r in self.workers.remote_workers():

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py in restore(self, objs)
    917         self.sync_filters(objs["filters"])
    918         for pid, state in objs["state"].items():
--> 919             self.policy_map[pid].set_state(state)
    920 
    921     @DeveloperAPI

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/rllib/policy/tf_policy.py in set_state(self, state)
    440         optimizer_vars = state.pop("_optimizer_variables", None)
    441         if optimizer_vars:
--> 442             self._optimizer_variables.set_weights(optimizer_vars)
    443         # Then the Policy's (NN) weights.
    444         super().set_state(state)

~/anaconda3/envs/rllib/lib/python3.7/site-packages/ray/experimental/tf_utils.py in set_weights(self, new_weights)
    193                 feed_dict={
    194                     self.placeholders[name]: value
--> 195                     for (name, value) in new_weights.items()
    196                     if name in self.placeholders
    197                 })

~/anaconda3/envs/rllib/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    956     try:
    957       result = self._run(None, fetches, feed_dict, options_ptr,
--> 958                          run_metadata_ptr)
    959       if run_metadata:
    960         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/rllib/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1155                 'Cannot feed value of shape %r for Tensor %r, '
   1156                 'which has shape %r' %
-> 1157                 (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
   1158           if not self.graph.is_feedable(subfeed_t):
   1159             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (256, 256) for Tensor 'default_policy/Placeholder_default_policy/default_policy/fc_out/kernel/Adam:0', which has shape '(256, 2)'

_Originally posted by @plutonic88 in https://github.com/ray-project/ray/discussions/11656_

**Comment by PranayPasula** [comment]
Hi @sven1977, @plutonic88,

Do you know whether this issue was ever resolved? I'm running into what looks like essentially the same issue in the same situation: shape mismatch in Adam layers while restoring a checkpointed policy.

**Comment by sven1977** [comment]
I'm just noticing that in the above script, we train with a "DQN" trainer, but then try to restore using "SimpleQ". This should certainly not work as the default models are different. Just tried the above script with using SimpleQ for both training and restoring and got no errors anymore.

**Comment by PranayPasula** [comment]
Thanks for the update. FYI, the cause of my issue is that the observation space dimension for a policy is being saved to checkpoints as an incorrect value. When restoring from checkpoint, TensorFlow creates layers with this incorrect value of inputs/outputs. I manually corrected this, and the original session.py without errors. I suspect this issue to be on my end.

**Comment by PranayPasula** [comment]
Thanks for the update. The problem I had is gone, but I'm not sure exactly why. I'll update after I figure this out.

**Comment by jeniscodes** [comment]
Now am facing the same issue, but I have used PPOConfig in trainer and build algo in evaluator to restore from the checkpoint. Did you figure out what was causing the issue before @PranayPasula
