### ISSUE TITLE
[PlacementGroup] GcsPlacementGroupTable should extends GcsTableWithJobId

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#11666]
# What is the problem?
I am working on #11467  these days, the reason for this issue is we didn't  release resource when a job is finished, so, the solution is register a job state listener when placement group manager init, but there is a pre-issue to update, the GcsPlacementGroupTable is extends `GcsTable`,  it should update to extends `GcsTableWithJobId` so that we can get all placement group belongs to a finished job.

cc @rkooo567 @ffbin    what do you think? 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.
 
- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
I think this PR will fix the issue? https://github.com/ray-project/ray/pull/11546

**Comment by rkooo567** [comment]
Also, the fundamental issue there is that Java doesn't have remove API? Does it have any equivalent API to `remove_placement_group`?

**Comment by clay4444** [comment]
> Also, the fundamental issue there is that Java doesn't have remove API? Does it have any equivalent API to `remove_placement_group`?

Do you mean to allow users to manually call remove_placement_group java api?  I think the core problem is that the placemenbt group resource is not released when the job is finished, which causes the second job submission failure.

**Comment by rkooo567** [comment]
>  core problem is that the placemenbt group resource is not released when the job is finished,

This is true, but that PR will handle the issue.

Also, we should support remove API anyway because users want to remove placement group before the job is done. We cannot always assume users will use placement group until the job is done.

**Comment by clay4444** [comment]
> > core problem is that the placemenbt group resource is not released when the job is finished,
> 
> This is true, but that PR will handle the issue.
> 
> Also, we should support remove API anyway because users want to remove placement group before the job is done. We cannot assume users will always keep placement group until the job is done.

yes, I will implements this java api~

**Comment by rkooo567** [comment]
Sounds good! I shared the design document with you :)
