### ISSUE TITLE
Possible bug with custom env

### ISSUE THREAD

**Issue by khmurakami** [ray-project/ray#1167]
I am trying to use the Ray library to import a custom env using the method in the documentation.``The name of the Env is Env which I am trying to import. The function works fine in train.py if I pass env as the argument directly instead of args.env. 
```
env = lambda: Env
config = ppo.DEFAULT_CONFIG.copy()
alg = PPOAgent(env, config)
```
The moment things get buggy is when I pass the alg variable into arg.alg. I get this error.

```
Traceback (most recent call last):
  File "RLRay.py", line 51, in <module>
    alg = PPOAgent(env, config)
  File "/home/khmurakami/.local/lib/python2.7/site-packages/ray-0.2.1-py2.7-linux-x86_64.egg/ray/rllib/agent.py", line 122, in __init__
    self._init()
  File "/home/******/.local/lib/python2.7/site-packages/ray-0.2.1-py2.7-linux-x86_64.egg/ray/rllib/ppo/ppo.py", line 96, in _init
    for _ in range(self.config["num_workers"])]
  File "/home/*******/.local/lib/python2.7/site-packages/ray-0.2.1-py2.7-linux-x86_64.egg/ray/actor.py", line 713, in remote
    ray.worker.global_worker)
  File "/home/******/.local/lib/python2.7/site-packages/ray-0.2.1-py2.7-linux-x86_64.egg/ray/actor.py", line 348, in export_actor_class
    assert False, "This should be unreachable."
AssertionError: This should be unreachable.
```

I looked inside the code at line 348 in export_actor_class and it looks like a worker.mode is not starting when it should be in some mode like Silent Mode or something of that sort. This is the line I am passing in.

### Changed
```
        runner.add_trial(
            Trial(
                env, alg, args.config, args.local_dir, None,
                args.resources, args.stop, args.checkpoint_freq, args.restore,
                args.upload_dir))
```
### Original
```
        runner.add_trial(
            Trial(
                args.env, args.alg, args.config, args.local_dir, None,
                args.resources, args.stop, args.checkpoint_freq, args.restore,
                args.upload_dir))
```
That triggers the error. I do not know what is causing it. If this is a dumb mistake please let me know. I am not sure if I am doing it right, but it shows up as PPO_custom when I run it. Thank you very much!

**Comment by ericl** [comment]
Hey Kalani, I think the issue is that "alg" should be a string and not the agent. The following snippet works for me (you'll have to replace the lambda to return an instance of your env and not CartPole of course). 

```
import gym
import ray
from ray.rllib.ppo import ppo
from ray.tune.trial import Trial
from ray.tune.trial_runner import TrialRunner

env = lambda: gym.make("CartPole-v0")
env.env_name = "my_env"   # optionally give your custom env a name
config = ppo.DEFAULT_CONFIG
alg = "PPO"


runner = TrialRunner()
runner.add_trial(Trial(env, alg, config))

ray.init()

while not runner.is_finished():
    runner.step()
    print(runner.debug_string())
```

**Comment by khmurakami** [comment]
I don't know if I should make a separate issue or theres another place for questions for this since this is kind of a different case, but

i think the example you are talking about with calling train on the agent directly is the one on the RRLIb section ,
``` 
import ray
import ray.rllib.ppo as ppo
from osim.env import RunEnv

ray.init()

#we inport Env(parameter) not using gym.make because it is a env already.  It ends up working, but the rewards don't get better unless it's something to do with the hyperparameters which we tried to change, but still nothing. 
env_creator = lambda: RunEnv(parameter)
config = ppo.DEFAULT_CONFIG.copy()
alg = ppo.PPOAgent(env_creator, config)



for i in range(10):
   # Perform one iteration of the algorithm.
  #is this where you call train() on the agent. 
   result = alg.train()
   print("result: {}".format(result))
   print("checkpoint saved at path: {}".format(alg.save()))
```

So i just replaced the example with the custom env. I call the env using a import which is made to be for OpenAI gym. When I use PPO agent on a OpenAI gym I can see the reward changing over time, but with a custom env, I don't see anything happening. Do you thing it's something with the custom env? The reason for that is, the custom env didn't work for the function def reset inside env.py inside of the ppo folder. We had to go inside and change the 'self.preprocessor.transform' for the variable observations and change [None] -> [:] and then change that into a numpy float array because for some reason it wasn't reading the Env properly or something like that. Does the Lambda have to take a string from gym.make to work with the Lambda function for it to compute rewards properly? Thank you!

**Comment by robertnishihara** [comment]
Are you still seeing this problem? It's possible that there's a bug in the custom env. It's also possible that the algorithm just isn't learning very well in the env.

**Comment by ericl** [comment]
Closing stale issue -- feel free to re-open if you're still seeing this.
