### ISSUE TITLE
Questions on Slurm Instructions

### ISSUE THREAD

**Issue by parthjaggi** [ray-project/ray#11671]
### Describe your feature request/question:

Having a look at the script provided on:
https://docs.ray.io/en/master/cluster/slurm.html

Short snippet:
```
#!/bin/bash
#SBATCH --job-name=test
#SBATCH --cpus-per-task=5
#SBATCH --mem-per-cpu=1GB
#SBATCH --nodes=4
#SBATCH --tasks-per-node=1
```

1. This script does not have values given for `#SBATCH --ntasks`. Is this something the user has to provide?
If I understand correctly then `--ntasks` acts as number of workers we want to create.

2. If above is true, why do we need to specify the number of nodes in the script: `#SBATCH --nodes=4`?
I am not sure, how node count should matter. If sufficient cores are provided so that they can be broken into different workers, node count should not be relevant.

3. Also what affect will the parameter `--tasks-per-node` have on the rllib run.

**Comment by rkooo567** [comment]
cc @richardliaw
