### ISSUE TITLE
[core] Support log rotation in Ray services

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#11688]
When the ray cluster runs for a long time or execute many tasks, log files can be large, such as `monitor.err`, full of `could not find ip for client xxxx`. I find parameters `logging_level`, `logging_format` and `log_to_driver ` in `ray.init()`. Is there a way to restrict the size of log files by default, like using `logging.handlers.RotatingFileHandler` and set maxBytes?

![image](https://user-images.githubusercontent.com/20527302/97453044-53545780-1970-11eb-8cb9-6ce4bd8dde69.png)

_Originally posted by @crystalww in https://github.com/ray-project/ray/discussions/11672_

**Comment by rkooo567** [comment]
I am working on this now.

**Comment by edoakes** [comment]
@rkooo567 can we close this?

**Comment by rkooo567** [comment]
We might need to revert this change, so I’d keep it open until that decision’s finalized

**Comment by rkooo567** [comment]
This is done
