### ISSUE TITLE
[Placement Group] Default actors won't be scheduled with placement groups.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#11692]
### What is the problem?

```
@ray.remote
class A:
    pass
a = A.options(placement_group=pg).remote()
```

This won't work because the default actor arguments have num_cpus=0. It means there's no resource that will be scheduled on the placement group-fied resources.

We should create some noop resources for the placement group, and add this resource requirements to all actors and tasks implicitly so that we can avoid this issue. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@clay4444 Do you have bandiwidth to work on this issue? 

Also, @richardliaw Do you think this is a blocker for tune integration?

**Comment by rkooo567** [comment]
Hey @clay4444 Are you in progress with this issue?

**Comment by clay4444** [comment]
> Hey @clay4444 Are you in progress with this issue?

sorry about for delay days this issue...  I was busy on double eleven before, I will fix this within 2 days.

**Comment by rkooo567** [comment]
@clay4444 After discussing with Eric, we just decided to disallow placement group scheduling with 0 resources.
