### ISSUE TITLE
ray serve - model upgrade failing for Tensorflow keras model

### ISSUE THREAD

**Issue by kumarvc** [ray-project/ray#11691]
### What is the problem?
For traffic split testing, Model upgrade is failing in [ray serve] for tesnsorflow model. I am able to run demo to upgrade sklearn model but not tensorflow keras model.

I used below statement to connect and create backend for version 2 but it 's failed at stage 2 during backend creation. 
client = serve.connect()
client.create_backend("tf:v2", TFVechileModelv2, TRAINED_MODEL_PATH_V2)
client.set_traffic("tf_vechile_classifier", {"tf:v2": 0.25, "tf:v1": 0.75})

Ray dashboard provides below reason for the error.
Error: Traceback (most recent call last): File "/home/osboxes/miniconda3/envs/ray-serve/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 130, in _handler_route return await handler(bind_info.instance, req) File "/home/osboxes/miniconda3/envs/ray-serve/lib/python3.8/site-packages/ray/new_dashboard/modules/stats_collector/stats_collector_head.py", line 146, in get_errors ip = req.query["ip"] KeyError: 'ip' 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.8.5
tensorflow 2.3.1
ray '1.1.0.dev0'
Ubuntu 19.10

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @mfitton

**Comment by edoakes** [comment]
@kumarvc does the call to `set_traffic` fail and throw an exception? Or is the only error you're seeing the error from the dashboard?

**Comment by mfitton** [comment]
There's no reason a dashboard failure would affect the model upgrade, but it'll still be good for me to look into this issue, as the dashboard should be the natural way to debug this.

**Comment by kumarvc** [comment]
@edoakes, Call to set_traffic fail and throw an exception and hence unable to perform split testing for tensorflow model

**Comment by edoakes** [comment]
@kumarvc I see, that's not good. Is it possible for you to provide a standalone script that will reproduce the issue? If you can provide that we should be able to fix it in short order.
