### ISSUE TITLE
[rllib] Behavior Cloning leaks memory

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#11754]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Behavior Cloning leaks memory. Using `timesteps_per_iteration` will make leakage much faster.

I am using Ray 1.0.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

#### Setting
First, I generate the dataset using the way in `ray/rllib/tuned_examples/marwil/cartpole-bc.yaml`, but changing the dataset size from 50,000 to 200,000:

```bash
rllib train --run=PPO --env=CartPole-v0 --stop='{"timesteps_total": 200000}' --config='{"output": "/tmp/out", "batch_mode": "complete_episodes"}'
```

Then I run the script `test.yaml` identical to the example yaml but with larger stopping criterion, via: `rllib train -f test.yaml`:

```bash
# test.yaml
cartpole-bc:
    env: CartPole-v0
    run: BC
    stop:
        timesteps_total: 5000000  # <<== Here
    config:
        # Works for both torch and tf.
        framework: tf
        # In order to evaluate on an actual environment, use these following
        # settings:
        evaluation_num_workers: 1
        evaluation_interval: 1
        evaluation_config:
            input: sampler
        # The historic (offline) data file from the PPO run (at the top).
        input: /tmp/out
        timesteps_per_iteration: 10000  # <<== Here!!!!
```

#### With `timesteps_per_iteration `
Then I find the memory increases linearly. 

The first iteration, the memory cost is:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/22206995/97874156-8a9d7c80-1d53-11eb-92c7-5a0f245041b3.png">

After 2.3M step, 180s (printed time, not exactly time), the memory goes to 6.3G.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/22206995/97879436-eddedd00-1d5a-11eb-983b-be832f7c7140.png">

So if `timesteps_per_iteration ` is turn on, the memory goes **from 4.9 G to 6.3 G in 2.3M steps** in a linear manner. The memory is leaked in a very fast speed, if using larger dataset, until the OOM happens.

#### Without `timesteps_per_iteration `

If we close the option `timesteps_per_iteration `, the memory is gradually increased from 6.2G to 6.8G and will still goes to OOM, but the speed is much slower than with `timesteps_per_iteration`.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/22206995/97880130-bd4b7300-1d5b-11eb-9180-1bf639ba8c2b.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/22206995/97880813-93df1700-1d5c-11eb-9ace-eafdeef905c6.png">

I have tried this on larger dataset and the memory leak is even more drastic, so the result here is only to reproduce the issue. For your information, I find that the incremental memory is exactly the size of the offline dataset. 

#### Another issue

By the way, **the printed time (`time_total_s`) is incorrect in BC**. The real-world time elapses much much faster than the printed time. I am not sure why.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by pengzhenghao** [comment]
I think the issue is related to #9961 .

The document say `replay_buffer_size ` refer to the steps, while in practice it refers to the number of batches. This is extremely misleading.

```
    # Number of steps max to keep in the batch replay buffer.
    "replay_buffer_size": 100000,
```

**Comment by sven1977** [comment]
Closing this. This has been fixed here:
https://github.com/ray-project/ray/pull/10957 (not part of ray 1.0.0, only available in current master!).
A warning has been added and a counting bug related to returning the correct buffer size has been fixed.
