### ISSUE TITLE
[Core] Ray breaks alignment for NumPy arrays of doubles

### ISSUE THREAD

**Issue by ienkovich** [ray-project/ray#11760]
### What is the problem?
I'm using Ray 1.0.0 with Python 3.8.3 on Ubuntu 18.04

When I use Ray to serialize/deserialize a NumPy array of doubles, I get an unaligned NumPy array (data is not 8-byte aligned).

### Reproduction

Here is a reproducer I use
```
import numpy as np
import ray
ray.init()

arr1 = np.array([10.1, 20.2, 30.3], dtype = np.double)
oid = ray.put(arr1)
arr2 = ray.get(oid)

ptr1 = arr1.__array_interface__["data"][0]
print(f"Original address: 0x{hex(ptr1)} - {'un' if ptr1 % 8 != 0 else ''}aligned")
assert(ptr1 % 8 == 0)
ptr2 = arr2.__array_interface__["data"][0]
print(f"Deserialized address: 0x{hex(ptr2)} - {'un' if ptr2 % 8 != 0 else ''}aligned")
assert(ptr2 % 8 == 0)
```

The output is:
```
Original address: 0x0x56150a88c9d0 - aligned
Deserialized address: 0x0x7f738756010c - unaligned
Traceback (most recent call last):
  File "1.py", line 14, in <module>
    assert(ptr2 % 8 == 0)
AssertionError
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
Is this a regression from Ray 0.8 series?

**Comment by robertnishihara** [comment]
I think we actually want the arrays to be 64-byte aligned for performance reasons. I know we guaranteed that when we were using pyarrow for serialization. @pcmoritz @suquark

**Comment by ericl** [comment]
Interesting, so this may have been broken for some time now.

**Comment by vnlitvinov** [comment]
Food for thought: I've tried pickling and unpickling back (by using builtin `pickle` module and calling `pickle.loads(pickle.dumps(arr, -1))`), and unpickled array is properly aligned, while retrieved via Ray is not.

**Comment by rkooo567** [comment]
@ericl What's the action item here?

**Comment by suquark** [comment]
@robertnishihara I almost sure when moving from pyarrow to pickle5, the buffer is still aligned:

https://github.com/ray-project/ray/blob/28e7439cf049bc54774f77d5a4dc166565aa7e3b/python/ray/includes/serialization.pxi#L301-L307

For large chunks, we align the buffer to 64 bytes(kMajorBufferAlign); for small chunks, we align it to 8 bytes (kMinorBufferAlign).

**Comment by pcmoritz** [comment]
@suquark Could it be that the relative addresses are aligned, but not the start? Maybe we need to make sure to make `ptr` aligned in here: https://github.com/ray-project/ray/blob/master/python/ray/includes/serialization.pxi#L360

Can you test that and create a PR for it?

**Comment by robertnishihara** [comment]
@suquark it's definitely not aligned right now, e.g.,

```
import ray
import numpy as np
ray.init()
x = ray.get(ray.put(np.zeros(10**8)))
x.ctypes.data % 64  # This is often (always?) 12 for me. Not that I tried larger arrays in case the different code paths for smaller objects change things.
```
