### ISSUE TITLE
[tune] Best way to tune hundreds of models

### ISSUE THREAD

**Issue by andrewredd** [ray-project/ray#11764]
# Describe your feature request

I need to tune several hundred XGBoost models. I'm planning on using a machine with 112 cores, implementing early stopping at the trial level (not using hyperband) and allowing the algorithm to have 4 cores to per trial. I'm planning on sequentially looping through each model (out of roughly 200 and tuning them individually) I have three questions:

1) Is there a better way to do this?
2) I have access to a YARN/Spark cluster with many workers capable of training these models. Is there a way to have Ray speak to these workers instead of needing to tune on a single, large machine? Is there a framework recommended to easily access more compute from GCP?
3) Is there a way to use the slack compute power as one model is finishing tuning? (i.e. queuing up the next model to begin running as soon as the previous model is finished running the maximum number of trials)

**Comment by richardliaw** [comment]
cc @krfricke
