### ISSUE TITLE
[Wheel] Cannot import `dataclasses` module after installing Ray on MacOS with Python3.6

### ISSUE THREAD

**Issue by goelakash** [ray-project/ray#11773]
### What is the problem?
Ray installation for MacOSX and Python 3.6 is missing the dataclasses module, which is only packaged Python 3.7 onwards, and is required to be installed separately by the user for older python versions. This should be automatically installed (as fixed by this commit - https://github.com/ray-project/ray/commit/67c653c0537c1a6ce8e87799e55e34cdcd037550). Maybe this commit isn't built into the wheels yet.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray versions tested are:
1.0.0 (stable)
1.1.0.dev0 (nightly)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
(Platform - MacOSX, Python 3.6)

1. Ray 1.0.0

```
pip install ray ray[rllib] ray[tune]
python
import dataclasses
```
2. Ray 1.1.0.dev0
```
pip install ray ray[rllib] ray[tune]
ray install-nightly
python
import dataclasses
```

If we cannot run your script, we cannot fix your issue.

- [x ] I have verified my script runs in a clean environment and reproduces the issue.
- [ x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @architkulkarni Can you take a look at this? I believe you made a PR about this.

**Comment by rkooo567** [comment]
Please try https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1604425438226300?thread_ts=1604362613.219300&cid=C01DLHZHRBJ

**Comment by architkulkarni** [comment]
The fix actually was already in the nightly wheels.  After installing the nightly wheel, to update dependencies, you still have to run `pip install "ray[rllib]" "ray[tune]"` again, according to the note here https://docs.ray.io/en/master/installation.html.
