### ISSUE TITLE
Strange behavior of num_workers

### ISSUE THREAD

**Issue by joschu** [ray-project/ray#1179]
I've noticed some strange behavior related to how many workers ray starts. Probably not a bug, but maybe you can provide some more helpful messages to the user.

First of all, when I do `ray.init(num_workers=1)`, ray initially starts one worker, but later starts a second one at some point during the computation.

Second, I start a head node with `--num-workers=4`, and I start bunch of workers, all with `--num-workers=4` on remote machines. Then when I look at `ray.global_state.workers()`, the head node has 4 workers and the worker nodes each have 8 workers.

**Comment by joschu** [comment]
Actually for the second item, I may be doing something wrong. I made a minimal example, and there are only 4 workers on the remote nodes as requested.

**Comment by atumanov** [comment]
@joschu , try `--num-cpus 4` and `ray.init(num_cpus=4)` instead. Ray scheduler allocates and tracks virtual resource capacity. There are some cases where it's desirable to temporarily allow the number of worker processes to exceed the number of configured cores. `--num-workers` literally means how many workers will be started, but it does not guarantee that it will stay constant.  This is useful in some cases, e.g. starting ray on manycore nodes and avoiding instantiation of 128 worker processes, when debugging and interacting with the object store. We could consider deprecating this option. Configuring your virtual resource capacity (i.e., number of CPUs and GPUs) is a strong signal and that number doesn't change.

**Comment by joschu** [comment]
I see, thanks for the explanation.

**Comment by robertnishihara** [comment]
Closing for now. This should be clarified by #1201.
