### ISSUE TITLE
Linux nightly wheels on documentation return 404

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#11801]

**Comment by devin-petersohn** [comment]
I also tried a number of git hashes and they were not working for me either. Are the wheels being built and uploaded properly?

**Comment by rkooo567** [comment]
There's an issue with latest doc. It should work if you use the master doc https://docs.ray.io/en/master/index.html

**Comment by devin-petersohn** [comment]
Linux wheels are not accessible from that link either.

**Comment by rkooo567** [comment]
Hmm I think we are currently failing to push wheels after we started using manylinux10. Let me get back to you

**Comment by simon-mo** [comment]
For a workaround change the manylinux2014 -> manylinux1 in the url, e.g.:
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp36-cp36m-manylinux1_x86_64.whl

This should give you access to linux wheels from Nov. 3 before 05c4e3fb2a3b36ceea90cac4104d8466a0cc2ac5

**Comment by simon-mo** [comment]
We just merged a PR from @ijrsvt that will hopefully resolve this issue, will keep this updated.

**Comment by simon-mo** [comment]
Should be fixed now, please check it out: https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies
