### ISSUE TITLE
[rllib] AttributeError: 'MetricsContext' object has no attribute 'counter' 

### ISSUE THREAD

**Issue by AlexandraVolokhova** [ray-project/ray#11813]
Hello! 

I tried to run Dreamer and got `AttributeError: 'MetricsContext' object has no attribute 'counter' `

That happens because of the typo here:
https://github.com/ray-project/ray/blob/92718de40c6ee67e37b25988d7f3c9f72df4dcb4/rllib/agents/dreamer/dreamer.py#L202

It should refer to `counters` instead of `counter` as follows: 
`metrics.counters[STEPS_SAMPLED_COUNTER] *= self.repeat`

I fixed it locally and managed to run Dreamer.

**Comment by rkooo567** [comment]
cc @sven1977
