### ISSUE TITLE
[Tune] Wait for instances to spin up before giving up on jobs

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#11855]
I am using Ray 1.1 dev0 installed from wheel.

If you run "ray submit --start ... " with AWS, and you are starting a new cluster, the "submit" will get killed if you are waiting on worker nodes to spin up:

`ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 4 CPUs, 1 GPUs, but the cluster has only 0 CPUs, 0 GPUs, 8.64 GiB heap, 2.98 GiB objects (1.0 node:10.0.0.225). Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available.
`

It seems the appropriate behavior here is to wait for the worker nodes to get online and then try submitting the job.

**Comment by rkooo567** [comment]
cc @krfricke

**Comment by richardliaw** [comment]
@richardrl do you set `queue_trials=True`?

**Comment by richardliaw** [comment]
Fixed with queue_trials=True

**Comment by richardrl** [comment]
Yea for anyone reading this, set `queue_trials=True` in `tune.run(...)`
