### ISSUE TITLE
[launching cluster] `ray up` on Kubernetes failing

### ISSUE THREAD

**Issue by aaronhmiller** [ray-project/ray#11850]
### What is the problem?
Following the documentation: https://docs.ray.io/en/latest/cluster/launcher.html

When running `ray up example-full.yaml` receive an error:

jsonschema.exceptions.ValidationError: Additional properties are not allowed ('rsync_filter', 'rsync_exclude' were unexpected)

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray --version: `ray, version 1.0.0`
python --version: Python 3.7.3
OS version: MacOS X 10.15.7
kubectl version: ```Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
1. connect to your Kubernetes cluster and verify with `kubectl get nodes`
2. [it shouldn't matter, but I was using EKS]
3. run `ray up ray/python/ray/autoscaler/kubernetes/example-full.yaml
4. receive the error above about rsync_filter and rsync_exclude

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
^^ tried to install latest wheel, but received 404 on pulling the .whl file: ```ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl
ERROR: Could not install requirement ray==1.0.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.0.0-cp37-cp37m-macosx_10_13_intel.whl```

**Comment by Gekho457** [comment]
Try commenting out the lines involving `rsync_exclude` and `rsync_filter` in `ray/python/ray/autoscaler/kubernetes/example-full.yaml`
and, just in case, also in
`ray/python/ray/autoscaler/kubernetes/defaults.yaml`
These options aren't compatible with Ray 1.0.0.

**Comment by aaronhmiller** [comment]
Thank you @Gekho457. I'll submit a tiny PR to update those. Both indicate the options are not compatible w/ K8S.
