### ISSUE TITLE
[cli] `ray rsync-up YAML`  ignores the excluded files

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#11863]
I think `ray rsync-up` currently ignores the excluded files in the YAML (it does not exclude anything)

_Originally posted by @richardrl in https://github.com/ray-project/ray/issues/10216#issuecomment-723190040_

**Comment by vinamrabenara** [comment]
when we set ```file_mounts_sync_continuously: True``` in the YAML, what events will trigger a rsync? Will mere file modifications trigger automatic rsync?
