### ISSUE TITLE
Plasma manager failed to start, retrying now.

### ISSUE THREAD

**Issue by electronick1** [ray-project/ray#1186]
Getting this error (see screenshot). 
Tried "docker - anaconda" setup, and MacOs setup - same errors in both cases. 

Can you please say what I missed or this is smth in ray ? 

My Dockerfile -> https://gist.github.com/electronick1/e9a48862a149377418a29bbdbca9f8cf
My docker-compose -> https://gist.github.com/electronick1/99e6d2967414abdf5d1a6b841e437f50
<img width="640" alt="screen shot 2017-11-06 at 10 35 06 pm" src="https://user-images.githubusercontent.com/5982083/32460586-f40121ce-c33b-11e7-8617-047a44428f9e.png">

Also is it possible to check any logs to see what actually reason behind " Plasma manager failed .."

Thanks for advice

**Comment by robertnishihara** [comment]
Hmm.. one comment is that when you `pip install ray`, that already includes a redis-server executable, so you don't need to provide that yourself (unless you're using Redis separately). However, that probably shouldn't cause things to fail.

You can check the log files in `/tmp/raylogs` and see if there is anything there.

On one of the machines, can you try just running the following in Python?

```python
import ray
ray.init()
```

and see if that succeeds or fails?

Once you've done that, can you check which processes are currently running?

E.g., see if the plasma store is running via

```
ps aux | grep "plasma_store "
```

See if the redis servers are running (there should be two) via

```
ps aux | grep "redis-server "
```

See if the plasma manager is running via

```
ps aux | grep "plasma_manager "
```

**Comment by electronick1** [comment]
For ray.init() getting this 
<img width="635" alt="screen shot 2017-11-07 at 5 55 14 pm" src="https://user-images.githubusercontent.com/5982083/32499943-a5433b70-c3dc-11e7-9a27-b89f05e9ece9.png">

For ps commands, getting this:
<img width="602" alt="screen shot 2017-11-07 at 5 56 00 pm" src="https://user-images.githubusercontent.com/5982083/32499964-aec6926e-c3dc-11e7-93a9-264afcbc2fe5.png">

For /tmp/raylogs  :(
<img width="364" alt="screen shot 2017-11-07 at 5 56 19 pm" src="https://user-images.githubusercontent.com/5982083/32499996-c29f1b62-c3dc-11e7-9170-e2d84932c547.png">


You mentioned that it should be two redis servers ? Why ?

**Comment by electronick1** [comment]
I think, the problem in IP address that head command creating.
I can connect to "redis:6379" and stuff, but there is no chance to connect to head node with defined ip address (172.23.0.6:6379).

Also head process exit each time with code 0 🤔
  
<img width="638" alt="screen shot 2017-11-07 at 6 48 49 pm" src="https://user-images.githubusercontent.com/5982083/32502729-317ceec2-c3e4-11e7-85fc-fbadece579f9.png">

<img width="636" alt="screen shot 2017-11-07 at 6 51 07 pm" src="https://user-images.githubusercontent.com/5982083/32502757-490399e2-c3e4-11e7-835c-d0a72a8daca7.png">

**Comment by electronick1** [comment]
BTW, there is no chance to see processes because head restarting every time, 
and "/tmp/raylogs" - does not exists :(

**Comment by kunalgosar** [comment]
Getting the same issue after building ray from source (current master).

```
(ray-dev) [kunalgosar@Kunals-MacBook-Pro ray (cdf94c18 ✗)]$ python 
Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 16:25:05) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
ray>>> ray.init()
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:53556 to respond...
Waiting for redis server at 127.0.0.1:11865 to respond...
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Plasma manager failed to start, retrying now.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kunalgosar/research/ray/python/ray/worker.py", line 1640, in init
    use_raylet=use_raylet)
  File "/Users/kunalgosar/research/ray/python/ray/worker.py", line 1475, in _init
    use_raylet=use_raylet)
  File "/Users/kunalgosar/research/ray/python/ray/services.py", line 1696, in start_ray_head
    use_raylet=use_raylet)
  File "/Users/kunalgosar/research/ray/python/ray/services.py", line 1423, in start_ray_processes
    use_raylet=use_raylet)
  File "/Users/kunalgosar/research/ray/python/ray/services.py", line 1085, in start_objstore
    stderr_file=manager_stderr_file)
  File "/Users/kunalgosar/research/ray/python/ray/plasma/plasma.py", line 189, in start_plasma_manager
    raise Exception("Couldn't start plasma manager.")
Exception: Couldn't start plasma manager.
```

Processes:

```

[kunalgosar@Kunals-MacBook-Pro ray (cdf94c18 ✗)]$ ps aux | grep "plasma_store "

kunalgosar       12428   0.0  0.0  4267752    636 s003  R+    5:50PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn plasma_store 
kunalgosar       12160   0.0  0.0  4271100    704 s002  S+    5:46PM   0:00.01 /Users/kunalgosar/research/ray/python/ray/plasma/../core/src/plasma/plasma_store -s /tmp/plasma_store46148307 -m 6871947673
kunalgosar        5091   0.0  0.0  4271100    476 s002  S     5:28PM   0:00.01 /Users/kunalgosar/research/ray/python/ray/plasma/../core/src/plasma/plasma_store -s /tmp/plasma_store66693819 -m 6871947673
[kunalgosar@Kunals-MacBook-Pro ray (cdf94c18 ✗)]$ ps aux | grep "redis-server "
kunalgosar        5086   0.2  0.0  4309656   1396 s002  S     5:28PM   0:02.79 /Users/kunalgosar/research/ray/python/ray/core/src/common/thirdparty/redis/src/redis-server *:21509      
kunalgosar       12155   0.1  0.0  4309656   1436 s002  S+    5:46PM   0:00.57 /Users/kunalgosar/research/ray/python/ray/core/src/common/thirdparty/redis/src/redis-server *:53556      
kunalgosar       12441   0.0  0.0  4258468    184 s003  R+    5:50PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn redis-server 
kunalgosar       12156   0.0  0.0  4309656   1188 s002  S+    5:46PM   0:00.16 /Users/kunalgosar/research/ray/python/ray/core/src/common/thirdparty/redis/src/redis-server *:11865      
kunalgosar        5087   0.0  0.0  4309656   1172 s002  S     5:28PM   0:00.75 /Users/kunalgosar/research/ray/python/ray/core/src/common/thirdparty/redis/src/redis-server *:31019      
[kunalgosar@Kunals-MacBook-Pro ray (cdf94c18 ✗)]$ ps aux | grep "plasma_manager "
kunalgosar       12454   0.0  0.0  4267752    692 s003  R+    5:50PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn plasma_manager 
```

**Comment by kunalgosar** [comment]
Resolved the issue above ^ - seems that the dependencies silently failed to build in the setup script. Running the `build.sh` script separately as root, solved the problem for me.

**Comment by robertnishihara** [comment]
The code has changed enough that I think this issue is no longer relevant.
