### ISSUE TITLE
Asyncio equivalent of ray.wait

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#11860]
### Describe your feature request
Currently `await asyncio.wait([object_ref])` will still call a ray.get under the hood. This incurs data transfer overhead. We are missing a ray.wait equivalent that doesn't pull the data.

**Comment by edoakes** [comment]
To be precise, it doesn't actually call `ray.get` under the hood, but it does fetch the data using a similar mechanism (just want to avoid potential confusion for readers).

**Comment by edoakes** [comment]
bump

**Comment by edoakes** [comment]
duplicate
