### ISSUE TITLE
Valgrind for Python C extensions

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#119]
We should make sure to set up valgrind for our C extensions to make sure there are no memory leaks in there. This will requires some custom handling to make sure all the spurious warnings from Python are removed:

https://github.com/python/cpython/blob/master/Misc/README.valgrind

We probably need to compile our own python for these valgrind tests.

**Comment by robertnishihara** [comment]
Closing because we no longer use Python C extensions.
