### ISSUE TITLE
[CLI] Add option to `ray memory` to print object store usage for all nodes

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#11904]
### Describe your feature request

Right now running `ray memory` only prints the memory usage info of the current node. Can we add an option so that it prints the memory usage info for **all** nodes?

Is it also possible to show a `used/total_available` statistic so that I can tell if the object store is (close to) full?

**Comment by rkooo567** [comment]
That sounds like a good idea. Btw, this is already all available if you use the dashboard. (But I agree to port this to CLI).

**Comment by ericl** [comment]
It seems this is already the case. The raylet internally collects stats from all nodes, so sending a request to any node will do.
