### ISSUE TITLE
How to extract pytorch model weights from rllib?

### ISSUE THREAD

**Issue by xuehy** [ray-project/ray#11903]
How can I export the pytorch policy model to pytorch jit file or `pth` file after trained with rllib `PPOTrainer`? I want to deploy the model to some critical environments where the ray framework is not allowed to be installed.

I have found that the model weights can be obtained by `PPOTrainer.get_policy().get_weights()`. 
```
  checkpoint = trainer.get_policy().get_weights()
   with open('ray_torch_model.pkl', 'wb') as f:
            pickle.dump(checkpoint, f)
```
But how can I obtain the model structures so that I can rebuild the model without rllib?

**Comment by rkooo567** [comment]
cc @ericl

**Comment by eadlam** [comment]
https://github.com/ray-project/ray/pull/13989
