### ISSUE TITLE
[tune] why one trial stops running when use pbt?

### ISSUE THREAD

**Issue by noprohuangqi** [ray-project/ray#11906]
### Describe your feature request

When I use PBT for training, for example there are four trials. And I found sometimes one trail will stop at one epoch  and other trials will work normally. Of course this can be solved by use `synch=True` , but I really want to know why this happend. I am sure this situation is not caused by resourse.Is it some internal mechanism in PBT that causes this problem?

**Comment by amogkam** [comment]
@noprohuangqi thanks for bringing this up; this is odd behavior and I don’t think it has to do with resources. Could you provide more info on your setup? Do you have any stopping conditions set? It would be great if you could share your code as well as the console output.
