### ISSUE TITLE
[CORE] Starting many Actors increases RAM usage

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [ray-project/ray#11919]
Hi,

I'm running a test script for understanding if the problem was my code but I get the same behaviour even with a dummy code like this.

```
import random
import ray
@ray.remote
class Model(object):

	def __init__(self,i):
		self.id=i
		self.counter=0

	def add(self):
		self.counter=self.counter+random.randint(0,10)


class ManyModels(object):
	"""docstring for ManyModels"""
	def __init__(self):
		self.models=[]


	def add_model(self,i):
		model = Model.remote(i)
		self.models.append(model)

	def step(self):
		for model in self.models:
			model.add.remote()

def main():
	ray.init()
	num=1000
	sim=ManyModels()

	for i in range(num):
		sim.add_model(i)

	sim.step()

        ray.shutdown()


if __name__ == '__main__':
	main()
```

If I increase the number of actors it eats up all the RAM and gives this warning

`	WARNING worker.py:1779 -- WARNING: 234 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.`

I have tried to read the related issue but I was not able to understand.

Can anyone help me in parallelizing the above code without eating up all the memory?

Obviously, my real code is more complex and uses complex objects with respect to this dummy test.

**Comment by rkooo567** [comment]
By default, actor's remote task sets num_cpus=0. That says, you can oversubscribe actors if you create a lot of them.

Each actor needs a single process to be started. Some solutions;

1. Use many nodes to start many actors and set `num_cpus` to avoid oversubscription. For example,
```python3
@ray.remote(num_cpus=0.5) # Will make max num_cpus in the cluster * 2 actors
class Actor
    pass
```
