### ISSUE TITLE
[rllib] ES and ARS agents cannot handle observation of type list

### ISSUE THREAD

**Issue by danuo** [ray-project/ray#11913]
### What is the problem?
There is a bug that occurs when training is done with either "ES" or "ARS" agent. When one uses a custom environment with observation of type `list` and `len(list)=1`, the training crashes. This is because internally, the list `observation = [0]` gets converted into type `int`, which many functions in place cannot handle. Here are some of the errors:
`box.py`:
```
return x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)
AttributeError: 'int' object has no attribute 'shape'

observation[None] -> int not subscriptable
```

### Reproduction (REQUIRED)
```python3
from ray import tune
import gym, numpy
from gym.spaces import Discrete, Box

class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = 10
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(
            0.0, self.end_pos, shape=(1, ), dtype=numpy.float32)
    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]
    def step(self, action):
        assert action in [0, 1], action
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1.0 if done else -0.1, done, {}

tune.run(
    "ES", # or "ARS"
    name = "Bugreport",
    checkpoint_at_end = True,
    config = {"env": SimpleCorridor,},
    stop = {"timesteps_total": 250_000,}
    )
```

I will produce a PR to fix the issue. Since there are many different ways to fix this, please have a look if my approach is the most simple / general.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Closing this issue as per the PR: https://github.com/ray-project/ray/pull/11914.
