### ISSUE TITLE
[Docker] Cannot import ruamel.yaml on ray Docker images

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#11925]
### What is the problem?
* I cannot run `python -c "import ruamel.yaml"`, but when I run `pip install ruamel.yaml` it claims it is already installed.
* `pip show ruamel.yaml`
```
Name: ruamel-yaml
Version: 0.15.87
Summary: ruamel_yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
Home-page: UNKNOWN
Author: Anthon van der Neut
Author-email: a.van.der.neut@ruamel.eu
License: UNKNOWN
Location: /root/anaconda3/lib/python3.7/site-packages
Requires: 
Required-by: conda
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
sounds like a path issue? `python -c 'import sys; print(sys.path)'`

**Comment by ijrsvt** [comment]
Solution:
```
conda install ruamel.yaml
```

**Comment by ijrsvt** [comment]
@richardliaw The part that is weird is that before the `conda install`, the directory `root/anaconda3/lib/python3.7/site-packages/ruamel_yaml` existed **and  `import ruamel_yaml` worked**.

**Comment by ijrsvt** [comment]
The output is also: 
```
['', '/root/anaconda3/lib/python37.zip', '/root/anaconda3/lib/python3.7', '/root/anaconda3/lib/python3.7/lib-dynload', '/root/anaconda3/lib/python3.7/site-packages']
```
and `$PATH` is:
```
/root/anaconda3/bin:/root/anaconda3/condabin:/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

```
