### ISSUE TITLE
[Dashboard] Blank screens when clicking on expand buttons

### ISSUE THREAD

**Issue by TanjaBayer** [ray-project/ray#11932]
#### Setup
* ray 1.1.0.dev0
* python 3.7
* multinode-setup (2 nodes) in docker on mesos dcos (but I can also reproduce it in single node setup)
* Browser: chromium browser Version 86.0.4240.75 on ubuntu 18.04

After starting a node screen turns blank and console error appears:
![image](https://user-images.githubusercontent.com/30770185/98787874-5afc0d80-2400-11eb-8ef4-a9a35e5b474a.png)

### Reproduction (REQUIRED)
I did some tests and was able to reproduce it like this:

run python docker: `docker run --net host -it python:3.7 bash `
``` bash
pip install -U ray
ray install-nightly
ray start --head
python
```
In the python terminal
``` python
import ray
ray.init()
@ray.remote
def test():
    import time
    time.sleep(10)
    print('finished')
test.remote()
```

Running the test.remote() results in the blank screen

Related on slack:
https://ray-distributed.slack.com/archives/CP950VC76/p1603863841085400

**Comment by mfitton** [comment]
@TanjaBayer Thanks for reporting this. @ijrsvt hit the same issue. I'm working on a fix for this now.

**Comment by mfitton** [comment]
@rkooo567 I just made a PR to fix this: https://github.com/ray-project/ray/pull/11954 could you take a look when you have a chance? I'll check back to make sure tests pass CI in an hour or so.
