### ISSUE TITLE
[rllib] Issue with changing name of checkpoint save file

### ISSUE THREAD

**Issue by Pagariya** [ray-project/ray#11955]
Hello, I am using Rllib for some of our research. While working with RLlib we want to change the name of the file (Checkpoint_{}) where the checkpoint is saved with the .save() function. How can I achieve this?

Thanks 
Anshul

**Comment by richardliaw** [comment]
I think this is not possible. What is your use case?

**Comment by Pagariya** [comment]
We are using it for Robotic Arm Control. We want to change the name of the checkpoint with the name having some metadata of training.
