### ISSUE TITLE
[rllib] PPO ICM learning rate

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#11971]
Hello, I know the default ppo learning rate is 5e-5, default curiosity learning rate is 0.001. 
I just want to know whether the two learning rate are same?   

If I use curiosity in ppotrainer, how do I set it?
Thank you!

**Comment by sven1977** [comment]
Hey @zzchuman , no they are not the same. The curiosity module has its own optimizer and lr.
You can set the curiosity lr inside the exploration_config key, the same way as it's done in rllib/utils/explorations/tests/test_curiosity.py:
```
            config["exploration_config"] = {
                "type": "Curiosity",
                "eta": 0.2,
                "lr": 0.001,  # <- HERE
                "feature_dim": 128,
                "feature_net_config": {
                    "fcnet_hiddens": [],
                    "fcnet_activation": "relu",
                },
                "sub_exploration": {
                    "type": "StochasticSampling",
                }
            }
```

**Comment by zzchuman** [comment]
Thank you! got it! @sven1977 ,  I have a try! Thank you!
