### ISSUE TITLE
[tune] RuntimeError: The actor with name ImplicitFunc failed to be imported

### ISSUE THREAD

**Issue by Dadatata-JZ** [ray-project/ray#11991]
Hi there, 

First time user, met this issue and could not locate where this function actually is working. 

> 
> Failure # 1 (occurred at 2020-11-12_14-37-46)
> Traceback (most recent call last):
>   File "/home/zha1syv/anaconda3/envs/facto/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 515, in _process_trial
>     result = self.trial_executor.fetch_result(trial)
>   File "/home/zha1syv/anaconda3/envs/facto/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
>     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
>   File "/home/zha1syv/anaconda3/envs/facto/lib/python3.6/site-packages/ray/worker.py", line 1428, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(RuntimeError): [36mray::ImplicitFunc.train()[39m (pid=49293, ip=172.16.23.112)
>   File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 483, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
> RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
> 
> ### Describe your feature request
> 
> For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!
>

**Comment by richardliaw** [comment]
Hmm, can you tell me more about your setup? I've seen this error message before but I can't quite reproduce this error.

**Comment by richardliaw** [comment]
Have you tried this? https://stackoverflow.com/questions/54338013/parallel-import-a-python-file-from-sibling-folder

**Comment by diegoclarity** [comment]
Any updates on this?? Having the same error when trying to do hyperparameter search.... Just`trainer.hyperparameter_search(` All the trials fails and I see this message in the logs..

**Comment by MakGulati** [comment]
Using TensorFlow backend.
WARNING:tensorflow:From /Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2021-02-12 11:14:49,908 INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265
2021-02-12 11:14:52,029 WARNING function_runner.py:540 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.
2021-02-12 11:14:52.046750: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-02-12 11:14:52.073524: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb734e30470 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-12 11:14:52.073554: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/Users/mayank/.local/lib/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
2021-02-12 11:15:04,154 WARNING worker.py:1034 -- Warning: The actor ImplicitFunc has size 67315581 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
== Status ==
Memory usage on this node: 5.7/8.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 1/4 CPUs, 0/0 GPUs, 0.0/2.83 GiB heap, 0.0/0.98 GiB objects
Result logdir: /Users/mayank/ray_results/training_function_2021-02-12_11-14-53
Number of trials: 1/3 (1 RUNNING)
+-------------------------------+----------+-------+---------+
| Trial name                    | status   | loc   |   alpha |
|-------------------------------+----------+-------+---------|
| training_function_26ba3_00000 | RUNNING  |       |   0.001 |
+-------------------------------+----------+-------+---------+


2021-02-12 11:15:05,294 WARNING worker.py:1034 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID df5a1a8201000000. Traceback:
Traceback (most recent call last):
  File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'frameworks'

(pid=4995) 2021-02-12 11:15:05,285      ERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.
(pid=4995) Traceback (most recent call last):
(pid=4995)   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
(pid=4995)     actor_class = pickle.loads(pickled_class)
(pid=4995) ModuleNotFoundError: No module named 'frameworks'
2021-02-12 11:15:10,324 ERROR worker.py:980 -- Possible unhandled error from worker: ray::ImplicitFunc.__init__() (pid=4995, ip=192.168.1.247)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
2021-02-12 11:15:10,325 ERROR worker.py:980 -- Possible unhandled error from worker: ray::ImplicitFunc.train() (pid=4995, ip=192.168.1.247)
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
== Status ==
Memory usage on this node: 5.9/8.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 2/4 CPUs, 0/0 GPUs, 0.0/2.83 GiB heap, 0.0/0.98 GiB objects
Result logdir: /Users/mayank/ray_results/training_function_2021-02-12_11-14-53
Number of trials: 2/3 (2 RUNNING)
+-------------------------------+----------+-------+---------+
| Trial name                    | status   | loc   |   alpha |
|-------------------------------+----------+-------+---------|
| training_function_26ba3_00000 | RUNNING  |       |   0.001 |
| training_function_26ba3_00001 | RUNNING  |       |   0.01  |
+-------------------------------+----------+-------+---------+


2021-02-12 11:15:17,532 WARNING worker.py:1034 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 7bbd902801000000. Traceback:
Traceback (most recent call last):
  File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'frameworks'

(pid=4996) 2021-02-12 11:15:17,522      ERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.
(pid=4996) Traceback (most recent call last):
(pid=4996)   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
(pid=4996)     actor_class = pickle.loads(pickled_class)
(pid=4996) ModuleNotFoundError: No module named 'frameworks'
2021-02-12 11:15:22,566 ERROR worker.py:980 -- Possible unhandled error from worker: ray::ImplicitFunc.__init__() (pid=4996, ip=192.168.1.247)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
2021-02-12 11:15:22,566 ERROR worker.py:980 -- Possible unhandled error from worker: ray::ImplicitFunc.train() (pid=4996, ip=192.168.1.247)
  File "python/ray/_raylet.pyx", line 422, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 456, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 459, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.

**I was doing grid search on learning rates. I have tensorflow version 1.15 **

**Comment by richardliaw** [comment]
What version of Ray are you on? Could you try the latest Ray (1.2)?

**Comment by MakGulati** [comment]
> What version of Ray are you on? Could you try the latest Ray (1.2)?

Previously I was using Ray 1.1 but I have updated to 1.2 now. Any clue what's happening here??

> Using TensorFlow backend.
> WARNING:tensorflow:From /Users/mayank/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> 2021-02-13 15:36:33,840 INFO services.py:1174 -- View the Ray dashboard at http://127.0.0.1:8265
> 2021-02-13 15:36:35,957 INFO registry.py:65 -- Detected unknown callable for trainable. Converting to class.
> 2021-02-13 15:36:35,958 WARNING function_runner.py:541 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
> WARNING:tensorflow:OMP_NUM_THREADS is no longer used by the default Keras config. To configure the number of threads, use tf.config.threading APIs.
> 2021-02-13 15:36:35.981612: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2021-02-13 15:36:36.001015: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fac3a6586e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2021-02-13 15:36:36.001044: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> /Users/mayank/.local/lib/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
>   warnings.warn('No training configuration found in save file: '
> 2021-02-13 15:36:45,635 WARNING worker.py:1107 -- Warning: The actor ImplicitFunc has size 67315279 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
> == Status ==
> Memory usage on this node: 5.7/8.0 GiB
> Using AsyncHyperBand: num_stopped=0
> Bracket: Iter 320.000: None | Iter 80.000: None | Iter 20.000: None
> Resources requested: 2/4 CPUs, 0/0 GPUs, 0.0/2.64 GiB heap, 0.0/0.88 GiB objects
> Result logdir: /Users/mayank/ray_results/exp
> Number of trials: 1/1 (1 RUNNING)
> +------------------------------+----------+-------+----------+
> | Trial name                   | status   | loc   |       lr |
> |------------------------------+----------+-------+----------|
> | train_test_model_e1592_00000 | RUNNING  |       | 0.056406 |
> +------------------------------+----------+-------+----------+
> 
> 
> (pid=21024) Using TensorFlow backend.
> 2021-02-13 15:36:50,283 WARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID a67dc375e60ddd1a23bd3bb901000000. Traceback:
> Traceback (most recent call last):
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
>     actor_class = pickle.loads(pickled_class)
> ModuleNotFoundError: No module named 'functions'
> 
> 2021-02-13 15:36:50,285 ERROR trial_runner.py:616 -- Trial train_test_model_e1592_00000: Error processing event.
> Traceback (most recent call last):
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
>     results = self.trial_executor.fetch_result(trial)
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
>     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/worker.py", line 1456, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train_buffered() (pid=21024, ip=192.168.1.247)
>   File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
> RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.
> Result for train_test_model_e1592_00000:
>   {}
>   
> == Status ==
> Memory usage on this node: 5.8/8.0 GiB
> Using AsyncHyperBand: num_stopped=0
> Bracket: Iter 320.000: None | Iter 80.000: None | Iter 20.000: None
> Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/2.64 GiB heap, 0.0/0.88 GiB objects
> Result logdir: /Users/mayank/ray_results/exp
> Number of trials: 1/1 (1 ERROR)
> +------------------------------+----------+-------+----------+
> | Trial name                   | status   | loc   |       lr |
> |------------------------------+----------+-------+----------|
> | train_test_model_e1592_00000 | ERROR    |       | 0.056406 |
> +------------------------------+----------+-------+----------+
> Number of errored trials: 1
> +------------------------------+--------------+--------------------------------------------------------------------------------------------------------+
> | Trial name                   |   # failures | error file                                                                                             |
> |------------------------------+--------------+--------------------------------------------------------------------------------------------------------|
> | train_test_model_e1592_00000 |            1 | /Users/mayank/ray_results/exp/train_test_model_e1592_00000_0_lr=0.056406_2021-02-13_15-36-40/error.txt |
> +------------------------------+--------------+--------------------------------------------------------------------------------------------------------+
> 
> Traceback (most recent call last):
>   File "csinet_ray.py", line 278, in <module>
>     "lr": tune.uniform(0.001, 0.1),
>   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/tune/tune.py", line 444, in run
>     raise TuneError("Trials did not complete", incomplete_trials)
> ray.tune.error.TuneError: ('Trials did not complete', [train_test_model_e1592_00000])
> (pid=21024) 2021-02-13 15:36:50,272     ERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.
> (pid=21024) Traceback (most recent call last):
> (pid=21024)   File "/Users/mayank/anaconda3/envs/tf3/lib/python3.6/site-packages/ray/function_manager.py", line 496, in _load_actor_class_from_gcs
> (pid=21024)     actor_class = pickle.loads(pickled_class)
> (pid=21024) ModuleNotFoundError: No module named 'functions'

**Comment by jaidhyani** [comment]
Also having this problem.

**Comment by MakGulati** [comment]
@jaidhyani you may want to check :) https://discuss.ray.io/t/class-methods-in-tune-run/910/6
