### ISSUE TITLE
[autoscaler] Failed workers end up in broken state

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12005]
### What is the problem?
* ray 1.0.1
* kubernetes autoscaling

When an autoscaled worker failed to update, it ends up in a broken state:
* The worker pod that was scaled and failed to update is not cleaned up. It keeps running and keeps using e.g. GPU resources.
* The autoscaler algorithm takes resources of "failed workers" into account, while in fact no resources can be scheduled on these workers.

### Reproduction (REQUIRED)
One way to force a worker to be in a "failed update" state is to set `NODE_START_WAIT_S` low enough.
 https://github.com/ray-project/ray/blob/3b56a1a5220fe0c3b522cff43dbb6ef7e33bfd99/python/ray/autoscaler/_private/command_runner.py#L36

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @AmeerHajAli

**Comment by ericl** [comment]
One option here is to retry on update failures, or to terminate the node if updates failed.

**Comment by AmeerHajAli** [comment]
I think this should be handled by the autoscaler cleaner of idle nodes. The only concern is when the number of nodes is min_workers and then it might not be cleaned.

**Comment by AmeerHajAli** [comment]
If we can detect failed nodes, we can easily skip the `keep_min_workers` call when the node is tagged as failed.

**Comment by wuisawesome** [comment]
> terminate the node if updates failed.

IMO this seems like the best solution. Clean and cost effective.

One downside is that this would make it harder to debug setup failures, so we may want to consider putting it behind a flag.

**Comment by ericl** [comment]
@AmeerHajAli I think you mentioned running into this before. Do you want to take this issue?

We can probably do something like auto-terminate failed workers (or at least add an option to do so).

**Comment by AmeerHajAli** [comment]
I am happy to take this bug into my queue.

**Comment by AmeerHajAli** [comment]
Closed in #12661 for nodes that failed to update/init and `NODE_START_WAIT_S` for getting nodes.
