### ISSUE TITLE
[autoscaler] Number of target nodes is incorrect

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12006]
### What is the problem?
* ray 1.0.1
* kubernetes autoscaler

### Reproduction (REQUIRED)
When I run this script of @simon-mo twice: https://gist.github.com/simon-mo/7b0dd033b2f12c72c75ce0cfd0c664d7
A worker is scaled, but the number of target nodes is incorrect:
`2020-11-10 17:09:24,585 INFO autoscaler.py:591 -- Cluster status: 1/0 target nodes (0 pending)`
It should report `1/1`.
Although the reporting is wrong, the actor and worker keep running, so the worker is not scaled down...

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by ericl** [comment]
We replaced the legacy autoscaler backend recently (it will be released in 1.0.2). I'm closing this issue for now since it's likely fixed in the new backend; feel free to re-open if this isn't the case.
