### ISSUE TITLE
[core] passing an object multiple times deserializes into different objects in remote function

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#12008]
### What is the problem?

When passing the same object multiple times to an actor or task, it is deserialized into two different objects. I would expect it to be deserialized into the same object.

### Reproduction (REQUIRED)

```
import ray

ray.init()


class LocalObject:
    def __init__(self, val):
        self.val = val


def local_same(item, other):
    return item == other


@ray.remote
def remote_same(item, other):
    return item == other


obj = LocalObject(4)
assert local_same(obj, obj)
assert ray.get(remote_same.remote(obj, obj))  # Throws AssertionError
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Hmm I guess it makes sense because both are not referenced, but copied when remote calls are invoked? 

cc @stephanie-wang
