### ISSUE TITLE
[autoscaler] Make NODE_START_WAIT_S configurable (for docker container nodes)

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12004]
### Describe your feature request

Currently the time it can take to start a new node in the autoscaler is limited to 300 seconds: https://github.com/ray-project/ray/blob/3b56a1a5220fe0c3b522cff43dbb6ef7e33bfd99/python/ray/autoscaler/_private/command_runner.py#L36
In some setups, where starting and configuring new nodes takes a few minutes and downloading docker images also takes some time, it can happen 300s is too short.
So it would be nice if this constant would be configurable...

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by ericl** [comment]
This deadline should only apply to physical start of the instance (time until first SSH connection can be established). Post-setup steps like downloading images are after this step.

**Comment by wuisawesome** [comment]
@PidgeyBE I guess one question here is what error message(s) are you seeing that lead you to believe this constant is the problem?

**Comment by PidgeyBE** [comment]
@ericl Indeed that's correct
@wuisawesome I dont remember exactly, I had to help out in a debugging sessions because our DevOps team was experiencing issues with it. The problem is we are using ray autoscaling on kubernetes and e.g. in google cloud we have an additional system which scales physical nodes when there is no space for additional pods anymore.
So when Ray autoscaling decides to start a new GPU worker for example, first a new Google Cloud VM has to be started, NVIDIA drivers have to be installed etc, then the docker image for the worker pod has to be downloaded into the newly created VM and only after this the Pod becomes "ready". This whole proces (before SSHing into the pod becomes possible) takes longer than 300s.
Currently our issue is resolved by patching the ray code (replacing `NODE_START_WAIT_S = 300` with `NODE_START_WAIT_S = 3000`), but being able to configure it would be a lot cleaner... :)
