### ISSUE TITLE
Trying to understand the performance of short-lived actors with a dependency of big module

### ISSUE THREAD

**Issue by yncxcw** [ray-project/ray#12017]
### Describe your question

I am running this benchmark to exercise an issue we are facing.

In `ray_test.py`:
```python
import ray
import time

from tf import func
ray.init()

@ray.remote
class Counter(object):
    def __init__(self):
        self.value = 0

    def increment(self):
        self.value += func()
        return self.value

    def get_counter(self):
        return self.value

WORKER_COUNT = 200

s = time.time()
for _ in range(10):
    actors = []
    for _ in range(WORKER_COUNT):
        actors.append(Counter.remote())

    for actor in actors:
        ray.get(actor.increment.remote())
print(time.time() - s)
```

In `tf.py`:
```python
import tensorflow
import keras

def func():
    return 1         
```

This gives me the perf like:
```
# 200 workers + tf import: 163s
# 20 workers + tf import: 19s
# 2 workers + tf import: 11.67s 
```

If I made this change `self.value += func() -> self.value += 1` from `ray_test.py`, then it gives me perf like:
```
# 200 workers: 37.937s
# 20 workers: 3.24s
# 2 workers: 3.28s
```
It seems that big dependencies have a huge impact on perf for short-lived actors. I am wondering if this is a known issue or if there is a way to optimize it. 

Related discussion: https://discuss.ray.io/t/try-to-understand-the-overhead-of-small-tasks/42

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

**Comment by ericl** [comment]
This is because of the "calling ray.get in a loop" antipattern, see this doc for more details on how to fix: https://docs.google.com/document/u/1/d/167rnnDFIVRhHhK4mznEIemOtj63IOhtIPvSYaPgI4Fg/mobilebasic#h.5hvaid3puygu

**Comment by yncxcw** [comment]
@ericl hi, Yeah, I am just trying to understand if importing a large dependency would potentially slow down the short-lived task.
