### ISSUE TITLE
[Autoscaler] Clarify override resources message

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#12031]
### What is the problem?

Right now if a resource is provided in both the `RAY_OVERRIDE_RESOURCES` env var, and through another means, we print a message like 
```
2020-11-15 10:53:44,191	INFO node.py:286 -- Autoscaler overriding resources: {'CPU': 32}.
```

Instead, we shouldn't print this message if the quantity is the same. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
BTW, @wuisawesome I think this belongs under the `fix-error-msg` label right?

**Comment by wuisawesome** [comment]
oh yeah i didn't realize those were separate tags

**Comment by ericl** [comment]
I think we should put these under the milestone right?

**Comment by ericl** [comment]
@richardliaw how about we remove the tag since we have the milestone?
