### ISSUE TITLE
[tune] Log error message if machines don't have ssh access

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12032]
### Describe your feature request

Head node needs to have ssh access between different machines in order to leverage rsync to move checkpoints across nodes.

Right now, there is no proper error message printed. However, we should log a message once that says:

```
Ray Tune need ssh access between head and worker nodes to move checkpoints properly. Either allow for ssh access (i.e., setting the correct authorized keys), or implement your own node-syncer: <documentation>.
```

**Comment by krfricke** [comment]
Resolved with task-based syncing.
