### ISSUE TITLE
[Object Spilling] Make filesystem external storage work in multi-nodes.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12044]
### Describe your feature request

File system based spilling has so much easier interface for users to use than S3. It'll be really great if we can make this work in multi-nodes setup.

**Comment by ericl** [comment]
Hmm in principle this isn't too hard right? We can spill it, and just not change the location in the directory. When we try to fetch it, reload it if needed.

**Comment by rkooo567** [comment]
Yes! That was my thought as well.

**Comment by rkooo567** [comment]
For now, we just pull it from external storage if the object has been already spilled

**Comment by rkooo567** [comment]
Duplicated
