### ISSUE TITLE
[C++ API] Objects leaking in the C++ language Support.

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#12041]
The c++ API is leaking objects. We suspect this is due to reference counting. We might need to add a class like this in the C++ API https://github.com/ray-project/ray/blob/master/python/ray/includes/object_ref.pxi. 

example:
```
auto r1 = actor5.Task(&Counter::Add, r0).Remote();
auto r2 = actor5.Task(&Counter::Add, r1).Remote();
auto r3 = actor5.Task(&Counter::Add, r2).Remote();
int result3 = *(Ray::Get(r3)); // this will remove r0, r1, r2, r3, which is pretty scary.
// int result2 = *(Ray::Get(r2)); // will not work
// int result2 = *(Ray::Get(r1)); // will not work
// int result2 = *(Ray::Get(r0)); // will not work
```
- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by kfstorm** [comment]
We can refer to https://github.com/ray-project/ray/milestone/16 for adding reference counting support in C++ worker.

**Comment by zhe-thoughts** [comment]
Thanks @kfstorm! 

There are recently some users interested in C++ (Intel, Alibaba). Just in order to set right expectations, when do you think we can have this issue resolved? cc @SongGuyang @raulchen

**Comment by kfstorm** [comment]
Sorry that we don't have much bandwidth on this currently. Could you guys take on this issue?

**Comment by AmeerHajAli** [comment]
@SongGuyang mentioned he will look into it tomorrow.
