### ISSUE TITLE
ray.init() fails on macOS Big Sur

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#12059]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
OS version: macOS Big Sur
Ray version: should impact all versions.

Issue:
`ray.init()` fails when starting redis, with the following error stack.
```
Traceback (most recent call last):
  File "debugging.py", line 2, in <module>
    ray.init()
  File "/Users/haochen/code/ant_ray/python/ray/worker.py", line 740, in init
    ray_params=ray_params)
  File "/Users/haochen/code/ant_ray/python/ray/node.py", line 200, in __init__
    self.start_head_processes()
  File "/Users/haochen/code/ant_ray/python/ray/node.py", line 801, in start_head_processes
    self.start_redis()
  File "/Users/haochen/code/ant_ray/python/ray/node.py", line 580, in start_redis
    fate_share=self.kernel_fate_share)
  File "/Users/haochen/code/ant_ray/python/ray/_private/services.py", line 720, in start_redis
    fate_share=fate_share)
  File "/Users/haochen/code/ant_ray/python/ray/_private/services.py", line 902, in _start_redis_instance
    ulimit_n - redis_client_buffer)
  File "/Users/haochen/.pyenv/versions/3.7.6/lib/python3.7/site-packages/redis/client.py", line 1243, in config_set
    return self.execute_command('CONFIG SET', name, value)
  File "/Users/haochen/.pyenv/versions/3.7.6/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/haochen/.pyenv/versions/3.7.6/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/haochen/.pyenv/versions/3.7.6/lib/python3.7/site-packages/redis/connection.py", line 747, in read_response
    raise response
redis.exceptions.ResponseError: The operating system is not able to handle the specified number of clients, try with -33
```

Digging into this issue, I found it's because `resource.getrlimit(resource.RLIMIT_NOFILE)[0]` (see [here](https://github.com/ray-project/ray/blob/90574b66cce07f8f4fabe99bee6ff6419c097a0b/python/ray/_private/services.py#L977)) now returns `9223372036854775807` on Big Sur, while it returns `256` on previous macOS versions. 

Removing [this line](https://github.com/ray-project/ray/blob/90574b66cce07f8f4fabe99bee6ff6419c097a0b/python/ray/_private/services.py#L984) can fix this issue. @ericl @edoakes @rkooo567 Do you know what is the purpose of this code? Is it still needed? 

### Reproduction (REQUIRED)

Just `ray.init()`.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Oh interesting. We set it before because 256 fds are usually not enough to handle all connections to Redis.

**Comment by robertnishihara** [comment]
In the cluster setting, you could have many hundreds of thousands of workers, so `maxclients` needs to be at least that large.

**Comment by raulchen** [comment]
Just found the reason why `resource.getrlimit(resource.RLIMIT_NOFILE)[0]` returns `9223372036854775807` is not related to Big Sur, it's because of [this line](https://github.com/ray-project/ray/blob/90574b66cce07f8f4fabe99bee6ff6419c097a0b/python/ray/worker.py#L633).

**Comment by architkulkarni** [comment]
It looks like you've already figured out the issue, but I'll post my error message here since it's slightly different and the last line gives an idea of what we could try setting the upper limit to (namely, 4294967295).  I don't know if that makes sense though, I'm not familiar with this part of the code.

```python-traceback
[...same as above...]
  File "/Users/archit/anaconda3/envs/ray-py36/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Invalid argument '9223372036854775775' for CONFIG SET 'maxclients' - argument must be between 1 and 4294967295 inclusive
```

**Comment by ericl** [comment]
@raulchen we can probably cap to an upper limit of 10000 or something for redis connections?

**Comment by bermeom** [comment]
I had the same issue

ray.init()
---------------------------------------------------------------------------
ResponseError                             Traceback (most recent call last)
/mnt/c/Users/mbermeo/Documents/ainguraIIot/dev/arcelor/python/processing_kpis.py in <module>
----> 1 ray.init()

~/.local/lib/python3.6/site-packages/ray/worker.py in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _java_worker_options, _code_search_path, _temp_dir, _load_code_from_local, _lru_evict, _metrics_export_port, _object_spilling_config, _system_config)
    715             shutdown_at_exit=False,
    716             spawn_reaper=True,
--> 717             ray_params=ray_params)
    718     else:
    719         # In this case, we are connecting to an existing cluster.

~/.local/lib/python3.6/site-packages/ray/node.py in __init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    198         # Start processes.
    199         if head:
--> 200             self.start_head_processes()
    201             redis_client = self.create_redis_client()
    202             redis_client.set("session_name", self.session_name)

~/.local/lib/python3.6/site-packages/ray/node.py in start_head_processes(self)
    803         assert self._redis_address is None
    804         # If this is the head node, start the relevant head node processes.
--> 805         self.start_redis()
    806 
    807         self.start_gcs_server()

~/.local/lib/python3.6/site-packages/ray/node.py in start_redis(self)
    578              redirect_worker_output=True,
    579              password=self._ray_params.redis_password,
--> 580              fate_share=self.kernel_fate_share)
    581         assert (
    582             ray_constants.PROCESS_TYPE_REDIS_SERVER not in self.all_processes)

~/.local/lib/python3.6/site-packages/ray/_private/services.py in start_redis(node_ip_address, redirect_files, resource_spec, port, redis_shard_ports, num_redis_shards, redis_max_clients, redirect_worker_output, password, fate_share)
    714         stdout_file=redis_stdout_file,
    715         stderr_file=redis_stderr_file,
--> 716         fate_share=fate_share)
    717     processes.append(p)
    718     redis_address = address(node_ip_address, port)

~/.local/lib/python3.6/site-packages/ray/_private/services.py in _start_redis_instance(executable, modules, port, redis_max_clients, num_retries, stdout_file, stderr_file, password, redis_max_memory, fate_share)
    896         if current_max_clients < ulimit_n - redis_client_buffer:
    897             redis_client.config_set("maxclients",
--> 898                                     ulimit_n - redis_client_buffer)
    899 
    900     # Increase the hard and soft limits for the redis client pubsub buffer to

~/.local/lib/python3.6/site-packages/redis/client.py in config_set(self, name, value)
   1218     def config_set(self, name, value):
   1219         "Set config item ``name`` with ``value``"
-> 1220         return self.execute_command('CONFIG SET', name, value)
   1221 
   1222     def config_resetstat(self):

~/.local/lib/python3.6/site-packages/redis/client.py in execute_command(self, *args, **options)
    876         try:
    877             conn.send_command(*args)
--> 878             return self.parse_response(conn, command_name, **options)
    879         except (ConnectionError, TimeoutError) as e:
    880             conn.disconnect()

~/.local/lib/python3.6/site-packages/redis/client.py in parse_response(self, connection, command_name, **options)
    890         "Parses a response from the Redis server"
    891         try:
--> 892             response = connection.read_response()
    893         except ResponseError:
    894             if EMPTY_RESPONSE in options:

~/.local/lib/python3.6/site-packages/redis/connection.py in read_response(self)
    750 
    751         if isinstance(response, ResponseError):
--> 752             raise response
    753         return response
    754 

ResponseError: The operating system is not able to handle the specified number of clients, try with 10000

**Comment by crclark** [comment]
The PR above did not fix the issue. It can still be reproduced with

```
ulimit -n unlimited
ray start --head
```

on macOS
