### ISSUE TITLE
Wheel builds failing

### ISSUE THREAD

**Issue by dHannasch** [ray-project/ray#12058]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
master on Travis
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

`LINUX_WHEELS=1 LINUX_JARS=1` are failing to build on Travis.
The failures started with https://github.com/ray-project/ray/commit/9920933e318986cfe6cd8a8fad12b1d8b4490917, ~though it looks like the failures might be unrelated to the commit itself. https://github.com/ray-project/ray/commit/90574b66cce07f8f4fabe99bee6ff6419c097a0b appears to be aimed at fixing the problem by pinning aiohttp.~

What's interesting is that https://github.com/ray-project/ray/commit/8609e2dd90e78cfc7e95f453ad7eb9f17a74bcb7 changed the wheel build from erroring out to failing normally, apparently incidentally. It's unclear why that happened (and it might not matter).
(That's the only real reason for creating this issue, noting that fact in case it turns out to be a clue.)

https://github.com/ray-project/ray/commit/bea0031491876ee8b1fd3057508041a5a5819a74 was meant to fix the build but doesn't appear to have done so.

After further investigation, this does have to do with https://github.com/ray-project/ray/commit/9920933e318986cfe6cd8a8fad12b1d8b4490917 after all. The current error is:
```
{"stream":"Successfully installed ray-1.1.0.dev0\n"}
{"stream":"\u001b[91m/bin/sh: 1: sudo: not found\n\u001b[0m"}
{"errorDetail":{"code":127,"message":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 sudo rm `basename $WHEEL_PATH`' returned a non-zero code: 127"},"error":"The command '/bin/sh -c $HOME/anaconda3/bin/pip --no-cache-dir install `basename $WHEEL_PATH`[all] \u0026\u0026 sudo rm `basename $WHEEL_PATH`' returned a non-zero code: 127"}
```
It's unclear why `sudo` fails here and not elsewhere.

**Comment by ijrsvt** [comment]
The problem is that we updated our `base-image` #11407, but that wasn't built and pushed to our DockerHub because the method the function (`determine_tests_to_run.py`) used to check if docker was affected (and thus triggering a rebuild of `base-images) seems to not work on merge builds.

**Comment by ijrsvt** [comment]
[Merge build](https://travis-ci.com/github/ray-project/ray/jobs/434849569#L14820)

[Last commit--PR Build](https://travis-ci.com/github/ray-project/ray/jobs/433972422#L11974)
