### ISSUE TITLE
Ray does not show error message

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#1206]
I recently tried the example from the doc (​http://ray.readthedocs.io/en/latest/internals-overview.html​ ​Section​ ​“NOTE and​ ​Limitations”):

```
@ray.remote
def f(x):
    return helper(x)

def helper(x):
    return x + 1

f.remote(0)
```

I would expect to get an error message, but in fact I didn't. So I wonder if there are things going wrong, or I missed something.

P.S The code was running on Ray 0.2.1 and Python 3.5 on MacBook Pro.

**Comment by robertnishihara** [comment]
Thanks @RuofanKong! Can you check if the issue still happens with Ray 0.2.2?

When I run this I get 

```
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "<ipython-input-5-8fc5f727239b>", line 3, in f
NameError: name 'helper' is not defined
```

Note, I edited the formatting of the code block, but I think it is currently correct.

Just as a sanity check, can you try

```python
import threading

def f():
    print("Is this printed?")

t = threading.Thread(target=f)
t.start()
```

and see if `Is this printed?` gets printed?

**Comment by robertnishihara** [comment]
You're running those lines after doing `ray.init()` right?

**Comment by RuofanKong** [comment]
@robertnishihara Thanks for the comment! I upgraded my ray to be 0.2.2, but still didn't get the error message. Also tried the above code snippet, and I could get `Is this printed?` to be printed. 

> You're running those lines after doing ray.init() right?

Yes. The following is my complete code:
```
import ray


@ray.remote
def f(x):
    return helper(x)


def helper(x):
    return x + 1


if __name__ == "__main__":
    ray.init()
    f.remote(0)
```

**Comment by robertnishihara** [comment]
Oh, I see. In this case, the code is actually succeeding, so there is no error message.

We may change things so that this fails in the future, but right now the remote function `f` is not being pickled and exported until `ray.init()` is called. By the time that happens, `helper` has already been defined and so everything works.

You can see the error if you instead run

```python
import ray
import time

ray.init()

@ray.remote
def f(x):
    return helper(x)


def helper(x):
    return x + 1

f.remote(0)

time.sleep(10)
```

Note that the `time.sleep` is there to prevent the script from exiting before it has the chance to print the error message, since the error is printed asynchronously in the background.

**Comment by RuofanKong** [comment]
Thanks for the explanation! Sounds like in the ray code (not limited to the above case), we need to put `ray.init()` before defining any remote functions so it could be picked up and executed, right?

**Comment by robertnishihara** [comment]
You can *define* remote functions and actors before calling `ray.init()` as you do in your example.

However, tasks will not be *executed* until after `ray.init()` has been called.

**Comment by RuofanKong** [comment]
@robertnishihara Yeah, my point is if defining remote functions and actors before calling ray.init() is more efficient, and if it's the suggested way doing so :)

**Comment by robertnishihara** [comment]
Both ways should be about equally efficient. However, defining them before `ray.init()` may be more natural in some cases (e.g., if you define the remote functions/actors in a different module and then import that module before `ray.init()`.

**Comment by RuofanKong** [comment]
I see. Thanks!

**Comment by GoingMyWay** [comment]
Similar issue. There is a bug in of the actor and the actor did not show error bug got stuck
