### ISSUE TITLE
Security Question what is the 'google" package ray is installing? (pip install ray)

### ISSUE THREAD

**Issue by ricpruss** [ray-project/ray#12083]
### What is the problem?
The 'google' package required by ray looks very suspect and is **not** an official google package.

https://pypi.org/project/google/
is very suspect. No source link, home page links off to some random blog.  Author link goes no where.
Certainly not done by google.

*Ray version and other system information (Python version, TensorFlow version, OS):*
pip list | grep ray
ray                      1.0.1

### Reproduction (REQUIRED)
pip install ray

**Comment by pcmoritz** [comment]
@thomasdesr Can you have a look at this?

**Comment by richardliaw** [comment]
@ricpruss thanks a bunch for opening this issue! That's a bad oversight on our side:

This was introduced in: https://github.com/ray-project/ray/pull/6045 by @pcmoritz 

We should perhaps install `protobuf` (as seen in this repo: https://github.com/benhodgson/protobuf-to-dict/blob/master/setup.py). Or just vendor the protobuf-to-dict inside ray repo.

**Comment by pcmoritz** [comment]
It seems to me that we are not actually using this package (it is unrelated to the `google` namespace we are using), so just removing the requirement might fix the issue.

**Comment by pcmoritz** [comment]
I created a PR here: https://github.com/ray-project/ray/pull/12085

Let's see if that fixes it, or if we need additional dependencies here!

**Comment by pcmoritz** [comment]
Thanks a lot for flagging this @ricpruss

**Comment by ricpruss** [comment]
Thanks you certainly have fixed it fast,
Ric
