### ISSUE TITLE
[autoscaler] [docker] ray up on stopped node fails?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12104]
### What is the problem?

I ran `ray up` on a cluster that I had previously stopped. 

The ray up was unable to finish properly due to a `tmp` call.

cc @ijrsvt 
```
(base) ➜  aws git:(docker-fix) ✗ ray up example-full.yaml -y
Cluster: default

Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (head & workers): ray-autoscaler_2_us-west-2 [default]
  VPC Subnets (head & workers): subnet-d26e76b6, subnet-503c0e26 [default]
  EC2 Security groups (head & workers): sg-0e2ad6debfc8e0814 [default]
  EC2 AMI (head & workers): ami-0a2363a9cff180a64

No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]

Acquiring an up-to-date head node
  Reusing nodes i-0c90dd53359e25223. To disable reuse, set `cache_stopped_nodes: False` under `provider` in the cluster configuration.
  Stopping instances to reuse
  Launched a new head node
  Fetching the new head node

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/6] Waiting for SSH to become available
    Running `uptime` as a test.
    Waiting for IP
      Not yet available, retrying in 10 seconds
      Received: 35.165.135.138
ssh: connect to host 35.165.135.138 port 22: Connection refused
    SSH still not available SSH command failed., retrying in 5 seconds.
Warning: Permanently added '35.165.135.138' (ECDSA) to the list of known hosts.
 09:00:19 up 0 min,  1 user,  load average: 0.35, 0.08, 0.03
Shared connection to 35.165.135.138 closed.
    Success.
Shared connection to 35.165.135.138 closed.
latest-gpu: Pulling from rayproject/ray
Digest: sha256:9e330168fbeface86427d29b4a1a996bdefca42fff38ff155a29c8d1d1020b74
Status: Image is up to date for rayproject/ray:latest-gpu
docker.io/rayproject/ray:latest-gpu
Shared connection to 35.165.135.138 closed.
Shared connection to 35.165.135.138 closed.
Shared connection to 35.165.135.138 closed.
Shared connection to 35.165.135.138 closed.
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Shared connection to 35.165.135.138 closed.
2020-11-18 01:00:24,949	WARNING command_runner.py:780 -- Nvidia Container Runtime is present, but no GPUs found.
Shared connection to 35.165.135.138 closed.
9191520da0ddb9d6259795e5a758a298934bdab25ee153e60ddcd350318ed789
Shared connection to 35.165.135.138 closed.
Shared connection to 35.165.135.138 closed.
lstat /tmp/ray_tmp_mount: no such file or directory
Shared connection to 35.165.135.138 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!

  Failed to setup head node.
```

**Comment by ijrsvt** [comment]
@richardliaw can you rerun with something like `ray up -vvvvvv ...`

**Comment by AmeerHajAli** [comment]
I get this error too @ijrsvt .

**Comment by ijrsvt** [comment]
@richardliaw Follow up question, did you happen to edit your YAML between shutting down and restarting?

**Comment by richardliaw** [comment]
hmmm maybe i modified the filemounts

**Comment by amogkam** [comment]
Same thing is happening for me. I did modify the setup_commands on the yaml between shutting down and restarting.

**Comment by cfusting** [comment]
+1

**Comment by ericl** [comment]
@AmeerHajAli @ijrsvt this sounds like a potential P0 issue, should we raise the priority?

**Comment by cfusting** [comment]
I'm having a related issue with DockerSyncer:

> invalid output path: directory "/tmp/ray_tmp_mount/...

Interestingly earlier in the logs I see the directory being created:

> VINFO command_runner.py:474 -- Running `^[[1mmkdir -p /tmp/ray_tmp_mount/...

Unfortunately I cannot create an issue as my code is proprietary and I likely won't have time to build a minimal example, but the issues are related at least with respect to the directory in question. I'm looking over the framework code now.

**Comment by edoakes** [comment]
@AmeerHajAli can you please take a look at this ASAP? Not sure if it should be release blocking.

**Comment by AmeerHajAli** [comment]
I think this is a release blocker.
Basically, it is straightforward to reproduce:
1. `ray up`
2. `ray down`
3. `ray up` -> fails because it can't locate `/tmp/ray_tmp_mount`
@ijrsvt , I think the command runner is looking for the `/tmp/ray_tmp_mount` and fails because it assumes it is there in the cached node. But it seems like AWS cleans the `/tmp` directory on terminated nodes.

**Comment by ijrsvt** [comment]
@AmeerHajAli This is not a new regression and I think that rushing this fix as a cherry pick is more risky than waiting for this fix to go through nightlies.

**Comment by AmeerHajAli** [comment]
@ijrsvt , I think it is very common for someone to run `ray up` after a `ray down`. I understand it is not a regression. But I am not sure what is the workaround here? The user will have to change the cluster name or work very hard to make it ray up again. If this is not a good reason for blocking a release then I am fine with it, but at least we should have some documentation somewhere telling the user what to do when he faces this issue.

**Comment by richardliaw** [comment]
Hey, just to help clarify, I think there's two conversations happening -- a conversation around _deadline_ and conversation around _importance_. 

@AmeerHajAli I think Ian and me and you absolutely agree that it is important to provide a workaround. 

I think Ian was just pushing back on the "prioritization/deadline" for this task. In terms of prioritization, I think it's ok to do it within the time frame of this sprint or even the sprint after (since everyone is going on holidays anyways).

**Comment by ijrsvt** [comment]
I definitely agree that this is important, I think a workaround should be to set the following in `provider:`
```
cache_stopped_nodes: False
```
