### ISSUE TITLE
[rllib] Custom model compute_action is wrong.

### ISSUE THREAD

**Issue by Tinusf** [ray-project/ray#12107]
### What is the problem?
Hello, I have created a custom model based on TFModelV2, akin to the example "MyKerasModel" in https://github.com/ray-project/ray/blob/master/rllib/tests/test_model_imports.py, using `num_outputs=2`. I am trying to create a PPO agent without critic that is first trained in a supervised manner using:
```
model.base_model.compile(optimizer=optimizer, loss="mse", metrics=["accuracy"])
model.base_model.fit(x, y, epochs=10)
```
After that I import the model to the new PPO agent using 
```
agent.import_model(import_file=weights_file)
```
However when I run 
```
action = agent.compute_action(observation)
```
I ALWAYS get the same number twice as output, for example: `action = [1. 1.]`, or `action = [0.132512 0.132512]`. This is bad and this is not what I supervised trained on earlier. 

In order to circumvent this it works fine to do this:
```agent.base_model.predict(np.array([observation])).squeeze()```
or do this:
```
action = agent.compute_action(observation, full_fetch=True)
action = action[2]['action_dist_inputs'][:2]
```
However this seems like unexpected behavior and also makes it impossible to train further using PPO and simulations. If I try to train on the agent I get this error:
```
ValueError: Cannot feed value of shape (1, 1) for Tensor 'default_policy/prev_action:0', which has shape '(?, 2)'
```
It seems that it doesn't understand that my actions are of shape 2 not 1.

My config parameters are 
```
config["vf_share_layers"] = False
config["use_critic"] = False
config["use_gae"] = False
config["explore"] = False
config["batch_mode"] = "complete_episodes"
```
I am unsure if this is a bug or if I am missing some config parameters. 
Does anyone have any tips of what I could do?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 1.0.1
Python version: 3.7.9
Tensorflow Version: 2.3.1
Ubuntu 20.04

### Reproduction 
I am unable to give the whole source code for my gym environment at this moment. Let me know if it is impossible to solve this without my script, if it is then I guess I could try to swap out the environment with a openAI environment.

**Comment by krfricke** [comment]
cc @sven1977

**Comment by sven1977** [comment]
Thanks for filing this issue @Tinusf ! However, we cannot help you debug this problem, if we don't have a (maybe simplified) reproduction script that - when executed - shows this error. This could easily be a problem in your custom model that we cannot possibily figure out w/o looking at your code.

**Comment by Tinusf** [comment]
Understandable, right now I have circumvented this issue by using another implementation of SAC, however if I come back to this and I find time to create a reproduction script that doesn't expose the closed source gym environment I will reopen this issue.
