### ISSUE TITLE
[rllib] Previous reward and prev action parameter

### ISSUE THREAD

**Issue by Waki7** [ray-project/ray#12118]
I would like to request that in the LSTMWrapper the parameters for previous action and previous reward be separate. Including previous reward is also a huge red flag for a lot of applications, it can completely nullify your results. On the other hand, conditioning on previous action is fairly common and effective in real use cases.

**Comment by sven1977** [comment]
@Waki7 Thanks for filing this issue!
Yeah, and there is another problem anyways with how discrete prev_actions are encoded (as int->float w/o one_hotting :/ ). Let's fix that at the same time. :)

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/12397
@Waki7
