### ISSUE TITLE
[Dashboard / metrics] KeyError: 'viewData'

### ISSUE THREAD

**Issue by anabranch** [ray-project/ray#12126]
### What is the problem?

Ray nightly, TF 2.2, Python 3.7.7, running a tune training workload.

```
Error: Traceback (most recent call last): File "/root/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/utils.py", line 351, in _update_cache response = task.result() 
File "/root/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/modules/stats_collector/stats_collector_head.py", line 89, in get_all_nodes all_node_details = await DataOrganizer.get_all_node_details() 
File "/root/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/datacenter.py", line 201, in get_all_node_details for node_id in DataSource.nodes.keys() 
File "/root/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/datacenter.py", line 201, in <listcomp> for node_id in DataSource.nodes.keys() 
File "/root/anaconda3/lib/python3.7/site-packages/ray/new_dashboard/datacenter.py", line 149, in get_node_info node_stats["viewData"], KeyError: 'viewData'
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@anabranch could you please provide some info on how to reproduce this? e.g., cluster yaml and what the tune job was

**Comment by anabranch** [comment]
Yes, I will try to get the repro. Feel free to leave as P2 until then, just wanted to document the error for posterity. Additionally, it also looks like we're just querying a dictionary for a value that may or may not exist. It seems like if we just did `node_stats.get("viewData", {<insert-default>}` then we'd cover our bases.

**Comment by anabranch** [comment]
In fact just looking at [the code](https://github.com/ray-project/ray/blob/master/dashboard/datacenter.py#L146). It seems like this is almost designed to occur as

        node_stats = dict(DataSource.node_stats.get(node_id, {}))

Will create an empty dictionary if it can't find the node_id and in 4 lines later we try to extract a value from it.

I realize a reproduction would be nice, but this also just seems like a bit of a code smell where we're creating an empty dictionary and later assuming it to have a certain key.

**Comment by edoakes** [comment]
@anabranch yeah, see the PR above which fixes it. Want a repro mostly to make sure there aren't other related corner cases / assumptions we're making

**Comment by anabranch** [comment]
ugh, I just didn't refresh github so I didn't see the PR...
