### ISSUE TITLE
can i run ray with tensorflow-gpu version 1.x?

### ISSUE THREAD

**Issue by LianShuaiLong** [ray-project/ray#12149]
### Describe your feature request

For feature requests or questions, post on our Github Discussions page instead: https://github.com/ray-project/ray/discussions!

**Comment by krfricke** [comment]
Hi @LianShuaiLong, sure you can. Ray itself is a general distributed computing framework and agnostic towards the libraries you use. As for the specific libraries, RLLib's algorithms support tensorflow 1.x. The other libraries don't have any restrictions with regards to libraries, so work with it, too. 

Does this answer your question? If not it would be great to learn more about your use case - what are you aiming to use Ray for?

**Comment by LianShuaiLong** [comment]
> Hi @LianShuaiLong, sure you can. Ray itself is a general distributed computing framework and agnostic towards the libraries you use. As for the specific libraries, RLLib's algorithms support tensorflow 1.x. The other libraries don't have any restrictions with regards to libraries, so work with it, too.
> 
> Does this answer your question? If not it would be great to learn more about your use case - what are you aiming to use Ray for?
i close this issue since i test ray in tensorflow-gpu1.14 successfully ;Anyway,Ray is an excellent framework
