### ISSUE TITLE
Make use of __getstate__ and __setstate__  during serialization

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#1214]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Platform independent
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**:  0.2.2
- **Python version**: 3.6.2
- **Exact command to reproduce**: See examples below

### Describe the problem

`__getstate__` and `__setstate__` is commonly used for serialization. But it seems that ray does not make use of them. 

Some objects may contain raw system objects (file handlers, etc.) or duplicated values (cache, temporary variable, etc.).  Trying to serialize they by directly expanding them as dictionaries of their fields could be incorrect and inefficient. `__getstate__` and `__setstate__` can also be used as workaround (users could override them) in case serialization fails.

### Source code / logs

```python
# Example
class SomeClass:
    def __init__(self, filename):
        self.name = filename
        self.file = open(filename)
    
    def __getstate__(self):
        odict = self.__dict__.copy()  # get attribute dictionary
        del odict['file']  # remove filehandle entry
        return odict
    
    def __setstate__(self, dict):
        fh = open(dict['name'])  # reopen file
        self.name = dict['name']
        self.file = fh

obj = SomeClass('/dev/zero')
object_id = ray.put(obj)
res = ray.get(object_id)
res.file.read()  # ---> ValueError: I/O operation on uninitialized object

import pickle
res = pickle.loads(pickle.dumps(obj))
res.file.read()  # OK
```

**Comment by robertnishihara** [comment]
@suquark thanks for the example! You're right custom serialization is important for cases like this. For cases that Ray does not handle, we fall back to cloudpickle, which presumably makes use of `__getstate__` and `__setstate__`. However, there are most likely some classes where we don't fall back to cloudpickle and where we could take advantage of `__getstate__` and `__setstate__`.

This may just be a matter of checking if the class has the `__getstate__` and `__setstate__` attributes and then using them if so..

**Comment by ericl** [comment]
Perhaps we should also replace the checkpoint methods `__ray_save__` and `__ray_restore__` with `__get/setstate__`?
