### ISSUE TITLE
[autoscaler] cannot launch head node running ray 1.0.0 from system running 1.0.1

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#12161]
### What is the problem?

Schema validation code fails on a 1.0.0 head node when it encounters `rsync_exclude` and `rsync_filter` entries when reading `ray_bootstrap_config.yaml`, which occurs when `ray up` was run on a machine with ray 1.0.1.

This can be fixed by removing the rsync entries from `python/ray/autoscaler/*/defaults.yaml`, although this isn't ideal because it means you can't specify a meaningful default on systems that aren't running 

### Reproduction (REQUIRED)

With ray-1.0.1 installed, boot a cluster (`ray up`) which installs ray-1.0.0 in the setup commands.  You then get the following error in monitor.err after the head node has booted:

`jsonschema.exceptions.ValidationError: Additional properties are not allowed ('rsync_exclude', 'rsync_filter' were **unexpected)`**

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Is this something we might be able to address in the post1 release? cc @AmeerHajAli @wuisawesome

**Comment by wuisawesome** [comment]
Unfortunately this would probably require patching 1.0 which is unlikely.

Starting in 1.0.1 though, we are trying to maintain api compatibility so hopefully this won't happen again in the future.

**Comment by krfricke** [comment]
Thanks @mattearllongshot for raising this - unfortunately for the time being you'll just have to make sure to use compatible versions. I'll close this issue for now, but we're trying hard to avoid such problems in the future.
