### ISSUE TITLE
ImportError: cannot import name 'resources_to_json'

### ISSUE THREAD

**Issue by mturk24** [ray-project/ray#1216]
When running this script of A3C on Pong: python/ray/rllib/train.py --env=Pong-ram-v4 --alg=A3C --config='{"num_workers": N}',

I get this error: "ImportError: cannot import name 'resources_to_json'" after installing all of the dependencies and ensuring each library is recognized.

Here is a log:
Traceback (most recent call last):
  File "python/ray/rllib/train.py", line 11, in <module>
    from ray.tune.config_parser import make_parser, resources_to_json
ImportError: cannot import name 'resources_to_json'

**Comment by richardliaw** [comment]
Hey, thanks for making this issue! 

It's likely that your current version of Ray is out of date, which may be the case if you're installing Ray from PyPI via pip.

If so, you can uninstall your current version of Ray, and build Ray from source ([MacOSX instructions here](http://ray.readthedocs.io/en/latest/install-on-macosx.html)). Hopefully this resolves your issue, but please follow up if not!
