### ISSUE TITLE
Ray doesn't allow "actor=" kwarg

### ISSUE THREAD

**Issue by LinxiFan** [ray-project/ray#12181]
Ray v1.0

```
import ray

@ray.remote
class Hello:
    def __init__(self, actor):
        pass

ray.init()

hello = Hello.remote(10)  # works
hello = Hello.remote(actor=10)  # fails
```

Ray doesn't allow "actor=" keyword argument. Error message: `actor_method_executor() got multiple values for argument 'actor'`. 

I believe the internal variable "actor" should be renamed to `_actor` to avoid the conflict with user API. 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
cc @ericl

**Comment by rkooo567** [comment]
@ericl Should we change the argument to something else? haha

**Comment by LinxiFan** [comment]
`actor=` is a very common term in reinforcement learning, so it'd be great to avoid the conflict. Thanks!

**Comment by rkooo567** [comment]
Created a patch https://github.com/ray-project/ray/issues/12181

**Comment by rkooo567** [comment]
This should be fixed.
