### ISSUE TITLE
[Rllib] 1.0.1 - eager_tf_policy has no attribute action_sampler_fn

### ISSUE THREAD

**Issue by Dipamc77** [ray-project/ray#12212]
The action_sampler_fn is referenced as self.action_sampler_fn ... which is never assigned to self

Hence, using an action_sampler_fn with eager mode on results in error

Error on line:
https://github.com/ray-project/ray/blob/releases/1.0.1/rllib/policy/eager_tf_policy.py#L352

Python version 3.7.3
Tensorflow version 2.2.0

**Comment by amogkam** [comment]
Hi @Dipamc77 do you have a small reproducible script to try out? Thanks!

**Comment by sven1977** [comment]
Thanks for filing this @Dipamc77 !
This PR fixes the issue: https://github.com/ray-project/ray/pull/12765
Closing. Feel free to re-open should you continue seeing this problem on your end.
