### ISSUE TITLE
[RFC] Improved autoscaler log messages

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#12221]
The current autoscaler output is quite difficult to interpret due to its verbosity and low-level details. This is a proposal to clean it by periodically emitting the following summary table:

```
======== Autoscaler status 2020-11-20 23:14:36,653 ========
Node status
------------------------------------------------------------
Healthy:
 2 p3.2xlarge (2 active)
 20 m4.4xlarge (18 active, 2 idle)

Pending:
 34.5.234.51: m4.4xlarge, launching
 34.5.234.52: m4.4xlarge, launching
 34.5.234.53: m4.4xlarge, waiting for ssh
 34.5.234.54: m4.4xlarge, waiting for ssh
 34.5.234.55: m4.4xlarge, starting ray, /tmp/ray/setup-10.log
 34.5.234.56: m4.4xlarge, setting up, /tmp/ray/setup-11.log
 34.5.234.57: m4.4xlarge, setting up, /tmp/ray/setup-12.log

Recent failures:
 172.24.25.33: m4.4xlarge, /tmp/ray/setup-8.log
 35.4.235.11: p3.2xlarge, /tmp/ray/setup-9.log

Resources
------------------------------------------------------------
Usage:
 530.0/544.0 CPU
 2.0/2.0 GPU
 0.0/2.0 AcceleratorType:V100
 0.0 GiB/1583.19 GiB memory
 0.0 GiB/471.02 GiB object_store_memory

Demands:
 {"CPU": 1}: 150 pending tasks
 [{"CPU": 4} * 5]: 5 pending placement groups
 [{"CPU": 1} * 100]: from request_resources()
```

Implementation details:
- The autoscaler should periodically generate a JSON status message that includes the above information.
- We should log the above text summary for of the JSON status every 10-30s.
- Other ray components such as the dashboard and `ray status` can also access this information.

**Comment by richardliaw** [comment]
cc @mkoh-asapp @mattearllongshot

**Comment by ijrsvt** [comment]
@ericl Would it be useful to include something about the `head_node` in this output (like which one it is)?

**Comment by rkooo567** [comment]
cc @mfitton We should definitely port this to our dashboard.

**Comment by markgoodhead** [comment]
This would be a game-changing feature for autoscaler debugging/visibility - can't wait until this is on the dashboard!

**Comment by richardliaw** [comment]
cc @maximsmol this would be a good thing to use (especially since the plan is to emit json)

**Comment by wuisawesome** [comment]
Hmm now that we're adding these to `ray status`, I wonder if we should also make some of this information available programmatically... Just a thought.

**Comment by richardliaw** [comment]
yep! cc @maximsmol who is investigating a prototype

**Comment by edoakes** [comment]
FYI we are currently exposing this programmatically in the dashboard (`/api/cluster_status`), but it currently isn't advertised anywhere.

**Comment by AmeerHajAli** [comment]
@ericl @wuisawesome can we close this issue?

**Comment by wuisawesome** [comment]
I'd call it 95% done since we don't have the per-file logging doen yet

**Comment by DmitriGekhtman** [comment]
What remains to do is the per-node logging, and this task has been delegated to me.

Let me just confirm the requirement and a potential way to do it. 

?Requirement?:
We need a log file for each node_id, and each NodeUpdater running inside of the monitor process should  log to that file.

?Design?:
One strategy is to put the requisite logging logic in the NodeUpdater --
Give the NodeUpdater a `self.logger` attribute.
Have the NodeUpdater detect by some means if it's running inside the monitor process. 
If it's not running in the monitor process, then 
`self.logger = logger`, where logger is the `logger = logging.getLogger(__name__)` defined at the top of the file.
If it is running in the monitor process, then `self.logger` is a custom logger that doesn't belong to the standard logging hierarchy and writes to a node_id-dependent log file.

@rkooo567 
Does this sound like a remotely sane strategy?

If anyone has a better idea, let me know.

**Comment by ericl** [comment]
I recall the node updater used to be a process, so you could redirect
stdout to a file directly. It seems to be a thread now, so maybe we have to
pass a logger and also capture any child command outputs as well. We could
also try moving it back to a process but that sounds like a bigger change.

**Comment by richardliaw** [comment]
@DmitriGekhtman 

IIRC you shouldn't be using `logging` in NodeUpdater, but rather the custom autoscaler CLI logger. There should be an option for that logger to write stdout/stderr to a specific file upon invocation of command (at least for non-kubernetes environments such as Docker and standard).

This logger should be used in both cases of being in a monitor process or not (rather, the stdout redirect should be toggled).

**Comment by DmitriGekhtman** [comment]
@richardliaw Ah, yep you're right, it uses the CLI logger.
@ericl And yeah, need to figure out how to redirect child command output.

**Comment by DmitriGekhtman** [comment]
cli_logger.print just prints, as far as I can tell
https://github.com/DmitriGekhtman/ray/blob/master/python/ray/autoscaler/_private/cli_logger.py#L422

**Comment by wuisawesome** [comment]
I'm not sure how you would go about using a logger here since iirc we don't capture any output. My assumption this would be done by redirecting stdout at the process runner level.

**Comment by DmitriGekhtman** [comment]
hmm, well, right now stdout and stderr go to monitor.out and monitor.err, 
and monitor.log gets all log records at level at least info.

For the purposes of this issue, are the "autoscaler log messages" we're talking about the contents of monitor.log?

**Comment by DmitriGekhtman** [comment]
ech -- anyways, i see: the goal is to redirect all output of cmds run by NodeUpdater.cmd_runner to the relevant file.

**Comment by ericl** [comment]
fyi @clarkzinzow this might be a good starter issue

**Comment by DmitriGekhtman** [comment]
^ feel free to change the assignment from me to @clarkzinzow if Clark is interested
cc @AmeerHajAli

**Comment by wuisawesome** [comment]
Minor update: we should refer to failed nodes by their id, since ip addresses can be reused when failed nodes are terminated.

**Comment by ericl** [comment]
Hmm IDs aren't as useful though, about as useful as an out of date IP. If
we keep failed nodes alive, then IPs should still be relevant right?

So we should still keep the IPs since they're more generally useful.

**Comment by wuisawesome** [comment]
ok, we can use IP, but it puts us at the mercy of the k8s ip allocation policy.

**Comment by wuisawesome** [comment]
@yiranwang52 what should the `/tmp/ray/setup-10.log` part look like for the k8s operator?

**Comment by AmeerHajAli** [comment]
Can we close this once we add the ray status to include failed nodes?

**Comment by AmeerHajAli** [comment]
Closing this since the final piece here is covered in this issue: https://github.com/ray-project/ray/issues/13586
