### ISSUE TITLE
KeyError on returning an ActorHandle from an Actor method.

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#1222]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.2.2
- **Python version**: 3.6
- **Exact command to reproduce**: `ray.get(actor1.get_actor2.remote())`

### Describe the problem

I get a KeyError when I try to return an ActorHandle from an ActorMethod. See the annotated logs below for details.

### Source code / logs

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/Users/DevinPetersohn/anaconda/envs/python36/lib/python3.6/site-packages/ray/actor.py", line 653, in __del__
    self._ray_actor_handle_id.id() == ray.worker.NIL_ACTOR_ID):
  File "/Users/DevinPetersohn/anaconda/envs/python36/lib/python3.6/site-packages/ray/actor.py", line 639, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'ActorHandle' object has no attribute '_ray_actor_handle_id'
```
Is it possible that the dictionary serialization of the ActorHandle is causing this problem?
```
WARNING: Serializing objects of type <class 'ray.actor.ActorHandle'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.signature.FunctionSignature'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
```
I am able to print the actor handle out here, and as long as I don't try to access anything inside the Actor, there is no problem with the rest of the code. When I do try to access something inside the actor, the code exits. No new errors are shown when it exits.
```
Actor(c9cdbeda27c4c646e398f4dfbc4f3bc2553032b2)
Traceback (most recent call last):
  File "g_main.py", line 33, in <module>
    print(ray.get(x.get_oid_dictionary.remote()))
  File "/Users/DevinPetersohn/anaconda/envs/python36/lib/python3.6/site-packages/ray/actor.py", line 419, in remote
    dependency=self.actor._ray_actor_cursor)
  File "/Users/DevinPetersohn/anaconda/envs/python36/lib/python3.6/site-packages/ray/actor.py", line 594, in _actor_method_call
    is_actor_checkpoint_method=is_actor_checkpoint_method)
  File "/Users/DevinPetersohn/anaconda/envs/python36/lib/python3.6/site-packages/ray/worker.py", line 516, in submit_task
    self.task_driver_id.id()][function_id.id()]
KeyError: b'\xfa\xb1\xdd3v\xbbz\xd4\xe1h\x0c\x1f\xe2O>\x07\xa1+,\xe1'
```

All of the logs above are repeated whether I try to access something inside the Actor or not.

Is this error due to problems rebuilding the ActorHandle?

**Comment by robertnishihara** [comment]
I think we haven't implemented support for returning actor handles from actors (we've just implemented passing them in). Do you need to return an actor handle?

E.g., if actor2 is being created inside of actor1, perhaps you can instead create actor2 outside of actor1 and then pass actor2 into actor1's init method or something like that? What does the structure of the code look like?

**Comment by devin-petersohn** [comment]
actor1 may need to create several actors, and those actors may be needed by remote functions. 

The structure of the code is such that there is a parent actor that contains several handles to several different actors. actor1 acts as the manager for these inner actors. New actors can be built at any time. To avoid having to create an ActorMethod on actor1 for each method that operates on these inner actors, or to operate on them directly, we need a way to get them out of actor1.

For now, the easy fix is to just make the outermost actor (actor1) not be an actor. The consequences of this are probably a loss of asynchrony.

**Comment by robertnishihara** [comment]
If the outer actor has the power to create/remove inner actors, that is, if the inner actors are just an implementation detail of the outer actor, then you may not want to pass the inner actors out of the outer actor. It may actually make sense to implement methods on the outer actor that just call methods on the inner actors.

**Comment by suquark** [comment]
I used such a workaround for ActorHandle issues (passing them in inside another object or just return a handle):

```python
wrapped_handle = ray.actor.wrap_actor_handle(actor_handle)
object_id = ray.put(wrapped_handle) # input
# ...
wrapped_handle = ray.get(object_id)
actor_handle = ray.actor.unwrap_actor_handle(ray.worker.global_worker, wrapped_handle) # return
```

I don't know if it is correct (assigning `global_worker` maybe potentially problematic?), but it works for me.
If it always works, I think it's better to implement `__getstate__` and `__setstate__` for ActorHandle (so that we can always serialize it), related to https://github.com/ray-project/ray/issues/1214

**Comment by robertnishihara** [comment]
@suquark, I wouldn't expect that to work. Did that work for you?

**Comment by stephanie-wang** [comment]
@suquark, that looks like it will work in most cases, but I don't think it will work if you try to return the handle from the actor creator.  We haven't yet implemented proper reference counting for passing around ActorHandles, so once the original handle goes out of scope, the actor will soon be terminated.

**Comment by suquark** [comment]
@robertnishihara It works when I tried to implement a server-client model (multiple servers processing requests from multiple clients):

```python
@ray.remote
class Server:
   # ...


@ray.remote
class Client:
    def __init__(self, servers: List[Server]):
        self.servers = servers
        for i, s in enumerate(self.servers):
            if isinstance(s, ray.actor.ActorHandleWrapper):
                self.servers[i] = ray.actor.unwrap_actor_handle(ray.worker.global_worker, s)

    # ...


servers = [Server.remote() for _ in range(4)]
_servers = [ray.actor.wrap_actor_handle(svr) for svr in servers]
clients = [Client.remote(_servers) for _ in range(40)]
# ...

```

**Comment by chtlp** [comment]
@robertnishihara  Do you have plans for supporting this feature?

It would be great if ray can return actor handles efficiently from an actor method. In our application we want to use ray as a model server, with each actor representing a model. We also have a manager actor that does the load balancing, and it would be great if the manager can return the handles of model actors to the clients.

**Comment by robertnishihara** [comment]
I think we should support this down the road. In the meantime it should be possible to work around this (e.g., by creating the model actors outside of the manager actor and then passing them in to the manager actor as well as to the clients, and then having the manager actor return some sort of identifier that the client uses to find the right handle.. I don't know enough about your application to know if that will work, but I think we can find some workaround).

It may be actually be a fairly simple change. @stephanie-wang do you think we should just go ahead and prototype this?

**Comment by chtlp** [comment]
Hi @robertnishihara thanks! The workaround you described might work, but it's quite convoluted. In our application we want to send model-serving requests from some client code, not necessarily in the actors, so if the client can dynamically get the actor handle, the it can discover the right actor to call very easily.

**Comment by robertnishihara** [comment]
Are the "clients" part of the same overall script that creates the actors? Or are the clients run in separate scripts and using the actors created in a different script?

If it's the latter, we may need to implement "named actors" to allow actors created by one job to be used in another job. I'll open an issue for this.

**Comment by chtlp** [comment]
@robertnishihara: for now the clients run in the same python program, but in different processes. But in the future we do want to run clients on different machines, and "named actors" can be very useful in that situation.

**Comment by stephanie-wang** [comment]
@robertnishihara, yes, I think we can prototype this in the next few weeks.

**Comment by robertnishihara** [comment]
@chtlp Makes sense, I created an issue for named actors at #1424.

@stephanie-wang sounds good!

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant

**Comment by rodorio** [comment]
> @robertnishihara It works when I tried to implement a server-client model (multiple servers processing requests from multiple clients):
> 
> ```python
> @ray.remote
> class Server:
>    # ...
> 
> 
> @ray.remote
> class Client:
>     def __init__(self, servers: List[Server]):
>         self.servers = servers
>         for i, s in enumerate(self.servers):
>             if isinstance(s, ray.actor.ActorHandleWrapper):
>                 self.servers[i] = ray.actor.unwrap_actor_handle(ray.worker.global_worker, s)
> 
>     # ...
> 
> 
> servers = [Server.remote() for _ in range(4)]
> _servers = [ray.actor.wrap_actor_handle(svr) for svr in servers]
> clients = [Client.remote(_servers) for _ in range(40)]
> # ...
> ```

Hello, I'm using ray version 1.0.1 on a raspberry pi and I'm trying to do something similar to what suquark mentioned above. Unfortunately the wrap_actor_handle function doesnt seem to be working:

AttributeError: module 'ray.actor' has no attribute 'wrap_actor_handle'

I'm trying to use a ray queue on the server to handle incoming requests from different clients. Once those requests are processed, I would like the server to return the value to the specific client. It's probably a bad approach, but I the way I was planning on accomplishing it was by having the client pass an actor to the server queue that would contain the request. The server would then save the result to the actor and set a flag that would let the client know the data is ready to use. However in order to do that I would need to be able to return an actor handle from the queue.

I've looked into named requests since my server and clients are on different scripts but synchronizing unique names across all the different clients seems like it would be painful. is there a better way to do this?
