### ISSUE TITLE
[aws] Docker doesn't support changing filemounts

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12220]
### What is the problem?

```
    Please ray stop & restart cluster to allow mount /root/autoscaler/:/Users/rliaw/ray/python/ray/autoscaler/ to take hold
```

If I add a file mount to an existing cluster, I can no longer start my cluster properly. This is actually a huge pain point for my development, where I sometimes need to attach different folders.

cc @ijrsvt

**Comment by ijrsvt** [comment]
@richardliaw Can you elaborate more on what you workflow is? Specifically, what state do you need to "keep in the cluster".

**Comment by richardliaw** [comment]
yeah:

```
< build yaml >
ray up yaml
... wait 10 minutes for node to get ready ...

ray exec yaml -> failed! didn't load the right file mount.

< edit yaml to correct file mounts >
ray up -y yaml # skip downloading container, skip waiting for vm to boot
.. wait 30 seconds for container to reload

ray exec yaml -> success!
```

**Comment by ijrsvt** [comment]
@richardliaw Oh! So you're totally fine with tearing down the container and restarting it :)

**Comment by richardliaw** [comment]
yep, that's right!

**Comment by richardliaw** [comment]
(but not with the vm download)

**Comment by ijrsvt** [comment]
There will be zero VM download :)

**Comment by rdonkin** [comment]
To amplify on @ijrsvt comment, I found that ssh into head node then `docker kill ray_container; docker rm ray_container` is a workaround (presumably needs to be done on all worker nodes too).

Doing a ray down and ray up with node re-use would be easier and fairly quick - but there's another bug where re-using stopped nodes causes docker to fail, so that's not an option.

**Comment by richardliaw** [comment]
@rdonkin could you create a new issue about the bug that you're facing?

I suspect it's already resolved on the new release actually.

This bug seems to be addressed already too - will close this for now.
