### ISSUE TITLE
[tune] Ray tune xgboost experiment stuck with local_mode

### ISSUE THREAD

**Issue by alokgogate** [ray-project/ray#12231]
I've recently upgraded from `ray==0.8.7` to `ray==1.0.1` and have been using xgboost with tune. I've noticed that if I have sampled 10 (or more than 1) hyperparameter configurations (using hyperopt for parameter optimization) only the first experiment starts and remains in `running` state. I've tried this a few times and was able to reproduce it with the following code. 

I've also tested by downgrading ray to `ray==0.8.7` to verify once again and was able to run all experiments without any issue

python: Anaconda distribution **3.6.4**
ray: **1.0.1**
xgboost: **1.2.1**
hyperopt: **0.2.4**

```import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import xgboost as xgb
from ray import tune
from hyperopt import hp
from ray.tune.suggest.hyperopt import HyperOptSearch
from ray.tune.utils import pin_in_object_store,get_pinned_object

ray.init(local_mode=True,dashboard_host="X.X.X.X",num_cpus=10,num_gpus=4)

import sklearn.datasets

def train_breast_cancer(config):
    model_xgb_1 = XGBClassifier(**config)
    X_train = get_pinned_object(X_id_train)
    y_train = get_pinned_object(y_id_train)
    X_test = get_pinned_object(X_id_test)
    y_test = get_pinned_object(y_id_test)
    eval_set = [(X_test,y_test)]
    model_xgb_1.fit(X_train,y_train,eval_set=eval_set,early_stopping_rounds = 500)    
    # Train the classifier
    preds_proba = model_xgb_1.predict_proba(X_test,ntree_limit=model_xgb_1.get_booster().best_ntree_limit)[:,1]
    thrshld = 0.50
    out = (preds_proba>thrshld)*1
    mean_f1 = metrics.f1_score(y_test, out)
    #track.log(mean_f1 = metrics.f1_score(y_test, out))
    tune.report(mean_f1 = metrics.f1_score(y_test, out))    

data, labels = sklearn.datasets.load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(
        data, labels, test_size=0.25)

X_id_train = pin_in_object_store(X_train)
y_id_train = pin_in_object_store(y_train)
X_id_test = pin_in_object_store(X_test)
y_id_test = pin_in_object_store(y_test)

param_meta = {'n_estimators': hp.choice('n_estimators', np.arange(300,1000,50, dtype=int)),
			  'booster' : 'gbtree',
			  'max_delta_step' : hp.choice('max_delta_step', np.arange(1,10, dtype=int)),
			  'objective' : 'binary:logistic',
			  'seed' : 42,
			  'reg_alpha' : hp.quniform ('reg_alpha', 20, 40, 5),
			  'reg_lambda' : hp.quniform ('reg_lambda', 20, 40, 5),
			  'max_depth': hp.choice('max_depth', np.arange(7,20, dtype=int)),
			  'min_child_weight': hp.quniform ('min_child_weight', 1, 20, 1),
			  'subsample': hp.uniform ('subsample', 0.8, 1),
			  'learning_rate' : hp.quniform('learning_rate', 0.3, 1.5, 0.025),
			  'gamma' : hp.quniform('gamma', 0.75, 1.5, 0.1),
			  'colsample_bytree' : hp.quniform('colsample_bytree', 0.7, 1, 0.05),
			  'colsample_bylevel' : hp.quniform('colsample_bylevel', 0.7, 1, 0.05),
			  'tree_method':'gpu_hist'
			  }
algo = HyperOptSearch(
param_meta,
metric="mean_f1",
mode="max",
)

analysis = tune.run(train_breast_cancer,
	resources_per_trial={"gpu": 1},
	verbose=1,
	search_alg=algo,
	num_samples=10,
	mode="max",
	local_dir="/local_drive/"
	)

```

- [x] I have verified my script runs in a clean environment and reproduces the issue.

cc: @richardliaw

**Comment by richardliaw** [comment]
Thanks, @alokgogate . This seems bad - what happens if you enable local_mode=False, and disable GPU usage?

**Comment by alokgogate** [comment]
Hi @richardliaw, all trials run if I disable GPU usage and enable `local_mode=False`
Also I tried setting `local_mode=False` and try with GPU and it seemed to work fine. 

the setting of `local_mode` is only for redis or applicable for the entire ray cluster?

Also if I want to set the location of plasma store, session directory etc how would I do it in v1.0.1. Earlier (v0.8.7) I used to set  `temp_dir="/path_to_nas"` and it would set all parameters correctly. In v1.0.1 didn't find `temp_dir` parameter. Would I have to set everything manually ?

**Comment by richardliaw** [comment]
Local mode is just for your own python file/"job" - so that your code runs on 1 process.

You can set `temp_dir` with a renamed parameter: `_temp_dir`: https://docs.ray.io/en/master/package-ref.html#ray-init

**Comment by richardliaw** [comment]
BTW, have you considered using `tune-sklearn` for XGBoost training?

**Comment by alokgogate** [comment]
Not yet, will take a look at it though.
