### ISSUE TITLE
Issue on page /ray-debugging.html

### ISSUE THREAD

**Issue by keyboardAnt** [ray-project/ray#12238]
AttributeError: module 'ray.util' has no attribute 'pdb'

**Comment by pcmoritz** [comment]
Thanks for the report, this is not released yet and only available in the Ray nightly (see https://docs.ray.io/en/master/installation.html#daily-releases-nightlies). Let me clarify that in the documentation!

**Comment by keyboardAnt** [comment]
Thanks

**Comment by rkooo567** [comment]
Should be available now.
