### ISSUE TITLE
Ray on PBS cluster: All workers jam on head node

### ISSUE THREAD

**Issue by Lewisracing** [ray-project/ray#12230]
I'm trying to deploy Ray on a PBS cluster. I requested 2 nodes for this

```
NODES=`cat $PBS_NODEFILE`
echo $NODES
ip_prefix=`hostname -i`
suffix=':6379'
ip_head=$ip_prefix$suffix
redis_password='5241590000000000'

echo parameters: $ip_head 
module load PyTorch
ray start --head --port=6379 --redis-password='5241590000000000'
sleep 3

for NODE in $NODES
do
  ssh -tt $NODE &
  module load PyTorch &
  ray start --address=$ip_head --redis-password='5241590000000000'

done
sleep 10

module load PyTorch
python < Main.py
```
No strange error was reported. Given the info below, I should assume that the connection is seccussful?
![image](https://user-images.githubusercontent.com/48195265/99872252-64dbf880-2bd8-11eb-8791-8611262d9480.png)
But why all the workers are still working on the head node and other one is doing nothing?
Anything wrong with the PBS shell script or what?

**Comment by Patol75** [comment]
Could be solved by #10466.
