### ISSUE TITLE
Ray worker cannot find files on cluster storage

### ISSUE THREAD

**Issue by Lewisracing** [ray-project/ray#12243]
Hi,

I'm wondering if Ray reads or write a file in the storage in a different way?

I'm trying to run Ray codes on a cluster, when I try to let a Ray worker load a file such as `np.load('aaa/asd.npy')` the program popped an error saying 'No such file or directory'. But the file is literally there and same thing happens when saving. 

(1) For non-Ray programs, it definitely works (either a local workstation or a cluster)
(2) For ray programs, it only works on my own workstation. But when it comes to the cluster, it can not find the file. So it really confuses me here. Anything I'm missing?

**Comment by rkooo567** [comment]
In a cluster setting, ray workers can run in “any machine” in your cluster. You can see the error message if the machine that runs the ray worker doesn’t have a file.

**Comment by rkooo567** [comment]
So in order to avoid this you should,

1. Make sure every machine has the same file at the same path
2. Or use file systems like NFS

**Comment by Lewisracing** [comment]
But in the cluster I'm using, all compute nodes are connected to the same storage. And there's no problem running completely separated non-ray jobs on different nodes accessing the same folder given the same relative path

**Comment by rkooo567** [comment]
In that case, why don’t you try listing files on the path you specified within a ray worker and see if the path actually does exist?

**Comment by Lewisracing** [comment]
Good idea... and interesting...  why is Ray directing me back to the user root directory...

**Comment by rkooo567** [comment]
I think it uses the path where you ran ray start. If you use autoscaler, this might be a user root directory

**Comment by Lewisracing** [comment]
> it uses the path where you ran ray start.

Yup, point made. Thanks

**Comment by Lewisracing** [comment]
> it uses the path where you ran ray start.

Yup, point made. Thanks
