### ISSUE TITLE
[core] How to assign a specific actor to a specific GPU

### ISSUE THREAD

**Issue by KyunghyunLee** [ray-project/ray#12247]
I use multiple actors for different jobs. 
I defined different functions for each job, and their computation time differ. 
Therefore, I want to assign a whole GPU for the heavy-load actor and share the other GPU for light actors. 
However, I cannot find how to assign a specific actor to a specific GPU.

Thanks!

**Comment by edoakes** [comment]
@wuisawesome what's the recommended way to do this?

**Comment by edoakes** [comment]
Btw, @KyunghyunLee this would be a good thing to ask on our discussion forum: discuss.ray.io. Would you mind re-posting there so other users can discover it more easily?

**Comment by KyunghyunLee** [comment]
@edoakes I posted a same question on discussion forum. Thanks!
https://discuss.ray.io/t/how-to-assign-a-specific-actor-to-a-specific-gpu/60

**Comment by wuisawesome** [comment]
Now that the discussion has gotten started on the forum, I will close this issue to keep things in one place.
