### ISSUE TITLE
[autoscaler] Ray autoscaler: Monitor could not find IP

### ISSUE THREAD

**Issue by swicaksono** [ray-project/ray#12248]
I have done my own research about this and tried to find relevant issues on my current problem, but I did not find any suitable reference. I tried to up my own local cluster based on this reference [local autoscaller](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml) and [the YAML file](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml). It succeeds to build the ray context in the head node, but nothing happens in the worker node.

When I checked in the logs monitor, the message error is like this:

```sh
==> /tmp/ray/session_latest/logs/monitor.out <==

==> /tmp/ray/session_2020-11-23_09-56-20_904295_22151/logs/monitor.err <==
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
Monitor: could not find ip for client 05b7f46d29ed19c4c0f85d6377e894b657054c57
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
- python 3.6.6
- ray 1.0.1.post1

This is how I run the script and the YAML file is based on the Ray git reference (link above) and I just changed the head and worker IP.

### Reproduction
```bash
ray up cluster-local.yaml
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
cc @AmeerHajAli @wuisawesome  can you help with this?

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/12138
