### ISSUE TITLE
[RLlib] Restoring GTrXLNet with A3C model requires historic observation

### ISSUE THREAD

**Issue by syed881** [ray-project/ray#12251]
Hey guys,

I have a custom environment where the observation size is (1,10) and action size is (2). For my environment, I found that A3C with GTrXLNet performs best. For GTrXLNet, I have used following configuration:

"model": {
		"custom_model": GTrXLNet,
		"max_seq_len": 10,
		"custom_model_config": {
			"num_transformer_units": 1,
			"attn_dim": 64,
			"num_heads": 2,
			"memory_tau": 50,
			"head_dim": 32,
			"ff_hidden_dim": 32,
		},
	},

It is mentioned in the GTrXLNet class that it assumes state to be the history of L recent observations. However, I have not changed anything in my environment. My custom environment returns the same sized state from both reset() and step(). I have successfully trained and saved model. Now, when I try to load the model for testing, it asks for multiple inputs. If I understood correctly, it asks me for following tensors:

Tensor("default_policy/Reshape_6:0", shape=(?, ?, 10), dtype=float32) 
[<tf.Tensor 'default_policy/Placeholder:0' shape=(?, 10, 10) dtype=float32>, <tf.Tensor 'default_policy/Placeholder_1:0' shape=(?, 50, 64) dtype=float32>] 
Tensor("default_policy/seq_lens:0", shape=(?,), dtype=int32)

As I returned the same sized state from both reset() and step() during the training, I don't know how to transform state into the required size for testing. Can anyone please help me in this issue?

Thank you in advance to anyone that is able to help me!

**Comment by krfricke** [comment]
cc @sven1977

**Comment by sven1977** [comment]
Great question @syed881 !
For testing, you should always pass in the following into your loaded model (I'm assuming this is a "raw" tf model that you call from within a session?). Or are you using a restored RLlib Trainer?

In case you are using a raw tf model loaded from a tf-export:
- observations: The current observation, but with time rank, so simply: [1=B, 1=T, [your obs dim=10]]
- list of 2 state inputs:
1) The previous 10 observations (all 0s if you are at the beginning of the episode). This way, you should get ([1=B, 10=T, [your obs dim=10]])
2) The previous 10 memory states (your memory space is (64,)). Also here: if at the beginning of the episode, 0-fill this vector at the beginning (left-side). So this should have the shape: [1=B, 10=T, 64]
- the seq_lens array, which should always be just: [1] if your batch size (B) is 1; [1, 1] if your batch size is 2, etc..

Important:
Now the 2nd state output (in your config, its always a list of 2 tensors) of the model must be fed in the next model call back in as the new value under point 2) above.
