### ISSUE TITLE
[autoscaler/k8s] Autoscaler does not recover from interruption of k8s API

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12255]
### What is the problem?
* ray==1.0.0
* kubernetes autoscaling

### Reproduction (REQUIRED)
In for example Google Cloud, it is not uncommon for the kubernetes master to be rebooted (e.g. when node-pools are added/removed, master is upgraded, etc..).
However, in this case, the k8s API used by ray autoscale is temporarily unavailable and the autoscale monitor crashes, without recovering. The head node is kept, to keep log files, but since the monitor stopped, autoscaling is not possible anymore.
In a production environment this is unacceptable behavior. Either the monitor should restart itself after failure (preferred) or the head node should also kill itself to keep the autoscaling cluster state consistent. In the latter case, the software using the ray cluster could restart the ray cluster itself.

Issue can be reproduced by e.g. killing a kubernetes master node.

Example logs:
[monitor.out.txt](https://github.com/ray-project/ray/files/5581604/monitor.out.txt)
[monitor.errr.txt](https://github.com/ray-project/ray/files/5581606/monitor.errr.txt)
In this case the issue occured in `list_namespaced_pod`. The same could happen when starting a new worker pod though, I'm not sure what will happen then...

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
^ PR above looks good.

Also @PidgeyBE I think you can set AUTOSCALER_MAX_NUM_FAILURES=99999 to achieve a similar effect:
https://github.com/ray-project/ray/blob/c0be448343a20137c20b7efae84cfc77e4981cfb/python/ray/autoscaler/_private/constants.py#L19
