### ISSUE TITLE
[metrics] CLI to easily access logs for a given job/actor/etc.

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12309]

**Comment by scottsun94** [comment]
cc: @rkooo567 should we close it since we already have ray state log api

**Comment by rkooo567** [comment]
Use `ray logs` API for this purpose. https://docs.ray.io/en/master/ray-observability/state/state-api.html#logs (note: The API is alpha, and it will be changed at beta to be something like `ray logs actor...`)
