### ISSUE TITLE
[tune] When a trainable function returns, mark it as TERMINATED

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1231]
### Describe the problem

Currently if a trainable function returns (i.e. with the `return` statement), we don't handle it specially and the actor will hang around forever.

cc @vlad17

**Comment by vlad17** [comment]
For a first version, I wanted to run a grid search that fully executes the entire training process for everything, which is the use case this would address (no stopping condition should be required, sometimes it's impossible to know how many training steps a full run will take)
