### ISSUE TITLE
Parameter Action,hidden invalid action,if all the step action in my valid action space.

### ISSUE THREAD

**Issue by oasfuyou** [ray-project/ray#12348]
I'm using ray rllib to develop a game bot, when I use the parameter action,I have hidden the invalid action by implements the TFModelV2 forward function, but the step action from the policy not all in the valid action, for example, valid action [1,5,9,15,29,90,100,190....4000], and some step action is 101, and some step in the valid action, can you help me solve this problem, wish your response as soon as possible.

**Comment by alperyyildiz** [comment]
Is it possible that you are not passing your custom model to the trainer? I faced the same issue and found out that I'm not using my custom model.

**Comment by sven1977** [comment]
Thanks for filing this issue @oasfuyou !
Also, could you provide a reproduction script? We cannot help you debug issues quickly if we don't have such a script.
