### ISSUE TITLE
[tune] Resuming an interrupted Experiment does not restart scheduled trials

### ISSUE THREAD

**Issue by thoglu** [ray-project/ray#12347]
### What is the problem?

I start a simple "Gridsearch" using the below script with args.resume=False to start a fresh Experiment. I use num_cpus=2 and resources_per_trial is 1 cpu to enforce that only 2 trials can be worked on at a time .. the other 2 are in line but not reall in state "PENDING". The output says 1/4 trials running in the beginning, because the reporter has not caught up .. in reality 2 trials are running ,and 2 are in line. After a while (~20 secs or so) I stop via ctrl+c. When I now restart the script with args.resume="LOCAL", tune will only restart those trials that were running before, and tune forgot about the "PENDING" trials .. are the 2 leftover trials really in "PENDING" state or in no state at all? Anayway, this means any continuation of the Experiment is actually incomplete.

Am I missing something and this is desired behavior? I would like to do a grid search like this in a real world situation, but I cannot seem to get proper resuming to work where also "PENDING" trials are taken into account correctly.

Side Question: Is this only a peculiarity of Grid_Search?
### Reproduction (REQUIRED)
    import sys
    import os

    import ray
    import argparse
    from ray import tune
    import numpy
    import copy
    import time

    from ray.tune import CLIReporter
    import ray.tune.syncer

    if __name__ == "__main__":

        parser = argparse.ArgumentParser('test')
        parser.add_argument("-resume", type=str, default="False")
        args=parser.parse_args()

         if(args.resume=="False"):
             args.resume=False

         def trainable(config, checkpoint_dir=None):
        
             print("running choice .. ")
             print(config["fixed_choices"])

             time.sleep(1000)

             return
        
         ## 4 choices in a grid search
         cfg=dict()

         cfg["fixed_choices"]=tune.grid_search([0,1,2,3])

         reporter = CLIReporter(max_progress_rows=10)
   
         ray.init(num_cpus=2)

         analysis = tune.run(
             trainable,
             name="tune_resume_test",
             config=cfg,
             log_to_file=True,
             num_samples=1,
             local_dir="tune_bug_test",
             resume=args.resume,
             max_failures=-1,
             resources_per_trial={"cpu": 1, "gpu": 0},
             progress_reporter=reporter)

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue occurs with the [1.0.1] release

**Comment by Gstevenson3** [comment]
Just an FYI, I have the same problem running PB2 as the trial scheduler.

**Comment by richardliaw** [comment]
This should be fixed on master.
