### ISSUE TITLE
[k8s] Kubernetes autoscaler missing kubectl-rsync.sh in wheels

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12355]
### What is the problem?

```2020-11-19 10:53:25,832	INFO updater.py:274 -- New status: waiting-for-ssh
/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/command_runner.py:212: UserWarning: NodeUpdater: ray-head-cs8vg: rsync failed: '[Errno 2] No such file or directory: '/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh': '/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh''. Falling back to 'kubectl cp'
  UserWarning)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/command_runner.py", line 206, in run_rsync_up
    "{}@{}:{}".format(self.node_id, self.namespace, target),
  File "/app/miniconda3/envs/regulator/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/app/miniconda3/envs/regulator/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/app/miniconda3/envs/regulator/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/app/miniconda3/envs/regulator/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh': '/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/kubernetes/kubectl-rsync.sh'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/miniconda3/envs/regulator/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/ray/autoscaler/_private/updater.py", line 124, in run
    self.do_update()
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
Reported by @PidgeyBE. Currently trying to reproduce.

**Comment by edoakes** [comment]
The above PR should fix the issue -- we moved some of the autoscaler source code to a `_private/` subdirectory but missed changing `setup.py`. This would have been caught if we were testing k8s autoscaler in CI (which we will be doing soon cc @simon-mo @Gekho457).

Interestingly, this seems to only be an issue on linux. Most of our local dev work is on mac using minikube which is why we weren't seeing issues when testing manually.

**Comment by edoakes** [comment]
repro:

```
(base) ray/python % docker run -it rayproject/ray:nightly bash
(base) ray@a13642853bba:/$ ls /home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/
__init__.py  __pycache__  config.py  node_provider.py
```

**Comment by Gekho457** [comment]
Confirming that rsync is working as expected -- I was able to launch a Ray cluster on Kubernetes using Ray installed from the most recent nightly wheels.
The relevant line of output is
```2020-11-24 15:43:01,008 VINFO updater.py:448 -- `rsync`ed /tmp/ray-bootstrap-h2tygiir (local) to ~/ray_bootstrap_config.yaml (remote)```
indicating that rsync successfully copied the local cluster config to the head node.
