### ISSUE TITLE
[Dashboard] Duplicate IPs/Machine View Rows in dashboard

### ISSUE THREAD

**Issue by mfitton** [ray-project/ray#12363]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
![image](https://user-images.githubusercontent.com/3156716/100145087-a70d7000-2e4c-11eb-9458-5cd3bc9d91fe.png)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mfitton** [comment]
Simon sent me a message indicating that this issue is still present. PR #12410 did not actually fix it 😢

**Comment by rkooo567** [comment]
We are distinguishing them based on the node id right? Isn't it kind of expected?

**Comment by mfitton** [comment]
Yeah, but I would expect the nodes with the same IP would all have the same node ID, so I would expect them to have the same react key and thus not have duplicate renders.

**Comment by mfitton** [comment]
I noticed that there are actually duplicate nodes in the payload with different node IDs, where one of the node's raylet is marked DEAD and the other is not. I'll continue investigating. Seems like a backend issue.

**Comment by rkooo567** [comment]
When raylet restarts, they will have the different node id although the ip is the same

**Comment by rkooo567** [comment]
It is like each raylet runtime is a new node in the perspective of gcs. We can probably just filter dead nodes from rendering?

**Comment by mfitton** [comment]
@simon-mo this is the issue I mentioned in slack.

**Comment by mfitton** [comment]
Yeah, filtering dead nodes from rendering does sound like the simplest fix. I'm going to read the code a little more, but will probably go with filtering dead nodes as a hot fix.
