### ISSUE TITLE
[RLlib] Batch size based on (multi) agent steps, not env-steps.

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#12372]
"WARNING sampler.py:743 -- More than 1033 observations for 47 env steps are buffered in the sampler. If this is more than you expected, check that that you set a horizon on your environment correctly and that it terminates at some point. **Note: In multi-agent environments, `rollout_fragment_length` sets the batch size based on environment steps, not the steps of individual agents, which can result in unexpectedly large batches**."

Can we get an option to set the batch size based on agent steps instead of environment steps? Without this, I'm not aware of any simple method for attaining reasonably sized batches in envs with a variable number of agents. Practical example: in Neural MMO, agents spawn at a constant rate, so the longer they survive (e.g. the better the policy), the more agents there are.

Joseph

**Comment by sven1977** [comment]
Great idea. We can add a single-agent-step count to the MultiAgentBatch. And then produce rollouts based on that metric, rather than env-steps. That should do it.

**Comment by jsuarez5341** [comment]
Thanks so much, Sven! Maybe soon I'll be able to experiments without having to manually kill and change the batch size part way through :)

**Comment by sven1977** [comment]
This has been merged today.
Simply set in your config:
```
config:
    multiagent:
        count_steps_by: agent_steps
        ...
```
to make the collected batches (including train batches) use the individual agent count rather than the env-step count (which remains the default).

Also: This only works if `_use_trajectory_view_api=True` in your config (default value).

**Comment by jsuarez5341** [comment]
Perfect -- I'll work on porting a my project to rllib master as soon as possible to try it out! Thanks Sven!
