### ISSUE TITLE
ray install-nightly installs older version than docs links

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12370]
### What is the problem?

Installing using `ray install-nightly`:
```
(base) code/ray % docker run -it rayproject/ray:latest bash
(base) root@4c73acfbdc9f:/# ray install-nightly
...
(base) root@4c73acfbdc9f:/# python -c "import ray;print(ray.__version__);print(ray.__commit__)"
1.1.0.dev0
9527220a868fbd57aa7617fa9a5eacecd56602db
```

Installing with link from docs:
```
(base) code/ray % docker run -it rayproject/ray:latest bash
(base) root@4c73acfbdc9f:/# pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
...
(base) root@4c73acfbdc9f:/# python -c "import ray;print(ray.__version__);print(ray.__commit__)"
1.1.0.dev0
4ada3e4c9952ffd6f573f9813a0231bafc6cf17c
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@richardliaw am I misunderstanding something here?

**Comment by richardliaw** [comment]
Yeah, basically the latest ray wheels are being written to a new path (updated after 1.0.1 was released).
