### ISSUE TITLE
[serve] serve.connect() should work with non-detached instance in non-serve actor & driver

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12383]
### What is the problem?
Users need to call serve.connect() to retrieve the handle in *non-serve managed ray actors and ray drivers*. This is currently not possible.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
This works, test here: https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_api.py#L800

**Comment by simon-mo** [comment]
It doesn't work in other ray actors or drivers.

**Comment by simon-mo** [comment]
But yeah technically this is just a feature request. Not a bug.

**Comment by edoakes** [comment]
Oh, you mean non-serve-managed actors? The issue description says serve backends and that there's no way to do composition, which does work (it's tested in the link above).

Could you clarify the feature request in the description?

**Comment by simon-mo** [comment]
Updated. thanks!

**Comment by simon-mo** [comment]
it should work now.
