### ISSUE TITLE
can not install on ubuntu 14.04 by pip

### ISSUE THREAD

**Issue by luanyunteng** [ray-project/ray#1238]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 14.04
- **Ray installed from (source or binary)**:pip
- **Ray version**:dont know
- **Python version**:2.7
- **Exact command to reproduce**:

### Describe the problem

when I try to install ray on ubuntu14.04 by pip,I got an error "Could not find any downloads that satisfy the requirement ray", when I read the pip.log, I found all the resources is "because it is not compatible with this Python"

**Comment by xhochy** [comment]
This problem is probably solved by upgrading to a newer pip version (`>=8.1.2`).
