### ISSUE TITLE
Default docker image (and all autoscaler images) does not support rllib

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12390]
### What is the problem?
Got:

```
    from ray.rllib.models.preprocessors import get_preprocessor, \
  File "/root/anaconda3/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py", line 2, in <module>
    import cv2
  File "/root/anaconda3/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
when running: 
```
rllib train --run=PPO --env=Pong-v0 --config='{"num_workers": 16, "num_sgd_iter": 1}' --num-samples=10000 --stop='{"timesteps_total": 1}' --ray-address=auto
```

workaround: https://github.com/conda-forge/pygridgen-feedstock/issues/10

cc @ericl @sven1977 @ijrsvt

**Comment by ijrsvt** [comment]
@richardliaw Which images (`ray`, `ray-ml`, `autoscaler`) and which tags (`nightly`, `latest`)

**Comment by richardliaw** [comment]
ah, i see - i ran `rayproject/ray:latest`; perhaps instead, it would be good to add a reference to `ray-ml` this explicitly in all of the example yamls.

**Comment by ericl** [comment]
@ijrsvt can you change the yamls to ray-ml by default?

**Comment by ijrsvt** [comment]
@ericl I'm okay with doing this--my only concern is that it _will slow down the pull time_.

**Comment by ericl** [comment]
Can you add the original image as a second line with a comment as a hint to the user? e.g.
```
image: ray-ml:latest
# image: ray:latest   # use this one if you don't need ML dependencies, it's faster
```

**Comment by ijrsvt** [comment]
@ericl Great idea!! :) Will do ASAP
