### ISSUE TITLE
[ci] re-enable gcs fault tolerance tests

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12412]
Tests were skipped https://github.com/ray-project/ray/pull/12393.

cc @WangTaoTheTonic @rkooo567 @wumuzi520

**Comment by rkooo567** [comment]
@wuisawesome This needs to be on again when the new scheduler is on

**Comment by wuisawesome** [comment]
I see, it sounds like these tests really depend on placement groups to be implemented?

**Comment by wuisawesome** [comment]
Or rather, maybe I should ask: does this depend on anything other than placement groups?

**Comment by rkooo567** [comment]
I need to look at which tests are skipped, but there’s high possibility it is not only related to the placement group impl.

**Comment by WangTaoTheTonic** [comment]
This should be done by placement group, and new scheduler(perhaps not very much). 
/cc @ffbin
