### ISSUE TITLE
ImportError: cannot import name resources_to_json

### ISSUE THREAD

**Issue by luanyunteng** [ray-project/ray#1242]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 14.04
- **Ray installed from (source or binary)**:pip
- **Ray version**:0.2.2
- **Python version**:2.7
- **Exact command to reproduce**:

### Describe the problem

when I try the command
`python ray/python/ray/rllib/train.py --env CartPole-v0 --alg PPO --config '{"timesteps_per_batch": 10000}'`
I got an error
`Traceback (most recent call last):
  File "ray/python/ray/rllib/train.py", line 11, in <module>
    from ray.tune.config_parser import make_parser, resources_to_json
ImportError: cannot import name resources_to_json`

and I install by pip:
`lyt@up111:~$ pip install ray
Requirement already satisfied: ray in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: redis in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: six>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: flatbuffers in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: cloudpickle>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: funcsigs in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: pytest in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from ray)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from pytest->ray)
Requirement already satisfied: py>=1.4.33 in /usr/local/lib/python2.7/dist-packages (from pytest->ray)`

**Comment by robertnishihara** [comment]
Hi, I believe this is the same issue as #1216 (basically a mismatch between the Ray version and the Ray source code that you've cloned).
