### ISSUE TITLE
[New scheduler] Fix test_global_gc::test_global_gc_actors

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#12438]

**Comment by kfstorm** [comment]
When the new scheduler is enabled, local GC is not triggered. The root cause is that `local_queues_.GetTasks(TaskState::READY)` returns an empty list, thus `any_pending` is always false.

https://github.com/ray-project/ray/blob/6475297bd3774fa1bdad5233164d2aa65e2c86e5/src/ray/raylet/node_manager.cc#L642-L660

@wuisawesome

**Comment by ericl** [comment]
Hey @kfstorm just checking, since you self-assigned are you planning to submit a patch?

**Comment by kfstorm** [comment]
Oh, sorry. I forgot to follow this issue. @wuisawesome Do you know if there's a quick fix so I don't need to go through the new scheduler logic?

**Comment by wuisawesome** [comment]
I think our dispatch queue is equivalent to the ready queue in the old scheduler.

**Comment by ericl** [comment]
@wuisawesome isn't it actually `tasks_to_schedule_` (after calling SchedulePendingTasks() to process any schedulable tasks to the waiting or dispatch queues)?

I added some more comments to the headers here to try to clarify: https://github.com/ray-project/ray/pull/12730

**Comment by wuisawesome** [comment]
Isn't the transition in the old scheduler Infeasible -> Placeable -> Waiting -> Ready -> Running?

**Comment by ericl** [comment]
The new scheduler is doing something more like this:
```
Schedulable ----> Waiting ----> Dispatch ----> Lease granted
          \-----------------------^
```

**Comment by wuisawesome** [comment]
Right, which would mean that the dispatch queue in the new scheduler is most analogous to the ready queue in the old one.

**Comment by ericl** [comment]
Dispatch queue has different semantics though right? It means waiting for
workers, not waiting for resources.

**Comment by wuisawesome** [comment]
I think it's possible to be waiting on resources in either queue (like in the old scheduler). Tasks always move from the waiting queue to the dispatch queue, so a task can go on the waiting queue, then while its dependencies are being fulfilled the node's resources are taken up (this is why `AttemptDispatchWork` returns a boolean)

**Comment by ericl** [comment]
That's awkward, it means we can't look at the state of the queues and make a determination of whether tasks are currently blocked on resources only right? So you have to do some calculation on the tasks in the waiting queue as well.

Maybe we can just iterate over all tasks in the scheduling queue and also waiting queue that don't fit into local resources. The cluster_task_manager can provide a visitor function like `foreach_task_awaiting_resources(std::function<void(Task)> visitor)`.

Relatedly, it seems concerning we iterate over all READY tasks in the existing scheduler, since that could be an O(n) operation. I guess it's not an issue with the direct call architecture though since the number of task lease requests is usually quite small.

**Comment by ericl** [comment]
Alternatively, we could have `::TasksUnblocked()` move tasks from `waiting` back to `tasks_to_schedule`. The next ScheduleAndDispatch will move those tasks directly to `dispatch`.

That way, we just need to check `tasks_to_schedule` for all tasks waiting on resources. Eventually all tasks blocked on resource demands will end up there.

**Comment by ericl** [comment]
@kfstorm are you still working on this, or should we take it over? We have a soft deadline of end of this week.

**Comment by kfstorm** [comment]
@ericl @wuisawesome After looking into this issue again, I still don't know a clear way to fix it. Maybe you guys could take over this issue?
