### ISSUE TITLE
[New scheduler] Fix test_gcs_fault_tolerance::test_gcs_server_restart

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#12436]

**Comment by rkooo567** [comment]
Yep! That’s correct. Actually, @wuisawesome is taking a look at adding the pg feature to the new scheduler!

**Comment by wuisawesome** [comment]
@kfstorm I will implement placement groups for the new scheduler. If that doesn't fix the problem, can you take over this?

**Comment by kfstorm** [comment]
@wuisawesome Sure. Let me know when it's ready.

**Comment by wuisawesome** [comment]
@clay4444  since you're taking over the placement group PR, can you notify @kfstorm when it's ready?

**Comment by clay4444** [comment]
@wuisawesome   sure.
