### ISSUE TITLE
[autoscaler] initial_workers does not work

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12444]
### What is the problem?

* ray nightly

### Reproduction (REQUIRED)
1. Start a k8s autoscaling cluster with a config.yaml that has `initial_workers: 1`
Result: No initial workers are started

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by AmeerHajAli** [comment]
Hi @PidgeyBE , we no longer support `initial_workers` with the new autoscaler. What is your use case? why do you need it?

**Comment by PidgeyBE** [comment]
Hi @AmeerHajAli 
We don't necessarily need it. I just wasn't aware that it was deprecated and saw it wasn't working anymore...
Can be closed for me! :+1:

**Comment by edoakes** [comment]
@AmeerHajAli can we make this deprecation more clear to users? e.g., throwing an error if initial_workers is included in the YAML?
