### ISSUE TITLE
[core] Cloudpickle can't handle Union typing and other generics

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12445]
### What is the problem?
*ray 1.0.0

### Reproduction (REQUIRED)
In our application, we are facing issues with pickling Union type hints and Generics.
Currently we patch ray Cloudpickle with 2 functions:
```
def cleanup_unions(annotations):
    def _is_union(v) -> bool:
        return "typing.Union" in str(v)

    return {k: v for k, v in annotations.items() if not _is_union(v)}


def cleanup_generics(obj):
    # Inspired by https://gist.github.com/pitrou/a14a012871e852fdfaddbd8141d59611
    for k in list(obj):
        if k.startswith("_abc_"):
            del obj[k]
```
The Monkeypatch itself looks like this:
```
    # === PATCH ===============================================================
    if sys.version_info < (3, 7):
        annos = clsdict.get("__annotations__", None)
        if annos is not None:
            clsdict["__annotations__"] = cleanup_unions(annos)
        cleanup_generics(clsdict)
    # === PATCH ===============================================================
```
and we apply them in 4 methods:
```
    ray.cloudpickle.cloudpickle_fast._function_getstate
    ray.cloudpickle.cloudpickle_fast._class_getstate
    ray.cloudpickle.cloudpickle.CloudPickler.save_function_tuple
    ray.cloudpickle.cloudpickle.CloudPickler.save_dynamic_class
```
The last 2 methods are not available anymore in the latest ray master.

To reproduce:
```
from ray import cloudpickle
from typing import Union

def function() -> Union[str, int]:
    return "test"

a = cloudpickle.loads(cloudpickle.dumps(function))
```
-> `PicklingError: Can't pickle typing.Union[str, int]: it's not the same object as typing.Union`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by suquark** [comment]
This could because we upgrade the cloudpickle version. We could not revert it to the older version, because the older version fails when serializing some other objects.

For the current cloudpickle version, `ray.cloudpickle.cloudpickle.CloudPickler.save_function_tuple` is moved to `ray.cloudpickle.cloudpickle_fast. CloudPickler._dynamic_function_reduce`; `ray.cloudpickle.cloudpickle.CloudPickler.save_dynamic_class` is moved to `ray.cloudpickle.cloudpickle_fast. _dynamic_class_reduce `

**Comment by PidgeyBE** [comment]
Issue not reproducible anymore in ray 1.1.0
