### ISSUE TITLE
Getting `AttributeError: 'StandardStreamInterceptor' object has no attribute 'close'` when running e.g. a test case.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#12452]
I'm getting
`AttributeError: 'StandardStreamInterceptor' object has no attribute 'close'`
when running e.g. a test case.

This shows up on:
MacOS (and also our travis)
Py3.7
Ray 1.1.0dev (master branch)

Reproduce e.g.:
```
python ray/rllib/tests/test_supported_spaces.py
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Fixed.
