### ISSUE TITLE
[SGD] Inconsistent timeout units used in SGD

### ISSUE THREAD

**Issue by liside** [ray-project/ray#12466]
### What is the problem?
Inconsistent timeout units used in SGD, making it unable to time out properly.

TorchTrainer in RaySGD takes a parameter timeout_s: 
```
timeout_s (float): Seconds before the torch process group times out. Useful when machines are unreliable.
```
In the remote mode, TorchTrainer wraps timedelta around the given timeout in seconds to initialize workers. As per Python doc, timedelta turns *a duration expressing the difference between two date, time, or datetime instances to microsecond resolution*. If one gives 10.0 to TorchTrainer, timedelta will turn it into 10 days, causing it nearly impossible to time out. See: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/worker_group.py#L178

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray v1.0.0, PyTorch v1.7.0, Ubuntu v18.04

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Any tutorial code using remote workers would reproduce this bug.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
cc @amogkam

**Comment by amogkam** [comment]
This is a good catch @liside! Should be fixed in #12477

**Comment by liside** [comment]
You might want to change this line as well: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/worker_group.py#L470

**Comment by amogkam** [comment]
Oh right another good catch ;)
