### ISSUE TITLE
[autoscaler] Remote execution gets slower, much space used on head node

### ISSUE THREAD

**Issue by night-fury-web** [ray-project/ray#12479]
Ray 1.0.1
Python 3.7.6 on conda
Ubuntu 18.04

After a few hours running remote functions, remote functions take much time than the beginning.
If I `ray stop` on head node and `ray up xx.yaml` on driver node, this issue disappears. And it happens again after a few hours.
Also `/tmp/ray` takes much storage if head node is running quite long time. Is there any command to clean unnecessary files?
I just use `rm -rf /tmp/ray` at the moment.

**Comment by sandguardian** [comment]
Here is `raylet.out`.
[raylet.zip](https://github.com/ray-project/ray/files/5612697/raylet.zip)

**Comment by sandguardian** [comment]
```
eval_pool = ActorPool(
    [
        RayClass.remote(data)
        for _ in range(100)
    ]
)
unordered_results = list(
    eval_pool.map_unordered(
        lambda actor, item: actor.ray_remote_function.remote(
            func, item
        ),
        items,
    )
)
```

My project runs this part again and again. In the beginning it takes about 1 to 2 secs, but after a few hours it takes over 8 secs.

CC @rkooo567

**Comment by rkooo567** [comment]
About the logs size, you will be able to configure log rotation very soon (within a couple weeks).

**Comment by rkooo567** [comment]
Do you think it is possible to create a reproducible script?

**Comment by rkooo567** [comment]
I will spend time on this once you create a script!
