### ISSUE TITLE
[rllib][tune][ddppo] additional worker instances not started

### ISSUE THREAD

**Issue by ghost** [ray-project/ray#12470]
### What is the problem?
Hi, I want to start ray rllib distributed DDPPO.
Attached is a basic test-app that shows that no additional instances are created, based on the custom_env.py
Expected output:
running rllib with 2 or 3(?) instances 1. ray head, 2. + 3. workers
got:

> ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 9 CPUs, 2 GPUs, but the cluster has only 32 CPUs, 1 GPUs, 11.96 GiB heap, 25.54 GiB objects (1.0 node:172.31.24.76, 1.0 accelerator_type:T4). Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available.

It should start a second instance I suppose.
As I understood DDPPO, the head-instance also needs 1 GPU for training but should start n workers  (with GPU) for sampling.

ray, version 1.0.1.post1, Python 3.8.5

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
test_app.py (sry, python code highlighting is not working correctly):
import argparse
import gym
from gym.spaces import Discrete, Box
import numpy as np

import ray
from ray import tune
from ray.tune import grid_search, register_trainable
from ray.rllib.agents.ppo import ddppo, ppo
from ray.rllib.models import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.models.tf.fcnet import FullyConnectedNetwork
from ray.rllib.models.torch.torch_modelv2 import TorchModelV2
from ray.rllib.models.torch.fcnet import FullyConnectedNetwork as TorchFC
from ray.rllib.utils.framework import try_import_tf, try_import_torch
from ray.rllib.utils.test_utils import check_learning_achieved

import os

torch, nn = try_import_torch()

parser = argparse.ArgumentParser()
parser.add_argument("--run", type=str, default="DDPPO")
parser.add_argument("--torch", action="store_true")
parser.add_argument("--as-test", action="store_true")
parser.add_argument("--stop-iters", type=int, default=200)  
parser.add_argument("--stop-timesteps", type=int, default=100000)
parser.add_argument("--stop-reward", type=float, default=1e3)

class SimpleTableEnv(gym.Env):

    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(
            0.0, self.end_pos, shape=(1, ), dtype=np.float32)

    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]

    def step(self, action):
        assert action in [0, 1], action
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1.0 if done else -0.1, done, {}

class TorchCustomModel(TorchModelV2, nn.Module):
    """Example of a PyTorch custom model that just delegates to a fc-net."""

    def __init__(self, obs_space, action_space, num_outputs, model_config,
                name):
        TorchModelV2.__init__(self, obs_space, action_space, num_outputs,
                            model_config, name)
        nn.Module.__init__(self)

        self.torch_sub_model = TorchFC(obs_space, action_space, num_outputs,
                                    model_config, name)

    def forward(self, input_dict, state, seq_lens):
        fc_out, _ = self.torch_sub_model(input_dict, state, seq_lens)
        return fc_out, []

    def value_function(self):
        return torch.reshape(self.torch_sub_model.value_function(), [-1])

if __name__ == "__main__":
    args = parser.parse_args()
    args.torch = True
    ray.init(address='auto', _redis_password='5241590000000000')   

    ModelCatalog.register_custom_model(
        "my_model", TorchCustomModel)

    config = {
        "env": SimpleTableEnv, 
        "env_config": {
        },
        "model": {
            "custom_model": "my_model",
        },
        "vf_share_layers": True,    
        "vf_loss_coeff": 1.0,
        "lr": 1e-4, 
        "kl_coeff": .2,   
        "num_workers": 2, 
        "framework": "torch" if args.torch else "tf",
    }

    stop = {
        "training_iteration": args.stop_iters,
        "timesteps_total": args.stop_timesteps,
        "episode_reward_mean": args.stop_reward,
    }

    import ray.rllib.agents.ppo.ddppo as ddppo 
    DEFAULT_CONFIG = ddppo.DEFAULT_CONFIG.copy()
    DEFAULT_CONFIG["num_gpus"] = 0
    DEFAULT_CONFIG["num_envs_per_worker"] = 1
    DEFAULT_CONFIG["use_gae"] = True
    DEFAULT_CONFIG["lambda"] = 0.95
    DEFAULT_CONFIG["discount"] = 0.96
    DEFAULT_CONFIG["num_gpus_per_worker"] = 1
    DEFAULT_CONFIG["num_cpus_per_worker"] = 4
    DEFAULT_CONFIG["rollout_fragment_length"] = 64  
    DEFAULT_CONFIG["sgd_minibatch_size"] = 64 
    DEFAULT_CONFIG["train_batch_size"]  -1
    
    print("config", DEFAULT_CONFIG)

    MyTrainer = ppo.PPOTrainer.with_updates(
        name="DDPPO",
        default_config=DEFAULT_CONFIG,
        execution_plan=ddppo.execution_plan,
        validate_config=ddppo.validate_config)

    trials = tune.run(MyTrainer, 
        name="test", 
        config=config, 
        stop=stop,
        local_dir="~/ray_results",
    )
    if args.as_test:
        check_learning_achieved(trials, args.stop_reward)

    ray.shutdown()

aws.yaml, nothing special here, only:
max_workers: 8
InstanceType: g4dn.8xlarge

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
> trial requested 9 CPUs, 2 GPUs, but the cluster has only 32 CPUs, 1 GPUs

It doesn't work since your cluster only has 1 GPU. You could try num_gpus: 0.5 to allow two workers on a GPU.

**Comment by 1seck** [comment]
Hi there, thank you I will try that, but the question was also why the
engine does not automatically start another worker instance on aws, since
in ddppo the head also needs 1 GPU for calculations.
Or more general, since I am trying for some weeks now to get an industry
standard model and physics model to run: what are good configurations? P2
xlarge have to few mem since the whole model params are saved into memory
etc.
New error is now batch sizes of gru are not as expected but only after some
calculations which I think is because of end batches at the end of an
iteration or episode or alike, could that be the case?
Sry for putting all in one issue :)

But rllib is production ready, and used for industry models, right?

Eric Liang <notifications@github.com> schrieb am Di., 8. Dez. 2020, 20:53:

**Comment by ericl** [comment]
Is your cluster configured to have GPU worker nodes? https://docs.ray.io/en/master/cluster/autoscaling.html

I would try out a basic non-autoscaling setup first (perhaps with a single p2.8xl or p2.16xl), to validate things work before running with multiple nodes.

**Comment by 1seck** [comment]
That I actually did which goes, but then I switched to g4dn with 1 GPU and the scaling works fine now with 1 head, 2 workers. I added queue_trials=True.
Getting lim increase soon. Only  problem now is the batch size problem.

**Comment by 1seck** [comment]
I suppose the error was that relic does not wait until the autoscaled instance workers are started up and with `queue_trials=True ` works fine now, could that be, then we can close the issue.
