### ISSUE TITLE
[docs][core] Documentation improvement in master/walkthrough.html

### ISSUE THREAD

**Issue by micahtyong** [ray-project/ray#12472]
### Minor improvements/fixes in Ray Core Walkthrough

1. In the ["Cancelling Tasks" section](https://docs.ray.io/en/master/walkthrough.html#cancelling-tasks), it would be useful to demonstrate what happens when `ray.get` is called on a reference that has been canceled. 
2. In the ["Fetching Results" section](https://docs.ray.io/en/master/walkthrough.html#fetching-results), defining `long_running_function()`is missing a colon. 
3. In the ["Calling the actor" section](https://docs.ray.io/en/master/walkthrough.html#calling-the-actor), an assert statement should be called instead for consistent error handling throughout this tutorial.

**Comment by micahtyong** [comment]
Assigning myself: @micahtyong

**Comment by richardliaw** [comment]
awesome! feel free to cc me when you open a PR.
