### ISSUE TITLE
[RLLib] Formatting file names of episodes in model evaluation

### ISSUE THREAD

**Issue by abrandenb** [ray-project/ray#12480]
### Improvement of model evaluation outputs: It is currently not possible to change the file names of the episodes that are collected for evaluation. 

Being able to format the output files to a format such as `output-{TRAINSTEP}-worker{ID}_{BATCH}.json` can lead to a cleaner representation of evaluation episodes. More specifically, in many applications, the training step of evaluation is more important than the walltime. _As far as I see it, the training step is currently not even included in data of the evaluation output file itself._ 

In general, this would make searching for specific episodes a lot easier, since you would not need to open the files to extract specific meta-data that you could easily retrieve from a nicely formatted filename. 

This has shortly been discussed with @sven1977 on the [ray discussion board](https://discuss.ray.io/t/formatting-output-file-names-organizing-saved-episodes/81).

I would suggest to accept a custom function `evaluation_format_fn` as a parameter for the Trainer. This function would be called *for each episode* with the corresponding episode data (recorded states) and metadata (worker ID, training step, batch_ID, ...) and outputs a string file name. In my opinion, this would be an elegant solution, as the user can select the data that is most interesting for the use-case, as well as allow for saving in custom directories. As i am fairly new to the ray architecture, i am unsure if this suggestion is viable or not. 

Let me know what you think!

**Comment by sven1977** [comment]
This is a great suggestion @abrandenb . I will take a look at this. We should also have a "output_max_num_episodes" parameter that limits the number of episodes in one file. If either `output_max_num_episodes` or `output_max_file_size` is None, RLlib will use only one of these restrictions, if both are given, they are both max conditions. At least one of them must be provided.

**Comment by abrandenb** [comment]
Thanks for the response @sven1977 ! Just a minor comment from my side:

>  If either `output_max_num_episodes` or `output_max_file_size` is None, RLlib will use only one of these restrictions, if both are given, they are both max conditions. <ins>**At least one of them must be provided.**</ins>

Is there a specific reason why splitting the output has to be enforced? I do agree, that the default should include some type of file splitting (e.g. by `output_max_file_size` as it is currently), since this prevents the unwilling generation of virtually unreadable monster-files. However, if a user may decide that saving all episodes into a single large file would be better for their application, I don't see necessity to keep them from doing so. Please correct me if I'm missing something!

**Comment by jlshin** [comment]
Did this get implemented?
