### ISSUE TITLE
Pruning / Quantization support

### ISSUE THREAD

**Issue by hoangpm-2081** [ray-project/ray#12489]
Hello Ray :)
I have a question: 
"In the near future, can ur framework support pruning and quantization model like tf lite and if can how long u guys build it ?"
Thank for read my question

**Comment by krfricke** [comment]
Hi @hoangpm-2081, since Ray is a general computing framework there are no restrictions for other libraries or frameworks you might want to use.
Are you maybe inquiring specifically about RLLib?

**Comment by hoangpm-2081** [comment]
Ok thank because i think pruning/quantization are the optimization of ML model. I think optimization is an important part in deploying ML model. Then i want your implement in the near future not import some thrid-party packages.
Thank for replying
