### ISSUE TITLE
[rllib] Discrete(20) Observation_space  gets converted to Box(-1,1,(20,)) inside agent

### ISSUE THREAD

**Issue by VenezianoMauro** [ray-project/ray#12483]
### What is the problem?
Running tutorial:
https://colab.research.google.com/github/ray-project/tutorial/blob/master/rllib_exercises/rllib_colab.ipynb

Observation space is Discrete(20) in the environment. When training there is no problem but when  doing trainer.compute_action(state) raises ValueError: ('Observation ({}) outside given space ({})!', array(0), Box(-1.0, 1.0, (20,), float32))

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version 1.0.1.post1
Python version 3.7.9
Pytorch version 1.7.0+cpu
OS windows 10

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import gym
from gym import spaces
import numpy as np
import ray
from ray.rllib.agents.ppo import PPOTrainer, DEFAULT_CONFIG
ray.init(ignore_reinit_error=True, log_to_driver=False)

class ChainEnv(gym.Env):
    def __init__(self, env_config = None):
        env_config = env_config or {}
        self.n = env_config.get("n", 20)
        self.small_reward = env_config.get("small", 2)  # payout for 'backwards' action
        self.large_reward = env_config.get("large", 10)  # payout at end of chain for 'forwards' action
        self.state = 0  # Start at beginning of the chain
        self._horizon = self.n
        self._counter = 0  # For terminating the episode
        self._setup_spaces()
    
    def _setup_spaces(self):
        ##############
        # TODO: Implement this so that it passes tests
        self.action_space = spaces.Discrete(2)
        self.observation_space = spaces.Discrete(self.n)
        ##############

    def step(self, action):
        assert self.action_space.contains(action)
        if action == 1:  # 'backwards': go back to the beginning, get small reward
            ##############
            # TODO 2: Implement this so that it passes tests
            reward = self.small_reward
            ##############
            self.state = 0
        elif self.state < self.n - 1:  # 'forwards': go up along the chain
            ##############
            # TODO 2: Implement this so that it passes tests
            reward = 0
            self.state += 1
        else:  # 'forwards': stay at the end of the chain, collect large reward
            ##############
            # TODO 2: Implement this so that it passes tests
            reward = self.large_reward
            ##############
        self._counter += 1
        done = self._counter >= self._horizon
        return self.state, reward, done, {}

    def reset(self):
        self.state = 0
        self._counter = 0
        return self.state
    
trainer_config = DEFAULT_CONFIG.copy()
trainer_config['num_workers'] = 1
trainer_config["train_batch_size"] = 400
trainer_config["sgd_minibatch_size"] = 64
trainer_config["num_sgd_iter"] = 10
trainer_config["framework"] = "torch"

trainer = PPOTrainer(trainer_config, ChainEnv);
for i in range(2):
    print("Training iteration {}...".format(i))
    trainer.train()

env = ChainEnv({})
state = env.reset()

done = False
max_state = -1
cumulative_reward = 0

while not done:
    state = np.array(state)
    action = trainer.compute_action(state)
    state, reward, done, results = env.step(action)
    max_state = max(max_state, state)
    cumulative_reward += reward

print("Cumulative reward you've received is: {}. Congratulations!".format(cumulative_reward))
print("Max state you've visited is: {}. This is out of {} states.".format(max_state, env.n))
```

If we cannot run your script, we cannot fix your issue.

- [yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [ yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this @VenezianoMauro ! Taking a look rn.

**Comment by sven1977** [comment]
Hmm, apparently our OneHotPreprocessor (the one that transforms int observations into one-hot Boxes) does not store the "original_space" property in the new space, leading the Trainer's local_worker to believe that its Policy has the Box space as its original one (instead of Discrete(20)).
This is fixed with this PR: 
As a workaround for right now, replace the if-block in line in rllib/models/preprocessors.py:~83
```
        if (isinstance(self, TupleFlatteningPreprocessor)
                or isinstance(self, DictFlatteningPreprocessor)
                or isinstance(self, RepeatedValuesPreprocessor)):
```
with this one here:
```
        if isinstance(self, (DictFlatteningPreprocessor, OneHotPreprocessor,
                             RepeatedValuesPreprocessor,
                             TupleFlatteningPreprocessor)):
```

**Comment by sven1977** [comment]
This is also related to this issue here: https://github.com/ray-project/ray/issues/12516

**Comment by sven1977** [comment]
I'm closing this issue. Please feel free to re-open it should the above solution/PR not work on your end.

**Comment by nitsan57** [comment]
Hi,
I am having the exact same issue, I used this change, and I still gets a box observation space instead of discrete.
any more potential issues?

**Comment by phixxx5** [comment]
I'm still experiencing this error with my code as well as with the test script in here. I'm on version 1.1.0. The workaround doesn't work for me. Maybe this should be re-opened? @sven1977

**Comment by phixxx5** [comment]
actually my problem was fixed by the workaround in https://github.com/ray-project/ray/issues/12516#issuecomment-741667729
Thanks!
