### ISSUE TITLE
[tune] How can i get 'metric' value currently of all trials while running Ray? 

### ISSUE THREAD

**Issue by LianShuaiLong** [ray-project/ray#12487]
### What is the problem?
I want to get 'metric' best so far during running ray, and to help me decide whether to save model trained by current trial.
so what should i do?  

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Hi @LianShuaiLong, could you give us a concrete example where in your code you'd want to implement such logic? Since `tune.run()` is a blocking call and waits until all trials are finished (or another stopping condition is reached) I think it must happen within a trial. 

However, trial trainables currently do not receive any information about other trials. You will probably have to keep at least one checkpoint per trial, and can decide after the run which checkpoint to keep:

```
analysis = tune.run(....)
best_checkpoint_dir = analysis.best_trial.checkpoint.value
# ...
```

**Comment by LianShuaiLong** [comment]
> Hi @LianShuaiLong, could you give us a concrete example where in your code you'd want to implement such logic? Since `tune.run()` is a blocking call and waits until all trials are finished (or another stopping condition is reached) I think it must happen within a trial.
> 
> However, trial trainables currently do not receive any information about other trials. You will probably have to keep at least one checkpoint per trial, and can decide after the run which checkpoint to keep:
> 
> ```
> analysis = tune.run(....)
> best_checkpoint_dir = analysis.best_trial.checkpoint.value
> # ...
> ```

Since it takes too long to finish all trials, i want to get the best model currently anytime during training.

**Comment by LianShuaiLong** [comment]
is there any way to get name of the trial during running ray?

**Comment by LianShuaiLong** [comment]
https://github.com/ray-project/ray/issues/6796#issuecomment-736340082
