### ISSUE TITLE
[autoscaler] Any way to download files from the all worker nodes?

### ISSUE THREAD

**Issue by rightx2** [ray-project/ray#12497]
I'm using ray autoscaler with multiple nodes of the AWS ec2

What I want to do is to aggregate files generated in each worker node to my local machine (My Ray Actor process on each worker will generate a bunch of files on its own file system)

Here are some ideas:

1. `ray rsync-down` looks good but it works only for the head node, not all other worker nodes

2. `ray exec "scp ALL_FILES user_name@MY_LOCAL_MACHINE_IP:~/`: it looks good as well but only works with the head node.

Any idea, please?

**Comment by limenutt** [comment]
Would it be possible to reopen it?
