### ISSUE TITLE
[rllib] episode reward mean

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#12491]
Hello, I try to run my code via rllib. But, I find the rllib auto generated ray results episode reward mean is not equal my code records. I want to know how to calculate the episode reward mean.  By the way, my code is  8 agent.

**Comment by ingambe** [comment]
Have you checked the `metrics_smoothing_episodes` parameter?
It defines the number of episodes to consider in the computation of these average/min/max metric

**Comment by zzchuman** [comment]
> 您检查`metrics_smoothing_episodes`参数了吗？
> 它定义了在计算这些平均/最小/最大度量时要考虑的情节数

Thank you! I am sure that I am not use the smoothing! 
I  use the independent PPO to control 9 agents.
So, I want to know that the episode reward mean is the mean value of multi agents per episode? right?

**Comment by zzchuman** [comment]
> metrics_smoothing_episodes

I am not define the metrics_smoothing_episodes. 

# Wait for metric batches for at most this many seconds. Those that have not returned in time will be collected in the next train iteration.
 "collect_metrics_timeout": 180,
 # Smooth metrics over this many episodes.            "metrics_smoothing_episodes": 100,

So, it is  the default 100.
And, I want to know that  the episode reward mean is the mean value of multi agents?

**Comment by mingju88D** [comment]
Does this means the average mean for one episode will need to be divided by 100? I am asking this is because my own code only evaluates the mean reward only on one episode.

**Comment by mingjunwang88** [comment]
Does this means the average mean for one episode will need to be divided by 100? I am asking this is because my own code only evaluates the mean reward only on one episode.

**Comment by ericl** [comment]
It will be averaged (smoothed) over the last 100 completed episodes of training overall.

**Comment by mingjunwang88** [comment]
make sense. Thanks @ericl
