### ISSUE TITLE
[rllib] significant performance difference between Torch and TF PPO policy

### ISSUE THREAD

**Issue by LARS12llt** [ray-project/ray#12494]
### Describe your feature request
Runing the same **PPO algorithm with same NN model, weight inititialization and  hyperparameters**, **TF significantly outperforms pytorch** in OpenAI procgen benchmark, a video game like Atari for Reinforcement Learning benchmark. What's more, TF runs faster than Pytorch (TF:90mins, Pytorch:120 mins), when environment time-steps is 8M. 
I try different binaries of ray (0.8.6, 0.8.7) and versions of pytorch (1.4.0, 1.5.0, 1.6.0, 1.7.0), but get the same results. 
With double check the PPO algorithm in rllib ( ppo_torch_policy and ppo_tf_policy), I am sure taht thay are the same. Is it possibile that the different sampling in workers contributes to this dramatically different performances? 

Is there any suggestion or solution to this problem?

**Comment by ingambe** [comment]
I've made the same observation with custom parametric model.
Tensorflow is about 15% faster in my benchmark.

**Comment by ericl** [comment]
I think this is expected, it's just a performance difference between the frameworks.

**Comment by LARS12llt** [comment]
@ericl @ingambe Thanks for replying. Yes, minor implementation differences between different frameworks could sometimes cause a significant difference. After tunning a lot in pytorch with ray and many discussions with ray users,  I don't think this  is the only reason.
After discuss with other competitors in NeurIPS 2020 procgen competition, which use ray as default distirbuted framework, I think the sampling process in ray with pytorch works, but the training process may not. One competitor rewrite the training code, and bridge the performance gap between TF and Pytorch.  This is mostly because rllib is not optimized for pytorch ppo policy at this point, I guess.
Here is a relevant discussion https://discourse.aicrowd.com/t/how-to-find-subtle-implementation-details/3585

**Comment by ericl** [comment]
Interesting. This could be the case, especially if you are seeing learning performance differences (and not just wall-time compute differences). @sven1977 might be worth taking a look here to see if we can pick up those fixes.

**Comment by sven1977** [comment]
Yeah, on wall-time, no doubt, TorchPPO is slower. But I don't remember seeing any learning performance differences when I recently ran PPO Atari benchmarks (I ran both tf and torch).
The big difference I still see is only:
- default initialization of weights in Dense layers is Xavier in tf and normc in torch (our SlimFC class actually uses Xavier as default, but we override this with normc if we create SlimFCs via our FullyConnectedNetwork or VisionNetworks).

I just checked the default Adam optimizer used by most of our algos (also PPO) and they both have: `beta1=0.9, beta2=0.999, epsilon=1e-08`.

**Comment by LARS12llt** [comment]
Thanks. I am trying to provide more details and a clear code. 

For example, with code from Thomas Tumiel, who using a IMPALA-CNN with modified channel [32,64,64] and default PPO TF policy ,  we can get about 60 scores in starpilot environment of procgen benchmark. 
This code is base on TF. When I change it into Pytorch, it only returns about 40 with same settings:

- same IMPALA-CNN model with modified channel [32,64,64]

- same frame stack

- Xavier init for weight, zeros init for bias

- same hyperparameters for default PPO algorithm

- same beta and epsilon value for Adam optimizer ( I modifiy the epsi)

The training curves using tensorboard are as folows:
-mean Return:
![return](https://user-images.githubusercontent.com/20750897/101774425-0d6edf80-3b29-11eb-8f0a-a07a2eb74c9a.png)


-KL divergence:
![kl](https://user-images.githubusercontent.com/20750897/101774451-165fb100-3b29-11eb-92ad-31f4ffefbafb.png)




Atteach files are  clear codes modified from [Thomas Tumie.](https://github.com/ttumiel/procgen-competition).  
For  pytorch, try CUDA_VISEBLE_DEVICE=0,1 ./run_torh.sh --train
for TF, try CUDA_VISEBLE_DEVICE=2,3 ./run_tf.sh --train
Atteach files:[NO8_solution.zip](https://github.com/ray-project/ray/files/5672746/NO8_solution.zip)
