### ISSUE TITLE
Wheel not supported on Mac

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#12501]
### What is the problem?
Can not install Ray wheel on Mac
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray ray-1.1.0.dev0, commit id: 17a6b9bbe7f53c87d4b1afaedf06287ea3a03ba0
Python: 3.8.3
OS: Macos 10.15.6
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
On Mac:
pip install https://ray-wheels.s3-us-west-2.amazonaws.com/master/17a6b9bbe7f53c87d4b1afaedf06287ea3a03ba0/ray-1.1.0.dev0-cp38-cp38m-macosx_10_15_intel.whl

ERROR: ray-1.1.0.dev0-cp38-cp38m-macosx_10_15_intel.whl is not a supported wheel on this platform.
If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
@simon-mo any ideas?

**Comment by simon-mo** [comment]
Can you show the output of `pip debug`?
