### ISSUE TITLE
[Core] GCS based Actor Scheduling discourages actor colocation. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12546]
### What is the problem?

Might be related to https://github.com/ray-project/ray/issues/11239.

Before we enabled GCS-based-actor-scheduling (< 0.8.7), actors were always tried to be scheduled on the same node as the owner if possible (by our worker lease protocol). But after 0.8.7, actor lease requests are just sent to the random node instead of being sent to the node of the owner. This leads actors to be distributed well across the cluster.

This could've introduced unexpected regression in rllib or Tune. If actors are not located in the same node, there will be additional network cost/object transfer cost which could lead to slow down/OOM (especially when our broadcast was not throttled). 

We can resolve the issue by always first trying to schedule actors on the same node as the owner instead of a random node. This should be pretty easy/straightforward fix.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @roireshef

**Comment by rkooo567** [comment]
cc @ffbin Do you have some bandwidth to take care of it?

**Comment by ffbin** [comment]
You can assign it to me. I implemented this in the previous version, but it was lost in the GCS-based-actor-scheduling .

**Comment by rkooo567** [comment]
SGTM. btw, we should probably do this only when there are resource requirements. Otherwise, every actor created by 

```python3
@ray.remote
class Actor:
    pass
```

will have num_cpus=0 meaning every actor will be scheduled on the same node as a creator.

**Comment by ffbin** [comment]
> SGTM. btw, we should probably do this only when there are resource requirements. Otherwise, every actor created by
> 
> ```python
> @ray.remote
> class Actor:
>     pass
> ```
> 
> will have num_cpus=0 meaning every actor will be scheduled on the same node as a creator.

Ok, thanks.

**Comment by rkooo567** [comment]
@ffbin Do you have a plan to work on it soon?

**Comment by ffbin** [comment]
> @ffbin Do you have a plan to work on it soon?

Yeah, i am working on it now. I want to abstract NodeSelector separately, so that PG and actor can reuse a set of interfaces when scheduling and selecting nodes.

**Comment by ffbin** [comment]
@rkooo567

**Comment by rkooo567** [comment]
The inteface LGTM. But this line;
```
ScheduleResourceSets(pending_actors, soft_spread) -> Node list
```
is different from this issue's policy right?

It is soft spread as a fallback currently.

**Comment by ffbin** [comment]
soft_spread is just a sample, it will support spread / pack / strict_ spread/strict_ pack. I will submit a PR this week.

**Comment by ericl** [comment]
If we want to hotfix this into the release branch, the fix should be minimal. Can we do something small (<20 LOC patch) without the refactoring initially?

**Comment by ffbin** [comment]
> @rkooo567 If we want to hotfix this into the release branch, the fix should be minimal. Can we do something small (<50 LOC patch) without the refactoring initially?

@ericl I think i can submit a hotfix PR today.

**Comment by ffbin** [comment]
> > @rkooo567 If we want to hotfix this into the release branch, the fix should be minimal. Can we do something small (<50 LOC patch) without the refactoring initially?
> 
> @ericl I think i can submit a hotfix PR today. cc @rkooo567

**Comment by roireshef** [comment]
@rkooo567 @ffbin @ericl  Hi guys, can anyone of you briefly summarize what was fixed, in what version, and what should we test for? (what should we expect to work at the moment)
