### ISSUE TITLE
[rllib] How to avoid to call the function _initialize_loss_from_dummy_batch

### ISSUE THREAD

**Issue by yangysc** [ray-project/ray#12556]
### How to avoid to call the function _initialize_loss_from_dummy_batch in the file torch_policy_template.py

Hi,
       It seems the torch policy tries to initialize the loss definition from one dummy batch, meaning that the **user-defined model has to deal with inputs with all zeros**. It's fine since CNN/MLP can handle this type of input, but my **agent model is a GNN model (by dgl library), so it cannot deal with null graphs (inputs are all zeros)**. Can I avoid this without the burden of **checking the input is all zeros or not**?   Thanks in advance!

**Comment by yangysc** [comment]
Ok, I think I have to modify the code by dgl, so it can handle empty graphs.

**Comment by Rohan138** [comment]
I'd like to reopen this, if possible. I'm implementing MADDPG in PyTorch, so all elements from my samplebatch are of the form obs_{agent_id}. In general, it seems that the _initialize_loss_from_dummy_batch function is going to cause issues for many implementations or integrations e.g. it passes in np.array for info while my environment returns dicts. Thoughts?
