### ISSUE TITLE
[core] Async API hides RayActorErrors

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12567]
### What is the problem?
* all ray versions
* ray.get() raises an exception if e.g. an actor crashes. If you await the same ObjectRef instead, no exception is raised.

### Reproduction (REQUIRED)
```
import asyncio
import ray

ray.init()

@ray.remote
class SomeActor():
    def ping(self):
        ray.actor.exit_actor()
        return "OK"


async def test():
    try:
        q = SomeActor.remote()
        result = ray.get(q.ping.remote())
    except Exception as e:
        print(f"Good job, ray.get resulted in {e}")

    try:
        q = SomeActor.remote()
        result = await q.ping.remote()
        print(f"Bad job, await didn't raise an exception, but returns {result}")
    except Exception as e:
        print(f"Good job, await resulted in {e}")

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
This results in
```
Good job, ray.get resulted in The actor died unexpectedly before finishing this task.
Bad job, await didn't raise an exception, but returns The actor died unexpectedly before finishing this task.
```
I think `ray.get()` and `await` should have the same behaviour: Raise an exception in case of a RayActorError...
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Hi @PidgeyBE, thanks for raising this issue! This has _just_ been fixed <24 hours ago. Try our nightly wheel? https://github.com/ray-project/ray/commit/ef1b0c13c35391434fdc0ccaa750bd9d30ce24dc

**Comment by PidgeyBE** [comment]
Indeed. Wasnt fixed in wheel yet, but I checked out master and ran from source, and there it worked :+1: 
Thanks!
