### ISSUE TITLE
[tune] register_env checks for FunctionType instead of callable

### ISSUE THREAD

**Issue by timurlenk07** [ray-project/ray#12575]
### What is the problem?
In [registry.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/registry.py#L85) line 85, check is made for **FunctionType**, while in my opinion any **callable** should be accepted, like `functools.partial`.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ubuntu 18
Python 3.8
ray=1.0.1.post1

### Reproduction (REQUIRED)
```python
from functools import partial
import ray
from ray.tune.registry import register_env

def launch_env_from_config(config, extra_config=None):
    pass # create env from config and extra_config here
model = None # Here a pytorch model is loaded
ray.init()

foo = partial(launch_env_from_config, extra_config={'model': model})
register_env('MyEnv', foo)
```
This results in:
```python
TypeError: ('Second argument must be a function.', functools.partial(...))
```

This is somewhere between a feature request and a bug, but as a user I definitly expected `register_env` should work as well with `functools.partial`, as IMO the latter can do all a `FuntionType` can.
I am not really familiar with the codebase so there might be reasons why check for `FunctionType` rather than `callable` is necessary.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@timurlenk07 good catch! Would you be interested in pushing a fix?

**Comment by timurlenk07** [comment]
Sure, will do it :)

**Comment by timurlenk07** [comment]
Can you give me a link to instructions how to run tests? I checked CONTRIBUTING.rst, and run setup_hooks.sh so I think linter will be run this way, but I don't know how to run the unit tests.
