### ISSUE TITLE
[core] run_function_on_all_workers semantics changed

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12599]
### What is the problem?

*1.0.0 vs 1.0.1

### Reproduction (REQUIRED)

The docs indicate that https://github.com/ray-project/ray/blob/6412dfaf383e84e5662cf4bfd3be3927de42e8e1/python/ray/worker.py#L296:
```
        This function will first be run on the driver, and then it will be
        exported to all of the workers to be run. It will also be run on any
        new workers that register later. If ray.init has not been called yet,
        then cache the function and export it later.
```
This hasn't been changed.
However if you have a ray cluster with 1 head and 1 worker and you execute:
```
import ray
ray.init(address="auto")

def test(*args, **kwargs):
    print(
        "Running with run_function_on_all_workers()"
    )
ray.worker.global_worker.run_function_on_all_workers(test)
```
The function will run on both nodes in ray 1.0.0, but only on the driver in ray 1.0.1...
It seems the `run_function_on_all_workers` is only ran when the first task/actor runs on a node.
e.g. doing 
``` 
@ray.remote
def test(*args, **kwargs):
    print(
        "Running with run_function_on_all_workers()"
    )
for node in ray.nodes():
    address = node["NodeManagerAddress"]
    init_worker.options(
        num_cpus=0,
        resources={f"node:{address}": 0.01}
    ).remote()
```
makes sure the `run_function_on_all_workers` is executed on all _current_ ray nodes...

Can the old semantics be restored?

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
@PidgeyBE this is an internal API, we don't provide any guarantees on the behavior of those.

**Comment by PidgeyBE** [comment]
Ok @ericl . We will investigate if we can find a way to eliminate the use of the function (on our side).
