### ISSUE TITLE
[Serve] Passing ObjectRef no longer works.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12593]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
This is a regression from ray 1.0.1.post1

```python
import numpy as np
import requests

import ray
from ray.exceptions import GetTimeoutError
from ray import serve
from ray.test_utils import SignalActor

client = serve.start()

unblock_worker_signal = SignalActor.remote()

def blocked_by_ref(serve_request):
    assert not isinstance(serve_request.data, ray.ObjectRef)

client.create_backend("ref", blocked_by_ref)
client.create_endpoint("ref", backend="ref")
handle = client.get_handle("ref")

# Pass in a ref that's not ready yet
ref = unblock_worker_signal.wait.remote()
worker_result = handle.remote(ref)

# Worker shouldn't execute the request
try:
    ray.get(worker_result, timeout=1)
except:
    pass

# Now unblock the worker
unblock_worker_signal.send.remote()
ray.get(worker_result)
```

On 1.0.1.post1 this passed but on nightly this script will error because we wrap the object ref into the query object, no longer inlining it.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@simon-mo this is fixed, right?
