### ISSUE TITLE
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil'

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#12623]
### What is the problem?

unable to import Ray or run Ray CLI because of psutil errors

- macOS 11.0.1 (20B29)
- Ray commit 0138c2dbb4857f9c716877a5a5f3cd5cd5a9320a
- Python 3.8.6 [Clang 12.0.0 (clang-1200.0.32.28)]

### Reproduction
1. `python3 -m pip install -e .`
2. `python3 -c "import ray"` results in:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../ray/python/ray/__init__.py", line 63, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 98, in init ray._raylet
    import ray.memory_monitor as memory_monitor
  File ".../ray/python/ray/memory_monitor.py", line 9, in <module>
    import psutil  # noqa E402
  File ".../ray/python/ray/thirdparty_files/psutil/__init__.py", line 159, in <module>
    from . import _psosx as _psplatform
  File ".../ray/python/ray/thirdparty_files/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) (.../ray/python/ray/thirdparty_files/psutil/__init__.py)
```

`python3 -c "import ray.memory_monitor"` results in the same error

`python3 -c "import psutil"` results in no errors

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
You can fix it by deleting the `thirdparty_files` directory I think

**Comment by rkooo567** [comment]
Maybe we can add this to our contribution doc?

**Comment by sumanthratna** [comment]
> You can fix it by deleting the `thirdparty_files` directory I think

Thanks!

> Maybe we can add this to our contribution doc?

Definitely. This is what it took for me:
1. `pushd python/ && python3 -m pip install -e . && popd`
2. `rm -rf python/ray/thirdparty_files/`
3. `python3 -m pip install setproctitle`

I'll leave this open for now; I'll try to push a doc-fix PR tomorrow.

**Comment by bveeramani** [comment]
The troubleshooting section should be placed on the [Building Ray from Source](https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray) page instead of the [Installing Ray](https://docs.ray.io/en/latest/ray-overview/installation.html#troubleshooting) page because the error occurs while building Ray from source.

(Ran into this error recently. Only discovered the "Troubleshooting" section after finding this GitHub issue)

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/26166
