### ISSUE TITLE
An imported class behaves differently from a local class

### ISSUE THREAD

**Issue by LinxiFan** [ray-project/ray#12627]
### What is the problem?

For my application, I need to patch the `__init__` method of a class. However, Ray behaves differently for a class defined in the current module VS an imported class. 

### Reproduction (REQUIRED)

Version 1.0.1.post1

For a class defined in the same module, the patched `__init__` works as expected: 

```python
import ray

def patched_init(self):
    print('PATCHED')

class Foo:
    def __init__(self):
        print('UNCHANGED')

Foo.__init__ = patched_init
ray.init()
foo = ray.remote(Foo).remote()  # prints "PATCHED"
```

However, if I move the `Foo` class to another module, the patch is ignored: 

```python
# foo.py
class Foo:
    def __init__(self):
        print('UNCHANGED')
```

main script:
```python
from foo import Foo

def patched_init(self):
    print('PATCHED')

Foo.__init__ = patched_init
ray.init()
foo = ray.remote(Foo).remote()  # WRONG: prints "UNCHANGED"
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Hmm, I think this is an issue with how cloudpickle captures class definitions. 

Instead, would it be possible to just create a subclass of Foo?

**Comment by LinxiFan** [comment]
Thanks Richard! This is an extremely simplified version of what I'm doing, so the patching part is not easily avoidable. Do you have any workaround idea?

**Comment by richardliaw** [comment]
Another possibility is just to pass the function into the constructor of the class, and allow __init__ to be manually overridden by that function.

**Comment by LinxiFan** [comment]
That's a great idea! Thank you so much. Closing this issue as solved.
