### ISSUE TITLE
[tune] Clearer design and architectures of Tune

### ISSUE THREAD

**Issue by GuHongyang** [ray-project/ray#12638]
### Clearer design and architectures of Tune

First of all, thank you for providing such a useful optimization library. 
Although the internal structure is provided in https://docs.ray.io/en/latest/tune/api_docs/internals.html, it is difficult for me to quickly write a custom search algorithm or a custom trial scheduler.  I hope you can show the entire internal mechanism in a flowchart. For example, in TialRunner, how search_alg and scheduler_alg work.

**Comment by richardliaw** [comment]
Great point! Maybe this can help too: 

https://docs.ray.io/en/latest/tune/tutorials/tune-lifecycle.html

**Comment by GuHongyang** [comment]
Thanks!  But I think this is not clear enough, especially in TrialRunner, when defining hooks such as “start”, “end”, and “completed” for “step” and “trial”, an entire flow chart should be given to facilitate development. It can have a clear structure like pytorch-lightning, or a mini_pyro given by pyro.

These are some of my humble opinions, but thank you very much.

**Comment by richardliaw** [comment]
cc @krfricke this could be a good piece of documentation to add (a flowchart showing where Callbacks, Schedulers, and Search Algorithms come in).
