### ISSUE TITLE
API Proposal: @ray.wrapper

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#12633]
## Context

It is well known that applications often times require unserializable services (or mutable state). In order to handle these cases on Ray, we typically recommend that users create Actors which encapsulate these services or objects.

This approach works well when developing new code, but has one major shortcoming when porting existing code over to Ray: When migrating an existing code base, this could require large, or infeasible changes. Many frameworks which utilize dependency injection patterns are prime examples of this (like FastAPI or PyTest). 

## Proposal

Introduce an annotation `@ray.wrapper` which converts an unserializable python class into one that ray can serialize. 

Example: consider a service like the following

```
class UnserializableService:
    def __init__(self):
        self.db_connection = create_connection()

    def do_somthing(self, foo):
         self.db_connection.write(foo)
```

we would expect 

**P0**: Serializability
```
service = UnserializableService()
# This would also be callable via a @ray.wrapper annotation
wrapped_version = ray.wrapper(UnserializableService)() 

assert service.do_something() == wrapped_service.do_something()
assert str(service) == str(wrapped_service)

# This would throw and exception
remote_function.remote(service)

# This would not throw an exception
remote_function.remote(wrapped_version)

# WIth async
@ray.wrapper
class UnserializableService:
    def __init__(self):
        self.db_connection = create_connection()

    async def do_somthing(self, foo):
         self.db_connection.write(foo)
```

**P1**: Integrations (typing and type hints) 
```
assert instanceof(service, BaseService) == True
assert instanceof(wrapped_service, BaseService) == True

@ray.wrapper
class UnserializableService:
    pass

def foo(service : UnserializableService):
    pass
```

**P2**: Tighter python integration (capturing mutable global state).
```
singleton_counter = 0

@ray.wrapper
class GlobalCounter:
    def inc(self):
        global singleton_counter
        singleton_counter += 1
```

### Drawbacks

* Any implementation of this wrapper will most likely result in incurring overhead (a direct actor call and accompanying ray.get).
* It is a little less obvious that these function calls will incur extra overhead (compared to manually implementing it). 

These performance issues should be mitigated by 2 factors though:
1. These service calls are typically, relatively expensive anyways, so the performance overhead may not be siginficant.
2. This is a purely optional annotation. In cases where performance degradation is a concern, it is always possible to fallback to the status quo (more manual implementations).

**Comment by robertnishihara** [comment]
The API seems fully specified, yet I still find myself having trouble understanding it without knowing what it's doing under the hood (this is important at least for knowing what to expect in terms of performance).

Is the idea that `ray.wrapper(UnserializableService)` is basically the same as `ray.remote(UnserializableService)`, that is it creates an actor with an instantiation of the `UnserializableService` class and returns an actor handle, but the syntax for invoking methods on the actor is slightly different (no `.remote` or `ray.get`) so it behaves just like a regular object?

So it makes the thing serializable by putting it behind a layer of indirection?

**Comment by wuisawesome** [comment]
Yeah, I would propose the most straight forward implementation initially. I would definitely be open to a better/more performant implementation that maintains the same semantics (if one exists). 

```
@ray.wrapper
class Foo:
    def synchronous_function(self, x, y):
        pass

    def async_function(self, x, y):
        pass
```

would be equivalent to

```
class FooWrapper:
    def __init__(self):
        self.handle = ray.remote(Foo).remote()

    def synchronous_function(self, x, y):
        return ray.get(self.handle.synchronous_function.remote(x, y))

    def async_function(self, x, y):
        return self.handle.async_function.remote(x, y)
```

The async function is no longer async, but since it returns an object ref, it should still roughly behave the same (i.e. you can `await` it). 

I think the easiest way to achieve this would be via careful use of overriding `__getattr__`.

**Comment by ericl** [comment]
This seems more like a modification of an existing concept (actor decorators) than a new one. Shouldn't it be an option or subtype of actor decorators then, instead of a whole new thing?

**Comment by wuisawesome** [comment]
Yeah, I don't think this introduces any new concepts, but it's a pretty big API/behavior change (I would expect that I can always can `x.remote()` on anything with a `@ray.remote` decorator). 

I don't feel very strongly about this, but would lean towards a different decorator (I suppose something like `@ray.remote(preserve_signature=True)` wouldn't be a super big deal).
