### ISSUE TITLE
[rllib] marwil get_policy_class returns None when framework != torch

### ISSUE THREAD

**Issue by mvindiola1** [ray-project/ray#12632]
### What is the problem?
The get_policy_class method in marwil.py only returns a policy when the framework is torch. If it is any of the tensorflow frameworks it returns None.

This behavior was introduced in the commits for adding the behavior cloning trainer here:
https://github.com/ray-project/ray/commit/4b278c36fcdeda1a519f43104ed881746f3a863b#diff-0430e19a34e6921b0b10841406a117d19a5b292aa99543b56a01bbad5592f29cL45

I searched the closed issues and could not find any issues that mention the tensorflow policy should be removed from marwil's get_policy_class and I checked other agents get_policy_class and they still return tensorflow policies in their get_policy_class methods so I think the else branch was removed in error.

I am happy to prepare a PR if it is warranted. 

I bring this issue up because the change caused a regression in my code when I am trying to update the trainer. I have something like this which no longer works:

```python
def marwil_get_policy_class(config):
    from ray.rllib.agents.marwil.marwil import get_policy_class as marwil_get_policy_class
    return marwil_get_policy_class(config).with_updates(postprocess_fn=postprocess_fn)
``` 

### Reproduction (REQUIRED)
```python
from ray.rllib.agents.marwil.marwil import get_policy_class, DEFAULT_CONFIG
print(get_policy_class(DEFAULT_CONFIG))
DEFAULT_CONFIG["framework"] = "torch"
print(get_policy_class(DEFAULT_CONFIG))
```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this @mvindiola1 ! Taking a look now. ...

**Comment by sven1977** [comment]
I remember we often got the following complaints:
Users trying to set `default_policy` in `build_trainer` to their own custom policy class and then wondering that this class still wouldn't be used by the built Trainer. The reason was b/c `get_policy_class` would still return the TF policy version (given that framework="tf") and the given default was simply ignored. This is why we changed it to the following logic:
If `get_policy_class` returns None, use the `default_class`.

As a workaround, could you simply re-write your function to:
```
def marwil_get_policy_class(config):
    from ray.rllib.agents.marwil.marwil import get_policy_class as marwil_get_policy_class
    from ray.rllib.agents.marwil.marwil_tf_policy import MARWILTFPolicy
    class_ = marwil_get_policy_class(config)
    if class_ is None:
        class_ = MARWILTFPolicy
    return class_.with_updates(postprocess_fn=postprocess_fn)
```

**Comment by mvindiola1** [comment]
@sven1977 Thank you for the suggestion. That is exactly how I handled the error. Following up on your last comment, the main reason I filed the issue was because there are a number of agents that still have the old behavior for get_policy_class. Should those be changed to match or just be left alone?

I just compiled a list from the master branch with the following: 
* Name of the policy
* get_policy_class return value with the DEFULT_CONFIG settings
* the default policy defined in build trainer

### Agents following the current pattern
|Agent | get_policy_class | default_policy | notes |
|---|---|---|---|
|dqn/simple_q | None | SimpleQTorchPolicy |
|dqn/DQNTrainer | None | DQNTFPolicy |
|marwil | None | MARWILTFPolicy|
|pg | None | PGTFPolicy |
|ppo/appo | None | AsyncPPOTFPolicy |
|ppo/ppo | None | PPOTFPolicy | 
sac| None | SACTFPolicy |

### Agents following the old pattern
|Agent | get_policy_class | default_policy | notes |
|---|---|---|---|
|ddpg | DDPGTFPolicy | DDPGTFPolicy
|a2c| A3CTFPolicy | A3CTFPolicy |
|a3c| A3CTFPolicy | A3CTFPolicy |
|maml | MAMLTFPolicy | MAMLTFPolicy |
|impala | VTraceTFPolicy | VTraceTFPolicy, | this one would be tricky to change to return a None becuse there are two levels of conditionals
|dreamer | DreamerTorchPolicy | DreamerTorchPolicy| this one could follow mbmpo and not_define get_policy_class

### Agents doing something different
|Agent | get_policy_class | default_policy | notes |
|---|---|---|---|
|ars | ARSTFPolicy | N/A | does not use build_trainer
|es | ESTFPolicy | N/A | does not use build_trainer
|slateq | SlateQTorchPolicy | None |  this one could be changed to match the current approach
|mbmpo | N/A | MBMPOTorchPolicy | get_policy_class not defined
|dqn/GenericOffPolicyAlgorithm | None | None |
