### ISSUE TITLE
[tune] Compatibility error with pytorch lightning1.0 's Callbacks

### ISSUE THREAD

**Issue by huhubrave** [ray-project/ray#12645]
### What is the problem?
Running[ the example](https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-lightning.html#tune-pytorch-lightning) in the link causes an error.  **TypeError: on_validation_batch_end() takes 6 positional arguments but 7 were given**
When "TuneReportCallback"  is added to pytorch lightning‘s callbacks.

*Ray version and other system information (Python version, TensorFlow version, OS):*

ray v1.1.0.dev0
pytorch-lightning 1.0.3

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-lightning.html#tune-pytorch-lightning

**Comment by amogkam** [comment]
Hi @huhubrave do you have the full stack trace that you are seeing? I'm not able to reproduce this on PTL v1.0.3.

**Comment by sumanthratna** [comment]
(linking PR #11375, https://github.com/ray-project/ray/pull/11375/files#diff-dd7410063c0dffe287cb4eb207a0b1810ba3d934182f9d2b79fa2285a2248112L79-R82, discussion #11859)

**Comment by richardliaw** [comment]
Looks like this might be already fixed.
