### ISSUE TITLE
Argument with shared variables

### ISSUE THREAD

**Issue by LinxiFan** [ray-project/ray#12640]
### What is the problem?

I observe unintuitive behavior if the arguments passed to a remote function contain shared data. It is corrected if I directly apply `cloudpickle`.

Ray v1.0.1.post1, python 3.7, Ubuntu 18.04

### Reproduction (REQUIRED)

```python
import cloudpickle
import ray
ray.init()


@ray.remote
def f1(c):
    c['x'][0] = 100
    print('f1', c)


@ray.remote
def f2(c):
    c = cloudpickle.loads(c)
    c['x'][0] = 100
    print('f2', c)


shared = [1, 2, 3]
c = {'x': shared, 'y': shared}

f1.remote(c)
f2.remote(cloudpickle.dumps(c))
```

Printed results:
```
f1 {'x': [100, 2, 3], 'y': [1, 2, 3]}  # not shared anymore
f2 {'x': [100, 2, 3], 'y': [100, 2, 3]}  # desired behavior
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by suquark** [comment]
I can further confirm it is not related to cloudpickle or pickle protocol 5 used by ray:

```python
from ray import cloudpickle
a = [0]
b=[a,a]
s = []
d = cloudpickle.loads(cloudpickle.dumps(b, protocol=5, buffer_callback=s.append), buffers=s)
assert d[0] is d[1]   # pass

ray.init()
d = ray.get(ray.put(b))
assert d[0] is d[1]  # fail
```

**Comment by ericl** [comment]
This is expected behavior, please see https://docs.google.com/document/d/167rnnDFIVRhHhK4mznEIemOtj63IOhtIPvSYaPgI4Fg/edit for workarounds ("Accessing global variables"
