### ISSUE TITLE
[k8s] [autoscaler] Helm chart for deploying Ray on Kubernetes 

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#12654]
### Describe your feature request
This is a commonly requested feature, and it's on our to-do list.

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by Gekho457** [comment]
We're currently finishing up an initial release of a new Kubernetes operator for deploying Ray clusters.
(See https://github.com/ray-project/ray/pull/12098)

I think once we're done with that, we can go ahead and package the operator and associated resources as a helm chart.

**Comment by salqadri** [comment]
Any ETA on this?
