### ISSUE TITLE
[doc] Add info about single core/multi core in opencv

### ISSUE THREAD

**Issue by TanjaBayer** [ray-project/ray#12651]
In the docs you have a section about parallelism with Ray (https://docs.ray.io/en/master/serve/advanced.html?highlight=omp#configuring-parallelism-with-omp-num-threads), also there is a information about that here: https://docs.ray.io/en/master/configure.html?highlight=OMP_NUM_THREADS#cluster-resources.

Due to this infos in the docs I was quite astonished that my workers where using more than 100% cpu. I found out that opencv is not using the `OMP_NUM_THREADS` variable, it has it's own version of it. To disable parallisation use:

``` python
 cv2.setNumThreads(0)
```
You can check the number of cpus and threads with this:

``` python
logger.debug(f'threads: {cv2.getNumThreads()}, cpus: {cv2.getNumberOfCPUs()}')
```

See opencv docs [here](https://docs.opencv.org/master/db/de0/group__core__utils.html#gae78625c3c2aa9e0b83ed31b73c6549c0)

I know this is not an issue from ray, but I assume there might be more people using opencv along side ray, so it would be nice if you could add a hint somewhere in the docs, that might save someone else the time I needed to find this one out :smile:

**Comment by edoakes** [comment]
Thanks for reporting @TanjaBayer. This can be quite confusing & hard to debug. Made a PR that documents this case to help others in the future :)
