### ISSUE TITLE
[tune] OverflowError: cannot serialize a bytes object larger than 4 GiB in pickle_checkpoint

### ISSUE THREAD

**Issue by FarzanT** [ray-project/ray#12650]
### What is the problem?
Ray[tune] PBT is unable to save trials where the model is larger than 4GB, resulting in the following error stack:
```
Failure # 1 (occurred at 2020-12-07_10-50-59)
Traceback (most recent call last):
  File "/u/ftaj/anaconda3/envs/drp/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 348, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "/u/ftaj/anaconda3/envs/drp/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 289, in _start_trial
    self.restore(trial, checkpoint)
  File "/u/ftaj/anaconda3/envs/drp/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 733, in restore
    obj = TrainableUtil.checkpoint_to_object(value)
  File "/u/ftaj/anaconda3/envs/drp/lib/python3.7/site-packages/ray/tune/trainable.py", line 86, in checkpoint_to_object
    data_dict = TrainableUtil.pickle_checkpoint(checkpoint_path)
  File "/u/ftaj/anaconda3/envs/drp/lib/python3.7/site-packages/ray/tune/trainable.py", line 80, in pickle_checkpoint
    "data": data,
OverflowError: cannot serialize a bytes object larger than 4 GiB
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.7.3
Pytorch 1.7
Ubuntu 18 LTS
Ray Version: 1.0.1.post1 (unable to run on the nightly build as it results in other irrelevan errors)

### Reproduction (REQUIRED)
Any model + weights whose size is larger than 4GB

### Possible solution
Use `protocol=4` in pickle to serialize objects larger than 4GB.

**Comment by ericl** [comment]
@richardliaw

**Comment by FarzanT** [comment]
@richardliaw Any reason why we can't provide our own checkpoint saving function? Like using the `torch.save` and `torch.load` from Pytorch. I'm sure there wouldn't be any model saving/loading issues there.
I actually added `protocol=4` to `pickle_checkpoint` and that fixed the checkpoint saving part, but now I get a `MemoryError` in `f.read()` part of `pickle_checkpoint`.

**Comment by richardliaw** [comment]
I think we can fix this by replacing pickle with `ray.cloudpickle`

**Comment by FarzanT** [comment]
@richardliaw Is there anything else that I can do? I've never submitted a pull request, but want to fix this issue as it's disallowing me to optimize larger models.

**Comment by richardliaw** [comment]
Thanks for the ping! Hmm can you try changing the one line “import pickle”
to “import ray.cloudpickle as pickle” and see if that works?

You may need to do this on all nodes of your cluster if you have multiple.

**Comment by FarzanT** [comment]
@richardliaw Yes it did! Thank you!

**Comment by richardliaw** [comment]
Very cool! sorry for the the slow reply... been a bit busy these days. Do you want to push a pull-request? If you're busy I can do it quickly so that it gets fixed in later ray releases.

**Comment by richardliaw** [comment]
(But it'd be awesome for you to do it :) )

**Comment by FarzanT** [comment]
No problem at all, I understand how busy you are! I'll give it a try, have to do a bit of research on how to do this properly.

**Comment by FarzanT** [comment]
@richardliaw Hey, I just made the changes but don't know how to assign you.
