### ISSUE TITLE
Clarify versioning requirements for Ray Client

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12676]
Do I need to have the same Python version locally as is running on the cluster? Do I need to have the same Ray version?

Seems like we could potentially be somewhat lax here if we define the gRPC interface well.

**Comment by barakmich** [comment]
That's correct, some drift is allowable. One need not have the same version locally as on the cluster. The difference being that they may not have the 'latest and greatest' features but assuming we're good about making backwards compatible proto changes when we go beta/GA with the feature, then we should be set. 

If we wanted to get fancy, the first feature in our protocol negotiation could be version. But that's not on this MVP list, so I'm marking this P3

**Comment by edoakes** [comment]
Sounds good, let's make sure it's P0 that this is clear in the docs :)
