### ISSUE TITLE
[rllib] MultiAgentBatch object has no attribute 'total'

### ISSUE THREAD

**Issue by alexenos** [ray-project/ray#12678]
### What is the problem?
When trying to train with an ExternalEnv MultiAgent environment through the PolicyServerInput/PolicyClient interface. The following error occurs:

```
Traceback (most recent call last):
  File "/home/dgarner/.local/share/virtualenvs/ray_bug-QUDZwH1p/lib/python3.6/site-packages/ray/rllib/env/policy_client.py", line 272, in run
    "server.".format(samples.count, samples.total()))
AttributeError: 'MultiAgentBatch' object has no attribute 'total'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
python==3.6.9
ray==1.0.1.post1
tensorflow==2.3.1
OS: Ubuntu 18.04 LTS

### Reproduction (REQUIRED)
Based on the `unity3d_[server|client].py` example, the following scripts will reproduce the error. Run the server script with no arguments, and then the client script with no arguments in another terminal.

```
python bug_server.py
python bug_client.py
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by alexenos** [comment]
Here are the scripts with a `.txt` extension

[bug_client.txt](https://github.com/ray-project/ray/files/5661172/bug_client.txt)
[bug_server.txt](https://github.com/ray-project/ray/files/5661173/bug_server.txt)

**Comment by ericl** [comment]
Looks like it was using a deprecated method .total instead of .agent_steps(). Do you mind submitting a fix?

**Comment by alexenos** [comment]
I dont mind at all!

**Comment by sven1977** [comment]
Thanks for raising this @alexenos ! This PR fixes the issue:
https://github.com/ray-project/ray/pull/12704
Closing this. Feel free to re-open should the fix not work for you.
