### ISSUE TITLE
[Core] ability to set the hard limit for the number of workers

### ISSUE THREAD

**Issue by jennicetao** [ray-project/ray#12683]
`[2020-12-08 21:07:51,676 I 20313 20313] worker_pool.cc:746: The worker pool has 51 registered workers which exceeds the soft limit of 48, and worker 362535858062b8599b72fa433da90d45df6cb739 with pid 2138 has been idle for a a while. Kill it.`

This very frequently happens with my job where many same tasks run with some time gaps between each run. It's time consuming for my tasks to reload in a new process. I would like to rather set the hard limit and not kill the processes; this is supposed to be controlled by max_calls parameter in remote function.

**Comment by ericl** [comment]
Can you provide a reproduction case? Is this with multiple different jobs on the same cluster?

**Comment by rkooo567** [comment]
@jennicetao Can you try in the latest master if you are seeing the same issue? Also, it'd be great if you can provide a reproduction script.

**Comment by rkooo567** [comment]
Hey @jennicetao This issue might be resolved by https://github.com/ray-project/ray/pull/14202
