### ISSUE TITLE
[Core] More elegant mechanism to borrow CPUs for workers

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12686]
### What is the problem?

Currently, when the worker's main thread is blocked by Ray's blocking call, we are running a mechanism called borrowing cpus. The idea is basically that when the task is blocked, we release the cpu of that worker until it is unblocked to avoid deadlocking. 

The current mechanism is not really great and easily can lead to starting 100s of workers. For example, try running the below script which has lots of object dependencies and calls ray.get frequently. 

There are 2 high level solutions here; 
- Allow users to disable borrowing cpus. (low level for users)
- Implement a better mechanism that is more robust

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

https://gist.github.com/ericl/d419c6373928b4b7c8739738262da287

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by clarkzinzow** [comment]
@rkooo567 This is still an issue, right?

**Comment by rkooo567** [comment]
I think we have a pretty good workaround now, so we can just close it
