### ISSUE TITLE
Maximum number of file descriptors for redis connections exceeded at runtime

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1269]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: wheels from f7c4f41df80b5b0b57068138e87c728ee609e392
- **Python version**: 3.6.3

### Describe the problem

Start a cluster on 10 m4.4xlarge as described here: http://ray.readthedocs.io/en/latest/using-ray-on-a-large-cluster.html

After the cluster is started, we can connect drivers and submit tasks. However, after running the following program:

```python
@ray.remote
def f(x):
  i = 1
  return i

@ray.remote
def g(x):
  results = [f.remote(x) for i in range(20)]
  return sum(ray.get(results))

u = ray.put("hello")
results = [g.remote(u) for i in range(10000)]
%time print("sum is", sum(ray.get(results)))
```

Trying to connect a new driver fails with
```
Exception in thread Thread-103:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 301, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached
```

**Comment by pcmoritz** [comment]
This might be because ray will start more workers on client nodes and therefore the max number of redis client connections is eventually exceeded. A possible fix is to get rid of redis clients in workers.

**Comment by robertnishihara** [comment]
As a workaround (this will only increase the maximum number of redis clients to a point..), before starting the head node, you can do `ulimit -n 65536` followed by `ray start --head --max-redis-clients=65504`.

**Comment by robertnishihara** [comment]
It is no longer necessary to do `--redis-max-clients=65504`. You just have to make sure to raise the `ulimit -n` before starting Ray.
