### ISSUE TITLE
Custom Serializer Guide

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#12719]
### Describe your feature request
https://docs.ray.io/en/latest/serialization.html?highlight=serialize
The doc page removed the mention of custom_serializer. Can we add a simple guide for the best practices for implement the custom `__reduce__` function?

cc @richardliaw @suquark 
For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by richardliaw** [comment]
Note that this is blocking people from porting from 0.8 to 1.x.

(`register_custom_serializer` was removed)

**Comment by simon-mo** [comment]
Here's a quick code sample
```
import ray
import sqlite3

ray.init()


class DBConnection:
    def __init__(self, path):
        self.path = path
        self.conn = sqlite3.connect(path)

    def __reduce__(self):
        deserializer = DBConnection
        serialized_data = (self.path,)
        return deserializer, serialized_data

original = DBConnection("/tmp/db")
print(original.conn)

copied = ray.get(ray.put(original))
print(copied.conn)
```

**Comment by rkooo567** [comment]
Btw, just out of curiosity, but why do we suggest reduce instead of custom serializer? 

Isn't reduce harder to use when the object you'd like to serialize is, for example, from other libraries since you need to add the method to the classes that are not under your control? (whereas it is easier in the custom serializer if I understand how it works correctly)

**Comment by simon-mo** [comment]
Correct. That's why for PyTorch Tensor @suquark introduced serialization_addons. Maybe we can make that a public API?

**Comment by richardliaw** [comment]
@ericl what's the recommendation for working around the custom serializer, which was removed in 1.0?

**Comment by ericl** [comment]
Define __reduce__ (standard pickle5 custom serialization).

**Comment by suquark** [comment]
How about some third-party objects that users cannot define `__reduce__` in the original object? One case is pytorch tensor (the default `__reduce__` is of low efficiency; another one is the pydantic metadata)

**Comment by ericl** [comment]
Can you wrap the tensor in another class and define a serializer for that?

**Comment by suquark** [comment]
No, because we are going to change all pytorch tensors used in the application without changing user's code. For example, this issue: https://github.com/ray-project/ray/issues/12317

**Comment by suquark** [comment]
@ericl any thoughts?

**Comment by pcmoritz** [comment]
For posterity: Unfortunately, just overriding the `__reduce__` method gives an error:
```
In [1]: import torch

In [2]: torch.FloatTensor.__reduce__
Out[2]: <method '__reduce__' of 'object' objects>

In [3]: torch.FloatTensor.__reduce__ = lambda self: (None, None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-cbecd3267b43> in <module>
----> 1 torch.FloatTensor.__reduce__ = lambda self: (None, None)

TypeError: can't set attributes of built-in/extension type 'torch.FloatTensor'
```

While there is a way to do it anyways (https://pypi.org/project/forbiddenfruit/), it is not portable and doesn't look very well supported.
