### ISSUE TITLE
[rllib] compute_action broken since Version 1.0.1

### ISSUE THREAD

**Issue by afaul** [ray-project/ray#12713]
### What is the problem?
I'm using the compute_action function of Trainers to evaluate the trained agents.
Since Version 1.0.1 the compute_action function, at least of the PPOTrainer, don't accepts Dict-based observation spaces as parameter.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.7.7
TensorFlow 2.2.0
OS: Windows

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import gym
import numpy as np
import ray.rllib.agents.ppo as ppo
import ray

class Env_class(gym.Env):
    def __init__(self, config):
        self.observation_space = gym.spaces.Dict({
            "a": gym.spaces.Box(low=np.NINF, high=np.inf, shape=(1,)),
            "b": gym.spaces.Box(low=0, high=np.inf, shape=(1,)),
            "c": gym.spaces.Box(low=0, high=np.inf, shape=(1,)),
            "d": gym.spaces.Box(low=0, high=np.inf, shape=(1,)),
        })
        self.action_space = gym.spaces.Discrete(51)
        self.stepcount = 0

    def reset(self):
        self.stepcount = 0
        observation = {"a": [-10], "b": [10], "c": [5], "d": [15]}
        return observation

    def step(self, action):
        observation = {"a": [-20], "b": [20], "c": [15], "d": [25] }
        reward = 5
        if self.stepcount > 5:
            episode_ended = True
        else:
            episode_ended = False
        additional_information = {}
        self.stepcount += 1
        return observation, reward, episode_ended, additional_information

env_config = {}
# instantiate env class
env = Env_class(env_config)

ray.init()
config = ppo.DEFAULT_CONFIG.copy()
agent = ppo.PPOTrainer(config=config, env=Env_class)

# run until episode ends
episode_reward = 0
done = False
obs = env.reset()
while not done:
    action = agent.compute_action(obs)
    print(f"action: {action}")
    obs, reward, done, info = env.step(action)
    episode_reward += reward

```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this @afaul ! 
I think this is the same issue as this one here, which is fixed now:
https://github.com/ray-project/ray/issues/12516

**Comment by sven1977** [comment]
Closing this due to being a duplicate.
