### ISSUE TITLE
[New Scheduler] Make `AsyncResolveObjects` and `AsyncResolveObjectsFinish` compatible to the new scheduler

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12725]
### What is the problem?

Not sure @wuisawesome and I have the same problem scenario, but it seems like without handling the code block below with the new scheduler, we can have subtle race condition issues in non-unit-test environment.

Sang Cho  2 minutes ago
Hmm it seemms like this block looks relevant though?
```cpp
    if (mark_worker_blocked && !worker->IsBlocked() &&
        current_task_id == worker->GetAssignedTaskId()) {
      Task task;
      RAY_CHECK(local_queues_.RemoveTask(current_task_id, &task));
      local_queues_.QueueTasks({task}, TaskState::RUNNING);
      // Get the CPU resources required by the running task.
      // Release the CPU resources.
      auto const cpu_resource_ids = worker->ReleaseTaskCpuResources();
      local_available_resources_.Release(cpu_resource_ids);
      cluster_resource_map_[self_node_id_].Release(cpu_resource_ids.ToResourceSet());
      worker->MarkBlocked();
      // Try dispatching tasks since we may have released some resources.
      DispatchTasks(local_queues_.GetReadyTasksByClass());
    }
```

Sang Cho  1 minute ago
If this method is called before DirectCallBlocked (because grpc doesn’t guarantee ordering), I guess it can cause some problems?

Alex Wu  1 minute ago
oh that’s a good point, i guess we should insert a ScheduleAndDispatch() in there

Alex Wu  1 minute ago
yeah can you make an issue? it should be easy to fix (though it sounds like we don’t have a reproduction for it)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
@stephanie-wang can you sanity check us here? This seems reasonable, but it's a little strange that we don't fail any tests because of this.

**Comment by ericl** [comment]
> If this method is called before DirectCallBlocked (because grpc doesn’t guarantee ordering), I guess it can cause some problems?

We have other code that handles re-ordered messages though. What is the scenario that is of concern here?

**Comment by rkooo567** [comment]
My concern here is that the code seems to be very similar to `HandleDirectCallTaskBlocked`, and I thought the reason was to handle some subtle edge cases or other possible cases that can happen around handling blocking tasks.

**Comment by rkooo567** [comment]
Another concern is our unit tests are not perfect, and since node manager didn't have unit tests, some of code that was written to handle some edge cases could have been ignored when developing the new scheduler, and they were discovered by non-reproducible issues. So, I thought it'd make sense to match the previous behavior as much as possible if we are not certain that this is not needed.

**Comment by ericl** [comment]
Ok. Until we are certain this is a real issue, let's close it. We shouldn't be making speculative fixes unless we are sure about the problem. Most likely this isn't needed in the direct call path.
