### ISSUE TITLE
[New Scheduler] Provide infeasible tasks / pending tasks information to the dashboard.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#12737]
### What is the problem?

cc @mfitton Do we have a dashboard test to check this? 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@rkooo567 I'm confused -- is this an existing bug or a required feature for enabling the new scheduler?

**Comment by rkooo567** [comment]
Ah, it is a required feature (new scheduler doesn’t report the infeasible & pending tasks)

**Comment by mfitton** [comment]
It's in the test here: https://github.com/ray-project/ray/blob/master/dashboard/modules/logical_view/tests/test_logical_view_head.py#L18

**Comment by ericl** [comment]
@mfitton do you know where this information coming from? I'm having a hard time finding out where the dashboard is getting this data from.

**Comment by ericl** [comment]
I see, it was introduced in 1e690673d8bd5f2204ad49a78cc93d29cf9e4d12
