### ISSUE TITLE
[serve] Memory growth related to redis

### ISSUE THREAD

**Issue by ppdollhhh** [ray-project/ray#12739]
Problem:
In my project, I use ray[serve] to do model inference.

When I did jmeter test(function is ok), memory has been consistent growth slowly.  

I use command top to debug this problem,  the memory size of redis-server process is growing  steadily. 

When ray start, two redis-server will start together. One of the two redis-server is the root cause of this problem, whose port is random(the normal one is 6379).

Any one can help sovle this problem?

thx!!!

Information:
ray:1.0.0 or 1.0.1post
system: ubuntu16.04
python:3.6.9

start commond:  ray start --head --dashboard-host 0.0.0.0 --dashboard-port 8265

ray_server.py code:

import ray 
from ray import serve
from AlgWorker.algWorker import FaceDetect

class Config_Backend:
    def __init__(self, num_gpus, num_replicas, max_batch_size):
        self.ray_actor_options = {"num_gpus": num_gpus}
        self.config = {"num_replicas": num_replicas,
                       "max_batch_size": max_batch_size}

config_FaceDetect = Config_Backend(0.25, 8, 10) 
ray.init(address='localhost:6379')
client = serve.start(http_host="0.0.0.0", detached=True)
client.create_backend("FaceDetect_retina", FaceDetect,
                      ray_actor_options=config_FaceDetect.ray_actor_options, config=config_FaceDetect.config)
client.create_endpoint("FaceDetect", backend="FaceDetect_retina", route="/faceDetect")

algWorker.py
from ray import serve
import ray

class FaceDetect:
    def __init__(self):
        self.modelDet = RetinaFaceTensorRT()   #init tensorRT model
      
    @serve.accept_batch
    def __call__(self, flask_requests):
        responses = []
        for flask_request in flask_requests:
                do something.......
                response.append(result)
            responses.append(response)
        return responses

**Comment by simon-mo** [comment]
Hi @ppdollhhh, thanks for raising this issue. Can you try installing the latest ray master? https://docs.ray.io/en/latest/installation.html#latest-snapshots-nightlies

This issue should be fixed in master as part of #12395. However, it's weird that redis memory was the issue. can you post a screenshot of your system's memory monitor (htop or Activity Monitor) before and after?
