### ISSUE TITLE
Permission/Accessibility Connecting to Redis using Ray on Apple Silicon (ARM)

### ISSUE THREAD

**Issue by sonny3690** [ray-project/ray#12742]
### What is the problem?
Initing ray leads to issues connecting to redis.

*Ray version and other system information (Python version, TensorFlow version, OS):*
- OS: Apple Big Sur 11.0.1
- Python: 3.8.6
- Running on 13-inch Apple M1

### Reproduction (REQUIRED)

Apriori checked that redis-cli is working:

```
(python-parser) smo@Sonnys-MacBook-Pro-2 python-parser % redis-cli
127.0.0.1:6379>
```

But initing ray on the REPL leads to the following:

```sh
Python 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/worker.py", line 696, in init
    _global_node = ray.node.Node(
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/node.py", line 198, in __init__
    self.start_head_processes()
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/node.py", line 800, in start_head_processes
    self.start_redis()
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/node.py", line 568, in start_redis
    process_infos) = ray.services.start_redis(
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/services.py", line 739, in start_redis
    port, p = _start_redis_instance(
  File "/Users/smo/.local/share/virtualenvs/python-parser-PPVORIu3/lib/python3.8/site-packages/ray/services.py", line 927, in _start_redis_instance
    raise RuntimeError("Couldn't start Redis. "
RuntimeError: Couldn't start Redis. Check log files: /tmp/ray/session_2020-12-10_01-59-32_010274_33542/logs/redis.out /tmp/ray/session_2020-12-10_01-59-32_010274_33542/logs/redis.err
>>>
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
The wheel was built for intel and probably not compatible with apple silicon. We also used some executable what might not work well with Rosettta2 translation. Can you try building Ray from source? https://docs.ray.io/en/latest/development.html#building-ray-full

**Comment by ramicaza** [comment]
I found that the version of redis that ray ships with doesn't like m1 Macs as per [this issue ](https://github.com/redis/redis/issues/8062). The fix is clear: ray needs to update the redis version that's shipped.  But for now a hacky workaround is to symlink your redis-server executable (which starts correctly) to <wherever your python packages are installed>/ray/core/src/ray/thirdparty/redis/src/redis-server

**Comment by djoull** [comment]
Hi,

Both solutions (building Ray from source & symlink an up-to-date Redis-server executable) don't work for me.

Would you have an ETA for this fix ?

**Comment by AlexanderKoch-Koch** [comment]
On my M1 Mac it works with sudo. However, it still fails to import rllib.
And I am using a Terminal with Rosetta 2.

~$ sudo python3
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2021-01-27 13:02:59,865	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8266
{'node_ip_address': '192.168.178.30', 'raylet_ip_address': '192.168.178.30', 'redis_address': '192.168.178.30:17263', 'object_store_address': '/tmp/ray/session_2021-01-27_13-02-59_265625_87586/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-01-27_13-02-59_265625_87586/sockets/raylet', 'webui_url': '127.0.0.1:8266', 'session_dir': '/tmp/ray/session_2021-01-27_13-02-59_265625_87586', 'metrics_export_port': 63523, 'node_id': '22d9f74bafb316a074fab72fc706bb6c1ccb07e8'}
>>> import ray.rllib
Illegal instruction: 4

**Comment by djoull** [comment]
I finally got Ray to work on my M1 Mac with sudo.

Not sure what I did, but :  
- I had to install JDK 11 for arm (.dmg) from https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk.
- Then built Bazel from source
- Then built Ray from source (version 2.0.0(dev0)) https://docs.ray.io/en/latest/development.html#building-ray-full (without the bazel install step)

The only thing that doesn't work properly is the dashboard, that doesn't show proper CPU usage for individual workers.

**Comment by iamhatesz** [comment]
@djoull 

> I finally got Ray to work on my M1 Mac with sudo.
> 
> Not sure what I did, but :
> 
> * I had to install JDK 11 for arm (.dmg) from https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk.
> * Then built Bazel from source
> * Then built Ray from source (version 2.0.0(dev0)) https://docs.ray.io/en/latest/development.html#building-ray-full (without the bazel install step)
> 
> The only thing that doesn't work properly is the dashboard, that doesn't show proper CPU usage for individual workers.

Hey, could you please provide more details on your successful compilation of Ray? I did as you suggested but I keep receiving Bazel errors:

On version 3.2.0:

>     ERROR: /private/var/tmp/_bazel_tomaszwrona/74e0e82bb2f4d8ef2fc160911776661a/external/boost/BUILD.bazel:1760:14: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).

On latest version 4.0.0:

>     ERROR: /private/var/tmp/_bazel_tomaszwrona/74e0e82bb2f4d8ef2fc160911776661a/external/com_google_protobuf/BUILD:873:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.

**Comment by ramicaza** [comment]
@djoull could you potentially post a whl file for your build (I know this is a tall order so completely understand if you can't).  

Also, could we know if the maintainers are making an effort to support apple silicon natively?  The hack I mentioned earlier in this thread works but it runs everything through rosetta 2 and it's sad knowing that my programs utilizing ray are running around 1.5-2x slower because of they aren't running natively.
