### ISSUE TITLE
[ray] The results of ray.cluster_resources() is not right.

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#12744]
### What is the problem?

ray version: 1.0.1.post1
python version: 3.6.5
OS: CentOS 7

The results of `ray.cluster_resources()` is not right.

`ray.cluster_resources()`:
![image](https://user-images.githubusercontent.com/1471864/101742127-60cf3680-3b05-11eb-8567-c5d7c94c41c8.png)

`Resoures in Dashboard`:
![image](https://user-images.githubusercontent.com/1471864/101742779-88260380-3b05-11eb-9436-0ff790f5d46b.png)

I'm not try ray-nightly version, if it's fixed, please let me know. Thx a lot!

BRs!

**Comment by rkooo567** [comment]
Currently, the units that are specified by cluster_resources are different from GB because of some legacy scheduler code. We are currently developing the new scheduler now, and this issue will be resolved once that's completed.

**Comment by DonYum** [comment]
@rkooo567 Thanks for your reply. What's the roadmap of the new scheduler? Will it be included in the next release?

**Comment by rkooo567** [comment]
The eta is eoy, so it will be likely to be included in jan or feb release
