### ISSUE TITLE
RayTaskError(ImportError)

### ISSUE THREAD

**Issue by jac-z-uk** [ray-project/ray#12755]
Hi, I upgraded pettingzoo and ray and get this error: 

"line 1452, in get
    raise value.as_instanceof_cause()

RayTaskError(ImportError)"

The old and new versions are as follows:
pettingzoo: 1.3.5 to 1.4.2
ray: 1.0.0 to 1.1.0.dev0
(I use the same version of gym 0.17.3 in both runs.)

The script runs fine on the old versions but I get the error with the new versions:

The script for the new version which produces the bug is:

```python
from copy import deepcopy
from numpy import float32
import os
from pettingzoo.sisl import multiwalker_v5

import ray
from ray.rllib.agents.registry import get_agent_class
from ray.rllib.env import PettingZooEnv
from ray.tune.registry import register_env

def env_creator(config):
    env = multiwalker_v5.env(n_walkers=config.get("n_walkers",3))    
    env.reset()
    env = PettingZooEnv(env)
    return env

alg_name = "PPO"

config = deepcopy(get_agent_class(alg_name)._default_config)
register_env('multiwalker', lambda config: env_creator(config))

test_env = env_creator({})
obs_space = test_env.observation_space
act_space = test_env.action_space

config["multiagent"] = {
    "policies": {
        "av": (None, obs_space, act_space, {}),
    },
    "policy_mapping_fn": lambda agent_id: "av"
}

config["num_gpus"] = int(os.environ.get("RLLIB_NUM_GPUS", "0"))
config["log_level"] = "DEBUG"
config["num_workers"] = 1
config["rollout_fragment_length"] = 30
config["train_batch_size"] = 200
config["horizon"] = 200
config["no_done_at_end"] = False

#####################
ray.init()

trainer = get_agent_class(alg_name)(env="multiwalker", config=config)
trainer.train()
test_env.reset()

ray.shutdown()
```
                                                              

Confirming:
- [Yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [Yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
This works for me fine, can you post a stacktrace?

I had to install Box2D though

**Comment by jac-z-uk** [comment]
Thank you for looking into this!  I have Box2D (2.3.8).  Also I forgot to mention I'm on macOS.  Please see below the stacktrace:

Traceback (most recent call last):

  File "/Users/jz/Dropbox/Python/2020/Dec2020_Multiwalker_ray.py", line 145, in <module>
    trainer = get_agent_class(alg_name)(env="multiwalker", config=config)

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 107, in __init__
    Trainer.__init__(self, config, env, logger_creator)

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 480, in __init__
    super().__init__(config, logger_creator)

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 644, in setup
    self._init(self.config, self.env_creator)

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 139, in _init
    num_workers=self.config["num_workers"])

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 721, in _make_workers
    logdir=self.logdir)

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 81, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))

  File "/Users/jz/opt/anaconda3/envs/ray_1/lib/python3.7/site-packages/ray/worker.py", line 1373, in get
    raise value.as_instanceof_cause()

RayTaskError(ImportError)

**Comment by richardliaw** [comment]
Hmm, is there an even longer stack trace? Like is there a message beyond
the import error? Or perhaps before?

**Comment by jac-z-uk** [comment]
No, that's the full stack trace.  I created a new env and installed all and again get the same exact error message.

**Comment by richardliaw** [comment]
Hmmmm, can you take a look at the logs in `/tmp/ray/session_latest/logs/worker*`? Do you see anything interesting there (or maybe post all the worker logs?)

**Comment by jac-z-uk** [comment]
I checked all the worker files and no useful information there.  They all show : "Ray worker pid: xxxxx".  xxxxx is a different number in each worker file.

**Comment by richardliaw** [comment]
Ah, can you try updating to 1.2.0.dev0 too? Sorry, that is the latest version of Ray.

**Comment by jac-z-uk** [comment]
Ok thanks, I upgraded to 1.2.0.dev0 now, unfortunately I get the exact same error again.

**Comment by gefei456** [comment]
@ingo-ch Did you had solved this problem ? I met the same one.
