### ISSUE TITLE
[ray][metrics] Displaying metrics about Ray cluster on Datadog

### ISSUE THREAD

**Issue by salman1993** [ray-project/ray#12761]
### Describe your feature request
- Want to be able to look at Ray metrics from a Datadog dashboard
- Metrics include: queue size, memory/CPU/GPU utilization, etc. 

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
Thanks for the feature request! We are collecting metrics in the OpenCenesus format and export them using prometheus exporter by default. It seems like datadog also has a support for prometheus integration (https://docs.datadoghq.com/integrations/prometheus/). Did you find some limitation from this and request a feature to natively support datadog metrics exporter?

**Comment by scottsun94** [comment]
@salman1993 It seems that this feature has been supported. Is there any limitation from it? Otherwise, we could close this issue?

**Comment by scottsun94** [comment]
Closing it for now. @salman1993 Please reopen if your issues are not resolved.
