### ISSUE TITLE
Python3.5 support?

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1277]
Is ray supported for Python 3.5 or later?  Official Ray instructions ask to install pssh which is only supported for 2.7, 3.2. Default Ubuntu AMI comes with Python 3.5 . PS, I use paramiko which is 3.5 compatible

**Comment by pcmoritz** [comment]
Yes it supports Python 3.5 and 3.6 (not yet 3.7 however). We have wheels for both these versions.

**Comment by yaroslavvb** [comment]
But I can't install pssh on Python 3.5, should I use Ray on 3.5 without it? This page says I need it -- http://ray.readthedocs.io/en/latest/using-ray-on-a-large-cluster.html

If I try to install it on a system that has Python 3.5 (default Ubuntu AMI), it tries to get Python 2

```
7[0;44r8[1A[Jubuntu@ip-172-31-28-76:~$ sudo apt-get install pssh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python
  python-minimal python2.7 python2.7-minimal
Suggested packages:
  python-doc python-tk python2.7-doc binfmt-support
The following NEW packages will be installed:
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib pssh python
  python-minimal python2.7 python2.7-minimal

```

**Comment by pcmoritz** [comment]
I typically use Anaconda Python 3 and that doesn't interfere with pssh and you can install the system python 2.7 just fine.

**Comment by pcmoritz** [comment]
As long as you only import ray from python3 and used pip3 to install it, it should also work if you use the system python 3 and have they system python 2.7 installed. Let us know if you run into problems. But Anaconda is usually better than the system python so I'd recommend that!

**Comment by robertnishihara** [comment]
@yaroslavvb I use `pssh` and Python 3.5 all the time (though typically with Anaconda). You're saying that `pssh` tries to install Python 2, but is that a problem? It just means you'll have an extra Python on your machine.

**Comment by yaroslavvb** [comment]
Nope, shouldn't be a problem, I was pre-emptively trying to avoid things running in the wrong version of Python
