### ISSUE TITLE
[core] sys.stdout broken for 3rd party libraries

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#12784]
### What is the problem?
* ray nightly
* pafy==0.5.5

### Reproduction (REQUIRED)
I was testing something with ray nightly and got
```
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/rvai/extensions/sources/videostream_source.py", line 10, in <module>
    import pafy
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/pafy/__init__.py", line 7, in <module>
    from .pafy import new
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/pafy/pafy.py", line 40, in <module>
    from .util import call_gdata
  File "/app/miniconda3/envs/regulator/lib/python3.6/site-packages/pafy/util.py", line 18, in <module>
    not_utf8_environment = mswin or (sys.stdout.encoding and
AttributeError: 'StandardStreamInterceptor' object has no attribute 'encoding'
```
It seems since 11 days, ray is overwriting `sys.stdout` with something custom that does not inherit from the original `sys.stdout`, which breaks any 3rd party library that also want to use `sys.stdout` I assume...
https://github.com/ray-project/ray/blob/e3b5deb7414aee5265840148dd62eb028709999d/python/ray/workers/default_worker.py#L190

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Ah, yeah we added this for the log rotation. I will add the encoding method.

**Comment by PidgeyBE** [comment]
Adding encoding method will fix this particular issue, but still there could be other issues left, right?

**Comment by rkooo567** [comment]
I think we can keep adding methods in that case? The current class is almost like a file-like object in my opinion. If you have other good ideas to support log rotation to logs that are streamed to stdout, I'd love to hear the idea as well. Btw, @edoakes, this issue is related to the one I was worried bout when you reviewed my code!

**Comment by PidgeyBE** [comment]
I just feel like in that way you will always lag behind.
![image](https://user-images.githubusercontent.com/19860056/101894674-d17a5f80-3ba6-11eb-9461-6cdba5023b74.png)
I think these are all the methods/properties that should be supported

**Comment by rkooo567** [comment]
I see. @AmeerHajAli also suggested to inherit sys.stdout. I will either do that or implement all those 3 methods.

**Comment by rkooo567** [comment]
@PidgeyBE Is it a hard blocker now?

**Comment by PidgeyBE** [comment]
@rkooo567 If it is in a release we will not be able to use the release because we depend on other 3rd party libraries to which are broken now.

**Comment by rkooo567** [comment]
Hmm I see. Can I ask you which library caused this issue?

**Comment by PidgeyBE** [comment]
@rkooo567 Sure, that's in the ticket description: `pafy==0.5.5`. So just doing `import pafy` is enough to raise an exception.

**Comment by rkooo567** [comment]
Thanks! I will try fixing it asap and hopefully I can include it to the next release.

**Comment by rkooo567** [comment]
@mfitton I think it is okay to cherry-pick this now
