### ISSUE TITLE
API for specifying resource requirements at task submision time

### ISSUE THREAD

**Issue by aldanor** [ray-project/ray#1278]
(Initial discussion in #1236.)

It would be useful to be able to specify resource requirements when submitting a task (especially RAM -- for example, the same task running a ML task being applied to a grid of learners and datasets, varying in size; in this case we can specify how much the task is going to consume before launching it, but this information is not static).

The current infrastructure is in place to support specifying resource requirements at tasks submission time, however it can only be done now via `ray.remote()` decorator which attaches them to tasks statically; the current workaround is doing something like this, creating a new wrapper for each execution:

```python
def f(x):
    pass

ray.remote(resources={"Memory": 1})(f)(3)
ray.remote(resources={"Memory": 2})(f)(4)
```

A cleaner API would be nice; maybe something like this (or whichever else if anyone has better ideas):

```python
@ray.remote
def f(x):
    pass

f.with_resources(Memory=1).remote(3)
f.with_resources(Memory=2).remote(4)
```

**Comment by robertnishihara** [comment]
Thanks @aldanor, this is a really good idea. Something like your API suggestion should work I think.

**Comment by robertnishihara** [comment]
This can be done with `f._remote(args=[], kwargs={}, num_return_vals=2, num_cpus=1, num_gpus=2, resources={'Custom': 1})`.
