### ISSUE TITLE
Is ray or ray[serve] compatible with python3.9 and pipenv/poetry?

### ISSUE THREAD

**Issue by dashsatish** [ray-project/ray#12788]
Ray and Ray-Serve

### What is the problem?
Unable to install latest version of ray a.k.a 1.0.1.post1 in a virtual env running with python3.9. The error so described 
here is same when run with pipenv or poetry.

*Ray version and other system information (Python version, TensorFlow version, OS):*
OS version: MacOS catalina, version: 10.15.6(19G73)
Python: 3.9
Poetry: Poetry version 1.1.4
(or
pipenv: 2018.11.26
)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
python -m pip install -U pip pipenv==2018.11.26 poetry --no-cache-dir
poetry new demo
cd demo
# edit pyproject.toml file to add "ray" in the project dependencies (sample toml file attached):
# neither of these work when put in the pyproject.toml file
# >>> ray = "*"
# >>> ray = { version = "*" }
poetry update
```
[pyproject.toml.zip](https://github.com/ray-project/ray/files/5679609/pyproject.toml.zip)

[Error obtained]
```

 • Installing ray (1.0.1.post1): Failed

  RuntimeError

  Unable to find installation candidates for ray (1.0.1.post1)

  at ~/.pyenv/versions/3.9.0/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```
If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [Yes ] I have verified my script runs in a clean environment and reproduces the issue.
- [Yes ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
Hi @dashsatish, unfortunately Ray (and therefore Ray Serve) does not support Python 3.9 yet. We are actively working on this and you can expect to see support for it soon. We currently support Python 3.6-3.8.

**Comment by edoakes** [comment]
Closing due to duplicate with https://github.com/ray-project/ray/issues/12788

**Comment by dashsatish** [comment]
@edoakes Just curious, is the work to support ray-core with python 3.8 to 3.9 intensive? The reason I ask this is because  I assume supporting different python 3.x versions for a library(including a huge stack system) should be seamless. Do correct me.

**Comment by edoakes** [comment]
@dashsatish see the above issue for details. It's not quite that simple because Ray contains a significant amount of C++/cython code.

**Comment by frankier** [comment]
That above link is a link to this issue!
