### ISSUE TITLE
[serve] Make deploying basic models simpler

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12794]
Currently, the "hello world" deployment for Serve is:

```python
serve.start()
serve.create_backend("backend_name", BackendImpl)
serve.create_endpoint("endpoint_name", backend="backend_name")
```

This logical endpoint / physical backend split is useful for advanced features like traffic splitting, incremental deployments, etc. but for basic use cases this is quite verbose and can be confusing.

**Comment by edoakes** [comment]
@simon-mo @architkulkarni my proposal here is to introduce a new wrapper API called `serve.deploy` that will basically just wrap `create_backend` and `create_endpoint` into one.

```python
serve.deploy("backend_and_endpoint_name", BackendImpl, config=BackendConfig(), route="/backend_and_endpoint_name")
```

If the user calls `serve.deploy` and the backend and endpoint already exist, we will transparently create a new backend, switch traffic to it, and delete the existing backend. We can also introduce another API called `serve.delete` that will delete the backend/endpoint pair.
```python
serve.delete("backend_and_endpoint_name")
```

In the docs, the basic examples can all use this API, then we can point to the backend/endpoint docs for advanced use cases.

Thoughts?

**Comment by architkulkarni** [comment]
This sounds great!  I wonder if it might be a little confusing when used in conjunction with `create_backend` and `create_endpoint` for the advanced use cases, but I think it's still worth it.  

How should `serve.delete("backend_and_endpoint_name")` work?  It can delete the backend and endpoint with that name, but perhaps it should also delete other backends (with other names) used by the endpoint with name `"backend_and_endpoint_name"`.

**Comment by edoakes** [comment]
Improved in deployments API
