### ISSUE TITLE
Remove load_code_from_local

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#12834]
### Describe your feature request
Currently, the python code can be loaded from gcs or local, but can't can loaded from both side. It would be great if we can try load code from local first, and load from gcs if we can't load cpode from local.

**Comment by raulchen** [comment]
sounds good to me

**Comment by kfstorm** [comment]
The only concern I have is performance regression. We may need some tests.

**Comment by rkooo567** [comment]
Any progress in this?

**Comment by kfstorm** [comment]
@chaokunyang Do you have any plan solving this issue?

**Comment by chaokunyang** [comment]
There may be a code consistency issue . If we load code from local first and then load from gcs. We may have some code consistency in python. Due to the dynamics of python, one can replace a class's method runtime. If we load code from gcs, we can get the latest class in remote. But if we load code from local first, we just got the raw class and lost the remote modification.

**Comment by kira-lin** [comment]
Hi, I'm very interested in this feature. @chaokunyang Are you still working on this? Particularly, what I need is the ability for python to call java actor/functions, but meanwhile python can still call its functions defined outside the code search path. This is a common use case for python, such as in a REPL like Jupyter notebook. 

I feel like specifying a java code search path does not necessarily applies to python. Loading from both local and GCS is great, but if it has consistency issues, I think maybe as a first step we can separate code search path for python and java. In other words, when only java_code_search_path is set, python still loads functions from gcs.

**Comment by raulchen** [comment]
@kira-lin @chaokunyang  we can work around this by only allowing dynamically changing functions that were initially loaded from the GCS. If a function was initially loaded from local disk, it can not be dynamically changed.

@rkooo567 does this sound good to you?

I can find someone to work on this.

**Comment by kira-lin** [comment]
Hi @rkooo567 , @raulchen , any progress?

**Comment by raulchen** [comment]
hi @kira-lin , #17605 will fix this issue.
