### ISSUE TITLE
Installing Ray Core on Rasbperry Pi 4B

### ISSUE THREAD

**Issue by rodorio** [ray-project/ray#12835]
Hello,

I dont know if this is the correct place to post this but I'm wanting to install Ray on my rasberry-pi but I keep getting the following message:

Could not find a version that satisfies the requirement ray (from versions: )
No matching distribution found for ray

From what I understand this is due to the fact that Ray does not currently build a wheel for ARM. 

I was wondering if someone had instructions on how to install it/build it for the pi. If it makes it easier I'm only looking to install the Ray core for now.

Thanks!

**Comment by PidgeyBE** [comment]
We are working on ARM builds.
I should have a ray 0.8.5 somewhere if you'd like and I'm currently trying to build ray 1.0.1.

If Ray team could give us some pointers of where to put our code (using qemu/docker for emulation ARM environment) we could put it in the ray repository.

**Comment by PidgeyBE** [comment]
@rodorio This zip should contain a wheel for ray 1.0.1 on ARM. Would you mind testing it?
[ray-1.0.1-cp36-cp36m-linux_aarch64.zip](https://github.com/ray-project/ray/files/5691036/ray-1.0.1-cp36-cp36m-linux_aarch64.zip)

**Comment by rodorio** [comment]
Thanks @PidgeyBE! I dont know if I did it right but I got this error:

$pip install /home/pi/Downloads/ray-1.0.1-cp36-cp36m-linux_aarch64.whl
ray-1.0.1-cp36-cp36m-linux_aarch64.whl is not a supported wheel on this platform.

**Comment by rodorio** [comment]
Ok, I think I figured it out, my RPI has armv71 instead of aarch64.

**Comment by rodorio** [comment]
Ok, apparently there is a 64 bit version of Raspbian thats in beta. I'm gonna try to update to it tomorrow.

**Comment by PidgeyBE** [comment]
@rodorio Yes indeed there is. I'm also trying to build a release for ARMv7.
But it takes a long time :)

**Comment by PidgeyBE** [comment]
@rodorio I've build ray and py-spy (ray dependency) for ARMv7l. Would be interesting if you could try it out!
[ray-pyspy-armv7l.zip](https://github.com/ray-project/ray/files/5698218/ray-pyspy-armv7l.zip)

**Comment by rodorio** [comment]
Hm, looks like the same error. Any ideas?

$pip install /home/pi/Downloads/py_spy-0.3.3-cp36-cp36m-linux_armv7l.whl
py_spy-0.3.3-cp36-cp36m-linux_armv7l.whl is not a supported wheel on this platform.

**Comment by rodorio** [comment]
Got a little further:

	$python3.6 -m pip install py_spy-0.3.3-cp36-cp36m-linux_armv7l.whl
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
		from pip._internal import main as _main  # isort:skip # noqa
	  File "/usr/lib/python3/dist-packages/pip/_internal/__init__.py", line 40, in <module>
		from pip._internal.cli.autocompletion import autocomplete
	  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
		from pip._internal.cli.main_parser import create_main_parser
	  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
		from pip._internal.cli import cmdoptions
	  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 17, in <module>
		from pip._internal.locations import USER_CACHE_DIR, src_prefix
	  File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 10, in <module>
		from distutils import sysconfig as distutils_sysconfig
	ImportError: cannot import name 'sysconfig'

**Comment by rodorio** [comment]
I think its because I have both 3.6 and 3.7 installed but I cant seem to be able to fix it. I may try looking into virtual environments but I've never worked with them before.

**Comment by PidgeyBE** [comment]
I got myself a RasPi4 and the following worked for me, using conda environments:
(The benefit of conda over virtualenv will be that conda can download packages that are already compiled/built for ARM. Conda is also pretty well isolated from the system python installations)
```
wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh
sudo md5sum Miniconda3-latest-Linux-armv7l.sh # (optional) check md5
chmod +x Miniconda3-latest-Linux-armv7l.sh
./Miniconda3-latest-Linux-armv7l.sh # -> change default directory to /home/pi/miniconda3
```

```
bash
conda config --add channels rpi
conda create -n ray python=3.6
source activate ray
```

```
pip install py_spy-0.3.3-cp36-cp36m-linux_armv7l.whl
pip install ray-1.0.1-cp36-cp36m-linux_armv7l.whl
```
... this last step takes a while... will update when finished...

**Comment by PidgeyBE** [comment]
This one works on my Raspi4! [Uploading ray_armv7l_32bit.zip…]()

**Comment by PidgeyBE** [comment]
This version works for me on Raspberry Pi 4, 32bit OS: [ray_armv7l_32bit.zip](https://github.com/ray-project/ray/files/5703429/ray_armv7l_32bit.zip)

**Comment by rodorio** [comment]
Nice! I've been swamped today but I'll give it a try tomorrow. Was it still using the conda env?

**Comment by PidgeyBE** [comment]
Yes, indeed! Instructions above, with conda, but with that last zip file!

**Comment by rodorio** [comment]
Ah darn, I think I broke my bash installation messing around with pyenv a few days ago. Imma try to see if I can undo what I did:

bash: export: `$': not a valid identifier
bash: export: `export PATH="/home/pi/.pyenv/shims:${PATH}"

**Comment by rodorio** [comment]
Hm so I got it to install but it wont run:

`Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.6.12/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/home/pi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/ray/__init__.py", line 61, in <module>
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "/home/pi/.pyenv/versions/3.6.12/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/.pyenv/versions/3.6.12/lib/python3.6/site-packages/ray/_raylet.so: wrong ELF class: ELFCLASS64

**Comment by rodorio** [comment]
Oh never mind, I got it working. Thanks @PidgeyBE!

Would you happen to have the py_spy installer foraarch64? I want to try to get that working as well.

**Comment by PidgeyBE** [comment]
@rodorio Py spy and ray for python 3.6, aarch64:
[ray1.0.1-cp36.zip](https://github.com/ray-project/ray/files/5728997/ray1.0.1-cp36.zip)
Haven't tested them myself, but will do later today

**Comment by rodorio** [comment]
Really appreciate it @PidgeyBE, worked like a charm!

I'll play around wit it and let you know how it goes:


  Python 3.6.12 (default, Dec 21 2020, 06:39:15)
  [GCC 8.3.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> import ray
  >>>

**Comment by benfred** [comment]
py-spy has wheels for armv7/aarch64 on pypi now - you should be able to pip install it on a raspberry pi now: https://github.com/benfred/py-spy/issues/328
