### ISSUE TITLE
Issue in ray.init() functionality

### ISSUE THREAD

**Issue by mohitranawat** [ray-project/ray#12841]
I am using ray  version 1.0.1.post1 in Linux.
I have made the ray cluster of two systems.
My member node has one GPU also.
I wanted to use both the nodes and GPU also but when I am mentioning  ` ray.init( address = "auto") ` I cannot use the GPU.
and when I want to explicitly mention the `num_cpus`  according to total number of cores combining both the nodes and `num_gpus` it is not able to acccess the other node.

Also I want to limit the number of processes created and divide it among two machines in cluster. This is also not possible I guess ?

Am I understanding the API wrong or is there any bug ?

**Comment by edoakes** [comment]
@mohitranawat could you post a stack trace or a code sample so we have more information to go on here? This would also probably be better posted on discuss.ray.io -- that's our community forum.

**Comment by mohitranawat** [comment]
`import time 
import random 
import ray 
import os
ray.init(num_gpus = 1)


def tiny_work(x):

    for i in range(10000):
        pass
    time.sleep(0.0001) # replace this is with work you need to do
    return x

@ray.remote
def mega_work(start, end):
    return [tiny_work(x) for x in range(start, end)]

start = time.time()
result_ids = []
[result_ids.append(mega_work.remote(x*1000, (x+1)*1000)) for x in range(1000)]
results = ray.get(result_ids)
print("duration =", time.time() - start) `

There is no as such things as stack traces in this case. The inferences I told you are collected from ray dashboard @edoakes

**Comment by mohitranawat** [comment]
` import time 
import random 
import ray 
import os
ray.init(num_gpus = 1)


def tiny_work(x):
    for i in range(10000):
        pass
    time.sleep(0.0001) # replace this is with work you need to do
    return x

@ray.remote
def mega_work(start, end):
    return [tiny_work(x) for x in range(start, end)]

start = time.time()
result_ids = []
[result_ids.append(mega_work.remote(x*1000, (x+1)*1000)) for x in range(1000)]
results = ray.get(result_ids)
print("duration =", time.time() - start)  
`

**Comment by edoakes** [comment]
@mohitranawat this seems like more of an "API question" than an issue - could you please post this on the community forum at discuss.ray.io?
