### ISSUE TITLE
[tune] local scheduler doesn't register GPUs

### ISSUE THREAD

**Issue by smellslikeml** [ray-project/ray#1285]
### System information
- **OS: Linux Ubuntu 16.04
- **Install: source**
- **Ray 0.3.0
- **Python 3.6

### Describe the problem
Modified example from docs on tune to load data and train XGBoost
Installation passes all tests
tutorial example no. 9 succeeds in recognizing 2 gpus through get_gpu_ids()

setting "resources" : {"cpu": 32, "gpu": 0}, I can run without GPUs.
swept "driver_cpu_limit" and "driver_gpu_limit"

### Source code / logs
```
== Status ==
Using FIFO scheduling algorithm.
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'colsample_bytree': 0.746, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01}:	PENDING

Waiting for redis server at 127.0.0.1:18594 to respond...
Waiting for redis server at 127.0.0.1:39609 to respond...
Allowing the Plasma store to use up to 40.5045GB of memory.
Starting object store with directory /dev/shm and huge page support disabled
Starting local scheduler with the following resources: {'CPU': 32}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui8173.ipynb?token=3aa72eec694631c9b5a2d32fbbc3ae7a157e58a5ca997987
======================================================================

Traceback (most recent call last):
  File "xgb_sweep.py", line 60, in <module>
    run_experiments({'xgb_sweep': xgb_sweep})
  File "/home/funk/anaconda3/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/tune/tune.py", line 77, in run_experiments
    runner.step()
  File "/home/funk/anaconda3/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/tune/trial_runner.py", line 84, in step
    (trial.resources, self._avail_resources))
ray.tune.error.TuneError: ('Insufficient cluster resources to launch trial', (Resources(cpu=32, gpu=2, driver_cpu_limit=32, driver_gpu_limit=2), Resources(cpu=32, gpu=0, driver_cpu_limit=32, driver_gpu_limit=0)))
Disconnecting client on fd 9
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5317 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5318 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5319 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5320 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5321 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5322 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5323 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5324 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5325 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5326 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5327 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5328 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5329 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5330 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5331 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5332 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5333 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5334 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5335 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5336 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5337 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5338 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5339 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5340 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5341 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5342 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5343 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5344 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5345 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5346 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5347 which hadn't started yet.
[INFO] (/home/funk/ray/src/local_scheduler/local_scheduler.cc:168) Killed worker pid 5348 which hadn't started yet.
Disconnecting client on fd 7
Disconnecting client on fd 5
```

**Comment by ericl** [comment]
Can you try `run_experiments(..., num_gpus=N)`?

Currently we don't auto-detect the number of GPUs locally so you need to pass that through to ray (https://github.com/ray-project/ray/issues/1168)

**Comment by smellslikeml** [comment]
I tried num_gpus both inside/outside of resources part of the config for run_experiments.

"resources": {"cpu": 32, "num_gpus": 2} results in the error:

ray.tune.error.TuneError: Unknown resource type num_gpus, must be one of ('cpu', 'gpu', 'driver_cpu_limit', 'driver_gpu_limit')

setting
'gpu': 0
gives no error

'gpu': 2 
leads to the above

**Comment by richardliaw** [comment]
Hey, just to identify the problem (and clarify what Eric said above) - can you confirm you've tried the following:

```
run_experiments(
        config={... "resources": {"cpu": 32, "gpu": 2}}, 
        num_gpus=2
)
```

Note that there is both a `gpu` specification in the config and also a `num_gpus` in the `run_experiment` top level.

**Comment by smellslikeml** [comment]
Thanks for clarification. While specifying num_gpus=2 outside the "experiment dictionary", I was only able to use **one** of the available gpus. 
Experimented with declaring CUDA_VISIBLE_DEVICES="0,1" and find normal gpu utilization only on the first gpu id in the list: ray.get_gpus_ids()       #[1,0]

Increased num_gpus to 10, 4, 3 (more than the 2 available devices) to find:
terminate called after throwing an instance of 'thrust::system::system_error'

Incidentally, after running on one gpu, the script fails with:

ray.tune.error.TuneError: Trial finished without reporting result!

I had set reporter=None. I will need to review reporters to make this work with xgboost api.

**Comment by richardliaw** [comment]
Sounds good! 

If you could also provide the logs for both num_gpus = 2 and setting num_gpus to more than 2 that would help a lot!

**Comment by smellslikeml** [comment]
**N=2**

== Status ==
Using FIFO scheduling algorithm.
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	PENDING

Waiting for redis server at 127.0.0.1:35815 to respond...
Waiting for redis server at 127.0.0.1:16221 to respond...
Allowing the Plasma store to use up to 40.5045GB of memory.
Starting object store with directory /dev/shm and huge page support disabled
Starting local scheduler with the following resources: {'GPU': 2, 'CPU': 32}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui30177.ipynb?token=bbaacac6b658843d1214fa6e35ff1df87643774699335483
======================================================================

Unified logger created with logdir '/tmp/ray/xgb_sweep/my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}ov06zfjp'
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources used: 32/32 CPUs, 2/2 GPUs
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	RUNNING

[0]rent train-auc:0.602915      valid-auc:0.594356_reg_01_plus_ps_car_04_cat    2 in   0.1
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 1000 rounds.
[100]	train-auc:0.627395	valid-auc:0.615766
[200]	train-auc:0.630025	valid-auc:0.617953
[300]	train-auc:0.634868	valid-auc:0.62193
[400]	train-auc:0.640331	valid-auc:0.626239
[500]	train-auc:0.645019	valid-auc:0.630646
[600]	train-auc:0.648239	valid-auc:0.633475
[700]	train-auc:0.650864	valid-auc:0.635132
[800]	train-auc:0.652789	valid-auc:0.635984
[900]	train-auc:0.65483	valid-auc:0.636717
[1000]	train-auc:0.656657	valid-auc:0.637019
[1100]	train-auc:0.658397	valid-auc:0.637466
[1200]	train-auc:0.659993	valid-auc:0.637731
[1300]	train-auc:0.661382	valid-auc:0.63781
[1400]	train-auc:0.66277	valid-auc:0.63793
[1500]	train-auc:0.664021	valid-auc:0.637977
[1600]	train-auc:0.665181	valid-auc:0.637936
[1700]	train-auc:0.66629	valid-auc:0.637897
[1800]	train-auc:0.667546	valid-auc:0.637991
[1900]	train-auc:0.668623	valid-auc:0.638022
[2000]	train-auc:0.669619	valid-auc:0.638046
[2100]	train-auc:0.670647	valid-auc:0.637979
[2200]	train-auc:0.671655	valid-auc:0.638013
[2300]	train-auc:0.672699	valid-auc:0.637869
[2400]	train-auc:0.673707	valid-auc:0.637854
[2500]	train-auc:0.674754	valid-auc:0.637793
[2600]	train-auc:0.675778	valid-auc:0.637651
[2700]	train-auc:0.676705	valid-auc:0.637527
[2800]	train-auc:0.677654	valid-auc:0.637374
Stopping. Best iteration:
[1857]	train-auc:0.66818	valid-auc:0.6381

Remote function train failed with:

Traceback (most recent call last):
  File "/home/funk/ray/python/ray/worker.py", line 759, in _process_task
    *arguments)
  File "/home/funk/ray/python/ray/actor.py", line 199, in actor_method_executor
    return method(actor, *args)
  File "/home/funk/ray/python/ray/tune/script_runner.py", line 152, in train
    result = self._status_reporter._get_and_clear_status()
  File "/home/funk/ray/python/ray/tune/script_runner.py", line 44, in _get_and_clear_status
    raise TuneError("Trial finished without reporting result!")
ray.tune.error.TuneError: Trial finished without reporting result!


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:35815")
  
Error processing event: Traceback (most recent call last):
  File "/home/funk/ray/python/ray/tune/trial_runner.py", line 163, in _process_events
    result = ray.get(result_id)
  File "/home/funk/ray/python/ray/worker.py", line 2212, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(0346f989004b4c118dd69d10658f70751fcb98ba). It was created by remote function train which failed with:

Remote function train failed with:

Traceback (most recent call last):
  File "/home/funk/ray/python/ray/worker.py", line 759, in _process_task
    *arguments)
  File "/home/funk/ray/python/ray/actor.py", line 199, in actor_method_executor
    return method(actor, *args)
  File "/home/funk/ray/python/ray/tune/script_runner.py", line 152, in train
    result = self._status_reporter._get_and_clear_status()
  File "/home/funk/ray/python/ray/tune/script_runner.py", line 44, in _get_and_clear_status
    raise TuneError("Trial finished without reporting result!")
ray.tune.error.TuneError: Trial finished without reporting result!


Stopping my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'} Actor timed out, but moving on...
== Status ==
Using FIFO scheduling algorithm.
Resources used: 0/32 CPUs, 0/2 GPUs
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	ERROR

Traceback (most recent call last):
  File "xgb_sweep.py", line 61, in <module>
    run_experiments({'xgb_sweep': xgb_sweep}, num_gpus=N)
  File "/home/funk/ray/python/ray/tune/tune.py", line 82, in run_experiments
    raise TuneError("Trial did not complete", trial)
ray.tune.error.TuneError: ('Trial did not complete', <ray.tune.trial.Trial object at 0x7fd21a47cfd0>)
Disconnecting client on fd 9
[WARN] (/home/funk/ray/src/local_scheduler/local_scheduler_algorithm.cc:282) Removing actor with ID c4f401abafdc958e1c41d5eea88228f6b0b09668 and 1 remaining tasks.
[WARN] (/home/funk/ray/src/global_scheduler/global_scheduler.cc:406) Missed too many heartbeats from local scheduler, marking as dead.
Disconnecting client on fd 43
Disconnecting client on fd 41
Disconnecting client on fd 40
Disconnecting client on fd 39
Disconnecting client on fd 38
Disconnecting client on fd 42
Disconnecting client on fd 37
Disconnecting client on fd 36
Disconnecting client on fd 35
Disconnecting client on fd 34
Disconnecting client on fd 33
Disconnecting client on fd 32
Disconnecting client on fd 31
Disconnecting client on fd 30
Disconnecting client on fd 29
Disconnecting client on fd 28
Disconnecting client on fd 27
Disconnecting client on fd 26
Disconnecting client on fd 24
Disconnecting client on fd 25
Disconnecting client on fd 23
Disconnecting client on fd 22
Disconnecting client on fd 21
Disconnecting client on fd 20
Disconnecting client on fd 19
Disconnecting client on fd 18
Disconnecting client on fd 17
Disconnecting client on fd 16
Disconnecting client on fd 15
Disconnecting client on fd 14
Disconnecting client on fd 13
Disconnecting client on fd 12
Disconnecting client on fd 11
Disconnecting client on fd 7
Disconnecting client on fd 5




**N = 3**
== Status ==
Using FIFO scheduling algorithm.
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	PENDING

Waiting for redis server at 127.0.0.1:10767 to respond...
Redis failed to start, retrying now.
Waiting for redis server at 127.0.0.1:11076 to respond...
Allowing the Plasma store to use up to 40.5045GB of memory.
Starting object store with directory /dev/shm and huge page support disabled
Starting local scheduler with the following resources: {'GPU': 3, 'CPU': 32}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui26598.ipynb?token=000a008c3858f6818a6a99b4a52de160a967c2e329c26e44
======================================================================

Unified logger created with logdir '/tmp/ray/xgb_sweep/my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}ad857ccu'
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources used: 32/32 CPUs, 3/3 GPUs
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	RUNNING

terminate called after throwing an instance of 'thrust::system::system_error'   2 in   0.1
  what():  
Disconnecting client on fd 20
A worker died or was killed while executing a task.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="127.0.0.1:10767")
  
Error processing event: Traceback (most recent call last):
  File "/home/funk/ray/python/ray/tune/trial_runner.py", line 163, in _process_events
    result = ray.get(result_id)
  File "/home/funk/ray/python/ray/worker.py", line 2212, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(c155c7235c220db1ba6f3ca12cce5bb3a369e9d3). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task.

== Status ==
Using FIFO scheduling algorithm.
Resources used: 0/32 CPUs, 0/3 GPUs
Tensorboard logdir: /tmp/ray/xgb_sweep
 - my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}:	ERROR

Traceback (most recent call last):
  File "xgb_sweep.py", line 61, in <module>
    run_experiments({'xgb_sweep': xgb_sweep}, num_gpus=N)
  File "/home/funk/ray/python/ray/tune/tune.py", line 82, in run_experiments
    raise TuneError("Trial did not complete", trial)
ray.tune.error.TuneError: ('Trial did not complete', <ray.tune.trial.Trial object at 0x7fd42cefbfd0>)
Disconnecting client on fd 9
Disconnecting client on fd 43
[WARN] (/home/funk/ray/src/global_scheduler/global_scheduler.cc:406) Missed too many heartbeats from local scheduler, marking as dead.
Disconnecting client on fd 42
Disconnecting client on fd 41
Disconnecting client on fd 40
Disconnecting client on fd 39
Disconnecting client on fd 38
Disconnecting client on fd 37
Disconnecting client on fd 36
Disconnecting client on fd 35
Disconnecting client on fd 31
Disconnecting client on fd 34
Disconnecting client on fd 30
Disconnecting client on fd 33
Disconnecting client on fd 32
Disconnecting client on fd 27
Disconnecting client on fd 29
Disconnecting client on fd 28
Disconnecting client on fd 26
Disconnecting client on fd 24
Disconnecting client on fd 25
Disconnecting client on fd 23
Disconnecting client on fd 22
Disconnecting client on fd 21
Disconnecting client on fd 19
Disconnecting client on fd 18
Disconnecting client on fd 17
Disconnecting client on fd 16
Disconnecting client on fd 15
Disconnecting client on fd 14
Disconnecting client on fd 13
Disconnecting client on fd 12
Disconnecting client on fd 11
Disconnecting client on fd 7
Disconnecting client on fd 5

**Comment by ericl** [comment]
Hm, I'm wondering if xgboost is respecting CUDA_VISIBLE_DEVICES? Basically if you run the xgboost code outside of Ray, does setting CUDA_VISIBLE_DEVICES allow it to use both gpus in that case?

Btw, the reporter error is since you have to call reporter to reports results, e.g. `reporter(timesteps_total=100, mean_accuracy=0.615766)` to report the first line above.

**Comment by smellslikeml** [comment]
Thank you for the reporter clarification, I used best_iteration and parsed the eval methods of xgboost's 
 train inside the my_train function.
XGBoost uses the parameter[ 'n_gpus'.](http://xgboost.readthedocs.io/en/latest/gpu/)

[Recompiled xgboost](http://forums.fast.ai/t/xgboost-with-gpu-support/5535/2
) source after [installing NCCL](http://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html#debian) from NVIDIA.

Now setting 'n_gpus' : 2, I confirm fuller utilization of both devices running the command:
watch -n 0.1 nvidia-smi

However, each of 4 experiments is launched one at a time i.e.

config_0..... RUNNING
config_1.... PENDING
config_2.... PENDING
config_3.... PENDING

Ran separate process using xgboost to confirm that it doesn't default to consume all GPU memory like tensorflow.

**Comment by ericl** [comment]
Yeah, that's expected since the Ray schedulers assigns the full GPU to each trial (if you request 2 gpus, the trial has exclusive access to those GPUs until it completes).

Support for fractional GPUs is not yet implemented: https://github.com/ray-project/ray/issues/402

As a workaround you can manage GPU scheduling yourself (request 0 gpus), and just set CUDA_VISIBLE_DEVICES etc. manually. You can also tweak the CPU resource request to avoid overloading the GPUs, e.g. even if only need 1 CPU you can request more CPUs so that Ray will not schedule too many concurrent trials on the two GPUs of the node.

fyi @robertnishihara

**Comment by ericl** [comment]
Btw, I'm curious why your experiment string looks like `my_train_0_config={'objective': 'binary:logistic', 'eval_metric': 'auc', 'eta': 0.009, 'max_depth': 4, 'subsample': 0.766, 'min_child_weight': 300, 'silent': 1, 'stratified': True, 'gamma': 0.01, 'tree_method': 'gpu_hist'}`, typically I see something like `my_train_0_max_depth=4,subsample=0.5,min_child_weight=300`. Are you passing in the config var as a raw python string instead of a dictionary?

**Comment by smellslikeml** [comment]
Appreciate the clarification... will stay tuned.
I pass a dictionary and use xgb.train(params) instead of the XGBClassifier

**Comment by richardliaw** [comment]
OK this should be addressed in xray (closing for now).
