### ISSUE TITLE
[rllib] Overriding policy.compute_actions does not work with ray > 1.0.0 and torch

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#12861]
### What is the problem?
I have been able to find a way to update default policies in a generic fashion. I.e. based on some user specified functionality that can be added to a policy, such as a `mixin`, one can specify which policy to update based on the `run_or_experiment` flag in `tune_kwargs`. See: https://github.com/ray-project/ray/discussions/11806, https://github.com/ray-project/ray/discussions/11636, and the repo: https://github.com/acxz/action-mod-rllib for how I have done this for overriding compute_actions for any specified policy. (P.S. would be nice to have this feature in rllib proper.)

This has worked fine for torch and ray versions <= 1.0.0, however, above that version number, it seems that rllib is not going through the mixin code path.
It is important to note that `tf` works just fine for versions of ray >= 1.0.0.

Basically, adding a mixin that overrides `compute_actions` of a torch policy does not affect the policy, even though a new updated policy is registered by rllib.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 1.0.1post
python:  3.8.6
torch: 1.7.1
tensorflow-gpu: 2.4.0
OS: archlinux

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

<details>
<summary>Script</summary>

  ```
"""Script to run experiment."""
from typing import Dict, List, Optional

import ray
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.agents.ppo import ppo_tf_policy
from ray.rllib.agents.ppo import ppo_torch_policy
from ray.rllib.agents.ppo.ppo_tf_policy import PPOTFPolicy
from ray.rllib.agents.ppo.ppo_torch_policy import PPOTorchPolicy
from ray.rllib.policy import tf_policy, torch_policy
from ray.rllib.policy.policy import Policy
from ray.rllib.utils.annotations import override
from ray.rllib.utils.typing import TensorType, Tuple, Union


def train_cartpole():
    """Cartpole experiment."""
    ray.init()

    class ActionModMixin:
        """Mixin class that overrides the action computation of the policy."""

        # pylint: disable=too-many-locals
        @override(Policy)
        def compute_actions(
                self,
                obs_batch: Union[List[TensorType], TensorType],
                state_batches: Optional[List[TensorType]] = None,
                prev_action_batch: Union[List[TensorType], TensorType] = None,
                prev_reward_batch: Union[List[TensorType], TensorType] = None,
                info_batch: Optional[Dict[str, list]] = None,
                episodes: Optional[List["MultiAgentEpisode"]] = None,
                explore: Optional[bool] = None,
                timestep: Optional[int] = None,
                **kwargs) -> \
                Tuple[TensorType, List[TensorType], Dict[str, TensorType]]:
            """Override the compute_actions of the policy."""
            actions, state_out, extra_fetches = \
                super().compute_actions(obs_batch, state_batches,
                                        prev_action_batch, prev_reward_batch,
                                        info_batch, episodes, explore,
                                        timestep, **kwargs)

            modified_actions = actions
            modified_state_out = state_out
            modified_extra_fetches = extra_fetches

            import sys
            sys.exit()

            return modified_actions, modified_state_out, modified_extra_fetches

    setup_tf_before_init = ppo_tf_policy.setup_config
    tf_mixins = [tf_policy.LearningRateSchedule,
                 tf_policy.EntropyCoeffSchedule,
                 ppo_tf_policy.KLCoeffMixin,
                 ppo_tf_policy.ValueNetworkMixin]

    setup_torch_before_init = ppo_tf_policy.setup_config
    torch_mixins = [torch_policy.LearningRateSchedule,
                    torch_policy.EntropyCoeffSchedule,
                    ppo_torch_policy.KLCoeffMixin,
                    ppo_torch_policy.ValueNetworkMixin]

    # pylint: disable=unused-argument
    def setup_action_mod_mixin_before_init(policy, obs_space, action_space,
                                           config):
        """Initialize ActionModMixin."""
        ActionModMixin.__init__(policy)

    def setup_action_mod_mixin_tf_before_init(policy, obs_space, action_space,
                                              config):
        """Initialize tf default and ActionMod Mixins."""
        setup_tf_before_init(policy, obs_space, action_space,
                             config)
        setup_action_mod_mixin_before_init(policy, obs_space, action_space,
                                           config)

    def setup_action_mod_mixin_torch_before_init(policy, obs_space,
                                                 action_space, config):
        """Initialize torch default and ActionMod Mixins."""
        setup_torch_before_init(policy, obs_space, action_space,
                                config)
        setup_action_mod_mixin_before_init(policy, obs_space, action_space,
                                           config)

    # Extend existing mixins with the ActionModMixin
    tf_mixins.append(ActionModMixin)
    torch_mixins.append(ActionModMixin)

    ActionModPPOTFPolicy = PPOTFPolicy.with_updates(
        name='ActionModPPOTFPolicy',
        before_init=setup_action_mod_mixin_tf_before_init,
        mixins=tf_mixins)

    ActionModPPOTorchPolicy = PPOTorchPolicy.with_updates(
        name='ActionModPPOTorchPolicy',
        before_init=setup_action_mod_mixin_torch_before_init,
        mixins=torch_mixins)

    def get_policy_class(config):
        if config['framework'] == 'torch':
            return ActionModPPOTorchPolicy

        return ActionModPPOTFPolicy

    ActionModTrainer = PPOTrainer.with_updates(
        default_policy=ActionModPPOTFPolicy,
        get_policy_class=get_policy_class)

    ray.tune.registry.register_trainable('ActionModTrainer', ActionModTrainer)

    tune_kwargs = {
        'run_or_experiment': 'ActionModTrainer',
        'stop': {
            'episode_reward_mean': 150,
            'timesteps_total': 100000,
        },
        'config': {
            'env': 'CartPole-v0',
            # Works: compute_actions gets overridden and exits via sys.exit()
            # 'framework': 'tf',
            # Doesn't work: compute_actions does not get overridden and fails
            # to exit with a sys.exit()
            'framework': 'torch',
            'gamma': 0.99,
            'lr': 0.0003,
            'num_workers': 1,
            'observation_filter': 'MeanStdFilter',
            'num_sgd_iter': 6,
            'vf_share_layers': True,
            'vf_loss_coeff': 0.01,
            'model': {
                'fcnet_hiddens': [32],
                'fcnet_activation': 'linear',
            }
        }
    }

    ray.tune.run(**tune_kwargs)


if __name__ == '__main__':
    train_cartpole()
  ```

</details>

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Downstream issue: https://github.com/acxz/action-mod-rllib/issues/1

**Comment by sven1977** [comment]
Could you post a small self-sufficient reproduction script here that creates such a policy so I can debug this?

**Comment by acxz** [comment]
I have posted my script under a drop down menu in the OP. Or would you like a more slimmed down one?

**Comment by acxz** [comment]
@sven1977 could you take a look at this issue again. My script is posted in the OP.

**Comment by Manuscrit** [comment]
I had a similar problem. I found that when using: ` "_use_trajectory_view_api": True,` (default to `True` in RLLib 1.1.0) then the rollout worker will use the method `policy.compute_actions_from_input_dict` instead of `policy.compute_actions`.
I guess you can set it to `False` in your rllib config dict or refactor your code to work with `compute_actions_from_input_dict`.

**Comment by angelolovatto** [comment]
Related to what @Manuscrit said, with `"_use_trajectory_view_api": True`, the extra fetches (third element of returned tuple) from `policy.compute_actions` do not appear in the sample batch collected by rollout workers. Thus, if you compute things like action likelihoods for later use, you won't find them in the batch.

**Comment by 51616** [comment]
@angelolovatto I think you still can use extra information from the batch. Have a look at [this file](https://github.com/ray-project/ray/blob/master/rllib/policy/torch_policy.py#L287). After computing the actions, you can add extra fetches to the output the same way you did with `compute_actions`.

If you still don't see these columns, try using `_initialize_loss_from_dummy_batch` in your custom policy. It add/remove views from policy's view_requirements depending on your loss/inference.

**Comment by Manuscrit** [comment]
Instead of overriding `policy.compute_action` you could to override `policy._compute_action_helper` to have your change be used by both `policy.compute_actions` and `policy.compute_actions_from_input_dict`.

Related to @angelolovatto 
> with "_use_trajectory_view_api": True, the extra fetches (third element of returned tuple) from policy.compute_actions do not appear in the sample batch collected by rollout workers.

To have your `extra_fetches` sent into the `sample_batch` you can add the keys you want in the `policy.view_requirements` like that:
```
self.view_requirements.update(
  {
      "new_key": ViewRequirement(),
  }
)
```

Otherwise your new extra_fetches are filtered out by 
https://github.com/ray-project/ray/blob/c2e240e866b9564d083dbeb8fec5d8179d4d2ee0/rllib/evaluation/sampler.py#L844-L848

**Comment by angelolovatto** [comment]
Thank you @Manuscrit! I didn't notice the filtering step in sampler.py; that is very interesting. I'll try it out when I get the chance and see if the results appear in my sample batch.
