### ISSUE TITLE
[tune] Conditional Grid Search??

### ISSUE THREAD

**Issue by GuHongyang** [ray-project/ray#12869]
Hello there! I want to know if it supports conditional grid search.

I hope that when a takes different values, b will also grid search the corresponding results.

I have four situations to search, as shown below
**（a=1, b=8), (a=1, b=9), (a=2, b=6), (a=2, b=7)**

But currently only grid search can be performed in the following way
_config={
            "a": tune.grid_search([1,2]),
            "b": tune.grid_search([6,7,8,9]),
        })_
In this case, 2 * 4 = 8 experiments will be performed. This will cause some unnecessary waste of resources. Is it possible to perform a conditional grid search? ? ? I know that it is currently possible to customize the search algorithm to achieve this effect. Will the official consider implementing this search space?

**Comment by sumanthratna** [comment]
Hi @GuHongyang! Can you take a look at this? I think it might help for your use-case: https://docs.ray.io/en/master/tune/tutorials/overview.html#conditional-grid-search. 

For your example that would look like this (hard-coded):
```python
def _iter():
    yield 1, 8
    yield 1, 9
    yield 2, 6
    yield 2, 7

config = {
    "ab": tune.grid_search(list(_iter())),
}
```

**Comment by krfricke** [comment]
In your case you should even be able to use something like this:

```
config = {
    "ab": tune.grid_search([(1, 8), (1, 9), (2, 6), (2, 7)])
}
```

I'll close this since we deal with this case in the documentation.
