### ISSUE TITLE
Inconsistency with scheduling on the Actor methods

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#1286]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.3
- **Python version**: 3.6

### Describe the problem

There is a bit of inconsistency with the scheduling of methods on an Actor. See the code example below.

### Source code / logs

I will include a full working example for Python 3+:
```python
import ray
import time

ray.init()

@ray.remote
class ActorA():
    def __init__(self):
        self.list = []
    def actorMethod(self, i):
        self.list.append(i)
    def getList(self):
        return self.list

@ray.remote
def remoteTask(actorHandle):
    for i in range(10000):
        actorHandle.actorMethod.remote(i)
    return "Done"

actorHandle = ActorA.remote()

ray.get(remoteTask.remote(actorHandle))

for sec in range(7):
    print(len(ray.get(actorHandle.getList.remote())))
    time.sleep(1)
```
Output:
```
2538
3916
5326
6754
8203
9667
10000
```
Notice that, despite the `ray.get` on the remote task, which guarantees that all tasks from the loop are scheduled, we still are getting `actorHandle.getList` scheduled with some priority over the others. The following is my workaround for this currently.

```python
import ray

ray.init()

@ray.remote
class ActorA():
    def __init__(self):
        self.list = []
    def actorMethod(self, i):
        self.list.append(i)
        return "Done"
    def getList(self):
        return self.list

@ray.remote
def remoteTask(actorHandle):
    oidList = []
    for i in range(10000):
        oidList.append(actorHandle.actorMethod.remote(i))
    return oidList

actorHandle = ActorA.remote()

ray.get(ray.get(remoteTask.remote(actorHandle)))
print(len(ray.get(actorHandle.getList.remote())))
```
This workaround forces a wait on the execution, not the scheduling. Ideally we could have some guarantees about scheduling when calling something like this.

**Comment by edoakes** [comment]
@stephanie-wang is this still an issue?

**Comment by stephanie-wang** [comment]
This looks like expected behavior to me.
