### ISSUE TITLE
[autoscaler] give the ability to modify the node types while the cluster is running

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#12879]
If you have a running cluster and you want to change the node types without terminating the cluster, make sure it works smoothly.

CC @edoakes @Gekho457. Can any of you please provide a good example use case here?

**Comment by edoakes** [comment]
Example: in Ray Serve, want to deploy a new model with different dependencies while the cluster is running.

**Comment by DmitriGekhtman** [comment]
Solved for VMs, tracked elsewhere for KubeRay.
