### ISSUE TITLE
[Docker] Microbenchmark client put gb/s perf regression

### ISSUE THREAD

**Issue by mfitton** [ray-project/ray#12895]
### What is the problem?
When running the release tests in Docker via the product, two aspects of the microbenchmark show a regression in speed, namely in `multi client put gigabytes per second` and `single client put gigabytes per second`
![image (1)](https://user-images.githubusercontent.com/3156716/102279237-ea08b380-3edf-11eb-9e77-068aa35453e4.png)
![image](https://user-images.githubusercontent.com/3156716/102279240-eb39e080-3edf-11eb-8ec0-9dffb35ff2c4.png)

Here is the analysis difference from the previous version:
![image (2)](https://user-images.githubusercontent.com/3156716/102279389-26d4aa80-3ee0-11eb-9a87-1b70d79dcb0f.png)

*Ray version and other system information (Python version, TensorFlow version, OS):* 
Run using the ray-project/releaser tool on the 1.1.0 release in the Anyscale product latest ray docker image. `python cli.py --git-branch releases/ray-1.1.0 suite:run microbenchmark` is what I'm using to trigger the build. The only difference with the release branch is a line:
![image](https://user-images.githubusercontent.com/3156716/102279709-b4b09580-3ee0-11eb-9690-d1e0327a4d9d.png)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
Verified that this was caused by passing too little memory to `--shm-size`. Relevant warning for Ray:
```
2020-12-15 22:51:11,578	WARNING services.py:1640 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 2147483648 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
```

This error message was a little confusing, so improving it here: https://github.com/ray-project/ray/pull/12896
