### ISSUE TITLE
reduce computation time for DL

### ISSUE THREAD

**Issue by divyankgarg** [ray-project/ray#12902]
I want to know is there any way in Ray that can be used to reduce the computation time for DL models. 
Like for sklearn ML models I tried to used the ray remote and actors for model selection and then ray back end for computing individual model. It gave good result in SVC and xg-boosting method by reducing computation time and better result. 
I waant to do the same for DL models like I have 3 different LSTM models and using ray remote and actor I am able to do model selection at less time but for computing individual model using ray backend it doesn't work. Ray does not activate for computation and DL model take almost same time as usual?

**Comment by edoakes** [comment]
@divyankgarg this would also be better posted to discuss.ray.io

**Comment by divyankgarg** [comment]
Yes sure will do it. But can anyone provide the solution for it. Ray SGD with TFTrainer is already tested but it failed to give better result in total time taken.

**Comment by richardliaw** [comment]
(moving this discussion to `discuss.ray.io`)
