### ISSUE TITLE
[tune] Implement adaptive multi-resolution grid search as a ray.tune TrialScheduler

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1290]
Grid search is one of the most popular hyperparam search algorithms (despite its inefficiency), due to its easy understandability. It would be great to provide an adaptive version of grid search that provides the same understandability benefits, while saving on costs. My guess is that a 2-5x cost savings will not be hard to achieve, and it can save experimentation time as well.

The implementation could look something like this:
- The user defines some grid (hypercube) to evaluate; the scheduler starts with a very coarse version of that grid (e.g. 2-3 points per dimension).
- As results become available, add more dimension values (hypercube slices) to explore potentially promising regions.
- When it becomes clear a dimension value is poor performing or statistically indistiguishable from nearby values (likely since typically only a few of the hyperparam values have the most effect), pause/stop trials for the entire dimension value (hypercube slice).

**Comment by Kaahan** [comment]
Currently looking into this.
