### ISSUE TITLE
Ray SGD Distributed Tensorflow

### ISSUE THREAD

**Issue by divyankgarg** [ray-project/ray#12900]
I tried to compare the time taken by LSTM model for 230k rows with using Ray distributed tensorflow and not using Ray.  All the parameters are same like batch size and steps per epoch. But I am shocked to find that LSTM model on single VM without Ray is performing better then compared to Ray SGD for number of replicas ranging from 4 to 12. We have 6 machine in Ray cluster (30 cores) then also Ray sgd for same model take more time to compute. What is the reason?

**Comment by richardliaw** [comment]
@divyankgarg can you post this question on discuss.ray.io?

Thanks!

**Comment by divyankgarg** [comment]
Hi @richardliaw . Could you tell the solution for it. Why TFTrainer is not helping in reducing the time for DL models even it is replicating the models and dataset is huge. Why increasing replicas is taking more time to compute compared to simple LSTM in one worker node?

**Comment by richardliaw** [comment]
(moved to discuss.ray.io)
