### ISSUE TITLE
[Kubernetes] Resilience of Ray/K8s cluster launcher and operator to temporarily unavailable K8s API.

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#12924]
In production environments, the K8s API server can sometimes be temporarily unavailable.  
This causes problems launching clusters (https://github.com/ray-project/ray/issues/12883)
and autoscaling (https://github.com/ray-project/ray/issues/12255)

The cluster launcher and operator need to be resilient to temporary unavailability of the K8s API server, e.g. 
by implementing retry logic.
We also need to test this resilience in the CI.

**Comment by AmeerHajAli** [comment]
@Gekho457 Thanks for filing this! I generally add Serverless Milestone to such issues.
.

**Comment by Gekho457** [comment]
I think you beat me to adding the milestone by a split second :)

**Comment by DmitriGekhtman** [comment]
This isn't specific enough and has been confusing for planning work on the serverless autoscaling milestone. Closing.
