### ISSUE TITLE
broken pipe when calling ray.get()

### ISSUE THREAD

**Issue by tylerkohn** [ray-project/ray#12920]
When running under reasonable (not necessarily huge) load I've witnessed broken pipes when calling ray.get() to retrieve something.  Under most conditions this does not happen so I don't have a reproducible script.  

we are using ray 1.0.0 on a GKE cluster and minikube (seeing it on both) using python 3.7 on Ubuntu 20.04.1 LTS

The error being reported is:

```
 File "/app/company/services/ray_services/training/training_details_actor.py", line 316, in get_model_version_dict
    return ray.get(training_details_oid)
  File "/venv/lib/python3.7/site-packages/ray/worker.py", line 1423, in get
    values = worker.get_objects(object_refs, timeout=timeout)
  File "/venv/lib/python3.7/site-packages/ray/worker.py", line 303, in get_objects
    object_refs, self.current_task_id, timeout_ms)
  File "python/ray/_raylet.pyx", line 807, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 150, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe `
```

The code being called is:
```
    def get_model_version_dict(self):
        training_details_oid = self._actor.get_training_details.remote(
            self._model_version_name
        )
        return ray.get(training_details_oid)
```

get_training_details is just managing a dictionary of strings

if there are specifics that I'm missing that would be helpful let me know. Thanks!

**Comment by rkooo567** [comment]
Did you see any logs from /tmp/session_latest/logs/raylet.out or *core-worker* logs when you see this error?

**Comment by tylerkohn** [comment]
are those logs found on the specific worker?  also, where/which logs are the core-worker logs?  the pods are still up but the logs seem to have been rotated (haven't found anything with the right dates yet.

**Comment by richardliaw** [comment]
They should be on the `head` pod. You can just post all the `/tmp/ray/session_latest` logs (in a zip) if you want us to look through it :)

**Comment by tylerkohn** [comment]
unfortunately those logs were long gone.  I updated a number of the libraries (including ray - we were on 1.0.0).  I'm going to close this and open a new one if I run across this again.  thanks!
