### ISSUE TITLE
[dashboard] Empty screen or errors when running ray

### ISSUE THREAD

**Issue by TanjaBayer** [ray-project/ray#12938]
### What is the problem?

When starting ray scrips with the latest nightly version the dasboard only shows a blank screen, making it impossible to check any logs or other stuff. When checking the console the following two errors are printed repeatedly:

![image](https://user-images.githubusercontent.com/30770185/102464888-3cb3ae00-404d-11eb-9707-ea9de553cefc.png)

* ray: 1.1.0.dev0
* Python 3.7.9 
* Ubuntu 18.04

I assume it is a specific Linux/Ubuntu issue because I was not able to reproduce the problem on a Mac

### Reproduction 
A minimal example which was reproducing the issue. Sometimes you see the dashboard for some seconds before the screen becomes blank

``` python
import time

import numpy as np
import ray

print(ray.__version__)
ray.init()


@ray.remote
def get_batch():
    batch_of_numpys = [np.random.randint(0, 255, (360, 640, 3), dtype=np.uint8) for _ in
                       range(0, 150)]
    return batch_of_numpys


while True:
    print(len(ray.get(get_batch.remote())))
    time.sleep(2)

```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html). Actually it only happens there for me.

@mfitton

**Comment by edoakes** [comment]
@mfitton could you take a look?

**Comment by mfitton** [comment]
I'm also able to reproduce on Ubuntu, and not on OS X. It has to do with the logCount and errorCount for workers being undefined in Ubuntu for some reason. Reading through the code now and trying to figure out how that could happen...

**Comment by mfitton** [comment]
I'm still a little confused about why this is happening, but I have some front-end code that I think will at least patch the issue if nothing else. I'm running this alongside some other tasks, but I'm going to test the fix at some point today and open up a PR if the fix is successful.
