### ISSUE TITLE
AttributeError: module 'ray' has no attribute 'services'

### ISSUE THREAD

**Issue by kli-crise** [ray-project/ray#12934]
`2020-12-17 15:17:44,440 INFO worker.py:651 -- Connecting to existing Ray cluster at address: 10.244.5.200:6379
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    set(ray.get([f.remote() for _ in range(1000)]))
  File "/home/kpl/.local/lib/python3.6/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::f() (pid=654, ip=10.244.5.200)
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "test.py", line 9, in f
    return ray.services.get_node_ip_address()
AttributeError: module 'ray' has no attribute 'services'
`

**Comment by richardliaw** [comment]
`from ray.services import get_node_ip_address()`

**Comment by valiantljk** [comment]
https://docs.ray.io/en/master/cluster/index.html might need to be updated

```
import time

@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```
