### ISSUE TITLE
Properly fate-share dashboard agents with Raylet on Windows

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#12949]
### What is the problem?

We should be able to do this using the Windows Job API, we currently do that for the workers.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mattip** [comment]
I am not familiar with the term "fate-share" and could only find [one reference](https://docs.ray.io/en/latest/placement-group.html?highlight=fate-share#lifecycle) to it in the documentation. Is there something actionable to do for this issue?
