### ISSUE TITLE
[rllib] ValueError: ('Observation ({}) outside given space ({})!' for an inside the space observation

### ISSUE THREAD

**Issue by saeid93** [ray-project/ray#12940]
rrlib's `preprocessor.py` line 62 gets stuck in the value error `ValueError: ('Observation ({}) outside given space ({})!`. But the observation is not outside the given space. I tried the same observation and space outside rllib and the `observation_space.contains(observation)` returned `True` for the example that rllib returns `ValueError`

**observation**:

```
{'containers_resources_usage':
 array([[ 563.2, 5734.4,  500. ],
       [ 563.2, 5734.4,  500. ],
       [ 563.2, 5734.4,  500. ],
       [ 563.2, 5734.4,  500. ],
       [ 870.4, 4915.2,  800. ],
       [ 870.4, 4915.2,  800. ],
       [ 870.4, 4915.2,  800. ],
       [ 460.8, 5734.4,  900. ],
       [ 460.8, 5734.4,  900. ],
       [ 460.8, 5734.4,  900. ],
       [ 460.8, 5734.4,  900. ],
       [  51.2, 2457.6, 1400. ],
       [  51.2, 2457.6, 1400. ],
       [  51.2, 2457.6, 1400. ]]), 
'hosts_resources_usage': 
array([[ 1433.6, 10649.6,  1300. ],
       [ 1484.8, 13107.2,  2700. ],
       [ 1075.2, 13926.4,  2800. ],
       [  972.8, 13926.4,  3200. ],
       [ 1894.4, 16384. ,  2200. ]]),
'containers_resources_usage_frac':
array([[0.55, 0.7 , 0.25],
       [0.55, 0.7 , 0.25],
       [0.55, 0.7 , 0.25],
       [0.55, 0.7 , 0.25],
       [0.85, 0.6 , 0.4 ],
       [0.85, 0.6 , 0.4 ],
       [0.85, 0.6 , 0.4 ],
       [0.45, 0.7 , 0.45],
       [0.45, 0.7 , 0.45],
       [0.45, 0.7 , 0.45],
       [0.45, 0.7 , 0.45],
       [0.05, 0.3 , 0.7 ],
       [0.05, 0.3 , 0.7 ],
       [0.05, 0.3 , 0.7 ]]),
'hosts_resources_usage_frac':
array([[0.7  , 0.65 , 0.325],
       [0.725, 0.8  , 0.675],
       [0.525, 0.85 , 0.7  ],
       [0.475, 0.85 , 0.8  ],
       [0.925, 1.   , 0.55 ]]),
'containers_hosts':
array([4, 2, 0, 1, 1, 4, 0, 2, 3, 4, 3, 3, 1, 2]),
'auxiliary_resources_usage':
array([0., 0., 0.])}
```

**Space:**

```
Dict(auxiliary_resources_usage:Box(0.0, 114688.0, (3,), float64),
containers_hosts:Box(0.0, 6.0, (14,), float32),
containers_resources_usage:Box(0.0, 8192.0, (14, 3), float64),
containers_resources_usage_frac:Box(0.0, 1.0, (14, 3), float64),
hosts_resources_usage:Box(0.0, 16384.0, (5, 3), float64),
hosts_resources_usage_frac:Box(0.0, 1.0, (5, 3), float64)))
```

**Comment by sven1977** [comment]
This is a float32 vs float64 problem. Your Space has a couple of float64 components in it, e.g. `auxiliary_resources_usage`, but the np.arrays in your sample seem to be float32 ones. Could you confirm that this would work if you either change your space to all float32 or your sample accordingly?
I admin that these mismatches should probably not throw an error, but just be translated into the right type. ...

**Comment by saeid93** [comment]
Yes, that solved the problem. Thank you!

**Comment by KiborgBBK** [comment]
Good day
with a similar problem, I solved the question, maybe you can help solve this problem (https://github.com/ray-project/ray/issues/13177):

agent = AlphaZeroTrainer (config = config)
agent.restore (checkpoint2)
env = CartPole ()

state = env.reset ()
action = agent.compute_action (state)
print (action)

... / ray / rllib / contrib / alpha_zero / play.py ", line 180, in <module>
    action = agent.compute_action (obs)
  File "... / ray / rllib / agents / trainer.py", line 858, in compute_action
    result = self.get_policy (policy_id) .compute_single_action (
  File "... / ray / rllib / policy / policy.py", line 211, in compute_single_action
    out = self.compute_actions (
  File "... / ray / rllib / contrib / alpha_zero / core / alpha_zero_policy.py", line 47, in compute_actions

    return self.compute_actions_from_input_dict (
  File "... / ray / rllib / contrib / alpha_zero / core / alpha_zero_policy.py", line 62, in compute_actions_from_input_dict
    for i, episode in enumerate (episodes):
TypeError: 'NoneType' object is not iterable


thanks in advance for the answer

**Comment by chokosabe** [comment]
Why is this closed?!

Running into the exact same problem....

**Comment by KiborgBBK** [comment]
The problem is the wrong floats. Perhaps instead of float64, you need to supply float32, or instead of float, supply int. Well, or something like that, you need to watch what should be in the state of the environment

**Comment by quinn-dougherty** [comment]
Getting this bug with `spaces.Discrete`, is it known to also be a problem converting between int and float?

**Comment by wegfawefgawefg** [comment]
This issue isnt correct. 
I've verified my observation space is correct, and have tried both float32 and float64 casting on the returned observations from my env. Ive widened the observation state to absurd numbers to ensure it couldnt be exceeded, as well.

If I had to guess, the issue may have something to do with checkpoint loading. Does checkpoint loading pull in the old obs space settings?

**Comment by tieincred** [comment]
I am facing similar issue but couldn't figure out even after changing the float 64 and float 32 types for observations space.
![error1](https://user-images.githubusercontent.com/60173762/119931581-41d33c80-bf9f-11eb-829e-050169be8b25.jpg)
![error2](https://user-images.githubusercontent.com/60173762/119931583-43046980-bf9f-11eb-941d-735ac20b682e.jpg)
![error3](https://user-images.githubusercontent.com/60173762/119931584-43046980-bf9f-11eb-9d4f-fd34cfd0f3fc.jpg)

**Comment by tieincred** [comment]
can anyone help me around this?

**Comment by crazy25000** [comment]
> can anyone help me around this?

Your limits are inverted, try flipping the min and max.
