### ISSUE TITLE
[K8s] PIP install in pod running `rayproject/ray:nightly` image does not work on GKE

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#12944]
### What is the problem?
See title.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Gekho457** [comment]
@richardliaw could you add repro script / other details
