### ISSUE TITLE
[Dashboard] Getting `KeyError: 'RAY_RAYLET_PID'` on Win.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#12947]
When running e.g. `rllib train --env CartPole-v0 --run PPO` on Windows, I'm seeing these error messages.
The program doesn't crash.

```
(pid=None) Traceback (most recent call last):
(pid=None)   File "D:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\new_dashboard/agent.py", line 317, in <module>
(pid=None)     raise e
(pid=None)   File "D:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\new_dashboard/agent.py", line 293, in <module>
(pid=None)     agent = DashboardAgent(
(pid=None)   File "D:\Programs\Anaconda3\envs\ray\lib\site-packages\ray\new_dashboard/agent.py", line 65, in __init__
(pid=None)     self.ppid = int(os.environ["RAY_RAYLET_PID"])
(pid=None)   File "D:\Programs\Anaconda3\envs\ray\lib\os.py", line 675, in __getitem__
(pid=None)     raise KeyError(key) from None
(pid=None) KeyError: 'RAY_RAYLET_PID'

```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
I saw these error messages yesterday on my Mac even with just a `ray.init()`. 

It stopped after I upgraded the latest wheels again.
