### ISSUE TITLE
[k8s] nodes are leaked upon outdated config

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12959]
### Reproduction (REQUIRED)

When we update the cluster yaml, it is expected that the entire ray k8s cluster is terminated (and all worker pods too).

However, in testing, I've seen that the worker pods remain alive. This causes the cluster to leak resources.

**Comment by richardliaw** [comment]
@Gekho457 @AmeerHajAli

**Comment by Gekho457** [comment]
Related: https://github.com/ray-project/ray/issues/12879
Recently @yiranwang52 @edoakes and I talked about this -- I think we agreed that the autoscaler's restart/update behavior is in general not very well defined or documented.  

@richardliaw 
How precisely did you modify the cluster config? 

If something specifying the behavior of worker pods is modified, I definitely agree that the existing worker pods should be terminated.
If a global setting like `upscaling_speed` is changed, that shouldn't necessarily cause any pods to terminate.

**Comment by richardliaw** [comment]
Yeah this is a bit complex. 

The cluster provider will terminate the head node and restart it if the head node config changes. The head node will do the same for worker nodes (if needed).

Usually on other node providers, you can safely terminate the head node, and the new head node will either be able to attach to existing worker nodes. And thus, "leaking nodes" is actually not that big deal.

However, in our situation, there can be the case where:

1. head pod requests worker pods to be placed
2. worker pods are queued, waiting for instance pool to scale up
3. user terminates head pod during config change.
4. queued worker pod gets placed in lieu of head pod on that existing node
5. user can't use the existing resources anymore and needs to wait for a new head pod, all while worker pods are claiming unused resources.

**Comment by DmitriGekhtman** [comment]
Improving the behavior of KubeRay when Ray cluster configuration is changed is tracked in the KubeRay repo.
