### ISSUE TITLE
How to use BERT tokenizer in ray cluster?

### ISSUE THREAD

**Issue by deepankar27** [ray-project/ray#12965]
Hello Team,

ray==0.8.4

First, a big thanks for awesome lib I love it's simplicity.
I have 3 node cluster setup, I am doing text pre-processing where I need Bert tokenizer as well. I want to distribute it as well.
I am looking for suggestion on how to distribute it, only this piece is running on local.
 - I am thinking to use Ray[serve]
 - Distribute ray service only for tokenization. I want to avoid it for n/w overhead

Thanks in advance.

**Comment by richardliaw** [comment]
Hey, can you please post questions to https://discuss.ray.io/ ? 

Thanks!
