### ISSUE TITLE
[Autoscaler] cleanup the cluster yaml

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#12960]
~~1) remove `worker_default_node_type` field from the cluster yaml and cleanup the code that uses it [Done].~~
2) print a warning/logger.error for using `min_workers` and `initial_workers` and any of the deprecated fields in the yaml with multi node types.
~~3) Make max_workers infinity per node type by default. [Done]~~
4) Make all example-full.yaml for all providers use multi node types and update all the defaults.yaml to use multi node type.

// We should consider doing the following but this should not be a requirement because we do not support modifying the cluster yaml while the cluster is running.
1) support `worker_start_ray_commands` per node type similar to `worker_setup_commands` and `initialization commands`.
2) The config runtime hash should take into account the per node type custom config and not only the global `config["worker_setup_commands"]`.
3) The config runtime hash should take into account the global and per node type`initialization_commands`.
4) Add the global/per node type docker_config to the list of hashed configs. 

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
> make max_workers a required field

Why does this need to be required? The alternative here is to default to `inf` because the global max_workers field is required and bounds the max number of nodes regardless.
