### ISSUE TITLE
[tune]AttributeError: 'NoneType' object has no attribute 'optimizer'

### ISSUE THREAD

**Issue by Coorch** [ray-project/ray#12969]
### What is the problem?

- Ray version: 1.0.1.post1
- python: 3.7.5
- OS: Linux version 4.14.81.bm.23-amd64

AttributeError: 'NoneType' object has no attribute 'optimizer'

### Reproduction (REQUIRED)
`from ray.tune.suggest.skopt import SkOptSearch`

![image](https://user-images.githubusercontent.com/38720272/102588520-833a0300-4148-11eb-98b8-72864d59ab40.png)

**Comment by richardliaw** [comment]
Thanks for the report! The fix is to install `pip install scikit-optimize`.

**Comment by richardliaw** [comment]
I've opened a PR to fix this error message

**Comment by Coorch** [comment]
> Thanks for the report! The fix is to install `pip install scikit-optimize`.

Thanks. 
The problem has been solved.
