### ISSUE TITLE
[autoscaler] Improve/specify/document precise restart/update behavior of the autoscaler

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#12966]
The behavior of the autoscaler when the cluster config is updated seems not to be very well specified or documented. It should be clearer how changing each field of the cluster config affects the state of the cluster.

Related issues:
https://github.com/ray-project/ray/issues/12879
https://github.com/ray-project/ray/issues/12959

**Comment by DmitriGekhtman** [comment]
I think we mostly covered this in https://github.com/ray-project/ray/pull/16691
The information is probably present in the docs, spread between reference sections  for `ray up` and cluster configs.
Not entirely sure how important this is or how best to gather/present this info.

For what sorts of workflows do users prefer to `ray up` to update a cluster rather than doing `ray down; ray up`?
@richardliaw @javi-redondo wdyt?

**Comment by wuisawesome** [comment]
Bumping priority to P2 since we have some documentation now

**Comment by DmitriGekhtman** [comment]
Documented the behavior for VMs. (Hopefully the doc refactor didn't accidentally delete that.)
Related issues tracked for KubeRay.
