### ISSUE TITLE
Ray: Check failed: _s.ok() Bad status: IOError: Failed to receive the handle.

### ISSUE THREAD

**Issue by enxtw1** [ray-project/ray#12979]
cant connect to Win 10 CLI init from Python with following error:

2020-12-18 23:17:57,062 INFO worker.py:650 -- Connecting to existing Ray cluster at address: 192.168.1.73:6379
F1218 23:18:01.161550   872 14600 client.cc:262]  Check failed: _s.ok() Bad status: IOError: Failed to receive the handle.
*** Check failure stack trace: ***
    @   00007FFF675E983B  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FFF675E85D2  public: __cdecl google::LogMessage::~LogMessage(void) __ptr64
    @   00007FFF675AF9C8  public: virtual __cdecl google::NullStreamFatal::~NullStreamFatal(void) __ptr64
    @   00007FFF6741431D  PyInit__raylet
    @   00007FFF67411998  PyInit__raylet
    @   00007FFF67411D3C  PyInit__raylet
    @   00007FFF673EE156  PyInit__raylet
    @   00007FFF673F292B  PyInit__raylet
    @   00007FFF673ED1AA  PyInit__raylet
    @   00007FFF6738BFDC  PyInit__raylet
    @   00007FFF673A17AC  PyInit__raylet
    @   00007FFF6738E50A  PyInit__raylet
    @   00007FFF673B4A17  PyInit__raylet
    @   00007FFF67326471  public: virtual void __cdecl google::LogSink::WaitTillSent(void) __ptr64
    @   00007FFF67349377  public: virtual void __cdecl google::LogSink::WaitTillSent(void) __ptr64
    @   00007FFF672AF822  (unknown)
    @   00007FFF71D4775E  _PyEval_EvalCodeWithName
    @   00007FFF71D5A80C  _PyObject_MakeTpCall
    @   00007FFF71D5A5A3  _PyObject_FastCallDict
    @   00007FFF71EDA903  _PyEval_SignalReceived
    @   00007FFF71E57FEB  Py_FatalError
    @   00007FFF71D4BA07  _PyEval_EvalFrameDefault
    @   00007FFF71D46D18  _PyEval_EvalCodeWithName
    @   00007FFF71D47C7F  _PyFunction_Vectorcall
    @   00007FFF71D5A55F  _PyObject_FastCallDict
    @   00007FFF71EDA903  _PyEval_SignalReceived
    @   00007FFF71E57FEB  Py_FatalError
    @   00007FFF71D4BE3E  _PyEval_EvalFrameDefault
    @   00007FFF71D46D18  _PyEval_EvalCodeWithName
    @   00007FFF71D47C7F  _PyFunction_Vectorcall
    @   00007FFF71D5A55F  _PyObject_FastCallDict
    @   00007FFF71EDA903  _PyEval_SignalReceived

Ray is latest via pip install in conda, Python 3.8, Win 10, no Tensorflow

### Reproduction (REQUIRED)
in CLI: ray start --head --port=6379    --> used in Conda env..for some reason I cant run in cmd because of dependency issues. Python below is run in same conda env. Following the instruction on ray in conda I had it working once but after that I had the above issue again.

In Python:
import ray
ray.init(address='auto', _redis_password='5241590000000000')

- [ YES] I have verified my script runs in a clean environment and reproduces the issue.
- [ YES] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

I have also tried with below python code but no difference to above error:
os.environ['GRPC_VERBOSITY']='DEBUG'
os.environ['http_proxy']=''
os.environ['https_proxy']=''

Sometimes I get the normal init to work from Python code but its temperamental. I also tried init with ignore_reinit_error=True but I still get the issue. 

Maybe I can resolve the issue if I dont run the CLI but have a logic in Python that identifies if init has run and then doesnt call it again?

**Comment by edoakes** [comment]
@enxtw1 I'm a little bit confused about the workflow that you're using that's hitting the issue here. Could you provide the sequence of commands you're running that reproduces the issue? Also, could you please provide more info about the environment (e.g., python version, windows vs. WSL, etc.)

**Comment by enxtw1** [comment]
> @enxtw1 I'm a little bit confused about the workflow that you're using that's hitting the issue here. Could you provide the sequence of commands you're running that reproduces the issue? Also, could you please provide more info about the environment (e.g., python version, windows vs. WSL, etc.)

Thanks for responding!

Environment: Ray is latest via pip install in conda, Python 3.8, Win 10, no Tensorflow, no WSL
Workflow: 1) run CLI in conda env 2) import and init in python as per above  --> I had this working once but when I tried again I am then and still now getting the above error
