### ISSUE TITLE
The ray stuck when report metrics

### ISSUE THREAD

**Issue by LianShuaiLong** [ray-project/ray#12981]
### What is the problem?
 I choose Ray with AsyncHyperBandScheduler to search Optimal hyperparameters for deep networks, but i found the program stuck when report metrics to Ray, how can i solve it?
*Ray version and other system information (Python version, TensorFlow version, OS):*
version:1.0
tensorflow version:1.14
os:ubuntu18.04
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

        self.estimator.train(input_fn=self.train_input_fn, steps=None)
        save_dir = os.path.join(Configs["serving_model"],str(self.trial_name))
        #os.makedirs(save_dir, exist_ok=True) 
        export_model(self.estimator,save_dir)#Configs["serving_model"]) #saving model corresponed to trial_name
        self.metric_val = self.estimator.evaluate(input_fn = self.val_input_fn)
        

        return {
                "epoch": self.iteration,
                "val_cvr_auc": self.metric_val['cvr_auc'],
                "val_ctr_auc": self.metric_val['ctr_auc']
                }

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Can you print the types for `self.metric_val['cvr_auc']`?

**Comment by LianShuaiLong** [comment]
> Can you print the types for `self.metric_val['cvr_auc']`?
I just found out that it occurs due to my large evaluation set, not bug of Ray
