### ISSUE TITLE
[tune] @wandb_mixin doesn't work with tune.with_parameters

### ISSUE THREAD

**Issue by ujvl** [ray-project/ray#13005]
### What is the problem?

`@wandb_mixin` decorator doesn't work with tune.with_parameters. 

my guess is you need to pull the trainable fn's `__mixin__` property out to the with_parameters wrapper fn.

```
from ray.tune.integration.wandb import wandb_mixin
from ray import tune

@wandb_mixin
def train(cfg, a, b):
	wandb.log({"ok": 1}) 

tune.run(tune.with_parameters(train, a=1, b=2))
```

Error:

```
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train() (pid=48002, ip=169.229.48.120)
        ...
    raise wandb.Error("You must call wandb.init() before {}()".format(name))
wandb.errors.error.Error: You must call wandb.init() before wandb.log()
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
hey, thanks for the report. Have you tried this on master (1.2.0.dev0)?

cc @krfricke @amogkam

**Comment by amogkam** [comment]
Yep this should be fixed on master/latest wheels! 

https://github.com/ray-project/ray/blob/master/python/ray/tune/function_runner.py#L653

**Comment by ujvl** [comment]
ah thanks, worked for me
