### ISSUE TITLE
[tune] sample_from validation fails with functools.partial and callables with kwargs

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#13009]
CC @richardliaw 

(labeling as bug because functools.partial and callables with kwargs should definitely be supported [IMO] and there's no indication in the docs that they don't work)

### What is the problem?
https://github.com/ray-project/ray/blob/4caa6c6d7806d1e406322bfb50fa01072f63985e/python/ray/tune/sample.py#L317-L320

In `tune.sample_from` we have a check to see if the passed callable has either 0 or 1 arguments. This fails for `functools.partial` and callables that have argument with default values. 

### Reproduction (REQUIRED)
```python
# untested; you get the idea
from ray import tune


def trainable(config):
    return config["a"]

def get_a(spec, base=2):
    return base/(spec.b**2)

config = {
    "b": tune.uniform(0, 10),
    "a": tune.sample_from(get_a),
}
tune.run(trainable, config=config)
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

#### Make `spec` a positional argument
i.e., instruct users to make this their `sample_from` signature:
```python
def func(spec, /, arg, kwarg=None):
    pass
```
then we could change the check to `if len(frozenset(name for name, param in signature(func).parameters.items() if param.kind == Parameter.POSITIONAL_ONLY)) > 1`

pros:
- we get to keep the check

cons:
- seems a little unintuitive for users to be required to do this

#### Remove the check
pros:
- this GH issue is resolved

cons:
- uglier error message is user passes function with an incorrect signature?
    - we can `except NameError` to print a prettier error message

**Comment by krfricke** [comment]
Let's use `sig.bind()` for this as we do for `detect_checkpoint_func` and alike. That way we stay very flexible and still support all kinds of callables.

I pushed a small PR for this, would be great to get your feedback on it.
