### ISSUE TITLE
[Tune] Isolated directory per trial

### ISSUE THREAD

**Issue by rlnsanz** [ray-project/ray#1300]
This is a feature request.

Would be useful if each trial gets its own isolated directory for read/write. The location of this directory should be reported or identifiable so the contents of the directory may be accessed (e.g. to copy the contents of the directory out of that directory). There should be an option to keep or destroy the directory after the trial terminates.

Per trial:
```python
original_dir = os.getcwd()
os.chdir('random unique dir')
f()
os.chdir(original_dir)
```

**Comment by ericl** [comment]
https://github.com/ray-project/ray/pull/1297 fixes this as part of the cleanup
