### ISSUE TITLE
[autoscaler] make placement groups bypass upscaling speed limit.

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#13015]
Currently, placement groups do not bypass the upscaling speed limit, and hence upscaling will be gradual, we should make it happen instantly just like request_resources() and min_workers constraints. 

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
This proposal seems clear to me, but can you provide some context around _why_ we would want to treat placement groups differently than other demands?

**Comment by AmeerHajAli** [comment]
@wuisawesome Tune and Serve asked it becomes instantaneous. Also, in its original design, it was supposed to be instantaneous.
