### ISSUE TITLE
[rllib] Training using A3C results in IndexError

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#1303]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.5.3
- **Exact command to reproduce**: `python3 ./python/ray/rllib/train.py --run A3C --env CartPole-v0`

### Describe the problem

The training script fails due to IndexError. The issue appears to be on line 22 of `rllib/models/misc.py`. The `conv2d()` function calls `x.get_shape()[3]`, but `x.get_shape()` returns `(?, 4)`.

### Source code / logs

[console_output.txt](https://github.com/ray-project/ray/files/1541838/out.txt)

**Comment by ericl** [comment]
This seems to be fixed if you pass `"use_lstm": false` in the config. It looks like we should turn that off by default except for atari?

**Comment by richardliaw** [comment]
Should be fixed.
