### ISSUE TITLE
Ray Tune Output on Spyder? View instead on Ray Tune Dashboard?

### ISSUE THREAD

**Issue by messmor** [ray-project/ray#13060]
When running ray tune in Spyder, the table of output data does not display. Instead, the ouput is: 
```<IPython.core.display.HTML object>```
I've imported the IPython.core.display package, but this output persists. Is there a quick fix to get the output working correctly in spyder? 

Also, if there is no fix, maybe the same output is displayed on Ray Dashboard? How does one find the Tune Log Directory to submit in Ray Dashboard to view experiment results?

**Comment by richardliaw** [comment]
Can you try passing in a `CLIReporter` explicitly to tune.run?

```
from ray.tune import CLIReporter
tune.run(progress_reporter=CLIReporter()

**Comment by messmor** [comment]
Yes, this works perfectly. Thank you!
