### ISSUE TITLE
[Docs] Package reference not showing parameters. 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13066]
### What is the problem?

The Ray docs package reference is now showing `ray.init(*args, **kwargs)` instead of the full list of parameters. Links between master and the last release below. 

This shouldn't necessarily block the 1.2.0 release, but we shouldn't update the latest/stable docs until we fix this. 

Master: https://docs.ray.io/en/master/package-ref.html

Latest: https://docs.ray.io/en/latest/package-ref.html 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sumanthratna** [comment]
I haven't looked into this much but I think sphinx is confused by this decorator:
https://github.com/ray-project/ray/blob/c4e273920f517b18c99fbabca49135dd6e30e683/python/ray/_private/client_mode_hook.py#L35-L47
from c4e273920f517b18c99fbabca49135dd6e30e683

not really sure if there's a workaround... @richardliaw what docs-building package is used? e.g., sphinx, napoleon
