### ISSUE TITLE
[tune] Share dataset memory between workers?

### ISSUE THREAD

**Issue by xuanqing94** [ray-project/ray#13078]
### Describe your feature request

Hi! I would like to thank the developers of ray, it saves me a lot of time writing the boilerplates for research.

One question though, can we share memory (for dataset) between workers in tune? For instance, some ML algorithm like gbdt requires in-memory full data (as opposed to minibatch SGD). My scenario is that the data requires 40G, and I have 8 GPUs but only 250 G RAM. So technically I can't spawn more than 250/40=6 instances. Which is clearly suboptimal.

Wouldn't it be great if we can share dataset memory (cause it is read-only)?

**Comment by richardliaw** [comment]
Awesome to hear! Yeah, if you use `tune.with_parameters` to pass your data to your workers, you will automatically leverage Ray's shared memory object store per node.

**Comment by xuanqing94** [comment]
@richardliaw Thank you! that works.
