### ISSUE TITLE
[CI] Windows CI failure

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#13079]
### What is the problem?

Many Windows CI tests fails with crazy messages like address violation for a while recently. Does anyone know what happen? (or it just because windows CI is very flaky now?)

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
(closing this since we have windows CI issue)
