### ISSUE TITLE
[RLlib] OpenAI Baselines subprocess equivalent

### ISSUE THREAD

**Issue by ava6969** [ray-project/ray#13071]
rllib
### Describe your feature request
In OpenAI baselines i could easily create a vectorized environment that is stepped in parallel using their subproc module, I tried using the vectorized env with rllib but i only see 2 out my cpu is being used. iIdon't know if increasing n_workers in this case would help me accomplish it in this case, as i am currently using n_envs per workers and setting remote worker_envs to true. not sure if this will get me the same effect.

**Comment by sven1977** [comment]
Can you try the `remote_worker_envs=True` setting in your config. This should parallelize vectorized envs via ray.
