### ISSUE TITLE
[Tune] Disable Checkpoints and avoiding checkpoint file clashes on Windows.

### ISSUE THREAD

**Issue by jmrichardson** [ray-project/ray#13084]
Hi, Is it possible to disable checkpointing?  Would like to prevent ray tune from saving state.  I have tried configure_logging=False in ray.init() as well as checkpoint_freq=0 in tune.run but didn't help.  Here is a snip of the errors I am getting:

`Trial Runner checkpointing failed: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\john\\ray_results\\train_2020-12-25_20-53-27\\.tmp_searcher_ckpt' -> 'C:\\Users\\john\\ray_results\\train_2020-12-25_20-53-27\\searcher-state-2020-12-25_20-53-27.pkl'`

I am thinking that the function is fast and the timestamp on the file is by second and because it is parallel it is checkpointing too fast and sees that a file has already been written.

Thanks for any help.

**Comment by richardliaw** [comment]
This should be resolved with #14089
