### ISSUE TITLE
[RFC] Auto update memory / object_store_memory resources

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13110]
Currently, the memory resources are reported as [reserved] / [total]. Users can request reservations via `@ray.remote(memory=xxx)` and so on. However, most users don't specify memory resources in decorators, hence memory is always reported as `0.0 / total`, which is quite confusing.

The proposal is to periodically measure the actual memory usage in the raylet, and set the memory resource availability to `max([reserved], actual) / [total]`. For example:

Suppose a node has 8GB of object store memory, 4GB of which is in use. No memory resources are requested in decorators.
Before: `0.0 GB / 8 GB`
Proposal: `4.0 GB / 8 GB`

Suppose the same node has 6GB of memory reserved in resource decorators:
Before: `6.0 GB / 8 GB`
Proposal: `6.0 GB / 8GB`

This solves two problems:
- memory reporting is more intuitive (no more: why is 0GB being used?)
- resource scheduling can work even if not every task has accurate reservations in its decorator, based on runtime measurements

cc @wuisawesome @pcmoritz

**Comment by robertnishihara** [comment]
@ericl can you clarify what you mean by "reported"? Are you talking about what is shown in the dashboard? Or what is sent in heartbeats?

**Comment by ericl** [comment]
Both: dashboards, local scheduler, and in heartbeats. It would be at the granularity of nodes (you would roll-up memory usage of all workers).

**Comment by robertnishihara** [comment]
And can you say how this reported memory would be used in scheduling decisions? I see how it could be taken into account when assigning a task to a node. What effect would it have in the single-node case? E.g., if you have a machine with 10GB memory. There is a pending task that requests 5GB memory. There is one running task that didn't reserve any memory, but is using 8GB memory. Would the pending task get scheduled or not?

**Comment by ericl** [comment]
It wouldn't get scheduled, because if it did the node would run out of
memory.

**Comment by pcmoritz** [comment]
I think this is a good idea.

This would be (mostly) backwards compatible since a task with requirement memory=0.0 would get scheduled even if there is no available memory, right?

So in the common case where every task has memory=0.0 requirement, this just increases clarity for the user.

**Comment by ericl** [comment]
Yeah, it shouldn't affect scheduling at all unless you're setting the resource annotations explicitly already. I did a bit more investigation and there are a couple open questions that may be important:

for `memory`:
- do we count the memory of idle workers? If not, will this pose any stability issues if idle workers leak memory?

for `object_store_memory`:
- how do we handle scheduling in the case of object spilling?

**Comment by ericl** [comment]
Seems like a P1 for object_store_memory at least, now that we have admission control. Otherwise, users could be confused why their tasks aren't scheduled (due to object store memory pressure).

**Comment by ericl** [comment]
fyi @clarkzinzow this might be a good starter task

**Comment by stephanie-wang** [comment]
FYI, #14094 is related and we will need to report object store memory availability from each node to fix it. So that will bring us partway there.

**Comment by stephanie-wang** [comment]
Yep, my plan is to report how much object store memory is available on each node for new task arguments. So once an object is spilled, it will get released and its size will be automatically added to this available memory.

**Comment by wuisawesome** [comment]
Sounds good! btw, i wonder if there are implications around scheduling behavior here? If a node's memory is over subscribed, can we still schedule tasks to it? (if no, this can have some dangerous deadlock implications)

**Comment by stephanie-wang** [comment]
Hmm yeah. I'll keep the fix for #14094 limited to just spilling back to the node with the most amount of memory available.
