### ISSUE TITLE
[RLlib] SlateQ Missing Documentation and Benchmarks

### ISSUE THREAD

**Issue by michaelzhiluo** [ray-project/ray#13115]
Currently, https://docs.ray.io/en/master/rllib-algorithms.html does not seem to have documentation/benchmarks for SlateQ, an algorithm in `rllib/agents`.

@desktable Thanks for your tremendous contribution to RLlib! Would you have time this month to add such documentation for your SlateQ algorithm? If you're busy, I can take a shot at it.

**Comment by desktable** [comment]
Hi Michael - You are welcome! Unfortunately I do not have time to write
documentation this month. Would be happy to answer any questions via slack!
