### ISSUE TITLE
[Ray] Disk loading Too High

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#13135]
Ray: 1.1.0
Python: 3.7.6
Ubuntu20 in Docker

I'm using ray cluster which has 1 Head with 2 workers in separated nodes. However I had a very strange problem. 
When I use ActorPool to distribute the tasks, By chance, `the server node will hang` and `disk loading is Very high(Write up to 150MBps!!!)`.
![image](https://user-images.githubusercontent.com/1471864/103414931-f026b180-4bba-11eb-8187-92b039723034.png)

And the error log is as follows:

```
File "/usr/local/conda/lib/python3.7/site-packages/ray/util/actor_pool.py", line 91, in map_unordered
   yield self.get_next_unordered()
File "/usr/local/conda/lib/python3.7/site-packages/ray/util/actor_pool.py", line 201, in get_next_unordered
    list(self._future_to_actor), num_returns=1, timeout=timeout)
File "/usr/local/conda/lib/python3.7/site-packages/ray/worker.py", line 1513, in wait
    worker.current_task_id,
File "python/ray/_raylet.pyx", line 1001, in ray._raylet.CoreWorker.wait
File "python/ray/_raylet.pyx", line 148, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: No such file or directory
```

**Comment by rkooo567** [comment]
Is there any way to reproduce this issue? (Maybe you can provide the docker image)?

Also, can you see which folder causes high disk usage?

**Comment by DonYum** [comment]
@rkooo567  It happened 2 times. The first time I accidentally damaged the scene. The 2nd time I get the info as above.
I'm sorry that I can not provide the docker img. However, you can tell me how to operate when it happened again.

**Comment by DonYum** [comment]
@rkooo567  I found #13148 has been closed. But I'm still confused. I added some info. Is it convenient for you to reply again?
Thanks a lot!

**Comment by DonYum** [comment]
@rkooo567  I think it's caused by coredump.
I have submitted a new question #13221.

**Comment by richardliaw** [comment]
(closing this as duplicate)
