### ISSUE TITLE
[RFC] Piping important autoscaler events to driver logs

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13141]
While https://github.com/ray-project/ray/issues/12221 provides users a way to inspect the current autoscaler status, it is still difficult to understand how autoscaling interacts with a running application. One way of solving this is to pipe important autoscaler events to the the driver logs. This includes:
- Scale up / down events.
- Failure events.

my_app.py:
```
ray.init(address="auto")
ray.get([cpu_task.remote() for _ in range(10000)])
print("cpu tasks done")
ray.get([gpu_task.remote() for _ in range(100)])
time.sleep(60)
print("done")
```

```
$ python my_app.py
(autoscaler +0s) Scaling from 10 -> 40 CPUs
(autoscaler +1m30s) Scaling from 40 -> 100 CPUs, reached max worker limit
(autoscaler +2m15s) Error launching 2 nodes (setup failure)
(autoscaler +2m35s) Lost contact with 5 nodes (terminated)
(autoscaler +2m45s) Restarting Ray on 3 nodes (heartbeat timeout)
cpu tasks done
(autoscaler +3m30s) Scaling from 0 -> 2 GPUs, 100 -> 30 CPUs
(autoscaler +5m20s) Scaling from 2 -> 10 GPUs, 30 -> 110 CPUs, reached max worker limit
(autoscaler +10m15s) Scaling from 10 -> 0 GPUs, 110 -> 10 CPUs
done
```

Implementation wise this could piggyback on the existing log monitor by adding a new file type (autoscaler-events.log) that the log monitor tails and sends to the driver similar to how it already sends raylet ERROR messages.

cc @AmeerHajAli @richardliaw

**Comment by richardliaw** [comment]
Nice, this is a good idea; any ideas about how you could toggle it?

**Comment by ericl** [comment]
Hmm, ideally we'd design it so the user doesn't feel like they need to toggle it. For example, throttling the events to avoid spam and being careful to combine multiple events into a single update.

**Comment by wuisawesome** [comment]
Can we just treat `montor.err` like `raylet.err`? i.e. `logger.warning("foo")` -> `monitor.err`, `logger.error("foo")` -> `monitor.out`.

**Comment by ericl** [comment]
One difference here is we want to surface important events that aren't
necessarily errors to the user as well, to provide better feedback about
system behavior.
