### ISSUE TITLE
Use -Wextra for compiling C++ sources

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1314]
Currently only C code files (which we mostly got rid of) are compiled with -Wextra, see

https://github.com/ray-project/ray/blob/d6062ef8f6f4171d2f2ab1d4deb53fbd82fa68c2/src/common/cmake/Common.cmake#L36

However we should compile all source files with -Wextra and add the flag here:

https://github.com/ray-project/ray/blob/d6062ef8f6f4171d2f2ab1d4deb53fbd82fa68c2/src/common/cmake/Common.cmake#L6

There are a few errors that currently prevent this, this should be fixed.

**Comment by edoakes** [comment]
Automatically closing stale issue.
