### ISSUE TITLE
[Ray] What's the Idle Acor for?

### ISSUE THREAD

**Issue by DonYum** [ray-project/ray#13148]
Ray: 1.1.0
Python: 3.7.6
Ubuntu20 in Docker

I'm using ray cluster which has 1 Head with 2 workers in separated nodes. Total CPU num is 16*3=48, and I start 42 Actors to a ActorPool: `pool = ActorPool([SelfDefActor.remote(buf) for _ in range(CPU_NUM-6)])`

However, When I use `pool.map()` to start actors, I saw 53 workers in Ray board, And some of them are IDEL status:

![image](https://user-images.githubusercontent.com/1471864/103436538-96c09000-4c57-11eb-8002-b40b2cccc0c7.png)

Is there Anyone can explain this?

**Comment by rkooo567** [comment]
IDLE actors mean that the given actor is not executing any actor methods.

**Comment by DonYum** [comment]
@rkooo567 
Why are there extra actors? I start `42 actors`, but I saw `53 workers`!
Thanks a lot.

**Comment by rkooo567** [comment]
Oh sorry. I will reply very soon
