### ISSUE TITLE
[Tune] RuntimeError: CUDA error: invalid device ordinal                                                                                                              

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#13149]
Ray version 1.2.0.dev0

Error:
`RuntimeError: CUDA error: invalid device ordinal`

Running on AWS server with 4 GPUs (instance type p3.8xlarge)

Fails on this code block:
```
gpu_device_pool = os.environ['CUDA_VISIBLE_DEVICES'].split(",")
    for idx, (key, model) in enumerate(models_container_dict.items()):
        selected_gpu = gpu_device_pool[idx % len(gpu_device_pool)]
        print("Selected GPU")
        print(selected_gpu)
        model.to(torch.device(f"cuda:{selected_gpu}"))
```

YAML:
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: richard_cluster_gpu_4x

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 0

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 40

# The initial number of worker nodes to launch in addition to the head
# node. When the cluster is first brought up (or when it is refreshed with a
# subsequent `ray up`) this number of nodes will be started.
initial_workers: 2

# Whether or not to autoscale aggressively. If this is enabled, if at any point
#   we would start more workers, we start at least enough to bring us to
#   initial_workers.
autoscaling_mode: default

# This executes all commands on all nodes in the docker efcontainer,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
  image: "richardrl/minimum_tmp:latest" # e.g., tensorflow/tensorflow:1.5.0-py3
  container_name: "minimum_tmp" # e.g. ray_docker
  # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
  # if no cached version is present.
  pull_before_run: True
  run_options: []
#    - $([ -d /proc/driver ] && echo -n --runtime-nvidia) # Use the nvidia runtime only if nvidia gpu's are installed
  worker_run_options:
    - --runtime=nvidia  # Extra options to pass into "docker run"

  # Example of running a GPU head with CPU workers
  # head_image: "tensorflow/tensorflow:1.13.1-py3"
  # head_run_options:
  #     - --runtime=nvidia

  # worker_image: "ubuntu:18.04"
  # worker_run_options: []

# The autoscaler will scale up the cluster to this target fraction of resource
# usage. For example, if a cluster of 10 nodes is 100% busy and
# target_utilization is 0.8, it would resize the cluster to 13. This fraction
# can be decreased to increase the aggressiveness of upscaling.
# This value must be less than 1.0 for scaling to happen.
target_utilization_fraction: 0.8

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 30

# Cloud-provider specific configuration.
provider:
  type: aws
  region: us-east-1
  # Availability zone(s), comma-separated, that nodes may be launched in.
  # Nodes are currently spread between zones by a round-robin approach,
  # however this implementation detail should not be relied upon.
  availability_zone: us-east-1a, us-east-1b
  cache_stopped_nodes: False

# How Ray will authenticate with newly launched nodes.
auth:
  ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below.
#    ssh_private_key: /path/to/your/key.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
head_node:
  InstanceType: c4.2xlarge
  ImageId: ami-043f9aeaf108ebc37 # Deep Learning AMI (Ubuntu) Version 24.3
#   You can provision additional disk space with a conf as follows
  BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        VolumeSize: 4000

  # Additional options in the boto docs.

# Provider-specific config for worker nodes, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
worker_nodes:
  InstanceType: p3.8xlarge
  ImageId: ami-043f9aeaf108ebc37 # Deep Learning AMI (Ubuntu) Version 24.3

  # Run workers on spot by default. Comment this out to use on-demand.
  InstanceMarketOptions:
    MarketType: spot
    # Additional options can be found in the boto docs, e.g.
    #   SpotOptions:
    #       MaxPrice: MAX_HOURLY_PRICE
  BlockDeviceMappings:
    - DeviceName: /dev/sda1
      Ebs:
        VolumeSize: 4000
  # Additional options in the boto docs.

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
  "/home/ubuntu/tmp_code": "~/improbable/tmp_code",
}

rsync_exclude:
  - "out/"
  - ".git/"
  - "tmp/vr/logs/"
  - "histograms/"
  - "hyperparam_configs/.git/"
  - "test2"
  - "tmp/dataloader_pkls/"


# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up nodes.
setup_commands:
  # Note: if you're developing Ray, you probably want to create an AMI that
  # has your Ray repo pre-cloned. Then, you can replace the pip installs
  # below with a git checkout <your_sha> (and possibly a recompile).
#  - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux1_x86_64.whl
  - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.2.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip install ray[tune]
  - pip install -e /home/ubuntu/tmp_code
  - pip install wandb
  # Consider uncommenting these if you also want to run apt-get commands during setup
  # - sudo pkill -9 apt-get || true
  # - sudo pkill -9 dpkg || true
  # - sudo dpkg --configure -a

# Custom commands that will be run on the head node after common setup.
head_setup_commands:
  - pip install boto3  # 1.4.8 adds InstanceMarketOptions

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
  - pip install boto3  # 1.4.8 adds InstanceMarketOptions

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
  - ray stop
  - ray stop --force
  - ulimit -n 65536; ray start --num-cpus=0 --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  - ray stop
  - ray stop --force
  - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

**Comment by richardrl** [comment]
@richardliaw

**Comment by amogkam** [comment]
@richardrl could you post the full code and the full stack trace please. Thanks.

**Comment by amogkam** [comment]
Hi @richardrl just want to follow up here. Did the issue get resolved? If not, I'm more than happy to look into it if you could provide a reproducible example and more info about the full stack trace. Thanks!

**Comment by amogkam** [comment]
Hey @richardrl I'm going to close this due to inactivity. If this is still an issue, please feel free to reopen it and I can take a look.

**Comment by wwj-2017-1117** [comment]
I also meet an same question , the code as follow:
cat demo.py

import ray
import os
import subprocess
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import time

# 设置 CUDA 可见性 , 还是不行
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
# 定义一个 Ray 远程任务
@ray.remote(num_gpus=1)
def run_allreduce_on_node(master_ip, world_size, rank , data_sizes, gpus_per_node):
    # 设置环境变量
    os.environ['MASTER_ADDR'] = master_ip
    os.environ['MASTER_PORT'] = '8899'
    os.environ['WORLD_SIZE'] = str(world_size)
    os.environ['RANK'] = str(rank)    
    os.environ['LOCAL_RANK'] = local_rank = str(rank % gpus_per_node)

    # 运行 allreduce_test 函数
    allreduce_test(local_rank , rank, world_size , data_sizes)

def allreduce_test(local_rank , rank, world_size, data_sizes):
    
    # 1.初始化分布式环境
    dist.init_process_group(backend='gloo', init_method='env://', world_size=world_size, rank=rank)
    device = f'cuda:{local_rank}'
    print(f"local_rank={local_rank} rank={rank}  device={device} word_size={world_size}")


    # 2.预热阶段
    torch.cuda.set_device(device) # RuntimeError: CUDA error: invalid device ordinal
    warmup_tensor = torch.tensor([1.0] * 2* 1024 * 1024, device=device)  # 2M 个数据 , 大小则是 2M * 4B = 8MB
    dist.barrier()
    dist.all_reduce(warmup_tensor, op=dist.ReduceOp.SUM)
    print(f"rank {rank} - Warmup completed")


    # 3. 正式阶段    
    for size in data_sizes:
        dist.barrier()  # 同步所有节点
        start_time = time.perf_counter()  # 单位是秒(s)
        tensor = torch.tensor([1.0] * size, dtype=torch.float32 , device=device)
        dist.all_reduce(tensor , op=dist.ReduceOp.SUM) 
        elapsed_time = time.perf_counter() - start_time   # delta 单位是秒(s)
        bandwidth = 2 * size * (world_size - 1) / world_size / (elapsed_time ) / 1024**3   # 带宽单位为 GB/s
        print(f"rank {rank} data-size: {size/(1024*1024)}(MB) allReduce-time: {elapsed_time:.4f}(s) BW: {bandwidth:.2f}GB/s")

    dist.destroy_process_group()

def main(master_ip, num_nodes, gpus_per_node , data_sizes):
    # 初始化 Ray
    ray.init(address='auto')

    # 计算总的世界大小
    world_size = num_nodes * gpus_per_node
    world_size =2
    # 启动所有节点上的 allreduce 测试
    tasks = []
    for rank in range(world_size):
        tasks.append(run_allreduce_on_node.remote(master_ip, world_size, rank , data_sizes , gpus_per_node))

    # 等待所有任务完成
    ray.get(tasks)

    # 等待所有任务完成，使用 ray.wait 进行异步处理
    
    # 关闭 Ray
    ray.shutdown()

if __name__ == "__main__":
    master_ip = '0.0.0.0'  # 主节点的 IP 地址
    num_nodes = 1  # 节点数量
    gpus_per_node = 2 # 每个节点的 GPU 数量
    data_sizes = [1* 1024 * 1024, 2 * 1024 * 1024, 4 * 1024 * 1024, 8 * 1024 * 1024]  # 不同的数据量 1MB, 2MB, 4MB, 8MB
    
    gpu_number = torch.cuda.device_count()
    if gpus_per_node != gpu_number:
        print("The number of GPUs on each node must be the same as the number of GPUs on the master node.")
        print(f"gpus_per_node: {gpus_per_node}, gpu_number: {gpu_number}")
        exit(1)
    main(master_ip, num_nodes, gpus_per_node , data_sizes)


python demo.py


  File "/work/demo.py", line 23, in run_allreduce_on_node
    allreduce_test(local_rank , rank, world_size , data_sizes)
  File "/work/demo.py", line 34, in allreduce_test
    torch.cuda.set_device(device) # RuntimeError: CUDA error: invalid device ordinal
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(run_allreduce_on_node pid=1190) local_rank=1 rank=1  device=cuda:1 word_size=2
(run_allreduce_on_node pid=1166) local_rank=0 rank=0  device=cuda:0 word_size=2
