### ISSUE TITLE
RAY_PDB toggle causes actor died message

### ISSUE THREAD

**Issue by sahewat** [ray-project/ray#13144]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS): **Python 3.7, ray 1.2 nightly (have also reproduced w/ same issue on 1.1 release)**

@richardliaw I have ray set up on a GCP cluster using the instructions provided in the latest docs.
I’m having problems with ray SGD dying after throwing the error:
```
File "/opt/conda/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 266, in __init__
    self._start_workers(self.max_replicas)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 326, in _start_workers
    self.worker_group.start_workers(num_workers)
  File "/opt/conda/lib/python3.7/site-packages/ray/util/sgd/torch/worker_group.py", line 231, in start_workers
    ray.get(self._setup_operator())
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1395, in get
    raise value
```
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.

I’ve investigated the `/tmp/ray/logs/latest_run/python-core-worker*.log` files on the worker and see the attached output [out.txt](https://github.com/ray-project/ray/files/5758394/out.txt)

Strangely, this doesn’t happen as long as I use the `RAY_PDB=1` flag and runs normally.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
import ray
from ray.util.sgd import TorchTrainer
from ray.util.sgd.torch import TrainingOperator
from ray.util.sgd.torch.examples.train_example import LinearDataset

import torch
from torch.utils.data import DataLoader

class CustomTrainingOperator(TrainingOperator):
    def setup(self, config):
        # Load data.
        train_loader = DataLoader(LinearDataset(2, 5), config["batch_size"])
        val_loader = DataLoader(LinearDataset(2, 5), config["batch_size"])

        # Create model.
        model = torch.nn.Linear(1, 1)

        # Create optimizer.
        optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

        # Create loss.
        loss = torch.nn.MSELoss()

        # Register model, optimizer, and loss.
        self.model, self.optimizer, self.criterion = self.register(
            models=model,
            optimizers=optimizer,
            criterion=loss)

        # Register data loaders.
        self.register_data(train_loader=train_loader, validation_loader=val_loader)


ray.init(address='auto')

trainer1 = TorchTrainer(
    training_operator_cls=CustomTrainingOperator,
    num_workers=2,
    use_gpu=True,
    config={"batch_size": 64})

stats = trainer1.train()
print(stats)
trainer1.shutdown()
print("success!")
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@sahewat can you quickly measure roughly how often RAY_PDB=1 fails vs RAY_PDB=0 fails?
