### ISSUE TITLE
[RFC]: Support using external redis

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#13166]
RFC Doc: https://docs.google.com/document/d/1hM6w4FYhfZVOP_CrWY9PNNPDuW_qe5SgPbCIQt3t_M8/edit#heading=h.luwkx6tnsocp

Comments on RFC Doc:
- check redis_max_memory
- add limitation that user should ensure the external redis is empty (clean and not used)
- throw exceptions if the external redis is not empty
- use a more general name like `--external-addresses`

### Describe your feature request

Currently ray starts a local redis instance on the head node. We found that redis can be a bottleneck if we have many actors/remote functions happening.
Support using external redis is a good way to utilize elasticity, which means we can (**optionally**) separate redis away from the head node.

Steps:
- [ ] support external redis address when starting ray processes
- [ ] support redis password for external redis
- [ ] add some tests to make sure functions  are ok
- [ ] check if external redis is connectable (available)
- [ ] check if external redis is being used or has remaining data

See more discussion in Slack thread: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1608350795267400

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
cc @pcmoritz @ericl

**Comment by ericl** [comment]
I'm not sure about this, given that we plan to remove the redis dependency in the future.

**Comment by WangTaoTheTonic** [comment]
> I'm not sure about this, given that we plan to remove the redis dependency in the future.
> 
> Why would an external redis be more scalable? Can't you configure the head node redis similarly?

More scalable: Head node is only one node. No matter how many redis instances on it, they also use same resources(cpu/mem) of only one node.
If we support external redis, the multi redis servers can be deployed on different nodes out of ray cluster.

BTW what's the plan to `remove the redis dependency`? Is it an initial proposal or something already on the schedule?

**Comment by raulchen** [comment]
@ericl This doesn't conflict with "removing redis dependency", we can use a neutral name that refers to "address of GCS's backend storage".
Regarding the motivation of this issue, maybe @rkooo567 can comment more on this. I think he received this requirement from a user on Slack.

**Comment by ericl** [comment]
Hmm I see, it seems reasonable enough, though we should probably document
this as a parameter that may change in the future as the GCS storage
evolves.

**Comment by rkooo567** [comment]
Agree this parameter may change in the future. We can also probably just
make a parameter private. What about things like _remote_gcs_address?

**Comment by WangTaoTheTonic** [comment]
PR https://github.com/ray-project/ray/pull/13170 has been merged. I'm closing this issue. Thanks all.
