### ISSUE TITLE
[Ray] Raylet crashes due to overloaded, is that possible for it to auto-restart on crashes?

### ISSUE THREAD

**Issue by trunghlt** [ray-project/ray#13160]
### What is the problem?

*Ray version: 1.1.0*

We are using Ray for running multiple tasks at different times. When a raylet crashes due to overloaded, is it possible to make it auto-restart so the next tasks don't result in error?

**Comment by rkooo567** [comment]
@ericl Isn't it already supposed to be auto-started?

**Comment by ericl** [comment]
The AutoScaler already restarts it. This issue isn't well specified so I'm going to close it.
