### ISSUE TITLE
Segfault when putting object whose class closes over an ObjectID.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1317]
The following causes a segfault.

```python
import ray

class Foo():
    def __init__(self):
        self.val = ray.put(0)
    def method(self):
        f

ray.init()

f = Foo()

ray.put(f)
```

The error appears to happen when trying to pickle the class `Foo`. We prevent object IDs from being pickled at 

https://github.com/ray-project/ray/blob/b1d89026cdd41d7437972de256eb3371bb3bc5c1/src/common/lib/python/common_extension.cc#L205-L208

However, we never registered `CommonError` with the python extension module. I think that's the problem. Should be fixed by #1316.

**Comment by robertnishihara** [comment]
This bug was found by @devin-petersohn.

@devin-petersohn let us know if this fixes it for you!

**Comment by guoyuhong** [comment]
This bug should be fixed by https://github.com/ray-project/ray/pull/3674 .
