### ISSUE TITLE
1st example given in Search / Key Concepts doesn't converge and this is confusing

### ISSUE THREAD

**Issue by LukeAI** [ray-project/ray#13187]
### What is the problem?

The [first example](https://docs.ray.io/en/master/tune/key-concepts.html#search-algorithms) given in the introductory Key Concepts / Search Algorithms page on Ray Tune doesn’t iteratively converge, it just samples the search space at random. Since the point of using Ray Tune is to discover optimal hyperparameters, this is quite confusing for newcomers (such as myself).

I suggest replacing it with something that, if copied verbatim, will converge on optimal hyperparameters in a quick, obvious, straightforward way. A suggestion could be the below

Although maybe somebody more experienced with Ray could offer something better as
- this causes Ray to give a warning about the uniform search space sampling not making sense for bayes
- naive bayes doesn't work unless done sequentially. so the necessity for a `ConcurrencyLimiter` here is a bit of a curve-ball
- maybe a better/more sophisticated search algorithm (Ax??) should be the suggested default, as most users will probably start out just using whatever they get working from copying and pasting examples from the Docs. (well that's how I work anyway...)

I'm pretty pressed for time right now, but I'm happy to come back to this in the next week or so with a more refined suggestion/example if nobody else has an offering.

@richardliaw FYI

```
def objective(x, a, b):
    return a * (x ** 0.5) + b

def trainable(config):
    for x in range(20):
        score = objective(x, config["a"], config["b"])
        tune.report(score=score)

config = {
    "a": tune.uniform(0, 1),
    "b": tune.uniform(0, 20)
}

# use a simple naive bayes optimizer
opt = BayesOptSearch(metric="score", mode="max")

# by default, Ray will distribute trials across available computing resources
# naive bayes requires trial results sequentially
opt = ConcurrencyLimiter(opt, max_concurrent=1)

tune.run(
    trainable,
    config=config,
    search_alg=opt,
    num_samples=20,
    stop={"training_iteration": 10}
)
```

**Comment by krfricke** [comment]
Thanks @LukeAI for this suggestion.

I'd argue to stay with HyperOpt or another search algorithm that supports a diverse range of configuration spaces. Pure BayesOpt can only be used to optimize float parameters.

HyperOpt should incorporate knowledge from previous trials already, even in the current example. We might want to introduce concurrency limiting here though, as it will always result in basically random search if all trials are run in parallel.

**Comment by LukeAI** [comment]
sure, I have no strong opinions as to what the example should be. I did also try HyperOpt with concurrency limiter and also much greater number of trials and as far as I could tell it was just sampling at random and didn't find a particularly good optimum.
