### ISSUE TITLE
[core] ray.kill pending actor doesn't cancel the actor creation task

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13214]
### What is the problem?

Currently, `ray.kill` will silently fail if the actor has not already been started. This appears to be because we try to kill actors directly (via direct actor transport), but now GCS is responsible for scheduling/creating actors, so the actor's owner can't easily cancel the pending lease request. 

Here's a simple reproduction which shows the lease request is still infeasible in a raylet.

```
import ray
from ray._raylet import GlobalStateAccessor
import time

cluster = ray.init()

global_state_accessor = GlobalStateAccessor(
    cluster["redis_address"], ray.ray_constants.REDIS_DEFAULT_PASSWORD)
global_state_accessor.connect()


@ray.remote(resources={"WORKER": 1.0})
class ActorA:
    pass

a = ActorA.remote()
ray.kill(a) # do not wait until it starts

while True:
    message = global_state_accessor.get_all_resource_usage()
    if message is not None:
        resource_usage = ray.gcs_utils.ResourceUsageBatchData.FromString(
            message)
        print(resource_usage)
    else:
        print(message)
    time.sleep(1)
```

cc @ericl 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @ffbin Do you have some bandwidth to take a look at this task?

**Comment by ffbin** [comment]
> cc @ffbin Do you have some bandwidth to take a look at this task? I think we just need to cancel lease in the raylet queue when actors are killed before it is created

ok, i will take a look, thanks.

**Comment by ffbin** [comment]
https://github.com/ray-project/ray/pull/13254/files @wuisawesome @rkooo567 If ray.kill no_restart is true, we will destroy the actor and cancel the actor creation task. If ray.kill no_restart is false, we will not cancel the actor creation task, because it itself needs to be rescheduled. What's your suggestion?

**Comment by rkooo567** [comment]
Cancel actor creation task => meaning removing a task from the raylet queue? 

If so, don't we need to cancel them in both cases? Rescheduling is handled by GCS anyway

**Comment by ffbin** [comment]
@rkooo567  If ray.kill no_restart is false, we do not need to cancel the actor creation task, because after you cancel actor creation task, you still need to reschedule actor and send actor creation task request to raylet again. If ray.kill no_restart is true, we just need to `DestroyActor` and `DestroyActor` will cancel  actor creation task if actor creation request of this actor id is pending in raylet.

**Comment by wuisawesome** [comment]
> If ray.kill no_restart is true

`no_restart=True` by default and as you can see from the reproduction, the actor creation task isn't being cancelled. Is the reproduction working for you?

**Comment by rkooo567** [comment]
@ffbin I think the confusion is you are thinking about cancelling lease "within a GCS server", and the issue is "cancelling task entry within a raylet".

GCS side metadata is cleaned properly whereas the raylet side is not based on Alex's reproduction script.

**Comment by ffbin** [comment]
> > If ray.kill no_restart is true
> 
> `no_restart=True` by default and as you can see from the reproduction, the actor creation task isn't being cancelled. Is the reproduction working for you?

Yeah, the reproduction is working, thx.

**Comment by ffbin** [comment]
> @ffbin I think the confusion is you are thinking about cancelling lease "within a GCS server", and the issue is "cancelling task entry within a raylet".
> 
> GCS side metadata is cleaned properly whereas the raylet side is not based on Alex's reproduction script.

![image](https://user-images.githubusercontent.com/13081808/103964808-4dac9680-5197-11eb-85dd-12656ca67df4.png)
The gcs actor manager `DestroyActor` will cancel the lease request in raylet.

**Comment by ffbin** [comment]
@rkooo567 https://github.com/ray-project/ray/pull/13254 Do you think this plan is feasible?

**Comment by rkooo567** [comment]
Hmm I feel like the issue should be irrelevant to no_restart. When you run Alex's reproduction on your PR, does it pass?

I feel like what we need is just to call cancel lease request RPC in `CancelOnLeasing`.

**Comment by ffbin** [comment]
> Hmm I feel like the issue should be irrelevant to no_restart. When you run Alex's reproduction on your PR, does it pass?
> 
> I feel like what we need is just to call cancel lease request RPC in `CancelOnLeasing`.

We don't know the state of the actor, so it's better to call `DestroyActor`. I will add Alex's reproduction  to the test case, and I will ping you to review it after PR is finished, thx.

**Comment by rkooo567** [comment]
I think I am still confused. Can you show me the output of running Alex's script with no_restart True and False?

**Comment by ffbin** [comment]
`running Alex's script with no_restart True`
batch {
  node_id: "\311\020\247\235uQ\205>\243\365\024\025\010\3310[\365\002SI\245\355\354m\342\3150\006"
  resources_available {
    key: "CPU"
    value: 8.0
  }
  resources_available {
    key: "memory"
    value: 94.0
  }
  resources_available {
    key: "node:30.52.220.53"
    value: 1.0
  }
  resources_available {
    key: "object_store_memory"
    value: 32.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 8.0
  }
  resources_total {
    key: "memory"
    value: 94.0
  }
  resources_total {
    key: "node:30.52.220.53"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 32.0
  }
  resource_load {
    key: "CPU"
    value: 1.0
  }
  resource_load {
    key: "WORKER"
    value: 1.0
  }
  resource_load_changed: true
  resource_load_by_shape {
    resource_demands {
      shape {
        key: "CPU"
        value: 1.0
      }
      shape {
        key: "WORKER"
        value: 1.0
      }
      num_infeasible_requests_queued: 1
    }
  }
}
resource_load_by_shape {
  resource_demands {
    shape {
      key: "CPU"
      value: 1.0
    }
    shape {
      key: "WORKER"
      value: 1.0
    }
    num_infeasible_requests_queued: 1
  }
}
placement_group_load {
}

**Comment by ffbin** [comment]
`running Alex's script with no_restart False`
batch {
  node_id: "\270\251D\320\031\337\271\203>\363+B9\301\330n\035\326\274\215k\255)\333\301\032t\324"
  resources_available {
    key: "CPU"
    value: 8.0
  }
  resources_available {
    key: "memory"
    value: 96.0
  }
  resources_available {
    key: "node:30.52.220.53"
    value: 1.0
  }
  resources_available {
    key: "object_store_memory"
    value: 33.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 8.0
  }
  resources_total {
    key: "memory"
    value: 96.0
  }
  resources_total {
    key: "node:30.52.220.53"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 33.0
  }
  resource_load {
    key: "CPU"
    value: 1.0
  }
  resource_load {
    key: "WORKER"
    value: 1.0
  }
  resource_load_changed: true
  resource_load_by_shape {
    resource_demands {
      shape {
        key: "CPU"
        value: 1.0
      }
      shape {
        key: "WORKER"
        value: 1.0
      }
      num_infeasible_requests_queued: 1
    }
  }
}
resource_load_by_shape {
  resource_demands {
    shape {
      key: "CPU"
      value: 1.0
    }
    shape {
      key: "WORKER"
      value: 1.0
    }
    num_infeasible_requests_queued: 1
  }
}
placement_group_load {
}

**Comment by ffbin** [comment]
@rkooo567 Do you expect `num_infeasible_requests_queued` to be 0?

**Comment by ffbin** [comment]
I call `lease_client->CancelWorkerLease` in gcs actor scheduler and it will cancel actor creation request.
`running Alex's script with no_restart True`:
batch {
  node_id: "\206\363\344\377<3^\350y\'s\250\264x\214+\035\010<Us\177\255\323\362\"\035H"
  resources_available {
    key: "CPU"
    value: 8.0
  }
  resources_available {
    key: "memory"
    value: 99.0
  }
  resources_available {
    key: "node:10.15.246.254"
    value: 1.0
  }
  resources_available {
    key: "object_store_memory"
    value: 34.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 8.0
  }
  resources_total {
    key: "memory"
    value: 99.0
  }
  resources_total {
    key: "node:10.15.246.254"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 34.0
  }
  resource_load_changed: true
  resource_load_by_shape {
  }
}
placement_group_load {
}
`running Alex's script with no_restart False`:
batch {
  node_id: "\273\315\313K\234\272X\264\014xE0\020\006Y\333\367\313^\013\264\324\303#\343\030z\342"
  resources_available {
    key: "CPU"
    value: 8.0
  }
  resources_available {
    key: "memory"
    value: 95.0
  }
  resources_available {
    key: "node:10.15.246.254"
    value: 1.0
  }
  resources_available {
    key: "object_store_memory"
    value: 33.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 8.0
  }
  resources_total {
    key: "memory"
    value: 95.0
  }
  resources_total {
    key: "node:10.15.246.254"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 33.0
  }
  resource_load {
    key: "CPU"
    value: 1.0
  }
  resource_load {
    key: "WORKER"
    value: 1.0
  }
  resource_load_changed: true
  resource_load_by_shape {
    resource_demands {
      shape {
        key: "CPU"
        value: 1.0
      }
      shape {
        key: "WORKER"
        value: 1.0
      }
      num_infeasible_requests_queued: 1
    }
  }
}
resource_load_by_shape {
  resource_demands {
    shape {
      key: "CPU"
      value: 1.0
    }
    shape {
      key: "WORKER"
      value: 1.0
    }
    num_infeasible_requests_queued: 1
  }
}
placement_group_load {
}

**Comment by wuisawesome** [comment]
Yes, I think the version with `lease_client->CancelWorkerLease` looks right.
