### ISSUE TITLE
Pytest with xdist consistently fails on Windows when more than one worker is used

### ISSUE THREAD

**Issue by gshimansky** [ray-project/ray#13213]
### What is the problem?

Running Modin tests with `xdist` on Windows is impossible because 2nd and consequent workers fail to connect to Redis. Problem is reproducible in [GitHub Actions environment](https://github.com/modin-project/modin/pull/2558/checks?check_run_id=1652259815#step:5:17) and locally on my laptop.
<details><pre>
> python -m pytest -n 2 modin/pandas/test/dataframe/test_binary.py
PytestBenchmarkWarning: Benchmarks are automatically disabled because xdist plugin is active.Benchmarks cannot be performed reliably in a parallelized environment.
======================================================================================================= test session starts ========================================================================================================
platform win32 -- Python 3.7.7, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: C:\Users\gashiman\OneDrive - Intel Corporation\work\modin, configfile: setup.cfg
plugins: benchmark-3.2.3, cov-2.10.1, custom-exit-code-0.3.0, forked-1.1.3, xdist-2.2.0
gw0 ok / gw1 [0][gw0] node down: Not properly terminated

replacing crashed worker gw0
gw2 [225] / gw1 [0]
collecting 0 items / 2 errors
============================================================================================================== ERRORS ==============================================================================================================
___________________________________________________________________________________ ERROR collecting modin/pandas/test/dataframe/test_binary.py ____________________________________________________________________________________
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\_private\services.py:640: in wait_for_redis_to_start
    redis_client.client_list()
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\client.py:1194: in client_list
    return self.execute_command('CLIENT LIST')
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\client.py:898: in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\connection.py:1192: in get_connection
    connection.connect()
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\connection.py:567: in connect
    self.on_connect()
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\connection.py:643: in on_connect
    auth_response = self.read_response()
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\connection.py:739: in read_response
    response = self._parser.read_response()
..\..\..\AppData\Roaming\Python\Python37\site-packages\redis\connection.py:484: in read_response
    raise response
E   redis.exceptions.AuthenticationError: invalid password

The above exception was the direct cause of the following exception:
C:\Program Files\Python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:953: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:728: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
modin\pandas\__init__.py:180: in <module>
    Engine.subscribe(_update_engine)
modin\config\pubsub.py:107: in subscribe
    callback(cls)
modin\pandas\__init__.py:119: in _update_engine
    initialize_ray()
modin\engines\ray\utils.py:149: in initialize_ray
    _lru_evict=True,
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\worker.py:722: in init
    ray_params=ray_params)
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\node.py:216: in __init__
    self.start_head_processes()
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\node.py:767: in start_head_processes
    self.start_redis()
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\node.py:597: in start_redis
    fate_share=self.kernel_fate_share)
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\_private\services.py:843: in start_redis
    fate_share=fate_share)
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\_private\services.py:989: in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
..\..\..\AppData\Roaming\Python\Python37\site-packages\ray\_private\services.py:651: in wait_for_redis_to_start
    redis_ip_address, redis_port)) from authEx
E   RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.
_______________________________________________________________________________________________________ ERROR collecting gw2 _______________________________________________________________________________________________________
Different tests were collected between gw1 and gw2. The difference is:
--- gw1

+++ gw2

@@ -0,0 +1,225 @@
</pre></details>

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray version 1.1.0, Python 3.7.7, Windows 10 x64 1909.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by pyrito** [comment]
What's the status of this issue? We're still seeing some CI errors with this.

**Comment by anyscalesam** [comment]
@pyrito < believe this should be resolved; if you are you still seeing CI errors on ray28 can you pop them here so we can take a look at it?
