### ISSUE TITLE
PolicyServerInput with num_workers = 1 will have AttributeError

### ISSUE THREAD

**Issue by herunyu** [ray-project/ray#13227]
### What is the problem?

PolicyServerInput with num_workers = 1 will have AttributeError

*Ray version and other system information (Python version, TensorFlow version, OS):*
* ray: 1.1.0
* python: 3.8.5
* tensorflow:  2.3.1
* OS: macOS 11.1 or Ubuntu 20.04.1 LTS

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
env = "CartPole-v0"
    connector_config = {
        # Use the connector server to generate experiences.
        "input": (
            lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)
        ),
        # Use a single worker process to run the server.
        "num_workers": 1,
        # Disable OPE, since the rollouts are coming from online clients.
        "input_evaluation": [],
    }

trainer = PPOTrainer(
            env=env,
            config=dict(
                connector_config, **{
                    "rollout_fragment_length": 1000,
                    "train_batch_size": 4000,
                    "framework": args.framework,
                }))

checkpoint_path = CHECKPOINT_FILE.format(args.run)

    # Attempt to restore from checkpoint if possible.
    if os.path.exists(checkpoint_path):
        checkpoint_path = open(checkpoint_path).read()
        print("Restoring from checkpoint path", checkpoint_path)
        trainer.restore(checkpoint_path)

    # Serving and training loop
    while True:
        print(pretty_print(trainer.train()))
        checkpoint = trainer.save()
        print("Last checkpoint", checkpoint)
        with open(checkpoint_path, "w") as f:
            f.write(checkpoint)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

When I set num_workers to 1 it will give an AttributeError as follow:

---

WARNING:tensorflow:From /Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-01-06 14:09:10,810 INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
2021-01-06 14:09:12,882 INFO trainer.py:591 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-01-06 14:09:12,883 INFO trainer.py:616 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=49831) WARNING:tensorflow:From /Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=49831) Instructions for updating:
(pid=49831) non-resource variables are not supported in the long term
(pid=49831) 2021-01-06 14:09:19,552     INFO policy_server_input.py:89 -- 
(pid=49831) 2021-01-06 14:09:19,552     INFO policy_server_input.py:90 -- Starting connector server at localhost:9900
(pid=49831) 2021-01-06 14:09:19,552     INFO policy_server_input.py:91 -- 
Traceback (most recent call last):
  File "cartpole_server.py", line 54, in <module>
    trainer = PPOTrainer(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 106, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 465, in __init__
    super().__init__(config, logger_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable.py", line 96, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 629, in setup
    self._init(self.config, self.env_creator)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 133, in _init
    self.workers = self._make_workers(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 700, in _make_workers
    return WorkerSet(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 87, in __init__
    self._local_worker = self._make_worker(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 315, in _make_worker
    worker = cls(
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 607, in __init__
    self.input_reader: InputReader = input_creator(self.io_context)
  File "cartpole_server.py", line 34, in <lambda>
    lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)
  File "/Users/hyt/miniconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/env/policy_server_input.py", line 84, in __init__
    self.rollout_worker.sampler.get_metrics = get_metrics
AttributeError: 'NoneType' object has no attribute 'get_metrics'

**Comment by ericl** [comment]
@sven1977 can you take a look?

**Comment by sven1977** [comment]
Thanks for filing this issue @herunyu ! I can reproduce this. However, I'm not sure what the purpose of rollout workers (num_workers > 0), would be here. The server process is basically the learner (local_worker) and the client(s) are the rollout workers.
Sure, you could argue that you need a mixed setup with some rollout workers remote and others running on the server side.

Either way, you can fix this error by setting `"create_env_on_driver": True` in your Trainer's config. This will make sure that a Sampler object (with environment) is created either way on the local worker (driver) no matter whether you set num_workers >0 or not.

**Comment by herunyu** [comment]
Oh I see. I thought that if I can make multiple servers I can utilize the power of ray to train the model in parallel. According to what you said, it doesn’t really matter if using 1 num workers or more than 1, am I right? Does that mean that I cannot use parallelism to train the model?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sven Mika <notifications@github.com>
发送时间: Saturday, January 9, 2021 8:11:31 PM
收件人: ray-project/ray <ray@noreply.github.com>
抄送: Runyu He <herunyu@berkeley.edu>; Mention <mention@noreply.github.com>
主题: Re: [ray-project/ray] PolicyServerInput with num_workers = 1 will have AttributeError (#13227)


Thanks for filing this issue @herunyu<https://github.com/herunyu> ! I can reproduce this. However, I'm not sure what the purpose of rollout workers (num_workers > 0), would be here. The server process is basically the learner (local_worker) and the client(s) are the rollout workers.
Sure, you could argue that you need a mixed setup with some rollout workers remote and others running on the server side.

Either way, you can fix this error by setting "create_env_on_driver": True in your Trainer's config. This will make sure that a Sampler object (with environment) is created either way on the local worker (driver) no matter whether you set num_workers >0 or not.

―

**Comment by herunyu** [comment]
@sven1977 Would you mind taking a few minutes to take a look at my question？Really appreciated it!
