### ISSUE TITLE
[dashboard][core] Running ray memory yields reference types inconsistent with master/memory-management.html

### ISSUE THREAD

**Issue by micahtyong** [ray-project/ray#13231]
### What is the problem?

Upon running `ray memory` in the command line while a Ray application is running, yielded reference types are inconsistent with what is described in [the docs](https://docs.ray.io/en/latest/memory-management.html#debugging-using-ray-memory). In multiple instances, the reference type is incorrectly denoted as `ACTOR_HANDLE`. 

*Ray version and other system information (Python version, TensorFlow version, OS):* 
- Ray 1.2.0
- Python 3.6.8
- TensorFlow 2.4.0
- macOS 10.14.6

### Reproduction (REQUIRED)

1. Create a mock Ray application using an example from [the docs](https://docs.ray.io/en/latest/memory-management.html#debugging-using-ray-memory).  
For example,
```
import ray
import time
ray.init()

@ray.remote
def f(arg):
    return arg

a = ray.put(None)
b = f.remote(None)

time.sleep(100)
```
2. Run the application, then run `ray memory`
3. At this point, you should see results that are inconsistent with what is in the documentation as described above. 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
```
At this point, you should see results that are inconsistent with what is in the documentation as described above. (EDIT: The beta introduction of object spilling has created an issue where ray memory will break entirely and yield AttributeError: store_stats).
```
This might be because you didn't rebuild the core after you pull the latest master. Is it reproducible when you use ray by downloading the master wheel?

**Comment by micahtyong** [comment]
You're right, just edited the PR!
