### ISSUE TITLE
Question: Redis failed to start on AWS server

### ISSUE THREAD

**Issue by Wanda-Sankey** [ray-project/ray#13239]
I am having an issue where I run a nextflow process on an AWS server that calls a Ray instance. I get the error message "Redis failed to start" however the process seems to complete without issue and the output file generates. I was wondering if this is a permission issue on AWS nodes and if Redis is required for use of Ray?

**Comment by rkooo567** [comment]
Redis is used as a central metadata store of Ray (called GCS), and it is automatically started when you start a head node. 

Can you see if there are logs from /tmp/ray/session_latest/logs/redis.out|err?

**Comment by Wanda-Sankey** [comment]
Redis.err is empty. Redis.out has the following text: 

`28605:C 10 Dec 2020 15:27:48.216 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
28605:C 10 Dec 2020 15:27:48.216 # Redis version=5.0.9, bits=64, commit=00000000, modified=0, pid=28605, just started
28605:C 10 Dec 2020 15:27:48.216 # Configuration loaded
28605:M 10 Dec 2020 15:27:48.217 # Server initialized
28605:M 10 Dec 2020 15:27:48.217 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
28605:M 10 Dec 2020 15:27:48.217 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
28605:signal-handler (1607614070) Received SIGTERM scheduling shutdown...
28605:M 10 Dec 2020 15:27:50.458 # User requested shutdown...
28605:M 10 Dec 2020 15:27:50.458 # Redis is now ready to exit, bye bye...
`

**Comment by rkooo567** [comment]
Where did you get the redis failed to start? I cannot see any issue from the log messages.

**Comment by rkooo567** [comment]
Also, can you explain more details about your deployment setup?

**Comment by rkooo567** [comment]
redis is removed from ray master.
