### ISSUE TITLE
[releaser] Release test dependencies not being properly installed. 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13249]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

When running the releaser `python cli.py suite:run long_running_tests`, the rllib/tune related tests seem to fail due to dependency issues. Attached is the output of the impala test.
[ray_command_output_scd_2vJnlEdLvBs7qUzYy3Y1vt.txt](https://github.com/ray-project/ray/files/5778898/ray_command_output_scd_2vJnlEdLvBs7qUzYy3Y1vt.txt)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
```
  File "/root/anaconda3/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by ijrsvt** [comment]
Are these running on `ray` or `ray-ml` docker images?

**Comment by simon-mo** [comment]
ok i think the error was that we because we were using ray instead of ray-ml

https://github.com/ray-project/ray/blob/master/release/long_running_tests/cluster.yaml#L4
