### ISSUE TITLE
`ray status` and `ray memory` shouldn't need to start a new job

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13250]
### Describe your feature request

Because we have a limited number of job ids, running `watch -n 1 ray memory` (arguably the intended use case of the command), we will run out of job ids in ~18 hours. 

We can get all the information we need using `GlobalStateAccessor` without calling `ray.init`. 

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

cc @ericl

**Comment by rkooo567** [comment]
cc @micahtyong Are you interested in doing this?

**Comment by micahtyong** [comment]
Sure, I'm happy to take a look!
