### ISSUE TITLE
Issue on page /tune/user-guide.html

### ISSUE THREAD

**Issue by edwinytgoh** [ray-project/ray#13299]
Under the Checkpointing section in the Tune user guide (https://docs.ray.io/en/master/tune/user-guide.html#checkpointing), the example code block contains `for iter in range(start, 100):`, and `with tune.checkpoint_dir(step=step)`. 

Should it be `for step in range(start, 100)` instead?

**Comment by richardliaw** [comment]
yeah! that sounds right. Would you be willing to push a fix?
