### ISSUE TITLE
[tune] Trial Runner checkpointing failed: [WinError 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by ptyshevs** [ray-project/ray#13290]
### What is the problem?

Using `OptunaSearch` I receive the warning in the title, which looks something like this:
![image](https://user-images.githubusercontent.com/9576353/103991891-64a5b580-51a4-11eb-8865-b9464e855a38.png)

The code in reproduction section looks something like this:
![image](https://user-images.githubusercontent.com/9576353/103991969-81da8400-51a4-11eb-8291-cb4528483afd.png)

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray v1.1.0
python 3.8.3
OS: Windows 10 v.20H2

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

(Warning: you need to have optuna installed)

```python3
import ray
from ray import tune
import numpy as np
import os
import json
from ray.tune.suggest.optuna import OptunaSearch

ray.init(include_dashboard=False)

class MyTrainableClass(tune.Trainable):
    """Example agent whose learning curve is a random sigmoid.

    The dummy hyperparameters "width" and "height" determine the slope and
    maximum reward value reached.
    """

    def setup(self, config):
        self.timestep = 0

    def step(self):
        self.timestep += 1
        v = np.tanh(float(self.timestep) / self.config.get("width", 1))
        v *= self.config.get("height", 1)

        # Here we use `episode_reward_mean`, but you can also report other
        # objectives such as loss or accuracy.
        return {"episode_reward_mean": v}

    def save_checkpoint(self, checkpoint_dir):
        path = os.path.join(checkpoint_dir, "checkpoint")
        with open(path, "w") as f:
            f.write(json.dumps({"timestep": self.timestep}))
        return path

    def load_checkpoint(self, checkpoint_path):
        with open(checkpoint_path) as f:
            self.timestep = json.loads(f.read())["timestep"]
            
analysis = tune.run(
        MyTrainableClass,
        name="optuna_search",
        num_samples=20,
        metric="episode_reward_mean",
        mode="max",
        stop={"training_iteration": 1},
        config={
            "width": tune.randint(10, 90),
            "height": tune.randint(0, 100)
        },
        search_alg=OptunaSearch(),
        checkpoint_freq=1,
        fail_fast=True)

print("Best hyperparameters found were: ", analysis.best_config)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [+] I have verified my script runs in a clean environment and reproduces the issue.
- [-] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Quentin-M** [comment]
https://github.com/ray-project/ray/pull/14089

**Comment by diman82** [comment]
I can confirm, that I get the same error for ray 1.2.0

**Comment by richardliaw** [comment]
@diman82 @ptyshevs could you try the latest ray wheels?

**Comment by ptyshevs** [comment]
@richardliaw sorry, I don't have access to that environment now.

**Comment by richardliaw** [comment]
Closed by https://github.com/ray-project/ray/pull/14089 -- this should be fixed on master!
