### ISSUE TITLE
[rllib] when remote_worker_envs = True, episode.user_data does not persist

### ISSUE THREAD

**Issue by Maltimore** [ray-project/ray#13294]
### What is the problem?
I have callbacks which assign extra information to `episode.user_data`:

```python
class MyCallbacks(DefaultCallbacks):
    def on_episode_start(self, *, worker: RolloutWorker, base_env: BaseEnv,
                         policies: Dict[str, Policy],
                         episode: MultiAgentEpisode, env_index: int, **kwargs):
        episode.user_data['energy'] = []

    def on_episode_step(self, *, worker: RolloutWorker, base_env: BaseEnv,
                        episode: MultiAgentEpisode, env_index: int, **kwargs):
        info = episode.last_info_for()
        # in the first step, info is none, so we cannot append the information
        if info is not None:
            episode.user_data['energy'].append(info['energy'])
```

This works fine if `remote_worker_envs=False`. If `remote_worker_envs=True`, I get 

```
  File "/home/maltimore/repos/project/src/ray_callbacks.py", line 21, in on_episode_step
    episode.user_data['energy'].append(info['energy'])
KeyError: 'energy'

```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Tested with Ray 1.0.1 and nightly. Python 3.7, pytorch version 1.7, Ubuntu 20.04

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@sven1977

**Comment by bradleypick** [comment]
Is there any update on this issue? 

I'm seeing something similar when trying to use `episode.user_data` (which is added in a custom callback similar to above) in a custom evaluation function. I've tried a few things, but can't find a workaround.
