### ISSUE TITLE
Does Ray only support model parallel with TensorFlow and Pytorch?

### ISSUE THREAD

**Issue by cfangplus** [ray-project/ray#13329]
Hello,

Today I read the ray document from the follow two URL to get how to run ray with Deep Learning frameworks. 
https://docs.ray.io/en/master/using-ray-with-pytorch.html
https://docs.ray.io/en/master/using-ray-with-tensorflow.html

But they seems that only model parallel is support, So I want to know does data parallel supported with ray with TensorFlow/Pytorch?

**Comment by amogkam** [comment]
Hi @cfangplus the examples you posted actually show data parallel training where there are multiple replicas of the same model, each training on different batches of data. 

If you want a more fleshed out library for this very purpose, you can also check out [RaySGD](https://docs.ray.io/en/master/raysgd/raysgd.html),  which provides a wrapper around Pytorch DistributedDataParallel or Tensorflow Mirrored Strategy and a nice high-level Trainer API.

**Comment by cfangplus** [comment]
yea, thanks for your remind.
Another question, I note the paper of Ray and there is a performance evaluation between Ray + TF and Distributed TF. 
This experiment used TF1.8 and relyed on parameter-server SGD, so now, is there some update compared with TF2 version, PyTorch or allreduce relyed SGD?

**Comment by amogkam** [comment]
I don't think we have updated benchmarks for Ray implementation of SGD.

There are some (outdated) benchmarks for the Ray SGD library: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/examples/benchmarks/README.rst.

But the Ray SGD library is just a wrapper around Pytorch and Tensorflow, it doesn't actually implement its own communication primitives with Ray.

**Comment by cfangplus** [comment]
> 
> 
> I don't think we have updated benchmarks for Ray implementation of SGD.
> 
> There are some (outdated) benchmarks for the Ray SGD library: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/examples/benchmarks/README.rst.
> 
> But the Ray SGD library is just a wrapper around Pytorch and Tensorflow, it doesn't actually implement its own communication primitives with Ray.

Ray SGD library is just a wrapper around Pytorch and TensorFlow, is that true? I note from the paper that there is an experiment between Ray and OpenMPI ?  Also how to explain the evalution between Ray + TF and Distributed TF shows the former has better performance?
