### ISSUE TITLE
Ray client beta now available in nightlies!

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13324]
Ray now offers a remote client that can be used to connect to Ray from your laptop / other machines not part of the cluster itself. Check out the docs here! https://docs.ray.io/en/master/ray-client.html

A quick summarization of the docs:
1. Start a server (inside the cluster): `python -m ray.util.client.server [--host host_ip] [--port port] [--redis-address address] [--redis-password password]`
2. Connect to the Ray server (outside the cluster): `ray.util.connect("server_host:port")`

That's it! You should be able to use the full Ray API. There are a few bugs left, see the Ray Client milestone for more details. If you discover any additional issues or have feature requests, please comment below and file new issues!

cc @barakmich @richardliaw

**Comment by Yhinner** [comment]
@ericl Thanks for bringing up this useful feature! I haven't tried it yet, but have few high level questions:

1. With Ray client, we do not need to run `ray start` on my local machine outside of the cluster, is it correct?
2. As mentioned in https://github.com/ray-project/ray/issues/8035, the client has some tolerance of ray versions. Does it guarantee any two arbitrary versions of server and client can connect? If not, how do we identify which version of clients are supported for a given ray server version?
3. The same goes for python versions. With the older workaround that runs `ray start` on local machine, the python version has to be exact match, it even failed while my cluster has python 3.7.7 while my local machine has python 3.7.6. Is it the case case here as well?

I am thinking about a use case where my local machine is a centralized workspace for code development, while I can create multiple ray clusters (may have different minor versions in ray and python) for different purposes, and connect to the clusters from different programs. So the answers to above questions would definitely help me to build the infrastructure in way proper way. Thanks a lot!

**Comment by ericl** [comment]
> With Ray client, we do not need to run ray start on my local machine outside of the cluster, is it correct?

That's right, just call ray.util.connect().

> As mentioned in #8035, the client has some tolerance of ray versions. Does it guarantee any two arbitrary versions of server and client can connect? If not, how do we identify which version of clients are supported for a given ray server version?

So far we haven't made such guarantees as the feature is in beta; likely we'll provide a formal guarantee in the future.

> The same goes for python versions. With the older workaround that runs ray start on local machine, the python version has to be exact match, it even failed when my cluster has python 3.7.7 while my local machine has python 3.7.6. Is it the case same here as well?

The python version has to match to the minor version (3.7.6 vs 3.7.7 is fine).

**Comment by paravatha** [comment]
@ericl  python 3.7.7 and python 3.7.9 doesn't work. I had to make sure both  be **3.7.7**
**When you say "Start a server (inside the cluster): python -m ray.util.client.server"**, do I have to run it inside the head pod ? (I am using k8s operator)

**Comment by ericl** [comment]
> @ericl python 3.7.7 and python 3.7.9 doesn't work. I had to make sure both head pod and my client pod be python 3.7.7

That's the first time I've heard of this; could you provide more details? That would be unfortunate if minor versions can break serialization.

> When you say "Start a server (inside the cluster): python -m ray.util.client.server", do I have to run it inside the head pod ? (I am using k8s operator)

Any head/worker pod should work.

**Comment by paravatha** [comment]
@ericl I will try again and provide the exact error. But, I am currently seeing this issue for k8s operator https://github.com/ray-project/ray/pull/13588#issuecomment-766390052

**Comment by stuart-clark-45** [comment]
Hi @ericl thanks for the update is the connection secure between the client the and cluster?

**Comment by ericl** [comment]
Currently it is not configured with HTTP(s). You can setup your own secure proxy however if you want to expose it over the internet.
