### ISSUE TITLE
[rllib] Memory leak with CARLA integration

### ISSUE THREAD

**Issue by jackbart94** [ray-project/ray#13338]
I am working for CARLA and trying to update the integration with RLLib that is mentioned in the documentation with our latest release. While doing that, I have been noticing that the memory gets consumed slowly (``ram_util_percent`` keeps increasing over time) while running any of the examples, until it fills up entirely. I suspect there is a memory leak somewhere, but I haven't been able to identify it yet.

Ray version: 1.1.0
Python version: 3.8.5
Tensorflow version: 2.4.0
OS: Ubuntu 18.04

At this time, being integrated with an external library, I don't have a quick snippet to reproduce the issue. However, I will attach a screenshot to show what is the problem and you can let me know the additional steps to create a proper issue for this case.

Also, here's what I tried:
Different versions of Ray and different versions of Tensorflow (both 1.x and 2.x) or PyTorch.
Setting ``object_store_memory`` to a certain value.
Using ``local_mode``.
Using any ``num_workers``.

![This is an example of what happens](https://user-images.githubusercontent.com/32928804/104191665-17347d00-541e-11eb-9177-eb2209b1862b.png)

When ``num_workers`` is 1 or more, the ray process that seems to be leaking is ``RolloutWorker.par_iter_next_batch()``, but when it's set to 0, it's the main one as well.

I will keep analyzing if there might be a leak in the integration with CARLA itself, and it would be great if you have any suggestion for doing that!

**Comment by mageofboy** [comment]
Hi @jackbart94 , were you able to resolve this issue in your integration with CARLA? I am working on a similar project that involves integrating CARLA and rllib, and I am also encountering the same memory leak issue during training.

cc: @pschafhalter

**Comment by varunjammula** [comment]
Same issue. I tried different versions of ray from 1.1 to 1.10 and all have the same issue. @jackbart94 were you able to solve this issue?

**Comment by varunjammula** [comment]
@mageofboy Were you able to find a solution to this?

**Comment by jackbart94** [comment]
It's definitely fixed and already has an official repository. It's working correctly there. You can find it [https://github.com/carla-simulator/rllib-integration](at this link.)

**Comment by varunjammula** [comment]
@jackbart94 Thanks for the reply. I am using the official repo but modified it slightly. It works with DQN. When I try to use APEX with multiple workers, it crashes after several iterations. Were you successful in using other DRL algorithms?
