### ISSUE TITLE
[rllib] Way to check current epsilon

### ISSUE THREAD

**Issue by FruechteBini** [ray-project/ray#13337]
Hello guys,

is there a way to get the current epsilon in e.g. on_episode_start() ?

I did set my exploration settings like this:

```
# 3) Example exploration_config usages:
# a) DQN: see rllib/agents/dqn/dqn.py
"explore": True,
"exploration_config": {
   # Exploration sub-class by name or full path to module+class
   # (e.g. “ray.rllib.utils.exploration.epsilon_greedy.EpsilonGreedy”)
   "type": "EpsilonGreedy",
   # Parameters for the Exploration class' constructor:
   "initial_epsilon": 1.0,
   "final_epsilon": 0,
   "epsilon_timesteps": 20000,  # Timesteps over which to anneal epsilon.
},
```

How can I check if epsilon is actually 0 after 20000 timesteps?

Debugging I found the policy config in the worker class - but is there also a variable like "current_eps" or sth similar?
![image](https://user-images.githubusercontent.com/33086953/104192023-92962e80-541e-11eb-982a-b8e33bb4dcb8.png)

Thanks & Greetings

**Comment by mvindiola1** [comment]
@FruechteBini it is going to be in the exploration object of your policies. This worked for me: `policies["<POLICY_NAME>"].exploration.get_info()`

**Comment by Stefan-1313** [comment]
Hi @mvindiola1 ,
I have the same problem. How do I get the `policies` dict you metion?

**Comment by ArturNiederfahrenhorst** [comment]
@Stefan-1313 I'm running experiments on master and they get the cur_epsilon right. It will be 1.0 in the beginning - try sampling again after calling algorithm.train() as follows:

`from ray.rllib.algorithms.simple_q.simple_q import SimpleQ, SimpleQConfig

config = SimpleQConfig().framework(framework="torch")

algo = SimpleQ(config=config, env="CartPole-v0")
for i in range(10):
    algo.train()
    epsilon = algo.get_policy().exploration.get_state()['cur_epsilon']
    print(epsilon)`

**Comment by ArturNiederfahrenhorst** [comment]
@FruechteBini The current epsilon for an epsilon greedy exploration is part of the exploration object itself.
It's accessible via `self.epsilon_schedule(self.last_timestep)`
