### ISSUE TITLE
[serve] ImportedBackend cannot accept batches

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13343]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@simon-mo I think this can be fixed by just putting the `accept_batch` decorator on the dynamic class that's returned, but it makes me think we should just scrap the decorator. It's only ever caused me trouble personally and it's basically just documentation.

**Comment by simon-mo** [comment]
I think we should still keep it because it helps use to give better error message and do validation ahead of time.  The user can just add accept batch in the dynamic class's __call__ right? Is there a repro example?
