### ISSUE TITLE
[rllib] UnboundLocalError: local variable 'input_space' referenced before assignment

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#13342]
I'm trying to run MBMPO on my environment, but I get this error:
`UnboundLocalError: local variable 'input_space' referenced before assignment`

My action_space is a `Tuple`. Is there a requirement to define `input_space` as well?

Here is my code
```
return tune.run(
        "MBMPO",
        stop={"episodes_total": episodes_total},
        config={
            "env": "MyEnv",
            "num_gpus": 0,
            "num_workers": 1,
            "framework" : "torch",
            "env_config": {}
        },
    )
```

**Comment by drozzy** [comment]
This is probably because this if statement is not exchaustive:
https://github.com/ray-project/ray/blob/master/rllib/agents/mbmpo/model_ensemble.py#L134

It just ignores Tuple space

**Comment by richardliaw** [comment]
cc @sven1977

**Comment by sven1977** [comment]
[RLlib] Issue #13342: Add `validate_spaces` to MB-MPO.
