### ISSUE TITLE
[rllib] Registering custom preprocessors

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1335]
Right now there are some hiccups when using custom preprocessor:

- register_preprocessor doesn't work due to to a small bug (PR underway)
- More severely, ModelCatalog is not broadcast to workers, so we cannot register a new preprocessor globally. As a workaround we do it in the creator of the custom environment but that's awkward

**Comment by ericl** [comment]
For (2) we should replace it with the tune registry, which is broadcast.

**Comment by pcmoritz** [comment]
Hm, does it make sense to include the preprocessor in the tune registry? Maybe we can generalize the tune registry or create the possibility to have custom registries (although that sounds like over engineering). Another possibility is to also broadcast the rllib registry.

**Comment by ericl** [comment]
The tune registry is a genetic facility, you can declare a new object
category so it is fenced off from other ones.

**Comment by richardliaw** [comment]
I think this is addressed.
