### ISSUE TITLE
[core] Ray prevents to set a write flag of numpy array.

### ISSUE THREAD

**Issue by brorro** [ray-project/ray#13360]
### What is the problem?

I'm using ray==1.1.0, ubuntu==20.04 and pytorch==1.7.1.
When i try to set a flag of an array, numpy raises an exception,
`ValueError: cannot set WRITEABLE flag to True of this array`.
This happened after i got upgrade ray to 1.1.0 from 1.0.1.post1.
I needed to set write flag to make pytorch to construct tensors from the array, rather than copy and construct new tensor.

### Reproduction (REQUIRED)
```
import numpy as np
import ray
import torch


@ray.remote(num_cpus=2, num_gpus=1)
class GPUActor:
    def __init__(self):
        pass

    def foo(self, client):
        client.data.setflags(write=True)
        tensor = torch.from_numpy(client.data)
        """
        Working on tensor
        """
        return tensor.sum().item()


class Client:
    def __init__(self):
        self.data = np.array([1, 2, 3])


ray.init(include_dashboard=False)


a = GPUActor.remote()
b = Client()
c = a.foo.remote(b)
d = ray.get(c)
print(d)

```
- [YES] I have verified my script runs in a clean environment and reproduces the issue.
- [YES] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
This is Ray's computation model (Objects in the store is immutable). cc @stephanie-wang Do you know any good way to get around this?

**Comment by krfricke** [comment]
See also https://docs.ray.io/en/master/serialization.html#numpy-arrays
I don't think there's a workaround for that - you'll either have to construct and store the array on the actor or create a copy.

**Comment by stephanie-wang** [comment]
Yes, the behavior is expected. The reason objects are immutable is to prevent possible inconsistencies with anyone else that has a reference to the same object (`client` in this case). If you want others to see the updates, you should wrap the `Client()` object in an actor, as @krfricke suggested. Otherwise, creating a copy should work.

**Comment by brorro** [comment]
It's so sad that I have to constantly copy large memory that will not changed in whole life time. Wrapping the `Client()` in an actor is not an option because it has to be dynamically distributed to actors.

**Comment by stephanie-wang** [comment]
Hmm I think I misunderstood your original error. I didn't realize that the error was from setting the flag, not from writing directly to a read-only array. I'm not sure that this is a Ray error, actually. What numpy version are you using? There's a similar issue described [here](https://github.com/pandas-dev/pandas/issues/24839).

**Comment by brorro** [comment]
The version is 1.19.2 And yes you're right that error occurs exactly when the flag is edited. I hope there is a way to handle this issue.

**Comment by stephanie-wang** [comment]
Have you tried checking the versions of your other installs according to
the link that I sent you? Maybe yours is the same problem.

**Comment by brorro** [comment]
`numpy==1.15.4` resolved the issue, but it's too old to satisfy other packages' dependency.

**Comment by stephanie-wang** [comment]
Okay, I'm closing this issue since it appears to be a problem with other libraries, not Ray. Good luck tracking this down!

**Comment by brorro** [comment]
I'm not sure this is related to other libraries, considering that previous Ray release just worked fine. The only thing I have changed was to upgrade Ray to 1.1.0. Anyway I have no choice but to stick with 1.0.1...
