### ISSUE TITLE
[core] Does the communication between processes in the GPU also need to pass through ObjectStore?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#13368]
In Ray, the communication between processes is realized through shared memory (ObjectStore). When task gets the data object id, it can get the data with ray.get(). But there may be direct NVLink connections between GPUs, then the data generated by the process in the GPU is sent to the process in another GPU. Does the data transfer also need to go through ObjecStore? Can't data be transferred directly between GPUs?
Looking forward to your reply~~

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
No, NVLink communication between GPUs don't need to go through the object store.

**Comment by Matrix-World** [comment]
> No, NVLink communication between GPUs don't need to go through the object store.
thank you for your reply. @richardliaw 
In addition, I have two questions:
1. In fact, there is no NVLink connection between the GPUs of our machines. When the processes in the GPU communicate, the data needs to go through the PCIe Bus and memory. In this case, will the data generated by the process in the GPU also be stored in the ObjectStore? Does another process in the GPU obtain data through object_id?
2. I submit a case of Ray SGD TorchTrainer (https://docs.ray.io/en/latest/raysgd/raysgd_pytorch.html), and set num_workers=100, use_gpu=False (Ray cluster has one master and 2 slaves). I would like to know if torch and ray are combined here, is the communication between processes realized through shared memory (ObjectStore) or through MPI/GLOO/NCCL at the bottom of torch?

**Comment by Matrix-World** [comment]
> 
> 
> No, NVLink communication between GPUs don't need to go through the object store.
Thank you sincerely for your reply, but I have three other questions that are very confused and need your help (These are similar to the two questions I mentioned above ).
I followed the MNIST Tutorial to train an MNIST classifier with Pytorch Lightning's LightningModule and Ray SGD (https://docs.ray.io/en/master/raysgd/raysgd_ptl.html). But currently we still mainly use Torch, so we had trained an MNIST classifier with Pytorch(not pytorch_lightning) and Ray SGD, Just convert LightningModule to nn.Module and rewrite train_epoch and validate methods( case A). In another case, only pytorch is used to implement MNIST classifier without using RaySGD(case B). Both cases are DistributedDataParallel， the question as follows:

    Then I run the MNIST classifier (epochs=30, use_gpu=True, num_workers=4) of the above two cases(A,B) respectively, and the other models, parameters, and data are all the same.
    By comparing the total training time (30 epochs), I found that：
    total trian time=82s(in case B),
    total train time=60s(in case A), when using RaySGD, the training efficiency is accelerated by approximately 26.8%, it is
    amazing.
    Then we output the training time of each GPU under each epoch:
    each train time ~ 3.0s (in case B)
    each train time ~ 3.7s (in case A), when using RaySGD, the each training efficiency in every GPU is accelerated,
    30 * (3.7-3) is approximately equal to (82-60).
    So I want to know whether the data transmission between GPUs is optimized when using RaySGD with Pytorch for Multi-GPU training. In addition, I saw that backend=nccl can be set in trainer = TorchTrainer(), which means that RaySGD with Pytorch implements All-Reduce and still uses Pytorch's own process communication mechanism. So I am confused, what causes the above acceleration effect?
    According to the Running benchmarks and introduction(https://github.com/ray-project/ray/tree/master/python/ray/util/sgd/torch/examples/benchmarks), the Ray is just wrapping Pytorch DistributedDataParallel. Does RaySGD affect Pytorch's NCCL?
    According to the introduction of RaySGD, trainer = TorchTrainer(
    training_operator_cls=CustomeTrainingOperator,
    num_workers=num_workers,
    config=config,
    use_gpu=True
    ), TorchTrainer will use the CustomTrainingOperator class instance as a set of Ray Actors, and then distribute them on multiple GPUs for distributed training, then whether the data generated by these Actors during the running process (such as the train_epoch method) will be stored in the Object Store, In the All-Reduce process, can other GPU processes be directly obtained from the Object Store, leading to the aforementioned acceleration effect? I just guess.
    Sincerely look forward to your reply ？
    Waiting~~
