### ISSUE TITLE
[Metrics] Metrics are not exported when using different jobs

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#13372]
### What is the problem?
In an ipython window, run
```python
import ray
from ray.util import metrics
ray.init(_metrics_export_port=9999)
```
and leave it running.  In a second terminal, in an ipython window run
```python 
import ray
from ray.util import metrics

ray.init(address="auto")
error_counter = metrics.Count( 
            "fake_error_counter", 
            description=("The number of exceptions that have " 
                         "occurred in the backend."), 
            tag_keys=("backend", )) 
error_counter.set_default_tags({"backend": "FAKE BACKEND"}) 

error_counter.record(12345)
```

If you check localhost:9999, this metric never gets printed.  However, if you now go back to the first ipython window and paste in a different custom metric (say `fake_error_counter_2`), that metric will successfully be printed.  

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray nightly, Python 3.6, Mac OS Big Sur
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
cc @rkooo567

**Comment by architkulkarni** [comment]
Inspecting the logs for the second driver process in the above example (the one whose metric never gets exported) reveals the following:

```
[2021-01-13 18:11:39,748 W 82859 3049247] metric_exporter.cc:206: Export metrics to agent failed: IOError: 14: failed to connect to all addresses. This won't affect Ray, but you can lose metrics from the cluster.
```

**Comment by rkooo567** [comment]
Yeah I think this is the same issue as what I found from the product.
