### ISSUE TITLE
Forcing workers to be on different IP's

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1338]
How do I force workers to be on different IP's? Running synchronous parameter server example from [sharded_parameter_server_benchmark.py](https://gist.github.com/robertnishihara/87aa7a9a68ef8fa0f3184129346cffc3), worker assignment is non-deterministic, sometimes putting workers on different IP's, and sometimes overlapping them.

I'm using the following Ray wheel: https://s3-us-west-2.amazonaws.com/ray-wheels/20d6b74aa6c034fdf35422e6805e2283c672e03f/ray-0.3.0-cp35-cp35m-manylinux1_x86_64.wh

To reproduce, follow [Setup](https://github.com/diux-dev/cluster/tree/master/ray_integration#setup) and then [launch_ray_sync.py](https://github.com/diux-dev/cluster/tree/master/ray_integration#ray-example-with-synchronous-parameter-server) instructions

Example successful run:
```
ubuntu@ip-172-31-38-175:~$ python ray_sync.py                     --redis-addres
s=172.31.38.175:6379                     --num-workers=2                     --n
um-parameter-servers=2                     --dim=25000
ps ips:
0 ObjectID(b590eb558d167f21fb95a50a2722aacc89faa6db) ['172.31.47.14']
1 ObjectID(43b77e7e433ee52add031387d4cbe8491a8fd787) ['172.31.42.112']
worker ips:
0 ObjectID(29541ea57bf9a28711a03050dbc0b480874424cf) ['172.31.43.112']
1 ObjectID(b23e985a09fcb77a692a1a9bcd74993bb647f4bd) ['172.31.34.115']
elapsed times:  0.16676759719848633 0.16390705108642578 0.002860546112060547
elapsed times:  0.16541194915771484 0.1631171703338623 0.002294778823852539
elapsed times:  0.165177583694458 0.16281414031982422 0.002363443374633789
```
Example failing run

```
ps ips:
0 ObjectID(08edb335efdb56e58ba5fa50d6e3796f381816b2) ['172.31.41.13']
1 ObjectID(d2afcf97fcb6099bee2b645f47590ffca36bb614) ['172.31.44.196']
worker ips:
0 ObjectID(0e3c9390734ccdb844eea531c4f7f15573d23be8) ['172.31.44.196']
1 ObjectID(127b2b84ba853e86ef9883bf2271e44e935d9353) ['172.31.41.13']
Traceback (most recent call last):
```

As a side-note, I had trouble launching web visualizer. I think the necessary dependencies are installed, but I don't see the message on head node with Jupyter link. As a work-around, I tried launching new ray process on Ray node using script below. It starts listening on 8888, but there's no link with authentication token printed on the console, perhaps it's only listening on 127.0.0.1 and not *?

```
python
import ray
import time
ray.init(redis_address="172.31.38.175:6379")
time.sleep(3600*100)
```

**Comment by robertnishihara** [comment]
Each worker requires 1 GPU, so if you start Ray on each machine with 1 GPU, then all of the workers will be on different machines. I'm working on a change right now that will enable actors to use arbitrary custom resources, so we won't have to specify GPUs.

**Comment by robertnishihara** [comment]
As for the web UI, can you check if there is a jupyter notebook process running on the head node? You can also call `ray.get_webui_url()` from any driver to get the URL.

**Comment by yaroslavvb** [comment]
So I guess it's a bug then? (the script I ran has `@ray.remote(num_gpus=1)`)

**Comment by robertnishihara** [comment]
You're calling `ray start` with `--num-gpus=4` in 

https://github.com/diux-dev/cluster/blob/f822a38e32f6051b92598ef89cbedc79fd0f013a/ray_integration/launch_ray_sync.py#L94

so it can schedule up to 4 workers on the same machine. I think you want `--num-gpus=1`.

**Comment by yaroslavvb** [comment]
doh, good point
