### ISSUE TITLE
[rllib] Supporting vectorization of MultiAgentEnv within a single process?

### ISSUE THREAD

**Issue by ToruOwO** [ray-project/ray#13387]
According to issue#4938, vectorization of MultiAgentEnv within a single process is not automatically handled, and one needs to create a custom class for that starting from BaseEnv.

Would you consider adding this support in the future? (So that vectorization is performed `num_envs_per_worker > 1`)
Thank you!

**Comment by ericl** [comment]
num_envs_per_worker > 1 works just fine with multi agent envs--- I believe that PR is referring to a special use case where the env itself is somehow hosting multiple logical episodes.

**Comment by ToruOwO** [comment]
Hi,

For some reason, my `MultiAgentEnv` is never properly initialized whenever `num_envs_per_worker > 1`. This is why I think there might be some issue with vectorization of `MultiAgentEnv`, since the training works fine when the environment subclasses from `BaseEnv`, `VectorEnv` and `RemoteVectorEnv`. I wonder if you have any idea on the cause of this issue and how to fix it?

Thank you!
