### ISSUE TITLE
[dashboard] [RFC] Job submission

### ISSUE THREAD

**Issue by fyrestone** [ray-project/ray#13395]
### Background

Currently, a Ray job is usually started in 2 ways: 1) directly run a driver script from within the cluster; 2) use the `ray submit` command, which will copy the driver script to the cluster and run it.
 
There are a few problems with the current approaches:
- Users need to have access to log into the cluster, or have ray command installed in their laptops.
- There is no automatic way to prepare job dependencies.
- No isolation of job dependencies (jobs running in the same cluster may require different versions of a third party library).

The above problems are critical when running Ray jobs in a large-scale cluster.

This proposal is to implement the job submission feature based on the dashboard. This will include the following features:
- Expose RESTful APIs for submitting jobs and dropping jobs.
- Job dependencies management (downloading and cleanup).
- Support job environment isolation.
- Support multi-languages, e.g. Python, Java, cross language.

This feature is already implemented in Ant's internal fork of Ray, and has been running stably in production. We'd like to contribute it to the open-source community. **Please let us know if you have any comments or questions**.

### Detailed solution

- Add a `POST /jobs` for submitting job and a `DELETE /jobs/{job id}` for dropping job in job head.
- A job description in json which is friendly to RESTful API. Example:
``` json
{
  "name": "example",
  "owner": "abc.xyz",
  "language": "PYTHON",
  "supported_languages": [
    "PYTHON",
    "JAVA"
  ],
  "driver_entry": "simple_job",
  "driver_args": [
    "arg1",
    "arg2"
  ],
  "runtime_env": {
    "working_dir": "http://xyz.com/simple_job.zip",
    "py_modules": [
      "/path/to/other_module",
      "/other_path/local_project.zip"
    ],
    "conda": {
      "channels": [
        "defaults"
      ],
      "dependencies": [
        "codecov"
      ]
    },
    "pip": [
      "pydantic >= 1.8",
      "http://xyz.com/my_package.whl"
    ],
    "jars": [
      {
        "name": "common",
        "version": "2.1",
        "url": "http://xyz.com/commons-io-2.5.jar",
        "md5": "0ba5d0350ec3a77dfe81ce63e0c02e03"
      }
    ],
    "docker": {
      "image": "anyscale/ray-ml:nightly-py38-cpu"
    },
    "env_vars": {
      "OMP_NUM_THREADS": "32",
      "TF_WARNINGS": "none"
    },
    "jvm_options": [
      "-XX:+PrintGCDetails",
      "-XX:+PrintGCDateStamps"
    ]
  }
}
```
- The job agent prepare job environment according to the `supported_languages`, then start the driver by `language`.
- Manage job dependency in the job agent:
  - Python
    - pip download requirements to a cache directory.
    - pip install requirements from the cache directory.
    - The cache directory is shared among all jobs.
  - Java
    - Download jars to the shared jar directory.
    - Check the md5 of the downloaded jars.
    - Create a hard link from shared jar directory to the job directory.
    - The shared jar directory is shared among all jobs.
- Support the job environment isolation in job agent:
  - Create a job directory for each job.
  - Create a virtualenv for Python / cross language job.

### Steps of job submission

1. Job head receives a `POST /jobs` request, and sends a `SubmitJob` request to GCS.
2. Prepare the virtualenv on each node:
  a. GCS updates the job table, and publishes a notification.
  b. Each raylet receives the notification and sends a request to the job agent.
  c. The job agent creates a new virtualenv for this job, and starts downloading dependencies.
3. Start the driver.
  a. One of the job agents will start the driver process after dependencies are ready.
  b. The driver starts and joins the cluster by calling ray.init(address=””).

#### How to avoid the case that a raylet receives a task and executes it before the corresponding job dependencies are downloaded?

We use a special custom resource `RAY_JOB_RESOURCE_{job id}` to indicate that the dependencies are ready on a node. 
This resource will be automatically added to all tasks of the job, if the job is submitted from Dashboard.
The job agent will add this resource to a node when dependencies are finished downloading.

#### How to handle the case that the driver fails to start?

Raylet monitors the driver process. It will mark the job as failed if the driver process exits or the driver is not registered for a long time.

#### Fault handling

If job agent is dead, all drivers belong to this job agent commit suicide. Raylet restarts the job agent, then tells the job agent to initialize all job environments.
If raylet is dead, the job agent commit suicide. A new raylet restart, it subscribes to job notification and gets the job list. Raylet starts a job agent, then tells the job agent to initialize all job environments.

### Reference
The PR: https://github.com/ray-project/ray/pull/11960
Related issue: https://github.com/ray-project/ray/issues/11982
Design doc: https://docs.google.com/document/d/1DfY84f0bi6amXEdJFXrNwvIswRH2msAdgb-OMxpu7BM

**Comment by ericl** [comment]
@fyrestone could you comment on what this feature needs from Ray core? In particular, I'm trying to get an idea of whether it could be implemented more as a "Ray plugin" or if it needs to be deeply integrated with the system.

It sounds like there are a few components that could be started as separate services from Ray core:
1. API server
2. Agent daemon on each node
Presumably the Raylet needs to call into the agent daemon to setup dependencies as well.

The reason to implement this as more of a plugin would be to reduce tight coupling (improving maintainability of Ray), and potentially allow multiple job submission systems to be easily implemented.

**Comment by fyrestone** [comment]
This implementation is more like a `Ray plugin`, it is decoupled from Ray core. As you mentioned, the core components of job submission feature are:
1. API server _(The **head** part of dashboard job module)_
2. Agent daemon on each node _(The **agent** part of dashboard job module)_

But, we still need some features from Ray core:
- New grpc APIs to GCS and raylet.
- Driver node selection logic in GCS.
- Add constraints on resource `RAY_JOB_RESOURCE_{job id}` for  each task.
- Handle driver failures in raylet.
- Extend job state and `JobTableData`.
- Make Python worker can run in job virtualenv.

**Comment by ericl** [comment]
So one issue is there is substantial overlap between "Ray client" jobs, and jobs launched from this interface. It seems like these interfaces should be unified, so that:
- Ray client jobs show up as jobs in the dashboard.
- The same client server also handles job submissions.

Otherwise, we will have two similar but slightly incompatible methods of submitting jobs in Ray.

**Comment by fyrestone** [comment]
The Ray server for the client starts as a job driver and serves as a proxy. A ray server is just one job, no matter how many clients connect to it. I think it's not overlapped with the job submission. The dashboard can show all the jobs in different types.

**Comment by richardliaw** [comment]
Merged.
