### ISSUE TITLE
[rllib] I can't use QMixTrainer trainer.compute_action to obtain an action.

### ISSUE THREAD

**Issue by imxuemei** [ray-project/ray#13405]
I took TwoStepGame for an example. My code is as follows. 
I have tried different obs from TwoStepGame or TwoStepGame.with_agent_groups. It always obtained different errors.
Can any one tell me how to obtain actions from multi-agent env based on QMixTrainer?

`trainer = QMixTrainer(env="grouped_twostep", config=config)
    for i in range(1):
        res = trainer.train()
        print('==iter==')
        print(res)

    # env = TwoStepGame(config["env_config"]).with_agent_groups(grouping, obs_space=obs_space, act_space=act_space)
    env = TwoStepGame(config["env_config"])
    obs = env.reset()
    print('init obs: ', obs)
    for i in range(10):
        # all_obs = obs['group_1']
        act_dict={}
        for j in range(2):
            act_dict[j] = trainer.compute_action(obs)
        obs,rew,done,info = env.step(act_dict)
        print("obs  ", obs)
        print("rew  ",rew)
`

**Comment by Counterfeiter** [comment]
same problem here...

Any solutions ?

My best guss:

```python
env = CustomEnv(level=level, normalize_obs = True, verbose = verbose).with_agent_groups(
                grouping, obs_space=obs_space, act_space=act_space)
obs = env.reset()
agent = QMixTrainer(config=config, env="custom_env")
agent.restore(restore)
```

but fails. custom_env is registered before....

**Comment by imxuemei** [comment]
> same problem here...
> 
> Any solutions ?
> 
> My best guss:
> 
> ```python
> env = CustomEnv(level=level, normalize_obs = True, verbose = verbose).with_agent_groups(
>                 grouping, obs_space=obs_space, act_space=act_space)
> obs = env.reset()
> agent = QMixTrainer(config=config, env="custom_env")
> agent.restore(restore)
> ```
> 
> but fails. custom_env is registered before....

I haven't solved it. Other trainers, such as A3CTrainer, can work, but QMIX can't.

**Comment by jzxycsjzy** [comment]
Same problem. I cannot obtain action from action space when I try to use QMix algorithm. Include train.trainer() and tune.tuner().fit()

**Comment by joshmyersdean** [comment]
Has there been any progress on this issue?
