### ISSUE TITLE
[rllib] [tune] Error when training Unity MLAgents env with num_samples > 1

### ISSUE THREAD

**Issue by rallen10** [ray-project/ray#13412]
When trying to train an mlagents environment using rllib with num_samples > 1, I get the following error:

```
mlagents_envs.exception.UnityWorkerInUseException: Couldn't start socket communication because worker number 1 is still in use. You may need to manually close a previously opened environment or use a different worker number.
```

**Comment by richardliaw** [comment]
cc @sven1977

**Comment by yurirocha15** [comment]
I was taking a look at the source code and noticed that every time a new env is created the _BASE_PORT attribute is updated, while the worker_id is kept at 0. But if the user sends a custom port as an argument, seems that the same port and worker_id would be used, causing an error. This might be related to this issue.

https://github.com/ray-project/ray/blob/84e110a949e83c4956cca14ed59fd5a92e34f3fe/rllib/env/unity3d_env.py#L76-L86

**Comment by chenfei8888** [comment]
> cc @sven1977

Hello, how is this problem solved
