### ISSUE TITLE
ray.get_runtime_context().get() fails on a driver

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13415]
### What is the problem?

`ray.get_runtime_context().get()` errors when running on a driver. This should still return the useful context information (e.g., current node ID) or at the very least have a better error message.

```python
import ray
ray.init()

print(ray.get_runtime_context().get())
```

```
2021-01-13 14:15:29,011 INFO services.py:1169 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(ray.get_runtime_context().get())
  File "/Users/eoakes/code/ray/python/ray/runtime_context.py", line 26, in get
    "task_id": self.task_id,
  File "/Users/eoakes/code/ray/python/ray/runtime_context.py", line 92, in task_id
    assert self.worker.mode == ray.worker.WORKER_MODE, (
AssertionError: This method is only available when the process is a                 worker. Current mode: 0
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Ah I think this should be a simple fix. I will take a look at it later.

**Comment by edoakes** [comment]
@rkooo567 yeah it ended up being really simple so I just made a quick PR to fix, PTAL when you have a chance.
