### ISSUE TITLE
[RLlib] Trainer._validate_config(config) is no longer idempotent

### ISSUE THREAD

**Issue by raoul-khour-ts** [ray-project/ray#13427]
### What is the problem?
Trainer._validate_config(config) is no longer idempotent

the issue was introduced in https://github.com/ray-project/ray/commit/d49c3fae0bc339c51468b91af773199848df95f5

If you run Trainer._validate_config(config) 2 times on the same config it will throw a value error saying framestack should be auto|None when it changed framestack to 0 in the first call.

This happens commonly when running the functional API of tune and using default resources request then running the experiment

**Comment by raoul-khour-ts** [comment]
@sven1977 Can you look at this?

**Comment by sven1977** [comment]
Closing this issue. Above PR fixes this problem. Thanks @raoul-khour-ts for raising this and for the fix!
