### ISSUE TITLE
Autoscaler demands accumulate infinitely

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#13431]
### What is the problem?

On a simple workload, `ray.get([f.remote() for _in range(1000)])`, where the functions just sleep for 30s, `ray status` shows demands accumulating forever on master:
```
Demands:
 {'CPU': 1.0}: 824683+ pending tasks/actors
```

cc @AmeerHajAli @wuisawesome

**Comment by wuisawesome** [comment]
@ericl are you doing this on a single machine? Or a cluster?

**Comment by ericl** [comment]
This was a cluster.

**Comment by AmeerHajAli** [comment]
824683+ 👀

**Comment by ericl** [comment]
This was a cluster

**Comment by wuisawesome** [comment]
@ericl Does this need to become a release blocker?

**Comment by ericl** [comment]
Yeah, this seems like a major regression.

**Comment by ericl** [comment]
Please don't remove P1 labels, we need to label with both

**Comment by Wordyka** [comment]
How to reproduce this bug? Is it any of instructions or step that we must be followed? Thank you
