### ISSUE TITLE
[Tune] Automatically retrieve metric lists when using TuneReporterCallback for Keras models.

### ISSUE THREAD

**Issue by LucaCappelletti94** [ray-project/ray#13449]
### Describe your feature request
Currently, in order to report all the metrics computed by my model, which in classification tasks is particularly of interest, I am using the following code snippet:

```python
from ray.tune.integration.keras import TuneReportCallback
model = build_my_keras_model(...)

TuneReportCallback(metrics=[
    "{}{}".format(sub, metric)
    for metric in model.metrics_names
    for sub in ("", "val_")
])
```

Now, that can be easily automated within the TuneReportCallback class by using the `self.model` object available in Keras callbacks and we could reduce the usage example to:

```python
from ray.tune.integration.keras import TuneReportCallback
model = build_my_keras_model(...)

TuneReportCallback()
```

where simply all metrics computed by the model are reported. 

The user still may specify the list of metrics of interest if there is no desire for all metrics to be reported, but I cannot think of such a reason.

I will make a pull request adding this feature shortly.

**Comment by krfricke** [comment]
Hi @LucaCappelletti94, yep, that makes sense - however I was under the impression we're already doing that:

```
# (in TuneReportCallback)
    def _handle(self, logs: Dict, when: str = None):
        if not self._metrics:
            report_dict = logs   # <------ relevant line
        else:
            report_dict = {}
            for key in self._metrics:
                if isinstance(self._metrics, dict):
                    metric = self._metrics[key]
                else:
                    metric = key
                report_dict[key] = logs[metric]
        tune.report(**report_dict)
```

Do I assume correctly that this currently does not work? If so, a contribution is much appreciated. It would be great if you could add a test for this then.

**Comment by LucaCappelletti94** [comment]
You are absolutely right, somehow it flew over my head. It is documented in the main docstring.

Thanks!
