### ISSUE TITLE
[core] ray.exceptions.ObjectStoreFullError: even though i enabled spill

### ISSUE THREAD

**Issue by srikanthgadadasu** [ray-project/ray#13443]
[test_pipeline_using_ray.txt](https://github.com/ray-project/ray/files/5812544/test_pipeline_using_ray.txt)
When i am passing 5m records dataframe to the actor method, its failing with below error, even-though i am using latest beta version of ray where data spill is enabled. and how to make sure all temporary files created during process will be removed after completition of the program?

File "python/ray/_raylet.pyx", line 1251, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 1256, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 331, in ray._raylet.prepare_args
  File "python/ray/_raylet.pyx", line 993, in ray._raylet.CoreWorker.put_serialized_object
  File "python/ray/_raylet.pyx", line 918, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 145, in ray._raylet.check_status
ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0f00000003000000 in object store because it is full. Object size is 516884584 bytes.
The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.

*Ray version and other system information (Python version, TensorFlow version, OS):*

$ pip list | grep ray
ray                      1.2.0.dev0
$ python3 --version
Python 3.8.6

System info:
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

PFA code used for testing

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ yes] I have verified my script runs in a clean environment and reproduces the issue.
- [ yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html)

**Comment by rkooo567** [comment]
Thanks for reporting the issue! (With reproduction). I will take a look at the issue.

For deleting objects, spilled objects are automatically deleted when object is not used anymore (by our reference counting protocol). But if you shutdown the cluster with ctrl - c it is currently not deleted. We will support deleting the directory when ctrl c is triggered, but for now you can just delete the directory after the job is done.

**Comment by rkooo567** [comment]
Tried the same example with Dask on Ray in the latest master (with a little bit of modification because the application was broken), and I verified it works. Here's my code. Please reopen an issue if you face other issues! 

```python3
import ray
from timeit import default_timer as timer
import time
import pandas as pd
import dask.dataframe as dd
from ray.util.dask import ray_dask_get
import json

ray.init(num_cpus=6)

df = dd.read_csv('http://eforexcel.com/wp/wp-content/uploads/2020/09/5m-Sales-Records.zip').repartition(8)

class Utils():

    def __init__(self):
        pass

    def parse_dates_using_lookup(self, date_column, format_to='%Y%m%d', infer_datetime_format=False):
        dates = {date:pd.to_datetime(date, infer_datetime_format=infer_datetime_format) for date in date_column.unique()}
        return date_column.map(dates)

    def define_partitions(self, seq, num_of_partitions):
        m = num_of_partitions
        n,b,newseq=len(seq),0,[]
        for k in range(m):
            a, b = b, b + (n+k)//m
            newseq.append(seq[a:b])
        return newseq

@ray.remote
class Pipeline():

    def transform(self, df, partition_no): 
        '''All transformations before repartition'''
        start = timer()
        df = df.get_partition(partition_no).compute(scheduler=ray_dask_get)
        # df['Order_Date'] = Utils().parse_dates_using_lookup(df['Order_Date'])
        # df['Ship_Date'] = Utils().parse_dates_using_lookup(df['Ship_Date'])
        #df = df[df['Region'] == 'Europe']
        print("duration =", timer() - start, " seconds for transform")
        return df

    def re_partition_sort_data(self, df, partition_metadata, partition_keys, sort_keys, partition_no):
        start = timer()
        '''Prepare partitions based on partition metadata'''
        df = df[df[partition_keys].isin(partition_metadata)]
        if sort_keys is not None:
            '''Sort data based on sort keys'''
            df.sort_values(by=sort_keys)
        print("duration =", timer() - start, " seconds for preparing partition based on keys")

        start = timer()
        filename = "/tmp/data/sample_textfile." + str(partition_no) + ".txt"
        df.to_csv(filename, sep='|', header=None, encoding='utf-8')
        print("duration =", timer() - start, " seconds for writing")

start = timer()
try:
    actors = {}
    result_ids_step1 =[]
    completed_ids_step1 = []

    result_ids_step2 = []
    completed_ids_step2 = []

    npartitions = df.npartitions
    parallel = df.npartitions//2

    temp_list = []

    '''Workers for executing step1 tasks'''
    for i in range(parallel):
        x = temp_list[-1] if temp_list else 0 
        y = [x, x+1] if x not in temp_list else [x+1, x+2]
        temp_list.extend(y)
        actors[i] = Pipeline.options(max_concurrency=1).remote()
        result_ids_step1.append(actors[i].transform.remote(df, y[0]))
        result_ids_step1.append(actors[i].transform.remote(df, y[1]))
    
    '''Get step1 status'''
    while len(result_ids_step1):
        done_ids, result_ids_step1 = ray.wait(result_ids_step1)
        completed_ids_step1.extend(done_ids if isinstance(done_ids, list) else [done_ids])
    
    '''Prepare list of data frames to be merged '''
    dflist = [ray.get(objref_id) for objref_id in completed_ids_step1]

    '''prepare the merged data frame'''
    df_concat = pd.concat(dflist)

    '''Get the partitions metadata based on keys'''
    partition_keys = 'Region'
    sort_keys = ['Order_Date']
    partition_metadata = Utils().define_partitions(seq = list(df_concat[partition_keys].value_counts(dropna=False).keys()), 
                                                         num_of_partitions = parallel)
    print(partition_metadata)

    '''Repartition data: partition using metadata >> sort >> write files'''
    for i, x in enumerate(partition_metadata):
        result_ids_step2.append(actors[i].re_partition_sort_data.remote(df_concat, x, partition_keys, sort_keys, i))

    '''Get step2 status'''
    while len(result_ids_step2):
        done_ids, result_ids_step2 = ray.wait(result_ids_step2)
        completed_ids_step2.extend(done_ids if isinstance(done_ids, list) else [done_ids])

finally:
    for x in actors.keys():
        ray.kill(actors[x])
print("duration =", timer() - start, " seconds")
```
