### ISSUE TITLE
[tune] Starting multiple trails, each with remote workers, hangs

### ISSUE THREAD

**Issue by johannespitz** [ray-project/ray#13447]
I am working on a 16 Core machine with Python 3.7.7 and ray1.1.0 installed via pip.

When trying to use tune to run multiple RL trails, where each trail uses a couple of remote workers, the program simply hangs forever. This problem seems closely related to issue #3644 regarding nested remote calls. However, I think in this case it should be fairly simple to fix. 
 
A minimal example to reproduce the described behavior is this:
```
import time
import numpy as np
import ray
from ray import tune

@ray.remote(num_cpus=1)
class Worker():
    def __init__(self, idx):
        self.idx = idx

    def collect_data(self):
        time.sleep(1) # compute something
        return np.arange(100) + self.idx

def main(config):
    time.sleep(5) # compute something
    worker_list = []
    for it in range(config['num_worker']):
        worker_list.append(Worker.remote(it))
    for it in range(config['num_iterations']):
        wait_list = []
        for worker in worker_list:
            wait_list.append(worker.collect_data.remote())
        data = ray.get(wait_list)
        result = np.sum(data)
        time.sleep(1) # compute something
        tune.report(iteration=it, result=result)


ray.init(num_cpus=16)

analysis = tune.run(
    main,
    metric="result",
    mode="max",
    config=dict(
        num_worker=4,
        num_iterations=tune.grid_search(list(range(10, 30))),
    ),
    # resources_per_trial=dict(
    #     cpu=4,
    #     gpu=0
    # ),
    # queue_trials=True,
)
```

Initially, I expected that setting resources_per_trail would limit the resources that each trail may allocate, but that didn't work.

Now, is there a way to tell tune that each trail WILL require some number of resources, such that fewer trails get started?

**Comment by krfricke** [comment]
Hi @johannespitz, indeed there is - [see here in the docs (Advanced resource allocation)](https://docs.ray.io/en/master/tune/api_docs/trainable.html#advanced-resource-allocation).

You're correct to use `resources_per_trial`, however, the `cpu` and `gpu` indicate the resources for the trainable actor. If that actor requests more resources, you can reserve them via the `extra_cpu` and `extra_gpu` fields.

In your case, you'll want to run training like so:

```

analysis = tune.run(
    main,
    metric="result",
    mode="max",
    config=dict(
        num_worker=4,
        num_iterations=tune.grid_search(list(range(10, 30))),
    ),
    resources_per_trial=dict(
        cpu=1,
        extra_cpu=4,
        gpu=0
    )
)
```

If you start 4 remote  workers this will require 5 CPUs, 1 for the trainable driver and one for each worker.

**Comment by johannespitz** [comment]
Thank you for quick response, and the detailed answer!
This is exactly what I was looking for.
