### ISSUE TITLE
ray create_or_update should restart workers if head node is updated

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1345]
### Describe the problem
To reproduce:
1. ray create_or_update test.yaml
2. make some change to the head node config
3. ray create_or_update test.yaml

The head node will be restarted since it's config changed, but the workers will not. This is problematic since the workers won't automatically reconnect to the head node, they need to be restarted.

Possible fixes:
- Restart the workers if the head node process gets restarted
- Have workers attempt to reconnect automatically
- Have the head node try to restart worker nodes that are in the cluster but not connected

**Comment by robertnishihara** [comment]
When you say "restart the worker", do you mean "rerun `ray start` on the worker machines"?

That might be the simplest.

**Comment by ericl** [comment]
Yeah, it would involve `ray stop`, and `ray start --redis_address...`. In principle the ray commands could be different (e.g. using some virtualenv) though most of times it would be that.

**Comment by robertnishihara** [comment]
Ok, that makes sense.
