### ISSUE TITLE
[core] can I use an external redis server?

### ISSUE THREAD

**Issue by CheungChan** [ray-project/ray#13453]
如题，申请了云redis做ray集群的GCS。但是启动ray start --head --address 会报错--head和--address不能一起用。
如果使用ray start --address又会报错redis中session_name键不存在。

**Comment by krfricke** [comment]
Hi @CheungChan, `ray start --head` starts up the redis server, so it can't be used together with `--address`. To change the GCS port on the head node, use `ray start --head --port 6379`.

See also here: https://docs.ray.io/en/master/configure.html#head-node

**Comment by CheungChan** [comment]
Thanks.  So can I use another  redis  server rather than the one in head node,such as a redis server on cloud to start a ray  cluster.  Beacause when the head node is down ,the redis on the head node will be down,too. The cluster data will lose.

**Comment by krfricke** [comment]
Ah, got it. I know there was an effort to enable this - cc @rkooo567 who should know more about this.

**Comment by rkooo567** [comment]
Ah yeah @WangTaoTheTonic is planning to add an api to support this. But for now, we don’t have a way to do that

**Comment by WangTaoTheTonic** [comment]
Hi @CheungChan, currently we don't support external redis server but we are planning to do this and proposal are being discussed!

**Comment by WangTaoTheTonic** [comment]
The initial pull request has been created: https://github.com/ray-project/ray/pull/13170

**Comment by WangTaoTheTonic** [comment]
External redis has been supported. User can pass the address of external redis with argument `--address` when starting processes on the head node. Everything else will be same as before.
I'm closing this. If there's any issue in that we can discuss in new issue. @CheungChan
