### ISSUE TITLE
RequestLimitExceeded during cluster autoscaling

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1346]
### Describe the problem

Sometimes you see RequestLimitExceeded (on DescribeInstances or some other AWS poll) during operation of an autoscaling cluster. This seems to be because we poll very aggressively (every time in the monitor.py loop). We should probably (1) poll AWS less often, and (2) back-off on RequestLimitExceeded exceptions (boto already does some internal backoff, but it doesn't appear to retry for extended periods of time).

**Comment by robertnishihara** [comment]
I've run into this as well.

**Comment by robertnishihara** [comment]
@ericl is there a workaround for this now?

**Comment by ericl** [comment]
Yeah, throttling the update() to once every 5s works well (the quick hack
is to add a sleep).
