### ISSUE TITLE
[core] Better error message when parent actor dies

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13488]
### What is the problem?
```python
import ray
ray.init()

@ray.remote
class Inner:
    def ping(self):
        return "pong"

@ray.remote
class Outer:
    def __init__(self):
        self.inner = Inner.remote()

    def get_ref(self):
        return self.inner

outer = Outer.remote()
inner = ray.get(outer.get_ref.remote())
del outer
ray.get(inner.ping.remote())
```

It's expected that the call to `inner.ping.remote()` fails due to the actors fate sharing, but we should provide a better error message to make it easier to understand/debug.

```
Traceback (most recent call last):
  File "t.py", line 20, in <module>
    ray.get(inner.ping.remote())
  File "/Users/eoakes/code/ray/python/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/eoakes/code/ray/python/ray/worker.py", line 1390, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
I can take over this next sprint.

**Comment by stephanie-wang** [comment]
Related to (subsumed by?) #15962.
