### ISSUE TITLE
[tune] Multi-gpu training with tune + pytorch lightning hangs at ddp initialization

### ISSUE THREAD

**Issue by mrkulk** [ray-project/ray#13483]
When I run tune with a pl.LightningModule trainer in multi-gpu mode, the script hangs at 

```
(pid=25845, ip=172.31.47.46) GPU available: True, used: True
(pid=25845, ip=172.31.47.46) TPU available: None, using: 0 TPU cores
(pid=25845, ip=172.31.47.46) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1,2]
(pid=25845, ip=172.31.47.46) initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
```

When the number of `number of gpus == 1`, then it no more hangs and proceeds normally. 

When discussing with @richardliaw, he suggested that " it seems like there’s no more support for starting pytorch lightning training using multiple separate scripts" and suggested to raise this feature request. Thank you very much!

**Comment by krfricke** [comment]
Thanks @mrkulk, supporting PyTorchLightning multi GPU training is an issue that came up a couple of times recently. We'll be looking into how to support this.

**Comment by mrkulk** [comment]
@krfricke : That would be great! Looking forward to hearing about it and that would basically unlock us (so I can imagine many others) to use ray for most of the pressing scenarios.

**Comment by richardliaw** [comment]
cc @amogkam I think this could be solved with a Ray Accelerator for PTL.

**Comment by thecooltechguy** [comment]
Hi I was also trying to run multi-gpu training with PTL (with ddp) + Ray Tune, looking forward to such an integration!

**Comment by amogkam** [comment]
Hey @mrkulk, we'll take a look at this next week. What Pytorch Lightning and Ray versions are you using?

**Comment by mrkulk** [comment]
That sounds great! I am currently using `ray==1.1.0` and `pytorch_lightning==1.1.5`

**Comment by amogkam** [comment]
Hi @mrkulk @thecooltechguy, we just finished implementing a Ray backend for distributed Pytorch Lightning training here- https://github.com/ray-project/ray_lightning_accelerators.

The package introduces 2 new Pytorch Lightning accelerators for quick and easy distributed training on Ray.

It also integrates with Tune and should resolve your issue. Now you can use Tune to run multiple trials in parallel, and each trial can itself be distributed with any number of CPUs or GPUs.

Please check it out, and let us know how it goes!

**Comment by thecooltechguy** [comment]
Wow, thanks @amogkam ! Can't wait to try it out!!

**Comment by richardliaw** [comment]
I'll close this issue now, and we can continue any new issues on the new Github repo :)

**Comment by veqtor** [comment]
Hi, was any progress made on this, furthermore, where is this new repo that you talk about?

**Comment by griff4692** [comment]
> Hi @mrkulk @thecooltechguy, we just finished implementing a Ray backend for distributed Pytorch Lightning training here- https://github.com/ray-project/ray_lightning_accelerators.
> 
> The package introduces 2 new Pytorch Lightning accelerators for quick and easy distributed training on Ray.
> 
> It also integrates with Tune and should resolve your issue. Now you can use Tune to run multiple trials in parallel, and each trial can itself be distributed with any number of CPUs or GPUs.
> 
> Please check it out, and let us know how it goes!

Hi I just tried this out and was getting timeout errors with wandb unfortunately.

**Comment by f2010126** [comment]
> I'll close this issue now, and we can continue any new issues on the new Github repo :)


Hi This issue still persists. Could you please reopen it?
