### ISSUE TITLE
[tune] wait_for_gpu

### ISSUE THREAD

**Issue by Emilon1928** [ray-project/ray#13486]
### What is the problem?

Ray version: master

There are two errors in the wait_for_gpu function in tune.utils.util:

1. the ratio of occupied gpu memory (eg. 0.1) to total memory (eg. 10 000MiB) is compared - line 459
2. the object is returned before the for loop which results in a constant value of the occupied gpu memory - line 457

![image](https://user-images.githubusercontent.com/23121677/104712292-a8f40100-5722-11eb-9bb7-a3152c8d34b6.png)

**Comment by krfricke** [comment]
I can confirm the first error, which should be straightforward to fix. I don't understand what you mean by the second though. We only return `True` when the memory is free, in all other cases we raise a `RuntimeError`. Am I missing something?

**Comment by Emilon1928** [comment]
What I mean is that once an object is returned, it does not change the values of its fields. Which means that every time you check gpu_object.memoryUsed it stays the same. In my case this problem was solved by moving line 457 inside the loop.

**Comment by krfricke** [comment]
Ah, right, that does make sense. Thanks! Would you like to push a PR for this? Otherwise I can get to it sometime later today.

**Comment by krfricke** [comment]
Actually, I think we actually want to compare total memory usage. As in, we're usually not interested in waiting until the GPU has e.g. 80% free memory, but rather until the GPU has e.g. 2GB free memory so our model fits on it. Right?

In that case we'll just need to adjust the docstring to make this clear and move the GPU query into the loop.

**Comment by Emilon1928** [comment]
Yes, you are right. I think more usefull should be total amount of free memory instead of ratio.
