### ISSUE TITLE
[core] Abort trap: 6 when trying to use cluster

### ISSUE THREAD

**Issue by jagoosw** [ray-project/ray#13492]
### What is the problem?
I keep getting an "Abort trap:6" error when I try to run a 
Ray 1.1.0
Python 3.8.6
MacOS/Ubuntu

### Reproduction 
On the host machine:
`ulimit -c unlimited`
`ray start --head --include-dashboard true`
I did the first line as others suggested it may fix it but it runs the same with and without

On the client machine:
` ray start --address="172.21.162.159:6379" --redis-password="5241590000000000" `
`python`
`>>>import ray`
`>>>ray.init(address="auto")`

**Comment by rkooo567** [comment]
The given information is not sufficient to do troubleshooting. Can you provide this information?

1. Full logs (especially which log file received the abort trap6).
2. The environment and how you deploy the cluster in more detail.

**Comment by jagoosw** [comment]
I'm not sure how to get this information but I'll try. When I run the python bit with the verbose tag it gives no information before the abort message. Where should I look for the logs.

The "cluster" is just a ubuntu server that I manually started ray on.

**Comment by jagoosw** [comment]
I think this was related to the `ulimit -n ` issue because when I did a fresh install on the cluster it seems to be working now. Sorry for the bother

**Comment by rkooo567** [comment]
@jagoosw Re; logs. You can find them from `/tmp/ray/session_latest/logs`.

**Comment by yywangvr** [comment]
> I think this was related to the `ulimit -n ` issue because when I did a fresh install on the cluster it seems to be working now. Sorry for the bother

I get the same issue. Could you explain more in detail what did you do? A "fresh install" fo what? Thank you

**Comment by jagoosw** [comment]
> > I think this was related to the `ulimit -n ` issue because when I did a fresh install on the cluster it seems to be working now. Sorry for the bother
> 
> I get the same issue. Could you explain more in detail what did you do? A "fresh install" fo what? Thank you

I just set up new virtual environments on both sides and re installed everything. I never got it working properly but it stopped doing the errors.

**Comment by yywangvr** [comment]
> > > I think this was related to the `ulimit -n ` issue because when I did a fresh install on the cluster it seems to be working now. Sorry for the bother
> > 
> > 
> > I get the same issue. Could you explain more in detail what did you do? A "fresh install" fo what? Thank you
> 
> I just set up new virtual environments on both sides and re installed everything. I never got it working properly but it stopped doing the errors.

Thanks. set up new virtual environment through anaconda, right? Then, you redinstalled everything?

**Comment by jagoosw** [comment]
Yeah new pip venv too then reinstalled it all
