### ISSUE TITLE
[rllib] Wrong reward for MBMPO Cartpole?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#13507]
It seems like maybe this is returning 0.0 when it should really be returning 1.0?
https://github.com/ray-project/ray/blob/2cd51ce608744e801c1a888540e138213120c10a/rllib/examples/env/mbmpo_env.py#L29

The `rew` is equal to `True` when the game is over, as such it should be zero (according to official code https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L137). When `rew` is equal to `False`, game is not over and so reward should be 1.0.

**Comment by drozzy** [comment]
Perhaps?
```
done = (x < -self.x_threshold) | (x > self.x_threshold) | (
            theta < -self.theta_threshold_radians) | (
                theta > self.theta_threshold_radians)
rew = (not done).astype(float)
```

**Comment by michaelzhiluo** [comment]
Recommend creating your own custom wrapper that MBMPO-Env can use. `rew.astype(float)` is for more general envs.

**Comment by drozzy** [comment]
https://github.com/ray-project/ray/blob/2cd51ce608744e801c1a888540e138213120c10a/rllib/examples/env/mbmpo_env.py#L13

**Comment by sven1977** [comment]
Yeah, this seems to be not a CartPole-like reward :). Agreed, this seems to be kind of a reversed reward (1.0 if position is bad (terminal), 0.0 if position is "good").
I'll fix it.

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/14037

Thanks for filing this @drozzy !
