### ISSUE TITLE
how to read data from local directory

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13504]
I have a setup similar to [this ray example](https://docs.ray.io/en/master/tune/examples/mnist_pytorch.html), however, instead of downloading the dataset, I want to read from a local directory, so the `get_data_loaders` function will just contain some code like:

`pd.read_csv('path/to/file.csv')`

However, reading a csv file like this seems to be giving error

> FileNotFoundError: [Errno 2] No such file or directory

Upon further inspection, when I call `os.getcwd() `before `pd.read_csv()` it seems that `ray` has changed my working directory to something like `/home/user/ray_results/func_68e39_00000_0_dim=128_data.csv`.

Is there a way to pass the location of my csv file to `ray` so that it can read it?

**Comment by rkooo567** [comment]
Can you try listing files in the directory to make sure if you have them on the right path?

**Comment by turmeric-blend** [comment]
```
src ---> datasets ---> period_2017 ---> data.csv
      |
     ---> main.py
```

my paths are something like above, where in `main.py` I call `pd.read_csv('datasets/period_2017/data.csv')`.

**Comment by rkooo567** [comment]
Oh I meant to try

print(os.cwd()) in your remote method and see where your remote function is running.

Since the remote function is running in a different process, it doesn't use the same file path as your driver usually.

**Comment by turmeric-blend** [comment]
yes I've printed this as in my question as above: `/home/user/ray_results/func_68e39_00000_0_dim=128_data.csv`

**Comment by rkooo567** [comment]
If you can ensure your file exists in a local node, you can just pass the full path to the remote method I think? Am I missing anything from your question?

**Comment by turmeric-blend** [comment]
Yes passing the full path works. But I was looking for a method where we can pass from the relative path. For example:

```
src ---> datasets ---> period_2017 ---> data.csv
      |
     ---> main.py
```

Since `datasets` folder share the same level path as `main.py`, I wanted to pass something like `datasets/period_2017/data.csv` instead of `/home/user/Documents/src/datasets/period_2017/data.csv` (the full path).

Seems more intuitive to me initially I guess. But the full path works too. Thanks.

**Comment by rkooo567** [comment]
I think you can achieve it if you run ray start or ray.init in main.py, but I am not 100% sure.

**Comment by yzs981130** [comment]
> I think you can achieve it if you run ray start or ray.init in main datasets folder, but I am not 100% sure.

I confirmed that the default python working directory is where I ran `ray start` (let's only talk about launching ray using `ray start`). 

I wonder if there is any approach to changing the working directory to where the python script is, without passing the absolute path just like above?
