### ISSUE TITLE
[autoscaler] Ray on Kube deployments do not populate the expected environment variables.

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#13500]
### What is the problem?

Ray on Kube does not set the expected environment variables so the examples do not work.

Ray:7ff314a5df15f4b2b241f48cb90a2f7c14cebe5e  & run with latest containers

### Reproduction (REQUIRED)

Follow the steps from https://docs.ray.io/en/master/cluster/kubernetes.html, exec inside of the head node (or exec node) and run the provided `example.py`.

Then run `export`.

observer RAY_HEAD_SERVICE_HOST and other environment variables are not present.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

Video: https://www.youtube.com/watch?v=EU3gAoQQIA0&t=1675s (tried with my own custom containers on ARM K3s & the ray latest containers on x86 minikube).

**Comment by richardliaw** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
This environment variable is supposed to be set by Kubernetes assuming a Service named `ray-head` exists:
https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml#L3

The relevant bit of documentation is here:
`https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables`
