### ISSUE TITLE
[tune] how to enforce even integer number in the search space

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13517]
I require my `batch_size` in the search space to be an **even number**, so I tried `tune.qrandint(4, 64, 2)`. However I am also using `HyperOpt` which gave this warning:

> HyperOpt does not support quantization for integer values. Reverting back to 'randint'.

Making certain trials contain odd `batch_size` which produces error in my model. Is there another way to enforce even integer number in the search space?

EDIT:

I also tried `tune.sample_from(lambda spec: np.random.randint(2, 64) * 2)`, and HyperOpt gave error:

> HyperOpt does not support parameters of type `Function` with samplers of type `NoneType`

**Comment by turmeric-blend** [comment]
solved by directly using `np.random.randint(2, 128)*2` in config search space instead of `tune.`

**Comment by turmeric-blend** [comment]
reopening as it actually just returned a constant instead of random even integer between 2 and 128. Issue remains how to  enforce even integer number in the search space?

**Comment by richardliaw** [comment]
Can you try doing a tune.randint, and then in your training function, multiply it by 2?

**Comment by turmeric-blend** [comment]
I assume you mean

```
config={..., 'batch_size': tune.randint(1, 64), ...}


def train_function(config):
      batch_size = config['batch_size']*2
```

I guess it works but then I have to always be aware that my range is half the max range in `randint`

**Comment by krfricke** [comment]
Please note that this has been improved upon in the latest master and the ray nightly wheels. The next release will support quantized integers in hyperopt out of the box (e.g. using `tune.qrandint()`).

Please re-open if you have any more questions.
