### ISSUE TITLE
Factory initialization for Python Actors

### ISSUE THREAD

**Issue by nirvana-msu** [ray-project/ray#13521]
### Describe your feature request

In Java, Ray allows to initialize Actors using a [factory pattern](https://github.com/ray-project/ray/issues/11715#issuecomment-720893290). In Python, however, this is not the case - the only way to create an actor is through `__init__`. Factory pattern (i.e. `@classmethod`) is useful in many situations in Python as well, and it would be great if Ray allowed for that. The best workaround I can think of for now would be to override `__new__` to return deserialized instance (instead of creating new one) - which comes with an extra hurdle of having to overwrite `__init__`s' signature to bypass the parameter validation Ray performs...

Here's a dummy example of what it could look like:

```python
import ray

ray.init()

class Counter:
    def __init__(self):
        self.value = 0

    def increment(self):
        self.value += 1
        return self.value

    @classmethod
    def create(cls, value):
        counter = cls()
        counter.value = value


Counter = ray.remote(Counter.create)

counter_actor = Counter.remote(5)

print(ray.get(counter_actor.increment.remote()))  # should print 6
```

Ray could detect if it gets a `@classmethod`, and treat it as a request to create an Actor using a factory pattern. Alternatively, a more explicit API would also be fine.

**Comment by nirvana-msu** [comment]
I would say this is still relevant.. At the very least I'd like to hear if there are plans to ever support this.

**Comment by Mazyod** [comment]
This is also useful for async actors that require some async calls during initialization, as we don't want to (can't?) use `async __init__(self):`.
