### ISSUE TITLE
[dashboard] constant "Unexpected channel data received" warnings make dashboard.err grow to ~100GB

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#13524]
### What is the problem?

While debugging a head node out-of-disk error, we found that `dashboard.err` for the current session has grown to 90GB in size.  Tailing the last few lines of the file reveals that the following is repeatedly printed:
```
2021-01-18 18:01:22,982 WARNING node_stats.py:317 -- Unexpected channel data received, channel: b'ERROR_INFO:*', data: Failed to load data because of 'ascii' codec can't decode byte 0xd8 in position 11: ordinal not in range(128)
```

It'd be great to fix the underlying issue generating this message, or curtail the maximum # of times this gets printed - FYI, the dashboard UI is functional.

*Ray version and other system information (Python version, TensorFlow version, OS):*
1.0.1post2

**Comment by rkooo567** [comment]
Btw, we will introduce log-rotation to avoid this sort of log-size-explosion issue. Definitely agree the underlying issue should be handled. cc @fyrestone.

**Comment by fyrestone** [comment]
> Btw, we will introduce log-rotation to avoid this sort of log-size-explosion issue. Definitely agree the underlying issue should be handled. cc @fyrestone.

Dashboard and dashboard agent always use the rotation logger, from the first PR of new dashboard. I noticed that this PR https://github.com/ray-project/ray/pull/12101 modify the default rotation size to 500GB. That's too big. I think ~500MB will be enough.

**Comment by fyrestone** [comment]
That's wired. The new dashboard never has the source code file `node_stats.py`. And the new dashboard always uses the log file name `dashboard.log` _(not the `dashboard.err`)_. I think this issue is about the old dashboard. Ray has switched to the new dashboard. Can you try the latest version of ray?

**Comment by rkooo567** [comment]
@fyrestone There's another PR to make it 512MB * 5 backup. 

and yeah. @concretevitamin Is it possible to see if the issue still happens from 1.1.0? We had large transition to our dashboard backend architecture, and that was introduced from 1.1.0

**Comment by concretevitamin** [comment]
Thanks, all; great to hear it's been fixed in a newer version.  We may give
that a try in the future.
