### ISSUE TITLE
[documentation] ray on kubernetes documentation

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#1353]
Can the info from https://github.com/robertnishihara/ray-kubernetes get added to the standard ray documentation or is it too out of date?  Any and all best practices or additional instructions for anyone using ray with kubernetes will be very much appreciated.

**Comment by robertnishihara** [comment]
I think it's out of date but that it should be possible to get it working with relatively minor tweaks. I don't use kubernetes enough (at all really) to be confident in the instructions, so this is an area where contributions from someone with more kubernetes experience would be valuable!

I wrote some instructions on the `instructions` branch of that repository https://github.com/robertnishihara/ray-kubernetes/tree/instructions. Most of those instructions are about how to set up a kubernetes cluster in the first place on GCE. If you already have a kubernetes cluster running, then the instructions should be much simpler.

**Comment by robertnishihara** [comment]
On a related note, @ericl has been building an interface for launching Ray on a cluster (see http://ray.readthedocs.io/en/latest/autoscaling.html). Right now it is targeted at AWS, but it would be a natural to support the same interface with a kubernetes backend.

**Comment by raopku** [comment]
@virtualluke I agree with you.  I think the standard ray documentation should has  instructions for kubernetes.

**Comment by richardliaw** [comment]
This should be done by next week; and as a follow up we can add autoscaler support.
