### ISSUE TITLE
Add detached for Placement Group Creation

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#13541]
### Describe your feature request

There are some problems in the destruction of placement group at present, so, we should support  lifetime="detached".
More details reference to  #13320

**Comment by edoakes** [comment]
@clay4444 I assume if we have lifetime="detached" we will also support names?

**Comment by clay4444** [comment]
> @clay4444 I assume if we have lifetime="detached" we will also support names?
@edoakes 
Placement Group has supported names,  you can find it in `placement_group.py`
`def placement_group(bundles: List[Dict[str, float]],
                    strategy: str = "PACK",
                    name: str = "unnamed_group") -> PlacementGroup:`
I'm not sure if that's what your mean ?

**Comment by clay4444** [comment]
Close
