### ISSUE TITLE
[rllilb] No module named 'ray.rllib.models.torch.modules.reshape' Error when I try to import 'DREAMERTrainer'

### ISSUE THREAD

**Issue by Sangboom** [ray-project/ray#13551]
### What is the problem?

Ray version: 1.1.0
Python version: 3.8.5
OS: Ubuntu 20.04

I have a problem with importing DREAMERTrainer.
It says there is no module named Reshape on 'ray.rllib.models.torch.modules.reshape'.
So I try to find the Reshape function, and I found that one on 'ray.rllib.models.torch.misc'.
Thus, I change 'ray.rllib.models.torch.modules.reshape' into 'ray.rllib.models.torch.misc'.
However, it still didn't work (problem on torch_policy.py).

In addition, Dreamer works properly on ray 1.0.0 which has 'Reshape' function on the dreamer_model python file.
But it didn't work well when I include the same Reshape function on ray 1.1.0's dreamer_model.

Thank you

### Reproduction (REQUIRED)
I've tried this on the new Anaconda environment just install ray and python only (+ other things that ray needs).

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ray.rllib.agents.dreamer import DREAMERTrainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sangbeom/anaconda3/envs/dreamerTest/lib/python3.8/site-packages/ray/rllib/agents/dreamer/__init__.py", line 1, in <module>
    from ray.rllib.agents.dreamer.dreamer import DREAMERTrainer, DEFAULT_CONFIG
  File "/home/sangbeom/anaconda3/envs/dreamerTest/lib/python3.8/site-packages/ray/rllib/agents/dreamer/dreamer.py", line 14, in <module>
    from ray.rllib.agents.dreamer.dreamer_model import DreamerModel
  File "/home/sangbeom/anaconda3/envs/dreamerTest/lib/python3.8/site-packages/ray/rllib/agents/dreamer/dreamer_model.py", line 3, in <module>
    from ray.rllib.models.torch.modules.reshape import Reshape
ModuleNotFoundError: No module named 'ray.rllib.models.torch.modules.reshape'

**Comment by sven1977** [comment]
Thanks for filing this. This is indeed broken. We should also add a simple "compilation" test case, so something like this cannot happen anymore in the future.
This issue has been fixed in master now.
