### ISSUE TITLE
How to realize the transmission of ObjectStore data under different nodes？

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#13557]
Under a node, communication between workers is to achieve zero copy of data through ObjectStore. Under different nodes, data transmission between workers requires a plasma mechanism. I don't quite understand the specific implementation of remote data transmission here. In the code, a Ray's node needs to run two processes, RayLet and Plasma Store, while RayLet needs to maintain a Node Manager and an Object Manager.
1. So if local workers need other Object Store data, do they operate through Object Manager? Does data transmission between nodes use sockets?
2. Can RayLet be used alone, such as providing some APIs? you can use java/scala to write RDD, DataFrame and other data to ObjectStore, and then you can directly read the object through Python/java API to realize process communication in different languages. It also ensures that data is pulled across nodes.
Looking forward to your reply~

**Comment by rkooo567** [comment]
> Ray's node needs to run two processes, RayLet and Plasma Store,
This is no longer true in the recent Ray versions. Raylet process has a plasma store as a thread.

1. Local network among processes is using Unix socket. So if worker needs to access the object in the plasma store, it is done through Unix socket. Remote communication is done with grpc. Data transmission is done by the object manager.
2. This is tried by one of our big contributors (Ant Finanncial). https://docs.ray.io/en/latest/cross-language.html?highlight=cross%20language

**Comment by Matrix-World** [comment]
> 
> 
> > Ray's node needs to run two processes, RayLet and Plasma Store,
> > This is no longer true in the recent Ray versions. Raylet process has a plasma store as a thread.
> 
>     1. Local network among processes is using Unix socket. So if worker needs to access the object in the plasma store, it is done through Unix socket. Remote communication is done with grpc. Data transmission is done by the object manager.
> 
>     2. This is tried by one of our big contributors (Ant Finanncial). https://docs.ray.io/en/latest/cross-language.html?highlight=cross%20language

@rkooo567 
Thank you sincerely for your reply, but I have three other questions that are very confused and need your help. 
I followed the MNIST Tutorial to train an MNIST classifier with Pytorch Lightning's LightningModule and Ray SGD (https://docs.ray.io/en/master/raysgd/raysgd_ptl.html). But currently we still mainly use Torch, so we had trained  an MNIST classifier with Pytorch(not pytorch_lightning) and Ray SGD, Just convert LightningModule to nn.Module and rewrite train_epoch and validate methods( case A).  In another case, only pytorch is used to implement MNIST classifier without using RaySGD(case B). Both cases are DistributedDataParallel， the question as follows:  
1. Then I run the MNIST classifier (epochs=30, use_gpu=True, num_workers=4) of the above two cases(A,B) respectively, and the other models, parameters, and data are all the same. 
    By comparing the total training time (30 epochs), I found that：
    total trian time=82s(in case B), 
    total train time=60s(in case A), when using RaySGD, the training efficiency is accelerated by approximately 26.8%, it is     
    amazing. 
    Then we output the training time of each GPU under each epoch:
     each train time~3.0s (in case B)
     each train time~3.7s (in case A)， when using RaySGD, the each training efficiency in every GPU is accelerated,   
     30*(3.7-3)s is approximately equal to (82-60)s.
     So I want to know whether the data transmission between GPUs is optimized when using RaySGD with Pytorch for Multi-GPU training. In addition, I saw that backend=nccl can be set in trainer = TorchTrainer(), which means that RaySGD with Pytorch implements All-Reduce and still uses Pytorch's own process communication mechanism. So I am confused, what causes the above acceleration effect? 
2.  According to the Running benchmarks and introduction(https://github.com/ray-project/ray/tree/master/python/ray/util/sgd/torch/examples/benchmarks), the Ray is just wrapping Pytorch DistributedDataParallel. Does RaySGD affect Pytorch's NCCL? 
3. According to the introduction of RaySGD, trainer = TorchTrainer(
     training_operator_cls=CustomeTrainingOperator,
     num_workers=num_workers,
     config=config,
     use_gpu=True
), TorchTrainer will use the CustomTrainingOperator class instance as a set of Ray Actors, and then distribute them on multiple GPUs for distributed training, then whether the data generated by these Actors during the running process (such as the train_epoch method) will be stored in the Object Store, In the All-Reduce process, can other GPU processes be directly obtained from the Object Store, leading to the aforementioned acceleration effect? I just guess.
Sincerely look forward to your reply ？
