### ISSUE TITLE
[ray_client] Cannot instantiate imported actor class

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13562]
### What is the problem?

Get a "ray is not connected" error when trying to instantiate an actor class that was imported

`c.py`:
```python
import ray

@ray.remote
class C:
    pass
```

`test.py`:
```python
from c import C

import ray
ray.util.connect("localhost:61234")

c = C.remote()
```

Output:
```
(base) code/ray % python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    c = C.remote()
  File "/Users/eoakes/code/ray/python/ray/actor.py", line 410, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/Users/eoakes/code/ray/python/ray/actor.py", line 557, in _remote
    worker.check_connected()
  File "/Users/eoakes/code/ray/python/ray/worker.py", line 207, in check_connected
    raise RaySystemError("Ray has not been started yet. You can "
ray.exceptions.RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/13272
