### ISSUE TITLE
[Core] Actor is still alive when exception raised in constructor.

### ISSUE THREAD

**Issue by lixin-wei** [ray-project/ray#13578]
### What is the problem?

Now if an exception is raised in actor's constructor, actor will be ALIVE and remember this exception, then reraise this error in incoming tasks.

In normal programming, when you have exceptions in class's constructor, this class will not be created successfully. But in ray's actor, it will be created successfully. This inconsistency will make user confused.

After discussion, we want to make actor DEAD when constructor has exceptions, **and don't trigger restart even when `num_restarts` is set.** 

For implementation, we want to save exceptions in GCS and publish it to all workers. Once caller find the callee actor is DEAD and has exception info, caller will throw exceptions in ray.get().

This change won't break original behavior, exception info will still be thrown in caller. And besides, the exception information won't be lost since we store it in GCS instead of memory. This can address the issue that, when actor is killed, exception information will be lost.

What do you think about this solution? I want to know your ideas, if you all agree, I'll open a PR to implement this solution.

**Comment by lixin-wei** [comment]
We've already discussed a lot in this PR: https://github.com/ray-project/ray/pull/13334. Now we move here to discuss our new sulotion.

@stephanie-wang @ericl @robertnishihara @raulchen

**Comment by ericl** [comment]
This seems pretty reasonable, since it mirrors the behavior of tasks as permanently failing on an app level exception.

When you say publish to all workers btw, is that a potential scalability issue?

**Comment by raulchen** [comment]
We don't have to publish the info to "all workers". We can just save it in the actor table, and callers to this actor will subscribe to this and get the exception. Then we the callers call "ray.get", they will receive the exception.

**Comment by lixin-wei** [comment]
> We don't have to publish the info to "all workers". We can just save it in the actor table, and callers to this actor will subscribe to this and get the exception. Then we the callers call "ray.get", they will receive the exception.

Yes, this is exactly what I meant. Use GCS's pub/sub. @ericl

**Comment by raulchen** [comment]
I think this approach is better than the previously mentioned ones, because:
- it mimics the same behavior in a single-process program. 
- No API changes are required. And from users' perspective, the behavior is still the same.
- It fixes the issue the the worker process is still running and wasting resources.

**Comment by rkooo567** [comment]
When the actors are re-created, are they retried aggressively? One concern I have is when actor of max_restart=-1 that has errors in the constructor is created, it will spam the GCS server.

**Comment by lixin-wei** [comment]
> When the actors are re-created, are they recreated aggressively? One concern I have is when actor of max_restart=-1 that has errors in the constructor is created, it will spam the GCS server.

@rkooo567 Actor won't be recreated once has exceptions in the constructor. I mentioned it in my first comment:

> After discussion, we want to make actor DEAD when constructor has exceptions, and don't trigger restart even when num_restarts is set.

**Comment by raulchen** [comment]
@ericl @stephanie-wang @rkooo567 do you have other comments? should we proceed with this approach?

**Comment by ericl** [comment]
LGTM
