### ISSUE TITLE
Cloudpickle Version mismatch when using custom built ray on a cluster

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1357]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: fa3a41366cf25dd5244873a705988de98f76a6ac
- **Python version**: 
```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
```

### Describe the problem
Start a cluster as described in http://ray.readthedocs.io/en/latest/using-ray-on-a-large-cluster.html, attach a driver on the head node and connect to Ray. You will find the a version missmatch like so:

```
In [3]: ray.services._compute_version_info()
Out[3]: 
('0.3.0',
 '/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/__init__.py',
 '3.6.3',
 '0.4.0',
 None)

In [4]: ray.worker.global_worker.redis_client.get("VERSION_INFO")
Out[4]: b'["0.3.0", "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray-0.3.0-py3.6-linux-x86_64.egg/ray/__init__.py", "3.6.3", "0.5.2", null]'
```

**Comment by pcmoritz** [comment]
The problem here is that we have cloudpickle pinned to 0.5.2 so ray start will find that, but the interactive interpreter might have another version installed.

**Comment by robertnishihara** [comment]
The solution is probably to bring cloudpickle inside the repository. In that case, we'll need to keep track of more fine-grained versions of Ray, probably by doing what TensorFlow does to keep track of the git version https://github.com/tensorflow/tensorflow/search?utf8=%E2%9C%93&q=git_version&type=
