### ISSUE TITLE
[tune] Errors when using points_to_evaluate argument for a few search algos

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13576]
I am trying out a few search algos (run from scratch) with Ray version 1.1.0, and is running into a few issues when using `points_to_evaluate` argument:

Search Space Setup:
```
even_int_model_dim = [x for x in range(1, 12+1) if x % 2 == 0]
even_int_batch_size = [x for x in range(1, 16+1) if x % 2 == 0]
int_sequence = [x for x in range(20, 100+1)]
int_local_context_len = [x for x in range(3, 15+1)]
int_num_heads = [x for x in range(2, 6+1)]

config={'seed': 0, 'train_start_date': 'None', 'valid_start_date': '2017-01-01', 'test_start_date': '2018-01-01',
	'data_path': 'path/to/data', 'num_epoch': 100, 'loss_fn': loss_fn, 'device': 'cuda:0', 
	'sequence': tune.choice(int_sequence),
	'local_context_len': tune.choice(int_local_context_len), 'batch_size': tune.choice(even_int_batch_size), 'num_heads': tune.choice(int_num_heads),
	'model_dim': tune.choice(even_int_model_dim), 'num_layers': tune.choice([1, 2]), 'dropout': tune.uniform(0, 0.7),
	'allocator': 'numark', 'max_weight': 0.1, 'stochasticity': tune.choice([True, False]),
	'resample': False, 'n_draws': 100, 'n_portfolios': 5, 'feature_dims': 0, 
	'learning_rate': 0.001, 'beta1': 0.9, 'beta2': 0.999, 
	'eps': 0.00000001, 'weight_decay': 0, 'amsgrad': True}

current_best = [{'sequence': 100, 'local_context_len': 5, 'batch_size': 16, 
		 'num_heads': 6, 'model_dim': 12, 'num_layers': 1, 'dropout': 0.01, 'stochasticity': False}]
```

When using `HyperOpt`:
`algo = HyperOptSearch(points_to_evaluate=current_best)`
Error:
> File "/home/user/anaconda3/envs/user/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 874, in rec_eval
>     rval_var = node.pos_args[int(switch_i) + 1]
> IndexError: list index out of range

When using `Optuna`:
`algo = OptunaSearch(points_to_evaluate=current_best)`
Error:
> TypeError: __init__() got an unexpected keyword argument 'points_to_evaluate'

When using `Ax`:
`algo = AxSearch(points_to_evaluate=current_best)`
Error:
> TypeError: __init__() got an unexpected keyword argument 'points_to_evaluate'

**Comment by krfricke** [comment]
Hi @turmeric-blend, which version of Ray are you using? The `points_to_evaluate` arguments are currently only available in the nightly wheels / current master and not in the latest release.
You can try `ray install-nightly` to install the nightly wheels.

**Comment by turmeric-blend** [comment]
ok thanks
