### ISSUE TITLE
[autoscaler] request_resources demands don't update after multiple calls

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13575]
### What is the problem?

There seems to be a problem where request_resources values don't change if request_resources is called multiple times. 

```
request_resources(bundles=[{"CPU": 1}])
sleep(10)
request_resources(bundles=[{"CPU": 2}])
```

will result in a permanent request for a single CPU. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
cc @ericl @AmeerHajAli

**Comment by ericl** [comment]
I think this is fixed in nightly (at least it works for me, checking `ray status` locally).
