### ISSUE TITLE
"Handling Large Datasets" within hyperparameter_search 

### ISSUE THREAD

**Issue by smn57** [ray-project/ray#13585]
Is there the possibility to handle large datasets as described in the [user-guide](https://docs.ray.io/en/latest/tune/user-guide.html#handling-large-datasets) within [hyperparameter_search](https://huggingface.co/transformers/main_classes/trainer.html#transformers.Trainer.hyperparameter_search) by Huggingface? 

However, I want to use `t5-large` and it happens the dataset size does not matter, the model itself is very big and triggers `redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer`. I hoped to prevent this error by using `tune.with_parameters`. Or is there any other solution to that?

**Comment by richardliaw** [comment]
Hey @smn57 this is a similar issue to https://github.com/huggingface/transformers/issues/9146. We're going to prioritize this this week!

**Comment by richardliaw** [comment]
Should be addressed with the latest transformers!

**Comment by smn57** [comment]
Working smoothly, thank's for the attention!
