### ISSUE TITLE
[rllib][DQN] unable to restore checkpoint after TF variables renaming

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#13598]
### What is the problem?

- Ray version: 0.8.6 & 1.1.0
- Tensorflow version: 2.3.1
- Python version: 3.8.5

Since 01125b8fcfce88472c2e20d116bc6662032088e0 (so problem starts to occur in `0.8.7`), TF variables naming has changed in `distributional_tf_q_model.py`. Debugging variable names in 0.8.6 gives following result (`q_model`):

```
00 = {ResourceVariable} <tf.Variable 'default_policy/fc_1/kernel:0' shape=(12, 400) dtype=float32>
01 = {ResourceVariable} <tf.Variable 'default_policy/fc_1/bias:0' shape=(400,) dtype=float32>
02 = {ResourceVariable} <tf.Variable 'default_policy/fc_out/kernel:0' shape=(400, 300) dtype=float32>
03 = {ResourceVariable} <tf.Variable 'default_policy/fc_out/bias:0' shape=(300,) dtype=float32>
04 = {ResourceVariable} <tf.Variable 'default_policy/value_out/kernel:0' shape=(400, 1) dtype=float32>
05 = {ResourceVariable} <tf.Variable 'default_policy/value_out/bias:0' shape=(1,) dtype=float32>
06 = {ResourceVariable} <tf.Variable 'default_policy/q_func/action_value/hidden_0/kernel:0' shape=(300, 256) dtype=float32>
07 = {ResourceVariable} <tf.Variable 'default_policy/q_func/action_value/hidden_0/bias:0' shape=(256,) dtype=float32>
08 = {ResourceVariable} <tf.Variable 'default_policy/q_func/action_value/dense/kernel:0' shape=(256, 2652) dtype=float32>
09 = {ResourceVariable} <tf.Variable 'default_policy/q_func/action_value/dense/bias:0' shape=(2652,) dtype=float32>
10 = {ResourceVariable} <tf.Variable 'default_policy/q_func/state_value/dense_1/kernel:0' shape=(300, 256) dtype=float32>
11 = {ResourceVariable} <tf.Variable 'default_policy/q_func/state_value/dense_1/bias:0' shape=(256,) dtype=float32>
12 = {ResourceVariable} <tf.Variable 'default_policy/q_func/state_value/dense_2/kernel:0' shape=(256, 51) dtype=float32>
13 = {ResourceVariable} <tf.Variable 'default_policy/q_func/state_value/dense_2/bias:0' shape=(51,) dtype=float32>
```

while in 0.8.7 (and onwards):

```
 00 = {ResourceVariable} <tf.Variable 'default_policy/fc_1/kernel:0' shape=(12, 400) dtype=float32>
 01 = {ResourceVariable} <tf.Variable 'default_policy/fc_1/bias:0' shape=(400,) dtype=float32>
 02 = {ResourceVariable} <tf.Variable 'default_policy/fc_out/kernel:0' shape=(400, 300) dtype=float32>
 03 = {ResourceVariable} <tf.Variable 'default_policy/fc_out/bias:0' shape=(300,) dtype=float32>
 04 = {ResourceVariable} <tf.Variable 'default_policy/value_out/kernel:0' shape=(400, 1) dtype=float32>
 05 = {ResourceVariable} <tf.Variable 'default_policy/value_out/bias:0' shape=(1,) dtype=float32>
 06 = {ResourceVariable} <tf.Variable 'default_policy/hidden_0/kernel:0' shape=(300, 256) dtype=float32>
 07 = {ResourceVariable} <tf.Variable 'default_policy/hidden_0/bias:0' shape=(256,) dtype=float32>
 08 = {ResourceVariable} <tf.Variable 'default_policy/dense/kernel:0' shape=(256, 2652) dtype=float32>
 09 = {ResourceVariable} <tf.Variable 'default_policy/dense/bias:0' shape=(2652,) dtype=float32>
 10 = {ResourceVariable} <tf.Variable 'default_policy/dense_1/kernel:0' shape=(300, 256) dtype=float32>
 11 = {ResourceVariable} <tf.Variable 'default_policy/dense_1/bias:0' shape=(256,) dtype=float32>
 12 = {ResourceVariable} <tf.Variable 'default_policy/dense_2/kernel:0' shape=(256, 51) dtype=float32>
 13 = {ResourceVariable} <tf.Variable 'default_policy/dense_2/bias:0' shape=(51,) dtype=float32>
```

Notice the missing `q_func/action_value` and `q_func/target_value` prefixes which were present in `0.8.6` thanks to TF scope. Same goes for target Q model.

This leads to only partial reloading of weights when checkpoint is restored, and some layers get randomly initialized. Agent performance is thus bad and random. I've tested reverting to previous naming convention of layers and it does fix the issue. There is a similar issue reported in https://github.com/ray-project/ray/issues/13132, but it affects pytorch and for same training and restoring versions.

Possible actions:
- in `distributional_tf_q_model.py`, the `prefix` variable is no longer used for action and state layers, only for noisy layer. Not sure it's intended, but there's a chance it gets used again in the future, leading to same reloading problems. Should variables naming be fixed once for all?
- add a warning in `tf_utils.set_weights` when not all reloaded weights get assigned
- force automatic assignment of weights when variable names don't match. There are certainly lot of edge cases though.

### Reproduction (REQUIRED)

Steps to reproduce:
1. train an agent with version 0.8.6 and save model
2. reload model with any version between 0.8.7 and 1.1.0
3. observe reloaded agent performance has dropped, and gives a different result for a given space state on every reload.

**Comment by sven1977** [comment]
Thanks for filing this @antoine-galataud !
Yeah, one solution could even be:
loop through model's variables (v):
- check, whether we find v's name in the list of loaded variables
- if not, check the names of all loaded variables that have the same shape and pick the one with the closest name to v's name.
- if no match found for v: error
