### ISSUE TITLE
How to get best model checkpoint after program ends with a few ERROR trial runs?

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13590]
Currently, this is how I get the best model checkpoint after training has ended.
```
analysis = tune.run(...)

# load model for inference/testing
model = torch.load(analysis.best_checkpoint+'model.pth')
```
However, if some trials run into **TuneError**, the programs end abruptly **after** `tune.run` finishes going through all `num_samples` like so:
```
analysis = tune.run(...) 
<---------------- program ends here and raises TuneError ---------------->
raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [runner_46a17c71, runner_27c01c26, runner_79feafd4, runner_01cd356c, runner_1a7e0f28, runner_0c64284a, runner_49e73fe0, runner_a9086918, runner_c889d2f4])

# load model for inference/testing  <---- not run
model = torch.load(analysis.best_checkpoint+'model.pth')  <---- not run
```

So I try the `Analysis` method to get best model checkpoint after program ends, but there is no way to get it automatically without defining a `Trial` instance:
```
from ray.tune import Analysis

ray_run = '/home/user/Documents/ml/src_ray/ray_results/runner_2021-01-20_13-49-35'
analysis = Analysis(experiment_dir=ray_run, default_metric='loss_valid', default_mode='min')

analysis.get_best_logdir() # this method gets up to the best model folder but not the best checkpoint

analysis.get_best_checkpoint() # requires a Trial class
```
Now the question is how do I define the `Trial` class properly? Or is there a better way to get best model checkpoint path in the case where `tune.run` ends with a few error trials.

**Comment by arx7ti** [comment]
Just got same issue. Tried to use 
`best_trial_dir = analysis.get_best_logdir()
best_checkpoint = analysis.get_best_checkpoint(
    best_trial_dir, metric="map", mode="max")` 
but this leads to error: ...has zero or more than one tune_metadata.
Therefore, I resolved original problem by updating arguments for `tune.run()` with `resume=True` and `raise_on_failed_trial=False`. Then, the analysis instance is now able to return values from `get_best_trial()` and `get_best_checkpoint()` successfully.
