### ISSUE TITLE
GPU is too expensive. SIMD is better to provide high performance. Can ray provide some simd utility?

### ISSUE THREAD

**Issue by ggservice007** [ray-project/ray#13593]
Many high performance projects or libraries use the SIMD to accelerate such as apache arrows and pysimdjson

Apache Arrows
https://arrow.apache.org/overview/

![Snip20210121_1](https://user-images.githubusercontent.com/9192908/105284714-fd4d2400-5bed-11eb-9f50-346799c7fbd0.png)

pysimdjson

https://github.com/TkTech/pysimdjson

Python bindings for the simdjson project, a SIMD-accelerated JSON parser. If SIMD instructions are unavailable a fallback parser is used, making pysimdjson safe to use anywhere.

 Data-Parallel Programming via SIMD Vector Types

Can we some simd to parallel programming?

**Comment by ggservice007** [comment]
[year_2015_data_parallel_via_simd_vector_type.pdf](https://github.com/ray-project/ray/files/5847146/year_2015_data_parallel_via_simd_vector_type.pdf)

![Snip20210121_3](https://user-images.githubusercontent.com/9192908/105285714-e90a2680-5bef-11eb-84d3-2aaaaf967c9b.png)



The ray  base layer is implemented by using C++.  So we can write some simd utility to provide the Python user.

**Comment by wuisawesome** [comment]
Hey, Ray shouldn't interfere with the native execution of other libraries which rely on SIMD instructions (so you should get the full power of SIMD from pytorch/tensorflow/arrow already). Could your provide an example where you thing Ray isn't doing/performing the way you expect it to?

**Comment by ggservice007** [comment]
I am developing a project which SIMD version [cuGraph](https://github.com/rapidsai/cugraph). 

The first step is to implement the SIMD [cudf](https://github.com/rapidsai/cudf).

I am implmeneting the SIMD DataFrames based on vaex or its ideas.

Vaex uses ApacheArrow data structures and C++ to speed up string operations.

Vaex is a high performance Python library for lazy Out-of-Core DataFrames (similar to Pandas), to visualize and explore big tabular datasets. It calculates statistics such as mean, sum, count, standard deviation etc, on an N-dimensional grid for more than a billion (10^9) samples/rows per second. 

https://github.com/vaexio/vaex

The next step is to use the parallel functionality provided by Ray.

**Comment by wuisawesome** [comment]
I see, you can run any code that you can put in a python module (including any compiled cython) and Ray will just faithfully execute it.

**Comment by ggservice007** [comment]
Nice, more and more libraries to support SIMD.  The numpy also supports SIMD after 1.20.0. 

![image](https://user-images.githubusercontent.com/9192908/106245594-ab3c7c00-6247-11eb-83dd-e3bec54abf8d.png)


https://github.com/numpy/numpy/releases/tag/v1.20.0rc2
