### ISSUE TITLE
Issue on page /cluster/index.html

### ISSUE THREAD

**Issue by MaximeBouton** [ray-project/ray#13605]
This code:
```python
import time

@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```

 from the documentation seems outdated as it throws 
```
AttributeError: module 'ray' has no attribute 'services'
```

**Comment by wuisawesome** [comment]
Thanks for the heads up. We should definitely update the docs, but using `ray.nodes()` is a much better way of getting the ip address of all the nodes in the cluster.

**Comment by rkooo567** [comment]
Should be handled with better public/private API annoation
