### ISSUE TITLE
Shared memory auto-detection is not working

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#13619]
### What is the problem?
On a m5.16xlarge instance, I'm getting this error when running `ray microbenchmark` with autoscaler default docker:
```
2021-01-20 16:57:03,655 WARNING services.py:1628 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 46198665216 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=Xgb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 2gb.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @ijrsvt?  I remember you brought up about adding auto-setting shm but not sure if it is introduced.

**Comment by rkooo567** [comment]
Also, @simon-mo did you follow this message?

```
If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=Xgb' to 'docker ru
```

**Comment by simon-mo** [comment]
The auto shm-size seems accurate. The thing is the detached /dev/shm is 46G, which is definitely more than 2G

**Comment by ijrsvt** [comment]
I think that error is technically correct :O 
The formula for memory size is: 
```
available_memory * DEFAULT_OBJECT_STORE_MEMORY_PROPORTION
(~256) * 0.3 = 76.8 GiB
```
Now I think the main concern is that available_memory = `total_memory - memory_in_use` and there may be different memory usage between when the container is not started and when it is running. That said,  the level of difference is **hugee**

**Comment by AmeerHajAli** [comment]
@ijrsvt should we close this issue?

**Comment by ijrsvt** [comment]
@AmeerHajAli Yes we should!
