### ISSUE TITLE
[rllib] No "eager" in trainer configuration

### ISSUE THREAD

**Issue by kevin1zc** [ray-project/ray#13613]
### What is the problem?
I am building a custom TFModelV2 that uses LSTM layers, and I need to enable eager execution to use cuDNN acceleration. According to RLlib documentation, I should set `config["eager"]: True` in trainer config, but I got the error `Exception: Unknown config parameter 'eager'`. I then tried the sample code at [https://docs.ray.io/en/latest/rllib-training.html#basic-python-api](url), and got the exact same error. Could you please check if this is a bug in the source code?

*Ray version and other system information (Python version, TensorFlow version, OS):
-Ray version: 1.1.0
-Python version: 3.6.9
-TensorFlow version: 2.4.0
-OS: Ubuntu 18.04.5 LTS*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print

ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0
config["num_workers"] = 1
config["eager"] = True
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
```
This code is directly from the RLlib documentation and changes `config["eager"]` from `False` to `True`.

- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
- [x] I have verified my script runs in a clean environment and reproduces the issue.

**Comment by ReCodeLife** [comment]
I had the same problem when I use ppo to run other sample code.so I look in the code for the keyword "eager".I see that maybe the code has changed. when I use `config={"framework": 'tfe',"num_workers": 0})`,the code are working.

**Comment by sven1977** [comment]
Thanks for filing this @kevin1zc and for the answer @ReCodeLife !
Yes, "eager" has been deprecated since Ray 1.x. Please use framework="tfe" or "tf2", instead.
Closing this issue.
