### ISSUE TITLE
[autoscaler] Add support for podman in Ray's autoscaler command line tool

### ISSUE THREAD

**Issue by jCrompton** [ray-project/ray#13617]
As of now there is no good way to run the autoscaler with podman rather than docker, I tried setting 'docker' as an alias to podman in the initialization_commands section to no avail. 

Happy to share more details if necessary

**Comment by ijrsvt** [comment]
Hey @jCrompton Thanks for suggesting this! Would you be interested in contributing this change to Ray? It should be as simple as just changing the `docker_command_runner` to optionally using `podman` instead of `docker` for all the commands! I'd be more than willing to help you with the process!

**Comment by jCrompton** [comment]
Sure thing, I'm guessing all these changes would be in the `DockerCommandRunner` class? Ideally defined by the `docker_config` arg?

**Comment by jCrompton** [comment]
How do I get access to the codebase?

**Comment by jCrompton** [comment]
e.g. permission to push to branches

**Comment by ijrsvt** [comment]
@jCrompton 

> Sure thing, I'm guessing all these changes would be in the `DockerCommandRunner` class? Ideally defined by the `docker_config` arg?

Yep! I left a few more comments about places to make these changes!

> How do I get access to the codebase?
It looks like you made a fork and that is great! Once this PR is ready for merge, someone with permissions will merge it in. Some more info is available [here](https://docs.ray.io/en/master/getting-involved.html#submitting-and-merging-a-contribution).

**Comment by jCrompton** [comment]
> @jCrompton
> 
> > Sure thing, I'm guessing all these changes would be in the `DockerCommandRunner` class? Ideally defined by the `docker_config` arg?
> 
> Yep! I left a few more comments about places to make these changes!
> 
> > How do I get access to the codebase?
> 
> It looks like you made a fork and that is great! Once this PR is ready for merge, someone with permissions will merge it in. Some more info is available [here](https://docs.ray.io/en/master/getting-involved.html#submitting-and-merging-a-contribution).

Done

**Comment by ijrsvt** [comment]
@jCrompton thanks for adding the schema! I think just fixing `docker.py` and adding a test (I would suggest copying [`test_autoscaler.py::testGetOrCreateHeadNode`](https://github.com/ray-project/ray/blob/da5928304a22d81b3623302767c4a89da4391e8f/python/ray/tests/test_autoscaler.py#L395) and changing all the "docker"s to "podman"s)
