### ISSUE TITLE
[Placement Group] Support Named Placement Group

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#13625]
### Describe your feature request

Now, the name we specified when we create placement group was just a label, in order to better support placement group sharing among jobs, we should support `Named placement group` like `Named Acror`

**Comment by rkooo567** [comment]
This simply means we will implement get_placement_group(name=“”)?

**Comment by clay4444** [comment]
hm... I think the api should like `ray.get_placement_group("name")` because the name should unique in a ray cluster ?

**Comment by clay4444** [comment]
> This simply means we will implement get_placement_group(name=“”)?

hm... I think the api should like `ray.get_placement_group("name")` because the name should unique in a ray cluster ?

**Comment by clay4444** [comment]
cc @ffbin

**Comment by clay4444** [comment]
cc @jovany-wang

**Comment by raulchen** [comment]
In Java-API for named actors, there is an optional flag "global", which means whether a named actor is internal to a job or available in the whole cluster.
We can do something similar to PGs.

**Comment by clay4444** [comment]
Done
