### ISSUE TITLE
[core] ray.put takes longer when called inside an Actor class.

### ISSUE THREAD

**Issue by vishal00100** [ray-project/ray#13638]
I've noticed that `ray.put` is twice as slow if it's called in an `Actor` class.

In this code `ray.put` takes about 40ms.

```python
import ray
import numpy as np
from tqdm import tqdm
import time
from ray.util.metrics import Count, Gauge

def run():
    put_count = Count(name="repro_put_count")
    put_gauge = Gauge(name="repro_put_gauge")
    for ridx in tqdm(range(1000000000), desc="Main loop"):
        stime = time.time()
        object_ref = ray.put(np.zeros((3, 3000, 5000, 1)))
        put_gauge.record((time.time() - stime) * 1000)
        put_count.record(1.)

if __name__ == '__main__':
    print(ray.init(_metrics_export_port=58391))
    print(ray.cluster_resources())
    run()
```
![image](https://user-images.githubusercontent.com/29234773/105539445-c137c300-5cc2-11eb-8cf9-7efce74ecdde.png)

whereas in this code it takes about 80ms.

```python
import ray
import numpy as np
from tqdm import tqdm
import time
from ray.util.metrics import Count, Gauge

@ray.remote
class Actor1:

    def __init__(self):
        self.put_count = Count(name="repro_put_count")
        self.put_gauge = Gauge(name="repro_put_gauge")

    def do_stuff(self):
        stime = time.time()
        object_ref = ray.put(np.zeros((3, 3000, 5000, 1)))
        self.put_gauge.record((time.time() - stime) * 1000)
        self.put_count.record(1.)
        return object_ref


def run():
    actor1 = Actor1.remote()
    for ridx in tqdm(range(1000000000), desc="Main loop"):
        object_ref = ray.get(actor1.do_stuff.remote())

if __name__ == '__main__':
    print(ray.init(_metrics_export_port=58391))
    print(ray.cluster_resources())
    run()
```
![image](https://user-images.githubusercontent.com/29234773/105539688-14aa1100-5cc3-11eb-9f57-18f944712d9a.png)

Can someone explain why `ray.put` is twice as slow in an `Actor` class?

Thanks in advance.

**Comment by vishal00100** [comment]
I had some background tasks running that was slowing down `ray.put`. Closing this issue.

**Comment by rkooo567** [comment]
@vishal00100 Is the background task the cause of your ray.put getting slower as well in other issue? It seems like the ray.put latency seems to be stable here.

**Comment by vishal00100** [comment]
@rkooo567 No I didn't anything else running then. 

For posterity - this is the [other issue](https://github.com/ray-project/ray/issues/13612)
