### ISSUE TITLE
[rllib] rewards column is being discarded when using PG

### ISSUE THREAD

**Issue by dibgerge** [ray-project/ray#13646]
### What is the problem?

Ray version: nightly build
DL package: Torch

The [documentation](https://docs.ray.io/en/master/rllib-sample-collection.html#how-does-rllib-determine-which-views-are-required) mentions that **rewards** column is never deleted, however when using `PGTorchPolicy` and `PGTorchTrainer`, only the `advantages` column is available, and there is no `reward`. 

This prohibits using offline algorithm, like re-creating the offline datasets example in the [docs here](https://docs.ray.io/en/master/rllib-offline.html).

### Reproduction (REQUIRED)

Can be recreated by following the offline datasets example. Generate data with PG: 

```
rllib train
    --run=PG \
    --env=CartPole-v0 \
    --config='{"output": "/tmp/cartpole-out", "output_max_file_size": 5000000}' \
    --stop='{"timesteps_total": 100000}'
```

Looking at the outputs json file for this training, there are no `rewards` field. Also, when using the generated data to train DQN, it fails with `KeyError: rewards` (and `KeyError`: `new_obs`). 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Taking a look. ...
Workaround for now: `_use_trajectory_view_api=False`.
Sorry about the delay. I thought this was fixed in an earlier PR, but it wasn't.
This PR here (see above) fixes the issue for both torch and tf. It makes sure that certain "core" keys are always available in the loss/output, such as rewards, dones, infos, etc..

**Comment by sven1977** [comment]
@dibgerge, thanks for filing this!
