### ISSUE TITLE
using ray java actor in cluster mode will not run application 

### ISSUE THREAD

**Issue by liuyongvs** [ray-project/ray#13644]
### What is the problem?
when i use ray java actor in cluster mode will not run application on ray version 1.0.1.
i fould it could run in SINGLE_PROCESS while can not in CLUSTER.

i do following this, which is a simple counter problem:
1.  ray start --head --code-search-path=/mnt/disk1/ly/lib/log4j-1.2.17.jar:/mnt/disk1/ly/lib/disk1/ly/flink-1.12.0/lib/log4j-slf4j-impl-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-core-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-api-2.12.1.jar:/mnt/disk1og4j-1.2-api-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table-blink_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.zookeeper-3.4.14.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-json-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-dist_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-ck1/ly/flinkOnRay-1.0-SNAPSHOT.jar --dashboard-host  10.192.78.61
  or do not use code-search-path
2. ray start --address='10.192.78.61:6379' --redis-password='5241590000000000' --code-search-path=/mnt/disk1/ly/lib/log4j-1.2.17.jar:/mnt/disk1/ly/lib/disk1/ly/flink-1.12.0/lib/log4j-slf4j-impl-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-core-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-api-2.12.1.jar:/mnt/disk1og4j-1.2-api-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table-blink_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.zookeeper-3.4.14.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-json-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-dist_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-ck1/ly/flinkOnRay-1.0-SNAPSHOT.jar
 or do not use code-search-path
3. /usr/lib/cloudmanager/components/lark/misc/jdk/bin/java '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5555' -cp /mnt/disk1/ly/flinkOnRay-1.0-SNAPSHOT.jar -Dlog.file=/mnt/disk1/ly/flink-ray-session.log -Dlog4j.configuration=file:/mnt/disk1/ly/flink-1.12.0/conf//log4j-session.properties -Dlog4j.configurationFile=file:/mnt/disk1/ly/flink-1.12.0/conf//log4j-session.properties -Dlogback.configurationFile=file:/mnt/disk1/ly/flink-1.12.0/conf//logback-session.xml -Dray.address=10.192.78.61:6379 -Dray.node-ip=10.192.78.61 -Dray.job.code-search-path=/mnt/disk1/ly/lib/log4j-1.2.17.jar:/mnt/disk1/ly/lib/disk1/ly/flink-1.12.0/lib/log4j-slf4j-impl-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-core-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/log4j-api-2.12.1.jar:/mnt/disk1og4j-1.2-api-2.12.1.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table-blink_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-table_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.zookeeper-3.4.14.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-json-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-dist_2.11-1.12.0.jar:/mnt/disk1/ly/flink-1.12.0/lib/flink-ck1/ly/flinkOnRay-1.0-SNAPSHOT.jar org.apache.flink.container.entrypoint.Counter

ERRO:
F0123 14:22:08.193676 70431 70433 raylet_client.cc:57] Could not connect to socket /tmp/ray/session_2021-01-23_14-21-38_064261_63237/sockets/raylet
*** Check failure stack trace: ***
    @     0x7f06739f79cd  google::LogMessage::Fail()
    @     0x7f06739f8ec3  google::LogMessage::SendToLog()
    @     0x7f06739f769a  google::LogMessage::Flush()
    @     0x7f06739f78d1  google::LogMessage::~LogMessage()
    @     0x7f06739abd98  ray::RayLog::~RayLog()
    @     0x7f06736bb17d  ray::raylet::RayletConnection::RayletConnection()
    @     0x7f06736bb3f6  ray::raylet::RayletClient::RayletClient()
    @     0x7f067363de19  ray::CoreWorker::CoreWorker()
    @     0x7f0673641a90  ray::CoreWorkerProcess::CreateWorker()
    @     0x7f067364261f  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x7f0673642f6a  ray::CoreWorkerProcess::Initialize()
    @     0x7f06735c5e17  Java_io_ray_runtime_RayNativeRuntime_nativeInitialize

raylet.err
F0123 14:21:48.917438 63597 63597 worker_pool.cc:888]  Check failed: state != states_by_lang_.end() Required Language isn't supported.
*** Check failure stack trace: ***
    @     0x555eabe80d3d  google::LogMessage::Fail()
    @     0x555eabe821ac  google::LogMessage::SendToLog()
    @     0x555eabe80a19  google::LogMessage::Flush()
    @     0x555eabe80c31  google::LogMessage::~LogMessage()
    @     0x555eabe352b9  ray::RayLog::~RayLog()
    @     0x555eabaf01df  ray::raylet::WorkerPool::GetStateForLanguage()
    @     0x555eabaf778b  ray::raylet::WorkerPool::RegisterDriver()
    @     0x555eabb4cc4e  ray::raylet::NodeManager::ProcessRegisterClientRequestMessage()
    @     0x555eabb52242  ray::raylet::NodeManager::ProcessClientMessage()
    @     0x555eabac2ec0  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZNS1_6raylet6Raylet12HandleAcceptERKN5boost6system10error_codeEEUlS3_lS8_E0_E9_M_invokeERKSt9_Any_dataS3_lS8_
    @     0x555eabe1b0ae  ray::ClientConnection::ProcessMessage()
    @     0x555eabe17f6a  boost::asio::detail::read_op<>::operator()()
    @     0x555eabe18fb2  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @     0x555eac18370f  boost::asio::detail::scheduler::do_run_one()
    @     0x555eac184c11  boost::asio::detail::scheduler::run()
    @     0x555eac185c42  boost::asio::io_context::run()
    @     0x555eaba98cbc  main
    @     0x7fcdcee61555  __libc_start_main
    @     0x555eabaab621  (unknown)

**Comment by rkooo567** [comment]
cc @kfstorm 

> F0123 14:21:48.917438 63597 63597 worker_pool.cc:888] Check failed: state != states_by_lang_.end() Required Language isn't supported.

Is there any other thing he should do setup Java workers?

**Comment by kfstorm** [comment]
@liuyongvs Could you help check if `java` is in `PATH` when you run `ray start`.

**Comment by liuyongvs** [comment]
hi @kfstorm , i  try it and it also could not work. Could i add your Wechat(微信)？

**Comment by kfstorm** [comment]
@liuyongvs Sure. Just search "kfstorm".

**Comment by liuyongvs** [comment]
thanks so much . i added you. we are doing flink on ray.

**Comment by chaokunyang** [comment]
@liuyongvs You can try ray==1.1.0

**Comment by chaokunyang** [comment]
It's a bug which got fixed in #9896

**Comment by liuyongvs** [comment]
hi @chaokunyang ,  yeap. it is bug because of ray 1.0.1 linux version lack of the ray-dist jar
