### ISSUE TITLE
Ray dashboard doesn't work with K8s operator

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#13655]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Bhavya6187** [comment]
Looks like even modin is getting wrong resource values. This is what I got when I import modin after initialising ray on the cluster.

![image](https://user-images.githubusercontent.com/723146/106073959-da27e600-60bf-11eb-9777-10951262ca48.png)
