### ISSUE TITLE
what happen when I connect to ray cluster kubernetes on  premise on my use Load Balance show this error redis_context.cc:336: Could not allocate Redis context, will retry in 100 milliseconds.

### ISSUE THREAD

**Issue by siess223** [ray-project/ray#13650]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
Hey, could you provide some context and a reproduction for this? (Ray version, autoscaler config, k8s operatrs/crds, etc)?

**Comment by zjutoe** [comment]
I meet the same error. just the simplest code, "import ray" and "ray.init()":
```

$ /opt/anaconda3/bin/python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
import ray
>>> ray.init(address="192.168.120.36:6379", _redis_password='5241590000000000')
ray.init(address="192.168.120.36:6379", _redis_password='5241590000000000')
2021-02-07 23:34:46,578 INFO worker.py:656 -- Connecting to existing Ray cluster at address: 192.168.120.36:6379
[2021-02-07 23:34:46,584 W 11222 11222] redis_context.cc:336: Could not allocate Redis context, will retry in 100 milliseconds.
[1]    11222 segmentation fault  /opt/anaconda3/bin/python
```

I was trying to connect to the ray head node 192.168.120.36 from 192.168.120.37.

my system configuration

Python: Anaconda3-2020.11-Linux-x86_64
OS：
```
$ uname -a
Linux idc37 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

```
