### ISSUE TITLE
tuple out of range

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1365]
This line causes tuple out of range
https://github.com/ray-project/ray/blob/0ae660ce4e9d96d3fc87eeac753e12c9b414147e/python/ray/services.py#L353

It tries to get `true_version_info[4]`

true_version_info:
('0.3.0', '/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/__init__.py', '3.6.3', '0.5.2')
version_info: ('0.3.0', '/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/__init__.py', '3.6.3', '0.5.2', None)

Ray version:
```pip install https://s3-us-west-2.amazonaws.com/ray-wheels/20d6b74aa6c034fdf35422e6805e2283c672e03f/ray-0.3.0-cp36-cp36m-manylinux1_x86_64.whl```

**Comment by robertnishihara** [comment]
Extremely weird. Related to #1360, but somehow it looks like we have a tuple which contains a `None` value, then we serialize it with `json.dumps`, stick it in Redis, retrieve it from Redis, and deserialize with `json.loads`, and the `None` value disappears or something like that.

**Comment by robertnishihara** [comment]
I think this issue wasn't reproducible. Please reopen if that's not the case.
