### ISSUE TITLE
Be more explicit about how to run scripts with the autoscaler

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1366]
The documentation should walk the user through how exactly to set up a cluster and execute a script, and especially describe what needs to be executed where, i.e. the "ray create_or_update" command is run on a laptop and the script is run on the head node.

This may seem obvious to us, but is not obvious for users and it is really important that the experience of setting up a cluster and running a script is as smooth as possible.

This can either be part of the autoscaling documentation, or be part of a tutorial "setting up a cluster".

**Comment by cathywu** [comment]
This would be really helpful in the autoscaling documentation!

**Comment by pcmoritz** [comment]
fixed by https://github.com/ray-project/ray/pull/1367
