### ISSUE TITLE
[autoscaler][kubernetes] Give a useful error message during rsync when target file or folder not found

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#13662]
Currently spews nonsense.

**Comment by scottsun94** [comment]
@DmitriGekhtman
Sorry about repeating the same question. In consideration of KubeRay, do we still need to do this? Or do we need to fix this for KubeRay?

**Comment by DmitriGekhtman** [comment]
Thanks for following up.
We don't support using rsync with KubeRay.
