### ISSUE TITLE
[rllib] 3 unexpected variables under tensorflow eager mode

### ISSUE THREAD

**Issue by kevin1zc** [ray-project/ray#13660]
### What is the problem?
I tried to set my custom tensorflow model to be executed in eager mode by setting `config["framework"]: "tfe"`. However, under eager mode, there will always be 3 tensorflow variables that are not registered, no matter what the model structure is. These 3 variables should not appear as well since they are not in the model. 
The error message is:
`ValueError: It looks like variables {<tf.Variable 'default_policy/Variable:0' shape=() dtype=int64, numpy=0>, <tf.Variable 'default_policy/Variable:0' shape=() dtype=int64, numpy=0>, <tf.Variable 'default_policy/Variable:0' shape=() dtype=int64, numpy=0>} were created as part of <*confidential* object at 0x7f142959d240> but does not appear in model.variables()`

*Ray version and other system information (Python version, TensorFlow version, OS):
-Ray version: 1.1.0
-Python version: 3.6.9
-TensorFlow version: 2.4.0
-OS: Ubuntu 18.04.5 LTS*

### Reproduction (REQUIRED)
Original model:
```
class LSTMNetwork(TFModelV2):
    """Generic fully connected network implemented in ModelV2 API."""

    def __init__(self, obs_space: gym.spaces.Space,
                 action_space: gym.spaces.Space, num_outputs: int,
                 model_config: ModelConfigDict, name: str):
        super(LSTMNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name)

        activation = get_activation_fn(model_config.get("fcnet_activation"))

        inputs = tf.keras.layers.Input(obs_space.shape, name="observations")

        input_depth = inputs[..., :45000]
        input_sensor = inputs[..., 45000:]

        input_depth = tf.keras.layers.Reshape(target_shape=(50, 30, 30, 1))(input_depth)
        input_sensor = tf.keras.layers.Reshape(target_shape=(50, 36))(input_sensor)

        conv_lstm = tf.keras.layers.ConvLSTM2D(filters=10, kernel_size=(3, 3))(input_depth)
        pool = tf.keras.layers.MaxPool2D()(conv_lstm)
        flat = tf.keras.layers.Flatten()(pool)

        fc1 = tf.keras.layers.Dense(512, activation=activation)(flat)
        fc2 = tf.keras.layers.Dense(128, activation=activation)(fc1)
        conv_out = tf.keras.layers.Dense(16, activation=activation)(fc2)

        sensor_lstm = tf.keras.layers.LSTM(units=64)(input_sensor)

        action_out = tf.keras.layers.Concatenate()([sensor_lstm, conv_out])
        action_out = tf.keras.layers.Dense(128, activation=activation,
                                           kernel_initializer=normc_initializer(1.0))(action_out)
        action_out = tf.keras.layers.Dense(64, activation=activation,
                                           kernel_initializer=normc_initializer(1.0))(action_out)
        final_action_out = tf.keras.layers.Dense(num_outputs,
                                                 activation=activation,
                                                 kernel_initializer=normc_initializer(1.0))(action_out)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.01))(action_out)

        self.base_model = tf.keras.Model(
            inputs, [final_action_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict: Dict[str, TensorType],
                state: List[TensorType],
                seq_lens: TensorType) -> (TensorType, List[TensorType]):
        model_out, self._value_out = self.base_model(input_dict["obs"])
        return model_out, state

    def value_function(self) -> TensorType:
        return tf.reshape(self._value_out, [-1])
```
A simple model for testing:
```
class LSTMNetwork(TFModelV2):
    """Generic fully connected network implemented in ModelV2 API."""

    def __init__(self, obs_space: gym.spaces.Space,
                 action_space: gym.spaces.Space, num_outputs: int,
                 model_config: ModelConfigDict, name: str):
        super(LSTMNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name)

        activation = get_activation_fn(model_config.get("fcnet_activation"))

        inputs = tf.keras.layers.Input(obs_space.shape, name="observations")

        tmp = tf.keras.layers.Dense(100)(inputs)
        final_action_out = tf.keras.layers.Dense(num_outputs,
                                                 activation=activation,
                                                 kernel_initializer=normc_initializer(1.0))(tmp)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.01))(tmp)

        self.base_model = tf.keras.Model(
            inputs, [final_action_out, value_out])
        self.register_variables(self.base_model.variables)
```
Both models have the same error message.

Update: example at [https://github.com/ray-project/ray/blob/master/rllib/examples/eager_execution.py](url) also has the same error.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ColdFrenzy** [comment]
I'm having the same issue. Did you find a solution?

**Comment by kevin1zc** [comment]
@ColdFrenzy No, unfortunately. I'm now turning to PyTorch instead.

**Comment by ColdFrenzy** [comment]
@kevin1zc I've found a workaround. I'm working in a multi-agent environment with a custom model . Following some examples, i've defined my  trainer_config_dict as: 
`config = {
        "env": myenv,
        "multiagent": {
            "policies_to_train": ["p1_policy","p2_policy"],
            "policies": {
                "p1_policy": (PGTFPolicy,obs_space,act_space, {
                    "model" : {
                        "custom_model": "my_custom_model",
                    },

                }),
                "p2_policy": (DQNTFPolicy,obs_space,act_space, {
                    "model":{
                        "custom_model": "my_custom_model",
                    },
                }),
            },
            "policy_mapping_fn": select_policy,
            }
        }`

This gave me the error:
`It looks like variables {<tf.Variable 'p1_policy/Variable:0' shape=() dtype=int64, numpy=0>, <tf.Variable 'p1_policy/Variable:0' shape=() dtype=int64, numpy=0>, <tf.Variable 'p1_policy/Variable:0' shape=() dtype=int64, numpy=0>} were created as part of <*confidential* object at 0x0000024C33D52128> but does not appear in model.variables(). `

Then removing the model key and only using the custom_model key as:  

`config = {
        "env": myenv,
        "multiagent": {
            "policies_to_train": ["p1_policy","p2_policy"],
            "policies": {
                "p1_policy": (PGTFPolicy,obs_space,act_space, {
                    "custom_model": "my_custom_model",

                }),
                "p2_policy": (DQNTFPolicy,obs_space,act_space, {
                    "custom_model": "my_custom_model",
                }),
            },
            "policy_mapping_fn": select_policy,
            }
        }`

Solved the error for me

**Comment by ColdFrenzy** [comment]
If anyone is still having this problem, this should have been addressed with the commit 56878221ede8b7bc3b145eaca7f1f8c609481df8 , you just need to skip the self.register_variable step in your custom model. Anyway, the error is bypassed but not completely solved. 

I just debugged the code a little bit and i noticed that the error is related to tf.keras.Model call inside the custom model.  
In fact when the model is build through the get_model_v2 function in ray/rllib/model/catalog.py , its variables are tracked.
https://github.com/ray-project/ray/blob/1754359281d8b4b9d15f2cb62ca5330d8c6ea84f/rllib/models/catalog.py#L411-L436

Actually Keras.Model should not create any variable to be tracked. I'm not sure where this process happens, but during the keras.Model call inside the custom model, the next_creator function (in the previous linked code) is called 3 times and receive the following as kw arguments :
```
{'initial_value': 0, 'trainable': None, 'validate_shape': True, 'caching_device': None, 
'name': None, 'variable_def': None, 'dtype': 'int64', 'import_scope': None, 'constraint': None,
'synchronization': <VariableSynchronization.AUTO: 0>, 
'aggregation': <VariableAggregationV2.ONLY_FIRST_REPLICA: 3>, 'shape': None}
```

**Comment by sven1977** [comment]
Please provide a complete reproduction script. I get an error (unrelated to this issue) when trying the first of the models above. For the simplified model above, I cannot reproduce this issue (it runs fine), no matter whether I use the deprecated register_variables inside the Model's constructor or not.

```
import gym

import ray
from ray import tune
from ray.rllib.models.catalog import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.models.tf.misc import normc_initializer
from ray.rllib.utils.framework import get_activation_fn, try_import_tf

tf1, tf, tfv = try_import_tf()


class LSTMNetwork(TFModelV2):
    """Generic fully connected network implemented in ModelV2 API."""

    def __init__(self, obs_space: gym.spaces.Space,
                 action_space: gym.spaces.Space, num_outputs: int,
                 model_config, name: str):
        super(LSTMNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name)

        activation = get_activation_fn(model_config.get("fcnet_activation"))

        inputs = tf.keras.layers.Input(obs_space.shape, name="observations")

        tmp = tf.keras.layers.Dense(100)(inputs)
        final_action_out = tf.keras.layers.Dense(num_outputs,
                                                 activation=activation,
                                                 kernel_initializer=normc_initializer(1.0))(tmp)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.01))(tmp)

        self.base_model = tf.keras.Model(
            inputs, [final_action_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict,
                state,
                seq_lens):
        model_out, self._value_out = self.base_model(input_dict["obs"])
        return model_out, state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])


if __name__ == "__main__":
    ray.init(local_mode=True)

    ModelCatalog.register_custom_model("my_model", LSTMNetwork)
    config = {
        "env": "CartPole-v0",
        "model": {
            "custom_model": "my_model",
        }
    }
    stop = {
        "training_iteration": 10,
    }
    tune.run("PPO", config=config, stop=stop, verbose=2)

```

**Comment by ColdFrenzy** [comment]
By adding "framework" : "tf2" inside the config dictionary it gave me the error. Here is the code:
```
import gym

import ray
from ray import tune
from ray.rllib.models.catalog import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.models.tf.misc import normc_initializer
from ray.rllib.utils.framework import get_activation_fn, try_import_tf

tf1, tf, tfv = try_import_tf()


class LSTMNetwork(TFModelV2):
    """Generic fully connected network implemented in ModelV2 API."""

    def __init__(self, obs_space: gym.spaces.Space,
                 action_space: gym.spaces.Space, num_outputs: int,
                 model_config, name: str):
        super(LSTMNetwork, self).__init__(
            obs_space, action_space, num_outputs, model_config, name)

        activation = get_activation_fn(model_config.get("fcnet_activation"))

        inputs = tf.keras.layers.Input(obs_space.shape, name="observations")

        tmp = tf.keras.layers.Dense(100)(inputs)
        final_action_out = tf.keras.layers.Dense(num_outputs,
                                                 activation=activation,
                                                 kernel_initializer=normc_initializer(1.0))(tmp)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.01))(tmp)

        self.base_model = tf.keras.Model(
            inputs, [final_action_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict,
                state,
                seq_lens):
        model_out, self._value_out = self.base_model(input_dict["obs"])
        return model_out, state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])


if __name__ == "__main__":
    ray.init(local_mode=True)

    ModelCatalog.register_custom_model("my_model", LSTMNetwork)
    config = {
        "env": "CartPole-v0",
        "model": {
            "custom_model": "my_model",
        },
        "framework" : "tf2"
    }
    stop = {
        "training_iteration": 10,
    }
    tune.run("PPO", config=config, stop=stop, verbose=2)
```

**Comment by kevin1zc** [comment]
@ColdFrenzy Thank you for your feedback and suggestion. I'll try that with the master branch later.

@sven1977 This error is associated with the eager execution. In graph mode the code works fine, but if you set `"framework": "tf2"` or `"tfe"` in `config,` the error will occur.

**Comment by kevin1zc** [comment]
It seems that Ray 1.2.0 solves the problem. However, in my case, tfe or tf2 is twice slower than tf.

**Comment by kevin1zc** [comment]
Problem already fixed in newer versions
