### ISSUE TITLE
[autoscaler][kubernetes][operator] Add rolling upgrade functionality to K8s operator

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#13675]
The K8s operator should include rolling update logic, similar to the functionality of the K8s Deployment controller. (See https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/.)

**Comment by smartkiwi** [comment]
Could you please provide update for when (approximately)rolling update support could be possible coming ?

Here is the use case when it could be handy: in my company there is requirements for release artifacts deployed on production to be approved (and tested) before deployment . As of now we run gunicron based k8s services - and we use Docker images as an artifacts to be approved and deployed.

So I envision if we move our service to Ray Serve - new version deployment would involve updating Ray k8s cluster to a newer version of docker for image using rolling update, and running Ray deploy for a new app on a client.

Alternative release process could be done by packaging app as python wheels - but with ML app there are big chance that a new version of some library would need to be deployed along with new version of an app, and packaging both app and dependencies into a docker image during CI build allows catch various problems and running functional and integration tests for a docker image before doing deploy.

**Comment by AmeerHajAli** [comment]
@simon-mo , perhaps you know the answer to the question above?

**Comment by DmitriGekhtman** [comment]
This does seem like it should be thought of in the multi-Ray-cluster setting ("Jobs and Services" in the language of the Ray maintainers).

The idea would be to bring up a new Ray cluster for the new version and start redirecting traffic from the old one to the new one.

A more complex single-cluster application-level alternative would be to do a rolling upgrade of Ray Runtime Environments rather than docker images.

**Comment by simon-mo** [comment]
We recommend new cluster for "clean slate" abstraction. In the "pet vs cattle" terminology, we recommend treating ray clusters as ephemeral and interchangeable "cattles".

**Comment by DmitriGekhtman** [comment]
To implement a rolling update oneself, one could use two [KubeRay](https://github.com/ray-project/kuberay)-managed Ray clusters.
Gradually scale down worker replicas on the old cluster and gradually scale up worker replicas on the new one.

**Comment by DmitriGekhtman** [comment]
> We recommend new cluster for "clean slate" abstraction. In the "pet vs cattle" terminology, we recommend treating ray clusters as ephemeral and interchangeable "cattles".

Ironically, the reason for this is that each Ray cluster is itself very stateful -- individual Ray nodes are, in general, "pets" from a Ray-cluster-internal perspective.
Managing that state during an upgrade is an unsolved problem. Starting a new cluster and eventually tossing out the old works just fine.

**Comment by DmitriGekhtman** [comment]
Discussion of upgrades has moved to the KubeRay repo.
https://github.com/ray-project/kuberay/issues/527
