### ISSUE TITLE
[tune] ValueError: The returned checkpoint path must be within the given checkpoint dir

### ISSUE THREAD

**Issue by djollet** [ray-project/ray#13678]
### What is the problem?

When running a population based training (PBT) with ray tune, i get the following error massage:

```python
ERROR trial_runner.py:856 -- Trial train_model_46427_00002: Error processing result.
Traceback (most recent call last):
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\tune\trial_runner.py", line 854, in _process_trial_save
    checkpoint_value = self.trial_executor.fetch_result(trial)
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::ImplicitFunc.save() (pid=6664, ip=192.168.178.20)
  File "python\ray\_raylet.pyx", line 482, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 436, in ray._raylet.execute_task.function_executor
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\function_manager.py", line 553, in actor_method_executor
    return method(actor, *args, **kwargs)
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\tune\function_runner.py", line 434, in save
    checkpoint_path = TrainableUtil.process_checkpoint(
  File "C:\Users\Dirk\anaconda3\lib\site-packages\ray\tune\trainable.py", line 41, in process_checkpoint
    raise ValueError(
ValueError: The returned checkpoint path must be within the given checkpoint dir C:\Users\Dirk/ray_results\2021-01-05_11-24-15iiap2bxm\checkpoint_4: C:\Users\Dirk\ray_results\2021-01-05_11-24-15iiap2bxm\checkpoint_4
```

I think it has something to do with the pertubation and checkpointing, but I can’t find anything about it.

### Information about my setup:
Windows 10
pycharm 2020.3
python 3.8
ray 1.0.1.post1
pytorch 1.7

### Reproduction (REQUIRED)
https://gist.github.com/djollet/8a73ba0157feb9f1a303833763cd0e43
Paths to images need to be adapted. Folder structure:
-MainFolder
--RayTune.py (Scipt in gist)
--Train
-------Class1
----------img1_1
----------img2_1
----------...
-------Class2
----------img1_2
----------img2_2
----------...
-------Class3 
----------img1_3
----------img2_3
----------...
-------Class4
----------img1_4
----------img2_4
----------...
-------Class5
----------img1_5
----------img2_5
----------...
-------Class6
----------img1_6
----------img2_6
----------...
-------Class7
----------img1_7
----------img2_7
----------...
-------Class8
----------img1_8
----------img2_8
----------...
-------Class9
----------img1_9
----------img2_9
----------...
--Test(same structure as Train folder)

**Comment by krfricke** [comment]
cc @amogkam

**Comment by amogkam** [comment]
Thanks for posting this issue. It looks like a problem with how paths are stored specifically with Windows. The `parent_dir` has a backslash right before `ray_results`, but the checkpoint path has a forward slash. Internally, we check to make sure whether the checkpoint path string starts with `parent_dir`, but because the slashes are different, this is raising an error.

cc @richardliaw I think you wrote a lot of the function checkpointing code. Do you perhaps know where we could've seen this discrepancy in slashes? I looked through and it doesn't look like we are hardcoding a forward slash anywhere, so I believe the `os` library should automatically take care of this.

Alternatively, we could just use `os` methods to check for parent directory rather than string matching.

**Comment by richardliaw** [comment]
ah @amogkam it's actually everywhere we hardcode `~/ray_results`. On windows, this automatically keeps the forward slash -- instead we probably want to do something like: https://stackoverflow.com/a/4028943/14961124

**Comment by richardliaw** [comment]
@djollet one workaround for now is to hardcode `tune.run(local_dir="~\ray_results")` for your windows machine
