### ISSUE TITLE
[core] Error on ray.init()

### ISSUE THREAD

**Issue by BladeofDarken** [ray-project/ray#13670]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro v 18363
Ray installed from (source or binary):Latest wheel
Ray version:1.1.0
Python version: 3.8
Describe the problem
When I run ray.init(), will report an error.

"2021-01-24 13:30:32,206	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265"

Simple Program will not run because of this error. Using @ray.remote and .get for invoking

**Comment by krfricke** [comment]
Hi @BladeofDarken, as the log message suggests, this is not an error but an information log. It outputs a link to the Ray dashboard.

If there's another error or something does not work, please give us access to your code and the full output you get.

**Comment by kuangsangudu** [comment]
[win error]Hello,  I run the code `ray.init()`, it will report an error.

Here is the error.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\conda\lib\site-packages\ray\worker.py", line 722, in init
    ray_params=ray_params)
  File "D:\conda\lib\site-packages\ray\node.py", line 216, in __init__
    self.start_head_processes()
  File "D:\conda\lib\site-packages\ray\node.py", line 767, in start_head_processes
    self.start_redis()
  File "D:\conda\lib\site-packages\ray\node.py", line 590, in start_redis
    self.get_resource_spec(),
  File "D:\conda\lib\site-packages\ray\node.py", line 314, in get_resource_spec
    is_head=self.head, node_ip_address=self.node_ip_address)
  File "D:\conda\lib\site-packages\ray\resource_spec.py", line 165, in resolve
    num_gpus = _autodetect_num_gpus()
  File "D:\conda\lib\site-packages\ray\resource_spec.py", line 252, in _autodetect_num_gpus
    lines = subprocess.check_output(cmdargs).splitlines()[1:]
  File "D:\conda\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "D:\conda\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\conda\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\conda\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
**FileNotFoundError: [WinError 2] The system can not find the file specified。**

**Comment by WilbertYuan** [comment]
> [win error]Hello, I run the code , it will report an error.`ray.init()`
> 
> Here is the error. Traceback (most recent call last): File "", line 1, in File "D:\conda\lib\site-packages\ray\worker.py", line 722, in init ray_params=ray_params) File "D:\conda\lib\site-packages\ray\node.py", line 216, in **init** self.start_head_processes() File "D:\conda\lib\site-packages\ray\node.py", line 767, in start_head_processes self.start_redis() File "D:\conda\lib\site-packages\ray\node.py", line 590, in start_redis self.get_resource_spec(), File "D:\conda\lib\site-packages\ray\node.py", line 314, in get_resource_spec is_head=self.head, node_ip_address=self.node_ip_address) File "D:\conda\lib\site-packages\ray\resource_spec.py", line 165, in resolve num_gpus = _autodetect_num_gpus() File "D:\conda\lib\site-packages\ray\resource_spec.py", line 252, in _autodetect_num_gpus lines = subprocess.check_output(cmdargs).splitlines()[1:] File "D:\conda\lib\subprocess.py", line 411, in check_output **kwargs).stdout File "D:\conda\lib\subprocess.py", line 488, in run with Popen(*popenargs, **kwargs) as process: File "D:\conda\lib\subprocess.py", line 800, in **init** restore_signals, start_new_session) File "D:\conda\lib\subprocess.py", line 1207, in _execute_child startupinfo) **FileNotFoundError: [WinError 2] The system can not find the file specified。**

I got the same problem

**Comment by WilbertYuan** [comment]
how to solve it?
