### ISSUE TITLE
Train an MNIST classifier with Torch and Ray SGD failed.

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#13682]
I followed the MNIST Tutorial to train an MNIST classifier with Pytorch Lightning's LightningModule and Ray SGD (https://docs.ray.io/en/master/raysgd/raysgd_ptl.html, we made a few changes to the model). No errors were reported . But currently we still mainly use Torch, so we want to Train an MNIST classifier with Pytorch(not pytorch_lightning) and Ray SGD, but the error keeps happening:too many vlaues to unpack(excepted 2).
For the MNIST classifier with Torch and RaySGD case, I customized a custom TrainingOperator that provides a train_epoch implementation according to the official API（https://docs.ray.io/en/latest/raysgd/raysgd_pytorch.html#raysgd-custom-training.

Below is my submission script in test1.txt (you can run it directly after successfully installing ray[all]==1.1.0).
[test1.txt](https://github.com/ray-project/ray/files/5866759/test1.txt
------------------------edite line---------------------------------
Then the following error will be reported:

File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 112, in train_epoch
    num_steps=num_steps, profile=profile, info=info, iterator=iterator)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_runner.py", line 140, in train_epoch
    train_stats = self.training_operator.train_epoch(iterator, info)
  File "/home/yexin/workSpace/PyCharmProjects/HikVision/org/bigAI/ray/RaySGDMNISITvsHorvord_B.py", line 93, in train_epoch
    x, y = batch
ValueError: too many values to unpack (expected 2)
----------edite line--------------------------
The script of train an MNIST classifier with Pytorch Lightning's LightningModule and Ray SGD is as follows in test2.txt(without any error, it can run successfully):
[test2.txt](https://github.com/ray-project/ray/files/5866783/test2.txt)

This error makes me very confused. The data sets, models, training and validation in the two cases are exactly the same. Just converting LightningModule to nn.Module, train_epoch method always prompts: too many values to unpack(x,y= batch), if I implement train by myself, how should I modify it?
Especially looking forward to your reply.

**Comment by amogkam** [comment]
Hi @Matrix-World, the method signature you have for `train_epoch` is incorrect. It should be `def train_epoch(self, iterator, info)`, and you would have to iterate through the `iterator`: `for batch_idx, batch in enumerate(iterator)`, and then call `train_batch` in this for loop. 

Also just an FYI, if you want the same exact behavior with the `LightningOperator` and you own `CustomOperator`, the training functions are not the exact same as what's specified in the `training_step` in the `LightningModule`. Internally, the `LightningOperator` does more: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/lightning_operator.py#L194

**Comment by Matrix-World** [comment]
> 
> 
> Hi @Matrix-World, the method signature you have for `train_epoch` is incorrect. It should be `def train_epoch(self, iterator, info)`, and you would have to iterate through the `iterator`: `for batch_idx, batch in enumerate(iterator)`, and then call `train_batch` in this for loop.
> 
> Also just an FYI, if you want the same exact behavior with the `LightningOperator` and you own `CustomOperator`, the training functions are not the exact same as what's specified in the `training_step` in the `LightningModule`. Internally, the `LightningOperator` does more: https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/lightning_operator.py#L194

Thank you for your reply. I have solved this problem by rewriting the trian_epoc and validate methods.
