### ISSUE TITLE
Ray doesnt assign plasma to one node and one of the worker is dead on another node

### ISSUE THREAD

**Issue by srikanthgadadasu** [ray-project/ray#13690]
<img width="1259" alt="Screen Shot 2021-01-22 at 3 33 43 PM" src="https://user-images.githubusercontent.com/66190462/105756478-ad869980-5f1a-11eb-9b3c-cd16f56323f5.png">

### What is the problem?

I started Ray on 3 nodes and observed below issues
1:  It doesnt assign plasma storage space to one of the node
2:  One of the worker is in IDLE state and the work assigned for that worker didnt return and program was waiting for it infinitely

Used below commands for starting ray

`ray start --head --num-cpus=4

ray start --address='host address' --redis-password='5241590000000000'`

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray version 1.2.0 dev
Python 3.8.6

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [Y ] I have verified my script runs in a clean environment and reproduces the issue.
- [ Y] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Could you provide us a reproduction script? Also @wuisawesome This might be a scheduling regression.

**Comment by srikanthgadadasu** [comment]
its the same script i provided for other issue #13443

**Comment by rkooo567** [comment]
Do you mind trying the 2.0.0dev0 instead?

**Comment by rkooo567** [comment]
Also, are you in the public Ray slack channel? I can follow up there for this issue.

**Comment by srikanthgadadasu** [comment]
I tried 2.0.0 dev version and its actually very unstable in terms of keeping multiple nodes.  I ran the same program on same 3 nodes using 2.0 version and after sometime the slave nodes are appearing offline, thats the reason i switched back to 1.2

**Comment by srikanthgadadasu** [comment]
> Also, are you in the public Ray slack channel? I can follow up there for this issue.

yes i am

**Comment by rkooo567** [comment]
What's your handle there?

**Comment by srikanthgadadasu** [comment]
Srikanth Gadadasu

**Comment by rkooo567** [comment]
@srikanthgadadasu and I met in person and figured out the issue.
