### ISSUE TITLE
raylet has info but no nodes have the necessary resources, but my node has enough resources

### ISSUE THREAD

**Issue by liuyongvs** [ray-project/ray#13709]
### What is the problem?
when i develop flink on ray session mode, i found ray can not make TaskManager run, but the resource is enough(2647 * 5m)

/mnt/disk1/ly/ray/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/raylet.1 --store_socket_name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/plasma_store.1 --object_manager_port=0 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=55666 --node_ip_address=10.192.78.61 --redis_address=10.192.78.61 --redis_port=6379 --num_initial_workers=64 --maximum_startup_concurrency=64 --static_resource_list=node:10.192.78.61,1.0,CPU,64,memory,2647,object_store_memory,782 --config_list=plasma_store_as_thread,True --python_worker_command=/mnt/disk1/ly/ray/bin/python /mnt/disk1/ly/ray/lib/python3.7/site-packages/ray/workers/default_worker.py --node-ip-address=10.192.78.61 --node-manager-port=55666 --object-store-name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/plasma_store.1 --raylet-name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/raylet.1 --redis-address=10.192.78.61:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=45612 --redis-password=5241590000000000 --java_worker_command=java -Dray.address=10.192.78.61:6379 -Dray.raylet.node-manager-port=55666 -Dray.object-store.socket-name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/plasma_store.1 -Dray.raylet.socket-name=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/sockets/raylet.1 -Dray.redis.password=5241590000000000 -Dray.home=/mnt/disk1/ly/ray/lib/python3.7/site-packages/ray/../.. -Dray.logging.dir=/tmp/ray/session_2021-01-26_14-45-33_035895_17964/logs -Dray.session-dir=/tmp/ray/session_2021-01-26_14-45-33_035895_17964 -Dray.job.code-search-path=[] RAY_WORKER_RAYLET_CONFIG_PLACEHOLDER -cp /mnt/disk1/ly/ray/lib/python3.7/site-packages/ray/jars/* RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER io.ray.runtime.runner.worker.DefaultWorker --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2021-01-26_14-45-33_035895_17964 --metrics-agent-port=45612 --metrics_export_port=62382 --object_store_memory=59476926873 --plasma_directory=/dev/shm

raylet log
I0126 14:46:57.000681 18098 18098 worker.cc:123] Assigned worker 01000000ffffffffffffffffffffffffffffffff to job 01000000
I0126 14:47:26.193353 18098 18098 scheduling_policy.cc:142] The task with ID ffffffffffffffffafd7fa8201000000 requires {CPU: 4.000000}, {MEM: 1392508928.000000} for execution and {CPU: 4.000000}, {MEM: 1392508928.000000} for placement, but no nodes have the necessary resources. Check the client table to view node resources.

**Comment by rkooo567** [comment]
Cc @ffbin do you know the api to see available resources?

**Comment by liuyongvs** [comment]
@rkooo567 is it also a bug at ray java resource api . 
it is ok when it is  changed to this(disable the resources)

            Configuration flinkConfigForTaskManager = setTaskManagerParams(flinkConfig, taskExecutorProcessSpec);
            ActorHandle<CustomTaskManagerRunner> actorWorker = Ray.actor(CustomTaskManagerRunner::new, flinkConfigForTaskManager)
//                .setJvmOptions(opts)
//                .setResources(resources)
//                .setMaxRestarts(-1)
                .remote();
            actorWorker.task(CustomTaskManagerRunner::start)
                .remote();

**Comment by rkooo567** [comment]
Hmm it is odd. Unfortunately, I am not that famliar with Java APIs, but @kfstorm and @ffbin can help!

**Comment by kfstorm** [comment]
@liuyongvs Please use "memory" rather than "MEM" to specify memory resource.

**Comment by liuyongvs** [comment]
@kfstorm @rkooo567 , kfstorm is right, the resources like CPU, memory is strict match.(it is  **case sensitve**)

**Comment by rkooo567** [comment]
I think we can close the issue? Feel free to reopen if the issue wasn't resolved!
