### ISSUE TITLE
Adding / removing actors from actor pool

### ISSUE THREAD

**Issue by srikanthgadadasu** [ray-project/ray#13704]
### Describe your feature request

It would be great if we can able to add/remove actors from actor pool dynamically in middle of the program.  Can you add transferring idle actors from one pool to another pool dynamically inside the program 

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
Can you also specify the use case?

**Comment by srikanthgadadasu** [comment]
Use Case:   Consider there are N stages in a program and N actor pools defined with n, ..... 3,2,1, 0 actors assigned for each, as soon as any of the actor is free from pool(it doesnt have any work to do), then it should be removed from that pool and get assigned to next pool(or whichever pool needed them) and so on. And there should not be any idle actors in the program (if any actor is not needed in any pool, then it should be deleted)

**Comment by rkooo567** [comment]
cc @micahtyong Are you interested in taking a look at this? This will be a pretty fun task

**Comment by micahtyong** [comment]
Sure, I can take a look

**Comment by micahtyong** [comment]
Hi @srikanthgadadasu, we're thinking of exposing three new functions from the `ActorPool` class that can satisfy your use case: 
- `pop()`: removes the first idle actor from a pool
- `append()`: adds an actor to a pool 
- `has_free()`: returns whether or not an idle actor exists in a pool 

To use this API, you could do something like the following: 
```
pool = ActorPool([a1, a2])
pool2 = ActorPool([b1])
...
while pool.has_free(): 
    pool2.append(pool1.pop())
```
Let us know if you have thoughts or concerns regarding this approach. cc: @rkooo567

**Comment by srikanthgadadasu** [comment]
That would be great
