### ISSUE TITLE
OSError: Apache/mod_wsgi log object is not associated with a file descriptor.

### ISSUE THREAD

**Issue by ansarisam** [ray-project/ray#13716]
Ray and Ray Serve

### What is the problem?
I have a simple Ray program that connects with Ray cluster running Ray Serve and executes a remote function.
When I run this program from the command line, it works like a charm. However, when this remote function is called from a Django based web app hosted on Apache2 server using mod_wsgi, I get the following error:

“OSError: Apache/mod_wsgi log object is not associated with a file descriptor.”

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python: 3.8
OS: Ubuntu 20.4
Ray:  1.1.0
Tensorflow: 2.3.0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

`class Parallel():
	def init(self):
		ray.init(address="auto")
	@ray.remote
	def getCellContent(self, row):
		return "x"

parallel = Parallel()
future_rows = [parallel.getCellContent.remote(i) for i in range(4)]
print(ray.get(future_rows))`

https://gist.github.com/ansarisam/88290df4a4aeed7ab049e9f8e7c8c1da

Stacktrace:
`“OSError: Apache/mod_wsgi log object is not associated with a file descriptor.”
Here is the stack trace:

[Tue Jan 26 03:59:02.706384 2021] [wsgi:error] [pid 335920:tid 140665254037248] File “/home/venv/table_creator.py”, line 23, in init
[Tue Jan 26 03:59:02.706396 2021] [wsgi:error] [pid 335920:tid 140665254037248] ray.init(address=‘auto’)
[Tue Jan 26 03:59:02.706422 2021] [wsgi:error] [pid 335920:tid 140665254037248] File “/home/venv/lib/python3.8/site-packages/ray/worker.py”, line 766, in init
[Tue Jan 26 03:59:02.706435 2021] [wsgi:error] [pid 335920:tid 140665254037248] connect(
[Tue Jan 26 03:59:02.706461 2021] [wsgi:error] [pid 335920:tid 140665254037248] File “/home/venv/lib/python3.8/site-packages/ray/worker.py”, line 1080, in connect
[Tue Jan 26 03:59:02.706472 2021] [wsgi:error] [pid 335920:tid 140665254037248] faulthandler.enable(all_threads=False)
[Tue Jan 26 03:59:02.706526 2021] [wsgi:error] [pid 335920:tid 140665254037248] OSError: Apache/mod_wsgi log object is not associated with a file descriptor.`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
hey @ansarisam do you mind fixing up the whitespacing in your reproduction? I think the issue here is that the `ray.remote` annotation should only be used on functions and classes (but not bound methods within a class).

**Comment by ansarisam** [comment]
> hey @ansarisam do you mind fixing up the whitespacing in your reproduction? I think the issue here is that the `ray.remote` annotation should only be used on functions and classes (but not bound methods within a class).

I tried to insert code but for some reason, it is not preserving the formatting. Here is the gist code link to show the formatting.
https://gist.github.com/ansarisam/88290df4a4aeed7ab049e9f8e7c8c1da 

I do have @remote annotation with a function of a class. And if that is the reason, it is not working, I will try the remote function without any class. Thanks for this pointer.

**Comment by ansarisam** [comment]
> > hey @ansarisam do you mind fixing up the whitespacing in your reproduction? I think the issue here is that the `ray.remote` annotation should only be used on functions and classes (but not bound methods within a class).
> 
> I tried to insert code but for some reason, it is not preserving the formatting. Here is the gist code link to show the formatting.
> https://gist.github.com/ansarisam/88290df4a4aeed7ab049e9f8e7c8c1da
> 
> I do have @Remote annotation with a function of a class. And if that is the reason, it is not working, I will try the remote function without any class. Thanks for this pointer.

Hi @wuisawesome,
I modified my code to keep the @ray.remote function outside any class and experienced the same error. 
Thank you.

**Comment by ansarisam** [comment]
Hi Guys,
Does anyone have any idea how to fix this problem? Thank you.
