### ISSUE TITLE
[Object Spilling] Causes weird issues when number of IO workers are >= 2.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13728]
### What is the problem?

Works well when there's only one IO worker. We probably don't clean up metadata properly. 

Until we fix this, we can only use 1 IO worker.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
This duplicates https://github.com/ray-project/ray/issues/13725 right?

**Comment by rkooo567** [comment]
I am not 100% sure, but there's a possibility. What about I just close it for now and reopen if you that issue doesn't fix it?
