### ISSUE TITLE
[Object Spilling] smart_open seems to require us to pre-create a boto3 session and share through transport param

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13757]
### What is the problem?

I've seen the Restore worker has too high cpu usage (100%), so  I did some profiling. It seems like we need to create a S3 session and pass it to the transport_param every time (it seems like smart open doesn't automatically handle this). You can see 50% of time is spent creating a new session. This could be probably why S3 spilling was slow so far.

<img width="791" alt="Screen Shot 2021-01-27 at 10 47 52 PM" src="https://user-images.githubusercontent.com/18510752/106100806-c5644600-60f1-11eb-8092-f43696b0f626.png">

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @ericl

**Comment by rkooo567** [comment]
https://github.com/RaRe-Technologies/smart_open/blob/9fe29621ae2434f6d1fbce2d06564d6f65a5a551/smart_open/s3.py#L477

**Comment by ericl** [comment]
Good find. Also, please remember to add bugs to core bugs!
