### ISSUE TITLE
20k small task problem, kernel crashes [tune]

### ISSUE THREAD

**Issue by mike576** [ray-project/ray#13759]
Hi everyone,

 I am new to ray and tune, but at first sight, it looks super cool. I’d like to ask a question and maybe also find out what's wrong with my concept?

using ray: version 1.1.0
os: linux ubuntu 18.

So in our project, we build a lot of models 20k-100k, sometimes only 1k with grid search, so we have 20k-100k trials too. We don't want to find the best model, we‘d like to look at the distribution of the ML models and their performance (eg. distribution or r2 ). To train a model, it takes only about 1 sec, so you can consider it as a small task but not as a tiny task. So a week ago we started to use Tune and Ray with Jupyter notebook, on a bigger linux machine on aws with 96 CPUs, no other nodes, and almost every run the kernel crashes. I cannot find any log which would describe the cause of the crash.
I do understand that there is some overhead with starting trials and also copy the objects to the object store etc. I have read in another thread the tiny task problem too.

As I have found out the 1000 trials run perfectly, so there's must be something wrong with 20k-100k. In the logs I have found also a performance bottleneck: “Consider increasing your period of result reporting to improve performance”. We use yield at the and of every trial,  so every second there's a result reporting. and also I get warnings like: "The `start_trial` operation took 0.754 s, which may be a performance bottleneck."

In the memory of the ray dashboard, I can see 100-200 objects only. In htop, I can see a lot of IDLE ray processes (Maybe waiting for getting an object or task), the machine is utilized about 30% - 40% only. By contrast the same tasks with Parallels using 100% of the 96 CPUs. So there's must be something wrong with my concept or with my settings. Note we set checkpoint_freq=500 (avoiding saving checkpoints every 10th trial.)

Questions:

- how could I find out what crashes the kernel?
- How could I find out what the tasks are waiting for?
- Would you consider to change the architecture and do some inner trial grid search? e.g. if 1 trial does 100  different grid searches,  then I can reduce the 20k trials to 200. Is this a good workaround?
- What else can I try? 

Thanks,
Miklos

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by mike576** [comment]
In the mean time I got through the utilization problem by ray.put() and get(obj_ref) which is much more preformat. However kernel dies also. Sometimes it hangs at the very last step.

**Comment by mike576** [comment]
I have created a bug about this issue so the follow-up is there: #13881 
So, I close this issue now.
