### ISSUE TITLE
List of workers is empty

### ISSUE THREAD

**Issue by YarShev** [ray-project/ray#13758]
### What is the problem?

List of workers is empty.

```bash
pip list | grep ray
ray                           1.0.1.post1
```

### Reproduction (REQUIRED)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

```python
import ray
ray.init()

from ray.state import state

state.workers()
{}

oid1 = ray.put(1)
state.workers()
{}

@ray.remote
def foo():
    return 1

oid2 = foo.remote()
state.workers()
{}
```

**Comment by rkooo567** [comment]
Can you try the latest master and see the issue still happens? I remember we fixed this at one point and don't remember if it was before or after 1.0.1

**Comment by YarShev** [comment]
I have tried the latest master. Both `ray.state.state.workers()` and `ray.state.workers()` works good. So, will be waiting for the release.

**Comment by YarShev** [comment]
By the way, is there a way to get a list of local `ObjectRef` references for a worker?

**Comment by YarShev** [comment]
A stub just to remove stale tag.

**Comment by rkooo567** [comment]
I think ray.state.workers() will probably deprecated. Can you specify your use case including this question? `By the way, is there a way to get a list of local ObjectRef references for a worker?`

**Comment by YarShev** [comment]
This question has partly been resolved on discuss.ray.io ([link](https://discuss.ray.io/t/get-actor-handle-by-objectref/601)). However, I would like to have an ability to run a remote function as closer to data as possible, as well as a user has some flexibility to send a remote call to the concrete worker (as it is done in Dask, for example, `client.submit(lambda: 1, workers='tcp://1.1.1.1:11111')`. As far as I know, Ray provides similar opportunity using placement groups and custom resources to run a function on the concrete node. But is there some stuff to run a function on the concrete worker?

**Comment by rkooo567** [comment]
No. Ray doesn't cache objects to process (but it uses the distributed object store in shared memory), so there's no need to schedule tasks directly to workers for locality. Using the same node should guarantee enough locality for Ray.

**Comment by YarShev** [comment]
Okay, that makes sense to me. Closing the issue.
