### ISSUE TITLE
[Object Spilling] IO worker seems to hold shared memory.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13768]
### What is the problem?

After the job that uses object spilling, io workers are usually not killed (unlike worker processes). I found out all the objects that are spilled / restored from them are not freed from shared memory. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run a heavy workload that uses object spilling.
Job done. 
df -a /dev/shm -h => This should show that shared memory is still used.
kill IO workers.
df -a /dev/shm => You can see memory usage became 0%

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
This is expected. Shared memory is never freed once allocated.

**Comment by rkooo567** [comment]
But it is freed when the io worker is killed? Doesn’t this mean if we have a long running work, we will use up all the shared memory?

**Comment by ericl** [comment]
The object store will use up to the max shared memory. This is never
released to the OS until ray exits by design.

**Comment by rkooo567** [comment]
So I have a question in this case. (I just want to make sure if I
understand it correctly)

Let’s say we run the same jobs 5 times in a row, each of which uses 10%
shared memory. In this case, after the 4th run, we will use 40% (and let’s
say that’s the max object store memory). The objects should’ve been all
evicted at this moment. In this case, if we run the 5th job, does it still
work? (Is it reusing the unfreed memory or something)?

**Comment by ericl** [comment]
Yes, the memory is allocated from the OS permanently but can be reused
internally by Ray for multiple objects. You can try it out yourself, there
is no issue here.

**Comment by rkooo567** [comment]
Sounds good. Thanks for the explanation (will also try out)!
