### ISSUE TITLE
Autoscaler should allow configuration of disk space and should use a larger default.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1376]
While using the autoscaler, I ran out of disk space very quickly. I was using it for development and Anaconda + Ray took most of the disk space. This should be configurable through the yaml file and should come with a larger value.

**Comment by robertnishihara** [comment]
@pschafhalter this issue can be closed, right?

**Comment by pschafhalter** [comment]
Yes, it was fixed in #1401

**Comment by robertnishihara** [comment]
@pschafhalter I don't think this works as intended (or I'm using it incorrectly). I just tried using the `example.yaml` and uncommenting the block

```
    # BlockDeviceMappings:
    #     - DeviceName: /dev/sda1
    #       Ebs:
    #           VolumeSize: 100
```

I used 200 instead of 100, but when I ssh'ed to the head node, the 200GB were no where to be found (same with the worker nodes). Any ideas?

**Comment by robertnishihara** [comment]
Reopening because it doesn't work in the examples provided.

**Comment by pschafhalter** [comment]
I'll take a look and see what's going on.

**Comment by pschafhalter** [comment]
@robertnishihara strange, it seems to work fine for me. I uncommented the block in `example.yaml` and launched clusters with 100GB  and 200GB of storage in the head node. I'm running the most recent version of ray in a virtual environment installed from source.

For 100GB:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           769M  8.7M  761M   2% /run
/dev/nvme0n1p1   97G   38G   60G  39% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
tmpfs           769M  8.0K  769M   1% /run/user/1000
```

For 200GB:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           769M  8.7M  761M   2% /run
/dev/nvme0n1p1  194G   38G  157G  20% /
tmpfs           3.8G     0  3.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.8G     0  3.8G   0% /sys/fs/cgroup
tmpfs           769M  8.0K  769M   1% /run/user/1000
```
