### ISSUE TITLE
[rllib] Indesirable sorting of observation keys by `DictFlatteningPreprocessor`.

### ISSUE THREAD

**Issue by duburcqa** [ray-project/ray#13760]
### What is the problem?

I don't see any reason why someone would want the keys of an observation dict to be sorted alphabetically if stored using a "normal" `dict` instead of an actual `OrderedDict`. Both an equivalent in practice since Python3.6, and required by Python specifications since 3.7. I'm referring to [line 266](https://github.com/ray-project/ray/blob/d11e62f9e61a2eb2c5ce9c8d437b3d0d9cae6511/rllib/models/preprocessors.py#L266) in preprocessors module.

*Ray version and other system information (Python version, TensorFlow version, OS): * Python3.6, Ubuntu18.04, Tensorflow 2.2, Ray 1.2.0 nighly

- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stanislav-chekmenev** [comment]
I agree with you, @duburcqa. It makes my life harder when working with `Dict()` gym spaces.

**Comment by sven1977** [comment]
Thanks for posting this @duburcqa !
Yeah, this makes sense. We should leave the order in the dict coming from the env as-is and not re-sort it (silently!) as this may cause surprises later inside the model/policy.
I'll create a PR. If all tests pass w/o this sorting, we'll merge.

**Comment by sven1977** [comment]
On a separate note: We are thinking of completely getting rid of Preprocessors. The only reason why we still have the default ones (custom ones are no longer supported) is to flatten complex observation spaces, but our SampleCollectors/Models should be able to handle this automatically. However, this is WIP.

**Comment by sven1977** [comment]
PR is out (see above). Waiting for all tests to pass. ...

**Comment by ThomasLecat** [comment]
I see the MR isn't merged yet. Don't you think that not sorting will do more harm than sorting? The Gym Dict space sorts the key in the [constructor](https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/spaces/dict.py#L38-L39), any environment using a Gym Dict space will fail unless the keys in the observation are sorted

**Comment by duburcqa** [comment]
It does not always sort them, only if it is not `OrderedDict`. And, why would someone care about the order if someone is not using `OrderedDict` for constructing the the `gym.Dict` space in the first place ? The good solution for me is not to sort, so that people willing to do it can to it on there own, instead of doing it systematically.
