### ISSUE TITLE
[autoscaler] Better validation for min_workers and max_workers

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13775]
### What is the problem?

User can specify max_workers globally that's less than min_workers for node types, causing nodes to repeatedly get started and killed. We should better validate the YAML.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
Reopening due to #13807

**Comment by AmeerHajAli** [comment]
I fixed herE:
https://github.com/ray-project/ray/pull/13811
