### ISSUE TITLE
[rllib] Incorrect count_steps_by metrics

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#13802]
Problem: #12372 introduced the option to measure training progress by agent steps rather than env steps. However, it appears the trainer logs do not reflect this change. When I train on a many-agent env for 1 epoch with the following batch size params:

ROLLOUT_FRAGMENT_LENGTH = 100
TRAIN_BATCH_SIZE                      = 800
TRAIN_HORIZON                           = 200
EVALUATION_HORIZON                = 50
NUM_WORKERS                            = 4

RLlib's Trainer.train() 'info' logs return 'num_steps_sampled': 400, 'num_steps_trained': 400.

Tested on 20.04 with ray-nightly 1.2.0.dev0

Upon inspecting the underlying environment states, each of the 4 envs has been simulated for 100 time steps. It looks to me like RLlib is simulating each env for the minimum amount of time, equal to ROLLOUT_FRAGMENT_LENGTH and collecting the results. Since each env has >>1 agent, this is greater than the batch size, so the trainer runs an optim step. However, the logger should report num_steps_sampled >= 800 (and in this case, unless RLlib is truncating batches behind the scenes, a number >> 800 since each env has many agents).

Impact: No easy way to measure hardware/sampling performance on variable-agent envs

**Comment by sven1977** [comment]
This PR fixes the issue:
https://github.com/ray-project/ray/pull/14033

Added two more keys to the info dict returned by Trainer.train():
num_agent_steps_trained and num_agent_steps_sampled

**Comment by sven1977** [comment]
@jsuarez5341 ^

**Comment by jsuarez5341** [comment]
Perfect, thank you!
