### ISSUE TITLE
[RFC] Periodically write internal stats to the .out file. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13810]
### Describe your feature request

For example, raylet can emit internal stats inside DebugString() every 10 seconds or so. 

```
std::string ObjectManager::DebugString() const {
  std::stringstream result;
  result << "ObjectManager:";
  result << "\n- num local objects: " << local_objects_.size();
  result << "\n- num active wait requests: " << active_wait_requests_.size();
  result << "\n- num unfulfilled push requests: " << unfulfilled_push_requests_.size();
  result << "\n- num pull requests: " << pull_manager_->NumActiveRequests();
  result << "\n- num buffered profile events: " << profile_events_.size();
  result << "\n- num chunks received total: " << num_chunks_received_total_;
  result << "\n- num chunks received failed: " << num_chunks_received_failed_;
  result << "\n" << push_manager_->DebugString();
  result << "\n" << object_directory_->DebugString();
  result << "\n" << store_notification_->DebugString();
  result << "\n" << buffer_pool_.DebugString();
  return result.str();
}
```

We are already doing this in GCS server, and we can possibly do it in core worker and raylet. This will help us find some anomalies easily when things are going wrong (e.g., too high number of pull requests).

**Comment by simon-mo** [comment]
aren't they written to `session_dir/debug_state.txt`? at least they were written there before.

**Comment by rkooo567** [comment]
Yeah it is already written there. But the benefit of this approach is as follow.

1. It kind of shows the historical information (and using metrics API is imo is not a good idea here because these values are too internal).
2. It is easy to see the tendency with logs (since it is in the log file).
3. Also easier to troubleshoot user issues (we'll be able to detect anomalies in an easier way when looking at user logs).
