### ISSUE TITLE
[Tune] Feature: possibility to report nested metrics

### ISSUE THREAD

**Issue by loicsacre** [ray-project/ray#13827]
When configuring the CLIReporter for a trial, for instance with
```
tune.run(..., progress_reporter=CLIReporter(metric_columns=["date", "training_iteration", "timesteps_total"])
````
it would be nice to be able to report nested metrics such as evaluation ones for which the results are nested like this `result["evaluation"]["episode_reward_mean"]`. It is not possible to access them because the elements of the `metric_columns` parameter are the keys of the result dictionnary.

Potential solutions could be to have some kind of convention (for instance `"evaluation/episode_reward_mean"`) or to accept list as metric_columns (`metric_columns=["date", ["evaluation", "episode_reward_mean"] ]`)

**Comment by loicsacre** [comment]
@richardliaw https://discuss.ray.io/t/tune-feature-possibility-to-report-evaluation-metrics/645

**Comment by krfricke** [comment]
Right, we only have the functionality Richard mentioned for parameter columns, not for metric columns. Would you like to contribute this functionality @loicsacre? Otherwise I can work on it, but it might take a couple of days before I'll get to it.

**Comment by richardliaw** [comment]
@loicsacre thanks a bunch for creating this feature request!

**Comment by loicsacre** [comment]
> Right, we only have the functionality Richard mentioned for parameter columns, not for metric columns. Would you like to contribute this functionality @loicsacre? Otherwise I can work on it, but it might take a couple of days before I'll get to it.

Sorry I don't have time to work on it for the moment. This is not urgent, but it is just something I noticed when playing around with Tune and would be useful

**Comment by orthosku** [comment]
Hi there - how could this be used to display the evaluation episode reward mean per iteration? I can't make it out from the code changes.
