### ISSUE TITLE
[serve]: Ray Serve fails when running a Jupyter notebook via Papermill

### ISSUE THREAD

**Issue by pgagarinov** [ray-project/ray#13840]
### What is the problem?
There is a project called [*papermill*](https://papermill.readthedocs.io/en/latest/usage-cli.html). I use papermill to run Jupyter notebook from the "GET" request handler in Ray Serve. Papermill creates a separate process when it runs the notebook. The first request from the client to the server is handled just fine (but apparently it leaves some garbage behind). The second call causes an exception on the server side and blocks the client.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/4868370/106511375-31272400-64e1-11eb-92bb-01666e7f9e74.png">

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/4868370/106511341-266c8f00-64e1-11eb-93f4-ba2488437727.png">

*Ray 1.1.0*

### Reproduction
Attaching the scripts to reproduce the problem.

[scripts2reproduce.zip](https://github.com/ray-project/ray/files/5906444/scripts2reproduce.zip)

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@simon-mo this looks strange, could you take a look and try to repro?

**Comment by pgagarinov** [comment]
@simon-mo 
I've solved my problem via replacing
```
_ = pm.execute_notebook(....)
```

with
```
    obj_ref = ray.remote(execute_notebook).remote(...)
    _ = ray.get(obj_ref)
```
Is the expected way to make things work?

Also, should the error message be a more user-friendly, maybe even suggesting to call other functions from the request handler via "ray.remote"?

**Comment by simon-mo** [comment]
On the original issue, I wasn't able to reproduce it with Ray nightly and papermill latest. However, I do have to `pip uninstall uvloop` because papermil.execute_notebookl->nbclient->nest_asyncio dynamically patch the asyncio loop. 
```
➜  ~/Downloads/scripts2reproduce python server.py
2021-02-01 17:09:01,594	INFO services.py:1174 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=55330) 2021-02-01 17:09:03,720	INFO http_state.py:70 -- Starting HTTP proxy with name 'iwjxsc:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.31.141-0' on node 'node:192.168.31.141-0' listening on '0.0.0.0:8000'
(pid=55331) INFO:     Started server process [55331]
(pid=55330) 2021-02-01 17:09:07,755	INFO controller.py:180 -- Registering route '/run-dummy' to endpoint 'dummy-backend-endpoint' with methods '['GET']'.
Server is running... press Ctrl+C to stop it if needed.
(pid=55331) 2021-02-01 17:09:14,349	INFO router.py:249 -- Endpoint dummy-backend-endpoint doesn't exist, waiting for registration.
(pid=55374) request processing: started
(pid=55374) input params: {'ALPHA': 2}
(pid=55374) execution of the notebook: started
Executing:   0%|          | 0/5 [00:00<?, ?cell/s]
Executing:  20%|██        | 1/5 [00:01<00:05,  1.30s/cell]
Executing:  80%|████████  | 4/5 [00:02<00:01,  1.02s/cell]
Executing: 100%|██████████| 5/5 [00:04<00:00,  1.32s/cell]
Executing: 100%|██████████| 5/5 [00:04<00:00,  1.09cell/s]
(pid=55374) execution of the notebook: done
(pid=55374) request processing: done
(pid=55374) request processing: started
(pid=55374) input params: {'ALPHA': 2}
(pid=55374) execution of the notebook: started
Executing:   0%|          | 0/5 [00:00<?, ?cell/s]
Executing:  20%|██        | 1/5 [00:00<00:02,  1.46cell/s]
Executing:  80%|████████  | 4/5 [00:01<00:00,  1.72cell/s]
Executing: 100%|██████████| 5/5 [00:03<00:00,  1.01s/cell]
Executing: 100%|██████████| 5/5 [00:03<00:00,  1.26cell/s]
(pid=55374) execution of the notebook: done
(pid=55374) request processing: done
(pid=55374) request processing: started
(pid=55374) input params: {'ALPHA': 2}
(pid=55374) execution of the notebook: started
Executing:   0%|          | 0/5 [00:00<?, ?cell/s]
Executing:  20%|██        | 1/5 [00:00<00:02,  1.42cell/s]
Executing:  80%|████████  | 4/5 [00:01<00:00,  1.68cell/s]
Executing: 100%|██████████| 5/5 [00:03<00:00,  1.02s/cell]
Executing: 100%|██████████| 5/5 [00:03<00:00,  1.26cell/s]
(pid=55374) execution of the notebook: done
(pid=55374) request processing: done
(pid=55374) request processing: started
(pid=55374) input params: {'ALPHA': 2}
(pid=55374) execution of the notebook: started
Executing:   0%|          | 0/5 [00:00<?, ?cell/s]
Executing:  20%|██        | 1/5 [00:00<00:03,  1.32cell/s]
Executing:  80%|████████  | 4/5 [00:01<00:00,  1.58cell/s]
Executing: 100%|██████████| 5/5 [00:03<00:00,  1.05s/cell]
Executing: 100%|██████████| 5/5 [00:05<00:00,  1.01s/cell]
(pid=55374) execution of the notebook: done
(pid=55374) request processing: done
```


On the ray.remote approach, this is a good idea, however, I would suggest running:
```
await ray.remote(execute_notebook).remote(...)
```
so you can handle more requests concurrently in case you have this use case. `ray.get(object_ref)` block the entire process.
