### ISSUE TITLE
[Core]Python calling java always raise a value error

### ISSUE THREAD

**Issue by DashShen** [ray-project/ray#13850]
### What is the problem?
Ray: 1.1.0
OS: macOs 10.15.5
Python: 3.7.9

When I use cross-language feature, let python call java class, ray always raise a value error:
```
ValueError: Cross language feature needs --load-code-from-local to be set.
```
And there is no document to tell me how to set this configuration right.
Even if I start ray cluster with `--load-code-from-local` parameter, 
```
ray start --head --port=6379 --load-code-from-local  --code-search-path=/path/to/counter.jar
```
The ValueError still raised. And only if I set this parameter with `ray.init('auto', _load_code_from_local=True)`, the value error will gone.

Should we update document to tell users how to set this configuration correctly?Or take other way to solve this problem?

**Comment by DashShen** [comment]
@deanwampler Does anyone can reply me?

**Comment by MarcoAlejandro** [comment]
@DashShen have you tried to use: 

```
ray.init(address='auto', job_config=ray.job_config.JobConfig(code_search_path="/path/to/counter.jar"))
```

I've just spotted your error, but it doesn't happen to me if I set up the driver code like above.

**Comment by gudaoxifeng2016** [comment]
Have you solved this problem? I also had this problem with ray 2.3.1
