### ISSUE TITLE
Discuss cache named actor in core worker locally.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#13854]
Bulk users use `ray.get_actor(name=xxx)` temporarily, and it's necessary to enable caching named actor in core worker locally.

Before support it, we'd better to discuss the behavior of `ray.get_actor()`. 

There 're 2 facts of the current named actor now:
- one is `ray.get_actor()` supports the same name for different actors serially:
```python
a = ActorA.options(name="named_actor").remote()
ray.exit_actor(a, no_restart=True)
b = ActorB.options(name="named_actor").remote()       # It does work!!!
```
- another one is that `ray.get_actor()` will raise a `ValueError` if the name doesn't exist.

I'd like to propose these:
（1） named actor doesn't support duplicated name with different actors. Because this is not a strong requirement and if we enable this, users may use it incorrectly as well.
  (2)   `ray.get_actor()` returning None indicates there doesn't exist the name, and returning not None indicates we found a handle for the name but we don't promise the actor is valid. If that's an invalid handle, remote call will raise the corresponding exception.

----
BTW, the reason for proposing no duplicated name for different actors is local core worker has no way to be notified the deletion event.(GCS pubs the deletion event is not a good idea.)

 
After those changes, we can support the TTL for the named actor cache locally.

@edoakes @kfstorm @rkooo567 @simon-mo  @raulchen  cc

**Comment by rkooo567** [comment]
> （1） named actor doesn't support duplicated name with different actors. Because this is not a strong requirement and if we enable this, users may use it incorrectly as well.

Is it the case even after we delete an actor? If so, I think it is a strong requirement to allow duplicated names "after" the actor is deleted. It hurts user experience a lot if we don't allow duplicated names at all in the same cluster.

**Comment by jovany-wang** [comment]
> Is it the case even after we delete an actor

Yes, that's the case, after we delete the actor!

**Comment by jovany-wang** [comment]
> > （1） named actor doesn't support duplicated name with different actors. Because this is not a strong requirement and if we enable this, users may use it incorrectly as well.
> 
> Is it the case even after we delete an actor? If so, I think it is a strong requirement to allow duplicated names "after" the actor is deleted. It hurts user experience a lot if we don't allow duplicated names at all in the same cluster.

If it's necessary to allow duplicated names, maybe we should subscribe the named actor once we cached it. And once the handle of the name is changed, local can be notified as soon. 
But the change is a bit big.

**Comment by jovany-wang** [comment]
@WangTaoTheTonic will follow up this item.

**Comment by jovany-wang** [comment]
Tao is working in progress: https://github.com/ray-project/ray/pull/17339

**Comment by WangTaoTheTonic** [comment]
PR merged. I think we can close this.
