### ISSUE TITLE
[rllib] Load right configuration for the evaluation script

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1386]
The evaluation script at the moment is not loading the configuration (config dict) from the checkpoint. This may produce wrong results or errors if runs have been created with configuration options that are different from the defaults.

cc @ericl @richardliaw @pschafhalter

**Comment by ericl** [comment]
Hmm, this might be somewhat of a feature, since you might want different settings at train and test time.

**Comment by pschafhalter** [comment]
Maybe a `--load-config` flag might be helpful.

**Comment by ericl** [comment]
Flagging is a good idea, perhaps by default it loads it from the file unless you pass --config explicitly.

**Comment by ZzXxL1994** [comment]
no

**Comment by richardliaw** [comment]
Flagging is fine.
