### ISSUE TITLE
[placement group] Can not create pg for fractional resources

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#13862]
### What is the problem?
I try to create a placement group with specific node ip as resources.
I used Ray 2.0.0-dev,  python 3.8.3, and tried with two ways, neither works.

First is directly creating the pg, and assuming the ray cluster_resources already has the node ip resource
```
import ray
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)
ray.init()
ray.cluster_resources() # this will print {'node:192.168.1.5': 1.0, 'CPU': 12.0, 'memory': 232.0, 'object_store_memory': 80.0}
ray.state.current_node_id() # this will print 'node:192.168.1.5'

#creating the pg with ip as the resource bundle
pg=placement_group([{ray.state.current_node_id():0.01}])
ray.get(pg.ready()) # code will stuck here, never return
```

second is to init ray with the custom resources
```
import ray
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)
ray.init(resources={'node:192.168.1.5':1.0})
pg=placement_group([{'node:192.168.1.5':0.01}])
ray.get(pg.ready()) # code will stuck here too.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 2.0.0.dev0, python 3.8.3, os Darwin Kernel Version 19.6.0
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
Attached above.
If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Can you verify this works with CPU:0.001?

**Comment by richardliaw** [comment]
Can confirm that things hang with `pg=placement_group([{'CPU':0.01}])`

**Comment by valiantljk** [comment]
> Can confirm that things hang with `pg=placement_group([{'CPU':0.01}])`

seems not working
```
>>> pg1=placement_group([{'CPU':0.01}])
>>> ray.get(pg1.ready())
```

**Comment by richardliaw** [comment]
Also I can confirm this bug exists on master.

**Comment by richardliaw** [comment]
Ah, this is because fractional resources is being used.

```
pg=placement_group([{'CPU':1}])
ray.get(pg.ready()) # code will stuck here, never return
```
^ this will work fine.

**Comment by valiantljk** [comment]
> Ah, this is because fractional resources is being used.
> 
> ```
> pg=placement_group([{'CPU':1}])
> ray.get(pg.ready()) # code will stuck here, never return
> ```
> 
> ^ this will work fine.

Works for both node ip and CPU, so fraction should not be used in creating pg?

**Comment by richardliaw** [comment]
that's a bug, I think we must support fractions moving forward... but for now, you can workaround by avoiding fractions.

**Comment by rkooo567** [comment]
@richardliaw I think for custom resources, fractional resources are allowed (for example, node IP should work with 0.01, otherwise it doesn't make sense). @wuisawesome do you have any guess why?

**Comment by valiantljk** [comment]
Also, after creating the node ip pg, I can't schedule a task onto it.

```
import ray
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)
ray.init()

@ray.remote
def f():
    return True

pg=placement_group([{'node:192.168.1.5':1}])
ray.get(pg.ready())
f.options(placement_group=pg).remote()
```
the last line will stuck, and prints a warning:

```
2021-02-03 02:24:56,492	WARNING worker.py:1044 -- 
The actor or task with ID 61ce891450422af4ffffffffffffffffffffffff10000000 
cannot be scheduled right now. It requires 
{CPU_group_33cdc64050a4978443ae88cb8c00072e: 1.000000} for placement, 
however the cluster currently cannot 
provide the requested resources. The required resources may be added
 as autoscaling takes place or placement groups are 
scheduled. Otherwise, consider reducing the resource requirements of the task.
```

**Comment by rkooo567** [comment]
@valiantljk When you use the placement group, you need to provide the resource that the placement group bundle contains. So you should,

```python3
import ray
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)
ray.init()
# num_cpus should be 0 because your pg bundle doesn't have cpu
@ray.remote(num_cpus=0, resources={"node:192.168.1.5": 0.X})
def f():
    return True

pg=placement_group([{'node:192.168.1.5':1}])
ray.get(pg.ready())
f.options(placement_group=pg).remote()
```

**Comment by valiantljk** [comment]
Interesting. 
So, by default a task would require num_cpus=1.

**Comment by rkooo567** [comment]
Yep that's right. You can think the placement group pre-reserves resources, and you are scheduling your tasks/actors on those resources.

**Comment by valiantljk** [comment]
> Yep that's right. You can think the placement group pre-reserves resources, and you are scheduling your tasks/actors on those resources.

what happens if the tasks used a lot of cpus, but user only reserves 0.1 cpu? is there preemption during task execution?

**Comment by rkooo567** [comment]
In that case, tasks are just infeasible.

**Comment by rkooo567** [comment]
so it won't be scheduled

**Comment by valiantljk** [comment]
> so it won't be scheduled

I mean, for a task that user doesn't specify any resource requirement, but during runtime, it uses a lot of cpu. 
for example, 
```
@ray.remote
def f():
    ...

f.options(placement_group=pg)remote()
```
for task f, user doesn't specify the num_cpus, but the f can occupy the cpu for a very long time...
in this case, if pg only reserves 0.1 cpu, what will happen. what does 0.1 cpu mean in ray's context?

**Comment by rkooo567** [comment]
oh, so firstly the default num_cpus of every task is 1! (so your task will require 1 cpu).

But if you don't require any resource that placement group reserves (let's say you are running num_cpus=0 task), placement group won't work (so it is still schedulable, but it won't follow the placement restriction)

**Comment by valiantljk** [comment]
For some reason, today I can't reproduce the issue of 'can not create pg for fractional resources'

**Comment by amogkam** [comment]
I'm trying this out on master, but placement group creation with node resources specified is hanging
```
ray.init(num_cpus=1)
node_ip = ray.services.get_node_ip_address()
pg = placement_group([{"CPU": 1, f"node{node_ip}": 1}])
ray.get(pg.ready())
print("Created Placement group")
```
Does the node resource have to be specified in `ray.init()`?

**Comment by rkooo567** [comment]
This must be automatically set upon ray start, but I am not sure about ray.init

**Comment by richardliaw** [comment]
@amogkam I think you have a typo in your code (`f"node:{node_ip}` is missing the colon)

**Comment by amogkam** [comment]
@richardliaw Ohhh yes good catch. That fixes the problem.
