### ISSUE TITLE
Default actor resources

### ISSUE THREAD

**Issue by pspillai** [ray-project/ray#13884]
### What is the problem?

Ray documentation clearly indicates that by default, when not specified explicitly, ray actors will use 1 cpu resource (https://docs.ray.io/en/master/actors.html#resources-with-actors).  However it seems like the default is actually 0.

*Ray version and other system information (Python version, TensorFlow version, OS):*
I saw this behavior on Ray 0.8.4, 1.0.0, 1.1.0, and 2.0.0dev.    
I'm using Python 3.7.1 and 3.8.5 on Ubuntu 16.04.

### Reproduction (REQUIRED)
```
import ray
ray.init(num_cpus=1)

@ray.remote
class foo:
    def f(self):
        return 1

a = foo.remote()
b = foo.remote()     # There should not be enough resources for this
print (ray.get(a.f.remote()))
print (ray.get(b.f.remote()))    # This should fail (block indefinitely)
```
Based on the documentation, I would expect that there would be a warning that an actor could not be scheduled and is pending , and the second ray.get will block forever.  However, this is not the case -- code terminates, showing both actors were constructed even though total cpu resources was limited to 1.   

In contrast, with explicit num_cpus parameter, the code behaves as expected.
```
import ray
ray.init(num_cpus=1)

@ray.remote(num_cpus=1)
class foo:
    def f(self):
        return 1

a = foo.remote()
b = foo.remote()     # There should not be enough resources for this
print (ray.get(a.f.remote()))
print (ray.get(b.f.remote()))    # This should fail (block indefinitely)
```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
> If you do not specify any resource requirements in the actor class’s remote decorator, then by default, the actor will not acquire any resources for its lifetime, but every time it executes a method, it will need to acquire 1 CPU resource.

So the creation doesn't require resources (Actor.remote()), but the execution does (a.f.remote())). I am actually not sure if the latter is still the case. cc @wuisawesome

**Comment by wuisawesome** [comment]
Yeah this is a little subtle. `ray.remote` and `ray.remote(num_cpus=1)` are _not_ the same. `ray.remote` means the actor uses CPUs whenever it runs anything (the constructor, a function, etc), but it _frees_ the CPU when it's not using it. 

`ray.remote(num_cpus=1)` means it just always keeps the CPU.

**Comment by pspillai** [comment]
Actually, it does not seem to acquire the resource when executing either.  If it acquired, we would expect the calls to a.f and b.f to be serialized, but they seem to run in parallel.

```
import time
import ray
ray.init(num_cpus=1)

@ray.remote
class foo:
    def f(self):
        time.sleep(5)
        return time.time()

a = foo.remote()
b = foo.remote()
print( ray.get([a.f.remote(),b.f.remote()]) )
```
Would expect the two times to be about 5 seconds apart, but sample put I get are milliseconds apart (e.g., `[1612381831.23969, 1612381831.2475588]`)

**Comment by rkooo567** [comment]
Yeah it seems like the default is cpu=0, and we reserve resources only for placement (actor creation). I will update the doc accordingly. Thanks for bringing this up!

**Comment by richardliaw** [comment]
@rkooo567 did you fix the docs for this?

**Comment by rkooo567** [comment]
I believe so. Let me double check

**Comment by rkooo567** [comment]
It is handled

**Comment by wuisawesome** [comment]
We can close the issue then right?
