### ISSUE TITLE
Fewer digits for network traffic

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13892]
Sometimes the network traffic column has a very long decimal number. We should always round to just 2 digits or something.

<img width="430" alt="Screen Shot 2021-02-03 at 4 24 45 PM" src="https://user-images.githubusercontent.com/9871461/106817404-701dbc80-663c-11eb-87b4-5726de093ad2.png">

**Comment by edoakes** [comment]
Memory too!

<img width="314" alt="Screen Shot 2021-05-13 at 1 28 47 PM" src="https://user-images.githubusercontent.com/9871461/118169968-2e48a300-b3ef-11eb-89ce-1d15bae46355.png">

**Comment by alanwguo** [comment]
This has been fixed.
