### ISSUE TITLE
Render worker table on nodes page

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13894]
<img width="1555" alt="Screen Shot 2021-02-03 at 4 27 56 PM" src="https://user-images.githubusercontent.com/9871461/106817662-cd197280-663c-11eb-9f12-1d4cb0760d1e.png">

In the old dashboard, you could expand a node to see the workers and their resource usage on the same page. Now, you need to click on the "id" field (which users may not realize) and then click over to the "workers" tab. Can we allow users to just expand the node card and see all of the workers below?

**Comment by hegdeashwin** [comment]
@edoakes Let me check this out.
