### ISSUE TITLE
[autoscaler] Make it possible to specify availability zone

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1389]
I was running into this on the current master, wanted to start a bunch of g2.2xlarges. According to https://github.com/ray-project/ray/blob/d21ea0ca451b53608c70fc4bff0dbb7b0e1530ff/python/ray/autoscaler/aws/config.py#L139
the script used the availability zone that comes last in the alphabet (us-east-1f in my case) which didn't have these instances.

For now I'm working around it by changing it to `reverse=False`.

**Comment by richardliaw** [comment]
Another current workaround is specifying the subnet corresponding to the availability zone.

**Comment by robertnishihara** [comment]
Fixed by #1393
