### ISSUE TITLE
Object store usage for workers/actors

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13890]
In the existing dashboard we can see the object store usage of each process and node.

**Comment by raulchen** [comment]
@edoakes do you know how to get the object store usage for a worker?

**Comment by edoakes** [comment]
The easiest way to find out would be to look at the current OSS dashboard frontend code and trace it back, because it's displaying per-worker GPU stats.

I believe the way it works is we get the GPU usage by GPU index here:
https://github.com/ray-project/ray/blob/master/dashboard/modules/reporter/reporter_agent.py#L336

Then we get the GPUs assigned to the workers via CoreWorkerStats:
https://github.com/ray-project/ray/blob/master/src/ray/protobuf/common.proto#L401

We then display the usage of the correct indices of a given worker.

**Comment by SongGuyang** [comment]
@edoakes @raulchen I will try to do this.
