### ISSUE TITLE
Remove the TaskFuncDesc and replace it with human-readable name

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#13893]
<img width="437" alt="Screen Shot 2021-02-03 at 4 26 26 PM" src="https://user-images.githubusercontent.com/9871461/106817556-a0655b00-663c-11eb-9895-77d7c0640586.png">

Instead of the above, we should just have the function/class name of the task/actor.

**Comment by mxz96102** [comment]
Rename to class name col to display functionDescriptor

**Comment by SongGuyang** [comment]
Solved by https://github.com/ray-project/ray/pull/26785.
