### ISSUE TITLE
[core] Actor will never be created once the owner driver shutdown intentionally before resolving dependencies.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#13902]
## Reproductable Script
(1) Run `ray start --head`
(2) Run the following driver code:
```python
import ray
import time

ray.init(address="auto", _redis_password='5241590000000000')

@ray.remote
def slow_hi():
    time.sleep(5)
    return "hihihi"

@ray.remote
class TargetActor:
    def __init__(self, obj):
        self.str = obj

    def say_hi(self):
        return self.str

obj = slow_hi.remote()
target_actor = TargetActor._remote(lifetime="detached", name="target_actor", args=[obj])

ray.shutdown()
```
Then use `ray.actors()` to look at the state of `target_actor`, it's `DEAD` eventually.
If we add a `sleep(10)` before `ray.shutdown()`, it will pass.

This is similar to the issue #13900 , but it's not the same one. In this issue, `target_actor` is created in driver and then driver exits gracefully. That means this `shutdown` is a user's behavior, so in the nature of things, we should make sure the `target_actor` created eventually.

To achieve the goal, we should make sure driver has received all of the task replies before gracefully exiting.

**Comment by rkooo567** [comment]
I can imagine this type of code could be pretty common. Great catch!

**Comment by rkooo567** [comment]
Are you guys planning to work on fixing it?

**Comment by jovany-wang** [comment]
> Are you guys planning to work on fixing it?

But we haven't a good solution on this.  How do you guys think?

**Comment by rkooo567** [comment]
Hmm yeah. 

> To achieve the goal, we should make sure driver has received all of the task replies before gracefully exiting.

This sounds potentially problematic (since we won't know when those tasks will be done).

**Comment by jovany-wang** [comment]
One possible solution is that driver sends the `REGISTER_ACTOR` request to GCS, and the GCS store it and reply `REGISTERED` to caller. Once that done, it means GCS will promise the actor will never be lost even if the dependencies unresolved. But I'm not sure if this is conflict with ref-counting.

@rkooo567 @edoakes @wumuzi520 @kfstorm @raulchen @chaokunyang @ashione 
Do you have more thoughts on this?

**Comment by ashione** [comment]
Will it make ray.shutdown more complicated processing since it must get all of infilght response.

**Comment by jovany-wang** [comment]
Maybe another feasible way is add a flag `wait_until_actors_are_created` for `ray.shutdown()`

**Comment by jovany-wang** [comment]
@rkooo567 
After some discussions offline, we'd like to propose the `ray.wait(actor)` or `ray.wait(actors)` API to work to address this issue.  Because we have no more good and simple solution to wait until we have received a response of an asynchronous request.

`ray.wait(actor)` is a synchronous API, and it will wait until the actor state became alive.

Why not users use a dummy `ping()` method for the actor, because our  users have many actors in a job, they have been suffering that adding many many meaningless methods for actors, such as `ping()`, `heath()` and `check()` etc.

**Comment by ericl** [comment]
I'd be in favor of allowing ray.wait() on actors, would you be interested in contributing this?

**Comment by jovany-wang** [comment]
> I'd be in favor of allowing ray.wait() on actors, would you be interested in contributing this?

OK

**Comment by jovany-wang** [comment]
This issue will be enhanced in the feature `wait actor`:  https://github.com/ray-project/ray/issues/14923
