### ISSUE TITLE
[RLlib] Performance decrease when used more workers

### ISSUE THREAD

**Issue by stanislav-chekmenev** [ray-project/ray#13907]
Performance decreases when the number of cores increases.  Check out the following output:

N CPUs: 1. Sample throughput: 1005.539. Sample time: 4009.79.Total time 58.33322477340698
N CPUs: 2. Sample throughput: 1429.264. Sample time: 2865.811.Total time 53.83760857582092
N CPUs: 4. Sample throughput: 1830.129. Sample time: 2238.093.Total time 48.2752788066864
N CPUs: 6. Sample throughput: 981.671. Sample time: 4302.866.Total time 62.42157578468323
N CPUs: 8. Sample throughput: 740.618. Sample time: 5530.516.Total time 66.46916174888611

The throughput increases up until 4 CPUs and then drops.

The issue almost disappears when I redo `ray.init()` for each new run with a different amount of workers:

N CPUs: 1. Sample throughput: 1088.754. Sample time: 3703.316.Total time 53.739232301712036
N CPUs: 2. Sample throughput: 1486.653. Sample time: 2755.182.Total time 50.54168391227722
N CPUs: 4. Sample throughput: 1889.726. Sample time: 2167.51.Total time 50.093419313430786
N CPUs: 6. Sample throughput: 2192.979. Sample time: 1926.147.Total time 49.009753704071045
N CPUs: 8. Sample throughput: 2230.116. Sample time: 1836.676.Total time 50.85565519332886

**However the total time spent is not really changing. Can you tell why? Why does it matter if one does `ray.init()` once or several times?**

Then the numbers are the following

**Ray: 2.0.0.dev(), Python: 3.8.6,  Ubuntu 18.04, PyTorch 1.7.1**

### Reproduction

To reproduce the bug run this script:

```python
import ray

from ray.rllib.agents import ppo


def main() -> None:
    EPOCHS = 5
    NUM_WORKERS = [1] + list(range(0, 9, 2))[1:]

    ray.init()
    res = {}
    for cpu in NUM_WORKERS:
        config = {
            'framework': 'torch',
            'log_level': 'DEBUG',
            'num_workers': cpu,
            'num_gpus': 0,
            'num_envs_per_worker': 1,
            "rollout_fragment_length": 64,
            "train_batch_size": 4000
        }
        trainer = ppo.PPOTrainer(env="CartPole-v0", config=config)
        for i in range(EPOCHS):
            res[cpu] = trainer.train()

    sample_throughput = []
    total_time = []
    sample_time = []

    for cpu in NUM_WORKERS:
        sample_time.append(res[cpu]['timers']['sample_time_ms'])
        sample_throughput.append(res[cpu]['timers']['sample_throughput'])
        total_time.append(res[cpu]['time_total_s'])

    for i, cpu in enumerate(NUM_WORKERS):
        print(f'N CPUs: {cpu}. Sample throughput: {sample_throughput[i]}. Sample time: {sample_time[i]}.'
              f'Total time {total_time[i]}')


if __name__ == '__main__':
    main()
```
To get the second results just move `ray.init()` to the next line after `for cpu in NUM_WORKERS` and add `ray.shutdown()` in the end of that for-loop.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stanislav-chekmenev** [comment]
Apparently, when we re-init the trainer with a new number of CPUs the previous involved cores are not freed and still in use, that's why we see a decrease in performance right after more than half of the cores has been used in training. The same pattern is seen with more CPUs.

**Comment by lethaiq** [comment]
@stanislav-chekmenev I observe the same behaviors. Do you have a solution for this yet?

"num_workers": 1,
"num_envs_per_worker": 1,
"num_cpus_for_driver": 1,
"num_cpus_per_worker": 15,

=> works fine

"num_workers": 2,
"num_envs_per_worker": 1,
"num_cpus_for_driver": 1,
"num_cpus_per_worker": 15,

=> performance decreases

"num_workers": 1,
"num_envs_per_worker": 2,
"num_cpus_for_driver": 1,
"num_cpus_per_worker": 15,

=> performance decreases
