### ISSUE TITLE
[Core] Actor never be created if the owner die before resolved dependencies

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#13900]
## Brief
Detached actor will never be created if the owner die before resolving dependencies.

## Reproductable Script
(1) ray start --head
(2) Run a driver script
```python
import ray
import time

ray.init(address="auto", _redis_password='5241590000000000')

@ray.remote
def slow_hi():
    time.sleep(5)
    return "hihihi"


@ray.remote
class TargetActor:
    def __init__(self, obj):
        self.str = obj

    def say_hi(self):
        return self.str


@ray.remote
class Worker1:
    def run(self):
        obj = slow_hi.remote()
        target_actor = TargetActor._remote(lifetime="detached", name="target_actor", args=[obj])
        return "running"

w1 = Worker1._remote(lifetime="detached", name="w1")
print(ray.get(w1.run.remote()))
ray.kill(w1, no_restart=True)


# try to use `target_actor`
while True:
    try:
        target_handle = ray.get_actor("target_actor")
        break
    except ValueError:
        continue

print(ray.get(target_handle.say_hi.remote()))
```
**You will never get `hihihi` string printed and the driver hangs at `while True`.**

(3) And if we use `ray.actors()` to show all actor information, you will get:
```bash
w1: DEAD (Because we killed it intentionally.)
target_actor: DEAD (I believe this is not correct.)
```

Then if you add a sleep before we kill w1:
```diff
 w1 = Worker1._remote(lifetime="detached", name="w1")
 print(ray.get(w1.run.remote()))
+time.sleep(10)
 ray.kill(w1, no_restart=True)
```
the script will pass.

## Reasons
The reasons for this issue are:
(1) GCS will kill unresolved actor if its owner dead even if the unresolved actor is detached.
(2) GCS depends on 2 steps ( `REGISTER` and `CREATE` ) to create an actor. In some words, if an actor was registered to GCS but the caller doesn't call `CREATE` to GCS, once the caller dead, the actor wouldn't be created any longer.
(3) Above 2 points depends on another keyword `detached` , so I'd like to know more about whether `detached` is necessary actually.

Before we reach the agreement on `detached` , we can fix the (2): once an actor registered, that means we promise to client that we will create the actor eventually, even if its state is `DEPENDENCIES_UNREADY` .

**Comment by richardliaw** [comment]
@rkooo567 can you take a look?
