### ISSUE TITLE
ray.init() is hanging

### ISSUE THREAD

**Issue by seyuboglu** [ray-project/ray#13910]
### What is the problem?
`ray.init()` is hanging. After logging `2021-02-04 10:22:05,793 INFO services.py:1193 -- View the Ray dashboard at http://127.0.0.1:8265`, `ray.init()` never returns. 

I'm running on CentOS Linux release 7.6.1810 (Core) with Python 3.8.5 

Thank you!

### Reproduction (REQUIRED)
```
import ray
ray.init()
```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
If you run `ray start` in your terminal, is it also hanging?

**Comment by rkooo567** [comment]
Also, can you zip your log files in /tmp/ray/session_latest/logs and post here?

**Comment by seyuboglu** [comment]
`ray start --head` is not hanging 
2021-02-04 10:59:58,748 INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265

attached logs below
[ray_logs.tar.gz](https://github.com/ray-project/ray/files/5927934/ray_logs.tar.gz)

**Comment by rkooo567** [comment]
So this is the log I found
```
[2021-02-04 11:00:29,824 I 24275 24275] worker_pool.cc:375: Some workers of the worker process(24333) have not registered to raylet within timeout.
```

Can you follow this step?
1. Run ray.init()
2. Look at log raylet.out and see if you can see the same log
3. See if the corresponding pid has been actually spawned (if not you can probably see if there was kernel crash using a demsg command (https://man7.org/linux/man-pages/man1/dmesg.1.html)).

**Comment by rkooo567** [comment]
It looks like ray.init is waiting until worker processes are spawned, but they never actually was spawned (for some unknown reasons), and that's why it was hanging .

**Comment by suuyawu** [comment]
Any update?

**Comment by richardliaw** [comment]
IF anyone can reproduce on AWS, this would be very much appreciated.

**Comment by Rubydesic** [comment]
For anyone who has showed up here from Google, #13794 is the reason. The workaround is to use conda instead of a venv or make your venv using a lower version of python. Hopefully you can save the hours I wasted on this

**Comment by haderbacheamir** [comment]
I had the same issue on centOS 7 machine, I could solve my problem by introducing the num_cpus parameter as : `ray.init(num_cpus=1)` before using ray.tune() function.

**Comment by putdanil** [comment]
The issue is still here, it seems to happen only on specific gpu or cpu. Fixable only with ray.init(num_cpus=1).
