### ISSUE TITLE
Output logs to log files instead of stdout in C++ tests.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#13927]
When we execute C++ test in `bazel test xxx`, the logs of gcs, raylet are both outputted to stdout, which is hard to debug.

We have 2 options:
- Add a flag or env-var to indicate if we need output all text of logs to stdout.
- DO NOT output logs to stdout any longer.

**Comment by rkooo567** [comment]
Why not just using --test_output=streamed?

**Comment by jovany-wang** [comment]
1. --test_output=streamed just output the logs in real time, and it still outputs all logs to stdout. We have to grep them by pid, such as if gcs_server pid is 1999, we should `grep 1999 -r ./` to filter gcs logs. 
2. https://github.com/ray-project/ray/blob/master/src/ray/core_worker/test/core_worker_test.cc#L114 core_worker_test depends on gcs and raylet.

**Comment by rkooo567** [comment]
We removed a core worker test btw I believe

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/13514#issuecomment-764120791

In this case, this is not necessary right?
