### ISSUE TITLE
[core] placement groups `ready()` always returns in local mode

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#13932]
### What is the problem?

With `local_mode=True`, placement groups `ready()` remote function always returns the placement group, even if it is unfeasible to schedule. The state in the `placement_group_table` is correctly stated as `PENDING`.

Tested on latest release (1.1.0) and latest master.

### Reproduction (REQUIRED)
```
import time

import ray
from ray.util import placement_group, placement_group_table

ray.init(num_cpus=2, local_mode=True)  # Passes with `local_mode=False`

pgs = [placement_group([{"CPU": 1}]) for _ in range(3)]

time.sleep(0.5)
print(placement_group_table())  # One is pending

ready_futs = [pg.ready() for pg in pgs]


ready, not_ready = ray.wait(ready_futs, num_returns=3, timeout=1.)
assert len(ready) == 2, f"Num ready PGs: {len(ready)}"
assert len(not_ready) == 1

```

cc @ericl 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
ah, yeah it is because in local mode every task is just executed right away... maybe we should write placement group APIs for a local mode.

**Comment by rkooo567** [comment]
Are you guys blocked by this?

**Comment by krfricke** [comment]
No, it was just a failing test. When setting `local_mode=False` the test takes a little bit longer but passes.

**Comment by rkooo567** [comment]
Duplicate https://github.com/ray-project/ray/issues/17937
