### ISSUE TITLE
tune.run() method cluttering the display with logs

### ISSUE THREAD

**Issue by pragyagarg642** [ray-project/ray#13930]
In trainable method, if there is print statement (for e.g., ```print("Something"), end="\r", flush=True)```) inside a loop then, instead of overwriting the existing printed statement it displays it on new line and this leads to cluttering the display with repetitive logs. Tried using the logging parameter to control log level but it is not working in this case. Another option that can be used is ```log_to_driver=False``` in ray.init() but it suppresses the logs entirely. We need to suppress these repetitive logs only and print them once i.e, overwrite the already printed statements. Any help would be appreciated. Thanks.

Adding example screenshot of the issue:
![image](https://user-images.githubusercontent.com/37925282/107003312-92d1e180-67b2-11eb-81a5-e1a2dafc1cda.png)

**Comment by richardliaw** [comment]
`\r` doesn't work well because we don't enable interactive stdout/err printing for remote processes. If you want to print output, I recommend using a callback or custom progress reporter.

**Comment by pragyagarg642** [comment]
Okay, thank you @richardliaw
