### ISSUE TITLE
[tune] Is there an option to discard trial?

### ISSUE THREAD

**Issue by andrefagundes10** [ray-project/ray#13957]
In hyperopt there is the option: 

return {loss: None, status: STATUS_FAIL}

In optuna:

raise optuna.exceptions.TrialPruned()

In Ray Tune???

**Comment by krfricke** [comment]
Hi @andrefagundes10, that depends where you want to make this decision.

If you want to make this decision in the trainable, you can just return. The trial is then marked as complete.

If you want to make this decision in the driver, you can use a Stopper callback for this: https://docs.ray.io/en/master/tune/api_docs/stoppers.html
