### ISSUE TITLE
Dask task based shuffle inefficient to execute in Ray due to dummy map split tasks

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#13959]
### What is the problem?

It seems like shuffle requires N^2 number of tasks for shuffle implementation (There are N^2 `getitem` tasks, each of which literally just gets a single entry from a dictionary, where N is a number of partitions). This is unnecessary for Ray as we natively support multiple return object references. We should pack all these getitem tasks into a single task to remove unnecessary overhead. In this way, we can remove the task overhead to N. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Should note the fundamental issue is causing O(n^2) data restores from external storage in the worst case with object spilling.
