### ISSUE TITLE
[tune] Auto-filled metrics suppression

### ISSUE THREAD

**Issue by ptyshevs** [ray-project/ray#13965]
According to the [docs](https://docs.ray.io/en/master/tune/user-guide.html#tune-autofilled-metrics), there are multiple metrics auto-reported upon trial completion.

Q: Is it possible to modify the final dict of what is reported?

Use-case: using Class API, we provide additional information to Trainable.setup via config regarding model structure. This is then gets automatically stored in `params.pkl` along with proper hyperparameter sample.

Any help is highly appreciated.

**Comment by krfricke** [comment]
Hey @ptyshevs, in the class API everything you return in the `step()` function is reported to Ray Tune. You cannot change values of auto-filled metrics, but depending on what you need you can either report these metrics yourself (in the return dict) or use a custom [logger](https://docs.ray.io/en/master/tune/api_docs/logging.html) to augment the results and write them to some kind of log.

**Comment by ptyshevs** [comment]
@krfricke custom logger won't enable me to remove some of the auto-filled metrics, right?
I was looking through the source code, but couldn't find the specific place where those values are imputed. I'd appreciate the reference to it.

**Comment by richardliaw** [comment]
Which of the metrics are you thinking to remove?

**Comment by ptyshevs** [comment]
@richardliaw I've added special objects to config that are used in `tune.Trainable.setup` for initialization. `Tune` then reports entire config, that includes those objects, and stores everything in `params.pkl` under trial folder.

I'd like to filter out `config` before it is auto-reported.
