### ISSUE TITLE
why is trainer.current_epoch used for model checkpoint callback for Pytorch Lightning

### ISSUE THREAD

**Issue by turmeric-blend** [ray-project/ray#13971]
1. In the model saving [callbacks](https://github.com/ray-project/ray/blob/918ad84f08ee3e019e79d049442fc509777abac0/python/ray/tune/integration/pytorch_lightning.py#L220) for Pytorch Lightning, why is `step=trainer.global_step` used instead of `step=trainer.current_epoch`? Using `current_epoch` seems more intuitive as the save checkpoints per trial will be named after the **epoch of that trial** and not the global 'step' of all trials.

**Comment by amogkam** [comment]
Hey @turmeric-blend, the argument to `step` is used to determine the name for the checkpoint directory. But, we need to make sure that each checkpoint directory name is unique. In cases where we are checkpointing multiple times per epoch, then we cannot use `current_epoch` as the checkpoint directory name because a directory with that name will have already existed.

**Comment by turmeric-blend** [comment]
For a normal training/validation setup the workflow is, for **each** epoch, `training_loop` --> `validation_loop` --> `checkpointing to determine whether to save model or not`. In this case, this:

> In cases where we are checkpointing multiple times per epoch

would **not** occur, and can I just confirm that the defaults in ray's callbacks are to work with the normal cases?

In addition, can I know what would the ray settings be to work with this case:

> In cases where we are checkpointing multiple times per epoch

Thank you !

**Comment by amogkam** [comment]
It's definitely viable to checkpoint multiple times per epoch. For example, you can checkpoint after each training batch like so:
```
callback = TuneReportCheckpointCallback(on="batch_end")
```

Using the global step for checkpoint directory name ensures that all directories have a unique name in all cases, regardless of the checkpoint frequency. If you want to map global-step based directory names to epoch numbers, it should just be the lowest step is epoch 0, the next lowest is epoch 1, and so on.

That being said, it should be possible use `trainer.current_epoch` for epoch checkpointing, and `trainer.global_step` for checkpointing at other frequencies. Can you explain more about your use case? Is this request mainly for human readability, or is there more context here?

**Comment by turmeric-blend** [comment]
I have my callback like so: `callback = TuneReportCheckpointCallback(..., on="validation_end")`. And internally in the [callback method](https://github.com/ray-project/ray/blob/918ad84f08ee3e019e79d049442fc509777abac0/python/ray/tune/integration/pytorch_lightning.py#L220) I changed `trainer.global_step` to `trainer.current_epoch` for ease of readability of my files. 

```
with tune.checkpoint_dir(step=trainer.current_epoch) as checkpoint_dir:
            trainer.save_checkpoint(
                os.path.join(checkpoint_dir, self._filename))
```

I was afraid I might break something (or worst have a saving bug without knowing it - eg maybe the latest best file won't be saved if there already exists a checkpoint with the same name like you mentioned) since I am not so familiar with ray tune. 

My guess was if my training/validation setup was in a way that it would never run into the case where **multiple checkpoints would be made within a single epoch**, then I wouldn't have to worry about any checkpointing issues. Would having `callback = TuneReportCheckpointCallback(..., on="validation_end")` be enough to ensure this?

**Comment by amogkam** [comment]
Ah I see, yes using that `current_epoch` as the dir name is fine as long as there is only one checkpoint per epoch. Your current setup looks good.
