### ISSUE TITLE
Driver fetch its job ID from GCS server in core worker layer

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#13984]
In our Java and Python code, we get the next job ID via accessing the primary redis server directly. For the long term, a driver should send an RPC request to GCS server to get its job ID in the core worker layer, and `job_id` should be removed from `CoreWorkerOptions`.

**Comment by SongGuyang** [comment]
I need to do this.

**Comment by kfstorm** [comment]
@SongGuyang #16190

**Comment by kfstorm** [comment]
@WangTaoTheTonic Are you still working on this?

**Comment by WangTaoTheTonic** [comment]
This has been done with https://github.com/ray-project/ray/pull/16528 and https://github.com/ray-project/ray/pull/16190
@kfstorm

**Comment by kfstorm** [comment]
@WangTaoTheTonic Has C++ worker been migrated to the new approach?

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic Has C++ worker been migrated to the new approach?

I didn't see cpp worker use this api.

**Comment by WangTaoTheTonic** [comment]
c++ part addressed. Let's close this.
