### ISSUE TITLE
When the task starts to read local data, will these data be read to the Object Store?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#13980]
Hello, 
If I use @remote annotation on a function that reads data, will the local data (hdfs) enter the ObjectStore first?

**Comment by rkooo567** [comment]
Data will be stored in the object store if ray.put is called or the object is returned from ray tasks, (e.g.,

```
@ray.remote
def f():
    return np.zeros(100000) # will be stored in the object store. Note the object is stored in the plasma store only when the size is bigger than 100KB
```
)
