### ISSUE TITLE
[tune] Custom Early Stopping leads subsequent trials always terminating within the first iteration 

### ISSUE THREAD

**Issue by envision253** [ray-project/ray#13983]
Hi everyone,

I'm using Ray Version '1.1.0' with Python 3.7.4 on Mac OS X Catalina 10.15.7. My goal is to get the desired number of samples (i.e. num_samples), stopping bad trials early based on some timeout criterion. Here I have chosen the default sample (i.e. Basic Variant Generator), although this also happens with other sampling schemes as well. 

I tried implementing a custom stopper which terminates a trial lets say after 50s. The first two trials (parallelized batch) works perfectly fine. But after this all trials get stopped within the first iteration. If I omit the custom stopper, this does not happen and all trials run through successfully. 

Is there any parameter I'm missing that leads to this sort of behavior?

```python
import ray 
import time 

from ray import tune
from ray.tune.suggest.basic_variant import BasicVariantGenerator
from ray.tune.stopper import Stopper


class CustomStopper(Stopper):
    def __init__(self):
        self._start = time.time()
        self._deadline = 50

    def __call__(self, trial_id, result):        
        return (time.time() - self._start) > self._deadline
    
    def stop_all(self):
        return False


def easy_objective(config):
    for trial_iter in range(500):
        time.sleep(10)
        tune.report(trial_iter)
    
    return config['dummy'] ** 2 


analysis = tune.run(
    easy_objective,
    name = "early-stopping-test",
    config = {'dummy' : tune.uniform(0,1)},
    num_samples = 1000,
    log_to_file = True,
    verbose = 1, 
    resources_per_trial = {'cpu' : 2}, 
    stop = CustomStopper(),
    )
```

**Comment by krfricke** [comment]
Hi @envision253, you are setting the `self._start` property of your stopper to the current time on initialization. Effectively you're then checking if the start of your complete training run is more than 50 seconds ago - and after the first two trials, each subsequent trial is more than 50 seconds after the start of the experiment. 

What you implemented is thus a global timeout stopper.

What you'll likely want to do instead is to have a per-trial timeout stopper. Here's two possibilities:

1)

You can track the start time on a per-trial basis
```
class CustomStopper(Stopper):
    def __init__(self, deadline=50):
        self._start = {}
        self._deadline = deadline

    def __call__(self, trial_id, result):
        if not trial_id in self._start:
            self._start[trial_id] = time.monotonic()
        return (time.monotonic() - self._start[trial_id]) > self._deadline
    
    def stop_all(self):
        return False
```

2)

You can use the Ray Tune-provided result metric `time_total_s`:

```
class CustomStopper(Stopper):
    def __init__(self, deadline=50):
        self._deadline = deadline

    def __call__(self, trial_id, result):
        return result["time_total_s"] > self._deadline
    
    def stop_all(self):
        return False
```
