### ISSUE TITLE
[rllib] Update RL Exercises to match changes made to the init

### ISSUE THREAD

**Issue by alvkao58** [ray-project/ray#1399]
### Describe the problem

Currently, RL Exercises 3, 4, 5 have incorrect syntax for initializing agents; it should be `PPOAgent(config, 'CartPole-v0')` as opposed to `PPOAgent('CartPole-v0', config)`.

**Comment by richardliaw** [comment]
Thanks @alvkao58! 

Do you want to give it a shot (fork the tutorial repository and then open a pull request there)?
