### ISSUE TITLE
[RFC] runtime_env for actors and tasks

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#14019]
There's been a lot of user questions and discussion around how to specify dependencies for a given job, actor, or task. There are a few different general use cases here:

1. Users want to run tasks/actors that require different or conflicting Python dependencies as part of one Ray application.
2. Users want to use Docker containers to manage dependencies (not just Python) for different tasks and actors as part of one Ray application.
3. Users want to distribute local Python modules and files to their workers/actors for rapid iteration/development.
4. Users want to easily install new Python packages as part of their development workflow (e.g., change library versions without restarting the cluster).

This proposal is to introduce a new `runtime_env` API that enables all of these use cases and can generalize to future worker environment-related demands.

The `runtime_env` will be a dictionary that can be passed as an option to actor/task creation:
```python
f.options(runtime_env=env).remote()
Actor.options(runtime_env=env).remote()
```

This dictionary will include the following arguments:

- `container_image (str)`: Require a given (Docker) container image. The image must have the same version of Ray installed.
- `conda_env (str)`: Activates a named conda environment that the worker will run in. The environment must already exist on the node.
- `files (Path)`:  Project files and local modules to unpack in the working directory of the task/actor.
- (possible future extension) `python_requirements (Union[File, List[str]])`: List of Python requirements or a requirements.txt file to use to dynamically create a new conda environment.

These options should cover the all known dependency management use cases listed above.

Misc semantics:
- Any downstream tasks/actors will by default inherit the `runtime_env` of their parent.
- The `runtime_env` needs to be able to be specified on an individual actor and task basis, but for convenience it should also be able to be set in the `JobConfig` as a default for all tasks/actors spawned by the driver.

At this point, this RFC is primarily about the **use cases** and **interface**, not the implementation of each `runtime_env` option. Please comment if you believe there is a use case not covered, the UX could be improved, etc.

**Comment by richardliaw** [comment]
A couple questions -- 
* Where must the `files` be if they are file system path? Will it be only on the head node or must it exist on any arbitrary node?
* With python_requirements, we will probably also want to introduce a 'pip args' to specify a distro  pull build from?


cc @tgaddair if you have any thoughts, as this might simplify some deployment work.

**Comment by ericl** [comment]
> Where must the files be if they are file system path? Will it be only on the head node or must it exist on any arbitrary node?

They can be anywhere, Ray core will zip up and unpack it on the workers automatically in the worker working directory.

> With python_requirements, we will probably also want to introduce a 'pip args' to specify a distro pull build from?

Yeah, probably need to scope this out one more.

**Comment by rkooo567** [comment]
This looks like a really nice improvement! For the possible serialization issues among actors and tasks, is it supposed to be just handled by users? 

cc @valiantljk. Please comment if you have any feedback!

**Comment by ericl** [comment]
Perhaps we can consider cross-env method calls to be similar to cross-lang calls? https://docs.ray.io/en/master/cross-language.html

The restrictions appear to be:
1. Only primitive types are supported: float, bytes, str, ActorHandle, and arrays of such.
2. Serialization is with msgpack.

We could potentially use the same msgpack interface and extend it to support more types (e.g., numpy arrays, Dicts).

Other options might include:
- Going back to Arrow-based serialization.

**Comment by edoakes** [comment]
I think the simplest solution for now will be to restrict cross-env calls to the same Ray and Python minor versions. Primitive types should then work as expected and it will be up to users to ensure they're using the same application-level library versions if they're passing non-primitive types (e.g., numpy arrays).

Arrow might indeed be a good long-term solution here.

**Comment by valiantljk** [comment]
I think this will be very useful. I'm not clear about how to support the container runtime_env though. 
In my mind, it's a bit weird that the the actor or task itself should bother with the container runtime, e.g., which image to be based on. If the interface is designed in this way, then during actor creation or execution, there should be some runtime check, i.e., comparing the runtime_env with the actual container runtime. 
Would it be nicer if the runtime_env is supported out of the scope of the actor creation? 

But as @edoakes stated this is just for interface design. I'd like to stay tuned for the design and implementation.

**Comment by edoakes** [comment]
@valiantljk good points. We've discussed more about the implementation about the container_image env as that's actually what prompted this discussion initially. Here's a link to a document that goes more in-depth on it:
https://docs.google.com/document/d/1MbsjSye2KgYuLPPUWziU8iPTBCC_0h9EOrUIX4LFC2M/edit#

The TL;DR is that for now this will be tightly integrated with the autoscaler. The autoscaler will add new node types to satisfy scheduling constraints specified by the container_image requirement. In the future we may be able to support per-worker containers, which would allow us to remove this tight coupling of the container image and the node.

**Comment by raulchen** [comment]
Allowing different environments for different jobs makes a lot of senses. 
But I'm not clear in which case we would need to use different environments for tasks/actors in the same job. Why can't just start multiple jobs? 
I could imagine many potential issues: 
- cross-env call could be error-prone.
- if we initialize the env unpon task/actor submission. that could be very slow.
- hard for debugging when something goes wrong as there are many different envs in a job.

**Comment by ericl** [comment]
We have a number of users asking for this, to summarize the main use cases:
- In microservice and model serving workloads, developers want to run different versions of services and models within the same serving job topology.
- In distributed ML pipelines, ML engineers want to stitch together operators written by different teams that may have different library and code dependencies.

Currently these users are not able to use Ray at all (they consider runtime env support as a hard blocker).

re: issues, the plan is as follows:
> cross-env call could be error-prone.

We plan to define a restricted x-env call format (similar to xlang). Ideally this would be unified with xlang calls.

> if we initialize the env unpon task/actor submission. that could be very slow.

It's no slower than launching a new job. The env can be cached on the node, similar to the job.

**Comment by bklaubos** [comment]
> They can be anywhere, Ray core will zip up and unpack it on the workers automatically in the worker working directory.
This means performance hit to dynamically installing dependencies. One possible way is to designate certain nodes as providing dependencies ready environment.i.e not all Ray nodes are "equivalent". Certain workers would be instantiated on certain Ray node. Think of it long the line of K8s's "taint and tolerance" wrt to dependencies.

**Comment by bklaubos** [comment]
> The TL;DR is that for now this will be tightly integrated with the autoscaler. The autoscaler will add new node types to satisfy scheduling constraints specified by the container_image requirement. In the future we may be able to support per-worker containers, which would allow us to remove this tight coupling of the container image and the node.

@edoakes - Instantiating a new pod associated with a task is very expensive. For Actor its probably OK since actors probably expected to live for a while for mutation purpose.

**Comment by nostalgicimp** [comment]
Is this RFC for runtime_env is still ongoing under development? I saw the docs already show its usage(https://docs.ray.io/en/master/advanced.html#conda-environments-for-tasks-and-actors)(https://docs.ray.io/en/master/package-ref.html#ray-remote), but my installed ray2.0.0.dev0 version still couldn't recognize this newly added runtime_env and override_environment_variables.

My ray.get(read_from_hdfs.options(runtime_env={"SEC_TOKEN_STRING":token}).remote()) failed with following error. runtime_env is not within the listed options. 

AssertionError: The @ray.remote decorator must be applied either with no arguments and no parentheses, for example '@ray.remote', or it must be applied using some of the arguments 'num_returns', 'num_cpus', 'num_gpus', 'memory', 'object_store_memory', 'resources', 'max_calls', or 'max_restarts', like '@ray.remote(num_returns=2, resources={"CustomResource": 1})'.

**Comment by edoakes** [comment]
Hey @nostalgicimp, this is under active development! We expect the feature to be GA'd in Ray 1.5 (in around a month or so). On the nightly wheels you can test it out using:

```python
from ray import JobConfig
ray.init(job_config=JobConfig(runtime_env={"working_dir": "."}))
```

We should have some documentation for this up soon.

cc @architkulkarni

**Comment by nostalgicimp** [comment]
> Hey @nostalgicimp, this is under active development! We expect the feature to be GA'd in Ray 1.5 (in around a month or so). On the nightly wheels you can test it out using:
> 
> ```python
> from ray import JobConfig
> ray.init(job_config=JobConfig(runtime_env={"working_dir": "."}))
> ```
> 
> We should have some documentation for this up soon.
> 
> cc @architkulkarni

Thanks @edoakes! 
Looking forward to it.

**Comment by bklaubos** [comment]
@edoakes @architkulkarni https://docs.google.com/document/d/1gLGl_eNUsf0O2se4rKg7fbf9IhHtst1w8ydGPNCXnQI/edit#
say that this RFC is available for Ray 1.4+? Are we at Ray 1.4 today?

**Comment by gilfree** [comment]
Hi.

In 1.6 the RFC has landed, and I saw that there is some code related to container runtime environments. But - the option to select a container in the runtime environment is not documented. 

What is the status of using containers here (different containers of different actors?). Is this WIP, planned, or abandoned? I am not familiar with ray internals, but I am willing to learn and try to lend a hand here.

**Comment by simon-mo** [comment]
Hi @gilfree, the container runtime environment is code complete but pending extensive testing and documentation. It can be considered as WIP and planned to release with upcoming Ray releases.

**Comment by gilfree** [comment]
Thanks for the answer. 

Maybe I am looking at the wrong place, but from looking in the [code](https://github.com/ray-project/ray/blob/ead02b21b9617350f4618b8a41413c19eb3580c4/python/ray/workers/setup_worker.py#L90) it seems that it requires `podman`. Is that the case? 

Do you plan to support other container runtimes? Or make it a configurable option? Also there are some hard coded options there that at least in my environment I will need to control. Will you be willing to accept a PR that makes these customizable, something along the lines of:

```python
container_driver = container_option.get("container_driver","podman")

container_command = container_options.get("container_options",[
        container_driver, "run", 
        "--cgroup-manager=cgroupfs", "--network=host", "--pid=host",
        "--ipc=host", "--env-host"
    ])
container_command.extend("-v", tmp_dir + ":" + tmp_dir)
```

Thanks!

**Comment by richardliaw** [comment]
I think we can close this RFC given that runtime envs is GA now. @architkulkarni @edoakes ?
