### ISSUE TITLE
Connect to ray dashboard via ssh port forwarding on gcc

### ISSUE THREAD

**Issue by Jogima-cyber** [ray-project/ray#14015]
After a ray.init() in a python notebook on google cloud console, I'm trying to forward in ssh the dashboard port with the command : 
gcloud compute ssh name-of-my-instance -- -NfL 8265:localhost:8265
But I keep receiving some "channel 3: open failed: connect failed: Connection refused" and it is impossible for me to connect.
However I can connect with this method to a tensorboard. Do you already have a similar issue ? What do you think could cause it ?

**Comment by rkooo567** [comment]
Hmm can you make sure if the ray dashboard is started on port 8265?
