### ISSUE TITLE
Histogram metric does not update without ray.get

### ISSUE THREAD

**Issue by thegyro** [ray-project/ray#14014]
**Version** - ray.2.0.0.dev (ARM64 build of ray)

In the following snippet

``` python
import time

import ray
from ray.util.metrics import Histogram


@ray.remote
class Actor:
    def __init__(self):
        self.hist = Histogram(name="dummy_hist_metric", boundaries=[1.0,2.0])

    def do(self):
        self.hist.record(1.5)
        print("done")


if __name__ == "__main__":
    print(ray.init(_metrics_export_port=8080))

    start = time.time()

    actor = Actor.remote()

    while time.time() - start < 120:
        actor.do.remote()
        time.sleep(0.03)
```

I don't see the `dummy_hist_metric` being populated in Prometheus. But if I do `ray.get(actor.do.remote())`, I do observe it. `Gauge` and `Count` works fine without `ray.get`. Is there any reason why the `Histogram` metric works differently? My use case requires that I don't use `ray.get` anywhere in my pipeline...

**Comment by edoakes** [comment]
@thegyro I tried reproducing this locally and the metric showed up for me:
```
# HELP ray_dummy_hist_metric 
# TYPE ray_dummy_hist_metric histogram
ray_dummy_hist_metric_bucket{Component="core_worker",Version="2.0.0.dev0",le="1.0"} 0.0
ray_dummy_hist_metric_bucket{Component="core_worker",Version="2.0.0.dev0",le="2.0"} 589.0
ray_dummy_hist_metric_bucket{Component="core_worker",Version="2.0.0.dev0",le="+Inf"} 589.0
ray_dummy_hist_metric_count{Component="core_worker",Version="2.0.0.dev0"} 589.0
ray_dummy_hist_metric_sum{Component="core_worker",Version="2.0.0.dev0"} 883.5
```

Is it possible you didn't wait long enough before checking the endpoint? I believe the reporting interval is 10s by default.

**Comment by thegyro** [comment]
My bad - I do see it now though I had to wait much longer than 15 seconds (default prometheus scrape interval). Thanks for the help!
