### ISSUE TITLE
Performance loss over long periods of time

### ISSUE THREAD

**Issue by thegyro** [ray-project/ray#14020]
**Version** - ray.2.0.0.dev (ARM64 build)

I am using ray to parallelize a stream processing pipeline and improve its throughput. A `main_actor` continuously acquires and pre-processes a batch of images and submits it to a downstream `actor1`. The idea is that while the `main_actor` is working on a batch of images at time `t`, the downstream actor can work on images at time `t-1`.  The following standalone snippet captures this:

```python
import signal
import time
import traceback

import ray
import numpy as np


from ray.util.metrics import Count, Gauge, Histogram


def ray_get(item_ref, metric, tags={}):
    s = time.time()
    item = ray.get(item_ref)
    latency = (time.time() - s) * 1000

    metric.record(latency, tags=tags)
    return item


def ray_put(item, metric, tags={}):
    s = time.time()
    item_ref = ray.put(item)
    latency = (time.time() - s) * 1000
    metric.record(latency, tags=tags)
    return item_ref


NUM_IMGS = 3


@ray.remote
class MainActor:
    def __init__(self, actor1):
        self.actor1 = actor1

        self.main_latency_gauge = Gauge(name="main_actor_latency")
        self.write_gauge1 = Gauge(name="main_actor_write1_latency")
        self.write_gauge2 = Gauge(name="main_actor_write2_latency")
        self.acquired_counter = Count(name="num_acquired")

    def run(self):
        acq_count = 0
        while True:
            try:
                start_time = time.time()
                frame_start_time = time.time()

                img = np.zeros((NUM_IMGS, 3000, 5000), dtype=np.uint8)
                self.acquired_counter.record(value=NUM_IMGS)
                acq_count += 1

                # do some work on img
                time.sleep(0.04)
                img_proc = np.zeros((NUM_IMGS, 300, 500), dtype=np.float32)

                item1 = {
                    'img_proc': img_proc,
                    'frame_start_time': frame_start_time,
                    'frame_remote_start_time': time.time()
                }
                item1_ref = ray_put(item1, self.write_gauge1)
                result_ref = self.actor1.process.remote([item1_ref])

                end_time = time.time()

                self.main_latency_gauge.record((end_time-start_time)*1000)
            except Exception as ex:
                print(traceback.format_exc())


@ray.remote
class Actor1:
    def __init__(self, monitor_actor):

        self.monitor_actor = monitor_actor

        self.actor1_gauge = Gauge(name="actor1_total_latency")
        self.actor1_frame_gauge = Gauge(name="actor1_frame_latency")
        self.actor1_remote_gauge = Gauge(name="actor1_remote_latency")

        self.read_gauge = Gauge(name="actor1_read_latency")
        self.write_gauge = Gauge(name="actor1_write_latency")

    def process(self, item_ref):
        try:
            frame_remote_end_time = time.time()
            start_time = time.time()

            item = ray_get(item_ref[0], self.read_gauge)
            img_proc = item['img_proc']

            # do some work
            time.sleep(0.02)

            result = np.zeros(10, dtype=np.float32)
            result_ref = ray_put(result, self.write_gauge)

            end_time = time.time()

            self.actor1_remote_gauge.record((frame_remote_end_time - item['frame_remote_start_time']) * 1000)
            self.actor1_frame_gauge.record((end_time - item['frame_start_time'])*1000)
            self.actor1_gauge.record((end_time - start_time) * 1000)

            self.monitor_actor.record.remote()

            return result_ref
        except Exception as ex:
            print(traceback.format_exc())


@ray.remote
class MonitorActor:
    def __init__(self):
        self.count = 0
        self.start_time = time.time()
        self.processed_counter = Count(name="num_processed")

    def record(self):
        self.count += 1
        self.processed_counter.record(NUM_IMGS)

        if self.count == 1000:
            print("Num proc: ", self.count * NUM_IMGS, "FPS: ", self.count * NUM_IMGS/(time.time() - self.start_time))
            self.count = 0
            self.start_time = time.time()
            print()


def exit_pipeline(signum, frame):
    global EXIT
    EXIT = True


if __name__ == "__main__":
    print(ray.init(_metrics_export_port=8080))

    monitor_actor = MonitorActor.remote()
    actor1 = Actor1.remote(monitor_actor)

    main_actor = MainActor.remote(actor1)

    EXIT = False
    signal.signal(signal.SIGINT, exit_pipeline)
    signal.signal(signal.SIGTERM, exit_pipeline)

    running = False
    while not EXIT:
        if not running:
            main_actor.run.remote()
            running = True
            print("Started")

    print("Shutting down")
    ray.shutdown()
```

I am tracking the "time of flight" for a particular frame (i.e total time it takes for the frame to be processed through the pipeline) and this is what I observe:

![Screen Shot 2021-02-09 at 7 10 06 PM](https://user-images.githubusercontent.com/4838833/107445501-8e872a80-6b0a-11eb-8aee-65ccef2c81ad.png)

I observe spikes due to two reasons:
 1. Due to a spike in `remote_latency`- the time between when a frame is submitted to `actor1` and when `actor1` begins processing it 
 2. Due to spikes in `ray.get()` and `ray.put()` calls in `actor1`

Is this expected? It would be great if I can get some clarity on how I can fix/alleviate the issue.

**Comment by rkooo567** [comment]
Is the Grafana graph from the script you posted (or from your real application)? 

> Due to a spike in remote_latency- the time between when a frame is submitted to actor1 and when actor1 begins processing it

I think this can happen when actor1 is already occupied (and doing some processing). Each actor will do 1 processing at a time, so if the processing takes longer or if you request to a busy actor, it can take some time between the submission <-> execution.

> Due to spikes in ray.get() and ray.put() calls in actor1
This is also hard to say. ray.get is a blocking call, so it is not weird this can spike in some scenarios. (for example, if your dependency object ref is not read yet when the ray.get is called, it will take long time). If ray.put takes long time, that is a bit weird (unless your object store memory usage is too high, and the object spilling starts happening. You can check it by running `ray memory --stats-only`. https://docs.ray.io/en/master/memory-management.html#object-spilling)

**Comment by thegyro** [comment]
The graph is generated using the script I posted. So hopefully it's reproducible from your end. I modified the script slightly so that I record `frame_remote_start_time` *after* I write the image to the object store. So I submit the task to `actor1` using: `self.actor1.process.remote([item1_ref], time.time())`

The `main_actor` is (intentionally) slower than `actor1` (in theory at least), so I don't see why there should be a bottleneck or queuing up of tasks at all. Also, I don't see these spikes in the first one hour of usage. It only gets worse with time. The object_store_memory is 0.09% utilization, so I am not sure if memory consumption is a problem.

![Screen Shot 2021-02-10 at 2 02 38 AM](https://user-images.githubusercontent.com/4838833/107476946-dd51b600-6b44-11eb-8276-71ce83fa836a.png)


In the above graph, the spikes are predominantly due to `frame_remote_latency` i.e time between submission and execution. Though there are spikes in `ray.get` and `ray.put` calls,  I am not sure if that is the main reason.

I am also including the object_store_memory below:
![Screen Shot 2021-02-10 at 2 11 17 AM](https://user-images.githubusercontent.com/4838833/107477267-7385dc00-6b45-11eb-8e2b-021dc89a851f.png)

**Comment by rkooo567** [comment]
I see. The spike seems definitely interesting. @ericl Do you know when is the case that actor submission overhead could spike?

**Comment by thegyro** [comment]
It does look like tasks are being queued up:

![Screen Shot 2021-02-10 at 12 45 44 PM](https://user-images.githubusercontent.com/4838833/107549602-018db100-6b9e-11eb-9f58-1b5fa030fdd7.png)

The number of pending tasks was 0 when I checked a few hours ago. But now it looks like it's getting worse the longer I run -

![Screen Shot 2021-02-10 at 12 36 56 PM](https://user-images.githubusercontent.com/4838833/107549852-4ca7c400-6b9e-11eb-9382-211eb9facbe1.png)

I can make sure that the `main_actor` doesn't submit a job to `actor1` if `actor1` is already working on something, but that would mean that I drop more frames and the system throughput drops.

**Comment by ericl** [comment]
Sounds like you can ray.wait on some old tasks to bound the queue length?
(Backpressure)

**Comment by thegyro** [comment]
I can do that but I will end up dropping more frames and system performance is still going to drop. In my pipeline, the producing actor is operating at a lower FPS than the consuming actor (in theory) - so there shouldn't' be any bottlenecks right? I am curious to know why it's fine for the first one hour or two and only gets worse with time.

**Comment by ericl** [comment]
It shouldn't affect performance if you wait on sufficiently old tasks right? Those should be long completed so the wait will be instant.

Not sure why the consumer is falling behind---do you know if your application code slowing down or some Ray API call?

**Comment by thegyro** [comment]
The consumer is just a dummy actor that does the following:

```python
  def process(self, item_ref):
          item = ray_get(item_ref[0], self.read_gauge)
          img_proc = item['img_proc']

          # do some work
          time.sleep(0.02)

          result = np.zeros(10, dtype=np.float32)
          result_ref = ray_put(result, self.write_gauge)

          self.monitor_actor.record.remote()

          return result_ref
```

I have provided the entire script to reproduce this in the original post. To clarify:

1. `main_actor` (i.e producer) has 40ms of compute + one shared memory write. 
2. `actor1`(i.e consumer) has 20ms of compute + one shared memory read + one shared memory write. 

If I measure the total latency of each -  `main_actor` is about 40 + 10 ms ~ 50 ms and `actor1` is `20 + 5 ~ 25 ms`.  Since the producer is slower than the consumer, the number of pending tasks for `actor1` should always be zero. For the first one hour or two of use, the whole pipeline runs smoothly, and things work as expected. It only gets worse with time and I want to better understand why that happens.

By using `ray.wait`, I can make sure that the `main_actor` will only submit *new* jobs to `actor1` if the number of pending jobs is less than a threshold (say 5). If `main_actor` has submitted 5 jobs to `actor1` and `all` of them are not complete, I can drop the 6th job. This way the queue doesn't build up. If I track the number of dropped frames over time, for the first one hour or two, I will be dropping 0 frames, and over time, I will keep dropping more and more. But none of this should happen in my specific example because the producer is intentionally designed to be slower than the consumer.

**Comment by ericl** [comment]
It sounds pretty similar to https://github.com/ray-project/ray/issues/13612 then, if the root cause is ray.put slowing down over time.
