### ISSUE TITLE
Can't run ray.init() with ray1.1.0 

### ISSUE THREAD

**Issue by offthewall123** [ray-project/ray#14029]
### What is the problem?

Can't run ray.init() with ray1.1.0
pip install ray==1.1.0
import ray
ray.init()
then would contiously print log

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2021-02-10 07:54:24,748	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
{'node_ip_address': '10.0.2.12', 'raylet_ip_address': '10.0.2.12', 'redis_address': '10.0.2.12:6379', 'object_store_address': '/tmp/ray/session_2021-02-10_07-54-24_300792_19984/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2021-02-10_07-54-24_300792_19984/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2021-02-10_07-54-24_300792_19984', 'metrics_export_port': 60834, 'node_id': '87004ee4982f27b4e68156b9dde677954f779ffc'}
>>> 2021-02-10 07:54:26,770	WARNING worker.py:1034 -- The agent on node sr412 failed with the following error:
Traceback (most recent call last):
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
    await raylet_stub.RegisterAgent(
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612914866.758323786","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914866.758319735","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
(pid=raylet)     await raylet_stub.RegisterAgent(
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
(pid=raylet)     raise _create_rpc_error(self._cython_call._initial_metadata,
(pid=raylet) grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
(pid=raylet) 	status = StatusCode.UNAVAILABLE
(pid=raylet) 	details = "failed to connect to all addresses"
(pid=raylet) 	debug_error_string = "{"created":"@1612914866.758323786","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914866.758319735","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
(pid=raylet) >
e2021-02-10 07:54:28,314	WARNING worker.py:1034 -- The agent on node sr412 failed with the following error:
Traceback (most recent call last):
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
    await raylet_stub.RegisterAgent(
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612914868.303893093","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914868.303889267","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
(pid=raylet)     await raylet_stub.RegisterAgent(
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
(pid=raylet)     raise _create_rpc_error(self._cython_call._initial_metadata,
(pid=raylet) grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
(pid=raylet) 	status = StatusCode.UNAVAILABLE
(pid=raylet) 	details = "failed to connect to all addresses"
(pid=raylet) 	debug_error_string = "{"created":"@1612914868.303893093","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914868.303889267","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
(pid=raylet) >
2021-02-10 07:54:29,808	WARNING worker.py:1034 -- The agent on node sr412 failed with the following error:
Traceback (most recent call last):
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
    await raylet_stub.RegisterAgent(
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612914869.804022989","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914869.804019357","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
(pid=raylet)     await raylet_stub.RegisterAgent(
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
(pid=raylet)     raise _create_rpc_error(self._cython_call._initial_metadata,
(pid=raylet) grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
(pid=raylet) 	status = StatusCode.UNAVAILABLE
(pid=raylet) 	details = "failed to connect to all addresses"
(pid=raylet) 	debug_error_string = "{"created":"@1612914869.804022989","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914869.804019357","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
(pid=raylet) >
exit()2021-02-10 07:54:31,300	WARNING worker.py:1034 -- The agent on node sr412 failed with the following error:
Traceback (most recent call last):
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
    loop.run_until_complete(agent.run())
  File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
    await raylet_stub.RegisterAgent(
  File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1612914871.290903809","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914871.290900337","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

(pid=raylet) Traceback (most recent call last):
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 317, in <module>
(pid=raylet)     raise e
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 306, in <module>
(pid=raylet)     loop.run_until_complete(agent.run())
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(pid=raylet)     return future.result()
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 176, in run
(pid=raylet)     await raylet_stub.RegisterAgent(
(pid=raylet)   File "/home/xdy/miniconda3/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
(pid=raylet)     raise _create_rpc_error(self._cython_call._initial_metadata,
(pid=raylet) grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
(pid=raylet) 	status = StatusCode.UNAVAILABLE
(pid=raylet) 	details = "failed to connect to all addresses"
(pid=raylet) 	debug_error_string = "{"created":"@1612914871.290903809","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5390,"referenced_errors":[{"created":"@1612914871.290900337","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
(pid=raylet) >

### Reproduction (REQUIRED)
>>pip install ray==1.1.0
>>python
>>import ray
>>ray.init()

**Comment by rkooo567** [comment]
Can you show me logs in `/tmp/ray/session_latest/logs`?

**Comment by rkooo567** [comment]
(you can zip it and post here)

**Comment by offthewall123** [comment]
[logs.tar.gz](https://github.com/ray-project/ray/files/5956497/logs.tar.gz)
@rkooo567

**Comment by rkooo567** [comment]
Hey @fyrestone Do you know why this error keeps occurring? It should happen because of the agent issue.

**Comment by rkooo567** [comment]
@offthewall123 Can you also tell us which Linux distro and version you are using?

**Comment by offthewall123** [comment]
> @offthewall123 Can you also tell us which Linux distro and version you are using? Also do you happen to use the private IP or VPN?
Fedora release 29 (Twenty Nine)
No, didn't use vpn.

**Comment by offthewall123** [comment]
And can run successfully with ray0.8.6.....

**Comment by rkooo567** [comment]
Yeah, so we rebuilt the dashboard to make it more scalable and stable, and it seems like one of the dashboard components doesn't work with your env for some reason (seems like some networking issue). The error message just indicates the dashboard is broken (and it is restarted right away, and that's why you keep seeing the issue). 

@fyrestone wrote this code path, and I wonder what's his thought about the issue.

**Comment by fyrestone** [comment]
> Yeah, so we rebuilt the dashboard to make it more scalable and stable, and it seems like one of the dashboard components doesn't work with your env for some reason (seems like some networking issue). The error message just indicates the dashboard is broken (and it is restarted right away, and that's why you keep seeing the issue).
> 
> @fyrestone wrote this code path, and I wonder what's his thought about the issue.

Is the `http_proxy` or `https_proxy` environment var configured? This problem has been fixed by https://github.com/ray-project/ray/pull/12598. Could you try the latest version?

**Comment by offthewall123** [comment]
> > Yeah, so we rebuilt the dashboard to make it more scalable and stable, and it seems like one of the dashboard components doesn't work with your env for some reason (seems like some networking issue). The error message just indicates the dashboard is broken (and it is restarted right away, and that's why you keep seeing the issue).
> > @fyrestone wrote this code path, and I wonder what's his thought about the issue.
> 
> Is the `http_proxy` or `https_proxy` environment var configured? This problem has been fixed by #12598. Could you try the latest version?

Yes, have set a global `http_proxy`. Have tried the latest version....ray 1.1.0

**Comment by fyrestone** [comment]
> > > Yeah, so we rebuilt the dashboard to make it more scalable and stable, and it seems like one of the dashboard components doesn't work with your env for some reason (seems like some networking issue). The error message just indicates the dashboard is broken (and it is restarted right away, and that's why you keep seeing the issue).
> > > @fyrestone wrote this code path, and I wonder what's his thought about the issue.
> > 
> > 
> > Is the `http_proxy` or `https_proxy` environment var configured? This problem has been fixed by #12598. Could you try the latest version?
> 
> Yes, have set a global `http_proxy`. Have tried the latest version....ray 1.1.0

The ray 1.2.0 has been released, could you try it?
