### ISSUE TITLE
Add ability to convert Modin objects to MLDataSet: MLDataSet.from_modin()

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#14039]
### Describe your feature request

It would be great if we had the ability to convert Modin's internal dataframe structure to an `MLDataSet` to use with Ray training. For a long time we have discussed how to have interoperability between training on Ray with Modin, and now we have a straightforward path there.

We can contribute this.

**Comment by ericl** [comment]
FYI @ConeyLiu @richardliaw

**Comment by richardliaw** [comment]
That's great, let us know if you need help!

**Comment by fschlimb** [comment]
Why not creating a ParallelIterator? It's more generic and MLDataSets can work with ParallelIterators.

**Comment by guykhazma** [comment]
Hi @devin-petersohn ,

Wouldn't it be beneficial to have Modin DataFrames as the first class DataFrame for Ray? 
As MLDataset is essentially a parallel iterator of Pandas DataFrames we are losing Modin benefits not?

Thanks

**Comment by devin-petersohn** [comment]
@guykhazma Yes, there is lost functionality with MLDataset. I believe this is a first step toward better integrations. Do you have an idea of what the ideal case would be?
