### ISSUE TITLE
Resume tune task seems ignore the terminated trials

### ISSUE THREAD

**Issue by EscapeReality846089495** [ray-project/ray#14032]
### Althouth I can resume tune task shutdowned before, but I can’t understand why the Number of Trials could be like this:
![image](https://user-images.githubusercontent.com/46855992/107499609-1f740980-6bd0-11eb-9ad8-00746a53c36f.png)

I set num_samples=2 and shutdown the tune after 1 trial. And I resumed the same tune, it could find there was one trial which the status is terminated. But the resumed tune process still runned 2 trials so that the total trials was 3. Is there any concept or feature that I miss?

*Ray version 2.0.0(nightly) and other system information (Python version 3.6, pytorch 1.7.0, Windows 10):*

### Reproduction (REQUIRED)
```python3
import os
import time
from ray import tune
import json
import ray


def train_func(config, checkpoint_dir=None):
    start = 0
    if checkpoint_dir:
        with open(os.path.join(checkpoint_dir, "checkpoint")) as f:
            state = json.loads(f.read())
            start = state["step"] + 1

    for step in range(start, 100):
        time.sleep(1)

        # Obtain a checkpoint directory
        with tune.checkpoint_dir(step=step) as checkpoint_dir:
            path = os.path.join(checkpoint_dir, "checkpoint")
            with open(path, "w") as f:
                f.write(json.dumps({"step": step}))

        tune.report(hello="world", ray="tune")


ray.init(
    num_cpus=2,
    num_gpus=1,
    object_store_memory=7 * 1024 * 1024 * 1024,
    # local_mode=True
)
analysis = tune.run(
    train_func,
    name='a_func',
    num_samples=2,
    resources_per_trial={'cpu': 2, 'gpu': 1},
    resume=True
)
```
This code is rewrited from tutorial of Ray Tune. I terminate the process after 1 trial and resume it, get such a result as shown in the screenshot above.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [2.0.0.dev0 wheels](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-win_amd64.whl).

**Comment by richardliaw** [comment]
I'm actually unable to reproduce this issue unfortunately...

**Comment by EscapeReality846089495** [comment]
I has paste my log on Ubuntu paste.
[Here](https://paste.ubuntu.com/p/H33gYhdJ8x/) is the log before shutdown my tune process.
[Here](https://paste.ubuntu.com/p/vrgZ4kH2nt/) is the log after shutdown.
To be honest, I guass the [WinError 183] may be the key.

**Comment by richardliaw** [comment]
Hmm, well it does seem like the checkpointing didn't succeed.

**Comment by EscapeReality846089495** [comment]
Yes, but I have tried to run as administrator and change the local directory but checkpoint is still not work. What should I do?
