### ISSUE TITLE
[Client] Provide common ObjectRefType

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#14042]
### Describe your feature request

We do a lot of defensive type checking in Modin when using Ray to make sure that things are working. It would be very convenient if `ClientObjectRef` extended `ObjectRef` so that assertions like `assert(isinstance(obj, ray.ObjectRef))` would still work without needing to handle the Client object separately.

**Comment by devin-petersohn** [comment]
Related to modin-project/modin#2688

**Comment by Bhavya6187** [comment]
Hey guys, can you verify if this example works with current nightlies - https://docs.ray.io/en/master/modin/index.html#modin-with-the-ray-client?

I run into this bug when I try to run it.

**Comment by ericl** [comment]
This turns out to be quite tricky to do, since ObjectRef is a native cdef that depends on the C++ runtime. Would the following workaround work?

```
ObjectRefType = Union[ray.ObjectRef, ClientObjectRef]
```

Then you can type check around ObjectRefType instead of ObjectRef directly.

**Comment by devin-petersohn** [comment]
Yes, that will work for our purposes. Something like:

```python
from ray import ObjectRefType

assert isinstance(myobj, ObjectRefType)
```

**Comment by ericl** [comment]
Moving to core bugs for tracking

**Comment by pcmoritz** [comment]
Would it be possible to only have a single `ObjectRef` type for both client and the rest of Ray? Certainly from the API side that would be the simplest (no need for `is_object_ref_type` etc)?

If the implementation requires it, the `ObjectRef` could have an internal distinction if it is a client ref or a Ray ref.
