### ISSUE TITLE
[rllib] Adam Optimizer in PPO

### ISSUE THREAD

**Issue by jkterry1** [ray-project/ray#14053]
As I understand the documentation after comparing it with IMPALA, only SGD is supported with your implementation of PPO. This is a problem because ADAM with annealing is important to reproducing OpenAIs original PPO results. However, in issues, I've seen @ericl reference the existence of adam annealing for PPO. If ADAM for PPO is already available, could the documentation be fixed (e.g. for the eps parameter)? If not, could it be added since it's a moderately important feature?

**Comment by justinkterry** [comment]
Slightly famous paper that's in part on why adam w/ annealing is important for reproducing results: https://openreview.net/pdf?id=r1etN1rtPB

**Comment by cpwan** [comment]
So... has this issue been fixed? I am getting suboptimal results with PPO. Not sure if it is the problem with the optimizer or other parts of my code. 
Can someone confirm which optimizer was used in the PPO?
