### ISSUE TITLE
[Core] Ownership-based Object Directory - Support ray.objects() API when ownership-based object directory is enabled

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#14073]
`ray.objects()` queries the GCS for object location data, which will always be empty when the ownership-based object directory is enabled. If we wish to support this API moving forward, we should support this API when the ownership-based object directory is turned on.

### Implementation

This could be accomplished by leveraging the `ray memory` paradigm of [fetching node stats from all raylets](https://github.com/ray-project/ray/blob/936cb5929c455102d5638ff5d59c80c4ae94770f/src/ray/raylet/node_manager.cc#L2643-L2686), by augmenting the [object ref info in the core worker stats](https://github.com/ray-project/ray/blob/936cb5929c455102d5638ff5d59c80c4ae94770f/src/ray/protobuf/common.proto#L343-L359) to also include object locations.

**Comment by ericl** [comment]
I'm looking at the tests and perhaps we don't need something as strong as ray.objects()? What if we added an internal API for counting the number of objects only?

**Comment by clarkzinzow** [comment]
Yep this issue is assuming that we still want to provide a `ray.objects()` API to users or include object location data in a `ray.memory()` API, if that's not the case then those tests can be fixed with an internal API and I'll close this issue.

**Comment by clarkzinzow** [comment]
Note that https://github.com/ray-project/ray/pull/16130 added an end-user API for getting the locations of a single object, which should suffice for most advanced data locality use cases that previously relied on `ray.objects()`. @ericl do we still want to offer a `ray.objects()` API, or should we close this issue?

**Comment by clarkzinzow** [comment]
@ericl This is already fully implemented, right? I think we can close this, unless we want to discuss exposing this as a public API (it's private rn IIRC).
