### ISSUE TITLE
[tune] make_checkpoint_dir() in function_runner.py should use leading "0"s in checkpoint directory

### ISSUE THREAD

**Issue by thoglu** [ray-project/ray#14072]
Hi,
the current implementation of checkpoint dir creation calls
make_checkpoint_dir() from TrainableUtils in "ray/tune/function_runner.py"
with the option "index=step".

I suggest to change 'index=step' to 'index="%.12d" % step '

so checkpoint dirs are actually numerically sorted at creation, by appending
a sufficient number of leading 0's to the checkpoint directory name.

**Comment by krfricke** [comment]
Thanks, I guess this makes sense. 6 digits should be enough though - there are certainly problems that use more timesteps (e.g. Atari) but I'd argue they are rather rare and you probably wouldn't keep millions of checkpoints.

**Comment by thoglu** [comment]
I think 6 digits is rather low, since in the current implementation "step" refers to the internal training steps, not checkpoint steps.. and again in RL problems you can easily reach 9-10 million training steps.. so why not go with something higher than 6?

**Comment by krfricke** [comment]
We should keep it practical however, and twelve zeros means lines become very long (especially in a terminal). This is a cosmetic issue after all, so I think it should be fine to optimize for the more common cases.

**Comment by thoglu** [comment]
How about 8 digits ;) this probably covers all use cases, including reinforcement learning (999 mio steps) and is not much more than 6
