### ISSUE TITLE
How to remove shared object ?

### ISSUE THREAD

**Issue by bioinfornatics** [ray-project/ray#14070]
Dear,
In order to save memory I would like to remove object puts into shared memory.
Indeed, once the batch of tasks as been done it is not necessary to keep those data in memory.

Thanks to highlight on this topic

best regards

**Comment by rkooo567** [comment]
Objects are removed automatically if the object is not used by programs anymore. For example

a = ray.put(big_obj)
del a

in this case, there’s no reference to a anymore, so the memory is automatically GC’ed (we support distributed ref counting)

**Comment by bioinfornatics** [comment]
Thanks @rkooo567 
I was looking into the API somithnq name `remvoe`, `drop` …
