### ISSUE TITLE
[Docker] Can't get the Dashboard to load at all

### ISSUE THREAD

**Issue by SpencerPao** [ray-project/ray#14071]
### What is the problem?
Whenever I run ray.init() on docker, I can't pull up the dashboard at the address provided. No errors pop up. 
It states 'View the Ray dashboard at http://127.0.0.1:8265", but whenever I go to the link it states that the site can't be reached.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray==1.1.0
tensorflow==2.4.0
Python: 3.6
OS: None (docker)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
Dockerfile:
FROM python:3.6
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "ray_tester.py"]
```
------------------------------------------
```
requirements.txt
tabulate==0.8.7
ray==1.1.0
tune=0.0.1
tensorboardX==2.1
tensorflow==2.4.0
```
------------------------------------------
```
ray_tester.py
import ray
import time
if __name__ == "__main__":
    ray.init()
    time.sleep(1000)
```

------------------------------------------
ALSO: if I were to run this code: https://docs.ray.io/en/master/tune/examples/mnist_pytorch.html.
I get the same issue. (I can't connect to the dashboard interface)

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Hey @SpencerPao maybe you have to do some port forwarding for Docker to get access to the dashboard? 

Can you try running this outside of docker?
