### ISSUE TITLE
How re-start RAY programme after crashing? 

### ISSUE THREAD

**Issue by shamanez** [ray-project/ray#14091]
I get the following messege.

![image](https://user-images.githubusercontent.com/16892570/107861927-fb554880-6ead-11eb-82d1-775daea05206.png)

**Comment by rkooo567** [comment]
Call `ray stop` to make sure your redis server (GCS) is killed (this is the server that uses --port). 

Or if you'd like to start two instances, you can also specify the port; `ray start --head --port=4444`

**Comment by shamanez** [comment]
I have the used the ray stop. But what happens is when program crashes in the middle, it does not free the sever.

**Comment by rkooo567** [comment]
Can you try with ray stop --force and try again in that case?

**Comment by rkooo567** [comment]
And when you said program crashes, what does this mean? Your drivers failed or raylets failed?

**Comment by shamanez** [comment]
Ok. Thanks.

**Comment by rkooo567** [comment]
Is it also happening when you use CTRL+C?

Also, when you say actor crashes, is it crashed due to application error (e.g., your code mistake) or system errors (e.g., Raylet has segfault)? I am trying to figure out if the issue if CTRL+Z, zombie processes due to system failures, or something else/.

**Comment by shamanez** [comment]
Yeah application errors. Nothing wrong with RAY.

**Comment by rkooo567** [comment]
Can you also answer this question? `Is it also happening when you use CTRL+C?` Also, it'd be great if you can give us a reproduction script. (so that I can try with CTRL-Z and see if it happens to me as well)

**Comment by shamanez** [comment]
CTRL+C doesn't even kill the process. I use [this huggingface script](https://github.com/huggingface/transformers/blob/master/examples/research_projects/rag/finetune_rag_ray.sh).
