### ISSUE TITLE
OOM GPU memory on windows

### ISSUE THREAD

**Issue by RocketRider** [ray-project/ray#14106]
I am using ray/rllib on windows (win 10), but I am constantly running into OOM of the GPU.
I do have a 1080Ti with 11GB, CUDA 11.0 is configured. TF 2.4.1 is used.
I tested it with ray 1.0.1, 1.2.0 and master.
The exact same setup runns on linux without any issue.

The error always occures during the first training of PPO or others.

> Traceback (most recent call last):
>   File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\tune\trial_runner.py", line 586, in _process_trial
>     results = self.trial_executor.fetch_result(trial)
>   File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\tune\ray_trial_executor.py", line 609, in fetch_result
>     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
>   File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\Admin\anaconda3\envs\ray_tf2\lib\site-packages\ray\worker.py", line 1456, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(ResourceExhaustedError): ray::PPO.train_buffered() (pid=27140, ip=10.64.249.232)
>   File "c:\users\admin\anaconda3\envs\ray_tf2\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
>     return self._call_tf_sessionrun(options, feed_dict, fetch_list,
>   File "c:\users\admin\anaconda3\envs\ray_tf2\lib\site-packages\tensorflow\python\client\session.py", line 1451, in _call_tf_sessionrun
>     return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
>   (0) Resource exhausted: OOM when allocating tensor with shape[500,72,8,8] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[{{node default_policy_1/tower_1/model_1/MobilenetV3small/expanded_conv_1/depthwise/depthwise}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[default_policy_1/tower_1/Mean_1/_2129]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>   (1) Resource exhausted: OOM when allocating tensor with shape[500,72,8,8] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[{{node default_policy_1/tower_1/model_1/MobilenetV3small/expanded_conv_1/depthwise/depthwise}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 0 successful operations.
> 0 derived errors ignored.

**Comment by rkooo567** [comment]
cc @sven1977 Would you be able to address this question?
