### ISSUE TITLE
[rllib] Pytorch models using a Tensorflow feature

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#14114]
Clean Ubuntu 20.04 env + Ray 1.2 (official release, not 1.2.dev0)

get_action_shape method in rllib/models/catalog.py provides optional parameter framework="tf" but _get_dummy_batch_from_view_requirements in rllib/policy/policy.py calls the method without setting the framework parameter, e.g. ModelCatalog.get_action_shape(view_req_space)

Fix: Add framework parameter to call

**Comment by sven1977** [comment]
Thanks for the issue @jsuarez5341 !

**Comment by sven1977** [comment]
This should be fixed in the current master now. Closing this issue.
