### ISSUE TITLE
a single bug in k8s autoscaler part

### ISSUE THREAD

**Issue by baozhiming** [ray-project/ray#14123]
This bug will never appear, but it is still ugly
![image](https://user-images.githubusercontent.com/32292894/108011835-eeb62900-7042-11eb-8e19-7a92212085a4.png)

**Comment by DmitriGekhtman** [comment]
lol, thanks for pointing that out!
It should read "return config"

I'll fix this next time I open a PR in the Ray repo (within the next few days)
