### ISSUE TITLE
[dashboard] dashboard crashed on nightly

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#14133]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Repro:
- run dashboard on nightly, the page goes blank
- open the console, there some error of undefined attribute related to node.net
- might be related to the rename (net -> network)?

I will revert the original PR in the meantime

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

Checkout this branch #14061 
OS: MacOS

Build the dashboard using:
```
pushd ray/dashboard/client
npm install
npm run build
popd
```
Then run:
```
import ray
ray.init()
```
View the Ray dashboard at the link provided. It will show a blank page.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
I am seeing the same issue. Is it the ClusterFeatureRenderFn has no property 0 or sth?

**Comment by simon-mo** [comment]
yeah that should be the error from the frontend, but the underlying issue is related to some backend changes.

**Comment by rkooo567** [comment]
Is this fixed now?

**Comment by kathryn-zhou** [comment]
@rkooo567 the previous PR was reverted, so it should be fixed. will be adding another PR that re-adds the PR changes along with the more extensive fix
