### ISSUE TITLE
[docs] running time for examples is 0.000 s

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#14130]
### What is the problem?

sphinx-gallery embeds the running time in HTML for examples, but on the ray docs it shows 
> **Total running time of the script**: ( 0 minutes 0.000 seconds)

e.g., see bottom of https://docs.ray.io/en/master/auto_examples/plot_parameter_server.html

the actual runtime should be reported, or we should disable that message by setting `min_reported_time` to `inf`

**Comment by simon-mo** [comment]
can you submit a PR to set min_reported_time to inf? We are not running those code in the doc generation process. Thanks!

**Comment by sumanthratna** [comment]
> can you submit a PR to set min_reported_time to inf? We are not running those code in the doc generation process. Thanks!

sure, I'll do that now. FYI, setting [`$SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) will disable reporting runtimes (as an implementation detail in sphinx-gallery). @simon-mo if you think we should set the SOURCE_DATE_EPOCH env var then I can add that in the PR instead of just adding `min_reported_time`
