### ISSUE TITLE
[Tune] Trainables making copies of global variables?

### ISSUE THREAD

**Issue by jan-petrak** [ray-project/ray#14140]
What is the problem?

Trainable instances do not access global variables. It seems like they create their copies.

Reproduction (REQUIRED):

```
import time
import threading

from ray import tune

x = []

class MyTrainable(tune.Trainable):
    def step(self):  # This is called iteratively.
        global x
        while not x:
            print("x is still empty")
            time.sleep(1)
        return { "score" : 5 }

def add_to_x():
    global x
    while True:
        time.sleep(5)
        x.append(42)
        print("x has len: " + str(len(x)))
        time.sleep(2)

threading.Thread(target=add_to_x).start()

analysis = tune.run(
    MyTrainable,
    config={
        'a': tune.choice([1,2]),
    })
```

it produces an output like this:
(pid=8444) x is still empty
(pid=8444) x is still empty
x has len: 1
(pid=8444) x is still empty
(pid=8444) x is still empty
(pid=8444) x is still empty
(pid=8444) x is still empty
(pid=8444) x is still empty
(pid=8444) x is still empty
(pid=8444) x is still empty
x has len: 2
(pid=8444) x is still empty
(pid=8444) x is still empty

**Comment by jonas27** [comment]
@jan-petrak can I ask why you closed it again? I think it is probably the  expected behavior from ray tune, but how can we still store data in memory to be accessible after the runs?

**Comment by jan-petrak** [comment]
@jonas27 Not sure what you mean by "again", but I closed it because I realized Tune runs each trial in a new process. So, if we change the value of a global variable, it is changed only in that process (trial).

I guess, whatever data you wish to access after the runs need to be contained in the returned dictionary.

**Comment by jonas27** [comment]
Yeah, but u can actually run it as a single process for debugging or so with `ray.init(local_mode=True)`.
I got it solved using a remote class, see [here](https://stackoverflow.com/a/62768456/6640073)
Not sure why the there are so many function calls, the class was enough for me.
```
@ray.remote
class GlobalState:
    def __init__(self):
        self.bestScore = 0
        self.bestRun = []

    def set(self, val_roc_score, run):
        if self.bestScore < val_roc_score:
            print("overwrite best score")
            self.bestScore = val_roc_score
            self.bestRun = run
    
    def resetScore(self):
        self.bestScore, self.bestRun = 0, None
```
then 
```
analysis = tune.run(
        trainable,
        fail_fast=True,
        num_samples=50,
        scheduler=ASHAScheduler(metric="mean_accuracy", mode="max", reduction_factor=4, grace_period=2,),
        config=config)
    with open('best-config-' + cancer + '.txt', 'w') as f:
        print("Best config: ", analysis.get_best_config(metric="mean_accuracy", mode="max"), file=f)
    globalstate.set.remote(5,cancerType=cancer)
```
Something like that anyway...

**Comment by haoliangjiang** [comment]
> globalstate

Do you mind elaborating your solution a little bit more? I did not quite follow what your global variables are and how you call them in tune.run. Thanks in advance.

**Comment by haoliangjiang** [comment]
@jonas27

**Comment by jonas27** [comment]
@haoliangjiang I did it like this

@ray.remote
class GlobalState:
    def __init__(self):
        self.bestScore = 0
        self.bestRun = []

    #
    def set(self, val_roc_score, run):
        if self.bestScore < val_roc_score:
            self.bestScore = val_roc_score
            self.bestRun = run

    def resetScore(self):
        self.bestScore, self.bestRun = 0, None

    def get(self):
        return self.bestRun

**Comment by haoliangjiang** [comment]
@jonas27 Thanks. Really beautiful solution.
