### ISSUE TITLE
[rllib] Workload is not evenly distributed on a dual socket windows machine

### ISSUE THREAD

**Issue by Kai-AI** [ray-project/ray#14153]
Hi, I am using RLlib for RL control of rocket engines for my PhD research. I am using rllib locally on my Windows machine, which is a workstation with 2 seperate CPUs (Intel Xeon Gold 6140). The problem is that only 1 CPU is actually working and the second CPU is mostly in idle. I have already discussed the problem on discuss.ray.io and was asked to open an issue (https://discuss.ray.io/t/ray-on-a-local-machine-with-2-cpus/398/4).

Each CPU has 18 cores, so in total the workstation has 36 physical cores / 72 threads.

Now when I start ray with ray.init, ray.available_resources tells me that I have 72 cores.

> {'CPU': 72.0, 'memory': 1405.0, 'object_store_memory': 472.0, 'node:129.247.203.102': 1.0, 'GPU': 1.0}

When I spawn an RL training with Tune and "num_samples=72", all 72 jobs are started, but the workload is really oddly distributed across both CPUs. In my custom Rockent environment, this effect is even more pronounced and the second CPU is loaded only 15% on average .

Do you have any ideas what is going?

![core0](https://user-images.githubusercontent.com/53511975/108196295-3e672400-7119-11eb-90b0-a48ed6de6c2f.PNG)
![core1](https://user-images.githubusercontent.com/53511975/108196300-3f985100-7119-11eb-9f25-7165bee73dc8.PNG)
![task](https://user-images.githubusercontent.com/53511975/108196805-d49b4a00-7119-11eb-8533-4f07fc871381.PNG)

Minimum example:
>import ray
from ray import tune
from ray.rllib.agents.sac import DEFAULT_CONFIG
if __name__ == "__main__":
    config = DEFAULT_CONFIG.copy()
    config["env"] = "Pendulum-v0"  
    config["framework"] = "torch"
    config["num_workers"] = 1 
    config["num_envs_per_worker"] = 1
    config["evaluation_interval"] = 1
    config["evaluation_num_episodes"] = 10
    ray.init(include_dashboard=False) 
    tune.run("SAC", config=config, checkpoint_freq=50, checkpoint_at_end=True, num_samples=72)

**Comment by rkooo567** [comment]
cc @sven1977

**Comment by Kai-AI** [comment]
Any idea how I could further analyze or debug this problem?

**Comment by ilyaozornov** [comment]
I have a similar problem on our server with two CPUs. Just one is being used by Ray, even if I start ray twice via ray.init() from two different python processes. I guess that has something to do with Processor Groups in Windows Server 2019, but have no idea what to do about it.
![изображение](https://github.com/ray-project/ray/assets/12899286/09ef8ea0-9b02-4708-8c17-356ba462eb33)
