### ISSUE TITLE
add ability to check ray version

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1415]
Maybe something like `tensorflow.__git_version__`...to be able to use as sanity check in logs that correct version is used

**Comment by robertnishihara** [comment]
Great idea, we'll do this! I don't suppose you'd be interested in contributing this patch?

**Comment by DuaneNielsen** [comment]
ray --version from the command line would be helpful too

**Comment by edoakes** [comment]
We now have `ray.__commit__`. `ray --version` would be great.

**Comment by rkooo567** [comment]
This has been added. Try `ray --verison`
