### ISSUE TITLE
[Object Spilling] Object directory is not notified when spilled object is deleted

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#14168]
### What is the problem?

When a spilled object is deleted, the object directory (GCS-based or ownership-based) is not notified, meaning that the spilled URL and spilled node ID are never unset in the object directory. Given that we use the existence of those fields as a proxy for whether the object is currently spilled, we risk running into issues e.g. when an object is spilled, restored, and then evicted, where the pull manager might think that the object is still spilled and try to restore it.

**Comment by rkooo567** [comment]
I think this is more critical for OBOD case, so I will assign it to you @clarkzinzow

**Comment by ericl** [comment]
Discussed offline; this isn't needed since the spilled file is only ever deleted if the object reference is deleted itself.
