### ISSUE TITLE
[Core] RayTaskError serialization is broken

### ISSUE THREAD

**Issue by barakmich** [ray-project/ray#14172]
### What is the problem?

`ray.exceptions.RayTaskError` does some metaclass work that results in the inability to deserialize it.

This is easy to test by way of `ray.exceptions.RayError` -- a `RayTaskError` cannot always survive

```
r: RayTaskError
RayError.from_bytes(r.to_bytes())
```

The resulting error looks like the following when using the ray client:
```
  File "/usr/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 46, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ray/util/client/api.py", line 33, in get
    return self.worker.get(vals, timeout=timeout)
  File "/usr/lib/python3.6/site-packages/ray/util/client/worker.py", line 156, in get
    out = [self._get(x, timeout) for x in to_get]
  File "/usr/lib/python3.6/site-packages/ray/util/client/worker.py", line 156, in <listcomp>
    out = [self._get(x, timeout) for x in to_get]
  File "/usr/lib/python3.6/site-packages/ray/util/client/worker.py", line 168, in _get
    err = cloudpickle.loads(data.error)
TypeError: __init__() missing 6 required positional arguments: 'function_name', 'traceback_str', 'cause_cls', 'proctitle', 'pid', and 'ip'
```

This is, modulo the logging fixed in #14161, the root cause of #13842. It happens without the client.

### Reproduction (REQUIRED)

```python
import ray
from ray.exceptions import RayError
ray.init()

@ray.remote
def g():
    with open("/dev/asdf", "w") as f:
        f.write("HI")

v = g.remote()
# v is a ObjectRef to an exception
try:
  ray.get(v)
except RayError as r:
  print(RayError.from_bytes(r.to_bytes()))
```
The above should yield a TypeError while handling the original exception.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
@edoakes I vaguely remember you said you have something in the pipeline for this?

**Comment by edoakes** [comment]
I recently merged a PR that serializes the full remote exception for a `RayTaskError`, don't think it solves this problem
https://github.com/ray-project/ray/pull/14449

**Comment by richardliaw** [comment]
Marking as P1 due to critical user request (@yuduber).
