### ISSUE TITLE
[Java] Ray call java api doesn't support method overload

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#14186]
### What is the problem?
Ray java api use method reference(lambda) to reference a method which will be executed remotely and enforce type safety in compile-time. But when the referenced method is overloaded, the compiler will complain. This is because both ray call api(`io.ray.RayCall#task/io.ray.ActorCall#task`) and referenced methods are overloaded, neither side of the methods are determinate ahead, the compiler can't determinate the methods of any side. 
For static function call, this can be mitigated if the users add more type informations in code like:
![image](https://user-images.githubusercontent.com/12445254/108337652-4f469100-7210-11eb-88d9-26a792a5bbaa.png)

For actor task call, this can be mitigated too:
![image](https://user-images.githubusercontent.com/12445254/108465146-6b077100-72bc-11eb-83cc-284f3caa6a2f.png)

And neither the static method call or instance methods call can work when static methods are overlaoded with instance methods and the first parameter type is the same with actor class type which is uncommon:
![image](https://user-images.githubusercontent.com/12445254/108464797-c9801f80-72bb-11eb-9536-b999b804ed1c.png)

All those limits are exposed by the methods reference. The ray runtime does support method overload, but by the limitation of java language we can't reference overloaded method:
![image](https://user-images.githubusercontent.com/12445254/108452573-b2353800-72a3-11eb-978e-cb68f300fe41.png)
`Reference to an instance method of an arbitrary object of a particular type` doesn't support `overload`.

### Reproduction (REQUIRED)
![image](https://user-images.githubusercontent.com/12445254/108337692-5a99bc80-7210-11eb-9623-12adf57541d2.png)
![image](https://user-images.githubusercontent.com/12445254/108337720-5ec5da00-7210-11eb-856f-c8d517509d3d.png)

### Solution
* For both normal task call(static function call) and actor task call(instance function call), method overload can be mitigated if the users add more type informations. When static methods are overlaoded with instance methods and the first parameter type is the same with actor class type which is uncommon, this solution may not work. But since it's uncommon, it's OK we dones't support this case.

* Both those call can be resolved by adding a non-compile-time type-safety task call interface for overloaded methods and put method resolution and linking into runtime when the function starts to execute. The method resolution will be based on the arguments number and types of passed. API example: `<R> ActorTaskCaller<R> task(String methodName, Object... args)`. The cons are we lose type-safety and have some performance cost because the method  resolution are put into runtime instead of compile-time.

### Reference
1. https://dzone.com/articles/java-8s-method-references-put-further-restrictions
2. https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html
- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by raulchen** [comment]
An alternative solution is to support lambdas. So users can work around overload methods by wrapping them with lambdas. 
E.g.
```java
actor.task((actor) -> actor.hello(1));  // the argument of the lambda must be the actor class.
actor.task((actor) -> actor.hello("1"))
```
The advantage is that we can still preserve type safety.

**Comment by chaokunyang** [comment]
> An alternative solution is to support lambdas. So users can work around overload methods by wrapping them with lambdas.
> E.g.
> 
> ```java
> actor.task((actor) -> actor.hello(1));  // the argument of the lambda must be the actor class.
> actor.task((actor) -> actor.hello("1"))
> ```
> 
> The advantage is that we can still preserve type safety.

lambda is more complicated. Method reference doesn't contain state ,this is why we can convert method reference to function descriptor. But lambda can captures outer variables and state, which is stateful, so we can't convert lambda to function descriptor. We may need to use a common function descriptor and serialize lambda and arguments instead
