### ISSUE TITLE
[dask-on-ray] Add better support for progress reporting

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#14216]
### Describe your feature request

Users often wish to monitor the progress of their Dask tasks (e.g. via a progress bar) as their computation unfolds. Although this is currently possible using Dask-on-Ray callbacks and `ray.wait()`, since this is a common use case, we should make this easier for users. Dask [has a first-class `ProgressBar` callback](https://docs.dask.org/en/latest/diagnostics-local.html#progress-bar), and we should too. Exposing it as a callback seems like the right API.

### Examples

```python
with RayProgressBar():
    dask.compute(some_dask_object)
```

### Implementation

Although we can implement a progress bar using `ray.wait()` on top of the existing `ray.get()` that's done within the Dask-on-Ray scheduler, it would be more efficient and more generically useful to change the Dask-on-Ray scheduler's `ray.get()` to a `ray.wait()`, while providing convenient hooks for callbacks. This will also make supporting things like dropping task errors (#14215) easier.

**Comment by clarkzinzow** [comment]
@rkooo567 I'm assigning you since this is in your sprint.

**Comment by clarkzinzow** [comment]
@rkooo567 Should we close this based on the progress bar that you added?

**Comment by vmagdin** [comment]
What's the best way to monitor progress in Dask-on-Ray? I am using Dask's ProgressBar, but it's not super informative because it gets to 100% quickly, while the underlying computation keeps going.

**Comment by swyatt7** [comment]
> What's the best way to monitor progress in Dask-on-Ray? I am using Dask's ProgressBar, but it's not super informative because it gets to 100% quickly, while the underlying computation keeps going.

I am also seeing this issue. 

There doesn't seem to be support for `ray_tqdm`, `tqdm.dask.TqdmCallback`, or `dask.diagnostics.ProgressBar` when trying to use `dask_on_ray`. 

I think the reason that the `tqdm.dask.TqdmCallback` and `dask.diagnostics.ProgressBar` don't inherently work is in the Ray-specific callback abstraction for `finish` is "executed after all Ray tasks of been submitted, not executed" which is noted [here](https://docs.ray.io/en/latest/ray-more-libs/dask-on-ray.html#callbacks):

> The existing Dask scheduler callbacks (`start, start_state, pretask, posttask, finish`) are also available, which can be used to introspect the Dask task to Ray task conversion process, but note that the `pretask` and `posttask` hooks are executed before and after the Ray task is submitted, not executed, and **that `finish` is executed after all Ray tasks have been submitted, not executed.**

Which makes sense that the progress bars goes to 100%, even though it is still being executed. 

I think what you might have to do is create your own context manager tqdm object, that abstracts `RayDaskCallback._ray_pretask()` and `RayDaskCallback._ray_posttask()` that updates a tqdm progress.
