### ISSUE TITLE
How to monitor memory usage in ray?

### ISSUE THREAD

**Issue by ali3assi** [ray-project/ray#14214]
I tried to monitor my hyperparamters ray tune based solution:
1- Can I monitor the memory usage, CPU, GPU etc?
2- I follow https://docs.ray.io/en/master/ray-metrics.html as suggested:
So when I run localhost:8080 I see the dashboard but noting inside. Indeed, if we go to status menue and select target option we can see:
**Endpoint:** [http://localhost:8080/metrics](http://laptop-6o4h5m9s:8080/metrics) 
**STATE:** DOWN
**LABELS:** instance="localhost:8080" job="prometheus"
...
**ERROR:** Get "http://localhost:8080/metrics": dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

similarly, when I run my code, **I can see anything my console**.

### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
What do you mean by `So when I run localhost:8080 I see the dashboard but noting inside`? If you follow the instruction, 8080 should have a prometheus endpoint (not a dashboard), and the dashboard should be bound to 9090

**Comment by ali3assi** [comment]
@rkooo567  I mean when I type in the browser localhost:8080

**Comment by rkooo567** [comment]
Are you using VPN? It is probably just a network issue (looks like 9090 cannot access localhost:8080)?

Also from 8080, the metrics should start displaying every 10 second. Can you also give me the screenshot of it?

**Comment by ali3assi** [comment]
![image](https://user-images.githubusercontent.com/16214827/108554631-5a59f980-72c2-11eb-9534-cac976b64cbb.png)

**Comment by rkooo567** [comment]
8265: Dashboard
8080: Prometheus endpoint (the endpoint that prometheus server scrapes to obtain metrics from ray) https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-itself
9090: Prometheus server

**Comment by rkooo567** [comment]
ah are you using windows?

**Comment by rkooo567** [comment]
I think dashboard is not supported on Windows, and the monitoring information is exposed as a part of dashboard. I think that's the root cause..
