### ISSUE TITLE
[Ownership-based Object Directory] Object location subscribers aren't properly notified when reference is freed

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#14213]
### What is the problem?

When a reference is freed, all future object location removal RPCs to the core worker will error with object not found, which the OBOD will interpret as a no-op. This means that after a reference is freed, no more updates will be pushed to the location subscribers. In order to match the current GCS-based object directory's semantics, we should push a final empty location update when a reference is freed.

**Comment by ericl** [comment]
Do you have an example where there are still subscribers when a reference is freed? Shouldn't the reference be retained until there are no possible subscribers?
