### ISSUE TITLE
[dask-on-ray] Memory efficiency: Dask arrays should always be passed by reference only

### ISSUE THREAD

**Issue by Hoeze** [ray-project/ray#14227]
When passing a (persisted) dask array with np.ndarray chunks to some ray remote function, the whole dask array does get serialized.
I created a notebook showing the consequence:
https://gist.github.com/Hoeze/26430689bb3252ebb71b9ae08242d09a

Instead, the np.ndarray chunks should be put to the object store and the dask array should only contain references to the object store.

This could be solved by different ways, e.g.
- some `ray_put_dask` function that converts every chunk to a delayed `ray.get()` method
- change `dask.persist()` to return chunk references instead of np.ndarray-typed chunks

@rkooo567 @clarkzinzow

**Comment by rkooo567** [comment]
Thanks for the awesome analysis in the gist @Hoeze. @clarkzinzow will take a look at this next week!

**Comment by clarkzinzow** [comment]
@rkooo567 **Some background:** The semantics of Dask Distributed's `Client.persist()` and plain Dask's `dask.persist()` are a bit different: the former [triggers computation on the Dask Distributed cluster and inlines references to the corresponding futures in the Dask collection](https://distributed.dask.org/en/latest/api.html#distributed.Client.persist), while the latter [eagerly computes the Dask collection and brings the results into memory](https://github.com/dask/dask/blob/ad01acc14088d03127dfec4f881cce959f3ac4d9/dask/base.py#L674-L678). If you use the latter and a Dask Distributed client exists and is connected to the cluster, the [`Client.persist()` semantics will take over](https://github.com/dask/dask/blob/ad01acc14088d03127dfec4f881cce959f3ac4d9/dask/base.py#L744-L759). Unfortunately, no such hooks exist for non-Dask Distributed schedulers, so Dask-on-Ray won't be able to offer the same behavior for `dask.persist()`.

@Hoeze The closest we could get is adding a `ray_no_get`/`ray_futures`/`ray_persist` kwarg to `ray_dask_get`, which would cause a Dask collection full of Ray objects to be returned.  The latter would be used like
```python
dask.config.set(scheduler=ray_dask_get)
df = # Some Dask DataFrame with column "foo"
df = df.persist(ray_persist=True)
df.foo.max().compute()
```
Having to remember to pass `ray_persist=True` is annoying, and maybe having a separate `ray_persist` function would be better. Which of these options would work better for you?

**Comment by Hoeze** [comment]
@clarkzinzow If you say it is possible to overwrite `df.persist()`, would it then be possible to have a global `ray_persist=True` as default option?
In general, I use `df.persist()` for two reasons:
- I want to keep the chunks for parallel processing
- I want to load pre-load chunks for fast reading

In both cases, it does not make sense to use `ray_persist=False` since I can just use `df.compute()` if I need a materialized `np.ndarray` object.

If this is not possible, I'd prefer an explicit `ray.dask.persist()` function :)

**Comment by clarkzinzow** [comment]
The core issue is that `ray_dask_get` won't be able to tell if it's being called by `dask.compute()` or `dask.persist()`, the call will look exactly the same `ray_dask_get` in either case, which is why a user-supplied `ray_persist=True` flag would be necessary. And I agree that an explicit function would be better! I think that's the best option for now.

**Comment by rkooo567** [comment]
+1 for explicit function. I can imagine this could be also useful for regular .compute output? Especially when we’d like to pass dask output to other ray task or sth

**Comment by clarkzinzow** [comment]
@rkooo567 We'd want to maintain the expected `.compute()` semantics that Dask provides, where `.compute()` returns a concrete Pandas DataFrame or NumPy Ndarray in memory. Dask itself doesn't expose a `.compute()` flag for turning on that inlined future references behavior, since that's what `.persist()` is for. If anything downstream from Dask such as a Ray task or a Dask --> MLDataset connector wants to work directly with object store references, they should have to use `.persist()` or our own `ray_persist()`, which I think is fine.

**Comment by rkooo567** [comment]
I see. So users can use `ray_persist(df)` to get refs and `df.compute` to get the result at a centralized place right? This sounds good to me!

**Comment by rkooo567** [comment]
Hey @Hoeze Can you try this out and let us know how ti works?

**Comment by Hoeze** [comment]
I tried it and it works great! Thank you @rkooo567 and @clarkzinzow :smile: 

One thing that one has to be aware of, though, is that using object_ref's in Dask arrays only work when using `.compute(scheduler=ray_dask_get)`. When forgetting to set this option, one gets a strange error:

```python
import ray
from ray.util.dask import ray_dask_get
import dask.array
import numpy as np

ray.init()

x = dask.array.from_array(np.ones(10))
x = x.rechunk(3, 3)
x = x.persist(scheduler=ray_dask_get)

print("> x.compute():")
print(x.compute())
print("> x[5].compute(scheduler=ray_dask_get):")
print(x[5].compute(scheduler=ray_dask_get))
print("> x[5].compute():")
print(x[5].compute())
```

<details>

```python
> x.compute():
[ObjectRef(c1bc039a3735bcd4ffffffffffffffffffffffff0100000001000000)
 ObjectRef(7b3a1cd820ede810ffffffffffffffffffffffff0100000001000000)
 ObjectRef(9244b8758d3bc0baffffffffffffffffffffffff0100000001000000)
 ObjectRef(f280fff700a52401ffffffffffffffffffffffff0100000001000000)]
> x[5].compute(scheduler=ray_dask_get):
1.0
> x[5].compute():
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-736ff49ae2ff> in <module>
      4 print(x[5].compute(scheduler=ray_dask_get))
      5 print("> x[5].compute():")
----> 6 print(x[5].compute())

/opt/modules/anaconda/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    277         dask.base.compute
    278         """
--> 279         (result,) = compute(self, traverse=False, **kwargs)
    280         return result
    281 

/opt/modules/anaconda/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    559         postcomputes.append(x.__dask_postcompute__())
    560 
--> 561     results = schedule(dsk, keys, **kwargs)
    562     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    563 

/opt/modules/anaconda/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     82         get_id=_thread_get_id,
     83         pack_exception=pack_exception,
---> 84         **kwargs
     85     )
     86 

/opt/modules/anaconda/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    485                         _execute_task(task, data)  # Re-execute locally
    486                     else:
--> 487                         raise_exception(exc, tb)
    488                 res, worker_id = loads(res_info)
    489                 state["cache"][key] = res

/opt/modules/anaconda/lib/python3.7/site-packages/dask/local.py in reraise(exc, tb)
    315     if exc.__traceback__ is not tb:
    316         raise exc.with_traceback(tb)
--> 317     raise exc
    318 
    319 

/opt/modules/anaconda/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

/opt/modules/anaconda/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

TypeError: 'ray._raylet.ObjectRef' object is not subscriptable
```

</details>

A possible solution to this would be to wrap every `object_ref` with `dask.delayed(ray.get)(object_ref)`.
However, I guess this would imply quite some unnecessary overhead...

**Comment by clarkzinzow** [comment]
@Hoeze I'm happy to hear that it's working pretty well for you! And that is quite an unfortunate failure mode, I know that Dask Distributed gets around that by having dedicated logic in `.compute()` to detect if a Dask Distributed client has been instantiated, at which point it will use that as the scheduler. And unfortunately, I think that wrapping every object ref would be an untenable performance hit, and possibly break the future inlining logic.

I was planning on encouraging people to use the `dask.config.set(scheduler=ray_dask_get)` pattern for this reason (either set globally or as a context manager) so you don't have to always remember to pass that kwarg, would that work for you?

**Comment by Hoeze** [comment]
> I was planning on encouraging people to use the `dask.config.set(scheduler=ray_dask_get)` pattern for this reason (either set globally or as a context manager) so you don't have to always remember to pass that kwarg, would that work for you?

Yes, that's what I do now.
You need to run `dask.config.set()` on all workers. Otherwise, you run into this problem when calling `.compute()` in some remote function as well.

**Comment by rkooo567** [comment]
We have an internal api to run the function on every worker. Maybe we should just support ray.util.setup_dask_on_ray() which sets the config on all workers + apply our custom shuffle optimization
