### ISSUE TITLE
[rllib] access policy model in env step function

### ISSUE THREAD

**Issue by adriendoerig** [ray-project/ray#14247]
In RLlib, I would like to have access to the policy model in the environment step function, to print some debugging information at each timestep. I would also need to make the step function depend on the state of a layer in my policy model. Is this possible? 

I couldn't find a way to get any information about the model, except for the output action of course, in the environment. Currently, I am passing tensors I would like to print concatenated with the action, but this is quite cumbersome. Thanks!

**Comment by hamta** [comment]
> In RLlib, I would like to have access to the policy model in the environment step function, to print some debugging information at each timestep. I would also need to make the step function depend on the state of a layer in my policy model. Is this possible?
> 
> I couldn't find a way to get any information about the model, except for the output action of course, in the environment. Currently, I am passing tensors I would like to print concatenated with the action, but this is quite cumbersome. Thanks!

@adriendoerig  Did you find any solution for your question?
