### ISSUE TITLE
[rllib] MultiDiscrete action space with dims > 1 throws error

### ISSUE THREAD

**Issue by Bam4d** [ray-project/ray#14249]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Rllib Version: 1.2.0
Python Version: 3.8
torch Version: 1.7.0
OS: ubuntu 20.04

In `ray/rllib/models/catalog.py` the total number of elements is calculated with `int(sum(action_space.nvec)`. Which throws an error if the Action space is more than 1 dimensional, as sum() here only does a 1d sum.

Can possibly be fixed with np.sum() instead of the native sum() function.

### Workaround

Currently rolling my own custom action distribution

### Reproduction

```
import os
import sys

import numpy as np
import ray
from gym.spaces import Box, MultiDiscrete
from ray import tune
from ray.rllib.agents.impala import ImpalaTrainer


class MultiDiscrete2DTestEnv():

    def __init__(self, env_config):
        self.observation_space = Box(0, 1, shape=(10, 10, 10), dtype=np.float)
        
        self.action_space = MultiDiscrete([
            [10, 10, 10],
            [10, 10, 10],
            [10, 10, 10]]
        )


if __name__ == '__main__':
    sep = os.pathsep
    os.environ['PYTHONPATH'] = sep.join(sys.path)

    ray.init(num_gpus=1, local_mode=True)

    env_name = 'ray-reproduce-test'

    config = {
        'framework': 'torch',
        'num_workers': 1,

        'num_envs_per_worker': 1,
        'env': MultiDiscrete2DTestEnv,
    }

    stop = {
        # 'training_iteration': 100,
        'timesteps_total': 200000,
    }

    result = tune.run(ImpalaTrainer, config=config, stop=stop)
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Bam4d** [comment]
This might actually be significantly more complicated, because many other places in the codebase assume that multidiscrete spaces are not 2D.

**Comment by sven1977** [comment]
Thanks for filing this issue @Bam4d !

As a workaround, you could also just do this, I think:
```
action_space = MultiDiscrete([10, 10, 10, 10, 10, 10, 10, 10, 10]). # <- flatten
# Use a gym ActionWrapper to translate (reshape).
action = action.reshape([3, 3])
```

Something along those lines.

**Comment by Bam4d** [comment]
Yes my current approach to this is to flatten everything and reshape in the env wrapper. Thanks
