### ISSUE TITLE
[core] Turn on "put_small_objects_in_memory_store" feature 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#14258]
### What is the problem?

This feature has been sitting around and off for a while, but seems non-trivial to turn on. See #13621

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jjyao** [comment]
This is on by default now.
