### ISSUE TITLE
[core] How to obtain memory occupied by object ref?

### ISSUE THREAD

**Issue by Hoeze** [ray-project/ray#14250]
Hi, is there an easy way to get the memory occupied by some object ref?
E.g. `ray.sizeof(ray.put(object))`

**Comment by stephanie-wang** [comment]
There's no way to do this programmatically, but it would be an easy enough feature to add. Since ObjectRefs are also futures, we would have to return None or something similar if the size is unavailable, though.

**Comment by rkooo567** [comment]
Hey @Hoeze Can you also explain the use case here? Are you using it for debugging your Dask on Ray workload?

**Comment by Hoeze** [comment]
I tried to find out why my cross-validation method caused 30GB increase of memory usage.
My first guess was that the returned lightgbm models are large, so I wanted to check this.

Since ray has to track object sizes anyway, I was just curious whether it could tell me the object size.
For now, I `joblib.dump`ed it to disk (the resulting file occupies then 4.7GB).

**Comment by rkooo567** [comment]
For now, you can achieve this using ray memory command (it is not programmable api tho). I can take a look if there’s a good way to support this.

**Comment by mlguruz** [comment]
> @jmoralez I think right now you can obtain the information using `ray.experimental.get_object_locations`. Note that this is an experimental API, and the semantics could be changed.
> 
> ```python
> In [3]: @ray.remote 
>    ...: def f(): 
>    ...:     return 4 
>    ...:                                                                                                               
> 
> In [4]: r = f.remote()                                                                                                
> 
> In [6]: ray.experimental.get_object_locations([r])                                                                    
> Out[6]: 
> {ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000001000000): {'node_ids': [],
>   'object_size': 15}}
> ```

I'm actually running into this error running the example:
![image](https://user-images.githubusercontent.com/24363659/217636555-09baf79b-4723-4c42-892b-72e52c01a740.png)

my ray version is 2.2.0

**Comment by rkooo567** [comment]
Hmm did you call ray.shutdown?

**Comment by mlguruz** [comment]
> Hmm did you call ray.shutdown?

No This is exactly what I run:

![image](https://user-images.githubusercontent.com/24363659/217642518-f0b759a4-fe81-4441-9536-b4df76622a40.png)


`ray://10.28.49.186:10001` <- this is the head node ip of AWS EC2 cluster
```

**Comment by rkooo567** [comment]
Ah, I think this feature is probably not supported by ray client https://docs.ray.io/en/master/cluster/running-applications/job-submission/ray-client.html. 

We may fix this issue by ray 2.4.

**Comment by rkooo567** [comment]
Meanwhile I am curious if it is a viable option to use ray job submission (https://docs.ray.io/en/master/cluster/running-applications/job-submission/index.html) instead? Basically, don't use 10001 port

**Comment by mlguruz** [comment]
> Meanwhile I am curious if it is a viable option to use ray job submission (https://docs.ray.io/en/master/cluster/running-applications/job-submission/index.html) instead? Basically, don't use 10001 port

haha I was literally just looking at Ray Job API :) 

I was always doing `ray.init(xxx)` in my local/launcher python script, to submit workload to cluster. Is Ray Job the more recommended way of doing that?

**Comment by rkooo567** [comment]
Yeah. We don't recommend ray client unless it is necessary as it is innately less performant. Some of features may not be there too. 

If you execute your script locally, you can either do `ray job submit -- <python script.py>` (use `ray.init("auto") inside`). You can also just run <python script.py> directly with `ray.init("auto")` in your script. If you use 10001 port, that will use ray client.

**Comment by mlguruz** [comment]
> 

Thank you! 

Btw I've tried the python sdk, and below is the only way I can connect to remote ray cluster

```
# If using a remote cluster, replace 127.0.0.1 with the head node's IP address.
client = JobSubmissionClient("ray://10.28.49.149:10001")
```

**Comment by rkooo567** [comment]
cc @architkulkarni is this the right way to connect to a remote cluster?

**Comment by architkulkarni** [comment]
`client = JobSubmissionClient("ray://10.28.49.149:10001")` will work, but it's a convenience feature mainly to support people who have `RAY_ADDRESS` set to `"ray://10.28.49.149:10001"` because they use Ray Client a lot and don't want to unset or switch it every time they want to use Ray Jobs.  

But under the hood, when Ray Job API receives a Ray Client address, it connects with Ray Client to retrieve the dashboard URL (`"http://10.28.49.149:8265"`) and then uses the dashboard URL for API requests.  So `client = JobSubmissionClient("http://10.28.49.149:8265")` is a better approach, and I would expect it to work.  Could it be that the dashboard is running on port `8266` or some other port?  Given that Ray Client is working, you can check the dashboard URl with 
```
    with ray.init(address="ray://10.28.49.149:10001") as client_context:
        print(client_context.dashboard_url)
```

**Comment by mlguruz** [comment]
> `client = JobSubmissionClient("ray://10.28.49.149:10001")` will work, but it's a convenience feature mainly to support people who have `RAY_ADDRESS` set to `"ray://10.28.49.149:10001"` because they use Ray Client a lot and don't want to unset or switch it every time they want to use Ray Jobs.
> 
> But under the hood, when Ray Job API receives a Ray Client address, it connects with Ray Client to retrieve the dashboard URL (`"http://10.28.49.149:8265"`) and then uses the dashboard URL for API requests. So `client = JobSubmissionClient("http://10.28.49.149:8265")` is a better approach, and I would expect it to work. Could it be that the dashboard is running on port `8266` or some other port? Given that Ray Client is working, you can check the dashboard URl with
> 
> ```
>     with ray.init(address="ray://10.28.49.149:10001") as client_context:
>         print(client_context.dashboard_url)
> ```

thank you - let me try that!

**Comment by scv119** [comment]
looks `ray.experimental.get_object_locations` get the job done.
