### ISSUE TITLE
Ensure dashboard starts on the desired port

### ISSUE THREAD

**Issue by MattEWeber** [ray-project/ray#14257]
### What is the problem?
We need a guarantee that the ray dashboard will get started on port 8265 when `ray stop` and `ray start` are called programmatically in quick succession.

*Ray version and other system information (Python version, TensorFlow version, OS):*

In Ray 1.2.0 (Python 3.7) using `ray stop --force`, fixes the problem the majority of the time but we're still seeing it get started on the undesired port about 1/2000 tries.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Courtesy of @ijrsvt 
```
import subprocess
iteration = 0
while True:
    output = subprocess.run("ray stop --force; ray start --head > /dev/null", shell=True, capture_output=True)
    assert "8265" in output.stderr.decode()
    print("Started on 8265", " -- Iteration -- ", iteration, ")
    iteration += 1
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
discussed offline, @edoakes suggested that one path forward would be the Ray dashboard keep trying to find to the specified port.

**Comment by MattEWeber** [comment]
The workaround we were using was a script that delayed running ray start until port 8265 was open. So yeah, I think doing something like that internally to Ray is the way to go!

**Comment by ijrsvt** [comment]
@simon-mo  What if a user is running ray multiple times, should we still support the 'incrementing' behavior? 

(I mean this could be solved with trying to bind to 8265 for ~5 seconds, and then beginning to count).

**Comment by edoakes** [comment]
@ijrsvt we can leave the existing behavior if the port is not explicitly specified by the user

**Comment by ijrsvt** [comment]
@edoakes Sounds good, the one edge case that I personally find weird is that if I specify `--dashboard-port=8265`, the current behavior is to still increment (this is only because it looks like the code doesn't differentiate from a user-provided value of 8265 and the default value of 8265).

**Comment by simon-mo** [comment]
Actually, I think we should do the following:
- Only do the incrementing behavior for `ray.init()` use case.
- `ray start --head` should be equivalent to `ray start --head --dashboard-port 8265` because it doesn't make sense to run multiple `ray start --head` on the same node. If the port is not available, ray start should fail. 
- Set SO_REUSEPORT option to allow rapid `ray stop; ray start --head` to succeed.

Thoughts? @ijrsvt @edoakes

**Comment by MattEWeber** [comment]
I assumed the reason why incrementing was the default behavior for `ray start` previously was so you could consistently start up the dashboard even if some other non-Ray process was using port 8265. Wouldn't we lose that?

**Comment by edoakes** [comment]
`ray start` is only really used for "production" deployments / from within cluster managers. In both of these cases you want a fixed port, not for it to randomly pick a new one, so I think it's fine to only support this from `ray.init()`. Honestly, the automatic port selection might not even be desirable for `ray.init()` (I personally always assume it's running on :8265).

@simon-mo this solution sounds good to me, but what will happen if we use `SO_REUSEPORT` and another process is already using the port? How do we differentiate between an old dashboard using it and a different process?

**Comment by ijrsvt** [comment]
@simon-mo Sounds good to me.

@edoakes I'm on the fence about automatic port selection. It is simultaneously annoying (* tend to just assume it is going to be 8265) and useful (in a more development context when I might have several conda envs).

**Comment by simon-mo** [comment]
We would assume only Ray dashboard would occupy the port and set `SO_REUSEPORT` and that process would exit soon. If there are another non-ray process:
- if that process have set `SO_REUSEPORT`, kernel should load balance between two socket in linux, and send all traffic to the first process bind to that port in macOS
- if that process have not set `SO_REUSEPORT`, our subsequent bind will fail. 

Overall I think setting SO_REUSEPORT would be a good addition, the chance that other non-ray process occupy the same port AND set SO_REUSPORT is low.

**Comment by fyrestone** [comment]
Maybe we can set the default value of dashboard port to `None` (or 0).

- If the dashboard port is not None,
  - then auto select a port from [8265, 8265 + 10], failed if no available port found.
- else,
  - use the dashboard port to start dashboard, failed if the port is occupied.
