### ISSUE TITLE
[rllib] I cannot debug into env step function while using register_env

### ISSUE THREAD

**Issue by itmorn** [ray-project/ray#14276]
`config["env"] = MyEnv`
I found it possible to debug into env step function using the code style above.

But now I have a complex environment as follows and I don't know how to convert it to the above way because I want to debug into the env step function.
`register_env("tictactoe",lambda config: PettingZooEnv(env_creator()))`

**Comment by sven1977** [comment]
Interesting. Did you try setting `local_mode=True` in your call to `ray.init(local_mode=True)`?

**Comment by sven1977** [comment]
@itmorn ^^

**Comment by itmorn** [comment]
thanks
