### ISSUE TITLE
Add missing dependencies for ray.tune/rllib to wheel

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1428]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.3.0
- **Python version**: 2.7.12
- **Exact command to reproduce**: Create a new virtualenv, install ray with pip, then `import ray.tune`.

### Describe the problem
ray.tune depends on, through rllib:

* OpenAI Gym (`gym`)
* OpenCV (`cv2`)
* scipy

but they are not specified as dependencies of the wheel on PyPI.

**Comment by richardliaw** [comment]
Also related https://github.com/ray-project/ray/issues/1364 and #1144 (along others). tl;dr Tune should not depend on RLlib 

@ericl thoughts on post above?

**Comment by richardliaw** [comment]
Fixed in #1454!
