### ISSUE TITLE
Ray printing "(raylet) cut: write error: Broken pipe" constantly

### ISSUE THREAD

**Issue by cbravo93** [ray-project/ray#14305]
Hi!

When using ray, I constantly get this message from raylet (every 1-2 secs it is printed):

```
(raylet) cut: write error: Broken pipe
```

This is the output of raylet.out (the warning part is repeated all over again)

```
[2021-02-24 13:49:00,424 I 29643 29643] io_service_pool.cc:36: IOServicePool is running with 1 io_service.
[2021-02-24 13:49:00,432 I 29643 29643] store_runner.cc:29: Allowing the Plasma store to use up to 190.873GB of memory.
[2021-02-24 13:49:00,432 I 29643 29643] store_runner.cc:42: Starting object store with directory /dev/shm and huge page support disabled
[2021-02-24 13:49:00,433 I 29643 29643] grpc_server.cc:75: ObjectManager server started, listening on port 32793.
[2021-02-24 13:49:00,436 I 29643 29643] node_manager.cc:189: Initializing NodeManager with ID 487e06036c0f9b3f34e14ef02d8feca6f064cede136a2e2fb44509dd
[2021-02-24 13:49:00,436 I 29643 29643] grpc_server.cc:75: NodeManager server started, listening on port 43854.
[2021-02-24 13:49:00,441 I 29643 29663] agent_manager.cc:76: Monitor agent process with pid 29662, register timeout 30000ms.
[2021-02-24 13:49:00,442 I 29643 29643] raylet.cc:133: Raylet of id, 487e06036c0f9b3f34e14ef02d8feca6f064cede136a2e2fb44509dd started. Raylet consists of node_manager and object_manager. node_manager address: 10.118.230.160:43854 object_manager address: 10.118.230.160:32793 hostname: 10.118.230.160
[2021-02-24 13:49:00,444 I 29643 29643] service_based_accessor.cc:559: Received notification for node id = 487e06036c0f9b3f34e14ef02d8feca6f064cede136a2e2fb44509dd, IsAlive = 1
[2021-02-24 13:49:02,918 I 29643 29653] store.cc:226: Object store current usage 8e-09 / 190.873 GB.
[2021-02-24 13:49:10,583 W 29643 29649] metric_exporter.cc:206: Export metrics to agent failed: IOError: 12: Method not found!. This won't affect Ray, but you can lose metrics from the cluster.
[2021-02-24 13:49:10,584 I 29643 29643] agent_manager.cc:32: HandleRegisterAgent, ip: 10.118.230.160, port: 48136, pid: 29662

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Linked to libnvidia-ml library at wrong path : /usr/lib64/libnvidia-ml.so.1
```

And in raylet.err is just the error all over again

```
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
cut: write error: Broken pipe
```

The code continues running though. It would happen anytime I use it, even with the simplest example. Any idea on how to avoid this? This is happening with Python 3.7.4 and ray 1.2.0 and 2.0.0. I have used ray 0.8.6 before without issues.

Thanks!

**Comment by rkooo567** [comment]
Can you give me the simple example you said this error would occur? Also, what's the OS?

**Comment by cbravo93** [comment]
Hi @richardliaw !

*Example*
It would happen any time I try to run ray (if the task takes more than a few seconds). I am running on a single node. This is a toy example:

```
import ray

@ray.remote
def test(i):
    return i

ray.init(num_cpus=5)
x=ray.get([test.remote(i) for i in range(5*(10**5))])
ray.shutdown()
```

And this is what happens:

Jupyter notebooks
![image](https://user-images.githubusercontent.com/19205518/109133709-958e7980-7755-11eb-9dea-d2d3ac5907a9.png)

Console
![image](https://user-images.githubusercontent.com/19205518/109133822-adfe9400-7755-11eb-8dfe-98be0b0e61a9.png)

The code itself runs with no issues, it just keeps printing that message.

*OS*

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Cheers!

C

**Comment by cbravo93** [comment]
Actually, there is no need to run anything simply doing:

```
import ray
ray.init(num_cpus=5)
```

And waiting a couple seconds prompts the messages already:

![image](https://user-images.githubusercontent.com/19205518/109135077-fbc7cc00-7756-11eb-82cb-ae50e671d308.png)

**Comment by richardliaw** [comment]
Can you provide the files of `/tmp/ray/session_latest/logs`

**Comment by cbravo93** [comment]
Here they go :)

[logs.zip](https://github.com/ray-project/ray/files/6051609/logs.zip)

**Comment by richardliaw** [comment]
Unfortunately, there's not much info to go off of here... it seems like there's some `cut` command failing somewhere

**Comment by rkooo567** [comment]
I've seen lots of this error from the raylet logs. Do you know what this means? 

```
You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2021-02-26 19:08:33,294 I 36755 36755] node_manager.cc:1263: Driver (pid=36552) is disconnected. job_id: 01000000
Linked to libnvidia-ml library at wrong path : /usr/lib64/libnvidia-ml.so.1
```

**Comment by rkooo567** [comment]
Also, can you try starting ray with

`ray start --head` and connect to it using `ray.init(address='auto')` and see if the same kind of issue happens, or it behaves differently?

**Comment by cbravo93** [comment]
Hi!

Ray seems to not be found from CLI (do I need to add something before ray start?). About the error, I also noticed it, it also appears just running ray.init(). 

The "solution" I found for this issue was to keep raylet quiet by:

```
_stderr = sys.stderr                                                         
null = open(os.devnull,'wb') 
ray.init(num_cpus=n_cpu, **kwargs)
sys.stderr = null
#Run your process here
ray.shutdown()
sys.stderr = sys.__stderr__
```

It still prints relevant errors from the process I am running, while making my notebooks look much nicer without the infinite errors :)

Of course this does not explain the issue itself. Other information that may be relevant, this error didnt happen in 0.8.6, in 1.2 the error is printed almost every second, in the ray2.0 (nightly release from a few weeks, Python 3.7) still appears but considerably less frequently.

Thanks for checking it!

**Comment by hauntsaninja** [comment]
@cbravo93 I also ran into this and I think I found a workaround in https://github.com/ray-project/ray/pull/21686
Could you confirm what error `python -c 'import pynvml; pynvml.nvmlInit()'` gives you?
