### ISSUE TITLE
[OBOD] Dask on Ray 100GB shuffle is crashed with the heartbeat error

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14324]
### What is the problem?

When the OBOD is turned on a single node 100GB dask on ray shuffle didn't finish with the heartbeat missing error from the raylet. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @clarkzinzow @ericl

**Comment by rkooo567** [comment]
@clarkzinzow I will assign you here.

**Comment by clarkzinzow** [comment]
Good news here. After moving the raylet heartbeat to a different thread, the 100GB Dask-on-Ray shuffle completes without issue. We should probably rescope this to debugging OBOD-caused raylet stress, with a possibly visible side effect being delayed resource reports.

**Comment by ericl** [comment]
Closing since this is very stale, let's make a new issue with more details as needed if we encounter this during tests again.
