### ISSUE TITLE
ray memory --stats-only should not fetch all reference table info 

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#14325]
If you pass --stats-only, the RPC should skip returning the extra info, otherwise sometimes you get:

	details = "Sent message larger than max (124329006 vs. 104857600)"
	debug_error_string = "{"created":"@1614208992.390378279","description":"Error received from peer ipv4:192.168.14.248:58804","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Sent message larger than max (124329006 vs. 104857600)","grpc_status":8}"

**Comment by rkooo567** [comment]
I think this will be fixed by https://github.com/ray-project/ray/pull/13444. But I can re-confirm later. (and I will make sure this will be fixed)
