### ISSUE TITLE
Require opt-in to switching plasma to /tmp instead of /dev/shm

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#14326]
Ray can suffer severe performance degradations (IO hangs / meltdowns) if the object store size is too large. Instead of doing this automatically, make it opt in.

1. Raise an exception if object store size is too large by default (and make auto-configured size small enough to fit)
2. Require an opt in flag / env var to allow switching to /tmp (e.g., RAY_ALLOW_USING_TMP_FOR_PLASMA)

With object spilling, Modin etc. should also no longer need to use /tmp

**Comment by rkooo567** [comment]
cc @devin-petersohn

**Comment by devin-petersohn** [comment]
Thanks, we will be updating how Modin handles the object store to use the new best practices.

We are also encouraging users to initialize Ray themselves starting with 0.9 (this week).
