### ISSUE TITLE
[dashboard] Dashboard failed to start

### ISSUE THREAD

**Issue by RaphaelCS** [ray-project/ray#14344]
### What is the problem?

I tried to run `ray start --head --num-cpus 2 -vv --block &` but it seemed that the dashboard failed to start. I cannot connect to localhost:8265 neither.
Here is the output after executing the command:
```
$ ray start --head --num-cpus 2 -vv --block &
[1] 1356161
$ Local node IP: 192.168.5.201
2021-02-25 20:56:19,113 INFO services.py:1195 -- View the Ray dashboard at http://localhost:8265

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='192.168.5.201:6379' --redis-password='5241590000000000'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop

--block
  This command will now block until terminated by a signal.
  Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.

Some Ray subprcesses exited unexpectedly:
  dashboard [exit code=0]

Remaining processes will be killed.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
**ray**: 2.0.0.dev0
**Python**: 3.7.9
**OS**: Ubuntu 20.04.2 LTS

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```shell
ray start --head --num-cpus 2 -vv --block &
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
What's the log output from `/tmp/ray/session_latest/logs/dashboard.log`?

**Comment by RaphaelCS** [comment]
Before I tried to reproduce the issue to get the output from `/tmp/ray/session_latest/logs/dashboard.log`, I had reinstalled the lastest wheel (and linked to the lastest source code). 
Now the issue doesn't occur anymore. 😄 
I think the issue occurred because I hadn't updated the wheel to the latest (though I had the latest source code). I noticed that after update the wheel to the latest, an error message appeared demanding me to build the dashboard from extra steps, which didn't appear when using a previous wheel. The error message is as follow:
```
  File ".../ray/new_dashboard/dashboard.py", line 44, in setup_static_dir
    raise FrontendNotFoundError(
FrontendNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/new_dashboard/client && npm install && npm ci && npm run build): '/home/LAB/chensi/anaconda3/envs/ray2dev/lib/python3.8/site-packages/ray/new_dashboard/client/build'
```

**Comment by RaphaelCS** [comment]
> Before I tried to reproduce the issue to get the output from `/tmp/ray/session_latest/logs/dashboard.log`, I had reinstalled the lastest wheel (and linked to the lastest source code).

Sorry, I made a mistake. :cry:
I didn't update the wheel to the latest (though I want to). I wrongly download the latest wheel of version 1.2.0 from [this page](https://docs.ray.io/en/releases-1.1.0/installation.html#daily-releases-nightlies). I didn't realize that the wheel's version is related to the doc's version.

But, whatever, the issue doesn't occur after installing the true latest wheel of version 2.0.0, and without any extra build for dashboard.

**Comment by rkooo567** [comment]
Ah yes, sorry about that 😢. There were some issues before that the latest wheel in the doc wasn’t properly connected to the true latest wheel. Now it should be all resolved! Thanks for writing up how you fixed the issue :)!!

**Comment by RaphaelCS** [comment]
Everything is fine now! 😄
