### ISSUE TITLE
[Placement Group] [Java] Security of Get All placement groups in java API

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#14347]
### What is the problem?
Currently, the interface of getting all placement groups in java API will return all `PlacementGroups` in the whole cluster, which brings security issues.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by kfstorm** [comment]
@clay4444 Is this issue resolved? Do you have any plan to resolve it?

**Comment by rkooo567** [comment]
Please reopen if it is not resolved
