### ISSUE TITLE
[core] The autoscaler failed when environments has http_proxy or https_proxy

### ISSUE THREAD

**Issue by ConeyLiu** [ray-project/ray#14350]
### What is the problem?
When the environment has set `http_proxy` or `https_proxy`, got the following errors:
```python
In [1]: import ray

In [2]: ray.init()
2021-02-25 22:41:24,961 INFO services.py:1226 -- View the Ray dashboard at http://127.0.0.1:8265
2021-02-25 22:41:26,775 WARNING worker.py:1063 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 272, in run
    self._run()
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 166, in _run
    self.update_load_metrics()
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 131, in update_load_metrics
    request, timeout=4)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1614264084.283816946","description":"Error received from peer ipv4:10.239.4.80:913","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Socket closed","grpc_status":14}"
>

```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by thomasdesr** [comment]
Hey @ConeyLiu !

I'm having difficulty reproducing this behavior. I've tried a few approaches like this:

```
$ nc -l 8080 &
[1] 3821

$ cat <<EOF | HTTP_PROXY=http://localhost:8080 HTTPS_PROXY=http://localhost:8080 python
> import os
> print(os.environ["HTTP_PROXY"], os.environ["HTTPS_PROXY"])
>
> import ray
> print(ray.__version__)
>
> ray.init()
> EOF
http://localhost:8080 http://localhost:8080
1.2.0
2021-02-26 16:30:14,957 INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265

$
```

Could you share a bit more context on how you're triggering this behavior in your reproduction script?

**Comment by ConeyLiu** [comment]
Hi @thomasdesr,  I got the error on the master branch code.
```python
(ray) lxy@xyliu:~/git_repository/ray/python$ ipython
Python 3.7.7 (default, Mar 23 2020, 22:36:06)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]: del os.environ["http_proxy"]

In [3]: del os.environ["https_proxy"]

In [4]: os.environ["http_proxy"] = "http://example.com:9000"

In [5]: os.environ["https_proxy"] = "http://example.com:9000"

In [6]: import ray

In [7]: ray.__version__
Out[7]: '2.0.0.dev0'

In [8]: ray.init()
2021-02-27 13:29:14,895 INFO services.py:1226 -- View the Ray dashboard at http://127.0.0.1:8265
Out[8]:
{'node_ip_address': '10.239.10.106',
 'raylet_ip_address': '10.239.10.106',
 'redis_address': '10.239.10.106:6379',
 'object_store_address': '/tmp/ray/session_2021-02-27_13-29-13_563859_24641/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2021-02-27_13-29-13_563859_24641/sockets/raylet',
 'webui_url': '127.0.0.1:8265',
 'session_dir': '/tmp/ray/session_2021-02-27_13-29-13_563859_24641',
 'metrics_export_port': 64463,
 'node_id': '010a8ffef98d0eb94a736fdbbbd1409e26a41ee69b808ad3e70e17c5'}

In [9]: 2021-02-27 13:29:18,205 WARNING worker.py:1090 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 272, in run
    self._run()
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 166, in _run
    self.update_load_metrics()
  File "/home/lxy/git_repository/ray/python/ray/monitor.py", line 131, in update_load_metrics
    request, timeout=4)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/lxy/miniconda3/envs/ray/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1614403758.197256674","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
>

In [9]:
```

**Comment by thomasdesr** [comment]
That does it! Thanks :D

I do have a question if the fix in #14351 is the right way to handle this. These environment variables are fairly standard ways to configure various network clients.

Do you have a use case where these environment variables need to be set but GRPC clients should not be following their instructions? I'm worried we'd break users who depend on this behavior.

One complication is that this does look like a change in behavior from `1.2` -> `2.0`. I can't repro this on `1.2`.

**Comment by AmeerHajAli** [comment]
This change was introduced after ray 1.2, here:
https://github.com/ray-project/ray/commit/d87a82e8915f5bb3adc24b6f0f99ddece10be3ea#diff-f53bc0455e31fe9f401c121cd42fed36aca0ca3f862c8b88588b6a133da9dc64

**Comment by ConeyLiu** [comment]
> Do you have a use case where these environment variables need to be set but Ray's GRPC clients should not be following their instructions? I'm worried we'd break users who depend on this behavior.

I have not that case. Our proxy is used to access the network outside of the company. The ray cluster should be a local network cluster. I have patched before for dashboard https://github.com/ray-project/ray/pull/12598. It has a similar problem and had reported by some users too.

**Comment by thomasdesr** [comment]
Since this is a new & unreleased behavior let us hope no one is depending on this yet.

If you're reading this in the future because making this change broke your use case, sorry 😭. Please reply here so we can discuss how to support both of these situations.
