### ISSUE TITLE
[build system] hanging docker containers after build fails or aborts

### ISSUE THREAD

**Issue by shaneknapp** [ray-project/ray#1436]
### System information
- **Linux Ubuntu 16.04**:
- **Ray installed from source for CI builds**:

### Describe the problem
When a Ray build ends prematurely, and after test/jenkins_tests/multi_node_docker_test.py runs, it leaves behind docker containers that take ~500G of disk space.

### Source code / logs
in test/jenkins_tests/multi_node_docker_test.py:
```
        command = (["docker", "run", "-d"] + mem_arg + shm_arg + volume_arg +
                   [docker_image, "ray", "start", "--head", "--block",
                    "--redis-port=6379",
                    "--num-redis-shards={}".format(num_redis_shards),
                    "--num-cpus={}".format(num_cpus),
                    "--num-gpus={}".format(num_gpus),
                    "--no-ui"])
        print("Starting head node with command:{}".format(command))

        proc = subprocess.Popen(command,
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

after speaking w/dan crankshaw about his docker testing approach, he strongly suggests the following (which i agree with):

1.  add a tag/label to each and every docker container that is launched
2.  add a final step to your tests that goes through this list of tags and explicitly kills these containers
3. set up all of your builds to be limited to one executing on a worker at any time.  this will keep builds from stomping on other ray containers.

**Comment by shaneknapp** [comment]
to give you an idea of how much disk space is being used by these hanging containers (as well as expressing the urgency of needing this fixed):

with hanging containers (/var/lib/docker is mounted in /home):
```
sknapp@amp-jenkins-staging-worker-01:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
020ef2171d9a        b0caa6955ea5        "ray start --block..."   11 hours ago        Up 11 hours                             focused_yalow
65608b4759f2        b0caa6955ea5        "ray start --block..."   11 hours ago        Up 11 hours                             nostalgic_mclean
ab35a3e72b2c        b0caa6955ea5        "ray start --block..."   11 hours ago        Up 11 hours                             silly_lamarr
2b1d73a9f86f        b0caa6955ea5        "ray start --block..."   11 hours ago        Up 11 hours                             suspicious_mestorf
20ad83ef507a        b0caa6955ea5        "ray start --head ..."   11 hours ago        Up 11 hours                             vigorous_neumann
sknapp@amp-jenkins-staging-worker-01:~$ df -h | grep home
/dev/sda        881G  594G  243G  71% /home
```

after force-killing those containers, running docker-gc and deleting the associated images and volumes:

```
sknapp@amp-jenkins-staging-worker-01:~$ df -h | grep home
/dev/sda        881G  171G  665G  21% /home
```

**Comment by shaneknapp** [comment]
adding 1T of disk to the workers has definitely helped, but i had to clean up both ubuntu workers today...  one was at 60% disk utilization, and the other at 50% due to hanging ray containers.

**Comment by robertnishihara** [comment]
Thanks @shaneknapp we'll try out that solution this weekend.

**Comment by robertnishihara** [comment]
@shaneknapp can you point me to a recent example of this occurring? Looking through https://amplab.cs.berkeley.edu/jenkins/job/Ray/ (and ignoring the recent string of failures due to a new version of `gym`), I see some failures, but from the logs it appears to me that the containers are all shut down. Trying to debug this and I want to make sure I'm looking at the correct log files.

**Comment by shaneknapp** [comment]
i killed a few yesterday...  since we have enough disk now for this to not
take down a build node, i will let you know the next time this happens.

On Fri, Jan 26, 2018 at 12:21 PM, Robert Nishihara <notifications@github.com

**Comment by robertnishihara** [comment]
I observed the following just now.

If I start a test such as

```
python test/jenkins_tests/multi_node_docker_test.py --docker-image=558a2b347fda --num-nodes=5 --num-redis-shards=5 --num-gpus=0,1,2,3,4 --num-drivers=7 --driver-locations=0,1,0,1,2,3,4 --test-script=/ray/test/jenkins_tests/multi_node_tests/remove_driver_test.py
```

and then stop it with **Control c**, it will shutdown the containers properly. However, if I stop it with **Control-\** (or **kill -9**), it will leave the containers running.

So in situations where our tests hang and assuming Jenkins sends a **kill -9** signal then we will probably leave containers dangling.

**Comment by shaneknapp** [comment]
yep, jenkins sends a SIGKILL.

**Comment by robertnishihara** [comment]
Closed because I think this is "mostly" addressed by #1477. Of course, the problem will still arise if our tests get a SIGKILL, but now they should raise an exception on their own if they take more than 10 minutes.

Let me know if you see more orphaned docker containers.

**Comment by shaneknapp** [comment]
it happened again.  looks like a build took too long to complete, timed out, and the SIGKILL issued by the jenkins job proc didn't percolate up to kill the docker container properly:

https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/3664/

```
sknapp@amp-jenkins-staging-worker-02:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e280aa573e1d        b958ffb2d857        "python /ray/pytho..."   13 hours ago        Up 13 hours                             elastic_clarke
```

**Comment by robertnishihara** [comment]
I see, that behavior is expected given the SIGKILL. Though the experiment really should timed out and exited on its own..
