### ISSUE TITLE
[autoscaler] Kubernetes support

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1437]
I took a look at this and I think the following would be sufficient to support launching autoscaling Ray clusters in Kubernetes:

- Implement and register a k8s node_provider class (this interface here: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/node_provider.py). An example implementation for AWS/boto is here: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/node_provider.py. I think the "nodes" would be  implemented as pods in k8s, and tags would be k8s pod labels (or possibly annotations).

- The head Ray node/pod that hosts the autoscaler will need permissions to list pods, query their labels/annotations, and add/remove pods.

- Since pods don't have public IPs by default we'll have to replace the SSH commands used to set up nodes with kubectl exec equivalents when using a k8s provider.

Note that since Ray's scheduler needs fine-grained control over which pods to remove, we can't easily use higher-level Kubernetes scheduling primitives.

**Comment by ericl** [comment]
@virtualluke

**Comment by virtualluke** [comment]
I will be looking at this this week, will post any status/ideas as I go.

**Comment by bigdata2** [comment]
@ericl Can you describe how in the current implementation AWS autoscaler detects if a node is dead and can be removed? From glancing at the code, it looks like that the Monitor class in monitor.py is somehow handling that, but I am not clear how. More specifically I am not clear how _update function which seem to be handling autoscaling is getting called in autoscaler.py. 
Also, the resources for each node have to be accounted for when scaling up. Finally, why does "Ray's scheduler needs fine-grained control over which pods to remove"?  If a local scheduler is terminated then the corresponding pod can be removed correct?

**Comment by ericl** [comment]
@bigdata2 the monitor class does two things
- subscribe to local scheduler heartbeats, which are processed as they are received via `self.load_metrics.update()`
- periodically trigger an autoscaling pass by calling `self.autoscaler.update()`

During an `update` call, the autoscaler looks at the load metrics to determine whether new nodes should be added or removed. It also tries to recover nodes which look unhealthy (no heartbeat within AUTOSCALER_HEARTBEAT_TIMEOUT_S=30s).

The reason we need fine-grained control is because we don't want to terminate nodes that are still running tasks, or whose object store is still serving object transfers to other tasks. Local schedulers never terminate themselves, and can always receive tasks at any time from the global scheduler. Note that the current implementation is subject to a race condition which can be handled by fault tolerance but isn't completely ideal:
- The autoscaler can decide to terminate an idle node at the same time a global scheduler assigns a new task to it.

This can be improved in the future by adding calls to the global scheduler to disable scheduling for a node before attempting to remove it.

**Comment by bigdata2** [comment]
Okay, I agree that the race condition should be handled somehow -- global scheduler blocking resource allocation on a node seems to be a reasonable approach. 

I am also looking at a similar case where the current autoscaler in Ray needs to work with Kubernetes scheduler so that the resource is reserved or locked on a node when a request to add a pod is made to avoid race conditions or overloading of the nodes.  

How is cluster's resource utilization calculated? Is it the total load on all the individual nodes in a cluster or something else?

**Comment by ericl** [comment]
Resource utilization is calculated as follows:

Initialize `total_load_fraction = 0.0`
For each node, compute the usage fraction of each resource (e.g. 2/4 GPUs = 0.5). Add the max usage fraction across resources to `total_load_fraction`.
The utilization fraction is just `total_load_fraction / num_nodes`.

This ensures we always take into account the bottleneck resource when scaling up.

You can find some examples of this calculation here https://github.com/ray-project/ray/blob/master/test/autoscaler_test.py#L118

**Comment by bigdata2** [comment]
So if I understand it correctly, this is a design where Ray is also acting as a cluster manager to autoscale (add/remove) cluster nodes when the load changes because of additional services running on the cluster.  Kubernetes autoscaler when enabled adds new node to the cluster if there are pods that cannot fit into the existing cluster. I am not sure about the need of autoscaler in that case. However, it will be useful to bring up Ray with Kubernetes.

**Comment by ericl** [comment]
You'll still want Ray autoscaling in Kubernetes though, since otherwise Ray workers could be idle and using resources that other Kubernetes jobs could use instead (or Kubernetes could release the nodes to the underlying cloud provider). The Ray autoscaler would just be managing pods instead of nodes directly.

**Comment by xprotobeast2** [comment]
I am trying to get ray to work with k8s. Need some clarification on whether I am tracking what you want on this. 
1. Is there any merit to allow ray.init() to spin up an autoscaling cluster?  If i understand it correctly, right now the only way to create an autoscaling cluster is through ray create. The use case might be something like an interactive python session inside an existing kubernetes pod where I do:
```
import ray
ray.init(autoscale=true, autoscaling_config=default_config)
```
and I end up with `num_workers` number of pods with identical or specified configs running ray workers, and also a StandardAutoscaler, Monitor etc able to add, remove pods.

2. ray create_or_update works exactly as it does now except nodes are implemented as pods.

**Comment by ericl** [comment]
@xprotobeast2 the use case (1) you described makes a lot of sense to me, since wanting to leverage ray from an existing pod is probably common.

Also it shouldn't be hard to add (2) later on top of that as needed.

**Comment by robertnishihara** [comment]
Still haven't worked out autoscaler support, but we have preliminary documentation for using Ray on Kubernetes available at https://ray.readthedocs.io/en/latest/deploy-on-kubernetes.html.

**Comment by gaocegege** [comment]
Trying to do feasibility research based on ray and the ray-operator: https://github.com/gaocegege/ray/pull/1

Now it can get head/worker node info from k8s. But have some problems when getting the monitor info using kubectl in autoscaler/updater. Because there is no file named `monitor*` when `rayproject/examples` is running.

One quick question: How can we collect metrics from the container? I am not sure why it cannot be collected. I am using the same cmd as we did in other node-providers now.

## Helpful Info

### Worker Logs

```
Using IP address 10.244.0.5 for this node.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-20_13-52-56_1/logs.
WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting the Plasma object store with 6.612813414 GB memory using /tmp.
{'webui_url': '', 'node_ip_address': '10.244.0.5', 'redis_address': u'10.111.224.247:6379', 'redis_shards': ['10.244.0.6:6380', '10.244.0.6:6381'], 'object_store_address': '/tmp/ray/session_2019-08-20_13-52-56_1/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2019-08-20_13-52-56_1/sockets/raylet'}

Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop
```

Run `bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && tail -n 100 -f /tmp/ray/session_*/logs/monitor*'`:

```
root@sample-cluster-worker-7f65cdd786-z9n6z:/ray# bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && tail -n 100 -f /tmp/ray/session_*/logs/monitor*'
tail: cannot open '/tmp/ray/session_*/logs/monitor*' for reading: No such file or directory
tail: no files remaining
```

Run `ls /tmp/ray/session_*/logs/`

```
root@sample-cluster-worker-7f65cdd786-z9n6z:/ray# ls /tmp/ray/session_*/logs/
log_monitor.err   raylet.out                                           worker-a47e7d31cc1685dde0c1c1fc656587af483744d6.err
log_monitor.out   worker-66b970d170168753fd5b2a265f3d196fd3e2aa4a.err  worker-a47e7d31cc1685dde0c1c1fc656587af483744d6.out
plasma_store.err  worker-66b970d170168753fd5b2a265f3d196fd3e2aa4a.out  worker-cd2707b06408f302157791c60bb198b79d2137e1.err
plasma_store.out  worker-778b346d190fa9188cb1cfa442f2ba7802c4106e.err  worker-cd2707b06408f302157791c60bb198b79d2137e1.out
raylet.err        worker-778b346d190fa9188cb1cfa442f2ba7802c4106e.out
```

**Comment by edoakes** [comment]
Were you running this on the head node? The monitor process only runs on the head node and therefore those logs will only appear there.

**Comment by gaocegege** [comment]
Thanks. Since we have a WIP PR now, I am going to review and help enhance it.

**Comment by gaocegege** [comment]
Can we close the issue now? I think #5492 implemented the feature.

**Comment by edoakes** [comment]
#5492
