### ISSUE TITLE
[autoscaler] Azure support

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1438]
It would be nice to support Azure VMs as well. Largely this would require implementing and registering an Azure node_provider class (this interface here: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/node_provider.py). An example implementation for AWS/boto is here: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/node_provider.py. 

See also: https://github.com/ray-project/ray/issues/1437

**Comment by sachinkundu** [comment]
I can take this now unless someone else is working on this already.

**Comment by robertnishihara** [comment]
Hi @sachinkundu, that'd be amazing. I don't think anyone is currently working on it. cc @hartikainen @ericl @richardliaw 

Please let us know if you have any questions.

**Comment by pcmoritz** [comment]
@sachinkundu Have you had a chance to look into this?

**Comment by chenhuims** [comment]
@ericl @sachinkundu Does Ray support Azure now? If not, do you know what else one needs to do besides  registering an Azure node_provider class to enable Azure?

**Comment by sachinkundu** [comment]
@pcmoritz I haven't been able to get to this. Sorry for that. I do want to asap. @chenhuims Are you interested in taking over? Yes I think one needs to provide node_provider implementation as it is for other cloud providers.

**Comment by chenhuims** [comment]
@pcmoritz @richardliaw Thanks for the replies! I'm happy to look into this. But I'm really new to Ray. It could be nice that you can provide me some instructions.

**Comment by robertnishihara** [comment]
@chenhuims that sounds great! Please take a look at https://github.com/ray-project/ray/pull/2061 to see how support for GCP was implemented.

**Comment by shreyagu** [comment]
@chenhuims @robertnishihara  @richardliaw @ericl Was anyone able to implement this for Azure?

**Comment by robertnishihara** [comment]
@shreyagu there hasn't been any progress on this. If you can help, that'd be fantastic!

**Comment by richardliaw** [comment]
Note for others that as of 1/10/2020, this is still an open issue :)

**Comment by gramhagen** [comment]
Happy to help here as well. I'm wondering if it would be easier to use a Virtual Machine Scale Set (https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview) to configure the workers.

Also I'm curious what the head node is used for? Is it necessary to configure it separately from the worker nodes, or could a worker node arbitrarily be selected as the head node.

**Comment by gramhagen** [comment]
first cut here: https://github.com/gramhagen/ray/tree/gramhagen/azure_autoscaler

Still WIP, after I test it out a bit I'll push a PR, there's definitely things that I don't understand perfectly on both the Ray side and the Azure side, but hopefully we can iron out all the kinks

**Comment by robertnishihara** [comment]
Thanks @gramhagen! Looking forward to trying it out.

**Comment by richardliaw** [comment]
@gramhagen feel free to make a draft PR and tag folks if you have questions on any parts of the code!

**Comment by gramhagen** [comment]
thanks @richardliaw! I'll do that. so far the bootstrap_azure() function seems to be working

**Comment by richardliaw** [comment]
We've just merged Azure support. Feel free to try it out!
