### ISSUE TITLE
Unable to start a dashboard

### ISSUE THREAD

**Issue by KhrystynaFaryna** [ray-project/ray#14391]
Hi, this is an awesome framework.  I ran into an issue, I am trying to use ray[tune] to reproduce [this ](https://github.com/kakaobrain/fast-autoaugment) project. My jobs are running on a local linux gpu cluster.
How can I access the **dashboard** from my windows pc? If I go to localhost:8265, I get  "This site can’t be reached
localhost refused to connect."
I followed the instructions from [here](https://docs.ray.io/en/master/ray-dashboard.html). Any help would be much appreciated.

**Comment by richardliaw** [comment]
Hey @KhrystynaFaryna maybe you need to port-forward that 8265 port to your local laptop? https://phoenixnap.com/kb/ssh-port-forwarding
`ssh -L8265:localhost:8265 ubuntu@...`

**Comment by KhrystynaFaryna** [comment]
Yes I did that -  it did not help. I also tried using:
`ray.init(dashboard_host='0.0.0.0')`
Now it says:
`-- View the Ray dashboard at http://172.17.0.3:8265`
And when I go there I get:
''This site can’t be reached 172.17.0.3 took too long to respond.''

I am using ray version 1.2.0.

**Comment by richardliaw** [comment]
Hmm, maybe you'll need to open a port between 172.17.0.3 for your local machine?
