### ISSUE TITLE
1.0 migration guide is missing

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#14399]
Reading through [releases](https://github.com/ray-project/ray/releases), a 1.0 migration guide is mentioned:

> If you're migrating from Ray < 1.0.0, be sure to check out the [1.0 Migration Guide](https://github.com/ray-project/ray/discussions/11482).

I would want to check it out, but the link does not work. So where is the 1.0 Migration Guide?

**Comment by Frag17** [comment]
Find the same queestion

**Comment by rkooo567** [comment]
Hmm @richardliaw do you know where the link is?

**Comment by rkooo567** [comment]
Ah it looks like it was in discussions channel, and we removed it.

**Comment by Frag17** [comment]
> Ah it looks like it was in discussions channel, and we removed it.

Can you place it in documents or something else，So we can  check out the Migration Guide？

**Comment by fatenghriss** [comment]
Hello, did someone ended by by finding a link to this migration guide? Thanks

**Comment by richardliaw** [comment]
Hmm, I am trying to recover this doc but it looks like I cannot find it. 

Here is an "audit" spread sheet that we did share publicly:

https://docs.google.com/spreadsheets/d/1F6VZ1R_fgDzpRZjXI5_6gaUwW2CQKi431dCDTR-Vm8s/edit#gid=0

**Comment by rkooo567** [comment]
Btw, the original doc was in our "discussion" channel, which we decided to delete over discuss.ray.io. And the post was deleted because of that.

**Comment by mitar** [comment]
And nobody can find the doc through other means?

**Comment by richardliaw** [comment]
Yeah, the doc is just wiped out by github (it was just a github discussion note with a couple comments).

**Comment by mitar** [comment]
So how do I then migrate past 1.0?

**Comment by richardliaw** [comment]
The guide was largely a collection of user-raised questions (probably was like 5-10 suggestions). Happy to help guide you through this myself.
