### ISSUE TITLE
[rllib] custom env document example failed

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#1440]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.3.0
- **Python version**: 3.6
- **Exact command to reproduce**:

import ray
from ray.tune.registry import register_env
from ray.rllib import ppo

def create_my_env():
    import gym
    return gym.make("CartPole-v1")

env_creator = lambda :create_my_env()
env_creator_name = "myenv"
register_env(env_creator_name, env_creator)
ray.init()
alg = ppo.PPOAgent(env=env_creator_name)
for i in range(10):
    result = alg.train()
    print(result)

### Describe the problem
myenv does not exist. the example in the document of ray does not work
http://ray.readthedocs.io/en/latest/rllib.html#custom-environments

this can be fix by following
alg = ppo.PPOAgent(env=env_creator_name, registry=ray.tune.registry._default_registry)

however, i think this is not very elegant to use in this way.

I think abstract definitions of the environment in ray rllib should be explicitly written into the document to make it clear for users to customize their environment.

for example:

```
class env(object):
    """
    observation space
    action space
    """
    def step(self, action):
        raise NotImplementedError
    
    def reset(self):
        raise NotImplementedError
    
    def render(self):
        raise NotImplementedError
    
    def close(self):
        raise NotImplementedError
    
    """
    ...
    """
```

I think in the application of reinforcement learning in practice, the form of the environment often exists as a remote service address.

```
class env(object):
    """
    observation space
    action space
    """
    def step(self, action):
        import requests
        return requests.post(url, json=params)
    
    def reset(self):
        raise NotImplementedError
    
    def render(self):
        raise NotImplementedError
    
    def close(self):
        raise NotImplementedError
    
    """
    ...
    """
```

Batch creation environment may need to take parameters

```
class BatchedEnv(object):
    """This holds multiple gym envs and performs steps on all of them."""
    def __init__(self, env_creator, batchsize, options):
        self.envs = [env_creator() for _ in range(batchsize)]
```

Thank you for your excellent work

**Comment by robertnishihara** [comment]
Thanks @raopku, looks like we need the `env_creator` to take a config argument (and need to update the documentation to reflect this). E.g.,

```python
def create_my_env():
    import gym
    return gym.make("CartPole-v1")

env_creator = lambda config: create_my_env()
```

**Comment by ericl** [comment]
@raopku good point on the abstract env -- there's actually a stub provided by OpenAI just for this, but it's a bit hard to find. Let me dig it up and add it to the docs.

The registry issue I believe is already fixed in master (https://github.com/ray-project/ray/blob/master/python/ray/rllib/agent.py#L77). Since 0.3.1 is so close we might just want to wait for that instead of attempting a backport to 0.3.0.

**Comment by richardliaw** [comment]
Partially addressed in #1443. A few changes should still be made (see discussion on thread).

**Comment by ericl** [comment]
https://github.com/ray-project/ray/pull/1447

**Comment by shirellm** [comment]
Hello everyone, I'm new to openAI gym and RLlib. I'm trying to run a PPOTrainer on the env i created on gym but something is not working and I can't figure what is the problem.
my main file is:
````
import numpy as np
import gym
import mujoco_py
import random
import sys
sys.path.insert(1, '/home/mosaic-challenge/shirelle_ws/gym_shirelle/gym-dog')
import gym_dog
from gym_dog.envs.dog_env_2 import DogEnv2 as env
import ray
from ray.rllib.agents import ppo
import tensorflow as tf
from ray.tune.registry import register_env
from ray import tune
from ray.tune.logger import pretty_print
def create_my_env():
    import gym
    return gym.make('dog-v2')


env_creator = lambda config: create_my_env()

env_creator_name = "myenv"
register_env(env_creator_name, env_creator)
ray.init()
alg = ppo.PPOTrainer(env=env_creator_name)
for i in range(10):
    result = alg.train()
print(result)
```

*************** my env is (in a different file):************


```
import gym
from gym import error, spaces, utils
from gym.utils import seeding
import numpy as np
from gym_dog.envs.mujoco import mujoco_env
from ray.rllib.agents.ppo import PPOTrainer


class DogEnv2(mujoco_env.MujocoEnv, utils.EzPickle, gym.Env):

    def __init__(self):
        mujoco_env.MujocoEnv.__init__(self, "./go1/xml/go1.xml", 5)
        utils.EzPickle.__init__(self)
        self.action_space = gym.spaces.box
        self.observation_space = gym.spaces.box
        # self.action_space = self.env.action_space
        # self.observation_space = self.env.observation_space

    def step(self, action):
        xposbefore = self.sim.data.qpos[0]
        self.do_simulation(action, self.frame_skip)
        xposafter = self.sim.data.qpos[0]
        ob = self._get_obs()
        reward_ctrl = -0.1 * np.square(action).sum()
        reward_run = (xposafter - xposbefore) / self.dt
        reward = reward_ctrl + reward_run
        done = False
        return ob, reward, done, dict(reward_run=reward_run, reward_ctrl=reward_ctrl)

    def _get_obs(self):
        return np.concatenate(
            [
                self.sim.data.qpos.flat[1:],
                self.sim.data.qvel.flat,
            ]
        )

    def reset_model(self):
        qpos = self.init_qpos + self.np_random.uniform(
            low=-0.1, high=0.1, size=self.model.nq
        )
        qvel = self.init_qvel + self.np_random.standard_normal(self.model.nv) * 0.1
        self.set_state(qpos, qvel)
        return self._get_obs()

    def viewer_setup(self):
        self.viewer.cam.distance = self.model.stat.extent * 0.5
```
