### ISSUE TITLE
[tune] Cleanup function not running to completion

### ISSUE THREAD

**Issue by VishDev12** [ray-project/ray#14407]
### What is the problem?

When migrating from Ray 1.0.1 to Ray 1.1.0 or 1.2.0, I found that the program exits as soon as all the iterations are done in tune.run. The execution of the cleanup function is not fully completed.

I had seen the same problem in a previous version of Ray (0.8.4) and raised this issue:
#7963

@richardliaw implemented a fix for it through this PR:
#7967

In the 1.2.0 version, when trying a fix for it myself, I found that a simple time.sleep allows the cleanup function to complete execution.

**Comment by richardliaw** [comment]
hmm @krfricke maybe take a look at this?

meanwhile @VishDev12 could you check if this is still the case on the latest nightly wheels?

**Comment by krfricke** [comment]
Hm, so this code works for me:

```
import time
from ray import tune

class MyTrainable(tune.trainable.Trainable):
    def setup(self, config):
        print("Setup")

    def step(self):
        return {"metric": self.iteration, "done": True}

    def stop(self):
        print("stop")
        time.sleep(15)
        print("Still stop")


tune.run(
    MyTrainable,
    verbose=2
)
```

i.e. the "Still stop" is printed. Could you build on this to create a reproducible example?

**Comment by VishDev12** [comment]
I'm not sure what happened, but as soon as I set the `TUNE_DISABLE_AUTO_CALLBACK_LOGGERS` environment variable to 1, the issue went away. I must've messed up the logger flow that was changed in version 1.1.0.

Sorry for the false alarm!

**Comment by krfricke** [comment]
Glad to hear that! If the issue comes up again or you suspect it might be related to Tune after all, feel free to re-open.
