### ISSUE TITLE
How to Combining ray queue and asyncio

### ISSUE THREAD

**Issue by bioinfornatics** [ray-project/ray#14404]
Dear,

Firstly thanks for your awesome library.

I would like to split my program into 2 components.

1. a writer into a background thread that run forever (with an input stream of data to store)
2. a producer which generate a stream of data through a job queue `ray.util.queue`

I use currently ray `1.1.0` in python. I do not found into the documentation how to use together ray + queue + asyncio.

Could you provide a little snippet ?

Thanks

something like:
```python
def start_background_loop(loop: asyncio.AbstractEventLoop, queue: Queue) -> None:
    asyncio.set_event_loop(loop)
    loop.run_forever()


async def store(queue: Queue, writer: RecordBatchFileWriter):
    while True:
        if not queue.empty():
            future = queue.get(block=True)
            batch = ray.get(future)
            writer.write_batch(batch)
        else:
            await asyncio.sleep(5)

@ray.remote
def producer(data) -> RecordBatch:
…

async def submit(foo):
   for data in foo:
       while queue.full():
           asyncio.sleep(5)
       queue.put(producer(data))

def main(ray_address):
    queue = Queue(maxsize=no_tasks)
    loop = asyncio.new_event_loop()
    t = Thread(target=start_background_loop, args=(loop,), daemon=True)
    t.start()
    ray.init(address=ray_address)
    foo = … # a list of data to process
    local = fs.LocalFileSystem()
    with local.open_output_stream('somewhere.arrow') as file:
        with RecordBatchFileWriter(file, distance_table_schema) as writer:
            writer_task = loop.create_task(store(queue, writer))
    submitter_task = loop.create_task(submit.remote(foo))
    submitter_task.done()
    writer_task.cancel()
   
```

**Comment by rkooo567** [comment]
cc @architkulkarni

**Comment by architkulkarni** [comment]
Hi @bioinfornatics, in Ray 1.2.0 we have added async get and put methods for the Ray Queue called `get_async` and `put_async`.  See https://docs.ray.io/en/master/package-ref.html#ray-util-queue-queue.  If you would like to stay on Ray 1.1.0, you could try copying the source code available at that link.

Alternatively, see https://gist.github.com/simon-mo/bcc385a2d577b1353b8b3e93b384b55e for two code samples for a producer-consumer pattern which avoids using Ray Queues.  One sample uses ordinary `asyncio` queues, and the other sample uses Ray's [Threaded Actors](https://docs.ray.io/en/master/async_api.html#threaded-actors).

**Comment by bioinfornatics** [comment]
Thanks @architkulkarni that sound awesome.

Thanks for your amazing tool

**Comment by richardliaw** [comment]
Closing for now!
