### ISSUE TITLE
[tune] use Optuna's `fixed_distributions` parameter after next release (2.6.0)

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#14415]
See #14387 and the Optuna docs here: https://optuna.readthedocs.io/en/latest/reference/generated/optuna.study.Study.html#optuna.study.Study.ask

**Comment by hvy** [comment]
Optuna v2.6 ([PyPi](https://pypi.org/project/optuna/2.6.0/)) was just released with this parameter so this issue might be addressable. The conda-forge release is being worked on and should be available this week. Just dropping by for a heads up.

**Comment by krfricke** [comment]
Awesome, thanks! I'll see to address this next week then.
