### ISSUE TITLE
[tune] release 1.2.0 insufficient  aiohttp requirements

### ISSUE THREAD

**Issue by breznak** [ray-project/ray#14413]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
- ray 1.2.0
- python 3.7
- Ubuntu 20.04

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Following the Ray[tune] + PL guide: https://docs.ray.io/en/master/tune/tutorials/tune-pytorch-lightning.html 
fails at importing `aiohttp.typedefs` 
- the version installed by ray is cca 1.2
- when updating `pip install aiohttp==3.6.2` this works, I didn't search for minimal working version of aiohttp 

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@breznak could you show your stacktrace? that'd help us figure out what to fix!

**Comment by richardliaw** [comment]
(closing since this has a quick fix and also we are removing the aiohttp dep soon)
