### ISSUE TITLE
Load, play, rollout a trained/saved policy (without cli rollout.py)

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#14429]
I know this might be a duplicate, but there is still no clear section in the docs explaining how to do a simple rollout/render from a trained policy.
What I'm talking about is **code-based** (not command line based) equivalent of [stable baselines example like this](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading):
<img width="647" alt="Screen Shot 2021-03-01 at 7 20 19 PM" src="https://user-images.githubusercontent.com/140710/109577178-2ac99f00-7ac3-11eb-8408-a878ec8a1143.png">

In constrast, rllib provides only [this huge file that is really hard to understand](https://github.com/ray-project/ray/blob/master/rllib/rollout.py#L25), and can only be used via cli:
<img width="549" alt="Screen Shot 2021-03-01 at 7 21 52 PM" src="https://user-images.githubusercontent.com/140710/109577305-62d0e200-7ac3-11eb-9ca6-c078c2eae2d4.png">

It would be nice to have an example of how to access a trained policy itself, so that we can write a simple render loop like in stable-baselines above.

**Comment by stefanbschneider** [comment]
I set up a simple example in both `stable baselines` and the equivalent in RLlib that illustrates how to train, save, load, and play/rollout an agent: https://github.com/ray-project/ray/pull/15897

* SB example: https://github.com/ray-project/ray/blob/af5d5e99a6611828c5fb782811ace8e60c49a6cb/rllib/examples/sb2rllib_sb_example.py
* Equivalent RLlib example: https://github.com/ray-project/ray/blob/af5d5e99a6611828c5fb782811ace8e60c49a6cb/rllib/examples/sb2rllib_rllib_example.py

@drozzy Does that clarify how to use RLlib in your case? In many parts it's actually quite similar to the SB script.
Where were you looking for such clarification in the RLlib docs? Maybe we can update them to point to this example such that it'll be easier for others.

**Comment by drozzy** [comment]
I don't think I ever saw this done anywhere (maybe I missed it in the docs?):
`analysis.get_best_checkpoint(trial=analysis.get_best_trial())` 

Thank you that's certainly very helpful.
