### ISSUE TITLE
Regression in scheduling performance

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#14420]
### What is the problem?

When running the scalability envelope, it's clear that task scheduling has regressed significantly since the cluster never reaches full utilization (looking at `ray status` it's clear that we're scheduling very slowly.

This is a regression since 1.2.0 (the only scheduling policy PR was #14096 ). 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

Run the scalability envelope (see the 10k task scheduling field). 

`ray submit --start benchmarks/distributed/config.yaml benchmarks/distributed/test_distributed.py`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
@wuisawesome can you include details about the regression and how to reproduce in the issue description?

**Comment by wuisawesome** [comment]
Just to summarize from our sync:

This looks like the issue is worker prestart here. In the sequential spilling case, we only have to start worker processes on the nodes that are used (in the case of a non-fully utilized cluster). Waiting for worker processes to start blocks the scheduling process, so there is less blocking. 

**Short term solution**: Turn randomized spillback off by default. 

We'll need a longer term solution relatively soon, since our dependency management features will increase worker startup times and exacerbate this issue.
