### ISSUE TITLE
[k8s] Operator & JupyterHub Connectivity issues 

### ISSUE THREAD

**Issue by rmkohlman** [ray-project/ray#14438]
I am having a hard time trying to connect to ray head from jupyterhub notebook.

env : k8s on docker desktop Mac 
installed  : ray k8s operator [namespace=ray], k8s jupyterhub [namespace=jhub] 
ray cluster :  example-cluster2-ray-head (example from operators on ray.io page)

![image](https://user-images.githubusercontent.com/45956230/109605847-07165100-7ae3-11eb-9647-26287258a976.png)

**Comment by rmkohlman** [comment]
Okay I got it working... I feel dump 😂
I didn't have the right version of ray on the hub

![image](https://user-images.githubusercontent.com/45956230/109728145-e269ba00-7b72-11eb-96e0-0b7eb5e3e101.png)

**Comment by DmitriGekhtman** [comment]
Glad you were able to get this to work.

We really should have a warning message indicating Ray version mismatch @ericl what do you think?
(I know we do currently show an error showing Python minor version mismatch.)

**Comment by ericl** [comment]
Yep, we are now checking for Ray version compatibility ("protocol version mismatch"), this is only in the nightly build though.
