### ISSUE TITLE
py.typed file missing in PyPI Linux wheel

### ISSUE THREAD

**Issue by cassidylaidlaw** [ray-project/ray#14431]
### What is the problem?

The MacOS wheel of ray contains a `py.typed` file, whereas the Linux wheel does not. This file indicates that type checking can be performed against the types defined in Ray. Excluding the file on Linux means that type checkers like `mypy` work differently on different OSs on projects using Ray.

I have confirmed this for Ray 1.2.0 and Python 3.8 (see below). I have not checked other versions.

### Reproduction (REQUIRED)

The following commands download wheels for MacOS and Linux and grep through the contents to show that the `py.typed` file is only present in the MacOS wheel:

```
$ wget https://files.pythonhosted.org/packages/11/04/a856f1ebbaf293fc765399bd69e3293a51adbd095cd40ae6f10e2d6b4728/ray-1.2.0-cp38-cp38-macosx_10_13_x86_64.whl
$ wget https://files.pythonhosted.org/packages/8b/eb/c4b2b01e4b7f86a5c2e7d34b33d7c128ae8dd13dbb4a2552374f0eeceaa4/ray-1.2.0-cp38-cp38-manylinux2014_x86_64.whl
$ unzip -l ray-1.2.0-cp38-cp38-macosx_10_13_x86_64.whl | grep typed
        0  02-12-2021 19:52   ray-1.2.0.data/purelib/ray/py.typed
$ unzip -l ray-1.2.0-cp38-cp38-manylinux2014_x86_64.whl | grep typed
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @simon-mo do you know why we are missing this dep?

**Comment by simon-mo** [comment]
ah probably because it's not included when we package the wheels, can you file a PR to add it in https://github.com/ray-project/ray/blob/bacbdd297b3ddf1407fd34db926b642717028d7e/python/setup.py#L51-L92

**Comment by syed-ahmed** [comment]
It seems like this issue isn't fixed. I tried the following and don't see a py.typed file:
```
wget https://files.pythonhosted.org/packages/b8/82/591538eb5c856fc7dfc08d05fcca9f2cb5f341825337561475ca7140948d/ray-1.3.0-cp38-cp38-manylinux2014_x86_64.whl
 2112  unzip -l ray-1.3.0-cp38-cp38-manylinux2014_x86_64.whl | grep typed
```
