### ISSUE TITLE
[rllib] Is there any example for training parallel petting zoo environments ?

### ISSUE THREAD

**Issue by dimikout3** [ray-project/ray#14446]
In RLlibs examples for multi-agent systems there is an example only for classic petting environments (rllib/examples/multi_agent_independent_learning.py or rllib/examples/multi_agent_parameter_sharing.py)
I am currently working on a project which requires parallel execution of actions from all the agents. Is any similar example ?

**Comment by mvindiola1** [comment]
@dimikout3 It is not really documented anywhere but there is a ParallelPettingZooEnv that you can import with `from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv`. 

Figuring out how to pad the observations was tricky. I eventually found this to work:
```
from pettingzoo.mpe import simple_adversary_v2, simple_spread_v2
from pettingzoo.utils.to_parallel import to_parallel
from ray.tune.registry import register_env
from supersuit.aec_wrappers import pad_observations

def mpe_env(base_env, mpe_args):
    env = base_env.env(**mpe_args)
    env = pad_observations(env)
    env = to_parallel(env)
    env = ParallelPettingZooEnv(env)
    return env
register_env("simple_spread", lambda mpe_args: mpe_env(simple_spread_v2, mpe_args))
register_env("simple_adversary", lambda  mpe_args: mpe_env(simple_adversary_v2, mpe_args))
```
