### ISSUE TITLE
Cluster ray failure due to port missing

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#14453]
### What is the problem?
Raylet failed to get port in cluster mode.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
# in shell
ray start --head
# run the following script
from collections import Counter
import socket
import time
import test
import ray

ray.init(address='auto', _redis_password='5241590000000000')

print('''This cluster consists of
    {} nodes in total
    {} CPU resources in total
'''.format(len(ray.nodes()), ray.cluster_resources()['CPU']))

@ray.remote
def f():
    time.sleep(0.001)
```
And it'll show errors like this:

```
2021-03-02 12:39:22,238 INFO worker.py:664 -- Connecting to existing Ray cluster at address: 172.17.0.2:6379
This cluster consists of
    1 nodes in total
    8.0 CPU resources in total
(raylet) usage: default_worker.py [-h] --node-ip-address NODE_IP_ADDRESS
(raylet)                          --node-manager-port NODE_MANAGER_PORT
(raylet)                          [--raylet-ip-address RAYLET_IP_ADDRESS]
(raylet)                          --redis-address REDIS_ADDRESS
(raylet)                          [--redis-password REDIS_PASSWORD] --object-store-name
(raylet)                          OBJECT_STORE_NAME [--raylet-name RAYLET_NAME]
(raylet)                          [--logging-level {debug,info,warning,error,critical}]
(raylet)                          [--logging-format LOGGING_FORMAT]
(raylet)                          [--temp-dir TEMP_DIR] [--load-code-from-local]
(raylet)                          [--use-pickle] [--worker-type WORKER_TYPE]
(raylet)                          --metrics-agent-port METRICS_AGENT_PORT
(raylet)                          [--object-spilling-config OBJECT_SPILLING_CONFIG]
(raylet)                          [--code-search-path CODE_SEARCH_PATH]
(raylet)                          [--logging-rotate-bytes LOGGING_ROTATE_BYTES]
(raylet)                          [--logging-rotate-backup-count LOGGING_ROTATE_BACKUP_COUNT]
(raylet) default_worker.py: error: argument --node-manager-port: invalid int value: 'RAY_NODE_MANAGER_PORT_PLACEHOLDER'
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by iycheng** [comment]
I think this bug is related to this PR https://github.com/ray-project/ray/pull/14349  @ericl  @kfstorm

**Comment by rkooo567** [comment]
If this is true, isn't it a serious bug? Should we revert the PR?

**Comment by rkooo567** [comment]
I just tried and couldn't reproduce. Is it happening consistently?

**Comment by iycheng** [comment]
It's consistently happening on my side. Reverting this PR looks like fixing this issue. I merged my code to upstream/origin today and it's not working. I check to the trunk of the remote, and it keeps happening. I'm running it in docker instance which I suppose should be OK?

**Comment by ericl** [comment]
Did you recompile? Sounds like Python is out of sync with C++ changes.

**Comment by iycheng** [comment]
I'll close this. Somehow `python setup.py bdist_wheel` doesn't update `.so`. After cleaning up, it looks good.
