### ISSUE TITLE
[large scale]Reduce redis connections

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#14463]
### Describe your feature request

![image](https://user-images.githubusercontent.com/5276001/109781689-17ddd880-7c43-11eb-9fb7-dcb45be55ec7.png)

Like image up there we use redis client to setup connections to redis, which contains 3 different contexts. Each context would fire a connection and most times not all of them is necessary.
Each redis client contains 1 primary context and N sharding contexts and sometime sharding contexts are not needed.

Basically in a cluster of `N` nodes with `S` sharding redis server, if there're number of `A` actors(workers) running, we have `A*(3+S*3)+N*(3+S*3)+(3+S*3)+G*(3+S*3)`(for details see below)  redis connections in total, which is a very huge number that has already crash our internal redis server.

We would like to reduce redis connections used in ray core, mainly including:
connections used by **worker**: `A*(3+S*3)` -> `A*2`
connections used by **raylet**: `N*(3+S*3)` -> `N*2`
connections used by **GlobalStateAccessor**: `G*(3+S*3)` -> `G*1`
connections used by **Gcs Server**: `(3+S*3)` -> `1+S*3`

I believe this can remarkably reduce the number of redis connections and minimize redis pressure. After this round, we'd like to do further more, including:
1. let raylet instead of worker itself do gcs server failure detecting
2. reduce redis connections directly used by ray-java/ray-python

About sharding connetions

- [x] Disable sharding connections in gcs client https://github.com/ray-project/ray/pull/14600

About contexts

- [x] Disable async context in core worker https://github.com/ray-project/ray/pull/14596
- [x] Disable sync/subscribe context in sharding contexts https://github.com/ray-project/ray/pull/14706
- [x] Disable async/subscribe context in global state accessor https://github.com/ray-project/ray/pull/14705
- [x] Disable async context in raylet redis client https://github.com/ray-project/ray/pull/14617 and https://github.com/ray-project/ray/pull/14704

### Optimization results:
| #raylet| #worker | #redis connection(before) | #redis connection(after)|
| :-----| ----: | :----: | :----: |
| 1,000| 0 | 4,014 |3,012 |
| 1,000 | 1,250 | 11,532 |6,773 |
| 1,000 | 10,000 | 64,039 |33,026 |

(THIS TEST IS BASED INTERNAL CODE BASE)
From this figure we can tell this optimization reduce redis connections by 50% in worker side and 25% in raylet side.
There's still lots of connections existed. We need to analyze them in phase 2.

**Comment by WangTaoTheTonic** [comment]
FYI most of works have been done internally and I would like to file pull requests in near days. :-P

**Comment by WangTaoTheTonic** [comment]
//cc @kfstorm

**Comment by kfstorm** [comment]
In `A*(3+S*3)+N*(3+S*3)+(3+S*3)+G*(3+S*3)`, could you point out the sources?

**Comment by WangTaoTheTonic** [comment]
> In `A*(3+S*3)+N*(3+S*3)+(3+S*3)+G*(3+S*3)`, could you point out the sources?
![image](https://user-images.githubusercontent.com/5276001/109774709-9d5d8a80-7c3b-11eb-931e-abac065aa84e.png)
It's here.

**Comment by rkooo567** [comment]
hey @WangTaoTheTonic this is the perfect timing. We also discovered the overloaded Redis is the bottleneck to scale up the cluster further from one of our users.  

I have 4 questions.
- For (3 + s * 3), is it because each context creates 3 connections, and we have (s+1) context (primary + shards)? 
- And when you say we will only use 2 connections for actor & raylet, how will you remove all these connections? We will not make connections to shards anymore?
- Do we need global state accessor connection separately? Can't we just use the same connection as the worker connection? 

Also, definitely a good idea to reduce the number of connections from the python / java code. Do you have any exact number regarding how many connections each Python worker creates  now?

**Comment by WangTaoTheTonic** [comment]
> * For (3 + s * 3), is it because each context creates 3 connections, and we have (s+1) context (primary + shards)?
yes
> * And when you say we will only use 2 connections for actor & raylet, how will you remove all these connections? We will not make connections to shards anymore?
We will add bool arguments to `redis_client_option` which indicates whether it need sync/async/subscribe context. For those client who need only one or two of those contexts we just set the rest to false.
shards are only used in gcs server for accessing data stored in redis, so we can disable them in other scenarios.(also by bool parameter)
> * Do we need global state accessor connection separately? Can't we just use the same connection as the worker connection?
global state accessor seems to be used more in python code. It is mostly used for getting data from gcs. Redis connection is only to sense failure of gcs server.
I'm not sure if global state accessor can reuse redis connections in worker but it's a bit hard or complicated at first glimpse. Maybe we can do it in phase 2.

>Do you have any exact number regarding how many connections each Python worker creates now?
We did not run python jobs too much. For java it's like 5 or 6 connections created by each worker.

**Comment by kfstorm** [comment]
@WangTaoTheTonic The image you put here has some Ant-internal code. Maybe you'll update it?

**Comment by WangTaoTheTonic** [comment]
> @WangTaoTheTonic The image you put here has some Ant-internal code. Maybe you'll update it?

ok

**Comment by rkooo567** [comment]
Thanks for the response! When do you plan to create PRs for this?

**Comment by WangTaoTheTonic** [comment]
I'd like to create them in a week. :-p

**Comment by ericl** [comment]
cc @wuisawesome

**Comment by WangTaoTheTonic** [comment]
All PRs related with this issue have been merged. I'd like to keep optimize number of redis connections and see what we can do in phase 2.

**Comment by clarkzinzow** [comment]
Great work @WangTaoTheTonic! 😁
