### ISSUE TITLE
Will the TrainingOperator class be automatically converted to Ray Actor in RaySGD?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#14467]
When a Python class is annotated by @ray.remote, the class will be used as a Ray Actor process for stateful calculations.
When I used RaySGD, I studied the source code (torch_trainer.py) and found that the custom TrainingOperator class will be copied to all remote nodes and start a series of actors, so these custom classes with models, etc. 
will be converted into Actor processes ?
Looking forward to your reply.

**Comment by DmitriGekhtman** [comment]
cc @richardliaw @amogkam

**Comment by amogkam** [comment]
@Matrix-World yes internally the `TrainingOperator` class that you define will be copied over to all training process on all nodes. But the `TrainingOperator` class itself is not converted into an actor. We have an internal `TorchRunner` abstraction that is an actor class and represents 1 worker. Each `TorchRunner` objects instantiates the user-defined `TrainingOperator` and stores it as an attribute. Hope this clarifies things.

**Comment by YeahNew** [comment]
> @Matrix-World yes internally the `TrainingOperator` class that you define will be copied over to all training process on all nodes. But the `TrainingOperator` class itself is not converted into an actor. We have an internal `TorchRunner` abstraction that is an actor class and represents the training worker. Each `TorchRunner` actor object instantiates the user-defined `TrainingOperator` and stores it as an attribute. Hope this clarifies things!

get it, Thanks
