### ISSUE TITLE
What is the relationship between ObjectStore and Plasma？

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#14465]
The Ray framework uses ObjectStore as a shared memory to realize communication between processes. I studied the project source code and found that ObjectStore stores and obtains data objects through the underlying Plasma storage mechanism, right?
I am not sure how ObjectStore calls Plasma. Does ObjectStore encapsulate Plasma so that data can be obtained across nodes?
Is master/src/ray/plasma/store_exec.cc used to start the plasma service on the node and allocate a memory area for shared memory?
Is master/src/ray/object_manager/plasma used to store and get the data?
Is object_manager.cc used to manage ObjectStore?
The method calls in the source code are very complicated for me, it is difficult to sort out clearly, can you help explain?
Looking forward to your reply.

**Comment by rkooo567** [comment]
> Is master/src/ray/plasma/store_exec.cc used to start the plasma service on the node and allocate a memory area for shared memory?

This code is not used anymore. We used to start a new process for the plasma store. Now, the plasma store is one of threads inside a raylet. 

You can think it is a layered design. 

Raylet
====
Object Manager (A high level layer that manages objects. It is also in charge of pulling/pushing objects in other nodes if it needs them).
====
Plasma store (object store): Shared-memory based key-value store

core_worker.cc (python worker) basically asks the object manager to pull the object it needs to the local plasma store (this is what ray.get or ray.wait is doing). Once the object is pulled to the local plasma store, the core worker receives the fd of the mmapped file (which is a way plasma store creates objects) and directly access to the shared memory.
