### ISSUE TITLE
[client] [doc] Update Ray 1.0 Architecture white paper with Ray Client

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#14473]
### Describe your feature request

The [Ray 1.0 Architecture](https://docs.google.com/document/d/1lAy0Owi-vPz2jEqBSaHNQcy2IBSDEHyXNOQZlGuj93c/edit?usp=sharing) white paper is now a "definitive guide" for developers to understand Ray internals. Ray Client should be part of "Connecting to Ray"

**Comment by ericl** [comment]
Done!
