### ISSUE TITLE
bazel 4.0.0 build failing

### ISSUE THREAD

**Issue by viotemp1** [ray-project/ray#14475]
### What is the problem?
bazel build -c fastbuild //:ray_pkg failing

*Ray version and other system information (Python version, TensorFlow version, OS):*
git origin/master

### Reproduction (REQUIRED)
I followed the steps from https://docs.ray.io/en/master/development.html
Fast, Debug, and Optimized Builds

Error is 
DEBUG: /home/.../git/ray/bazel/ray_deps_setup.bzl:63:14: No implicit mirrors used because urls were explicitly provided
ERROR: /home/.../.cache/bazel/_bazel_.../3d6f788daadb4d2ddf971c3424fdc02c/external/com_google_protobuf/BUILD:873:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
ERROR: Analysis of target '//:ray_pkg' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed
INFO: Elapsed time: 0.252s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

bazel --version
bazel 4.0.0

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by viotemp1** [comment]
made it finally following the diff from [https://github.com/bazelbuild/bazel/issues/12887](https://github.com/bazelbuild/bazel/issues/12887)
Maybe is not the right solution, there are come warnings when building...

I modified WORKSPACE like this.

diff --git a/WORKSPACE b/WORKSPACE
index 35038a3a1..21834f5c0 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -1,5 +1,20 @@
 workspace(name = "com_github_ray_project_ray")

+load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
+
+git_repository(
+    name = "rules_proto",
+    commit = "cfdc2fa31879c0aebe31ce7702b1a9c8a4be02d2",
+    remote = "https://github.com/bazelbuild/rules_proto.git",
+)
+
+load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
+rules_proto_dependencies()
+rules_proto_toolchains()
+
+load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
+protobuf_deps()
+
 load("//bazel:ray_deps_setup.bzl", "ray_deps_setup")

 ray_deps_setup()

Thanks, can be closed

**Comment by viotemp1** [comment]
I actually have some errors - from time to time. Not sure is this compilation is the problem. I found the same issue with tf-mightly also

(pid=gcs_server) [2021-03-08 16:35:53,918 C 124910 124910] gcs_placement_group_scheduler.cc:202:  Check failed: it != placement_group_leasing_in_progress_.end() 
(pid=gcs_server) [2021-03-08 16:35:53,918 E 124910 124910] logging.cc:435: *** Aborted at 1615214153 (unix time) try "date -d @1615214153" if you are using GNU date ***
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435: PC: @                0x0 (unknown)
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435: *** SIGABRT (@0x3e80001e7ee) received by PID 124910 (TID 0x7f8ad59d9800) from PID 124910; stack trace: ***
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435:     @     0x55d6d32a6cbf google::(anonymous namespace)::FailureSignalHandler()
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435:     @     0x7f8ad5f3b3c0 (unknown)
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435:     @     0x7f8ad5a2418b gsignal
(pid=gcs_server) [2021-03-08 16:35:53,919 E 124910 124910] logging.cc:435:     @     0x7f8ad5a03859 abort
(pid=gcs_server) [2021-03-08 16:35:53,920 E 124910 124910] logging.cc:435:     @     0x55d6d3296005 ray::SpdLogMessage::Flush()
(pid=gcs_server) [2021-03-08 16:35:53,921 E 124910 124910] logging.cc:435:     @     0x55d6d329603d ray::RayLog::~RayLog()
(pid=gcs_server) [2021-03-08 16:35:53,921 E 124910 124910] logging.cc:435:     @     0x55d6d309f414 ray::gcs::GcsPlacementGroupScheduler::MarkScheduleCancelled()
(pid=gcs_server) [2021-03-08 16:35:53,922 E 124910 124910] logging.cc:435:     @     0x55d6d30afa94 ray::gcs::GcsPlacementGroupManager::RemovePlacementGroup()
(pid=gcs_server) [2021-03-08 16:35:53,923 E 124910 124910] logging.cc:435:     @     0x55d6d30b063f ray::gcs::GcsPlacementGroupManager::HandleRemovePlacementGroup()
(pid=gcs_server) [2021-03-08 16:35:53,923 E 124910 124910] logging.cc:435:     @     0x55d6d30073c2 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc14ServerCallImplINS4_35PlacementGroupInfoGcsServiceHandlerENS4_27RemovePlacementGroupRequestENS4_25RemovePlacementGroupReplyEE13HandleRequestEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=gcs_server) [2021-03-08 16:35:53,924 E 124910 124910] logging.cc:435:     @     0x55d6d33f7771 boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server) [2021-03-08 16:35:53,925 E 124910 124910] logging.cc:435:     @     0x55d6d33f8e89 boost::asio::detail::scheduler::run()
(pid=gcs_server) [2021-03-08 16:35:53,926 E 124910 124910] logging.cc:435:     @     0x55d6d33faf97 boost::asio::io_context::run()
(pid=gcs_server) [2021-03-08 16:35:53,926 E 124910 124910] logging.cc:435:     @     0x55d6d2f87417 main
(pid=gcs_server) [2021-03-08 16:35:53,926 E 124910 124910] logging.cc:435:     @     0x7f8ad5a050b3 __libc_start_main
(pid=gcs_server) [2021-03-08 16:35:53,928 E 124910 124910] logging.cc:435:     @     0x55d6d2f9a577 (unknown)

**Comment by TisonKun** [comment]
It seems the same issue as https://github.com/ray-project/ray/issues/14117

**Comment by viotemp1** [comment]
True, I'll watch that Issue. This can be closed
