### ISSUE TITLE
How are the inputs and outputs of every task converted to Apache Arrow format and stored in Object_Store?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#14502]
According to the introduction of the 4.2.3 section (In-Memory Distributed Object Store) in the Ray .paper(https://arxiv.org/pdf/1712.05889.pdf). This zero-copy data format sharing between tasks running on the
same node is Apache Arrow. 
I want to know whether the data calculated by the task or the data read from the file will be automatically converted into the Apache Arrow format, and then the store process of Plasma will be called to store the data?
So how does it convert the data format?

**Comment by rkooo567** [comment]
We don't use arrow format currently by default
