### ISSUE TITLE
[rllib] SAC ignores custom_action_dist

### ISSUE THREAD

**Issue by dHonerkamp** [ray-project/ray#14503]
### What is the problem?

SAC ignores the custom_action_dist argument. I am specifying a custom model (inherited from SACTorchModel) and action dist like this:
```
"model":  {"custom_model": "map_encoder_sac_torch_network",
                    "custom_action_dist": 'MyTanhGaussian',}
```

But this does not get picked up.

In `ray/rllib/policy/policy_template.py` it seems to detect this and enters the `elif make_model_and_action_dist` condition. But then ultimately ends up in `ray/rllib/agents/sac/sac_torch_policy.py` where `_get_dist_class()` ignores the options.

Specifying the same config for PPO properly picks up my custom action distribution.

*Ray version and other system information (Python version, TensorFlow version, OS):*
python3.7.9
ray Version: 2.0.0.dev0

### Reproduction (REQUIRED)
```
import torch
from ray.rllib.models.action_dist import ActionDistribution
from ray.rllib.models.torch.torch_action_dist import TorchDiagGaussian, TorchDistributionWrapper
from ray.rllib.utils.typing import ModelConfigDict, TensorType
from typing import Tuple, Optional, Callable, List
from ray.rllib.models.modelv2 import ModelV2, restore_original_dimensions
from ray.rllib.models.torch.torch_modelv2 import TorchModelV2
import ray
from ray.rllib.models.catalog import ModelCatalog
from ray.rllib.utils.annotations import override
from ray.rllib.agents.sac import SACTrainer

class MyTanhGaussian(TorchDiagGaussian):
    @override(ActionDistribution)
    def __init__(self, inputs: List[TensorType], model: TorchModelV2):
        TorchDistributionWrapper.__init__(self, inputs, model)
        mean, log_std = torch.chunk(self.inputs, 2, dim=1)
        mean = torch.tanh(mean)
        self.dist = torch.distributions.normal.Normal(mean, torch.exp(log_std))

if __name__ == '__main__':
    ray.init()

    ModelCatalog.register_custom_action_dist("MyTanhGaussian", MyTanhGaussian)

    ray_config = {
        "model":  {"custom_action_dist": 'MyTanhGaussian',},
        "env": "CartPole-v0",
        "framework": "torch"
    }

    trainer = SACTrainer(config=ray_config)
    while True:
        print(trainer.train())
```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/16427

**Comment by sven1977** [comment]
Thanks for filing this issue @dHonerkamp and for the detailed description!
The above PR should fix this issue for torch and tf. Your script does go now into your custom distribution, but then throws another error on action out of range. I'm guessing you'd have to tweak the range of your distribution to match the environment?

**Comment by sven1977** [comment]
Closing this issue.
