### ISSUE TITLE
[tune] All of the BOHB trials pause

### ISSUE THREAD

**Issue by RaphaelCS** [ray-project/ray#14500]
### What is the problem?

I am working with **tune** and **rllib** and I try to use BOHB.
But all of the trials pause and finally throw an errror:
```
Traceback (most recent call last):
  File "test_bohb_paused.py", line 30, in <module>
    analysis = tune.run(
  File ".../ray/tune/tune.py", line 520, in run
    runner.step()
  File ".../ray/tune/trial_runner.py", line 519, in step
    self.trial_executor.on_no_available_trials(self)
  File ".../ray/tune/trial_executor.py", line 193, in on_no_available_trials
    raise TuneError("There are paused trials, but no more pending "
ray.tune.error.TuneError: There are paused trials, but no more pending trials with sufficient resources.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
**ray**: 2.0.0.dev0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

```python
import ray
from ray.rllib.agents.dqn import dqn
from ray import tune
from ray.tune.schedulers.hb_bohb import HyperBandForBOHB
from ray.tune.suggest.bohb import TuneBOHB


if __name__ == "__main__":
    ray.init("auto")

    config = {
        "log_level": "INFO",
        "framework": "torch",

        "env": "CartPole-v1",

        "num_gpus": 0.1,
        "num_workers": 1,

        "seed": tune.lograndint(1, int(1e9)),
    }

    bohb_search = TuneBOHB(seed=20210305)

    bohb_hyperband = HyperBandForBOHB(
        time_attr='timesteps_total',
        max_t=int(3e6),
        reduction_factor=4)

    analysis = tune.run(
        dqn.DQNTrainer,
        scheduler=bohb_hyperband,
        search_alg=bohb_search,
        config=config,
        num_samples=100,
        local_dir=".",
        metric="episode_reward_mean",
        mode="max",
    )

    ray.shutdown()
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
(or, change the time_attr to be something like `training_iteration`)

**Comment by RaphaelCS** [comment]
@richardliaw Thanks for your reply!

Do you mean there may be some constraints between timesteps_total and number of samples?

Is there any theoretical reason?

**Comment by richardliaw** [comment]
yep, this is due to BOHB/hyperband and the `max_r` specification.

**Comment by RaphaelCS** [comment]
Ok. Thanks for your help!

I don’t have time to validate the solutions proposed by @richardliaw in the next few months, so I just close this issue.

Feel free to reopen this if anyone still encounters this problem, or to add comment to validate the solutions.
