### ISSUE TITLE
pyarrow.lib.check_status error

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#1451]
OS: Centos 7.4
ray: 0.3.0 (pip install whl from 01-18-2018)
pyarrow: 0.8.0
python3: 3.6.3 (Anaconda 5.0.1)

Not sure where to look for more details, so a pointer in the right direction on the below error would be helpful:

```
Traceback (most recent call last):
  File "agg_parquet_list_all.py", line 162, in stage2
    sub_results = ray.get([stage1.remote(i,m_list,epoch_timestamp) for i in chunks])
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2229, in get
    values = worker.get_object(object_ids)
  File "/opt/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 473, in get_object
    i + ray._config.worker_fetch_request_size())])
  File "pyarrow/plasma.pyx", line 555, in pyarrow.plasma.PlasmaClient.fetch (/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/plasma.cxx:6898)
  File "pyarrow/error.pxi", line 79, in pyarrow.lib.check_status (/ray/src/thirdparty/arrow/python/build/temp.linux-x86_64-3.6/lib.cxx:8350)
pyarrow.lib.ArrowIOError: Broken pipe
```

Would take some work to pull out the code for an example but if needed will try harder.  This same code with few changes was working a few months ago.

**Comment by pcmoritz** [comment]
@virtualluke Thanks for the bug report! Can you share all the logs from /tmp/raylogs from that run with us? That might help to get an idea what is going on, but to ultimately pinpoint and fix the problem, we might need to have the example code to reproduce the problem.

**Comment by robertnishihara** [comment]
@virtualluke So it was working and then you updated Ray and it stopped working? Did you update Ray by doing a `git pull` followed by rerunning `python setup.py develop`?

Could you try `rm -rf`ing the `ray` directory (or running `git clean -f -f -x -d` from `ray/`) and rebuilding? Sometimes arrow doesn't rebuild properly.

**Comment by virtualluke** [comment]
Downloaded the whl from the build a few days ago and did a pip install on the whl.

**Comment by virtualluke** [comment]
Ok, re-ran the program a few times (about 2 hours each time) and watched the resources and output closely.  The above is related to an out of memory problem on one of the ray nodes, and not related to the error as above.  This can be closed.  One of the boxes got enough jobs taking enough memory over time that exhausted the box memory and the resultant error was the above.  The third time running the program just now and the distribution of jobs was more even from a memory perspective and that allowed the program to finish successfully (random success).

I will need to think of a better way to parallelize the work (the data partitioning in particular) to not have this problem repeat.  When this was run a few months ago the data correlation was over much less data and we didn't see this issue.

**Comment by pcmoritz** [comment]
Hey Luke,

Thanks for the update! One solution you should consider if it's possible to estimate the memory requirements of your tasks is using the user-defined resource labels (see https://github.com/ray-project/ray/pull/1236) to define a "memory" label. Instructions are in the PR. You can define a new label "MemoryBytes" which is the amount of bytes that the machine has (in ray start) and the amount of bytes required to run a task (in the decorator). The scheduler will make sure that the memory requirement of the currently scheduled tasks (as specified in the decorator) is smaller than the max defined in the node.

Let us know if that helps!

This however doesn't account for the amount of memory in the object store, so if that's the issue we should brainstorm some more about a good solution.

-- Philipp.

**Comment by virtualluke** [comment]
In this particular case it is hard to estimate the memory required to run a task to be able to put it in the decorator.  I could overestimate and it sounds like I could guarantee finishing without a memory error but I wouldn't optimize spreading the load it seems.

**Comment by robertnishihara** [comment]
Thanks @virtualluke. Closing this as you suggested, though we should figure out how to get a better error message in this kind of situation.
