### ISSUE TITLE
ObjectIDs should be referenceable in closures

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1453]
The following program cannot work since ObjectIDs are not serializable, and hence cannot be closed over:

```
import ray
import numpy as np

ray.init()

X = np.zeros(int(1e6))
X_id = ray.put(X)

@ray.remote
def do_something():
    return len(ray.get(X_id))

print(ray.get(do_something.remote()))
```

You might ask: why not just pass X_id as an argument to do_something? This is sometimes difficult because of the structure of the program, or because the function in question is invoked by library code (e.g. Ray Tune or RLlib) and the library has restrictions (i.e. interface contracts) on the structure of the data passed to user-defined functions and classes.

Some possible ways to resolve this:
1. Make ObjectID serializable -- this would solve the problem, but may complicate lifetime tracking (ref-counting) of objects in the object store. Since objects broadcasted from the driver in this way are likely to be long-lived, premature eviction could be bad. There is no current way to pin objects in memory except via hack with numpy arrays: `arr = np.zeros(1); X_id= ray.put((arr, X))`
2. Add to_string() / from_string() methods to ObjectID -- this has the same problems as (1) but makes closing over the ids more explicit.
3. Named objects.

(Either way, an object pinning API would be desirable).

**Comment by ericl** [comment]
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import base64

import ray
from ray.tune.registry import _to_pinnable, _from_pinnable


_pinned_objects = []
PINNED_OBJECT_PREFIX = "ray.tune.PinnedObject:"


def pin_in_object_store(obj):
    obj_id = ray.put(_to_pinnable(obj))
    _pinned_objects.append(ray.get(obj_id))
    return "{}{}".format(
        PINNED_OBJECT_PREFIX, base64.b64encode(obj_id.id()).decode("utf-8"))


def get_pinned_object(pinned_id):
    from ray.local_scheduler import ObjectID
    return _from_pinnable(ray.get(ObjectID(
        base64.b64decode(pinned_id[len(PINNED_OBJECT_PREFIX):]))))


if __name__ == '__main__':
    ray.init()
    X = pin_in_object_store("hello")
    print(X)
    result = get_pinned_object(X)
```

FYI the following can be used to work around the issue

**Comment by robertnishihara** [comment]
This is done now by @suquark in https://github.com/ray-project/ray/pull/3541 I think.
