### ISSUE TITLE
TuneBaseSearchCV to extend BaseSearchCV from sklearn

### ISSUE THREAD

**Issue by Matgrb** [ray-project/ray#14534]
Currently, the TuneBaseSearchCV inherits from BaseEstimator from sklearn, however, I suppose it should extend BaseSearchCV, in order to be fully consistent with the sklearn API. Thanks to this one can detect, whether this object is in fact an optimization search schema, or a classifier.

**Comment by timvink** [comment]
I think this should probably be an issue in https://github.com/ray-project/tune-sklearn ..

**Comment by richardliaw** [comment]
Thanks! I'll close this for now.
