### ISSUE TITLE
[metrics] Add ASIO event loop statistics collection

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#14545]
### Describe your feature request

Collect count, queueing time, and execution time statistics for asio handler posts, and periodically dump these statistics to the debugging state file.

**Comment by edoakes** [comment]
@clarkzinzow this would be awesome. Any reason to dump them to the state file rather than exporting prometheus metrics?

**Comment by ericl** [comment]
We can probably export both right? I think the reason to dump to state file is that Prometheus metrics aren't generally available post-hoc after a crash, unless you have it setup for collection.

**Comment by edoakes** [comment]
Yep both SGTM. State file is useful for post-hoc analysis/crashes, prometheus metrics are good for monitoring perf over time
