### ISSUE TITLE
Disable ray low memory monitoring

### ISSUE THREAD

**Issue by lcodeca** [ray-project/ray#14541]
See: https://discuss.ray.io/t/disable-ray-low-memory-monitoring/1167
As requested: @rkooo567

Desired behavior:
- start ray without the low memory check
- even if RAM & Swap are (or reach) 100%, all workers/divers just wait for some memory to be freed, without crashing.

I understand that this may be against best practices, but the option is intended for the following scenario:
- RAY+RLlib used for research on a private server/cloud.
- The server/cloud resources usage is not monitored and not fair: first-come-first-served, no user limits.
- The experiment(s) start the ray cluster and starts the training, even if RAM/CPU/Swap are 100%

**Comment by rkooo567** [comment]
Hey @ericl Is there any good workaround he can try now?

**Comment by ericl** [comment]
There's an env var you can set (check the memory monitor code)

**Comment by lcodeca** [comment]
Thank you @ericl 

I think it's `RAY_DISABLE_MEMORY_MONITOR`
https://github.com/ray-project/ray/blob/8b7cf7cab92d4b4b5cfdc4f905eac07129737fc3/python/ray/memory_monitor.py#L59

**Comment by rkooo567** [comment]
Should be available in the recent versions.
