### ISSUE TITLE
[Question] [rllib] Auto-Attention (GTrXL) wrapping not working

### ISSUE THREAD

**Issue by AlessandroZavoli** [ray-project/ray#14548]
Dear all,

I was trying to add the Auto-Attention (GTrXL) wrapping but it seems to fail compiling on "use_attention": True.

Not sure if this is an experimental feature (and thus in beta) or if it should work.

        Traceback (most recent call last):
        File "/home/spectral000az/Documenti/tesisti/ReinforcementLearning/quadnew/main_train_2D.py", line 101, in <module>
          IAE = sim_2d(trainer, env)
        File "/home/spectral000az/Documenti/tesisti/ReinforcementLearning/quadnew/sim_quad1d.py", line 72, in sim_2d
          action = agent.compute_action(obs, explore=False)  # PPO
        File "/home/spectral000az/miniconda3/envs/conda-tf2/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 850, in compute_action
          result = self.get_policy(policy_id).compute_single_action(
        File "/home/spectral000az/miniconda3/envs/conda-tf2/lib/python3.8/site-packages/ray/rllib/policy/policy.py", line 211, in compute_single_action
          out = self.compute_actions(
        File "/home/spectral000az/miniconda3/envs/conda-tf2/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 330, in compute_actions
          to_fetch = self._build_compute_actions(
        File "/home/spectral000az/miniconda3/envs/conda-tf2/lib/python3.8/site-packages/ray/rllib/policy/tf_policy.py", line 788, in _build_compute_actions
          raise ValueError(
      ValueError: Must pass in RNN state batches for placeholders [<tf.Tensor 'default_policy/Placeholder:0' shape=(?, ?, 64) dtype=float32>], got []

**Comment by AlessandroZavoli** [comment]
Thank you. It makes sense, definitively.
However, I'm not sure how to initialize the hidden states at the first call (i thought "None" would work, but it doesn't.) 
If you have an example, it would be helpful.

**Comment by pierreia** [comment]
Hi, Did you success about this problem? I encounter the same difficulty.

**Comment by AlessandroZavoli** [comment]
No. I'm stuck in finding the correct size of the state for the initial step.
One possibility could be to use evaluation callbacks, but that's something I still do not understand entirely

**Comment by sven1977** [comment]
The initial state can be all zeros and has to be of size: [B, `attention_memory_inference`, `attention_dim`], where B is the batch dimension (any number) and the other number are your attention specific config settings.
E.g. `np.zeros(shape=[B, 50, 16])` if config.attention_dim=16 and config.attention_memory_inference=50.
Does this help?

**Comment by itmorn** [comment]
@AlessandroZavoli  Hope this helps you
`state_attention = np.zeros(shape=[70, 32])
        while not done and keep_going(steps, num_steps, episodes,
                                      num_episodes):
            multi_obs = obs if multiagent else {_DUMMY_AGENT_ID: obs}
            action_dict = {}
            for agent_id, a_obs in multi_obs.items():

                if a_obs is not None:
                    policy_id = mapping_cache.setdefault(
                        agent_id, policy_agent_mapping(agent_id))
                    p_use_lstm = use_lstm[policy_id]
                    if True:
                        a_action, p_state, _ = agent.compute_action(
                            a_obs,
                            state=[state_attention],
                            prev_action=prev_actions[agent_id],
                            prev_reward=prev_rewards[agent_id],
                            policy_id=policy_id)
                        state_attention = np.r_[state_attention,p_state][1:]`
