### ISSUE TITLE
[kubernetes][autoscaler] Autodetected resources override the manual ones when autoscaling with K8s

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14553]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Autodetected resources override the manual ones when autoscaling with K8s:
https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/kubernetes/config.py#L85

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by AmeerHajAli** [comment]
Lets add a test for this in our CICD.

**Comment by DmitriGekhtman** [comment]
Yes, should be straightforward to include a test with the PR that addresses this.
