### ISSUE TITLE
Nevergrad PSO doesn't work with ray.tune

### ISSUE THREAD

**Issue by Nithanaroy** [ray-project/ray#14559]
https://colab.research.google.com/drive/1QqK0gwNCTCdA9Vzo7v-Wd9TKfM8oDdrF?usp=sharing shows the problem in detail. 

```python
algo = NevergradSearch(
        optimizer=ng.optimizers.PSO # doesn't work
    )
```

**Error**
The `optimizer` argument passed to NevergradSearch must be either an `Optimizer` or a `ConfiguredOptimizer`.

`OnePlusOne` works fine. Does this mean, ray tune no longer support PSO?

**Comment by krfricke** [comment]
Hi,

this should work if you pass `ng.optimizers.ConfiguredPSO()`, as this will return a factory for creating the optimizer.

However I agree that it should be possible to just pass optimizer classes. I'll address this with low priority - for now please just try to use the suggestion above and let me know if it works.

**Comment by Nithanaroy** [comment]
Thank you, this works.
