### ISSUE TITLE
[autoscaler] Improve latency of `ray down` for big clusters

### ISSUE THREAD

**Issue by jennakwon06** [ray-project/ray#14550]
### Describe your feature request

I'm working with hundred-node EC2 autoscaling clusters. I noticed that `ray down` can take a long time due to serial calls for terminating the EC2 instances. 

From Richard Liaw: """I think it’s because we run docker stop on each of the machines, and stop machines sequentially (which adds up to a lot of time). The amazon console should be much faster for this use case"""

From Ian Rodney: """Yeah we docker stop on all of the nodes because in some NodeProviders node shutdown may not be guaranteed! We can probably find a way to optimize this for NodeProviders that have guaranteed shutdown"""

**Comment by jennakwon06** [comment]
@rkooo567

**Comment by rkooo567** [comment]
Can you also mention how slow it is, what's the workaround you are using right now? (e.g., are you terminating the cluster from the EC2 dashboard or sth?)

**Comment by AmeerHajAli** [comment]
Thanks @jennakwon06 !
The AWS node provider runs the termination in parallel (https://github.com/ray-project/ray/blob/72615ae590d32d4ac1e36e3134e5bec8c7ecac9e/python/ray/autoscaler/_private/aws/node_provider.py#L468)

We should just run the docker stop in parallel as well, @ijrsvt , this should be easy to do as well right? We can spawn multiple threads to call `run_docker_stop`.

**Comment by ijrsvt** [comment]
Quick FYI on this. I've been trying to run the `_exec("docker stop")` command in parallel on threads, threadPoolExecutors and processes, and have been getting an issue where my terminal is in an unusable state after `ray down`. The issue looks like the following:
```
(ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ (ray) ubuntu@ip-172-31-47-243:~/ray$ 
```

The exact issues are: 
1. I press enter, it creates a new shell prompt to the right of the last one.
2. Anything I type is not visible
3. This is only fixed by running `reset`.
