### ISSUE TITLE
[tune] Fix Hyperband to terminate Trial when max_i is reached

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1456]
### Describe the problem
Hyperband should terminate all trials in bracket when bracket is finished.

**Comment by haoyangz** [comment]
I tried running [hyperband.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperband_example.py) with #1586 merged and no longer saw trials that hung forever, but when visualizing using tensorboard, I do find two trials with iterations > 100.  Shouldn't all trials finish at 100 iteration as per the specification of hyperband instance used in  [hyperband.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperband_example.py)? Did I miss something?

**Comment by richardliaw** [comment]
The point of confusion actually is inherited from the original paper: https://people.eecs.berkeley.edu/~kjamieson/hyperband.html 

I'll rename the parameter to a more intuitive value.

**Comment by haoyangz** [comment]
Hmm so what does the `max_t` here mean exactly? Taking the example in [https://people.eecs.berkeley.edu/~kjamieson/hyperband.html](https://people.eecs.berkeley.edu/~kjamieson/hyperband.html), is `max_t`=81+27+9+3+1 instead of 81?

**Comment by richardliaw** [comment]
For what I interpreted from the paper and the post, 
> the number of iterations they are run for `r_i` within each round of the Successive Halving innerloop
would end up giving `total_iterations = 81 + 27 + 9 + 3 + 1`. Originally, `max_t` was intended to be equivalent to `max_iter`.
