### ISSUE TITLE
Collect actor metrics

### ISSUE THREAD

**Issue by kathryn-zhou** [ray-project/ray#14570]
### Describe your feature request
Ray is currently not collecting actor metrics (actors scheduled, actors executed, actors pending). Can we add those and export to Prometheus so that users can view these metrics on their Grafana Dashboards (like they can with tasks scheduled, executed, and pending)?

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
Probably need to handle this in a different way than Prometheus
