### ISSUE TITLE
[core] Raylet kills workers that are not actually idle

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#14577]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

The worker pool kills workers that have been idle after a period, but "idle" just means whether a task has been assigned to it. Workers can also have outstanding RPCs that should be finished before the worker is considered idle. For example:

1. Worker A sends task to worker B.
2. B executes task, stores return value O in local object store. B sends an RPC to its local raylet to pin the object. B waits for the reply before releasing O, to make sure O does not get GC'ed.
3. Raylet kills B because it thinks it's idle.
4. Raylet receives the RPC to pin O, but O has been evicted.

Ideally, we should allow the workers to tell the worker pool when they are idle instead of having the worker pool decide.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Actually, this is kind of what this fixes; https://github.com/ray-project/ray/pull/14408

Previously, we sent a kill request, but it was not actually killed. They just became a zombie (and after the PR above, they won't be). So I guess this should've been fixed?

**Comment by stephanie-wang** [comment]
I see, there is still an issue with outstanding RPCs though. Let me update the description.

**Comment by rkooo567** [comment]
After 2, if the kill request is received, isn't it supposed to be ignored by https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L2645? Or is owns objects "after" it succeeds to pin?

**Comment by ericl** [comment]
cc @kfstorm could you recommend an approach here? This can cause spuriously cause object loss errors. What if the worker reports when it's idle (count outstanding RPCs?)

**Comment by kfstorm** [comment]
Making sure no outstanding RPCs is a way to try. But I'm concerned about chained RPC requests. e.g. RPC request 2 is sent in the reply callback of RPC request 1.

Maybe we need to make sure `io_service`s are idle too?

**Comment by stephanie-wang** [comment]
I think chained requests should be okay, since we can make sure not to count the worker as idle until the second request is fulfilled.

Probably not a good idea to check for `io_service` idle since that will count periodic timers too. I think we can take it on a case-by-case basis, only marking the worker as not idle for specific outstanding RPCs. We could also move the logic about whether there are active ObjectRefs to have the worker check it instead.

**Comment by stephanie-wang** [comment]
@kfstorm, do you think you could take this issue since it is related to the idle worker killing?

**Comment by kfstorm** [comment]
@stephanie-wang Sorry that I'm on leave until May 5th.

**Comment by stephanie-wang** [comment]
It seems that this error can be triggered in memory-intensive workloads. A temporary workaround is to increase the idle timeout for workers:
```python
ray.init(_system_config={"idle_worker_killing_time_threshold_ms": int(1e6)})  # Set to 1000s.
```
