### ISSUE TITLE
Improve the object loss message.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14580]
### What is the problem?

The current message is; 
```
ray.exceptions.ObjectLostError: Object 4dfeca054278f155ffffffffffffffffffffffff0100000001000000 is lost due to node failure.
```

We can improve the error message by:
- Including more details about the node that failed (e.g., its IP address or other identifiers).
- Make sure to disambiguate between losing the owner of the object and its data.
- Provide more details in the object metadata (e.g., the callsite, the name of the creating task or actor, its size).

We'll split this PR into two tasks:

- [ ] Attach call site metadata to ObjectRefs
- [ ] Disambiguate failure types

**Comment by ericl** [comment]
We should also remove the legacy plasma info string here.

**Comment by richardliaw** [comment]
@rkooo567 can you add a bit more about what type of action item is recommended?

A couple thoughts:

1. Common cause of object lost is node pre-emption. Suggestion: Many cloud providers have pre-emption notices. would it be possible to support "object drainage upon pre-emption"? This would mitigate but not fully prevent the problem.

2. One common possibility that my entire application grinds to a halt/dies soon after seeing this error. It'd be good to know what's the right way to design my application such that I can avoid losing my object entirely. For example, having some suggested design pattern for data replication.

Suggestion: There are two ways an object can be created - either through `put` or task return. For task return, probably the right way is to have real fault tolerance (reconstruction?). For `put`, would it be possible to do something like `ray.replicate(object_id)`, which creates copies of the object across multiple nodes, or `ray.object.as_durable(object_id, nfs/s3="...")`, which will allow you to have a backup copy?

**Comment by rkooo567** [comment]
I think the P0 action item here is to figure out how to add structured information to the error object (so that it can include various more information). Once that's done, 1 & 2 both sounds good to me, but I'd say 2 is more low hanging fruit (and higher priority).

**Comment by richardliaw** [comment]
Just to link a user issue: https://discuss.ray.io/t/objectlosterror/2864

**Comment by richardliaw** [comment]
User here also brings up a `replicate` command available in Dask and whether that can be available in Ray:

https://discuss.ray.io/t/objectlosterror/2864/4

**Comment by rkooo567** [comment]
Hmm I am not sure if we support reconstruction replication is necessary. Could be useful for actor workload since reconstruction is hard to be supported for actors. @ericl Is other DP library like Spark exposing replication options to users (or is it even supported)?

**Comment by tkram01** [comment]
Spark allows you to persist a dataframe at different storage levels including replicating it to 2 other cluster nodes - https://spark.apache.org/docs/latest/rdd-programming-guide.html#rdd-persistence

**Comment by stephanie-wang** [comment]
Here are some notes on the types of failures can occur right now, but that all result in ObjectLostError. I'm also including the metadata that I think we can reasonably include:

1. The object was stored in Ray's distributed memory but all copies have been lost.
  a. We can include the IP address where the object was stored.
  b. We can include object metadata such as call site.
2. The owner of the object has died.
  a. We can include the IP address where the owner was, but not the location of the object.
3. The owner of the object is alive, but the ref count for the object is 0. This can happen if the ObjectRef was passed multiple times, and an intermediate ref holder died. It could also be a bug in Ray's distributed ref counting.
  a. We can include the IP address of the owner.

I think this is a good list to start with. At least it should make it clear when there was actually a node failure vs. a process failure vs. a potential bug. Unfortunately, it's a bit hard to include meaningful metadata in cases 2 and 3.

**Comment by ericl** [comment]
Can we propagate a bit of extra metadata (e.g. creation site string / type)
in the object reference proto? That will allow us a good error message even
in the worst case.

**Comment by stephanie-wang** [comment]
Hmm yeah I think we could do that. We can do this in two PRs then, one to propagate the metadata and another to disambiguate the error messages.

**Comment by rkooo567** [comment]
@stephanie-wang After looking at code, it seems like this task https://github.com/ray-project/ray/issues/15962 can also be benefited by this change (adding call site to protobuf). Additionally, I think we can also include (task,actor) repr / type (task vs actor) / ip of (task, actor) to the protobuf? 

```
message ObjectMetadata {
    string repr = 1;
    string ip = 2;
    optional string name = 3;
    string call_stie = 4;
}

message ObjectReference {
    ObjectMetadata metadata = 1;
}
```

In this way, we can always include object_ref.metadata() to every exception such as WorkerCrashedError or ActorDiedError?
