### ISSUE TITLE
Warning messages when redis-server is started on Linux.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#146]
On Linux, after compiling redis and starting a redis-server (e.g., with `src/common/thirdparty/redis/src/redis-server`, a large number of warning messages appear.

These messages appear when the user starts Ray with `ray.init`.

```
ubuntu@ip-172-31-37-7:~/ray$ src/common/thirdparty/redis/src/redis-server
25487:C 22 Dec 23:43:21.136 # Warning: no config file specified, using the default config. In order to specify a config file use src/common/thirdparty/redis/src/redis-server /path/to/redis.conf
25487:M 22 Dec 23:43:21.137 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.9.102 (46a88703/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 25487
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

25487:M 22 Dec 23:43:21.138 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
25487:M 22 Dec 23:43:21.138 # Server started, Redis version 3.9.102
25487:M 22 Dec 23:43:21.138 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
25487:M 22 Dec 23:43:21.138 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
25487:M 22 Dec 23:43:21.138 * The server is now ready to accept connections on port 6379
```

- The first one can be addressed by passing in a config file.
- I'm not sure about the next three, and I don't have a sense of how serious they are (though the redis server does output some very nice suggestions for what to do).

Eventually, I'd like the Redis stdout/stderr (and the stdout/stderr for other processes as well) to be viewable through a web UI but not logged to the terminal.

In the meantime, should we suppress these messages by just redirecting the Redis stdout/stderr to `/dev/null`? Should we leave them as they are? Or should we address them..

**Comment by atumanov** [comment]
I think there's a more general underlying question of what to do with stdio for all Ray system components. We could have something like a RAY_LOG_DIR where logs are aggregated for all system components including Redis. All stdio can be redirected there. User shouldn't see any of this. At the same time, they should be able to access these messages if they want to. So best practice is to store it in a per-daemon log and log-rotate them (to keep the space per log capped).

**Comment by robertnishihara** [comment]
Agreed. There is a deeper question about how to handle output from all the different processes.

**Comment by robertnishihara** [comment]
As a stopgap, this commit redirects the redis-server output to `/dev/null`. This is not a long term solution.. https://github.com/ray-project/ray/pull/149/commits/2d0d0412a37be8d65c9e2138aaa3b7fee91affb2

**Comment by robertnishihara** [comment]
We're suppressing the error for now (by always redirecting redis output to a file). We may want to look into this more in the future to improve redis performance..
