### ISSUE TITLE
[metrics] Report resources allocated to Ray for Grafana dashboard

### ISSUE THREAD

**Issue by kathryn-zhou** [ray-project/ray#14613]
### Describe your feature request
PR #14184 removed deprecated code paths that included Local Available Resource metrics that reported how much of each resource was allocated to Ray. Could we have the new scheduler expose metrics like this so that we can export to Prometheus and then Grafana?

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by ericl** [comment]
@edoakes @rkooo567 what's the state of metrics reporting? Should the raylet emit metrics via OpenCensus? Should the GCS do it instead? Or are there other possibilities here?

**Comment by edoakes** [comment]
@ericl both raylet and the GCS can emit metrics via OpenCensus and it'll show up in the prometheus endpoints. I'm not opinionated about which should do this, but it's probably more useful to have per-node information so maybe raylet is the natural place.

**Comment by ericl** [comment]
Sounds good, so it seems like we should be emitting this from raylet via the existing OpenCensus metrics.
