### ISSUE TITLE
[tune] Issue on page /tune/api_docs/schedulers.html

### ISSUE THREAD

**Issue by garricklw** [ray-project/ray#14625]
It's really difficult from the docs (and I dug around in the code a bit too) to tell what values should go in the time_attr field for applicable schedulers. It would be great if the possible values for that parameter were documented on this page.

**Comment by richardliaw** [comment]
Hmm, that's good feedback. Usually, I would just leave it as `training_iteration` which is the number of times that `tune.report` is called. 

What are you trying to do exactly?
