### ISSUE TITLE
[tune/rllib] experiment launch hangs if resources not predeclared

### ISSUE THREAD

**Issue by andrew-rosenfeld-ts** [ray-project/ray#14621]
### What is the problem?

With a recent Ray nightly, `tune` can hang if resources weren't explicitly requested for an experiment, which was not the case in Ray 1.2.0. See repro below.

The relevant versions are the Ray nightly as of 2021-03-11 (and from a day or two previous), compared vs Ray 1.2.0.
I can reproduce it on various versions of Python (3.7 and 3.8), TensorFlow (1.4 and 2.2), OS's (Ubuntu and Debian), and hardware (laptop, GCP).

### Reproduction (REQUIRED)
This works on 1.2.0 but not on the latest nightly:
```python

from ray import tune
from ray.rllib.agents import ppo


def trainable(config):
    agent = ppo.PPOTrainer(config=config, env='CartPole-v0')
    for i in range(5):
        results = agent.train()
        tune.report(**results)


config = ppo.DEFAULT_CONFIG.copy()
config["num_workers"] = 1

tune.run(trainable, config=config)
```

On the latest nightly, you need to do something like:
```
tune.run(trainable,
         config=config,
         resources_per_trial=ppo.PPOTrainer.default_resource_request(config))
```

Otherwise, things will hang indefinitely with:
```
2021-03-11 14:50:30,228	WARNING worker.py:1093 -- The actor or task with ID ffffffffffffffff4139de48e65f5c38f5415d8d01000000 cannot be scheduled right now. It requires {CPU_group_22bbf6cabd14c38948e3624c2cafb801: 1.000000} for placement, but this node only has remaining {3.000000/4.000000 CPU, 3.416979 GiB/3.416979 GiB memory, 1.708490 GiB/1.708490 GiB object_store_memory, 0.000000/1.000000 CPU_group_22bbf6cabd14c38948e3624c2cafb801, 0.000000/1.000000 CPU_group_0_22bbf6cabd14c38948e3624c2cafb801, 1.000000/1.000000 node:192.168.86.101}
. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

Is this intended? If so, could the message be updated to be more explicit? (I have become used to ignoring these errors, as they often resolve on their own just fine) Could the documentation also be updated?

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@sven1977 @krfricke seems like a recently introduced bug by the placement group support

**Comment by sven1977** [comment]
I think this is actually desired new behavior. But @krfricke @richardliaw , please correct me if I'm wrong here.

The main problem is that the above `trainable` function does not properly define its actual resource requirements (which are, based on the PPO used: 2 CPUs -> 1x driver and 1x worker) and with the new way of always converting to a PlacementGroupFactory, this fails ("more actors (2) than resources (1 CPUs)").

In 1.2, we would not auto-generate a placement group factory and set `has_placement_group=False` in the default `Resources(cpu=1)` object. This would then schedule the experiment to run on a single CPU, even though 2 should be used!

As a quick workaround, you can also set the env variable `TUNE_PLACEMENT_GROUP_AUTO_DISABLED=1`.

**Comment by sven1977** [comment]
@andrew-rosenfeld-ts  ^^

**Comment by sven1977** [comment]
Confirmed that it runs ok when setting the env variable: `TUNE_PLACEMENT_GROUP_AUTO_DISABLED=1`.

**Comment by krfricke** [comment]
Yes, that seems right if the PPO trainer actually requires 2 CPUs to run.

The reason this worked on previous versions is that resource requirements were not strictly enforced. I.e., Tune assumed that you only use one CPU when you don't explicitly set resources. You can however request more resources as long as they're available.

You would eventually run into problems if you reach your resource limits. E.g. if you start 2 trials on a machine with 3 CPUs, Tune will think you have resources to run 3 concurrent trials. It will thus try to start both trials at the same time, but they really would require 4 CPUs.

Here's a simple reproduction script based on your original script:

```
import os
import ray
from ray import tune
from ray.rllib.agents import ppo

os.environ["TUNE_PLACEMENT_GROUP_AUTO_DISABLED"] = "1"

ray.init(num_cpus=3)


def trainable(config):
    agent = ppo.PPOTrainer(config=config, env='CartPole-v0')
    for i in range(5):
        results = agent.train()
        tune.report(**results)


config = ppo.DEFAULT_CONFIG.copy()
config["num_workers"] = 1

tune.run(trainable, config=config, num_samples=2)
```

Thus, the old behavior was actually faulty, even though it works as long as enough cluster resources are available to run all trials at the same time.

**Comment by andrew-rosenfeld-ts** [comment]
Is there any way to make the error message more friendly for users? 

It doesn't mention anything about specifying resources per experiment, it suggests creating fewer actors or increasing the resources available to the cluster.

```
2021-03-11 14:50:30,228	WARNING worker.py:1093 -- The actor or task with ID ffffffffffffffff4139de48e65f5c38f5415d8d01000000 cannot be scheduled right now. It requires {CPU_group_22bbf6cabd14c38948e3624c2cafb801: 1.000000} for placement, but this node only has remaining {3.000000/4.000000 CPU, 3.416979 GiB/3.416979 GiB memory, 1.708490 GiB/1.708490 GiB object_store_memory, 0.000000/1.000000 CPU_group_22bbf6cabd14c38948e3624c2cafb801, 0.000000/1.000000 CPU_group_0_22bbf6cabd14c38948e3624c2cafb801, 1.000000/1.000000 node:192.168.86.101}
. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

**Comment by krfricke** [comment]
I agree that this is not a very informative or actionable error message.

When requesting too many resources within a placement group (as in this case) the message could/should point out that the limit lies within the placement group and not the cluster. cc @ericl 

For Ray Tune we would actually want custom error messages (e.g. suggesting to set the resources_per_trial parameter), but I don't think supporting this is currently on the roadmap.

**Comment by rkooo567** [comment]
What's the status of this?
