### ISSUE TITLE
 [tune] What are workarounds required to use fractional GPU with Pytorch Lightning

### ISSUE THREAD

**Issue by e13000** [ray-project/ray#14624]
In the tutorial, https://docs.ray.io/en/latest/tune/tutorials/tune-pytorch-lightning.html, it is mentioned that certain workarounds needed to use fraction GPU with Pytorch lightning. Would you please give me some pointers what must be done?

**Comment by DmitriGekhtman** [comment]
cc @krfricke @richardliaw

**Comment by krfricke** [comment]
Ah actually let me cc @amogkam who's been working on the PTL integration recently.

**Comment by amogkam** [comment]
@e13000 can you describe your use case some more? Is it just to increase concurrency by having multiple trials share GPUs?

This might actually work out of the box. Can you try with fractional GPUs and see if you are running into any issues?

**Comment by e13000** [comment]
Dear @amogkam, 
Yes, we want increase concurrency using fractional GPU training due to very limited resources. We are a small research team which has just been founded in a third world country. I'm prepared to migrate back to the country this weekend so I can only test again next week. Previously, I was not able to use fractional GPU training with Ray[Tune] + PL. I understand that one can use multiple GPU training for Pytorch-lightning using ray_lightning accelerator but our use-case is not that.
I will update to you as soon as possible.

**Comment by e13000** [comment]
I tried the example here: https://docs.ray.io/en/master/tune/examples/mnist_pytorch_lightning.html
Pytorch==1.8, pytorch-lightning==1.2, ray_tune==1.2, python==3.8.

> Failure # 1 (occurred at 2021-03-18_17-22-42)
> Traceback (most recent call last):
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 586, in _process_trial
>     results = self.trial_executor.fetch_result(trial)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 609, in fetch_result
>     result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/worker.py", line 1456, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(TuneError): �[36mray::ImplicitFunc.train_buffered()�[39m (pid=2306580, ip=10.17.72.150)
>   File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
>   File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/trainable.py", line 167, in train_buffered
>     result = self.train()
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/trainable.py", line 226, in train
>     result = self.step()
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 366, in step
>     self._report_thread_runner_error(block=True)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 512, in _report_thread_runner_error
>     raise TuneError(
> ray.tune.error.TuneError: Trial raised an exception. Traceback:
> �[36mray::ImplicitFunc.train_buffered()�[39m (pid=2306580, ip=10.17.72.150)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 248, in run
>     self._entrypoint()
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 315, in entrypoint
>     return self._trainable_func(self.config, self._status_reporter,
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 576, in _trainable_func
>     output = fn()
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 651, in _inner
>     inner(config, checkpoint_dir=None)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/ray/tune/function_runner.py", line 645, in inner
>     fn(config, **fn_kwargs)
>   File "/home/anhnht3/testpl/testpl.py", line 132, in train_mnist_tune
>     trainer = pl.Trainer(
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 41, in overwrite_by_env_vars
>     return fn(self, **kwargs)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 348, in __init__
>     self.accelerator_connector.on_trainer_init(
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator_connector.py", line 104, in on_trainer_init
>     self.trainer.data_parallel_device_ids = device_parser.parse_gpu_ids(self.trainer.gpus)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 65, in parse_gpu_ids
>     _check_data_type(gpus)
>   File "/home/anhnht3/miniconda3/envs/testpl/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 178, in _check_data_type
>     raise MisconfigurationException("Device ID's (GPU/TPU) must be int, string or sequence of ints or None.")
> pytorch_lightning.utilities.exceptions.MisconfigurationException: Device ID's (GPU/TPU) must be int, string or sequence of ints or None.

**Comment by amogkam** [comment]
@e13000 there's a change to the example that's needed. The `gpus_per_trial` used for Tune can be fractional, but the `num_gpus` passed into the training function (and ultimately to the pl.Trainer) still needs to be an integer. So you'd have to modify it like so 
```
tune.with_parameters(
            train_mnist_tune,
            data_dir=data_dir,
            num_epochs=num_epochs,
            num_gpus=math.ceil(gpus_per_trial))
```
Could you try this out? Thanks.

**Comment by e13000** [comment]
Hi @amogkam 

It works! I really appreciate your help. It would be nice if the examples for pytorch-lightning are updated. 

Best Wishes,
e13000

**Comment by amogkam** [comment]
Great! Yes I will make the change, I just wanted to make sure it worked for you first.
