### ISSUE TITLE
Ray custom controller does not remedy broken deployments

### ISSUE THREAD

**Issue by dimberman** [ray-project/ray#14634]
### What is the problem?

The Kubernetes Operator won't restart pods when pods die.

If I launch a Ray cluster using the documentation found [here](https://docs.ray.io/en/master/cluster/kubernetes.html#k8s-operator) and then a pod dies (or you manually kill a pod), then the ray operator does not launch a replacement pod. This can render a ray deployment unusable.

*Ray version and other system information (Python version, TensorFlow version, OS):*
 
2.0.0-dev
### Reproduction (REQUIRED)

There not a precise code snippet for this, rather this can be found by launching a ray cluster using the operator and killing pods using kubectl.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
Thanks, will look into reproducing and resolving.

**Comment by DmitriGekhtman** [comment]
Should clarify in interest of tracking this, that the specific event currently not remedied is failure of the head pod.
