### ISSUE TITLE
[autoscaler K8s] There is a way that I can count within python the number of actors alive in a K8s ray cluster?

### ISSUE THREAD

**Issue by Jhonathan-Pedroso** [ray-project/ray#14647]
I am having some trouble to submit many actors by the same time in the cluster, and I need a logic to count the number of actors alive just to create a queue. There is a way I can list the number of actors that is currently alive?

Thank you in advance!

**Comment by DmitriGekhtman** [comment]
Hi! Could you post this in the Ray discussion forum under Ray Core: https://discuss.ray.io/c/ray-core/8
and tag me in the message (@dmitri)?

discuss.ray.io is a better place for questions/discussion, as opposed to github, which is better for bugs and requests for specific functionality.

**Comment by Jhonathan-Pedroso** [comment]
> Hi! Could you post this in the Ray discussion forum under Ray Core: https://discuss.ray.io/c/ray-core/8
> and tag me in the message (@dmitri)?
> 
> discuss.ray.io is a better place for questions/discussion, as opposed to github, which is better for bugs and requests for specific functionality.

Done thanks!
