### ISSUE TITLE
Will ray.tune run in parallel in as multi-thread?

### ISSUE THREAD

**Issue by yywangvr** [ray-project/ray#14645]
I copy the code from the official demo: https://docs.ray.io/en/latest/tune/key-concepts.html

```python
# Be sure to first run `pip install hyperopt`

import hyperopt as hp
from ray.tune.suggest.hyperopt import HyperOptSearch

# Create a HyperOpt search space
config = {
    "a": tune.uniform(0, 1),
    "b": tune.uniform(0, 20)

    # Note: Arbitrary HyperOpt search spaces should be supported!
    # "foo": tune.randn(0, 1))
}

# Specify the search space and maximize score
hyperopt = HyperOptSearch(metric="score", mode="max")

# Execute 20 trials using HyperOpt and stop after 20 iterations
tune.run(
    trainable,
    config=config,
    search_alg=hyperopt,
    num_samples=20,
    stop={"training_iteration": 20}
)
```

### Describe your feature request
I am new to Ray.tune, and I want to know:
* How can I ask the Tune.run to run 20 trials in parallel based on my PC cores?
* Is it automatically parallelized? How can I change it?

**Comment by DmitriGekhtman** [comment]
cc @krfricke @richardliaw

**Comment by richardliaw** [comment]
Hey @yywangvr, it will run 20 trials in parallel based on your PC cores. 

What type of configuration are you interested in doing?

**Comment by yywangvr** [comment]
Hello @richardliaw , thanks for the answers. 

I am new to learn Ray.tune and I don't have the configuration yet. Thank you.

If I only have 4 cores in local laptop, it will run 4 trials in parallel and put the rest in the queue, right?
