### ISSUE TITLE
Can not import HEBOSearch

### ISSUE THREAD

**Issue by zrajabi** [ray-project/ray#14642]
I have installed the latest ray on Google Colab pro, and want to do optimization using hero, but import fails:
from ray.tune.suggest.hebo import HEBOSearch
>>> No module named 'HEBO'

from hebo.optimizers.hebo import HEBO
>>> is successful

Could you please help me why I can not import it from ray?

**Comment by richardliaw** [comment]
Can you post a longer stack trace?

did you install the right HEBO? https://pypi.org/project/HEBO/

cc @Yard1

**Comment by Yard1** [comment]
Have you installed Ray 1.2.0 or the nightly 2.0.0 wheel?

**Comment by zrajabi** [comment]
I have installed the following version Ray 1.20:
! pip install ray==1.2.0
Successfully installed aiohttp-3.7.4.post0 aiohttp-cors-0.7.0 aioredis-1.3.1 async-timeout-3.0.1 blessings-1.7 colorama-0.4.4 colorful-0.5.4 gpustat-0.6.0 hiredis-1.1.0 multidict-5.1.0 opencensus-0.7.12 opencensus-context-0.1.2 py-spy-0.3.4 ray-1.2.0 redis-3.5.3 yarl-1.6.3

! pip install HEBO:
Successfully installed GPy-1.9.9 HEBO-0.1.0 cma-2.7.0 gpytorch-1.4.0 paramz-0.9.5 pymoo-0.4.2.2

but when I want to import HEBOSearch using:

from ray.tune.suggest.hebo import HEBOSearch

I get this error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-8b0484be2e23> in <module>()
      1 
----> 2 from ray.tune.suggest.hebo import HEBOSearch
ModuleNotFoundError: No module named 'ray.tune.suggest.hebo'

**Comment by zrajabi** [comment]
Ok, the nightly version worked which is ray-2.0.0.dev0:
!pip install https://s3-us-west-2.amazonaws.com/ray-wheels/master/ba6cebe30fab6925e5b2d9e859ad064d53015246/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

Thanks for the help @Yard1!

**Comment by Yard1** [comment]
Yeah HEBO is not present in 1.2.0. Glad it's solved!

**Comment by qo4on** [comment]
I used this link:
```
!pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
```
But got a warning:
```
/usr/local/lib/python3.7/dist-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
```
How can I fix this?

**Comment by qo4on** [comment]
Thanks. For Kaggle it turned out to be a bit more complicated:
```
!pip install -U tensorboardX HEBO > /dev/null
!pip install "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl" > /dev/null
!pip uninstall -y dataclasses > /dev/null
```
