### ISSUE TITLE
[rllib] KeyError when "skipping" agent steps

### ISSUE THREAD

**Issue by ejunprung** [ray-project/ray#14653]
### What is the problem?

In multi-agent configurations, we "skip" agents when any particular agent does not require an action at a given point in time. This worked fine in Ray 1.0.0 but in Ray 1.2.0, it throws a KeyError.

```
  File "/mnt/c/Users/edwar/Desktop/testing/conda/lib/python3.7/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 445, in episode_step
    episode = self.episodes[episode_id]
KeyError: 20694229
```

According to https://docs.ray.io/en/master/rllib-env.html#multi-agent-and-hierarchical, I believe this behavior should be allowed.

```
# Observations are a dict mapping agent names to their obs. Only those
# agents' names that require actions in the next call to `step()` will
# be present in the returned observation dict.
```

**Ray 1.2.0
Tensorflow 2.3.1
Ubuntu WSL**

### Reproduction (REQUIRED)
```
import glob, gym, numpy, ray, sys, os
import numpy as np
from ray.rllib.env import MultiAgentEnv
from ray.rllib.agents.registry import get_agent_class

class Environment(MultiAgentEnv):
    def __init__(self, env_config):
        self.action_space = gym.spaces.Discrete(2)
        self.observation_space = gym.spaces.Box(0, 1, numpy.array([1]), dtype=numpy.float32)
    def reset(self):
        self.steps = 0

        obsdict = {}
        for i in range(0, 2):
            # Skip step
            if self.steps % 2 == 0:
                continue
            obsdict[str(i)] = numpy.array([0])
        return obsdict

    def step(self, action):
        self.steps + 1

        for i in range(0, 2):
            # Skip step
            if self.steps % 2 == 0:
                continue
            act = action[str(i)]
            actionArray = act.astype(numpy.float32)

        obsdict = {}
        rewarddict = {}
        donedict = {}
        for i in range(0, 2):
            # Skip step
            if self.steps % 2 == 0:
                continue
            obsdict[str(i)] = numpy.array([0])
            rewarddict[str(i)] = 0
            donedict[str(i)] = False
        donedict['__all__'] = False
        return obsdict, rewarddict, donedict, {}

ray.init()

trials = ray.tune.run(
    'PPO',
    stop={
         'training_iteration': 100
    },
    config = {
        'env': Environment,
        'no_done_at_end': True,
        'horizon': 2000
    }
)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this @ejunprung . I can reproduce this. ...

**Comment by sven1977** [comment]
One thing, though, your env never produces any observations, ever (you probably mean to do `self.steps += 1` not `self.steps + 1`).
This can be fixed - I guess - by just returning prematurely in the `SampleCollector.episode_step` method iff the episode hasn't even been stepped yet by any agents, circumventing the key error.

So as a workaround: Can you try adding this if block at the beginning of:
ray/rllib/evaluation/collectors/simple_list_collector.py::~444:

```
    @override(SampleCollector)
    def episode_step(self, episode_id: EpisodeID) -> None:
        # <<--HERE-->>
        if episode_id not in self.episodes:
            return
        # <<--END-->>

        episode = self.episodes[episode_id]
```

**Comment by ejunprung** [comment]
@sven1977 Oops, sorry. Typo.

That if block and it fixes the problem. Thank you so much. We are going to apply a hotfix on our end for now so we're all set!

**Comment by sven1977** [comment]
Great! I'll also provide a PR with a fix in a sec ...

**Comment by sven1977** [comment]
PR: https://github.com/ray-project/ray/pull/14765
