### ISSUE TITLE
Install Ray on offline ubuntu system

### ISSUE THREAD

**Issue by ryaghmaie1** [ray-project/ray#14669]
Hi Ray team,
I am trying to install Ray on an ubuntu linux system that does not have internet. I have Python 3.6.9 built with numpy, mat4py, ...

- I tried to use the .whl on the website for linux cp36 and it complained that it was not supported on my linux system.
- I cloned the GitHub repo and tried to install using "sudo apt-get install ray". It seems it installed it. See below, however it is not installed because importing ray in a test.py files prompts an error:
**-------------------------------error in importing ray---------------------------------------**
  File "test.py", line 2, in <module>
    import ray
  File "external_packages/Ray/ray/python/ray/__init__.py", line 63, in <module>
    import ray._raylet  # noqa: E402
**------------------------------sudo installation----------------------------------------**
- ry189:~/external_packages/Ray/ray/python$ sudo apt-get install ray
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ray is already the newest version (2.3.1-5).
The following packages were automatically installed and are no longer required:
  default-jdk default-jdk-headless linux-headers-4.18.0-21 linux-headers-4.18.0-21-generic linux-headers-5.0.0-37 linux-headers-5.0.0-37-generic
  linux-image-4.18.0-21-generic linux-image-5.0.0-37-generic linux-modules-4.18.0-21-generic linux-modules-5.0.0-37-generic linux-modules-extra-4.18.0-21-generic
  linux-modules-extra-5.0.0-37-generic openjdk-11-jdk openjdk-11-jdk-headless
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Appreciate your prompt help on this,
Regards,
Ray

**Comment by geraint0923** [comment]
I don't think ray currently support `apt-get` installation. You can follow this [installation guide](https://docs.ray.io/en/master/installation.html) or [this build-from-source guide](https://docs.ray.io/en/master/development.html#building-ray) given that your computer doesn't have the internet.
