### ISSUE TITLE
[tune] not using GPU for HEBO Optimization

### ISSUE THREAD

**Issue by zrajabi** [ray-project/ray#14674]
### What is the problem with gpu utilization on HEBO Search? 

@richardliaw @Yard1 
I am tuning using HEBO on Google Colab with 16G GPU, I import and run the tuner, I set resources_per_trial={"cpu": 2, "gpu": 1} but inside the objective I checked that GPUs is not utilized at all. I get the following warning which will be an error if I have .to(device) for model

/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 101: invalid device ordinal (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
(pid=1220)   return torch._C._cuda_getDeviceCount() > 0

I didn't have this kind of error when I used bayesian-optimization.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray-2.0.0.dev0
Python 3.7.10
Pytorch: 1.8.0+cu101

### Reproduction (REQUIRED)
```
def fn_objective(config):
  
  import torch
  from torch import device 
  from sklearn.metrics import f1_score

  device = device("cuda:0" if torch.cuda.is_available() else "cpu")
  print(device)
  print(True)
  i = 0
  EPOCHS = hparams_tmp.epochs 
  checkpoint_dir = []
  TH = config['TH']
  best_val_acc = 0
  best_val_loss = 0
  
  df = pd.concat([data , dev ])
  RANDOM_SEED = config['RANDOM_SEED']
 
  RANDOM_SEED = random.randint(0, 100)
  torch.cuda.manual_seed(RANDOM_SEED)

  df_train, df_val = train_test_split(df, test_size=0.1, random_state = RANDOM_SEED, shuffle = True) 
  train_data_loader = create_data_loader(df_train, tokenizer, MAX_LEN )
  val_data_loader = create_data_loader(df_val, tokenizer, MAX_LEN )
  test_data_loader = create_data_loader(test, tokenizer, MAX_LEN )

  print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
  print(torch.cuda.device_count())
  model = EmotionClassifier(n_classes).to(device) 
 
  alpha, beta, gamma = config['alpha'], config['beta'], config['gamma'].sample() 
  cb =  True 
  pw = True  
  print(alpha, beta, gamma)
  
  loss_fn = FocalLoss(alpha, beta, gamma, CB = cb, PW = pw, logits=True, reduce= True).to(device) 
  lr = config['lr'].sample()
  total_steps = len(train_data_loader) * hparams_tmp.epochs 
  optimizer = AdamW(model.parameters(), lr = lr, weight_decay=1e-2, correct_bias=False) 
  
  for epoch in range(EPOCHS):
    print('inside loop')
    import torch, gc
    gc.collect()
    torch.cuda.empty_cache()
    train_acc, train_loss = train_epoch(model, train_data_loader, loss_fn, optimizer, device, n_classes, TH)
    print(train_acc)
    val_acc, val_loss, y_pred, y_pred_probs, y_true, F1_micro, F1_macro, F1_weighted = eval_model( model, val_data_loader, loss_fn, device, TH)
    if val_acc > best_val_acc:
      best_val_acc = val_acc
      best_val_loss = val_loss
  print(f'Epoch {epoch + 1}/{EPOCHS}')
  print(f'Train loss for model {i+1} {train_loss} accuracy {train_acc}')
  print(f'Val loss for model {i+1} {val_loss} accuracy {val_acc}')
  tune.report(loss = val_loss, accuracy = val_acc,  F1_micro = F1_micro, F1_macro =  F1_macro, F1_weighted = F1_weighted )

##### Main ######
from ray.tune.schedulers import AsyncHyperBandScheduler
from ray.tune.suggest.hebo import HEBOSearch
from hebo.design_space.design_space import DesignSpace
  
config = {
      'TH': tune.uniform(0.3,0.5),
      'lr': tune.loguniform(2e-5, 5e-5) ,
      'alpha': tune.uniform(0.5,2.0),
      'beta': tune.uniform(0.99,0.9999),
      'gamma': tune.uniform(0.5,2.0),
      'RANDOM_SEED': tune.choice([0, 100]) 
      }
  max_concurrent = 8 # maximum number of concurrent trials
  algo = HEBOSearch(points_to_evaluate = points_to_evaluate, 
                    random_state_seed=123, 
                    max_concurrent=max_concurrent,
                    #metric="mean_loss", mode="min",
                    )
  scheduler = AsyncHyperBandScheduler()

result = tune.run(fn_objective,
                  metric="loss",
                  mode="min",
                  search_alg=algo,
                  scheduler=scheduler,
                  num_samples=1,
                  resources_per_trial={"cpu": 2, "gpu": 1},
                  config=config, 
                  checkpoint_at_end=True, 
                  )
```

**Comment by Yard1** [comment]
It's possible something is messing things up inside HEBO. Can you try with:
```python
HEBOSearch(points_to_evaluate = points_to_evaluate,
	  random_state_seed=123,
	  max_concurrent=max_concurrent,
	  model_name="gp",
)
```
?

**Comment by Yard1** [comment]
One more thing, can you try reinstalling pytorch, making sure it's with GPU support? It's possible that HEBO has overwritten it.

**Comment by zrajabi** [comment]
@Yard1 I think have Gpu support, this is the whole error trace:
HyperOpt has also shows the same error.

== Status ==
Memory usage on this node: 3.6/12.7 GiB
Using AsyncHyperBand: num_stopped=0 Bracket: Iter 64.000: None | Iter 16.000: None | Iter 4.000: None | Iter 1.000: None
Resources requested: 1.0/2 CPUs, 1.0/1 GPUs, 0.0/7.33 GiB heap, 0.0/3.66 GiB objects (0.0/1.0 accelerator_type:P100)
Result logdir: /root/ray_results/fine_tune_base_models_01_2021-03-14_22-08-12
Number of trials: 2/10 (1 PENDING, 1 RUNNING)

Trial name | status | loc | RANDOM_SEED | TH | alpha | beta | gamma | lr
-- | -- | -- | -- | -- | -- | -- | -- | --
fine_tune_base_models_01_c4c9679a | RUNNING |   | 37 | 0.362342 | 0.5 | 0.99 | 1 | 3.22e-05
fine_tune_base_models_01_c4cda44a | PENDING |   | 37 | 0.420223 | 0.5 | 0.99 | 2 | 3.83e-05


(pid=8915) /usr/local/lib/python3.7/dist-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
(pid=8915)   warnings.warn(warning.format(ret))
(pid=8915) 2021-03-14 22:08:23,746	ERROR function_runner.py:254 -- Runner Thread raised error.
(pid=8915) Traceback (most recent call last):
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 248, in run
(pid=8915)     self._entrypoint()
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 316, in entrypoint
(pid=8915)     self._status_reporter.get_checkpoint())
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 580, in _trainable_func
(pid=8915)     output = fn()
(pid=8915)   File "<ipython-input-18-283c767c6203>", line 47, in fine_tune_base_models_01
(pid=8915)   File "<ipython-input-6-b60ba684a73c>", line 18, in train_epoch
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
(pid=8915)     result = self.forward(*input, **kwargs)
(pid=8915)   File "<ipython-input-7-acb1c2afe671>", line 45, in forward
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 170, in _lazy_init
(pid=8915)     torch._C._cuda_init()
(pid=8915) RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 101: invalid device ordinal
(pid=8915) Exception in thread Thread-2:
(pid=8915) Traceback (most recent call last):
(pid=8915)   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
(pid=8915)     self.run()
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 267, in run
(pid=8915)     raise e
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 248, in run
(pid=8915)     self._entrypoint()
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 316, in entrypoint
(pid=8915)     self._status_reporter.get_checkpoint())
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 580, in _trainable_func
(pid=8915)     output = fn()
(pid=8915)   File "<ipython-input-18-283c767c6203>", line 47, in fine_tune_base_models_01
(pid=8915)   File "<ipython-input-6-b60ba684a73c>", line 18, in train_epoch
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
(pid=8915)     result = self.forward(*input, **kwargs)
(pid=8915)   File "<ipython-input-7-acb1c2afe671>", line 45, in forward
(pid=8915)   File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 170, in _lazy_init
(pid=8915)     torch._C._cuda_init()
(pid=8915) RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 101: invalid device ordinal
(pid=8915) 
2021-03-14 22:08:24,022	ERROR trial_runner.py:727 -- Trial fine_tune_base_models_01_c4c9679a: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 697, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 678, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1430, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.

**Comment by zrajabi** [comment]
ALSO, print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids())) returns []

**Comment by Yard1** [comment]
And this doesn't happen if you don't install HEBO, correct?

**Comment by zrajabi** [comment]
@Yard1 yes, I used to run random search and bayesian-optimization from ray using gpu. Now, it doesn't see any CUDA within the objectives.
Out of the scope of tune.run, it sees the gpu but inside the runner (function), gpu is invisible. Just tried this example from ray:

https://docs.ray.io/en/latest/tune/examples/hyperopt_example.html 

put the following within objective function:
print('torch.cuda.is_available',torch.cuda.is_available() ,torch.cuda.device_count())
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    from torch import device 
    device = device("cuda:0" if torch.cuda.is_available() else "cpu")
 here is what I get:
>>> torch.cuda.is_available is False
>>> ray.get_gpu_ids(): [0, 0]

**Comment by Yard1** [comment]
I am not that familiar with Colab, I assume it comes with pytorch pre-installed, right? In that case, can you restart the environment and try this (after installing ray and any other packages):
`pip install pymoo gpytorch GPy` and then `pip install --no-dependencies HEBO`

I believe the issue is with HEBO's torch (no gpu support) overwriting colab's torch, and if I am correct, this should prevent this.

Aside from that it would be good to check if random search still works without installing HEBO, just to make sure the issue is actually with HEBO and not something else which could have broken since you last ran this.

**Comment by Yard1** [comment]
Closing as stale.
