### ISSUE TITLE
[docker] no cuda device availabel in pytorch

### ISSUE THREAD

**Issue by Sertingolix** [ray-project/ray#14683]
### What is the problem?

The latest docker builds for ray-ml do not support the gpu with torch.

Note: tensorflow works

### Reproduction (REQUIRED)

`docker run --gpus all -it rayproject/ray-ml:nightly-gpu python -c "import torch; print(torch.cuda.is_available())"`

outputs false

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Sertingolix** [comment]
Apparently the cpu version is installed in this container. I'm not sure if this is intended behavior to keep the image size small. In the meantime you can install torch gpu in the running container or build a new one with the following docker file:

[Dockerfile.txt](https://github.com/ray-project/ray/files/6140905/Dockerfile.txt)

**Comment by ijrsvt** [comment]
@Sertingolix Thanks for bringing this up! I was under the impression that installing [`torch+cu110`](https://github.com/ray-project/ray/blob/master/python/requirements_ml_docker.txt) was sufficient for GPU support (it is done [here](https://github.com/ray-project/ray/blob/master/python/requirements_ml_docker.txt)).

I will look into getting this working!

**Comment by Sertingolix** [comment]
I would have assumed that too. Maybe there is another torch dependency. 
Happy to help. rllib is great :)
