### ISSUE TITLE
torch load model

### ISSUE THREAD

**Issue by sikiyu27** [ray-project/ray#14682]
model=torch.jit.load("model.pt")
print(model(x))

error

RuntimeError: forward() Expected a value of type 'Dict[str, Tensor]' for argument 'argument_1' but instead found type 'UsageTrackingDict'.
Declaration: forward(torch.Agent.hierarchical.cnn_skill.CNNetwork self, Dict(str, Tensor) argument_1, Tensor[] argument_2, Tensor argument_3) -> ((Tensor, Tensor[]))
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

**Comment by DmitriGekhtman** [comment]
Could you provide more details on your Ray environment -- operating system, Ray version, any other details that could aid in reproduction of the problem?
