### ISSUE TITLE
torch export_model and load model

### ISSUE THREAD

**Issue by sikiyu27** [ray-project/ray#14681]
model=torch.jit.load("model.pt")
print(model(x))

error

RuntimeError: forward() Expected a value of type 'Dict[str, Tensor]' for argument 'argument_1' but instead found type 'UsageTrackingDict'.
Declaration: forward(__torch__.Agent.hierarchical.cnn_skill.CNNetwork self, Dict(str, Tensor) argument_1, Tensor[] argument_2, Tensor argument_3) -> ((Tensor, Tensor[]))
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

**Comment by zhuhj-tery** [comment]
Hello,
I also encounter the similar problem and I'm wondering how you make it works.
Thank you very much in advance.
