### ISSUE TITLE
Pyarrow import error after installation

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1468]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.12
- **Ray installed from (source or binary)**: Source
- **Ray version**: Unclear (for reasons to follow)
- **Python version**: 3.5.4
- **Exact command to reproduce**: python setup.py develop

### Describe the problem
After running python setup.py develop I get this error:  

Traceback (most recent call last):
  File "runtest.py", line 13, in <module>
    import ray
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/Users/eugenevinitsky/Desktop/Research/Bayen/Code/ray-test/flow_ray/python/ray/pyarrow_files/pyarrow/__init__.py", line 32, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: No module named 'pyarrow.lib'

**Comment by eugenevinitsky** [comment]
Note, upgrading to python 3.6 resolved this issue.

**Comment by pcmoritz** [comment]
Hey, thanks for reporting! I'm glad this is resolved, if it comes back we should look into it more. We are shipping our own version of pyarrow with Ray [1], so this should not be happening. But there could be something in the Python configuration that makes it behave differently, so if more people run into this (or you run into it again) it would be good to know and fix.

[1] https://github.com/ray-project/ray/blob/master/python/ray/__init__.py#L15

**Comment by robertnishihara** [comment]
Hmm, it's probably not related to the Python version. We recently updated the version of Arrow that we're using (this morning), so that could have something to do with it if you did a git pull in the Ray repository or something like that.

Closing for now, but please reopen this if you see this issue again or know how to reproduce it.
