### ISSUE TITLE
[rllib] rollout_fragment_length using count_steps_by parameter

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#14689]
The rollout_fragment_length parameter should be counted in environment_steps, not agent_steps.

The utility of the count_steps_by parameter is to maintain fixed-size batches (e.g. consistent memory usage) in variable-agent environments. Using agent_steps to compute rollout_fragment_length will result in mixed-size fragments and inconsistent LSTM backpropagation horizons.

Ray version: all, including today's nightly. Tested on Ubuntu 20.04

**Comment by sven1977** [comment]
@jsuarez5341 , wait, wasn't this the exact purpose of `agent_steps`? To have equally sized batches, no matter how many agents step at the same time and in which frequency?
You can still get the agent_steps from a MultiAgentBatch (even with `count_steps_by=env_steps`) by calling `multi_agent_batch.agent_steps()`.

**Comment by jsuarez5341** [comment]
> @jsuarez5341 , wait, wasn't this the exact purpose of `agent_steps`? To have equally sized batches, no matter how many agents step at the same time and in which frequency?
> You can still get the agent_steps from a MultiAgentBatch (even with `count_steps_by=env_steps`) by calling `multi_agent_batch.agent_steps()`.

Hmm I see what you mean. Yes, we want equally sized batches. The only issue is that rollout_fragment_length caps the LSTM backpropagation horizon. I suppose that, as a rule of thumb, rollout_fragment_length > max_agents * max_seq_len ? That might solve the problem, will run some tests and circle back.
