### ISSUE TITLE
[doc] Add Ray Use Case Section

### ISSUE THREAD

**Issue by mGalarnyk** [ray-project/ray#14702]
### What is the problem?

The docs don't have a use case section. I would like to add one. One option is in the [What is Ray] section.  It would be next to  sections for [Blog and Press](https://docs.ray.io/en/master/#blog-and-press) and [Talks (Videos)](https://docs.ray.io/en/master/#talks-videos).

Some links would include: 

- [Ray, Amazon] [Introducing Amazon SageMaker Reinforcement Learning Components for open-source Kubeflow pipelines](https://aws.amazon.com/blogs/machine-learning/introducing-amazon-sagemaker-reinforcement-learning-components-for-open-source-kubeflow-pipelines/) 
- [Ray, Ant Group] [Online Resource Allocation with Ray at Ant Group](https://www.anyscale.com/blog/online-resource-allocation-with-ray-at-ant-group)
- [Ray, Uber] [Elastic Deep Learning with Horovod on Ray](https://eng.uber.com/horovod-ray/)

Is there a better idea out there for a use case section?

**Comment by mGalarnyk** [comment]
Accidentally  added the labels.

**Comment by mGalarnyk** [comment]
Can I open a PR for this?

**Comment by rkooo567** [comment]
@mGalarnyk Please do so!! I think it is very important for the adoption
