### ISSUE TITLE
Ray Serve SimpleQueue objects should only be shared between processes through inheritance

### ISSUE THREAD

**Issue by Nanda-Nandan** [ray-project/ray#14717]
### Adding logger object inside backend class raising above error

I am using the code fastapi with ray serve code snippet.
since debugging is not possible even with local mode i used logger to debug,but i am facing issue while adding logger too

```
import ray
from ray import serve
from fastapi import FastAPI
import uvicorn
from transformers import pipeline
from pydantic import BaseModel
from loguru import logger
import os
import time

app = FastAPI()

serve_handle = None

file_path = os.path.abspath(__file__)
project_dir = os.path.dirname(file_path)
log_dir = os.path.join(project_dir, 'Logs')
t = time.strftime("%y_%m_%d")

logger.add(f"{log_dir}/dev_{t}.log", rotation="500mb", encoding="utf-8", enqueue=True, retention="10 days")



@app.on_event("startup")  # Code to be run when the server starts.
async def startup_event():
    # ray.init(address="auto",_redis_password='5241590000000000',local_mode=True, num_cpus=5,num_gpus=1)  # Connect to the running Ray cluster.
    ray.init(num_cpus=5,num_gpus=1)  # Connect to the running Ray cluster.
    client = serve.start()  # Start the Ray Serve client.

    # Define a callable class to use for our Ray Serve backend.
    class GPT2:
        def __init__(self):
            self.nlp_model = pipeline("text-generation", model="gpt2")
            self.logger = logger

        async def __call__(self, request):
            self.logger.info(f"request parameter {request}", request = request)
            text = self.nlp_model(await request.body(), max_length=50)

            return text

    # Set up a backend with the desired number of replicas.
    backend_config = serve.BackendConfig(num_replicas=1)
    client.create_backend("gpt-2", GPT2, config=backend_config)
    client.create_endpoint("generate", backend="gpt-2")

    # Get a handle to our Ray Serve endpoint so we can query it in Python.
    global serve_handle
    serve_handle = client.get_handle("generate")




@app.get("/generate")
async def generate(query: str):
    logger.info(f"request parameter {query}", request = query)
    return await serve_handle.remote(query)
if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8081)

```
In this code if i am commenting self.logger.info(f"request parameter {request}", request = request)  in GPT2 class it is working fine, but when uncommenting the above error occurs.

**Comment by edoakes** [comment]
@Nanda-Nandan could you please post the full stack trace of the error that you're getting?

**Comment by Nanda-Nandan** [comment]
**Thanks for quick response,Here it is**

ERROR:    Traceback (most recent call last):
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/home/nanda/Study/code/rayexample/facemask_fastapiray.py", line 51, in startup_event
    client.create_backend("gpt-2", GPT2, config=backend_config)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serve/api.py", line 62, in check
    return f(self, *args, **kwargs)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serve/api.py", line 408, in create_backend
    self._controller.create_backend.remote(backend_tag, backend_config,
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/actor.py", line 109, in remote
    return self._remote(args, kwargs)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/actor.py", line 150, in _remote
    return invocation(args, kwargs)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/actor.py", line 139, in invocation
    return actor._actor_method_call(
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/actor.py", line 823, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
  File "python/ray/_raylet.pyx", line 1258, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 1263, in ray._raylet.CoreWorker.submit_actor_task
  File "python/ray/_raylet.pyx", line 298, in ray._raylet.prepare_args
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serialization.py", line 319, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serialization.py", line 299, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serialization.py", line 259, in _serialize_to_pickle5
    raise e
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/serialization.py", line 255, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/nanda/Study/environments/dl/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 574, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 347, in __getstate__
    context.assert_spawning(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance

ERROR:    Application startup failed. Exiting.
(pid=4330) INFO:     Started server process [4330]

**Comment by simon-mo** [comment]
@Nanda-Nandan can we try move `from loguru import logger` and the setup `logger` into the init method of the GPT2 backend?

**Comment by Nanda-Nandan** [comment]
I have moved like below

```
    class GPT2:
        def __init__(self):
            from loguru import logger
            file_path = os.path.abspath(__file__)
            project_dir = os.path.dirname(file_path)
            log_dir = os.path.join(project_dir, 'Logs')
            t = time.strftime("%y_%m_%d")

            logger.add(f"{log_dir}/dev_{t}.log", rotation="500mb", encoding="utf-8", enqueue=True, retention="10 days")
            self.nlp_model = pipeline("text-generation", model="gpt2")
            self.logger = logger

        async def __call__(self, request):
            self.logger.info(f"request parameter {request}", request = request)
            text = self.nlp_model(await request.body(), max_length=50)

            return text
```
It is working fine now,but still i didnt  get the reason behind it.

- Do we need to use different logger or different object if we want to use both outside backend class or inside backend class, i mean to say in case of 2 different backend classes i have to do same in both classes ?
- 
- This is not related to  the problem above,Is there any simpler method to debug these type of scenario apart from pdb, i mean visual debug like using pycharm or vscode?

**Comment by simon-mo** [comment]
because the backend class is running inside another process, you have to initialize the logger separately. 

you can use `ray.util.check_serialize.inspect_serializability` utility to check the backend class is serialization or not.
https://github.com/ray-project/ray/blob/master/python/ray/util/check_serialize.py#L131

**Comment by Nanda-Nandan** [comment]
okay then what i should do whn i will create a composed backend and i want to log composed backend,backend1,backend2 using same logger,because in whole application i want to use one logger ?

```
@app.on_event("startup")  # Code to be run when the server starts.
async def startup_event():
    # ray.init(address="auto",_redis_password='5241590000000000',local_mode=True, num_cpus=5,num_gpus=1)  # Connect to the running Ray cluster.
    ray.init(num_cpus=5,num_gpus=1)  # Connect to the running Ray cluster.
    client = serve.start()  # Start the Ray Serve client.

    def detector_model(request):
        print("Model 1 called with data ", request.query_params.get("data"))
        return random()

    def mask_model(request):
        print("Model 2 called with data ", request.query_params.get("data"))
        return request.query_params.get("data")

    class ComposedModel:
        def __init__(self):
            client = serve.connect()
            self.detector_model = client.get_handle("detector_model")
            self.mask_model = client.get_handle("mask_model")

        # This method can be called concurrently!
        async def __call__(self, starlette_request):
            data = await starlette_request.body()
            print(data)
            score = await self.detector_model.remote(data=data)
            if score > 0.5:
                result = await self.mask_model.remote(data=data)
                result = {"model_used": 2, "score": score}
            else:
                result = {"model_used": 1, "score": score}

            return result

    # Set up a backend with the desired number of replicas.

    client.create_backend("mask_model", mask_model)
    client.create_endpoint("mask_model", backend="mask_model")

    client.create_backend("detector_model", detector_model)
    client.create_endpoint("detector_model", backend="detector_model")

    backend_config = serve.BackendConfig(num_replicas=1)
    client.create_backend("composed_backend", ComposedModel, config=backend_config)
    client.create_endpoint("generate", backend="composed_backend")

    # max_concurrent_queries is optional. By default, if you pass in an async
    # function, Ray Serve sets the limit to a high number.
    # client.create_backend(
    #     "composed_backend", ComposedModel, config={"max_concurrent_queries": 10})
    # client.create_endpoint(
    #     "composed", backend="composed_backend", route="/composed")

    # Get a handle to our Ray Serve endpoint so we can query it in Python.
    global serve_handle
    serve_handle = client.get_handle("generate")


@app.get("/generate")
async def generate(query: str):
    print(query)
    return await serve_handle.remote(query)

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8081)
# Our pipeline will be structured as follows:
```
like in above code if i want use use same logger for ComposedModel,detector_model,mask_model which is 3 different backends how i can do using same logger ?

**Comment by simon-mo** [comment]
This code should work for stdlib logger but i'm not sure why it won't work for logrus logger

**Comment by Nanda-Nandan** [comment]
using loggingthe error is not coming,but its not able to log
