### ISSUE TITLE
[Core] Delayed task replies when actor FO happens cause subsequent task failures

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#14727]
According to https://github.com/ray-project/ray/blob/6e326cc23933c64e203691a7946c105ecb896eea/src/ray/core_worker/transport/direct_actor_transport.cc#L162-L168, this is a known issue but hasn't been addressed. 

We recently observed this bug in our internal repo. In our case, an actor crashed and a failover is triggered, but the RPC connection between the caller and the actor is still alive. After about 1s, the actor is alive again and the caller connects to the new actor instance. At this time, there are still 2 task replies that haven't returned (they returned with errors after about 10s). Now new tasks are sent to the actor continuously but `ray.get()` on these tasks never returns.

There are two issues here.

1) the sequence number of the first task sent after the actor is alive again is not 0, so the callee won't execute the task and waits for a task with seq no 0 (which doesn't exist).

2) If the caller periodically (<30s) submits new tasks to the new actor instance, the `OnSequencingWaitTimeout` function will never be executed. So all tasks received by the new actor instance will be kept in `ActorSchedulingQueue` and no reply with "Cancelling stale RPC" message is sent back to the caller.

> Changing the expiry time of a timer while there are pending asynchronous waits causes those wait operations to be cancelled.

I believe this is the reason for `OnSequencingWaitTimeout` not getting called.

Repro script:

```python
@pytest.mark.parametrize(
    "ray_start_cluster_head", [{
        "num_cpus": 0
    }], indirect=True)
def test_actor_failover_with_bad_network(ray_start_cluster_head):
    # The test case is to cover the scenario that when an actor FO happens,
    # the caller receives the actor ALIVE notification and connects to the new
    # actor instance while there are still some tasks sent to the previous
    # actor instance haven't returned.
    #
    # It's not easy to reproduce this scenario, so we use SIGSTOP to pause the
    # previous actor process to keep the RPC connection alive while killing
    # the node to trigger actor failover. Later we send SIGKILL to kill the
    # previous actor process to let the task fail.
    #
    # The expected behavior is that after the actor is alive again and the
    # previous RPC connection is broken, tasks sent via the previous RPC
    # connection should fail but tasks sent via the new RPC connection should
    # succeed.

    cluster = ray_start_cluster_head
    node = cluster.add_node(num_cpus=1)

    @ray.remote(max_restarts=1)
    class Actor:
        def getpid(self):
            return os.getpid()

    # The actor should be placed on the non-head node.
    actor = Actor.remote()
    pid = ray.get(actor.getpid.remote())

    # Pause the actor process.
    os.kill(pid, signal.SIGSTOP)
    time.sleep(1)

    # Submit a task (task 1) to the actor while it is paused. The return
    # object should be unready.
    obj1 = actor.getpid.remote()
    with pytest.raises(GetTimeoutError):
        ray.get(obj1, timeout=1)

    # Kill the non-head node and start a new one.
    cluster.remove_node(node, allow_graceful=False)
    cluster.add_node(num_cpus=1)

    # Now GCS should trigger actor FO. Wait for the actor to be alive.
    def check_actor_restart():
        actors = list(ray.actors().values())
        assert len(actors) == 1
        return (actors[0]["State"] == ray.gcs_utils.ActorTableData.ALIVE
                                      and actors[0]["NumRestarts"] == 1)

    wait_for_condition(check_actor_restart)

    # Kill the previous actor process.
    os.kill(pid, signal.SIGKILL)

    # Now we should be able to get the return value of task 1, which raises
    # an error.
    with pytest.raises(RayActorError):
        ray.get(obj1)

    # Submit new tasks to the actor. We should be able to get these return
    # values without any issue.
    new_objs = []
    while True:
        new_objs += [actor.getpid.remote()]
        try:
            ray.get(new_objs[0], timeout=10)
            new_objs = new_objs[1:]
            if len(new_objs) == 0:
                break
        except GetTimeoutError:
            # Ignore the timeout error here to reproduce the issue that
            # objects will never be ready.
            pass
        time.sleep(10)
```

We expect the test case to finish within a short time but actually, it never ends.

**Comment by kfstorm** [comment]
@stephanie-wang @ericl , cc @raulchen @MissiontoMars @ashione @jovany-wang

**Comment by kfstorm** [comment]
@stephanie-wang Any thoughts about this?

**Comment by stephanie-wang** [comment]
I don't have time to take this on at the moment, but perhaps you could, @kfstorm? Looks like one fix might be to fail outstanding RPCs to the previous version of the actor.

**Comment by kfstorm** [comment]
@stephanie-wang Do you mean we forcibly invoke the reply callback and store a `RayActorError` exception to the return object for every outstanding task on actor restarting notification arrives?
