### ISSUE TITLE
[rllib] The Monitor wrapper records training episodes instead of evaluation

### ISSUE THREAD

**Issue by vakker** [ray-project/ray#14734]
### What is the problem?

Ray: 2.0.0.dev0 (897b84b)
Python: 3.8

The [doc](https://docs.ray.io/en/master/rllib-training.html#common-parameters) suggests that using `record_env` saves videos from the evaluation. However, it seems that all the training episodes are saved and none of the evaluation ones. This makes training slow and it doesn't capture what was intended.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```python
import gym
import numpy as np
import ray
from gym.spaces import Box, Discrete
from ray import tune


class SimpleCorridor(gym.Env):
    metadata = {'render.modes': ['human', 'rgb_array']}

    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(0.0, self.end_pos, shape=(1, ), dtype=np.float32)

    def reset(self):
        self.cur_pos = 0
        return [self.cur_pos]

    def step(self, action):
        assert action in [0, 1], action
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
        elif action == 1:
            self.cur_pos += 1
        done = self.cur_pos >= self.end_pos
        return [self.cur_pos], 1.0 if done else -0.1, done, {}

    def render(self, mode="human"):
        img = np.random.randint(0, 256, size=(64, 64, 3), dtype=np.uint8)
        return img


if __name__ == "__main__":
    ray.init(local_mode=True)

    config = {
        "env": SimpleCorridor, 
        "evaluation_interval": 1,
        "env_config": {
            "corridor_length": 5,
        },
        "evaluation_num_episodes": 10,
        "num_workers": 1,
        "num_envs_per_worker": 1,
        "framework": "torch",
        "record_env": 'videos',
        "render_env": True,
    }

    stop = {"training_iteration": 3}
    results = tune.run('PPO', config=config, stop=stop)
```

Also, if I move the options under `evaluation_config` it still produces the same behaviour:
```python
    config = {
        "env": SimpleCorridor, 
        "evaluation_interval": 1,
        "env_config": {
            "corridor_length": 5,
        },
        "evaluation_num_episodes": 10,
        "evaluation_config": {
            "record_env": 'videos',
            "render_env": True,
        },
        "num_workers": 1,
        "num_envs_per_worker": 1,
        "framework": "torch",
    }
```

With this config I would expect to see 3x10 videos in `<trial log dir>/videos`, but I see 670 videos, and if I look into the `openaigym.episode_batch.0.2759844.stats.json` file it shows all the elements in `episode_types` as `'t'` (instead of `'e'`).

**Note**: without `local_mode=True` the script crashes at the end and doesn't save the stats and manifest files, but that's a separate issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Hey @vakker . Thanks for filing this. Videos should indeed be produced for the evaluation workers (unless maybe there are none).

**Comment by sven1977** [comment]
This PR fixes the problem (and many others related to recording, monitoring, rendering): 
https://github.com/ray-project/ray/pull/14796
