### ISSUE TITLE
[Dashboard] Reorganize dashboard modules

### ISSUE THREAD

**Issue by fyrestone** [ray-project/ray#14766]
We should reorganize the dashboard modules to make the structure more clear.

- Actor module
  - The `/logical/actor_groups` from logical_view.
  - The `/logical/actors` from logical_view.
  - Update actors from stats_collector.
- Node module is renamed from stats_collector

Also, we can move some control logic out of reporter module, such as `/api/launch_profiling`

Then, dashboard have these modules: job, actor, node, event, log, tune, reporter...

**Comment by hegdeashwin** [comment]
@fyrestone Recently, my team started exploring Ray.io and I was wondering how can I contribute to Ray, specially on Dashboard stuffs.

**Comment by fyrestone** [comment]
The dashboard provides data for two frontends: the old frontend(default) and new frontend. Here are some dashboard-related works:

- Refine the new frontend, and make it as the default frontend. There are many new frontend related issues that need to be fixed: https://github.com/ray-project/ray/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22New+Dashboard+Frontend%22
- Improve the dashboard backend: https://github.com/ray-project/ray/milestone/38, more features are going to be contributed to the community after this issue is fixed.

Currently, I am working on the job submission feature, which is also dashboard related: https://github.com/ray-project/ray/pull/15103

**Comment by richardliaw** [comment]
cc @edoakes do you have any suggestions for @hegdeashwin ?

**Comment by edoakes** [comment]
@hegdeashwin I'd say any of the issues in the milestones linked by @fyrestone would be a great place to start! Specifically both of these issues should be pretty small in scope:

- https://github.com/ray-project/ray/issues/13890
- https://github.com/ray-project/ray/issues/13889

Also, in general our testing for the dashboard is lacking so a good place to start might be to clean up & add more tests :)

**Comment by hegdeashwin** [comment]
Sure @edoakes. Sounds good. As a prerequisite currently, I'm begin with following things
1. I'm setting up dev environment
2. Understanding codebase

Any documentation or guidance on above would be great help. My email id is ashwin.hegde3@gmail.com in case required.

**Comment by hegdeashwin** [comment]
Cool, I found the documentation here https://docs.ray.io/en/master/getting-involved.html & https://docs.ray.io/en/master/development.html#building-ray

**Comment by hegdeashwin** [comment]
[Update], Followed the documentation and I was able to run Ray server on my local, also able to see the current & experimental dashboard

**Comment by richardliaw** [comment]
we've refactored the dashboard - closing because stale.
