### ISSUE TITLE
[Core] `max_calls=1` Causes WorkerStartup to Fail when processing many tasks

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#14776]
### What is the problem?
* This is the initial issue that caused be to open #14775. That issue is what I've run into while trying to repro this one.
* The error is a segfault here `ray::raylet::WorkerPool::StartProcess()`

* Exact logs are [here](https://gist.github.com/ijrsvt/ef320012aa5a143355dfb178331149bf)

*Ray version and other system information (Python version, TensorFlow version, OS):*
* Ray Version: 1.2.0
* Python Version: Python 3.7.7
* Docker Container: rayproject/ray:ray-deps:1.2.0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
```
[2021-03-16 23:36:27,224 W 85 85] node_manager.cc:410: Last heartbeat was sent 801 ms ago. There might be resource pressure on this node. If heartbeat keeps lagging, this node can be marked as dead mistakenly.
```

This sounds sketchy. It shouldn't happen anymore because the heartbeat is in a different thread. We might have some condition that overloads raylet when there are many tasks.

**Comment by wuisawesome** [comment]
Let's make sure #14775 doesn't fix this first before investigating.

**Comment by ericl** [comment]
I'm going to mark this as needs repro until that other issue is resolved.
