### ISSUE TITLE
[tune] Support resume in AxSearch

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#14779]
I am having the same problem using Ax. My experiment finished as expected after 20 trials, but I would like to continue tuning without rerunning those 20 configurations that were tested already.

_Originally posted by @Mr-Pepe in https://github.com/ray-project/ray/issues/14667#issuecomment-800185465_

**Comment by Mr-Pepe** [comment]
I was looking at implementing this but stumbled upon a general question.

What is the desired behavior for resuming a tuning? If the tuning run was interrupted unfinished trials should be run. That's what I think the current implementation tries to do. But what if the tuning run finished as expected and I want to run more trials with new configurations, using existing trials to warm-start the process? Right now I get a `TrialRunner resumed, ignoring new add_experiment.` message and no new trials are generated. 

Is this a feature request that has not come up yet and should be handled seperately?

**Comment by krfricke** [comment]
Closed by #18760

**Comment by krfricke** [comment]
@Mr-Pepe currently you can pass `points_to_evaluate` and `evaluated_results` to some of these searchers. I'll add a new issue to track this in https://github.com/ray-project/ray/issues/18847
