### ISSUE TITLE
[Core] `max_calls=1` crashes ray when many tasks are launched.

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#14775]
### What is the problem?
* Ray crashes with `overflow_cpu_instances[i] == 0 Should not be overflow` when launching many tasks with `max_calls=1`. Full error at bottom

*Ray version and other system information (Python version, TensorFlow version, OS):*
- Ray: 1.2.0 (and Ray 2.0.0)
- Python 3.7.7
- Docker: rayproject/ray-ml:1.2.0-gpu (but no GPUs used)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

On a machine with 2 CPUs (`m5.large`)

```
import ray
import time
ray.init()

@ray.remote(max_calls=1)
def one_sec():
    time.sleep(1)

for _ in range(60):
    one_sec.remote()
    one_sec.remote()
    time.sleep(0.5)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

```
(raylet) [2021-03-18 09:18:04,554 C 1068 1068] cluster_task_manager.cc:809:  Check failed: overflow_cpu_instances[i] == 0 Should not be overflow
(raylet) [2021-03-18 09:18:04,554 E 1068 1068] logging.cc:415: *** Aborted at 1616084284 (unix time) try "date -d @1616084284" if you are using GNU date ***
(raylet) [2021-03-18 09:18:04,555 E 1068 1068] logging.cc:415: PC: @                0x0 (unknown)
(raylet) [2021-03-18 09:18:04,555 E 1068 1068] logging.cc:415: *** SIGABRT (@0x42c) received by PID 1068 (TID 0x7fbd2d556800) from PID 1068; stack trace: ***
(raylet) [2021-03-18 09:18:04,555 E 1068 1068] logging.cc:415:     @     0x564ba40989ef google::(anonymous namespace)::FailureSignalHandler()
(raylet) [2021-03-18 09:18:04,556 E 1068 1068] logging.cc:415:     @     0x7fbd2d12c980 (unknown)
(raylet) [2021-03-18 09:18:04,556 E 1068 1068] logging.cc:415:     @     0x7fbd2c220fb7 gsignal
(raylet) [2021-03-18 09:18:04,556 E 1068 1068] logging.cc:415:     @     0x7fbd2c222921 abort
(raylet) [2021-03-18 09:18:04,556 E 1068 1068] logging.cc:415:     @     0x564ba3c36e9c _ZN3ray6RayLogD2Ev.cold
(raylet) [2021-03-18 09:18:04,557 E 1068 1068] logging.cc:415:     @     0x564ba3d3b11f ray::raylet::ClusterTaskManager::ReleaseCpuResourcesFromUnblockedWorker()
(raylet) [2021-03-18 09:18:04,558 E 1068 1068] logging.cc:415:     @     0x564ba3ce9737 ray::raylet::NodeManager::HandleDirectCallTaskBlocked()
(raylet) [2021-03-18 09:18:04,559 E 1068 1068] logging.cc:415:     @     0x564ba3ce97e9 ray::raylet::NodeManager::ProcessDirectCallTaskBlocked()
(raylet) [2021-03-18 09:18:04,560 E 1068 1068] logging.cc:415:     @     0x564ba3d277e2 ray::raylet::NodeManager::ProcessClientMessage()
(raylet) [2021-03-18 09:18:04,560 E 1068 1068] logging.cc:415:     @     0x564ba3c866a1 _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZNS1_6raylet6Raylet12HandleAcceptERKN5boost6system10error_codeEEUlS3_lS8_E0_E9_M_invokeERKSt9_Any_dataOS3_OlS8_
(raylet) [2021-03-18 09:18:04,562 E 1068 1068] logging.cc:415:     @     0x564ba404430e ray::ClientConnection::ProcessMessage()
(raylet) [2021-03-18 09:18:04,563 E 1068 1068] logging.cc:415:     @     0x564ba40413bc boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(raylet) [2021-03-18 09:18:04,564 E 1068 1068] logging.cc:415:     @     0x564ba4407301 boost::asio::detail::scheduler::do_run_one()
(raylet) [2021-03-18 09:18:04,566 E 1068 1068] logging.cc:415:     @     0x564ba44089a9 boost::asio::detail::scheduler::run()
(raylet) [2021-03-18 09:18:04,567 E 1068 1068] logging.cc:415:     @     0x564ba440ae97 boost::asio::io_context::run()
(raylet) [2021-03-18 09:18:04,568 E 1068 1068] logging.cc:415:     @     0x564ba3c52ce2 main
(raylet) [2021-03-18 09:18:04,568 E 1068 1068] logging.cc:415:     @     0x7fbd2c203bf7 __libc_start_main
(raylet) [2021-03-18 09:18:04,570 E 1068 1068] logging.cc:415:     @     0x564ba3c67da5 (unknown)
zsh: abort (core dumped)  ipython
```

**Comment by ijrsvt** [comment]
cc @wuisawesome Any ideas about this?

**Comment by wuisawesome** [comment]
Your title says `max_calls=-1`, but your repro has `max_calls=1`. 

We should fix this either way though. It might just be an edge case in worker termination.

cc @ericl

**Comment by ijrsvt** [comment]
@wuisawesome Yikes, I definitely meant `max_calls=1`.

**Comment by ijrsvt** [comment]
One interesting thing I've noticed while debugging is that the WorkerID from Redis is nil ([here](https://github.com/ray-project/ray/blob/0495d6af1581e2d3bbd4e0819265cf17d2c41611/src/ray/raylet/node_manager.cc#L762)) on the worker crash that tore down the cluster.

**Comment by wuisawesome** [comment]
interesting... that could explain why we're not freeing resources properly/why the cluster resource view is messed up... Any ideas why the worker id is messed up? 

Other option is to bisect to find the issue.

**Comment by ijrsvt** [comment]
@wuisawesome I'm not sure if this was ever **not** a bug :( 

I think at the most basic level what is happening is that the CPUs returned by the crashed worker have already been re-added. 

I'm not 100% if they were added back for that worker **twice**, or if the task's were added back already:
```
[2021-03-18 17:29:16,377 I 79654 79654] cluster_resource_scheduler.cc:849: Freeing Task Resources
[2021-03-18 17:29:16,377 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 31  failures: 0
[2021-03-18 17:29:16,581 I 79654 79654] cluster_resource_scheduler.cc:866: Add CPU Resources
[2021-03-18 17:29:16,581 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 0  failures: 0
[2021-03-18 17:29:16,581 W 79654 79654] cluster_task_manager.cc:865: Deallocing for a09b808006d718f7db751b10195fb2e03dc153ecb371f11ea7785de4
[2021-03-18 17:29:16,582 I 79654 79654] node_manager-checkpoint.cc:1093: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = 0
[2021-03-18 17:29:16,582 I 79654 79654] cluster_resource_scheduler.cc:849: Freeing Task Resources
[2021-03-18 17:29:16,582 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 0  failures: 0
[2021-03-18 17:29:16,582 I 79654 79654] cluster_resource_scheduler.cc:866: Add CPU Resources
[2021-03-18 17:29:16,582 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 0  failures: 1
```

One thing that is clear, is that there are **many instances** of the crashed worker returning CPUs before the task
```
[2021-03-18 17:29:14,320 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 24  failures: 0
[2021-03-18 17:29:14,320 W 79654 79654] cluster_task_manager.cc:865: Deallocing for 6b50f0e255fe51b8962b17680438a5fd4eee8938f7a25c8e176592fb
[2021-03-18 17:29:14,321 I 79654 79654] cluster_resource_scheduler.cc:849: Freeing Task Resources
[2021-03-18 17:29:14,321 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 0  failures: 0
[2021-03-18 17:29:14,321 I 79654 79654] node_manager-checkpoint.cc:1093: NodeManager::DisconnectClient, disconnect_type=1, has creation task exception = 0
[2021-03-18 17:29:14,321 I 79654 79654] cluster_resource_scheduler.cc:849: Freeing Task Resources
[2021-03-18 17:29:14,321 W 79654 79654] cluster_resource_scheduler.cc:653: Adding back CPUs for 24  failures: 1 # NOTE(this is just ignored)
```

**Comment by wuisawesome** [comment]
Yeah, I guess my question is why are we returning the worker multiple times to begin with?

**Comment by ijrsvt** [comment]
@wuisawesome what do you mean by returning it multiple times? 

[Here is gist with the main patches I made for debugging purposes and the output of raylet.out](https://gist.github.com/ijrsvt/4c8cf72f31a9daa9fefb2e783df158dc).

It almost looks as if the failure is because of the following scenario:
1. Worker_1 with Task_1 using `cpu = 0` finishes and crashes because `max_calls=1`
2. Worker_1 returns the resources `cpu = 0` 
3. Task_2 is assigned `cpu = 0` and scheduled on Worker_2 
4. Task_1 _returns its resources_ to `cpu = 0`
5. Worker_2 with Task_2 finishes and crashes because `max_calls=1`
6. Worker_2 tries to return resources to `cpu = 0`, but it is already 'full'

**Comment by sanjaysrikakulam** [comment]
Hi,

Any update regarding this issue? I encountered this today when I used `max_calls=1` in my remote function `@ray.remote(num_cpus=1, max_calls=1)`. This error occurs after running a few loops.

**Comment by wuisawesome** [comment]
#15083 fixes it (manually confirmed). Should be able to merge it pretty soon.

**Comment by sanjaysrikakulam** [comment]
Is the fix now available in a ray 1.3.0?

**Comment by wuisawesome** [comment]
Unfortunately not, it is in the nightly build and will be in 1.4 (which should come out in 1-2 weeks)

**Comment by sanjaysrikakulam** [comment]
OK, thank you! Looking forward to 1.4.
