### ISSUE TITLE
Azure Autoscaler - Permission denied connecting to Docker socket - Head Node Setup

### ISSUE THREAD

**Issue by XavierGeerinck** [ray-project/ray#14780]
Ray RLLib
Version 2.0.0.dev0

When running `ray up` for an Azure deployment, the following occurs:

```bash
  [5/7] Initalizing command runner
Shared connection to 20.71.92.41 closed.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=rayproject%2Fray-ml&tag=latest-gpu: dial unix /var/run/docker.sock: connect: permission denied
Shared connection to 20.71.92.41 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

**Comment by XavierGeerinck** [comment]
Might be related to https://github.com/ray-project/ray/issues/13711

**Comment by ijrsvt** [comment]
@XavierGeerinck Awesome! Glad to hear that worked! I'll be trying to fix some of these launch issues (this one and the one with `setup_commands` as soon as I get some Azure credentials :)

**Comment by ijrsvt** [comment]
Actually @gramhagen Do you know if there is an Azure image that has Docker preconfigured?

**Comment by gramhagen** [comment]
Similar images are available here: https://github.com/Azure/AzureML-Containers#how-to-get-the-azure-ml-images

But they don't setup a ubuntu user (just using root), also they don't come with any python packages installed, so you will still need to do that. In short I don't think this is particularly any more helpful than the other images, sorry! =/

**Comment by gramhagen** [comment]
if you are deploying a vm on azure using the data science vm image will get you docker, ubuntu user, and preconfigured conda environments: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-dsvm.ubuntu-1804?tab=Overview

**Comment by ijrsvt** [comment]
Hmm, @XavierGeerinck what Sku/version were you using?

**Comment by ijrsvt** [comment]
> this is what we use in the deploy to azure option in the docs:

Thanks so much @gramhagen !!! It looks like these are also used in the YAMLs as well! (I didn't realize  `dsvm` meant "Data Science VM")

**Comment by XavierGeerinck** [comment]
Note though that the conda commands seem to run on the container if I am not mistaken? Those don't have conda available I think?

**Comment by ijrsvt** [comment]
@XavierGeerinck Yep! these are run inside the container! _Conda_ is available (with our images), but those environments do not exist!

**Comment by XavierGeerinck** [comment]
Ok! Then it's just a matter of configuring those correctly.

I got it running here now! Can definitely do a `.yaml` update once I am able to run an experiment then if that's ok? Currently stuck due to #14666

**Comment by AmeerHajAli** [comment]
@XavierGeerinck , can you please update the yamls?

**Comment by AmeerHajAli** [comment]
What is the status of this?

**Comment by XavierGeerinck** [comment]
Hi @AmeerHajAli thanks for following up! I am currently still stuck due to #14666 so can't test yet

**Comment by wuisawesome** [comment]
going to assume the fix worked and will close this issue.
