### ISSUE TITLE
[autoscaler][kubernetes] Bad autoscaler/K8s behavior under memory constraints 

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14789]
### What is the problem?

I try to launch 30 min_workers on K8s, with the autoscaler running in a memory-constrained environment (a pod with requests=limits=512Mi).
30 worker pods get launched, but the pods do not successfully connect to the Ray cluster.
`ray status` reports various states for head node and workers each time I attempt this.

For future scalability efforts, it would be good to understand this behavior and to have sensible failure behavior when the autoscaler doesn't have enough memory.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
To add more detail -- I used the cluster launcher, so the autoscaler was running on the head node. Perhaps nearly all memory was already being used up by the other Ray head processes.

**Comment by ericl** [comment]
Can we raise an error by default for excessively small pods (less than 4GB?)

**Comment by DmitriGekhtman** [comment]
This was more of a concern with the `ray up` stack -- probably autoscaler was contending with other ray head processes for memory. Re-marking P2 for now. 
(Autoscaler memory efficiency is an important goal but not exactly within scope here.)

**Comment by DmitriGekhtman** [comment]
This is now under control, doesn't need to be tracked.
