### ISSUE TITLE
[docker] Images with extraneous Ray commits might sometimes be getting tagged nightly

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14794]
### What is the problem?

Looks like images with non-merged PR commits occasionally might sometimes get tagged nightly.
I recently pulled a nightly image that had this ray commit in it https://github.com/ray-project/ray/commit/f4b2ae7408c78d8fabf8569e8f458083b1d752ab

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
Ah, this looks like when people make branches *directly* on the `ray-project/ray` repo 😞
