### ISSUE TITLE
Could not find a version that satisfies the requirement ray

### ISSUE THREAD

**Issue by noah-peeters** [ray-project/ray#14819]
### What is the problem?
When trying to install ray using ```pip install ray``` on windows 10, I get an error saying the package "ray" wasn't found.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python version: 3.9.2

### Reproduction
```pip install ray```
```ERROR: Could not find a version that satisfies the requirement ray ERROR: No matching distribution found for ray```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sheltonsuen** [comment]
Hi @noah-peeters , did you solve this issue? seems like I meet the same issue, and still sucking here #17505, could you give me some information for how you handle this, thanks 😄
