### ISSUE TITLE
[rllib] AttributeError: 'ReplayBuffer' object has no attribute '_num_sampled'

### ISSUE THREAD

**Issue by ymd-h** [ray-project/ray#14818]
### What is the problem?

`ReplayBuffer.sample` produces `AttributeError`.

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Docker Python:3.8
- ray-1.2.0

### Reproduction (REQUIRED)

```python
from ray.rllib.execution.replay_buffer import ReplayBuffer
from ray.rllib.policy.sample_batch import SampleBatch

rb = ReplayBuffer(32)
rb.add(SampleBatch(obs_t=[0], action=[0], reward=[0], obs_tp1=[0], done=[0]), weight=1.0)

rb.sample(1)
```

`AttributeError: 'ReplayBuffer' object has no attribute '_num_sampled'`

The error comes from the following line.

https://github.com/ray-project/ray/blob/fab2c40d2938b6bbdf47e94475d614403e754dce/rllib/execution/replay_buffer.py#L118

It seems the attribute `_num_sampled` was replaced by `_num_timesteps_sampled`, however, the line was forgotten.
(This is the last `_num_sampled`, as far as I searched.)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by RuofanKong** [comment]
I hit the same issue now that blocks us. Is there an ETA on the fix?

**Comment by RuofanKong** [comment]
Looks this attribute is unused anywhere. can we just simply remove it?

**Comment by ymd-h** [comment]
@RuofanKong 
> can we just simply remove it?

No. This is a refactoring bug (maybe) introduced by the commit: https://github.com/ray-project/ray/commit/8f79b4e45ee41565690c59769462c12208996c4a.

The `_num_sampled` should be replaced with `_num_timesteps_sampled`.

(The `_num_timesteps_sampled` is used at `ReplayBuffer.stats()` method)
