### ISSUE TITLE
[tune] Trainable.__init__ docstring refers to build()

### ISSUE THREAD

**Issue by andrew-rosenfeld-ts** [ray-project/ray#14824]
### What is the problem?

This is purely a minor documentation bug.

The docstring for `Trainable.__init__()` includes the text:
```Subclasses should prefer defining ``build()`` instead of overriding ``__init__()`` directly.```

I don't see any other reference to `build()` in the code. Looking at the git history, it seems `build` was superseded by `setup`, yet this docstring wasn't updated. Another, related docstring was updated in https://github.com/ray-project/ray/pull/9448 but this instance was missed.

This is current in Ray master as of 2021-03-21.

**Comment by amogkam** [comment]
Yes, thanks for finding this! `build` has been superseded by `setup`. Do you mind making a quick PR to fix this and tagging me? Thanks!

**Comment by andrew-rosenfeld-ts** [comment]
Sure @amogkam, I created https://github.com/ray-project/ray/pull/14850 to fix this.
