### ISSUE TITLE
Difficult to find working Ray + Horovod example.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#14825]
None of the code snippets at https://horovod.readthedocs.io/en/stable/ray_include.html actually run out of the box.

The same is true of the code snippet on https://horovod.readthedocs.io/en/stable/api.html#horovod-ray-api.

If we change them so that users can copy and paste the examples and they just work, that will make it a lot easier to use Ray + Horovod.

@richardliaw

**Comment by richardliaw** [comment]
Good point - in the future, can you open issues against the horovod/horovod repo? Thanks!

**Comment by richardliaw** [comment]
Moved to https://github.com/horovod/horovod/issues/3022
