### ISSUE TITLE
Unbounded memory leak from raylet when spilling happens with large number of used objects

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14832]
### What is the problem?

Run: python -m ray.experimental.shuffle --num-partitions=1000 --partition-size=1e6 --object-store-memory=1e9

After 820~ish map objects are created, the raylet starts spilling, and you can detect there's a memory leak from the raylet (memory grows unlimitedly, and the machine eventually crashes).

This is highly likely because the spilling logic fuse 100K+ of objects to a single file, but it is not clear yet. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @iycheng @ericl

**Comment by ericl** [comment]
Can we just add the quick fix of at most 10k objects per spill file?

**Comment by rkooo567** [comment]
Okay. Confirmed limiting the number of objects to fuse fixes the issue.
