### ISSUE TITLE
[docs][rllib] Contributing documentation does not mention additional dependencies required for to develop

### ISSUE THREAD

**Issue by Bam4d** [ray-project/ray#14834]
following the guide on `https://docs.ray.io/en/master/rllib-dev.html` is missing several steps before a working dev environment can be realised.

The current instructions are:
1) install wheels using `pip install -U ....`
2) run `setup-dev.py -y`

However this does not allow you to run any examples with rllib (particularly ones running with tune).

There are several packages missing that are not installed by the above steps. 

My workaroud is to currently also install the `pip install -r requirements_rllib.txt` and `pip install -r requirements_tune.txt`. However i'm not sure if this is the correct approach.

It would be nice if the additional steps were included in the `setup-dev.py` script!

**Comment by Bam4d** [comment]
Additionally some of the dependencies in tune such as those in requirements_tune override things like `torch-1.8.0` to `torch-1.7.1-cpu` so its unclear which dependency list is supposed to be installed

**Comment by richardliaw** [comment]
cc @matthewdeng @yard1 for contributor guide efforts.
