### ISSUE TITLE
Issue on page /cluster/kubernetes-manual.html

### ISSUE THREAD

**Issue by MarcoAlejandro** [ray-project/ray#14837]
The [documentation](https://docs.ray.io/en/master/cluster/kubernetes-manual.html#ray-k8s-static) for a static Kubernetes cluster states: 

"_A Ray cluster consists of a single head node and a set of worker nodes (**the provided ray-cluster.yaml** file will start 3 worker nodes)_"

However, the mentioned `ray-cluster.yaml` file isn't linked in the page. 

Personally, I found the file after doing a web search of the file name in a Github repo. 

**Solution**:

Add a link to the file [ray-cluster.yaml](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) in the page https://docs.ray.io/en/master/cluster/kubernetes-manual.html#ray-k8s-static

**Comment by DmitriGekhtman** [comment]
Good idea -- I'll sneak that enhancement into a PR.
