### ISSUE TITLE
Refactor `aws/config.py` to use `available_node_types`

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#14856]
### Describe your feature request

Kill `head_node` and `worker_nodes` fields in `aws/config.py`. 
Use `available_node_types` instead.

This finishes the migration to `available_node_types` for `aws`.

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by xcharleslin** [comment]
cc @xcharleslin 
We can remove https://github.com/anyscale/product/pull/3803 and https://github.com/ray-project/ray/pull/14859 once this is done!

**Comment by AmeerHajAli** [comment]
cc @ckw017
