### ISSUE TITLE
Support multi-flow transfers

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1485]
AWS instances support 25 Gbps between instances in placement group, which requires opening connections to different ports. Connection between same pair of ports is limited to 10 Gbps. IE

```
172.31.1.10:40000 -> 172.31.1.11:5000 -> limited to 10 Gbps.
172.31.1.10:40001 -> 172.31.1.11:5000 -> limited to 10 Gbps.

```

To get this bandwidth out of Ray, it would need to support multiple ports. IE, if I send send 3 large objects, it would create 3 different socket connections from different ports.

The multi-flow with 3 flows can be tested by setting `-p 3` using instructions below
https://aws.amazon.com/premiumsupport/knowledge-center/network-throughput-benchmark-linux-ec2/

**Comment by robertnishihara** [comment]
This is a great idea, we should definitely do this.

**Comment by robertnishihara** [comment]
Is this specific to AWS? Or could speedups from using multiple ports occur in other settings?

**Comment by robertnishihara** [comment]
Due to changes made in #1430, when we implement the ability to send multiple objects in parallel, we will probably need to adjust the code which keeps track of which objects are being received.

**Comment by yaroslavvb** [comment]
So apparently the reason for this is the way oversubscribing is handled -- on AWS, you are guaranteed 10Gbps or 5Gbps bandwidth when you open a flow. So the underlying system can keep track of its available capacity by counting number of flows.

Azure oversubscribes its connections, so it has no reason to have this "flow" construct. Not sure about GCP

**Comment by yaroslavvb** [comment]
BTW, upcoming version of NCCL will support this through MIN_NRINGS feature (multiple all-reduce rings going through same NIC)

**Comment by yaroslavvb** [comment]
One possible way addressing it is to have (or find) a stand-alone socket library that would stripe data on 3 ports instead of 1. Then load this library through `LD_PRELOAD`

**Comment by robertnishihara** [comment]
Do you know of such a library? We're starting to use boost asio.

**Comment by robertnishihara** [comment]
Should be done now since have multiple connections between object managers.
