### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [ray-project/ray#14867]
(base) [jw@cn05 ray]$ ./build.sh
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-redhat-linux/10" is unsafe for cross-compilation
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-redhat-linux/10/../../../../lib64" is unsafe for cross-compilation
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: library search path "/lib/../lib64" is unsafe for cross-compilation
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/../lib64" is unsafe for cross-compilation
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: library search path "/usr/lib/gcc/aarch64-redhat-linux/10/../../.." is unsafe for cross-compilation
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/../../../../lib64/crti.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/crtbeginS.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/libgcc.a(cas_1_1.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/../../../../lib64/libpthread.so: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: //lib64/libc.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: //usr/lib64/libc_nonshared.a(elf-init.oS): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: //lib/ld-linux-aarch64.so.1: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/libgcc.a(cas_1_1.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/crtendS.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
/home/jw/c4aarch64_installer/compiler_compat/ld: warning: /usr/lib/gcc/aarch64-redhat-linux/10/../../../../lib64/crtn.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
...
Starting local Bazel server and connecting to it...
DEBUG: /home/jw/ray/bazel/ray_deps_setup.bzl:63:14: No implicit mirrors used because urls were explicitly provided
INFO: Analyzed target //:ray_pkg (83 packages loaded, 13912 targets configured).
INFO: Found 1 target...
ERROR: /home/jw/.cache/bazel/_bazel_jw/edaa68ba175309c58660ec6d5f2d62d5/external/org_bzip_bzip2/BUILD.bazel:6:11: C++ compilation of rule '@org_bzip_bzip2//:bz2lib' failed (Exit 1): gcc failed: error executing command
  (cd /home/jw/.cache/bazel/_bazel_jw/edaa68ba175309c58660ec6d5f2d62d5/sandbox/linux-sandbox/28/execroot/com_github_ray_project_ray && \
  exec env - \
    LANG=C \
    LD_LIBRARY_PATH=/opt/FJSVstclanga/default/lib64:/opt/FJSVstclanga/default/lib64: \
    PATH=/home/jw/c4aarch64_installer/bin:/home/jw/c4aarch64_installer/condabin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/lib64/qt-3.3/bin:/home/jw/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/var/lib/snapd/snap/bin:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin \
    PWD=/proc/self/cwd \
  /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.o' -fPIC -iquote external/org_bzip_bzip2 -iquote bazel-out/aarch64-opt/bin/external/org_bzip_bzip2 -isystem external/org_bzip_bzip2 -isystem bazel-out/aarch64-opt/bin/external/org_bzip_bzip2 -Werror -w -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_bzip_bzip2/randtable.c -o bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command
  (cd /home/jw/.cache/bazel/_bazel_jw/edaa68ba175309c58660ec6d5f2d62d5/sandbox/linux-sandbox/28/execroot/com_github_ray_project_ray && \
  exec env - \
    LANG=C \
    LD_LIBRARY_PATH=/opt/FJSVstclanga/default/lib64:/opt/FJSVstclanga/default/lib64: \
    PATH=/home/jw/c4aarch64_installer/bin:/home/jw/c4aarch64_installer/condabin:/home/jw/.sdkman/candidates/groovy/current/bin:/opt/FJSVstclanga/default/bin:/usr/lib64/qt-3.3/bin:/home/jw/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.dotnet/tools:/var/lib/snapd/snap/bin:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin \
    PWD=/proc/self/cwd \
  /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.o' -fPIC -iquote external/org_bzip_bzip2 -iquote bazel-out/aarch64-opt/bin/external/org_bzip_bzip2 -isystem external/org_bzip_bzip2 -isystem bazel-out/aarch64-opt/bin/external/org_bzip_bzip2 -Werror -w -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/org_bzip_bzip2/randtable.c -o bazel-out/aarch64-opt/bin/external/org_bzip_bzip2/_objs/bz2lib/randtable.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
ccache: error: Failed to create temporary file for /run/user/1001/ccache-tmp/tmp.cpp_stdout.lQkTvm: Read-only file system
Target //:ray_pkg failed to build
INFO: Elapsed time: 400.966s, Critical Path: 9.18s
INFO: 1132 processes: 1117 internal, 15 linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jw/c4aarch64_installer/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/jw/c4aarch64_installer/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/jw/c4aarch64_installer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./python/setup.py", line 406, in <module>
    api_main(*sys.argv)
  File "./python/setup.py", line 378, in api_main
    result = build(**kwargs)
  File "./python/setup.py", line 291, in build
    env=bazel_env)
  File "./python/setup.py", line 174, in bazel_invoke
    result = invoker([cmd] + cmdline, *args, **kwargs)
  File "/home/jw/c4aarch64_installer/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bazel', 'build', '--verbose_failures', '--', '//:ray_pkg']' returned non-zero exit status 1.
(base) [jw@cn05 ray]$

**Comment by richardliaw** [comment]
I think we've been seeing some progress for Arch builds recently. cc @wuisawesome to follow up here.

**Comment by wuisawesome** [comment]
@LutzWeischerFujitsu if you're still having this issue, can you try to follow #13780 and post there if it doesn't work?

**Comment by LutzWeischerFujitsu** [comment]
Solved using v1.5.2.
