### ISSUE TITLE
Ray.get fetches not prioritized in PullManager (can lead to deadlock with pull manager memory capping)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#14886]
PullManager now caps memory consumption for active and pending task args, as well as ray.get/wait fetches to 70% of available memory: https://github.com/ray-project/ray/pull/14817

However, this might lead to deadlock if PullManager hits the 70% cap while ray.get() fetches of an active task are still queued, or deadlocking if a task's args is already using 70% of memory and it calls ray.get() on something else.

Possible fixes: prioritize ray.get fetches, perhaps also exempt them from the capping (both prioritize and exempt)?

**Comment by ericl** [comment]
cc @stephanie-wang --- should we revert that patch from the 1.3 branch in the interim?

**Comment by stephanie-wang** [comment]
One option is to only cap the args for active tasks. Pending task args don't need to be capped since it's safe to evict them.

**Comment by stephanie-wang** [comment]
Thanks, @pdames, that's good to know. 'll try to get a fix out in by next week.
