### ISSUE TITLE
[Core] Support getCurrentActorHandle

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#14899]
## Brief
We have some requirements like:
- Pass itself actor handle to other actors.
- Treat itself actor handle as normal as other actor handles.

Currently, `ray.get_actor(actor_id)` has no such ability because we should register its handle of non-detached actors anyway (PS: Only caller side registers it).
So we should provide `ray.get_runtime_context().current_actor` method. (`Ray.getRuntimeContext()>getCurrentActorHandle()` in Java)

## Implementation
Implementation can be light: add a serialized actor handle field into actor_creation_task_spec. And the callee side registers the built-in serialized handle when executing its actor creation task.

## TODOs
- [x] Implement Java  side with core worker changes. #14900
- [x] Wrap Python side. #17110

**Comment by simon-mo** [comment]
@jovany-wang bump on the Python support

**Comment by jovany-wang** [comment]
> @jovany-wang bump on the Python support

Here you go! #17110
