### ISSUE TITLE
Tune + placement groups improvements

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#14908]
If you start a `tune.run` today with 1 trial (num_workers=1000), `tune.run` calls this:
```
pg = placement_group([{"CPU": 1}] * 1000, name="blabla")
ray.get(pg.ready())
```

The issue with this workflow is that Tune will not run until we reach enough nodes that accommodate 1000 cpus, and then start scheduling tasks. A more efficient workflow can potentially be to schedule as nodes spin up and not wait until all of them are up. Can Tune create a placement group per worker in num_workers?

**Comment by krfricke** [comment]
So to sketch this out a little more, this is mostly related to RLLib trainables that can have multiple remote rollout workers running. It can be extended to general distributed training settings with a varying amount of workers.

The first thing we should consider here is if starting rollouts with fewer workers and scaling up to more workers is something that is a) technically possible without too much refactoring (dynamically adding new workers) and b) does not impede training. E.g. presumably the total number of rollout steps should be considered for training/stopping, not the per-worker number of rollout steps, as we would have lower sample throughput at the start of the trial or for trials with fewer workers. (Depending on the cluster setup, some trials might never get access to the full resources) cc @sven1977 for the first question on rllib.

The second question is how we should integrate Tune with this. Currently we're scheduling one placement group per trial, and we only start the trial once the placement group is placed - and this requires that all bundles can be placed at the same time. One possibility to do this would be to allow placement groups to be partially placed. I.e. we can schedule the trial once the first bundle is placed, and add workers as bundles are added. Another option would be to create nested placement groups from within the trials. cc @ericl if you have any thoughts on this.

**Comment by ericl** [comment]
I don't think we want to support this use case right now--- dynamic trial sizing is very complex and I haven't heard any users ask for this in RLlib.
