### ISSUE TITLE
[Cluster] No "python-core-worker-*.log" logs written

### ISSUE THREAD

**Issue by eicnix** [ray-project/ray#14914]
### What is the problem?

Actor dies unexpectedly with message `ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.` but no `python-core-worker-*.log` file is actually available. Other log files like the `dashboard.log` have been updated in the meanwhile. 

### Reproduction (REQUIRED)
- Ray 1.2
- Python 3.7.7
- Local Cluster with Docker mode

1. Cause unexpected actor failure
2. `ray attach ray/local.yml`
3. `ls -lath /tmp/ray/session_latest/logs/`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Can you provide a script that can cause unexpected actor failures?
