### ISSUE TITLE
[core] `worker.run_function_on_all_workers` runs in the driver process twice

### ISSUE THREAD

**Issue by thomasdesr** [ray-project/ray#14919]
### What is the problem?

run_function_on_all_workers runs the function passed twice on the driver (but once on all the workers). It should only run it once.

### Reproduction (REQUIRED)

```python
import ray

print(ray.__version__)

ray.init()

def setup(worker_info):
    print("Running setup")

ray.worker.global_worker.run_function_on_all_workers(setup)
```

```
Ray 1.2.0
2021-03-24 17:12:10,254 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379
Running setup
Running setup
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jjyao** [comment]
run_function_on_all_workers is deleted by #30895
