### ISSUE TITLE
Feature request on `actor.wait(timeout_ms)` API

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#14923]
## 1. Problems And Background

Many users' code needs a function that waits for an actor to complete. Previously, we were encouraging users to implement meaningless remote calls such as `ray.wait (actor.no_op.remote())` to workaround. But as the scale of the user code repository grows, so does the cost of maintenance.

Therefore, I'd like to propose an API that waits for an actor to be created successfully, to simplify such operations for users.

## 2. API
python
```python
# actor1.ready() returns a RayObject.
ray.wait([actor1.ready()])
```
Java
```java
Ray.wait(ImmutableLists.of(actor1.ready()))
```
Exceptions such as `TimeoutException`, `ActorDeadException` would be thrown if the actor is not created successfully.

**Comment by richardliaw** [comment]
Why not just do `ray.wait([actor])` to avoid introducing a new API?

**Comment by jovany-wang** [comment]
> Why not just do `ray.wait([actor])` to avoid introducing a new API?

The parameter of current `ray.wait()` is RayObject. I'm not sure if it's weird to pass an actor handle as its parameter.

**Comment by jovany-wang** [comment]
@ericl @raulchen Let us discuss the `ray.wait(actor)` here.

**Comment by raulchen** [comment]
@ericl regarding `ray.wait` on actors, my main concern is that if may cause confusions that `ray.wait` is used for both objects and actors. E.g., should we allow passing both objects and actors in one call (`ray.wait([object, actor])`)? If so, the return values will be a mixture of object refs and actor handles. And users will be confused about how to deal with the results. 

Thus, I'd like to have a separate API, say `ray.wait_actors`, which has the same usage as `ray.wait(objects)` but is used for waiting actors.

**Comment by ericl** [comment]
I agree, overloading wait seems problematic. I see two possible APIs:

1. Add a ray.wait_actors() method as suggested.
2. Generate a default actor.ready() method which can be used with normal wait (it can be put in its own concurrency group). This would be consistent with placement group's .ready().

**Comment by raulchen** [comment]
I'm slightly in favor of `ray.wait([actor.ready()]`. The benefit is to avoid introducing a new API. 
Regarding the implementation, I'd prefer not to use an concurrency group for it. As that will create an extra thread. We can cache the ready() result, so there won't be too many `ready` tasks. Then just putting it in the default thread should be fine.

**Comment by ericl** [comment]
I see, is the proposal to special case the implementation of ready in the
core worker so it doesn't get blocked by other tasks? If so then sgtm. We
could also use this pattern in the future to get other actor stats from the
core worker.

**Comment by raulchen** [comment]
> is the proposal to special case the implementation of ready in the
core worker so it doesn't get blocked by other tasks

right

**Comment by jovany-wang** [comment]
Thanks. `ray.wait([actor.ready()]` looks good to me as well. 
I'll update the full API usage in the description.  And I believe the implementation of this API is light.

**Comment by jovany-wang** [comment]
> We can cache the ready() result, so there won't be too many `ready` tasks. Then just putting it in the default thread should be fine.

How to handle the case that once the target actor is restarted or dead if we cache the ready() result?

**Comment by jovany-wang** [comment]
One light implementation is that submit a normal task. In Python just add a ready method for ActorClass, like `__ray_terminate__`.

I'm not sure it's necessary to  implement it in core worker.

**Comment by edoakes** [comment]
@jovany-wang it's necessary to implement it in the core worker to avoid it blocking on other tasks that may be running

**Comment by jovany-wang** [comment]
Will confirm later.

**Comment by jovany-wang** [comment]
It's still valid.

**Comment by kfstorm** [comment]
Do we all agree that this feature is valid? I think we should be on the same page before discussing the API design.

**Comment by jovany-wang** [comment]
> Do we all agree that this feature is valid? I think we should be on the same page before discussing the API design.

+1

**Comment by ericl** [comment]
Yeah, it seems valid. Seems everyone agrees above--- just the implementation needs to be fixed to not block if other tasks are running, right?

**Comment by jdonzallaz** [comment]
Hi, is this feature implemented now? One of the related PR has been closed, and I can't find another one that implements it.
