### ISSUE TITLE
Reconnecting to ray does not work

### ISSUE THREAD

**Issue by blublinsky** [ray-project/ray#14959]
### What is the problem?

*Ray version 2.0.o-dev

### Reproduction (REQUIRED)
If you execute this code , the connection fails
```
ray.util.connect('127.0.0.1:10001')
if rayclient.is_connected():
    ray.util.disconnect()
ray.util.connect('127.0.0.1:10001')
```
If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @AmeerHajAli

**Comment by AmeerHajAli** [comment]
@blublinsky , I tried this locally:
```
import ray
import ray.util
from ray.util.client import ray as rayclient
ray.util.connect("127.0.0.1:10001")
if rayclient.is_connected():
    print("disconnecting...")
    ray.util.disconnect()
ray.util.connect('127.0.0.1:10001')
@ray.remote
def f(x):
    return x ** x

print(ray.get(f.remote(2)))
```
it works, so I am not sure what is going on. Can you call `ray install-nightly` and rerun this?
