### ISSUE TITLE
[rllib] "normalize_actions" parameter is clipping the action while it shouldn't.

### ISSUE THREAD

**Issue by duburcqa** [ray-project/ray#14968]
### What is the problem?

`"normalize_actions"` common parameter can be used to "Unsquash actions to the upper and lower bounds of env's action space", yet in practice it also clip it to [-1.0, 1.0], as you can see [here](https://github.com/ray-project/ray/blob/de7ee75d27919178167cdc377e25441fc1b7a59b/rllib/env/normalize_actions.py). I think this behavior is not expected, and should be fixed, since the common parameter `"clip_actions"` is already offering this feature.

**Comment by mvindiola1** [comment]
Hi @duburcqa

Perhaps I am kissing something but looking at the code I do not see an issue. I will not clip to - 1,1 but actionspace.low and actionspace.high. That could be - 1,1 or any other pair of values defined by the environment. I think it makes sense to enforce that the unsquashed action is within the bounds of the action space. Where you seeing or thinking something different?

**Comment by duburcqa** [comment]
> I think it makes sense to enforce that the unsquashed action is within the bounds of the action space. Are you seeing or thinking something different?

Yes, it makes sense, yet I don't think you should. It should be possible to allow out-of-range values, since it is not forbidden by OpenAI gym specifications. If it is an issue or not must be handled specifically for every environments.

**Comment by duburcqa** [comment]
@richardliaw Any news ? I can create a PR by myself if necessary.
