### ISSUE TITLE
[serve] dependencies not listed in ray[full]

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#14972]
### What is the problem?

`pip install ray[serve]` installs dependencies that are not in `pip install ray[full]`

@simon-mo 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Are they supposed to? There's also a `ray[all]` which contains the union of all lib deps. @richardliaw

**Comment by wuisawesome** [comment]
interesting, now i'm wondering why `ray[full]` exists... I've only seen it in an autoscaler warning...

**Comment by richardliaw** [comment]
yeah that's definitely confusing. "full" is definitely new, and we should rename it appropriately.

[all] is the entire ecosystem. [full] is the current ray core.

What about ray[core]?

**Comment by wuisawesome** [comment]
What do you mean by "ray core". I would think the ray core is encompassed by `pip install ray`

**Comment by edoakes** [comment]
What exactly is `ray[full]` vs `ray`? Maybe `ray[util]` or something?
