### ISSUE TITLE
[serve] Documentation page on development & debugging best practices

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#14974]
e.g., how do I see logs when I get an internal server error from fastapi?

**Comment by victor-ab** [comment]
BTW, @edoakes do you know the answer to this question?

**Comment by edoakes** [comment]
@victor-ab we are working on improving this, but for now I'd recommend you use the Ray dashboard to look at logs, else the log files are also in /tmp/ray/session_latest/logs/working-*.{out,err}

**Comment by edoakes** [comment]
@simon-mo should this ticket be assigned for serve CUJ?

**Comment by simon-mo** [comment]
For this particular use case:

When you get an application manifested as exception, the traceback should be in the traceback.
For example, the following prints:
```python
from ray import serve
serve.start()
@serve.deployment
def f():
    1/0
f.deploy()
import requests
print(requests.get("http://localhost:8000/f").text)
```


```
Task Error. Traceback: ray::RayServeWrappedReplica.handle_request() (pid=72593, ip=127.0.0.1)
  File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/utils.py", line 234, in wrap_to_ray_error
    raise exception
  File "/Users/simonmo/Desktop/ray/ray/python/ray/serve/replica.py", line 316, in invoke_single
    result = await method_to_call()
  File "<ipython-input-3-5f772a1f8a63>", line 3, in f
ZeroDivisionError: division by zero.
```

**Comment by simon-mo** [comment]
@edoakes moving this to CUJ but not blocker
