### ISSUE TITLE
[tune] tune.run() with resume="REMOTE" throws ValueError, and kwarg docs are out of date

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#14977]
### What is the problem?

Resuming a `tune.run()` job using the `resume="REMOTE"` option fails with a `ValueError: Called resume from remote without remote directory` (raised by ray/tune/trial_runner.py", line 236 in _validate_resume). The [API docs](https://docs.ray.io/en/latest/tune/api_docs/execution.html#tune-run) for the `resume` kwarg seem out of date, because it references `local_checkpoint_dir` and `remote_checkpoint_dir`, both of which don't seem to be referenced anywhere else in the docs.

```
ray.__version__  # '1.2.0'
Python 3.8.5
Ubuntu 20.10
```

### Reproduction

`tune.run(..., local_dir=LOCAL_MODEL_DIR, resume="REMOTE", name="experiement_I_want_to_resume", sync_config=tune.SyncConfig(upload_dir=REMOTE_MODEL_DIR)) .`

I'm very sorry, but I have too much on my plate to make a fully reproducible example and reproduce on the latest wheels.

**Comment by krfricke** [comment]
This seems to be an usage error and can be solved by passing ``tune.run(sync_config=tune.SyncConfig(upload_dir="s3://bucket/remote_checkpoint_dir"))``. I fixed the docstring and added more verbose printouts in #16709 - please let me know if this helps!

**Comment by crypdick** [comment]
Thanks @krfricke. I did pass in a sync config but maybe other things have been fixed since v1.2.0?

**Comment by krfricke** [comment]
Yeah, that might be - 1.2.0 is a bit dated. Let me know if you run into this issue again, otherwise I'll consider this closed after mergin #16709
