### ISSUE TITLE
[docs] Broken link in release documentation

### ISSUE THREAD

**Issue by mntan3** [ray-project/ray#14975]
### What is the problem?

https://docs.ray.io/en/master/installation.html#official-releases
The "release process doc" link seems to be broken. 

I'm guessing it was supposed to link to here: https://github.com/ray-project/ray/blob/master/release/RELEASE_PROCESS.rst

### Reproduction (REQUIRED)
Go here: https://docs.ray.io/en/master/installation.html#official-releases and click "release process doc"

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by pcmoritz** [comment]
This was fixed in https://github.com/ray-project/ray/pull/19312
