### ISSUE TITLE
Creating exe file on Windows

### ISSUE THREAD

**Issue by yolking** [ray-project/ray#14993]
System information
Windows 10 
ray 1.2.0
python 3.8.8

Basically I am trying to create an .exe file based on python script, where `ray` is used. Script works perfectly fine in python, but I need .exe to launch this code on another computer.
I create .exe using `pyinstaller` with several manually added hidden dependencies for ray 
hiddenimports=['ray.async_compat','msgpack']
Unfortunately, exe application crashes on `ray.init(num_cpus=2)` with 
> Traceback (most recent call last):
>   File "myscript.py", line 41, in <module>
>   File "ray\_private\client_mode_hook.py", line 47, in wrapper
>   File "ray\worker.py", line 714, in init
>   File "ray\node.py", line 220, in __init__
>   File "ray\node.py", line 827, in start_head_processes
>   File "ray\node.py", line 632, in start_redis
>   File "ray\_private\services.py", line 833, in start_redis
>   File "ray\_private\services.py", line 942, in _start_redis_instance
> AssertionError

I think the problem is redis-server.exe, which isn't connected by `pyinstaller`, but I have no idea how to fix it.

**Comment by mattip** [comment]
Can you check on latest ray 2.9.3, where redis-server is no longer required?
