### ISSUE TITLE
[serve] Clarify subpath behavior for @serve.ingress

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#14994]
@simon-mo there was some confusion in our hackathon project as to how exactly overlapping subpaths would work. The behavior that we wanted was to be able to have a "catch all" deployment at `/` (it was serving the frontend static files) and then other deployments at subpaths like `/api`.

Right now, what happens is if you put a `path_prefix="/"`, this will appear at `http://localhost:8000//`.

I think what we want here is for the HTTP proxy to do a longest prefix match and then allow the individual deployments to handle it from there.

Thoughts @simon-mo?

**Comment by edoakes** [comment]
cc @alanwguo who discovered the problem!

**Comment by edoakes** [comment]
Marking P1 to at least have clear docs on the behavior, the longest prefix match is more of a nice to have IMO.

**Comment by edoakes** [comment]
Actually @architkulkarni is it possible to use the starlette routing code you used for the existing variable routes support for this?

**Comment by architkulkarni** [comment]
The question is basically whether it's possible to support this using Path Parameters: https://www.starlette.io/routing/#path-parameters. Let me think about it.  We could also look into porting Starlette's Mount feature (see link) into Serve the same way we did with the Router--not sure yet if that would be helpful

**Comment by architkulkarni** [comment]
The way the route priority in Starlette is it just tries the routes in order, so we have to order them correctly.  This may be as easy as ordering by decreasing length of `ingress_path`, but I might be missing something more subtle.  Here's the example from the docs:
```python
# Don't do this: `/users/me` will never match incoming requests.
routes = [
    Route('/users/{username}', user),
    Route('/users/me', current_user),
]

# Do this: `/users/me` is tested first.
routes = [
    Route('/users/me', current_user),
    Route('/users/{username}', user),
]
```

**Comment by edoakes** [comment]
I believe just ordering them in order of increasing length should work
unless I’m missing something.

We should also probably disable variable routes support at this level once
fastapi is the recommended way to do things unless there’s a concrete use
case for it.

**Comment by simon-mo** [comment]
for static file use case, users should either:
- use StaticFiles middlewares to actually serve static assets
- add a `/{wildcard:path}` endpoint to serve so it matches against arbitrary subpath, and ask Serve to potentially deprioritize it.

**Comment by alanwguo** [comment]
that's what we do actually: https://github.com/anyscale/dev-dashboard/blob/main/backend/web.py

Except serve doesn't interpret "/" path prefix as the root path but rather root + "/"
