### ISSUE TITLE
[ray client] Support all ray public APIs in ray client

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#15010]
We should support all the public ray APIs [here](https://docs.ray.io/en/master/package-ref.html?highlight=ray.kill#ray-kill) in ray client.
Currently for example:
`ray.kill(), ray.cancel(), ray.get_gpu_ids()` are not supported.

**Comment by DmitriGekhtman** [comment]
What is the desired behavior for `ray.get_gpu_ids()` when it is called from client mode?
Should we return an empty list?
cc @ijrsvt

**Comment by ijrsvt** [comment]
I'll defer to @ericl on this one. If this is being called as a way to check if GPUs exist on the head node (before launching ray tasks that require GPUs), then we should probably forward the request to the server.

**Comment by ericl** [comment]
The driver is never assigned GPUs, so it should return empty list as it
does in a normal driver.

**Comment by AmeerHajAli** [comment]
split this issue into multiple issues:
#15174 #15175  #15176
