### ISSUE TITLE
Ray can't be initialized while connected to redis

### ISSUE THREAD

**Issue by VinnyLiu0817** [ray-project/ray#15035]
**System information**
OS: Windows 10
Ray: 1.2.0
Python: 3.7 64-bit

**Problem description:**
Running the script on a github program about DML and I built a simple redis cluster with 3 nodes and 3 slaves on my local laptop, but ray can't be initialized when it tries to connect to the redis cluster. I am pretty sure that I open the redis cluster mode.
Console/debugger outputs look like this:
![move error](https://user-images.githubusercontent.com/77725034/113109575-b193a800-9238-11eb-8192-6ddc10d6b28a.jpg)

**Comment by rkooo567** [comment]
Do you still see this issue now?
