### ISSUE TITLE
Ray.init() -  (raylet) Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by GaspTO** [ray-project/ray#15053]
Hi,
When I execute 
`import ray
ray.init()`

There's some trouble with some threads that I can't understand what it is about.  Here's some short print of the problem.
![image](https://user-images.githubusercontent.com/47759921/113234238-cc960480-9298-11eb-8630-c3bd82136617.png)

Here are the logs of raylet
[raylet-1.err.txt](https://github.com/ray-project/ray/files/6240534/raylet-1.err.txt)
[raylet-1.out.txt](https://github.com/ray-project/ray/files/6240535/raylet-1.out.txt)

I spoke to a Ray team member online and he suggested I ran 
`ray.init(include_dashboard=False)`

Which gave me the following error:
![image](https://user-images.githubusercontent.com/47759921/113234760-ca807580-9299-11eb-87f5-b8184f9496f6.png)

And the raylet logs:
[raylet-2.out.txt](https://github.com/ray-project/ray/files/6240540/raylet-2.out.txt)
[raylet-2.err.txt](https://github.com/ray-project/ray/files/6240541/raylet-2.err.txt)

He then told me it was harmless and to post it here.

Also, when I run init as in the first time, I don't see anything in the localhost:port address.

Thank you

**Comment by rkooo567** [comment]
What's your OS? Also what virtual env do you use? do you have anything special about your environment? (I've never seen this issue before)
