### ISSUE TITLE
How to clear objects from the object store in ray?

### ISSUE THREAD

**Issue by Stefan-1313** [ray-project/ray#15058]
I am trying out the promising multiprocessing package `ray`. I have a problem I seem not be able to solve. My program runs fine the first time, but at a second run this Exception is raised on the `ray.put()` line:

    ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff010000000c000000 in object store because it is full. Object size is 2151680255 bytes.
    The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.

**What do I want to do:**
In my actual code (I'm planning to write) I need to process many `big_data_objects` sequentially. I want to hold one `big_data_object` in memory at a time and do several heavy (independent) computations on the big data object. I want to execute these computations in parallel. When these are done, I have to replace these `big_data_object` in the object store by new ones and start the computations (in parallel) again.

Using my test script I simulate this by starting the script again without `ray.shutdown()`. If I shutdown `ray` using `ray.shutdown()` the object store is cleared but then reinitializing takes a long time and I cannot process multiple `big_data_object` sequentially as I want to.

**What sources of information have I studied:**
I studied this document [Ray Design Patterns][1] and studied the section 'Antipattern: Closure capture of large / unserializable object' and how to the proper pattern(s) should look like. I also studied the getting started guide which lead to the following test script.

**A minimum example to reproduce the problem:**
I created a test script to test this. It is this:

    #%% Imports
    import ray
    import time
    import psutil
    import numpy as np
    
    
    #%% Testing ray
    # Start Ray
    num_cpus = psutil.cpu_count(logical=False)
    if not ray.is_initialized():
        ray.init(num_cpus=num_cpus, include_dashboard=False)
    
    # Define function to do work in parallel
    @ray.remote
    def my_function(x):  # Later I will have multiple (different) my_functions to extract different feature from my big_data_object
        time.sleep(1)
        data_item = ray.get(big_data_object_ref)
        return data_item[0,0]+x
    
    # Define large data
    big_data_object = np.random.rand(16400,16400)  # Define an object of approx 2 GB. Works on my machine (16 GB RAM)
    # big_data_object = np.random.rand(11600,11600)  # Define an object of approx 1 GB.
    # big_data_object = np.random.rand(8100,8100)  # Define an object of approx 500 MB.
    # big_data_object = np.random.rand(5000,5000)  # Define an object of approx 190 MB.
    big_data_object_ref = ray.put(big_data_object)
    
    # Start 4 tasks in parallel.
    result_refs = []
    # for item in data:
    for item in range(4):
        result_refs.append(my_function.remote(item))
        
    # Wait for the tasks to complete and retrieve the results.
    # With at least 4 cores, this will take 1 second.
    results = ray.get(result_refs)
    print("Results: {}".format(results))
    
    
    #%% Clean-up object store data - Still their is a (huge) memory leak in the object store.
    for index in range(4):
        del result_refs[0]
    
    del big_data_object_ref

**Where do I think it's going wrong:**
I think I delete all the references to the object store in the end of the script. As a result the objects should be cleared from the object store (as described [here][2]). Apparently, something is wrong because the `big_data_object` remains in the object store. The `results` are deleted from the object store just fine, however.

**Some debug information:**
I inspected the object store using `ray memory` command, this is what I get:

    (c:\python\cenv38rl) PS C:\WINDOWS\system32> ray memory
    ---------------------------------------------------------------------------------------------------------------------
     Object ID                                                Reference Type       Object Size   Reference Creation Site
    =====================================================================================================================
    ; worker pid=20952
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; worker pid=29368
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; worker pid=17388
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; worker pid=24208
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; worker pid=27684
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; worker pid=6860
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\serialization.py:object_ref_deserializer:45 | c:\python\cenv38rl\lib\site-packages\ray\function_manager.py:fetch_and_register_remote_function:180 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_process_key:140 | c:\python\cenv38rl\lib\site-packages\ray\import_thread.py:_run:87
    ; driver pid=28684
    ffffffffffffffffffffffffffffffffffffffff010000000b000000  LOCAL_REFERENCE       2151680261   c:\python\cenv38rl\lib\site-packages\ray\worker.py:put_object:277 | c:\python\cenv38rl\lib\site-packages\ray\worker.py:put:1489 | c:\python\cenv38rl\lib\site-packages\ray\_private\client_mode_hook.py:wrapper:47 | C:\Users\Stefan\Documents\Python examples\Multiprocess_Ray3_SO.py:<module>:42
    ---------------------------------------------------------------------------------------------------------------------
    
    --- Aggregate object store stats across all nodes ---
    Plasma memory usage 2052 MiB, 1 objects, 77.41% full

**Some of the things I have tried:**
If, I replace `my_function` for:

    @ray.remote
    def my_function(x):  # Later I will have multiple different my_functions to extract separate feature from my big_data_objects
        time.sleep(1)
        # data_item = ray.get(big_data_object_ref)
        # return data_item[0,0]+x
        return 5

and then the script successfully clears the object store but `my_function` cannot use the `big_data_object` which I need it to.

**My question is: How to fix my code so that the `big_data_object` is removed from the object store at the end of my script without shutting down ray?**

*Note: I installed ray using `pip install ray` which gave me version `ray==1.2.0` which I am using now. I use ray on `Windows` and I develop in `Spyder v4.2.5` in a `conda` (actually miniconda) environment in case it is relevant.*

  [1]: https://docs.google.com/document/d/167rnnDFIVRhHhK4mznEIemOtj63IOhtIPvSYaPgI4Fg/edit#
  [2]: https://docs.ray.io/en/latest/memory-management.html

**Comment by Stefan-1313** [comment]
I have tested also on a ubuntu machine with 8GB RAM. For this I used the `big_data_object` of 1GB.
I can confirm the issue also occurs on this machine.

The `ray memory` output:
```
(SO_ray) stefan@stefan-HP-ZBook-15:~/Documents/Ray_test_scripts$ ray memory 
---------------------------------------------------------------------------------------------------------------------
 Object ID                                                Reference Type       Object Size   Reference Creation Site
=====================================================================================================================
; worker pid=18593
ffffffffffffffffffffffffffffffffffffffff0100000001000000  LOCAL_REFERENCE       1076480259   /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/function_manager.py:fetch_and_register_remote_function:180 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_process_key:140 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_run:87 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/threading.py:run:870
; worker pid=18591
ffffffffffffffffffffffffffffffffffffffff0100000001000000  LOCAL_REFERENCE       1076480259   /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/function_manager.py:fetch_and_register_remote_function:180 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_process_key:140 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_run:87 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/threading.py:run:870
; worker pid=18590
ffffffffffffffffffffffffffffffffffffffff0100000001000000  LOCAL_REFERENCE       1076480259   /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/function_manager.py:fetch_and_register_remote_function:180 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_process_key:140 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_run:87 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/threading.py:run:870
; driver pid=17712
ffffffffffffffffffffffffffffffffffffffff0100000001000000  LOCAL_REFERENCE       1076480259   (put object)  | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:wrapper:47 | /home/stefan/Documents/Ray_test_scripts/Multiprocess_Ray3_SO.py:<module>:43 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py:exec_code:453
; worker pid=18592
ffffffffffffffffffffffffffffffffffffffff0100000001000000  LOCAL_REFERENCE       1076480259   /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/function_manager.py:fetch_and_register_remote_function:180 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_process_key:140 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/site-packages/ray/import_thread.py:_run:87 | /home/stefan/miniconda3/envs/SO_ray/lib/python3.8/threading.py:run:870
---------------------------------------------------------------------------------------------------------------------

--- Aggregate object store stats across all nodes ---
Plasma memory usage 1026 MiB, 1 objects, 99.69% full
```

I have to run the program in `Spyder` so that after execution of the program I can inspect the object store's memory using `ray memory`. If I run the program in `PyCharm` for example, `ray` is automatically terminated as the script is completed so I cannot check if my script clears the object store as intended.

**Comment by rkooo567** [comment]
I am taking a look at this now..

**Comment by rkooo567** [comment]
The problem is that your remote function captures `big_data_object_ref `, and the ref from there is never removed. Note that when you do this type of thing

```python3
# Define function to do work in parallel
@ray.remote
def my_function(x):  # Later I will have multiple (different) my_functions to extract different feature from my big_data_object
    time.sleep(1)
    data_item = ray.get(big_data_object_ref)
    return data_item[0,0]+x
    return 5

# Define large data
big_data_object = np.random.rand(16400,16400)
big_data_object_ref = ray.put(big_data_object)
```

`big_data_object_ref` is seriliazed to the remote function definition (thus there's a permanant pointer). 

Instead use this type of pattern; 

```python3
#%% Imports
import ray
import time
import psutil
import numpy as np


#%% Testing ray
# Start Ray
num_cpus = psutil.cpu_count(logical=False)
if not ray.is_initialized():
    ray.init(num_cpus=num_cpus, include_dashboard=False)

# Define function to do work in parallel
@ray.remote
def my_function(big_data_object, x):  # Later I will have multiple (different) my_functions to extract different feature from my big_data_object
    time.sleep(1)
    return big_data_object[0,0]+x
    # return 5

# Define large data
#big_data_object = np.random.rand(16400,16400)  # Define an object of approx 2 GB. Works on my machine (16 GB RAM)
# big_data_object = np.random.rand(11600,11600)  # Define an object of approx 1 GB.
big_data_object = np.random.rand(8100,8100)  # Define an object of approx 500 MB.
# big_data_object = np.random.rand(5000,5000)  # Define an object of approx 190 MB.
big_data_object_ref = ray.put(big_data_object)
print("ref in a driver ", big_data_object_ref)

# Start 4 tasks in parallel.
result_refs = []
# for item in data:
for item in range(4):
    result_refs.append(my_function.remote(big_data_object_ref, item))
    
# Wait for the tasks to complete and retrieve the results.
# With at least 4 cores, this will take 1 second.
results = ray.get(result_refs)
print("Results: {}".format(results))
print(result_refs)

#%% Clean-up object store data - Still their is a (huge) memory leak in the object store.
#for index in range(4):
#    del result_refs[0]
del result_refs

del big_data_object_ref
import time
time.sleep(1000)
```

(The difference is that now we pass `big_data_object_ref` instead of capturing it)

**Comment by Stefan-1313** [comment]
@rkooo567, Thank you so much! You made me very happy :)
I tried it and it worked. However, I have some comments which could be good for you to know and perhaps document (see bottom of this post)

First, I have a question about the solution:

> Instead use this type of pattern;
> ... [code example] ...
> (The difference is that now we pass big_data_object_ref instead of capturing it)

I tried something similar, but slightly different (which didn't work obviously), namely:
@ray.remote
```
def my_function(big_data_object_ref, x): 
    time.sleep(1)
    data_obj = ray.get(big_data_object_ref)
    return data_obj [0,0]+x
```

Why don't we have to use `ray.get()` in this context?

----------------------------------------------------------------
Alright, some other things I noticed during my testing which may be good for you to be aware of and to perhaps have documented (if only by a small note).

I use `Spyder` (version `4.2.5` at the moment) to develop my code. After running some code, Spyder keeps all variables and objects alive so you can easily debug, even if it code exited by a unhandled Exception. You can inspect and manipulate the variables using an IPython console. You can then also run snippets of code using the variables still in memory.

As such, it allowed me to inspect the variables `big_data_object_ref` and `result_refs` and compare the ID's which those returned by the `ray memory` command.

But if I then use (e.g.) `del result_refs` in the Spyder console, I can see the variable is deleted form the variable explorer in Spyder. If I then try to access `result_refs` I get (as expected): `NameError: name 'result_refs' is not defined`

However, if I then call `ray memory` the objects are NOT removed from the object store. So I was confused.
When I run my script with this in the end (inspired by your example solution):

```
#%% Testing ray
# ... my ray testing code

#%% Clean-up object store data
print("Wait 10 sec BEFORE deletion")
time.sleep(10)

del result_refs
del big_data_object_ref

print("Wait 10 sec AFTER deletion")
time.sleep(10)
```
And I use `ray memory` during both the 10 second breaks, I can verify all the objects get successfully removed from the object store.

Apparently, something is happening here in the interaction between `ray` and Spyder. I don't know what exactly, but a note in the docs could in the future save people (using Spyder) from lot of frustration in their introduction to `ray`. If it would be solved it would be even better off course ;).

However, I just share this experience to do with as you like :). I am curious about the `ray.get()` above though.

**Comment by rkooo567** [comment]
@Stefan-1313 Thanks for the valuable feedback :) 

> My question: Why don't we have to use ray.get() in this context?

When the object ref is passed to the remote function, they are automatically `ray.get`'ed. If you'd like to call ray.get inside a remote function, then pass the argument inside a list of dictionary.

```python3
ref = ray.put(some_object)

@ray.remote
def f(ref_list):
    print(ray.get(ref_list[0]))

ray.get(f.remote([ref])) # Notice we are passing the ref inside a list. 

```

> Apparently, something is happening here in the interaction between ray and Spyder. I don't know what exactly, but a note in the docs could in the future save people (using Spyder) from lot of frustration in their introduction to ray. If it would be solved it would be even better off course ;).

We've seen a similar issue from ipython too. Unfortunately, fixing it is not really trivial. I definitely agree it'll be great to have a doc! (But not sure where's the best place?) Also, feel free to create PR to add this information :)!

**Comment by Stefan-1313** [comment]
@rkooo567, I will try to make a PR to add the information somewhere in the near future.
Does the `ray` in combination with `IPython` perks only happen with respect to the object store. Or does it affect other parts of `ray` as well? Because that determines what is a good place in the docs.

**Comment by nathanin** [comment]
The comments here helped me fix an issue in a setup where I need to take results and save them to disk when ready. I expect the results to be consumed pretty much as quickly as they're available, therefore I expect near-constant memory usage. All results would be too large to hold in memory at once, so I was getting the ready tasks with `ray.wait`, but was totally confused about why my objects were remaining in the object store. I was doing deep copies and deleting everything. Turns out I wasn't deleting the actual task IDs! 

This pattern keeps LOCAL_REFERENCES to every returned object, resulting in growing memory usage:
```python
data_id = ray.put(big_data)

futures = []
for i in range(Ntasks):
  futures.append( remote_fn.remote(data_id,) )

# not deleting the original futures list was the core mistake
not_ready = futures
for i n range(Ntasks):
  ready, not_ready = ray.wait(not_ready, num_returns=1)
  big_return_data = ray.get(ready[0])

  # save big_return_data to disk

  del big_return_data

```


This pseudocode summarizes the setup that's working in my case:

```python
data_id = ray.put(big_data)

not_ready = []
for i in range(Ntasks):
  not_ready.append( remote_fn.remote(data_id,) )

for i n range(Ntasks):
  ready, not_ready = ray.wait(not_ready, num_returns=1)
  big_return_data = ray.get(ready[0])

  # save big_return_data to disk

  # pretty sure this would get cleared on the next iteration, but for good measure..
  del ready
  del big_return_data

```
