### ISSUE TITLE
[core] Raylet crashes during task retry. Check failed: overflow_cpu_instances[i] == 0 Should not be overflow

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#15077]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

If a task submits another task and then fails, there is an assertion check that crashes the raylet.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

This script works if the child task is killed and crashes if the parent task is killed.

```python
import ray
import signal
import os
import time


TEST_ARGS = True
KILL_PARENT = True

@ray.remote
class PidActor:
    def __init__(self):
        self.child_pid = None
        self.parent_pid = None

    def set_child_pid(self, pid):
        if self.child_pid is None:
            self.child_pid = pid

    def get_child_pid(self):
        return self.child_pid
    
    def set_parent_pid(self, pid):
        if self.parent_pid is None:
            self.parent_pid = pid 

    def get_parent_pid(self):
        return self.parent_pid
    
@ray.remote
def child(pid_actor, ref):
    pid_actor.set_child_pid.remote(os.getpid())
    time.sleep(3)


@ray.remote
def parent(pid_actor):
    pid_actor.set_parent_pid.remote(os.getpid())
    if TEST_ARGS:
        x = ray.put("x" * 1000000)
    else:
        x = "x"
    ray.get(child.remote(pid_actor, x))

ray.init()
pid_actor = PidActor.remote()
p = parent.remote(pid_actor)

pid = None
while pid is None:
    if KILL_PARENT:
        pid = ray.get(pid_actor.get_parent_pid.remote())
    else:
        pid = ray.get(pid_actor.get_child_pid.remote())
    time.sleep(1)

os.kill(pid, signal.SIGKILL)
ray.get(p)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment]
@wuisawesome @ericl, probably a regression with the new scheduler. Any ideas?

**Comment by wuisawesome** [comment]
Yeah, this is probably #14775

**Comment by ericl** [comment]
Should this be a release blocker?

**Comment by wuisawesome** [comment]
Maybe... The bug has always been in the new scheduler, but it was exacerbated by object spilling (https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L742)

**Comment by rkooo567** [comment]
I've seen this before when I was working on the hackathon project

**Comment by stephanie-wang** [comment]
Probably duplicate of #14775, but @wuisawesome should confirm.
