### ISSUE TITLE
[Serve] `serve shutdown` doesn't clean up endpoints

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#15085]
### What is the problem?
Serve shutdown should clean up all the instances and delete the checkpoint. Right now if you run `serve shutdown` and create the endpoints/backends again, the endpoints/backends appear already taken.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
hmm weird because we do have this
```
    async def shutdown(self) -> None:
        """Shuts down the serve instance completely."""
        async with self.write_lock:
            for proxy in self.http_state.get_http_proxy_handles().values():
                ray.kill(proxy, no_restart=True)
            for replica_dict in self.backend_state.get_replica_handles(
            ).values():
                for replica in replica_dict.values():
                    ray.kill(replica, no_restart=True)
            self.kv_store.delete(CHECKPOINT_KEY)
```

maybe just add a integration test for this.

**Comment by edoakes** [comment]
@simon-mo I believe this was fixed by @jiaodong's change
