### ISSUE TITLE
[dask-on-ray] Update Dask-on-Ray scheduler to be compatible with concurrent.futures refactor.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#15094]
Dask [recently refactored](https://github.com/dask/dask/commit/ad0e5d140dfc934d94583f8ce50d6b00a04cea38) their local scheduler to be based on `concurrent.futures`, breaking some our dependence on changed/removed internal Dask APIs. We need to update the Dask-on-Ray scheduler to:

1. [P0] Either (a) be compatible with the `concurrent.futures`-based API, or (b) copy the internal APIs we were relying on previously into the Dask-on-Ray implementation.
2. [P1] Remove the dependence on internal Dask scheduler APIs.

**Comment by rkooo567** [comment]
After 1, will this work with the previous dask versions? Are we going to need diverged implementation for different versions?

**Comment by clarkzinzow** [comment]
1(b) would be compatible with both, 1(a) would only be compatible with newer Dask versions. I personally think we should go with 1(b).

**Comment by rkooo567** [comment]
Agree 1(b) sounds better (especially, when there's no special reason to be compatible to their private APIs). Do you happen to know what's the implication? For example, why did they decide to use concurrent.futures based impl instead? Is there performance difference or sth like that?

**Comment by clarkzinzow** [comment]
@rkooo567 The concurrent.futures scheduler API was originally added by a user [in order to have Dask execute tasks as serverless cloud functions](https://github.com/dask/dask/issues/6220), and was adopted generically given that [it offers a much nicer scheduler API](https://github.com/dask/dask/issues/6220#issuecomment-630211954). There were concerns around a potential performance _regression_, but it appears that they used task batching to counter act that and potentially even provide performance improvements.

> In addition to these changes, the local scheduler now batches several tasks per submit call. This is important for cases like multiprocessing where there can be a fair bit of overhead to setting up a process and communicate to/from it. Though this strategy is used in all cases. This results in comparable (if not slightly better) performance in all cases.

See [PR](https://github.com/dask/dask/pull/6322).
