### ISSUE TITLE
[autoscaler][kubernetes] Cluster launcher broken due to ray:nightly Kubernetes import error

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#15095]
### What is the problem?

Autoscaler running in `ray-ml:nightly` image on Kubernetes fails, with a Kubernetes import error.

```from kubernetes import client
ImportError: cannot import name 'client' from 'kubernetes' (/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/__init__.py)
```
 
However, directly `kubectl exec`ing into the pod and open a Python session, `from kubernetes import client` works fine.

Also, this issue does not arise for the `rayproject/ray:nightly` image.

Also, older `ray-ml` images don't have this problem --
`rayproject/ray-ml:73fb5d` does not have this problem.

Maybe an issue with the Python path in recent `ray-ml` images?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
See discussion here:
https://discuss.ray.io/t/autoscaler-on-k8s-import-client-error/1529/7

**Comment by DmitriGekhtman** [comment]
@ijrsvt do you know what might cause an issue like this?

**Comment by DmitriGekhtman** [comment]
Correction -- this affects the default `rayproject/ray:nightly` image as well.

**Comment by DmitriGekhtman** [comment]
Not sure why I didn't see this earlier -- but good news is that the working image mentioned above is only three days old, so I can start bisecting.

**Comment by ijrsvt** [comment]
Hmm, interesting. I just pulled `rayproject/ray:nightly` (`ecb94b`) and ran `python -c "from kubernetes import client"` and did not see any issues.

**Comment by DmitriGekhtman** [comment]
Yeah, for some reason the issue only arises when you run this with the Ray autoscaler... so downstream of Ray start

**Comment by ijrsvt** [comment]
`sys.path` has also not changed between the two

**Comment by ijrsvt** [comment]
Are you seeing this on the operator in particular?

**Comment by DmitriGekhtman** [comment]
Right now seeing with cluster launcher.

**Comment by ijrsvt** [comment]
But on which node is the import error arising?

**Comment by DmitriGekhtman** [comment]
the head

**Comment by DmitriGekhtman** [comment]
I bisected it down to this commit
https://github.com/ray-project/ray/commit/e02bd990d89e24e5df1e563deed7c086b17e3740
cc @AmeerHajAli

**Comment by DmitriGekhtman** [comment]
I'm betting the Operator is unaffected -- going to do a quick test..

**Comment by ijrsvt** [comment]
Ahh yeah, I just added a print statement to the line before `from kubernetes import client`, and it looks like the 'kubernetes' module being imported is:
```
<module 'kubernetes' from '/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/__init__.py'>
```

**Comment by DmitriGekhtman** [comment]
Confirming operator is unaffected..

**Comment by DmitriGekhtman** [comment]
This makes sense.

**Comment by DmitriGekhtman** [comment]
Aah, yeah should have pasted the stacktrace from discuss.ray.io
```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 276, in run
    self._initialize_autoscaler()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 125, in _initialize_autoscaler
    event_summarizer=self.event_summarizer)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 86, in __init__
    self.reset(errors_fatal=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 521, in reset
    raise e
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 479, in reset
    self.config["cluster_name"])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/providers.py", line 186, in _get_node_provider
    provider_cls = _get_node_provider_cls(provider_config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/providers.py", line 162, in _get_node_provider_cls
    return importer(provider_config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/providers.py", line 54, in _import_kubernetes
    from ray.autoscaler._private.kubernetes.node_provider import \
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/__init__.py", line 1, in <module>
    import kubernetes
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/__init__.py", line 2, in <module>
    from kubernetes.config.config_exception import ConfigException
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/config.py", line 6, in <module>
    from kubernetes import client
ImportError: cannot import name 'client' from 'kubernetes' (/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kubernetes/__init__.py)
```

**Comment by ijrsvt** [comment]
Ah, totally missed that part!
