### ISSUE TITLE
[tune] progress.csv has data rows but no header - breaks restore

### ISSUE THREAD

**Issue by max0x7ba** [ray-project/ray#15106]
### What is the problem?
progress.csv has data rows but no header when a trial is terminated before reporting anything and then restarted.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray-1.2.0
torch-1.8.1
Ubuntu 20.04 LTS

### Reproduction (REQUIRED)
`CSVLogger` constructor does:

```
self._continuing = os.path.exists(progress_file)
self._file = open(progress_file, "a")
```

Instead, it should do:
```
self._continuing = os.path.exists(progress_file) and os.path.getsize(progress_file) > 0
self._file = open(progress_file, "a")
```

**Comment by max0x7ba** [comment]
Thinking more about it, `CSVLogger` shouldn't create an empty progress.csv at all. Rather only create it upon first report.

**Comment by krfricke** [comment]
This might be related to #18892. Taking a look now (sorry for the delay...)
