### ISSUE TITLE
Use only 1 of 2 GPU when connecting node to cluster

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#15114]
When connecting a node to an existing Ray cluster, is it possible to specify which GPU device should be used to process jobs submitted to the cluster?

Running this command

    ray start --address=<address>

seems to make all GPU devices on the node available to the cluster. I am looking for a way to only use GPU 1, and not GPU 0.

Thanks

**Comment by richardliaw** [comment]
CUDA_VISIBLE_DEVICES=1 ray start should work for you.

**Comment by nyxynyx** [comment]
Thanks!
