### ISSUE TITLE
What's the best practice of integrating customized environment on specific port?

### ISSUE THREAD

**Issue by dickren123** [ray-project/ray#15113]
[Rllib]

Hi, I am new to Rllib and want to get a best practice of this scenario:  I package a gaming environment (C++) into a HTTP service (e.g., on port 10000) which can be integrated into gym interfaces. (e.g., in the 'step' method calling this interface to obtain the updated observations). I want to know how to realize multi environment in such scenario? Do I have to create multiple environments (e.g., from 10000-10050) and round robin these ports manually? Or there is another mechanism in rllib automatically creating multiple envs based on one gym of only port 10000? 

I checked the doc and found out that PolicyClient-PolicyServer is similar to this requirement but in the Client side I still have to create a gym env in which only port 10000 is integrated.

**Comment by brollb** [comment]
The config passed to each environment has a "worker_index" attribute which can be used to determine the port that should be used. The game instances can either be long-lived processes running independently or they can be automatically spun up as a subprocess (knowing the worker index allows you to ensure the ports won't collide!).

One tricky thing if you spinning up the game engines in a subprocess is that the buffer for the game stdout may fill up and cause training to halt with no obvious reason. If I recall correctly, I worked around this by updating the command to the subprocess to something like `pyrogenesis | grep -i "RL interface listening"` as this will filter out all other stdout and the buffer shouldn't ever contain more than the initial "listening" message. (In this example I was using [0 AD](http://play0ad.com/) so `pyrogenesis` is the name of the game engine.)

I know this is a bit late but hopefully this is helpful! (If you figured it out, hopefully it is helpful to someone else with this problem!)
