### ISSUE TITLE
[tune] How to get summary table after tune.run() has finished?

### ISSUE THREAD

**Issue by athenawisdoms** [ray-project/ray#15127]
When `tune.run()` has finished running, is it possible to grab a DataFrame or table of the table that is frequently printed out during training?

This table contains the hyperparameters of all the trials and some metrics. 

```
+-------------------+------------+-------+-----------+-----------------+--------+------------------+------------+
| Trial name        | status     | loc   |   dropout |   learning_rate |   iter |   total time (s) |       loss |
|-------------------+------------+-------+-----------+-----------------+--------+------------------+------------+
| train_d48b7_00000 | TERMINATED |       |       0.5 |          5e-05  |     39 |          349.52  |   0.112351 |
| train_d48b7_00001 | TERMINATED |       |       0.6 |          5e-05  |     39 |          351.183 |   0.121403 |
| train_d48b7_00002 | TERMINATED |       |       0.7 |          5e-05  |     39 |          351.692 |   0.141085 |
+-------------------+------------+-------+-----------+-----------------+--------+------------------+------------+
```

Or another summary table that shows some overview of the entire Tune run. I will be using this summary data for automatically sending a Slack notification.

**Comment by amogkam** [comment]
Hey @athenawisdoms, yes you should be able to get all this information via the `ExperimentAnalysis` API that's returned by `tune.run` (https://docs.ray.io/en/latest/tune/key-concepts.html#analysis). In particular, the `results_df` will give you a pandas dataframe with latest information for all the trials, which should be equivalent to what's being printed out during tune.run.

I am going to close this for now, but please feel free to re-open if there is more information that you would like that cannot be retrieved from the `ExperimentAnalysis` API!
