### ISSUE TITLE
[tune] Support resolving grid search variables before random samples

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#15126]
Right now, grid search variables are resolved before the random samples are generated. 

If we could toggle the order of resolution, we could support this: https://discuss.ray.io/t/is-there-a-way-to-run-the-same-hyperparameter-configuration-multiple-times/1412/12

**Comment by richardliaw** [comment]
cc @krfricke for thoughts or suggestions!

**Comment by krfricke** [comment]
I've seen this request before, and generally I agree that it makes sense to support this. I remember stumbling upon this when refactoring the search space API. 
So the reasoning here would be that we only want the grid search variable to vary between trials, and all other resolved variables should remain constant.

Do we want this to be configurable (with an en environment variable or so)? This is mostly to enable full backwards compatibility.

**Comment by richardliaw** [comment]
I think it would be just a parameter like `BasicVariantGenerator(resolve_order="grid-random" | "random-grid")`. I don't think we need to support this anywhere else? though not sure.

**Comment by calvinwy** [comment]
Is this completed and merged into the latest version if I update my Ray tune over conda-forge repo?  Also, is there instruction somewhere which describe how to use this?

**Comment by krfricke** [comment]
Hi @calvinwy, it is not included in 1.4.1, but will be included in the upcoming 1.5.0 release.

The documentation is a bit sparse. We're currently having trouble with the master documentation on `docs.ray.io`, but here's a link to the API reference: https://ray--16501.org.readthedocs.build/en/16501/tune/api_docs/suggestion.html#random-search-and-grid-search-tune-suggest-basic-variant-basicvariantgenerator

**Comment by calvinwy** [comment]
Thanks @krfricke, any idea when will the 1.5.0 be available on conda-forge?

> Hi @calvinwy, it is not included in 1.4.1, but will be included in the upcoming 1.5.0 release.
> 
> The documentation is a bit sparse. We're currently having trouble with the master documentation on `docs.ray.io`, but here's a link to the API reference: https://ray--16501.org.readthedocs.build/en/16501/tune/api_docs/suggestion.html#random-search-and-grid-search-tune-suggest-basic-variant-basicvariantgenerator

**Comment by krfricke** [comment]
We're working on release testing as we speak and hope to release 1.5.0 this week (tentatively). I'm not sure how we manage conda releases (cc @richardliaw can you help?) but it should be available shortly after.

**Comment by calvinwy** [comment]
@krfricke I just checked it on conda-forge, it seems like it is still 1.4.0, do you mind to check an follow up on this?  Many thanks!

https://anaconda.org/conda-forge/ray-tune

**Comment by krfricke** [comment]
Hi @calvinwy, I reached out internally to see how we can integrate the update process into our release process. I'm co-managing the next (1.6.0) release and will see that this will be included soon.

**Comment by calvinwy** [comment]
@krfricke, but this is included in 1.5.0 already right?  If so, is it possible to have it makes it way to conda-forge by any chance?

**Comment by krfricke** [comment]
I'm on it right now, but it might take some time (we have to update some of the patches required by conda builds)

**Comment by calvinwy** [comment]
@krfricke I see 1.5.0 on conda-forge now, thanks a lot for your effort, really appreciate it!! ;)

**Comment by krfricke** [comment]
Happy to do it :-)

**Comment by calvinwy** [comment]
@krfricke hi Kai, there seems to be a problem with `num_samples`.  Using constant_grid_search=True, the `num_samples ` doesn't work anymore.  It only sample each grid variable once.
