### ISSUE TITLE
[serve] Make HTTP proxies a normal Serve deployment

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15135]
The behavior we want w/ the HTTP proxies is quite similar to other deployments and this would allow us to deduplicate code and dogfood deployments a bit. We could also get some benefits such as the ability to do rolling updates for config and argument changes (e.g., route table updates, changing the port the HTTP server is listening on or adding a middleware).

The only thing blocking this at the moment is the ability to have resizable placement groups, which would allow us to maintain the existing placement strategy of one proxy per node. There may be a hacky temporary workaround for this, but I haven't thought of a good one yet (I'd like to avoid hard-coding scheduling logic for this special case). cc @rkooo567

**Comment by akshay-anyscale** [comment]
Still needed?

**Comment by edoakes** [comment]
Dup of https://github.com/ray-project/ray/issues/19151
