### ISSUE TITLE
[rllib][ray client] Rock paper scissors with Ray client

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#15159]
### What is the problem?

The rllib rock-paper-scissors multi-agent example currently fails with Ray client due to missing support for `ray.get_gpu_ids()`
https://github.com/ray-project/ray/blob/master/rllib/examples/rock_paper_scissors_multiagent.py 
https://github.com/ray-project/ray/issues/15010

Once `ray.get_gpu_ids()` support is added, the success of `rock_paper_scissors_multiagent.py` example with Ray client should be verified.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
The issue ultimately comes from here:

https://github.com/ray-project/ray/blob/64cc092959264cea42099690f13eceb6036e34d8/rllib/evaluation/rollout_worker.py#L527-L530

Is the correct fix to add a check that we're not in client mode to the `if` statement?

cc @sven1977 @AmeerHajAli @ijrsvt

**Comment by DmitriGekhtman** [comment]
Actually, `ray.get_gpu_ids` should probably return any empty list when called from client mode.

**Comment by AmeerHajAli** [comment]
closed in https://github.com/ray-project/ray/pull/15185.
@DmitriGekhtman , can you please make sure to close issues when their PR is merged?
