### ISSUE TITLE
Is 1 Gigabit Ethernet Sufficient Bandwidth for Multiple (4) Nodes?

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#15153]
How do we plan the network capacity needed to run Ray/Tune distributed training of a model for 4 nodes? Is it sufficient to use the regular 1 gigabit ethernet connections to connect the nodes together? 

Or will gigabit ethernet bottleneck training for this setup and instead require 10GbE, and higher?

**Comment by richardliaw** [comment]
How do you plan to use the distributed training? Is it 1 model per node?

**Comment by nyxynyx** [comment]
@richardliaw 1 model across 4 nodes. 

If 1 gigabit network is not sufficient, then 1 model per node.

**Comment by richardliaw** [comment]
I think 1 Gb connection across nodes seems quite slow if you plan to do model-parallel training. However, it is still usable. Also, if you're doing 1 model across 4 nodes, the performance characteristics doesn't seem particularly relevant to Ray right (since you're probably using NCCL to do cross-node communication)?

**Comment by nyxynyx** [comment]
@richardliaw Good point, thanks!

Is 1 Gb for 4 nodes to run 1 model per node generally considered insufficient? 

For example, if the model is 1 GB, the training/validation data is 20 GB, and training takes about 1 hour per trial, can we say that the initial transfer of 21 GB of data at 100 MB/s will take about 3.5 mins per node, and a total of 10 mins for the first epoch to start on all 4 nodes if the head node already contains the model and data? So like a 5% (best case) and 15% (worse case) increase in training time if using 1 Gbe to connect 4 nodes.
