### ISSUE TITLE
[tune] Search/Restore for ASHA

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#15177]
### Describe your feature request

If I pause an tune run, change the search space bounds, and resume, tune will continue using the same bounds as before. 

This means that, if I want to do a course-to-fine hyperparameter search, I can't pause a Tune run, constrain the search space, and resume. Instead, I need to start a new experiment from scratch. Given our dataset sizes, each trial is quite expensive to train, so it would be great if we could resume a tune run so that ASHA can terminate underperforming trials instead of spending a lot of time re-establishing a baseline.

cc @richardliaw

**Comment by richardliaw** [comment]
@krfricke do you think you could take this sometime? It should be similar to what we're doing for search algorithms.

cc @worldveil

**Comment by krfricke** [comment]
So generally you should just be able to pickle the scheduler object, e.g.:

```
scheduler = ASHAScheduler(...)

tune.run(
    # ...
    scheduler=scheduler)
    
pickle.dump(scheduler, "scheduler.ckpt")
# ...
scheduler = pickle.load("scheduler.ckpt")
tune.run(
    # ...
    scheduler=scheduler)
```

However I've submitted a PR in #15438 that wraps around pickle nicely, so you can use it like this:

```
scheduler = ASHAScheduler(...)

tune.run(
    # ...
    scheduler=scheduler)
    
scheduler.save("scheduler.ckpt")
# ...
scheduler = ASHAScheduler(...)
scheduler.restore("scheduler.ckpt")
tune.run(
    # ...
    scheduler=scheduler)
```

So this is very straightforward. The main question I have is if you need support for this to happen automatically, e.g. like searcher checkpoints, and that scheduler state should be loaded when resuming runs. How are you currently stopping and resuming tune trials?

**Comment by crypdick** [comment]
Thanks @krfricke ! I currently stop the trial with a keyboard interrupt and terminate the EC2 machine. Then, to resume, I find the trial on S3 and resume from the run_id. Since resuming from remote checkpoints is broken (see https://github.com/ray-project/ray/issues/14977) I first sync down the trial dir manually and resume from local.

In my opinion the searcher checkpoints should be sync'd to S3, since otherwise I'd have to manually upload these pkls to the remote Tune S3 path. I think one would expect that resuming an experiment would restore the history of which hyperparamters were already tried and what their performance was.
