### ISSUE TITLE
[Metrics] Counter::inc() does not support custom values

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#15179]
### What is the problem?
I am unable to use the `metrics.Counter` when I want to increment by a non-one value. 
This is the intended behavior as per the [example in prometheus's python client](https://github.com/prometheus/client_python#counter) 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Nightly: `195f81`

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
from ray.util import metrics
counter = metrics.Counter("my_counter")
counter.inc()
# my_counter == 1
counter.inc(30)
# my_counter == 2 (should equal 31)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
Yeah @clarkzinzow also pointed this out. cc @edoakes

**Comment by rkooo567** [comment]
We should probably remove the argument within inc() or use Sum instead. Seems like prometheus doesn't support any argument in the `inc` method, so we should probably follow that?

**Comment by ijrsvt** [comment]
@rkooo567 Prometheus *does* have an argument in `inc` (see the example I linked above).

**Comment by rkooo567** [comment]
Ah, I see. Then we should just use SUM under the hood.
