### ISSUE TITLE
[ray client] Support public API: ray.kill()

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#15176]

**Comment by DmitriGekhtman** [comment]
This appears to be implemented here:
https://github.com/ray-project/ray/blob/eed34092f26dcedadfcf469ec041bdda70ed1e24/python/ray/util/client/api.py#L136

Is the remaining task simply to expose this method in `RayAPIStub`?

@iycheng or @ericl , could you provide some context for what goes in `ClientApi` vs `RayAPIStub`?

**Comment by DmitriGekhtman** [comment]
Already implemented, see https://github.com/ray-project/ray/pull/15178#issuecomment-816237961 .

**Comment by AmeerHajAli** [comment]
Reopening until we make sure metadata is added.
cc @DmitriGekhtman
