### ISSUE TITLE
Ability to re-use FastAPI across deployments

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#15180]
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by edoakes** [comment]
@simon-mo what happens if I try to do this today?

**Comment by edoakes** [comment]
(wondering if we should bump up the priority if it's confusing)

**Comment by simon-mo** [comment]
The routes might be over-ridden, dependening when `App.deploy()` is called.

**Comment by simon-mo** [comment]
PR linked. btw, in FastAPI the routes are first-declared-first-used: 
```
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def func_v1():
    return "first"

@app.get("/")
def func_v2():
    return "second"
```

"first" will always get served for `"/"`
