### ISSUE TITLE
`RolloutWorker.set_weights.remote(weights)`

### ISSUE THREAD

**Issue by kaninaba94** [ray-project/ray#15196]
I am trying to understand the workings of `ray.tune.run(PPOTrainer, ...)`. For that purpose, I need to understand the lines shown below.
https://github.com/ray-project/ray/blob/c8f8a8e51005cb3aab64a9e98f6e709b4976c03b/rllib/evaluation/worker_set.py#L106-L111
In my understanding, `self.remote_workers()` (line 110) points to a list of `RolloutWorker`s. So when you call `e.set_weights.remote(weights)`, my understanding of Python tells me to look for an object called `set_weights` that has a method called `remote(weights)`. Or else, look for a method that has a nested method calles `remote`. The `RolloutWorker` class has a method `set_weights`, but I don't know what `remote` points at. 
https://github.com/ray-project/ray/blob/c8f8a8e51005cb3aab64a9e98f6e709b4976c03b/rllib/evaluation/rollout_worker.py#L707-L720

Can anyone help me out?

**Comment by mvindiola1** [comment]
@kaninaba94 remote is thr ray convention and wrapper for indicating tgat you want ray to asynchronously schedule and execute a python function/method. Have a look here for an introduction: https://docs.ray.io/en/master/walkthrough.html

**Comment by kaninaba94** [comment]
thank you very much!
