### ISSUE TITLE
ray.worker.global_worker.run_function_on_all_workers will run function twice on the current driver

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#15201]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

```python
import ray
import os
import time

if __name__ == '__main__':
    ray.init()
    ray.worker.global_worker.run_function_on_all_workers(
        lambda x: print(os.getpid())
    )
    # wait for spinning up workers
    time.sleep(1)
```

output:

```
8264
8264
(pid=8288) 8288
(pid=8284) 8284
(pid=8286) 8286
(pid=8289) 8289
(pid=8287) 8287
(pid=8285) 8285
(pid=8291) 8291
(pid=8290) 8290
```
This is done intentionally:

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/worker.py#L358-L360

https://github.com/ray-project/ray/blob/4289fa8d43dc4b38a0066cf54a0dadd84a658a77/python/ray/_private/import_thread.py#L164

I am not sure if this is expected or a bug. Someone need to confirm it.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
> and job_id != self.worker.current_job_id.binary()): 

You mean this line right? I think this is intentional (we run functions only for the same job).

**Comment by suquark** [comment]
@rkooo567 `function({"worker": self})` is intentional to run the exported function in the current driver. `job_id != self.worker.current_job_id.binary())` is intentional to run the function exported by the current driver in the current driver. I do not know why we need both.

**Comment by suquark** [comment]
I think `job_id != self.worker.current_job_id.binary()` should be `job_id == self.worker.current_job_id.binary()`
