### ISSUE TITLE
Kubernetes operator images in 1.2.0 pin to latest image tag

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/ray#15222]
### What is the problem?
https://github.com/ray-project/ray/blob/b87fc1be5505c577f01807fd342e0cdb2e129081/doc/kubernetes/ray-cluster.yaml#L62

If user want to use a stable ray version, they may go to tag or a release branch. The problem is images in most of these branches/tags pin to `nightly` which is not a good practice. 

User will install latest images (master) with 1.2.0 manifest. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
1.2.0

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
git clone https://github.com/ray-project/ray.git
kubectl -n ray apply -f path_to_ray_manifest
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by pcmoritz** [comment]
Thanks for reporting, this should indeed be fixed! Instead of `nightly`, we should use the `latest` Ray here, which is always the latest Ray released Ray version. We are already doing that for the non-k8s autoscaler, see https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml

cc @DmitriGekhtman

**Comment by Jeffwan** [comment]
Em. even `latest` is used there, it's still a problem if user uses "stable" version. 

I think the problem may be addressed from version/ release managed perspective.  If community cut tag against master every time, then all tags will have manifests using `latest` will points to master builds but the manifest is still in older version. For example, example_cluster specs will not be compatible with `latest` operator.

**Comment by ijrsvt** [comment]
The image is now pinned!
