### ISSUE TITLE
[serve] Blacklist replicas in the ServeHandle if they return a RayActorError

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15223]
Once a replica returns a RayActorError, it will never be used again as the controller will spin up a new actor to replace it. We should remove it from the available replicas in the handle in this case to avoid repeatedly failing requests.

**Comment by edoakes** [comment]
cc @simon-mo

**Comment by akshay-anyscale** [comment]
Is this solved by the Denylist work that Shreyas is doing?

**Comment by edoakes** [comment]
yes it is, duplicate so closing
