### ISSUE TITLE
[RaySGD] Potential bug with PyTorch optimizer construction

### ISSUE THREAD

**Issue by zhisbug** [ray-project/ray#15258]
### What is the problem?
The current RaySGD follows the workflow below:
1. Users override operator's `setup()` function, and construct `model`, `optimizer`, and `criterion` in it;
2.  Users register the created `model`, 'optimizer`, `criterion` via `register()` function;
3. The register function will check whether `use_gpu` is True and if yes, move the `model` and `criterion` to GPU via a `.cuda()` call at backend.

This has a potential problem: the optimizer created by the user in the `setup()` function was constructed before the `model` and `criterion` are moved to GPU (via `.cuda()`). This behavior seems to deviate from what PyTorch is suggesting users do. See [this note from PyTorch doc](https://pytorch.org/docs/stable/optim.html#constructing-it).

According to[ some discussion in PyTorch Forum](https://discuss.pytorch.org/t/effect-of-calling-model-cuda-after-constructing-an-optimizer/15165/3), this will cause issues for optimizer which will allocate tensor buffers at construction, such as Adagrad, but will not cause issues for optimizers which allocate tensor buffers at the first call of its `step()` function.

**Comment by zhisbug** [comment]
@richardliaw

**Comment by amogkam** [comment]
Hey @zhisbug thanks for raising this issue!

We have been developing a new version of Ray SGD with a cleaner API which you can see here: https://docs.ray.io/en/master/raysgd/v2/raysgd.html. In Ray SGD v2, the user can supply their own training function containing all of the training logic, and thus can control when the model is moved to CUDA, so I would recommend you try it out. To easily migrate from Ray SGD v1 to v2 you can check out this guide: https://docs.ray.io/en/master/raysgd/v2/migration-guide.html.

Let me know if you have questions, I am happy to help!
