### ISSUE TITLE
[DataFrame] ray.transpose() not working with NaN values

### ISSUE THREAD

**Issue by hsubbaraj** [ray-project/ray#1525]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.2
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: ray_df.transpose()

### Describe the problem
@devin-petersohn 
ray_df.T doesn't work with np.NaN values. It drops all values (even if not NaN) and returns an empty dataframe.

### Source code / logs

Test DataFrames:
<img width="584" alt="screen shot 2018-02-07 at 4 48 56 pm" src="https://user-images.githubusercontent.com/8093660/35949527-d3a00d76-0c26-11e8-942e-15da64bca90c.png">

Code for tests:
<img width="584" alt="screen shot 2018-02-07 at 4 48 56 pm" src="https://user-images.githubusercontent.com/8093660/35949592-32cb3f46-0c27-11e8-9eae-fd16834b29b0.png">

Output for test_transpose (the first is ray_df.T, the second is pandas_df.T):
<img width="854" alt="screen shot 2018-02-07 at 4 50 00 pm" src="https://user-images.githubusercontent.com/8093660/35949559-f9d839dc-0c26-11e8-8aee-58fb7d9e46b4.png">

**Comment by devin-petersohn** [comment]
It turns out that it didn't drop all values, just ones on the partition with `np.nan` s. In this example, the majority of the dataframe was nans, so that is why this behavior was observed.
