### ISSUE TITLE
Why are there symlinks from python/ray to new_dashboard/, rllib/ and streaming/python/?

### ISSUE THREAD

**Issue by fcardoso75** [ray-project/ray#15267]
I'm building ray on a Windows 10 machine (Developer mode enabled and git core.symlinks=true) but the following symlinks are broken (they are created as file symlinks instead of directory symlinks):

Directory python\ray:

```
new_dashboard symlink to ..\..\dashboard
rllib symlink to ..\..\rllib
streaming symlink to ..\..\streaming\python
```

For the build to work, I have to manually delete them and recreate using the command:

```
mklink /D <symlink_name> <target_directory>
```

I would like to fix these issues but before doing so, I would like to ask why there are symlinks under python\ray. Couldn't we move those three directories under python\ray or have the main bazel build file refer to the builds in those directories instead?

Thanks,

@raulchen

**Comment by fyrestone** [comment]
I the `new_dashboard symlink to ..\..\dashboard` breaks ray build on Windows?

**Comment by fcardoso75** [comment]
The streaming symlink to ..\..\streaming\python breaks the build on Windows, but the others are not working properly either since they are created as file symlinks instead of directory symlinks (that difference exists on Windows).

**Comment by mehrdadn** [comment]
Have you enabled symlinks? `git config --local core.symlinks true`

**Comment by mehrdadn** [comment]
Sorry I just saw that in your question

**Comment by fcardoso75** [comment]
Tagging @pcmoritz

**Comment by mehrdadn** [comment]
@fcardoso75 I just remembered something. Did you set `core.symlinks` to `true` **BEFORE** cloning the repo, or after? It might be too late to do it after cloning... see [here](/bazelbuild/bazel/issues/5437#issuecomment-605533843).

**Comment by fcardoso75** [comment]
@mehrdadn:

@pcmoritz and I git set core.symlinks = true BEFORE checking out the repo in our machines. I happened to clone it more than once to ensure I didn't make a mistake.

**Comment by fcardoso75** [comment]
Here it is what I see after I git clone the repo (I removed the extra dir information which would only clutter the output):
```
D:\ray\python\ray>dir

04/17/2021  04:02 AM    <SYMLINK>      new_dashboard [..\..\dashboard]
04/17/2021  04:02 AM    <SYMLINK>      rllib [..\..\rllib]
04/17/2021  04:03 AM    <SYMLINK>      streming [..\..\streaming\python]

D:\ray\python\ray>

D:\ray\python\ray>cd streaming
The directory name is invalid.

D:\ray\python\ray>dir streaming

 Directory of D:\ray\python\ray

04/17/2021  04:03 AM    <SYMLINK>      streaming [..\..\streaming\python]
               1 File(s)              0 bytes

D:\ray\python\ray>cd rllib
The directory name is invalid.

D:\ray\python\ray>dir rllib

 Directory of D:\ray\python\ray

04/17/2021  04:02 AM    <SYMLINK>      rllib [..\..\rllib]
               1 File(s)              0 bytes

D:\ray\python\ray>cd new_dashboard
The directory name is invalid.

D:\ray\python\ray>dir new_dashboard

 Directory of D:\ray\python\ray

04/17/2021  04:02 AM    <SYMLINK>      new_dashboard [..\..\dashboard]
               1 File(s)              0 bytes

D:\ray\python\ray>
```

And if we run these commands on Powershell:

```
PS D:\ray\python\ray> Get-ItemPropertyValue -Path .\rllib -Name Attributes,Target
Archive, ReparsePoint
..\..\rllib
PS D:\ray\python\ray> Get-ItemPropertyValue -Path .\streaming -Name Attributes,Target
Archive, ReparsePoint
..\..\streaming\python
PS D:\ray\python\ray> Get-ItemPropertyValue -Path .\new_dashboard -Name Attributes,Target
Archive, ReparsePoint
..\..\dashboard
PS D:\ray\python\ray>
```

Notice that the symlink swere created as Archive symlinks and not as Directory symlinks. Perhaps it is a git for Windows bug, maybe the original Unix links were created in a way that Windows doesn't support, there could be many explanations.

I wrote a small Powershell script to replace the broken symlinks with working ones., and I'm ready to submit a PR, but before doing that I think we should see why we need those symlinks in first place.

**Comment by mehrdadn** [comment]
Could you paste the `git clone` command you're running similarly (with the surrounding text)?

**Comment by fcardoso75** [comment]
```
D:\>git clone https://github.com/ray-project/ray.git
Cloning into 'ray'...
remote: Enumerating objects: 119481, done.
remote: Counting objects: 100% (1049/1049), done.
remote: Compressing objects: 100% (663/663), done.
remote: Total 119481 (delta 582), reused 694 (delta 376), pack-reused 118432
Receiving objects: 100% (119481/119481), 112.64 MiB | 11.60 MiB/s, done.
Resolving deltas: 100% (87276/87276), done.
Checking out files: 100% (3425/3425), done.

D:\>
```

**Comment by mehrdadn** [comment]
Strange. And this is plain Git for Windows, right? not MSYS or Cygwin or something like that?

**Comment by fcardoso75** [comment]
That's correct.

```
PS D:\> git --version
git version 2.16.2.windows.1

PS D:\> get-command git
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.16.2.1   C:\Program Files\Git\cmd\git.exe

PS D:\>
```

**Comment by mehrdadn** [comment]
I feel like this shouldn't matter unless you're using MSYS2 somewhere, but try running `Set MSYS=winsymlinks:native`?

**Comment by mehrdadn** [comment]
(Then clone/checkout again)

**Comment by fcardoso75** [comment]
I don't think that wouldn't help in my case. I don't use mingw or cygwin

**Comment by mehrdadn** [comment]
Yeah I realize it shouldn't matter, but I just checked git-for-Windows's source code and I think it might matter anyway. See [here](/git-for-windows/git/commit/3d1cd831f1fe86e1924c1a967b383191d930b01c).

**Comment by mehrdadn** [comment]
I'm guessing you wouldn't notice this in CI because it's already running under MSYS2, so the `MSYS` environment variable would already be set. And I always have this set locally, so it doesn't matter for me. But for other people who go straight from the command prompt or PowerShell, I guess it would matter.

**Comment by fcardoso75** [comment]
I think I might have solved the problem (without my script). I upgraded my git for Windows to the newest version (2.31.1), git cloned ray again and the symlinks were already correct. I'm running a build now.

```
PS D:\> Get-Command git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.31.1.1   C:\Program Files\Git\cmd\git.exe

PS D:\>
```

**Comment by mehrdadn** [comment]
Huh, interesting. That means you didn't set `MSYS` after all, right?

**Comment by fcardoso75** [comment]
No, I did not, but I see that git for Windows comes with a mingw environment. I don't know if git uses it or just makes it available for the users, but it is present at C:\Program Files\Git\mingw64

**Comment by mehrdadn** [comment]
Oh I think that's some minimal environment just to support its own internal scripts, since git uses shell scripts for some tasks.

Looking through their repo, it seems this is something they added support for recently [here](/git-for-windows/git/pull/3147/commits/95a1de263958878e3dfffa9251f48dc75e442ccc), so that explains why your upgrade worked!

**Comment by fcardoso75** [comment]
It worked on my machine.
I will ask @pcmoritz to do the same on his machine before closing this issue.

**Comment by mehrdadn** [comment]
I actually would suggest getting rid of symlinks in any case if there's enough interest. I was hoping to do this myself when I was porting Ray to Windows, since I did expect people to run into issues with it eventually and because in general symlinks and version control don't mix very well, but I imagined it would be low priority for everyone, so I didn't bother. But I think it wouldn't be a bad idea if there's more motivation for it now.

**Comment by fcardoso75** [comment]
I think that would be a good idea. I'm very new to ray, but I don't see many benefits in using symlinks in the source tree.

**Comment by fcardoso75** [comment]
One more benefit in removing the symlinks from the source tree:
Developer mode started with Windows 10. People might want to build on other systems like Windows 8.1 or Windows Server,  and on Windows Server they might not have the permissions to enable symlink support.
