### ISSUE TITLE
Ray Dashboard not showing additional nodes

### ISSUE THREAD

**Issue by joshuaathomas94** [ray-project/ray#15264]
### What is the problem?

I am attempting to start a node from my terminal remotely. I run the ray start --address='ip_address:6379' --redis-password='password' command from the node and it produces no errors and seemly connects. But when I access the dashboard I can only see the host. 

I have a head node running on a remote server and added port forwarding rules to the server for ports 8265, and 6379. I also started the node with --dashboard-host=0.0.0.0 to view the dashboard from outside of my private network. But no matter what I do whenever I add a node from another remote device nothing shows up on the dashboard. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
Ray installed from (source or binary): source
Ray version: 1.2.0
Python version: 3.8.5

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sheecegardezi** [comment]
I was getting into similar problem. What I realized was on node the cmd 

`$ ray start --address=xyz --redis-password='xyz' --block`

Needs to keep running so i experemented with adding & and it worked for me

`$ ray start --address=xyz --redis-password='xyz' --block &`

**Comment by joshuaathomas94** [comment]
> I was getting into similar problem. What I realized was on node the cmd
> 
> `$ ray start --address=xyz --redis-password='xyz' --block`
> 
> Needs to keep running so i experemented with adding & and it worked for me
> 
> `$ ray start --address=xyz --redis-password='xyz' --block &`

Tried it, but didn't work, thanks anyways.

**Comment by scottsun94** [comment]
Bump it ^

**Comment by scottsun94** [comment]
Closing for now. Please reopen if you still see this issue
