### ISSUE TITLE
Feature request: detect if actors requests are queueing up

### ISSUE THREAD

**Issue by danwallach** [ray-project/ray#15262]
With a progress-bar actor, I had some code that was sending it update messages faster than it could consume them (probably around 10k messages per second). This caused it to get backed up, and I stopped seeing visible updates, since the requests to read data from the same actor were getting backed up in the message queue with all the pending writes.

The fix was simple: batching together messages to the actor, to get the message rate down to something reasonable. Problem solved.

Feature request: it would be handy for actors to have a mechanism to detect if message processing is slower than message arrival, and to generate a suitable warning message. I fixed this by just making a wild guess and hacking up a solution, and it worked, but I’d been trying a bunch of other things first before I had the lucky guess.

**Comment by richardliaw** [comment]
What if you had some sort of autoscaling actor pool, where new actors (and nodes) were provisioned according to load?

**Comment by danwallach** [comment]
In my specific case, I was using an actor to collect information on a big job, so remote tasks were "reporting back" to the actor, which was collecting statistics. That actor was mutating a Python dictionary with state, which works fine until the request rate gets too large. That wouldn't naturally map to an "actor pool" unless Ray also offered a scalable, mutable, transactional, distributed dictionary abstraction.

I mean, if Ray did that, it would be fantastic. In the meanwhile, it might be easier to add some logic to notice when requests are queueing up for an actor faster than it can process them.
