### ISSUE TITLE
rllib install failed

### ISSUE THREAD

**Issue by Meta-YZ** [ray-project/ray#15268]
When I install rllib , happened some erros:

 Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: six, pyasn1, urllib3, rsa, pyparsing, pyasn1-modules, protobuf, multidict, idna, chardet, cachetools, yarl, typing-extensions, requests, pytz, packaging, numpy, googleapis-common-protos, google-auth, future, attrs, async-timeout, scipy, pyrsistent, pyglet, psutil, Pillow, opencensus-context, nvidia-ml-py3, hiredis, google-api-core, cloudpickle, blessings, aiohttp, redis, pyyaml, python-dateutil, py-spy, prometheus-client, opencv-python, opencensus, msgpack, jsonschema, gym, grpcio, gpustat, filelock, colorful, colorama, click, atari-py, aioredis, aiohttp-cors, tensorboardX, tabulate, ray, pandas, opencv-python-headless, lz4, dm-tree
    Running setup.py install for atari-py ... error

How can I solve this problem?

**Comment by Yuanzhuo-Liu** [comment]
ubuntu 18.04

**Comment by Misterion777** [comment]
Faced same issue, you should install following packages: `git, cmake, zlib1g, zlib1g-dev`,
as stated [here](https://github.com/openai/atari-py#installation-from-source).
