### ISSUE TITLE
Speeding up serialization of pandas dataframes.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1527]
See earlier related discussion at dask/distributed#614, some related discussion in apache/arrow#1360.

If a dataframe consists of numerical data, it should already be handled efficiently. However, if it contains strings, then those columns are represented in pandas as numpy object arrays. We currently serialize numpy object arrays by converting them to lists and then serializing the lists. While iterating through the list, if we encounter an object that pyarrow doesn't know how to serialize, then we call a custom serializer.

This can often be made faster by just pickling the numpy object array (which is what the pyarrow `pandas_serialization_context` does). However, that fails to handle objects in the numpy array which require custom serializers (custom user-defined objects) or objects that can't be pickled.

In particular, we'd like to support serializing numpy arrays of `ObjectID`s, but `ObjectID`s are not pickleable (see #1453).

**Some options:**
- Make ObjectIDs pickleable (this is simple, but could make it easier to write incorrect code).
- Catch the exception when pickle fails on the numpy object array and then back off to the list approach (this will work in the `ObjectID` case because we raise an exception during pickling, but usually the exception occurs when unpickling, and that will be much harder to handle).
- Store some extra information that lets the serialization context know that it is dealing with a numpy object array that came from a pandas dataframe. This could be done by wrapping the numpy object array in a custom class which is only used internally in Ray or pyarrow.

cc @devin-petersohn @pcmoritz

**Comment by robertnishihara** [comment]
See one approach in apache/arrow#1581.

**Comment by devin-petersohn** [comment]
> Make ObjectIDs pickleable (this is simple, but could make it easier to write incorrect code)

What is the incorrect code possible here? Is the problem that the user might call `ray.get` and get another `ObjectID`?

**Comment by robertnishihara** [comment]
Hmm.. I guess I'm slightly worried about users writing remote functions or actors that close over `ObjectID`, but maybe that wouldn't really cause any issues.

**Comment by devin-petersohn** [comment]
Do we expect better (de)serialization performance for lists of `ObjectIDs` if they can be pickled?

**Comment by robertnishihara** [comment]
Not really, serializing/deserializing arrays of `ObjectID`s should be instantaneous regardless of how you do it since the arrays will most likely be very small.

**Comment by devin-petersohn** [comment]
In the graph project, we can get lists of `ObjectIDs` that are on the order of 10-100k elements. This is partly why I ask.

**Comment by robertnishihara** [comment]
Ok, now I think that pickling object IDs will be trickier than I initially thought. The main issue is that pickle isn't really designed to work across processes.

**Comment by robertnishihara** [comment]
Resolved.
