### ISSUE TITLE
[Serve] handle.replicas() API

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#15312]
A new API to list the replicas belong to the Serve deployment. Concretely:

```python
handle = DeploymentCls.get_handle()

handle.replicas() -> List[Replica]
handle.replicas()[0].actor_handle -> ray.ActorHandle
handle.replicas()[0].tag
handle.replicas()[0].address
handle.replicas()[0]...
```

**Comment by edoakes** [comment]
@simon-mo why do you suggest that this goes inside of the handle? In my eyes that has the abstraction reversed -- the handle should be an additional layer on top of `replicas` that load balances across them. That's how I expect users to use this -- they'll have their own `ServeHandle` implementation that takes in the replicas and decides how to route across them.

**Comment by akshay-anyscale** [comment]
Still needed?
