### ISSUE TITLE
[Autoscaler] Fails with 0 specified resources

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15315]
### What is the problem?
With a cluster.yaml has a resource specified as 0, the autoscaler errors out with a division by 0 error.

See https://github.com/ray-project/ray/issues/15214#issuecomment-819892157 for more info.

**Comment by DmitriGekhtman** [comment]
taking a look

**Comment by amogkam** [comment]
We should also try to add a unit test for this
