### ISSUE TITLE
[dashboard]ray dashboard crashed

### ISSUE THREAD

**Issue by Vickzhang** [ray-project/ray#15322]
dashboard of ray cluster crashed,  especially when logs become large. The web console log:

:8265/nodes?view=details:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/tune/availability:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/logical/actor_groups:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/nodes?view=details:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/tune/availability:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/logical/actor_groups:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/nodes?view=details:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/tune/availability:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/logical/actor_groups:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/nodes?view=details:1 Failed to load resource: net::ERR_NETWORK_CHANGED
:8265/tune/availability:1 Failed to load resource: net::ERR_NETWORK_CHANGED
……
……

------------------------
How to debug?    This phenomenon has appeared many times.

**Comment by rkooo567** [comment]
What's the OS you are using?

**Comment by Vickzhang** [comment]
> What's the OS you are using?

ubuntu 16.04,  
ray version:  1.1.0
num of nodes:  8 nodes (local server).

**Comment by scottsun94** [comment]
In Ray 2.0, we made the previous experimental dashboard the new default dashboard. Have you tried it? Are you running into the same issue?
@Vickzhang

**Comment by scottsun94** [comment]
^ Bump it
