### ISSUE TITLE
[autoscaler] Local node provider doesn't work

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#15342]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Local node provider support has been ignored for a while and currently does not work. 

See e.g.
https://discuss.ray.io/t/worker-nodes-not-available-with-manual-configuration/1743
https://discuss.ray.io/t/local-cluster-with-multiple-nodes-in-yaml-config-while-theres-only-head-being-started-any-hints/526
https://discuss.ray.io/t/getting-started-with-rllib-on-a-private-cluster/683

Identify precise issues, fix, update configuration logic, and write tests to prevent regressions. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xmzzyo** [comment]
Hi @DmitriGekhtman , I have the same issue. Did you resolve it yet?

**Comment by DmitriGekhtman** [comment]
Not yet — planning to work on this next week!

**Comment by vroomzel** [comment]
Have a similar issue after upgrading from Ray 1.1.0 to 1.3, local cluster doesn't start any worker nodes.
Adding new `upscaling_speed: 1.0` config from https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml didn't help either.
However, if i manually ssh into a worker node and run `ray start ...`, the node gets added to the cluster.

**Comment by DmitriGekhtman** [comment]
working on fixing these issues -- the problems are completely external to Ray itself, and you shouldn't have any issues starting a Ray cluster manually by running Ray start on the head node, then Ray start on each worker.

**Comment by vroomzel** [comment]
Makes sense. Though would be nice to be able to do it with one `ray up...` command on the head node. Btw cluster start works in 1.2.0 as well, so the issue is only in 1.3.
