### ISSUE TITLE
Move java lang worker off of redis

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#15358]
TODO: Scope this

**Comment by WangTaoTheTonic** [comment]
There're two places using redis client(Jedis) in java worker:
- get `session_dir` key if the worker is a driver, this is a temp connection and do only one time in starting.
- get next Job ID in gcs client. It's a long connection.  like: `int jobCounter = (int) primary.incr("JobCounter".getBytes());`

I would like to remove the second, by transform it to a function in global state accessor.

**Comment by wuisawesome** [comment]
Sounds great! Do you or someone else have bandwidth to take on this task?

**Comment by WangTaoTheTonic** [comment]
I'll take this and first PR has been filed.

**Comment by WangTaoTheTonic** [comment]
Reopen this as there's one more step to finish.
