### ISSUE TITLE
Documentation error: Specifying cross-language `code_search_path` in python

### ISSUE THREAD

**Issue by jonathn** [ray-project/ray#15362]
### What is the problem?

Ray version 1.2.0 and 'master'.

On the cross-langage docs page,
(https://github.com/ray-project/ray/blob/master/doc/source/cross-language.rst)
the 2 examples of specifying the `code_search_path` under python seem to be wrong..
```
        ray.init(job_config=ray.job_config.JobConfig(code_search_path="/path/to/code"))
...and...
        ray.init(job_config=ray.job_config.JobConfig(code_search_path="/path/to/jars:/path/to/pys"))
```
..eg. when trying the first example, the JVM gets started in the background with the following option:
```
-Dray.job.code-search-path=/:p:a:t:h:/:t:o:/:j:a:r:s
```
This causes havoc because the JVM uses 100% CPU apparently spidering the whole filesystem starting from '/'.
I believe the examples should pass a list of strings, like:
```
        ray.init(job_config=ray.job_config.JobConfig(code_search_path=["/path/to/code"]))
...and...
        ray.init(job_config=ray.job_config.JobConfig(code_search_path=["/path/to/jars", "/path/to/pys"]))
```

Ideally, the code would raise an exception if the code_search_path is not a list.

### Reproduction (REQUIRED)

Using the examples on the documentation page reproduces the problem.

**Comment by jovany-wang** [comment]
@jonathn Thanks for reporting this.

I guess the PR #12102 fixed the above issue. 

You can refer this line:
https://github.com/ray-project/ray/pull/12102/files#diff-8519cdbd4dfe5ea26233b8af79e34dad0d245535cd6cf03bcf40dc2bd07bf1d1R44

**Comment by richardliaw** [comment]
Closing this for now.
