### ISSUE TITLE
[Core] Support setting RuntimeEnv from @ray.remote decorator

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#15374]
Currently it can only be set from `.options` for actors and tasks, but the Ray API specifies that the arguments in `.options` should be identical to those in `@ray.remote()`.
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by crypdick** [comment]
@architkulkarni awesome work. Will this be in v1.4.1?
