### ISSUE TITLE
Extra data missing in checkpoint 

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1537]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.3
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.3.1
- **Python version**: 3.6.3
- **Exact command to reproduce**: n/a

### Describe the problem
Running an experiment not all of the checkpoints contain extra_data. Consequently running PPOAgent._restore to try and replay data throws an error. Maybe this is expected behavior? 

### Source code / logs
@ericl On the machine ubuntu@34.224.174.160 with the key I have sent you you can see the missing files in ~/ray_results/2018-02-13_20-18-30qgh4_hx7

**Comment by ericl** [comment]
Hm which files are missing? I see
```
ubuntu@ip-172-31-27-111:~/ray_results/2018-02-13_20-18-30qgh4_hx7$ ls | grep .index | wc -l
10
ubuntu@ip-172-31-27-111:~/ray_results/2018-02-13_20-18-30qgh4_hx7$ ls | grep .extra_data | wc -l
10
```
which seems consistent

**Comment by eugenevinitsky** [comment]
NVM, files somehow got lost in the file transfer process. Thanks!
