### ISSUE TITLE
Is there a way to view/save actions and observations?

### ISSUE THREAD

**Issue by kaninaba94** [ray-project/ray#15395]
Is there a way to view/save actions and observations? In the file progress.csv, I can only view episode-specific data, though I would like to access finer-grained information about my experiments.

https://github.com/ray-project/ray/blob/b0a813baad0a4a187f0cc25e11498843aff899c6/python/ray/tune/progress_reporter.py#L2

**Comment by mvindiola1** [comment]
The config "output" option might be what you are looking for. https://docs.ray.io/en/master/rllib-offline.html?highlight=output#output-api
