### ISSUE TITLE
Protocol Error 'got \x00 as reply type byte' while trying connecting to GCSServer

### ISSUE THREAD

**Issue by Zarca** [ray-project/ray#15434]
Hi,
I tried to connect to GCSServer(which is actually a redis process) using `redis-cli -h xxx_host -p xxx port `.
After connecting to it, no matter what redis command(like KEYS * , PING...) typed in,  there will raise such an error message showing "Protocal Error :got \x00 as reply type byte", and break down quickly.
Is this a bug?  or is there any way one can get the object table stored in GCSServer?

**Comment by richardliaw** [comment]
It is not recommended to access the redis process via `redis-cli`. Can you instead do something like `ray.objects`?

**Comment by Zarca** [comment]
Hi,@richardliaw,
Is the redis process working as GCSServer having any differences between the ordinary redis process (generally started by redis-server )?
I don't get what makes the error message above  happening.
