### ISSUE TITLE
[tune]: what is the real meaning of the metric "epoch" in ray/python/ray/tune/examples/pbt_transformers/pbt_transformers.py at 120 lines?

### ISSUE THREAD

**Issue by Shao-kun-Zhang** [ray-project/ray#15430]
I set the 'num_train_epoches" in tune_config to fixed 100, but after experiment, I found that the "epoch" in progressive.csv is not 100. I want to figure out what is the meaning of the metric "epoch", and I want to know when it will be measured.

**Comment by amogkam** [comment]
The "epoch" field is one of the values returned by the Huggingface Trainer `evaluate` call. https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py#L1865. It represents the current training epoch of the training run.

**Comment by Shao-kun-Zhang** [comment]
Thanks for your reply! In pbt, each trial only report the results when one iteration finished. So, if I set the "num_train_epoches" 100. The "epoch" should be 100 too since "epoch" was measured after the iteration finished. But it is not 100. I want to know why.

**Comment by amogkam** [comment]
Are you referring to the value in your csv file? Where is `progressive.csv` coming from?

**Comment by Shao-kun-Zhang** [comment]
Yes, I get the "epoch" it from progressive.csv.

**Comment by amogkam** [comment]
What is progressive.csv? Did you make that yourself?

**Comment by richardliaw** [comment]
I think @Shao-kun-Zhang  means `progress.csv`?

**Comment by Shao-kun-Zhang** [comment]
Yes! It is progressive.csv. Thanks for your help.

Richard Liaw ***@***.***> 于2021年4月22日周四 上午1:26写道：

**Comment by amogkam** [comment]
Could you share the output of that?

**Comment by Shao-kun-Zhang** [comment]
*objective*

*eval_loss*

*eval_acc*

*epoch*

*time_this_iter_s*

*should_checkpoint*

*done*

*timesteps_total*

*episodes_total*

*training_iteration*

*experiment_id*

*date*

*timestamp*

*time_total_s*

*pid*

*hostname*

*node_ip*

*time_since_restore*

*timesteps_since_restore*

*iterations_since_restore*

*trial_id*

*0.6606498194945850*

2.127528190612790

0.6606498194945850

25.0

580.2400183677670

TRUE

FALSE



1

a80a67a11dc747d2b7b4faed99ce2792

2021-04-20_13-09-15

1618895355

580.2400183677670

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

580.2400183677670

0

1

0bc2e_00003

*0.6714801444043320*

1.9221887588501000

0.6714801444043320

50.0

579.540388584137

TRUE

FALSE



2

ee031f0012ce41b8b48a7d0fd4c226f8

2021-04-20_13-19-05

1618895945

1165.4179685115800

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

579.540388584137

0

1

0bc2e_00003

*0.6750902527075810*

1.855969786643980

0.6750902527075810

38.46153846153850

321.1356272697450

TRUE

FALSE



3

ee031f0012ce41b8b48a7d0fd4c226f8

2021-04-20_13-24-35

1618896275

1496.8672842979400

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

321.1356272697450

0

1

0bc2e_00003

*0.6750902527075810*

1.855969786643980

0.6750902527075810

38.46153846153850

321.0242621898650

TRUE

FALSE



3

ee031f0012ce41b8b48a7d0fd4c226f8

2021-04-20_13-30-07

1618896607

1496.7559192180600

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

321.0242621898650

0

1

0bc2e_00003

*0.6750902527075810*

1.8424313068389900

0.6750902527075810

51.282051282051300

322.7862596511840

TRUE

FALSE



4

ee031f0012ce41b8b48a7d0fd4c226f8

2021-04-20_13-35-39

1618896939

2093.125644683840

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

322.7862596511840

0

1

0bc2e_00003

*0.6570397111913360*

1.2093082666397100

0.6570397111913360

100.0

584.3565037250520

TRUE

FALSE



4

ee031f0012ce41b8b48a7d0fd4c226f8

2021-04-20_13-45-33

1618897533

117

de19b2f00a194011eb0818005d94b55affee-zhengxw13-0

10.110.211.91

584.3565037250520

0

1

0bc2e_00003
As you can see, the "epoch"  is not integer, and I want to know why. I see
the code in huggingface transformer, but I didn't find the reason. I think
it should be 100 since I set the "num_train_epochs" 100 in
pbt_transformer.py. I want to know when and how the "epoch" in
progressive.csv got. Thanks!


Amog Kamsetty ***@***.***> 于2021年4月22日周四 上午9:59写道：

**Comment by amogkam** [comment]
This is not easy for me to read? Do you mind sharing the actual file, or formatting this? Thanks

**Comment by Shao-kun-Zhang** [comment]
Sorry to bother you again. Thanks for your help!

Amog Kamsetty ***@***.***> 于2021年4月22日周四 上午10:55写道：

**Comment by Shao-kun-Zhang** [comment]
al_loss | eval_acc | epoch | time_this_iter_s | should_checkpoint | done | timesteps_total | episodes_total | training_iteration | experiment_id | date | timestamp | time_total_s | pid | hostname | node_ip | time_since_restore | timesteps_since_restore | iterations_since_restore | trial_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.6606498194945850 | 2.127528190612790 | 0.6606498194945850 | 25.0 | 562.5749394893650 | TRUE | FALSE |   |   | 1 | d3b0f5ff86204c21afe01d0917718bac | 2021-04-20_14-46-48 | 1618901208 | 562.5749394893650 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 562.5749394893650 | 0 | 1 | bd73c_00003
0.6425992779783390 | 1.7388126850128200 | 0.6425992779783390 | 100.0 | 1141.7624199390400 | TRUE | FALSE |   |   | 2 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-06-04 | 1618902364 | 1709.9914691448200 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 1141.7624199390400 | 0 | 1 | bd73c_00003
0.6750902527075810 | 1.8424313068389900 | 0.6750902527075810 | 51.282051282051300 | 308.0833206176760 | TRUE | FALSE |   |   | 4 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-11-29 | 1618902689 | 2026.9642324447600 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 308.0833206176760 | 0 | 1 | bd73c_00003
0.6931407942238270 | 2.429642915725710 | 0.6931407942238270 | 64.1025641025641 | 311.7120985984800 | TRUE | FALSE |   |   | 5 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-16-40 | 1618903000 | 2338.6763310432400 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 619.795419216156 | 0 | 2 | bd73c_00003
0.6895306859205780 | 2.555601119995120 | 0.6895306859205780 | 76.92307692307690 | 310.7312910556790 | TRUE | FALSE |   |   | 6 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-21-51 | 1618903311 | 2649.4076220989200 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 930.5267102718350 | 0 | 3 | bd73c_00003
0.6823104693140800 | 2.6277050971984900 | 0.6823104693140800 | 89.74358974358970 | 311.2292537689210 | TRUE | FALSE |   |   | 7 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-27-02 | 1618903622 | 2960.6368758678400 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 1241.7559640407600 | 0 | 4 | bd73c_00003

This is the progressive.csv run by pbt_transformer.py.

**Comment by Shao-kun-Zhang** [comment]
objective | eval_loss | eval_acc | epoch | time_this_iter_s | should_checkpoint | done | timesteps_total | episodes_total | training_iteration | experiment_id | date | timestamp | time_total_s | pid | hostname | node_ip | time_since_restore | timesteps_since_restore | iterations_since_restore | trial_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.6606498194945850 | 2.127528190612790 | 0.6606498194945850 | 25.0 | 562.5749394893650 | TRUE | FALSE |   |   | 1 | d3b0f5ff86204c21afe01d0917718bac | 2021-04-20_14-46-48 | 1618901208 | 562.5749394893650 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 562.5749394893650 | 0 | 1 | bd73c_00003
0.6425992779783390 | 1.7388126850128200 | 0.6425992779783390 | 100.0 | 1141.7624199390400 | TRUE | FALSE |   |   | 2 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-06-04 | 1618902364 | 1709.9914691448200 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 1141.7624199390400 | 0 | 1 | bd73c_00003
0.6750902527075810 | 1.8424313068389900 | 0.6750902527075810 | 51.282051282051300 | 308.0833206176760 | TRUE | FALSE |   |   | 4 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-11-29 | 1618902689 | 2026.9642324447600 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 308.0833206176760 | 0 | 1 | bd73c_00003
0.6931407942238270 | 2.429642915725710 | 0.6931407942238270 | 64.1025641025641 | 311.7120985984800 | TRUE | FALSE |   |   | 5 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-16-40 | 1618903000 | 2338.6763310432400 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 619.795419216156 | 0 | 2 | bd73c_00003
0.6895306859205780 | 2.555601119995120 | 0.6895306859205780 | 76.92307692307690 | 310.7312910556790 | TRUE | FALSE |   |   | 6 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-21-51 | 1618903311 | 2649.4076220989200 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 930.5267102718350 | 0 | 3 | bd73c_00003
0.6823104693140800 | 2.6277050971984900 | 0.6823104693140800 | 89.74358974358970 | 311.2292537689210 | TRUE | FALSE |   |   | 7 | 371c86ae83654b8ba05df1075a2677d4 | 2021-04-20_15-27-02 | 1618903622 | 2960.6368758678400 | 118 | c2a2d5200a1a2011eb0a2730e35ba49cf5f6-zhengxw13-0 | 10.33.116.182 | 1241.7559640407600 | 0 | 4 | bd73c_00003

**Comment by amogkam** [comment]
Looks like all the rows in the csv file are results from the same trial at different timesteps. So I would expect only 1 of them to be at epoch 100.
