### ISSUE TITLE
Execute ray.put() under a node, where is the ObjectID stored?

### ISSUE THREAD

**Issue by Matrix-World** [ray-project/ray#15435]
Hi,
I started a ray cluster and executed：
 import ray 
ray.init(address="ip:port",redis_password="XXX") in the python shell of another node to connect to the cluster.
Execute ray.put() multiple times on this node,
Then execute: redis-cli -h xxx -p xxx -a xxx to connect to redis-server, but no Object Table is found. So I want to know where the object id returned by ray.put() is stored? Is it in the local scheduler?
Is The Object Table in GCS (it is actually redis process) just used to map the ObjectID on which machine?
Looking forward to U~~

**Comment by rkooo567** [comment]
The object is stored in the plasma store, which is different from Redis
