### ISSUE TITLE
Fault Injection Feature for Testing

### ISSUE THREAD

**Issue by lixin-wei** [ray-project/ray#15433]
we want to contribute our large-scale stability tests.  This will benefit us all. For ant, we can reduce bugs from the community if these cases can be run in the community. For you, it will improve ray’s releasing quality.

After discussing with @wuisawesome, we think we lack a tool in the community that can inject faults to cluster like killing processes, shutting down pods.

I think one possible way is to implement this function into agents, offering an HTTP API in the dashboard to kill an arbitrary process in the cluster. This is easy to implement because there are already similar APIs used to execute commands like pstack , pmap, and show process’s stack and memory info in the dashboard. For security, this API will be gated behind a feature flag which will only be opened in tests.

Do you think it makes sense? I want to know your thoughts. If you all agree we will proceed with this approach.

**Comment by wuisawesome** [comment]
I think a feature for simulating failure modes is a pretty uncontroversial and good idea. 

I think we’re concerned that the implementation is easy to write, but hard to maintain because of the security implications. Right now, a dashboard user only has read-only access to the cluster, but after this, they might have full control. 

Is it possible to use `ray exec` with the kubernetes operator? If so, the autoscaler could be another alternative implementation that doesn't introduce a change of responsibility.

**Comment by richardliaw** [comment]
In ML tests, we use `ray kill-random-node` (and its `autoscaler.sdk` equivalent) to kill nodes.

**Comment by wuisawesome** [comment]
@richardliaw we're looking for a more fine grained api to kill specific components on nodes (i.e. kill only the raylet)

**Comment by richardliaw** [comment]
Why not use the same mechanism as `ray kill-random-node` to achieve what you want to do?

**Comment by wuisawesome** [comment]
Yeah I'm advocating for doing it in the autoscaler IF this is compatible with the k8s operator (`kill-random-node` is the same mechanism as `ray exec`, just applied to different nodes, and `ray exec` is more general)

**Comment by lixin-wei** [comment]
@richardliaw @wuisawesome Yeah I also think implement this in autoscaler is a good idea. Who is responsible for autoscaler? Would you please ping him? Let's discuss with him about this feature.

**Comment by wuisawesome** [comment]
@AmeerHajAli (you can also include me in this discussion).

**Comment by AmeerHajAli** [comment]
@DmitriGekhtman , would you like to take the lead on this?

**Comment by wuisawesome** [comment]
Please at least keep me in the loop on the API for this, since core stability testing is the only use case for this.

**Comment by DmitriGekhtman** [comment]
After some internal discussion, I _think_ the rough consensus was that this sort of functionality should be a hidden core Ray feature, which can be exposed to the world outside the Ray cluster via Ray client.

**Comment by DmitriGekhtman** [comment]
Officially punting the lead back to @wuisawesome, since we've decided the autoscaler isn't the best place for this API.
 :)

**Comment by DmitriGekhtman** [comment]
@lixin-wei 
Hmm, so before we figure out how precisely _where_ to expose the API, could you scope precisely what this functionality will do? 
Is it just going to kill arbitrary Ray processes?

**Comment by DmitriGekhtman** [comment]
> Officially punting the lead back to @wuisawesome, since we've decided the autoscaler isn't the best place for this API.
> :)

Actually, glad to contribute to the discussion as well.

If necessary, we can start shared planning documents.

**Comment by lixin-wei** [comment]
> @lixin-wei
> Hmm, so before we figure out precisely _where_ to expose the API, could you scope precisely what this functionality will do?
> Is it just going to kill arbitrary Ray processes or is there something more?

Yes, what we want now is killing arbitrary Ray processes. We might also want other fault injection functionality such as high CPU usage, high network usage, high disk usage, and so on for further usage. But these won't be used quite recently.

> Officially punting the lead back to @wuisawesome, since we've decided the autoscaler isn't the best place for this API.
:)

I also agree with that after internal discussion with my colleagues, since we are not using autosacler now.

@wuisawesome I’m wondering what will the API look like? Would you please show me some examples?

And how will you implement this feature in server side? Who will be responsible for killing process, raylet?

**Comment by wuisawesome** [comment]
The ray client server is the most logical place to do this since it's the closest thing we have to an API server. I'm not sure how much work it will be to be able to kill arbitrary processes with it though, because it currently just submits jobs to the cluster (there's no obvious way to run shell commands on other nodes without using Ray tasks).

**Comment by lixin-wei** [comment]
> I'm not sure how much work it will be to be able to kill arbitrary processes with it though, because it currently just submits jobs to the cluster (there's no obvious way to run shell commands on other nodes without using Ray tasks).

Yes, there is only one server on the head, the implementation seems to be not easy.

Do you think implementing this in the API server makes sense? There are already similar APIs in the dashboard for executing cmds. It's very easy to implement it, and we can contribute to this.

**Comment by wuisawesome** [comment]
I think we can do it in the dashboard as long as we make it clear that it is an internal testing tool, off by default, and not a public/stable API. In general, we should still make sure we don’t want to turn the dashboard into an API server (e.g. we don’t want this to turn into a way to execute commands for submitting jobs).

**Comment by lixin-wei** [comment]
@wuisawesome Sure, this will only be an internal testing tool.

So you agree with my solution that doing this in dashboard agents? If you agree, I'll start to open a PR and implement this.

**Comment by wuisawesome** [comment]
Yeah sounds good

**Comment by wuisawesome** [comment]
@lixin-wei any update on this?

**Comment by lixin-wei** [comment]
@wuisawesome Oh sorry, I was busy with some internal business these days, so I haven't start now.

Do you need this urgently? I plan to open a PR in a month. Will this be too late for you? If you have an earlier deadline please tell me, I can raise the priority of this.

**Comment by wuisawesome** [comment]
@richardliaw do you have any thoughts about the priority?

**Comment by richardliaw** [comment]
I would say P1, this is pretty high impact for serious ray users (of which
there are a recent few)
