### ISSUE TITLE
Can't get object even knowing the ObjectID

### ISSUE THREAD

**Issue by Zarca** [ray-project/ray#15452]
Hi,
I'm using two separate python processes  in a single machine to do a test on.
In the test, the first python process init a ray cluster and call `ray.put()`to put some data
into the objectStore  and I print the objectID,
In another python process, after connecting the existing ray cluster, I constructed an objectRef instance using the  former objectID. but when calling `ray.get()` on that objectID, there will be a never-ending blocking and can't return the
data stored in ObjectStore.
Is this a bug that the object in the shared memory can't be shared between two processes?(and why different tasks can share ?)

**Comment by richardliaw** [comment]
@Zarca this is more of a restriction of the Ray programming model. 

You'll need to explicitly pass the object reference object to a ray worker on the remote node.
