### ISSUE TITLE
[tune] S3 sync from workers

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1546]
### Describe the problem
Currently the tune S3 syncer only syncs from experiment logs from the head node. This is a problem if you have custom logs that you put in $CWD, since those are not sent to the head node.

We should also sync those, separately. Note that this requires granting worker nodes S3 access.

cc @vlad17 @richardliaw

**Comment by vlad17** [comment]
@ericl  or perhaps the master can just rsync those files onto itself, and then be the only node that does the s3 sync? Then you don't need additional permissions, and you can put a tensorboard proc on the head that serves the freshest data

**Comment by robertnishihara** [comment]
Does it make sense for the S3 syncer to apply specifically to experiment logs? Or should it apply to all stdout/stderr?

**Comment by vlad17** [comment]
@robertnishihara if you're asking me, then all I really care are the tensorflow logfiles. I imagine most people would write valuable info to files in cwd but don't care about losing stdout/err data (except for debugging, but that's a separate issue and probably doesn't require persistence)

**Comment by richardliaw** [comment]
Merged - @vlad17 feel free to open if current impl doesn't suffice.
