### ISSUE TITLE
[bug] Can not import AxSearch

### ISSUE THREAD

**Issue by tanzeyy** [ray-project/ray#15474]
### What is the problem?

Ray version: 1.2.0

Can not import AxSearch

### Reproduction (REQUIRED)

```python
>>> from ray.tune.suggest import AxSearch
ImportError: cannot import name 'AxSearch' from 'ray.tune.suggest'
```

### Fix
Seems like add 
```python
from ray.tune.suggest.ax import AxSearch
```
in `ray.tune.suggest.__init__.py` would fix this issue.

**Comment by amogkam** [comment]
@tanzeyy you have to do `from ray.tune.suggest.ax import AxSearch` to import AxSearch. Note the `.ax` after `suggest`.

**Comment by tanzeyy** [comment]
Seems I was wrong while importing. Closing this.
