### ISSUE TITLE
Incorrect torch version installed in GPU version of ray-ml containers

### ISSUE THREAD

**Issue by gmatev** [ray-project/ray#15470]
### What is the problem?
Pre-built `ray-ml` container images with `gpu` flavor contain a CPU only version of Torch

Tested this out on pre-release 1.3.0 images but from what I can see the container composition logic and requirements stacking has not changed. 

### Reproduction (REQUIRED)
The simplified repro is to locally execute the container
```
docker run -t -i rayproject/ray-ml:1.3.0-py38-gpu
(base) ray@6199db9c2fdc:~$ pip freeze | grep ^torch
torch==1.7.1+cpu
torchvision==0.8.2+cpu
```

**Comment by gmatev** [comment]
@richardliaw

**Comment by richardliaw** [comment]
@amogkam do you think you could look into this?

**Comment by amogkam** [comment]
Hey @gmatev thanks a bunch for bringing this up! We have a PR open for the fix and will make sure update the latest Docker images once it is merged.

**Comment by gmatev** [comment]
Awesome! Is there also a reason 1.3.0 will be installing torch 1.7.1 and torchvision 0.8.2 as opposed to 1.8 and 0.9 respectively? Seems like there may also be an issue with the the combo of 1.7.1 and cuda11 that comes with the GPU base image.

**Comment by amogkam** [comment]
Ah yes that's an oversight on our part. In order to support Cuda 11, we had to pin the torch versions, and we never updated those. I'll make sure to update them now.
