### ISSUE TITLE
`//rllib:tests/test_checkpoint_restore` takes too long

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#15489]
### What is the problem?
```
py_test(
    name = "tests/test_checkpoint_restore",
    tags = ["tests_dir", "tests_dir_C"],
    size = "enormous",
    srcs = ["tests/test_checkpoint_restore.py"]
)
```

This test often takes 20+min in even Buildkite CI. As a rule of thumb we shouldn't have individual tests that takes more than 5min. Is there a way to shrink it or split it up into medium tests?

cc @sven1977 @ericl

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/15499
@simon-mo
