### ISSUE TITLE
[DataFrame] df.T.T is leaving out partitions

### ISSUE THREAD

**Issue by hsubbaraj** [ray-project/ray#1548]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.2
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.3.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: ray_df.T.T

### Describe the problem
@devin-petersohn 
When performing ray_df.T.T, the dataframe drops some partitions. There also may be an issue with types, where int values are casted into floats

### Source code / logs

<img width="422" alt="screen shot 2018-02-15 at 7 21 49 pm" src="https://user-images.githubusercontent.com/8093660/36292310-accf773a-1285-11e8-9f92-b45ca468a3f6.png">

**Comment by devin-petersohn** [comment]
This is resolved by #1545

**Comment by devin-petersohn** [comment]
Rosolved with #1545
