### ISSUE TITLE
max_calls does not help with third party memory leaks but it is advertised to do so.

### ISSUE THREAD

**Issue by adam-katona** [ray-project/ray#15498]
### What is the problem?
The ray.remote() parameter max_calls is advertised as being able to help with third-party memory leaks. However it does not restart the processes with leaked memory but keeps them around as IDLE, which results in the leaked memory accumulating.

The documentation: "max_calls (int) – Only for remote functions. This specifies the maximum number of times that a given worker can execute the given remote function before it must exit (this can be used to address memory leaks in third-party libraries or to reclaim resources that cannot easily be released, e.g., GPU memory that was acquired by TensorFlow). By default this is infinite."

The memory leak can only be fixed if the worker process which called the leaking code is restarted, by keeping the worker around as IDLE, the leaked memory just accumulates.

Ray version: ray-1.3.0, OS: linux, python 3

### Reproduction (REQUIRED)
```python
import gym   
# pip install gym[box2d]   
# I cannot reproduce this without third-party libraries, since the bug is about third-party memory leaks.
import ray

ray.shutdown()
ray.init(num_cpus=1,dashboard_port=9995,log_to_driver=False) # log_to_driver to supress message spam by workers

@ray.remote(max_calls=5)
def restart_mem_leak(): # a function which have a known thrid party memory leak
    env = gym.make('CarRacing-v0')
    obs = env.reset()
    env.close()
    
# this results in IDLE processes accumulation with leaked memory
ray.get([restart_mem_leak.remote() for _ in range(1000)])
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Hmm this should be fixed in the latest version of ray. please reopen if that's not the case!
