### ISSUE TITLE
Windows wheels do not have {{RAY_COMMIT_SHA}} replaced with actual commit hash in __init__.py

### ISSUE THREAD

**Issue by nirvana-msu** [ray-project/ray#15502]
### What is the problem?

Really minor thing - windows wheels do not have `{{RAY_COMMIT_SHA}}` replaced with actual commit hash in `__init__.py` (like e.g. linux wheels). It doesn't seem to make any difference, just a little odd:
```
# Replaced with the current commit when building the wheels.
__commit__ = "{{RAY_COMMIT_SHA}}"
__version__ = "1.3.0"
```
This is the case for at least the two most recent releases (1.3.0, 1.2.0), haven't checked the ones before.

**Comment by mattip** [comment]
Fixed in the latest 1.9.1 release:
```
>>> import ray
>>> ray.__commit__
'2cdbf974ea63caf4323aacbccaef2394a14a8562'
>>> ray.__version__
'1.9.1'
>>>
```

Thanks for the report. Closing, please reopen if I misunderstood.
