### ISSUE TITLE
Ray Tune doesn't scale, scheduling performance degrades to less than 25% worker utilization with 32 workers.

### ISSUE THREAD

**Issue by max0x7ba** [ray-project/ray#15504]
### What is the problem?
I run a grid search of 19440 trials using `FIFOScheduler` and the default `search_alg` with 32 worker CPUs.

I encounter 2 problems:

1. In the first few minutes 100% of workers are utilized. After ~1100 trials complete only ~6 worker CPUs are busy at a time, the rest of worker CPUs are idling, while the logging says "Number of trials: 2930/19440 (1000 PENDING, **32 RUNNING**, 1898 TERMINATED)". In other words, scheduling keeps busy less that 25% of worker CPUs. 
2. Looking into log files I notice that at this point `gcs_server.out` is 16GB in size, filled with ~89 million lines like the following:
```
[2021-04-25 22:33:39,901 I 2215124 2215124] gcs_placement_group_scheduler.cc:141: Scheduling placement group __tune_19c488be__55f5f383, id: 4b7b88f0acf7d6dadc1ec0d726e39f4a, bundles size = 1
[2021-04-25 22:33:39,901 I 2215124 2215124] gcs_placement_group_scheduler.cc:150: Failed to schedule placement group __tune_19c488be__55f5f383, id: 4b7b88f0acf7d6dadc1ec0d726e39f4a, because no nodes are available.
[2021-04-25 22:33:39,901 I 2215124 2215124] gcs_placement_group_manager.cc:215: Failed to create placement group __tune_19c488be__55f5f383, id: 4b7b88f0acf7d6dadc1ec0d726e39f4a, try again.
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_scheduler.cc:141: Scheduling placement group __tune_19c488be__45ec09b4, id: 164f45d0a5e0ad31aad8d7acfe455e0b, bundles size = 1
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_scheduler.cc:150: Failed to schedule placement group __tune_19c488be__45ec09b4, id: 164f45d0a5e0ad31aad8d7acfe455e0b, because no nodes are available.
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_manager.cc:215: Failed to create placement group __tune_19c488be__45ec09b4, id: 164f45d0a5e0ad31aad8d7acfe455e0b, try again.
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_scheduler.cc:141: Scheduling placement group __tune_19c488be__2db3328e, id: 23066cf1865fe81ca4922400efcddd51, bundles size = 1
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_scheduler.cc:150: Failed to schedule placement group __tune_19c488be__2db3328e, id: 23066cf1865fe81ca4922400efcddd51, because no nodes are available.
[2021-04-25 22:33:39,902 I 2215124 2215124] gcs_placement_group_manager.cc:215: Failed to create placement group __tune_19c488be__2db3328e, id: 23066cf1865fe81ca4922400efcddd51, try again.
```

OS: Ubuntu 20.04
Python: 3.8.8
Ray: 1.3.0

### Minimal reproduction code
The following code reproduces both issues:

1. Scheduling performance degrades to less than 30% workers being utilized (32 total worker CPUs) after ~1100 completed trials (`load_avg` metric goes down at that point). The following warnings are observed after ~2000 completed trials:
```
2021-04-26 12:20:16,000	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.513 s, which may be a performance bottleneck.
2021-04-26 12:20:16,741	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.626 s, which may be a performance bottleneck.
2021-04-26 12:20:17,384	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.521 s, which may be a performance bottleneck.
2021-04-26 12:20:18,132	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.626 s, which may be a performance bottleneck.
2021-04-26 12:20:18,849	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.611 s, which may be a performance bottleneck.
2021-04-26 12:20:19,487	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.532 s, which may be a performance bottleneck.
2021-04-26 12:20:20,324	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.719 s, which may be a performance bottleneck.
2021-04-26 12:20:20,979	WARNING util.py:161 -- The `choose_trial_to_run` operation took 0.541 s, which may be a performance bottleneck.
```
2. `gcs_server.out` being spammed with log messages. Running the code produces `gcs_server.out` of 22GB.

The code itself:

```
import os
import zlib
import struct

import ray
from ray.tune.result import DEFAULT_RESULTS_DIR
from ray.tune.schedulers import FIFOScheduler


def cpu_hog(value, bits):
    mask = (1 << bits) - 1
    steps = 1
    while (value := zlib.crc32(struct.pack("<I", value))) & mask:
        steps += 1
    return steps, value


def tune_one(config):
    steps, score = cpu_hog(config["value"], config["complexity"])
    ray.tune.report(steps=steps, score=score, load_avg=os.getloadavg()[0])


def tune():
    ray.init(_temp_dir=os.path.join(DEFAULT_RESULTS_DIR, "tmp"))  # Otherwise, gcs_server.out fills up /tmp.
    ray.tune.run(
        tune_one,
        config={"value": ray.tune.grid_search(list(range(10000))), "complexity": 26},
        scheduler=FIFOScheduler()
    )


if __name__ == "__main__":
    tune()
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by max0x7ba** [comment]
The bottleneck limiting Ray Tune scalability seems to be `TrialRunner._trials` list only ever growing and those linear scans of this list to pick the next trial to run. @richardliaw

**Comment by max0x7ba** [comment]
[cProfile output](https://github.com/ray-project/ray/files/6410723/cprofile.txt). Top 20 functions where the scheduler spends tme:

```
   1642/1    0.005    0.000 1349.273 1349.273 {built-in method builtins.exec}
        1    0.000    0.000 1349.273 1349.273 ray_scheduler_test.py:2(<module>)
        1    0.079    0.079 1348.969 1348.969 ray_scheduler_test.py:24(tune)
        1    0.076    0.076 1346.805 1346.805 tune.py:71(run)
     9346    0.295    0.000 1323.013    0.142 trial_runner.py:464(step)
  1618506    1.371    0.000 1047.611    0.001 client_mode_hook.py:43(wrapper)
  1552100  109.535    0.000 1036.289    0.001 worker.py:1527(wait)
  1552059  869.753    0.001  869.753    0.001 {method 'wait' of 'ray._raylet.CoreWorker' objects}
  3715765    5.583    0.000  652.517    0.000 placement_groups.py:421(has_ready)
     9346    0.093    0.000  610.924    0.065 trial_runner.py:606(_get_next_trial)
     9346    3.601    0.000  592.348    0.063 trial_scheduler.py:125(choose_trial_to_run)
  1532482    0.639    0.000  588.744    0.000 trial_runner.py:587(has_resources_for_trial)
  1532482    1.777    0.000  588.106    0.000 ray_trial_executor.py:779(has_resources_for_trial)
  1542722   11.388    0.000  571.964    0.000 placement_groups.py:355(update_status)
     6346    0.089    0.000  519.307    0.082 trial_runner.py:624(_process_events)
     6346    0.060    0.000  478.602    0.075 ray_trial_executor.py:647(get_next_available_trial)
  4945329    2.691    0.000  103.799    0.000 placement_groups.py:141(__eq__)
  4945329    8.207    0.000  101.108    0.000 inspect.py:2720(__eq__)
  4945329    7.174    0.000   90.835    0.000 inspect.py:2894(__eq__)
  9890658   25.210    0.000   67.748    0.000 inspect.py:2880(_hash_basis)
```

**Comment by dekromp** [comment]
Hi,
I am observing a similar (if not the same) issue.  ray version:  `1.3.0`,  OS: ubuntu server 20.04, python: `3.8.8`
`gcs_server.out`: 
```
...
[2021-05-03 19:34:48,477 I 33883 33883] gcs_placement_group_manager.cc:215: Failed to create placement group __tune_c0d3dad5__f4b36ab1, id: 915b0ca0ef75eba82a5fbd51c469d72e, try again.
[2021-05-03 19:34:48,477 I 33883 33883] gcs_placement_group_scheduler.cc:141: Scheduling placement group __tune_c0d3dad5__579d438f, id: 9c9355546869b98ac97eedf35c84a0b5, bundles size = 1
[2021-05-03 19:34:48,477 I 33883 33883] gcs_placement_group_scheduler.cc:150: Failed to schedule placement group __tune_c0d3dad5__579d438f, id: 9c9355546869b98ac97eedf35c84a0b5, because no nodes are available.
```
Which I just realized has 140 GB (no typo, thanks for pointing that out @max0x7ba) after running roughly 16 hours.

STDOUT:
```
...
Memory usage on this node: 5.6/15.3 GiB
Using AsyncHyperBand: num_stopped=66
Bracket: Iter 80.000: None | Iter 40.000: None | Iter 20.000: 0.34035758674144745 | Iter 10.000: 0.3636363744735718 | Iter 5.000: 0.19719786942005157
Resources requested: 4.0/84 CPUs, 1.0/21 GPUs, 0.0/233.05 GiB heap, 0.0/95.03 GiB objects (0.0/21.0 accelerator_type:T4)
Current best trial: b8d60_00083 with val/f1=0.5 and parameters={...}
Result logdir: ...
Number of trials: 1096/2000 (1000 PENDING, 1 RUNNING, 95 TERMINATED)
```

In my case I am performing a series of hypertuning tasks that sequentially call `tune.run` with 2000 trials each on a cluster of AWS `g4dn` instances and this happens after the second run (so 4000 trials have preceded the output above). But I observed the same behavior with single hypertuning jobs that have 5000 trials. As described by @max0x7ba in the beginning scheduling works as expected but then it degrades until only 1 Running trial (on the head node) is shown at a time and no jobs seem to be scheduled to the other nodes.
I am calling `ray.tune` with 
```python
tune.run(
    ...
    resources_per_trial={
        "cpu": 4,
        "gpu": 1,
    },
    ...
)
```
Maybe one additional information. I only observe this behavior since I upgraded from ray `1.2.0` to `1.3.0` last week.

Thanks for looking into this.

**Comment by krfricke** [comment]
From a quick glimpse this could actually be related to https://github.com/ray-project/ray/issues/15595#issuecomment-831518809 and https://discuss.ray.io/t/ray-tune-log-grows-extremely-large/1992/3

Basically starting a large number of placement groups fills the logs and might introduce overhead.

Can you try setting `TUNE_MAX_PENDING_TRIALS_PG=x` where x is the number of available cluster CPUs (or really the maximum number of parallel trials you expect to be running, which seems to be 32)?

**Comment by max0x7ba** [comment]
@kradongit A part of the problem is that `TrialRunner._trials` grows indefinitely with completed trials not being removed from the list. That cannot possibly scale, IMHO.

**Comment by krfricke** [comment]
We tested this I think for up to 10,000 trials. Linear scanning through 10k items doesn't take too much time, though I agree we should fix this by moving finished trials to a different list and possibly split experiment checkpointing in a second step.

**Comment by krfricke** [comment]
We also have a release test testing the scheduling overhead specifically for 10k trials. However this uses very short evaluation functions to keep the wallclock time shorter for testing. Thus the log file issue didn't came up in those release tests.

We might want to have a long running release test for this.

**Comment by max0x7ba** [comment]
> We tested this I think for up to 10,000 trials. Linear scanning through 10k items doesn't take too much time, though I agree we should fix this by moving finished trials to a different list and possibly split experiment checkpointing in a second step.

Well, those numerous linear scans of ever growing `TrialRunner._trials` evict progressively more user data out of L2 and L3 CPU caches, making memory-intensive user tasks slow down orders of magnitude. Tasks like `os.sleep()` or my `cpu_hog` may not show any statistically significant difference because of not accessing much memory, but memory intensive ones should.

I wonder what RAM resources those 10k trials require.

**Comment by krfricke** [comment]
Can you try the `TUNE_MAX_PENDING_TRIALS_PG=x` to solve the gcs_server.out problem?

I'm happy to work on removing finished trials from the `TrialRunner._trials` this week/early next week. We will probably include these fixes in a 1.3.1 patch release.

**Comment by max0x7ba** [comment]
> Can you try the `TUNE_MAX_PENDING_TRIALS_PG=x` to solve the `gcs_server.out` problem?

Sure, please, bear with me.

**Comment by max0x7ba** [comment]
@krfricke I confirm that `TUNE_MAX_PENDING_TRIALS_PG=32` solves the problem of `gcs_server.out`. Running my reproduction code with `range(10,000)`:

* With `TUNE_MAX_PENDING_TRIALS_PG` unset, `gcs_server.out` is `7,775,092,845` bytes.
* With `TUNE_MAX_PENDING_TRIALS_PG=32`, `gcs_server.out` is `302,695,182` bytes.

No change to idle workers problem, though.

**Comment by max0x7ba** [comment]
@krfricke With `TUNE_MAX_PENDING_TRIALS_PG=32` and `range(10000)` I no longer observe idle worker CPUs.

**Comment by krfricke** [comment]
Thanks for confirming. I'll submit a quick PR that sets TUNE_MAX_PENDING_TRIALS_PG to max(16, the number of available cluster CPUs divided by the number of required CPUs per trials) per default. With a minimum of 16 pending trials per default autoscaling should still be triggered reasonably fast. Note that this doesn't limit the number of parallel (e.g. running trials), just the number of placement groups and trial objects that are created.

I'll get to the `TrialRunner._trials` optimization in a different PR.

**Comment by max0x7ba** [comment]
> I'm happy to work on removing finished trials from the `TrialRunner._trials` this week/early next week. We will probably include these fixes in a 1.3.1 patch release.

https://github.com/ray-project/ray/issues/15751 may be related to `TrialRunner._trials` growing indefinitely.

**Comment by krfricke** [comment]
Just as a quick update on this, it's not straightforward to just remove trials from `TrialRunner._trials`, as this would effectively be a breaking API change for existing callbacks and other hooks.

However, you're right that we're linearly scanning through the `_trials` list a number of times each step. Usually this is not a problem as most experiments run with few trials. 

The default callbacks (logger and syncer) do not scan through the `trials` parameter.

The schedulers do scan through all trials. They should however still work if the only scanned through non-terminated trials.

The searchers do not scan through all trials.

Other locations where we scan through trials:

```
trials_done = all(trial.is_finished() for trial in self._trials)
...
num_pending_trials = len([t for t in self._trials if t.status == Trial.PENDING])
...
# This only needs pending trials
self.trial_executor.stage_and_update_status(self._trials)
...
# reconcile placement groups
            self._pg_manager.reconcile_placement_groups(
                trial_runner.get_trials())
...
# _get_next_trial()
all(trial.is_finished() for trial in self._trials)
any(trial.status == Trial.PENDING for trial in self._trials)
```

In all these cases it should be enough to just scan through non-terminated trials. An exception is the `reconcile_placement_groups` method, but this is only called periodically every x seconds and not potentially at each step.

There are other cases (e.g. when printing the table) where we scan through all trials, but again, these occur periodically and not at each step, so should be fine to keep.

So the things to do here are a) keep a list or set of non-terminated trials and b) offer an API to access these, e.g. `TrialRunner.get_nonterminated_trials()`.

The problem comes up with maintaining this collection however. We don't impose any kind of API to set trial statuses via the Trial runner. The trial status can be updated by any component interacting with it via the `Trial.set_status()` API. Even though we currently only do this in the trial runner, executor, and tests, this not a guarantee.

We can probably implement some reconciliation method that is run periodically - it just has to scan over all live trials and mark them as as terminated if applicable. This does not seem ideal, but might be good enough. The reconciliation method should be public so that other components can call it deliberately.

This would help reduce the stress of linear scanning in the case where you have a large number of trials but only relatively few concurrently running trials. Would this help your usecase?

**Comment by max0x7ba** [comment]
> Just as a quick update on this, it's not straightforward to just remove trials from `TrialRunner._trials`, as this would effectively be a breaking API change for existing callbacks and other hooks.
> [...]
> The problem comes up with maintaining this collection however. We don't impose any kind of API to set trial statuses via the Trial runner. The trial status can be updated by any component interacting with it via the `Trial.set_status()` API. Even though we currently only do this in the trial runner, executor, and tests, this not a guarantee.

I spent some few hours looking into `TrialRunner` code and made the scheduler maintain its own list of only the next trials to run, only to discover that `TrialRunner._trials` is scanned elsewhere, as you reported. It looked to me that `TrialRunner` and `Trial` APIs should not pass the entire list of trials to callbacks, but rather make the callbacks query `TrialRunner` API for `Trials` they are interested in. This way `TrialRunner` can maintain `Trials` efficiently with sub-linear scalability. And that looked like a big task for me.

> We can probably implement some reconciliation method that is run periodically - it just has to scan over all live trials and mark them as as terminated if applicable. This does not seem ideal, but might be good enough. The reconciliation method should be public so that other components can call it deliberately.
> 
> This would help reduce the stress of linear scanning in the case where you have a large number of trials but only relatively few concurrently running trials. Would this help your usecase?

My current use case is up to 100,000 of trials to run locally on 32 worker CPUs. I would like all workers to be utilised 100% all the time, rather than idling.

**Comment by krfricke** [comment]
Benchmark results for 10,000 trials.

Before (current master):

```
2021-05-17 03:04:05,251 INFO tune.py:549 -- Total run time: 684.58 seconds (675.74 seconds for the tuning loop).
The bookkeeping overhead test took 714.62 seconds, which is below the budget of 800.00 seconds. Test successful. 
```

After (with PR applied):

```
2021-05-17 03:24:21,715 INFO tune.py:549 -- Total run time: 684.79 seconds (674.01 seconds for the tuning loop).
The bookkeeping overhead test took 715.43 seconds, which is below the budget of 800.00 seconds. Test successful. 
```

I.e. virtually identical results. This is just for a 1 sec sleep task. I'm running it again right now with a 5 second 100% CPU task (matrix multiplication).


I don't think callbacks are the problem, as the default ones usually don't loop through the `_trials`. It's more likely the scheduler, which at 100,000 trials will get called 100,000 times.

I'm reluctant to default to only querying the set of live trials, as it will invalidate some assumptions (e.g. for the FIFO scheduler that we actually get first in, first out). I can see two ways here. Either the set of live trials becomes a list instead of a set (as in the current PR) - this would keep the FIFO invariance, but modifying the list (which we do often) would require linear time (though on a much smaller scale, in your case just 32 trials). The other alternative would be to introduce an environment variable or so with which you could configure schedulers (and callbacks) to only query the live trials set (i.e. `trial_runner.get_live_trials()` instead of `trial_runner.get_trials()`). This would leave us with the current set implementation and still solve the problem for the special case where a very large number of trials is started.

I'll think about the complexity implications of just turning the live trials into a list. It would be the easiest change, but I want to avoid introducing another possible scale limitation.

**Comment by max0x7ba** [comment]
> I don't think callbacks are the problem, as the default ones usually don't loop through the `_trials`. It's more likely the scheduler, which at 100,000 trials will get called 100,000 times.

Has it been identified where the scalability bottlenecks are?

Looking into that [cProfile](https://github.com/ray-project/ray/issues/15504#issuecomment-830734272) on 3000 trials:

Top 20 by `tottime`:
```
        ncalls  tottime  percall   cumtime  percall                                                     location
0      1552059  869.753    0.001   869.753    0.001          {method 'wait' of 'ray._raylet.CoreWorker' objects}
1      1552100  109.535    0.000  1036.289    0.001                                         worker.py:1527(wait)
2   1598308210   55.475    0.000    56.059    0.000                        {built-in method builtins.isinstance}
3        66024   27.375    0.000    27.375    0.000                 {method 'acquire' of '_thread.lock' objects}
4      9890658   25.210    0.000    67.748    0.000                                 inspect.py:2880(_hash_basis)
5     49453290   17.316    0.000    21.410    0.000                                   inspect.py:2881(<genexpr>)
6      1542722   11.388    0.000   571.964    0.000                       placement_groups.py:355(update_status)
7     19781316   11.152    0.000    15.600    0.000                                      inspect.py:2601(__eq__)
8      9890658    9.804    0.000    13.740    0.000                                  inspect.py:2884(<dictcomp>)
9     37514340    8.871    0.000     8.871    0.000                                    trial.py:591(is_finished)
10     4945329    8.207    0.000   101.108    0.000                                      inspect.py:2720(__eq__)
11    79403302    8.070    0.000     8.070    0.000                                        inspect.py:2551(kind)
12    25029253    7.861    0.000    13.914    0.000                               trial_runner.py:461(<genexpr>)
13     1935114    7.528    0.000     7.528    0.000              {built-in method _json.encode_basestring_ascii}
14     4945329    7.174    0.000    90.835    0.000                                      inspect.py:2894(__eq__)
15         256    6.989    0.027     6.989    0.027                              {built-in method posix.replace}
16       12399    6.924    0.001     6.924    0.001                             {built-in method builtins.print}
17    12721845    6.473    0.000    13.686    0.000                                        copy.py:128(deepcopy)
18     3715765    5.583    0.000   652.517    0.000                           placement_groups.py:421(has_ready)
19        3000    4.594    0.002     5.170    0.002  {method 'create_actor' of 'ray._raylet.CoreWorker' objects}
```

Top 20 by `cumtime`:
```
     ncalls  tottime  percall   cumtime   percall                                             location
0         1    0.000    0.000  1349.273  1349.273                    ray_scheduler_test.py:2(<module>)
1      1642    0.005    0.000  1349.273  1349.273                      {built-in method builtins.exec}
2         1    0.079    0.079  1348.969  1348.969                       ray_scheduler_test.py:24(tune)
3         1    0.076    0.076  1346.805  1346.805                                      tune.py:71(run)
4      9346    0.295    0.000  1323.013     0.142                            trial_runner.py:464(step)
5   1618506    1.371    0.000  1047.611     0.001                      client_mode_hook.py:43(wrapper)
6   1552100  109.535    0.000  1036.289     0.001                                 worker.py:1527(wait)
7   1552059  869.753    0.001   869.753     0.001  {method 'wait' of 'ray._raylet.CoreWorker' objects}
8   3715765    5.583    0.000   652.517     0.000                   placement_groups.py:421(has_ready)
9      9346    0.093    0.000   610.924     0.065                 trial_runner.py:606(_get_next_trial)
10     9346    3.601    0.000   592.348     0.063          trial_scheduler.py:125(choose_trial_to_run)
11  1532482    0.639    0.000   588.744     0.000         trial_runner.py:587(has_resources_for_trial)
12  1532482    1.777    0.000   588.106     0.000   ray_trial_executor.py:779(has_resources_for_trial)
13  1542722   11.388    0.000   571.964     0.000               placement_groups.py:355(update_status)
14     6346    0.089    0.000   519.307     0.082                 trial_runner.py:624(_process_events)
15     6346    0.060    0.000   478.602     0.075  ray_trial_executor.py:647(get_next_available_trial)
16  4945329    2.691    0.000   103.799     0.000                      placement_groups.py:141(__eq__)
17  4945329    8.207    0.000   101.108     0.000                              inspect.py:2720(__eq__)
18  4945329    7.174    0.000    90.835     0.000                              inspect.py:2894(__eq__)
19  9890658   25.210    0.000    67.748     0.000                         inspect.py:2880(_hash_basis)
```

**Comment by krfricke** [comment]
In my benchmarks all CPUs have been fully utilized during the whole run. I might try to scale up this to 50-100k trials.

Note that this was on the PR #15811, haven't run comparison benchmarks yet

**Comment by max0x7ba** [comment]
> In my benchmarks all CPUs have been fully utilized during the whole run.

I didn't realise that.

Do you think PR #15811 is ready for me to take if for a test drive?

**Comment by krfricke** [comment]
I think it should be good to try out.

One last thing you might want to do is to use `trial_runner.get_live_trials()` instead of `trial_runner.get_trials()` in the FIFOScheduler (assuming you're using it) - but actually it would be great to try it out without the change. Whatever works best for you.

By the way, just for context, how long does a single trial take (approx)?

**Comment by max0x7ba** [comment]
I ran the reproduction script from my report and with `TUNE_MAX_PENDING_TRIALS_PG=32` and 10,000 trials I cannot reproduce the issue: all 32 CPU workers are utilised 100% all the time. 

I didn't try applying your patch.

> how long does a single trial take (approx)?

It takes around 1h40m to run the reproduction with 10,000 trials and 32 CPU workers. Each trial takes 1-70 seconds, ~20 seconds on average.

**Comment by max0x7ba** [comment]
> I think it should be good to try out.
> 
> One last thing you might want to do is to use `trial_runner.get_live_trials()` instead of `trial_runner.get_trials()` in the FIFOScheduler (assuming you're using it) - but actually it would be great to try it out without the change. Whatever works best for you.

For this test I used my production workload with `MedianStoppingRule`.

Before applying the patch, 3500 trials produced 350 warnings _`choose_trial_to_run` operation took 0.xyz s, which may be a performance bottleneck_.

After applying the patch, 3500 trials produced 90 warnings. 

> By the way, just for context, how long does a single trial take (approx)?

Roughly 2 minutes each trial.

**Comment by max0x7ba** [comment]
> > I think it should be good to try out.
> > One last thing you might want to do is to use `trial_runner.get_live_trials()` instead of `trial_runner.get_trials()` in the FIFOScheduler (assuming you're using it) - but actually it would be great to try it out without the change. Whatever works best for you.
> 
> For this test I used my production workload with `MedianStoppingRule`.
> 
> Before applying the patch, 3500 trials produced 350 warnings _`choose_trial_to_run` operation took 0.xyz s, which may be a performance bottleneck_.
> 
> After applying the patch, 3500 trials produced 90 warnings.

I ran another 3000 trials today using the patched code and got 323 warnings about `choose_trial_to_run` taking too long. 

It looks like my runs are inconclusive about whether the patch makes a difference on `choose_trial_to_run` taking too long warnings, when the metric is the count of these warnings.

**Comment by krfricke** [comment]
Sorry for letting this rest for a while.

My take on this is that it should be safe to merge #15811 as it might help performance in some cases. It's hard for me to investigate this further without a reproducible example on my end. I'm happy to investigate more, but would need to rely on your tracing here to make this happen. What do you think?

**Comment by max0x7ba** [comment]
> My take on this is that it should be safe to merge #15811 as it might help performance in some cases. 

I have been using the code with that patch all this time, no issues observed.

> It's hard for me to investigate this further without a reproducible example on my end. I'm happy to investigate more, but would need to rely on your tracing here to make this happen. What do you think?

IMO, a separate PR with a good reproduction is needed to improve on the list of trials.

**Comment by bbudescu** [comment]
I am having this issue, too, with ray 2.3.1.
