### ISSUE TITLE
[rllib] multi-task RL with Rllib

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#15517]
Hello,

I'm trying to implement one simple multi-task RL (universal functional approximator) where the input is current state and specific task and generated goal-conditioned reward. 

I tried to search if there is any example of using RLlib to perform this, but what I found is only to customize multi-agent for this scenario. Techinically this is not multi-agent because it's the same agent with the shared policy (just the input is different). 

Is there any recommendation of how to use RLLib for this?

**Comment by mvindiola1** [comment]
Hi @AprilXiaoyanLiu,

I think it will be easier to make suggestions with more concrete information about the environment an policies if you have them available.
