### ISSUE TITLE
Can I use Ray Client to connect to a remote cluster while using my local cluster?

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#15521]
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

### My Setup

I have a long-running cluster that is intended to be used by multiple people. Each user submits jobs that run on this cluster.

Our current approach is to connect each user's driver nodes to this cluster, then use custom resources to make sure the jobs run on the cluster nodes. This setup has known issues (#8822) and we're forced to restart the cluster every few days.

I want to use the Ray Client feature so that the driver nodes no longer need to be part of the cluster, but rather only need to use Ray Client to forward job requests.

However each driver node program also uses Ray for local task parallelism. It looks like there is no way to connect to multiple Ray instances at the moment.

My ideal workflow would be something like this:

```python
ray = ray.init("auto")  # connect to local Ray

local_cluster = ???
remote_cluster = ray.util.connect(???)

ray.get([foo.remote(i, on=local_cluster) for i in range(10)])

# We want `foo` to run on the local cluster
@ray.remote
def foo(i):
  return bar.remote(on=remote_cluster)

# We want `bar` to run on the remote cluster
@ray.remote
def bar():
  pass
```

Is there some workaround to make this work?

cc @concretevitamin @michaelzhiluo

**Comment by valiantljk** [comment]
probably can try this workaround:
```
def clean_ray():
     try:
         ray.util.disconnect() # close remote connection
    except Exception as e:
        pass
    try:
        ray.shutdown() # close local connection
    except Exception as e:
       pass
 
def ray_local():
      clean_ray()
      ray.init(address="auto")

def ray_remote(remote_cluster):
    clean_ray()
    ray.util.connect(remote_cluster)

ray_local()
ray.get([foo.remote(i) for i in range(10)])

ray_remote()
ray.get([bar.remote(i) for i in range(10)])

# We want `foo` to run on the local cluster
@ray.remote
def foo(i):
  return bar.remote()

# We want `bar` to run on the remote cluster
@ray.remote
def bar():
  pass
```

**Comment by franklsf95** [comment]
@valiantljk Thanks, but unfortunately this won't work because I need the task `foo` (which runs on the local cluster) to call `bar`, which I want to run on the remote cluster.

**Comment by ericl** [comment]
This isn't currently possible, but might be added in the future (cc @edoakes )

**Comment by ericl** [comment]
This is now supported https://github.com/ray-project/ray/pull/17942
