### ISSUE TITLE
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.

### ISSUE THREAD

**Issue by tokiinan5** [ray-project/ray#15535]
I am trying to hyperparameter tuning on  [goEmotion](https://github.com/google-research/google-research/tree/master/goemotions) model using RayTune. The program works well in my local machine using a subset of the data set, however when I deploy it in SLURM I get the following errors:

`raise RuntimeError(f"The actor with name {actor_class_name} "
RuntimeError: The actor with name ImplicitFunc failed to be imported, and so cannot execute this method.`

My Trainable is as follows : 

```
def main(config):
  parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
  os.environ["PYTHONPATH"] = parent_dir + ":" + os.environ.get("PYTHONPATH", "")
  

  os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
  alpha=config["alpha"]
  gamma=config["gamma"]
  lr=config["lr"]

  tf.estimator.train_and_evaluate(
        estimator, train_spec=train_spec, eval_spec=eval_spec)
```

and 

```
  if __name__ == "__main__":
  from ray import tune
  from ray.tune.suggest.bayesopt import BayesOptSearch
  import tensorflow as tf
  ray.init()
  
  #import cloudpickle
  #cloudpickle.loads(cloudpickle.dumps(main))
  search_space = {
    "alpha": tune.uniform(0.9, .009),
    "gamma": tune.uniform(2, 4),
    "lr"    :tune.uniform(2e-5, 5e-5)


  }
  search_algo=BayesOptSearch(max_concurrent=4, metric="mean_accuracy", mode="max")
  resources_per_trial={"cpu": 1,"gpu":1}
  metric="mean_accuracy"

  analysis=tune.run(main,
                    config=search_space,
                    search_alg=search_algo,
                    resources_per_trial=resources_per_trial,
                    num_samples=3,stop={"training_iteration": 3}, 
                    max_failures=1,
                    local_dir=tune_output_dir)

  best_config = analysis.get_best_config(metric="mean_accuracy", mode='max')
  if best_config is None:
            logger.error(f'Optimization failed')
  else:
            logger.info("Saving best model config")
            with open(os.path.join(output_dir, 'config_bert.json'), 'w') as f:
                json.dump(best_config, f, indent=4)
 #analysis=tune.run(main)
```

several methods in the main() are class methods

**Comment by krfricke** [comment]
Hi @tokiinan5, usually this means that your trainable is accessing modules/dependencies that are not installed on all machines of the cluster. E.g. if you're using tensorflow, tensorflow has to be installed on all cluster nodes. This is true for all other packages as well.

It's hard to see which other dependencies your code has, but it should be a good start to look through your import statements and make sure that each dependency is available on each node (with the same version).
