### ISSUE TITLE
[core] Objects are spilled before `gc.collect()` finishes

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#15550]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.3/2.0dev

Ubuntu 18.04, 8 cores.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
import dask
import dask.dataframe as dd
import json
import pandas as pd
import numpy as np
import os.path
import csv

from dask.distributed import Client
from dask.distributed import wait

import time


@dask.delayed
def generate(num_bytes):
    nrows = int(num_bytes // 8)
    array = np.random.randint(0, 100, size=(nrows, ), dtype=np.int64)
    return array


@dask.delayed
def select(array):
    return np.random.choice(array)


def run(nbytes, num_consumers):
    times = []
    start = time.time()
    for i in range(20):

        trial_start = time.time()

        array = generate(nbytes)
        futures = []
        for _ in range(num_consumers):
            futures.append(select(array))
        print(dask.compute(*futures)[:10])

        trial_end = time.time()
        duration = trial_end - trial_start
        times.append(duration)
        print("Trial {} done after {}".format(i, duration))

        del futures
        del array
        #import gc
        #gc.collect()

        if time.time() - start > 60:
            break
    return times


if __name__ == '__main__':
    import ray
    from ray.util.dask import ray_dask_get

    ray.init(object_store_memory=4e9)
    dask.config.set(scheduler=ray_dask_get)

    run(1_000_000_000, 4)
```

This script repeatedly generates a large array. With the `gc.collect()` lines commented out, most trials on my laptop complete in about 1.4s, but occasionally one trial takes ~4s. I confirmed that this is because an ObjectRef from a previous round is not getting freed at the end of the loop, and it ends up getting spilled when the next object needs to be stored.

With the `gc.collect()` lines commented in, each trial finishes consistently in 1.4s.

There are two problems here:
1. Dask-on-Ray is probably creating a cyclic reference that's keeping ObjectRefs in scope.
2. Although the raylet triggers `gc.collect()` on the workers once out of memory, it's not giving the workers enough time to complete this before triggering spilling. So we end up spilling objects that would've been collected anyway.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Is the root cause a bad interaction of spilling with global gc triggering? Ideally, we'd trigger global gc before we get close to the spilling threshold to avoid this scenario.

**Comment by stephanie-wang** [comment]
> Is the root cause a bad interaction of spilling with global gc triggering? Ideally, we'd trigger global gc before we get close to the spilling threshold to avoid this scenario.

I think there are two problems:
1. There appears to be a memory leak in Dask-on-Ray.
2. Both global GC and spilling get triggered on OOM (close to 100% capacity). Global GC gets triggered first, but probably, they usually happen concurrently because I think both calls are asynchronous.

**Comment by ericl** [comment]
By memory leak you mean Dask on Ray is storing object refs in structures with cyclic refs? So not technically a leak but not ideal for GC.

**Comment by ericl** [comment]
Hm so maybe we trigger global gc when we hit say 70%? Not sure what the optimal policy here.

**Comment by rkooo567** [comment]
I think triggering a little early sounds like a good short-term remedy. As long as we don't call it frequently, there shouldn't be much perf impact.. but I wonder if there's a systematic way to detect cyclic refs from object refs...

**Comment by iycheng** [comment]
> There appears to be a memory leak in Dask-on-Ray.

I disabled the gc and run the iteration two times. Things are wired. For the first iteration, generation zero in gc gives nothing related to object ref and is like this:
```
[<bound method Event.wait of <threading.Event object at 0x7fe24e986100>>, <bound method Condition.__exit__ of <Condition(<unlocked _thread.lock object at 0x7fe24e986120>, 3)>>, (True, 0.01), <bound method Event.wait of <threading.Event object at 0x7fe24e986100>>, <bound method Condition.__exit__ of <Condition(<unlocked _thread.lock object at 0x7fe24e986120>, 3)>>, (True, 0.01), <bound method Event.wait of <threading.Event object at 0x7fe24e986100>>, <bound method Condition.__exit__ of <Condition(<unlocked _thread.lock object at 0x7fe24e986120>, 3)>>, (True, 0.01)]
```

But for the second it's more complicated, and having things like `cell`, `ObjectRef` and other complicated things. 

This is kind of wired since the first and second iteration run the same code. Even between two iterations, I run `gc.collect` manually, the result is still the same. I still can't figure out the reason for this. But no matter what, I guess we still need to run gc earlier.

> Both global GC and spilling get triggered on OOM (close to 100% capacity). Global GC gets triggered first, but probably, they usually happen concurrently because I think both calls are asynchronous.

Things are a little bit complicated here due to LRU. I plan to use the following algorithm:

 - if used > 0.8 * capacity
    - try eviction first
    - if still greater than 0.8 * capacity
       - if gc hasn't run within some duration run gc

**Comment by ericl** [comment]
We already trigger GC periodically every 10 minutes I believe. How about
raising this frequency with the object store memory usage? E.g.,

50% -> every 100 seconds
75% -> every 10 seconds

There's a bunch of code managing GC frequency that could be modified to
implement this adaptive strategy.

**Comment by iycheng** [comment]
I like the idea of increasing the frequency. Let me check how to implement this. In terms of cycle reference, I don't have a good idea about the root cause.

**Comment by iycheng** [comment]
We'd like to prevent global gc from triggered too frequently, so the minimal time between triggering should be 30s by default.

But this still doesn't fix this specific issue. The reason is that things are happening fast, and we have 30s by default, which is not enough for this case. I'm wondering whether it's enough for practice.
