### ISSUE TITLE
Databricks:  AttributeError: 'ConsoleBuffer' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by joshheitzmanlumedic** [ray-project/ray#15551]
### What is the problem?

The below exception was observed running on Databricks 7.3 LTS clusters when the code at the bottom was run as both a submit job (a .py file entry point) and in a Databricks notebook.

Traceback (most recent call last):
  <redacted>
    ray_ctx.init()
  File "/databricks/python/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 468, in init
    redis_address=redis_address)
  File "/databricks/python/lib/python3.7/site-packages/zoo/ray/raycontext.py", line 525, in _start_driver
    node_ip_address=node_ip)
  File "/databricks/python/lib/python3.7/site-packages/ray/worker.py", line 818, in init
    internal_config=_internal_config)
  File "/databricks/python/lib/python3.7/site-packages/ray/worker.py", line 1119, in connect
    faulthandler.enable(all_threads=False)
AttributeError: 'ConsoleBuffer' object has no attribute 'fileno'

*Ray version and other system information (Python version, TensorFlow version, OS):*

Azure Databricks 7.3 LTS cluster

Standard libraries for a Azure Databricks 7.3 LTS cluster with the addition of only:

analytics-zoo[ray]==0.9.0
analytics_zoo_bigdl_0_12_1_spark_3_0_0_0_9_0_jar_with_dependencies.jar

### Reproduction (REQUIRED)

from zoo.common.nncontext import init_nncontext
sc = init_nncontext()

import ray
from zoo.ray import RayContext

ray_ctx = RayContext(sc=sc, object_store_memory="1g")
ray_ctx.init() # exception raised during this call

@ray.remote
class Counter(object):
	  def __init__(self):
		  self.n = 0

	  def increment(self):
		  self.n += 1
		  return self.n

counters = [Counter.remote() for i in range(1)]
ray.get([c.increment.remote() for c in counters])

ray_ctx.stop()

**Comment by joshheitzmanlumedic** [comment]
May be related to this:  https://github.com/ray-project/ray/issues/2683

**Comment by amogkam** [comment]
Can you add this code before running `ray.init()` 
```
import sys
 
sys.stdout.fileno = lambda: False
```

from https://forums.databricks.com/questions/45772/is-there-step-by-step-guide-how-to-setup-ray-clust.html

**Comment by joshheitzmanlumedic** [comment]
@amogkam That bit of black magic did the trick.  Thanks!

I noticed this comment on the reference post:

> Indeed, this will solve the problem of running ray on a single node (main node) , it doesn't really solve scaling out (running ray on worker nodes as well).

So, I checked the executor logs for any similar errors.  Didn't find any errors, so this looks to be a complete workaround.
