### ISSUE TITLE
[RFC] Proposal to add Ray Namespaces

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15557]
[RFC document](https://docs.google.com/document/d/1XWoof0GFTVkU3kVIwhnrNCDkBFch0CAAMhz7a4q8-xI/edit?usp=sharing)

The TL;DR is to introduce the concept of "namespaces" that can logically separate applications within a cluster. This can be useful for isolation and resource accounting and is particularly useful for long-lived services that outlive the duration of a driver program.

By default, each application will live in its own "anonymous namespace" (one-to-one mapping between driver and namespace) and be isolated from others.

**Comment by lixin-wei** [comment]
I think It’s more easy-to-understand to call it session instead of namespace. Do you think so?

**Comment by lixin-wei** [comment]
BTW, would you please offer some more detailed implementation docs? I noticed there is already an implementation PR. We are concerned whether it will conflict with our internal namespace design.

**Comment by edoakes** [comment]
@lixin-wei we will post a more detailed design doc before actually merging an implementation. The PR that's open from @wuisawesome is just a prototype for an internal demo.

**Comment by lixin-wei** [comment]
> @lixin-wei we will post a more detailed design doc before actually merging an implementation. The PR that's open from @wuisawesome is just a prototype for an internal demo.

Great, could you please ping me when the doc is posted?
