### ISSUE TITLE
[serve] FastAPI hangs during shutdown

### ISSUE THREAD

**Issue by isaac-vidas** [ray-project/ray#15567]
### What is the problem?

While trying out Ray Serve with FastAPI on my local environment, I run the server with `uvicorn api.main_serve:app --reload --log-level debug` and when I try to shut it down (ctrl+c) it hangs.
I tried adding `@app.on_event('shutdown')` and calling `ray.shutdown()` from it or overriding `Server.handle_exit` from `from uvicorn.main import Server` but that doesn't seem to change anything.
When I comment out `ray.init()` and the whole Ray Serve related code  I can shutdown the server with no issues.

*Ray version and other system information (Python version, TensorFlow version, OS):*
```
ray==1.3
fastapi==0.63.0
uvicorn==0.13.4
pydantic==1.8.1
```

and also happened in the following env: 

```
ray==1.2.0
fastapi==0.63.0
uvicorn==0.13.4
pydantic==1.6
```

### Reproduction (REQUIRED)

The code that I used is from the `transformers` example:

```
import ray
from ray import serve
from fastapi import FastAPI
from transformers import pipeline

# Start the web service
app = FastAPI()

# Load the model
nlp_model = pipeline("text-generation", model="gpt2")

serve_handle = None


@app.on_event("startup")
async def startup_event():
    ray.init()
    # Default port is 8000 but FastAPI takes that by default
    client = serve.start(http_port=8001)
    class GPT2:
        def __init__(self):
            self.nlp_model = pipeline("text-generation", model="gpt2")
        def __call__(self, request):
            return self.nlp_model(request.query_params["data"], max_length=50)
    client.create_backend(
        "gpt-2", 
        GPT2, 
        config={"num_replicas": 10}
    )
    client.create_endpoint(
        "gpt-endpoint", 
        backend="gpt-2"
    )
    global serve_handle
    serve_handle = client.get_handle("gpt-endpoint")


@app.get("/generate")
async def generate(query: str):
    return await serve_handle.remote(data=query)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@simon-mo can you please take a look and try to repro this?

**Comment by simon-mo** [comment]
hmm i'm have trouble repro this locally. control C worked for me locally with uvicorn:
```
INFO:     127.0.0.1:49182 - "GET /generate?query=hiiii HTTP/1.1" 200 OK
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [33304]
```
can you try with nightly? https://docs.ray.io/en/master/installation.html#daily-releases-nightlies

**Comment by isaac-vidas** [comment]
Seems to be working fine after I upgraded to `1.4`.

Closing this for now.
