### ISSUE TITLE
Suppress FutureWarnings about dependencies

### ISSUE THREAD

**Issue by RemKamal** [ray-project/ray#15587]
Hello all,

Using ray with a simple actor, I keep getting messages of this type:
cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.\n",

When I changed logging to logging.CRITICAL, the warning still does not go away.
Please let  me know if I miss anything obvious.

Thanks,
Remkamal 
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by QiuZiXian** [comment]
I ran into a similar situation.
My environment is win10 and python3.8.3
when I install ray follow the document of ray site （https://docs.ray.io/en/master/installation.html）
`pip install -U ray`
then run the code below
`import ray
ray.init()`
but it throws an exception like
`D:\app\anaconda3\lib\site-packages\ray\autoscaler\_private\cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  warnings.warn(
2021-05-14 17:28:32,467	ERROR services.py:1276 -- Failed to start the dashboard: Failed to read dashbord log: [Errno 2] No such file or directory: 'C:\\Users\\87875\\AppData\\Local\\Temp\\ray\\session_2021-05-14_17-28-27_851918_18328\\logs\\dashboard.log'
`
I find the path of logs，but I can't find the file dashboard.log

[https://github.com/ray-project/ray/issues/9114](url)
mfitton say ：the dashboard currently does not work on Windows. I recommend passing include_dashboard=False when calling ray.init()
follow this method，I solve the first problem，but second one still remain.
` After a while，Process finished with exit code 0`

so how to use dashboard on win?

**Comment by RemKamal** [comment]
I managed to get rid of those warnings by:
from ray.autoscaler._private.cli_logger import cli_logger
cli_logger._warning(msg=None,_level_str="ERROR")

Then, even setting log_to_driver to False, it still creates thousands of logs for my actors, so I keep deleting them manually from the /tmp/ray/session_latest/logs.
