### ISSUE TITLE
[tune] With optuna randint's upper bound looks inclusive.

### ISSUE THREAD

**Issue by hotohoto** [ray-project/ray#15593]
### What is the problem?

(AS IS)

With Optuna, `b=10` was found from `tune.randint(0, 10)`, even though the upper bound is supposed to be exclusive according to https://docs.ray.io/en/master/tune/api_docs/search_space.html#ray.tune.randint.

![image](https://user-images.githubusercontent.com/5404902/116665611-f2681380-a9d4-11eb-89ae-bbe955ea3032.png)

(TO BE)

b=10 should not be found

(FYI)

- With `HyperOptSearch` or `TuneBOHB`, there is the same bug.
- But `tune.randint(0, 10).sample()` looked good.

(Versions)

* ray version: `1.2.0`, `1.3.0`, and `2.0.0.dev0`
* optuna: `2.7.0`
* no tensorflow
* python version `3.8.3`
* Ubuntu `20.04.2 LTS`

### Reproduction (REQUIRED)

```
import ray
import math
from ray import tune
from ray.tune.suggest.optuna import OptunaSearch

def my_trainable(config):
    def func(x, a, b):
        return math.log((a + b)**2 + ((x-5)**2)/100)

    for x in range(10):
        score = func(x, config["a"], config["b"])
        tune.report(score=score)

config = {
    "a": tune.uniform(-50, 50),
    "b": tune.randint(0, 10),
}

optuna_search = OptunaSearch(
    metric="score",
    mode="min",
)

analysis3 = tune.run(
    my_trainable,
    num_samples=10,
    config=config,
    search_alg=optuna_search
)
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [*] I have verified my script runs in a clean environment and reproduces the issue.
- [*] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
I see, this is because Optuna defines randint as inclusive:

https://optuna.readthedocs.io/en/stable/reference/generated/optuna.distributions.DiscreteUniformDistribution.html#optuna.distributions.DiscreteUniformDistribution

So in this case we will just have to subtract 1 from the higher bound in the search space conversion.

This is pretty straightforward,. Do you want to file a PR for that? Otherwise I can get to it sometime this week.

**Comment by hotohoto** [comment]
I hope all the search algorithms be checked via one or more unit tests if it's possible because the same thing happened with `HyperOptSearch ` and `TuneBOHB`. (I didn't check all the algorithms.)

I've changed the upper bound as you mentioned. So, there is no hurry from my side, I'm just waiting for the next official release. Thanks a lot.
