### ISSUE TITLE
K8s Operator: Ray processes not restarting when container restarts

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#15608]
### What is the problem?

For various reasons, Kubernetes may decide to recreate the containers within a Pod. When this happens, the Ray setup commands are not run again, resulting in the container having no Ray processes running.

If something triggers a restart of the container, the Ray cluster should eventually come back into a ready state as though it were initialized for the first time.

### Reproduction (REQUIRED)

Launch a single-node Ray cluster via the Ray Operator. Force a restart of the `ray-node` container (note: have not yet been able to reliably repro this part yet, but I assume there is a way to do this).

Run `kubectl describe pod <pod_name>`. Should show that the container was created some time after the Pod itself:

```
Name:         my-cluster-ray-head-29dns
Namespace:    ray
Priority:     0
Node:         ...
Start Time:   Thu, 29 Apr 2021 18:51:49 -0700
Labels:       ...
Annotations:  <none>
Status:       Running
...
Controlled By:  RayCluster/my-cluster
Containers:
  ray-node: ...
    Ports:         6379/TCP, 10001/TCP, 8265/TCP, 8000/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      --
    Args:
      trap : TERM INT; sleep infinity & wait;
    State:          Running
      Started:      Sat, 01 May 2021 20:16:16 -0700
    Ready:          True
    Restart Count:  0
```

Note that the `Restart Count` is listed as 0, though the container was definitely restarted (in this case, over a day after the Pod was created). This may be related, but not sure.

SSH into the ray-node container, and you should notice that `ps -aux` shows no Ray processes and `ls /tmp` shows an empty directory.

cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Thanks for bringing this up.
Closely related:
https://github.com/ray-project/ray/issues/14634

The situation is that there is currently zero tolerance for head pod failure/restarts.

**Comment by DmitriGekhtman** [comment]
After this https://github.com/ray-project/ray/pull/15526 is merged, you'd at least get an update that the Ray cluster is in an error state.

**Comment by DmitriGekhtman** [comment]
Head failure is an actual cause for concern when running the head in a k8s pod 
(as opposed to just using vms)
cc @ericl @pcmoritz
