### ISSUE TITLE
[runtime_env] Basic working_dir not working with ray.init()

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15620]
```python
import ray

job_config = ray.job_config.JobConfig(runtime_env={"working_dir": "."})
ray.init(job_config=job_config)

@ray.remote
class Test:
    def hi(self, *args):
        with open("hello") as f:
            return f.read()

t = Test.remote()

assert ray.get(t.hi.remote()) == "hello"
```

**Comment by iycheng** [comment]
@edoakes  The reason it failed is that when calling init and the core worker is constructed, it'll spawn workers immediately and it'll fail to fetch the jobs.

The reason the test case runs ok is because it's not running by init directly. It tests init to existing cluster or client connect to an existing cluster. Let me see how to fix this.

**Comment by iycheng** [comment]
I thought about it a little bit and I think it doesn't make sense in this case. In this case, ray is local, so we should have all the envs there. I can add a check for this usage. Do you think that's OK? @edoakes

**Comment by edoakes** [comment]
Hmm I think we definitely need to support this, otherwise it'll be really confusing to users who want to do local testing. Shouldn't the worker pool be keyed on the job config? I didn't fully understand the reason why this isn't working.

**Comment by iycheng** [comment]
The reason is that, if it's a fresh start, it'll start some workers with the job config and these workers will not be able to access the uris.

**Comment by edoakes** [comment]
Sorry, still not following. If they're started with the job config then shouldn't they have the correct URIs?

**Comment by iycheng** [comment]
> Sorry, still not following. If they're started with the job config then shouldn't they have the correct URIs?

I made the fixing for this. In raylet, there is an option where it'll try to init worker when core worker got created. We need to upload it later after creating the core worker.
