### ISSUE TITLE
Object spilling does not seem to work in Ray 1.3 on Windows machine

### ISSUE THREAD

**Issue by hannahbus** [ray-project/ray#15633]
### What is the problem?

I am using Ray 1.3, Python 3.8.5 and Spyder 5.0  on a Windows 10 machine (8 CPU, 8 GB RAM). 

I parallelize a function, which returns large objects. The return objects eventually fill up the object store leading the programme to crash. I was hoping that with Ray 1.3 the programme would not crash as the documentation says: "In Ray 1.3+, objects will be spilled to disk if the object store fills up." 

In what follows, I provide a minimal example to showcase my use case. The attached file contains the corresponding error message: [Error_Output.txt](https://github.com/ray-project/ray/files/6421375/Error_Output.txt)

### Reproduction Code 

```
import numpy as np
import time
from time import sleep 
import ray 
import sys

 
test = []
N = 10**1
list = [list(range(N)), list(range(N+1))]
ray.init(num_cpus = 3) 

@ray.remote 
def some_function(t, list): 
    sleep(t)
    return np.random.random((10**5, 100))


list_ref = ray.put(list)
processing = [some_function.remote(time, list_ref) for time in 10**3 * [1]]

 while len(processing) > 0:
    done, processing = ray.wait(processing)
    returns = ray.get(done)
    test.append(np.copy(returns))
    del returns

ray.shutdown()
```

**Comment by mattip** [comment]
@hannahbus can you try with latest ray 2.9.3?
