### ISSUE TITLE
Missing argument "max_calls" for RemoteFunction.options

### ISSUE THREAD

**Issue by Deathn0t** [ray-project/ray#15649]
I was wondering if it was normal for `ray.remote_function.RemoteFunction.options` to not have the `max_calls` argument which is technically good for `ray.remote`? I think it would be more coherent to have it here as well.

Is there any technical limitation?

https://docs.ray.io/en/latest/package-ref.html#ray-remote

**Comment by simon-mo** [comment]
There isn't any technical limitation, rather simply missing implementation, feel free to submit a PR! 😁

**Comment by Deathn0t** [comment]
Thanks for your answer @simon-mo! I will try. I was wondering is there any advantage of using `RemoteFunction.options` over `ray.remote` at run time (in a functional manner such as `remote_func = ray.remote(...)(func)`?

**Comment by simon-mo** [comment]
They are equivalent. Even though ray.remote is often documented as a decorator, using it `remote_func = ray.remote(...)(func)` is totally fine, and in fact, several libraries like Ray Tune and Ray Serve use this pattern.

**Comment by DonYum** [comment]
+1
I'm also confused of missing `max_calls` in options().
