### ISSUE TITLE
[serve] Problem with serving 

### ISSUE THREAD

**Issue by ar0ra1** [ray-project/ray#15666]
I am following the [documentation](https://docs.ray.io/en/master/serve/index.html#ray-serve-quickstart) and I can't seem to get it working. 

Pre-req: ` pip install ray[serve]`

Error: 
```
/Users/<user>/PycharmProjects/ray_rllib/venv/bin/python /Users/<user>/PycharmProjects/ray_rllib/e2e.py
2021-05-06 19:31:12,157	INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=8075) 2021-05-06 19:31:14,394	INFO http_state.py:67 -- Starting HTTP proxy with name 'fDRrsO:SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:192.168.0.192-0' on node 'node:192.168.0.192-0' listening on '127.0.0.1:8000'
Traceback (most recent call last):
  File "/Users/<user>/PycharmProjects/ray_rllib/e2e.py", line 14, in <module>
    hello.deploy()
AttributeError: 'function' object has no attribute 'deploy'
(pid=8073) INFO:     Started server process [8073]

Process finished with exit code 1

```

**Comment by simon-mo** [comment]
Hi the documentation correspond to Ray nightly. please install https://docs.ray.io/en/master/installation.html#daily-releases-nightlies

alternatively you can view the released version of the doc here
https://docs.ray.io/en/latest/serve/index.html

**Comment by ar0ra1** [comment]
Oh!

I thought the entire documentation refers to the official release and not the nightly
