### ISSUE TITLE
Set time-out on individual ray task

### ISSUE THREAD

**Issue by asm582** [ray-project/ray#15672]
Hello @rkooo567 ,

Consider a scenario for which large numbers of tasks with some outliers are present. We want the ability in ray in the form of python decorators to time-out individual tasks. Such functionality is provided in spark here: https://stackoverflow.com/questions/63389263/how-to-set-timeout-to-a-spark-task-or-map-operation-or-skip-long-running-task

Here is an example use case:

The below list  user_task consists of normal_task and long_task :
user_task [normal_task, normal_task, normal_task, long_task, normal_task, normal_task]

where normal_tasks are tasks that run within time-out and long_task is a task that runs for a very long time termed as an outlier.
we looked at ray.wait and ray.cancel APIs it does not have the capability to set time-out at the individual task level, in other words, we want to provide an opportunity to run all the tasks in the above user_tasks array and time-out outlier tasks.

Please let us know if you need any further details.

**Comment by rkooo567** [comment]
Hey @ijrsvt @richardliaw do you guys know any good way to achieve this?

**Comment by clarkzinzow** [comment]
If you're willing to apply a timeout uniformly to a set of tasks, wouldn't something like the following `ray.wait()` flow work?
```python
user_task = [task1, task2, task3, task4]
TASK_TIMEOUT = 10.0
done, in_progress = ray.wait(user_task, num_returns=len(user_task), timeout=TASK_TIMEOUT, fetch_local=False)
for task in in_progress:
    ray.cancel(task)
```
This should cancel any tasks that take longer than `TASK_TIMEOUT` to run.

If you're looking to specify different timeouts for each task, how to achieve that is less obvious to me.

**Comment by clarkzinzow** [comment]
If you're willing to apply a timeout uniformly to a set of tasks, wouldn't something like the following `ray.wait()` flow work?
```python
user_task = [task1, task2, task3, task4]
TASK_TIMEOUT = 10.0
done, in_progress = ray.wait(user_task, num_returns=len(user_task), timeout=TASK_TIMEOUT, fetch_local=False)
for task in in_progress:
    ray.cancel(task)
```
This should cancel any tasks that take longer than `TASK_TIMEOUT` to run.

If you're looking to specify different timeouts for each task, how to achieve that is less obvious to me.

**Comment by asm582** [comment]
@clarkzinzow Thank you for replying but this does not help since a long outlier task will lead to canceling tasks that never ran, please refer to the spark link shared for more details.

**Comment by ijrsvt** [comment]
Hmm, one way to do this (albeit a bit heavyweight) is to create some sort of wrapper
```
@ray.remote(num_cpus=0.01)
def wrapper(function, timeout, force=False):
    x = function.remote()
    _, unfinished = ray.wait([x], timeout=timeout)
    if len(unfinished) > 0:
        ray.cancel(unfinished[0], force=force)
	return ray.get(x)
```

**Comment by asm582** [comment]
@ijrsvt thank you. when you say unfinished how does not know if the task is queued or running?

**Comment by ijrsvt** [comment]
Oh, there is no distinction between queued and running here.

**Comment by clarkzinzow** [comment]
>Thank you for replying but this does not help since a long outlier task will lead to canceling tasks that never ran, please refer to the spark link shared for more details.

Maybe I'm misunderstanding, but what I gave above will only cancel tasks that are not yet finished after `TASK_TIMEOUT` seconds, since only tasks that are not yet finished after `TASK_TIMEOUT` seconds will be returned in the `in_progress` list. If you're talking about wanting to only cancel a task if it has been _running_ for longer than `TASK_TIMEOUT` (not including queue time), then I think that would have to be manually implemented using an actor, where each task registers itself with the actor once it's running, and if it the task doesn't finish after `TASK_TIMEOUT` seconds, the actor cancels the task.

>thank you. when you say unfinished, how does one know if the task is queued or running?

I don't think that there's a way to delineate between queued and running tasks there.

**Comment by asm582** [comment]
@clarkzinzow How do you know if a task is in a "running" state? from the above solution, it looks like you are suggesting to register the task at submit time. If there are a large number of tasks it is possible that some tasks are queued but currently user has no information about the state of the task I think

**Comment by asm582** [comment]
> @ijrsvt thank you. when you say unfinished, how does one know if the task is queued or running?

so then is it the case that we might be killing a queued task? we want to provide opportunity for every task to be in state running, after spending time in state running greater than time-out we want to kill such tasks

**Comment by asm582** [comment]
> > Thank you for replying but this does not help since a long outlier task will lead to canceling tasks that never ran, please refer to the spark link shared for more details.
> 
> Maybe I'm misunderstanding, but what I gave above will only cancel tasks that are not yet finished after `TASK_TIMEOUT` seconds, since only tasks that are not yet finished after `TASK_TIMEOUT` seconds will be returned in the `in_progress` list. If you're talking about wanting to only cancel a task if it has been _running_ for longer than `TASK_TIMEOUT` (not including queue time), then I think that would have to be manually implemented using an actor, where each task registers itself with the actor once it's running, and if it the task doesn't finish after `TASK_TIMEOUT` seconds, the actor cancels the task.
> 
> > thank you. when you say unfinished, how does one know if the task is queued or running?
> 
> I don't think that there's a way to delineate between queued and running tasks there.

It would be of great help if you could share a code snippet of task registration with the actor while running, I tried your idea after a task is started but unable to send object reference for a task that is started so that I can use ray.cancel

**Comment by richardliaw** [comment]
@asm582 why don't you just use an actor method instead of a "task and actor" or wrangling ray.wait + ray.cancel here? You will be able to better control the lifecycle of the executed task:

```python
@ray.remote(max_concurrent_calls=2)
class Function:
    def __init__(self):
        self._start = None
        
    def execute(self, fn):
        self._start = time.time()
        return fn()
        
    def duration(self):
        return time.time() - self._start
        
        
funcs = [Function.remote() for i in range(...)]
everyone = [f.execute.remote(your_func) for f in funcs]
duration = ray.get(everyone[0].duration.remote())
if duration > 50:
    ray.kill(everyone[0])
```

Let me know if that works for you?

**Comment by richardliaw** [comment]
good point :)

**Comment by asm582** [comment]
Thanks @richardliaw  and @rkooo567 I am trying to run the sample code that you shared and I get the below error:

![Screen Shot 2021-05-07 at 3 23 00 PM](https://user-images.githubusercontent.com/5898557/117498841-572cec00-af48-11eb-93dd-5899945471f5.png)

**Comment by asm582** [comment]
> You should be doing:
> 
> ```python
> f.execute.remote(a)
> ```
> 
> Right now the code will kill the first task.

Yes thank you, the returned function does not have the duration attribute, any suggestions:

![Screen Shot 2021-05-07 at 3 37 00 PM](https://user-images.githubusercontent.com/5898557/117500118-2f3e8800-af4a-11eb-9de8-fb5cb0ddcf66.png)

**Comment by richardliaw** [comment]
sorry can you replace that line with `(funcs[0].duration.remote())`

**Comment by asm582** [comment]
@richardliaw ok the program runs but it let run the dummy task for 50 seconds and then killed the actor not the task as I understand, Here is the output:

[ObjectRef(9bb55bc9a880f4cefc8204747604c8cce2230de40100000001000000), ObjectRef(aae99729138a74d29d78bd90898368ca67cdd5970100000001000000), ObjectRef(c0e56a21dcb5fe6436e14f5d7a18682e2d3056080100000001000000), ObjectRef(764f8475f05bf00148b7ee15cf1ae472a4bb9b7e0100000001000000)]
The duration obtained is: 50.00698804855347
killing actor: ObjectRef(9bb55bc9a880f4cefc8204747604c8cce2230de40100000001000000)

So in a scenario where there are thousands of tasks, an outlier task may run to never run to completion. We want to detect the running time of a task i.e. time spent doing computation if the running time of a task is greater than the threshold then kill such task(s). I am not sure if the above sample code achieves the same.

**Comment by asm582** [comment]
Thanks for the prompt response @richardliaw 
ray.wait returns two arrays, I assume you are referring to check of remaining ids?

Due to resource constraints actors are created but I don't see them in duration or result list:

![Screen Shot 2021-05-07 at 6 06 43 PM](https://user-images.githubusercontent.com/5898557/117513099-007edc80-af5f-11eb-8ebd-6a5645a49dbd.png)

Do you think of a possibility to create a new API or python decorator to handle such a scenario?

**Comment by richardliaw** [comment]
I think we will consider it if we have a couple more independent requests to handle such a scenario. 

Can you post your code? I do think that you are quite close to a working implementation.

**Comment by asm582** [comment]
@richardliaw , Here is the code snippet, it does not run as expected. I have questions added to the implementation, can you please answer those?

```
#Goal: run all tasks and kill running task that continues to run after 10 seconds
ray.init(num_cpus=4, ignore_reinit_error=True)

def a(i):
    time.sleep(i*5)
    return I

@ray.remote(num_cpus=1)
class Function:
    import time
    def __init__(self):
        self._start = None      
    def execute(self, fn, i):
        self._start = time.time()
        return fn(i)   
    def duration(self):
        return time.time() - self._start

#code that loops and kills tasks
#create 5 actros
funcs = [Function.remote() for i in range(5)]

#create dummys sleep tasks that sleeps for 
# i*5 seconds where i is from 0 t0 4
i = 0
everyone = []
for f in funcs:
    everyone.append(f.execute.remote(a,i))
    i = i + 1
    
#actors that runs sleep functions
all_durations = [f.duration.remote() for f in funcs]
print("The duration is: "+str(all_durations))

while True:
    #ready tasks are the tasks that have finished running??
    #remaining tasks are tasks that are queue???
    #will ray.wait ever return for an outlier task ??
    ready, remaining = ray.wait(all_durations)
    print("The ready tasks are: "+str(ready))
    #ray.get with task from ready map will provide time after the task is completed running, not when it is running
    time_run = ray.get(ready[0])
    print("The running time of task is: "+str(time_run))
    if time_run > 10:
        #ray.kill needs an actor id, how to map actors to ids (references) returned by ray.wait, do not know the order of execution
        ray.kill(result)
    time.sleep(1)
```

**Comment by asm582** [comment]
@richardliaw  can you please help with the above questions

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/18916
