### ISSUE TITLE
[tune/huggingface] TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by roxanadangerm** [ray-project/ray#15678]
Hello @richardliaw ,

I am testing a huggingface code (https://github.com/huggingface/notebooks/blob/master/examples/text_classification.ipynb) that uses Ray for fine tuning, but I getting an error "cannot pickle thread.RLock object"

### Environment info:
- Platform: Linux
- Python version: 3.8.5
- Torch version: 1.8.1
- transformers: 4.3.2

### Reproduction (REQUIRED)

The following lines define my Dockerfile:

FROM nvidia/cuda:11.0-base
CMD nvidia-smi

#set up environment
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get install unzip
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

RUN pip3 install jupyter ipywidgets scipy sklearn torch datasets transformers===4.3.2

RUN pip3 install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl

=============

Inside the container, please execute the notebook at: https://github.com/huggingface/notebooks/blob/master/examples/text_classification.ipynb. The problem occurs in the cell: 

best_run = trainer.hyperparameter_search(n_trials=10, direction="maximize")

I was testing the task='sstb', change this variable in cell 3.

Best regards,
RD

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
OK I just figured out the issue.

Turns out `metric` objects are not serializable after you touch them.

Can you try something like re-creating the metric object when you call `hyperparameter search`?

```python
metric = load_metric('glue', actual_task)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    if task != "stsb":
        predictions = np.argmax(predictions, axis=1)
    else:
        predictions = predictions[:, 0]
    return metric.compute(predictions=predictions, references=labels)

trainer = Trainer(
    model_init=model_init,
    args=args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset[validation_key],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)
trainer.hyperparameter_search(...)
```

**Comment by roxanadangerm** [comment]
Yes, this worked.
Thank you very much, @richardliaw .
