### ISSUE TITLE
[Tune] Significant impact on performance of unnecessary copy `TBXLogger.on_result` (~20%)

### ISSUE THREAD

**Issue by duburcqa** [ray-project/ray#15699]
`TBXLogger.on_result` is calling `flatten_dict` internally in order to flatten the dictionary of data to monitor [here](https://github.com/ray-project/ray/blob/996a002b00356d66c2feb071cef9e1a1f0b3f0e7/python/ray/tune/logger.py#L195). So far so good, but `flatten_dict` is doing a copy internally, without any optional argument to prevent it. In this case, it appears to be irrelevant after some testing, or may be necessary in only some edge cases I'm not aware of. In my setup, it is significantly affecting the performance, slowing down the optimization by about 20%. I'm logging several histogram data (about 10), and running PPO on a medium-size real world problem (training batch size ~ 30000).

Here are flamegraphs obtained using `py-spy` before and after replacing `copy.deepcopy` by `copy.copy` in `flatten_dict`. 

![image](https://user-images.githubusercontent.com/17752950/117545486-481c6b80-b026-11eb-9c7b-3a8dc112349c.png)

![image](https://user-images.githubusercontent.com/17752950/117545466-2d49f700-b026-11eb-8fb8-055bf7242219.png)

**Comment by richardliaw** [comment]
hey @duburcqa, thanks for bringing this up!

Maybe we can implement the flatten in a way that doesn't deepcopy all of the leaf items (like your histograms), only the dictionary containers?

Does your patch do that? If so, it'd be great if you could push a short draft PR (I could help shepherd/clean it up!)

**Comment by duburcqa** [comment]
@richardliaw I created the PR a few days ago, if someone want to have a look.
