### ISSUE TITLE
[rllib] PPO KL coefficient update differs from original paper

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#15698]
### What is the problem?

As [reported on ray.discuss](https://discuss.ray.io/t/diffrences-between-the-ppo-implementation-and-the-origonal-ppo-paper/1735) by user [levmckinney](https://discuss.ray.io/u/levmckinney), the factors for the update of the KL coefficient differ from the original paper.

The difference exists in the [TF implementation](https://github.com/ray-project/ray/blob/5f0be94989030f0a796c49ec14b5a96878a5ba06/rllib/agents/ppo/ppo_tf_policy.py#L225), as well as in the [torch implementation](https://github.com/ray-project/ray/blob/5f0be94989030f0a796c49ec14b5a96878a5ba06/rllib/agents/ppo/ppo_torch_policy.py#L188).
        
Original Paper: [Link](https://arxiv.org/pdf/1707.06347.pdf)

**Comment by richardliaw** [comment]
cc @sven1977

**Comment by sven1977** [comment]
Thanks for raising this issue @ArturNiederfahrenhorst !
I left a comment on discuss. I don't think the difference is big enough to justify a change right now as it could (but should not) break people's baselines/tuned configs.
Let me know, if you think the current values could potentially negatively affect PPO's learning.

**Comment by ArturNiederfahrenhorst** [comment]
Consensus is that this HP should be left alone. Quoting from ray.discuss:
> Probably it was implemented based on earlier iterations of the PPO paper. I don’t think this hyperparameter is particularly sensitive though, it would be safer to leave it alone to avoid any backward incompatible changes.
