### ISSUE TITLE
Docker container: can't install g++

### ISSUE THREAD

**Issue by mjuric** [ray-project/ray#15707]
### What is the problem?

I'm trying to build an image derived `FROM rayproject/ray:latest-cpu`, but cannot install g++ (which I need to build some third-party code that my code needs).

Is it possible something is broken with apt in ray's current Docker image?

### Reproduction (REQUIRED)

```
$ docker run --rm -it rayproject/ray:latest-cpu

(base) ray@b5265bc683d6:~$ sudo -s apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
...snip...
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4305 B]
Fetched 17.7 MB in 4s (4544 kB/s)
Reading package lists... Done

(base) ray@b5265bc683d6:~$ sudo -s apt-get install g++
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 g++ : Depends: g++-9 (>= 9.3.0-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
I think this is not ray related -- perhaps this should fix it https://askubuntu.com/questions/723955/sudo-apt-get-install-g-unmet-dependencies
