### ISSUE TITLE
[rllib] Avoid calling the model.value_function twice in ppo_torch_policy

### ISSUE THREAD

**Issue by yangysc** [ray-project/ray#15711]
### What is the problem?

For the case of `vf_share_layers= False` and `use_critic=True`,  calling the `model.value_function()` twice in ppo_torch_policy would call the forward function twice, which may **be time-consuming for large encoder net**.

https://github.com/ray-project/ray/blob/0026cf1be6411a0e5eecd7a784c1d4ab8db47ebb/rllib/agents/ppo/ppo_torch_policy.py#L86-L113

Instead we can save the value, to avoid calling `model.value_function` twice. @sven1977 
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Hey @yangysc . Absolutely, this could be a problem with large torch models.

Will fix this.

Also, we are working on deprecating the ModelV2 API (with the `value_function` call) anyways right now, such that it's be more transparent for users what's actually happening under the hood when models are called.
