### ISSUE TITLE
[autoscaler] memory usage rarely shown in the monitor logs

### ISSUE THREAD

**Issue by philippeboyd** [ray-project/ray#15739]
### What is the problem?

Autoscaler info sometimes show `memory` and `object_store_memory` and sometimes doesn't.

```
2021-05-11 16:10:16,057	INFO autoscaler.py:309 --
======== Autoscaler status: 2021-05-11 16:10:16.056925 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head
 8 ray_worker_64
 8 ray_worker_48
Pending:
 (no pending nodes)
Recent failures:
 10.30.20.77: ray_worker_64
 10.30.20.73: ray_worker_48

Resources
---------------------------------------------------------------

Usage:
 881.0/883.0 CPU
 352.60/2486.849 GiB memory
 151.12/1067.135 GiB object_store_memory

2021-05-11 16:10:22,599	INFO autoscaler.py:309 --
======== Autoscaler status: 2021-05-11 16:10:22.599602 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head
 8 ray_worker_64
 8 ray_worker_48
Pending:
 (no pending nodes)
Recent failures:
 10.30.20.77: ray_worker_64
 10.30.20.73: ray_worker_48

Resources
---------------------------------------------------------------

Usage:
 883.0/883.0 CPU
 0.00/2486.849 GiB memory
 0.00/1067.135 GiB object_store_memory
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 1.3.0 (1.2.0 also), python 3.8

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Following this starter (on GCP in my case) [https://docs.ray.io/en/master/cluster/cloud.html](https://docs.ray.io/en/master/cluster/cloud.html), run any kind of workload and memory usage will rarely be shown in the monitor logs

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
closing since we've stabilized these quite a bit since 1.3
