### ISSUE TITLE
[RLlib] AttributeError: 'numpy.ndarray' object has no attribute 'get_shape' when running custom_rnn_model example with framework tf2 or tfe

### ISSUE THREAD

**Issue by kk-55** [ray-project/ray#15764]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray, version 2.0.0.dev0
Python 3.8.8, 64-bit
tf.__version__ 2.4.1
Microsoft Windows 10 Pro

AttributeError 'numpy.ndarray' object has no attribute 'get_shape' when using method `add_time_dimension` with framework configs `tf2` or `tfe`. If variable `padded_inputs` is an numpy array which seems to occur with framework configs `tf2` or `tfe`, then `get_shape` is unknown for 'numpy.ndarray'.

![grafik](https://user-images.githubusercontent.com/63732956/118009456-58965400-b34e-11eb-88c8-07a71b5febfb.png)

### Reproduction (REQUIRED)
Issue can be reproduced when running example script custom_rnn_model.py and framework config either `tf2` or `tfe`.

The following quick workaround seems working with all tensorflow framework configs:
`new_shape = ([new_batch_size, max_seq_len] +
                     list(padded_inputs.shape[1:]))`

![grafik](https://user-images.githubusercontent.com/63732956/118014413-7b773700-b353-11eb-9a90-98dee3e992f3.png)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
@kk-55 could you submit a PR to fix? that would be really appreciated!

**Comment by kk-55** [comment]
@richardliaw I've submitted this PR #16868
