### ISSUE TITLE
[RFC] Ray succeeds its first 100TB shuffle.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#15770]
2 weeks ago, we succeed 100TB streaming shuffle for the first time :slightly_smiling_face: (technically 90TB). 

**Note:** the current 100TB shuffle experiment is not actually using 100TB sort implementation (but it is using script that stresses the network & storage & memory layer of Ray in the same way). We are planning to implement sorting algorithm for further testing and performance optimization in the future.

Check out this file to see the code (https://github.com/ray-project/ray/blob/master/python/ray/experimental/shuffle.py).

## The cluster spec
- 50 i3.8xl (32 cpus per each)
  - 110GB object store memory per each
  - 4, 1.5TB NVME 
  - 1500 partitions 
  - 63GB partition size

Therefore, there are 
- 90 TB data size
- 1500 ** 2 == 2250000 (22 millions) Ray objects
- 1600 CPUs
- 5500GB object store memory
- 300TB SSD

in the Ray cluster. 

## Experiment 
**Data size**
90TB shuffle with 1500 partitions. (22 millions Ray objects)

**Result**
Shuffled 90122222 MiB in 7976.173890590668 seconds

**Performance analysis**
Note I used 50 i3.8xl and 4 nvme per node (1 wasn’t enough to shuffle 100TB because it will only have 50TB disks).

Here’s the theoretical performance calculation. The calculation is done by `data_size / read_bandwidth + data_size / write_bandwidth + data_size / network bandwidth`

```
>>> t = 180000 / (16*4*n) + 90000 / (0.6*n);
>>> t
3056.25
```

So we are about 38% of the theoretical performance.

Here’s more details about how it is calculated.
```
100TiB shuffle given N i3.8xl nodes
- 32*N physical cores
- 16*N*4 GiB/s SSD IO (4 NVME)
- 0.6*N GiB/s network IO (10Gbps / 8 for bits / 2 for send recv)
M partitions
Need to write 90000GiB of data
Need to transfer 90000GiB over network
Need to do M^2 partitions object location lookups
Need to read 90000GiB of data
Total time for shuffle =
    90000 / (16*4*N) +   # write
    90000 / (16*4*N) +   # read
    90000 / (0.6*N) +  # shuffle
```

**Comment by rkooo567** [comment]
cc @ericl @stephanie-wang @clarkzinzow @iycheng @valiantljk @kfstorm

**Comment by vecorro** [comment]
Thanks, @rkooo567. I already opened a report (https://github.com/ray-project/ray/issues/15500) several weeks ago but have not received a response yet.

When you say that you used a "raw deployment", do you mean something like this https://docs.ray.io/en/master/cluster/quickstart.html ?

**Comment by rkooo567** [comment]
It's the extension of this autoscaler config! https://github.com/ray-project/ray/blob/master/release/data_processing_tests/multi_node.yaml. Let's actually follow up your issue in your thread, not here.

**Comment by kfstorm** [comment]
@rkooo567 Have you tried more partitions with a smaller partition size? e.g. 10000 partitions * 9GB partition size

**Comment by rkooo567** [comment]
@kfstorm We haven't. 10000 partitions will generate 100 million ray objects, so it'd be a pretty good stress testing workload. But we don't currently have a plan to have this much of stress test. (So please feel free to do so!)

**Comment by rkooo567** [comment]
cc @franklsf95 can you share the cluster.yaml people can reproduce the result?

**Comment by richardliaw** [comment]
Closing this since it's been over 6 months.
