### ISSUE TITLE
[tune] s3 sync issue kills job

### ISSUE THREAD

**Issue by vlad17** [ray-project/ray#1578]
[err.txt](https://github.com/ray-project/ray/files/1746542/err.txt)

### System information

    (tensorflow_p36) ubuntu@ip-172-31-19-252:~$ uname -a
    Linux ip-172-31-19-252 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    (tensorflow_p36) ubuntu@ip-172-31-19-252:~$ python -c "import ray; print(ray.__version__)"
    0.3.1
    (tensorflow_p36) ubuntu@ip-172-31-19-252:~$ python -V
    Python 3.6.3 :: Anaconda, Inc.

In the middle of a tune hyperparameter search, I received the following error:

```
ERROR trials:
 - ray_train_1_dyn_bn=False,dyn_dropout=0,dyn_l2_reg=0,exp_name=do-0,l2-0,bn-False:     ERROR => /home/ubuntu/ray_results/dyn-reg/ray_train_1_dyn_bn=False,dyn_dropout=0,dyn_l2_reg=0,exp_name=do-0,l2-0,bn-False_2018-02-18_23-58-43tyy2_nxq/error_2018-02-19_23-25-19.txt [pid=23386], 263 s, 142300 ts
```

The log makes it clear it's from a bad s3 sync killing the whole job; this and other safe s3 exceptions should probably be ignored rather than kill the run. Final exception was `socket.timeout: The read operation timed out`

**Comment by ericl** [comment]
What's the log? I don't see how the s3 sync could kill the job since it's launched as a subprocess -- perhaps something else went wrong?

**Comment by ericl** [comment]
Resolved in master.
