### ISSUE TITLE
Actors not scheduling when some placement groups cannot be placed

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#15801]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

When you try to create more placement groups than the available resources in the cluster, some of the placement groups are created, and others are pending. 

If you try to schedule actors on all the placement groups, you would expect some of the actors to be scheduled (because some of the placement groups are ready), but others to be pending. 

For some reason, none of the actors seem to be useable. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
See @simon-mo 's repro in the comment below https://github.com/ray-project/ray/issues/15801#issuecomment-842791609

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
I added a print to the tdqm loop and it works for me. Is it just a tqdm bug?
```
eric@eric-thinkpad-t490s:~/Desktop$ python -i x.py
2021-05-13 18:59:11,570	INFO worker.py:716 -- Connecting to existing Ray cluster at address: 192.168.5.121:6379
  0%|                                                                                                                                                                                | 0/32 [00:00<?, ?it/s]Got actor [ObjectRef(48b7ee15cf1ae472a616461b1b5b70fcba01005e0100000001000000)]
Got actor [ObjectRef(d3ab1aaf09c00ee8b76ec5549180e249e8b534370100000001000000)]
Got actor [ObjectRef(b9679322487eb9c374d62dd2d30b25e1258157660100000001000000)]
Got actor [ObjectRef(a12253d7c747501cba581878e56a86e8ab7ebaab0100000001000000)]
Got actor [ObjectRef(9d78bd90898368cad0c1af04fc555a4b864ee0e10100000001000000)]
Got actor [ObjectRef(fc8204747604c8cc94405b81834969814414a3b80100000001000000)]
Got actor [ObjectRef(931690d20f999d2fe5720485ae19e2b957cf531f0100000001000000)]
Got actor [ObjectRef(36e14f5d7a18682ea05d2d93918911bd4076589a0100000001000000)]
```

**Comment by simon-mo** [comment]
@ericl @wuisawesome I think I got a local repro.

1. `ray start --head --num-cpus 2`
2. Python run
```python
import ray

ray.init(address="auto")

@ray.remote
class A:
	def ready(self):pass

pgs = [ray.util.placement_group([{"CPU": 1}]) for _ in range(1008)]
actors = [A.options(placement_group=pg).remote() for pg in pgs]
refs = [actor.ready.remote() for actor in actors]

while True:
	ready, not_ready = ray.wait(refs, num_returns=len(refs), timeout=5)
	print(len(ready), len(not_ready))
	if len(not_ready) == 0:
		break
```
3. In bash, run
```
while true;
do
  ray start --address=auto --num-cpus=1
  sleep 30
done
```

Observe that while the new worker nodes start locally in the bash script, the actors were not scheduled as the "ready" are not ready, it prints
```
python app.py
2021-05-17 20:06:04,335	INFO worker.py:716 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
2 1006
...
```

**Comment by ericl** [comment]
Can you also reproduce this with an real cluster (just checking that it isn't some weird local-node issue).

**Comment by simon-mo** [comment]
Yeah this is actually an issue with real cluster originally.

**Comment by simon-mo** [comment]
Update, in the real cluster with the same script, when there are 374 CPUS adn 183 worker nodes, only 1 actor is ready out side of the head node.
