### ISSUE TITLE
[serve] Improve `Deployment` docstring and add attributes to check current settings

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15822]
Currently the decorator docstring is good but not the one for the resulting `Deployment` type.

Should also be able to do `Deployment.num_replicas` to check current setting and so on. We should document these in the docstring.

**Comment by edoakes** [comment]
@simjay based on our conversation on the other thread -- want to take it? :)

**Comment by simjay** [comment]
@edoakes Sure :) A few questions first,

1. You are talking about the docstring on `class Deployment` itself correct?
2. For checking current setting of `Deployment.num_replicas`, it will be a pretty similar types of task with `prev_version` checking, would it? I guess I wanna ask what kinds of aspects do you wanna check with num_replicas?
3. Could you elaborate a bit more on what you meant by `add attributes to check current settings`?

**Comment by edoakes** [comment]
1. Yep the `Deployment class`.

For 2 and 3, I just mean that users should be able to dynamically get the current settings for a deployment. For example, if they wanted to just add one replica, they could do:

```python
D = serve.get_deployment("D")
D.options(num_replicas=d.num_replicas+1).deploy()
```

I don't mean that Serve itself should do any checking, just exposing these attributes so users can use them!

**Comment by edoakes** [comment]
@simjay I made a quick PR for this because I want to make sure it gets in before our 1.4 branch cut (happening tomorrow)

**Comment by simjay** [comment]
Sorry for the late reply. Will take a look at this once my testing troubles are gone!
