### ISSUE TITLE
[rllib]Why the Hierarchical training uses new lower-level agents for each higher-level action?

### ISSUE THREAD

**Issue by imxuemei** [ray-project/ray#15831]
I have tried the example of Hierarchical training in https://docs.ray.io/en/master/rllib-env.html#hierarchical-environments. However, I'm a little confused about that "Each higher-level action creates a new lower-level agent instance with a new id." 
I think there is only one low-level policy here, and it is trained whenever the hierarchical env switches to the low-level state. The observations from different low-level agents are taken as sample batches which are used to compute policy gradient. Then, why each lower-level agent instance is taken as a new agent with a new id?

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by mvindiola1** [comment]
Hi @imxuemei,

The place to look is in the environment here: https://github.com/ray-project/ray/blob/master/rllib/examples/env/windy_maze_env.py

The way this works is there are two agents a high level agent (l1)  and a low level agent (l2). In this environment the l1 and l2 agents interleave steps.

L1 .    .     .    .    L1
.    L2 L2 L2 L2 .

The way this environment transitions between them is by indicating that the L2 agent is done in the environment. Once an agent is done it cannot be undone in the same episode so the environment needs to spawn a new L2 agent with a different ID. 

That might look like this. 
L1 .    .     .    .  L1 . . . . L1
.    L2-0 L2-0 L2-0 L2-0 . L2-1 L2-1 L2-1 L2-1 .

**Comment by imxuemei** [comment]
@mvindiola1 , thanks very much. I got it.
