### ISSUE TITLE
[client] Can't redirect output when using ray.util.connect

### ISSUE THREAD

**Issue by al-rigazzi** [ray-project/ray#15843]
### What is the problem?
When using `ray.util.connect()` to start a driver script, it is impossible to mimic the `log_to_driver` functionalities offered by `ray.init()`. Therefore, if I start a ray cluster using the cli on each node, and then use `ray.util.connect`, the process is overloaded with messages from all workers.
*Ray version and other system information (Python version, TensorFlow version, OS):*
- Ray 1.3.0
- Python 3.7/3.8
- RHEL
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
If you first setup the cluster as defined, then you can run:
```
from ray import tune
import ray.util
import numpy as np

ray.util.connect("HEAD_ADDRESS:10001")

tune.run(
    "PPO",
    stop={"episode_reward_max": 200},
    config={
        "framework": "torch",
        "env": "CartPole-v0",
        "num_gpus": 0,
        "lr": tune.grid_search(np.linspace (0.001, 0.01, 100).tolist()),
        "log_level": "ERROR",
        "num_cpus_per_worker": 1,
    },
    verbose=0,
)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
IMO this is a Ray core issue. Since `ray start --no-redirect-worker-output` is deprecated, functionality has been moved to `log_to_driver` in `ray.init()`. We will need something similar for `ray.connect()`. 

cc @wuisawesome are you the right person to tag for this?

**Comment by wuisawesome** [comment]
If I understand correctly, this should just require adding a log to driver flag to ray client right?

**Comment by krfricke** [comment]
Yes!

**Comment by krfricke** [comment]
@wuisawesome is there any progress/update on this? Should we create a separate issue to track this or will this do?

Can I assign this to you?

**Comment by AmeerHajAli** [comment]
tracked in #17697. Please reopen if I misunderstood.
