### ISSUE TITLE
[rllib/tune] Unnecessary log from trainer when using tune

### ISSUE THREAD

**Issue by al-rigazzi** [ray-project/ray#15844]
### What is the problem?
The following messages are issued when setting log level to `WARN` or `ERROR` to a trainable example, when this is run from tune:
```
(pid=34577) 2021-05-17 11:13:46,504     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34564) 2021-05-17 11:13:46,614     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34568) 2021-05-17 11:13:46,613     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34579) 2021-05-17 11:13:46,603     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34562) 2021-05-17 11:13:46,664     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34559) 2021-05-17 11:13:46,665     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34565) 2021-05-17 11:13:46,675     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34561) 2021-05-17 11:13:46,637     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(pid=34566) 2021-05-17 11:13:46,701     INFO trainer.py:696 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[...]
```
This defeats the purpose of setting `log_level` to a high value and clutters the worker output, as this message is shown for every trial. In other words, if I manually set the log level to a high value, then I am responsible for the lack of output and I should not be warned. If it is really requested that this message is shown, then it should be issued once per `tune.run` call, not for every trial.
*Ray version and other system information (Python version, TensorFlow version, OS):*
- Ray 1.3.0
- Python 3.7/3.8
- RHEL
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
from ray import tune
import ray.util
import numpy as np

ray.util.connect("HEAD_ADDRESS:10001")

tune.run(
    "PPO",
    stop={"episode_reward_max": 200},
    config={
        "framework": "torch",
        "env": "CartPole-v0",
        "num_gpus": 0,
        "lr": tune.grid_search(np.linspace (0.001, 0.01, 100).tolist()),
        "log_level": "ERROR",
        "num_cpus_per_worker": 1,
    },
    verbose=0,
)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
cc @sven1977 this code is in the rllib base `Trainer` class. Do we need this output at all? Would it be enough to print it when the `rrlib` cli command is used?
