### ISSUE TITLE
[Serve] test_deploy time doubled after 

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#15870]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

`test_deploy.py` used to take around ~300s. But after commit cd32a92edc275be82074b8426a24121bcf6bab0f, the test time doubled. You can verify it on the local machine. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
cc @edoakes

**Comment by edoakes** [comment]
@simon-mo why did you close this? Was it not actually an issue?

**Comment by simon-mo** [comment]
it turns out somehow my PR https://github.com/ray-project/ray/pull/15865 timing. out but not on master, therefore closing. https://buildkite.com/ray-project/ray-builders-pr/builds/5451#2df15f8f-414f-4615-95e7-6ead1e782d02/6-11133
