### ISSUE TITLE
RLlib plot errros

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [ray-project/ray#15874]
Hi! When I try to plot "policy_reward_mean", The following error occurred:
![image](https://user-images.githubusercontent.com/68255669/118631955-fa2e0300-b79d-11eb-9811-7c38b5b1a337.png)
Could you please tell me how to solve it?Thanks!

**Comment by mvindiola1** [comment]
Hi @Yuanzhuo-Liu,

ExperimentAnalysis uses the state.json file not results.json. Try with that file instead.

**Comment by Yuanzhuo-Liu** [comment]
Hi @mvindiola1 .
Thanks, here's another mistake. Sorry, I was too stupid.
![image](https://user-images.githubusercontent.com/68255669/118774377-c3b2bf80-b853-11eb-8b05-8a5992cc0fa9.png)

**Comment by Yuanzhuo-Liu** [comment]
My state.json is follow:
![image](https://user-images.githubusercontent.com/68255669/118908654-ccf16a00-b8ef-11eb-9489-3c5421ce3044.png)

**Comment by mvindiola1** [comment]
@Yuanzhuo-Liu don't be so hard on your self. There is no error there. That is a warning but it exited cleanly.

**Comment by richardliaw** [comment]
Hope things look good @Yuanzhuo-Liu  -- thanks for the help, @mvindiola1 !
