### ISSUE TITLE
[dashboard] Dashboard crashes ray in local cluster setup

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#15882]
This precedes https://github.com/ray-project/ray/issues/11940.

I've recently upgraded to Ray 1.3.0 and getting the following on local cluster setup:

```
(raylet, ip=172.17.0.3) Traceback (most recent call last):
(raylet, ip=172.17.0.3)   File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server
(raylet, ip=172.17.0.3)     sock.bind(sa)
(raylet, ip=172.17.0.3) OSError: [Errno 99] Cannot assign requested address
(raylet, ip=172.17.0.3) 
(raylet, ip=172.17.0.3) During handling of the above exception, another exception occurred:
(raylet, ip=172.17.0.3) 
(raylet, ip=172.17.0.3) Traceback (most recent call last):
(raylet, ip=172.17.0.3)   File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/agent.py", line 338, in <module>
(raylet, ip=172.17.0.3)     raise e
(raylet, ip=172.17.0.3)   File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/agent.py", line 326, in <module>
(raylet, ip=172.17.0.3)     loop.run_until_complete(agent.run())
(raylet, ip=172.17.0.3)   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
(raylet, ip=172.17.0.3)     return future.result()
(raylet, ip=172.17.0.3)   File "/usr/local/lib/python3.6/dist-packages/ray/new_dashboard/agent.py", line 161, in run
(raylet, ip=172.17.0.3)     await site.start()
(raylet, ip=172.17.0.3)   File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 128, in start
(raylet, ip=172.17.0.3)     reuse_port=self._reuse_port,
(raylet, ip=172.17.0.3)   File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
(raylet, ip=172.17.0.3)     % (sa, err.strerror.lower()))
(raylet, ip=172.17.0.3) OSError: [Errno 99] error while attempting to bind on address ('10.120.59.27', 0): cannot assign requested address
```

**Comment by roireshef** [comment]
@rkooo567 @mfitton

**Comment by roireshef** [comment]
My setup is:
**on head node**
```
ray start --block --head \
--port=6379 \
--redis-password=5241590000000000 \
--node-ip-address=10.120.59.22 \
--gcs-server-port=6005 \
--dashboard-port=6006 \
--node-manager-port=6007 \
--object-manager-port=6008 \
--redis-shard-ports=6400,6401,6402 \
--min-worker-port=6100 --max-worker-port=6299
```

**on worker node(s)**
```
ray start --block \
--address=10.120.59.22:6379 \
--redis-password=5241590000000000 \
--node-ip-address=10.120.59.27 \
--node-manager-port=6007 \
--object-manager-port=6008 \
--min-worker-port=6100 --max-worker-port=6299 \
--num-gpus=0 
```

And then running in the head node, inside python:
`ray.init(address='10.120.59.22:6379', _redis_password='5241590000000000')`

Now, it doesn't matter if I enter include_dashboard=false or --dashboard-port=??? in any of those commands. It keeps failing!

**Comment by edoakes** [comment]
@roireshef as an experiment, what happens if you don't specify the `node-ip-address` manually in the workers? It looks like the ip address you're providing is somehow not able to be bound to for a TCP port

**Comment by roireshef** [comment]
@edoakes it happens even if I run with head only (no worker nodes). Does it still make sense to try? Should I try removing this flag in the head node?

Is there any way to disable the dashboard in the meantime while we are debugging so I can at least run my trials without it? The include-dashboard flag is ignored.

**Comment by roireshef** [comment]
@edoakes I'm into different issues when I remove `--node-ip-address` since I'm running in docker containers and the way you resolve self ip will not recover the physical machine's ip, but rather docker container ip. So for instance, running 
```
ray.services.get_node_ip_address()
```
will return the same ip for both machines I try to handshake (which is their docker container internal ip). 
It was concluded before (in another ticket) that providing `--node-ip-address` in this setup is essential.

Then, we're back to square one. 

Is there a way to disable the dashboard?
