### ISSUE TITLE
[RLLib] Typo/Bug in Marwil TF policy affecting Advantage update

### ISSUE THREAD

**Issue by felipeeeantunes** [ray-project/ray#15887]
I was taking a look at Marwil TF loss and I guess I found a typo /bug (with a 100x effect on the loss update value): the value [here](https://github.com/ray-project/ray/blob/master/rllib/agents/marwil/marwil_tf_policy.py#L114) should be 10^(-8) instead of 10^(-6).

**Comment by mvindiola1** [comment]
Hi @felipeeeantunes.

Good eye. I noticed it too. was planning on fixing it while fixing this #15800.

**Comment by sven1977** [comment]
Great catch @felipeeeantunes and @mvindiola1 !
Will provide a fix.
