### ISSUE TITLE
[serve] Automatic load-based autoscaling for deployments

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#15888]
A number of users have asked about this; if you have a use case, please comment here so we can track and prioritize this feature!

**Comment by mihajenko** [comment]
Our use case: we wish to auto-scale our FastAPI Serve backends on a Kubernetes cluster (using the RayCluster CRD). Serve works through backends, which can be scaled by configuring the `num_replicas` parameter. It can even be reconfigured on the fly. As suggested to me by @edoakes on Slack:

> Note that you could write a simple monitor process that checks the load on teh cluster and resizes the number of replicas accordingly.

True. However, lower-level ray APIs are already consuming cluster resources in a greedy fashion. That is, many `ray.remote` calls will spawn additional Pods if a k8s cluster still has the resources, and within configured `maxWorker` limits. Serve, on the other hand, requires a fixed number of backend replicas, for some reason. For that reason I believe backend replicas should follow the same greedy approach, unless explicitly limited.

**Comment by TanjaBayer** [comment]
I think that would be really great feature. But I think if you have a larger micro service architecture, you will encounter different loads. Right now you need to handle that by an additional script, which makes the usage of ray serve more static and less serverless.
