### ISSUE TITLE
Object store does not evict objects as expected

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#15886]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Ray master version

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import numpy as np
import ray

OBJECT_STORE_MB = 100
OBJECT_SIZE_MB = 50
OBJECT_COUNT = 10
BYTES_PER_MB = 1024 * 1024

ray.init(object_store_memory=OBJECT_STORE_MB * BYTES_PER_MB)

refs = [
    ray.put(np.ones(OBJECT_SIZE_MB * BYTES_PER_MB, dtype=np.uint8))
    for _ in range(OBJECT_COUNT)
]
print("ray.put OK")
for i, ref in enumerate(refs):
    ret = ray.get(ref)
    print(f"ray.get({i}) OK, size={ret.size}")
```

The object store has 100MB space. We first write 10* 50MB objects to it. This will cause the first 8 or 9 objects to spill to disk.

We then call `ray.get` on each of the objects. They should be brought back one by one.

Reality: `ray.exceptions.ObjectStoreFullError` and the program hangs.

```
ray.put OK
ray.get(0) OK, size=52428800
2021-05-18 11:20:52,880 WARNING worker.py:1104 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 711, in ray._raylet.restore_spilled_objects_handler
    with ray.worker._changeproctitle(
  File "python/ray/_raylet.pyx", line 714, in ray._raylet.restore_spilled_objects_handler
    bytes_restored = external_storage.restore_spilled_objects(
  File "/home/ubuntu/raydev/ray/python/ray/external_storage.py", line 534, in restore_spilled_objects
    return _external_storage.restore_spilled_objects(object_refs,
  File "/home/ubuntu/raydev/ray/python/ray/external_storage.py", line 306, in restore_spilled_objects
    self._put_object_to_store(metadata, buf_len, f, object_ref,
  File "/home/ubuntu/raydev/ray/python/ray/external_storage.py", line 101, in _put_object_to_store
    worker.core_worker.put_file_like_object(metadata, data_size, file_like,
  File "python/ray/_raylet.pyx", line 1068, in ray._raylet.CoreWorker.put_file_like_object
    object_already_exists = self._create_put_buffer(
  File "python/ray/_raylet.pyx", line 1034, in ray._raylet.CoreWorker._create_put_buffer
    check_status(CCoreWorkerProcess.GetCoreWorker().CreateExisting(
  File "python/ray/_raylet.pyx", line 152, in ray._raylet.check_status
    raise ObjectStoreFullError(message)
ray.exceptions.ObjectStoreFullError: Failed to put object ffffffffffffffffffffffffffffffffffffffff0100000002000000 in object store because it is full. Object size is 52429047 bytes.
The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.
An unexpected internal error occurred while the IO worker was restoring spilled objects.
```

It is also worth noting that when the object sizes are 49MB (i.e. the object store can fit 2 objects), the program works just fine. So I'm wondering what's causing the difference. When we call `ray.get` on the 2nd object, the 1st object should already be out of Python scope, right?

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

cc @stephanie-wang @rkooo567

**Comment by rkooo567** [comment]
I think it is just that the previous object is pinned due to ray.get, so we cannot put the new object at all (since the first object is not spillable)?

**Comment by franklsf95** [comment]
@rkooo567 but why is it the case that when the object store is large enough to hold 2 objects, then they can all get spilled?

**Comment by rkooo567** [comment]
I think when we restore, only one of objects are pinned, and the other is not, so we always evict the un-pinned object and restore the new object to ray.get. But when it is 50MB, it can probably fit only one object, and we cannot evict the pinned object due to ray.get. If you create 50MB objects, is it possible to have 2 of them in the object store?

**Comment by franklsf95** [comment]
I think you're right that when the object size is 50MB it can only fit one object. 

OK this is interesting: if I add a `del ret` line before the loop ends, then the 50MB version can also work. When the 2nd `ray.get` is called, the first `ret` is still in scope, and only goes out of scope _after_ the `ray.get` call. Hence the deadlock.

I think this is expected behavior then. Closing this.
