### ISSUE TITLE
[RFC] Support task and actor placement on "head node"

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15930]
# Proposal
Provide a mechanism to enforce placement of a particular task or actor on the head node of a Ray cluster

# Motivation
When using libraries like Tune with Ray Client, the main driver for the library (`tune.run`, `xgboost_ray.train`) needs to be placed on a particular node with the following properties:
* The node cannot be pre-emptible
* The node can be easily accessed by the user (via `ray attach`, `ray rsync`) to support downloading of results/checkpoints

Placement on the head node of the Ray cluster (the node that calls `ray start --head`) satisfies both of these properties.

# Proposed Implementation
Autoscaler will automatically add a `{"HeadNode": 1}` custom resource to the head node.

The user can then specify `@ray.remote(resources={'HeadNode': 0.01})` requirement for the task/actor.

We could also provide a more convenient `@ray.remote(head_node=True)` API

**Comment by amogkam** [comment]
@AmeerHajAli @richardliaw @ericl

**Comment by ericl** [comment]
Another possibility is to use the existing `node:<ip>` magic resources, and ask Ray for the head node IP address (same as redis address)? This might already be possible with existing APIs.

**Comment by amogkam** [comment]
Can you get the head node IP address programmatically via Ray Client?

**Comment by ericl** [comment]
I'm not aware of a current way, though you can try to infer from `ray.nodes()` output perhaps. We might have to add a new API or add it to runtime context.

**Comment by rkooo567** [comment]
Didn’t we have resources like head: 1 to the head node in the past? Did we remove it?

**Comment by richardliaw** [comment]
@robertnishihara's comment: 

We should be going in the opposite direction. In the near-medium term, the head node should disappear. It's inconsistent with serverless, and it's inconsistent with the Ray client, so we should avoid doing anything that bakes the concept further in than it already is.
On the other hand, something like `resources={'non-preemptible': 1}` would be acceptable.

**Comment by simon-mo** [comment]
As a datapoint, for Ray Serve, we assume the where-ever user starts their Serve deploy is the head node. So a simple `ray.get_runtime_context().node_id` can help us pin the head node. This `node_id` works with Ray client, where the client server is ran.
https://github.com/ray-project/ray/blob/dde7cbd2885765a9fc61b05daca4f6f9973aed10/python/ray/serve/api.py#L663-L666

def get_current_node_resource_key() -> str:
    """Get the Ray resource key for current node.

    It can be used for actor placement.
    """
    current_node_id = ray.get_runtime_context().node_id.hex()
    for node in ray.nodes():
        if node["NodeID"] == current_node_id:
            # Found the node.
            for key in node["Resources"].keys():
                if key.startswith("node:"):
                    return key
    else:
        raise ValueError("Cannot found the node dictionary for current node.")

**Comment by wuisawesome** [comment]
I'd argue that a scheduling hint `foo.options(force_local_node=True).remote()` would be a better equivalent solution. It has the properties:
* Allows fatesharing with nodes in general
* Doesn't place emphasis on the head node
* Has other uses for locality scheduling (when you can't use a placement group).

**Comment by amogkam** [comment]
@wuisawesome I like your proposal as well assuming it'll also work with Ray Client- the local node would be the node that is running the client server (which currently is the head node) and not the laptop.

**Comment by amogkam** [comment]
@AmeerHajAli would it be possible to follow @ericl's suggestion and add a new API to get the IP address that the ray client server is running on?

**Comment by simon-mo** [comment]
@amogkam you can already do that `ray.get_runtime_context().node_id`. It returns a copy of the information from the client server, which runs on headnode.

**Comment by amogkam** [comment]
Oh I see, thanks @simon-mo. I will try that out.

I agree that long term we no longer want a head node concept, but in the meantime we need something that works currently.

**Comment by amogkam** [comment]
@GoingMyWay yes- the recommended way to do this now is via the `SchedulingStrategy` API https://docs.ray.io/en/latest/ray-core/actors/scheduling.html#scheduling-strategy.

**Comment by GoingMyWay** [comment]
> @GoingMyWay yes- the recommended way to do this now is via the `SchedulingStrategy` API https://docs.ray.io/en/latest/ray-core/actors/scheduling.html#scheduling-strategy.

@amogkam, thanks. For Ray 1.13, we can following the following example:

```python
@ray.remote
class Actor:
    pass

# "DEFAULT" scheduling strategy is used (packed onto nodes until reaching a threshold and then spread).
a1 = Actor.remote()

# Zero-CPU (and no other resources) actors are randomly assigned to nodes.
a2 = Actor.options(num_cpus=0).remote()

# Only run the actor on the local node.
a3 = Actor.options(
    scheduling_strategy=NodeAffinitySchedulingStrategy(
        node_id = ray.get_runtime_context().node_id,
        soft = False,
    )
).remote()
```

For Ray 1.11, what method can I use to achieve it?
