### ISSUE TITLE
`placement_group=None` is not working when trying not to use the same placement group from children actors.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#15944]
## Repro
- start placement group with 4 bundles
- start multiple actors inside placement group, all actors should consume 1 full bundle
- from one of the actors, start a named actor with placement_group=None

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
This is working if I specify placement_group=False. Maybe we should just document it.

**Comment by ericl** [comment]
Seems like a trivial fix, can you make a PR?

**Comment by rkooo567** [comment]
It looks like placement_group=None is not the right semantic here because that's the default value (so it is hard to make it work).

Any objection of using `options(placement_group=PlacementGroup.empty())` for the same purpose? Or `options(placement_group=False)`.

**Comment by ericl** [comment]
Why not change the default to False or some other sentinel value (e.g., -1)? Then, None will work as expected as an override.

**Comment by rkooo567** [comment]
Sounds good to me.
