### ISSUE TITLE
Show actual error from worker logs instead of just saying "please check worker logs" on failure

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#15962]
### Describe your feature request

Currently, when a worker fails, `ray.get` may raise:

- `ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.`
- `ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task. Check python-core-worker-*.log files for more information.`.

When we run a large application with hundreds or thousands of tasks or actors, it is hard to quickly determine which remote task or actor and actor task has failed.

As a comparison, when a remote task or an actor task raises an application error, we see this:

```
ray.exceptions.RayTaskError: ray::foo() (pid=27990, ip=11.124.24.106)
  File "python/ray/_raylet.pyx", line 503, in ray._raylet.execute_task
    with ray.worker._changeproctitle(title, next_title):
  File "python/ray/_raylet.pyx", line 513, in ray._raylet.execute_task
    outputs = function_executor(*args, **kwargs)
  File "<string>", line 10, in foo
Exception: test message
```

The `RayTaskError` message is so much helpful because it includes the function name, PID, and IP address.

We should print the below information in `WorkerCrashedError` and `RayActorError`:

- Function name, PID, and IP address (as they are already included in RayTaskError)
- Actor name (for named actors)
- Actor creation task function name (Maybe we don't need this because the actor task function name implies this?)

I'm not sure whether we should print actor ID and task ID, though.

**Comment by kfstorm** [comment]
cc @rkooo567

**Comment by ericl** [comment]
@kfstorm are you actively working on this?

**Comment by kfstorm** [comment]
@ericl No. And I'm on vocation this week. Sorry for the late reply.

**Comment by ericl** [comment]
@rkooo567 we should just include the last few lines of the worker logs (e.g., last few KB), which will show the underlying error here.

**Comment by ericl** [comment]
Actually, I think this would be fixed by https://github.com/ray-project/ray/issues/12893, so closing this and bumping the priority of that one.
