### ISSUE TITLE
[GCS] Too many duplicate logs in GCS.

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#15971]
### What is the problem?
I'm trying to solve this issue #15801 , but I found that there are so many repeated logs in the gcs_server.out. 
Is this expected? 

![image](https://user-images.githubusercontent.com/17047853/119144813-9c3e3b80-ba7b-11eb-9bbb-541971ff978e.png)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by clay4444** [comment]
@wuisawesome

**Comment by wuisawesome** [comment]
Yes this is expected, but I didn't realize it would make the debug logs so unreadable. I'm ok with removing that print statement.
