### ISSUE TITLE
Ray tune uses infinite disk space

### ISSUE THREAD

**Issue by francis2tm** [ray-project/ray#15982]
python 3.6.9
pytorch 1.8.1+cu102
Ubuntu 18.04

I'm running a ray tune script based on https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html .
In the last few days everything worked flawlessly, but since yersterday, 2 things have changed, I think it's because I updated ray's version:
1) Before, when the hyperparameter search was starting, only the running trial and completed trials appeared. Now, they all appear (most as pending, like so:
`` +---------------------+----------+-------+--------+----------+--------+----------+--------+----------+--------+--------+--------+--------------+-----------+----------+-------------+
| Trial name          | status   | loc   |   1_cv |   2_cvmp |   3_cv |   4_cvmp |   5_cv |   6_cvmp |   7_cv |   8_cv |   9_fc |   batch_size | dataset   |   epochs |          lr |
|---------------------+----------+-------+--------+----------+--------+----------+--------+----------+--------+--------+--------+--------------+-----------+----------+-------------|
| DEFAULT_b42bd_00000 | RUNNING  |       |      8 |        4 |     32 |        1 |     64 |      128 |      8 |     32 |      5 |          333 | non-avg   |        3 | 0.000485154 |
| DEFAULT_b42bd_00001 | PENDING  |       |      8 |        4 |    128 |       16 |    128 |        4 |    128 |      8 |      5 |          333 | non-avg   |        5 | 0.0607565   |
| DEFAULT_b42bd_00002 | PENDING  |       |     16 |       32 |      8 |      128 |     16 |        4 |      2 |    128 |      5 |          333 | non-avg   |        5 | 0.0597711   |
| DEFAULT_b42bd_00003 | PENDING  |       |     32 |       32 |     32 |       32 |     64 |        4 |     32 |     64 |      5 |          333 | non-avg   |        5 | 0.0045665   |
| DEFAULT_b42bd_00004 | PENDING  |       |     64 |        4 |     16 |        2 |      2 |       64 |     32 |     16 |      5 |          333 | avg       |        3 | 0.000119926 |
| DEFAULT_b42bd_00005 | PENDING  |       |     32 |       64 |      1 |        8 |      8 |      128 |    128 |     16 |      5 |          333 | non-avg   |        5 | 0.00046917  |
| DEFAULT_b42bd_00006 | PENDING  |       |     64 |        8 |      2 |      128 |      8 |       16 |     64 |    128 |      5 |          333 | avg       |        3 | 0.0316614   |
| DEFAULT_b42bd_00007 | PENDING  |       |     32 |       64 |     32 |       64 |     64 |        2 |      2 |     16 |      5 |          333 | non-avg   |        7 | 0.00549312  |
| DEFAULT_b42bd_00008 | PENDING  |       |     16 |       16 |     64 |        1 |      2 |       16 |      1 |      4 |      5 |          333 | avg       |        7 | 0.00319996  |
| DEFAULT_b42bd_00009 | PENDING  |       |     64 |        1 |    128 |        4 |     16 |        4 |     16 |     16 |      5 |          333 | avg       |        7 | 0.0354274   |
| DEFAULT_b42bd_00010 | PENDING  |       |     32 |        1 |     32 |        1 |      1 |        1 |      4 |      8 |      5 |          333 | non-avg   |        7 | 0.00144669  |
| DEFAULT_b42bd_00011 | PENDING  |       |      8 |        8 |      1 |        1 |     64 |       16 |     64 |      8 |      5 |          333 | non-avg   |        3 | 0.06252     |
| DEFAULT_b42bd_00012 | PENDING  |       |     16 |        1 |      1 |       32 |      1 |        1 |      2 |    128 |      5 |          333 | non-avg   |        5 | 0.000461432 |
| DEFAULT_b42bd_00013 | PENDING  |       |     16 |       32 |     32 |       32 |     64 |        1 |    128 |     16 |      5 |          333 | avg       |        5 | 0.0491384   |
| DEFAULT_b42bd_00014 | PENDING  |       |     32 |       16 |     16 |        8 |    128 |        8 |     64 |      4 |      5 |          333 | avg       |        7 | 0.000960133 |
| DEFAULT_b42bd_00015 | PENDING  |       |     32 |        2 |      4 |        8 |      2 |        4 |      8 |      8 |      5 |          333 | avg       |        3 | 0.0567406   |
| DEFAULT_b42bd_00016 | PENDING  |       |      8 |        8 |     16 |        8 |      2 |        8 |     16 |     32 |      5 |          333 | non-avg   |        3 | 0.000452181 |
| DEFAULT_b42bd_00017 | PENDING  |       |     64 |        4 |      8 |      128 |     16 |       16 |     32 |    128 |      5 |          333 | avg       |        3 | 0.000422259 |
| DEFAULT_b42bd_00018 | PENDING  |       |     16 |        2 |      4 |       32 |      2 |      128 |      2 |     32 |      5 |          333 | avg       |        3 | 0.0624519   |
| DEFAULT_b42bd_00019 | PENDING  |       |     64 |        1 |     16 |        2 |      2 |       64 |    128 |      2 |      5 |          333 | avg       |        5 | 0.0024542   |
+---------------------+----------+-------+--------+----------+--------+----------+--------+----------+--------+--------+--------+--------------+-----------+----------+-------------+
... 930 more trials not shown (930 PENDING)

I don't mind the above happening, but I just mentioned to help in finding out what's the bug.

2) Now, after ~100 trials, my 28GiB free disk space are gone in a matter of ~1h. I don't know why, but now ray uses a lot of diskspace? He stores files in /tmp folder. It seems that in each trial, he stores stuff there which he never cleans, gradually building up a lot of disk space.

Any information regarding this last issue? 

Thanks in advance

**Comment by richardliaw** [comment]
@francis2tm this issue is reported here with a workaround: https://github.com/ray-project/ray/issues/15695

Let me know if it works!

**Comment by francis2tm** [comment]
It worked, thanks!
