### ISSUE TITLE
ray[tune] requirements

### ISSUE THREAD

**Issue by CookiePPP** [ray-project/ray#16010]
### What is the problem?
Crash on line
https://github.com/ray-project/ray/blob/c624e89483f3512a73f74361acae93637e40810e/python/ray/tune/logger.py#L266
Running
```python
pip3 install -U ray ray[tune] ray[defaults]
```
should update tensorboardX to 1.9 or higher but does not.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.8
TensorFlow 2.3
Pop_os! 19.10
TensorboardX 1.8

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
!pip3 install -U ray
!pip3 install ray[tune]
!pip3 install ray[defaults]
from tensorboardX.summary import hparams
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

~~- [ ] I have verified my script runs in a clean environment and reproduces the issue.~~
~~- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).~~

**Comment by CookiePPP** [comment]
https://github.com/lanpa/tensorboardX/pull/470
`tensorboardX.summary.hparams` was added to tensorboardX in version 1.9

**Comment by krfricke** [comment]
cc @amogkam maybe we only have to bump some dependencies?

**Comment by amogkam** [comment]
@krfricke I think we just need to pin 1.9 as the minimum version for tensorboardX in setup.py. The dependencies in `requirements_tune.txt` shouldn't be affecting this.
