### ISSUE TITLE
[Core] object_store_memory leak after Ctrl-C of job

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16026]
### What is the problem?

After I stopped the driver due to https://github.com/ray-project/ray/issues/16025, I found out ray status prints object_store_memory > 0. It shouldn't happen because all the memory is supposed to be cleaned up. This can impact autoscaler potentially.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

- Run multi node shuffle 
```
python -m ray.experimental.shuffle --ray-address="localhost:6379" --num-partitions=1000 --partition-size=100e6
```
- Ctrl + C on the driver before it is done.
- Run `ray status`

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Is it just an issue with the job not being marked as dead? Maybe it takes a bit of time after am unexpected exit with Ctrl-C.

What if you wait longer? Or is the job cleaned up but objects still remain?

**Comment by rkooo567** [comment]
I can double check later, but based on my observation, other resources (e.g., CPU) are cleaned, but object store memory is not completely cleaned (and it stays the same after I waited a bit). If I run the next job, it doesn't seem to be affected, so it is probably just some of evictable objects are not evicted after the job is done. 

Let me see if I can create a repro later.

**Comment by ericl** [comment]
I see, @stephanie-wang can you think of a reason why we might not be cleaning up some of these objects? Is it indeed possible the store is full of evictable objects only?

**Comment by rkooo567** [comment]
I did additional investigation. The issue was the "pending_spilling_objects" are processed pretty late when all the owners are dead, and objects are pinned by them until the URL is updated to the owner. After I waited for some time, it was automatically cleaned up. It is still a little mysterious why it would take so long time to be cleaned (it took a couple minutes).

**Comment by rkooo567** [comment]
Maybe it took a long time to process thousands of requests replied from the owner, but IIUC, it should be done within a couple seconds.. Maybe need more investigation.
