### ISSUE TITLE
[Scheduler] Hybrid scheduling policy doesn't load balance tasks when object store memory is > 50%

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16027]
### What is the problem?

cc @wuisawesome 

When I ran the shuffle test in the multi node cluster (4 nodes), it looks like the head node object store is utilized 100% before other nodes are utlilized.

```
python -m ray.experimental.shuffle --ray-address="localhost:6379" --num-partitions=1000 --partition-size=100e6
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Can you provide more details into the issue? It is difficult to tell the expected behavior based on the description.

**Comment by rkooo567** [comment]
Based on my understanding, tasks should be load balanced when the object store utilization reaches to around 50% to avoid unnecessary object spilling, but I found the head node is utilized 100% before other node object stores are even used (which means the policy is not working as expected).

**Comment by ericl** [comment]
I'm not totally surprised about this since there is some delay before the load balancing occurs. If the node is pretty small it might just fill up before this happens. Anyways, this issue is not detailed enough to point to a concrete problem, we should investigate further before prioritizing it.

**Comment by rkooo567** [comment]
Yeah I agree with `we should investigate further before prioritizing it.`. I will have further investigation while I am helping Jenna.

**Comment by rkooo567** [comment]
The problem was that when the tasks were scheduled for the first time, all nodes have object store memory usage == 0, which leads to schedule all num_cpus/2 memory intensive tasks into nodes. Issue could be resolved by using load balancing policy.
