### ISSUE TITLE
[Shuffle] RPC intensive workload blocks the raylet main thread

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16039]
### What is the problem?

When running busy applications, it seems like `ray memory --stats-only` times out with the below error message;

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1621898029.827254768","description":"Error received from peer ipv4:172.31.62.0:41753","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
```

It happens when I ran memory intensive workload and all of tasks are scheduled on a single node. Since copying the large memory uses good amount of CPU, this seems to be expected, but it is weird this blocks the main thread which makes ray memory extremely slow. We should figure out what code causes and offload it to other threads. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run `dask_on_ray_large_scale_test` without any scheduling configuration (50% utilization score) + 5 nodes cluster. 

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Can you comment on why it could be timing out? Isnt stats only a super lightweight call that's just reading some counters from memory?

**Comment by rkooo567** [comment]
That's why I added need-repro-script. It is suppose to be super lightweight, and I could see it runs for a short time, but it times out when I ran the dask on ray workload (I tried in multiple different raylets, and it were the same). My guess is when one raylet collects stats from other raylets, there's something wrong.

**Comment by rkooo567** [comment]
It looks like the problem was this; 

- When I ran Jenna's workload for the first time with her original script, the memory usage was too high for our object store memory (imagine she uses 200+GB object store memory whereas my experiment uses only 32GB).
- This causes some of raylets extremely busy (which causes long queuing time, 100+s). Note that the root cause of long hanging wasn't visible to the asio stats 
- ray memory --stats-only basically pings every raylet, and it waits until every node responds. The problem is those really busy raylets didn't respond accordingly. 

So there is a couple action items..

1. Figure out what made raylet busy, and see if we can make that part better (we'd like avoid having any logic that blocks raylet for a long time in any circumstance).
2. Make ray memory to timeout if raylets don't reply quick enough.

**Comment by rkooo567** [comment]
Updated the main description + I think we should figure out what's the root cause.

**Comment by ericl** [comment]
I believe the following recreates the main symptom:

`RAY_max_fused_object_count=2000 python -m ray.experimental.shuffle --num-partitions=200 --partition-size=10e6`

Note that if you reduce the RPC load by setting RAY_max_fused_object_count=10, or adding sleeps in the spill() function of external_storage.py, the problem goes away.

I'm not sure why this is causing the event loop to break though. I would have expected some kind of gRPC error. Unless we are breaking gRPC with too many requests (or some bug with our gRPC integration).

**Comment by ericl** [comment]
https://github.com/ray-project/ray/issues/16048 might be a proximate cause of this issue as well.

**Comment by ericl** [comment]
Closing since it's almost certainly a duplicate.
