### ISSUE TITLE
Restore requests should bypass object store

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16044]
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

cc @stephanie-wang 

Imagine there are number of pinned objects at each node. At the same time, if there are many object restoration requests from many nodes, it is possible that the restoration request goes through OOM (and it will be retried by object manager).

The problem here is that since we don't use admission control for the restoration requests, they could be executed unnecessarily, which can cause straggler problem (since the object creation is FIFO). See the below example.

```
object store memory: 10GB
pinned: 7GB
restoration requests: 1GB 1GB 2GB 2GB 4GB
Worst case: 4GB -> 2GB -> 2GB -> 1GB -> 1GB
In this case, every object behind would be blocked by the 4GB object creation request
Best case: 1GB -> 2GB -> 1GB -> 2GB -> 4GB
In this case, we can proceed everything much faster
```

There are two possible solutions; 
- Bypass the ray.put for pull requests
- Make admission control to take into account of restoration requests memory

TODO: Repro will be ready later.

**Comment by ericl** [comment]
I think we should be bypassing the object store for restore requests. We can be streaming the data directly from disk over the network, which would both be much lower CPU overhead and avoids this kind of memory thrashing issue.

**Comment by rkooo567** [comment]
(will be closed after the third PR)

**Comment by scv119** [comment]
^
