### ISSUE TITLE
Fractional resources <= 0.01 are not handled correctly in placement groups

### ISSUE THREAD

**Issue by benni-hepp** [ray-project/ray#16053]
### What is the problem?

Fractional resources <= 0.01 are not handled correctly in placement groups.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.3.0
Tensorflow: 1.15.0
PyTorch: 1.7.1
OS: Linux (in docker container)

### Reproduction (REQUIRED)
```
import ray
from ray.util.placement_group import placement_group
import sys

if __name__ == '__main__':
    ray.init(resources={'cpuworker': 1000})

    if sys.argv[1] == 'works':
        bundles = [{'cpuworker': 0.1} for _ in range(4)]
    elif sys.argv[1] == 'fails':
        bundles = [{'cpuworker': 0.01} for _ in range(4)]
    else:
        raise ValueError('sys.argv[1] needs to be either "works" or "fails"')

    pg = placement_group(
        bundles,
        strategy='SPREAD',
        lifetime='detached',
        name='remote_replay_buffer_placement_group')

    print(f'calling ready()')
    ray.get(pg.ready(), timeout=10)
    print(f'done calling ready()')
```

Running `python3 script.py works` gives:
```
calling ready()
done calling ready()
```

Running `python3 script.py fails` gives:
```
calling ready()
Traceback (most recent call last):
  File "script.py", line 23, in <module>
    ray.get(pg.ready(), timeout=10)
...
ray.exceptions.GetTimeoutError: Get timed out: some object(s) not ready.
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
@wuisawesome any guess why this happens?

**Comment by wuisawesome** [comment]
I wonder if it has something to do with the conversion from double (in protobuf) to fixedpoint in the scheduler. In theory we use a granularity of 1/10000

**Comment by clay4444** [comment]
hmm, It seems it has been fixed at some point, I can't reproduce this in the master branch.

**Comment by rkooo567** [comment]
That’s great!

**Comment by rkooo567** [comment]
Actually @clay4444 can you actally create a PR that adds this repro to unit tests?

**Comment by clay4444** [comment]
> Actually @clay4444 can you actally create a PR that adds this repro to unit tests?

Yeah, sure.
