### ISSUE TITLE
[RLlib] Restored DQNTrainer cannot solve the environment it was trained on.

### ISSUE THREAD

**Issue by pxc** [ray-project/ray#16065]
### What is the problem?

I'm trying to train a simple cartpole model using `ray.tune.run`, load a trainer from the final checkpoint and show that it works in the environment. However, the loaded trainer does not perform very well at all.

Ray version: 2.0.0.dev0 installed from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl

OS: Linux

PyTorch: 1.8.1+cpu

Python 3.6.9

This _might_ be the same issue as https://github.com/ray-project/ray/issues/15162

I thought it might be related to the issue fixed by @sven1977 in [this commit](https://github.com/ray-project/ray/pull/14838/files), but the fix is present in the latest master that I was using.

### Reproduction (REQUIRED)

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

```
import gym
import ray
from ray.rllib.agents.dqn import DQNTrainer

config = {
    "env": "CartPole-v0",
    "framework": "torch",
    "model": {
        "fcnet_hiddens": [64],
        "fcnet_activation": "linear",
    },
}

stop = {"episode_reward_mean": 195}

ray.shutdown()
ray.init(include_dashboard=False, ignore_reinit_error=True)

analysis = ray.tune.run("DQN", config=config, stop=stop, checkpoint_at_end=True)

# restore a trainer from the last checkpoint
checkpoint = analysis.get_last_checkpoint()
trainer = DQNTrainer(config=config)
trainer.restore(checkpoint)

env = gym.make("CartPole-v0")

observation = env.reset()
i = 0
done = False
while not done:
    action = trainer.compute_action(observation)
    observation, reward, done, info = env.step(action)
    i += 1

print("Loaded trainer survived for", i, "steps")
```

I would expect it to report something close to 200 steps, but it is much less than that.

If I change this repro script to use PPO instead of DQN then it works as expected.

**Comment by sven1977** [comment]
Hey @pxc , this is probably due to the exploration state not properly saved by RLlib. This is fixed in a currently open PR here:
https://github.com/ray-project/ray/pull/16354

**Comment by sven1977** [comment]
@pxc , could you confirm this is working in the current master and re-open in case it's still an issue for you?

Closing this issue now.

**Comment by pxc** [comment]
@sven1977 Many thanks. I've just tried this with `ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl` and can confirm that this issue is fixed there.
