### ISSUE TITLE
❓ [rllib] How to disable default encoding ?

### ISSUE THREAD

**Issue by remondn-swk** [ray-project/ray#16070]
My observation space is a `spaces.Discrete`.

`rllib` automatically one-hot encode this observation, as mentioned in the [docs](https://docs.ray.io/en/master/rllib-models.html#built-in-preprocessors)

---

**How can I disable this behavior ?**

The tensor my model receives has `[batch, discrete_size]` shape, but I want `[batch]` shape.

**Comment by krfricke** [comment]
cc @sven1977 and also see https://discuss.ray.io/t/how-to-disable-auto-encoding/2289 (duplicate)

**Comment by gjoliver** [comment]
it may be hard for now. but Sven is in the middle of getting rid of pre-processor altogether.
so mark this closed since Stale bot will soon close this anyways.
