### ISSUE TITLE
Fail to connect to head in another machine

### ISSUE THREAD

**Issue by lausannel** [ray-project/ray#16084]
### What is the problem?

Ray --1.2.0
Windows10
Python 3.8.3

I was running ray in one machine and I cannot connect to the remote server. Ray 1.2.0 or 1.3.0 neither worked
on another machine which has already started the ray service and connected to the head node(They are in the same network)
```Python
import ray
from ray.util.queue import Queue

ray.init(address='auto', _redis_password='5241590000000000')
# You can pass this object around to different tasks/actors
print("Start to Run!")
```
The output is as follows
```
2021-05-26 21:04:53,912 INFO worker.py:654 -- Connecting to existing Ray cluster at address: 183.172.63.51:6379
```
Then nothing happened, even without an exit code
I cannot run the code except in the head node

**Comment by lausannel** [comment]
I could use the redis-cli to connect to server
```
redis-cli.exe -h 183.172.63.51 -p 6379
183.172.63.51:6379>
```

**Comment by rkooo567** [comment]
Hi, @lausannel. I think the windows support is still alpha, and we don't support the cluster mode right now IIRC.

**Comment by carlogrisetti** [comment]
#19171 should have fixed this as well. Can you guys check if this is still a real issue?
