### ISSUE TITLE
[kubernetes][operator] Launch head and worker pods at the same time

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#16090]
Currently the operator launches the head pod first and then `minWorkers` workers. 
Launch the head and worker pods at the same time.

**Comment by tgaddair** [comment]
A couple things that would be great to change as part of this:

1. Run `headStartRayCommands` and `workerStartRayCommands` as the container init command, not from the operator.
2. Forward log output from the head / worker pods to stdout / stderr so it can be captured by k8s logging utilities like fluentd, etc.

Both of these should be achievable together is the start command is made blocking. What do you think?

**Comment by DmitriGekhtman** [comment]
100% 
For 1: https://github.com/ray-project/ray/issues/16088
For 2, just opened a generic issue to improve logging / document how to set up logging: https://github.com/ray-project/ray/issues/16101 
We're probably not going to be able to split up all the log-producing ray node processes into their own pods, at least not in the near future, so piping everything to stdout will probably not work.
