### ISSUE TITLE
export to onnx

### ISSUE THREAD

**Issue by armando-fandango** [ray-project/ray#16096]
In the following file: https://github.com/ray-project/ray/blob/master/rllib/policy/torch_policy.py

Please add export to onnx facility either in the export_model function or additional function.

**Comment by krfricke** [comment]
See also https://discuss.ray.io/t/how-to-save-rllib-model-as-onnx/2298

**Comment by armando-fandango** [comment]
How to guess the dummy_input once the access to the model object is obtained, because according to the PyTorch function to save ONNX models, the dummy input is required: https://pytorch.org/docs/stable/onnx.html#
