### ISSUE TITLE
[kubernetes][operator] Event/status monitoring stability

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#16092]
There's some risk of the operator dropping RayCluster lifecycle events and inconsistently processing state.
In particular, the current [status monitoring setup](https://github.com/ray-project/ray/blob/a7a5a2b2b72b91ffea840a85f1b10fdb3435c2f7/python/ray/ray_operator/operator.py#L305) is pretty fragile.
https://github.com/ray-project/ray/pull/15787 should greatly improve the situation, but we should still 

- add a reconciling loop to ensure consistency of state  
- monitor RayCluster status more robustly

**Comment by scottsun94** [comment]
@DmitriGekhtman 
Same question. In consideration of KubeRay, do we still need to do this? Or do we need to fix this for KubeRay?

**Comment by DmitriGekhtman** [comment]
Specifically relates to stability of legacy operator. This can be closed. Thanks again for following up.
