### ISSUE TITLE
[serve] Add support for `serve run` command for development

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#16094]
It would be very convenient to have something similar to `uvicorn run --reload` that would re-run your deploy script each time you saved it. We can also have the driver spin in the background so users can see logs from their deployments on the console.

**Comment by edoakes** [comment]
This should be as simple as:

```python
while True:
    <detect file changes>
    python underlying_script.py
```

**Comment by edoakes** [comment]
There should be an existing library to watch for file changes. @simon-mo didn't you point this out at some point?

**Comment by simon-mo** [comment]
#15505

**Comment by edoakes** [comment]
@simjay this might be a nice feature for you to work on if you're interested!

**Comment by simjay** [comment]
Will take a look!

**Comment by simjay** [comment]
@edoakes So just to be sure, this will be another command in `scripts.py`, which will be used for dev purposes right? If that's the case, it looks like a simple new-feature tasks (with all the info you guys listed above)

**Comment by edoakes** [comment]
@simjay yup, that's right!

**Comment by simjay** [comment]
@edoakes Make a quick initial PR for this. Please review! I was debating myself if we would need a 'detached' mode for serve.run. Let me know what you think!

**Comment by simjay** [comment]
@edoakes Please review! I was debating myself whether should I add `detached` mode for the serve.run or not. Let me know if that would be useful

**Comment by edoakes** [comment]
Thanks @simjay will try to look this weekend.
