### ISSUE TITLE
Ray crashes when the number of returned objects does not equal to num_returns

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#16100]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

- Ray nightly

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray

ray.init()


@ray.remote(num_returns=2)
def f():
    print("f")
    return []


ray.get(f.remote())
```

Output:

```
python repro.py                                                                                                                     ▼  raydev ubuntu@ip-172-31-33-4  23:30:25
2021-05-26 23:30:29,214 INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8266
(pid=1332600) f
2021-05-26 23:30:31,159 WARNING worker.py:1114 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. Task ID: a67dc375e60ddd1affffffffffffffffffffffff01000000 Worker ID: 08b9909051ddc796559e45f99d6f109fc8b2eeca86555d8884bc9b2b Node ID: 40dbbaa52193ee59f10a7f156a6ea1d42e4d9aad65c447ba0087577c Worker IP address: 172.31.33.4 Worker port: 40205 Worker PID: 1332600
^C^C^C^CTraceback (most recent call last):
  File "repro.py", line 12, in <module>
    ray.get(f.remote())
  File "/home/ubuntu/miniconda3/envs/raydev/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/raydev/lib/python3.8/site-packages/ray/worker.py", line 1487, in get
    values, debugger_breakpoint = worker.get_objects(
  File "/home/ubuntu/miniconda3/envs/raydev/lib/python3.8/site-packages/ray/worker.py", line 328, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 985, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 155, in ray._raylet.check_status
KeyboardInterrupt
(pid=1332599) f
```

The crash site is https://github.com/ray-project/ray/blob/master/src/ray/core_worker/transport/direct_actor_transport.cc#L524.

I was wondering if Ray could return a better error message in this case?

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
@franklsf95 do you mind creating a quick PR to fix it? I think we can just add assert failure or something? The fix could be pretty easy I believe?

**Comment by robin5540** [comment]
I'm new to ray. I thought this is an interesting issue.

Would it make sense to do a one time runtime self inspection of the source code to make sure the function always returns the correct amount of return values? Some thing like this

```python
import ast
import inspect

def check_number_return_vals(expected_num_of_vals):
    def _wrapper(func):
        func_ast = ast.parse(inspect.getsource(func))
        # TODO: This should be a simple visitor not manual loop

        # The we are always getting funcdef here so unwrap one layer
        assert len(func_ast.body) == 1 and isinstance(func_ast.body[0], ast.FunctionDef)
        body = func_ast.body[0].body

        for statment in body:
            if isinstance(statment, ast.Return):
                return_val = statment.value

                actual_number_of_returns = 0
                if return_val is None:
                    actual_number_of_returns = 0
                elif not isinstance(return_val, ast.Tuple):
                    actual_number_of_returns = 1
                else:
                    actual_number_of_returns = len(return_val.elts)

                if actual_number_of_returns != expected_num_of_vals:
                    raise RuntimeError(f"The number of return is expect to be {expected_num_of_vals} but got {actual_number_of_returns}, the offending function should be in the stack trace")
        # There is no wrapper going on, just a load time ast check
        return func
    return _wrapper


@check_number_return_vals(1)
def test_good_func():
    return 1

@check_number_return_vals(1)
def test_good_func_tuple():
    return (1,)

@check_number_return_vals(0)
def test_good_func_tuple_zero():
    return ()

@check_number_return_vals(2)
def test_bad_func():
    return 1


if __name__ == "__main__":
    pass
```

**Comment by franklsf95** [comment]
I think the main point is that we need to throw an error instead of crashing. Throwing an `AssertionError` is good here I think. What @robin5540 proposes is to throw a compile-time error rather than at runtime, which could surface the error earlier. @rkooo567 is there concern of performance penalty if we bake the AST checking logic into `@ray.remote`?

**Comment by rkooo567** [comment]
Hmm I don't think so. We do this checking only when the function or class is decorated by ray.remote right?  (so it will only impact the performance when serialization is happening)

**Comment by franklsf95** [comment]
Yea but this would only catch errors like

```
@ray.remote(num_returns=2)
def f():
  return 0
```

But not

```
@ray.remote
def f():
  return 0

f.options(num_returns=2).remote()
```

So maybe we should go with a runtime assertion error for now.

**Comment by rkooo567** [comment]
I see. I doubt this would incur any performance overhead. it is just one assertion when option is called right?

**Comment by franklsf95** [comment]
@rkooo567 it also involves parsing the function body using the `ast` module. But it should be fine.

**Comment by rkooo567** [comment]
Ah, I see. What about just we catch it in the cython code and upstream the assertion error?

**Comment by robin5540** [comment]
What about injecting the check here: https://github.com/ray-project/ray/blob/d3832ab2e1d28c36fba497d9c5e4c919900dbdf1/python/ray/remote_function.py#L72

This should catch all paths that tries to create a remote function.

**Comment by rkooo567** [comment]
oh right. We can probably do ast parsing when the remote function is created, cache the real num_returns, and always compare when options is called.

**Comment by rkooo567** [comment]
oh right. We can probably do ast parsing when remote functions are created, cache the real num_returns, and then we can compare them? In this case, do we ever need num_returns?

**Comment by robin5540** [comment]
>In this case, do we ever need num_returns?
I'm no familiar with the code base yet. If `num_returns` is only used for checking the sanity of the task. `RemoteFunction` init time check should suffice (for python at least)
