### ISSUE TITLE
[serve] Fix shutdown logic

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#16115]
`serve.shutdown()` is somewhat flaky right now. We should make this properly delete all of the deployments and wait for the deletion to go through (make it a synchronous call).

**Comment by edoakes** [comment]
@simjay this should be relatively small in scope and would help you better understand the backend_state loop

**Comment by simjay** [comment]
Hey @edoakes, it really did help me understanding the control loop in the backend_state. A few question before I make sure that I understood this issue correctly

1. It looks like the shutdown logic flows as such: `serve.shutdown` -> `Client.shutdown` -> `ServeController.shutdown` -> `BackendState.shutdown`. For me, it looks like each step's shutdown actually waits for shutdown to be completed (although `client.shutdown` is async method, it is being called with `ray.get`) Which part of these deletion processes should I make sure to be done? 
2. Would be a good 'flaky' usecase that I can recreate and potentially add to the test suites?

**Comment by edoakes** [comment]
@simjay

1. That's right that the client waits for that method call on the controller to finish, but the actual method itself isn't properly waiting for all of the state to be cleaned up. Specifically, what it does right now is pretty hacky in that it just sends a kill message to all of the actors (using ray.kill). It doesn't wait for them to finish and I don't think this even works in some cases such as when the actor hasn't started up yet. We should go through the normal delete operation for all of the deployments and wait for it to finish (same thing we do for `Deployment.delete()`)
2. Good question. One simple one is to try shutting down a deployment whose constructor always errors (I believe that is flaky right now). Another is just to add some tests ensuring that by the time shutdown() returns, all of the actors are gone from the system (we had this at some point, might still have some partial test cases for it).

**Comment by simjay** [comment]
@edoakes 

1. Ah interesting. For some reason I thought ray.kill would force stop the actors but good to know that it does not guarantee the actual termination of the actors. Will change ray.kill to a regular deployment deletion methods and see what I get.
2. This will be a good place to start I guess; coming up with the test suite that actually breaks the current flaky deployment. 

So this will be my plan of action:
implement test suites that breaks the current logic -> swap ray.kill with deployment deletion -> run the test suites again and pray it would pass :)
