### ISSUE TITLE
Feature Request: Unify CPP and Python worker IDs

### ISSUE THREAD

**Issue by joeybai** [ray-project/ray#16127]
### What is the problem?
CPP and Python worker IDs are treated as separate entities.
We would like a single ID to uniquely identify a worker.

CC @rkooo567 @ijrsvt @wuisawesome 

*Ray version and other system information (Python version, TensorFlow version, OS):* Latest

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
Hey @joeybai can you tell us the priority of this task? Is it a high priority?

**Comment by joeybai** [comment]
@rkooo567 this is medium priority for now, but could escalate in the near the future.

**Comment by alanwguo** [comment]
@rkooo567 , this is now a higher priority because its needed to reliably filter the actor logs from loki. Without this, we can easily associate an actor entity from the dashboard (identified by `py_worker_id`) with the logs stored in loki (keyed by a cpp worker_id).

**Comment by rkooo567** [comment]
cc @ericl

**Comment by rkooo567** [comment]
Reverted due to the Java issue
