### ISSUE TITLE
ray 1.3.0 on python 3.7 linux

### ISSUE THREAD

**Issue by freephys** [ray-project/ray#16126]
### What is the problem?
After pip install get error:

ray/autoscaler/_private/utility.py

impor ray._private.services as services
AttributeError: Module 'ray' has no attribute '_private'

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
This should be fixed in latest Ray? Please reopen an issue if this doesn't work!

**Comment by MrDarcy1** [comment]
Hi I got the same problem with import ray in python 3.6 win10. 
My ray version is 1.10.

import ray
Traceback (most recent call last):

  File "<ipython-input-13-d310bc7e5061>", line 1, in <module>
    import ray

  File "D:\anaconda\envs\pytorch\lib\site-packages\ray\__init__.py", line 83, in <module>
    _configure_system()

  File "D:\anaconda\envs\pytorch\lib\site-packages\ray\__init__.py", line 65, in _configure_system
    ray._private.compat.patch_redis_empty_recv()

AttributeError: module 'ray' has no attribute '_private'
