### ISSUE TITLE
[kubernetes][operator] Extend K8s configuration exposed in the Helm chart

### ISSUE THREAD

**Issue by bklaubos** [ray-project/ray#16151]
Usually the head and/or worker nodes needs to have access to credentials like AWS3, Postgres, etc for reading/writing data to external sources.
When autoscaling Ray nodes and the workers they spawn, need to be able make the secrets available similar to
config maps.
See https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by DmitriGekhtman** [comment]
Another recent request is to add imagePull secrets.

I think in the near future we can expose everything in a podSpec needed for secrets and many other fields,
keeping the few things really necessary for Ray's basic function hidden.

For the immediate moment, you may be able to add what you need directly by customizing the chart -- specifically, by editing the custom resource template [here](https://github.com/ray-project/ray/commit/95c3d88cac69f1d53d381baedc9dfe7192673dba).
The `podTypes` in values.yaml map directly to the `podTypes` in the custom resource template.

**Comment by DmitriGekhtman** [comment]
I've generalized the title.
