### ISSUE TITLE
[core] Disabling overcommit in plasma can cause ObjectStoreFullErrors due to fragmentation

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#16164]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

After #16061, SIGBUS errors no longer appear when overcommitting is disabled. However, now ObjectStoreFullErrors can be thrown instead. This is due to fragmentation and probably occurs more when large objects are allocated.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Dask-on-Ray [sort](https://gist.githubusercontent.com/stephanie-wang/f4d061ca237837f79069807cf88e6c14/raw/db619ddb490cf1b14726d59bc4a06ff8a87366a7/test_sort.py).

For reference, this is what I see now on Dask-on-Ray sort:
50GB object store, overcommit=True -> OK
50GB object store, overcommit=False -> ObjectStoreFullError
100GB object store, overcommit=True -> SIGBUS
100GB object store, overcommit=False -> ObjectStoreFullError

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

#16097 should fix this.

**Comment by ericl** [comment]
Overcommit is now flag disabled by default, so we can close this.

**Comment by stephanie-wang** [comment]
I think we should keep some version of this issue open since SIGBUS is still possible with the default config.

**Comment by ericl** [comment]
How about we re-open the original SIGBUS issue? This issue doesn't make sense since it's already fixed.
