### ISSUE TITLE
[rllib] Will the hidden state of an rnn policy be reset by default at the end of an episode?

### ISSUE THREAD

**Issue by LukasNothhelfer** [ray-project/ray#16166]
I'm relatively new to ray/rllib and have been fiddling with this question for a while, which I haven't been able to answer yet. My question: Is the hidden state of an rnn model derived from RecurrentNetwork, for example as described in [the documentation](https://docs.ray.io/en/master/rllib-models.html?highlight=forward_rnn#implementing-custom-recurrent-networks) automatically reset at the end of an episode? Is there then a new call of get_initial_state() or how are the initial values known then? In which module is this done? First of all, I would of course be interested to know if this is handled at all. I would be very grateful for any help, as this problem has been plaguing me for a while.

**Comment by richardliaw** [comment]
Hey @LukasNothhelfer could you redirect your question to discuss.ray.io? The community will be able to quickly help you out there!

**Comment by LukasNothhelfer** [comment]
Did it: https://discuss.ray.io/t/rllib-will-the-hidden-state-of-an-rnn-policy-be-reset-by-default-at-the-end-of-an-episode/2355
