### ISSUE TITLE
Metrics support in RaySGD

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#16182]
### Describe your feature request
Currently, our users are interested in the following metrics, supporting them in RaySGD would be very useful.
* accuracy
* precision
* recall
* f1_measure

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by richardliaw** [comment]
@valiantljk do you have any thoughts on the above suggestion?

**Comment by valiantljk** [comment]
@richardliaw I'll give it a try

**Comment by valiantljk** [comment]
Hi @richardliaw could you give me an example of using torchmetrics in raysgd?
