### ISSUE TITLE
[rllib] [tune] Logger not using default log dir in docker container on kubernetes

### ISSUE THREAD

**Issue by a-python-script** [ray-project/ray#16203]
I used the simple script from the tutorial

```
import ray
from ray import tune

ray.init()
tune.run(
    "PPO",
    stop={"episode_reward_mean": 200},
    config={
        "env": "CartPole-v0",
        "num_gpus": 1,
        "num_workers": 1,
        "lr": tune.grid_search([0.01, 0.001, 0.0001]),
    },
)
```

The script is run in a Docker container on a Kubernetes cluster. The Docker container has access to a local folder. Below is the snippet from the Kubernetes configuration file that handles this.

```
...
       volumeMounts:
            - mountPath: "/workspace/" # directory IN the container
              name: localdir # matches volume-name from below
...
      volumes:
        - name: localdir
...
            path: "/home/stud/nothelfer/custom-rl-impl/" # The path you want to mount
....
```

I have been able to run the folder configuration several times without any problems, the file systems are properly shared. So in my Docker container the above script is in the folder `/workspace/simple.py`

I would expect ray/tune to create the logdir in `/workspace/ray_results`. However, ray/tune tries to create the the logdir in `/ray_results`. I always get a PermissionDenied error from my container. The complete error is shown below. 

```
[...]$ logs myjob-57qf7
2021-06-02 23:00:42,341 INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
2021-06-02 23:00:42,344 WARNING services.py:1716 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=2.62gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/workspace/simple.py", line 5, in <module>
    tune.run(
  File "/opt/conda/lib/python3.8/site-packages/ray/tune/tune.py", line 449, in run
    runner = TrialRunner(
  File "/opt/conda/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 270, in __init__
    os.makedirs(self._local_checkpoint_dir, exist_ok=True)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/ray_results'
```
I am using the latest ray version and Python 3.8 in the Docker container.

- [yes] I have verified my script runs in a clean environment and reproduces the issue.
- [yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by LukasNothhelfer** [comment]
If you modify the above example as follows, it will work correctly:

```
import ray
from ray import tune

ray.init()
tune.run(
    "PPO",
    stop={"episode_reward_mean": 200},
    local_dir="./ray_results",
    config={
        "env": "CartPole-v0",
        "num_gpus": 1,
        "num_workers": 1,
        "lr": tune.grid_search([0.01, 0.001, 0.0001]),
    },
)
```
However, if you omit the `./` before `ray_results`, it does not work. It also doesn't work if you use your own trainable (derived from tune.trainable) instead of `"PPO"`.

**Comment by richardliaw** [comment]
Yeah, Tune will not auto-detect your own local dir for Kubernetes. It will always default to `~/ray_results`. 


> It also doesn't work if you use your own trainable (derived from tune.trainable) instead of "PPO".

Can you provide an example for what you mean here?

**Comment by krfricke** [comment]
Seems this is a k8s configuration error, so closing here
