### ISSUE TITLE
[tune] [rllib] Env config only allows dicts with string keys

### ISSUE THREAD

**Issue by stefanbschneider** [ray-project/ray#16215]
### What is the problem?

I'm using RLlib with a custom environment, which I want to configure with a dict that contains int values as keys.
This works fine with the environment itself, but when I try to run my RLlib algorithm against the environment, `ray.tune` throws an error:

```
2021-06-03 12:42:58,849	ERROR trial_runner.py:567 -- Trial PPO_CentralRelNormEnv_5aeab_00000: Error processing event.
Traceback (most recent call last):
  File "C:\Users\Stefan\git-repos\work\DeepCoMP\venv-old\lib\site-packages\ray\tune\trial_runner.py", line 529, in _process_trial
    flat_result = flatten_dict(result)
  File "C:\Users\Stefan\git-repos\work\DeepCoMP\venv-old\lib\site-packages\ray\tune\utils\util.py", line 249, in flatten_dict
    add[delimiter.join([key, subkey])] = v
TypeError: sequence item 1: expected str instance, int found
```

Apparently, Ray/RLlib expects all dicts inside the `config`, which also includes the env config, to only have string keys.
Why? Is there any reason not to allow int keys or is this just a bug? 

https://github.com/ray-project/ray/blob/master/python/ray/tune/utils/util.py#L271
Here, we could simply cast the `subkey` (and `key`) to string before applying `join`.

*Ray version and other system information (Python version, TensorFlow version, OS):*
* Ray version: 1.0 (I thought I had upgraded to 1.3; but the issue is also currently on `master`)
* Python version: 3.8.2
* TF version: 2.2.0
* OS: Windows 10

For example, an `env_config = {'dict_config': {1: 2, 2: 3}}` should fail because the dict within the `env_config` does not have string keys.

**Comment by krfricke** [comment]
Seems like this was resolved: https://github.com/ray-project/ray/blob/master/python/ray/util/ml_utils/dict.py#L120

A quick test shows it works:

```
from ray import tune

def train(config):
    for i in range(24):
        tune.report(metric=config["a"][2])


tune.run(
    train,
    num_samples=4,
    metric="metric",
    mode="max",
    config={
        "a": {
            2: 3,
            4: 5
        }
    }
)
```

closing this for now, lmk if the problem persists.
