### ISSUE TITLE
[Core] Placement group scheduling hangs in edge cases (1.4 regression, multiple repros)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#16221]
The placement group stress release tests is failing in pre-1.4, however it may be due to an infra change in the release tests.

**Comment by clarkzinzow** [comment]
This has been narrowed down to an issue with [scenario 2 in the placement group stress tes](https://github.com/ray-project/ray/blob/cf58cd76c701da39c1aecb37d14ab659df91f729/release/stress_tests/workloads/test_placement_group.py#L67-L146)t, specifically with concurrent placement group creation and removal when using the STRICT_SPREAD strategy. The test passes without issue when switching the strategy to PACK or STRICT_PACK, but fails for SPREAD and STRICT_SPREAD.

Moreover, STRICT_SPREAD passes when changing the precreated placement group percentage to 100%, such that all placement groups are created serially in the driver, and each pg launcher task waits and removes those placement groups in parallel. This specifically suggests an issue with creation of placement groups not behaving well in the face of concurrent creations and removals.

This is not being considered a release blocker for Ray 1.4.0.

**Comment by wuisawesome** [comment]
I'm not sure if this is actually helpful, but I can repro this issue on the scalability envelope too (using the default policy)

**Comment by ericl** [comment]
Note that https://github.com/ray-project/ray/issues/16237 has a potentially simpler repro that may be worth digging into first.
