### ISSUE TITLE
[Core] Pending actors behavior when using multiple driver

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#16237]
Can't figure out a better title, but here's a repro for the weird pending placement scaling behavior. Full script:
```python
import ray
from ray.cluster_utils import Cluster
from ray.test_utils import run_string_as_driver
import time

USE_PG = True

@ray.remote(num_cpus=1)
class A:
    def __init__(self):
        print("Started!")
        
    def ready(self): pass

@ray.remote(num_cpus=1)
class Controller:
    def __init__(self):
        self.actors = []

    def start_k(self, k):
        if USE_PG:
            pgs = [ray.util.placement_group([{"CPU": 1}]) for _ in range(k)]
            actors = [A.options(placement_group=pg, num_cpus=1).remote() for pg in pgs]
        else:
            actors = [A.options(num_cpus=1).remote() for _ in range(k)]

        refs = [actor.ready.remote() for actor in actors]
        return refs

    def set_replicas(self, num):
        num_to_add = num - len(self.actors)
        self.actors.extend(self.start_k(num_to_add))

    def get_num_ready(self):
        ready, not_ready = ray.wait(self.actors, num_returns=len(self.actors), timeout=1)
        return len(ready), ray.get(ready)

cluster = Cluster()
cluster.add_node(num_cpus=2)

ray.init(address="auto", namespace="a")
c = Controller.options(lifetime="detached", name="C").remote()
ray.get(c.set_replicas.remote(1))
print(ray.get(c.get_num_ready.remote())) # Should return 1
ray.shutdown()


ray.init(address="auto", namespace="a")
c = ray.get_actor("C")
ray.get(c.set_replicas.remote(50))
print(ray.get(c.get_num_ready.remote())) # Should return 1, because no available capacity.

# Let's add some nodes.
[cluster.add_node(num_cpus=2) for _ in range(2)]
while True:
    time.sleep(2)
    # Observe the "num_ready" value will stay at 1
    print(ray.get(c.get_num_ready.remote()))
```

This script shows that creating a detached actor that manages the lifetime of other actors. In the first job, the driver creates it and spawn one replica of A. In the second job, the driver tries to scale up the number of replicas of A. And we will add some worker nodes to the cluster. Then see how much actors can be placed. Running the script should print:
```
2021-06-03 19:08:18,109	INFO worker.py:727 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
(1, [None])
2021-06-03 19:08:19,376	INFO worker.py:727 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
(1, [None])
(1, [None])
(1, [None])
(1, [None])
(1, [None])
(1, [None])
... # repeats
```

And then if you change the flag `USE_PG = False`, the following will print, 
```
2021-06-03 19:09:47,462	INFO worker.py:727 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
(pid=63019) Started!
(1, [None])
2021-06-03 19:09:48,746	INFO worker.py:727 -- Connecting to existing Ray cluster at address: 192.168.1.69:6379
(3, [None, None, None])
(12, [None, None, None, None, None, None, None, None, None, None, None, None])
(12, [None, None, None, None, None, None, None, None, None, None, None, None])
(12, [None, None, None, None, None, None, None, None, None, None, None, None])
```
(note that this number `12` might change from run to run, I have seen 11 and 14 as well)

This is pretty bizarre as well because we should only have total of 6 CPUs in the cluster.

Few other notes:
- Changing the lifetime of placement group itself makes no difference
- This has to be done with two jobs. If we do everything in one job, it will scale fine.
- I was use the releases/1.4.0 version for the logs, `pip install https://s3-us-west-2.amazonaws.com/ray-wheels/releases/1.4.0/4ed174d167d4c35adbab009a42ac7f7d22c95ed7/ray-1.4.0-cp36-cp36m-macosx_10_13_intel.whl`. But I also tried nightly with [`b376fd345843be0da1dc49e964453ec8cb45432c`](https://github.com/ray-project/ray/commit/b376fd345843be0da1dc49e964453ec8cb45432c)

**Comment by simon-mo** [comment]
You can also try running `ray start --address=auto --num-cpus=1` in other terminal windows. The number of ready references won't change as you add more nodes. Regardless of the feature flag.

**Comment by simon-mo** [comment]
@clarkzinzow @ericl @wuisawesome @rkooo567 any idea?

**Comment by ericl** [comment]
I'm going to roll this issue into the other more general one here: https://github.com/ray-project/ray/issues/16221
