### ISSUE TITLE
[rllib] How to output parameters of model?

### ISSUE THREAD

**Issue by Glaucus-2G** [ray-project/ray#16285]
I have use PPO algorithm in my custom environment, the action_space and obs_space is like：
```
class MyEnv(gym.Env):
    def __init__(self):
        self.action_space = Box(-400,400,[3,])
        self.observation_space = Box(-1000,1000,[20,])
```
After hundreds of iterations，the action output for model is NAN.  I have also checked some ways  metioned in [#8135](https://github.com/ray-project/ray/issues/8135) and
[#7923](https://github.com/ray-project/ray/issues/7923), but it seems useless.

Now I want to check the parameters of the network when action is NAN. I have searched some issues and docs, but not find how to get these information from PPOTrainer. Could you tell me if  I have save a model like following codes, how to print the parameters of model which defined in PPOTrainer?

I use PPOTrainer.__getstate__() to get some garbled information, so I'm not sure if that is the weight of the network.
Should I define a same network which like in PPOTrainer? And then use restore to load model and print?

```
import ray
from ray.rllib.agents.ppo import PPOTrainer
from ray.tune.registry import register_env
import gym

class MyEnv(gym.Env):
    def __init__(self, env_config):
        self.env = gym.make('CartPole-v0')
        self.action_space = self.env.action_space
        self.observation_space = self.env.observation_space

    def reset(self):
        obs = self.env.reset()
        return obs

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        return obs, reward, done, info

def main():
    ray.init()
    register_env("myenv", lambda config: MyEnv(config))
    config = {
        'num_workers': 2,
        'use_pytorch': True,
        'model':{'fcnet_hiddens': [128,128],
                     'fcnet_activation': 'relu',}
    }
    trainer = PPOTrainer(env="myenv", config=config)
    max_training_episodes = 1
    for i in range(max_training_episodes):
        result = trainer.train()
        checkpoint_path = trainer.save()
        print(pretty_print(result))
    trainer.stop()

if __name__ == '__main__':
    main()
```

Ray version: 0.8.7

**Comment by mvindiola1** [comment]
Hi @Glaucus-2G,

Have your tried `trainer.get_weights()`?  That should return a dictionary with layer names and weight values.

**Comment by Glaucus-2G** [comment]
> Hi @Glaucus-2G,
> 
> Have your tried `trainer.get_weights()`? That should return a dictionary with layer names and weight values.

@mvindiola1  Thank you very much for your help! It works.

I have tried all the methods shown in the picture and `trainer.get_weights()` is not one of them. Maybe I should update my Ray version  to have a corresponding prompt.
![image](https://user-images.githubusercontent.com/28855796/121105518-d73fbd80-c836-11eb-9820-abb01b5d5a29.png)

Thank you again for your help！

**Comment by Glaucus-2G** [comment]
> Hi @Glaucus-2G,
> 
> Have your tried `trainer.get_weights()`? That should return a dictionary with layer names and weight values.

@mvindiola1  Thank you very much for your help! It works.

I have tried all the methods shown in the picture and `trainer.get_weights()` is not one of them. Maybe I should update my Ray version  to have a corresponding prompt.
![image](https://user-images.githubusercontent.com/28855796/121105518-d73fbd80-c836-11eb-9820-abb01b5d5a29.png)

Thank you again for your help！

**Comment by mvindiola1** [comment]
No problem happy to help. If you have more questions in the future, the anyscale team prefers if questions like this are asked at https://discuss.ray.io/
