### ISSUE TITLE
[Tune] Syncing to self-hosted S3 storage fails when checkpointing

### ISSUE THREAD

**Issue by sietseromijn** [ray-project/ray#16284]
### What is the problem?
Syncing to a self-hosted S3 storage fails when checkpoint_freq >= 1 is set in tune.run.
Because the S3 storage is self-hosted, the --endpoint-url flag needs to be set in the AWS CLI or it can't be found. 
This can't be circumvented by configuring the AWS CLI as far as I know [https://github.com/aws/aws-cli/issues/1270](url).

So to run the aws sync command with a custom endpoint I created the following SyncConfig:
```
        sync_config = tune.SyncConfig(
            sync_to_driver=False,
            upload_dir=f's3://tune-trials/',
            sync_to_cloud=f'aws --endpoint-url {os.environ["S3_ENDPOINT"]} s3 sync ' \
                          '{source} {target} --only-show-errors'
        )
```

This works for:
```
        analysis = tune.run(tune.durable(TFTrainable),
                            sync_config=sync_config,
                            num_samples=5,
                            config=tune_config,
                            stop={'training_iteration': 10},
                            verbose=True
                            )
```

But fails for:
```
        analysis = tune.run(tune.durable(TFTrainable),
                            sync_config=sync_config,
                            num_samples=5,
                            config=tune_config,
                            stop={'training_iteration': 10},
                            verbose=True,
                            checkpoint_freq=1,
                            checkpoint_score_attr='validation_loss')
```

with the following error:

```
ray.tune.error.TuneError: Sync error. Ran command: aws s3 sync /home/ray/ray_results/TFTrainable_2021-06-07_01-17-35/TFTrainable_d0d56_00000_0_learning_rate=1e-06_2021-06-07_01-17-36/ s3://tune-trials/TFTrainable_2021-06-07_01-17-35/TFTrainable_d0d56_00000_0_learning_rate=1e-06_2021-06-07_01-17-36 --only-show-errors
Error message (1): fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
```

As you can see ray defaults to the standard aws s3 sync command instead of the one provided in SyncConfig.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Build from rayproject/ray-ml:e58ba6-py38 image on Ubuntu 18.04.4 LTS

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
hey @sietseromijn I'll look into this this week. If you have a chance to find out where this bug is occurring, please let me know!

**Comment by sietseromijn** [comment]
Thanks @richardliaw 

I think the problem is that the durable trainer calls get_cloud_sync_client from ray.tune.sync_client,
which then creates the default sync_up and sync_down templates again, without checking the SyncConfig. 

```
def _create_storage_client(self):
    """Returns a storage client."""
    return get_cloud_sync_client(self.remote_checkpoint_dir)
```

```
def get_cloud_sync_client(remote_path):
    """Returns a CommandBasedClient that can sync to/from remote storage.

    Args:
        remote_path (str): Path to remote storage (S3, GS or HDFS).

    Raises:
        ValueError if malformed remote_dir.
    """
    if remote_path.startswith(S3_PREFIX):
        if not distutils.spawn.find_executable("aws"):
            raise ValueError(
                "Upload uri starting with '{}' requires awscli tool"
                " to be installed".format(S3_PREFIX))
        sync_up_template = "aws s3 sync {source} {target} --only-show-errors"
        sync_down_template = sync_up_template
        delete_template = "aws s3 rm {target} --recursive --only-show-errors"

    return CommandBasedClient(sync_up_template, sync_down_template,
                              delete_template)
```

**Comment by richardliaw** [comment]
Actually, this seems to be a durable trainable issue. @krfricke could you take a quick look at this?

**Comment by krfricke** [comment]
Yes, I have another task with S3 storage on my list and can look into both.

**Comment by krfricke** [comment]
Hey @sietseromijn, I opened a PR in #16739 to fix this. Could you take a look and maybe try out if the patch fixes your problem?

**Comment by sietseromijn** [comment]
Thanks @krfricke. Will try it this week

**Comment by sietseromijn** [comment]
Hey @krfricke, I have been unable to test it.  
I tried building Ray from source but i'm getting an AutoscalingExceptionRecovery error when creating a cluster. 

Might be because I am building the Dockerfile wrong. 
Does this look alright? 
```
FROM rayproject/ray-ml:1.4.1-py38
RUN sudo apt-get install -y git
RUN git clone --single-branch --branch self-s3 https://github.com/krfricke/ray/
RUN cd ray && python python/ray/setup-dev.py -y
```

**Comment by krfricke** [comment]
Hm, this looks good tbh, but since we merged this into master a few days ago, can you try `rayproject/ray-ml:nightly-py38`?

**Comment by krfricke** [comment]
It might be that I didn't merge latest master into that branch and that this lead to conflicts

**Comment by sietseromijn** [comment]
Yes the latest nightly build works and fixed the issue for me. Thanks!
