### ISSUE TITLE
[runtime env] actor and task runtime env should merge with job_config's runtime env

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#16294]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
We should also pass the working_dir field to the actors and tasks.
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by iycheng** [comment]
There are two things here, 1) for task and actor with different runtime env, we should merge it with base; 2) we shouldn't delete working dir. cc @AmeerHajAli

**Comment by iycheng** [comment]
Issue for 2) https://github.com/ray-project/ray/issues/16411
