### ISSUE TITLE
why shm_avail should be greater than object_store_memory

### ISSUE THREAD

**Issue by hahazhky** [ray-project/ray#16308]
```python
# Compare the requested memory size to the memory available in
# /dev/shm.
if shm_avail > object_store_memory: 
	plasma_directory = "/dev/shm"
elif (not os.environ.get("RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE")
	  and object_store_memory >
	  ray_constants.REQUIRE_SHM_SIZE_THRESHOLD):
	raise ValueError(
		"The configured object store size ({} GB) exceeds "
		"/dev/shm size ({} GB). This will harm performance. "
		"Consider deleting files in /dev/shm or increasing its "
		"size with "
		"--shm-size in Docker. To ignore this warning, "
		"set RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE=1.".format(
			object_store_memory / 1e9, shm_avail / 1e9))
```
why shm_avail need to be greater than object_store_memory, if I did not set object_store_memory, it is automatically set based on avaiable system memory, then they are equal. At this time, if I meet elif condition, it will raise an ERROR, I think it's not reasonable. When shm_avail is equal to object_store_memory, /dev/shm still works I think.

**Comment by ericl** [comment]
Do you mean we should change it to ">="?

There's also this current bug https://github.com/ray-project/ray/issues/14182 which means if you set them close, you are very likely to run into SIGBUS errors due to the way dlmalloc is working. The fix for that is in progress but it requires pretty substantial changes to Ray's memory allocation strategy.

**Comment by hahazhky** [comment]
@ericl Yes, I think >= is more reasonable，I set object_store_memory in ray.init for now to avoid this ValueError

**Comment by richardliaw** [comment]
will leave it to @ericl to triage/assign

**Comment by zhe-thoughts** [comment]
(Context: I’m doing a round of cleanup of waiting-for-triage issues)

@jjyao @rkooo567 @scv119 I'm marking this as P2 but let me know if you agree. Thanks!

**Comment by rkooo567** [comment]
@ericl since we have fallback allocation, we can just set it >= and close this?

**Comment by ericl** [comment]
Yes, I think >= would be fine. I don't think you would ever hit this except when manually setting the memory though, if I understand the scenario.
