### ISSUE TITLE
[Client] Ray Client Documentation

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#16313]
As discussed with @ijrsvt, making this issue to track Ray Client documentation improvements.

A few points that I think would help the docs:

- What is Ray Client?
- Why do I need it? When would I use it vs. ray.init?
- Step-by-step guide on how to set it up (Starting the cluster, how to do port forwarding)
- How do I configure Ray Client? How should all the args that I pass into ray.init be passed into ray.util.connect?
- Make sure that same versions of dependencies are installed on client side and server
- How to propagate environment variables to server
- Advanced: How does Ray Client actually work internally?

**Comment by ijrsvt** [comment]
TODO still:

* [ ] Configuring `ray.util.connect()`
* [ ] Explaining that dependencies must be the same version or else bad things might happen
* [ ] How to propagate environment variables to server
* [ ] Maybe a link to the `README.md` for how does it work
