### ISSUE TITLE
[runtime env] Make Serve fully support runtime_env

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#16318]
Right now all actors inherit the env of the initial job

**Comment by edoakes** [comment]
@iycheng we need some API for getting the underlying URIs for the working_dir

**Comment by iycheng** [comment]
https://github.com/anyscale/product/blob/master/backend/server/app_v2.py#L133-L135
https://github.com/anyscale/product/blob/master/start.py#L294-L296

**Comment by iycheng** [comment]
Or you can try this one:
```
ray.get_runtime_context().runtime_env
```

**Comment by ericl** [comment]
Is this more of a new feature than stability fix?
