### ISSUE TITLE
Fix unexpected signed to unsigned integer conversions

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#16321]
In Ray core, we sometimes unintentionally convert negative integer to unsigned integer and leads to unexpected behavior.

Following is a concrete example:
- in the OBOD Reference, [the object_size type is int64_t and default to -1](https://github.com/ray-project/ray/blob/608991999c4005f04790880ea575187addd1eafb/src/ray/core_worker/reference_count.h#L532);
- However in GetObjectLocationOwnerReply, the [object_size is typed uint64](https://github.com/ray-project/ray/blob/deda35fb4a5be2a1beff05d489a19d73a5c68d93/src/ray/protobuf/core_worker.proto#L224);

So as a result, if we have an unsolved object, call on [CoreWorker::GetObjectLocationOwner](https://github.com/ray-project/ray/blob/deda35fb4a5be2a1beff05d489a19d73a5c68d93/src/ray/core_worker/core_worker.cc#L2539) will return 2^64 - 1 in object_size (when -1 is converted to uint64_t)

We have other [usages](https://github.com/ray-project/ray/commit/0998d69968608012ca6cdd1ee166961df1aa0f0b#diff-d1a1d6d63f7b3cb5d146a52e04[…]9de40c6a7406dc0be121acb7f33a4c8
) of uint64_t. We should eliminate this category of unsafe conversion if possible.

**Comment by zhe-thoughts** [comment]
(Context: I’m doing a round of cleanup of waiting-for-triage issues)

@scv119 This is already assigned to you and in Core Backlog. Let's give it a priority label and we can remove it as`triage`?

**Comment by zhe-thoughts** [comment]
Making a judgement call that this is P2 (a tech debt that does not immediately affect any user yet). Chen can change if you see fit
