### ISSUE TITLE
[Core] Concurrent actor starting too many threads fix causing lost objects

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#16322]
### What is the problem?

The #14927 fix is currently causing lost objects in a shuffling data loader workload, confirmed via git bisecting and testing a wheel with the corresponding commit reverted. Still need to determine the underlying issue. A few half-baked possibilities:

1. The introduction of the bug that the aforementioned PR was fixing was made in [this PR](https://github.com/ray-project/ray/pull/7335), which itself was fixing an issue in which async actor tasks were being queued before the `is_asyncio_` flag is set by the actor creation task. It appears that said original issue may have been reintroduced by the more recent PR.
2. The PR #7335 introduced a fiber thread per caller, while #14927 reverted us back to a fiber thread shared by all callers/scheduling queues; did we at some point start implicitly relying on having a fiber thread per caller?

**Comment by jovany-wang** [comment]
This PR #14927 aims to fix starting too many threads for concurrent calls, and it doesn't care about the number of fibers I guess.
how about enabling that every caller holds a fiber instead of reverting #14927 ?

**Comment by rkooo567** [comment]
@ericl I think the fix needs to be picked for 1.4.1? Thought?

**Comment by ericl** [comment]
Yea tag it for 1.4.1

**Comment by clarkzinzow** [comment]
@jovany-wang we don't yet know if the bug is due to sharing a fiber thread among all callers, I was only calling that out as a possibility. And if that ends up being the bug, we should fix it so sharing a single fiber thread works instead of changing it to have a fiber thread per caller, since we'd definitely rather have a single shared fiber thread.

Here's my current plan: I'm going to timebox an investigation of the underlying bug. If I can identify the bug and create a fix, then I will close the reverting PR and open + merge a PR containing the fix (included in the 1.4.1 patch); if I can't, then I will add a minimal reproduction to this issue and also add it as a Python test (if possible), the reverting PR will be merged (included in the 1.4.1 patch), and the "concurrent actors starting too many threads" issue will be reopened, where any fix for that issue (e.g. a reverting of the revert PR) will have to not trigger this bug, either by ensuring that the test passed or, if we're unable to create such a test, by manually running the workload.

Hopefully we can find a fix for the underlying issue so we don't have to revert that PR!
