### ISSUE TITLE
[Core] Add container option in RuntimeEnv protobuf

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#16333]
### Describe your feature request

Currently runtime_env has been serialized to json format in python code, and in cpp code we can't use runtime_env field. I think this is the related PR: https://github.com/ray-project/ray/pull/15658

When starting worker process in container, we want to add field to specify container options (e.g. image,run_options). How about add `container option` field in runtime_env(python),  pass this field to TaskSpec(protobuf)?

**Comment by chenk008** [comment]
@iycheng @ericl Please take a look.

**Comment by ericl** [comment]
Can we serialize runtime env in protobuf instead? This should not be a separate field, it can be an attribute of runtime env.

**Comment by chenk008** [comment]
@ericl  Does you add  an attribute in RuntimeEnv like the following 
```
message ContainerOption {
  string image = 1;
  repeated string run_options = 2;
}

message RuntimeEnv {
  /// The raw json passed from user
  string raw_json = 1;
  /// Uris used in this runtime env
  repeated string uris = 2;
  ContainerOption containerOption = 3;
}
```

**Comment by ericl** [comment]
Yes, something like that would work.
