### ISSUE TITLE
Restricting Ray to particular NUMA zone?

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1634]
Larger machines have 2 physical sockets (ie, p3.16xlarge) so memory is non-uniform.
Is there a way to restrict Ray to use a specific NUMA zone?

In PyTorch, this can be done by using `GOMP_CPU_AFFINITY` flag, and gives increased performance for addition in some cases --
https://github.com/pytorch/pytorch/issues/5412#issuecomment-368693766

If PyTorch is restricted to use NUMA zone 0, it may improve performance when Ray results lie in the same numa zone.

**Comment by robertnishihara** [comment]
For memory in the object store, this would probably have to happen in the object store when we allocate the memory-mapped file. Probably in https://github.com/apache/arrow/blob/b2eb6ac90f9fd09d2bd2855b9c6121ea789ea6a0/cpp/src/plasma/malloc.cc#L86.

Alternatively, if we restrict the object store to use a single memory-mapped file, then it'll probably automatically be in a single NUMA zone (though I'm just guessing). We have a flag for that in the object store, but it currently isn't piped through to the Ray API. See https://github.com/apache/arrow/blob/b2eb6ac90f9fd09d2bd2855b9c6121ea789ea6a0/cpp/src/plasma/store.cc#L867.

@atumanov any idea how to do this?

**Comment by robertnishihara** [comment]
That's for memory managed by the object store. For memory allocated by pytorch or Python, it probably suffices to do set `GOMP_CPU_AFFINITY` before doing `ray start`.

**Comment by yaroslavvb** [comment]
`GOMP_CPU_AFFINITY` is GNU OMP specific, for setting affinity in numpy with MKL backend it's probably `KMP_AFFINITY`, and it looks like there's no standard way for doing it in numpy with OpenBLAS backend (https://github.com/xianyi/OpenBLAS/issues/905#issuecomment-223775844)

**Comment by atumanov** [comment]
NUMA affinity can certainly be done by pinning the object store on startup with `numactl --membind=0 <object_store_command>`. Note, though, that the memory available to the object store will be limited by the capacity of that NUMA zone. I'd also like to point out that pinning the process to a core does not guarantee that process' NUMA affinity. It only guarantees core affility. I haven't tried this in PyTorch, but the semantics of `GOMP_CPU_AFFINITY` is likely to guarantee core affinity only.

**Comment by atumanov** [comment]
ok, I've looked at the related github discussions on this, GOMP_CPU_AFFINITY is used by OpenMP to set affinity programmatically, which trickles down to sched_setaffinity() at a lower level. This same effect can be achieved with `numactl` as well. That way you have one hammer (`numactl`) for setting both NUMA affinity *and* CPU affinity as follows:
```
numactl --membind=<NUMA_ZONE> --physcpubind=<core_id>
```
Example:
```
numactl --membind=0 --physcpubind=0-3 sleep 999
```
This is also flexible enough to allow range specifications for both NUMA and CPU affinity.

**Comment by yaroslavvb** [comment]
So ray starts a bunch of processes, how do I numactl them all? Do I just do `numactl` on the parent? IE `numactl --.... python my_ray_script.py`?

**Comment by atumanov** [comment]
@yaroslavvb , we could properly expose this as part of the command-line interface when starting ray, but for how the easy workaround is to add the numactl command prefix in front of the object (aka plasma) store command here:
https://github.com/ray-project/ray/blob/master/python/ray/plasma/plasma.py#L64

**Comment by atumanov** [comment]
Then, you will also need to `numactl --membind=0` your python script, to make sure it binds to the same NUMA node zero. This should make sure that both the object store client and the object store server operate locally to the same NUMA zone. I felt like this would be an important feature to expose.

**Comment by robertnishihara** [comment]
Closing since I think this is answered.
