### ISSUE TITLE
Build failure (from source)

### ISSUE THREAD

**Issue by vipulharsh** [ray-project/ray#1637]
### System information
- Linux Centos 3.10:
- Ray installed from source:
- Latest version from git (commit-id: f1e5789c2694ae051c021775356efaf2c4b8f50c)
- Python version: 2.7.5
- python setup.py install --home=<build-dir>

### Describe the problem
 Build fails with the following error 

> ray/src/common/cmake/../task.h:12:37: fatal error:format/common_generated.h: No such file or directory
>  #include "format/common_generated.h"

On checking, no file named "common_generated.h" was found in the format directory.

### Source code / logs

[error.log](https://github.com/ray-project/ray/files/1773252/error.log)
[out.log](https://github.com/ray-project/ray/files/1773253/out.log)

**Comment by robertnishihara** [comment]
Ok, I just tried compiling on CentOS (Amazon Linux AMI) and couldn't reproduce the same error (it worked for me after doing the following on a fresh instance).

I initially got

```
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
    CMake 3.2 or higher is required.  You are running version 2.8.12.2
```

and had to upgrade `cmake` by following the instructions at http://jotmynotes.blogspot.com/2016/10/updating-cmake-from-2811-to-362-or.html.

Also had to do

```
sudo yum update
sudo yum install -y git cmake autoconf curl libtool boost-devel boost-devel-static unzip
sudo yum install -y gcc gcc-c++ make openssl-devel
sudo yum install flex bison

pip install cython
```

Can you check that all of those things are installed?

If you try recompiling, you'll need to do the following in between compilation attempts.

```
rm -rf thirdparty
git checkout thirdparty
```

**Comment by vipulharsh** [comment]
All the above dependencies seem to be in order. I am running the build script with only 1 thread (by setting the PARALLEL variable to 1).  The format/common_generated.h file is not present, so it might be a dependency issue somewhere.

**Comment by robertnishihara** [comment]
Can you first manually run the following and make sure it works?

```
cd ray/
./python/ray/core/flatbuffers_ep-prefix/src/flatbuffers_ep-install/bin/flatc -c -o src/common/format/ src/common/format/common.fbs --gen-object-api
```

Then after that, see if compilation works?

It could be an issue with some dependencies not being specified in the cmakelists so things are getting built out of order..

**Comment by robertnishihara** [comment]
Note that one of the most common sources of errors is trying to recompile after installing some dependencies. Since cmake caches a bunch of stuff, if you install new dependencies, you typically need to remove the ray directory and start over.

**Comment by vipulharsh** [comment]
I tried manually running the command and then ran "python setup.py install" and got the same error. I am seeing that the setup script removes the generated files.

**Comment by robertnishihara** [comment]
Code has changed enough that this error is likely no longer relevant.
