### ISSUE TITLE
[tune][rllib] Experiment results are missing from progress.csv but is in result.json

### ISSUE THREAD

**Issue by rlan** [ray-project/ray#16375]
### What is the problem?

After running tune.run, the experiment results are missing from progress.csv but are in result.json.
A possible solution is written by mannyv: https://discuss.ray.io/t/saving-checkpoints-with-good-custom-metric-using-tune-run/2109/12

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray version 1.2.0.
Tensorflow 1.15.4.
Python 3.7.8.
macOS 10.15.7.

### Reproduction (REQUIRED)

```python
import ray
from ray import tune

from ray.rllib.examples.env.random_env import RandomEnv

config = {
  "env": RandomEnv,
  "lr": 1e-4,
  "env_config" : {
    "max_episode_len" : 5,
  },
  "evaluation_interval" : 2,
  "evaluation_num_episodes": 1,
}

stop = {
  "training_iteration": 16,
}

ray.init()


metric = 'evaluation/episode_reward_mean'
mode = 'max'
results = tune.run(
  "A3C",
  name="test",
  config=config, 
  stop=stop, 
  checkpoint_at_end=False, checkpoint_freq=2, keep_checkpoints_num=3,
  checkpoint_score_attr=metric,
  mode=mode,
  )

results.default_metric = metric
results.default_mode = mode
# get the data frame
df = results.dataframe()
print(list(df.columns))
# or get the best checkpoint path
checkpoint_path = results.get_best_checkpoint(trial=results.get_best_trial())
print(checkpoint_path)

ray.shutdown()
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by richardliaw** [comment]
Hey @Patil2099 , this was simultaneously addressed by https://github.com/ray-project/ray/pull/15915 which we just merged.

Sorry for the confusion here!
