### ISSUE TITLE
[xgb] Cache HIGGS for CI 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#16388]
We should vendor this dataset to a S3 bucket. Here's an example of how we do this for MNIST dataset: https://github.com/ray-project/ray/commit/f4b2dd94b2f1a28547ac91b4e69d11b2fabf332e

**Comment by matthewdeng** [comment]
Created the [ray-ci-higgs](https://console.aws.amazon.com/s3/buckets/ray-ci-higgs?region=us-west-2&tab=objects) S3 bucket for this. 

Implementation/usage of this bucket for CI tests is currently pending Ray Client multi-node data loading support:
- Modin: https://github.com/modin-project/modin/issues/3179
- Dask: https://github.com/ray-project/ray/issues/16406
