### ISSUE TITLE
get_actor fails from separate process in version 1.4.0 (works in 1.3.0)

### ISSUE THREAD

**Issue by radix0000** [ray-project/ray#16380]
### Update

Seems that this is related to new namespace feature (adding namespace="" to all ray.init calls fixes problem), so disregard bug report below. This is now a "couldn't you have made a slightly bigger deal out change that breaks existing code in docs etc." issue.

### Previous report

*Ray version (fails):* 1.4.0 (working in 1.3.0)
*Python version:* 3.8.10

### Description

Acquiring a reference to a named actor works within the same process from which the actor was created, but consistently fails from a different process after connecting with ray.init(address="auto"), or specifying the address. Run ray.init(), create named actor, loop running get_actor to make sure is still there (all works), in separate python process run ray.init(address="auto") to connect, and run get_actor (fails in 1.4.0, works in 1.3.0)

### To Reproduce

To create actor:

````python
#!/usr/bin/env python
import asyncio

import ray
ray.init()

@ray.remote
class TestActor:
    def __init__(self):
        pass

async def run():
    a1 = TestActor.options(name="actor1").remote()
    while True:
        print("Running")
        print(ray.get_actor("actor1"))
        await asyncio.sleep(0.25)

if __name__ == "__main__":
    print("Starting ...")
    asyncio.run(run())
````

> ~/code/ray-test$ ./test1.py 
> 2021-06-11 15:10:26,507	INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8265
> Starting ...
> Running
> Actor(TestActor,5b38ce10f038c79b42a0705a01000000)
> Running
> Actor(TestActor,5b38ce10f038c79b42a0705a01000000)
> Running
> Actor(TestActor,5b38ce10f038c79b42a0705a01000000)
> Running
> Actor(TestActor,5b38ce10f038c79b42a0705a01000000)
> ...

To get the actor:

````python
#!/usr/bin/env python
import asyncio

import ray
ray.init(address="auto")

print(ray.get_actor("actor1"))
````
> ~/code/ray-test$ ./test2.py 
> 2021-06-11 15:10:47,096	INFO worker.py:726 -- Connecting to existing Ray cluster at address: xxx.xxx.xxx.xxx:29257
> Traceback (most recent call last):
>  File "./test2.py", line 28, in <module>
>     print(ray.get_actor("actor1"))
>   File "/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
>     return func(*args, **kwargs)
>   File "/lib/python3.8/site-packages/ray/worker.py", line 1659, in get_actor
>    handle = worker.core_worker.get_named_actor_handle(name)
>   File "python/ray/_raylet.pyx", line 1521, in ray._raylet.CoreWorker.get_named_actor_handle
>   File "python/ray/_raylet.pyx", line 159, in ray._raylet.check_status
> ValueError: Failed to look up actor with name 'actor1'. You are either trying to look up a named actor you didn't create, the named actor died, or the actor hasn't been created because named actor creation is asynchronous.

Expected result something like (what you get in Ray 1.3.0):

> ~/code/ray-test$ ./test2.py 
> 2021-06-11 15:06:45,579	INFO worker.py:640 -- Connecting to existing Ray cluster at address: xxx.xxx.xxx.xxx:45663
> Actor(TestActor,e5911d8aa2963ebb8dadf17401000000)

Note when reversing actor creation, so that the process that ran ray.init(address="auto") creates the actor and the original process that ran ray.init() just tries to get the actor, the same behaviour is observed (the process that did not create the process cannot ).

- [ x ] I have verified my script runs in a clean environment and reproduces the issue.
- [ x ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by wuisawesome** [comment]
> This is now a "couldn't you have made a slightly bigger deal out change that breaks existing code in docs etc." issue.

@radix0000 out of curiosity, in your opinion, what would've been the ideal way for us to have communicated this change?
