### ISSUE TITLE
Subscriber.cc thread-safe vs non-thread safe

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#16381]
### Describe your feature request

Related: https://github.com/ray-project/ray/pull/16334

Subscriber.cc is developed as a thread-safe module, and it has unlock -> lock again region in the codebase to call callbacks (since the callback can use subscriber API which can deadlock). @iycheng had another suggestion to just make the module non-thread safe and require callers to use the API always on the same thread (e.g., post on the io service always). 

There are pros and cons of these two approaches; 

Thread-safe
Pro: Easy to use for the API caller perspective. It is guaranteed that the entries are subscribed at the point where the function is called.

Con: The internal code needs to have a little complicated locking code (unlock before calling the subscription callback).

Not thread-safe
Pro: Internal code doesn't need locking code at all

Con: The API caller needs to ensure the Subscriber APIs are always called on the same thread as client pool's io service thread (which callbacks are executed).

**Comment by iycheng** [comment]
I'll make it a P1

**Comment by iycheng** [comment]
I think it's not about thread-safe or non-thread safe with a lock, but it's about:

```
{
  lock_guard(lock)
}
```

vs 

```
// in one place
{
   lock.unlock()
}
// in another place where you can't find easily
{
  lock.lock()
}
```

**Comment by rkooo567** [comment]
Yeah I agree, but we should focus on the end behavior here (since choosing io service will have a consequence of non-thread safe behavior). If your concern is purely about that it is hard to understand where to lock again, is it okay to use re-entarant lock?

**Comment by rkooo567** [comment]
Will just use io service to execute callbacks
