### ISSUE TITLE
ray stack command doesn't work

### ISSUE THREAD

**Issue by leonnardo** [ray-project/ray#16383]
Ray version: 1.4.0
MacOS version: 11.4
Python version: 3.7.10
py-spy version: 0.3.7

When I run `ray stack` it shows this error:
```
Stack dump for leonnardo.rabello 81007   0.6  0.8  8213348 132640 s001  S     3:20PM   1:46.50 ray::Clf
error: Found argument '--native' which wasn't expected, or isn't valid in this context

USAGE:
    py-spy dump [OPTIONS] --pid <pid>

For more information try --help
```
Removing the `--native` arg from the command [here](https://github.com/ray-project/ray/blob/3fa9f2e5d628c271c06b3fd9636ce0c952f64b42/python/ray/scripts/scripts.py#L1337) worked fine for me.

I can fork and make the merge request if you want.

**Comment by richardliaw** [comment]
@leonnardo `--native` isn't working on macos. 

A merge request would be very much appreciated! Can you just check `sys.platform == 'darwin'` and remove the --native arg if so?

**Comment by wuisawesome** [comment]
Looks like native is only really supported on linux, so we might want the check to be `sys.platform != linux` instead.

**Comment by leonnardo** [comment]
> @leonnardo `--native` isn't working on macos.
> 
> A merge request would be very much appreciated! Can you just check `sys.platform == 'darwin'` and remove the --native arg if so?

Yeah, sure!

Do you have any unit tests for this or should I not worry about this?

**Comment by wuisawesome** [comment]
You may need to modify `python/ray/tests/test_advanced_3.py::test_ray_stack`

**Comment by richardliaw** [comment]
hey @leonnardo did you end up opening a request? sorry for the late followup!

**Comment by pcmoritz** [comment]
fixed by https://github.com/ray-project/ray/pull/36100
