### ISSUE TITLE
[client] Mishandling of `argparse` functionality in `ray.util.client.server` leads to inability to specify redis address for `ray` server.

### ISSUE THREAD

**Issue by OrEisenberg** [ray-project/ray#16399]
`ray` version: 1.4.0
`python` version: 3.7.7

### Reproduction
Run 
```
python -m ray.util.client.server --redis-address {address_1}
```
in a setting where 
`ray._private.services.find_redis_address()` returns `[address_0, address_1]`. 

### Elaboration
As near as I can tell, all the problems with how `try_create_redis_client` behaves in this context seems to stem from the fact that it assumes that a dict with keys identical to the command line args is passed, but this is just not how `argparse.Namespace` and `argparse.ArgumentParser` work.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
cc @ijrsvt

**Comment by ijrsvt** [comment]
@OrEisenberg Thanks for bringing this up!

**Comment by OrEisenberg** [comment]
@ijrsvt Thanks for taking care of it so quickly!

**Comment by ijrsvt** [comment]
@OrEisenberg No worries! Glad you found this :)
