### ISSUE TITLE
[kubernetes] Decouple Ray Operator from Ray Core release cycle

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#16415]
Currently, the Ray Operator for k8s has very little overlap with the ray core API, and in the future should have none once the autoscaler is implemented a Pod. Moving the Ray Op to its own release cycle would make it easier to develop both projects without needing to be held up by timelines from the other.

cc @richardliaw @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
This a reasonable suggestion, but --

We're ramping up for a faster release cycle (target: one minor release per two weeks) so it might not be necessary, in terms of one component significantly blocking the other.

Having decoupled interoperable components is definitely something we think about, e.g. lots of discussion internally around maintaining independence of the autoscaler from the core of Ray. Splitting up releases is probably not something that's going to be done in the near term, though.

**Comment by richardliaw** [comment]
@DmitriGekhtman @AmeerHajAli do you have any insight re: the progress on maintaining independence of the autoscaler from Ray?

**Comment by DmitriGekhtman** [comment]
For autoscaler and Ray versions are interoperable since 1.2.0 -- the relevant protobufs are stable with a clear message not to change.
However, the monitor has some Ray core dependencies.

Main thing we're thinking about in this thread is independence of the k8s operator from the autoscaler (and the rest of ray)

**Comment by DmitriGekhtman** [comment]
Also, sry above I meant a target of a _patch_ release per two weeks.
