### ISSUE TITLE
model default config

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#16421]
Hello, @sven1977 !
I have read the MODEL_DEFAULTS: ModelConfigDict . I have some questions about the model default config.

1.  In the model config, fc net can be set as : [256,256]. It means 2 hidden FullyConnectedNetwork layers to be used.  Right?
2.  "model":{
            "fcnet_hiddens": [256, 128],
            "fcnet_activation": "tanh",

            "use_lstm": True,
            "max_seq_len": 20,
            "lstm_cell_size": 256,
        },

If I set the model config as this, It means I use the FullyConnectedNetwork and lstm together, right?

**Comment by richardliaw** [comment]
I believe so!

**Comment by richardliaw** [comment]
be sure to ask questions on discuss.ray.io too!
