### ISSUE TITLE
[ray] - Suggestion: remove from default printing the log within jupyter lab

### ISSUE THREAD

**Issue by Jhonathan-Pedroso** [ray-project/ray#16431]
I strongly recommend eliminating the default behavior of printing the log within the output. When working with large clusters it is absolutely frustrating when the notebook freeze because of the html being overpopulated by error messages and you can not cancel the job. If I was a user getting started I would definitely never use it again. I would recommend also you collaborate with jupyter lab folks for better communication of the worker tasks within jupyter lab, specially for cancelling them.

**Comment by richardliaw** [comment]
Hey @Jhonathan-Pedroso thanks a bunch for this candid feedback.

Perhaps we can disable printing once the flow of output becomes too fast. This would make it so that smaller use cases (local machine + jupyter) would still get some output.

**Comment by richardliaw** [comment]
@rkooo567 could you help triage this request?

**Comment by Jhonathan-Pedroso** [comment]
> Hey @Jhonathan-Pedroso thanks a bunch for this candid feedback.
> 
> Perhaps we can disable printing once the flow of output becomes too fast. This would make it so that smaller use cases (local machine + jupyter) would still get some output.

I think this would be great @richardliaw

**Comment by ericl** [comment]
Does `ray.init(log_to_driver=False)` solve the problem?

**Comment by Jhonathan-Pedroso** [comment]
@ericl it does not, keep printing

**Comment by ericl** [comment]
Does this work for you?

```
ray.init(addr, log_to_driver=False)
2021-06-16 13:13:33,595	INFO worker.py:734 -- Connecting to existing Ray cluster at address: 192.168.5.121:6379
>>> @ray.remote
... def f():
...   print("HI")
... 
>>> 
>>> f.remote()
ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000001000000)
```

(no "HI" is printed with this setting)

**Comment by Jhonathan-Pedroso** [comment]
@ericl  the problem it is when start to display a bunch of errors, and you submit several hundreds of processes.

**Comment by ericl** [comment]
Can you provide an example script that produces errors with log to driver
false? Sounds like a bug.

**Comment by Jhonathan-Pedroso** [comment]
@ericl unfortunately I can not disclosure due to confidentiality, I apologize for that, it is out of my control.

**Comment by ericl** [comment]
Can you make a generic repro?

**Comment by scottsun94** [comment]
@Jhonathan-Pedroso Sorry to bother. +1 Eric. Are you able to create a generic repo? Otherwise, it's hard to validate a fix.

**Comment by zhe-thoughts** [comment]
It's been 7 days since the ask for a repro. Let's close this and @Jhonathan-Pedroso please reopen if the issue still exists! Thanks for reporting your experience using Ray
