### ISSUE TITLE
[SGD] Remove `sgd_gpu` release test

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#16435]
Due to https://github.com/anyscale/product/issues/4573, ` release/nightly_gpu_tests/sgd_gpu/sgd_gpu_test.py` has been temporarily set to `num_workers=1` (https://github.com/ray-project/ray/pull/16382/) to allow it to pass and test fp16 support. Once the linked issue has been solved, it should be set back to `num_workers=2`.

**Comment by Yard1** [comment]
cc @amogkam

**Comment by amogkam** [comment]
Leaving this open to disable the `sgd_gpu` test from the release test suite. We have now deprecated Ray SGD, and in the future, any tests of this form should be run in GPU CI anyways.
