### ISSUE TITLE
[rllib] (Update ray 1.4.0) AttributeError: 'NoneType' object has no attribute 'keras'

### ISSUE THREAD

**Issue by cola-nicolas** [ray-project/ray#16457]
### What is the problem?

I'm using RLLib with Pytorch.
In version `1.3.0`, I was registering my model with :

```python
from ray.rllib.models import ModelCatalog

ModelCatalog.register_custom_model("my_model", MyModel)
```

I upgraded to version `1.4.0`, and now the same line raises the following error :

> Traceback (most recent call last):
  File "main.py", line 18, in <module>
    ModelCatalog.register_custom_model("my_model", MyModel)
  File "/home/me/miniconda3/envs/rllib/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 741, in register_custom_model
    if issubclass(model_class, tf.keras.Model):
AttributeError: 'NoneType' object has no attribute 'keras'

#### Where is the problem

The culprit seems to be this line :

https://github.com/ray-project/ray/blob/3a09c82fbfce8f00533234844729e6d99fb0f24c/rllib/models/catalog.py#L741

Which does not work because `tf` is `None`.

**Comment by borogreg** [comment]
The issue was solved [here](https://github.com/ray-project/ray/pull/16171).
You can also work around the issue by installing tensorflow in your conda environment.
