### ISSUE TITLE
[core] Temp dir / cluster address issues

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#16458]
### What is the problem?

Ray uses the default temp directory for the "ray_current_cluster" file whether or not a custom `temp-dir` is passed to `ray start`. 
For example:
https://github.com/ray-project/ray/blob/2abb1e1d38b11a87d32715fc4593d98e15ea4553/python/ray/scripts/scripts.py#L584
https://github.com/ray-project/ray/blob/2abb1e1d38b11a87d32715fc4593d98e15ea4553/python/ray/scripts/scripts.py#L809
https://github.com/ray-project/ray/blob/2abb1e1d38b11a87d32715fc4593d98e15ea4553/python/ray/client_builder.py#L146
This can lead to permissions troubles which can block on-prem Ray usage, see
https://github.com/ray-project/ray/issues/16339#issuecomment-861299718

Either find a way to persist custom temp dirs passed to ray start or find a 
different way to store the current Ray cluster address.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
While it would be easy enough to fix in the "head" if branch in ray start, not sure how to consistently fix everywhere.

**Comment by rkooo567** [comment]
@DmitriGekhtman is this handled in the merged PR above?

**Comment by DmitriGekhtman** [comment]
Yep, closing.
