### ISSUE TITLE
Possible memory corruption on fd reuse if plasma_unlimited=1

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#16460]
The plasma client does not handle re-use of file descriptors properly. Re-use of a file descriptor id can cause memory corruption as the client tries to map memory from the wrong files.

FD re-use can occur if we ever un-map a file, which occurs when we deallocate filesystem-backed pages with RAY_plasma_unlimited=1.

This issue was discovered in https://github.com/ray-project/ray/pull/16451 (thanks @scv119 !)

```
import random
import ray
import numpy as np

@ray.remote
class Actor:
    def produce(self, i):
        s = int(random.random() * 200)
        z = np.ones(s * 1024 * 1024)
        z[0] = i
        return z

    def consume(self, x):
        print(x)

ray.init(object_store_memory=100e6)
i = 0
a = Actor.remote()
b = Actor.remote()
while True:
    x_id = a.produce.remote(i)
    i += 1
    ray.get(b.consume.remote(x_id))
```

**Comment by rkooo567** [comment]
It's probably because we don't properly close them? (If I remember correctly, we don't close fds at all for plasma objects)
