### ISSUE TITLE
jemalloc as Arrow's default allocator

### ISSUE THREAD

**Issue by xhochy** [ray-project/ray#1648]
I just wanted to give you a heads-up that we plan to activate `jemalloc` as the default allocator in the Arrow 0.9 release again. This should speed up a lot of Arrow's operations. Previously we had some problems that are now fixed in jemalloc (Arrow will vendor its own namespaced version of jemalloc to ensure that all the fixes are included).

It would be nice if you could try out the latest Arrow HEAD built with `-DARROW_JEMALLOC=ON` and see if this causes any problems for Ray. This would give me some advanced warning if there is still anything problematic. I don't expect anything to actually break but I want to be super-sure ;)

**Comment by concretevitamin** [comment]
@xhochy Thanks for the heads up.  I'm curious: have you or the team tried other malloc implementations?  Tcmalloc?

**Comment by yaroslavvb** [comment]
TensorFlow team compared jemalloc and tcmalloc and went the jemalloc route
