### ISSUE TITLE
[tune] Docker : Ray Dashboard 

### ISSUE THREAD

**Issue by kangsan0420** [ray-project/ray#16491]
Hi,
I'm trying to use ray tune for my project on docker and I have trouble with accessing ray dashboard.
I changed the dashboard port since I already set the port binding for the container as below.

```python
tune.init(dashboard_port=9012)
tune.run(
    ...
)
```

This resulted in the below image and I wanted to view the ray dashboard.

![image](https://user-images.githubusercontent.com/79678563/122322171-01445e80-cf60-11eb-83ea-ce2fff6cf0b5.png)

However, when I access to that port with host ip, I get the connection refused error as below.
I have checked the firewall setting and I think it's not the docker setting problem because I'm using another port for the same host to remote jupyter.

![image](https://user-images.githubusercontent.com/79678563/122323034-69e00b00-cf61-11eb-91f8-c7eb0da42f6c.png)

**Comment by Aaronyxt** [comment]
I tried the init function with the following setting and it worked for me.

tune.init(dashboard_port=9012, dashboard_host="0.0.0.0")

**Comment by kangsan0420** [comment]
@Aaronyxt Thank you! I should have noticed the host :)
