### ISSUE TITLE
[rllib] R2D2: Batch management when using both RNN and non-RNN policies in a single MA environment 

### ISSUE THREAD

**Issue by thomascros** [ray-project/ray#16503]
### What is the problem?

The problem occurs while using a multi-agent environment when at least one agent is using R2D2 policy and another agent is using a non-RNN policy. It happens inside _timeslice_along_seq_lens_with_overlap_ method in _add_batch_ method of the _LocalReplayBuffer_ class of _replay_buffer.py_:

When a batch of an non-RNN policy is processed, it does not contains any 'seq_lens' key which raise an error inside the timeslice_along_seq_lens_with_overlap method:

>     assert seq_lens is not None and len(seq_lens) > 0, \
>             "Cannot timeslice along `seq_lens` when `seq_lens` is empty or None!"

The fact that is does not contain a 'seq_lens' seems normal (as it is not supposed to be used in a RNN configuration) but I guess that the batch should not been timeslice at all. However, the condition (to timeslice or not a batch) is defined by the _self.replay_sequence_length_ of the _LocalReplaybuffer_ class, with is set to be > 1 because we are using a R2D2 policy for at least one agent.

### A non-optimal solution

I extended the condition in add_batch method of the LocalReplaybuffer class (see the bold sentence below: ** XXX **) not to timeslice batches of non-RNN policies. I think this solution is not optimal because I guess it can hide errors if the batch's keys are not well initialized by the trajectory view API for each policies.

>                 for policy_id, sample_batch in batch.policy_batches.items():
>                     print("policy_id =", policy_id)
>                     print("sample_batch =", sample_batch)
>                     if self.replay_sequence_length == 1 or **"seq_lens" not in sample_batch.data** :
>                         timeslices = sample_batch.timeslices(1)
>                     else:
>                         timeslices = timeslice_along_seq_lens_with_overlap(
>                             sample_batch=sample_batch,
>                             zero_pad_max_seq_len=self.replay_sequence_length,
>                             pre_overlap=self.replay_burn_in,
>                             zero_init_states=self.replay_zero_init_states,
>                         )

Ray version: 1.4.0 (also tested on latest wheels)

### Reproduction

The problem can be easily reproduced using [the rllib rock_paper_scissors example ](https://github.com/ray-project/ray/blob/1df19a04fe2b9960ba364cbcc8da996cb214bfa8/rllib/examples/rock_paper_scissors_multiagent.py
), if one set trainer="R2D2" and run the third test called: run_heuristic_vs_learned(args, lstm=True).

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ArturNiederfahrenhorst** [comment]
Hi @thomascros, thanks for raising this! I've implemented another solution in the linked PR. Maybe that solution works for you? Feel free to leave feedback over there if you have any thoughts.
