### ISSUE TITLE
[RLlib] 'RNNModel' object has no attribute 'base_model' (for curiosity)

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#16505]
I have verified my script runs in a clean environment and reproduces the issue.
 I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

I try to use the rnn_model.py in my code. In my code, 9 PPO agent is set and each agent use the curiosity module and custom model. I am sure that PPO agent with curiosty module and without custom model work!

trainer = PPOTrainer(env="3x3grid", config={
        "num_workers": 0,
        "exploration_config": {
            "type": "Curiosity",
            "lr": 0.001,
            "sub_exploration": {
                "type": "StochasticSampling",
            }
        },
        "model":{
            "custom_model": "rnn",
            "max_seq_len": 20,
        },

![image](https://user-images.githubusercontent.com/38434094/122397283-66717180-cfab-11eb-807e-41b9b5b2bca4.png)

Can you teach me where is wrong?
Thank you!

**Comment by AdityaDas-IITM** [comment]
I'd like to work on this issue, could you please help me get started?

**Comment by dolphingarlic** [comment]
Adding to this, using `ComplexInputNetwork` (with Ray 1.10) gives me the same error in the same place: ` AttributeError: 'ComplexInputNetwork' object has no attribute 'base_model'`.

I noticed that changing `self._curiosity_feature_net.base_model.variables` to `self._curiosity_feature_net.variables()` seems to get rid of this bug -- perhaps that could be a fallback if `base_model` doesn't exist?

**Comment by dyllanwli** [comment]
Got the same issue in `ray-2.0.0.dev0`

**Comment by grizzlybearg** [comment]
Hi, is there any progress on this?

**Comment by grizzlybearg** [comment]
Why has this been closed?
