### ISSUE TITLE
[rllib] assert seq lens is not None!

### ISSUE THREAD

**Issue by zzchuman** [ray-project/ray#16500]
Hello @sven1977 !

python 3.7.6
torch 1.9.0
ray 1.4.0 and 1.0.0

In my code, I set the 9 PPO agent. The agent set is:

 
![image](https://user-images.githubusercontent.com/38434094/122365156-053aa580-cf8d-11eb-84f9-7896708838bf.png)

And I sure that it works without lstm setting. But when I add the lstm, It occours:
![image](https://user-images.githubusercontent.com/38434094/122365376-34511700-cf8d-11eb-85eb-aa689920b747.png)

It reminds me that assert seq lens is not None! 
But I do not know how to set it!

Thank you!

**Comment by DomagojHack** [comment]
Any news with this, I am reproducing the same problem with A3C
