### ISSUE TITLE
[rllib] Fix to flakey TD3 tests causes regression in IMPALA

### ISSUE THREAD

**Issue by Bam4d** [ray-project/ray#16529]
### What is the problem?

Recently a fix to a problem that many users were having was merged: #16162

This fix was then mostly removed to fix flakey tests: #16309

@sven1977  the original issue is now back.

torch 1.8.1
python 3.8
ray (latests wheels)

### Reproduction (REQUIRED)

Reproduction and description of issue is in the original ricket #16162 

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Hmm, let me make sure we triage this.

**Comment by richardliaw** [comment]
@Bam4d can you reopen the PR?

**Comment by smorad** [comment]
@Bam4d @sven1977  I can verify this issue is back. Strangely, now `sample_time` explodes rather than `grad_time` using IMPALA
![image](https://user-images.githubusercontent.com/1743889/124604517-ebd99a80-de62-11eb-93c4-6e183a410ba6.png)

**Comment by sven1977** [comment]
Thanks for the new PR @Bam4d , I'll merge it asap (I'll quickly confirm on a GPU machine).

**Comment by sven1977** [comment]
The above PR was merged, hence the issue was fixed. Closing this now. Please re-open in case this issue resurfaces again in the future.
