### ISSUE TITLE
Problems Running on Cluster using the Manager: Slurm

### ISSUE THREAD

**Issue by marianogabitto** [ray-project/ray#1653]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: ray (0.3.1)
- **Python version**: 2.7.13
- **Exact command to reproduce**: import ray

### Describe the problem

I get the following error when I try to import ray:

import ray
  File "/mnt/xfs1/home/mgabitto/python_cpu/lib/python2.7/site-packages/ray/__init__.py", line 50, in <module>
    from ray.worker import (error_info, init, connect, disconnect,
  File "/mnt/xfs1/home/mgabitto/python_cpu/lib/python2.7/site-packages/ray/worker.py", line 946, in <module>
    global_worker = Worker()
  File "/mnt/xfs1/home/mgabitto/python_cpu/lib/python2.7/site-packages/ray/worker.py", line 238, in __init__
    self.original_gpu_ids = ray.utils.get_cuda_visible_devices()
  File "/mnt/xfs1/home/mgabitto/python_cpu/lib/python2.7/site-packages/ray/utils.py", line 133, in get_cuda_visible_devices
    return [int(i) for i in gpu_ids_str.split(",")]
ValueError: invalid literal for int() with base 10: 'NoDevFiles'

### Source code / logs

This is how I am running the code:
sbatch -N 1 --exclusive runner_cpu.sh 

Inside runner_cpu.sh is the following code:

#!/bin/bash

# activating the correct environment
module load gcc/7.2.0
module load cuda
module load cudnn/v5.1-cuda-8.0
source ~/python_cpu/bin/activate

# Running Command
stdbuf -oL python code.py  >> log.log

Any help appreciated

Thanks,

M

**Comment by robertnishihara** [comment]
What is the value of `gpu_ids_str`? Can you post the code example?

**Comment by pcmoritz** [comment]
cc @rshin who might have ran Ray on Slurm

**Comment by robertnishihara** [comment]
@marianogabitto, can you also do `echo $CUDA_VISIBLE_DEVICES` from the command line and see what it says?

**Comment by marianogabitto** [comment]
If I do 
echo $CUDA_VISIBLE_DEVICES

on the command line it returns an empty line. But what we actually want is to run the command within a bash script. When I do it, I get "NoDevFiles"

so basically I think this is the problem. Why do you have to query how many gpus does the system has? Can we omit this? some option to avoid gpu support?

M

**Comment by marianogabitto** [comment]
One update. I solved the issue by running the script using:

sbatch -N 1 -p gpu --gres=gpu:2  --exclusive runner_cpu.sh

Basically, I am allocating gpu's to the process (although I am not using them). In this way, the variable returns with a number and the script can proceed. Is there any way of removing this gpu check from Ray with any flag (--nogpu)?

M

**Comment by robertnishihara** [comment]
Yeah we can fix this. Another workaround that should work is when you do `ray start ...` on all of the machines, change it to be `CUDA_VISIBLE_DEVICES='' ray start ...`.

**Comment by marianogabitto** [comment]
Yes, it works now...

Great, I am closing this issue as it is solved.

Thanks !

**Comment by leon2014dresden** [comment]
hi @marianogabitto i have got the same problem as you. But i don't understand the solution 'change it to be CUDA_VISIBLE_DEVICES='' ray start ... '. Can you tell me how to change the slurm file or python script?

**Comment by marianogabitto** [comment]
Dear Leon,
     I fix my issue by adding a line into my slurm script. Can you try to see if this works? This is my slurm script:

#!/bin/bash
source activate python_with_ray

CUDA_VISIBLE_DEVICES=''

python my_script

**Comment by leon2014dresden** [comment]
Yes, it works now...

thank you!
