### ISSUE TITLE
PBT Replay relies on outdated code

### ISSUE THREAD

**Issue by yorickvanzweeden** [ray-project/ray#16563]
This line in PopulationBasedTrainingReplay relies on outdated code
https://github.com/ray-project/ray/blob/79a9d6d5171071190f531121be310fb4d203cf11/python/ray/tune/schedulers/pbt.py#L822

Currently, the `stop_trial` method does not support a `stop_logger` keyword.
https://github.com/ray-project/ray/blob/79a9d6d5171071190f531121be310fb4d203cf11/python/ray/tune/ray_trial_executor.py#L468

This ability was removed in https://github.com/ray-project/ray/commit/603accf1c28fc08f8d0ab5351777bba288ab3df0. It used to look like this:
https://github.com/ray-project/ray/blob/f7b19c41e3c0e4c131a78c632e3e5ce380194fe4/python/ray/tune/ray_trial_executor.py#L300-L301

@krfricke I am tagging you, as you authored both the PopulationBasedTrainingReplay and https://github.com/ray-project/ray/commit/603accf1c28fc08f8d0ab5351777bba288ab3df0

**Comment by krfricke** [comment]
Thanks @yorickvanzweeden, I'll fix this soon. If you want to you can also file a PR (the only thing to do is to remove the outdated argument from the call to `stop_trial`)

**Comment by yorickvanzweeden** [comment]
@krfricke Made a PR (#16564)
