### ISSUE TITLE
[RFC] Ray Client Scalability Envelope and Optimizations

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#16593]
This RFC proposes 2 things:

**Scalability Envelope for multi-node Ray Client**
Currently we have a scalability envelope for `ray.init()` that runs every release test. With new changes to the Ray API, can we also have a scalability envelope for multi-node Ray Client? This will help us identify any future regressions or performance degradations with Ray Client and will make sure that it is able to scale.

**Optimizing Ray Client performance**
Once we identify areas of poor performance with Ray Client, we should optimize them. Currently @matthewdeng is already seeing issues where `ray.put(...)` with large objects is incredibly slow with Ray Client. This makes workflows that involve large datasets (like with Modin for example) infeasible with Ray Client.

cc @wuisawesome @ericl @AmeerHajAli @mwtian @ijrsvt

**Comment by wuisawesome** [comment]
Sounds reasonable, I guess this is mostly a question of what dimensions should it include.

I'd propose we start with the dimensions in the single node scalability envelope, but we may have to bump the values down for ray client.

**Comment by amogkam** [comment]
The main issue that we are running into right now is the object store benchmark.

**Comment by wuisawesome** [comment]
Is it the `ray.put` that's hanging? That should be caught in the single node benchmark too.

**Comment by amogkam** [comment]
Ah ok, yes it’s the ray.put that’s hanging.

**Comment by AmeerHajAli** [comment]
cc @mwtian.
This is btw unfortunate to see. In general we should strive to have the same performance/experience with ray client as with ray init.
