### ISSUE TITLE
[RLlib] rl algorithms hangs forever when called for training 

### ISSUE THREAD

**Issue by oroojlooy** [ray-project/ray#16618]
### What is the problem?
ray just hangs forever when I call `DQN` to train `CartPole-v0`. I have the same issue with `PPO` and `A2C`. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 1.3.0
tensorflow: 2.5.0
python: 3.6.8
OS: Red Hat 7.6 

### Reproduction (REQUIRED)
Here is the code to produce:

```
import ray
import gym 

ray.init()
from ray.rllib.agents.dqn import DQNTrainer, DEFAULT_CONFIG
config = DEFAULT_CONFIG.copy()

agent = DQNTrainer(config, 'CartPole-v0')
for i in range(10000):
    result = agent.train()

```

And here is what I get: 

```
2021-06-22 16:24:42,888	INFO services.py:1269 -- View the Ray dashboard at http://127.0.0.1:8265
2021-06-22 16:24:48,775 [WARNI]  From /home/anaconda3/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-06-22 16:24:49,113 [WARNI]  From /home/anaconda3/lib/python3.6/site-packages/tensorflow_probability/python/internal/variadic_reduce.py:115: calling function (from tensorflow.python.eager.def_function) with experimental_compile is deprecated and will be removed in a future version.
Instructions for updating:
experimental_compile is deprecated, use jit_compile instead
2021-06-22 16:24:50,104	INFO trainer.py:669 -- Tip: set framework=tfe or the --eager flag to enable TensorFlow eager execution
2021-06-22 16:24:50,105	INFO trainer.py:696 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-06-22 16:24:55,387	WARNING deprecation.py:34 -- DeprecationWarning: `SampleBatch.data[..]` has been deprecated. Use `SampleBatch[..]` instead. This will raise an error in the future!

```

**Comment by mvindiola1** [comment]
Have you tried printing the results on each iteration?

**Comment by oroojlooy** [comment]
> Have you tried printing the results on each iteration?

No, I do not print anything for the run. I use the automatic result generator, `results.json` and `progress.csv`. Some of the generated results include some values and some are empty.
I ran 10 jobs in a same time, and some has executed and some not. Is there any limit on the number of jobs that can run in same time in a single machine? My machine has a Xeon with 80 cores. I thought is it powerful enough to handle those jobs.

**Comment by mvindiola1** [comment]
By run 19 jobs at the same time do you mean something roughly similar to: you opened 10 terminals and ran this script in each one? Or are you using tune and setting num_samples to 10?

**Comment by oroojlooy** [comment]
I mean something similar to having 10 different terminals and run one script at each. 

I did not check with small number of iterations since the actual env which I am using is quite complex and needs several thousands of iterations. 
I'll run with smaller number of iterations to see if that helps.

**Comment by mvindiola1** [comment]
When you run in 10 terminals what the ray.init() line is doing is starting up a ray head node and 80 ray workers for each of those 10 processes. You will actually have 10 seperate instances of the ray server components and 800 ray workers running on your machine.

You probably want to try using tune.run instead.

**Comment by oroojlooy** [comment]
I see. 
Can I run `ray.tune` on the parameters of the environment? I mean `env_config` dictionary which is part of the algorithm's `config`?

**Comment by mvindiola1** [comment]
Yes. Here is an example you can look at that uses tune with the options you mentioned.
https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py

**Comment by oroojlooy** [comment]
Thanks for the link!

In the provided example, if I change it to: 

```
    config = {
        "env": SimpleCorridor,  # or "corridor" if registered above
        "env_config": {
            **"corridor_length": [5, 15, 25],**
        },
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        "num_gpus": int(os.environ.get("RLLIB_NUM_GPUS", "0")),
        "model": {
            "custom_model": "my_model",
            "vf_share_layers": True,
        },
        "lr": grid_search([1e-2, 1e-4, 1e-6]),  # try different lrs
        "num_workers": 1,  # parallelism
        "framework": args.framework,
    }

```
does it consider three version of the env too?

**Comment by mvindiola1** [comment]
No if you wanted to do that you could do for example:
```
"env_config": {
            "corridor_length": tune.grid_search([5, 15, 25]),
        },
```

This would create 3 experiments one where corridor_length=5 a second with it equal to 15 etc.

On the other hand with
`"corridor_length": tune.choice([5, 15, 25]),`
would randomly choose one for each of the independent trial runs if you requested for example 10 trials with tune.run(num_samples=10)

**Comment by oroojlooy** [comment]
Thanks for the example!
