### ISSUE TITLE
[kubernetes][operator][autoscaler][core?] Support syncing files down when using K8s operator

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#16615]
### Describe your feature request

The deprecated K8s cluster launcher supported syncing files from cluster to laptop, but the operator does not.

We may want a Ray-internal system for syncing files/directories down and between nodes.

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by DmitriGekhtman** [comment]
From discussion thread: https://discuss.ray.io/t/syncing-files-to-and-from-ray-cluster/2566/2

**Comment by DmitriGekhtman** [comment]
cc @richardliaw for potential tune implications -- i actually think tune's rsync already doesn't work for the k8s operator because the head pod doesn't (and shouldn't) have pods/exec rbac permission

**Comment by richardliaw** [comment]
In this case user needs to rely on S3.

**Comment by DmitriGekhtman** [comment]
Also possible to work out a solution involving `kubectl exec`.

**Comment by DmitriGekhtman** [comment]
or `kubectl cp`
