### ISSUE TITLE
[Core] Replace plasma with new version

### ISSUE THREAD

**Issue by xunzhang** [ray-project/ray#16617]
Hi,
I noticed that ray holds its own implementation of plasma. Is there specific implementation of plasma need to be used in Ray? Otherwise, is that possible to replace the plasma with the version in apache arrow(https://github.com/apache/arrow/tree/master/cpp/src/plasma)? Thanks.

**Comment by rkooo567** [comment]
Yes! Ray back ported the plasma store for further optimization. Unfortunately, it is currently not possible to change the different version of plasma store

**Comment by xunzhang** [comment]
I see, thanks. Can you briefly describe the specialization of plasma used by Ray?

**Comment by rkooo567** [comment]
Plasma store was originally developed for Ray to support zero-copy distributed object store. Right now, it is used to provide shared memory distributed object store, but it doesn't use the Arrow format for storing data unlike the original design.

**Comment by xunzhang** [comment]
I see, thanks!
