### ISSUE TITLE
[RFC] Beam Runner on Ray?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#16622]
### Intro

We are thinking of implementing a Beam Runner on top of Ray.

This may be on top of Dask/Ray or Spark/Ray, or even a separate intermediate abstraction.

### Comment from previous thread:

Out of curiosity, have we considered implementing an Apache Beam Runner on top of Ray Streaming as part of this plan? At a high level, I see it providing the following benefits:

1. Exposes a unified, cross-language (Java, Python, Scala, Beam SQL, etc.) API to clients for writing  streaming/batch data processing pipelines running on Ray.
2. Clarify exactly what common capabilities are supported by Ray Streaming versus other platforms (including Flink). See https://beam.apache.org/documentation/runners/capability-matrix/ for an example of the high-level capability types that writing a Beam Pipeline Runner would force its implementor to think about (it looks like we've already done a similar exercise in the Ray Streaming API doc at https://docs.google.com/document/d/1bwTAtxszssTwuT2AJl7z2AhaUzO2bui645jSAhebFCA/edit).
3. Allow existing Beam users to port their existing pipelines over to the Ray execution platform without having to completely rewrite their data processing pipeline code. This in turn facilitates more users naturally experimenting with Ray Streaming, testing its capabilities, discovering which use cases could use improvement, and which use cases it is best suited to handle.
4. Inherit support for all sources/sinks currently provided as Beam IO implementations (see https://beam.apache.org/releases/javadoc/2.19.0/org/apache/beam/sdk/io/).

If this is something that we're interested in pursuing, then I'd be happy to start contributing associated design docs, tasks, and code.

Additional Information:
1. How Beam Runs on Top of Flink: https://flink.apache.org/ecosystem/2020/02/22/apache-beam-how-beam-runs-on-top-of-flink.html
2. Why Apache Beam? A Google Perspective: https://cloud.google.com/blog/products/gcp/why-apache-beam-a-google-perspective
3. Apache Beam vs. Direct Spark/Flink API: https://stackoverflow.com/questions/43581127/what-are-the-benefits-of-apache-beam-over-spark-flink-for-batch-processing/43672838#43672838
4. Implementing Beam Pipeline Runners: https://beam.apache.org/contribute/runner-guide/
5. Streaming Systems (book largely explaining the underlying streaming model that Beam serves as a reference implementation of): http://shop.oreilly.com/product/0636920073994.do

_Originally posted by @pdames in https://github.com/ray-project/ray/issues/6184#issuecomment-595978839_

**Comment by pdames** [comment]
Thanks for creating this dedicated issue, Richard!

**Comment by pdames** [comment]
The proposed requirements for the initial Ray Beam Runner deliverable are available for review at: https://docs.google.com/document/d/1O-Dv1-bLGd-Tl6AOeHuVcm7WF0oGK8KlUNEeF66Q0O8.

**Comment by richardliaw** [comment]
Development for this is happening on this repo: https://github.com/ray-project/ray_beam_runner

**Comment by heinrichreimer** [comment]
The mentioned repo looks abandoned. What's the state of using Ray with Apache Beam?
