### ISSUE TITLE
[RFC] API to list named actors and placement groups

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#16623]
In the Ray Serve controller, we currently need to checkpoint the names of all of the actors and placement groups in the system to avoid leaking actors in failure scenarios. This logic could be simplified if we had the ability to query all named actors and placement groups in the system (or a namespace) instead. This would allow Serve to recover the current state of the system by querying the GCS and only checkpoint the goal state, rather than attempting to maintain checkpoints for both the current and goal states.

Proposed API:
```python
ray.list_named_actors() -> List[str]
ray.list_named_placement_groups() -> List[str]
```

This would return a list of the currently active actor and PG names in the current namespace. I'm not too opinionated on the exact API naming here. The implementation for this should be very simple - just a simple RPC to the GCS.

**Comment by edoakes** [comment]
I believe the former used to be possible via `ray.actors()` but that was deprecated (rightfully).

**Comment by ericl** [comment]
Makes sense to me. Do we also need the ability to list namespaces?

Another question is whether we can put it in a sub-module rather than top-level ray.

**Comment by edoakes** [comment]
I don't currently know of a use case for listing namespaces so IMO we can omit it for now.

I'm good with putting it in a submodule bu not sure if any of the existing ones we currently have make sense. We could throw it into `util` but it's really a core functionality. We could also consider putting this it in experimental and then promoting it in the future.

@pcmoritz do you have any thoughts/preferences here?
