### ISSUE TITLE
[core] namespace being overwritten by anonymous namespace

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#16630]
### What is the problem?
Namespace doesn't seem to be set when using Anyscale Connect.

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Python:** 3.7.10
**Ray:** Latest Wheel

### Reproduction (REQUIRED)
I ran the following script in an Anyscale Project Cluster:
```python
import ray

ray.client("anyscale://").namespace("banana").connect()
current_namespace = ray.get_runtime_context().namespace
print(f"Current Namespace: {current_namespace}")
```
Output:
```
2021-06-22 18:27:13,948 INFO worker.py:734 -- Connecting to existing Ray cluster at address: 172.31.49.66:6379
Current Namespace: 3e135042-88ba-4327-82ca-fdd6b2d631db
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
@matthewdeng does this happen without `"anyscale://"`?

**Comment by matthewdeng** [comment]
It seems specific to `"anyscale://"`! I ran the following locally without a cluster up:

```python
import ray

ray.client().namespace("banana").connect()
current_namespace = ray.get_runtime_context().namespace
print(f"Current Namespace: {current_namespace}")
```

```
2021-06-22 20:41:21,375	INFO services.py:1315 -- View the Ray dashboard at http://127.0.0.1:8265
Current Namespace: banana
```

I also tried running the following locally (after calling `ray start --head`) and on the Anyscale head node:
```python
import ray
  
ray.client("localhost:10001").namespace("banana").connect()
current_namespace = ray.get_runtime_context().namespace
print(f"Current Namespace: {current_namespace}")
```
Both give the same result with another error(?):
```
Current Namespace: banana
Error in sys.excepthook:

Original exception was:
```

**Comment by ijrsvt** [comment]
@matthewdeng I'm not too sure about the `sys.excepthook` issue, but let me open this up on `anyscale`?

**Comment by ijrsvt** [comment]
@matthewdeng I am not able to repro this:
```
In [1]: import ray; ray.client("anyscale://abc").namespace("abc").connect()


In [2]: ray.get_runtime_context().namespace
Out[2]: 'abc'
```

Versions are the latest:
```
ubuntu@ip-172-31-47-243:~/$ anyscale --version
0.4.5
ubuntu@ip-172-31-47-243:~/$ ray --version
ray, version 1.4.0
```
