### ISSUE TITLE
Memory Leak on CARLA Environment?

### ISSUE THREAD

**Issue by bhairavmehta95** [ray-project/ray#1663]
### System information
- **Linux Ubuntu 16.04, 256GB of GPU Memory**
- **Ray installed from Source**:
- **Ray version 0.3.1**:
- **Python version 3.5.2**:
- **Exact command to reproduce: (inside examples/carla) python env.py**:

### Describe the problem
I am running the CARLA environment with 10 PPO workers, and throughout my runs, the GPU memory usage seems to be steadily increasing. I suspect this is due to the resetted servers not being fully killed, but I wanted to see if anyone else has had a similar issue.

### Source code / logs
I am rendering the CARLA game sessions off screen on a server, with this command:

```python
self.server_port = random.randint(10000, 60000)
gpu_num = random.randint(0, 3)
self.server_process = subprocess.Popen('DISPLAY=:8 vglrun -d :7.{} {} {} -windowed \
     -ResX=400 -ResY=300 -carla-server -carla-world-port={} -fps=20 \ 
     -carla-no-hud'.format(gpu_num, SERVER_BINARY, self.config['server_map'], self.server_port), \
      preexec_fn=os.setsid, stdout=open('logs/CARLA_LOG_{}.log'.format(self.server_port), "w"), shell=True)
live_carla_processes.add(os.getpgid(self.server_process.pid))
```

**Comment by ericl** [comment]
Hmm, do you still see the old processes in nvidia-smi?

**Comment by bhairavmehta95** [comment]
I don't see them there but if I go into a process manager and search for a port that I know has been closed (i.e puthin client says that it's been closed because server connection timed out / refused / closed), I can still find the process there.

**Comment by ericl** [comment]
It's possible the main process never reaped the child processes (i.e.
called wait() on them) so they're still around as zombies. Weird that they
don't show in nvidia-smi but still use gpu memory though -- how do you tell
the usage of these processes?

**Comment by bhairavmehta95** [comment]
I was watching the GPU Memory Usage through htop. This was the only thing I was running on the entire server, which caused me to believe the zombie processes are still somehow using the memory.
