### ISSUE TITLE
[ray cluster] Manual cluster setup issue regarding ports

### ISSUE THREAD

**Issue by chanshing** [ray-project/ray#16643]
This is very related to https://github.com/ray-project/ray/issues/7632

I have my own minicluster of nodes so I had to setup ray cluster manually. The standard instructions didn't work for me. What used to work was to manually specify a bunch of ports, as suggested here https://github.com/ray-project/ray/issues/7632:

```bash
# On the head node
ray start --head --port=6379 \
--redis-shard-ports=6380 \
--node-manager-port=12345 \
--object-manager-port=12346 \
--gcs-server-port=10000 \
--min-worker-port=10001 \
--max-worker-port=10999

# On worker node(s)
ray start --address='10.12.0.15:6379' --redis-password='5241590000000000' \
--node-manager-port=12345 \
--object-manager-port=12346
```

Ok, so this used to work for me at least until 0.8.7. After a long time, I finally decided to update to 1.4.0. But after I did that, the first command on the head node gave me:

```bash
 f"Ray component {comp} is trying to use "
ValueError: Ray component worker_ports is trying to use a port number 10001 that is used by other components.
Port information: {'gcs': [6379], 'object_manager': [12346], 'node_manager': [12345], 'gcs_server': [10000], 'client_server': [10001], 'dashboard': [8265], 'dashboard_agent': [63626], 'metrics_export': [59840], 'redis_shards': ['6380'], 'worker_ports': [10001, 10002, 10003, ..., 10999]}
``` 

Luckily, the error message was very helpful. What seems to have happened is that there was a new `client_server` port recently introduced, which in my case is using port 10001. I managed to solve my issue by using `--min-worker-port=10002` so that they don't collide. So my questions are:

1. How is this `client_server` port picking the port to be used? Is it `gcs_server` + 1?
2. Can this port be manually specified, as is the case for the other ports?
3. Maybe this port requirement should also be mentioned in https://docs.ray.io/en/releases-1.4.0/configure.html?highlight=ports#ports-configurations?

The reason I ask all this is that I cannot ask IT to just open all the ports for me. They want to keep the list of open ports as short as possible.

**Comment by richardliaw** [comment]
Hey @chanshing thanks a bunch for this comprehensive writeup! 

@rkooo567 can you help take this? It looks like there's just a couple fixes on the documentation that should be applied.

**Comment by rkooo567** [comment]
Hey @ijrsvt @AmeerHajAli can you guys update the port documentation to take into account of the client server usage?

**Comment by ijrsvt** [comment]
The `client_server_port` is hardcoded to `10001`. 

It can be set with `--ray-client-server-port=XXXX`
