### ISSUE TITLE
surprising singleton behavior

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1665]
Consider following, np.split is always a list of objects, but after going through Ray, the result is either a single Ray object or a list of Ray objects depending on whether `shards` is equal to 1

```
@ray.method(num_return_vals=shards)
        def compute_gradients(self, *weights):
            return np.split(array, shards)
```

**Comment by richardliaw** [comment]
Yeah this was a little odd - I'm not totally sure what the right thing to do here is. 

One possibility is to force the semantics of `method` to always return a list of objects, and also enforce that the wrapped function also returns a list?  In which case we could consider renaming `ray.method` into `ray.split`.

Thoughts?
