### ISSUE TITLE
[flaky-test] Race condition in set removing callback.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#16688]
### What is the problem?

Right now, contained_in_objects are reported by pushing a message WaitForRefRemoved. 

But the main thread is not waiting for the return of this one which caused a race condition.

Think about this flow:

1. task return to the driver
2. driver deserialize the obj and notice the nested object is not contained, decrease the local references 
3. the references now equals 0 which will trigger a deletion
4. wait for ref removed now got received by the driver which including the contained in objs [(code)](https://github.com/ray-project/ray/blob/33e319e9d76513ca18eec4968c15019e97cd271d/src/ray/core_worker/reference_count.cc#L917)

If the ordering is 1 -> 4 -> 2 -> 3, it should be good.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

`pytest --count=100 ./ray/tests/test_reference_counting_2.py::test_return_object_ref -svx`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by iycheng** [comment]
@rkooo567 I have a question for contained_in_objects, will this include ids contained in nested ids which is still under resolving?

**Comment by rkooo567** [comment]
oh interesting. Is it the root cause of the flaky test? I think for this question @stephanie-wang can answer better than me

**Comment by iycheng** [comment]
Yes, that's my speculation. But I need some knowledge from experts here to confirm. @stephanie-wang do you think what I mentioned makes sense?

**Comment by kfstorm** [comment]
@iycheng Could you put some links to code blocks here? I don't quite understand the issue.

**Comment by iycheng** [comment]
Since this is an async call, we can just comment on this line to reproduce.

https://github.com/ray-project/ray/blob/33e319e9d76513ca18eec4968c15019e97cd271d/src/ray/core_worker/reference_count.cc#L855-L856

Basically, it's about whether WaitForRefRemoved got received by the caller, before or after task returns.

If `WaitForRefRemoved` received after tasks returns, it'll have log like this:
```
  35 [2021-07-13 22:04:31,037 D 20845 20185] task_manager.cc:244: Task c361e4b8895ba43cffffffffffffffffffffffff01000000 returned direct object c361e4b8895ba43cffffffffffffffffffffffff0100000001000000, now has 1 plasma returns in scope
  36 [2021-07-13 22:04:31,037 D 20845 20185] task_manager.cc:250: Task c361e4b8895ba43cffffffffffffffffffffffff01000000 now has 0 plasma returns in scope
  37 [2021-07-13 22:04:31,037 D 20845 20845] core_worker.cc:1215: Plasma GET timeout -1
  38 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:221: Add local reference 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000
  39 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:222: REF 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000 borrowers: 0 local_ref_count: 1 submitted_count: 0 contained_in_owned: 0 contained_in_borrowed: NIL_ID contains: 0 lineage_ref_count: 0
  40 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:99: Adding borrowed object 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000
  41 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:241: Remove local reference 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000
  42 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:242: REF 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000 borrowers: 0 local_ref_count: 0 submitted_count: 0 contained_in_owned: 0 contained_in_borrowed: NIL_ID contains: 0 lineage_ref_count: 0
  43 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:439: Attempting to delete object 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000
  44 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:445: REF 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000 borrowers: 0 local_ref_count: 0 submitted_count: 0 contained_in_owned: 0 contained_in_borrowed: NIL_ID contains: 0 lineage_ref_count: 0
  45 [2021-07-13 22:04:31,037 D 20845 20845] reference_count.cc:483: Deleting Reference to object 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000
  46 [2021-07-13 22:04:31,046 I 20845 20185] reference_count.cc:1079: Tried to report locality data for an object 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. The object has probably already been freed.
  47 [2021-07-13 22:04:31,046 D 20845 20185] future_resolver.cc:80: Object not returned directly in GetObjectStatus reply, 6693814a2c6a06e2ffffffffffffffffffffffff0100000001000000 will have to be fetched from Plasma
```

Otherwise, it'll look like this
```
  44 [2021-07-13 22:04:24,314 D 20845 19905] task_manager.cc:188: Task return object 00c4b50fa56034e6ffffffffffffffffffffffff0100000001000000 has size 221
  45 [2021-07-13 22:04:24,314 D 20845 19905] task_manager.cc:244: Task 00c4b50fa56034e6ffffffffffffffffffffffff01000000 returned direct object 00c4b50fa56034e6ffffffffffffffffffffffff0100000001000000, now has 1 plasma returns in scope
  46 [2021-07-13 22:04:24,314 D 20845 19905] task_manager.cc:250: Task 00c4b50fa56034e6ffffffffffffffffffffffff01000000 now has 0 plasma returns in scope
  47 [2021-07-13 22:04:24,314 D 20845 20845] core_worker.cc:1215: Plasma GET timeout -1
  48 [2021-07-13 22:04:24,314 D 20845 20845] reference_count.cc:221: Add local reference d888d48d82a65b44ffffffffffffffffffffffff0100000001000000
  49 [2021-07-13 22:04:24,314 D 20845 20845] reference_count.cc:222: REF d888d48d82a65b44ffffffffffffffffffffffff0100000001000000 borrowers: 0 local_ref_count: 1 submitted_count: 0 contained_in_owned: 1 contained_in_borrowed: NIL_ID contains: 0 lineage_ref_count: 0
  50 [2021-07-13 22:04:24,314 D 20845 20845] reference_count.cc:99: Adding borrowed object d888d48d82a65b44ffffffffffffffffffffffff0100000001000000
  51 [2021-07-13 22:04:24,315 D 20845 20845] reference_count.cc:241: Remove local reference d888d48d82a65b44ffffffffffffffffffffffff0100000001000000
  52 [2021-07-13 22:04:24,315 D 20845 20845] reference_count.cc:242: REF d888d48d82a65b44ffffffffffffffffffffffff0100000001000000 borrowers: 0 local_ref_count: 0 submitted_count: 0 contained_in_owned: 1 contained_in_borrowed: NIL_ID contains: 0 lineage_ref_count: 0
  53 [2021-07-13 22:04:24,321 D 20845 19905] future_resolver.cc:80: Object not returned directly in GetObjectStatus reply, d888d48d82a65b44ffffffffffffffffffffffff0100000001000000 will have to be fetched from Plasma
  54 [2021-07-13 22:04:24,327 D 20845 20845] reference_count.cc:167: Adding owned object ffffffffffffffffffffffffffffffffffffffff0100000046060000
```


So for the first one it got deleted (WaitForRefRemoved received after task return)

For the second one, it's ok since it received WaitForRefRemoved


My guess is that we should return this info through return instead of WaitForRefRemoved. @stephanie-wang do you think it makes sense?

**Comment by stephanie-wang** [comment]
After syncing offline with @iycheng, it looks like the issue is actually with the test itself.

At [this line](https://github.com/ray-project/ray/blob/33e319e9d76513ca18eec4968c15019e97cd271d/python/ray/tests/test_reference_counting_2.py#L125), the inner `ObjectRef` is no longer in scope at the borrower, and the borrower tries to access the object with the binary ID, which is not supported.

Sometimes the test passes, just because the WaitForRefRemoved RPC notifies the borrower that the inner `ObjectRef` is actually contained in the outer `ObjectRef`, which happens to add the inner `ObjectRef` entry back to the table.
