### ISSUE TITLE
[raysgd] Placement group support in RaySGD

### ISSUE THREAD

**Issue by HuangLED** [ray-project/ray#16682]
We would like to request RaySGD to have placement group support. 

More specifically, when starting a RaySGD trainer, we would like to assign resource allocations (num_workers, maybe other things as well) to a set of placement groups first, then RaySGD arrange training workers accordingly based on the placement-group specifications. 

One particular toy example would go like this: Let say there are 3 nodes in the cluster, we create three placement groups (P1, P2 and P3), one for each node based on IPs.    P1, P2 and P3 each initiates different number of workers (or the same number of workers).  The current behavior of RaySGD is that it allocate workers using a greedy algorithm. 

Happy to help if there is anything I can assist in this effort. 

Related discussions: 
https://discuss.ray.io/t/placement-group-support-in-raysgd/2530

@richardliaw

**Comment by amogkam** [comment]
Hey @HuangLED thanks for making the feature request! We are currently working on this implementation right now.

But a quick question: what default strategy do you think makes sense? Also why would you need multiple placement groups?

**Comment by HuangLED** [comment]
Thanks Amog, @amogkam .  Let me explain the difficulty first, then throw out what default strategy I think work for my use case. 

[Issue]
My use case is to train GNN model.  Let us say we have ray cluster with 10 nodes. In a distributed GNN setting, we partition graph into 10 partitions and load them into memory (Graph Sampling service, memory intensive) on each node, by using ip-based placement group scheduling. Now each node has one actor running graph service.  Let us say each machine has 64 cores, then now each node has 63 idle cores.  Next, we want spin off training task with 2 training process each node, in total 20 workers. The reason to spread out training process, is that we want to colocate them to take advantage of graph data being local (at least for each node). 

In current RaySGD setup, all the 20 training worker gets greedily allocated to the first node.  That makes all the other 9 graph service purely go through network for the sampled graph data. 

[Strategy that works in short term] 

If we can have a strategy saying **"evenly distribute all the 20 workers across the cluster"**. That should work in the short term. Though that would only work well if all the machines has exactly the SAME hardware setup. 

[Ideal Strategy that ultimately works]

We are able to define 10 ip-based placement groups for training purpose, and for each placement we define num_workers/use_gpu etc.

**Comment by amogkam** [comment]
Thanks for the thorough description! The use case makes a lot of sense, and we should be able to support this fully.

Just want to point out that neither strategy actually require multiple placement groups.

For the short term fix- this can be done by using a single placement group with a bundle for each worker and SPREAD strategy.

For the ideal strategy- this still uses a single placement group, but with a bundle per node and a STRICT_SPREAD strategy.
