### ISSUE TITLE
[rllib] Callback on_episode_end with MultiAgentEnv not returning empty dict for last_info

### ISSUE THREAD

**Issue by akelloway** [ray-project/ray#16683]
### What is the problem?
With a MultiAgentEnv and for a on_episode_end custom callback (at least, I have not tested other callbacks or Envs) I am expecting to see the last info dictionary for each agent but I am seeing only empty dictionaries for each agent. 

I think I have tracked down the issue to [this line](https://github.com/ray-project/ray/blob/9b17c35bee6a28b4b09ede36fdb9fdced3929f55/rllib/env/base_env.py#L473) which I think should be:
`infos = self.last_infos` 
but I am not 100% sure of that. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.8.3, Windows, TF 2.5, Numpy 1.19.5 
### Reproduction (REQUIRED)
Simple reproducing script where I edited the BasicMultiAgent from examples to add content to the info dictionaries and a statement to print what we expect to see in the on_episode_end callback for validation.

```python
import gym
from ray.rllib.env.multi_agent_env import MultiAgentEnv
from ray.rllib.examples.env.mock_env import MockEnv
import ray
from ray import tune
from ray.tune.registry import register_env
from typing import Dict
from ray.rllib.env import BaseEnv
from ray.rllib.policy import Policy
from ray.rllib.evaluation import MultiAgentEpisode, RolloutWorker
from ray.rllib.agents.callbacks import DefaultCallbacks

class MyCallback(DefaultCallbacks):
    def on_episode_end(self, worker: RolloutWorker, base_env: BaseEnv,
                       policies: Dict[str, Policy], episode: MultiAgentEpisode,
                       **kwargs):      
        print("INSIDE CALLBACK: ", episode._agent_to_last_info)

class MyBasic(MultiAgentEnv):
    def __init__(self, num):
        self.agents = [MockEnv(25) for _ in range(num)]
        self.dones = set()
        self.observation_space = gym.spaces.Discrete(2)
        self.action_space = gym.spaces.Discrete(2)
        self.resetted = False
    def reset(self):
        self.resetted = True
        self.dones = set()
        return {i: a.reset() for i, a in enumerate(self.agents)}
    def step(self, action_dict):
        obs, rew, done, info = {}, {}, {}, {}
        for i, action in action_dict.items():
            obs[i], rew[i], done[i], info[i] = self.agents[i].step(action)
            info[i] = {"MY TESTER" : 1.0}
            if done[i]:
                self.dones.add(i)
        done["__all__"] = len(self.dones) == len(self.agents)
        if done["__all__"]:
             print("INSIDE ENV: ", info)
        return obs, rew, done, info
register_env('basic', lambda env_config: MyBasic(4))
config = {
    "env": 'basic',
    'callbacks': MyCallback
}
ray.init(address='auto', _redis_password='5241590000000000')
results = tune.run("PPO", config=config, stop = {"training_iteration" : 2})
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mvindiola1** [comment]
@akelloway, Which version of ray are you using? Nightly?

@krfricke, I think the regression was introduced in this commit:

 https://github.com/ray-project/ray/commit/be6db0648546f51d16dba4ccc6a8ddcff6d10400#diff-1554f1224e7fdc10fdf8875954f0dafdeaf4a05c411fefd6e557edc03e7565b1

**Comment by akelloway** [comment]
@mvindiola1 I am using the Nightly version. 

I agree with you that it is likely also causing that other issue for the on_episode_step callback since I think both make a call to BaseEnv.poll

**Comment by mvindiola1** [comment]
@akelloway,

I think this should fix it for you:

```python
        # If episode is done, release everything we have.
        if dones["__all__"]:
            rewards = self.last_rewards
            self.last_rewards = {}
            dones = self.last_dones
            self.last_dones = {}
            self.last_obs = {}
            infos = self.last_infos
            self.last_infos = {}
        # Only release those agents' rewards/dones/infos, whose
        # observations we have.
        else:
            for ag in observations.keys():
                if ag in self.last_rewards:
                    rewards[ag] = self.last_rewards[ag]
                    del self.last_rewards[ag]
                if ag in self.last_dones:
                    dones[ag] = self.last_dones[ag]
                    del self.last_dones[ag]
                if ag in self.last_infos:
                    infos[ag] = self.last_infos[ag]
                    del self.last_infos[ag]
```

**Comment by akelloway** [comment]
@mvindiola1 
Thanks - that looks like a more robust fix than mine. Do you want to the submit the fix?

**Comment by mvindiola1** [comment]
@krfricke is assigned to the task. I am happy to submit the PR if he wants me to.

**Comment by krfricke** [comment]
Hi @mvindiola1, it would be great if you could create and submit the PR!

**Comment by krfricke** [comment]
I went ahead and created the PR

**Comment by mvindiola1** [comment]
@krfricke,  Thanks for letting me know. I was going to submit one tonight.

I wrote a unit test for the issue if you want to add it to your PR.

https://github.com/mvindiola1/ray/commit/08a899838e75aaca054f472b72197ed29bfd7a90
