### ISSUE TITLE
[DataFrame] ray.dataframe does not have any read functions

### ISSUE THREAD

**Issue by MadScientistKris** [ray-project/ray#1670]

**Comment by tobycheese** [comment]
I guess it's not in the release yet. But it would have been nice if the [blog](https://rise.cs.berkeley.edu/blog/pandas-on-ray/) post would mention that building from trunk is needed.

As a site note, I was unsuccessful doing just that on linux, when building I get

_No such file or directory: './ray/pyarrow_files/pyarrow'_

**Comment by robertnishihara** [comment]
Good point, it's only mentioned at the very end of the blog post, but we should update the blog post.

For right now you an build from source or try installing the latest wheel via a command like

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.3.1-cp36-cp36m-manylinux1_x86_64.whl
```

Depending on your OS and Python version, you will need to substitute a wheel name from https://pypi.python.org/pypi/ray/0.3.1.

@tobycheese if you're running into compilation issues, want to post a separate issue with the full error message?

cc @devin-petersohn

**Comment by MadScientistKris** [comment]
@robertnishihara  Awesome, looking forward to a more updated version of release.

**Comment by devin-petersohn** [comment]
@tobycheese Thanks for the feedback! I realize not everyone reads the blog post to the end so I put a note at the top so it's easier to see.

**Comment by robertnishihara** [comment]
Sounds good, looks like there's an issue with the latest wheels #1597 (should be fixed soon), but anyway building from source should work.

**Comment by devin-petersohn** [comment]
@ahialy Did you build Ray from source? It looks like you may have built from pip.

Follow the directions at: http://ray.readthedocs.io/en/latest/index.html to build from source for your OS. Let me know if it doesn't work then!

**Comment by n-raghu** [comment]
Hi
I built ray from source using the link provided by @devin-petersohn .
'read_csv' works for me, however, I could not find 'read_table' or 'read_sql_query' which is available in native pandas package.
I'm trying to read data from SQL Server or MySQL instead of CSV file.
Could you provide me some pointers on this?

**Comment by devin-petersohn** [comment]
@n-raghu Thanks for your question. Currently `read_table` and `read_sql_query` are not implemented in Pandas on Ray. In our recent [blog](https://rise.cs.berkeley.edu/blog/pandas-on-ray/) post, we explained that the project is still early-stage and we are still in the process of implementing everything. If you would like to make a feature request, please open another issue.

**Comment by robertnishihara** [comment]
The "latest" wheels should be working again.

**Comment by tobycheese** [comment]
@robertnishihara: Building from source now works for me, the hint [here](https://github.com/ray-project/ray/issues/1692) helped. Thanks!

**Comment by marnixkoops** [comment]
This also seems to solve the issue:
data = pd.dataframe.pd.read_csv('data.csv')

**Comment by devin-petersohn** [comment]
@marnixkoops see https://github.com/ray-project/ray/issues/1706#issuecomment-373084365

**Comment by devin-petersohn** [comment]
Closing as the newest Ray release has this, so you no longer need to build from source. Please open a new issue if you are still having trouble with this.
