### ISSUE TITLE
[Dashboard] [Logging] Write CPU, GPU, RAM usage per node to a log file

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#16711]
### Describe your feature request

The dashboard supports viewing CPU, GPU, and RAM usage per task over time, but there is no easy way to write this to a log file.  Ray should provide some API to support this.

**Comment by architkulkarni** [comment]
unstale

**Comment by architkulkarni** [comment]
unstale

**Comment by scottsun94** [comment]
One question: "CPU, GPU, and RAM usage per task over time" This is referring to physical machine usage per Ray task over time?

**Comment by architkulkarni** [comment]
@scottsun94 I think I might have meant to write "node" instead of task.  This issue just referring to the physical machine usage reported in the dashboard, or more generally anything that's prominently visible in the dashboard UI but doesn't show up in any log file or doesn't have a programmatic way to access it, but perhaps this is already covered in the recent observability work.

**Comment by scottsun94** [comment]
Got it. I guess that fetching those time-series metrics programmatically has been covered by metrics export: https://docs.ray.io/en/latest/ray-observability/ray-metrics.html.
cc: @rkooo567 could confirm

**Comment by rkooo567** [comment]
Why do you want to write this to a log file? Isn't it sufficient you can see it from the the graph?

**Comment by architkulkarni** [comment]
At least one user requested this, but it was a while ago so I don't remember.  I imagine it's so you can parse the data using a program instead of scanning it visually.

**Comment by scottsun94** [comment]
Here is a request for this: https://github.com/ray-project/ray/issues/28496

**Comment by rkooo567** [comment]
Hmm sounds like this should be sufficient for this use case (if it is just for nodes); 

> Got it. I guess that fetching those time-series metrics programmatically has been covered by metrics export: https://docs.ray.io/en/latest/ray-observability/ray-metrics.html.

**Comment by rkooo567** [comment]
Close as duplicate https://github.com/ray-project/ray/issues/28496
