### ISSUE TITLE
[rllib] d4rl: offline data path error

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#16720]
### What is the problem?

I get the following error when reproducing cql.
```
gym.error.Error: Attempted to look up malformed environment ID: b'7/site-packages/ray/rllib/d4rl'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 1.4.0, python 3.7, tensorflow 2.5.0, linux

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Install rllib with python virtualenv and run the following:
```
rllib train -f rllib/tuned_examples/cql/halfcheetah-cql.yaml
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mvindiola1** [comment]
I think you forgot the file switch (-f) . Try

`rllib train -f rllib/tuned_examples/cql/halfcheetah-cql.yaml`

**Comment by juliusfrost** [comment]
> I think you forgot the file switch (-f) . Try
> 
> `rllib train -f rllib/tuned_examples/cql/halfcheetah-cql.yaml`

That was just my typo creating the issue, thanks for the catch.
