### ISSUE TITLE
[Serve] [Investigation] ServeHandle stuck when overloaded and requests dropped.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#16749]
### What is the problem?

I will try to find a more exact repro for this. Generally, this happens when the an load test overloaded the replicas and queue up a lot of requests. And then the load tests drop the http requests. You can observe that even in no active http connections, the http proxy is hanging and rejecting requests.

```
ubuntu@ip-172-30-0-109:~$ sudo env "PATH=$PATH" py-spy dump --pid 37932
Process 37932: ray::HTTPProxyActor
Python v3.7.7 (/home/ray/anaconda3/bin/python3.7)

Thread 0x7F452D190740 (active): "MainThread"
    main_loop (ray/worker.py:409)
    <module> (ray/workers/default_worker.py:197)
Thread 0x7F42AE7BF700 (idle): "ray_import_thread"
    wait (threading.py:300)
    wait (threading.py:552)
    _run (ray/_private/import_thread.py:75)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7F42AD6BD700 (active+gil): "AsyncIO Thread"
    add (_weakrefset.py:84)
    create_task (asyncio/base_events.py:404)
    ensure_future (asyncio/tasks.py:608)
    ensure_future (asyncio/tasks.py:617)
    <setcomp> (asyncio/tasks.py:387)
    wait (asyncio/tasks.py:387)
    assign_replica (ray/serve/router.py:189)
    assign_request (ray/serve/router.py:287)
    remote (ray/serve/handle.py:178)
    _send_request_to_handle (ray/serve/http_proxy.py:58)
    _fallback_to_prefix_router (ray/serve/http_proxy.py:303)
    __call__ (starlette/routing.py:609)
    __call__ (ray/serve/http_proxy.py:319)
    __call__ (uvicorn/middleware/proxy_headers.py:59)
    run_asgi (uvicorn/protocols/http/h11_impl.py:369)
    _run (asyncio/events.py:88)
    _run_once (asyncio/base_events.py:1786)
    run_forever (asyncio/base_events.py:541)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7F4502FFD700 (active)
```
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@simon-mo it's possible this is the same issue that causes `test_handle` to be flaky.

**Comment by edoakes** [comment]
Would be worth spending some time to try to fix it.
