### ISSUE TITLE
Memory requirement per trial in raytune 

### ISSUE THREAD

**Issue by vijaymobile123** [ray-project/ray#16767]
<tune>

I am not able to pass memory requirement per trial in raytune using ray 1.14.

Is `memory` removed from `resources_per_trial`  in the recent raytune release ? If so - How do we allocate memory per trial ?

**Comment by Yard1** [comment]
Hey @vijaymobile123, sorry for the late reply. You should be able to pass a memory requirement through `PlacementGroupFactory` like this: `resources_per_trial=PlacementGroupFactory[{"CPU": 1, "memory": 1000}]`. Feel free to reopen the issue if needed!
