### ISSUE TITLE
Issue in integrating  Ray Serve with Ray's Cross language programming capability 

### ISSUE THREAD

**Issue by SnehaHegde24** [ray-project/ray#16769]
We are able to execute ray serve end points doing multiple activities like process tracking , CRUD operations (sqllite) and file based activities .

The issue comes up , when we are trying to bring in the cross language programming capability within ray serve 

Use case is : We need to write few end points in ray serve  which has business logic to be used from java jar ( cross language programming capability) 

We had posted the same in discussion group :
https://discuss.ray.io/t/issue-in-integrating-ray-serve-with-rays-cross-language-programming/2698

Attaching here few screenshots which can give clarity on what we are trying to do 

<img width="690" alt="Screenshot 2021-06-30 at 10 51 56 AM" src="https://user-images.githubusercontent.com/16030241/123906142-41a8d100-d991-11eb-982b-d19e5df47977.png">

Error we are getting : 
![image](https://user-images.githubusercontent.com/16030241/123906195-5a18eb80-d991-11eb-8956-a97ffaa96b5b.png)

Any help or pointers is much appreciated .

**Comment by richardliaw** [comment]
@simon-mo can you assign some priority for this (and removing the triage label)? the triage label should be temporary at best -- thanks!

**Comment by simon-mo** [comment]
HI @SnehaHegde24 sorry about the late reply, Ray Serve should work with cross language calls without issue, can you reproduce it with just Ray tasks? i.e
```python
import ray
import sys
 
sys.path.append(".../Desktop/Cross_language_programming/ADD.jar")
ray.init(job_config=ray.job_config.JobConfig(code_search_path=sys.path))
  
@ray.remote
def add_num():
 add_function = ray.java_function("io.ray.demo.Math", "add")
 # Call the Java remote function.
 obj_ref3 = add_function.remote(1, 2)
 res = ray.get(obj_ref3)
 return res

 
print(ray.get(add_num.remote()))
```

**Comment by jadhav7777** [comment]
Hi @simon-mo getting error on trying this code.

![code1](https://user-images.githubusercontent.com/52358283/128016941-22c07305-b7f4-4157-86eb-b05484db8fa2.png)

Error:

![Error1](https://user-images.githubusercontent.com/52358283/128016971-86144fa9-6715-43ef-91a7-4db3b5119fba.png)

**Comment by jadhav7777** [comment]
> HI @SnehaHegde24 sorry about the late reply, Ray Serve should work with cross language calls without issue, can you reproduce it with just Ray tasks? i.e
> 
> ```python
> import ray
> import sys
>  
> sys.path.append(".../Desktop/Cross_language_programming/ADD.jar")
> ray.init(job_config=ray.job_config.JobConfig(code_search_path=sys.path))
>   
> @ray.remote
> def add_num():
>  add_function = ray.java_function("io.ray.demo.Math", "add")
>  # Call the Java remote function.
>  obj_ref3 = add_function.remote(1, 2)
>  res = ray.get(obj_ref3)
>  return res
> 
>  
> print(ray.get(add_num.remote()))
> ```

Hi @simon-mo  getting error on trying this code.

Could you help on this ?


![code1](https://user-images.githubusercontent.com/52358283/128020114-edf54889-65e8-44f1-bb7f-93623a460ac6.png)

Error:

![Error1](https://user-images.githubusercontent.com/52358283/128020148-747da9b7-c9f4-4f05-b051-6d738a571f28.png)

**Comment by SnehaHegde24** [comment]
Hi @simon-mo , 

We tried the above mentioned thing , and still are facing issues .
Could you help us on that .

Regards
Sneha

**Comment by simon-mo** [comment]
Hi sorry for the late reply, but the path should be the directory where jar lives, not the jar itself

**Comment by simon-mo** [comment]
Feel free to reopen if it is still an issue
