### ISSUE TITLE
Specifying which IP "ray start --head" listens on

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1677]
On AWS, `ray start --head` listens on `<ip>` where `<ip>` can be obtained through boto3 API.
On my MacBook, it listens on ip `192.168.128.226`, how do I get or set this IP?

What is this 192.168.128.226 address? Is it guaranteed to stay the same? Can I get it to listen at 127.0.0.1?

IE, in another process locally, `ray.init(redis_address='192.168.128.226:6379')` works, but `ray.init(redis_address='127.0.0.1:6379')` fails

**Comment by yaroslavvb** [comment]
OK, it looks like locally on Mac, I get this IP out of `import socket; socket.gethostbyname(socket.gethostname())`. Internets are saying this method is unreliable in that it can return 127.0.0.1

**Comment by robertnishihara** [comment]
You can pass in node_ip_address=“127.0.0.1” to ray.init. Does that work?
Also turning off internet should have the same effect.

**Comment by yaroslavvb** [comment]
The issue is not ip of ray node, but ip redis node. `ray start` creates redis server that listens on `192.168.128.226` and doesn't listen on `127.0.0.1`. I think it's possible to listen on both, that's what jupyter [does](http://jupyter-notebook.readthedocs.io/en/stable/public_server.html)

```
# Set ip to '*' to bind on all interfaces (ips) for the public server
c.NotebookApp.ip = '*'
```

**Comment by yulinzhang** [comment]
This question is also relevant, if we want the redis server, created by `ray start --head`, to only listen to a particular ip for security reasons. Is there any solution for that?

**Comment by edoakes** [comment]
@yulinzhang I believe you can do this by specifying the `--node-ip-address <your_ip>` flag to `ray start`.
