### ISSUE TITLE
[client] SIGABRT while connecting to Ray inside docker from driver on host computer

### ISSUE THREAD

**Issue by ankur6ue** [ray-project/ray#16776]
### What is the problem?
SIGABRT while using Ray server running from inside a docker container from a driver program running on the host computer

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.8.8, Ray 1.4

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

I create a Ray docker image using Python 3.8.8 using the following docker file:
```
# FROM prefecthq/prefect:0.14.5-python3.7 as base_image
FROM python:3.8.8 as base_image
# Install pip
RUN python -m pip install --upgrade pip
ENV BASE_DIR=/opt/ocr
RUN python3 -m pip install --user virtualenv
# this removes the need to do source activate, command source is not availabe by default
# see: https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/opt/dev
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install wheel
# needed to get rid of ImportError: libGL.so.1:
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
# needed to get rid of ImportError: libtk8.6.so
RUN apt-get install tk -y
RUN apt-get install nano
RUN apt-get -y install tesseract-ocr
# needed for pdf2image
RUN apt-get -y install poppler-utils
COPY requirements.txt /tmp/requirements.txt
WORKDIR /tmp
RUN pip install -r requirements.txt

WORKDIR /opt/ocr
COPY /utils/*.py /opt/ocr/utils/
COPY *.py /opt/ocr/
COPY test-image.png /opt/ocr

CMD ["python", "test.py"]
```
ray is listed in the requirements.txt file, along with other dependencies required by the application.

I start the ray server inside this docker file as follows:
```
docker run -itd --rm --name=$CONTAINER_NAME --cpus=0.000 --shm-size=12G \
  --network=host \
  $IMAGE_NAME /bin/bash
  # -f option forcibly stops ray processes on master node
  ray stop -f
  docker exec $CONTAINER_NAME \
    ray start --head --num-cpus=$NUM_CPUS --redis-password="password" --port=$PORT
```
Now I can exec into the container and run my application program successfully. To initialize ray in my driver program, I use:
ray.init(address='auto', _redis_password='password', log_to_driver=True, logging_level=logging.DEBUG)

I can also see the program execution on the ray dashboard on the host node

However, when I run my driver program outside the docker image, I get a:
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

error in ray.init (before any of my application code is executed). 

When I start the ray server directly (outside the docker container), my application runs with no issues. Upon stepping in the driver program, the issue seems to be in (worker.py, line 1256):
```
 worker.core_worker = ray._raylet.CoreWorker(
        mode, node.plasma_store_socket_name, node.raylet_socket_name, job_id,
        gcs_options, node.get_logs_dir_path(), node.node_ip_address,
        node.node_manager_port, node.raylet_ip_address, (mode == LOCAL_MODE),
        driver_name, log_stdout_file_path, log_stderr_file_path,
        serialized_job_config, node.metrics_agent_port, runtime_env_hash)
```
If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ankur6ue** [comment]
There is a much easier way to repro the problem:
1. Run ray docker image:

```
# # Get IP address of master node
master_node_address="$(hostname --ip-address)"
# Number of CPUs to use on the master node
NUM_CPUS=8
# Ray port on the master node
PORT=6378
IMAGE_NAME=rayproject/ray
docker run -itd --rm --name=$CONTAINER_NAME --cpus=0.000 --shm-size=12G \
  --network=host 
  $IMAGE_NAME /bin/bash
  # -f option forcibly stops ray processes on master node
  ray stop -f
  docker exec $CONTAINER_NAME \
    ray start --head --num-cpus=$NUM_CPUS --redis-password="password" --port=$PORT
```
2. Verify you can see ray dashboard on the host computer
3. Run a test program on the host computer:

```
import time
import ray

ray.init(address="auto", _redis_password='password', log_to_driver=True)
# ray.client("192.168.1.168:10001").connect()

@ray.remote
def f():
    time.sleep(0.01)
    return ray._private.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```
crashes with a SIGABORT

```
import time
import ray

# ray.init(address="auto", _redis_password='password', log_to_driver=True)
ray.client("192.168.1.168:10001").connect()

@ray.remote
def f():
    time.sleep(0.01)
    return ray._private.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```
Results in:
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair

**Comment by richardliaw** [comment]
@DmitriGekhtman or @ijrsvt I think you all might be best suited to address this issue

**Comment by ijrsvt** [comment]
@ankur6ue I'm not able to reproduce this. Does this repro with `ray.client("localhost:10001").connect()`

**Comment by ankur6ue** [comment]
The issue was related to setting a non-default redis password when starting ray from inside the docker container. This is because calling ray.client doesn't let me specify the redis password. This should be fixed, unless I'm missing something. You should definitely be able to reproduce the issue if you set a non-default redis password when you call ray start from the docker container. 

```
import time
import ray

# ray.init(address="auto", _redis_password='password', log_to_driver=True)
ray.client("192.168.1.168:10001").connect()

@ray.remote
def f():
    time.sleep(0.01)
    return ray._private.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```

**Comment by ankur6ue** [comment]
I now have a question about the same issue from inside a kubernetes pod. 

Here's my kubernetes pod yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: ray-head
spec:
  containers:
    - name: ray-head
      image: rayproject/ray # tesseract-ocr:latest
      command: [ "/bin/bash", "-c", "--"]
      args:
        - "sleep 3600"
      #  - "ray start --head --num-cpus=$MY_CPU_REQUEST"
      # We want to use a local image, as opposed to from a container repo
      imagePullPolicy: Never
      ports:
        - containerPort: 6379  # Redis port
        - containerPort: 10001  # Used by Ray Client
        - containerPort: 8265  # Used by Ray Dashboard
        - containerPort: 8000 # Used by Ray Serve
```
I start a pod:
k create -f yaml_name
# exec into the pod and start ray:
 k exec --stdin --tty pod_name -- /bin/bash
ray start --head

Verify pod is running and get the pod ip. Then try to connect using ray.client("pod_ip:10001").connect()
You'll get an error. Let me know if you need any help with reproducing the issue

**Comment by DmitriGekhtman** [comment]
Using a non-default redis password is no longer a public part of our api, as we don't recommend using that to secure the redis -- you should isolate your network instead.

We should print a message saying it's deprecated.

For the k8s issue:
1. I recommend setting requests and limits (preferably equal) for ray to function correctly
2. I think to connect from outside the k8s you'd first want to do
`kubectl port-forward ray-head 10001:10001`
Then `ray.client("127.0.0.1:10001").connect()`
3. The only deployment strategy on k8s officially supported by Ray is via the Ray operator:
https://docs.ray.io/en/master/cluster/kubernetes.html

**Comment by DmitriGekhtman** [comment]
oh I see you're connecting inside of the pod. let me take a look

**Comment by DmitriGekhtman** [comment]
I'm unable to reproduce the issue when connecting from inside the pod.
Could you post the error message?

**Comment by dovahcrow** [comment]
> I'm unable to reproduce the issue when connecting from inside the pod.
> Could you post the error message?

Same issue, Ray on Kubernetes using the official helm chart. No matter the client is outside the cluster or inside the cluster, it triggers a `SIGABRT` when running `ray.init(address="auto"`.

A little bit drill down using GDB it turns out `SpdLogMessage::Flush` triggers the `abort` which I guess the logger gets a critical log message but the log never got printed out before the whole process terminated.

**Comment by DmitriGekhtman** [comment]
I'm following these steps without seeing an error:
(1) helm install default chart
(2) kubectl exec into ray head after the head pod comes up
(3) open python shell
(4) run `import ray; ray.init("auto")`

@dovahcrow Does this cause a SIGABRT for you?

**Comment by dovahcrow** [comment]
@DmitriGekhtman I didn't get any error if I run `import ray; ray.init("auto")` in the ray head container. However, I got sigabrt outside, e.g. in a container runs python:3.7.7.

I drilled down a little bit, and found that the reason for SIGABRT is "Failed to get the system config from Raylet: IOError: 14: failed to connect to all addresses`. However, I didn't have any issue connecting to the ports on the head using telnet.

I also tried `ray.client(address='10.244.6.35:10001').connect()` in which `10.244.6.35` is the address that the pod of head node is running on, and it gives me no error. Idk why does `ray.init` not work.

**Comment by DmitriGekhtman** [comment]
Currently `ray.init` only works when run from within the Ray cluster -- this behavior may change in the near future (we know the current api is a bit confusing)
Right now client connections from outside a Ray cluster must use `ray.client(...).connect()`

**Comment by ankur6ue** [comment]
A related question. I'm using my own Ray - Kubernetes deployment, so I
understand exactly what is going on - which deployments are being set up,
how many pods are running etc. The official ray-kubernetes documentation is
sparse and doesn't really explain how the setup works.

I set up two deployments - one that creates a ray head (1 replica), another
that creates a ray worker (1 replica) and a service that exposes the ray
head deployment. The image used for these deployments is a custom image I
created - starting from a base Python 3.8.8 image and then installing ray,
sci-kit learn and other dependencies needed by my project. In order for
things to work - I need to specify the following in the command and
argument fields for the head and worker deployment

command: [ "/bin/bash", "-c", "--"]
       args:
            - "trap : TERM INT; sleep infinity & wait;"

Once the head/worker pods are running, I need to exec into each pod and run
the ray head/worker processes:
For example, to start ray head on the head pod, I use:
 kubectl exec ${head_pod_name} -- ray start --head --no-monitor
--dashboard-host 0.0.0.0 --num-cpus=3

I'd like to understand why I can't use the ray start command directly in
the deployment yaml itself?

**Comment by DmitriGekhtman** [comment]
I think it should work if you add the `--block` flag to the Ray start command.

https://github.com/ray-project/ray/blob/27c2f570f1f703dba3e7be1445181bfac07007ef/doc/kubernetes/ray-cluster.yaml#L60

**Comment by DmitriGekhtman** [comment]
This flag makes sure that `ray start` blocks while ray processes are running.
https://docs.ray.io/en/master/package-ref.html#cmdoption-ray-start-block
