### ISSUE TITLE
[RLlib] lagrangian parameter in rllib cql config

### ISSUE THREAD

**Issue by longyuzhao** [ray-project/ray#16770]
### What is the problem?

When specifying config['lagrangian'] = True using cql, I am getting the following error:
`RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.`

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 2.0.0.dev0, python 3.7, torch 1.8.1+cu102

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

In sample code https://github.com/ray-project/ray/blob/master/rllib/agents/cql/tests/test_cql.py, add the following line into config:
`config['lagrangian'] = True`
Then run
`python test_cql.py`

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mvindiola1** [comment]
Hi @longyuzhao,

If you change this line to retain_graph=True does it work for you?

https://github.com/ray-project/ray/blob/0cbeefdadfa36d048955c091d935118d76886ffe/rllib/agents/cql/cql_torch_policy.py#L249

**Comment by longyuzhao** [comment]
Does not seem to solve the problem. I got a different error
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [256, 1]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).` 
after making the change. This is still running `python test_cql.py`

**Comment by richardliaw** [comment]
@michaelzhiluo can you take a look?

**Comment by michaelzhiluo** [comment]
Hi all, `lagrangian=True` hasn't been fully tested yet (neither is the optimizer being used even when it is true); for now, CQL should work with it set to False.

**Comment by tzyodear** [comment]
把306~309行放到262行后面改成alpha_prime_loss.backward(retain_graph=True)就行了。 原代码里也是先算alpha_prime_loss再算critic_loss的。可以参考[https://github.com/aviralkumar2907/CQL/blob/master/d4rl/rlkit/torch/sac/cql.py](url)  第270行后面的
