### ISSUE TITLE
Logging from remote functions?

### ISSUE THREAD

**Issue by yaroslavvb** [ray-project/ray#1678]
What's the proper way to log from remote actors? Messages sent to sys.stdout are going into void.

I got a workaround with

    with open('/tmp/log.txt', 'a') as f:
      f.write('important information')

**Comment by yaroslavvb** [comment]
To actually use this work-around to look at logs from my PS shard I also had to use actors and gpu-resource trick to make sure only one actor is placed on machine. Then use `ray.services.get_node_ip_address()` to figure out which machine the actor was placed on, ssh into that machine and cat `/tmp/log.txt`

I think Ray needs a way to log from actors which works when you have multiple actors per machine

**Comment by robertnishihara** [comment]
STDOUT and STDERR are currently redirected to `/tmp/raylogs/` on the same machine as the worker process.

You can try calling `ray.global_state.log_files()` to get all of the logfiles.

**Comment by pcmoritz** [comment]
We should also consider making it possible to get the stdout from a given remote function via the object_id of one of it's outputs (e.g. `ray.get_stdout(object_id)`, same for `ray.get_stderr`), by storing it in the GCS and retrieving it from there.

**Comment by robertnishihara** [comment]
This was fixed a while ago. Stdout/stderr gets streamed back to the driver.
