### ISSUE TITLE
`ray.init` hangs on WSL1

### ISSUE THREAD

**Issue by prutskov** [ray-project/ray#16804]
### What is the problem?

`ray.init` hangs on WSL1 Ubuntu 20.04.2 LTS

Package versions:
ray==1.4.1
python==3.8.10

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run on WSL1.
```python
import ray
ray.init() # hangs
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by anyscalesam** [comment]
@peytondmurray can you  attempt a repro with latest ray271; if unable to repro we can close.

**Comment by mattip** [comment]
The process does not hang. It does require gui access. The windows firewall does not like the new exe starting up, and pops up some dialog boxes the first time. If that is the reason for this issue the OP should say so. In the mean time I will close this.
