### ISSUE TITLE
Dashboard white screen gpu 

### ISSUE THREAD

**Issue by SheldonCurtiss** [ray-project/ray#16807]
![image](https://user-images.githubusercontent.com/78921582/124135808-294cbb00-da52-11eb-97b4-1bc20f088567.png)

### What is the problem?
Cuda + nvidia drivers and I started to see this problem

On ubuntu lts 18
1.4.1 ray
Python3.9

### Reproduction (REQUIRED)
Running one of the examples

**Comment by rkooo567** [comment]
cc @edoakes 

Did you also see the issue from 1.3?

**Comment by SheldonCurtiss** [comment]
![image](https://user-images.githubusercontent.com/78921582/124173061-8f4c3900-da78-11eb-8527-65dd289b5b2c.png)
![image](https://user-images.githubusercontent.com/78921582/124173082-94a98380-da78-11eb-950c-c510244ec7f9.png)

Unsure if I changed something but error is this @rkooo567

**Comment by SheldonCurtiss** [comment]
Also I'm on WSL unsure if that's related

**Comment by SheldonCurtiss** [comment]
Further information I'm using https://github.com/werner-duvaud/muzero-general
Issue with ray appears to happen on all examples and was functional pre gpu

**Comment by scottsun94** [comment]
@SheldonCurtiss Could you confirm if this issue has been fixed? 
You seemed to submit the same issue here.  #16781 @mattip has some follow-up questions for you.

**Comment by scottsun94** [comment]
Closing this for now. @SheldonCurtiss let us know if you see this issue again.
