### ISSUE TITLE
[RLIib] Backward compatibility issue with Pytorch

### ISSUE THREAD

**Issue by loicsacre** [ray-project/ray#16809]
It would be very interesting to introduce a check of the Pytorch version in order to be backward compatible with old versions at this place:

https://github.com/ray-project/ray/blob/6f48e4f56665aca5b351af9ea9bd1e3c06b81af9/rllib/evaluation/rollout_worker.py#L520

The old method name is [`set_deterministic`](https://pytorch.org/docs/1.7.1/generated/torch.set_deterministic.html?highlight=determ#torch.set_deterministic)

**Comment by richardliaw** [comment]
@loicsacre we just merged support for this in https://github.com/ray-project/ray/pull/16813.

**Comment by richardliaw** [comment]
Thanks a bunch for opening this issue!
