### ISSUE TITLE
[Ray core] Ray worker process leak

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#16802]
### What is the problem?
Ray python worker process leak after `ray.shutdown` called and driver process exited.
![image](https://user-images.githubusercontent.com/12445254/124102350-de9f6300-da92-11eb-9001-3e34aeda6c12.png)

*Ray version and other system information (Python version, TensorFlow version, OS):*
* ray:1.4.0
* os: macos 10.13.6 
* python version: 3.8.1

### Reproduction (REQUIRED)
```python
import asyncio
import ray


@ray.remote
class Actor:

    def __init__(self):
        pass

    async def f1(self):
        pass

    async def f2(self):
        pass

    async def health_check(self):
        return True

    def exit_actor(self):
        """Exiting current process gracefully."""
        ray.actor.exit_actor()


async def is_alive(a):
    try:
        await a.health_check.remote()
        return True
    except Exception:
        return False


async def test_leak():
    ray.init()
    a = Actor.remote()
    print(await a.f1.remote())
    print(await a.f2.remote())
    print(await a.health_check.remote())
    a.exit_actor.remote()
    wait_time, waited_time = 1, 0
    while await is_alive(a):  # pragma: no cover
        if waited_time > wait_time:
            raise Exception('''Can't stop %s in %s, kill sub_pool forcibly''', a, wait_time)
        await asyncio.sleep(0.1)
        wait_time += 0.1
    print(f'kill succeed')
    ray.shutdown()


if __name__ == '__main__':
    asyncio.run(test_leak())


```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
Confirmed that I could reproduce it locally and `ray stop` did not kill the process:
```
(base) code/ray % python leak.py 
2021-07-01 12:37:56,638 INFO services.py:1330 -- View the Ray dashboard at http://127.0.0.1:8265
None
None
True
kill succeed
(base) code/ray % ps aux | grep Actor
eoakes           65947   0.0  0.0  4399356    792 s001  S+   12:38PM   0:00.00 grep Actor
eoakes           65919   0.0  0.1 22842300  71996 s001  S    12:37PM   0:00.76 ray::Actor            
(base) code/ray % ray stop 
Did not find any active Ray processes.
(base) code/ray % ps aux | grep Actor
eoakes           65951   0.0  0.0  4399356    792 s001  S+   12:38PM   0:00.00 grep Actor
eoakes           65919   0.0  0.1 22842300  72000 s001  S    12:37PM   0:00.76 ray::Actor   
```

cc @jiaodong this is likely the same issue you were seeing when working on release tests.

**Comment by jiaodong** [comment]
> Confirmed that I could reproduce it locally and `ray stop` did not kill the process:
> 
> ```
> (base) code/ray % python leak.py 
> 2021-07-01 12:37:56,638 INFO services.py:1330 -- View the Ray dashboard at http://127.0.0.1:8265
> None
> None
> True
> kill succeed
> (base) code/ray % ps aux | grep Actor
> eoakes           65947   0.0  0.0  4399356    792 s001  S+   12:38PM   0:00.00 grep Actor
> eoakes           65919   0.0  0.1 22842300  71996 s001  S    12:37PM   0:00.76 ray::Actor            
> (base) code/ray % ray stop 
> Did not find any active Ray processes.
> (base) code/ray % ps aux | grep Actor
> eoakes           65951   0.0  0.0  4399356    792 s001  S+   12:38PM   0:00.00 grep Actor
> eoakes           65919   0.0  0.1 22842300  72000 s001  S    12:37PM   0:00.76 ray::Actor   
> ```
> 
> cc @jiaodong this is likely the same issue you were seeing when working on release tests.

Yes the symptom is the same. And in this example it didn't even need to involve detached or ray cluster utils and previously I think Simon also pointed out to be suspicious.

**Comment by edoakes** [comment]
@chaokunyang does this only occur when using asyncio actors and when using `exit_actor`?

**Comment by chaokunyang** [comment]
> @chaokunyang does this only occur when using asyncio actors and when using `exit_actor`?
It only occurs when using `asyncio` actors and `exit_actor` simultaneously

**Comment by ericl** [comment]
@chaokunyang is this actively worked on?

**Comment by ericl** [comment]
I can still reproduce in nightly today.
