### ISSUE TITLE
Node Config does not support NetworkInterfaces

### ISSUE THREAD

**Issue by xcharleslin** [ray-project/ray#16815]
### What is the problem?

NetworkInterfaces is a valid field in [boto.create_instances()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances). However, Ray does not support this. If you try to specify this field in node configuration, a Boto error will be raised, saying that SubnetId and SecurityGroupIds fields must be moved inside NetworkInterfaces.

A specific use case of this parameter is to support launching in special subnet configurations. In these configurations, NetworkInterfaces paramters are required to do things like request automatic public IP address or request specific public IP address from a user's Elastic IP pool.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
@xcharleslin correct me if I'm wrong:
the most urgent use-case is covered by 
https://github.com/ray-project/ray/pull/16816
and the longer term solution is to fix `aws/config.py` bootstrapping logic to respect `NetworkInterfaces`.

Based on that, I'm going to mark this P2.

Also, I think @ckw017 would probably a good person to implement the fix for this issue given his relatively recent work on aws configs.
cc @AmeerHajAli

**Comment by xcharleslin** [comment]
Correctamundo. Thanks for triaging @DmitriGekhtman !

**Comment by xcharleslin** [comment]
@DmitriGekhtman I tagged that PR as closing this issue; change if it is not the case.
