### ISSUE TITLE
[tune] How to use BayesOpt?

### ISSUE THREAD

**Issue by renatobellotti** [ray-project/ray#16814]
I am a bit confused about how to use the HyperOptSearch properly. The constructor needs a search space, but some examples give the search space to ``tune.run(config=...)``. Do i have to put it in both places, or is ``tune.run()`` enough?

**Comment by richardliaw** [comment]
Tune.run is enough. Search space is an optional argument in the constructor right? Maybe we can improve the docstring.

**Comment by renatobellotti** [comment]
Thanks for your fast answer! I have asked the wrong question, what I meant was BayesOpt:

This algorithm requires setting a search space using the BayesianOptimization search space specification.

Is the usual space definition enough?

**Comment by richardliaw** [comment]
Yep! Same answer should apply.
