### ISSUE TITLE
utils.get_num_cpus

### ISSUE THREAD

**Issue by LondonAppDev** [ray-project/ray#16811]
### Describe your feature request

I'm using `ray.utils.get_num_cpus` on a project which was removed in v1.4. As per the deprecation message, I'm raising a feature request. 

I'm assuming this has been removed and isn't likely to be coming back, right?

**Comment by richardliaw** [comment]
@wuisawesome @rkooo567 please review?

**Comment by wuisawesome** [comment]
Yeah most likely not. It was only meant to be an internal helper for picking a good default num_cpus.

Can you describe your use case? In particular, why would `ray.cluster_resources()` not work?

**Comment by richardliaw** [comment]
(Or even just `multiprocessing.cpu_count`)?
