### ISSUE TITLE
[rlib] Independent bound for each dimension AssertionError

### ISSUE THREAD

**Issue by frenkowski** [ray-project/ray#16845]
### What is the problem?

Starting from [Ray-1.4.0](https://github.com/ray-project/ray/releases/tag/ray-1.4.0), the Box space type with independent bound for each dimension (e.g. `Box(low=np.array([-1.0, -2.0]), high=np.array([2.0, 4.0]), dtype=np.float32)`) is no longer supported.
Looking at the file `/ray/rllib/models/catalog.py`, in lines 244-245 I noticed the following  new asserts: 

```python
assert np.all(action_space.low == low_)
assert np.all(action_space.high == high_)
```

My suggestion is to modify them as follows:

```python
assert np.all(action_space.low >= low_)
assert np.all(action_space.high <= high_)
```

### Reproduction 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
hey @frenkowski that looks right. Can you open a PR and tag me?
