### ISSUE TITLE
[Tune] Progress report becomes strange after upgrading to ray 1.4.1

### ISSUE THREAD

**Issue by Tonyhao96** [ray-project/ray#16874]
Previous ray version, like 1.4, the log of tuning progress like this:
>== Status ==
Memory usage on this node: 69.5/251.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 16.0/24 CPUs, 8.0/8 GPUs, 0.0/146.26 GiB heap, 0.0/66.67 GiB objects (0.0/1.0 accelerator_type:V100)
Current best trial: 0b62c_00019 with val_accuracy=0.9474 and parameters={'lr': 0.0244, 'momentum': 0.28, 'weight_decay': 0.00936, 'batch_size': 64}
Result logdir: /mnt/lustre/qhhu/ray_results/cifar10_GRID_200sample_res18
Number of trials: 115/200 (26 PENDING, 8 RUNNING, 81 TERMINATED)

However, after upgrade to ray 1.4.1, the log of tuning progress like this:

>== Status ==
Memory usage on this node: 59.5/251.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 16.0/24 CPUs, 8.0/8 GPUs, 0.0/152.21 GiB heap, 0.0/69.22 GiB objects (0.0/2.0 CPU_group_b11dbe119a46b337b3342ec1c06d6020, 0.0/2.0 CPU_group_612dc58b86ad6ae3a68de2e799cef694, 0.0/1.0 GPU_group_b11dbe119a46b337b3342ec1c06d6020, 0.0/2.0 CPU_group_3cf87711c4745585da5b660fb6ea6c45, 0.0/2.0 CPU_group_0276ef980b5e4b317cd3f97a127c598d, 0.0/1.0 GPU_group_0276ef980b5e4b317cd3f97a127c598d, 0.0/1.0 CPU_group_0_3cf87711c4745585da5b660fb6ea6c45, 0.0/1.0 CPU_group_1_b638e2d9ef492ba0e145af7473b5cc9e, 0.0/1.0 CPU_group_0_0276ef980b5e4b317cd3f97a127c598d, 0.0/2.0 CPU_group_1755ff30d764a4baecf0b3ca1bb61f95, 0.0/1.0 CPU_group_0_b11dbe119a46b337b3342ec1c06d6020, 0.0/1.0 CPU_group_1_dbbe0bb23dfd69c4068f1d0b67265aab, 0.0/1.0 CPU_group_0_13d84ca6ba106472e58786831e8d2b1f, 0.0/1.0 CPU_group_0_dbbe0bb23dfd69c4068f1d0b67265aab, 0.0/1.0 CPU_group_0_1755ff30d764a4baecf0b3ca1bb61f95, 0.0/1.0 CPU_group_0_b638e2d9ef492ba0e145af7473b5cc9e, 0.0/1.0 GPU_group_1_13d84ca6ba106472e58786831e8d2b1f, 0.0/1.0 GPU_group_1_3cf87711c4745585da5b660fb6ea6c45, 0.0/2.0 CPU_group_b638e2d9ef492ba0e145af7473b5cc9e, 0.0/2.0 CPU_group_13d84ca6ba106472e58786831e8d2b1f, 0.0/1.0 GPU_group_3cf87711c4745585da5b660fb6ea6c45, 0.0/1.0 CPU_group_1_b11dbe119a46b337b3342ec1c06d6020, 0.0/1.0 GPU_group_1_1755ff30d764a4baecf0b3ca1bb61f95, 0.0/1.0 accelerator_type:V100, 0.0/1.0 CPU_group_1_3cf87711c4745585da5b660fb6ea6c45, 0.0/1.0 GPU_group_1755ff30d764a4baecf0b3ca1bb61f95, 0.0/1.0 GPU_group_1_b11dbe119a46b337b3342ec1c06d6020, 0.0/1.0 GPU_group_b638e2d9ef492ba0e145af7473b5cc9e, 0.0/1.0 GPU_group_dbbe0bb23dfd69c4068f1d0b67265aab, 0.0/1.0 GPU_group_1_0276ef980b5e4b317cd3f97a127c598d, 0.0/2.0 CPU_group_dbbe0bb23dfd69c4068f1d0b67265aab, 0.0/1.0 GPU_group_13d84ca6ba106472e58786831e8d2b1f, 0.0/1.0 CPU_group_1_612dc58b86ad6ae3a68de2e799cef694, 0.0/1.0 GPU_group_1_dbbe0bb23dfd69c4068f1d0b67265aab, 0.0/1.0 CPU_group_1_13d84ca6ba106472e58786831e8d2b1f, 0.0/1.0 CPU_group_1_0276ef980b5e4b317cd3f97a127c598d, 0.0/1.0 GPU_group_1_612dc58b86ad6ae3a68de2e799cef694, 0.0/1.0 CPU_group_1_1755ff30d764a4baecf0b3ca1bb61f95, 0.0/1.0 GPU_group_1_b638e2d9ef492ba0e145af7473b5cc9e, 0.0/1.0 CPU_group_0_612dc58b86ad6ae3a68de2e799cef694, 0.0/1.0 GPU_group_612dc58b86ad6ae3a68de2e799cef694)
Current best trial: 5a8fb_00004 with val_accuracy=0.1435 and parameters={'lr': 0.0002, 'momentum': 0.15, 'weight_decay': 0.0009100000000000001, 'batch_size': 512}
Result logdir: /mnt/lustre/qhhu/ray_results/cifar10_res18_GRID_200sample_200epoch
Number of trials: 34/200 (26 PENDING, 8 RUNNING)

There are so many `CPU_group_1_xxxx, 0.0/1.0 GPU_group_1_xxx, 0.0/1.0 ` in the log.

Would you please tell me what is wrong is it? I just run the same code on the same server.

Here is the code:
```python
VisionTrainable = TorchTrainer.as_trainable(
        training_operator_cls=VisionTrainingOperator,
        config=config,
        num_workers=1,
        # num_cpus_per_worker=2,
        scheduler_step_freq="epoch",
        use_gpu=True)

analysis = tune.run(
        VisionTrainable,
        ...)
```
My code performs well in ray 1.4.

**Comment by richardliaw** [comment]
Hmm, this seems like a regression on our side. We should be filtering those out.

cc @krfricke
