### ISSUE TITLE
Add resource IDs in TaskResourceInstances,NodeResourceInstances

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#16873]
### Describe your feature request

We uses `ResourceIdSet` to keeps track of the specific IDs that are available for a collection of resources before. Now we uses `TaskResourceInstances` and `NodeResourceInstances` ,  there is no information about resource IDs.  We want to support resource limit in https://github.com/ray-project/ray/issues/16871, I think the information about resource IDs is important.A typical example is GPUs, the worker don't know which GPU should be to use.

We also want to support assigning different cpus to different workers by using cpuset. I think it's useful in high performance compute scenario.

**Comment by lixin-wei** [comment]
We've discussed offline, this information is still available in the new scheduler's structs, this issue is invalid, closing.

**Comment by lixin-wei** [comment]
This information is still available in TaskResourceInstances.

**Comment by chenk008** [comment]
Thanks. I think we can use  `predefined_resources` in `TaskResourceInstances` to get the assigned GPUs. And I have found `accelerator_type` in the remote option, so the GPU in `predefined_resources` can stand for the GPU resource.

How about other resource like FPGA?  Now UnitInstanceResources only contains CPU,GPU.

**Comment by chenk008** [comment]
https://github.com/ray-project/ray/blob/7c21be545037ec5be09e41d49badb3ba0b4469e3/src/ray/raylet/scheduling/cluster_resource_scheduler.cc#L622
Why we treat all custom resource as none unit_instances?

**Comment by chenk008** [comment]
And I think `CPU` should not belong to UnitInstanceResources when we use cpushare to limit resource usage.

**Comment by lixin-wei** [comment]
Yeah, I'm also wondering why we only set unit_instances=true for predefined resources? Why we designed like that, @wuisawesome could you help?

**Comment by wuisawesome** [comment]
I think GPU needs to be a unit resource and we should probably keep CPU a unit resource to avoid unexpected side effects. It's necessary because you can't split a 1 GPU task across multiple GPUs.

**Comment by chenk008** [comment]
Hi @wuisawesome How about adding a flag to enable cpu share mode? It is default policy in kubernetes. I have create a pull request.
