### ISSUE TITLE
[RLlib] Graph convolutional Memory

### ISSUE THREAD

**Issue by smorad** [ray-project/ray#16872]
@sven1977

I used rllib for my paper [Graph Convolutional Memory for Deep Reinforcement Learning](https://arxiv.org/abs/2106.14117). I've found it outperforms GTrXL, LSTM, and DNC on partially observable problems such as stateless cartpole.

I'm curious if you would be interested in upstreaming my work. If so, I can clean it up and add it as a `TorchModelV2` similar to LSTMs/GTrXLs using something like `use_gcm = True` in the config. My current implementation is available here: https://github.com/smorad/graph-conv-memory/blob/master/src/models/ray_graph.py. It does require an additional dependency: `torch_geometric` which is an extension for `torch`.

**Comment by jon-chuang** [comment]
Interested in the intersection between RL, online learning, causal inference, and graphical models/causal structural models, and where this piece of research fits into this larger picture.
