### ISSUE TITLE
Create separated actor and critic models in A2C 

### ISSUE THREAD

**Issue by oroojlooy** [ray-project/ray#16883]
Is it possible to have a separated model for the actor and the critic models in A2C from a config file, like the following config dict? 

```
      # Model options for the actor.
      "Actor_model": {
          "fcnet_activation": "relu",
          "fcnet_hiddens": [256, 256],
      },
      # Model options for the critic.
      "critic_model": {
          "fcnet_activation": "relu",
          "fcnet_hiddens": [128, 128],
      },

```

**Comment by mvindiola1** [comment]
Hi @oroojlooy,

It is not possible to do that with the default config and model in rllib but, you could do that yourself if you implemented a custom model. This will only work if you are using only fully connected layers. It is currently not possible to have seperate networks if you include an lstm. 


https://docs.ray.io/en/master/rllib-models.html#custom-models-implementing-your-own-forward-logic

**Comment by oroojlooy** [comment]
Thanks for the link!
