### ISSUE TITLE
[rllib] **model_config not passed to constructor for custom keras models

### ISSUE THREAD

**Issue by translearn** [ray-project/ray#16884]
### What is the problem?

*Ray version == 1.4.1*

When using a custom tf.keras.Model, the dictionary model_config is not passed to the constructor in rllib/models/catalog.py - line 456.

```python
with tf.variable_creator_scope(track_var_creation):
    if issubclass(model_cls, tf.keras.Model):
        instance = model_cls(
            input_space=obs_space,
            action_space=action_space,
            num_outputs=num_outputs,
            name=name,
            **customized_model_kwargs,
        )
```

Adding **model_config fixes the issue:

```python
with tf.variable_creator_scope(track_var_creation):
    if issubclass(model_cls, tf.keras.Model):
        instance = model_cls(
            input_space=obs_space,
            action_space=action_space,
            num_outputs=num_outputs,
            name=name,
            **model_config,
            **customized_model_kwargs,
        )
```

### Reproduction

To reproduce the issue, create a custom model based on the class Keras_FullyConnectedNetwork in rllib/models/tf/fcnet.py.
When using the custom model, parameters like fcnet_hiddens are not set, since **model_config is not passed to the constructor.

**Comment by richardliaw** [comment]
Hmm, nice catch! would you be willing to open a PR for this?

Happy to help merge this for you.

**Comment by translearn** [comment]
Thank you! I've created a PR #16970.

**Comment by translearn** [comment]
Closing this issue, since the current behavior is intended to separate default models and custom models (see PR #16970).
The suggested solution is to copy default parameters like fcnet_hiddens from config['model'] to config['model']['custom_model_config'], if required.
