### ISSUE TITLE
[DataFrame] Concatenate DataFrames

### ISSUE THREAD

**Issue by jbonatakis** [ray-project/ray#1690]
### System information
- **Operating System**: MacOS Sierra 10.12.6
- **Ray Installation**: From source
- **Ray Version**: 0.3.1
- **Python Version**: 3.6.4 Anaconda
- **Exact Command**: df = pd.concat([df1, df2])

### Describe the problem

I would like to be able to concatenate two dataframes.

### Source code / logs

Traceback (most recent call last):
  File "script.py", line 43, in <module>
    df = pd.concat([df1, df2])
AttributeError: module 'ray.dataframe' has no attribute 'concat'

**Comment by devin-petersohn** [comment]
Hi @jbonatakis, would a good first pass be to allow `pd.concat()` only on `DataFrames` for `axis=0`?

**Comment by jbonatakis** [comment]
Yeah, that would be a great start!

**Comment by devin-petersohn** [comment]
Support for `axis=0` on Pandas and Ray added with #1739.
