### ISSUE TITLE
Cython version is inconsistent in codebase

### ISSUE THREAD

**Issue by thomasjpfan** [ray-project/ray#16918]
The osx and linux wheels are pinned to `cython==0.29.15`:

https://github.com/ray-project/ray/blob/74c9fa065002a2e51b966528e4451bd78fe51fb2/python/build-wheel-macos.sh#L84

https://github.com/ray-project/ray/blob/74c9fa065002a2e51b966528e4451bd78fe51fb2/python/build-wheel-manylinux2014.sh#L78

while the rest of the codebase uses `0.29.0`. Should the rest of the codebase use `0.29.15` to be consistent with the release dependencies?

**Comment by richardliaw** [comment]
cc @wuisawesome any thoughts here?
