### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file ray/dataframe/dataframe.py

### ISSUE THREAD

**Issue by ChiamYu** [ray-project/ray#1691]
Hi, 

I built the ray from source in Ubuntu 16.04 (python 2.7) and tried to import ray.dataframe:
`import ray.dataframe as pd`

and received the following error:
```
SyntaxError: Non-ASCII character '\xe2' in file ray/dataframe/dataframe.py on line 745, but no encoding dttp://python.org/dev/peps/pep-0263/ for details
```

https://github.com/ray-project/ray/blob/2b747ba46cee4445c8ff1640a2a5d7c88e2d1723/python/ray/dataframe/dataframe.py#L744

Could you please change all the non-ASCII single-quote (’) in the docstring to the standard quote (') in your repo? It works after I did that. Thanks!

**Comment by robertnishihara** [comment]
Thanks @ChiamYu, I opened #1693, can you let me know if that addresses the problem for you?
