### ISSUE TITLE
[rllib] Relax the version constraints on opencv-python-headless

### ISSUE THREAD

**Issue by mrksr** [ray-project/ray#16929]
### What is the problem?

Rllib depends on `opencv-python-headless`. In `setup.py`, a rather restrictive version constraint is placed on opencv:  https://github.com/ray-project/ray/blob/34422ef53fd072b21da9900a8b70e1b5756ff96a/python/setup.py#L113

This can lead to problems in a Python 3.9 environment, as there are no wheels for a 4.X version of opencv that also satisfy this constraint:
```shell
$ pip install --only-binary ":all:" opencv-python-headless==4.3.0.36
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.3.0.36 (from versions: 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54)
ERROR: No matching distribution found for opencv-python-headless==4.3.0.36
```
There are older versions of opencv (3.4.X) and newer versions of opencv (e.g. >=4.4.0) that supply wheels for Python 3.9. It is possible to install the old version of opencv, but my suspicion is that the constraint is tighter than it needs to be because it was introduced via a CI hotfix in #10049. 

Is the tight constraint needed or can it be relaxed to newer versions of opencv? Thanks!

**Comment by richardliaw** [comment]
@vakker is taking a stab at removing the cv2 dependency.

cc @sven1977

**Comment by mrksr** [comment]
I think this is fixed now in current master (and Ray 1.6), as `opencv-python-headless` is no longer mentioned in `setup.py`. @richardliaw could you verify? I think in that case we can close this issue :)

**Comment by vakker** [comment]
Yes, it was fixed by #16841

**Comment by mrksr** [comment]
Perfect!
Thanks all for your work, especially @vakker!

**Comment by mattip** [comment]
opencv is still mentioned in  python/requirements.txt https://github.com/ray-project/ray/blob/786c5759dee02b57c8e10b39f1c1bed07f05eb5a/python/requirements.txt#L38

Is that still needed?

**Comment by vakker** [comment]
It seems like #17158 added that back, without actually using opencv anywhere. 
The last comment on the PR points that out, I'm not sure why that was left in.

@richardliaw @sven1977 I assume that's a regression that should be resolved in a new PR?
