### ISSUE TITLE
Cross Language programming not being supported in Kubernetes cluster. No way to pass code_search_path in ray.client().connect()

### ISSUE THREAD

**Issue by amitshil** [ray-project/ray#16928]
Relevent tags:
#Kubernetes 
#Multinode Cluster 
#Cross Language Programming 

### What is the problem?
Unable to run the cross language programming (python calling java) in Kubernetes ray cluster. There is no way to pass "job_config or code_search_path" in the ray client while connecting to kubernetes cluster.

Reproducible steps:
sample java code:
![image](https://user-images.githubusercontent.com/9427587/124746999-1f89f280-df3f-11eb-929b-91d9f2fe7859.png)

Create a java jar out of it say Test.jar

Python script

import ray
import sys

sys.path.append("resources/Test.jar")
job_config = ray.job_config.JobConfig(code_search_path=sys.path)

# ray.init('10.67.149.103:6379', job_config=job_config)  # works locally in single machine
# ray.util.connect('10.67.149.103:6379', job_config=job_config)  # doesn't work - gives error    ray.client('10.67.149.103:6379').connect()  # has no way to pass job config

def find_sum():
    assert ray.is_initialized() == True
    add_class = ray.java_actor_class("com.test.Add")
    sum = add_class.remote()
    obj_ref = sum.add.remote(5, 7)
    res = ray.get(obj_ref)
    print(f'Result is : {res}')
    ray.shutdown()

find_sum()

![image](https://user-images.githubusercontent.com/9427587/124749567-0898cf80-df42-11eb-9f12-2c6cadceb988.png)

Ray version and other system information (Python version, TensorFlow version, OS):
Ray version : '1.4.1'
Python version: Python 3.7.7
Java version: openjdk version "11.0.11" 2021-04-20

### Reproduction (REQUIRED)
Already provided the reproduction steps above. 

I have verified my script runs in a clean environment and reproduces the issue. Could you confirm if this is a bug? Kindly let me know in case of anything required for reproducing or understanding the problem.

Discussion link: https://discuss.ray.io/t/what-is-the-way-to-to-set-code-search-path-in-the-driver-while-doing-cross-language-programming-in-k8-ray-cluster/2788

**Comment by amitshil** [comment]
java code for reproducing, just if anyone wants to try reproducing by copying this:

package com.test;
public class Add {
	public static int add(int a, int b) {
		return a + b;
	}
	public static void main(String args[]) {
		System.out.println(add(5, 7));
	}
}

create a jar out of it, and place it under - pythonscriptdirectory/resources/

**Comment by jovany-wang** [comment]
It seems runtime-env can address this issue? @chenk008 @SongGuyang

**Comment by SongGuyang** [comment]
Yep, we can extend runtime env to support this cross language cases.

**Comment by jovany-wang** [comment]
I believe this is finished. Please refer to ray docs for more information about runtime env and passing java jars.
