### ISSUE TITLE
[Core] ObjectLostError related to ownership and named detached actor

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#16951]
### What is the problem?

Kill the driver while the detached named actor holds the ownership will result in `ray.exceptions.ObjectLostError: Object 7ff8ed146320e218ffffffffffffffffffffffff0100000001000000 is lost due to node failure`. This happens when the driver is been terminated, not exiting normally (however for other examples not shown here, exit the driver normally raises the same issue).

### Reproduction (REQUIRED)

```python
def test_ownership():
    subprocess.run(["ray start --head"], shell=True)
    time.sleep(1)
    script = os.path.join(
        os.path.abspath(os.path.dirname(__file__)), "detached.py")
    proc = subprocess.Popen([sys.executable, script])
    time.sleep(10)
    proc.kill()
    time.sleep(1)
    # connect to the cluster
    ray.init(address="auto", namespace="workflow")
    actor = ray.get_actor("holder")
    x = actor.get.remote()
    while isinstance(x, ray.ObjectRef):
        x = ray.get(x)
    assert x == 42
    ray.shutdown()
    subprocess.run(["ray stop"], shell=True)
    time.sleep(1)
```

the simplest `detached.py`:

```python
import ray


@ray.remote
def foo(x):
    return ray.put(42)


@ray.remote
class Actor:
    def __init__(self):
        self.ref = None

    def invoke(self):
        self.ref = foo.remote(0)

    def get(self):
        return self.ref


if __name__ == "__main__":
    ray.init(address="auto", namespace="workflow")
    a = Actor.options(name="holder", lifetime="detached").remote()
    a.invoke.remote()

    import time
    time.sleep(100)
```

a more complicated `detached.py`:

```python
import ray


@ray.remote
def foo(x):
    print("Executing", x)
    import time
    time.sleep(1)
    if x < 42:
        return foo.remote(x + 1)
    else:
        return 42


@ray.remote
class Actor:
    def __init__(self):
        self.ref = None

    def invoke(self):
        self.ref = foo.remote(0)
        return self.ref

    def get(self):
        return self.ref


if __name__ == "__main__":
    ray.init(address="auto", namespace="workflow")
    a = Actor.options(name="holder", lifetime="detached").remote()
    x = a.invoke.remote()

   # use time.sleep(100) here also causes error. but if the driver exits, no errors occur
    while isinstance(x, ray.ObjectRef):
        x = ray.get(x)
    assert x == 42
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by iycheng** [comment]
I see errors like this
```
/tmp/ray/session_latest/logs/gcs_server.out:[2021-07-08 04:08:05,673 W 2242 2242] gcs_worker_manager.cc:37: Reporting worker failure, worker id = 94b9a8f355374939838a344d1917b4cd0fbc4294e76ccde91c099157, node id = 5e217d5e527b0638d169f437a4a45097b9f53dde7ea326325f63892f, address = 172.31.38.60, exit_type = SYSTEM_ERROR_EXIT, has creation task exception = 0. Unintentional worker failures have been reported. If there are lots of this logs, that might indicate there are unexpected failures in the cluster.
/tmp/ray/session_latest/logs/gcs_server.out:[2021-07-08 04:08:05,673 I 2242 2242] gcs_actor_manager.cc:636: Worker 94b9a8f355374939838a344d1917b4cd0fbc4294e76ccde91c099157 on node 5e217d5e527b0638d169f437a4a45097b9f53dde7ea326325f63892f exited, type=SYSTEM_ERROR_EXIT, has creation_task_exception = 0
```

If looks like if the driver got killed, the actor somehow will exist as well, even it's a detached actor. But, when driver exist normally, it looks fine. When creating actor, there might be something wrong.

@suquark to unblock your side, could you use `sys.exit` in your test case until it being fixed? If looks like sys.exit works. For example, register signal handler in driver and issue signal in test script.

**Comment by suquark** [comment]
@iycheng for my test case (not the case shown here) the same error occurs when I exit the driver normally.

**Comment by suquark** [comment]
(Add P1 label due to blocking some current work & detached named actor should be really stable)

**Comment by stephanie-wang** [comment]
Looks like the issue is that the worker that owns the innermost ObjectRef is fate-sharing with the first driver. So the order of events is:

1. Actor submits task foo.
2. `foo` is executed on Worker. Worker has the same job ID as the first driver. `foo`'s returned ObjectRef is referred to by Actor.
3. First driver exits. Raylet kills all workers with the same job ID, so Worker also exits. `foo`'s returned ObjectRef is no longer accessible.

Maybe one fix is to drain workers once their job has finished instead of killing them outright. ObjectRefs that are entirely contained in one job should eventually go to 0 normally as the driver and other workers exit. But in this case, Worker will stay alive because it owns an ObjectRef that is still referred to by a detached actor.
