### ISSUE TITLE
[cross language] Setting code search path after ray.init() in python

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#16954]
### Describe your feature request

Setting code search path in `ray.init` is not quite user friendly. For example, one wants to use some libraries which use cross language, and all of them has a path to set. If a user needs to get the path from each library and concat them to set in `ray.init`, that would be quite annoying. I think at least when driver is in python, we should be able to modify code search path after `ray.init`, or even set it for each java actor/task.

**Comment by raulchen** [comment]
At Ant, our typical usage is to distribute all the libraries (both Python and Java) to a predefined path. So in the driver code, you only need to set one path in ray.init.
Do you think this can resolve your problem?

**Comment by kira-lin** [comment]
Thanks for your reply @raulchen. We are from the RayDP(Spark on Ray) team, and we also want to use cross language. At least our jar and spark jars needs to be added to code search path. That means our users need to add these path to the code search path in `ray.init` in the driver code , which might be less convenient. If users want to use other libraries using cross language, this would be annoying.

I think if driver is in python, then code search path could be specified before it uses any java code, in that case users do not need to modify their code. Maybe we can see how the new multi-language goes and submit a PR.

**Comment by SongGuyang** [comment]
We already do a discuss offline. We can solve this issue after support Java dependencies in Runtime Env. We will begin to do this recently.

**Comment by kira-lin** [comment]
Thanks, I'll close this issue for now.
