### ISSUE TITLE
Improve handling of nested tasks to avoid crashing due to too many workers

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#16973]
When a workload of nested tasks executes, Ray should prioritize launching under-represented task classes. For example, in the following workload:

```
ray.init(num_cpus=2)

@ray.remote
def outer():
   return ray.get(inner.remote())

@ray.remote
def inner():
  return 0

ray.get([f.remote() for _ in range(1000)])
```

Ray should be executing at most 2 concurrent instances of `outer`. Priority should be given to scheduling `inner` tasks. This may be a regression.

cc @wuisawesome @stephanie-wang @anabranch

**Comment by wuisawesome** [comment]
I can take this. I think we can solve this with LIFO queuing on the raylet.

**Comment by ericl** [comment]
I don't think lifo solves this problem entirely due to core worker level queuing right? What might work better is proportional fair share.

**Comment by wuisawesome** [comment]
Hmmm I don't quite understand why the core worker queue would cause problems here. In the single node case:

**===========after the first 2 tasks are kicked off=========== **

**Driver**
Queue: outer[3:1000]

**Worker 0 (outer[0])**
Queue: <N/A>

**Worker 1 (outer[1])**
Queue: <N/A>

**Raylet**
Queue: outer[2]

**===========after the `ray.get()` begins to execute (cpu is released)===========**

**Driver**
Queue: outer[3:1000]

**Worker 0 (outer[0])**
Queue: <N/A>

**Worker 1 (outer[1])**
Queue: <N/A>

**Raylet**

With FIFO: 
Queue: outer[2], inner[0], inner[1]

With LIFO:
Queue: inner[1], inner[0], outer[2]

**Comment by ericl** [comment]
I think it could work in that case, but LIFO has significant disadvantages compared to fair sharing of resources for the following reasons:
1. In the distributed setting, the submission order of tasks becomes somewhat ill defined, especially if there are tasks from multiple nodes, or spillback. You might need complicated notions of tracking order such as timestamps.
2. Even if we track LIFO correctly, it is likely to lead to starvation of certain workloads if there are multiple tenants in the cluster or multiple sub-routines in the job submitting tasks.

Proportional fair sharing has none of these disadvantages, and also has the bonus of improving multi-tenancy (fair sharing is an expected scheduler feature in these cases). It also has well known properties since we have already implemented and used it in the past in Ray (this issue is a regression).
