### ISSUE TITLE
Speed up actor ID (and other random ID generation).

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1698]
This function is really slow (on the order of 5-10ms). It is used in a bunch of places and should be replaced with something faster (e.g., a deterministic hash). This is an issue e.g., for actor creation.

https://github.com/ray-project/ray/blob/cae108d019a51bd7bd35df7f93b68ff07a84d9cd/python/ray/utils.py#L84-L107

**Comment by richardliaw** [comment]
what about `uuid.uuid4().bytes`?

**Comment by richardliaw** [comment]
On my machine...
```
In [12]: %timeit ray.utils.random_string()
4.91 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [13]: %timeit uuid.uuid4().bytes
8.89 µs ± 561 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [14]: uuid.uuid4().bytes
Out[14]: b'b\xe9l?\xe9\nI\x8a\x95\xc8f\xe1D\xb6\x19\xef'
```

**Comment by robertnishihara** [comment]
There are a couple considerations here.

1. Speed
2. Deterministic ID generation
3. Not messing up the random seed (this means that if a user seeds the random number generator in their application, we shouldn't mess with the state of the random seed)

Right now, we have only 3. It'd be nice to have all 3.

The `uuid` approach is nice. That seems to get us 1 and 3, and it simplifies our lives a little bit.

@stephanie-wang how important is deterministic actor ID generation for now?

**Comment by robertnishihara** [comment]
I'm guessing we definitely want deterministic ID generation right now, but switching to that behavior right now could cause issues.. I'm not sure.

**Comment by richardliaw** [comment]
for 2 (although not too necessary to do so right now) https://stackoverflow.com/questions/41186818/how-to-generate-a-random-uuid-which-is-reproducible-with-a-seed-in-python

**Comment by robertnishihara** [comment]
It's subtle.. that may be enough to generate the same sequence of random numbers on a given worker. However, we have to account for the fact that tasks are scheduled on workers in random ways, so we aren't guaranteed to be on the same worker.

Down the road I think we have to do a hash of the parent task ID and some sort of counter.

Also, this avoids messing up any tasks that use the `uuid` module.

**Comment by stephanie-wang** [comment]
I think deterministic ID generation is a must for actors if we want to do reconstruction properly. I haven't thought about it thoroughly, but I think it will get pretty hairy if actors are assigned random IDs.
