### ISSUE TITLE
[DataFrame] AttributeError: module 'ray.dataframe' has no attribute 'read_csv'

### ISSUE THREAD

**Issue by jaymanjunath** [ray-project/ray#1699]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Sierra Vista
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**:ray==0.3.1
- **Python version**:3.6.2
- **Exact command to reproduce**: 
               import ray.dataframe as pd
               # Pandas on Ray
               print("Pandas on Ray:")
%time pandas_on_ray = pd.read_csv("international-data/midyear_population_age_country_code.csv")

### Describe the problem

I am using Jupyter lab to test ray, it's not working as I expected.
![screen shot 2018-03-12 at 10 29 00 am](https://user-images.githubusercontent.com/30962121/37299336-39b20812-25e0-11e8-8f24-2849d85929da.png)

**Comment by devin-petersohn** [comment]
Hi @jaymanjunath it looks like you installed by `pip install ray`. If you came from the [blog](https://rise.cs.berkeley.edu/blog/pandas-on-ray/) and are trying to test the code, ray must be built from source. 

You can find the instructions to build from source (current master) on the [readthedocs](http://ray.readthedocs.io/en/latest/index.html) page.

**Comment by robertnishihara** [comment]
Also see #1670.

**Comment by marnixkoops** [comment]
This also seems to solve the issue:
data = pd.dataframe.pd.read_csv('data.csv')

**Comment by devin-petersohn** [comment]
@marnixkoops see https://github.com/ray-project/ray/issues/1706#issuecomment-373084365

**Comment by devin-petersohn** [comment]
Closing as the newest Ray release has this, so you no longer need to build from source.
