### ISSUE TITLE
[placeholder] Single node scalability envelope tests are broken (also the distributed tests)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17009]
In the dashboard, the single node scalability tests are failing in master with 134 (abort).

cc @wuisawesome @rkooo567

**Comment by jiaodong** [comment]
Hi @ericl, what's the current status on this for 1.5.0 release that is cut this Monday morning on fd59518980ba2995c72035042cc3341b75baef78 ? It's passing nightly tests with minor issue and weekly tests are still run. 

It will be great to know if this issue should be release blocking for 1.5.0, if not, what's the ETA you have in mind ? Thanks !

**Comment by ericl** [comment]
If this is passing on the 1.5 branch, we can unblock the release. Otherwise, @rkooo567 is looking at fixing this on master as an interrupt.

**Comment by rkooo567** [comment]
If the test succeeds in 1.5 release build, it should be fine to unmark as a release blocker.

**Comment by jiaodong** [comment]
All nightly tests passed on 1.5.0 cut and the only failing long running weekly test is https://buildkite.com/ray-project/periodic-ci/builds/548#de9691e9-3027-44a1-a109-e2ab6e437fd2, which is the "distributed test", I think it should be relevant to the title of this PR ?

**Comment by rkooo567** [comment]
That test was broken from before, so it is unrelated. I think we can just mark this as P1 (standard stability task), but not a release blocker?

**Comment by jiaodong** [comment]
Got it, I will leave it to you guys to make the call on this issue regarding if it should be release blocking or not, if not please update the label accordingly, otherwise please keep me updated if you have ETA on it :)
