### ISSUE TITLE
[core] Ability to monitor task scheduling status

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#17001]
### Describe your feature request

It's useful to have more detailed information about a task's scheduling status, e.g., `PENDING`, `SCHEDULED` (and on which node), `DONE`, `FAILED` etc. Ray has `ray memory` right now for `ObjectRefs`, but the information just says whether a task is completed or not. Eventually integration with the dashboard would also be good.

Implementation-wise, it would be good to integrate this tool with `ray memory`, which already gets garbage-collected automatically.

**Comment by rkooo567** [comment]
Huge +1.

**Comment by ericl** [comment]
The "Status Check" section of this doc is relevant here: https://docs.google.com/document/d/1OT6m4xQDN8UtsBgnAMpX6nhXpNAfdeHJVve-iGhw1WI/edit
