### ISSUE TITLE
[placeholder] Actor creation tasks very infrequently hang (<0.05% of the time)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17008]
This issue is broken out from https://github.com/ray-project/ray/issues/16612

(TODO: add more repro details)

cc @wuisawesome

**Comment by jiaodong** [comment]
Hi @ericl , what's the current status on this for 1.5.0 release that is cut this Monday morning on fd59518980ba2995c72035042cc3341b75baef78 ? It's passing nightly tests with minor issue and weekly tests are still run. 

It will be great to know if this issue should be release blocking for 1.5.0, if not, what's the ETA you have in mind ? Thanks !

**Comment by clarkzinzow** [comment]
@jiaodong I'm currently working on this as a P0 + release blocker, worked on a reproduction yesterday and continuing to work on a reproduction + fix today.

**Comment by jiaodong** [comment]
Thanks for confirming, I will update this in our release notes and feel free to keep me updated once you need cherrypicks :)
