### ISSUE TITLE
[placeholder] Runtime environment takes minutes to load (from S3) sometimes

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17006]
This issue is broken out from https://github.com/ray-project/ray/issues/16612

(TODO: add repro details)

cc @wuisawesome

**Comment by wuisawesome** [comment]
@architkulkarni @edoakes can y'all find an owner for this?

**Comment by edoakes** [comment]
@architkulkarni is currently looking into it. Will likely need some help from @iycheng on the S3 codepath.

**Comment by edoakes** [comment]
@architkulkarni can you please report back here when you have a chance to repro w/ and w/o the S3 feature flag?

**Comment by wuisawesome** [comment]
thanks! lemme know if you want to sit down to get the repro working.

**Comment by architkulkarni** [comment]
Thanks a lot @wuisawesome -- before I take up more of your time, let me try to repro it myself, but I may ask for help if things don't work.  Do you happen to have the code for making the histogram lying around?

**Comment by iycheng** [comment]
I think right now, only the non-s3 code paths got tested. But from my understanding, it should be the same. Let me know if there is a huge difference.

**Comment by wuisawesome** [comment]
Unfortunately I think I `git reset` it away :(

I just regexed around log files to generate it though. I can try to recreate it if it helps.
