### ISSUE TITLE
Error building Arrow from source WSL Windows

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#1700]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows Subsystem for Linux - Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.3.1
- **Python version**: 3.6
- **Exact command to reproduce**: `pip install -e . --verbose`

### Describe the problem

I will try to keep this brief:

1.) It has worked before on this system in this specific path. After the Arrow version was updated most recently, it no longer builds on the `/mnt/c`
2.) It builds fine on the Linux filesystem side. It only fails on `/mnt/c/.../``

This is a problem because Windows apps should not access the Linux filesystem. 

### Source code / logs
These are the relevant logs. `stderr` doesn't give meaningful output.
```
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
/usr/share/automake-1.15/am/ltlibrary.am: warning: 'libsnappy.la': linking libtool libraries using a non
-POSIX
/usr/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
Makefile.am:4:   while processing Libtool library 'libsnappy.la'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1.7ubuntu1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1.7ubuntu1
libtool: and run autoconf again.
make[4]: *** [snappy.lo] Error 63
make[3]: *** [all] Error 2
```

**Comment by Anya28** [comment]
I am having a similar issue at the moment. I am also using Windows Subsystem for Linux - Ubuntu 16.04, and failing on the pip install -e . --verbose command. Have you managed to solve the issue?

**Comment by robertnishihara** [comment]
@Anya28 can you share the logs from the installation?

**Comment by robertnishihara** [comment]
Compilation has changed substantially, so this should no longer be an issue.
