### ISSUE TITLE
[rllib] Re-enable skipped tests

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#17011]
### What is the problem?

https://github.com/ray-project/ray/pull/17010

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Ping on this P0 (fix or downgrade)?

**Comment by amogkam** [comment]
Ah yes, the fix for this was merged earlier today by @sven1977 (https://github.com/ray-project/ray/pull/17321).
