### ISSUE TITLE
[tune] How to support GPU in float number

### ISSUE THREAD

**Issue by Tonyhao96** [ray-project/ray#17032]
I want to run 2 trials on 1 GPU and have tried two methods on example code [mnist trainable](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py).

**Method 1**

```python
    analysis = tune.run(
        TrainMNIST,
        resources_per_trial=tune.PlacementGroupFactory([{"CPU": 2, "GPU": 1}],
                                                       strategy="PACK"),
        ...)
```

**Method 2**
```python
    analysis = tune.run(
        TrainMNIST,
        resources_per_trial={"cpu": 2, "gpu": 0.5},
        ...)
```

Both of them raise the same exception:

```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 741, in _process_trial
    raise RuntimeError(
RuntimeError: Trial TrainMNIST_75086_00005 has a non-training future scheduled but 2 results left to process. This should never happen - please file an issue at https://github.com/ray-project/ray/issues
```

I checked the [PlacementGroupFactory](https://docs.ray.io/en/master/tune/api_docs/internals.html?highlight=PlacementGroupFactory#placementgroupfactory) document, the float number GPU should be already supported?

```python
tune.run(
    train,
    tune.PlacementGroupFactory([
        {"CPU": 1, "GPU": 0.5, "custom_resource": 2}
    ]))
```

**Comment by krfricke** [comment]
This should be unrelated to fractional GPU usage. We've refactored the future handling code immensely in the past months and haven't seen this issue since then, so I'm closing this until it is raised again.
