### ISSUE TITLE
Use ray to query parquet files stored in an object storage

### ISSUE THREAD

**Issue by barrachri** [ray-project/ray#1704]
I'd like to use ray to load parquet files stored in a object storage (s3 for example).

The aim is to run distributed queries using pandas and avoid using impala/drill/presto/athena.

It seems there is a support for [parquet files](https://github.com/ray-project/ray/blob/d78a22f94c7413a093b0a2a20087131f1e6e85ad/python/ray/dataframe/io.py#L18) but only limited to local files.

**Comment by devin-petersohn** [comment]
Hi @barrachri, thanks for the request! We are currently working on this and should have basic functionality ready within the next week or so.

**Comment by barrachri** [comment]
Thanks @devin-petersohn, do you have a PR for this?

**Comment by devin-petersohn** [comment]
Not yet, I'll ping you when it goes in.
