### ISSUE TITLE
Redis maxclients is sometimes artificially low 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#17045]
### What is the problem?

This issue seems difficult to reproduce, but sometimes maxclients is much lower than the ulimit. This is one cause of flakiness for the scalability envelope. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by wuisawesome** [comment]
This is presumably the root cause of the scalability envelope breakage.

**Comment by ericl** [comment]
@iycheng I believe this is the issue you're looking at right now

**Comment by iycheng** [comment]
With the AMI defined in this [PR](https://github.com/ray-project/ray/pull/17443), this issue should be fixed.
