### ISSUE TITLE
Ray library - read_csv function

### ISSUE THREAD

**Issue by erseema** [ray-project/ray#1706]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 17.04)**:
- **Ray installed from (source or binary)**: Ray installed from pip package manager
- **Ray version**:  ray-0.3.1
- **Python version**: 2.7
- **Exact command to reproduce**: 
import ray.dataframe as rd
rd.read_csv("/home/seema/Desktop/EVENTSALE.csv")

**But this throwing an error , 'module' object has no attribute 'read_csv'**.. Though in this blog the same function is used to read a csv .. https://rise.cs.berkeley.edu/blog/pandas-on-ray/

**Comment by tushar-nitave** [comment]
At the end of the blog they have written _The code used here is on the current master branch of Ray, but has not yet made it into a release._ So, I guess you have to wait till the official release is made.

**Comment by devin-petersohn** [comment]
See #1699. You can use this if you build from source.

**Comment by EKami** [comment]
It's not yet usable for me, there are too many unsupported operations for now. Any idea when you plan to make a stable release @devin-petersohn ? Thanks

**Comment by devin-petersohn** [comment]
@EKami We are working very hard to make this happen as soon as possible, and most operations will be done by the end of the month. Which operations do you need the most?

**Comment by EKami** [comment]
Thanks a lot for this @devin-petersohn . For the operations you can find them all in [this script](https://github.com/EKami/Torchlite/blob/master/examples/rossmann.py) (it's the one on which I tested pandas on ray). The script is standalone, meaning you just have to execute it and it will download the dataset, preprocess the data, make predictions etc... Simple operations such as:
```
train.StateHoliday = train.StateHoliday != '0'
```
Are not working with pandas on ray. If I change the code to:
```
train["StateHoliday"] = train["StateHoliday"] != '0'
```
I get another error.
Maybe my script could be useful to you to test many different operations from pandas?

**Comment by devin-petersohn** [comment]
Thanks @EKami, I'll look into your script. We only have some basic functionality at this point, but we're rapidly adding to it!

**Comment by erseema** [comment]
I built it from source.. but still the same error

**Comment by robertnishihara** [comment]
@erseema, that probably means that when you do `import ray`, it's finding the version that you installed with pip. Try doing `pip uninstall ray -y` over and over until you've uninstalled all of the versions of Ray. Then reinstall from source.

**Comment by erseema** [comment]
Ok.. Let me try this once more. As i uninstalled ray before building from
source

**Comment by marnixkoops** [comment]
This also seems to solve the issue:
data = pd.dataframe.pd.read_csv('data.csv')

**Comment by devin-petersohn** [comment]
@marnixkoops Your suggestion is actually running the pandas import in `__init__.py`. `pd.dataframe.pd` is Pandas. This issue has to do with the fact that we have not yet released the Pandas on Ray in an official release. If you want to use Pandas on Ray, you have to build from source at the moment.

**Comment by devin-petersohn** [comment]
Closing as the newest Ray release has this, so you no longer need to build from source. Please open a new issue if you are still having trouble with this.
