### ISSUE TITLE
[autoscaler][kubernetes] Investigate scale down problems

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#17063]
### What is the problem?

It has been reported on Ray slack that the Kubernetes operator is having issues scaling down Ray nodes in a timely manner (even when there are merely ~15 Ray pods to scale down). Investigate. 

Ray slack discussion: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1625778322325400

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by tkram01** [comment]
The test script to reproduce is the same as in this issue - https://github.com/ray-project/ray/issues/16820

**Comment by DmitriGekhtman** [comment]
The operator in question has been deprecated.
Downscaling is more robust with KubeRay, probably.
