### ISSUE TITLE
[core] A test utility library for injecting failure for Ray applications

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17079]
### Describe your feature request

It could be very nice to be able to do ray.simulate_node_unresponsive(node).

There are various failures that we should consider supporting, such as:

* Memory failures
* OS failures (thread limit, port limit, file limit)
* Network failures

cc @wuisawesome @rkooo567

**Comment by wuisawesome** [comment]
Duplicate of #15433

**Comment by richardliaw** [comment]
nice, thanks for the pointer
