### ISSUE TITLE
[Dataset] Clean up Arrow filesystem serializability issues

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#17085]
Arrow's S3 filesystem isn't serializable which causes read/write tasks to fail when they close over such a filesystem instance. We should change the Ray Dataset IO layer to take filesystem factories instead of filesystem instances, where we use such a filesystem factory to create a filesystem instance within the read/write tasks.

**Comment by clarkzinzow** [comment]
@wuisawesome Could you add some more details as to the specific failure when serializing Arrow's S3 filesystem? It appears that it at least _should_ be serializable: https://github.com/apache/arrow/blob/dd9261ee67d1e81f036d3d1f9cb5dd544914f5a7/python/pyarrow/_s3fs.pyx#L226-L268

**Comment by wuisawesome** [comment]
Here's a repro:

```
import ray
import pyarrow.fs

@ray.remote
def foo(s3fs):
    pass

ray.init()

s3fs, _ = pyarrow.fs.FileSystem.from_uri("s3://anyscale-data")
ray.get(foo.remote(s3fs))
```

**Comment by ericl** [comment]
It seems that it's serializable but fails during deserialization:
```
>>> (pid=174956) 2021-07-14 13:54:20,653	ERROR serialization.py:253 -- S3 subsystem not initialized; please call InitializeS3() before carrying out any S3-related operation
(pid=174956) Traceback (most recent call last):
(pid=174956)   File "/home/eric/Desktop/ray/python/ray/serialization.py", line 251, in deserialize_objects
(pid=174956)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=174956)   File "/home/eric/Desktop/ray/python/ray/serialization.py", line 189, in _deserialize_object
(pid=174956)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=174956)   File "/home/eric/Desktop/ray/python/ray/serialization.py", line 167, in _deserialize_msgpack_data
(pid=174956)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=174956)   File "/home/eric/Desktop/ray/python/ray/serialization.py", line 157, in _deserialize_pickle5_data
(pid=174956)     obj = pickle.loads(in_band)
(pid=174956)   File "pyarrow/_s3fs.pyx", line 214, in pyarrow._s3fs.S3FileSystem._reconstruct
(pid=174956)   File "pyarrow/_s3fs.pyx", line 204, in pyarrow._s3fs.S3FileSystem.__init__
(pid=174956)   File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
(pid=174956)   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
(pid=174956) pyarrow.lib.ArrowInvalid: S3 subsystem not initialized; please call InitializeS3() before carrying out any S3-related operation
```

**Comment by wuisawesome** [comment]
Same thing. It didn't serialize correctly (missed the S3 subsystem) so it couldn't deserialize.

**Comment by clarkzinzow** [comment]
It looks like the S3 subsystem is typically initialized when `pyarrow.fs` is imported: https://github.com/apache/arrow/blob/ec0c3c595554ca441a2161eb4dfc2c0e178b7e41/python/pyarrow/fs.py#L46-L52

**Comment by clarkzinzow** [comment]
Since it appears that deserialization never triggers an import of `pyarrow.fs`, I'm guessing that's why deserialization fails.

**Comment by clarkzinzow** [comment]
It seems like the right solution is for Arrow to expose [`EnsureS3Initialized()`](https://github.com/apache/arrow/blob/apache-arrow-4.0.1/python/pyarrow/_s3fs.pyx) to [Cython](https://github.com/apache/arrow/blob/apache-arrow-4.0.1/python/pyarrow/includes/libarrow_fs.pxd#L182-L184), and to call it in [`S3FileSystem._reconstruct()`](https://github.com/apache/arrow/blob/apache-arrow-4.0.1/python/pyarrow/_s3fs.pyx#L212-L214), before constructing the `S3FileSystem` object.

**Comment by clarkzinzow** [comment]
One workaround idea: Register a custom cloudpickle serializer that wraps the deserializer (`S3FileSystem._reconstruct()`) with a function that tries to `import pyarrow.fs` first to implicitly trigger S3 subsystem initialization, if not yet initialized (i.e. if `pyarrow.fs` has not yet been imported).

**Comment by ericl** [comment]
We could also wrap all the user passed filesystem objects with our own that
has a custom deserialization hook?

But either seems workable.

**Comment by clarkzinzow** [comment]
@ericl True; I was thinking that this may be generically useful for other users of `S3FileSystem` and that we'd want to add it to `python/ray/serialization_addons.py`, but I'm now realizing that could complicate forward pyarrow compatibility for non-Dataset users, which seems bad.

**Comment by wuisawesome** [comment]
Why don't we just allow the user to pass a callable? Most other ray libraries do this, and it seems relatively painless for users.

**Comment by clarkzinzow** [comment]
@wuisawesome I tried to find a solution that didn't require taking a callable since:
1. Requiring a callable is worse UX (albeit slightly) than just being able to pass a filesystem directly.
2.The filesystems are designed to be serializable, so passing a callable shouldn't be necessary.
3. We would have had to change our filesystem validation logic to (i) invoke the callable to get the filesystem, (ii) validate said filesystem, (iii) re-wrap the filesystem in a callable (or reuse the original callable if we don't care about mutating the filesystem during validation) before giving it to the read/write tasks. Not to mention the filesystem inference logic inferring and validating a filesystem, and then wrapping the same filesystem creation logic in a lambda to give to the read/write tasks. Overall, would have been uglier.

**Comment by ericl** [comment]
Re-opening this since it's not addressed for Parquet--- https://github.com/ray-project/ray/pull/17492 is a temporary workaround for that case.

**Comment by clarkzinzow** [comment]
@ericl I think that the solution that I first proposed, adding a custom serialization hook for `S3FileSystem` that tries to `import pyarrow.fs` before reconstructing the filesystem, would work for all known cases, including the Parquet datasource.
