### ISSUE TITLE
Step meta and Metrics for workflow step

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#17090]
We should be able to support basic metrics for the system, for example, duration of tasks, task failure stats …

**Comment by iycheng** [comment]
@ericl here are some ideas for API:

```
workflow.get_stats(workflow_id) -> Dict # return workflow level stats, like how long does this execute
workflow.get_stats(workflow_id, step_id) -> Dict # return workflow step level stats
```

Some system-defined stats will be calculated by workflow:

- when does the step start
- when does the step stop
- how many times does this step runs
- error message
- [optional] what are the next/previous steps (step_id) for this step


And we should also provide API for users to inject customized steps info:

```
s = workflow_step.step()
s.get_stats(key) -> val
s.put_stats(key, val)
```

The naming of the stats: for all customer stats, it'll be prefixed with `user_`.

**Comment by iycheng** [comment]
We need to do the following things to make it work:

- Add element for workflow data (https://github.com/ray-project/ray/blob/master/python/ray/workflow/common.py#L127:7)
- API in workflow to handle the updates (https://github.com/ray-project/ray/blob/master/python/ray/workflow/common.py#L203)
- Checkpointing  (https://github.com/ray-project/ray/blob/master/python/ray/workflow/workflow_storage.py#L356) (https://github.com/ray-project/ray/blob/master/python/ray/workflow/workflow_storage.py#L124) when checkpoint inputs and outputs
- Retrieve as well
- Some tests for this.

**Comment by ericl** [comment]
Could you provide a more detailed specification of the stats API (e.g., Python signature and pydoc?)

**Comment by iycheng** [comment]
```
def get_stats(workflow_id: str, *, name: Optional[str]) -> Dict: ...
    """
    Get workflow stats for a workflow. By default, it'll give job level stats.

    identity.step(i).run("workflow_id")
    print(workflow.get_stats("workflow_id"))
    {"job_started":.., ...}
    """

class Workflow:
   def set_stats(key, val): ...
   """
       set the key to be the value for stats

      w = identity.options(name="ABC").step()
      w.set_stats("V", 123)
      w.run("workflow_id")
      workflow.get_stats("workflow_id", name="ABC")
      # {"V": 123, "job_started": xxxx}
   """

**Comment by ericl** [comment]
get_stats() makes sense to me. However, don't you need to call set_stats() from within the workflow step? It doesn't make sense for it to be adding stats before the workload is run.

**Comment by iycheng** [comment]
Some offline sync, we probably will split the feature into two parts:

* Give the user the way to add meta info
* Executor should be able to add metrics

For the first one:
```
@workflow.step
def func(v): ...

# meta in options is for step meta
# meta in run is for workflow meta
func.options(meta={"A": "B"}, name="func").step(123).run(workflow_id="w", meta={"D": "E})

workflow.get_meta("w", name="func") # return {"D": "E"}
workflow.get_meta("w") # return {"A": "B"}

```


For the second one:

```
w = func.step()
w.run()

# inside run
w._put_stats("start_time", 1234)
# checkpoint inputs/funcbody/options/stats
# w finished
w._put_stats("end_time", 2345)
# checkpoint outputs/stats


workflow.get_stats(workflow_id, step_id: Optional[])
```

I think these are going to be very similar code paths, which we can build by reusing a lot of code.

**Comment by ericl** [comment]
It sounds good. I think there are some small changes we can work out during implementation (e.g., meta => metadata).

Btw, one thing we can consider is merging metadata and stats. For example, get_metadata could return `{"name": step_name, "inputs": ..., "stats": {....}}` where the stats dict is nested under metadata. This is just to reduce confusion around get_output vs get_stats vs get_metadata.

**Comment by lchu-ibm** [comment]
> ```
> @workflow.step
> def func(v): ...
> 
> # meta in options is for step meta
> # meta in run is for workflow meta
> func.options(meta={"A": "B"}, name="func").step(123).run(workflow_id="w", meta={"D": "E})
> 
> workflow.get_meta("w", name="func") # return {"D": "E"}
> workflow.get_meta("w") # return {"A": "B"}
> ```

@iycheng just started looking at this issue. one quick clarification on the above:  shouldn't the first line return A:B while the second line return D:E.  I might miss something but the order seems off to me.

**Comment by iycheng** [comment]
@lchu-ibm  you are right! Let me fix it there.

**Comment by lchu-ibm** [comment]
@iycheng for metadata retrieval, what's the design for unfinished workflow?

For a completed workflow, it should be straightforward - just a static metadata retrieval from checkpoints. 

How about other status? say running or resumable?   should it have similar logic as `get_output`?

**Comment by iycheng** [comment]
Yes, we should. I think for now, if it has been written, it'll return otherwise, throw an exception.

Ideally, we probably can have some tricks to return object ref even for steps not running.
