### ISSUE TITLE
Support nested object ref checkpointing

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#17094]
Support more complicated object references.

**Comment by kfstorm** [comment]
@iycheng Do you have a more detailed description of this issue? e.g. What does object ref checkpointing mean?

**Comment by iycheng** [comment]
@kfstorm this belongs to the workflow library on top of ray. Checkpointing means to store the object into a disk, and then read it back from failure.

**Comment by kfstorm** [comment]
@iycheng And what's the difference between this and object spilling?

**Comment by iycheng** [comment]
> @iycheng And what's the difference between this and object spilling?

Potentially we can utilize object spilling's functionality for this. But right now, we don't have a persistence layer for ray, and object spilling is the job scope. Checkpoint needs to make the object able to be retrieved after the job.

Besides, object spilling might not need to take care of nested ref, since it's within job scope. But take a step future, if we want to introduce persistence layer for ray, it'll have the same issue.

**Comment by kfstorm** [comment]
@iycheng May I know what's the use case to persist the data beyond job scope? Why workflow requires this feature? What's the relationship between the two jobs (one writes data to disk and the other reads from disk)?

What makes nested object ref checkpointing special? Do we already implemented object ref checkpointing?

**Comment by iycheng** [comment]
> May I know what's the use case to persist the data beyond job scope? 

If you want to retrieve the data after ray cluster down, it'll be useful.


> Why workflow requires this feature? 

So it can load it back and resume from the failed point easily

> What's the relationship between the two jobs (one writes data to disk and the other reads from disk)?

Think about running -> failed -> resume case, running will write -> resume will read.

> What makes nested object ref checkpointing special? Do we already implemented object ref checkpointing?

If not, how can we read the data back? It's obj_ref [obj_ref[obj_ref]] you only store the first one, you can't get the rest.

**Comment by kfstorm** [comment]
@iycheng Thanks for the information. We are talking about the persistence of steps/nodes/jobs' parameters in a workflow, right?

I'm a bit surprised that we are now handling Ray cluster down cases now. Should we focus on high availability of Ray cluster instead?

**Comment by iycheng** [comment]
@kfstorm You are right, here it's about the persistence of steps/nodes/jobs.

I think at the same time, we are also working on HA of ray cluster like @stephanie-wang  is working on lineage reconstruction and @wuisawesome  is working on GCS HA.
