### ISSUE TITLE
Integrating Pandas into RAY Framework

### ISSUE THREAD

**Issue by n-raghu** [ray-project/ray#1710]
I'm trying to integrate pandas library into ray framework to make use of multi-core feature.
I have tested that ray is installed and working perfectly.

```
import ray
from pandas import read_sql
ray.init()
def tstSynchronize(customerSQL,connexion):
 return read_sql(customerSQL,connexion)

@ray.remote
def oneSynchronize(customerSQL,connexion):
 return read_sql(customerSQL,connexion)
```

```
>>> customerQL
' SELECT * FROM vwEAE_StudentData WHERE fldCustId=2'
>>> connexion
<pypyodbc.Connection object at 0x7fd07a956f60>
>>> pdf=tstSynchronize(customerQL,connexion)
>>> pdf=oneSynchronize.remote(customerQL,connexion) 
>>> ray.error_info()
```

[{b'message': b'Remote function \x1b[31mlmsForker.oneSynchronize\x1b[39m failed with:\n\nTraceback (most recent call last):\n  File "/eae/dts/v36/space/lmsForker.py", line 11, in oneSynchronize\n    pdf=read_sql(customerSQL,cnx,chunksize=csize)\n  File "/eae/env/great/lib/python3.6/site-packages/pandas/io/sql.py", line 400, in read_sql\n    chunksize=chunksize)\n  File "/eae/env/great/lib/python3.6/site-packages/pandas/io/sql.py", line 1444, in read_query\n    cursor = self.execute(*args)\n  File "/eae/env/great/lib/python3.6/site-packages/pandas/io/sql.py", line 1404, in execute\n    cur = self.con.cursor()\n  File "/eae/env/great/lib/python3.6/site-packages/pypyodbc.py", line 2570, in cursor\n    cur = Cursor(self, row_type_callable=row_type_callable)\n  File "/eae/env/great/lib/python3.6/site-packages/pypyodbc.py", line 1194, in __init__\n    check_success(self, ret)\n  File "/eae/env/great/lib/python3.6/site-packages/pypyodbc.py", line 1007, in check_success\n    ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi)\n  File "/eae/env/great/lib/python3.6/site-packages/pypyodbc.py", line 991, in ctrl_err\n    raise ProgrammingError(\'\', \'SQL_INVALID_HANDLE\')\npypyodbc.ProgrammingError: (\'\', \'SQL_INVALID_HANDLE\')\n', b'data': b'{\'function_id\': b"\\xc6\\x89a\'\\xae!\\x15\\x9b4\\xca\\xa9H\\xd5\\xc1\\xf5\\xc3\\xab\\xa9\\x08\\x01", \'function_name\': \'lmsForker.oneSynchronize\'}', b'type': b'task'}]

First execution which is linked to default process (tstSynchronize) works and loads data, however, the second function(oneSynchronize) with 'RAY' decorator fails.

Could you please let me know if I'm missing something?

Thank you.

**Comment by robertnishihara** [comment]
I can't quite run your example, can you post a full runnable script? In this case, I need the definitions of `customerQL` and `connexion`.

Note that we are working on parallelizing pandas on Ray, e.g., see https://rise.cs.berkeley.edu/blog/pandas-on-ray/. Note that you need to build Ray from source to use this though and it is not feature complete yet.

**Comment by n-raghu** [comment]
Hi,
Yes, I have build ray from source and checked the framework is working fine.
I have attached the script file along with the behavior.
Please check and let me your comments.

[sample.txt](https://github.com/ray-project/ray/files/1810204/sample.txt)

Regarding parallelizing pandas, I have already submitted a feature request and aware of it.
Since I already designed some code in pandas, I just checking if I can integrate this code into ray.

**Comment by pschafhalter** [comment]
Looks like the issue is that [pyodbc is not thread safe](https://stackoverflow.com/questions/1537809/python-multiprocessing-and-database-access-with-pyodbc-is-not-safe).

This means that Ray cannot share the pyodbc connection object across tasks. A fix would be to create a new connection in each task:
```python
@ray.remote
def oneSynchronize(customerSQL):
 connexion = pypyodbc.connect("your connection string here")
 return read_sql(customerSQL,connexion)
```

**Comment by n-raghu** [comment]
@pschafhalter Thanks for the pointers.
I have changed my code to establish a new connection when initiating a new thread which runs successfully.
