### ISSUE TITLE
[Core] Use language independent worker initiators

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#17104]
### Describe your feature request

Currently, ray supports Python/Java/C++ workers, raylet will fork one language worker on demand. Now `runtime env` can works with python worker, but don't support Java/C++ workers.

How about add an language independent worker initiators? I think we can use `setup_worker.py` as the initiator , and the initiator will setup worker enviroment (e.g. create a container).

When we want to create [k8s native worker Pod](https://github.com/ray-project/ray/issues/14077)  , the initiator can create Pod.

The new workflow looks like: 
![image](https://user-images.githubusercontent.com/2086945/125724300-d8998f18-ad9b-4213-92b3-d2170a470e7e.png)

**Comment by jovany-wang** [comment]
It makes sense to me.

**Comment by raulchen** [comment]
Sounds good. And we should move the language-specific code from the worker pool to the initiator. cc @SongGuyang
