### ISSUE TITLE
ray on docker  produce  core file

### ISSUE THREAD

**Issue by yiwei00000** [ray-project/ray#17112]
### Describe your feature request

Our Ray cluster is deployed in Docer. When training on Ray, a large number of **core.xxx files** are generated. May I ask what this file is for? If not, how can I stop this file from being generated?

**Comment by RagavMaddali** [comment]
hey @yiwei00000 : I am also facing the same issue. Are you able to establish connection with ray.init command 
```
ray.init(address=":6379",_redis_password="")
```

**Comment by yiwei00000** [comment]
> hey @yiwei00000 : I am also facing the same issue. Are you able to establish connection with ray.init from external machine command
> 
> ```
> ray.init(address=":6379",_redis_password="")
> ```
> 
> ?

No, it must be connected via a client. For example: ray.client(address=' IP :10001').connect(), but it runs super slow.

**Comment by yiwei00000** [comment]
> hey @yiwei00000 : I am also facing the same issue. Are you able to establish connection with ray.init from external machine command
> 
> ```
> ray.init(address=":6379",_redis_password="")
> ```
> 
> ?

At startup, docker run -- ulimit core = 0. When -- ulimit core = 0 is added, the core file will not be generated again
