### ISSUE TITLE
DOC: Pandas and Ray

### ISSUE THREAD

**Issue by westurner** [ray-project/ray#1711]
### Describe the problem
What should I link to in pandas/docs/source/ecosystem.rst?

### Source code / logs
- https://github.com/ray-project/ray/tree/master/python/ray/dataframe/
  - https://github.com/ray-project/ray/blob/master/python/ray/dataframe/test/test_dataframe.py
- https://rise.cs.berkeley.edu/blog/pandas-on-ray/
- [ ] http://ray.readthedocs.io/en/latest/search.html?q=Pandas
  - http://nbsphinx.readthedocs.io/en/latest/
  - ``jupyter convert --to rst`` requires pandoc
- [ ] DOC: ecosystem.rst: Pandas and Ray
  https://github.com/pandas-dev/pandas/issues/20334
  https://github.com/pandas-dev/pandas/blob/master/doc/source/ecosystem.rst

**Comment by robertnishihara** [comment]
@westurner we're in the process of putting up a documentation page and will send out the link shortly, thanks!

**Comment by robertnishihara** [comment]
Please link to http://ray.readthedocs.io/en/latest/pandas_on_ray.html.

cc @devin-petersohn

**Comment by westurner** [comment]
Thanks!
