### ISSUE TITLE
ray.init(address="<ip>:6379",_redis_password="<password>") is not connecting and creating dump files with name core.<random number>

### ISSUE THREAD

**Issue by RagavMaddali** [ray-project/ray#17119]
HI Ray Team, 

Installation steps :
pip install ray==1.4.1

Step to start ray head :
ray start --head --port=6379 --redis-password="password" --gcs-server-port=10000 --dashboard-host "0.0.0.0"

step to start ray worker : 
ray start --address="ip:6379" --redis-password="password" --node-manager-port=11001 --object-manager-port=11002

When i try to connect to ray with following syntax 
ray.init(address="ip:6379",_redis_password="password") 
i observe that connection is not established and files with name core.<number> is getting created.

Need help in getting this issue resolved.

Thanks,
Ragav.

**Comment by yiwei00000** [comment]
Are you running a Ray cluster on Docker? And when it can't connect, it generates a lot of core. XXX files?

**Comment by RagavMaddali** [comment]
I tried on docker as well as virtual machine. 
From notebook i am not able to establish connection to the process running in virtual machine and docker. 
The core.xxx files are created in notebook from which i am try to establish connection.

**Comment by raddessi** [comment]
I'm seeing this same behavior on Fedora 31/32 without using docker, but inside conda envs running python 3.7. FWIW installing `ray==1.2` does work but anything beyond version 1.2 shows this issue 99% of the time.
