### ISSUE TITLE
[rllib] Is there a native way to keep track of how many episodes have been completed during training?

### ISSUE THREAD

**Issue by akshaygh0sh** [ray-project/ray#17167]
I essentially want to store a string representation of my game every _n episodes_ rather than at the end of _every _single_ episode via the [on_episode_end](https://github.com/ray-project/ray/blob/94f17ec09976abce63e01ff1666c77fc71cacae5/rllib/agents/callbacks.py#L96) function. Is there some internal episode counter variable that I could access to make sure I log the string representation of the game every n episodes rather than every single episode or would I just have to use some kind of global variable to do this?

Thanks.

**Comment by mvindiola1** [comment]
Hi @akshaygh0sh,

I have wanted this feature for some time but I have not seen it. I guess maybe I should add it and submit a PR.

Your best bet is to do it in the callback like you are now. The callbacks are classes. You could add an init dunder and add a member variable that you increment in every call to on_episode_end and use it for the check.

One gotcha here is that in the init you need to make sure to call the super init or you will get a confusing message about missing `legacy_callbacks`.

P.S. This type of question is better asked at https://discuss.ray.io

**Comment by akshaygh0sh** [comment]
Thank you, I assumed that would be the best way to approach it.
