### ISSUE TITLE
[tune] ImportError: cannot import name '_default_registry'

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1716]
I'm seeing this on a development branch, but I suspect it could occur more generally.

It occurs every once in a while when running

```
python python/ray/tune/test/trial_runner_test.py
```

The error is

```
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 1694, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
  File "/home/ubuntu/ray/python/ray/tune/registry.py", line 12, in <module>
    from ray.tune.trainable import Trainable, wrap_function
  File "/home/ubuntu/ray/python/ray/tune/__init__.py", line 6, in <module>
    from ray.tune.tune import run_experiments
  File "/home/ubuntu/ray/python/ray/tune/tune.py", line 8, in <module>
    from ray.tune.hyperband import HyperBandScheduler
  File "/home/ubuntu/ray/python/ray/tune/hyperband.py", line 8, in <module>
    from ray.tune.trial_scheduler import FIFOScheduler, TrialScheduler
  File "/home/ubuntu/ray/python/ray/tune/trial_scheduler.py", line 5, in <module>
    from ray.tune.trial import Trial
  File "/home/ubuntu/ray/python/ray/tune/trial.py", line 15, in <module>
    from ray.tune.registry import _default_registry, get_registry, TRAINABLE_CLASS
ImportError: cannot import name '_default_registry'
```

It looks to me like the issue is some circular imports.

`registry` imports `tune`, which imports `hyperband`, which imports `trial_scheduler`, which imports `trial`, which imports `_default_registry` from `registry`. The problem is that this is all triggered by the `import registry` command which hasn't defined `_default_registry` yet because it's defined at the end of the file... somehow we need to break this cyclic import.

One solution mentioned by @ericl is to make one of the imports lazy.

**Comment by robertnishihara** [comment]
Looks like it can be addressed with a change like https://github.com/ray-project/ray/pull/1668/commits/b55d690d6142f60ef4ecf2c7e667f9030d984de4. There are probably other related issues like that though.

I guess the lesson is that `from X import Y` is dangerous to use if there may be cyclic imports. In general it's probably preferable to do just `import X`.

**Comment by richardliaw** [comment]
To add - guido recommends `import  X` where `X` is a module. 

https://docs.python.org/3/faq/programming.html#how-can-i-have-modules-that-mutually-import-each-other

**Comment by robertnishihara** [comment]
Nice find! Let's try to stick with that.
