### ISSUE TITLE
Broken data processing links on documentation page

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#17171]
The highlighted links on https://docs.ray.io/en/master/ below are broken (I didn't check all of them, but all of the data-related docs should be checked.

There are also probably a ton of ray data-related links in Ray blog posts that are broken as well.

<img width="776" alt="Screen Shot 2021-07-17 at 2 38 29 PM" src="https://user-images.githubusercontent.com/249517/126049897-ff5d8fb6-e783-4e09-b6ca-7f9faa462635.png">

**Comment by robertnishihara** [comment]
This is also true on this page https://docs.ray.io/en/master/ray-libraries.html#ray-oss-list (and probably others).

**Comment by robertnishihara** [comment]
Also links in this blog https://medium.com/distributed-computing-with-ray/data-processing-support-in-ray-ae8da34dce7e (and probably others).

**Comment by lyle-nel** [comment]
These links as well:

https://docs.ray.io/en/master/dask-on-ray.html
https://docs.ray.io/en/master/modin/index.html
https://docs.ray.io/en/master/iter.html

**Comment by lyle-nel** [comment]
@robertnishihara In the interim, you can still access the documentation using https://docs.ray.io/en/releases-1.4.1/

**Comment by lyle-nel** [comment]
Parallel iterators are still missing from the newest documentation:

**Comment by lyle-nel** [comment]
Still no work on this functionality being deprecated?
