### ISSUE TITLE
Include repr() of the actor in actor task errors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17170]
### Describe your feature request

In many cases, IP/hostname/pid are not very interpretable.

Often times, in a user program, actors can have nice interpretable labels (either pre-set or determined during runtime).

Ideally, we can allow the user to do the following:

```
Traceback (most recent call last):
...
ray.exceptions.RayTaskError: ray::...() (label="data_sharder_rank:1")
...
ray.exceptions.RayTaskError: ray::...() (label="trainer_rank:4")
```

and the exception can also programmatically capture this label, like:

```
exc.cause.cause.cause.{label,pid,ip}
```

**Comment by ericl** [comment]
What if we just included the `repr(actor)` in the message?

**Comment by richardliaw** [comment]
Ah, that's a good fix.
