### ISSUE TITLE
[Datasets] Add Feather IO layer to Ray Datasets.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#17185]
Apache Arrow has a first-class tabular file format, [Feather](https://arrow.apache.org/docs/python/feather.html), that the Ray Datasets IO layer should support. Combined with Ray Datasets' existing `.from_arrow()` and `.to_arrow()` APIs, this would round out our "all-Arrow" experience, which should be as nice as possible given our "distributed Arrow dataset" positioning.

## Implementation Note

This should fit within the `FileBasedDatasource` paradigm, where we'd have a `FeatherDatasource` class that derives from it and need only implement `._read_file()`. This is assuming that the pyarrow feather readers/writers support `pyarrow.NativeFile` as the source/destination.

**Comment by shaileshcheke** [comment]
Can I work on this?

**Comment by clarkzinzow** [comment]
@shaileshcheke Definitely! 🙌 I've been wanting to see this happen for a long time.

Let me know if you want any assistance with leveraging the custom datasource API for this, I *think* that this should only involve a simple subclassing of [`FileBasedDatasource`](https://github.com/ray-project/ray/blob/76da2255d9c59d485e8cd5e942de49eb93e03011/python/ray/data/datasource/file_based_datasource.py#L127). We have a few examples of such simple subclasses with `CSVDatasource`

**Comment by jianoaix** [comment]
@shaileshcheke are you still on this or any thing blocking you?

**Comment by shaileshcheke** [comment]
@jianoaix Really sorry for replying late. Was busy in other things last month. Nothing is blocking me. I am still working on it.

**Comment by shaileshcheke** [comment]
Facing **←[0mC:/users/dell/_bazel_dell/vpvw64rg/external/com_github_grpc_grpc/BUILD:1517:16: Compiling src/core/lib/resource_quota/memory_quota.cc failed: (Exit 2): cl.exe failed: error executing command** while building. OS: Windows 10, Python Version: 3.9.13, Visual Studio Build Tools 2019.

**Comment by shaileshcheke** [comment]
As said in implementation note, I have implemented FeatherDatasource with _read_file. Is it sufficient?
