### ISSUE TITLE
Make Ray debugger more useable on a Ray cluster

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#17197]
### Describe your feature request

Right now the Ray debugger usability is very restricted on a Ray cluster: You need to ssh into the node that has the task/actor you want to debug and run `ray debug` from there. There are three possible implementations to improve this:

1. The first implementation is very simple and is to introduce an internal flag to ray.init that makes it so the worker process debugger will be bound to `0.0.0.0` (in https://github.com/ray-project/ray/blob/94f17ec09976abce63e01ff1666c77fc71cacae5/python/ray/util/rpdb.py#L198) and the node's private IP address will be stored in the GCS in https://github.com/ray-project/ray/blob/94f17ec09976abce63e01ff1666c77fc71cacae5/python/ray/util/rpdb.py#L212. This will make it very easy to just call `ray debug` from the head node and use the debugger this way. This will work well in k8s and probably also in EC2 using private IP addresses. It opens a possible security risk if the cluster is not run behind a firewall (that's why the flag should be off by default). On k8s and EC2 the default configurations should be safe, if we want to avoid users getting bitten by opening ports we could bind the sockets to the private IP address instead of `0.0.0.0`.
2. The second implementation is a bit more complex and is to implement it similar to https://github.com/ray-project/ray/pull/14662 and use SSH to tunnel the traffic to the right node. This will need additional setup by the user (i.e. keys) but is better from a security perspective.
3. The third implementation is pretty complex and is to implement a service in the Ray client server, which speaks the debugging protocol and will route the traffic to the right node. This might be best done by using an existing proxy that understands GRPC and can translate GRPC calls to the TCP level.

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by davidxia** [comment]
closed by https://github.com/ray-project/ray/pull/17275 if not immediately obvious
