### ISSUE TITLE
[Datasets] Allow user to specify dataset metadata in read APIs

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#17220]
It the user knows the dataset metadata and wants to obviate the need for reading a metadata file (e.g. in Parquet) or executing a read task to learn the dataset metadata, they should be able to give the dataset metadata to the read APIs and have that metadata propagate down to the block metadata.

Most likely this would be limited to the dataset schema, since the number of rows and the size in bytes won't be even throughout blocks and will be difficult to propagate. Even if this was limited to just the schema, this would still be very useful.

**Comment by ericl** [comment]
Another thing here might be to add a resolve schemas option to the read, which will force the reader to merge all schemas ahead of time. It could be pretty efficient for parquet (maybe this should be the default?) but would take longer for other formats.

**Comment by pdames** [comment]
I can submit a PR for this since I've started prototyping the same metadata injection features as part of a Redshift Manifest datasource implementation (where the manifests being read always comes with per-block byte counts and sometimes also includes row counts + schema info).

**Comment by clarkzinzow** [comment]
Supported added by #22896, closing!
