### ISSUE TITLE
[rllib] Engineering Issues/Backlog

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1724]
Here we track a  TODOs/nice to haves for RLlib - all contributions are welcome. There is no timeline for these things.

### Training
 - [ ] MultiGPU
    - [ ] Consider using a wrapper over `tf.optimizer` like `tf.contrib.distribute`
    - [ ] Investigate all-reduce
 - [ ] Sharded PS Optimizer

## Algorithms:
 - [ ] TRPO
 - [ ] IMPALA

# DONE 
 - [x] **Consider a utility for learners; ie given an environment, return rollouts as fast as possible** (CommonPolicyEvaluator with Vectorized Envs)
 - [x] LSTM support
 - [x] Switch Multi-GPU code (#1646)
 - [x] Multi-agent support
 - [x] Benchmarks: compare against other baselines, add results to repo / regression tests
 - [x] Script for regression testing:
     - [x] launch cluster
     - [x] running a suite of tests
     - [x] pushing all results to S3
 - [x] DDPG
 - [x] switch from snappy to lz4

**Comment by ericl** [comment]
Closing; we should split any remaining stuff into separate tickets if we intend to do them.
