### ISSUE TITLE
ray.exception.RaySystemError: System error: Ray has not been started yet, you can start ray with ray init()

### ISSUE THREAD

**Issue by kbmannnn** [ray-project/ray#17261]
env: 
python3.7.7
ray version 1.3.0

I used the official example to build a ray cluster in the k8s cluster. When I use ray.util.connect('ray-head:10001'), I can successfully connect to the ray cluster, but at the end of running ppo training, the error is as follows:
          
          File"home/ray/project/player/player_runner_ppo.py", line 116, ininit variables self.trainer = PPoTrainer(env="xsim_env:, config=config)
          File /home/ray/anaconda3/Lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 121, in _init_ Trainer._init_(self,config,env, logger_creator)
          File"/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py",line 520,ininit super().init (config, logger creator)
          File"/home/ray/anaconda3/ib/python3.7/site-packages/ray/tune/trainable.py, line 98, in_init_ self.setup(copy.deepcopy(self.config))
          File·/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py”,line 711, in setup self._init(self.config.self.env creator)
          File·/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py”, line 153, in_init num workers=self.config["num workers"])
          File-home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 852, in _make_workers logdir=self.logdir)
          File-/home/ray/anaconda3/ib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py".line 98,in_init
          spacessspaces.
          File -/home/ray/anaconda3/ib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py",line 357, in _make_worker spaces=spaces.
          File -/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py”, line 536。in_init_ if not ray.get gpu ids):
          File-/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 401, in get_gpu_ids worker check connected()
          File-/home/ray/anaconda3/ib/python3.7/site-packages/ray/worker,py", line 202, in check_connected raise RaySystemError("Ray has not been started yet. You can "
          ray.exceptions.RaysystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()

**Comment by rkooo567** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Weird -- just to confirm: by official example, do you mean the default helm chart?
https://docs.ray.io/en/master/cluster/kubernetes.html

Also, does the same problem occur with the latest official Ray release (1.4.1) and/or Ray master?
