### ISSUE TITLE
KeyError: <SumoMultiEnv.SUMOAgent object at 0x7f27246a99d0>

### ISSUE THREAD

**Issue by albertcruzeyork** [ray-project/ray#17266]
### Describe your feature request

For questions, post on our Discussion page instead: https://discuss.ray.io/
when trainer trains the policy, who transfer the object <SumoMultiEnv.SUMOAgent object at 0x7f27246a99d0> to policy_mapping_fn? i'm confused. how to get the agent_id in my env? how to correct my code?  
![2021-07-23 00-20-54 的屏幕截图](https://user-images.githubusercontent.com/33293300/126674314-981269f9-842a-4653-a976-c5fc618f588a.png)
![2021-07-23 00-02-49 的屏幕截图](https://user-images.githubusercontent.com/33293300/126674346-7031d811-152f-4b5b-8eb9-d79437518c43.png)
![2021-07-23 00-30-53 的屏幕截图](https://user-images.githubusercontent.com/33293300/126675054-d70b3651-947a-4d0f-a79c-34897b26d8b4.png)

**Comment by rkooo567** [comment]
cc @sven1977

**Comment by mvindiola1** [comment]
@albertcruzeyork 

What do your reset and step functions look like?

**Comment by albertcruzeyork** [comment]
@mvindiola1 
![2021-07-24 14-45-59 的屏幕截图](https://user-images.githubusercontent.com/33293300/126860114-53408406-be70-47ae-90c0-6c047eea5d78.png)

**Comment by albertcruzeyork** [comment]
@mvindiola1 
![2021-07-24 14-45-59 的屏幕截图](https://user-images.githubusercontent.com/33293300/126860137-11b8e1eb-fc59-4f36-b7a9-0a9484e7077d.png)

**Comment by albertcruzeyork** [comment]
@mvindiola1 
![2021-07-24 14-48-35 的屏幕截图](https://user-images.githubusercontent.com/33293300/126860181-fb9eda3e-6244-4c5b-aa76-6fb9b1470af5.png)

**Comment by albertcruzeyork** [comment]
There seems to be a bug. i print the action_dict in step function and it shows two dict
`(pid=576553) Loading configuration ... done.
(pid=576553) {'nt1': 4, 'nt10': 3, 'nt11': 2, 'nt12': 2, 'nt13': 1, 'nt14': 3, 'nt15': 3, 'nt16': 4, 'nt17': 5, 'nt18': 0, 'nt19': 4, 'nt2': 0, 'nt20': 2, 'nt21': 5, 'nt22': 2, 'nt23': 1, 'nt24': 5, 'nt25': 4, 'nt3': 0, 'nt4': 1, 'nt5': 3, 'nt6': 1, 'nt7': 0, 'nt8': 3, 'nt9': 0}
(pid=576553) {0: 1, 1: 1, 2: 1, 3: 0, 4: 5, 5: 0, 6: 5, 7: 5, 8: 2, 9: 4, 10: 1, 11: 4, 12: 3, 13: 3, 14: 0, 15: 4, 16: 3, 17: 5, 18: 4, 19: 3, 20: 0, 21: 4, 22: 3, 23: 3, 24: 4}
(pid=576553) Exception in thread Thread-1:
(pid=576553) Traceback (most recent call last):
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/threading.py", line 932, in _bootstrap_inner
(pid=576553)     self.run()
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 376, in run
(pid=576553)     raise e
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 373, in run
(pid=576553)     self._run()
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 398, in _run
(pid=576553)     item = next(rollout_provider)
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
(pid=576553)     base_env.send_actions(actions_to_send)
(pid=576553)   File "/home/cy/anaconda3/envs/rl/lib/python3.8/site-packages/ray/rllib/env/base_env.py", line 421, in send_actions
(pid=576553)     obs, rewards, dones, infos = env.step(agent_dict)
(pid=576553)   File "/home/cy/rllibsumoutils-master/example/SumoMultiEnv.py", line 195, in step
(pid=576553)     agent.step(int(action_dict[agent.agent_name]), self.simulation)
(pid=576553) KeyError: 'nt1'`

**Comment by mvindiola1** [comment]
@albertcruzeyork I have a hunch that your reset and step functions are using different names for the agent keys. Can you double check that?
