### ISSUE TITLE
Workflow usability issues fixing before alpha

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#17285]
- [x] - Add a type alias for ray.workflow so we don't need to use ray.experimental.workflow in the examples. You should be able to ray.workflow.list_all() without any imports.
- [x] - aioboto3 should be a soft dependency if not using S3 storage
- [x] - Using default local dir: `/tmp/ray/workflow_data`. This should only be used for testing purposes.' -> Let's remove the message since you print the storage dir in INFO logs for workloads elsewhere.
- [x] - In the examples, please include sample logs output so the users know what to expect.
- [x] - 2021-07-22 15:49:50,815        INFO workflow_access.py:85 -- Get the output of workflow aggregate.c3c2ccc4e8824f64bc6b5253b53043c2.1626994189.903368473 successfully. -> Remove this log
- [x] - Can you add INFO level logs for each workflow step executed? We can add to the documentation how to reduce the verbosity.
- [ ] - When I tried to change the result.run(workflow_id="hello", resume_existing=True(default)), it is re-executing the job each time. It should resume from a previous job if the id already exists. If resume_existing=False, an exception can be raised if a workflow already exists telling you to resume it explicitly. We should log that we're resuming a previously existing workflow.
- [x] - When I run >>> workflow.list_all() with no storage dir created, I get ray.experimental.workflow.storage.base.DataLoadError
- [x] - Should raise ValueError when getting the status of workflow that doesn't exist.
- [x] - Can we use string values instead of WorkflowStats enum in the public API? It's more convenient for the user. We can convert to enum internally for type checking.
- [x] - Change return type of list_all() back to list (sorry, realizing returning dict from list doesn't make sense).
- [ ] - ray.exceptions.RaySystemError: System error: Workflow[id=hello] failed during execution. Why is this a SystemError? Also, the exception chain is quite long.
- [x] - I should be able to define @workflow.step(step_max_retries) directly. Also, please rename this to just max_retries and document its behavior.
- [x] - When retrying a failed step, we should print the exception and log that we're trying.
- [x] - The counter example doesn't run (typos, missing getstate/setstate)
- [x] - get output issue https://github.com/ray-project/ray/issues/17287

**Comment by richardliaw** [comment]
we should do more of these :)

**Comment by iycheng** [comment]
@suquark there are two items left, could you help fix them?

**Comment by iycheng** [comment]
Move error message one to this issue: https://github.com/ray-project/ray/issues/18147
