### ISSUE TITLE
[autoscaler] Enforce per-node-type max workers by terminating nodes

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#17297]
### What is the problem?

The autoscaler currently does terminate nodes that are above per-node-type max workers limits. Fix this.
https://github.com/ray-project/ray/blob/cc38ffb0a04a2ddfea85a2dd1713beaf0b3ab20a/python/ray/autoscaler/_private/autoscaler.py#L258

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by AmeerHajAli** [comment]
@sasha-s, a quick fix here can be helpful.

**Comment by AmeerHajAli** [comment]
@DmitriGekhtman , thanks for filing the github issue on OSS.
