### ISSUE TITLE
Authentication and encryption in Ray - SSL support

### ISSUE THREAD

**Issue by sugoyal** [ray-project/ray#17290]
I want to run a Ray cluster in AWS EKS. For compliance requirements, all communication needs to be encrypted and authenticated (using OpenID Connect).

Communication can be :

Between OnPrem to AWS (for example between OnPrem Ray client and Ray cluster on EKS)
Within EKS cluster (for example between head node and worker nodes)

I found the similar issue https://github.com/ray-project/ray/issues/13274 - ray.util.connect() and SSL config therein
Only half of it has been implemented and issue has been closed i.e only  ray.util.connect has been implemented buy not SSL config for it.

**Comment by oscarknagg** [comment]
Just chiming to add that this would also be useful to me, for similar purposes.
