### ISSUE TITLE
ray.init() does not initialize

### ISSUE THREAD

**Issue by ricardopv1** [ray-project/ray#17298]
Hi,
I am trying to initialize ray but it stays there forever, does not show an error or anything.

This is the code I am running

```
%pylab inline
import torch
import sys, os
import pystk
import ray
ray.init(logging_level=50)
```

I also tried `ray.init()` without success.
I tried both in Jupyter Notebook, and VS Code
I am on Windows 10 21H1 using a virtualenv, no conda, no wsl.
I am using ray 1.4.1

I have left it running for more then 30 minutes and it just does not finish.

Does anyone has a suggestion?

![image](https://user-images.githubusercontent.com/70735644/126821620-ade83d79-cb86-4f31-9a15-b0bebe0de827.png)

**Comment by rkooo567** [comment]
What's your platform? Are you also using virtualenv or conda?

**Comment by ricardopv1** [comment]
I am on Windows 10 21H1 using a virtualenv, no conda, no wsl.

**Comment by rkooo567** [comment]
I see. I remember this was resolved (as a workaround) if I used conda. Can you check this out? Unfortunately, we currently don't have resources to fix Windows issues... :(

**Comment by ricardopv1** [comment]
Thanks SangBin, yes I just installed anaconda and it works fine now. One thing I could identify is that now that I initialized using conda, I was asked by the firewall to allow ray and some other modules to communicate to the outside.
This didn't happen before so I can just assume that the previous behavior was because it couldn't communicate to the outside.
