### ISSUE TITLE
Sigterm handler is not triggered if it's registered before ray.init()

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#17308]
### Sigterm handler is not triggered if it's registered before ray.init()
We found a very interesting behavior. Basically, if we register the sigterm_handler function in the Python main process before ray.init(), this sigterm_handler function is never triggered even if the sigterm signal is captured. We noticed that this handler is only triggered if we put register it after ray.init() .

### Reproduction

- Ray Version: 1.3.0
- Python Version: 3.6.5
- OS: MacOS Catalina v.10.15.6

The following is a simple repro code:
```
import signal

import ray

def main_prepare_to_die(signum: int, frame) -> None:
    print("Main process prepare to die is triggered!")

if __name__ == "__main__":
    signal.signal(signal.SIGTERM, main_prepare_to_die)
    ray.init()
    # NOTE: If we uncommented out the following line, then the
    # function "main_prepare_to_die()" will be triggered to be called.
    # signal.signal(signal.SIGTERM, main_prepare_to_die)
    while True:
        pass
```
This could be reproduced by running above simple code and run command “kill <pid>” in another terminal window.

**Comment by RuofanKong** [comment]
Any updates on it?

**Comment by yoanisgil** [comment]
FYI, I was not able to reproduce the issue while using `ray==1.9.2`

**Comment by kouroshHakha** [comment]
Closing this issue since it is not reproducible on master anymore.
