### ISSUE TITLE
Ray 1.4.1 will not train using `rllib train` with framework="torch" - self.devices is empty [rllib]

### ISSUE THREAD

**Issue by SamShowalter** [ray-project/ray#17316]
### What is the problem?

Running rllib 1.4.1 with num_gpus > 0 and framework="torch" causes a failure. This failure looks to correspond to Rllib not picking up any GPUs when running `ray.get_gpu_ids()`, which causes an error with `self.device = self.devices[0]` since `self.devices is empty`. Run on Ubuntu 18.04.5 LTS with Tesla T4 GPU and 16 core CPU cluster. This issue does not occur when tf or tf2 is specified as the framework.

### Reproduction (REQUIRED)
rllib train --env=CartPole-v0 --run=PPO --config '{"num_workers": 10,"framework":"torch", "num_gpus":1}'

### Images of reproduction on my machine

![Screen Shot 2021-07-24 at 1 25 24 PM](https://user-images.githubusercontent.com/22321529/126880436-bc443bd8-159b-4658-bd87-90a80f8905c4.png)

![Screen Shot 2021-07-24 at 1 25 41 PM](https://user-images.githubusercontent.com/22321529/126880437-b057e167-2bf0-4fed-91cb-c45e799bfc15.png)

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mvindiola1** [comment]
Duplicate of  #16715
