### ISSUE TITLE
[RFC] Introduce `logging_metadata` option for Ray tasks & actors

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#17347]
It can currently be hard to associate logs with a given task/actor as our logs are broken out per-worker and do not have metadata associated with them. The way that users do this today is by rolling their own python `logger` and then configuring their logging stack to parse the logs accordingly.

For the typical user, we probably want something as simple as `name=<module.func_name>` for tasks and `name=<module.class_name>` for actors. This would be easily parsed and we could have a simple tutorial on how to integrate with logging stacks like Loki.

However, this doesn't quite work on its own for libraries, which often wrap user code in their own task/actor implementations. An example of this is the [Serve Replica class](https://github.com/ray-project/ray/blob/master/python/ray/serve/backend_worker.py#L33). If we were to just log the class name, it wouldn't be very useful to end users as it would always just say `ray.serve.BackendWorker` or similar. There may also be library-specific information that libraries would like to attach to messages. For example, in Serve we currently register a custom logger that attaches the deployment name and replica ID to log messages.

To satisfy both of these use cases, the proposal is to add a field called `logging_metadata` to task/actor options. This consists of a dictionary of key-value pairs that will be attached to messages logged using the Python `logging` module`. Example below:

```python
import logging
logger = logging.getLogger("ray")

@ray.remote
def my_func():
    print("hi") # No metadata will be attached, just "hi"
    logger.info("hello") # Metadata will be attached, in this case just the function name: "name='main:my_func' -- hello"
    
# Override the logging metadata with a different name and other info:
my_func.options(logging_metadata={"name": "super_special_func", "customer_id": "super_special_customer"}).remote()

# You can also set default logging metadata at the job level:
ray.init(job_config=JobConfig(logging_metadata={...}))
```

This would be used to replace the existing Ray Serve logger as follows (pseudocode for what's run in the Serve controller):
```python
BackendReplica.options(logging_metadata={"deployment": <deployment_name>, "replica": <replica_id}).remote()
```

The benefit in Serve aside from just generalizing what we have today is that users could override this with their own metadata if they wanted to (e.g., model version or whatever).

**Comment by edoakes** [comment]
Note that we could also attach the same tags to the tracing data exported via OpenTelemetry which would make for pretty good synergy across logging & tracing.

**Comment by richardliaw** [comment]
Only relevant for classes: What about using `def __repr__` somehow? Related to #17170 .

**Comment by pcmoritz** [comment]
Why a new API for this? Looking at https://www.structlog.org/en/21.1.0/getting-started.html it seems very natural to me to do something like
```
from structlog import get_logger

logger = get_logger()

@ray.remote
def my_func():
    log = logger.bind(name="super_special_func", customer_id="super_special_customer")
    log.msg("hello")
```

The advantage here is that it will work for both Python functions as well as Ray tasks. I assume for other structured logging libraries there would be similar capabilities.

**Comment by pcmoritz** [comment]
For the `BackendReplica` use case, the actual class name could just be an argument to the constructor and then it can do `self.log = logger.bind(...)` in the constructor.
