### ISSUE TITLE
[tune] Expose experiment settings to Searchers and Schedulers

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#17346]
### Describe your feature request

It should be possible for Searchers and Schedulers to access experiment settings. Something like this:

In searcher/scheduler:
```python
    def set_search_properties(self, metric: Optional[str], mode: Optional[str],
                              config: Dict, experiment: Experiment) -> bool:
```

In `tune.run` (line 434):
```python
    if config and not search_alg.set_search_properties(metric, mode, config, experiments[0]):
```

This will allow to eg. receive information about time budget, allowing for deadline-based logic in the searcher/scheduler.

**Comment by Yard1** [comment]
cc @richardliaw

**Comment by xwjiang2010** [comment]
I did a little survey of the current scheduler/searcher APIs.

There seems to be at least 3 similar/potentially conflicting way of specifying scheduler/searcher behavior:
- when they are initialized (this can be done by user, outside of tune.run()'s implementation, or done in tune.run())
- set_search_properties API. In the case of searcher, this interface is extended to take `config: Dict`. In example `blendsearch_example.py`, this construct is used to pass in `time_budget_s`. (can be called both outside of tune.run() and within)
- add_configurations(List[Experiment]) API for searcher. (called in tune.run())

The following questions may worth discussion:
- How are these APIs different?
- what is the ideal state we want to achieve in terms of defining scheduler/searcher behavior?
- where should user input certain config, e.g. time_budget_s? Through tune.run(xxx) or through initializing Scheduler or both? If the input configs somehow conflict, which one takes priority?

**Comment by richardliaw** [comment]
This is a great set of questions. Ignoring schedulers for now, a couple comments:

> add_configurations(List[Experiment]) API for searcher. (called in tune.run())

I think this is basically only used to specify the number of samples used in searcher?

> what is the ideal state we want to achieve in terms of defining scheduler/searcher behavior?

Ideally each config value will be specified in only one place. The searcher init function should be the landing place for all optimization algorithm-specific parameters. Right now we have some overlap, like `metric/mode/time_budget_s`. Ideally they should live in tune.run (or the top level execution declaration). Some are duplicated due to backwards compatibility. 

But some more examples might be helpful here -- maybe you can take one of the more confusing APIs and post so that we can go over it?

cc @krfricke

**Comment by Yard1** [comment]
@xwjiang2010 The searcher/scheduler initialization always takes priority over `set_search_properties`. That method is called in `tune.run`, to set some common properties like config, mode and metric to ensure that they need not to be set again in searcher/scheduler initialization.

Config dict, ideally, should not contain any searcher/scheduler properties. `time_budget_s` in blendsearch should rather be set during initalization as an argument, or, as proposed in this issue, to allow it to be ommited and set automatically through `set_search_properties`, based on the argument passed to `tune.run`.

Let us take an imaginary scheduler that requires information about the deadline. Currently, it would need to be used like this:
```python
scheduler = DeadlineScheduler(time_budget_s=100)

tune.run(config, time_budget_s=100, scheduler=scheduler)
```

As can be seen, the information about time budget needs to be set twice, as right now that information is not passed through `set_search_properties`, called inside `tune.run`. With the proposed change, the usage would be as follows:

```python
scheduler = DeadlineScheduler()

tune.run(config, time_budget_s=100, scheduler=scheduler). # scheduler has access to time_budget_s value through an Experiment object passed in `set_search_properties`
```
