### ISSUE TITLE
[rllib] tensorboard events file not written for DQN since 1.5.0

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#17366]
### What is the problem?

Tensorboard events file isn't outputted during DQN or Apex training since Ray 1.5.0

Ray version: 1.5.0
Tensorflow version: 2.4.0
OS version: Ubuntu 20.04 LTS

### Reproduction (REQUIRED)

```python
from ray import tune
from ray.rllib.agents.dqn import DQNTrainer
tune.run(DQNTrainer, config={"env": "CartPole-v0"}, stop={"timesteps_total": 1e4})
```

Check console output for output directly:

```shell
2021-07-27 14:19:13,894	INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8266
== Status ==
Memory usage on this node: 75.0/371.2 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/96 CPUs, 0/0 GPUs, 0.0/202.36 GiB heap, 0.0/90.72 GiB objects
Result logdir: /home/ubuntu/ray_results/DQN_2021-07-27_14-17-05
...
```

Events file not found where it should be:

```shell
$ ll ~/ray_results/DQN_2021-07-27_14-17-05/DQN_CartPole-v0_51e0c_00000_0_2021-07-27_14-17-05/
total 108
drwxrwxr-x 2 ubuntu ubuntu  4096 Jul 27 14:17 ./
drwxrwxr-x 3 ubuntu ubuntu  4096 Jul 27 14:17 ../
-rw-rw-r-- 1 ubuntu ubuntu    26 Jul 27 14:17 params.json
-rw-rw-r-- 1 ubuntu ubuntu    35 Jul 27 14:17 params.pkl
-rw-rw-r-- 1 ubuntu ubuntu 19103 Jul 27 14:17 progress.csv
-rw-rw-r-- 1 ubuntu ubuntu 73344 Jul 27 14:17 result.json
```

This issue is reproduced with `ApexTrainer`
This issue is NOT reproduced with Ray <= 1.4.1 or other algorithms like PPO

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by krfricke** [comment]
Hi @antoine-galataud, this has been introduced in https://github.com/ray-project/ray/pull/16695.

The original problem has been fixed in TensorboardX 2.4, so I created a PR to revert these changes in #17403.

For the meantime, you can pass the logger directly:

```
from ray.tune.logger import TBXLoggerCallback
# ...
tune.run(
    # ...
    callbacks=[TBXLoggerCallback()]
)
