### ISSUE TITLE
How to efficiently collect rollouts with ray multi-processing?

### ISSUE THREAD

**Issue by sabeaussan** [ray-project/ray#17370]
I'm working on a project where I need to collect rollouts to fill a dataset and then train a model on it. I'd like to collect these rollouts in parallel to speed up the process so I'm trying to use the multi-processing provided by the ray library :

    import time
    import ray
    
    ray.init()
    
    @ray.remote
    class MainActor:
        def __init__(self):
            self.data_set = []
    
        def process_item(self, item):
            # process incoming item
            item+=1
            return item
    
        def append(self, val):
            # add item to data set after processing it
            item = self.process_item(val)
            self.data_set.append(item)
    
        def train(self):
            # train on datatset
            return len(self.data_set)
    
    main_actor = MainActor.remote()
    
    @ray.remote
    def rollout_collector(main_actor):
        t = time.time()
        for i in range(40000):
            main_actor.append.remote(i)
        print("time per rollout : ",time.time() - t)
    
    
    t = time.time()
    ray.get([rollout_collector.remote(main_actor) for i in range(3)])
    ray.get(main_actor.train.remote())
    print("total time with multi-processing: ",time.time() - t)
    
    # ============================== Single process ================================
    
    class MainActor:
        def __init__(self):
            self.data_set = []
    
        def process_item(self, item):
            # process incoming item
            item+=1
            return item
    
        def append(self, val):
            # add item to data set after processing it
            item = self.process_item(val)
            self.data_set.append(item)
    
        def train(self):
            # train on datatset
            pass
    
    main_actor = MainActor()
    t = time.time()
    for i in range(120000):
        main_actor.append(i)
    main_actor.train()
    print("total time with single process : ",time.time() - t)

The rollout_collector collect items and then store them, after processing, inside the MainActor to finally train on it. However, this method is extremely slow :

[![enter image description here][1]][1]

Each rollout when using ray take as much as 20 sec compare to 0.12 sec without ray and multi-processing. I have one cpu for the main actor and 3 for the rollout_collectors.
I don't think I can store the rollouts inside the rollout_collector workers and then send everything to the main actor as I'm using reservoir sampling for the training. Furthermore, I get a really long execution time for a very simple function when using ray : the training function on MainActor juste return the length of the dataset but it still take 20 sec to execute. 

So my question is Am I doing something wrong ? What would be the best way to achieve my goal ?

  [1]: https://i.stack.imgur.com/tV4f6.png

**Comment by krfricke** [comment]
Hi @sabeaussan, I think the answer in https://stackoverflow.com/questions/68550901/how-to-efficiently-fill-a-list-with-ray-multi-processing is pretty comprehensive.

Basically you are queuing 120,000 calls to `main_actor.append.remote()` and all of these have to be executed sequentially. This is a huge scheduling overhead. And this becomes much more apparent for very trivial workloads - iterating through a loop takes microseconds, while communicating with the main actor takes much longer. 

For realistic workloads, you will probably see huge speed ups compared to a single threaded approach.

If you're sample collections are trivial or take only subseconds to sample, consider batching them to lower the serialization and communication costs incurred by sending the data to the main actor.

**Comment by sabeaussan** [comment]
Yes, thx for the clarification.
