### ISSUE TITLE
[lineage][RFC] Per-function API for enabling lineage reconstruction

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#17379]
### Describe your feature request

Add a separate decorator for allowing tasks to be re-executed upon object store failure.

TODO: Add details and examples.

**Comment by ericl** [comment]
Is this different from `max_retries=0` or is it intended as a separate flag?

**Comment by stephanie-wang** [comment]
I was thinking a separate flag like `enable_reconstruction` or something. One issue with the `max_retries` parameter is we're using it both for re-executing failed tasks and for re-executing a task that's already completed during reconstruction.
