### ISSUE TITLE
[Core] Logging INFO Messages are not showing

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#17374]
Even though the logging level for `ray.init()` is configured to INFO, the INFO log messages do not show up.

Running this:
```
import ray
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

ray.init(log_to_driver=True, logging_level=logging.INFO)

@ray.remote
def t():
	logger.error("Error")
	logger.warning("Warning")
	logger.info("Info")
	logger.critical("Critical")


ray.get(t.remote())
```

Output:
```
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2021-07-27 14:31:48,786	INFO services.py:1251 -- View the Ray dashboard at http://127.0.0.1:8265
(pid=57943) Error
(pid=57943) Warning
(pid=57943) Critical
```

cc @rkooo567

**Comment by sirius5871** [comment]
I am also facing this issue and it is not possible for me to change the logging level to either `debug` or `warning` for the whole code since many of these logs are being used in downstream systems.

Is there any workaround or update on this issue?

Thanks.

**Comment by rkooo567** [comment]
You should set the logger level per task / actor's init method https://docs.ray.io/en/master/ray-observability/ray-logging.html#how-to-set-up-loggers. I think we should have some better high level APis to configure logs

**Comment by hora-anyscale** [comment]
Per Triage sync: correct usage is: 

ray.init(log_to_driver=True, logging_level='info')

**Comment by pcmoritz** [comment]
Actually, the documentation is wrong here -- see the "Parameters" section in https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-init -- can you fix that @amogkam ?

**Comment by amogkam** [comment]
@rkooo567 can you confirm if this is resolved and make the necessary documentation changes if so?

**Comment by rkooo567** [comment]
We have documentation regarding how to set logger. `ray.init(log_to_driver=True, logging_level='info')` is not propagated to workers. It is only for logs from the driver internal ray logs. I think it is more like we don't have APIs to propagate logger config to all workers yet.

**Comment by rkooo567** [comment]
Example API that other systems support worker loggers https://www.distributedpython.com/2018/11/06/celery-task-logger-format/

**Comment by kevin85421** [comment]
Currently, users can propagate logging configuration to all worker processes within a job via `worker_process_setup_hook`. See [this doc](https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html) for more details. This issue is also duplicate with #39712 #23385.
 
```python
# driver.py
def logging_setup_func():
    logger = logging.getLogger("ray")
    logger.setLevel(logging.DEBUG)
    warnings.simplefilter("always")

ray.init(runtime_env={"worker_process_setup_hook": logging_setup_func})

logging_setup_func()
```
