### ISSUE TITLE
How should I schedule a task to run on a specified node in a ray cluster? 

### ISSUE THREAD

**Issue by YeahNew** [ray-project/ray#17387]
Ray can schedule tasks to other nodes according to the usage of node resources, but I now need to schedule a task to a specific machine in the ray cluster.
For example, datatmp = StoreIntoObjectStore(df,num_shards,batch_size), I hope to assign this task to a fixed machine to run in ray cluster instead of randomly assigning it through the ray scheduler.
Can this be done? I haven't seen ray provide related API to operate?
Looking forward to your reply~

**Comment by richardliaw** [comment]
Hey @YeahNew ! 

Which machine do you want to run this on (what's special about it), and why doesn't the random assignment work?
