### ISSUE TITLE
[tune] Make `local_dir` and `logdir` consistent

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1738]
### Describe the problem
Right now, `local_dir` and `logdir` are used across Tune in an inconsistent fashion. We should decide on one thing and use it throughout.

**Comment by ericl** [comment]
How about we rename `local_dir` to `ray_results_dir` (and perhaps remove it from the examples since ~/ray_results should work fine for most users).

**Comment by richardliaw** [comment]
Closing because not an issue.
