### ISSUE TITLE
[doc][tune]Link broken in Tune's page.

### ISSUE THREAD

**Issue by amavilla** [ray-project/ray#17394]
I faced 404 error when I clicked the follow link "Move your models from training to serving on the same infrastructure with [Ray Serve](https://docs.ray.io/en/master/tune/serve/index.html)".

The link broken is in [this Tune page](https://docs.ray.io/en/master/tune/index.html#).

I would like to make the PR, if the correct URL is "https://docs.ray.io/en/master/serve/index.html".

**Comment by richardliaw** [comment]
Yep, your suggestion looks right -- make a PR?

**Comment by amavilla** [comment]
Thank you  for your quick reply.
Sure. I'd like to make a PR.
