### ISSUE TITLE
Dashboard Agent Fails to Start in Docker Containers

### ISSUE THREAD

**Issue by nikunjm10** [ray-project/ray#17390]
### What is the problem?
Dashboard Agent Fails to start in docker containers because the dashboard agent tries to bind to the **host IP**, not the IP of the container. Furthermore, it is not possible to set the port of the dashboard agent.
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 1.4.1

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

1. Starting the docker container using the following command : -

```
sudo docker run -dit -p 3000:3000 -p 8265:8265 -p 6374:6374 -p 6379:6379 -p 6380:6380 -p 8000:8000 \
-p 8888:8888 -p 50050:50050 -p 50051:50051 -p 4000:4000 -p 4001:4001 -p 4002:4002 -p 4003:4003 \
-p 4040:4040 -p 10000-10200:10000-10200 -p 10201-10300:10201-10300 -p 37280:37280 -p 36458:36458 \
-p 38251:38251 -p 41091:41091 -p 44217:44217 -p 55711:55711 -p 58331:58331 -p 63084:63084 -p  \
63246:63246 -p 57454:57454 -p 63313:63313 -p 60504:60504 --shm-size=204.89gb \
--name nikunjJUL20 rayproject/ray:1.4.1-gpu bash
```

2. Docker `exec` into the container

Starting the ray using the following command : -

```
ray start --head --node-ip-address <ip of the machine> --port 10275 --dashboard-host 0.0.0.0 \
--dashboard-port 8265 --object-manager-port 4000 --node-manager-port 4001 --min-worker-port 10002 \
--max-worker-port 10042 --ray-client-server-port 10250  --gcs-server-port 4003 --num-cpus 0 \
--redis-shard-ports 10201 --metrics-export-port=10280
```

Facing the below error : -

```
2021-07-21 12:22:53,160 INFO scripts.py:206 – Connecting to Ray instance at <ip of the machine>:10275.
2021-07-21 12:22:53,161 INFO worker.py:736 – Connecting to existing Ray cluster at address: <ip of the machine>:10275
Active breakpoints:
Enter breakpoint index or press enter to refresh: 2021-07-21 12:22:54,889 WARNING worker.py:1123 – The agent on node 648518b3d714 failed with the following error:
Traceback (most recent call last):
File “/usr/local/lib/python3.7/site-packages/ray/new_dashboard/agent.py”, line 326, in
loop.run_until_complete(agent.run())
File “/usr/local/lib/python3.7/asyncio/base_events.py”, line 587, in run_until_complete
return future.result()
File “/usr/local/lib/python3.7/site-packages/ray/new_dashboard/agent.py”, line 161, in run
await site.start()
File “/usr/local/lib/python3.7/site-packages/aiohttp/web_runner.py”, line 128, in start
reuse_port=self._reuse_port,
File “/usr/local/lib/python3.7/asyncio/base_events.py”, line 1389, in create_server
% (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address (‘IP of the machine’, 0): cannot assign requested address
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ijrsvt** [comment]
@fyrestone 
How is the dashboard agent used? 

The problem here is that
1. The IP used for the `dashboard_agent` should be `0.0.0.0` to allow it to bind correctly
2. The Port should be settable because it can be useful for users to specify this port if they only have a limited number of ports open between machines.

**Comment by ijrsvt** [comment]
WIP for Dashboard Agent port specification: https://github.com/ray-project/ray/pull/17392

WIP for allowing bind to `0.0.0.0`: https://github.com/ray-project/ray/pull/17393

**Comment by fyrestone** [comment]
> @fyrestone
> How is the dashboard agent used?
> 
> The problem here is that
> 
> 1. The IP used for the `dashboard_agent` should be `0.0.0.0` to allow it to bind correctly
> 2. The Port should be settable because it can be useful for users to specify this port if they only have a limited number of ports open between machines.

Thanks for looking into this issue. Currently, the dashboard agent binds to the `node ip address` with port 0. It's better to specify an agent port when starting ray in a docker container, the default value of 0 can avoid port conflicts.

**Comment by fyrestone** [comment]
> WIP for Dashboard Agent port specification: #17392
> 
> WIP for allowing bind to `0.0.0.0`: #17393

Can we just apply the PR #17392? I think the `0.0.0.0` is too broad to bind, the PR #17393 is not necessary.

**Comment by ijrsvt** [comment]
Both are necessary @fyrestone. The problem with binding to the `Node IP` in Docker is that the host machine's IP address is `Node IP`, but the Docker container only has access to the Docker network. This means that trying to bind to the `Node IP` address results in:
```
OSError: [Errno 99] error while attempting to bind on address ('172.31.47.243', 58080): cannot assign requested address
```

A repro for this is:
* `docker run --rm -it -d rayproject/ray:1.4.1 bash`
* `docker exec` into the container and run:
`pip install ipython`
`ipython`
```
import aiohttp.web
app = aiohttp.web.Application()
runner = aiohttp.web.AppRunner(app)
await runner.setup()
site = aiohttp.web.TCPSite(runner, "172.31.47.243", "58080")
await site.start()
```


@fyrestone Do you know where the Raylet actually binds to the Node IP?

**Comment by fyrestone** [comment]
> Both are necessary @fyrestone. The problem with binding to the `Node IP` in Docker is that the host machine's IP address is `Node IP`, but the Docker container only has access to the Docker network. This means that trying to bind to the `Node IP` address results in:
> 
> ```
> OSError: [Errno 99] error while attempting to bind on address ('172.31.47.243', 58080): cannot assign requested address
> ```
> 
> A repro for this is:
> 
> * `docker run --rm -it -d rayproject/ray:1.4.1 bash`
> * `docker exec` into the container and run:
>   `pip install ipython`
>   `ipython`
> 
> ```
> import aiohttp.web
> app = aiohttp.web.Application()
> runner = aiohttp.web.AppRunner(app)
> await runner.setup()
> site = aiohttp.web.TCPSite(runner, "172.31.47.243", "58080")
> await site.start()
> ```
> 
> @fyrestone Do you know where the Raylet actually binds to the Node IP?

Yes, you are right. The raylet bind to `0.0.0.0` at https://github.com/ray-project/ray/blob/master/src/ray/rpc/grpc_server.cc#L34. The `node ip address` is the address reports to the GCS.

**Comment by ijrsvt** [comment]
@nikunjm10 This should be resolved now! Please let me know if it works now!

**Comment by nikunjm10** [comment]
@ijrsvt Thank you. Will it work in the ray 1.4.1?

**Comment by nikunjm10** [comment]
Okay Thank you @ijrsvt . I will try it

**Comment by nikunjm10** [comment]
@ijrsvt I am trying to install ray using this
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/f424de894fecf3fc6df48ab2808cd4ba6c0fcb40/ray-1.4.1-cp37-cp37m-centos7_x86_64.whl
But I am not able to, Can you help me with this also?

**Comment by ijrsvt** [comment]
@nikunjm10 How did you get this URL? We do not build Wheels with the tag `centos7`. We use `manylinux2014` instead.

The wheel build of the commit with #17393 should be:
[s3-us-west-2.amazonaws.com/ray-wheels/master/7b1c207be33892df6e556e7b5f7fb4b44c81c821/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl](s3-us-west-2.amazonaws.com/ray-wheels/master/7b1c207be33892df6e556e7b5f7fb4b44c81c821/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl)

**Comment by nikunjm10** [comment]
Ohkay, I myself created it using the document of the ray. But I made a mistake as there was no mentioning about the tags there. I will try using this, thank you

**Comment by nikunjm10** [comment]
Yes it solved the problem @ijrsvt . Thank you for your help. Do you have any idea when can I expect an official release of this PR?

**Comment by ijrsvt** [comment]
@nikunjm10 they will be in `Ray 1.6.0`!

**Comment by nikunjm10** [comment]
Okay Thank you @ijrsvt . I am closing this issue.
