### ISSUE TITLE
[doc][RLib] Explanation of words.

### ISSUE THREAD

**Issue by amavilla** [ray-project/ray#17395]
In [this page](https://docs.ray.io/en/master/rllib.html), there is the expression "Next, we’ll cover three key concepts in RLlib: Policies, Samples, and Trainers.".

I think "Sample batches" would be better than "Samples" and also "Training" instead of "Trainers", because the following title are "Sample batches" and "Training" where explain their functionalities.

I would like to make the PR, if this modification would make sense.

**Comment by richardliaw** [comment]
Hi @amavilla I think we should probably keep the text as-is. These are the actual "concepts" (as in, objects that you would interact with). 

Perhaps, we can link the words to the relevant sections?

**Comment by amavilla** [comment]
Yes, I think we can easily imagine the relevant sections as they are present explanation.
Thank you for your response and appreciating to hear your opinion. 

Could I close this issue by myself?
