### ISSUE TITLE
[core] `get_object_locations` returns empty node_ids for inlined objects

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#17402]
### What is the problem?

Latest master

`ray.experimental.get_object_locations` returns an empty node list for pandas dataframes returned by ray datasets.

I assume this has nothing to do with the ray datasets themselves but more with remotely created dataframes?

cc @rkooo567 @ericl 

### Reproduction (REQUIRED)

```
import ray
import pandas as pd

ray.init()

dfs = [ray.put(pd.DataFrame([0, 1, 2, 3])) for _ in range(2)]
ray.wait(dfs)

locations = ray.experimental.get_object_locations(dfs)
for obj, loc in locations.items():
    assert len(loc["node_ids"]) > 0, (obj, loc)

ds = ray.experimental.data.from_pandas(dfs)
parts = ds.to_pandas()
ray.wait(parts)

locations = ray.experimental.get_object_locations(parts)
ray.wait(locations)
for obj, loc in locations.items():
    assert len(loc["node_ids"]) > 0, (obj, loc)  # Fails!
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
> ray.wait(locations)

Is it because you have to ray.wait(num_returns=len(locations))?

**Comment by krfricke** [comment]
Unfortunately adding `num_returns` for either `locations` or `parts` does not change anything

**Comment by ericl** [comment]
This seems to be because the objects in the script above are too small, so they got inlined in the response (no location available since they are inline). Increasing the sizes works:

```
import ray
import numpy as np
import pandas as pd

ray.init()

dfs = [ray.put(pd.DataFrame(np.zeros(1024 * 1024))) for _ in range(2)]
ray.wait(dfs)

locations = ray.experimental.get_object_locations(dfs)
for obj, loc in locations.items():
    assert len(loc["node_ids"]) > 0, (obj, loc)

ds = ray.experimental.data.from_pandas(dfs)
parts = ds.to_pandas()
ray.wait(parts)

locations = ray.experimental.get_object_locations(parts)
for obj, loc in locations.items():
    assert len(loc["node_ids"]) > 0, (obj, loc)  # Fails!
```

@scv119 @rkooo567 perhaps we should be more explicit about this scenario?

**Comment by rkooo567** [comment]
Yeah agree. Maybe if the object is inlined, we can return only the current node?

**Comment by rkooo567** [comment]
Yeah agreed. Btw I feel like if the object is inlined, non of location returned is the right behavior (since we don't want to take into that location account of for locality calculation). Wonder if we just need to raise an exception if the location is not ready instead (and empty location means it is inlined).

**Comment by scv119** [comment]
We can also be more explicit: such as return a flag inlined = true

**Comment by krfricke** [comment]
Thanks for clarifying - I'll adjust my test scripts to use larger objects then.
I'd say an inline flag would be nice for verbosity, but I'll leave this to you all to decide.
