### ISSUE TITLE
[doc][sgd] Broken Link in SGD's page.

### ISSUE THREAD

**Issue by kimikuri** [ray-project/ray#17404]
### What is the problem?
In the page "https://docs.ray.io/en/master/raysgd/raysgd_ptl.html#pytorch-lightning-with-raysgd".  
I faced sorry page when I clicked the follow link "RaySGD includes an integration with Pytorch Lightning’s **LightningModule**.".

Now, it links to "https://pytorch-lightning.readthedocs.io/en/latest/lightning_module.html".

I would like to make the PR, if the correct URL is "https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html".

### Reproduction (REQUIRED)
![rayLink](https://user-images.githubusercontent.com/87696872/127320626-494e7207-a698-45fd-a231-70b56d19651d.png)

**Comment by krfricke** [comment]
That looks good - can you file the PR @kimikuri ?

**Comment by matthewdeng** [comment]
Fixed in https://github.com/ray-project/ray/pull/17423
