### ISSUE TITLE
Question: Get the currently used or idle resources from ray

### ISSUE THREAD

**Issue by youthmrg** [ray-project/ray#17428]
I have a requirement: Before submitting a task to the Ray cluster, I need to determine whether the current cluster load (resource usage) exceeds the threshold. If the load is too heavy, I will choose not to submit a new task temporarily.

So, does Ray provide related APIs to get the currently used or idle resources (CPU, GPU, Memory, etc.) of the cluster, just like what the dashboard shows.

**Comment by krfricke** [comment]
Does `ray.available_resources()` help?

**Comment by youthmrg** [comment]
Thank you for your quick reply :)

### System information
- ray version: 1.4.1
- ray cluster config, created by kubernetes
> | Node   | Count | CPU  | Memory | GPU  |
> | ------ | ----- | ---- | ------ | ---- |
> | header | 1     | 8    | 16G    | 0    |
> | worker | 9     | 8x9  | 16Gx9  | 0    |
> | Total  | 10    | 80   | 160G   | 0    |

Ray provides two functions: `ray.cluster_resources()` and `ray.available_resources`, which are used to obtain all current and available resources of the cluster respectively. However, in actual use, I found that the results returned by the two are almost the same, even if the ray cluster has tasks running (some of the resources have been consumed, which can be seen from the dashboard).

The code I tested is as follows, and the result of the operation is shown in the figure below. So I think what `ray.available_resources` gets is wrong resource information. Is this a bug?
```python
try:
    import ray
    ray.util.connect('<cluester_ip>:<port>')
    
    avail = ray.available_resources()
    print("object_store_memory {}, memory {}".format(avail["object_store_memory"] / 2**30, avail["memory"] / 2**30))

    cluster = ray.cluster_resources()
    print("object_store_memory {}, memory {}".format(cluster["object_store_memory"] / 2**30, cluster["memory"] / 2**30))
finally:
    ray.util.disconnect()
    ray.shutdown()
```

And the output is as follows，it can be found that `ray.available_resources` shows that the total memory is about 102GB, but the dashboard shows that the memory is 149GB (this is more accurate), why the two information is inconsistent？

> object_store_memory 43.58939165342599, memory 102.55564995110035
> object_store_memory 44.589419171214104, memory 102.55564995110035

![image-20210730143143988](https://user-images.githubusercontent.com/42192409/127611389-80a5a943-5c67-4318-8bfe-571a83d4a7bf.png)

**Comment by youthmrg** [comment]
> Does `ray.available_resources()` help?

When no task is running, the output is as follows: 
> object_store_memory 44.589419171214104, memory 102.55564995110035
> object_store_memory 44.589419171214104, memory 102.55564995110035

This is almost the same as the output when there is a load.
