### ISSUE TITLE
[Serve] tag client-side autoscaling/updating logs with `deployment=`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#17446]
### Describe your feature request
Currently, logs are tagged with `component=serve`, `backend=<backend_tag>` (soon to be `deployment=`), and `replica=<replica_tag>`, but only if the logs originate from inside a replica.  However, we probably want these tags (the first two, at least) to also show up on Serve client logs, such as the logger.info calls in `api.py`.  E.g. "Updating deployment {deployment} to version {version}" and "2021-08-05 08:48:31,568      INFO backend_state.py:869 -- Adding 1 replicas to backend 'hello'."
For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by edoakes** [comment]
Oh great point @architkulkarni. Do you want to make a small patch for this? We'll want to make sure we somehow keep the formatting in sync across the different loggers.
