### ISSUE TITLE
Did we clear up Function Table?

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#17458]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
We have a user who uses RayClient to connect to Ray cluster and execute some remote functions. 4 hours after the cluster being started they found the memory of redis exceeds 5GiB and found it seems like most of the big key is `FunctionTable:`.
I've checked the codes and found we only rpush data into FunctionTable: key but not see somewhere they are deleted or cleared.

Just to confirm if the analysis is right and what should we do if it is?

![image](https://user-images.githubusercontent.com/5276001/127610622-27ea7d04-4c58-47f4-bf81-2199c9062356.png)
*The memory of redis on aliyun reaches 5.69GB*
![image](https://user-images.githubusercontent.com/5276001/127610677-44ac49e0-1f26-4067-b039-7513daedeb3c.png)
*Top 20 of big key*
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
We currently don't properly GC functions from GCS. https://github.com/ray-project/ray/issues/8822

**Comment by rkooo567** [comment]
I think cleaning this up is not that easy right now without having full scanning of Redis table. One of possible future implementations are; 

- If ownership sharing is supported, we can just use function definition as a task / actor dependency (ray.put(func_or_class_def))
- If Redis pubsub is removed, we can having worker <-> function reference counting table and GC when workers are dead. 

But, I'd love to hear your ideas

**Comment by WangTaoTheTonic** [comment]
Thanks for reply SangBin.
Another thing we can discuss or do with cleaning up this table is that we maybe need to refactor the `list` type to flat table so that we can store and delete function using kv manager(so we can remove direct redis client using), which comes up from https://github.com/ray-project/ray/issues/15353.

**Comment by rkooo567** [comment]
I see. In that case, how's the function def import work? Are we getting it on demand? (rn, all definitions are propagated to all workers of the same job). Also, how do you plan to GC them?
