### ISSUE TITLE
New error today : ERROR:ray._private.services:Failed to start the dashboard: Failed to start the dashboard, return code 1.

### ISSUE THREAD

**Issue by AlexandreBourrieau** [ray-project/ray#17461]
Hello,

From today I got new error when starting ray.init on google colab :

` ERROR:ray._private.services:Failed to start the dashboard: Failed to start the dashboard, return code 1. The last 10 lines of /tmp/ray/session_2021-07-30_09-57-08_631192_291/logs/dashboard.log`

```
(raylet) Traceback (most recent call last):
(raylet)   File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 366, in <module>
(raylet)     raise e
(raylet)   File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 354, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/agent.py", line 130, in run
(raylet)     dashboard_consts.RETRY_REDIS_CONNECTION_TIMES)
(raylet)   File "/usr/local/lib/python3.7/dist-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
(raylet)     return await aioredis.create_redis_pool(
(raylet) AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
```

Yesterday all was OK with the same code...

**Comment by Curt-Park** [comment]
Currently, ray doesn't specifies `aioredis` version:
https://github.com/ray-project/ray/blob/master/python/requirements.txt#L9

Unfortunately, the major update of `aioredis`, which was done a few hours ago, makes conflicts with ray.
You should downgrade `aioredis == 1.3.1`.

**Comment by AlexandreBourrieau** [comment]
Oh ok thanks you very much work like a charm :-)
