### ISSUE TITLE
[RLLIB] range takes no keyword arguments

### ISSUE THREAD

**Issue by o0olele** [ray-project/ray#17477]
### What is the problem?
~~~shell
TypeError: range() takes no keyword arguments
~~~
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 1.4.1
python version: 3.7.3
tf version: 2.5
OS: windows

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

when using attention net with ppo with config:
~~~json
{
   "use_attention": True,
    "attention_use_n_prev_actions": 2,
    # Whether to feed r_{t-n:t-1} to GTrXL.
    "attention_use_n_prev_rewards": 2,
}
~~~
and the source code in `master/rllib/models/tf/attention_net.py:808`
~~~python
                    for i in range(
                        self.use_n_prev_actions,
                        step=self.action_space.shape[0]):
~~~
If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by o0olele** [comment]
Then, when fixed the problem above, I got another problem:
~~~shell
DataType string for attr 'TI' not in list of allowed values: uint8, int32, int64
~~~

I found no way to fix this one, finally i set "attention_use_n_prev_actions" and "attention_use_n_prev_rewards" to 0.

**Comment by mvindiola1** [comment]
Hi @o0olele,
Do you have a reproduction script you could provide?

**Comment by o0olele** [comment]
> Hi @o0olele,
> Do you have a reproduction script you could provide?

@mvindiola1 for `TypeError: range() takes no keyword arguments`, i think the code should be:
~~~python
for i in range(0, self.use_n_prev_actions, self.action_space.shape[0]):
~~~

**Comment by o0olele** [comment]
https://github.com/ray-project/ray/blob/e812691909710ba3db4df894ddb0b2d9230095a4/rllib/models/tf/attention_net.py#L808

using multiaction and attetion net.

**Comment by mvindiola1** [comment]
Nice find @o0olele <https://github.com/o0olele>. Can you prepare a PR with
the fix?

**Comment by o0olele** [comment]
The PR is done, @mvindiola1

**Comment by mvindiola1** [comment]
@richardliaw @sven1977 PR for your review.

**Comment by juliusfrost** [comment]
Thanks for bringing this up. Your PR was just merged :)
