### ISSUE TITLE
Issue on page /tune/tutorials/tune-pytorch-lightning.html

### ISSUE THREAD

**Issue by import-antigravity** [ray-project/ray#17487]
The code snippet:

```python
    if checkpoint_dir:
        # Currently, this leads to errors:
        # model = LightningMNISTClassifier.load_from_checkpoint(
        #     os.path.join(checkpoint, "checkpoint"))
        # Workaround:
        ckpt = pl_load(
            os.path.join(checkpoint_dir, "checkpoint"),
            map_location=lambda storage, loc: storage)
        model = LightningMNISTClassifier._load_model_state(
            ckpt, config=config, data_dir=data_dir)
        trainer.current_epoch = ckpt["epoch"]
```

Does using `load_from_checkpoint()` still lead to errors? I've found from testing on my own that it doesn't seem to but I haven't tested it thoroughly. I don't know the last time this page was checked.

**Comment by souravraha** [comment]
I have already suggested a solution to this. Using resume_from_checkpoint ensures that the full training state is restored. Hence, it is preferable to passing load_from_checkpoint in the LightningModule. You may find https://github.com/ray-project/ray/pull/17437/files instructive in this regard.

**Comment by DBraun** [comment]
In my case I wanted to resume a checkpoint and do `trainer.predict()` without first calling `trainer.fit()`. That required me to first do `trainer.checkpoint_connector.resume_start()`
