### ISSUE TITLE
Fail to run ray Java API demo on Mac M1 laptop, is this a compatibility problem?

### ISSUE THREAD

**Issue by huxiaoxiang** [ray-project/ray#17484]
### What is the problem?
I installed ray on my Mac(M1 chipset, 8C 16G). Running Python Demo succeeded. But Failed on running Java Demo.
OS: MacOS Big Sur, 11.3.1
python: 3.8.10
JDK:  1.8.0_275(Zulu 8.50.0.1017-CA-macos-aarch64)
ray:    1.4.1

### Reproduction (REQUIRED)
package io.ray.example.hello_world;

import io.ray.api.ObjectRef;
import io.ray.api.Ray;

public class HelloWorld {

  public static void main(String[] args) {
    Ray.init();

    ObjectRef<String> hello = Ray.task(() -> "Hello").remote();
    ObjectRef<String> world = Ray.task(() -> "World").remote();
    String result = Ray.task((String h, String w) -> h + ", " + w + "!", hello, world).remote().get();

    System.out.println("Result string is" +  result);

    Ray.shutdown();
  }
}

I always get the error: 
>  Exception in thread "main" java.lang.UnsatisfiedLinkError: ~/Library/Caches/JNA/temp/jna218612762451701584.tmp: dlopen(~/Library/Caches/JNA/temp/jna218612762451701584.tmp, 1): no suitable image found.  Did find: ~/Library/Caches/JNA/temp/jna218612762451701584.tmp: no matching architecture in universal wrapper

Even though I build from source of Ray master repository and get a version of v2.0.0.dev0, the problem still exists.
Any help is appreciate!

- [ Y] I have verified my script runs in a clean environment and reproduces the issue.
- [ Y ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jovany-wang** [comment]
@huxiaoxiang  Do you build from source by the following steps?
1. pip install `python` -e . -v
2. cd java & mvn clean install

**Comment by huxiaoxiang** [comment]
> @huxiaoxiang Do you build from source by the following steps?
> 
> 1. pip install `python` -e . -v
> 2. cd java & mvn clean install

Actually, I built ray following the build instruction on ray.io.
1. dependency: python=3.8.10, cython=0.29.15, bazel=3.2.0
2. 
cd ray/python
pip install -e . --verbose

![image](https://user-images.githubusercontent.com/4969695/128141628-83b6e23d-9460-419a-938d-fa8d47ba9d8a.png)
![image](https://user-images.githubusercontent.com/4969695/128141647-5bbec068-921f-4015-bc29-dab4bef8a693.png)

**Comment by jovany-wang** [comment]
Right now Ray has been supported on M1. Feel free to reopen this or open a new issue if it cannot work on your environment.
