### ISSUE TITLE
[Dashboard][event] keep event agent report position when restarted

### ISSUE THREAD

**Issue by fyrestone** [ray-project/ray#17496]
- Problem
  - Currently, our event agent only reports events files which mtime > time.time() - 30 minutes. So, duplicated events may be reported and filtered by the event head.
- Solution
  - The event head records the report position. The event agent reports events from last position after restarted.

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by rkooo567** [comment]
Restart feature is not there anymore.
