### ISSUE TITLE
Add large scale IO tests to nightly dashboard

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17493]
In addition to the binary files read test, we should test the following additional workloads against S3 in nightly tests:

```
# first, erase the scratch directory
aws s3 rm -rf s3://bucket/path
# time parquet write
ray.data.range_arrow(10e9).write_parquet("s3://bucket/path")
# time parquet read
ray.data.read_parquet("s3://bucket_path").map_batches(lambda b: [0])
```

And repeat for JSON, CSV. In total this test should emit 6 metrics (json read, json write, csv read, csv write, parquet read, parquet write). It's also acceptable to emit a single combined timing.

**Comment by clarkzinzow** [comment]
@ericl Is this still a P1, or more of a P2?

**Comment by ericl** [comment]
I think we have enough coverage this is a P2.
