### ISSUE TITLE
[tune], [rllib] airoedis dependency version

### ISSUE THREAD

**Issue by Blubberblub** [ray-project/ray#17534]
I did a fresh install via pip install 'ray[rllib]' to test the hierarchical_training.py example on a WSL2 in windows. During this aioredis 2.0.0 is installed as a dependency. However when running the example that is using tune i get `AttributeError: module 'aioredis' has no attribute 'create_redis_pool'.

The create_redis_pool method is not used in airoedis version after 1.3.1. [https://githubmemory.com/repo/madkote/fastapi-plugins/issues/15](url)
The issue can be solved by downgrading aioredis 1.3.1. I'm not sure if this just needs an update in the  dependencies or higher version features are used elesewhere.

Python version: 3.8.5
Ray version: 1.5.0
TF-version: 2.4.1

**Comment by richardliaw** [comment]
@Blubberblub thanks a bunch for this post!

Yeah this is an update in the dependencies that we had to fix urgently last week. 

For future reference (for ray < 1.5.1), please run `pip install -U aioredis<2.0`.

See #17472.
