### ISSUE TITLE
ray-minimal installation causes metrics to hang (fix docs)

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#17557]
[This example](https://docs.ray.io/en/master/ray-metrics.html?highlight=metrics#application-level-metrics) and everything related metrics no longer work with ray minimal installation. Even though the error message mentions "dashboard will only be usable via `pip install 'ray[default]'`", **(prometheus) metrics** is not in the list and this is not called out in documentation.

**Comment by richardliaw** [comment]
I believe this is fixed.
