### ISSUE TITLE
How should we do resource requirements and scheduling for actor creation tasks?

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1756]
Summarizing some thoughts from discussions with @ericl @richardliaw @pcmoritz @atumanov and @stephanie-wang.

_Some details about the current approach:_
- When we create an actor, e.g., with `a = Actor.remote()`, an **actor creation task** is submitted (as a regular task, and executed on some worker (turning that worker into the actor).
- When a method is invoked on an actor, e.g., with `a.method.remote()`, an **actor method task** is scheduled on the actor and executed by the actor.
- The actor creation task may require resources (e.g., 1 CPU and 1 GPU). These resources are acquired for the lifetime of the actor. By default, if nothing is specified in the `@ray.remote` decorator, then no resources are required by the actor creation task.
- The actor methods may also require resources (currently the only options are 0 CPUs or 1 CPU, but this would be easy to change). These resources are acquired for the duration of the method. Currently, if nothing is specified in the `@ray.remote` decorator, then 1 CPU is required by each actor method, and otherwise 0 CPUs are required by each actor method.

_Properties we'd like to have:_
1. **Actor bin-packing.** That is, if we have 20 machines, each with 10 CPUs, in our cluster, and we create 200 actors, then the actors are evenly spread throughout the cluster (and similarly if the machines are unequal in size then more actors are on the bigger machines).
2. **Things shouldn't hang. ** That is, if you're running a script and you create 9 actors and you have 8 CPUs, the script should still run. Or if it really can't run, then you should get a good error message or exception. The concern about this is why the default behavior is to associate 0 CPUs with the actor lifetime.
3. Excess actors should be balanced as well. So if you have 20 machines, each with 10 CPUs, and you create 400 actors, then you should get 20 per machine.

_Challenges:_
1. The above properties are a bit at odds. To achieve them, we may need the ability to specify more of an "anti-affinity" behavior, but that will likely require resources with different semantics than the resources we currently use.
2. The scheduling of the actor creation task must take into account the resource requirements of the actor methods. Currently, each actor method only takes into account its own resource requirements, but if a method requires 2 CPUs and the actor creation task requires 1 CPU, then it could get scheduled on a machine with only 1 CPU, which would be a problem. We currently work around this restricting the possible method resource requirements and preventing any actors from being created on machines with 0 CPUs.

**Comment by ericl** [comment]
Another challenge is autoscaling, which is at odds with "not hanging". If a cluster is autoscaling, you might want to wait for nodes to get added instead of committing to placing the actors immediately.

**Comment by robertnishihara** [comment]
#1757 is a hack to improve actor load balancing for actors that do not acquire any lifetime resources.
