### ISSUE TITLE
[autoscaler][core] Verify stability of resource protos in CI.

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#17562]
### Describe your feature request

We need to implement a test in the CI that automatically verifies if the resource proto interface between autoscaler and GCS is modified.
This will make it much less likely that Ray/Autoscaler version compatibility is broken due to human error. 

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by DmitriGekhtman** [comment]
cc @AmeerHajAli @wuisawesome @wuisawesome @stephanie-wang

**Comment by DmitriGekhtman** [comment]
Shifting to P1 given that responsible parties are overcommitted with other work and don't intend to solve this in the next couple of days.

**Comment by AmeerHajAli** [comment]
will be handled in the autoscaler planning.

**Comment by wuisawesome** [comment]
Closing as we're tracking the gcs/autoscaler interface elsewhere.
