### ISSUE TITLE
What is expected of file_mounts in cluster.yaml is not clear

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#17594]
### Describe your feature request

Depending on whether raw AMI or docker container is launched, file_mounts argument expect different path. /home/ubuntu vs /home/ray/. What is expected is not clear for users. example-full.yaml does not mention this.

**Comment by richardliaw** [comment]
@ijrsvt @DmitriGekhtman can you take a look? This is quite confusing behavior.

**Comment by DmitriGekhtman** [comment]
@xwjiang2010 I think `~` should resolve correctly to the home directory in both cases? Let us know if that works.

Either way, the documentation could be improved here.

By the way, you may be interested in checking out the new [runtime environments](https://docs.ray.io/en/master/advanced.html#runtime-environments-experimental) functionality for syncing files.
I think runtime envs will be the preferred way of managing Ray dependencies in the future.

**Comment by xwjiang2010** [comment]
Thank you!!
Sounds good. I'll give ~ a try next time. May be worthwhile to update the documentation, especially since we have so many ways of achieving similar things, including the newly come up runtime environment.
