### ISSUE TITLE
[tune] Privatize TrialExecutor interface

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#17593]
### Describe your feature request
We want to start privatizing TrialExecutor.

### Why?
The separation of a TrialExecutor and RayTrialExecutor is unnecessary and confusing.

Two classes are highly coupled.
- TrialRunner is defaulting to use RayTrialExecutor and directly calling its method that is not even in TrialExecutor interface (e.g. `get_staged_trial`)
- TrialExecutor's implementation is relying on RayTrialExecutor's implementation (e.g. `has_resources_for_trial`)

Also on a high level, RayTrialExecutor together with the underlying resource management logic is the core offering of Ray. Unclear if there is any customized implementation TrialExecutor other than RayTrialExecutor.

**Comment by xwjiang2010** [comment]
@krfricke @Yard1 @richardliaw

**Comment by krfricke** [comment]
I'd vote for eventually consolidating these classes into one. There is no discernible use case (anymore?) to implement an own trial executor. Also, in most cases it should then be possible to just inherit from `RayTrialExecutor` instead. 

Thus, we should deprecate the class and remove it in a future release.

**Comment by Yard1** [comment]
Agreed, though we should still do a depreciation cycle.
