### ISSUE TITLE
[tune] Confusing cpu flags

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1759]
### Describe the problem

Currently having to specify `cpu` and `driver_cpu_limit` is confusing. Rather we should take `cpu` and `worker_cpu`, which is clearer to explain (`driver_cpu_limit => cpu` and `cpu - driver_cpu_limit => worker_cpu`).

cc @richardliaw @eugenevinitsky

**Comment by ericl** [comment]
Possible new schema
```
{
    "cpu": <int> default=1,
    "gpu": <int> default=0,
    "reserve_extra_cpu": <int> default=0,
    "reserve_extra_gpu": <int> default=0,
    "strict": <bool> default=false,
}
```

**Comment by richardliaw** [comment]
merged with `driver_cpu_limit => cpu` and new field called `extra_cpu`
