### ISSUE TITLE
[Dataset] Write a dataset fail if the path doesn't exist

### ISSUE THREAD

**Issue by djdongjin** [ray-project/ray#17616]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Build from source, python 3.8.10, MacOS

When writing a dataset to a path that doesn't exist, it will fail. Is this expected or `ray` should create the output folder if not exist and then write the dataset to it? If it's not expected, I can send a PR to fix this.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
ds = ray.data.range_tensor(10000, shape=(3, 5))
ds.map_batches(lambda t: t + 2).show(2)
ds.write_numpy("/tmp/tensor_out_31231")   # a random folder that doesn't exist.

# same for write_csv api
ds = ray.data.range(100)
ds.write_csv("/tmp/dsafd12121") # random folder not exist
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
I agree we should probably create the directory if it doesn't exist! A PR would be great.

**Comment by djdongjin** [comment]
> I agree we should probably create the directory if it doesn't exist! A PR would be great.

Then I will try to send a PR today :)

**Comment by ericl** [comment]
Any update here?

**Comment by djdongjin** [comment]
Hi @ericl , I was able to cover the local file system situation, but not sure about the cloud storage situation (s3). I saw the file system checking happens in a lower level (pyarrow?) Any idea how we can check the file system here and create the path if it doesn't exist (only) in local file system?

**Comment by ericl** [comment]
Does the pyarrow filesystem API provide any such facility for this? Otherwise, not sure if we can handle that case.

**Comment by clarkzinzow** [comment]
@djdongjin Any progress here? It seems like `pyarrow.FileSystem.create_dir()` is idempotent, so for the write APIs that take a directory path argument, we could always try to create the directory after resolving the filesystem, e.g. here: https://github.com/ray-project/ray/blob/2ee1b90c17c7dec4483b8edc0ca55f3b58048104/python/ray/data/datasource/file_based_datasource.py#L117
