### ISSUE TITLE
[Log] When the driver is crashed with FATAL logs, it is not printed to the stdout.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#17621]
### What is the problem?

Currently, cpp core worker logs are logged to the file. It is usually fine, but for driver, it can cause issues. When the driver is crashed with FATAL error, that error message is only logged and not printed to the driver, which can give confusion that driver is crashed out of blue. It happens because our logger basically logs core worker logs to the file only. We should print the FATAL log to the stderr in this case. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
@ericl If we emit FATAL logs to stderr of core worker, it can also stream FATAL error to driver because core workers are child processes of raylet, and their stderr is redirected to the raylet's stderr (which is redirected to raylet.err I believe)

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/12893

**Comment by rkooo567** [comment]
Btw, this is technically different issue from #12893. For example, implementing this can solve #12893 as a side effect, but #12893 doesn't guarantee this will be supported (since driver will be killed before the message is published).
