### ISSUE TITLE
[tune] Pass in other arguments to Trainable Function

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1762]
### Describe the problem
I don't want to modify any of my code to use Tune; I just want to add a reporter parameter (and a tune configuration). 

See source code for example.

### Source code / logs
This is an example code that I want to change to Tune.

```python
def run_training(args):
    # create model
    model = models.__dict__[args.arch](args.pretrained)
    model = torch.nn.DataParallel(model).cuda()

    best_prec1 = 0

    # optionally resume from a checkpoint
   ...
```
This has a particular format for setting up a lot of non-hyperparam information. It would take 20 or 30 lines of modifications to fit the current Tune specification. Ideally, I would only want to modify 2 or 3 lines (passing in reporter, calling the reporter, and modifying the hyperparameter)

Part to change here:
https://github.com/ray-project/ray/blob/5c7ef34b054de9ca28328333189ccc788a7d121f/python/ray/tune/function_runner.py#L60-L70

**Comment by ericl** [comment]
How is it possible to not change the code? You still need to report your results and parse the args right?

**Comment by richardliaw** [comment]
Modified above description to clarify. See this:
https://github.com/ucbdrive/skipnet/pull/3

**Comment by ericl** [comment]
Can't you define a new function

`def train(config, reporter): run_training(args, config, reporter)`

that wraps the original function call?

**Comment by richardliaw** [comment]
I guess that's reasonable, although I suspect this isn't the first solution that people would think of...

I guess we can close this for now and if anyone has a complaint later on we can open this again

**Comment by nadavbh12** [comment]
Do you have a suggestion how I would to get around doing this with a custom `Trainable` class?
As I don't call the constructor explicitly, I don't see another option for passing parameters to it...

**Comment by richardliaw** [comment]
Hey @nadavbh12, sorry this slipped through the cracks. What are you trying to do?

**Comment by hershelm** [comment]
I believe the question is how to pass in arguments to the Trainable class (i.e., to `_setup(self)`). The approach I've been using is to add parameters to `config` in my train_spec, which is passed to `_setup(self)` and that works well. Interesting though, in an older approach, i simply loaded in args using an argparser, and it seemed that `_setup()` was also passed my dictionary of args somehow, and I was able to use that inside of `_setup()`.

**Comment by ericl** [comment]
I guess the args were serializable, so they were captured as part of the
class definition. Passing options through config is probably more robust
though and lets you parametrize args per trial.

**Comment by nadavbh12** [comment]
Sorry for late response, eventually I realized I could just pass it through config, which was than rather straightforward.

**Comment by YannisPap** [comment]
For anyone still interesting in this, you can use `functools.partial()` to pass any additional argument, **serialisable or not**.

Example:

```python
from functools import partial

import pandas as pd
from ray import tune
from ray.tune.suggest import ConcurrencyLimiter
from ray.tune.suggest.bayesopt import BayesOptSearch

config = {"a": tune.uniform(0, 1), "b": tune.uniform(0, 20)}

# I believe pandas dataframes are not serialisable
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})


def objective(x, run_params):
    return run_params["a"] * (x ** 0.5) + run_params["b"]


def trainable(run_params, data):
    print(data.head())  # Use the additional attribute however you want.
    for x in range(20):
        score = objective(x, run_params)

        tune.report(score=score)


enhanced_trainable = partial(trainable, data=df)


tune.run(
    enhanced_trainable,
    config=config,
    metric="score",
    mode="max",
    search_alg=ConcurrencyLimiter(
        BayesOptSearch(random_search_steps=4), max_concurrent=2
    ),
    num_samples=20,
    stop={"training_iteration": 20},
    verbose=2,
)


```
