### ISSUE TITLE
[Core] Make  WorkerCacheKey more extentional

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#17630]
### Describe your feature request

Currently `WorkerCacheKey` has three member: two map and one string.  I think we can make it more extentional. 

How about use one `std::unordered_map<std::string, std::string>` in `WorkerCacheKey`? We put key-value pairs into `WorkerCacheKey` on demand.

**Comment by jovany-wang** [comment]
I don't know what the best practice is for this issue yet, but it's necessary to refine it to avoid future bugs.
