### ISSUE TITLE
[Core] IDLE worker leaked

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#17646]
### What is the problem?

In Ray 1.5, we've seen that a head node running with outstanding number of worker nodes. This is an indication that we are not properly released/killed, probably a bug in worker_pool

### Reproduction (REQUIRED)
The simplest way is to run non_streaming_shuffle_1tb_5000_partitions nightly test in both prod or OSS env. When it close to OOM usually we will notice hunderds of idle workers.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by hora-anyscale** [comment]
Per Triage Sync: Closing
