### ISSUE TITLE
Error while killing actor started in non-current namespace

### ISSUE THREAD

**Issue by nikitavemuri** [ray-project/ray#17644]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Python 3.7, Ray `57b190c98770c0582d525076c261a104fc72a66a`

### Reproduction (REQUIRED)
```
import ray

ray.init()
# Start actor in non-current namespace
actor_name = "namespace1/actor_name"

@ray.remote
class A:
    pass

A.options(name=actor_name, lifetime="detached").remote()
a = ray.get_actor(actor_name)
print(
    f"Got actor '{actor_name}' ({a}) when "
    f"ray.get_runtime_context().namespace = {ray.get_runtime_context().namespace}"
)

ray.kill(a)
ray.get_actor(actor_name) # Error
```
This fails when getting the actor after it is killed with error:
```
(pid=gcs_server) [2021-08-06 11:53:42,818 C 49198 22243947] gcs_actor_manager.cc:247:  Check failed: iter != registered_actors_.end() 
(pid=gcs_server) *** StackTrace Information ***
(pid=gcs_server)     ray::GetCallTrace()
(pid=gcs_server)     ray::SpdLogMessage::Flush()
(pid=gcs_server)     ray::RayLog::~RayLog()
(pid=gcs_server)     ray::gcs::GcsActorManager::HandleGetNamedActorInfo()
(pid=gcs_server)     ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(pid=gcs_server)     boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server)     boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server)     boost::asio::detail::scheduler::run()
(pid=gcs_server)     boost::asio::io_context::run()
(pid=gcs_server)     main
(pid=gcs_server)     start
(pid=gcs_server)     0x0
```
This also fails with the same error when initially getting the actor handle if the actor is non-detached (`A.options(name=actor_name).remote()`)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
I think it is duplicate to https://github.com/ray-project/ray/issues/17629

**Comment by rkooo567** [comment]
Please re-open it is not.

**Comment by simon-mo** [comment]
@nikitavemuri looks like the fix is merged via https://github.com/ray-project/ray/pull/17670 (tyvm @rkooo567)! can you try rebase your PR?
