### ISSUE TITLE
[rllib] Torch multi GPU does not work with RNNs

### ISSUE THREAD

**Issue by jsuarez5341** [ray-project/ray#17653]
Latest Ray nightly on python 3.8, Ubuntu

```
import ray
import ray.rllib.agents.ppo as ppo]

ray.init()

config={
'framework': 'torch',
'num_gpus': 2, 
'model': {'use_lstm': True}, 
}

trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
for i in range(10):
   trainer.train() 
```

produces error:

ValueError: cudnn RNN backward can only be called in training mode In tower 0 on device cuda:0

**Comment by jsuarez5341** [comment]
@sven1977 Awesome work on multi gpu btw, just the one gotcha above :)

**Comment by sven1977** [comment]
Confirmed. This PR fixes the issue:
https://github.com/ray-project/ray/pull/17657
