### ISSUE TITLE
Image Pull secrets causes an error

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#17658]
### What is the problem?

After 208d997414986710b79022db99373f7f9a11e39e I get an error trying to deploy helm

### Reproduction (REQUIRED)

```
holden@hkdesktop:~/repos/ray/deploy/charts$ helm -n ray install example-cluster --create-namespace ./ray  
Error: template: ray/templates/raycluster.yaml:79:24: executing "ray/templates/raycluster.yaml" at <.Values.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets
```
- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by tekumara** [comment]
Same issue here.

To reproduce:

```
$ git clone --depth 1 git@github.com:ray-project/ray.git
$ cd ray/deploy/charts
$ helm -n ray install example-cluster --create-namespace ./ray
Error: template: ray/templates/raycluster.yaml:79:24: executing "ray/templates/raycluster.yaml" at <.Values.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets
$ git show-ref HEAD
c315596ed2ed7bf273c872fa6a98b57cf0cd6010 refs/remotes/origin/HEAD
```

**Comment by rkooo567** [comment]
cc @ijrsvt

**Comment by ijrsvt** [comment]
@holdenk and @tekumara I think this is addressed in https://github.com/ray-project/ray/pull/17678

@DmitriGekhtman I presume you have an idea of a path forward here?

**Comment by DmitriGekhtman** [comment]
Should be fine to use master after the revert Ian mentioned above.

We'll come back later to adding support for image pull secrets, making sure to maintain backwards compatibility.
