### ISSUE TITLE
ray dashboard memory tab loading wheel when nothing running 

### ISSUE THREAD

**Issue by tekumara** [ray-project/ray#17663]
A cluster with nothing running will show an infinite loading wheel, rather than report nothing. This is a confusing UX because it does not distinguish between "please wait" and "there's nothing running".

<img width="509" alt="Screen Shot 2021-08-08 at 5 10 12 pm" src="https://user-images.githubusercontent.com/125105/128624166-6761a75e-dc6e-4848-9dfe-3463a49fc966.png">

ray 1.5.1

### Reproduction (REQUIRED)

```
pip install 'ray[default]'
ray start --head
# open the dashboard and navigate to the memory tab
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @edoakes

**Comment by jmakov** [comment]
Same with ray v1.6.0

**Comment by sidazhou** [comment]
Same in 22 Aug

**Comment by rkooo567** [comment]
We haven't fixed this issue. We will convert to the new dashboard from ray 2.0, and this feature will be temporarily removed. Please use the CLI `ray memory` or `ray list objects` in the meantime. We will consider adding back the feature later.
