### ISSUE TITLE
Ray1.4版本，在已经搭建的集群上跑python代码时报错，无法远程连接虚拟机中的集群

### ISSUE THREAD

**Issue by QWQyyy** [ray-project/ray#17668]
集群是成功运行的
![image](https://user-images.githubusercontent.com/54056797/128659376-ff0cdc4d-8a35-4dbc-96ab-d980fb81f4ee.png)
远程无法操作集群，报错redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
![image](https://user-images.githubusercontent.com/54056797/128659346-816c9a29-22bf-4609-ba2d-b22dafb3b027.png)
可以ping通，防火墙也已经关闭，但是却出现这个问题

**Comment by simon-mo** [comment]
maybe duplicate of #17480
