### ISSUE TITLE
dashboard process crash cause ray cluster crash

### ISSUE THREAD

**Issue by tomjamescn** [ray-project/ray#17675]
### What is the problem?
Frequent requests between actors in head node and worker node cause the dashboard to not respond, which in turn causes the entire cluster to crash. 

If disable dashboard when starting ray cluster, everything is ok.

Ray 1.3 1.4 1.5.1

**Comment by rkooo567** [comment]
cc @edoakes 

Do you know why that causes crash? does it use high memory usage or something?

**Comment by tomjamescn** [comment]
@rkooo567 `ray memory` show that memory usage is low. but when our program based on ray cluster (1 head and 1 worker node)  lasts for a while, dashboard first crash and then the ray cluster crash.

**Comment by rkooo567** [comment]
Is it possible to check top or htop command and see if the dashboard process uses large memory?

**Comment by Akkarine** [comment]
My case. After several hours of load, all nodes has very high CPU demand for `log_monitor.py`, so all others computing tasks struggle without resources. 
![image](https://user-images.githubusercontent.com/13115270/129141639-ec2e4449-3f55-4837-b8cb-497f87fa37d2.png)

And if I try to open dashboard on head node, it slowly consumes all memory, going to `RayOutOfMemoryError`, as I mentioned in https://github.com/ray-project/ray/issues/7317#issuecomment-894755966

![image](https://user-images.githubusercontent.com/13115270/129141287-23e29230-2fec-4513-a9da-01fd75479e8b.png)

**Comment by rkooo567** [comment]
@Akkarine It looks like glob has pretty high overhead because it needs to do regex for finding files. Can you tell me how many files do you have when the log monitor uses high cpu usage? (ls /tmp/ray/session_latset/logs | wc -l)

**Comment by Akkarine** [comment]
> @Akkarine It looks like glob has pretty high overhead because it needs to do regex for finding files. Can you tell me how many files do you have when the log monitor uses high cpu usage? (ls /tmp/ray/session_latset/logs | wc -l)

Right now I set up envs RAY_ROTATION_BACKUP_COUNT=0 RAY_ROTATION_MAX_BYTES=1024
Ran work around an hour and stopped. RIght now it is working, but `log_monitor.py` always has 25% CPU load.

One of nodes:
![image](https://user-images.githubusercontent.com/13115270/129149227-7de435ac-be03-49a9-90f2-31133d3103dd.png)
![image](https://user-images.githubusercontent.com/13115270/129149431-23eaebe1-1e50-441e-82f5-33e0ffcaa89f.png)

**Comment by rkooo567** [comment]
We will have the right fix for the log monitor, and that will be tracked here https://github.com/ray-project/ray/issues/7317

**Comment by Akkarine** [comment]
unstale
