### ISSUE TITLE
How to use custom module to load data in Colab environment

### ISSUE THREAD

**Issue by lucaguarro** [ray-project/ray#17686]
I have created a custom class that is responsible for loading my dataset. In order to use this class in Google Colab, I upload it to my drive and then update the system's path to include the corresponding drive directory.

I essentially do something like:
`sys.path.append('drive/path/to/dataset')`

And now I can import my dataset class located in 'drive/path/to/dataset'
`from MultimodalGoodreadsDataset import MultimodalGoodreadsDataset`

However when I try to use ray-tune to perform a hyperparameter search I get the following error:

> ModuleNotFoundError: No module named 'MultimodalGoodreadsDataset'
> ...
> ERROR worker.py:421 -- Exception raised in creation task: The actor died because of an error raised in its creation task

I have wrapped the data loading in a function:

```
def load_data():
  ds = MultimodalGoodreadsDataset(...)

  return ds
```

I presume this is where the error is occurring. Why can't ray-tune find the module when the module is able to be used just fine in other code cells? How can I get around this error?

**Comment by richardliaw** [comment]
@lucaguarro hey, this is due to Ray automatically enabling parallelism and needing to run your training on a separate process. Do you have a bit more code that I can look at here?

**Comment by lucaguarro** [comment]
Yes, here is my code

Training Function:
`
def mm_train_fun1(config, checkpoint_dir='/tmp/MultiModalModels'):
  ds = load_data()

  model = FullModel(ds.f_lengths[0], ds.f_lengths[1], config['std_dims'], config['num_units']).to('cuda')
  model.train()

  criterion = nn.CrossEntropyLoss()
  optimizer=AdamW(model.parameters(), lr=config["lr"])

  trainloader = DataLoader(ds.train, batch_size=config["batch_size"], shuffle=True, collate_fn=partial(my_collate_fn, f1_len=ds.f_lengths[0], f2_len=ds.f_lengths[1]))
  valloader = DataLoader(ds.val, batch_size=config["batch_size"], shuffle=True, collate_fn=partial(my_collate_fn, f1_len=ds.f_lengths[0], f2_len=ds.f_lengths[1]))

  for epoch in range(config['num_epochs']):
    running_loss = 0.0
    epoch_steps = 0

    for batch_idx, batch in enumerate(train_dataloader):
      c5g_f = batch['c5g_f'].to('cuda')
      bert_f = batch['bert_f'].to('cuda')
      genre = batch['genre'].to('cuda')
      targets = batch['label'].to('cuda')

      optimizer.zero_grad()
      outputs = model(c5g_f.float(), bert_f.float(), genre.float())
      loss = criterion(outputs, targets)
      loss.backward()
      model.float()
      optimizer.step()

      running_loss += loss.item()
      epoch_steps += 1

      if batch_idx % 10 == 9:
        print("[%d, %5d] loss: %.3f" % (epoch + 1, i + 1,
                                        running_loss / epoch_steps))
        running_loss = 0.0

      # Validation loss
      val_loss = 0.0
      val_steps = 0
      total = 0
      correct = 0

      all_predictions = np.array([])
      all_labels = np.array([])

      with torch.no_grad():
          for i, batch_v in enumerate(val_dataloader, 0):

              c5g_f = batch_v['c5g_f'].to('cuda')
              bert_f = batch_v['bert_f'].to('cuda')
              genre = batch_v['genre'].to('cuda')
              targets = batch_v['label'].to('cuda')

              outputs = model(c5g_f.float(), bert_f.float(), genre.float())
              _, predicted = torch.max(outputs.data, 1)

              all_predictions = np.append(all_predictions, predicted.cpu().numpy())
              all_labels = np.append(all_labels, targets.cpu().numpy())

              loss = criterion(outputs, targets)
              val_loss += loss.cpu().numpy()
              val_steps += 1

      with tune.checkpoint_dir(epoch) as checkpoint_dir:
          print("saving in checkpoint dir")
          path = os.path.join(checkpoint_dir, "checkpoint")
          torch.save((model.state_dict(), optimizer.state_dict()), path)

      s_precision, s_recall, s_f1, _ = precision_recall_fscore_support(all_labels, all_predictions, average='weighted')
      print('s_precision:', s_precision, 's_recall:', s_recall, 's_f1:', s_f1)
`

Testing Function:
`
def test_results(net, test_dataloader, device="cpu"):
  all_predictions = np.array([])
  all_labels = np.array([])

  net.to(device)
  net.eval()
  with torch.no_grad():
    for i, batch_test in enumerate(test_dataloader, 0):
        c5g_f = batch_test['c5g_f']
        bert_f = batch_test['bert_f']
        genre = batch_test['genre']
        targets = batch_test['label']

        outputs = net(c5g_f.float(), bert_f.float(), genre.float())
        _, predicted = torch.max(outputs.data, 1)

        all_predictions = np.append(all_predictions, predicted.numpy())
        all_labels = np.append(all_labels, targets.numpy())

  s_precision, s_recall, s_f1, _ = precision_recall_fscore_support(all_labels, all_predictions, average='weighted')

  return {
      'precision': s_precision,
      'recall': s_recall,
      'f1': s_f1
  }

test_results(model, test_dataloader)
`

Main Function:
`
def main(num_samples = 6, max_num_epochs = 15):
  tune_config = {
    "lr": tune.loguniform(5e-4, 5e-2),
    "batch_size": tune.choice([32,64,128]),
    "num_epochs": tune.choice([1,3,5,7,9]),
    "std_dims": tune.sample_from(lambda _: np.random.randint(50,300)),
    "num_units": tune.sample_from(lambda spec: np.random.randint(25,spec.config.std_dims)),
    "wandb": {
      "project": "MultiModalClassifier",
      "api_key": config['WandB']['api_key'],
      "log_config": True
    }
  }

  scheduler = ASHAScheduler(
    max_t=max_num_epochs,
    grace_period=1,
    reduction_factor=2)

  result = tune.run(
    partial(mm_train_fun1, checkpoint_dir='/tmp/MMModels'),
    config = tune_config,
    resources_per_trial={'gpu': 1},
    metric = 'loss',
    mode = 'min',
    num_samples = num_samples,
    scheduler = scheduler,
    callbacks=[WandbLoggerCallback(
        project="MultiModalClassifier",
        group='raytune_hpsearch',
        api_key=config['WandB']['api_key'],
        log_config=True
    )])

  best_trial = result.get_best_trial(metric="f1", mode="max", scope="last")
  print("Best trial config: {}".format(best_trial.config))
  print("Best trial final validation loss: {}".format(
      best_trial.last_result["loss"]))
  print("Best trial final validation accuracy: {}".format(
      best_trial.last_result["f1"]))
  
  best_trained_model = FullModel(311595, 768, best_trial.config['std_dims'], best_trial.config['num_units'])
  device = "cpu"
  
  best_trained_model.to(device)
                        
  best_checkpoint_dir = best_trial.checkpoint.value
  model_state, optimizer_state = torch.load(os.path.join(
      best_checkpoint_dir, "checkpoint"))
  best_trained_model.load_state_dict(model_state)

  # model_save_name = "yungclassifier.pt"
  path = F"/content/drive/MyDrive/Thesis/BookSuccessPredictor/saved_models/classifier1.pt"
  torch.save(best_trained_model.state_dict(), path)
  return test_results(best_trained_model, test_dataloader, device)
`

`test_results = main()`

**Comment by lucaguarro** [comment]
Yes, here is my code. Let me know if there is anything else I can provide

Training Function:


    def mm_train_fun1(config, checkpoint_dir='/tmp/MultiModalModels'):
      ds = load_data()
      
      model = FullModel(ds.f_lengths[0], ds.f_lengths[1], config['std_dims'], config['num_units']).to('cuda')
      model.train()
      
      criterion = nn.CrossEntropyLoss()
      optimizer=AdamW(model.parameters(), lr=config["lr"])
      
      trainloader = DataLoader(ds.train, batch_size=config["batch_size"], shuffle=True, collate_fn=partial(my_collate_fn, f1_len=ds.f_lengths[0], f2_len=ds.f_lengths[1]))
      valloader = DataLoader(ds.val, batch_size=config["batch_size"], shuffle=True, collate_fn=partial(my_collate_fn, f1_len=ds.f_lengths[0], f2_len=ds.f_lengths[1]))
      
      for epoch in range(config['num_epochs']):
      running_loss = 0.0
      epoch_steps = 0
      
      for batch_idx, batch in enumerate(train_dataloader):
        c5g_f = batch['c5g_f'].to('cuda')
        bert_f = batch['bert_f'].to('cuda')
        genre = batch['genre'].to('cuda')
        targets = batch['label'].to('cuda')
      
        optimizer.zero_grad()
        outputs = model(c5g_f.float(), bert_f.float(), genre.float())
        loss = criterion(outputs, targets)
        loss.backward()
        model.float()
        optimizer.step()
      
        running_loss += loss.item()
        epoch_steps += 1
      
        if batch_idx % 10 == 9:
          print("[%d, %5d] loss: %.3f" % (epoch + 1, i + 1,
                                          running_loss / epoch_steps))
          running_loss = 0.0
      
        # Validation loss
        val_loss = 0.0
        val_steps = 0
        total = 0
        correct = 0
      
        all_predictions = np.array([])
        all_labels = np.array([])
      
        with torch.no_grad():
            for i, batch_v in enumerate(val_dataloader, 0):
      
                c5g_f = batch_v['c5g_f'].to('cuda')
                bert_f = batch_v['bert_f'].to('cuda')
                genre = batch_v['genre'].to('cuda')
                targets = batch_v['label'].to('cuda')
      
                outputs = model(c5g_f.float(), bert_f.float(), genre.float())
                _, predicted = torch.max(outputs.data, 1)
      
                all_predictions = np.append(all_predictions, predicted.cpu().numpy())
                all_labels = np.append(all_labels, targets.cpu().numpy())
      
                loss = criterion(outputs, targets)
                val_loss += loss.cpu().numpy()
                val_steps += 1
      
        with tune.checkpoint_dir(epoch) as checkpoint_dir:
            print("saving in checkpoint dir")
            path = os.path.join(checkpoint_dir, "checkpoint")
            torch.save((model.state_dict(), optimizer.state_dict()), path)
      
        s_precision, s_recall, s_f1, _ = precision_recall_fscore_support(all_labels, all_predictions, average='weighted')
        print('s_precision:', s_precision, 's_recall:', s_recall, 's_f1:', s_f1)

Testing Function:

    def test_results(net, test_dataloader, device="cpu"):
      all_predictions = np.array([])
      all_labels = np.array([])
    
      net.to(device)
      net.eval()
      with torch.no_grad():
        for i, batch_test in enumerate(test_dataloader, 0):
            c5g_f = batch_test['c5g_f']
            bert_f = batch_test['bert_f']
            genre = batch_test['genre']
            targets = batch_test['label']
    
            outputs = net(c5g_f.float(), bert_f.float(), genre.float())
            _, predicted = torch.max(outputs.data, 1)
    
            all_predictions = np.append(all_predictions, predicted.numpy())
            all_labels = np.append(all_labels, targets.numpy())
    
      s_precision, s_recall, s_f1, _ = precision_recall_fscore_support(all_labels, all_predictions, average='weighted')
    
      return {
          'precision': s_precision,
          'recall': s_recall,
          'f1': s_f1
      }
    
    test_results(model, test_dataloader)

Main Function:

    def main(num_samples = 6, max_num_epochs = 15):
      tune_config = {
        "lr": tune.loguniform(5e-4, 5e-2),
        "batch_size": tune.choice([32,64,128]),
        "num_epochs": tune.choice([1,3,5,7,9]),
        "std_dims": tune.sample_from(lambda _: np.random.randint(50,300)),
        "num_units": tune.sample_from(lambda spec: np.random.randint(25,spec.config.std_dims)),
        "wandb": {
          "project": "MultiModalClassifier",
          "api_key": config['WandB']['api_key'],
          "log_config": True
        }
      }
    
      scheduler = ASHAScheduler(
        max_t=max_num_epochs,
        grace_period=1,
        reduction_factor=2)
    
      result = tune.run(
        partial(mm_train_fun1, checkpoint_dir='/tmp/MMModels'),
        config = tune_config,
        resources_per_trial={'gpu': 1},
        metric = 'loss',
        mode = 'min',
        num_samples = num_samples,
        scheduler = scheduler,
        callbacks=[WandbLoggerCallback(
            project="MultiModalClassifier",
            group='raytune_hpsearch',
            api_key=config['WandB']['api_key'],
            log_config=True
        )])
    
      best_trial = result.get_best_trial(metric="f1", mode="max", scope="last")
      print("Best trial config: {}".format(best_trial.config))
      print("Best trial final validation loss: {}".format(
          best_trial.last_result["loss"]))
      print("Best trial final validation accuracy: {}".format(
          best_trial.last_result["f1"]))
      
      best_trained_model = FullModel(311595, 768, best_trial.config['std_dims'], best_trial.config['num_units'])
      device = "cpu"
      
      best_trained_model.to(device)
                            
      best_checkpoint_dir = best_trial.checkpoint.value
      model_state, optimizer_state = torch.load(os.path.join(
          best_checkpoint_dir, "checkpoint"))
      best_trained_model.load_state_dict(model_state)
    
      path = F"/content/drive/MyDrive/Thesis/BookSuccessPredictor/saved_models/classifier1.pt"
      torch.save(best_trained_model.state_dict(), path)
      return test_results(best_trained_model, test_dataloader, device)

**Comment by richardliaw** [comment]
@lucaguarro can you try doing something like:

```diff
def mm_train_fun1(config, checkpoint_dir='/tmp/MultiModalModels'):
+ sys.path.append('drive/path/to/dataset')  # make sure this is a full path, not relative
  ds = load_data()

**Comment by lucaguarro** [comment]
This didn't seem to work. I also tried to "force" the reimport by doing `from MultimodalGoodreadsDataset import MultimodalGoodreadsDataset` but this also did not do anything.

I am confused as to why raytune can use classes from non-local imports without issue but instead has issues with my own local import. Do all the imports not get transferred over to the new process?

**Comment by richardliaw** [comment]
Hmm, where does `load_data` get defined? MultimodalGoodreadsDataset should be only imported in the function.

IIRC this is a limitation of cloudpickle. cc @suquark

**Comment by lucaguarro** [comment]
load_data is defined as a standalone function in its own cell. 

If MultimodalGoodreadsDataset is not available shouldn't I be getting an "ImportError" as opposed to a "No module" error?

**Comment by jmakov** [comment]
Can confirm that `sys.path.append('abs_path_to_module')  # make sure this is a full path, not relative` doesn't work.

**Comment by lucaguarro** [comment]
> ray.init(runtime_env={"working_dir": "."})

When I try this in colab, the cell hangs with the following output:

> 2021-11-01 22:24:02,013	ERROR services.py:1254 -- Failed to start the dashboard: Failed to read dashbord log: [Errno 2] No such file or directory: '/tmp/ray/session_2021-11-01_22-24-00_586568_80/logs/dashboard.log'

**Comment by edoakes** [comment]
@lucaguarro What are the contents of that log file?
