### ISSUE TITLE
May hang when submitting actor task

### ISSUE THREAD

**Issue by keyile** [ray-project/ray#17700]
### What is the problem?

It could be a deadlock when the main thread (holding GIL) is waiting for the mutex in core worker, and the heartbeat thread (holding the mutex) is waiting for GIL. We provide the corresponding stacks below to make it more clear:

![image](https://user-images.githubusercontent.com/32282736/128835399-6fa9ada7-804d-423a-963c-06103c55f7dd.png)
![image](https://user-images.githubusercontent.com/32282736/128835262-e37fef02-db95-4131-8480-9000337fb050.png)

The PR #12803 may be relative with this issue.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 1.5.0
Python: 3.7.9
OS: Mac OS 11.4

### Reproduction (REQUIRED)
The reproduction is very difficult so no code can be provided here.

Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by kfstorm** [comment]
It seems that this issue has been addressed by https://github.com/ray-project/ray/pull/17396. cc @ericl  @scv119 @rkooo567 to confirm.

**Comment by kfstorm** [comment]
Also cc @fyrestone
