### ISSUE TITLE
Actor creation warning can fire spuriously under heavy load.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1770]
On a cluster with 98 nodes (1 m4.16xlarge and 97 m4.xlarge), there are a total of 452 CPUs. Doing the following

```python
@ray.remote(num_cpus=1)
class Foo(object):
    pass

fs = [Foo.remote() for _ in range(452)]
```

leads to a number of warning messages of the form

*The actor with ID 0ac1331a6bab10c0b239cf1ebdf5f92a976de0e7 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor. Try reducing the number of actors created or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags.*

Right now a lot of spillback is required to place these actors properly, which triggers this warning. Note that the likelihood of this error can be reduced dramatically with more intelligent scheduling.

**Comment by whatbeg** [comment]
@robertnishihara often meet this, because I need to create a large number of Actors, but it seems that each Actor will keep at least one CPU，causing the later Actors to be spilling back?
So there is a case: users want no keeping of Actors, they create a large number of Actors but only need one running for each Actor. How can Ray handle this case?

**Comment by robertnishihara** [comment]
If you create an actor with no arguments in the decorator, e.g.,

```python
@ray.remote
class Foo:
    def method(self):
        ...
```

Then you can create an actor with `f = Foo.remote()` and it won't require any resources for its lifetime. However, each method invocation, e.g.,`f.method.remote()` will require 1 CPU resource.

In contrast, if you do

```python
@ray.remote(num_cpus=1)
class Foo:
    def method(self):
        ...
```

then the actor will reserve 1 CPU resource for its entire lifetime, and method invocations will not require any additional resources.

**Comment by whatbeg** [comment]
@robertnishihara Thanks for your quick reply.
I focus on creating a large number of Actors, each Actor has one method and is executed once.
there is an interesting thing:
I do next experiment on my desktop with 8 CPU (virtual cores) and I want to create 80 Actors, running each Actor once.

``` python
@ray.remote
class Counter(object):
    def __init__(self):
        self.value=0
    def increment(self):
        self.value += 1
        return self.value
```

Version 1: run 80 Actor methods once
``` python
start_time = time.time()
counters = [Counter.remote() for _ in range(80)]
results = ray.get([c.increment.remote() for c in counters])
print(results)  # prints [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ....]
end_time = time.time()
print("time cost: {}".format(end_time - start_time))

time cost: 43.3
```

Version 2: run 8 Actor methods 10 times
``` python
start_time = time.time()

total_results = []
for i in range(10):
    counters = [Counter.remote() for _ in range(8)]
    results = ray.get([c.increment.remote() for c in counters])
    total_results.extend(results)
print(total_results)

end_time = time.time()
print("time cost: {}".format(end_time - start_time))

time cost: 43.5
```

they have similar time cost!
but when I run 8 Actor methods once, it just cost 1.2s, I expect that running 80 Actor methods cost about 12s, but it's disappointing.
here is the time cost with different the number of Actor methods.
```
8 methods: 1.2s
16 methos: 6s     expected: 2.4s
24 methods: 10.5s    expected: 3.6s
32 methods:  15.2s   expected: 4.8s
......
```

So the questions are:
**1. Where is the extra time spent on Version 1 ?
2. Where is the extra time spent on Version 2 ?**

**Comment by robertnishihara** [comment]
In both cases, you are creating 80 actors. In your second example, you should move the line `counters = [Counter.remote() for _ in range(8)]` outside of the `for` loop.

**Comment by robertnishihara** [comment]
This no longer happens because we no longer give warnings for actors that are taking too long to create (though we should find a way to).
