### ISSUE TITLE
[core] Safety bug in distributed reference counting

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#17719]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

#13309 introduces an optimization for small objects that allows `ObjectRef` holders to get the value directly from the owner. I think this is causing a bug in the distributed ref counting code when ObjectRefs are nested.

The scenario is something like this, where worker W holds an ObjectRef to A, which contains ObjectRef B.
1. W gets A's value from A's owner.
2. A's owner responds with A's value, also says that A contains the nested ref B.
3. W submits a task that depends on A. A is small, so it gets inlined into the task's description.
4. W deletes local ref to A.

W's ref counts at the end will look like this:
A, local_ref_cnt = 0, submitted_ref_cnt = 0
B, local_ref_cnt = 0, submitted_ref_cnt = 1

W is supposed to keep track of the nested relationship between A <> B, so that eventually, B's owner will learn that W still has a reference to it. Right now we don't do this when A is small enough to be inlined.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments): See #17717.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment]
A workaround for this issue is to run with the environment variable `RAY_max_direct_call_object_size=0`, which will disable inlining objects.

**Comment by ericl** [comment]
Given this bug, is the optimization still worth it?

**Comment by stephanie-wang** [comment]
I think so. It should be a straightforward fix.

Actually it appears that #17553 is a different issue.

**Comment by stephanie-wang** [comment]
I'm going to wait on #17553 because they both require the same refactoring for nested object refs. This one should be just a few lines change on top of #17777.
