### ISSUE TITLE
[core] Actors force-killed while they still own objects that are referenced

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#17718]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

Actors are ref-counted and will get force-killed if there are no more references to the actor.

However, this can be problematic if another process references an object owned by that actor. Then, that reference becomes unusable because the actor has been killed. We should fix this by only exiting the actor once its refs have drained.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments): See #17717.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by stephanie-wang** [comment]
The workaround for this issue right now is to keep the actor handle in scope.

**Comment by ericl** [comment]
Couldn't this cause issues if the actor is holding resources like GPU memory? In that case force-killing regardless of ownership status would be what the user would expect.

**Comment by stephanie-wang** [comment]
Hmm so this is tricky... I think in most cases the actor should exit normally even if we wait to drain the references, but it is possible to write programs that have a cycle of ObjectRef passing, and then we will definitely leak. The user can always resolve the deadlock themselves by using `ray.kill` to force-kill the actor, but that might be hard to do.

I think our two choices are either to:
1. Force kill on actor out of scope, but log a warning if the actor exits with references still in distributed scope.
2. Drain references on actor out of scope, but log a warning if the actor is still holding references for a long time.

Unfortunately I think it's kind of hard for a user to resolve either issue on their own... I think 1 is easier.

**Comment by rkooo567** [comment]
I think 1 + figuring out a way to inject this warning into ObjectLostError sounds better? I think this happens because of application issue (ref not managed correctly), and just failing the job should be easier to debug than having resources leaks (given we can give them clear warning).  

Or what about 2, and instead of warning it, we can probably just force kill it and do 1 after timeout?

**Comment by ericl** [comment]
Also in favor of (1) (perhaps with enhanced error messages).

**Comment by hora-anyscale** [comment]
Per Triage Sync: Working as intended

cc: @ericl
