### ISSUE TITLE
[dependencies] Add a test to check the minimal install of Ray.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17714]
We should add a build that specifically only installs ray with minimal installs.

We should make sure that this is tested on the cluster.

cc @amogkam

**Comment by richardliaw** [comment]
@amogkam I will assign this to you for now; please delegate/cc help if appropriate

**Comment by richardliaw** [comment]
@krfricke Would you be able to take this item? Assigning this to you for now, please cc help if appropriate!

**Comment by amogkam** [comment]
Sorry haven't gotten to this yet. I chatted with @simon-mo briefly, and he suggested just creating a separate conda environment for this test since the bootstrap docker image already includes the full set of dependencies.

**Comment by krfricke** [comment]
That sounds easy enough, happy to take this on.

**Comment by krfricke** [comment]
Closed by https://github.com/ray-project/ray/pull/18071
