### ISSUE TITLE
[autoscaler] Don't tell users to set num_workers for head node

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17721]
```
Setting `max_workers` for node type `head` to the global `max_workers` value of 10. To avoid spawning worker nodes of type `head`, explicitly set `max_workers: 0` for `head`.
```

^ I get this warning message for my head node (which is explicitly tagged as head node too). Can we please avoid printing this message? 

It is unintuitive.

cc @DmitriGekhtman @ijrsvt

**Comment by DmitriGekhtman** [comment]
Related to the other issue on this.
This is warning you about the current default behavior.

**Comment by richardliaw** [comment]
This got fixed right @DmitriGekhtman ?

**Comment by DmitriGekhtman** [comment]
Indeed, closed in https://github.com/ray-project/ray/pull/17757.
