### ISSUE TITLE
Datasets will crash if memory usage is too high for .map()--- should bound memory usage

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#17748]
### What is the problem?

read_parquet on a moderately sized dataset causes ray to crash.

Note: this is a public s3 bucket so this should be reproducible.

```
import ray
from ray.data import read_parquet
ray.init(address="auto")

files = [f"s3://xgboost-demo-data/data.parquet/partition={i}/part_{i}.parquet" for i in range(100)]
inference_df = read_parquet(files).map(lambda x: x)
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Could you provide more details on the crash (i.e., stack trace, logs?)

**Comment by wuisawesome** [comment]
There's no good stack trace here. CPU usage in all the workers goes through the roof, then the raylet misses too many heartbeats and kills itself (this script is running locally). The workers then die. Some of them print:

```[
2021-08-11 22:34:56,324 W 1482097 1482109] gcs_server_address_updater.cc:58: Failed to get gcs server address from Raylet: IOError: 14: failed to connect to all 
addresses
```

before they fateshare with their dead raylet.

**Comment by ericl** [comment]
I just tried locally, that's just because map() is very inefficient and you run out of memory for large partitions. Using .map_batches() fixes the issue.
