### ISSUE TITLE
[Serve] Regression: no more ability to disable http ingress for deployment

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#17764]
Deployment API doesn't the ability to reject HTTP ingress route. It used to have `serve.create_endpoint(route=None)` but `@serve.deployment(route_prefix=None)` is not equivalent.

```
from ray import serve
import requests

serve.start()

@serve.deployment(route_prefix=None)
def f(_):
    pass

f.deploy()
print(requests.get("http://localhost:8000/f")) <- should not exist?
```

**Comment by iasoon** [comment]
I think this was fixed by https://github.com/ray-project/ray/pull/21042
