### ISSUE TITLE
[cleanup] Pull stats table out of instrumented_io_context and enable by default for non-asio stats

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#17761]
Currently our operation stats tracker is inside the instrumented_io_context class, but it is actually recording general purpose metrics.

1. Pull the class out into a separate event_tracker/operation_tracker class.
2. Enable reporting by default (except for asio perhaps---which is triggering segfaults in Java tests still).

cc @iycheng @clarkzinzow

**Comment by scv119** [comment]
@ericl I think you fixed the first one and @rkooo567 fixed the second one.
