### ISSUE TITLE
ray AttributeError

### ISSUE THREAD

**Issue by zhangkefeng** [ray-project/ray#1778]
sync_parameter_server.py  cluster ray failed：

Traceback (most recent call last):
  File "/home/disk0/fuchang01/python27-14/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/disk0/fuchang01/python27-14/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "sync_parameter_server.py", line 24, in __init__
AttributeError: 'module' object has no attribute 'SimpleCNN'

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.255.90.19:8777")

Remote function get_weights failed with:

Traceback (most recent call last):
  File "/home/disk0/fuchang01/python27-14/lib/python2.7/site-packages/ray/worker.py", line 770, in _process_task
    *arguments)
  File "/home/disk0/fuchang01/python27-14/lib/python2.7/site-packages/ray/actor.py", line 162, in actor_method_executor
    return method(actor, *args)
  File "sync_parameter_server.py", line 31, in get_weights
AttributeError: 'ParameterServer' object has no attribute 'net'

I have to put import file into sync_parameter_server.py.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by robertnishihara** [comment]
What is the exact command that you're running to cause this error? In particular, are you attaching to an existing Ray cluster or starting it locally?

Running

```
cd examples/parameter_server
python sync_parameter_server.py
```

seems to work for me.

You said "I have to put import file into sync_parameter_server.py". Can you clarify what you mean by that? What import statement did you have to add, and where did you add it?

**Comment by zhangkefeng** [comment]
I am attaching to an existing Ray cluster！   

# ray.init(redis_address=args.redis_address)
ray.init(redis_address="10.255.90.19:8777")

Only change this code. Attach redis into existing ray cluster.  
sync_parameter_server.py local is ok

**Comment by zhangkefeng** [comment]
I am attaching to an existing Ray cluster！   

# ray.init(redis_address=args.redis_address)
ray.init(redis_address="10.255.90.19:8777")

Only change this code. Attach redis into existing ray cluster.  
sync_parameter_server.py local is ok

**Comment by robertnishihara** [comment]
Does it work on a single machine if you first start Ray with

```
ray start ...
```

and then run the application by attaching to the existing Ray cluster (but where the cluster only has one machine in it)?

Is it possible that different versions of Ray are installed on the different machines? Or could they be installed in different locations?

**Comment by zhangkefeng** [comment]
@robertnishihara    Run the application by attaching to the existing Ray cluster (but where the cluster has different machines in it, two machines).  

One machine has work space, other does not have  workspace.

Other machine does not work.  If we make work space,  run is ok

**Comment by robertnishihara** [comment]
Got it, when you run this application, when the ParameterServer actor class is defined, the class definition will be pickled and exported to the workers. When the workers try to unpickle the class, they will then need to run the `import model` line, so the `model` Python module has to be on the `PYTHONPATH`. If that isn't the case then it won't be able to find the module.

This usually isn't an issue if the code is located in the same place on all of the machines.

**Comment by robertnishihara** [comment]
Closing for now. Feel free to reopen if it's still an issue.
