### ISSUE TITLE
[Tune] Access to more detailed resource management information

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#17799]
This is to improve Tune usability, namely we should not just let user be stuck in PENDING state. The current PlacementGroup API is very reactive. Tune doesn't know if a certain request is ever gonna be fulfilled or not. Since autoscaler has access to cluster.yaml and has an overview understanding of the resource requests, ideally it should signal if a request cannot be met at all. 

For context, see discussions under 
https://github.com/ray-project/ray/pull/17533/files/d6150e7f8b3a3b2b64cc056abf45f8e6642e4056#diff-4ed0b87c19cc0a24e8ab5747e611efa147b689312489ad4acfe604d05f17e7ac

which resource is not available, and how much is being requested
what is the total amount of those resource available on the cluster

**Comment by xwjiang2010** [comment]
@AmeerHajAli @richardliaw @mwtian

**Comment by xwjiang2010** [comment]
@wuisawesome as well. Mingwei mentioned this may fit in Ray Scheduler.

**Comment by wuisawesome** [comment]
Btw there was some discussion around this in #14908 but it's worth revisiting if requirements have changed. I suspect this will be somewhat involved though.

**Comment by xwjiang2010** [comment]
Duped with #18018
