### ISSUE TITLE
rayproject/ray-ml:latest-gpu image does not point to ray 1.5.2

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#17795]
With every release the rayproject/ray-ml:latest* should be updated to the latest ray version (which is 1.5.2 atm)
instead rayproject/ray-ml:latest-gpu (the default when you call ray up aws/example-full.yaml) points to ray 1.4.1
We should also check all latest images

CC @edoakes @jiaodong 

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jiaodong** [comment]
With help from @ijrsvt and @thomasdesr i got the script running to update docker images: https://hub.docker.com/repository/docker/rayproject/ray/tags?page=1&name=latest&ordering=last_updated

Feel free to reopen if the issue persists.

**Comment by AmeerHajAli** [comment]
I just called ray up on an example.yaml and it is still version 1.4.1. Can we keep this open until calling ray up and then calling ray--version prints 1.5.2?

**Comment by jiaodong** [comment]
I think that's due to the script took ~20mins to process one image and is still running on my laptop :/ We should keep it open until it's verified. Just to confirm, how did you verify it by "ray up on example.yaml" ? I don't have much context about this part

**Comment by AmeerHajAli** [comment]
here it is:
https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml

**Comment by jiaodong** [comment]
closing after verified pulled docker image correctly points to 1.5.2
