### ISSUE TITLE
[Core] Better error messages for when disk is full.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#17801]
### What is the problem?

When disk becomes full because the user workload has huge data size even more than a disk, the operating systems give "no space left in device" error. We should detect this scenario and raise a better error such as DiskFullError. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/17017 (should fix both in same issue)
