### ISSUE TITLE
[RLlib Tune] Can't get gpu ids in colab.

### ISSUE THREAD

**Issue by heyfavour** [ray-project/ray#17814]
when i use ray rllib in google colab,it can't get gpu ids if framework is torch ( tf is normal)
in ray/rllib/policy/torch_policy.py  => line 152   => ray.get_gpu_ids() =>return [] 

code:
#install
!pip install ray[default]
!pip install ray[rllib]
#run
import ray
import ray.rllib.agents.sac as sac

ray.init(num_gpus=1)
config = sac.DEFAULT_CONFIG.copy()
config["num_gpus"] = 1
config["num_workers"] = 1
config["framework"] = "torch"

trainer = sac.SACTrainer(config=config, env="CartPole-v0")

**Comment by jamesliu** [comment]
Same issue here with both standalone python and jupyter notebook.

**Comment by sven1977** [comment]
Hey @heyfavour , could you try this on the latest master? We have made some improvements in RLlib (especially for torch+GPU) recently and this should work now.
