### ISSUE TITLE
Testing that the newest version of Gym doesn't break anything in RLlib befor I release it

### ISSUE THREAD

**Issue by jkterry1** [ray-project/ray#17827]
Hey,

I'm about to cut a release of Gym based on what's currently on the master branch for it. Joseph Suarez (Neural MMO) said I should ask you guys to run all your RLlib tests with this to make sure nothing is broken.

@sven1977

**Comment by richardliaw** [comment]
@jkterry1 please go ahead and release! We will aim to adjust our CI/releases accordingly.

cc @amogkam @krfricke @sven1977 .

**Comment by jkterry1** [comment]
No I mean that this is my first release of Gym as the maintainer and there should be no breaking changes so I'm trying to make sure that I didn't accidentally do something that breaks major upstream projects without meaning to. This is especially because there have been numerous large changes to the specified dependencies.

**Comment by richardliaw** [comment]
Can you push a release candidate to pypi? We'd be happy to run our test suite against that.

**Comment by jkterry1** [comment]
Is depending on something akin to `pip install git+https://github.com/openai/gym.git@master` compatible with your test suite? If not I can deal with pushing a release candidate to PyPI (OpenAI is still in control of the PyPI so it's fairy nontrivial).

**Comment by amogkam** [comment]
@jkterry1 OK no worries we can test against master branch. I can kick off the testing right now.

**Comment by amogkam** [comment]
Kicked it off here https://github.com/ray-project/ray/pull/17829

**Comment by avnishn** [comment]
Hi @jkterry1,

Yesterday we saw you released gym 0.21 🎉! 

We found that it broke our tests because of an issue with being able to access gym environments such as Cartpole-v0. 

This is fine, as we've pinned to 0.19 in the meantime.

I wasn't able to find the release notes anywhere for your release so that we can see what changes have been made between 0.20 and 0.21. They weren't on pypy. 

Would you happen to know where I can find those?
It would be really useful so that we can unpin gym. 

Thanks,
@avnishn

**Comment by jkterry1** [comment]
The release notes are just in the regular GitHub release notes: https://github.com/openai/gym/releases

Two notes though:
-Could you please elaborate on the issue with Cartpole-v0 in particular? That should not have been impacted.
-Why are you pinning 0.19 instead of 0.20 if 0.20 was the last good release?

**Comment by jkterry1** [comment]
@avnishn @sven1977 @richardliaw Could you please take a look at my comment above when you get a chance?

**Comment by avnishn** [comment]
Hey sorry that I missed this! I'll use my time tomorrow to diagnose this and potentially fix it. Thanks for pointing me in the direction of the release notes! It looks like there shouldn't be any breaking changes according to the notes.
