### ISSUE TITLE
DOC: The documentation points to 2.0.0dev 

### ISSUE THREAD

**Issue by dmatrix** [ray-project/ray#17846]
### What is the problem?

The docs point to the future version of Ray, not the current one. This could prove confusing for new comer who does a ‘pip install ray’,  followed by ray—version, only to see 1.5.

*Ray version and other system information (Python version, TensorFlow version, OS):*

the current docs website.

**Comment by dmatrix** [comment]
I wonder if this problem comes from this [line](https://github.com/dmatrix/ray/blob/master/doc/source/conf.py#L239)

**Comment by richardliaw** [comment]
fixed
