### ISSUE TITLE
[rllib]: The tensor has two None in shape when not use eager mode

### ISSUE THREAD

**Issue by howieeeeeeee** [ray-project/ray#17862]
### What is the problem?
When I use ViewRequirement to produce "prev_n_obs", such as
`self.view_requirements["prev_n_obs"] = ViewRequirement(
            data_col="obs",
            shift="-10:0",
            space=obs_space)`
it will have "tensorflow.python.framework.errors_impl.InvalidArgumentError: Only one input size may be -1, not both 0 and 1"
since the shape of  input_dict['prev_n_obs'] is (?, ?, obs_space.size).
But this will not  happen when I use in eager mode.

### Reproduction 
The above code is the definition.  I check the code in https://github.com/ray-project/ray/blob/9322f6aab53f4ca5baf5a3573e1ffde12feae519/rllib/utils/tf_ops.py#L65 and it will generate 2 None.

**Comment by sven1977** [comment]
Hey @howieeeeeeee , the 2x None is intended as the view requirements state that a **range** of obs (-10 to 0) is needed per single timestep. Could you take a look at this example script here?

https://github.com/ray-project/ray/blob/master/rllib/examples/trajectory_view_api.py

It's being tested per-PR in our CI for framework=tf and I just ran it locally for framework=tfe. It does work ok and I'm not getting any errors. It also runs a evaluation loop at the end calculating single actions via `Trainer.compute_single_action`.
Let me know, if this doesn't solve the problem.
