### ISSUE TITLE
[tune] sync down and path sanitization problems

### ISSUE THREAD

**Issue by sofglide** [ray-project/ray#17894]
### Sync down fails at the end of each trial
Ray 1.5.0 on Azure cluster
Python 3.8

### Reproduction (REQUIRED)
Do a tune experiment where some params are strings containing space (like `name = "MY NAme"`) or params which a single value is a tuple.

Actually, since it seems that tune accepts only params which a single value is immutable, if you need to pass a sequence as a parameter like:
```sequence_params = choice([[1, 2 , 3], [10, 20, 30]])```
this will not work and the param value passed to the trial whill be None (I think).

The solution I found was to pass tuples
```sequence_params = choice([(1, 2 , 3), (10, 20, 30)])```

When tune runs a trial, the name of the trial folder will contain the name and value of some of the params (up to a certain length of the folder name). At the end of the trial, the folder in synced down to the master.

The paths will then contain spaces and special characters like `()` and this path will be the argument to `rsync`.

It seems that tune does not sanitize the paths the `rsync` command fails.

This is the fundamental bug.

The other remark is that it was very difficult to identify this root cause, when `rsync` fails the error is caught and not printed, only a generic message is printed.

Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

I think path strings should be protected/sanitized when passed to `rsync` and error messages improved.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sofglide** [comment]
@richardliaw

**Comment by richardliaw** [comment]
@xwjiang2010 do you think you could take this issue?

**Comment by xwjiang2010** [comment]
Sure. I'll take a look.
