### ISSUE TITLE
[rllib] Mutating `validate_config` (in R2D2 [and others])

### ISSUE THREAD

**Issue by andras-kth** [ray-project/ray#17921]
### What is the problem?

A number of trainer classes have **mutating** `validate_config` methods
causing validation to fail if evaluation is enabled and `evaluation_config`
doesn't contain the expected defaults.

Relevant code locations:
* [trainer](https://github.com/ray-project/ray/blob/7e109a3266016a35501ddd897f279576fe7bfc3d/rllib/agents/trainer.py#L753)
* [r2d2](https://github.com/ray-project/ray/blob/7e109a3266016a35501ddd897f279576fe7bfc3d/rllib/agents/dqn/r2d2.py#L97)
* [rnnsac](https://github.com/ray-project/ray/blob/7e109a3266016a35501ddd897f279576fe7bfc3d/rllib/agents/sac/rnnsac.py#L44)
* ... (probably others)

Users can work around the issue by including relevant defaults in their
`evaluation_config` (see the commented line in the repro script).

Better ways to solve this _could_ be to
* automatically include those defaults if missing
* change `validate_config` to _also_ accept the results of its mutations (in addition to the defaults)
* ... (probably others I haven't thought of)

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray, version 1.5.2 (Python 3.8.11 [irrelevant])

### Reproduction (REQUIRED)
```python
from ray import tune

tune.run(
    "R2D2",
    config=dict(
        env="CartPole-v0",
        model=dict(use_lstm=True),
        evaluation_num_workers=1,
        # evaluation_config=dict(replay_sequence_length=-1),
    ),
    stop=dict(training_iteration=2),
)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by sven1977** [comment]
Hey @mehes-kth , thanks for filing this issue. I never thought about the problem this causes for the evaluation workers, but this is certainly a bug.
