### ISSUE TITLE
[tune] DurableTrainable and upload_dir are confusing concepts

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#17950]
### Describe your feature request

If you want to upload your checkpoints to S3, you can use a `tune.SyncConfig` with `upload_dir="s3://...`. But this will e.g. not delete remote checkpoints with `keep_checkpoints_num`. The `DurableTrainable` has a very similar goal, but will actually work with remote checkpoint deletion - but might run into other problems?

Generally it would be good to either consolidate these efforts or to very clear which one to use in which situation (and raise warnings or errors if they are used in the wrong way).

A good way to go start with this would be to examine what exactly these two concepts do, what the similarities and differences are, and how we should use them in the future.

@matthewdeng is this something you could take a look at? I'm happy to help/pair code/debug!

Also cc @richardliaw and @grechaw

**Comment by matthewdeng** [comment]
Yeah this is very interesting, @richardliaw @xwjiang2010 and I were just chatting about this topic yesterday. https://github.com/ray-project/ray/issues/17940 may be related to the `keep_checkpoints_num` gap mentioned.

Maybe @xwjiang2010 and I can work together to consolidate our understanding of this functionality into a document and formulate a plan?

**Comment by xwjiang2010** [comment]
Yes, Matt, that's a good idea, let's sync on that.
