### ISSUE TITLE
[Dashboard] Dashboard agent is created and killed indefinitely when pip install ray[default] is not downloaded. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#17965]
### What is the problem?

When I ran ray start with ray downloaded by pip install ray, I observed the dashboard agent is indefinitely created and killed (which uses lots of cpu forking processes) because the agent is immediately crashed due to dependency issue, and the raylet restarts them after 10ms. 

### Reproduction (REQUIRED)
Run ray with pip install ray and look at raylet.out

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @richardliaw @edoakes should be a high priority issue

**Comment by richardliaw** [comment]
@rkooo567 @edoakes is this a release blocker?

**Comment by edoakes** [comment]
@richardliaw just discussed with @rkooo567 and sounds like it should be a blocker. He was seeing something like 30% CPU usage in the raylet due to constant retries.
