### ISSUE TITLE
Some models will be slower when running Distributed Scikit-learn / Joblib on ray cluster ？

### ISSUE THREAD

**Issue by YeahNew** [ray-project/ray#17974]
I recently hope to use Distributed Scikit-learn / Joblib on Ray to train some ML models, and refer to your case: https://docs.ray.io/en/master/joblib.html. The program is faster when running on a multi-node Ray cluster than a local Ray cluster. But when I change the model  to LogisticRegression, the training time of the ML model will be longer on a multi-node Ray cluster（Below is my execution code test）, and I did see a lot of started PollActor.run_batch() processes running on the ray web ui. When I do not use ray cluster(register_ray() and with joblib.parallel_backend('ray') were removed) , the entire training time will be shorter. This makes me very puzzled, LR model training does not seem to be suitable for ray acceleration?  
In addition, 
    1. When PollActor.run_batch() is running on other nodes in the cluster, will the data it needs be transmitted to other nodes via the network by the driver node (the description may be inaccurate, the node submitting the task)?
    2. When I use local data to train the LR model and submit it to the cluster to run, I found that Plasma on Ray Web UI will use a particularly large capacity (~10GB), even though the data file I read locally is only about 2GB.  It seems to store all the data from the training in Plasma.
Looking forward to your reply

----------code-------------
import joblib
from ray.util.joblib import register_ray
from scipy.stats import uniform
from sklearn import linear_model,datasets
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
iris = datasets.load_iris()
logistic = LogisticRegression(solver='saga', tol=1e-3, max_iter=5000,random_state=0)
distributions = dict(C=uniform(loc=0, scale=6),penalty=['l2', 'l1'])
clf = RandomizedSearchCV(logistic, distributions, random_state=0,n_iter=3000,n_jobs=40)

register_ray()
with joblib.parallel_backend('ray'):
     search = clf.fit(iris.data, iris.target)
----------code-------------

**Comment by gracedu0213** [comment]
I'm also having a similar issue with distributed Scikit-learn/Joblib on Ray, but with distributed random forest classifier.

Train data size: 30GB. n_jobs = 32

System params:
Sklearn==0.24.2; Ray==1.6.0; joblib==1.0.1

When using distributed random forest classifier with joblib on Ray (`register_ray()`), the training took 5.5 hours to complete.
```
model = sklearn.ensemble.RandomForestClassifier(n_jobs=32)
register_ray()
with joblib.parallel_backend('ray', self.num_jobs):
    model.fit(features, targets)
```
When not using joblib for distributed training (allocating all 32 processes on a single worker), the training jobs finished in 2.5 hours, which is consistent to the time it takes when training the model on google cloud AI platform. 
```
model = sklearn.ensemble.RandomForestClassifier(n_jobs=32)
model.fit(features, targets)
```

**Comment by YeahNew** [comment]
> 
> 
> I'm also having a similar issue with distributed Scikit-learn/Joblib on Ray, but with distributed random forest classifier.
> 
> Train data size: 30GB. n_jobs = 32
> 
> System params:
> Sklearn==0.24.2; Ray==1.6.0; joblib==1.0.1
> 
> When using distributed random forest classifier with joblib on Ray (`register_ray()`), the training took 5.5 hours to complete.
> 
> ```
> model = sklearn.ensemble.RandomForestClassifier(n_jobs=32)
> register_ray()
> with joblib.parallel_backend('ray', self.num_jobs):
>     model.fit(features, targets)
> ```
> 
> When not using joblib for distributed training (allocating all 32 processes on a single worker), the training jobs finished in 2.5 hours, which is consistent to the time it takes when training the model on google cloud AI platform.
> 
> ```
> @ray.remote
> def train(features, targets):
>   model = sklearn.ensemble.RandomForestClassifier(n_jobs=32)
>   model.fit(features, targets)
> ```

Yes, It seems that distributed Scikit-learn/Joblib on Ray is not suitable for large-scale data . Have you tried other ways to do distributed scikit-learn? I have been doing this kind of work recently, can we communicate together? 
哈哈~
