### ISSUE TITLE
init with worker cleanup multiple times in a same process doesn't work

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#1798]
### System information
- **OS Platform and Distribution: MacOS Sierra 10.12.6**
- **Ray installed from: pip**
- **Ray version: 0.3.1**
- **Python version: 3.5.2**

I recently found a very interesting issue. Specifically, I tried the simple code as below:

```
import ray


@ray.remote
def mimic_func():
    return True


class A:

    def __init__(self):
        self.foo = None

    def run(self):
        task_id = mimic_func.remote()
        res = ray.get(task_id)
        return res


def run_ray():
    # Ray init
    ray.init()
    
    # Do some tasks with ray remote.
    a = A()
    res = []
    for _ in range(5):
        res.append(a.run())
    print("The result is: %s" % res)
    
    # Ray cleanups.
    ray.worker.cleanup()


run_ray()
```
and this would print `[True, True, True, True, True]`, which works fine. However, if we run the code with logic "ray init -> ray remote function calls -> ray workers cleanups" _**in a same process for more than once**_ as follow:

```
import ray


@ray.remote
def mimic_func():
    return True


class A:

    def __init__(self):
        self.foo = None

    def run(self):
        task_id = mimic_func.remote()
        res = ray.get(task_id)
        return res


def run_ray():
    # Ray init
    ray.init()
    
    # Do some tasks with ray remote.
    a = A()
    res = []
    for _ in range(5):
        res.append(a.run())
    print("The result is: %s" % res)
    
    # Ray cleanups.
    ray.worker.cleanup()


# First time to run ray with remote funcs
run_ray()

# Second time to run ray with remote funcs
run_ray()
```
This would raise a key error. So I was wondering if this's an intention behavior or a bug to fix. Thanks!

**Comment by RuofanKong** [comment]
Following my above comment, the unit test that I mean is like:
```
import unittest
import ray


@ray.remote
def mimic_func():
    return True


class A:

    def __init__(self):
        self.foo = None

    def run(self):
        task_id = mimic_func.remote()
        res = ray.get(task_id)
        return res


class TestRay(unittest.TestCase):

    def setUp(self):
        ray.init()

    def test_run_ray_first_time(self):
        # Do some tasks with ray remote.
        a = A()
        res = []
        for _ in range(5):
            res.append(a.run())
        print("The result is: %s" % res)

    def test_run_ray_second_time(self):
        # Do some tasks with ray remote.
        a = A()
        res = []
        for _ in range(5):
            res.append(a.run())
        print("The result is: %s" % res)

    def tearDown(self):
        ray.worker.cleanup()
```

The issue could be reproduced by running the above test `unit_test.py` using command `python3 -m unittest unit_test.py`.

**Comment by robertnishihara** [comment]
Makes sense, it should be possible to get around this by defining the remote function inside of `run_ray()`. That way the remote function will be exported both times you call `run_ray`.

Alternatively you could define the remote function in an external file and reload it inside of `run_ray` or something like that.

**Comment by RuofanKong** [comment]
@robertnishihara Thanks for the comment! I tried your proposed workaround, but seems they're still not solving the problem, and I'd be also interested in the detailed causes behind this issue :)

Also, I believe there might be a temporary solution around fixing the issue, but in terms of long run, I am curious if there're any plans to fix it in Ray :) The reason is from users perspective, it might be more reasonable to define remote functions anywhere for the general purpose (I mean, not just exported somewhere else).

Additionally, (may not be related to this issue directly), but for your above comment "ray.worker.cleanup() isn't really part of the API.", I wonder if we have such a formal API to clean up the ray cluster if not suing `ray.worker.cleanup()` ? If not, can we make a feature request? I'm curious because from the user perspective, we may need to manually do the cleanup in some cases, such as the above unit test example :)

**Comment by robertnishihara** [comment]
Want to create a separate issue for the feature request? I think something like this would be useful to support better.

**Comment by RuofanKong** [comment]
@robertnishihara Opened a feature request https://github.com/ray-project/ray/issues/1814. But in terms of the issue here, do you have any suggestions?

**Comment by robertnishihara** [comment]
The following seems to work for me.

```python
import ray

def run_ray():
    @ray.remote
    def mimic_func():
        return True

    class A:
        def __init__(self):
            self.foo = None
        def run(self):
            task_id = mimic_func.remote()
            res = ray.get(task_id)
            return res

    ray.init()
    
    # Do some tasks with ray remote.
    a = A()
    res = []
    for _ in range(5):
        res.append(a.run())
    print("The result is: %s" % res)
    
    # Ray cleanups.
    ray.worker.cleanup()


run_ray()

run_ray()
```

It gives the output

```
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:51611 to respond...
Waiting for redis server at 127.0.0.1:27497 to respond...
Starting local scheduler with the following resources: {'CPU': 8, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui12647.ipynb?token=0fa54e23eb21ee5d3a10ae508a6ff5256c85c1a907854170
======================================================================

The result is: [True, True, True, True, True]
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:64835 to respond...
Waiting for redis server at 127.0.0.1:49276 to respond...
Starting local scheduler with the following resources: {'CPU': 8, 'GPU': 0}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui84391.ipynb?token=3e9978d1d4983767191e2cc6b42cf19d471621aaa6833259
======================================================================

The result is: [True, True, True, True, True]
```

**Comment by RuofanKong** [comment]
@robertnishihara interesting! did you run it on latest ray, as I'm on 0.3.1.

**Comment by robertnishihara** [comment]
Yeah, I ran it on 0.4.0, can you try that? (I didn't try 0.3.1.)

**Comment by RuofanKong** [comment]
@robertnishihara  0.4.0 works for me as well. Thanks! But I am curious about the root cause behind the issue.

**Comment by robertnishihara** [comment]
I'm not sure about the exact change between 0.3.1 and 0.4.0, but the fundamental issue is the following:

When a remote function is defined, its definition is exported to the workers (assuming `ray.init()` has been called). If `ray.init()` has not been called, then the definition will be exported when `ray.init()` is called.

When a remote function is invoked (e.g., `f.remote()`), then we don't ship the function definition, we just ship the function ID, then the worker uses that ID to lookup the appropriate function and execute it.

When you call `ray.worker.cleanup()`, we're killing all of the workers and other Ray processes. We also reset some state on the driver.

Then when you call `ray.init()` again, the remote function does not get exported again. Then when you call `f.remote()` the driver or worker or some process looks for the remote function with the given ID, but it can't be found because some state was flushed when we did `ray.worker.cleanup()` and was never recreated.

**Comment by avaziri** [comment]
@RuofanKong 
I tried to manually export the function, but I need some objects (particularly the function_evaluator) which I am not sure how to retrieve.
```
    func = _test_remote
    func_name = "{}.{}".format(func.__module__, func.__name__)
    func_id = rw.compute_function_id(func_name, func)
    func_invoker = None # Not sure where I can get this
    func_properties = FunctionProperties(
        num_return_vals=1,
        resources=None,
        max_calls=None)
    rw.export_remote_function(func_id, func_name, func, func_invoker,
                              func_properties)
```

**Comment by robertnishihara** [comment]
@RuofanKong what do you mean precisely? You can manually query 

```python
r = ray.worker.global_worker.redis_client
keys = r.lrange('Exports', 0, -1)
exports = [r.hgetall(key) for key in keys]
```

though this is definitely not stable/supported and could easily change.

**Comment by robertnishihara** [comment]
One option could be to define the function `f` as a regular function, but then inside of the test, define and export the remote function via `f_remote = ray.remote(f)`.

**Comment by robertnishihara** [comment]
Now with `ray.shutdown()` documented, I think this is addressed. If not, please reopen.
