### ISSUE TITLE
Memory error: object does not fit in the plasma store

### ISSUE THREAD

**Issue by AlexGrinch** [ray-project/ray#1801]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 
- **Python version**: 3.5.2

### Describe the problem
I want to run 8 agents playing gym Pong in parallel to collect data for experience buffer. However, when I try to save the produced data to some list, I get memory error. 

### Source code

>num_workers = 8
workers = [Worker.remote(worker_index) 
           for worker_index in range(num_workers)]

----------------------- this code works fine -----------------
> for i in range(10):
    observations = [worker.make_long_step.remote(100) for worker in workers]
    obs = ray.get(observations)

----------------------- this code fails -----------------------
 
> transitions = []
for i in range(10):
    observations = [worker.make_long_step.remote(100)  for worker in workers]
    obs = ray.get(observations)
    transitions += obs

### Error logs

Remote function make_long_step failed with:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 841, in _process_task
    self._store_outputs_in_objstore(return_object_ids, outputs)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 768, in _store_outputs_in_objstore
    self.put_object(object_ids[i], outputs[i])
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 372, in put_object
    self.store_and_register(object_id, value)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 302, in store_and_register
    serialization_context=self.serialization_context)
  File "plasma.pyx", line 401, in pyarrow.plasma.PlasmaClient.put
  File "plasma.pyx", line 302, in pyarrow.plasma.PlasmaClient.create
  File "error.pxi", line 93, in pyarrow.lib.check_status
pyarrow.lib.PlasmaStoreFull: object does not fit in the plasma store

**Comment by robertnishihara** [comment]
The observations are never getting deallocated because they’re stored in
the transitions list. The observations themselves are backed by shared
memory in the object store (assuming there are numpy arrays involved), so
that’s why the object store is filling up. Though even if that weren’t the
case you’d still get an out of memory error at some point because things
are not getting deallocated.

How much memory is available on the machine? And how large are the
observations?

**Comment by AlexGrinch** [comment]
During ray.init() I got the following warning:
Warning: Reducing object store memory because /dev/shm has only 1073741824 bytes available.
So, it seems I have ~1Gb of memory for my observations. On the machine I have a lot of memory and I can easily store 1M observations (84x84x4 numpy images). I thought that 1Gb is enough to store 800=8x100 observations I get from running 8 agents 100 steps each and decided to copy this 800 observations to local list after every run.

Am I right that the only solution here is to increase the amount of available memory in /dev/shm so I can store all necessary observations?

**Comment by robertnishihara** [comment]
How large is each observation? If you want to check the serialized size, you can do

```
import ray
import pyarrow as pa

obs = ...

pa.serialize(obs).to_buffer().size
```

Usually `/dev/shm` is half the size of the amount of available memory. Is there a reason that it is smaller in this case?

But yes, it sounds like increasing the size of `/dev/shm` is the way to go. Assuming that you actually can configure that in your setup?

**Comment by AlexGrinch** [comment]
In my example the size of each obs (which is 800 transitions of form `(s, a, r, s', done)`) is equal to 0.16 Gb. 

I think the memory is smaller because I use docker. It seems that I need to reconfigure the available memory limitation so I can store the whole replay buffer in it.

Thanks for your help!
