### ISSUE TITLE
Example with deprecated class

### ISSUE THREAD

**Issue by jmugan** [ray-project/ray#18031]
I love RLlib so far. Thanks for your effort. The example at https://docs.ray.io/en/master/rllib-offline.html#example-converting-external-experiences-to-batch-format uses `SampleBatchBuilder`, but that is deprecated and also gives a weird error `AttributeError: 'function' object has no attribute '_next_unroll_id'` for the line `writer.write(batch_builder.build_and_reset())` in my modified version of that example.  Is there an equivalent example somewhere with `SimpleListCollector`, which is what I assume I should use.

Commenting out `@Deprecated(new="a child class of `SampleCollector`", error=False)` seemed to fix it. The decorator somehow made Python think that `SampleBatchBuilder` was a function. Weird.

**Comment by sven1977** [comment]
Hey @jmugan , great catch. Yeah, we should update that example. Let me work on a PR ...

**Comment by sven1977** [comment]
I think the `Deprecated` issue has been fixed recently. It's now treating the "decoratee" :) as a class (as it should), not a function anymore.
