### ISSUE TITLE
"ray start --head" in command line gives 'ray' not found

### ISSUE THREAD

**Issue by Thompson104** [ray-project/ray#18045]
### What is the problem?
Python 3.6.9;
Ray: 1.6.0;
Ubuntu 18.04.
### Reproduction (REQUIRED)
I'm trying to run `ray start --head`  but have the following result from command line:
![image](https://user-images.githubusercontent.com/28070085/130656218-402afad7-47ee-4edb-b14a-6272a369ddc3.png)

I'm able to run ray.init in python3 and the result is:
![image](https://user-images.githubusercontent.com/28070085/130656592-846ba12f-269a-4ff0-aa23-acfb832c344c.png)

I wonder what may cause this? Thank you.

**Comment by richardliaw** [comment]
Can you try `python3 -m ray start --head`? Looks like ray wasn't installed into your default environment.

**Comment by Thompson104** [comment]
Thanks for the quick reply. The suggested command returns: `/usr/bin/python3: No module named ray.__main__; 'ray' is a package and cannot be directly executed`

However, the problem seems to be fixed after I restarted my computer? Not sure why.
