### ISSUE TITLE
NAN reward when using customized config

### ISSUE THREAD

**Issue by Erichliu00** [ray-project/ray#1804]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.4.0
- **Python version**: 3.5.2 (Anaconda)
- **Exact command to reproduce**: See description

### Describe the problem
Default config works fine for me, but if change [default config](https://github.com/ray-project/ray/blob/master/python/ray/rllib/es/es.py#L29) in es.py as follows:
```
DEFAULT_CONFIG = dict(
    l2_coeff=0.005,
    noise_stdev=0.02,
    episodes_per_batch=10,
    timesteps_per_batch=500,
    eval_prob=0.003,
    return_proc_mode="centered_rank",
    num_workers=5,
    stepsize=0.01,
    observation_filter="MeanStdFilter",
    noise_size=250000000,
    env_config={})
```
then run `python es/es.py --env Swimmer-v1 --run ES --local-dir temp`, you will get NAN reward.

### Source code / logs
Plz see this [gist](https://gist.github.com/Erichliu00/0a57d54e0c1374552f92dcc937167447).

**Comment by robertnishihara** [comment]
Since there are only `episodes_per_batch` episodes per batch, and each episode is used for evaluation with probability `eval_prob`, on average you'll expect `0.03` episodes to be used for evaluation per algorithm iteration. When this happens, the reward is displayed as NAN. There isn't anything really wrong though.

You can test this by setting `eval_prob` to `0.5` or something like that.

**Comment by Erichliu00** [comment]
Cool, got it, thank you for the quick response! 
BTW, I am very curious whether the performance of RL algorithms implemented in other open source implementations is comparable with here given the same setting? Like [here](https://github.com/openai/baselines) for PPO, DQN, and [here](https://github.com/openai/evolution-strategies-starter) and [here](https://github.com/uber-common/deep-neuroevolution) for ES?

**Comment by robertnishihara** [comment]
The ES implementation here is pretty similar to the OpenAI ES implementation and uses some of the same code.

I'm not sure about the Uber implementation. Our DQN implementation shares some code with the baselines implementation. Our PPO implementation is different from the baselines implementation but the performance is probably comparable in most settings.

**Comment by Erichliu00** [comment]
Very cool, thank you so much.
