### ISSUE TITLE
[rllib] Trainer.with_updates does not allow adding additional mixins

### ISSUE THREAD

**Issue by RickDW** [ray-project/ray#18044]
I have posted this proposal on the [ray forums](https://discuss.ray.io/t/feature-request-trainer-with-updates-discards-previous-mixins/3337) as well but I figured it might be good to post it here as well.

I'm working on a project where a trainer's default_resource_request method needs to be updated. This can be done by passing a mixin into the trainer's with_updates() method. This is what is done in rllib's impala and apex implementations for example. When this is done, any previous mixins used to construct the trainer will be discarded, and only the new mixins will be mixed in with the Trainer class. While this might be the right functionality in some cases, in others such as mine it makes things unnecessarily messy.

There is a simple work around that does not require with_updates' functionality to be changed, which is to manually create a new class that mixes the trainer and whatever mixins you want to add. However as soon as the resulting class is updated using with_updates, the manual mixins will be thrown away like before. Again, this might be what you want in some cases, but definitely not all the time. Creating this new functionality would be very easy and would not break any existing code, so I think it would be a good feature to have. Let me know what you think.

**Comment by gjoliver** [comment]
can I ask why you still need to use with_updates() when you have a manually created new class?

**Comment by RickDW** [comment]
It seems to me that the whole idea behind with_updates is that anyone can easily modify a Trainer class when it is the same as an existing Trainer with a few updates. The same goes for the classes constructed by with_updates(), they should be modifiable the same way. So you don't want users to have to work around this functionality by manually creating classes in the first place.

**Comment by gjoliver** [comment]
yeah, definitely.

**Comment by sven1977** [comment]
Hey @RickDW , could you try doing this hack instead?

```
# The modified Trainer class we will use. This is the exact same
# as a PPOTrainer, but with the additional default_resource_request
# override, telling tune that it's ok (not mandatory) to place our
# n remote envs on a different node (each env using 1 CPU).
PPOTrainerRemoteInference = add_mixins(PPOTrainer,
                                       [OverrideDefaultResourceRequest])
```

The above example is from:
https://github.com/ray-project/ray/blob/master/rllib/examples/remote_envs_with_inference_done_on_main_node.py

So you could do: `.with_updates()` first and then use `.add_mixins()`. Does this make sense?

Btw, the plan is to get rid of mixins (and the `trainer_template.py`) soon in favor of a simpler/more unified system anyways as mixins are causing lots of confusion. But for now the above should work.

**Comment by gjoliver** [comment]
We have moved away from using template and mixins to construct trainers.
Users should be able to override any member functions easily now.
Closing.
