### ISSUE TITLE
[serve] serve.start() needs to have detached=True or its cleaned up right away

### ISSUE THREAD

**Issue by kombuchafox** [ray-project/ray#18056]
### Describe your feature request
serve.start() needs to have detached=True when using ray client or else deployment is cleaned up right away.

Everytime I deploy the actor is killed and recreated

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by edoakes** [comment]
@kombuchafox do you mean the deployment is cleaned up when the script exits? If so, that's the expected behavior of the detached flag.
