### ISSUE TITLE
Pull request race triggers inefficient pull retry

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#18062]
### What is the problem?

https://github.com/ray-project/ray/issues/17628#issuecomment-905157992

his happens 100% of time when pipeline spilling wasn't enabled, and 50% of time when it is enabled (we should eventually solve it by better retry protocol). TL;DR this block is triggered quite often which made it wait 10 additional seconds. 
https://github.com/ray-project/ray/blob/5571d2436da42438c26967a5d1211a2ebbeffe42/src/ray/object_manager/object_buffer_pool.cc#L97

Object store mem: 64MB/70MB
Object: 8MB with 2 chunks

- chunk index 1 receives at thread A
- buffer pool attempts to spill & create an object 
- chunk index 0 receives at thread B
- buffer pool attempts to spill & create an object 
- Object is created by chunk index 0 (since it is FIFO)
- But chunk index 1 gets reply from the plasma store first.
- chunk index 0 failed at https://github.com/ray-project/ray/blob/5571d2436da42438c26967a5d1211a2ebbeffe42/src/ray/object_manager/object_buffer_pool.cc#L97
- chunk index 1 creates the object successfully.
- Since chunk index 0 failed, it should wait 10 more seconds to retry.

This can be solved by either 1. better retry protocol we are planning to do. 2. cache the request until object is created (this is not ideal because it can cause large memory usage) and seal it as soon as it is created. It happens less often because creating a new object at buffer pool is usually faster (since we are not blocked by spilling)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
Look at the original issue

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/issues/17628#issuecomment-905173500 Another discussion

**Comment by rkooo567** [comment]
cc @ericl @scv119 @stephanie-wang 

There are 3 solutions suggested; 

- Cache push grpc requests until the object is created
- Make retry protocol efficient
- locking while creating objects

**Comment by ericl** [comment]
Why don't we just retry the create for index 0 (instantaneously), then things will just work since the object was created for index 1 already right?

**Comment by rkooo567** [comment]
Oh actually a good point. I realized the order is a bit messed up. So 

indx 1 -> indx 0 created

but indx 0 is replied first (since this is done by retry from the client), and indx0 status is failed (duplicated creation) 

and indx0 is dropped and then indx1 is replied.

and that’s the time buffer pool noticed there was an object created

**Comment by rkooo567** [comment]
We (Mingwei and I) will handle this next week @ericl is it okay to reopen it?
