### ISSUE TITLE
[nightly test] stress test placement group is timing out

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18080]
[  Stress test placement group](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_XK8dGTQuc7i9va97p1u5YYGZ?command-history-section=command_history) has been timing out consistently. We should prioritize the fix of it.

**Comment by scv119** [comment]
Was trying to bisecting but it seems the tests has been flaky since July 12th. Specifically I've been running placement group stress tests against https://github.com/ray-project/ray/commit/33e319e9d76513ca18eec4968c15019e97cd271d. Which hangs very frequently. Probably we should find the root cause instead of bisecting it.

**Comment by scv119** [comment]
Here are some `ray status` the the test hangs. They are hanging at waiting for bundle to be ready. Looks these tests are waiting for resource `bundle`?

```
Resources
------------------------------------------------------------
Usage:
 0.0/8.0 CPU
 0.00/29.647 GiB memory
 0.00/0.146 GiB object_store_memory
 666.0/666.0 pg_custom

Demands:
 {'bundle': 0.001}: 99+ pending tasks/actors (99+ using placement groups)
```
```
Resources
------------------------------------------------------------
Usage:
 0.0/8.0 CPU
 0.00/26.790 GiB memory
 0.00/0.146 GiB object_store_memory
 109.0/666.0 pg_custom

Demands:
 {'pg_custom': 1.0}: 2+ pending tasks/actors (2+ using placement groups)
 {'bundle': 0.001}: 8+ pending tasks/actors (8+ using placement groups)
 {'pg_custom': 1.0} * 5 (STRICT_SPREAD): 9+ pending placement groups
```

**Comment by ericl** [comment]
Is this test fixed? The PRs above were merged 5 days ago.

**Comment by rkooo567** [comment]
Yeah should be fixed (let me check nightly dashboard at home later and close it)
