### ISSUE TITLE
[Datasets] Add test coverage for reading from HDFS.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#18094]
Add test coverage for reading from a pyarrow `HadoopFileSystem`. Will need to explore mocking HDFS, or starting and managing a local HDFS cluster via a pytest fixture.

**Comment by jianoaix** [comment]
@atomic FYI this PR which is for S3 may serve as an example for HDFS test: https://github.com/ray-project/ray/pull/17158

**Comment by heyitsmui** [comment]
@jianoaix based on @atomic's bandwidth, we are targeting 11/23 for completion for this task, let us know if this is reasonable, thanks!
