### ISSUE TITLE
Function manager exports duplicate functions

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#18095]
### What is the problem?

The function manager currently uploads functions, using a key derived from the pickled function, but couldpickle pickling isn't stable. This means the function will get reuploaded many times. 

On mitigation is to put a uuid in the function when the decorator is invoked, and use that (instead of hashing the bytes) to determine function uniqueness. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
@ray.remote
def f():
 pass

@ray.remote
def g():
  ray.get(f.remote())

ray.get([g.remote() for _ in range(5)])
```

(put a print statement in `function_manager.py::export`). 

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jjyao** [comment]
With the example @wuisawesome gave, cloudpickle does its job correctly and we generate the same key every time. The issue is that we don't check if the key already exists in redis but instead we always do `hset & rpush`. Each `rpush` will cause all workers to re-download the function again. The fix can simply be checking the return value of `hset`, if it says the key already exists, we don't do `rpush`.

**Comment by ericl** [comment]
I've seen in other examples cloudpickle is nondeterministic. Why not go
with the uuid approach? It seems less likely to go wrong.

**Comment by jjyao** [comment]
Oh sure, I'll do the UUID thing then along with what I proposed since it's still needed even if we generate the key deterministically.

**Comment by ericl** [comment]
Sounds good. It seems both optimizations could be helpful.
