### ISSUE TITLE
[Dataset] Progress Bar not rendering correctly inside Ray actor

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#18103]
Shuffle Map:  56%|█████▋    | 22/39 [00:00<00:00, 219.32it/s]
Shuffle Map:  59%|█████▉    | 23/39 [00:00<00:00, 229.36it/s]
Shuffle Map:  59%|█████▉    | 23/39 [00:00<00:00, 229.52it/s]
Shuffle Map:  56%|█████▋    | 22/39 [00:00<00:00, 219.51it/s]
Shuffle Map: 100%|██████████| 39/39 [00:00<00:00, 234.59it/s]
Shuffle Reduce:   0%|          | 0/39 [00:00<?, ?it/s]
Shuffle Map: 100%|██████████| 39/39 [00:00<00:00, 245.06it/s]
Shuffle Reduce:   0%|          | 0/39 [00:00<?, ?it/s]
Shuffle Map: 100%|██████████| 39/39 [00:00<00:00, 243.93it/s]
Shuffle Reduce:   0%|          | 0/39 [00:00<?, ?it/s]
Shuffle Map: 100%|██████████| 39/39 [00:00<00:00, 248.51it/s]
Shuffle Reduce:   0%|          | 0/39 [00:00<?, ?it/s]
Shuffle Reduce:  49%|████▊     | 19/39 [00:00<00:00, 189.97it/s]
Shuffle Reduce:  64%|██████▍   | 25/39 [00:00<00:00, 231.85it/s]
Shuffle Reduce:  54%|█████▍    | 21/39 [00:00<00:00, 205.99it/s]
Shuffle Reduce:  56%|█████▋    | 22/39 [00:00<00:00, 213.37it/s]
Shuffle Reduce: 100%|██████████| 39/39 [00:00<00:00, 199.48it/s]
Shuffle Reduce: 100%|██████████| 39/39 [00:00<00:00, 193.51it/s]
Shuffle Reduce: 100%|██████████| 39/39 [00:00<00:00, 192.05it/s]
Shuffle Reduce:  97%|█████████▋| 38/39 [00:00<00:00, 191.82it/s]

When calling Ray Dataset operations from inside a Ray worker, the progress bars are not rendering properly and make the output very messy.

Is there a way to disable these?

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
I think the main issue here is that the carriage return/rewriting that tqdm gets discarded; you may want to consider turning of tdqm when using Ray Tune.

**Comment by clarkzinzow** [comment]
@amogkam I don't think this has been fixed, I'll assign a priority and get it in the backlog.

**Comment by npuichigo** [comment]
Any update on that?
