### ISSUE TITLE
[rllib] Policy `learner_stats` get dropped when multi_gpu_learner_thread.py is used (in GPU and multi-GPU use cases).

### ISSUE THREAD

**Issue by Bam4d** [ray-project/ray#18116]
### What is the problem?

When multiple gpus are used, learner stats are gathered in the `learn_on_loaded_batch` method with a "tower_X" key before the stats:
https://github.com/ray-project/ray/blob/master/rllib/policy/torch_policy.py#L645

for example:
```
{'tower_0': {'learner_stats': {'cur_lr': 0.000495184, 'policy_loss': -40.517921447753906, 'entropy': 1.8380180597305298, 'entropy_coeff': 0.0005, 'var_gnorm': 17.741676330566406, 'vf_loss': 0.7066917419433594, 'vf_explained_var': array([0.5089742], dtype=float32), 'mean_rhos': 1.0025060176849365, 'std_rhos': 0.39850014448165894}}}
```

This 'tower_0' is not taken into account when `get_learner_stats()` is used:
https://github.com/ray-project/ray/blob/089dd9b94924cccb85ba1affccc4b0c8907f192c/rllib/execution/multi_gpu_learner_thread.py#L102

This causes the policy learner_stats to get dropped when GPUs are used.

## CPU does not drop these stats
This is different from when a single gpu/cpu is used, the `learn_on_loaded_batch` function will return:
```
{'learner_stats': {'cur_lr': 0.000495184, 'policy_loss': -40.517921447753906, 'entropy': 1.8380180597305298, 'entropy_coeff': 0.0005, 'var_gnorm': 17.741676330566406, 'vf_loss': 0.7066917419433594, 'vf_explained_var': array([0.5089742], dtype=float32), 'mean_rhos': 1.0025060176849365, 'std_rhos': 0.39850014448165894}
```

(note the lack of `tower_X` key)

Similar code can then extract the policy metrics which works!
https://github.com/ray-project/ray/blob/089dd9b94924cccb85ba1affccc4b0c8907f192c/rllib/execution/learner_thread.py#L80

*Ray version and other system information (Python version, TensorFlow version, OS):*

version: latest dev 2.0.0
python: 3.8
macosx + linux
torch + tensorflow

### Reproduction (REQUIRED)

Run anything with GPU learners (specifically in my case I'm using IMPALA)

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

@sven1977

**Comment by yangysc** [comment]
I also found on my task when using mutli_gpu ppo, the performance is much worse than using only one gpu.  Is the performance difference related to this issue? or there is somthing more needed to set first to use two gpus? @sven1977 Please take a look. Thanks!

I am using two gpus by setting the rllib as follows:
`            "num_gpus": num_gpus,  # 0.35, # must set to one, cannot be 2
`

The performance difference between one gpu and two gpus are plotted as follows:

For two gpus: the `kl` is much higher, and the performance is worse.

<img width="1472" alt="Snipaste_2021-08-30_19-08-52" src="https://user-images.githubusercontent.com/8980981/131330600-92fa0f96-03b4-4d59-b12c-cd27b757f8fc.png">
<img width="1436" alt="Snipaste_2021-08-30_19-10-05" src="https://user-images.githubusercontent.com/8980981/131330642-000565a8-d5eb-4b1d-a3de-83532e138e52.png">

**Comment by yangysc** [comment]
Even I used what Bam4d suggested by changing to the following code

` self.stats = get_learner_stats(fetches) `

The performance is still bad for using two gpus...  

May I ask that, if multi-gpu (ppo) code has been tested that all exisiting tasks can be learned sucessfully just like using one gpu? @sven1977  Sorry for disturbing you again :<

**Comment by yangysc** [comment]
I tested some tasks using two gpus, and it seems the original code can work.  So which one is the right one?

**Comment by mvindiola1** [comment]
@Bam4d

Does flipping the keys fix this?

```python
batch_fetches[LEARNER_STATS_KEY]={} 
for i, batch in enumerate(device_batches):
            batch_fetches[LEARNER_STATS_KEY] [f"tower_{i}"] = self.extra_grad_info(batch)
```

**Comment by sven1977** [comment]
Thanks for raising this issue. Great catch! We should add a check to all agent "compilation" tests to check the structure of the stats.

To solve this: I think we should rather fix the `get_learner_stats()` function to handle the multi-GPU case and then use that function in all execution ops. We can use the existing all-tower-reduce code in `MultiGPUTrainOneStep` and move that into `get_learner_stats`, then use `get_learner_stats` consistently everywhere.

**Comment by sven1977** [comment]
@Bam4d @mvindiola1 ^

**Comment by sven1977** [comment]
Closing this issue. Please feel free to re-open it should there still be problems.
The above PR makes sure that all `Trainer.train()` returned results dict have the same structure (test for that added), regardless of the particular setup, like multi-GPU, tf/torch, multi-agent, num_sgd_iters>1.
