### ISSUE TITLE
[Datasets] Prevent Datasets from treating the first line of a CSV file as the header.

### ISSUE THREAD

**Issue by YeahNew** [ray-project/ray#18117]
ray.data.read_csv() will read the first line of the csv file as schma information by default. Whether this method can be modified, similar to spark.read.format("csv").option("header","False"), you can choose whether to read the first line of content.

**Comment by clarkzinzow** [comment]
Hi @YeahNew, that's great feedback, sorry that this issue fell through the cracks! I think that we could add an API for not treating the first line as the header, although we would then require the user to provide the column names at read time.

**Comment by clarkzinzow** [comment]
Hey @YeahNew, I just tried out using the Arrow `csv.ReadOptions(column_names=[...])` passthrough arg and confirmed that this (1) prevents the first line from being read as a header containing the column names, and (2) properly sets the column names. I opened a [PR](https://github.com/ray-project/ray/pull/24161) adding a test that does this!
