### ISSUE TITLE
Best way to diagnose the OOM problem in a Ray cluster

### ISSUE THREAD

**Issue by yuduber** [ray-project/ray#18134]
We are running Ray cluster heavily in our production with various models and sometime we encounter out of memory issue.  When this happens, it's very often difficult to diagnose which component of our training is causing the issue.  Since the end to end training process includes many parts, for example from data reader to shuffling, batch formation, then to trainer's model.  When the Ray worker node OOM and dies, we don't know which component or components is/are the major contributor of memory consumption.

Do we have any tool or guideline to help with debugging such case?

Typical logs of such OOM run is shown below:
In out peloton job link, we can see:

Memory limit exceeded: Requested: 128032MB Maximum Used: 128032MB MEMORY STATISTICS: cache 70078464 rss 133866430464 rss_huge 5765070848 shmem 69992448 mapped_file 70000640 dirty 8192 writeback 0 pgpgin 28909048 pgpgout 1454609 pgfault 29250854 pgmajfault 1 inactive_anon 69992448 active_anon 133866356736 inactive_file 16384 active_file 0 unevictable 4096 hierarchical_memory_limit 134251282432 total_cache 70078464 total_rss 133866430464 total_rss_huge 5765070848 total_shmem 69992448 total_mapped_file 70000640 total_dirty 8192 total_writeback 0 total_pgpgin 28909048 total_pgpgout 1454609 total_pgfault 29250854 total_pgmajfault 1 total_inactive_anon 69992448 total_active_anon 133866356736 total_inactive_file 16384 total_active_file 0 total_unevictable 4096

We want not only just the Ray's consumption of the memory, but also preferably memory footprint of other external components.

**Comment by rkooo567** [comment]
We currently don't have built-in general profiling tool for this. I think we can probably develop one that helps you to figure it out though (for example, each worker exposes its memory usage + running task name + etc., and we create a tool to poll them). 

But I am also curious what's the commonly used way for this sort of memory profiling problem. Do you mind following up with this https://github.com/ray-project/ray/issues/18134#issuecomment-906836020?

**Comment by yuduber** [comment]
One tool I used to use in my previous company was the jemalloc heap profiler, which can generate a map showing memory allocated by any function calls (need to compile with debug symbols) at a specific time of execution.

**Comment by rkooo567** [comment]
So for your case, what you are interested in is when the crash happens, you'd like to know the memory usage breakdown in components in your container right? And your container has its own memory limit allocated (like in your example, it is 128GB).

As a short term solution, I usually 
1. Keep track of memory usage per worker in your application. 
2. Provide memory > peak memory or introduce backpressure (e.g., if one of nodes have unbalanced memory usage, try spreading workload by adding more nodes or using different resources)

I have some questions.

1. Have you considered to track per-process memory and build a dashboard on it? 
2. Your OOM is from RAM usage right? So, Ray uses 30% of memory for object store (shm), and other components will use other 70% of memory, and I assume you are OOM is from RAM usage?
3. Do you typically know the memory usage of some of your work ahead of time? (e.g., when shuffling, do you estimate the memory usage of it ahead of time?) Or is it more like just allocate some amount of memory that doesn't crash?
4. Do you prefer low-overhead, less accurate solution (e.g., Ray exposes memory usage per worker associated with components, but cannot track 100% correct memory) or high-overhead, more accurate solution? (e.g., heap profiler, which can introduce large overhead, but could accurately track memory).
5. Let's say you can somehow figure out which component caused issue. What's the mitigation strategy here? Is there a way to control memory usage now? (like you give more backpressure to training or shuffle workload)

**Comment by rkooo567** [comment]
Also cc @scv119

**Comment by thuningxu** [comment]
For starters, can Ray log its memory usage using low overhead method periodically? Not through a 3rd-party metrics system such as prometheus but just print out?

**Comment by scv119** [comment]
@thuningxu @yuduber sorry that you have OOM issues using Ray. At the moment I'd suggest use the combination of jemalloc and `ray memory --stats-only` to debug memory related issues, which I used to debug OOM related issues for Anyscale product.

For memory usage observability we are actively looking into this area and planning project around it. The current idea is to integrate with jemalloc and periodically generate heap profile for each ray Process, as @thuningxu suggeted.

**Comment by scv119** [comment]
cc @mwtian @iycheng

**Comment by rkooo567** [comment]
@thuningxu 

> For starters, can Ray log its memory usage using low overhead method periodically? Not through a 3rd-party metrics system such as prometheus but just print out?

Where do you expect to see these logs (reading each log file or driver)? Also, you are looking for per-process memory usage?

**Comment by thuningxu** [comment]
Would be great if the driver can collect this for each worker. We should have per-process memory usage to look at the total amount.

**Comment by rkooo567** [comment]
cc @scv119 I think we shouldn't let it slip. I also heard a similar request from Dask on Ray user before (making memory profiling easy by providing per task/actor memory usage).

**Comment by rkooo567** [comment]
maybe consider to add it to the usability hot issue?

**Comment by scv119** [comment]
@rkooo567 yes please! maybe let's schedule an dev-infra hackathon?

**Comment by rkooo567** [comment]
Yes! That sounds fun!

**Comment by richardliaw** [comment]
Bumping on this; anything we can do here, maybe by 1.9 or 1.10?

This seems to be a recurring issue for multiple engagements, and it seems to be lowhanging fruit (adding some more logs about current/peak memory usage)

**Comment by rkooo567** [comment]
Maybe you can try this in the short term; https://github.com/ray-project/ray/blob/b52cc6ecdcc6599886a6e8710b438b169791e8b2/python/ray/_private/test_utils.py#L737

Example; https://github.com/ray-project/ray/blob/b52cc6ecdcc6599886a6e8710b438b169791e8b2/release/nightly_tests/dask_on_ray/large_scale_test.py#L446

This will print top 10 process memory usage for print_interval

EX)
```
success = 1
--
  | _peak_memory = 10.77
  | _peak_process_memory = PID	MEM	COMMAND
  | 195	2.64GiB	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=
  | 1297	1.4GiB	ray::IDLE
  | 1317	1.4GiB	ray::IDLE
  | 1321	1.4GiB	ray::IDLE
  | 2226	1.4GiB	ray::IDLE
  | 1247	1.4GiB	ray::IDLE
  | 1340	1.4GiB	ray::IDLE
  | 1309	1.4GiB	ray::IDLE
  | 1299	1.4GiB	ray::dask:load_array_one_minute-9bb17547-e737-48f4-abb7-932f2fa7a0ad
  | 1314	1.4GiB	ray::dask:load_array_one_minute-9a9e141b-44ed-4e20-afdf-ede0fd8251a1
```

**Comment by richardliaw** [comment]
@rkooo567 do we have a plan to include this in the next ray release?

**Comment by rkooo567** [comment]
We don't right now. But I think we can add this to the dashboard?

**Comment by frosk1** [comment]
would appreciate this feature

**Comment by rkooo567** [comment]
Hi, guys. We updated this documentation. https://docs.ray.io/en/master/ray-observability/monitoring-debugging/troubleshoot-failures.html#debugging-out-of-memory

We now support
- Ray level OOM killer to kill workers and automatically retry
- Event, metrics, and error messages to expose OOM failures
- Better metrics including per-taks/actor memory usages across the cluster.
- Per task/actor memory profiling (this is not fully supported yet, but we plan to do it by ray 2.7)

Please reopen or add comments if you have further feedback or feature request!
