### ISSUE TITLE
Feature Request for cleaning up the Ray cluster

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#1814]
Manually cleaning up the Ray cluster is necessary to users, especially for the unit test case that each one has a ray init. Currently, we could use `ray.worker.cleanup()`, but it is not part of Ray API. This ticket is to request the feature of supporting manually clean-up the Ray cluster.

**Comment by avaziri** [comment]
I would really like if we could get some sort of response to this feature request. I have also run into issues where the `ray.worker.cleanup()` deletes information in an unsafe order, causing future remote functions to fail. 

Essentially very similar to errors from https://github.com/ray-project/ray/issues/1798

**Comment by avaziri** [comment]
@robertnishihara That is the context in which I encounter this problem.

**Comment by RuofanKong** [comment]
Just wonder if there's any update for the ticket :)

**Comment by pschafhalter** [comment]
@RuofanKong #2374 should resolve this issue by exposing and documenting `ray.shutdown`

**Comment by RuofanKong** [comment]
@pschafhalter Ahh ok. Is `ray.shutdown()` supported for 0.5?

**Comment by pschafhalter** [comment]
No, 0.5 released last week and #2374 is still open/WIP. Will hopefully be supported for the next release in a few weeks.

**Comment by robertnishihara** [comment]
That's right. However, @RuofanKong, the behavior of `ray.shutdown` in #2374 is exactly the same as `ray.worker.cleanup`, so there shouldn't be any change in behavior there.

**Comment by robertnishihara** [comment]
Fixed by #2374. Let me know if this does what you want.
