### ISSUE TITLE
[Helm][Kubernetes] Ray Cluster sometimes fails to be created

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#18152]
### What is the problem?

Some users find that a RayCluster does not come up when installing the operator and Ray cluster in the same namespace.

```
➜  charts git:(master) ✗ helm upgrade --install ray-cluster ray 
Release "ray-cluster" does not exist. Installing it now.
NAME: ray-cluster
LAST DEPLOYED: Fri Aug 27 10:44:12 2021
NAMESPACE: default 
STATUS: deployed
REVISION: 1
TEST SUITE: None
➜  charts git:(master) ✗ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
ray-operator-5b9cd6dbd5-49277   1/1     Running   0          9s
➜  charts git:(master) ✗ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
ray-operator-5b9cd6dbd5-49277   1/1     Running   0          15s
➜  charts git:(master) ✗ kubectl get rayclusters
No resources found in  default  namespace.

Logs:
Not enough permissions to list namespaces. Falling back to a list of namespaces which are assumed to exist: {'default'}
Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.
Not enough permissions to watch for namespaces: changes (deletion/creation) will not be noticed; the namespaces are only refreshed on operator restarts.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Assuming this is now P1

**Comment by DmitriGekhtman** [comment]
This issue was resolved through Slack conversation. The issue in this case was that helm upgrade was used instead of helm install. In a similar-looking case, there was a problem with custom head Ray start commands.
