### ISSUE TITLE
docker.py's rsync is not working as intended

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18150]
### What is the problem?
Minimal reproduction:
- Have a 2 node ray cluster: one head and one worker.
- Create a source folder at /home/ray/tmp-result on worker and create a nested /home/ray/tmp-result/001 folder with some file in it.
- On headnode, invoke rsync function: 
```
rsync(
            cluster_config=cluster_config_file,
            source="/home/ray/tmp-result/",
            target="/home/ray/tmp-result/",
            down=True,
            ip_address=worker_node,
            use_internal_ip=True)
```
- Verify that on head node, there is only 001 under /home/ray/tmp-result
- Now, on worker node, create another 003 folder and remove 001 folder.
- On head node, remove 001 folder and run the same rsync
- After rsync, you will see both 001 and 003 folder on head node, while it really should be just 003.
It almost feels like that rsync has some memorization in itself. After rsync was used to sync a directory that contains certain sub directory x from source to target, even if x is then removed from both source and target, during a subsequent rsync, x will reappear on target (but not on source).

Tried to put together the following script but it's not entirely working due to some bootstrap error; but it should demonstrate the basic idea. My own debugging set up involves Ray Tune. It's not bare minimum but let me know if that set up is more helpful. 

```
import os
import shutil

from ray.autoscaler.sdk import rsync

WORKER_NODE_IP = "172.31.22.11"
CLUSTER_CONFIG_FILE = "/home/ray/ray_bootstrap_config.yaml"
PATH = "/home/ray/tmp-results/"


def main():
    try:
        shutil.rmtree(PATH)
    except:
        pass
    print("Please create remote folder /home/ray/tmp-results/001 on worker node and put some files in it. After this press continue.")
    import ipdb; ipdb.set_trace()
    rsync(
        cluster_config=CLUSTER_CONFIG_FILE,
        source=PATH,
        target=PATH,
        down=True,
        ip_address=WORKER_NODE_IP,
        use_internal_ip=True)
    print(f"Directories under {PATH} on head are {str(os.listdir(PATH))}.")
    print(
        "Please create remote folder /home/ray/tmp-results/003 on worker node and put some files in it. And remove 001 folder. After this press continue.")
    import ipdb; ipdb.set_trace()
    shutil.rmtree(os.path.join(PATH, "001"))
    print(f"After deletion, directories under {PATH} on head are {str(os.listdir(PATH))}."). # Should only see 003
    rsync(
        cluster_config=CLUSTER_CONFIG_FILE,
        source=PATH,
        target=PATH,
        down=True,
        ip_address=WORKER_NODE_IP,
        use_internal_ip=True)
    print(f"After rsync, directories under {PATH} on head are {str(os.listdir(PATH))}, while it should only contain 003.")

if __name__ == "__main__":
    main()
```

Pretty recent master. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
@richardliaw -- feel free to raise priority on this issue, you might have more context.

**Comment by richardliaw** [comment]
I'll bump this to P1, as this is a pretty important feature to get right.

**Comment by AmeerHajAli** [comment]
What is the use case here? why not use the filemounts in ray core?

**Comment by AmeerHajAli** [comment]
(Why is this related to autoscaling?)

**Comment by richardliaw** [comment]
New files need to be synced from the head to worker and from worker to head during the execution of the Tune run. 

We use `autoscaler.sdk.rsync` for this. 

Filemounts in ray core are static (and they're not bidirectional IIRC - they don't sync from worker to head).

**Comment by AmeerHajAli** [comment]
oh wow, I totally forgot that we have `autoscaler.sdk.rsync`

**Comment by ijrsvt** [comment]
> Is it possible to verify that this is also the case with rsync from shell?

@richardliaw Yep! I am able to reproduce with:
```
rsync --rsh "ssh -i /home/ray/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o 
UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 \
-o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/98bfe188d5/%C -o ControlPersist=10s -o ConnectTimeout=120s" \
-avz --exclude **/.git --exclude **/.git/** --filter "dir-merge,- .gitignore" ubuntu@10.0.1.110:/tmp/ray_tmp_mount/defaultIan/home/ray/tmp-result/ /home/ray/tmp-result/
```

IPs, directories & Control Path likely need to be changed.
