### ISSUE TITLE
[Core] actor call microbenchmark perf regression

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18168]
We've noticed there is a [40% regression](https://a5472365.us1a.app.preset.io/superset/dashboard/17/?preselect_filters=%7B%7D#CHART-Eiv4W7QpvZ) in n_n_(async)_actor_calls_async microbenchmark since Aug 27th. We should investigating if the trends continues.

**Comment by ericl** [comment]
b9978dd02b307bf95081b422e5427a13327c197a is the first bad commit
commit b9978dd02b307bf95081b422e5427a13327c197a
Author: chenk008 <kongchen28@gmail.com>
Date:   Tue Aug 24 04:34:32 2021 +0800

    [Core] revert: revert Unified worker starter (#18008)

 cpp/src/ray/config_internal.cc                     |  4 ++
 .../java/io/ray/test/WorkerJvmOptionsTest.java     |  7 +++
 python/ray/_private/services.py                    | 61 +++++++++++++++-------
 python/ray/tests/mock_setup_worker.py              | 12 +++++
 python/ray/tests/test_runtime_env_fork_process.py  | 25 +++++++++
 python/ray/tune/BUILD                              |  2 +-
 python/ray/workers/setup_runtime_env.py            | 47 +++++++++++++----
 src/ray/raylet/worker_pool.cc                      |  9 ----
 8 files changed, 129 insertions(+), 38 deletions(-)

**Comment by ericl** [comment]
I was able to bisect with `RAY_ADDRESS= TESTS_TO_RUN="n:n async-actor calls async" ray microbenchmark`

"good" commits -> 20-25k calls/s
"bad" commits -> 4-5k calls/s
