### ISSUE TITLE
First time i tried it and it does not work  - ctypes objects containing pointers cannot be pickled

### ISSUE THREAD

**Issue by Oxi84** [ray-project/ray#18195]
I read this module is supposed to be better than python multiprocessing, but when i have tried the same thing that works with ray i get: ctypes objects containing pointers cannot be pickled

Obviously there are not pointers in the object, these are just a few lists. Quite big lists, but python multiprocesing is handling them without any problem.

**Comment by richardliaw** [comment]
Can you provide a simple repro script @Oxi84 ?

**Comment by Oxi84** [comment]
I found the cause and its is not the software but the pickle module. My data is too complex to be pickled, so i tried to all the json such as normal json, orjson and so on and nothing worked except for one tuple of module for pickling but it was too slow and i cannot remember the name.

But thanks for trying to help.
