### ISSUE TITLE
ray dashboard hangs in "Loading..."

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18196]
CC @edoakes 

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by edoakes** [comment]
@AmeerHajAli please provide a reproduction for this

**Comment by jmakov** [comment]
Have the same problem here. `ray up cluster.yaml`, open localhost:8265. The page displays "Loading..." and "TypeError: NetworkError when attempting to fetch resource.".
