### ISSUE TITLE
Killing workers with running tasks

### ISSUE THREAD

**Issue by mehrdadn** [ray-project/ray#182]
We want the ability to kill workers with running tasks. Some things to think through and figure out beforehand:

1. When workers notify the scheduler that the task has been completed, the scheduler should not mark the worker as available.

2. Think through what to do if the scheduler receives a `SubmitTask` or `PutObj` from a worker that has been marked for dying.

3. The driver or a worker may have called pull on an object that may never be delivered. (Maybe send some kind of Object Unavailable reply to the object stores so that they notify the workers?)

**Comment by robertnishihara** [comment]
#148 lets the scheduler kill all of the workers when there are no currently running tasks and no tasks in the task queue. This does not address the setting where there are tasks running and tasks in the task queue.

**Comment by robertnishihara** [comment]
#190 makes it possible to restart workers (e.g., and have them use new application code). This is still only in the setting where there are no tasks running and no tasks in the task queue.

**Comment by robertnishihara** [comment]
Closing because the current work flow no longer requires us to kill workers. It will probably be useful to have similar functionality, e.g., the ability to cancel a task, but we'll track that separately.
