### ISSUE TITLE
Use glog for C++ logging.

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#1820]
` RAY_LOG(INFO) << "Add() issued; about to do Lookup()";` prints
```
Add() issued; about to do Lookup()
```
whereas glog's macro, `LOG(INFO) << "Mutated key: " << key_str << "; size: " << key_str.size();` prints
```
I0403 11:21:51.685478 2963071808 chain_module.h:313] Mutated key: ; size: 0
```
The timestamp, filename, and line number are critical information for debugging.

Relevant discussion in https://github.com/ray-project/ray/pull/1805.

**Comment by robertnishihara** [comment]
Fixed by #2695.
