### ISSUE TITLE
ami-0a2363a9cff180a64 used in examples may no longer exist

### ISSUE THREAD

**Issue by tdhopper** [ray-project/ray#18207]
I am trying to follow steps for deploying Ray to AWS, and it fails trying to find the AMI ami-0a2363a9cff180a64. I believe the AMI no longer exists.

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

Follow AWS steps [here](https://docs.ray.io/en/latest/cluster/quickstart.html)

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
Hey @tdhopper is it possible that you've changed your AWS region? 

The ami-0a2363a9cff180a64 AMI should only exist for us-west-2 (and still works for me)

**Comment by tdhopper** [comment]
Ah, that is the case. I don't have access to us-west-2 on my infrastructure. Thanks.
