### ISSUE TITLE
[helm][kubernetes][autoscaler] Helm cluster deletion is awkward

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#18212]
Currently uninstalling a helm-installed Ray cluster requires deleting the RayCluster CR and then uninstalling the helm chart.
Failing to do this in the right order lands you in a weird state. This UX is terrible. 
Fix so that a single helm uninstall cleans resources cleanly.

**Comment by mikwieczorek** [comment]
Hi, any updated on the problem @DmitriGekhtman ? 
Using `helm uninstall ray-cluster` removes the operator while the head and workers are intact. 

BTW. Is the k8s operator still the recommended way or KubeRay is the new way for deploying RayCluster?

**Comment by DmitriGekhtman** [comment]
It's possible to install and uninstall Ray clusters and the operator independently.
See https://docs.ray.io/en/latest/cluster/kubernetes-advanced.html#running-multiple-ray-clusters

> BTW. Is the k8s operator still the recommended way or KubeRay is the new way for deploying RayCluster?

I'd personally recommend KubeRay. Main caveat with KubeRay is that Ray autoscaler integration is still in the works. If you're ok with statically sized clusters (or managing scale yourself) then go with KubeRay.

**Comment by DmitriGekhtman** [comment]
Not an issue with KubeRay which is the preferred solution for deploying on K8s.
