### ISSUE TITLE
[client] Ray Client times out when connecting to a cluster running docker

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#18226]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 1.6.0, fresh virtualenv. Also reproducible with nightly.

Ray Client times out when connecting to a node which is running docker. Works fine without docker.

### Reproduction (REQUIRED)
Script:
```python
import ray

@ray.remote
def func():
    return 1

ray.init("ray://IP")

ray.get(func.remote())
```

Cluster config: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-gpu-docker.yaml

**Comment by richardliaw** [comment]
cc @AmeerHajAli @DmitriGekhtman @ckw017

**Comment by AmeerHajAli** [comment]
What you mean by times out? Do you mean while your running it times out or it never connects?

**Comment by AmeerHajAli** [comment]
did you expose the port on the head node in the AWS console?

**Comment by DmitriGekhtman** [comment]
Is the script in the PR description executed locally (laptop)?

**Comment by Yard1** [comment]
@AmeerHajAli 
I get `ConnectionError: ray client connection timeout`. I have tried to use security groups to expose the port, didn't change anything. It works fine without docker - I can connect if ray is running on the node directly.

@DmitriGekhtman 
Yes.

**Comment by AmeerHajAli** [comment]
can you check the ray/python versions on the docker and on the laptop?

**Comment by Yard1** [comment]
@AmeerHajAli  I've switched to using the py38 docker image.

Local: Python 3.8.10 ray, version 1.6.0
Remote: Python 3.8.5 ray, version 1.6.0

**Comment by richardliaw** [comment]
Bumping @AmeerHajAli @DmitriGekhtman @ckw017

What are our options at this point?

**Comment by ckw017** [comment]
Any chance you can sanity check that whatever methods of exposing the docker port work in general? From inside docker you can do something like: `python -m http.server --bind 0.0.0.0 8000` inside, and then see if you can see anything on port 8000 from your laptop

**Comment by Yard1** [comment]
Tried that, and it didn't work. Looks more like a Docker issue. I took a look at the default Docker run args that Autoscaler uses, and it contains `--net=host`, which should bind all ports in the container to the host, but it doesn't seem to work for some reason. @ijrsvt Do you have any ideas? The client server inside the container is running:
```
(base) ray@ip-172-31-23-31:~$ ps aux | grep client
ray        330  0.5  0.1 664444 77776 ?        Sl   11:06   0:02 /home/ray/anaconda3/bin/python -m ray.util.client.server --redis-address=172.31.23.31:6379 --port=10001 --mode=proxy --redis-password=5241590000000000 --serialized-runtime-env {}
ray        601  0.0  0.0  13216  1156 pts/2    S+   11:12   0:00 grep --color=auto client
```

**Comment by AmeerHajAli** [comment]
can you also try:
ray.client(IP).connect()?

**Comment by Yard1** [comment]
Same result, `ConnectionError: ray client connection timeout`

**Comment by AmeerHajAli** [comment]
what is the IP you are using?

**Comment by Yard1** [comment]
I am using the external AWS instance IP with the port (10001) specified. I double checked - the IP is correct.

**Comment by Yard1** [comment]
The issue was caused by a misconfigured security group for AWS - specifying a new one in the cluster environment fixed the issue. I think this is something we should document/warn about. Thanks @ckw017 for sitting down with me to figure it out!

**Comment by AmeerHajAli** [comment]
@Yard1 , since it was very helpful for you, do you mind making a followup documentation PR?

**Comment by AmeerHajAli** [comment]
Thanks @ckw017 !

**Comment by Yard1** [comment]
@AmeerHajAli Yeah, will do

**Comment by AmeerHajAli** [comment]
@Yard1 , please assign me as a reviewer + Assignee on the PR when ready.
