### ISSUE TITLE
[sgd] Bug in Example code for RaySGD examples

### ISSUE THREAD

**Issue by ZhijieWang** [ray-project/ray#18232]
### What is the problem?
1.5.2 Ray, running example code in the doc.

### Reproduction (REQUIRED)
Original code from here https://docs.ray.io/en/latest/raysgd/raysgd_pytorch.html#
```import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from ray.util.sgd.torch import TrainingOperator
from ray.util.sgd.torch.examples.train_example import LinearDataset

class MyTrainingOperator(TrainingOperator):
    def setup(self, config):
        # Setup all components needed for training here. This could include
        # data, models, optimizers, loss & schedulers.

        # Setup data loaders.
        train_dataset, val_dataset = LinearDataset(2, 5), LinearDataset(2,
                                                                        5)
        train_loader = DataLoader(train_dataset,
                                  batch_size=config["batch_size"])
        val_loader = DataLoader(val_dataset,
                                batch_size=config["batch_size"])

        # Setup model.
        model = nn.Linear(1, 1)

        # Setup optimizer.
        optimizer = torch.optim.SGD(model.parameters(), lr=config.get("lr", 1e-4))

        # Setup loss.
        criterion = torch.nn.BCELoss()

        # Setup scheduler.
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.9)

        # Register all of these components with Ray SGD.
        # This allows Ray SGD to do framework level setup like Cuda, DDP,
        # Distributed Sampling, FP16.
        # We also assign the return values of self.register to instance
        # attributes so we can access it in our custom training/validation
        # methods.
        self.model, self.optimizer, self.criterion, self.scheduler = \
            self.register(models=model, optimizers=optimizer,
                          criterion=criterion,
                          schedulers=scheduler)
        self.register_data(train_loader=train_loader, validation_loader=val_loader)
```

![Screen Shot 2021-08-30 at 2 26 18 PM](https://user-images.githubusercontent.com/1463296/131408303-b89ccc03-c2b7-438d-bac8-f6eb4c951d49.png)

![Screen Shot 2021-08-30 at 2 26 07 PM](https://user-images.githubusercontent.com/1463296/131408310-310f76a8-d89f-4ca0-b393-bdc51e95d156.png)

`criterion = torch.nn.BCELoss()` can be replaced with `criterion = torch.nn.MSELoss()`

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by amogkam** [comment]
We have now deprecated Ray SGD and have replaced with with [Ray Train](https://docs.ray.io/en/latest/train/train.html) which provides a more flexible API for distributed deep learning training on Ray!

The documentation containing this example will be removed.

**Comment by matthewdeng** [comment]
@pcmoritz RaySGD has been deprecated, and the documentation has been removed in Ray 1.13: https://docs.ray.io/en/releases-1.13.0/
