### ISSUE TITLE
[Datasets] Document comparison between NVTabular, Petastorm

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#18233]
### What is the problem?

We need to frame the comparison of Ray Datasets to other "ingest" frameworks.

* Petastorm: DQ’ed because lack of support for sparse tensors (ragged tensors) and controlled batch size.
* NVIDIA NVTabular
* TF Transforms.

**Comment by richardliaw** [comment]
Recommend doing this with priority :) 

cc @wuisawesome @clarkzinzow @ericl

**Comment by daikeshi** [comment]
Hey @richardliaw, we are also interested in seeing the comparison between Ray Datasets and NVTabular/TF.Transform. It'll be super helpful if we can get more insights. Thank you!

**Comment by clarkzinzow** [comment]
Completed in Datasets FAQ.
