### ISSUE TITLE
rllib: possible error message improvement

### ISSUE THREAD

**Issue by jmugan** [ray-project/ray#18231]
I made the mistake of defining the observation space with a Python dict instead of `gym.spaces.Dict`.

The error message was `ValueError: observation_space not provided in PolicySpec for default_policy and env does not have an observation space OR no spaces received from other workers' env(s) OR no observation_space specified in config!`

Presumably, it found `observation_space` in the environment but decided it was invalid since it wasn't a `gym.spaces`.

The error message could be improved by maybe noting when an `observation_space` isn't a `gym.spaces`.

@richardliaw suggested that I post this as an issue.

Thanks for the great work. I'm loving rllib so far.

**Comment by richardliaw** [comment]
Awesome thanks for this :) I've cc'ed Sven, who maintains RLlib. Hopefully we can get this patch in by the next release (also contributions are totally welcome) :)

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/18249
@jmugan ^
