### ISSUE TITLE
[tune] Grid search hangs with 40+ nodes

### ISSUE THREAD

**Issue by henrique** [ray-project/ray#18244]
### What is the problem?

A large grid search with more than 40 nodes seems to hang indefinitely (or at least for a couple of hours).
I can successfully run the same code with up to 20 GPU nodes (1 GPU per node), or 10 CPU nodes (24 cores each).
20 CPU nodes (480 parallel trials) also seems to hang, so it may or may not have something to do with the number of trials, I am not sure.
I have only tested it using our SLURM cluster, so that could be the issue as well. However, it does seem to immediately start the server without any issue, and I can see all resources being listed correctly:
```
== Status ==
Memory usage on this node: 12.8/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/960 CPUs, 0/40 GPUs, 0.0/1706.85 GiB heap, 0.0/734.13 GiB objects (0.0/40.0 accelerator_type:P100)
Number of trials: 1056/8000 (1056 PENDING)
...
```
It keeps printing the status and list of trials, over and over without starting the actual runs.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray[tune] 1.4 / 1.6

### Reproduction (REQUIRED)
- [ X ] I have verified my script runs in a clean environment and reproduces the issue.
- [ X ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

```
import ray
from ray import tune

import os
import time
import numpy as np
from attrdict import AttrDict

def train_model(config, checkpoint_dir):
    ''' Dummy trainable '''
    args = AttrDict(**config)
    print(checkpoint_dir, config)

    for epoch in range(args.epochs):
        print(f"epoch {epoch} iteration")
        time.sleep(3)
        val_accuracy = epoch / args.epochs
        tune.report(epoch=epoch, accuracy=val_accuracy)

    return dict(epoch=epoch, accuracy=val_accuracy)


if __name__ == '__main__':
    if 'RAY_HEAD_NODE' in os.environ:
        ray.init(address='auto',
                _node_ip_address=os.environ['RAY_HEAD_NODE'],
                _redis_password=os.environ['RAY_REDIS_PASSWORD'])
    else:
        ray.init()  # single node

    local_dir = os.getenv('SCRATCH', '/tmp')
    job_name = 'grid-search'
    analysis = tune.run(
        train_model,
        num_samples=1,
        local_dir=local_dir,
        name=job_name,
        metric='accuracy',
        mode='max',
        config={
            'wd': tune.grid_search(list(np.logspace(1e-5, 1e-3, num=20))),
            'base_lr': tune.grid_search(list(np.logspace(1e-5, 0.2, num=20))),
            'momentum': tune.grid_search(list(np.linspace(0.75, 0.95, num=20))),
            'epochs': 19,
            # ...
        }
    )

    print(analysis.best_config)
```

**Comment by richardliaw** [comment]
Hey @henrique , good to see you back! 

That seems unfortunate. Would it be possible to provide the system logs for us to diagnose the issue?

Specifically, if you can get `/tmp/ray/session_latest/logs` as a zip from the head node of a hanging cluster, that would be really useful.

**Comment by henrique** [comment]
Hi @richardliaw 
Thanks for the prompt response.
1st, How can I change that log dir?  I don't really have access to `/tmp` on those machines :roll_eyes: 

2nd, trying to make a simpler example, I have just realised that this might actually be a problem with our distributed file system (I assume you guys have also tested ray with many nodes before):
   It seems to work if I remove the `local_dir` parameter, so I guess the workers might perhaps be stuck trying to create that folder, or similar.
   Is there a way to make the workers start in a more serial way? I.e. so that not all workers access the folder at the same time?

Thanks again for your help!

**Comment by richardliaw** [comment]
Hmm, maybe local_dir points to `~/` which might be a distributed file system?

If you have a local file system on each node (on my previous slurm setup it was /data), you should point your local dir to that if possible.

**Comment by henrique** [comment]
Our nodes don't have any local drives, so it's all distributed anyway.
It seems a bit weird that it worked with local_dir defaulting to HOME, instead of the faster lustre fs I was pointing to before.
I need to do some more tests, I guess.

BTW, I couldn't find any ray session logs when it hangs, even when setting `_temp_dir`.
I'm also still sometimes having out of memory problems or even failing to just start the head node, maybe the sleeps in the slurm script aren't enough (It would be nice to find a better solution for the latter).

I will try this again when I have more time.
Thanks again for your attention @richardliaw and please let me know if you have any other tips/ideas
Cheers!
