### ISSUE TITLE
type of agent_id in [rllib] multiagent 

### ISSUE THREAD

**Issue by niujh** [ray-project/ray#18272]
### What is the problem?

type of agent_id

Firstly, https://docs.ray.io/en/master/rllib-env.html take agent_id as type str

trainer = pg.PGAgent(env="my_multiagent_env", config={
    "multiagent": {
        "policies": {
            # the first tuple value is None -> uses default policy
            "car1": (None, car_obs_space, car_act_space, {"gamma": 0.85}),
            "car2": (None, car_obs_space, car_act_space, {"gamma": 0.99}),
            "traffic_light": (None, tl_obs_space, tl_act_space, {}),
        },
        "policy_mapping_fn":
            lambda agent_id:
                "traffic_light"  # Traffic lights are always controlled by this policy
                if agent_id.startswith("traffic_light_")
                else random.choice(["car1", "car2"])  # Randomly choose from car policies
    },
})

while https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent_two_trainers.py takes agent_id  as type int

    def policy_mapping_fn(agent_id, episode, **kwargs):
        if agent_id % 2 == 0:
            return "ppo_policy"
        else:
            return "dqn_policy"

Now, what can i do, if i wish the policy be selected by the agent name.

**Comment by mvindiola1** [comment]
The agent_id can be any type that is a valid key in a dictionary. The policy_mapping_function takes the agent_id as input so if the ids are strings then treat them as such. If they are currently integers then change them to strings if that is what you need.

**Comment by sven1977** [comment]
Hey @niujh , what @mvindiola1 said :): Agent IDs are produced by your env, so their type/nature are entirely in your env's hands. The env can decide to use ints as agent IDs (e.g. 0, 1, ...) or strings (e.g. "ag0", "ag1", but also "1", "2", etc..). Your `policy_mapping_fn` must handle these particular agent IDs coming from your env. In the above example, the `policy_mapping_fn` handles only ints as agent IDs. An example policy_mapping_fn that would handle agent ID strings could e.g. be:
```
def policy_mapping_fn(agent_id, episode, worker, **kwargs):
    if agent_id == "agent0":
        return "ppo_policy"
    else:
        return "dqn_policy"
```

**Comment by sven1977** [comment]
Closing this issue now as answers have been provided.
