### ISSUE TITLE
[runtime env] add "includes" or some other way of overriding "excludes"

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18279]
### Describe your feature request
Currently runtime environments allows files to be excluded from being uploaded as part of the working_dir via the option `"excludes"`.  However, currently there's no way to override this force a file to be included.  

One concrete situation is if someone's project contains a `.gitignore` file containing some `.pkl` files.  (The `.pkl` files are necessary to run the code, but the user doesn't want them in their git repository.)  However, currently Ray parses the `.gitignore` file and excludes the listed files from being uploaded to the working directory.  The result is that the `.pkl` files are not uploaded to the cluster, and the user's code doesn't work.

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by richardliaw** [comment]
This should be implemented already right? I see `excludes` as a listed parameter in https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#id1.

(However I don't see it as a parameter listed on RuntimeEnv config object):

https://docs.ray.io/en/latest/_modules/ray/runtime_env/runtime_env.html

**Comment by architkulkarni** [comment]
Yeah, we already have `"excludes"`, but there are some cases where you still want to override that and include some files without modifying `.gitignore`, and the current`"excludes"` API isn't enough.

The RuntimeEnvConfig is a different object from RuntimeEnv itself which has more meta-level configuration options for the runtime env install.

**Comment by architkulkarni** [comment]
Bumping to P1 as we've heard more than one user request this, and there's no viable workaround except for committing the unwanted large files to git.

**Comment by architkulkarni** [comment]
@edoakes Can I get your opinion on the following API?

The proposal is to add the env var `RAY_RUNTIME_ENV_SKIP_GITIGNORE` which makes the packaging code skip the part where it parses the gitignore into the `"excludes"` list.

The behavior is simpler than `"includes"`.  The downside is for the use case in the issue, the user will have to manually parse their `.gitignore` file into the `excludes` list, but this is just a couple lines of Python.

**Comment by edoakes** [comment]
@architkulkarni what's the issue you're referring to?

**Comment by architkulkarni** [comment]
Sorry, I meant the present issue, it's just the case that the user has a few large files in their gitignore which are nevertheless required in the `working_dir`.   If the user wants to "include" these files but still respect the rest of the `.gitignore`, then if they use this env var they'd have to populate their own `excludes` list which consists of their gitignore minus those files.

**Comment by edoakes** [comment]
Oh, got it, I think that is a pretty reasonable workaround...

**Comment by lonsdale8734** [comment]
@edoakes `excludes` not support `!` prefix? From https://git-scm.com/docs/gitignore:

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again.

**Comment by edoakes** [comment]
Hmm, I'm not sure. IIRC we use a library to do the pattern matching. Would be simple enough to test out.

**Comment by m-walters** [comment]
> [@edoakes](https://github.com/edoakes) `excludes` not support `!` prefix? From https://git-scm.com/docs/gitignore:
> 
> > An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again.

I'm finding the same!
In my `.gitignore` I (of course) filter `*.env` files. but I can't re-add these to ray with `!some-specific.env` or `!*.env`.
Then raylet complains:
```bash
(raylet) error: No environment file found at: ....
```

And if I remove/comment it in `.gitignore` then it works. My guess is that it comes down to order? If the `.gitignore` files are loaded after, then it will override my `!*.env` term.
