### ISSUE TITLE
[operator] Ray Operator ApiServer error

### ISSUE THREAD

**Issue by smandrell-ec** [ray-project/ray#18276]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

I am trying to deploy the ray operator and ray cluster with helm, following the instructions here: https://docs.ray.io/en/master/cluster/kubernetes.html#installation

The operator succeeds in deploying, however there is a `Crashbackloop` and the specific failure log in the operator's pod is
```
Traceback (most recent call last): File "/home/ray/anaconda3/lib/python3.7/site-packages/kopf/_cogs/clients/errors.py", line 148, in check_response response.raise_for_status() File "/home/ray/anaconda3/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status headers=self.headers, aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('https://10.253.24.1:443/apis/packages.operators.coreos.com/v1')
```

### Reproduction (REQUIRED)
Simply follow preparation steps [here](https://docs.ray.io/en/master/cluster/kubernetes.html#preparation) and then the installation steps [here](https://docs.ray.io/en/master/cluster/kubernetes.html#installation).

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [yes] I have verified my script runs in a clean environment and reproduces the issue.
- [yes] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by socar-humphrey** [comment]
I encountered the same error. Is there anyone who figured out how to resolve this issue?

**Comment by smandrell-ec** [comment]
We moved to Kubeflow because of this and it has been great.

**Comment by sidazhou** [comment]
Ok, apparently the problem/solution is this: https://github.com/helm/helm/issues/6361#issuecomment-538220109
