### ISSUE TITLE
[datasets] Requirements for my use case

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#18297]
### Describe your feature request

I have a use case for datasets that I need to get working.

Cluster environment:

Ideal 2 workloads that work:

**Local shuffle**

```python
ds = ray.data.read_parquet(hdfs)
splits = ds.split(num_workers)

@ray.remote(num_gpus=1)
def consume(split):
    # ideally I can do a local sliding window shuffle. maybe we can just wrap this in Petastorm?
    # split = split.iter_batches(100000).random_shuffle().to_torch(batch_size=250)
    iterator = split.to_torch(batch_size=250)
    all_lengths = []
    for i in range(epochs):
		length = 0
        for data, labels in iterator:
            y = model(data)
            length += len(data)
        all_lengths += [length]
        model.validate()
    
    return all_lengths

lengths = ray.get([consume.remote(split) for split in splits])
assert all(length == lengths[0] for length in lengths)
assert sum(lengths[0]) >= ds.count()
```

**Distributed Windowed Shuffle**

```python
ds = ray.data.read_parquet(hdfs)
window_pipe = ds.random_shuffle(window_size=100GB)
splits = window_pipe.split(num_workers)

@ray.remote(num_gpus=1)
def consume(split):
    iterator = split.to_torch(batch_size=250)
    all_lengths = []
    for i in range(epochs):
		length = 0
        for data, labels in iterator:
            y = model(data)
            length += len(data)
        all_lengths += [length]
        model.validate()
    
    return all_lengths

lengths = ray.get([consume.remote(split) for split in splits])
assert all(length == lengths[0] for length in lengths)
assert sum(lengths[0]) >= ds.count()
```

Requirements:
- [ ] I need to be able to shuffle a window of my data, where window > cluster space.
- [ ] I need to be able to detect when my epoch is finished
- [ ] I need a way to reuse the iterator to ingest the epoch (handle recurring epochs)
- [x] #18352
- [x] I need a way to get data into torch format

Nice to have:
- [ ] I would like to be able to specify a window of bytes, since the reason why i need windowing in the first place is to manage a smaller set of data.

**Comment by ericl** [comment]
For the first one can you use map batches to implement it? `split.map_batches(lambda batch: batch.shuffle())`

**Comment by richardliaw** [comment]
@ericl Unfortunately `.shuffle` doesn't exist as an API.

Concretely, is the suggestion to do:

```
map_batches(lambda batch: batch.to_pandas().sample(1).to_pyarrow_table())
```
?

**Comment by ericl** [comment]
Yeah, something like that. Though I don't think you need to call
.to_pyarrow_table(), just use .map_batches(batch_format="pandas")
Eric

**Comment by richardliaw** [comment]
yep
