### ISSUE TITLE
Placement group request never completes if cluster has nodes with different CPU counts and request includes bundle with more than minimum number of CPUs

### ISSUE THREAD

**Issue by jfischer** [ray-project/ray#18309]
### What is the problem?
I have an on-premises cluster with three nodes: one with 8 CPUs and two with 16 CPUs each. If I create a bundle with one 8-cpu entry and two 16-cpu entries, the wait for the placement group to be ready hangs forever. It seems that, if you have unequal cpu counts in your nodes, you can only request a placement group with the maximum cpu count equal to the smallest node in your cluster (e.g. 3 entries with 8 CPUs each in my case). 

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 1.6 and latest nightly, Python 3.9, Linux

### Reproduction (REQUIRED)
Here is a command line script that reproduces the issue on my cluster:
```
#!/usr/bin/env python3
"""
Try to run a worker on all the CPUs in the cluster.
"""
import sys
import ray
import ray.util
import argparse
from collections import Counter

@ray.remote(num_cpus=1.0)
def worker():
    import socket
    return socket.gethostname()

def main(argv=sys.argv[1:]):
    parser = argparse.ArgumentParser()
    parser.add_argument("--address", default="auto", type=str, help="Address for this Ray node")
    parser.add_argument("--redis-password", default=None, help="Password to use for Redis")
    parser.add_argument( "--strategy", default="STRICT_SPREAD",
        help="Stategy for placement group bundle allocation. Default is STRICT_SPREAD, use 'None' to get default."
    )
    args = parser.parse_args(argv)

    print("Initializing Ray...")
    if args.redis_password is not None:
        ray.init(address=args.address, _redis_password=args.redis_password)
    else:
        ray.init(address=args.address)

    nodes = [
        node for node in ray.nodes() if node["Alive"] and "CPU" in node["Resources"]
    ]
    print("Nodes:")
    for node in nodes:
        print(f"  {node['NodeManagerHostname']} ({int(node['Resources']['CPU'])} cpus)")
    print()
    bundles = [{"CPU": node['Resources']['CPU']} for node in nodes]
    print(f"Bundles are {bundles}")
    strategy = args.strategy if args.strategy!="None" else None
    pg = ray.util.placement_group(bundles, strategy=strategy)
    print(f"Getting placement group with {len(bundles)} bundles and strategy {strategy}...")
    print(ray.get(pg.ready()))
    print(ray.util.placement_group_table(pg))

    # now, we run a worker on each CPU in the placement group
    pg_indexes = []
    for (bundle_index, bundle) in enumerate(bundles):
        for cpu in range(int(bundle['CPU'])):
            pg_indexes.append(bundle_index)
    futures = [worker.options(placement_group=pg, placement_group_bundle_index=index).remote() for index in pg_indexes]
    hosts = Counter(ray.get(futures))
    print("Completed successfully.")
    print(f"Task to host mapping was: {hosts}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
```
Here is the output, if I run it on my cluster:
```
2021-09-01 10:07:08,723	INFO worker.py:825 -- Connecting to existing Ray cluster at address: 192.168.1.30:6379
Nodes:
  kapalua (8 cpus)
  benben (16 cpus)
  margie (16 cpus)
Bundles are [{'CPU': 8.0}, {'CPU': 16.0}, {'CPU': 16.0}]
Getting placement group with 3 bundles and strategy STRICT_SPREAD...
```
The program then hangs at this point.

Ideally, the placement group service would look though the node database and find a matching node for the larger requests, taking into account the CPU capability. My workaround has been to either disable the workers on the smaller node (so I run two 16-cpu bundles) or pick the smallest node and run the 

- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jfischer** [comment]
I discussed this issue on Slack with @ericl and he asked me to file a bug.

**Comment by rkooo567** [comment]
So, to be clear, you have

{CPU: 16, CPU:16, CPU:8} nodes and [{CPU:16}, {CPU:16}, {CPU:8}] cannot be scheduled with STRICT PACK right?

**Comment by ericl** [comment]
@rkooo567 can you try reproducing this with local clusterUtils multi-node?

**Comment by jfischer** [comment]
@rkooo567, yes, that is correct.

**Comment by rkooo567** [comment]
I will try repro tomorrow. Btw my guess is the scheduler is not smart enough to schedule on 8 cpus bundle to 8 cpus node (and allocate on the 16 cpus node).

**Comment by rkooo567** [comment]
I could reproduce it (it is actually flaky). Pretty sure it is just the scheduling algorithm is not smart enough to assign biggest resources first. Let me see if I can make a quick fix

**Comment by ericl** [comment]
Ah, so it's just a bin packing issue and not an actual bug. Agree we should assign the biggest bundles first, but downgrading to P1.

**Comment by rkooo567** [comment]
This will be soon fixed. Sorry for the delay. I am planning to merge the fix PR within 2 weeks.

**Comment by rkooo567** [comment]
@jon-chuang will take a look at this

**Comment by jon-chuang** [comment]
I have managed to repro with MWE for `STRICT_SPREAD`, `SPREAD`, `PACK` (when cannot fulfill `STRICT_` requirement on best effort basis): 
```python
cluster.add_node(num_cpus=1)
cluster.add_node(num_cpus=2)

placement_group = ray.util.placement_group(
    name="name",
    strategy="SPREAD",
    bundles=[{"CPU": 1}, {"CPU": 2}],
)
ray.get(placement_group.ready())
# hangs here
```
This does not affect: `STRICT_PACK` (which fails to allocate the resource) and fails with suitable error message:
```
Error: No available node types can fulfill resource request defaultdict(<class 'float'>, {'CPU': 3.0}). Add suitable node types to this cluster to resolve this issue.
```

**Comment by jon-chuang** [comment]
This is the issue: unimplemented sorting of resources:
```cpp
const std::vector<ResourceSet> &GcsResourceScheduler::SortRequiredResources(
    const std::vector<ResourceSet> &required_resources) {
  // TODO(ffbin): A bundle may require special resources, such as GPU. We need to
  // schedule bundles with special resource requirements first, which will be implemented
  // in the next pr.
  return required_resources;
}
```

**Comment by rkooo567** [comment]
@jfischer this must be fixed. let us know if you see the issue again!
