### ISSUE TITLE
[Ray object store] ray.put hangs when using multiple remote actors to put objects

### ISSUE THREAD

**Issue by ShuangQiuac** [ray-project/ray#18326]
### What is the problem?
We are trying to use ray object store to cache input data in memory.  When using multiple (e.g., 16) remote actors to run ray.put(split_data), it hung without throwing any exceptions.  (For 16 actors, each actor put 7300+ items concurrently.)

We checked the process with strace, and found it executing futex with ETIMEDOUT (connection timeout), and observed very low CPU utility for each of the put actor process.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray-1.4.0, python-3.7.9

### Reproduction (REQUIRED)
The following code snippet is the remote actor class:

    class QueueActor:  
        def __init__(self, file_list=[], maxsize=200000):
            self.maxsize = maxsize
            self.queue = queue.Queue(maxsize=maxsize)
            self.object_list = []
            self.file_list = file_list
            self.pops = 0
    
        def empty(self):
            return self.queue.empty()
    
        def put(self, item):
            filename = item[0]
            filepath = item[1]
            content = read_image_from_file(filepath)
            object_ref = ray.put(content)
            self.object_list.append((filename, object_ref))
            return self.queue.put(object_ref)
    
        def get(self, timeout=5):
            while self.pops < len(self.file_list):
                if not self.queue.empty():
                    object_ref = self.queue.get(timeout=timeout)
                    self.pops += 1
                    return ray.get(object_ref, timeout=timeout)
                else:
                    time.sleep(5)
            raise StopIteration
    
        def get_object_list(self):
            return self.object_list
    
        def put_batches(self):
            for item in self.file_list:
                self.put(item)
    
        def ready(self) -> bool:
            return len(self.object_list) == len(self.file_list)

**Comment by rkooo567** [comment]
@scv119 do you have some bandwidth to try reproducing it?

**Comment by ShuangQiuac** [comment]
It turns out to be a misusage of ray.wait (ray.wait returns immediately when I passed an object list that contains a ready object, and it causes the program hanging at ray.wait)
