### ISSUE TITLE
Build command doesn't work as expected

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/ray#18362]
### What is the problem?

When I tried to run `./build-docker.sh`, it starts to build `base-deps`, `ray-deps` and `ray`.
However, I notice this PR https://github.com/ray-project/ray/pull/16998 add one extra line `COPY $FIND_LINKS_PATH $FIND_LINKS_PATH` in `ray-deps` and `ray` Dockerfile. The commands failed because of missing `.whl`.

I am curious if I build image in an incorrect way or this is a real bug.  It's easy to reproduce but if that's the case, the release process should already break.  can someone help take a look?

```
++ basename /tmp/tmp.GEuUaWttx4/ray-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl
+ docker build --build-arg GPU= --build-arg BASE_IMAGE=ubuntu:focal --build-arg WHEEL_PATH=ray-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl --build-arg PYTHON_VERSION=3.7.7 -t rayproject/ray-deps:nightly docker/ray-deps
Sending build context to Docker daemon  49.58MB
Step 1/10 : ARG GPU=""
Step 2/10 : FROM rayproject/base-deps:nightly"$GPU"
 ---> 4f28fbd4c203
Step 3/10 : ARG AUTOSCALER="autoscaler"
 ---> Using cache
 ---> 1ded5abcb98b
Step 4/10 : ARG WHEEL_PATH
 ---> Using cache
 ---> 7787b0064a45
Step 5/10 : ARG FIND_LINKS_PATH=".whl"
 ---> Using cache
 ---> 18d44bd026d4
Step 6/10 : ENV LC_ALL=C.UTF-8
 ---> Using cache
 ---> 535d18e6c8bf
Step 7/10 : ENV LANG=C.UTF-8
 ---> Using cache
 ---> c79e5f2f9463
Step 8/10 : COPY $WHEEL_PATH .
 ---> Using cache
 ---> f05062f05f71
Step 9/10 : COPY $FIND_LINKS_PATH $FIND_LINKS_PATH
COPY failed: file not found in build context or excluded by .dockerignore: stat .whl: file does not exist
++ basename /tmp/tmp.GEuUaWttx4/ray-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl
+ rm docker/ray-deps/ray-1.6.0-cp37-cp37m-manylinux2014_x86_64.whl
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Download ray source and build the image. I am using 1.6.0 release tag
```
./build-docker.sh
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by umialpha** [comment]
I also have issue
