### ISSUE TITLE
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by juyunsang** [ray-project/ray#18378]
### What is the problem?
Hello
Training with large size data(2GB) results in the following error.
There is no problem with small size of training data(<100Mb)

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2021-09-06 17:15:49,920 [ERROR] Exception serializing message!
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_common.py", line 86, in _transform
    return transformer(message)
ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 2339503268
2021-09-06 17:15:49,925 [ERROR] Got Error from data channel -- shutting down:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/ray/util/client/dataclient.py", line 69, in _data_main
    for response in resp_stream:
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception serializing request!"
        debug_error_string = "None"
>
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by juyunsang** [comment]
@scv119 
Thank you for reply
ray version is 1.5.1
ray-lightning version is 0.11
pytorch-lightning version is 1.4.5
pytorch version is 1.7.0

inside the trainset object, 2GB of learning data is placed in memory and used.
If i reduce the number of trainset data, train well in ray cluster.
The size of the train set is over 2GB. Is this a problem?
Is it impossible for ray clusters to put over 2GB of training data in memory and use?

- dataset.py
```python
from torch.utils.data import Dataset
import json
class Trainset(Dataset):
      def __init__(self):
          self.total_data = []
          with open('trainset.json', 'r') as f:
                  for line in f:
                        self.total_data.append(self._preprocess_trainset(line))
      def __getitem__(self, idx):
          return self.total_data[idx]

      def __len__(self):
          return len(self.total_data)

     
   

```

- train.py
```python
    ray_cluster_connection = f'ray host'
    ray.client(ray_cluster_connection).namespace('test').connect()
    print(ray.available_resources())

    train_loader = DataLoader(trainset,
                        batch_size=cfg.batch_size,
                        num_workers=cfg.num_workers)
    valid_loader = DataLoader(validset,
                        batch_size=cfg.batch_size,
                        num_workers=cfg.num_workers)

    plugin = RayShardedPlugin(num_workers=2, num_cpus_per_worker=1, use_gpu=True)

    logging.info("training start")
    trainer = pl.Trainer(
        logger=[tb_logger],
        gpus=1,
        max_steps=cfg.max_steps,
        val_check_interval=cfg.val_check_interval,
        log_every_n_steps=cfg.log_interval,
        precision=16 if cfg.train.use_fp16 else 32,
        flush_logs_every_n_steps=cfg.flush_logs_every_n_steps,
        progress_bar_refresh_rate=cfg.progress_bar_refresh_rate,
        plugins=[plugin]
    )
    trainer.fit(model, train_loader, valid_loader)
```

**Comment by rkooo567** [comment]
This must be the client issue where the returned data message size limit is 2GB. We should probably use streaming to get the return value from the ray cluster. cc @AmeerHajAli @ijrsvt

**Comment by scv119** [comment]
also cc @richard4912

**Comment by AmeerHajAli** [comment]
Can you use file mounts in the cluster yaml to uplod the files and have ray client just operate on files existing on the cluster?

**Comment by AmeerHajAli** [comment]
Also cc @iycheng

**Comment by juyunsang** [comment]
@AmeerHajAli 
Thank you for reply
I mounted nfs on the ray cluster and built it.
2GB size trainet.json is stored in nfs and ray cluster reads files in nfs.
If there's anything else I need to test, I'd appreciate it.

**Comment by juyunsang** [comment]
@AmeerHajAli @rkooo567 
hello
Is there any suggestion to solve this problem?

**Comment by AmeerHajAli** [comment]
@juyunsang , can you use file mounts and not upload the data with ray client?

here is a link to file mounts:
https://docs.ray.io/en/master/cluster/config.html#cluster-configuration-file-mounts

**Comment by AmeerHajAli** [comment]
@mwtian , any suggestions on what we can do here?

**Comment by mwtian** [comment]
As @rkooo567 mentioned above, using streaming to chunk data transfer can likely solve the issue here. `ray.put()` should be converted to a streaming-unary RPC.

**Comment by AmeerHajAli** [comment]
Can we make this change as part of making ray.put() async? How complex is that?

**Comment by mwtian** [comment]
Chatted with Ameer. This should be doable. We will start looking at this 1 week from now.

**Comment by ericl** [comment]
How about changing this to raise a better warning, such as "your request is too large, consider doing this in a remote task".

I'm concerned we're optimizing an anti-pattern here if we implement uploading huge objects (which is going to be super slow over the client anyways).

**Comment by amogkam** [comment]
@ckw017 @AmeerHajAli can we revisit this issue? The same problem is happening again in https://github.com/ray-project/ray/issues/20869.

It would be great if we can prioritize this and have a better error message.

**Comment by rkooo567** [comment]
cc @scv119 @ericl  maybe we should prioritizing raising a better error here?

**Comment by ICESDHR** [comment]
> Chatted with Ameer. This should be doable. We will start looking at this 1 week from now.

hi, i have the same problem.It's been three weeks. Any progress?  I'd appreciate any other suggestions.

**Comment by ckw017** [comment]
We'll be bumping the priority of this!

**Comment by ICESDHR** [comment]
> 

Do you have an optimization plan? When will it be available?

**Comment by ICESDHR** [comment]
> We'll be bumping the priority of this!

Do you have an optimization plan? When will it be available?
And Is there a temporary method that can be quickly modified?

**Comment by AmeerHajAli** [comment]
@ICESDHR , to the best of my knowledge, we will only improve the error message. We do not recommend transferring 2GB+ data over the network from your laptop and instead perhaps you can change your code so that Ray can download the data instead of uploading it.

**Comment by ICESDHR** [comment]
> @ICESDHR , to the best of my knowledge, we will only improve the error message. We do not recommend transferring 2GB+ data over the network from your laptop and instead perhaps you can change your code so that Ray can download the data instead of uploading it.

i have the similar problem.
i use TuneSearchCV function to train model use 4GB dataset, my code is 
```
tune_search = TuneSearchCV(
        clf,
        parameter_grid,
        search_optimization="bayesian",
        n_trials=30,
        early_stopping=True,
        max_iters=3,
        verbose=2,
        time_budget_s=10,
    )
    tune_search.fit(x_train, y_train)
```
In the implementation of method TuneSearchCV.fit(), i found data transfer is forced, and data size > 2GB, and Throw an error like **ValueError: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 5979803541**

```
# tune_sklearn/tune_basesearch.py
def _fit(self, X, y=None, groups=None, tune_params=None, **fit_params):
    ...
    X_id = ray.put(X)
    y_id = ray.put(y)
    ....
```

**so i think this is a bug. if only fix error message, function TuneSearchCV() can't train dataset which large than 2GB!**

**Comment by richardliaw** [comment]
@ICESDHR can you help clarify what your cluster setup is and are you calling ray.init somewhere?

**Comment by ICESDHR** [comment]
@richardliaw i deploy ray cluster in k8s,  one head and three workers(they're both 2CPU & 20G memory)

my code like this, it's work well when dataset < 2GB. if i use 4GB dataset ,it's broken down and throw Error: Message ray.rpc.DataRequest exceeds maximum protobuf size of 2GB: 5979803541


```
x = mydata.data
y = mydata.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

clf = SGDClassifier()

ray.init(config.ray_address)
tune_search = TuneSearchCV(
    clf,
    parameter_grid,
    search_optimization="bayesian",
    n_trials=30,
    early_stopping=True,
    max_iters=3,
    verbose=2,
    time_budget_s=10,
)
tune_search.fit(x, y)
```

**Comment by richardliaw** [comment]
@ICESDHR can you help clarify, where are you running the Tune code? is it in a separate Kubernetes pod on the same cluster? or is it from your laptop?

**Comment by bananenpampe** [comment]
I receive the same error, what can I do to avoid this error when running on one node and one GPU?

**Comment by bananenpampe** [comment]
status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (170845224 vs. 104857600)"
        debug_error_string = "{"created":"@1646086693.652770104","description":"Error received from peer ipv4:10.91.27.42:42316","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Received message larger than max (170845224 vs. 104857600)","grpc_status":8}"

**Comment by ckw017** [comment]
@bananenpampe Can you share the full traceback? The `104857600` limit looks like it comes from runtime environments, are you trying to transfer a large file through runtime a runtime env (for example, a large file in your working directory)

**Comment by bananenpampe** [comment]
Traceback (most recent call last):
  File "ray_hypers_tune.py", line 317, in <module>
    main(num_samples=100, max_num_epochs=50, gpus_per_trial=1)
  File "ray_hypers_tune.py", line 293, in main
    progress_reporter=reporter))
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/tune.py", line 453, in run
    restore=restore)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/experiment.py", line 113, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/experiment.py", line 258, in register_if_needed
    register_trainable(name, run_object)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/registry.py", line 76, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/registry.py", line 152, in register
    self.flush_values()
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/tune/registry.py", line 175, in flush_values
    _make_key(self._prefix, category, key), value, overwrite=True)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/experimental/internal_kv.py", line 79, in _internal_kv_put
    namespace) == 0
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 135, in wrapper
    return f(self, *args, **kwargs)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/ray/_private/gcs_utils.py", line 257, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/kellner/venvs/COSMO/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (170845224 vs. 104857600)"
        debug_error_string = "{"created":"@1646086693.652770104","description":"Error received from peer ipv4:10.91.27.42:42316","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Received message larger than max (170845224 vs. 104857600)","grpc_status":8}"
>

Hello, this is the full traceback.

**Comment by bananenpampe** [comment]
I think my comments are not correct. I have not correctly serialized my dataset in my code. Thank you for the effort!
However, would you recommend writing a simple get_data() function that uses ray.put() and .get() on the pytorch tensor instances I am using that contain the dataset?

**Comment by cgy-dayup** [comment]
> 
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (210771146 vs. 104857600)"
	debug_error_string = "{"created":"@1646188124.309444695","description":"Error received from peer ipv4:10.207.183.32:40455","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Received message larger than max (210771146 vs. 104857600)","grpc_status":8}"

i also come across the problem.have you sloved the problem?

**Comment by ckw017** [comment]
@cgy-dayup are you using tune as well? If there's more context to that error message that would be handy to debug (see bananenpampe's traceback above).

@xwjiang2010 Can you help triage, not too familiar with that Tune codepath, but looks like it relies on a KV put which is trying to store something larger than 100 MiB

**Comment by cgy-dayup** [comment]
> @cgy-dayup are you using tune as well? If there's more context to that error message that would be handy to debug (see bananenpampe's traceback above).
> 
> @xwjiang2010 Can you help triage, not too familiar with that Tune codepath, but looks like it relies on a KV put which is trying to store something larger than 100 MiB
yes,i use tune as well.

**Comment by cgy-dayup** [comment]
> status = StatusCode.RESOURCE_EXHAUSTED details = "Received message larger than max (170845224 vs. 104857600)" debug_error_string = "{"created":"@1646086693.652770104","description":"Error received from peer ipv4:10.91.27.42:42316","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Received message larger than max (170845224 vs. 104857600)","grpc_status":8}"

i receive the same error.Have you solved the problem?

**Comment by xwjiang2010** [comment]
@cgy-dayup can you link your script? It's probably related to transferring some big chunk of data when the training function is serialized and shipped through GCS.
Usually we recommend people using `tune.with_parameters` in such cases. Can you try it out?

**Comment by jnpm** [comment]
Hi, I have a similar error as bananenpampe using raytune. I have also tried using `tune.with_parameters` but that also did not work. My dataset is not even big (roughly 2MB). I'm using Jupyterlab on AWS Sagemaker.

```
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
Input In [20], in <module>
      3 model = BertSentiment(weight_path=pretrained_weights_path, config=bertconfig)
      4 dataloaders_dict, dataset_sizes = prepare_dataset(dataset_shuffled, 300596, configuration=configuration, tokenizer=tokenizer,
      5                                                       val_split=0.15, test_split=0.15)
----> 7 analysis = tune.run(
      8     tune.with_parameters(train_wrapper, data=dataloaders_dict),
      9     metric="highest_accuracy",
     10     mode="max",
     11     resources_per_trial={"gpu": 1},
     12     config=configuration,
     13     #callbacks=[WandbLoggerCallback()]
     14     )

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/tune.py:437, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, queue_trials, loggers, _remote)
    435 for i, exp in enumerate(experiments):
    436     if not isinstance(exp, Experiment):
--> 437         experiments[i] = Experiment(
    438             name=name,
    439             run=exp,
    440             stop=stop,
    441             time_budget_s=time_budget_s,
    442             config=config,
    443             resources_per_trial=resources_per_trial,
    444             num_samples=num_samples,
    445             local_dir=local_dir,
    446             sync_config=sync_config,
    447             trial_name_creator=trial_name_creator,
    448             trial_dirname_creator=trial_dirname_creator,
    449             log_to_file=log_to_file,
    450             checkpoint_freq=checkpoint_freq,
    451             checkpoint_at_end=checkpoint_at_end,
    452             keep_checkpoints_num=keep_checkpoints_num,
    453             checkpoint_score_attr=checkpoint_score_attr,
    454             export_formats=export_formats,
    455             max_failures=max_failures,
    456             restore=restore)
    457 else:
    458     logger.debug("Ignoring some parameters passed into tune.run.")

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/experiment.py:113, in Experiment.__init__(self, name, run, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, sync_config, trial_name_creator, trial_dirname_creator, log_to_file, checkpoint_freq, checkpoint_at_end, keep_checkpoints_num, checkpoint_score_attr, export_formats, max_failures, restore)
    108     if checkpoint_freq:
    109         raise ValueError(
    110             "'checkpoint_freq' cannot be used with a "
    111             "checkpointable function. You can specify checkpoints "
    112             "within your trainable function.")
--> 113 self._run_identifier = Experiment.register_if_needed(run)
    114 self.name = name or self._run_identifier
    116 # If the name has been set explicitly, we don't want to create
    117 # dated directories. The same is true for string run identifiers.

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/experiment.py:258, in Experiment.register_if_needed(cls, run_object)
    255     logger.warning(
    256         "No name detected on trainable. Using {}.".format(name))
    257 try:
--> 258     register_trainable(name, run_object)
    259 except (TypeError, PicklingError) as e:
    260     extra_msg = ("Other options: "
    261                  "\n-Try reproducing the issue by calling "
    262                  "`pickle.dumps(trainable)`. "
    263                  "\n-If the error is typing-related, try removing "
    264                  "the type annotations and try again.")

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/registry.py:76, in register_trainable(name, trainable, warn)
     73 if not issubclass(trainable, Trainable):
     74     raise TypeError("Second argument must be convertable to Trainable",
     75                     trainable)
---> 76 _global_registry.register(TRAINABLE_CLASS, name, trainable)

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/registry.py:152, in _Registry.register(self, category, key, value)
    150 self._to_flush[(category, key)] = pickle.dumps_debug(value)
    151 if _internal_kv_initialized():
--> 152     self.flush_values()

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/tune/registry.py:174, in _Registry.flush_values(self)
    172 def flush_values(self):
    173     for (category, key), value in self._to_flush.items():
--> 174         _internal_kv_put(
    175             _make_key(self._prefix, category, key), value, overwrite=True)
    176     self._to_flush.clear()

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/experimental/internal_kv.py:84, in _internal_kv_put(key, value, overwrite, namespace)
     81     namespace = namespace.encode()
     82 assert isinstance(key, bytes) and isinstance(value, bytes) and isinstance(
     83     overwrite, bool)
---> 84 return global_gcs_client.internal_kv_put(key, value, overwrite,
     85                                          namespace) == 0

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/_private/gcs_utils.py:144, in _auto_reconnect.<locals>.wrapper(self, *args, **kwargs)
    142 while True:
    143     try:
--> 144         return f(self, *args, **kwargs)
    145     except grpc.RpcError as e:
    146         if remaining_retry <= 0:

File ~/.conda/envs/scipy/lib/python3.9/site-packages/ray/_private/gcs_utils.py:245, in GcsClient.internal_kv_put(self, key, value, overwrite, namespace)
    242 logger.debug(f"internal_kv_put {key} {value} {overwrite} {namespace}")
    243 req = gcs_service_pb2.InternalKVPutRequest(
    244     namespace=namespace, key=key, value=value, overwrite=overwrite)
--> 245 reply = self._kv_stub.InternalKVPut(req)
    246 if reply.status.code == GcsCode.OK:
    247     return reply.added_num

File ~/.conda/envs/scipy/lib/python3.9/site-packages/grpc/_channel.py:946, in _UnaryUnaryMultiCallable.__call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    937 def __call__(self,
    938              request,
    939              timeout=None,
   (...)
    942              wait_for_ready=None,
    943              compression=None):
    944     state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                   wait_for_ready, compression)
--> 946     return _end_unary_response_blocking(state, call, False, None)

File ~/.conda/envs/scipy/lib/python3.9/site-packages/grpc/_channel.py:849, in _end_unary_response_blocking(state, call, with_call, deadline)
    847         return state.response
    848 else:
--> 849     raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (442149695 vs. 104857600)"
	debug_error_string = "{"created":"@1647296213.253399140","description":"Error received from peer ipv4:169.254.255.2:60653","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Received message larger than max (442149695 vs. 104857600)","grpc_status":8}"
>
```

**Comment by xwjiang2010** [comment]
@[jnpm](https://github.com/jnpm)
can you link me with what you supplied as trainable into `tune.run()`?

**Comment by jnpm** [comment]
@xwjiang2010

```
def train_wrapper(config):
    Dense_opt = dense_opt(model, config)
    optim = Dense_opt.get_optim()
    criterion = nn.CrossEntropyLoss()

    exp_lr_scheduler = lr_scheduler.StepLR(optim, step_size=5, gamma=0.1)

    best_accuracy, best_f1 = train_model(model, model_type, "./sb_train_outp", criterion, optim, exp_lr_scheduler, device, configuration=configuration, logging=True)
    tune.report(highest_accuracy=best_accuracy, highest_f1=best_f1)
```

The tokenizer and model is specified in the global environment.
`train_model` is the function that iterates over epochs and batches for the training and validation set and returns the highest accuracy value over all epochs.

**Comment by xwjiang2010** [comment]
@jnpm 
I think in this case, your transformer model is implicitly captured in train function, and is too big to be shipped over GCS. 
you can either try `ray.put` it directly/ `tune.with_parameters()` or just simply initialize the model in each trial from `pretrained_weights_path` and `bertconfig`.

**Comment by jnpm** [comment]
@xwjiang2010 Do you mean to put the model initialization inside the `train_wrapper` function?

**Comment by AmeerHajAli** [comment]
@ckw017 this should be closed now, correct?
