### ISSUE TITLE
[rllib] n-step learing and prioritized replay for R2D2

### ISSUE THREAD

**Issue by michaelhoyer** [ray-project/ray#18397]
### Describe your feature request

Will n-step learing and prioretized replay be added for R2D2 in a future version? Usage of both is blocked in r2d2.py.

When I try n-step learnig wich n>1 and delete the `raise ValueError("n_step > 1 not yet supported by R2D2!")` in line 112 in the r2d2.py file my code runs. Does this mean that n-step-learning is already implemented for r2d2?

**Comment by mvindiola1** [comment]
Hi @michaelhoyer,

You will get a quicker response to this question at https://discuss.ray.io

**Comment by sven1977** [comment]
Hey @michaelhoyer ,
great question. I think it's actually fine and we can remove the restriction. We do properly postprocess unrolled trajectories using the Policies' `postprocess_nstep_and_prio` methods (same a used for DQN). Also, the R2D2 loss does take `n_step` into account, when calculating the TD error. I'll PR a fix with this restriction removed.

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/18939

**Comment by sven1977** [comment]
Hey @michaelhoyer , can you try out the latest master? We have added support now for n-step to R2D2 (and RNNSAC) + switched on prio replay support for both as well as per the above PR. Closing this now.
