### ISSUE TITLE
[tune] BOHB, Ax, Dragonfly searchers are missing save and restore functionality

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#18399]
### What is the problem?

BOHB, Ax, Dragonfly searchers are missing save and restore functionality.

Followup from https://github.com/ray-project/ray/issues/18271

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by zahta** [comment]
@Yard1 and @krfricke, thank you for investigating this issue, but the problem still exists in the TuneBOHB search algorithm. No checkpoint is saved and I encountered the following warning:
2021-09-27 12:05:15,833	WARNING suggestion.py:290 -- save not implemented for Searcher. Skipping save.

I added the source code of [bohb.py](https://github.com/ray-project/ray/blob/361cae4d1c39e6300b5779d6a9ffada9df61802e/python/ray/tune/suggest/bohb.py) to my codes and then the warning disappeared but no checkpoint is still saved.
