### ISSUE TITLE
Placement groups hang because resources updates are lost under stress

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#18409]
### What is the problem?

It is something I found while I was making smaller repro of https://github.com/ray-project/ray/issues/18080 (**note that the root cause of https://github.com/ray-project/ray/issues/18080 is different**).

It seems like under stress, there's the race condition where some of resource change updates are lost from GCS -> raylet, which eventually causes placement groups to hang. This is an example;

1. pg is created
2. raylet reports new resources to GCS (currently, we don't report this using the existing resource path, but we send a separate RPC for "new resources update", which is very brittle).
3. GCS publishes new resources to all nodes
4. All nodes update resources in their local view.

It looks like when 3 happens, under stress, this updates are sometimes lost, which causes hang. For example, the node (node A) that has infeasible tasks (e.g., ready task) will never know that the placement group resource is updated in a different node (node B), then the ready task will hang forever. I could reproduce this by creating pgs with STRICT SPREAD and requires all tasks to be scheduled on each bundle. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python3
# This is stress test to run placement group.
# Please don't run it in the cluster
# setup yet. This test uses the cluster util to simulate the
# cluster environment.

import time

# from time import perf_counter
from random import random

import ray

from ray.cluster_utils import Cluster
from ray.util.placement_group import (placement_group, remove_placement_group)

# This number should be divisible by 3.
resource_quantity = 666
num_nodes = 5
custom_resources = {"pg_custom": resource_quantity}
# Create pg that uses 1 resource of cpu & custom resource.
num_pg = resource_quantity

# TODO(sang): Cluster setup. Remove when running in real clusters.
cluster = Cluster()
nodes = []
for _ in range(num_nodes):
    nodes.append(
        cluster.add_node(
            num_cpus=3, num_gpus=resource_quantity,
            resources=custom_resources))
cluster.wait_for_nodes()

ray.init(address=cluster.address)
while not ray.is_initialized():
    time.sleep(0.1)

# Scenario 1: Create bunch of placement groups and measure how long it takes.
total_creating_time = 0
total_removing_time = 0
repeat = 1
total_trial = repeat * num_pg
bundles = [{"GPU": 1, "pg_custom": 1}] * num_nodes

@ray.remote(num_cpus=0, num_gpus=1, max_calls=0)
def mock_task(i):
    time.sleep(0.1)
    # print(f"Task scheduled {i}")
    return True


@ray.remote(num_cpus=0)
def pg_launcher(pre_created_pgs, num_pgs_to_create):
    print("Creating pgs")
    pgs = []
    pgs += pre_created_pgs
    for i in range(num_pgs_to_create):
        pgs.append(placement_group(bundles, strategy="STRICT_SPREAD"))

    pgs_removed = []
    pgs_unremoved = []
    # Randomly choose placement groups to remove.
    print("removing pgs")
    for pg in pgs:
        if random() < .5:
            pgs_removed.append(pg)
        else:
            pgs_unremoved.append(pg)

    tasks = []
    # Randomly schedule tasks or actors on placement groups that
    # are not removed.
    print(f"Scheduling {len(pgs_unremoved) * num_nodes} tasks")
    for i, pg in enumerate(pgs_unremoved):
        for j in range(num_nodes):
            # NOTE: We schedule tasks on all bundles
            tasks.append(
                mock_task.options(
                    placement_group=pg,
                    placement_group_bundle_index=j).remote(i))

    # Remove the rest of placement groups.
    for pg in pgs_removed:
        remove_placement_group(pg)

    print("ready")
    i = 0
    print("pgs ready")
    ray.get(tasks)
    ray.get([actor.ping.remote() for actor in actors])
    # Since placement groups are scheduled, remove them.
    for pg in pgs_unremoved:
        remove_placement_group(pg)


pre_created_num_pgs = 0
print(f"pre created num pgs: {pre_created_num_pgs}")
num_pgs_to_create = num_pg - pre_created_num_pgs
pg_launchers = []
for i in range(3):
    pg_launchers.append(pg_launcher.remote([], num_pgs_to_create // 3))
print(f"{(num_pgs_to_create // 3) * 3} pgs will be created")
ray.get(pg_launchers)
ray.shutdown()
print("Stress Test succeed.")

```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by rkooo567** [comment]
cc @wuisawesome This is the resource report stuff I talked about. I am not sure the root cause, but my expectation is if we remove the separate RPC path and unify the resource report to the puller, it is highly likely fixed.

**Comment by rkooo567** [comment]
@clay4444 are you planning to take a look at this?

**Comment by rkooo567** [comment]
Btw, I think the ideal fix is just to remove these two RPCs;

```cpp
  NewPlacementGroupResourceManager(
      std::shared_ptr<ClusterResourceScheduler> cluster_resource_scheduler,
      std::function<
          void(const ray::gcs::NodeResourceInfoAccessor::ResourceMap &resources)>
          update_resources,
      std::function<void(const std::vector<std::string> &resource_names)>
          delete_resources);
```

`update_resources` & `delete_resources` and make them reported through the regular resource report path

**Comment by rkooo567** [comment]
That's will make this path robust and easy to debug.

**Comment by clay4444** [comment]
@rkooo567  sorry,  I didn't catch this, What do you mean by "the existing resource path"?

**Comment by clay4444** [comment]
It looks like indeed problematic,  I found I can't successfully run the `test_placement_group.py::test_actor_scheduling_not_block_with_placement_group` test case in my local laptop,  because the published msgs from GCS were lost so many.

**Comment by clay4444** [comment]
hm...  I'm a little bit confusing,  What did we do to make sure that a task (actor creation or normal task such as ready) can perceive the  PG running in another node had been created successfully in time?    @rkooo567

**Comment by rkooo567** [comment]
So, currently, we have 2 routes to update resources; 

1. Resource update path. GCS server pulls resource information from all nodes and update them (it uses lightweight heartbeat, but it seems to be broken in the master). This happens every 100ms.
2. Resource addition path; Whenever new resources are created, raylet calls `HandleUpdateResources` to update new resources. So "creating" new resources use different path than 1, when 1 should handle everything ideally (since that will simplify the code path).

For placement groups,. whenever new pgs are created, it uses the path 2. It is more likely to cause unexpected race conditions (since we have 2 concurrent RPC paths). 

The infeasible tasks are scheduled in this way; 

1. Tasks are queued on the raylet
2. It waits until new resources are updated
3. If new resources are updated, it spills tasks to nodes that have "feasible" resources.

Since GCS updates from 2 are lost in some scenarios, we fail to 3, which will make those tasks to be infeasible forever (which is reproducible from my repro)

**Comment by rkooo567** [comment]
@ericl I think we should also make this task high priority.

**Comment by ericl** [comment]
Closing as (near-duplicate) of https://github.com/ray-project/ray/issues/18080

**Comment by rkooo567** [comment]
Actually this is a separate issue from the closed one. We have passing tests now because this pattern was never tested before. I believe if we change the existing test a bit to match this, it will start hanging

**Comment by rkooo567** [comment]
@clay4444 are you taking a look at this now?

**Comment by rkooo567** [comment]
I will actually take over this task
