### ISSUE TITLE
[rllib] Unecessary GPU memory usage caused by policy initialization with GPU workers

### ISSUE THREAD

**Issue by Bam4d** [ray-project/ray#18429]
### What is the problem?

Latest version of ray, 
python 3.8
Ubuntu linux

### Loss initialization on worker nodes uses up unecessary GPU memory, even though loss is never calculated/used 

In policy.py on ALL worker nodes, `_initialize_loss_from_dummy_batch` function is used to test that the RL algorithm is set up correctly and record the view requirements for the policy.
https://github.com/ray-project/ray/blob/master/rllib/policy/policy.py#L722

In worker nodes, this calculation includes performing loss and backprop calculation for a batch of arbitrary size (used to be 200, but now is at least 32)

The problem arises when worker nodes are told to run on GPU. In this case... for *every* worker, loss is calculated on the GPU, meaning that *n* models including gradients are put on the GPU. These gradients are actually never used at all in gradient calculation... but they stay on the GPU indefinitely. 

This wastes huge amounts of GPU memory and stops additional workers from being able to run (as memory runs out).

The workers *never* actually calculate the loss, so initializing the loss is completely superflous. This makes GPU memory usage about 10-100x worse than it needs to be an severely limits the ability to use GPU workers!

### Reproduction

Start any IMPALA (or other) algorithm with workers that use GPU.

You can see that for each worker, a very large amount of memory is allocated, proportional to the `batch_divisibility_requirement` variable.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

@sven1977

**Comment by Bam4d** [comment]
Here is a branch where I have hacked around the issue to stop loss being calculated on GPUs....

Everything works the same but GPU workers use about 10x less memory

https://github.com/Bam4d/ray/tree/dummy_initialize_hack

**Comment by mvindiola1** [comment]
@Bam4d,

Nice find and fix. I think this issue would also exist for synchronous algorithms too. Do you see the memory savings for A2C as well?

**Comment by HJasperson** [comment]
Thanks for this! 

I ended up needing to go slightly further and completely bypassed the call to `_initialize_loss_from_dummy_batch` in `eager_tf_policy.py`. If you do this, you need to set `self._no_tracing = False`, and I recommend manually setting the view requirements in your model.

ray 1.11.0
python 3.9
running PPO

**Comment by gjoliver** [comment]
are you using torch? I think this is not need for torch or tf2 if you can simply set the view_requirements youself, but may be required for tf1 when we have to construct the graph with proper shapes.
