### ISSUE TITLE
`max_calls` is not a valid argument for  options()

### ISSUE THREAD

**Issue by DomagojKorais** [ray-project/ray#18430]
### What is the problem?

`max_calls` is not a valid argument for  `options() ` function, even if it is a valid argument for `remote()`.
*Ray version and other system information (Python version, TensorFlow version, OS):*
* Ray version: 1.6.0
* Python version: Python 3.7.6
* OS: Ubuntu 20.04.3 LTS

### Reproduction 
```
import ray
@ray.remote(num_cpus=2, max_calls=1)    
def remote_function(x):
    print(x)
    
ray.init()
remote_function.options(num_cpus=2,max_calls=1).remote(1)
```

Above code returns the following TypeError:
`TypeError: options() got an unexpected keyword argument 'max_calls'`

**Comment by robertnishihara** [comment]
Looks like a bug, thanks for filing this!
