### ISSUE TITLE
[C++ API/release] add sanity check

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#18462]
### Describe your feature request

Since we plan on publishing the C++ wheels with the next release, release managers should be able to test if the wheels are in a good state.

We do this for the regular wheels here: https://github.com/ray-project/ray/blob/master/release/util/sanity_check.py

How can we do this for CPP wheels?

cc @SongGuyang @jjyao @ericl

**Comment by mwtian** [comment]
One thing to note is that there are discussions of the C++ ABI we are going to build wheels with: https://github.com/ray-project/ray/pull/18273. Depending on the discussion we may want to label wheels with their ABI version, to support multiple ABI versions in future.
