### ISSUE TITLE
Unable to install ray 1.6.0 on Mac 10.14

### ISSUE THREAD

**Issue by florence-henry** [ray-project/ray#18461]
Hello,

I'm unable to install ray 1.6.0 on Mac 10.14
Here is what I get from a clean virtualenv with python 3.8

```
$ pip install  ray==1.6.0 
ERROR: Could not find a version that satisfies the requirement ray==1.6.0 (from versions: 0.8.4, 0.8.5, 0.8.6, 0.8.7, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.1.post1, 1.1.0, 1.2.0, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2)
ERROR: No matching distribution found for ray==1.6.0
```

Looking at the "Download files" section I see that the wheel file is `ray-1.6.0-cp38-cp38-macosx_10_15_x86_64.whl (52.4 MB) `. If I understantd well, only Mac >= 10.15 can install this file.

This is surprising because the nightlies for 2.0.0 are distributed with `macos_10_13`. Is this restriction intentional ?

I also tried to install without the binaries, but it also fails :
```
$ pip install  ray==1.6.0 --no-binary=ray
ERROR: Could not find a version that satisfies the requirement ray==1.6.0 (from versions: none)
ERROR: No matching distribution found for ray==1.6.0
```

How can I install version 1.6.0 on my mac ?

Thanks for your help

**Comment by istoica** [comment]
I get the same error when trying to install 1.6.0 on my Mac:

`$ pip install ray==1.6.0
ERROR: Could not find a version that satisfies the requirement ray==1.6.0 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.1.post1, 1.1.0, 1.2.0, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2)
ERROR: No matching distribution found for ray==1.6.0
`

**Comment by pcmoritz** [comment]
The problem here seems to be that the wheels require macOS 10.15, see https://pypi.org/project/ray/1.6.0/#files

(the wheels are named like ray-1.6.0-cp36-cp36m-macosx_10_15_intel.whl)

**Comment by pcmoritz** [comment]
The change was introduced in https://github.com/ray-project/ray/pull/17902

**Comment by krfricke** [comment]
Just as a general comment, the nightlies are *not* supplied as 10.13 - those are old nightlies and we will remove them from S3 soon to avoid confusion. All current wheels are 10.15 only.
