### ISSUE TITLE
[Issue template] Upgrade the issue template to issue forms.

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#18460]
### Describe your feature request

The new github issue forms looks fantastic!  Can we upgrade our issue template to issue forms?  just like this  [demo](https://github.com/clay4444/ray/issues/new?assignees=&labels=bug%2Ctriage&template=bug-report.yml&title=%5BBug%5D+), What do you think?

**Comment by richardliaw** [comment]
Great request! create a PR?

**Comment by clay4444** [comment]
> Great request! create a PR?

sure!
