### ISSUE TITLE
[Perf] Shuffle 5000 partition performance regression

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#18474]
### What is the problem?

Looks like from 4888d7c9af6a62ea5b1bedd8a56ed95529408bb4, 5000 partitions shuffle became 1k seconds slower (15 minutes). 

This is the possible root cause https://github.com/ray-project/ray/pull/18016, but it seems to rather improvement performance for smaller scale tests (1000 partitions)

We need to verify if https://github.com/ray-project/ray/pull/18016 is the root cause (and maybe we won't take further actions)

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jjyao** [comment]
No longer have this test.
