### ISSUE TITLE
many_drivers test is failing

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18482]
### What is the problem?

many_drivers test is failing consistently during nightly release test: https://buildkite.com/ray-project/periodic-ci/builds/955#321ba519-f49b-4a99-9f18-629270bbf2c9

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
Hmm are we not tracking these in the nightly dashboard? @rkooo567

**Comment by rkooo567** [comment]
We currently don't track long running tests (they have been owned by the ML team). I think it makes sense to bring this to us and start tracking it.

**Comment by ericl** [comment]
@richardliaw do you own this issue?

**Comment by jjyao** [comment]
#18251 fixed the issue.
