### ISSUE TITLE
[Java] Unable to use setResource()

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#18488]
`setResource()` is deprecated. But the API in Java is just marked as `@deprecated`. 

Many users complain about their errors:
![image](https://user-images.githubusercontent.com/19473861/132829654-db009dd1-5531-488f-bb18-14236122ea8b.png)

The issue is introduced from https://github.com/ray-project/ray/pull/12735 
It just removed the server handler and did not remove the client API, and it marked the test as disabled.

And many streaming users are suffering from this issue.

@ashione  cc

Maybe it's better to add codeowners for Java API and Java test as well.

**Comment by jovany-wang** [comment]
@ashione I believe 1.6.0 can not be used any longer. We should fix this issue ASAP and catch up the timeline of Ray 1.7.0.

**Comment by ashione** [comment]
We found a lot of users fail to set up streaming app since this interface is removed.
