### ISSUE TITLE
[RLlib nightly test] learning_test has been consistently timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18497]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
nightly release test

Sample test: https://buildkite.com/ray-project/periodic-ci/builds/959#f65046fd-c6f7-4a47-b930-f9a7af697930

Sample error:
```
Traceback (most recent call last):
--
  | File "release/e2e.py", line 1447, in _run
  | File "release/e2e.py", line 887, in wait_for_session_command_to_complete
  | File "release/e2e.py", line 402, in _check_stop
  | CommandTimeoutError: Process timed out while running a command.
  | [ERROR 2021-09-10 02:41:55,506] e2e.py: 1471  API Exception (500) from GET /api/v2/session_commands/{session_command_id}/execution_logs
  | Reason: Internal Server Error
  | HTTP response body: {"error":{"detail":"Internal Server Error"}}
  | Trace ID: ['x-trace-id', '8c7859875f568a959a7ad099ddbdea']
  | Traceback (most recent call last):
  | File "release/e2e.py", line 1447, in _run
  | File "release/e2e.py", line 887, in wait_for_session_command_to_complete
  | File "release/e2e.py", line 402, in _check_stop
  | CommandTimeoutError: Process timed out while running a command.

****
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xwjiang2010** [comment]
@sven1977

**Comment by jjyao** [comment]
learning_test passed today. https://buildkite.com/ray-project/periodic-ci/builds/1016#5828d61d-b28c-4803-89e5-70d25a910c8a
