### ISSUE TITLE
Make Ray wheels manylinux2014 compatible

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#18506]
### What is the problem?

Currently we are not running `auditwheel` on our wheels (see https://github.com/ray-project/ray/blob/4971e1394115a7a4c80f2e5b17c23df946883c4b/python/build-wheel-manylinux2014.sh#L103). It turns out they are actually not manylinux2014 compatible.

The first problem when running `auditwheel` on them is that all the binaries are in the `purelib` instead of the `platlib` folder. After unzipping the wheel, moving `purelib` to `platlib` and adapting `ray-1.6.0.dist-info/RECORD` to point to the new files, I'm getting this message from auditwheel:

```
ray-1.6.0-cp37-cp37m-linux_x86_64.whl is consistent with the
following platform tag: "manylinux_2_17_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libc.so.6 with versions
{'GLIBC_2.4', 'GLIBC_2.6', 'GLIBC_2.3.4', 'GLIBC_2.17', 'GLIBC_2.14',
'GLIBC_2.7', 'GLIBC_2.15', 'GLIBC_2.3.2', 'GLIBC_2.9', 'GLIBC_2.16',
'GLIBC_2.3', 'GLIBC_2.2.5', 'GLIBC_2.8', 'GLIBC_2.11', 'GLIBC_2.10'},
libstdc++.so.6 with versions {'GLIBCXX_3.4.18', 'CXXABI_1.3.5',
'CXXABI_1.3.7', 'GLIBCXX_3.4.14', 'GLIBCXX_3.4.19', 'GLIBCXX_3.4',
'GLIBCXX_3.4.11', 'CXXABI_1.3.3', 'CXXABI_1.3', 'CXXABI_1.3.2',
'GLIBCXX_3.4.17', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4.9'}, libgcc_s.so.1
with versions {'GCC_3.0'}, libpthread.so.0 with versions
{'GLIBC_2.2.5', 'GLIBC_2.12', 'GLIBC_2.3.3', 'GLIBC_2.3.2'}, libm.so.6
with versions {'GLIBC_2.2.5'}, librt.so.1 with versions
{'GLIBC_2.2.5'}, libdl.so.2 with versions {'GLIBC_2.2.5'}

This constrains the platform tag to "manylinux_2_17_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```

It is not clear that this is currently causing problems but it certainly has the potential to cause problems (in the past we have seen very subtle segfaults from non-conforming wheels). While the manylinux2014 standard is compatible with all older standards (manylinux1, manylinux2010), I'm not sure if this is also the case for `manylinux_2_17_x86_64`.

We should make sure our wheels have the right tags and we run `auditwheel` on them. Preferably we should produce manylinux2014 wheels.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by mwtian** [comment]
Great find. I agree either the wheels should conform to `manylinux2014`, or just be built with a newer image to comform to `manylinux_2_y`. The current situation has the disadvantage of both using an old image (past EOL) for building wheels which limits our ability for e.g. installing newer tools, and not actually compatible with older environments. cc @scv119

**Comment by duburcqa** [comment]
To be conformant with `manylinux2014`, exported dynamic libraries must depends on the following maximum versions according to [PEP599](https://www.python.org/dev/peps/pep-0599/):
```
GLIBC_2.17
CXXABI_1.3.7
GLIBCXX_3.4.19
```
which is apparently the case here, so no segfault to expect in the first place. 

From [PEP600](manylinux2014_x86_64 is now an alias for manylinux_2_17_x86_64)`manylinux2014` is preciseley an alias for `manylinux_2_17`.

**Comment by duburcqa** [comment]
Apparently it is possible to explicitly check compliance to `manylinux2014_x86_64` by doing `auditwheel repair --plat manylinux2014_x86_64 [...]` if necessary.

**Comment by scv119** [comment]
Thanks for reporting, we will look into this. Also thanks @duburcqa for the pointer, seems we might just need to run auditwheel as @duburcqa suggested.

**Comment by scv119** [comment]
@mwtian do you know the status of this one?

**Comment by mwtian** [comment]
This has been dropped for awhile .. Related questions are: whether and when should Ray move to the newer manylinux standard, and what kind of ABI should Ray guarantee. Maybe we can start a doc or REP ..

**Comment by SongGuyang** [comment]
Wish to see a REP. 😊

**Comment by jjyao** [comment]
@aslonnie @can-anyscale is this issue still relevant now?

**Comment by aslonnie** [comment]
> @aslonnie @can-anyscale is this issue still relevant now?

probably still relevant, we never really audit the wheel, and the `TODO` comment was removed by @can-anyscale (which probably should be kept):

https://github.com/ray-project/ray/pull/38415/files#diff-38e85fefc7a419849845aad70765dc1f50055cd84a65f175374cf634ef6543b1L122

which might explains the various segfaults.. as we build the wheels in manylinux, but run them in ubuntu..

**Comment by can-anyscale** [comment]
yes, likely still an issue, and the TODO is moved into ci/build/build-manylinux-wheel.sh file ;)

**Comment by poodlewars** [comment]
hi @aslonnie @can-anyscale we've been having some trouble with Ray segfaults with our project, arcticdb, since we upgraded it to C++20.

```
import ray
import arcticdb
```

segfaults, whereas,

```
import arcticdb
import ray
```

is fine.

It seems likely to us that this is a packaging / manylinux issue.

I'm curious about the remark above,

> which might explains the various segfaults

Have other projects reported issues with this?

**Comment by aslonnie** [comment]
hi

> Have other projects reported issues with this?

not recently at least.

where does it segfault at ?  what version of `ray` and `arcticdb` and platform+python environment can we reproduce this?

**Comment by jjerphan** [comment]
Hi all,

The segmentation fault can be reproduced with the PyPI wheels of `arcticdb==4.4.2` and `ray-core=2.11.0`, at least on Linux.

Investigations made by @willdealtry showed that the segmentation fault is occuring when there is a de-allocated (I let William complete the answer, as I think he explored the problem further):

<details>
<summary>Stack trace</summary>

```c
13 0x00007fdf31be1476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#14 0x00007fdf31bc77f3 in __GI_abort () at ./stdlib/abort.c:79
#15 0x00007fdf31c28676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fdf31d7ab77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#16 0x00007fdf31c3fcfc in malloc_printerr (str=str@entry=0x7fdf31d78744 "free(): invalid pointer") at ./malloc/malloc.c:5664
#17 0x00007fdf31c41a44 in _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at ./malloc/malloc.c:4439
#18 0x00007fdf31c44453 in __GI___libc_free (mem=<optimised out>) at ./malloc/malloc.c:3391
#19 0x00007fdf2f46e05c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate (this=0x559dcf5d58a0, __pos=0, __len1=<optimised out>, __len2=17)
    at /home/conda/feedstock_root/build_artifacts/gcc_compilers_1706816862910/work/libstdc++-v3/include/bits/cow_string.h:3472
#20 0x00007fdf2f46e490 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_safe (this=0x559dcf5d58a0, __pos1=0, __n1=<optimised out>, 
    __s=0x7fbce1326d02 <descriptor_table_protodef_descriptors_2eproto+2> "descriptors.proto\022\033arcticc.pb2.descriptors_pb2\"\350\003\n\016TypeDescriptor\022I\n\nvalue_type\030\001 \001(\01625.arcticc.pb2.descriptors_pb2.TypeDescriptor.ValueType\022G\n\tsize_bits\030\002 \001(\01624.arcticc.pb2.descriptors_pb2.TypeDescri"..., __n2=17)
    at /home/conda/feedstock_root/build_artifacts/gcc_compilers_1706816862910/work/libstdc++-v3/include/bits/cow_string.h:3679
#21 0x00007fbcdff795b1 in google::protobuf::internal::InlineGreedyStringParser(std::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*) () from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#22 0x00007fbcdffd598e in google::protobuf::FileDescriptorProto::_InternalParse(char const*, google::protobuf::internal::ParseContext*) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#23 0x00007fbcdff77db3 in bool google::protobuf::internal::MergeFromImpl<false>(google::protobuf::stringpiece_internal::StringPiece, google::protobuf::MessageLite*, google::protobuf::MessageLite::ParseFlags) () from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#24 0x00007fbcdffeb9df in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#25 0x00007fbcdff93b5c in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#26 0x00007fbcdfff97ef in google::protobuf::internal::AddDescriptorsRunner::AddDescriptorsRunner(google::protobuf::internal::DescriptorTable const*) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#27 0x00007fbcdfe4f0b8 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=102)
    at /opt/arcticdb/arcticdb_link/cpp/out/linux-release-build/proto/arcticc/pb2/proto/descriptors.pb.cc:989
#28 0x00007fbcdfe4f0e3 in _GLOBAL__sub_I.00102_descriptors.pb.cc(void) ()
    at /opt/arcticdb/arcticdb_link/cpp/out/linux-release-build/vcpkg_installed/x64-linux/include/google/protobuf/port_undef.inc:154
#29 0x00007fdf31ee147e in call_init (l=<optimised out>, argc=argc@entry=20, argv=argv@entry=0x7ffd56504568, env=env@entry=0x559dcd55b830) at ./elf/dl-init.c:70
#30 0x00007fdf31ee1568 in call_init (env=0x559dcd55b830, argv=0x7ffd56504568, argc=20, l=<optimised out>) at ./elf/dl-init.c:33
#31 _dl_init (main_map=0x559dcf5dc740, argc=20, argv=0x7ffd56504568, env=0x559dcd55b830) at ./elf/dl-init.c:117
#32 0x00007fdf31d13af5 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7fdf31ee8f40 <call_dl_init>, args=args@entry=0x7ffd564f9fc0)
    at ./elf/dl-error-skeleton.c:182
#33 0x00007fdf31ee8ff6 in dl_open_worker (a=0x7ffd564fa160) at ./elf/dl-open.c:808
```

</details>

The build system of ArcticDB is currently statically linking the C++ standard library within shared objects it ships in its wheels. https://github.com/man-group/ArcticDB/pull/1572 modifies the linkage so that the C++ standard library is loaded dynamically and so that the wheels comply with [the `manylinux2014` policy](https://peps.python.org/pep-0599/#the-manylinux2014-policy).

This solves the problem for me, but we need extensive testing. To me, https://github.com/man-group/ArcticDB/pull/1572 is likely a partial solution to this kind of issues. I believe we should make sure the wheels of ArcticDB and Ray comply with the `manylinux2014` policy (which was crafted to shared common libraries, preventing this kind of problem).

ArcticDB uses `auditwheels` before publishing the wheels, and Ray also must.

Note that those segmentation faults cannot be reproduced with the conda-forge package of `arcticdb` and `ray-core` thanks to the conda package model for whom common libraries are distributed as shared dependencies in dedicated packages.

**Comment by jjerphan** [comment]
Hi all,

The segmentation fault can be reproduced with the PyPI wheels of `arcticdb==4.4.2` and `ray-core=2.11.0`, at least on Linux.

Investigations made by @willdealtry showed that the segmentation fault is occuring when there is a de-allocated (I let William complete the answer, as I think he explored the problem further):

<details>
<summary>Stack trace</summary>

```c
13 0x00007fdf31be1476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#14 0x00007fdf31bc77f3 in __GI_abort () at ./stdlib/abort.c:79
#15 0x00007fdf31c28676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fdf31d7ab77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#16 0x00007fdf31c3fcfc in malloc_printerr (str=str@entry=0x7fdf31d78744 "free(): invalid pointer") at ./malloc/malloc.c:5664
#17 0x00007fdf31c41a44 in _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at ./malloc/malloc.c:4439
#18 0x00007fdf31c44453 in __GI___libc_free (mem=<optimised out>) at ./malloc/malloc.c:3391
#19 0x00007fdf2f46e05c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate (this=0x559dcf5d58a0, __pos=0, __len1=<optimised out>, __len2=17)
    at /home/conda/feedstock_root/build_artifacts/gcc_compilers_1706816862910/work/libstdc++-v3/include/bits/cow_string.h:3472
#20 0x00007fdf2f46e490 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_safe (this=0x559dcf5d58a0, __pos1=0, __n1=<optimised out>, 
    __s=0x7fbce1326d02 <descriptor_table_protodef_descriptors_2eproto+2> "descriptors.proto\022\033arcticc.pb2.descriptors_pb2\"\350\003\n\016TypeDescriptor\022I\n\nvalue_type\030\001 \001(\01625.arcticc.pb2.descriptors_pb2.TypeDescriptor.ValueType\022G\n\tsize_bits\030\002 \001(\01624.arcticc.pb2.descriptors_pb2.TypeDescri"..., __n2=17)
    at /home/conda/feedstock_root/build_artifacts/gcc_compilers_1706816862910/work/libstdc++-v3/include/bits/cow_string.h:3679
#21 0x00007fbcdff795b1 in google::protobuf::internal::InlineGreedyStringParser(std::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*) () from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#22 0x00007fbcdffd598e in google::protobuf::FileDescriptorProto::_InternalParse(char const*, google::protobuf::internal::ParseContext*) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#23 0x00007fbcdff77db3 in bool google::protobuf::internal::MergeFromImpl<false>(google::protobuf::stringpiece_internal::StringPiece, google::protobuf::MessageLite*, google::protobuf::MessageLite::ParseFlags) () from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#24 0x00007fbcdffeb9df in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#25 0x00007fbcdff93b5c in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#26 0x00007fbcdfff97ef in google::protobuf::internal::AddDescriptorsRunner::AddDescriptorsRunner(google::protobuf::internal::DescriptorTable const*) ()
   from /path/pyenvs/work/lib/python3.8/site-packages/arcticdb_ext.cpython-38-x86_64-linux-gnu.so
#27 0x00007fbcdfe4f0b8 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=102)
    at /opt/arcticdb/arcticdb_link/cpp/out/linux-release-build/proto/arcticc/pb2/proto/descriptors.pb.cc:989
#28 0x00007fbcdfe4f0e3 in _GLOBAL__sub_I.00102_descriptors.pb.cc(void) ()
    at /opt/arcticdb/arcticdb_link/cpp/out/linux-release-build/vcpkg_installed/x64-linux/include/google/protobuf/port_undef.inc:154
#29 0x00007fdf31ee147e in call_init (l=<optimised out>, argc=argc@entry=20, argv=argv@entry=0x7ffd56504568, env=env@entry=0x559dcd55b830) at ./elf/dl-init.c:70
#30 0x00007fdf31ee1568 in call_init (env=0x559dcd55b830, argv=0x7ffd56504568, argc=20, l=<optimised out>) at ./elf/dl-init.c:33
#31 _dl_init (main_map=0x559dcf5dc740, argc=20, argv=0x7ffd56504568, env=0x559dcd55b830) at ./elf/dl-init.c:117
#32 0x00007fdf31d13af5 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7fdf31ee8f40 <call_dl_init>, args=args@entry=0x7ffd564f9fc0)
    at ./elf/dl-error-skeleton.c:182
#33 0x00007fdf31ee8ff6 in dl_open_worker (a=0x7ffd564fa160) at ./elf/dl-open.c:808
```

</details>

The build system of ArcticDB is currently statically linking the C++ standard library within shared objects it ships in its wheels. https://github.com/man-group/ArcticDB/pull/1572 modifies the linkage so that the C++ standard library is loaded dynamically, making the wheels comply with [the `manylinux2014` policy](https://peps.python.org/pep-0599/#the-manylinux2014-policy).

This solves the problem for me locally, but we need extensive testing. To me, https://github.com/man-group/ArcticDB/pull/1572 is likely a partial solution to this kind of issues. I believe we should make sure the wheels of ArcticDB and Ray comply with the `manylinux2014` policy (which was crafted to share common libraries, eventually preventing this kind of problems).

ArcticDB uses `auditwheel` before publishing the wheels, and Ray also must instead of [performing custom erroneous adaptation of its wheels](https://github.com/ray-project/ray/blob/4971e1394115a7a4c80f2e5b17c23df946883c4b/python/build-wheel-manylinux2014.sh#L98-L112).

Note that those segmentation faults cannot be reproduced with the conda-forge package of `arcticdb` and `ray-core` thanks to the conda package model for whom common libraries are distributed as shared dependencies in dedicated packages.
