### ISSUE TITLE
Support scheduling_hint=SPREAD|COLOCATE for tasks and actors

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#18524]
Several use cases benefit from finer-grained control over scheduling, and cannot benefit from automatic locality-aware scheduling nor placement groups.

Proposal:
```
# The scheduler will try to spread the tasks across the cluster.
func.options(scheduling_hint="SPREAD").remote()

# The scheduler will only schedule the task on current node.
func.options(scheduling_hint="COLOCATE").remote()
```

**Data reading tasks**: These tasks have no input, but produce large amounts of output. Ideally Ray would spread these tasks across the cluster, but currently there is no way to do so. This causes data imbalance in ML ingest and Dask-on-Ray workloads. Currently Dask-on-Ray recommends a hidden scheduler flag for this: https://docs.ray.io/en/latest/data/dask-on-ray.html#best-practice-for-large-scale-workloads

This is also a blocker for scalable ML ingest without the "resource prefix" hack, since large datasets cause memory imbalance across the cluster without spreading.

**Helper tasks relying on local resources**: Suppose a task a file locally, but wants to launch sub-tasks for parallelism. There is no current way to do this except by relying on hacky node id resources. Another example is the driver forking a "main" task on the head node for easy debugging.

Related issues: https://github.com/ray-project/ray/issues/18465, https://github.com/ray-project/ray/issues/5722

**Comment by valiantljk** [comment]
For colocate, does this api allow users to colocate any two+ tasks easily?

I think we also have this requirement, so far we just hacked with node id as customized res. 

Good to see this proposal!

**Comment by ericl** [comment]
In the above proposal, you could force colocation of two tasks if the second task is launched by the first task. If the two tasks are launched independently you can already force colocation using a placement group, hope this helps.

**Comment by simon-mo** [comment]
This would also generalize to actors placement right?

**Comment by ericl** [comment]
Yes, we could support it for both tasks and actors, though the implementation may differ slightly for actors.

**Comment by mwtian** [comment]
For `scheduling_hint="SPREAD"`, do we envision "spread" tasks and actors get launched together or separately, e.g. 100 tasks each launching another, or a single task launching 100 other tasks?

**Comment by ericl** [comment]
For the Datasets use case they're all launched together (by the driver). I think we'd want the hint to work well in both scenarios, are there some implications per scenario you're thinking of?

**Comment by mwtian** [comment]
For the `spread` hint, it seems we would need a higher level collection abstraction to spread tasks within, or an identifier where tasks / actors with the same identifier value are spread out. The second approach seems to work for both scenarios of launching. Maybe there are more elegant approaches. I'm curious to see what the final API we decide to have.

**Comment by robertnishihara** [comment]
COLOCATE seems to force colocation, whereas "hint" sounds like a best effort thing.

**Comment by raulchen** [comment]
```python
func.options(scheduling_hint="SPREAD").remote()
```
I'm confused about the semantic of this. Does this mean that `func` will be scheduled to a node that is different from the current node? 
If I submit 5 tasks with `scheduling_hint="SPREAD"`. What happens to them? Are those 5 tasks independent or will they be spread?

**Comment by ericl** [comment]
> If I submit 5 tasks with scheduling_hint="SPREAD". What happens to them? Are those 5 tasks independent or will they be spread?

The scheduler will do its best to spread them equally across different nodes, similar to SPREAD in placement groups. No guarantees though.

**Comment by clay4444** [comment]
> > If I submit 5 tasks with scheduling_hint="SPREAD". What happens to them? Are those 5 tasks independent or will they be spread?
> 
> The scheduler will do its best to spread them equally across different nodes, similar to SPREAD in placement groups. No guarantees though. They are independent.

hmm... It sounds like SOFT SPREAD in placement group but without Gang Scheduler?

**Comment by jjyao** [comment]
@clay4444 Yea, behave similar to soft spread in placement group.
