### ISSUE TITLE
[nightly-test] many_nodes_actor_test is broken

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18528]
Last two many_node_actor_test failed without infra failure: [[1](https://buildkite.com/ray-project/periodic-ci/builds/962#218702ed-aff2-4efb-88c9-f323f74e772a)][[2](https://buildkite.com/ray-project/periodic-ci/builds/965#9777f227-ca42-4517-8833-f00474313896)]

The first known [broken](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_PrExYMKYjYwPcuA4pW1mpH8Q?command-history-section=command_history) commit is 1587eb22f030047469dee0a211de9072392fe9ae
Last known [unbroken](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/app-config-details/bld_SAnSpemXSzKsa1n19ESMdEqn) commit is 688dbeb4c

**Comment by ericl** [comment]
Looking at the broken commit test log, shouldn't this count as a real failure and not infra failure?

**Comment by ericl** [comment]
The only two commits that look suspicious to me from `git log 688dbeb..1587eb2` are:

```
commit 2fcfea10b3604d61c6fe664b9360043f1b55de3b
Author: Edward Oakes <ed.nmi.oakes@gmail.com>
Date:   Fri Sep 10 02:13:32 2021 -0500

    [runtime_env] Move URI deletion logic to the agent, remove util worker code (#18471)

commit 7b2ed4c1f8bd0cb076725ec3d64ad7c2cd331485
Author: SangBin Cho <rkooo567@gmail.com>
Date:   Thu Sep 9 20:39:01 2021 -0700

    [Placement group] Placement group scheduling hangs due to creation/removal race condition (#18419)
```

**Comment by scv119** [comment]
2fcfea10b3604d61c6fe664b9360043f1b55de3b looks broken:  https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/app-config-details/bld_d9YLbnyS2ZNLWqJjsiAWgnf8

**Comment by ericl** [comment]
Shall we try reverting it?

**Comment by scv119** [comment]
let me double check if its parent commit pass the test.

**Comment by scv119** [comment]
alright parent commit f2d8f23fb640218adb336d3b7da5e4d08c225cac passed the test https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Vpky45WfR7jR8zdAjsPv4uU2?command-history-section=command_history

**Comment by iycheng** [comment]
There are two issues there:

- node is marked dead. I've increased GCS thread number
- infra error: fail to acquire 500 nodes. I'll try to reduce it to 400 for now.

**Comment by iycheng** [comment]
Increase the thread to 8
```
  actor_launch_time = 179.710744493
  actor_ready_time = 14.067243351000116
  total_time = 193.7779878440001
  num_actors = 10000
  success = 1
  _runtime = 206.03042674064636
  _session_url = https://beta.anyscale.com/o/anyscale-internal/projects/prj_LFKjNprpiYt4AjAf1NdLDJwn/clusters/ses_5ccZB2Z97L7eiJiqNd2idYBj
  _commit_url = https://s3-us-west-2.amazonaws.com/ray-wheels/master/dee12be25386415a6b5a858fdb605a3457e90f66/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  _stable = True
```
I'll create one PR for this.
