### ISSUE TITLE
miss clip_rewards for ApeX optimizer

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#1852]
https://github.com/ray-project/ray/blob/0b7ad668ff83b618eeb234b33ba019b27184e544/python/ray/rllib/dqn/dqn.py#L18

I think in /dqn/dqn.py, OPTIMIZER_SHARED_CONFIGS must include "clip_rewards", as ApeX optimizer receives this argument in its _init function.

**Comment by joneswong** [comment]
of course, I will do that accordingly.

**Comment by joneswong** [comment]
Hi eric,
    I have submitted a pr as https://github.com/ray-project/ray/pull/1853
    I am not familiar with the procedure of making contributions to
opensource project. Any issue, plz tell me. I will edit the pr accordingly.
    best
    Zhen Wang
​

**Comment by ericl** [comment]
Looks food! I will merge it once tests pass.

**Comment by ericl** [comment]
Merged, thanks!
