### ISSUE TITLE
[rllib] running compact regression finishes with no module named 'tblib'

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18531]
When I run `rllib train -f compact-regression-test.yaml` I get the following error after the application finishes and all trials are Terminated/Errored:

```
Traceback (most recent call last):
  File "/Users/ameerhajali/anaconda3/envs/ray/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/rllib/train.py", line 257, in run
    concurrent=True)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/tune/tune.py", line 692, in run_experiments
    _remote=False))
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 88, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/api.py", line 42, in get
    return self.worker.get(vals, timeout=timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 339, in get
    res = self._get(to_get, op_timeout)
  File "/Users/ameerhajali/anaconda3/envs/ray/lib/python3.7/site-packages/ray/util/client/worker.py", line 362, in _get
    err = cloudpickle.loads(data.error)
ModuleNotFoundError: No module named 'tblib'
```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by gjoliver** [comment]
This seems like something in ray client, and not RL specific?
it's a pickle related library.

**Comment by AmeerHajAli** [comment]
Do you know if this is just some missing dependency on my laptop or the cluster?

**Comment by AmeerHajAli** [comment]
Should tblib be in the ray-ml docker images?

**Comment by gjoliver** [comment]
Probably. Let me take another soon. Maybe this is a recent change.

**Comment by sven1977** [comment]
This is a strange one, I have never seen this package as missing. The job runs fine for me. Just tried it on a g3s.xlarge with an `anyscale/ray-ml:1.6.0-py38-gpu` container:

![image](https://user-images.githubusercontent.com/5839854/133053583-8ccfaa3e-2078-4641-999a-bbf45c9dea2c.png)

**Comment by AmeerHajAli** [comment]
are you running it with ray client? It might be missing on your laptop maybe? Did you wait until the job finishes?

**Comment by gjoliver** [comment]
it seems tblib allows you to pickle stack traces, and raise them on a different machine.
so you won't need tblib if there is no error in the first place.
if you look at Ameer's error stack trace, the actual problem is:

cloudpickle.loads(data.error)

so our client is trying to raise the error it just received, and couldn't find tblib which is used by cloudpickle.
in summary, I think there is an error in the rl stack, but we don't know what that is, because the error is not raised.
and Ameer's laptop seems to be missing tblib, otherwise we would have seen the actual error.

does this make sense?

**Comment by gjoliver** [comment]
Not a rllib specific issue. Closing.

**Comment by garymm** [comment]
I just hit this again trying to run something using rllib on a worker running an official ray-ml container. It's very annoying. Shall I re-open, or can someone open a new issue that is more accurate?
