### ISSUE TITLE
[core] Ray async actor worker process leak

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18533]
### What is the problem?
```
ray) jjyao@Jiajuns-MacBook-Pro:~/Workspace/ray1/python jjyao/refactor$ python leak.py 
2021-09-12 19:56:31,759	INFO services.py:1250 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "leak2.py", line 22, in <module>
    ray.get(a.exit.remote())
  File "/Users/jjyao/Workspace/ray1/python/ray/_private/client_mode_hook.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/Users/jjyao/Workspace/ray1/python/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
(ray) jjyao@Jiajuns-MacBook-Pro:~/Workspace/ray1/python jjyao/refactor$ ps aux | grep ray
jjyao            23584  98.1  0.1 19230904  77952 s007  R     7:56PM   0:06.27 ray::Actor            
jjyao            23610   0.0  0.0  4408696    844 s007  S+    7:56PM   0:00.00 grep ray
```
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
```
import asyncio
import ray
ray.init()

@ray.remote
class Actor:
    async def exit(self):
        ray.actor.exit_actor()

    async def loop_forever(self):
        while True:
            await asyncio.sleep(5)

a = Actor.remote()
a.loop_forever.remote()
ray.get(a.exit.remote())
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by jjyao** [comment]
The issue is that we cannot join fiber_runner_thread_ during shutdown since one of the detached fiber (for loop_forever) is still running. The fix can be just cancelling the loop_forever fiber so the thread can exit. The question is should we even try to run `exit_actor` in the first place given the document says that
```
Note that this method of termination will wait until any previously submitted tasks finish executing and then exit the process gracefully with sys.exit.
```
@ericl @rkooo567 @simon-mo  what's your thought?

**Comment by simon-mo** [comment]
`exit_actor` should gracefully exit the actor almost immediately. The only cleanup is there to drain any references or shutdown rpc channels. It shouldn't wait for tasks to finish. I think there isn't a native way to wait for shutdown with all the tasks finishes. (from the caller side, there's a difference between `actor.__ray_terminate__.remote()` and `ray.kill(actor)`)

> The fix can be just cancelling the loop_forever fiber so the thread can exit. 
This sounds good to me.

**Comment by ericl** [comment]
I think we should deprecate the exit actor API. The user can just use
exit() or os._exit() instead.

Why did we add this API in the first place?

**Comment by simon-mo** [comment]
os exit doesn’t exit the whole process when it’s called from a thread
(in threaded actors and asyncio actor). In fact, it won’t even rethrow
the SystemExit back to main thread.

**Comment by ericl** [comment]
What about _exit()?

**Comment by simon-mo** [comment]
https://stackoverflow.com/questions/1489669/how-to-exit-the-entire-application-from-a-python-thread

Looks like `os._exit` should work.

**Comment by jjyao** [comment]
Initially I thought the difference between `exit_actor()` and `_exit()` was that `exit_actor()` waits for previously submitted tasks to finish and it is **intentional** exit in the codebase. Do we still want the concept of `IntentionalSystemExit` vs `UnexpectedSystemExit`?

**Comment by ericl** [comment]
Got it. Then, I agree we should try to resolve this issue.

However, it is a bit strange the process is leaked even after the parent script exits. I would expect child processes to get killed even if they are hung.

**Comment by jjyao** [comment]
My understanding is that we are already in the process of shutting down and we have disconnected/unregistered from raylet/gcs. So basically no one knows the existence of this actor process, that's probably why `ray stop` also doesn't help here.

**Comment by simon-mo** [comment]
Actually i think it's not waiting for submitted tasks to finish, rather to wait for submitted tasks to finish _submitting_ and then just exit.

**Comment by jjyao** [comment]
Then we need to change the documentation (I can do it as part of this task). Why do we want to wait for submitted tasks to finish submitting?

**Comment by ericl** [comment]
Duplicates above
