### ISSUE TITLE
[rllib] Should we calculate `prev_action_dist` using target model with appo?

### ISSUE THREAD

**Issue by yangysc** [ray-project/ray#18548]
Should we calculate `prev_action_dist` using target model with appo? Why do we use behaviour model here?

https://github.com/ray-project/ray/blob/ac0a153b0628ca0a1ef3d47da15aa5643c6e61b5/rllib/agents/ppo/appo_torch_policy.py#L83

Please correct me if I was wrong, and feel free to delete it.

**Comment by scv119** [comment]
cc @xwjiang2010
