### ISSUE TITLE
modin_xgboost_test timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18553]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
nightly release

https://buildkite.com/ray-project/periodic-ci/builds/966#192a4ec4-b6b3-4384-a6b1-939d90c822ef

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by xwjiang2010** [comment]
@Yard1 Anotoni, can you take a look? The cluster seems to be up and running tho: https://beta.anyscale.com/o/anyscale-internal/jobs/job_E7W2ai97cyTZ1V1pwwJh7zvf

**Comment by richardliaw** [comment]
Nice work here! Thanks for moving fast on this :)
