### ISSUE TITLE
Getting pytorch model weights on cuda device gives no dimension tensors

### ISSUE THREAD

**Issue by JunhongXu** [ray-project/ray#1856]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:
Binary
- **Ray version**:
0.4.0
- **Python version**:
3.6
- **Exact command to reproduce**:

### Describe the problem

I am trying to write a pytorch version of PPO in Ray. When I implement ```get_weights() and set_weights()``` method, I got this warning and the weight tensors I got from remote does not have any element (The problem only exists when the tensors are on GPUs.):

> WARNING: Serializing objects of type <class 'torch.cuda.FloatTensor'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
 

### Source code / logs

The code I used: 

```

class TorchPPOAgent(Agent):

    def _init(self):
        self.local_evaluator = TorchPPOEvaluator(env_creator=self.env_creator, config=self.config)

        RemoteEvaluators = ray.remote(**self.config['worker_resources'])(TorchPPOEvaluator)
        self.remote_evaluators = []
        for _ in range(self.config['num_workers']):
            self.remote_evaluators.append(RemoteEvaluators.remote(self.config, self.env_creator))
		# other initialization stuff ...
	
	...

    def _train(self):
        local_model = self.local_evaluator
        remote_models = self.remote_evaluators

        # sync parameters
        weight_id = ray.put(local_model.get_weights())

 		# the tensors in this state dict are torch.cuda.FloatTensor with no dimensions
		print(ray.get(weight_id))	


	
class TorchPPOEvaluator(PolicyEvaluator):

    def __init__(self, config, env_creator):
		# ... initialization stuff ...
		if self.config['cuda']:
        	self.net.cuda()
	
	# set weights and get weights function
    def set_weights(self, weights):
		# if I first transfer the GPU tensors to CPU, it works fine.
        # if self.config['cuda']:
        #     for weight in weights:
        #         weights[weight] = weights[weight].cuda()
        self.net.load_state_dict(weights)

    def get_weights(self):
        state_dict = self.net.state_dict()
		# if I first transfer the GPU tensors to CPU, it works fine.
        # if self.config['cuda']:
        #     for key in state_dict:
        #         state_dict[key] = state_dict[key].cpu()
        return state_dict

```

**Comment by richardliaw** [comment]
@robertnishihara @pcmoritz  do you know how the serialization library currently interacts with PyTorch tensors?

**Comment by robertnishihara** [comment]
Hi @JunhongXu,  we are using a custom serializer for regular (non-cuda) pytorch tensors defined at https://github.com/apache/arrow/blob/1ee7d11f562210474921ba07f591fd2df800c757/python/pyarrow/serialization.py#L102-L124.

Can you try defining a custom serializer, e.g.,

```python
import ray
import torch

ray.init()

x = torch.cuda.FloatTensor(5, 5).random_()

def serializer(obj):
    return obj.cpu().numpy()

def deserializer(serialized_obj):
    return torch.from_numpy(serialized_obj).cuda()

ray.register_custom_serializer(torch.cuda.FloatTensor, serializer=serializer, deserializer=deserializer)

# Now the following should work!
x_id = ray.put(x)
y = ray.get(x_id)
```

If that works for you then we should probably make that the default in pyarrow.

Note that this unfortunately goes through CPU memory.. we're slowly working on GPU support for the object store, but it isn't ready yet.

**Comment by JunhongXu** [comment]
@robertnishihara, thank you! This worked perfectly. I have also tried serialize pytorch tensor directly and it also worked too:

```python
def serializer(obj):
    return obj.cpu()

def deserializer(serialized_obj):
    return serialized_obj.cuda()
```

**Comment by robertnishihara** [comment]
Oh that approach is cleaner, thanks!

**Comment by activatedgeek** [comment]
I was trying to convert some existing RL code to be parallelized via Ray and it looks like it cannot serialize some PyTorch backend class. Further, it looks from this discussion that GPU is not supported yet. 

However, I am curious, how would the implementation of GPU (de)serialization look like? On a high level would it involve a hardware specific implementation of something like a `GPUObjectID`? I also wanted to clarify that are `ObjectID`s just keys to the serialized version of Python(ic) objects in the Redis Store?

**Comment by robertnishihara** [comment]
You can enable Ray to work with GPU backed tensors by defining the  custom serializers above (assuming you're ok with an extra copy to CPU memory).

`ObjectID`s are just keys to serialized Python objects in the **Plasma object store**. Redis is used for metadata (e.g., task specifications and object locations), whereas Plasma is used for data https://arrow.apache.org/blog/2017/08/08/plasma-in-memory-object-store/.

We're working on supporting GPU backed buffers in Plasma, but that is a work in progress.

**Comment by activatedgeek** [comment]
Got it! Thanks!

**Comment by valiantljk** [comment]
I have arbitrary python class, it looks like using Plasma, it requires me to write all the custom serializer and deserializer for those classes, is there any easier way?

**Comment by robertnishihara** [comment]
@valiantljk you may want to create a separate issue for this. Can you post the error messages you see? Does `cloudpickle` correctly serialize/deserialize the object?

**Comment by thiagocrepaldi** [comment]
> 
> 
> You can enable Ray to work with GPU backed tensors by defining the custom serializers above (assuming you're ok with an extra copy to CPU memory).
> 
> `ObjectID`s are just keys to serialized Python objects in the **Plasma object store**. Redis is used for metadata (e.g., task specifications and object locations), whereas Plasma is used for data https://arrow.apache.org/blog/2017/08/08/plasma-in-memory-object-store/.
> 
> We're working on supporting GPU backed buffers in Plasma, but that is a work in progress.

Is there any update on supporting GPU backed buffers in Plasma *without* doing an extra copy to CPU?

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
