### ISSUE TITLE
[RFC] Policy and Mechanism For Externally Downscaling a Ray Cluster

### ISSUE THREAD

**Issue by asm582** [ray-project/ray#18576]
### Describe your feature request

Users on the empty ray cluster may initially launch an elastic machine learning pipeline that takes all the resources of a fixed kubernetes cluster. User pipelines may have multiple stages and each stage may demand different resource requirements. While the current ray autoscaler terminates ray workers based upon idleness, we want to downscale independent of resources used in any stage of pipeline execution. A typical use case would be that the user decides to start another job. Currently, the user has the capability to do this with a helm; this may not be graceful enough for workloads consisting of ray worker nodes running actors as well as tasks. User changes made to helm configuration evicts ray workers without any knowledge about actors/tasks scheduled on the workers. 

This proposal is to remove ray nodes by condoning i.e. avoid scheduling new tasks on nodes that are marked for removal.

For more details, please refer to the proposal here:

https://docs.google.com/document/d/1K80ZZ7Ee5DE7KAjND3g0iYUTUfJTMRRE6-CONGeQnmc/edit

CC @wuisawesome @DmitriGekhtman @asyoussef

**Comment by DmitriGekhtman** [comment]
Let's reopen and take another look at the linked docs.

**Comment by wuisawesome** [comment]
beep bop boop
