### ISSUE TITLE
[tune]: OptunaSearch define-by-run space incompatible with evaluated_rewards

### ISSUE THREAD

**Issue by ccssmnn** [ray-project/ray#18587]
### What is the problem?

I'm using Ray Tune for running hyperparameter optimization using OptunaSearch as a search algorithm. There are many options to configure the algorithm. Especially, there is a variety of different ways to describe the search space. When using the define-by-run way, it is not possible to provide evaluated_rewards.

```
Traceback (most recent call last):
  File "tune.py", line 20, in <module>
    algo = OptunaSearch(
  File ".../.venv/lib/python3.8/site-packages/ray/tune/suggest/optuna.py", line 243, in __init__
    self._setup_study(mode)
  File ".../.venv/lib/python3.8/site-packages/ray/tune/suggest/optuna.py", line 270, in _setup_study
    self.add_evaluated_point(point, reward)
  File ".../.venv/lib/python3.8/site-packages/ray/tune/suggest/optuna.py", line 419, in add_evaluated_point
    trial = ot.trial.create_trial(
  File ".../.venv/lib/python3.8/site-packages/optuna/_experimental.py", line 68, in new_func
    return func(*args, **kwargs)  # type: ignore
  File ".../.venv/lib/python3.8/site-packages/optuna/trial/_frozen.py", line 618, in create_trial
    trial._validate()
  File ".../.venv/lib/python3.8/site-packages/optuna/trial/_frozen.py", line 337, in _validate
    if set(self.params.keys()) != set(self.distributions.keys()):
AttributeError: 'function' object has no attribute 'keys'
```

The reason is that Optuna's interface expects a distribution (dict), when creating a trial. But the OptunaSearch class passes its own search space, which in this case is a callable. Optuna's validation fails. I guess right now the user must provide a distribution dict when using evaluated_rewards.

I would be happy to open a PR to:
- raise an exception explaining the incompatibilities before calling optuna
- add a hint for this issue in the docs
- add working examples to the docs

Ray 1.6.0
Optuna 2.9.1
Python 3.8.10

### Reproduction (REQUIRED)

```python
import optuna
from ray import tune
from ray.tune.suggest.optuna import OptunaSearch


def objective(x):
    return (x - 2)**2


def trainable(config):
    x = config["x"]
    loss = objective(x)
    tune.report(objective_value=loss)


points = [{"x": 4.0}, {"x": 1.0}]

rewards = [objective(config["x"]) for config in points]

algo = OptunaSearch(
    # WORKS
    # space={"x": optuna.distributions.UniformDistribution(-10, 10)},
    # FAILS
    space=lambda trial: {"x": trial.suggest_float("x", -10, 10)},
    metric="objective_value",
    mode="min",
    points_to_evaluate=points,
    evaluated_rewards=rewards,
)

algo = tune.suggest.ConcurrencyLimiter(algo, max_concurrent=1)

analysis = tune.run(
    trainable,
    metric="objective_value",
    mode="min",
    search_alg=algo,
    num_samples=10,
)

best = analysis.get_best_config("objective_value", "min")

print(best)
```

It is worth mentioning, that the above script works fine with define-by-run when no evaluated_rewards is passed to OptunaSearch.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by Yard1** [comment]
Thanks for catching this! A PR would be appreciated. I just want to quickly take a look if it's possible to provide this functionality somehow.

**Comment by Yard1** [comment]
Yeah, I think it's fine to just make it clear to the user that this functionality is not (yet) supported with define-by-run. Thanks!
