### ISSUE TITLE
[core][scheduler] Data locality scheduling doesn't always work with distributed scheduler policy

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#18581]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 2.0dev

Locality aware leasing works by choosing a node that has the most arguments local for a task. However, this can interact poorly with the scheduler spreading threshold, which forces tasks to other nodes if the local resource utilization is higher than a certain threshold. So we can end up in a situation like this:

1. Object A created on node N, which puts node N's object store memory usage over the threshold (default 50%).
2. Driver submits task T that depends on A, sends to node N because A is local there.
3. Node N sees that head node has CPU and object store memory available, so it sends it back to the head node.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

TODO: Add example.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by ericl** [comment]
What if we made data locality take precedence over the default spread threshold? Suppose we also have an explicit SPREAD hint in the future. Then the priority of these scheduling heuristics would be:
1. Explicit scheduling hints (highest)
2. Locality-based decision
3. Default spread threshold (lowest)

cc @clarkzinzow

**Comment by stephanie-wang** [comment]
Yes in general, I think we need to allow the spread threshold to be specified individually for tasks instead of globally in the system. For tasks that have locality, we can override the default spread threshold.

**Comment by jjyao** [comment]
Redo #20026 after this issue is fixed.
