### ISSUE TITLE
Zip two datasets together

### ISSUE THREAD

**Issue by linyiyue** [ray-project/ray#18580]
### Describe your feature request
We have two dataset in the ObjectStore, 
dataset1 = Dataset(num_bcloks=10, num_rows=100, schema={id: Int64, feat_1:double,feat_2:Int64, feat_3:Double)
dataset2 = Dataset(num_bcloks=10, num_rows=100, schema={id: Int64, score_1:double,score_2:Int64, score_3:Int64)
Id is a one-to-one correspondence in the two dataset，We want a new dataset with schema={id:Int64, feat_1:double,score_1:double}，Is there any related,API that can achieve this funcation。
![image](https://user-images.githubusercontent.com/65530090/133183184-0407f16f-0fd5-43a8-abb1-1ed4039346a0.png)

For questions, post on our Discussion page instead: https://discuss.ray.io/

**Comment by scv119** [comment]
cc @clarkzinzow do you know if this is something we are planning to support in the near future?

**Comment by ericl** [comment]
It sounds like you want to zip() together two datasets of the same size, is that correct? This should be pretty easy to implement.

The more general case is join() on the id, which would require a shuffle.
