### ISSUE TITLE
Ray on AWS Fargate/ECS?

### ISSUE THREAD

**Issue by dirtyValera** [ray-project/ray#18599]
Went through cloud deployment docs but haven't found anything on how to run Ray on AWS Fargate.

My usecase is burstable data science tasks which require high number of workers available on demand, while most of the time they stay idle. Example is FargateCluster in Dask with enabled adaptive scaling.

Since Ray supports Dask, is it possible to put it on Fargate somehow?

**Comment by MarvinSt** [comment]
interested to know about this possibility as well!

**Comment by varshithvvs** [comment]
Any update on ray support for was fargate??
