### ISSUE TITLE
Exception: Ray exceeded the maximum number of classes that it will recursively serialize when attempting to serialize an object of type <class 'ray.rllib.optimizers.sample_batch.SampleBatch'>.

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#1859]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.4.0 
- **Python version**: 3.6.3
- **Exact command to reproduce**: N/A

### Describe the problem
Running a script on an AWS m4.16xlarge machine, I encounter the below error when trying to use 60 workers, but not when using 30 or 40. 

### Source code / logs
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.worker.RayTaskError'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Traceback (most recent call last):
  File "/home/ubuntu/ray/python/ray/worker.py", line 841, in _process_task
    self._store_outputs_in_objstore(return_object_ids, outputs)
  File "/home/ubuntu/ray/python/ray/worker.py", line 768, in _store_outputs_in_objstore
    self.put_object(object_ids[i], outputs[i])
  File "/home/ubuntu/ray/python/ray/worker.py", line 372, in put_object
    self.store_and_register(object_id, value)
  File "/home/ubuntu/ray/python/ray/worker.py", line 295, in store_and_register
    "type {}.".format(type(value)))
Exception: Ray exceeded the maximum number of classes that it will recursively serialize when attempting to serialize an object of type <class 'ray.rllib.optimizers.sample_batch.SampleBatch'>.

**Comment by richardliaw** [comment]
this is odd; do you know what part of the code does this?

**Comment by eugenevinitsky** [comment]
Will rerun and give you the total traceback, should be more helpful

**Comment by Scitator** [comment]
@richardliaw @eugenevinitsky 

just got the same error message with Apex DDPG example. Does anybody know any solutions?

**Comment by robertnishihara** [comment]
Hm, you could always register a custom serializer, e.g.,

```python
class Foo(object):
    def __init__(self):
        self.x = 3

def custom_serializer(obj):
    return pickle.dumps(obj)

def custom_deserializer(serialized_obj):
    return pickle.loads(serialized_obj)

ray.register_custom_serializer(
    Foo,
    serializer=custom_serializer,
    deserializer=custom_deserializer)
```

Actually, if you want to use cloudpickle, you can just use the shorthand.

```python
ray.register_custom_serializer(Foo, use_pickle=True)
```

**Comment by ericl** [comment]
Closing stale issue -- feel free to re-open if you're still seeing this.
