### ISSUE TITLE
Tune does not detect autoscaling 

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#18608]
if ~/ray_bootstrap_config.yaml is not available on the cluster Tune throws the following error:
```
Traceback (most recent call last):
  File "tft_rllib.py", line 530, in <module>
    app.run(main)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "tft_rllib.py", line 521, in main
    verbose=1,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 585, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 627, in step
    self._run_and_catch(self.trial_executor.on_no_available_trials)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 394, in _run_and_catch
    func(self.get_trials())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_executor.py", line 321, in on_no_available_trials
    self._may_warn_insufficient_resources(trials)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_executor.py", line 302, in _may_warn_insufficient_resources
    _get_insufficient_resources_error_msg(trial))
ray.tune.error.TuneError: You asked for 75.0 cpu and 1.0 gpu per trial, but the cluster only has 12.0 cpu and 1.0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
```

### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by DmitriGekhtman** [comment]
At risk of repeating a thing we've already established, checking for`~/ray_bootstrap_config.yaml` on the head node isn't a reliable way of determining if a cluster is autoscaling.

**Comment by richardliaw** [comment]
What I really need is just a way to detect whether we have autoscaling enabled. 

This should provide it https://github.com/ray-project/ray/issues/15933, but it is P1.

As a workaround, I would propose having an escape hatch for disabling the error (i.e., just include the env var workaround `TUNE_WARN_INSUFFICENT_RESOURCE_THRESHOLD_S` in the warning message).

For context, currently, we do the following:

1. OSS, laptop/manual cluster: raise error
2. OSS, autoscaling (with yaml): warn
3. OSS, on k8s operator: raise error.
4. product: raise error.

Where we want to be is:

1. all setups that do not have autoscaling capacity: error.
2. all clusters that have autoscaling capacity: warn.

For now, maybe we can just always warn.

cc @xwjiang2010

**Comment by AmeerHajAli** [comment]
> What I really need is just a way to detect whether we have autoscaling enabled.
> 
> This should provide it #15933, but it is P1.
> 
> As a workaround, I would propose having an escape hatch for disabling the error (i.e., just include the env var workaround `TUNE_WARN_INSUFFICENT_RESOURCE_THRESHOLD_S` in the warning message).
> 
> For context, currently, we do the following:
> 
> 1. OSS, laptop/manual cluster: raise error
> 2. OSS, autoscaling (with yaml): warn
> 3. OSS, on k8s operator: raise error.
> 4. product: raise error.
> 
> Where we want to be is:
> 
> 1. all setups that do not have autoscaling capacity: error.
> 2. all clusters that have autoscaling capacity: warn.
> 
> For now, maybe we can just **always warn**.
> 
> cc @xwjiang2010

@ijrsvt any thoughts on this?

**Comment by AmeerHajAli** [comment]
@richardliaw , this warning will be misleading in the product:
```
You asked for 75.0 cpu and 1.0 gpu per trial, but the cluster only has 12.0 cpu and 1.0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
```

**Comment by xwjiang2010** [comment]
@AmeerHajAli @richardliaw 
Ameer is ok with prepending this message with "If autoscaler is still scaling up, ignore this message. "

The only downside is for OSS user not using autoscaler, this seems a little confusing. But since we don't have the API to detect autoscaler, this is the best we can do. 
If everybody is good with this proposal, I will go ahead and make the PR.

**Comment by richardliaw** [comment]
OK that's fine.
