### ISSUE TITLE
Compile error on latest macOS

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1861]
MacOS 10.13.4, XCode 9.3:

```
In file included from /Users/pcmoritz/ray/src/ray/id.cc:1:
In file included from /Users/pcmoritz/ray/src/ray/id.h:4:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/inttypes.h:247:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/inttypes.h:30:15: fatal error: 'inttypes.h' file not found
#include_next <inttypes.h>
              ^~~~~~~~~~~~
1 error generated.
```

**Comment by pcmoritz** [comment]
Actually, this looks like a problem with my XCode installation, since other include files are also not found.

**Comment by TheHolyRoger** [comment]
@pcmoritz did you resolve this?

**Comment by pcmoritz** [comment]
Yeah, it went away after re-installing/upgrading XCode.

**Comment by TheHolyRoger** [comment]
Thanks! Mine unfortunately didn't, going to try on Ubuntu instead. Bloody Macs

**Comment by TheHolyRoger** [comment]
I ended up fixing it on my mac by symlinking the include files into the android studio mac sdk folder, not pretty but it works...

**Comment by AgoraBeck** [comment]
Maybe,  set CFLAGS wrong. 

The following works for me . 
CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk  -Wall      -O3
