### ISSUE TITLE
Skip running virtual actor step inside a workflow if have runned

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#18616]
```
@workflow.step
def error_step():
   actor = workflow.get_actor("a")
   actor.method.run_async()
   # error
   return "Finished"

error_step.step().run("X") # Error here
workflow.resume("X") # actor.method.run_async will be rerunned, which is not supposed to be.
```

To do this, we need https://github.com/ray-project/ray/issues/18356 and also checkpoint the scheduling info.

**Comment by ericl** [comment]
Actually this seems potentially subtle. For example, what if the method were called twice?

```
@workflow.step
def error_step():
   actor = workflow.get_actor("a")
   actor.method.run_async()
   actor.method.run_async()  # <------ would this be skipped?
   # error
   return "Finished"
```

I think it may be safer/clearer to expect the user to explicitly pass idempotency tokens.

**Comment by iycheng** [comment]
@ericl  I think you got a very good point. I listed the following cases for resume:

```
@workflow.step
def error_step():
   actor = workflow.get_actor("a")
   # error
   actor.method.run_async() # <----- don't skip
   actor.method.run_async()  # <------  don't skip
```


```
@workflow.step
def error_step():
   actor = workflow.get_actor("a")
   actor.method.run_async() # <----- skip
   # error
   actor.method.run_async()  # <------  don't skip
```


```
@workflow.step
def error_step():
   actor = workflow.get_actor("a")

   actor.method.run_async() # <----- skip
   actor.method.run_async()  # <------  skip
   # error
```
So the semantics here is that in either case of the failure when this step is executed successfully, we need to guarantee that the method got executed like it never fail in the beginning.

I think there is a way to make it work, for example, the system token will be: workflowid + step_id + virtual actor id + method + how many times executed in this context.

So for the first one, the token will be

`workflow_id.error_step_id.a.method.0`

and the second one will be

`workflow_id.error_step_id.a.method.1`


Do you mean let the user generate their token and workflow use that as the token we talk about here? (just want to make sure we don't mean the user handle the dedupe in application layer)

**Comment by ericl** [comment]
I actually mean we should let the user handle it at the application layer. Probably we can revisit this if it comes up often, but it seems too magical right now.

**Comment by iycheng** [comment]
To let the user handle it in application layer won't work for long running virtual actors. This means they need to keep that in actor's state all the time. So it'll only accumulate.

But doing it in workflow internally, we can avoid starting the actor method by checking the workflow step's meta. In this way we don't need to store it in virtual actor's state and the workflow itself can be deleted later in the future.

**Comment by iycheng** [comment]
Close it for now.
