### ISSUE TITLE
[Nightly Release] AttributeError: 'Worker' object has no attribute '_credentials' 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#18633]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Nightly release tests are broken by 
AttributeError: 'Worker' object has no attribute '_credentials' 

https://buildkite.com/ray-project/periodic-ci/builds/987#178c69a0-23d1-43d5-b172-1b0b0667d528

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/987#178c69a0-23d1-43d5-b172-1b0b0667d528

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
Chris, you may have the best context here. Seems related to this [PR](https://github.com/ray-project/ray/pull/18484). 
It's affecting all our nightly tests that use Anyscale client.

@Yard1 do you think we can flip `[use_connect](https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/golden_notebook_tests/golden_notebook_tests.yaml?L7:5)` in all 3 tests?

**Comment by xwjiang2010** [comment]
cc @jjyao

**Comment by jjyao** [comment]
Should we then revert the PR for now?

**Comment by Yard1** [comment]
The entire point of those tests is to use connect 😅

**Comment by ckw017** [comment]
Fix worked on test_wheels, will leave open until the next nightly run works

**Comment by ckw017** [comment]
Looks resolved in the last nightly run
