### ISSUE TITLE
[Release] serve_micro_benchmark is failing nightly release test

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18648]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/987#b4722355-6c26-4bbc-82d3-73b39cd7c443

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/987#b4722355-6c26-4bbc-82d3-73b39cd7c443

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaodong** [comment]
This is test implementation issue rather than serve code that recent changes of serve controller code simply surfaced it. It's recently resolved in #18566 (see full context on PR comments); I will add the commit hash to cherrypick list but can confirm it's not release blocking.

**Comment by jiaodong** [comment]
I've updated cherry pick doc, @jjyao feel free to close this PR once it's cherrypicked on release branch.
