### ISSUE TITLE
[Feature] One more step for kv manager

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#18688]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We already have a kv manager in gcs server and some Python codes use it to store some metadata or configuration with methods like `_internal_kv_get`/`_internal_kv_put` in `ray.experimental.internal_kv`. 
There're some needs from our users who wanna store some meta info or configuration in there applications but don't wanna maintain a extra storage backend like mysql or redis because it's too expensive.
So I like to do things below:
1. Expose kv api in Java side, as our internal users mostly use Java api of Ray.
2. Remove `experimental` tag in Python `internal_kv`, make it public and official.
3. Unify api of kv in Java and Python side. In Java it looks like `Ray.internal().kv().get(key)` and Python `ray.internal_kv.get(key)`.
4. Remove redis part in Python `internal_kv.py`. (Also part of removing redis dependency job)

Making this part public has some concerns:
1. Users are not allowed to put too large or too many k-v, or it would bring a burden to gcs/redis.
2. Users are not allowed to operate some specified keys, like those prefixed with `Actor:` or `Job:`.

To resolve these two concerns, for long term we can support optional storage backends like an extra redis, mysql, hbase, etc.

Welcome to comment on this. @iycheng 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This needs an api review. Cc @ericl

**Comment by ericl** [comment]
I think we should have a separate API for durable storage, and leave internal KV alone.

**Comment by ericl** [comment]
I think the next step would be to propose an API for the durable storage, and a pluggable backend interface in Python (can likely adapt spill worker's existing storage interface).

We'd need to outline how storage users like serve, workflows, and object spilling could leverage such an interface as well.

**Comment by WangTaoTheTonic** [comment]
Could we at least synchronize internal KV function to Java side? As there're so many interfaces only exist in Python but not Java, which is unfair for our users using Java api.

**Comment by iycheng** [comment]
I synced with @mwtian  today. Since we are trying to decouple gcs with redis, internal kv actually is one part of this.
One thing required by the other component, like monitoring is that they don't want to depend on _raylet.so.
So the future direction for internal kv is to use grpc instead of cython API.

> Remove redis part in Python internal_kv.py. (Also part of removing redis dependency job)
This is not a trivial job, it's not like just removing it. We need to make sure some components only have light dependence. 


> I think we should have a separate API for durable storage, and leave internal KV alone.
I vote for this one. We probably still want to keep internal kv experimental and maybe deprecate this component in the future once we have the durable storage layer.

**Comment by iycheng** [comment]
> Could we at least synchronize internal KV function to Java side? As there're so many interfaces only exist in Python but not Java, which is unfair for our users using Java api.

I do feel there are gaps here for multi-language. We need to make sure things can be supported easily with a thin wrapper as a long-term plan.
