### ISSUE TITLE
Can Distributed Scikit-learn/Joblib be executed in a distributed manner only through hyperparameter search? 

### ISSUE THREAD

**Issue by YeahNew** [ray-project/ray#18687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

@ericl @AmeerHajAli @richardliaw @krfricke @bartbroere @Yard1 
Hello,
I have been paying close attention to the topic of Distributed Scikit-learn / Joblib. I hope that scikit-learn can use ray to realize distributed modeling, and each distributed task only processes part of the data. But I found that to do distributed scikit-learn according to the official case method（https://docs.ray.io/en/master/joblib.html）, it can only be done in the form of hyperparameter scanning. If you use the model directly（logistic.fit(x_train,y_train)）, only one process is observed in the ray web UI interface. Is that so? 
Looking forward your reply~

### Use case
```python
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV,train_test_split
from scipy.stats import uniform

x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=.2)
logistic = LogisticRegression(solver='saga', tol=1e-2, max_iter=50,random_state = 0)
distributions = dict(C=uniform(loc=0, scale=4),penalty = ['l2', 'l1'])
clf = RandomizedSearchCV(logistic, distributions, random_state=0,n_iter=100,verbose=10)

import joblib
from ray.util.joblib import register_ray
register_ray()
with joblib.parallel_backend('ray'):
    clf.fit(x_train, y_train)
    # logistic.fit(x_train,y_train)

pred = clf.predict(x_test)
#pred = logistic.predict(x_test)
accuracy = np.count_nonzero(np.array(pred) == np.array(y_test)) / len(pred)
print("accuracy:{:0.3f}".format(accuracy))
```
### Related issues

When Distributed Scikit-learn / Joblib executes distributed tasks, does each task mean to obtain a part of the data（mini-batchsize）? 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Also cc @Yard1

**Comment by Yard1** [comment]
@YeahNew Ray joblib backend is just that - a backend for joblib. If a scikit-learn model/transformer/object does not use joblib internally, then the Ray backend won't have anything to parallelize. As far as I know, the linear/logistic regression models in scikit-learn do not use joblib. Examples of estimators that do are random forests, voting/stacking estimators and indeed, hyperparameter searchers.

**Comment by YeahNew** [comment]
> 
> 
> @YeahNew Ray joblib backend is just that - a backend for joblib. If a scikit-learn model/transformer/object does not use joblib internally, then the Ray backend won't have anything to parallelize. As far as I know, the linear/logistic regression models in scikit-learn do not use joblib. Examples of estimators that do are random forests, voting/stacking estimators and indeed, hyperparameter searchers.
> 
> What part of the data each worker obtains depends on how joblib is used inside the model, but in most cases, all workers get the entire dataset.

Then I have another question. Ray joblib backend is not capable of accelerating all models of scikit-learn, right? In another issue（https://github.com/ray-project/ray/issues/17974） I submitted, someone（gracedu0213） directly used sklearn.ensemble.RandomForestClassifier by Distributed Scikit-learn / Joblib on Ray, and the results showed that it did not speed up the modeling.

**Comment by Yard1** [comment]
Hey @YeahNew, the main benefit from using the Ray backed for joblib is the ability to run jobs on a Ray cluster as opposed to a single node. There is some extra overhead coming from Ray, and you are unlikely to see speedups if you use the Ray joblib backend on a single node.
