### ISSUE TITLE
[CI][Bug]  CI uploads wrong Ray wheels to AWS.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#18702]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

When we download ray wheels from aws, the __commit__ of the wheels is different the revision indicates by the aws url.

For example we expect pip3 install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/12b3b1f7238db655a8ab41530d3709e7e6cfbed8/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl 
has revision 12b3b1f7238db655a8ab41530d3709e7e6cfbed8, but it's not the case.

> Just for completeness, it is not that the commit string on the wheel is incorrect - the wheel itself is wrong. So if the wheel is named /master/aaaa/ray.whl and __commit__="bbbb", then you in fact have the wheels corresponding to commit bbbb. These just have been uploaded to the wrong path (or, actually, to both paths, /master/aaaa/ray.whl and /master/bbbb/ray.whl)

first identified from nightly tests failure: https://beta.anyscale.com/o/anyscale-internal/configurations/app-config-details/bld_Ryt1W6DAAiwMg2LeXtzR8H6m

### Reproduction script

```
pip3 install -U https://s3-us-west-2.amazonaws.com/ray-wheels/master/12b3b1f7238db655a8ab41530d3709e7e6cfbed8/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
python -c 'import ray; assert ray.__commit__ == "12b3b1f7238db655a8ab41530d3709e7e6cfbed8"'
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
two more bad wheels: 
 https://s3-us-west-2.amazonaws.com/ray-wheels/master/de050e81874035a4279f007a913a7ebd32317209/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl 
 https://s3-us-west-2.amazonaws.com/ray-wheels/master/ba1c489b79409ca61b1e046e6e684410e9a94629/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

**Comment by krfricke** [comment]
My guess here is that buildkite runners are re-used and not completely purged. We recently ran into a problem in a release CI test:

```
fatal: destination path '/var/lib/buildkite-agent/ray' already exists and is not an empty directory.
```

https://buildkite.com/ray-project/periodic-ci/builds/1041#05f1809e-6238-4610-962f-df2b893e39fb

which might indicate that this is the case cc @simon-mo do you know more about this?

**Comment by krfricke** [comment]
Just for completeness, it is not that the commit string on the wheel is incorrect - the wheel itself is wrong. So if the wheel is named `/master/aaaa/ray.whl` and `__commit__="bbbb"`, then you in fact have the wheels corresponding to commit `bbbb`.

**Comment by jjyao** [comment]
@krfricke are you saying the wheels in https://s3.console.aws.amazon.com/s3/buckets/ray-wheels?region=us-west-2&prefix=master/&showversions=false is wrong? I manually installed them and `__commit__` is correct.

**Comment by krfricke** [comment]
Another followup, this only happens for *Linux wheels*, the Mac wheels are correct! (or at least I haven't seen a mismatch, yet)

**Comment by jjyao** [comment]
This is more obvious https://buildkite.com/ray-project/ray-builders-branch/builds/3799#283c057c-6334-466b-805d-75535a16e169: we are building wheels for 1.7.0 but some 2.0.0.dev0 wheels from master are also uploaded to s3.
