### ISSUE TITLE
[Bug] Race condition in reference counting

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#18723]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

Not sure if this is duplicated with #18552. I'll just raise this issue.

### Ray Component

Ray Core

### What happened + What you expected to happen

Deep nested recursion randomly causes reference counting error under linux and macos (with the reproduction script):

```
...
(f pid=21793) => step 95
(f pid=21793) => step 97
[2021-09-17 21:18:48,248 C 21763 21763] reference_count.cc:474:  Check failed: !inner_it->second.contained_in_borrowed_id.has_value() Outer object ccf18832be165679ffffffffffffffffffffffff0800000001000000, inner object 991f8dfb5ecc308fffffffffffffffffffffffff0800000001000000
*** StackTrace Information ***
    _ZN3ray12GetCallTraceB5cxx11Ev
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::ReferenceCounter::DeleteReferenceInternal()
    ray::core::ReferenceCounter::RemoveLocalReference()
    __pyx_pw_3ray_7_raylet_10CoreWorker_87remove_object_ref_reference()
    __Pyx_PyObject_CallOneArg()
    __pyx_tp_dealloc_3ray_7_raylet_ObjectRef()
    PyDict_SetItem
```

### Reproduction script

```python
import ray

@ray.remote
def f(x):
    print(f"=> step {x}")
    if x > 400:
        return x
    return f.remote(x + 1)


r = f.remote(1)
while isinstance(r, ray.ObjectRef):
    r = ray.get(r)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Thanks for the clean reproduction! cc @stephanie-wang @iycheng

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/18552
