### ISSUE TITLE
Numba integration 

### ISSUE THREAD

**Issue by DrTodd13** [ray-project/ray#18769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I propose a tighter Ray+Numba integration.  As part of http://github.com/Python-for-HPC/ramba, we explored how to create one decorator that applies both @ray and @numba.njit.  This decorator removes the need to create a ray wrapping function by hand.  This is straighforward for functions but more complicated for actors.  For actors, we applied our combined decorator to the actor class but we also introduced a decorator for actor methods to indicate which of the actor methods should be Numba compiled.  Our approach was to try to compile such annotated functions in Numba parallel mode and if that fails then fallback to non-parallel and if Numba fails entirely to fallback to Python.

### Use case

We got good performance results and excellent programmability from our approach but our approach suffers from being a separate package.  Something like this could really be integrated into Ray maintaining its existing decorator but with an additional flag to indicate Numba compilation.  When that flag is present, Ray could incorporate the technology we developed in the aforementioned package to hide the work to create the wrapping functions and to maintain a nice programmable environment.  I would like to open a dialogue to talk about what we've done in ramba and to see if you agree like I do that this would be be placed as an option in ray itself.  We are happy to work with you to help port our technology into ray.

### Related issues

#593 and #7298

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DrTodd13** [comment]
@robertnishihara @pspillai Please note this feature request.

**Comment by robertnishihara** [comment]
Thanks @DrTodd13 sounds like an interesting idea :)

Do you have example benchmarks or use cases where this gives a big speedup (Ray + Numba versus just Ray)?

Also, do you have an API proposal?

**Comment by DrTodd13** [comment]
@rob

> Thanks @DrTodd13 sounds like an interesting idea :)
> 
> Do you have example benchmarks or use cases where this gives a big speedup (Ray + Numba versus just Ray)?
> 
> Also, do you have an API proposal?

We mostly benchmarked versus the parallel research kernels (https://github.com/IntelLabs/Kernels.git).  In particular, we looked mostly at nstream, stencil, and mandelbrot.  For nstream, our ray+numba integration was >4x faster on 4 nodes compared to ray alone on 4 nodes.  For stencil, ray+numba was about 6x faster than ray.  For mandelbrot, ray+numba was around 8x faster if I recall.  @pspillai can speak to these numbers a bit better than I can since he was the one who did most of the benchmarking.  In general, I think to answer your question I would say that if it is a problem that people would generally want to use Numba on for single node then they would very likely want to use it to do the local computations in the multi-node case as well.  If you have to breakup a problem to go multinode then you can break it up even more and get some of the parallelism benefits from ray that you would also get from Numba but a lot of people still just use single-threaded Numba for the benefits of compiled code and I think that is mostly what you see in the previous data.

In terms of API, @pspillai and I haven't discussed it much since we were primarily seeing if the idea worked in our own package but I was thinking an additional flag to the ray decorator like "numba=True".  The decorator to say which actor method to compile, we used "ramba.jit", but I think that does need to be a new decorator in ray that you could name however you wish.

One thing to be careful about is thread counts since both ray and Numba use them.  Perhaps ray's num_cpus could do double-duty and control the Numba thread count as well.  I believed that is what we did in our case (although we did it manually) but I think we gained some insight that that is perhaps the right thing to do and easily done automatically.

**Comment by DrTodd13** [comment]
@robertnishihara Created a WIP PR to show you the kind of thing I was suggesting.  Tested locally on a few examples but didn't add any examples to the PR and can't get the test suite to run on my machine.

**Comment by robertnishihara** [comment]
@DrTodd13 it's currently possible to use Ray + Numba like in this example (with a little indirection).

Is it correct to say that your PR lets you do the same thing but with more convenient syntax?

```python
import numpy as np
from numba import njit
import ray

@njit(fastmath=True)
def mz_centroid(_int_f, _mz_f):
    return ((_int_f/_int_f.sum()) * _mz_f).sum()


@ray.remote
def f():
    a = np.random.random(10)
    b = 123
    return mz_centroid(a, b)


ray.init()
results = ray.get([f.remote() for i in range(4)])
print(results)
```

**Comment by DrTodd13** [comment]
> @DrTodd13 it's currently possible to use Ray + Numba like in this example (with a little indirection).
> 
> Is it correct to say that your PR lets you do the same thing but with more convenient syntax?
> 
> ```python
> import numpy as np
> from numba import njit
> import ray
> 
> @njit(fastmath=True)
> def mz_centroid(_int_f, _mz_f):
>     return ((_int_f/_int_f.sum()) * _mz_f).sum()
> 
> 
> @ray.remote
> def f():
>     a = np.random.random(10)
>     b = 123
>     return mz_centroid(a, b)
> 
> 
> ray.init()
> results = ray.get([f.remote() for i in range(4)])
> print(results)
> ```

If you really wanted the call to random to not be Numba compiled then you would be forced to do it your way.  However, if you can include random as part of the Numba compilation (which there is reason to because it will parallelize for large sizes) then the syntax enabled by the PR would be as follows:

```@ray.remote(numba={'fastmath':True})
def f():
    a = np.random.random(10)
    b = 123
    return ((a/a.sum()) * b).sum()
```
