### ISSUE TITLE
[RLlib] the way replay_proportion works for agents like APPO and IMPALA is not intuitive

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#18799]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Our IMPALA and APPO agents support a config field called replay_proportion.

https://github.com/ray-project/ray/blob/698b4eeed3e2699f3181baeadecf966702a55eaf/rllib/agents/ppo/appo.py#L63
https://github.com/ray-project/ray/blob/698b4eeed3e2699f3181baeadecf966702a55eaf/rllib/agents/impala/impala.py#L68

We have been recommending our customers to use a number between [0, 1.0] (basically percentage).
However, this is totally not how this field works:

https://github.com/ray-project/ray/blob/698b4eeed3e2699f3181baeadecf966702a55eaf/rllib/execution/replay_ops.py#L194-L196

So the relationship between replay_proportion and actual percentage of samples replayed is:

(0, 1.0] -> 50% replayed samples
(1.0, 2.0] -> 66% replayed samples,
(2.0, 3.0] -> 75% replayed samples,
...

This is not ideal, because 1) it's quite confusing. 2) you can't really use other percentages like 70% for example. 3) you can't use less than 50% replayed samples.

I think we should simply change the logic to something like:
```
self.replay_buffer.add_batch(sample_batch). # queue batch for future sampling.
if random.random() < f:
  batch = self.replay_buffer.replay()
else:
  batch = sample_batch
return [batch]
```
This way, we are providing exactly f% of replayed samples.

### Reproduction script

Reproduce by reading the source code.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
Should also benchmark and test potential performance impact after making the change.

**Comment by ericl** [comment]
It does seem confusing, but note that you can in fact select any fraction like 70% (2.3) or 15% (0.17), probabilistically the math works out.

How about adding a new config called replay_fraction and deprecating the proportion option?

I believe the translation would be something like replay_proportion = 1/(1-replay_fraction) - 1

**Comment by gjoliver** [comment]
oh, you are absolutely right. if introducing a new field, I can quickly do that.

**Comment by sven1977** [comment]
It's actually, syntactically, correct to call the current key "proportion". It's just not clear what the other value in the proportion is (it's assumed the user knows it's 1.0).
Yes, let's just soft-deprecate the existing "replay_proportion" key and - if still used - a) warn b) auto-set the new key: "replay_fraction".

replay_fraction = replay_proportion / (replay_proportion + 1)
