### ISSUE TITLE
[Feature] add avx2 resource for training

### ISSUE THREAD

**Issue by kShines** [ray-project/ray#18803]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The tensorflow-gpu with AVX and AVX2 is faster than it without AVX and AVX2. （[View the comparison results](https://stackoverflow.com/questions/46136952/how-faster-is-tensorflow-gpu-with-avx-and-avx2-compared-with-it-without-avx-and)）
When a driver has AVX2 instruction set or other, we can add these resources to config for better training results.
In the process, we use component which named ['cpuinfo'](https://github.com/workhorsy/py-cpuinfo) to get cpu instruction set architectures.
In my commit, we can import environment variables to declare CPU instruction set resources, like "export CPU_INSTRUCTION_SET='avx2, avx'".

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ashione** [comment]
@jovany-wang 

**Comment by jovany-wang** [comment]
Hi @kShines could you tell more details on:
(1) what'll happen if a training worker is not scheduled to a AVX/AVX2  node?
(2) What the API looks like to enable it, a flag called enable_avx or others ?

**Comment by ashione** [comment]
> Hi @kShines could you tell more details on:
> (1) what'll happen if a training worker is not scheduled to a AVX/AVX2 node?
> (2) What the API looks like to enable it, a flag called enable_avx or others ?

User might know their apps deps build with avx instruction or not.  Different env/ray version should be guranteed If they want to run tensorflow on ray cluster.
For api-wise, in first implementation, we can set a simple env variable that determines node of ray cluster should report specific resource or not.

**Comment by jovany-wang** [comment]
Let's reschedule this item. @kShines

**Comment by kShines** [comment]
@jovany-wang Please help me find some reviewers

**Comment by jovany-wang** [comment]
If you have more actions on this, please reopen this.
