### ISSUE TITLE
TuneBOHB search algorithm cannot save 

### ISSUE THREAD

**Issue by zahta** [ray-project/ray#18811]
### Search before asking

- [ ] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Executing codes on Google Colab 
Ray version: 1.6.0
Python version: 3.7.12

We faced an issue with the BOHB search algorithm (TuneBOHB) and HyperBandForBOHB Scheduler. No checkpoints have been saved and we received the following warning: 

2021-09-20 06:56:05,895	WARNING suggestion.py:290 -- save not implemented for Searcher. Skipping save.

We should mention that there was no problem with saving checkpoints while using the PBT search algorithm. Furthermore, we run our codes on Google Colab and trying to save checkpoints on Google Drive.

### Reproduction script

2021-09-20 06:56:05,895	WARNING suggestion.py:290 -- save not implemented for Searcher. Skipping save.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Thanks for raising this issue - this was fixed in #18399
