### ISSUE TITLE
[Bug] [Datasets] parallelism does not match num_blocks

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#18828]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When creating a dataset, the number of blocks is sometimes greater than the `parallelism` argument. My expectation was that the number of blocks would be the exact same as the parallelism.

cc @scv119 

### Reproduction script

```python
import ray

num_records = 10
for i in range (1, num_records + 1):
    ds = ray.data.range(num_records, parallelism=i)
    num_blocks = ds.num_blocks()
    print(f"parallelism: {i}, num_blocks: {num_blocks}")
```

```
parallelism: 1, num_blocks: 1
parallelism: 2, num_blocks: 2
parallelism: 3, num_blocks: 4
parallelism: 4, num_blocks: 5
parallelism: 5, num_blocks: 5
parallelism: 6, num_blocks: 10
parallelism: 7, num_blocks: 10
parallelism: 8, num_blocks: 10
parallelism: 9, num_blocks: 10
parallelism: 10, num_blocks: 10
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@ericl @clarkzinzow does this look like a bug?

**Comment by ericl** [comment]
This is expected, since you cannot parallelize a single record further. The parallelism argument is just a hint.
