### ISSUE TITLE
Support concurrent.futures interfaces

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1883]
https://docs.python.org/3/library/concurrent.futures.html

Since this is a part of the standard library in Python 3, it would be useful to have an implementation/adapter for `concurrent.futures.Executor` and `concurrent.futures.Future`. This would make it easier to port existing software which uses this interface (e.g. `concurrent.futures.ProcessPoolExecutor`) and also interoperate with any other libraries using it.

**Comment by mrocklin** [comment]
You might also want to look at `as_completed` and `wait`, both of which are fairly commonly used.

**Comment by edoakes** [comment]
We support `asyncio` futures interface now

**Comment by jcmgray** [comment]
This would still be very convenient to have - and is I think a separate issue and interface from `asyncio` no?
