### ISSUE TITLE
[Feature][workflow] Delete virtual actor after use

### ISSUE THREAD

**Issue by yuanchi2807** [ray-project/ray#18848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Workflow virtual actors are persistent on backend storage. Provide a function to delete or clean up the artifacts and free up storage space. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
I'd propose the following API:

```
workflow.delete(workflow_id="")
```

**Comment by yuanchi2807** [comment]
> I'd propose the following API:
> 
> ```
> workflow.delete(workflow_id="")
> ```

That'd work prefectly.

**Comment by iycheng** [comment]
```
workflow.delete(namespace="ns", workflow_id="id") # delete job id in namespace ns
workflow.delete(namespace="ns") # delete the whole namespace ns
```

**Comment by wuisawesome** [comment]
Some proposed behavior for the edge cases here:

What do when you delete a running workflow?

Let's leave it undefined for now (since we don't have `workflow.cancel`)


Calling delete on a non-existent workflow?

Do nothing, maybe print a warning? (this provides idempotency).

**Comment by iycheng** [comment]
Yes, for a running one, we should `workflow.cancel` and then delete.
