### ISSUE TITLE
Inconvenient to programmatically get information about exceptions raised in remote functions

### ISSUE THREAD

**Issue by rshin** [ray-project/ray#1885]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 2.7.12
- **Exact command to reproduce**: see below

### Describe the problem

If a remote function raises an exception, Ray prints the traceback from the exception to stdout and raises a RayGetError when `ray.get` is called on the corresponding remote object (which causes the traceback to be printed again).

While the diagnostics are helpful for debugging unintended or unanticipated exceptions, transmuting the exception into a RayGetError does not facilitate programmatic exception handling. RayGetError is not exported from the `ray` module, and it does not directly contain any information about the exception which caused it (except within the traceback string inside `e.task_error.traceback_str`).

### Source code / logs

```python
from __future__ import print_function
import ray
class MyException(Exception):
  pass
@ray.remote
def f():
  raise MyException
ray.init()
try:
  ray.get(f.remote())
except MyException:
  print('I caught my exception')
```
does not print 'I caught my exception'

In contrast, this example with multiprocessing works fine:
```python
from __future__ import print_function
import multiprocessing
class MyException(Exception):
  pass
def f():
  raise MyException
pool = multiprocessing.Pool()
try:
  pool.apply_async(f).get()
except MyException:
  print('I caught my exception')
```

**Comment by mitar** [comment]
I think there is also `ray.worker.error_info` function which might help here?

**Comment by richardliaw** [comment]
This should be fixed now that we subclass the error.
