### ISSUE TITLE
[Bug] progress.csv header missing

### ISSUE THREAD

**Issue by resuly** [ray-project/ray#18892]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

https://github.com/ray-project/ray/blob/0669e651b93c6da8bbfe39b41e4ea3ca3ae89edf/python/ray/tune/analysis/experiment_analysis.py#L360

For some reason, the progress.csv sometimes doesn't have a header. This will lead to wrong column names and code broken above.

### Reproduction script

I'm can't provide the reproduction script but this could be caused by tune.run(**resume=True**). 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Without a reproduction script or at least some context on what you're running this is hard to debug. I tried a few things and looked over the code, but couldn't find any issues.

Which version of Ray are you using?
What kind of workload are you running? Is this a RLLib trainable? Are you using custom loggers or callbacks? 

Without this information we're unable to help resolving this.
