### ISSUE TITLE
[Feature] Introduce Node Name Concept to Raylet

### ISSUE THREAD

**Issue by lixin-wei** [ray-project/ray#18915]
### Description

Now when starting a raylet, a random node ID will be generated.

But sometimes we need all raylets in a pod to have a consistent name.

So we want to introduce a 'node name' concept to raylet. This name is passed through raylet's main args. One raylet has at most one node name. And node name is unique across the entire cluster.

Here are some use cases:
1. A raylet died and restarts in a pod, now we need to wait for GCS to notice the heartbeat timeout(30s), and then the actors in the old raylet will be rescheduled. With node name, GCS can find that a raylet with the same node name is registered and mark the old one as dead immediately.
2. A pod has some hardware error, the raylet in it keeps dying and restarting. We want to add this node to the blacklist so that no tasks will be scheduled to this node anymore. But the node ID keeps changing, we don't have a consistent name to figure out these raylets. With node name, we can do it.

The above two features have already been implemented in Ant and is using for a while. The first one is called 'Quick raylet failover', the second is called 'Node Freezing'. We want to open source them, but first, we need to add the 'node name' concept.

Do you agree with adding this concept? Looking forward to your comments! If you all agree I'll open a PR to do this.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
To clarify, this will be in addition to node id? So we have:
- Node name (set by external env var, stable across restarts).
- Node id (unique to each restart).

Btw, is the idea we can set the node name to the machine IP / pod name by default?

**Comment by scv119** [comment]
> And node name is unique across the entire cluster.
How will this be enforced? Random generated NodeID is a good forcing function to reduce human errors.

> A more fundamental question: what does it mean to have two Raylets/nodes (maybe at the same time, or one stopped and another come up with the same name) have the same node name. 
Does this mean they have same durable state, or same hardware?

**Comment by lixin-wei** [comment]
> To clarify, this will be in addition to node id? So we have:
@ericl Yeah, exactly.

> Btw, is the idea we can set the node name to the machine IP / pod name by default?
@ericl Yeah, that's exactly what we do now. We set it to the IP by default :)

**Comment by lixin-wei** [comment]
> To clarify, this will be in addition to node id? So we have:

@ericl Yeah, exactly.

> Btw, is the idea we can set the node name to the machine IP / pod name by default?

@ericl Yeah, that's exactly what we do now. We set it to the IP by default :)

**Comment by lixin-wei** [comment]
> How will this be enforced? Random generated NodeID is a good forcing function to reduce human errors.

@scv119  When a raylet with the same node name is registered to GCS, GCS will mark the old one as DEAD immediately. And in this way, we can make raylet failover quicker.

> A more fundamental question: what does it mean to have two Raylets/nodes (maybe at the same time, or one stopped and another come up with the same name) have the same node name.
Does this mean they have same durable state, or same hardware?

@scv119  In our cases, it means they are in the same pod/physical machine. We set the node name to the machine IP by default.

And there won't be two raylets that have the same node name be alive at the same time.

**Comment by scv119** [comment]
> How will this be enforced? Random generated NodeID is a good forcing function to reduce human errors.

>  @scv119 When a raylet with the same node name is registered to GCS, GCS will mark the old one as DEAD immediately. And in this way, we can make raylet failover quicker.

So if we accidentally started two nodes with same name one will be killed. The burden is on user to pick unique names, especially for OSS users.  Can we do something different like adding a `tombstone node` and called by container management system?

**Comment by lixin-wei** [comment]
> So if we accidentally started two nodes with same name one will be killed. The burden is on user to pick unique names,

The node name is empty by default. User won't set this. So this won't have any side effects by default.

 We'll set the node name when starting cluster. In Ant we set it to machine IP in cluster starting scripts. In community maybe we can set it to pod name or IP in autoscaler.

> especially for OSS users. Can we do something different like adding a tombstone node and called by container management system?

What's the meaning of OSS and `tombstone node`? Would you please say more about this?

**Comment by rkooo567** [comment]
This sounds like the better semantics is we never allow users to set the node name, but it is automatically set based on the deployment systems (like Eric suggested)?

**Comment by lixin-wei** [comment]
> This sounds like the better semantics is we never allow users to set the node name, but it is automatically set based on the deployment systems (like Eric suggested)?

@rkooo567 Yes, that's more clear. Normal users will never use this. Only deployment systems will set node names.
