### ISSUE TITLE
[ci/Feature] Add kubernetes release tests 

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#18922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The k8s test suite is not included in release testing at the moment, but they were for previous releases (e.g. 1.4.0).

We should add them back at some point.

cc @DmitriGekhtman 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Really, this "automate kubernetes release tests"

**Comment by DmitriGekhtman** [comment]
Release testing for Ray on K8s is tracked elsewhere. The tests in question have been removed along with the legacy Ray operator.
