### ISSUE TITLE
[Serve] [Serve Autoscaler] [Bug] Undesirable repeating scale up / scale down behavior

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18925]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

1. A single replica is started, requests start to pile up and its queue becomes long.
2. Serve autoscaler starts up N replicas in response.
3. Instantly, the average queue length is much smaller, by a factor of N.
4. Serve autoscaler scales down. Empirically it seems to shut down the first replica.  The requests piled up in its queue disappears.
5. The average queue length is now very small, and we scale back down to one replica.  
6. Repeat (assuming the rate of requests is roughly constant)

This behavior is not desirable.  Ideally, we scale up, which takes pressure off the first replica by spreading new requests among the new replicas, which causes the first queue to shrink, and we reach some sort of stable equilibrium.

### Reproduction script

TODO.  Basically, have a deployment that sleeps for 1 second, and then flood it with requests (say 5 requests per second).

### Anything else

Followup issue from https://github.com/ray-project/ray/pull/18793

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
Can you sketch out the fix here? Would it be:
- Controller shutdown replicas with least number of enqueued items
- Have longer shutdown grace period for the first replica
- something else?

**Comment by architkulkarni** [comment]
After discussing with @edoakes, I think I was using an unrealistic request processing size (10s-30s per request) when I was manually testing.  Since a typical heavyweight request will only take 1-2s, I think the existing shutdown grace period of 20s should be fine.

Let me test this again with 1-2s requests, and also with the downscale delay enabled.  If the problem still persists, then we can look into having the controller shut down replicas with the shortest queues first.

**Comment by architkulkarni** [comment]
accidentally closed

**Comment by architkulkarni** [comment]
@simon-mo I tested with 1 second requests and with 0 upscale/downscale delay, and it behaved as expected.  I wonder whether the 2.0 second default `graceful_shutdown_wait_loop` should be increased.  If we assume that a "heavyweight" model takes 1-2 seconds per request, then a stopped replica will only have time to process 1 or 2 requests before the graceful shutdown, so if the queue is large it'll discard most of it.  

Separately, I tried enabling upscale and downscale delay (setting both to 10s) and got some weird behavior:
```
(ServeController pid=20248) 1
(ServeController pid=20248) [4.147286821705427]
(ServeController pid=20248) 1
(ServeController pid=20248) [4.184615384615385]
(ServeController pid=20248) 5
(ServeController pid=20248) [4.221374045801527]
(ServeController pid=20248) 2021-10-22 17:17:20,347	INFO backend_state.py:910 -- Adding 4 replicas to deployment 'f'. component=serve deployment=f
(ServeController pid=20248) 1
(ServeController pid=20248) [4.2781954887218046]
(ServeController pid=20248) 2021-10-22 17:17:20,478	INFO backend_state.py:929 -- Removing 4 replicas from deployment 'f'. component=serve deployment=f
(ServeController pid=20248) 1
(ServeController pid=20248) [4.298507462686567]
(ServeController pid=20248) 1
(ServeController pid=20248) [4.318518518518519]
```
Here it's printing the target `num_replicas` and the list `current_num_ongoing_requests` during each controller loop.  The bug is that it immediately scales down after scaling up.  (It correctly waits 10s to scale up.). I'm investigating this right now, it should be a simple fix.

**Comment by architkulkarni** [comment]
Found the root cause.  It's that right after it scales up, the current number of replicas stays at the initial value (here, 1) for a short while (because replicas take time to start up).  The autoscaler sees this, notes that the upscale/downscale delay timer hasn't yet been reached (because it was just reset), and therefore decides to keep the number of replicas the same.  But to do this, it sets num_replicas to the current number of replicas, which is still 1.  I have an idea of how to fix this so I'll submit a PR.
