### ISSUE TITLE
[Bug/data] `filter()` on empty dataset raises ValueError 

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#18972]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Running `filter()` on an empty dataset fails with `ValueError: not enough values to unpack (expected 2, got 0)`

cc @ericl @clarkzinzow 

### Reproduction script

```
import ray

ray.init()

ds = ray.data.from_items([])
ds = ds.filter(lambda x: True)

print(list(ds.iter_rows()))
```

Output:

```
Map Progress: : 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Users/kai/coding/sandbox/scratch.py", line 6, in <module>
    ds = ds.filter(lambda x: True)
  File "/Users/kai/coding/ray/python/ray/data/dataset.py", line 303, in filter
    return Dataset(compute.apply(transform, ray_remote_args, self._blocks))
  File "/Users/kai/coding/ray/python/ray/data/impl/compute.py", line 48, in apply
    new_blocks, new_metadata = zip(*refs)
ValueError: not enough values to unpack (expected 2, got 0)
Map Progress: : 0it [00:02, ?it/s]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
@clarkzinzow can you take a look? cc @scv119
