### ISSUE TITLE
fail to run hyperopt_example 

### ISSUE THREAD

**Issue by PiggyFan** [ray-project/ray#1897]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sierra
- **Ray installed from (source or binary)**:  source
- **Ray version**: 0.4.0
- **Python version**: 3.6
- **Exact command to reproduce**: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperopt_example.py#L33

### Describe the problem

When I use the hyperopt_example, the value in "space" can't serialize to JSON. (line 33)
The error is about ray/tune/variant_generator, line 20, to_argv tried to serialize hp.uniform which is not JSON serializable. I had installed the hyperopt package via tutorial specified source. How could I fix this error? Thanks for resolving my problem.

### Source code / logs

![2018-04-13 5 38 41](https://user-images.githubusercontent.com/26171212/38728151-a6a8b1bc-3f41-11e8-9dd7-9c8e80ad9a0a.png)

**Comment by richardliaw** [comment]
Can you try upgrading Ray to the latest version as mentioned here:
http://ray.readthedocs.io/en/latest/installation.html

I believe your version of Ray is a bit outdated. Let me know if that fixes
your problem!

**Comment by PiggyFan** [comment]
Thanks a lot. After upgrading the latest version the problem be fixed.

**Comment by sdr2002** [comment]
Same issue came here.
I have up-to-date ray via 
pip install --upgrade ray in anaconda2/python3.6 env.
Hyperopt is installed and 'hpo_scheduler.py' is downloaded from git repo into the right directory(in pip ver, hpo_scheduler.py is not placed, fyi)
Still have 'TypeError: Object of type 'Apply' is not JSON serializable' error.
