### ISSUE TITLE
[Release] horovod_test is failing weekly release test 

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#18989]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
Traceback (most recent call last):
--
  | File "release/e2e.py", line 1972, in <module>
  | app_config_id_override=args.app_config_id_override,
  | File "release/e2e.py", line 1874, in run_test
  | raise RuntimeError(last_logs)
  | RuntimeError: Command returned non-success status: 1; Command logs:  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 226, in _run
  | self.autoscaler.update()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 200, in update
  | raise e
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 185, in update
  | self._update()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 315, in _update
  | ensure_min_cluster_size=self.load_metrics.get_resource_requests())
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 197, in get_nodes_to_launch
  | strict_spreads, node_resources, node_type_counts)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/resource_demand_scheduler.py", line 542, in reserve_and_allocate_spread
  | assert not unfulfilled
  | AssertionError
```

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/1156#c04b3286-b535-4f50-bca6-2f16a1d2a20a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
It seems like it's failing on something unrelated to the test itself.

**Comment by AmeerHajAli** [comment]
@jjyao / @richardliaw , I am not sure what to do here. @wuisawesome , do you know what's up?

**Comment by AmeerHajAli** [comment]
@ijrsvt can you help on this one?

**Comment by jjyao** [comment]
It passed with a retry: https://buildkite.com/ray-project/periodic-ci/builds/1156#45d1fe68-f957-405d-b2dd-b282223f3b5e

**Comment by ijrsvt** [comment]
@AmeerHajAli do you still want me to look into this?

**Comment by AmeerHajAli** [comment]
@jjyao , is this closed??

**Comment by jjyao** [comment]
@AmeerHajAli I think the issue is still there even though it doesn't always happen. I think we can keep it as P0 but not a release-blocker? What do you think?

**Comment by AmeerHajAli** [comment]
@ijrsvt , do you have time to take a look to be a bit precautious?

**Comment by ijrsvt** [comment]
@AmeerHajAli I'm not super sure what is going on here. @wuisawesome any ideas off the top of your head?

**Comment by wuisawesome** [comment]
I'd want to see logs (in particular, if thie "The autoscaler could not find a node type to satisfy..." is getting printed). It looks like that assertion can either get triggered if there's a bug in the logic, or an unexpected input to the function. It may also be worth just putting logging why that assertion is failing.

**Comment by ericl** [comment]
I'm downgrading this. It's on ML team to prioritize.
