### ISSUE TITLE
[Release] node_failure is failing the weekly release test

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#19009]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
Traceback (most recent call last):
  File "workloads/node_failures.py", line 68, in <module>
    cluster.add_node()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/cluster_utils.py", line 112, in add_node
    spawn_reaper=self._shutdown_at_exit)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/node.py", line 244, in __init__
    self._ray_params.update_pre_selected_port()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/parameter.py", line 318, in update_pre_selected_port
    f"Ray component {comp} is trying to use "
ValueError: Ray component metrics_export is trying to use a port number 60096 that is used by other components.
Port information: {'gcs': [], 'object_manager': [], 'node_manager': [], 'gcs_server': [], 'client_server': [], 'dashboard': [8265], 'dashboard_agent': [60096], 'metrics_export': [60096], 'redis_shards': [], 'worker_ports': [0]}
If you allocate ports, please make sure the same port is not used by multiple components.
```

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/1156#78145457-1df0-40c1-ab65-5faf730a152f

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This is a long-lived issue. I think we can close it. It happens because our port assignment logic is not robust, and we are testing many nodes failure with cluster_utils (so it is more likely to have port collision). We should eventually move this test to happen in real multi nodes.
