### ISSUE TITLE
[Bug] The CRD of RayCluster can't support the apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by UrmsOne** [ray-project/ray#19001]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Environment: 
* k8s v1.15.1 
* Ray tag v1.6.0

The k8s cluster in the production environment is v1.15.1, supported the CRD VERSION of "apiextensions.k8s.io/v1beta1". 

But the current crd configuration file "deploy/charts/crds/clsuter_crd.yaml"  only supports "apiextensions.k8s.io/v1".

To solve this problem,I have written the CRD configuration file of the version "apiextensions.k8s.io/v1beta1" and willing to 

submit a PR.

### Reproduction script

Reproduction script: 

```
root@ubuntu:/home/ray#kubectl apply -f deploy/charts/crds/clsuter_crd.yaml
error: unable to recognize "crd": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by GoingMyWay** [comment]
@UrmsOne Please upgrade the k8s version to the latest one (v1.16+).  There is no `CustomResourceDefinition` in the version you used.
