### ISSUE TITLE
[Feature] Automatically use GPU without @ray.remote decorator

### ISSUE THREAD

**Issue by lihang-peloton** [ray-project/ray#19011]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Automatically use GPU without @ray.remote decorator

### Use case

We used python multiprocessing for single node parallelism and turned that to 100 nodes with one line code change to `from ray.util.multiprocessing.pool import Pool` from `multiprocessing.pool import Pool` as per 
[How to scale Python multiprocessing to a cluster with one line of code](https://medium.com/distributed-computing-with-ray/how-to-scale-python-multiprocessing-to-a-cluster-with-one-line-of-code-d19f242f60ff)

However, all nodes only used CPU (although GPU are available). Went though the Ray document saying requiring @ray.remote  decorator (potentially changing many existing codes). As a result, we have to give up Ray due to we'd like to keep technology independent and not change too much existing code. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Yard1** [comment]
It should be straightforward to extend the Pool class to accept a kwargs dict that would be passed to the Actor options. Something like this:
````python
Pool(ray_actor_options=dict(num_gpus=1))  # each PoolActor will now require 1 GPU
```

Would that be sufficient for your use case?
