### ISSUE TITLE
[DataFrame] support read_json

### ISSUE THREAD

**Issue by superaja** [ray-project/ray#1902]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MAC OS 10.10.5
- **Ray installed from (source or binary)**: used pip
- **Ray version**: 0.4.0
- **Python version**: 3.6
- **Exact command to reproduce**: from ray import dataframe as rpd
rpd. read_json(data_json, orient = 'index')

AttributeError                            Traceback (most recent call last)
<ipython-input-116-36a05a2f53e0> in <module>()
----> 1 rpd.read_json(a_json, orient='index')

AttributeError: module 'ray.dataframe' has no attribute 'read_json'

### Describe the problem

Would like to request support for read_json function that is currently supported by pandas

**Comment by devin-petersohn** [comment]
Hi @superaja, thanks for the request! We plan to support this very soon. We have a PR #1712 in the works that will solve this problem.

**Comment by superaja** [comment]
Thank you ! 

Will close this and track PR#1712.
