### ISSUE TITLE
[Bug] [rllib] TF2 model export not implemented?

### ISSUE THREAD

**Issue by kevin1zc** [ray-project/ray#19021]
### Ray Component

RLlib

### What happened + What you expected to happen

I trained a PPO policy with tf2 framework and want to export it for external use. However, after I called the policy's `export_model()` function it gave me nothing, and when I checked the source code in ray.rllib.policy.eager_tf_policy I found that this function is not implemented. 
```
@override(Policy)
def export_model(self, export_dir):
    pass
```
I then tried to call the agent's `export_model()` function, but it threw an error: `TypeError: export_model() got an unexpected keyword argument 'onnx'`
How can I save the tf2 policy?

### Reproduction script

Following code gave me nothing:
```
agent = ppo.PPOTrainer(config=config, env=env)
agent.restore(checkpoint)
policy = agent.get_policy()
policy.export_model(save_dir)
```
Following code throws an error:
```
agent = ppo.PPOTrainer(config=config, env=env)
agent.restore(checkpoint)
agent.export_model(ExportFormat.MODEL, save_dir)
```

**Comment by ricky-ma** [comment]
Hi Kevin, did you ever find a work-around for this issue?

**Comment by kevin1zc** [comment]
Hi @ricky-ma ,  I wrote a model saving function directly inside the model class:
```
def save_model(self, path):
    tf.saved_model.save(self.base_model, path)
```
and then call it from the agent: 
```
policy = agent.get_policy()
policy.model.save_model(write_out_path + 'my_model')
```
