### ISSUE TITLE
[Bug] Service names in K8s documentation are inconsistent causing job_example.py to fail

### ISSUE THREAD

**Issue by romilbhardwaj** [ray-project/ray#19061]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters, Others

### What happened + What you expected to happen

The examples provided in the In the [k8s manual deployment](https://github.com/ray-project/ray/blob/master/doc/kubernetes) documentation do not work. Creating the cluster and the example-job using the provided yamls results in a connection error for the job. Here are the logs for `ray-test-job` pod created by [job-example.yaml](https://github.com/ray-project/ray/blob/master/doc/kubernetes/job-example.yaml):

```
--2021-10-03 09:44:06-- https://raw.githubusercontent.com/ray-project/ray/master/doc/kubernetes/example_scripts/job_example.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1311 (1.3K) [text/plain]
Saving to: ‘job_example.py’
0K . 100% 64.8M=0s
2021-10-03 09:44:06 (64.8 MB/s) - ‘job_example.py’ saved [1311/1311]
Traceback (most recent call last):
File "job_example.py", line 50, in <module>
ray.init("ray://example-cluster-ray-head:10001")
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
return func(*args, **kwargs)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 773, in init
return builder.connect()
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/client_builder.py", line 101, in connect
self.address, job_config=self._job_config)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client_connect.py", line 35, in connect
ignore_version=ignore_version)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/__init__.py", line 81, in connect
connection_retries=connection_retries)
File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 156, in __init__
raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout
```

### Reproduction script

Before running, you must have the ray namespace created in k8s.
```
# Create cluster
kubectl create -f https://raw.githubusercontent.com/ray-project/ray/master/doc/kubernetes/ray-cluster.yaml

# Create job-example
kubectl create -f https://raw.githubusercontent.com/ray-project/ray/master/doc/kubernetes/job-example.yaml
```

At this point, the ray-test-job pod fails with a ConnectionError.

### Anything else

This appears to be because the job_example.py has the address of the ray cluster hard coded to `"ray://example-cluster-ray-head:10001"` at [L50](https://github.com/ray-project/ray/blob/b8ef4f0a346b2554910eb53366923b3f6ab5747b/doc/kubernetes/example_scripts/job_example.py#L50). However, the service is named `ray-head` in ray-cluster.yaml at [L6](https://github.com/ray-project/ray/blob/b8ef4f0a346b2554910eb53366923b3f6ab5747b/doc/kubernetes/ray-cluster.yaml#L6).

The fix appears to be simple - either change the service name in ray-cluster.yaml to `example-cluster-ray-head` or change the address in job_example.py to `"ray://ray-head:10001"`. The example works as expected after this.

Happy to submit a PR.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Thanks for pointing this out!
For consistency with other examples in the docs, the preferred fix is to rename the service:
https://github.com/ray-project/ray/pull/19065
