### ISSUE TITLE
[Datasets] Support batching across windows in a DatasetPipeline.

### ISSUE THREAD

**Issue by jerry-pca** [ray-project/ray#19063]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Dataset iter_batches seems to be completely broken when using repeat dataset.

### Reproduction script

```
import ray
def fmt(el):
    return f"{el}"

pipe = ray.data.from_items([(123,'a')]).repeat(9)
pipe = pipe.map(fmt)
for broken_batch in pipe.iter_batches(batch_size=3, batch_format='native'):
    print(f"This is not a batch it's a row {list(broken_batch)}")
    
for row in pipe.iter_rows():
    print(f"This is a row so it makes sense to be one item: {row}") 

```

         
--------- results ------>
Stage 0:   0%|          | 0/9 [00:00<?, ?it/s]
  0%|          | 0/9 [00:00<?, ?it/s]
Stage 1: 100%|██████████| 9/9 [00:00<00:00, 158.88it/s]
Stage 0: 100%|██████████| 9/9 [00:00<00:00, 149.51it/s]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
This is not a batch it's a row ["(123, 'a')"]
Stage 0:   0%|          | 0/9 [00:00<?, ?it/s]
  0%|          | 0/9 [00:00<?, ?it/s]
Stage 1: 100%|██████████| 9/9 [00:00<00:00, 165.67it/s]
Stage 0: 100%|██████████| 9/9 [00:00<00:00, 153.51it/s]
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')
This is a row so it makes sense to be one item: (123, 'a')

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerry-pca** [comment]
cc @ericl @scv119

**Comment by scv119** [comment]
@jerry-pca  what's your expected result?  more like 
```
This is not a batch it's a row ["(123, 'a')", "(123, 'a')", "(123, 'a')"]
This is not a batch it's a row ["(123, 'a')", "(123, 'a')", "(123, 'a')"]
This is not a batch it's a row ["(123, 'a')", "(123, 'a')", "(123, 'a')"]
```
?

**Comment by jerry-pca** [comment]
@scv119 Yes I would expect each batch to be a list (of length batch_size) of objects.

**Comment by ericl** [comment]
Seems we currently don't batch across different dataset within a dataset pipeline. This would be nice to have, but I don't think this is a particularly high priority issue since batching can always return `< batch_size` even with a single dataset at the end.

**Comment by clarkzinzow** [comment]
Bump for this, since users seem to expect that if `len(ds) % batch_size == 0`, then they will see the entire dataset when batching, even after windowing the dataset.

**Comment by ericl** [comment]
Bumped to P1 (seems like an easy enough issue to fix).

**Comment by clarkzinzow** [comment]
Bumping to a P1 since the assumption:
> if `len(ds) % batch_size == 0`, then all batches will be full

is often made implicitly by users.

Another encountered use case is when using batch normalization in their model, which breaks (raises an error) when using a unit batch size. We'd like to recommend that the user ensures that `len(ds) % batch_size != 1` and then this failure case won't be hit, but without batching across windows in a pipeline, this guarantee won't hold and users are forced to handle this edge case in iterator consuming code.
