### ISSUE TITLE
[Bug] building locally on windows does not set std=c++17

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#19070]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I build the python part of ray locally with `cd python; pip install . --use-feature=in-tree-build`. Since #18813 this requires `std=c++17` for the `std::optional` support. That was added to `.bazelrc` in #18622 but apparently that is not working for the pip-invoked bazel. The build fails, complaining about `optional`. Adding `set BAZEL_CXXOPTS="-std=c++17"` did not help.

### Reproduction script

Download `https://github.com/bazelbuild/bazel/releases/download/3.6.0/bazel-3.6.0-windows-x86_64.zip` and extract the contents `bazel.exe` to `C:\bazel\bazel.exe`. Then set environment variabless
```
set BAZEL_PATH=c:\bazel\bazel.exe
set PATH=%PATH%;C:\bazel
set BAZEL_SH=C:\Program Files\Git\bin\bash.exe

cd python; pip install . --use-feature=in-tree-build
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jjyao** [comment]
@mwtian I think you might be able to help here?

**Comment by mwtian** [comment]
I'm unfamiliar with Windows build, but could this be a compiler issue? Which version of MSVC / clang-cl is used here? CC @wuisawesome do you know people who can help with Windows build?

**Comment by wuisawesome** [comment]
@mattip potentially dumb question, but do you know why the windows build succeeds at all with this bug since we have a few uses of `std::optional` and are able to build windows wheels for it?

**Comment by wuisawesome** [comment]
cc @simon-mo

**Comment by simon-mo** [comment]
as context we are using msvc in github action

**Comment by mattip** [comment]
> why the windows build succeeds at all with this bug

There are many environment parameters that can affect this. I guess somewhere in the CI the `.bazelrc` or some other config file is being parsed, where my local build is not parsing them. I am using the latest MSVC 2019.

**Comment by pcmoritz** [comment]
@mattip I could reproduce the issue on my windows machine and this fixes it for me: https://github.com/ray-project/ray/pull/19088

Can you check if that makes it work for you?
