### ISSUE TITLE
[tune] Improve error message for Tune trials failing. 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#19077]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

The user always sees "Trial failed to complete" or "How to deal with TuneError: (‘Trials did not complete’,…)"

But the real user error is usually higher up in the stack trace.

This can be hard for users to diagnose.

We should fix this error message.

https://discuss.ray.io/t/how-to-deal-with-tuneerror-trials-did-not-complete/3718

### Reproduction script

tune.run(lambda cfg: ValueError)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yonil7** [comment]
Is there any plan to fix this? (every time there is an exception during `tune.run()` the log just shows `TuneError("Trials did not complete", incomplete_trials)` and for seeing the original exception one needs to browse and open the `error.txt` file)
