### ISSUE TITLE
[Bug] Build error: `shared_ptr` not in namespace `std`

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#19082]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

1. Bug:
```
In file included from src/ray/util/util.cc:15:
bazel-out/k8-opt/bin/_virtual_includes/ray_util/ray/util/util.h:134:6: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
  134 | std::shared_ptr<std::unordered_map<std::string, std::string>> ParseURL(std::string url);
      |      ^~~~~~~~~~
bazel-out/k8-opt/bin/_virtual_includes/ray_util/ray/util/util.h:25:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
```
2. Expected behavior: build successfully
3. sysinfo
OS: ArchLinux
GCC: 11.1.0
Bazel: 4.2.0
Java: 11.0.12+7

### Reproduction script

N/A as this is a build issue

### Anything else

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jjyao** [comment]
Hi @acxz, what's the build command you used? I'm wondering why we didn't encounter this issue before.

**Comment by acxz** [comment]
Just a simple `python setup.py build`.

Reasons for why this may not be encountered could be because of the GCC version or maybe during a parallel build, a header file with the `<memory>` include gets included previously. Maybe from this file: https://github.com/ray-project/ray/blob/master/src/ray/util/logging.h#L56
