### ISSUE TITLE
[Bug] [Datasets] Ray Datasets metadata resolution very slow on large parquet dataset

### ISSUE THREAD

**Issue by isaac-vidas** [ray-project/ray#19089]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

When running batch predictions using Ray Datasets with ~4,000 files, 500MB each (~2TB overall), the process just waits for about 20-30 minutes before actually starting to run. During that time, nothing seems to be running on the cluster as there are no active workers on Ray.
It seems that the less files I'm using, the less time I have to wait before it starts running.
For example, if I'll run on 1,000 files instead, the process will only wait for ~7 minutes before starting to load the model on the workers and process the data.

While it's running, if I stop the process, it's usually stops around here:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
/tmp/ipykernel_330/1070400646.py in <module>
      4     file_paths,
      5     filesystem=fs,
----> 6     parallelism=parallelism
      7 ).pipeline(parallelism=parallelism)
      8 # ds = ds.map_batches(BatchInferModel, compute="actors", batch_size=256)

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/data/read_api.py in read_parquet(paths, filesystem, columns, parallelism, ray_remote_args, **arrow_parquet_args)
    219         columns=columns,
    220         ray_remote_args=ray_remote_args,
--> 221         **arrow_parquet_args)
    222 
    223 

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/data/read_api.py in read_datasource(datasource, parallelism, ray_remote_args, **read_args)
    149     """
    150 
--> 151     read_tasks = datasource.prepare_read(parallelism, **read_args)
    152 
    153     def remote_read(task: ReadTask) -> Block:

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/data/datasource/parquet_datasource.py in prepare_read(self, parallelism, paths, filesystem, columns, schema, **reader_args)
     76             if len(pieces) == 0:
     77                 continue
---> 78             metadata = _get_metadata(pieces, file_sizes, schema)
     79             pieces = [cloudpickle.dumps(p) for p in pieces]
     80             read_tasks.append(

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/data/datasource/parquet_datasource.py in _get_metadata(pieces, file_sizes, schema)
     90     for p in pieces:
     91         try:
---> 92             piece_metadata.append(p.metadata)
     93         except AttributeError:
     94             break

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/pyarrow/_dataset.pyx in pyarrow._dataset.ParquetFileFragment.metadata.__get__()

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/pyarrow/_dataset.pyx in pyarrow._dataset.ParquetFileFragment.ensure_complete_metadata()

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/pyarrow/_fs.pyx in pyarrow._fs._cb_open_input_file()

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/pyarrow/fs.py in open_input_file(self, path)
    316         from pyarrow import PythonFile
    317 
--> 318         if not self.fs.isfile(path):
    319             raise FileNotFoundError(path)
    320 

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/fsspec/asyn.py in wrapper(*args, **kwargs)
     89     def wrapper(*args, **kwargs):
     90         self = obj or args[0]
---> 91         return sync(self.loop, func, *args, **kwargs)
     92 
     93     return wrapper

/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/fsspec/asyn.py in sync(loop, func, timeout, *args, **kwargs)
     57     while True:
     58         # this loops allows thread to get interrupted
---> 59         if event.wait(1):
     60             break
     61         if timeout is not None:

/opt/miniconda/envs/product_classification/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554 

/opt/miniconda/envs/product_classification/lib/python3.7/threading.py in wait(self, timeout)
    298             else:
    299                 if timeout > 0:
--> 300                     gotit = waiter.acquire(True, timeout)
    301                 else:
    302                     gotit = waiter.acquire(False)

KeyboardInterrupt: 
```

### Reproduction script

```
import ray
import pandas as pd
from gcsfs import GCSFileSystem
from google.cloud import storage

ray.init("auto")

file_paths = get_list_of_files_from_gcs()

class BatchInferModel:
    def __init__(self):
        import tensorflow as tf
        from tensorflow import keras
        self.model_path = "<MODEL_PATH>"
        self.model = keras.models.load_model(self.model_path)
        self.signature = self.model.signatures["serving_default"]
        self.features = list(self.signature.structured_input_signature[1].keys())
    
    def __call__(self, batch) -> pd.DataFrame:
        import uuid
        import pandas as pd
        import numpy as np
        
        batch = batch.to_pandas()
        features = batch[self.features].to_dict(orient="series")
        X = {feature: np.array([x for x in series.values]) for feature, series in features.items()}
        predictions = self.model.predict(X)
        predictions_df = pd.DataFrame(predictions)
        # Writing output here until `ds.write_parquet()` will support GCS
        predictions_df.to_parquet("<OUTPUT_PATH>")
        return pd.DataFrame()

fs = GCSFileSystem()
parallelism = 400
ds = ray.data.read_parquet(
    file_paths, 
    filesystem=fs,
    parallelism=parallelism
).pipeline(parallelism=parallelism)
ds = ds.map_batches(BatchInferModel, batch_size=70000)

# Write to GCS doesn't work so we write the output during map_batch
# ds.write_parquet("<OUTPUT_PATH>", filesystem=fs)
ds.count()
```

### Anything else

Using Ray 1.6

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhe-thoughts** [comment]
Thanks for reporting this @isaac-vidas !

**Comment by ericl** [comment]
cc @clarkzinzow @scv119

**Comment by ericl** [comment]
Hmm based on the above stack trace (thanks for including it), I think we are bottlenecked on reading parquet metadata. 30 minutes for 4k files would amount to reading 2 metadata files a second, which is a bit slow but seems about right.

Probably the resolution is to resolve metadata in parallel with remote tasks, @clarkzinzow do you want to give that a try?

**Comment by isaac-vidas** [comment]
Additional info on this (perhaps this should be in a different issue?), once the pipeline starts working, plasma memory completely fills up. I tried different `batch_size` but it doesn't change what's happening with the plasma.
Also interesting, the Ray cluster has 855 workers and while running the dataset pipeline it has 929 workers (at least half are IDLE) while I defined `parallelism=400`
Is there a way to make sure plasma will not get to this condition while running the dataset pipeline?

See images for examples:
<img width="1788" alt="Screen Shot 2021-10-05 at 12 27 52 AM" src="https://user-images.githubusercontent.com/80056737/135963066-d505f01c-0ce6-4562-9cee-bbc04e5aa547.png">
<img width="1772" alt="Screen Shot 2021-10-05 at 12 50 13 AM" src="https://user-images.githubusercontent.com/80056737/135963114-2f12960b-ce1e-4f30-a17b-c4ef1d3d3769.png">
<img width="835" alt="Screen Shot 2021-10-05 at 12 50 52 AM" src="https://user-images.githubusercontent.com/80056737/135963134-726e73b5-e6aa-41ae-8188-f6da456717bd.png">

from `ray memory` on the head node:
```
--- Summary for node address: total_actor_handles ---
Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
18414008682.0 B      0, (0.0 B)        3, (18414008682.0 B)  0, (0.0 B)     0, (0.0 B)           0, (0.0 B)   

--- Object references for node address: total_actor_handles ---
IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref

10.15.71.2 | 164 | Worker | (deserialize task arg) ray.data.impl.compute._map_block | 6137881950.0 B | PINNED_IN_MEMORY | de00f8f96bf2abf3ffffffffffffffffffffffff0100000001000000


10.15.71.2 | 276 | Worker | (deserialize task arg) ray.data.impl.compute._map_block | 6138008471.0 B | PINNED_IN_MEMORY | 45c7189625060160ffffffffffffffffffffffff0100000001000000


10.15.71.2 | 163 | Worker | (deserialize task arg) ray.data.impl.compute._map_block | 6138118261.0 B | PINNED_IN_MEMORY | 49ed34679827eea0ffffffffffffffffffffffff0100000001000000



--- Aggregate object store stats across all nodes ---
Plasma memory usage 2341684 MiB, 407 objects, 133.8% full, 93.53% needed
Plasma filesystem mmap usage: 831668 MiB
Spilled 669558 MiB, 116 objects, avg write throughput 2420 MiB/s
Restored 35116 MiB, 6 objects, avg read throughput 129 MiB/s
Objects consumed by Ray tasks: 1932011 MiB.
Object fetches queued, waiting for available memory.
```

**Comment by scv119** [comment]
@isaac-vidas one thing interesting is
```
--- Aggregate object store stats across all nodes ---
Plasma memory usage 2341684 MiB, 407 objects, 133.8% full, 93.53% needed
```
indicates we only have 407 objects in the plasma store, which roughly matches the parallelism=400. This means each object is ~5753MiB in size, which is 10x more than what stored on Disk. 
Hmm, this could mean that the parquet file is heavily compressed. 
I'd suggest if we can try to reduce the parallelism to see if it reduces the overall memory usage.

**Comment by isaac-vidas** [comment]
@scv119 thanks for the info!
I can try reducing the parallelism. would reducing the parallelism affect the efficiency or the time it would take for the pipeline to run?

I thought that in this case the `batch_size` should do the trick because if we're reducing the batch_size, it would mean that the batch which is passing through the pipeline at a given time is smaller and so plasma store will be less full. Is that wrong?

**Comment by isaac-vidas** [comment]
Running another test at the moment with the same dataset (4,000 parquet files, 500MB each) on the same cluster (58 nodes, 870 workers) with the following dataset config:
```
parallelism=200
batch_size=50000
```

Started getting these errors:
```
2021-10-05 06:10:45,957	WARNING worker.py:1215 -- The node with node id: e462970bf6169c73e8d2cb268bae823f5a1f4a22d79cdbd8cbd86037 and ip: 10.15.54.2 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
(pid=9004, ip=10.15.5.131) Uploads 50000 to gcs
(pid=9004, ip=10.15.5.131) start 50000
2021-10-05 06:10:49,261	WARNING worker.py:1215 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 723, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 726, in ray._raylet.spill_objects_handler
  File "/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/external_storage.py", line 522, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/external_storage.py", line 278, in spill_objects
    owner_addresses, url)
  File "/opt/miniconda/envs/product_classification/lib/python3.7/site-packages/ray/external_storage.py", line 128, in _write_multiple_objects
    buf_len = len(buf)
TypeError: object of type 'NoneType' has no len()
An unexpected internal error occurred while the IO worker was spilling objects: object of type 'NoneType' has no len()
(raylet, ip=10.15.5.131) [2021-10-05 06:13:16,830 E 100 100] local_object_manager.cc:269: Failed to send object spilling request: IOError: 14: Socket closed
(raylet, ip=10.15.5.131) [2021-10-05 06:13:18,102 E 100 100] local_object_manager.cc:269: Failed to send object spilling request: IOError: 14: failed to connect to all addresses
(raylet, ip=10.15.5.131) [2021-10-05 06:13:18,103 E 100 100] local_object_manager.cc:269: Failed to send object spilling request: IOError: 14: failed to connect to all addresses
```

Dashboard (see the plasma difference on the different workers):
<img width="1769" alt="Screen Shot 2021-10-05 at 2 13 05 AM" src="https://user-images.githubusercontent.com/80056737/135970398-4a363dc8-a799-42e8-a0bf-8fa1c5e065b7.png">

`ray memory` not returning, so I might need to recreate the cluster and try again.

**Comment by scv119** [comment]
> I can try reducing the parallelism. would reducing the parallelism affect the efficiency or the time it would take for the pipeline to run?

Yeah in generally yes. However, if we reach a point the pipeline is stalled because of of object spilling, increase parallelism might not help even have negative effect.

> I thought that in this case the batch_size should do the trick because if we're reducing the batch_size, it would mean that the batch which is passing through the pipeline at a given time is smaller and so plasma store will be less full. Is that wrong?

The plasma store memory usage is dominated by two factors: 
1. working set size. This is controlled by the pipeline parallelism in our case.
2. read amplification, i.e. the number of copies of the same data.  a plasma object could be copied between nodes when the read_parquet and map_batches are running on the different Ray nodes. So the only way batch_size could affect plasma memory usage is it increases the probability of map_batches and read_parquet are running on different nodes. I guess this is unlikely in our case, as most of the case the batch_size is way smaller than the number of rows in a single plasma object (parquet_file), so most of the time we only need 1 or 2 copy of the plasma object (parquet_file).
