### ISSUE TITLE
[Bug] ray install-nightly does not work on MAC os

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#19104]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

when trying to install nightly using ray install-nightly, the command fails since the link to the nightly wheel on macOS is incorrect:

produced link:
`https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_13_intel.whl`

actual link to nightly:

`https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_15_intel.whl`

### Reproduction script

`ray install-nightly`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by matthewdeng** [comment]
This is fixed in https://github.com/ray-project/ray/pull/17973, which isn't included in the latest released version.
