### ISSUE TITLE
[Bug] [Regression] Dask on Ray large scale test fails with node failure

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#19136]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/1189#325affb3-c040-4e4e-8859-91d0a0740a14

This seems to happen after `db0483a29a0f78596c823f31a235001c44fad9ba` and is pretty consistent

### Reproduction script

Run the same test

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
(closed, reverted in master)
