### ISSUE TITLE
Unable to run tune getting started example in local_mode.

### ISSUE THREAD

**Issue by golanha** [ray-project/ray#19134]
I try to run the quick getting started example tune, in ray local mode:

```
import ray
from ray import tune



def objective(step, alpha, beta):
    return (0.1 + alpha * step / 100)**(-1) + beta * 0.1


def training_function(config):
    # Hyperparameters
    alpha, beta = config["alpha"], config["beta"]
    for step in range(10):
        # Iterative training function - can be any arbitrary training procedure.
        intermediate_score = objective(step, alpha, beta)
        # Feed the score back back to Tune.
        tune.report(mean_loss=intermediate_score)

ray.init(local_mode=True,num_gpus=1,num_cpus=1)
analysis = tune.run(
    training_function,
    config={
        "alpha": tune.grid_search([0.001, 0.01, 0.1]),
        "beta": tune.choice([1, 2, 3])
    })

print("Best config: ", analysis.get_best_config(
    metric="mean_loss", mode="min"))

# Get a dataframe for analyzing trial results.
df = analysis.results_df 
```
where I only added the line:
`ray.init(local_mode=True,num_gpus=1,num_cpus=1)`

I get the warning:
**"A Tune session already exists in the current process. If you are using ray.init(local_mode=True), you must set ray.init(..., num_cpus=1, num_gpus=1) to limit available concurrency."** Although I did run init as with the parameters required.
Only one trial be comes in running mode the rest are stuck in pending and the program hangs.
```
+-------------------------------+----------+-------+---------+--------+
| Trial name                    | status   | loc   |   alpha |   beta |
|-------------------------------+----------+-------+---------+--------|
| training_function_8a2ee_00000 | RUNNING  |       |   0.001 |      3 |
| training_function_8a2ee_00001 | PENDING  |       |   0.01  |      3 |
| training_function_8a2ee_00002 | PENDING  |       |   0.1   |      3 |
+-------------------------------+----------+-------+---------+--------+

```

**Comment by dennymarcels** [comment]
Can I ask this case to be reopen? I have the same issue. Since I am trying to implement some extra processing steps on the head node when tuning is completed, this problem won't let me finish the tuning process to get to the part of the code I need to work on. 

This issue only happens if I have requested more than one trial; if I request one single trial, the problem does not occur. For this reason I am quite convinced that there is some concurrency problem going on.
