### ISSUE TITLE
[Bug] Placement group causing Tune/RLlib to not schedule properly

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#19143]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

This may be a dup of #19130, but filing a separate issue to track anyways.

We are starting a Tune trial and requesting resources via PG and PG is not yet fully available. Autoscaler starts nodes that fulfills the request, but PG is never placed and never becomes “ready”.

@krfricke mentioned we can reliably reproduce the following:
* PG were still displayed as “pending” even though resources were available in cluster.
* No actors started even though they were pending.

This happened on OSS master. The output is similar to the problem shown in #19130
https://gist.github.com/richardliaw/2a620d0d2674115f4cbed90aaa86a1e4

### Reproduction script

from absl import app

import ray
from ray import tune
from ray.tune import CLIReporter

def main(unused_argv):
    ray.init(runtime_env={"working_dir": "."})

    # Defaults
    config = {
        # === Basics ===
        "env": "Pong-v0",
        "framework": "tf",
        "min_iter_time_s": 60,
        "num_gpus": 1,
        "num_gpus_per_worker": 0,
        "num_workers": 64,  # n2-standard-64
        "num_envs_per_worker": 4,
        "ignore_worker_failures": True,  # TODO(bkasper): Still helpful?

        # === Evaluation ===
        "evaluation_num_workers": 10, # 10,
        "evaluation_num_episodes": "auto",
        "evaluation_parallel_to_training": True,
        "evaluation_interval": 1,
        "evaluation_config": {
            "explore": False,
        },
    }

    results = tune.run(
        "APPO",
        config=config,
        stop={"time_total_s": 3600 * 12},
        num_samples=4,
        mode="max",
        verbose=1,
        progress_reporter=CLIReporter(
            metric_columns={
                "training_iteration": "iter",
                "time_total_s": "time_total_s",
                "timesteps_total": "ts",
                "snapshots": "snapshots",
                "info/learner_queue/size_mean": "learner_queue_mean",
                "episodes_this_iter": "train_episodes",
                # "policy_reward_mean/main_agent": "train_winrate",
                "evaluation/episodes_this_iter": "eval_episodes",
                #"evaluation/policy_reward_mean/main_agent": "eval_winrate",
            },
            sort_by_metric=True,
            max_report_frequency=30,
        ),
        callbacks=[],
    )

    results.results_df.to_csv("results.csv")

if __name__ == "__main__":
    app.run(main)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
@gjoliver so all the fixes have been merged into the master. Is it possible for you to verify if this is still reproduced in the master?

**Comment by gjoliver** [comment]
ok, I will verify using a nightly wheel and let you know.
thanks for the fix Sang!

**Comment by rkooo567** [comment]
Thanks for verifying this :)!!!
