### ISSUE TITLE
[Serve] Move _blocking to deployment options

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19155]
Currently user can do `DeploymentClass.deploy(_blocking=False)` to make the call returns a goal_id. This is not very clean and confusing. We should have a design to make to this part of DeploymentClass.options(return_blocking=False).deploy().

**Comment by iasoon** [comment]
Personally I feel the current way is cleaner than the proposed solution. As I see it, `_blocking` is a setting for how the `deploy` method should happen, as opposed to `options`, which changes the properties for the actual deployment.
