### ISSUE TITLE
[autoscaler] Support Sync-only Command

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1917]
### Describe the problem
Sometimes, I'll edit files locally, and I want to remount all the directories without running `create_or_update` which is a little time consuming. Running rsync myself is annoying because 
1. I want mounting on all nodes
2. Figuring out the right rsync command and typing it is a huge pain

One possible API would be `ray sync [-y] [cluster.yaml]`

**Comment by robertnishihara** [comment]
This would be really useful.

**Comment by richardliaw** [comment]
Addressed in #2678.
