### ISSUE TITLE
[Windows] Reenable test_basic* on windows

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#19177]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We should reenable all the basic tests on windows. Currently they're disabled. Some individual tests are disabled via @pytest.skipif. Those can be found with this query: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+file:test_basic*+sys.platform&patternType=regexp&case=yes

We're also skipping all of `test_basic_{2, 3}`. (entirely skipped test suites can be found here: https://github.com/ray-project/ray/blob/master/ci/travis/ci.sh#L155) 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pcmoritz** [comment]
I'm trying to reactivate the last remaining small bits here: https://github.com/ray-project/ray/pull/21273

**Comment by pcmoritz** [comment]
This is now done
