### ISSUE TITLE
[Bug] [CPP] cpp api doesn't work on windows

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#19189]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When I install the cpp wheel on windows, I realized that we still have libray_api.so instead of dll.

### Reproduction script

pip install ray[cpp]

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SongGuyang** [comment]
Keep the issue open.
