### ISSUE TITLE
[Bug] [Tune] Checkpoint not found after successful sync down

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#19192]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

When checkpointing is enabled for a Tune job on product, we see regular exceptions like:

2021-10-07 11:08:51,576	ERROR trial_runner.py:1014 -- Trial APPO_CartPole-v1_70ab3_00000: Error handling checkpoint /home/ray/ray_results/resume-test/APPO_CartPole-v1_70ab3_00000_0_2021-10-07_11-07-31/checkpoint_000002/checkpoint-2
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 1009, in _process_trial_save
    checkpoint=trial.saving_to)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/callback.py", line 259, in on_checkpoint
    callback.on_checkpoint(**info)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 457, in on_checkpoint
    self._sync_trial_checkpoint(trial, checkpoint)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 432, in _sync_trial_checkpoint
    trial, checkpoint.value))
ray.tune.error.TuneError: Trial APPO_CartPole-v1_70ab3_00000: Checkpoint path /home/ray/ray_results/resume-test/APPO_CartPole-v1_70ab3_00000_0_2021-10-07_11-07-31/checkpoint_000002/checkpoint-2 not found after successful sync down.

This can be reliably reproduced on GCP cloud.

### Reproduction script

# Standard Library
from datetime import datetime
import functools
import pickle
import pprint
import random

# Third Party
import numpy as np
import ray

from ray import tune
from ray.tune import CLIReporter

EXP_NAME = "tune-test"

def main():
    ray.init(address="auto")

    # Defaults
    config = {
        # === Basics ===
        "env": "CartPole-v1",
        "framework": "tf2",
        "eager_tracing": True,
        "min_iter_time_s": 60,
        "num_gpus": 0,
        "num_gpus_per_worker": 0,
        "num_workers": 1,
        "num_envs_per_worker": 2,
        "ignore_worker_failures": True,
        # === Learning ===
        "batch_mode": "complete_episodes",
        "rollout_fragment_length": 32,
        "train_batch_size": 1024,
        "gamma": 1.0,
        "lr": 1e-4,
        "vf_loss_coeff": 0.25,
        "entropy_coeff": 0.001,
        # === Evaluation ===
        "evaluation_num_workers": 1,
        "evaluation_num_episodes": "auto",
        "evaluation_parallel_to_training": True,
        "evaluation_interval": 1,
        "evaluation_config": {
            "explore": False,
        },
    }

    results = tune.run(
        tune.durable("APPO"),
        name=EXP_NAME,
        config=config,
        checkpoint_freq=2,
        checkpoint_at_end=True,
        sync_config=tune.SyncConfig(
            sync_to_driver=False,
            sync_on_checkpoint=True,
            upload_dir=<gcp bucket here>,
        ),
        max_failures=-1,
        num_samples=4,
        stop={"time_total_s": 3600 * 12},
        verbose=1,
        progress_reporter=CLIReporter(
            metric_columns={
                "training_iteration": "iter",
                "time_total_s": "time_total_s",
                "timesteps_total": "ts",
                "snapshots": "snapshots",
                "info/learner_queue/size_mean": "learner_queue_mean",
                "episodes_this_iter": "train_episodes",
                "evaluation/episodes_this_iter": "eval_episodes",
            },
            sort_by_metric=True,
            max_report_frequency=30,
        ),
    )

    print(f"Best hyperparameters were: {pprint.pformat(results.best_config)}")

    results.results_df.to_csv("results.csv")

if __name__ == "__main__":
    main()

### Anything else

ping @gjoliver for the cluster env and gcs setup for reproducing.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
After #19589 is merged I'll make sure that K8s syncing works without durable trainables.

**Comment by krfricke** [comment]
This should have been fixed by recent fixes to the GCP cloud syncing release tests (e.g. #24015, #24008, #23804)
