### ISSUE TITLE
[Release Tests] Cluster startup failure is not acknowledged

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#19228]
## Issue
When the cluster startup fails, the error is not communicated to the `e2e` script. The `e2e` script will execute the next step (as if the startup succeeded) and only then run into a `"No active cluster matching pattern {} found"` error.

### Logs
```
[INFO 2021-10-07 11:27:13,284] e2e.py: 1412  Syncing files to session...
--
  | [ERROR 2021-10-07 11:27:14,374] e2e.py: 1514  No active cluster matching pattern train_small_1633630177 found
  | Traceback (most recent call last):
  | File "release/e2e.py", line 1418, in _run
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/controllers/session_controller.py", line 720, in push
  | session = get_project_session(project_id, session_name, self.api_client)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/project.py", line 148, in get_project_session
  | sessions = get_project_sessions(project_id, session_name, api_client)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/anyscale/project.py", line 123, in get_project_sessions
  | "No active cluster matching pattern {} found".format(session_name)
  | click.exceptions.ClickException: No active cluster matching pattern train_small_1633630177 found
```

## Examples
| Test  | Session |
| ------------- | ------------- |
| [train_small](https://buildkite.com/ray-project/periodic-ci/builds/1194#3fc86edc-6fff-45aa-9ad2-7d5cd329a3e7)  | [train_small_1633630177](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_b5xsqfixff2HecLza4jcDH7i)  |
| [tune_small](https://buildkite.com/ray-project/periodic-ci/builds/1194#36040f28-edc5-452b-8b3c-82fe8978116d)  | [tune_small_1633630177](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_gYVNHQy2qdw57mH5sG9gMZBK)  |
| [ft_small_non_elastic](https://buildkite.com/ray-project/periodic-ci/builds/1194#f64e4cde-623e-48de-a7e0-55aaecfbfd72)  | [ft_small_non_elastic_1633630182](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_WSGNN2qJ91r1YTfjujB7qTX3)  |
| [learning_tests](https://buildkite.com/ray-project/periodic-ci/builds/1194#36995719-954e-4bd4-a4f5-3316460b21de)  | [learning_tests_1633630205](https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_MrrLVQZGZyhpn1x54W59tg5x)  |

**Comment by xwjiang2010** [comment]
cc @yifeif @alanwguo @allenyin55 @jjyao

**Comment by xwjiang2010** [comment]
Slightly two different issues under the hood:
1. cluster startup takes too long.
2. e2e.py blindly assumes that startup succeeds and proceeds.
