### ISSUE TITLE
[Bug] I can’t resume training

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19240]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

https://discuss.ray.io/t/i-cant-resume-training/3760

I can’t resume training. Say I run python egt_node_gat.py --framework torch --stop-iters 500 --stop-reward 1 and it reaches iter 500 and stops.

Now I want to keep training further so I run the script again with a higher --stop-iters, but this time with resume="PROMPT" in tune.run.

and it terminates immediately
Number of trials: 1/1 (1 TERMINATED)

Should I be doing anything differently?

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aploium** [comment]
Hello, did you solved this finally? I encountered the same scene as you.
I set an `time_budget_s`, so my tune stopped after that, but want to continue for more time.
