### ISSUE TITLE
[rllib] Reproduce IMPALA algorithm

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#1924]
### Describe the problem

https://deepmind.com/blog/impala-scalable-distributed-deeprl-dmlab-30/

The high-level IMPALA architecture is similar to Ape-X except without the replay buffer. Some key features:
- V-trace
- use of LSTMs
- use of deep residual network
- multi-gpu support (allreduce)

**Comment by richardliaw** [comment]
cc: @joneswong
