### ISSUE TITLE
Add more in-depth tutorial

### ISSUE THREAD

**Issue by triciasfu** [ray-project/ray#19250]
### Description

Add more in-depth tutorial in the Ray Serve docs that is more realistic than a Counter example

**Comment by simon-mo** [comment]
- [ ] Serve actual ML model
- [ ] Best practice
- [ ] How to hit the endpoint realistically via HTTP and Python
- [ ] Scaling out
- [ ] Updating code
- [ ] OpenAPI link
- [ ] Composition?
