### ISSUE TITLE
Add documentation to clarify: ray.init, serve.start, serve.connect, detached and namespaces

### ISSUE THREAD

**Issue by triciasfu** [ray-project/ray#19257]
### Description

Clarify the interaction between Ray.init and serve.start() and serve.connect(). Also detached and namespaces.

**Comment by simon-mo** [comment]
Rewrite of https://docs.ray.io/en/latest/serve/deployment.html#lifetime-of-a-ray-serve-instance

convert it to a top level "serve concepts"

- deployment
- detached
- serve.start
- namespaces and how serve relates to namespaces
- ray init and how serve relates to
