### ISSUE TITLE
Update structure of Serve documentation

### ISSUE THREAD

**Issue by triciasfu** [ray-project/ray#19252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

One proposal:

- Ray Serve Overview
- Hello World example
- Converting existing application via Fast API
-- Deployment options - # of actors, # of GPUs
- Deploying Ray Serve 
-- Locally
--- How to query your endpoint
-- On another cloud provider
-- On Anyscale
--- Link out to Anyscale docs
--- How to query your endpoint
- Updating Ray Serve Deployment
- Production
-- Anyscale CI/CD
-- Services
- Logging and Monitoring
- Serve Architecture
- Advanced tutorials
-- Types of ML model serving: Request Batching & Model Composition
-- Existing Advanced Tutorials
-- ...

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
Dup of #19253
