### ISSUE TITLE
[nit] Improve error message for list deployments

### ISSUE THREAD

**Issue by triciasfu** [ray-project/ray#19258]
### Description

Improve error message: 
List deployments throws the following error:
RayServeException: Called `serve.connect()` but there is no instance running on this Ray cluster. Please call `serve.start(detached=True) to start one.

**Comment by simon-mo** [comment]
What's the right error message here? This error is thrown when Serve cannot find a detached instance and working as intended here.

To add clarify, how about:

RayServeException: You are trying to connect to a detached Serve instance. However Ray Serve cannot find one right now. If you have a Serve cluster running, make sure it's started with `serve.start(detached=True)` so it's accessible from other drive program. If you would like to start a Serve cluster, you can run `serve.start()` for a ephemeral instance and `serve.start(detached=True)` for instance that persist after script exits.
