### ISSUE TITLE
[Bug/tune] Rllib register_all re-overwrites overwritten trainables

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#19267]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Follow-up to https://github.com/ray-project/ray/pull/19223

The reason why this lead to errors previously was the following:

- `tune.durable("PPO")` (or any other string) overwrites the registered trainable for "PPO" globally with the durable version
- Starting a trainable on a remote node re-imports rllib
- Importing rllib triggers `_register_all()` - overwriting the "PPO" trainable again with the original version!
- Subsequent trial startups hence start up the non-durable version of PPO

Renaming the durable string as in https://github.com/ray-project/ray/pull/19223 fixes the problem, but only on a surface level. We should revise the register process, e.g. make sure we only register once (e.g. keep as state in the KV store).

### Reproduction script

Start a cluster with at least 3 nodes a 4 CPUs each (I used docker-compose to do this).

Undo change introduced in #19223

Run this script:

```
import time
from ray.tune.durable_trainable import durable
from ray.tune.trial import Trial
from ray.tune.experiment import Experiment

import ray

ray.init(address="auto")


from ray.tune.ray_trial_executor import RayTrialExecutor

trainable = durable("PPO")
name = Experiment.register_if_needed(trainable)

executor = RayTrialExecutor()

config = {"num_workers": 1, "num_gpus": 0, "evaluation_num_workers": 2}

trial1 = Trial(name, config=config)
trial2 = Trial(name, config=config)
trial3 = Trial(name, config=config)

executor.stage_and_update_status([trial1, trial2, trial3])


def _start(trial):
    print(trial)
    while not executor.start_trial(trial):
        time.sleep(1)


_start(trial1)
print("SCHEDULED")
print(trial1.get_trainable_cls())


_start(trial2)
print("SCHEDULED")
print(trial2.get_trainable_cls())

time.sleep(2)

_start(trial3)
print("SCHEDULED")
print(trial3.get_trainable_cls())
```

Truncated output:

```
PPO_cd9f1524
SCHEDULED
<class 'ray.tune.durable_trainable.durable.<locals>._WrappedDurableTrainable'>
PPO_cd9fb65a
SCHEDULED
<class 'ray.tune.durable_trainable.durable.<locals>._WrappedDurableTrainable'>
PPO_cda03ab2
SCHEDULED
<class 'ray.rllib.agents.trainer_template.PPO'>
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
I'm closing this issue. I'm pretty sure we already fixed this in RLlib some time ago (along moving the Bandits from contrib into the main `agents` folder). RLlib does not - anywhere in its code - call `_register_all()` anymore.
