### ISSUE TITLE
Installation hangs while running python setup.py build

### ISSUE THREAD

**Issue by kanaadp** [ray-project/ray#1926]
### System information
- **OSX**:
- **Installing most recent version through source**:
- **Ray 0.4.0 (aa07f1ce4e0cfc4ba7bd0b466d77522360910b68)**:
- **Python version 3.6.5**:
- ** pip install -epip install -e . **:

### Describe the problem
Trying to install Ray hangs when running the command: "/Users/kanaad/miniconda3/envs/ray/bin/python setup.py build"

(I have installed ray before, but I was reinstalling and ran into this issue. I've followed the setup instructions on [here](http://ray.readthedocs.io/en/latest/installation.html).

### Source code / logs
Here's the log from the set-up script. Thanks!
[output-log.txt](https://github.com/ray-project/ray/files/1930361/output-log.txt)

**Comment by robertnishihara** [comment]
Hmm.. sometimes if you build Ray and then do a `git pull` and then rebuild it causes problems. Can you try doing the following from the `ray/` directory?

First clear out some old files

```
rm -rf python/ray/core
rm -rf python/ray/pyarrow_files
rm -rf thirdparty/build/arrow
rm -rf thirdparty/pkg/arrow
rm -rf thirdparty/build/parquet-cpp

git checkout python/ray/core
git checkout python/ray/pyarrow_files
```

Rebuild

```
cd python
pip install -e . --verbose
```

**Comment by robertnishihara** [comment]
Closing because this is likely outdated.
