### ISSUE TITLE
[Core][usability] Improving error messages 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#19271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Improve error message when Ray running large-scale actors use case.  
https://anyscaleteam.slack.com/archives/C027L220V0V/p1633653933187600?thread_ts=1633581002.181700&cid=C027L220V0V

### Use case

TBD

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@richardliaw can you add a bit context here? thanks :)

**Comment by rkooo567** [comment]
duplicated from https://github.com/ray-project/ray/issues/20534
