### ISSUE TITLE
[Bug] Build of `master` failing on Linux

### ISSUE THREAD

**Issue by czgdp1807** [ray-project/ray#19283]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

The following command,

`bazel build //:ray_pkg`

failed with the following error in `master` (commit - ab55b808c56f9e23af575fa1),
```
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
src/ray/object_manager/object_buffer_pool.cc: In destructor ‘ray::ObjectBufferPool::~ObjectBufferPool()’:
src/ray/object_manager/object_buffer_pool.cc:34:33: error: unused variable ‘id’ [-Werror=unused-variable]
   for (const auto &[id, cond_var] : inflight_ops) {
                                 ^
cc1plus: all warnings being treated as errors
Target //:ray_pkg failed to build
```

### Reproduction script

`bazel build //:ray_pkg`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
@czgdp1807 Is this still an issue? I think more recent compilers will be a bit more lenient here because there is no way to ignore a variable for structured binding here. I can definitely make a fix too.

**Comment by czgdp1807** [comment]
It’s been quite sometime since I ran a build on Linux. AFAIK, if the above line is fixed then it should be working. I can tell you by Tuesday whether this needs a fix.

**Comment by mwtian** [comment]
Sounds good. Ray's Linux CI has been passing. When you try it again and if it fails, please let me know the system and compiler versions, thanks!

**Comment by czgdp1807** [comment]
On latest `master` I get the following,

```cpp
Use --sandbox_debug to see verbose messages from the sandbox
In file included from src/ray/util/util.cc:33:0:
bazel-out/k8-opt/bin/_virtual_includes/ray_util/ray/util/filesystem.h:17:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Target //:ray_pkg failed to build
INFO: Elapsed time: 230.284s, Critical Path: 23.96s
INFO: 2117 processes: 1100 internal, 1017 linux-sandbox.
FAILED: Build did NOT complete successfully
```

Compilers

1. `g++`
```cpp
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
2. `gcc`
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by rkooo567** [comment]
Must be due to this PR https://github.com/ray-project/ray/pull/18941 I think this requires the gcc version >= 9

**Comment by chenk008** [comment]
Maybe we should add some gcc version check in `setup.py`

**Comment by rkooo567** [comment]
Yeah can we do this? Also cc @mwtian

**Comment by chenk008** [comment]
I have upgrade to gcc 9, there is still some error:
```
bazel-out/host/bin/external/com_github_google_flatbuffers/_objs/flatc_library/idl_parser.o:idl_parser.cpp:function flatbuffers::Parser::Next(): error: undefined reference to 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
```

**Comment by aslonnie** [comment]
issue is out of date
