### ISSUE TITLE
[Nightly] train_small timeout. Stuck in `Waiting until actors are ready` for more than 60seconds

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19305]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

train_small is timing out. Most notably `waiting untill actors are ready` takes more than 60s. This is after `wait_cluster` is done so no more autoscaling should be happening.
Happens both in the case using ray client and not.

```
[INFO 2021-10-10 11:23:56,465] e2e.py: 825  Starting job train_small_1633889125 with Ray address: anyscale://train_small_1633889125?autosuspend=10
--
  | (pid=1279) 2021-10-10 11:24:23,274	INFO main.py:913 -- [RayXGBoost] Created 4 new actors (4 total actors). Waiting until actors are ready for training.
  | The actor or task with ID ffffffffffffffff625c288d32dc2a41fdedf2a402000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
  | Required resources for this actor or task: {CPU_group_cda3ad2861590c44996ec6a82e0b2cfc: 4.000000}
  | Available resources on this node: {0.000000/4.000000 CPU, 587202559.960938 GiB/587202559.960938 GiB memory, 233156159.960938 GiB/233156159.960938 GiB object_store_memory, 0.000000/4.000000 CPU_group_cda3ad2861590c44996ec6a82e0b2cfc, 1.000000/1.000000 node:172.31.120.249, 1000.000000/1000.000000 bundle_group_2_cda3ad2861590c44996ec6a82e0b2cfc, 1000.000000/1000.000000 bundle_group_cda3ad2861590c44996ec6a82e0b2cfc, 4.000000/4.000000 CPU_group_2_cda3ad2861590c44996ec6a82e0b2cfc}
  | In total there are 0 pending tasks and 1 pending actors on this node.
  | (pid=1279) 2021-10-10 11:24:53,302	INFO main.py:947 -- Waiting until actors are ready (30 seconds passed).
  | (pid=1279) 2021-10-10 11:25:23,375	INFO main.py:947 -- Waiting until actors are ready (60 seconds passed).
  | (pid=1279) 2021-10-10 11:25:36,855	INFO main.py:958 -- [RayXGBoost] Starting XGBoost training.
```

Link: https://buildkite.com/ray-project/periodic-ci/builds/1209#49028e00-affd-404f-b2b3-7309a875787b

### Reproduction script

Nightly release test

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@krfricke @matthewdeng

**Comment by ckw017** [comment]
Hm, afaik client itself shouldn't introduce that kind of delay to schedule an actor ("The actor or task with ID ffffffffffffffff625c288d32dc2a41fdedf2a402000000 cannot be scheduled right now" is coming from core, so the client has already tried to schedule the actor at this point). Do you know what the differences between use_connect=True vs. False are? I'm guessing True will do something like ray.init(anyscale://..., ...). How does use_connect=False work (where and how does it run)?

**Comment by xwjiang2010** [comment]
`use_connect=False` case uses `ray.init(address="auto")`.
It's run [here](https://sourcegraph.com/github.com/ray-project/ray/-/blob/release/xgboost_tests/workloads/train_small.py?L25).
`use_connect` sets RAY_ADDRESS env variable in e2e.py and that in turn decides which ray.init() to invoke.

 I also can't connect the dots as to how ray client may introduce the scheduling error. But it appears that for this test this error only shows up when using ray client (everything else kept the same) and causes test to timeout. I was thinking maybe scheduling logic behave differently? At the end of the day, using ray client means driver process and head node are separated and that is one more hop (?) for scheduling?

**Comment by xwjiang2010** [comment]
@scv119 @rkooo567 from Core side.

**Comment by xwjiang2010** [comment]
> Also, is this an ongoing issue or did it start becoming a problem recently? I think we've had a few autoscaler changes in the past few weeks.

I think the issue has always been there since Day 1 we switch to use_connect for some of our tests. 
One thing I want to point out is from the test log, autoscaling is already complete - i.e. we have already reached the number of worker nodes that we want. (wait_cluster.py is done successfully) So I don't think there should be further autoscaling. Hence the actor scheduling error msg is strange to me.

![Screen Shot 2021-10-12 at 3 04 51 PM](https://user-images.githubusercontent.com/87673679/137035517-d031ef73-bc96-4481-9353-066c4296c5b5.png)

**Comment by ckw017** [comment]
After some digging it looks like that probably isn't the issue

**Comment by rkooo567** [comment]
@scv119 how long did it take to propagate? Also when you day “resources are propagated”, does that include pg creation time?

**Comment by rkooo567** [comment]
So, to be clear, this is not stuck, but this is slower right?

**Comment by rkooo567** [comment]
NOTE: This has been deprioritized by other tasks, but we are planning to look at in next 3 weeks.

**Comment by rkooo567** [comment]
> Yes, I started tracking this test just before 1.8.0 release branch cut. At that time, it was just flaky. Now it's consistently failing every day.

Btw, how is the 45 seconds defined? What's the average time that when it is passing?

**Comment by xwjiang2010** [comment]
@krfricke may have better context. I remember being told that it used to take ~20 seconds.
