### ISSUE TITLE
[train] Better TF Autosharding Usability 

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#19324]
To use Ray Datasets properly with Ray SGD and Tensorflow MultiWorkerMirroredStrategy, TF autosharding needs to be disabled. Currently, this is left to the user to handle, but SGD should handle this internally.

**Comment by jwyyy** [comment]
Hi @amogkam, is anyone working on this issue? If no, I would like to take a look. Thanks!

**Comment by jwyyy** [comment]
Hi @matthewdeng @amogkam, I studied this issue a little bit. It seems we can have a simple fix. Currently I have two ideas in my mind. Please let me know which one looks good to you. 

1. We can turn off autosharding inside [`to_tf()`](https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L2002-L2066). The implementation should be straightforward, as the return object is already a TF dataset. But I am not sure if this affects the current usage of`to_tf()` in other cases.
2. Alternatively, we can temporarily turn off autosharding by patching a modified version of `to_tf()` inside [`get_dataset_shard()`](https://github.com/ray-project/ray/blob/master/python/ray/train/session.py#L298-L305), something like
```python
original_to_tf = shard.to_tf
def new_to_tf(self, other_args):
    # call the original to_tf()
    # turn off autosharding
shard.to_tf = types.MethodType(new_to_tf, shard)
```
This doesn't affect other Ray Dataset objects.

Also we can give a user warning if autosharding is on. Please let me know your comments. I will work on the implementation once I collect your feedback. Thanks!

**Comment by amogkam** [comment]
Hey @jwyyy, thanks for looking into this!

We originally had option 1, but decided that it didn't really make sense to have this directly in Ray Datasets. I think option 2 would work well here instead!

cc @matthewdeng for thoughts.

**Comment by matthewdeng** [comment]
What about providing a utility function (e.g. `train.tensorflow.prepare_dataset_shard`) so that it is more explicit to the user what is happening?

**Comment by amogkam** [comment]
I would actually prefer doing this automatically with an option to disable. Is there a use case when you would not want this? We can show a log message saying that this is happening so that it is clear to the user.

**Comment by jwyyy** [comment]
> What about providing a utility function (e.g. `train.tensorflow.prepare_dataset_shard`) so that it is more explicit to the user what is happening?

Hi @matthewdeng, thank you for your suggestion! Can you be more specific on the behaviors of the proposed utility function? `train.torch.prepare_dataset()` takes a torch dataset. (I guess `train.tensorflow.prepare_dataset_shard` is expected to take a something like TF dataset to be consistent?) Here I think @amogkam meant turning off autosharding when a TF Dataset returned from a Ray Dataset.

**Comment by matthewdeng** [comment]
Ah in my mind we would just move [this](https://github.com/ray-project/ray/blob/master/python/ray/train/examples/tensorflow_linear_dataset_example.py#L34-L41) into a util function.  

I'm not sure if there are any cases where the user _wouldn't_ want this done automatically, but my hesitancy comes from the fact that this is implicit to the user and doesn't appear to be configurable if they ever did want to disable it?

With that said, I'm not strongly opposed to this behavior if it's documented well in the user guide (since it overrides the behavior of `Dataset.to_tf`) or if there's a way the user can disable it.

**Comment by jwyyy** [comment]
Can we do the following ?
```python
def get_dataset_shard(dataset_name, autoshard_off = True):
    # do stuff
    original_to_tf = shard.to_tf
    def new_to_tf(self, other_args):
        # call the original to_tf()
        if autoshard_off:
            # turn off autosharding
    shard.to_tf = types.MethodType(new_to_tf, shard)
    # do stuff
```
It adds an extra argument in the `get_dataset_shard()` method, but it also gives users an option to turn it on / off.

**Comment by matthewdeng** [comment]
Yeah, that actually seems like a good compromise! Perhaps we can make this more specific to `to_tf` by naming it `tf_autoshard_off` since we don't need the same logic for `to_torch`.

**Comment by jwyyy** [comment]
Sounds good! I will do the implementation and add related doc 😄  Thanks!

**Comment by jwyyy** [comment]
Hi @matthewdeng @amogkam, the overriding approach does not fully resolve the issue. `get_dataset_shard()` may return a DatasetPipeline which does not have `to_tf()` method. A TF dataset is obtained by calling `next()` as shown in the [example](https://github.com/ray-project/ray/blob/master/python/ray/train/examples/tensorflow_linear_dataset_example.py#L73). We could override the native iterable method and turn off the autosharding there. But not sure if it is what we want. (It soon becomes complicated.) What are your thoughts?

**Comment by matthewdeng** [comment]
Ah, that's right... good catch. I think handling only Datasets or overriding the iterable method will more than likely end up leading to unintended behavior down the line.

The utility method can be a reasonable stop-gap until a better solution is discovered, if @amogkam is okay with it! 😄

**Comment by amogkam** [comment]
yep a utility function sounds good to me! What do you guys think about `train.tensorflow.prepare_dataset_shard`?

**Comment by jwyyy** [comment]
> yep a utility function sounds good to me! What do you guys think about `train.tensorflow.prepare_dataset_shard` that accepts a tf Dataset?

Adding `train.tensorflow.prepare_dataset_shard()` agrees with @matthewdeng's previous suggestion. At the same time, we can revise the warning to remind users of using this method when they use TF datasets. An TF example is helpful (although it should be straightforward).
