### ISSUE TITLE
Error when using hugepages on the amazon deep learning AMI (Python 2).

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#1933]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: The Amazon deep learning AMI (version 7) `ami-c91677b1` in us-west-2.
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.4.0
- **Python version**: 2.7

I set up hugepages using the instructions at http://ray.readthedocs.io/en/latest/plasma-object-store.html#using-plasma-with-huge-pages.

First `source activate tensorflow_p27`.

Then I do

```python
import ray
import numpy as np

ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")

x = np.ones(10 ** 8, dtype=np.uint8)

ray.put(x)
```

The last line fails with

```
---------------------------------------------------------------------------
ArrowIOError                              Traceback (most recent call last)
plasma.pyx in pyarrow.plasma.PlasmaClient.release()

error.pxi in pyarrow.lib.check_status()

ArrowIOError: Error during munmap
Exception pyarrow.lib.ArrowIOError: ArrowIOError('Error during munmap',) in 'pyarrow.plasma.PlasmaBuffer.__dealloc__' ignored
Out[3]: ObjectID(d9c4a702f8faf11e9742dab081c62f7ec1d09e14)
```

**Comment by mitar** [comment]
Probably memory not aligned. [Here it is written](https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt):

> Syscalls that operate on memory backed by hugetlb pages only have their lengths aligned to the native page size of the processor; they will normally fail with errno set to EINVAL or exclude hugetlb pages that extend beyond the length if not hugepage aligned.  For example, munmap(2) will fail if memory is backed by a hugetlb page and the length is smaller than the hugepage size

**Comment by atumanov** [comment]
actually, it's been known to work on the `tensorflow_p27` environment. I created a working AMI for @ericl and @richardliaw with hugepages enabled. If that AMI still exists, we should double check and close this issue.

**Comment by edoakes** [comment]
Python 2 no longer supported
