### ISSUE TITLE
[xray] get_gpu_ids returns empty list

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1938]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 p3.16x
- **Ray installed from (source or binary)**: Binary (https://github.com/richardliaw/ray/commit/8aaf7efa310776dc7c8d6b235352273fd149a938) which is very similar to master
- **Python version**: 2.7
- **Exact command to reproduce**: ray.get_gpu_ids() on `ray start --head --use-raylet`

### Describe the problem
Need `get_gpu_ids()`/resources in x-ray.

**Comment by atumanov** [comment]
Good point. We don't have this supported in raylet nodemanager at the moment.

**Comment by robertnishihara** [comment]
This has been fixed.
