### ISSUE TITLE
[Feature] [C++ API] add nightly test

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#19382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Add nightly test for C++ API.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
I'm probably not the right person to look into this.

Maybe @rkooo567 - do you know if we have something like this already?

**Comment by rkooo567** [comment]
I think we can skip th is for now
