### ISSUE TITLE
[Bug] Autoscaler monitor log was included the dashboard worker logs.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19389]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

If you have an autoscaling cluster launched using ray cluster launcher, the monitor.log is rendered as part of the node's log section. However, because the log is appended every 5s, it will cause the dashboard broken. 

### Versions / Dependencies

Nightly

### Reproduction script

ray up...

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This is fixed by https://github.com/ray-project/ray/pull/19385
