### ISSUE TITLE
[xray] GPU placement unusable for Actors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#1940]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 (2 p3.8xlarges)
- **Ray installed from (source or binary)**: binary
- **Ray version**: 
- **Python version**: 2.7
### Describe the problem
Need actor GPU placement but when specified, the actors hang.
### Source code / logs
```
import ray

class Actor(object):
    def __init__(self):
        self.x = 1
    def result(self):
        return 123

ray.init(redis_address="localhost:6379", use_raylet=True)
Actor = ray.remote(num_gpus=4)(Actor)
actors = [Actor.remote() for i in range(2)]
results = [a.result.remote() for a in actors]
print(ray.get(results))
```
cc: @atumanov

**Comment by pcmoritz** [comment]
I can reproduce this on the latest master, starting the raylet with

```
ray start --head --num-gpus 4 --use-raylet
```

**Comment by robertnishihara** [comment]
Pretty sure this has been fixed.
