### ISSUE TITLE
[Dataset] allow additional transformation on the data after fetching the batch 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#19421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Sometimes users to do some additional transformation on the data after fetching the batch. 
[In one case](https://github.com/ludwig-ai/ludwig/pull/1391/files#diff-db32a4692043fdf9957a872263f752a913c3cbb84a76ddaafa3c8dff6e2b5307R161), it's just taking the list of rows and stacking them into a numpy array.
maybe this can be pushed into the pipeline so it can be done in parallel (right now most cpus are idle because the training is single threaded)
something like batch -> map -> iterate

### Use case

dataset

### Related issues

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Hmm yeah I think you should transform before calling iter_batches(). I think having a post-transform API would be pretty confusing / difficult to implement in a performant way.
