### ISSUE TITLE
[Bug] [Workflow] Workflow.resume of a nonexistent workflow has side effects

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#19481]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

When calling `workflow.resume` on a non-existent workflow, we should error, but not create side effects. 

### Versions / Dependencies

Master

### Reproduction script

```
from ray import workflow

workflow.init()

with pytest.raises(Exception):
    workflow.resume("doesnt_exist")

assert workflow.list_all() == [], "Shouldn't list the resume that didn't work"
```

### Anything else

Caused by this line: https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/workflow/workflow_access.py?L174:18

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
@suquark can you help verify this to make sure it's not happening any more? If so, close this.
