### ISSUE TITLE
[Bug] Slow serialization on numpy view

### ISSUE THREAD

**Issue by ArnaudReminiz** [ray-project/ray#19547]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have encountered degraded performances on ray.put calls when serializing a numpy view on an array as for example produced by a `numpy.flip` operation. The call is slower than copying the whole array and then calling ray.put. 

This is not a bug per say, but it is not present in the documentation, and represent a big performance hit if not addressed by the user. It may also be easily corrected in the serialization process just by copying the array if it's attribute `base` is not `None`.

### Versions / Dependencies

Ray : 1.7.0
Numpy : 1.19.5
Python : 3.8.10
OS : Ubuntu 20.04

### Reproduction script

```
import ray
import numpy as np
import timeit

# Original array
arr = np.array(np.random.uniform(0,255,(720, 1280, 3)), dtype = np.uint8)
# Flip view of "arr"
fliped_arr = np.flip(arr, axis=-1)

# Time of serializing "arr"
timeit.timeit(lambda : ray.put(arr), number=100)
# Mesured time : 0.227

# Time of serializing flip view of "arr"
timeit.timeit(lambda : ray.put(fliped_arr), number=100)
# Mesured time : 2.86

# Time of copying and serializing the flip view of "arr"
timeit.timeit(lambda : ray.put(np.array(fliped_arr)), number=100)
# Mesured time : 0.895
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gaurav274** [comment]
I encountered a simpler issue. Looks like when the numpy array isn't contiguous ray.put is slow
