### ISSUE TITLE
Ray Client Server should know whether agent has been started instead of trying to import ray[default]

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#19558]
Currently the Ray Client server doesn't have information about whether we intended to start the dashboard agent or not.  So before sending a CreateRuntimeEnv RPC to the agent, it tries to import ray[default] and uses this as a proxy for whether or not the agent is started or not (because ray[default] contains the Ray dashboard dependencies.). This is not future-proof, see https://github.com/ray-project/ray/pull/19491#discussion_r731914614. We should pass in information about whether or not we intend to start the agent directly to the Ray Client server.

**Comment by ericl** [comment]
Btw this is somewhat resolved by https://github.com/ray-project/ray/pull/19493... the client server will see "AgentDisabled" when trying to locate the agent port.
