### ISSUE TITLE
[Feature] NSight GPU profiler support

### ISSUE THREAD

**Issue by drewm1980** [ray-project/ray#19631]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We are using Ray to distributed deep learning training on clusters, and would like more insight into whether our training loop is running efficiently within its Ray worker.

I have found that the best tool for profiling GPU enabled code, by a longshot, is Nvidia's own NSight Systems profiler: https://developer.nvidia.com/nsight-systems. 

I would like to have some documented and tested path to configuring a ray worker to run its code in a new process under nsight-systems, and somehow get at the resulting dumped profile.

With some debuggers a workflow is possible (though not ergonomic):
1. Figure out which node is running your worker via kubernetes
2. ssh into the node
3. discover what container your worker is running in
4. connect to running container
5. install py-spy or another profiler into the running container
6. figure out what process your worker is running in
7. attach the profiler to the running worker process and dump results to screen.

This, unfortunately, is not possible with nsight-systems, since it cannot attach to an already running process; you have to launch the process using nsys for all of the hooks to get set up correctly. 

### Use case

1. We discover that some piece of code that runs inside a ray worker has a performance problem.
2. We do some configuration (not sure where) to enable GPU profiling for that worker
3. We do some configuration to retrieve the actual profile information from the cluster
4. We load the dumped profiler into NVidia's profile visualizer, discover the problem cause, make code changes, and repeat the process.

Note that this request does NOT concern profiling performance issues caused by Ray itself. Distributed (non-gpu) tracing frameworks are more appropriate for that, and are out of scope for this feature request. This is purely about the ability to profile CUDA-using code running in a ray worker.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
Seems we have another user asking for it: https://discuss.ray.io/t/are-there-any-hacks-to-use-nsys-in-ray/8097

**Comment by yzs981130** [comment]
A similar use case is here. Profiling tools like `nsys` will be greatly beneficial for profiling and performance analysis of workloads. Currently, `nsys` could be only used as a launcher of processes, which is incompatible with Ray. 

I believe it would be very helpful if the following needs were taken into account.

1. It would be helpful if support for `nsys` could work under various environments of Ray, such as local mode, ray cluster, etc. 
2. The profiling function can be turned on or off on demand, which will greatly facilitate the use of the profiling function in production environments.

**Comment by scottsun94** [comment]
This seems pretty important if users want to go really deep to optimize GPU usage.
cc: @rkooo567 @ericl @rickyyx @alanwguo 

@drewm1980 @yzs981130 
I'm wondering when you choose to use profiling tools like tf profiler/ pytorch profiler and when you choose to use `nsys` for GPU profiling.

**Comment by yzs981130** [comment]
> This seems pretty important if users want to go really deep to optimize GPU usage. cc: @rkooo567 @ericl @rickyyx @alanwguo
> 
> @drewm1980 @yzs981130 I'm wondering when you choose to use profiling tools like tf profiler/ pytorch profiler and when you choose to use `nsys` for GPU profiling.

From my own limited experience, when I try to get relatively high-level information (e.g., operator time breakdown), the framework-level profiler is better. I usually use `nsys` to figure out more fine-grained execution and time sequenced information. For example, I need to confirm the actual parallelized operations on GPU, or figure out which op blocks the others.

**Comment by yzs981130** [comment]
reopen

**Comment by rickyyx** [comment]
I believe @rkooo567 is working on something releated?

**Comment by rkooo567** [comment]
I think maybe after ray 2.5 (we are feature freeze in observability until then)

**Comment by shayanhoshyari** [comment]
I would also like to +1 this feature.

**Comment by darthhexx** [comment]
+1 from me as well

**Comment by cadedaniel** [comment]
@darthhexx and @shayanhoshyari , can you share your use case (if it isn't distributed training)?

**Comment by KarimDarwish** [comment]
Has there been any update on this/is there any way to help here? Use case would be profiling distributed training

**Comment by jonathan-anyscale** [comment]
Hi, the PR for this support is already merged and available for nightly wheel + next ray release. 
https://github.com/ray-project/ray/pull/39998

**Comment by scottsun94** [comment]
Note: this PR above only supports `nsys` in Ray Core.
If you guys want to use `nsys` with Ray Train, Ray Tune, or other libraries, please create a new ticket and document your requirements there.
