### ISSUE TITLE
[Bug] Worker would be leaked if it received a SIGTERM when DrainAndShutdown.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#19639]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

If a worker receives a SIGTERM signal when it's doing reference_counting->DrainAndShutdown stuffs, it would be leaked.

### Versions / Dependencies

master

## STEP1
`ray start --head`

## STEP2
Run this driver scripts:
```python
import ray
import numpy as np

ray.init(address='auto')

@ray.remote
def normal_task(large):
    import time
    time.sleep(60 * 60)
    return "normaltask"

large = ray.put(np.zeros(100 * 2**10, dtype=np.int8))
obj = normal_task.remote(large)
ray.get(obj)

```
## STEP3
Use `ps -ef | grep ray::` command to find the pid of the `normal_task` worker.
![image](https://user-images.githubusercontent.com/19473861/138478055-0d9ad685-fcdf-47dd-b861-87c677f14e02.png)
Then kill it with SIGTERM:
```
kill -15 88824
```
## STEP4
Wait the normal_task getting reconstructed, and then exit your driver process.

## FINALLY
The worker(pid=88824) is leaked. And next coming tasks wouldn't be scheduled to this worker.

REASON: It sends a disconnect message to raylet, but it doesn't exit because of DrainXxxx(). and raylet remove it from `registered_workers` in worker_pool. So `TryKillingIdleWorkers()` is not able to kill it.

### Anything else

In our production environment, the leaked worker executed a heavy task, and leaded the worker with a high memory usage(around 10G+). So in a short time, the memory usage wouldn't be down, and other actors were scheduled onto this pod, resulting in a critical OOM.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
File a simple reproduced script:
```python
import ray
import numpy as np

ray.init(address='auto')

"""
@ray.remote
class A:
    def hello(self):
        return "hello"

    def f(self):
        return "actor"
"""

@ray.remote
def normal_task(large):
    import time
    time.sleep(60 * 60)
    return "normaltask"

# actor = A.remote()
# assert ray.get(actor.hello.remote()) == "hello"

large = ray.put(np.zeros(100 * 2**10, dtype=np.int8))
obj = normal_task.remote(large)
ray.get(obj)
```

**Comment by jovany-wang** [comment]
@stephanie-wang Could you take a look at this one?

**Comment by ericl** [comment]
Isn't this working as intended? We can't remove the worker if there are active references until it is drained.

**Comment by jovany-wang** [comment]
> Isn't this working as intended? We can't remove the worker if there are active references until it is drained.


I don't think it's intended.  

```python
@ray.remote
def normal_task(x):
    # time.sleep(60 * 60)         #### No sleep here
    return "normaltask"
```
For the above snippet, `normal_task` adds the `x` as its local reference, `normal_task` isn't the owner of `x`, so the `x` should be removed after `normal_task` finished.

And for the following one, if we send a SIGTERM to the `normal_task` worker when it's doing `time.sleep(60 * 60)`, the `normal_task` raises an exception to the user side or reconstruct it. But anyway, the `x` should be out of the `normal_task` scope, and `normal_task` worker should remove the local reference of `x` in local. But it doesn't remove the local reference since it's drained and the job is offline, noway to trigger it.

```python
@ray.remote
def normal_task(x):
    time.sleep(60 * 60)       # Will receive a SIGTERM here and trigger a SYSTEM_EXIT error.
    return "normaltask"
```

**Comment by jovany-wang** [comment]
Generally speaking, for both the `normal_task` finishing normally and terminating with errors, the local reference `x` should be removed and the local worker shouldn't drain anything.

**Comment by ericl** [comment]
I see. I can reproduce this locally. I wonder if it's because we improperly cancelled the task when handling SIGTERM, and did not get a chance to release references to the task arguments.

**Comment by jovany-wang** [comment]
Yes.  What do you think of the best fixing?
I don't make sure if it's possible to release them in Python layer. Otherwise we should release them in core worker once task canceled.

**Comment by ericl** [comment]
Hmm how about setting a reference to them in core worker that can be
released on hitting sigterm or other unexpected signals?
