### ISSUE TITLE
[runtime_env] Support a worker setup hook that runs before importing Ray

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#19640]

**Comment by edoakes** [comment]
More requests for this recently:
https://discuss.ray.io/t/how-can-i-run-a-python-function-in-each-workers-interpreter-as-it-joins/4122

**Comment by edoakes** [comment]
Bumping to P1 due to user requests

**Comment by joncarter1** [comment]
Hey all,

I'm glad I stumbled across this issue, the RAY_USER_SETUP_FUNCTION is really handy for my use case and will help me further tighten security in my Ray cluster.

I'm wondering whether there's a target release for the custom RuntimeEnv plugin which I've heard whispers for in a few places?

Thanks,
Jonathan

**Comment by rkooo567** [comment]
https://docs.ray.io/en/latest/ray-observability/user-guides/configure-logging.html#customizing-worker-process-loggers

<img width="760" alt="Screenshot 2023-08-09 at 11 18 49 AM" src="https://github.com/ray-project/ray/assets/18510752/b0be3654-20c3-4323-a94b-ef0fae9f37c7">

The experimental feature is already supported. We are planning to harden the support by ray 2.7
