### ISSUE TITLE
"Task is a driver task and so the object created by ray.put could not be reconstructed."

### ISSUE THREAD

**Issue by heyucongtom** [ray-project/ray#1968]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Sierra 10.13.3
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.4.0
- **Python version**: 3.6.5
- **Exact command to reproduce**: just python [source.py]

### Describe the problem
When continuously putting and getting large objects result in error saying:
  
"The task with ID 7e6d77402f393fac87ca0da4818f1e62c7c8edad is a driver task and so the object created by ray.put could not be reconstructed."

"You can inspect errors by running ray.error_info()", which actually == []. 

I attached the source code to reproduce this problem.

### Source code / logs
```
import ray
import time
import numpy as np
SIZE_MB = [0.001 * pow(1.23, i) for i in range(55, 60)] # Towards 201 MB object.
total_nums = [1,2,4,8,16]

def test_get_throughput():
	"""
	Test single-threaded maximum get throughput achievable by Ray
	We measure the actual throughput by first call get
	Then copy the result of get onto a numpy array
	so that we can force memory copying...
	"""

	def do_measure_throughput(size, reuse_rate, num, rand_ids, target_array):
		for i in range(num):
			target_array += ray.get(rand_ids[i])

	for size in SIZE_MB:
		rand_ids = [ray.put(np.random.rand(int(size * 250 * 1000))) for _ in range(total_nums[-1])]
		for num in total_nums:
			my_tag = num
			target_array = np.zeros(int(size * 250 * 1000))
			print(num, size)
			do_measure_throughput(size, reuse_rate, num, rand_ids, target_array)

if __name__ == "__main__":
	ray.init()
	print("Testing throughput for get...")
	test_get_throughput()


```

**Comment by liyouhaolinezone** [comment]
Have you solved this problem？how?

**Comment by heyucongtom** [comment]
@liyouhaolinezone There exists a limit for the maximum size for Redis database. (I forget where to find that limit, but it's like ~2G). The continuous put & get of the large object **may somehow** (which I don't get time to explore in depth, but I am doing it.) stall the resource managing code.

My solution is to avoid storing large stuff in Redis, which shall be used as a cache. See https://muut.com/blog/technology/redis-as-primary-datastore-wtf.html

**Comment by ferreirafabio** [comment]
@heyucongtom have you looked into this? Does increasing the maximum size help? I am facing the same issue under Redhat 7.5, Python 3.6 and the up-to-date ray version.

**Comment by heyucongtom** [comment]
@ferreirafabio Take a look at https://github.com/ray-project/ray/blob/master/python/ray/plasma/plasma.py#L17, and https://arrow.apache.org/docs/python/plasma.html. I guess this controls the size of the plasma database. Modifying this may help, but since it shall be used as cache, I guess storing large objects shall not be encouraged.

**Comment by boscotsang** [comment]
@heyucongtom I also come up with this problem when training last for about a day. I doubt that it's because redis or plasma's  memory is full. I'm running lots of actors and therefore many data are pass by redis or plasma. However, when I get the data from woker, the data are no longer useful which cost much memory. Is there any method to clear these useless data? Thanks.

**Comment by robertnishihara** [comment]
@boscotsang can you try the latest snapshot of the master and see if the issue persists? https://ray.readthedocs.io/en/latest/installation.html#latest-stable-version

**Comment by boscotsang** [comment]
@robertnishihara The problem still exisits after update to thre latest snapshot of the master.
`worker.py: [ERROR]  The task with ID 0000000078673ece7b3ac8115895c7f60ae675d8 is a driver task and so the object created by ray.put could not be reconstructed.`

**Comment by boscotsang** [comment]
After removing the ray.put in the main process, it seems that it doesn't crash any more. The problem may be the plasma evicted the object put by main process.

**Comment by anttttti** [comment]
I had this error when plasma store is too full, from trying to work with big result objects. The program gets stuck repeating this message every few minutes. Changing /dev/shm to use all of the system RAM and object-store-memory to match this changed this to a regular out-of-memory error from the Ray profiler, which seems easier to work with and plan around.

**Comment by virtualluke** [comment]
I am seeing this error from time to time, seems random.  When I rerun the job it succeeds.  It is infrequent but very frustrating.  

This error message as is is not very helpful. 

 Is it a plasma store memory issue?  How can I tell?  Using ray master from about a week ago, python 3.7.4

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
