### ISSUE TITLE
Using remote functions and ray.worker.cleanup leads to crashes

### ISSUE THREAD

**Issue by avaziri** [ray-project/ray#1970]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.3 LTS
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.4.0
- **Python version**: 3.5.4
- **Exact command to reproduce**: See follow up comment
### Describe the problem
When working in an environment where you are going to initialize and shutdown Ray multiple times in the same process (e.g. during execution of a pytest suite) it unclear how to shut down all the workers properly. As described in https://github.com/ray-project/ray/issues/1798 if one tries to use `ray.remote.cleanup()` this causes some remote function definitions to be missing. I am not sure if during each test they get exported then accidentally deleted, or if somehow they never get exported on subsequent tests. In particular you end up getting errors like the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 821, in _process_task
    *arguments)
  File "/usr/local/lib/python3.5/dist-packages/ray/actor.py", line 212, in actor_method_executor
    method_returns = method(actor, *args)
  File "/brain/src/backend/pdp/agents/bonsai_trainable.py", line 177, in test
    result = self._test(weights, lesson)
  File "/brain/src/backend/pdp/agents/bonsai_dqn_agent.py", line 318, in _test
    self.registry, self.logdir, num_episodes_for_remote))
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2583, in func_call
    return _submit(args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2603, in _submit
    resources=resources)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 2423, in _submit_task
    return global_worker.submit_task(function_id, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ray/worker.py", line 578, in submit_task
    self.task_driver_id.id()][function_id.id()]
KeyError: b'\xe1\xa0\xb0\xca`\xaa\xf7T\x8a\xe2\x1bS\x16\xb1\xc2\x8d\xbd#&\xf3'
```
Following the suggestions from https://github.com/ray-project/ray/issues/1798 I made sure to define my remote function at the last possible moment, right before I used it. Even with that I am still getting errors like the above.

How can I fully shut down Ray in a way that ensures everything is completely torn down before I try to move on to the next test in the suite? It seems to me like `ray.remote.cleanup()` only kills one worker. I suppose the problem is that I need to kill each and every worker? Highly related to this feature request: https://github.com/ray-project/ray/issues/1814

**Comment by avaziri** [comment]
Made a bug report with the Ray team here https://github.com/ray-project/ray/issues/1970. Still trying to make a simple example that has the behavior

**Comment by avaziri** [comment]
I have found a workaround which may have some serious side effects. All I can say is that it seems to resolve the issue.


```
def create_test_remote(foo:
    # Change from worker mode to script mode for a moment in order to trick
    # worker into exporting function definiton
    original_mode = ray.worker.global_worker.mode
    ray.worker.global_worker.set_mode(ray.worker.SCRIPT_MODE)

    @ray.remote
    def _test_remote(foo):        
        return True
    ray.worker.global_worker.set_mode(original_mode)

    out_id = _test_remote.remote(foo)
    return out_id
```
This works because this causes the worker to publish the remote function definition rather than trying to look it up in the cache.

**Comment by robertnishihara** [comment]
This has been fixed now.
