### ISSUE TITLE
[Tune] Rsync checkpoint flow involves ip to node_id and back to ip

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19710]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

rsync checkpoint flow involves converting ip to node_id and back to ip, which is insufficient.
This contributes to process_trial_result being slow in Tune loop.
```
xw - callback: <ray.tune.progress_reporter.TrialProgressCallback object at 0x7fb3cc7a7070>
takes 6.4849853515625e-05

xw - callback: <ray.tune.logger.CSVLoggerCallback object at 0x7fb3cc7a7310>
takes 0.0001087188720703125

xw - callback: <ray.tune.logger.JsonLoggerCallback object at 0x7fb3cc7a7370>
takes 9.107589721679688e-05

xw - callback: <ray.tune.logger.TBXLoggerCallback object at 0x7fb3cc7a7160>
takes 0.0008788108825683594

xw - callback: <ray.tune.syncer.SyncerCallback object at 0x7fb3cc7a73a0>
2021-10-25 11:22:26,851 INFO command_runner.py:357 -- Fetched IP: 172.31.51.129
2021-10-25 11:22:26,851 INFO log_timer.py:25 -- NodeUpdater: ins_fhkpTvGP2seweE6g2J3sn5Q1: Got IP  [LogTimer=676ms]
takes 2.655524969100952
2021-10-25 11:22:27,545 WARNING util.py:165 -- The `callbacks.on_trial_result` operation took 2.657 s, which may be a performance bottleneck.
2021-10-25 11:22:27,546 WARNING util.py:165 -- The `process_trial_result` operation took 2.658 s, which may be a performance bottleneck.
```

code pointers:
_private/commands.py: rsync and rsync_to_node

### Versions / Dependencies

master

### Reproduction script

python test_bookkeeping_overhead.py

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
This is still relevant. Let's keep it open for now.

**Comment by krfricke** [comment]
I think this should be resolved with our task-based syncing.
