### ISSUE TITLE
[Serve] Handle should not send tasks on crashed actor

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19723]
Currently when when an actor crash, serve handle expect that controller will refresh the set of actors. But controller might be down or busy at times. The information about actor status is available through the `ready_ref` we are tracking in `ReplicaSet`. We should be able to instructment serve handle to choose not to send new requests to crashed actors, or exponentially block it for some duration.

**Comment by edoakes** [comment]
@shrekris-anyscale can you close this when you merge your relevant PR? :)
