### ISSUE TITLE
[Feature] Add an option to start head node without raylet

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#19745]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

In a large scale ray cluster, the head node's load is high because gcs server will handle a lot of events. And the raylet on the head node make things worse.

Please add an option to start head node without raylet.

### Use case

The head node don't start raylet.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kfstorm** [comment]
> As a workaround, you can start the head node with `--num-cpus=0`, which will prevent tasks from getting scheduled onto it.

@ericl Tasks with `@ray.remote(num_cpus=0)` will still be able to schedule to the head node, right?
