### ISSUE TITLE
Problem with reproducing example from docs

### ISSUE THREAD

**Issue by atypic** [ray-project/ray#1982]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 4.9.65-3+deb9u2
- **Ray installed from (source or binary)**: pip the wheel
- **Ray version**: 0.4.0
- **Python version**: 3.6.5
- **Exact command to reproduce**:  python test_script.py

### Describe the problem

Code from examples fail.

### Source code / logs

> 
> Remote function step failed with:
> 
> Traceback (most recent call last):
>   File "/home/oddrune/miniconda3/envs/retrogame/lib/python3.6/site-packages/ray/worker.py", line 821, in _process_task
>     *arguments)
>   File "/home/oddrune/miniconda3/envs/retrogame/lib/python3.6/site-packages/ray/actor.py", line 212, in actor_method_executor
>     method_returns = method(actor, *args)
>   File "fuckface.py", line 15, in step
>     return self.env.step(action)
> AttributeError: 'GymEnvironment' object has no attribute 'env'
> 
> 

```
import gym
import ray

ray.init(redirect_worker_output=True)

@ray.remote
class GymEnvironment(object):
    def __init__(self, name):
        self.env = gym.make(name)
        self.env.reset()

    def step(self, action):
        return self.env.step(action)

    def reset(self):
        self.env.reset()

pong = GymEnvironment.remote("Pong-v0")
print(ray.get(pong.step.remote(0)))  # Take action 0 in the simulator.

```

**Comment by atypic** [comment]
Missing box2d, obviously the env failed to load.

**Comment by robertnishihara** [comment]
Glad it's working now. FYI I modified the filename in the traceback.

**Comment by atypic** [comment]
err... yeah. i actually don't remember what the filename was, but knowing myself it was probably very rude. i get destructive when i debug.
