### ISSUE TITLE
[Bug] It seems head node is not found by worker nodes Ray Tune/Austoscaler GCP

### ISSUE THREAD

**Issue by dennymarcels** [ray-project/ray#19852]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, Ray Clusters

### What happened + What you expected to happen

I've been trying to run [mnist_pytorch_trainable.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py) with [example_full.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/gcp/example-full.yaml) at GCP, but with two minor changes: I set `resources_per_trial` to be 2 CPUs (since the yaml file does not contain nodes with 3 CPUs to begin with), and I set `resources: {'CPU': 0}` to the head node to force training with the workers only.

Everything goes fine until the workers are instantiated. They are created properly, I can ssh to them, but the log in the dashboard says that they are in the `setting_up` stage indefinitely. As a result, no training ever begins.

Curiously, I am quite sure I did manage to make this pipeline work a few days ago...

I did also try to run my own code adapted from the above, and also a very `simple_script.py` only to make sure that the issue was not with the script, but could not advance.

Another thing I noticed is that, in my own implementation (where I did not set up a Docker environment and run ray from bash), if I SSH to the instantiated worker then `ray status`, it says `Could not find any running Ray instance`, meaning it is not connected to it, even though it is running at the head node. If then I force `ray start` to the internal IP of the head node, the terminal gets stuck indefinitely. I suspect this is what is happening in the session managed by the autoscaler.

I believe that the head node instantiated by ray submit is not reachable in the network. Nevertheless, if I manually start a head node (the same command but no `autoscaling_config`), any other instance can find it.

### Versions / Dependencies

My machine runs Ubuntu 20.04, my instances are on Debian 9 running Ray 1.7.0/Python 3.7.

### Reproduction script

[mnist_pytorch_trainable.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py)
[example_full.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/gcp/example-full.yaml)

```
# simple_script.py
import time
import ray
from ray import tune

def train_fn(config):
    time.sleep(60)
    tune.report(mean_loss = 1)

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--ray-address", type=str)
    args = parser.parse_args()

    ray.init(address=args.ray_address)
    tune_config = {'batch_size': tune.grid_search([16, 32, 64])}
    analysis = tune.run(train_fn, config = tune_config, resources_per_trial={"cpu": 1})
    print("Best config is:", analysis.best_config)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by dennymarcels** [comment]
I figured out what was going on... I needed to forward ports between GCP instances. Preventively, I open all ports & protocols for instances managed by the Ray Austoscaler. All is good now.

**Comment by NikAleksFed** [comment]
@dennymarcels I have the same issue. Can you describe your solution more specifically? Did you modify "head_start_ray_commands" and "worker_start_ray_commands" in "config.yaml"? If so, can you share this part of config?

**Comment by dennymarcels** [comment]
I won't remember the details but as far as I can tell, all I had to do was port forwarding.
