### ISSUE TITLE
[Bug] build ray project on arch64 

### ISSUE THREAD

**Issue by hecheng64** [ray-project/ray#19865]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

I followed (https://docs.ray.io/en/master/development.html#building-ray-full ) the operation on arch64 centos8, but the following problems occurred：
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/2342e7b33aca58abb45809f4e4067d31/sandbox
[25 / 1,878] 8 actions running
Compiling src/compiler/python_generator.cc [for host]; 51s processwrapper-sandbox
Compiling src/google/protobuf/util/message_differencer.cc [for host]; 51s processwrapper-sandbox
Compiling src/compiler/node_generator.cc [for host]; 37s processwrapper-sandbox
Compiling src/google/protobuf/compiler/cpp/cpp_helpers.cc [for host]; 29s processwrapper-sandbox
Compiling src/google/protobuf/compiler/cpp/cpp_message.cc [for host]; 28s processwrapper-sandbox
Compiling src/google/protobuf/compiler/cpp/cpp_padding_optimizer.cc [for host]; 10s processwrapper-sandbox
Compiling src/google/protobuf/compiler/cpp/cpp_primitive_field.cc [for host]; 5s processwrapper-sandbox
Compiling src/google/protobuf/compiler/cpp/cpp_service.cc [for host]; 3s processwrapper-sandbox

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/2342e7b33aca58abb45809f4e4067d31/server/jvm.out')

### Versions / Dependencies

ray: the lastest 
python :3.7
os； centos8
arch：aarch64 or arm64

### Reproduction script

(https://docs.ray.io/en/master/development.html#building-ray-full

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ddelange** [comment]
duplicate of #12128
