### ISSUE TITLE
[Serve] Calling serve.start(detached=True) with different options should error

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19868]
When users starts Serve cluster with a set of options (http options, checkpoint path) and then connects to it with a different set of options, we should either update it, or error out.

**Comment by pmmitche** [comment]
Hi! I'm interested in working on this, but had some questions. In terms of "connecting" to the serve cluster, what call would that be? I see the `_connect()` in python/ray/serve/api.py, but don't see the ability to pass in any options. Or would it be the `ray_actor_options` field of `.deploy()`? Any info would be great, thanks!

**Comment by jiaodong** [comment]
Hi @pmmitche ! Thanks for your interest on this issue. The options are passed from cli in https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/serve/scripts.py?L33-69 which are translated into serve/api.py calls such as `serve.start`

**Comment by jwyyy** [comment]
Hi @pmmitche, are you still working on this issue? If not, would you mind letting me pick it up? Thanks!

**Comment by pmmitche** [comment]
Hi @jwyyy be my guest! Caught up with other stuff at the moment.

**Comment by jiaodong** [comment]
Feel free to tag us as reviewers :)

**Comment by jwyyy** [comment]
Hi @simon-mo @jiaodong, I studied the issue but found some points unclear. Could you help me clarify them? Then I can start to work on the implementation. 

Essentially we want to update the `client` object when multiple `serve.start()` are called. HTTP options and checkpoint path are saved in the client's controller (actually an `Actor` object). So the idea is to compare the new HTTP and checkpoint path inputs to the existing ones, and throw out error messages if they don't match. 
1. Am I correct about the intended behaviors? 
2. Then when and under what circumstances do we **update** the client? 
3. Also, when updating the client, do we simply update its HTTP options and checkpoint path (thus [`kv_store`](https://github.com/ray-project/ray/blob/fd02065ce577dbe5a8860d21c4232cc7c0aa9725/python/ray/serve/controller.py#L76-L78))? Or actually we need to create a new one to replace the old one (then shutdown the old one)?

Thank you for your clarification! 😄

**Comment by jwyyy** [comment]
Hi @simon-mo @jiaodong, just want to follow up. Would you mind giving me some initial comments on the previous message when you have time to take a look? Then I will start to work on the implementation. Thanks a lot!

**Comment by simon-mo** [comment]
Hi @jwyyy sorry about the late reply and thank you for planning to contribute! 

> Am I correct about the intended behaviors? Then when and under what circumstances do we update the client?

Yup! We should either throw error (easier) or perform an idempotent update (harder to implement). I see the error approach as a simple, stop-gap fix solution and the update as long term solution.

> Also, when updating the client, do we simply update its HTTP options and checkpoint path (thus kv_store)? Or actually we need to create a new one to replace the old one (then shutdown the old one)?

This needs some thought. For HTTP options, we should consider creating new http servers based on those options and shutting down old ones (with a big warning to the user). For kv store options, we should perform such update with a loud noise (you might notice that for kv store, we will need to re-initialize some objects in controller).

Please feel free to choose the scope that you feel comfortable implementing and let us know!

**Comment by jwyyy** [comment]
Hi @simon-mo, no worries, and thank you for your comments! They are very helpful. I think I can start to do the error-throw first in an initial commit, which can help add the feature soon. But the update approach looks more elegant, and I will definitely explore more. Will update with more thoughts. Thanks again!

**Comment by jwyyy** [comment]
Hi @simon-mo @jiaodong, I made an initial commit to address this issue based on our discussion above. The current implementation aims for a short-term solution and only reports a warning. 

Regarding the update approach, here are some thoughts:
1. The warning can still be kept in the update solution. 
2. Can we add an option in `serve.start(_update_config = False)` to allow users to choose if they want to update HTTP and KV store? 
3. For the idempotent update, if the user has used the client to perform some actions, it is likely that there are some data stored in KV store and HTTP proxies. I think we may want to keep existing data when re-initializing HTTP servers and KV store (related objects). Could you point me to some Ray util methods that can copy config from old objects to new ones (HTTP and KV store? If there is no such method, should we implement one for this purpose?

Please let me know your thoughts and comments when you have time to review the PR! Thanks a lot!
