### ISSUE TITLE
[DataFrame] _IndexMetadata.copy() may block on OID-backed _index_cache

### ISSUE THREAD

**Issue by Veryku** [ray-project/ray#1988]
### Describe the problem
Since we will support passing the index as an Object ID for `_IndexMetadata` as of #1984, `_IndexMetadata.copy()` may result in a blocking call waiting for `_index_cache` to be populated. Refer to the code snippet below.

### Source code / logs
https://github.com/ray-project/ray/blob/master/python/ray/dataframe/index_metadata.py#L270

**Comment by devin-petersohn** [comment]
@Veryku Opening a new issue to track this on the [Modin](https://github.com/modin-project/modin) repo
