### ISSUE TITLE
[Nightly release]  gcp_k8s_durable_upload is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19895]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/1414#63566f3c-0e27-4dfd-8031-039ab8f315f8

### Versions / Dependencies

master/nightly

### Reproduction script

master/nightly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Re-opening to track GCP-specific issues

**Comment by krfricke** [comment]
Should have been fixed by #24015
