### ISSUE TITLE
[Bug] [Core] Actor Memory Leak?

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#19905]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

While I was debugging https://github.com/ray-project/ray/issues/19891, I found a repro for just Ray Core. The symptom here is the actor process's rss is growing unbounded, hinting at a potential memory leak. 

The clue here is that there are a lot of the following warning printed in core worker log
```
[2021-10-29 15:35:11,387 W 308 4150412] reference_count.cc:1264: Object locations requested for f41b9572c5c83548a29d4ccf3ef06c8cf066b2040100000001000000, but ref already removed. This may be a bug in the distributed reference counting protocol.
```

Please see the repro script for the workload.

### Versions / Dependencies

Master
```
commit 16d3afc665290addbb5c164f6cd29d1bfe552375 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: architkulkarni <architkulkarni@users.noreply.github.com>
Date:   Fri Oct 29 15:03:53 2021 -0700

    [serve] Base autoscaling decisions on target num replicas, not current num replicas (#19869)
```

### Reproduction script

Ok I have several version of the repro, but the most useful one is the following 

```python
import ray
import os
import asyncio
import numpy as np
import psutil

@ray.remote
class QpsTest:
    def __init__(self):
        self.count = 0

    async def __call__(self):
        self.count += 1

        # note this is below object store memory threshold
        state = np.zeros((1000, 1000), np.uint64)
        process = psutil.Process(os.getpid())
        proc_mem = process.memory_info().rss / (1024 ** 2)
        print(f'count{self.count} \t mem={proc_mem:6.1f} MB.')

        return state

# Use multiple callers to increase the throughput
async def replica_runner(handle):
    while True:
        await handle.__call__.remote()

async def main():
    ray.init(num_cpus=1, log_to_driver=False)

    handle = QpsTest.options(max_concurrency=10).remote()

    await asyncio.gather(*[replica_runner(handle) for _ in range(40)])


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```
Run this script, then go the logs directory to tail the worker log. You will see memory just grow.

You can see that we are using async actor and async senders to simulate a workload that having the actor return a big enough object that's less than plasma limit.

You can change the workload, but the current setting clearly demonstrate the issue fast. I tried the following but the memory still grow (although slower):
- add gc.collect()
- change the number of sender
- change the actor to sync actor
- change the actor to threaded actor.
- cache psutil object

However, the one scenario that it didn't grow if when you cache the numpy array. i.e. 
```python
class QpsTest:
    def __init__(self):
        self.state = np.zeros((1000, 1000), np.uint64)

    async def __call__(self):
        ...
        return self.state # no leak!
```

Another hypothesis is memory leak in numpy, but when I ran the following script, it showed much slower growth, making it look like more just memory allocator having difficulty compacting memory.
```
import numpy as np
import os
import psutil
import time

process = psutil.Process(os.getpid())
proc_mem = process.memory_info().rss / (1024 ** 2)
last_growth = time.time()
while True:
    state = np.zeros((1000, 1000), np.uint64)
    new_proc_mem = process.memory_info().rss / (1024 ** 2)
    if new_proc_mem != proc_mem:
        proc_mem = new_proc_mem
        dur = time.time() - last_growth
        last_growth = time.time()
        print(dur,"later, mem is", proc_mem)
```

```
0.0038938522338867188 later, mem is 240.31640625
11.735158920288086 later, mem is 247.97265625
12.92294692993164 later, mem is 255.62890625
15.137562036514282 later, mem is 263.28515625
66.46054983139038 later, mem is 270.94140625
... # and it gets harder and harder to see memory growth
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
cc @scv119 @rkooo567 @ericl please let me know if you can't reproduce this or this is a false alarm (could be just (py)malloc being weird and don't compact memory...)

**Comment by scv119** [comment]
can't reproduce with ray 1.7.0 + numpy 1.20.3 for 20 minutes on linux :/

**Comment by simon-mo** [comment]
closing, user identified as library bug.
