### ISSUE TITLE
[Bug] Something a bit weird about the new per-commit wheel artifact

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#19920]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Branch: https://github.com/ray-project/ray/commits/test_wheels/jungong-connect_tests
Commit: 895dc2ced5f5aaa88c69e9d239df2701ac5eac52
The Linux "wheels and jars" job seemed to complete successfully.
Buildkite: https://buildkite.com/ray-project/ray-builders-pr/builds/17431#ab6f29bb-a157-407f-9e2a-9c5dfd50cc0f

However linux wheels are not in the s3 folder:
https://s3.console.aws.amazon.com/s3/buckets/ray-wheels?region=us-west-2&prefix=test_wheels/jungong-connect_tests/895dc2ced5f5aaa88c69e9d239df2701ac5eac52/&showversions=false

Even a bit more strange, if you try to download the new per-commit wheel from:
https://s3-us-west-2.amazonaws.com/ray-ci-artifact-pr-public/895dc2ced5f5aaa88c69e9d239df2701ac5eac52/tmp/artifacts/.whl/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

You will get a wheel file for a random commit hash:
851cdf49048bf87d8d4803ca0ea08765d7cae472

No idea where does that commit/wheel come from.

### Versions / Dependencies

2.0.0dev0

### Reproduction script

As description.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
Looks like you deleted the branch. Make sure to merge master and re-open if this happens again!

**Comment by gjoliver** [comment]
See this again, check out this wheel:

https://ray-ci-artifact-branch-public.s3.amazonaws.com/2d50bf13025272185a41f7dcab66bab994a99719/tmp/artifacts/.whl/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

it actually has a commit hash of add2450b92bcb8c18b6fef7667c8acb9e3cc63cd

**Comment by jjyao** [comment]
I have seen the same issue for PR wheel:
```
[INFO] 1/25/2022, 8:30:27 AM: * Step 15/16 (commit,modifyfs) : RUN python -c 'import ray; assert ray.__commit__ == "0646277340b7bade3c41bfd0841b962c2b793e9c", ray.__commit__'  (724355b0)
[INFO] 1/25/2022, 8:30:27 AM: Client TLS is disabled
[INFO] 1/25/2022, 8:30:28 AM: * Started pushing layer sha256:4def28367dc7f4f1c52e32b791de14a3999be25f3aadfc8eb93aec8dd559fba9
[INFO] 1/25/2022, 8:30:28 AM: Client TLS is disabled
[ERROR] 1/25/2022, 8:30:28 AM: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: 9a1bdd7d91583984695d7b4dbf270040585f5f7e
```

Seems the issue is not fully fixed. cc @krfricke

**Comment by gjoliver** [comment]
this is fixed by Kai
