### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sjulias** [ray-project/ray#19939]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Dashboard

### What happened + What you expected to happen

Unable to start head node with dashboard

### Versions / Dependencies

version: ray[default]==1.7.0

### Reproduction script

Reproduce steps:
machine: Linux 4.15.0-88-generic x86_64

     conda create -n ray python=3.8.11
     conda activate ray
     pip install ray[default]==1.7.0
     IP=`hostname -I | awk '{print $1}'`
     ray start --head --port=6379 --node-ip-address="$IP" --redis-password="1" --include-dashboard=true  -- dashboard-port=8266 --dashboard-host "0.0.0.0"

    this command fails to start with the following error

        raise ImportError(DASHBOARD_DEPENDENCY_ERROR_MESSAGE)
        ImportError: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip 
        install ray[default]`

The same installation two weeks ago on another machine works like a charm.
When I copied the exact env from the old machine it working. When I do the following installation steps on another machine it fails. So my suspicion is that the latest buggy version is released 
Please take a look 

### Anything else

It happens for me for every new installation

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sjulias** [comment]
In addition, when I ran the ps command this is the output

         ps -ef | grep ray
    yuls  33866     1  0 03:20 pts/2    00:00:00 /users/anaconda_data/shared/yuls/ray/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *:6379
    yuls  33871     1  0 03:20 pts/2    00:00:00 /users/anaconda_data/shared/yuls/ray/lib/python3.8/site-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *:63965
    yuls  33876     1  0 03:20 pts/2    00:00:00 /users/anaconda_data/shared/yuls/ray/lib/python3.8/site-packages/ray/core/src/ray/gcs/gcs_server --redis_address=10.9.47.15 --redis_port=6379 --log_dir=/tmp/ray/session_2021-11-02_03-20-50_483522_33864/logs --config_list=eyJvYmplY3Rfc3BpbGxpbmdfY29uZmlnIjogIntcInR5cGVcIjogXCJmaWxlc3lzdGVtXCIsIFwicGFyYW1zXCI6IHtcImRpcmVjdG9yeV9wYXRoXCI6IFwiL3RtcC9yYXkvc2Vzc2lvbl8yMDIxLTExLTAyXzAzLTIwLTUwXzQ4MzUyMl8zMzg2NFwifX0iLCAiaXNfZXh0ZXJuYWxfc3RvcmFnZV90eXBlX2ZzIjogdHJ1ZX0= --gcs_server_port=0 --metrics-agent-port=50506 --node-ip-address=10.9.47.15 --redis_password=yul_3
    yuls  33877     1  3 03:20 pts/2    00:00:00 /users/anaconda_data/shared/yuls/ray/bin/python -u /users/anaconda_data/shared/yuls/ray/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py --logs-dir=/tmp/ray/session_2021-11-02_03-20-50_483522_33864/logs --redis-address=10.9.47.15:6379 --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --redis-password=yul_3 --monitor-ip=10.9.47.15
    yuls  33887     1  4 03:20 pts/2    00:00:00 /users/anaconda_data/shared/yuls/ray/bin/python -m ray.util.client.server --redis-address=10.9.47.15:6379 --port=10001 --mode=proxy --redis-password=yul_3 --metrics-agent-port=50506

**Comment by richardliaw** [comment]
Ah, this may be because of a recent aiohttp issue. Can you try running `pip install aiohttp<3.8`?

**Comment by sjulias** [comment]
You absolutely right, 
I've run pip install aiohttp==3.7 , and now it is working
Thank you very much!!!
