### ISSUE TITLE
[Bug]  Ray not initializing with Slurm

### ISSUE THREAD

**Issue by andrewkhardy** [ray-project/ray#19942]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I think I have the same problem as #16009,or possibly #17491, but as this comes from the default [Slurm](https://docs.ray.io/en/latest/cluster/examples/slurm-template.html#slurm-template) template, I think it is worth fixing. Running this default template after putting in my directories and number of cores and whatnot gives me the following error for each worker node 

```
This node has an IP address of 10.20.1._, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
```
The process then only runs on the head node. 
What should be changed in the template? 

I'm also running a Python program and trying to use Ray as a backend to joblib, so I'm confused as to where or not I need to put a `ray.init()` command in the Python program and if I feed it an address and redis password, whether than will distribute to all the worker notes. 

Right now I have a test as 
```
from ray.util.joblib import register_ray  
import ray
import os
from joblib import Parallel,parallel_backend, delayed
from tqdm import tqdm
def TestFunction(x):
    return x**2

#ray.init(address="auto", _redis_password = os.environ["redis_password"])
register_ray()
with parallel_backend("ray"):
   observables  = Parallel(verbose = 10)(delayed(TestFunction)(i) \
					for i in tqdm(range(100)))
```

### Versions / Dependencies

Ray 1.7.0
joblib

### Reproduction script
```
#!/bin/bash
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=1
#SBATCH --account=def-aparamek
#SBATCH --time=23:45:00


# ===== DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING =====
# This script is a modification to the implementation suggest by gregSchwartz18 here:
# https://github.com/ray-project/ray/issues/826#issuecomment-522116599
redis_password=$(uuidgen)
export redis_password

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
nodes_array=($nodes)

node_1=${nodes_array[0]}
ip=$(srun --nodes=1 --ntasks=1 -w "$node_1" hostname --ip-address) # making redis-address

# if we detect a space character in the head node IP, we'll
# convert it to an ipv4 address. This step is optional.
if [[ "$ip" == *" "* ]]; then
  IFS=' ' read -ra ADDR <<< "$ip"
  if [[ ${#ADDR[0]} -gt 16 ]]; then
    ip=${ADDR[1]}
  else
    ip=${ADDR[0]}
  fi
  echo "IPV6 address detected. We split the IPV4 address as $ip"
fi

port=6379
ip_head=$ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "STARTING HEAD at $node_1"
srun --nodes=1 --ntasks=1 -w "$node_1" \
  ray start --head --node-ip-address="$ip" --port=$port --redis-password="$redis_password" --block &
sleep 30

worker_num=$((SLURM_JOB_NUM_NODES - 1)) #number of nodes other than the head node
for ((i = 1; i <= worker_num; i++)); do
  node_i=${nodes_array[$i]}
  echo "STARTING WORKER $i at $node_i"
  srun --nodes=1 --ntasks=1 -w "$node_i" ray start --address "$ip_head" --redis-password="$redis_password" --block &
  sleep 5
done

# ===== Call your code below =====

python raytestcode.py dummy_input
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Reignbeaux** [comment]
I'm currently dealing with the same problem on slurm. I cannot connect a second worker (running on a separate node) to the head node - I get the same message as reported above. Did you find a solution to this?

**Comment by andrewkhardy** [comment]
I have. It's long enough that I don't remember exactly what I did to fix it, but the ray.init is enough. 

ray.init(address="auto", _redis_password = os.environ["redis_password"])
register_ray()  

That default SLURM script should effectively place redis_password and address in the global variable storage.

**Comment by Reignbeaux** [comment]
Yes, his solution did work for me!

**Comment by tupui** [comment]
Ok thank you!

**Comment by tupui** [comment]
@andrewkhardy, maybe some documentation is missing to highlight this.

**Comment by vale981** [comment]
I get this error, but only on one node.
Kind of weird.
And the error message is unfortunately not very helpful as it may appear in many contexts.

**Comment by tupui** [comment]
> I get this error, but only on one node.
> Kind of weird.
> And the error message is unfortunately not very helpful as it may appear in many contexts.

@vale981 did you try to use `auto` to set the address? What about the global env for the redis password? Do you have other Ray instances running?

**Comment by vale981** [comment]
It is my impression that if the ray head is on another node, I will surely have to supply its address. Is that not so?

**Comment by tupui** [comment]
@vale981 We need more details on your setup and the commands/actions you tried.

**Comment by Chengeng-Yang** [comment]
> I have. It's long enough that I don't remember exactly what I did to fix it, but the ray.init is enough.
> 
> ray.init(address="auto", _redis_password = os.environ["redis_password"]) register_ray()
> 
> That default SLURM script should effectively place redis_password and address in the global variable storage.

Hello @andrewkhardy , I'm having the same issue (https://discuss.ray.io/t/ray-on-slurm-different-ip-addresses-of-worker-nodes/6071), could I ask did you find a way to edit the slurm template to fix this issue? Many thanks!
