### ISSUE TITLE
[Bug] ImportError: Not all Ray Dashboard dependencies were found.

### ISSUE THREAD

**Issue by alvin-yang68** [ray-project/ray#19956]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

`ray.init(include_dashboard=True)` throws ImportError: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`.

This issue was encountered on both Windows 10 and Ubuntu 20.04. Running `pip install ray[default]` did not fix the issue. 

### Versions / Dependencies

Ray 1.7.0
Python 3.8.10
Windows 10

### Reproduction script

```
import ray
ray.init(include_dashboard=True)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nocluebutalotofit** [comment]
Same problem with
Ray 1.7.0
aiohttp 3.8.0
Python 3.9.5
macOS Big Sur

```
import aiohttp.signals
from aiohttp.frozenlist import FrozenList  # noqa: F401
```
fail with aiohttp 3.8.0 which is permitted by ray/python/requirements.txt which says aiohttp>=3.7

**Comment by nocluebutalotofit** [comment]
> Getting the same problem due to aiohttp 3.8.0 that released breaking changes :(

Yes, that is why simple downgrading ray does not help.

**Comment by dennymarcels** [comment]
Same.
Ray 1.8 and 1.7
Python 3.9
Debian 11

**Comment by nocluebutalotofit** [comment]
> Same. Ray 1.8 and 1.7 Python 3.9 Debian 11
> 
> I confirm that downgrading aiohttp to 3.7 solves it temporarily.
This should be reflected in ray/python/requirements.txt:
Instead of "aiohttp>=3.7" something like "aiohttp=3.7".

**Comment by jamesmishra** [comment]
I think this issue was fixed when PR https://github.com/ray-project/ray/pull/20261 landed on master.
