### ISSUE TITLE
[Tune] test_trial_requeue fails due to pg caching

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19952]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

When removing legacy resources, I noticed that if a node is taken out from the cluster, the corresponding PG is still recycled to place another trial on it.

To reproduce, use `test_trial_requeue`. set `TUNE_PLACEMENT_GROUP_AUTO_DISABLED` to `False` (to enable using PG).

This is bad, as the node is already dead and no more trials should be placed on it. (The test just hangs on waiting for training result)

The solution is to not cache PG anymore. However, I also need to check if/how the same issue won't show up in `reuse_actors` scheme. 

### Versions / Dependencies

master

### Reproduction script

test_trial_requeue

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
cc @krfricke @Yard1 
I would wish PG to be some kind of "lease" for putting some computing tasks on some node. This lease's validity should be synchronized in best effort to reflect the current status. This doesn't seem to be the case.
In a more general case, can the following sequence happen? pg.ready() returns true --> node is down --> pg.ready() still returns true --> a trial is placed onto that pg --> the trial hangs forever.

**Comment by rkooo567** [comment]
Actually, if this `When removing legacy resources, I noticed that if a node is taken out from the cluster, the corresponding PG is still recycled to place another trial on it.` happens, placement group scheduler is supposed to re-create bundles on a dead node to other nodes. Do you see this cause hanging or sth like that?

**Comment by xwjiang2010** [comment]
Thansk Sang! So there are actually some mechanisms there. Good to know! I am gonna check it out using a real cluster. `test_trial_requeue` is emulating a cluster for unit test, I don't know how realistic the set up is. 
If there are discrepancies, maybe we should just move relevant tests to use real multi-node set up, the ones that Kai was setting up recently.

**Comment by xwjiang2010** [comment]
Tried a small example to showcase the following scenario:
1. start a cluster with empty head and one worker node
2. start a trial successfully on the worker node
3. while the trial is running on worker node, the cluster lost the worker node
4. as a result, `ray.exceptions.RayActorError` is thrown
5. try to put another trial onto the pg without checking for pg.ready() (which is the current implementation in Tune) leaves the false impression that the trial is RUNNING when it's actually PENDING. 
```
def test_failed_pg(start_connected_emptyhead_cluster):

    cluster = start_connected_emptyhead_cluster
    node = cluster.add_node(num_cpus=1)
    cluster.wait_for_nodes()

    class Trainer:
        def __init__(self):
            pass

        def train(self):
            print("In train() function.")
            time.sleep(10)
            return 5

    from ray.util.placement_group import placement_group
    pg = placement_group([{"CPU": 1}])
    ray.get(pg.ready())
    actor1 = ray.remote(Trainer).options(
        placement_group=pg,
        placement_group_bundle_index=0,
        placement_group_capture_child_tasks=True,
        num_cpus=1,
        num_gpus=0,
        resources=None).remote()
    print("actor1 is placed!")
    train_future = actor1.train.remote()
    time.sleep(1).
    cluster.remove_node(node)
    cluster.wait_for_nodes()
    try:
        ray.get(train_future)  # should print out actor dead error
    except ray.exceptions.RayActorError:
        pass
    import ipdb; ipdb.set_trace()  # pg.ready() hangs here as expected.
    # We should check for pg.ready() again when putting another trial onto the pg.
    # The expected behavior should be hanging as we have removed all nodes from the cluster by now.
    actor2 = ray.remote(Trainer).options(
        placement_group=pg,
        placement_group_bundle_index=0,
        placement_group_capture_child_tasks=True,
        num_cpus=1,
        num_gpus=0,
        resources=None).remote()
    print("actor2 is placed!")
    ray.get(actor2.train.remote())
```

But if we add 
```
    # re-adding the node.
    cluster.add_node(num_cpus=1)
    ray.get(pg.ready())
```
before placing `actor2`, actor2 will be successfully placed and ran. So seems like Core is managing "moving" placement groups from dead nodes to living nodes.

Question to @rkooo567, what is the API guarantee here? If a pg is ready at any moment, before it is returned back to Core, can we assume that there is always meaningful resources associated with this pg (even after the node it was originally on is dead)? We are in the process of ditching pg caching anyways, but want to understand this nuance more for documentation purposes. Thanks!

**Comment by rkooo567** [comment]
> Question to @rkooo567, what is the API guarantee here? If a pg is ready at any moment, before it is returned back to Core, can we assume that there is always meaningful resources associated with this pg (even after the node it was originally on is dead)? We are in the process of ditching pg caching anyways, but want to understand this nuance more for documentation purposes. Thanks!

Currently, the guarantee is same as regular actor/task based workload. We rely on the autoscaler that it will start up a proper node and the dead bundles are recovered properly. This is the best-efforts-based, and the guarantee is not so strong right now (it can hang if bundles are not re-created properly because of resource race with other actors / tasks).

**Comment by xwjiang2010** [comment]
Patching https://github.com/ray-project/ray/pull/19515/files makes the test pass.
@Yard1 this is sort of a different change. I think the reason of why that test is failing is understood, we just need to merge the changes one by one. I don't want to squash everything into one PR, if it's ok with you guys.
