### ISSUE TITLE
[Tune] pg does not support empty bundle resources 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19959]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Specifically, this won't work after fully switching to pg: https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/tests/test_api.py?L280

Should we just remove this test case and make it clear in the API this is not supported?

### Versions / Dependencies

master

### Reproduction script

pytest -s python/ray/tune/tests/test_api.py::TrainableFunctionApiTest::testBuiltInTrainableResources

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I think it makes sense to remove the test? Empty bundle doesn't really make sense (it means the pg is not usable)

**Comment by rkooo567** [comment]
Actually, it is kind of possible to use empty bundle if the purpose is to schedule 0 resource tasks/actors to the same bundle. So, we can theoretically remove this input validation
