### ISSUE TITLE
[Bug] SegFault on Ubuntu 20.04 when creating actor

### ISSUE THREAD

**Issue by ysx001** [ray-project/ray#19967]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When running simulation on ubuntu 20.04, create_actor seg faults with the below error. It works fine on MacOS.

https://github.com/ray-project/ray/blob/f101f7cc02e9388680f4ad8ccb49325f2cabcc53/python/ray/actor.py#L785-L805

```> /home/sarah/anaconda3/envs/py38/lib/python3.8/site-packages/ray/actor.py(772)_remote()
-> actor_handle = ActorHandle(
(Pdb) (pid=122834) *** SIGSEGV received at time=1635821659 on cpu 0 ***
(pid=122834) PC: @     0x563d235c5d17  (unknown)  _PyErr_SetObject
(pid=122834)     @     0x7fa5917f23c0  (unknown)  (unknown)
(pid=122834)     @     0x563d237f79a0  (unknown)  (unknown)
(pid=122834) [2021-11-01 19:54:19,101 E 122834 122834] logging.cc:315: *** SIGSEGV received at time=1635821659 on cpu 0 ***
(pid=122834) [2021-11-01 19:54:19,101 E 122834 122834] logging.cc:315: PC: @     0x563d235c5d17  (unknown)  _PyErr_SetObject
(pid=122834) [2021-11-01 19:54:19,104 E 122834 122834] logging.cc:315:     @     0x7fa5917f23c0  (unknown)  (unknown)
(pid=122834) [2021-11-01 19:54:19,107 E 122834 122834] logging.cc:315:     @     0x563d237f79a0  (unknown)  (unknown)
2021-11-01 19:54:19,404	WARNING worker.py:1227 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffba86a762419ad8570a7bf7a901000000 Worker ID: 49f11065af37d8717eb7f85a94d133cfa5cb51502c407f5bbdf1b7db Node ID: 63b3745b9563a5e434f3b0233de8625e2bf6e73a1bf00443fb720aaf Worker IP address: 100.80.143.11 Worker port: 45381 Worker PID: 122834
```

### Versions / Dependencies

Ray 1.7.0
Python: 3.8
OS: ubuntu 20.04

### Reproduction script

https://github.com/yunfanjiang/cs238-rps/blob/main/exp_scripts/baselines/a3c.py

run with python3 a3c.py --bot_policy pure_rock --num_gpus 0

### Anything else

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
The link seems to be not available. Can you check the security settings? https://github.com/yunfanjiang/cs238-rps/blob/main/exp_scripts/baselines/a3c.py

**Comment by ysx001** [comment]
We pulled the latest code from ray repo and build from scratch (instead of install with pip), and the code was able to run successfully. Maybe it was a bug fixed in the latest version and you need to bloom release it. Closing the issue for now.
