### ISSUE TITLE
[Bug] MLFlow nested runs don't work with Ray

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/ray#19978]
I'm trying to run 100 different regression models for 100 products (distributed using Ray and joblib) and track them using MLFlow. I want to group the 100 models under a single run so I use a parent MLFlow run function which calls a nested child MLFlow run function. But when I run it, it shows up as 101 seperate experiments on MLFlow UI. The experiments are properly nested when I use a simple for loop but doesn't work as expected using Ray

**Comment by einarbmag** [comment]
Bump. I think the best practice when logging hyperparameter tuning trials to MLflow is to use nested runs, so this should be offered with the MLflowLoggerCallback, if not the default.
