### ISSUE TITLE
[Tune] test_api.py::testBuiltInTrainableResources failing after using PG path 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19985]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

`pytest -s python/ray/tune/tests/test_api.py::TrainableFunctionApiTest::testBuiltInTrainableResources`

Stuck in `pending` forever, without raising TuneError.

This is due to the fact that Tune cannot reliably detect if autoscaler is used or not: https://github.com/ray-project/ray/issues/18608

### Versions / Dependencies

master

### Reproduction script

`pytest -s python/ray/tune/tests/test_api.py::TrainableFunctionApiTest::testBuiltInTrainableResources`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@ericl 
Do you think it makes sense for Core to expose an API to tell Tune if autoscaler is used or not?
Current way of relying on bootstrap file is not reliable, as discovered in #18608. 
cc @richardliaw

**Comment by ericl** [comment]
We should probably just have the autoscaler raise the error if the placement group is infeasible. Maybe we can prioritize for next Sprint? Cc @rkooo567 @scv119

**Comment by xwjiang2010** [comment]
Yeah, maybe just something that let pg.ready() return instead of hang forever.

**Comment by rkooo567** [comment]
@xwjiang2010 I think in the master, we always start the autoscaler. I agree we can prioritize https://github.com/ray-project/ray/issues/18835

**Comment by xwjiang2010** [comment]
Thanks @rkooo567 It would be great to know your timeline.  We have some Tune tech debt reduction work that's dependent on this ticket.
btw, to get the terminology correct, the request is less about knowing whether autoscaler is "used" than knowing if a pg request is feasible or not.

**Comment by rkooo567** [comment]
We are planning to work on it next sprint. I think the task is quite complicated, so it might take some time. 

That says, is there any short-term workaround for you? I wonder if you can add timeout to .ready or use .wait API instead
