### ISSUE TITLE
[Feature]  Add link checking to CI

### ISSUE THREAD

**Issue by kcpevey** [ray-project/ray#19980]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

There are some broken links in the docs. We can check for valid links in ci by using 
```
sphinx-build -b linkchecker
```

I'd be happy to implement this if its desired. I'd just need someone to suggest the proper location for this. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
Hey, thanks for opening this issue!

The problem with linkchecker is that it often just causes github to start throwing 404s/400s iirc. Did you experience this? is there something we can do to address this?

**Comment by kcpevey** [comment]
I haven't seen this. It did find that some links were 404s, but those appeared to be valid. For example, here is a snippet of the output:
```
(line  184) ok        https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn
(line  588) redirect  https://github.com/ray-project/xgboost_ray/tree/master/examples/ - permanently to https://github.com/ray-project/xgboost_ray/blob/master/examples
(line  595) broken    https://github.com/ray-project/xgboost_ray/tree/master/examples/higgs_parquet.py - 404 Client Error: Not Found for url: https://github.com/ray-project/xgboost_ray/tree/master/examples/higgs_parquet.py
(line  592) broken    https://github.com/ray-project/xgboost_ray/tree/master/examples/simple.py - 404 Client Error: Not Found for url: https://github.com/ray-project/xgboost_ray/tree/master/examples/simple.py
(line  593) broken    https://github.com/ray-project/xgboost_ray/tree/master/examples/higgs.py - 404 Client Error: Not Found for url: https://github.com/ray-project/xgboost_ray/tree/master/examples/higgs.py
(line  612) ok        https://xgboost.readthedocs.io/en/latest/treemethod.html
(line  612) ok        https://xgboost.readthedocs.io/en/latest/treemethod.html
(line  596) broken    https://github.com/ray-project/xgboost_ray/tree/master/examples/train_on_test_data.py - 404 Client Error: Not Found for url: https://github.com/ray-project/xgboost_ray/tree/master/examples/train_on_test_data.py
(line    4) ok        https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html
```
Do you mean you added it to github actions and it caused 404s (outside of the report generation above) when it was run there?

**Comment by pcmoritz** [comment]
I made some progress in https://github.com/ray-project/ray/pull/20030 and added it to the README and fixed the links. Currently it is a bit too flaky to run it in the CI I think.
