### ISSUE TITLE
[Bug] [RLlib] Callback on_learn_on_batch inconsistent

### ISSUE THREAD

**Issue by SebastianBo1995** [ray-project/ray#19993]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When using the callback on_learn_on_batch there is no access to the "infos" dict when using the default framework. When setting the framework to tf2, there is access to the infos dict. 

Since access to the infos dict can be mandatory for the HER Algorithm it would be great to always generate the Sample Batch with the infos dict. #8526

### Versions / Dependencies

v1.7 and v1.8 tested

### Reproduction script

https://colab.research.google.com/drive/1BxyoHYcCcLMfO9arMWhirtvDHDkLWcuB?usp=sharing

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SebastianBo1995** [comment]
Update: Seems to be comming from https://github.com/ray-project/ray/blob/master/rllib/policy/tf_policy.py
Lines 190ff: 
```
        # Disable env-info placeholder.
        if SampleBatch.INFOS in self.view_requirements:
            self.view_requirements[SampleBatch.INFOS].used_for_training = False
            self.view_requirements[
                SampleBatch.INFOS].used_for_compute_actions = False
```

where the infos dict gets disabled. Any way to enble it from outside without changing the tf_policy.py? 

Still a consistent behaviour would be desireable  😄

**Comment by amogkam** [comment]
cc @gjoliver

**Comment by gjoliver** [comment]
we should make things consistent.
can you share your script with me?
will take a look.

**Comment by SebastianBo1995** [comment]
Changes permissions for the colab 
https://colab.research.google.com/drive/1BxyoHYcCcLMfO9arMWhirtvDHDkLWcuB?usp=sharing

**Comment by gjoliver** [comment]
Looking around, I think the reason tf2 supports info_dict while tf doesn't is because the sample batch gets converted into a feed_dict for forward pass in tf1. the nn has no idea about these fields and will error out if we don't get rid of it.
Not sure what's the best fix here actually, can you use a callback that happens before post-processing?
I will discuss a bit among the team.

**Comment by gjoliver** [comment]
Hi Sebastian, I chatted with the team, it is not clear what is the best way for us to support this in tf1.
Any reason you can't use tf2? We have recently made some improvements to make sure that tf2 is as performant as tf1.
Also not sure what exactly is your use case, still think maybe we can do this some other way.
I am gonna close this issue for now. Please reopen if this really is a show stopper for you somehow.

**Comment by SebastianBo1995** [comment]
Hi @gjoliver  

my use case would be the Hindsight experience Replay. Therefore I have to acess the infos dict to get the "goal". 

The main problem arised, when sharing the code for the callback. And the other person using another framework. If you just close it as is, it would be great to add it to the documentation: https://docs.ray.io/en/latest/rllib-training.html#callbacks-and-custom-metrics. 

Or rather in the docstring.

**Comment by gjoliver** [comment]
sure, I will add it to the docstring. thanks for suggesting documentation improvements actually.
