### ISSUE TITLE
Broken link for offline RL in docs

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#20003]
This link is broken:

https://github.com/ray-project/ray/tree/master/rllib/examples/serving/offline_rl.py

It's the first example under here:

https://docs.ray.io/en/latest/rllib-examples.html#serving-and-offline

Can we replace with an offline RL example? Popular among users.

**Comment by sven1977** [comment]
This has been fixed in master. The problem was the additional `examples/serving` sub-directory. However, the script sits directly in `examples/`.
Closing this issue.
