### ISSUE TITLE
[ray client] Get ObjectRef within remote function doesn’t work with Ray Client and Jupyter Notebook 

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#20012]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Get ObjectRef within remote function doesn’t work with Ray Client and Jupyter Notebook.
Discussion here: https://discuss.ray.io/t/get-objectref-within-remote-function-doesnt-work-with-ray-client-and-jupyter-notebook/3902

I will look into reproducing the problem and adding more details here.

### Versions / Dependencies

JupyterLab 3.1.13
Ray 1.7.0

### Reproduction script

Some details here:
https://discuss.ray.io/t/get-objectref-within-remote-function-doesnt-work-with-ray-client-and-jupyter-notebook/3902

More details to come.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @ckw017

**Comment by DmitriGekhtman** [comment]
According to discuss.ray.io discussion, resolved on Ray 1.8.0
Closing for now -- might be good to double check that things are ok.

**Comment by peterghaddad** [comment]
Hi @DmitriGekhtman, I am seeing this issue when running Tune Experiments in Ray 2.0. Should we open this issue back up? I can give more details.

**Comment by peterghaddad** [comment]
@DmitriGekhtman is there a reason we are closing this issue? Are we saying that we are always supposed to use the job sdk? When would we want to use the Ray Client then? Just trying to understand. Thanks!
