### ISSUE TITLE
[Bug]  no error in the log and no dashboard process

### ISSUE THREAD

**Issue by yiwei00000** [ray-project/ray#20017]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

When I use ray version 1.8.0, I use the command ray start --head --port = 6379 --dashboard host = 0.0.0. After starting, there is no error in the log, but there is no dashboard process, and I can't access ray dashboard in the browser

### Versions / Dependencies

ray 1.8.0

### Reproduction script

ray start --head --port=6379 --dashboard-host=0.0.0.0

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @edoakes @simon-mo

**Comment by simon-mo** [comment]
Can you add `--include-dashboard=true`?

**Comment by jfischer** [comment]
Hi, I ran into the same issue. I'm starting ray with the following command line:
```
ray start --head --dashboard-host=0.0.0.0 --include-dashboard=true --block
```

I added a print to my local copy of Ray to get the exact cause of the import error. This is the error: `No module named 'aiohttp.signals'`

In my environment, I'm using version 3.8.0 of aiohttp. It does not have a `signals` submodule. Looking at the commit history for aiohttp, I suspect the following change is causing the problem: https://github.com/aio-libs/aiohttp/commit/7f0cd0d3bfbd3566b3035f670c8f351836c1ba08#diff-2f6aee0ecbf53b6b3760ba0a15c5cbc47898bdcdab1db521a63ad99a7bca3d98

**Comment by simon-mo** [comment]
yes. please downgrade aiohttp to <3.8 for now. https://github.com/ray-project/ray/issues/19940#issuecomment-961304640 We currently pinned the version in development branch and will make Ray compatible with 3.8.0 soon https://github.com/ray-project/ray/issues/19951
