### ISSUE TITLE
[Bug] [RLLib] Bug when doing eval episodes without exploration

### ISSUE THREAD

**Issue by SebastianBo1995** [ray-project/ray#20021]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When setting explore to False and doing evaluation episodes, there is a mismatch between numpy an tf variable of the "last_timestep". 

  ```
  @override(Exploration)
    def set_state(self, state: dict,
                  sess: Optional["tf.Session"] = None) -> None:
        if self.framework == "tf":
            self.last_timestep.load(state["last_timestep"], session=sess)
        else:
            self.last_timestep = state["last_timestep"]
```

### Versions / Dependencies

V1.8

### Reproduction script

https://colab.research.google.com/drive/1GgaW8hBF8UpaHDD000whWx7pTHLXFz77?usp=sharing

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SebastianBo1995** [comment]
Seems to be fixed in the latest branch: https://github.com/ray-project/ray/blob/e6ae08f41674d2ac1423f3c2a4f8d8bd3500379a/rllib/utils/exploration/gaussian_noise.py
from yesterday.

**Comment by sven1977** [comment]
Awesome, thanks @SebastianBo1995  for confirming the fix. Closing this now. Feel free to re-open should the bug occur again.
