### ISSUE TITLE
[Bug] Ray 2.0 nightlies not reflecting current master

### ISSUE THREAD

**Issue by rhamnett** [ray-project/ray#20027]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Tune

### What happened + What you expected to happen

Hello @richard4912  I am using a 2.0 py3.7 nightly installed today from link https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl  

pip install -U --no-cache-dir https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

It doesn’t seem to contain this PR from 20 days ago. Is this expected? https://github.com/ray-project/ray/pull/19321

### Versions / Dependencies

2.0 nightly

### Reproduction script

pip install -U --no-cache-dir https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
Current latest wheel should contains commit https://github.com/ray-project/ray/commit/3d7d341dd0003723124c171c5a0206b0a3793c44

I verified it by
```
wget https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
unzip ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
ray-2.0.0.dev0.data/purelib/ray
grep commit __init__.py
```

```
88:__commit__ = "3d7d341dd0003723124c171c5a0206b0a3793c44"
```

Can you make sure to `pip uninstall -y ray; pip install ...`? Sometimes when you already have nightly installed, pip will not re-install when with `-U` because the version string is the same `2.0.0.dev0`.

**Comment by rhamnett** [comment]
Aha! I had not correctly uninstalled the previous version. 

Perhaps a note would be useful on the nightly section explaining this. 

Many thanks

**Comment by simon-mo** [comment]
> Perhaps a note would be useful on the nightly section explaining this.

Feel free to open a PR changing https://github.com/ray-project/ray/blob/master/doc/source/installation.rst ;-)

**Comment by rhamnett** [comment]
As you wish! https://github.com/ray-project/ray/pull/20034

**Comment by rhamnett** [comment]
hi @simon-mo this does not seem to be live on the website. https://docs.ray.io/en/latest/installation.html

Best wishes

**Comment by simon-mo** [comment]
Try https://docs.ray.io/en/master/installation.html

The latest points to latest pip release which we do roughly once a month.

**Comment by rhamnett** [comment]
ah cool :)
