### ISSUE TITLE
[rllib] RunningStat.push error

### ISSUE THREAD

**Issue by linshiyx** [ray-project/ray#2004]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 3.5.4
- **Exact command to reproduce**:

### Describe the problem
TypeError: 'numpy.float64' object does not support item assignment  
The error is encounted at line 43 ```self._M[...] += delta / self._n``` In rllib/utils/filter.py.
I think the reason is as follows:  
If the shape of the RunningStat is (), then the type of M in RunningStat is supposed to be numpy.ndarray. But line 46 ```M = (n1 * self._M + n2 * other._M) / n``` makes the type of M become numpy.float64. And numpy.float64 does not support item assignment. So I think line 43 should be ```self._M += delta / self._n```.

### Source code / logs
line 43 in rllib/utils/filter.py.
----------------------- this code works fine -----------------
self._M += delta / self._n
----------------------- this code fails -----------------------
self._M[...] += delta / self._n

**Comment by robertnishihara** [comment]
Do you have a code example or script that reproduces the problem?

**Comment by linshiyx** [comment]
@robertnishihara Here's a simple script.
```
import numpy as np

a = np.zeros(())
a[...] = 2  # it works
print(a)

b = 1
c = a * b
print(type(c))
try:
    c[...] = 3  # TypeError: 'numpy.float64' object does not support item assignment
except TypeError:
    print('TypeError')
```

**Comment by robertnishihara** [comment]
Thanks, what I meant was do you have a code example that causes the bug to happen in rllib?

**Comment by linshiyx** [comment]
@robertnishihara I make some changes to your ppo, and use `local_evaluator` to generate data. 
```
local_evaluator.sample()
```
which is not in your code.
The reason that it doesn't appear in your code is because:
Though type of `self._M` is `<class 'numpy.float64'>` in `local_evaluator.rew_filter.rs`. With `other._M = np.copy(self._M)` in RunningStat.as_serializable(),  type of `other._M` becomes `<class 'numpy.ndarray'>` again. So in RemoteEvaluators it wouldn't be a problem.
And if you have already considered this case and not allow `local_evaluator` to generate data, you can just leave it alone :).

**Comment by richardliaw** [comment]
Sounds good - I think we will leave it as is :)
