### ISSUE TITLE
[Core] have the autoscaler raise the error if the placement group is infeasible 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#20043]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Context: https://github.com/ray-project/ray/issues/19985

### Versions / Dependencies

NA

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@scv119 @rkooo567

**Comment by rkooo567** [comment]
I think this should already be supported. cc @ericl can you confirm it?

**Comment by ericl** [comment]
It's definitely not supported (we have a P1 usability issue files on this...).

**Comment by rkooo567** [comment]
Oh I see. We are only printing messages now right?

**Comment by rkooo567** [comment]
I think we can close this issue as a duplicate; https://github.com/ray-project/ray/issues/18835
