### ISSUE TITLE
[Bug] [Placement Group] [Test]  pg.ready() hang forever when GCS server restarting.

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#20058]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

`test_placement_group_3.py#test_create_placement_group_during_gcs_server_restart` flaky on master branch.
currently, it was skipped.

### Versions / Dependencies

None.

### Reproduction script

None.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clay4444** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
Duplicate; https://github.com/ray-project/ray/issues/19671 Can you take it over? I will close the duplicated one

**Comment by clay4444** [comment]
@rkooo567  oh, sorry,  I missed the one you created. sure, I will take it over.
