### ISSUE TITLE
[Bug] Can not start Ray with Apache Arrow flight on mac

### ISSUE THREAD

**Issue by mmuru** [ray-project/ray#20068]
Using Ray 1.8.0 and PyArrow 6.0.0 (or 5.0.0) - Ray throws below error message on Mac. 
````
self.global_state_accessor.connect() in _really_init_global_state method throws Abort trap: 6.
````
However, it works on Linux environment. Please, see [https://discuss.ray.io/t/can-not-start-ray-with-arrow-flight-segmentation-fault-11/3898](url) for more information. 

I think, it is a bug on Mac platform. Please, let me know how to resolve it. Thanks.

**Comment by infzo** [comment]
I had the same problem. It is clear that:
1. In the Linux environment
2. PyArrow is installed using conda, but PIP does not have this problem.
3. This problem exists in both PyArrow 5.0.0 and PyArrow 6.0.0.
4. The Ray version is the latest version, including the preview version.

```
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.flight
>>> import ray
>>> ray.init()
2021-11-11 11:20:16,367 INFO services.py:1331 -- View the Ray dashboard at http://127.0.0.1:8265
Aborted (core dumped)
```

**Comment by mmuru** [comment]
@architkulkarni: Please, review this issue and provide an update. Thanks.

**Comment by architkulkarni** [comment]
I don't know much about PyArrow unfortunately, @clarkzinzow @jjyao do you have any ideas about this or know who should triage it?

**Comment by jjyao** [comment]
Sorry for the late reply. I'll take a look.

**Comment by jjyao** [comment]
@mmuru Could you try the latest daily build, seems the issue has been fixed in master.

**Comment by mmuru** [comment]
@jjyao: Yes, it works now with the latest daily build. Thanks for your help. Could you tell me what was the issue?

**Comment by jjyao** [comment]
I think it's related to #20132
