### ISSUE TITLE
Example of policy inference

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#20062]
We need an example of policy inference for RLlib in the docs. 

Could we include it in the intro example?

https://docs.ray.io/en/latest/rllib.html

I think it's important to show how users can actually use the thing they just trained when they are getting started to envision the end result.

**Comment by worldveil** [comment]
I'll also be adding a page or section in the docs (this page perhaps: https://docs.ray.io/en/latest/rllib-models.html ?), but once I have the example I can do the writing portion

**Comment by sven1977** [comment]
Added 3 scripts (normal case, LSTM, attention) to the examples folder and linked to the simple one from the RLlib index docs page. Closing this issue now.
