### ISSUE TITLE
[Bug] "PENDING_CREATION" status issue, and related resubmission problem. [non-head node]

### ISSUE THREAD

**Issue by DarcyOly** [ray-project/ray#20092]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Bugs and actor's creating problem:
1. Actor's status is frozen at "PENDING_CREATION", when register an actor from non-head nodes.
 ```
   class RemoteProc(Object): ...
        def __init__(self):
            pass
        def procTask(self, a, b):
            print('[%s]-> %s' % (a, b))
    RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
```

   Dashboard shows this registered actor is remaining "PENDING_CREATION".
   It's neccessory to submit actor from other nodes, or at least to refuse these node's register submission and raise warnning.

2. Related problem with "PENDING_CREATION" actor. 
`proc= ray.get_actor('test', namespace='xxx')`
    a. This code could get "PENDING_CREATION" status actor, without status check. (this status shall be invalid, instead of obtainable). And actor will hang forever if tried to run it.
    b. This actor handler can be called by api: "ray.kill", without any logging. While dashboard shows the status turn to be "DEAD" in this namespace. After killing, if we wanna re-submit the same actor with "RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()", error " ailed to create actor" raised, and eventually  the terminal will crash.

Attachments.
Bug 1: 

b120ed0ac5c738a7a75892be09000000(0) | testProc | __main__ RemoteProc __init__ 9f8e28f28c3a4a1099b47adf8627c1b... | 09000000 | 0 |   | 0 | DEAD |  
-- | -- | -- | -- | -- | -- | -- | -- | --
acef0c60c51301feb1e7a33a0a000000(0) | testProc | __main__ RemoteProc __init__ 5ed1054cf7954252a28a25a55d6d681... | 0a000000 | 0 |   | 0 | DEAD |  
7d074daae2438b4f82c8755d0e000000(0) | testProc1 | __main__ RemoteProc __init__ 6487bdf6d75247689727eaae682024b... | 0e000000 | 0 |   | 0 | PENDING_CREATION |  
6d709b216bc19cdf77ce4a5310000000(0) | test | __main__ RemoteProc __init__ a09dfd3bd548485fa3f417fd9542ded... | 10000000 | 0 |   | 0 | PENDING_CREATION |  
77c3d47d01bce6d99a3c412211000000(0) | test | __main__ RemoteProc __init__ 6e6adfbbabe84c31a7617235ab8199f... | 11000000 | 94958 | 172.16.xxx.xxx | 10022 | Active

Bug 2:
In [8]: RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='nvh').remote()
[2021-11-05 10:33:06,468 E 94924 94948] direct_task_transport.cc:61: Failed to create actor ceab7a792cab03c5646a394511000000 with status: Invalid: Actor may be already destroyed.
Out[8]: Actor(RemoteProc, ceab7a792cab03c5646a394511000000)

In [9]: 2021-11-05 10:33:06,480	WARNING worker.py:1227 -- 3 retries left for task ffffffffffffffffceab7a792cab03c5646a394511000000, attempting to resubmit.
(pid=gcs_server) [2021-11-05 10:33:06,467 E 60903 60903] gcs_actor_manager.cc:148: Failed to register actor: Invalid: Actor with name 'test' already exists., job id = 11000000, actor id = ceab7a792cab03c5646a394511000000
(pid=gcs_server) [2021-11-05 10:33:06,468 E 60903 60903] gcs_actor_manager.cc:174: Failed to create actor, job id = 11000000, actor id = ceab7a792cab03c5646a394511000000, status: Invalid: Actor may be already destroyed.

(pid=gcs_server) [2021-11-05 10:33:12,050 E 60903 60903] gcs_actor_manager.cc:148: Failed to register actor: Invalid: Actor with name 'test' already exists., job id = 11000000, actor id = ceab7a792cab03c5646a394511000000
In [9]: [2021-11-05 10:33:17,251 C 94924 94948] core_worker.cc:966:  Check failed: _s.ok() Bad status: TimedOut: There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::CoreWorker::InternalHeartbeat()
    ray::PeriodicalRunner::DoRunFnPeriodically()
    ray::PeriodicalRunner::DoRunFnPeriodically()::{lambda()#1}::operator()()
    boost::asio::detail::executor_function<>::do_complete()
    boost::asio::io_context::executor_type::dispatch<>()
    boost::asio::detail::wait_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    ray::core::CoreWorker::RunIOService()
    execute_native_thread_routine

### Versions / Dependencies

Ubuntu 16.04
Ray 1.7.1

### Reproduction script

```
## This code is running on child node.
import ray
ray.init('auto')

@ray.remote(num_cpus=1)
class RemoteProc(object):
    def __init__(self):
        pass

    def procTask(self, a, b):
        print('[%s]-> %s' % (a, b))

RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
proc = ray.get_actor('test', namespace='xxx')
ray.get(proc.procTask.remote(1,2))
# Kill and resubmit
# ray.kill(proc)
# RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DarcyOly** [comment]
src\ray\gcs\gcs_server\gcs_actor_manager.cc :
...
Status GcsActorManager::RegisterActor(const ray::rpc::RegisterActorRequest &request,
                                      RegisterActorCallback success_callback) {
    ...
    auto actor = std::make_shared<GcsActor>(request.task_spec(), ray_namespace);
    if (!actor->GetName().empty()) {
        ...
    } else {
        std::stringstream stream;
        stream << "Actor with name '" << actor->GetName() << "' already exists.";
        return Status::Invalid(stream.str());
    }
}

Seems like "GcsActorManager" wouldn't check refed actor's current status, only validate actor's name. Leading to unsuspected failure when submit duplicate-name Actor (same namespace). 
Cause of unittest requirement, we need submit and kill the same actor for couple of times, hope this bug can be fixed asap. 
Thx a lot.

**Comment by ericl** [comment]
@rkooo567 this seems like another manifestation of this P0 bug (incorrect concurrency handling for named actor creation): https://github.com/ray-project/ray/issues/19896

**Comment by DarcyOly** [comment]
> @rkooo567 this seems like another manifestation of this P0 bug (incorrect concurrency handling for named actor creation): #19896

it's correct, the same. Thanks for help.
this one will be closed.
