### ISSUE TITLE
[Bug] ray.wait against a single object is not allowed

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#20101]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Invoking `ray.wait` against a single object ref raises an error. Expected to behave the same as waiting for a list with a single object.

```
>>> obj = ray.put(1)
>>> ray.wait(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yangkai/.pyenv/versions/3.7.9/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/yangkai/.pyenv/versions/3.7.9/lib/python3.7/site-packages/ray/worker.py", line 1761, in wait
    "wait() expected a list of ray.ObjectRef, got a single "
TypeError: wait() expected a list of ray.ObjectRef, got a single ray.ObjectRef
```

### Versions / Dependencies

1.8.0

### Reproduction script

```python
import ray
ray.init()
obj = ray.put(1)
ray.wait(obj)
```

### Anything else

This also applies to Java/C++ worker. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
you can just do this? (per error message)
```
ray.wait([obj])
```
