### ISSUE TITLE
[Bug] Dask on Ray set_index causes rows to disappear

### ISSUE THREAD

**Issue by crclark** [ray-project/ray#20108]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

After loading a Dask dataframe from a directory of Parquet on GCS, calling `.set_index('some_string_column')` on the dataframe will cause a large random number of rows to disappear from the dataframe.

- If `compute=False` is passed to `.set_index()`, the rows will temporarily disappear. Sleeping for a while will return correct results. However, I don't know how long I should sleep in general.
- If `compute=True` is passed to `.set_index()`, the rows seem to disappear forever (though maybe I just need to wait longer).

### Versions / Dependencies

- dask=2021.10.0=pyhd8ed1ab_0
- dask-core=2021.10.0=pyhd8ed1ab_0
- ray==1.7.0

### Reproduction script

```
import dask
import dask.dataframe as dd
import dask.array as da
import ray
from ray.util.dask import ray_dask_get

ray.init(address="auto")
dask.config.set(scheduler=ray_dask_get) # comment this line out and the numbers below are all equal

# In my test data, this df has about 2.7 million rows
df = dd.read_parquet('gs://some/path/with/parquet/files')
df = df.set_index('some_string_column') # comment this line out and the numbers below are all equal

# If compute=False, each of the prints below will return random increasing numbers.
# If compute=True, each of the prints below will return the same random incorrect number.
print(sum(df.map_partitions(len).compute()))
print(sum(df.map_partitions(len).compute()))
print(sum(df.map_partitions(len).compute()))

# If compute=False, this print will always show the correct result
# If compute=True, this print will show the same wrong number as all of the above 
print(len(df))
```

### Anything else

This only happens when the `ray_dask_get` scheduler is used. With the default Dask scheduler, all of the print statements return the same correct number.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Is it possible for you to quickly verify if lower version of dask has the same issue? Like 2021.9 or 2021.8

**Comment by rkooo567** [comment]
Cc @scv119 i think this should be P0? (Very bad correctness issue)

**Comment by clarkzinzow** [comment]
@rkooo567 Definitely a P0, don't worry I'm already working on it!

**Comment by ericl** [comment]
Is this still a P0 issue given we cannot reproduce?

**Comment by clarkzinzow** [comment]
@ericl @crclark Downgrading this to a P1 until we have an open/mock data reproduction.

**Comment by crclark** [comment]
Sorry for the delay. We were able to reproduce with a synthetic dataset.

```
import dask
import dask.dataframe as dd
import dask.dataframe.multi as ddm
import dask.array as da
import numpy as np
import pandas as pd
import ray
import random
import string
from ray.util.dask import ray_dask_get

ray.init('auto', ignore_reinit_error=True)
dask.config.set(scheduler=ray_dask_get)

# Synthesis... It will take a minute or two
n = 2524770
maxNameLength = 100
names = ['']*n
letters = string.ascii_letters
for i in range(n):
    names[i] = ''.join(random.choice(letters) for i in range(random.randrange(maxNameLength)))
uniqNames = list(set(names))
synth_ddf = dd.from_pandas(pd.DataFrame(uniqNames, columns = ['name']), npartitions=8)
synth_ddf = synth_ddf.set_index('name')
print('The correct number of the unique names:', len(uniqNames))
print('Using Synchronous', sum(synth_ddf.map_partitions(len).compute(scheduler='synchronous')))
print('Using ray_dask_get', sum(synth_ddf.map_partitions(len).compute(scheduler=ray_dask_get)))
```

The output will be:

```
The correct number of the unique names: 2449596
Using Synchronous 2449596
Using ray_dask_get 611982
```

With Ray 1.8.0, Dask 2021.10.0, Python 3.8.4.

**Note:** this only seems to happen on some clusters, but we aren't able to find a pattern. We have seen it happen with even a single Ray node.

**Comment by abdulla-hammad** [comment]
@clarkzinzow  and @ericl, do you think it should be P0 as we can now reproduce with synthetic data?

**Comment by clarkzinzow** [comment]
@crclark Thank you for the reproduction! @abdulla-hammad Agreed that this should be a P0, I'll take this as an interrupt.

**Comment by clarkzinzow** [comment]
@crclark First run on a local Ray yields no rows dropped:
```
In [1]: import dask
   ...: import dask.dataframe as dd
   ...: import dask.dataframe.multi as ddm
   ...: import dask.array as da
   ...: import numpy as np
   ...: import pandas as pd
   ...: import ray
   ...: import random
   ...: import string
   ...: from ray.util.dask import ray_dask_get
   ...:
   ...: ray.init()
   ...: dask.config.set(scheduler=ray_dask_get)
   ...:
   ...: # Synthesis... It will take a minute or two
   ...: n = 2524770
   ...: maxNameLength = 100
   ...: names = ['']*n
   ...: letters = string.ascii_letters
   ...: for i in range(n):
   ...:     names[i] = ''.join(random.choice(letters) for i in range(random.randrange(maxNameLength)))
   ...: uniqNames = list(set(names))
   ...: synth_ddf = dd.from_pandas(pd.DataFrame(uniqNames, columns = ['name']), npartitions=8)
   ...: synth_ddf = synth_ddf.set_index('name')
   ...: print('The correct number of the unique names:', len(uniqNames))
   ...: print('Using Synchronous', sum(synth_ddf.map_partitions(len).compute(scheduler='synchronous')))
   ...: print('Using ray_dask_get', sum(synth_ddf.map_partitions(len).compute(scheduler=ray_dask_get)))
The correct number of the unique names: 2449934
Using Synchronous 2449934
Using ray_dask_get 2449934
```

>Note: this only seems to happen on some clusters, but we aren't able to find a pattern. We have seen it happen with even a single Ray node.

Interesting. I'll try to run this a few more times locally, then with a mock cluster, until I'm able to reproduce.

**Comment by clarkzinzow** [comment]
I wasn't able to reproduce this with a mock cluster, going to try with a real cluster tomorrow.

**Comment by clarkzinzow** [comment]
@crclark This appears to be an issue with Dask's shuffle algorithm inference, where it's defaulting to a disk-based shuffle even thought we're using a distributed shuffle, which is most likely resulting in dropped data since the filesystem isn't shared across nodes. Dask Distributed manually sets the shuffle algorithm in the global config to the task-based shuffle, which the Dask-on-Ray scheduler should probably do as well.

@crclark could you try passing `shuffle="tasks"` to `.set_index()` and see if that works? Concretely:
```python
import dask
import dask.dataframe as dd
import dask.dataframe.multi as ddm
import dask.array as da
import numpy as np
import pandas as pd
import ray
import random
import string
from ray.util.dask import ray_dask_get

ray.init('auto', ignore_reinit_error=True)
dask.config.set(scheduler=ray_dask_get)

# Synthesis... It will take a minute or two
n = 2524770
maxNameLength = 100
names = ['']*n
letters = string.ascii_letters
for i in range(n):
    names[i] = ''.join(random.choice(letters) for i in range(random.randrange(maxNameLength)))
uniqNames = list(set(names))
synth_ddf = dd.from_pandas(pd.DataFrame(uniqNames, columns = ['name']), npartitions=8)
synth_ddf = synth_ddf.set_index('name', shuffle='tasks')
print('The correct number of the unique names:', len(uniqNames))
print('Using Synchronous', sum(synth_ddf.map_partitions(len).compute(scheduler='synchronous')))
print('Using ray_dask_get', sum(synth_ddf.map_partitions(len).compute(scheduler=ray_dask_get)))
```

**Comment by clarkzinzow** [comment]
I'll open up an issue for the Dask-on-Ray scheduler setting that config.

**Comment by clarkzinzow** [comment]
Using [this issue](https://github.com/ray-project/ray/issues/20992) as the tracker for Dask-on-Ray automatically setting that config.
