### ISSUE TITLE
Policy Mapping Function based on Environment Observation

### ISSUE THREAD

**Issue by leeykang** [ray-project/ray#20112]
Is it possible to create an agent which uses different policies depending on an observation? For example, in a hypothetical Windy Gridworld environment where the wind can change direction spontaneously, an agent might choose a different policy depending on whether the wind is blowing North, South, East or West.
This is similar to Hierarchical Training, but the policy being used by the agent at every time step is determined individually and can change depending on the episode trajectory.

**Comment by ericl** [comment]
Sure, I think there are a couple ways. You could implement a custom Policy object. Another alternative is leveraging multi-agent: https://docs.ray.io/en/latest/rllib-env.html#hierarchical-environments

**Comment by leeykang** [comment]
Awesome, got it, thanks!
