### ISSUE TITLE
[Bug][Workflow] S3 storage path issue

### ISSUE THREAD

**Issue by lchu-ibm** [ray-project/ray#20114]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

When using S3 as backend for workflow storage, I noticed two path issues:

1. [parse.urlparse](https://github.com/ray-project/ray/blob/master/python/ray/workflow/storage/__init__.py#L32) will append leading slash to the object key. this is captured in https://github.com/ray-project/ray/issues/19027
2. ["/".join](https://github.com/ray-project/ray/blob/master/python/ray/workflow/storage/s3.py#L48) might not be a good practice here as it doesn't smartly avoid duplicated slashes when there are cases like: leading slash, trailing slash or empty element.  In our case, empty element can be involved for "parent" files with `step_id=""`.  So `make_key` will generate thing like `workflow_id/steps//outputs.json`, which is not a problem in local file system because the downstream [pathlib.Path(key)](https://github.com/ray-project/ray/blob/master/python/ray/workflow/storage/filesystem.py) will resolve double slashes to one, but same thing not true for S3.

Solution:
1. [parsed_url.path](https://github.com/ray-project/ray/blob/master/python/ray/workflow/storage/__init__.py#L39) -> `parsed_url.path.lstrip("/")`
2. use things like `os.path.join` to replace `"/".join`. 

### Versions / Dependencies

.

### Reproduction script

Ran any workflow with S3 as backend, we get the following:

```bash
s3://bucket//workflow_data/workflow_id/steps//outputs.json
```

Noticed the double slashes before `workflow_data`, and another double slashes before `outputs.json`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
It looks good. cc @wuisawesome

**Comment by wuisawesome** [comment]
Yeah, it looks like there's `urllib.parse.urljoin(url1, url2)` is probably technically the correct helper function (which I just learned about...), but lgtm
