### ISSUE TITLE
Update RLlib in 60 seconds example

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#20122]
A few things we want to do here:

- Show example that is more customizable, and shows something resembling user code
- Point to Tune [checkpointing docs](https://github.com/ray-project/ray/pull/20045)
- Point to [policy inference example](https://github.com/ray-project/ray/issues/20062)
 
On the first point, this can be any existing example in codebase/github, no need to design a new one unless we need to. 

Can also replace this with even better one in full revamp, we just need something incrementally better now.

**Comment by sven1977** [comment]
Page has been updated. Closing this issue now. Please feel free to post a PR with fixes for the `ray/doc/source/rllib/index.rst` file.
