### ISSUE TITLE
[Core] async actor process shutdown leak on OSX

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#20159]
```
ray start --head
python e.py
ray stop --force
pgrep ray::
```

```python
import ray
import asyncio
import time

@ray.remote
class A:
    async def g(self):
        await asyncio.sleep(10000)

ray.init(address="auto")
actor = A.options(lifetime="detached", name="A").remote()
actor.g.remote()
time.sleep(2)
```

shows that after ray stop, the actor process was not killed, and it uses 100% cpu

**Comment by simon-mo** [comment]
active thread flamegraph
![image](https://user-images.githubusercontent.com/21118851/140835488-6aecaa62-11a1-4c9a-86c0-2c962f8ee035.png)

**Comment by simon-mo** [comment]
Ok i was able to reproduce this with simple async actor.
```
ray start --head
python e.py
ray stop --force
pgrep ray::
```

```python
import ray
import asyncio
import time

@ray.remote
class A:
    async def g(self):
        await asyncio.sleep(10000)

ray.init(address="auto")
actor = A.options(lifetime="detached", name="A").remote()
actor.g.remote()
time.sleep(2)
```

**Comment by scv119** [comment]
uses 100% cpu makes this pretty bad. bump it to P0

**Comment by iycheng** [comment]
maybe related to this: https://github.com/ray-project/ray/issues/18533

**Comment by simon-mo** [comment]
I can reproduce this on my mac on 1.8.0 and f8430e6eca2490f06647be3c8fe4b867e675eb93.

**Comment by iycheng** [comment]
Hmm, it seems related to the platform and linux seem work, but not mac.

**Comment by iycheng** [comment]
lower to P1, since only mac can reproduce this.

**Comment by jjyao** [comment]
What I found is that the process is eventually killed but after 10+s
