### ISSUE TITLE
[Core] process leak hanging with `ray.nodes()` on OSX

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#20158]
Repro:
1. `ray start --head`.
2. Run the following script in a terminal.
```
import ray
import time

ray.init(address="auto")

@ray.remote
def f():
    while True:
        time.sleep(0.1)
        ray.nodes()

ray.get(f.remote())
```
3. Run `ray stop --force` in another terminal.
4. Run `ps aux | grep ray::` to identify leaked process. You should see the ray::f() process is now leaked, even though ray stop responded 
```
$ ray stop --force
Stopped all 14 Ray processes.
```
5. Running py-spy on the leaked process shows 
```
sudo py-spy dump --pid XXX`
➜  /private/tmp/repro sudo py-spy dump --pid 10151
Process 10151: ray::f()
Python v3.6.9 (/Users/simonmo/miniconda3/bin/python3.6)

Thread 0x10ECACE00 (idle): "MainThread"
    node_table (ray/state.py:180)
    nodes (ray/state.py:781)
    wrapper (ray/_private/client_mode_hook.py:105)
    f (b.py:10)
    main_loop (ray/worker.py:427)
    <module> (ray/workers/default_worker.py:218)
```

**Comment by simon-mo** [comment]
@scv119 please help triage!

**Comment by scv119** [comment]
@simon-mo is this considered more like P1?

**Comment by simon-mo** [comment]
Would appreciate a workaround if this is marked as P1. For example, specifying a deadline for ray.nodes(). We can't have process leak in Serve.

**Comment by ericl** [comment]
@simon-mo I can't reproduce this on _master_. I can reproduce a potentially related bug, where the driver hangs, but I don't see ray::f() hang.

This is on Linux / current master.

**Comment by simon-mo** [comment]
I wonder if this is a mac os thing. @edoakes and @architkulkarni can repro this on their mac. 

> I can reproduce a potentially related bug, where the driver hangs, but I don't see ray::f() hang.

does it hang on ray.nodes() call? i think the root cause just relates to core worker shutdown interfering other things so it doesn't matter it's driver or worker.

**Comment by ericl** [comment]
The hang I'm seeing is at
```
48881:[2021-11-10 14:55:56,885 I 661824 661848] direct_task_transport.cc:592: The worker failed to receive a response from the local raylet, but raylet is still alive. Try again on a local node. Error: IOError: 
```

Basically the driver isn't properly exiting when the raylet dies in this case, but it seems like a separate issue.

I do see the worker properly cleaned up on stop though.

**Comment by ericl** [comment]
Reading through the code, I think the culprit may be in our use of Redis. Since @mwtian is removing the node table in favor of direct gRPC access currently, I think we can downgrade this and re-visit. It's highly likely to be fixed after that.

Separately I'll make a patch to fix the driver hang, I think that one is kind of bad.

**Comment by simon-mo** [comment]
sounds good with the downgrade. however, i think `ray.nodes()` currently go through GlobalStateAccessor -> gcs_client_ which isn't redis?

**Comment by mwtian** [comment]
GCS client uses Redis underneath currently. The default will be switched in a few weeks.

**Comment by simon-mo** [comment]
ah got it. thanks!
