### ISSUE TITLE
Deadlock with ray.util.multiprocessing.Pool

### ISSUE THREAD

**Issue by jordiae** [ray-project/ray#20161]
I have an application using Ray's ray.util.multiprocessing.Pool that eventually deadlocks during the application of a distributed map. Each worker in the map writes to disk in their own file, but some of them get stuck. Eventually, all of them seem to be stuck. If I stop the application with a keyboard interruption, the code is stuck at:

```
    return self._ready_index_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

After Googling for a while, the only potentially related issue I have found is that apparently this can happen with Python's multiprocessing (whose API and functionality Ray tries to emulate in ray.util.multiprocessing.Pool), because of the combination of fork() and multi-threading. For instance, see https://pythonspeed.com/articles/python-multiprocessing/. In the case of Python's multiprocessing, the suggested solution is using spawn instead of fork, which is not possible in Ray (https://github.com/ray-project/ray/issues/13568).

I'm not sure at all that the cause is multi-threading, but I haven't found any other possibilities. While my application doesn't explicitly create any thread, I'm using Python's logging, which might create threads under the hood? Also, there is no easy way to know if any of the libraries I'm using is directly or indirectly creating any threads. I've tried to remove as many dependencies as possible (e.g., tqdm's progress bar) with no luck.

The problem is very difficult to debug. At this point, I'm not sure whether I'm doing something wrong or there is a bug (and not even sure if the bug is in Ray itself). Any help will be much appreciated. Thanks!

**Comment by jordiae** [comment]
Update: the exact same code deadlocked both with Python's multiprocessing Pool and Ray's Pool. If I force Python's multiprocessing to use spawn() instead of fork(), as suggested by the link I shared above, it doesn't deadlock anymore! However, this is not possible in Ray (#13568).

**Comment by rkooo567** [comment]
cc @edoakes ? do we use any multiprocessing pool functionality within our codebase? 

Also @jordiae do you have any repro script that we can reproduce the issue?

**Comment by edoakes** [comment]
We don't use mp.Pool, we have our own custom implementation, but we may have a similar threading issue.

https://github.com/ray-project/ray/blob/master/python/ray/util/multiprocessing/pool.py

**Comment by jordiae** [comment]
> cc @edoakes ? do we use any multiprocessing pool functionality within our codebase?
> 
> Also @jordiae do you have any repro script that we can reproduce the issue?

I didn't mean that you did. I meant that you expose an API purposedly identical to the one of mp.Pool (in the code @edoakes  sent). I use this API, and the exact same code but just changing the parallel backend:#
- Hangs if using mp.Pool with fork().
- Does NOT hang if using mp.Pool with spawn().
- HANGS if using Ray, which uses fork() (it doesn't support spawn).

In other words, implementations using fork() hang, implementations using spawn() don't. In the case of mp.Pool I can force mp to use spawn() but in the case of Ray I cannot.

I'll try to attach a minimal example that reproduces the bug.
