### ISSUE TITLE
[Bug] prom_metrics_service_discovery.json only contains head node

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#20162]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### What happened + What you expected to happen

Launch any Ray cluster; the `prom_metrics_service_discovery.json` file only contains the head node IP, rather than the IPs of all nodes. This makes me unable to monitor the cluster using Prometheus/Grafana. This issue has persisted through the last week on master.

### Versions / Dependencies

master

### Reproduction script

```bash
$ ray up -y python/ray/autoscaler/aws/example-full.yaml
$ ray attach python/ray/autoscaler/aws/example-full.yaml
ubuntu@ip-172-31-31-112:~$ ray status
======== Autoscaler status: 2021-11-09 00:07:42.314384 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray.head.default
 16 ray.worker.default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/128.0 CPU
 0.00/708.788 GiB memory
 0.00/476.000 GiB object_store_memory
 0.0/16.0 worker
 0.0/16.0 worker:i3.2xlarge

Demands:
 (no resource demands)
ubuntu@ip-172-31-31-112:~$ cat /tmp/ray/prom_metrics_service_discovery.json
[{"labels": {"job": "ray"}, "targets": ["172.31.31.112:44217"]}, {"labels": {"job": "prom"}, "targets": []}]
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
hmm interesting. This is basically written by the dashboard agent (agent.log) using ray.nodes. Is it like this for a long time? (although you wait, it doesn't update it?)

**Comment by rkooo567** [comment]
cc @edoakes @simon-mo this seems to be the regression.

**Comment by franklsf95** [comment]
@rkooo567 Correct, it does not update even after a long time.

**Comment by rkooo567** [comment]
Are you planning to submit the fix? (I saw you marked the checkbox)

**Comment by franklsf95** [comment]
@rkooo567 I could help out, but right now I don't know what the problem is :)

**Comment by rkooo567** [comment]
```
        nodes = ray.nodes()
        metrics_export_addresses = [
            "{}:{}".format(node["NodeManagerAddress"],
                           node["MetricsExportPort"]) for node in nodes
            if node["alive"] is True
        ]
        redis_client = services.create_redis_client(self.redis_address,
                                                    self.redis_password)
        autoscaler_addr = redis_client.get("AutoscalerMetricsAddress")
        if autoscaler_addr:
            metrics_export_addresses.append(autoscaler_addr.decode("utf-8"))
        return json.dumps([{
            "labels": {
                "job": "ray"
            },
            "targets": metrics_export_addresses
        }])
```

This is how we dump contents. Maybe you can try if `ray.nodes()`returns the correct output first, and then you can check dashboard_agent.log and see if there's any exception.

**Comment by franklsf95** [comment]
This just fixed itself mysteriously on latest master. I'll reopen this if it happens again.
