### ISSUE TITLE
[Placement Group] [Java] Make the Class PlacementGroup serializable in Java Api

### ISSUE THREAD

**Issue by clay4444** [ray-project/ray#20189]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Make the Class PlacementGroup serializable in Java API so that the placement group handler can be passed in multiple processes in cluster.

### Versions / Dependencies

Master

### Reproduction script

None.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Should we consider the xlang usage?

**Comment by jovany-wang** [comment]
@clay4444 Who is the owner of this issue? :)
I saw that you're willing to submit a PR in the description, but this issue is assigned to me and @kfstorm .

**Comment by clay4444** [comment]
@jovany-wang   oh, sorry, I will submit a pr as quickly!
