### ISSUE TITLE
[Feature] Ability to customize Ray session name

### ISSUE THREAD

**Issue by ralbertazzi** [ray-project/ray#20182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Although [the Ray documentation](https://docs.ray.io/en/latest/configure.html#logging-and-debugging) makes me understand that the session name can be customized ("By default, the name is session_{timestamp}_{pid}"), it actually cannot be changed as you can see [from the code](https://github.com/ray-project/ray/blob/90fd38c64ac282df63c2a7fbccf66a46217991a4/python/ray/node.py#L178).
I would like to customize the session name, ideally from `ray.init`:
```python
ray.init(session_name="custom_session")

session_name: Optional[str] = None # by default it behaves as of now
```

### Use case

What I am trying to achieve is having a deterministic way of finding the log directory of Ray so that I can configure log exporters (fluentd) to export logs of internal ray components (`gcs_server.out`, `gcs_server.err`, `raylet.out`, `raylet.err`, ...). Right now we can configure the base temp dir but not the session name, which makes the path non deterministic.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Session name customization is not supported by the public API https://docs.ray.io/en/master/package-ref.html#ray-init. If you let me know what sentence gave you that impression, I can delete them from the doc. 

Regarding the feature request, I am curious if running fluentd on top of session_latest is working? (that's the symlink to the latest session).

**Comment by ralbertazzi** [comment]
Hi @rkooo567 thanks for reaching out!

The documentation that mislead me is [here](https://docs.ray.io/en/latest/configure.html#logging-and-debugging), specifically when it says:
```
By default, the name is session_{timestamp}_{pid}
```
What I thought it "If there is a default, there is also a non-default way that I can customize!". I think that just removing "By default" would solve the misleading.

My bad for not finding `session_latest`! I will try it but my guess is that it should work :)
