### ISSUE TITLE
[runtime env] Allow specifying Path instead of str for working_dir, py_modules

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#20198]
Users might be using `pathlib.Path` in their code.  Currently they have to convert to `str` before passing into a runtime environment, but we should do this conversion for them.

**Comment by hckuo** [comment]
Hey, I'm interested at working on this. Just to clarify the goal: we want to modify code in this dir (https://github.com/ray-project/ray/tree/53630ee03b8d0fbdcd76f037203085f4565a0ad1/python/ray/_private/runtime_env) so that users can pass a Path instance to specify the runtime env.
