### ISSUE TITLE
[Bug] Background function with max calls doesn't release resources

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#20203]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When `max_calls` is set and a background task is set, we don't return the worker until a process exit. Since there's a background task executing, the worker process can't or be reused since it owns the ref for the background process.

### Versions / Dependencies

master

### Reproduction script

```
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

@ray.remote
def g():
    time.sleep(.1)
    return 0

@ray.remote(num_cpus=1, num_gpus=1, max_calls=1, max_retries=0)
def f():
    return [g.remote()]

nested = ray.get([f.remote() for _ in range(10)])

# Should still be able to retrieve these objects, since f's workers will
# wait for g to finish before exiting.
ray.get([x[0] for x in nested])
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/10960
