### ISSUE TITLE
[rllib] Allow passing in additional TF operations for evaluation for PPO (e.g. for batch normalization)

### ISSUE THREAD

**Issue by kovalevvlad** [ray-project/ray#2023]
I would like to use a simple TF model with batch normalization along with PPO. I am considering the following TF feature - https://www.tensorflow.org/api_docs/python/tf/layers/batch_normalization. The problem I am facing is that in order for the above batch normalization feature to work, you have to run the moving mean/variance update operations, in addition to the NN graph computation. As far as I can tell, there is no way of passing these operations into `extra_ops` in `self.par_opt.optimize(extra_ops=...)` call inside `PPOEvaluator.run_sgd_minibatch(..)`. Is anyone aware of a workaround that I could use? Is there perhaps a proper way of doing this that I have missed? Apologies if this is a dumb question, I am fairly new to both TF and rllib.

EDIT: Additionally, I don't think there is currently a way to add extra values to the TF `feed_dict` during training/prediction. In my use-case, this is necessary to switch batch normalization between training and prediction modes.

**Comment by ericl** [comment]
I think you would have to patch ppo_evaluator.py to include those extra ops explicitly. This is definitely something that would be nice to support cleanly in the API though, perhaps as part of supporting user defined policies (https://github.com/ray-project/ray/issues/2053) cc @richardliaw

**Comment by kovalevvlad** [comment]
I have tried to hack this in locally but didn't make much progress. I think I need to get a bit more comfortable with the code-base first. I'd be happy to submit a PR if you could give me some suggestions on where to start.

**Comment by kovalevvlad** [comment]
Hi @richardliaw. Here's a simple example of problem I am having. Consider the following model:

```python
class FullyConnectedNetwork(Model):
    def _init(self, inputs, num_outputs, options):
        activation = tf.nn.tanh
        is_training = tf.placeholder("bool")
        hidden_layers = [10, 6, 4]
        last_layer = inputs
        for size in hidden_layers:
            last_layer = slim.fully_connected(last_layer, size)
            last_layer = tf.layers.batch_normalization(last_layer, training=is_training)
            last_layer = activation(last_layer)

        output = slim.fully_connected(last_layer, num_outputs)
        return output, last_layer
```

From tensorflow docs (https://www.tensorflow.org/api_docs/python/tf/layers/batch_normalization):

> Note: when training, the moving_mean and moving_variance need to be updated. By default the update ops are placed in tf.GraphKeys.UPDATE_OPS, so they need to be added as a dependency to the train_op...

This is the first issue. I don't have direct access to the training operation used by rllib so I can't add `UPDATE_OPS` as a dependency. Additionally, if I understand correctly, this is made more complicated by the fact that we have 2 networks - actor & critic, so we have 2 separate training ops with 2 separate sets of dependencies (I might be wrong on this one so please correct me if I am wrong).

> training: Either a Python boolean, or a TensorFlow boolean scalar tensor (e.g. a placeholder). Whether to return the output in training mode (normalized with statistics of the current batch) or in inference mode (normalized with moving statistics). NOTE: make sure to set this parameter correctly, or else your training/inference will not work properly.

This is the second issue that I am facing. I need to be able to control the value of `is_training` placeholder but I don't have any control over the feed_dict that's passed into tensorflow by rllib during training/prediction.

**Comment by ericl** [comment]
Got it. I think calling the update ops can be addressed by adding the control deps around `tf.optimizer.apply_gradients` call in line 84 of `multi_gpu_impl`. This updates both the actor and critic networks at once. Automatically adding these deps might be useful in general for rllib.

One issue I can see is that since we create a separate model tower on each GPU, this will update each tower's moving mean and variance separately, which could be a problem (but you can try it out and see, or alternatively set PPO to use only 1 GPU to avoid the issue).

For the `is_training` placeholder, I think if you set the tensor to default to `false`, then the only place it needs to be overriden is in line 150 of ppo_evaluator (adding it to the extra_feed_dict).

**Comment by kovalevvlad** [comment]
I have tried a simplified version of what you describe. I have wrapped `apply_gradients` in a control dependency and just hardcoded `is_training=True` just to get things moving:

```
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
        with tf.control_dependencies(update_ops):
            self._train_op = self.optimizer.apply_gradients(avg)
```

Now I am getting a TF exception complaining about the observation placeholder not being set when updating moving mean/variance in the batch norm layers:

```
Traceback (most recent call last):
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,16]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[?,16], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
	 [[Node: tower/value_function/fully_connected/weights/read/_97 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:3", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_361_tower/value_function/fully_connected/weights/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:3"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...py", line 85, in <module>
    result = agent.train()
  File ".../venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 109, in train
    result = self._train()
  File ".../venv/lib/python3.6/site-packages/ray/rllib/ppo/ppo.py", line 176, in _train
    self.file_writer)
  File ".../venv/lib/python3.6/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 159, in run_sgd_minibatch
    file_writer=file_writer if full_trace else None)
  File ".../venv/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_impl.py", line 178, in optimize
    run_metadata=run_metadata)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,16]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[?,16], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
	 [[Node: tower/value_function/fully_connected/weights/read/_97 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:3", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_361_tower/value_function/fully_connected/weights/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:3"]()]]

Caused by op 'Placeholder', defined at:
  File "...py", line 77, in <module>
    agent = ppo.PPOAgent(config=dict({**ppo_config, "env_config": env_config}), env=env_creator_name)
  File ".../venv/lib/python3.6/site-packages/ray/rllib/agent.py", line 84, in __init__
    Trainable.__init__(self, config, registry, logger_creator)
  File ".../venv/lib/python3.6/site-packages/ray/tune/trainable.py", line 89, in __init__
    self._setup()
  File ".../venv/lib/python3.6/site-packages/ray/rllib/agent.py", line 107, in _setup
    self._init()
  File ".../venv/lib/python3.6/site-packages/ray/rllib/ppo/ppo.py", line 100, in _init
    self.registry, self.env_creator, self.config, self.logdir, False)
  File ".../venv/lib/python3.6/site-packages/ray/rllib/ppo/ppo_evaluator.py", line 63, in __init__
    tf.float32, shape=(None,) + self.env.observation_space.shape)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4848, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File ".../venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,16]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[?,16], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
	 [[Node: tower/value_function/fully_connected/weights/read/_97 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:3", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_361_tower/value_function/fully_connected/weights/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:3"]()]]
```

**Comment by ericl** [comment]
Ah, that is probably since the multi-gpu SGD operates in two phases:
First, data is loaded into GPU memory (in the `load_data` call).
Then, gradients are computed over slices of the in-memory dataset.

This allows us to avoid excess CPU->GPU transfers when executing multiple iterations of sgd. However, it means that data is only fed once, during load. It might work to just move the control deps to the data loading ops (`batch.initializer` in multi_gpu_impl:214). Those assign ops should definitely be run with the right placeholders set.

**Comment by kovalevvlad** [comment]
But if the algorithm performs multiple gradient applications per data batch, don't we need to update the weights on every gradient application rather than once per tower initialization?

**Comment by ericl** [comment]
Oh right, then, I think your current approach is right, but you need to
filter out the update ops that are depending on the original bulk load
placeholders (which are not used during the actually apply). Can you print
out the list of update ops from the batch norm layers?

**Comment by ericl** [comment]
@alok would you like to take a look at this? It would be great if we supported batch norm more generally across rllib models/algorithms, and after the recent refactoring this seems feasible.
