### ISSUE TITLE
Propagate failure to acquire worker lease from local raylet instead of retrying forever

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#20239]
Currently, we retry task leasing requests indefinitely: https://github.com/ray-project/ray/blob/master/src/ray/core_worker/transport/direct_task_transport.cc#L585

This leads to driver hangs if the raylet is dead. It would be better to propagate the error to the task if the raylet we tried to contact is local (local gRPC calls should never fail).

This can be reproduced by https://github.com/ray-project/ray/issues/20158 on Linux (the driver will hang after ray stop is called).

**Comment by rkooo567** [comment]
Hmm does that mean IsRayletFailed function is not working as expected? (Given code, it looks like the driver should QuicKExit())?

**Comment by ericl** [comment]
We shouldn't quickexit the driver though, just fail Ray API calls and let
the user code handle the exit.

Though the raylet pid isn't set there for sure.

**Comment by rkooo567** [comment]
Yeah I agree with that! I just wanted to know if this function was working properly or not. Good to know it is not, and I can repro…

**Comment by rkooo567** [comment]
@ericl Maybe I can take this next sprint as I recently added this IsRayletFailure logic to have cleaner log upon local raylet failure? I am thinking to find a way to detect local raylet failure better and reliably propagate the exception to the driver (whereas workers will just QuickExit()).
