### ISSUE TITLE
[Bug] `quniform` error (specific to `HEBO` search algorithm)

### ISSUE THREAD

**Issue by scho97** [ray-project/ray#20246]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

When I use `tune.quniform()` to configure my search space with `HEBOSearch()`, the sampling does not give out properly quantized values.

I have tested this problem with three different search algorithms: random search, BOHB, and HEBO. The experiments were ran over ten trials with `tune.quniform(1.0, 2.5, 0.1)`. The hyperparameter values I got for each algorithm are as follows:

**Random Search:**
```
[2.5, 2.1, 2.1, 2.1, 1.9000000000000001, 1.6, 1.9000000000000001, 1.7000000000000002, 1.1, 1.9000000000000001]
```
**BOHB:**
```
[1.9, 2.5, 1.7000000000000002, 2.3, 2.0, 2.1, 1.9, 2.5, 1.4, 1.9]
```
**HEBO:**
```
[2.289924255917817, 1.9375, 1.1875, 1.5625, 2.3125, 1.7572203876967833, 1.0, 2.125, 1.375, 1.75]
```

I suppose some of the values in random search and BOHB with long trailing decimal points can be explained as deriving from the limitation of floating points, but it seems the values sampled by HEBO are improper.

### Versions / Dependencies

ray==1.8.0
python==3.7.11
numpy==1.21.2
macOS Big Sur v11.6

### Reproduction script

This problem can be reproduced by any instances using `tune.quniform()` with `tune.run(..., search_alg=HEBOSearch(...), ...)`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sumanthratna** [comment]
Hi @scho97, do you see any warnings in your output? I believe HEBO does not support quantization: 

https://github.com/ray-project/ray/blob/ce8504b0b29306a94f2b805d8093413f372b97b7/python/ray/tune/suggest/hebo.py#L343-L345

**Comment by scho97** [comment]
Hi @sumanthratna, thank you for your reply. I see HEBO does not support quantization. I will make a change accordingly.

I did not see any warnings in my output. FYI, the `total_run_time` also does not print out when I use HEBO while using other search algorithms prints it out.
