### ISSUE TITLE
[Bug] Synchronous actor creation is too slow

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20244]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

cc @scv119 

## Problem
According to @xwjiang2010's benchmark, the throughput of creating 100 actors synchronously is really low. When you run the script below, 

- creating 1 actor and calling its actor method 100 times in a loop took **0.24 second**
- creating 1 actor and calling its method 1 time synchronously for 100 times in the loop took **100 seconds** (thus 1 actor creation / s). 

Although it is expected there's higher overhead in the synchronous actor creation, 1 actor creation per second seems to be **really slow**. We need to 

- Investigate if this is regression.
- Investigate the root cause of low throughput. 
- Add a benchmark script that tests synchronous actor creation time (we only measure concurrent creation).

cc @ericl is 1 actor creation/s expected throughput? You can see the script below to see how the benchmark was performed.

### Versions / Dependencies

master

### Reproduction script

```python3
import ray
import time

@ray.remote
class Actor:
    def __init__(self, *args):
        if len(args) > 0:
            self._val = args[0]
        else:
            self._val = 0
    def set_val(self, val):
        self._val = val
    def get_val(self):
        return self._val

@ray.remote
def task():
    return 2

ray.init()

results = []
start = time.perf_counter()
actor = Actor.remote()
for i in range(100):
    actor.set_val.remote(i)
    results.append(ray.get(actor.get_val.remote()))
taken = time.perf_counter() - start

print(f"Reuse actor. Took {taken:.2f} seconds")

results = []
start = time.perf_counter()
for i in range(100):
    actor = Actor.remote(i)
    results.append(ray.get(actor.get_val.remote()))
taken = time.perf_counter() - start

print(f"New actor. Took {taken:.2f} seconds")

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Yeah this seems normal to me. Starting workers is inherently slow.

Applications should not assume any blocking calls are fast.
