### ISSUE TITLE
[release][core-nightly] inference is failing. 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20258]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_nyHPVp7fNykxK9vAV8UCVLrn?command-history-section=command_history

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@wuisawesome can you take a quick look to see if anything is obviously wrong? seems to me nothing has changed in dataset for last 5-6 days.

**Comment by wuisawesome** [comment]
Ok, this was an extremely strange issue, looks like it's an underlying numpy bug. The following code only works with numpy >=1.20 (yes the code doesn't directly use numpy).

```
import pandas as pd
import torch
pd.DataFrame([torch.arange(27).reshape(3,3,3) for _ in range(10)])
```

#20001 seems to be the culprit, but reverting it isn't going to fix the problem. 

This code seems pretty fundamental to our block representation, so we should probably (1) add a numpy version constraint: `numpy >= 1.20` and (2) ensure that the anyscale/ray docker images have an acceptable version of numpy. @clarkzinzow would definitely want you to confirm that there isn't a simple way constructing the blocks in a different way though. 

cc @ericl @zhe-thoughts @scv119

**Comment by zhe-thoughts** [comment]
Thanks @wuisawesome. 

What's the implication of constraining the NumPy version to be >= 1.20?

**Comment by wuisawesome** [comment]
I think we can keep the constraint to the dataprocessing requirements (and just update the default version in our own docker images) so the implications should be fairly minimal.

It seems like the main implication is that we're going to be tightening the version constraints for the numpy dependency quite a bit (since 1.20.0 was released in january of this year).

**Comment by clarkzinzow** [comment]
@wuisawesome Note that we can't require `numpy>=1.20.0` until we drop Python 3.6 support, since NumPy dropped Python 3.6 support in 1.20.0: https://numpy.org/devdocs/release/1.20.0-notes.html#numpy-1-20-0-release-notes

**Comment by clarkzinzow** [comment]
For our CI, I think it's already the case that all Datasets jobs are on Python 3.7 or greater?

**Comment by wuisawesome** [comment]
Oh shoot, that's a good point. Maybe we can just add that version rule for python >= 3.7 then.

**Comment by iycheng** [comment]
Inference is still failing, reopen the ticket.
https://buildkite.com/ray-project/periodic-ci/builds/1675#152aee41-67fa-4d16-a2d7-63086b1a4ef7

**Comment by zhe-thoughts** [comment]
Do we have a leading theory? Thanks

**Comment by rkooo567** [comment]
This seems to be fixed in the master. Please reopen if this fails again.
