### ISSUE TITLE
[Bug] MADDPG algorithm does not use exploration config correctly

### ISSUE THREAD

**Issue by Gabr1e1** [ray-project/ray#20259]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

MADDPGTFPolicy inherits TFPolicy, which doesn't use the Exploration object's get_exploration_action method, therefore the MADDPG policy doesn't use exploration at all, despite setting config['explore'] to True.

### Versions / Dependencies

ray == 1.8.0

### Reproduction script

If you add a line of code in get_exploration_action in stochastic_sampling.py (default exploration config for MADDPG):
```
@override(Exploration)
    def get_exploration_action(
            self,
            *,
            action_distribution: ActionDistribution,
            timestep: Optional[Union[int, TensorType]] = None,
            explore: bool = True):
        assert False # If 
        if self.framework == "torch":
            return self._get_torch_exploration_action(action_distribution,
                                                      timestep, explore)
        else:
            return self._get_tf_exploration_action_op(action_distribution,
                                                      timestep, explore)

```

You will see that MADDPGTrainer never actually stops, and the training is normal.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mvindiola1** [comment]
Hi @Gabr1e1,

The maddpg implementation is not like most of the other algorithms in rllib. It has several non-standard things unfortunately. This is why it is in the contrib module.

It does do exploration by sampling from a RlaxedOnehitCategorical distribution. There is no way to turn off exploration to produce a deterministic action.

https://github.com/ray-project/ray/blob/71a162d8ab198dc0553b82c16296496246781f1a/rllib/contrib/maddpg/maddpg_policy.py#L371

**Comment by Gabr1e1** [comment]
I understand that it is currently sampling from a RelaxedOneHotCategorical distribution. But what I am saying is that it ignores the exploration_config specified. There could be other ways to explore other than using the RelaxedOneHotCategorical distribution, per my understanding.

**Comment by mvindiola1** [comment]
@Gabr1e1,

OK I understand now. I agree, although in my opinion (which admittedly is not worth much) it would require a complete rewrite using the standard interfaces to support that kind of exploration.

**Comment by Gabr1e1** [comment]
@mvindiola1 As far as exploration is concerned, I think a simple replacement of `act_sampler` would suffice? Like this:
```
act_sampler, _ = self.exploration.get_exploration_action(observations=obs_ph_n[agent_id],
                                                                 action_distribution=act_sampler,
                                                                 timestep=self._timestep, explore=self._is_exploring)
```
Pretty much the same as in DynamicTfpolicy.
I agree, though, that a better way to do this is maybe to let Maddpg policy inherit Dynamictfpolicy instead of Tfpolicy

**Comment by Gabr1e1** [comment]
I just realized that this wouldn't work on most existing exploration classes. I am only writing this because I am implementing a custom exploration method.
