### ISSUE TITLE
[Tune] resource_changing_scheduler._are_resources_the_same  

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#20272]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

`resource_changing_scheduler._are_resources_the_same`  returns False
between `[{CPU: 1.0, GPU: 0.0}]` and `[{CPU: 1.0}]`

Is this expected?

Depending how we want to define the semantics of equal, here are a few options:
1. consider the two equal and update `PlacementGroupFactory.__eq__`
2. consider them not equal but consider resources are the same for `ResourceChangingScheduler`'s concern. --> Update the logic in `_are_resources_the_same`.

In either case, since `PlacementGroupFactory` and `example_resources_allocation_function` using `PlacementGroupFactory` are both public facing API, we should probably make it clear what is the expected behavior. 

### Versions / Dependencies

master

### Reproduction script

https://github.com/ray-project/ray/pull/19515

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@Yard1 Do you mind taking a look?

**Comment by Yard1** [comment]
Yeah, this should not be happening. I will create a PR.
