### ISSUE TITLE
[release][nightly] `xgboost` tests failing

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#20303]
There are multiple XGboost release tests failing on the nightly build:

`ft_small_elastic`: https://buildkite.com/ray-project/periodic-ci/builds/1606#f56a1ef9-c67c-4ac8-a529-7321ef0f1abd
`ft_small_non_elastic`: https://buildkite.com/ray-project/periodic-ci/builds/1606#63702d3f-5def-491b-82cf-f6f055b5a3eb
`train_small`: https://buildkite.com/ray-project/periodic-ci/builds/1606#5d094c61-836d-4bf8-8870-5463db87a2f0
`xgboost_sweep`: https://buildkite.com/ray-project/periodic-ci/builds/1606#93b9a718-ba5f-4eba-835b-95785296f18c
`xgboost_gpu_connect_latest`: https://buildkite.com/ray-project/periodic-ci/builds/1606#25c0729c-3e9f-4e99-94d6-bdf0c1bd1f68
`xgboost_gpu_connect_master`: https://buildkite.com/ray-project/periodic-ci/builds/1606#93546dc1-d7e0-46d2-bc4d-f17d9e213246

**Comment by iycheng** [comment]
offline synced with @krfricke  it looks like train_small's failure is expected. I've verified the rest tests passed

https://buildkite.com/ray-project/periodic-ci/builds/1638#d330556d-6074-4d26-8c9c-49b65175d74f
