### ISSUE TITLE
[RFC][Workflows][Events] Pre-commit function

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#20307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

# Context

At the moment, workflow events are _always_ checkpointed. Workflow events can also contain quite a bit of data, therefore, this checkpointing process can be quite inefficient.

Consider the case where a workflow tries to process large messages (like images) off of a distributed queue (like Kafka or SQS). In this case, we shouldn't checkpoint the messages because

1. They're already durably stored on the queue.
2. Checkpointing them would be extremely expensive since queues can hold quite a bit of data.

The challenges here are 

1. We don't want to checkpoint the event.
2. We can't commit the event until we've checkpointed _something_ so that we can remain fault tolerant.

Essentially, the steps we want are: poll_event -> process_event -> commit_event. The current steps are poll_event -> commit_event -> process_event. 

## API

```
def wait_for_condition(event_listener: EventListenerType, pre_commit_fn: Callable[[Event], T] = lambda x: x, *args, **kwargs) -> T:
```

Example usage:

Classify an image before checkpointing/comitting:

```
processed_queue_event = workflow.wait_for_condition(KafkaListener, preprocess_fn=classify_img.remote)
```

Ensure that multiple workflow steps finish before the result is committed.

```
def infer_and_record_stats(img):
    infer_step_result = infer.step(img)
    record_result = tracking_actor.increment_processed_count.step()
    return gather.step(infer_step_result, record_result)

workflow.wait_for_event(KafkaListener, pre_commit_fn = infer_and_record_stats)
```

## Alternative API

We could also do this by providing a utility function instead of an argument.

```
event_listener_type = ray.workflow.make_event_listener(KafkaListener, pre_commit_fn=...)
event_step = workflow.wait_for_event(event_listener_type)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
This is supported by event_checkpointed. Close this.
