### ISSUE TITLE
[release] many_ppo output is polluted with memory profile prints 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#20309]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_KdA3jWbK8HDYnir84fpR8XsD?command-history-section=command_history

For some reason, only limited logs in "command history" are preserved. Currently, it's all about memory profiling info.

Can we instead direct the info to some file as an artifact maybe?

### Versions / Dependencies

master

### Reproduction script

many_ppo

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I am planning to handle this
