### ISSUE TITLE
[Bug] minimal aws cluster does not launch

### ISSUE THREAD

**Issue by sronen1** [ray-project/ray#20316]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Trying to do:
ray up config.yaml
Where config.yaml is the minimal aws file given below. Getting an error:

    class GcsAioPublisher:
  File "/home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/ray/_private/gcs_pubsub.py", line 197, in GcsAioPublisher
    def __init__(self, address: str = None, channel: grpc.aio.Channel = None):
AttributeError: module 'grpc' has no attribute 'aio'
Shared connection to 35.84.2.198 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.

config,yaml 

cluster_name: minimal
provider:
    type: aws
    region: us-west-2
    cache_stopped_nodes: False

### Versions / Dependencies

Local ray is 2.0 nightly in python 3.9 virtual env. no conda.

### Reproduction script

ray up config.yaml

config,yaml 

cluster_name: minimal
provider:
    type: aws
    region: us-west-2
    cache_stopped_nodes: False

### Anything else

It worked a few days ago. Don't know what changed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This should be fixed by https://github.com/ray-project/ray/pull/20287

**Comment by rkooo567** [comment]
The wheel will be available in 3-4 hours I think

**Comment by sronen1** [comment]
Thanks!
