### ISSUE TITLE
[Datasets] [Bug] Preserve row/partition order for non-shuffling operations; document row/partition reordering for non-obvious shuffle operations

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#20329]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When passing `locality_hints` to `Dataset.split()`, the items/blocks in the `Dataset` appear to "reverse".

My initial expectation would be for to resulting splits to be the same as if I called `split` without `locality_hints` (or `split_at_indices`). 

If this is the expected behavior, maybe the docs could be updated to make this more clear?

### Versions / Dependencies

Ray 1.8.0 / nightly

### Reproduction script

```python
import ray

num_items = 10
num_splits = 2

dataset = ray.data.range(num_items)
print(f"dataset: {dataset.take()}")

dataset_split = dataset.split(n=num_splits)
print(f"dataset_split: {[d.take() for d in dataset_split]}")

@ray.remote
class ActorCls():
  pass

actors = [ActorCls.remote() for _ in range(num_splits)]
dataset_split_locality = dataset.split(n=num_splits, locality_hints=actors)
print(f"dataset_split_locality: {[d.take() for d in dataset_split_locality]}")
```

Output:
```
dataset: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
dataset_split: [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
dataset_split_locality: [[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
Our locality-aware split probably isn't stable, i.e. we don't guarantee that (1) block ordering will be preserved within splits, or (2) block ordering will be preserved across splits; even if all actors are on the same node, we don't make that guarantee.

Is this actually a functionality issue, or just unexpected behavior?

**Comment by clarkzinzow** [comment]
@matthewdeng Ping on this!

**Comment by matthewdeng** [comment]
Oops @clarkzinzow I guess this was a misassumption on my part. Perhaps the (non)guarantees could be made clearer in the API documentation?

**Comment by clarkzinzow** [comment]
@matthewdeng I think we can adopt the semantics of other (distributed) dataframe libraries (Dask DataFrames, Spark): **row and partition order is preserved, unless shuffling occurs; if it's not obvious that an operation involves a shuffle (e.g. it's not called `.sort()` `.shuffle()`), then the documentation of the operation should make it clear that it does**.

I'm going to rescope this issue to making sure that we follow these semantics and properly document where row/partition ordering is not preserved, and add this issue to our docs/UX audit tracker.

**Comment by matthewdeng** [comment]
That sounds good to me! Just to make sure I understand, is locality-aware splitting one of those cases where this is a non-obvious shuffle?

**Comment by clarkzinzow** [comment]
@matthewdeng Yes, we'd make a note that if `equal=True` OR `locality_hints=...` is provided, then block/row ordering is no longer guaranteed.
