### ISSUE TITLE
[Bug] [Tune] checkpointing fails on k8s clusters

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#20338]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

running https://docs.ray.io/en/latest/train/examples/tune_cifar_pytorch_pbt_example.html .. throws the following error:
```
(pid=12287) 2021-11-13 23:51:41,217	ERROR trial_runner.py:1100 -- Trial tune_function_33667_00000: Error handling checkpoint /home/ray/ray_results/tune_function_2021-11-13_23-48-05/tune_function_33667_00000_0_lr=0.001_2021-11-13_23-48-05/checkpoint_-00001/
(pid=12287) Traceback (most recent call last):
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 1095, in _process_trial_save
(pid=12287)     checkpoint=trial.saving_to)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/callback.py", line 259, in on_checkpoint
(pid=12287)     callback.on_checkpoint(**info)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 482, in on_checkpoint
(pid=12287)     self._sync_trial_checkpoint(trial, checkpoint)
(pid=12287)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 457, in _sync_trial_checkpoint
(pid=12287)     trial, checkpoint.value))
(pid=12287) ray.tune.error.TuneError: Trial tune_function_33667_00000: Checkpoint path /home/ray/ray_results/tune_function_2021-11-13_23-48-05/tune_function_33667_00000_0_lr=0.001_2021-11-13_23-48-05/checkpoint_-00001/ not found after successful sync down.
```

### Versions / Dependencies

python 3.7, ray 1.8

### Reproduction script

`RAY_ADDRESS=anyscale://cluster-7 python tune_cifar_pytorch_pbt_example.py --use-gpu`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by worldveil** [comment]
@krfricke it seems like all the default Tune examples will fail on a k8s cluster with default checkpointing (rsync). 

Can we add an error message here pointing users to cloud checkpointing docs if it fails in this case?
https://docs.ray.io/en/master/tune/user-guide.html#using-cloud-storage

"Are you running on a k8s or managed cluster? rsync will not function due to a lack of SSH. You'll need to use cloud-checkpointing if that's the case, see instructions here <LINK>"

**Comment by iycheng** [comment]
I've put it in the release blockers spreadsheet. Please don't duplicate it there.
