### ISSUE TITLE
[CI][Bug] CI uploads wrong Ray PR wheels to S3.

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#20334]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Similar to #18702, the PR wheel that's uploaded to s3 can be wrong and doesn't have the matching commit.

### Versions / Dependencies

master

### Reproduction script

https://beta.anyscale.com/o/anyscale-internal/configurations/app-config-details/bld_hZWCwS5NAWEaxsmvjB7sXFPV

One bad wheel: https://ray-ci-artifact-pr-public.s3.amazonaws.com/949401e39e5de011732a5709775b5c84f70ea4d6/tmp/artifacts/.whl/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jjyao** [comment]
cc @simon-mo @krfricke

**Comment by rkooo567** [comment]
Another example; 

https://ray-ci-artifact-pr-public.s3.amazonaws.com/34a0845b190c15806256aa3f422e2dfdfb1195de/tmp/artifacts/.whl/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl

Contains 846bdaf687ab5f2a7b84c02901baa68ec5c0e772

**Comment by simon-mo** [comment]
I ran into this as well and i have no clue so far.
