### ISSUE TITLE
[Bug] missing set_object_store_client_options

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#20344]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I set `object_store_memory` on an actor but when the actor is initialized I get the following error:

```
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 647, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
AttributeError: 'ray._raylet.CoreWorker' object has no attribute 'set_object_store_client_options'
An unexpected internal error occurred while the worker was executing a task.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff0f53ace4f42d7f316e64b36b01000000 Worker ID: 3a8c443e45349ebda7cdcf949273321eeaf55a8bfad34cb776660ac5 Node ID: 49bf1bc53fcaaf4a5ed10c71a89d45b729a6b930589963d1373c0cdb Worker IP address: 10.42.3.26 Worker port: 10003 Worker PID: 324
(pid=324) 2021-11-14 12:38:52,749	ERROR worker.py:428 -- SystemExit was raised from the worker
(pid=324) Traceback (most recent call last):
(pid=324)   File "python/ray/_raylet.pyx", line 647, in ray._raylet.task_execution_handler
(pid=324)   File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
(pid=324) AttributeError: 'ray._raylet.CoreWorker' object has no attribute 'set_object_store_client_options'
(pid=324) 
(pid=324) During handling of the above exception, another exception occurred:
(pid=324) 
(pid=324) Traceback (most recent call last):
(pid=324)   File "python/ray/_raylet.pyx", line 673, in ray._raylet.task_execution_handler
(pid=324) SystemExit
```

### Versions / Dependencies

Commit 66aac2e21925f64255803d0002222ab0d69f6a51 on Ubuntu

### Reproduction script

@ray.remote(max_restarts=5, object_store_memory=10)
class LimitedMemActor(object):    
    def __init__(self):
        import random
        self.value = 0

    def greet(self):
        import numpy as np
        self.value += 1
        return f"Hi {self.value}"

limited_mem_actor = LimitedMemActor.remote()
actor_results = list(map(lambda x: limited_mem_actor.greet.remote(), range(1, 100)))

### Anything else

`set_object_store_client_options` was removed in dbd32601415692c51caa930256f0c90a96b6204a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
cc @scv119

**Comment by Willian-Zhang** [comment]
Is `object_store_memory` deprecated or not? What's an proper way to set this limit rn?

**Comment by jjyao** [comment]
Sorry for missing this issue. Yea, you don't need to set object_store_memory and we do plan to deprecate it.

**Comment by zhe-thoughts** [comment]
@jjyao Looks like this can be closed?

**Comment by jjyao** [comment]
`object_store_memory` is deprecated for actor as of 2.0. You can config object spilling instead (https://docs.ray.io/en/releases-2.0.0/ray-core/objects/object-spilling.html) for out-of-core processing.
