### ISSUE TITLE
[RFC][Java] `Ray.getActor()` returns an `Optional` instead of throwing exception.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#20356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We return an Optional in Java `Ray.getActor()` while throwing an ValueError from Python `ray.get_actor(name)` 
Should we align it to Python version? @kfstorm @chaokunyang @raulchen 
Some backgrounds: https://github.com/ray-project/ray/pull/20135#discussion_r748997125

PS: Since this is an API change, if we‘re going to do that, we still need to consider the backward compatibility.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by raulchen** [comment]
I'm in favor of `Optional`. Throwing a ValueError when something is absent is a common practice in Python, but not in Java.

**Comment by kfstorm** [comment]
I'm not sure what's the common practice in Java. But since we throw an exception if the object is lost on `Ray.get(objRef)`, shouldn't we do the same for `Ray.getActor(name)`?

**Comment by raulchen** [comment]
For `Ray.get(objRef)`, I think it makes sense to throw an exception. Because if the object is absent, it does indicate an exception (e.g., it's evicted or its owner is dead).

**Comment by kfstorm** [comment]
@raulchen It can also indicate a user error, which applies to `Ray.getActor(name)` as well.

**Comment by raulchen** [comment]
These 2 cases are different. 
For `Ray.getActor(name)`, as the argument is a string, it can be used to check if an actor with the given name exists. 
While for `Ray.get(objectRef)`, as the argument ObjectRef is generated by Ray, the object must be present unless there is an error.

**Comment by kfstorm** [comment]
I see your point. In Java, we usually don't throw an exception to represent a valid state, but it's common in Python. In this case, the absence of a named actor is not considered an error, hence we shouldn't throw an exception in Java.
