### ISSUE TITLE
[release][nightly] AWS&GCP related tests failed in nightly tests

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20360]
`aws_no_sync_down`: https://buildkite.com/ray-project/periodic-ci/builds/1625#45e54933-4ac2-47b4-ac01-1572fec9e210
`aws_ssh_sync`: https://buildkite.com/ray-project/periodic-ci/builds/1625#b1cc0af9-563d-439b-b1ec-1acc081fa7b3
`aws_durable_upload`: https://buildkite.com/ray-project/periodic-ci/builds/1625#2a15f70d-12c9-4aef-93e5-2fc35668878e
`gcp_k8s_durable_upload `: https://buildkite.com/ray-project/periodic-ci/builds/1625#b02b515f-2426-49b2-bc97-204de57d905c

App config build failure:
``
[INFO] 11/14/2021, 10:10:47 AM: * Step 10/13 (commit,modifyfs) : RUN printf "[GoogleCompute]\nservice_account = default\n" > /home/ray/.boto  (1aaa4230)
[ERROR] 11/14/2021, 10:10:47 AM: sh: 1: cannot create /home/ray/.boto: Permission denied

[ERROR] 11/14/2021, 10:10:47 AM: Command exited with 2

[INFO] 11/14/2021, 10:10:56 AM: * Removed 25 directories under /
[ERROR] 11/14/2021, 10:10:56 AM: failed to execute build plan: execute stage: build stage 0: build node: do execute: execute step: cmd wait: exit status 2
```

**Comment by yiranwang52** [comment]
Also CC @allenyin55 
looks like permission in base image changed.

**Comment by yiranwang52** [comment]
To manually repro:
```
docker run -it --entrypoint=/bin/bash --rm anyscale/ray:nightly-py37
printf "[GoogleCompute]\nservice_account = default\n" > /home/ray/.boto
```
This isn't a problem with released version `ray:latest`

**Comment by yiranwang52** [comment]
It's because in latest nightly, there is already a .boto in base image
```
-rw-rw-r-- 1 root root    43 Nov 15 08:00 .boto
```

**Comment by yiranwang52** [comment]
it was added in #8020.
It has the same content as the .boto file these tests are trying to add for GCP.
Better to update the tests to remove this line.

**Comment by yiranwang52** [comment]
Fix: https://github.com/ray-project/ray/pull/20407/files
