### ISSUE TITLE
Deploy ray on kubernetes

### ISSUE THREAD

**Issue by knightXun** [ray-project/ray#2037]
I notice ray just use docker deploy ray system, kubernetes is must better then docker.So can i send a pr about kubernetes to deploy ray?

**Comment by richardliaw** [comment]
yes, that would be greatly appreciated!

**Comment by robertnishihara** [comment]
We should look into making a Helm chart. That might be the easiest way for Kubernetes users to deploy Ray. https://helm.sh/

**Comment by richardliaw** [comment]
Awesome! It would be great to create a WIP PR as soon as possible so that
we can provide intermediate feedback or assistance!

**Comment by knightXun** [comment]
@richardliaw due to evil great-wall Firewall, I meet many compile errors, some package can't be downloaded. can I use old packages like ray-0.4.0 to build images ? is that ok?

**Comment by robertnishihara** [comment]
It should be fine to just install Ray with `pip`.

**Comment by knightXun** [comment]
@robertnishihara ok, I will retry, and do my best.

**Comment by robertnishihara** [comment]
What do you mean by "old packages"? Ray 0.4.0 is the latest release, right?

**Comment by ericl** [comment]
Note that there is also this old issue to support Kubernetes in the autoscaler https://github.com/ray-project/ray/issues/1437

**Comment by knightXun** [comment]
@robertnishihara  I spent two days, now i built images successfully.
@ericl ok

**Comment by robertnishihara** [comment]
@knightXun that's great! Can you share the config files or instructions that you used to do this? And also instructions for how to try it out?

**Comment by knightXun** [comment]
@robertnishihara is there only one ray-master in the cluster?

**Comment by robertnishihara** [comment]
Right now, for the purposes of starting up a Ray cluster, there is a single "head" node, and a number of "worker" nodes.

The only difference is that the "head" node runs some additional processes (a global scheduler, some redis servers, some other things) in addition to the ones that the "worker" nodes have.

We don't really need a "head" node. E.g., the redis servers can live anywhere and so can the global scheduler and other extra processes. The main reason that it is this way is that it's easier to specify the command line arguments for starting things up this way.

So yes, you start one "head" node (which I think is what you mean by "ray-master").

**Comment by knightXun** [comment]
@robertnishihara ok, thanks. I will deploy one head node.

**Comment by knightXun** [comment]
@robertnishihara  I used kubernetes deploy a redis cluster. I noticed a head node will startup a redis. So i really want to get rid of this redis then using the redis cluser. In one word, I want run 'head' node expert that      redis.I need every processes expect that redis. So how can i do that?

**Comment by richardliaw** [comment]
Yeah, I believe https://github.com/ray-project/ray/pull/2058 does not intend to have NodeProvider/Autoscaler integration, which is probably the only ongoing effort that I'm aware of integrating ray with k8s. 

Would you be up for taking a cut at a NodeProvider for kubernetes?

**Comment by knightXun** [comment]
As for autoscalar , we can create a k8s original hpa  to solve it.But this hpa can only autoscale ray by cpu/memory, qps maybe. we can use prometheus_client expose the other metrics that autoscalar needs.

**Comment by knightXun** [comment]
As for nodeprovider, kubernetes already support aws/gce/gke.

**Comment by worrel** [comment]
@knightXun NodeProvider also provides internal/external node IP & the ability to create more nodes (which I interpreted in Kubernetes to mean more pods).  So i think we'd need a dedicated kubernetes nodeprovider since pod IP != IP of aws/gce node on which it runs.  i'll take a look at this later this week when I have some time.

**Comment by robertnishihara** [comment]
Closing so we can consolidate kubernetes documentation issues at #1353.

**Comment by kyprifog** [comment]
@robertnishihara I noticed that you had mentioned in passing using helm for ray.  Is this something you are still interested in doing?  Or did you decide on going a different direction?

**Comment by richardliaw** [comment]
@Gekho457 is now the main person driving Kubernetes on Ray! Maybe we can open another issue to discuss this?

**Comment by Gekho457** [comment]
Here's the new issue:
https://github.com/ray-project/ray/issues/12654

**Comment by Gekho457** [comment]
Also, feel free to post about this on our Discussion page: https://discuss.ray.io/
