### ISSUE TITLE
[rllib] RLlib installation installs tensorflow even tensorflow-gpu is available

### ISSUE THREAD

**Issue by arisliang** [ray-project/ray#2038]
Shouldn't tensorflow-gpu be enough to satisfy the installation dependency?

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 3.6.4
- **Exact command to reproduce**: `pip install 'ray[rllib]'`

**Comment by richardliaw** [comment]
Seems like this might be a TF + pip issue... 

Would it suffice just to add a line suggesting to add `--no-deps` for people who have their own tensorflow build?

**Comment by arisliang** [comment]
Will `--no-deps` ignore other dependencies as well, or it ignores TF only if tf already exists?

**Comment by richardliaw** [comment]
It will ignore all dependencies.

Another option is to be explicit about asking users to install TF
separately and not include it as a dependency, as Keras does.

**Comment by arisliang** [comment]
Install TF separately is probably better then, if even Keras does that as well. Because CPU and GPU version is quite different, essentially the dependency included here at most is for the CPU version. For GPU version, user will have to refer to tf installation instructions anyway.

**Comment by richardliaw** [comment]
(Fixed by #2178)
