### ISSUE TITLE
[Bug] modin-on-ray's unwrap_partitions is 100x slower on Mac than on Windows

### ISSUE THREAD

**Issue by mvashishtha** [ray-project/ray#20388]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I was doing some development on [Modin](https://github.com/modin-project/modin) and wanted to call [unwrap_partitions](https://github.com/modin-project/modin/blob/7a8158873e77cb5f1a5a3b89be4ddac89f576269/modin/distributed/dataframe/pandas/partitions.py#L22), which uses Ray to materialize the partitions constituting a Modin dataframe. I found that the function call took 122 seconds on my Macbook, but 721 milliseconds on a Windows computer.

### Versions / Dependencies

Before running the reproduction script, install Modin with

`pip install modin`

and download [this file](https://drive.google.com/file/d/11fyF1Tpz1207wA9Zq3nVrKZ7qJj10j8D/view?usp=sharing).

My Mac is on:
- MacBook Pro (16-inch, 2019), macOS Big Sur 11.5.2
- Python 3.8.8
- Ray 1.8.0
- Modin  0.11.1+37.g0a3acc15
- RAM: 16 GB 2667 MHz DDR4 
- `ray.cluster_resources()`: {'CPU': 16.0,
 'object_store_memory': 3248034201.0,
 'memory': 6496068404.0,
 'node:127.0.0.1': 1.0}

The Windows computer is:
- Windows 10 machine with 10 cores
- Python 3.8.5
- Ray 1.7.1
- Modin 0.11.1+45.g41213581

### Reproduction script

from modin.distributed.dataframe.pandas import unwrap_partitions
import modin.pandas as pd
import ray
from modin.config import NPartitions
fdf = pd.read_csv("test_700kx256.csv")
%time ray.wait(unwrap_partitions(fdf, axis=0), num_returns=NPartitions.get())

### Anything else

Some other Modin operations have been drastically slower on my Mac than on the same Windows machine. I have observed the same problem with other Macs. I have tried to provide a simple, reproducible example here.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by devin-petersohn** [comment]
@wuisawesome Is someone available to take a look? This appears to be an object store issue.

**Comment by wuisawesome** [comment]
@devin-petersohn @mvashishtha are y'all able to reproduce this without a dataset? Or really ideally, simulate modin's behavior here with just the ray core? 

cc @scv119 @rkooo567

**Comment by mvashishtha** [comment]
@wuisawesome here's an example that doesn't use Modin. We do need the data to be about 0.8 GB total, as it is here, to see a major difference in speed:

```python
import numpy as np
import ray
import pandas as pd
import time

ray.init()

objs = [[ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8)))) for _ in range(8)] for _ in range(8)]

@ray.remote
def f(*objs):
    return pd.concat(objs)

s = time.time()
l = [f.remote(*objs[i]) for i in range(len(objs))]
ray.wait(l, num_returns=len(l))
print(time.time() - s)
```

This takes 224 and 132 seconds on two trials on the macbook from the first comment, but just .69 seconds on the windows computer from the first comment.

**Comment by wuisawesome** [comment]
@mvashishtha thanks, do you also mind sharing your `ray.cluster_resources()` and the ram on the machines?

**Comment by devin-petersohn** [comment]
@wuisawesome Machine specs are in the first post.

**Comment by wuisawesome** [comment]
@devin-petersohn I'm mostly wondering about RAM specifically (I don't think it's mentioned) because I'm wondering if we're getting object spilling on the mac repro. Btw when I run the script locally (also a 16inch 2019 macbook pro), it take 6s to run (e2e including the `ray.init` and everything).

**Comment by devin-petersohn** [comment]
I see, that makes sense. The Mac machine has 16GB of memory, and there should be no object spilling.

Could this be a dependency issue? Do you reproduce the issue with a fresh conda environment?

**Comment by mvashishtha** [comment]
@wuisawesome I edited my `cluster_resources` and RAM into the Mac specs in my first comment.

**Comment by devin-petersohn** [comment]
@wuisawesome @scv119 @rkooo567 What else do you all need to reproduce this? This is a blocker for us.

**Comment by pcmoritz** [comment]
@czgdp1807 and @mattip Can you look into this?

**Comment by pcmoritz** [comment]
Thanks for following up on this @devin-petersohn and thanks for the repro!

**Comment by wuisawesome** [comment]
@pcmoritz this is actually faster on windows, so it probably isn't a windows problem?

**Comment by wuisawesome** [comment]
Btw I just got what I think is a reliable repro by setting object store memory explicitly. Without the object store memory part, it runs quickly (< 7s), with the object store memory part, it takes 98s. 

@scv119 @rkooo567 If I had to guess, I'd say this is an object spilling bug? 

```
import numpy as np
import ray
import pandas as pd
import time

ray.init(object_store_memory=3248034201)

objs = [[ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8)))) for _ in range(8)] for _ in range(8)]

@ray.remote
def f(*objs):
    return pd.concat(objs)

s = time.time()
l = [f.remote(*objs[i]) for i in range(len(objs))]
ray.wait(l, num_returns=len(l))
print(time.time() - s)
```

**Comment by pcmoritz** [comment]
Haha wow, I didn't realize this was actually faster on Windows! First time something is faster on Windows I think :)

**Comment by wuisawesome** [comment]
@devin-petersohn actually as a short term work around to unblock you, can you manually set `object_store_memory` to a higher value for now?

**Comment by mvashishtha** [comment]
@wuisawesome Even with 3.75x the object store memory, that script takes 163 seconds on the same mac I've been using throughout:

```python
import numpy as np
import ray
import pandas as pd
import time

ray.init(object_store_memory=3248034201*3.75)

objs = [[ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8)))) for _ in range(8)] for _ in range(8)]

@ray.remote
def f(*objs):
    return pd.concat(objs)

s = time.time()
l = [f.remote(*objs[i]) for i in range(len(objs))]
ray.wait(l, num_returns=len(l))
print(time.time() - s)
```

That's about as much object store memory as Ray is willing to take. If I go to 4x, I get

```
ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (0.0 GB) is less than 0% of total.
```

**Comment by devin-petersohn** [comment]
Thanks @pcmoritz!

**Comment by rkooo567** [comment]
After the run, what's the output of ray memory --stats-only? 

Also, @pcmoritz does Windows support shared memory? Once of possibility is that Mac uses /tmp as a plasma store memory, which is probably a lot slower than shm (for example running things on Mac was a lot slower than Windows)

**Comment by mvashishtha** [comment]
@rkooo567 Immediatelyfter running the previous script with the change `object_store_memory=3248034201*3.625`, I got from `ray memory --stats-only`:

```
======== Object references status: 2021-11-23 21:38:52.033474 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 4104 MiB, 72 objects, 36.55% full, 36.55% needed
Objects consumed by Ray tasks: 256 MiB.
```

**Comment by rkooo567** [comment]
Is it same in the windows output? 

I feel like the diff probably just comes from shm vs /tmp, but I will wait for philipp for windows information

**Comment by rkooo567** [comment]
@wuisawesome it seems like his workload is slow without object spilling (whereas it is faster in your machine). Isn’t there possibility the issue is where plasma object is stored? (In mac, it is /tmp, and maybe his tmp is slow, and in windows, it probably uses shm)

**Comment by scv119** [comment]
oh @rkooo567 that's a good point. we don't have /dev/shm on Mac

**Comment by naren-ponder** [comment]
My results upon running the script:

> ======== Object references status: 2021-11-29 13:48:29.630798 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 3080 MiB, 40 objects, 93.31% full
Spilled 2052 MiB, 36 objects, avg write throughput 759 MiB/s
Restored 771 MiB, 3 objects, avg read throughput 286 MiB/s
Objects consumed by Ray tasks: 256 MiB.

Took me 113.09455108642578 seconds with resources:

> 
Out[3]: 
{'memory': 6963071387.0,
 'object_store_memory': 3481535692.0,
 'node:10.0.0.7': 1.0,
 'CPU': 16.0}

**Comment by devin-petersohn** [comment]
What else do you need from us to help move this along @wuisawesome @rkooo567 ?

**Comment by devin-petersohn** [comment]
Hi folks, wanted to check in on this. What else do you need?

**Comment by devin-petersohn** [comment]
@rkooo567 Thanks for the response. The performance on the new Macs is generally unacceptable, we are talking about 2 or 3 or 4 minutes for a task with <1GB of data dependencies, writing out <1GB to the object store. 

This is really important, and I will send ship you a new Mac on loan if that is what it takes to get this fixed. It is blocking critical development and usage.

cc @pcmoritz should I send you all a machine with instructions on installation to reproduce?

**Comment by rkooo567** [comment]
Hmm when you say new Mac, are you talking about M1 macbook?

**Comment by devin-petersohn** [comment]
No, not on M1. This is happening on Intel Macbook pro, I think related specs are in the first comment of the issue.

**Comment by rkooo567** [comment]
I have been looking into this a bit more, and @scv119 it looks like it takes about 1 minute to seal the object after it is created;

```
[2021-12-06 08:32:26,992 D 71235 386613851] store.cc:506: Finishing create object 480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000 request ID 82
[2021-12-06 08:33:28,662 D 71235 386613851] store.cc:271: sealing object 480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000
```

Do you know when this can happen?

**Comment by rkooo567** [comment]
Also, @devin-petersohn can you try

```python3
import numpy as np
import ray
import pandas as pd
import time

ray.init()

s = time.time()
objs = [[ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8)))) for _ in range(8)] for _ in range(8)]
print(time.time() - s)

@ray.remote
def f(*objs):
    s = time.time()
    result= pd.concat(objs)
    print(ray.put(result))
    print("took ", time.time() - s)
    return None

s = time.time()
l = [f.remote(*objs[i]) for i in range(len(objs))]
ray.wait(l, num_returns=len(l), fetch_local=False)
print(time.time() - s)
time.sleep(300)
```

-> use this script instead and give me output for both Windows & Mac following the below instruction.

Windows; Can you try running it without using shm & same object store memory as Mac? That says, start ray with `ray.init(_plasma_directory="[tmp dir that mounts on SSD]", object_store_memory=[same amount of object store memory as Mac])` and see the result? 

Mac: Can you try running this without swap memory? https://windsketch.cc/macbook-disable-swap/ -> this is the instruction.

If Windows is still a lot faster, and Mac has 1~2 straggler processes like this
```
(f pid=71253) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
(f pid=71253) took  4.93780779838562
(f pid=71252) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
(f pid=71252) took  4.9707770347595215
(f pid=71249) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
(f pid=71249) took  4.962975263595581
(f pid=71257) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
(f pid=71257) took  4.977849006652832
(f pid=71253) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
(f pid=71253) took  0.41484522819519043
(f pid=71254) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
(f pid=71254) took  61.75509691238403
(f pid=71251) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
(f pid=71251) took  62.12915802001953
66.74275207519531
(f pid=71256) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
(f pid=71256) took  66.21789193153381
```

I think then I can reproduce the issue on my Mac.

**Comment by devin-petersohn** [comment]
@rkooo567 This is what I get on windows: 

Initialized ray with:

```python
ray.init(_plasma_directory="/tmp", object_store_memory=8*10**9)   # "/tmp" is on SSD
```

Time logs:
```
1.951300859451294
0.754875898361206
 pid=58288) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
 pid=58288) took  0.16087603569030762
 pid=60260) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
 pid=60260) took  0.16087603569030762
 pid=54228) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
 pid=54228) took  0.1507406234741211
 pid=58944) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
 pid=58944) took  0.1402578353881836
 pid=49816) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
 pid=49816) took  0.10034632682800293
 pid=51792) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
 pid=51792) took  0.1316070556640625
 pid=60472) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
 pid=60472) took  0.16087603569030762
 pid=58468) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
 pid=58468) took  0.10034632682800293
```

**Comment by mvashishtha** [comment]
@rkooo567 

I followed your instructions on my Mac. I confirmed that `sysctl -a vm.compressor_mode` was 2 before running the script. The result was:

```
(f pid=670) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
(f pid=670) took  2.6811389923095703
(f pid=674) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
(f pid=674) took  2.68546199798584
(f pid=669) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
(f pid=669) took  100.98013496398926
(f pid=672) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
(f pid=672) took  101.09086203575134
(f pid=665) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
(f pid=665) took  124.84489488601685
(f pid=667) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
(f pid=667) took  125.37648892402649
(f pid=671) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
(f pid=671) took  125.51181387901306
126.05867576599121
(f pid=673) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
(f pid=673) took  125.43582272529602
```

I am currently on:

- Ray 1.8.0
- Python 3.8.8
- MacBook Pro (16-inch, 2019), macOS Big Sur 11.5.2
- RAM: 16 GB 2667 MHz DDR4

**Comment by rkooo567** [comment]
@mvashishtha Is it also initialized with the same object store memory as @devin-petersohn ? (8GB)

**Comment by mvashishtha** [comment]
@rkooo567 No, but I tried again from a clean reboot with swapping off, Ray 1.9.0, and the same object store memory. The result was:

```
3.589334011077881
(f pid=725) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
(f pid=725) took  95.86621809005737
(f pid=731) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
(f pid=731) took  95.87045192718506
(f pid=730) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
(f pid=730) took  97.40504431724548
(f pid=729) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
(f pid=729) took  143.84988689422607
(f pid=733) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
(f pid=733) took  144.01996326446533
(f pid=734) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
(f pid=734) took  145.20651698112488
(f pid=728) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
(f pid=728) took  164.49023699760437
165.6788969039917
(f pid=732) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
(f pid=732) took  165.2853000164032
```

`ray memory --stats-only` after the script gave:

```
======== Object references status: 2021-12-06 13:50:22.946147 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 2048 MiB, 64 objects, 26.84% full, 26.84% needed
Objects consumed by Ray tasks: 256 MiB.
```

**Comment by rkooo567** [comment]
@mvashishtha actually, can you try one more thing? 

If you run the test with object_store_memory=1*10**9, does it still take long time?

**Comment by mvashishtha** [comment]
@rkooo567 it's much faster with that much memory.

```
3.9019620418548584
(f pid=719) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
(f pid=719) took  2.4078662395477295
(f pid=720) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
(f pid=720) took  2.409072160720825
(f pid=719) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
(f pid=719) took  2.414275884628296
(f pid=720) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
(f pid=720) took  2.302288770675659
(f pid=719) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
(f pid=719) took  2.389883041381836
(f pid=720) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
(f pid=720) took  2.4492599964141846
10.131613969802856
(f pid=719) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
(f pid=719) took  2.2678987979888916
(f pid=720) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
(f pid=720) took  2.3231279850006104
```

and `ray memory --stats-only` gives:

```
======== Object references status: 2021-12-06 14:29:03.787635 ========
--- Aggregate object store stats across all nodes ---
Plasma memory usage 512 MiB, 16 objects, 53.69% full, 0.0% needed
Spilled 2048 MiB, 64 objects, avg write throughput 1218 MiB/s
Restored 2368 MiB, 74 objects, avg read throughput 933 MiB/s
Objects consumed by Ray tasks: 256 MiB.
```

**Comment by rkooo567** [comment]
Hmm so it looks like ray.put(obj) on /tmp is so much slower than using object spilling (writing to disk) on Mac. cc @scv119 

@mvashishtha as a last experiment, can you try initialize ray with `ray.init(_plasma_directory="/tmp", object_store_memory=8*10**9) ` on Linux and see if the performance matches the MacOS case?

**Comment by devin-petersohn** [comment]
I am interested in hearing @scv119's opinion on this issue: specifically the seal taking a significant amount of time.

@rkooo567 we don't have a Linux box at the moment, would a cloud machine work? That might not be something you need us for, but still happy to help in whatever way we can.

**Comment by rkooo567** [comment]
Yeah cloud machine works. Just want to know if writing to tmp is purely slow on Mac. I was suspecting the swap memory first, but it seems like he is still getting an issue when it is turned off

**Comment by devin-petersohn** [comment]
@rkooo567 you were able to reproduce the issue yourself though, correct?

**Comment by rkooo567** [comment]
Yes. It is slow on my Mac.

**Comment by rkooo567** [comment]
But as I mentioned we should figure out if the bug is from ray or systems (MacOs). The delay between create / seal kind of indicates it is that writing to /tmp is purely slow m. (Between create / seal, it memcpy into mmaped memory on tmp). I suspect this could be the root cause https://stackoverflow.com/questions/30956242/slow-memory-allocation-in-osx, but this might be clearer once we see if this is still slow on Linux.

**Comment by mvashishtha** [comment]
@rkooo567 on my Macbook, I tried to write to /tmp directly instead of using the object store. That gave the best performance for me so far. I ran:

```shell
mkdir -p /tmp/ray_concat/{0..7}/inputs/
```

and then

```python
import numpy as np
import ray
import pandas as pd
import time

ray.init()

s = time.time()
for i in range(8):
    for j in range(8):
        pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8))).to_pickle(f"/tmp/ray_concat/{i}/inputs/{j}.pkl")
print(time.time() - s)

@ray.remote
def f(i):
    s = time.time()
    result = pd.concat([pd.read_pickle(f"/tmp/ray_concat/{i}/inputs/{j}.pkl") for j in range(8)])
    result.to_pickle(f"/tmp/ray_concat/{i}/result.pkl")
    print("took ", time.time() - s)
    return None

s = time.time()
l = [f.remote(i) for i in range(8)]
ray.wait(l, num_returns=len(l), fetch_local=False)
print(time.time() - s)
```

and got 

```
3.5236802101135254
(f pid=3244) took  1.3453829288482666
(f pid=3235) took  1.2905640602111816
(f pid=3239) took  1.2991852760314941
(f pid=3242) took  1.3212089538574219
(f pid=3240) took  1.344235897064209
(f pid=3241) took  1.3124470710754395
(f pid=3236) took  1.3546371459960938
1.8764007091522217

(f pid=3238) took  1.3736701011657715
```

Does that suggest that writing to /tmp isn't the culprit?

**Comment by rkooo567** [comment]
Ray mmap on /tmp and copy the memory into the mmaped blocks (instead of directly writing to disk). So, it is a different case. Object spilling also writes things into /tmp, and the fact that it was fast explains this (because it uses the direct file IO in this case). If this https://stackoverflow.com/questions/30956242/slow-memory-allocation-in-osx is true, it kind of explains why this is a lot slower. I suspect using /tmp as a plasma dir on Linux is not as slow as MacOS.

**Comment by rkooo567** [comment]
Okay. I ran the same code on /tmp mounted plasma store on Linux (on Docker container), and it took
a.py
```python3
import numpy as np
import ray
import pandas as pd
import time
s = time.time()
print("start")
ray.init(object_store_memory=8e9, _plasma_directory="/tmp")
print("done", time.time() -s)

s = time.time()
objs = [[ray.put(pd.DataFrame(np.random.randint(0, 100, size=(2**14, 2**8)))) for _ in range(8)] for _ in range(8)]
print(time.time() - s)

@ray.remote
def f(*objs):
    s = time.time()
    result= pd.concat(objs)
    print(ray.put(result))
    print("took ", time.time() - s)
    return None

s = time.time()
l = [f.remote(*objs[i]) for i in range(len(objs))]
ray.wait(l, num_returns=len(l), fetch_local=False)
print(time.time() - s)
```

```
python a.py
start
2021-12-07 15:07:50,284 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8266
2021-12-07 15:07:50,286 INFO services.py:1837 -- object_store_memory is not verified when plasma_directory is set.
done 3.790452480316162
3.676954507827759
1.9108612537384033
(f pid=881) ObjectRef(32cccd03c567a254ffffffffffffffffffffffff0100000002000000)
(f pid=881) took  1.549422264099121
(f pid=884) ObjectRef(480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000)
(f pid=884) took  1.5525469779968262
(f pid=878) ObjectRef(ee4e90da584ab0ebffffffffffffffffffffffff0100000002000000)
(f pid=878) took  1.5674192905426025
(f pid=889) ObjectRef(a67dc375e60ddd1affffffffffffffffffffffff0100000002000000)
(f pid=889) took  1.558527946472168
(f pid=887) ObjectRef(4ee449587774c1f0ffffffffffffffffffffffff0100000002000000)
(f pid=887) took  1.5268173217773438
(f pid=852) ObjectRef(69a6825d641b4613ffffffffffffffffffffffff0100000002000000)
(f pid=852) took  1.565333604812622
(f pid=850) ObjectRef(623b26bdd75b28e9ffffffffffffffffffffffff0100000002000000)
(f pid=850) took  1.562201976776123
(f pid=890) ObjectRef(63964fa4841d4a2effffffffffffffffffffffff0100000002000000)
(f pid=890) took  1.5681102275848389
```
only about 1 second each. So, I think the issue is almost likely that MacOS is very slow when it allocates blocks for mmap as this issue https://stackoverflow.com/questions/30956242/slow-memory-allocation-in-osx indicates.

**Comment by mvashishtha** [comment]
@rkooo567 thanks for checking that. Will Ray have a fix for the slowness on MacOS?

**Comment by rkooo567** [comment]
Hmm in this case, the fix is tricky. Mmap is a core mechanism on all ray object creation, so fixing requires changes in this (since the issue is syscall itself seems not working well on MacOS). There could be other alternatives like recommending low object store memory for mac os. 

Cc @ericl @scv119 what do you guys think?

**Comment by ericl** [comment]
So it's looking like using large amounts of /tmp for object store memory on OSX is somehow slow, like 100x slower than a small object store. But a small object store is fine, right?

Couple questions:
- Is there a particular threshold of object store size where things suddenly get slower?
- Was this always a problem? Did it start with some Ray release?

In general, using large amounts of /tmp memory can cause system thrashing even on Linux systems. But generally it's OK on small machines. It would be good to understand if thrashing is the cause (e.g., very high amounts of IO/filesystem writeback activity), or if mmap is just somehow slow (as @rkooo567 proposes).

**Comment by scv119** [comment]
sorry swarmed by other issues.

>  have been looking into this a bit more, and @scv119 it looks like it takes about 1 minute to seal the object after it is created;
> 
> [2021-12-06 08:32:26,992 D 71235 386613851] store.cc:506: Finishing create object 480a853c2c4c6f27ffffffffffffffffffffffff0100000002000000 request ID 82
> [2021-12-06 08:33:28,662 D 71235 386613851] store.cc:271: sealing object 480a853c2c4c6f27ffffffffffffffffffffffff01

between those two are the actual writing of the object.

**Comment by scv119** [comment]
It seems most likely due to trashing (i.e. the OS tries to write back mmaped pages back to disk due to lack of physical memory), given the fact allocating 1GB of plasma store size doesn't cause this issue.  Maybe we should find some tools to confirm this.

**Comment by ericl** [comment]
If it indeed is thrashing, then seems we should set a limit on the object store size that can be allocated to /tmp by default. In Linux, we already raise an error if the /tmp object store is configured to be >10GB. However on other platforms no error is raised: https://github.com/ray-project/ray/blob/master/python/ray/_private/services.py#L1851

**Comment by scv119** [comment]
after some reading, you i think you might be able to use `vmstat` to monitor the swap out pages during the process; this is the best indication of trashing.

**Comment by devin-petersohn** [comment]
I am not sure that this is thrashing. 

- We have disabled swapping above and the performance was not improved
- We also used a disk-based `_plasma_directory` with no improvement as well
- We had the best performance writing pickle files to `"/tmp"` from the worker, bypassing the object store completely. If thrashing was the problem why would bypassing plasma altogether help?

Maybe I am missing something here, but I thought we had already ruled out thrashing.

**Comment by ericl** [comment]
When object store is backed by /tmp (or any other filesystem other than /dev/shm), the operating system will be trying to write-back these to disk, regardless of whether swapping is enabled. But it might be something else.

I don't have a mac, but @rkooo567 @scv119 if you can reproduce I'd be happy to help dig into this.

**Comment by scv119** [comment]
Yeah. Unfortunately I can't get a reproduce on my Mac; tried different settings like the number of plasma store size and number of objects; range from 8GB to 40GB (my Mac has 64GB of memories)

**Comment by rkooo567** [comment]
I could reproduce this with 16gb mac. Maybe we can pair program to verify if thrashing is the root cause?

**Comment by rkooo567** [comment]
Btw, here's the initial investigation. 

- Seems like it only happens in 16 GB MacOS (doesn't happen in 64GB MacOS nor Linux). 
- What we found out is when we memcpy into mmaped /tmp directory "concurrently from many threads/processes", the slowdown happens. For example, after we disabled "parallel_memcpy (https://github.com/ray-project/ray/blob/30d3115c4585df3b5cead882b69c7a80c8f023b6/src/ray/util/memory.cc#L28)", if we create object one by one from a single process, the creation speed was as expected (fast). If we create objects concurrently from many processes, the slowdown starts happening.
- Issue doesn't occur when the memory usage of the plasma store is < 2GB on 16GB MacOS.

We are going to do further investigation, but this seems to be closely related to MacOS kernel implementation (at least from what I've observed). There's a possibility of paging, but it is not clear. It's also possible it is due to MacOS mmap implementation. 

One thing we are trying to do is @scv119 running the workload with 4X memory usage (since his MacOS has 4X more memory) and see if the same issue is still happening. If so, we should probably cap the memory limit on 16GB MacOS to be around 2GB (since the issue doesn't seem to happen in this case).

**Comment by devin-petersohn** [comment]
Thanks @rkooo567 for the update. Let us know if/how we can help on this.

**Comment by wuisawesome** [comment]
@rkooo567 @scv119 as a short term workaround, I wonder if we should feature flag parallel memcpy and turn it off by default on mac?

**Comment by scv119** [comment]
My intuition is there is some mmap policy involved in Mac that differs 16GB from other memory size. The best bet is to search/ask some OSX kernel engineer to be sure.

Disable parallel memcpy might need a bit of work, since we need to serialize multiple workers write to PlasmaStore; However we could force memory allocation on different mmap for Mac.
Another hackish workaround is to limit the plasma store size to 2GB for 16GB Mac.

**Comment by ericl** [comment]
+1 to limit to 2GB. Is there any downside for this?

**Comment by scv119** [comment]
> +1 to limit to 2GB. Is there any downside for this?
Policy could change. We also don't know how things works for different settings (i.e. 8GB?)

**Comment by ericl** [comment]
How about limiting it to 2GB for any kind of Mac?
