### ISSUE TITLE
[Bug] DatasetPipeline .iter_epochs() can lead to infinite loops

### ISSUE THREAD

**Issue by crclark** [ray-project/ray#20394]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

#### The bug

Iterating over the epochs of a DatasetPipeline containing a finite number of epochs can loop forever in some cases where it should not.

This example from the Dataset docs works correctly:

```python
pipe = ray.data.from_items([0, 1, 2, 3, 4]) \
    .repeat(3) \
    .random_shuffle_each_window()

for i, epoch in enumerate(pipe.iter_epochs()):
    print("Epoch {}", i)
    for row in epoch.iter_rows():
        print(row)
```

Removing the last two lines that print the rows of each epoch causes it to loop forever:

```python
pipe = ray.data.from_items([0, 1, 2, 3, 4]) \
    .repeat(3) \
    .random_shuffle_each_window()

for i, epoch in enumerate(pipe.iter_epochs()):
    print("Epoch {}", i)
```

Trying to call `list(pipe.iter_epochs())` also hangs.

#### Expected behavior

Any traversal of `.iter_epochs()` should terminate if `.repeat(n)` was invoked with finite `n`.

### Versions / Dependencies

Ray 1.8.0, Python 3.8.4, Ubuntu

### Reproduction script

```python
pipe = ray.data.from_items([0, 1, 2, 3, 4]) \
    .repeat(3) \
    .random_shuffle_each_window()

for i, epoch in enumerate(pipe.iter_epochs()):
    print("Epoch {}", i)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
cc @clarkzinzow

**Comment by ericl** [comment]
Btw great issue report. @crclark are you interested in submitting a fix? If not, we'll get to this prior to datasets GA.

**Comment by crclark** [comment]
Sadly I won't have time to submit a fix. Thanks!
