### ISSUE TITLE
[Bug] test_threaded_actor seems to start hanging in the master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20395]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Threaded actor stress tests seems to start failing. Looks like it is hanging (this succeeds 4~5 times in a row before this happens).

https://buildkite.com/ray-project/periodic-ci/builds/1634#8801ae86-d2ff-41ce-bf3c-b9b5e9970adb

From the same range as ^

this is the commit range. I think it could be highly likely one of @scv119 PR given that it is from threaded actor stress tests. 

<img width="1268" alt="Screen Shot 2021-11-15 at 2 52 19 PM" src="https://user-images.githubusercontent.com/18510752/141865348-df0629cf-0d8b-4206-86ae-ecd1595b194a.png">
 

### Versions / Dependencies

master

### Reproduction script

Threaded actor stress test. Note that this test is not supposed to hang because it just kills & create actors again and again. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
Filtered out user name.

**Comment by rkooo567** [comment]
Thanks for catching that!

**Comment by scv119** [comment]
bisecting: 6777a31751f6851feee7df1604e6139ac00a52e7 [passed](6777a31751f6851feee7df1604e6139ac00a52e7).

**Comment by scv119** [comment]
bisecting:  477b6265d98cb03676c1021df314d0769e43e885  [passed too](https://beta.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_g7mYRhm3vFjaDfFaEJ3zKk7T?command-history-section=command_history)

**Comment by scv119** [comment]
bisecting: 117219557190101d5a7cf776843e602ec5d06e74 [passed too](https://beta.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/app-config-details/bld_1an5Dx5Ga6tg37qgwcYwe7X3)

**Comment by rkooo567** [comment]
Hmm... not great lol. 

Maybe we can bump down the priority and collect more data in this case?

**Comment by scv119** [comment]
bisecting: 5b1c8e46e16b04b46463eaef523e661f4e31e8ff [passed](https://beta.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_FnWrsjHWPaN1KPznt7MCkn8p?command-history-section=command_history)

**Comment by scv119** [comment]
@rkooo567 so the test is flaky by itself.

**Comment by rkooo567** [comment]
seems like a fluke
