### ISSUE TITLE
[placement group] Support placement groups with no resources

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#20401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Users may want to use the scheduling hints w/o resources for each actor.

Needed in Serve: https://github.com/ray-project/ray/issues/19771

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
@rkooo567 @scv119 I assume this should be straightforward? Can we get it prioritized?

**Comment by rkooo567** [comment]
I think implementation-wise, it is simple, but what’s the use case? (This has no practical meaning iiuc). You can just schedule without specifying a bundle index or not use placement group at all?

**Comment by ericl** [comment]
In the spirit of not supporting hacks, would implementing the colocation scheduler hint avoid the need for this? https://github.com/ray-project/ray/issues/18524

**Comment by edoakes** [comment]
@ericl yes I think that would actually be preferred :)

Though we need one other thing -- the ability to force the autoscaler to scale up immediately for the actors instead of respecting the throttling/delay (that's why we use 1 PG per actor right now).

**Comment by ericl** [comment]
Got it, I think that's easy enough to add (some plumbing to split up task vs actor resource demands): cc @DmitriGekhtman for prioritization. That feature is orthogonal from this issue though right (you'd never create 0-cpu actors of that sort?)

**Comment by DmitriGekhtman** [comment]
Oh, scaling up immediately for actors makes a lot of sense (since they're long-lived).
The context was tldr for me -- can we close this issue and open a new one for scaling up immediately for actors?

**Comment by edoakes** [comment]
That's right @ericl

**Comment by DmitriGekhtman** [comment]
Let's keep this open. I was digging for this issue recently in the context of GCS/autoscaler interface redesign.
