### ISSUE TITLE
[Bug] Lineage reconstruction not working always with no streaming shuffle.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20408]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Please refer to https://github.com/ray-project/ray/pull/20277#discussion_r748034969

When enabling commented out test, I discovered the test is not passing as expected.

In the non streaming shuffle workload, all tasks are owned by the driver, so it should be a good representative workload for lineage reconstruction.

The test keeps killing worker nodes every X seconds. 

The expected behavior of non streaming shuffle + node failures is
1. Raising an exception without lineage reconstruction. -> Seems like it hangs occasionally.
2. succeeding with the lineage reconstruction -> Seems like it doesn't always succeeds.

### Versions / Dependencies

master

### Reproduction script

Check the link. This is the example;

```
@pytest.mark.skip(reason="Flaky.")
@pytest.mark.parametrize(
    "ray_start_chaos_cluster", [{
        "kill_interval": 8,
        "env_vars": {
            "RAY_lineage_pinning_enabled": "true"
        },
        "head_resources": {
            "CPU": 1
        },
        "worker_node_types": {
            "cpu_node": {
                "resources": {
                    "CPU": 8,
                },
                "node_config": {},
                "min_workers": 0,
                "max_workers": 4,
            },
        },
    }],
    indirect=True)
def test_chaos_lineage_reconstruction(ray_start_chaos_cluster):
    shuffle.run(
        ray_address="auto",
        no_streaming=True,
        num_partitions=200,
        partition_size=15e6)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment]
@rkooo567 I was just trying this out and it looks like the fixture actor isn't always getting scheduled on the head node, so we end up sometimes killing the driver node.

**Comment by rkooo567** [comment]
@stephanie-wang is this blocked by https://github.com/ray-project/ray/blob/master/python/ray/tests/test_chaos.py#L211? Or the pin existing object should be able to re-enable tests? (I saw it is not enabled yet)

**Comment by stephanie-wang** [comment]
Ah right, thanks for the reminder! I'll try to open a PR to fix it this week.
