### ISSUE TITLE
[Release][Bug] Windows build failing in the master

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20416]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Windows build seems to fail in the master for some time.

https://flakey-tests.ray.io/

Need to fix it before proceeding the release

### Versions / Dependencies

master

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
https://github.com/ray-project/ray/pull/20437

**Comment by iycheng** [comment]
Close this one since we decide not to cherry-pick it https://github.com/ray-project/ray/pull/20437#issuecomment-972365927
