### ISSUE TITLE
[Bug] [RLlib] EpsilonGreedy exploration fails without normalized actions

### ISSUE THREAD

**Issue by SebastianBo1995** [ray-project/ray#20419]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When Setting the exploration to epsilon greedy and normalize_actions to False, the output of the action has always the shape of () without any regards to the actual action space. 

### Versions / Dependencies

Ray V1.8 

### Reproduction script

https://colab.research.google.com/drive/1BxyoHYcCcLMfO9arMWhirtvDHDkLWcuB#scrollTo=OEwI6lpMZCzi

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mvindiola1** [comment]
Hi @SebastianBo1995,

Epsilong-Greedy is an exploration strategy for Categorical (Discrete) action spaces. 

You are using TD3 in this case which only works for Continuous (Box) action spaces. 

You probably want to switch to GaussianNoise. 

Check out this link for more info:

https://docs.ray.io/en/latest/rllib-training.html#customizing-exploration-behavior

**Comment by SebastianBo1995** [comment]
Thanks for the information. 😃
