### ISSUE TITLE
[Java] Support RuntimeEnv and docker in container  for Java Worker

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#20425]
- [ ] Support starting java worker process in container.
- [x] Support specifying java dependencies in runtime env, both in job level and actor/task level.

**Comment by chenk008** [comment]
For now, java driver is initialized by `Ray.init()` which will load `ray.conf`.

To support java driver runtime env, we can add `runtime-env` into `ray.conf`. Sample is listed below:
```
ray {
  // ----------------------
  // Basic configurations
  // ----------------------

  // Address of the Ray cluster to connect to.
  // If not provided, a new Ray cluster will be created.
  address: ""

  runtime-env: {
     "jars":[
         "https://host/a.jar"
     ],
     "env_vars":{
         a: "b"
     }
  }
}
```

**Comment by chenk008** [comment]
And java driver can create tasks/actors with different runtime env, so we need add some new API. The runtime env will contain multiple plugins, so we can use a Map<String,Object> to store it.

# Here is some change in java API.

### Add setRuntimeEnv into io.ray.api.call.BaseActorCreator
```
public class BaseActorCreator<T extends BaseActorCreator> {
   private static final Gson DEFAULT_GSON = new Gson();

    public void setRuntimeEnv(Map<String,Object> runtimeEnv) {
        String jsonStr =DEFAULT_GSON.toJson(runtimeEnv);
        this.builder.setSerializedRuntimeEnv(jsonStr);
    }
}
```

### Add serializedRuntimeEnv into io.ray.api.options.ActorCreationOptions.Builder
```
public class Builder {
    public final String serializedRuntimeEnv;
}
```

# Sample with runtime env
```
Map<String, String> envs = new HashMap<String, String>();
envs.put("a", "b");
Map<String, Object> runtimeEnvMap = new HashMap<>();
Map<String, String> containerMap = new HashMap<>();
containerMap.put("image", "some_image");
runtimeEnvMap.put("container", containerMap);
runtimeEnvMap.put("env_vars", envs);

PyActorHandle actor =
Ray.actor(PyActorClass.of("test", "RuntimeEnvActor"))
  .setRuntimeEnv(runtimeEnvMap)
  .remote();
```

**Comment by jovany-wang** [comment]
@SongGuyang @raulchen CC the APIs.

**Comment by raulchen** [comment]
> The job agent will read the config about the runtime-env, and start the driver process with it. And runtime-env will affect the whole job.

The runtime env in the config file is used for job scope. So we'd better put it under `ray.job.runtime-env`.

**Comment by raulchen** [comment]
Regarding the actor- and task-level API, I have 2 suggestions:
1) Make it strong-typed instead of using a raw Map. The demo will look like this:
```java
RuntimeEnv runtimeEnv = RuntimeEnv.builder()
    .setEnvVar("a", "b)
    .setContainerImage("image_url")
    .build();
Actor<> actor = Ray.actor(...).setRuntimeEnv(runtimeEnv).remote();
```
2) Do not add gson dependency to the api module. We can delay serializing the runtime env object in the runtime module.

**Comment by jovany-wang** [comment]
`dynamic options`, `codesearchpath` can also re-impled in runtime env.
