### ISSUE TITLE
Add dataset execution metrics API

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#20445]
We can piggyback some execution time metrics on the dataset return metadata. This can include:
- Execution time per task (min,max,mean)
- Queueing time per task (min,max,mean)
- Input/output sizes (min,max,mean)
- Overall stage execution time

This should be accessible via some metrics method on the dataset object itself. We also should think about it should work for dataset pipelines.

cc @clarkzinzow @scv119

**Comment by clarkzinzow** [comment]
@ericl I was going to leave this open until split is instrumented, or should I open a separate issue for that?

**Comment by ericl** [comment]
We can make that separate.
