### ISSUE TITLE
[C++ Worker] Align APIs  for Namespace concept.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#20460]
This issue is used to track the work items to port C++ APIs for namespace concepts.

- [x] Remove APIs to global actor and global PG. #20468 
- [x] Support specifying the namespace for job.
- [x] Support generating an UUID string as the namespace for an anonymous namespace.
- [ ] Support `GetNamespace()` API.
- [x] Support `GetActor(name, namespace)` 
- [ ] and `GetPlacementGroup(name, namespace)`.
- [ ] Update doc page.

**Comment by jovany-wang** [comment]
@qicosmos @SongGuyang @kfstorm

**Comment by jovany-wang** [comment]
@MissiontoMars

**Comment by WangTaoTheTonic** [comment]
job anonymous namespace, creating actor with specified names, getting actor with namespace has been supported.
Two subtasks and doc to do. Will implement them ASAP.

**Comment by jovany-wang** [comment]
Closing this. If it's necessary, please file a new issue.
