### ISSUE TITLE
[Bug] [Ray Autoscaler] Parallel Launch of Head and Worker Node

### ISSUE THREAD

**Issue by michaelzhiluo** [ray-project/ray#20463]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

For multi-node clusters, Ray Autoscaler will first setup Ray Head node first, and then setup a bunch of Ray Worker nodes in async parallel. For examples where instances take forever to launch (because the setup takes a long time), this can be a tedious process, as the user needs to wait for head node (30 min to complete) and then wait for worker nodes (>=30 min to complete).

Ideally, both the head and workers should launch in parallel. We were wondering if this is an intended design feature or it is a bug that should be fixed.

### Versions / Dependencies

Most recent version of Ray and Ray Autoscaler

### Reproduction script

Run any autoscaler config that launches more than 1 node. This sequential dependency is always there.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
This isn't something we intend to fix. To optimize launch speed, you can pre-bake AMIs or use docker images.

**Comment by franklsf95** [comment]
@ericl I'm curious is there a reason that head and worker nodes provisioning and setup _cannot_ happen concurrently?

**Comment by ericl** [comment]
It can, and does in architectures like the k8s operator, kuberay, and in Anyscale. We don't intend to add new features to direct cloud autoscaling beyond stability and bug fixes.
