### ISSUE TITLE
[Bug] Autoscaler  doesn't scale CPU-only workloads to workers with GPU

### ISSUE THREAD

**Issue by andras-kth** [ray-project/ray#20476]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Clusters where *all* nodes have a GPU fail to autoscale on CPU-only workloads.
```
The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0} ,...
```

Changing the resource definition of the node type (leaving everything else intact) allows the cluster to autoscale.

I'm guessing that this _may_, in fact, be the intended behavior, as a cost-saving "feature".
In which case, the right "fix" would be to define node types both *with* and *without* GPU.

### Versions / Dependencies

Ray 1.8.0
Python 3.9

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hora-anyscale** [comment]
Per Triage Sync: Need to update docs to reflect this is intended behavior

**Comment by DmitriGekhtman** [comment]
The correct behavior is to avoid adding GPU workers when possible, but to add GPU workers when needed fulfill the workload.

The code for this is very straightforward to implement (max 5 lines, plus a test)
