### ISSUE TITLE
Be able to disable passing arguments and return values by reference

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#20470]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

`max_direct_call_object_size` defines the max size of the direct call object, 0 indicate passing by reference always.
There're applications which have the requirement on turn it off. It means they need pass by value always. Even if we can set a very large number for it, but it still not make sense semantically .

I'd like to do that, when this flag is -1, it means that we want to turn it off, indicating passing by value always.

@ericl @rkooo567 CC does it reasonable to your guys, or offer a reasonable workaround, thanks.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Why is it a requirement? The application shouldn't need to know, and
performance is better passing by reference.

**Comment by jovany-wang** [comment]
Let me make the words shorter.

The data in object store relies on the distributed GC to collect, and distributed GC relies on local GC to trigger, so we have an flag to trigger local GC `local_gc_interval_s`  https://github.com/ray-project/ray/blob/master/src/ray/common/ray_config_def.h#L276-L280

It triggers every 10m, which makes our online application happens vibration in every 10m. It's too bad for online applications.
We tried to increase the interval time, but it'll happens another issue about memory full.

Fairly, -1 indicates never pass by reference is the same semantic as 100 indicating limit 100B. So I don't think applications should not need to know it. 

If you have another idea on solving this issue, feel free to let me know.

**Comment by ericl** [comment]
Reference counting will immediately delete the references once they fall out of scope. The local gc is only in the rare edge case the object gets caught in a Python reference cycle.

You can avoid it by avoiding Python reference cycles, or calling gc.collect(). In Java, you could also call System.gc().

If calling GC is too high overhead, we could add an API to delete object copies explicitly from the object store (this is needed for other applications as well).

**Comment by ericl** [comment]
> Even if we can set a very large number for it, but it still not make sense semantically.

Actually I don't quite get this, why not just set it to a very large value? We can't set it to unlimited since you'll exceed the gRPC max message size. So something like 50MB will probably fix your use case, and also won't break gRPC.

**Comment by ericl** [comment]
Actually, I don't think GC is relevant here at all. The object reference created for passing arguments automatically by reference is never exposed to the application-level. So there is no chance it can get caught in a Python reference cycle or end up in some older Java GC generation. It should always be immediately discarded after the task finishes. If it isn't, that must be a bug.

> I'd like to do that, when this flag is -1, it means that we want to turn it off, indicating passing by value always.

There are other issues with having large values, such as hitting the gRPC max message size. I think if a user wants to raise it, they should set it explicitly to some large value, like 50MB, to bound the worst case outcome.

**Comment by jovany-wang** [comment]
Will investigate more details and then discuss here.

**Comment by jovany-wang** [comment]
@ericl I understood the 10min interval by default is used for addressing the cycle reference issue. But the cost of `System.GC()` in Java is still expensive because it stops the world. We set it to 24h for our user online applications, they still complain about it because all workers of the application stop the world at almost the same time every day.
(Note that many workers in production use more than 100G memory, STOP-THE-WORLD would take a long long long time.)

I'd like to make this behavior more natural instead of doing GC every interval. 

For example, I'd like to remove the behavior that doing FULL-GC in every interval.
Then, for object store memory, we can bookkeep the watermarks of every node's objectstore, and then trigger a local GC on the node whose object store is almost full.
For the in-memory store, we can remove the native object once `ray.get()` finished, and cache the objects in the language frontend. This can be avoid the cycle reference issue because the objects are all in trust to the language frontend.

Any thought, or correct me if I'm wrong?

**Comment by ericl** [comment]
@jovany-wang your concerns on the GC makes sense. However, for batch applications not running full GC can leak tons of memory and cause OOMs. Since OOMs are worse than slowdowns, I'd suggest keeping it on by default and documenting it as a option for production applications.

> For the in-memory store, we can remove the native object once ray.get() finished, and cache the objects in the language frontend. This can be avoid the cycle reference issue because the objects are all in trust to the language frontend.

Regarding this issue, when args are auto-converted to references those ObjectRef are never exposed to the application right? So how is it possible those end up in reference cycles?

**Comment by jovany-wang** [comment]
> Regarding this issue, when args are auto-converted to references those ObjectRef are never exposed to the application right?  

Yes.

For this case, data in callee's object store would not be freed. Is there any problem with cycle reference?
```python
@ray.remote
def recv(data):
   data   # not an object ref
   
recv.remote(huge_array)   # auto put in plasma under the hood for transport
```

**Comment by ericl** [comment]
Oh, there is one possibility of a cyclic ref here, not involving the ObjectRef, but the `data` array if it's mmaped (e.g., numpy array type).

Plasma can't delete the underlying object if the data array is mmaped. So even if the reference counter is at zero, the object will be pending deletion of the mmaped `data` array.

**Comment by chunweiyuan** [comment]
> Oh, there is one possibility of a cyclic ref here, not involving the ObjectRef, but the `data` array if it's zero-copy mmaped (e.g., numpy array type).
> 
> Plasma can't delete the underlying object if the data array is mmaped. So even if the reference counter is at zero, the object will be pending deletion of the mmaped `data` array.
> 
> Are you seeing this happen in your application?

Could this be what's happening at #20618?

**Comment by jovany-wang** [comment]
I proposed another approach to address the FullGC issue https://github.com/ray-project/ray/issues/21218 , so close this issue.
