### ISSUE TITLE
[runtime_env] Unhelpful error message when runtime_env fails to be installed

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#20483]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

```python
In [2]: @ray.remote(runtime_env={"working_dir": "s3://fake.zip"})
   ...: class A:
   ...:     def hi(self): pass
   ...:

In [3]: a = A.remote()
2021-11-17 10:43:40,587 INFO services.py:1338 -- View the Ray dashboard at http://127.0.0.1:8265

In [4]: a
Out[4]: Actor(A, 18495d6d384908064e9cd7d701000000)

(raylet) [2021-11-17 10:43:46,668 E 99870 16327337] agent_manager.cc:190: Failed to create runtime env: {"working_dir": "s3://fake.zip"}, error message: not enough values to unpack (expected 2, got 1)
(pid=gcs_server) [2021-11-17 10:43:46,668 E 99863 16327023] gcs_actor_scheduler.cc:316: Failed to lease worker from node e20be19e69f7d0c11022135b345b9d58ed42f7000687a482e38d248a for actor 18495d6d384908064e9cd7d701000000(A.__init__) as the runtime environment setup failed, job id = 01000000
```

### Versions / Dependencies

master

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
The actual exception also only returns a generic message:
```python
428 class RuntimeEnvSetupError(RayError):
429     """Raised when a runtime environment fails to be set up."""
430
431     def __str__(self):
432         return (
433             "The runtime environment for this task or actor failed to be "
434             "installed. Corresponding error logs should have been streamed "
435             "to the driver's STDOUT.")
```

We should remove the noisy C++ logs and instead return the underlying traceback here (it's already returned from the agent)

**Comment by rkooo567** [comment]
Cc @lixin-wei 

we are planning to work on this soon. (The work was separated by 2, support exception -> support better msg)

**Comment by lixin-wei** [comment]
> Cc @lixin-wei 
> 
> 
> 
> we are planning to work on this soon. (The work was separated by 2, support exception -> support better msg)

nice!

**Comment by rkooo567** [comment]
I am on it now! ETA is next Tu, but it could be delayed depending on other work I am doing.
