### ISSUE TITLE
Ray common storage configuration

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20497]
## Overview
Right now if the ray cluster is shutdown, all data will be lost, so for the services that require data living beyond that they need to do this in their own way. One drawback is that, the user might need to config this multiple times for different component. Right now, serve deployment metadata/tune checkpoints/workflow checkpoints/spilled objects will need persistent storage, and we should provide a storage component which can be used directly.

## Solutions
This [RFC](https://github.com/ray-project/ray/issues/18885) covers the API for storage client. 

To add more to the RFC, we need it to be integrated deeply with the object store for performance. (related [doc](https://docs.google.com/document/d/1parUH_Mk0zYQeOMReJIjTmEcDFgxGG-Cs55sbv72e1g/edit#))

**Comment by ericl** [comment]
Didn't realize this duplicated https://github.com/ray-project/ray/issues/18885, let me just link that instead.
