### ISSUE TITLE
[autoscaler] GCP support

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#2049]
It would be great if the autoscaler supported Google Cloud Platform.

I'm going to start implementing the GCP node provider soon. Thought I would open up this as a feature request to see if anyone else has done work towards this or possibly has any specific thoughts about the implementation (e.g. what should/could change from the aws node provider).

**Comment by AdamGleave** [comment]
I'd be happy to beta-test this, GCP has some attractive features for my workloads.

**Comment by hartikainen** [comment]
@AdamGleave Would be great to have some beta-testing help once this gets to master. I'm curious, what are the features that GCP has and AWS does not?

**Comment by AdamGleave** [comment]
The main one for me is the ability to specify custom instance types. This lets me get a higher CPU:GPU ratio than is possible on AWS, useful for my workloads given how expensive GPUs are on both AWS & GCP.

**Comment by richardliaw** [comment]
Hey Adam,

You can try out the GCP autoscaler by running `ray create_or_update
[cluster yaml]` off the current master, using this cluster yaml file: [ray
dir]/python/ray/autoscaler/gcp/example-full.yaml

I believe you should be able to specify custom instance types via the yaml.
Let me know how it goes!

**Comment by richardliaw** [comment]
This is merged in master, so closing this for now.
