### ISSUE TITLE
[release] aws_ssh_sync test failure

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20508]
https://buildkite.com/ray-project/periodic-ci/builds/1701#521058b3-4051-460e-b1c6-9367a427c114

**Comment by amogkam** [comment]
ok looks like this test is just flaky. Just re-ran it again on the release branch and it is passing. https://buildkite.com/ray-project/periodic-ci/builds/1701#bf9f1c16-c4ad-4d18-b762-3baa0df4fcd5
