### ISSUE TITLE
[Datasets] `iter_epochs` not iterating using native format 

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#20510]
It seems like when iterating over a dataset returned by `iter_epochs`, the batch format is always a Pandas dataframe, and not the native format.

This behavior is different when iterating over a regular ray dataset or a dataset returned by `iter_datasets`.

```python
import ray
import pandas as pd

# Regular dataset
dataset = ray.data.range(5)
next_iter_batch = next(dataset.iter_batches())
assert type(next_iter_batch) == list

# Dataset returned by iter_epochs
dataset = ray.data.range(5).repeat()
next_epoch_iter_batch = next(next(dataset.iter_epochs()).iter_batches())
assert type(next_epoch_iter_batch) == pd.DataFrame

# Dataset returned by iter_datasets
dataset = ray.data.range(5).repeat()
next_dataset_iter_batch = next(next(dataset.iter_datasets()).iter_batches())
assert type(next_dataset_iter_batch) == list
```

**Comment by ericl** [comment]
I think this is because the default value of `batch_format = "pandas"` in `class DatasetPipeline`. How about we change it to "pandas" for both Dataset and DatasetPipeline?

**Comment by amogkam** [comment]
@ericl why not make it "native" for both?

**Comment by ericl** [comment]
I don't have a strong opinion, but it seems "pandas" is more usable by default. Arrow tables are pretty hard to work with and most people end up converting it to pandas anyways.

**Comment by amogkam** [comment]
Got it.

Just my 2c- for a simple dataset like `ray.data.from_range` I would prefer working with python lists than pandas dataframes.
