### ISSUE TITLE
[Bug] e2e.py doesn't work on m1

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#20511]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

This may be a symptom of other more significant platform specific issue, thus this tracking bug.
If you try running e2e.py to launch any CI test, you see the following trace stack:

'''
(main) jungong:~/ray$ ANYSCALE_HOST=https://beta.anyscale.com ANYSCALE_CLI_TOKEN=<token> ANYSCALE_PROJECT=<proj> python release/e2e.py --test-config release/rllib_tests/rllib_tests.yaml --test-name=learning_tests
Cloning into '/var/folders/9d/p2w617vn5658ttkgqwm09w9m0000gn/T/tmpk41wb9bq'...
remote: Enumerating objects: 11230, done.
remote: Counting objects: 100% (254/254), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 11230 (delta 4), reused 237 (delta 2), pack-reused 10976
Receiving objects: 100% (11230/11230), 5.32 MiB | 13.69 MiB/s, done.
Resolving deltas: 100% (21/21), done.
[INFO 2021-11-17 15:06:16,947] e2e.py: 466  Latest 10 commits for branch master: ['1cadd61917f8f350f51d10b27c8f71f9cf1d49e6', '56619b955e627d044bd948c38c14816c3a00052a', '724a140795ca9869359ca1d554abf48324eb1d92', '03aec4e04aefa3afa6be8614bcdbb492e120cafa', 'd1c624901f7ddf4af95e8fc8bbd4f166b2f78d70', '3d668768dee031bf24872b9d4f81baafff92e84f', 'e01f14d7df559a8fb8ba4f1b611fe688600c4e06', 'dba84546d9b5cb6323fc5abe04c762bde2295d5a', '18d605fa7c224e59a60f81928c50a437a6b8dcec', '454db6902c718efd3ab8a78b0c5e86bc89b1ddbf']
[INFO 2021-11-17 15:06:17,154] e2e.py: 472  Found wheels URL for Ray 2.0.0.dev0, branch master: https://s3-us-west-2.amazonaws.com/ray-wheels/master/1cadd61917f8f350f51d10b27c8f71f9cf1d49e6/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
[INFO 2021-11-17 15:06:17,183] e2e.py: 1881  Link to project: https://beta.anyscale.com/o/anyscale-internal/projects/prj_yfgD2xrBjDTKnvsJrZUHxtKZ/?tab=session-list
[INFO 2021-11-17 15:06:17,183] e2e.py: 1888  This will now run test learning_tests.
[INFO 2021-11-17 15:06:17,183] e2e.py: 1890  Starting process with timeout 14400 (prepare timeout 14400, build timeout 1800)
Traceback (most recent call last):
  File "release/e2e.py", line 2214, in <module>
    run_test(
  File "release/e2e.py", line 2030, in run_test
    result = run_test_config(
  File "release/e2e.py", line 1893, in run_test_config
    process.start()
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'run_test_config.<locals>._run'
'''

Seems like it has trouble picking the _run function.

### Versions / Dependencies

master

### Reproduction script

See description

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
still valid issue

**Comment by pcmoritz** [comment]
We could change the documentation for Ray on M1 and recommend people to run a x86_64 version of python, then there will be no problems with grpc and everything will just work. That's how I set up the Anyscale end-to-end tests now and it seems to be working well. It is also the recommendation from gRPC (https://groups.google.com/g/grpc-io/c/9iM4SPpOyC8). Rosetta will take care of the emulation and I think it is fast enough (but we should check).

We can leave the current instructions and wheels for people who want to run natively on M1, and then switch over when gRPC releases wheels. What do you think? Or we keep the current instructions as the recommendation and add the x86_64 version as an alternative.

**Comment by gjoliver** [comment]
it seems like a library would need to be compile under this dual arch mode to be able to run on both platforms.
I am not sure ... kinda feel like even if the universal python runs fine, there will be dependent x86 builds that won't run on M1?

also, this specific problem seems to be pickle related. like we are not able to pick the _run() function for remote running on M1 somehow.

**Comment by pcmoritz** [comment]
Actually x86_64 Python will just only use x86_64 wheels and libraries, at least that's my experience and nothing needs to be specially compiled. It's pretty magic and kudos to apple for making it work. I think this option is worth at least mentioning in the docs -- it will also make sure all the wheels work that are only compiled for x86_64 and not arm64.

**Comment by gjoliver** [comment]
what, really? 🤯 
let me test a bit and report back.
