### ISSUE TITLE
[Bug] OwnerDiedError when a task worker is reused as an actor

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#20554]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

This bug happens when a worker creates an ObjectRef while executing a task, then later gets reused as an actor. If the actor goes out of scope, Ray force-kills the process without waiting for any owned ObjectRefs to drain. Later, this will trigger an `OwnerDiedError` if another process tries to get the ObjectRef because the object's owner has been killed.

### Versions / Dependencies

Ray 2.0dev

### Reproduction script

```python
import ray
import numpy as np


@ray.remote
def create_ref():
    ref = ray.put(np.zeros(100_000_000))
    return ref

@ray.remote
class Actor:
    def __init__(self):
        return

    def foo(self):
        return

ray.init(num_cpus=1, object_store_memory=1000_000_000)  # 1 CPU so we only start 1 worker.
wrapped_ref = create_ref.remote()
print(ray.get(ray.get(wrapped_ref)))

# create_ref worker gets reused as an actor.
a = Actor.remote()
ray.get(a.foo.remote())
# Actor will get force-killed.
del a

# Flush the object store.
for _ in range(10):
    ray.put(np.zeros(100_000_000))

# Object has been evicted and owner has died. Throws OwnerDiedError.
print(ray.get(ray.get(wrapped_ref)))
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment]
@ericl, this bug is related to the "context" thing we were discussing about tracking when ObjectRefs were created.

**Comment by ericl** [comment]
Hmm what are some ways we could fix this? What if workers owning objects are not eligible for being converted into an actor?

**Comment by stephanie-wang** [comment]
Yeah, so I think we could:
1. Not reuse workers for actors, either in general or if they own objects.
2. Drain actors on force-kill if they own objects from a previous task. I think this one is not as good because the actor may have state that we want to clean up.

**Comment by ericl** [comment]
Right, I think the second option isn't workable since actors often have GPU
state that requires killing the process to clean up.
