### ISSUE TITLE
[xray] Actors failing (placeholder title)

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2060]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: (personal branch)
- **Python version**: 2.7
- **Exact command to reproduce**: run code below

### Describe the problem
The following fails on TWO nodes with this error:

```
Traceback (most recent call last):
  File "example.py", line 20, in <module>
    result = ray.get([a.method.remote() for a in actors])
  File "/home/ubuntu/ray/python/ray/worker.py", line 2423, in get
    values = worker.get_object(object_ids)
  File "/home/ubuntu/ray/python/ray/worker.py", line 483, in get_object
    i + ray._config.worker_fetch_request_size())])
  File "plasma.pyx", line 558, in pyarrow.plasma.PlasmaClient.fetch
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Broken pipe
```

### Source code / logs

```
import ray
import time

@ray.remote(num_cpus=2)
class Test(object):
    def set(self, val):
        time.sleep(5)
        self.val = val

    def method(self):
        return 1

    def get(self):
        return self.val


ray.init(redirect_output=False, redis_address="localhost:6379", use_raylet=True)
actors = [Test.remote() for i in range(20)]
[a.set.remote(v) for a, v in zip(actors, range(20))]
result = ray.get([a.method.remote() for a in actors])
result = ray.get([a.get.remote() for a in actors])
print(result)
```

**Comment by stephanie-wang** [comment]
Can you recreate this error with two raylets running locally, using `ray.worker._init(num_local_schedulers=2, start_ray_local=True, ...)`?

Also, it looks like a raylet might be crashing. Is there any error output from the raylet processes?

**Comment by richardliaw** [comment]
OK right now I've rebased the fetch code onto master (https://github.com/richardliaw/ray/tree/xrayfetch3) and I'll do the following:
on this branch - 
1. Getting this code snippet to error
2. Getting this code snippet to error locally (if 1)
3. Getting raylet error outputs  (if 2)

**Comment by richardliaw** [comment]
Looks like this doesn't fail on master.
