### ISSUE TITLE
[Bug] [Core][Autoscaler] Stuck downscaling worker nodes, don't know why GCS thinks they're still running

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#20615]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Autoscaler

### What happened + What you expected to happen

With a similar cluster setup as in
https://github.com/ray-project/ray/issues/20614,
I got stuck with a few workers that refused to time out.

I manually extracted load metrics by initializing a Monitor object in a Python shell and saw that the last used time for each 
worker was essentially now. I'm unaware of any tasks, actors, or drivers running in the cluster. 

I probably won't be able to reproduce this, but it would be good to improve debug-ability of such issues.

Expected behavior: User should have easy access to information explaining what's running on nodes and why they won't time out.

### Versions / Dependencies

Ray master

### Reproduction script

Launch a cluster, do some stuff, stop doing stuff. Check ray.state.actors and ray status to see if it looks like things are idle. Get surprised that stuff doesn't shut down. 

### Anything else

Just saw it once.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
+ 1 on observability.

**Comment by hora-anyscale** [comment]
Per Triage sync: closing as it was fixed.

cc: @ericl

**Comment by DmitriGekhtman** [comment]
I agree with closing this because there isn't a concrete actionable issue to fix.

However, users still run into issues of this nature (why doesn't my cluster scale down?) on a regular basis.
