### ISSUE TITLE
[Bug] Pid=None after running multiple jobs

### ISSUE THREAD

**Issue by CavalloneChen** [ray-project/ray#20612]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have one python script written with ray. There are one actor class and multiple task functions in that script, and gpus are used. When I run my script with different parameters, the first to the third jobs would generate logging information normally and they all have their corresponding pid printed. However, when more jobs are started with the same script, the later jobs will all have pid=None, and their logging output will spam all running shells, which is very annoying.

### Versions / Dependencies

ray                       1.8.0                    pypi_0    pypi
ray-cpp                   1.8.0                    pypi_0    pypi

### Reproduction script

I'm sorry I can't provide a reproduction script as it is quite private.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Is it possible to provide the mock script and instruction regarding how I should run them? I've seen some users who saw the same issue, and it'd be a great chance to get fix it.
