### ISSUE TITLE
[Train] Run release tests with NCCL

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#20658]
Make sure to set NCCL_SOCKET_IFNAME env var to "ens3"

**Comment by matthewdeng** [comment]
For additional context, the problem occurs with PyTorch 1.9.0 & NCCL 2.7.8 and specifically seems to be problematic with the `veth` device. The hardware used by the tests are currently using `ens3`, but similar changes could be made to support `ensX` or `ethX` interfaces.
