### ISSUE TITLE
[Bug] Job submission seems to leak bash processes

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#20659]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

repeatedly do 

```
ray job submit -- "python -c 'print(123); import time; time.sleep(5)'"
```

And ctrl+c them. We seem to have high # of hanging bash processes left.

<img width="1950" alt="Screen Shot 2021-11-22 at 7 22 49 PM" src="https://user-images.githubusercontent.com/6372689/142966921-e4a7c07a-27cb-4765-8663-8af3b6174033.png">

### Versions / Dependencies

on master

### Reproduction script

repeatedly do 

```
ray job submit -- "python -c 'print(123); import time; time.sleep(5)'"
```

And ctrl+c them. We seem to have high # of hanging bash processes left.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jiaodong** [comment]
After `killall -9 bash` and repeatedly submit & interrupt job submission again, this issue seems not reproducible again. It could be other actions i took locally, will leave it open for now.

**Comment by edoakes** [comment]
Haven't been able to reproduce.
