### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by shahar-fleischman** [ray-project/ray#20667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Hi,
I have 2 requests:
1. I would like to do log rotation for logs in ray log dir(monitor,dashboard, and all other ever growing files) right now if you rotate the log, the dashboard process keeps writing to the old file, and is not using the new file, it also does not support kill -HUP for reloading.
2. change ray log location from the default /tmp/ray.

Thanks.

### Use case

Run ray without the need to restart the whole cluster after deleting the files.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Which files are problems now? We currently have log rotation for most of files, I think except the worker logs.

**Comment by shahar-fleischman** [comment]
Dashboard & monitor
Is there a place I can see the settings for log rotation in ray documentation ?
Can I move ray log location from /tmp ?
