### ISSUE TITLE
[Bug] Prometheus Metrics Exporting not working

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#20665]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I launched Ray successfully with a metrics export port, but then that port is unreachable. Tried the same thing on macOS and it works.

```bash
> ray start --head --metrics-export-port=8080
Local node IP: 10.10.0.4

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='10.10.0.4:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
> telnet localhost 8080
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

### Versions / Dependencies

- Problem exists on both the latest stable (1.8.0) and nightly master
- Problem only exists on Linux (Ubuntu 20.04); does not happen on macOS

### Reproduction script

see above

### Anything else

Happens every time now

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jaimehrubiks** [comment]
Is the metrics server just not working? I'm running just in regular app mode, and this won't expose the port ray.init(_metrics_export_port=6000)

**Comment by jon-chuang** [comment]
I am not able to repro with latest master.

Could you show your `sudo ss -ltn` to see which ports are open?

**Comment by jaimehrubiks** [comment]
I remove the message I sent because I found my issue. I was missing this "pip install ray[default]" , did not have the [default] part. That helped me.

**Comment by jon-chuang** [comment]
I confirmed that if another process is using that port, Ray does not send any error message, and this fails silently. 

@rkooo567 I think we should fix this by having ray at least report that the port is used by another process and say that it will not be able to export metrics? Or should the behaviour be to fail to start?

**Comment by rkooo567** [comment]
Hmm we should have code to raise exception if it uses the port that will be used by other procs

seems like the main root cause is it doesn’t work with minimal ray (expected, but that is not surfaced to users). @jon-chuang would you be interested in fixing it?

**Comment by jon-chuang** [comment]
@rkooo567 Turns out that code is not used for metrics_export_port. Could you point out where this code is for other ports? The issue is the prometheus_client has its own code path for consuming ports.
