### ISSUE TITLE
[Serve][Blog] Code still mentioned create_backend.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#20675]
https://www.anyscale.com/blog/ray-and-mlflow-taking-distributed-machine-learning-applications-to

Trying to create a backend seems to have a different signature now:
client.create_backend("mlflow_backend", MLFlowBackend, model_uri)
-> AttributeError: 'Client' object has no attribute 'create_backend'

**Comment by simon-mo** [comment]
@architkulkarni ping on this? thanks

**Comment by architkulkarni** [comment]
Sorry, I haven't worked on this yet but I will get to it this sprint.  I just need to update the blog to use the Serve Deployments API.

**Comment by architkulkarni** [comment]
Still valid, deprioritizing to P2 because the blog is old and the Serve+Mlflow integration has very low usage
