### ISSUE TITLE
[Ray 1.8] "ray memory" fails with "No module named 'aiohttp.signals'"

### ISSUE THREAD

**Issue by Metalcycling** [ray-project/ray#20681]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Hi Ray team,

I can run most `ray` commands like `ray status` and `ray timeline` but when I try `ray memory` I get the following error:

```
Traceback (most recent call last):
  File "/home/metalcycling/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/metalcycling/.local/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1969, in main
    return cli()
 ...
  File "/home/metalcycling/.local/lib/python3.8/site-packages/ray/dashboard/optional_deps.py", line 8, in <module>
    import aiohttp.signals
ModuleNotFoundError: No module named 'aiohttp.signals'
```

I manually imported the code on my Python shell and while `import aiohttp` works, `import aiohttp.signals` doesn't work. On the aio-libs page somebody reported the same issue [here](https://github.com/aio-libs/aiohttp/issues/6250), so this is a problem on their side, really. But it seems they are not following their own deprecation process and that means the signals module is not available. Is there a way to fix Ray so I can use the memory utility?

Thanks,
Pedro

### Versions / Dependencies

```
metalcycling@linux:~$ python3 --version
Python 3.8.8
```

```
>>> import aiohttp
>>> aiohttp.__version__
'3.8.1'
>>> 
```

```
>>> import ray
>>> ray.__version__
'1.8.0'
>>>
```

### Reproduction script

```
metalcycling@linux:~$ ray memory
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TheFizzWare** [comment]
Also having this issue but for doing 
```python
ray.init(include_dashboard=True)
```
which eventually trips this `raise ImportError(...` on line 1204
```python
1199:        # Make sure the process can start.
1200:        try:
1201:            import ray.dashboard.optional_deps  # noqa: F401
1202:        except ImportError:
1203:            if require_dashboard:
1204:                raise ImportError(DASHBOARD_DEPENDENCY_ERROR_MESSAGE)
1205:            else:
1206:                return None, None
```

... Meanwhile, doing `pip install -U 'ray[default]'` only results in `Requirement already satisfied: ...`.

**Comment by TheFizzWare** [comment]
It appears that the issue also involves any
```python
import aiohttp.frozenlist
```
That was discovered by commenting out the `import aiohttp.signals` line from ray's `optional_deps.py`, trying the import again, and getting the same `ModuleNotFoundError` for `aiohttp.frozenlist` instead of `aiohttp.signals`.

I was able to `ray.dashboard.optional_deps` after commenting those two import lines in `optional_deps.py`, and have moved on to debugging other issues in starting the dashboard. I'm not yet sure that commenting out those dependencies is enough to bypass the issue for now.

**Comment by pcmoritz** [comment]
This is a known problem that is fixed in master in https://github.com/ray-project/ray/pull/20261.

In the current release you can pin `aiohttp` by running `pip install aiohttp==3.7` which will fix it.

**Comment by TheFizzWare** [comment]
@pcmoritz Thank you, worked exactly as you said it did.

**Comment by carlogrisetti** [comment]
`pip install "aiohttp>=3.7,<3.8"` is a better way to address this, since it will include any fixes that will be released

**Comment by scv119** [comment]
@ericl looks this is fixed?

**Comment by 2726651506** [comment]
pip install aiohttp==3.7.4
