### ISSUE TITLE
[Bug] Ray 1.8.0 [Default] does not contain dashboard when installing with pip3 on ubuntu server

### ISSUE THREAD

**Issue by JNMGR14** [ray-project/ray#20702]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I installed ray using
"`pip3 install ray [default]`"

But it shows me the following error that I show in the image, the first ray installation was using the sentence that I show in quotes but it still throws me an error that indicates "Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray [default]`. "

This even though I have used ray [default] and also decided to use "`sudo pip3 install ray [default]`"

But nothing works and I really need the dashboard

![image](https://user-images.githubusercontent.com/71668190/143253027-1d191d2e-a6e5-4438-a2bd-a2361af1a94a.png)

### Versions / Dependencies

Ray 1.8.0 [Default]

### Reproduction script

`ray start --head --port=10000 --include-dashboard=true --dashboard-host=192.168.1.215 --dashboard-port=7777 --num-cpus=16`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
What happens if you try pip install -U “ray[default]”?

**Comment by JNMGR14** [comment]
I tried it with

```
"pip3 install -U ray [default]"

"pip3 --upgrade --force-reinstall ray[default]"

"pip3 --upgrade --force-reinstall --no-cache-dir ray[default]"
```

**Comment by JNMGR14** [comment]
And answering your question

It actually installs everything normally and when trying to run the statement `"ray start --head --port = 10000 --include-dashboard = true --dashboard-host = 192.168.1.215 --dashboard-port = 7777 --num-cpus = 16 "` and the error occurs again

**Comment by rkooo567** [comment]
What about uninstall and reinstalling again?

**Comment by rkooo567** [comment]
Any logs from dashboard.log?

**Comment by rkooo567** [comment]
It is in /tmp/ray/session_latest/logs normally

**Comment by JNMGR14** [comment]
![image](https://user-images.githubusercontent.com/71668190/143283581-33bf7cfc-197d-4840-859a-5d6ad360e284.png)

**Comment by pcmoritz** [comment]
This is probably the same issue as https://github.com/ray-project/ray/issues/20681, can you try the fix recommended there?

**Comment by hckuo** [comment]
I ran into a similar issue. I realized that `npm run build` failed. I solved it by rebuilding the dashboard client:
```
cd ray/dashboard/client
export NODE_OPTIONS=--openssl-legacy-provider
npm run build
```

**Comment by 2726651506** [comment]
pip install aiohttp==3.7.4 you can solve this issue

**Comment by KastanDay** [comment]
I didn't realize that `pip install ray` != `pip install "ray[default]"` 

The `"ray[default]" version includes necessary dependencies for things like Ray's Dashboard. Try installing that, which is okay to do on top of a regular install, because it just adds more dependencies. Good luck!
