### ISSUE TITLE
[Bug] Placement group Prepare/Commit needs to batched per node.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#20715]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Currently, when the placement group is prepared/committed/removed, we are sending a separate RPC per bundle.

This is bad because

1. The performance can be impacted when you have many bundles in a single node. (It is quite common). Also could be related to https://github.com/ray-project/ray/issues/20243
2. It is more likely to have race condition. Since newly created resources can be used between each bundle creation. e.g., Node A will have bundle B and C. It is possible bundle B is used before C is created. This is currently handled correctly, but it can be more vulnerable to race condition in the future change.

Ideally, we should batch bundle requests per node instead of per bundle. This will help us solving two issues.

1. will be better because we can reduce # of RPCs and resource update logic (Each bundle creation requires to iterate all resources now).
2. will be better because we prepare & commit all resources at the same time. There's no worry about any sort of timing problem.

### Versions / Dependencies

master

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @clay4444 do you have bandwidth to take this?

**Comment by clay4444** [comment]
> 

yeah, I will check this~
