### ISSUE TITLE
[Bug] Check failed: core_worker_process causes Actor to crash

### ISSUE THREAD

**Issue by Seanny123** [ray-project/ray#20736]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

As described in [my Discourse post](https://discuss.ray.io/t/multi-stage-pipeline-using-ray/4266?u=seanny123), I'm currently trying to run a multi-stage Ray pipeline with fan-out using Ray Actors + Queues. To setup the computation, I create large (+100) amounts of actors. When initializing these actors, I get this error:

```
[2021-11-26 00:18:28,227 C 74884 75529] core_worker.cc:194:  Check failed: core_worker_process The core worker process is not initialized yet or already shutdown.
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::CoreWorkerProcess::EnsureInitialized()
    ray::core::CoreWorkerProcess::GetCoreWorker()
    __pyx_pw_3ray_7_raylet_10CoreWorker_23get_worker_id()
```

I do not know how to interpret this error, but it seems to cause the actor to crash according to the dashboard, which harms the scalability of my workflow.

### Versions / Dependencies

Ray = 1.8.0
Python = 3.9
OS = Fedora 34

### Reproduction script

```python
import ray
import time
from ray.util.queue import Queue

num_queue = Queue()
str_queue = Queue()
out_queue = Queue()

n_work = 100
n_mult = 10


@ray.remote
def append_a(get_queue: Queue, put_queue: Queue):
    while num := get_queue.get(block=True):
        time.sleep(1)
        put_queue.put(f"{num}a")


@ray.remote
def append_b(get_queue: Queue, put_queue: Queue):
    while num_str := get_queue.get(block=True):
        time.sleep(1)
        for i in range(n_mult):
            put_queue.put(f"{num_str}{i}b")


# create many workers for each stage
for _ in range(10):
    append_a.remote(num_queue, str_queue)
for _ in range (100):
    append_b.remote(str_queue, out_queue)


# submit to queue
for i in range(n_work):
    num_queue.put(str(i))


# retrieve results
for i in range(n_work*n_mult):
    print(out_queue.get())
```

### Anything else

This occurs most frequently when using a Ray Cluster depolyed on Kubernetes. However, it also occurs (although more rarely) when using a local cluster.

**Comment by JanJF** [comment]
I got the same issue

**Comment by varunjammula** [comment]
+1

**Comment by rkooo567** [comment]
@Seanny123 I failed to actually run the attached script because of some issues

1. := -> should I just use ==?
2. There are some variables that are not defined. Can you fix this?
