### ISSUE TITLE
[Feature] Support for Pytorch-lightning 1.5.0

### ISSUE THREAD

**Issue by jamesbsilva** [ray-project/ray#20741]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

As of Pytorch-lightning 1.5.0

https://github.com/PyTorchLightning/pytorch-lightning/blob/49d09aa28b4bdde7a272c3e77dc3f13613802672/CHANGELOG.md#150---2021-11-02

The property `running_sanity_check` in the `Trainer` class has been deprecated in favor of `sanity_checking` as of 1.5.0 as linked above. This property is used in the following lines which I have been patching to support `1.5.0` 

https://github.com/ray-project/ray/blob/3b77840c1b6daf8d008350460ec4ca7c3df830db/python/ray/tune/integration/pytorch_lightning.py#L177

https://github.com/ray-project/ray/blob/3b77840c1b6daf8d008350460ec4ca7c3df830db/python/ray/tune/integration/pytorch_lightning.py#L231

Is there any plan to support 1.5.0+? I am not sure what the preferences are as far as dealingl with backcompatibility otherwise could submit a PR.

I tried searching about this although from the changelog above the complete deprecation of the property was just released in packages of just a few weeks ago.

### Use case

Support for using the newer versions of pytorch-lightning .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
I believe a similar PR to achieve this is being implemented by the great @kaushikb11? 

 #20562

**Comment by jamesbsilva** [comment]
It looks like that will indeed make this a subset of that functionality. Nice, I cant wait until this is released.

**Comment by amogkam** [comment]
Will keep this open until #20562 is merged

**Comment by dynamicwebpaige** [comment]
Would it make sense to close this issue, given that [#20562](https://github.com/ray-project/ray/pull/20562) is now merged? We might also want to reach out to the [`prob-ml/bliss`](github.com/prob-ml/bliss) team to reintroduce their Ray dependency, as it looks like they might have been blocked on Lightning support.

**Comment by amogkam** [comment]
Yes this can be closed- Ray Tune supports PTL 1.5 as of #20562!
