### ISSUE TITLE
[Feature] Cluster launcher script to run on node (re-)relaunch

### ISSUE THREAD

**Issue by Ivorforce** [ray-project/ray#20758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Today, I had the problem that my head node ran long enough to stop my workers (due to idleness). When I used it again, reactivating the workers after 2 days hibernation, my `docker login` that I run in `initialization_commands` had expired.

Now, I could on initialization set up something like a cronjob that runs the login every x hours to keep me logged in. Please feel free to tell me this is the better solution if you believe so. However, seeing as though login only really needs to be provided when spawning a worker (new or waking from hibernation), that's the only time where I'd ideally run `docker login`.

What do you think?

Another workaround: It's also possible to manually run `ssh ec2-user@xxx "aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin xxx;"` on all workers and re-running `ray up`, eliminating the need to shut it down or set up a cronjob.

### Use case

Establishing connections required for docker setup at respawn (i.e. after waking from hibernation).

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by askainet** [comment]
We are using [Amazon ECR Docker Credential Helper](https://github.com/awslabs/amazon-ecr-credential-helper) to take care of renewing docker credentials automatically when needed.

Try adding this script to your `initialization_commands` (it assumes AWS credentials are already available in your system):

```yaml
initialization_commands:
  - |
    # Setup amazon-ecr-credential-helper to automatically renew docker login credentials for AWS ECR
    wget https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.5.0/linux-amd64/docker-credential-ecr-login
    sudo install -o root -g root -m 0755 docker-credential-ecr-login /usr/local/bin/docker-credential-ecr-login
    mkdir -p $HOME/.docker
    echo '{"credsStore": "ecr-login"}' > $HOME/.docker/config.json
```

**Comment by Ivorforce** [comment]
Thanks for the pointer, this helped. I'm now installing the same software via yum and I think the issue is resolved for me now. Thanks!
