### ISSUE TITLE
[Bug] get_checkpoints_path does not work with tmp dir names

### ISSUE THREAD

**Issue by marcm-ml** [ray-project/ray#20762]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Using [get_checkpoints_paths](https://github.com/ray-project/ray/blob/bf2c5f1417c71ce85e7b377a10be7e1ecdddf750/python/ray/tune/utils/trainable.py#L143-L175) (which is internally used in Analysis objects) fails when a checkpoint dir has irregular names such as `checkpoint_tmpccbce4`. The line in question is https://github.com/ray-project/ray/blob/bf2c5f1417c71ce85e7b377a10be7e1ecdddf750/python/ray/tune/utils/trainable.py#L170
Checkpoint names like these can happen if tune restores trials for example. Sometimes these checkpoints stay and cause this error. Also, I consider it bad design inferring the checkpoint iteration from the checkpoint name as nothing stops the user from passing anything else than an int as step (which becomes part of the checkpoint name) in `tune.checkpoint_dir(step="blabla")`

### Versions / Dependencies

latest ray
windows10

### Reproduction script

None as it requires functional tune directory. Just change the name of the checkpoint to anything else than integer and it fails.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
I agree, the checkpoint iter should be inferred from the tune metadata. Thanks for raising this

**Comment by Nesqulck** [comment]
Agreed. Usually they get deleted as soon as the next checkpoint comes available. However, I noticed that this does not happen reliably but needs more investigation. Are there flags in the metadata to distinguish between tmp and normal? If so, the Analysis object can disregard those checkpoints, possibly in TrainableUtil.get_checkpoint_paths()
