### ISSUE TITLE
[Bug][Serve] Documentation code didn't seem to work for FastAPI

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#20768]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

Our documentation example https://docs.ray.io/en/latest/serve/http-servehandle.html#fastapi-http-deployments didn't work for new users using FastAPI.

### Versions / Dependencies

on master

### Reproduction script

```
import ray
from fastapi import FastAPI
from ray import serve
app = FastAPI()
ray.init(address="auto", namespace="summarizer")
serve.start(detached=True)
@app.get("/")
def f():
    return "Hello from the root!"
# ... add more routes, routers, etc. to `app` ...
@serve.deployment(route_prefix="/")
@serve.ingress(app)
class FastAPIWrapper:
    pass
```

Path '/' not found. Please ping http://.../-/routes for route table.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by batman-do** [comment]
@jiaodong how to fix that, i have same error :((

**Comment by edoakes** [comment]
@batman-do could you post the code you are using and what error you got?

**Comment by drewm23** [comment]
Try adding this at the end of your code

``python
serve.run(Summarizer.bind())
``
