### ISSUE TITLE
[Feature] Run the test nightly instead of weekly

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#20770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Some tests which are not expensive are running weekly. We should consider converting them to nightly tests.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
This is done!
