### ISSUE TITLE
[core][nighlyt-test] object-store is failing  

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20795]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

object_store is failing benchmark/nightly tests https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_qSSkfmdtkA4FN8L51eQKF7ax

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
cc @rkooo567 do you have context here?

**Comment by rkooo567** [comment]
I think this is fixed in the master? by this PR https://github.com/ray-project/ray/pull/20739

**Comment by rkooo567** [comment]
Confirm it is fixed.
