### ISSUE TITLE
[Feature] Support strawberry-graphql in serve with FastAPI

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#20805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

User tried to use GraphQL + FastAPI but ran into serialization error: https://discuss.ray.io/t/fastapi-and-graphql/4300

Looks like we're not supporting it well and based on docs on fastapi - https://fastapi.tiangolo.com/advanced/graphql/ the only supported alternative is to use Starlette based graphql instead, which serve supports Starlette.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by austinnichols101** [comment]
In the following link there is mention of a `one pager` regarding graphql + force serialization.  Is this document available somewhere?  Thanks!

`https://discuss.ray.io/t/fastapi-and-graphql/4300/3`

> [jiaodong](https://discuss.ray.io/u/jiaodong)
[Dec '21](https://discuss.ray.io/t/fastapi-and-graphql/4300/4)
Thanks for trying out on this, I think you’ve uncovered a pattern that other uses might run into as well about serialization. We force serializing fastapi app but it seems like blocking use cases like yours.
> 
> The good news is, it’s possible to avoid serializing it to get rid of this class of failure. [@simon-mo](https://discuss.ray.io/u/simon-mo) is working on a one pager for this.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @simon-mo are you aware of a one-pager covering this?

cc: @sihanwang41

**Comment by simon-mo** [comment]
Kind off. The alternative approach is essentially perform a import from the class, by passing Serve's serialization stack. 

```python
@serve.deployment
class MyAPP
    def __init__(self):
        from my_module import app_with_graphql
        self.app = app_with_graphql

    async def __call__(self, request: starlette.requests.Request):
        # NOTE(simon): This is now duplicated from ASGIAppWrapper because we need to
        # generate FastAPI on the fly, we should find a way to unify the two.
        sender = ASGIHTTPSender()
        await self.app(request.scope, receive=request.receive, send=sender)
        return sender.build_asgi_response()
```
