### ISSUE TITLE
[Bug] Numpy vs Bytes ray.get() Performance Gap

### ISSUE THREAD

**Issue by NathanTP** [ray-project/ray#20801]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

bytes objects are much slower than numpy objects when storing/loading through ray.put/get. The test script below shows it clearly, but the basic setup is: pass either a bytes object or numpy object of the same size (e.g. 4MiB) to a remote actor and time how long it takes to ray.get the object twice.  The numpy version is ~2x faster than the bytes for the first ray.get. The second ray.get is much faster than the first for numpy, but not significantly faster for bytes.

I would expect both versions to behave similarly (or perhaps a bit better for bytes). Particularly since serializing/deserializing them with ray.cloudpickle has similar performance (bytes are slightly faster than np).

### Versions / Dependencies

Python 3.8
ray nightly (Nov 30 2021)
OS: Centos7 and Ubuntu 20.04

### Reproduction script

```
import ray
import numpy as np
import time

ray.init()


@ray.remote
class testActor():
    def test(self, refs):
        start = time.time()
        ray.get(refs)
        print("first took: ", time.time() - start)

        start = time.time()
        ray.get(refs)
        print("second took: ", time.time() - start)


act = testActor.remote()

# This behaves well (second fetch is ~5x faster)
a = np.ones(1024**2, dtype=np.int32)
print("4MiB Numpy")
aRef = ray.put(a)
act.test.remote([aRef])

# These behave poorly
#   * First fetch is ~2x slower than the numpy version
#   * second fetch is only ~1.2x faster
# a = np.ones(1024**2, dtype=np.int32).data.cast('B')
a = bytes([1]*(4*1024*1024))
print("4MiB bytes")
aRef = ray.put(a)
act.test.remote([aRef])

# Bytes and NP perform similarly when serializing/deserializing
start = time.time()
aNpSer = ray.cloudpickle.dumps(aNp)
aNpDes = ray.cloudpickle.loads(aNpSer)
print("Serialize aNP: ", time.time() - start)

start = time.time()
aBytesSer = ray.cloudpickle.dumps(aBytes)
aBytesDes = ray.cloudpickle.loads(aBytesSer)
print("Serialize aBytes: ", time.time() - start)
```

### Anything else

This issue is deterministic across machines and ray versions (I've tried 1.6, 1.8, and 2.0dev). I've only tested on a single node.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I think bytes are probably not supported by zero-copy whereas numpy is. 

If zero copy is not supported, when you call ray.get, there's additional overhead to copy the value into the process memory. 

https://docs.ray.io/en/master/serialization.html#numpy-arrays

**Comment by scv119** [comment]
@NathanTP as @rkooo567 suggested, Ray is optimized fro numpy where put yields fewer copies under the hood. Closing it for now but let's know if you have more questions.
