### ISSUE TITLE
[Feature] Support to run Ray worker container in a rootless container

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#20820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Now we can start Ray process in an isolated container, but `root` is required. It is unfortunate.

We need to run Ray worker rootless container. In Ray worker scenarios, what we need is an isolated rootfs and some cgroup configs.

### rootfs
We can reuse container image, and use overlay to create a new rootfs. 

In Ubuntu Distro (linux kernel 5.0+), we can mount a overlayfs in unprivileged user-ns. But other distro like centos/fedora not support it now.

### cgroup

For cgroupv2, a unprivileged can create his sub cgroup.### 

### Use case

In a multi-tenant Ray cluster, each job may require different libraries and runtime. And immutable infrastructure can help users to deploy their job easily. 

The container image provide an isolated filesystem and it is immutable. In most scenarios, Ray run without privilege, so it can't create normal container like Docker.

We need to support run worker in a slim container.

### Related issues

https://github.com/ray-project/ray/issues/14077

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by chenk008** [comment]
[Fuse-overlayfs](https://github.com/containers/fuse-overlayfs) is an implementation of overlay+shiftfs in FUSE for rootless containers, it can help to workaround this rootfs issue on non-debian based distros.

**Comment by peterghaddad** [comment]
Can we re-open this issue?
