### ISSUE TITLE
Remove deprecated autoscaler fields [Bug][autoscaler] Retire deprecated autoscaler fields

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#20837]
Deprecated fields like "initial_workers, target_utilization_fraction, autoscaling mode, worker_nodes, head_node` need to be officially retired at this point (we should raise an error if these fields are present).
Anecdotally, some of these fields no longer work well. There's not much interest maintaining them.

**Comment by wuisawesome** [comment]
Let's do this with ray 2.0

**Comment by jjyao** [comment]
@DmitriGekhtman @wuisawesome it's time to remove those fields :) Could someone do it?

**Comment by DmitriGekhtman** [comment]
I'll leave it to @AmeerHajAli to assign the item.

My two cents on the implementation is to do this in as lightweight a way as possible:
- Identify the fields that must be removed (at least the ones I listed above)
- Add a validation step **at the very start** of the Ray up sequence which checks for the forbidden fields and aborts with an error if the fields are present.

**Comment by jjyao** [comment]
Ideally we want this to be done by 07/15 (before the 2.0 branch cut).

**Comment by AmeerHajAli** [comment]
@wuisawesome , can you make a PR for this?

**Comment by wuisawesome** [comment]
It sounds like the urgency is now higher here with the branch cut approaching. Assuming we agree this is a p0 release blocker, I'll take it on

**Comment by scv119** [comment]
Any update on this one? @wuisawesome

**Comment by wuisawesome** [comment]
i'm aiming to get a PR out today.

**Comment by wuisawesome** [comment]
Realizing there's a lot more configs to manually edit, and tests to manually run than i thought. new eta is end of today (i should be working on it all day today).

**Comment by DmitriGekhtman** [comment]
Autoscaling config editing is a swamp, I know.

Tip, in case you're not already thinking along these lines -- if possible, make as few internal changes as possible -- just raise an Exception at the very surface entrypoint if anything any of the deprecated fields are present.

In particular, test_autoscaler.py uses deprecated fields extensively -- if possible, don't bother fixing that right now.

**Comment by scv119** [comment]
> My two cents on the implementation is to do this in as lightweight a way as possible:
> 
> Identify the fields that must be removed (at least the ones I listed above)
> Add a validation step at the very start of the Ray up sequence which checks for the forbidden fields and aborts with an error if the fields are present.


How hard would it be to build a tool that generate a new yaml from the old one? Looks current behavior is a bit abruptive.

**Comment by wuisawesome** [comment]
Reopening for tracking until we unrevert on the release branch.

**Comment by matthewdeng** [comment]
Hey @wuisawesome what's the status of this?

**Comment by wuisawesome** [comment]
cherry-pick should be ready

**Comment by wuisawesome** [comment]
re-picked, closing (again)
