### ISSUE TITLE
[Bug] _resolve_paths_and_filesystem func in file_based_datasource.py

### ISSUE THREAD

**Issue by chaomengyuan** [ray-project/ray#20834]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

In `prepare_read()`, when two hdfs file paths (hdfs://netloc/path1, hdfs://netloc/path2) are passed into `_resolve_paths_and_filesystem()`. The first one is parsed into "path1" and the second one is parsed into "netloc/path2". Then, when calling `_expand_paths()` in the next step, there is no issue with "path1" but an "FileNotFoundError: netloc/path2" will show up.

### Versions / Dependencies

ray 2.0.0.dev0
python 3.7
OS Debian 10

### Reproduction script

import ray

json_files=["hdfs://netloc/path1", "hdfs://netloc/path2"]
ray.data.read_api.read_json(json_files)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@chaomengyuan I think this is because you're missing a few quotations marks here: `["hdfs://netloc/path1, hdfs://netloc/path2"]`. This is a single long string instead of two strings. When using `["hdfs://netloc/path1", "hdfs://netloc/path2"]` instead, the JSON read works as expected for me.

**Comment by chaomengyuan** [comment]
@clarkzinzow Sorry for the typo and I updated the issue. The problem comes from this line: https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/file_based_datasource.py#L450. I need to change it to `return parsed.path` instead of 'return parsed.netloc + parsed.path' to work in our inner environment. Otherwise, it will try to find the path "netloc/path2" under "hdfs://netloc" directory instead of "hdfs://" and throws an  "FileNotFoundError".

**Comment by clarkzinzow** [comment]
@chaomengyuan I haven't been able to reproduce this with the list of two strings, `["hdfs://netloc/path1", "hdfs://netloc/path2"]`, but I was able to reproduce it using the accidental list of a single string, `["hdfs://netloc/path1, hdfs://netloc/path2"]`. Have you confirmed that you can reproduce this with the fixed reproduction?

**Comment by chaomengyuan** [comment]
@clarkzinzow Yes, I confirmed that, at least in our inner HDFS. As I mentioned in the last message, for the second path, it throws an error saying "netloc/path2" is not available. But after I change this line: https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/file_based_datasource.py#L450 to just returning the "path", it works.

**Comment by clarkzinzow** [comment]
@chaomengyuan Ok thank you! I'll keep trying to reproduce it on my end.
