### ISSUE TITLE
[Bug] training stuck in PENDING status

### ISSUE THREAD

**Issue by KyunghyunLee** [ray-project/ray#20847]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I just run the example to train IMPALA in atari environments using `rl-experiments`.
It sticks forever in PENDING status.

```
rllib train -f atari-impala/atari-impala.yaml
```

== Status ==
Current time: 2021-12-02 17:21:50 (running for 00:03:10.22)
Memory usage on this node: 8.3/125.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/32 CPUs, 0/2 GPUs, 0.0/75.41 GiB heap, 0.0/36.31 GiB objects (0.0/1.0 accelerator_type:RTX)
Result logdir: /home/lkh/ray_results/atari-impala
Number of trials: 4/4 (4 PENDING)
+------------------------------------------------+----------+-------+-----------------------------+
| Trial name                                     | status   | loc   | env                         |
|------------------------------------------------+----------+-------+-----------------------------|
| IMPALA_BreakoutNoFrameskip-v4_74c3f_00000      | PENDING  |       | BreakoutNoFrameskip-v4      |
| IMPALA_BeamRiderNoFrameskip-v4_74c3f_00001     | PENDING  |       | BeamRiderNoFrameskip-v4     |
| IMPALA_QbertNoFrameskip-v4_74c3f_00002         | PENDING  |       | QbertNoFrameskip-v4         |
| IMPALA_SpaceInvadersNoFrameskip-v4_74c3f_00003 | PENDING  |       | SpaceInvadersNoFrameskip-v4 |
+------------------------------------------------+----------+-------+-----------------------------+

### Versions / Dependencies

ubuntu16.04
python==3.6.10
ray==1.8.0
pytorch==1.8.0

### Reproduction script

rllib train -f atari-impala/atari-impala.yaml

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Hi @KyunghyunLee, `atari-impala.yaml` specifies 32 workers, each using a CPU. However, the learner and also uses up resources, so the 32 CPUs your cluster has are not sufficient. Can you try e.g. 16 workers?

Can you see any warning outputs for insufficient resources? cc @xwjiang2010
