### ISSUE TITLE
Update to latest arrow?

### ISSUE THREAD

**Issue by alok** [ray-project/ray#2084]
The torch patch I added to arrow would fix #955, part of #1856, and part of #2036.

Is it feasible to update ray to use that version, or at least apply a patch in the build process to apply that one change?

**Comment by richardliaw** [comment]
I tried `git checkout df20683` (which I believe is master) and I wasn't able to compile, unfortunately.

**Comment by alok** [comment]
@richardliaw Can you try it with `git checkout df9bdc10a9481ee328e22cf0dc20e17d4ca4f8d0`? I would do it myself, but my installation is in a shaky place and I don't want to risk breaking it right now.

**Comment by pcmoritz** [comment]
Thanks, I will submit an arrow PR to fix that!

The fix is this:

In cpp/src/plasma/client.h, replace 

#define PLASMA_DEFAULT_RELEASE_DELAY kDeprecatedPlasmaDefaultReleaseDelay;

with

#define PLASMA_DEFAULT_RELEASE_DELAY plasma::kDeprecatedPlasmaDefaultReleaseDelay

**Comment by pcmoritz** [comment]
Patch here, will merge when tests pass: https://github.com/apache/arrow/pull/2063

**Comment by pschafhalter** [comment]
Updating Arrow should also resolve #1014 due to apache/arrow#2055.

**Comment by pcmoritz** [comment]
PR to update Ray: https://github.com/ray-project/ray/pull/2100

**Comment by pschafhalter** [comment]
Fixed by #2100.
