### ISSUE TITLE
[RFC] Usage Data Collection in Ray

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#20857]
Hi all! 

I'd like to get your thoughts on this below proposal which will impact a large number of Ray users.

The Ray team is proposing to enable the collection of usage statistics data in Ray, which will be used to understand how to improve Ray.

[Here is the proposal.](https://docs.google.com/document/d/1ZT-l9YbGHh-iWRUC91jS-ssQ5Qe2UQ43Lsoc1edCalc/edit?usp=sharing) **You will always be able to disable and request deletion usage data collection as described in the proposal [[link](https://docs.google.com/document/d/1ZT-l9YbGHh-iWRUC91jS-ssQ5Qe2UQ43Lsoc1edCalc/edit?usp=sharing)].**

As the Ray project and community have grown, the surface area of Ray has increased a lot, and it’s been increasingly difficult for us to understand how to best spend our time and efforts to improve Ray. We are proposing a lightweight usage statistics and data collection mechanism to help us discover and address the most pressing issues.

While many will appreciate the actionable insights this data provides, we also recognize that not everyone wants to send usage data. Again, we will make sure that **you can always disable collection and/or request usage data deletion as described in the proposal [[link](https://docs.google.com/document/d/1ZT-l9YbGHh-iWRUC91jS-ssQ5Qe2UQ43Lsoc1edCalc/edit?usp=sharing)].**

Please feel free to give your feedback, on this issue or in #data-collection-feedback channel on the Ray Slack!

Update: We'll keep this RFC open for 2 weeks, starting on 12/2 to 12/16.

**Comment by ArturNiederfahrenhorst** [comment]
I support this kind of data collection in open source projects :)

**Comment by davidbuniat** [comment]
I support it as well. Analyzing edge cases of instability and getting actionable insights will be extremely helpful to make Ray more stable.

**Comment by tgaddair** [comment]
This will be very informative for better understanding the community. Looking forward to the blog post summarizing the results :).

**Comment by dmatrix** [comment]
In general, non-intrusive data collection with goodwill and good cause to improve the usage of the platform and its libraries is a good idea. And openly sharing with the community is even better. Good idea!

**Comment by stefanbschneider** [comment]
Same here, I support and see great potential in collecting usage data - and I agree it's crucial that this remains transparent and optional. Looking forward to the resulting insights and improvements!

**Comment by richardliaw** [comment]
This proposal has been up for 1 month and has not received any pushback. Thanks all for your input; we'll be proceeding with implementation now!

**Comment by rkooo567** [comment]
Please check https://docs.ray.io/en/master/cluster/usage-stats.html#usage-disable for more details!
