### ISSUE TITLE
[Bug] nightly test many_nodes_actor_test is flakey

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20862]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/1838#c4491071-470e-4cfb-8623-9d2c0e05cfb5 is hanging

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
https://github.com/ray-project/ray/issues/20395

**Comment by rkooo567** [comment]
Is this expected to be close? (don't we have not sufficient data to confirm?)
