### ISSUE TITLE
[CI] nightly dashboard is broken

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20861]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

go/cd it's broken

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
I contacted support from our dashboard service provider and will report back here.

**Comment by simon-mo** [comment]
Preset ticket https://preset.atlassian.net/browse/PPR-43

im still asking about a better workaround than hard coding the date.

**Comment by simon-mo** [comment]
We are still waiting on preset to fix this and perform a deployment. This is no meaningful update here.

**Comment by simon-mo** [comment]
Preset support told me that they were in the process of fixing and deploying still. The issue still persist.

**Comment by simon-mo** [comment]
From support:
> I have confirmed with our engineering team that the fix had landed on your deployment. You should no longer be seeing issues with datetime filtering. Thank you again for the feedback on the bug that you were experiencing.
