### ISSUE TITLE
[Dataset][Bug]  Ray Dataset and Train example doesn't work

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20874]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I have a script using Ray Dataset and Train that runs locally but when running on an Anyscale cluster, the get_dataset_shard step inside the training func gives an error AttributeError: 'Worker' object has no attribute 'core_worker'
The full script is here: https://github.com/anyscale/ray-on-anyscale-test/blob/ray-dataset/book-rating-prediction-ray-dataset.ipynb

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by matthewdeng** [comment]
Actually explicit Ray Client support wasn't added for Ray Train until 1.9. The behavior in 1.8 in which the `BackendExecutor` is on the driver has not been tested, and may be the reason for this.

**Comment by clarkzinzow** [comment]
Fixed by upgrading to Ray 1.9, when Ray Client support was added to Ray Train.
