### ISSUE TITLE
Can't resume a run after hitting max samples

### ISSUE THREAD

**Issue by mm04926412** [ray-project/ray#20886]
Even if I raise the max sample limit it seems that once a run has hit the original limit that the run is effectivelly dead and cannot be resumed anymore. Is there a work around to this?

**Comment by mvindiola1** [comment]
Resume is for when a trial fails. Restore can be used to start a new trial using the saved parameters of a previous one.

**Comment by mm04926412** [comment]
What I am trying to do is carry on with my hparam search after the script last terminated as I have to do my searches in "bursts" on my cluster. Would restore enable that? I mostly just dont want to throw away the search space information.

**Comment by mm04926412** [comment]
Hi just wanted to bump this.
