### ISSUE TITLE
[Bug] Cannot access member "map_batches" for type "DatasetPipeline[int]"

### ISSUE THREAD

**Issue by tekumara** [ray-project/ray#20888]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

  vscode and pyright report:

```
  12:13 - error: Cannot access member "map_batches" for type "DatasetPipeline[int]"
    Member "map_batches" is unknown (reportGeneralTypeIssues)
```

Because DatasetPipeline is a dynamically created method without type annotations.

This prevents vscode from:
1. being able to go to the definition of the method
1. being able to determine the return type, so autocomplete fails.

This adds friction during development. 

### Versions / Dependencies

ray 1.9.0

### Reproduction script

```
import ray

# Create a dataset and then create a pipeline from it.
base = ray.data.range(1000000)
print(base)
# -> Dataset(num_blocks=200, num_rows=1000000, schema=<class 'int'>)
pipe = base.window(blocks_per_window=10)
print(pipe)
# -> DatasetPipeline(num_windows=20, num_stages=1)

# Applying transforms to pipelines adds more pipeline stages.
pipe = pipe.map_batches(lambda batch: [v * 2 for v in batch])
print(pipe)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@tekumara Thank you, this is great dev UX feedback on how we designed `DatasetPipeline`! We should look at a more editor-friendly way to implement these while still avoiding a lot of boilerplate.

**Comment by GuillaumeDesforges** [comment]
We hit the same limitation because of 
https://github.com/ray-project/ray/blob/e9ae784e629e31f5291dde7bb881da1ab61ab5ec/python/ray/data/dataset_pipeline.py#L791-L821

A quick fix would be to make type stubs https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md

**Comment by GuillaumeDesforges** [comment]
In the meantime, I'll just stop using `.{method}_each_window` since it's just sugar for a one-liner which is well supported by all tooling:

```diff
-  ds = ds.random_shuffle_each_window()
+  ds = ds.foreach_window(lambda ds: ds.random_shuffle())
```
