### ISSUE TITLE
[Bug] [RLlib] Actions are calculated for done agents

### ISSUE THREAD

**Issue by iamhatesz** [ray-project/ray#20904]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When using `rllib.evaluate.rollout` method on a multi-agent environment, actions are being calculated for agents which have just done. This is due to the following code block:

https://github.com/ray-project/ray/blob/master/rllib/evaluate.py#L477-L512

The for-loop over agents doesn't check, if in the previous step a particular agent has done. The `done` flag is simplified to `__all__`, which is obviously False, as other agents are still operating.

If you confirm this as a bug, I can prepare a simple PR for this.

### Versions / Dependencies

1.8.0, master

### Reproduction script

no repro, as this is obviously visible in the code

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
@iamhatesz , yes, this looks like a bug! :) Thanks so much for catching this and for your offer to PR a fix.
