### ISSUE TITLE
[Train] update checkpointing documentation

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#20910]
### Problem 
The existing documentation does not make it clear how users should be saving and loading models. We have a [section on checkpointing](https://docs.ray.io/en/master/train/user_guide.html#checkpointing) but it is pretty generic.

#### Examples
1. https://github.com/ray-project/ray/issues/20824
2. https://discuss.ray.io/t/how-do-i-save-a-model-with-ray-train/4361

### Proposed Solution
 Update User Guide documentation with clear examples of saving/loading model weights.
- Torch: `model.state_dict()` / `model.load_state_dict()`
- Tensorflow (Keras): `model.get_weights()` / `model.set_weights()`

**Comment by jwyyy** [comment]
Hi @matthewdeng, I made a PR to update checkpoint examples in the documentation. Please let me know your feedback once you have time to review. Thank you very much!
