### ISSUE TITLE
[release] `train_tensorflow_mnist_test` failed on nightly test

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#20913]
https://buildkite.com/ray-project/periodic-ci/builds/1874#e503a83e-1765-48d1-bb1e-1efc0c21ad8e

Sorry if I assigned to the wrong person, please reassign if necessary! :)

**Comment by matthewdeng** [comment]
Looks like a sporadic failure, [today's run](https://buildkite.com/ray-project/periodic-ci/builds/1880#c5852419-8f89-462f-8866-9a1fc4782b57) succeeded. Marking this as closed, but please feel free to reopen this issue if this happens again.
