### ISSUE TITLE
[Train] Document how to handle `state_dict`

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#20915]
### Problem

When checkpointing a Torch model's `state_dict`, there may be some inconsistencies when saving/loading depending on whether the model is wrapped in DDP.

### Proposal
Provide a utility method that always fetches the non-DDP version of the `state_dict`.

Without DDP:
```
model.state_dict()
```

With DDP:
```
model.module.state_dict()
```

### Also see
[torch.nn.modules.utils.consume_prefix_in_state_dict_if_present](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/utils.py#L42-L74)

**Comment by matthewdeng** [comment]
Spoke with @amogkam.

Since `consume_prefix_in_state_dict_if_present` should functionally be the same, we may just need to document this as the recommended approach in the checkpointing section!

**Comment by matthewdeng** [comment]
Added to Checkpointing docs in https://github.com/ray-project/ray/pull/20973. 

If anyone runs into issues or finds the docs confusing, please feel free to reopen this issue. Thanks!

**Comment by xeray** [comment]
Hey Matt,

having to use `consume_prefix_in_state_dict_if_present` is a bit overhead. Would you recommend against using the "unprepared" model for the purpose of checkpointing? It seems that the since DDP just wraps around the model, the actual model buffers are the same objects. So it might be more straightforward to do this:

```
plain_model = Model(...)
ray_model = ray.train.torch.prepare_model(plain_model)
for in in range(...):
  ray_model.train_step()
  ray.air.Checkpoint.from_dict(plain_model.state_dict())
```

**Comment by amogkam** [comment]
Hey @xeray, yes that also works
