### ISSUE TITLE
[Train] Better log message for actor name

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#20914]
From @matthewdeng:

In Ray Train, any log/print messages from the worker side show up like this 

```
(BaseWorkerMixin pid=78517) op: "TensorSliceDataset"
(BaseWorkerMixin pid=78517) input: "Placeholder/_0"
(BaseWorkerMixin pid=78517) input: "Placeholder/_1"
(BaseWorkerMixin pid=78517) attr {
(BaseWorkerMixin pid=78517)   key: "Toutput_types"
(BaseWorkerMixin pid=78517)   value {
(BaseWorkerMixin pid=78517)     list {
(BaseWorkerMixin pid=78517)       type: DT_FLOAT
(BaseWorkerMixin pid=78517)       type: DT_INT64
(BaseWorkerMixin pid=78517)     }
(BaseWorkerMixin pid=78517)   }
(BaseWorkerMixin pid=78517) }
```

By default the class name that's executing the training function is used (`BaseWorkerMixin`), but this is confusing since it's an internal concept.

It would be better to show a better name here: either the name of the actual function or something like `TrainingWorker_0`, `TrainingWorker_1`, etc.

**Comment by richardliaw** [comment]
You can use `__repr__` to do this I think.

**Comment by matthewdeng** [comment]
Duplicate of https://github.com/ray-project/ray/issues/20593
