### ISSUE TITLE
[release] `network_overhead` failed on nightly test

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#20912]
https://buildkite.com/ray-project/periodic-ci/builds/1874#e503a83e-1765-48d1-bb1e-1efc0c21ad8e

Please reassign if necessary, thanks! :)

**Comment by ericl** [comment]
Ping on this?

**Comment by architkulkarni** [comment]
I went through the history, looks like it's just very flaky.  I think this means for the release we can just rerun it until it passes, so let me downgrade this to P1.

**Comment by krfricke** [comment]
Passing (mostly) in recent builds
