### ISSUE TITLE
[Serve] Add Serve metric for HTTP error codes

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#20928]
Serve currently provides a metric `serve_deployment_error_counter` for the number of exceptions that happen inside each deployment. 

Another useful metric is how many non-200 HTTP return codes have been returned.  These could happen in a user's deployment even if there was no exception raised, so this is a distinct metric from `serve_deployment_error_counter`.

**Comment by Hankpipi** [comment]
I'm interested in this, I wonder if errors caught in` http_proxy.py` are all the HTTP errors we need to count.

**Comment by architkulkarni** [comment]
I took a brief look at the code and it looks like `_send_request_to_handle` has the logic where we actually send the response.  We could count the non-200 return codes here, but if we do that I don't know how we would be able to tag it by deployment.  Maybe there's a better place to do it?

**Comment by Hankpipi** [comment]
Can we just tag this metric by `handle.endpoint_name`? 
I find that the metrics defined in `router.py` is tagged by `endpoint_name` too(`self.deployment_name` defined in class `Router` is actually `endpoint_name`).
https://github.com/ray-project/ray/blob/f7b0b872f9d5a2671d52d53891255d9f814034f7/python/ray/serve/handle.py#L99-L104

**Comment by architkulkarni** [comment]
> Can we just tag this metrics by `handle.endpoint_name`? I find that the metrics defined in `router.py` is tagged by `endpoint_name` too(`self.deployment_name` defined in class `Router` is actually `endpoint_name`, I'm not sure is this a naming error).
> 
> https://github.com/ray-project/ray/blob/f7b0b872f9d5a2671d52d53891255d9f814034f7/python/ray/serve/handle.py#L99-L104
> 
> 
> https://github.com/ray-project/ray/blob/f7b0b872f9d5a2671d52d53891255d9f814034f7/python/ray/serve/router.py#L175-L181

Oh nice, I think that could work!  You're probably right that it's a naming error, feel free to fix it--at some point we renamed everything from the pre-Ray 1.4 "backends and endpoints" API to the new "deployments" API, but some things may have fallen through the cracks.

**Comment by Hankpipi** [comment]
I have tried to fix this naming error and add metrics for HTTP error codes, please help review @architkulkarni.
