### ISSUE TITLE
[Feature] Support Java async actors

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#20967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Python already supports asyncio actors, which allows users to run multiple concurrent tasks in one thread. Another similar feature is concurrent actor calls, which runs multiple concurrent tasks synchronously in multiple threads.

Java doesn't have native support for event loops. But sometimes users want to use their own thread pools to handle an actor task and reply the task asynchronously.  This use case is not yet supported. 

Here is the proposed API:
```java
public class AsyncActor {
	
	public Future<Integer> asyncMethod() {
	   CommpletableFuture<Integer> resFuture = new CompletableFture<Integer>();
	   new Thread(() -> {
	       resFuture.completeValue(1);
	   }).start();
	   return resFuture;
	}

	public int syncMethod() {
		return 1; 
	}
}

ActorHandle<AsyncActor> asyncActor = Ray.actor(AsyncActor::new)
        .setAsync(True)
	.remote();
ObjectRef<Integer> res = asyncActor.task(AsyncActor::asyncMethod)
    .remote();
System.out.println(res.get());
```

Key design points:
- Users should explicitly specify whether an actor is async or not, as Java doesn't have "async def".
- Any method that returns a `Future<T>` is considered an async method. The caller still get `ObjectRef<T>`, instead of `ObjectRef<<Future<T>>`.
- Unlikely Python aynscio actor case where Ray creates the event loop thread, users can use their own threads to handle the task. When the returned future object is complete, Ray will finish the pending task and reply to the caller. 
- The underlying implementation in core worker depends on Fiber, which is exactly the same as Python asyncio actors.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by raulchen** [comment]
cc @kfstorm @jovany-wang @kira-lin

**Comment by kfstorm** [comment]
Can we not add 'setAsync(true)'? We can infer whether it's an async actor by scanning member methods. If this is not a good approach, at least use annotation instead. Actor options set on actor creation is mainly designed for dynamic tuning, but whether an actor is async should be solely defined by the code of the actor. It's not possible to change it at runtime.

**Comment by raulchen** [comment]
> Can we not add 'setAsync(true)'? We can infer whether it's an async actor by scanning member methods. If this is not a good approach, at least use annotation instead. Actor options set on actor creation is mainly designed for dynamic tuning, but whether an actor is async should be solely defined by the code of the actor. It's not possible to change it at runtime.

Makes sense. I'll use an annotation.
