### ISSUE TITLE
Ray tune fails to use gpu.

### ISSUE THREAD

**Issue by saharudra** [ray-project/ray#2096]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux, Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.4.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: Providing the code, running it throws the error.

### Describe the problem

Ray fails to utilize GPU resources, the code when run without ray works fine.
The pytorch code is in mnist_classification_pytorch.txt

### Source code / logs

[ray_output.txt](https://github.com/ray-project/ray/files/2017596/ray_output.txt)
[mnist_classification_pytorch.txt](https://github.com/ray-project/ray/files/2017599/mnist_classification_pytorch.txt)

**Comment by richardliaw** [comment]
You’ll need to specify trial_resources in the dict that you’re passing into
run_experiments. Check out
http://ray.readthedocs.io/en/latest/tune-config.html

Let me know if you run into any other issues!

**Comment by saharudra** [comment]
Hi, thanks for that. The process started utilizing GPU resources. But I am facing the following issue.
[log_test.txt](https://github.com/ray-project/ray/files/2018102/log_test.txt)

**Comment by richardliaw** [comment]
You might need to make sure ave_loss is a float, rather than a list or
tensor.

**Comment by saharudra** [comment]
Thanks, it worked.
