### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ahah-figure** [ray-project/ray#20975]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Often, when I initialize ray on a dataproc cluster, many nodes report the following message. Not 100% sure at this point, but I think it mostly occurs when calling ```ray.init()``` after calling ```ray.shutdown()```. Despite the message, everything seems to work fine. Is this anything I need to worry about?

```
(pid=15228, ip=x) [2021-12-08 18:27:50,700 C 15228 16032] core_worker.cc:194:  Check failed: core_worker_process The core worker process is not initialized yet or already shutdown.
(pid=15228, ip=x) *** StackTrace Information ***
(pid=15228, ip=x)     ray::SpdLogMessage::Flush()
(pid=15228, ip=x)     ray::RayLog::~RayLog()
(pid=15228, ip=x)     ray::core::CoreWorkerProcess::EnsureInitialized()
(pid=15228, ip=x)     ray::core::CoreWorkerProcess::GetCoreWorker()
(pid=15228, ip=x)     __pyx_pw_3ray_7_raylet_10CoreWorker_23get_worker_id()
(pid=15228, ip=x)     method_vectorcall_NOARGS
```

### Versions / Dependencies

ray=1.8; python=3.8; ubuntu=18.10

### Reproduction script

```
ray.init(address="localhost:6379", _redis_password="xxx", include_dashboard=True)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
Thanks for reporting @ahah-figure, there is nothing to worry about and has been fixed in ray 1.9
