### ISSUE TITLE
[Bug] core_driver.log leaks when log_to_driver=False

### ISSUE THREAD

**Issue by jeffreykennethli** [ray-project/ray#20991]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

After running ray.init(log_to_driver=False), then ray.shutdown(), the ray driver logs remain open, when they are expected to be closed. See screenshot:

![image](https://user-images.githubusercontent.com/15958254/145435528-15ee4384-6559-4e1d-a5fc-6893ddac40f1.png)

### Versions / Dependencies

ray==1.9.0
python==3.8.8
psutil==5.6.6

OS: macOS 12

### Reproduction script

```
import ray
import psutil

p = psutil.Process()
ray.init(log_to_driver=False)
ray.shutdown()
print(p.open_files())

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by YarShev** [comment]
@jeffreykennethli, does the issue still persist?

**Comment by YarShev** [comment]
stub

**Comment by richardliaw** [comment]
I think this is still an issue. @rkooo567 should triage when you get the time.

**Comment by rkooo567** [comment]
Hmm actually I think this is an intended behavior. The file is open because we are writing cpp logs from driver core worker.
