### ISSUE TITLE
[regression] stress_test_many_task performance regression 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#20999]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

N/A

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/21304
