### ISSUE TITLE
[Serve Autoscaler] Dynamically increase min_replicas

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#21018]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

**Issue**

When a Serve Deployment is redeployed with a higher `min_replicas` value, it doesn't increase the number of replicas. However, the unfinished requests remain queued (which is expected).

**Expected Behavior**

When a Serve Deployment is redeployed with a higher `min_replicas` value, it should increase the number of replicas to the new `min_replicas` value, and it should keep unfinished requests queued until they are completed.

### Versions / Dependencies

Ray: 2.0.0.dev0
Python: 3.8.12
OS: macOS Big Sur 11.4 (M1 Mac)

### Reproduction script

Reproduction script (add this test to `python/ray/serve/tests/test_autoscaling_policy.py`):

```python
@pytest.mark.skipif(sys.platform == "win32", reason="Failing on Windows.")
def test_e2e_raise_min_replicas(serve_instance):
    signal = SignalActor.remote()

    @serve.deployment(
        _autoscaling_config={
            "metrics_interval_s": 0.1,
            "min_replicas": 1,
            "max_replicas": 10,
            "look_back_period_s": 0.2,
            "downscale_delay_s": 0.2,
            "upscale_delay_s": 0.2
        },
        # We will send over a lot of queries. This will make sure replicas are
        # killed quickly during cleanup.
        _graceful_shutdown_timeout_s=1,
        max_concurrent_queries=1000,
        version="v1")
    class A:
        def __call__(self):
            ray.get(signal.wait.remote())

    A.deploy()

    controller = serve_instance._controller
    start_time = get_deployment_start_time(controller, A)

    handle = A.get_handle()
    [handle.remote() for _ in range(1)]

    print("\nstay at 1\n")

    import time
    time.sleep(3)

    assert get_num_running_replicas(controller, A) == 1
    
    print("\nredeploy A\n")
    A.options(_autoscaling_config={
            "metrics_interval_s": 0.1,
            "min_replicas": 2,
            "max_replicas": 10,
            "look_back_period_s": 0.2,
            "downscale_delay_s": 0.2,
            "upscale_delay_s": 0.2
        },
        # We will send over a lot of queries. This will make sure replicas are
        # killed quickly during cleanup.
        _graceful_shutdown_timeout_s=1,
        max_concurrent_queries=1000,
        version="v2")
     
    # BUG: this redeployment does not increase the number of replicas
    A.deploy()

    print("\nscale to 2\n")
    wait_for_condition(lambda: get_num_running_replicas(controller, A) >= 2)
    assert get_num_running_replicas(controller, A) == 2

    signal.send.remote()

    # As the queue is drained, we should scale back down.
    wait_for_condition(lambda: get_num_running_replicas(controller, A) <= 2)
    assert get_num_running_replicas(controller, A) > 1

    # Make sure start time did not change for the deployment
    assert get_deployment_start_time(controller, A) == start_time
```

To see the number of replicas at each control loop, call `print(current_num_ongoing_requests)` in `controller.py`'s `autoscale()` function.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iasoon** [comment]
@shrekris-anyscale I can't reproduce this issue. Could it be that your testcase has an error? I think that on the second `deploy` call, you are deploying `v1` of your deployment again. For deploying the new configuration, `A.options(**opts).deploy()` should be used. With that change, the testcase passes for me.

**Comment by shrekris-anyscale** [comment]
Ah, thanks @iasoon. The test did indeed have the error that you mentioned. With the fix, it passes on my end as well, so I'll close the issue.
