### ISSUE TITLE
[Bug] Ray client connection error after running helm upgrade

### ISSUE THREAD

**Issue by daikeshi** [ray-project/ray#21031]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

We host our Ray cluster on GKE using the k8s operator. I notice lately that after I run helm upgrade with updated chart values for workers (e.g. worker memory and cpu configurations), the Ray client always reportsed the following errors when I try to connect to the remote cluster. 

```python
import ray
ray.init("ray://*.*.*.*:10001")
```
```shell
(pid=runtime_env, ip=10.202.73.4) 2021-12-10 19:20:12,407	INFO conda_utils.py:101 -- Creating conda environment /tmp/ray/session_2021-12-10_18-35-53_413495_421/runtime_resources/conda/3064695ffd6b3f9c33cecca7eab1f711da6c9ed4
(raylet, ip=10.202.73.4) [2021-12-10 19:20:13,027 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.202.73.4) [2021-12-10 19:20:13,029 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.202.73.4) [2021-12-10 19:20:13,030 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
```

I have to restart the head pod to fix this issue. I wonder if this is expected or there are other workarounds to avoid restarting the head node. It seems I don't have this issue if I directly edit `raycluster` k8s resource object via `kubectl edit -n ray raycluster keshi-ray-test`. 

### Versions / Dependencies

```shell
ray==1.8.0
helm==v3.7.1
```

### Reproduction script

1. Update cpu and memory values in Ray chart `ray-helm-chart/value.yaml`
```
rayWorkerType:
    memory: 16Gi
    CPU: 8
```
2. Run `helm  -n ray upgrade --install --set namespacedOperator=True keshi-ray-test  ./ray-helm-chart`
3. Run the following python script to connect to the remote cluster.
```python
import ray
ray.init("ray://*.*.*.*:10001")
```
 

### Anything else
Sometimes, after deleting the head pod, the operator couldn't create a new one, I saw the following errors from the ray operator log. I had to delete the cluster and recreate it. 
```shell
keshi-ray-test,ray:2021-12-10 20:05:41,806	ERROR monitor.py:398 -- Error in monitor loop
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 439, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 318, in _run
    self.update_load_metrics()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 234, in update_load_metrics
    request, timeout=60)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1639195541.804102929","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639195541.804101280","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
keshi-ray-test,ray:2021-12-10 20:05:41,806	DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 439, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 318, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 234, in update_load_metrics\n    request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1639195541.804102929","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639195541.804101280","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>\n' True None
keshi-ray-test,ray:2021-12-10 20:06:01,807	ERROR gcs_utils.py:137 -- Failed to send request to gcs, reconnecting. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1639195561.806849457","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639195561.806847815","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
keshi-ray-test,ray:2021-12-10 20:08:13,196	ERROR gcs_utils.py:142 -- Connecting to gcs failed. Error <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1639195561.806849457","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639195561.806847815","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
keshi-ray-test,ray:2021-12-10 20:08:14,198	DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_error' b'The autoscaler failed with the following error:\nTraceback (most recent call last):\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 439, in run\n    self._run()\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 318, in _run\n    self.update_load_metrics()\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 234, in update_load_metrics\n    request, timeout=60)\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__\n    return _end_unary_response_blocking(state, call, False, None)\n  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking\n    raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "failed to connect to all addresses"\n\tdebug_error_string = "{"created":"@1639195541.804102929","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1639195541.804101280","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"\n>\n' True None
```

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
@DmitriGekhtman @wuisawesome any thoughts here?

cc @zhe-thoughts @gjoliver @worldveil for visibility

**Comment by DmitriGekhtman** [comment]
That's definitely problematic. The suboptimal workaround while we look into this is to tear down the Ray cluster and then recreate it, rather than updating the configuration.

**Comment by daikeshi** [comment]
> That's definitely problematic. The suboptimal workaround while we look into this is to tear down the Ray cluster and then recreate it, rather than updating the configuration.

:-) yeah, this is what I'm doing right now as a workaround. Please keep me posted and let me know if there's anything I can help with.

**Comment by jacobdanovitch** [comment]
Hmm, I'm also seeing this (`agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.`) but tearing my cluster down didn't fix it for me. It also doesn't seem to be breaking anything; is there at least a way to silence it?

**Comment by architkulkarni** [comment]
The "Failed to delete URIs" error comes from the runtime environment garbage collection, but I'm not sure exactly what is causing the error or why it is happening with the Helm upgrade.  To disable garbage collection the following might help, taken from the [master branch docs](https://docs.ray.io/en/master/handling-dependencies.html):

> Runtime environment resources on each node (such as conda environments, pip packages, or downloaded `working_dir` or `py_modules` folders) will be removed when they are no longer referenced by any actor, task or job. To disable this (for example, for debugging purposes) set the environment variable `RAY_runtime_env_skip_local_gc` to `1` on each node in your cluster before starting Ray (e.g. with `ray start`).

**Comment by architkulkarni** [comment]
@DmitriGekhtman it's odd because the reproduction in the original post doesn't seem to use runtime environments at all.  Does a runtime environment get inserted automatically when using the K8s operator?

@daikeshi @jacobdanovitch could there be any clues in the logs?  By default they are in `/tmp/ray/session_latest/logs`.  If you zip them up and share I can take a look.

**Comment by DmitriGekhtman** [comment]
> Does a runtime environment get inserted automatically when using the K8s operator?

I don't think so.

**Comment by daikeshi** [comment]
@architkulkarni I don't have the logs now, but I can try to reproduce it tomorrow. Where can I find `/tmp/ray/session_latest/logs`?

**Comment by architkulkarni** [comment]
@daikeshi that directory should be present on each node in the Ray cluster.  @DmitriGekhtman is this the recommended way to get the logs when using K8s?

**Comment by wuisawesome** [comment]
This might be a grpc versioning issue under the hood?

**Comment by DmitriGekhtman** [comment]
This issue pertains to the deprecated legacy Ray Operator.
