### ISSUE TITLE
[Bug] executing trials in local mode (ray.init(local_mode=True)) triggers endless blocking for next trial

### ISSUE THREAD

**Issue by karstenddwx** [ray-project/ray#21048]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

trial_runner.py blocks forever for providing the next trial (endless loop),
while loop in _update_trial_queue never breaks

prerequisites:
- initialize ray in local_mode=True (max_concurrent=1 -> which on its part causes not providing next trial)
- do not execute trial if trial already exists (see MyTrialExecuter)

run the code snippet provided to reproduce the issue

### Versions / Dependencies

ray 1.9

### Reproduction script

    import os
    import ray
    from ray import tune
    from ray.tune.experiment import Experiment
    from ray.rllib.examples.env.debug_counter_env import DebugCounterEnv
    from ray.tune.ray_trial_executor import RayTrialExecutor
    from ray.tune.trial import Trial

    class MyTrialExecutor(RayTrialExecutor):
        """ my trial executor sets trial state to 'TERMINATED' if trial folder already exists """
        def __init__(self):
            super(MyTrialExecutor, self).__init__()

        def start_trial(self, trial, checkpoint=None, train=True):
            env_name = trial.config['env']
            trial_foldername = f'{trial.trainable_name}_{env_name}'
            existing_trial_folders = [f for f in os.listdir(trial.local_dir) if f.startswith(trial_foldername)]
            if existing_trial_folders:
                trial.set_status(Trial.TERMINATED)
                return True

            return super().start_trial(trial, train=train)

    if __name__ == "__main__":
        env_name = DebugCounterEnv.__name__
        tune.register_env(env_name, lambda config: DebugCounterEnv(config))

        ray.init(local_mode=True)
        # ray.init()

        exp_name = env_name
        spec = {
            'run': "DQN",
            'stop': {
                "training_iteration": 1
            },
            'config': {
                "env": env_name,
            },
            'checkpoint_at_end': True,
        }
        ray.tune.run_experiments(Experiment.from_json(exp_name, spec), trial_executor=MyTrialExecutor())

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Local mode is not well tested/supported and should generally only be used for testing purposes. Does this block your use case?

**Comment by karstenddwx** [comment]
> Local mode is not well tested/supported and should generally only be used for testing purposes. Does this block your use case?

Normally, within the IDE I run with local mode to be able to debug rllib in case. Real trainings running outside the IDE anyway, why I not switch back from local mode inside the IDE.
Testing quick rllib training and evaluation round trip as a pytest currently not finishes.

I know a simple workaround in the process helps, but an existing feature should work in any case.

But yes, it does NOT block my use case.

**Comment by krfricke** [comment]
Closing this as this is non-blocking, and custom trial executors will be deprecated, soon.
