### ISSUE TITLE
[Bug] Memory usage growing unboundedly using episode step callback.

### ISSUE THREAD

**Issue by duburcqa** [ray-project/ray#21041]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

For some reason, the memory usage grows unboundedly and linearly until eventually OOM error if I enable this monitoring callback. I'm using PPO algorithm for training. I can confirm it is not happening if it is disabled. Normally, it is expected to store only a bunch of episodes as history for statistics smoothing. My episodes are quite short, so it is not the issue. For some reason, it seems that the old episodes are not properly collected because of this. 

```
class MonitorInfoCallback(DefaultCallbacks):
    def on_episode_step(self, *, episode: MultiAgentEpisode, **kwargs: Any) -> None:
        super().on_episode_step(episode=episode, **kwargs)
        info = episode.last_info_for()
        if info is not None:
            for key, value in info.items():
                episode.hist_data.setdefault(key, []).append(value)
```

Does anybody has any idea about what is causing the issue and how to solve it ? Maybe it is not the right way to log custom histograms without min/max/mean graph in tensorboard ? 

For the record, `episode.hist_data` is used to compute `hist_stats` via `summarize_episodes` in `CollectMetrics` that is part of the execution plan. Maybe I should add a step to delete the original histogram data afterward ?

### Versions / Dependencies

I have this problem since ever on Linux. Everything ranging from Python 3.6 on Ubuntu 18.04 with Ray 1.3.0 to Python 3.9 on Ubuntu 21.10 with ray 1.9.0.

### Reproduction script

Any dummy environment returning `info: Dict[str, float]` and using PPO algorithm should do the trick. It should be the same for any other algorithm but I haven't tested it.

### Anything else

I'm trying to fix it by changing the way `CollectMetrics` works. We will see if it helps.

Updated: No luck. I did not manage to fix it.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by duburcqa** [comment]
Here is what I get using tracemalloc between each training iterations:
```
/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py:162: size=317 MiB (+32.9 MiB), count=8856446 (+945713), average=37 B
/home/duburcqa/.local/lib/python3.9/site-packages/ray/rllib/evaluation/metrics.py:162: size=7017 KiB (+706 KiB), count=33 (+0), average=213 KiB
<string>:1: size=4215 KiB (+373 KiB), count=41506 (+3675), average=104 B
/usr/lib/python3.9/tracemalloc.py:193: size=204 KiB (+72.4 KiB), count=3084 (+1511), average=68 B
/usr/lib/python3.9/tracemalloc.py:115: size=52.5 KiB (+52.5 KiB), count=672 (+672), average=80 B
/home/duburcqa/.local/lib/python3.9/site-packages/tree/__init__.py:510: size=17.5 KiB (-42.6 KiB), count=320 (-907), average=56 B
/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py:160: size=47.4 MiB (-40.7 KiB), count=960390 (+0), average=52 B
/home/duburcqa/.local/lib/python3.9/site-packages/ray/rllib/execution/metric_ops.py:94: size=324 KiB (+28.7 KiB), count=2 (+0), average=162 KiB
/home/duburcqa/.local/lib/python3.9/site-packages/torch/nn/modules/container.py:141: size=3264 B (-7968 B), count=57 (-166), average=57 B
/usr/lib/python3.9/tracemalloc.py:132: size=6080 B (+6080 B), count=1 (+1), average=6080 B
```

```
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/rllib/execution/metric_ops.py", line 83
   episodes, self.to_be_collected = collect_episodes(
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/rllib/evaluation/metrics.py", line 112
   metric_lists = ray.get(collected)
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105
   return func(*args, **kwargs)
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/worker.py", line 1706
   values, debugger_breakpoint = worker.get_objects(
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/worker.py", line 363
   return self.deserialize_objects(data_metadata_pairs,
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/worker.py", line 325
   return context.deserialize_objects(data_metadata_pairs,
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py", line 281
   obj = self._deserialize_object(data, metadata, object_ref)
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py", line 194
   return self._deserialize_msgpack_data(data, metadata_fields)
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py", line 172
   python_objects = self._deserialize_pickle5_data(pickle5_data)
 File "/home/duburcqa/.local/lib/python3.9/site-packages/ray/serialization.py", line 162
   obj = pickle.loads(in_band)
```

**Comment by duburcqa** [comment]
Comparison with and without `MonitorInfoCallback` enabled:
![image](https://user-images.githubusercontent.com/17752950/145728946-4f9c040f-00d6-4156-ab75-d0116ad8436c.png)

**Comment by krfricke** [comment]
cc @sven1977

**Comment by duburcqa** [comment]
Anybody has any idea ? This bug is very painful. I just cannot use ray at all because of it.

**Comment by duburcqa** [comment]
still blocking.

**Comment by sven1977** [comment]
Strange, episodes don't get recycled, so there shouldn't be any remaining `hist_stats` in a new one.

**Comment by sven1977** [comment]
Hey @duburcqa , could you provide a fully functional, single repro script that runs as-is so I can debug this? Thanks.

**Comment by duburcqa** [comment]
@sven1977 ok I will try and let you know. It should be straightforward.

**Comment by duburcqa** [comment]
@sven1977 Here it is:
```
import logging
from copy import deepcopy

import gym

import ray
from ray.rllib.agents.callbacks import DefaultCallbacks
from ray.rllib.agents.ppo import DEFAULT_CONFIG, PPOTrainer as Trainer


class MonitorInfoCallback(DefaultCallbacks):
    def on_episode_step(self, *, episode, **kwargs):
        super().on_episode_step(episode=episode, **kwargs)
        info = episode.last_info_for()
        if info is not None:
            for key, value in info.items():
                episode.hist_data.setdefault(key, []).append(value)

class DummyEnv(gym.Env):
    def __init__(self, env_config):
        self.action_space = gym.spaces.Box(low=-1, high=1, shape=(1,))
        self.observation_space = gym.spaces.Box(low=-1, high=1, shape=(1,))

    def reset(self):
        return self.observation_space.sample()

    def step(self, action):
        obs = self.observation_space.sample()
        rew = 0.0
        done = False
        info = {f"metadata_{i}": 0.0 for i in range(100)}
        return obs, rew, done, info

config = deepcopy(DEFAULT_CONFIG)
config["framework"] = "torch"
config["num_gpus"] = 1
config["log_level"] = logging.ERROR
config["metrics_smoothing_episodes"] = 0
config["env"] = DummyEnv
config["callbacks"] = MonitorInfoCallback
config["normalize_actions"] = False
config["clip_actions"] = False
config["sample_async"] = False
config["train_batch_size"] = 80000
config["sgd_minibatch_size"] = 8000
config["num_sgd_iter"] = 20
config["num_workers"] = 8
config["num_envs_per_worker"] = 5
config["rollout_fragment_length"] = 2000

logger_creator = ray.init(
    num_cpus=8,
    num_gpus=1,
    logging_level=logging.ERROR,
    log_to_driver=False,
    include_dashboard=False)

train_agent = Trainer(config)
while True:
    train_agent.train()
```

**Comment by duburcqa** [comment]
![image](https://user-images.githubusercontent.com/17752950/148525661-91341d95-1232-433e-bb8c-4631920a8ead.png)

**Comment by PNaughton** [comment]
@duburcqa are you sure that your environment finishes in this example? I could be wrong, but it is not obvious to me that it would.

**Comment by duburcqa** [comment]
What do you mean ? Anyway I don't understand why anything like this could legitimate a memory leak.

**Comment by duburcqa** [comment]
@gjoliver why did you close this issue ? It is not fixed and still blocking me. I  just don't have time to work on it anymore.

**Comment by gjoliver** [comment]
Your last update seemed to indicate that you had found a fix, I probably mis-understood.
We have too many outstanding issues, I was trying to figure out which ones we actually need to spend time on.
If 1) your actual env is finishing, but still have a memory leak, and 2) you need input or help from the team,
feel free to provide an updated reproduce script and then re-open the issue.
Thanks.

**Comment by duburcqa** [comment]
Ok I will do so. I was saying that the reproduction script was actually not reproducing the issue because we managed to fix it. Unfortunately the fix only works with the toy example and not my actual learning pipeline. So I need to come up with the better example.

**Comment by gjoliver** [comment]
I see. yeah, definitely reopen the issue once this is actionable again.
thanks.
