### ISSUE TITLE
[Bug] ImpalaTrainer - RuntimeError: Dequeue `check()` returned False! 

### ISSUE THREAD

**Issue by kajc10** [ray-project/ray#21058]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, Ray Train, RLlib

### What happened + What you expected to happen

Ran ImpalaTrainer and after a few iterations an error is raised : RuntimeError: Dequeue `check()` returned False! Exiting with Exception from Dequeue iterator.  The same environment was used with PPOTrainer without any problems.

### Versions / Dependencies

Ubuntu 20.04.3
Ray 1.9.0
Python 3.8.10

### Reproduction script

```bash
register_env("myenv", prepare_env)
ray.shutdown()

ray.init(
	num_cpus=args.num_cpus,
	num_gpus=args.num_gpus,
	include_dashboard=False,
	ignore_reinit_error=True,
	log_to_driver=False,
)

parameter_search_analysis = ray.tune.run(
	ImpalaTrainer,
	name=training_name,
	#Trainer (algorithm) config
	config={
		"env": "myenv",         
		"framework": "torch",

		#Model config
		"model": {
			"fcnet_activation": "relu"
		},

		"env_config": {
			"accepted_start_angle_deg": 5,
		},

    	"num_workers": args.num_cpus - 1,
    	"num_gpus": args.num_gpus,
	},
	stop={'timesteps_total': max_steps},
	num_samples=1,
	metric="episode_reward_mean",
	mode="max",
    checkpoint_at_end=True,
    local_dir="./dump",
    keep_checkpoints_num=2,
    checkpoint_score_attr="episode_reward_mean",
    checkpoint_freq=1,
)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @kajc10 , thanks for filing this issue. Could you make sure your reproduction script works as-is out of the box? It's currently dependent on some missing code, e.g. `prepare_env`. Thanks.

**Comment by gjoliver** [comment]
I am gonna close since it's about 1.9.0, and has been a while since last update.

**Comment by andraxin** [comment]
[Apparently](https://buildkite.com/ray-project/ray-builders-pr/builds/44593#01834ab7-eb3f-4754-930f-a4fe5228ccff), the problem persists in 1.13.0, and also on the current `master` as evidenced by a failed CI build:
https://buildkite.com/ray-project/ray-builders-pr/builds/44593#01834ab7-eb3f-4754-930f-a4fe5228ccff/13-3427

So, you have your reproduction right in your own test code, but still choose to do nothing about it... GREAT!
