### ISSUE TITLE
[Bug] ExperiementAnalysis doesnt work if path has been changed

### ISSUE THREAD

**Issue by kaechb** [ray-project/ray#21050]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Hi, 
I did not find any issue regarding this, but I can hardly believe that I am the only one that ran into this. 

1. When renaming the folder containing the results of a ray tune search, the ExperimentalAnalysis can not be used anymore: e.g. renaming train_2021-12-08_16-47-01 to RandomSearch will give the error when loading
 `Could not load trials from experiment checkpoint. This means your experiment checkpoint is likely faulty or incomplete, and you won't have access to all analysis methods. Observed error: Unknown trainable: train
Couldn't read config from 459 paths `
2. Somehow expected that to work independently of the path names
3. This was run on a server with SLURM

### Versions / Dependencies

ray 1.9.0

### Reproduction script

Just anything including a tune.run with only the following keywords:
`tune.run(
        tune.with_parameters(train,jets=jets,scalar=scaler),
        # metric="loss",
        # mode="min",
        search_alg=df_search,
        scheduler=scheduler,
        num_samples= num_samples,
        config=bayes_config,
        resources_per_trial=resources
    )`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
See also https://discuss.ray.io/t/experimentanalysis-on-google-cloud-storage/5783/6 - we should fix this soon

**Comment by Yard1** [comment]
@krfricke @xwjiang2010 let's talk about this during the tune eng sync
