### ISSUE TITLE
Tune.run takes a long time before training

### ISSUE THREAD

**Issue by fengxiaoxu96** [ray-project/ray#21071]
Hello!

I am using `Tune.run()` to train `PPO` agent in rllib.

The `tune.run` command is like this
```
results = tune.run(
        "PPO",
        config=config,
        stop=stop,
        local_dir=args.result_dir,
        verbose=3,
        scheduler = asha_scheduler,
        progress_reporter=reporter,
        checkpoint_freq=5,
        checkpoint_at_end=True,
    )
```
and the model config is
```
config = {
        "env": "Hsrsim-v0",

        "num_gpus": int(os.environ.get("RLLIB_NUM_GPUS", "1")),

        "model": {
            "post_fcnet_hiddens": [256, 256],
            "post_fcnet_activation": "relu" 
        },
        "callbacks":MyCallbacks,
        "horizon":1000,
        "rollout_fragment_length":128,
        "batch_mode": "truncate_episodes",

        "gamma": 0.99,
        "lr": 0.0001,
        "train_batch_size": 128,
        "framework": "torch",

        "num_workers":1,
        "vf_loss_coeff":0.01
    }
```
the asha_scheduler is set as this
```
asha_scheduler = ASHAScheduler(
        time_attr='training_iteration',
        metric='episode_reward_mean',
        mode='max',
        max_t=100,
        grace_period=5,
        reduction_factor=3,
        brackets=1
    )
```

But the training does not start and it always keeps showing `== Status ==` in the terminal as
```
== Status ==
Current time: 2021-12-14 07:31:12 (running for 00:22:20.98)
Memory usage on this node: 13.4/62.7 GiB
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 45.000: None | Iter 15.000: None | Iter 5.000: None
Resources requested: 2.0/2 CPUs, 1.0/1 GPUs, 0.0/37.09 GiB heap, 0.0/18.54 GiB objects
Result logdir: /home/feng/ray_results/PPO
Number of trials: 1/1 (1 RUNNING)
+---------------------------+----------+---------------------+
| Trial name                | status   | loc                 |
|---------------------------+----------+---------------------|
| PPO_Hsrsim-v0_b0c82_00000 | RUNNING  | 192.168.11.86:95416 |
+---------------------------+----------+---------------------+
```

The CPU usage is 100% and GPU has `PPO.train()` process but is not working.

I saw the [#5386](https://github.com/ray-project/ray/issues/5386) and he solved it by reducing the size of grid-search.
But in my case, I do not need to search so I am confused why it is stuck in this stage.

Appreciate any help about this.

**Comment by fengxiaoxu96** [comment]
Previously, the initialization code is `ray.init(num_cpus=2)`,
retried with `ray.init()` and it can start to train, but `reward = nan` for all iters

and later I changed nothing and try again the training and it is again stuck in searching with keeping showing `Status` as above.

Can anyone help with this problem?

**Comment by tuln128** [comment]
Hello @fengxiaoxu96,
I am wondering if you were able to fix the problem mentioned above or not, as I am facing the same situation. It would be greatly appreciated if you can share your experience on how to get if fixed.
Thank you very much in advance!
