### ISSUE TITLE
[1.9.1 release] CI test "Run Windows Build" failing consistently on release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21079]
Example: https://buildkite.com/ray-project/ray-builders-branch/builds/5157#30d1ac78-a93d-4d36-b710-3296c5a134d2

**Comment by simon-mo** [comment]
Buildkite windows test are fine it ignore. Please use github action as source of truth.

**Comment by architkulkarni** [comment]
Ah thanks!  It passed on gh actions so we're good.
