### ISSUE TITLE
[Bug] Logs show memory resource requests as billions of gigabytes

### ISSUE THREAD

**Issue by Ha5hBr0wn** [ray-project/ray#21077]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

The docs on this page: [https://docs.ray.io/en/latest/memory-management.html#memory-aware-scheduling](url) seem to specify memory requirements in terms of bytes. 

Logs that appear during runs such as 
```
2021-12-14 09:09:54,160 WARNING worker.py:1245 -- The actor or task with ID ffffffffffffffff9469138bb3148c6114a5263a01000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
Required resources for this actor or task: {memory: 524288000.000000 GiB}, {CPU: 10.000000}
Available resources on this node: {8.000000/48.000000 CPU, 4325029640.039062 GiB/6422181640.039062 GiB memory, 2752363559.960938 GiB/2752363559.960938 GiB object_store_memory, 1.000000/1.000000 node:10.12.37.32}
```
put the units as GiB, which is confusing, as when I request 5GB it looks like in the logs that I requested 5 billion GB. So it seems that either the docs or the logs are incorrect in units (I am assuming its the logs)

Thanks

### Versions / Dependencies

Ray 1.9.0 

### Reproduction script

Launching a large machine learning job with individual actors as components, requesting memory resources, and manually terminating actors that finish to ensure progress (no deadlocks present). 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Tehada** [comment]
I made some research and it seems that problem happens [here](https://github.com/ray-project/ray/blob/92599d9127e228fe8d0a2d94ca75754ec21c4ae4/src/ray/common/task/scheduling_resources.cc#L192).

Initial amount in bytes hits this code:
```
return std::to_string(quantity * 50 / 1024) + " GiB";
```

and wrong conversion happens. Also it seems that previously this place had correct code according to [this commit](https://github.com/ray-project/ray/commit/d314d0c10eb7677ff6638d94118a2caeba9af419) (look at diff for `scheduling_resources.cc`).

**Comment by Tehada** [comment]
@Chong-Li can you help us with this change by your commit?

**Comment by clarkzinzow** [comment]
This should be fixed by [this PR](https://github.com/ray-project/ray/pull/21089), which has been merged into master.
