### ISSUE TITLE
[1.9.1 release] CI test "Setting up bootstrap env (ML)" failing consistently on release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21080]
Example: https://buildkite.com/ray-project/ray-builders-branch/builds/5157#d9ba05cb-fc05-4156-a90d-900e146c0574

```


fec81a2bd77c: Pushed
--
  | 92abf697be08: Pushed
  | 268270c5b9e9: Pushed
  | 555bed93e79f: Pushed
  | 6dd7bd2e77c5: Pushed
  | 9beb963d568f: Pushed
  | 9f54eef41275: Layer already exists
  | 6bcb35299c17e62c4611b12a985e0c211a00898d-ml: digest: sha256:05e846ce23eac8bc6bc61c4083ee7c94e6b6329baeee0567ef931139c812af2d size: 3054
  |  
  | real	6m24.220s
  | user	0m0.480s
  | sys	0m0.415s
  | ----------
  | cat: pipeline.ml.yml: No such file or directory
  |  
  | 73a1c552029c90d5a088dae9e5ee012536fff0ed450ff3d08f989d754d6d5030
  | ["RAY_CI_TUNE_AFFECTED", "RAY_CI_SGD_AFFECTED", "RAY_CI_TRAIN_AFFECTED", "RAY_CI_RLLIB_AFFECTED", "RAY_CI_RLLIB_DIRECTLY_AFFECTED", "RAY_CI_SERVE_AFFECTED", "RAY_CI_DASHBOARD_AFFECTED", "RAY_CI_DOC_AFFECTED", "RAY_CI_CORE_CPP_AFFECTED", "RAY_CI_CPP_AFFECTED", "RAY_CI_JAVA_AFFECTED", "RAY_CI_PYTHON_AFFECTED", "RAY_CI_LINUX_WHEELS_AFFECTED", "RAY_CI_MACOS_WHEELS_AFFECTED", "RAY_CI_STREAMING_CPP_AFFECTED", "RAY_CI_STREAMING_PYTHON_AFFECTED", "RAY_CI_STREAMING_JAVA_AFFECTED"]
  | jq: error (at affected_set.json:1): Cannot iterate over null (null)
  | 🚨 Error: The command exited with status 5
  | user command error: exit status 5


```

**Comment by architkulkarni** [comment]
@simon-mo is this just a Buildkite issue?  Should it be a release blocker?  It's still happening on the release branch for 1.9.1: https://buildkite.com/ray-project/ray-builders-branch/builds/5189#b108a72f-a077-4c8f-9e61-5f5c8f66473b

**Comment by simon-mo** [comment]
@krfricke can you please take a look? I don't think it's release blocking. This is just the new pipeline configured assume the existence of pipeline.ml.yml but 1.9.1 doesn't have it (totally fine).

**Comment by architkulkarni** [comment]
Ah gotcha, I didn't realize the pipeline configuration happened outside of the Ray repo (although it makes sense in retrospect why I couldn't find the string "setting up bootstrap env (ML)" in the Ray repo).  So I think there's no action needed here @krfricke, since this doesn't seem to be a problem on master
