### ISSUE TITLE
[Feature] Compatibility test for job submission 

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#21099]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We need to ensure to have proper tests of job submission import lib path to ensure we're not breaking compatibility.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Why is this a P0?

**Comment by simon-mo** [comment]
Hmm this shouldn't be P0 as no user is actively impacted by the lack of test at the moment. changing to P1

**Comment by jiaodong** [comment]
Yet it's not directly user impacting so not quite P0 of our OSS standard. Just for prioritization to land it earlier.

**Comment by edoakes** [comment]
this is merged
