### ISSUE TITLE
poor parallelism in the driver with multiprocess

### ISSUE THREAD

**Issue by CtfGo** [ray-project/ray#2109]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Centos release 6.3
- **Ray installed from (source or binary)**:binary
- **Ray version**:0.3.1
- **Python version**:2.7.14
- **Exact command to reproduce**:
start a new process simultaneously by multiprocessing.Process in the driver

### Describe the problem

I start a new process simultaneously by multiprocessing.Process in the driver to receive data and put into a queue communicating with the main process. However, it seems that the reception process and the main process use the same cpu because I found their cpu usage rate are mostly lower than 50%. What's more, if the reception process just receives data but does not put data into the communication queue so that the main process blocked by queue.get(), the reception process can take full advantage of the cpu and the usage rate is higher than 90%. My code is like the demo in the following. 

Is there a manager which will restrict resource used by the driver in Ray ? or some other global objects that need to be synchronized and shared among ray process so may cause this phenomenon ?Looking forward to a reply, thank you!

### Source code / logs

```
import multiprocessing
import ray

def receive_data(queue):
    while True:
        data = receive() #"reveive data from server"
        queue.put(data)

def run():
    queue = multiprocessing.Queue()
    reception_process = multiprocessing.Process(
            target=receive_data, args=(queue,))
    reception_process.start()
    while True:
        data = queue.get()
        handle_data() #"handle the data and train model"

if __name__ == "__main__":
    ray.init()
    run()
```

**Comment by robertnishihara** [comment]
Interesting, I don't think Ray should have any effect on the performance of multiprocessing in this case.

Your example fails for me with

```
Process Process-1:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-c73169d9d5d6>", line 6, in receive_data
    data = receive() #"reveive data from server"
NameError: name 'receive' is not defined
```

**Comment by CtfGo** [comment]
Sorry, it is a trivial example that just shows the logic of my code.
