### ISSUE TITLE
[1.10.0 Release] Core Scalability and Nightly Tests failing with mismatched Ray commits

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21096]
See https://buildkite.com/ray-project/periodic-ci/builds/1954# and https://buildkite.com/ray-project/periodic-ci/builds/1953, about 10 tests failed at the app config step.  Clicking into the app config build, we see

```
[INFO] 12/14/2021, 1:14:40 PM: * Pushing with cache ID bfc80e7b
[INFO] 12/14/2021, 1:14:40 PM: Client TLS is disabled
[INFO] 12/14/2021, 1:14:40 PM: * Step 9/10 (commit,modifyfs) : RUN python -c 'import ray; assert ray.__commit__ == "8325a32d664d84dc7034753df1b55066461562e7", ray.__commit__'  (c4be50d3)
[INFO] 12/14/2021, 1:14:40 PM: Client TLS is disabled
[INFO] 12/14/2021, 1:14:40 PM: * Started pushing layer sha256:a8bed5949a49cb7f0df92c80ff906207232f3913a62e2d7dd792ae8dbb712ccc
[INFO] 12/14/2021, 1:14:40 PM: Client TLS is disabled
[ERROR] 12/14/2021, 1:14:40 PM: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: 8a943e8081ff4ee505d0fae3bdbb75ff208821de

[ERROR] 12/14/2021, 1:14:40 PM: Command exited with 1
```

**Comment by architkulkarni** [comment]
These two commits are a couple of hours apart.  I'll downgrade it to P1 because it looks like some edge case with the timing, hopefully it gets fixed by re-running the tests.

**Comment by architkulkarni** [comment]
This happened on the last two nightly tests.  Restarting the test didn't fix it, example: https://buildkite.com/ray-project/periodic-ci/builds/1961#71ad71bc-351d-4947-ab85-6a92cfb1df2f

I think we should upgrade the priority again because I could see it delaying the release if we can't get the tests to pass by restarting.  @krfricke I'm not sure who to assign this to, could you please help find an owner for this issue?

**Comment by clarkzinzow** [comment]
@architkulkarni @krfricke I'm on-call for the core team, let me know if y'all need any assistance with this!

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/21119.

**Comment by architkulkarni** [comment]
This is still happening on the nightly release tests: https://buildkite.com/ray-project/periodic-ci/builds/2010#_

Here's one example: https://buildkite.com/ray-project/periodic-ci/builds/2010#9b766a9a-5eff-4518-b02e-dc0ad8658122/138-215

This points to a failed app config build, with the traceback
```
[ERROR] 12/17/2021, 2:08:07 AM: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: 85a368c720a5d5b6820eaf7960d6e9687277dd78
```
from 
```
python -c 'import ray; assert ray.__commit__ == "02465a6792ff625ceea60dae4ef3cbcb895ee083", ray.__commit__'
```

It looks like it's using a cached failed app config:
```


[INFO 2021-12-17 10:04:40,448] e2e.py: 798  Test uses an app config with hash prj_2xR6uT6t7jJuu1aCwWMsle-065f156b46d934eec43f528c47a28434816cb5465533b79fd93cbba7d6ab8d56. Looking up existing app configs with this name.
--
  | [INFO 2021-12-17 10:04:54,108] e2e.py: 811  App config already exists with ID apt_hdUqPS46iJnGtmPULgVjcTzt
  | [ERROR 2021-12-17 10:04:54,369] e2e.py: 1684  App config build failed.


```

  Is there a way to clear the cache and force it to build a new app config?

**Comment by architkulkarni** [comment]
Actually, maybe we just need to propagate the fix from https://github.com/ray-project/ray/pull/21119/files to the other app configs.
