### ISSUE TITLE
[Feature][runtime env] add a DebugString and print the ref stats

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#21108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Reference the comment https://github.com/ray-project/ray/pull/20789#issuecomment-985303094.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I will set this P1. Good observability must be the necessary for all features as we've been having hard time debugging when issues coming up.

**Comment by rkooo567** [comment]
IF there's a better way to implement observability in runtime environment, I'd love to hear the idea!

**Comment by SongGuyang** [comment]
@rkooo567 Make sense. I will add this with a high priority.
