### ISSUE TITLE
[Release 1.9.1] impala test failing consistently on release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21116]
Example: https://buildkite.com/ray-project/periodic-ci/builds/1945#0deaa5c7-da74-4507-913d-109712915efe

There's a memory error:
```
Memory usage on this node: 29.7/30.9 GiB: ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.
```

**Comment by architkulkarni** [comment]
@amogkam I think this happened for 1.9.0 as well.  What should we do, should we ignore this test for the release, or do we need some sort of fix?  Or should I keep rerunning it?

**Comment by amogkam** [comment]
@architkulkarni is this using the test from master?

**Comment by architkulkarni** [comment]
No, the test infrastructure and test suite are both from the release branch

**Comment by architkulkarni** [comment]
Should I cherry pick something to fix this?  I'm worried that running the master test suite against an older release will give noisy results, but maybe I should do it anyway

**Comment by amogkam** [comment]
ah got it, then you would need to pick this commit https://github.com/ray-project/ray/pull/20691
