### ISSUE TITLE
[1.9.1 Release] pg_long_running_performance_test failing consistently on release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21118]
Example: https://buildkite.com/ray-project/periodic-ci/builds/1947#e99e8276-f045-4aaa-94ea-374ba7177a5e/139-396

```


Traceback (most recent call last):
--
  | File "placement_group_tests/long_running_performance_test.py", line 144, in <module>
  | main()
  | File "placement_group_tests/long_running_performance_test.py", line 110, in main
  | assert (ray.cluster_resources()["custom"] >= NUM_PG_AT_EACH_STAGE * 4)
  | AssertionError


```

**Comment by architkulkarni** [comment]
@rkooo567 Not sure about the priority of this one.  I see it's marked with `stable: false`, does that mean I should completely ignore it for the release, or should I keep restarting until it passes?  It failed the last 4 times.

**Comment by rkooo567** [comment]
The error is not related to the test. When did you do branch cut? This test has been pretty stable for a while

**Comment by architkulkarni** [comment]
This is for 1.9.1, not 1.10.0.  So it's just the 1.9.0 branch plus the log4j fix and a version bump commit.

**Comment by architkulkarni** [comment]
1.9.0 branch cut was Nov 16.  Should we just ignore this test for the 1.9.1 release?

**Comment by rkooo567** [comment]
Let me see if I can find cherry pick for you actually

**Comment by rkooo567** [comment]
Oh it is for 1.9. Let’s ignore in this case
