### ISSUE TITLE
Supporting Airspeed Velocity

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2112]
In general, regarding Airspeed Velocity (regression testing) - In order to run and log a benchmark, suite it will build by calling `setup.py develop` from the root directory (where `.git` resides). A few complications arise here:
  - `setup.py` for `ray` does not sit in the root directory
  - building from source can take a while, especially given that we already have wheels built and pushed to s3. 

There’s a couple workarounds (ie, having a separate benchmarking repository) but would be nice to hear thoughts.

## Plan:

- [x] Get an initial commit for ASV into the repo (#2113). This will only support `asv dev`.
- [x] Setup ASV so that build functionality is not completely encapsulated in `asv run`. This may require forking ASV into `ray-project`.
   - [x] Include a `machine.json` in Docker so that asv can run without input

3. Get a full docker + ASV pipeline working
 - [x] Expose Env Vars in Docker
 - [x] Push results to a proper directory structure in S3
 - [x] Make sure visualization works correctly (right now only visualizes one commit)

Optimizations:
 - [ ] Make the jenkins build faster

cc @robertnishihara @pcmoritz

**Comment by pcmoritz** [comment]
Arrow has the same configuration as ray with respect to having setup.py in `python/` and they got asv working: https://github.com/apache/arrow/blob/master/python/asv.conf.json

**Comment by robertnishihara** [comment]
Let's not use asv to build Ray (at least for now). I don't even think Arrow does that though I could be wrong.

Let's assume that Ray is already installed and just use asv to run the tests (visualize the results).

**Comment by pcmoritz** [comment]
It might be that arrow actually uses a fork of asv, see here: https://github.com/apache/arrow/blob/db036630021fc8334ea29a3a3dcff01a206ac517/python/README-benchmarks.md

**Comment by pcmoritz** [comment]
and here: https://github.com/apache/arrow/blob/db036630021fc8334ea29a3a3dcff01a206ac517/python/doc/Benchmarks.md

**Comment by richardliaw** [comment]
RE: Arrow

1. Yeah, they use a fork of asv
2. Arrow's ASV builds Arrow from what I can tell...:
  - the suspected line in the config is here:
https://github.com/apache/arrow/blob/master/python/asv.conf.json#L38
  - they had to augment ASV (hence the fork) like this:
https://github.com/airspeed-velocity/asv/compare/airspeed-velocity:92c072a...pitrou:07b1911#diff-8a99b546f3845ff961c3b98258ccd635R44
  - And the script that they run for building is this, which I think builds
Arrow... https://github.com/apache/arrow/blob/master/python/asv-build.sh

If you want to assume Ray is already installed, and just run the test, we
will need to fork ASV (and modify something like this line
https://github.com/airspeed-velocity/asv/blob/92c072a9c476d9338ff4f5bf20d90030c09d4872/asv/commands/run.py#L296
).

Thoughts?

Richard

**Comment by richardliaw** [comment]
@pcmoritz @robertnishihara is there some way of making sure the `ray.tar` being put into the docker has the `.git` folder?

**Comment by richardliaw** [comment]
Done via #2246 and #2304
