### ISSUE TITLE
[Bug] [runtime env] "conda" field fails to install with M1 cluster

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21123]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

If the Ray cluster is running on an M1 Mac, then when the runtime env agent tries to create a conda environment, it injects the wrong Ray dependency into the conda env.  (It inserts the wheel URL that uses the wheel for non-M1 macs).

This causes
```
EnvException: Pip failed
(pid=runtime_env) 2021-12-15 15:02:48,527	INFO conda_utils.py:198 -- 
Traceback (most recent call last):
 File "/Users/shrekris/Desktop/fname.py", line 15, in <module>
  assert ray.get(f.remote())
 File "/Users/shrekris/miniforge3/envs/ray19/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
  return func(*args, **kwargs)
 File "/Users/shrekris/miniforge3/envs/ray19/lib/python3.9/site-packages/ray/worker.py", line 1715, in get
  raise value
ray.exceptions.RuntimeEnvSetupError: The runtime_env failed to be set up.
(raylet) [2021-12-15 15:02:50,369 E 10467 2401112] agent_manager.cc:190: Failed to create runtime env: {"_ray_commit": "92599d9127e228fe8d0a2d94ca75754ec21c4ae4", "conda": {"dependencies": ["pip", {"pip": ["pip-install-test==0.5"]}]}}, error message: Failed to install conda environment /tmp/ray/session_2021-12-15_15-02-00_234536_10411/runtime_resources/conda/aa958e4ea4f7080354413b6d2cb9214637aa7044:
(raylet) ERROR: ray-1.9.0-cp39-cp39-macosx_10_15_x86_64.whl is not a supported wheel on this platform.
(raylet) 
(raylet) Ran pip subprocess with arguments:
(raylet) ['/tmp/ray/session_2021-12-15_15-02-00_234536_10411/runtime_resources/conda/aa958e4ea4f7080354413b6d2cb9214637aa7044/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/ray/session_2021-12-15_15-02-00_234536_10411/runtime_resources/conda/condaenv.0ff6dfcv.requirements.txt']
(raylet) Pip subprocess output:
(raylet) 
(raylet) failed
(raylet) 
(raylet) CondaEnvException: Pip failed
(raylet)
```

### Versions / Dependencies

Ray 1.9

### Reproduction script

```
import ray

ray.init()

runtime_env = {"conda": {"dependencies": ["pip", {"pip": ["pip-install-test==0.5"]}]}}


@ray.remote(runtime_env=runtime_env)
def f():
    import pip_install_test

    return True


assert ray.get(f.remote())
```

### Anything else

Since we don't have M1 wheels for nightlies, for now we should just try to fix this for the stable releases.  Having a cluster of M1 macs is probably uncommon, but running Ray locally on an M1 laptop will become increasingly common.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@architkulkarni Could you assign a priority to this issue and remove the "triage" label?

**Comment by architkulkarni** [comment]
Since M1 wheels are not uploaded to AWS, we'll need to `pip install ray=={ray.__version__}` for M1 wheels instead of doing `pip install http://ray-wheels.aws..../{ray_commit}"` as we do for other wheels.  The downside of this is it will only work for PyPI released versions of Ray (so it won't work for nightlies.)
