### ISSUE TITLE
[Bug] Ray always crashes when using a lot of actors/tasks

### ISSUE THREAD

**Issue by Ha5hBr0wn** [ray-project/ray#21135]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I am using Ray to run large machine learning workflows in a distributed fashion. My runs spawn thousands of actors and tasks and often crashes Ray. 

The following messages is frequently displayed:

`(raylet, ip=XX.XX.XX.XX) [2021-12-16 08:45:49] core_worker.cc:451: Failed to register worker db5e2ab8f60a689af44fe79 to Raylet. Invalid: Invalid: Unknown worker`

When this message shows up the job doesn't crash but some of the results seem to not come out. 

I specify resources for my actors and tasks and exit actors when they finish to ensure forward progress. Additionally the cluster I am on has 500 machines and 30,000 cores so it is not unrealistic to handle large workloads. 

Sometimes just restarting the cluster and rerunning the job works.

What is this message (it is not very descriptive)? And how can I run larger jobs without them always crashing?

### Versions / Dependencies

Ray 1.9.0

### Reproduction script

Just launch a large job (thousands of actors consuming maybe 20 GB each) but exiting once they are done (no deadlocks)

### Anything else

Problem occurs very often and is crippling productivity

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by addisonklinke** [comment]
@Ha5hBr0wn did you end up finding a solution or PR which fixed the issue?

**Comment by Ha5hBr0wn** [comment]
Yes, thanks for checking. I wasn't running within our SLURM cluster environment causing resources to be overallocated between my jobs and others hence the crashes.
