### ISSUE TITLE
[Bug] Please trigger new release after log4j fix

### ISSUE THREAD

**Issue by KristianHolsheimer** [ray-project/ray#21150]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I'm getting vulnerability notifications because one of my packages has a dependency on an old of log4j via Ray.

The log4j was already bumped up in `master` in #21081 

Please could you trigger a new release without the log4j lookup vulnerability?

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @architkulkarni

**Comment by architkulkarni** [comment]
This is being tracked here: https://github.com/ray-project/ray/issues/21055. We're currently going through the release process for `ray==1.9.1`.
