### ISSUE TITLE
[RFC] Job queueing functionality with Ray Serve + Workflows

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#21161]
## Overview

A number of users have raised the desire for a native Job queue within Ray, which can provide:
- persistence (guarantee that tasks aren't lost due to failures)
- rate limiting (limit the number of concurrently executing tasks in the cluster)
- integration with online serving / event sources (e.g., Serve, SQS)
- Ray integration (use Ray as the execution layer)

This aligns well with the combination of Serve + the Workflows project (https://docs.ray.io/en/latest/workflows/concepts.html), with a few enhancements. In particular, Workflows needs to:
- support rate limiting. The simplest version would be something like `workflow.init(max_concurrent_jobs=100)`.
- support some API to query/list the queue of pending workflows (perhaps extending the metadata API: https://github.com/ray-project/ray/pull/20156).

## Reference Architecture

The following proposes a reference architecture for supporting Job queueing in Ray, with support for querying job status and integration with serve & event sources.

At a high level, it is composed of a few parts:
1) A Serve deployment that can take incoming Job execution requests and Job status query requests.
 - Each job is launched as a separate Ray workflow, with an incrementing workflow id.
 - Workflows will run as many concurrent jobs as possible given its concurrency limit, ordered by workflow id.
 - Workflows can be queried for the status of any given workflow and general queue stats.
2) A workflow that runs in the background polling events from an event bus, e.g., SQS.
 - When an event is received, it launches a workflow to process the event and acks the event.

![flow](https://user-images.githubusercontent.com/14922/146613701-ce9a66b5-1f65-4223-bf7e-4c64314892fa.png)

## Discussion
*Fault tolerance*:
- Each workflow is durably persisted to workflow storage, and automatically retried on failure while the cluster is running.
- When the cluster restarts, the Serve deployment is re-launched, and this calls `workflow.resume_all()` on startup to resume interrupted jobs.

*Scalability*:
- This architecture should scale to many thousands of pending jobs. Further scalability to millions of pending jobs requires adding an index to the workflows storage.
- The size of each job can be arbitrarily scalable (e.g., use thousands of cores) since it's just running in Ray.
- The latency per job is several hundreds of milliseconds, due to the storage choice of Workflows. This should be low enough for Ray-based compute jobs, but can be optimized in the future with faster Workflow storage plugins.

## Status

Currently, this project is in discussion and we want to gather further feedback from the community. Should we proceed, most of the work involves adding operational features to workflows and examples:

P0:
- [ ] Add rate-limiting support to workflows
- [ ] Add index to workflows to support more queued / total jobs

P1:
- [ ] Add metadata query functionality to workflows
- [ ] End-to-end application example with Ray Serve + Workflows, and blog post
- [ ] Nightly scalability tests

cc @simon-mo @iycheng @edoakes @anabranch @yiranwang52

**Comment by mbehrendt** [comment]
thx a lot for putting together this proposal @ericl .

One topic we should drill into a bit more is the persistence layer, and what to persist. E.g. storing execution metadata and potentially other data can become stressful for the underlying persistence technology. What's your thinking around this?

**Comment by rkooo567** [comment]
This document also could be useful for feature comparison? https://docs.google.com/spreadsheets/d/1Q_v__QtYzDtIDOkfmeQqVAw_jiksBz-GbJn-m-pDM34/edit#gid=0

**Comment by ericl** [comment]
> One topic we should drill into a bit more is the persistence layer, and what to persist. E.g. storing execution metadata and potentially other data can become stressful for the underlying persistence technology. What's your thinking around this?

Currently, workflows supports filesystem and S3-based persistence. This is relatively high latency (~100ms+ per operation), but very scalable. Once we add an index, this should also scale nicely for very large queues of jobs.

**Comment by ericl** [comment]
Also cc @pcmoritz

**Comment by amogkam** [comment]
Would this support job prioritization or dynamic resources for each job?

For example, I have a long-running training job and want it to use all the resources in my cluster. But if a higher priority job comes in, I want to move some of my resources from the training job to the new high priority job. Assume that the training job can natively handle scaling down/up without having to restart training.

**Comment by ericl** [comment]
> Would this support job prioritization or dynamic resources for each job?

Great question. In the RFC we only have support for rate limiting. Supporting prioritized jobs / multiple queues of different types of jobs would be the next obvious extension [P1].

**Comment by mbehrendt** [comment]
> > Would this support job prioritization or dynamic resources for each job?
> 
> Great question. In the RFC we only have support for rate limiting. Supporting prioritized jobs / multiple queues of different types of jobs would be the next obvious extension [P1]. Though we may need to add features to Ray to support prioritization of existing running jobs.

would be interesting to have this guided by use cases. in a certain way, prioritization of work is/was driven by hard constraints in terms of capacity. when running on a cloud, there is still a quota set for an account, but in general there is much more freedom wrt allocating new capacity as needed, and also take alternative approaches, which would be interesting to think through. E.g. instead of having to make prioritization trade-offs within Ray, there is also the option of just spinning up another ray cluster, for workloads of a different priority. with that it could also be ensured (even more strongly) that low and high-priority work don't step on each other, but would avoid the need for implementing complex cluster-internal prioritization logic.

WDYT?

**Comment by ericl** [comment]
That's a great point. Indeed taking a step back prioritization can be
solved at a higher layer for most use cases, so there isn't a strong need
to support that within a cluster beyond simple rate limiting.

**Comment by jacobdanovitch** [comment]
Rate limiting for workflows would be really helpful, currently struggling a bit to setup a workflow where we have to call an API at a certain rate per second.

**Comment by ericl** [comment]
Interesting nuggets on Ray for job processing from this blog: https://vishnudeva.medium.com/scaling-applications-on-kubernetes-with-ray-23692eb2e6f0

> But as good as my experience was using Ray for ML, I didn’t really consider using it to offload job processing for a web application when the need arose. There was no need because there’s no dearth of dedicated software available to process jobs: Celery, RQ (Redis Queue), Kubeflow Pipelines (KFP), Airflow, Volcano, and more.

> However, what I actually found out was that while solutions like Celery and RQ allowed for low-latency job processing, they needed a dedicated team to build and maintain a layer of infrastructure on top that would allow for more complex functionality — worker-aware scheduling, GPU support, etc.

> But with the unpredictable overhead of Kubernetes scheduling, we pretty much need to forget about low latency processing for our jobs, which is not an option when your goal is to enable near real-time use-cases.

This echoes other use cases for Ray as a unified & high-performance processing backend.

**Comment by jon-chuang** [comment]
re: job prioritization
related: https://github.com/ray-project/ray/issues/2618 https://github.com/ray-project/ray/issues/16782

**Comment by jon-chuang** [comment]
Recommend this [very informative and relevant talk](https://www.youtube.com/watch?v=oZl-D4zsW6E) on preemption and packing of jobs for **Nomad**, a low-latency, lightweight cluster orchestration tool based on distributed scheduling via Sparrow, made by Hashicorp.

Key takeaways:
- (named) task groups and priority levels (very related in my mind also to observability, task tagging, and task graph visualization)
- Both intra-node and inter-node preemption via greedy and approximate heuristics
    - In the context of Ray, preemption decisions also need to be made on the basis of the availability of object store inputs on various candidate nodes
- Observability for live and historical preemption and scheduling decisions

Additional thoughts:
- Thinking about the design of low-latency systems like ScyllaDB which still run heavy background tasks like analytic workloads and database compaction in the same cluster, use of (fine-grained) priority levels and priority groups for online and offline tasks is a very common practice when latency is a concern. 
    - I think there is something to consider here given that one of the strong selling points of Ray is its ability to provide low-latency task execution. In exploring Ray as a more general purpose system that allows for vertically integrating other types of compute alongside ML workloads, I believe multi-tenancy, sharing the same dataplane, managing a single-cluster with multiple job groups with different latency requirements, are just some of the important capabilities to investigate.

**Comment by jon-chuang** [comment]
Another use case for priority scheduling: prioritizing bottlenecked tasks: https://github.com/apache/arrow-datafusion/issues/1221#issuecomment-1013068782

**Comment by ddelange** [comment]
> persistence (guarantee that tasks aren't lost due to failures)

What is the current state of persistence/recovery (can someone point me to docs/issues)? Will the requirements of persistence be tracked under this RFC?

Take for instance the scenario where both ray-operator and the head pod are scheduled on a spot instance, that spot instance gets unexpectedly killed, and these pods are restarted on another node (I guess this scenario is also relevant outside the Serve/Workflows context).

- What happens to jobs that had already finished but are still needed?
- What happens to jobs that were currently being processed (worker panic)?
- What happens to jobs that were still in the queue?

**Comment by thatcort** [comment]
What sort of execution guarantee are you aiming to provide? Exactly once? At least once?

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！

**Comment by richardliaw** [comment]
I believe this proposal is being superseded by https://github.com/ray-project/ray/issues/32292.

Please comment there to voice your support + vote on which option is better for your use case! We are looking for more signals.
