### ISSUE TITLE
[Bug] After train, when I test the environment, the range of action exceeds action_space

### ISSUE THREAD

**Issue by zhou-ting-hub** [ray-project/ray#21169]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

action = trainer.compute_single_action(obs)
Is this tested by the model trained? If not, what should I test with the trained model? If yes, why the range of action of trained results is in the range of 0 to 1, But the range of action of test results  exceed the action_space?
![111](https://user-images.githubusercontent.com/80151423/146628559-e79868a1-7f48-4725-8346-d9cc6cf9bd01.png)

        self.action_space = spaces.Box(
            low=0, high=1, shape=(4,))
        # Prices contains the OHCL values for the last five prices
        self.observation_space = spaces.Box(
            low=-1, high=1, shape=(13,))

### Versions / Dependencies

rllib python pytorch

### Reproduction script

obs = env.reset()
done = False
total_reward = 0.0
while not done:
    # Compute a single action, given the current observation
    # from the environment.
    action = trainer.compute_single_action(obs)
    # Apply the computed action in the environment.
    obs, reward, done, info = env.step(action)
    print(f'obs: {obs}')
    print(f'action: {action}')
    env.render()
    total_reward += reward
print(f"Shreaked for 1 episode; total-reward={total_reward}")

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @zhou-ting-hub , thanks for filing this issue! Could you provide a single, self-sufficient, working reproduction script. Only with that can we properly debug your issue. Thanks :)

**Comment by gjoliver** [comment]
consolidating this issue to https://github.com/ray-project/ray/issues/23074
