### ISSUE TITLE
[Datasets] Ensure Datasets + Ray Client test coverage.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#21180]
We should make sure that Datasets works correctly with Ray Client. The easiest route would be using a fixture for every Datasets test that runs two versions of the test: one with normal Ray, and one with Ray Client.

**Comment by AmeerHajAli** [comment]
Hi @clarkzinzow , thanks for filing this. I am not sure what is the current prioritization for Datasets relative to other work, but I think this sounds like Datasets cannot be E.g. in Alpha/Beta without working with Ray Client. It seems to me like a P0 for Datasets (not sure what is the priority relative to other work and thus I’d refer to @ericl / @scv119)

**Comment by clarkzinzow** [comment]
@AmeerHajAli This issue is just for adding Ray Client test coverage; as I mentioned in the other issue, any reproducible issues with Datasets + Ray Client would be a P0/interrupt.
