### ISSUE TITLE
[Feature] [xlang/C++ API] Interop of `msgpack::sbuffer`/FFI-safe buffer and `LocalMemoryBuffer`

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Generally, this fits into the larger picture of xlang and FFI:
- We want an FFI-compatible buffer (e.g. `sbuffer`, but hopefully something more serialization format-independent)
- We don't want to needlessly copy data to and from Ray core runtime's buffer interface (`LocalMemoryBuffer`). So, one might want interop via transferring ownership (i.e. responsibility for freeing allocated memory) in the underlying buffer.
  - However, since the data copied in this way tends to be small, this may not have impact, may need some advice here
  - One must make sure both sides know how they are allocating/deallocating the data (libc::malloc?, alignment)
- Other related topics: zero-copy deserialization, `RaySerialization`, xlang-compatible serialization frameworks/formats like protobuf, flatbuffer (and perhaps Fury...?)

### Idea
Have a simple C-ABI compatible buffer that uses libc::malloc and libc::free and suitable common alignment
- Considerations:
  - Even if you cannot pre-allocate a fixed-size buffer for serialization, and may need a scratch space for dynamic sized serialization, and thus a copy; an ownership transfer or custom deallocation callback would at least save on deserialization copy.

### Use case

Better interop, perhaps fewer copies

### Related issues

https://github.com/ray-project/ray/issues/20372

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
> but hopefully something more serialization format-independent

What's serialization format-independent?

> We don't want to needlessly copy data to and from Ray core runtime's buffer interface (LocalMemoryBuffer). So, one might want interop via transferring ownership (i.e. responsibility for freeing allocated memory) in the underlying buffer.

Do you mean we shouldn't copy a rust layer buffer to LocalMemoryBuffer right? This is a good idea. We've been suffering it for a long time in Java worker.

> Have a simple C-ABI compatible buffer that uses libc::malloc and libc::free and suitable common alignment
I don't know if it's a good idea to have a common interface compatible buffer yet.

**Comment by jovany-wang** [comment]
For a short term plan, you can add a `SBuffer` extending from ray::Buffer make `msgpack::sbuffer` as your object_allocator.
