### ISSUE TITLE
[1.10.0 Release] Scalability tests `many_actors`, `many_tasks`, `many_pgs`, `many_nodes` all failing on master

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21203]
E.g. Smoke test: https://buildkite.com/ray-project/periodic-ci/builds/2038#af8e223c-5c35-41a3-b079-9cf629e424a8

Full tests: https://buildkite.com/ray-project/periodic-ci/builds/2042

It failed the last two times, but there was a period of infra failures before that, so it's possible it's a regression.  The errors are all the same so I'm grouping these together.

```python-traceback
Traceback (most recent call last):
--
  | File "distributed/test_many_pgs.py", line 76, in <module>
  | test_utils.wait_for_condition(no_resource_leaks)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/test_utils.py", line 326, in wait_for_condition
  | raise RuntimeError("The condition wasn't met before the timeout expired.")
  | RuntimeError: The condition wasn't met before the timeout expired.
```

**Comment by architkulkarni** [comment]
@wuisawesome Can you please take a look and downgrade the priority if it's not a regression or shouldn't be a release blocker?

**Comment by architkulkarni** [comment]
Actually, not just the smoke tests are failing, the full tests are failing too: https://buildkite.com/ray-project/periodic-ci/builds/2042

**Comment by architkulkarni** [comment]
@clarkzinzow can you help find an owner for this?  "Resource leaks" sounds pretty bad, but could it possibly just be an issue with the test script?

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/issues/21203 -> This should fix it

**Comment by rkooo567** [comment]
Just merged. Can you cherrypick and test it again?

**Comment by architkulkarni** [comment]
Thanks!  We haven't done the branch cut yet, so nothing to cherry pick for now.  Once the wheels are ready for that commit in buildkite (~1h), I will manually run the Core scalability test and report back.  If it looks good I'll make the branch cut for 1.10.0.

**Comment by architkulkarni** [comment]
Test in progress here: https://buildkite.com/ray-project/periodic-ci/builds/2045

**Comment by rkooo567** [comment]
Seems to pass
