### ISSUE TITLE
Public Helm Repository for Ray Chart

### ISSUE THREAD

**Issue by eytanhanig** [ray-project/ray#21206]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

For the past 7 months [Ray's Helm documentation](https://github.com/ray-project/ray/blob/master/doc/source/cluster/kubernetes.rst#installing-the-ray-operator-with-helm) has stated "The chart will be published to a public Helm repository as part of a future Ray release."

There is no better time than now to create a public Helm repository and publish Ray's chart to it, especially since many tools touted as alternatives to Ray already offer this.

### Use case

Many companies use continuous deployment for Helm charts which, in the case of many tools, requires that a Helm chart already be present in a Helm repository. Even for those that can reference charts in GitHub directly, such as Argo CD, having the Ray chart in a Helm repository is necessary when attempting to use it as a dependency chart.

An example of this is how my company, Womply, wishes to avoid maintaining our own copy of the Helm chart while at the same time wanting to deploy [External Secrets](https://github.com/external-secrets/kubernetes-external-secrets) objects alongside it, which we would normally do by referencing the public Helm chart as a dependency and then adding additional YAML templates on top of it.

It is worth noting that tools often mentioned as Ray alternatives, such as Dask and Spark, already offer public Helm repositories, and that ease of deployment does influence which tool is adopted at companies actively evaluating them.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by eytanhanig** [comment]
A simple implementation for this is to [use GitHub pages to host Helm charts](https://helm.sh/docs/howto/chart_releaser_action/). This method is so widely followed that the official Helm project even offers a [Chart Releaser Action for GitHub](https://github.com/marketplace/actions/helm-chart-releaser).

Normally I'd offer to open a PR for this, however the majority of the work will require intervention by a repository Admin.

**Comment by DmitriGekhtman** [comment]
Thanks for posting the issue.
As the docs claim, it's on our to-do.

cc @pcmoritz @zhe-thoughts @richardliaw

**Comment by richardliaw** [comment]
This is now done: https://github.com/ray-project/kuberay/issues/475

**Comment by DmitriGekhtman** [comment]
Thanks, Richard! Technically, it will be officially done with the next stable KubeRay release (0.4.0), since we've just worked out the Helm release strategy after the last release (0.3.0).
