### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ze897c** [ray-project/ray#21202]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Dashboard

### What happened + What you expected to happen

Folks: was using ray via python very successfully until, maybe?, I switched to the experimental dashboard, although this seems to make very little sense to me.

Not sure if I have tracked this down well at all, but it FEELS like ray breaks for me after switching to the experimental dashboard. I could perhaps validate this (somewhat) if I could delete/edit config to force the dashboard back to the stable version. Maybe in the redis cache...? Any help would be fantastic: happy to dig in more, but would need a direction to look. Thanks All.

"""
(pid=93804) 2021-12-05 14:44:32.742 python[93804:2522960] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:363
(pid=93804) 2021-12-05 14:44:32.744 python[93804:2522960] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:363
(pid=93807) 2021-12-05 14:44:32.740 python[93807:2522941] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:363
(pid=93807) 2021-12-05 14:44:32.743 python[93807:2522941] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:363
....
"""

### Versions / Dependencies

osx: Big Sur 11.6
python: 3.8.12
ray.version: 1.9.0
java: "1.8.0_201"
...what am I missing?

### Reproduction script

I am unable to give a reproduction script: was working fine until recently.

### Anything else

Problem now repeats always.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Hmm what do you mean by “switching to experimental dashboard”? Experimental dashboard cannot be the default option now afaik, so it doesn’t make much sense to me what this means.

**Comment by ze897c** [comment]
Agreed: does not make sense to me either. As I said, I could not actually diagnose the issue. What I meant was that I toggled the experimental dashboard view from the main page of the 'classic' dashboard.

My behavior is that Ray no longer works, and code that previously functioned now hangs, and fill up the terminal with endless stream of 

```
(pid=93807) 2021-12-05 14:44:32.743 python[93807:2522941] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], NSUndoManager.m:363
```

I tried re-installing, and still get the same behavior. I am not using java, so also unclear on (what appears to be) java errors. I am stumped, and would love any ideas for how to debug/fix.

Thanks.

**Comment by rkooo567** [comment]
How do you initialize ray? Are you using ray startv

**Comment by ze897c** [comment]
```
import ray
ray.init()
```

**Comment by rkooo567** [comment]
Tbh, I never saw this issue, and it is very unlikely this is related to the dashboard. But let’s try from disabling it? You can do ray.init(include_dashboard=False)

also can you share the full logs of those pid with assertion failures? In /tmp/ray/session_latest/ray/logs, there must be files that correspond to the pid that have assertion failures

**Comment by ze897c** [comment]
Happy to. Will take me a bit here

**Comment by ze897c** [comment]
[logs.zip](https://github.com/ray-project/ray/files/7763732/logs.zip)
...sorry for the delay, had to get back to the correct box
