### ISSUE TITLE
[Feature] [Jobs] Add `list_jobs` api back after Job submission

### ISSUE THREAD

**Issue by xychu** [ray-project/ray#21209]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Hi team, seems the job list api got removed after Job submission added, any plan to add this back?
![ray-jobs-404](https://user-images.githubusercontent.com/936394/146853909-1e21e31f-fe50-4c9d-a66e-eaa997d2edf1.png)

### Use case

1. list all the jobs that from job submission
2. list all the remote tasks in current ray cluster
3. if possible, it would be nice to have some kind of label/filter on list_jobs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vicyap** [comment]
Hi, is there a workaround to list jobs? Is there a way to list job ids?
