### ISSUE TITLE
Use scoped enums in C++ and flatbuffers.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2121]
We should replace all instances of `enum` with `enum class`. Also, we should generate scoped enums from flatbuffers using `--scoped-enums` (see https://github.com/google/flatbuffers/blob/master/docs/source/Compiler.md).

**Comment by guoyuhong** [comment]
I'm working on this.

**Comment by robertnishihara** [comment]
I believe this has been fixed now.
