### ISSUE TITLE
[RFC][Java] Track topics on Java worker and APIs for Ray2.0

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21220]
This issue is used to track the topics of Ray Java worker and APIs for Ray 2.0 .

Some topics are listed below:
- Should we use 1 module instead of api module and runtime module?
- Should we remove the local mode code path?
- Should we remove multiple actors in one process?

### Java API Changes In 2.0
1. APIs related multiple worker instance in one process
  #24147 
  #23973
- [D]Ray.wrapRunnable
- [D]Ray.wrapCallable
- [D]Ray.getAsyncContext
- [D]Ray.setAsyncContext

3. Run-mode enum value: SINGLE_PROCESS to LOCAL #24679

4. Move exception classes to API module #24540

**Comment by jovany-wang** [comment]
@kfstorm @raulchen

**Comment by kfstorm** [comment]
I'm in favor of yes, yes, and yes.

**Comment by jovany-wang** [comment]
After discussed with @chenk008 offline, once local mode get removed, maybe we can package `libcore_worker.so` to wheel instead of jar, so that we have no need to extract it from jar to disk.

**Comment by jovany-wang** [comment]
Another one is once we support specifying jars for runtime-env, is it the time to remove code-search-path?
@chaokunyang @SongGuyang @chenk008

**Comment by SongGuyang** [comment]
Yep, I agree that we should remove code-search-path and merge this feature to runtime env. Let's think about how to support.

**Comment by raulchen** [comment]
> Should we use 1 module instead of api module and runtime module?

What's the problem with having 2 separate api and runtime modules?

> Should we remove the local mode code path?

I prefer removing. But we should probably make it consistent for other languages. Maybe you can open a separate issue to get more inputs from other people.

> Should we remove multiple actors in one process?

Yep, we should move the multi-actors feature as a util lib. You can open a new issue for this.

**Comment by kfstorm** [comment]
Should we push forward about merging the api and runtime modules?

**Comment by jovany-wang** [comment]
The benefits of merging api module and runtime module are:
- Avoiding too many reflection invocations.
- We now have only one implementation, it's unnecessary to introduce a runtime module in principle.
- It also could reduce the LOC.

Disadvantages：
- It's a break change.
- ?

I prefer to merge them, but I don't know the concerns from @raulchen .
