### ISSUE TITLE
[Bug] Flaky `ray_cpp_pkg` build cmd

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21238]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Others

### What happened + What you expected to happen

The ray_cpp_pkg build cmd is flaky, and fails due to not having write permissions to remove old dirs

### Versions / Dependencies

Ray v2.0.0
Ubuntu 20.04

### Reproduction script

I am not sure how to consistently reproduce or the exact conditions, only that this ocassionally happens when trying to build the pkg

### Anything else

The workaround is to cd into the relevant .cache/bazel folder and execute
```
sudo rm -rf python/ray/cpp
sudo rm -rf cpp/example/thirdparty
```
Manually. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jon-chuang** [comment]
@qicosmos do you ever encounter this issue when installing ray from local build? Is there a way to do this which does not rely on explicit cmd (somewhat hacky), and relies on Bazel's own management of build artifacts?

**Comment by qicosmos** [comment]
We have tested install ray_cpp_pkg on mac and Centos, not tested it on Ubuntu.
Could you provide your command lines for repeating the issue?

@SongGuyang Could you look at the issue?

**Comment by jon-chuang** [comment]
I think I just run `bazel build ray_cpp_pkg` in cpp directory. Usually it fails. 
I can't recall if building from python folder via `pip install -e . --verbose` results in the issue. I don't think so as it uses sudo as the caller.
Maybe if there is a way to call bazel with sudo, it would fix the issue?

**Comment by jon-chuang** [comment]
Closing as I think I'll use pip install as the workaround

**Comment by jon-chuang** [comment]
Reopening this since I also encounter this error with `bazel run cluster_mode_test`. Since this is a typical command to run, I believe this is a bug.
