### ISSUE TITLE
[Bug] can't get ray cluster fully utilized

### ISSUE THREAD

**Issue by mbehrendt** [ray-project/ray#21230]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

(I created this issue based on a chat with Sang Cho)

### Ray Component

Ray Clusters

### What happened + What you expected to happen

i created a cluster with 120 nodes, each having 8 vCPU and 32GB of memory. I triggered 10k task executions, and used the ray decorator assigning 0.15 vCPU to each task execution. While that should be enough work to fully utilize the cluster, many nodes are only lightly or not utilized at all (according to the ray dashboard). 

Is this familiar behavior? Have you seen this in other scenarios of an equivalent size?

![image](https://user-images.githubusercontent.com/4745697/147016438-4295c234-c5fb-44e0-8381-767a9f4cafed.png)

### Versions / Dependencies

1.9

### Reproduction script

I just call the task 10k times, which usually finished within a small, single-digit number of seconds. I also had tried the `RAY_max_pending_lease_requests_per_scheduling_category  == num_nodes` environment variable setting, but didn't see a major effect.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mbehrendt** [comment]
did some more investigation:

It turns out that the relatively slow invocation of a larger number of tasks exacerbates this issue, b/c the completion rate can be higher than the max possible invocation rate.

To break this down into a smaller, more contain experiments, i now setup a cluster of 11 nodes, and invoked a very simple tasks (sleeping for 300)  1000 times, each of them with 0.1 or 0.2 cVPUs assigned. Based on the VM config i'm using, this is more than enough to fully utilize the cluster -- which eventually happens. However, the 385 tasks being scheduled as part of this test, take a bit more than 120 seconds, which feels extremely long (that is about 385/120 = ~3 tasks per second). Based on that, it seems like this perf issue should be addressed first, to have a solid baseline for more load intensive workloads as described above.

**Comment by rkooo567** [comment]
cc @ericl @scv119 is this a known issue? The performance seems to be indeed very slow, and I found we had pretty big regression compared to 1.4.0. 

For example, in 1.4,  https://github.com/ray-project/ray/blob/master/release/release_logs/1.4.0/scalability/distributed.txt 
we could schedule **600 tasks/s**

and 1.7 https://github.com/ray-project/ray/blob/master/release/release_logs/1.7.0/benchmarks/many_tasks.txt
we now can only schedule **27/s** 

Btw his experiment was done with max_pararellism = 10 (the number of nodes).

**Comment by ericl** [comment]
I'm pretty sure that number is calculated wrong, since it scheduled 10k tasks and the overall runtime was 600 seconds.

**Comment by scv119** [comment]
the fundamental reason is ray single node scheduler becomes a bottleneck for embarrassingly parallel workload like this. An simple workaround for now is to submit jobs through actors placed on different nodes.

**Comment by scv119** [comment]
we should tackle this at ray 2.1

**Comment by AlexThirty** [comment]
Is there any update on this? Sorry to bother

**Comment by rkooo567** [comment]
It hasn't been fixed yet. This is one of PRs that attempt to fix the issue https://github.com/ray-project/ray/pull/28179/files

**Comment by scv119** [comment]
should have fixed as part of https://github.com/ray-project/ray/issues/26262
