### ISSUE TITLE
[Bug] RuntimeWarning: Mean of empty slice during training from np.nanmean in train_ops.py

### ISSUE THREAD

**Issue by jamesliu** [ray-project/ray#21242]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

1. What happened:
When training(E.g. PPOTrainer train), it will get RuntimeWarning sometimes below:

anaconda3/envs/py38/lib/python3.8/site-packages/ray/rllib/execution/train_ops.py:232: RuntimeWarning: Mean of empty slice tree.map_structure(lambda *s: None if s[0] is None else np.nanmean(s, axis=0), 
2. Expected:
No such annoying warning
3. Useful information:
After the investigation, the warning comes from the code when values in some specifi field of batch_fetches_all_towers are all np.nan. That causes np.nanmean throws such RuntimeWarning
 fetches[policy_id] = tree.map_structure(
                    lambda *s: None if s[0] is None else np.nanmean(s, axis=0),
                    *batch_fetches_all_towers)
E.g. 
[{..., "vf_explained_var":np.nan}, {..., "vf_explained_var":np.nan} .....]

### Versions / Dependencies

ray.__version__
'2.0.0.dev0'

It should happen on other versions.

### Reproduction script

When I run the example below and ppo trainer for my own data, but it is a general problem.

https://github.com/anyscale/academy/blob/471fed0c3c6c3f85649dcf20e30c64ea25dc222b/ray-rllib/explore-rllib/03-Custom-Environments-Reward-Shaping.ipynb

### Anything else

Suggestion,
np.namean throws such kind of warning when all elements in the list are np.nan. We may avoid call np.namean by checking the list s:
E.g.
np.all(np.isnan(s))

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by vakker** [comment]
This also happens elsewhere:
```
(PPO pid=1731058) /home/user/.pyenv/versions/spg-exp/lib/python3.9/site-packages/ray/rllib/utils/metrics/learner_info.py:84: RuntimeWarning: Mean of empty slice                 
(PPO pid=1731058)   return np.nanmean(tower_data)
```

Is this actually an issue or is this a harmless warning?

**Comment by sven1977** [comment]
Not sure it's so harmless. I would not expect e.g. vf_explained_var to be NaN on any GPU tower, unless something exploded in your model/loss.

@avnishn , something to definitely look at when starting the "catch errors during learning" project of yours.

@jamesliu Can you check your model's weights after you see these warnings? Also, what do the loss/vf-loss values look like?

**Comment by jamesliu** [comment]
@sven1977  Thanks for your suggestion. I will reproduce the issue and check the model's weights and loss/vf-loss/vf_explained_var values.

**Comment by jamesliu** [comment]
The warning can be reproduced in Exercise 2 from academy example in (https://github.com/anyscale/academy/blob/471fed0c3c6c3f85649dcf20e30c64ea25dc222b/ray-rllib/explore-rllib/03-Custom-Environments-Reward-Shaping.ipynb.)
1. attached is the gzipped pickled model weights. May you shed some light on what value to look at? 
[trainer_weights.pickle.gz](https://github.com/ray-project/ray/files/7834634/trainer_weights.pickle.gz)
2. vf_explained_var is all NaN at some time. What may cause it?

Add @ceteri  - contributor of the example in case he has some idea about it.

Besides the academy example, the warning was also reproduced in my own application, but somehow, the warning cannot be reproduced in my application at this moment.

**Comment by ceteri** [comment]
Hi @jamesliu ,

The `academy/ray-rllib/explore-rllib/03-Custom-Environments-Reward-Shaping.ipynb` part was built earlier. Dean edited it some earlier in 2020 to prep for webinars, although I believe the code was copied from an earlier source. I was asked to update some links here prior to a conference in later 2020, but not the code examples. FWIW, I was working in primarily in <https://github.com/DerwenAI/rllib_tutorials>

**Comment by gjoliver** [comment]
not sure what else is expected from the RLlib team. let us know if you need more input.
thanks for the report.
