### ISSUE TITLE
[Bug] RuntimeError: Failed to create runtime_env for Ray client server

### ISSUE THREAD

**Issue by andreapairon** [ray-project/ray#21241]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Serve

### What happened + What you expected to happen

Trying to run a script that uses Ray serve, but fails at the runtime env creation.

![image](https://user-images.githubusercontent.com/16152588/147121062-3a0c28a0-53d6-4dfd-b256-38e9001ae209.png)

My Ray serve script is deployed as Deployment on an AKS cluster and connects to the Ray cluster using `ray.init` (see the reproduction script below).

### Versions / Dependencies

`python3.7`
`ray 1.9.0`
`pytorch`
`torchvision`

AKS Cluster with Ubuntu 18.04 node

### Reproduction script

```import ray
import torchvision
from torchvision import models as models
import PIL
import requests

workers=1

ray_env = {"conda": {"dependencies": ["pytorch", "torchvision", "pip", {"pip": ["ray[serve]", "Pillow", "requests"]}]}}
ray.init(address="ray://<svc_address>:10001", runtime_env=ray_env)

from ray import serve

serve.start()

@serve.deployment(route_prefix="/alexnet")
def predict(request):
    alexnet = models.alexnet(pretrained=True)
    img_file = "./robot.jpg" # you need an img here
    img = PIL.Image.open(img_file)
    img = torchvision.transforms.ToTensor()((img))
    img = 0.5 + 0.5 * (img - img.mean()) / img.std()
    img = img.unsqueeze(0)
    res = alexnet(img)
    print(res)
    return f"Predicted with AlexNet!"

predict.deploy()

resp = requests.get("http://<svc_address>:8000/alexnet")
print(resp.json())```




### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Hi @andreapairon, thanks for reporting this.  I was unable to reproduce this using a local Ray client connection (that is, running `ray start --head` on a local machine, and then executing your script with `ray.init(address="ray://localhost:10001", runtime_env=ray_env)`.

Can you check the logs to see if there are any clues as to why the runtime_env failed to be set up?  By default they are in `/tmp/ray/session_latest/logs`.  For me, I see successful output of a conda installation in `dashboard_agent.log`.  You might also find relevant logs in `runtime_env_setup_*` and `ray_client_server_*` log files.  Or if you're comfortable with sharing your log files, you can zip them up and send them over and I can take a look.

**Comment by architkulkarni** [comment]
Actually, your screenshot output prints the last lines of the conda installation output.  It seems to have stopped after "Verifying transaction", but I'm not sure why.  Here's the relevant portion of a successful installation log for comparison:

```
2022-01-03 11:38:28,893	INFO conda_utils.py:198 -- Preparing transaction: ...working... done
2022-01-03 11:38:31,809	INFO conda_utils.py:198 -- Verifying transaction: ...working... done
2022-01-03 11:38:39,617	INFO conda_utils.py:198 -- Executing transaction: ...working... done
2022-01-03 11:38:46,800	INFO conda_utils.py:198 -- Installing pip dependencies: ...working... Ran pip subprocess with arguments:
2022-01-03 11:38:46,801	INFO conda_utils.py:198 -- ['/tmp/ray/session_2022-01-03_11-37-54_198496_24684/runtime_resources/conda/217083f2e1cb155311699beee459fe26c26ef295/bin/python', '-m', 'pip', 'install', '-U', '-r', '/tmp/ray/session_2022-01-03_11-37-54_198496_24684/runtime_resources/conda/condaenv.jxjqcm59.requirements.txt']
2022-01-03 11:38:46,801	INFO conda_utils.py:198 -- Pip subprocess output:
2022-01-03 11:38:46,801	INFO conda_utils.py:198 -- Collecting ray[serve]
...
```

So it looks like it stopped before installing the pip packages. 

@andreapairon Does this failure happen consistently?

**Comment by ankur6ue** [comment]
I'm seeing the same issue.. ray on kubernetes tries to install runtime dependencies but stalls midway

Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 624, in Datapath
    client_id, job_config):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 281, in start_specific_server
    specific_server=specific_server,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/proxier.py", line 234, in _create_runtime_env
    "Failed to create runtime_env for Ray client "
RuntimeError: Failed to create runtime_env for Ray client server: Failed to install pip requirements:
Collecting ruptures

**Comment by architkulkarni** [comment]
Hi @ankur6ue sorry you're running into this!  could you post more logs from `dashboard_agent.log` on the head node and any other runtime env setup logs you might find on the head node?  

It may be that the `pip install` ran out of memory and was killed; if this is the case there should be `Killed` in the logs somewhere.  Regardless, you can try increasing the memory of your node to see if that fixes it.  Another experiment to try out for debugging is whether you can manually access the node via command line and install the same environment, and see if it fails in the same way.

**Comment by misbahfhm** [comment]
was it solved? @andreapairon
