### ISSUE TITLE
`pip` copies installed packages to `session_*\\runtime_resources` everytime

### ISSUE THREAD

**Issue by czgdp1807** [ray-project/ray#21254]
In the following test we (I and @mattip) noticed that it takes very long times to complete the installation of `tensorflow` and `pytorch`. I changed it to `numpy` and `scipy` (specifically,  `"pip": ["tensorflow", "torch"]` to `"pip": ["scipy", "numpy"]` and noticed that it took 90s just to install `scipy`. Most of the time is taken in copying the `scipy` (and `numpy`) installation to `--target=C:\\CONDA_~1\\ray\\session_*\\runtime_resources\\pip\\some_hash_value`. (see screenshot below). So, we think that installing tensorflow (and friends) to above target directory should take way more longer because the list of packages to be copied is really huge.

```python
def test_runtime_env_no_spurious_resource_deadlock_msg(
        runtime_env_local_dev_env_var, ray_start_regular, error_pubsub):
    p = error_pubsub

    @ray.remote(runtime_env={"pip": ["tensorflow", "torch"]})
    def f():
        pass

    # Check no warning printed.
    ray.get(f.remote())
    errors = get_error_message(p, 5, ray.ray_constants.RESOURCE_DEADLOCK_ERROR)
    assert len(errors) == 0
```

May be to avoid that we can either use package sharing (cc: @mattip) for the same version or may be just copy to `runtime_resources` directory only when the installed version is different from what is available in `site_packages`.

<img width="1010" alt="Screenshot 2021-12-23 at 4 00 33 PM" src="https://user-images.githubusercontent.com/36567889/147227671-a8acaf7b-27be-4594-8c58-dd78742b4840.png">

As you can see whole `scipy` installation is copied to `runtime_resources/` directory. In case of tensorflow (and friends), it might take way more than 90s because, tensorflow alone is 430 MB and it's dependencies list is huge so in total it might amount to around 1GB (it will be large though may not be exactly that 1GB).

**Comment by pcmoritz** [comment]
cc @edoakes Any thoughts here?
