### ISSUE TITLE
[Feature] large data storage in Ray object store

### ISSUE THREAD

**Issue by chuckhope** [ray-project/ray#21251]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Hi, I have utilized ray tune to do the knowledge distillation work with huggingface transformers. Before training ,I have to use the SquadV1Prcessor of huggingface to extract features. I have a dataset of about 400MB, and it turns to 80GB (the virtural memory in the 'htop' UI). 

The solutions I have tried:
  1. I have tried wrap the data in the trainable function     >>>   ValueError: The actor ImplicitFunc is too large  > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB
  2. put my processed features into tune.with_parameters instead      >>>.   However, the program gets stuck without info. I can see from 'htop' UI that the program is still running but with a 80GB VIRT.
  3. put my processed features using ray.put and ray.get.   >>>    basically, I guess "ray.put" do the same thing with "tune.with_parameters"
 
Do you have any ideas my help, thank you!
 

### Use case

ray tune to store a data ref larger than 80GB

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
That seems a lot of data. Can you try run `ray memory --stats-only` to see the object store memory usage?

**Comment by chuckhope** [comment]
@scv119 Thanks for your response. I got the message"Plasma memory usage 20305MiB, 10 objects, 55.53% full, 55.53% needed Objects consumed by Ray tasks: 20305 MiB" and the program just got stuck without info.
