### ISSUE TITLE
[Bug] Memory leak inside docker container

### ISSUE THREAD

**Issue by lionsheep0724** [ray-project/ray#21269]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When I initialize ray with ray.init() in docker container, the memory usage increases over time and container dies when memory over shm-size limit. (**only ray.init() can cause this issue**)
Also, too many duplicated processes spawns when ray.init. (RAY:IDLE, ray dashboard, something ray-related processes)
I reproduced this issue with official ray image : https://pypi.org/project/ray/#history

P.S : Our use-case is combination of docker container, fastapi scheduler and ray. (i.e : we initialize ray instance once, and do ray.put, ray.get every pre-defined cycle.)

### Versions / Dependencies

ray version : 1.9.1. 

### Reproduction script

ray.init() (inside docker container)

### Anything else
Now I found that the only way to solve this issue is just shutdown ray instance every single schedule. But I think it's temporary solution. 
+ I want to make sure if there's no issue with fastapi-scheudler, or any other async processes

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jon-chuang** [comment]
Hmm, if your driver worker is not deleting references to the objects it puts once they aren't needed, maybe that's what's gradually eating up memory?

**Comment by lionsheep0724** [comment]
> 



> Hmm, if your driver worker is not deleting references to the objects it puts once they aren't needed, maybe that's what's gradually eating up memory?

No. as I mentioned, memory gradully increases when ray.init'ed only. No ray.get, no ray.put in my test case.

**Comment by lionsheep0724** [comment]
Let me share my first design pattern to reproduce this issue. (pseudo code)
ray.init(num_cpus=4,dashboard_host='0.0.0.0',dashboard_port=8888, configure_logging=False)
```
dd = []
bb = ray.put(dd)
fut = []
for i in range(10):
fut.append(aa.remote(bb))
ss = ray.get(fut)
@ray.remote
def aa(ss):
    a = np.random.rand(380,640)
    ss.append(a)
    return ss
```

**Comment by scv119** [comment]
@lionsheep0724 how it takes you job to OOM? Also it'd be nice to run `ray memory --stats-only` to see the memory growth overtime.

**Comment by lionsheep0724** [comment]
> @lionsheep0724 how it takes you job to OOM? Also it'd be nice to run `ray memory --stats-only` to see the memory growth overtime.
Please refer to same issue #21445

**Comment by scv119** [comment]
merge the issue to #21445
