### ISSUE TITLE
[Bug] Confusing routes in make_fastapi_class_based_view

### ISSUE THREAD

**Issue by dongruixiao** [ray-project/ray#21264]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

When I was using the same app on two different deployments

```python3
app = FastAPI()

@serve.deployment
@serve.ingress(app)
class CounterDeployment
    pass

@serve.deployment
@serve.ingress(app)
class CounterDeployment2
    pass

CounterDeployment.deploy()
CounterDeployment2.deploy()
```

I would like to get a clear route in each api documentation, like this:

```python3

# http://localhost:8000/CounterDeployment/docs
# /incr
# /decr

# http://localhost:8000/CounterDeployment2/docs
# /incr2
# /decr2

```
but in fact it didn't, i got like this:

```python3

```python3

# http://localhost:8000/CounterDeployment/docs
# /incr
# /decr

# http://localhost:8000/CounterDeployment2/docs
# /decr
# /incr2
# /decr2
```

More information is available below from my reproduction script, 
and I have also provided the code that may have been the problem.

### Versions / Dependencies

```
ray==1.9.0
```

### Reproduction script

```python3

In [1]: import ray

In [2]: from fastapi import FastAPI

In [3]: from ray import serve

In [4]: ray.init('auto', namespace='algo-serve')

In [5]: serve.start(detached=True)

In [6]: app = FastAPI()

In [7]: @serve.deployment
   ...: @serve.ingress(app)
   ...: class CounterDeployment:
   ...:     def __init__(self, count=0):
   ...:         self.count = count
   ...:
   ...:     @app.get('/incr')
   ...:     def incr(self):
   ...:         self.count += 1
   ...:         return self.count
   ...:     @app.get('/decr')
   ...:     def decr(self):
   ...:         self.count -= 1
   ...:         return self.count
   ...:

In [8]: @serve.deployment
   ...: @serve.ingress(app)
   ...: class CounterDeployment2:
   ...:     def __init__(self, count=0):
   ...:         self.count = count
   ...:
   ...:     @app.get('/incr2')
   ...:     def incr2(self):
   ...:         self.count += 1
   ...:         return self.count
   ...:     @app.get('/decr2')
   ...:     def decr2(self):
   ...:         self.count -= 1
   ...:         return self.count
   ...:

In [9]: CounterDeployment.deploy()

In [10]: CounterDeployment2.deploy()


```

### Anything else

I see that it seems to be deleting routes in different deployments [here](https://github.com/ray-project/ray/blob/master/python/ray/serve/http_util.py#L232), 

but it shouldn't be deleting list elements in its [own loop](https://github.com/ray-project/ray/blob/master/python/ray/serve/http_util.py#L215)

FYI: https://github.com/ray-project/ray/blob/master/python/ray/serve/http_util.py#L215-L232

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
Thanks for the report @dongruixiao. I can reproduce this.

**Comment by jacobdanovitch** [comment]
I had this issue as well, works correctly with the nightly build now.
