### ISSUE TITLE
[Bug] Wandb randomly crashing experiments logging

### ISSUE THREAD

**Issue by NumberChiffre** [ray-project/ray#21272]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Hi everyone,

I am running some ray tune + pytorch lightning code with `ASHAScheduler` on a single GPU and noticed that some experiments logging will have the status `crashed` shown on wandb, while the experiments would still be running and also updated on tensorboard. The expected behavior is that I would see the same updates on wandb equivalent to what I see on tensorboard. I also validated that there has been no memory spikes or any other resource problems from what I can see. This issue is quite random and does not occur for most of my experiment trials, just a few.

The console logger would also show that the status is `RUNNING`, so I actually have no error logs for this.

When trying to use `wandb sync wandb/{experiment_name}`, I would get this:
...wandb: WARNING .wandb file is incomplete (record checksum is invalid, data may be corrupt), be sure to sync this run again once it's finished

This issue seems to match with an existing issue on wandb's issues and is still currently open, though I am not sure if its a network instability issue:
https://github.com/wandb/client/issues/1526

### Versions / Dependencies

torch = "1.9.1"
pytorch-lightning = "1.4.9"
ray = "1.9.1"
wandb = "0.12.5"
python = 3.7.12
OS = Ubuntu 20.04
GPU = NVIDIA GeForce GTX 1660 SUPER

### Reproduction script

Used this, except that I added an extra `callback=[WandbLoggerCallback()]` in `tune.run()`:

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_lightning.py

### Anything else

Everytime I run ray tune with wandb callback I would get this issue.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
This seems like a wandb client API stability issue.

**Comment by NumberChiffre** [comment]
Most likely, I haven't seen this issue in the last week, will close this.
