### ISSUE TITLE
[rllib] Unify distributions in action_dist

### ISSUE THREAD

**Issue by alok** [ray-project/ray#2127]
Now that torch and tensorflow both support builtin distributions, it may be a good idea to unify ActionDistribution with some sort of dynamic dispatch. It makes things like computing kl divergence cleaner too, since it's already done (and optimized).

I have a branch that starts working on this, but it's preliminary at the moment.

**Comment by ericl** [comment]
Yes, I think this could also improve performance too, by avoiding a lot of the small tensor ops.

**Comment by ericl** [comment]
Closing this for now since we only have the one torch example
