### ISSUE TITLE
[xlang] [C++/C/Rust/Golang] Refactor Out (Native) Language Harness 

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We should investigate refactoring out a native harness than can be used by all native language drivers and workers (and beyond).

This is related to more broadly refactoring out common features and requirements, e.g. could be at a code structure/spec level too. Native harness is a very concrete version of this more general common factoring.

For instance:
- dynamic library tooling (function manager):
  - function ptr <-> fn descriptor mapping
  - invoker ptr retrieval/invocation from dynamic library
  - (standardized?) invocation FFI
  - common serializer/buffer mgmt
- worker cmdline, config, and worker process invocation.
- others... to be added

Related: 
https://github.com/ray-project/ray/issues/21181

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Not sure what you meant about `dynamic library tooling (function manager)`.

But from my personal understandings, one thing is verbose about config. For example, if we need add a flag which should be applied to all of the workers, we should add it to driver as well as adding it in `worker_pool` to make it applied in worker.

**Comment by jon-chuang** [comment]
For dynamic library tooling, its more for native code, basically loading dynamic `.so` files, get all of the symbols, and map any task execution request to the appropriate function pointer, and finally the FFI interface (hopefully with C-ABI) for ray runtime to invoke those functions, and pass and retrieve serialized arguments or pointers.

**Comment by jon-chuang** [comment]
For this config, I think it could be put in `core_worker/utils`. What dya guys think?

**Comment by SongGuyang** [comment]
Looks good to me to build common utils or libraries for all languages. But I'm not sure how many codes of dynamic library loading can be shared from C++ worker to Rust because I'm not familiar with Rust. Can you make a prototype for this? If you can do, I'm happy to review! 
 About cmdline, I think it is easy to share.
About config, it is a great refactor which we always want to do. I think we should unify the config ways for all languages. But it is also not easy. We need a unified design for this.

**Comment by jon-chuang** [comment]
> But I'm not sure how many codes of dynamic library loading can be shared from C++ worker to Rust .. Can you make a prototype for this?

I will definitely try to do so as I am currently building this component for Rust. 
However, I've some other issues to prioritize so it may be a few weeks later.

Definitely will make a PR soon for the config/cmdline refactor as it is low-hanging fruit, and the earlier done, the better.

**Comment by SongGuyang** [comment]
Sounds good.

**Comment by jon-chuang** [comment]
Here is an idea I have:
- Make the function manager initialization from path a callback with C++ API, accepting lib path as arguments
- This function manager callback can be initialized, alongside the dylib-local reference to the default-worker initialized coreworker, after the default coreworker has been initialized (similar to: https://github.com/ray-project/ray/pull/21125)

Thoughts @qicosmos ?
