### ISSUE TITLE
[Bug] Graph mode errors when using framework="tf"

### ISSUE THREAD

**Issue by wpwpxpxp** [ray-project/ray#21278]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm using Ray RLlib to train a PPO agent with TWO modifications on the PPOTFPolicy. 

- I added a mixin class (say "Recal") to the "mixins" parameter in "build_tf_policy()". This way, the PPOTFPolicy would subclass my "Recal" class and have the access of the member functions that I defined in "Recal". My "Recal" class is a simple subclass of tf.keras.Model. 
- I defined a "my_postprocess_fn" function to replace the "compute_gae_for_sample_batch" function which is given to the parameter "postprocess_fn" in "build_tf_policy()". 

The "PPOTrainer=build_trainer(...)" function keeps unchanged. I use framework="tf", and make eager mode disabled.

Pseudo code is below. [Here](https://colab.research.google.com/drive/15sBQ3HJrwH_ODi5CINDDrvCsD4ypDl46?usp=sharing) is a running version at colab.

```
class Recal:
    def __init__(self):
        self.recal_model = build_and_compile_keras_model()

def my_postprocess_fn(policy, sample_batch):
    with policy.model.graph.as_default():
        sample_batch = policy.recal_model.predict(sample_batch)
    return compute_gae_for_sample_batch(policy, sample_batch)

PPOTFPolicy = build_tf_policy(..., postprocess_fn=my_postprocess_fn, mixins=[..., Recal])
PPOTrainer = build_trainer(...)
ppo_trainer = PPOTrainer(config=DEFAULT_CONFIG, env="CartPole-v0")

for i in range(1):
  result = ppo_trainer.train()
```

The last line triggered the error:

`tensorflow.python.framework.errors_impl.FailedPreconditionError: Could not find variable default_policy_wk1/my_model/dense/kernel. This could mean that the variable has been deleted. In TF1, it can also mean the variable is uninitialized. Debug info: container=localhost, status error message=Container localhost does not exist. (Could not find resource: localhost/default_policy_wk1/my_model/dense/kernel)
	 [[{{node default_policy_wk1/my_model_1/dense/MatMul/ReadVariableOp}}]]`

### Versions / Dependencies

Ray 1.8
Python 3.7

### Reproduction script

Here is a colab [link](https://colab.research.google.com/drive/15sBQ3HJrwH_ODi5CINDDrvCsD4ypDl46?usp=sharing) that can reproduce the error. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
can you provide a reproduce script that we can actually run?
thanks.
