### ISSUE TITLE
realloc(): Invalid pointer: perhaps shared memory getting massively clogged by plasma?

### ISSUE THREAD

**Issue by ghostFaceKillah** [ray-project/ray#2128]
#### Os Platform and Distribution

Desktop Ubuntu 16.04

```
misiu@mothership:~$ uname -a
Linux mothership 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
misiu@mothership:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
#### Ray installed from (source or binary)
Binary ```pip install ray```

#### Ray version
0.4.0
```
(py3) misiu@mothership:~$ python -c "import ray; print(ray.__version__)"
0.4.0
```

#### Python version
3.5.2
```
(py3) misiu@mothership:~$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
```

#### Exact command to reproduce:
```
git clone https://github.com/ghostFaceKillah/baselines.git
cd baselines
tmux
python -m baselines.acktr.run_atari
```
outside of tmux, every 10 minutes or so
```
df -kh /dev/shm
```

### Describe the problem
Hi Authors & Contributors, thanks for great work! I love the project.

I have a bit of a problem that looks similar to #1119, but cannot be solved by increasing the size of /dev/shm.

I am working on distributed version of openai baselines SubprocVecEnv. I need it to work with environments that are so resource hungry that they have to be put on separate computers and use ray to push actions to them and get states etc back.

I have started by making a copy of SubprocVecEnv that uses ray to handle the process management and interprocess comunication. Here is the code for the environment:
https://github.com/ghostFaceKillah/baselines/blob/master/baselines/common/vec_env/ray_vec_env.py
Here is the code of the whole commit that makes small adjustments to make it run within training context:
https://github.com/ghostFaceKillah/baselines/commit/589b7f353fec7598eec31617d6d489b943f45ae2

However when I run it in training on my machine, an error seen on the error log seen below appears after around 3 hours of computing.

It looks a lot like #1119, and I speculate that plasma store slowly fills up whole available memory until there isn't any left.

I speculate this based on repeated running of 
```
df -kh /dev/shm
```
each time it is called, shows a slightly higher usage.

As I have 64GB on my computer and shm is 32GB I am guessing "it should work". I am guessing that plasma should somehow clean the old stuff it doesn't need?

Am I missing something or is it a problem with ray?

Thank you for your time & attention. Let me know if I can help debugging.

### Source code / logs

I have produced a easy to run code that reproduces the problem.
It is a fork of openai baselines with one commit that introduces ray.

The fork is here:
https://github.com/ghostFaceKillah/baselines

The one commit that changes baselines is here
https://github.com/ghostFaceKillah/baselines/commit/589b7f353fec7598eec31617d6d489b943f45ae2

After running it for some time (around 3 hours on machine with 64 GB RAM = 32 GB shared memory), it generates the following log:

![zrzut ekranu 2018-05-23 o 07 51 56](https://user-images.githubusercontent.com/2945232/40427298-9635cf4c-5e9d-11e8-8755-644be3a42e01.png)

(Sorry for the image, the original log file got deleted)

which looks a lot like #1119

**Comment by ghostFaceKillah** [comment]
I have run it again, this time it filled in all available RAM (64 GB).

**Comment by ghostFaceKillah** [comment]
Looks related to #733

**Comment by pcmoritz** [comment]
Since there is one task per step in the code, one likely thing to happen is that redis gets filled up with the lineage until all RAM on the machine is filled up with redis memory and then the allocation in the local scheduler fails. If that's the case, you can use the flushing functions here to reclaim memory: https://github.com/ray-project/ray/blob/78e4b021abb6a7e073f71e6a8ef74fedb9ee02fe/python/ray/experimental/__init__.py#L7 (make sure you have this patch included: https://github.com/ray-project/ray/pull/1797), or batch together calls to step to create less lineage.

**Comment by ghostFaceKillah** [comment]
Thanks, rerunning now to check which process is using most memory.
Is copy of `top` output sufficient?

Then I will run a version with redis cleaning and see if it helps.

**Comment by robertnishihara** [comment]
Yeah, the output of `top` would be good. You can try calling the flushing methods in https://github.com/ray-project/ray/blob/master/python/ray/experimental/features.py, e.g.,

```
ray.experimental.flush_redis_unsafe()  # To flush some logs
ray.experimental.flush_finished_tasks_unsafe()  # To flush task metadata for finished tasks.
ray.experimental.flush_evicted_objects_unsafe()  # To flush metadata for evicted objects.
```

**Comment by ghostFaceKillah** [comment]
I confirm that most likely the slowdown is caused by `ray`. 

Steps to reproduce are as in the first post in this thread.

Unexecpted behavior:
Fps drops from 800 frames in the beginning to around 50 after 15 minutes of training and then even lower.
Fps without ray is around 1.3k.

Maybe I am misusing the framework?

**Comment by robertnishihara** [comment]
I'd suggest taking a look at the timeline visualization http://ray.readthedocs.io/en/latest/webui.html, which is really useful for diagnosing performance issues.

How many `RayVecEnv` objects are created throughout the training run?

Can you check where time is being spent? E.g., which `RayVecEnv` method call is getting slower (and how slow)?

Note that each `env.step` call in the `EnvActor` is probably very quick (less than 1ms), so depending on the overhead, it can be difficult to get a speedup from parallelizing tasks of this size.

**Comment by ericl** [comment]
This was fixed in https://github.com/ray-project/ray/pull/3499
