### ISSUE TITLE
[Feature] Fine-grained actor call end-to-end time tracing required

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#21294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

In the online real-time bussiness scenario, such as financial payment system, the latency SLA of actor call is extremely important. At present, there is a lack of end-to-end latency tracking for actor call, system owners can not figure out why some remote calls timeout.

We propose to add timestamp tracing field in TaskSpec, and measure the fine-grained task spec lantency, including the sending time cost from caller to callee, the task execution time cost and the reply from callee to caller. And on this basis, P99/P95 can be measured.

A new option should be added to trigger on the tracing, and set to false by default to prevent performance regression.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by MissiontoMars** [comment]
@scv119 Could you help look at this or involve some other in? Thanks. cc @raulchen @jovany-wang

**Comment by scv119** [comment]
Task/actor execution time is indeed a critical metric to observe. @rkooo567 is this something you have planned to work on?
I have the impression (and conceptually) that task specs is supposed to be immutable, but not 100% sure. I'll take a closer look and get back to you!

**Comment by jon-chuang** [comment]
Actually I think this can be derived from local logs, but the clocks need to be synced between machines. Since we are talking about microsecond scale, not sure what is the typical drift for machines.

Not convinced that collecting statistics should be in-band in the task spec between worker to worker RPC.

For statistics collection/tracing more generally, my intuition is to advocate for a global real-time events time series. 

Not sure if it ought to be part of GCS or separate. Possibly separate and use something like influxDB and can scale independently.

**Comment by rkooo567** [comment]
Yeah I think this can be derived from scheduling events I am planning to work on. I agree with Jon for general api & impl (getting it from event logs + collecting outside gcs

**Comment by MissiontoMars** [comment]
@rkooo567 Great! Is there any documentation to describe the scheduling events? I want to have a early look.

**Comment by rkooo567** [comment]
It is not completed yet. I can share with you once it is done, and then we can discuss if this can satisfy the requirement

**Comment by MissiontoMars** [comment]
@rkooo567 Is there any progress on this work ?

**Comment by rkooo567** [comment]
Oh no. Actually the scope of the project has been changed. This could be a part of the project, but it is not a high priority. 

If you have bandwidth, adding things to task spec sounds good to me! But we should make sure this is done in a thread safe way (and isolated from other immutable fields)!
