### ISSUE TITLE
[Datasets] [Pandas Block] Implement PandasBlockAccessor in pandas-native ways

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#21296]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

#20988 Introduces a Pandas block format support in Ray Dataset. But Some methods of `PandasBlockAccessor` are implemented by converting to and from Arrow format. The performance may be not as good enough as the pandas-native way. We need to re-implement them.

Interfaces to be implemented:
- `sort_and_partition`
- `combine`
- `merge_sorted_blocks`
- `aggregate_combined_blocks`

### Related issues

#20719

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@kfstorm Any chance that you might have bandwidth to take this on in the near future?

**Comment by kfstorm** [comment]
@clarkzinzow Sorry for the late reply. Unfortunately, I don't have the bandwidth to work on this.

**Comment by clarkzinzow** [comment]
Hey @kfstorm, no worries, I opened a PR for this last week! https://github.com/ray-project/ray/pull/26313
