### ISSUE TITLE
[Core][Bug] many_task stress test regression 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#21304]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
{
  "tasks_per_second": 27.508657888123608,
  "num_tasks": 10000,
  "time": 663.5219151973724,
  "success": "1",
  "_runtime": 674.2678966522217,
  "_session_url": "https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_XCJkRqS4HkuHLXehx7i6Fwvc",
  "_commit_url": "https://s3-us-west-2.amazonaws.com/ray-wheels/releases/1.7.0/2367a2cb9033913b68b1230316496ae273c25b54/ray-1.7.0-cp37-cp37m-manylinux2014_x86_64.whl",
  "_stable": true
}
```

We have seen task scheduling/execution throughput regression [(27/s)](https://github.com/ray-project/ray/blob/master/release/release_logs/1.7.0/benchmarks/many_tasks.txt) since Ray 1.7. It was [500-600/s ](https://github.com/ray-project/ray/blob/master/release/release_logs/1.4.0/stress_tests/many_tasks.txt)at Ray 1.4 and unfortunately the benchmark is missing from 1.5 and 1.6.

@jjyao's change parallelizing of lease requests is expected to to speed this up

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
@rkooo567 can you take a look?

**Comment by rkooo567** [comment]
Sure. Will look into this today

**Comment by rkooo567** [comment]
So, it turns out the regression was not as big as 600 tasks/s -> 27 tasks/s (I misread 600 runtime as 600 tasks/s).

When I ran 1.4, it could schedule about 90 tasks/s. And after we merge the async pop worker PR from Ant, it became 27 tasks/s. I think we should see if @stephanie-wang's PR will fix this regression first. The issue itself can be downgraded for now.

Regarding task performance in general, I've done some experiment, and found out the max in flight lease request is the bottleneck (so the submission speed). Here's the result of my experiment.

```
1.4 => 90/s. So it was always slow
1.9 -> 27/s # 3X regression after the worker pool PR.
1.9 + num_nodes(64) max lease request: 60/s, (there were 50K-ish spillback)
1.9 + 5000 max lease request: 191/s, (there were more than 1.5 million spillback)
```

**Comment by jjyao** [comment]
We probably should do more performance work around what a good lease parallelism is. I'm going to set the default to 10 but it's probably not the best.

**Comment by rkooo567** [comment]
Yeah agreed! We can have different policies to make it better as well.

Also, my current impression of max lease requests is to alleviate load, so it might be also possible to control this from raylet. For example, raylet decides the max pending tasks (that could be high, like 5000~10000) and reject the lease request if the queue is full. 

I think we can discuss the best approach when we tune the best value.

**Comment by rkooo567** [comment]
Unassign myself for now. We will revisit it (performance) after refactoring. Right now, we know that increasing the lease parallelism can improve the performance a lot!
