### ISSUE TITLE
[Bug] Odd debug log formatting for gcs accessor

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21302]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Log output strings looks normal

Instead, we have byte-like formatting appearing
```
accessor.cc:1079: Reporting worker failure, raylet_id: "\222\036-\362\211\207\303H\235\372}\235\252\374)cZ:\036Me\023\357\201\325u.\223"
ip_address: "192.168.1.75"
port: 10002
worker_id: "\001\000\000\000\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
```

### Versions / Dependencies

ray 2.0.0-dev

### Reproduction script

nil

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Can you file a PR to fix it? It should be just formatting (normally, when ids are printed, .Hex() is called automatically iirc, but this probably didn’t do that)

**Comment by jon-chuang** [comment]
Actually, this is from `DebugString` which is autogen from protobuf for address
```proto
// Address of a worker or node manager.
message Address {
  bytes raylet_id = 1;
  string ip_address = 2;
  int32 port = 3;
  // Optional unique id for the worker.
  bytes worker_id = 4;
}
```
Bytes are encoded in the DebugString as octal.

Since it is difficult to change, and not so important, I think we should just ignore it.
