### ISSUE TITLE
[CI] Migrate from YAPF to Black

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#21311]
## Overview

The Ray Team has decided to format the Ray Python code with [Black](https://black.readthedocs.io/en/stable/index.html). This means that going forward, changes to Python code must adhere to the [Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html). 

We'll be updating [`./scripts/format.sh`](https://github.com/ray-project/ray/blob/master/ci/travis/format.sh), so if you're a contributor, your workflow shouldn't change.

## Motivation

We're switching to Black because:
* Code formatted with Black is more readable than code formatted with YAPF.
* Black is faster than YAPF.
* Black is the most popular Python formatting tool.

For more information about the motivation behind this change, read the [full proposal](https://docs.google.com/document/d/1kSmUOdUkCksQNoS01Ux4wk-nzJ8GFzu6--uPaR1fIUQ/edit?usp=sharing).

## Implementation Plan

We're planning on rolling out the changes in three phases.

**Phase One:**
- [x] #21312 
- [x] #21315 
- [x] #21314 
- [x] #21313 

**Phase Two:**
- [x] #21316 
- [x] Comment on open pull requests and tell contributors how to update their code.

**Phase Three:**
- [x] #21317 
- [x] #21318 
- [x] #21319 

## Timeline

| Phase | Due Date | Status                 |
|-------|----------|------------------------|
| I     | 1/1      | :white_check_mark: Done |
| II    | ~~1/15~~ 1/29     | :white_check_mark: Done         |
| III   | 1/31     |          |

**Comment by pcmoritz** [comment]
This is now finished, right?

**Comment by bveeramani** [comment]
There's one last minor PR #21984, but otherwise we're done!
