### ISSUE TITLE
[Core] [Bug] Ray failed with uWSGI

### ISSUE THREAD

**Issue by dokuboyejo** [ray-project/ray#21327]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When ray is used with uwsgi, it fails with below
```
/usr/bin/uwsgi-core: invalid option -- 'u'
getopt_long() error
```

### Versions / Dependencies

Tried with version 0.8.0 to 1.9.1

### Reproduction script

Start up application with uwsgi

```
/usr/bin/uwsgi --die-on-term --single-interpreter --ini /etc/uwsgi/apps-enabled/uwsgi_webhook.ini --log-master
```
The error get thrown immediately after hitting `ray.init`

PS: initializing ray with `local_mode=True` doesn't produce the error. However, that option allows only single process and is only for debugging, so can't really be used as the essence of ray is to leverage parallelism.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dokuboyejo** [comment]
It appears when ray is initialized it tried to start the cluster with node_ip, which eventually conflicts with uwsgi

**Work around**
Given I'm using supervisord with uwsgi, I created an additional task specifically for ray

```
[program:ray]
command = venv/bin/ray start --head

[program:uwsgi]
command = /usr/bin/uwsgi --single-interpreter --die-on-term --ini /etc/uwsgi/apps-enabled/uwsgi_webhook.ini --log-master
```

With the above, ray was able to start normally without affecting uwsgi, and both could then work together

**Comment by richardliaw** [comment]
Looks like there is a workaround, so closing this for now. @dokuboyejo
