### ISSUE TITLE
[Core] [Documentation] LBFGS example in documentation doesn't seem correct.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#21328]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

In this documentation page https://docs.ray.io/en/latest/auto_examples/plot_lbfgs.html, the documentation refers to creating an actor, but then the @ray.remote decorator doesn't appear anywhere and the code doesn't seem to match the text. That's just one example on this page, but there are other issues. Overall, you can't get this code to run from the documentation page.

<img width="769" alt="Screen Shot 2022-01-01 at 9 37 12 PM" src="https://user-images.githubusercontent.com/249517/147867264-6baf6a0e-eaa6-4162-8ea1-35749451f69d.png">
 

### Versions / Dependencies

Latest

### Reproduction script

Not applicable

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by robertnishihara** [comment]
FYI @maxpumperla

**Comment by robertnishihara** [comment]
I think it's still an issue. @maxpumperla @richardliaw shall we just remove the example?

**Comment by maxpumperla** [comment]
@robertnishihara good point, let me see what's best here.
