### ISSUE TITLE
[RLlib] [Bug] IMPALA num_multi_gpu_tower_stacks overwrites minibatch_buffer_size

### ISSUE THREAD

**Issue by vakker** [ray-project/ray#21335]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Running an IMPALA (or APPO) training with not matching `num_multi_gpu_tower_stacks` and `minibatch_buffer_size` causes:
```
(APPO pid=3782545) 2022-01-02 22:07:15,476      WARNING impala.py:178 -- In multi-GPU mode you should have at least as many multi-GPU tower stacks (to load data into on one device) as you have stack-index slots 
in the buffer! You have configured 2 stacks and a buffer of size 32. Setting `minibatch_buffer_size=2`.      
```

There are many tuned examples that explicitly include `num_multi_gpu_tower_stacks: 1` with `minibatch_buffer_size` that's not 1 (e.g. `ppo/halfcheetah-appo.yaml`). 
It's not clear why this is happening and there's no mention of this in the docs, and it's also not clear why the tuned examples have this. Maybe they were not updated when this check was introduced. 
Then there's a potential performance regression, since all the relevant examples are run with `minibatch_buffer_size: 1`.

### Versions / Dependencies

Ray: 327eb84 (latest master)

### Reproduction script

```
rllib train -f rllib/tuned_examples/ppo/pong-appo.yaml
```
or
```
rllib train -f rllib/tuned_examples/ppo/pendulum-appo.yaml
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by vakker** [comment]
I believe this was introduced in #18540 to change the exception to a warning, but shouldn't the resolution be the other way around?
I.e. instead of:
```python
config["minibatch_buffer_size"] = num_stacks
```
do 
```python
config["num_multi_gpu_tower_stacks"] = buffer_size
```

My understanding is that the stacks are there to support the requirements of the algorithm, not the other way around. In other words, changing the `minibatch_buffer_size` has RL performance implications, while changing `num_multi_gpu_tower_stacks` has throughput or memory implications.

@sven1977, what do you think?

**Comment by gjoliver** [comment]
Hi Vince, thanks for the issue.
this is minibatch_buffer_size though, not sgd_minibatch_size. So the training batch would still be the same size.
While the buffer may be smaller, and there may be speed implication, I don't how whether there will be be performance impact.

**Comment by vakker** [comment]
@gjoliver thanks for clarification. The training batch size would be the same (which in controlled by `train_batch_size` for IMPALA, not `sgd_minibatch_size` if I understand it correctly), but the number of batches that the trainer iterates through each "epoch" depends on the `minibatch_buffer_size`. 

E.g. if `num_sgd_iter=10`, `minibatch_buffer_size=1` and `train_batch_size=500`, then the trainer is going to do 10 passes over the same 500 samples, while if `minibatch_buffer_size=5`, then the trainer is going to do 10 passes over 5 batches of 500 samples. 

Is that correct? If so, then I would assume that it has a performance implication, because it's easier for the policy to overfit in the `minibatch_buffer_size=1` case compared to `minibatch_buffer_size=5`. Or maybe this is irrelevant, I'm not sure.

**Comment by gjoliver** [comment]
@vakker 🤯 too many confusing parameters.
I hope minibatch_buffer_size doesn't have impact on how many times a mini_batch gets used. need to double check.
and in general, if same data gets trained on for fewer times, it is less likely to get overfit.
@sven1977 would know this instantly. I will try to double check when I get a chance.

**Comment by vakker** [comment]
@gjoliver have you had the chance to look into this? Do you need any further info?
