### ISSUE TITLE
[Bug] [C++ API] Calling `Put` results in undefined behaviour?

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21336]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

NativeRuntime inherits from AbstractRuntime's `string Put(sbuffer)` method.
NativeRuntime does not initialize `unique_ptr<WorkerContext> worker_`
However, `string Put(sbuffer)` is defined:
```cpp
std::string AbstractRayRuntime::Put(std::shared_ptr<msgpack::sbuffer> data) {
  ObjectID object_id =
      ObjectID::FromIndex(worker_->GetCurrentTaskID(), worker_->GetNextPutIndex());
  Put(data, &object_id);
  return object_id.Binary();
}
```
On the other hand, the user facing API is:
```cpp
template <typename T>
inline ray::ObjectRef<T> Put(const T &obj) {
  auto buffer =
      std::make_shared<msgpack::sbuffer>(ray::internal::Serializer::Serialize(obj));
  auto id = ray::internal::GetRayRuntime()->Put(buffer);
  return ray::ObjectRef<T>(id);
}
```
Ergo, calling `Put` would trigger undefined behaviour by calling a member function on a `nullptr`.

Is this correct? @qicosmos @SongGuyang 

If it is correct, why doesn't it break the tests? In particular, in `cluster_mode_tests.cc`:
```cpp
auto obj = ray::Put(12345);
auto get_result = *(ray::Get(obj));
EXPECT_EQ(12345, get_result);
```

### Versions / Dependencies

ray master

### Reproduction script

read code

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jon-chuang** [comment]
This is indeed confirmed by this piece of code
```cpp
std::string AbstractRayRuntime::Put(std::shared_ptr<msgpack::sbuffer> data) {
  auto is_null = worker_ == nullptr;
  RAY_LOG(INFO) << "Triggering this pathway: " << is_null;
  ObjectID object_id =
      ObjectID::FromIndex(worker_->GetCurrentTaskID(), worker_->GetNextPutIndex());
  Put(data, &object_id);
  return object_id.Binary();
}
```
and this output
```cpp
abstract_ray_runtime.cc:91: Triggering this pathway: 1
```
when calling `bazel run cluster_mode_test`

Could you guys fix so that the code does not depend on undefined behaviour?

**Comment by qicosmos** [comment]
I think it's a bug, i will fix it, thank you.
