### ISSUE TITLE
[Core][Bug] decision_tree_autoscaling_20_runs is flaky

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#21349]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Looks worker crashed during start up?
```
2021-12-28 04:16:51,152 INFO worker.py:853 -- Connecting to existing Ray cluster at address: 172.31.29.225:6379
(best_split_for_idx_remote pid=288, ip=172.31.45.66) 2021-12-28 04:20:36,449    ERROR worker.py:432 -- SystemExit was raised from the worker.
(best_split_for_idx_remote pid=288, ip=172.31.45.66) Traceback (most recent call last):
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "python/ray/_raylet.pyx", line 770, in ray._raylet.task_execution_handler
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "python/ray/_raylet.pyx", line 591, in ray._raylet.execute_task
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "decision_tree/cart_with_tree.py", line 305, in best_split_for_idx_remote
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "decision_tree/cart_with_tree.py", line 266, in best_split_for_idx
(best_split_for_idx_remote pid=288, ip=172.31.45.66)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 429, in sigterm_handler
(best_split_for_idx_remote pid=288, ip=172.31.45.66)     sys.exit(1)
(best_split_for_idx_remote pid=288, ip=172.31.45.66) SystemExit: 1
(best_split_for_idx_remote pid=2551, ip=172.31.42.15) 2021-12-28 04:20:36,444   ERROR worker.py:432 -- SystemExit was raised from the worker.
(best_split_for_idx_remote pid=2551, ip=172.31.42.15) Traceback (most recent call last):
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "python/ray/_raylet.pyx", line 770, in ray._raylet.task_execution_handler
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "python/ray/_raylet.pyx", line 591, in ray._raylet.execute_task
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "python/ray/_raylet.pyx", line 629, in ray._raylet.execute_task
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "decision_tree/cart_with_tree.py", line 305, in best_split_for_idx_remote
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "decision_tree/cart_with_tree.py", line 266, in best_split_for_idx
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 429, in sigterm_handler
(best_split_for_idx_remote pid=2551, ip=172.31.42.15)     sys.exit(1)
(best_split_for_idx_remote pid=2551, ip=172.31.42.15) SystemExit: 1
```

[Seems ](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_MJ5X9U99DusXAHEnVmGxwYiR?command-history-section=command_history&job-section=deployments)

### Versions / Dependencies

latest ray on product.

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Maybe we should try reproducing it?

**Comment by scv119** [comment]
The plan is to kick off 20 runs with different fetch_object timeout to see if the OBOD broadcast timeout is the issue.

kicking off 20 runs with 10 minutes timeout here: https://session-dbhm6gl2dhnke5cyn7ipnuny.i.anyscaleuserdata.com/jupyter/lab

and also kicking off 20 runs with 60 minutes timeout.

**Comment by scv119** [comment]
I have been stress testing the test for 40 runs and didn't get a reproduce. Also reading the log it seems most likely 

1. the node was killed due to unexpected failures (could it be infra failures?)
2. the worker node OOMed.

Reading the log it looks the worker was killed even before we submitting the job; so it's likely 1 is more probable?

**Comment by rkooo567** [comment]
cc @DmitriGekhtman I remember there was a feature request to dispaly autoscaler events better on the prod. Has this been deprioritized? It'll be really useful for debugging this sort of failures (that could be related to autoscaler)

**Comment by DmitriGekhtman** [comment]
Deprioritized, though we're still entertaining thoughts of better log viewing over there.. are there autoscaling logs available? I'd be most willing to strain my eyeballs at them.

**Comment by rkooo567** [comment]
Autoscaling logs seem to be lost after the cluster shutdown. Only head node logs are left

**Comment by DmitriGekhtman** [comment]
Maintaining logs should be a priority. Also, we'll want to migrate to the new stack at some point.

**Comment by scv119** [comment]
Hasn't have a reproduction since Jan 3rd. Probably not worth investigating at the moment.
