### ISSUE TITLE
[Core] [Bug] ray.util.multiprocessing.Pool slower than multiprocessing.Pool

### ISSUE THREAD

**Issue by yogeveran** [ray-project/ray#21343]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

I checked the efficiency of ray.util.multiprocessing.Pool and found that locally it is slower than multiprocessing.Pool
I tested with 
Ray  1.6.0
Python 3.6.9
linux.

Code:
`

  import os
  import time
  import numpy as np
  from ray.util.multiprocessing import Pool as RPool
  from multiprocessing import Pool as MPool
  import ray
  
  

  def f(index: int):
      return np.log2(index + 1) + np.log10(index + 1)
  
  

  if __name__ == '__main__':
  
      ray.init()
      s = time.time()
      pool = RPool()
      results = list(pool.map(f, range(1000)))
      print(len(results))
      print('RPool', time.time() - s)
      ray.shutdown()
  
      s = time.time()
      pool = MPool()
      results = list(pool.map(f, range(1000)))
      print(len(results))
      print('MPool', time.time() - s)

`
    
Output was:    
1000
RPool 0.8084681034088135
1000
MPool 0.03540182113647461

### Versions / Dependencies

Ray 1.6.0
Python 3.6.9
linux.

### Reproduction script

import os
import time

import numpy as np
from ray.util.multiprocessing import Pool as RPool
from multiprocessing import Pool as MPool

import ray

def f(index: int):
    return np.log2(index + 1) + np.log10(index + 1)

if __name__ == '__main__':
    ray.init()
    s = time.time()
    pool = RPool()
    results = list(pool.map(f, range(1000)))
    print(len(results))
    print('RPool', time.time() - s)
    ray.shutdown()

    s = time.time()
    pool = MPool()
    results = list(pool.map(f, range(1000)))
    print(len(results))
    print('MPool', time.time() - s)

### Anything else

Every run.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
Could you try running this on latest master (a [nightly wheel](https://docs.ray.io/en/master/installation.html#daily-releases-nightlies)) to see if this is still the case? Ray has changed a good bit since 1.6!

**Comment by yogeveran** [comment]
Ray version 1.9.1 and 2.0.0.dev0 still suffers with a ~4 slowdown (ran on google colab).
Python 3.7.12

**Comment by richardliaw** [comment]
Can you instead try using `ray.data` here? 

In my experience, ray data is way faster than the pool API.

**Comment by yogeveran** [comment]
I changed the numpy operation to time.sleep(0.01).
Seems like there a slight overhead to Ray Pool however it is negligible for long operations.
![image](https://user-images.githubusercontent.com/9862270/148371365-a78b2d28-8fc3-41f9-a794-47106b1d0bb8.png)

I don't think using ray.data instead is worthwhile, doesn't solve the main issue.

**Comment by richardliaw** [comment]
Why doesn’t it solve the main issue? Isn’t the main issue a question on how
to get fast performance?

**Comment by yogeveran** [comment]
Nope :) 
It was just an example to show that switching from 
multiprocessing.Pool to ray.util.multiprocessing.Pool
on local machine could have negative impact on runtime.
I thought perhaps it should be addressed.
