### ISSUE TITLE
[Core][Bug] dask_on_ray_1tb_sort is flaky

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#21346]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_GrXJdM9i4sBUJ2Vitg1de7xR?command-history-section=command_history
the latest run failed with object location not found error.
```
Trial 0 start
Traceback (most recent call last):
  File "dask_on_ray/dask_on_ray_sort.py", line 209, in <module>
    file_path=args.file_path)
  File "dask_on_ray/dask_on_ray_sort.py", line 130, in trial
    10, npartitions=-1))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1096, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/dataframe/core.py", line 1130, in _head
    result = result.compute()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 182, in ray_dask_get
    result = ray_get_unpack(object_refs, progress_bar_actor=pb_actor)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 475, in ray_get_unpack
    computed_result = get_result(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/dask/scheduler.py", line 463, in get_result
    return ray.get(object_refs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1740, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: [36mray::dask:('head-1000-10-sort_index-83dded8a012efbd64d576d110747e40c', 0)[39m (pid=1883, ip=10.0.2.136)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: [36mray::dask:('head-partial-10-sort_index-83dded8a012efbd64d576d110747e40c', 5)[39m (pid=1884, ip=10.0.2.136)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: [36mray::dask:('sort_index-83dded8a012efbd64d576d110747e40c', 5)[39m (pid=1884, ip=10.0.2.136)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: [36mray::dask:('simple-shuffle-b816d627453488d9321c08feb88fb166', 5)[39m (pid=196, ip=10.0.2.85)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object a35cf0632d2a65124d4edd08ecb54563bb6836ec0200000002000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

Fetch for object a35cf0632d2a65124d4edd08ecb54563bb6836ec0200000002000000 timed out because no locations were found for the object. This may indicate a system-level bug.
```

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
cc @rkooo567  any insight?

**Comment by rkooo567** [comment]
@scv119 I think we didn't merge anything that could be related to this flakiness. 

@stephanie-wang Do you have any guess? This seems to happen if the object is not pulled for 10 minutes. I think sometimes object pulling can be very slow for dask on ray 1tb. Is the timer ever refreshed in some cases (like when it is retried?)

**Comment by stephanie-wang** [comment]
Oh it could be related to #20516. The timer is supposed to only fire if there are no locations found for the object, but maybe there's a bug.

**Comment by rkooo567** [comment]
@stephanie-wang What's the case the lookup takes long time? It seems like it is initiated upon pulling, so 

1. Resources are ready for the task
2. All dependencies are ready in the cluster

So, if it takes 10+ minutes to lookup location, that's only when failures happen?

**Comment by stephanie-wang** [comment]
It should only be when it attempts a pull but there are no locations for the object. Normal pull retries won't trigger the error as long as they succeed in finding a location to pull from.

**Comment by rkooo567** [comment]
So, it seems like there are 2 times locations are not found. I am trying to figure out if it is a bug or due to some resources limit (e.g., high cpu or slow network)

1. OBOD is not updated -> shouldn't happen because tasks are scheduled after deps are ready
2. Pull is already cancelled -> I don't exactly know when this happens, but my impression is it shouldn't happen in Dask on Ray
3. OBOD subscription is slow -> Could happen when the driver or raylet has high CPU usage
4. Objects are lost -> didn't happen based on logs

So, it is highly likely case 3?

**Comment by stephanie-wang** [comment]
Yeah my guess it is either 3 or there is a bug in the error reporting.

**Comment by rkooo567** [comment]
I think we need to try reproducing & investigating it

**Comment by scv119** [comment]
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_DBhM6GL2DHnKe5cyN7iPNUnY?command-history-section=command_history
another case of timeout

**Comment by scv119** [comment]
kicking off 20 runs with 10 minutes timeout here: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_DBhM6GL2DHnKe5cyN7iPNUnY

**Comment by scv119** [comment]
Hmm both of them succeeded running for last 40 runs or so. Should I try to increate the timeout as it seems the most probably root cause?

**Comment by rkooo567** [comment]
What about we decrease the timeout and see if it fails more often? (maybe like 3 minutes?)

**Comment by scv119** [comment]
huh, let me try that out

**Comment by scv119** [comment]
Another not yet-to-reproduce bug
