### ISSUE TITLE
[kubernetes][Bug] Error computing CPU usage on minikube 

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#21353]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Refer to discussion:
https://discuss.ray.io/t/logging-error-computing-cpu-usage-of-ray-kubernetes/4435

### Versions / Dependencies

Refer to discussion:
https://discuss.ray.io/t/logging-error-computing-cpu-usage-of-ray-kubernetes/4435

### Reproduction script

Refer to discussion:
https://discuss.ray.io/t/logging-error-computing-cpu-usage-of-ray-kubernetes/4435

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wuisawesome** [comment]
may be relatedc to #20614

**Comment by shrekris-anyscale** [comment]
Another user that's deploying Ray on Kubernetes running on Docker Desktop ran into a similar issue: https://discuss.ray.io/t/error-computing-cpu-usage-of-ray-kubernetes-pod-docker-desktop/4606

**Comment by lihost** [comment]
Thank you @shrekris-anyscale.
 
Hi @DmitriGekhtman, while this is being resolved, do we have any workaround to this so that we can test our deployments locally?

**Comment by DmitriGekhtman** [comment]
The exceptions are benign (but extremely annoying).
A suboptimal temporary workaround while I work on a fix is to downgrade docker desktop to a version before 4.30
Related: https://github.com/earthly/earthly/issues/1533

**Comment by lihost** [comment]
Thanks @DmitriGekhtman. Downgraded to 4.2.0 and it worked.

**Comment by DmitriGekhtman** [comment]
Following up: This is fixed in [linked](https://github.com/ray-project/ray/pull/21688). Things should now work with the latest Docker Desktop.

**Comment by DmitriGekhtman** [comment]
However, the first release including the fix was the recent Ray 1.12.0.
