### ISSUE TITLE
[RLlib] Change Occurrences of `RemoteVectorEnv` to `RemoteBaseEnv`

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#21359]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

this should probably be RemoteBaseEnv, https://github.com/ray-project/ray/blob/master/rllib/utils/pre_checks.py#L27

### Versions / Dependencies

N/a

### Reproduction script

N/a

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
is this done? @avnishn ?

**Comment by gjoliver** [comment]
hey man, this should be closed right?

**Comment by avnishn** [comment]
Yerp.
