### ISSUE TITLE
[Feature Request] [Serve] Pass back application exceptions from Serve deployments

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#21365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

This feature will pass back any application errors that are raised in a Serve deployment.

### Use case

Currently, if there are application exceptions in a class's `__init__()` method (and possible throughout other methods in the class), and if the user calls `deploy()` on that class, it will fail and raise only an `async_goal_exception`. The application error inside the `__init__()` method is not passed back to the user, making it seem like a Serve issue instead of an application issue. Passing back the application error expedites the user's Serve development journey and reduces surprise.

### Related issues

See #21299 for an example where a user must debug an application error despite Serve obfuscating it.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
dup of https://github.com/ray-project/ray/issues/22418
