### ISSUE TITLE
[Core] [Bug] ray memory command produces inconsistent results

### ISSUE THREAD

**Issue by xinchen384** [ray-project/ray#21384]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Monitoring & Debugging, Dashboard

### What happened + What you expected to happen

We use the command "ray memory" to check the status of Ray's object store. It turns out that the result generated from the command is very confusing. 

The testbed needs to have two nodes. On one node, an object is put into object store, and then run the command to check the status. The aggregated results on both nodes are not consistent with the summary.  
(1) On the 47 node running the command, the summary of the 12 node is 264B, the summary of the 47 node is 1600MB, but the aggregated is 762MB.
(2) On the 12 node running the command, the summary of the 12 node is 800MB, the summary of the 47 node is 800MB, but the aggregated is 762MB.

The summary and the aggregated results seem using different metrics, in terms of what is counted and what is not counted. At least, the number should be consistent.

The following is the logs.

check_memory pid=3591574, ip=10.128.91.47) ======== Object references status: 2022-01-05 08:40:04.983423 ========
(check_memory pid=3591574, ip=10.128.91.47) Grouping by node address...        Sorting by object size...        Display allentries per group...
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) **_--- Summary for node address: 10.128.115.12 ---_**
(check_memory pid=3591574, ip=10.128.91.47) Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
(check_memory pid=3591574, ip=10.128.91.47) **_264.0 B_**              2, (263.0 B)      0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           2, (-2.0 B)  
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) --- Object references for node address: 10.128.115.12 ---
(check_memory pid=3591574, ip=10.128.91.47) IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.115.12 | 447254 | Driver |           | ?    | LOCAL_REFERENCE | ee4e90da584ab0ebffffffffffffffffffffffff0100000001000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.115.12 | 447254 | Driver | <unknown> | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.115.12 | 447254 | Driver |           | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000001000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.115.12 | 447254 | Driver |           | 264.0 B | LOCAL_REFERENCE | 69a6825d641b46135ba0f22968968612a61467950100000001000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) -**_-- Summary for node address: 10.128.91.47 ---_**
(check_memory pid=3591574, ip=10.128.91.47) Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
(check_memory pid=3591574, ip=10.128.91.47) **_1600000510.0 B_**       0, (0.0 B)        0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           3, (1600000509.0 B)
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) --- Object references for node address: 10.128.91.47 ---
(check_memory pid=3591574, ip=10.128.91.47) IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.91.47 | 3591538 | Worker |           | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000001000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.91.47 | 3591538 | Worker |           | 800000255.0 B | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) 10.128.91.47 | 3591574 | Worker | (deserialize task arg) memory.check_memory | 800000255.0 B | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) To record callsite information for each ObjectRef created, set env variable RAY_record_ref_creation_sites=1
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=3591574, ip=10.128.91.47) **_--- Aggregate object store stats across all nodes ---
(check_memory pid=3591574, ip=10.128.91.47) Plasma memory usage 762 MiB,_** 1 objects, 0.2% full, 0.2% needed
(check_memory pid=3591574, ip=10.128.91.47) 
(check_memory pid=447289) ======== Object references status: 2022-01-05 08:40:05.533676 ========
(check_memory pid=447289) Grouping by node address...        Sorting by object size...        Display allentries per group...
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) --- **_Summary for node address: 10.128.115.12_** ---
(check_memory pid=447289) Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
(check_memory pid=447289) **_800000519.0 B_**        2, (263.0 B)      0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           3, (800000253.0 B)
(check_memory pid=447289) 
(check_memory pid=447289) --- Object references for node address: 10.128.115.12 ---
(check_memory pid=447289) IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.115.12 | 447254 | Driver |           | ?    | LOCAL_REFERENCE | 4ee449587774c1f0ffffffffffffffffffffffff0100000001000000
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.115.12 | 447254 | Driver | <unknown> | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.115.12 | 447254 | Driver |           | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000001000000
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.115.12 | 447254 | Driver |           | 264.0 B | LOCAL_REFERENCE | 69a6825d641b46135ba0f22968968612a61467950100000001000000
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.115.12 | 447289 | Worker | (deserialize task arg) memory.check_memory | 800000255.0 B | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=447289) 
(check_memory pid=447289) --- **_Summary for node address: 10.128.91.47_** ---
(check_memory pid=447289) Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
(check_memory pid=447289) 800000255.0 B        0, (0.0 B)        0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           2, (800000254.0 B)
(check_memory pid=447289) 
(check_memory pid=447289) --- Object references for node address: 10.128.91.47 ---
(check_memory pid=447289) IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.91.47 | 3591538 | Worker |           | ?    | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000001000000
(check_memory pid=447289) 
(check_memory pid=447289) 
(check_memory pid=447289) 10.128.91.47 | 3591538 | Worker |           | 800000255.0 B | ACTOR_HANDLE   | ffffffffffffffff5ba0f22968968612a61467950100000002000000
(check_memory pid=447289) 
(check_memory pid=447289) To record callsite information for each ObjectRef created, set env variable RAY_record_ref_creation_sites=1
(check_memory pid=447289) 
(check_memory pid=447289) -**_-- Aggregate object store stats across all nodes ---_**
(check_memory pid=447289) **_Plasma memory usage 762 MiB,_** 1 objects, 0.2% full, 0.2% needed
(check_memory pid=447289) 

### Versions / Dependencies

Ray = 1.9.0

### Reproduction script

```  
import ray
  import numpy as np
  import socket
  import os
  
  total_num = 100000000
  actor_name = "global_actor"
  pg_name = "pg_name"
  
  @ray.remote
  class DataActor:
      def __init__(self):
          self.data = ray.put(np.ones(total_num))
  
      def get_data(self):
          return self.data
  
  @ray.remote
  def check_memory(data):
      os.system("ray memory")
      return 1
  
  ray.init(address="auto")
  
  # define placement_group to distribute tasks 
  # across ray cluster nodes
  num_nodes = len(ray.nodes())
  
  bundles = [{"CPU": 1}]*num_nodes 
  placement_group = ray.util.placement_group(
      name = pg_name,
      strategy="SPREAD", 
      bundles=bundles,
      )
  ray.get(placement_group.ready())
  
  my_actor = DataActor.options(
      name=actor_name,
      placement_group=placement_group,
      placement_group_bundle_index=0,
      ).remote()
  
  data = my_actor.get_data.remote()
  
  ref = check_memory.options(
      placement_group=placement_group,
      placement_group_bundle_index=0,
  ).remote(data)
  result = ray.get(ref)
  
  ref = check_memory.options(
      placement_group=placement_group,
      placement_group_bundle_index=num_nodes-1,
  ).remote(data)
  result = ray.get(ref)
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@xinchen384 When running this, did you see any error-level log entries of the form `"Failed to get remote node stats: "` in the raylet logs (`/tmp/ray/session_latest/logs/raylet.err`)?

**Comment by xinchen384** [comment]
@clarkzinzow No. In the raylet logs, there is just one warning: /opt/conda/envs/py37/lib/python3.7/site-packages/ray/dashboard/modules/reporter/reporter_agent.py:38: UserWarning: `gpustat` package is not installed. GPU monitoring is not available. To have full functionality of the dashboard please install `pip install ray[default]`.)
  warnings.warn("`gpustat` package is not installed. GPU monitoring is "

**Comment by clarkzinzow** [comment]
@xinchen384 I think that there are two issues here:
1. The `Mem Used by Objects` column is misleading/incorrect, since there isn't a 1:1 mapping from object references to physical objects in the object store, i.e. physical objects in the object store can be double counted;
2. You're returning an object reference from `DataActor.get_data()`, so you're actually passing around an object reference to an object reference with `data = my_actor.get_data.remote()`, so the underlying actor data ndarray never actually gets resolved and deserialized in the `check_memory()` task.

E.g., for node with IP address 10.128.91.47 on the first run:
```
Mem Used by Objects Local References Pinned Pending Tasks Captured in Objects Actor Handles
1600000510.0 B 0, (0.0 B) 0, (0.0 B) 0, (0.0 B) 0, (0.0 B) 3, (1600000509.0 B)
--- Object references for node address: 10.128.91.47 ---
IP Address | PID | Type | Call Site | Size | Reference Type | Object Ref
10.128.91.47 | 3591538 | Worker | | 800000255.0 B | ACTOR_HANDLE | ffffffffffffffff5ba0f22968968612a61467950100000002000000
10.128.91.47 | 3591574 | Worker | (deserialize task arg) memory.check_memory | 800000255.0 B | ACTOR_HANDLE | ffffffffffffffff5ba0f22968968612a61467950100000002000000
```
Notice that the object IDs for these two references are the same, one representing the reference created when put into the store in the actor constructor:
```python
  @ray.remote
  class DataActor:
      def __init__(self):
          self.data = ray.put(np.ones(total_num))
```
and another representing the **reference to the reference** passed to the `check_memory` task:
```python
  ref = check_memory.options(
      placement_group=placement_group,
      placement_group_bundle_index=0,
  ).remote(data)
```
Note that `data` here is an object ref **containing** the `ray.put()` object ref. If you wanted to pass the `DataActor().data` reference to the task and have the task resolve the underlying object, then you'd need to pass `ray.get(data)` to the task to unwrap the outer object ref.
```python
  # my_actor.get_data.remote() returns an object reference wrapping the DataActor().data reference,
  # i.e. outer_ref = ray.ObjectRef(ray.ObjectRef(np.ndarray)), so we need to fetch the outer reference to
  # unwrap it and get the inner reference that we actually care about.
  outer_ref = my_actor.get_data.remote()
  # This is now the object reference to the data ndarray in the actor.
  data_ref = ray.get(outer_ref)
  
  ref = check_memory.options(
      placement_group=placement_group,
      placement_group_bundle_index=0,
  ).remote(data_ref)
  result = ray.get(ref)
```
Back to the memory summary: each of these references are to a single underlying object in the 10.128.91.47 node's object store that's 800 MB, which is why the aggregate object store usage is still 800 MB. However, the `Mem Used by Objects` is a naive calculation, summing up the size of the underlying object pointing to be each reference, which results in double-counting the single 800 MB object.

The second run hits the same case, since the data is never actually transferred to the 10.128.115.12 node when the `check_memory()` task is run, since the `data` argument is a doubly nested object reference; the `data` argument that's resolved and deserialized on the 10.128.115.12 node is just another object reference, for the data ndarray that's still living in the actor on the 10.128.91.47 node. If you updated your code to the snippet I gave above, you should see 1600 MB aggregate object store usage.

**Comment by xinchen384** [comment]
@clarkzinzow Thanks for your detailed explanation. Yes, what you said makes sense to me. Just to confirm my understanding here: (1)What you mean by "The Mem Used by Objects column is misleading/incorrect" is that the column counts the size of the object that the object reference is referring to, where the actual data of the object is not moved there yet, which is the reason why "The aggregated stats" does not include the size, or double-counting the size. (2) "the aggregated object store stats" reflects the actual usage, in terms of the real memory size and the number of objects. Correct me if I am wrong.

**Comment by clarkzinzow** [comment]
@xinchen384 Yep that's exactly it! I believe that you already got this, but just in case you didn't: in the case of the first run, even if you were resolving and deserializing the actual object ref (instead of a ref pointing to a ref), you'd end up referencing the ndarray via shared memory since `check_memory()` is running on the same node as the actor, so no moving or copying would be required for the first run. Moving _is_ required for the second run.

**Comment by richardliaw** [comment]
Is there any updates to the documentation to be made here?
