### ISSUE TITLE
[Core] [xlang] Support invoke overloaded Java functions from Python worker.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21380]
Currently, Python call Java remote functions doesn't support overloaded because in Python side, we don't know the signatures of the remote functions. For example, we have a overloaded functions in Java:
```java
/// In Java worker 
int f(int i) { ... }
int f(String s) { ... }
```
```python
# In Python worker
f.remote(2) # We don't know the signature of the function.
```
It will get overloaded exception from Java side.

**Comment by kfstorm** [comment]
There are several ways I can think of to mitigate the issue.

1. Allow passing the method signature when calling from Python to Java. This can be done by adding an optional parameter `signature` at https://github.com/ray-project/ray/blob/f8244a4cc0c908ed27b9569200f15e7d6eccb35c/python/ray/cross_language.py#L60
2. When the overloaded methods have different numbers of parameters, we can still infer the desired one by checking the number of provided arguments. In this way, a user shouldn't need to pass the method signature as long as there's only one overloaded method that has the same number of parameters as provided arguments.
3. Refine the exception message when a user invokes an overloaded Java method without signature to provide suggestions to fix it. The current message is:

```
RayFunction io.ray.serve.RayServeWrappedReplica.<init> is overloaded, the signature can't be empty.
```

I believe this is much better:

```
The Java method io.ray.serve.RayServeWrappedReplica.<init> is overloaded, but you're trying to call it without the method signature. This can happen if there are multiple overloaded methods that have the same number of parameters as provided arguments. You can fix it by 1) renaming methods to avoid overloading. 2) trying to differentiate the overloaded methods by the number of parameters. 3) Pass the correct Java method signature via `java_function(class_name=..., function_name=..., signature=...)` or `java_actor_class(...).foo.options(signature=...)`. You can obtain the method signature via command line tool `javap`. e.g. `javap ...`.
```

**Comment by simon-mo** [comment]
@jovany-wang @kfstorm I have implemented option 2 (match number of arguments) in https://github.com/ray-project/ray/pull/21410/commits/5dbff1358853f5874335ee2a165d1c744190de28 as part of Ray Serve PR. Please take a look!

**Comment by kfstorm** [comment]
@simon-mo Thanks for the update.

This issue will remain open because we still couldn't distinguish overloads with the same amount of parameters.

**Comment by WangTaoTheTonic** [comment]
x-lang invocation from c++ to java also has this requirement. Maybe we can consider them together.
