### ISSUE TITLE
[Core] [Feature - Perf] Scale Ray.get(): the time of calling ray.get increases linearly and adding parallelism does not help too much

### ISSUE THREAD

**Issue by xinchen384** [ray-project/ray#21399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Our application needs to fetch a large of objects using "ray.get" from Ray's object store, where each object might be small. We found that the time of calling "ray.get()" increases linearly with the number of object references, which is fine. When we want to optimize the "ray.get" operation, it seems that it is not scalable. How to parallelize this? or any other way for the speed up when ray.get on a large number of object references.

The charts below is the two results on a single node, by running the following python scripts. 
![image](https://user-images.githubusercontent.com/8742819/148263355-e9e49b18-9f0b-40b1-b003-5cffeee9124e.png) ![image](https://user-images.githubusercontent.com/8742819/148263377-9d046546-e1d3-40d4-844d-aa61fa99e319.png)

The first chart shows the time of increasing the number of object references. The other chart shows the time of "ray.get" 100000 objects with an increasing number of tasks. This runs on a single node, where the number of cores is larger than 8.

```
import ray
import time

total_size = 100000
#total_size = 100

@ray.remote
def load_data():
    return [ray.put(i) for i in range(total_size)]

@ray.remote
def test_ray_get(refs, num): 
    ref_list = refs[:num]
    start = time.time()
    res = ray.get(ref_list)
    print("#items: ", len(ref_list), "time:", time.time()-start)
    return res

data = load_data.remote()
for i in range(10):
    num = int(total_size/10)*(i+1)
    res = ray.get(test_ray_get.remote(data, num))
    #print("get result:", res)

@ray.remote
def get_task(refs):
    return ray.get(refs)

@ray.remote
def test_parallel_get(ref_list, num_parallel):
    num = len(ref_list)
    start = time.time()
    num_per_batch = int(num/num_parallel)
    if num%num_parallel > 0:
        num_per_batch += 1
    res, result, j = [], [], 0
    for _ in range(num_parallel):
        j_end = min(j+num_per_batch, num)
        res.append(get_task.remote(ref_list[j:j_end]))
        j += num_per_batch
    res = ray.get(res)
    for x in res:
        result.extend(x)
    print("parallel #items: ", len(ref_list), "time:", time.time()-start, num_parallel)
    return result

for i in range(8):
    res = ray.get(test_parallel_get.remote(data, i+1))
    #print("parallel get result:", res)
```

### Use case

This should be a generic user case, where application needs to fetch a large number of objects from the object store. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by valiantljk** [comment]
Have you measured the time of this step:
```
    for x in res:
        result.extend(x)
```

**Comment by xinchen384** [comment]
@valiantljk This step takes less than 1ms, so that should be okay.

**Comment by HuangLED** [comment]
@clarkzinzow @amogkam
