### ISSUE TITLE
[CI] [LINT] Linter failing with `AttributeError: get_tune_ddp_resources` on `1.10.0rc0` release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21426]
The linter was passing but started to fail on a commit which looks unrelated: https://github.com/ray-project/ray/commit/7fdc5470f21394a48f0328a3db57041fa6ee4b7a

It's failing with 

```
sphinx.errors.SphinxWarning: autodoc: failed to import function 'get_tune_ddp_resources' from module 'ray_lightning.tune'; the following exception was raised:
--
  | Traceback (most recent call last):
  | File "/opt/miniconda/lib/python3.6/site-packages/sphinx/util/inspect.py", line 307, in safe_getattr
  | return getattr(obj, name, *defargs)
  | AttributeError: module 'ray_lightning.tune' has no attribute 'get_tune_ddp_resources'
```

Link to failure: https://buildkite.com/ray-project/ray-builders-branch/builds/5425#03f2a852-4393-4ac2-b7ed-fd44dcc8e5ed/601-756

Link to success on the preceding commit: https://buildkite.com/ray-project/ray-builders-branch/builds/5415#dd303e26-a285-4f53-8d0f-4f641ab112b7

**Comment by architkulkarni** [comment]
@amogkam @richardliaw Is this innocuous or indicative of a deeper issue?  According to the release process CI needs to pass completely, so I think this should be a release blocker.  

I wondered if it was some upstream dependency change that caused this, but I didn't se this error in any recent Ray PRs. 
 Any ideas how to fix it?

**Comment by architkulkarni** [comment]
@simon-mo does anything jump out at you here?  The lint step should be independent of the docker build step, right? The docker build script is the only thing that changed in the breaking commit.

**Comment by simon-mo** [comment]
There might be a `ray_lightning` update?

**Comment by amogkam** [comment]
Oof this is coming from this change that I just merged  https://github.com/ray-project/ray_lightning/commit/63ab0c015c81be7246da644a7193d2d51768f45b, and in `requirements_doc.txt` we are installing Ray Lightning master.

**Comment by amogkam** [comment]
I'll make a PR to fix this real quick, but let me think about whether we want to show master or latest versions of upstream libraries (ray-lightning, xgboost-ray, lightgbm-ray, tune-sklearn) in the docs.

**Comment by architkulkarni** [comment]
Ahh makes sense.  Thanks for the quick diagnosis @amogkam!  Please let me know when your PR is ready to pick, and can you also update the release tracker? https://docs.google.com/spreadsheets/d/1si3hVTEyZ--BUz_1sS6r8m6L8utVUtyNAOzAs2KXo3s/edit#gid=0

**Comment by amogkam** [comment]
@architkulkarni https://github.com/ray-project/ray/pull/21428
