### ISSUE TITLE
[Core] [Nightly] [Flaky] `many_drivers` test failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#21432]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```
(run_driver pid=3156456) ray.exceptions.RayTaskError(RayOutOfMemoryError): ray::f() (pid=3167980, ip=172.31.62.177)
--
  | (run_driver pid=3156456) ray._private.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ip-172-31-62-177 is used (29.1 / 30.57 GB). The top 10 memory consumers are:
  | (run_driver pid=3156456)
  | (run_driver pid=3156456) PID	MEM	COMMAND
  | (run_driver pid=3156456) 755	21.37GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dash
  | (run_driver pid=3156456) 729	0.41GiB	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s
  | (run_driver pid=3156456) 800	0.11GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/log_m
  | (run_driver pid=3156456) 51	0.09GiB	/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session web_terminal_server --deploy
  | (run_driver pid=3156456) 378	0.09GiB	/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/anyscale session auth_start
  | (run_driver pid=3156456) 691	0.09GiB	python workloads/many_drivers.py
  | (run_driver pid=3156456) 834	0.09GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen
  | (run_driver pid=3156456) 890	0.08GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen
  | (run_driver pid=3156456) 1014	0.08GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agen
  | (run_driver pid=3156456) 953	0.08GiB	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/agenTraceback (most recent call last):
  | File "workloads/many_drivers.py", line 95, in <module>
  | ray.get(ready_id)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
  | return func(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1742, in get
  | raise value.as_instanceof_cause()
  | ray.exceptions.RayTaskError(CalledProcessError): ray::run_driver() (pid=3136504, ip=172.31.62.177)
  | File "workloads/many_drivers.py", line 80, in run_driver
  | output = run_string_as_driver(driver_script)
  | subprocess.CalledProcessError: Command '['/home/ray/anaconda3/bin/python', '-']' returned non-zero exit status 1.
```

It seems the cluster is OOMing and the dashboard is to blame. 

### Versions / Dependencies

master

### Reproduction script

Run the weekly tests. example output: https://buildkite.com/ray-project/periodic-ci/builds/2247#309c72ce-6ceb-4e86-9470-3c429fb1bf81

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Description?

**Comment by mwtian** [comment]
It seems to pass in the latest run? https://buildkite.com/ray-project/periodic-ci/builds/2262#9abe2370-25b5-48cf-8db8-bf7fac7e7d13 Or does this fail with GCS bootstrapping configured?

**Comment by ericl** [comment]
I believe this is flaky, which is considered a P0 for nightly tests.

**Comment by clarkzinzow** [comment]
@iycheng Not a big deal, but we already had an [issue](https://github.com/ray-project/ray/issues/21413) open for this! In the future, don't forget to check for existing issues before opening a new one.

**Comment by wuisawesome** [comment]
I've run this a few times now (on the nested task branch), and it seems to pretty consistently fail after ~8hours.

@mwtian you're looking at the nightly version which only runs for 1hr.

**Comment by rkooo567** [comment]
How is dashboard using 20GB of data.. lol Is it possible to do some memory profiling?

**Comment by iycheng** [comment]
> Description?

Sorry, this ticket was created during standup just for a reminder purpose and the description was planned to be added later.

Overall it looks like a memory leak in the dashboard. THe plan here is to do some profiling and track the memory usage.

**Comment by mwtian** [comment]
@iycheng maybe we can sync up tomorrow and I will give memory profiling a try?

**Comment by iycheng** [comment]
> I've run this a few times now (on the nested task branch), and it seems to pretty consistently fail after ~8hours.
> 
> @mwtian you're looking at the nightly version which only runs for 1hr.

Notice there is a session that's running ok for more than 1 day. ([session](https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Wbgw3faihSQpHqV6pc5rABxC?command-history-section=command_history&user=usr_6IEyi1L0swJAKPY1Yjpml4))

I also reproduced, although not consistently, it somehow on the cluster. It seems flaky. I compared the dashboard logs, they seem similar.

Tried tracemalloc, but not luck in the run. We can give it another try tmr @mwtian

**Comment by iycheng** [comment]
![image](https://user-images.githubusercontent.com/74173148/148628487-0c255e7d-aca0-422a-b8a2-ff86f234cbb2.png)

It seems like I was wrong. The memory just increases slowly. 

The wired thing here is that from tracemalloc snapshot, it only claims 700mb memory used.

One thing that is not released is about the actor info in dashboard, but from the calculation, it shouldn't use more than 1gb.

**Comment by iycheng** [comment]
I disable the actor info in dashboard ad-hoc, and the issues are still there. If we trust tracemalloc, then the leak has to be in cpp layer. I'll profile the memory there.

**Comment by iycheng** [comment]
The job with actor info disabled is still running. It still has leak, but overall it only uses 4GB memory. The leak should come from other places in the dashboard/gcs.

We still should investigate this issue further, but a short-term solution is to purge the actor and keep only a limited number of actor info in the dashboard.

I'll create a PR to mitigate this issue first.


![image](https://user-images.githubusercontent.com/74173148/148889365-cd737619-51a3-4239-b4a1-8194c960509a.png)

**Comment by iycheng** [comment]
Segmentation fault which is not related to this issue but happened when I'm testing the fix

```
(run_driver pid=1955598) success
(run_driver pid=1955598) *** SIGSEGV received at time=1642049153 on cpu 5 ***
(run_driver pid=1955598) PC: @     0x7f86eb1cc378  (unknown)  instrumented_io_context::GetOrCreate()
(run_driver pid=1955598)     @     0x7f86ec2b83c0       3568  (unknown)
(run_driver pid=1955598)     @     0x7f86eb1ccaca        160  instrumented_io_context::RecordStart()
(run_driver pid=1955598)     @     0x7f86eb1d1940        256  ray::PeriodicalRunner::DoRunFnPeriodicallyInstrumented()
(run_driver pid=1955598)     @     0x7f86eb1d1e10        160  std::_Function_handler<>::_M_invoke()
(run_driver pid=1955598)     @     0x7f86eb1cbb2b        128  instrumented_io_context::RecordExecution()
(run_driver pid=1955598)     @     0x7f86eb1d02d1        544  boost::asio::detail::wait_handler<>::do_complete()
(run_driver pid=1955598)     @     0x7f86eb60e90c        128  boost::asio::detail::scheduler::do_run_one()
(run_driver pid=1955598)     @     0x7f86eb60f7c1        208  boost::asio::detail::scheduler::run()
(run_driver pid=1955598)     @     0x7f86eb60fd20         64  boost::asio::io_context::run()
(run_driver pid=1955598)     @     0x7f86eafac3f5        128  std::thread::_State_impl<>::_M_run()
(run_driver pid=1955598)     @     0x7f86ea890039  (unknown)  execute_native_thread_routine
(run_driver pid=1955598)     @     0x5580fd4619d0  (unknown)  (unknown)
(run_driver pid=1955598)     @     0x7f86eafabd50  (unknown)  (unknown)
(run_driver pid=1955598)     @ 0x90ffd53871e90789  (unknown)  (unknown)
(run_driver pid=1955598) [2022-01-12 20:45:53,886 E 1979083 1979243] logging.cc:317: *** SIGSEGV received at time=1642049153 on cpu 5 ***
(run_driver pid=1955598) [2022-01-12 20:45:53,886 E 1979083 1979243] logging.cc:317: PC: @     0x7f86eb1cc378  (unknown)  instrumented_io_context::GetOrCreate()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86ec2b83c0       3568  (unknown)
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb1ccaca        160  instrumented_io_context::RecordStart()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb1d1940        256  ray::PeriodicalRunner::DoRunFnPeriodicallyInstrumented()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb1d1e10        160  std::_Function_handler<>::_M_invoke()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb1cbb2b        128  instrumented_io_context::RecordExecution()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb1d02d1        544  boost::asio::detail::wait_handler<>::do_complete()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb60e90c        128  boost::asio::detail::scheduler::do_run_one()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb60f7c1        208  boost::asio::detail::scheduler::run()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eb60fd20         64  boost::asio::io_context::run()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86eafac3f5        128  std::thread::_State_impl<>::_M_run()
(run_driver pid=1955598) [2022-01-12 20:45:53,887 E 1979083 1979243] logging.cc:317:     @     0x7f86ea890039  (unknown)  execute_native_thread_routine
(run_driver pid=1955598) [2022-01-12 20:45:53,888 E 1979083 1979243] logging.cc:317:     @     0x5580fd4619d0  (unknown)  (unknown)
(run_driver pid=1955598) [2022-01-12 20:45:53,893 E 1979083 1979243] logging.cc:317:     @     0x7f86eafabd50  (unknown)  (unknown)
(run_driver pid=1955598) [2022-01-12 20:45:53,894 E 1979083 1979243] logging.cc:317:     @ 0x90ffd53871e90789  (unknown)  (unknown)
(run_driver pid=1955598) Fatal Python error: Segmentation fault
(run_driver pid=1955598) 
```

**Comment by rkooo567** [comment]
@iycheng this must be related to the recent event stats.

I have a speculative fix PR. How commonly this happens? Maybe this is a good script to test if things are fixed by this PR

**Comment by rkooo567** [comment]
Also you can use this tool to actually see the trend of memory usage growth per process;

https://github.com/ray-project/ray/blob/619478331240612f408a90a445bb3dea56d13696/release/nightly_tests/dask_on_ray/large_scale_test.py#L446

**Comment by iycheng** [comment]
@rkooo567  not very frequently. I only encounter it once.

**Comment by rkooo567** [comment]
I see. I think the java build is kind of flaky by the same segfault, so I will run it 10 times in a row to see if this fixes the issue

**Comment by iycheng** [comment]
When I'm trying to fix the issue, I also did bisect. Things are pretty interesting since this PR caused the leak
https://github.com/ray-project/ray/pull/20882
it's touches nothing for dashboard. 

I'm testing master now to see whether function table clean up is helpful here.

**Comment by iycheng** [comment]
Running with the master for one hour and it seems really good. I'll lower the priority to P1 for now.

![image](https://user-images.githubusercontent.com/74173148/149597518-ee669dd9-7441-495c-ac7f-0b434aba2362.png)

**Comment by iycheng** [comment]
Change to P0 again :( 

It seems there is a bug there which leads function lost:

`2022-01-14 15:54:14,588 WARNING worker.py:1259 -- This worker was asked to execute a function that it does not have registered. You may have to restart Ray.`

**Comment by ericl** [comment]
Hmm, is that a regression?

**Comment by iycheng** [comment]
The fix of function table here https://github.com/ray-project/ray/pull/21616

**Comment by iycheng** [comment]
> Hmm, is that a regression?

definitely, it is.

**Comment by iycheng** [comment]
Things are wired here. I'm writing down the following observations:

- With the fixing of function table, #21616 it's still not working. Basically OOM in the dashboard
- This #20882 makes the regression. Either commit before this PR or revert this PR on the master will fix the issue. But that PR doesn't touch the dashboard and that's the weirdest part.
- Stop recording actor info in the dashboard seems to fix the issue. But before #20882 there is no issue at all. So I'm wondering whether it's the right direction to go.
- tcmalloc shows memory leak in python, not cpp.

**Comment by iycheng** [comment]
One thing might not be related to this one is that, it seems promtail in testing env is using a lot of memory.
```
9073 root      20   0   19.8g  16.3g   8828 S 427.9  52.9  15131:00 promtail                                                                                                            
```

**Comment by rkooo567** [comment]
This is interesting. Any possibility the memory report was wrong or has a bug? Is it consistent when you check htop in the middle of the test run?

**Comment by iycheng** [comment]
> This is interesting. Any possibility the memory report was wrong or has a bug? Is it consistent when you check htop in the middle of the test run?

It's consistent.

**Comment by iycheng** [comment]
objgraph shows:
```
dict                  885246
list                  868636
ImmutableDict         568995
weakref               269427
Context               264750
coroutine             264745
frame                 264735
Task                  264706
Future                264699
TaskWakeupMethWrapper 264698
```

**Comment by iycheng** [comment]
Lower the priority to P1.
The reason it failed is that the master is faster after this [PR](https://github.com/ray-project/ray/pull/21616).

Memory leak still exists in the dashboard. But without this PR, every worker basically needs to import a lot of things and it slows the driver's performance.

We can see from this log
```
Iteration 2221:
  - Iteration time: 91.22895789146423.
  - Absolute time: 1639977131.3817475.
  - Total elapsed time: 82505.75467967987.
Iteration 2222:
  - Iteration time: 89.64419484138489.
  - Absolute time: 1639977221.0259423.
  - Total elapsed time: 82595.39887452126.
Iteration 2223:
  - Iteration time: 70.22041773796082.
  - Absolute time: 1639977291.24636.
  - Total elapsed time: 82665.61929225922.
Iteration 2224:
  - Iteration time: 141.53751230239868.
  - Absolute time: 1639977432.7838724.
  - Total elapsed time: 82807.15680456161.
```
It cost a lot of time to finish one iteration and within 24h, it only finished 2k iterations.




With this PR, it's like:
```
Iteration 4001:
  - Iteration time: 0.95485520362854.
  - Absolute time: 1643077687.9250314.
  - Total elapsed time: 26973.94828104973.
Iteration 4002:
  - Iteration time: 20.370080947875977.
  - Absolute time: 1643077708.2951124.
  - Total elapsed time: 26994.318361997604.
Iteration 4003:
  - Iteration time: 4.543852806091309.
  - Absolute time: 1643077712.8389652.
  - Total elapsed time: 26998.862214803696.
Iteration 4004:
  - Iteration time: 1.0939826965332031.
  - Absolute time: 1643077713.9329479.
  - Total elapsed time: 26999.95619750023.
```
This is about 8h, and it has run for 4k iterations.

The reason the slop of memory consumption is smaller as time goes by this PR is that the test is running slower as time goes.

There are a couple of options here:
- remove the expensive fields in actors (I probably will do this)
- limit the actor numbers (we'll lose the actor history as time going)
- store the info into disk-based DBS. (long-term plan maybe).

**Comment by wuisawesome** [comment]
nit: i think we've tried both of these things for actors, but not for jobs, so maybe that's where it needs to be done.

> limit the actor numbers (we'll lose the actor history as time going)

Can we make sure to let this stuff expire over time, not based on the number? that way we keep the guarantee that the snapshot can provide the data.

**Comment by iycheng** [comment]
@wuisawesome I think snapshot is reading data from GCS and limit numbers of actor history is for actors in `dashboard.DataCenter`.

But yeah, I think I'll only remove the unused fields in actors, like TaskSpec in `DataCenter.actor`

**Comment by wuisawesome** [comment]
ah i see, as long as you're removing it in the dashboard (and not the snapshot part), sounds good. i thought you were going to remove it from the ray core originally

**Comment by mwtian** [comment]
Should this be a P0 release blocker for 1.11.0, and should the fixes be merged to the release branch? cc @zhe-thoughts @ericl

**Comment by iycheng** [comment]
With the fix it can only reach to 5k iterations which are really wired since the observation for the memory growth is much more flat for the first several hours.
```
Iteration 5306:
  - Iteration time: 6.7853617668151855.
  - Absolute time: 1643347443.2771993.
  - Total elapsed time: 40198.51408481598.
```

I'll change the testing to run it only for 4k iterations.

**Comment by rkooo567** [comment]
@iycheng do we have a separate issue for tracking memory leak? I think we can close this and track that one instead

**Comment by iycheng** [comment]
Here: https://github.com/ray-project/ray/issues/22027
