### ISSUE TITLE
Linting for Java code.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2145]
We currently use `clang-format` to lint the C++ code and a combination of `yapf` and `flake8` to lint the Python code. These are tested in Travis. We should also do linting for the Java code to maintain a clean/consistent style.

What is the best practice here? Also, what does Arrow do?

cc @imzhenyu @salah-man @eric-jj

**Comment by pcmoritz** [comment]
Arrow is using this: https://github.com/apache/arrow/blob/master/java/dev/checkstyle/checkstyle.xml (see http://checkstyle.sourceforge.net/)

I wonder what Ant is using, it might be the easiest to use the same so we can keep consistency here.

**Comment by salah-man** [comment]
As far as i know, in Ant we have two ways to do the java code linting .
First, Ant has our own IDE plugin to help the developer to format code during coding process at real time, and could custom rules by something like *.xml, and we could also use the Eclipse Code Formatter instead which is open source.
Secode, to do the linting check in ci, we could add com.googlecode.maven-java-formatter-plugin to our pom.xml to do the code format, and add maven-checkstyle-plugin to do the style check which could use the command like mvn checkstyle binding to the CI. 
And we could reference https://github.com/alipay/sofa-rpc/blob/master/pom.xml

**Comment by salah-man** [comment]
Here comes the java code lint check and binding to the CI(https://github.com/ant-tech-alliance/ray/pull/26),  and when we finish the code review inner Ant of this PR, i will submit the PR to the Ray master, and you could review the code from the PR above, thanks.

**Comment by salah-man** [comment]
And the tool of java code lint(maven-checkstyle-plugin) and the detail rules(Google Style) almost the same as Apache Arrow.

**Comment by salah-man** [comment]
Here is the PR to the master(https://github.com/ray-project/ray/pull/2225), thanks.

**Comment by robertnishihara** [comment]
Addressed by #2225.
