### ISSUE TITLE
[Java][RuntimeEnv] Support jars for runtime env.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

#### 1. Actor or task level
```java
RuntimeEnv runtimeEnv = RuntimeEnv.builder()
    .setJars(Lists.of("jar1_url", ""jar2_url", ...))
    .build();
Actor<> actor = Ray.actor(...).setRuntimeEnv(runtimeEnv).remote();
```

#### 2. Job level
```yaml
job {
  runtime-env: {
     "jars":[
         // Job agent will download these jars, add them to the classpath.
         "https://host/a.jar"
     ]
  }
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
@SongGuyang @chenk008 CC

**Comment by Bowen0729** [comment]
Will it be released in the next version？

**Comment by jovany-wang** [comment]
> Will it be released in the next version？

I believe it's impossible to release it in 1.10.0. I'm not sure if we can release it in 1.11.0.

**Comment by SongGuyang** [comment]
@Bowen0729 Do you have any requirements about java runtime env?

**Comment by Bowen0729** [comment]
Actually,  when I run ray cluster on yarn, jar files are stored on HDFS, which have different absolute path in each node. In such case, how can I run a java worker? And I think this feature could fix my point, I can setJars for java workers.

**Comment by SongGuyang** [comment]
Yep, I think java runtime env can help you. We will support this feature recently. Please pay attention to the state of current issue and release notes.

**Comment by jovany-wang** [comment]
Items were finished.
