### ISSUE TITLE
[Feature] [Xlang] Auto method name translation

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#21474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

A common issue when communicating between Java and Python using the cross language API is the method name convention is not consistent for the language. 

For example when calling java from Python
```python
counter_class = ray.java_actor_class(
      "io.ray.demo.Counter")
counter = counter_class.remote()
# Note the camelCase
counter.incrementValue.remote()
```

calling Python from Java is less worried because you have to create `PyActorMethod` by string. But the snake_case still stand out.
```java
    PyActorClass actorClass = PyActorClass.of(
        "ray_demo", "Counter");
    PyActorHandle actor = Ray.actor(actorClass).remote();
    ObjectRef objRef1 = actor.task(
        PyActorMethod.of("increment_value", int.class)).remote();
```

The mix of camelCase and snake_case is harms readability and compatibility. For example, in Ray Serve, our Python actor needs to manage both Java and Python actors, we have to sprinkle these cases everywhere:
```
if lang = "JAVA":
    ref = actor.performTask.remote(...)
else:
    ref = actor.perform_task.remote(...)
```

### Proposal
Ideally, I can just call a snake_case method on Java actor handle and have it automatically translated to camelCase method name. so that
```
    ref = java_actor.perform_task.remote(...)
```
automatically resolves to the actor's performTask method.

**Comment by jovany-wang** [comment]
It's natural for Java and Py. But I'm not sure if it's a good idea for other languages. For example, C++ has no strong recommend on the function name style. @qicosmos CC

**Comment by jovany-wang** [comment]
Also CC @kfstorm

**Comment by jon-chuang** [comment]
I feel that this should be opt-in. So
```python
counter_class = ray.java_actor_class(..).set_methods_to_snake_case()
```

**Comment by kfstorm** [comment]
> It's natural for Java and Py. But I'm not sure if it's a good idea for other languages. For example, C++ has no strong recommend on the function name style. @qicosmos CC

I think it won't be a problem if we let users specify the desired naming conversion explicitly, like what @jon-chuang recommended above.

**Comment by jovany-wang** [comment]
> > It's natural for Java and Py. But I'm not sure if it's a good idea for other languages. For example, C++ has no strong recommend on the function name style. @qicosmos CC
> 
> I think it won't be a problem if we let users specify the desired naming conversion explicitly, like what @jon-chuang recommended above.

Yes. Proposal from @jon-chuang looks good.
