### ISSUE TITLE
[Core] [Bug] Remote client environment is not setting up properly.

### ISSUE THREAD

**Issue by aeroaks** [ray-project/ray#21471]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### What happened + What you expected to happen

Hi everyone, I have a Ray cluster deployed on Azure K8s. I connect to it using kubectl command as given in the documentation.
I initially ran the task in the local ray environment to test the scaling and working of the task. 
Then, when I am trying to run `put` an object to test on the cluster, it throws the following error:
```
Put failed:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-bd8872eca93e> in <module>
     16     'combined_dfs': combined_dfs_ray,
     17 }
---> 18 run_validation = validate_source.remote(config)
ModuleNotFoundError: No module named 'sklearn'
```
But sklearn is available in the local env. Also, for the algorithm we are running, we are using runtime_env option while running the ray.init command to make available our custom code. All the dependencies are already installed in the env.
```
LOCAL_PORT = 10001
ray.init(f"ray://127.0.0.1:{LOCAL_PORT}",
         runtime_env={
             "working_dir": "../src",
         })
```

By the `put` command, I was expecting an `objectId`, thus telling that the object has been successfully transferred to the cluster.

### Versions / Dependencies

I am using:

- Conda (Windows)
- Python 3.8.12
- Ray[default] 1.9.1
- Remote client on Azure k8s

### Reproduction script

I am trying to workout a small code sample, but the problem is that the simple code structure and no external dependencies are working fine in the remote client environment. The error occurs when I am using our existing dev env. I am trying to create an example in the meanwhile. Also, If there are any logs which could help in providing information then please do let me know.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
@aeroaks I'm not completely understanding your setup, but it looks to me most likely that one of your remote tasks requires sklearn and it isn't installed on the cluster. Can you try adding `"pip": ["sklearn"]` to the runtime_env to see if that resolves the issue?

**Comment by aeroaks** [comment]
I will try to explain the setup with a figure. Your question triggered another question in my mind. 
Even if the dependencies are installed in the local env, we need to provide specific instructions for the dependencies used by the task? I did not have to do that when running ray locally.

**Comment by edoakes** [comment]
When running on the cluster you need to make sure the deps are also installed there. Don't need to locally because everything is running in the same env (the local env).

**Comment by aeroaks** [comment]
My bad. Let me check again by providing the dependencies list in the init command.

Then I have question about using Ray for scaling out in production. Whenever a running program wants to use ray (lets say 3 different apps), then while connecting to ray, they have to provide the dependency list? (I am thinking in the lines of running one cluster and sharing with several apps)

**Comment by aeroaks** [comment]
I am currently using the following init command
```
LOCAL_PORT = 10001
ray.init(f"ray://127.0.0.1:{LOCAL_PORT}",
         runtime_env={
             "working_dir": "../src", # local_mod_a
             "py_modules": [local_mod_b],
             "pip": mod_a_req_list + mod_b_req_list, 
         }) 
```
With this command, I am able to run the function once using `ray.remote` but the task execution is not stable. (Even tried after deleting the cluster and redeploying it using the helm charts.) One of the errors I keep getting in the notebook output repeatedly is 
`(raylet, ip=198.18.54.6) [2022-01-08 08:38:18,970 E 122 122] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.` 

Apart from this, on the subsequent task execution attempts, I am getting the following error:
```
08_506769_110/runtime_resources/conda/c3cf6a3b8a8ce0782a3cef6bbc2869128c028b36/.tmp62fdz_67: line 3:  2193 Killed                  /tmp/ray/session_2022-01-08_02-03-08_506769_110/runtime_resources/conda/c3cf6a3b8a8ce0782a3cef6bbc2869128c028b36/bin/python -m pip install -U -r /tmp/ray/session_2022-01-08_02-03-08_506769_110/runtime_resources/conda/condaenv.veqlq0rj.requirements.txt
(pid=runtime_env, ip=198.18.54.6) 2022-01-08 08:37:38,422	INFO conda_utils.py:198 -- 
(pid=runtime_env, ip=198.18.54.6) 2022-01-08 08:37:38,422	INFO conda_utils.py:198 -- 
(pid=runtime_env, ip=198.18.54.6) 2022-01-08 08:37:38,423	INFO conda_utils.py:198 -- CondaEnvException: Pip failed
(pid=runtime_env, ip=198.18.54.6) 2022-01-08 08:37:38,423	INFO conda_utils.py:198 -- 
(raylet, ip=198.18.54.6) [2022-01-08 08:37:38,891 E 122 122] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=198.18.54.6) [2022-01-08 08:37:38,892 E 122 122] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
---------------------------------------------------------------------------
RuntimeEnvSetupError                      Traceback (most recent call last)
<ipython-input-67-168d52fc1508> in <module>
----> 1 out = ray.get(analysis)

C:\ProgramData\Anaconda3\envs\icrm\lib\site-packages\ray\_private\client_mode_hook.py in wrapper(*args, **kwargs)
    102             # we only convert init function if RAY_CLIENT_MODE=1
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104                 return getattr(ray, func.__name__)(*args, **kwargs)
    105         return func(*args, **kwargs)
    106 

C:\ProgramData\Anaconda3\envs\icrm\lib\site-packages\ray\util\client\api.py in get(self, vals, timeout)
     40             timeout: Optional timeout in milliseconds
     41         """
---> 42         return self.worker.get(vals, timeout=timeout)
     43 
     44     def put(self, *args, **kwargs):

C:\ProgramData\Anaconda3\envs\icrm\lib\site-packages\ray\util\client\worker.py in get(self, vals, timeout)
    357                 op_timeout = MAX_BLOCKING_OPERATION_TIME_S
    358             try:
--> 359                 res = self._get(to_get, op_timeout)
    360                 break
    361             except GetTimeoutError:

C:\ProgramData\Anaconda3\envs\icrm\lib\site-packages\ray\util\client\worker.py in _get(self, ref, timeout)
    384                 logger.exception("Failed to deserialize {}".format(resp.error))
    385                 raise
--> 386             raise err
    387         return loads_from_server(resp.data)
    388 

RuntimeEnvSetupError: The runtime_env failed to be set up.
```

**Comment by dongruixiao** [comment]
i had the same problem

```
In [4]: ray.init(address='auto', namespace='algo-serve', runtime_env={'pip':['requests==2.1.2'], 'env_vars': dict(os.environ)})
2022-01-10 12:20:57,224	INFO worker.py:843 -- Connecting to existing Ray cluster at address: 10.251.192.213:6379
Out[4]:
{'node_ip_address': '10.251.192.213',
 'raylet_ip_address': '10.251.192.213',
 'redis_address': '10.251.192.213:6379',
 'object_store_address': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/plasma_store',
 'raylet_socket_name': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/raylet',
 'webui_url': '10.251.192.213:8265',
 'session_dir': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411',
 'metrics_export_port': 61428,
 'node_id': 'ac4b598c8477048e81b883069027527fbaf0ba9be758441c427be970'}

(raylet) [2022-01-10 12:20:57,396 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet) [2022-01-10 12:20:57,397 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.251.183.221) [2022-01-10 12:20:57,615 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.251.183.221) [2022-01-10 12:20:57,617 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.251.183.221) [2022-01-10 12:20:57,682 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=10.251.183.221) [2022-01-10 12:20:57,809 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
```

**Comment by architkulkarni** [comment]
> My bad. Let me check again by providing the dependencies list in the init command.
> 
> Then I have question about using Ray for scaling out in production. Whenever a running program wants to use ray (lets say 3 different apps), then while connecting to ray, they have to provide the dependency list? (I am thinking in the lines of running one cluster and sharing with several apps)

Yeah, that would be the approach if you wanted to install the environment dynamically at runtime. (For example, one use case would be if each app had its own set of dependencies that might not be mutually compatible.) 

However, if all apps have the same dependencies, another approach is to set up your environment in advance on the cluster by using the setup commands: https://docs.ray.io/en/latest/cluster/config.html#setup-commands

**Comment by architkulkarni** [comment]
> i had the same problem
> 
> ```
> In [4]: ray.init(address='auto', namespace='algo-serve', runtime_env={'pip':['requests==2.1.2'], 'env_vars': dict(os.environ)})
> 2022-01-10 12:20:57,224	INFO worker.py:843 -- Connecting to existing Ray cluster at address: 10.251.192.213:6379
> Out[4]:
> {'node_ip_address': '10.251.192.213',
>  'raylet_ip_address': '10.251.192.213',
>  'redis_address': '10.251.192.213:6379',
>  'object_store_address': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/plasma_store',
>  'raylet_socket_name': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/raylet',
>  'webui_url': '10.251.192.213:8265',
>  'session_dir': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411',
>  'metrics_export_port': 61428,
>  'node_id': 'ac4b598c8477048e81b883069027527fbaf0ba9be758441c427be970'}
> 
> (raylet) [2022-01-10 12:20:57,396 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> (raylet) [2022-01-10 12:20:57,397 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,615 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,617 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,682 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,809 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> ```

Thanks @dongruixiao, could you share some more details about your setup?  Are you using helm charts as well?

**Comment by dongruixiao** [comment]
> > i had the same problem
> > ```
> > In [4]: ray.init(address='auto', namespace='algo-serve', runtime_env={'pip':['requests==2.1.2'], 'env_vars': dict(os.environ)})
> > 2022-01-10 12:20:57,224	INFO worker.py:843 -- Connecting to existing Ray cluster at address: 10.251.192.213:6379
> > Out[4]:
> > {'node_ip_address': '10.251.192.213',
> >  'raylet_ip_address': '10.251.192.213',
> >  'redis_address': '10.251.192.213:6379',
> >  'object_store_address': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/plasma_store',
> >  'raylet_socket_name': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411/sockets/raylet',
> >  'webui_url': '10.251.192.213:8265',
> >  'session_dir': '/tmp/ray/session_2022-01-10_11-43-51_099860_49411',
> >  'metrics_export_port': 61428,
> >  'node_id': 'ac4b598c8477048e81b883069027527fbaf0ba9be758441c427be970'}
> > 
> > (raylet) [2022-01-10 12:20:57,396 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > (raylet) [2022-01-10 12:20:57,397 E 49504 49504] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,615 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,617 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,682 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > (raylet, ip=10.251.183.221) [2022-01-10 12:20:57,809 E 157 157] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
> > ```
> 
> Thanks @dongruixiao, could you share some more details about your setup? Are you using helm charts as well?

I only run it in my custom cluster implemented via `node_provider.py` and do not use helm

**Comment by architkulkarni** [comment]
Thanks for the details @dongruixiao -- perhaps you can try setting the environment variable `RAY_runtime_env_skip_local_gc` to `1` on each node in your cluster?  I think you could do it in the `head_start_ray_commands` and `worker_start_ray_commands` before `ray start`.  This temporary workaround would disable the local garbage collection of runtime environment resources, which should in turn disable those messages.  The downside is that if you have a long running Ray job using many different pip and conda environments, they will accumulate on the disk without being cleaned up.

**Comment by aeroaks** [comment]
> Thanks for the details @dongruixiao -- perhaps you can try setting the environment variable `RAY_runtime_env_skip_local_gc` to `1` on each node in your cluster? I think you could do it in the `head_start_ray_commands` and `worker_start_ray_commands` before `ray start`. This temporary workaround would disable the local garbage collection of runtime environment resources, which should in turn disable those messages. The downside is that if you have a long running Ray job using many different pip and conda environments, they will accumulate on the disk without being cleaned up.

Hi @architkulkarni , I assume this workaround is applicable in any case, i.e. would help to solve my case as well?

Is this a recognised behaviour for which there will be a permanent solution?

**Comment by aeroaks** [comment]
> > My bad. Let me check again by providing the dependencies list in the init command.
> > Then I have question about using Ray for scaling out in production. Whenever a running program wants to use ray (lets say 3 different apps), then while connecting to ray, they have to provide the dependency list? (I am thinking in the lines of running one cluster and sharing with several apps)
> 
> Yeah, that would be the approach if you wanted to install the environment dynamically at runtime. (For example, one use case would be if each app had its own set of dependencies that might not be mutually compatible.)
> 
> However, if all apps have the same dependencies, another approach is to set up your environment in advance on the cluster by using the setup commands: https://docs.ray.io/en/latest/cluster/config.html#setup-commands

Hi @architkulkarni, I observed that when submitting the same task, once as a one off task, and next as a task submitted for parallel execution, the environment setup takes place whent he task is submitted. Since both are the same tasks and submitted at an interval of few seconds from the same notebook, thus same client, why does the environment setup is triggered twice. 
Is this normal behaviour?

**Comment by aeroaks** [comment]
Hi @architkulkarni, After recreating the cluster I tried connecting to the cluster. I get the `ClientContext` response but also get the following lines as output still:
```
(raylet, ip=198.18.45.7) [2022-01-18 02:27:44,928 E 120 120] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
(raylet, ip=198.18.45.7) [2022-01-18 02:27:45,930 E 120 120] agent_manager.cc:237: Failed to delete URIs, status = IOError: , maybe there are some network problems, will retry it later.
```

Is there a config that I could try?

**Comment by architkulkarni** [comment]
The line ` Killed` seems to indicate that it's a failure of the `pip install` itself, possibly due to running out of memory;  I found one example here: https://stackoverflow.com/questions/30550235/pip-install-killed.  Maybe you could check if the same error occurs with a smaller `pip` requirements list.

I'm not sure why `Failed to delete URIs` is happening, I'll try to reproduce it using some of the details from earlier in the thread.

**Comment by aeroaks** [comment]
Thanks for your help. I was able to get the remote cluster working by doing 2 things:

1. Increase the memory of the nodes (Solution to the last comment)
2. Use an extended `ray.init` command to include every dependencies when initializing like below
```
LOCAL_PORT = 10001
ray.init(f"ray://127.0.0.1:{LOCAL_PORT}",
         runtime_env={
             "py_modules": [pkg_b], # to include another local package that is used in the code
             "pip": pkg_a_req_list + pkg_b_req_list + tune_req_list, # include list of packages that are required by the local packages
                                                                                               # also, I had to pass list of packages for "ray.tune" to get it working 
         })
```
