### ISSUE TITLE
[Core] [Docs] Can't run the demo for AsyncIO for Actors 

### ISSUE THREAD

**Issue by Echo0117** [ray-project/ray#21481]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Hey, I'm trying to use AsyncActor to run my code concurrently, so I tried the demo on AsyncIO for Actors:
```
import ray
import asyncio
ray.init()

@ray.remote
class AsyncActor:
    # multiple invocation of this method can be running in
    # the event loop at the same time
    async def run_concurrent(self):
        print("started")
        await asyncio.sleep(2) # concurrent workload here
        print("finished")

actor = AsyncActor.remote()

# regular ray.get
# ray.get([actor.run_concurrent.remote() for _ in range(4)])

# async ray.get
await actor.run_concurrent.remote()
```

But I got errors:
![QuvVZLAY4Q](https://user-images.githubusercontent.com/54064209/148635608-bf3c1d6b-abba-41c0-bbaf-4c05af2d91b5.png)

I'd like to ask what is the correct way to write the code? Thank you very much!!

### Versions / Dependencies

ray == 1.9.1
python == 3.8.12

### Reproduction script

```
import ray
import asyncio
ray.init()

@ray.remote
class AsyncActor:
    # multiple invocation of this method can be running in
    # the event loop at the same time
    async def run_concurrent(self):
        print("started")
        await asyncio.sleep(2) # concurrent workload here
        print("finished")

actor = AsyncActor.remote()

# regular ray.get
# ray.get([actor.run_concurrent.remote() for _ in range(4)])

# async ray.get
await actor.run_concurrent.remote()
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
This is a bug in the demo code; `await` can only be used inside of an async function, but the demo code is trying to use it say the module level, which is incorrect. If you wrap the module-level code in an async function, it should work.

```python
import ray
import asyncio
ray.init()

@ray.remote
class AsyncActor:
    # multiple invocation of this method can be running in
    # the event loop at the same time
    async def run_concurrent(self):
        print("started")
        await asyncio.sleep(2) # concurrent workload here
        print("finished")


async def main():
    actor = AsyncActor.remote()

    # regular ray.get
    # ray.get([actor.run_concurrent.remote() for _ in range(4)])

    # async ray.get
    await actor.run_concurrent.remote()

asyncio.run(main())
```

**Comment by Echo0117** [comment]
> 

Hey, thanks for replying. It worked, but it only run on one task, what should I do if I want to run 10 tasks concurrently, like the one in  `# ray.get([actor.run_concurrent.remote() for _ in range(4)])`.

I tried to write it like: 
```
async def main():
    actor = AsyncActor.remote()
    for i in range(10):
        await actor.user_portrait_update.remote()
asyncio.run(main())
```

But it seems wrong, coz it took 10 times longer than one task.

**Comment by Echo0117** [comment]
> This is a bug/incompleteness in the demo code; `await` can only be used inside of an async function, but the demo code is trying to use it at the module level, which is incorrect. If you wrap the module-level code in an async function, it should work.
> 
> ```python
> import ray
> import asyncio
> ray.init()
> 
> @ray.remote
> class AsyncActor:
>     # multiple invocation of this method can be running in
>     # the event loop at the same time
>     async def run_concurrent(self):
>         print("started")
>         await asyncio.sleep(2) # concurrent workload here
>         print("finished")
> 
> 
> async def main():
>     actor = AsyncActor.remote()
> 
>     # regular ray.get
>     # ray.get([actor.run_concurrent.remote() for _ in range(4)])
> 
>     # async ray.get
>     await actor.run_concurrent.remote()
> 
> asyncio.run(main())
> ```
