### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [ray-project/ray#21487]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by matthewdeng** [comment]
cc @thomasdesr

**Comment by thomasdesr** [comment]
Hey @JamieSlome! You can reach us over at [security@anyscale.com](mailto:security@anyscale.com).

I'll leave this open till we add a security.md file to Ray.

**Comment by simon-mo** [comment]
https://github.com/ray-project/ray/blob/master/SECURITY.md exists! Thanks @JamieSlome for adding one. Closing.
