### ISSUE TITLE
[runtime env] API refactor

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#21495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

1、Can we make the runtime env API strong-typed instead of a json or dict? 

In python now, we provide runtime env API which is a dict. We need to do a lot validation logics here https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/validation.py. And If we support runtime env cross-language API, the validation code will be more complex and it couldn't be reused in Java and C++. 
Can we make the runtime env API strong-typed instead of a json or dict? If we do, I think runtime env will be clearer and easy to maintain.
Maybe the strong-typed API is like:
```
runtime_env = RuntimeEnvBuilder.set_env_vars({"a": "b"}).set_pip_packages(["requests", "pendulum==2.1.2"]).build()
ray.init(runtime_env=runtime_env)
```
The cross-language API is like:
```
java_runtime_env = RuntimeEnvBuilder.set_env_vars({"a": "b"}).set_jars(["s3://abc.jar"]).build()
ray.init(runtime_env=java_runtime_env)
```

2、Can we remove the code_search_path in Python, Java and C++?
We can support this logic in runtime env:
- In python, we can reuse the `py_modules` field. https://github.com/ray-project/ray/pull/21504/files#diff-ff7ace6af03d75dc9d8e031310da8f3994c5f71c8f3b29b587c0d841b63e1a1fR73
- In Java, we can add a new field `jars` like https://github.com/ray-project/ray/pull/21504/files#diff-ff7ace6af03d75dc9d8e031310da8f3994c5f71c8f3b29b587c0d841b63e1a1fR95.
- In C++, we can add a new field `dynamic_library` like https://github.com/ray-project/ray/pull/21504/files#diff-ff7ace6af03d75dc9d8e031310da8f3994c5f71c8f3b29b587c0d841b63e1a1fR110. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by SongGuyang** [comment]
@edoakes @architkulkarni @raulchen

**Comment by architkulkarni** [comment]
Regarding (1), we need to be able to have runtime_env be a JSON file so that the JSON file can be read by Ray Job Submission: https://docs.ray.io/en/master/ray-job-submission/overview.html.

Regarding (2), I agree we should remove `code_search_path`!  Those proposed additions look good to me.

**Comment by SongGuyang** [comment]
Emm.. Yep, job submission is a special case. @raulchen let’s discuss about this offline.

**Comment by raulchen** [comment]
For the job submission case, the HTTP interface should accept a JSON string, and then parse it to a strong-typed RuntimeEnv Python object before calling "ray.init" (or whichever Ray core API).

**Comment by architkulkarni** [comment]
> For the job submission case, the HTTP interface should accept a JSON string, and then parse it to a strong-typed RuntimeEnv Python object before calling "ray.init" (or whichever Ray core API).

That sounds like a good solution to me, @edoakes do you have any concerns about it?

**Comment by edoakes** [comment]
@raulchen @architkulkarni to be clear, this means we don't alter the existing HTTP API and have a strongly typed object that we cast it to in Python? That sounds fine, but we should continue to support an untyped dictionary in the Python APIs as well (it's often more convenient to pass around, write to/read from a file, etc.). This can simply take in a dictionary and cast it to the typed object (and reject it if ill-formated). The code effectively does this already.

**Comment by edoakes** [comment]
I really don't see the need for a builder API here though, this seems like unnecessary complexity. I think we can keep this very simple.

**Comment by raulchen** [comment]
> @raulchen @architkulkarni to be clear, this means we don't alter the existing HTTP API and have a strongly typed object that we cast it to in Python? That sounds fine, but we should continue to support an untyped dictionary in the Python APIs as well (it's often more convenient to pass around, write to/read from a file, etc.). This can simply take in a dictionary and cast it to the typed object (and reject it if ill-formated). The code effectively does this already.

Sounds good.

**Comment by SongGuyang** [comment]
> I really don't see the need for a builder API here though, this seems like unnecessary complexity. I think we should keep this very simple.

What kind of API do you prefer? Let's discuss the API in the offline meeting.

**Comment by SongGuyang** [comment]
In Python:
```
runtime_env = ray.runtime_env.RuntimeEnv(working_dir="s3://workding_dir.zip", 
        pip=["requests"],
        java_jars=["s3://jar1.zip"],
        java_jvm_options=["-Dxxx=xxx"])
```

or 

```
runtime_env = {"working_dir": "s3://workding_dir.zip", 
        "pip": ["requests"],
        "java_jars": ["s3://jar1.zip"],
         "java_jvm_options": ["-Dxxx=xxx"]}
```

In Java:

```
runtime_env = new RuntimeEnv.Builder().setWorkingDir("s3://workding_dir.zip").setJars(Lists.of("s3://jar1.zip"))
        .setJvmOptions(Lists.of("-Dxxx=xxx")).setPyPipPackages(Lists.of("requests")).build()
```

The principle is that:
        If we create a cross-language field of the typed runtime env, the API name should have a prefix, like "java_..." or "setPy...". Otherwise, the prefix is not required. 

What do you think about this?

**Comment by architkulkarni** [comment]
Adding a prefix for language-specific options makes sense to me!

**Comment by edoakes** [comment]
@SongGuyang this looks pretty good to me. So there would be no compatibility breakage for existing Python users, right?
