### ISSUE TITLE
[Bug] Initialization of wandb with Tune, start method fork

### ISSUE THREAD

**Issue by marceloruizrodriguez** [ray-project/ray#21490]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib, Monitoring & Debugging

### What happened + What you expected to happen

I had managed to implement wandb to analyze a multi-agent system with RLlib, but after fixing some bugs in my code (not related to wandb), I ran it again the next day and I got the error `wandb.errors.UsageError: Settings field start_method: fork not in [thread, spawn]` and it no longer allows me to analyze the metrics.

```
C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\ray\tune\callback.py:217: FutureWarning: Please update `setup` method in callback `<class 'ray.tune.integration.wandb.WandbLoggerCallback'>` to match the method signature in `ray.tune.callback.Callback`.
  warnings.warn(
== Status ==
Current time: 2022-01-09 17:18:06 (running for 00:00:00.15)
Memory usage on this node: 6.7/7.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs, 0.0/1.08 GiB heap, 0.0/0.54 GiB objects
Result logdir: C:\Users\VB_Pu\PycharmProjects\MARLPdM\results\my_exp
Number of trials: 1/1 (1 PENDING)
+----------------------------+----------+-------+
| Trial name                 | status   | loc   |
|----------------------------+----------+-------|
| PPO_FactoryEnv_ba16d_00000 | PENDING  |       |
+----------------------------+----------+-------+
2022-01-09 17:18:06,216	ERROR syncer.py:111 -- Log sync requires rsync to be installed.
 pid=21368) 2022-01-09 17:18:12,072	INFO trainer.py:722 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also want to then set `eager_tracing=True` in order to reach similar execution speed as with static-graph mode.
 pid=21368) 2022-01-09 17:18:12,072	WARNING ppo.py:143 -- `train_batch_size` (128) cannot be achieved with your other settings (num_workers=1 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 128.
 pid=21368) 2022-01-09 17:18:12,073	INFO ppo.py:166 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
 pid=21368) 2022-01-09 17:18:12,073	INFO trainer.py:743 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
wandb: ERROR Settings field `start_method`: fork not in [thread, spawn]
Process _WandbLoggingProcess-1:
Traceback (most recent call last):
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\ray\tune\integration\wandb.py", line 199, in run
    wandb.init(*self.args, **self.kwargs)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_init.py", line 914, in init
    wi.setup(kwargs)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_init.py", line 105, in setup
    self._wl = wandb_setup._setup()
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_setup.py", line 270, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_setup.py", line 256, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_setup.py", line 97, in __init__
    self._settings_setup(settings, self._early_logger)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_setup.py", line 109, in _settings_setup
    s._apply_environ(self._environ, _logger=early_logger)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_settings.py", line 783, in _apply_environ
    self._update(env_dict, _source=self.Source.ENV)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_settings.py", line 901, in _update
    self._check_invalid(k, v)
  File "C:\Users\VB_Pu\anaconda3\envs\MARL\lib\site-packages\wandb\sdk\wandb_settings.py", line 876, in _check_invalid
    raise UsageError("Settings field `{}`: {}".format(k, invalid))
wandb.errors.UsageError: Settings field `start_method`: fork not in [thread, spawn]
```
After this the code continues running normally (but I didn't want to paste the full log because is too large), the only thing is that there is an error to run the wandb.

I tried to pass the parameter `start_method="fork"` with the **kwargs, as suggested [here](https://docs.wandb.ai/guides/track/launch) in the callback, in this way: 

tune.run(**exp_dict, callbacks=[WandbLoggerCallback(
        project="MARL",
        api_key="ebf5a9f34786e935701e084ac9fdb9a368031873",
        log_config=True, **{"start_method":"fork"})])

 but is not recognized. Also in the wand.py from ray>tune>integration>wandb.py there is the commando `os.environ["WANDB_START_METHOD"] = "fork"` so I don't know what could be wrong

Edit: Seems the problem is with windows because it seems to be working with UNIX platform.

### Versions / Dependencies

wandb==0.12.9
ray==1.9.1
windows

### Reproduction script

tune.run(**exp_dict, callbacks=[WandbLoggerCallback(
        project="MARL",
        api_key=pvt_key,
        log_config=True,)])

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
Hi,
I am not very familiar with windows platform, but reading the error message, it seems to complain that only `thread` and `spawn` are expected but `fork` is instead given. 
Reading more about `multiprocessing.[get_all_start_methods](https://docs.python.org/3/library/multiprocessing.html)`, different methods are supported on windows.

Maybe try changing to `thread` instead?

**Comment by marceloruizrodriguez** [comment]
Hello @xwjiang2010 thank you for your reply. 
Yes, that seems to work now, I changed directly the file ./ray/tune/integration/wandb.py Line 198 from 

> os.environ["WANDB_START_METHOD"] = "fork"

to

> os.environ["WANDB_START_METHOD"] = "thread"

Thank you!
