### ISSUE TITLE
[rllib] Unable to restore agent 'key error: weights'

### ISSUE THREAD

**Issue by Carterbouley** [ray-project/ray#21505]
I am trying to restore a saved agent (which I downloaded after cluster training) so I can use it offline.

I am using the same version of ray for training and offline (ray==1.8.0) i am getting the following error - this did not happen with 0.8.4 - am I restoring the agent correctly?
![Screenshot 2022-01-10 at 15 43 51](https://user-images.githubusercontent.com/42470002/148794616-729d9ae8-c314-45ff-91b0-473c2a5d73a9.png)

**Comment by avnishn** [comment]
Hi @Carterbouley,

RLlib checkpoints are only guaranteed to be restorable with the version that they were trained on. If your agent was trained using 0.8.4, then it is only guaranteed to be restorable with 0.8.4.

If you were able to train using 1.8 and restore using ray 1.8, then could you try running the script below?
https://gist.github.com/avnishn/d9749005474eccb7dcc3969f28dfc84f

if that works, then its possible that you have the checkpoint directory incorrect or that your checkpoint has been corrupted, although the latter is unlikely.

Thanks,
@avnishn

**Comment by Carterbouley** [comment]
Thanks alot @avnishn - I rechecked and for anyone who has a similar problem, the notebook I was using to activate my cluster had ray 1.8.0 installed, but the actual cluster was training with 1.3.0 on Azure. Worth re-checking!

Thanks,
@Carterbouley
