### ISSUE TITLE
[train] add example for pytorch model parallelism

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#21508]
**Goal:** Add an example to the docs that showcases how you can use model parallelism + DDP to efficiently train across GPUs.

**Example:** https://pytorch.org/tutorials/intermediate/pipeline_tutorial.html

**Comment by richardliaw** [comment]
Here is an example for training (which uses master/nightly build) -- [docs.ray.io/en/master/ray-air/examples/gptj_deepspeed_fine_tuning.html](https://docs.ray.io/en/master/ray-air/examples/gptj_deepspeed_fine_tuning.html).

Hope that helps!
