### ISSUE TITLE
[Dask-on-Ray] [Feature] Propagate Dask-level resource requests and Ray task options via Dask annotations to Ray tasks.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#21536]
# Resource requests

Dask has an [annotation config API](https://docs.dask.org/en/stable/api.html#dask.annotate) as well as the ability to give top-level resource requests in the `dask.compute()` API, which allows a user to attach resource requests (among other things) globally and/or to a high-level subgraph of computation. We should map these resource request annotations and global resource specifications to Ray task resource requests.

## Use Case - GPU use in a heterogeneous cluster

If wanting to execute a Dask workload on a GPU, or a subset of Dask tasks on a GPU, in a heterogeneous cluster, propagating GPU resource requests to the underlying Ray tasks is required for correctness, otherwise GPU tasks may be scheduled onto non-GPU nodes, which will cause the tasks to fail.

```python
x = dd.read_csv(...)

with dask.annotate(resources={"GPU": 1}):
    y = x.map_partitions(func1)

z = y.map_partitions(func2)

z.compute(optimize_graph=False)
```

**Note:** Some small translation of Dask-level resources to Ray-level resources will be required. E.g., we don't allow for a `"GPU"` resource request to be given in the Ray task `"resources"` dict; we expect this to be given as `num_gpus=...`. Popping these from the Dask-level resource dict should be easy enough.

# Other Ray remote arguments

Besides resource requests, which we would like to achieve a 1:1 mapping with the Dask frontend API (for `dask.annotate()`, `dask.compute()`, etc.), we would also like to provide the ability to generically forward Ray remote arguments via `ray_remote_args` annotation/`.compute(ray_remote_args=...)` kwarg.

## Use case - spread scheduling

We'd like to use the spread scheduling strategy for data loading tasks but not for most others. Although we can hack this via matching data loading task name prefixes, this is brittle, and there may be other Dask operations that we wish to load balance across the cluster rather than use the default scheduling policy. We can allow the user to pick and choose where they apply spread scheduling via the Dask-level annotations:

```python
with dask.annotate(ray_remote_args={"scheduling_strategy": "SPREAD"}):
    x = dd.read_csv(...)

y = x.map_partitions(func1)
z = y.map_partitions(func2)

z.compute(optimize_graph=False)
```

**Comment by mikwieczorek** [comment]
+1 for this feature, that's what I am missing when running Dask with Ray. Would love to see a working solution for that.
