### ISSUE TITLE
[Feature] [Java]Remove GlobalStateAccessor in Java

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#21545]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Now in Java code, if we want get some data from gcs, the code path is `GcsClient.java -> GlobalStateAccessor.java ---jni---> global_state_accessor.cc -> gcs_client.cc ----rpc---> gcs server`, which is complicated.

We can send grpc directly to gcs server in `GcsClient.java`, and this will reduce code path. `GlobalStateAccessor.java` currently is only used by `GcsClient.java`, ant it could be removed after the refactor.

cc @iycheng 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jovany-wang** [comment]
Does Python worker access GCS only in grpc? I'm not sure if it's the best practice by the current status quo of our codebase.

**Comment by WangTaoTheTonic** [comment]
yeah now accessing GCS in Python is limited to grpc, told by @iycheng
