### ISSUE TITLE
[RFC] Move multi-actors-per-process feature to a separate util lib

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21547]
For the purposes of:
- Improving some API's semantics which based on one actor per process, such as kill(actor)..
- Clearing the gap and redundant codepath of PG and actors scheduling between Python and Java.
- Addressing other potential risks since the feature flag is off in opensource codebase currently.
- Speeding up the process to opensource gcs scheduling.
- Improving actor isolation.

We'd like to remove all code path of multi-actors-per-process and have not been support the feature. As an alternate, we'd like to support another parallel execution model based on concurrency group, which is as a separate util library of commonlibs. The new util is on the top of actor, hence it won‘t break the assumption of `one actor per process`.

**Comment by rkooo567** [comment]
cc @scv119 

Does this mean we won't have multiple core worker threads per process?

**Comment by jovany-wang** [comment]
> Does this mean we won't have multiple core worker threads per process?

Yes.

**Comment by rkooo567** [comment]
This is a nice change! I am totally in favor of this

**Comment by jovany-wang** [comment]
Blocked items:
- [ ] Move functiondescriptor, auto generated proto to api module.

**Comment by jovany-wang** [comment]
The plan should be:
1. to finish this https://github.com/ray-project/ray/pull/21701 on current master(before 2.0 cut).
2. to remove `num-java-workers-per-process` on 2.0 branch only. Because this is a huge breakage behavior.

**Comment by ericl** [comment]
Really happy to see these architectural cleanups!

**Comment by jovany-wang** [comment]
This is done. closing it

**Comment by jovany-wang** [comment]
Here is the ticket for further refactor https://github.com/ray-project/ray/issues/24567

**Comment by jovany-wang** [comment]
DONE
