### ISSUE TITLE
SIGBUS error appeared after out of memory error

### ISSUE THREAD

**Issue by DeepWolf90** [ray-project/ray#21576]
I run an RL experiment on a server. I use a simulator called CoppeliaSim to create my env.

At first time, it ran perfectly without any problem, until I got out of memory error. Then, when I tried to run again, it gave a SIGBUS error

```
*** SIGBUS received at time=1642066784 on cpu 15 ***0.00
(SelfPlay pid=21208) PC: @     0x7fb64d4b5972  (unknown)  (unknown)
(SelfPlay pid=21208)     @     0x7fbc5216f980  (unknown)  (unknown)
(SelfPlay pid=21208) [2022-01-13 10:39:44,149 E 21208 21753] logging.cc:317: *** SIGBUS received at time=1642066784 on cpu 15 ***
(SelfPlay pid=21208) [2022-01-13 10:39:44,149 E 21208 21753] logging.cc:317: PC: @     0x7fb64d4b5972  (unknown)  (unknown)
(SelfPlay pid=21208) [2022-01-13 10:39:44,149 E 21208 21753] logging.cc:317:     @     0x7fbc5216f980  (unknown)  (unknown)
(SelfPlay pid=21208) Fatal Python error: Bus error
(SelfPlay pid=21208) 
(SelfPlay pid=21208) Stack (most recent call first):
(SelfPlay pid=21208)   File "/data/kotb/robotarm/Env/robot-env/lib/python3.7/site-packages/pyrep/backend/sim.py", line 48 in simExtLaunchUIThread
(SelfPlay pid=21208)   File "/data/kotb/robotarm/Env/robot-env/lib/python3.7/site-packages/pyrep/pyrep.py", line 56 in _run_ui_thread
(SelfPlay pid=21208)   File "/data/kotb/robotarm/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865 in run
(SelfPlay pid=21208)   File "/data/kotb/robotarm/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917 in _bootstrap_inner
(SelfPlay pid=21208)   File "/data/kotb/robotarm/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885 in _bootstrap
2022-01-13 10:39:44,207 WARNING worker.py:1245 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: fffffffffffffffff3cd78e49be1f9e73f8e789901000000 Worker ID: c34dabceab147caba669b36e0b90dfcd32048ebd07e89345942f1e63 Node ID: e54046e40ae2e48deb7f5e5ae670f595f3c60054a5ccef82f2dc401f Worker IP address: 134.100.10.111 Worker port: 36011 Worker PID: 21208
```
However, if I use a simple gym env. instead of my CoppeliaSim env., it runs perfectly without SIGBUS error.

Important Note: I restarted the server and suddenly the error disappeared UNTIL I got out of memory error again, and the SIGBUS error appeared again

OS Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-92-generic x86_64)
 python 3.7.2
ray 1.9.1
PyTorch 1.9.0
PyRep 4.1.0.2

**Comment by rkooo567** [comment]
@DeepWolf90 do you have a self-contained repro script we can try reproducing the issue? This is very interesting, but it is difficult to construct the theory with the given information.

Also, cc @ericl it seems like there are some edge cases SIGBUS still can be raised.

**Comment by ericl** [comment]
+1 to making a repro (you should be able to do this by writing an env that returns fake obs data of the same shape as the real env).

That will let us know if it's Ray or Coppelia crashing.

**Comment by DeepWolf90** [comment]
@rkooo567 @ericl Thank you for your help.

I don't know exactly the cause of SIGBUS error, but when I updated the server OS to ubuntu 20.04, the error disappeared.

I'm pretty sure though, it is not Ray, may be dependencies issue.
