### ISSUE TITLE
[data] Support ds.groupby().map_groups()

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#21609]
Support an API that lets the user apply a function over all the values of a group (unaggregated). This can be implemented efficiently by using sort() under the hood.

```
class GroupedDataset:

    def map_groups(self,
                    fn: Union[CallableClass, Callable[[BatchType], BatchType]],
                    *,
                    compute: Optional[str] = None,
                    batch_format: str = "pandas",
                    **ray_remote_args) -> "Dataset[Any]":
        """Apply a function to each group of records.
        
        This is similar to pd.groupby().apply(). 
        
        The user given function should take as arguments (key, values), where key
        is the grouping key and values is a batch of all the values for the key, and
        returns a row of type T. These rows will be collected to form the result dataset.
        """

        # Sort groups records by key.
        sorted_ds = self._dataset.sort(key)

        def group_fn(batch):
            batch_groups = split_by_key(batch)
            # Assume batch is list type for now.
            out = []
            # Apply fn to each group of records
            for group in groups:
                for row in fn(group):
                    out.append(row)
            return []

        return sorted_ds.map_batches(
            group_fn, compute=compute, batch_format=batch_format, **ray_remote_args)
```

cc @richardliaw @clarkzinzow

**Comment by goodwanghan** [comment]
This is great! +1

Also, I suggest you let users be explicit about the output schema (if schema is a concept of ray dataset), because schema inference can cause performance and correctness issues on a distributed system.

**Comment by mathetes87** [comment]
The output schema suggestion seems very useful, not only because of the extra computation, but also because otherwise you could have conflicting schemas between rows

**Comment by mathetes87** [comment]
This would be so useful! I've needed this a number of times for different use cases.
About the optional output schema, would it also help because of possible conflicting schemas between groups output?

**Comment by jefferent2019** [comment]
Hi，@ericl，I have a problem with ensuring that when grouping data, the same KEY is divided into the same Block.  For example, the ability to aggregate daily stock data into a large data set and then group and break it down by stock code seems impossible for existing interfaces.  I see someone also encountered a similar situation: https://discuss.ray.io/t/filter-and-pivot-large-datasets-on-s3-by-symbol/5025/2.  So please evaluate whether you can support. Map_groups (...  , block_per_group=True).

**Comment by naijoaix** [comment]
Hi @jefferent2019, I think block is more like internal/physical representation of a Dataset. For map_groups(), even though we do make sure same key go to same block, this is implementation detail (to handle non-associative operations on a group). That said, your use case, which IIUC is about rekeying your data and write out a file for each new key, can be supported with groupby(stock_ticker).map_groups(func_to_write_group_to_file), which is similar to what Clark answered to you before.
