### ISSUE TITLE
[Bug] dashboard is consuming huge amount of network data

### ISSUE THREAD

**Issue by auderson** [ray-project/ray#21618]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

I found dashboard is using too much of the network, at a speed of around 3MB/s: 
![image](https://user-images.githubusercontent.com/48577571/149610417-f3618253-daa3-4b66-a149-641fea1dd5e5.png)

This looks abnormal, is it refreshing too frequently or downloading everything even not needed?

### Versions / Dependencies

I'm using ray 1.9.1 on a k8s cluster of 5 machines

### Reproduction script

.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Yeah I think it is currently very inefficient since it pulls the snapshot of the cluster every 1 second. 

cc @edoakes do you guys still handle dashboard-related issue? I think we should optimize this

**Comment by scottsun94** [comment]
@auderson 
In ray 2.0, we made the previous experimental dashboard the default dashboard.
Not sure if you have upgraded to 2.0, but are you still running into this issue with this new dashboard?

**Comment by auderson** [comment]
The new dashboard fixes this issue.

But BTW I think it can be more informative if you keep num of workers in the summary view. So that I don't have to click the nodes 1-by-1.

**Comment by scottsun94** [comment]
Great.

> keep num of workers in the summary view

Could you tell me more about why you want to know the # of workers? Why and when do you need it?

**Comment by auderson** [comment]
With that I can tell which node is idle and which is busy when debuging. Sometimes it's not enough to only look at the CPU usage. 

And CPU usage is not accurate either:
![image](https://user-images.githubusercontent.com/48577571/194810413-e1fd90e5-6b6d-4cc8-aa0c-d7c8bd05adb2.png)

**Comment by scottsun94** [comment]
> "I can tell which node is idle and which is busy when debugging"

Not sure if I fully understand this. Let's use your screenshot as an example. Even it shows you that there are 16 workers on the node "ray-header-0", those workers could be idle worker? How do you tell whether the node is idle only by # of workers?

**Comment by auderson** [comment]
![image](https://user-images.githubusercontent.com/48577571/194981616-f3a797f0-3623-417c-b1b4-1f9eb8099427.png)

In the legacy dashboard at least I can tell which one has 0 workers. 

> How do you tell whether the node is idle only by # of workers?

It would also be nice if # of non-idle workers is shown in stead of # of total workers.

**Comment by scottsun94** [comment]
Got it. Essentially, you want to which node is idle? How would you define an idle node? No task or actor running on that node?

**Comment by auderson** [comment]
Actually, I want to quickly locate which node is running the debugging job that I just submitted. In previous bashboard I can do it by checking # workers on each node. Now in the new version I can't.

**Comment by scottsun94** [comment]
Got it. So you actually don't care which node is idle as long as you know which job is running your debugging job? (easy to tell it from the # of workers on the node)

**Comment by auderson** [comment]
In a sense, yes.

**Comment by scottsun94** [comment]
> And CPU usage is not accurate either:

BTW, I followed up on this internally. One possibility for this is that the head node cpu usage actually includes gcs and other processes' cpu usage apart from the workers. That's why you see a higher usage than the total of the workers.

**Comment by scottsun94** [comment]
I'll close this issue then. Please create a new issues if you see anything off! Thanks!
