### ISSUE TITLE
Installing failure: Unable to locate Parquet libraries

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#2161]
### System information
- **customized CentOS with kernel Linux 3.10.0-327.ali2014.alios7.x86_64**:
- **Ray installed from source**:
- **latest**:
- **Python 2.7**:
- **pip install -e . --verbose**:

### Describe the problem

Today, I merged upstream/master.
As local scheduler was not found, I tried to re-install Ray.

### Source code / logs

Added shared library dependency arrow: /gruntdata/app_data/jones.wz/rl/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib64/libarrow.so
Added shared library dependency arrow_python: /gruntdata/app_data/jones.wz/rl/ray/thirdparty/pkg/arrow/cpp/build/cpp-install/lib64/libarrow_python.so
-- Checking for module 'parquet'
--   No package 'parquet' found
--  Could not find the parquet library. Looked in  system search paths.
CMake Error at CMakeLists.txt:341 (message):
Unable to locate Parquet libraries
-- Configuring incomplete, errors occurred!
See also "/gruntdata/app_data/jones.wz/rl/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
See also "/gruntdata/app_data/jones.wz/rl/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeError.log".

CMakeError.log shows:
Performing C++ SOURCE FILE Test CXX_SUPPORTS_ALTIVEC failed with the following output:
Change Dir: /gruntdata/app_data/jones.wz/rl/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_4b055/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_4b055.dir/build.make CMakeFiles/cmTC_4b055.dir/build
gmake[1]: Entering directory`/gruntdata/app_data/jones.wz/rl/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_4b055.dir/src.cxx.o
/gruntdata/app_data/jones.wz/anaconda2/bin/c++    -DCXX_SUPPORTS_ALTIVEC   -maltivec -o CMakeFiles/cmTC_4b055.dir/src.cxx.o -c /gruntdata/app_data/jones.wz/rl/ra    y/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-maltivec'
gmake[1]: *** [CMakeFiles/cmTC_4b055.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory `/gruntdata/app_data/jones.wz/rl/ray/thirdparty/build/arrow/python/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_4b055/fast] Error 2

Source file was:
int main() { return 0; }

**Comment by joneswong** [comment]
On another machine with the same environment and configurations, I can successfully install Ray but when import ray, it shows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ray/__init__.py", line 50, in <module>
    from ray.worker import (error_info, init, connect, disconnect, get, put, wait,
  File "ray/worker.py", line 24, in <module>
    import ray.experimental.state as state
  File "ray/experimental/state.py", line 28, in <module>
    from ray.core.generated.ray.protocol.Task import Task
ImportError: No module named ray.protocol.Task

**Comment by joneswong** [comment]
Sorry, it seems that I failed to clean the directory.

**Comment by pcmoritz** [comment]
Just for reference, this is the current way to clean _everything_ and do a fresh build in an existing ray repo:

In the ray/ directory, run:

```
rm -rf build
rm -rf python/ray/pyarrow_files
rm -rf thirdparty/build/arrow
rm -rf thirdparty/pkg/arrow
rm -rf thirdparty/build/parquet-cpp

git checkout python/ray/pyarrow_files
```

**Comment by robertnishihara** [comment]
I've been using

```
rm -rf python/ray/core
rm -rf python/ray/pyarrow_files
rm -rf thirdparty/build/arrow
rm -rf thirdparty/pkg/arrow
rm -rf thirdparty/build/parquet-cpp
rm -rf build

git checkout python/ray/core
git checkout python/ray/pyarrow_files
```
