### ISSUE TITLE
[Bug] [Core]Raylet may missed the report

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#21638]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

1. launch 1 head node and 1 worker node
2. kill the pod where the head node is on
3. see the raylet log on the worker node, and the warning continues like forever

![image](https://user-images.githubusercontent.com/5276001/149700819-caf3df93-5b27-4cee-853c-c6fa786db6c0.png)

Notes: It happens by accident.

### Versions / Dependencies

1.9

### Reproduction script

..

### Anything else

It looks like the local version is always newer, perhaps the raylet forget to report its latest resource after the head node restarting?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @iycheng

**Comment by rkooo567** [comment]
```
  if (next_resource_seq_no_ != 0 &&
      resource_usage_batch.seq_no() != next_resource_seq_no_) {
    // TODO (Alex): Ideally we would be really robust, and potentially eagerly
    // pull a full resource "snapshot" from gcs to make sure our state doesn't
    // diverge from GCS.
    RAY_LOG(WARNING)
        << "Raylet may have missed a resource broadcast. This either means that GCS has "
           "restarted, the network is heavily congested and is dropping, reordering, or "
           "duplicating packets. Expected seq#: "
        << next_resource_seq_no_ << ", but got: " << resource_usage_batch.seq_no() << ".";
    if (resource_usage_batch.seq_no() < next_resource_seq_no_) {
      RAY_LOG(WARNING) << "Discard the the resource update since local version is newer";
      return;
    }
  }
  next_resource_seq_no_ = resource_usage_batch.seq_no() + 1;
```
I think ` next_resource_seq_no_ = resource_usage_batch.seq_no() + 1;` should be updated before we do  
```
    if (resource_usage_batch.seq_no() < next_resource_seq_no_) {
      RAY_LOG(WARNING) << "Discard the the resource update since local version is newer";
      return;
    }
```

**Comment by rkooo567** [comment]
@WangTaoTheTonic can you provide the full log? I cannot see `Expected seq#: "
        << next_resource_seq_no_ ` from the log
