### ISSUE TITLE
[Feature] Simple replay for Simple Q algorithm

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#21633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I would like to disable prioritized replay for Simple Q algorithm, as the original DQN paper does not use prioritized replay and reproducing the paper with RLlib is at this point not possible (also to other facts I mentioned to @sven1977 , like e.g. no possibility to use another optimizer, but Adam, or having the extra 1x1 convolutional layer in the `VisionNet` which gives more parameters in the neural net than was used by Minh et al. (2015)). 

I would like to use the `['prioritized_replay'] = False` parameter in the trainer configuration to set prioritized replay off when needed. 

At present this configuration parameter gives an error messag from the `merge_trainer_configs` as this parameter is not in the `COMMON_CONFIG`. But even, if we would allow this parameter, the `LocalReplayBuffer` as well as the `MultiAgentReplayBuffer`, both rely on the `PrioritizedReplayBuffer` that requests `alpha>0` - __so, replay can not be turned off__. 

### Use case

Replicating papers from research or isolating the effect of prioritized replay on the performance of the algorithm can simply be achieved by setting 

```
"prioritized_replay": False
```

For a PR I need your guidance though, as I do not know what is the direction taken by RLlib here. I saw that the `LocalReplayBuffer` has been fully replaced by the `MultiAgentReplayBuffer`. Furthermore, there exist the `prioritized_replay` in `DQN`, but given the fact that `MultiAgentReplayBuffer`s do always use the `PrioritizedReplayBuffer` I wonder if this has any effect. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @simonsays1980 , thanks for raising this. This is actually a bug. SimpleQ should not use a prio. replay buffer.

Here is a PR that fixes this issue. Just as an information: We are working on a more API to specify/configure/define replay buffers and custom replay buffers.

https://github.com/ray-project/ray/pull/21665

**Comment by simonsays1980** [comment]
> Hey @simonsays1980 , thanks for raising this. This is actually a bug. SimpleQ should not use a prio. replay buffer.
> 
> Here is a PR that fixes this issue. Just as an information: We are working on a more API to specify/configure/define replay buffers and custom replay buffers.
> 
> #21665

The API sounds promising @sven1977! Really cool idea! Do you think we could also do a similar thing with optimizers for the training step? Altogether the whole RL algorithm becomes more modular - I like this approach.
