### ISSUE TITLE
[Core] Ray Buffers should have const data

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#21632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

There is no situation where Buffer needs to have non-const data. We should always restrict our types as much as possible. Hence, we should restrict Buffer to only have const data. (i.e. `data_` pointer is of type `const uint8_t *`)

Agreed, @jovany-wang ?

### Use case

Better type restrictions on code

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I think this is right. It seems dangerous we return non const pointer to the caller since ray objects are immutable anyway. 

Why don't you try creating a PR and see if we can compile it?

**Comment by jon-chuang** [comment]
Hmm, I've been looking into it. I'm starting to feel that we should distinguish between `Mutable` and `Immutable` at the type level.

Not sure how this plays with https://github.com/ray-project/ray/pull/21250 and the like of sharing responsibility for buffer lifetimes across language worker code and Ray core.
