### ISSUE TITLE
[Feature] support to Chinese or support utf-8 for code for python api

### ISSUE THREAD

**Issue by verigle** [ray-project/ray#21642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

def test():
    # 测试
    print("测试")

if add @ray.romote then will be error 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mattip** [comment]
I cannot reproduce. The code below works for me on Ubuntu20.04, with the locale set to `LC_CTYPE="en_US.UTF-8"` on python 3.9.9 using ray 2.0.0dev0 (latest HEAD). Could you report
- your operating system (windows? linux?)
- the results of `locale` (on linux) or `chcp` (on windows)
- your python version and how you installed it (conda? python.org?)
- what version of ray are you using (`ray.__version__`)
- what error are you getting?

```
import ray

ray.init()

@ray.remote
def test():
    # 测试
    print("测试")

assert ray.get(test.remote()) == 1
```

**Comment by pcmoritz** [comment]
Looks like the issue is fixed then, please re-open if it still happens.
