### ISSUE TITLE
[Java] Change API `ActorLifetime.DEFAULT` to `ActorLifetime.NON_DETACHED`

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21647]
Currently, we use a `DEFAULT` as an enum item of ActorLifetime which aligns with Python, but we've discussed this API in the next coming PR https://github.com/ray-project/ray/pull/21283 , and we thought `NON_DETACHED` is more reasonable than `DEFAULT`.

Considering that we haven't released `ActorLifetime` APIs, and the next official releasing is 1.1.10, we should make the final APIs for 1.1.10.

**Comment by jovany-wang** [comment]
We finished the change in PR #21639 .
@ericl @architkulkarni Could you guys help to pick to 1.1.10?

**Comment by architkulkarni** [comment]
Unfortunately it is too late to cherry-pick this into 1.10.0, but we will include this in 1.11.0.
