### ISSUE TITLE
Adding new Framework to Ray library

### ISSUE THREAD

**Issue by mariaboerner1987** [ray-project/ray#21651]
Hey Ray team,

I'm working on the open source project Flower that enables federated learning for different ML frameworks such as scikit, PyTorch (Lightning), and many more. In order to perform multi-machine simulations of Federated Learning, we have used Ray to spawn virtual clients and making different research settings in the field of federated learning possible.
Our open-source repository contains already example available here: https://github.com/adap/flower/blob/main/examples/simulation_pytorch

We wanted to reach out to ask whether you'd be interested in adding Flower to your ecosystem at the documentation ray-libraries.html and/or adding/linking our example to your documentation as well? If so, we could open a PR.

We would also be interested in writing a Blog Post about this example and promoting it together with Ray. Is this something you would be interested in?

Many regards,
Maria

**Comment by richardliaw** [comment]
Absolutely, this is awesome! Feel free to create a PR for the ecosystem page and perhaps add a page under "Other Libraries".

A blog would be awesome too, I'd be happy to help provide feedback at any stage.

**Comment by mariaboerner1987** [comment]
Great. Then we will make a PR for adding Flower to the ecosystem.
Do you mean with "Other Libraries" the "More Library" in the documentation such as https://docs.ray.io/en/master/joblib.html? I guess we will create a separate PR for this. 

I will contact you via mail about the blog post.

**Comment by richardliaw** [comment]
Yep, that sounds great! Feel free to reach out on slack too if you want faster correspondence.
