### ISSUE TITLE
[Kuberay] Ray CI integration with Kuberay, including Ray libraries

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#21657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Make sure the Ray/Kuberay integration is tested in our CI, including making sure libraries run and components like the Ray client is functional and doesn't break.

The best way to do this is to port this new CI functionality https://github.com/ray-project/ray/pull/20256 and the associated tests written by the Ray library team to minikube using Kuberay. This makes sure that all integrations are working well on Ray + Kubernetes and also the relevant code-paths are tested.

Minikube is a very nice environment for testing and developing Kubernetes locally so building on top of that makes a lot of sense. Technically, to get this working we need to find a way to run Minikube inside of our CI docker environment.

cc @krfricke who expressed interest in this

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
There a test of autoscaling support in the Ray CI.
Will open an issue tracking test of Ray libraries in the KubeRay repo.
