### ISSUE TITLE
[Kuberay] Optimize API calls of Kuberay Node Provider to k8s API server

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#21656]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

There are several opportunities to optimize the API calls in the Kuberay/Ray autoscaler integration at the moment:

- As pointed out in https://github.com/ray-project/ray/pull/21086#discussion_r785239788, we should use `resourceVersionMatch=NotOlderThan` in https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list for listing Pods
- We should try to see if it is possible to request less data from Kubernetes (e.g. for listing pods, we only need pod names and not the full pod specifications)
- We should try to see if we can include some throttling mechanism from the autoscaler side and make less API requests if a lot of Ray clusters are running in a K8s cluster to improve scalability (this is most likely not an issue for most users, but there might be some users who want to run the autoscaler with many clusters)

In general we should think about other ways to minimize API calls, see also the comment in https://github.com/ray-project/ray/pull/21086#discussion_r782652988

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I'm working on these problems now.

The list calls used to serve non_terminatated_nodes are the most problematic aspect of the current setup -- these have the potential to wreck a user's Kubernetes cluster if there are enough Ray clusters running with enough total pods.
