### ISSUE TITLE
[Kuberay] Automatically generate Autoscaler YAML config from CRDs

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#21655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

At the moment in https://github.com/ray-project/ray/pull/21086, the autoscaler config is manually posted to Kubernetes and shared between Ray clusters (and needs to be manually kept in sync with the Ray cluster CRD). Going forward we should autogenerate the config from the CRD and allow per cluster configs.

I think this is pretty important (P1) since it impacts the user interface, which we should try to stabilize sooner rather than later.

There are two ways to do this:

- In the Kuberay operator, generate the .yaml from the head and worker groups in the RayCluster CRD statically when the cluster is instantiated, create a  the autoscaler yaml as a ConfigMap and mount it into the autoscaler side car. This has the advantage that it is super robust and doesn't increase the number of k8s API requests and keeps kubernetes specific code out of the autoscaler as much as possible.
- Generate the .yaml dynamically in the autoscaler as proposed in https://github.com/ray-project/ray/pull/21086#issuecomment-1013563640. This has the advantage that it supports dynamically updating head and worker groups.

I would vote for the first solution for the added robustness -- dynamically updating groups doesn't seem like an important feature (but per cluster groups and not having to create the yaml files manually definitely is!).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I vote for the second option, for the reason that running `kubectl apply` against a running cluster must result in an updated autoscaling configuration.

**Comment by DmitriGekhtman** [comment]
In option 1 it would take a while (a few minutes, anecdotally?) for the updated config map to propagate to the autoscaler container's file system.
