### ISSUE TITLE
[tune] ray.tune blocks if running an experiment for more than 2 times in cluster mode

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#2165]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Darwin BeardeMacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 2.7.15
- **Exact command to reproduce**:

### Describe the problem

I'm using ray.tune with the simplest example code. It went well when I'm using single node mode through `ray.init()`. Then I started a one node cluster using `ray start --head --redis-port 8001` and passed the address to `init()`. The experiment finished for the first run, but hung forever in the second run, with the below message.

Is this issue expected or not? which means I have to restart ray cluster every time after I issue an experiment

### Source code / logs

```
def train_func(config, reporter):  # add a reporter arg
    for i in range(2):
        time.sleep(2)
        reporter(timesteps_total=i, mean_accuracy=i+97)  # report metrics


ray.init("30.55.72.250:8001")
ray.tune.register_trainable("train_func", train_func)

tune.run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "layer1": {
                "class_name": tune.grid_search(["a"]),
                "config": {"lr": tune.grid_search([1, 2])}
            },
        },
        "local_dir": os.path.expanduser("~/tmp")
    }
})
```

error log
This worker or driver is waiting to receive a class definition so that it can deserialize an object from the object store. This may be fine, or it may be a bug.

  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="30.55.72.250:8001")

**Comment by richardliaw** [comment]
Can you try installing the latest Ray via wheels and let me know how that goes? http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray

**Comment by ericl** [comment]
Might be the same issue as https://github.com/ray-project/ray/issues/1555

**Comment by old-bear** [comment]
@richardliaw 
Hi, I've done reinstallation according to the docs:
```
[^_^ 21:04 ~/Workspace/Alps-automl/python] pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.4.0-cp27-cp27m-macosx_10_6_intel.whl
Collecting ray==0.4.0 from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.4.0-cp27-cp27m-macosx_10_6_intel.whl
  Downloading https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.4.0-cp27-cp27m-macosx_10_6_intel.whl (9.1MB)
    100% |████████████████████████████████| 9.1MB 925kB/s
Requirement not upgraded as not directly required: numpy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (1.14.3)
Requirement not upgraded as not directly required: colorama in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (0.3.9)
Requirement not upgraded as not directly required: click in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (6.7)
Requirement not upgraded as not directly required: six>=1.0.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (1.11.0)
Requirement not upgraded as not directly required: redis in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (2.10.6)
Requirement not upgraded as not directly required: psutil in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (5.4.5)
Requirement not upgraded as not directly required: pyyaml in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (3.12)
Requirement not upgraded as not directly required: pytest in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (3.5.1)
Requirement not upgraded as not directly required: funcsigs in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (1.0.2)
Requirement not upgraded as not directly required: flatbuffers in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from ray==0.4.0) (2015.12.22.1)
Requirement not upgraded as not directly required: setuptools in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest->ray==0.4.0) (39.0.1)
Requirement not upgraded as not directly required: py>=1.5.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest->ray==0.4.0) (1.5.3)
Requirement not upgraded as not directly required: more-itertools>=4.0.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest->ray==0.4.0) (4.1.0)
Requirement not upgraded as not directly required: pluggy<0.7,>=0.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest->ray==0.4.0) (0.6.0)
Requirement not upgraded as not directly required: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pytest->ray==0.4.0) (18.1.0)
alps-common 1.0.1.5 has requirement keras==2.0.6, but you'll have keras 2.1.6 which is incompatible.
Installing collected packages: ray
  Found existing installation: ray 0.4.0
    Uninstalling ray-0.4.0:
      Successfully uninstalled ray-0.4.0
Successfully installed ray-0.4.0
```
However, the problem still exists with the same log above

**Comment by old-bear** [comment]
@ericl I've noticed that this issue may be fixed in #1927 
However, it seems that the patch doesn't appear in the latest tag 0.4.0. Could someone please release a new tag?

**Comment by robertnishihara** [comment]
@old-bear, you can try out the latest code by following the instructions at http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray. The next release is planned for several weeks from now.

**Comment by luweichao** [comment]
@robertnishihara , I encountered the same problem as @old-bear did and I installed the latest version of ray with "pip install git+https://github.com/ray-project/ray.git#subdirectory=python", but the problem still exists.

**Comment by old-bear** [comment]
@robertnishihara I've tried the latest ray by compiling it from source and install it on my machine according to the docs. Unfortunately, it still got no luck. The second run again hung forever, but this time leaves no error message:
```

Created LogSyncer for /Users/Bear/tmp/my_experiment/train_func_1_class_name=a,lr=5_2018-06-21_13-37-13ySNIoV ->
This worker or driver is waiting to receive a class definition so that it can deserialize an object from the object store. This may be fine, or it may be a bug.

(just hang in here forever)
```

The problem looks muck like the same as @luweichao . I think it might be helpful to check what's we have in common to fix this issue

(BTW, the installation from source took some effort because the build failed with messages about `parquet`. However, what really missing is thrift, which is not included in the brew list)

**Comment by robertnishihara** [comment]
If you check the logs in `/tmp/raylogs/` is there anything interesting? Any other error messages there?

Can you post the full stdout/stderr from the run as well as the full runnable script.

**Comment by robertnishihara** [comment]
Hmm, if you replace the `ray.init(...)` call with `ray.init(num_cpus=8)`, does that fix the issue? That seemed to fix it for me.

**Comment by old-bear** [comment]
`ray.init(num_cpus=8)` works, but the point is I want to use the cluster mode of ray so that the address must be passed into `init`.
I clean all the former logs and reproduce the problem
My trainable:
```
def train_func(config, reporter):  # add a reporter arg
    for i in range(2):
        time.sleep(1)
        print("in func %s" % os.getpid())
        reporter(timesteps_total=i, mean_accuracy=i)  # report metrics


ray.init("30.55.73.33:43435")
ray.tune.register_trainable("train_func", train_func)

tune.run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "layer1": {
                config": {"lr": tune.grid_search([1,5])}
            },
        },
        "local_dir": os.path.expanduser("~/tmp")
    }
})

```

The standard output for the 2nd run (since 1st always succeeds):
```
^_^ 12:00 ~/PycharmProjects/Playground] python ray_test.py
== Status ==
Using FIFO scheduling algorithm.
Result logdir: /Users/Bear/tmp/my_experiment
PENDING trials:
 - train_func_0_class_name=a,lr=1:	PENDING
 - train_func_1_class_name=a,lr=5:	PENDING

Created LogSyncer for /Users/Bear/tmp/my_experiment/train_func_0_class_name=a,lr=1_2018-06-22_12-00-53K8X2Qo ->
WARNING: Serializing objects of type <class 'ray.tune.registry._Registry'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 1/8 CPUs, 0/0 GPUs
Result logdir: /Users/Bear/tmp/my_experiment
PENDING trials:
 - train_func_1_class_name=a,lr=5:	PENDING
RUNNING trials:
 - train_func_0_class_name=a,lr=1:	RUNNING

Created LogSyncer for /Users/Bear/tmp/my_experiment/train_func_1_class_name=a,lr=5_2018-06-22_12-00-53LbQU2p ->
This worker or driver is waiting to receive a class definition so that it can deserialize an object from the object store. This may be fine, or it may be a bug.

```

Some error logs found in `/tmp/raylogs/*.err`
```
INFO:root:message-handler: driver_removed_handler
INFO:root:Driver 96bb6f8fb64061b810a874259828f5a0d02339cc has been removed.
INFO:root:Removed 67 dead redis entries of the driver from redis shard 0.
Allowing the Plasma store to use up to 13.7439GB of memory.
Starting object store with directory /tmp and huge page support disabled
Disconnecting client on fd 24
Disconnecting client on fd 23
Disconnecting client on fd 25
```

**Comment by old-bear** [comment]
Yes, I removed the former ray using `pip uninstall ray` and reinstalled the current version building from source. Maybe the uninstallation is not clean enough?

**Comment by robertnishihara** [comment]
Yeah, when reinstalling, I would just `rm -rf` the entire Ray directory and reclone it.

**Comment by surehb** [comment]
@robertnishihara , @luweichao we have a fix for this issue, and now we are testing it with @old-bear internally. Will send PR once the fix is verified.

**Comment by old-bear** [comment]
The fix by @surehb above works in this case, and has been tested for a week on a large cluster. This issue can be closed now. Thanks guys.
