### ISSUE TITLE
[Kuberay] Polish documentation and add example configurations

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#21663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Work with users to make sure the documentation is good and makes the users successful.

Add good example configurations (Kuberay RayCluster CRD yaml files) that can used by users to solve their problems -- you can get some ideas from the existing autoscaler configurations.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
We have some progress on this.
Further particular docs issues should be tracked in the KubeRay repo.
