### ISSUE TITLE
[Kuberay] Expose Ray client and dashboard in Kuberay and add docs about it

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#21662]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Add service definitions to expose the Ray client and dashboard in Kuberay (with info on how to thread it through a Kubernetes ingress, so it can work out of the box for users).

Add documentation on these.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
This is done.
