### ISSUE TITLE
[Bug] pg_long_running_performance_test is failing

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21679]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

pg_long_running_performance_test is failing. It succeeds at c0f12022785f4b7b8ca1deb1ba2720c8652b99d8, and start failing around 4a55d10bb1b70971f50a3872421f2c1eebd84e64. We need to bisect this. 

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @jjyao

**Comment by jjyao** [comment]
Based on the bisect, it's failing due to  4a55d10. The code has been reverted.
