### ISSUE TITLE
Issue on page /rllib/core-concepts.html

### ISSUE THREAD

**Issue by lorepieri8** [ray-project/ray#21678]
Broken link in the docs:

https://docs.ray.io/en/latest/rllib/rllib-concepts.html#policy-evaluation

(clicking on "Rollout workers" in https://docs.ray.io/en/latest/rllib/core-concepts.html)

**Comment by ArturNiederfahrenhorst** [comment]
This link is working nowadays, closing because this seems fixed and is inactive.
