### ISSUE TITLE
[Feature] Accelerate creation of large clusters [k8s] [GKE]

### ISSUE THREAD

**Issue by olivierlabreche** [ray-project/ray#21683]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

When creating large Ray clusters on GKE, the creation process appears iterative, as if not all workers were requested at once.

For example, creating a cluster of 200 workers with 15 GPUs each will initially request about 140 worker pods (creating, pending or running) after 2 minutes. Many of them will be in pending stages (presumably until GKE provisions the nodes).

![image](https://user-images.githubusercontent.com/91693350/150022563-d2c32fc6-e024-41f7-9467-e0ac4f92c448.png)

At this point, the pod count (creating, pending or running) starts increasing much more slowly than during the first 2 minutes. Eventually, after 8 minutes, all 200 pods have been requested (plus head and operator for a total of 202):

![image](https://user-images.githubusercontent.com/91693350/150023166-6d8a1cda-ca84-4596-9c09-fc6145e2fa10.png)

In total, it takes about 11-12 minutes for all workers to be ready.

Would you have any explanation for what we are observing? Would it be possible for all worker pods to be requested up front so that GCP may provision all required nodes in parallel (if this is not the case)?

### Use case

User creates a large cluster on k8s / GKE.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wuisawesome** [comment]
@DmitriGekhtman do you know if there's a quick ratelimiting argument that we just need to document/expose here?

**Comment by DmitriGekhtman** [comment]
The situation can be improved by setting the following environment variables for the operator pod.

AUTOSCALER_MAX_LAUNCH_BATCH=1
AUTOSCALER_MAX_CONCURRENT_LAUNCHES=9999

The defaults are 5 and 10 respectively. See https://github.com/ray-project/ray/blob/90093769df71ea4f49fdb7004565b4b747c62fcf/python/ray/autoscaler/_private/constants.py#L37-L44

This will result in the desired 200 pods launched in a single batch.

I think these settings should be default when deploying Ray on K8s. What do you think @wuisawesome ?

Also, we should document these environment variables (and many others).

**Comment by wuisawesome** [comment]
yup, i think this is the second time these args have come up.

**Comment by wuisawesome** [comment]
Let's bump this up to p1 if a third user hits this problem.

**Comment by DmitriGekhtman** [comment]
I'm going to raise the priority on this, to remind myself to make the fix on the env values for K8s.

**Comment by DmitriGekhtman** [comment]
@olivierlabreche 
This might be something you're already aware of -- when running larger Ray clusters, it's a good idea to keep tabs on the operator's memory usage.

**Comment by olivierlabreche** [comment]
Thank you @DmitriGekhtman, I will try this suggestion when I get some time and report back. This is very helpful.

**Comment by DmitriGekhtman** [comment]
The operator discussed in this issue has been deprecated and will be removed in Ray 2.2.0.
KubeRay has solved this issue by making autoscaling single-threaded and setting default upscaling speed to infinity.
