### ISSUE TITLE
[Feature][runtime env] URI reference refactor

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#21695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently, we generate a URI list in python worker when we validate a runtime env input. The related code is here https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/validation.py#L394. 

But, if we want to support cross-language, this logic can't be reused. For example, If we want to create a python runtime env in java, we should rewrite this logic in Java worker.

So, to address this issue, we should move this URIs generating logic from python worker to agent. And agent will reply the URIs to worker pool of raylet for reference counting. If we do that, this logic will become a general step which can be used for all the language workers. Actually, the URI resources are also downloaded by agent. So I think that makes sense.

But, if we generate URIs in agent, we will bring a risk condition. For example:
If worker A is using a runtime env A with URI A. At this point, a new task with runtime env B comes and "URI A" is also included in  runtime env B. But raylet doesn't know the URI list of runtime env B before agent reply the `CreateRuntimeEnv` rpc and can't increase the reference counter of "URI A" immediately. At this time, if worker A exits, the reference counter of "URI A" will be decreased to 0 and be deleted. 

In order to avoid risk condition, maybe we should make a URI reference refactor. Here is a proposal:
- Move the URI reference counting from worker pool to agent. We will maintain two maps in agent:
     * Map from runtime env to URIs
     * Map from URI to reference counter
- Instead, we can add two new maps in worker pool to be a runtime env reference counting:
     * Map from id to runtime env.
     * Map from runtime env to reference counter and runtime env context.
- In this refactor, raylet doesn't know the concept of URI. All the logics of URI can be handled by agent itself.
- Another benefit is that we can avoid sending some unnecessary `CreateRuntimEnv` RPCs when the runtime env already downloaded by agent. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by SongGuyang** [comment]
@edoakes @architkulkarni what do you think of this proposal? @rkooo567 could also give advise? cc @raulchen

**Comment by rkooo567** [comment]
Sorry for my ignorance, but is moving the logic into the core worker also an option? What's the pros and cons of this approach?

**Comment by SongGuyang** [comment]
Yep, it is also a alternative. But I think core worker is also unnecessary to know the concept of URIs. We should try to avoid adding unnecessary logic in worker for runtime env and unify the logics to agent. It is good for modularization and pluggability. And it is also hard to maintain a framework which needs to add code both in C++ and python.

**Comment by architkulkarni** [comment]
Thanks for writing down these detail! I think this proposal makes sense and I don't see a problem with it.

**Comment by rkooo567** [comment]
What’s the diff between runtime env vs uri? Is this impossible to completely remove states from worker pool?

**Comment by architkulkarni** [comment]
A single runtime environment can depend on multiple URIs.  Each URI corresponds to a single resource on disk, like `working_dir`, a conda environment, or a module in `py_modules`.

As for whether it's possible to make the worker pool stateless, that seems tricky if I'm understanding correctly: When we schedule a task with a runtime env, we need to know if there's an existing worker we can schedule it on that already has the correct runtime_env, or if we need to start a new worker with the desired runtime_env.  So it seems like we at least need to store the map from worker ID to runtime env as part of the state.

**Comment by SongGuyang** [comment]
> What’s the diff between runtime env vs uri? Is this impossible to completely remove states from worker pool?

If we remove states from worker pool, raylet need to send a rpc every time when worker is created or worker dies. Actually, if the job only uses a job level runtime env, raylet only need to send one rpc to agent before the job finished.

**Comment by rkooo567** [comment]
To be clear, do we need to send a rpc whenever worker is created or a new task is scheduled? And what’s the overhead of rpc usually (single round trip latency + qps) I suspect this is very low (local rpc) and could be premature optimization to cache info at worker pool? Any thoughts?

**Comment by SongGuyang** [comment]
> To be clear, do we need to send a rpc whenever worker is created or a new task is scheduled? 

Yep, If there is no state in worker pool, we don't know if the runtime env has been created and can't get the runtime env context for setup worker. And we need send a rpc to agent for updating the reference counter when a worker is created or a worker dies.

**Comment by SongGuyang** [comment]
> And what’s the overhead of rpc usually (single round trip latency + qps) I suspect this is very low (local rpc) and could be premature optimization to cache info at worker pool? Any thoughts?

Yep, maybe this overhead is low. But if we can optimize this by a reasonable way, I will try to do this. And I think add some states in worker pool is a way to do this optimization. The "runtime env reference counting" I mentioned in the proposal is just like a cache as you said.

**Comment by rkooo567** [comment]
Hmm i think it depends on the complexity of caching implementation, but if it is not very straightforward, I prefer to keep state only at agents and make all other components stateless. That seems way easier to understand and bug free

**Comment by SongGuyang** [comment]
My thought is that:
- Worker pool manage the life time of runtime env because it knows which runtime env is needed by which workers.
- Agent manage the life time of URIs because agent also download the resources.

But I don't ensure if this proposal will affect the implementation of caching https://github.com/ray-project/ray/pull/20273. @architkulkarni What do you think?

**Comment by SongGuyang** [comment]
@edoakes @raulchen What do you think about the discuss above?

**Comment by rkooo567** [comment]
Lmk if I am wrong, but this can be a lot simplified if we have CreateRuntimeEnvIfNeeded Rpc (that requests a list of uri). 

I personally don’t like that we have ref counting logic within a worker. It is a big complexity and bad separation of concern. 

I am technically not against in optimization, but we should do it only when there’s workload that can be benefitted by it.

**Comment by SongGuyang** [comment]
> I personally don’t like that we have ref counting logic within a worker. 

Do we have an alternative? We support setting runtime env in actor/task level now. Maybe worker is the best reference substance？

**Comment by rkooo567** [comment]
Let me know if I am missing something. I am still not very familiar with the implementation. 

Maybe alternative approach could be always sending RPC to agent and we only handle uri references? 

```
message CreateRuntimeEnvIfNeeded {
    str json_serialized_runtime_env
}

message DeleteRuntimeEnvIfNeeded {
    str json_serialized_runtime_env
}
```

and agent has ref to the uri. When uri ref goes to 0, it cleans up the uri (maybe with some caching timeout to avoid requesting the same uri after).

All workers just need to send this RPC when it is created / deleted.

**Comment by SongGuyang** [comment]
Should we consider the idempotence of this two RPCs?

**Comment by rkooo567** [comment]
I guess we don't need to worry about network error since it is all done locally? That said, maybe we don't need to worry about it.

This also makes me think; agent is a self-recovering component. How are we currently handling agent failures?

**Comment by SongGuyang** [comment]
Currently, we don't have state about reference counting in agent. So we don't need to handle agent failures?

I think this is a good question! When we move the reference counting logic to agent, we should consider agent failures any more.

**Comment by rkooo567** [comment]
Hmm interesting. In this case, the alternative is to keep all ref counting logic into worker pool and keep agent stateless...

**Comment by SongGuyang** [comment]
@rkooo567 Yep, let me take some time to summarize. Thank you for this discuss.

**Comment by SongGuyang** [comment]
Based on the discussion above, if we want to do this refactoring(move this URIs generating logic from python worker to agent), we have three options:

### Option 1: Keep all ref counting logic in worker pool and keep agent stateless.

This is what we already implemented currently. In worker pool, we have two maps to keep the URI reference(by `runtime_env_manager`):
- Map from id to URIs. (The id should be worker id or job id) 
- Map from URI to reference counter.

In this option, we should consider how to avoid the risk condition:
> If worker A is using a runtime env A with URI A. At this point, a new task with runtime env B comes and "URI A" is also included in runtime env B. But raylet doesn't know the URI list of runtime env B before agent reply the CreateRuntimeEnv rpc and can't increase the reference counter of "URI A" immediately. At this time, if worker A exits, the reference counter of "URI A" will be decreased to 0 and be deleted.

On possiable solution is adding a new RPC like `URIs GetUrisFromRuntimeEnv(RuntimeEnv)` from worker pool to agent. Before sending RPC `CreateRuntimeEnv`, worker pool uses `GetUrisFromRuntimeEnv` to get the URIs from agent and account it in the ref counting. There is no risk condition In this way.

Failure handling:
- If agent fails, raylet will restart it. At this time, worker pool should tell agent all the used URIs because agent should scan local disk to remove all the unused local resources or recover its cache. (Not sure if we already did this?)
- If raylet fails, all the worker processes will exit and agent will exit as well. In this case, we don’t need to recover the URI ref counting in worker pool. 

To summarize this option:
- Pros：
    - Keep reuse the module `runtime_env_manager` and don’t need to change a lot for ref counting.
    - Don’t need to recover the URI ref counting in worker pool.

- Cons：
    - Add a new RPC to avoid the risk condition.
    - Worker pool manages the URI reference. Agent generates the URIs and manages the URI cache. The logic of URI is separated. 


### Option 2: Keep ref counting logic of Runtime Env in worker pool and keep ref counting logic of URI in agent.

- Move the URI reference counting from worker pool to agent. We will maintain two maps in agent:
     * Map from runtime env to URIs
     * Map from URI to reference counter
- Instead, we can add two new maps in worker pool to be a runtime env reference counting:
     * Map from id to runtime env
     * Map from runtime env to reference counter and runtime env context

The core concept of this option:
- Worker pool manage the life time of runtime env because it knows which runtime env is needed by which workers.
- Agent manage the life time of URIs because agent also download the resources.

Failure handling:
- If agent fails, raylet will restart it. At this time, worker pool should tell agent all the used Runtime Envs instead of URIs. Agent should recover the URI reference counting maps from the Runtime Envs. And agent should also scan local disk to remove all the unused local resources or recover its cache. 
- If raylet fails, all the worker processes will exit and agent will exit as well. In this case, we don’t need to recover the runtime env ref counting in worker pool. 

To summarize this option:
- Pros：
    - No issue of risk condition.
    - Worker pool don’t know the concept of URI.

- Cons：
    - We need to maintain two different reference counting module in worker pool(c++) and agent(python).
    - We need to recover the URI reference counting maps when agent fails.

### Option 3: Keep all ref counting logic in agent.

- Remove the current URI ref counting in worker pool and make worker pool stateless.
- Instead, add a map to do URI ref counting in agent:
    - Map from URI to reference counter
 
The behavior of worker pool:
-  When worker pool receives a submitted job with eager installed runtime env or intend to start a worker process, it always send the RPC `CreateRuntimeEnvIfNeeded`(renamed from `CreateRuntimeEnv`) to agent.
- When the job finished or the worker process exited, worker pool always send the RPC `DeleteRuntimeEnvIfNeeded`(new added) to agent.
- Agent should increase the ref counter of all the URIs of the runtime env when it receives `CreateRuntimeEnvIfNeeded` and decrease the ref counter when it receives `DeleteRuntimeEnvIfNeeded`.
- Worker pool should guarantee the number of  `CreateRuntimeEnvIfNeeded` and `DeleteRuntimeEnvIfNeeded` is equal. And this two RPCs are not idempotent.

Failure handling:
- Same to option 2.

To summarize this option:
- Pros：
    - No issue of risk condition.
    - Worker pool is stateless. No ref counting modules in worker pool. We can put all the logic in agent.

- Cons：
    - We need to send RPC for every worker process. We can’t cache the runtime env context for reusing in worker pool.
    - This two RPCs are not idempotent. 
    - We need to recover the URI reference counting maps when agent fails.

**Comment by SongGuyang** [comment]
@rkooo567 @edoakes @raulchen I have summarized three options in the reply above. Can we choose one by discussion? I prefer to option 2 or option 3.

**Comment by SongGuyang** [comment]
> @rkooo567 @edoakes @raulchen I have summarized three options in the reply above. Can we choose one by discussion? I prefer to option 2 or option 3.

+ @architkulkarni

**Comment by edoakes** [comment]
@SongGuyang for options 2 and 3, how will the agent recover the ref counts from the raylet? We can't just communicate the list of envs in use because we also need the count for each of them. If we're maintaining that, we're essentially doing ref counting in both places.

**Comment by SongGuyang** [comment]
@edoake For option 2, we only need to send the list of envs because worker pool will delete envs when the ref count of envs become to zero. Agent don't need to know the ref count of envs.
For option 3, we need to summerilize the ref count of envs from existing workers and jobs, and send it to agent. I think worker pool is easy to summerilize this. What do you think about this？

**Comment by architkulkarni** [comment]
Thanks a lot for the summary @SongGuyang!

I think your response to @edoakes makes sense.  To clarify for myself, the agent's URI refcounts mean different things in Option 2 and Option 3 (let me know if I misunderstood):

Example: Runtime envs in use are (A, A, B, C, C, C) (e.g. 6 workers), and all of these envs use some uri X.

Option 2: Agent's URI refcount is  {X: 3}.  It counts the number of unique runtime envs.  

Option 3: Agent's URI refcount is {X: 6}.  It counts the number of runtime envs with multiplicity, since the worker_pool's `CreateRuntimeEnvIfNeeded` is called six times (the worker pool doesn't maintain any state about which envs were already used.)

I just have one question: 
> For option 3, we need to summerilize the ref count of envs from existing workers and jobs, and send it to agent. I think worker pool is easy to summerilize this. 

How is it possible to summarize the refcount of envs from existing workers and jobs?  Wouldn't we need to summarize it from some existing state?  If that's the case, then even Option 3 isn't really stateless, right?  And in this case, in Option 2, the two maps maintained by `worker_pool` aren't strictly necessary since they can be generated at any time using the summarizing.  Does that mean we should think of the two maps in Option 2 as a performance optimization to skip the summarizing step?

At this early stage I would say I prefer Option 2 because it's easier to understand conceptually, and both 2 and 3 have a stateful worker_pool anyway.  But I'm eager to hear responses from others.

-----
P.S.
> If agent fails, raylet will restart it. At this time, worker pool should tell agent all the used URIs because agent should scan local disk to remove all the unused local resources or recover its cache. (Not sure if we already did this?)

To answer the question, we haven't already done this.

**Comment by rkooo567** [comment]
Can you also add option 4: Remove the dashboard agent restart feature? We can alternatively fate-share raylet and agents in this case. 

Do you happen to know when this feature is actually useful? (When's the time only agent processes fail when raylet doesn't)? 

Also cc @scv119 can you also take a look at this?

**Comment by scv119** [comment]
I think @rkooo567 summarizes this pretty good. I think a clean solution would be either

1. have all states managed by Raylet, and the python code is stateless and doing very dumb things.
2. have all states managed by a separate service (agent); and the Raylet has a shimmer that calls the service through RPCs.

In option 1, we can only spawn a python process to resolve those runtime dependencies (i.e. download files, pip installs), and the process exists once the dependency is resolved. In this way the failure handling is much easier; we could also potentially support runtime dependencies other than python scripts. Also, since the state is in C++, we could also easily broadcast the per node runtime env state to other node in the cluster for better scheduling decisions.

In option 2, we need to ensure the the runtime env service (agent) fate-share with Raylet; it seems to be a bit harder since managing a separate process in Ray is considered an harder problem; but maybe not fundamental.

**Comment by edoakes** [comment]
@scv119 I think there's also an alternative to do option (1) in a thread to avoid process overhead & complexity (harder to coordinate) (assuming calling into Python code from raylet thread is tenable)

**Comment by SongGuyang** [comment]
> Can you also add option 4: Remove the dashboard agent restart feature & follow option 3? We can alternatively fate-share raylet and agents in this case. The pro is we don't need to worry about failover at all. The con is idk how stable agents are.

It makes sense to remove the dashboard agent restart feature. But I think they are two issues. We can also choice option 1 or option 2 after we remove the restart feature?

**Comment by SongGuyang** [comment]
> How is it possible to summarize the refcount of envs from existing workers and jobs? Wouldn't we need to summarize it from some existing state? If that's the case, then even Option 3 isn't really stateless, right? And in this case, in Option 2, the two maps maintained by `worker_pool` aren't strictly necessary since they can be generated at any time using the summarizing. Does that mean we should think of the two maps in Option 2 as a performance optimization to skip the summarizing step?
> 

You are right!

**Comment by SongGuyang** [comment]
@rkooo567 Anyway, "Option 3 + removing agent restart feature" is acceptable for me. I think the current restart feature is used to cover some specific cases, like agent hang and some abnormal exiting. Maybe @fyrestone can discuss about this.

**Comment by rkooo567** [comment]
@SongGuyang I think I generally agree with Chen here. We should make one of the components (client or agent) stateless. Removing agent restart is an easy way to make agent stateful. There's also a proposal to improve the general code structure here; https://github.com/ray-project/ray/issues/22089 (detailed proposal is not out yet).

**Comment by SongGuyang** [comment]
@rkooo567 Make sense. I agree that a stateless client could make the code and structure more clear and easy to maintain.

**Comment by SongGuyang** [comment]
@rkooo567 @edoakes @scv119 @architkulkarni Can we reach an agreement now? The final proposal is：
- Choice the option 3 of https://github.com/ray-project/ray/issues/21695#issuecomment-1022873950. (like option 2 of https://github.com/ray-project/ray/issues/21695#issuecomment-1029448144)
- Removing agent restart feature. If agent exits, raylet kills itself.
- Make worker pool stateless.

**Comment by edoakes** [comment]
@SongGuyang sounds good to me.

**Comment by fyrestone** [comment]
> @rkooo567 Anyway, "Option 3 + removing agent restart feature" is acceptable for me. I think the current restart feature is used to cover some specific cases, like agent hang and some abnormal exiting. Maybe @fyrestone can discuss about this.

I am not sure if the agent port conflict issue still exists? If agent is failed to start because of a port conflict, then raylet kill itself. User will get a bad experience.

**Comment by rkooo567** [comment]
Yeah this option is only valid under the assumption agent is stable. Is this the only existing known problem you know? I think I can take it over and fix it
