### ISSUE TITLE
[Feature] Support for directing *all* logs to stdout

### ISSUE THREAD

**Issue by chhabrakadabra** [ray-project/ray#21707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

It would be useful to redirect all the logs that go into the [`/tmp/ray`](https://docs.ray.io/en/master/ray-logging.html#logging-directory-structure) directory to stdout, perhaps using a flag in `ray start`.

### Use case

We deploy our Ray clusters using Kubernetes. We have log aggregation in all our Kubernetes clusters (from stdout to Splunk). It would be very useful for **all** ray logs to go to Splunk and this can be easily achieved if Ray made it possible to just output all the logs to stdout.

## Current solution

This is **mostly** supported already by the `GLOG_logtostderr` environment variable, where if this environment variable is set on the driver and all Ray nodes at connection/startup time, application logging (i.e. logging within tasks/actors) and **most** internal Ray logging will be redirected to stdout/stderr.

### Missing coverage

A few internal Ray components are not respecting the `GLOG_logtostderr` environment variable, and are therefore still logging to files even when this environment variable is set.

- [ ] Dashboard
- [ ] Dashboard agent
- [ ] Log monitor
- [ ] Core workers
- [ ] Autoscaler

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@chhabrakadabra This is actually most supported already by the `GLOG_logtostderr` environment variable, where if this environment variable is set on the driver and all Ray nodes at connection/startup time, application logging (i.e. logging within tasks/actors) and **most** internal Ray logging will be redirected to stdout/stderr. I just opened up a [PR](https://github.com/ray-project/ray/pull/21754) adding documentation for this feature.

I'll rescope this issue to capture the missing coverage so we can track which internal Ray components are not yet respecting this environment variable, and we can close this issue once coverage is complete.
