### ISSUE TITLE
[Bug] [Autoscaler] Autoscaler Doesn't Use k8s Memory Limits When Scheduling Memory-Aware Tasks

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#21706]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

1. With a worker node declared in the cluster YML as having 1Gi requested and 5Gi limit (for k8s), I set an actor to request 1Gi of RAM (`memory=1024 * 1024 * 1024`)
2. I expected the actor to be scheduled on a worker node.

What happened in practice is that the actor got stuck in scheduling ("no available node types"). This is likely because only the requested memory amount is used (note: the dashboard shows the worker as having 5Gi as the max RAM available). Then, because there's some overhead on the Ray worker pod (~200MB), it already appears that the pod has < 1Gi available (1Gi request - 200MB = 800MB < actor requested 1Gi).

### Versions / Dependencies

Ray 1.9.2 run on cluster. Ray 1.10.0 run on the autoscaler/operator.

### Reproduction script

import ray

ray.init(address="your remote cluster")

@ray.remote(memory=1024 * 1024 * 1024)
class OneGigRam:
    def f(self):
        return "Ran f"

handle = OneGigRam.remote()
print(ray.get(handle.f.remote()))

"""
Example Cluster Config for Worker Node
- name: worker-node
  minWorkers: 1
  maxWorkers: 5
  rayResources: {}
  podConfig:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        component: ray-worker
        type: ray
      generateName: ray-worker-
    spec:
      restartPolicy: Never
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

      containers:
      - name: ray-worker
        imagePullPolicy: Always
        image: < YOUR RAY IMAGE HERE >
        command: ["/bin/bash", "-c", "--"]
        args: ["trap : TERM INT; touch /tmp/raylogs; tail -f /tmp/raylogs; sleep infinity & wait;"]
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 1000m
            memory: 5Gi
"""

### Anything else

Problem occurs every time.

Can workaround by setting `rayResources: {"memory": < chosen int value>}` in the `cluster.yml`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hora-anyscale** [comment]
Per Triage Sync: The old K8s autoscaler is not supported, if still needed in KubeRay please create a new issue

https://github.com/ray-project/kuberay
