### ISSUE TITLE
[Bug] [RLlib] Potential Memory Leak in RolloutWorker / Env wrapper?

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#21718]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

RLlib rollout worker crashes due to OOM error after 10 hrs of training.

### Versions / Dependencies

Ray version 1.9.1 (cluster environment anyscale/ray-ml:1.9.1-py37-gpu)

### Reproduction script

TODO

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by grechaw** [comment]
Hi @sven1977 is this indeed something that you or someone on the team will be looking at as a next item after the alpha-star delivery?  I know you're in contact with the reporter frequently -- it comes up each week when we sync as well.

**Comment by sven1977** [comment]
Hey @grechaw , yes, we have looked at this in close contact with the original reporter and have fixed on leak on our end via this PR (which also establishes solid CI memory leak tests for our main agents).
https://github.com/ray-project/ray/pull/15412

**Comment by sven1977** [comment]
Closing this issue.
