### ISSUE TITLE
[workflow] Sending signal to specific workflow/step

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#21725]
With workflow events, we are able to read data from external sources, i.e., sleep or some external queue.

Sometimes users want to send a specific event to a specific workflow/step. One way to do this is to have an event dispatcher which will dispatch the event to the specific step. But the downside is that it's not scalable and also if there is some garbage to the queue, it doesn't know when to delete them.

What we need here is a event provider for workflow and this event provide can send event from outside.

```
class WorkflowEventProvider(EventListener):
    # These two are API from EventListener
    async def poll_for_event(self, event_type) -> Event:
        ...
    async def event_checkpointed(self, event: Event):
        ...

   # This is the API to send event
   async def signal(self, workflow_id: Optional[str], event: Event):
       ...
```

With this, to implement a contract approval workflow, we'll do:

```
# s1 will create a contract and send the contract to the person for an approval
s1 = generate_contract.step(contract_object, need_approval="tom@gmail.com")

def approve_event(contract):
    e = workflow.wait_for_event(WorkflowEventProvider, contract.id)

    @workflow.step
    def next_step(approval_result):
        if approval_result == "APPROVE":
              return finalize_contract.step(contract)
       else:
            return reject_contract.step(contract)
    return next_step.step(e)

approve_event.step(s1).run_async(workflow_id="contract")
```

Then the workflow will block in waiting to approval.

To approve the contract, we'll need:

```
event_provider = WorkflowEventProvider()
event_provider.signal("contract", "APPROVE")
```
Then the "contract" workflow should resume.

Some implementations ideas:
- short term [ok for now]
  - Right now, we run `poll_for_event` in a event loop. So for this specific function, it can sleep and poll from a detached actor.  signal will tell the detached actor that the event is ready. Here, the detached actor need to record the event for fault tolerance.
- long term [need update workflow.wait_for_event]
 - The long term version of workflow.wait_for_event will be implemented without the event loop. It'll
   1. register the waiting info in a detached actor
   2. before the waiting finished, it'll suspend the workflow to release the resource
   3. when event is finished, it'll write the results to the wait_for_event step and just resume the workflow.
 - with this the implementation will be much easier, basically, signal will just tell the coordinator it's ready and resume the suspended ones.

**Comment by iycheng** [comment]
@ericl  @klwuibm @yuanchi2807  could you take a look?

**Comment by iycheng** [comment]
@klwuibm @yuanchi2807 

I think it's doable. Basically, it'll wait for a different event id:

```
    e1 = workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:first_line_approval")
    e2 = workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:second_line_approval")
```
Then each step will wait for e1 and e2.

Besides, if multiple steps are waiting for the same event, you can pass `e1` to them as well.

When sending signals, you can just `.signal(workflow_id, "{contract_id}:first_line_approval", EVENT_DATA)`


>How do we use the above API to send two different approval signals to two different workflow steps in the same workflow dag?

Just send with different event id.


> Is a single event_provider instance going to serve 1 contract or say 10,000 active contracts?

EventProvider here is just an interface between event manager and workflow. It's actually stateless.

So the scalability actually depends on the actual implementation.

The current event implementation won't be able to support 10k. We did have a plan to support the efficiency, but due to some reason, it was delayed. (https://github.com/ray-project/ray/pull/20200/files). So we decide to wait until it becomes a bottleneck and actually asked by users for their product usage.

With the long term version I mentioned in the ticket, 10k active contract is totally reasonable numbers and also with sharding, it should be able to support more.




@ericl  please let me know if you have any comments about the proposal as well.

**Comment by yuanchi2807** [comment]
@iycheng 
>> Then each step will wait for e1 and e2. 
Do you mean a step may choose to wait for one or more events? An event may be thought as a special type of input data to a step and thus its arrival is checkpointed?

From the point of view of workflow developer, an event-driven ray workflow is defined as:
- A DAG consists of steps to process data, issue notifications or receive events;
- Each event type in the DAG must be declared with a unique id, that can be subscribed by one or more steps;
- Every event object is associated with a workflow id (DAG instance) and event type id. 
- The status of a workflow id can be summarized as the list of event type ids received and the list of steps executed. 

What else do we expect someone creating a contract approval flow to know?

**Comment by iycheng** [comment]
> An event may be thought as a special type of input data to a step and thus its arrival is checkpointed?

Yes. workflow.wait_for_event returns a Workflow object. All the FT-related things are the same as normal workflow objects.

Here, when should the event step finish depends on what do we do in the event provider.

- it can ask for a specific event_type to come
- multiple steps can subscribe to the same event_type
- it should have data that comes with the event.

@yuanchi2807

**Comment by iycheng** [comment]
Also, cc @mwtian  who is recently working on RFC about checkpoint coroutine.

**Comment by yuanchi2807** [comment]
@iycheng 
- multiple steps can subscribe to the same event_type

To clarify, the steps subscribing to the same event_type cannot have sequential dependency, ie. one is in the upstream of another step, because such sequential dependency means out of order execution. Non-sequential dependency, such as multiple steps in different branches of a DAG, is fine.

**Comment by klwuibm** [comment]
@iycheng 

Two follow-on questions:

(1) Can a workflow step waits for more than one event?  Namely we have something like the following:
` 
   e1= workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:first_line_approval")
   e2= workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:export_control_approval")

  @workflow.step
  def next_step(approval results):
      if (approval_results = first_line_approval && export_control_approval):
            return finalize_contract.step()
      else
           return reject_contract.step()
      **return next_step.step((e1, e2))**        
`
(2) Currently, we don't allow a workflow DAG to have cycles.  However, in case one of the approval steps gets a rejection, we would like to resubmit and re-execute the entire workflow job from the beginning.  This implies conceptually a cycle.  In order to avoid such a cycle, we probably need treat any rejection as a termination of the workflow job and create a new workflow id for the resubmitted workflow job.  Moreover, we also might want to aggregate all the history associated with the entire life cycle of this contract workflow job execution, including all the rejected ones.  I wonder if the current workflow engine could support this.

**Comment by iycheng** [comment]
> @iycheng
> 
> * multiple steps can subscribe to the same event_type
> 
> To clarify, the steps subscribing to the same event_type cannot have sequential dependency, ie. one is in the upstream of another step, because such sequential dependency means out of order execution. Non-sequential dependency, such as multiple steps in different branches of a DAG, is fine.

I think for this case if it's upstream, you can just pass the data from upstream to downstream.

**Comment by iycheng** [comment]
> @iycheng
> 
> Two follow-on questions:
> 
> (1) Can a workflow step waits for more than one event? Namely can we have something like the following:
> 
> ```
> e1= workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:first_line_approval")
> e2= workflow.wait_for_event(WorkflowEventProvider, f"{contract_id}:export_control_approval")
> 
> @workflow.step
> def next_step(approval results):
>     if (approval_results = first_line_approval && export_control_approval):
>           return finalize_contract.step()
>     else
>          return reject_contract.step()
> return next_step.step((e1, e2))   
> ```
Yes, it's doable.


> (2) Currently, we don't allow a workflow DAG to have cycles. However, in case one of the approval steps gets a rejection, we would like to resubmit and re-execute the entire workflow job from the beginning. This implies conceptually a cycle. In order to avoid such a cycle, we probably need to treat any rejection as a termination of the workflow job and create a new workflow id for the resubmitted workflow job. Moreover, we might want to aggregate all the history associated with the entire life cycle of this contract workflow job execution, including all the rejected ones. I wonder if the current workflow engine could support this.

I think it's not a cycle. With dynamic workflow, it's just like a recursive call that is supported by workflow. Basically depends on the results, just generate a new step. You don't need to re-submit a workflow.

**Comment by yuanchi2807** [comment]
@iycheng We created some pseudo code to illustrate how events and workflow steps interact. 
![image](https://user-images.githubusercontent.com/84025022/151422861-7b552d9f-5509-444c-adb9-a04e975c4499.png)
The pseudo code is meant to express the approval flow in the diagram. 
```
e1= f"{contract_id}:first_line_approval"
e2= f"{contract_id}:second_line_approval")
e3= f"{contract_id}:ip_approval")
e4= f"{contract_id}:export_control_approval")
e5= f"{contract_id}:business_control_approval")
e6= f"{contract_id}:contract_approval")
```
Next define basic branch constructs. 
```
def eventnode(forms, approver, subscribed_event):
    input_form, output_form = forms
    notify_approver(input_form, approver)
    # the step is blocked by wait_for_event()
    w = workflow.wait_for_event(WorkflowEventProvider, subscribed_event)

    if w == 'approved':
        output_form['approver'] = 'approved'
        return (input_form, output_form)
    else:
        # rejection
        # start a new run of contract_wf with an updated input_form
        return contract_wf.step((input_form, {}))
    #...
    # if subscribed_event == 'approved':
    #   return updated_form
    # elif subscribed_event == 'rejected':
      # how to start rejection handling?

def chain(node_chain, upstream):
  wf = workflow.step(node_chain[0]).step(upstream)
  for e in node_chain[1:]:
    newwf = workflow.step(e).step(wf)
    wf = newwf
  return wf

@workflow.step
def merge(approved_forms):
    customized_check_logic()
    return output_form

@workflow.step
def fork(downstreams, upstream):
    wf = []
    for ds in downstreams:
        if type(ds) == WorkflowStepFunction:
            wf.append(ds.step(upstream))
        else:
            wf.append(workflow.step(ds).step(upstream))
    return gather.step(*wf)
```
Lastly declare processsing steps and assemble them to contract_wf. 
```
node_first_line_mgmt_review = lambda form: eventnode(form, 'firstline@email', e1)
node_second_line_mgmt_review = lambda form: eventnode(form, 'secondline@email', e2)
node_intellectual_property_review = lambda form: eventnode(form, 'ipapprover@email', e3)
node_export_control_review = lambda form: eventnode(form, 'ecapprover@email', e4)
node_business_control_review = lambda form: eventnode(form, 'bcapprover@email', e5)
node_contract_control_review = lambda form: eventnode(form, 'contractapprover@email', e6)

contract_wf =
workflow.step(node_contract_control_review) \
    .step(node_business_control_review) \
    .step(merge.step(fork.step( \
        [lambda processing_form: chain([node_first_line_mgmt_review, node_second_line_mgmt_review],processing_form), \
        lambda processing_form: chain([node_intellectual_property_review],processing_form), \
        lambda processing_form: chain([node_export_control_review],processing_form)])))

contract_wf.step((submitted_form,{})).run('contract_id')
```

What is unclear is the 'reject' path in `eventnode`, how does a step dynamically kick off a run with new data? And how can the history from initial submission be kept, say for audit reasons?

**Comment by iycheng** [comment]
@yuanchi2807     `w: Workflow = workflow.wait_for_event(WorkflowEventProvider, subscribed_event)`

`w` is a workflow, and you can't get the value out of workflow without passing it to other steps.

**Comment by klwuibm** [comment]
@iycheng okay, would something like the following would do:
'''
def eventnode(forms, approver, subscribed_event):
    input_form, output_form = forms
    notify_approver(input_form, approver)
  
    w = workflow.wait_for_event(WorkflowEventProvider, subscribed_event)

    @workflow.step
    def is_event_approved(wf_event):
        if wf_event.get('approved'):
            return true
        else:
            return false
    
    if is_event_approved.step(w):
        output_form['approver'] = 'approved'
        return (input_form, output_form)
    else:
        # rejection
        # start a new run of contract_wf with an updated input_form
        return contract_wf.step((input_form, {}))
'''

**Comment by yuanchi2807** [comment]
@iycheng Follow up question on a step function inside another step function, such as `is_event_approved() `above. When the outer step `eventnode()` failed after `w` is received, does reexecution of `eventnode()` recover `w`?

**Comment by iycheng** [comment]
@yuanchi2807  it's not correct. `.step()` returns object, so you can't use this: `    if is_event_approved.step(w):`

Keep in mind that event/steps are both `Workflow` and you can't dereference it unless you pass it to inputs.

```
def eventnode(forms, approver, subscribed_event):
    input_form, output_form = forms
    notify_approver(input_form, approver)
    w = workflow.wait_for_event(WorkflowEventProvider, subscribed_event)
    @workflow.step
    def is_event_approved(wf_event):
        if wf_event.get('approved'):
            output_form['approver'] = 'approved'
            return (input_form, output_form)
        else:
            return contract_wf.step((input_form, {}))
    
```

**Comment by yuanchi2807** [comment]
@iycheng Thanks for the refresher. Aside from the syntax error, I believe the multi-approval workflow example is feasible, assuming multiple `wait_for_event` allow some form of hiberation. `workflow.cancel ` in a simplified example seems to be a partial solution.

**Comment by yuanchi2807** [comment]
@iycheng Thanks for the refresher. I believe our confusion came from executing the workflow object returned from `wait_for_event`. e.g.
```
w = workflow.wait_for_event(SQSEventListener)
p = process_event.step(w)

@workflow.step
def process_event(e):
    print(e["Messages"][0]['Body'])
```

**Comment by iycheng** [comment]
@yuanchi2807 workflow event is not different from other workflow steps from the user side. From the user's perspective, it's like:

```
@workflow.step
def wait_for_event(*args):
    # don't return until receive the event.
```

What's different is about the internal implementation which we can make it more efficient and support FT and recover correctly from a failure.
We are supposed to provide the same semantic as the normal workflow step.

**Comment by yuanchi2807** [comment]
@iycheng Coming back to this strawman, we face a bit struggle to modularize the building blocks to express multi-approval workflows, in a similar way that we modularized machine learning pipelines. For example, how would one fork multiple downstream steps after "APPROVE" or reset/restart after "REJECT"?
```
# s1 will create a contract and send the contract to the person for an approval
s1 = generate_contract.step(contract_object, need_approval="tom@gmail.com")

def approve_event(contract):
    e = workflow.wait_for_event(WorkflowEventProvider, contract.id)

    @workflow.step
    def next_step(approval_result):
        if approval_result == "APPROVE":
              return finalize_contract.step(contract)
       else:
            return reject_contract.step(contract)
    return next_step.step(e)

approve_event.step(s1).run_async(workflow_id="contract")
```

**Comment by iycheng** [comment]
I believe here it's about constructing a DAG. So you probably want to put the DAG construction into a step function and return the created DAG (Workflow in this context) in that step. For example, 
```
A -> B -> C --- if failed --> A
          |-- if succeeded -> D
```
Then you probably will want a step and inside that step do A/B/C and depending on the result rerun the function or not.

Thinks it as ML training, where each iteration, you have some result and you'll decide where to do in the next step.

**Comment by iycheng** [comment]
@yuanchi2807 @klwuibm  since we are working on an efficient workflow event and this one should be a follow-up for that which is about how to implement event provider. So I assign this task to you two.
