### ISSUE TITLE
[Bug] VisionNetwork and ComplexInputNetwork fail with non-1x1 final convolutional layer and FC-stack.

### ISSUE THREAD

**Issue by mgerstgrasser** [ray-project/ray#21736]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I am trying to recreate [the "Nature CNN" model from OpenAI Baselines](https://github.com/openai/baselines/blob/master/baselines/common/models.py#L15) in RLLib using the built-in model catalog. This consists of three convolutional layers followed by one fully connected layer. I believe setting `conv_filters` and `post_fcnet_hiddens` to the correct sizes, i.e. `"conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1]]` and `"post_fcnet_hiddens": [512,]`, should achieve this. However, this fails in several variations: 

* Using tensorflow, I get an error from [tf/visionnet.py:140](https://github.com/ray-project/ray/blob/master/rllib/models/tf/visionnet.py#L140)  because the final convolutional layer's output isn't size 1x1. I believe that requirement makes sense if the CNN layer is the final layer of the model, but not with another fully connected layer after it. I believe the `if`-statement in line 140 should only be triggered if the `else`-path in l131 is taken, i.e. l140 should be indented one more level. However, this triggers another issue with the `tf.squeeze` in l171, because the fully connected layer still has the wrong shape for a squeeze. This could be fixed by flattening the final convolutional layer.
* Interestingly, this also doesn't work with a complex input net if the image input is wrapped in a Dict. In that case, this issue is only with the value layer and the `tf.squeeze` in l207. As far as I can tell the value output of the CNN is not even used by the complex input network.
* When using Torch instead of tensorflow, this also fails for the simple observation space, here due to some mismatched dimensions in [torch/visionnet.py:212](https://github.com/ray-project/ray/blob/master/rllib/models/torch/visionnet.py#L212). 
* It seems that using a complex input net and Torch this does work, surprisingly.

### Versions / Dependencies

Tested using Ray 1.9.1, Python 3.7.7

### Reproduction script
```
import gym
import ray
import ray.rllib.agents.a3c.a2c as a2c
from ray import tune
from ray.rllib.env.wrappers.atari_wrappers import wrap_deepmind
from ray.tune.registry import register_env


# Wraps a basic Atari image obs inside a Dict space
class GymToDict(gym.Wrapper):
    def __init__(self, env):
        assert isinstance(env.observation_space, gym.spaces.Box)
        super(GymToDict, self).__init__(env)
        self.observation_space = gym.spaces.Dict({"image": self.env.observation_space})
        self.observation_space.shape = [
            1,
        ]  # hack to keep RLLib from wrapping in another set of deepmind wrappers

    def reset(self):
        return {"image": self.env.reset()}

    def step(self, action):
        ob, reward, done, info = self.env.step(action)
        return {"image": ob}, reward, done, info


# A basic Gym environment
def env_creator(env_config_dict):
    return gym.make("SpaceInvaders-v0")


# A Gym environment, but with the observation put inside a Dict space.
def env_creator_complex(env_config_dict):
    return GymToDict(wrap_deepmind(gym.make("SpaceInvaders-v0")))


# Register environments
register_env("CustomEnv", env_creator)
register_env("CustomEnvComplex", env_creator_complex)


# Basic ray config
ray.init(local_mode=True)
config = a2c.A2C_DEFAULT_CONFIG.copy()
trainer = a2c.A2CTrainer
config["num_workers"] = 1


# This works:
config["env"] = "CustomEnv"
config["framework"] = "tf"
config["model"] = {
    "conv_filters": [[16, [8, 8], 4], [32, [4, 4], 2], [256, [11, 11], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})


# This also works:
config["env"] = "CustomEnvComplex"
config["framework"] = "tf"
config["model"] = {
    "conv_filters": [[16, [8, 8], 4], [32, [4, 4], 2], [256, [11, 11], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})


# This does NOT work:
config["env"] = "CustomEnv"
config["framework"] = "tf"
config["model"] = {
    "conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})


# This also does NOT work:
config["env"] = "CustomEnvComplex"
config["framework"] = "tf"
config["model"] = {
    "conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})


# For torch, a basic obs space doesn't work either
config["env"] = "CustomEnv"
config["framework"] = "torch"
config["model"] = {
    "conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})


# But a complex input net does seem to work for torch! (Only lightly tested that it doesn't crash though.)
config["env"] = "CustomEnvComplex"
config["framework"] = "torch"
config["model"] = {
    "conv_filters": [[32, [8, 8], 4], [64, [4, 4], 2], [64, [3, 3], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})
```

### Anything else

I would be happy to work on a PR, but would need some guidance especially regarding what the intended behaviour of the value output is.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@avnishn do you mind clarifying what is the expected value output is?

**Comment by mgerstgrasser** [comment]
@avnishn I think the issue is that the final convolutional layer is not flattened even if there is a FC stack following it. I'm not sure if that's intentional or an oversight. If the final CNN layer is flattened, the nature CNN architecture works as intended.

I've submitted a draft PR here: #22137 
That draft PR fixes the Tensorflow version. I haven't touched the Torch version yet. Let me know if flattening the final CNN layer is the right thing to do, and I can do that in the Torch version too and finalise the PR.

**Comment by avnishn** [comment]
Thanks I will take a look!

**Comment by mgerstgrasser** [comment]
@avnishn Tanks! I also was looking into the Torch version today and just pushed a commit that should fix that one too. I think the Torch version was actually broken even with a 1x1 final convolutional layer if there was also a post-fc-stack, and if `vf_share_layers` was set to `True`. The value output layer in that case was expecting an input of size equal to the number of channels in the final convolutional layer, but it actually got an input of size equal to the number of nodes in the final FC layer. So the code below crashes on the master branch (with the same setup as the code snippet in the first post). My PR also fixes that.

I haven't tested yet what happens if `vf_share_layers` is set to `False`. I'd be happy to look into that too, but just want to check first that I'm going in the right direction here. 

```
# This does not work, even though the final convolutional layer has 1x1 output:
config["env"] = "CustomEnv"
config["framework"] = "torch"
config["model"] = {
    "conv_filters": [[16, [8, 8], 4], [32, [4, 4], 2], [256, [11, 11], 1]],
    "post_fcnet_hiddens": [
        512,
    ],
}
tune.run(trainer, config=config, stop={"timesteps_total": 1000})
```

**Comment by avnishn** [comment]
going to close this as this is a stale issue and we're moving over to the new RLModules API
