### ISSUE TITLE
Tutorial/example03 task_timeline() call throwing js errors and not loading.

### ISSUE THREAD

**Issue by jerry-pca** [ray-project/ray#2175]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.4 (17E199)
- **Ray installed from (source or binary)**: Binary "pip install ray"
- **Ray version**: 0.4.0
- **Python version**:  3.6.3
- **Exact command to reproduce**: Run tutorial example 3. Click "View task timeline". Note errors in js console. 

### Describe the problem

I am attempting to run the task timeline ui inside tutorial/exercises/exercise03.ipynb. When I run it, I'm getting post-message errors in js console, and the task timeline does not load. Is this a bug or should I be doing something to make the ui work?

### Source code / logs
![screen shot 2018-05-31 at 11 43 22 pm](https://user-images.githubusercontent.com/39196757/40825678-420618f0-652d-11e8-825e-07f0f308fc6b.png)

Text paste of screenshot:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('null').
inpage.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
i._write @ VM95 inpage.js:1
contentscript.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
c._write @ VM91 contentscript.js:1
VM95 inpage.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
i._write @ VM95 inpage.js:1
VM91 contentscript.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
c._write @ VM91 contentscript.js:1
VM489 inpage.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
i._write @ VM489 inpage.js:1
i @ VM489 inpage.js:1
(anonymous) @ VM489 inpage.js:1
1../lib/auto-reload.js @ VM489 inpage.js:1
o @ VM489 inpage.js:1
t @ VM489 inpage.js:1
(anonymous) @ VM489 inpage.js:1
(anonymous) @ VM473 contentscript.js:1
(anonymous) @ VM473 contentscript.js:1
1../lib/port-stream.js @ VM473 contentscript.js:1
b @ VM473 contentscript.js:1
l @ VM473 contentscript.js:1
(anonymous) @ VM473 contentscript.js:1
VM473 contentscript.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
c._write @ VM473 contentscript.js:1
c @ VM473 contentscript.js:1
(anonymous) @ VM473 contentscript.js:1
(anonymous) @ VM473 contentscript.js:1
1../lib/port-stream.js @ VM473 contentscript.js:1
b @ VM473 contentscript.js:1
l @ VM473 contentscript.js:1
(anonymous) @ VM473 contentscript.js:1
inpage.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
i._write @ inpage.js:1
i @ inpage.js:1
(anonymous) @ inpage.js:1
1../lib/auto-reload.js @ inpage.js:1
o @ inpage.js:1
t @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ contentscript.js:1
(anonymous) @ contentscript.js:1
1../lib/port-stream.js @ contentscript.js:1
b @ contentscript.js:1
l @ contentscript.js:1
(anonymous) @ contentscript.js:1
contentscript.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
c._write @ contentscript.js:1
c @ contentscript.js:1
(anonymous) @ contentscript.js:1
(anonymous) @ contentscript.js:1
1../lib/port-stream.js @ contentscript.js:1
b @ contentscript.js:1
l @ contentscript.js:1
(anonymous) @ contentscript.js:1
main.min.js:24059 Loading extension: jupyter-js-widgets/extension
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M67, around May 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
:8888/files/tmp55te3pux.html:101 Uncaught ReferenceError: Polymer is not defined
main.min.js:36745 Kernel: kernel_connected (e75a35ac-2c5f-4005-835b-06e6ad5af267)
main.min.js:36745 Kernel: kernel_ready (e75a35ac-2c5f-4005-835b-06e6ad5af267)
tmp81q4uch4.html:101 Uncaught ReferenceError: Polymer is not defined
    at HTMLDocument.<anonymous> (tmp81q4uch4.html:101)
tmp6iq2efyg.html:101 Uncaught ReferenceError: Polymer is not defined
    at HTMLDocument.<anonymous> (tmp6iq2efyg.html:101)
(anonymous) @ tmp6iq2efyg.html:101
notebook.js:1057 Notebook.move_cell_up is deprecated as of v4.1 and will be removed in v5.0
Notebook.move_cell_up @ notebook.js:1057
handler @ actions.js:475
final_actions.(anonymous function).handler @ actions.js:890
ActionHandler.call @ actions.js:992
fun @ toolbar.js:111
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
tmp6iq2efyg.html:101 Uncaught ReferenceError: Polymer is not defined
    at HTMLDocument.<anonymous> (tmp6iq2efyg.html:101)
(anonymous) @ tmp6iq2efyg.html:101

**Comment by robertnishihara** [comment]
The timeline only works in Chrome, could that be the issue?

**Comment by jerry-pca** [comment]
Apologies for the delay. @robertnishihara this issue occurs for me on chrome. Rough guess is It that that an iframe or a js lib is not loading, but it wasn't obvious to me if it was a mis config on my end or a bug.

**Comment by robertnishihara** [comment]
I haven't seen this before, so I'm not totally sure. Can you check `jupyter --version` and `python -c 'import ipywidgets; print(ipywidgets.__version__)'`. However, I don't think either of those are the issue.
