### ISSUE TITLE
Implement memory protection for GCS

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#21769]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

With GCS pubsub and KV, GCS itself now has increased chances of using too much memory. We need to implement some protections against OOM in GCS. Some ideas:
0. Allow configurable memory threshold for pubsub and KV combined.
1. When past the threshold, drop non-essential pubsub messages, e.g. logs, error info.
2. When past the threshold, fail operations that insert into the KV.

The memory threshold might be deducible from container limit.

For simplicity, we can start with a low hard coded limit for pubsub messages, e.g. 10MB for logs and error info.

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
cc @ericl @iycheng

**Comment by rkooo567** [comment]
Theoretically it shouldn’t use more memory than redis + gcs service combined from before?

**Comment by mwtian** [comment]
@rkooo567 I agree. GCS pubsub and KV shouldn't be a big regression in OOM protection. But there should be an opportunity for enhancement.

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/22339
