### ISSUE TITLE
[Core][Bug]  gRPC poller error message showed up in the logs

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#21781]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Our user is experiencing following errors in the worker log related grpc. 
```
([...] pid=15697, ip=10.120.158.253) E1129 03:37:56.802084512   18007 backup_poller.cc:134]       Run client channel backup poller: {"created":"@1638157076.802038566","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":320,"referenced_errors":[{"created":"@1638157076.802034167","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":950,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
([...] pid=58163, ip=10.123.160.166) E1129 03:37:56.747796001   60484 backup_poller.cc:134]       Run client channel backup poller: {"created":"@1638157076.747742130","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":320,"referenced_errors":[{"created":"@1638157076.747735658","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":950,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
```
more context https://anyscaleteam.slack.com/archives/C027L220V0V/p1638157108298400

### Versions / Dependencies

latest ray

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
I don't have much context here yet. The next step seems to be to find a repro. cc @rkooo567

**Comment by rkooo567** [comment]
I followed up with the user for repro, but I think it is not easy to obtain it unfortunately.. :(.

Two things we know is that 1. this is from Python worker code. 2. The error seems to appear if we access the closed fd

**Comment by mpgussert** [comment]
I think i see this too, or similar

`E0322 16:30:03.442713753    7520 backup_poller.cc:134]       Run client channel backup poller: {"created":"@1647966603.442613274","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":320,"referenced_errors":[{"created":"@1647966603.442608683","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":950,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}`

what exactly is going on here?  I'm not familiar with the intimate details of Ray and rllib yet

**Comment by ZaberKo** [comment]
I believe I have the similar issue on a docker container. The warning pops up at every `trainer.train()` step
```
E0402 17:39:02.274615934 3860901 backup_poller.cc:134]       Run client channel backup poller: {"created":"@1648921142.274527595","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":320,"referenced_errors":[{"created":"@1648921142.274524502","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":950,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
```
And the wired thing is that the same code (with same version of `ray`) works fine on a bare metal machine.

**Comment by rkooo567** [comment]
Hey @ZaberKo Is it possible to share your script + docker container config? I wonder if we can try reproducing the issue. 

Also, cc @mwtian for this question -> `I want to know whether it affects my training results, or it is just some trivial warning?`

**Comment by mwtian** [comment]
I believe this warning should not affect the results.

**Comment by ZaberKo** [comment]
Update: After upgrading to ray 1.11.0, the warning does not pop any more.

**Comment by troymyname** [comment]
Was anyone able to confirm that the issue is related to anything lower than Ray v1.11.0? What is the root-cause of the issue?

**Comment by troymyname** [comment]
@scv119 I am not sure why this issue was closed without properly understanding the root-cause. Do we know what is different in different versions of ray that led to this issue going away?

**Comment by sarahperrin** [comment]
I'm experimenting a similar issue with Ray v.1.13.0.
On my local computer, everything is working correctly but when executing my code which uses trainer.train() on a cluster (with slurm), the training takes more and more time at each iteration and I get this kind of message at some iterations:

E0402 17:39:02.274615934 3860901 backup_poller.cc:134]       Run client channel backup poller: {"created":"@1648921142.274527595","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":320,"referenced_errors":[{"created":"@1648921142.274524502","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":950,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
