### ISSUE TITLE
[Feature] Create and publish in pypi a wheel for linux arm64

### ISSUE THREAD

**Issue by azisi** [ray-project/ray#21786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Create and publish in pypi a wheel for linux arm64, so that i can pip install ray inside a docker container running in docker for mac in apple silicon/m1.

### Use case

Able to pip install ray inside a docker container running in docker for mac in apple silicon/m1.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MarvinSt** [comment]
would love to see this as well!

**Comment by billadam28** [comment]
I would love to see this as well!!

**Comment by ddelange** [comment]
duplicate of #12128

**Comment by aviau** [comment]
We would love to see this.

**Comment by baswelsh** [comment]
VERY interested in this.  Without it, we are unable to use Ray from a Docker container running on ARM (Apple Silicon).  We instead need to run our containers as x86 which is very slow on the M1s.

**Comment by etorhub** [comment]
Indeed, this would save our lives. Very interested on this.

**Comment by ddelange** [comment]
> Indeed, this would save our lives. Very interested on this.

xref https://github.com/ray-project/ray/issues/12128#issuecomment-1163980281

**Comment by ezorita** [comment]
+1

**Comment by infherny** [comment]
+1

**Comment by rsantanna** [comment]
+1

**Comment by mattip** [comment]
This is different from #12128, which is specific to raspberry pi wheels. Those are difficult to publish since they are not supported on PyPI.

**Comment by mattip** [comment]
Duplicate of #13780. Closing. Please comment on the other issue, or reopen this with an explanation of why this is different.

**Comment by pcmoritz** [comment]
We now have nightly wheels https://github.com/ray-project/ray/pull/31522 and for future releases we will also push those to pypi (possibly retroactively for Ray 2.2 if there is sufficient interest).

**Comment by krfricke** [comment]
I've just uploaded 2.2.0 ARM wheels to PyPI, so `pip install ray` will now work
