### ISSUE TITLE
[Bug] Shutdown check failure after gRPC based pubsub is enabled. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21789]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

cc @mwtian 

Update this patch (https://github.com/ray-project/ray/pull/21787) (adds a little delay to the function).

And then run `pytest -vs python/ray/tests/test_placement_group_mini_integration.py::test_placement_group_remove_stress`.

This will generate lots of 
<img width="1741" alt="Screen Shot 2022-01-21 at 2 41 34 PM" src="https://user-images.githubusercontent.com/18510752/150610132-e511d3a0-f44f-4108-b146-db248cef0008.png">

### Versions / Dependencies

Master

### Reproduction script

Read the main description 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
cc @mwtian This is the shutdown bug I mentioned. I think java shutdown error seems to be resolved after my PR, but I will keep you updated

**Comment by ericl** [comment]
@mwtian is this still an issue now?
