### ISSUE TITLE
[Bug] placement_group not fulfilled in FIFO order

### ISSUE THREAD

**Issue by Michaelvll** [ray-project/ray#21797]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Multiple placement_group's with the same resource requirement are not fulfilled in a FIFO order.

### Versions / Dependencies

* ray==1.9.2
* python==3.6.9
* OS: Ubuntu 18.04

### Reproduction script

To reproduce, please run the following code on a 1 GPU machine.
```python
import time

import ray
import ray.util as ray_util

ray.init('auto', namespace='test', log_to_driver=True)

@ray.remote
def create_placement_group(name):
    pg = ray_util.placement_group([{
        'CPU': 1,
        'GPU': 1,
    }])
    ray.get(pg.ready())
    print(f'{name} ready')
    time.sleep(5)
    ray_util.remove_placement_group(pg)
    print(f"removed pg {name}")

actors = []
for i in range(3):
    actors.append(create_placement_group.remote(f'pg{i}'))
    time.sleep(1)

ray.get(actors)
```

The expected output is the following:
```bash
pg0 pg ready
removed pg pg0
pg1 pg ready
removed pg pg1
pg2 pg ready
removed pg pg2
```

However, the actual behavior is that the pg2 will be fulfilled first, leading to the following output:
```bash
pg0 pg ready
removed pg pg0
pg2 pg ready
removed pg pg2
pg1 pg ready
removed pg pg1
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I think it makes sense to reserve fifo for pgs that have the same resource requirements. Would you like to create a PR for this?

**Comment by rkooo567** [comment]
Right now, we queue pg to the back of the queue if resources are not satisfiable (with retry delay). Maybe we can do this behavior per same key (same resource reqs with strategy).

**Comment by Michaelvll** [comment]
Thank you for the reply! Yes, I can submit a PR, but could you please point me to the current code for scheduling?

Also, I was wondering if we can keep the fifo order not only for pg that has exact same resource requirement but also, more generally, keep it whenever it is possible to do so.

For example, on a 2gpu machine, pg1 requires 1gpu, pg2 reuiqres 1, pg3 requires 2gpu, pg4 requires 1gpu, we also want that pg3 is fulfilled before pg4 if pg1 and pg2 release the resources within a given time gap. Otherwise, pg3 will always be fulfilled after all the 1gpu pgs finish (when there are a lot of 1gpu pgs, this can cause trouble never executing pg3).

**Comment by rkooo567** [comment]
My concern is if we keep FIFO for all resource requests, it can cause unexpected behaviors (head of line blocking). For example;

node A
{CPU: 4}

pg1
{CPU: 2}
pg 2
{CPU:3}
pg 3 
{CPU:2}

In this case, pg 3 will not be scheduled although you have 2 available CPUs. For user perspective this will look like some sort of scheduling bug since {CPU:2} pg cannot be scheduled although there are 2 CPUs. If we are keeping the order only within the same resource key (bundle shape + strategy), we wouldn't have this issue.

What's the use case of reserving FIFO order here? Isn't this something that can be handled by application level? 

Most of queueing code is within `gcs_placement_group_manager.cc`. We can also have a sync up if you'd like to learn this codebase!

**Comment by Michaelvll** [comment]
>  pg 3 will not be scheduled although you have 2 available CPUs

In my perspective, this problem can be solved by timeout. We wait for a few seconds `t` for pg 2, and if it failed to get the resources, we move on to the next pg. The `t` can be gradually increased when the number of failures increases for pg 2.

> What's the use case of reserving FIFO order here? Isn't this something that can be handled by application level?

It is actually a problem for the `ray job`. After I submit multiple jobs, the job that requires more resources will never finish as long as there are more tasks that request fewer resources, which is also quite surprising to the user, but yeah, as you said that might be more about application-level scheduling. 

> Most of queueing code is within `gcs_placement_group_manager.cc`. We can also have a sync up if you'd like to learn this codebase!

Sorry, I am pretty busy by the end of Jan. I would be very happy to chat in early February.
