### ISSUE TITLE
[Docs] RLlib: Reduce usage of long config lists 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#21835]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Many places in the RLlib docs rely on "config dumps" like [here](https://docs.ray.io/en/latest/rllib-training.html#common-parameters) and [here](https://docs.ray.io/en/latest/rllib-algorithms.html). Given the current API, the content itself has to be presented somehow. But commented long lists are not the way. We need to do a better job of explaining what to use when, what side effects changing things might have, and generally how configuration settings interact.

Can we group common configuration into categories? Or can we explain what can be configured in principle and defer the actual lists of config options into a reference? For instance, the (in principle very good) page on algorithms might actually be better placed under _API reference_, the way it is presented (pure info). As a pure reference it is great, as learning material it's not.

Of course, there's an underlying API component to all of this that needs to be solved eventually. For now, we need to see that our Training API makes sense to new-ish users.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
@avnishn please make sure you fully understand the task at hand before implementing/addressing this! Feel free to ping Max with questions.
