### ISSUE TITLE
[Docs] Data: Introduce "Key Concepts" page 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#21837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

For consistency, have the same key concepts page like most other Ray libs. Explain what I have to know to use Ray Data? Which concepts do I need to understand, which abstractions to dig to get started with the project?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maxpumperla** [comment]
@ericl I'm taking this one

**Comment by zhe-thoughts** [comment]
@clarkzinzow @maxpumperla @jianoaix : Is this already done? Thanks

**Comment by clarkzinzow** [comment]
@zhe-thoughts Yes this is done.
