### ISSUE TITLE
[Docs] Data: Create User Guides and Examples

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#21838]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Same as e.g. with Train, we don't really have good / any examples demonstrating a) how to do concrete tasks or b) how to tackle a somewhat realistic use case. Aim to have at least 3 of each to start with. Take [Ray Core](https://docs.ray.io/en/latest/auto_examples/overview.html) as a role model for now. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maxpumperla** [comment]
Follow [Tune User Guides](https://docs.ray.io/en/master/tune/tutorials/overview.html) and [Tune Examples](https://docs.ray.io/en/master/tune/examples/index.html) to get an idea of what we're aiming for.

In particular, identify useful topics for how-to guides first, and think about actionable examples that users care about.

**Comment by zhe-thoughts** [comment]
@maxpumperla @clarkzinzow If this task is finished, please close the issue. Thanks!
