### ISSUE TITLE
[Bug] many_tasks_serialized_ids is broken in the master

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21858]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

After we started long running tests every day, it seems like this fails every day; 

<img width="1466" alt="Screen Shot 2022-01-25 at 6 25 52 AM" src="https://user-images.githubusercontent.com/18510752/150995049-51de33fd-d8d6-47f8-a5c9-ef53740823fd.png">

### Versions / Dependencies

Master

### Reproduction script

Run many_tasks_serialized_ids

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jjyao** [comment]
The correct behavior of this test should be running for 1d and timed out (this timeout is expected since it's a infinite long running test). For the failed tests, they did successfully run for 1d and timed out. So it's the infra error after timeout caused the test to fail.

**Comment by jjyao** [comment]
It's `[INFO 2022-01-28 10:14:24,831] e2e.py: 399  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/aswgiavyxx --acl bucket-owner-full-control with {} via ray job submit` failed with `requests.exceptions.HTTPError: 502 Server Error: Bad Gateway`
