### ISSUE TITLE
[Feature] Set publisher for logs on ray init (to use in LogMonitor)

### ISSUE THREAD

**Issue by vsergeyev** [ray-project/ray#21857]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Hi,

Currently `LogMonitor` has a good feature to publish logs into Redis or GCS.
We using Ray (with Python) for workflows and one possible limitation of current approach is 0 TTL of Redis pubsub.

Is it a chance it could be introduced a param for ray.init() to specify user-defined class of `LogMonitor`'s `publisher`?
Should I fork repo and provide implementation?

Thank you,
V.

### Use case

 * run ray workflow
 * subscribe (pubsub) for logs and have a TTL for them
 * not depend on logs on FS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
@vsergeyev  thanks for providing the information!

I'd like to get a better understanding of your use case. What you'd like is to push all logs to someplace and collect them there right?

Also what kind of logs do you need? For example, do you only need application-level logs? Or do you also need library-level logs (workflow)? Or do you even need system-level logs (ray logs)?

**Comment by vsergeyev** [comment]
Hello @iycheng !

 * plan is to use Ray for workflows related to quantum-enabled application
 * we would like to collect both system and workflow logs
 * one of architecture idea we have - to build own service to provide a "Historical logs" feature

### Getting historical logs

How do we get historical logs if we didn't subscribed to pubsub at time these logs appeared?

In a cluster environment how all logs from worker nodes organized? Is it true, that with `LOG TO DRIVER`
these logs redirected to HEAD node?

Thank you for sharing any details or future plans!
