### ISSUE TITLE
[Bug] [CPP API]Failed when Passing object refs to remote functions

### ISSUE THREAD

**Issue by hero-tugang** [ray-project/ray#21856]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

It works when the object ref returned by remote function call.
then it fails when the object ref returned by put.

test code as:
-------------------
/// put and get object
  auto object = ray::Put(100);
  auto put_get_result = *(ray::Get(object));
  std::cout << "put_get_result = " << put_get_result << std::endl;

  /// common task
  auto task_object = ray::Task(Plus).Remote(1, 1);
  int task_result = *(ray::Get(task_object));
  std::cout << "task_result = " << task_result << std::endl;
  
  auto task_object2 = ray::Task(Plus).Remote(task_object, 1);
  std::cout << "task_result2 = " << *task_object2.Get() << std::endl;
  
  auto task_object3 = ray::Task(Plus).Remote(task_object2, 1);
  std::cout << "task_result3 = " << *task_object3.Get() << std::endl;
  
  auto task_object4 = ray::Task(Plus).Remote(object, 1);
  std::cout << "task_object4 = " << *task_object4.Get() << std::endl;

-------------------

result and error info as follow:
-------------------

put_get_result = 100
task_result = 2
task_result2 = 3
task_result3 = 4
[2022-01-25 16:34:55,167 C 12612 13039] core_worker.cc:760:  Check failed: _s.ok() Bad status: IOError: Broken pipe
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    std::_Function_handler<>::_M_invoke()
    ray::core::ObjectRecoveryManager::ReconstructObject()
    std::_Function_handler<>::_M_invoke()
    ray::core::ObjectRecoveryManager::RecoverObject()
    ray::core::CoreWorker::OnNodeRemoved()
    ray::gcs::NodeInfoAccessor::HandleNotification()
    std::_Function_handler<>::_M_invoke()
    ray::gcs::GcsPubSub::ExecuteCommandIfPossible()::{lambda()#1}::operator()()
    std::_Function_handler<>::_M_invoke()
    std::_Function_handler<>::_M_invoke()
    boost::asio::detail::completion_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    ray::core::CoreWorker::RunIOService()
    execute_native_thread_routine

-------------------

### Versions / Dependencies

ray, version 1.9.2
gcc version 9.3.0 

### Reproduction script

i compiled test code with following cmd:

g++ --std=c++17 -g example.cc -l ray_api -D_GLIBCXX_USE_CXX11_ABI=0 -I /usr/local/python3/lib/python3.9/site-packages/ray/cpp/include  -L /usr/local/python3/lib/python3.9/site-packages/ray/cpp/lib -o example
g++ --std=c++17 -fPIC -shared -g example.cc -l ray_api -D_GLIBCXX_USE_CXX11_ABI=0 -I /usr/local/python3/lib/python3.9/site-packages/ray/cpp/include  -L /usr/local/python3/lib/python3.9/site-packages/ray/cpp/lib -o example.so

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SongGuyang** [comment]
@qicosmos Any thought?

**Comment by jon-chuang** [comment]
This is a known issue fixed by https://github.com/ray-project/ray/pull/21236

**Comment by SongGuyang** [comment]
> This is a known issue fixed by #21236

Nice! @hero-tugang maybe you can download the latest wheels and retry. https://docs.ray.io/en/latest/installation.html#daily-releases-nightlies

Note, you should download two wheels: ray and ray-cpp. You can get the ray-cpp wheel download address easily from ray wheel download address. Just replace "ray-2.0.0" to "ray_cpp-2.0.0" in the download url.

**Comment by hero-tugang** [comment]
ok，l'll try. thx

**Comment by hero-tugang** [comment]
it works.
