### ISSUE TITLE
[RFC] Deprecate local mode

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#21850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Since we have debugging tool for a cluster, I think there's no need for having local mode any longer. 
Local mode increases redundancy and complexity of our code path.

I'm not sure if it's possible to remove local mode in Ray2.0 , but at least for Java, I believe we should remove them.
Or we can create a vote request for OOS to see if it's anyone has been using it.

@ericl @kfstorm 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Yeah I think I agree here. There are also better ways to implement local mode, such as running all tasks in the same worker process, which are both higher fidelity and equivalent in debuggability.

Ideally we'd have a replacement to recommend, though I think the usage of local mode is low enough to remove, especially given we have a distributed debugger too.

**Comment by kfstorm** [comment]
@ericl Is the distributed debugger widely used by Ray users? Do you think it's possible to make the debugger available for other front-end languages?

**Comment by ericl** [comment]
It's been used by large scale Python users. I don't think it would work in other languages though.

**Comment by jovany-wang** [comment]
Why not request a vote in community to see how many people use it?

**Comment by jovany-wang** [comment]
Also I don't think it's easy to support the debug tool for Java in a short time.
