### ISSUE TITLE
Build failure (from source) fatal error: local_scheduler/format/local_scheduler_generated.h: No such file or directory

### ISSUE THREAD

**Issue by ejxqy** [ray-project/ray#2185]
### System information
- **Linux Ubuntu 18.04**:
- **Ray installed from source**:
- **Latest version from git (commit-id: 19d6ca0670bac9d9c7fdda3060e6f92705b04263)**:
- **Python version 3.6.5**:
- **Exact command to reproduce "python setup.py install"**:

### Describe the problem

Build fails with the error "local_scheduler_generated.h: No such file or directory"

### Source code / logs

[ 44%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/node_manager.cc.o
**/home/js/ray/src/ray/raylet/node_manager.cc:4:10: fatal error: local_scheduler/format/local_scheduler_generated.h: No such file or directory**
 #include "local_scheduler/format/local_scheduler_generated.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/ray/CMakeFiles/ray_objlib.dir/build.make:413: recipe for target 'src/ray/CMakeFiles/ray_objlib.dir/raylet/node_manager.cc.o' failed
make[2]: *** [src/ray/CMakeFiles/ray_objlib.dir/raylet/node_manager.cc.o] Error 1
CMakeFiles/Makefile2:331: recipe for target 'src/ray/CMakeFiles/ray_objlib.dir/all' failed
make[1]: *** [src/ray/CMakeFiles/ray_objlib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

[error.log](https://github.com/ray-project/ray/files/2066701/error.log)

**Comment by robertnishihara** [comment]
Can you try cloning a fresh copy of the Ray repository and building it again (and if it fails, share the full stdout/stderr)?

It looks like the error happened earlier than what is recorded in the log.

**Comment by ejxqy** [comment]
Using the following comands 
_git clone https://github.com/ray-project/ray.git
cd ray/python
pip install -e . --verbose_

And got the following error:
**Command "/home/js/anaconda3/bin/python -c "import setuptools, tokenize;__file__='/home/js/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/js/ray/python/**

The full error log is 
[error.log](https://github.com/ray-project/ray/files/2074691/error.log)

**Comment by robertnishihara** [comment]
It's possible that this has been fixed by https://github.com/ray-project/ray/pull/2221.

Can you try removing the whole directory and trying again with the latest source?

You can also install Ray with `pip install ray` and if you want to try out the latest commits you can get install the nightly versions using the instructions at http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray.

**Comment by guoyuhong** [comment]
@robertnishihara I think this is the same issue in [2271](https://github.com/ray-project/ray/pull/2271).

**Comment by robertnishihara** [comment]
Thanks @ejxqy. Please try with the latest master and let me know if the issue persists.

**Comment by simon-mo** [comment]
Should be fixed on latest master.
