### ISSUE TITLE
[Bug] ray.remote is incompatible with classmethods

### ISSUE THREAD

**Issue by brandondube** [ray-project/ray#21868]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

A particular design for a program would be to have a class `__init__` which does nothing more (or almost nothing more) than attach some attributes to an instance.  Initializations requiring larger amounts of computation might be confined to a class method which prepares the inputs for `__init__`, aka the factory pattern.  A MWE that doesn't actually do any computations inside the factory method looks like

```python
class Foo:
    def __init__(self, x):
        self.x = x

    @classmethod
    def factory_f(cls, x):
        return cls(x)
```

If you try to use this with ray, it seems the remote decorator breaks `@classmethod`:

```python
ray.init()

ray_f = ray.remote(Foo)
ray_f.factory_f(1)
```
produces:
```
Traceback (most recent call last):
  File "/Users/bdube/source/lowfssim/lowfsc/testray.py", line 33, in <module>
    ray_f.factory_f(1)
  File "/Users/bdube/source/lowfssim/lowfsc/testray.py", line 11, in factory_f
    return cls(x)
TypeError: __init__() missing 2 required positional arguments: 'bases' and 'attr'
```

Precisely the same behavior occurs decorating the class at its definition, instead of after-the-fact, and if the class is defined after `ray.init`. 

I expected the code to do the ray equivalent of `f = Foo.factory_f(1)`, i.e. produce an instance of the class, with `f.x = 1` (modulo it being an actor, so I would get an ID instead of a PyObject).

It's possible I am attempting to do the wrong thing, and I should instead make my classes normally and go through their attributes after the fact and recursively `put` each ndarray.  The basic thing I am trying to do is avoid copying as much as possible, and have all the background state (that does not change) for my program exist inside the plasma storage.

### Versions / Dependencies

```
Ray 1.9.2
MacOS Big Sur, CentOS Linux release 7.8.2003, Ubuntu 20.04.3 LTS
Python 3.8.3, 3.8.9, 3.9.6
```

### Reproduction script

see what happened

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
Assigned to myself. Sorry for the mis-click. I will try to reproduce this issue on my machine.

**Comment by pcmoritz** [comment]
This should now be fixed with https://github.com/ray-project/ray/pull/22113 :)

**Comment by fuhuifang** [comment]
I need to decorate the class at its definition:
```python
@ray.remote
class Foo:
    def __init__(self, x):
        self.x = x
        print(self.x)

    @classmethod
    def factory_f(cls, x):
        return cls(x)
ray.init()  
ray.get(Foo.factory_f.remote(1))
```
and I'm getting
```
AttributeError: 'function' object has no attribute 'remote'
```
I'm using Ray 1.12.0. Any suggestions to fix this? Thanks!

**Comment by Kyrish** [comment]
> I need to decorate the class at its definition:
> 
> ```python
> @ray.remote
> class Foo:
>     def __init__(self, x):
>         self.x = x
>         print(self.x)
> 
>     @classmethod
>     def factory_f(cls, x):
>         return cls(x)
> ray.init()  
> ray.get(Foo.factory_f.remote(1))
> ```
> 
> and I'm getting
> 
> ```
> AttributeError: 'function' object has no attribute 'remote'
> ```
> 
> I'm using Ray 1.12.0. Any suggestions to fix this? Thanks!

I got precisely the same issue. "remote" decorator doesn't work with a "@classmethod".
