### ISSUE TITLE
[1.11 Release] `ray_lightning_user_test_master` failing

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#21871]
https://buildkite.com/ray-project/periodic-ci/builds/2503#9310e89c-7bf5-4374-a7d1-311dd3834663/6-344

But `ray_lightning_user_test_latest` is passing.
cc @xwjiang2010 @amogkam

**Comment by xwjiang2010** [comment]
@amogkam This is a different error signature but still the same "ray_lightning_user_test_master" test failing. 

@amogkam @matthewdeng thoughts?

**Comment by xwjiang2010** [comment]
@amogkam assigning this to you as you are already looking at it. Seems we can also drop release-blocker here?

**Comment by mwtian** [comment]
Sounds good, will drop the release blocker and close this issue since it is a duplicate to #21863.
