### ISSUE TITLE
[Bug] `ray.tune.integration.pytorch_lightning.TuneReportCallback` has an AttributeError

### ISSUE THREAD

**Issue by LiamMa** [ray-project/ray#21891]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

When using `ray.tune.integration.pytorch_lightning.TuneReportCallback` with pytorch_lightning, an error occurs as shown in the following figure:
![Screen Shot 2022-01-26 at 2 03 56 AM](https://user-images.githubusercontent.com/26243079/151125010-1568ec33-83a5-4271-b1ce-7e4744c90b76.png)

The reason is that pytorch_lightning has removed `Trainer.running_sanity_check` and used `Trainer.sanity_checking` instead in version 1.5.0.

### Versions / Dependencies

ray: 1.9.2
pytorch_lightning: 1.5.8

### Reproduction script

This is a small bug when using `ray.tune.integration.pytorch_lightning.TuneReportCallback` with Lightning Module.
It should be simply fixed by changing the naming inside the code.

### Anything else

Alternatively, I fixed it by adding an extra attribute to `trainer` by `trainer.running_sanity_check=trainer.sanity_checking`.
Therefore, it should be only a small naming issue.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Hey @LiamMa! This has been fixed in master and will be included in the Ray 1.11 release!
