### ISSUE TITLE
[Release] `threaded_actors_stress_test` failing on master, 1.10.0 and 1.11.0 release branches

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#21900]
E.g.
1.10.0: https://buildkite.com/ray-project/periodic-ci/builds/2489#fd61e70a-e76d-4a43-9a97-a8671b0b05f9
master: https://buildkite.com/ray-project/periodic-ci/builds/2514#d2044e01-e6b5-423b-ab57-b1d5cd9bb6c1

The failure looks like an infra failure, `Waiting for more nodes to come up: 1/201`. But it is unable to pass after retries, while concurrent tests do not exhibit infra failures. IIUC this test is recently promoted to stable.

cc @jjyao (oncall) @rkooo567 @architkulkarni

**Comment by mwtian** [comment]
On 1.10.0rc0, the test passed on the 11th retry: https://buildkite.com/ray-project/periodic-ci/builds/2193#10cd84f8-4355-49ba-bf24-70d32085747e

**Comment by zhe-thoughts** [comment]
Per Slack discussion, not a blocker for 1.10.0 release

**Comment by jjyao** [comment]
I experienced same issues before, 200 nodes is a lot especially during release period. I'll follow up to see if it's auto scaler issue or product issue.

**Comment by jjyao** [comment]
It's no longer happening.
