### ISSUE TITLE
[autoscaler] Print commands to forward WebUI port to laptop and log into the UI

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2190]
This would be very useful to print after the autoscaler is initialized. At the moment, users have to go to http://ray.readthedocs.io/en/latest/webui.html and fill in the details themselves.

(I just ran into this)

The autoscaler is scaling very nicely for my (task-based) workload 👍

**Comment by richardliaw** [comment]
This should be fixed with #7383
