### ISSUE TITLE
[1.11.0 Release] `serve_failure` failing on master and 1.11.0 branches

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#21918]
E.g.
1.11.0: https://buildkite.com/ray-project/periodic-ci/builds/2524#5e259950-8965-4f40-a39a-bb0f2fbf2c86/138-427
master: https://buildkite.com/ray-project/periodic-ci/builds/2503#69d841c1-1c30-4ea4-8a2e-c586ffe142c8/139-429

I was able to reproduce the issue by starting the test from my laptop. The cluster can be kept open after the failure with `--no-terminate`. e.g. get aws creds, then run
```
ANYSCALE_HOST=https://console.anyscale.com ANYSCALE_CLI_TOKEN=... ANYSCALE_CLOUD_ID=... ANYSCALE_PROJECT=... RAY_WHEELS=... RAY_TEST_REPO=https://github.com/ray-project/ray.git RAY_TEST_BRANCH=... python ray/release/e2e.py --category=... --test-config ray/release/long_running_tests/long_running_tests.yaml --test-name serve_failure --keep-results-dir --smoke-test --no-terminate
```

The failures to reach `/api/version` in the tests are due to dashboard being terminated. I checked the cluster, and `gcs` was also terminated. It looks like the process terminations are not due to any crash. However, because dashboard was terminated, the test cannot submit job and finish successfully.

Assigning to @simon-mo as serve oncall.

**Comment by mwtian** [comment]
Adding @jiaodong as current server oncall.

**Comment by jiaodong** [comment]
I just verified running `serve_failure.py` locally works fine after a few minutes while test runs errored but command history showed "finished" after running for ~1min 30secs. Checking into how `e2e.py` is implemented as the failure happens at that level as mingwei documented:

`

Traceback (most recent call last):
--
  | File "/home/ray/anaconda3/bin/ray", line 8, in <module>
  | sys.exit(main())
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/scripts/scripts.py", line 1960, in main
  | return cli()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1053, in main
  | rv = self.invoke(ctx)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 754, in invoke
  | return __callback(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 808, in wrapper
  | return f(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/cli.py", line 130, in job_submit
  | client = _get_sdk_client(address, create_cluster_if_needed=True)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/cli.py", line 28, in _get_sdk_client
  | return JobSubmissionClient(address, create_cluster_if_needed)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 130, in __init__
  | self._check_connection_and_version()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 141, in _check_connection_and_version
  | r.raise_for_status()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
  | raise HTTPError(http_error_msg, response=self)
  | requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://session-bsvhedc1wfqkzkrhtqy6rp56.i.anyscaleuserdata.com/api/version

`

**Comment by jiaodong** [comment]
cc: @krfricke based on https://sourcegraph.com/github.com/ray-project/ray/-/commit/9352cb781c7acdd1f7d4a0ce3941c351c8bacd21 for context -- what's the reason we included `ray stop` as a prepare command in the first place ? Seems like we're ensuring it to finish before trying to fetch `/tmp/release_test_out.json`, where the fetching command wouldn't work if it's done via job submission.

If the prepare command here means preparing for aggregating results, `ray stop` makes sense to me and i can submit a PR to make the last command `aws s3 cp /tmp/release_test_out.json` not using job submission to resolve this.

**Comment by mwtian** [comment]
Not using job submission would work. Also I just found the reason why dashboard is killed at the end. The `serve_failure` smoke test differs from other smoke tests in exiting just after 1 iteration, instead of running for ~3600s and getting terminated by the e2e.py script. When the `serve_failure.py` script finishes, it tears down the cluster including the dashboard, which stops job submission from working.

The fix would be to not exit early in smoke test mode, and maybe lower the smoke test length. PR is here: https://github.com/ray-project/ray/pull/21925

The reason for why `ray stop` is called to "prepare" the cluster, and why finishing `serve_failure.py` tears down the cluster, is because the script uses `Cluster` from `cluster_util.py`. With `Cluster`, it must start the Ray head node by itself, hence `ray stop` to prepare; and it tears down the Ray cluster when it is gc'ed. It may be migrated to use compute template in future.

**Comment by mwtian** [comment]
Since the issue has been identified to be related to test setup, lowering to P1.

**Comment by jiaodong** [comment]
Thanks Mingwei ! I think we agreed this is a test setup issue and you surfaced issue of our use of cluster_utils. Let me check with the team to see what's our plan on this as the proper setup seems to be use real job submission / services rather than running cluster_utils script on remote cluster, which should be more of a local dev / smoke test setup.

**Comment by mwtian** [comment]
Sounds good Jiao.
