### ISSUE TITLE
Performance regression of `microbenchmark` in 1.10.0 

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#21923]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

See https://github.com/ray-project/ray/pull/21908/, `microbenchmark` has slowed down in Actor method call throughput

----

So this regression is introduced by #20894. more specifically:
prior than #20894 we offload a lot of queuing logic into a different thread, so the worker thread (which submit the task) takes less time to return;
after #20894, we need to do extra work (and synchronization) in the worker thread (who submit the task) to check the queue length before offload the work to a different thread.

looks this change is fundamental for the correctness of the back pressure, and the 11k-12k/s per actor execution speed should be sufficient for our existing use cases, thus we decided unblock the release.

### Versions / Dependencies

1.10.0

### Reproduction script

`microbenchmark`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
Maybe we should add performance metrics in e2e.py tests to prevent regression from happening. Running successfully is the only metric we are monitoring (pass/fail). 

Also when I was doing releasing, in the last step, there is also a regression. I think we do benchmark after cut and identify the big regression as release blockers from the beginning so we'll have plenty of time to fix this.

**Comment by jjyao** [comment]
We have metrics, it's just that we didn't monitor closely. We should just set up auto alerts.

**Comment by mwtian** [comment]
Regressions: https://github.com/ray-project/ray/pull/21908
Suspected culprit (found by @jjyao): https://github.com/ray-project/ray/pull/20894

Regressions exist in 1.11.0 as well:
  1_n_actor_calls_async = [12725.67787708049, 552.0123808253086]
  n_n_actor_calls_async = [37888.75237849107, 987.6635435902489]
vs 1.10.0:
  "1_n_actor_calls_async": [
    11741.041010762125,
    485.03043177404095
  ],
  "n_n_actor_calls_async": [
    37042.17466054547,
    5632.999645469377
  ],

**Comment by scv119** [comment]
So this regression is introduced by #20894. more specifically:
prior than #20894 we offload a lot of queuing logic into a different thread, so the worker thread (which submit the task) takes less time to return;
after #20894, we need to do extra work in the worker thread (who submit the task) to check the queue length before offload the work to a different thread.

looks this change is fundamental for the correctness of the back pressure, and the 11k-12k/s per actor execution speed should be sufficient for our existing use cases, thus we decided unblock the release.
