### ISSUE TITLE
ValueError: Invalid return or yield value. Either return/yield a single number or a dictionary object in your trainable function

### ISSUE THREAD

**Issue by root12321** [ray-project/ray#21926]
ValueError: Invalid return or yield value. Either return/yield a single number or a dictionary object in your trainable function

why this error happen？any one help me ?

**Comment by root12321** [comment]
Traceback (most recent call last):
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(ImplicitFunc pid=117609)     self.run()
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/tune/function_runner.py", line 281, in run
(ImplicitFunc pid=117609)     raise e
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/tune/function_runner.py", line 262, in run
(ImplicitFunc pid=117609)     self._entrypoint()
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/tune/function_runner.py", line 331, in entrypoint
(ImplicitFunc pid=117609)     self._status_reporter.get_checkpoint())
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/util/tracing/tracing_helper.py", line 451, in _resume_span
(ImplicitFunc pid=117609)     return method(self, *_args, **_kwargs)
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/tune/function_runner.py", line 598, in _trainable_func
(ImplicitFunc pid=117609)     handle_output(output)
(ImplicitFunc pid=117609)   File "/home/leinao/anaconda3/envs/yolo_rotate_new/lib/python3.6/site-packages/ray/tune/function_runner.py", line 588, in handle_output
(ImplicitFunc pid=117609)     "Invalid return or yield value. Either return/yield "
(ImplicitFunc pid=117609) ValueError: Invalid return or yield value. Either return/yield a single number or a dictionary object in your trainable function.

**Comment by TM-C** [comment]
I have the same error. I'm following this turorial:

https://towardsdatascience.com/hyperparameter-tuning-with-keras-and-ray-tune-1353e6586fda

using this code:

https://github.com/himanshurawlani/hyper_fcn

Error Message:

Failure # 1 (occurred at 2022-02-09_16-07-50)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 893, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 707, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1733, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train()[39m (pid=643, ip=172.28.0.2, repr=train)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 315, in train
    result = self.step()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 532, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train()[39m (pid=643, ip=172.28.0.2, repr=train)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 262, in run
    self._entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 331, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 601, in _trainable_func
    handle_output(output)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/function_runner.py", line 591, in handle_output
    "Invalid return or yield value. Either return/yield "
ValueError: Invalid return or yield value. Either return/yield a single number or a dictionary object in your trainable function.

Could it be that somehow the code is implemented wrong regarding the output of a generator function?

Any help would be appreciated

**Comment by D-Idan** [comment]
I had the same issue.

** SOLVED ** by deleting the train function return
so now the directed function from the tune.run doesn't return anything.
