### ISSUE TITLE
[Bug] 1.9.0 PlacementGroup scheduling

### ISSUE THREAD

**Issue by kiralaz** [ray-project/ray#21920]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

This is not a contribution.

With the requirement of using PlacementGroup in 1.9.0 for Tune, we’ve noticed that cloud jobs run with custom resources and PlacementGroupFactory() fail to schedule all the actors and just hang indefinitely. Note that it is possible this bug was present before 1.9.0, as we were not using placement groups everywhere before.

 In our logs we see warnings like this

```
2022-01-26 01:00:53,234    WARNING worker.py:1245 -- The actor or task with ID ffffffffffffffffef9a401d7616b4423d86795701000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
Required resources for this actor or task: {CPU_group_9ec05ccf6e0b6dc761548df83a8f300f: 1.000000}, {worker_group_9ec05ccf6e0b6dc761548df83a8f300f: 1.000000}, {memory_group_9ec05ccf6e0b6dc761548df83a8f300f: 61440000.000000 GiB}
Available resources on this node: {30.000000/36.000000 CPU, 2007361660.009766 GiB/2335041660.009766 GiB memory, 1000732139.990234 GiB/1000732139.990234 GiB object_store_memory, 204800000.000000 GiB/327680000.000000 GiB memory_group_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_37_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 bundle_group_41_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_41_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 worker1, 1.000000/1.000000 node:172.29.255.62, 1000.000000/1000.000000 bundle_group_39_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_39_9ec05ccf6e0b6dc761548df83a8f300f, 61440000.000000 GiB/61440000.000000 GiB memory_group_41_9ec05ccf6e0b6dc761548df83a8f300f, 61440000.000000 GiB/61440000.000000 GiB memory_group_37_9ec05ccf6e0b6dc761548df83a8f300f, 0.000000/6.000000 worker_group_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 bundle_group_36_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 bundle_group_40_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 bundle_group_37_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_37_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_38_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_39_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_40_9ec05ccf6e0b6dc761548df83a8f300f, 61440000.000000 GiB/61440000.000000 GiB memory_group_39_9ec05ccf6e0b6dc761548df83a8f300f, 0.000000/6.000000 CPU_group_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_36_9ec05ccf6e0b6dc761548df83a8f300f, 1000.000000/1000.000000 bundle_group_38_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_40_9ec05ccf6e0b6dc761548df83a8f300f, 20480000.000000 GiB/20480000.000000 GiB memory_group_36_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_38_9ec05ccf6e0b6dc761548df83a8f300f, 994.000000/1000.000000 worker, 61440000.000000 GiB/61440000.000000 GiB memory_group_40_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 worker_group_36_9ec05ccf6e0b6dc761548df83a8f300f, 6000.000000/6000.000000 bundle_group_9ec05ccf6e0b6dc761548df83a8f300f, 1.000000/1.000000 CPU_group_41_9ec05ccf6e0b6dc761548df83a8f300f, 61440000.000000 GiB/61440000.000000 GiB memory_group_38_9ec05ccf6e0b6dc761548df83a8f300f}
 In total there are 0 pending tasks and 4 pending actors on this node.
```

### Versions / Dependencies

ray==1.9.0

### Reproduction script

We are able to reproduce this with a cluster consisting of two c5.9xlarge nodes. 

Below we have included a code snippet for pg_bug.py used to reproduce the bug and a description of our cluster setup.
The script is expected to raise the `Exception` very quickly if all actors are scheduled properly. Instead, it hangs indefinitely.

```
# pg_bug.py
import time

import ray
from ray import tune


@ray.remote
class Worker:
    def work(self):
        pass


# Memory specs of two types of workers
mem_per_worker = 400 * 1024**2  # 400 MB
mem_per_hm_worker = 3 * mem_per_worker


class Trainable(tune.Trainable):
    def setup(self, config):
        worker_cls = Worker.options(memory=mem_per_worker, resources={'worker': 1})
        hm_worker_cls = Worker.options(memory=mem_per_hm_worker, resources={'worker': 1})
        self.workers = [worker_cls.remote() for _ in range(config['num_workers'])]
        self.hm_workers = [hm_worker_cls.remote() for _ in range(config['num_hm_workers'])]

    def step(self):
        ray.get([worker.work.remote() for worker in self.hm_workers + self.workers])
        raise Exception("If this exception is raised, scheduling did not hang!")

    @classmethod
    def default_resource_request(cls, config):
        bundles = ([{
            'CPU': 1
        }] + [{
            'CPU': 1,
            'memory': mem_per_worker,
            'worker': 1
        }] * config['num_workers'] + [{
            'CPU': 1,
            'memory': mem_per_hm_worker,
            'worker': 1
        }] * config['num_hm_workers'])
        return tune.PlacementGroupFactory(bundles, strategy='PACK')


if __name__ == "__main__":
    ray.init(address="auto")
    while ray.cluster_resources()['CPU'] < 72:
        time.sleep(5)  # Wait for the other node to come online.
    print("STARTING TEST")
    tune.run(
        Trainable,
        stop={'training_iteration': 1000000},
        config={
            'num_workers': 36,
            'num_hm_workers': 5
        },
    )
```
On the head node, we run
```
ray start --head --num-cpus=`nproc --all` --resources='{"worker": 1000}' && python3 pg_bug.py
```
On the other node, we run
```
ray start --address=$REDIS_SERVER_ADDRESS --num-cpus=`nproc --all` --resources='{"worker": 1000}' 
```
where `REDIS_SERVER_ADDRESS` is set to `<head node hostname>:6379`. We’ve omitted details specific to launching jobs and setting up the cluster on our internal infrastructure, but hopefully the above instructions are sufficient to reproduce the issue.

### Anything else

In this setup, each c5.9xlarge instance has 36 CPUs and 72GB of RAM. Even accounting for object store memory, there should be plenty of resource left in terms of both CPU and memory to run this job. Also note that while the use of custom resource “worker” seems unnecessary in this case, we found it is a necessary part of the reproduction. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Thanks for the report @kiralaz !! We will take a look shortly.

@richardliaw can you guys take a initial look at this (maybe one of oncalls from you guys can take a look)? Just to make sure if there was no mistake in resource configuration or Tune side.

**Comment by rkooo567** [comment]
@kiralaz is it possible to share 

/tmp/ray/session_latest/debug_state.txt (if it is not there, it must be inside /log file) from both raylets?

**Comment by rkooo567** [comment]
> In this setup, each c5.9xlarge instance has 36 CPUs and 72GB of RAM. Even accounting for object store memory, there should be plenty of resource left in terms of both CPU and memory to run this job. Also note that while the use of custom resource “worker” seems unnecessary in this case, we found it is a necessary part of the reproduction.


@kiralaz this is interesting given `worker` is more common resources than cpus or memory (1000 per node)... @scv119 I wonder if this is a custom resource related bug

**Comment by richardliaw** [comment]
The code looks right to me; I wonder if you can inspect where all the actors are going. 

Maybe we can use the new pseudo-multi-node testing stuff for this (cc @krfricke )

**Comment by rkooo567** [comment]
Can you also share the output of ray status when things hang?

**Comment by kiralaz** [comment]
Sure, here's the output from `ray status` on my end
```
$ ray status
======== Autoscaler status: 2022-01-27 16:52:21.209356 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_49fb86a57d5b87c285bdaa6bfdefd4086f807b949ec8f4bc0c29512f
 1 node_16527f5ec08e4623f4d625129df2682cf21567663dc34aff7b3e521d
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 38.0/72.0 CPU (38.0 used of 42.0 reserved in placement groups)
 15.23/82.733 GiB memory (15.23 used of 19.92 GiB reserved in placement groups)
 0.00/38.185 GiB object_store_memory
 37.0/2000.0 worker (37.0 used of 41.0 reserved in placement groups)

Demands:
 {'CPU': 1.0, 'memory': 1258291200.0, 'worker': 1.0}: 4+ pending tasks/actors (4+ using placement groups)
```

**Comment by rkooo567** [comment]
@kiralaz 

In a glance, it looks like you have correct number of resources reserved by pg. If you look at

```
 38.0/72.0 CPU (38.0 used of 42.0 reserved in placement groups)
 15.23/82.733 GiB memory (15.23 used of 19.92 GiB reserved in placement groups)
 0.00/38.185 GiB object_store_memory
 37.0/2000.0 worker (37.0 used of 41.0 reserved in placement groups)
```

it correctly reserved 41 CPUs / workers (which is the sum of  `'num_workers': 36, 'num_hm_workers': 5`).

But for some reasons, you have 4 pending actors that require `{'CPU': 1.0, 'memory': 1258291200.0, 'worker': 1.0}` -> meaning 1 task cannot be scheduled forever.

Do you know what is this 1 additional actor that requires ` 'worker': 1.0`?

**Comment by rkooo567** [comment]
Can you also share the output of `ray.state.actors()`?

**Comment by kiralaz** [comment]
Sorry — not sure I totally follow your question. It looks like it is the `hm_worker` actors that are not being scheduled, right? since the associated `memory` request is 1.2GiB. 

Is it possible that since the hm_worker bundle resource requests are a superset of the other ones, that the `hm_worker` bundles are being filled up with `worker` actors that only require 400MiB of memory and thus there are no remaining bundles left that can be used to schedule `hm_worker` actors?

**Comment by rkooo567** [comment]
Sorry I think I misread some values last time I checked it...

I think your theory could make sense. I am not very familiar with Tune, but if this is the case, scheduling hm_workers on hm_worker bundles could solve the issue? @richardliaw is this possible?

**Comment by soundway** [comment]
I think we'll have to create a custom resource `hm_worker`, and then use them instead for hm_workers exclusively so workers will not be scheduled on the hm_worker bundles.

So basically, with PG, if any actor's resource requirement is a subset of another, then we'll run the risk of scheduling failures unless we create actors in a very specific order (in this case if we create hm_worker first then things should work). While I understand that users could also get around this with adding unique custom resource for each type of actors and that there's probably not an easy way on the developer's end to fix it, this behavior is not immediately intuitive, and it creates a problem that doesn't exist when PG is not used. A more informative error message could be useful here.

**Comment by richardliaw** [comment]
> Is it possible that since the hm_worker bundle resource requests are a superset of the other ones, that the hm_worker bundles are being filled up with worker actors that only require 400MiB of memory and thus there are no remaining bundles left that can be used to schedule hm_worker actors?

Seems like a fair theory.

A couple workarounds if this theory is correct, in addition to custom resources (which is not a nice workaround I see):

1. Place the hm_workers first, make sure they've been instantiated, then start the regular workers. This makes it so that the HM workers will acquire the right bundles. downside is that you may incur some extra latency.

2. Another option is to target the workers to a specific bundle. You should be able to fetch the current placement group within the tune trainable via [get_current_placement_group](https://docs.ray.io/en/latest/package-ref.html#get-current-placement-group), then target a specific bundle with `worker.options(placement_group=pg, placement_group_bundle_index=...)`. The downside of this approach is that you have to be cautious about how you index your placement group bundles.

> A more informative error message could be useful here.

We probably want a utility for displaying the committed / existing resources for each bundle. @rkooo567 anything like that exist?

**Comment by rkooo567** [comment]
@soundway I totally agree with what you are saying. I think the current API is very hard to use. Actually we are actively seeing if we can make API simpler & easier to use. I will share more information once things are more refined.

> We probably want a utility for displaying the committed / existing resources for each bundle. @rkooo567 anything like that exist?

The best one is `ray.availble_resources()`, but it has 2 issues. 
1. The pg resources are weirdly formatted. 
2. The consistency of API is not guaranteed. It is not guaranteed `ray.availble_resources()` always return the correct value. (it could be stale).

I think for 1, I can make some improvements (I will follow up on this). For 2, it is a bit tricky.

For this particular case, my impression is you want 3 bundle pools from the same pg. 
- `index 1` -> first actor
- `2 ~ num_workers` bundle -> `workers` actors
-  `num_workers + 1 ~ num_workers + num_hm_workers` bundles. -> `hm_workers` actors

The simplest case is Tune just creates 3 pgs. But this makes me wonder

- @soundway Do you have placement requirement for each bundle pool? Like should `workers bundle pool` and `hm_workers bundle pool` be collocated / spread? 
- If not, @richardliaw is it required to schedule 3 bundles pools atomically? Does creating 3 pg instead from the Tune side work?

**Comment by rkooo567** [comment]
Closing it as this wasn't the issue from the API itself. We are planning to have an improvement on the API, and it might be great if the question above is answered!
