### ISSUE TITLE
[Bug] Env variables are undocumented: AUTOSCALER_MAX_LAUNCH_BATCH AUTOSCALER_MAX_CONCURRENT_LAUNCHE

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#21936]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

There are env variables controlling speed of upscaling which are undocumented
AUTOSCALER_MAX_LAUNCH_BATCH AUTOSCALER_MAX_CONCURRENT_LAUNCHES
Document them, as many users have raised issues of the form "upscaling is slow, why?"

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
These aren't supposed to be user configuable, just internal constants. The upscaling config should be just `upscaling_speed`.

**Comment by DmitriGekhtman** [comment]
Some users have complained that upscaling is too slow, but ok.

I'm going to modify the defaults for K8s stacks (by setting envs in default and recommended configs), as the defaults appear to be targeted towards AWS EC2 autoscaling.
