### ISSUE TITLE
Make a `list_jobs` API

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21956]
We should export the jobs info to the cluster snapshot as well.

**Comment by edoakes** [comment]
Proposed API from discussion w/ @architkulkarni:

```
GET /api/jobs/
{
    "job_id": {"entrypoint": ..., "metadata": ..., "namespace": ..., "status": ..., "message": ...}
}
```

Also modify
`GET /api/jobs/{job_id}` to match the above

Add corresponding `list_jobs` method to SDK and `ray job list` to CLI.
