### ISSUE TITLE
[Feature] [Docs] Do not copy line numbers when clicking the clipboard

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#21968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Docs such as [this one](https://ray--21887.org.readthedocs.build/en/21887/serve/end_to_end_tutorial.html) include code snippets that can be copied by clicking a clipboard pop-up:

<img width="759" alt="clipboard" src="https://user-images.githubusercontent.com/92341594/151639695-02554f09-7406-4637-a1c1-9816a4c1665f.png">

However, due to updates in the doc formatting, clicking this clipboard now also copies line numbers (that are inserted using `:linenos:` in the source rst documentation files). The requested feature is to allow users to click this clipboard and copy only the code, not the line numbers.

### Use case

This feature makes it easier to follow along coding examples in the documentation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maxpumperla** [comment]
@shrekris-anyscale very good catch, thanks for spotting this. Should be an easy fix!

**Comment by maxpumperla** [comment]
ok, so surprisingly enough this seems to be a sphinx >= 4.0 issue, which needs to be patched in downstream themes:

https://github.com/sphinx-doc/sphinx/issues/9363

The RTD theme has fixed it, the book theme might not be aware yet:

https://github.com/readthedocs/sphinx_rtd_theme/issues/1168

**Comment by shrekris-anyscale** [comment]
Bumping this issue to remove the stale tag. I believe line numbers still get copied with that button.
