### ISSUE TITLE
[Spark-on-Ray] [Bug] When the total samples in a worker <= batch_size, the dataset's iteration will fail.

### ISSUE THREAD

**Issue by KepingYan** [ray-project/ray#21980]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

When the total samples in a worker <= batch_size, the dataset's iteration will fail at an assert:
`assert isinstance(block, pyarrow.Table), block`
Stack:
```python
  print(next(dataset.__iter__()))
  ray/data/impl/torch_iterable_dataset.py", line 10, in __iter__
    yield from it
  ray/data/dataset.py", line 1946, in make_generator
    drop_last=drop_last):
  ray/data/dataset.py", line 1865, in iter_batches
    yield from batch_block(block_window[0])
  ray/data/dataset.py", line 1858, in batch_block
    yield format_batch(batcher.next_batch(), batch_format)
  ray/data/impl/batcher.py", line 67, in next_batch
    output.add_block(block)
  ray/data/impl/arrow_block.py", line 98, in add_block
    self._builder.add_block(block)
  ray/data/impl/arrow_block.py", line 142, in add_block
    assert isinstance(block, pyarrow.Table), block
```
after debugging, I found that in this case, the following code is executed, but `block` has not been converted to `pyarrow.Table` at this time.
https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/data/impl/batcher.py#L65-L67
When I try to change L67 to `output.add_block(accessor.to_arrow())`, it works well.
I think this is a bug that needs to be fixed, or is there anything else that needs to be done to avoid this mistake?

### Versions / Dependencies

```
python==3.7
ray==1.9.2
raydp==0.4.1
torch==1.8.1+cpu
```

### Reproduction script

**code**
```python
import ray
import raydp
import torch

ray.init()
app_name = "Test"
num_executors = 1
cores_per_executor = 1
memory_per_executor = "500M"
spark = raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)
data = spark.read.format("csv").option("header", "true") \
        .option("inferSchema", "true") \
        .load('data.csv')
features = [field.name for field in list(data.schema) if field.name != "label"]

dataset = ray.data.from_spark(data, parallelism = 1)
dataset = dataset.to_torch(feature_columns=features,
                                        label_column="label",
                                        label_column_dtype=torch.float,
                                        feature_column_dtypes=[torch.float],
                                        batch_size=4)
print(next(dataset.__iter__()))
```
**data.csv**
```
fea,label
1,0
1,0
1,0
1,0
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@KepingYan Thank you for opening this issue, and for including a reproduction! This does indeed seem like an unhandled edge case, I'm surprised that this slipped through. I'll open up a PR fixing this!

**Comment by clarkzinzow** [comment]
@KepingYan I opened a PR adding a test that covers this case (batch size larger than total dataset size), and the test passes for me locally. This is a set of in-memory Pandas DataFrames for the test data, so maybe the bug is somewhere in the Spark-on-Ray integration.

Could you try reading the CSV with Datasets and see if you still hit that assertion error?

```python
import ray
import torch

ray.init()
dataset = ray.data.from_csv("data.csv")
features = [field for field in data.schema.names if field != "label"]
dataset = dataset.to_torch(feature_columns=features,
                                        label_column="label",
                                        label_column_dtype=torch.float,
                                        feature_column_dtypes=[torch.float],
                                        batch_size=4)
print(next(dataset.__iter__()))
```

Also, trying on the [latest nightly build](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies) would also be very helpful!

**Comment by clarkzinzow** [comment]
@KepingYan Ping on this!

**Comment by KepingYan** [comment]
@clarkzinzow  I'm back and sorry for not following up for so long.
Both ray.data.read_csv() and ray.data.from_pandas()  work fine for me. This makes sense because the blocks of data returned by both functions are already of type `pyarrow`,  so they do not trigger this assertion: https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/data/impl/arrow_block.py#L142
But the type of block I get here in my code sample is `bytes`.

It's true that this problem may be solved by converting the block of the data into `pyarrow` in Spark-on-Ray, but does ray need to consider this situation as well? 

- it seems that the source code does not state that the `bytes` type cannot be used
- another branch can handle the `bytes` type (L60 can convert the type of block to `pyarrow`),  https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/data/impl/batcher.py#L60  https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/data/impl/batcher.py#L69-L74 only this branch cannot (without any processing of the block) and then hit that assertion error. https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/data/impl/batcher.py#L65-L67

And this problem persists in ray-1.10.0.
