### ISSUE TITLE
[Datasets] [Bug] workers and actors leaking in trivial dataset use

### ISSUE THREAD

**Issue by disruptek** [ray-project/ray#21999]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I have a stock cluster and I'm testing datasets, but after running the code below, an actor named `ray::_DesignatedBlockOwner` persists in addition to three `ray::IDLE` workers.  Eventually, these will cumulatively consume all the memory in the cluster.

I will also eventually receive warnings such as this:
```
The actor '_DesignatedBlockOwner' has been exported 100 times. It's possible that this warning is accidental, but this may indicate that the same remote function is being defined repeatedly from within many tasks and exported to all of the workers. This can be a performance issue and can be resolved by defining the remote function on the driver instead. See https://github.com/ray-project/ray/issues/6240 for more discussion.
The remote function 'ray.data.read_api.remote_read' has been exported 100 times. It's possible that this warning is accidental, but this may indicate that the same remote function is being defined repeatedly from within many tasks and exported to all of the workers. This can be a performance issue and can be resolved by defining the remote function on the driver instead. See https://github.com/ray-project/ray/issues/6240 for more discussion.
The remote function '__main__.foo' has been exported 100 times. It's possible that this warning is accidental, but this may indicate that the same remote function is being defined repeatedly from within many tasks and exported to all of the workers. This can be a performance issue and can be resolved by defining the remote function on the driver instead. See https://github.com/ray-project/ray/issues/6240 for more discussion.
```

### Versions / Dependencies

ray-1.9.2
python-3.7.7 (and 3.9.5)
pyarrow-6.0.1
ubuntu-21.04 (default ray containers)
 `ami-029536273cb04d4d9`; so-called _deep learning ami (ubuntu) version 55_

### Reproduction script

```python
import ray

@ray.remote
def foo():
    return ray.data.range_arrow(10000, parallelism = 1)

ray.init(address="auto")
ref = foo.remote()
print(ray.get(ref))
ray.shutdown()
```

### Anything else

The code leaks three workers and one actor every time it is invoked against the cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
@clarkzinzow can you take a look?

**Comment by clarkzinzow** [comment]
@ericl It seems as if we need better lifecycle management of `_DesignatedBlockOwner`. Just to double-check, why can't we tie the `_DesignatedBlockOwner` lifetime to the driver/context creator instead of making it a detached actor?

**Comment by ericl** [comment]
We should be able to at least make it a global singleton. I think this is just a matter of setting the namespace.

**Comment by ericl** [comment]
@clarkzinzow maybe it would also work just to not set detached lifetime. The default lifetime should work, since we hold a reference to the actor in the context.

**Comment by disruptek** [comment]
I'm testing with a nightly (on python-3.9.5) and the first time I execute the code above, I'm left with four `IDLE` workers and a `_StatsActor` which persists.  Subsequent invocations add only three `IDLE` workers and a `_StatsActor`.

Are you able to reproduce?

**Comment by ericl** [comment]
That's expected. The number of stats actors shouldn't increase more than 1 though.

**Comment by ericl** [comment]
Hmm if the number of StatsActors increases @clarkzinzow I think we should make it a named actor / singleton as Serve does for its coordinator actor.

**Comment by ericl** [comment]
I can confirm StatsActor is cleaned up after the job exited, so things are working as intended now.

**Comment by disruptek** [comment]
This is still a problem for me; the code above still leaks one actor and several workers.  Any suggestions on where to look?
