### ISSUE TITLE
[Bug] shuffle_1tb_5000_partitions	 failed with `ray.exceptions.OwnerDiedError:`

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#21995]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

This test never failed before. I failed to find the right commit range. Maybe we merged a PR that makes things flaky recently. 

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_PghWWQhbp6cTthrC9SF42bvz
--

### Versions / Dependencies

Master

### Reproduction script

Run `shuffle_1tb_5000_partitions`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
Note there is a worker failed register error at the beginning of the runs.

**Comment by jjyao** [comment]
It has been successful since then.
