### ISSUE TITLE
[Dataset][Bug] _spread_resource_prefix doesn't work with GPU nodes

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#22003]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Currently, we always require CPU for data pipeline, and with the _spread_resource_prefix we requires GPU nodes to remove CPU resources. This makes it challenging if we want to schedule data pipeline on GPU nodes.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
This should be unneeded after @jjyao 's spread scheduling right?

**Comment by jjyao** [comment]
With spread scheduling, it won't run on GPU nodes either due to the global config `scheduler_avoid_gpu_nodes`
