### ISSUE TITLE
Make it possible to connect to Ray from multiple users on the same machine

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2200]
see https://groups.google.com/forum/#!topic/ray-dev/AGlrON95M0c

This would be very useful functionality to have, contributions welcome!

**Comment by robertnishihara** [comment]
I just tried this on AWS and it worked for me (one user was `ubuntu` and one was `root`). I tried with both users using the same Python executable and also with different executables.

I suspect the issue is that the two users have different Python versions or Ray versions.

**Comment by robertnishihara** [comment]
Closing because I think this works. Feel free to reopen if you see the issue.
