### ISSUE TITLE
How to control parameters range in pbt when not resampling

### ISSUE THREAD

**Issue by panye** [ray-project/ray#2201]
### System information
- **Ray version**: 0.4.0
- **Python version**: 2.7.0

### Describe the problem

Hi, I'm using Population Based Training in ray. And I set the parameters as following:

```
pbt = PopulationBasedTraining(                                                                                                                                                        
    time_attr="training_iteration", 
    reward_attr="mean_accuracy",                                                                                                                                                     
    perturbation_interval=1,                                                                                                                                                         
    hyperparam_mutations={                                                                                                                                                           
        "lr": lambda: random.uniform(0.000001,0.01),                                                                                                                                   
        "batch_size": lambda: random.randint(32, 64),                                                                                                                                
})

```
By default, there is 25% chance to resample parameters from the above distribution. And resampled parameters are definitely in my predefined range, which means batch size should larger than 32 and smaller than 64. But if not resampled, the value will be perturbed by a factor of 1.2 or 0.8. And in some cases, the batch size will be larger than 64, which may cause OOM problem. I'm wondering how to control the range of parameters when they are not resampled. Thank you!

### part of running logs

my_class_3@perturbed[batch_size=72,lr=0.0008]:     RUNNING [pid=10311], 2830 s, 3000 ts, 0.0416 acc

**Comment by ericl** [comment]
Hey @panye , you can specify `custom_explore_fn` to implement these sort of constraints on the hyperparameters. There's an example of this here: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/pbt_ppo_example.py#L22

**Comment by ericl** [comment]
Cool, closing then
