### ISSUE TITLE
[Bug] Dashboard memory leak

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#22027]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

Ray dashboard keeps the whole history of actors and never delete the old ones. So as time going, it'll OOM.

This issue is a follow up for this one https://github.com/ray-project/ray/issues/21432

many drivers test eventually OOM because we are running faster than before and as dashboard memory keeps increasing, it eventually OOM.

### Versions / Dependencies

master

### Reproduction script

many driver nightly tests

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I believe we've also gotten reports of high **CPU** usage from the dashboard.
https://discuss.ray.io/t/ray-dashboard-is-hanging/6202
Is that issue known/understood/solved? Is that issue separate from this one?

**Comment by alanwguo** [comment]
@DmitriGekhtman , have you been able to repro this using a kuberay cluster? (High CPU usage).

**Comment by DmitriGekhtman** [comment]
No, just heard rumors.
Will trying submitting a ton of tasks or something to see if it triggers the issue.

**Comment by alanwguo** [comment]
1. Clean up the actor metadata LRU
2. Do not cache logs. Instead use state observability `/api/v0/logs`
