### ISSUE TITLE
[Bug] Rllib episode handling with concurrent episodes

### ISSUE THREAD

**Issue by aralebox** [ray-project/ray#22036]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

In my project, I use ExternalEnv to train a policy. Due to practical reasons, I need to create an 'action episode' to continuously get actions. Meanwhile, separate episodes ('log episodes') are started to log actions and returns, then terminated. 
An error happens after a 'log episode' is ended, and get_action API is called using the 'action episode'.

**Error message:**
--- Logging error ---
Traceback (most recent call last):
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/env/policy_client.py", line 273, in run
    samples = self.rollout_worker.sample()
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 757, in sample
    batches = [self.input_reader.next()]
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 103, in next
    batches = [self.get_data()]
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 265, in get_data
    item = next(self._env_runner)
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 656, in _env_runner
    eval_results = _do_policy_eval(
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 1068, in _do_policy_eval
    input_dict = sample_collector.get_inference_input_dict(policy_id)
  File "/Users/ewayuwa/anaconda3/envs/rai_ray192/lib/python3.8/site-packages/ray/rllib/evaluation/collectors/simple_list_collector.py", line 627, in get_inference_input_dict
    collector = self.agent_collectors[k]
KeyError: (1460398824, 'agent0')

**Reproduction:**
The server is the "[simple “CartPole-v0” server](https://github.com/ray-project/ray/blob/master/rllib/examples/serving/cartpole_server.py)" provided in the Rllib "External Agents and Applications" section.
Client scripts are provided below.

**Suggested fix:**
Some debugging shows that _self.forward_pass_agent_keys_ in _simple_list_collector::get_inference_input_dict()_ is not updated when an episode is ended. 
I tried to add a method to update the variable in _simple_list_collector.py_, and call it in _sampler:: \_process_observations()_. It seems working. But I'm sure the ray team will come up with a more proper solution.

### Versions / Dependencies

python: 3.8.12
ray: 1.9.2

### Reproduction script

```
#!/usr/bin/env python
"""
Example to produce a bug related to episode handling

"""

import argparse
import gym

from ray.rllib.env.policy_client import PolicyClient

parser = argparse.ArgumentParser()
parser.add_argument(
    "--no-train", action="store_true", help="Whether to disable training."
)
parser.add_argument(
    "--inference-mode", type=str, default="local", choices=["local", "remote"]
)
parser.add_argument(
    "--off-policy",
    action="store_true",
    help="Whether to compute random actions instead of on-policy "
    "(Policy-computed) ones.",
)
parser.add_argument(
    "--stop-reward",
    type=float,
    default=9999,
    help="Stop once the specified reward is reached.",
)
parser.add_argument(
    "--port", type=int, default=9900, help="The port to use (on localhost)."
)

if __name__ == "__main__":
    
    args = parser.parse_args()

    env = gym.make("CartPole-v0")
    client = PolicyClient(
        f"http://localhost:{args.port}", inference_mode=args.inference_mode
    )

    # Get a dummy obs
    dummy_obs = env.reset()
    dummy_action = 0
    dummy_reward = 0

    # Start an episode to only get actions
    action_eid = client.start_episode(training_enabled=False)
    # Get some actions using the action episode
    _ = client.get_action(action_eid, dummy_obs)
    _ = client.get_action(action_eid, dummy_obs)

    # Start a log episode to log action and log return for learning
    log_eid = client.start_episode(training_enabled=True)
    # Log action and log return
    client.log_action(log_eid, dummy_obs, dummy_action)
    client.log_returns(log_eid, dummy_reward)
    # End the log episode
    client.end_episode(log_eid, dummy_obs)

    # Continue getting actions using the action episode
    # The bug happens when executing the following line
    _ = client.get_action(action_eid, dummy_obs)

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @aralebox , thanks for raising this issue. I can reproduce and am working on a fix ...

**Comment by aralebox** [comment]
> Hey @aralebox , thanks for raising this issue. I can reproduce and am working on a fix ...

Thanks for the prompt respond, Sven!

**Comment by sven1977** [comment]
@aralebox
fix-it PR: https://github.com/ray-project/ray/pull/22076

It was basically a bug in our sample collector, not adding samples for those episodes that have `training_enabled=False`. It should still collect those, but simply NOT postprocess them (and return for training) at a later point (when the rollout/episode is done). This not recording the data led to a "confusion" with the forward passes to be performed on the policy (hence the key error).

**Comment by sven1977** [comment]
Should be merged soon.

**Comment by aralebox** [comment]
> Should be merged soon.
Great! And thanks for the quick efforts!
Shall I update my ray to the latest version after the merge?
