### ISSUE TITLE
Get object from different machines

### ISSUE THREAD

**Issue by 0freeday** [ray-project/ray#2204]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu1404
- **Ray installed from (source or binary)**:binary
- **Ray version**:0.4.0
- **Python version**:2.7.12

### Describe the problem

Before I run the python script , I have run the cmd on m1:
**ray start --head**
 the cmd on m2:
**ray start --redis-address=10.31.22.111:32598**

This is on the machine named **m1: 10.31.22.111**
**import ray
ray.init(redis_address='10.31.22.111:32598')
x_id = ray.put(1)**

This is on the machine named **m2: 10.31.22.109**
**import ray
ray.init(redis_address='10.31.22.111:32598')
@ray.remote
def f(x):    return x+1
res_id = f.remote(x_id)
print(ray.get(res_id))**

When I run the script , the exception occured:

Traceback (most recent call last):
  File "1.py", line 8, in <module>
    res_id = f.remote(x_id)
NameError: name 'x_id' is not defined

So how can I get the object from the different machines?

**Comment by 0freeday** [comment]
@robertnishihara Hi, Would you mind to have a look please? Im really need help, thank you very much.

**Comment by robertnishihara** [comment]
Hi @0freeday, the variable `x_id` is not available on the second driver. It is only available within the script where you defined it. You should try to write everything within a single script.

**Comment by del007** [comment]
@robertnishihara I see. Thank you. Very appreciate for your comment🙂
