### ISSUE TITLE
[Release 1.11.0][Core] `single_client_get_calls_Plasma_Store` performance regression (-24%)

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#22053]
In the `1.11.0` release branch, `single_client_get_calls_Plasma_Store` has a regression from 5822/s -> 4417/s. After searching, I found 097706b35d55e0910cbc9bcf7995e1509ce2c6ca to be the root cause. The increased cost comes from recording stats in opencensus. I'm working on a fix.

The decisions to be made:
- Whether the regression needs to be fixed for the `1.11.0` release.
- To avoid the regression in 1.11.0, whether we should cherry pick a revert or a fix.

cc @rkooo567 @scv119 @ericl @zhe-thoughts

**Comment by mwtian** [comment]
Btw, there was a previous regression for `single_client_get_calls_Plasma_Store`:
- [~10k in Ray 1.6.0](https://github.com/ray-project/ray/blob/master/release/release_logs/1.6.0/microbenchmark.txt#L4)
- [~7k in Ray 1.7.0](https://github.com/ray-project/ray/blob/master/release/release_logs/1.7.0/microbenchmark.txt#L15)

I didn't find the conclusion for it.

**Comment by scv119** [comment]
> Btw, there was a previous regression for single_client_get_calls_Plasma_Store:
> 
> ~10k in Ray 1.6.0
> ~7k in Ray 1.7.0
> I didn't find the conclusion for it.

Yeah we've refactor a lot of plasma code during that period; could be introduced by one of those changes.
