### ISSUE TITLE
[Dataset] Improve dataset performance for validation.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#22069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

In certain workloads, the user runs validation very frequently; for example, every 1000 training step the use will validate the model with ~30GB of data. Currently the dataset is not optimized for validation performance, as the empirical experiments shows that using Ray dataset for validation (copy from data node to trainer) is slower than reading the validation files from disk.

### Use case

N/A

### Related issues

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
@scv119 @jianoaix Did we end up hitting the mark here for the user in question?

**Comment by jianoaix** [comment]
Closing now, feel free to reopen if we still see the issue.
