### ISSUE TITLE
[runtime env] Make RuntimeEnvAgent fate-share with raylet

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#22061]
Context and discussion:
https://github.com/ray-project/ray/issues/21695
https://github.com/ray-project/ray/pull/20273#issuecomment-1022943004

**Comment by rkooo567** [comment]
Can we defer this for now? We need actual design review to confirm the architecture. Detailed discussion is in https://github.com/ray-project/ray/issues/21695 (I think we need a formal design review)
