### ISSUE TITLE
[DataFrame] pivot_table is not supported :-(

### ISSUE THREAD

**Issue by chanansh** [ray-project/ray#2206]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-569bc709f835> in <module>()
----> 1 pv = df.pivot_table(index='u', columns='c', values='b')

~/anaconda3/lib/python3.6/site-packages/ray/dataframe/dataframe.py in pivot_table(self, values, index, columns, aggfunc, fill_value, margins, dropna, margins_name)
   1842                     dropna=True, margins_name='All'):
   1843         raise NotImplementedError(
-> 1844             "To contribute to Pandas on Ray, please visit "
   1845             "github.com/ray-project/ray.")
   1846 

NotImplementedError: To contribute to Pandas on Ray, please visit github.com/ray-project/ray.

**Comment by devin-petersohn** [comment]
Hi @chanansh! Thanks for posting this request. I'll move it up in priority on our backlog. If you're interested in implementing this yourself, feel free to let me know.

**Comment by chanansh** [comment]
Is implemtation in python or c?

**Comment by robertnishihara** [comment]
The Pandas on Ray library is in Python. The Ray backend itself is primarily in C++ with a Python frontend.

**Comment by chanansh** [comment]
But for pivot do I need low level or can I use the wrap?

**Comment by devin-petersohn** [comment]
I am putting together some documentation for contributing. For now, if you're interested in trying it, take a look at how we do other, similar transformations in [dataframe.py](https://github.com/ray-project/ray/blob/master/python/ray/dataframe/dataframe.py). It will not be low level, but some knowledge of how to parallelize is necessary (though even an introductory understanding should be fine). We are using Ray's python API to parallelize the operations on the dataframes.

**Comment by devin-petersohn** [comment]
@chanansh I am moving this feature request to the new repo so we do not lose track of it: https://github.com/modin-project/modin/issues/65
