### ISSUE TITLE
[Bug] FrameStack not handled in ray 1.9

### ISSUE THREAD

**Issue by Xuzzo** [ray-project/ray#22075]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

@MischaPanch  @ivandrodri

In our trainings we have been using [Framestack](https://github.com/openai/gym/blob/master/gym/wrappers/frame_stack.py) (gym wrapper) to stack observations. In ray 1.9, we get the following error

line 1695, in _validate_env
dummy_obs = dummy_obs.astype(env.observation_space.dtype)
AttributeError: 'LazyFrames' object has no attribute 'astype'

The problem is that at .reset() FrameStack returns a LazyFrame object and not an array.
Would it be possible to add support for FrameStack? Thanks.

### Versions / Dependencies

python 3.8
ray 1.9
ubuntu 20.04

### Reproduction script

Import gym 
from gym.wrappers import FrameStack
env = gym.make("CartPole-v0")
env = FrameStack(env, num_stack=2)
obs = env.reset()
obs.astype(float)

### Anything else

Commenting out lines 1693->1695 of rollout_worker.py everything seems to run normally.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by stwerner97** [comment]
The same issue applies to version 1.10.0

**Comment by kouroshHakha** [comment]
This issue is closed since it is resolved in master.

```
from ray.rllib.algorithms.ppo import PPOConfig
from ray.tune.registry import register_env

import gym
from gym.wrappers import FrameStack

env_creator = lambda config: FrameStack(gym.make("CartPole-v0"), num_stack=2)
register_env("stacked_cartpole", env_creator)

config = (
    PPOConfig()
    .environment(env="stacked_cartpole")
)

algo = config.build()
algo.train()
```
