### ISSUE TITLE
ResponseError: Invalid argument '10464' for CONFIG SET 'maxclients' 

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#22085]
Upon running a Ray script on a laptop for the first time in a day, I very often have the script fail and the following error message appear:

```
ResponseError: Invalid argument '10464' for CONFIG SET 'maxclients' - The operating system is not able to handle the specified number of clients, try with 10000
```

It's difficult to repro. Ray version is `1.9.2`. Any potential explanation or fix we should tell users to do / avoid?

**Comment by worldveil** [comment]
Bump here, anyone know what issue might be? @wuisawesome perhaps?

**Comment by wuisawesome** [comment]
Not sure what the issue is, but `maxclients` is a redis config, and as of 1.11, redis will be removed, so it should be solved by the most overkill solution ever :)
