### ISSUE TITLE
[RFC] Moving runtime env out of worker pool

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#22089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently runtime env logic is tightly coupled to worker pool, and this is not an ideal place to write runtime env logic. This breaks the single responsibility principle, which leads to the complicated plumbing code path like we have now. The culprit is https://github.com/ray-project/ray/pull/22032. 

Runtime env should be treated like other scheduling dependencies, like object pulling or worker startup. I think the ideal place to put this is inside `cluster_task_manager` between dependency pulling <-> worker startup.

Ideally, the whole logic needs to be hidden behind `runtime_env_manager` interface. Right now, we have code that needs to directly call `agent_manager_`, and this sort of things need to be avoided (https://github.com/ray-project/ray/blob/92d7e9bf988e3b482ad54847fa1d33fa6451db68/src/ray/raylet/worker_pool.cc#L1499).

The detailed refactoring proposal is TBD 

cc @architkulkarni @edoakes 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
Agree at a high level with the motivation, we'll need a detailed proposal on how exactly it should interface w/ the scheduler.
