### ISSUE TITLE
Make Ray Tune / hyperparameter tuning usage more prominent in config section

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#22080]
https://docs.ray.io/en/latest/train/user_guide.html#configuring-training

This section is good, but I missed the first couple read throughs that hyperparameter tuning was the main usage, ie: moving last sentence `A primary use-case for config is to try different hyperparameters. To perform hyperparameter tuning with Ray Train, please refer to the [Ray Tune integration](https://docs.ray.io/en/latest/train/user_guide.html#train-tune).` to the start of the section.

**Comment by worldveil** [comment]
Any complaints with this change? Or is there a better way?

**Comment by matthewdeng** [comment]
I don't have any complaints, but I would say that hyperparameter tuning is not necessarily the main usage even though it is the motivation for why the API is structured this way.

There are two cases that I would think about when writing this doc section:
1. I want to pass in some arguments. Normally, I would just add them to the function signature, but if I try that then an error will be raised. A simple example for this is I want to run a training function with a `smoke_test` flag or something of the sort. This is probably the main reader persona at this point of the documentation.
2. I want to do hyperparameter tuning. This actually isn't the primary use for this section of the documentation (as there is a section specific to hyperparameter tuning)
