### ISSUE TITLE
Ray serialization problems  

### ISSUE THREAD

**Issue by abhalawat** [ray-project/ray#22103]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

`Error : TypeError: Could not serialize the function address.contract`
I was using ray to make the processing between ethereum blockchain faster but faced this issue:

Code I used is:

Could anyone guide me how to resolve this?

### Versions / Dependencies

Python 3.8.10

### Reproduction script

```
@ray.remote
def contract(_block):
    blockDetails = web3.eth.get_block(_block)
    transaction = blockDetails.transactions
    for i in range(len(transaction)):
        tx_hash = transaction[i].hex()
        address = web3.eth.getTransactionReceipt(tx_hash).contractAddress
        print("address ",address," txHash ",tx_hash)
        if address != None:
            collection.insert_one({"Contractaddress":address,"Block": _block})
            return address

latestBlock = web3.eth.get_block('latest').number
futures = [contract.remote(block) for block in range(latestBlock)]
futures_id = ray.put(futures)
print(ray.get(futures))
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
I recommend you to try https://docs.ray.io/en/master/ray-core/serialization.html#troubleshooting on the `contract` method, and see if that contains any unserializable objects. Note that it can happen if the function contains "captured unserialized variables". Unserializable objects can be something like lock objects.

Example; 

```python3
a = ObjectUnserializable()

def f():
    # a is implicitly captured, and since a is unserializable, f is also unserializable. 
    print(a)
```

**Comment by abhalawat** [comment]
When I am trying to connect to mongo DB it is giving me this error:
`TypeError: cannot pickle '_thread.lock' object`

`TypeError: Could not serialize the function address.contract. Check https://docs.ray.io/en/master/serialization.html#troubleshooting for more information.`

How to I resolve this?

**Comment by rkooo567** [comment]
Please refer to the answer above! It is highly likely you are capturing MongoDB implicitly. It can be happened when you import MongoDB related packages. In that case doing something like this can also solve the issue
```python3
@ray.remote
def f():
    # import MongoDB related things here
```

**Comment by abhalawat** [comment]
okay,This solved the issue
