### ISSUE TITLE
[Bug] Resource demand backlog caps out at 10+ in multi-node K8s cluster

### ISSUE THREAD

**Issue by vicyap** [ray-project/ray#22122]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

My Setup:

I have deployed a Ray Cluster on Kubernetes with EKS. The cluster has a worker type with 15 CPUs that is always on (min_workers: 1). Other worker types include 7 CPUs, 15 CPUs, 30 CPUs.

I've also configured: `upscaling_speed=9999`, `AUTOSCALER_MAX_LAUNCH_BATCH=9999`, `AUTOSCALER_MAX_CONCURRENT_LAUNCHES=9999` as recommended here: https://github.com/ray-project/ray/issues/21683#issuecomment-1018015823

**Main Issue**:

Whenever I launch 200 tasks, the autoscaler only launches a single 7-cpu worker. After that worker is ready, it launches another single 7-cpu worker. I expect it to launch at least enough workers for 185 CPUs in the first iteration.

In the Ray Operator Pod Logs, I see `{'CPU': 1.0}: 1+ pending tasks/actors`. I imagine this should be something like "185+ pending tasks/actors"?

However, I can successfully use `ray.autoscaler.sdk.request_resources` to request 200 cpus all at once. 

---

Ray Operator Pod Logs:
`kubectl logs -f po/ray-operator-987dc99b9-47v92 | grep Resources -A 10`
```
Resources
---------------------------------------------------------------
Usage:
 0.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 (no resource demands)
py38-cu112,karpenter:2022-02-04 10:47:45,337    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.6050498485565186, '10.16.126.217': 0.6049869060516357}\n - NodeIdleSeconds: Min=0 Mean=38219 Max=76437\n - ResourceUsage: 0.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:45,338    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 4.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:47:51,278    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.5087563991546631, '10.16.126.217': 0.5086848735809326}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 4.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:51,289    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 10.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:47:57,323    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.4549856185913086, '10.16.126.217': 0.4549136161804199}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 10.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:57,324    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 15.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:48:03,348    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.54921555519104, '10.16.126.217': 0.5491447448730469}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 15.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:48:03,350    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 15.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
```

Ray Pod Description:
```
Name:         ray-operator-987dc99b9-47v92
Namespace:    karpenter
Priority:     0
Node:         ip-10-16-65-175.us-west-2.compute.internal/10.16.65.175
Start Time:   Thu, 03 Feb 2022 13:05:01 -0600
Labels:       cluster.ray.io/component=operator
              pod-template-hash=987dc99b9
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.16.68.93
IPs:
  IP:           10.16.68.93
Controlled By:  ReplicaSet/ray-operator-987dc99b9
Containers:
  ray:
    Container ID:  docker://f78dc8efee6c1f8483438e325c275a281c310341a1f304f4811aa8c80d263903
    Image:         rayproject/ray:bbc64e
    Image ID:      docker-pullable://rayproject/ray@sha256:6a0520c449555a31418ed79188827553e43276db6abc1bc4341edd16dd832eb3
    Port:          <none>
    Host Port:     <none>
    Command:
      ray-operator
    State:          Running
      Started:      Thu, 03 Feb 2022 13:05:03 -0600
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:                1
      ephemeral-storage:  1Gi
      memory:             1Gi
    Environment:
      AUTOSCALER_MAX_NUM_FAILURES:         inf
      AUTOSCALER_MAX_LAUNCH_BATCH:         9999
      AUTOSCALER_MAX_CONCURRENT_LAUNCHES:  9999
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wq2kl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-wq2kl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

### Versions / Dependencies

Ray Operator Image: rayproject/ray:bbc64e
Ray Client Version: 1.9.2
Python 3.8
Kubernetes Version: 1.21 with EKS

### Reproduction script

```python3
from pprint import pprint

import ray
ray.init("ray://mycluster.internal:10001")

@ray.remote
def task():
    import time
    time.sleep(30)

pprint(ray.cluster_resources())
results = ray.get([task.remote() for _ in range(200)])
```

### Anything else

This issue occurs every time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
>  {'CPU': 1.0}: 1+ pending tasks/actors

This seems like a pretty legit bug. @wuisawesome or @DmitriGekhtman can you try to repro? The script is just launching 200 tasks that sleep.

**Comment by DmitriGekhtman** [comment]
I was not able to replicate with a similar set-up but everything running with Ray 1.10.0

One suggestion is to trying using the same Ray version across all components (client, operator, head, workers).
(We'll add that recommendation to the docs soon.)

Issues with unexpected resource demands are kind of a recurring theme lately.
I'm going to push a PR adding a debug flag to enable logging the entire resource message in the autoscaler.

**Comment by DmitriGekhtman** [comment]
This should help debug stuff like this
https://github.com/ray-project/ray/pull/22136/

**Comment by vicyap** [comment]
Hi @DmitriGekhtman, thank you for looking into this. About "One suggestion is to trying using the same Ray version across all components", I did initially use the same version, 1.9.2, on all components and still hit this bug/behavior. I thought upgrading the ray operator to the latest docker image (`rayproject/ray:bbc64e` for me at the time) might resolve it, but it did not.

I'll try again and set AUTOSCALER_LOG_RESOURCE_BATCH_DATA=1.

**Comment by DmitriGekhtman** [comment]
To use the flag, the operator will need to use an image that includes the changes from the linked PR -- "rayproject/ray:6235b6" should do.
That particular operator image should be compatible with Ray 1.10.0. 
(If really in doubt, the log statement from the PR can be patched into a 1.10.0 image.)

**Comment by DmitriGekhtman** [comment]
Current running suspicion is that the bug could have to do with the Ray client connection.
In any case, it would be useful to see the resource message.

**Comment by vicyap** [comment]
Ok, I relaunched the operator with `rayproject/ray:6235b6` and set AUTOSCALER_LOG_RESOURCE_BATCH_DATA=1.

I'm still getting the same bug. "{'CPU': 1.0}: 1+ pending tasks/actors" when I should have many more pending tasks.

Logs and info here: https://gist.github.com/vicyap/47bcc6b078abfbae44bafac3676cc01e

**Comment by DmitriGekhtman** [comment]
Thanks for the detailed logs. I'll take a look.
cc also @wuisawesome who has more experience with the autoscaler's processing of the resource message

**Comment by wuisawesome** [comment]
Autoscaler is only seeing 1 request queued. This is going to be tough to debug without a repro. 

```
resource_load_by_shape {
  resource_demands {
    shape {
      key: "CPU"
      value: 1.0
    }
    num_ready_requests_queued: 1
  }
}
```

@vicyap can you try to wrap your submission code in a remote task so we can try to rule out whether it's a ray core or ray client issue?

**Comment by vicyap** [comment]
@wuisawesome 
> can you try to wrap your submission code in a remote task so we can try to rule out whether it's a ray core or ray client issue?

I ran something like this, and it fixed the issue! 
```python
@ray.remote
def task():
    import time
    time.sleep(30)

@ray.remote
def submit_tasks():
    results = ray.get([task.remote() for _ in range(200)])

ray.get(submit_tasks.remote())
```

Logs: https://gist.github.com/vicyap/8048073d6d7d7a9733f7964d03304948
I see `{'CPU': 1.0}: 194+ pending tasks/actors`

---

So what does this mean?

**Comment by wuisawesome** [comment]
Seems to imply that something funky is going on with ray client submitting the tasks... @ckw017 any ideas?

**Comment by ckw017** [comment]
Hmm, not sure. Best guess right now is that somehow the task resource requests are getting lost/modified between when they're submitted on client end and when they're on executed in a real driver. Will take a look

**Comment by DmitriGekhtman** [comment]
Cool, we've narrowed it down to a Ray client issue.

@vicyap could you provide some details on the networking setup you're using for the Ray client connection?
Where is the client connecting from?

**Comment by vicyap** [comment]
Ray Client -> VPN -> AWS NLB (managed as a Kubernetes LoadBalancer Service using [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller)) -> Ray Head Kubernetes Pod.

Clients connect from outside of the Kubernetes cluster. I connect using `ray.init("ray://mycluster.internal:10001")`. I set up `mycluster.internal` so it resolves to the AWS NLB.

Here are the kubernetes objects. I masked some IDs with "********".

`kubectl describe svc/ray-cluster`
```
Name:                     ray-cluster
Namespace:                karpenter
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-name: ray-cluster-gjdk
                          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
                          service.beta.kubernetes.io/aws-load-balancer-type: external
Selector:                 cluster.ray.io/component=ray-py38-cu112-ray-head
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       172.20.108.183
IPs:                      172.20.108.183
LoadBalancer Ingress:     ray-cluster-gjdk-********.elb.us-west-2.amazonaws.com
Port:                     <unset>  10001/TCP
TargetPort:               10001/TCP
NodePort:                 <unset>  32570/TCP
Endpoints:                10.16.102.85:10001
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

```

`kubectl describe po/ray-py38-cu112-head-4xnxj`
```
Name:         ray-py38-cu112-head-4xnxj
Namespace:    karpenter
Priority:     0
Node:         ip-10-16-99-98.us-west-2.compute.internal/10.16.99.98
Start Time:   Mon, 07 Feb 2022 13:29:34 -0600
Labels:       cluster.ray.io/component=ray-py38-cu112-ray-head
              ray-cluster-name=ray-py38-cu112
              ray-file-mounts-contents=********
              ray-launch-config=********
              ray-node-name=ray-ray-py38-cu112-head
              ray-node-status=up-to-date
              ray-node-type=head
              ray-node-uuid=********
              ray-runtime-config=********
              ray-user-node-type=head
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.16.102.85
IPs:
  IP:           10.16.102.85
Controlled By:  RayCluster/ray-py38-cu112
Containers:
  ray-node:
    Container ID:  docker://6e6d69dc421a3a890efa5a75a15528e945c5196f1a8f67076f536a7ba309017e
    Image:         rayproject/ray-ml:1.10.0-py38-cu112
    Image ID:      docker-pullable://rayproject/ray-ml@sha256:604197d454df1d1de3bef55cdba72529120eeef0dae1adb90a24f3500dea6bff
    Ports:         6379/TCP, 10001/TCP, 8265/TCP, 8000/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      --
    Args:
      trap : TERM INT; sleep infinity & wait;
    State:          Running
      Started:      Mon, 07 Feb 2022 13:34:58 -0600
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     0
      memory:  7G
    Requests:
      cpu:     0
      memory:  7G
    Environment:
      RAY_gcs_server_rpc_server_thread_num:  1
      RAY_PROFILING:                         1
    Mounts:
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2lnvv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-2lnvv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              karpenter.sh/capacity-type=on-demand
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

**Comment by DmitriGekhtman** [comment]
@ckw017 do you know if there are Ray client logs that could be of use in debugging?

**Comment by ckw017** [comment]
Yes, @vicyap can you retry without wrapping the submission code, and adding setting the log level to debug with ray.init (`ray.init("ray://mycluster.internal:10001", logging_level=logging.DEBUG)`).

This should produce logs locally on your laptop which could be useful, as well as logs on the head node in `/tmp/ray/session_latest/logs/ray_client_server_23000.err` (if there are similar logs with higher port numbers, i.e. 23001 those logs will also be handy).

**Comment by vicyap** [comment]
Ok, I ran with debug logging and used `range(50)` instead of 200. Logs here: https://gist.github.com/vicyap/1c0966b274cb89da0515810080368160

**Comment by ckw017** [comment]
> Ok, I ran with debug logging and used `range(50)` instead of 200. Logs here: https://gist.github.com/vicyap/1c0966b274cb89da0515810080368160

Thanks for the consistently detailed output! It looks like on the server side, the schedule requests are more or less arriving simultaneously (all 50 within 200ms of each other at 13:50:39), so rules out the possibility of the slow networking skewing when tasks are arriving.

It looks like, the function is being registered with these options (i.e. @ray.remote(**options)(task)):
```
{'num_cpus': 1, 'num_gpus': None, 'max_calls': 0, 'max_retries': 3, 'resources': None, 'accelerator_
type': None, 'num_returns': 1, 'memory': None, 'runtime_env': None, 'scheduling_strategy': None}
```

And then called with these options (i.e. task.options(**options).remote())

```
{'num_returns': None, 'num_cpus': None, 'num_gpus': None, 'memory': None, 'object_store_memory': None, 'accelerator_type': None, 'resources': None, 'max_retries': None, 'retry_exceptions': None, 'placement_group': 'default', 'placement_group_bundle_index': -1, 'placement_group_capture_child_tasks': None, 'runtime_env': None, 'name': '', 'scheduling_strategy': None}
```

Possibility here is that the options in one of these is throwing off the autoscaler. @wuisawesome I'm not too familiar with placement group configs/autoscaler configs, do these look sane/could some combination of these overwriting each other cause the behavior being observed?

**Comment by wuisawesome** [comment]
Those all seem pretty sane. I wonder if we can repro this without ray client?

```
remote_args = {'num_cpus': 1, 'num_gpus': None, 'max_calls': 0, 'max_retries': 3, 'resources': None, 'accelerator_
type': None, 'num_returns': 1, 'memory': None, 'runtime_env': None, 'scheduling_strategy': None}
task_args = {'num_returns': None, 'num_cpus': None, 'num_gpus': None, 
'memory': None, 'object_store_memory': None, 'accelerator_type': None, 
'resources': None, 'max_retries': None, 'retry_exceptions': None, 
'placement_group': 'default', 'placement_group_bundle_index': -1, 
'placement_group_capture_child_tasks': None, 
'runtime_env': None, 'name': '', 'scheduling_strategy': None}

def task():
 pass

remote_fn = ray.remote(**remote_args)(task)

ray.get([remote_fn.options(**task_args).remote() for _ in range(50)])
```

**Comment by vicyap** [comment]
> I wonder if we can repro this without ray client?

I'm not sure how to do this.

Your code doesn’t use `ray.init`, is that what you mean? When I tried this, the code just runs on my local machine.

When I do use `ray.init("ray://mycluster.internal:10001")`, I get the same behavior of `{'CPU': 1.0}: 1+ pending tasks/actors`

**Comment by wuisawesome** [comment]
ah sorry, i guess i'm wondering if you can run that code directly on the head node of the cluster (like `kubectl exec <head_pod> -- bash` and then put that script there and run python). Also should've specified that `task` probably needs to do a `time.sleep` 

```
import ray
import time

ray.init(address = "auto")
remote_args = {'num_cpus': 1, 'num_gpus': None, 'max_calls': 0, 'max_retries': 3, 'resources': None, 'accelerator_
type': None, 'num_returns': 1, 'memory': None, 'runtime_env': None, 'scheduling_strategy': None}
task_args = {'num_returns': None, 'num_cpus': None, 'num_gpus': None, 
'memory': None, 'object_store_memory': None, 'accelerator_type': None, 
'resources': None, 'max_retries': None, 'retry_exceptions': None, 
'placement_group': 'default', 'placement_group_bundle_index': -1, 
'placement_group_capture_child_tasks': None, 
'runtime_env': None, 'name': '', 'scheduling_strategy': None}

def task():
 time.sleep(30)

remote_fn = ray.remote(**remote_args)(task)

ray.get([remote_fn.options(**task_args).remote() for _ in range(50)])
```

**Comment by vicyap** [comment]
Running on the head node, I still get the same bug.
Logs: https://gist.github.com/vicyap/3bb92fe43de969a3c9dece6fc026df3a
[line 270](https://gist.github.com/vicyap/3bb92fe43de969a3c9dece6fc026df3a#file-ray-operator-log-L270) shows `{'CPU': 1.0}: 1+ pending tasks/actors`

**Comment by wuisawesome** [comment]
@scv119 @jjyao  seems like we have a ray-core only repro now. Do y'all mind taking a look? It sounds related to resource demand reporting.

**Comment by ericl** [comment]
I tried running that script locally and I got:
```
Demands:
 {'CPU': 1.0}: 42+ pending tasks/actors
```

Does this happen for you on master? What about k8s vs on laptop?

**Comment by vicyap** [comment]
Thank you all for helping me look into this...

I redeployed the operator with `rayproject/ray:54b2e1` and the head node with `rayproject/ray-ml:54b2e1-py38-cu112` which are the latest docker images.
Now I'm getting `{'CPU': 1.0}: 10+ pending tasks/actors`, which is better than 1+ pending, but still too low.

Logs: https://gist.github.com/vicyap/083d5bbcee5476b6a385b5a5c3a55f79
[line 228](https://gist.github.com/vicyap/083d5bbcee5476b6a385b5a5c3a55f79#file-ray-operator-log-L228)

---

Here is something strange. When I have 0 worker pods running, and I run that test script, I get `{'CPU': 1.0}: 200+ pending tasks/actors`, as expected.

But if I have 1 worker pod already running, and I run the script, I get `{'CPU': 1.0}: 10+ pending tasks/actors`, which is the issue.

---

I was able to repro on my laptop. 

I am using Docker Desktop 4.4.2 to run Kubernetes v1.22.5. I installed ray clusters with the following:
```
cd deploy/charts
helm install ray-operator ./ray --set "operatorOnly=true" --set "operatorImage=rayproject/ray:54b2e1"
helm install ray-cluster ./ray --set "clusterOnly=true" --set "image=rayproject/ray:54b2e1"
```
I modified the chart values and set the head pod type to CPU=0. I also configured upscaling_speed=9999, AUTOSCALER_MAX_LAUNCH_BATCH=9999, AUTOSCALER_MAX_CONCURRENT_LAUNCHES=9999, AUTOSCALER_LOG_RESOURCE_BATCH_DATA=1

Logs for this setup here: https://gist.github.com/vicyap/df09b45cbacf21c2ab6793fb9785c345

**Comment by ericl** [comment]
Ah, I think I have a suspicion of the issue, if it only happens with multiple workers. It may be due to an optimization @jjyao added recently which issues up to 10 concurrent worker resource requests (10 seems like a suspicious coincidence).

Just want to test this hypothesis, if you set `RAY_max_pending_lease_requests_per_scheduling_category=1` env var prior to starting ray, does this fix the issue?

**Comment by ericl** [comment]
It seems like this is somehow generally broken then. You can try it as a workaround but we'll look into this as a high priority issue.

**Comment by ericl** [comment]
Cc @iycheng

**Comment by ericl** [comment]
I think this should be happening on any multi-node cluster.

**Comment by iycheng** [comment]
Hmmm, I was testing scheduling issues, and I didn't encounter this issue. Let me recheck.

**Comment by iycheng** [comment]
I tried it today and it seems not reproducible with a cluster on ec2.

```
Resources
---------------------------------------------------------------
Usage:
 0.00/164.205 GiB memory
 0.0/1.0 node
 0.00/74.365 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 200+ pending tasks/actors
```

The commit is `40fa56f40cb1dbdc50d33291e5adf45e7f32d471`.

**Comment by ericl** [comment]
@iycheng after a bit of fiddling I was able to reproduce on a K8s cluster: https://console.anyscale.com/o/anyscale-internal/clusters/ses_ts49ySqkJ1bSxYD7tXuhjWmH

I think the main thing is you need a large number of worker nodes (wait for 20 nodes to start). In that condition, when I ran the following script I saw that the CPUs in the cluster took a long time to become utilized, though eventually they did (and also eventually the demands increased from 1->9k):

```
import ray
import time

@ray.remote
def foo():
      import time
      time.sleep(999)

ray.get([foo.remote() for _ in range(10000)])
```

**Comment by iycheng** [comment]
@ericl I'm not sure but I see it normal in `ray status`
```
(base) ray@ses-gcvu6f5vyrymh9qcmzhhsnq4-head-node-type-7ff57fdbbc-5pmmm:~$ ray status
======== Autoscaler status: 2022-02-23 20:37:31.026527 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head-node-type
Pending:
 IP not yet assigned: worker-node-type-0, uninitialized
 IP not yet assigned: worker-node-type-0, uninitialized
 IP not yet assigned: worker-node-type-0, uninitialized
 IP not yet assigned: worker-node-type-0, uninitialized
 IP not yet assigned: worker-node-type-0, uninitialized
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 8.0/8.0 CPU
 0.00/13.977 GiB memory
 0.00/6.988 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 9992+ pending tasks/actors
```
My session is here https://console.anyscale.com/o/anyscale-internal/projects/prj_LFKjNprpiYt4AjAf1NdLDJwn/clusters/ses_Gcvu6F5VyrYmH9qCmZhHSNQ4

**Comment by ericl** [comment]
You need to wait for the workers to come up before it can be reproduced.

**Comment by iycheng** [comment]
Oh, yes, I saw it now. Thanks for the clarification.

**Comment by iycheng** [comment]
It seems like

- if it has reached to max workers, demands will show 10+ pending tasks/actors. (full utilized)
- ec2 cluster also has this issue.

I suspect that when the cluster is fully utilized, max_pending_lease_requests_per_scheduling_category will limit the pending leasing request to be 10. So in this case, demand will drop to 10. I'll study the code related to max_pending_lease_requests_per_scheduling_category to double-check this.

**Comment by ericl** [comment]
Hmm but the backlog reporting should be independent of this right? Unless
somehow the core worker is no longer reporting the full backlog of tasks in
some situations.

**Comment by jjyao** [comment]
Yea backlog reporting is independent. @iycheng we can do a pair debugging on this.

**Comment by scv119** [comment]
last time i investigated:

- there is a known bug where we could over reporting if we have some shapes waiting in both in cluster_task_manager and local_task_manager's pending queue. 
- if worker reports backlog to local raylet but lease client from remote raylet due to locality based scheduling, there will be under report.

**Comment by jjyao** [comment]
> if worker reports backlog to local raylet but lease client from remote raylet due to locality based scheduling, there will be under report.

Could you elaborate on this?

**Comment by scv119** [comment]
yeah the back log reporting requires 
- the shape in both tasks queues (either cluster_task_manager/local_tasks_manager) 
- also the backlogs itself.
this [logic](https://sourcegraph.com/github.com/ray-project/ray/-/blob/src/ray/raylet/scheduling/scheduler_resource_reporter.cc?L129)
so if the client report the backlogs to local raylet but send tasks to remote raylet looks we have under reporting.

**Comment by iycheng** [comment]
I think the root cause is here: https://sourcegraph.com/github.com/ray-project/ray/-/blob/src/ray/core_worker/transport/direct_task_transport.cc?L302-307

It seems like when it reaches the max ones, it won't add it to the scheduling queue, so it's capped to 10. 

But I'm not sure how at the beginning before workers are up, it's > 10.

**Comment by jjyao** [comment]
We also report backlog periodically so even that function is early returned (also this function won't early return forever, once a lease is granted, a new lease will be requested), we still have the chance to report backlog: https://sourcegraph.com/github.com/ray-project/ray/-/blob/src/ray/core_worker/core_worker.cc?L723

**Comment by iycheng** [comment]
@jjyao  I think it's about this line https://sourcegraph.com/github.com/ray-project/ray/-/blob/src/ray/core_worker/transport/direct_task_transport.cc?L488

Pending lease request is not added. It's not about the backlog is not reported but about it doesn't include the pending request.

**Comment by iycheng** [comment]
It seems like local reporting is correct:
```
[2022-02-24 22:03:14,996 I 6687 6712] raylet_client.cc:323: ReportWorkerBacklog: {"workerId":"AQAAAP///////////////////////////////w==","backlogReports":[{"resourceSpec":{"name":"foo()","functionDescriptor":{"pythonFunctionDescriptor":{"moduleName":"test","functionName":"foo","functionHash":"c373934b223441b5b7ea7370fab1af88"}},"jobId":"AQAAAA==","taskId":"uiTdn7N8MoD///////////////8BAAAA","parentTaskId":"//////////////////////////8BAAAA","parentCounter":"10000","callerId":"//////////////////////////8BAAAA","callerAddress":{"rayletId":"0597aUshNnz7pblSEwbmWzkMFq6wWT3Nf/RyjQ==","ipAddress":"172.31.48.33","port":10002,"workerId":"AQAAAP///////////////////////////////w=="},"numReturns":"1","requiredResources":{"CPU":1},"maxRetries":3,"runtimeEnvInfo":{"serializedRuntimeEnv":"{}"},"depth":"1","schedulingStrategy":{"defaultSchedulingStrategy":{}}},"backlogSize":"9910"}]}
```
I'll check GCS aggregation.

**Comment by iycheng** [comment]
Have a fix, I need to add test for it.
