### ISSUE TITLE
[release] No way to run C++ wheels sanity check on Windows

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#22131]
Currently the release process involves running https://github.com/ray-project/ray/blob/master/release/util/pip_download_test.sh

For Windows, the release manager has to execute the steps in this script manually.  

For the non-C++ sanity check this is okay; the release manager can create isolated conda environments to test each wheel and then run `python sanity_check.py` in each environment.

However, the C++ sanity check involves running `bash sanity_check_cpp.sh`.  https://github.com/ray-project/ray/blob/master/release/util/sanity_check_cpp.sh
This in turn calls some more shell scripts which are not Windows-compatible.   I'm not sure if we need to write a `.bat` version of this script of if there's some easy workaround.

**Comment by architkulkarni** [comment]
cc @SongGuyang @mwtian for awareness.  I would guess this is low priority because the intersection of Windows users and C++ users is small.

**Comment by SongGuyang** [comment]
@architkulkarni Thank you for adding this. It could be assigned to @qicosmos

**Comment by architkulkarni** [comment]
I believe this is still an issue. cc recent release manager @scv119, feel free to close if no longer an issue

**Comment by cadedaniel** [comment]
I got `pip_download_test.sh` to work on windows with the following commands:

powershell
```ps1
# Install chocolatey
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# install git bash
choco install git.install --params "'/WindowsTerminal /NoAutoCrlf'"

# install anaconda
choco install anaconda3 -y --force --params '"/JustMe /AddToPath"'
```

git bash
```bash
conda init bash

# Restart terminal now
# Remove 3.6 from pip_download_test.sh now
# It will work now
RAY_HASH=47a077655b2efaf4c561fdc70a071c02f854cec1 RAY_VERSION=2.3.0rc0 ./pip_download_test.sh

```

**Comment by architkulkarni** [comment]
> I got pip_download_test.sh to work on windows with the following commands. the cpp wheels don't support windows so you'll need to comment out the cpp tests.

Seeing the following errors when I try to run it:

```
C:\tools\Anaconda3/etc/profile.d/conda.sh: line 9: /cygdrive/c/tools/Anaconda3/Scripts/conda.exe: No such file or directory
``` 

and 

```
ERROR: To modify pip, please run the following command:
C:\tools\Anaconda3\python.exe -m pip install --upgrade pip
```

It also prints things like 

```
=========================================================
Python version.
Python 3.11.5
This should be equal to 3.9
=========================================================
```

I guess because none of the conda commands are working.
