### ISSUE TITLE
[Datasets] [Feature] Support scalar column --> tensor column conversions

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#22139]
We should support the trivial scalar column --> tensor column conversions, creating a single-element-per-row tensor column. Right now, we don't have any test coverage for this conversion, and users are hitting some odd edge cases.

**Comment by tgaddair** [comment]
Thanks for creating this issue @clarkzinzow. It appears in Ray 1.10 there is an issue with boolean arrays that extends beyond scalars. Here's an issue with converting a column of boolean vectors:

```
import pandas as pd
import ray
from ray.data.extensions import TensorDtype

ray.init()

df = pd.DataFrame({"test": [[False, True, True], [True, False, True], [False, False, True]]})
data = ray.data.from_pandas(df)


def to_tensors(df: pd.DataFrame) -> pd.DataFrame:
    for c in df.columns:
        df[c] = df[c].astype(TensorDtype())
    return df


def batch_predict(df: pd.DataFrame) -> pd.DataFrame:
    return df
    

dask_dataset = (
    data
    .map_batches(to_tensors, batch_format="pandas")
    .map_batches(
        batch_predict, batch_size=32, compute="actors", batch_format="pandas", num_gpus=0
    )
    .to_dask()
)
```

This raises the exception: `TypeError: buffer is too small for requested array`

**Comment by clarkzinzow** [comment]
@tgaddair Thank you for finding a reproduction! I'll open up a dedicated issue for that.
