### ISSUE TITLE
Support multiple workers per process

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#2215]
Currently, Ray only supports one worker per process. This is okay with Python workers, because:
1) Workers don't share much resources with each other;
2) Multi-threading is inefficient in Python (CPython, to be more specific), because of GIL.

However, as Java worker has been introduced, this becomes an issue.
Because in a Java process, JVM itself costs significant amount of memory overhead. Using multi-processes means duplicating the overhead. 

For the short term, I'll work on supporting one worker per thread. 
For the long term, we can even use coroutines to make each worker very light-weight.

**Comment by robertnishihara** [comment]
@raulchen thanks, this is very important. Multi-threading (with a small number of threads) should be very straightforward to support as long as each worker has its own object store and raylet clients, right?

I like the idea of using co-routines. However, this would require API changes, right? E.g., in Python it would require tasks to use an event loop, right? How would this work in Java?

However, please do all changes in the **raylet** code path and not in the old **local scheduler** code path. The reason for this is that we are trying to get rid of the old code path as soon as possible, so it doesn't make sense to invest more energy in that part of the codebase.

If you are planning substantial code changes, then perhaps we should discuss the design.

**Comment by raulchen** [comment]
hi @robertnishihara, sorry that I missed your comment.

First, yes, it's a straightforward change, if each worker still has its own object store and raylet client (see my RP #2244). 
But in order to make it more scalable, I think it makes sense to have multiple workers share one connection in the future. However, that would require larger code changes, because right now the a lot of code in node manager looks up the worker by its connection, rather than by an unique id. 
So, let's see how #2244 works and decide wether to make the change afterwards. 

Regarding the API change to support coroutines in Python, what needs to be done is to make all the APIs async compatible (which means make all the underlying IO async and `async def` all functions) (I found there's already an issue discussing this topic #493).

Then the worker will be something like this:
```python
class Worker:
    async def loop(self):
        while True:
            task = await self.get_next_task()
            await self.execute_task(task);
```
And that requires users to define their tasks as async functions as well.

I didn't dig deeply into supporting coroutine in Java. After all, multi-threading is much more common in Java than coroutines. And I think it's okay that each language has its own concurrency model. The core doesn't need to know about this.
