### ISSUE TITLE
[Bug] DDPPO training_batch_size ValueError

### ISSUE THREAD

**Issue by dsctt** [ray-project/ray#22150]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### What happened + What you expected to happen

When running DDPPO, getting this error `ValueError: Set rollout_fragment_length instead of train_batch_size for DDPPO.` from https://github.com/ray-project/ray/blob/ray-1.10.0/rllib/agents/ppo/ddppo.py#L128

### Versions / Dependencies

Ray=1.10.0
Python=3.9.7
OS=Ubuntu 20.04.3 LTS

### Reproduction script

```
from ray import tune

# Configure the algorithm.
config = {
    "num_gpus_per_worker": 0,
    "num_gpus": 0,
    # Environment (RLlib understands openAI gym registered strings).
    "env": "Taxi-v3",
    # Use 2 environment workers (aka "rollout workers") that parallelly
    # collect samples from their own environment clone(s).
    "num_workers": 2,
    # Change this to "framework: torch", if you are using PyTorch.
    # Also, use "framework: tf2" for tf2.x eager execution.
    "framework": "torch",
    # Tweak the default model provided automatically by RLlib,
    # given the environment's observation- and action spaces.
    "model": {
        "fcnet_hiddens": [64, 64],
        "fcnet_activation": "relu",
    },
    # Set up a separate evaluation worker set for the
    # `trainer.evaluate()` call after training (see below).
    "evaluation_num_workers": 1,
    # Only for evaluation runs, render the env.
    "evaluation_config": {
        "render_env": True,
    "evaluation_interval": 1,
    },
}

tune.run(
    "DDPPO",
    config=config
)

# Evaluate the trained Trainer (and render each timestep to the shell's
# output).
trainer.evaluate()
```

### Anything else

Occurs every time. It appears to me that there are two passes going through this line https://github.com/ray-project/ray/blob/ray-1.10.0/rllib/agents/ppo/ddppo.py#L123. On the first pass, the `train_batch_size=-1` and it continues to then get set to another value in the following lines. On the second pass, it is now equal to the new value so it fails, giving the `ValueError`.
cc @jsuarez5341 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jsuarez5341** [comment]
@sven1977 This is part of the NMMO integration effort -- up there with APPO/Impala, as this would enable CPU-only training for small nets

**Comment by dsctt** [comment]
Was able to get the reproduction script working by setting `evaluation_num_workers=0` and also removing `evaluation_interval` from the config. This is my understanding of why the error was thrown:

1) `validate_config` is called here https://github.com/ray-project/ray/blob/ray-1.10.0/rllib/agents/trainer.py#L781
2) This changes the `train_batch_size` in the config from -1 to a new value here https://github.com/ray-project/ray/blob/ray-1.10.0/rllib/agents/ppo/ddppo.py#L124
3) The config is merged with the `user_eval_config` to create `eval_config` in line 860 of `trainer.py`
4) If you have `evaluation_num_workers` set to > 0 or `evaluation_interval set`, then the `eval_config` is sent through `validate_config` (again, partially) in line 868 of trainer.py. Since `train_batch_size` was passed through already, it is no longer -1 and will throw the error on line 128 of ddppo.py.

So either the user is not supposed to set `evaluation_num_workers` or `evaluation_interval`, or some way of not calling `validate_config` twice / allowing `ddppo.py` to handle it would have to go in.
