### ISSUE TITLE
ValueError: RolloutWorker has no `input_reader` object! Cannot call `sample()`. You can try setting `create_env_on_driver` to True.

### ISSUE THREAD

**Issue by amohazab** [ray-project/ray#22168]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### What happened + What you expected to happen

Hello everyone,
I am trying to run a APEX_DDPG with tune on a multi-agent environment with Ray v1.10 on Python 3.9.6. 
I get the following error:

**raise ValueError("RolloutWorker has no `input_reader` object! "
ValueError: RolloutWorker has no `input_reader` object! Cannot call `sample()`. You can try setting `create_env_on_driver` to True.**

status:
Current time: 2022-02-07 10:48:24 (running for 00:00:39.84)
Memory usage on this node: 13.0/15.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/4.27 GiB heap, 0.0/2.14 GiB objects
Result logdir: C:\Users\mohazaa1\ray_results\PPO
Number of trials: 1/1 (1 ERROR)
--------------------
Trial name | status | loc
--------------------- | ------- | ----------------
PPO_9e690_00000 | ERROR | 127.0.0.1:16836

I found the source of the error, which is in  RolloutWorker class definition :

 if self.fake_sampler and self.last_batch is not None:
            return self.last_batch
        elif self.input_reader is None:
            raise ValueError("RolloutWorker has no `input_reader` object! "
                             "Cannot call `sample()`. You can try setting "
                             "`create_env_on_driver` to True.")

But I do not know how to solve it!
sorry I am a little bit new to RLlib.

### Versions / Dependencies

Ray v1.10
Python  3.9.6
Windows 10

### Reproduction script

# I want to simulate a multi-unit auction framework. I first create a gym-based environment for each #User (bidder), who are independent from each other. We then create a multi-agent environment #(MultiUnitAuction) to go through the users, #get their bid values and clear the market. 
# We have 20 agents and 7 items.

class User(gym.Env):
    def __init__(self , marginal_value , max_marginal_value):
        self.marginal_value = marginal_value
        self.max_marginal_value = max_marginal_value
        self.action_space = gym.spaces.Box(low=np.array([0]), high=np.array([self.marginal_value]), dtype=np.float32)
        self.observation_space = gym.spaces.Box(low = np.array([0]), high = np.array([self.max_marginal_value]), dtype=np.float32)
 
    def step(self , bid, p_c):
        if bid >= p_c:
            return p_c , self.marginal_value-bid , False , {}
        else:
            return p_c , 0 , False , {}
        
    def reset(self):
        pass

class MultiUnitAuction(MultiAgentEnv):
    def __init__(self , num_agents , block_size):
        super().__init__()
        #get a vector of marginal valuations:
        marginal_valuation_vector = [1 , 3 , 4 , 4 , 4 , 71,7, 56, 88,16, 25, 32, 39, 12, 48, 10,40,14,12,30]
        #define a counter to end the episode
        #self.counter = 0
        #number of agents
        self.num_agents = num_agents
        #block_size
        self.block_size = block_size
        #define agents
        self.agents = [User(i , max(marginal_valuation_vector)) for i in marginal_valuation_vector]
        self.dones = set()
        self.observation_space = gym.spaces.Box(low=np.array([0]), high=np.array([max(marginal_valuation_vector)]), dtype=np.float32)
        self.action_space = gym.spaces.Dict({
            str(i) : gym.spaces.Box(low=np.array([0]), high=np.array([marginal_valuation_vector[i]]), dtype=np.float32) for i in range(0,self.num_agents)
        })
            
        
    def step(self , action_dict):
        obs , rew , done, info = {} , {} , {} , {}
        bids = []
        for i, action in action_dict.items():
            bids.append(action)
        
        p_c = sorted(bids)[len(bids) - self.block_size]
        
        for i, action in action_dict.items():
            obs[i], rew[i], done[i], info[i] = self.agents[int(i)].step(action , p_c)
        done["__all__"] = len(self.dones) == len(self.agents)
        
        return obs , rew , done , info
    
    def render(self):
        pass
    def reset(self):
        pass
        
tune.run(
        "APEX_DDPG",
        checkpoint_freq=10,
        config={
    "num_workers": 4,
    "create_env_on_driver": True,
    "multiagent": {
        "policies": {
            # the first tuple value is None -> uses default policy
            str(i): (None , test_env.agents[i].observation_space , test_env.agents[i].action_space , {"gamma": 0.9}) for i in range(0 , test_env.num_agents)},
        "policy_mapping_fn": (lambda agent_id, episode, **kwargs: select_policy) #select_policy
    },
})

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by oliverwang15** [comment]
@amohazab  Hi,I' m also new to Ray and RLlib. I also encounter this error today. My problem is that I forgot to add my `env` to `config`. You may try adding you environment to you `config` before using `ApexDDPGTrainer(config=config)` or using `ray.tune(config=config)`

The following is an example from [ray's official doc](https://docs.ray.io/en/latest/rllib-env.html#configuring-environments):
``` python
import gym, ray
from ray.rllib.agents import ppo

class MyEnv(gym.Env):
    def __init__(self, env_config):
        self.action_space = <gym.Space>
        self.observation_space = <gym.Space>
    def reset(self):
        return <obs>
    def step(self, action):
        return <obs>, <reward: float>, <done: bool>, <info: dict>

ray.init()
trainer = ppo.PPOTrainer(env=MyEnv, config={
    "env_config": {},  # config to pass to env class
})
```
You may also register your custom environment first:
``` python
from ray.tune.registry import register_env

def env_creator(env_config):
    return MyEnv(...)  # return an env instance

register_env("my_env", env_creator)
trainer = ppo.PPOTrainer(env="my_env")

**Comment by alhussein-jamil** [comment]
I encountered this problem when trying to make an evaluation worker : 
I simply had to specify 
`create_env_on_local_worker= True
`
hope this helps
