### ISSUE TITLE
[Bug] compatibility with aioredis >=2

### ISSUE THREAD

**Issue by h-vetinari** [ray-project/ray#22169]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

aioredis 2.0 was incompatible with current ray (#17462) and pinned in #17465. This is not a longterm-sustainable solution, hence this issue.

**Comment by rkooo567** [comment]
We will remove aioredis from the dependency soon. Cc @mwtian

**Comment by InbarShirizly** [comment]
> We will remove aioredis from the dependency soon. Cc @mwtian

any update about this matter? 🙏

**Comment by InbarShirizly** [comment]
any update here @rkooo567 ? thanks

**Comment by rkooo567** [comment]
I think this is removed!
