### ISSUE TITLE
[Bug] dataset_ingest_400G failed in master

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#22176]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2676#adf28a1c-2dbc-4e06-bfed-e43fafbea372

```
(remote_read pid=1225) [2022-02-07 04:20:03,942 E 1225 1225] plasma_store_provider.cc:122: Failed to put object 641e079764274441ffffffffffffffffffffffff0200000001000000 in object store because it is full. Object size is 219375455268 bytes.
--
  | (remote_read pid=1225) Plasma store status:
  | (remote_read pid=1225)
  | (remote_read pid=1225) (global lru) capacity: 78466815590
  | (remote_read pid=1225) (global lru) used: 0%
  | (remote_read pid=1225)


```

### Versions / Dependencies

master

### Reproduction script

core nightly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
```
plasma_store_provider.cc:122: Failed to put object 641e079764274441ffffffffffffffffffffffff0200000001000000 in object store because it is full. Object size is 219375455268 bytes.
```

note the object size is 200GB

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/22177
