### ISSUE TITLE
[Bug] datasets_preprocess_ingest failed in master due to pyarrow==7.0.0

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#22177]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

https://buildkite.com/ray-project/periodic-ci/builds/2676#65781171-8c7f-4d05-a638-018f400047d0

### Versions / Dependencies

master

### Reproduction script

core nightly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
```
[2022-02-07 10:53:22,808 E 268 268] plasma_store_provider.cc:122: Failed to put object a631fe8d231813bfffffffffffffffffffffffff0100000001000000 in object store because it is full. Object size is 753667402583 bytes.
```
this is even more crazier: 753GB

**Comment by ericl** [comment]
Hmm I suspect that there's something wrong with pandas block split() implementation. If this is the case, turning off the enabled flag should fix it.

**Comment by ericl** [comment]
From https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

```
While Index objects are copied when deep=True, the underlying numpy array is not copied for performance reasons. Since Index is immutable, the underlying data can be safely shared and a copy is not needed.
```

This seems to indicate deepcopy may not actually decouple the returned array fully from the base data. So random_shuffle() could cause O(n^2) data blowup if each slice is including a reference to the full base data.

**Comment by ericl** [comment]
Duplicate issue of https://github.com/ray-project/ray/issues/22161

**Comment by scv119** [comment]
Turns out it's to do with pyarrow 7.0.0. This bug happens if pyarrow==7.0.0 and not reproducible if pyarrow==5.0.0
