### ISSUE TITLE
[Bug] Could install ray on Docker

### ISSUE THREAD

**Issue by abhalawat** [ray-project/ray#22212]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### What happened + What you expected to happen

It gave the error:

```
Sending build context to Docker daemon  493.1kB
Step 1/8 : FROM python:latest
 ---> e2e732b7951f
Step 2/8 : RUN pip install -U ray
 ---> Running in f7ff65c23bbf
ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -U ray' returned a non-zero code: 1
```

### Versions / Dependencies

Python 3.8.10
Ray 1.10.0
Ubuntu 20.04.3 LTS

### Reproduction script

```
#Deriving the latest base image
FROM python:latest

RUN pip install -U ray

#Labels as key value pair
LABEL Maintainer="Aditi"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /ERC20_token

COPY requirements.txt requirements.txt
RUN pip install -Ur requirements.txt
#to COPY the remote file at working directory in container
COPY app.py ./
# Now the structure looks like this '/usr/app/src/test.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python3", "./app.py"]
```

### Anything else

I basically create a python code ,now want it to be an docker image and as under docker file we can only extract one image so ,I extracted python image .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Hey @abhalawat are you sure you're using Python 3.8? The `python:latest` image has python 3.10, which Ray does not have support for yet. #21221

**Comment by abhalawat** [comment]
Got your point.I had specify versions of both ray and python
