### ISSUE TITLE
[train] Add `load_checkpoint()` and `best_checkpoint` to `Trainer`

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#22226]
After training a model, we should expose utilities so that the user can load their best checkpoint in memory.

1. `Trainer.load_checkpoint(path)` to load an arbitrary checkpoint.
2. `trainer.best_checkpoint` to load `trainer.best_checkpoint_path` into memory.

**Comment by Stergios13** [comment]
Hello! i am happy to contribute to this issue!
