### ISSUE TITLE
[Jobs] Resolve inconsistent uses of `RAY_ADDRESS`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#22221]
`RAY_ADDRESS` is used both for Ray Client and Ray Job Submission, with different ports.  We should ideally have two different environment variables for these use cases.

Also: after https://github.com/ray-project/ray/pull/21938, the user may no longer need to manually set RAY_ADDRESS because the bootstrap address from the running cluster should automatically get read.  Verify this and update the docs accordingly.

**Comment by d4l3k** [comment]
Is setting ray address not needed at all any more even when running with a remote cluster?

The other thing is that RAY_ADDRESS is read by both `ray.init` and by job submission API but the format for the two usages is different. ray.init needs `RAY_ADDRESS=auto` or `RAY_ADDRESS=ray://...` but job submission API `RAY_ADDRESS=http://...` for the dashboard address

Are there plans to resolve this inconsistency? We'd like to be able to use the same env variable for both

**Comment by architkulkarni** [comment]
You're right, `RAY_ADDRESS` would still be needed when running with a remote cluster.  

But even if using the same format, you wouldn't be able to use the same environment variable, because the ports would be different (you'd need `ray://...:10001` to connect with Ray Client, and `ray://...:8265` to connect to the Job Submission server.).  

Our thought here was to prevent confusion by exclusively using `ray://` for Ray Client connections, and `http://` for API servers such as the Job Submission and Ray Serve REST API.  What do you think?

**Comment by d4l3k** [comment]
As a user I don't understand why they're different tbh -- seems like they could all go through one port and it'd make it way simpler to reason about. Or if two ports are necessary have one be discoverable by making a request to the other port so it's always exposed the same way

I'd be for splitting this into "RAY_ADDRESS" and "RAY_JOB_ADDRESS" to reduce confusion. Having a standard environment variable is nice though since it would make the integration into TorchX much easier and more comparable to how other schedulers such as Kubernetes/AWS/etc use the environment config

**Comment by salotz** [comment]
I still don't understand what the final solution is for this. The documentation in different is all over the place and its super confusing and not even sure its possible to do something like:

```sh
export RAY_ADDRESS="..."
ray list nodes
ray job submit

python -c "import ray; ray.init()
```

My suggestion is to make a different environment variable for each possible API/port that gets exposed, e.g.:

- `RAY_API_ADDRESS` for `8265`
- `RAY_JOBS_ADDRESS` for ??
- `RAY_CLIENT_ADDRESS` for 10001
- etc.

And clearly document for each the URL format that is accepted.
If it accepts the `ray://` protocol please explain what this is actually doing.
Also please explain for cases with RayCluster with custom ingresses how to write URLs for specific clusters, if that is even needed.

I think once you have these individual final overrides you can work on/implement a "catch-all" `RAY_ADDRESS` which magically does what you want based on good defaults on port numbers (or some config file that overrides port designations).

This allows for maximum flexibility for end users. Perhaps I want to firewall certain ports and allow  the `/list/nodes` API but not the Jobs, Client API. And in another allow autoscaling, etc.
