### ISSUE TITLE
[Bug] No such file or directory: 'python/ray/_raylet.pyx'

### ISSUE THREAD

**Issue by AprilXiaoyanLiu** [ray-project/ray#22252]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

After my agent completed training, it showed error FileNotFoundError: [Errno 2] No such file or directory: 'python/ray/_raylet.pyx'

### Versions / Dependencies

Python==3.6
Ray[RLLib]==1.3.0

### Reproduction script

The script is just standard RLLib PPO training with customized scripts 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
what happens if you run `pip install ray`?

**Comment by gjoliver** [comment]
closing this issue for lack of updates.
also please use more recent version of RLlib :)
