### ISSUE TITLE
[Bug] Serve shutdown does not work for detached serve instance

### ISSUE THREAD

**Issue by saswatac** [ray-project/ray#22254]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

Trying to shutdown a detached ray serve instance using `serve.shutdown` does not work.

### Versions / Dependencies

ray==1.10.0

python=3.8.0

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"

### Reproduction script

```
import ray
ray.init(address="ray://example-cluster-ray-head.ray:10001", namespace="x")
from ray import serve
serve.shutdown()
```

### Anything else

The problem is resolved if another serve API is called before shutdown

```
import ray
ray.init(address="ray://example-cluster-ray-head.ray:10001", namespace="x")
from ray import serve
serve.list_deployments()
serve.shutdown()
```

I think this if clause is unnecessary and it is what is causing the bug - https://github.com/ray-project/ray/blob/master/python/ray/serve/api.py#L703

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Hi @shrekris-anyscale, can I assign this issue to you?  Do you think you have enough context to investigate it?

**Comment by shrekris-anyscale** [comment]
Hi @architkulkarni, yes go ahead.
