### ISSUE TITLE
Document when a "results" folder for Tune checkpoint looks like so users know which path to use

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#22267]
`analysis = ExperimentAnalysis(best_checkpoint_dir)`

https://docs.ray.io/en/latest/tune/api_docs/analysis.html#experimentanalysis-tune-experimentanalysis

otherwise it's easy to not know exactly which part of path to use

**Comment by Yard1** [comment]
The current description seems enough, no? I guess the name of the argument itself is the most misleading.

**Comment by worldveil** [comment]
Just looked again, and I can buy that the description in the docstring is good enough. closing.
