### ISSUE TITLE
[Feature] add a callback to be called after each evaluation cycle

### ISSUE THREAD

**Issue by carlogrisetti** [ray-project/ray#22279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

A callback function that will allow to run custom code after the evaluation cycle completes

### Use case

Logging in tensorboard a custom metric on the evaluation process.
This is already doable with the training portion, but there is no actual way to do this on the evaluation results.

My custom environment has some additional results I would want to trace\graph\use, and the most important partition is the one generated in the evaluation step, not on the training step.

### Related issues

Couldn't find any similar issue

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by carlogrisetti** [comment]
Can anyone at least point me in the right direction to try and cobble up a PR introducing this callback?
It would be very helpful :)

**Comment by gjoliver** [comment]
adding a callback is actually extremely simple, for examle:
https://github.com/ray-project/ray/pull/22493
let me know if you want to give this a try :)

**Comment by AurelianTactics** [comment]
If I'm following the ray documentation and examples correctly there are three main steps to adding a callback after evaluations:
* Extend the functionality of the class DefaultCallbacks in callbacks.py. Example: https://github.com/AurelianTactics/ray/blob/eval-callback/rllib/agents/callbacks.py#L296
* Call that new method of DefaultCallbacks somewhere. I wasn't really sure about where to put that that so I put the callback in trainer.py after the evaluate function. https://github.com/AurelianTactics/ray/blob/eval-callback/rllib/agents/trainer.py#L1389
* Create your own custom callback that inherits from DefaultCallbacks and pass that to a trainer or tune object (I'm working on an example that is easier to share). The example I am working on internally works (I think) in that it gets results after the evaluation ends but there's a memory leak issue which may or may not be related.

**Comment by sven1977** [comment]
Hey @AurelianTactics , great stuff. Would you be willing to send us a PR that adds this required callback (after evaluation step) to the DefaultCallbacks class and makes our Trainers utilize it?

**Comment by carlogrisetti** [comment]
That would be awesome... I haven't yet had time to look into that, but it would be really nice to have. Thanks @AurelianTactics !

**Comment by AurelianTactics** [comment]
I'm stuck on how to test this. In other projects I've submitted pull requests to the process was different. I downloaded, installed, and tested from my fork. I'm not sure how to do that with ray. Am I supposed to follow the instructions here? https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-python-only 

If so, I'm unable to get the ray installation to read from my branch. I opened up a new AWS EC2 instance. I installed ray using the wheel for 3.6:
`pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl`

I installed the dependencies of my example
`pip install gym dm_tree`

I tested the example my example is based off on:
`python /opt/conda/lib/python3.6/site-packages/ray/rllib/examples/custom_metrics_and_callbacks.py --stop-iters 2 --framework torch`

I cloned my repo
`git clone https://github.com/AurelianTactics/ray.git --branch eval-callback`

I try to remove the dependency from the ray installation and so it points to my code:
```
cd ray
git remote add upstream https://github.com/ray-project/ray.git
python python/ray/setup-dev.py
```

Then when I try to run my example, it fails:
`python rllib/examples/custom_metrics_and_callbacks_on_evaluate_end.py --stop-iters 2 --framework torch`

I'm not sure what is going on with the error. Maybe it's still looking at the site-packages code and not my fork?

Failure # 1 (occurred at 2022-04-27_13-27-24)
^[[36mray::PGTrainer.train()^[[39m (pid=375, ip=172.17.0.2, repr=PGTrainer)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trainable.py", line 360, in train
    result = self.step()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1097, in step
    raise e
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1078, in step
    step_attempt_results = self.step_attempt()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1164, in step_attempt
    step_results = self._exec_plan_or_training_iteration_fn()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 2177, in _exec_plan_or_training_iteration_fn
    results = self.training_iteration()
  File "/opt/conda/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 1425, in training_iteration
    new_sample_batches = synchronous_parallel_sample(self.workers)
TypeError: synchronous_parallel_sample() takes 0 positional arguments but 1 was given

**Comment by carlogrisetti** [comment]
You might want to update your branch from master, since there are many occurrences where issues are already fixed before you encounter them, and you've been left behind on your own branch.

I'm not confident enough on the dev setup procedure to help you on that, sorry! :(

Once you pass some quick internal tests you might also want to submit a PR and let the more extensive CI tests run.
