### ISSUE TITLE
Dependencies should be optional

### ISSUE THREAD

**Issue by elyase** [ray-project/ray#2229]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 3.6.3
- **Exact command to reproduce**:
```python
import ray
import ray.tune as tune

@ray.remote
def train_func(config, reporter):
    reporter(timesteps_total=1, mean_accuracy=1)

#ray.init()
tune.register_trainable("train_func", train_func)

tune.run_experiments({
    "my_experiment": {
        "run": "train_func",
        "stop": {"mean_accuracy": 99},
        "config": {
            "lr": tune.grid_search([0.2, 0.4, 0.6]),
            "momentum": tune.grid_search([0.1, 0.2]),
        }
    }
})
```

### Describe the problem

At run time Ray requires many dependencies like `gym` and `cv2` that are not needed in every project/algorithm. It would be better if simpler algorithms (e.g.: random search) were dependency free At the very least this behaviour should be documented.

### Source code / logs

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-398c5fad922b> in <module>()
     16         "config": {
     17             "lr": tune.grid_search([0.2, 0.4, 0.6]),
---> 18             "momentum": tune.grid_search([0.1, 0.2]),
     19         }
     20     }

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/tune/tune.py in run_experiments(experiments, scheduler, with_server, server_port, verbose)
     51 
     52     # Make sure rllib agents are registered
---> 53     from ray import rllib  # noqa # pylint: disable=unused-import
     54 
     55     if scheduler is None:

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/__init__.py in <module>()
     15 
     16 
---> 17 _register_all()

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/__init__.py in _register_all()
     12                 "__sigmoid_fake_data", "__parameter_tuning"]:
     13         from ray.rllib.agent import get_agent_class
---> 14         register_trainable(key, get_agent_class(key))
     15 
     16 

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/agent.py in get_agent_class(alg)
    224 
    225     if alg == "PPO":
--> 226         from ray.rllib import ppo
    227         return ppo.PPOAgent
    228     elif alg == "ES":

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/ppo/__init__.py in <module>()
----> 1 from ray.rllib.ppo.ppo import (PPOAgent, DEFAULT_CONFIG)
      2 
      3 __all__ = ["PPOAgent", "DEFAULT_CONFIG"]

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/ppo/ppo.py in <module>()
     15 from ray.rllib.agent import Agent
     16 from ray.rllib.utils import FilterManager
---> 17 from ray.rllib.ppo.ppo_evaluator import PPOEvaluator
     18 from ray.rllib.ppo.rollout import collect_samples
     19 

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/ppo/ppo_evaluator.py in <module>()
     14 from ray.rllib.optimizers import PolicyEvaluator, SampleBatch
     15 from ray.rllib.optimizers.multi_gpu_impl import LocalSyncParallelOptimizer
---> 16 from ray.rllib.models import ModelCatalog
     17 from ray.rllib.utils.sampler import SyncSampler
     18 from ray.rllib.utils.filter import get_filter, MeanStdFilter

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/models/__init__.py in <module>()
----> 1 from ray.rllib.models.catalog import ModelCatalog
      2 from ray.rllib.models.action_dist import (ActionDistribution, Categorical,
      3                                           DiagGaussian, Deterministic)
      4 from ray.rllib.models.model import Model
      5 from ray.rllib.models.fcnet import FullyConnectedNetwork

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/models/catalog.py in <module>()
     13 from ray.rllib.models.action_dist import (
     14     Categorical, Deterministic, DiagGaussian, MultiActionDistribution)
---> 15 from ray.rllib.models.preprocessors import get_preprocessor
     16 from ray.rllib.models.fcnet import FullyConnectedNetwork
     17 from ray.rllib.models.visionnet import VisionNetwork

~/.local/share/virtualenvs/ray_test-TB5l6Bm_/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py in <module>()
      2 from __future__ import division
      3 from __future__ import print_function
----> 4 import cv2
      5 import numpy as np
      6 import gym

ModuleNotFoundError: No module named 'cv2'
```

**Comment by ericl** [comment]
I think this is fixed in master, at least we shouldn't pull in any RLlib deps by default: https://github.com/ray-project/ray/blob/master/python/ray/tune/test/dependency_test.py

I don't think the patch is in the 0.4 release though.

**Comment by santiagoolivar2017** [comment]
I am noticing this behavior. I am using ray==0.8.3

`File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/tune.py", line 265, in run
    restore=restore)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/experiment.py", line 122, in __init__
    _raise_on_durable(self._run_identifier, sync_to_driver, upload_dir)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/experiment.py", line 33, in _raise_on_durable
    trainable_cls = get_trainable_cls(trainable_name)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/registry.py", line 28, in get_trainable_cls
    validate_trainable(trainable_name)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/registry.py", line 35, in validate_trainable
    from ray import rllib  # noqa: F401
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/__init__.py", line 5, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/env/__init__.py", line 2, in <module>
    from ray.rllib.env.dm_env_wrapper import DMEnv
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/env/dm_env_wrapper.py", line 1, in <module>
    import gym
ModuleNotFoundError: No module named 'gym'
`

and I also get

`File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/tune.py", line 265, in run
    restore=restore)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/experiment.py", line 122, in __init__
    _raise_on_durable(self._run_identifier, sync_to_driver, upload_dir)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/experiment.py", line 33, in _raise_on_durable
    trainable_cls = get_trainable_cls(trainable_name)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/registry.py", line 28, in get_trainable_cls
    validate_trainable(trainable_name)
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/tune/registry.py", line 35, in validate_trainable
    from ray import rllib  # noqa: F401
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/__init__.py", line 5, in <module>
    from ray.rllib.env.base_env import BaseEnv
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/env/__init__.py", line 8, in <module>
    from ray.rllib.env.policy_client import PolicyClient
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/env/policy_client.py", line 12, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 11, in <module>
    from ray.rllib.env.atari_wrappers import wrap_deepmind, is_atari
  File "/opt/conda/envs/dynamic_dpdm/lib/python3.6/site-packages/ray/rllib/env/atari_wrappers.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
`
