### ISSUE TITLE
Hard to find example of doing middleware with Serve

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#22304]
Hard to find examples/docs around doing middleware w/ Serve. 

Was really difficult to even find that starlette integrated with Ray Serve.

No good examples. Can we point to a good example or integration path users could find? May only need to be link to external example.

Also, is this  (starlette) compatible with FastAPI or no?

**Comment by simon-mo** [comment]
How's the section? What does it miss? https://docs.ray.io/en/releases-1.9.2/serve/http-servehandle.html#enabling-cors-and-other-http-middlewares

**Comment by worldveil** [comment]
That is good. I just had a hard time finding it when searching via Google, probably because I was searching for "authentication". Maybe we just add that term, ie "middleware, like authentication or <example2>" kind of thing. 

just want it easy to find. and it's a one-line fix

**Comment by worldveil** [comment]
Can we also make clearer the relationship of FastAPI to starlette to newer users? Many tutorials out there reference FastAPI + Ray Serve, yet our documentation mostly calls for starlette

**Comment by worldveil** [comment]
thoughts here? or disagree we need to make clearer?
