### ISSUE TITLE
Issue on page /_modules/ray/tune/integration/pytorch_lightning.html

### ISSUE THREAD

**Issue by najaweed** [ray-project/ray#22314]
Problem raised because there no ''running_sanity_check'' in pytorch lightning Trainer , but "_run_sanity_check" 
please change  ''trainer.running_sanity_check''  into  ''trainer._run_sanity_check''

**Comment by amogkam** [comment]
@najaweed yes this has been changed in master: https://github.com/ray-project/ray/pull/21831, and this will be included in the Ray 1.11 release!

In the meantime you can install the Ray nightly wheels https://docs.ray.io/en/latest/installation.html#daily-releases-nightlies which include this change, or if you can downgrade to PTL 1.4 until the Ray 1.11 release.
