### ISSUE TITLE
[Dataset] ray failed to serialize pyarrow7.0.0 Tables 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#22310]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

See https://github.com/ray-project/ray/pull/22253#issuecomment-1034742274 and https://github.com/ray-project/ray/issues/22177 for more context.

TL;DR, when serialize pyarrow7.0.0 Tables, the serialization has wrong data size (as big as 200GBs). 

### Versions / Dependencies

pyarrow 7.0.0

### Reproduction script

python ray/release/nightly_tests/dataset/ray_sgd_runner.py --num-epochs 1 --smoke-test
with pyarrow 7.0.0 installed

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
Hmm interesting, @scv119 I tried to reproduce this locally and got ~the same high-water mark for object store utilization and number of bytes consumed by tasks when comparing `pyarrow==6.0.1` and `pyarrow==7.0.0`. 🤔

**Comment by ericl** [comment]
Here's a minimal repro. With pyarrow==6.0.1 it works fine. With 7.0, you get a 800GiB plasma allocated block...
```
import ray

ray.data.range_arrow(100e6, parallelism=1).write_parquet("/tmp/big")
ray.data.read_parquet("/tmp/big").show()
```

**Comment by ericl** [comment]
Inserting a copy() of the block seems to resolve the issue. Maybe there's some large sparse array that's allocated in the pyarrow object when read from parquet in pyarrow 7.0.0.

We can insert the copy as a workaround for that version, and file a bug upstream.

**Comment by clarkzinzow** [comment]
Interesting, I tried reading Parquet data and many different operation combinations and wasn't able to reproduce.

> We can insert the copy as a workaround for that version, and file a bug upstream.

I'll time-box an investigation this week and otherwise do as you suggest. Thank you for finding a repro!

**Comment by clarkzinzow** [comment]
After some thorough debugging, it looks like this is the [same bug](https://issues.apache.org/jira/browse/ARROW-10739) around serializing Arrow array slices-views on an underlying larger buffer. The core issue here is that Arrow's Parquet reader is creating chunked arrays whose chunks are each slice-views on an underlying contiguous buffer containing the entire chunked array, causing serialization of `N` chunks to copy the entire buffer `N` times.

Here is a minimal reproduction without involving Parquet (this fails in all Arrow versions):
```
In [1]: import pyarrow as pa

In [2]: base = pa.array(list(range(10000000)))

In [3]: chunked = pa.chunked_array([pa.Array.from_buffers(pa.int64(), 1000000, [None, base.buffers()[1]], offset=i * 1000000) for i in range(10)])

In [4]: len(pickle.dumps(base))
Out[4]: 80000148

In [5]: len(pickle.dumps(chunked))
Out[5]: 800000829
```

The change in Arrow 7.0.0 is that the created chunked array is all pointing at a single contiguous buffer; in past versions, a different backing buffer was created for each chunk.
```
In [5]: t = pa.table({"a": list(range(10000000))})
In [6]: pq.write_table(t, "test.parquet")
In [7]: t2 = pq.read_table("test.parquet")

In [8]: for chunk in t2["a"].chunks:
     ...:     print(chunk.buffers()[1].address)
     ...:
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
140413841182592
```
Here you can see that Arrow 6.0.1 created a different backing buffer for each chunk:
```
$ pip install pyarrow==6.0.1
$ ipython

In [1]: t = pq.read_table("test.parquet")

In [2]: for chunk in t["a"].chunks:
   ...:     print(chunk.buffers()[1].address)
   ...:
140596942995904
140596912532864
140596746389440
140596729610240
140596708642304
140596717033152
140596683476288
140596691865664
140596654113152
140596662507200
```

**Comment by ericl** [comment]
Great find. For (2), I think that sounds good if the implementation is fairly simple. Otherwise, we can add a smaller fix with the read logic.

Can you also file an Arrow issue for (3)?
