### ISSUE TITLE
placement_group_performance_test is slower than before

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#22322]
![image](https://user-images.githubusercontent.com/74173148/153681527-5ba98f2e-af3e-4c50-8d41-6819b336f68e.png)

It seems like placement group is slower than before. It started on this session https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_Tq5N2F7bgEueMZuLFYNLXtaC

It looks like not related to redisless ray since it's before the flag turns on.

**Comment by iycheng** [comment]
@rkooo567  could you take an initial investigation about this? it seems consistent slower than before.

**Comment by rkooo567** [comment]
wil finsh it by today

**Comment by rkooo567** [comment]
Very surprisingly it seems to be https://github.com/ray-project/ray/pull/22133

@scv119 do you have any clue?

**Comment by scv119** [comment]
hmm this test has no dependency on the microbenchmark script right? I can hard image these two are related.

**Comment by rkooo567** [comment]
Yeah that’s what I thought.. let me see if I can find anything tomorrow

**Comment by scv119** [comment]
ha the benchmark reuses the timeit from ray_microbenchmark_helpers
