### ISSUE TITLE
Cannot invoke actor methods from other threads

### ISSUE THREAD

**Issue by ICGog** [ray-project/ray#2234]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.4.0
- **Python version**: 2.7.12
- **Exact command to reproduce**:

### Describe the problem
I'm wrapping some ROS subscriber logic into a Ray actor. I register a ROS callback on a ROS pub/sub topic. The callback is invoked in another thread when a message is received. In the callback, I want to invoke other Ray actors, but I can't do it because Ray can only invoke other actors from the main thread. Unfortunately, I can't force ROS to invoke the callback in the main thread.

I discussed with @robertnishihara , and this limitation is because the Ray API is currently not thread safe. Could you please make the API thread safe?

### Source code / logs
At @robertnishihara suggestion, I've temporarily disabled the main thread check from here: [https://github.com/ray-project/ray/blob/1475600c818bca4ba75b3085f4e45e8762096406/python/ray/worker.py#L1088-L1092](https://github.com/ray-project/ray/blob/1475600c818bca4ba75b3085f4e45e8762096406/python/ray/worker.py#L1088-L1092)

However, it would be great if this issue could be sorted.

**Comment by robertnishihara** [comment]
@ICGog can you try out https://github.com/ray-project/ray/pull/2248 and see if that solves this problem for you?

**Comment by robertnishihara** [comment]
This should be addressed on the master by #2422. Also see related issue #2385.

If the issue persists, please let me know.
