### ISSUE TITLE
[Feature] Make deployment easier and support ray auto-scaling on Yarn

### ISSUE THREAD

**Issue by zjf2012** [ray-project/ray#22378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently, we can deploy ray workloads on Yarn via Skein which originates from Dask. In Dask, there is one more layer, dask-yarn, added on top of Skein to make deployment even easier. If we can add a similar layer, ray-yarn, on top of Skein, it will be more convenient for ray user. We can even support ray auto-scaling in "ray-yarn" based on Ray AutoScaler.

### Use case

Nowadays, there are still large number of groups using Yarn as their cluster resource manager. If we can support Yarn well in Ray, it will be easier for them to run Ray workloads along with their existing workloads.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by zjf2012** [comment]
@edoakes, what's your opinion? It seems that @jcrist had the same suggestion.

**Comment by zjf2012** [comment]
@edoakes, any comments?

**Comment by edoakes** [comment]
@zjf2012 yes, I think this would definitely be an improvement. The reason we originally went with recommending Skein was mostly due to resource constraints, we couldn't justify spending additional effort on it given the demand we saw from the community.

Is this something you would be willing to contribute?

**Comment by zjf2012** [comment]
> @zjf2012 yes, I think this would definitely be an improvement. The reason we originally went with recommending Skein was mostly due to resource constraints, we couldn't justify spending additional effort on it given the demand we saw from the community.
> 
> Is this something you would be willing to contribute?

yes, it's my pleasure to contribute it to community.
