### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hyaofeng** [ray-project/ray#22372]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

location: ray/autoscaler/_private/_kubernetes.py
method: fillout_resources_kubernetes
code:
    node_types = copy.deepcopy(config["available_node_types"])
    head_node_type = config["head_node_type"]
    for node_type in node_types:
......
        if node_types == head_node_type: 
            # we only autodetect worker type node memory resource
            autodetected_resources.pop("memory")

it always False for node_types == head_node_type 

### Versions / Dependencies

ray 1.9.0

### Reproduction script

none

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Can you update the title?
