### ISSUE TITLE
[Bug] breaking change in checkpoint save \ agent restore between 1.9.2 and 1.10.0

### ISSUE THREAD

**Issue by carlogrisetti** [ray-project/ray#22383]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, RLlib

### What happened + What you expected to happen

Ran some trainings with Ray Tune in 1.9.2 (and previous versions) with no issue at all, with a "vanilla" PPO trainer, without any custom model\architecture specified.

Trying to restore the same agent in Ray 1.9.2 works as expected, being then able to run everything
Trying to restore the same agent in Ray 1.10.0 gives out this error:

```
Traceback (most recent call last):
  File "C:\blabla\script.py", line 244, in run_inference
    agent.restore(checkpoint_path)
  File "C:\blabla\venv\lib\site-packages\ray\tune\trainable.py", line 467, in restore
    self.load_checkpoint(checkpoint_path)
  File "C:\blabla\venv\lib\site-packages\ray\rllib\agents\trainer.py", line 1823, in load_checkpoint
    self.__setstate__(extra_data)
  File "C:\blabla\venv\lib\site-packages\ray\rllib\agents\trainer.py", line 2443, in __setstate__
    self.workers.local_worker().restore(state["worker"])
  File "C:\blabla\venv\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 1346, in restore
    self.policy_map[pid].set_state(state)
  File "C:\blabla\venv\lib\site-packages\ray\rllib\policy\torch_policy.py", line 717, in set_state
    o.load_state_dict(optim_state_dict)
  File "C:\blabla\venv\lib\site-packages\torch\optim\optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

Seems there has been some structure change between 1.9.2 and 1.10.0 that prevents loading models saved with 1.9.2 into a 1.10.0 environment, and this could be a showstopper for people with a lot of agents\models trained on <1.10.0

### Versions / Dependencies

Ray 1.10.0
Python 3.7
Windows 10
Not related to any other libraries, since the bare agent.restore fails

### Reproduction script

Sorry for not having a script, but it's a normal ray.tune with ray.rllib.agents.ppo.PPOTrainer that then gets saved by the built-in saving mechanism, and finally gets restored with ray.rllib.agents.ppo.PPOTrainer.restore

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @carlogrisetti , sorry, but I was not able to reproduce this with PPO + torch + FrozenLake env. Generating a checkpoint with 1.9 and restoring with latest master worked just fine.
Could you post a repro script here? Thanks!

**Comment by carlogrisetti** [comment]
I will try to repro in a controlled environment and post a script or at least detailed instructions.
Sorry for this but I am having huge timing issues right now :)

**Comment by carlogrisetti** [comment]
Ok it definitely was an error in defining the custom model to be used. Sorry again.
