### ISSUE TITLE
local_mode not type stable

### ISSUE THREAD

**Issue by joschu** [ray-project/ray#2238]
It's unexpected behavior to me that the return type would depend on `driver_mode`. E.g., I was using ObjectID as a dictionary key, but the object that it pointed to was unhashable. This code breaks after switching to PYTHON_MODE.
```
In [1]: import ray
r
In [2]: ray.init(driver_mode=ray.PYTHON_MODE)
Out[2]: {'node_ip_address': None, 'redis_address': None}

In [3]: ray.put(1)
Out[3]: 1
```

**Comment by robertnishihara** [comment]
Thanks! Yeah, I think it would be better to return `ObjectID`s in Python mode. Similar complaint in #1155.

**Comment by robertnishihara** [comment]
Fixed by https://github.com/ray-project/ray/pull/5060.
