### ISSUE TITLE
[tune] remove `update_resources` from Trainable API

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#22392]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

Trainable.update_resources is not needed. 

@krfricke @Yard1 

### Versions / Dependencies

master

### Reproduction script

NA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Yard1** [comment]
+1, it is not necessary anymore.
