### ISSUE TITLE
Expose get timeout to python

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#224]
The timeout of get should be exposed to python so we can get control back to the interpreter if the object takes too long to compute or fetch.

**Comment by robertnishihara** [comment]
This could (almost) already be achieved by using

```python
ready_ids, _ = ray.wait(object_ids, timeout=...)
ray.get(ready_ids)
```

The differences are that

1. This involves a little more code.
2. This involves an extra IPC round trip to the object store.
3. Some of the objects corresponding to the object IDs in `ready_ids` could in principle be evicted from the object store between between the `ray.wait` and `ray.get` call, causing the `ray.get` call to block for a little while.

**Comment by robertnishihara** [comment]
Let's hold off on this for now. If there's a need for it, we can certainly add it in.

Right now, the main use case seems to be that you call `ray.get` in your interpreter and it's taking too long, so you want to do Ctrl-C to exit the get (it would require a lot of foresight to have thought to pass in a timeout ahead of time).
