### ISSUE TITLE
[Bug] Possible performance regression with TorchTrainer on Ray 1.9.2 (compared to Ray 1.6)

### ISSUE THREAD

**Issue by gmatev** [ray-project/ray#22405]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

**Context:** 
We have a benchmark test that is somewhat vanilla distributed training of Resnet on the Cats and Dogs Kaggle dataset. The test runs on a containerized version of Ray to perform distributed training. We run the test using GPUs and for cost reasons on CPUs. 

**Observation**
We have observed a non-trivial performance degradation when comparing the wall clock times between the version of the test (CPU and GPU) between Ray 1.6.0 and Ray 1.9.2 or later. Have not narrowed it down to a version in between. 

Here are some results summarizing the differences we see. Note that in 1.9.2 the training time per epoch seems to increase 

**Ray 1.6.0**

(0) | num_samples (1) | epoch (2) | batch_count (3) | train_loss (4) | last_train_loss (5) | start_ts (6) | end_ts (7) | profile.mean_train_epoch_s (8) | profile.mean_fwd_s (9) | profile.mean_grad_s (10) | profile.mean_apply_s (11)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 500040 | 0 | 44.0 | 0.7316540314630359 | 0.7283951070573594 | 2022-02-15 15:33:38.071996 | 2022-02-15 16:08:35.038999 | 2094.5568494796753 | 33.23912098407745 | 11.050184226036071 | 0.0004892587661743164
1 | 500040 | 1 | 44.0 | 0.7252435466473831 | 0.7186845958232879 | 2022-02-15 16:09:25.592997 | 2022-02-15 16:44:16.473100 | 2088.5956206321716 | 33.51775622367859 | 10.815592646598816 | 0.00048427581787109376
2 | 500040 | 2 | 44.0 | 0.7188752011488595 | 0.7108638452159034 | 2022-02-15 16:45:01.370347 | 2022-02-15 17:20:00.195195 | 2096.5942430496216 | 32.94399008750916 | 11.38773717880249 | 0.00046105384826660155

Easier to see elapsed time 
  | num_samples | epoch | batch_count | start_ts | end_ts |  
-- | -- | -- | -- | -- | -- | --
0 | 500040 | 0 | 44.0 | 2022-02-15 15:33:38 | 2022-02-15 16:08:35 | 34m 57s
1 | 500040 | 1 | 44.0 | 2022-02-15 16:09:25 | 2022-02-15 16:44:16 | 34m 51s
2 | 500040 | 2 | 44.0 | 2022-02-15 16:45:01 | 2022-02-15 17:20:00 | 34m 59s

**Ray 1.9.2**

  | num_samples | epoch | batch_count | train_loss | last_train_loss | start_ts | end_ts | profile.mean_train_epoch_s | profile.mean_fwd_s | profile.mean_grad_s | profile.mean_apply_s
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 500040 | 0 | 44.0 | 0.7595673781143710 | 0.7540111455652450 | 2022-02-15 15:53:55.217919 | 2022-02-15 16:27:37.520783 | 2019.854022026060 | 38.8397058725357 | 3.752868413925170 | 0.0005521297454833990
1 | 500040 | 1 | 44.0 | 0.7529379399788210 | 0.7455298231707680 | 2022-02-15 16:28:23.291743 | 2022-02-15 17:12:57.826593 | 2672.1326727867100 | 39.623832774162300 | 59.93712289333340 | 0.0005795001983642580
2 | 500040 | 2 | 44.0 | 0.7463416800953070 | 0.7427195860279930 | 2022-02-15 17:14:40.732041 | 2022-02-15 18:52:58.063230 | 2265.7598888874100 | 33.466416525840800 | 14.69275984764100 | 0.0005113124847412110

num_samples | epoch | batch_count | start_ts | end_ts |  
-- | -- | -- | -- | -- | --
500040 | 0 | 44.0 | 2022-02-15 15:53:55 | 2022-02-15 16:27:37 | 33m 42s
500040 | 1 | 44.0 | 2022-02-15 16:28:23 | 2022-02-15 17:12:57 | 44m 34s
500040 | 2 | 44.0 | 2022-02-15 17:14:40 | 2022-02-15 18:52:58 | 1h 38m 18s

**Request**
We have not been able to find anything in the release notes to suggest that this is a known issue. 
We have verified that this is not due to the way we orchestrate containerized Ray, and while the test we are using is fairly naive we are not sure how to narrow to a root cause or determine if this is a real performance degradation issue. 

Any confirmation of a known issue or tips on how to make progress will be greatly appreciated. 

### Versions / Dependencies

**Ray 1.6.0** 
- Ray cluster containers running rayproject/ray-ml:1.6.0-py38

**Ray 1.9.2**
- Ray cluster containers running rayproject/ray-ml:1.9.2-py38

### Reproduction script

Environment: 
* Ray cluster: 
** Worker 15 containers (6 CPU and 27GB RAM) each 
** Head container (6 CPU and 27GB RAM)

Here is the training job that we are using as a benchmark:

```
import argparse
import yaml
from dataclasses import dataclass, asdict

import ray
import torch.nn as nn
import torch.utils.data as data
from pkg_resources import parse_version
from ray.util.sgd.torch import TrainingOperator, TorchTrainer
from torch.optim import Adam


@dataclass
class DataConfig:
    root_path: str
    dataload_concurrency: int


@dataclass
class OptimizerConfig:
    learning_rate: float = 1e-6
    weight_decay: float = 1e-6


@dataclass
class Config:
    data: DataConfig
    optimizer: OptimizerConfig
    tqdm: bool = False
    use_cpus: bool = False


def loss_creator(use_cpus=False) -> nn.CrossEntropyLoss:
    if use_cpus:
        return nn.CrossEntropyLoss()
    else:
        return nn.CrossEntropyLoss().cuda()


def optimizer_creator(model, config: OptimizerConfig) -> Adam:
    return Adam(
        model.parameters(),
        lr=config['learning_rate'],
        weight_decay=config['weight_decay']
    )


def data_creator(config: DataConfig) -> (data.DataLoader, data.DataLoader):
    from torchvision.transforms import Normalize, ToTensor, Compose
    from PIL import Image
    import torch
    import torchvision
    import os

    normalize = Normalize(mean=[0.5, 0.5, 0.5], std=[0.1, 0.1, 0.1])
    transform = Compose([ToTensor(), normalize])

    def loader(path):
        im = Image.open(path)
        if im.width != 224 or im.height != 224:
            im = im.resize((224, 224))
        return im

    validate_dataset = torchvision.datasets.DatasetFolder(
        os.path.join(config['root_path'], "test"),
        loader,
        transform=transform,
        extensions=("png",)
    )
    validate_loader = torch.utils.data.DataLoader(
        validate_dataset,
        batch_size=128,
        shuffle=True,
        num_workers=config['dataload_concurrency'],
        pin_memory=True
    )

    train_dataset = data.ConcatDataset([
        torchvision.datasets.DatasetFolder(
            os.path.join(config['root_path'], "train"),
            loader,
            transform=transform,
            extensions=("png",)
        ) for i in range(20)
    ])
    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=128,
        shuffle=True,
        num_workers=config['dataload_concurrency'],
        pin_memory=True
    )
    return train_loader, validate_loader


def model_creator_resnet(use_cpus=False):
    import torchvision.models as models
    model = models.resnet50(True, progress=False)
    # Disable Training on Pretrained Layers
    for param in model.parameters():
        param.requires_grad = False

    model.fc = nn.Linear(model.fc.in_features, 2)
    if use_cpus is False:
        model = model.cuda()
    model = nn.DataParallel(model)
    return model


class BenchmarkOperator(TrainingOperator):
    def setup(self, config: dict):
        self._use_tqdm = config['tqdm']
        self.logger = logging.getLogger('BenchmarkOperator')
        train_loader, val_loader = data_creator(config['data'])
        model = model_creator_resnet(config['use_cpus'])
        optimizer = optimizer_creator(model, config['optimizer'])
        criterion = loss_creator(config['use_cpus'])
        self.model, self.optimizer, self.criterion = self.register(
            models=model,
            optimizers=optimizer,
            criterion=criterion
        )
        self.register_data(
            train_loader=train_loader,
            validation_loader=val_loader
        )

def initialization_hook():
    print("NCCL DEBUG SET")
    # Need this for avoiding a connection restart issue
    os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
    os.environ["NCCL_LL_THRESHOLD"] = "0"
    os.environ["NCCL_DEBUG"] = "INFO"

def get_config(path):
    if os.path.exists(path):
        with open(path) as props_file:
            return yaml.safe_load(props_file)
    return None


if __name__ == "__main__":
    import logging
    import datetime
    import pandas as pd
    from pprint import pformat
    import os
    import ray

    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)
    logger.info(datetime.datetime.now())

    output_dir = "/shared_storage_path/output/"
    num_workers = 90
    cores_per_worker = 1
    testdata_root_dir = "/mnt/data_size_12500"
    dataload_concurrency = 6
    use_cpus = True
    max_epoch = 3

    service_host = os.environ["RAY_HEAD_SERVICE_HOST"]
    service_port = os.environ["RAY_HEAD_SERVICE_PORT"]
    ray.init(f"ray://{service_host}:{service_port}")

    data_config = DataConfig(root_path=testdata_root_dir,
                             dataload_concurrency=dataload_concurrency)
    optimizer_config = OptimizerConfig()
    config = Config(data=data_config, optimizer=optimizer_config, tqdm=False,
                    use_cpus=use_cpus)

    trainer = TorchTrainer(
        config=asdict(config),
        use_gpu=True if not use_cpus else False,
        num_cpus_per_worker=cores_per_worker,
        num_workers=num_workers,
        initialization_hook=initialization_hook,
        training_operator_cls=BenchmarkOperator
    )

    trains = []
    vals = []

    os.makedirs(output_dir, exist_ok=True)
    for i in range(max_epoch):
        logger.info(f" EPOCH {i} START ".center(80, "="))
        logger.info(datetime.datetime.now())

        start_ts = pd.Timestamp.now()
        result = trainer.train(profile=True)
        end_ts = pd.Timestamp.now()
        result['start_ts'] = start_ts
        result['end_ts'] = end_ts
        result['epoch'] = i
        logger.info(pformat(result))
        trains.append(result)

        start_ts = pd.Timestamp.now()
        result = trainer.validate(profile=True)
        end_ts = pd.Timestamp.now()
        result['start_ts'] = start_ts
        result['end_ts'] = end_ts
        result['epoch'] = i
        logger.info(pformat(result))
        vals.append(result)

        logger.info(datetime.datetime.now())
        logger.info(f" EPOCH {i} END ".center(80, "="))

    trainer.shutdown()
    logger.info(datetime.datetime.now())

    trains = pd.json_normalize(trains)
    vals = pd.json_normalize(vals)

    trains.to_csv(os.path.join(output_dir, "trains.csv"))
    vals.to_csv(os.path.join(output_dir, "vals.csv"))
```

### Anything else

We are able to observe the degraded performance consistently

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Hey @gmatev do you see the same behavior if you use the same torch versions for both runs?

There actually has been no implementation changes to `TorchTrainer` from Ray 1.6 to now, so the regression is most likely due to some dependency changes in the Docker images I believe.

**Comment by gmatev** [comment]
Thanks for engaging @amogkam. It does seem that the two images have different versions of torch. We can try downgrading  this to the same torch version as 1.6.0 and see if we can reproduce the behavior. 

Any idea on what could case the epoch slowdown and how could torch version be impacting that?

**Comment by amogkam** [comment]
Unfortunately I have no ideas off the top of my head. There's been no changes to `TorchTrainer` and we make sure that actor performance does not regress between releases, so that's why I'm thinking it's related to dependencies.

Actually instead of downgrading torch, can you just use the `rayproject/ray-ml:1.6.0-py38` for both runs, but for the second manually upgrade to Ray 1.9? This will isolate whether it's a Ray issue or some other dependency issue.

**Comment by gmatev** [comment]
Will do

**Comment by amogkam** [comment]
Hey @gmatev apologies for the late reply-- yes I would recommend raising an issue with Pytorch. 

Regarding e2e performance of our release images, it's a bit tricky as each user has different requirements. Some users may want to use the latest versions of torch for new features without concern for performance. 

In general, I think it would be best to always try to keep up to date with the latest versions of torch. Though I agree-- we can definitely run training benchmarks for each release and publish those numbers!

**Comment by gmatev** [comment]
All good @amogkam. thank you!
