### ISSUE TITLE
[Bug] Symbol not found: _Py_GetArgcArgv on MacOS Big Sur 11.6.2

### ISSUE THREAD

**Issue by sergii-ivakhno-kidsloop** [ray-project/ray#22408]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

After installing ray as `poetry add ray  (or  ray[default])` and running `poetry run ray` I get an error:
```
Traceback (most recent call last):
  File "/Users/sergiiivakhnosivakhno/Library/Caches/pypoetry/virtualenvs/pytorch-audio-2zl3Ki-Z-py3.8/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/Users/sergiiivakhnosivakhno/Library/Caches/pypoetry/virtualenvs/pytorch-audio-2zl3Ki-Z-py3.8/lib/python3.8/site-packages/ray/__init__.py", line 91, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 16, in init ray._raylet
ImportError: dlopen(/Users/sergiiivakhnosivakhno/Library/Caches/pypoetry/virtualenvs/pytorch-audio-2zl3Ki-Z-py3.8/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
  Referenced from: /Users/sergiiivakhnosivakhno/Library/Caches/pypoetry/virtualenvs/pytorch-audio-2zl3Ki-Z-py3.8/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/sergiiivakhnosivakhno/Library/Caches/pypoetry/virtualenvs/pytorch-audio-2zl3Ki-Z-py3.8/lib/python3.8/site-packages/ray/thirdparty_files/setproctitle.cpython-38-darwin.so
```

I recognise that similar errors have been reported before, however I haven't found a clear solution / explanation except peculiar reports that changing minor Python versions or using different installation methods helps in edge cases.

On a similar line I wonder what are the system requirements for installing on MacOS - the official guidance just has a simple `pip install` line, but would gcc, etc be needed?

Many thanks for your help in advance - most appreciated! 

### Versions / Dependencies

MacOS Big Sur 11.6.2
ray = "1.10.0"
Python = 3.8.9 [Clang 13.0.0 (clang-1300.0.29.30)]

### Reproduction script

```
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
poetry new project
cd project
poetry add ray (or  ray[default])
poetry run ray
```

on MacOS Big Sur 11.6.2

**Comment by richardliaw** [comment]
Maybe relevant to: https://airflow.apache.org/docs/apache-airflow/2.0.2/installation.html#symbol-not-found-py-getargcargv ?
