### ISSUE TITLE
[RFC] [Job Submission] `list_jobs` REST API

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#22412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Make open source useful rest jobs API, corresponding SDK and CLI command.  

- ```
   GET /api/jobs/
   ```
   Options:
   None

   Return:
   Returns a list of all jobs running on the cluster, together with job data consisting of status, status message, runtime 
   environment, metadata, start time, end time, and namespace.  (see #22225 for an example of the job data)

   ``` 
   {
       "job_id": {"entrypoint": ..., "metadata": ..., "namespace": ..., "status": ..., "status_message": ...},
       ... 
   }
   ```

- ``` 
  GET /api/jobs/{job_id}
  ```
   Options:
  None

  Return:
  Same as GET /api/jobs, except only returns info for one job

We will have a corresponding Jobs SDK command:
```
from ray.job_submission import JobSubmissionClient

client = JobSubmissionClient("http://127.0.0.1:8265")

job_data_list = client.list_jobs()
```

And a corresponding Jobs CLI command:
```
ray job list
```
 

### Use case

This allows users to see which jobs are currently running.  Currently there is no way to do this; the user would have to manually keep track of job IDs as they are returned when the jobs are started.

### Related issues

https://github.com/ray-project/ray/issues/21956

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
@architkulkarni one very small nit, I think it should be `GET /api/jobs/` rather than `GET /api/jobs` to match the convention of the existing endpoints
