### ISSUE TITLE
[Bug] _validate_env raises EnvError even though observation looks ok

### ISSUE THREAD

**Issue by atrejut** [ray-project/ray#22429]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm using a custom environment with a `gym.spaces.Dict`-like observation space (see example code below).
When creating a trainer for this env `_validate_env` fails with  
```
Env's `observation_space` Dict(action_mask:Box([0. 0. 0.], [1. 1. 1.], (3,), float32), observations:Box([0. 0. 0. 0. 0.], [10. 10. 10. 10. 10.], (5,), float32)) does not contain returned observation after a reset ({'action_mask': array([0., 0., 0.]), 'observations': array([0., 0., 0., 0., 0.])})
```

This seems to be a problem with `gym==0.21.0`, but works fine with `gym==0.17.3`. I'm not sure whether the problem ultimately lies with `ray` or with `gym`, but reporting it here first since you're raising the exception. If you feel it should be reported against `gym` please let me know :)

### Versions / Dependencies

ray==1.10.0
gym==0.21.0
python==3.9
macOS

### Reproduction script
```
import numpy as np
import gym

import ray
from ray.rllib import agents
from ray.tune.registry import register_env

class TestEnv(gym.Env):
    def __init__(self, config):
        self.action_space = gym.spaces.Discrete(3)
        self.observation_space = gym.spaces.Dict({
                    "action_mask": gym.spaces.Box(0.0, 1.0, shape=(self.action_space.n,)),
                    "observations": gym.spaces.Box(low=0, high=10, shape=(5,))
                    })
    def reset(self):
        return {
            'action_mask': np.zeros(3),
            'observations': np.zeros(5)
        }

ray.init(_node_ip_address="0.0.0.0", ignore_reinit_error=True)
register_env('TestEnv', lambda _: TestEnv({}))

trainer_config = agents.ppo.DEFAULT_CONFIG.copy()
trainer_config.update({
    "env": 'TestEnv',
    "env_config": {},
})

trainer = agents.ppo.PPOTrainer(env='TestEnv', config={})
# -> results in ray.rllib.utils.error.EnvError:

# root cause seems to be here:
#########################
from ray.rllib.evaluation.rollout_worker import _validate_env
from ray.rllib.env.env_context import EnvContext

context = EnvContext(
            {},
            worker_index=1,
            vector_index=0,
            num_workers=1,
            remote=None,
        )
_validate_env(TestEnv({}), context)

```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR! (but have no idea currently what the cause of the issue is...)

**Comment by gjoliver** [comment]
I am gonna close this one, since this is a dup of #23527, we will focus and communicate resolution via that cover bug.
