### ISSUE TITLE
[Release 1.11.0] `gcp_k8s_durable_upload` failing

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#22433]
Same failure on `master` and `releases/1.11.0` branches, where nodes are not coming up:
https://buildkite.com/ray-project/periodic-ci/builds/2788#e06260cb-781d-4591-bacc-0bf1065a0469/81-266
https://buildkite.com/ray-project/periodic-ci/builds/2778#88afe272-79f8-46a5-b151-3d35b4595afa/139-344
I wonder if this is related to product k8s's support for GCS-Ray. @iycheng can you follow up with @DmitriGekhtman on this?

**Comment by DmitriGekhtman** [comment]
Ah, I didn't realize we were already running GCS-Ray against the internal K8s. Let me follow up offline.

**Comment by mwtian** [comment]
Great, thanks Dmitri!

**Comment by DmitriGekhtman** [comment]
This probably doesn't need to be taken as a release-blocker per-se -- just an indicator of some known product prep that needs to be done in preparation for the release.

**Comment by mwtian** [comment]
Sounds good, downgrading this to P1.
