### ISSUE TITLE
[Bug] Tune doesn't sync additional files back to head

### ISSUE THREAD

**Issue by Michalos88** [ray-project/ray#22445]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

1. After running all the steps for a given trial, we test the model in a separate validation environment. The results of that testing are saved as a json in trials logdir folder. When running this in a distributed setting, only training results are synced back to head, and the additional analysis file is not. 
2. I would expect tune to sync back all the files in the logdir back to head. 

### Versions / Dependencies

- Ray: 0.8.7.
- Python 3.7
- Ubuntu 18.02

### Reproduction script

```python
import json
import time
from pathlib import Path

import numpy as np
import ray
from ray import tune


def main():
    exps = list()
    ray.init(address="localhost:6379", log_to_driver=False)
    for i in range(0, 5):
        exps.append(
            tune.Experiment(
                run=TestTrainable,
                name=f"test_{i}",
                config={},
                stop={"training_iteration": 5},
                checkpoint_at_end=False,
                local_dir="~/ray_results/test_saving/",
                upload_dir=None,
                resources_per_trial=dict(cpu=1),
            )
        )
    tune.run(
        exps,
        verbose=1,
        resume=False,
        global_checkpoint_period=np.inf,
    )


class TestTrainable(tune.Trainable):
    def step(self):
        time.sleep(5)
        res = {"step": self.iteration}
        print(res)
        return res

    def cleanup(self):
        output = {
            "done": True,
            "iter": self.iteration,
            "analysis": "some analysis after steps are completed",
        }
        logdir = Path(self.logdir)
        fn = "analysis.json"
        io = (logdir / fn).open("w")
        json.dump(output, io)
        io.close()


if __name__ == "__main__":
    main()

```

### Anything else

I'm running this on Ray Cluster on AWS with 1 head with `num-cpus=0` (to make sure it is ran on worker and not on head), and 1 worker. 

Link to my initial question on slack: https://ray-distributed.slack.com/archives/CNECXMW22/p1642779685018600

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Michalos88** [comment]
Any updates on this @xwjiang2010? My project is past due because of this bug, so would really appreciate if someone could investigate this issue.

**Comment by xwjiang2010** [comment]
Sorry for being late on this ticket!
@Michalos88 Could you maybe update your ray version (0.8.7 is pretty old and no longer supported)?
