### ISSUE TITLE
[Bug] PPO cur_kl_coeff is not restored

### ISSUE THREAD

**Issue by 2dm** [ray-project/ray#22444]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When restoring from a checkpoint, either by `ppo_trainer.restore(checkpoint)` or `tune.run("PPO", ..., restore=checkpoint_path)`, the updated kl coefficient is not restore. Instead, the value from the configuration is used. 

### Versions / Dependencies

Tested on ray 1.10, Python 3.9

### Reproduction script

 Reproduction script based on sb2rllib_rllib_example.py from rllib's examples:

```
import gym
import ray
import ray.rllib.agents.ppo as ppo


env_name = "CartPole-v1"
train_steps = 10000
learning_rate = 1e-3
save_dir = "saved_models"


analysis = ray.tune.run(
    "PPO",
    stop={"timesteps_total": train_steps},
    config={
        "env": env_name,
        "lr": learning_rate
    },
    checkpoint_at_end=True,
    local_dir=save_dir,
)

analysis.default_metric = "episode_reward_mean"
analysis.default_mode = "max"
checkpoint_path = analysis.get_best_checkpoint(trial=analysis.get_best_trial())
print(f"Trained model saved at {checkpoint_path}")

train_steps = 20000

analysis = ray.tune.run(
    "PPO",
    stop={"timesteps_total": train_steps},
    config={
        "env": env_name,
        "lr": learning_rate
    },
    checkpoint_at_end=True,
    local_dir=save_dir,
    restore=checkpoint_path,
)
```
Tensorboard plot of cur_kl_coeff for the above script:
![image](https://user-images.githubusercontent.com/451839/154344339-5b49a6c1-1de5-4081-a64e-dd2bffba8e2c.png)

### Anything else

Thanks

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @2dm , thanks for raising this. This seems indeed wrong. We'll try to fix this.
Here is a PR:
https://github.com/ray-project/ray/pull/22590
