### ISSUE TITLE
[Feature] Looking for a way to cancel ray serve task

### ISSUE THREAD

**Issue by Purvak-L** [ray-project/ray#22450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I’ve deployed a prediction service using Ray serve. The predict service at times might take a while to finish. I want a way to cancel the ongoing prediction task. When I try to use ray.cancel/ray.kill using object ref/handle it says Actor task cancellation is not supported. The predict service is currently deployed on an AWS cluster.
I also tried ray.kill with handle.controller_handle and that didn't cancel the job/task

Discussion - https://discuss.ray.io/t/looking-for-a-way-to-cancel-ray-serve-task/5065

I'm looking for a way to cancel such long-running jobs!

### Use case

Think about a long-running predict job in NLP or GAN deployed using Ray Serve. A backend system should have a way to send kill/cancel signal to this job to either free up resources or it was a wrong request to begin with.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by spolcyn** [comment]
This would also be very useful to us in expanding our use of Ray Serve -- right now we use actors for things we'd otherwise prefer to use deployments for, mainly because we can kill actors and cancel a job in the middle.

**Comment by MissiontoMars** [comment]
This feature is very useful, but I am afraid it is difficult to implement. Do you have any ideas?

**Comment by Abhyudhey** [comment]
+1

**Comment by shrekris-anyscale** [comment]
This feature was released for Serve in Ray 2.8 ([commit](https://github.com/ray-project/ray/commit/ccf6212b418af3840a2b7cd31dc60cf55fb47855)). Check out [these docs](https://docs.ray.io/en/latest/serve/http-guide.html#request-cancellation) to learn more.
