### ISSUE TITLE
[Bug] rayproject/ray-ml:1.9.2-py38 does have non CPU unnecessary torch version 1.9.0+cu111

### ISSUE THREAD

**Issue by polovinko1980** [ray-project/ray#22468]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

That is more clarification request, but also might indicate the issue with publishing images.
In January release we do see following image tags published:
rayproject/ray-ml:1.9.2-py38
rayproject/ray-ml:1.9.2-py38-gpu

Assuming rayproject/ray-ml:1.9.2-py38 should be a CPU flavor and rayproject/ray-ml:1.9.2-py38-gpu is GPU one.
However, there is inconsistency between image content and image purpose. 
We do see that rayproject/ray-ml:1.9.2-py38 does have torch==1.9.0+cu111 installed that is used for GPU flavor.

Questions:
1. Why don't we have explicit tag for CPU flavor like it was in the past: rayproject/ray-ml:1.6.0-py38-cpu
2. What is really the purpose of rayproject/ray-ml:1.9.2-py38: CPU flavor or GPU flavor?
3. If rayproject/ray-ml:1.9.2-py38 is supposed to be used in CPU flavor, why it has torch==1.9.0+cu111  which is unnecessary for CPU?
4. May be you have a different tag for CPU image I have overlooked?

### Versions / Dependencies

rayproject/ray-ml:1.9.2-py38

### Reproduction script

docker run -it rayproject/ray-ml:1.9.2-py38 /bin/bash
(base) ray@f253ae26211a:~$ pip freeze | grep torch
botorch==0.5.0
gpytorch==1.6.0
pytorch-lightning==1.4.9
torch==1.9.0+cu111
torchmetrics==0.6.2
torchvision==0.10.0+cu111

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by polovinko1980** [comment]
Thanks, @amogkam Yes, we are considering that ml images are different from regular images, so please add support for CPU flavor of ray-ml.

**Comment by amogkam** [comment]
@polovinko1980 do you mind sharing some more details on the benefit that CPU ml images provide you guys? It would be great to hear more about your use case.

**Comment by polovinko1980** [comment]
Primary benefit is container size when we run training without using GPUs(test training and other workloads are CPU based). The images are used on Ray clusters orchestrated on top of auto-scaled K8s clusters so when it needs to land on a freshly spun node, a 3.5GB image vs 7GB image has a dramatic impact on startup time.

**Comment by amogkam** [comment]
CPU ML docker images have been added back as of Ray 1.12.1
