### ISSUE TITLE
privileged test failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#22460]
https://buildkite.com/ray-project/ray-builders-branch/builds/6104#d3be542b-da33-4efb-a008-2b60a8171ffc

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - feature:|@/linux-64::__glibc==2.33=0
  - brotlipy -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-package-handling -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - cryptography -> libgcc-ng -> __glibc[version='>=2.17']
  - libffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libgcc -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - libgcc-ng -> __glibc[version='>=2.17']
  - libstdcxx-ng -> __glibc[version='>=2.17']
  - ncurses -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pycosat -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - readline -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - ruamel_yaml -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - sqlite -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - tk -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - xz -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - yaml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.33

**Comment by iycheng** [comment]
@simon-mo  do you have some idea about this?

**Comment by simon-mo** [comment]
No i don't know how can this be fixed. Consider disable the test for now?

**Comment by rkooo567** [comment]
Maybe we should also ping Ant? I believe they contributed this feauter

**Comment by SongGuyang** [comment]
> Maybe we should also ping Ant? I believe they contributed this feature

@edoakes @simon-mo @rkooo567 Please ping us next time directly😊. If the code owner is not clear, you can ping @raulchen and he will distribute. We will take a high priority for the blocking issues in OSS.
