### ISSUE TITLE
Calling ray.init with object_store_memory set errors in Docker container

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#2249]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **Ray installed**: from source following the [Installation on Docker](https://ray.readthedocs.io/en/latest/install-on-docker.html) docs. 
- **Ray version**: 0.4 (latest build)
- **Python version**: 2.7 and 3.5
- **Exact command to reproduce**:
```python
import ray
ray.init(object_store_memory=1e9)
```

### Describe the problem
Setting `object_store_memory` when running Ray within docker causes an error connecting to a socket:
```pyarrow.lib.ArrowIOError: Could not connect to socket /tmp/plasma_store56046954```

### Source code / logs
[ray_error.log](https://github.com/ray-project/ray/files/2099526/ray_error.log)

**Comment by robertnishihara** [comment]
Can you look at the object store logs under `/tmp/raylogs`? How much shared memory does the docker container have? E.g., are you starting it with the `--shm-size` flag?

**Comment by pschafhalter** [comment]
The following is from the plasma store logs:
`/ray/thirdparty/build/arrow/cpp/src/plasma/store.cc:855 Check failed: scanned == 1`.

Looks like it might be an issue with the `sscanf` call in Arrow.

I started the docker instance with `docker run --shm-size=2G -t -i ray-project/deploy`.

**Comment by robertnishihara** [comment]
No longer relevant, I think. Please reopen if I'm wrong about that.
