### ISSUE TITLE
[Release 1.11.0] `serve_failure` failing on alerts raised

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#22501]
https://buildkite.com/ray-project/periodic-ci/builds/2788#f9a584f1-4c98-418d-9a76-444dc9e0a6ac/139-3338
Logs from the test output:
```
[ERROR 2022-02-18 07:01:12,301] e2e.py: 2264  Alert has been raised for long_running_tests/serve_failure (releases/1.11.0): Last update to results json was too long ago (79258.10 > 480)
[INFO 2022-02-18 07:01:12,301] e2e.py: 2286  Usually I would now report the following results:
{'test_suite': 'long_running_tests', 'test_name': 'serve_failure', 'status': 'error (alert raised)', 'last_logs': 'Last update to results json was too long ago (79258.10 > 480)', 'results': {'iteration': 251, 'iteration_time': 78.43659734725952, 'absolute_time': 1645117208.26745, 'elapsed_time': 7104.032537937164, 'last_update': 1645117208.2675087, 'last_update_diff': 79258.10186934471, '_runtime': None, '_session_url': None, '_commit_url': None, '_stable': True}, 'artifacts': {}, 'category': 'releases/1.11.0', 'team': 'serve'}
```
@architkulkarni assigning to you as serve oncall. Can you triage to see if this can be ignored, or a fix needs to be cherry picked? `serve_failure` seems to be failing on `master` as well, although with a different failure message.

**Comment by shrekris-anyscale** [comment]
@mwtian, @architkulkarni is out today. This looks like a bug– I'm taking a look.

**Comment by mwtian** [comment]
Thanks @shrekris-anyscale!

**Comment by edoakes** [comment]
@mwtian @simon-mo and @shrekris-anyscale looked into this and it appears to be a bug, but highly unlikely to impact any user workloads so we suggest to not mark it release-blocking.

**Comment by mwtian** [comment]
Sounds good, thanks for confirming! Closing since this is not happening on `master`. cc @iycheng
