### ISSUE TITLE
[Bug] torch.cuda.is_available() is False after running CPU task

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#22504]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When using PyTorch on Ray, mixing CPU and GPU tasks / actors leads to the GPU tasks being unable to properly initialize CUDA. 

Running a CPU ray task that uses PyTorch followed by a GPU task or actor leads to the latter being unable to init CUDA.

What should happen: regardless of whether any CPU tasks were run before the GPU task, the GPU task / actor should be able to properly init CUDA.

### Versions / Dependencies

```
ray==1.10.0
torch==1.10.2+cu111
```

### Reproduction script

```
import torch
import ray

ray.init("auto")

@ray.remote
def test_fn():
    print(torch.cuda.is_available())

@ray.remote(num_gpus=1)
def test_gpu_fn():
    print(torch.cuda.is_available())

ray.get(test_fn.remote())
ray.get(test_gpu_fn.remote())
```

prints: `False False` (expected: `False True`)

Also happens if the GPU task is changed to an actor:

```
import torch
import ray

ray.init("auto")

@ray.remote
def test_fn():
    print(torch.cuda.is_available())

@ray.remote(num_gpus=1)
class GpuActor(object):
    def test_gpu_fn(self):
        print(torch.cuda.is_available())

ray.get(test_fn.remote())

actor = GpuActor.remote()
ray.get(actor.test_gpu_fn.remote())
```

prints: `False False`

However, if we change the CPU task to an actor, it works as expected:

```
import torch
import ray

ray.init("auto")

@ray.remote
class CpuActor(object):
    def test_fn(self):
        print(torch.cuda.is_available())

@ray.remote(num_gpus=1)
class GpuActor(object):
    def test_gpu_fn(self):
        print(torch.cuda.is_available())

cpu_actor = CpuActor.remote()
ray.get(cpu_actor.test_fn.remote())

actor = GpuActor.remote()
ray.get(actor.test_gpu_fn.remote())
```

prints: `False True`

Furthermore, if we run the GPU task first, it works correctly:

```
import torch
import ray

ray.init("auto")

@ray.remote
def test_fn():
    print(torch.cuda.is_available())

@ray.remote(num_gpus=1)
def test_gpu_fn():
    print(torch.cuda.is_available())

ray.get(test_gpu_fn.remote())
ray.get(test_fn.remote())
```

prints: `True False`

### Anything else

This is running in Docker on AWS (g4dn.8xlarge)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Yeah, sounds similar to an issue we're investigating already. Probably we shouldn't reuse processes for actors or GPU tasks.

**Comment by ericl** [comment]
One way to force a different worker is to give it a unique runtime env. For example:

```
@ray.remote(runtime_env={"env_vars": {"some": "key"}})
def f():
   pass
```

That should force a fresh worker to be started for `f`.

**Comment by tgaddair** [comment]
Thanks, let me see if we can do something like this. Part of the complexity for us is that we're using libraries like Ray Train and Horovod that sit on top of Ray Core, so it's not always possible to specify these details, but I will see if we can plumb it through.

**Comment by tgaddair** [comment]
Very nice! I will give this a shot, thanks!
