### ISSUE TITLE
[API] Support for preallocated Object IDs

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2252]
### Describe the problem

There are a growing number of use cases for having a "preallocated" object id. The idea is that some opaque id can be generated, e.g., `id = new_random_object_id()`, and later on some task can "fulfill" the id by calling `ray.put(data, existing_id=id)`.

One use case is to support tight integration with TensorFlow, as part of https://github.com/ray-project/ray/issues/1945. Here, we require a custom TensorFlow op to read/write directly from the plasma store. This naturally requires object ids to be preallocated, since TensorFlow can't interact with Ray APIs directly.

Another use is to support a "task queue" Actor. Suppose you have some actor A sending data to B through a queue Q. A can call Q to enqueue tasks, and B can call Q to dequeue tasks, but B needs some way to send the result back to A. One natural way of doing this is for B to "fulfill" the object id preallocated by A.

### Open questions:
How does this interact with fault-tolerance?

**Comment by luochao1024** [comment]
@ericl  do you mean that this api has been added or the official team are still working on it? This api is really cool. I can't wait to use it!

**Comment by ericl** [comment]
I opened this to track the issue, since we would like to add this, though no one is currently working on it at the moment. Help would be welcome, of course.
