### ISSUE TITLE
Ray serve + FastAPI Tutorial / Docs

### ISSUE THREAD

**Issue by INF800** [ray-project/ray#22533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Hi, when I checked the official ray serve docs, I saw "more coming soon". I hope the documentation is in progress for ray serve. But I don't think documentation is ready for FastAPI.

I would like to write FastAPI specific tutorials for ray serve and send PR (with some guidance). Let me know your thoughts.

### Use case

Things that I want to cover in FastAPI specific tutorials / docs as a start.

- Stream prediction
- Batch prediction
- Ensemble prediction
- Realtime scaling of clusters

### Related issues

#9869

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by INF800** [comment]
https://docs.ray.io/en/latest/serve/http-servehandle.html#serve-fastapi-http This is good but I want to make application oriented docs/examples

**Comment by architkulkarni** [comment]
Hi @INF800 Thanks for offering to contribute, we'd be happy to have more such tutorials!  Feel free to submit PRs for these.  Let us know if there's any specific guidance you need; otherwise working off of the existing tutorials as a template should be fine (although these are not set in stone and you should feel free to improve them!)

**Comment by INF800** [comment]
Will keep you posted here.

**Comment by JosephChotard** [comment]
@INF800 Thanks for doing this! I'm very new to the framework and would especially like some clarification regarding swagger/openapi and ray:serve

**Comment by dineshbvadhia** [comment]
@INF800 @architkulkarni Sounds good. A few thoughts:

The combination of Ray + Ray Serve + FastApi (which sits on top of Starlette and uvicorn) adds up to a lot of independent moving parts in this stack. Apart from tutorials, what is missing are minimal working templates to cover:

* single node and multi-node templates with each showing:
* starting ray+serve+fastapi optimally
* shutting down ray+serve+fastapi safely
* http and ServeHandle versions of the templates, and also showing why one is better than the other if at all
* the templates shouldn't focus on ml models only but be of generic usage

**Comment by INF800** [comment]
Been thinking about how to pull this off for sometime. The main problem that I want to solve is "how to make the code as developer friendly as possible keeping the performance and 'gotchas' in mind". 

The best conclusion that I could come to was to create **template repository that will serve the following purposes**. (Feel free to add any as I am mentioning only the P0 ones) 

- Any developer (beginner/experienced) should be able to write an api with ease. Define API functions in a config file which will be automatically served. 

- Abstract the complicated parts but with detailed comments in the code. So that developers can understand what is happening under the hood. 

- Like FastAPI, we will keep everything as simple (yet performant) as possible unless we cannot.

**Comment by architkulkarni** [comment]
That sounds good!  Let us know if you need help opening a PR.

**Comment by architkulkarni** [comment]
Not too familiar with this but it looks like you can only create new repositories off of a template, not merge them into an existing repository.  

Maybe once we have more tutorials we can have an examples directory like https://github.com/mlflow/mlflow/tree/master/examples, but for now maybe it's easiest to just tutorials in our existing locations.

**Comment by INF800** [comment]
> Not too familiar with this but it looks like you can only create new repositories off of a template, not merge them into an existing repository.
> 
> Maybe once we have more tutorials we can have an examples directory like https://github.com/mlflow/mlflow/tree/master/examples, but for now maybe it's easiest to just add tutorials in our existing locations.

Sure, makes sense.

**Comment by INF800** [comment]
Hi, I need to setup kubernetes for testing. Is there some way I can grab some code and configurations from somewhere. 

Setup well enough to scale up a model that takes 2s to make predictions.

**Comment by INF800** [comment]
> Hi, I need to setup kubernetes for testing. Is there some way I can grab some code and configurations from somewhere.
> 
> Setup well enough to scale up a model that takes 2sec to make predictions and make it predict within 0.5-1sec or so.

I don't think it is available in docs as well

**Comment by INF800** [comment]
> > Hi, I need to setup kubernetes for testing. Is there some way I can grab some code and configurations from somewhere.
> > Setup well enough to scale up a model that takes 2sec to make predictions and make it predict within 0.5-1sec or so.
> 
> I don't think it is available in docs as well

@architkulkarni @AmeerHajAli kindly let me know. I will start writing from scratch if not available.

**Comment by AmeerHajAli** [comment]
cc @edoakes

**Comment by architkulkarni** [comment]
Hi @INF800, I don't think we have any sample Kubernetes code or configurations beyond what's listed in the Ray docs unfortunately.  We have a Ray Operator for kubernetes which may be helpful: https://docs.ray.io/en/latest/cluster/kubernetes.html
