### ISSUE TITLE
[Bug] agent_key not removed in self.agent_collectors in simple_list_collector when training_enabled==True in last_info

### ISSUE THREAD

**Issue by aralebox** [ray-project/ray#22539]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I'm using the ExternalEnv to train a RL policy with many short episodes. During test, "training_enabled" is set to True.
Occasionally, an assert error appeared in simple_list_collector.py, method add_init_obs(), line 641 "assert agent_key not in self.agent_collectors". 
Below is my analysis: 
When an episode is ended, in simple_list_collector.py, method postprocess_episode is called. In this method, self.agent_collectors is cleared @line 935:
if is_done:
                del self.agent_key_to_policy_id[agent_key]
                del self.agent_collectors[agent_key]
However, this is only executed for the agent_id in post_batches. When "training_enabled" is True (if clause in line 869), the current episode will not be put in post_batches.
The consequence is that self.agent_collectors kept growing with many short episodes whose training_enabled is set to True.
My guess about the error is that up to some point the randomness in generating episode_id is not sufficient to guarantee unique IDs. 

For line numbers, I refer to this file (master branch): https://github.com/ray-project/ray/blob/master/rllib/evaluation/collectors/simple_list_collector.py

### Versions / Dependencies

ray1.9.2

### Reproduction script

The issue cannot be 100% reproduced due to the randomness nature. If the problem explanation is not clear enough, I can try to submit a ExernalEnv based script generating many short episodes with "training_enabled" as True.

### Anything else

I inserted the following lines in simple_list_collector.py at line 949:

            agent_list = self.agent_collectors.copy().items()
            for (eps_id, agent_id), collector in agent_list:
                if eps_id == episode_id:
                    del self.agent_key_to_policy_id[(eps_id, agent_id)]
                    del self.agent_collectors[(eps_id, agent_id)]

It seems working.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Hey @aralebox , thanks for raising this!
You are right, when `training_enabled==False` the `del` code is never reached as we `continue` the loop before that.
Let's try your suggested fix and make sure all tests pass, then we can merge this. I'll PR now ...

**Comment by sven1977** [comment]
PR:
https://github.com/ray-project/ray/pull/22587
@aralebox
