### ISSUE TITLE
[Feature] Why ray can connnect to redis but my machine doesn't installed redis??

### ISSUE THREAD

**Issue by jinfagang** [ray-project/ray#22575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

My ray project can run by:

```
ray start --address='10.73.12.59:6379' --redis-password='xxx'
```

But I don't have redis on my machine:

```
> redis-cli
Hey! The program 'redis-cli' is currently not installed. You can install it by typing:
yum install redis

> redis-server -v
Hey! The program 'redis-server' is currently not installed. You can install it by typing:
yum install redis

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Ray comes with packaged Redis binary! It doesn't download the Redis
