### ISSUE TITLE
[Train] Automatic pipelining of host to device transfer

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#22603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

For better performance, we can pipeline the data transfer from CPU -> GPU with training. So while training is happening for one batch on one cuda stream, another cuda stream can concurrently move the next batch from CPU to GPU. We already have a user implementing this themselves (Ludwig). 

For our implementation we can follow what's being done in torchrec: https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/train_pipeline.py#L74 and add it to `WrappedDataLoader`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jwyyy** [comment]
Hi @amogkam, this issue is not in the train backlog. You may want to add it to the list. (I will look into this issue as well with other ones.)

**Comment by amogkam** [comment]
good catch, added it to the backlog!

**Comment by jwyyy** [comment]
Here is a minimal integration (not including the current `_WrappedDataLoader` implementation). I assume that `batch` is always a torch Tensor. The default dataLoader returns a list of predictors and targets. We need to take careful of different data formats, such as tuple / list, or a single tensor.
 
```python
def _to_device(batch, device, nonblocking):
    return None if batch is None else batch.to(device=device, non_blocking=nonblocking)

class _WrappedDataLoader:

    def __init__(self, dataloader, device):
        self._dataloader = dataloader
        self.dataloader_iter = None
        self.device = device
        self.memcpy_stream = torch.cuda.Stream(device) if device.type == "cuda" else None
        self.curr_batch = None
        self._prepare()
        # current implementation

    def __iter__(self):
        # current implementation
        return self

    def _prepare(self):
        self.dataloader_iter = iter(self._dataloader)
        self._get_next_batch()

    def _get_next_batch(self):
        next_batch = next(self.dataloader_iter, None)
        with torch.cuda.stream(self.memcpy_stream):
            self.curr_batch = _to_device(next_batch, self.device, True)

    def __next__(self):
        ret_batch = self.curr_batch
        if ret_batch is None:
            self._prepare()
            raise StopIteration
        self._get_next_batch()
        return ret_batch
```
The performance depends on the scale of the problem. For instance, I tested it using the pytorch mnist [example](https://github.com/pytorch/examples/blob/master/mnist/main.py) on my desktop (NVIDIA 2080 Ti). There was not a clear difference between using memory copy and not using it. 

For the following toy example (but a large scale),
```python
device = torch.device("cuda")
# create a toy dataloader
dataloader = [torch.randn((1024 * 4, 1024 * 4), device="cpu") for _ in range(100)]

# run the following experiment w. and w.o. memory copy
# can compute the average running time and std
for _ in range(100):
    torch.cuda.synchronize()
    start.record()
    for batch in dataloader: # or _WrappedDataLoader(dataloader)
        batch = batch.to(device) # remove this line if use _WrappedDataLoader
        torch.matmul(batch, batch)
    end.record()
    torch.cuda.synchronize()
```
the average runtime over 100 iterations without using memory copy was 1618.5s (std=29.3), while using memory copy reduced the average time to 1063.5s (std=21.6).

(We can also create a separate thread to handle the data movement to CUDA devices. But it may have a similar performance.)

Please let me know if the current plan looks good to you @amogkam. Thanks!
