### ISSUE TITLE
[serve] Make controller use import paths

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#22604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The Serve controller primarily uses serialized classes and functions when setting up replicas. It should instead primarily use import paths.

### Use case

Import paths better support the [REST API](https://github.com/ray-project/ray/pull/22578#discussion_r813065846) and cross-language use cases. With runtime environments, replicas can directly import the deployment class or function without worrying about serialization.

### Related issues

#22578 contains [some discussion](https://github.com/ray-project/ray/pull/22578#discussion_r813065846) about this enhancement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hora-anyscale** [comment]
Per Triage Sync:  @shrekris-anyscale is this still an issue?

cc: @sihanwang41

**Comment by shrekris-anyscale** [comment]
Thanks for following up here @hora-anyscale. I don't think there's a strong motivation for this change anymore since the controller can use import paths now.
