### ISSUE TITLE
[Bug] No Logging Options for Serve Deployment and/or Ray generated Pool Actors

### ISSUE THREAD

**Issue by Yatagarasu50469** [ray-project/ray#22605]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

Re-posted from: https://discuss.ray.io/t/no-logging-options-for-serve-deployment-and-or-ray-generated-pool-actors/5164 

Option(s) for controlling the logging level for a serve deployment and pool actors (generated under the Ray Pool API) with Python are not functional. Specifying the logging level at initialization should pass the specified level to any actors using the encapsulated resources, though this doesn’t actually appear to be the case. Reproduction script included for serve deployment, though similar behavior also occurs with pool actors. Thank you in advanced.

**What happened**
```
 pid=47948) 2022-02-22 15:30:47,910     INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
 pid=47948) 2022-02-22 15:30:48,017     INFO http_state.py:98 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:mQCdAu:SERVE_PROXY_ACTOR-node:127.0.0.1-0' on node 'node:127.0.0.1-0' listening on '127.0.0.1:8000'
2022-02-22 15:30:48,655 INFO api.py:475 -- Started Serve instance in namespace '0d3370fc-79eb-44c2-9487-469ea0e95e50'.
2022-02-22 15:30:48,670 INFO api.py:249 -- Updating deployment 'ModelServer'. component=serve deployment=ModelServer
 pid=2228) INFO:     Started server process [2228]
 pid=47948) 2022-02-22 15:30:48,769     INFO deployment_state.py:920 -- Adding 1 replicas to deployment 'ModelServer'. component=serve deployment=ModelServer
2022-02-22 15:30:49,437 INFO api.py:261 -- Deployment 'ModelServer' is ready at `http://127.0.0.1:8000/ModelServer`. component=serve deployment=ModelServer
 pid=40024) Initializing
 pid=40024) Called
 pid=47948) 2022-02-22 15:30:49,542     INFO deployment_state.py:940 -- Removing 1 replicas from deployment 'ModelServer'. component=serve deployment=ModelServer
```

**What you expected to happen**
```
 pid=40024) Initializing
 pid=40024) Called
```

### Versions / Dependencies

```
Windows 10 and/or Ubuntu 18.04
Python 3.8
Ray 1.10.0
```

### Reproduction script

```
import logging
import ray
from ray import serve
  
ray.init(configure_logging=True, logging_level=logging.ERROR)
  
@serve.deployment(route_prefix="/ModelServer")
class ModelServer:
    def __init__(self): print('Initializing')
    def __call__(self): print('Called')

serve.start()
ModelServer.deploy()
model = ModelServer.get_handle()
ray.get(model.remote())
serve.shutdown()
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dougpool** [comment]
Some updated information while testing with ray 2.1.0 / python 3.9.7

Only warning and critical logs appear to come through when using logging.debug|info|warn|critical regardless of the logging_level

```
import logging
import ray
from ray import serve
import time

ray.init(configure_logging=True, logging_level=logging.DEBUG)


@serve.deployment(route_prefix="/ModelServer")
class ModelServer:
    def __init__(self): logging.info('Initializing')

    def __call__(self):
        logging.critical('critical Called')
        logging.warning('warning Called')
        logging.debug('Debug Called')
        logging.info('Info Called')
        print('LOGGED VIA PRINT')


serve.start()
ModelServer.deploy()
model = ModelServer.get_handle()
ray.get(model.remote())
serve.shutdown()
```

**Comment by Yatagarasu50469** [comment]
A newly discovered side effect: warnings logged during any external library imports are not caught on actor/worker initialization, causing additional undesirable console clutter.
