### ISSUE TITLE
[Pandas on Ray] DataFrame.(Groupby).first Not Implemented?

### ISSUE THREAD

**Issue by crystalzyan** [ray-project/ray#2262]
Hi @devin-petersohn , I reran df.groupby.first on the new machine @pcmoritz gave me, and I still ran into a NotImplementedError. 

This time, I did figure how to print out the version of Ray that is installed on the new machine, so I hope you can let me know if this is indeed an old version of Ray or if this is a legitimate bug.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS (Xenial Xerus)
- **Ray installed from (source or binary)**: Unknown. Please ask Philipp Moritz, he was the one who installed Ray for me.
- **Ray version**: 0.4.0
- **Python version**: Anaconda Python 3.6.4
- **Exact command to reproduce**: 
```
import ray.dataframe as pd
df = pd.read_csv("yellow_tripdata_2015-01-01.csv")
df.groupby(df.passenger_count).first()  # Error here
```

### Describe the problem
I get the traceback copied below in the **Source code/logs** section, when running the line `df.groupby(df.passenger_count).first()`

Additionally, I noticed when running Ray on this new machine that the memory errors seem **much** worse than before. In my original email example, I was using the January dataset (1/12 of all of 2015 data), and was able to run several parts in succession. 

However, this time when running Ray, it would hang and spam `ObjectID already exists in the object store` error messages immediately, on any next line, right after `pd.read_csv` (with my 1/12 data, running **isolated** from pandas or anything else). I wouldn't even be able to run `df.head()` right after reading in the csv this time around.

I had to split my January dataset in half, and use only 1/24 of the 2015 data, in order to just run this test. It may have just been that the new machine has less memory, but I do hope that I am indeed running from the right version of Ray.

You can get the source data csv I used at this page [http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml](url) under 2015>January>Yellow. Note that this csv file is 2 GB.

### Source code / logs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/ray/python/ray/dataframe/groupby.py", line 235, in first
    return self._apply_agg_function(lambda df: df.first(offset=0,
  File "/home/ubuntu/ray/python/ray/dataframe/groupby.py", line 492, in _apply_agg_function
    result = [f(v) for k, v in self._iter]
  File "/home/ubuntu/ray/python/ray/dataframe/groupby.py", line 492, in <listcomp>
    result = [f(v) for k, v in self._iter]
  File "/home/ubuntu/ray/python/ray/dataframe/groupby.py", line 236, in <lambda>
    **kwargs))
  File "/home/ubuntu/ray/python/ray/dataframe/dataframe.py", line 2029, in first
    "To contribute to Pandas on Ray, please visit "
NotImplementedError: To contribute to Pandas on Ray, please visit github.com/ray-project/ray.
```

**Comment by devin-petersohn** [comment]
Thanks for reporting this @crystalzyan! It looks like `DataFrame.first` is not implemented, and our `DataFrameGroupBy.first` relies on it. Shouldn't be too difficult to implement.

**Comment by devin-petersohn** [comment]
@crystalzyan Closing to track in the new repo: https://github.com/modin-project/modin/issues/66
