### ISSUE TITLE
[Bug] ray dashboard ip:8265 out of memory

### ISSUE THREAD

**Issue by han14466** [ray-project/ray#22621]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Dashboard

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/1457188/155516683-964a7e0b-0bac-4ed4-93a5-5c44373cc49d.png)

The page loads very slowly, and the constant loading of resources consumes several G

### Versions / Dependencies

ray==1.10.0
chrome

### Reproduction script

just open website

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
What's the size of the cluster? I think currently dashboard memory usage is not optimized, and we should fix this. cc @edoakes

**Comment by edoakes** [comment]
cc @alanwguo for dashboard issues!

**Comment by han14466** [comment]
> What's the size of the cluster? I think currently dashboard memory usage is not optimized, and we should fix this. cc @edoakes

3 machines.

**Comment by rkooo567** [comment]
Is it possible to see what takes up most of the payload?

**Comment by han14466** [comment]
> 

you can see it request many nodes?view=details requestions. Each of requestion is 158M

**Comment by alanwguo** [comment]
@han14466, can you try using the experimental dashboard for now? You can click the "Experimental Dashboard" in the top right of the dashboard screen.

**Comment by scottsun94** [comment]
Closing it for now. @han14466 Please reopen if this issue persists in the new dashboard.
