### ISSUE TITLE
[Release test] horovod_user_test_latest is flaky

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#22633]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

Have been seeing this quite often. Let's track it in this ticket. The failure can be fixed by retry.

https://buildkite.com/ray-project/periodic-ci/builds/2905#76273d38-7e37-406c-a499-f63da6d92cef

### Versions / Dependencies

master

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
I think this is some race condition with GPUs on ray core. Potentially related to this https://github.com/ray-project/ray/issues/22504

**Comment by amogkam** [comment]
This is not just with horovod on ray, but I've also seen ray lightning test fail with the same error. Hence why I think it's stemming from Ray core.

**Comment by xwjiang2010** [comment]
ah I see. Thanks for pointing it out. Will close this one then!
