### ISSUE TITLE
[Pandas on Ray] NaN Sometimes Incorrectly Returned from Division Instead

### ISSUE THREAD

**Issue by crystalzyan** [ray-project/ray#2263]
Hi @devin-petersohn , I retried my example on the new machine @pcmoritz gave me, and I still ran into NaNs being incorrectly returned. 

This time, I did figure how to print out the version of Ray that is installed on the new machine, so I hope you can let me know if this is indeed an old version of Ray or if this is a legitimate bug.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS (Xenial Xerus)
- **Ray installed from (source or binary)**: Unknown. Please ask Philipp Moritz, he was the one who installed Ray for me.
- **Ray version**: 0.4.0
- **Python version**: Anaconda Python 3.6.4
- **Exact command to reproduce**: 
```
import ray.dataframe as pd
#import pandas as pd

df = pd.read_csv("yellow_tripdata_2015-01-01.csv")
df2 = df[(df['tip_amount'] > 0) & (df['fare_amount'] > 0)]

df2["tip_fraction"] = df2.tip_amount / df2.fare_amount  
#df2["tip_fraction"] = df2['tip_amount'] / df2['fare_amount'] # Yields same NaN behavior 
print(df2.head(3))  # NaNs returned here
```

### Describe the problem
The output of creating new column "tip_fraction" out of tip_amount/fare_amount differs from the result returned by pandas. Some values in the new column become NaN instead. See **Source Code / Logs** section for difference in output.

Additionally, I noticed when running Ray on this new machine that the memory errors seem **much** worse than before. In my original email example, I was using the January dataset (1/12 of all of 2015 data), and was able to run several parts in succession. 

However, this time when running Ray, it would hang and spam `ObjectID already exists in the object store` error messages immediately, on any next line, right after `pd.read_csv` (with my 1/12 data, running **isolated** from pandas or anything else). I wouldn't even be able to run `df.head()` right after reading in the csv this time around.

I had to split my January dataset in half, and use only 1/24 of the 2015 data, in order to just run this test. It may have just been that the new machine has less memory, but I do hope that I am indeed running from the right version of Ray. 

You may need to similarly split the dataset in half (use `df[df['tpep_pickup_datetime'] <= '01/15/2015']`) to recreate my exact values, otherwise after the filtering different rows will be returned in the head. Though, I do remember seeing a NaN when I first did this line with the original 1/12 data.

You can get the source data csv I used at this page [http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml](url) under 2015>January>Yellow. Note that this csv file is 2 GB.

### Source code / logs
Pandas's Head(3) Output (only the relevant columns):
```
Index | tip_amount | fare_amount | tip_fraction=tip_amount/fare_amount
0     | 2.00     | 14.5    | 0.137931
4     | 6.70     | 27.0    | 0.248148
6     | 1.66     | 7.0      | 0.237143
```

Ray's Head(3) Output (only the relevant columns):
```
Index | tip_amount | fare_amount | tip_fraction=tip_amount/fare_amount
0     | 2.00     | 14.5    | 0.137931
4     | 6.70     | 27.0    | NaN
6     | 1.66     | 7.0      | NaN
```

**Comment by devin-petersohn** [comment]
Thanks for reporting this @crystalzyan!

This code: `df2['tip_amount'] / df2['fare_amount']` relies purely on pandas because we are selecting a column (and we have no distributed `Series` object yet). It may have something to do with the assignment of the new column.

**Comment by devin-petersohn** [comment]
Resolved in https://github.com/modin-project/modin/pull/10
