### ISSUE TITLE
[Feature][runtime env] refactor URI Protocol in runtime env.

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#22654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Make different protocols become different plugins. In simple terms, I want to implement a SmartURIHandle, somewhat similar to [io_path](https://github.com/facebookresearch/iopath/tree/main):

``` python

class BaseURIHandler:
    def __init__(self, uri):
        ...
    async def async_download(self, file_name):
        ...
    
    async def get_hash_from_uri(self):
        ...
    
    async def get_hash_from_file(self, local_path):    
        ...

class SmartURIHandler:

    @classmethod
    def register_handler(cls, handler: BaseURIHandler):
        ....
    
    async def async_download(self, urI):
        ...
    
    async def get_hash_from_uri(self):
        ...
    
    async def get_hash_from_file(self, local_path):    
        ...

# download file
async def download_package(uri, file_name):
    return await SmartURIHandler(uri).download(file_name)
```
This simplifies the implementation of runtime_env.packing.py, and in the future, we have the opportunity to let users define their own protocols outside of ray.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
This looks like a good idea to me. What does `register_handler` do?

**Comment by Catch-Bull** [comment]
> This looks like a good idea to me. What does `register_handler` do?

make `SmartURIHandler` have the ability to handle a specify URI, for example:

``` python
class MyURIHandler:
    PROTOCOL = "my_uri"

# this will raise exception with message "unregister protocol: my_uri "
SmartURIHandler("my_uri://test.zip")

SmartURIHandler. register_handler(MyURIHandler)

# It will be OK
SmartURIHandler("my_uri://test.zip")

```

**Comment by edoakes** [comment]
@Catch-Bull the idea looks good, but I'm not sure about the specifics of this proposal. I think we could do something simpler like define an abstract `URIHandler` and then register the supported ones like this:
```
uri_handlers: Dict[str, URIHandler] = {"http": HTTPHandler}

ray.runtime_env.register_uri_handler("custom-uri", CustomURIHandler)
```

**Comment by Catch-Bull** [comment]
> 

no problem and I will open a PR, we can discuss details in PR's comment
