### ISSUE TITLE
[Bug][RLLib] Some parameters of ComplexInputNetwork (pytorch) are not sent to CUDA

### ISSUE THREAD

**Issue by max333** [ray-project/ray#22659]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

Some member modules of ComplexInputNetwork (rllib/models/torch/complex_input_net.py) are not sent to the GPU when using .to(device) because they were not registered as modules in the constructor.

Member modules stored in a dict within a pytorch module are not registered as inner modules by default.  One must call, for example, `self.add_module("cnn_{}".format(i), self.cnns[i])` in `__init__()`.  This is done in ComplexInputNetwork for `self.cnns`.   However it was forgotten for `self.one_hot` and `self.flatten` which are also dictionaries.

### Versions / Dependencies

Ray: d4a1bc7bc7e81060c

### Reproduction script

_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dan-1d** [comment]
Seems like this is now fixed in master. https://github.com/ray-project/ray/commit/a598458c464b88535e711ef7ef55f88e25c1820f
