### ISSUE TITLE
[Feature] [Java] Redirect stdout and stderr to java-worker log file

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#22664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently only lines printed via the slf4j logger will be written to the java-worker log file. Everything else through `System.out.println` or `System.err.println` still go through the file descriptor of raylet. It would great to redirect the log over to the worker where we have setup proper log streaming solution to the driver: https://github.com/ray-project/ray/pull/22629

cc @kfstorm 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kfstorm** [comment]
Actually, we redirected all stdout and stderr logs of workers to standalone files no matter what language front end they are. I think this would be the ideal solution. @qicosmos Could you upstream the change?

**Comment by kfstorm** [comment]
There's a related issue: https://github.com/ray-project/ray/issues/13466

**Comment by qicosmos** [comment]
So we need to distinguish logs according different languages?

**Comment by simon-mo** [comment]
Ah it doesn't have to be language dependent. It's just useful when you prefix the log by language, it helps debugging and log tagging during ingestion.

**Comment by kfstorm** [comment]
> Actually, we redirected all stdout and stderr logs of workers to standalone files no matter what language front end they are. I think this would be the ideal solution. @qicosmos Could you upstream the change?

I can work on making this upstreamed.
