### ISSUE TITLE
[Dataset][Bug] map_batches() handles the combining of results from empty and non-empty batches incorrectly

### ISSUE THREAD

**Issue by naijoaix** [ray-project/ray#22673]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

The map_batches() API of Dataset produces different results for the same input data, in these two conditions:
- There are no empty batch: the result is expected
- However when there are empty batch, the result is in different format

The expected behavior should be that the result is deterministic and the same, as long as we feed it the same input data.

Logs or how to reproduce (the first one produced a list expectedly, but the second one produced pyarrow table which is not expected):
>>> xs=[x % 3 for x in list(range(100))]
>>> xs
[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0]

>>> ds1=ray.data.from_items(xs).repartition(1).sort().map_batches(lambda x: x)
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

>>> ds2=ray.data.from_items(xs).repartition(30).sort().map_batches(lambda x: x)
>>> ds2.take_all()
[{'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 0}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 1}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}, {'value': 2}]

### Versions / Dependencies

Current code at head in Ray repo.

### Reproduction script

See the above section on how to reproduce.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by naijoaix** [comment]
From BlockOutputBuffer::has_next(), it will return at least one block; and from DelegatingBlockBuilder::build(), it returns ArrowBlockBuilder if it's empty block. We might pass down the block type so it can construct the expected BlockerBuilder.

**Comment by ericl** [comment]
It might be hard to pass the block type ahead of time since the UDF given to map_batches produces a batch of unknown type, but we could potentially reconcile / merge the types of empty blocks after execution.
