### ISSUE TITLE
[Feature] [RLLib] Remove RNNSAC

### ISSUE THREAD

**Issue by max333** [ray-project/ray#22693]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

RNNSAC is badly broken.  I lost a lot of time trying to use it.  It would be an improvement to RLLib to remove it as it is not maintained.   And obviously no one has ever used it since there are no bug reports.

I found many bugs and I'm sure there are many more.

`RNNSACTrainer.validate_config()` modifies the input `config["replay_sequence_length"]`.  But config validation is called twice in the grand scheme of things and it crashes the second time it's called.

In rnn_torch_sac_policy.py:`action_distribution_fn()` calls` model.get_q_values()` (twice if twin_q) but without adding the final `actions` argument `input_dict["actions"]`.  Somehow `get_q_values()` accepts a missing `actions` and uses `None` instead.  But that crashed in my use case.  I had to pass the actions within `action_distribution_fn()`, which are anyway available as `input_dict["actions"]`.

`RNNSACTorchModel._get_q_value()` is called twice when twin_q is used.  But the input argument `model_out` is modified by the function and it crashes the second time it's called with a now modified `model_out` input.

Also I had to replace `RNNSACTorchModel.get_policy_output()` with `SACTorchModel.get_policy_output()`.  The SAC version does a lot of preprocessing to the argument `model_out` which was certainly needed for my use case.

Something else which may be completely irrelevant is that `ComplexInputNetwork.__init__()` calls `TorchModelV2.__init__(..., self.original_space, ...)`, but I changed it to `obs_space` instead of `original_space`.  I honestly can't remember why I did that; I'm not sure if I needed to change that to get RNNSAC working.   But it might break RLLib elsewhere to do that.   I'm just mentioning this so you can take a look and double check if the current `TorchModelV2.__init__(..., self.original_space, ...)` is correct.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ArturNiederfahrenhorst** [comment]
Hey max, I'm fixing a couple of things here.
Can you post an exemplary input of RNNSACTorchModel.get_policy_output() that needed preprocessing?
And maybe a short description on your setup, i.e. what do you think is particular to your usecase that RLlib handles bad as opposed to our working examples? That would be super helpful for me.

**Comment by max333** [comment]
My state was multiple levels of dicts of dicts.  

A slightly related bug I reported related to flattening a complex space: #22659.

**Comment by max333** [comment]
I generally had many problems using dicts as state space.  I often had observation out-of-bound errors because the items in the flattened observation would be in a different order from the flattened items in the specification observation space.  I had to be very careful to define everything as OrderedDict instead of plain python dicts.  I was using python 3.8 where plain dicts are actually ordered, but I was getting mismatched ordering issues nonetheless.

**Comment by ArturNiederfahrenhorst** [comment]
Hi again @max333, I have written fixes for these issue but I struggle to reconstruct what happend in the following case. 

> Something else which may be completely irrelevant is that ComplexInputNetwork.__init__() calls TorchModelV2.__init__(..., self.original_space, ...), but I changed it to obs_space instead of original_space. I honestly can't remember why I did that; I'm not sure if I needed to change that to get RNNSAC working. But it might break RLLib elsewhere to do that. I'm just mentioning this so you can take a look and double check if the current TorchModelV2.__init__(..., self.original_space, ...) is correct.

Do you think this is worth perusing? Otherwise we could close this issue.

**Comment by max333** [comment]
No.  You can close the issue.  Thanks for fixing the other issues.
