### ISSUE TITLE
[Core] Use RAAI to enforce thread safety

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#22704]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

There are many thread unsafe methods in Ray codebase. Usually the methods are only threadsafe if a lock is acquired by an outer context. 

In order to enforce thread safety, we should convert these methods to obtain the lock guard (and check the address match) from the outer context.

Examples:
- https://github.com/ray-project/ray/blob/82daf2b041172ebab18d21810988632061af751a/src/ray/core_worker/transport/direct_task_transport.cc#L151
- https://github.com/ray-project/ray/blob/82daf2b041172ebab18d21810988632061af751a/src/ray/core_worker/transport/direct_task_transport.cc#L123

Comments:
- These are private internal methods not exposed in header, but still, this style of coding is inviting a mistake to be made in my opinion. At the very least, these methods ought to be marked as "not thread-safe".

Priority:
- Background / Incremental

### Versions / Dependencies

All

### Reproduction script

See examples

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
Note that we _do_ use [absl thread annotations](https://abseil.io/docs/cpp/guides/synchronization#thread-annotations) for these methods [in the header](https://github.com/ray-project/ray/blob/82daf2b041172ebab18d21810988632061af751a/src/ray/core_worker/transport/direct_task_transport.h#L133), marking these methods as requiring the mutex to be acquired before being called.

**Comment by jon-chuang** [comment]
I see, indeed. Thank you. May I know where the behaviour to either give an error or warning for EXCLUSIVE_LOCKS_REQUIRED and related annotations is defined in ray codebase?

**Comment by rkooo567** [comment]
It should fail the compilation if it doesn't hold the lock when the method is called. I will close this for now!
