### ISSUE TITLE
[Feature] Unclear how to concretely change ray's logging directory?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ray-project/ray#22707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Pinned docs (for version we're using): https://docs.ray.io/en/releases-1.9.2/ray-logging.html#logging-directory-structure
New docs: https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure

From docs:
> The default temp directory is `/tmp/ray` (for Linux and Mac OS). If you’d like to change the temp directory, you can specify it when `ray start` or `ray.init()` is called.

It's unclear why "it" is that should be changed.

Is it something like setting `${TMPDIR}` in the environment? (I am very afraid of changing this variable)

I tried looking at `ray start --help`, but didn't see flags that looked relevant:
https://gist.github.com/EricCousineau-TRI/f32c27ebddd551a57ab90e93db45172d

### Use case

I wanted to try and look at worker logs after ray auto-shuts it down.
However, it's in `/tmp`, thus I assume removed after shutdown.

I want to 

### Related issues

Relates https://github.com/ray-project/ray/issues/19834#issuecomment-1054479958

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by EricCousineau-TRI** [comment]
As a hacky workaround, I'm doing something silly like this via `setup_commands`:

```sh
# HACK: Save ray logs
# TODO(eric): Unclear how to change logging directory?
# https://docs.ray.io/en/releases-1.9.2/ray-logging.html#logging-directory-structure
old_log_dir=/tmp/ray
new_log_dir=~/ray-logs
if [[ ! -L ${old_log_dir} ]]; then
    if [[ -d ${new_log_dir} ]]; then
        echo "Shouldn't already exist" >&2
        exit 1
    fi

    if [[ -d ${old_log_dir} ]]; then
        mv ${old_log_dir} ${new_log_dir}
    else
        mkdir -p ${new_log_dir}
    fi

    ln -s ${new_log_dir} ${old_log_dir}
fi
```

**Comment by EricCousineau-TRI** [comment]
Yep, that'd be awesome, thanks!

But I was unable to figure this out w/ command-line args; I see the code (in 1.9.2) in this region:
https://github.com/ray-project/ray/blob/ef593fe5d3c864836b80ae77be32635cef42b537/python/ray/scripts/scripts.py#L434-L438

But I did not see all of these flags when looking at `ray start --help`:
https://gist.github.com/EricCousineau-TRI/f32c27ebddd551a57ab90e93db45172d#file-output-txt-L64-L69

Is this a bug w/ `ray`, or perhaps `click`?

**Comment by EricCousineau-TRI** [comment]
(I can file a separate issue, if that helps!)

**Comment by rkooo567** [comment]
I think it is because it is set to `hidden=True`. Hmm my guess is this is for some reasons not promoted as a public API

**Comment by EricCousineau-TRI** [comment]
Ooh, didn't even look at that haha.

But yeah, if it's in the documentation, perhaps it'd be good to promote to public?

**Comment by saswatac** [comment]
I tried the --temp-dir option.  It did change the logging directory, but does it also have other side effects? 

When I point the temp dir to a location in shared mount ( specifically Azure files) , ray fails to start. I get the following error in raylet.err

```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  bind: Operation not permitted
*** SIGABRT received at time=1646221892 on cpu 1 ***
PC: @     0x7f976e984fb7  (unknown)  raise
    @     0x7f976f890980  290693328  (unknown)
    @     0x7f976ed32760  (unknown)  (unknown)
    @     0x7f976ed32703  (unknown)  (unknown)
[2022-03-02 11:51:32,905 E 888 918] logging.cc:317: *** SIGABRT received at time=1646221892 on cpu 1 ***
[2022-03-02 11:51:32,905 E 888 918] logging.cc:317: PC: @     0x7f976e984fb7  (unknown)  raise
[2022-03-02 11:51:32,906 E 888 918] logging.cc:317:     @     0x7f976f890980  290693328  (unknown)
[2022-03-02 11:51:32,906 E 888 918] logging.cc:317:     @     0x7f976ed32760  (unknown)  (unknown)
[2022-03-02 11:51:32,906 E 888 918] logging.cc:317:     @     0x7f976ed32703  (unknown)  (unknown)
```

**Comment by rkooo567** [comment]
Hmm looks like the process probably just doesn’t have the access to the shared mount? Maybe you can try with sudo to verify (if you run ray start, also do sudo ray start)

**Comment by saswatac** [comment]
I don't think that is the case. The process is running in a container in kubernetes with the root user. And the logs actually get written to the files in the mount location.

**Comment by zhanwenchen** [comment]
Not everyone runs `ray start`. In fact, for distributed training, I have yet to see a single repo that does `ray start`.

**Comment by zhanwenchen** [comment]
> Hmm looks like the process probably just doesn’t have the access to the shared mount? Maybe you can try with sudo to verify (if you run ray start, also do sudo ray start)

Can't request sudo on an HPC cluster.
