### ISSUE TITLE
[Bug] Train PBT example is not using checkpointing

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#22733]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### What happened + What you expected to happen

Train PBT example is not using checkpointing, which is necessary for PBT to work as intended.

### Versions / Dependencies

Ray 1.11

### Reproduction script

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Yard1** [comment]
@amogkam @matthewdeng can this be closed?

**Comment by matthewdeng** [comment]
@Yard1 this hasn't been fixed yet. Adding to backlog!

**Comment by xwjiang2010** [comment]
Is this still relevant? @matthewdeng

**Comment by matthewdeng** [comment]
Looks like it's still not fixed? 

https://github.com/ray-project/ray/blob/master/python/ray/train/examples/tune_cifar_torch_pbt_example.py
