### ISSUE TITLE
[serve] No scaledown due to HTTP proxies on empty nodes

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#22734]
Serve currently targets all nodes in the cluster when `EveryNode` is set (even if they're otherwise empty), so Ray can never relinquish nodes when they're started.

We should instead maintain the invariant that the HTTP proxy only runs on the head node + any worker nodes that have deployment actors on them.

**Comment by kristinepetrosyan** [comment]
Thank you Edward!

**Comment by simon-mo** [comment]
@edoakes weird thing is that we already set `num_cpus=0` and autoscaler should ignore those actors. I'll try to repro.

**Comment by kristinepetrosyan** [comment]
This is issue is still appears to be there. It scales down all the actors but not the HTTP Proxy so at the end I have 7 workers being there empty and I need to manually delete them.

**Comment by architkulkarni** [comment]
Reopening, root cause found here https://github.com/ray-project/ray/issues/25414#issuecomment-1156775703
