### ISSUE TITLE
[rllib] Is A3C algorithm using async_optimizer implemented correctly as the algorithm stated in original paper?

### ISSUE THREAD

**Issue by luochao1024** [ray-project/ray#2273]
### Describe the problem

In the [async_optimizer](https://github.com/ray-project/ray/blob/master/python/ray/rllib/optimizers/async_optimizer.py), it uses a list to store all the tasks, and waits for the first element in the list and then processes it. Finally, it appends a new element to the end of the list and then repeats the loop. In this implementation, if somehow the first element in the list is processing really slowly, and many other elements have finished their tasks, then they all need to wait for the first one. Actually, this implementaion is not the same as stated in ray's official documentation [here](https://ray.readthedocs.io/en/latest/example-a3c.html), which uses `ray.wait(gradient_list)`. The async_optimizer does not use` ray.wait() `is because the `ray.wait()` does not work because of [this issue](https://github.com/ray-project/ray/issues/1128).

However, in the [original paper](https://arxiv.org/abs/1602.01783) by google, each worker updates the policy without waiting for anything. 

Why don't we use the same strategy as the one in [async_parameter_server](https://github.com/ray-project/ray/blob/master/examples/parameter_server/async_parameter_server.py). In this strategy, every worker does its own job without waiting for anybody.

Here is the pseudocode to change the original async_optimizer:
```
def _init(self):
    self.global_iteration = 0 

@ray.remote
def _help_step(self, evaluator_index):
    e = self.remote_evaluators[evaluator_index]
    while self.global_iteration < self.grads_per_step:
        e.set_weights.remote(self.local_evaluator.get_weights())
        fut = e.compute_gradients.remote(e.sample.remote())
        gradient, _ = ray.get(fut)
        self.local_evaluator.apply_gradients(gradient)
        self.global_iteration += 1

def step(self):
    workers = [_help_step.remote(i) for i in len(self.remote_evaluators)]
```

If we use this strategy, we can finish the whole training by calling step method once.

**Comment by ericl** [comment]
The reason is that there's a bit of a bug in ray.wait at the moment: https://github.com/ray-project/ray/issues/1128

We've found that this doesn't really affect performance though. For A3C, the driver is usually the bottleneck and not the workers, so the worker results are always ready to apply.

**Comment by ericl** [comment]
@richardliaw might have more comments on using a PS instead

**Comment by luochao1024** [comment]
Does the driver limit the range of cpus for async_optimizer stated [here](https://github.com/ray-project/ray/blob/master/doc/source/policy-optimizers.rst#available-policy-optimizers)? It only works with at most 10 cpus. If using a parameter_server strategy, can it scale to more cpus?

**Comment by ericl** [comment]
We've seen effective scaling up to 16 CPUs on Atari. You can add more workers, but whether you will see performance gains depends on the problem specific details.

**Comment by ericl** [comment]
We also have seen better scalability with a sharded param server strategy, however this isn't merged into the repo yet.

**Comment by richardliaw** [comment]
To answer your question, there is no enforced limit on the range of CPUs (workers), and the scaling is essentially the same when using a `parameter_server` strategy.

There is a `sharded_parameter_server` strategy that I have tried (and is not yet merged), and there I've been able to scale performance gains up to ~40 CPU workers. 

Would you be interested in trying it out?

**Comment by luochao1024** [comment]
@ericl Thanks

@richardliaw I would like to see the sharded_parameter_server strategy you mentioned above. Would you mind sharing it here?

**Comment by richardliaw** [comment]
Sure sounds good, although I haven't used it in a while. https://github.com/richardliaw/ray/tree/shard_autoscale/python/ray/rllib/shard

It's a little messy, but `test_shard.py` should work if you copy the entire `shard/` directory out of the repository and fix the imports. 

Let me know if you have any questions, and if you think it's useful, feel free to create a PR :)

**Comment by luochao1024** [comment]
@richardliaw Thank you~
