### ISSUE TITLE
[Bug][Serve] Excessive ServeController Log Output

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#22745]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Serve

### What happened + What you expected to happen

1. Got: The ServeController under normal circumstances is producing excessive output from the GCS
2. Expected: The ServeController only shows logs when it adds/removes/attempts to autoscale, or provides a way to configure the log level (preferably not including the GCS logs by default)
3. The beginning of a sample log looks like: `DEBUG gcs_utils.py:253 -- internal_kv_put b'SERVE_CONTROLLER_ACTOR-serve-serve-deployment-state-checkpoint` followed by a binary dump of the deployment.

### Versions / Dependencies

Ray 1.10.0
Python 3.7.12
Ubuntu 20.04
Kubernetes Cluster w/ Ray Operator

### Reproduction script

Wasn't able to replicate it locally with `ray start --head` -- this has occurred regularly with a deployment on our k8s cluster, though.

### Anything else

First few lines of the `ServeController` startup log are:
```
:actor_name:ServeController
2022-02-25 20:02:35,819 INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
2022-02-25 20:02:35,927 INFO http_state.py:101 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:IP_ADDRESS' on node 'node:IP-ADDRESS' listening on '127.0.0.1:8000'
2022-02-25 20:05:09,015 DEBUG gcs_utils.py:253 -- internal_kv_put b'SERVE_CONTROLLER_ACTOR-serve-serve-deployments-snapshot' b'{}
' True serve
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Can you provide us a repro script?

**Comment by spolcyn** [comment]
We've found the root cause here -- the `ray.ray_operator.operator_utils` module always sets the `ray` logger to `DEBUG` level, and we imported that module.

Likely a question for the team working on the operator, but is that intended behavior?
