### ISSUE TITLE
[Bug]Can't kill a placement group from placement group table.

### ISSUE THREAD

**Issue by ZhijieWang** [ray-project/ray#22774]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Xgboost ray kicks off some placement group which i do not control. It kicks off some infeasible ones and tried to kill it so the autoscaler can get back to a normal state faster.
Tried to list placement group, and kill placement group from there. 

### Versions / Dependencies

Ray 1.9.2

### Reproduction script

Launch xgboost_ray in a different driver.
Open a new driver and do below.
```
import ray
from pprint import pprint

# Import placement group APIs.
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group
)
placement_group_table()
remove_placement_group(placement_group_table()["af508d2c7fc62ac972e841bee7f26b8c"])
```
`af508d2c7fc62ac972e841bee7f26b8c` is one of the placement groups printed by placement_group_table() 

### Anything else

There is no way to reconstruct a placement group from the id etc.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
@ericl @rkooo567

**Comment by rkooo567** [comment]
While I think it is possible to support, I have some questions;

1. Can you tell me a bit more about "autoscaler can get back to a normal state faster."?
2. It is a bit weird to me xgboost starts infeasible ones, and you try killing it manually while the xgboost job is still running. Is it impossible to make xgboost job to not have infeasible pgs instead? (by modifying your resource requirement or etc..).

**Comment by ZhijieWang** [comment]
@rkooo567  the whole history with xgboost having infeasible placement group is a long complicated story. multiple issues filed involving infra team and many others. I ran into this during my attempt to repro and isolate issues.
"autoscaler can get back to a normal state faster." -- The placement group will hang around for a couple min, and i need to kill it to trigger a new set of auto scaling behavior and test different things. I don't think this is a critical and urgent issues, but realized that there is no way to get a `pg` from table and kill it.

**Comment by zhe-thoughts** [comment]
I'm on the fence whether this P1 or P2 (not sure how common the need is). @rkooo567 what do you think?

Once we decide a priority, could you help remove the `triage` label? Thanks!

**Comment by rkooo567** [comment]
looks like the use case is a bit niche (could be useful for Jupyter based workload). I will mark it P2. I think what we really need is this

```python3
pg = ray.get_placement_group(id=placement_group_table()["af508d2c7fc62ac972e841bee7f26b8c"])
remove_placement_group(pg)
```

There's an issue that we track to implement `get_placement_group(id=)`. If anyone is interested in this feature, please comment. We can prioritize it.

**Comment by rkooo567** [comment]
Hmm it is supposed to be killed when a driver is dead. if you do ray list placement-groups --detail, does it show detached: True?

**Comment by jaysin60** [comment]
It shows False:

`placement_group_id: 622a5ef17e545b520a4ac54f787101000000
    name: ''
    creator_job_id: '01000000'
    state: CREATED
    bundles:
    -   bundle_id:
            placement_group_id: 622a5ef17e545b520a4ac54f787101000000
            bundle_index: 0
        unit_resources:
            CPU: 10.0
            GPU: 8.0
        node_id: dd1ccd89cdf608b4b4736b7a28cf4e4f947f812a8474a592a86e2776
    -   bundle_id:
            placement_group_id: 622a5ef17e545b520a4ac54f787101000000
            bundle_index: 1
        unit_resources:
            CPU: 10.0
            GPU: 8.0
        node_id: b99a43b168d6dd47e64f72c76a069a08d9fc4f111e6b10734ea694e6
    -   bundle_id:
            placement_group_id: 622a5ef17e545b520a4ac54f787101000000
            bundle_index: 2
        unit_resources:
            CPU: 10.0
            GPU: 8.0
        node_id: 776959bf754289d1a5453e7c1e2f52023354462a0c695bc7abf29ea4
    -   bundle_id:
            placement_group_id: 622a5ef17e545b520a4ac54f787101000000
            bundle_index: 3
        unit_resources:
            CPU: 10.0
            GPU: 8.0
        node_id: 216724fcc2733007d77fe069b0f6aede67de16b3eba697f289a10835
    is_detached: false
    stats:
        creation_request_received_ns: '1713173811059887734'
        scheduling_started_time_ns: '1713173811059938394'
        scheduling_latency_us: '2541'
        end_to_end_creation_latency_us: '2592'
        scheduling_attempt: 1
        scheduling_state: FINISHED
        highest_retry_delay_ms: 0.0`

**Comment by rkooo567** [comment]
that's pretty weird. you are not using very old version of ray right?

**Comment by jaysin60** [comment]
Latest version of ray and xgboost_ray
```
ray                       2.10.0
xgboost-ray               0.1.19
```

After further investigation I found out actors were still alive even though the tasks have failed. So I killed the actors but still those those resources were reserved by placement-group.

**Comment by lonsdale8734** [comment]
@ZhijieWang work around by such code:

```python
from ray._raylet import PlacementGroupID
from ray._private.utils import hex_to_binary
from ray.util.placement_group import (
    PlacementGroup,
    placement_group_table,
    remove_placement_group,
)
import ray

ray.init()


for placement_group_info in placement_group_table().values():
    # https://github.com/ray-project/ray/blob/ray-2.7.0/python/ray/util/placement_group.py#L291
    pg = PlacementGroup(
            PlacementGroupID(hex_to_binary(placement_group_info["placement_group_id"]))
    )
    remove_placement_group(pg)
```
