### ISSUE TITLE
[Bug] Lots of "Fork support is only compatible with the epoll1 and poll polling strategies" errors / warnings?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ray-project/ray#22772]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

When using `ray.init()`, I see a lot of log messages, like:
```
(pid=239166) E0302 12:30:34.713597133  240459 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies
```

This doesn't seem to hurt performance.

Ideally, these errors / warnings don't exist.

Altenatively, there's a way to supress this across the full chain of `ray` processes (we are using cluster functionality).

### Versions / Dependencies

ray 1.9.2
CPython 3.8.10
Ubuntu 20.04

### Reproduction script

I do not have one externally shareable on hand. Can do so if requested (w/ some lead time).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/22518 -- seems workaround is to downgrade grpc.
