### ISSUE TITLE
specify dependencies versions

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2278]
Hi,

I am trying to follow the ray [tutorials](https://github.com/ray-project/tutorial). Nevertheless, I found several bug with save/load functional in ray 0.4 and decide to move to the master brach.

Unfortunately, I again come to bugs, but now with dependencies versions (lz4 package). I tried different versions (1.0.0, 1.1.0, 2.0.0), but all gives the same error:
```
     36 with ignoring(ImportError):
     37     import lz4
---> 38     compress['lz4'] = lz4.LZ4_compress
     39     decompress['lz4'] = lz4.LZ4_uncompress
     40 

AttributeError: module 'lz4' has no attribute 'LZ4_compress'
```

So, can you provide package version to reduce number of such issues? And is it correct, that ray version 0.5 would be available soon?

Thanks!

**Comment by richardliaw** [comment]
Can you post a full stack trace of the error?

Often times when I run into lz4 issues, I can resolve it by running `pip
install -U dask`.

**Comment by robertnishihara** [comment]
Yeah, that's probably the issue, also see https://github.com/ray-project/ray/issues/2137#issuecomment-391967245.

**Comment by Scitator** [comment]
Thanks, now all works perfectly.

Just to be sure, I want to implement several RL algos with Ray (I found it really great one with a lot of cool stuff). But with PyTorch neither TensorFlow. So, what is the best way to [start with](ray.readthedocs.io/en/latest/rllib-dev.html)?
Are there any PyTorch examples? (paper says they should be)

**Comment by richardliaw** [comment]
That's great - there's an example implementation of [A3C in PyTorch in the code base here](https://github.com/ray-project/ray/blob/master/python/ray/rllib/a3c/a3c_torch_policy.py) 

One thing you could take a look at is trying to implement the standard Policy Gradient in PyTorch. The current [tensorflow version is here](https://github.com/ray-project/ray/blob/master/python/ray/rllib/pg/pg_policy_graph.py). 

If you have any feedback or questions, feel free to reach out, either via github or on our mailing list!

**Comment by robertnishihara** [comment]
It's still pretty common to encounter this issue. I wonder if we should include something in RLlib that checks if lz4 is installed and if tensorflow is being used and then raises a better exception.

The issue is where to put the check. We basically want the check to happen iff `tf.contrib` is being used I think.

Another solution is to remove our usage of `tf.contrib`.

**Comment by silverbacknet** [comment]
It looks like this was fixed for good in https://github.com/ray-project/ray/commit/8b6f0d3224055e5e028569e31cfd56316f7ce29e
