### ISSUE TITLE
[Feature] [Docs] Improve connection between library references and their APIs

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#22791]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently, the API references for each Ray ML library is stored under "References" in the "API References" drop-down menu:

<img width="334" alt="Screen Shot 2022-03-02 at 5 07 17 PM" src="https://user-images.githubusercontent.com/92341594/156476504-d8f36de3-e2c7-4d4b-ae9c-27313faba6dc.png">

However, the rest of each library's documentation is stored separately. For example, there's no clear link between Ray Serve's documentation and its API:

<img width="335" alt="Screen Shot 2022-03-02 at 5 08 20 PM" src="https://user-images.githubusercontent.com/92341594/156476612-02dd588f-6b8d-4d12-a40f-63927010536c.png">

As an example, the previous Ray documentation format had this hyperlink:

<img width="257" alt="Screen Shot 2022-03-02 at 5 09 26 PM" src="https://user-images.githubusercontent.com/92341594/156476756-1bbff923-13fd-4064-aac9-c10ec5eccac9.png">

Two suggestions to improve connectivity between each library's documentation and its API:

1. Add a hyperlink in each library's section to its API.
2. Keep the "References" section but remove the "API References" top level drop drown. If only "API References" are stored in "References", it seems ok to move all the API references directly under "References" instead of nesting them in another drop down.

### Use case

Improve the user journey from documentation to API and back.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
cc @maxpumperla i think we've had this discussion multiple times, would be great to document the decision

**Comment by maxpumperla** [comment]
@shrekris-anyscale please have a look at Tune, where we have it in both places. I think there's benefit to both (central API section vs per-lib). Just duplicate the docs in the toc.yml

**Comment by shrekris-anyscale** [comment]
Closed by #22800.
