### ISSUE TITLE
Using gflags or similar for argument parsing

### ISSUE THREAD

**Issue by danielsuo** [ray-project/ray#2280]
Did a quick search through the issues list and didn't see anything related. Since the raylet code is fast-moving, it may be helpful to rely on an argument parsing library for ```raylet``` and ```raylet_monitor``` rather than magic numbers for argument positions.

Should be a small change, but raising as an issue rather than PR first because there may be some reason that the team doesn't want to do this.

**Comment by robertnishihara** [comment]
You're completely right.

We do it *slightly* better in legacy Ray 

https://github.com/ray-project/ray/blob/6bf48f47bcf91610db42b350e8149c85e01afb0d/src/local_scheduler/local_scheduler.cc#L1522-L1557

but if there's a more canonical C++ way of parsing arguments, that would be preferable.

**Comment by danielsuo** [comment]
Yeah, getopt is the POSIX way. There are innumerable c++ libraries doing this now, but [gflags](https://gflags.github.io/gflags/) seems to be reasonably popular. Some people don’t like the dependence on macros, though.

Boost also has a library and we already have that dependency.

**Comment by concretevitamin** [comment]
+1 to gflags.
