### ISSUE TITLE
Make redis ray pass ci testing

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#22814]
Due to lack testing for some period of time, redis ray is failing some tests. We should fix it and put the tests for it.

https://github.com/ray-project/ray/pull/22458/files

**Comment by scv119** [comment]
@iycheng can you close this if it's fixed?

**Comment by iycheng** [comment]
No yeat.

**Comment by iycheng** [comment]
duplicate https://github.com/ray-project/ray/issues/23155
