### ISSUE TITLE
[Scheduler] refactor scheduler data structures 

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#22850]
The current scheduler data structures (defined in `src/ray/raylet/scheduling/cluster_resource_data.h`) expose too many implementation details. This makes all the use sites have to deal with the concrete vectors and maps, and also leads to copy-pasted code.
I'd like to introduce a better abstraction to solve this problems. 

Current structure:
```
// Non-instance-level data structures:
// Resource request of a task
ResourceRequest:
- predefined_resources: std::vector<FixedPoint> 
- custom_resources: absl::flat_hash_map<int64_t, FixedPoint>

// Total and available values for a particular resource
ResourceCapacity:
- total: FixedPoint
- available: FixedPoint

// Resources of a node
NodeResources:
- predefined_resources: std::vector<ResourceCapacity>
- custom_resources: absl::flat_hash_map<int64_t, ResourceCapacity>

=========

// Instance-level data structures:
// Meanings same as above.
TaskResourceInstances:
- predefined_resources: std::vector<std::vector<FixedPoint>>
- custom_resources: absl::flat_hash_map<int64_t, std::vector<FixedPoint>>

ResourceInstanceCapacities:
- total: std::vector<FixedPoint>
- available: std::vector<FixedPoint>

NodeResourceInstances:
- predefined_resources: std::vector<ResourceInstanceCapacities>
- custom_resources: absl::flat_hash_map<int64_t, ResourceInstanceCapacities>
```

Proposed refactor:
```
// A set of predefined resources
// Encapsulates all the operators, such as Size, DebugString, GetCPU, GetGPU(), algebra operators, etc.
PredefinedResources:
- values: std::vector<FixedPoint>

// A set of custom resources 
CustomResources:
- values: absl::flat_hash_map<int64_t, std::vector<FixedPoint>>

// A set of resources, including predefined and custom resources. 
// Should be used as a basic unit of resource requirement.
// Provides
// - a Get(string resource_name) method that will look up both predefined and custom resources.
// - an iterator that allows looping over both predefined and custom resources.
// - algebra operators, etc.
ResourceRequest:
- predefined_resources: PredefinedResourceSet
- custom_resources: CustomResourceSet

// Resources of a node
// "normal_task_resources_" for GCS-based scheduling will also be added here. 
NodeResources:
- available: ResourceRequest;
- total: ResourceRequest;

========

// Instance-level data structures:
// Meanings same as above.
PredefinedResourceInstances:
- values: std::vector<std::vector<FixedPoint>>

CustomResourceInstances:
- values: absl::flat_hash_map<int64_t, std::vector<FixedPoint>>

TaskResourceInstances:
- predefined_resources: PredefinedResourceInstances
- custom_resources: CustomResourceInstances

NodeResourceInstances:
- total: TaskResourceInstances
- available: TaskResourceInstances
```

@ericl @scv119 @iycheng @wumuzi520 @Chong-Li @WangTaoTheTonic

**Comment by raulchen** [comment]
I plan to submit 2 PRs: one for non-instance-level resources, and one for instance-level. #22854 is the first one. It's not ready yet, just in case someone may want to see what the refactor will look like.
Basically the main idea is to hide the implementation details about the underlying arrays and maps, while retaining the current optimizations.

**Comment by raulchen** [comment]
Yeah, actually I wanted to rename "ResourceRequest" to "ResourceSet" as well. Because "request" is a bit too specific, and "set" is more general. But later I decided to hold on this change, in order to minimize the refactor.  
So, I'm going to keep the current name as the first step. If everyone agrees on "ResourceSet". I'm happy to do the renaming, after we remove the old "ResourceSet".

**Comment by scv119** [comment]
> // Resources of a node
> // "normal_task_resources_" for GCS-based scheduling will also be added here. 
> NodeResources:
> - available: ResourceRequest;
> - total: ResourceRequest;

If we decide not rename ResourceRequest, then we shouldn't put ResourceRequest into NodeResources; it's just very confusing.

**Comment by raulchen** [comment]
Also, regarding the optimization of using arrays for predefined resources. I also suspect the performance gains. 
But still, as the first step, my plan is to hide the array inside a "PredefinedResources" class. After this, it should be easy to change the underlying implementation.

**Comment by raulchen** [comment]
> > // Resources of a node
> > // "normal_task_resources_" for GCS-based scheduling will also be added here.
> > NodeResources:
> > 
> > * available: ResourceRequest;
> > * total: ResourceRequest;
> 
> If we decide not rename ResourceRequest, then we shouldn't put ResourceRequest into NodeResources; it's just very confusing.

I'm with you on this point. I'll vote for renaming.

**Comment by WangTaoTheTonic** [comment]
Voting for adding algebra operations in resource data structure, as current structure is pretty raw and the for loop to handle  `predefined_resources/custom_resources` is every where.

**Comment by jjyao** [comment]
https://github.com/ray-project/ray/pull/38650#pullrequestreview-1590444839
