### ISSUE TITLE
[serve]The interaction between Java API and Unified Controller API

### ISSUE THREAD

**Issue by liuyang-my** [ray-project/ray#22858]
In a complete Java user case, the cross language interaction between Java API and Python controller will be involved, such as starting a serve, deploying a deployment, querying the deployment status, and so on. The proposal of [Serve Unified Controller API](https://docs.google.com/document/d/1Yb9eZIQ4cZWypWZj4bK__7nDXWgthoj52QRg8FOFmNY/edit#heading=h.mttk25m16f6c) can solve this cross language problem. 

This issue lists the parts where the Java API interacts with the Controller API, as well as the related modification schemes.

### deploy
parameters:
| parameter name | parameter type |
| :----: | :----: |
| name | str |
| deployment_config_proto_bytes | bytes |
| replica_config | ReplicaConfig |
| version | Optional[str] |
| prev_version | Optional[str] |
| route_prefix | Optional[str] |
| deployer_job_id | "ray._raylet.JobID" |

* Merge `version`, `prev_version` into `DeploymentConfig`.
* Define `ReplicaConfig` protobuf.

### get_http_proxies
return: `Dict[NodeId, ActorHandle]`
* Change to the `ActorList` protobuf which contains an actor name list.

### get_deployment_info
return: `Tuple[DeploymentInfo, str]`
* Define a protobuf like `DeploymentRoute` composed of the `DeploymentInfo` and the `route_prefix`.

### list_deployments
return: `Dict[str, Tuple[DeploymentInfo, str]]`
* Define `DeploymentRouteList` protobuf containing the `DeploymentRoute` list.

### get_deployment_statuses
return: `Dict[str, DeploymentStatusInfo]`
* Define `DeploymentStatusInfo` protobuf.
* Define `DeploymentStatusInfoList` containing the `DeploymentStatusInfo` list.

**Comment by shrekris-anyscale** [comment]
What is the `str` that `get_deployment_info` returns?

**Comment by liuyang-my** [comment]
> What is the `str` that `get_deployment_info` returns?

The `str` in `get_deployment_info` returned value is `route_prefix`.
