### ISSUE TITLE
[docs] [rllib] Create Examples section with notebooks

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#22868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

We have a lot of links to GitHub Python scripts in RLlib, but very little in terms of walkthroughs/tutorials/examples.

Follow [Tune User Guides](https://docs.ray.io/en/master/tune/tutorials/overview.html) and [Tune Examples](https://docs.ray.io/en/master/tune/examples/index.html) to get an idea of what we're aiming for.

**Comment by dynamicwebpaige** [comment]
+1 for examples in `.ipynb` form! 🤗 

You can also regularly run these notebooks as makeshift integration tests, via cron or via GitHub Action, to ensure that updates to the APIs don't break existing functionality.

**Comment by maxpumperla** [comment]
hey @dynamicwebpaige, thanks! For our existing notebooks we already have a quick bazel rule in place that picks them all up in CI:

https://github.com/ray-project/ray/blob/master/doc/BUILD#L141-L147
