### ISSUE TITLE
[docs] [serve] Split into user guides and examples 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#22873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Similar to Tune, have a user guide (with overview page) consisting of:

- Calling Deployments
- Deploying Ray Serve
- Serving ML Models
- Using the Pipeline API
- Performance Tuning

What's currently called "Advanced Tutorials" corresponds to what we call "Examples" in other parts (again, see "Tune"). This "Examples" section should have an overview page as well.

**Comment by simon-mo** [comment]
It's done!
