### ISSUE TITLE
[docs] [clusters] Create landing page 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#22874]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The "Ray Cluster Quick Start" is quite informative, but there's very little in the way of "why" use Ray Clusters and "what" this project is. Create a landing page for this project similar to that of Tune. This can include the current quick start or not. In particular, we should clearly talk about what to expect from this project.

**Comment by zhe-thoughts** [comment]
Thanks @maxpumperla . Could you add the best example we have on a landing page? Would it be Tune? https://docs.ray.io/en/master/tune/index.html

**Comment by maxpumperla** [comment]
@zhe-thoughts yes
