### ISSUE TITLE
[jobs] Automatically set `RAY_ADDRESS` env var so users don't need to set `address="auto"`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#22884]

**Comment by edoakes** [comment]
@architkulkarni should be a quick fix: just need to set the env var in the supervisor actor.

**Comment by architkulkarni** [comment]
@jiaodong Actually, isn't this already fixed by https://github.com/ray-project/ray/issues/21938?  I changed all the scripts in `tests/subprocess_driver_scripts` to just use `ray.init()` and it still passed.

**Comment by architkulkarni** [comment]
@jiaodong specifically this part: https://github.com/ray-project/ray/blob/ebac18d1633d966ca2634cee1ee8a7e4b4d0b061/dashboard/modules/job/job_manager.py#L211-L218
