### ISSUE TITLE
[Bug][core] Plasma store should evict plasma-allocated objects immediately

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#22883]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

The plasma store only evicts objects when it needs to make space for a new object. This is fine because the objects are stored in shared memory, so it doesn't hurt to keep the extra copies around. However, if the object is fallback-allocated, we should actually try to evict it as soon as possible since this is taking up shared resources past the amount allocated to the plasma store. This can lead to higher-than-expected memory usage if no GC is triggered for a while.

### Versions / Dependencies

Ray 2.0dev

### Reproduction script

`test_plasma_unlimited.py::test_task_unlimited` with this modification to fix the flakiness:

```python
def test_task_unlimited():
    try:
        address = _init_ray()
        x1 = ray.put(np.zeros(400 * MB, dtype=np.uint8))
        refs = [x1]
        # x1 is spilled.
        x2 = ray.put(np.zeros(400 * MB, dtype=np.uint8))
        x2p = ray.get(x2)
        sentinel = ray.put(np.zeros(100 * MB, dtype=np.uint8))
        _check_spilled_mb(address, spilled=400)

        @ray.remote
        def consume(refs):
            # triggers fallback allocation, spilling of the sentinel
            ray.get(refs[0])
            # triggers fallback allocation.
            return ray.put(np.zeros(400 * MB, dtype=np.uint8))

        # round 1
        _ = ray.get(ray.get(consume.remote(refs)))  # <-- Originally just ray.get(consume.remote(refs))
        _check_spilled_mb(address, spilled=500, restored=400, fallback=400)

        del x2p
        del sentinel
    finally:
        ray.shutdown()
```

However, this change actually causes the test to fail every time because the fallback allocation is higher than expected, since the worker's old ref isn't getting evicted by the plasma store.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment]
cc @scv119?

**Comment by scv119** [comment]
> This can lead to higher-than-expected memory usage if no GC is triggered for a while.
For clarification, is this just a reporting issue or the fallback allocation has caused actual problems (like OOM)?
Assume the later case, does an eager eviction on fallback allocated objects suffice?

**Comment by stephanie-wang** [comment]
I haven't actually seen it cause issues, but I imagine it could in an adversarial case. The reason I found this was that the actual allocation was higher than expected, causing the flaky test (once fixed) to fail.

Yes, I think an easy fix is just to trigger eviction of fallback-allocated objects as soon as there are no more clients.

**Comment by ericl** [comment]
We were discussing this issue offline and concluded this isn't necessary since fallback-allocated objects are already part of the normal spilling / deletion path. So:
1. Either they're un-refed, at which point they're eagerly deleted.
2. Or memory pressure will trigger eviction / spilling, which will spill the fall-back allocated object and free it.

Having fallback-allocated objects hanging around can lead to higher _virtual_ memory usage than normal, but not higher resident / shm memory usage.

In the longer term, when we have priority order of spilling / eviction, it does make sense to prioritize spilling / evicting fallback objects to potentially reduce virtual memory usage / filesystem paging.
