### ISSUE TITLE
[Bug] SampleBatch.timeslices() causes infinite loop

### ISSUE THREAD

**Issue by ZaberKo** [ray-project/ray#22888]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When the SampleBatch size cannot be divided by `timeslices()` argument `size`, the internal loop will not meet the break condition. This is caused by the wrong loop condition (should be things like `while left>0`). See
https://github.com/ray-project/ray/blob/5ea565317a8104c04ae7892bb9bb41c6d72f12df/rllib/policy/sample_batch.py#L563-L570

### Versions / Dependencies

Ray version: 1.10.0
Python: 3.9.10
OS: Ubuntu 20.04

3rd lib: None

### Reproduction script

```python
#%%
import ray
from ray.rllib.agents.a3c import A2CTrainer,DEFAULT_CONFIG
from ray.rllib.evaluation import SampleBatch

ray.init(include_dashboard=False)
#%%
config=DEFAULT_CONFIG.copy()
config['framework']='torch'
config["rollout_fragment_length"]=200

trainer=A2CTrainer(config,env="CartPole-v1")

# %%
worker=trainer.workers.remote_workers()[0]
data=ray.get(worker.sample.remote())
data.timeslices(size=23) # stuck at here
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
@pcmoritz Can I look into this?

**Comment by czgdp1807** [comment]
Confirmed. There are two places which use `while left:` which should be replaced with `while left > 0:`. Making a PR to do that.

**Comment by czgdp1807** [comment]
Seems like already fixed in `master`. Closing it then.
