### ISSUE TITLE
[Ray]The driver hangs in the second run on a ray cluster and a possible solution

### ISSUE THREAD

**Issue by luweichao** [ray-project/ray#2288]
When I run the following task for a second time on a ray cluster, the driver hangs.

```
python ~/env/program/anaconda3/envs/py35/lib/python3.5/site-packages/ray/rllib/train.py
--env=Pong-ram-v4 --run=A3C --config='{"num_workers": 20, "use_gpu_for_workers": false}' --redis-address=192.168.1.53:6379
```

I added some logs and get the bug.

  An A3CAgent actor trains for one step and puts back a TrainingResult object to the driver, but the driver does not know how to deserialize the TrainingResult object. This is because in the previous run the A3CAgent actor puts a TrainingResult Object back to the driver and registered a custom serializer which is stored in Redis with key "Exports". Then in the second run the driver and worker will read custom serializer registered in Redis with key "Exports", but the driver will ignore those serializers not registered by itself. 

```
def fetch_and_execute_function_to_run(key, worker=global_worker):
    """Run on arbitrary function on the worker."""
    driver_id, serialized_function = worker.redis_client.hmget(
        key, ["driver_id", "function"])

    if (worker.mode in [SCRIPT_MODE, SILENT_MODE]
            and driver_id != worker.task_driver_id.id()):
        # This export was from a different driver and there's no need for this
        # driver to import it.
        return
```

So, the following is a possible solution, but not very good. I wonder if you have a better solution.

```
diff --git a/python/ray/worker.py b/python/ray/worker.py
index 84e88e18..f2a7c6b6 100644
--- a/python/ray/worker.py
+++ b/python/ray/worker.py
@@ -2000,11 +2000,11 @@ def fetch_and_execute_function_to_run(key, worker=global_worker):
     driver_id, serialized_function = worker.redis_client.hmget(
         key, ["driver_id", "function"])

-    if (worker.mode in [SCRIPT_MODE, SILENT_MODE]
-            and driver_id != worker.task_driver_id.id()):
+    #if (worker.mode in [SCRIPT_MODE, SILENT_MODE]
+    #        and driver_id != worker.task_driver_id.id()):
         # This export was from a different driver and there's no need for this
         # driver to import it.
-        return
+    #    return

     try:
         # Deserialize the function.
```

**Comment by ericl** [comment]
Should the worker also ignore the serializer registered by another driver, since the serializer could change across drivers?

**Comment by robertnishihara** [comment]
Yeah, custom serializers registered by one driver should be ignored by other drivers.

**Comment by luweichao** [comment]
Since the worker may not know the corresponding driver id, how could it ignore the serializer registered by other drivers?

**Comment by ericl** [comment]
I believe the driver id for the current task can be accessed via `ray.worker.global_worker.task_driver_id.hex()`.
