### ISSUE TITLE
[serve][Feature] Option to serve multiple instances of a single class with different arguments

### ISSUE THREAD

**Issue by jerinka** [ray-project/ray#22938]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

An option for creating multiple objects (with different init arguments) of a single class and ray-serving these objects.

### Use case

For using ray serving of multiple objects of same class, in projects with multiple objects created using a for loop based on user inputs at runtime (cannot be determined prior runtime).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
@jerinka Can you please share an example of current behaviour and the desired behaviour? It would be helpful to discuss and iterate on an example. Thanks.

**Comment by simon-mo** [comment]
Hi @jerinka, 

You can accomplish this with the name flag, pattern is:
```python
for i in range(10):
    YourClass.options(name=str(i)).deploy(arg=i)
```
