### ISSUE TITLE
[core][Feature] Ability to set Headers for gRPC channels.

### ISSUE THREAD

**Issue by peterhaddad3121** [ray-project/ray#22945]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Currently gRPC supports setting custom headers prior to creating the channels. However, Ray.init() doesn't support custom headers as parameters. This can be limiting due to multiple reasons: proxy authentication, etc. 

Is there a workaround to set a custom header for the gRPC channel? We do it for client_id, and the underlying gRPC SDK support it: See [here.](https://github.com/ray-project/ray/blob/2302b4eea87c480699797e4bf770d46d0b758379/python/ray/util/client/worker.py#L98)

### Use case

Need the ability to pass custom headers through the gRPC channels. This option will solve a variety of different use cases.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by peterhaddad3121** [comment]
Hi @mwtian any traction on this issue by chance? Was wondering if contributing the Python portion would be an option?

**Comment by mwtian** [comment]
Hi @peterhaddad3121, contributions are definitely welcomed! I think this feature should not have much controversy. Eventually we probably want to expand the flag for gRPC headers to all gRPC usages in Ray. cc @scv119 @iycheng @ericl

**Comment by peterghaddad** [comment]
Hi @mwtian, I pushed the above patches to a PR. Hoping that you could be a reviewer. Thanks!
