### ISSUE TITLE
Creating actors slows after exceeding CPUs despite terminating actors

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#2295]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10/Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.4.0
- **Python version**: 3.6.3

### Describe the problem

When creating and killing actors, actor instantiation slows once the number of actors created exceeds the number of CPUs. The issue occurs despite killing actors using `__ray_terminate__`  such that there is only 1 active actor.

#### Code
```python
import ray
import time

@ray.remote
class Foo:
    def bar(self):
        return 1

def run_actor():
    f = Foo.remote()
    ray.get(f.bar.remote())
    f.__ray_terminate__.remote()

for _ in range(10):
    start = time.time()
    run_actor()
    end = time.time()
    print("{0:4f} ms".format(1000 * (end - start)))
    time.sleep(1)
```
#### Output
18.928528 ms
7.702589 ms
7.824421 ms
7.327080 ms
856.424809 ms
790.140390 ms
838.207245 ms
842.015743 ms
813.701391 ms
791.989088 ms

I'm running this on a machine with 4 CPUs. If I launch Ray with additional CPUs e.g. `ray.init(num_cpus=8)`, the first 8 calls to `run_actor()` are fast, and all following calls are slow even though actors are out of scope and should be terminated.

**Comment by robertnishihara** [comment]
Can you see if the issue happens when using the raylet? That is, start `ipython` with `RAY_USE_XRAY=1 ipython`. If it only occurs in the legacy code base then it probably isn't worth fixing, but it'd be good to understand if the issue is still present.

**Comment by pschafhalter** [comment]
I observed the same behavior when using raylet.

I'm taking a closer look at the local scheduler code to see if something there is causing the issue.

**Comment by pschafhalter** [comment]
I looked into the issue some more and found the source of the bug.

Ray starts the local scheduler with some initial number of available workers which usually matches the number of CPUs. Creating an actor uses a worker, but destroying the actor does not add a worker back to the available workers. So after the initial pool of workers is depleted, new actors ask the local scheduler to create a new worker which causes the overhead.

**Comment by richardliaw** [comment]
Nice find!
