### ISSUE TITLE
[Bug] SimpleQ Trainer does not allow `prioritized_replay` configuration parameter

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#22972]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

# What happened
When I use `prioritized_replay` in the configuration of the SimpleQ agent, I get an Error: 

```
[2022-03-09 20:51:47,943 E 178997 178997] core_worker.cc:1297: Pushed Error with JobID: 01000000 of type: task with message: ray::SimpleQTrainer.__init__() (pid=178997, ip=192.168.1.102, repr=SimpleQTrainer)
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 746, in __init__
    super().__init__(config, logger_creator, remote_checkpoint_dir,
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 124, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 759, in setup
    self.config = self.merge_trainer_configs(
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 2077, in merge_trainer_configs
    return deep_update(config1, config2, _allow_unknown_configs,
  File "/home/simon/git-projects/ray-experiments/.venv/lib/python3.9/site-packages/ray/util/ml_utils/dict.py", line 51, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `prioritized_replay` at time: 1.64686e+09
``` 
This should not happen after the fix in #21633. The reason is that the `DEFAULT_CONFIG` (and also the `Trainer` config) does not contain the `prioritized_replay` parameter and `_allow_unknown_configs` in the `Trainer` is set to `False` (and therefore also for `SimpleQTrainer` and all that inherit from this, e.g. `DQNTrainer`). 
 
# What did I expect to happen
I expected this parameter to be readable by the `SimpleQTrainer` (at best also by the `DQNTrainer` and others that could also use `"prioritized_replay": False`.  

### Versions / Dependencies

ray 1.11.0
Linux Fedora 35

### Reproduction script

```
import ray
from ray import tune
import ray.rllib.agents.dqn as dqn

MyConfig = dqn.SIMPLE_Q_DEFAULT_CONFIG.copy()
MyConfig['prioritized_replay'] = False

ray.init(local_mode=True)
tune.run(   
    dqn.SimpleQTrainer,
    config=MyConfig,
    stop={"training_iteration": 4},
    fail_fast=True,
    num_samples=1,
)
```

### Anything else

I would actualy suggest to put the `prioritized_replay` parameter into the `replay_buffer_config` as this makes somehow more sense to a user, imo. __BUT__ I see that `prioritized_replay` is used by many agents and that could bring up backward compatabilities. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
@ArturNiederfahrenhorst should be able to provide more insights here.

**Comment by ArturNiederfahrenhorst** [comment]
Has been resolved in another PR.
Usage of Replay Buffers has shifted to specifying a new Replay Buffer config in the new API.
For example as follows:

`config = Trainer.merge_trainer_configs(SIMPLE_Q_DEFAULT_CONFIG, {"replay_buffer_config":{"type":"MultiAgentPrioritizedReplayBuffer"})`

I tested this in the new API and everything worked fine. Thanks for reporting!
