### ISSUE TITLE
[Bug] [Autoscaler] [Azure] Can't create multiple clusters on Azure

### ISSUE THREAD

**Issue by HongW2019** [ray-project/ray#22996]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

Ray autoscaler on Azure couldn't create multiple clusters in the same resource group.

After successfully create a cluster on Azure and keep it running,  then edit the `cluster_name` in the yaml and run the same command to create a new cluster in the same resource group. It will update the existing cluster, instead of create the new cluster.
```
ray up ray/python/ray/autoscaler/azure/example-full.yaml
```

### Versions / Dependencies

Ray-1.11.0

### Reproduction script

```
ray up ray/python/ray/autoscaler/azure/example-full.yaml
# after the cluster is successfully created and running
# then edit the cluster_name of yaml to create a new cluster
vim ray/python/ray/autoscaler/azure/example-full.yaml
ray up ray/python/ray/autoscaler/azure/example-full.yaml
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wuisawesome** [comment]
@gramhagen @eisber @ijrsvt do y'all mind taking a look at this? There seems to be another user reporting the issue still. https://discuss.ray.io/t/what-makes-a-cluster-unique-in-the-resource-group/6710

typically cluster name should be a tag on instances to prevent this.

**Comment by wuisawesome** [comment]
It seems there's already good discussion about the issue and solution here. https://github.com/ray-project/ray/pull/22997
