### ISSUE TITLE
[Train] Start deprecating tune/integrations/* and direct people to use ray AIR 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#23014]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

NA

### Versions / Dependencies

NA

### Reproduction script

NA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
@matthewdeng

**Comment by amogkam** [comment]
Closed by https://github.com/ray-project/ray/pull/24453
