### ISSUE TITLE
[Bug] [Dask-on-Ray] Dask-on-Ray scheduler does not use correct shuffle settings.

### ISSUE THREAD

**Issue by mikwieczorek** [ray-project/ray#23013]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

When using Ray Cluster with at least 1 head and 1 worker, setting index on Dask Dataframe and trying to extract rows by index I gets error like this, where the Keys are in the original DataFrame

`KeyError: '[672879, 674822, 669739, 644624, 711958, 670045, 685757, 687412, 639885, 650025] not in index`

It is easily visible when we print the length of Pandas and Dask Dataframes indexes. For example Pandas returns `19816` number of unique index values, whereas Dask reports roughly half that number. When explicitly setting `shuffle='tasks'` in `set_index` method the problem does not occur.
 

### Versions / Dependencies

I tested this case in Ray==1.10.0 + Dask==2021.12.0 and Ray==1.11.0 + Dask=2022.1.0. Both for Client and Cluster side.

### Reproduction script

```python
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd
import ray
from ray.util.dask import ray_dask_get

### Helpers
def create_df(num_unique_ids, max_num_samples, min_id, max_id):
    repetition_array = np.random.randint(1, max_num_samples, num_unique_ids)
    ids_array = np.repeat(np.random.randint(min_id, max_id, num_unique_ids), repetition_array).flatten()
    df = pd.DataFrame(
        {
            'id':  ids_array,
            'value': np.random.randint(0, max_num_samples, ids_array.size),
        }
    )
    # print(random_index.shape, repetition_array.shape, random_index.shape)
    return df

### RAY
# ray.init()  ## Local Ray  <- works correctly
ray.init(address='ray://ray-cluster-ray-head.ray.svc.cluster.local:10001')

### DASK
dask.config.set(scheduler=ray_dask_get)

grouping_column = 'id'
allowed_column_ids = ['id', 'value']
batch_size = 256

# Code
df = create_df(num_unique_ids=20000, max_num_samples=10, min_id=1, max_id=1000000)
df['id'] = df['id'].astype(np.int64)
df['value'] = df['value'].astype(object)
print(f'Number of rows in Pandas DataFrame {df.shape[0]}')

ddf = dd.from_pandas(df, npartitions=8)
ddf = ddf.set_index(grouping_column) #  <- causes error KeyError
# ddf = ddf.set_index(grouping_column, shuffle='tasks') #  <- works correctly

index_ids = ddf.index.unique().compute()

print(f'Numbr of unique ids in Pandas DataFrame index {len(df.set_index(grouping_column).index.unique())}')
print(f'Numbr of unique ids in Dask DataFrame index {len(index_ids)}')

unique_ids = df['id'].unique()
item_indices = np.random.permutation(unique_ids)

for start_ix in range(0, len(item_indices), batch_size):
    end_ix = min(start_ix + batch_size, len(item_indices))
    indices = item_indices[start_ix:end_ix]
    batch = ddf.loc[indices].compute(scheduler=ray_dask_get)`
```
### Anything else

This problem does not occur when:
-  Using local ray (`ray.init()`)
-  Explicitly setting `shuffle="tasks"` in set_index method
-  Using Ray Cluster with a single node (head-node).

I reported similar problem (https://github.com/ray-project/ray/issues/20992) that was solved, but now it seems that new case was discovered where the Ray scheduler fails. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by clarkzinzow** [comment]
Hi @mikwieczorek, this is a known issue (https://github.com/ray-project/ray/issues/20108, https://github.com/ray-project/ray/issues/20992), and it actually appears that you opened a similar issue a few months ago. You can fix this manually by setting `shuffle="tasks"` when calling `.set_index()`, as you indicated, or by forcing task-based shuffle via a global config: `dask.config.set(shuffle="tasks")`.

We [added](https://github.com/ray-project/ray/pull/21114) an `enable_dask_on_ray()` config helper that does this automatically for you, along with setting the Dask-on-Ray scheduler as the default Dask scheduler. We'd definitely recommend using that, if possible.

Will using this config helper suffice? We were hoping to avoid automatically setting global Dask configs at import time when using the Dask-on-Ray scheduler since that seems like a bad practice.

**Comment by mikwieczorek** [comment]
@clarkzinzow Yes, I opened similar issue as stated in my post at the top.

That's not generally a problem to set it manually, but I would expect that when Ray connects to a cluster (not local Ray) `tasks` should be the default and the only correct option. However, I understand you do not want to force some specific bahaviour.

Sseems like `enable_dask_on_ray()` does what I need. Thank you for quick response.
