### ISSUE TITLE
[docs][serve] Improve Ray Serve FastAPI docs

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#23041]
## FastAPI docs

(1) In [FastAPI section](https://docs.ray.io/en/latest/serve/http-servehandle.html#fastapi-http-deployments), let's return JSON response, since most users doing this will want that. it's pretty easy with `from fastapi.responses import JSONResponse` and `return JSONResponse(content=content)`

(2) Let's also call out that you don't need to do request parsing in same way, and that there's magic you can take advantage of:

```python
# don't need: request.query_params["txt"]

# instead can use...

def root(self, txt: str):
       return f"Hello, world: {txt}"
```

**Comment by dynamicwebpaige** [comment]
Would it be possible to tag in @tiangolo as the primary owner? cc: @edoakes

**Comment by edoakes** [comment]
Sounds good to me! 🎉
