### ISSUE TITLE
[rllib][Bug] AttributeError: module 'gym.wrappers' has no attribute 'Monitor'

### ISSUE THREAD

**Issue by oliverwang15** [ray-project/ray#23062]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

 **Gym has just [Removd deprecated Monitor class and its dependencies](https://github.com/openai/gym/commit/e3b4857fe24a4181b56ba4e02956ba282afbdbd2) about 10 days ago.**
So one of the solution is to downgrade gym to 0.22.0, such as `pip install gym==0.22.0`

``` python
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_28167/805889802.py in <module>
      1 import ray
      2 #import ray.rllib.agents.ddpg.td3 as td3
----> 3 import ray.rllib.agents.ppo.ppo as ppo
      4 #import ray.rllib.agents.a3c as a3c
      5 #import ray.rllib.agents.ddpg.apex as apex

~/miniconda3/lib/python3.8/site-packages/ray/rllib/__init__.py in <module>
      7 from ray.rllib.env.multi_agent_env import MultiAgentEnv
      8 from ray.rllib.env.vector_env import VectorEnv
----> 9 from ray.rllib.evaluation.rollout_worker import RolloutWorker
     10 from ray.rllib.policy.policy import Policy
     11 from ray.rllib.policy.sample_batch import SampleBatch

~/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/__init__.py in <module>
      1 from ray.rllib.evaluation.episode import Episode, MultiAgentEpisode
----> 2 from ray.rllib.evaluation.rollout_worker import RolloutWorker
      3 from ray.rllib.evaluation.sample_batch_builder import (
      4     SampleBatchBuilder, MultiAgentSampleBatchBuilder)
      5 from ray.rllib.evaluation.sampler import SyncSampler, AsyncSampler

~/miniconda3/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py in <module>
     18 from ray.rllib.env.multi_agent_env import MultiAgentEnv
     19 from ray.rllib.env.external_multi_agent_env import ExternalMultiAgentEnv
---> 20 from ray.rllib.env.utils import record_env_wrapper
     21 from ray.rllib.env.vector_env import VectorEnv
     22 from ray.rllib.env.wrappers.atari_wrappers import wrap_deepmind, is_atari

~/miniconda3/lib/python3.8/site-packages/ray/rllib/env/utils.py in <module>
     55 
     56 
---> 57 class VideoMonitor(wrappers.Monitor):
     58     # Same as original method, but doesn't use the StatsRecorder as it will
     59     # try to add up multi-agent rewards dicts, which throws errors.

AttributeError: module 'gym.wrappers' has no attribute 'Monitor'
```

### Versions / Dependencies

ray 1.11.0
gym 0.23.0
Python 3.8.10
OS ubuntu 
Kernel x86_64 Linux 5.4.0-90-generic

### Reproduction script

``` python
import ray
import ray.rllib.agents.ppo.ppo as ppo
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ZaberKo** [comment]
I believe this is caused by an incompatibility of gym 0.23. Reinstalling gym 0.21 works for me.

**Comment by mansur007** [comment]
Are there any plans to extend support to gym>0.22.0 ?
Many other useful packages require newer versions of gym.
E.g. supersuit requires gym>=0.24.1

I and many others will be very grateful if support is extended.
Thank you

**Comment by avnishn** [comment]
so right now we are supporting gym 0.23 

I think we can try to make it a priority to support the newer gym versions soon, the trouble being that the gym api has changed, and adapting to it requires us to restructure our own internal env api.
