### ISSUE TITLE
[Bug] ActorPool map returns incorrect results if submit happens before without getting result

### ISSUE THREAD

**Issue by PookieBuns** [ray-project/ray#23107]
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

According to docstring for Actorpool's map method

This returns an ordered iterator that will return results of the map as they finish. Note that you must iterate over the iterator to force the computation to finish.

This means that if I map an identity function with values [1,2,3,4,5], it should return [1,2,3,4,5] as the result

However, if beforehand, I submit a function with value 6, and I do not use get_next or any sort of call to return this result, Now when I call map with [1,2,3,4,5], it will return [6,1,2,3,4,5] instead, because the map function uses get_next in a while loop to return the results

![image](https://user-images.githubusercontent.com/83051474/158021378-ec1a8082-80a3-4e60-b843-46bccb2823b4.png)

### Versions / Dependencies

ray 1.11.0 [default]

Python3.8.8

Windows10 x64

### Reproduction script

```python
import ray
from ray.util import ActorPool

@ray.remote
class DummyActor:
    async def identity(self, s):
        return s


if __name__=='__main__':
    pool = ActorPool([DummyActor.remote() for i in range(2)])
    def func(a, v): return a.identity.remote(v)
    pool.submit(func, 6)
    # pool.get_next() # if I run this, then map will return the correct results, or else it won't
    map_values = [1,2,3,4,5]
    gen = pool.map(func, map_values)
    print([v for v in gen]) # [6,1,2,3,4,5]
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
@pcmoritz Can I work on this? Please let me know.

**Comment by czgdp1807** [comment]
I am able to reproduce the issue with `master` branch of `ray`.

**Comment by czgdp1807** [comment]
**Cause of the problem**

The underlying cause of the problem faced by @PookieBuns is the definition of `ActorPool.map` (see below),

https://github.com/ray-project/ray/blob/f51cb09e02c2797fd857adb0e7fd44d4dd4222d5/python/ray/util/actor_pool.py#L39-L65

As you can see, first the method submits the tasks and then calls `gen_next` until all the outputs of all the submitted tasks (including the ones submitted before map was called) are received. It doesn't check whether there are tasks already submitted before submitting new tasks provided as input. This is causing the output to be `[6, 1, 2, 3, 4, 5]` and not `[1, 2, 3, 4, 5]`.

**My approach to fix it**

Since, clearing the previous tasks first inside `map` method and then submitting new ones would be a breaking change, I add a new optional parameter to `map` i.e., `ignore_previous_tasks` which is `False` by default (keeping the current behaviour intact). However if `ignore_previous_tasks` is set to `True` I call `gen_next(timeout=0)` repeatedly until all the previously submitted tasks are cancelled. The reason for setting `timeout=0` is simply to suppress all the previous tasks as the user has specifically asked (by setting `ignore_previous_tasks=True`) to ignore them.

```diff
diff --git a/python/ray/util/actor_pool.py b/python/ray/util/actor_pool.py
index 27b8b7ce8..1af40b3e1 100644
--- a/python/ray/util/actor_pool.py
+++ b/python/ray/util/actor_pool.py
@@ -36,7 +36,7 @@ class ActorPool:
         # next work depending when actors free
         self._pending_submits = []
 
-    def map(self, fn, values):
+    def map(self, fn, values, ignore_previous_tasks=False):
         """Apply the given function in parallel over the actors and values.
 
         This returns an ordered iterator that will return results of the map
@@ -59,6 +59,13 @@ class ActorPool:
             ...                     [1, 2, 3, 4])))
             [2, 4, 6, 8]
         """
+        if ignore_previous_tasks:
+            while self.has_next():
+                try:
+                    self.get_next(timeout=0)
+                except TimeoutError:
+                    pass
+
         for v in values:
             self.submit(fn, v)
         while self.has_next():

```

cc: @pcmoritz

**Comment by PookieBuns** [comment]
I believe running get_next in the while loop could actually cause problems because if the initial submit is a very long task or even worse, a long blocking task, the map will actually have to wait until that task is completed before it can start actually mapping tasks. I don't have a clear solution to this as the a ray actor currently doesn't support canceling tasks yet

**Comment by PookieBuns** [comment]
@czgdp1807 @pcmoritz

**Comment by PookieBuns** [comment]
I believe the proper way to ignore the task is by somehow fiddling with the next_task_index and next_return_index so it skips over it instead of waiting for it?

**Comment by czgdp1807** [comment]
> if the initial submit is a very long task or even worse, a long blocking task, the map will actually have to wait until that task is completed before it can start actually mapping tasks.

I call `get_next` with `timeout=0` before submitting new tasks in `map`. I also catch the `TimeoutError` and ignore it in the process. Effectively it should mean that we are just ignoring the previously submitted tasks. So, ideally length of previously submitted tasks shouldn't matter. Let me confirm this for surety.

**Comment by PookieBuns** [comment]
from what I understand, when get_next raises a timeout error it doesn't effectively skip over the current future to be returned because the next_return_index doesn't get changed

**Comment by czgdp1807** [comment]
**Code**

```python
import ray
from ray.util import ActorPool
import asyncio

@ray.remote
class DummyActor:
    async def identity(self, s):
        if s == 6:
            await asyncio.sleep(120)
        return s


if __name__=='__main__':
    def func(a, v):
        return a.identity.remote(v)
    pool = ActorPool([DummyActor.remote() for i in range(2)])
    pool.submit(func, 6)
    # pool.get_next() # if I run this, then map will return the correct results, or else it won't
    map_values = [1,2,3,4,5]
    gen = pool.map(func, map_values)
    print([v for v in gen]) # [6,1,2,3,4,5]
```

**Approach**

```diff
diff --git a/python/ray/util/actor_pool.py b/python/ray/util/actor_pool.py
index ff7ad3baf..bead0b0b5 100644
--- a/python/ray/util/actor_pool.py
+++ b/python/ray/util/actor_pool.py
@@ -63,7 +63,7 @@ class ActorPool:
         # by calling `has_next` and `gen_next` repeteadly.
         while self.has_next():
             try:
-                self.get_next(timeout=0)
+                self.get_next(timeout=0, ignore_if_timedout=True)
             except TimeoutError:
                 pass
 
@@ -156,7 +156,7 @@ class ActorPool:
         """
         return bool(self._future_to_actor)
 
-    def get_next(self, timeout=None):
+    def get_next(self, timeout=None, ignore_if_timedout=False):
         """Returns the next pending result in order.
 
         This returns the next result produced by submit(), blocking for up to
@@ -181,10 +181,15 @@ class ActorPool:
                 "It is not allowed to call get_next() after " "get_next_unordered()."
             )
         future = self._index_to_future[self._next_return_index]
+        timeout_msg = "Timed out waiting for result"
+        raise_timeout_after_ignore = False
         if timeout is not None:
             res, _ = ray.wait([future], timeout=timeout)
             if not res:
-                raise TimeoutError("Timed out waiting for result")
+                if not ignore_if_timedout:
+                    raise TimeoutError(timeout_msg)
+                else:
+                    raise_timeout_after_ignore = True
         del self._index_to_future[self._next_return_index]
         self._next_return_index += 1
 
@@ -192,6 +197,8 @@ class ActorPool:
         i, a = self._future_to_actor.pop(future_key)
 
         self._return_actor(a)
+        if raise_timeout_after_ignore:
+            raise TimeoutError(timeout_msg + ". The task {} has been ignored.".format(future))
         return ray.get(future)
 
     def get_next_unordered(self, timeout=None):

```

I don't know if we should include the extra parameter, `ignore_if_timedout` in `get_next` because IMHO, if a task has been timed out then it should be ignored anyway and we should move forward with other tasks. Ideally, the previous tasks should be cancelled (IMO, its not a good idea for tasks to keep consuming resources if effectively their outputs are not of any use) but that isn't supported yet with actors. 

cc: @pcmoritz
