### ISSUE TITLE
[RLlib][Bug] OpenAI Gym with RLlib PPO computed action is not in action_space

### ISSUE THREAD

**Issue by davidschnermann** [ray-project/ray#23142]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

I wonder why the action calculated by the PPO agent from RLlib doesn't fit in the action space I defined in my Env. If I choose DDPG it fits. Sorry if I'm wrong and it isn't a bug, but I don't know how to solve the problem. So I would like to ask if it has something to do with the implementation or if it is something fundamental that I am not aware of. Maybe it's because PPO is an on-policy algorithm, or I don't know... please tell me. I would really like to understand it because I thought that every algorithm does everything only inside the action space.

### Versions / Dependencies

  gym 0.21.0
    numpy 1.22.0
    ray 1.10.0
    Python 3.8.12
    Ubuntu 20.04

### Reproduction script

```
import gym
import numpy as np

import ray
import ray.rllib.agents.ppo as ppo
import ray.rllib.agents.ddpg as ddpg

class TestEnv(gym.Env):
    def __init__(self, env_config = None):
        self.action_space = gym.spaces.box.Box(
            low=np.array([-1,-1], dtype=np.float32),
            high=np.array([1,1], dtype=np.float32))
        self.observation_space = gym.spaces.Discrete(3)

    def reset(self):
        self.done = False
        self.reward = 0
        ob =  self.observation_space.sample()
        return ob

    def step(self, action):
        assert self.action_space.contains(action)
        ob =  self.observation_space.sample()
        return ob, self.reward, self.done, dict()

def main ():
    env = TestEnv()
    ray.init(ignore_reinit_error=True)

    config = ppo.DEFAULT_CONFIG.copy()
    # config = ddpg.DEFAULT_CONFIG.copy()
    agent = ppo.PPOTrainer(config, TestEnv)
    # agent = ddpg.DDPGTrainer(config, TestEnv)
    
    state = env.reset()
    action = agent.compute_action(state)
    print('action: ', action)
    assert env.action_space.contains(action)        
    # state, reward, done, results = env.step(action)
    ray.shutdown()
    print("done.")

if __name__ == "__main__":
    main()

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richleigh** [comment]
Sounds similar to an issue I spotted a few days back https://github.com/ray-project/ray/issues/23074

**Comment by gjoliver** [comment]
thanks for the report, this is a dup of #23074
