### ISSUE TITLE
[Bug] autoscaler.sdk.request_resources input is not validated

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#23166]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

The arguments to ray.autoscaler.sdk are not validated.
I just did `ray.autoscaler.sdk(bundles={"GPU": 1})` forgetting to wrap the GPU bundle in brackets.
The request went through and I saw some garbage in the autoscaler logs.

I would expect the to have the system notice that `{"GPU": 1}` is not a `List[Dict[str, int]]` and raise a type error.

### Versions / Dependencies

Master

### Reproduction script

See above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hannahcoles** [comment]
Hi! Can I claim this issue please?

**Comment by DmitriGekhtman** [comment]
> Hi! Can I claim this issue please?

@hannahcoles 
Yes, please! Feel free to add me as a reviewer.

**Comment by truelegion47** [comment]
@DmitriGekhtman Added a draft, can you please help take a look when you get a chance ?
