### ISSUE TITLE
[Bug] ray.util.joblib does not spread tasks among PoolActors

### ISSUE THREAD

**Issue by xwu99** [ray-project/ray#23184]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

When using the following reproducer, joblib ray backend can not always spread the worker_func into 4 actor processes.

```python
from joblib import parallel_backend, Parallel, delayed
import ray
from ray.util.joblib import register_ray
import time

ray.init()
register_ray()

num_workers = 4


def worker_func(worker_id):
    print(f"starting {worker_id} and wait for 30 secs")
    time.sleep(30)


with parallel_backend("ray", n_jobs=num_workers):
    Parallel()(delayed(worker_func)(worker_id)
               for worker_id in range(num_workers))

```
Expected: All 4 tasks are spreaded to 4 actors.
```bash
2022-03-15 21:17:20,372	INFO services.py:1412 -- View the Ray dashboard at http://127.0.0.1:8265
2022-03-15 21:17:22,011	WARNING pool.py:494 -- The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
(PoolActor pid=29458) starting 3 and wait for 30 secs
(PoolActor pid=29454) starting 2 and wait for 30 secs
(PoolActor pid=29452) starting 0 and wait for 30 secs
(PoolActor pid=29448) starting 1 and wait for 30 secs
```
Actual: Only two actors are active and the last 2 tasks only proceed unitl the previous 2 ones finished:
```bash
2022-03-15 21:17:35,266	INFO services.py:1412 -- View the Ray dashboard at http://127.0.0.1:8265
2022-03-15 21:17:36,903	WARNING pool.py:494 -- The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
(PoolActor pid=29842) starting 0 and wait for 30 secs
(PoolActor pid=29840) starting 3 and wait for 30 secs
```

### Versions / Dependencies

ray, version 1.11.0

### Reproduction script

see above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
@pcmoritz Is this something that I can try fixing? Please let me know.

**Comment by pcmoritz** [comment]
Yes, that would be worth looking into :)

**Comment by czgdp1807** [comment]
I think I can reproduce. See the timestamps, some processes start when others are complete. Not all 4 are launched at the same time.

```
2022-03-17 09:41:04,445 INFO services.py:1464 -- View the Ray dashboard at http://127.0.0.1:8265
2022-03-17 09:41:15,916 WARNING pool.py:500 -- The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
(PoolActor pid=9540) starting 3 and wait for 30 secs 1647510081.4779196
(PoolActor pid=11456) starting 0 and wait for 30 secs 1647510081.4779196
(PoolActor pid=9540) starting 3 and wait for 30 secs complete 1647510111.494544
(PoolActor pid=11456) starting 0 and wait for 30 secs complete 1647510111.494544
(PoolActor pid=11456) starting 1 and wait for 30 secs 1647510111.494544
(PoolActor pid=11456) starting 1 and wait for 30 secs complete 1647510141.4959831
(PoolActor pid=11456) starting 2 and wait for 30 secs 1647510141.4959831
(PoolActor pid=11456) starting 2 and wait for 30 secs complete 1647510171.5126908
```

**Comment by czgdp1807** [comment]
The reason behind not all tasks being launched at the same time is random index generator i.e., the following method,

https://github.com/ray-project/ray/blob/f21092e80a962b4479ad4fc7c267c37088acc593/python/ray/util/multiprocessing/pool.py#L574-L575

Basically, joblib calls `apply_async` method which redirects to `Pool.apply_async` method of `ray` i.e., the following code is executed,

https://github.com/ray-project/ray/blob/f21092e80a962b4479ad4fc7c267c37088acc593/python/ray/util/multiprocessing/pool.py#L629-L632

The call to `self._random_actor_index` sometimes produces same index twice. For example, it generates `3`, then `3`, then `5` and then `7`. This would mean that two tasks will be mapped to same actor (which will execute them sequentially) and hence effectively first three tasks will be launched and the the final remaining task will be launched on actor 3. Overall, maximum concurrency will be lowered to 3 instead of 4. See a debug print output below,

```python
ray.init.start
2022-03-22 07:16:47,932 INFO services.py:1464 -- View the Ray dashboard at http://127.0.0.1:8265
ray.init.end
2022-03-22 07:16:56,742 WARNING pool.py:500 -- The 'context' argument is not supported using ray. Please refer to the documentation for how to control ray initialization.
self._random_actor_index():  3
self._random_actor_index():  3
self._random_actor_index():  5
self._random_actor_index():  7
(PoolActor pid=1800) starting 3 at 1647933425.4018404
(PoolActor pid=7012) starting 2 at 1647933425.4018404
(PoolActor pid=10020) starting 0 at 1647933425.4018404
(PoolActor pid=1800) ending 3 at 1647933435.4151847, gap: 10.013344287872314
(PoolActor pid=7012) ending 2 at 1647933435.4151847, gap: 10.013344287872314
(PoolActor pid=10020) ending 0 at 1647933435.4151847, gap: 10.013344287872314
(PoolActor pid=10020) starting 1 at 1647933435.4151847
(PoolActor pid=10020) ending 1 at 1647933445.4311497, gap: 10.015964984893799
[0, 1, 2, 3]
```

Will update this comment with some potential fixes.

**Comment by pcmoritz** [comment]
Let's do the second fix
