### ISSUE TITLE
[Docs] Improve the navigation of Ray Tune examples

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#23193]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

For examples we don't want to include in the side bar, we should still highlight their parent page in the side bar and add "Back to examples" button for easier navigation.
<img width="369" alt="Screen Shot 2022-03-15 at 10 46 31 AM" src="https://user-images.githubusercontent.com/9677264/158441178-21febe03-bc0c-49ea-9c97-ad0a6dc5fb21.png">

@max

### Versions / Dependencies

Ray 1.10

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maxpumperla** [comment]
fixed on master
