### ISSUE TITLE
[Docs] Improve the navigation experience

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#23194]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

Issue 1: The "collapse" button in the top left corner is confusing to me. I always thought it was "back" button.
<img width="985" alt="Screen Shot 2022-03-15 at 10 47 16 AM" src="https://user-images.githubusercontent.com/9677264/158450815-8269e8b5-7409-4faa-92b3-ca6685bbb8cf.png">

Suggestions:
Ideally, we should improve the navigation experience for different screen sizes.
1. for laptop/desktop/relatively big screens, we could remove this button.
2. for phones/small screen devices, we should optimize the navigation experience and probably keep the hamburger menu and this "collapse" button. (also, the current hamburger menu/side nav is broken on my phone).

Issue 2: the side nav seems unnecessarily wide compared to other doc sites. Should we restrict the width (wrap the item in the side bar when needed) and leave more space for the main page/contents?

@max

### Versions / Dependencies

ray 1.10

### Reproduction script

n/a

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by maxpumperla** [comment]
@scottsun94 fixed in https://github.com/ray-project/ray/pull/23417
