### ISSUE TITLE
[Datasets] Mental model confusion + Doc improvement (identified from user test)

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#23212]
### Context
We did 5 tests with users on loading data with Ray dataset & train an xgboost model.
All 5 participants are familiar with xgboost and have work experience in the machine learning industry.
### Test Data
- **4 of 5 failed the load dataset step** with ~15-30 mins attempt, 1 completed the step with assistance.
- On average, 5 of 5 find the step is **more difficult than they thought**. 
Expectation rating = 2, Experience rating = 6.5 (1 = very easy, 7 = very difficult)

FYI. [Session notes with error logs
](https://airtable.com/shrH87SOHwd3g54AZ)
### Cross-pattern Findings 
**Severity definition**
Low: It annoys or frustrates me for a moment.
Medium: It contributes to significant difficulty to complete my task but I work around and get it resolved.
High: It blocks me to complete my task.

Observation | Why it’s happening | Suggestion | Severity
-- | -- | -- | --
4/5 didn't realize they **need to repartition data** with the Ray dataset. (caused task failure) | There are concept-level differences of the match between load data using Ray datasete vs. other typical packages e.g. panda.(participants are familiar with) | Ideally API design should match to mental model people already have. But if there have to be concept-level differences, let the user be aware of the difference before they start their task e.g. "Things you should know before start”. | High 
5/5 sought for **end-end examples** in Ray documentation: "How to load parquet data[format used in the test]?" "How to sample data?”, “How to create a data frame for Ray dataset?” without satisfying results, they tried search function in Ray documentation, then Google search, but didn't find what they were looking for. | People tend to “learn within a context” when they are trying to complete their own task. | End-end examples speak to the user. In our case, ideally have a comparison of both Ray example and Panda(typical package people use to load data) example. | Medium
Participants find this is helpful but not enough. ![Screen Shot 2022-03-09 at 11_44_44](https://user-images.githubusercontent.com/97252176/158489509-6537ee45-c6e6-451a-8343-bef4e107f3ad.png) | Again, people tend to “learn within a context” | “Load x format of data is helpful, would be great to show how to use the actual API in a short example, and compare with load x format data using other packages.” - Participant x | Low

**Comment by Wendi-anyscale** [comment]
@clarkzinzow 
@maxpumperla

**Comment by maxpumperla** [comment]
@Wendi-anyscale this is fantastic, please keep it up :v:

**Comment by jianoaix** [comment]
This is nice feedbacks. And +1 to the finding in the first row!

I'm not sure I understand the second row though: "How to load parquet data format" is not an end-to-end task and it can be well answered with something like How to Load Data or How to Create Dataset (which we had revamped recently and hopefully should be much easier to figure out).

**Comment by pcmoritz** [comment]
@clarkzinzow @jianoaix 
Have we addressed the first row and the other feedback yet?
