### ISSUE TITLE
[core][Object Spilling] Spilled objects not deleted for Smart Open

### ISSUE THREAD

**Issue by kennethlien** [ray-project/ray#23214]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

1. Spilled objects to directories opened with `smart_open` are not deleted due to a lack of implementation.
2. Spilled objects to directories opened with `smart_open` should be deleted to prevent bloat and clutter.
3. https://github.com/ray-project/ray/blob/master/python/ray/external_storage.py#L496 has no definition.

### Versions / Dependencies

N/A

### Reproduction script

Running Ray with a `smart_open` config and causing it to spill objects will show that objects are not cleaned up afterwards.

```
{
    "object_spilling_config":  {
        "type": "smart_open",
        "params": {
            "uri": "s3://path"
        },
    }
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
This is resolved with the new pyarrow backend for object spilling: https://github.com/ray-project/ray/pull/22889

I'm not sure this is easy to do with smart_open, since it doesn't implement full filesystem semantics.
