### ISSUE TITLE
[core][Bug] long_running_many_drivers nightly test is failing

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#23238]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

It looks like the actual test is passing, or at least it seems to finish successfully in the cluster console.

I think maybe the error is related to the test infrastructure. I saw [this output](https://buildkite.com/ray-project/release-tests-branch/builds/175#d72b0b29-165a-48fe-a492-b204926ac688) in buildkite:
```
[INFO 2022-03-16 07:49:13,404] job_manager.py: 42  Executing pip install -q awscli && aws s3 cp /tmp/release_test_out.json s3://ray-release-automation-results/tmp/kxfgzkmzdt --acl bucket-owner-full-control with {} via ray job submit

[ERROR 2022-03-16 07:49:13,440] glue.py: 237  Could not fetch results for test command

[ERROR 2022-03-16 07:49:13,440] glue.py: 238  Could not fetch results from session: Request failed with status code 502: 

<html>

    <head>

        <title> Retrying </title>

        <meta http-equiv="refresh" content="5">

        <style>

        body {

            font-family: noto sans,sans-serif;

            padding: 25px;

        }

        </style>

    </head>

    <body>

      <h1>

        Loading...

      </h1>



      <h2> âŒ› </h2>

      <p> Service currently unavailable. </p>

      <p> This page will automatically refresh. </p>



    </body>

</html>

        .

Traceback (most recent call last):

  File "/tmp/release-tukOz7M6Fu/release/ray_release/command_runner/sdk_runner.py", line 164, in fetch_results

    self.file_manager.download(self.result_output_json, tmpfile)

  File "/tmp/release-tukOz7M6Fu/release/ray_release/file_manager/job_file_manager.py", line 57, in download

    {},

  File "/tmp/release-tukOz7M6Fu/release/ray_release/job_manager.py", line 100, in run_and_wait

    cid = self._run_job(cmd_to_run, env_vars)

  File "/tmp/release-tukOz7M6Fu/release/ray_release/job_manager.py", line 48, in _run_job

    entrypoint=full_cmd,

  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/job/sdk.py", line 90, in submit_job

    self._raise_error(r)

  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 218, in _raise_error

    f"Request failed with status code {r.status_code}: {r.text}."

RuntimeError: Request failed with status code 502: 

<html>

    <head>

        <title> Retrying </title>

        <meta http-equiv="refresh" content="5">

        <style>

        body {

            font-family: noto sans,sans-serif;

            padding: 25px;

        }

        </style>

    </head>

    <body>

      <h1>

        Loading...

      </h1>



      <h2> âŒ› </h2>

      <p> Service currently unavailable. </p>

      <p> This page will automatically refresh. </p>



    </body>

</html>

        .



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/tmp/release-tukOz7M6Fu/release/ray_release/glue.py", line 235, in run_release_test

    command_results = command_runner.fetch_results()

  File "/tmp/release-tukOz7M6Fu/release/ray_release/command_runner/sdk_runner.py", line 172, in fetch_results

    raise ResultsError(f"Could not fetch results from session: {e}") from e

ray_release.exception.ResultsError: Could not fetch results from session: Request failed with status code 502: 

<html>

    <head>

        <title> Retrying </title>

        <meta http-equiv="refresh" content="5">

        <style>

        body {

            font-family: noto sans,sans-serif;

            padding: 25px;

        }

        </style>

    </head>

    <body>

      <h1>

        Loading...

      </h1>



      <h2> âŒ› </h2>

      <p> Service currently unavailable. </p>

      <p> This page will automatically refresh. </p>



    </body>

</html>
```

### Versions / Dependencies

2.0dev

### Reproduction script

long_running_many_drivers

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by alanwguo** [comment]
Has this test ever worked? The 502 happens when the dashboard API server crashes. The dashboard API server is needed to submit the job which uploads the test results to S3.

One way we've seen the dashboard API server die is when the head_node is under heavy load the the API server crashes. 

option 1: Alter the test to have the head node set "cpu: 0" to avoid having any load on the head node.
option 2: reduce the scale of the test and the scalability envelope of ray.

Can we try cutting the number of iterations down for the next run?

**Comment by alanwguo** [comment]
It would also be helpful to be able to manually run this test and try to repro with less iterations. @krfricke, @rkooo567  is there documentation on how I can do this?

**Comment by stephanie-wang** [comment]
@alanwguo I think you can use this command:
```bash
cd release/ray_release
python scripts/run_release_test.py long_running_many_drivers --ray-wheels master --no-terminate
```

Test script is in release/long_running_tests/workloads/many_drivers.py

**Comment by stephanie-wang** [comment]
Also, this particular test doesn't have any worker nodes and it's supposed to test long-running behavior, so I'm not sure if there's a way we can meaningfully modify the test, unfortunately. I do remember this passing before, so I think this is a new error.

**Comment by krfricke** [comment]
Maybe we can just bump the instance size for this particular test. I think it's most likely that the head node is under too much load.

**Comment by krfricke** [comment]
Alternatively, we can switch back to SessionController-based syncing (which doesn't use jobs) - the test passed last time we used that (in the old infra): https://buildkite.com/ray-project/periodic-ci/builds/3041#a73020d9-440b-4d2c-a35f-0798a67d34e2
This is also the only difference.
I'll kick both options off

**Comment by alanwguo** [comment]
I think moving back to session controller-based syncing is the fastest way to unblock Stephanie.

In the medium term, @yifeif, @AmeerHajAli  , I think this is a good issue to spend time on for fixing stability issues. I'm happy to help out but I think infra folks should also be involved. For example, maybe we should health check all dataplane services and log the results in the control plane. Then we can see at what point do services start crashing.

**Comment by stephanie-wang** [comment]
Yes, my vote is to keep the test as is. Head node load is a valid application scenario and I think we should keep it in our test coverage. Thanks for looking into this!

**Comment by krfricke** [comment]
Ok, @stephanie-wang here is the PR that successfully fixed the run: https://github.com/ray-project/ray/pull/23379

fwiw, increasing the instance size did not fix the test anyway.

**Comment by stephanie-wang** [comment]
Closed by #23379.

**Comment by scv119** [comment]
Looks the job submission is not able to handle the load comes with this long_running_many_driver tests. A separate question is if job submission is designed to handle this many concurrent jobs (i.e. 4000). cc @edoakes  on this.

If job is not designed to handle the load (and I assume it doesn't), we probably need to keep this test with sdk instead of jobs even after we migrated to k8s clusters. cc @alanwguo

**Comment by edoakes** [comment]
@scv119 what is the workload here? We're trying to run 4000 concurrent ray jobs? If so, ray job submission definitely isn't designed/tested for that case (as a side note, it seems like kind of a strange workload to test).
