### ISSUE TITLE
[Feature] Remove route prefix for all deployment and deployment method nodes in a serve dag

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#23239]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

.

### Use case

.

### Related issues

.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by edoakes** [comment]
Specifics:

- Default "ingress" deployment to `/`
- All other deployments have `None`
- Error if any of the other deployments have non-default (maybe at `.bind()` step?)
