### ISSUE TITLE
[Bug] Ray 1.11.0 still rely on Redis python pkg

### ISSUE THREAD

**Issue by jie8357IOII** [ray-project/ray#23269]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

I expected Ray 1.11.0 could run without Redis lib and Redis python pkg.
So I install Ray 1.11.0 and uninstall Redis python pkg but faced the following error.

```
Traceback (most recent call last):
  File "/Users/jayce.li/miniconda3/envs/ray_test/bin/ray", line 5, in <module>
    from ray.scripts.scripts import main
  File "/Users/jayce.li/miniconda3/envs/ray_test/lib/python3.7/site-packages/ray/__init__.py", line 91, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 127, in init ray._raylet
  File "/Users/jayce.li/miniconda3/envs/ray_test/lib/python3.7/site-packages/ray/util/__init__.py", line 4, in <module>
    from ray._private.services import get_node_ip_address
  File "/Users/jayce.li/miniconda3/envs/ray_test/lib/python3.7/site-packages/ray/_private/services.py", line 26, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
```

### Versions / Dependencies

Ray 1.11.0
Python 3.7

### Reproduction script

```shell
conda create -n ray_test -y python=3.7 
conda activate ray_test      
pip install ray==1.11.0 
pip uninstall -y redis
ray start --head
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by mwtian** [comment]
Hi @jie8357IOII, in Ray 1.11.0, we only made Redis-less Ray the default, but Redis-Ray is still available with `RAY_bootstrap_with_gcs=0 RAY_gcs_storage=memory ray start --head`, so the `redis` dependency is needed. We plan to completely remove the Python `redis` dependency in the next 1 or 2 release. Please let us know if there are other issues!

**Comment by jie8357IOII** [comment]
Thank you! @mwtian! I am looking forward to Ray 1.12
Can't wait to get rid of Redis, issue close
