### ISSUE TITLE
Better support for importing from separate file on cluster

### ISSUE THREAD

**Issue by alexbao** [ray-project/ray#2327]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.4.0
- **Python version**: 2.7.10
- **Exact command to reproduce**: see the example code as below

### Describe the problem
High possibility to fail if run the driver test2.py by connecting to a remote ray cluster
`$ python test2.py  --redis_address=xxxx`

Error:

> Exception: The actor with name Bar failed to be imported, and so cannot execute this method

### Source code / logs

============ file test2.py===============
```
import ray
import actors2
import argparse

parser = argparse.ArgumentParser(description="Online learning service")

parser.add_argument("--redis_address", default=None, type=str,
                    help="Redis service address")


args = parser.parse_args()
if args.redis_address:
    print "redis_address:", args.redis_address
    ray.init(redis_address=args.redis_address)
else:
    ray.init()

Bar2 = ray.remote(actors2.Bar)

b = Bar2.remote()

print ray.get(b.get_x.remote())
```

============ file actors2.py===============
```
class Foo(object):
    def __init__(self):
        self.x = 1

class Bar(Foo):
    def __init__(self):
        super(Bar, self).__init__()

    def get_x(self):
        return self.x
```

**Comment by alexbao** [comment]
@raulchen

**Comment by richardliaw** [comment]
Thanks for posting this issue; I've definitely ran into this problem multiple times.

One possible solution (as discussed with @robertnishihara) would be to provide a utility function like `ray.broadcast_module(actors2)` that allows users to explicitly spread this module across different nodes.

Another solution would be to implicitly take care of this/under the hood, but there may be many uncovered edge cases/bugs.

**Comment by raulchen** [comment]
The quickest workaround is to just copy `actor2.py` to worker nodes.

`ray.broadcast_module` sounds like a good idea, especially when people only want to run quick scripts, they don't need to manually copy files.

But for large-scale projects, I think the best way is still copying code or deploying code via a wheel. Otherwise, we'll end up with doing a ton of `broadcast_module`s.

Regarding taking care of everything under the hood automatically, I doubt if it's even feasible. Because Python is too dynamic to detect all dependencies beforehand. (An alternative way is to go back to driver when something is missing, but that may introduce considerable overhead, and make the system too complex.)

**Comment by robertnishihara** [comment]
I implemented something like `ray.broadcast_module` a while ago in https://github.com/ray-project/ray/pull/150, but later removed it. I suppose it's still a useful thing to have around..

It provided

```python
ray.experimental.copy_directory(source_dir, target_dir)
```

to recursively copy a directory from the local machine throughout the cluster.

**Comment by richardliaw** [comment]
It would be nice to be placed into a tmp dir by default and extending the sys.path for each Ray worker with that directory.

I was hoping not to worry about it where to place it (and even maybe by keeping it in memory somehow, though that seems painful for workers dying and starting anew).

**Comment by raulchen** [comment]
One thing to notice is that we should also clean up PYTHONPATH after driver exits. Currently, 2 items are inserted to `sys.path` and never cleaned up, see https://github.com/ray-project/ray/blob/d8ba667175290e182dee0e309c4a65445249b80d/python/ray/worker.py#L2265-L2268.
It may cause naming conflicts when worker running code from multiple drivers.

**Comment by alexbao** [comment]
Discussed with @atumanov yesterday, and it turns out to be more interesting than I had thought. The specific use case we discussed is to deploy new code and rolling update the driver:

- Driver runs tasks remotely on ray cluster
- Driver is deployed as microservice
- When new version of code is available, the code has to be deployed to ray cluster, as well as creating new containers
- Ray cluster and micro service need to be updated atomicly, otherwise the code run in/between the nodes and microservices will be inconsistent
- NFS file sync might help to minimize gap of deploying time (aka down time of the service), but might not help for rolling update
- The major difference for deploying the services on ray v.s traditional distributed service is that, the communication between nodes for former uses remote function call, while the later uses rpc call

**Comment by richardliaw** [comment]
@robertnishihara @atumanov 	is it possible to provide something that alleviates this pain point in 0.6?

**Comment by ericl** [comment]
Auto-closing stale issue.

**Comment by Vysybyl** [comment]
Sorry to comment on a closed issue but I couldn't file any real solution. Spark for instance lets you add .py or .whl files to your context. Could you provide a working example? Thanks

**Comment by JoshBroomberg** [comment]
I agree with @Vysybyl I can't find a reasonable way to move code from a local "package" into an existing cluster. I want to do local development of some python code and then (re)run on an existing ray cluster as I make changes. Is there no good way to do this now?

**Comment by JoshBroomberg** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
hmm are you on the cluster launcher?

**Comment by JoshBroomberg** [comment]
@richardliaw no - we stand up a bespoke cluster using the command line and this cluster is "long lived" relative to the work session. I.E, we want to be able to change code and have this new code accessible on workers. The local code is configured as a python package and so is one "module"
