### ISSUE TITLE
[ml] `Tuner.fit` does not return ML Checkpoint

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#23295]
Running `tuner.fit()[0].checkpoint` returns a `ray.tune.Checkpoint` object, not a `ray.ml.Checkpoint` object.

**Comment by xwjiang2010** [comment]
cc @krfricke 
Problem description:
1. `ExperimentAnalysis` has this notions of `metric` and `mode` and what is "best" baked in.
2.  On the other hand, train using tune does not need these concepts. It does not need to get the best trial, it only needs to get "the" trial.

Proposal #1, `ExperimentAnalysis` is still what it is. But train will only call `result_grid[0].checkpoint` to get what it needs (which doesn't go through ExperimentAnalysis). This requires that `trial.checkpoint` is also returning the "new" checkpoint. We can use a similar boolean `_legacy_checkpoint` like you did for EA.
Proposal #2, extend `ExperimentAnalysis` to handle one trial case with no `metric` or `mode` specified.

I prefer #1. Let me know what you think. 

For now, to unblock the rest PRs, I put up https://github.com/ray-project/ray/pull/23280.
