### ISSUE TITLE
[release tests] runtime_env tests failing/flaky

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23291]
`runtime_env_rte_many_tasks_actors` latest run:
https://buildkite.com/ray-project/release-tests-branch/builds/181#79668090-b3c7-4eda-a689-b64a2dac51fe	

`runtime_env_rte_ray_client` latest run:
https://buildkite.com/ray-project/release-tests-branch/builds/181#cbf096a0-e278-4b01-88ae-859d3f93772a

**Comment by architkulkarni** [comment]
The failure is from dependency conflicts caused by the test installing old pinned versions of the `requests` library.  Should be a straightforward fix by using a different package with no dependency relations, like `pip-install-test==0.5` and `pip-install-test==0.4`.
