### ISSUE TITLE
[air] dogfooding: rendering issues

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#23304]
- [ ] [ml][Improvement] Progress bar doesn’t render properly in remote actors.
- [x] [ml][Improvement] Train_function_bla → we should change it to a good name

cc @xwjiang2010 @amogkam

**Comment by amogkam** [comment]
Closing as the first point is duplicate of https://github.com/ray-project/ray/issues/9233 (priority of #9233 has been upgraded to P2) and the second point is resolved by https://github.com/ray-project/ray/pull/23697.
