### ISSUE TITLE
[AIR] Dogfooding Issues from Matt/Eric

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#23307]
- [x] We need some way to load these keras dataset out of the box and other stuff (https://github.com/ray-project/ray/issues/23977)
- [x] #23439
- [x] #23870
- [ ] would be nice to be able to rename dataset columns (got "value", "value_1") zipping two numpy datasets or at least be able to set the column name when calling from_numpy()
- [ ] no way to visualize images easily in dataset e.g., save_as_images_files()
- [x] add a simple "map" preprocessor (ColumnAdd, ColumnModify)?
- [ ] * Why did it convert from arrowtensortypes to tensordtype? \

    ```
Dataset(num_blocks=1, num_rows=60000, schema={value: <ArrowTensorType: shape=(28, 28), dtype=uint8>, value_1: <ArrowTensorType: shape=(28, 28), dtype=uint8>})
[dataset]: Run `pip install tqdm` to enable progress reporting.
Dataset(num_blocks=1, num_rows=60000, schema={value: TensorDtype, value_1: TensorDtype})

Dataset(num_blocks=1, num_rows=60000, schema={value: <TensorType: shape... storage=arrow>, value_1: TensorDtype})


- [x] RESOLVED BY #23695 
* Not immediately obvious what to specify for tensorflowtrainer
* ScalingConfig is optional but there is no default value
* ValueError: You must specify the 'num_workers' in scaling_config.
* Better error messages for incorrect argument types (all interfaces)
- [ ] * feature_column should be mandatory / we should type check these argos
  * seems like bug in to_tf()
  * return batch["value"].values, batch["value_1"].values works
- [ ] * Need to specify batch size
- [ ] * Label column is merged with train dataset


cc @matthewdeng , @ericl

**Comment by clarkzinzow** [comment]
> would be nice to be able to rename dataset columns (got "value", "value_1") zipping two numpy datasets or at least be able to set the column name when calling from_numpy()

The column name should be an implementation detail of our tensor support, so we should try to handle this transparently to the user.
