### ISSUE TITLE
[rllib] save/load replay buffer

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2330]
Hi,

I wonder, is it possible to add save/load replay buffer for off-policy methods?
By this way, it is easy to speed up learning process for off-policy method cause we can easily reuse previous sampled trajectories.

Thanks!

**Comment by richardliaw** [comment]
Yeah - to do this, we just need to overwrite `PolicyOptimizer.save` and `PolicyOptimizer.restore` for `sync_replay_optimizer.py` and `async_samples_optimizer.py` (if you want to do it for DDPG). 

Would you be interested in pushing a PR? Otherwise, I can get to this tomorrow.

**Comment by Scitator** [comment]
@richardliaw 
Sorry for such late answer (I am at ConvAI2 now, so no free time).
Nevertheless, I can try to PR next week, but if you can do it - it would be great. I still don't know all Ray specific (and because of many refactoring commits over 2 previous weeks), so would much appreciate your help.

**Comment by Scitator** [comment]
@richardliaw is there any progress already? or can I try to PR this feature?

**Comment by richardliaw** [comment]
Hey sorry, I’ve been traveling and didn’t make progress on this; a PR would
be great!

**Comment by ericl** [comment]
Re-using old experiences will be possible with the I/O API in the future.

**Comment by dvillero** [comment]
Hi Gents, was this ever resolve? I'm running into a similar issue: I have saved previous experiences, which I use to pre-train my RAINBOW policy. However, to stop my offline training and connect to the life workers I have restart the policy which inherently empties the replay buffer.  Is there a way to stop offline training and plug in the environment workers without restarting the policy server or emptying the buffer?
