### ISSUE TITLE
[core][java][Bug] Cannot put object references onto object store with modern version of Java 

### ISSUE THREAD

**Issue by frreiss** [ray-project/ray#23347]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

With Java 17, Java code that attempts to write an object reference to object storage fails. More specifically:
* The code from the test case `https://github.com/ray-project/ray/blob/master/java/test/src/main/java/io/ray/test/ObjectRefTransferTest.java` does not work on Java 17
* The following simpler test program also does not work:
   ```java
   Ray.init();
   List<ObjectRef<String>> refsList = new ArrayList<ObjectRef<String>>();
   Ray.put(refsList);
   ```

In both cases, an exception similar to the following is thrown:
```
java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @6193b845

	at io.ray.runtime.serializer.MessagePackSerializer.encode(MessagePackSerializer.java:276)
	at io.ray.runtime.serializer.Serializer.encode(Serializer.java:8)
	at io.ray.runtime.object.ObjectSerializer.serialize(ObjectSerializer.java:165)
	at io.ray.runtime.object.ObjectStore.put(ObjectStore.java:64)
	at io.ray.runtime.AbstractRayRuntime.put(AbstractRayRuntime.java:78)
	at io.ray.api.Ray.put(Ray.java:62)
```

This problem appears to be due to some changes to Java's security model that were introduced in Java 9. See [this post on StackOverflow](https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m) for more information.

This issue is blocking me because the code I want to run does not work with Java 8.

### Versions / Dependencies

Ray 1.10
MacOS 12.2.1 (Monterey)
Java version info:
```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

### Reproduction script

```java
Ray.init();
List<ObjectRef<String>> refsList = new ArrayList<ObjectRef<String>>();
Ray.put(refsList);
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by frreiss** [comment]
Two updates from further testing:
* It looks like Ray's serialization of *any* object that contains a `String` field is not working on Java 17.
* Downgrading to Java 11 allows my program to work, but it prints out a warning message every time it runs:
   ```
   WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (file:/Users/[user name]/.m2/repository/de/ruedigermoeller/fst/2.57/fst-2.57.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.nustaq.serialization.FSTClazzInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
   ```

**Comment by simon-mo** [comment]
@raulchen please help triage

**Comment by frreiss** [comment]
One way to address this issue is to communicate that Ray only supports Java versions 1.8 through 11, inclusive. You could enforce that through two updates:
* Add a note about Java version compatibility to https://github.com/ray-project/ray/edit/master/doc/source/ray-overview/installation.rst, under the heading, "Install Ray Java with Maven".
* Add code to check the Java version at the top of [Ray.init()](https://github.com/ray-project/ray/blob/22c9c4aa391fbe6743502d66112472143f40464e/java/api/src/main/java/io/ray/api/Ray.java#L16). Exit with an error or print a warning if the Java version is greater than 11.x. The version compatibility flags in your compiled source already prevent Java versions below 1.8 from loading Ray's class files.

**Comment by jovany-wang** [comment]
Actually, we haven't supported >JDK11. For the concrete exception, I'll take a look later.

**Comment by kfstorm** [comment]
Ray Java depends on https://github.com/RuedigerMoeller/fast-serialization for serialization, and it doesn't support Java 17 yet. See https://github.com/RuedigerMoeller/fast-serialization/issues/312 for details. @jovany-wang Could we try adding [this](https://github.com/RuedigerMoeller/fast-serialization/issues/312#issuecomment-911770257) to our codebase?

**Comment by raulchen** [comment]
@lixin-wei could you also take look?
