### ISSUE TITLE
[Bug] [dataset] Idle workers and possible memory leak after ray dataset job

### ISSUE THREAD

**Issue by isaac-vidas** [ray-project/ray#23359]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

After running a dataset pipeline on a Ray cluster of about ~1000 CPUs across 70 nodes, a large amount of IDLE workers stay around after the job is done. In addition a lot of memory is being used across the nodes in the cluster.

The problem seems to be reproducible with the following code:

```python
class ModelPredictor:
    def __init__(self, model_ref, features):
        self.model_ref = model_ref
        self.features = features
        self._model = None

   @staticmethod
    def df_to_model_input(df):
        return {
            feature: np.array(series.values.tolist())[:, None]
            for feature, series in df.to_dict(orient="series").items()
        }

    @property
    def model(self):
        import tensorflow as tf  # noqa

        try:
            import tensorflow_text  # noqa
        except ImportError:
            pass
        if self._model is None:
            self._model = ray.get(self.model_ref)
        return self._model

    def __call__(self, df):
        X = self.df_to_model_input(df[self.features])
        predictions = self.model.predict(X)
        return df.assign(**{name: list(values) for name, values in predictions.items()})

# Load model and save ref
model = tf.keras.models.load_model(model_path)
model_ref = ray.put(model)

features = list(model.signatures["serving_default"].structured_input_signature[1].keys())

# Read parquet files
parquet_files = [...] # about 10 files with about 10M records

# Create pipeline
pipeline = ray.data.read_parquet(parquet_files, filesystem=fs, _spread_resource_prefix="node:")
# pipeline = Dataset(num_blocks=10, num_rows=9990831, schema=...)

# Repartition across the cluster of 1000 workers
pipeline = pipeline.repartition(num_blocks=1000)
# pipeline = Dataset(num_blocks=1000, num_rows=9990831, schema=...)

pipeline = pipeline.map_batches(
    ModelPredictor(model_ref, features),
    batch_size=100,
    batch_format="pandas",
    num_cpus=1,
)

pipeline.write_parquet(output_path, filesystem=fs)
```

See the following dashboard images after the `write_parquet` finished running:

All of the workers here are idle:
<img width="523" alt="Ray Dashboard 2022-03-19 17-43-45" src="https://user-images.githubusercontent.com/80056737/159139412-fbc45867-7261-4c37-bff2-58f5c0e57f19.png">

Workers are idle and memory is still being used:
<img width="1328" alt="Ray Dashboard 2022-03-19 17-47-07" src="https://user-images.githubusercontent.com/80056737/159139572-6429fd1a-4b71-4f80-8ac2-eae2830a59a8.png">

<img width="1256" alt="Ray Dashboard 2022-03-19 17-50-24" src="https://user-images.githubusercontent.com/80056737/159139633-93a9ff16-398a-48fc-9a90-b073913ec391.png">

### Versions / Dependencies

OS: ubuntu 18.04
python: 3.7.9

```
ray[default,tune]==1.9.1
tensorflow==2.7.0
tensorflow-text==2.7.3
tensorflow-hub==0.9.0
fsspec==2021.10.1
pandas==1.3.3
tqdm==4.62.3
pyarrow==6.0.0
gcsfs==2021.10.1
google-cloud-storage==1.42.3
tenacity>=8.0.1,<9.0.0
```

### Reproduction script

```python
class ModelPredictor:
    def __init__(self, model_ref, features):
        self.model_ref = model_ref
        self.features = features
        self._model = None

   @staticmethod
    def df_to_model_input(df):
        return {
            feature: np.array(series.values.tolist())[:, None]
            for feature, series in df.to_dict(orient="series").items()
        }

    @property
    def model(self):
        import tensorflow as tf  # noqa

        try:
            import tensorflow_text  # noqa
        except ImportError:
            pass
        if self._model is None:
            self._model = ray.get(self.model_ref)
        return self._model

    def __call__(self, df):
        X = self.df_to_model_input(df[self.features])
        predictions = self.model.predict(X)
        return df.assign(**{name: list(values) for name, values in predictions.items()})

# Load model and save ref
model = tf.keras.models.load_model(model_path)
model_ref = ray.put(model)

features = list(model.signatures["serving_default"].structured_input_signature[1].keys())

# Read parquet files
parquet_files = [...] # about 10 files with about 10M records

# Create pipeline
pipeline = ray.data.read_parquet(parquet_files, filesystem=fs, _spread_resource_prefix="node:")
# pipeline = Dataset(num_blocks=10, num_rows=9990831, schema=...)

# Repartition across the cluster of 1000 workers
pipeline = pipeline.repartition(num_blocks=1000)
# pipeline = Dataset(num_blocks=1000, num_rows=9990831, schema=...)

pipeline = pipeline.map_batches(
    ModelPredictor(model_ref, features),
    batch_size=100,
    batch_format="pandas",
    num_cpus=1,
)

pipeline.write_parquet(output_path, filesystem=fs)
```

### Anything else

This problem happens every time I use Ray Dataset.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ericl** [comment]
What's the object store size per node? This is pretty normal for newly started clusters. The object store size will grow up the configured max capacity and stay there, and Ray caches idle workers in its worker pool.

If the memory keeps growing over time as you submit more jobs, then that would be something to be concerned about.

**Comment by isaac-vidas** [comment]
> What's the object store size per node?

Object store size is the plasma right? It's the default 30% of each worker so in this case ~100GB.

> If the memory keeps growing over time as you submit more jobs, then that would be something to be concerned about.

From my experience, if I will run a new job on the same cluster the RAM will continue to increase until OOM.

**Comment by ericl** [comment]
I see. I think in your example this is because you didn't specify compute="actors" (or ActorPoolSpec in master). This can cause those callable classes to be leaked. In master we raise a warning in this scenario.

Can you try again with using compute="actors"? The actor processes should get terminated after the stage finishes.

**Comment by isaac-vidas** [comment]
> Can you try again with using compute="actors"? The actor processes should get terminated after the stage finishes.

Sure, I'll give it another go. In the past I had more trouble keeping the job stable with `compute="actors"` so I usually avoid using it if I already have a full cluster up and running but I can try again and check how it goes.

**Comment by ericl** [comment]
Sounds good. Btw, the new ActorPoolSpec allows you to control the min/max pool size explicitly, which might help with stability of jobs.

**Comment by isaac-vidas** [comment]
Thanks @ericl!
Do you mean [this section](https://docs.ray.io/en/master/data/getting-started.html?highlight=ActorPoolStrategy#transforming-datasets)? This looks pretty awesome!

Just making sure, this would only be available in the nightly build until the next Ray release, right?

**Comment by ericl** [comment]
Yep, it's only in nightly for now, should be in next release also.

**Comment by isaac-vidas** [comment]
Ok, good to know and thanks for the info. I'll run a couple of more tests and update it here.

**Comment by arshad171** [comment]
Hi,

Even I observe the same behavior. I have set `max_calls=1` for the remote functions I'm executing, but the idle workers don't seem to release the resources on completion of the task.

![image](https://user-images.githubusercontent.com/37022146/161419033-c0e49722-db59-485e-9249-abee6674837e.png)

As seen above, idle workers are hogging up to 1 GB of memory.

Is there a way to configure ray to kill idle workers after a idle time?

I know `ray.init` accepts `_system_config` with `kill_idle_workers_interval_ms` param, but it is only meant for dev/testing, and I could not pass the arg when connecting to an existing cluster.
