### ISSUE TITLE
[serve] Support access logs by default for HTTP (& deployment handles?)

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23376]
From @tgaddair:

> I've been using the FastAPI deployment feature of Ray Serve, it works well. However, I noticed that we don't get the nice logs from FastAPI telling us which endpoints are being hit:
> `INFO:     127.0.0.1:64266 - "GET /ping HTTP/1.1" 200 OK`
> This complicates debugging, as you might expect. Is there a simple way to enable this level of logging in Ray Serve? (I tried a few things with custom middleware, but it turned out to be quite a bit more complicated than I would have expected).

We should:

1. Have these on by default.
2. Have a way to turn it off.
3. Also support it for serve handle calls

**Comment by edoakes** [comment]
@simon-mo I'm thinking we should just properly configure the `"ray.serve"` logger and allow people to customize it as they wish, then use it for HTTP & serve handle logging. Should be quite simple but a huge QoL boost.

**Comment by simon-mo** [comment]
Relevant uvicorn code
https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/h11_impl.py#L430-L438

Currently turned off here 
https://github.com/ray-project/ray/blob/master/python/ray/serve/http_proxy.py#L387

**Comment by simon-mo** [comment]
Supported now! thx @edoakes
