### ISSUE TITLE
[core] Allow custom formatting for logs from remote processes

### ISSUE THREAD

**Issue by chhabrakadabra** [ray-project/ray#23388]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

I would like to configure the logging from both the driver and the remote tasks to be JSON formatted. When I try the attached snippet of code, the outcome is unexpected:

```text
% python logging_test.py
{"name": "ray._private.services", "msg": "View the Ray dashboard at http://127.0.0.1:8265"}
{"name": "root", "msg": "About to trigger remote function"}
(func pid=79618) {"name": "root", "msg": "I'm running inside a remote func"}
```

Note the `(func pid=20855)` at the start of the log message from the remote task. This disrespects the logging configurations. Currently, there seems to be no way around this issue. From what I can tell, the `print_worker_logs` function in `python/ray/worker.py` uses plain `print` along with hardcoded formatting.

### Versions / Dependencies

- Ray version: `1.9.2`
- Python version: `3.9.8`
- OS: osx version `12.2.1`
- No other libraries used

### Reproduction script

```python
import logging
import sys

import ray

logger = logging.getLogger()


def configure_root_logger():
    handler = logging.StreamHandler(stream=sys.stdout)
    # In reality, I might use a library like pythonjsonlogger
    handler.setFormatter(logging.Formatter('{"name": "%(name)s", "msg": "%(message)s"}'))

    root_logger = logging.getLogger()
    root_logger.addHandler(handler)
    root_logger.setLevel("INFO")


@ray.remote
def func():
    configure_root_logger()
    logger.info("I'm running inside a remote func")


if __name__ == "__main__":
    configure_root_logger()
    ray.init(configure_logging=False)
    logger.info("About to trigger remote function")
    ray.get(func.remote())
```

### Anything else

The problem is very reproducible. 

I'm also willing to submit one or more PRs for this issue, but I'd love some guidance from the Ray team. Should I just change the `print_worker_logs` function to use a logger instead of printing? Should I change the `connect` method in `worker.py` to use a different handler based on a user-provided switch (or environment variable)?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment]
The reason you see the `(func pid=xxx)` is to differentiate between messages printed by the driver process and messages printed by the remote worker. Otherwise, the output can be very confusing because it's not possible to tell which messages are from the local process, so we don't have plans to change this behavior or to allow it to be overridden.

A potential workaround is to take the logs from the worker's output. Look for these files: `/tmp/ray/session_latest/logs/worker-*`

**Comment by jon-chuang** [comment]
> I would like to configure the logging from both the driver and the remote tasks to be JSON formatted.

Sounds like you have a downstream consumer of the JSON formatted logs? In that case, are you thinking of piping the driver stdout into a separate consumer? 

In that case, it shouldn't be too hard to just parse the stdout and remove all of the non-JSON output?

**Comment by rkooo567** [comment]
oh yeah this is the important issue

**Comment by kevin85421** [comment]
Although `(func pid=20855)` in the driver log disrespects the logging configurations, the log file located in `/tmp/ray/session_latest/logs` adheres to the configurations. You can stream the log files to your logging infrastructure.

<img width="491" alt="Screen Shot 2024-03-17 at 5 22 51 PM" src="https://github.com/ray-project/ray/assets/20109646/c1f0b718-7e26-40cb-ad7f-df61b67ad838">
