### ISSUE TITLE
[Bug] the trainer stuck when enabling the use_gpu option and running trainer.start()

### ISSUE THREAD

**Issue by keep9oing** [ray-project/ray#23395]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Train

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

I tried to follow the document at https://docs.ray.io/en/latest/train/user_guide.html#backends
with
```python
from ray.train import Trainer
trainer = Trainer(backend="torch", num_workers=2, use_gpu=True)
trainer.start()
...
```
However, the progress does not go over with start() method. 
I have Nvidia GPU and also have trained with it via RLlib library.

The code above works well when I remove the use_gpu option.
Please check it out. Thank you.

### Versions / Dependencies

python==3.9.7
ray==1.11.0

OS: ubuntu 20.04
GPU: NVIDIA Geforce RTX 2080

### Reproduction script

Stuck at the moment below.

2022-03-22 11:11:17,420	INFO services.py:1412 -- View the Ray dashboard at http://127.0.0.1:8265
2022-03-22 11:11:18,857	INFO trainer.py:199 -- Trainer logs will be logged in: /home/keep9oing/ray_results/train_2022-03-22_11-11-18

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by amogkam** [comment]
Hey @keep9oing, if you have num_workers set to 2, then this requires at least 2 GPUs to start the trainer. Can you confirm the number of gpus your ray cluster has? You can do this with just printing ray.cluster_resources().

also is there anything being printed out in stdout? I believe there should be a message saying that your cluster may not have enough resources.

**Comment by matthewdeng** [comment]
Can you share the output of `ray status` when this is hanging?

**Comment by keep9oing** [comment]
Thank you @amogkam , I had a single GPU. When matching the number of workers and the number of GPUs solve the problem. Maybe I misunderstood the option.
