### ISSUE TITLE
[rllib] Preprocessors should support `reset`

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2339]
### Describe the problem
You may want to reset things depending on episode, like the frameskip buffer. 

https://github.com/openai/gym/blob/5404b39d06f72012f562ec41f60734bd4b5ceb4b/gym/core.py#L305

**Comment by ericl** [comment]
I don't think we should support this, env wrappers should be used instead.

Arguably preprocessors should be deprecated since they only support a subset of env wrapper functionality.

**Comment by richardliaw** [comment]
Can you create a followup issue to track that?
