### ISSUE TITLE
Certain codes may not avoid unexpected serialization of worker

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#2341]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Ray installed from (source or binary)**: source
- **Ray version**: latest
- **Python version**: any
- **Exact command to reproduce**:

```python
import ray
import ray.cloudpickle as pickle
foo = "do_not_serialize_me"  # global variable
def get_foo(foo=foo):
    return foo

def get_foo2():
    return foo

def bar():
    get_foo()

def bar2():
    get_foo2()

assert bytes(foo, 'ascii') not in cloudpickle.dumps(bar)  # Fail
assert bytes(foo, 'ascii') not in cloudpickle.dumps(bar2)  # Fail

```

### Describe the problem
In `worker.py`, `get_global_worker` and `_mode` are implemented to avoid serialization of worker. However, this example shows that they hardly work because cloudpickle will try to serialize everything related to a function. 

### Source code / logs

```python
def _mode(worker=global_worker):
    """This is a wrapper around worker.mode.
    We use this wrapper so that in the remote decorator, we can call _mode()
    instead of worker.mode. The difference is that when we attempt to serialize
    remote functions, we don't attempt to serialize the worker object, which
    cannot be serialized.
    """
    return worker.mode


def get_global_worker():
    return global_worker
```

**Comment by robertnishihara** [comment]
Is this a problem you're running into with the current codebase? Or only after some modifications that you've made?

**Comment by ericl** [comment]
Auto-closing stale issue.
