### ISSUE TITLE
[Feature][Java] Support passing RayConfig to `Ray.init()`

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#23415]
### Description

RuntimeEnv is too complex to be written as system properties in Java. We're proposing supporting passing RayConfig to `Ray.init()` for make RayConfig programmable.

The API and behavior should be like:
```java
System.setProperty("ray.job.runtime-env.env-vars.KEY1", "A");
System.setProperty("ray.job.runtime-env.env-vars.KEY2", "B");

RayConfig config = RayConfig.getInstance();
config.runtimeEnv.setEnvVar("KEY1", "C");
config.runtimeEnv.setEnvVar("KEY2", "C");
Ray.init(config);
```
The value of `KEY1` should be `A` and value of `KEY2` should be `C`.

**Comment by jovany-wang** [comment]
@SongGuyang @kfstorm @Catch-Bull @raulchen

**Comment by raulchen** [comment]
This is a good idea. But I think we need to use a different class, instead of the current "RayConfig". "RayConfig" already exposes too many implementation details. The new class should be much simpler, and it doesn't have to depend on the typesafe config lib.

**Comment by jovany-wang** [comment]
> This is a good idea. But I think we need to use a different class, instead of the current "RayConfig". "RayConfig" has too many implementation details. The new class should be much simpler, and it doesn't have to depend on the typesafe config lib.

I'd like to use `RayConfig` as the API class. Maybe we could rename current `RayConfig` class to `RayInternalConfig` or `TypeSafeConfig`. or do you have other thoughts? @raulchen @kfstorm @SongGuyang

**Comment by jovany-wang** [comment]
I believe the priority should be system property first, because we still need an approach to change the configuration value when code is not changed.

The implementation details  could be:
1. All configuration items in RayConfig class are optional, to let us know which items are set or not for further merging.
2. Items set via system properties should be set into RayConfig.

**Comment by jovany-wang** [comment]
> I believe the priority should be system property first, because we still need an approach to change the configuration value with no code changing.
> 
> The implementation details could be:
> 
> 1. All configuration items in RayConfig class are optional, to let us know which items are set or not for further merging.
> 2. Items set via system properties should be set into RayConfig.

I updated the issue description according this merging logic.
