### ISSUE TITLE
[Bug] integration test test_placement_group_5  is flakey

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23429]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

test_placement_group_5 has been frequently timing out. We should deflake it.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@jon-chuang can you take a look? cc @rkooo567 as well.

**Comment by rkooo567** [comment]
Relevant PR https://github.com/ray-project/ray/pull/23350
