### ISSUE TITLE
Plasma error for A3C

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2343]
Repeatedly getting errors in the A3C Regression test on Jenkins with the test dying.

The test run is `cd rllib/ && python train.py -f tuned_examples/regression_tests/cartpole-a3c.yaml`

```
[  0.00%] --- Setting up /ray/python/ray/rllib/tuned_examples/regression_tests/regression_test.py:101
[  0.00%] ---- /ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:620 Check failed: object_entry != objects_in_use_.end() 
               Traceback (most recent call last):
                 File "/tmp/asv/asv/benchmark.py", line 867, in <module>
                   commands[mode](args)
                 File "/tmp/asv/asv/benchmark.py", line 818, in main_setup_cache
                   cache = benchmark.do_setup_cache()
                 File "/tmp/asv/asv/benchmark.py", line 395, in do_setup_cache
                   return self._setup_cache()
                 File "/ray/python/ray/rllib/tuned_examples/regression_tests/regression_test.py", line 102, in setup_cache
                   return _evaulate_config(self._file)
                 File "/ray/python/ray/rllib/tuned_examples/regression_tests/regression_test.py", line 26, in _evaulate_config
                   trials = tune.run_experiments(experiments)
                 File "/ray/python/ray/tune/tune.py", line 104, in run_experiments
                   raise TuneError("Trials did not complete", errored_trials)
               ray.tune.error.TuneError: ('Trials did not complete', [A3C_CartPole-v0_0])
```

cc @pcmoritz

**Comment by wyndwarrior** [comment]
I have this error as well in a different usecase:

```
/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:620 Check failed: object_entry != objects_in_use_.end()
Aborted (core dumped)
```

**Comment by richardliaw** [comment]
Hey Andrew, can you post more info on your workload?

**Comment by dementrock** [comment]
@richardliaw I work on the same team with @wyndwarrior. We are not using rllib nor ray’s actor. We launch ray on a single machine and then use plasma as a message passing layer between several local processes. Occasionally we observe this error.

**Comment by pcmoritz** [comment]
In particular, does it use pytorch? We would really like to understand this error better but haven't seen it in a cleanly reproducible form so for unfortunately.

Any scripts that can reproduce it would be helpful.

**Comment by dementrock** [comment]
We also haven’t figured out a reproducible case. Some processes do use pytorch. @wyndwarrior can provide more detail.

**Comment by pcmoritz** [comment]
That would be very helpful!

**Comment by dementrock** [comment]
Ok, it seems like the error happens between some non-pytorch process and some pytorch process. However it’s the non-pytorch process that crashes.
