### ISSUE TITLE
[air] LightGBM Trainer should use `num_cpus_per_actor=2` by default

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#23449]
- [ ] LightGBM trainer should use `num_cpus_per_actor=2` by default
- [x] https://github.com/ray-project/ray/issues/23448
- [x] ~~Annoying to have to figure out how to create a manual scorer class and pass in the checkpoint object reference. Have to use examples to figure out how to do this.~~ Resolved by Batchpredictor! (https://github.com/ray-project/ray/pull/23808) 
- [x] ray.data does not have a method to drop columns for prediction. Have to do this in the scorer class after the conversion to pandas.

**Comment by Yard1** [comment]
Waiting on https://github.com/ray-project/ray/pull/25712
