### ISSUE TITLE
[Train] Issue on page /train/user_guide.html

### ISSUE THREAD

**Issue by davidegraff** [ray-project/ray#23480]
the first example code block will result in an `AttributeError` because `torch` isn't imported in `ray.train.__init__py`

the block in question:
```python
import torch
from torch.nn.parallel import DistributedDataParallel
+from ray import train


def train_func():
-   device = torch.device(f"cuda:{train.local_rank()}" if
-         torch.cuda.is_available() else "cpu")
-   torch.cuda.set_device(device)

    # Create model.
    model = NeuralNetwork()

-   model = model.to(device)
-   model = DistributedDataParallel(model,
-       device_ids=[train.local_rank()] if torch.cuda.is_available() else None)

+   model = train.torch.prepare_model(model)

    ...
```

**Comment by dynamicwebpaige** [comment]
Thanks for filing the issue! I was able to run the code sample you shared without error:

```python
import torch
from torch.nn.parallel import DistributedDataParallel
from ray import train

def train_func():
  device = torch.device(f"cuda:{train.local_rank()}" if torch.cuda.is_available() else "cpu")
  torch.cuda.set_device(device)
  
  model = NeuralNetwork()
  model = model.to(device)
  model = DistributedDataParallel(model, device_ids=[train.local_rank()] if torch.cuda.is_available() else None)
  model = train.torch.prepare_model(model)
```

Though there do appear to be some rendering and formatting issues with the documentation in the [Ray Train user guide](https://docs.ray.io/en/latest/train/user_guide.html#update-training-function). These quirks are persisted when clicking the `copy` button on the right hand side of the code block:

![image](https://user-images.githubusercontent.com/3712347/160269132-320b30f0-83f8-45d9-a9ce-0b671cf3eadc.png)

cc: @maxpumperla

**Comment by maxpumperla** [comment]
@dynamicwebpaige thanks. these "-/+" thingies have been put there intentionally by the Train team to indicate what has to be changed compared to normal torch training (cc @matthewdeng). Apart from that, what exactly do you mean be "rendering" issues?

If you ask me, I'd rather not have this "diff" feature in there for pedagogical reasons, especially since the code is not copyable. We should also move the code in question into a file, include it, and test it in CI.

**Comment by amogkam** [comment]
I personally am a fan of having the diff here to have a visual of how much your code can be simplified with Ray Train- this is what I liked about going through the Huggingface Accelerate docs for example: https://github.com/huggingface/accelerate. It also gives an overview of what exactly `prepare_model` and `prepare_data_loader` are doing, and what parts of your distributed pytorch code you no longer need. The downside being of course that it is not directly copy-pasteable.

One thing we can do is link to a fully runnable e2e example at the top of this section.

**Comment by amogkam** [comment]
Like compare the Huggingface accelerate docs: https://huggingface.co/docs/accelerate/index with Lightning Lite: https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html.

For Lightning Lite, they have the before/after in 2 separate code blocks, but for me it's much harder to tell what has changed compared to the Huggingface docs. This is why they also have the gif at the top I guess.

**Comment by dynamicwebpaige** [comment]
🙂 Thank you both for the clarification (in that the `+` and `-` additions to the code snippet indicate lines of code that have been changed, compared to Torch training).

> One thing we can do is link to a fully runnable e2e example at the top of this section, which you can then copy-paste and run.

+1 for having an end-to-end, testable example at the top of the section. Given that most users would probably be interested in a runnable code snippet when quick-selecting the `copy` button, would it be possible to have clicking the `copy` button _not_ copy those `+`s and `-`s? Or, as a stopgap, we could consider removing the `copy` button entirely for diffed code snippets, to nudge users toward the end-to-end example.

**Comment by davidegraff** [comment]
sidestepping the conversation about the readability of this block- I must be going crazy because when I run the following block:
```python
from ray import train

# model: torch.nn.module
model = train.torch.prepare_model(model)
```
I get an `AttributeError`. I'm confused why others aren't reporting this because `torch` isn't imported in the `train` top-level `__init__.py` file

**Comment by davidegraff** [comment]
I know I need to do that- that's how I've fixed it in my own code. But my point is this example from the docs is *broken*. Also, my two cents, the example is clear enough right now. I never thought to copy the plus and minus symbols into my own code to try and run it. I may not be bright, but I'm smarter than the average bear. A third penny, for those who want it, is that yes, it would be nice to have a snippet that you could honestly copy-paste to test.

**Comment by dynamicwebpaige** [comment]
> _The example from the docs is broken._

+1, and thank you for flagging this! We appreciate the issue; and as @amogkam mentions, this should now be fixed in master. I apologize for hijacking the issue to talk about formatting. 🙂 

> _I may not... smarter than the average bear_

You're brighter than you think! And there might be other users who get confused by the `+` / `-` symbols in examples. Speaking personally, knew not to try running them; but sure found it tedious to remove them from the `copy`-ed code snippet. 😅 

> _yes, it would be nice to have a snippet that you could honestly copy-paste to test._

Strong +1, very much agreed. 👍

**Comment by amogkam** [comment]
Closing as the initial issue has been resolved
