### ISSUE TITLE
[Feature] change name of "travis" folder in CI

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#23497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

the `ci/travis` folder is confusing. The `ci/README.md` also mentions Travis, could be interpreted in all sorts of ways. maybe time to change that to something more agnostic? After all, we're not using Travis anymore.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
done by @krfricke
