### ISSUE TITLE
[Bug] zip method does not work for Ray Datasets created from pandas DataFrames

### ISSUE THREAD

**Issue by lily-gao** [ray-project/ray#23501]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

When I try to zip two Ray Datasets created from pandas DataFrames, I get an `AttributeError: 'DataFrame' object has no attribute 'column_names'`. 

Changing a few lines in the source code for `PandasBlockAccessor` solves the issue.

### Versions / Dependencies

* python version  3.7.11 
*  nightly version of ray, installed using `pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-macosx_10_15_intel.whl`
* `pandas` version `1.2.4`, also tested on `1.4.1`

### Reproduction script

```
import ray
import pandas as pd

ds1 = ray.data.from_pandas(pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]}))
ds2 = ray.data.from_pandas(pd.DataFrame({'col3': ['a', 'b', 'c'], 'col4': ['d', 'e', 'f']}))
ds1.zip(ds2)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by matthewdeng** [comment]
@jianoaix can you take a look at this?
