### ISSUE TITLE
[Feature] getting redis password from environment variable

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/ray#23502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

when submitting a job to ray. the script will do an initialization using the head address discovered from an environment variable. However, when redis password is specified, the password is not available in environment variables. Shall we lookup it up in environment variables?

### Use case

When we submit a job to ray, putting the hardcoded password inside the script might not be a good idea. Putting it inside ray cluster as an environment variable can be a better approach.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
@ckw017

**Comment by ckw017** [comment]
@wilsonwang371 Can you describe your workflow in a bit more detail, specifically:
* How was the cluster launched (manually running ray start --head somewhere, going through `ray cluster up`, etc...)
* When/where are you generating the password

@mwtian Is core currently trying to clean up references to redis (--redis-address, --redis-password) from the API for the switch to HA GCS? Trying to figure out if adding this would cause too much clutter. Feel free to loop-in someone else if you don't have context.

**Comment by ericl** [comment]
We no longer use Redis by default in the latest Ray release, so these flags should be considered deprecated and have no effect.
