### ISSUE TITLE
[Feature] support set memory limit in ray tune

### ISSUE THREAD

**Issue by wuyeguo** [ray-project/ray#23528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

when use ray tune with a trianable function like this

tune.run(
    train_fn,
    resources_per_trial={"CPU": 2, "GPU": 0.5})

is there a config for set the memory used for one running？

### Use case

tune.run(
    train_fn,
    resources_per_trial={"CPU": 2, "GPU": 0.5， “MEM”: 2 * 1024 * 1024 * 1024})

if the worker has 4G free memory, while run just 2 actor once

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wuyeguo** [comment]
> 
Hi @krfricke 
thank you for your tips.

I modify my code like this
```
analysis = tune.run(lr_train,
                    config=search_space,
                    resources_per_trial={
                        "cpu": 2,
                        "gpu": 0,
                        "memory": 2 * 1024 * 1024 * 1024,
                   },
                   )
```
but i get exception like this
```
(run pid=10299) 2022-03-29 10:37:59,141 ERROR ray_trial_executor.py:558 -- Trial lr_train_3eefd_00000: Unexpected error starting runner.
(run pid=10299) Traceback (most recent call last):
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 549, in start_trial
(run pid=10299)     return self._start_trial(trial)
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 447, in _start_trial
(run pid=10299)     runner = self._setup_remote_runner(trial)
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 391, in _setup_remote_runner
(run pid=10299)     return full_actor_class.remote(**kwargs)
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/actor.py", line 532, in remote
(run pid=10299)     return actor_cls._remote(
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 371, in _invocation_actor_class_remote_span
(run pid=10299)     return method(self, args, kwargs, *_args, **_kwargs)
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/actor.py", line 766, in _remote
(run pid=10299)     resources = ray._private.utils.resources_from_resource_arguments(
(run pid=10299)   File "/home/ray/anaconda3/envs/ray/lib/python3.9/site-packages/ray/_private/utils.py", line 342, in resources_from_resource_arguments
(run pid=10299)     raise ValueError("The resources dictionary must not "
(run pid=10299) ValueError: The resources dictionary must not contain the key 'memory' or 'object_store_memory'

```

my ray cluster has two node and the start cmd like this

```
head_start_ray_commands:
config=~/ray_bootstrap_config.yaml
    - conda activate ray && ray stop
    - conda activate ray && ulimit -c unlimited && TUNE_PLACEMENT_GROUP_AUTO_DISABLED=1 && ray start --head --port=26379 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - conda activate ray && ray stop
    - conda activate ray && TUNE_PLACEMENT_GROUP_AUTO_DISABLED=1 && ray start --address=$RAY_HEAD_IP:26379
```

**Comment by wuyeguo** [comment]
@krfricke 
from pr https://github.com/ray-project/ray/pull/19773 ， ray has delete the config support for memory
but in document，it's supported， https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html

my python version 3.9.7， ray version 1.11

my target is use memory limit the train func concurrency in one single worker
what should I do ？

thanks 。

**Comment by chjhuang** [comment]
It seems that there is a code bug in file `tune/utils/placement_groups.py`:
![image](https://user-images.githubusercontent.com/3814012/161201908-2bfccde1-be03-42ed-bdc5-c6f466bbac66.png)
the `memory/object_store_memory` key may also should be pop up.

**Comment by BobvanSchendel** [comment]
I've had this issue just now and it's not clear how to set the memory now for Ray Tune since the docs don't seem to be updated. Is there any resource I can be pointed to as to how to set max memory limits now?
