### ISSUE TITLE
[Java Release Issue] No such ray-1.11.0 jar found in maven central repo

### ISSUE THREAD

**Issue by ashione** [ray-project/ray#23529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I just want to use released ray-1.11.0 java and found that no such package had been uploaded in maven central repo.
Anybody can trace that release pipeline and make sure this workitem has been finished in last release?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ashione** [comment]
@jovany-wang Could you know that release detail about 1.11.0 java related package?

**Comment by jovany-wang** [comment]
@mwtian CC

**Comment by ashione** [comment]
@mwtian I can even guess that no one is willing to check the entire checklist of the release process. this can not be said that it is not a careless. As a project that has been open source for a few years now, this is not a one-time occurrence, and we don't even know what caused this. In my opinion this is a major mistake in principle. If these can't be implemented, it's hard to ask other developers to follow any more rules, which ultimately leads to the whole open source ecosystem being in jeopardy. @jovany-wang

**Comment by mwtian** [comment]
I have ran through the Java release instructions twice, but it seems the jars are landing in the `JCentral` repo, without the Ray api jar either. Does anyone have ideas about how to fix that?

**Comment by jovany-wang** [comment]
![image](https://user-images.githubusercontent.com/19473861/160763146-3d0dd5ef-b686-4840-bca1-5497f716992d.png)

It seems to have been released successfully yesterday?

**Comment by mwtian** [comment]
Looks like the packages show up in Maven central now: https://mvnrepository.com/artifact/io.ray/ray-api/1.11.0
