### ISSUE TITLE
[Feature] Scale down Ray serve deployments to 0

### ISSUE THREAD

**Issue by Purvak-L** [ray-project/ray#23547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I want to have the control to scale down a model to 0 replicas when it's deployed using Ray Serve. Currently, the autoscaling_config in Ray serve doesn't allow min_replicas as 0. A nice to have will be to also control idle time per ray serve deployment. This will help free up resources when no load is present for a given model. I would also assume that the resources will free up.

Discussion: https://discuss.ray.io/t/deploy-a-model-which-scales-down-to-0-replicas/5572

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Purvak-L** [comment]
cc: @jiaodong

**Comment by Purvak-L** [comment]
@jiaodong / @shrekris-anyscale  / @simon-mo  Any updates on this? It would be quite useful for us!

**Comment by simon-mo** [comment]
The implementation was just merged in master. Thanks @sihanwang41: https://github.com/ray-project/ray/commit/b024a9543e5379c5695c50da577971a88bf699ef

Documentation incoming.

**Comment by Purvak-L** [comment]
@simon-mo Great news! Looking forward to this!
Thanks, @sihanwang41 !

**Comment by Purvak-L** [comment]
@simon-mo / @sihanwang41 I was using a nightly build and used the zero replicas feature (I understand it might not be feature complete as of now) and while stopping/shutting down the server I got following Exception -

`Exception ignored in: <function RayServeHandle.__del__ at 0x7f0eefd348c0>
Traceback (most recent call last):
 File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/handle.py", line 222, in __del__
 File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serve/handle.py", line 128, in stop_metrics_pusher
 File "/home/ray/anaconda3/lib/python3.7/threading.py", line 522, in set
 File "/home/ray/anaconda3/lib/python3.7/threading.py", line 365, in notify_all
 File "/home/ray/anaconda3/lib/python3.7/threading.py", line 348, in notify
TypeError: 'NoneType' object is not callable`

**Comment by simon-mo** [comment]
Thanks! Can you open another issue with the script you are trying and tag @sihanwang41 and me? Thank you so much!
