### ISSUE TITLE
[Feature] Support for `worker_start_ray_commands` per node type

### ISSUE THREAD

**Issue by melonipoika** [ray-project/ray#23554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

It should be possible to have different `worker_start_ray_commands` for each node type in the cluster.

Ray already support different `worker_setup_comamnds` and `docker` for each note type [[1]](https://docs.ray.io/en/latest/cluster/config.html#node-types):

```
<node_type_1_name>:
    node_config:
        Node config
    resources:
        Resources
    min_workers: int
    max_workers: int
    worker_setup_commands:
        - str
    docker:
        Node Docker
<node_type_2_name>:
    ...
...
```

### Use case

For example, to pass different values to `--object-store-memory` based on the total RAM in the machine in the node.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
@melonipoika 

Was the intention to be able to set custom object store size?
If so, it may be better to support setting object store size in the Resources field of the config, rather than `ray start` commands.

**Comment by melonipoika** [comment]
Thanks @DmitriGekhtman

Yes, it is the custom object store size that we need to customize per worker type. I didn't noticed this can be set in the Resources field. Will do that!

**Comment by MaxVanDijck** [comment]
I came across the same issue but the comment above didn't tell me where I needed to specify the resources very well, it's in the yaml file for the cluster configuration under so here it is incase anyone else comes across it
```yaml
available_node_types:
    ray.head.default:
        resources:
            object_store_memory: 130000000000
```
