### ISSUE TITLE
[runtime env] [Bug] Deflake `test_runtime_env_remote_uri`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#23570]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

From https://flaky-tests.ray.io/
<img width="1630" alt="Screen Shot 2022-03-29 at 11 43 50 AM" src="https://user-images.githubusercontent.com/5459654/160682812-e7f4aafa-574b-46a8-b4c3-22253e7983bb.png">
<img width="1621" alt="Screen Shot 2022-03-29 at 11 44 00 AM" src="https://user-images.githubusercontent.com/5459654/160682842-b4850048-6a5a-4dc3-b7bf-058ddedfce27.png">
The goal should be 99% green.

### Versions / Dependencies

n/a

### Reproduction script

`pytest python/ray/tests/test_runtime_env_remote_uri.py`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by richardliaw** [comment]
No longer an issue.
