### ISSUE TITLE
[Shuffle] Reduce ObjectRef memory usage

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#23604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

From the results of past instrumentation on drivers during shuffle, ObjectRef takes up most of the memory usage in the drivers, especially when using many partitions. We would like to look into ways to optimize this usage, ideally making ObjectRef memory usage to scale linearly with the number of workers used in the shuffle. Possible strategies:
1. Consolidate metadata of ObjectRefs returned from the same task.
2. Reduce per ObjectRef metadata overhead.

### Use case

Increase scalability of shuffle.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by stephanie-wang** [comment]
Closed by #23853.
