### ISSUE TITLE
[Bug]  Dask on Ray - Ray remote args not applied correctly for max_retries

### ISSUE THREAD

**Issue by atomic-init** [ray-project/ray#23625]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

**Bug**

With Dask on Ray, specifying `max_retries`  in `ray_remote_args` doesnt get applied correctly. It executes the default number of retries instead of the specified max_retries

**Expected Behavior**

Retry for the specified `max_retries` instead of the default number of retries

### Versions / Dependencies

Ray version : 1.11.0 
Dask version: 2021.11.2

### Reproduction script

**Repro**

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"a": [1] * 100, "b": [2] * 100})
ddf = dd.from_pandas(df, npartitions=1)

with dask.config.set(
    scheduler=ray_dask_get, dataframe_optimize=dataframe_optimize,
):

    def sleep(df: pd.DataFrame):
        time.sleep(1000)
        return df

    ddf = ddf.map_partitions(sleep, meta=ddf)
    result = ddf.compute(ray_remote_args={"max_retries": 1})
```

Kill the dask worker and observe that the number of retries is different than the specified max_retries
```
nobody@ray-worker$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
nobody     312   216 15 00:28 pts/0    00:00:03 ray::dask:('sleep-2ccb94005463f4ee785712e7e884417c', 0)
nobody     386   377  0 00:29 pts/1    00:00:00 ps -ef
nobody@ray-worker$ kill -9 312
nobody@ray-worker$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
nobody     311   216 11 00:28 pts/0    00:00:03 ray::dask:('sleep-2ccb94005463f4ee785712e7e884417c', 0)
nobody     388   377  0 00:29 pts/1    00:00:00 ps -ef
nobody@ray-worker$ kill -9 311
nobody@ray-worker$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
nobody     393   216 48 00:29 pts/0    00:00:03 ray::dask:('sleep-2ccb94005463f4ee785712e7e884417c', 0)
nobody     460   377  0 00:29 pts/1    00:00:00 ps -ef
nobody@ray-worker$ kill -9 393
nobody@ray-worker$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
nobody     392   216  6 00:29 pts/0    00:00:03 ray::dask:('sleep-2ccb94005463f4ee785712e7e884417c', 0)
nobody     464   377  0 00:30 pts/1    00:00:00 ps -ef
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
I think I can look into this.

**Comment by pcmoritz** [comment]
That would be great :)

**Comment by czgdp1807** [comment]
I am unable to reproduce the scenario in the OP. What I am doing is running the following example by launching, `python dask_error.py` in first Anaconda prompt on Windows and then running `ps -ef` repeatedly in another Anaconda prompt on Windows. I always get the following line `ps -ef` output,

```
(ray_dev) C:\Users\gagan>ps -ef
     UID     PID    PPID  TTY        STIME COMMAND
   gagan    2688       1 cons0    07:42:26 /usr/bin/ps
```

I tried running `python dask_error.py &` (appended an `&`) but it doesn't run in the background. 

My example,

```python
import pandas as pd
from ray.util.dask import ray_dask_get, dask
from ray.util.dask.optimizations import dataframe_optimize
import time

dd = dask.dataframe

df = pd.DataFrame({"a": [1] * 100, "b": [2] * 100})
ddf = dd.from_pandas(df, npartitions=1)

with dask.config.set(
    scheduler=ray_dask_get, dataframe_optimize=dataframe_optimize,
):

    def sleep(df: pd.DataFrame):
        time.sleep(1000)
        return df

    ddf = ddf.map_partitions(sleep, meta=ddf)
    result = ddf.compute(ray_remote_args={"max_retries": 1})
```

**Comment by mattip** [comment]
I don't think the original reproducer was running on windows
