### ISSUE TITLE
[Bug] GPU Process not killed if jobs are cancelled from client.

### ISSUE THREAD

**Issue by tianlinzx** [ray-project/ray#23638]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

I have two GPUs installed on the same server.
If I cancelled two jobs from client, the server won't kill the gpu process.
Then when I submit my job to server the 3rd time, the server will respond ,not enough GPU node to be assigned.

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   1165899      C                                    1133MiB |
|    1   N/A  N/A   1168217      C                                    1133MiB |
+-----------------------------------------------------------------------------+

### Versions / Dependencies

Ray-1.11.0.

### Reproduction script

not related to Reproduction script, just a scenario.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwjiang2010** [comment]
When you say "job", are you using ray job submission API?

It would be great if you can share some repro scripts, just the minimal would give me something to look at and clarify some of these confusions.

**Comment by tianlinzx** [comment]
@xwjiang2010 This issue can be closed. It never appears again after upgrading to 1.12.0. Thanks very much.
