### ISSUE TITLE
[Bug] ModuleNotFound: No module named `ray.tests` when executing `rllib`'s `conftest.py`  

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#23637]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

# What happened
I wanted to execute some tests in reagrd to code changes I did. Running `rllib/models/tests/test_distributions.py` ran like a charme (even though it needs `torch` and `tfp` installed). 

Then I wanted to run also regression tests and executed `rllib/tests/conftest_py` I got then the following error: 

```
ImportError while loading conftest '/home/simon/git-projects/ray/rllib/tests/conftest.py'.
rllib/tests/conftest.py:1: in <module>
    from ray.tests.conftest import ray_start_regular_shared  # noqa: F401
E   ModuleNotFoundError: No module named 'ray.tests'
```

# What ypu expected to happen
That the tests are executable and internal modules exist. 

### Versions / Dependencies

Linux Fedora 35
Python 3.9.0
ray 1.11.0

### Reproduction script

```
pytest -v -s rllib/tests/conftest.py
```

### Anything else

It would help, if we could describe in the docs under contributing to RLlib how to run the basic tests for RLlib. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
hey I tried this on latest master, and it seems to work fine.
I am going to close this for now.

**Comment by simonsays1980** [comment]
@gjoliver @avnishn Still have it after an `git pull upstream master`: 

```
python -m pytest -v -s rllib/tests/test_supported_spaces.py 
ImportError while loading conftest '/home/simon/git-projects/ray/rllib/tests/conftest.py'.
rllib/tests/conftest.py:1: in <module>
    from ray.tests.conftest import ray_start_regular_shared  # noqa: F401
E   ModuleNotFoundError: No module named 'ray.tests'
```

**Comment by gjoliver** [comment]
can you let me know how you set up your environment, and where are you running this command from?

**Comment by GHUserNameLL** [comment]
hi @gjoliver , did you solve the issue? Same problems here.

**Comment by simonsays1980** [comment]
@GHUserNameLL on which system are you installing. For Linux I have created an [installation help](https://discuss.ray.io/t/rllib-installation-help/5577/7?u=lars_simon_zehnder) in the forum and even an [installation shell script](https://github.com/simonsays1980/ray-installation-help/blob/main/virtual_env_install.sh). 

Usually, if you have this error popping up you need to make a clean reinstall. Often the nightly has changed somewhere and needs to be reinstalled. Also, do not forget to run the `setup-dev.py`.
