### ISSUE TITLE
[Feature] MuZero Algorithm 

### ISSUE THREAD

**Issue by PeterPirog** [ray-project/ray#23635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

Are there any plans to implement MuZero algorithm in ray?
[MuZero paper](https://arxiv.org/pdf/1911.08265.pdf)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by czgdp1807** [comment]
MuZero seems like a popular paper (on Google search I see 753 citations). It would be good to have an implementation of this in ray (if in scope of the project). What do you think? @pcmoritz
