### ISSUE TITLE
[Dataset][Bug]: ray.data.read_text severely underperforming as compared to ray tasks and python multiprocessing

### ISSUE THREAD

**Issue by siddgoel** [ray-project/ray#23663]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

I analyzed and profiled ray dataset performance and compared it with ray tasks and python multiprocessing and found the following:
While ray datasets took 206 seconds to read and count 10 text files, python multiprocessing took 5 seconds and ray tasks took 7 seconds.
This indicated  a possible performance loophole in ray datasets. To further investigate the matter, I profiled the ray dataset code using CProfile and found that approximately 55% of the time was being consumed by the [wait](https://github.com/ray-project/ray/blob/6d83a3f2832fc24f63af1c1270afdd4850d701db/python/ray/data/impl/progress_bar.py#L74) section of the [fetch_until_complete](https://github.com/ray-project/ray/blob/6d83a3f2832fc24f63af1c1270afdd4850d701db/python/ray/data/impl/progress_bar.py#L69) method, about 40% time was being consumed by ray.init() and ray imports and 5% was taken by ray.shutdown().

### Versions / Dependencies

ray: version 2.0.0.dev0
python: 3.7
os: MacOS Big Sur version 11.6

### Reproduction script

```
import ray
ray.init() 

input_path = "/input/directory/path/"
ds = ray.data.read_text(path_uncomp)
print(ds.count())

ray.shutdown()
```

Code used for python multiprocessing:

```
from io import BytesIO
from multiprocessing import Pool
from os import walk
import snappy

dir_path = "/input/path/"

def process_file(file_name):
    from pyarrow import fs
    local = fs.LocalFileSystem()
    with local.open_input_stream(dir_path + file_name, compression=None) as stream:
        read_bytes = BytesIO()
        snappy.stream_decompress(src=stream, dst=read_bytes)
    read_bytes.seek(0)
    print("Successfully decompressed: " + file_name)
    with open(dir_path + file_name + "dec", 'wb') as f:
        f.write(read_bytes.getbuffer())


if __name__ == '__main__':
    filenames = next(walk(dir_path), (None, None, []))[2]
    p = Pool(len(filenames))
    p.map(process_file, filenames)
```

Code for ray tasks:
```
from io import BytesIO
from multiprocessing import Pool
from os import walk
import snappy
import ray

ray.init()
dir_path = "/input/path/"

@ray.remote
def process_file(file_name):
    from pyarrow import fs
    local = fs.LocalFileSystem()
    with local.open_input_stream(dir_path + file_name, compression=None) as stream:
        read_bytes = BytesIO()
        snappy.stream_decompress(src=stream, dst=read_bytes)
        ray.put(read_bytes)
    read_bytes.seek(0)
    print("Successfully decompressed: " + file_name)
    with open(dir_path + file_name + "dec", 'wb') as f:
        f.write(read_bytes.getbuffer())

filenames = next(walk(dir_path), (None, None, []))[2]
futures = [process_file.remote(name) for name in filenames]
print(ray.get(futures))
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by siddgoel** [comment]
@valiantljk @clarkzinzow

**Comment by valiantljk** [comment]
- does ray dataset triggers serialization/deserialization?
- does ray dataset use ray.put to store the data in python process into plasma?

**Comment by jianoaix** [comment]
What's the size of data used in the issue? Is that sharable in order to reproduce the exact issue?
The 40% of time on ray.init() seems huge overhead, which may be due to the data you used was quite small.

**Comment by siddgoel** [comment]
> s

The file size here was approx 850MB and I used 3 such files. I don't think the files will be shareable but any random text file should work.

**Comment by siddgoel** [comment]
> 

The file size here was approx 850MB and I used 3 such files. I don't think the files will be shareable but any random text file should work.

**Comment by jianoaix** [comment]
I cannot reproduce it. What I did was to:
- take the 2MB file from this page (https://www.learningcontainer.com/sample-text-file/)
- repeat this file until it's 1GB
- make 5 copies of this 1GB file
- and then run your first script
It took just 13seconds to complete.

**Comment by valiantljk** [comment]
@jianoaix could you share your script and have @siddgoel try it

**Comment by jianoaix** [comment]
Sure, note it's the same script provided by @siddgoel 

(raycp38) jian@Jians-MacBook-Pro-16 ray % time python ds.py
Map Progress:  60%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 3/5 [00:06<00:00,  2.52it/s](raylet) Spilled 3178 MiB, 6 objects, write throughput 2740 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
Map Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.58s/it]
num rows: 7293445
num blocks: 5
python ds.py  1.57s user 0.80s system 17% cpu 13.626 total

(raycp38) jian@Jians-MacBook-Pro-16 ray % cat ds.py
import ray
ray.init() 

input_path = "text1gbdir/"
ds = ray.data.read_text(input_path)
print("num rows:", ds.count())
print("num blocks:", ds.num_blocks())

ray.shutdown()

(raycp38) jian@Jians-MacBook-Pro-16 ray % cd text1gbdir 
(raycp38) jian@Jians-MacBook-Pro-16 text1gbdir % ls -la
total 10838720
drwxr-xr-x   7 jian  staff         224 Apr 18 17:02 .
drwxr-xr-x  54 jian  staff        1728 Apr 18 17:04 ..
-rw-r--r--   1 jian  staff  1109881344 Apr 18 17:01 512.txt
-rw-r--r--   1 jian  staff  1109881344 Apr 18 17:02 512.txt.2
-rw-r--r--   1 jian  staff  1109881344 Apr 18 17:02 512.txt.3
-rw-r--r--   1 jian  staff  1109881344 Apr 18 17:02 512.txt.4
-rw-r--r--   1 jian  staff  1109881344 Apr 18 17:02 512.txt.5

**Comment by siddgoel** [comment]
@jianoaix I ran the same script on my mac and the output was as follows:

import ray, time
ray.init()

input_path = "/testpath/"
ds = ray.data.read_text(input_path)
print(ds.count())

ray.shutdown()

(perf) ➜  sid git:(master) ✗ time python test_perf.py
Map Progress:  40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 2/5 [00:27<00:03,  1.09s/it](raylet) Spilled 2118 MiB, 4 objects, write throughput 628 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
Map Progress:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 4/5 [00:31<00:01,  1.63s/it](raylet) Spilled 4238 MiB, 8 objects, write throughput 938 MiB/s.
Map Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:33<00:00,  6.68s/it]
7293445
python test_perf.py  4.42s user 3.09s system 16% cpu 45.635 total

**Comment by siddgoel** [comment]
Moreover, when we add a timer to calculate the init and I/O times, the result is as follows:
(perf) ➜  sid git:(master) ✗ time python test_perf.py
Map Progress:  40%|██████████████████████████████████████████████████████████████████████████████████                                                                                                                           | 2/5 [00:26<00:03,  1.06s/it](raylet) Spilled 2118 MiB, 4 objects, write throughput 513 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
Map Progress:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 4/5 [00:30<00:01,  1.72s/it](raylet) Spilled 4238 MiB, 8 objects, write throughput 795 MiB/s.
Map Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:32<00:00,  6.54s/it]
7293445
Init time: 8.840641021728516
I/O time: 33.20051622390747
python test_perf.py  4.12s user 3.25s system 16% cpu 45.750 total


My ray status output is as follows and I can see that the data is being spilled. Is this the same for you as well @jianoaix

**Comment by jianoaix** [comment]
At the beginning of this thread, you mentioned 40% time on init(), but now it showed 8.8s (out of 45s), so even from your side, the issue seemed not reproduced. At least not any random file.

**Comment by siddgoel** [comment]
The version I used while raising the issue was 2.0.0.dev0 whereas this time I used 1.12 as this was the one you used while testing. Moreover, I believe the discrepancy in ray performance is still there as it's still taking way more than 13s to process the files for me. @jianoaix

**Comment by jianoaix** [comment]
Did you try it on your internal data, or just some random data? I think we should nail that and make whatever issue reproducible. If you believe any random data can reproduce, can you create one and share it?

**Comment by siddgoel** [comment]
@jianoaix I tried it on the same data that you used. The exact same experiment with 5 files of 1GB each and the result is as mentioned above.

**Comment by jianoaix** [comment]
We'll add benchmark for `read_text()` API: https://github.com/ray-project/ray/issues/31002
If it's reproduced, we'll fix it.
