### ISSUE TITLE
[Bug] [AutoScaler] [Tune] DockerSyncer on local on-prem cluster will fail on error 'The field available_node_types is not supported for on-premise clusters'

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#23665]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Tune, Ray Clusters

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

Using DockerSyncer on local on-prem cluster when running ray.tune.run will run into error:

```
(run pid=690) 2022-04-01 19:54:17,771	PANIC config.py:23 -- The field available_node_types is not supported for on-premise clusters.
(run pid=690) 2022-04-01 19:54:17,771	ERROR syncer.py:261 -- Sync execution failed.
(run pid=690) Traceback (most recent call last):
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/syncer.py", line 257, in sync_down
(run pid=690)     self._remote_path, self._local_dir, exclude=exclude
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/integration/docker.py", line 141, in sync_down
(run pid=690)     use_internal_ip=True,
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/sdk/sdk.py", line 162, in rsync
(run pid=690)     should_bootstrap=should_bootstrap,
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 1195, in rsync
(run pid=690)     config = _bootstrap_config(config, no_config_cache=no_config_cache)
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 294, in _bootstrap_config
(run pid=690)     config = prepare_config(config)
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 213, in prepare_config
(run pid=690)     config = prepare_local(config)
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/local/config.py", line 23, in prepare_local
(run pid=690)     cli_logger.abort(err_msg)
(run pid=690)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py", line 604, in abort
(run pid=690)     raise exc_cls(msg)
(run pid=690) click.exceptions.ClickException: The field available_node_types is not supported for on-premise clusters.
```

I think the reason is:

`DockerSyncClient` will call `sync_down`, which will call `rsync` function in `autoscaler.sdk`, which will eventually call `prepare_local` inside `ray.autoscaler._private.local.config`. 

This guy has below lines:
```
    for field in "head_node", "worker_nodes", "available_node_types":
        if config.get(field):
            err_msg = unsupported_field_message.format(field)
            cli_logger.abort(err_msg)
```

Correct me if I'm wrong, but I think for docker local on-prem cluster, this is guaranteed to fail, b/c here, the config file is the bootstrapped `ray_bootstrap_config.yaml` in the docker container in the **head node** (not launcher), which *has* `available_node_types` field in there. 

Is there any quick fix or workaround for this? 

### Versions / Dependencies

Ray == '2.0.0.dev0'
Python == '3.7.7'

### Reproduction script

Below will yield above error for **local on-prem docker cluster**
```
from typing import Optional, Sequence, Callable, List

import ray
import logging

from ray import tune
from ray.tune import Callback
from ray.tune.syncer import Syncer
from ray.tune.trial import Trial


def objective(x, a, b):
    return a * (x ** 0.5) + b


if not ray.is_initialized():
    ray.init(address='ray://192.168.1.155:10001', ignore_reinit_error=True, logging_level=logging.DEBUG)

    
class Trainable(tune.Trainable):
    def setup(self, config):
        # config (dict): A dict of hyperparameters
        self.x = 0
        self.a = config["a"]
        self.b = config["b"]

    def step(self):  # This is called iteratively.
        score = objective(self.x, self.a, self.b)
        self.x += 1
        return {"score": score}

analysis = tune.run(
    Trainable,
    stop={"training_iteration": 20},
    config={
        "a": tune.grid_search(list(range(1, 11))),
        "b": tune.grid_search(list(range(1, 11))),
    }, 
    sync_config=tune.SyncConfig(syncer=DockerSyncer,)
)

print('best config: ', analysis.get_best_config(metric="score", mode="max"))
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Hi @mlguruz, as a workaround, once https://github.com/ray-project/ray/pull/23605 is merged you can use the RemoteTaskSyncer instead of the DockerSyncer.

As a (arguably ugly) workaround, you could create a valid bootstrap config:

```
with open(os.path.expanduser("~/ray_bootstrap_config.yaml"), "r") as fp:
    cluster_config = yaml.safe_load(fp)

cluster_config.pop("available_node_types", None)

with open(os.path.expanduser("/tmp/clean_config.yaml"), "w") as fp:
    yaml.safe_dump(cluster_config, fp)
```

And then use it in a custom docker syncer:

```
class OwnDockerSyncer(DockerSyncer):
    _cluster_config_file = "/tmp/clean_config.yaml"
```

(code untested)

**Comment by mlguruz** [comment]
> Hi @mlguruz, as a workaround, once https://github.com/ray-project/ray/pull/23605 is merged you can use the RemoteTaskSyncer instead of the DockerSyncer.
> 
> 
> 
> As another (arguably ugly) workaround, you could create a valid bootstrap config:
> 
> 
> 
> ```
> 
> with open(os.path.expanduser("~/ray_bootstrap_config.yaml"), "r") as fp:
> 
>     cluster_config = yaml.safe_load(fp)
> 
> 
> 
> cluster_config.pop("available_node_types", None)
> 
> 
> 
> with open(os.path.expanduser("/tmp/clean_config.yaml"), "w") as fp:
> 
>     yaml.safe_dump(cluster_config, fp)
> 
> ```
> 
> 
> 
> And then use it in a custom docker syncer:
> 
> 
> 
> ```
> 
> class OwnDockerSyncer(DockerSyncer):
> 
>     _cluster_config_file = "/tmp/clean_config.yaml"
> 
> ```
> 
> 
> 
> (code untested)

Thank you for the workaround and my apology for the late reply. 

Do we have any plan to add this fix in the next release?

**Comment by krfricke** [comment]
The change has been reflected in at least 1.13.0, possibly earlier. We do not use SSH based syncing anywhere anymore, and don't access internal autoscaler state. Thus this issue should not come up anymore (automatically).
