### ISSUE TITLE
[Bug] Ray does not support latest pytest module

### ISSUE THREAD

**Issue by Samreay** [ray-project/ray#23675]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

As part of the update to support python 3.10, we need to update pytest, as the current pinned version does not work with py310. Documenting this as an issue, and will start on a PR now.

### Versions / Dependencies

pytest

### Reproduction script

See comment history on https://github.com/ray-project/ray/pull/21221

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by acxz** [comment]
> Issue Severity

I would also like to point out that this is a bottleneck for upgrading to py310 @21221

**Comment by acxz** [comment]
@pcmoritz this has been incorrectly closed as the latest pytest version is 7.1.2
