### ISSUE TITLE
[Bug] No space left on device keeps occurring 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#23674]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

# What happened
I ran my experiment with 160 trials on GCP using the autoscaler syncing with GCS. After around 123 terminated trials the expriment errored out with an error: 

`No space left on device` 

I restarted a new cluster with way more disk space available and then ran `tune.run()` with `resume="AUTO"` using the GCS bucket path as `upload_dir`. The checkpoints were found and `tune` resumed training and errored out immediately with the same error: 

```
2022-04-03 15:02:39,426	INFO util.py:278 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 34.145.87.99
Shared connection to 34.145.87.99 closed.
Shared connection to 34.145.87.99 closed.
2022-04-03 15:02:51,795	INFO util.py:278 -- setting max workers for head node type to 0
Fetched IP: 34.145.87.99
Shared connection to 34.145.87.99 closed.

2022-04-03 06:03:03,038	INFO trial_runner.py:520 -- Downloading experiment checkpoint from gs://ray-results-18102021/MiniGrid-Experiments/MiniGrid-Empty-Random-6x6-v0/DQN
2022-04-03 06:03:17,735	WARNING trial_runner.py:604 -- Attempting to resume experiment from /home/ray/ray_results/DQN. This will ignore any new changes to the specification.
2022-04-03 06:03:22,751	INFO tune.py:554 -- TrialRunner resumed, ignoring new add_experiment but updating trial resources.
== Status ==
Current time: 2022-04-03 06:03:45 (running for 00:00:22.87)
Memory usage on this node: 2.9/31.4 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs, 0.0/18.55 GiB heap, 0.0/9.28 GiB objects (0.0/1.0 accelerator_type:K80)
Result logdir: /home/ray/ray_results/DQN
Number of trials: 160/160 (36 ERROR, 124 TERMINATED)
Number of errored trials: 7
+---------------------------+--------------+-------------------------------------------------------------------------------------------------------+
| Trial name                |   # failures | error file                                                                                            |
|---------------------------+--------------+-------------------------------------------------------------------------------------------------------|
| DQN_mini-grid_e7970_00130 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00130_fcnet_hiddens=64_16_2022-04-02_19-16-55/error.txt |
| DQN_mini-grid_e7970_00126 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00126_fcnet_hiddens=256_2022-04-02_18-36-22/error.txt   |
| DQN_mini-grid_e7970_00124 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00124_fcnet_hiddens=64_2022-04-02_18-27-33/error.txt    |
| DQN_mini-grid_e7970_00127 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00127_fcnet_hiddens=16_16_2022-04-02_18-38-21/error.txt |
| DQN_mini-grid_e7970_00129 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00129_fcnet_hiddens=32_32_2022-04-02_18-42-07/error.txt |
| DQN_mini-grid_e7970_00128 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00128_fcnet_hiddens=32_16_2022-04-02_18-41-05/error.txt |
| DQN_mini-grid_e7970_00125 |            1 | /home/ray/ray_results/DQN/DQN_mini-grid_e7970_00125_fcnet_hiddens=128_2022-04-02_18-29-17/error.txt   |
+---------------------------+--------------+-------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "/home/ray/test_env.py", line 173, in <module>
    resume="REMOTE",
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 633, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [DQN_mini-grid_e7970_00130, DQN_mini-grid_e7970_00126, DQN_mini-grid_e7970_00124, DQN_mini-grid_e7970_00127, DQN_mini-grid_e7970_00129, DQN_mini-grid_e7970_00128, DQN_mini-grid_e7970_00125, DQN_mini-grid_e7970_00133, DQN_mini-grid_e7970_00136, DQN_mini-grid_e7970_00146, DQN_mini-grid_e7970_00145, DQN_mini-grid_e7970_00138, DQN_mini-grid_e7970_00149, DQN_mini-grid_e7970_00151, DQN_mini-grid_e7970_00140, DQN_mini-grid_e7970_00154, DQN_mini-grid_e7970_00134, DQN_mini-grid_e7970_00157, DQN_mini-grid_e7970_00144, DQN_mini-grid_e7970_00139, DQN_mini-grid_e7970_00150, DQN_mini-grid_e7970_00156, DQN_mini-grid_e7970_00135, DQN_mini-grid_e7970_00153, DQN_mini-grid_e7970_00152, DQN_mini-grid_e7970_00131, DQN_mini-grid_e7970_00148, DQN_mini-grid_e7970_00158, DQN_mini-grid_e7970_00143, DQN_mini-grid_e7970_00142, DQN_mini-grid_e7970_00137, DQN_mini-grid_e7970_00147, DQN_mini-grid_e7970_00155, DQN_mini-grid_e7970_00132, DQN_mini-grid_e7970_00159, DQN_mini-grid_e7970_00141])
Shared connection to 34.145.87.99 closed.
Error: Command failed:

  ssh -tt -i /home/simon/.ssh/ray-autoscaler_gcp_us-west1_forex-328615_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_b30bd35137/4315291b87/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.145.87.99 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_nvidia_docker /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python /home/ray/test_env.py)'"'"'"'"'"'"'"'"''"'"' )'
```
At first I checked the error files, but they were from the first error with `No space left on device`. I then removed the files from the GCS bucket and the downsynced `ray_results` folder. 

I then reran again my script and and it again errored out with the output above - pointing to the `error.txt` files, but these were not existent.

As a result I again started a new cluster and the same happened. I searched through the files for `"error.txt"` and found it in the `experiment_state` JSON files: 
```
\"Traceback (most recent call last):\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py\\\", line 1047, in _process_trial_save\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\\\", line 675, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py\\\", line 1763, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(OSError): \\u001b[36mray::DQNTrainer.save()\\u001b[39m (pid=4090, ip=10.138.15.224, repr=DQNTrainer)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py\\\", line 407, in save\\n    checkpoint_dir or self.logdir, index=self.iteration)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/trainable.py\\\", line 149, in make_checkpoint_dir\\n    os.makedirs(checkpoint_dir, exist_ok=True)\\n  File \\\"/home/ray/anaconda3/lib/python3.7/os.py\\\", line 223, in makedirs\\n    mkdir(name, mode)\\nOSError: [Errno 28] No space left on device: '/home/ray/ray_results/DQN/DQN_mini-grid_e7970_00127_fcnet_hiddens=16_16_2022-04-02_18-38-21/checkpoint_000050'
```
It appears to me that tune somehow does produce the new error by reading the old one from the last experiment state? 

I also tried to set `"TUNE_MAX_PENDING_TRIALS_PG": "1"` and/or `"TUNE_DISABLE_AUTO_CALLBACK_LOGGERS":"1"` as had been suggested in earlier issues on the discussion board regarding the `No space left on disk` error many months ago, but nothing changed. 

>This blocks me from finishing my experiment. And running a complete new one would take some time and money. Is there any chance that I can resume the experiment anymore? 

# What I expected to happen
That `tune` is able to pick up the last experiment state without picking up the error while the conditions (more disk space) have fully changed (I even started a cluster with 1 TB of disk space while the checkpoints so far had occupied 91GB). 

I am now a little afraid, when running more experiments that some errors occur, the experiments cannot be resumed and my time and money is gone without having a successfully terminated experiment with results. 

### Versions / Dependencies

Using the last docker image for GPU on GCP: 
Ubuntu 18.04.6 LTS (Bionic Beaver)
ray 1.11.0
Python 3.7.7

### Reproduction script

Probably not possible because it needs my checkpoints. Whenever someone of the developers wants to check it out, I am open for pair coding checking what is going on. 

### Anything else

I tried to understand what happens there in the source code, but could not find the lines where the `experiment_state` gets evaluated and errors get probably picked up. 

Thankful for a fingerpointing into the source code. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by krfricke** [comment]
Generally continuing an experiment will not continue failed trials and just report their failures. This behavior changes when passing `resume="ERRORED_ONLY"`, see here: https://github.com/ray-project/ray/blob/master/python/ray/tune/trial_runner.py#L376

The idea here is that continuing an experiment with `resume=True` should continue the experiment as if it was not interrupted. This includes printing out information about failed trials at the end (thus picking up the error messages). Let me know if this answers your question or if you'd need a way to both continue pending trials and reset errored trials in one run.

**Comment by krfricke** [comment]
I'm closing this via #26826 as it should be resolved - you can just instruct tune to resume the errored trials so they don't show up as errored anymore.

Let me know if this doesn't solve your problem.
