### ISSUE TITLE
[Bug][rllib] cannot be called with a default None policies_to_train parameter.

### ISSUE THREAD

**Issue by zhaozj89** [ray-project/ray#23687]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

[add_policy](https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L1851) cannot be called with a default None `policies_to_train` parameter. It will give the following errors:

    Traceback (most recent call last):
      File "self_play_with_open_spiel.py", line 218, in <module>
        results = trainer.train()
      File "/Users/zzhaoao/Documents/RL/code/ray/python/ray/tune/trainable.py", line 369, in train
        self.log_result(result)
      File "/Users/zzhaoao/Documents/RL/code/ray/python/ray/rllib/agents/trainer.py", line 1868, in log_result
        self.callbacks.on_train_result(trainer=self, result=result)
      File "self_play_with_open_spiel.py", line 145, in on_train_result
        new_policy = trainer.add_policy(
      File "/Users/zzhaoao/Documents/RL/code/ray/python/ray/rllib/agents/trainer.py", line 1720, in add_policy
        policies_to_train=list(policies_to_train),
    TypeError: 'NoneType' object is not iterable

### Versions / Dependencies

ray 1.11.0
python 3.8
macOS Monterey Version 12.3.1

### Reproduction script

https://github.com/ray-project/ray/blob/master/rllib/examples/self_play_with_open_spiel.py

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@avnishn  can you triage this?

**Comment by sven1977** [comment]
Hey @zhaozj89 , could you try this on the latest master?

I see that we might have already fixed this issue. The current line in trainer.py is:

```
    ...
    policies_to_train=list(policies_to_train) if policies_to_train else None,
    ...
```

**Comment by sven1977** [comment]
Nevertheless, we will add the self_play examples back into the CI-tests. They were never included due to a pip/version conflict between open-spiel and tensorflow/torch, which has been resolved:

https://github.com/ray-project/ray/pull/23742

**Comment by zhaozj89** [comment]
Thanks. I just tried out the self_play example with a pip installation, and think it may be helpful to contribute something. Sorry that I did not notice that it had already been fixed before I opened the issue. Thanks for the quick reply!
