### ISSUE TITLE
[Bug] [RLib] rlib type hardcoding issues

### ISSUE THREAD

**Issue by vinzm** [ray-project/ray#23689]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

In the normc_initializer in `rllib/models/tf/misc.py:12` as shown below

```
def normc_initializer(std: float = 1.0) -> Any:
    def _initializer(shape, dtype=None, partition_info=None):
        out = np.random.randn(*shape).astype(np.float32)
        out *= std / np.sqrt(np.square(out).sum(axis=0, keepdims=True))
        return tf.constant(out)

    return _initializer
```

the input `dtype` is ignored, risulting in a hard-coded np.float32 initialization, regardless of the required dtype.
It should just be used like the following:
```
def normc_initializer(std: float = 1.0) -> Any:
    def _initializer(shape, dtype=None, partition_info=None):
        out = np.random.randn(*shape).astype(dtype)
        out *= std / np.sqrt(np.square(out).sum(axis=0, keepdims=True))
        return tf.constant(out)

    return _initializer
```

### Versions / Dependencies

Python 3.6.8, 
Linux/Windows

### Reproduction script

pass

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Thanks @scv119 for filing this issue. Here is a PR that fixed the problem:
https://github.com/ray-project/ray/pull/23741

**Comment by vinzm** [comment]
Thanks @sven1977 and @scv119, however I think it should be safer to check that the provided argument `dtype` is not (the default value) `None`, before directly using it as the `astype` argument.

**Comment by vinzm** [comment]
something like:
```out = np.random.randn(*shape).astype(dtype if dtype is not None else np.float32)```
