### ISSUE TITLE
[Datasets] [Feature] ray.data.read_csv OOM Error in case of large CSVs

### ISSUE THREAD

**Issue by arshad171** [ray-project/ray#23681]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

High: It blocks me to complete my task.

### What happened + What you expected to happen

In case of large CSVs, `ray.data.read_csv` doesn't seem to be reading the CSV in chunks and blows up the RAM, on the contrary `pyarrow.csv.open_csv` in conjunction with read_next_batch logic consumes less that 500 MB of RAM.

I also tried passing `pyarrow.csv.ReadOptions` to the `ray.data.read_csv` but it doesn't seem to help.

**ray.data.read_csv should be able to read csv in chunks (without OOM Error) similar to pyarrow**

### Versions / Dependencies

ray==1.11.0
pyarrow ==7.0.0

### Reproduction script

```python
import string
import sys

import numpy as np
import pandas as pd
import pyarrow
import ray
from pyarrow import csv

CSV_PATH = './test.csv'
NUM_ROWS = 5_000
BLOCK_SIZE = 1_000


CHARSET = [c for c in string.ascii_letters]


def create_sample_csv(num_rows):
    """
    creates a sample csv of size 5 GB
    1 kb per row x 1,000 x 5,000 rows = 5 GB
    """

    for i in range(num_rows):
        print(f'{i}/{num_rows}')

        text = [''.join(np.random.choice(
            CHARSET, size=1024 ** 1, replace=True)) for _ in range(BLOCK_SIZE)]
        row = {'text': text}
        df = pd.DataFrame(row)

        if i == 0:
            df.to_csv(CSV_PATH, index=False)
        else:
            df.to_csv(CSV_PATH, index=False, header=False, mode='a')


def read_csv_using_ray(csv_path):
    """
    read the csv using ray (ray.data.read_csv) wrappers
    consumes too much RAM, blows up (OOM error)
    """
    pipe = ray.data.read_csv(
        csv_path,
        # read_options=pyarrow.csv.ReadOptions(block_size=4 * 1024)
    ).window()

    count = 0
    for row in pipe.iter_rows():
        count += 1
        print(count)

    print(count)


def read_csv_using_pyarrow(csv_path):
    """
    read the csv using pyarrow directly
    reads in batches, consumes less than 500 MB of RAM
    """
    reader = csv.open_csv(csv_path)
    count = 0
    while True:
        try:
            batch = reader.read_next_batch()
            table = pyarrow.Table.from_batches([batch])
            count += len(table['text'])
        except StopIteration:
            print('stop')
            break

    print(count)


if __name__ == '__main__':
    cmd = sys.argv[1]
    if cmd == 'create_csv':
        create_sample_csv(num_rows=NUM_ROWS)
    elif cmd == 'read_using_ray':
        read_csv_using_ray(csv_path=CSV_PATH)
    elif cmd == 'read_using_pyarrow':
        read_csv_using_pyarrow(csv_path=CSV_PATH)
    else:
        print('invalid cmd. supported: create_csv, read_using_ray, read_using_pyarrow')

```

## Running the Script:

python script.py *[create_csv | read_using_ray | read_using_pyarrow]* 

- create_csv: creates a dummy 5 GB csv. path: `./test.csv`
- read_using_ray: reads the csv using `ray.data.read_csv`
- read_using_pyarrow: reads the csv using pyarrow functions

### Anything else

Able to reproduce it consistently

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by arshad171** [comment]
did some digging, this line is causing the problem: https://github.com/ray-project/ray/blob/11baa22c1efeaa7069e380eb5891754fd5ef650b/python/ray/data/read_api.py#L301

The above line is trying to figure out the schema by reading the first block.

1. why is the entire file (5 GB CSV) read as a single block. 
2. Is it possible to pass the schema if already known?

**Comment by arshad171** [comment]
@valiantljk @clarkzinzow any thoughts?

**Comment by arshad171** [comment]
> @arshad171 Although Datasets performs streaming reads on most file formats (including CSV files) and does support splitting a file into multiple blocks automatically if the DatasetContext.block_splitting_enabled config flag is set, it currently doesn't split files into multiple blocks by default, and even if that config flag is set, we don't yet support streaming those blocks through the (in-memory) object store.

> What I mean by that last bit is although the streaming reads will keep your Python worker heap utilization low, the read task doesn't return until all objects are put into the object store, so you wouldn't be able to start processing the data in that file until all 5 GB has been stored in the object store.


yes, I could observe that pyarrow reads the csv in chunks, but the entire csv is read before it can be processed.

Since this logic was to determine the schema, I thought defining the schema before hand would circumvent the entire csv
https://github.com/ray-project/ray/blob/11baa22c1efeaa7069e380eb5891754fd5ef650b/python/ray/data/read_api.py#L301

I could define the schema and see it getting reflected, but sadly the entire csv is read (as mentioned above).

Is there a way to work around this?

Or should I write my own logic to read csv is chunks and let ray process it by defining a simple remote function?

**Comment by chaos-ad** [comment]
Hey guys, i've stumbled upon the similar problem while reading ~15GB parquet file. And pyarrow.dataset.dataset(...).to_batches() however works like a charm. I guess the similar problem might arise when someone wants to store & process more than a few TB of data in HDFS, since it is generally advisable not to have >10k files
