### ISSUE TITLE
[Bug] Documentation rendering incorrectly for several of Ray's APIs.

### ISSUE THREAD

**Issue by dynamicwebpaige** [ray-project/ray#23704]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Others

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

<img width="783" alt="Screen Shot 2022-04-04 at 2 55 57 PM" src="https://user-images.githubusercontent.com/3712347/161638880-244bb27a-cdf5-43af-b656-e15a22ee9906.png">

The API documentation on [ray.io](ray.io) is frustratingly rendered (likely due to behavior in Sphinx). You can see irregularities in the screenshot above; for example: `str = '5241590000000000'` as well as `'%(asctime)s\t%(levelname)s %(filename)s:%(lineno)s -- %(message)s'`.

### Versions / Dependencies

N/A

### Reproduction script

Reference URL for the image above: [https://docs.ray.io/en/latest/ray-core/package-ref.html](https://docs.ray.io/en/latest/ray-core/package-ref.html)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pcmoritz** [comment]
As a start, let's remove all the arguments starting with an underscore from the documentation!

**Comment by pcmoritz** [comment]
@maxpumperla Do you want to look into that?
