### ISSUE TITLE
[Core] [Docs] Contributing documentation guide does not provide correct instructions

### ISSUE THREAD

**Issue by Samreay** [ray-project/ray#23711]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

While trying to contribute a PR (https://github.com/ray-project/ray/pull/23676) so we can get Python 3.10 supported, I went to the contribution documentation here: https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#testing

The instructions were very simple - install the requirements, and then you can run individual tests through pytest like the example provided.

However, the example provided does not run, and there's obviously some environment variables, pathing or something similar missing from the instructions that makes it difficult for newcomers to get up and running when trying to contribute to the project. It would be great if this documentation could be updated to include some more detail.

### Versions / Dependencies

Run from the master branch

### Reproduction script

1. Clone out ray
2. run `pip install -r python/requirements.txt`
3. Run `pytest -v -s python/ray/tests/test_basic.py`
4. Get a `ModuleNotFoundError`

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6748505/161714913-a87bd2aa-4dec-46b7-ace7-52011732769a.png">

This issue might be caused by needing the compiled cython (as even if I add the cloned out ray/python directory to my pythonpath it still then fails to run but this time when trying to import a pyx file), however Im also unable to follow the instructions for building only with python that are found here: https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-python-only

Wherein I cannot run the desired python file. All the steps run fine until we get to running the python file, as shown below. Interesntly, it seems to be failing with the same issue as unable to find the compiled cython file

```shell
(ray) sh@ARENKO-024 ray % pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-macosx_10_15_x86_64.whl
...
Installing collected packages: ray
Successfully installed ray-2.0.0.dev0
(ray) sh@ARENKO-024 ray % python python/ray/setup-dev.py
<frozen importlib._bootstrap>:219: RuntimeWarning: compiletime version 3.7 of module 'ray._raylet' does not match runtime version 3.8
<frozen importlib._bootstrap>:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 864 from C header, got 880 from PyObject
Traceback (most recent call last):
  File "python/ray/setup-dev.py", line 12, in <module>
    import ray
  File "/Users/sh/Projects/ray/python/ray/__init__.py", line 108, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 16, in init ray._raylet
    import setproctitle
ModuleNotFoundError: No module named 'setproctitle'
```

### Anything else

Apologies if I've just made some stupid mistake along the way, but would definitely appreciate any pointers if so, or updates to the documentation if not. Happy to submit a PR for the documentation too, but obviously would require figuring out what is going wrong first.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by dynamicwebpaige** [comment]
Is maintaining the contribution guide something that our developer advocacy team might be able to help with? cc: @richardliaw

**Comment by richardliaw** [comment]
Definitely so!
