### ISSUE TITLE
Expose ray.worker.cleanup?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2372]
### Describe the problem
`ray.worker.cleanup` is used in testing by quite a few parties now (including ourselves) - it would be good to document this properly and expose this.

**Comment by robertnishihara** [comment]
I'm working on this at the moment.

**Comment by richardliaw** [comment]
Great (this issue was just opened to track, as these things sometimes are forgotten...)

**Comment by RuofanKong** [comment]
I wonder if this feature is the same one as in #1814.
