### ISSUE TITLE
[Workflow][flaky-test] linux://python/ray/workflow:tests/test_virtual_actor_2  is flaky 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23760]
### What happened + What you expected to happen

python/ray/workflow/tests/test_virtual_actor_2.py is flaky on master. After initial investigation it's not clear what's the root cause. @iycheng @suquark can you help with this? 

### Versions / Dependencies

master

### Reproduction script

`pytest python/ray/workflow/tests/test_virtual_actor_2.py`

**Comment by architkulkarni** [comment]
If during this investigation it's determined that this is not a blocker for the 1.11.1 release, please let me know and I can proceed with the release.  (Currently cherry-pick PRs are failing CI because of this test)

**Comment by suquark** [comment]
NOTE: The flaky test is `test_wf_in_actor_seq_3`
