### ISSUE TITLE
[Bug] Ray Serve deployments doesn't work with custom dependencies. ray==1.11.0

### ISSUE THREAD

**Issue by mkotsalainen** [ray-project/ray#23772]
### What happened + What you expected to happen

I've recently installed Ray on an AWS EKS K8s cluster via the chart in https://github.com/ray-project/ray/tree/master/deploy/charts/ray

I'm trying to create Ray Serve deployments with custom pip dependencies from the documentation example here:
https://docs.ray.io/en/latest/serve/core-apis.html#handling-dependencies This fails. I can create deployments without custom pip environments.
```
import ray
from ray import serve
ray.init("ray://xxxxxxxxxxxxxx", namespace="serve")
serve.start(detached=True, http_options={"host": "0.0.0.0"})

@serve.deployment
def package_test(request):
    import pkg_resources
    installed_packages = {d.project_name: d.version for d in pkg_resources.working_set}
    return installed_packages

# This works
package_test.options(name="no-pip", ray_actor_options={}).deploy()

# This doesn't work
package_test.options(
    name="extra-packages",
    ray_actor_options={
        "runtime_env": {
            "pip": ["ray[serve]", "pip-install-test"]
        }
    }).deploy()

print(serve.list_deployments())
```

I get this error in the console when I run this program:

```
Caught schedule exception
2022-04-07 11:02:44,788	INFO cloudpickle.py:802 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
(ServeController pid=353) 2022-04-07 03:02:45,331	INFO checkpoint_path.py:16 -- Using RayInternalKVStore for controller checkpoint and recovery.
(ServeController pid=353) 2022-04-07 03:02:45,455	INFO http_state.py:101 -- Starting HTTP proxy with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:172.21.173.240-0' on node 'node:172.21.173.240-0' listening on '0.0.0.0:8000'
(HTTPProxyActor pid=412) INFO:     Started server process [412]
2022-04-07 11:02:47,702	INFO api.py:521 -- Started detached Serve instance in namespace 'serve'.
2022-04-07 11:02:47,923	INFO api.py:262 -- Updating deployment 'no-pip'. component=serve deployment=no-pip
(ServeController pid=353) 2022-04-07 03:02:47,931	INFO deployment_state.py:920 -- Adding 1 replicas to deployment 'no-pip'. component=serve deployment=no-pip
2022-04-07 11:02:48,084	INFO api.py:275 -- Deployment 'no-pip' is ready at `http://0.0.0.0:8000/no-pip`. component=serve deployment=no-pip
2022-04-07 11:02:48,302	INFO api.py:262 -- Updating deployment 'extra-packages'. component=serve deployment=extra-packages
(ServeController pid=353) 2022-04-07 03:02:48,374	INFO deployment_state.py:920 -- Adding 1 replicas to deployment 'extra-packages'. component=serve deployment=extra-packages
(ServeController pid=353) 2022-04-07 03:02:48,382	INFO deployment_state.py:1189 -- Deployment 'extra-packages' failed, deleting it. component=serve deployment=extra-packages
2022-04-07 11:02:48,464	INFO api.py:275 -- Deployment 'extra-packages' is ready at `http://0.0.0.0:8000/extra-packages`. component=serve deployment=extra-packages
{'no-pip': Deployment(name=no-pip,version=None,route_prefix=/no-pip)}
```

The extra-packages route is there (I see that by hitting the /-/routes endpoint) but when I try to access it I get a timeout.

Any tips on how I can debug this? I've checked logs for ray and workers but there is nothing there.

### Versions / Dependencies

ray==1.11.0 on my local machine
helm chart from ray-repo commit 46465abd6d866c3903b17c601e84e81b46c67190
eks k8s 1.20
The helm chart uses rayproject/ray:latest tag which in my case is docker.io/rayproject/ray@sha256:029ec7b7b9e59d49b6ea3a66b2813c3c07407239e0f5991064aa561829ec69a9

### Reproduction script

import ray

from ray import serve

ray.init("xxxxxxxxxxxxxxxxx", namespace="serve")

serve.start(detached=True, http_options={"host": "0.0.0.0"})

@serve.deployment
def package_test(request):
    import pkg_resources
    installed_packages = {d.project_name: d.version for d in pkg_resources.working_set}
    return installed_packages

# This works
package_test.options(name="no-pip", ray_actor_options={}).deploy()

# This doesn't
package_test.options(
    name="extra-packages",
    ray_actor_options={
        "runtime_env": {
            "pip": ["ray[serve]", "pip-install-test"]
        }
    }).deploy()

print(serve.list_deployments())

**Comment by mkotsalainen** [comment]
An update to this. I'm able to install custom packages via ray.init method like so:
```
ray.init("ray://xxxxxxxxxxx", namespace="serve", runtime_env={"pip": ["pip-test"]})
```
and then they are available to serve endpoints. However I want different packages for different endpoints. That's why I want to add them via ray_actor_options to ray serve deployments.

Also, I'm able to add packages to ray workers like so:

```
@ray.remote(runtime_env={"pip": ["pip-test"]})
def test():
    import pkg_resources
    installed_packages = {d.project_name: d.version for d in pkg_resources.working_set}
    return installed_packages
```

**Comment by architkulkarni** [comment]
Hi @mkotsalainen, thanks for the detailed reproduction and sorry you're running into this.  Are there any relevant logs in the head node?  By default these are at `/tmp/ray/session_latest/logs` on the head node, and relevant files to look at are `dashboard_agent.py` and `runtime_env_setup*`.  Also, are you able to reproduce this on a single local machine (e.g. by running `ray start --head`, and then using `ray://localhost:10001` as the address?)

**Comment by architkulkarni** [comment]
Running locally on the master branch, I did reproduce the message 
```
Caught schedule exception
2022-04-07 10:01:58,455 INFO common.py:219 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
```
but both endpoints are working as expected.  Can you see if the endpoints work for you when using the [Ray nightly wheels?](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies)

**Comment by architkulkarni** [comment]
@ckw017 do you happen to know how to debug the message `Caught schedule exception`?  Do you know if we could find the full exception somewhere in the logs, and where that might be?

**Comment by ckw017** [comment]
> @ckw017 do you happen to know how to debug the message `Caught schedule exception`? Do you know if we could find the full exception somewhere in the logs, and where that might be?

Traceback for the exception would usually be right after the "Caught schedule exception" message. The exception should also propagate to the client side and be raised by the call to schedule (call to .remote())

**Comment by architkulkarni** [comment]
Interesting, there isn't any further traceback...  Maybe it's being swallowed by Ray Serve somehow

**Comment by mkotsalainen** [comment]
Thanks for your input guys! 👍

I'm happy to report that installing Ray nightly wheel on drive machines and using rayproject/ray:nightly image for helm values allows me to install custom packages in Ray deployments. Closing this issue.
