### ISSUE TITLE
Why sync_parameter_server use set_flat but async_parameter_server not

### ISSUE THREAD

**Issue by cklsoft** [ray-project/ray#2378]
### Describe the problem
In the provided parameter server examples, why sync_parameter_server use set_flat but async_parameter_server not? 
And in what scenarios to use TensorFlowVariables.set_flat？

**Comment by luochao1024** [comment]
I also write a set_flat/get_flat version for async_parameter_server and I found set_flat/get_flat version is faster than the original one
