### ISSUE TITLE
add support for ppc64le in linux

### ISSUE THREAD

**Issue by luochao1024** [ray-project/ray#2379]
It seems like that ray only supports x86_64.  Is it possible to add wheels for ppc64le in Linux?

**Comment by robertnishihara** [comment]
Some questions
- Do you have a sense of what is involved with this?
- Is it just a matter of compiling on the relevant machine?
- Do you have examples of other projects that do this?

**Comment by luochao1024** [comment]
I switch to ubuntu now so I don't need it anymore. For example, if I want to install tensorflow in a `ppc64le server` and just use` pip install tensorflow`, it will raise an error saying something like no specific version found. But I can install the right version by following this page via conda https://anaconda.org/anaconda/tensorflow, which supports linux-ppc64le. 

Another example is about installing anaconda from this page https://www.anaconda.com/download/#linux. I need to download this installer `64-Bit (Power8 and Power9) Installer (288 MB)` instead of this one `64-Bit (x86) Installer (622 MB)`.
