### ISSUE TITLE
[Core] [Bug] Possible memory leak

### ISSUE THREAD

**Issue by tianlinzx** [ray-project/ray#23797]
### What happened + What you expected to happen

There is no job running on the working node, but it still take extremely high usage of memory.
Is there a potential memory leakage ? Or is there any settings to be configured to avoid such issue ?
![WX20220408-134637](https://user-images.githubusercontent.com/1411754/162372784-8940d845-8993-4a90-8b6f-0e582fdcb1e8.png)

### Versions / Dependencies

Ray 1.11

### Reproduction script

No special scripts need to be provided.

**Comment by clarkzinzow** [comment]
Hey @tianlinzx, thanks for opening an issue!

Do you have a minimal reproduction that demonstrates this?

**Comment by rkooo567** [comment]
Also, @tianlinzx is it possible to show us memory usage of that node? (like from htop command)

**Comment by rkooo567** [comment]
There's very high likelihood it is from dashboard.py process (which there's other open issue)

**Comment by tianlinzx** [comment]
The memory ussage is still increasing.
![20220411161408](https://user-images.githubusercontent.com/1411754/162693997-20848847-e67a-4d5d-9cce-1859b2ee3021.png)

**Comment by tianlinzx** [comment]
@rkooo567 Hi SangBin, here is the htop file .
![微信图片_20220418080007](https://user-images.githubusercontent.com/1411754/163737030-8c52b2c7-6664-452d-b15c-92d3c6e9eea9.png)

**Comment by rkooo567** [comment]
Hmm sorry. but the dashboard and your htop output doesn't match? Dashboard says each of your node has 32GB memory, but htop says it is 256GB

**Comment by tianlinzx** [comment]
![WX20220418-134909](https://user-images.githubusercontent.com/1411754/163761354-8928f4c7-4e26-4e14-a0f4-5aab67984d1c.png)
Here is the lastest daskboad screen.
