### ISSUE TITLE
Ray Core 1.11.0: socket.gaierror

### ISSUE THREAD

**Issue by cbravo93** [ray-project/ray#23799]
### What happened + What you expected to happen

I get the following error message when using ray 1.11.0, it didn't occur with 1.10.0:

```
(raylet) Traceback (most recent call last):
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/dashboard/agent.py", line 391, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/dashboard/agent.py", line 178, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/dashboard/agent.py", line 120, in _load_modules
(raylet)     c = cls(self)
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 161, in __init__
(raylet)     self._metrics_agent = MetricsAgent(
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
(raylet)     prometheus_exporter.new_stats_exporter(
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
(raylet)     exporter = PrometheusStatsExporter(
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 265, in __init__
(raylet)     self.serve_http()
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
(raylet)     start_http_server(
(raylet)   File "/opt/venv/lib/python3.8/site-packages/prometheus_client/exposition.py", line 167, in start_wsgi_server
(raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet)   File "/opt/venv/lib/python3.8/site-packages/prometheus_client/exposition.py", line 156, in _get_best_family
(raylet)     infos = socket.getaddrinfo(address, port)
(raylet)   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
(raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known
(raylet) 
(raylet) During handling of the above exception, another exception occurred:
(raylet) 
(raylet) Traceback (most recent call last):
(raylet)   File "/opt/venv/lib/python3.8/site-packages/ray/dashboard/agent.py", line 407, in <module>
(raylet)     gcs_publisher = GcsPublisher(args.gcs_address)
(raylet) TypeError: __init__() takes 1 positional argument but 2 were given
```

My process continues running and I get output though.

### Versions / Dependencies

Singularity image with Python 3.8 in Linux.

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Reproduction script

Any time I start a process in ray.

**Comment by clarkzinzow** [comment]
@cbravo93 This is a recent break in an unpinned Ray dependency, namely `prometheus_client`, which recently released a new version that breaks our metrics exporter. You can fix this by installing the previous `prometheus_client` version: `pip install -U prometheus_client==0.13.1`.

This was [fixed](https://github.com/ray-project/ray/commit/d27e73f85171ca23ed74175a3cdba6e555c4d540) in Ray master yesterday, and will be included in the upcoming 1.12 release (released today) and patched onto 1.11 with the 1.11.1 patch release.

**Comment by cbravo93** [comment]
Thanks!

**Comment by Nithanaroy** [comment]
> @cbravo93 This is a recent break in an unpinned Ray dependency, namely `prometheus_client`, which recently released a new version that breaks our metrics exporter. You can fix this by installing the previous `prometheus_client` version: `pip install -U prometheus_client==0.13.1`.
> 
> This was [fixed](https://github.com/ray-project/ray/commit/d27e73f85171ca23ed74175a3cdba6e555c4d540) in Ray master yesterday, and will be included in the upcoming 1.12 release (released today) and patched onto 1.11 with the 1.11.1 patch release.

Thanks for the patch @clarkzinzow 
Any timeline on when 1.11.1 will be released? I dont see it in https://pypi.org/project/ray/#history

**Comment by Nithanaroy** [comment]
And any thoughts on how I can suppress this log message? I disabled the dashboard like so,
```python
import ray
ray.init(include_dashboard=False, num_gpus=0)
```
but still see it.

**Comment by clarkzinzow** [comment]
>Any timeline on when 1.11.1 will be released?

cc @architkulkarni who is managing the ongoing 1.11.1 release!

**Comment by architkulkarni** [comment]
1.11.1 will hopefully be released by mid-next week.
