### ISSUE TITLE
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by arisliang** [ray-project/ray#2380]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.0
- **Python version**: 3.6
- **Exact command to reproduce**:
Just define function using non-ascii name

### Describe the problem

Unable to define function using non-ascii name. Attempted to do so gives ascii encoding error, such as:
> 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
### Source code / logs

@ray.remote
 def 你好():
    time.sleep(1)
    return 1

**Comment by robertnishihara** [comment]
Thanks for reporting this, I can reproduce the issue in Python 3.

I think this is not allowed in Python 2.

**Comment by arisliang** [comment]
Understandable for Python 2, as long as it's allowed inPython 3, :p
