### ISSUE TITLE
[Tune] how to create a search space that can Simultaneously search  layer of nn and num of nn's units ？

### ISSUE THREAD

**Issue by 5huanghuai** [ray-project/ray#23819]
Now, I'm learning how to use ray tune to tune Hyperparameters. But I don't know how to write a code to  search layer number of neural network and units number of each neural network Simultaneously.

**Comment by amogkam** [comment]
Hey @5huanghuai have you checked out the Ray Tune getting started documentation (https://docs.ray.io/en/latest/tune/getting-started.html)? It should give a good overview on how to define a training function and define a Tune search space!

**Comment by clarkzinzow** [comment]
@5huanghuai Also, our [discussion forum](https://discuss.ray.io/) is a perfect place for questions such as this!
