### ISSUE TITLE
Unable to install ray in venv(pipenv) on Python3.7

### ISSUE THREAD

**Issue by Olamyy** [ray-project/ray#2381]
System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac os high sierra
- **Ray installed from (source or binary)**: Unable to install ray
- **Ray version**: Unable to install ray
- **Python version**: 3.7
- **Pipenv version**: 2018.7.1
- **Exact command to reproduce**: 
`pipenv --python 3.7`
`pipenv shell`
`pipenv install ray` or `pip install ray`

### Describe the problem
I'm unable to install ray using a pipenv running Python3.7. 
I keep getting a distribution not found error.

> Collecting ray
  Could not find a version that satisfies the requirement ray (from versions: )
No matching distribution found for ray

### Source code / logs
`Collecting ray`
 `Could not find a version that satisfies the requirement ray (from versions: )`
`No matching distribution found for ray`

**Comment by robertnishihara** [comment]
Thanks for reporting this! I'm going to close it since it is basically the same issue as #1115.

We basically just need to build wheels for Python 3.7 and upload them.
