### ISSUE TITLE
[Tune][Bug] `tune.ExperimentAnalysis.best_checkpoint` does not filter `nan` metric values

### ISSUE THREAD

**Issue by XuehaiPan** [ray-project/ray#23812]
### What happened + What you expected to happen

I'm using `tune.run` to train my RL policy and hope to get the best checkpoint weights for further analysis.

```python
experiment = tune.Experiment(
    run='PPO',
    name=...,
    config=...,
    checkpoint_score_attr='episode_reward_mean',
    checkpoint_freq=20,
    checkpoint_at_end=True,
    ...
)

ray.init()

analysis = tune.run(
    experiment,
    metric='episode_reward_mean',
    mode='max',
)

best_checkpoint = analysis.best_checkpoint
```

Because I have set `checkpoint_freq=20`, the trainer saves `checkpoint-20` with metric `episode_reward_mean = math.nan`. Despite further training processes (e.g. `checkpoint-1000` has valid metrics), `analysis.best_checkpoint` always gives the path to `checkpoint-20`.

I have located the issue is caused by `sorted` with `nan` values:

https://github.com/ray-project/ray/blob/9655851f32d68013734dd44321914b27ad8fe633/python/ray/tune/analysis/experiment_analysis.py#L454-L455

For examples:

```python
In [1]: sorted([1, 3, 2, float('nan'), 1, 3, 2])
Out[1]: [1, 1, 2, 2, 3, nan, 3]

In [2]: sorted([1, float('nan'), 1, 3, 2])
Out[2]: [1, nan, 1, 2, 3]

In [3]: sorted([float('nan'), 1, 3, 2])
Out[3]: [nan, 1, 2, 3]
```

### Versions / Dependencies

ray[rllib] == 1.11.0

### Reproduction script

```python
import ray
from ray import tune

experiment = tune.Experiment(
    run='PPO',
    name='TUNE-BUGREPORT',
    config={
        'env': 'CartPole-v1',
        'num_workers': 0
    },
    stop={'timesteps_total': 10000},
    checkpoint_score_attr='episode_reward_mean',
    checkpoint_freq=1,
    checkpoint_at_end=True,
)

ray.init()

analysis = tune.run(
    experiment,
    metric='episode_reward_mean',
    mode='max',
)

best_checkpoint = analysis.best_checkpoint
print(best_checkpoint)
```

**Comment by amogkam** [comment]
Hey @XuehaiPan thanks for raising this! You are right this is definitely a bug-- it will be resolved once #23820 is merged in!
