### ISSUE TITLE
[RLlib] Include 'info_dict' in offline data

### ISSUE THREAD

**Issue by jbedorf** [ray-project/ray#23826]
### What happened + What you expected to happen

When using the `output` configuration key to log data during training, the `infos_dict` as returned from the environment is not written/recorded in the output files. This due to the fact that the `infos_dict` is not included in the `SampleBatch` that is being used for the training process. 

After some searching I found that this behaviour can be changed by modifying [this line](https://github.com/ray-project/ray/blob/ray-1.11.0/rllib/policy/tf_policy.py#L192) from 'False' to 'True':
`self.view_requirements[SampleBatch.INFOS].used_for_training = False`

In general the `info_dict` is not required, but it can be useful when recording data for offline training and additional information should be logged from the environment. 

Maybe the user can be given an additional option to enable this behaviour via something like this:
```
if config["output_config"].get("log_infos_dict", False):
    self.view_requirements[SampleBatch.INFOS].used_for_training = True
```

If this sounds reasonable let me know and I'll create a PR.

Note, in a previous issue ([here](https://github.com/ray-project/ray/issues/13469)) it was indicated that the problem was fixed. 

### Versions / Dependencies

Ray 1.11 and newer.

### Reproduction script

Run this and inspect the resulting json files, it will show that the `infos_dict` is not included. 
`rllib train --run=SAC --env=CartPole-v0 --config='{"output" : "/tmp/" , "num_workers" : 0}' --stop='{"timesteps_total" : 1000}'`

**Comment by gjoliver** [comment]
oh sorry, I read your question wrong. you are trying to write the info dicts to the recorded JSON files, get it, I thought it was about ingestion :)
I have a question about serializing arbitrary data to JSON though, since info dict can contain everything, and some of them may not be JSON serializable.

**Comment by jbedorf** [comment]
Yep, that's the goal. 
That's a valid concern yes, so the default should be to not write anything (like now) and if the user wants to record the info dicts they are responsible for ensuring that the data in the info_dicts can be serialized. The assumption here is that the user is in control of the environment and as such can control what is logged.

**Comment by gjoliver** [comment]
yeah, I think that sounds totally reasonable.
do you want to send a PR :)

**Comment by jbedorf** [comment]
Ok great, yep I'll work this out and create a PR once all is in place 👍
