### ISSUE TITLE
[Core] Forward task lineage if custom owner is specified in ray.put

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#23824]
### Description

@stephanie-wang @ericl 

In order to make the objects fault tolerant, their lineage should be properly set. But when creating the ray dataset, due to the limit of various data sources, this is sometimes not easy. 

If we have an API like forward, which changes the lineage of the object to the current task without copy, we would be able to make more data sources fault-tolerant.

### Use case

Using raydp as an example:
We use ray.put in spark mapPartitions to implement ray.data.from_spark. It is very difficult to do the other way: read spark rdd partitions in ray tasks. Because spark sessions is not serializable. Therefore, a dataset created this way is not fault-tolerant.

With ray.forward, we can spawn ray tasks to forward such objects, so that the particular task is resubmitted when an object is lost. We just need to ensure if the task is resubmitted, the particular partition is ray.put again and returned.

**Comment by stephanie-wang** [comment]
Thanks for the info, @kira-lin! To clarify, would it work if we only allowed forwarding in cases where a worker calls `ray.put` then returns the ref? For example, would the following behavior work for your use case?

Currently, Ray provides this kind of behavior:
```
@ray.remote
def foo():
  x_ref = ray.put(x)
  return x_ref

x_ref = ray.get(foo.remote())  # x will be gone if foo's worker dies.
```

What if we changed it so that `foo`'s caller owns `x_ref` instead?

**Comment by kira-lin** [comment]
To clarify, our problem is not about ownership, but recovery. To solve the problem you mentioned, we have implemented `Ray.put(x, actor_handle)`.  The problem we want to solve here is, how to recover an object created by ray.put, when it get lost. The solution we come up with is assigning a task to it, as if it is created by that task, and when the task get resubmitted, it'll ray.put the data again.

If it helps, this our [protype](https://github.com/oap-project/raydp/pull/229). And please check the [get_spark_partition](https://github.com/oap-project/raydp/pull/229/files#diff-8d5a74e493eefd7e7a1908a383a5801d857587d51e5f05197afc8d84111315bcR38) function especially.

**Comment by stephanie-wang** [comment]
Ownership and recovery are tightly linked because normally the owner is the one who recovers the object. I believe that your use case can be met by the code snippet I posted above. Let me write a quick design doc for this this week and we can discuss more.

**Comment by kira-lin** [comment]
Okay, but I'm still not sure if we can use it. In our case, the function which puts the data (foo in your case) is not a remote function. We run spark executor in a thread of a ray actor. The data is put by the executors

**Comment by stephanie-wang** [comment]
Hmm I'm a bit confused how this works then. What would the top-level task to rerun be? Can you provide a simplified example to show what behavior you want?

**Comment by kira-lin** [comment]
How our from_spark runs now:
from_spark called in python -> call java and pass dataframe through py4j -> mapPartitions on the df passed, save the data in the function, and return the object ids, owner addresses to python -> register the objects in python

What we plan to do now:
from_spark called in python -> tasks(method of an actor) spawned to get a partition of dataframe for each -> use a lock, so that only the first task will save the whole dataframe like above, the returned objects are saved in the actor -> each task returns one of the objects
We want the task to be rerun according to the partition. Using ray.get when returning works fine, but performance is unacceptable. We need a way to achieve it with better performance(no copy)

**Comment by stephanie-wang** [comment]
Let me see if I understand this correctly:
- there is one actor that owns all of the objects, let's call it `Owner`
- other threads will call `ray.put(x, owner_address=Owner)` to make sure that Owner owns all of the objects
- if `x` is lost, we want to make sure to re-execute whatever called `ray.put`.

Let me know if I misunderstood anything here.

In this case, the simplest solution I can think of is this:
- there is one actor that owns all of the objects, let's call it `Owner`
- Ray *tasks* (can be tasks executed on a multi-threaded actor) will call `ray.put(x, owner_address=Owner)` to make sure that Owner owns all of the objects
- if `x` is lost, Owner will re-execute the task that called `ray.put`.

This should be possible to do without supporting a new `ray.forward` call. Basically what we can do is send the currently executing task spec with the owner assignment RPC during the initial `ray.put`. Then the owner will store this as the local lineage and resubmit the task if the data is lost. Would that work for your use case?

**Comment by kira-lin** [comment]
What you understand is almost right, except that we can't make ray.put to be called in ray tasks now. It works like:
```
df.mapPartitions{ iter => 
  table = convertToArrow(iter)
  Ray.put(table, owner)
```
The function will be executed on spark executors(each of which is a thread of a Ray actor). We'll check how hard it is to implement this mapPartitions with ray tasks.

**Comment by stephanie-wang** [comment]
Thanks, @kira-lin, to clarify, I meant that the `ray.put` can be run on an actor, as long as it's always the same task that produces that object.

**Comment by kira-lin** [comment]
Sorry, I don't get it. If ray.put is called like our current way(not in its method), what taskID will the object have? Can this task be rerun?

**Comment by stephanie-wang** [comment]
This would only work with your planned refactor, which will associate each ObjectRef with a specific actor task, if I understand correctly.

**Comment by kira-lin** [comment]
The refactor is not feasible. We cannot even pass df/rdd when calling methods of executor actor, because it is not serializable, same as spark session. Without these, the executor can't save the data.

If we can implement from_spark this way, we would have returned the data directly to create the object, no need to use ray.put.

**Comment by stephanie-wang** [comment]
Synced offline, and we agreed to try to support forwarding the current task spec during `ray.put(owner=XXX)` to support reconstruction. @kira-lin will try to refactor the Spark-on-Ray code to leverage this method.

**Comment by kira-lin** [comment]
1. a task in python ->
2.  mappartitions in spark ->
3. ray.put in spark executor(a thread of a ray actor)
How can I get the task id of the first step in the third step? Thanks

**Comment by kira-lin** [comment]
@Catch-Bull Hi, I remember you implemented ray.put(owner=xxx), any idea on this? Is this useful in your use case?

**Comment by stephanie-wang** [comment]
> 1. a task in python ->
> 
>     2. mappartitions in spark ->
> 
>     3. ray.put in spark executor(a thread of a ray actor)
>        How can I get the task id of the first step in the third step? Thanks

I think you can probably get it through C++, but I'm not totally sure. Why do you need it?

**Comment by kira-lin** [comment]
As you said, I should forward the task spec in ray.put. The task spec should refer to the first step, right? Because I want that get rerun if lost. So where should I get the task spec during  ray.put in the third step?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Stephanie Wang ***@***.***>
发送时间: Thursday, May 12, 2022 7:39:32 AM
收件人: ray-project/ray ***@***.***>
抄送: Zhi Lin ***@***.***>; Mention ***@***.***>
主题: Re: [ray-project/ray] [Core] Forward task lineage if custom owner is specified in ray.put (Issue #23824)


  1.  a task in python ->

     *   mappartitions in spark ->

     *   ray.put in spark executor(a thread of a ray actor)
How can I get the task id of the first step in the third step? Thanks

I think you can probably get it through C++, but I'm not totally sure. Why do you need it?

―

**Comment by stephanie-wang** [comment]
Oh, got it. I think you actually want the task spec for the task that runs on the actor, though.

You will need to dive into the CoreWorker to do this. Here's a code sample to get the spec for the currently running [task](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L1682). I should have some time to help prototype this part next week, too, if you need it.

**Comment by kira-lin** [comment]
That'll be appreciated!

**Comment by kira-lin** [comment]
Hi @stephanie-wang ,
I was trying to implement as you said, but it did not behave as expected. What I did is: in CreateOwnedAndIncrementLocalRef, if owner address is set, (that is to assign an actor as owner), it sends a rpc to the owner to generate an objectID. This objectID is generated using worker_context_.GetCurrentTaskID of the owner, but the objectid still does not look like the objects returned by that task. The prefix part is different.

Why is it so?
