### ISSUE TITLE
[Datasets] [Bug] map_batches with actors reverses dataframe order

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#23833]
### What happened + What you expected to happen

When calling `map_batches` with `compute="actors"`, it seems the final order of the items is reversed. Contrary with tasks everything seems to be fine. See reproduction script for a simple example.

### Versions / Dependencies

Latest master

### Reproduction script

```
import ray

# Passes
ds = ray.data.from_items([1., 2., 3., 4.])
res = ds.map_batches(lambda item: item * 2., compute="tasks", batch_format="pandas").to_pandas().to_numpy().squeeze().tolist()
assert res == [2., 4., 6., 8.], res

# Fails
res = ds.map_batches(lambda item: item * 2., compute="actors", batch_format="pandas").to_pandas().to_numpy().squeeze().tolist()
assert res == [2., 4., 6., 8.], res
```

**Comment by krfricke** [comment]
I'm wondering if this could be the root cause of https://github.com/ray-project/ray/issues/20329?

**Comment by clarkzinzow** [comment]
@krfricke Thanks for opening this issue, definitely looks like a bug with the actor compute model! I'll take a look at fixing this.

>I'm wondering if this could be the root cause of https://github.com/ray-project/ray/issues/20329?

I don't think so, since the actor compute model isn't used in that workload.
