### ISSUE TITLE
[Core] No fault tolerance on detached actors

### ISSUE THREAD

**Issue by thomashlvt** [ray-project/ray#23845]
### What happened + What you expected to happen

For detached actors, the actor task is not retried after a process/node failure.
Presumably there is no reference to the actor that actually triggers the retry logic.

I am not sure whether this is expected behaviour or not. If so, any suggestions on how I can spawn detached actors while keeping the fault tolerance would be hugely appreciated!

### Versions / Dependencies

Docker image: Python:3.8

python 3.8.5
ray[default]==1.11.0

ray-1.11.0-cp38-cp38-manylinux2014_x86_64.whl 

### Reproduction script

I create a Ray cluster of 1 head node (`num_cpus=0`) and a worker node (`num_cpus=4`).
Then spawn the named actor from the Ray client through the following script:

```python
import ray
from time import sleep

ray.init("ray://localhost:10001", namespace="test")

@ray.remote
class DummyActor:
    def run_forever(self):
        while True:
            print("Running")
            sleep(5)

dummy = DummyActor.options(name="dummy", lifetime="detached").remote()
dummy.run_forever.remote()
```

The actor runs as expected.
After killing the worker node (where the actor was running), the actor dies, as expectedly.
However, when creating a new worker node, the actor never comes back alive.

**Comment by thomashlvt** [comment]
Awesome, this works, thx! Sorry, I thought `-1` was the default... Closing this issue :)

**Comment by thomashlvt** [comment]
Sorry, one more question. Is it possible to also retry the `DummyActor.run_forever` task when the actor is restarted. I tried using the `max_task_retries=-1` option, without success.

**Comment by jovany-wang** [comment]
Which task did you set the `max_task_retries` for?

**Comment by thomashlvt** [comment]
I pass `max_task_retries` in the `@ray.remote` decorator. (As detailed [here](https://docs.ray.io/en/latest/ray-core/fault-tolerance.html#actors))

**Comment by thomashlvt** [comment]
Thx, this approach works!
