### ISSUE TITLE
[Core] [Docs] small issue about the indent

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#23847]
### What happened + What you expected to happen

<img width="465" alt="image" src="https://user-images.githubusercontent.com/20907377/162843827-4cb001bd-a8b0-4533-b42e-262f6f4819e4.png">
and 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20907377/162843862-fc66f4ba-8833-413d-9fc8-79d61f23fab0.png">

https://github.com/ray-project/ray/blob/c8f207f746e49c2beff7c5f8dfac877e5c577ba6/doc/source/ray-core/doc_code/actor-pool.py and 
https://docs.ray.io/en/latest/ray-core/actors.html#actor-pool

This is the indent issue here!

### Versions / Dependencies

N/A

### Reproduction script

N/A

**Comment by iasoon** [comment]
Seems to be fixed (https://docs.ray.io/en/latest/ray-core/actors/actor-utils.html)

**Comment by pcmoritz** [comment]
Indeed!
