### ISSUE TITLE
[Datasets] write_parquet to GCS doesn't remove trailing /

### ISSUE THREAD

**Issue by a-ro** [ray-project/ray#23869]
### What happened + What you expected to happen

I am unsure to what extent this is a Ray bug vs expected behavior of using GCS. But the same script that used to work with Ray 1.8 had a new behavior when we switched to Ray 1.11.

1. If I save my dataset locally with a path that has a trailing slash, the trailing slash is ignored. If I use the same path but save on GCS instead, it will create a new directory "/" and save the parquet files under that dir. 

```
output.write_parquet("gs://my-bucket/magestic-ray/", 
                     filesystem=GCSFileSystem(),
                     try_create_dir=False)
```
I was expecting the same behavior as locally, which is saving the parquet files in `gs://my-bucket/magestic-ray`

2. Actual behavior: saved the parquet files under `gs://my-bucket/magestic-ray/`

### Versions / Dependencies

macOS Monterey 12.3.1
Python 3.9.7
pandas==1.3.5
ray==1.11.0
gcsfs=='2021.11.0'

### Reproduction script

```python
import pandas as pd
import ray
from gcsfs import GCSFileSystem


ray.init()
pdf = pd.DataFrame({"one": [1, 2, 3], "two": ["a", "b", "c"]})
ds = ray.data.from_pandas([pdf])


ds.write_parquet(
        "gs://my-bucket/magestic-ray/",
        filesystem=GCSFileSystem(),
        try_create_dir=False,        
)
```

**Comment by clarkzinzow** [comment]
GCS [treats trailing slashes as if it's part of the object name](https://cloud.google.com/storage/docs/troubleshooting#gsutil-stat), so I don't know if this behavior is unexpected. Not sure why this behavior changed between Ray versions, however.
