### ISSUE TITLE
[Core/PG/Schedule]Optimize the scheduling performance of actors/tasks with PG specified

### ISSUE THREAD

**Issue by larrylian** [ray-project/ray#23881]
####  1、 Current situation
1.  When pg is created, it will add a `xx_group_xxxx` Resource tag to node resource. eg: `CPU_group_e6b730b58a32a5b233c994fa8d6301000000`. 
2. Whether GCS scheduling or raylet scheduling, when scheduling actors/tasks with PG identification, the actor requirement which special pg and bundle index will be scheduled as a custom resource requirement.
eg: {CPU_group_1_e6b730b58a32a5b233c994fa8d6301000000:1}
3. **Then it will traverse each node to see whether there is this resource and whether the resource is sufficient When scheduling actors or tasks which require PG。However, only one node in all nodes meets this requirement.**

From the above process, we can see that the efficiency of actor scheduling is very low. The complexity of the algorithm is O (N), and N is the number of nodes.

#### 2、Optimization ideas:
In node selection process of actors scheduling that rely on PG. According to【PG Location index table( <pg_ id, bundle_ index, node_id>)】 directly queries the corresponding node_id. Then judge whether the node resources are sufficient. 

This optimization can reduce the complexity of the algorithm from O (N) to o (1)，and N is the number of nodes。In particular, the more nodes in large-scale clusters, the better the optimization effect.

Whether GCS scheduling or raylet scheduling, The implementation scheme is the same.

#### 3、 Optimization effect
In ant group, Now we have achieved the optimization in the GCS scheduling mode and obtained the following performance test results. The scheduling based on raylet is still implemented and will be shown later. In theory, the effect is the same.

##### 1、 Time consuming of selecting nodes through UT test:
The following is a statistical diagram of the time-consuming of each scheduling with 1500 nodes, 2000 PG and 12000 actors simulated.
**Effect: The average time of selecting nodes is reduced from 330us to 30us, and the performance is improved by about 11 times.**
![image](https://user-images.githubusercontent.com/11072802/163098283-2cf1f09e-f9e7-4b80-ad39-c810041b88cc.png)

##### 2、  Actual performance test of 1500 node large-scale cluster
**Test results:**
After testing a cluster of 1500 nodes, 100 concurrent submission of a total of 12,000 actors which dependent on PG), the performance improvement of the scenario is as follows:

1.  **The average time-consuming of selecting nodes for resource scheduling at GCS end is reduced from about (1 ~ 2ms) to (100 ~ 200 US), an increase of about 10 times. At the same time, the maximum time consumption of a single time is also reduced from the original 20ms to within 10ms.**

2.  **The total time of creating & executing 12,000  actors ranges from 271 (s) - > 225 (s) on average. Reduce time consumption by 17%.**

3. Theoretically, the greater the number of cluster nodes, the greater the improvement effect.

<div class="lake-content" typography="classic">

No. | The time-consuming of 100 concurrent submission of a total of 12000 actors（s) |  
-- | -- | --
  | Before optimization(s) | After optimization(s) | Percentage reduction
1 | 264.7 | 218.9 |  
2 | 266 | 227 |  
3 | 275 | 221.7 |  
4 | 281 | 222.1 |  
5 | 266.5 | 228.9 |  
6 | 274.6 | 231 |  
mean | 271.3 | 224.9333333 | 17%

</div>

**Test steps:**
_1.  Create 2000 PGs, 3 bundles per PGs, 6000 bundles in total. Wait until all PG are ready before performing the following test steps.
2.  Create 100 actors, and then each actor submits a total of 120 actors to PG. The total is 100 concurrent, and a total of 100 * 120 actors are submitted.
3.  Observe that the data of [GCS resource scheduling time consumption] in metric is the time consumption of the selected node
4.  Record the total time taken to submit 12000 actor._

**Comment by WangTaoTheTonic** [comment]
We'd like to remove the placement group labels in raylet for long term if possible, as it costs much more than the `regular` resources like cpu, memory when synchronizing in the cluster.

**Comment by raulchen** [comment]
@scv119 @rkooo567 This is an implementation-wise optimization for scheduling tasks that require PGs. IIUC, this optimization should be orthogonal to the PG 2.0 design. So I think we can add this optimization first.
