### ISSUE TITLE
[tune] Log sync fails on certain grid search values such as tuples

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#2388]
### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- Ray installed from (source or binary): binary
- Ray version: 0.5.0 
- Python version: Python 3.6.5
- Exact command to reproduce: n/a

### Describe the problem
I'm running an experiment with the following setup:
```python
tune.run_experiments({
    args.exp_name: {
        'run': 'my-runner',
        'config': {
            'image_size': tune.grid_search([(32, 32, 3), (16, 16, 3)]),
            'seed': tune.grid_search([1,2,3,4,5]),
        },
        ...
    }
})
```

The tuples in the `image_size` grid search result in trial names such as: `my-runner_6_image_size=(32, 32, 3),seed=1`, and thus the names of the result directories contain parentheses. This causes the logsync to fail with:

```bash
Running log sync: rsync -avz -e "ssh -i /home/ubuntu/ray_bootstrap_key.pem -o ConnectTimeout=120s -o StrictHostKeyChecking=no" 'ubuntu@10.138.0.9:'/home/ubuntu/ray_results/pusher/image/20180611-image-pusher-1/my-runner_6_image_size=(32, 32, 3),seed=4_2018-07-11_17-56-44oi02vquj'/' ''/home/ubuntu/ray_results/pusher/image/20180611-image-pusher-1/my-runner_6_image_size=(32, 32, 3),seed=4_2018-07-11_17-56-44oi02vquj'/' && gsutil rsync -r '/home/ubuntu/ray_results/pusher/image/20180611-image-pusher-1/my-runner_6_image_size=(32, 32, 3),seed=4_2018-07-11_17-56-44oi02vquj' 'gs://<...>/ray/results/pusher/image/20180611-image-pusher-1/my-runner_6_image_size=(32, 32, 3),seed=4_2018-07-11_17-56-44oi02vquj'
/bin/sh: 1: Syntax error: "(" unexpected
```

**Comment by ericl** [comment]
Looks like there may be unnecessary single quotes added around the already quote-escaped literals here: https://github.com/ray-project/ray/blob/74dc14d1fc4da4773d317f8570402cbe69d84f51/python/ray/tune/log_sync.py#L108

If removing those single quotes around `{}@{}:{}/` and `{}/` works, would you mind submitting a PR?

**Comment by hartikainen** [comment]
I'll test today or tomorrow and submit a PR if it works. Thanks Eric!
