### ISSUE TITLE
[RLlib] Pytorch only supports serialization through state_dict

### ISSUE THREAD

**Issue by kinalmehta** [ray-project/ray#23894]
### What happened + What you expected to happen

When using spectral_normalization in models, the following error occurs
```
  File "/home/kinal/miniconda3/envs/marl/lib/python3.9/site-packages/torch/nn/utils/parametrize.py", line 285, in getstate
    raise RuntimeError(
RuntimeError: Serialization of parametrized modules is only supported through state_dict(). See:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training
```
This is mostly because there are target policy copies made using `copy.deepcopy`. Check demo code for more details

Even though this is not directly related to ray/rllib, this does limit the use of pytorch functionality when using custom models. And the way ray/rllib handles pytorch classes is not officially supported by pytorch.

### Versions / Dependencies

Ray: 1.11.0
torch: 1.11.0
tensorflow: 2.8.0
Python: 3.9.7
OS: Fedora 35 with kernel 5.16

### Reproduction script

```py
import copy
import torch
import torch.nn as nn

sn = nn.utils.parametrizations.spectral_norm


model = nn.Sequential(
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
        )

for idx in range(len(model)):
    try: model[idx] = sn(model[idx])
    except: pass

model2 = copy.deepcopy(model)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ZengPan-github** [comment]
Hello, I have a similar problem. Have you solved it?

**Comment by jerry99s** [comment]
Hi, I meet the same problem. Could anyone help in this?
