### ISSUE TITLE
[RLLib] SampleBatch after shuffled has unshuffled intercepted_values 

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#23907]
### What happened + What you expected to happen

In ray=1.11.0, I found that the SampleBatch after `batch.shuffled()` has misaligned output. It turns out that the intercepted_values (which are torch tensors in my case) is keep intact from shuffling.

### Versions / Dependencies

ray=1.11.0

### Reproduction script

Called batch.shuffle() at arbitrary place in torch PPO execution plan.

**Comment by sven1977** [comment]
Hey @pengzhenghao , thanks for filing this issue. Great catch! I think this is indeed a bug as only the underlying (numpy) data is shuffled, but not the cached torch tensors.

**Comment by sven1977** [comment]
Provided a fix-it PR. Should be merged soon.

**Comment by pengzhenghao** [comment]
Thanks @sven1977 for quick fix! I came into this tiny bug when I debugging for a strange behavior when I run my old code in new version of ray. (But I can say this bug is not the reason)

I wonder if you can take a look and provide some insights, thanks!

https://discuss.ray.io/t/ppo-entropy-not-decreasing-in-ray-1-11-0-as-ray-1-2-0/5842/8
