### ISSUE TITLE
[RLlib] check_gym_environments not working with parametric actions

### ISSUE THREAD

**Issue by inpefess** [ray-project/ray#23925]
### What happened + What you expected to happen

The new `check_gym_environments` script in 2.3.1 is not working with a recommended way to deal with parametric actions (https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces).

The action space of a parametric environment is still discrete, so the checking script expects a step to succeed with any random action from it, which is not the case since some of them are not available.

For now, the only solution is to disable this check even for the environments for which, ideally, it should pass without errors.

### Versions / Dependencies

2.3.1

### Reproduction script

```python
from ray.rllib.examples.env.parametric_actions_cartpole import (
    ParametricActionsCartPole,
)
from ray.rllib.utils.pre_checks.env import check_gym_environments

parametric_env = ParametricActionsCartPole(1000)
check_gym_environments(parametric_env)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by inpefess** [comment]
I have just checked, it still fails with Ray 2.3.1

I can work on it, since in Gymnasium, `.sample()` method has a `mask` argument. It should be relatively straightforward:

If an observation is a `Dict` and has a key `action_mask` (as in the example https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces), we pass this value as `mask` argument for `action_space.sample`.

What do you think?

**Comment by Rohan138** [comment]
@inpefess Yes, if you'd like to create a PR for this, that would be highly appreciated. Otherwise I can go ahead and fix it.

Thank you for your contribution!

**Comment by inpefess** [comment]
> @inpefess Yes, that solution makes sense; if you'd like to create a PR for this, that would be highly appreciated.

OK, I'll work on it then.

**Comment by inpefess** [comment]
@Rohan138 I've created a PR, but there seems to be more trouble than I imagined. I'm still interested in moving it forward since my project uses parametric actions and Ray RLlib, and I think skipping the check instead of fixing it is suboptimal.
