### ISSUE TITLE
[RLlib] RuntimeError when testing self_play_with_open_spiel.py

### ISSUE THREAD

**Issue by MasterXiong** [ray-project/ray#23944]
### What happened + What you expected to happen

Hi, I tried to run the example code of ```self_play_with_open_spiel.py```. Everything went smoothly at first, but after training for about more than 100 iterations, I ran into the error as shown in the screenshot below, which seems to be a bug when calling Adam optimizer. 
![捕获](https://user-images.githubusercontent.com/20316847/163577436-2e4d3ecc-2932-46ac-bc13-5d9a1b8ee299.PNG)
Thanks for your help!

### Versions / Dependencies

python 3.6
torch==1.3.1
tensorflow==1.15.5
open-spiel==1.1.0
gym==0.21.0
mujoco-py==1.50.1.68
click==8.0.4

For ray, I tried with both version 1.11.0 and 2.0.0.dev0, and both encounter this error. 
Run with both docker on a server and directly on a local machine. 

### Reproduction script

Just run the example code of ```self_play_with_open_spiel.py```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @MasterXiong ,
I cannot reproduce this on master and I don't think we will look for the fix and pick it to earlier versions in this case.
Feel free to repoen the issue if you still experience it with our nightlies.
