### ISSUE TITLE
Ray component: Core , init doesn't run in colab

### ISSUE THREAD

**Issue by HosseinRZ95** [ray-project/ray#23949]
### What happened + What you expected to happen

I cant run ray.init() on Google colab it gives me this error:
[/usr/local/lib/python3.7/dist-packages/ray/_private/utils.py](https://localhost:8080/#) in get_system_memory()
    434     elif os.path.exists(memory_limit_filename_v2):
    435         with open(memory_limit_filename_v2, "r") as f:
--> 436             docker_limit = int(f.read())
    437 
    438     # Use psutil if it is available.

ValueError: invalid literal for int() with base 10: 'max\n'
it should run normally

### Versions / Dependencies

ray 1.12
python 3.7.1 colab
OS: linux colab

### Reproduction script

!pip install ray[default] -q
!pip install psutil -q 
!pip install gputil -q
import ray
ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by amirhossein-dezhboro** [comment]
I have the same problem. I would appreciate any solution.

**Comment by Victordmz** [comment]
Duplicate issue: #23943

**Comment by amogkam** [comment]
Hi all, thanks for making this issue! This is a known issue with ray 1.12. Please see https://github.com/ray-project/ray/issues/23951 for more informations, and possible workarounds. Thanks!
