### ISSUE TITLE
In utils.py get_system_memory() generates error on Google Colab

### ISSUE THREAD

**Issue by LilyShevchenko** [ray-project/ray#23943]
```
memory_limit_filename_v2 = "/sys/fs/cgroup/memory.max"
if os.path.exists(memory_limit_filename_v2):
    with open(memory_limit_filename_v2, "r") as f:
        docker_limit = int(f.read())
```

Generates TypeError on Colab Pro+ cause memory.max file contains 'max\n', not int.
I am a noob, idk whether it's your problem or theirs, just FYI. Reverting to previous Ray version fixed the issue.

**Comment by Victordmz** [comment]
I second this issue on Google Colab + the most recent ray tune version.
Reference notebook for reproducibility: https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/c24b93738bc036c1b66d0387555bf69a/hyperparameter_tuning_tutorial.ipynb

**Comment by HosseinRZ95** [comment]
I have same issue

**Comment by amirhossein-dezhboro** [comment]
I have this issue now... I think this issue stems from Google colab changes. I would appreciate if anyone could come with an idea to fix this

**Comment by amogkam** [comment]
Hi all, thanks for making this issue! This is a known issue with ray 1.12. Please see https://github.com/ray-project/ray/issues/23951 for more informations, and possible workarounds. Thanks!
