### ISSUE TITLE
[ray docker images] clean up ray-ml:nightly-py37-cpu and other outdated docker images

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#23974]
### Description

Was debugging with Kai and we realized that ray-ml:nightly-py37-cpu alike are deprecated. 

Could we maybe remove those docker images so that people wouldn't accidentally install the wrong outdated one?

@krfricke @simon-mo @allenyin55

**Comment by amogkam** [comment]
@xwjiang2010 can we provide more information here?

**Comment by xwjiang2010** [comment]
Could we maybe remove those docker images so that people wouldn't accidentally install the wrong outdated one?
Granted, it is pretty hard to keep track of the tags and get them exactly right.

**Comment by simon-mo** [comment]
If there's a list of such images, we can run a job to delete them from dockerhub
