### ISSUE TITLE
[Java] Support parallel actor. 

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#23973]
### Description

This is used for tracking the work items for Java parallel actor.
- [x] Initial implementation. #21701
- [ ] Write doc page for Java parallel actor.
- [ ] Auto-naming for parallel actor.
- [ ] Merge 2 generators into one.
- [ ] Fix return value type losing issue after Seralization 2.0

**Comment by simon-mo** [comment]
Would also be interesting to explore [Virtual Threads](https://openjdk.java.net/jeps/425)! I think this will allow equivalent of async actors in Python and be super powerful

**Comment by jovany-wang** [comment]
@simon-mo Do you have more context about the Python async requirements around here? or related issues.  I don't know whether it's recommended for Python because we're now focusing on removing multiple core worker instances from a process.

**Comment by jovany-wang** [comment]
reopening
