### ISSUE TITLE
[DEPENDENCIES] Dependency inconsistenct between platform (redis)

### ISSUE THREAD

**Issue by dchigarev** [ray-project/ray#23982]
### What happened + What you expected to happen

Since 1.12.0 release `redis` is no longer a mandatary dependency for Ray on any platform, supposing that a user can safely use Ray without it, unless they specify some redis-specific parameters. And that's exactly how it works on Linux, but not on Windows.

On Windows, Ray unconditionally imports `redis` inside [`_configure_system`](https://github.com/ray-project/ray/blob/f18fc31c7562990955556899090f8e8656b48d2d/python/ray/__init__.py#L74-L77), which makes it to fail with `ModuleNotFoundError` if `redis` is not installed. That wouldn't be a problem if `redis` would be a mandatory Ray's dependency on Windows, so that doing `pip install ray` installs everything needed.

Currently, doing `pip install ray` in a clean Windows env produces a non-working Ray:
```cmd
$ pip install ray
$ python -c "import ray; ray.init()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\rp-re\miniconda3\envs\clean_env5\lib\site-packages\ray\__init__.py", line 100, in <module>
    _configure_system()
  File "C:\Users\rp-re\miniconda3\envs\clean_env5\lib\site-packages\ray\__init__.py", line 77, in _configure_system
    ray._private.compat.patch_redis_empty_recv()
  File "C:\Users\rp-re\miniconda3\envs\clean_env5\lib\site-packages\ray\_private\compat.py", line 14, in patch_redis_empty_recv
    import redis
ModuleNotFoundError: No module named 'redis'
```
Is this expected or this should be considered as a bug?

### Versions / Dependencies

**OS**: Windows
**Ray**: 1.12.0
**Python**: 3.8.13

### Reproduction script

```bash
conda create --name clean_env python=3.8
conda activate clean_env
pip install ray
python -c "import ray; ray.init()"
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by dchigarev** [comment]
cc @modin-project/modin-ray[@rkooo567 @wuisawesome]

**Comment by wuisawesome** [comment]
cc @pcmoritz @czgdp1807 @mattip it sounds like this means the happy path on a fresh windows machine is broken. i'm sure the fix is simple, but this seems fairly important.

**Comment by amogkam** [comment]
@pcmoritz can you confirm if this should be a release blocker for 1.12.1?

**Comment by mwtian** [comment]
Sent a fix to remove Windows specific references to Redis in Python. Btw, since Win CI is passing, @wuisawesome do you know where can Python Redis get installed for Win CI?

**Comment by mwtian** [comment]
Ok, `redis` it is in `requirements.txt`

**Comment by wuisawesome** [comment]
@simon-mo probably knows more about the CI side of this than I do.
