### ISSUE TITLE
[Core] Being able/unable to modify numpy array in-place in shared memory

### ISSUE THREAD

**Issue by chunweiyuan** [ray-project/ray#23988]
### What happened + What you expected to happen

From [6507](https://github.com/ray-project/ray/issues/6507) I expect to be able to modify numpy arrays in-place in shared memory, once I tune the `writeable` flag.  However, I cannot seem to tune that knob in the snippet below.  On the other hand, `np.random.shuffle` still works in in-place mutation.  It's all a little confusing, as to what I can or cannot do in shared memory.

For my current work, I really would like to have different processes modifying different slices of the shared numpy array simultaneously.  Is that a no-no in Ray workflow?

### Versions / Dependencies

>>> ray.__version__
'1.11.0'
>>> np.__version__
'1.21.2'

### Reproduction script

```
import ray
import numpy as np

ray.init(num_cpus=2, object_store_memory=8*1e9)

ar = np.arange(5)

>>> ar.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

@ray.remote
def edit(ar):
    ar[4] = 100

ref = ray.put(ar)
edit.remote(ref)

>>> 2022-04-18 14:14:45,106	ERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::edit() (pid=662073, ip=10.158.148.186)
  File "<stdin>", line 3, in edit
ValueError: assignment destination is read-only

@ray.remote
def edit(ar):
    ar.flags.writeable = True
    ar[4] = 100

edit.remote(ref)

>>> 2022-04-18 14:15:48,121	ERROR worker.py:84 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): ray::edit() (pid=662073, ip=10.158.148.186)
  File "<stdin>", line 3, in edit
ValueError: cannot set WRITEABLE flag to True of this array

@ray.remote
def shuffle(ar):  # this actually succeeds in editing in-place
    np.random.shuffle(ar)
shuffle.remote(ref)
result = ray.get(ref)

>>> result
array([3, 4, 2, 0, 1])
```

**Comment by jjyao** [comment]
@chunweiyuan as mentioned in https://github.com/ray-project/ray/issues/6507, ray object is immutable so you shouldn't try to modify it in place. Even if you manage to make it work on a single box, it won't work in the cluster.  This use case is not something supported by Ray.
