### ISSUE TITLE
[docs] broken link in docs for searchable "ray design patterns" 

### ISSUE THREAD

**Issue by chucklesoclock** [ray-project/ray#23989]
### What happened + What you expected to happen

The following link is searchable via Google and search bar on the docs: 
* https://docs.ray.io/en/latest/ray-design-patterns/map-reduce.html#pattern-map-and-reduce

However from the screenshot, you can see such a page does not exist. I attempted to see if such a page was removed from the docs in a commit but was unable to ascertain. 

![image](https://user-images.githubusercontent.com/10835345/163881716-397dd182-979b-433a-a76e-3b150532be03.png)

I was hoping to get some useful info on patterns/antipatterns but alas. 

### Versions / Dependencies

N/A

### Reproduction script

https://docs.ray.io/en/latest/ray-design-patterns/map-reduce.html#pattern-map-and-reduce

Either follow the above link to see the 404 or search "map and reduce" from the search bar in the docs as below:

![image](https://user-images.githubusercontent.com/10835345/163883053-21db67af-67b6-494d-b539-b759afaeecab.png)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by maxpumperla** [comment]
@chucklesoclock @dynamicwebpaige all fixed

**Comment by chucklesoclock** [comment]
you guys rock! thank you for the prompt response
