### ISSUE TITLE
[Core][nightly-test] long_running_actor_deaths flaky 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23994]
### What happened + What you expected to happen

long_running_actor_deaths is flaky, @rkooo567 can you investigate and see why it's the case?

### Versions / Dependencies

latest ray

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
After the initial investigation, it looks like the test became flaky for 3 runs, and it became normal again.

Looking at the output, it was very difficult to figure out the root cause. 
```
7663, ip=172.31.78.77, repr=<actor_deaths.Parent object at 0x7efbf24f3110>)
  File "workloads/actor_deaths.py", line 89, in kill
    ray.get([child.__ray_terminate__.remote() for child in self.children])
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: Child
        actor_id: 8308d120e1ae90f061e2d74001000000
        pid: 3757748
        namespace: 89048da0-f1c4-4c05-b0c2-f57b3c4e14f8
        ip: 172.31.78.77
The actor is dead because its worker process has died. Worker exit type: INTENDED_EXIT
```

My immediate action item is;
1. Improve existing error messages to be clearer. I will write more details about `INTENDED_EXIT` to the error message.
2. See if the test becomes flaky again.

**Comment by scv119** [comment]
SGTM!

**Comment by scv119** [comment]
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_RHqukFXdtgr7BCFrgc5QuGv5 failed again!

**Comment by clarkzinzow** [comment]
@rkooo567 @scv119 Yep still flaky! https://buildkite.com/ray-project/release-tests-branch/builds/406#b17a86e9-d05c-45c0-8e80-d0c6fd24aac8

**Comment by scv119** [comment]
@rkooo567 bump it to p0 as this has been flaky recenlty.

**Comment by rkooo567** [comment]
Working on it now
