### ISSUE TITLE
[Core] OMP_NUM_THREADS change

### ISSUE THREAD

**Issue by ahah-figure** [ray-project/ray#24012]
### Description

It would be great if OMP_NUM_THREADS only changed within the context of a ray.get, ray.wait, tune.run, etc call so it doesn't affect other code.

### Use case

We just upgraded from ray from 1.8.0 to 1.11.0, and the change where importing ray sets OMP_NUM_THREADS to 1 has caused many issues for us. Examples:

1. A model pipeline that runs on a single machine might use ray to parallelize some data work then use xgboost or pytorch for thread-based model training or do something else that needs more than one thread.
2. A distributed pipeline might use ray.tune to optimize xgb hyperparameters where different trials happen on different nodes. Here, resources per trial would be something like `{cpu: os.cpu_count()}`.
3. Similarly, we use ray core to do distributed cross validation with xgb models. In this case, we wrap our training functions with `ray.remote(num_cpus=os.cpu_count())` and expect them to use all cores on whichever node they're on.
4. In a single function call, you may want to limit threads to 1 per worker (e.g., parallelizing some numpy code) then set them back to max (e.g., calling a function that does its own threading). This isn't an issue caused by the change, but we've had to do this before.

For many of our use cases, globally changing OMP_NUM_THREADS is a huge side-effect. My (probably uninformed) suggestion would be to make threads a resource like CPUs, GPUs, etc.

**Comment by krfricke** [comment]
Hi @ahah-figure, as a workaround, can you just set `OMP_NUM_THREADS` to something else (or even to empty `OMP_NUM_THREADS=`)? It is only overwritten if not already set before calling `ray.init()`

**Comment by ahah-figure** [comment]
> Hi @ahah-figure, as a workaround, can you just set `OMP_NUM_THREADS` to something else (or even to empty `OMP_NUM_THREADS=`)? It is only overwritten if not already set before calling `ray.init()`

Thanks. If I have a bunch of cron/airflow/prefect jobs that run on different machines, is there a better workaround than replacing

```
python -m mylib.main
```

with

```
export OMP_NUM_THREADS=$(cat /proc/cpuinfo | grep processor | wc -l) && python -m mylib.main
```

?
