### ISSUE TITLE
[RLlib] [Bug] The new ALE-py (v0.7.5) breaks the Atari wrapper in RLlib

### ISSUE THREAD

**Issue by ZaberKo** [ray-project/ray#24014]
### What happened + What you expected to happen

Currently, ALE-py released to 0.7.5, which changes its [`env.np_random`](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/db3728264f382402120913d76c4fa0dc320ef59f/src/gym/envs/atari/environment.py#L181). 

And this will cause an error when using the default Atari wrapper in RLlib.

https://github.com/ray-project/ray/blob/f18fc31c7562990955556899090f8e8656b48d2d/rllib/env/wrappers/atari_wrappers.py#L98

```
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```
Currently, downgrade to ALE-py 0.7.4 works for me. We should fix the code or set some constraints in `setup.py` 

### Versions / Dependencies

ay 1.12.0
gym 0.21.0
ale-py 0.7.5

### Reproduction script

None

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Hey @ZaberKo , thanks for filing this issue. This PR here (almost merged) fixes the issue. Thanks @avnishn for providing a fix for this problem so quickly!

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/24019
