### ISSUE TITLE
[Workflows] [Feature] Feature to limit the maximum number of workflows running.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#24029]
### Description

To better support https://github.com/ray-project/ray/issues/21161

One feature we need is to ensure workflow is able to limit the number of active workflows running.

We'll need APIs like this:

```
workflow.init(max_concurrent_jobs=N, max_queueing_jobs=M)
```

`max_concurrent_jobs` means for a given time, how many workflow jobs can run. A job will be queued if the number of running jobs reaches the limit.
`max_queueing_jobs` means the maximum number of jobs that can be queued. An exception will be thrown if the number of jobs queued reaches the limit.

### Use case

One use case is here: https://github.com/ray-project/ray/issues/21161

**Comment by iycheng** [comment]
@ericl  could you help review the proposed API there?

**Comment by suquark** [comment]
Close this issue with #24697
