### ISSUE TITLE
[Dashboard] Ray start head does not start dashboard

### ISSUE THREAD

**Issue by brucez-anyscale** [ray-project/ray#24051]
### What happened + What you expected to happen

I follow this doc https://docs.ray.io/en/latest/cluster/job-submission.html to test my ray job. 
I run the following:
```
(anyscale) [~]$ ray start --head
Local node IP: 127.0.0.1

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='127.0.0.1:6379' --redis-password='5241590000000000'

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto', _redis_password='5241590000000000')

  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
```

There is no line about ` INFO services.py:1360 -- View the Ray dashboard at http://127.0.0.1:8265`

And I cannot access http://127.0.0.1:8265/ either.

### Versions / Dependencies

$ ray --version
ray, version 1.9.0
$ python --version
Python 3.9.12

mac big sur 11.5.2

MacBook Pro (13-inch, M1, 2020)

### Reproduction script

 ray start --head

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by BigBen12138** [comment]
Please try `ray start --head --include-dashboard=true`, and it will remind you that you need to install ray[default].

**Comment by brucez-anyscale** [comment]
> Please try `ray start --head --include-dashboard=true`, and it will remind you that you need to install ray[default].

`ray start --head --include-dashboard=true` still does not start the dashboard.

**Comment by brucez-anyscale** [comment]
Figure out the solution
`pip install "ray[default]"`

**Comment by BigBen12138** [comment]
> `ray start --head --include-dashboard=true`
> 
> FYI for anyone that arrives at this thread, the above command does NOT give any reminders.

Because `pip install ray` only install ray core and it will remind you that you should install ray[default]. :)

**Comment by klieret** [comment]
In my case, I needed `pip install --upgrade --force-reinstall 'ray[default]'` to solve this (the `--upgrade --force-reinstall` arguments were necessary, despite being on a relatively new ray installation)

**Comment by summa-code** [comment]
This is still a problem, if there is conflict, they dont properly install Dashboard components.

**Comment by wanadzhar913** [comment]
Same, my Ray dashboard doesn't start in spite of installing `ray[default]` and `ray[serve]`.
