### ISSUE TITLE
[RLlib] KeyError in _step() from multi_gpu_learner_thread

### ISSUE THREAD

**Issue by RocketRider** [ray-project/ray#24074]
### What happened + What you expected to happen

I have an env with an agent that is not always used. So no data is produced in some batches. This leads to a key error in the _step() function when accessing batch.policy_batches.

So I changed the code to the following:
https://github.com/ray-project/ray/blob/master/rllib/execution/multi_gpu_learner_thread.py#L206
```
 # Load the batch into the idle stack.
        with self.load_timer:
            for pid in policy_map.keys():
                if not s.local_worker.is_policy_to_train(pid, batch):
                    continue
                policy = policy_map[pid]
                if isinstance(batch, SampleBatch):
                    policy.load_batch_into_buffer(
                        batch=batch,
                        buffer_index=buffer_idx,
                    )
                elif pid in batch.policy_batches:
                    policy.load_batch_into_buffer(
                        batch=batch.policy_batches[pid],
                        buffer_index=buffer_idx,
                    )
```
Is this a reasonable change and could be added to the code base?

### Versions / Dependencies

1.12.0

### Reproduction script

Create a env with an agent set as trainable_policy that is not producing any data.

**Comment by sven1977** [comment]
Hey @RocketRider , thanks for filing this. I think this is a good fix for the described situation. Let's create a PR ...

**Comment by RocketRider** [comment]
@sven1977 Thank you!
