### ISSUE TITLE
[Core] if "dataclasses" is installed as a pip dependency, cluster will silently fail to initialize

### ISSUE THREAD

**Issue by theocean154** [ray-project/ray#24078]
### What happened + What you expected to happen

```python
ray.init(runtime_env={"pip":["dataclasses"]})
```

This will seemingly create an environment, but fail to respond or be useable without any reported error.

May relate to #23844

### Versions / Dependencies

Latest ray

### Reproduction script

ray.init(runtime_env={"pip":["dataclasses"]})

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by theocean154** [comment]
May relate to #12091

**Comment by mattip** [comment]
I think the reproducer is missing a task invocation. This works for me with python 3.9 on ubuntu 20.04 and prints the result
```
import ray

ray.init(runtime_env={"pip":["dataclasses"]})

@ray.remote
def f(x):
    return x * x

futures = [f.remote(i) for i in range(4)]
print(ray.get(futures)) # [0, 1, 4, 9]
```

When I look in `/tmp/ray/session_latest/runtime_resources/pip/*/requirements.txt` I see `dataclasses`, and I can successfully start the virtualenv with `/tmp/ray/session_latest/runtime_resources/pip/*/virtualenv/bin/python`.

What version of python and what platform are you using?
