### ISSUE TITLE
[Core] [Docs/Question] Cython usage on Ray

### ISSUE THREAD

**Issue by jeromeshan** [ray-project/ray#24097]
Hi
I have a questions about cython usage in ray
But i could find any examples listed in the article. Nor by google or searching in repo.
Could you please help me there

**Comment by jeromeshan** [comment]
BTW
I was using to use ray to parallel cython code, but got this error
`ValueError: buffer source array is read-only`
also using ray.put for shared memory

But since i havent found an examples yet im not opening this error as an issue

**Comment by scv119** [comment]
@jeromeshan let's ask this question in https://discuss.ray.io/
