### ISSUE TITLE
[Autoscaler] [Docs] Link to cluster setup is broken

### ISSUE THREAD

**Issue by FedericoGarza** [ray-project/ray#24100]
In the section [Run on a Cluster](https://docs.ray.io/en/latest/ray-more-libs/multiprocessing.html#run-on-a-cluster), the link to [cluster setup](https://docs.ray.io/en/latest/ray-more-libs/cluster/index.html) does not work.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/10517170/164590051-60bad363-e6f0-4ef4-a78e-9813ea65162a.png">

**Comment by edoakes** [comment]
This is fixed in master
