### ISSUE TITLE
Run vulcanize trace_viewer

### ISSUE THREAD

**Issue by jleni** [ray-project/ray#2414]
### System information
- **OS Platform and Distribution**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.5.0
- **Python version**: conda, python 3.6.5
- **Exact command to reproduce**:

### Describe the problem
When running `ui.task_timeline()` in the Ray UI (jupyter), I always receive the same error message:

To view fullscreen, open chrome://tracing in Google Chrome and load `/tmp/tmp3gcxpm4j.json`
tracing/bin/trace_viewer_full.html is missing. Run vulcanize_trace_viewer from $TRACE_VIEWER and reload.

**Comment by robertnishihara** [comment]
Currently the way we are embedding the timeline into the Jupyter notebook seems to be unreliable. However, if you directly go to [chrome://tracing](chrome://tracing) and load the relevant `json` file, then it should work.

**Comment by jleni** [comment]
Yes, I've done that. I was not sure you were aware of this bug. Thanks!
Thanks for ray, it is a very a great contribution.

**Comment by robertnishihara** [comment]
Got it, thanks for reporting the bug! And I'm glad you like it :)

**Comment by singhai0** [comment]
Encountered the same error. Things work great in `chrome://tracing` though 🙇.

**Comment by Lmathesen** [comment]
I'm running Ray through Ubuntu 18.04 as a subsytem application on my Windows 10 machine. I am getting the same error when I try to execute through the Ray UI (jupyter notebook). I tried to execute the work around above (going through `chrome://tracing`), but when I access my Ubuntu files from Windows the associated `json` file does not exist in my `tmp` folder. I am currently running all visualizations through Windows, as the Ubuntu subsytem application does not support direct GUI's from linux. 
Is there any reason why the `tmp` folder is getting updated with the run files from Ray? (Indeed my whole `tmp` folder is empty as of now)

**Comment by ericl** [comment]
Auto-closing stale issue.
