### ISSUE TITLE
[tune] get_system_memory() crashes with "ValueError: invalid literal for int() with base 10: 'max\n'"

### ISSUE THREAD

**Issue by Athe-kunal** [ray-project/ray#24155]
### What happened + What you expected to happen

I am using Ray tune for [FInRL](https://github.com/AI4Finance-LLC/FinRL) with RLlib models and here is the tutorial [notebook](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/4-Optimization/FinRL_HyperparameterTuning_Raytune_RLlib.ipynb)
This tutorial notebook was working fine just a month back but now it is showing the following using:

When I am running the tune.run() functionality, it is throwing me the following error

`ValueError: invalid literal for int() with base 10: 'max\n'`

The error trace is as follows

```
def get_system_memory():
    """Return the total amount of system memory in bytes.

    Returns:
        The total amount of system memory in bytes.
    """
    # Try to accurately figure out the memory limit if we are in a docker
    # container. Note that this file is not specific to Docker and its value is
    # often much larger than the actual amount of memory.
    docker_limit = None
    # For cgroups v1:
    memory_limit_filename = "/sys/fs/cgroup/memory/memory.limit_in_bytes"
    # For cgroups v2:
    memory_limit_filename_v2 = "/sys/fs/cgroup/memory.max"
    if os.path.exists(memory_limit_filename):
        with open(memory_limit_filename, "r") as f:
            docker_limit = int(f.read())
    elif os.path.exists(memory_limit_filename_v2):
        with open(memory_limit_filename_v2, "r") as f: #
            docker_limit = int(f.read()) #Here error

    # Use psutil if it is available.
    psutil_memory_in_bytes = psutil.virtual_memory().total

    if docker_limit is not None:
        # We take the min because the cgroup limit is very large if we aren't
        # in Docker.
        return min(docker_limit, psutil_memory_in_bytes)

    return psutil_memory_in_bytes
```

### Versions / Dependencies

pandas==1.3.5
numpy==1.21.6
matplotlib==3.2.2
optuna==2.10.0
ray==1.12.0

I am running on Google colab

### Reproduction script

Here is the tutorial [notebook](https://github.com/AI4Finance-Foundation/FinRL/blob/master/tutorials/4-Optimization/FinRL_HyperparameterTuning_Raytune_RLlib.ipynb) to reproduce the results

**Comment by xwjiang2010** [comment]
Hi,
I searched around and seems there is a recent patch that addresses some of the issues with using Google Colab. https://github.com/ray-project/ray/pull/23922
Would you like to give it a try?

**Comment by xwjiang2010** [comment]
Actually.. looks related to #24149

**Comment by richardliaw** [comment]
There's a mega-hack you can use to get around this for now:
```
import ray
import psutil
psutil_memory_in_bytes = psutil.virtual_memory().total

ray._private.utils.get_system_memory = lambda: psutil_memory_in_bytes
```

**Comment by Athe-kunal** [comment]
This solved the issue, thank you @richardliaw and @xwjiang2010
