### ISSUE TITLE
[Datasets] Prefetching in `iter_batches()` does not work as expected

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#24158]
Due to `ray.wait()`'s `fetch_local` semantics being broken, prefetching in `Dataset.iter_batches()` is currently not working as expected. I.e., the benchmarking done in https://github.com/ray-project/ray/pull/23952 suggests that pull requests are not being started for all objects in the prefetch window.

### Possible Solutions

We should use a prefetching alternative with minimal overhead. Two options are:
1. **Actor-based prefetching** - pin an actor to each consumer and, at prefetch time, pass the prefetch window to an actor task in order for the blocks to be pulled to the node as task arguments. This is currently implemented [here](https://github.com/ray-project/ray/pull/23952), but has a few drawbacks:
  a. If they consumer doesn't have a Ray worker local (e.g. Ray Client), this breaks.
  b. It adds an extra actor-per-node overhead to the Ray cluster.
  c. Every prefetch incurs actor task submission overhead.
2. **Background thread prefetching** - use one or more background threads to prefetch blocks, feeding batches to the main thread via a queue. This has a few pros:
  a. This works with Ray Client.
  b. This doesn't add any extra Ray-level overhead, and the extra system-level overhead of the background thread should be minimal.
  c. We were already planning on adding such a background thread for pipelining batch slicing and batch transformations with training on prior batches.

(2) is more ideal given the provided pros, so we should try to make this work.

**Comment by jianoaix** [comment]
For drawback 1.b and 1.c, my sense is that they will matter in serving system with high throughput. I'm not sure it will matter that much here since it's one per validation node. I didn't realize 1.a is a problem, is it a real concern? Missing Ray Client already means broken ray node?

**Comment by jianoaix** [comment]
Actually I just recalled that it should work even in serving systems context based on my past experience. But we can evaluate anyway.

**Comment by clarkzinzow** [comment]
>For drawback 1.b and 1.c, my sense is that they will matter in serving system with high throughput. I'm not sure it will matter that much here since it's one per validation node.

1(b) and 1(c) can both affect latency/throughput of the batch iterator, which can affect GPU utilization. We've also run into miscellaneous issues with these kind of dummy actor patterns in the past.

>I didn't realize 1.a is a problem, is it a real concern? Missing Ray Client already means broken ray node?

Yes, it would cause this to break whenever batch prefetching is used with the consumer being Ray Client. In production workloads, the consumer will typically be another Ray library that will consume batches on a Ray worker, but this is still a big limitation for the prototyping phase.

**Comment by zhe-thoughts** [comment]
@clarkzinzow thanks for writing the summary (I really like it)

Is this a blocker for Dataset GA? cc @ericl for assessment too

**Comment by ericl** [comment]
I think this is a blocker for GA. There isn't a good way to get high performance for training with datasets on a multi node cluster if this feature is not working as intended.

**Comment by ericl** [comment]
We could also just fix ray.wait() right? Could we take a look into that first? Happy to hack on this in person say Monday.

**Comment by jianoaix** [comment]
We might need to root fix ray.wait() as actor pool is also relying on it.

**Comment by clarkzinzow** [comment]
@jianoaix The actor pool's use of `ray.wait()` should be fine, since it's not relying on any prefetching behavior (`fetch_local=False`): https://github.com/ray-project/ray/blob/024eafb5f4f07dbcb7f553085764272a82687944/python/ray/data/impl/compute.py#L192-L194

**Comment by jianoaix** [comment]
Remove release-blocker since we took workaround https://github.com/ray-project/ray/pull/23952 for now.
