### ISSUE TITLE
[Datasets] Automatically infer tensor blocks when returning NumPy ndarrays from `.map_batches()`

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#24208]
When the return type of the batch UDF in `.map_batches()` is a NumPy ndarray or list of ndarrays, we should automatically create a single-column table leveraging our tensor array extension. This should allow users to automatically benefit from our tensor block support.

**Comment by xwjiang2010** [comment]
This is great!
For my own understanding, does this mean that if I have a n-d numpy array returned, it will be automatically converted to an array with each element being (n-1) d numpy arrays?

**Comment by clarkzinzow** [comment]
>For my own understanding, does this mean that if I have a n-d numpy array returned, it will be automatically converted to an array with each element being (n-1) d numpy arrays?

Correct! If the UDF returns an ndarray, the outermost dimension of the ndarray will be treated as the row (batch) dimension; if the UDF returns a list of ndarrays, the list will be treated as the row (batch) dimension.

```python
ds = ray.data.range(4, parallelism=2)
print(ds)
# -> Dataset(num_blocks=2, num_rows=4, schema=<int>)
 
# Map each of the 2 blocks to 3 rows of 32 x 32 tensors, for a total of 6 rows.
ds2 = ds.map_batches(lambda _: np.ones((3, 32, 32)))
print(ds2)
# -> Dataset(num_blocks=2, num_rows=6, schema={"value": <ArrowTensorType: shape=(32, 32), dtype=double>})

# Map each of the 2 blocks to 2 rows of 32 x 32 tensors, for a total of 4 rows.
ds3 = ds.map_batches(lambda _: [np.ones((32, 32)), np.ones((32, 32))])
print(ds2)
# -> Dataset(num_blocks=2, num_rows=4, schema={"value": <ArrowTensorType: shape=(32, 32), dtype=double>})
```
