### ISSUE TITLE
[Core] Ray not producing same results as python serial run on Linux for ARIMA / lbgfs

### ISSUE THREAD

**Issue by ngupta23** [ray-project/ray#24224]
### What happened + What you expected to happen

Based on the example for [parallelizing ARIMA](https://www.anyscale.com/blog/scaling-time-series-forecasting-on-ray-arima-and-prophet-on-ray), I tried to replicate this with my dataset. I have multiple time series and I am using Ray to forecast these time series. When I forecast them serially using native python, I get a certain answer, and when I run them in parallel using ray, I get a different answers. 

NOTES:

1. This issue was observed on linux only. When I ran the same code on Windows with same library versions installed, I could not reproduce the issue.
2. The issue seems to be with the default `lbfgs` method used by pmdarima ARIMA model fit. If I change the method to `nm`, the results match between the python serial run and the ray parallel run on Linux as well. Hence the issue seems to be coming from how ray is handling `lbgfs` on Linux.

I would expect the python serial run and ray parallel runs to produce the same results.

### Windows

```
System:
    python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
    executable: C:\Users\Nikhil\.conda\envs\ray-test\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
    statsmodels: 0.13.2
    scipy: 1.7.3
    pmdarima: 1.8.5
    ray: 1.12.0
```

### Linux

```
System:
    python: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0]
    executable: /home/cdsw/.conda/envs/ray-test/bin/python
   machine: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17

Python dependencies:
        statsmodels: 0.13.2
        scipy: 1.7.3
        pmdarima: 1.8.5
        ray: 1.12.0       
```

### Reproduction script

Please see https://github.com/ngupta23/ray-test/blob/bug_ray/analysis/ray_pycaret_forecast_with_pandas.py

The dataset is included in the repo itself and will be read in when the above script is executed.

## Output of Script on Windows

```python
Ray Results match with Serial Python Run
```

## Output of script on Linux

`y_pred_x` is the python serial run
`y_pred_y` is the ray parallel run

```python
Ray Results that did not match Serial Python Run for following
          Item YYYYMM  y_pred_x  y_pred_y
0   B     2022-04    2820.0    2833.0
1   B     2022-05    5631.0    5656.0
2   B     2022-06    8432.0    8469.0
3   B     2022-07   11223.0   11273.0
4   B     2022-08   14004.0   14067.0
5   B     2022-09   16776.0   16851.0
6   B     2022-10   19538.0   19625.0
7   B     2022-11   22291.0   22390.0
8   B     2022-12   25034.0   25145.0
9   B     2023-01   27767.0   27891.0
10  B     2023-02   30491.0   30627.0
11  B     2023-03   33206.0   33353.0
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ngupta23** [comment]
I did some more digging and found that this issue is present even when using pyspark to parallelize the forecasts. However, the discrepancy is not present for the same time series. For example, in my case, for 1000 time series, pyspark mismatched on 3/1000 while ray mismatched on 1/1000 (and the one that was mismatching here was also mismatching in spark). Not sure if this is helpful for the final resolution, but thought I would document the findings here.

**Comment by jjyao** [comment]
Seems the issue is not related to Ray then? Is my understanding correct @ngupta23?

**Comment by ngupta23** [comment]
> Seems the issue is not related to Ray then? Is my understanding correct @ngupta23?

I would not put it that way. Reproducibility is still highly desired when we are parallelizing the run (compared to serial run). The fact that spark also does not produce same results always is just a side note. I am wondering if there is some initialization that is not happening correctly when parallelizing (I don't understand the internals of ray enough to comment on that).

**Comment by ngupta23** [comment]
Just FYI... The issue has not been resolved yet.
