### ISSUE TITLE
[Serve] Call to deployment handle sometimes blocks forever

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#24228]
### What happened + What you expected to happen

Code like the following sometimes blocks forever:
```
handle = Deployment.get_handle()
objref = handle.<fn>.remote(<args>)  # This is the line that blocks!
```

This happens with both the synchronous and the asynchronous handle (the latter using `objref = await handle...`). It seems to happen most right after several Serve replicas die (e.g., due to OOM or a pod they're on getting killed). 

We'd expect that the remote call *always* returns immediately, or there is a `timeout` option we can set to preempt the `remote()` call so we can try again or handle the issue another way. Our current solution is to wrap up the `remote()` call in a preemptible thread with a timeout.

This thread has the `py-spy` dump of an actor stuck on the call, as an example: https://discuss.ray.io/t/serve-handle-remote-calls-block-forever/5882. It seems that when the call goes synchronous (in `_try_assign_replica`), something blocks forever and doesn't return.

In the `python-core-worker-<hash>.log` file, we also see this message repeated many times:
```
[2022-04-27 19:56:25,237 I 223 246] direct_actor_task_submitter.cc:448: PushActorTask failed because of network error, this task will be stashed away and waiting for Death info from GCS, task_id=b767b7acdba684cee74317c6ca374f617b4954e901000000, wait queue size=7
[2022-04-27 19:56:25,253 I 223 246] task_manager.cc:419: Task failed: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: : Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.serve.replica, class_name=create_replica_wrapper.<locals>.RayServeWrappedReplica, function_name=handle_request, function_hash=}, task_id=3d921768abb887b4dd99d63cb666aa8ffc8b0e7001000000, task_name=RayServeWrappedReplica.handle_request(), job_id=01000000, num_args=4, num_returns=3, depth=0, actor_task_spec={actor_id=dd99d63cb666aa8ffc8b0e7001000000, actor_caller_id=ffffffffffffffff660e30a601ee6c4ee6f13aff03000000, actor_counter=0}
```

### Versions / Dependencies

Ray 1.11/1.12
Python 3.7.12
Ubuntu Linux 20
Running on Kubernetes

### Reproduction script

None

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by spolcyn** [comment]
@simon-mo

**Comment by edoakes** [comment]
@spolcyn do you have a minimal example we can use to reproduce this behavior? Would greatly help our ability to debug.

**Comment by spolcyn** [comment]
@edoakes Unfortunately not -- tried to make one several times to debug with, but no luck. Our full test suite passes, and it only seems to happen in the middle of relatively large jobs once deployed on a cluster deployed on k8s.

We're able to consistently replicate it with that cluster setup and our workload, though.

We also have these logs that occur when the issue happens (attached), which might suggest the error is occurring and returning, but nothing is awaiting that created `asyncio.Task`
[ray-logs.txt](https://github.com/ray-project/ray/files/8566527/ray-logs.txt)

**Comment by spolcyn** [comment]
An additional `py-spy` dump of what the call stack looks like when the actor is blocked:

```
Process 223: ray::InferenceJobHandlerActor.health_check()
Python v3.7.12 (/venv/bin/python3.7)

Thread 0x7FEC0180F740 (active): "MainThread"
    main_loop (ray/worker.py:449)
    <module> (ray/workers/default_worker.py:235)
Thread 251 (idle): "ray_import_thread"
    wait (threading.py:300)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:148)
    result (grpc/_channel.py:735)
    _poll_locked (ray/_private/gcs_pubsub.py:274)
    poll (ray/_private/gcs_pubsub.py:410)
    _run (ray/_private/import_thread.py:67)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 255 (idle): "AsyncIO Thread: default"
    _actor_method_call (ray/actor.py:1176)
    invocation (ray/actor.py:161)
    _remote (ray/actor.py:168)
    _start_span (ray/util/tracing/tracing_helper.py:421)
    remote (ray/actor.py:122)
    _poll_next (ray/serve/long_poll.py:107)
    _on_callback_completed (ray/serve/long_poll.py:101)
    chained (ray/serve/long_poll.py:159)
    _run (asyncio/events.py:88)
    _run_once (asyncio/base_events.py:1786)
    run_forever (asyncio/base_events.py:541)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7FEB45D76700 (active)
Thread 297 (idle): "Thread-4"
    wait (threading.py:300)
    wait (threading.py:552)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 771 (idle): "Thread-15"
    channel_spin (grpc/_channel.py:1258)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 246 (idle)
```

**Comment by spolcyn** [comment]
@edoakes Is this issue better for Ray Core? It seems to be triggered during some Serve behavior, but the logs below suggest maybe it's closer to core's work.

The core-worker logs on an actor that stalled (not responding to `ray.kill()` or other requests) are attached below, and it looks like the main error repeated over and over again is `GrpcUnavailable: RPC Error message: Socket closed...` 

[python-core-worker-logs.txt](https://github.com/ray-project/ray/files/8577500/python-core-worker-logs.txt)

This was accompanied in the normal worker logs by logs of the following exception (roughly the same # of occurrences as the `GrpcUnavailable` error in the core-worker logs).

```
2022-04-27 19:56:26,481 [ERROR] [base_events.py:1619] asyncio: Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /venv/lib/python3.7/asyncio/tasks.py:623> exception=RayActorError()>
Traceback (most recent call last):
  File "/venv/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: create_replica_wrapper.<locals>.RayServeWrappedReplica
        actor_id: e74317c6ca374f617b4954e901000000
        pid: 117
        name: SERVE_REPLICA::<app replica>#uVzzXF
        namespace: serve
        ip: IP_ADDRESS
The actor is dead because it was killed by `ray.kill`.
```

**Comment by simon-mo** [comment]
@spolcyn to clarify, is this issue now the same as #24419?

**Comment by spolcyn** [comment]
Correct, closing issue in favor of #24419

**Comment by eladn** [comment]
We’re facing the same issue when trying to make this remote() call from a pythonic thread. Were you also used threads on your original failed workflow, or was the remote() call invoked from the main thread?

**Comment by JalinWang** [comment]
I observed similar behaviors when trying to visit the failed deployment through HTTP. The request will hang. However, I can't use `request_timeout_s` because sometimes model inference takes very long.
