### ISSUE TITLE
[RLlib] Possible performance degradation from 1.10 to 1.12 

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#24247]
### What happened + What you expected to happen

With certain RL workloads, training will be slower with 1.12 than 1.10 (details TBA) cc @gjoliver @avnishn @sven1977

### Versions / Dependencies

1.12.0

### Reproduction script

TBA

### Issue Severity

High: It blocks me from completing my task.

**Comment by gjoliver** [comment]
we should be able to find a workaround without requiring cherrypicks.
unfortunately, a good fix exposed a different issue with our agent.
the real performance fix will need to come later after much investigation.

**Comment by gjoliver** [comment]
I will close this after working with Ben tomorrow.

**Comment by gjoliver** [comment]
wait, is this a release blocker for 1.13 or 1.12.1?
it may be nice if we can find a fix before 1.13 is out.

**Comment by zhe-thoughts** [comment]
Hey @gjoliver : I think it should be a release blocker for 1.13.0. Probably not worth blocking 1.12.1 on this.

**Comment by gjoliver** [comment]
sounds good

**Comment by gjoliver** [comment]
this is now fixed.
