### ISSUE TITLE
[rllib] Apex DDPG gpu utilization

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#2424]
Hi,

While using Ray Apex DDPG (`AsyncSamplesOptimizer`), I see one strange thing: even if config is with `gpu: true` I don't see any gpu utilisation in nvidia-smi:
![image](https://user-images.githubusercontent.com/7606451/42943917-e0bcb5b6-8b6c-11e8-8b44-76015c5c9d4e.png)

Why is that? By the docs, I assume to see 100% utilisation, cause the network should be updated in the background in something like training thread, is't it?

PS. sorry for a lot of questions, but it's RL completions time.

**Comment by ericl** [comment]
There definitely should be GPU util once learning starts. Are you running this through ./train.py? It should say something like `Resources used: 4/8 CPUs, 1/1 GPUs`. If not you'll need to make sure whatever process is running the agent has CUDA_VISIBLE_DEVICES set correctly.

You can also try running this https://github.com/ray-project/ray/blob/master/python/ray/rllib/tuned_examples/pong-apex.yaml which definitely uses a GPU.

**Comment by ericl** [comment]
Oh ic, APEX_DDPG never implemented the correct resource request when gpu: True. Also fixed here: https://github.com/ray-project/ray/pull/2426/files

**Comment by Scitator** [comment]
@ericl interesting, cause your example with pong utilises gpu for normal 10-20% 🤔

**Comment by ericl** [comment]
This should be fixed in master
