### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by ZPFPHD** [ray-project/ray#24255]
### What happened + What you expected to happen

Traceback (most recent call last):
File "E:\conda\envs\pytorch\lib\site-packages\ray_private\services.py", line 655, in wait_for_redis_to_start
redis_client.client_list()
File "E:\conda\envs\pytorch\lib\site-packages\redis\client.py", line 1194, in client_list
return self.execute_command('CLIENT LIST')
File "E:\conda\envs\pytorch\lib\site-packages\redis\client.py", line 898, in execute_command
conn = self.connection or pool.get_connection(command_name, **options)
File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 1192, in get_connection
connection.connect()
File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 567, in connect
self.on_connect()
File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 643, in on_connect
auth_response = self.read_response()
File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 739, in read_response
response = self._parser.read_response()
File "E:\conda\envs\pytorch\lib\site-packages\redis\connection.py", line 484, in read_response
raise response
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "hyper_tune.py", line 52, in
other_args=other_args)
File "H:\Bigscity-LibCity\libcity\pipeline\pipeline.py", line 211, in hyper_parameter
local_dir='./libcity/cache/hyper_tune', num_samples=num_samples)
File "E:\conda\envs\pytorch\lib\site-packages\ray\tune\tune.py", line 298, in run
_ray_auto_init()
File "E:\conda\envs\pytorch\lib\site-packages\ray\tune\tune.py", line 681, in _ray_auto_init
ray.init()
File "E:\conda\envs\pytorch\lib\site-packages\ray_private\client_mode_hook.py", line 82, in wrapper
return func(*args, **kwargs)
File "E:\conda\envs\pytorch\lib\site-packages\ray\worker.py", line 896, in init
ray_params=ray_params)
File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 248, in init
self.start_head_processes()
File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 894, in start_head_processes
self.start_redis()
File "E:\conda\envs\pytorch\lib\site-packages\ray\node.py", line 714, in start_redis
port_denylist=self._ray_params.reserved_ports)
File "E:\conda\envs\pytorch\lib\site-packages\ray_private\services.py", line 881, in start_redis
port_denylist=port_denylist)
File "E:\conda\envs\pytorch\lib\site-packages\ray_private\services.py", line 1029, in _start_redis_instance
wait_for_redis_to_start("127.0.0.1", port, password=password)
File "E:\conda\envs\pytorch\lib\site-packages\ray_private\services.py", line 666, in wait_for_redis_to_start
redis_ip_address, redis_port)) from authEx
RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.

When redis does not set a password, it will prompt that the client has authentication and the python program should be removed. When I set the redis password, I will be prompted with an invalid password. It should be that the password set in Python was not passed in correctly

### Versions / Dependencies

Package                       Version
----------------------------- -----------
absl-py                       0.13.0
aiohttp                       3.7.4.post0
aiohttp-cors                  0.7.0
aioredis                      1.3.1
alabaster                     0.7.12
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
ase                           3.22.1
astor                         0.8.1
astunparse                    1.6.3
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
bleach                        4.1.0
blessings                     1.7
blinker                       1.4
boto                          2.49.0
boto3                         1.21.32
botocore                      1.24.32
Bottleneck                    1.3.2
brotlipy                      0.7.0
bz2file                       0.98
cachetools                    4.2.2
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.3
cloudpickle                   2.0.0
colorama                      0.4.4
colorful                      0.5.4
coverage                      5.5
cryptography                  3.4.8
cycler                        0.10.0
Cython                        0.29.24
d2l                           0.17.3
debugpy                       1.5.1
decorator                     4.4.2
defusedxml                    0.7.1
dgl                           0.6.1
docutils                      0.17.1
durbango                      0.23
entrypoints                   0.3
et-xmlfile                    1.1.0
fastdtw                       0.3.4
fastprogress                  1.0.0
filelock                      3.6.0
flake8                        4.0.1
flake8-polyfill               1.0.2
fonttools                     4.25.0
fsspec                        2022.1.0
funcy                         1.17
future                        0.18.2
gast                          0.3.3
gensim                        4.1.2
geographiclib                 1.52
geopy                         2.0.0
google-api-core               2.7.2
google-auth                   1.33.0
google-auth-oauthlib          0.4.1
google-pasta                  0.2.0
googleapis-common-protos      1.56.0
googledrivedownloader         0.4
gpustat                       0.6.0
grpcio                        1.36.1
h5py                          2.10.0
hiredis                       1.1.0
hyperopt                      0.2.5
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.8.1
importlib-resources           5.4.0
iniconfig                     1.1.1
ipykernel                     6.7.0
ipython                       7.31.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isodate                       0.6.1
jedi                          0.18.1
Jinja2                        3.0.3
jmespath                      0.10.0
joblib                        1.1.0
JsonForm                      0.0.2
jsonschema                    4.4.0
JsonSir                       0.0.2
jupyter                       1.0.0
jupyter-client                7.1.1
jupyter-console               6.4.0
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
llvmlite                      0.37.0
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
mccabe                        0.7.0
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mock                          4.0.3
more-itertools                8.12.0
msgpack                       1.0.2
multidict                     5.1.0
munkres                       1.1.4
nbclient                      0.5.11
nbconvert                     6.4.2
nbformat                      5.1.3
nest-asyncio                  1.5.4
networkx                      2.6.3
nltk                          3.7
notebook                      6.4.8
numba                         0.54.1
numexpr                       2.7.3
numpy                         1.21.5
nvidia-ml-py3                 7.352.0
oauthlib                      3.1.1
olefile                       0.46
opencensus                    0.9.0
opencensus-context            0.1.2
openpyxl                      3.0.9
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
parso                         0.8.3
patsy                         0.5.2
pep8-naming                   0.12.1
pickle5                       0.0.11
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.2.4
pluggy                        0.13.1
prettytable                   3.0.0
prometheus-client             0.13.1
prompt-toolkit                3.0.24
protobuf                      3.17.2
psutil                        5.8.0
py                            1.10.0
py-spy                        0.3.11
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycparser                     2.21
pyDeprecate                   0.3.1
pyflakes                      2.4.0
pygcn                         0.1
Pygments                      2.11.2
PyJWT                         2.1.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyreadline                    2.1
pyrsistent                    0.18.1
PySocks                       1.7.1
pytest                        6.2.4
python-dateutil               2.8.2
Python-EasyConfig             0.1.7
python-louvain                0.15
python-utils                  2.5.6
pytorch-lightning             1.5.9
pytz                          2021.3
pywin32                       302
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         22.3.0
qtconsole                     5.2.2
QtPy                          2.0.1
ray                           1.2.0
rdflib                        6.1.1
redis                         3.5.3
regex                         2022.3.15
requests                      2.27.1
requests-oauthlib             1.3.0
Resource                      0.2.1
rsa                           4.7.2
s3transfer                    0.5.0
scikit-learn                  1.0.1
scipy                         1.7.1
seaborn                       0.11.2
Send2Trash                    1.8.0
setproctitle                  1.1.10
setuptools                    59.5.0
six                           1.16.0
smart-open                    1.9.0
snowballstemmer               2.2.0
Sphinx                        4.3.2
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
statsmodels                   0.13.0
tables                        3.5.2
tabulate                      0.8.9
tensorboard                   2.6.0
tensorboard-data-server       0.6.0
tensorboard-plugin-wit        1.6.0
tensorboardX                  2.2
tensorflow                    2.3.0
tensorflow-estimator          2.6.0
termcolor                     1.1.0
terminado                     0.13.1
testpath                      0.5.0
threadpoolctl                 2.2.0
toml                          0.10.2
torch                         1.10.0
torch-cluster                 1.5.9
torch-geometric               2.0.3
torch-geometric-temporal      0.50.0
torch-scatter                 2.0.9
torch-sparse                  0.6.12
torch-spline-conv             1.2.1
torchaudio                    0.10.0
torchmetrics                  0.7.1
torchsummary                  1.5.1
torchtext                     0.11.0
torchvision                   0.11.1
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing-extensions             3.10.0.2
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.2
wheel                         0.37.0
widgetsnbextension            3.5.2
win-inet-pton                 1.1.0
wincertstore                  0.2
wrapt                         1.12.1
xlwings                       0.24.9
yacs                          0.1.8
yarl                          1.6.3
zipp                          3.6.0

### Reproduction script

"""
模型调参脚本 (based on the ray[tune])
"""

import argparse

from libcity.pipeline import hyper_parameter
from libcity.utils import add_hyper_args

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    # 增加指定的参数
    parser.add_argument('--task', type=str,
                        default='traffic_state_pred', help='the name of task')
    parser.add_argument('--model', type=str,
                        default='GRU', help='the name of model')
    parser.add_argument('--dataset', type=str,
                        default='METR_LA', help='the name of dataset')
    parser.add_argument('--config_file', type=str,
                        default=None, help='the file name of config file')
    parser.add_argument('--space_file', type=str,
                        default='hyper_example', help='the file which specifies the parameter search space')
    parser.add_argument('--scheduler', type=str,
                        default='FIFO', help='the trial sheduler which will be used in ray.tune.run')
    parser.add_argument('--search_alg', type=str,
                        default='BasicSearch', help='the search algorithm')
    parser.add_argument('--num_samples', type=int,
                        default=5, help='the number of times to sample from hyperparameter space.')
    parser.add_argument('--max_concurrent', type=int,
                        default=1, help='maximum number of trails running at the same time')
    parser.add_argument('--cpu_per_trial', type=int,
                        default=1, help='the number of cpu which per trial will allocate')
    parser.add_argument('--gpu_per_trial', type=int,
                        default=1, help='the number of gpu which per trial will allocate')
    parser.add_argument('--exp_id', type=str, default=None, help='id of experiment')
    parser.add_argument('--seed', type=int, default=0, help='random seed')
#parser.add_argument('-a', type=str, dest='123456', action='store', help='password of redis ')
    # 增加其他可选的参数
    add_hyper_args(parser)
    # 解析参数
    args = parser.parse_args()
    dict_args = vars(args)
    other_args = {key: val for key, val in dict_args.items() if key not in [
        'task', 'model', 'dataset', 'config_file', 'space_file', 'scheduler', 'search_alg',
        'num_samples', 'max_concurrent', 'cpu_per_trial', 'gpu_per_trial'] and
        val is not None}
    hyper_parameter(task=args.task, model_name=args.model, dataset_name=args.dataset,
                    config_file=args.config_file, space_file=args.space_file,
                    scheduler=args.scheduler, search_alg=args.search_alg,
                    num_samples=args.num_samples, max_concurrent=args.max_concurrent,
                    cpu_per_trial=args.cpu_per_trial, gpu_per_trial=args.gpu_per_trial,
                    other_args=other_args)

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Hi @ZPFPHD, could you improve the issue by having a title with summary of the issue? Also could you provide a minimal reproducible code?

Also seems you are using `ray 1.2.0` which is very old, could you try the latest ray?

**Comment by richardliaw** [comment]
closing as stale
