### ISSUE TITLE
[Datasets] Sort should support fusion with previous stages

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24270]
### Description

Currently sort requires first sampling all of the input blocks in a map stage, getting the results of these, then executing the actual shuffle. The sample stage should be fused with any previous fuse-able stages to avoid materializing intermediate data.

**Comment by ericl** [comment]
Hmm how would this help? Seems you'd need to materialize anyway prior to the shuffle map stage, since you'd not want to repeat the computation for generating the data before sample.

**Comment by stephanie-wang** [comment]
Currently it looks like this: Load data -> spill -> restore -> sample -> restore -> map ...

With fusion, we can get it to: Load data + sample -> spill -> restore -> map ...

But actually that did make me realize - I don't know if it's currently possible to fuse these stages? Because we would need to add a return value to return the sample along with the block.

Judging from the 10TB results, it looks like we'd save about 15% total run time on master through this fusion.

**Comment by ericl** [comment]
Yeah, we'd need to special case this for sure. The current fusion code would be discarding the blocks of the load stage.
