### ISSUE TITLE
[Core] k8s node silently disappears when out of disk

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#24292]
### What happened + What you expected to happen

**Bug:** When running a script that has a large amount of object spilling, if the disk runs out of space then Kubernetes will silently terminate the node. Autoscaling will kick in and replace the dead node. There is no indication that there was a failure due to disk space.

**Expected Behavior:** Ray should detect when the disk is running out of space and warn the user before the node disappears.

**Useful information:**  The main pain point about this is that there are no logs or other indication about the failure. Furthermore, disk usage metrics are not being tracked in the Ray Dashboard for k8s:
https://github.com/ray-project/ray/blob/d9d9fbb0441bf52c8bbd53bf67011ec3f77f5697/dashboard/modules/reporter/reporter_agent.py#L300-L304

### Versions / Dependencies

Ray 1.12.0
K8s GCP

### Reproduction script

The script I used looked something like:
```python
import gcsfs
import ray

files = "SOME_LARGE_GCS_DATASET"
ds = ray.data.read_json(files, filesystem=gcsfs.GCSFileSystem())
ds = ds.repartition(200)
```

Though there's probably an easier way to do this (e.g. creating a bunch of large objects and putting them in the object store).

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
Some ideas:

- Add size limit thing (or other solution)
- Updating documentation for Ray in these scenarios (K8s or otherwise)
- Nightly tests for out of disk.

**Comment by scv119** [comment]
One page design doc is needed.

**Comment by spolcyn** [comment]
@scv119 What was the resolution / recommended course of action for this?
