### ISSUE TITLE
[air] data loading and processing inside of trials causes resource contention 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#24304]
### What happened + What you expected to happen

`ray.init(num_cpus=4)` 

Running two xgboost trial each claiming two CPUs. Expect to run through completion.

However, the program hangs with 

```
(scheduler +17s) Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
```

It turns out data processing step is using CPUs not accounted for in the per trial request. 

This may hit our users as surprise. 

### Versions / Dependencies

master

### Reproduction script

```
from typing import Optional

from sklearn.datasets import load_breast_cancer
from sklearn.utils import shuffle

from ray import tune
from ray.data import from_pandas, read_datasource, Dataset, Datasource, ReadTask
from ray.data.block import BlockMetadata
from ray.ml.config import RunConfig
from ray.ml.examples.pytorch.torch_linear_example import train_func as linear_train_func
from ray.ml.train.integrations.torch import TorchTrainer
from ray.ml.train.integrations.xgboost import XGBoostTrainer
from ray.ml.train import Trainer
from ray.tune import Callback, TuneError
from ray.tune.cloud import TrialCheckpoint
from ray.tune.tune_config import TuneConfig
from ray.tune.tuner import Tuner
from ray.ml.preprocessors import StandardScaler




class TestDatasource(Datasource):
    def __init__(self, do_shuffle: bool):
        self._shuffle = do_shuffle

    def prepare_read(self, parallelism: int, **read_args):
        import pyarrow as pa

        def load_data():
            data_raw = load_breast_cancer(as_frame=True)
            dataset_df = data_raw["data"]
            dataset_df["target"] = data_raw["target"]
            if self._shuffle:
                dataset_df = shuffle(dataset_df)
            return [pa.Table.from_pandas(dataset_df)]

        meta = BlockMetadata(
            num_rows=None,
            size_bytes=None,
            schema=None,
            input_files=None,
            exec_stats=None,
        )
        return [ReadTask(load_data, meta)]


def gen_dataset_func(do_shuffle: Optional[bool] = False) -> Dataset:
    test_datasource = TestDatasource(do_shuffle)
    return read_datasource(test_datasource)



import ray
ray.init(num_cpus=4)

trainer = XGBoostTrainer(
    label_column="target",
    params={},
    datasets={"train": gen_dataset_func()},
)
prep_v1 = StandardScaler(["worst radius", "worst area"])
prep_v2 = StandardScaler(["worst concavity", "worst smoothness"])
param_space = {
    "scaling_config": {
        "num_workers": 1,
    },
    "preprocessor": tune.grid_search([prep_v1, prep_v2]),
    "datasets": {
        "train": gen_dataset_func(),
    },
    "params": {
        "objective": "binary:logistic",
        "tree_method": "approx",
        "eval_metric": ["logloss", "error"],
        "eta": tune.loguniform(1e-4, 1e-1),
        "subsample": tune.uniform(0.5, 1.0),
        "max_depth": tune.randint(1, 9),
    },
}
tuner = Tuner(
    trainable=trainer,
    run_config=RunConfig(name="test_tuner"),
    param_space=param_space,
    tune_config=TuneConfig(mode="min", metric="train-error"),
)
results = tuner.fit()


```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
@clarkzinzow @matthewdeng Can you help clarify what should be the expected behavior here?

**Comment by clarkzinzow** [comment]
@xwjiang2010 This is a known issue, captured here: https://github.com/ray-project/ray/issues/24206

Can you comment on that issue what the ideal behavior would be, here? Should there be an option to capture Datasets tasks in a parent placement group, an option to capture all Datasets tasks in a dedicated global placement group, or some other option?

**Comment by xwjiang2010** [comment]
@clarkzinzow 
We can talk more in the meeting next Monday. 
My understanding is accounting of resources is pretty core to Ray and it also hooks into auto scaling mechanisms. Placement Group is introduced in response to the exact deadlock situation that we are seeing here. 
Without proper accounting, the best we can do is ask user to over provision (in the case of static cluster) and change the autoscaling logic to have a few CPUs to spare here and there, which is pretty bad IMO.
As for the proposals, I don't have a great answer.
option1: If we dedicate the resources to each trial, currently these resources are only used at the very beginning of the trials, unless we are talking pipelined dataset + training. Seems a waste to me.
option2: It's unclear how much resources to allocate for this global dataset dedicated resource pool? For example, say I have 10 trials all started and waiting at data loading stage. If my global dataset resource pool can only do one data loading at a time; this would mean that my 10 trials are forced to go through a narrow bridge sequentially, which is bad.
