### ISSUE TITLE
[docs][rllib] Reorganize the RLlib docs Algorithms section

### ISSUE THREAD

**Issue by christy** [ray-project/ray#24347]
### Description

Proposed Re-grouping of Algorithms in Docs

1. Rename UCB -> LinUCB on the [algorithms doc page](https://docs.ray.io/en/master/rllib/rllib-algorithms.html#available-algorithms-overview)
2. Add a friendly list of algorithms on the github RLlib page itself's [README](https://github.com/ray-project/ray/tree/master/rllib)
3. Repeat same groupings on the [algorithms doc page](https://docs.ray.io/en/master/rllib/rllib-algorithms.html#available-algorithms-overview) as the [README](https://github.com/ray-project/ray/tree/master/rllib)
4. Add links that go from README listed algorithms to algorithms doc page

README Algo organization 
Offline RL (put Off-policy Eval here):  BC, DQN, DDPG, TD3, SAC, CQL,
Model-free RL (maybe split into off/on policy)
Model-based RL
Derivative-free Algos
RecSys and Bandits (or separate categories)
Games (especially AlphaZero, APPO, IMPALA, A2C, A3C goes here)

### Use case

People come to RLlib looking for combinations of Environment and Algorithms that might best work for their Use Case.  The goal of the re-org is to give people more guidance finding which algorithms might be worth a try.

The algorithms today are listed in docs in API format.  They are not listed at all on the github README.md for RLlib itself.

**Comment by sven1977** [comment]
Hey @christy , thanks for listing these enhancement suggestions! Please feel free to create any docs PRs for fixing these shortcomings (I think you already posted a few that are in review rn).
Great stuff!

**Comment by sven1977** [comment]
My suggestion for grouping our algos would be (only slight differences to your suggestion):

* Offline RL (put Off-policy Eval here): BC, MARWIL, CQL, OPE ("importance sampling" and "weighted importance sampling")
* Model-free RL (maybe split into off/on policy):
  * On-policy: APPO, PPO, IMPALA, A2C, A3C, PG
  * Off-policy: DQN, DDPG, TD3, SAC
* Model-based RL: MBMPO, Dreamer
* Derivative-free Algos: ES & ARS
* RecSys and Bandits (or separate categories): LinUCB, LinTS, SlateQ
* Multi-agent: QMIX, AlphaStar, MA-DDPG

NOTE: `Games (especially AlphaZero, goes here)`: I wouldn't separate these as these are mostly async on-policy algos (in the model-free category)
