### ISSUE TITLE
Improve the current ASV setup for monitoring performance regressions

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2435]
There is some initial work on asv tests (see https://github.com/ray-project/ray/blob/master/python/README-benchmarks.rst), which can already be used to generate a performance dashboard locally.

The following issues should be addressed:

- [ ] Put up a webserver that just displays the ASV dashboard
- [ ] Make it possible to see performance from different repos/branches

**Comment by robertnishihara** [comment]
Closing because we are no longer using ASV.
