### ISSUE TITLE
[rllib] Sample throughput count in async_samples_optimizer.py

### ISSUE THREAD

**Issue by michaelschaarschmidt** [ray-project/ray#2439]
Hi,

analogue to the fix of measuring samples throughput in https://github.com/ray-project/ray/commit/f31a6ca96510deb77117826437434da80e6df1f4

shouldn't https://github.com/ray-project/ray/blob/master/python/ray/rllib/optimizers/async_samples_optimizer.py#L231

```

        with self.timers["sample_processing"]:
            for ev, sample_batch in self.sample_tasks.completed():
                self._check_not_multiagent(sample_batch)
                sample_timesteps += self.sample_batch_size
```

also use the actual sample batch size as to not overestimate throughput, depending on the packing strategy in the sampler? 

Edit: Looking at the code more I realize that sample_batch is an object_id, and just the object_id is passed to the memory shard which inserts it, so the batch size is not available without reading from the object store?

**Comment by ericl** [comment]
Yeah, we would need to pass the size separately to avoid downloading the entire batch to the driver.

That said, I believe that the accounting here is correct. In a3c it was off because the wrong config var was checked.

**Comment by michaelschaarschmidt** [comment]
Great, thanks!
