### ISSUE TITLE
[Core][Workflow]ray.init(address="auto") won't pick up the storage that initialized in ray start

### ISSUE THREAD

**Issue by lchu-ibm** [ray-project/ray#24394]
### What happened + What you expected to happen

In the latest changes, I observed that we moved persistent storage from Ray Workflow to Ray Core (i.e. from `workflow.init()` to `ray.init()`).

When I have a cluster that is created with `ray start ... --storage my_storage`, I would expect I could do `ray.init(address="auto")` to connect to the cluster and use the storage specified there. However, I got: 
```
RuntimeError: No storage URI has been configured for the cluster. Specify a storage URI via ray.init(storage=<uri>)
```

So apparently it expects me to put the SAME storage in `ray.init()` as well.  (it has to be the same storage because only the one specified in `ray start` would have the _valid file to pass the validity check).  This seems to be a duplicated effort to put the same value here, and there is no easy way I can find for user to easily grab that value in the code before doing ray.init()

### Versions / Dependencies

.

### Reproduction script

start ray first:
`ray stop && ray start --storage file:///Users/lchu/workflow_data --head`

then in the code:
```
ray.init(address="auto")
# run workflow with above will have error: 
# RuntimeError: No storage URI has been configured for the cluster. Specify a storage URI via `ray.init(storage=<uri>)`


ray.init(address="auto", storage="xxx")
# run workflow with above would work, but how do we get the value 
# that specified in "ray start" to fill in the xxx here.

```

**Comment by iycheng** [comment]
@lchu-ibm I synced offline with @ericl 
The right behavior here should be that:

- if ray.init without storage config, it'll use the one from the cluster. If no cluster is given, it'll not setup storage.
- if it's called with storage config, it'll use that.

**Comment by iycheng** [comment]
To make things simple, we can utilize internal kv to set it up and fetch it later.

**Comment by suquark** [comment]
This is the same issue in https://github.com/ray-project/ray/pull/24401. I just made a workaround for that PR. Still need a systematic fix.

**Comment by lchu-ibm** [comment]
@iycheng 

> if ray.init without storage config, it'll use the one from the cluster. If no cluster is given, it'll not setup storage.

This should be easy, what we can do is:  when creating the cluster head, we push storage config to internal kv store so non-heads will fetch that value from kv store, exactly as you described.

> if it's called with storage config, it'll use that. 

I would like to clarify on this one.  I understand if it is called as the head, but how about non-heads? Say I have the following:
```
# create cluster head with:
# ray start --head storage="A"

# connect to the existing cluster
ray.init(address="auto", storage="B")
```

My thought is above setting in ray.init() with storage=B should be errored out, as it uses a different storage as the one specified in the cluster.

**Comment by lchu-ibm** [comment]
Another option is to give user the flexibility of "overwriting" a storage config from a non-head worker/node, so above storage=B would overwrite the storage=A rather than error out, and jobs submitted from that driver will use storage=B.  

Currently this is not possible because `create_valid_file()` is only done when creating head node so specifying new storage after the cluster is created (e.g. from the application driver) won't work as it won't pass `check_valid_file()`.  we can of course make some modifications to allow this to happen, but I feel this might need some careful thinking on the design..

**Comment by iycheng** [comment]
@lchu-ibm given that it's hard to support this, let's don't change the semantics since we are not very clear about the actual use case. Just throw an error is good enough.
