### ISSUE TITLE
[Core][CI] reduce the CI build time for mac

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#24407]
### What happened + What you expected to happen

Currently our CI pipeline takes 10 hours to finish, mostly due to mac related build. We believe there are several low hanging fruits to improve this. some ideas from a better target determinator, or we just increase the number of mac machines.

 @simon-mo and @krfricke might have some idea on how to improve this.

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by jianoaix** [comment]
Discussed with @simon-mo on this issue, the CI pipeline time is now down to about 3 hours, by bumping up the resource (which is still within the quota).

The approaches on the table:
- Further increasing the builders: we still have sufficient quota
- More precisely figure out what tests are affected and run only those tests (so decrease unit cost, ie. CI cost per commit): @mwtian had a PR pending on this https://github.com/ray-project/buildkite-ci-stack/pull/16
- Reduce the frequency to run CI for MacOS (so decrease number of units, ie. CI invocations)

**Comment by mwtian** [comment]
PR to prune macos builds in CI has merged.

**Comment by mwtian** [comment]
I don't see much backlog for MacOS builds now. Closing.
