### ISSUE TITLE
[Docs] Dark mode theme for code snippets and output 

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#24425]
### Description

TensorFlow docs has a dark mode theme, which allows easier visibility for text (light), code snippet (dark), and output (in-between). This is something we can consider.

E.g. https://www.tensorflow.org/guide/data

![Screen Shot 2022-05-02 at 9 43 25 PM](https://user-images.githubusercontent.com/10713559/166405497-47805821-1742-4e12-8fbd-aeec02569923.png)

### Use case

Better UX for our docs

**Comment by maxpumperla** [comment]
@zhe-thoughts I researched this a bit and e.g. the "Furo" Sphinx theme supports switching to dark mode out of the box (see screenshot below).

By doing so I learnt that the theme underlying ours (pydata theme) now has dark mode as well, so I have high hopes that this might be propagated to our "book" theme

![Screenshot 2022-05-13 at 12 04 29](https://user-images.githubusercontent.com/3462566/168850331-9f80a09f-3314-4e31-8434-b9f48ad137b2.png)

**Comment by psytron** [comment]
Dark mode for dashboard too! :)
