### ISSUE TITLE
[tune] Document Tune checkpoint concept properly 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#24426]
### What happened + What you expected to happen

Checkpoint is a super loaded term. And it's not clear to our user what each type of checkpoint is. We should document this properly.

See context here: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1651544792830879

### Versions / Dependencies

Master

### Reproduction script

NA

### Issue Severity

Low: It annoys or frustrates me.

**Comment by maxpumperla** [comment]
@xwjiang2010 like this https://docs.ray.io/en/latest/tune/tutorials/tune-checkpoints.html or a more general page about the topic?

**Comment by xwjiang2010** [comment]
Hi @maxpumperla 
The user who asked the question was actually referring to this page. The confusion is around different types of checkpoints: trial v.s. experiment state and what each one is for. The page you are linking is more advanced - the next step further to zoom into trial checkpoint. 
See here for more context: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1651544792830879
