### ISSUE TITLE
[rllib] Evolution Strategies / ARS should support multi-agent

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2444]
### Describe the problem
Currently ES and ARS are single-agent only, since they hasn't been refactored to use the common PolicyEvaluator for sampling.

**Comment by cathywu** [comment]
I'm curious if there are development plans for this task / how one may get started with implementing it? ES / ARS are the best performing methods for some or our traffic tasks (in the single-agent setting), so we would love to test out multi-agent versions. 

CC @ericl @richardliaw @eugenevinitsky

**Comment by ericl** [comment]
Hey @cathywu , I think the main thing is having the Worker class in ES/ARS create a RolloutWorker object locally, and use worker.sample() instead of its own custom `policies.rollout` function called inside `self.rollout`. The RolloutWorker will return the multi-agent rollout batch and the rest of the ES algorithm can be adapted to handle that for optimization.

It's a bit more refactoring than it sounds, since RolloutWorker requires you pass in policies conforming to the `rllib.policy.Policy` interface (instead of the custom GenericPolicy class in es/policies.py).

I think the main difference between ES/ARS and the rest of the RLlib algorithms is that while most algorithms learn on batches of experiences, ES learns on tuples of (noise_indices, noisy_returns). Let me know if this makes sense; also happy to schedule some time to discuss.

**Comment by antoine-galataud** [comment]
An other positive side effect of such a refactoring would be to support custom metrics in ARS and ES. For now they aren't.

**Comment by simonsays1980** [comment]
@gjoliver Does it make sense to look into this before the `Connector`s are implemented?

**Comment by gjoliver** [comment]
feel like we should just bring these agents up to spec while we clean up the policy/model related things in preparation for connector refactoring.

**Comment by simonsays1980** [comment]
> feel like we should just bring these agents up to spec while we clean up the policy/model related things in preparation for connector refactoring.

@gjoliver Had the same feeling here. Thanks for your opinion.

**Comment by RocketRider** [comment]
@avnishn 
Is this issue resolved?
https://docs.ray.io/en/master/rllib/rllib-algorithms.html# still states ES does not support multi agent
