### ISSUE TITLE
[data] Add dataset.random_sample() API

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#24449]
### Description

Per https://discuss.ray.io/t/how-do-i-sample-from-a-ray-datasets/5308, we should add a `random_sample(N)` API that returns N records from a Dataset. This can be implemented via a `map_batches()` followed by a take().

cc @simon-mo @clarkzinzow 

### Use case

Random sample is useful for a variety of scenarios, including creating training batches, and downsampling the dataset for faster analysis / testing.

**Comment by xiurobert** [comment]
I'd like to give this a shot! I'm having a bit of trouble setting up my development environment on macOS though.

**Comment by xiurobert** [comment]
Would adding in a feature to sample a fraction (as referenced in the forum) be useful too?

**Comment by simon-mo** [comment]
@xiurobert thanks for picking it up. Out of curiosity, how did you find this issue?

**Comment by xiurobert** [comment]
> @xiurobert thanks for picking it up. Out of curiosity, how did you find this issue? 

I was randomly browsing GitHub out of boredom and this repo was recommended to me.

**Comment by xiurobert** [comment]
Now that the random_sample API is added, can this issue be closed?
