### ISSUE TITLE
[Jobs] No GPUs available in driver

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#24455]
### What happened + What you expected to happen

I am running this simple script on a node with GPUs.

```python
import ray
import torch

ray.init()
assert torch.cuda.is_available()
```

When run directly on the node, the assert statement passes. When running via Job submission, the assert statement fails. I expect the script to also pass when running via Job submission.

### Versions / Dependencies

Ray 1.12

### Reproduction script

```python
import ray
import torch

ray.init()
assert torch.cuda.is_available()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by architkulkarni** [comment]
@amogkam Thanks for filing this, do you already have a good sense of which configurations need to be passed to the job supervisor actor?  Is it just an environment variable? Not too familiar with `cuda` or how to make GPUs available.

**Comment by architkulkarni** [comment]
Adding a related note from @edoakes so we can track it here: "ideally we could set a resource request for the driver"

**Comment by amogkam** [comment]
What do you guys think about setting this env var for just the job supervisor actor so that it doesn't try to manage GPU resources? https://github.com/ray-project/ray/pull/17847

**Comment by architkulkarni** [comment]
@amogkam I haven't used that env var before but it sounds reasonable to me.  To be clear, we should set `RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=1` in the job supervisor actor, so that setting `CUDA_VISIBLE_DEVICES` is disabled, so that `cuda` becomes available?  It's a little confusing.

**Comment by amogkam** [comment]
Yep that's exactly right.

When you create an actor or task with `num_gpus=1` or whatever, it changes the `CUDA_VISIBLE_DEVICES` environment variable. Any GPU device ids that are not specified in this env var will be effectively hidden from torch, tensorflow, etc.

If we just don't set the env var in the job supervisor actor, then using Ray jobs won't change the behavior when compared to running the script directly on the head node.

**Comment by edoakes** [comment]
@amogkam assuming this will not be inherited by the rest of the Ray job it sounds like a good idea to me (more similar to running something directly on the head node).

@architkulkarni I think we should file a small change to do this and then remove it if/once we support resource requirements for the driver.

**Comment by amogkam** [comment]
Ah @edoakes-- that's a good point, I think it will affect all actors in the Job. If it's put in the runtime env of just the supervisor actor, will it be inherited by sub actors?

**Comment by architkulkarni** [comment]
@amogkam we can put it in the runtime env, or we can just set it manually, e.g. https://github.com/ray-project/ray/blob/master/dashboard/modules/job/job_manager.py#L222

But I think in either case, the environment variable will persist for child actors.  

Maybe one way around it is to set `RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=0` (note: 0) in the runtime env, while also manually setting it to `1` in the actor as above.  That way it'll be `0` in all sub tasks and actors, but `1` in the driver script.  Seems like a hack though...

**Comment by edoakes** [comment]
@architkulkarni I think we can set it in the runtime_env of the supervisor actor, then remove it from the runtime_env that's set for the driver. That should do it.

**Comment by edoakes** [comment]
@architkulkarni made a quick PR w/ a test to verify that it isn't set for child tasks
