### ISSUE TITLE
[RL Lib] Graceful handle of GRPC connection reset. 

### ISSUE THREAD

**Issue by ZhijieWang** [ray-project/ray#24466]
### What happened + What you expected to happen

RL Lib rollout worker unable to recover from GRPC error. Detail in here. https://github.com/anyscale/product/issues/10871
```
File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1651143558.130928005","description":"Error received from peer ipv4:10.96.58.42:50051","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Connection reset by peer","grpc_status":14}"
```

### Versions / Dependencies

Ray 1.12

### Reproduction script

https://github.com/anyscale/product/issues/10871

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ZhijieWang** [comment]
OSS team, please consider this as P1. I talked with @zhe-thoughts . @richardliaw  can i get your team to triage this?

**Comment by rkooo567** [comment]
@gjoliver is this something that should be handled by the core? (core side raising a certain exception on this network failures?) Or is the issue from out of band network communication from ray core?

**Comment by gjoliver** [comment]
I think this should be handled by core actually.
we don't do any gRPC communication ourselves in RLlib.

**Comment by ZhijieWang** [comment]
@rkooo567 Full stack trace here https://github.com/anyscale/product/issues/10871

**Comment by rkooo567** [comment]
Hmm looking at the stacktrace, the error seems to be from their application communication layer (`status = self.stub.IsGameReady(self.no_parameters)`). @gjoliver can you verify this? Does it mean it is not something core should handle?

**Comment by ZhijieWang** [comment]
@gjoliver @rkooo567  i don't have the code. But if we can determine the GRPC connection is not on our side, we can get back to Riot team and close this issue.

**Comment by scv119** [comment]
replied in the Anyscale issue.
