### ISSUE TITLE
Core - lack of simple way to redirect output to custom file

### ISSUE THREAD

**Issue by YoelShoshan** [ray-project/ray#24460]
### Description

It would be extremely useful if there was a simple way to redirect all remote job output into a custom file.

I've searched the documentation and available discussions online, and I did not encounter any solution that I believe is good enough.

The only solutions I've seen involve python logging (```import python logging```), which is limited in multiple ways:
1. It does not capture output from non-python code that is triggered from python (as many useful libraries are internally in, for example, cpp)
2. It requires a change to your python code, and ideally a solution that requires zero code is preffered

I've found a solution for this and creating a PR now.
The basic idea is to utilize screen custom args for this purpose, and allow ray users to provide those custom args when calling "ray submit ..."

when the PR will be merged, the user will be able to do:

```bash
ray submit some_cluster_config.yaml example_runnable_script.py --screen --extra-screen-args "-Logfile /gpfs/usr/someone/ray/output_log.txt"
```

and have both a screen session and also all of the output redirected to the custom file. It provides even stronger flexibility, as the user can provide a custom name to the screen session etc.

### Use case

Apart from the general flexibility of redirecting output to custom files (which IMHO is a must),
an example specific scenario is the following:

In machine learning, it's very useful to have session directories in which all of the data/files that are related to a certain training session are kept.
For example - model checkpoints, configurations etc. Storing there also the log file of the training session (which may take weeks!) is super helpful for proper organization and being able to easily retrospective examine such logs.

**Comment by jjyao** [comment]
Hi @YoelShoshan could you provide a descriptive title? Thanks!

**Comment by YoelShoshan** [comment]
> Hi @YoelShoshan could you provide a descriptive title? Thanks!

Sure - done :)
