### ISSUE TITLE
[Serve] [Deployment Graph] Always use async handle for executor

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#24474]
### Description

We're currently returning `RayServeSyncHandle` by default when we try to get the deployment handle for executor. See `deployment_node.py`, `deployment_method_node.py`, `deployment_function_node.py`.

Given the deployment handle is returned by us, in order to further improve performance we can default to the async version and implement an async executor to empower the `_execute_impl`.

Code pointer: https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/serve/pipeline/deployment_node.py?L122:18

**Comment by hora-anyscale** [comment]
Per Triage Sync: This is implemented, but instead of 'always' it's a user config.

cc: @sihanwang41
