### ISSUE TITLE
[docs] Links in ipynb examples are not formatted correctly

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24472]
### What happened + What you expected to happen

Seems to be using .rst link format but the source is markdown, so the link doesn't appear correctly on the docs page:

[Example source](https://github.com/ray-project/ray/blob/master/doc/source/data/examples/big_data_ingestion.ipynb) gets rendered as:

![Screenshot from 2022-05-04 12-02-37](https://user-images.githubusercontent.com/2560516/166807443-2e4fb212-4da5-4c82-ae12-040d89f4561d.png)

### Versions / Dependencies

2.0dev

### Reproduction script

none, see above example

**Comment by maxpumperla** [comment]
@stephanie-wang fixed on master
