### ISSUE TITLE
[Client] Chunk ClientTask's

### ISSUE THREAD

**Issue by ckw017** [ray-project/ray#24482]
### Description

If a ray.remote in client mode captures over 2GiB of dependencies, it will fail. We could work around this by chunking client task's into multiple messages.

**Comment by ckw017** [comment]
Alternative route: under the hood just ray.put all of the arguments to the task and convert to object refs instead (or detect arguments that are too large for serialization)

**Comment by mwtian** [comment]
> Alternative route: under the hood just ray.put all of the arguments to the task and convert to object refs instead (or detect arguments that are too large for serialization)

One thing to make sure for the `ray.put()` approach is that arguments object lifetime should be similar to passing arguments as values.
