### ISSUE TITLE
[Xray] ray.wait() potential deadlock

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#2448]
There seems to be a deadlock in `ray.wait(p, num_returns=len(p))`.  The script makes some progress in the beginning, but no further reports are printed out:
```0 tasks done, timestamp 1532032279.9039423
Attaching to process 20544

10000 tasks done, timestamp 1532032290.3010979
```

I've tried a few times and the symptom is the same: <=10k tasks finished, then no further progress is reported.

My script is at (some top/psrecord monitoring is non-consequential): https://gist.github.com/concretevitamin/013cec5a08ed65e75af96d6b3163c414 /

**Comment by robertnishihara** [comment]
I tried starting Python with `RAY_USE_XRAY=1 ipython` and then running a simplified version

```python
import ray

ray.init()

@ray.remote
def f():
    return 1

for i in range(1000000):
    print(i)
    batch = [f.remote() for _ in range(1000)]
    ray.wait(batch, num_returns=len(batch))
```

I haven't been able to reproduce the error so far (after letting the script run for several minutes). How long does it take to appear?

**Comment by concretevitamin** [comment]
Pretty soon for me.  Can you make the func return nothing (None), and compile and run with the gcs flag as well?

**Comment by robertnishihara** [comment]
Changing the return to `None` didn't make a difference for me. I'll try with the new GCS flag (probably tomorrow).

**Comment by robertnishihara** [comment]
Ok, I tried with the new GCS (both compilation and runtime) and still couldn't reproduce the error.

In your example, does `ray.wait` fail on the first try, or do some of the calls succeed?
