### ISSUE TITLE
[RLlib] The wrong simulation environment is configured in test code of the DDPG algorithm

### ISSUE THREAD

**Issue by fantow** [ray-project/ray#24496]
### What happened + What you expected to happen

When I execute the test code of the DDPG algorithm,program prompts the following error message:
  ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=5884, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000000E8DB675D08>)
KeyError: 'Pendulum-v0'.
![ray rllib](https://user-images.githubusercontent.com/18530950/166871269-14fdb871-64a8-4df9-9ded-1777f0af7bdb.png)

**But when I change the environment to 'Pendulum-v1', the program runs fine.Maybe it's a version legacy issue.**
**If this is a necessary issue, May I submit a PR to fix it?**

### Versions / Dependencies

Ray 1.12.0
Python 3.7

### Reproduction script

    def test_ddpg_compilation(self):
        print(ray.__version__)
        """Test whether a DDPGTrainer can be built with both frameworks."""
        config = ddpg.DEFAULT_CONFIG.copy()
        config["seed"] = 42
        config["num_workers"] = 1
        config["num_envs_per_worker"] = 2
        config["learning_starts"] = 0
        config["exploration_config"]["random_timesteps"] = 100
        num_iterations = 1

        # Test against all frameworks.
        for _ in framework_iterator(config):
            **trainer = ddpg.DDPGTrainer(config=config, env="Pendulum-v0")**
            for i in range(num_iterations):
                results = trainer.train()
                check_train_results(results)
                print(results)
            check_compute_single_action(trainer)
            # Ensure apply_gradient_fn is being called and updating global_step
            if config["framework"] == "tf":
                a = trainer.get_policy().global_step.eval(
                    trainer.get_policy().get_session())
            else:
                a = trainer.get_policy().global_step
            check(a, 500)
            trainer.stop()

### Issue Severity

High: It blocks me from completing my task.

**Comment by maxpumperla** [comment]
@fantow what you're saying is correct, it's fixed on master:

https://github.com/ray-project/ray/blob/master/rllib/agents/ddpg/tests/test_ddpg.py#L48

**Comment by fantow** [comment]
> @fantow what you're saying is correct, it's fixed on master:
> 
> https://github.com/ray-project/ray/blob/master/rllib/agents/ddpg/tests/test_ddpg.py#L48

Thanks,I didn't pay attention to the changes in the master branch.
