### ISSUE TITLE
[Ray doc] Cannot easily see/find all the search results using search on ray doc site

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#24519]
### What happened + What you expected to happen

<img width="1059" alt="Screen Shot 2022-05-03 at 6 29 38 PM" src="https://user-images.githubusercontent.com/9677264/167010731-badbd294-4277-4bb1-8589-fcae3bf7c617.png">
When searching, I type some queries and see the top results instantly which is great.
If I want to view more results/all results, I try to press "enter" on my keyboard but it only sends me to the first result. I don't have a way to see all search results.

### Versions / Dependencies

1.12 doc site.

### Reproduction script

Search in 1.12 doc site.

### Issue Severity

High: It blocks me from completing my task.

**Comment by scottsun94** [comment]
Asked in the slack channel. Some users do express the same need of viewing the all results.

**Comment by stephanie-wang** [comment]
Just want to +1 this! It's actually quite an obstacle because there is just no way to find the results that you need if they don't appear in the top few.

**Comment by matthewdeng** [comment]
One workaround I found is to directly go to https://docs.ray.io/en/latest/search.html

**Comment by stephanie-wang** [comment]
Hmm I think there is still an issue here. I just tried it on the master version of docs
![Screenshot from 2022-05-12 12-07-55](https://user-images.githubusercontent.com/2560516/168150268-2bba9d3e-40bc-4578-9193-0120a593c223.png)
.

**Comment by stephanie-wang** [comment]
Oh hmm may have just been a caching issue on my laptop. Never mind!
