### ISSUE TITLE
[Docs] Bug compiling documentation locally

### ISSUE THREAD

**Issue by FedericoGarza** [ray-project/ray#24520]
### What happened + What you expected to happen

1. I'm getting the following error trying to compile the docs locally.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/10517170/167014459-a36711a3-a1c4-4214-916c-347f849e130a.png">

2. Display docs locally.

### Versions / Dependencies

Python: 3.7
OS: macOS Monterey

### Reproduction script

```bash
gh repo clone ray-project/ray
conda create python=3.7 -n ray
conda activate ray
cd doc
pip install -r requirements-doc.txt
make html && open _build/html/index.html
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by maxpumperla** [comment]
@FedericoGarza seems like you have to install `libomp`. Can you please give that a shot? If it works, we should amend the docs accordingly.

**Comment by DmitriGekhtman** [comment]
I've also never been able to compile docs locally with the make command.
To work around errors of type "Warning, treated as error" I [delete the -W flag in the relevant spot in the Makefile](https://github.com/ray-project/ray/blob/f8b0ab7e78246e4dddf6c0095f3f7a5e409988ba/doc/Makefile#L55).

**Comment by DmitriGekhtman** [comment]
Currently, I get
```
Warning, treated as error:
multiple files found for the document "auto_examples/plot_hyperparameter": ['auto_examples/plot_hyperparameter.ipynb', 'auto_examples/plot_hyperparameter.rst', 'auto_examples/plot_hyperparameter.py']
Use '/Users/dmitrigekhtman/code/ray/doc/source/auto_examples/plot_hyperparameter.rst' for the build.
```
