### ISSUE TITLE
[RLlib] Curiosity implementation bug + Patch

### ISSUE THREAD

**Issue by mavroudisv** [ray-project/ray#24558]
### What happened + What you expected to happen

Hi, 

I have been facing an issue when using PPO with curiosity and Torch, on a machine with at least one available GPU. In particular:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

I have traced the error to lines (358-359):

```
torch.from_numpy(sample_batch[SampleBatch.OBS]),
torch.from_numpy(sample_batch[SampleBatch.NEXT_OBS]),
```

as shown here:
https://docs.ray.io/en/master/_modules/ray/rllib/utils/exploration/curiosity.html

My proposed fix is:

```
torch.from_numpy(sample_batch[SampleBatch.OBS]).to(policy.device),
torch.from_numpy(sample_batch[SampleBatch.NEXT_OBS]).to(policy.device),
```

### Versions / Dependencies

- Ray 2.0.0.dev0
- Framework: Torch 
- At least one GPU
- Curiosity enabled (PPOTrainer)

### Reproduction script

After unzipping, to reproduce the error please run: `crash.py`

The `curiosity_patched.py` is the patched version of the curiosity script as it appears [here]*(https://docs.ray.io/en/master/_modules/ray/rllib/utils/exploration/curiosity.html).

[curiosity_bug.zip](https://github.com/ray-project/ray/files/8643706/curiosity_bug.zip)

 *I'm explicitly importing Curiosity instead of using 'Curiosity', but this shouldn't matter.

### Patch

Assuming the error is reproducible and it's not on my end. I'd be keen to make a pull request to fix it. I have already included a fix in file `fixed.py`.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simonsays1980** [comment]
@mavroudisv Did you use in your experiment `num_workers>0`? As `Curiosity` in RLlib is up to now (regrettably) only synchronuously possible.

**Comment by mavroudisv** [comment]
Yes, I did. You're right that this is a common mistake but thankfully the error message in that case is clear!

**Comment by kouroshHakha** [comment]
@sven1977 I think the fix should be more fundamental that this local `.to(device)` solution. SampleBatch should have already been on the correct device ideally.
