### ISSUE TITLE
[Serve] `test_model_wrappers.py` not ran in CI

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#24550]
### What happened + What you expected to happen

This script doesn't have a `pytest.main` block so it was not properly tested in CI.

### Versions / Dependencies

master

### Reproduction script

... and it is failing.

**Comment by hora-anyscale** [comment]
Per Triage Sync: 'test_model_wrappers.py' does not exist anymore, closing as stale.

cc: @sihanwang41
