### ISSUE TITLE
Hello,I have done as the solution,but it has other problem shown in picture.can you help me,thank you!

### ISSUE THREAD

**Issue by flomok** [ray-project/ray#24568]
Hello, 

Your solution is working until I work with huggingface. It looks like the problem is in python 3.7, however  when I install python 3.8 in my colab:

```
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py38" --user
```
It does not recognize `transformers` , that I already install:

![ray_error](https://user-images.githubusercontent.com/53188008/164421186-365c14d0-a8f7-452f-95ce-ced284bec2a9.PNG)

Do you have any advice? 

Thank you so much.

_Originally posted by @JessicaLopezEspejel in https://github.com/ray-project/ray/issues/23951#issuecomment-1104932959_

**Comment by flomok** [comment]
![image](https://user-images.githubusercontent.com/88573497/167242903-67fb2d4c-9dcf-4036-af6b-bc2ff89245f1.png)

**Comment by xiurobert** [comment]
Hey so turns out this was fixed in the latest release.
