### ISSUE TITLE
error: Object created by ray.put could not be reconstructed.  

### ISSUE THREAD

**Issue by LuckyZXL2016** [ray-project/ray#2458]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5
- **Python version**: 3.6

### Describe the problem
I first applied the Ray to my project. The following error occurred and I don't know how to solve it. 

### Source code / logs
```python
import ray
ray.init(object_store_memory=1000) # only allows one int
a = ray.put(1)
ray.worker.global_worker.plasma_client.evict(516) # should return 516
ray.get(a)
```

Here is the result printed:
`The task with ID 4a82e1d5445d3c9cc0b5ebb9640218e6f7db2ab3 is a driver task and so the object created by ray.put could not be reconstructed. 
Suppressing duplicate error message.  
Suppressing duplicate error message. 
Suppressing duplicate error message. 
Suppressing duplicate error message.`

**Comment by richardliaw** [comment]
Do you know how far the program runs until this message starts occurring? Is it in `item_use_gamma`?

**Comment by ZzXxL1994** [comment]
But if I change _ray.init(object_store_memory=1000)_ to _ray.init()_, then the error will not occur. So why is this happening?

**Comment by robertnishihara** [comment]
@ZzXxL1994 `1000` is way too small because it is the quantity in bytes (we should clarify this and probably disallow numbers that are so small).
