### ISSUE TITLE
[air] Result dict has no key: training_iteration.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#24593]
### What happened + What you expected to happen

Dump the stack trace here first. Will add more details later.

```
2022-05-08 17:50:02,723	ERROR checkpoint_manager.py:180 -- Result dict has no key: training_iteration. checkpoint_score_attr must be set to a key in the result dict.
Trial TensorflowTrainer_a748c_00000 completed. Last result:
== Status ==
Current time: 2022-05-08 17:50:02 (running for 00:02:10.89)
Memory usage on this node: 40.5/64.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/16 CPUs, 0/0 GPUs, 0.0/26.08 GiB heap, 0.0/2.0 GiB objects
Result logdir: /Users/xwjiang/ray_results/TensorflowTrainer_2022-05-08_17-47-50
Number of trials: 1/1 (1 TERMINATED)
+-------------------------------+------------+-----------------+
| Trial name                    | status     | loc             |
|-------------------------------+------------+-----------------|
| TensorflowTrainer_a748c_00000 | TERMINATED | 127.0.0.1:37982 |
+-------------------------------+------------+-----------------+

```

### Versions / Dependencies

Master

### Reproduction script

```
from ray.ml.train.integrations.torch import TorchTrainer
import ray.train as train
import torch.nn as nn


def train_loop_per_worker():
    train.save_checkpoint(model=nn.Identity().state_dict())


trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config={"num_workers": 2}
)
result = trainer.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
The same thing also showed up in shopify's session. Looking into the issue.

**Comment by bveeramani** [comment]
Added a minimal repro script

**Comment by matthewdeng** [comment]
@xwjiang2010 can you take a look at this?

**Comment by xwjiang2010** [comment]
Tried the updated script - everything is working fine. Closing out...

```
from ray.train.torch import TorchTrainer
from ray.air import session
from ray.air.config import ScalingConfig
from ray.air.checkpoint import Checkpoint
import torch.nn as nn


def train_loop_per_worker():
    checkpoint = dict(model=nn.Identity().state_dict())
    session.report({"iter": 1}, checkpoint=Checkpoint.from_dict(checkpoint))


trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config=ScalingConfig(num_workers=2)
)
result = trainer.fit()
```

**Comment by matthewdeng** [comment]
Nice!

For context if anyone else runs into this, the `train.save_checkpoint` function has been replaced with `session.report` which now unifies reporting and checkpointing.

**Comment by edoakes** [comment]
I am still seeing I am seeing this error message in the following example on master (commit `6c10f3c7b983fc21c3df51be2c3ad0d2ffe8bea9`):
https://maxpumperla.com/learning_ray/ch_07_train/

Error message:
`2022-12-08 11:33:47,700 ERROR checkpoint_manager.py:327 -- Result dict has no key: training_iteration. checkpoint_score_attr must be set to a key in the result dict. Valid keys are: ['trial_id', 'experiment_id', 'date', 'timestamp', 'pid', 'hostname', 'node_ip', 'done']`

I believe I'm using the most recent API (`session.report`)

**Comment by Yard1** [comment]
Closing as neither me nor Edward can reproduce it again.

FYI this error means that trials have not reported even once, which usually means the real error will be in the Tune output above.

**Comment by maxpumperla** [comment]
@Yard1 @edoakes thanks for following up on that. Shouldn't we somehow catch this a little earlier then and surface a better error message?

**Comment by Yard1** [comment]
The actual error message would be in the stack trace above the checkpoint manager error
