### ISSUE TITLE
confuse about the performance

### ISSUE THREAD

**Issue by mx8435** [ray-project/ray#2460]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.0
- **Python version**: 2.7.15
- **Exact command to reproduce**:

### Describe the problem

I have ran test on Ray to test its performance. It cost almost 42 secs to synchronous transfer 100k times int data. The test is run in local mode. It is too slow ? While the benchmarks in paper show that it can reach 18k IOPS in single thread (transfer 1k data each time), to write data to plasma object store. Can you show the detail of benchmark code ? Thanks a lot.

![image](https://user-images.githubusercontent.com/8417466/43119389-bf83e01a-8f48-11e8-8622-64e456e0bf8e.png)

### Source code / logs

![image](https://user-images.githubusercontent.com/8417466/43119757-48cfd166-8f4a-11e8-9419-893ac200a342.png)

**Comment by zhijunfu** [comment]
The plasma store itself is quite fast. If you write 100K ints to store, and then read them out from store, it won't take more than a few seconds.  The script is essentially doing 100K remote calls, which involves task scheduling, forwarding, updating tasks data to redis .etc. Serialization & deserialization in python also can be time consuming. These all take time.

**Comment by robertnishihara** [comment]
Closing because this is from a while ago. There are still some performance optimizations that can be done with the store.
