### ISSUE TITLE
[Core] clarify that num_cpus are logical not physical in doc

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#24626]
### Description

when specifying resources requirement link num_cpus, user often confused this with concurrent tasks or phyisical cpu usgage

> Additional question - is that possible that worker will get more tasks than --num-cpus ?  I want to understand if its only the UX issue, or also a core issue?
> If I use a docker and give it x cpus, and also bound that to the --num-cpus in command line, i must be sure that the docker will get maximum x tasks
> Is that the case?
> 

we should do a better job there.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @jjyao - could you please confirm this was done?

**Comment by jjyao** [comment]
Not yet. It will be done as part of 2.2 core doc revamp.
