### ISSUE TITLE
Improve argument document of `address` and `port`

### ISSUE THREAD

**Issue by tisonkun** [ray-project/ray#24634]
_Originally posted by @tisonkun in https://github.com/ray-project/ray/issues/17400#issuecomment-1120759243_

Current, the help information of `ray start --help` shows:

```
  --address TEXT                  the address to use for Ray
  --port INTEGER                  the port of the head ray process. If not
                                  provided, defaults to 6379; if port is set
                                  to 0, we will allocate an available port.
```

It's confused by stating `use for Ray` since a user cannot understand what kind of usage is here.

Also, it would be better to add examples / demos on docsite for playing with such arguments and start some typical deployment. Such as with external object store.

**Comment by WangTaoTheTonic** [comment]
Hi, which release do you use?

**Comment by tisonkun** [comment]
```
$ ray --version
ray, version 1.12.0
```
