### ISSUE TITLE
CI failing to build window wheels

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#24653]
See the "bk://:windows: Wheels" at https://flakey-tests.ray.io/#owner=infra for details.

It looks some dependency issue from the logs:

+ popd
--
  | /c/Install/ray
  | + cd /c/Install/ray/python/../python
  | + /c/Install/ray/python/../ci/keep_alive pip install -v -e .
  | Using pip 21.2.2 from C:\Miniconda3\lib\site-packages\pip (python 3.6)
  | Obtaining file:///C:/Install/ray/python
  | Running command python setup.py egg_info
  | running egg_info
  | creating C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info
  | writing C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info\PKG-INFO
  | writing dependency_links to C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info\dependency_links.txt
  | writing entry points to C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info\entry_points.txt
  | writing requirements to C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info\requires.txt
  | writing top-level names to C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-pip-egg-info-kt8jh3rl\ray.egg-info\top_level.txt
  | Traceback (most recent call last):
  | File "C:\Miniconda3\lib\site-packages\importlib_metadata\_compat.py", line 9, in <module>
  | from typing import Protocol
  | ImportError: cannot import name 'Protocol'
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "<string>", line 1, in <module>
  | File "C:\Install\ray\python\setup.py", line 752, in <module>
  | ) if __name__ == "__main__" else None
  | File "C:\Miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
  | return distutils.core.setup(**attrs)
  | File "C:\Miniconda3\lib\distutils\core.py", line 148, in setup
  | dist.run_commands()
  | File "C:\Miniconda3\lib\distutils\dist.py", line 955, in run_commands
  | self.run_command(cmd)
  | File "C:\Miniconda3\lib\distutils\dist.py", line 974, in run_command
  | cmd_obj.run()
  | File "C:\Miniconda3\lib\site-packages\setuptools\command\egg_info.py", line 291, in run
  | writer = ep.resolve()
  | File "C:\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
  | module = __import__(self.module_name, fromlist=['__name__'], level=0)
  | File "C:\Miniconda3\lib\site-packages\pbr\pbr_json.py", line 19, in <module>
  | from pbr import git
  | File "C:\Miniconda3\lib\site-packages\pbr\git.py", line 31, in <module>
  | from pbr import version
  | File "C:\Miniconda3\lib\site-packages\pbr\version.py", line 26, in <module>
  | import importlib_metadata
  | File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 17, in <module>
  | from . import _adapters, _meta
  | File "C:\Miniconda3\lib\site-packages\importlib_metadata\_meta.py", line 1, in <module>
  | from ._compat import Protocol
  | File "C:\Miniconda3\lib\site-packages\importlib_metadata\_compat.py", line 11, in <module>
  | from typing_extensions import Protocol  # type: ignore
  | File "C:\Miniconda3\lib\site-packages\typing_extensions.py", line 159, in <module>
  | class _FinalForm(typing._SpecialForm, _root=True):
  | AttributeError: module 'typing' has no attribute '_SpecialForm'

**Comment by scv119** [comment]
@jianoaix can you try to upgrade python to 3.6.2?

**Comment by scv119** [comment]
https://stackoverflow.com/questions/67569038/flask-attributeerror-on-import-module-typing-has-no-attribute-noreturn/67857937#67857937

**Comment by scv119** [comment]
https://pypi.org/project/pbr/#history looks pbr had a release at May 5th. It showed up in the stack trace and that's when this failure happens.

**Comment by jianoaix** [comment]
Thanks Chen, nice catch the change of pbr, the timeline matches well. It looks we don't directly depend on pbr. It might be indirectly via setuptools.

For Python, it's already python-3.6.13 (according to https://buildkite.com/ray-project/ray-builders-branch/builds/7441#bd5b2603-29b6-45b7-91e6-0bd4ec09bf14)

**Comment by mattip** [comment]
Can we drop Python3.6? It reached EOL in Dec 2021, 4 months ago.

**Comment by mattip** [comment]
Does ray have a declared python version support policy?

**Comment by jianoaix** [comment]
I tried pinning setuptools to a version used in MacOS, and it seems work: https://github.com/ray-project/ray/pull/24699

Dropping 3.6 sounds good to me. @zhe-thoughts on the Python version support lifecycle.

If that's more risky to change, to unbreak CI, I think we can just pin setuptools for now.

**Comment by zhe-thoughts** [comment]
Seems there are still a number of companies using Ray on Python 3.6. So I don't think it can be dropped as of now. cc @pcmoritz to confirm this

**Comment by pcmoritz** [comment]
We indeed still have a large number of 3.6 downloads and some large users on 3.6, so I don't think we can drop it at this point. However, 3.6 is definitely heading towards the end -- TensorFlow and PyTorch are already dropping building wheels for 3.6 in their recent releases.
