### ISSUE TITLE
[Core] Suppress `ray.cancel` stderr noise from `KeyboardInterrupt`

### ISSUE THREAD

**Issue by wmayner** [ray-project/ray#24658]
### Description

`ray.cancel` is currently quite noisy; the implementation seems to send a `SIGTERM` signal, which by default is passed back to the driver's stderr as a `KeyboardInterrupt`. There are use cases where `ray.cancel` is called routinely as part of an algorithm, and thus should not be treated as an error (e.g. #24559).

`RAY_IGNORE_UNHANDLED_ERRORS=1` suppresses the noise, but this is not a solution because it also suppresses legitimately unexpected errors.

### Use case

There should be some way of using `ray.cancel` silently (ideally via a keyword argument).

**Comment by czgdp1807** [comment]
I can also look into this once https://github.com/ray-project/ray/issues/24559 is done.

**Comment by wmayner** [comment]
Bumping this as well as #24559
