### ISSUE TITLE
[Datasets] Bound actor pool size by number of input blocks.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#24668]
When batch mapping over an actor pool, we can map over all input blocks in parallel, but that's the upper limit to our parallelism. We should therefore not scale the actor pool beyond the number of input blocks, otherwise we'll be allocating actors that will never get used.

**Comment by amogkam** [comment]
With the effort to move towards fixed size actor pools, deprioritizing this issue.
