### ISSUE TITLE
[Core] long_running_actor_deaths is failing releases/1.13.0rc0

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#24660]
### What happened + What you expected to happen

long_running_actor_deaths is failing in the 1.13 release builds:

https://buildkite.com/ray-project/release-tests-branch/builds/507#ca9e517f-7d37-4bb2-9c38-060f59a8f401

### Versions / Dependencies

releases/1.13.0rc0

### Reproduction script

n/a

**Comment by rkooo567** [comment]
Hey @avnishn can you cherry-pick this PR and run (this won't impact any other tests) https://github.com/ray-project/ray/pull/24469/files? It seems like this test has been stable for a while after 5/4, and I have one commit that I think it could be a fix (not 100% sure), and I think this PR can help identify that.

**Comment by rkooo567** [comment]
This is the potential fix commit (https://github.com/ray-project/ray/commit/bf2dc94cdb4089044cef7b771d0473dbc57843dc), but I need https://github.com/ray-project/ray/pull/24469/files to be merged for better information

**Comment by scv119** [comment]
@rkooo567 is this a release blocker?

**Comment by rkooo567** [comment]
I tried bisecting it, but I could find a commit that looks suspicious around the time the first failure happens..
