### ISSUE TITLE
[Core] shuffle_1tb_5000_partitions is failing releases/1.13.0rc0

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#24661]
### What happened + What you expected to happen

[shuffle_1tb_5000_partitions](https://buildkite.com/ray-project/release-tests-branch/builds/507#28991b3b-65c3-419b-9e9a-60b0814e16d4) is failing (permalink to the buildkite run)

### Versions / Dependencies

releases/1.13.0rc0

### Reproduction script

n/a

**Comment by scv119** [comment]
confirmed that with the merge the test passed; while I'm kicking off more runs, I'll mark this closed.
https://console.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_rH3ATVQDCqkVgBijDcxpVQqC
