### ISSUE TITLE
[Core] many_tasks is failing releases/1.13.0rc0

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#24662]
### What happened + What you expected to happen

many tasks is failing on releases/1.13.0rc0

https://buildkite.com/ray-project/release-tests-branch/builds/507#aaa06767-2f2d-40f0-b3b8-28b4d716da77

### Versions / Dependencies

releases/1.13.0rc0

### Reproduction script

n/a

**Comment by rkooo567** [comment]
@jianoaix are you doing bisecting now?

**Comment by jianoaix** [comment]
It's not consistently failing so not sure bisecting can find anything useful here.

The first failure was on 5/1: https://b534fd88.us1a.app.preset.io/superset/explore/p/4KY87JeLoQW/
It then bounced back to normal for a few days and then becoming flaky again.

That first failure was at this commit: https://github.com/ray-project/ray/commit/27917f570de3296ecf6c81fbe0cc318efd448b1b
The commit however seems harmless to scheduling performance.

**Comment by jianoaix** [comment]
Re-ran the first failed commit https://github.com/ray-project/ray/commit/27917f570de3296ecf6c81fbe0cc318efd448b1b and this test passed: https://buildkite.com/ray-project/release-tests-branch/builds/455#67835cf3-a579-410b-9ada-c2075b0ac0d3

**Comment by jianoaix** [comment]
Fixed by https://github.com/ray-project/ray/pull/24758.

@avnishn can you cherry pick?

**Comment by zhe-thoughts** [comment]
Yup let's do a separate cherry-pick PR. Thanks @jianoaix

**Comment by jianoaix** [comment]
Done: https://github.com/ray-project/ray/commit/096918b357a2978e6f771ffb555cb60f2c8bc05b
