### ISSUE TITLE
[Core] scheduling_test_many_0s_tasks_many_nodes Is Failing releases/1.13.0rc0

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#24663]
### What happened + What you expected to happen

[scheduling_test_many_0s_tasks_many_nodes](https://buildkite.com/ray-project/release-tests-branch/builds/507#4df175e0-8532-4669-933f-7ed4523c8d8f) is failing on releases/1.13.0rc0

### Versions / Dependencies

releases/1.13.0rc0

### Reproduction script

n/a

**Comment by jianoaix** [comment]
This is known and same as https://github.com/ray-project/ray/issues/24234, @jjyao

**Comment by scv119** [comment]
this has been a known flaky tests so not release blocker.
