### ISSUE TITLE
[Core] `SetCurrentTaskId` & `GetCurrentTaskId` is incorrect when async actor is used. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#24682]
### What happened + What you expected to happen

Currently, `SetCurrentTaskId` stores the single currently running task id to the thread local data structure, which works for normal task/actor/threaded actors cases.

However, when async actor is used, this semantic is incorrect because async actor can run multiple tasks at the same time within the same thread.

https://github.com/ray-project/ray/blob/a7d552ca2541376b87a40bc6b2189bab5a5c6c5a/src/ray/core_worker/context.cc#L58

Ideally, we should store a set of task ids instead of a single ID per-thread local data structure. 

### Versions / Dependencies

Master

### Reproduction script

N/A

**Comment by rkooo567** [comment]
cc @scv119 for triage. I think this is not impacting correctness right now since there's no logic we depend on this. But it is very error prone

**Comment by hora-anyscale** [comment]
Per Triage Sync: Closing since dupe
