### ISSUE TITLE
[docs] Hard to understand context for quick search results

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24696]
### Description

Currently search results on docs only provide the page name, which is often hard to understand without context about the parent pages. For example, the below screenshot shows identical results for the top 3, even though they actually link to different pages (fault tolerance for tasks, actors, vs objects).

![Screenshot from 2022-05-11 11-25-46](https://user-images.githubusercontent.com/2560516/167920136-eaffe35d-e25a-49bf-a728-3b36fcd1bcdb.png)

**Comment by maxpumperla** [comment]
@stephanie-wang thanks, we should definitely fix that.

On the flip side, it's also a good idea not to call to many documents by the same, unspecific title (which is also presumably not that great for SEO). Maybe we should tackle that, too?

**Comment by stephanie-wang** [comment]
Yeah, but I think it would probably be better to add some subtext instead of trying to differentiate all of the titles. Sometimes there really are things that we need to treat separately depending on the Ray Core component or depending on the library.

Here's another example of that, looking at checkpointing, which is a concept both in individual libraries and in Ray Core. The first result is Tune-specific and the second is a Core example.

![Screenshot from 2022-05-11 12-53-00](https://user-images.githubusercontent.com/2560516/167934800-526ee785-1b71-494c-a485-8e63a85758bb.png)
