### ISSUE TITLE
[docs] Add end-to-end example on how to profile a Ray application

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#24702]
### Description

Take for example Waleed's decision tree example https://medium.com/distributed-computing-with-ray/the-power-and-potential-of-ray-8f6d9f2c3d44 and show how to profile it with the Ray timeline (seeing how large the tasks are, how much time is spent in data serialization and deserialization).

This is motivated by a user I have recently communicated with who was parallelizing an algorithms with Ray and it was hard to understand why there was no speedup.

**Comment by pcmoritz** [comment]
@maxpumperla @dynamicwebpaige What do you think about this?

**Comment by maxpumperla** [comment]
@pcmoritz sounds very interesting, let's go for it :D
