### ISSUE TITLE
[Core|Pubsub] Old subscribers cannot listen to new information after gcs_server restart

### ISSUE THREAD

**Issue by larrylian** [ray-project/ray#24721]
### What happened + What you expected to happen

 Old subscribers cannot listen to new information after gcs_server restart,like SubscribeAllNodeInfo subscribers。

What happened：
raylet.out is first node raylet's log .
gcs_server.1.out is gcs_server's log after gcs_server restart

1、add a new node 314ef1a71b2216122a0149ab45af181baf40fb5bdfe8592b4df08dbb after gcs_server restart
2、But raylet.out can't received notification of 314ef1a71b2216122a0149ab45af181baf40fb5bdfe8592b4df08dbb node
![image](https://user-images.githubusercontent.com/11072802/168022699-665a42c0-bcc4-47c9-95d0-94791b57e167.png)

### Versions / Dependencies

master

### Reproduction script

Use my python UT PR to reproduction #24724 :
```
def test_create_pg_when_add_new_node_after_gcs_server_restart(
    ray_start_cluster_head_with_external_redis,
):
    cluster = ray_start_cluster_head_with_external_redis

    # Restart gcs server.
    cluster.head_node.kill_gcs_server()
    cluster.head_node.start_gcs_server()

    # Restart the raylet.
    cluster.add_node(num_cpus=2)
    cluster.wait_for_nodes()

    placement_group = ray.util.placement_group([{"CPU": 2}])
    ray.get(placement_group.ready(), timeout=10)
    table = ray.util.placement_group_table(placement_group)
    assert table["state"] == "CREATED"

```
![image](https://user-images.githubusercontent.com/11072802/168040492-588c4524-9871-494a-a29f-260083b94f75.png)

**Comment by WangTaoTheTonic** [comment]
@iycheng @mwtian Can you help to ensure this?

**Comment by mwtian** [comment]
@iycheng has a pending PR for this: #24628

**Comment by WangTaoTheTonic** [comment]
PR merged, closing this.
