### ISSUE TITLE
[tune] Make tfevents files smaller 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#24737]
### Description

# Actual state
At present a trial writes a single `tfevents` file that can grow in large in size, if the trial runs long and has many metrics. On clouds like GCP, AWS, etc. this can become a problem as syncing to a bucket becomes slower by time until it almost stagnates and is finalized after the trial has finished. This makes users even wonder, if their experiment runs correctly. 

# Feature Request
It would be of advantage to have `tfevents` files of fixed size (maybe 1M timesteps or 1000 iterations) such that the single files can be synched faster with a bucket. 

### Use case

If we run huge experiments in the cloud we usually want to sync checkpoints, etc. with a bucket. To get here and there a glimpse at the state of the experiment, we start on a VM a TensorBoard instance that points its `logdir` to the experiment folder in the bucket. 

Having smaller `tfevents` files will then result in a current state of the experimen in TensorBoard.

**Comment by Yard1** [comment]
cc @krfricke @amogkam 

I am not sure if tensorboard supports combining results from multiple files, but if it does, then I think we should be able to implement this. @simonsays1980 how big was the file?

**Comment by simonsays1980** [comment]
@Yard1 it does :) That was actually the clue with my two `tfevents` files. It glues it together. You can give it a try by running an experiment, interrupting and resuming it. There should then be two files and if you load only one of them you get only the number of timesteps therein. 

What I right now look into, is, if the parameters in the `tune.SyncConfig` define the sync behavior of the `tfevents` files. @Yard1 do you have a guess?
