### ISSUE TITLE
[docs] Convert all rst files to md (like Serve!). Don't add new rst. 🚀 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#24730]
### Description

We use quite an assortment of features from the Sphinx ecosystem, but we don't have to rely on the rather wonky `rst` format. Markdown is much more popular, and I think it will be much easier to attract new contributors if everything we publish is either in `.md` format (in MyST flavour) or an `.ipynb`. 

We can slowly but surely migrate this over, not urgent. Once gone, we should erase all mentions of rst, especially in the docs contributor guide.

**Comment by simon-mo** [comment]
lesson learned from my rst2myst process:
- Make sure to use Python 3.7!
- The steps are `rst2myst convert $(find .rst)`; rm $(find .rst)`. 
- Then iterate over `make html` for the compilation process. The first try probably won't compile and most error should be broken references. Which are typically easy to fix!

**Comment by DmitriGekhtman** [comment]
[Oh, good, I'm not crazy.](https://github.com/ray-project/ray/pull/21086#discussion_r789993339)

**Comment by maxpumperla** [comment]
thanks @simon-mo! So far I've only done this manually, one by one. But it might be a good idea to speed this up a little, e.g. go by project.

**Comment by DmitriGekhtman** [comment]
Keep open.
