### ISSUE TITLE
[Core] shuffle performance regression

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#24740]
### What happened + What you expected to happen

we noticed performance regression for nightly test shuffle_1tb_5000_partitions. concretely the test previously takes 1h10m to finish but now it takes more than 2h30minutes.

after investigation we believe mostly likely 5a8264015b caused the regression.

here is the run before 5a8264015b: https://console.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_1ejykCYq9BnkC5v8ZJjrqc2b?command-history-section=command_history
here is the run after 5a8264015b: 
https://console.anyscale.com/o/anyscale-internal/projects/prj_SVFGM5yBqK6DHCfLtRMryXHM/clusters/ses_Lr5N8jVRdHCWJWYA2SRaUkzZ?command-history-section=command_history

### Versions / Dependencies

5a8264015b

### Reproduction script

python release/ray_release/scripts/run_release_test.py shuffle_1tb_5000_partitions

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@mwtian I tried revert the pr but it requires some merging due to follow up renaming #24451. Let you to decide if we should revert that too.

**Comment by mwtian** [comment]
Reverting both could be cleaner.
