### ISSUE TITLE
[Datasets] Unskip Datasets memory release tests

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#24757]
### What happened + What you expected to happen

This Datasets test has been failing since #24523, although the PR seems to be unrelated. Adding timeouts and retries didn't seem to help.

### Versions / Dependencies

2.0dev

### Reproduction script

bazel test //python/ray/data:tests/test_optimize

**Comment by stephanie-wang** [comment]
cc @clarkzinzow

**Comment by matthewdeng** [comment]
@clarkzinzow can you share what the context is here?

**Comment by c21** [comment]
Outdated issue now, closing.
