### ISSUE TITLE
[docs] 🔢  Establish configurable galleries for ecosystem integrations and other cases 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#24780]
### Description

The executable book project has an interesting way of defining example galleries like [this one](https://executablebooks.org/en/latest/gallery.html)

![Screenshot 2022-05-13 at 16 38 47](https://user-images.githubusercontent.com/3462566/168307416-13381377-9ab1-4d48-9a93-ca0c467a1520.png)

purely by touching a *simple to modify yaml file*. We could use this to improve the appeal of our current ["Ecosystem" page](https://docs.ray.io/en/latest/ray-overview/ray-libraries.html) and make it much easier for our partners to show integrations on our site.

In the same way, we could create a curated list of "projects using Ray", or build our own example gallery (e.g. for Ray AIR) in an easier fashion.

To make this happen, we should probably retire the `sphinx-panels` plugin and replace it with [`sphinx-design`](https://sphinx-design.readthedocs.io/en/sbt-theme/index.html), which the exec book project maintainers hail as the new thing.

**Comment by pcmoritz** [comment]
Let's keep this open, I'm sure we can get to this in the not too distant future :)
