### ISSUE TITLE
[Docs] full search results generates wrong URL

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#24808]
### What happened + What you expected to happen

1. Go to any subpage (e.g. https://docs.ray.io/en/master/data/dataset.html#)
2. Search for something in the search bar
3. Press enter

Expectation: https://docs.ray.io/en/master/search.html?q=test
Reality: https://docs.ray.io/en/master/data/search.html?q=test

cc @maxpumperla follow-up to https://github.com/ray-project/ray/pull/24722  

### Versions / Dependencies

master

### Reproduction script

See above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by maxpumperla** [comment]
@matthewdeng thanks, good catch! We're using a relative link to `/search.html`, which obv. doesn't work if you're not at the index page...
