### ISSUE TITLE
[Autoscaler][Logs][minor] Prefix (autoscaler) instead of (scheduler) for autoscaler events

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#24807]
### What happened + What you expected to happen

The autoscaler pushes some logs to the Ray driver. The logs are prefixed with `(scheduler)` which is misleading.
The prefix should be `(autoscaler)`.

### Versions / Dependencies

Ray master.

### Reproduction script

Submit a Ray task or actor which triggers upscaling to trigger the logs.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by truelegion47** [comment]
Can you please post some logs as example so I can pinpoint what places it might be coming from in autoscaler ?

**Comment by DmitriGekhtman** [comment]
Thanks -- will do -- this issue could indeed use more context.

**Comment by truelegion47** [comment]
@DmitriGekhtman Is this still needed ? If yes, could you please add some logs/context here when you get a chance ? I can throw in a fix.

**Comment by wuisawesome** [comment]
@slu0

**Comment by scottsun94** [comment]
@DmitriGekhtman It seems that we are waiting for more context : )

**Comment by DmitriGekhtman** [comment]
Run any Ray workload workload that triggers autoscaling, such as the one described here: https://docs.ray.io/en/latest/ray-contribute/fake-autoscaler.html (can be run on a laptop).
Messages describing scaling events will be slightly confusingly prefixed with `(scheduler)` rather than `(autoscaler)`.
