### ISSUE TITLE
[Tune: scheduler] shim tune.create_scheduler() does not properly parse kwargs for pb2 scheduler 

### ISSUE THREAD

**Issue by jimthompson5802** [ray-project/ray#24815]
### What happened + What you expected to happen

The shim `tune.create_scheduler()` does not properly parse the keyword parameters passed in a dictionary for the `pb2` scheduler.   For this call
```
pb2_parm_dict = {"time_attr": "time_total_s", "metric": "metric_score", "mode": "min",
                 "hyperparam_bounds": {"param1": [0, 1]}}

pb2_scheduler = create_scheduler("pb2", **pb2_parm_dict)
```

This error is generated:
```
Traceback (most recent call last):
  File "/opt/project/sandbox/hyperopt/mwe_create_scheduler.py", line 15, in <module>
    pb2_scheduler = create_scheduler("pb2", **pb2_parm_dict)
  File "/usr/local/lib/python3.8/site-packages/ray/tune/schedulers/__init__.py", line 66, in create_scheduler
    return SchedulerClass(**trimmed_kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/tune/schedulers/__init__.py", line 18, in _pb2_importer
    return PB2(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ray/tune/schedulers/pb2.py", line 293, in __init__
    raise TuneError("`hyperparam_bounds` must be specified to use "
ray.tune.error.TuneError: `hyperparam_bounds` must be specified to use PB2 scheduler.

```

The incorrect parsing appers to be specific to the `pb2` scheduler.  All other schedulers kwargs are processed correctly.

From what I can tell, the issue might be related to this: https://github.com/ray-project/ray/blob/5c9b1003d56eca4e0d06e4077a09ad0b8106fa16/python/ray/tune/schedulers/__init__.py#L14-L18

It appears when this call is made with `pb2` scheduler, this section of code :https://github.com/ray-project/ray/blob/5c9b1003d56eca4e0d06e4077a09ad0b8106fa16/python/ray/tune/schedulers/__init__.py#L63-L64 returns the parameters for `_pb2_importer()` and not the underlying `PB2()` constructor.

### Versions / Dependencies

ray 1.11.1
Python 3.8
OS: Linux 21a5e2d85a0d 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 GNU/Linux  (Docker container running in MacOS Docker Desktop)

### Reproduction script
```
from ray.tune.schedulers import create_scheduler


asynchyperband_parm_dict = {"time_attr": "training_iteration", "metric": "metric_score", "mode": "min"}

pb2_parm_dict = {"time_attr": "time_total_s", "metric": "metric_score", "mode": "min",
                 "hyperparam_bounds": {"param1": [0, 1]}}


# this works
asychyperband_scheduler = create_scheduler("asynchyperband", **asynchyperband_parm_dict)
print(asychyperband_scheduler)

# this fails
pb2_scheduler = create_scheduler("pb2", **pb2_parm_dict)
print(pb2_scheduler)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hey @jimthompson5802, thanks for the really clean bug report and repro! Taking a look over this, your hypothesis looks correct.

As a workaround, could you just skip over `create_scheduler` and directly instantiate the object?
```python
from ray.tune.schedulers.pb2 import PB2
pb2_scheduler = PB2(**pb2_parm_dict)
print(pb2_scheduler)
```

Also, would you be interested in making a PR to fix the issue?

**Comment by jimthompson5802** [comment]
@matthewdeng   thank you for confirming the hypothesis.  

Actually, I was thinking of possible fix for the issue, something like this in this area: https://github.com/ray-project/ray/blob/5c9b1003d56eca4e0d06e4077a09ad0b8106fa16/python/ray/tune/schedulers/__init__.py#L63-L64  the fix would be 
```
if scheduler == "pb2":
  scheduler_args = get_function_args(PB2)
else:
  scheduler_args = get_function_args(SchedulerClass)
trimmed_kwargs = {k: v for k, v in kwargs.items() if k in scheduler_args}
```

One concern I had was the comment in the wrapper about 
```
# PB2 introduces a GPy dependency which can be expensive, so we import
# lazily.
```

For the above fix, I would have to import `PB2`.    How would this affect the concern expressed in the comment?

**Comment by matthewdeng** [comment]
In general I think we'd want to adhere to the same logic in `_pb2_importer` and only import `PB2` if `scheduler == "pb2"`! 
 And going off that, we should not have to duplicate the import logic. 

One idea I had is to clean up the creation logic of `SchedulerClass` to directly capture the `_pb2_importer` logic if `scheduler == "pb2"` and return `PB2`. IMO it's a little strange that right now `SchedulerClass` points to the `_pb2_importer` function!

**Comment by jimthompson5802** [comment]
This is the part that I'm scratching my head on.

> lean up the creation logic of SchedulerClass to directly capture the _pb2_importer logic if scheduler == "pb2" and return PB2

I thought the existing logic would have done what you suggested.  Though in looking at `_pb2_importer` again, it appears to return an instanstiation of the PB2 class vs the class itself.  All the other entries are classes.  Maybe the fix is as simple as 
```
def _pb2_importer():
    # PB2 introduces a GPy dependency which can be expensive, so we import
    # lazily.
    from ray.tune.schedulers.pb2 import PB2
    return PB2
```

There are some tasks, I need to complete for the open source project I'm contributing to that uses ray, which uncovered tis bug.  Once I finish those tasks, I'll take another look at this.   Besides, I need to setup a ray development environment to work in.  

Thank you for the guidance.

**Comment by jimthompson5802** [comment]
@matthewdeng  ... an update:
* took awhile to get a dev environment in a docker container to working
*  I have a proposed fix for the `TuneError` exception, here is the same example program now working
```
from ray.tune.schedulers import create_scheduler


asynchyperband_parm_dict = {"time_attr": "training_iteration", "metric": "metric_score", "mode": "min"}

pb2_parm_dict = {"time_attr": "time_total_s", "metric": "metric_score", "mode": "min",
                 "hyperparam_bounds": {"param1": [0, 1]}}


# this works
asychyperband_scheduler = create_scheduler("asynchyperband", **asynchyperband_parm_dict)
print(asychyperband_scheduler)

# this now works
pb2_scheduler = create_scheduler("pb2", **pb2_parm_dict)
print(pb2_scheduler)

# output
<ray.tune.schedulers.async_hyperband.AsyncHyperBandScheduler object at 0x7f998a2917f0>

<ray.tune.schedulers.pb2.PB2 object at 0x7f998a1f6be0>

Process finished with exit code 0

```

* next step for me is update the test for this fix and to ensure it passes the linter tests.  Once this is done, I'll submit the PR.  Expect in the next day or two.

**Comment by jimthompson5802** [comment]
@matthewdeng   submitted PR to address the bug.

**Comment by sumanthratna** [comment]
actually, I think we have a simpler solution: 

the issue is that `ray._private.utils.get_function_args` (which calls `inspect.signature` internally) returns the parameters of `_pb2_importer` rather than `PB2`. Thus, we can simply add `functools.wraps(PB2)` as a decorator on `_pb2_importer` to tell `inspect.signature` to fetch the parameters of `PB2` rather than `_pb2_importer`

will leave it to @matthewdeng to decide on which solution to go with

**Comment by sumanthratna** [comment]
> Hey @sumanthratna, if I understand correctly that would require eagerly importing `PB2`, which would defeat the purpose of having `_pb2_importer` in the first place. Let me know if that's not the case!

Yup sorry you're correct -- let's stick with the current solution
