### ISSUE TITLE
[Tune] Issue on page /tune/api_docs/search_space.html

### ISSUE THREAD

**Issue by BabelTower** [ray-project/ray#24818]
how can i generate an interval by ray.tune as a hyperparameter for search space?

i want my hyperparameter be a format as (a, b), which a <= b. so that my program can sample for this interval.

**Comment by matthewdeng** [comment]
Hey @BabelTower, can you elaborate more on the criteria for this interval?

In your scenario, are a and b already known and for each Trial you want to generate 1 value in the range (a, b)? Or do you want to generate values for a and b which will be used within the Trial?
