### ISSUE TITLE
Ray core (Ray client) problem with 1.12.0

### ISSUE THREAD

**Issue by marsupialtail** [ray-project/ray#24823]
### What happened + What you expected to happen

This is a problem when running Ray 1.11 on cluster and Ray 1.12 on client.

Doing ray.init with address = cluster ip results in ModuleNotFoundError: No module named 'ray.runtime_env'

### Versions / Dependencies

1.12 on client, 1.11 on cluster

### Reproduction script

start a ray cluster with ray 1.11, then try to do ray.init on a ray client with ray 1.12

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
Hey @marsupialtail, in general you should be using the same version of Ray or [an error will be raised](https://docs.ray.io/en/latest/cluster/ray-client.html#versioning-requirements).
