### ISSUE TITLE
[Dashboard] Connecting to dashboard forces port usage 

### ISSUE THREAD

**Issue by spolcyn** [ray-project/ray#24858]
### What happened + What you expected to happen

1. Previously we used a URL with no port (dashboard.company.com) via a proxy to connect to the Ray Dashboard for monitoring and job submission. However, with the release of Ray 1.12, if the URL for the `JobSubmissionClient` doesn't have a port on it, there is no way to stop the implementation from adding a port number to it (https://github.com/ray-project/ray/blob/master/dashboard/modules/dashboard_sdk.py#L80)

2. We'd expect to be able to provide any URL, including ones that do the forwarding under the hood.

### Versions / Dependencies

Ray 1.12

### Reproduction script

client = JobSubmissionClient("http://dashboard.company.com") # --> will try to connect to "http://dashboard.company.com:8265"

### Issue Severity

Low: It annoys or frustrates me.

**Comment by simon-mo** [comment]
cc @edoakes @architkulkarni

**Comment by spolcyn** [comment]
@edoakes Yep! That syncs to what I would expect, restated below to confirm:

1. `client = JobSubmissionClient()` will use `localhost:8265` by default (like `ray.init()`)
2. `client = JobSubmissionClient("dashboard.company.com")` will connect to `dashboard.company.com`
3. `client = JobSubmissionClient("dashboard.company.com:8265")` will connect to `dashboard.company.com:8265`
