### ISSUE TITLE
[Datasets] Write out directory-partitioned datasets

### ISSUE THREAD

**Issue by jaidisido** [ray-project/ray#24879]
### Description

Looking at `ray.data.Dataset.write_*` methods, none of them seem to support writing partitioned data. Is there a plan to support this in the future?

### Use case

Writing data partitioned by specific columns is a common pattern in data engineering. Various other frameworks support it including Spark, Arrow, and Pandas.

**Comment by xiurobert** [comment]
Hi! There is a `repartition()` method, is what you are looking for?

**Comment by jaidisido** [comment]
Hi - yes I am referring to partitioning a dataset based on columns which is not covered by `repartition`.

For instance, pyarrow has a [write_to_dataset](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_to_dataset.html) method which writes the data partitioned by column to the filesystem

**Comment by xiurobert** [comment]
This is an interesting proposal. Maybe one of the core project members can chime in and discuss with you on this,

**Comment by valiantljk** [comment]
Could be a very cool feature to speedup IO on s3.

**Comment by bdewilde** [comment]
> Unless you are inquiring about creating the blocks based on the columns.

Yes, please! This is an old request, but the feature would still be useful. :) I have a dataset where certain sets of rows must be written out to separate files for later processing. Currently, I add a column to the dataset that's effectively a computed grouping key, use it in `Dataset.groupby()`, then iterate over groups via `GroupedDataset.map_groups()`, writing each to file. The problem with this is that this isn't really what map-groups is for, and I can't use the `Dataset.write_*()` methods for easy I/O and customized block file naming. I'd guess that it's also slower.

Would be really nice to have something like `Dataset.repartition(by=colname).write_parquet(PATH, block_path_provider=MY_BPP)`

**Comment by jaidisido** [comment]
I am not sure why this is marked as closed when the issue has not been resolved?

**Comment by bdewilde** [comment]
just following up to say that i did find a way to repartition a dataset by a single key but which fails for multiple keys. i got thoroughly lost in ray data internals while trying to implement the latter, more general case, but it seems like it should be possible for someone who understands the framework better. anyway, here's what i came up with:

```python
def repartition_by(
    ds: ray.data.Dataset, *, key: str, descending: bool = False
) -> ray.data.Dataset:
    """
    See Also:
        :meth:`ray.data.Dataset.repartition()`
    """
    # sort ensures that batches all have same key
    ds_sorted = ds.sort(key, descending)
    df_refs = [
        ray.put(batch)
        # null batch size ensures that all rows with same key included in each batch
        for batch in ds_sorted.iter_batches(batch_size=None, batch_format="pandas")
    ]
    return ray.data.from_pandas_refs(df_refs)
```

**Comment by ivanthewebber** [comment]
You can always groupby and then use Pandas to write, but yes; it would be much cleaner and better feature parity with PySpark to have it built in

**Comment by richardliaw** [comment]
There is now initial support for this -- https://github.com/ray-project/ray/pull/49411 

cc @gvspraveen
