### ISSUE TITLE
[client] Ray.init ignore_reinit_error=True doesn’t seem to work for ray client

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#24888]
### What happened + What you expected to happen

From https://discuss.ray.io/t/ray-init-ignore-reinit-error-true-doesnt-seem-to-work-for-ray-client/6148

when I am using ray.init() from a client to connect to a ray cluster, even when I pass in the ignore_reinit_error=True argument, it returns: RuntimeError: Ray Client is already connected. Maybe you called ray.init(“ray://”) twice by accident?

cc @chris

### Versions / Dependencies

Latest ray

### Reproduction script

ray.init(“ray://”) 
ray.init(“ray://”, ignore_reinit_error=True)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by spolcyn** [comment]
Is there a workaround for this currently? Otherwise, can it be upgraded to high severity (no workaround)?

**Comment by ericl** [comment]
@AmeerHajAli could you help triage this?

**Comment by AmeerHajAli** [comment]
@ckw017 , PTAL
