### ISSUE TITLE
[Core] use `@ray.remote` on a subclass with classmethods 

### ISSUE THREAD

**Issue by fuhuifang** [ray-project/ray#24899]
### Description

Reposting from https://discuss.ray.io/t/how-to-use-ray-remote-on-a-subclass/6150:

I want to define a class `Foo` with classmethod `main`, and an Actor class `Bar`:
```python
class Foo:
    def __init__(self, x):
        self.x = x    
    def run(self):
        pass
    @classmethod
    def main(cls, x):
        main_instance = cls(x)
        main_instance.run()
        return main_instance

@ray.remote
class Bar(Foo):
    def run(self):
        self.x += 1

ray.get(Bar.main.remote(1))
```
and run into error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'remote'
```
Ray version: 1.12.0

### Use case

I'm using Ray for orchestration, and a base class like `Foo` is required for easy user code.

**Comment by czgdp1807** [comment]
I can look into this.

**Comment by czgdp1807** [comment]
The following works for me,

```python
import ray

class Foo:
    def __init__(self, x):
        self.x = x
    
    def run(self):
        pass

    @classmethod
    def main(cls, x):
        main_instance = cls(x)
        main_instance.run()
        return main_instance

@ray.remote
class Bar(Foo):
    def run(self):
        self.x += 1

print(Bar.main(1))
```

**Output**

```bash
<__main__.ActorClass(Bar) object at 0x000002061D5AD3A0>
```

For actually supporting `.remote`, I would be required to do some more investigation and discussions. Let me know if the above works you. Thanks.

**Comment by fuhuifang** [comment]
> The following works for me,
> 
> ```python
> import ray
> 
> class Foo:
>     def __init__(self, x):
>         self.x = x
>     
>     def run(self):
>         pass
> 
>     @classmethod
>     def main(cls, x):
>         main_instance = cls(x)
>         main_instance.run()
>         return main_instance
> 
> @ray.remote
> class Bar(Foo):
>     def run(self):
>         self.x += 1
> 
> print(Bar.main(1))
> ```
> 
> **Output**
> 
> ```shell
> <__main__.ActorClass(Bar) object at 0x000002061D5AD3A0>
> ```
> 
> For actually supporting `.remote`, I would be required to do some more investigation and discussions. Let me know if the above works you. Thanks.

Thanks @czgdp1807 for investigating. We'll still need `.remote` in our case.

**Comment by tupui** [comment]
@fuhuifang I think that if you want to do this, you need to also decorate the class method itself (decorating the base class itself is not supported). Otherwise because you are using a class method, you are bypassing the remote on the main class. 

```python
class Foo:
    def __init__(self, x):
        self.x = x    

    def run(self):
        pass

    @classmethod
    @ray.remote
    def main(cls, x):
        main_instance = cls(x)
        main_instance.run()
        return main_instance

@ray.remote
class Bar(Foo):
    def run(self):
        self.x += 1

print(Bar.main.remote)
```

**Comment by fuhuifang** [comment]
> @fuhuifang I think that if you want to do this, you need to also decorate the class method itself (decorating the base class itself is not supported). Otherwise because you are using a class method, you are bypassing the remote on the main class.
> 
> ```python
> class Foo:
>     def __init__(self, x):
>         self.x = x    
> 
>     def run(self):
>         pass
> 
>     @classmethod
>     @ray.remote
>     def main(cls, x):
>         main_instance = cls(x)
>         main_instance.run()
>         return main_instance
> 
> @ray.remote
> class Bar(Foo):
>     def run(self):
>         self.x += 1
> 
> print(Bar.main.remote)
> ```

Hi @tupui, the argument `cls` in the classmethod seems not to be passed correctly. I'm getting `"TypeError: missing a required argument: 'x'"` if I call `Bar.main.remote(1)`.

Also, if I reorder the two decorators @classmethod and @ray.remote, I'm running into the following error. Are they compatible?
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in Foo
  File "C:\Users\fufang\Anaconda3\envs\shrike\lib\site-packages\ray\worker.py", line 2222, in remote
    assert len(args) == 0 and len(kwargs) > 0, error_string
AssertionError: The @ray.remote decorator must be applied either with no arguments and no parentheses, for example '@ray.remote', or it must be applied using some of the arguments in the list ['num_returns', 'num_cpus', 'num_gpus', 'memory', 'object_store_memory', 'resources', 'accelerator_type', 'max_calls', 'max_restarts', 'max_task_retries', 'max_retries', 'runtime_env', 'retry_exceptions', 'placement_group', 'concurrency_groups'], for example '@ray.remote(num_returns=2, resources={"CustomResource": 1})'
```
```python
class Foo:
    def __init__(self, x):
        self.x = x    

    def run(self):
        pass

    @ray.remote
    @classmethod
    def main(cls, x):
        main_instance = cls(x)
        main_instance.run()
        return main_instance
```

**Comment by tupui** [comment]
Oh indeed, and could you work with a `staticmethod`? This should not conflict.

**Comment by fuhuifang** [comment]
With `staticmethod`, the methods in Bar seem not working. The following code will raise NotImplementedError..
```python
class Foo:
    def __init__(self, x):
        self.x = x    

    def run(self):
        raise NotImplementedError

    @staticmethod
    @ray.remote
    def main(x):
        main_instance = Foo(x)
        main_instance.run()
        return main_instance.x

@ray.remote
class Bar(Foo):
    def run(self):
        self.x += 1
ray.get(Bar.main.remote(1))
```

**Comment by tupui** [comment]
@fuhuifang it makes sense, because you have `main_instance = Foo(x)` and in `Foo.run` you raise.
