### ISSUE TITLE
[tune] Better resumption of stopped or errored experiments 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#24918]
### Description

- Pre-experiment: Maybe we could provide some guidelines in regard to disk space (checkpoint size, etc.)

- During experiment: Probably using smaller tf.events  files (but many of them) would result in faster syncing to the bucket I guess (would also resolve [this issue](https://github.com/ray-project/ray/issues/24737)).

- When errored out:
   - Offering a `remote_errored_only` possibility for the errored out experiments stored in the bucket.
   - Somehow rerunning errored out experiments on top of already existent `experiment_state.json` files such that the stop conditions (e.g. 1e12 timesteps) still hold, or costs are not doubled, or at least the user is not left in doubt. This is also somehow connected to [this issue](https://github.com/ray-project/ray/issues/23674).

### Use case

Yesterday, a long-running experiment (over 4 days now) errored out on GCP due to no disk space left (600GB were full). I made a snapshot (as usually the data from the head node does not sync that fastly with the bucket see [this issue](https://github.com/ray-project/ray/issues/24737)) and tried to the snapshot as boot disk - but the ray_results  were not there on this disk. I also attached the snapshot as a secondary but could not mount it. 
After two hours of searching for a solution I gave up and decided to go for the bucket option. I used `resume="ERRORED_ONLY"`, but that threw an error. So I restarted the experiment with `resume=REMOTE` which downloaded the experiment folder. 
This morning I saw also this errored out. What I then did was to run (with the downloaded data from the bucket) again with `resume=ERRORED_ONLY` and that finally ran (even though the experiment shows only the timesteps run in this experiment and not in the run before). I stopped the experiment later this day then. 

# Use case
I run an experiment and sync to a bucket. My VM runs out of disk space and the experiment errors out. I can delete the machine, start a new one with more disk space and resume the experiment from the last checkpoint stored to the bucket `tune` always synced to.  At the end I have the same files as if I had no interruption in my experiment (of course random states, etc. are different, but the amount of files are the same).

**Comment by simonsays1980** [comment]
@Yard1 As written in slack ;)

**Comment by krfricke** [comment]
We had a few requests for both restarting errored out trials and continuing other trials now. We should take this on soon and think about how to best configure it.

**Comment by simonsays1980** [comment]
> We had a few requests for both restarting errored out trials and continuing other trials now. We should take this on soon and think about how to best configure it.

I think this could really push the usability of `tune` another step up. As these problems will occur over and over again - they are part of our work. And early frustration could drive newbies away.

**Comment by krfricke** [comment]
@simonsays1980 can you take a look at #26826 and confirm if that solves this issue for now?

All your use cases should be covered: Resume+Remote is possible, and errored trials can be added to the experiment, or restarted, or resumed.

**Comment by krfricke** [comment]
Closing this per comment in #26826
