### ISSUE TITLE
[core] Newly pushed actors to ActorPool are not used in previously submitted tasks

### ISSUE THREAD

**Issue by siavash119** [ray-project/ray#24921]
### What happened + What you expected to happen

If I submit tasks to an ActorPool, it will use the available _idle_workers or append to _pending_submits. If I then push a new actor to the pool, I expect this actor to be assigned to a task if there are any pending submits, but it is not. The new actor will never be used until I submit a new task myself. This is easily fixed by after successfully pushing a new actor to _idle_workers, if _pending_requests, submit one from _pending_requests like so...

```python
if actor_pool._pending_submits:
    actor_pool.submit(*actor_pool._pending_submits.pop(0))
```

or even more simply fixed by calling _return_actor on the new Actor in push as shown in the last line here
```python
    def push(self, actor):
        """Pushes a new actor into the current list of idle actors.
		
        Examples:
            >>> @ray.remote # doctest: +SKIP
            >>> class Actor: # doctest: +SKIP
            ...     ... # doctest: +SKIP
            >>> a1, b1 = Actor.remote(), Actor.remote() # doctest: +SKIP
            >>> pool = ActorPool([a1]) # doctest: +SKIP
            >>> pool.submit(lambda a, v: a.double.remote(v), 1) # doctest: +SKIP
            >>> print(pool.get_next()) # doctest: +SKIP
            2
            >>> pool2 = ActorPool([b1]) # doctest: +SKIP
            >>> pool2.push(pool.pop_idle()) # doctest: +SKIP
        """
        busy_actors = []
        if self._future_to_actor.values():
            _, busy_actors = zip(*self._future_to_actor.values())
        if actor in self._idle_actors or actor in busy_actors:
            raise ValueError("Actor already belongs to current ActorPool")
        else:
            self._return_actor(actor)
```

### Versions / Dependencies

master branch

### Reproduction script

```python
import ray
ctx = ray.init(address="auto")

@ray.remote
class Test:
	def run(self, value):
		return value

actor_pool = ray.util.ActorPool([Test.remote() for _ in range(10)])
assert len(actor_pool._idle_actors) == 10

actor_pool.submit(lambda a, v: a.run.remote(v), None)
assert len(actor_pool._idle_actors) == 9


for i in range(20):
	actor_pool.submit(lambda a, v: a.run.remote(v), i)

	
assert len(actor_pool._idle_actors) == 0
assert len(actor_pool._pending_submits) == 11

actor_pool.push(Test.remote())

# I expect _idle_actors to be 0, but it is 1.
assert len(actor_pool._idle_actors) == 1
# I expect _pending_submits to be 10, but it is 11.
assert len(actor_pool._pending_submits) == 11

while actor_pool.has_next():
	res = actor_pool.get_next_unordered()
	# _idle_actors never drops below 1. i.e. The pushed actor is never used.
	assert len(actor_pool._idle_actors) >= 1
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by mwtian** [comment]
Hi @siavash119 thanks for the detailed investigation! Do you want to submit a PR for this? If not I can take it over too.

**Comment by siavash119** [comment]
Sure, I'll just call _return_actor at the end of push. Should I update the docstring for push, too, or is the current one sufficient for now? I've also implemented some other features for Actor Pools where renaming _return_actor might make sense, but I'll leave that for feature requests later. I'll start this pull request and see if there's any discussion.
