### ISSUE TITLE
[Core][flakey-test] linux://python/ray/tests:test_logging is flakey

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#24937]

**Comment by rkooo567** [comment]
cc @iycheng it looks like this only fails on medium k-z tests that enabled syncer.  Can you take over the issue?

Also, it looks like the flaky tracker includes all test result from different type of the same test (e.g., syncer / redis / normal). Are you aware of any progress that fixes this issue? (Maybe we should prepend the syncer / redis in front of the test suite name?)

**Comment by rkooo567** [comment]
Example:
https://buildkite.com/ray-project/ray-builders-branch/builds/7810#018101a4-77bf-4354-9275-807b0e5eff5f
https://buildkite.com/ray-project/ray-builders-branch/builds/7809
https://buildkite.com/ray-project/ray-builders-branch/builds/7826#01810686-04b3-4373-9a05-5aaf8b8b4107

(All recent failures are from syncer medium k-z)

**Comment by rkooo567** [comment]
hmm actually I might have figured out the issue. Let me ping you if I cannot fix it!
