### ISSUE TITLE
[Datasets/AIR] Ray Dataset actors still use up resources after Notebook cell is stopped 

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#24948]
### What happened + What you expected to happen

As discussed in https://github.com/ray-project/ray/issues/24711, even when Ray actor references are released, actors that are currently executing methods are not forced killed.

This behavior leads to poor UX when running Ray Datasets with an `ActorPool` compute strategy in notebook environments, particularly during development. If one actor fails, or the cell is interrupted, an error is raised on the driver side. However, there are actors that continue to still execute the dataset operation and use up resources.

In Ray Datasets, we should catch any Exceptions that are raised on the driver, and then terminate all actors so that these actors do not continue to use up resources.

The workaround for now is to restart the notebook runtime to free up the claimed resources, or wait for the Dataset actors to free up resources before re-running the cell.

### Versions / Dependencies

Ray master

### Reproduction script

Run the below in a Colab Notebook. The cell will fail. Then immediately try running it again. You should see that it will hang with not enough resources available to schedule the actors.

```
import ray
ds = ray.data.range(10)

class MaybeFail:
    def __call__(self, item):
        if item == 0:
            raise ValueError()
        else:
            import time
            time.sleep(10000)
            return item

ds.map(MaybeFail, batch_size=1, compute=ActorPoolStrategy())
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by peytondmurray** [comment]
I've been looking into addressing this. It looks like `ActorPoolStrategy._apply` defines the actors and initiates the computation. @clarkzinzow @ericl - would be grateful for your input on this: is `ActorPoolStrategy._apply` the right place to try/except these exceptions, or should I be doing this inside the `Actor` class itself? I was thinking of terminating the entire pool of actors here if an exception is encountered. What do you think?

**Comment by ericl** [comment]
Yep, I think terminating the actors created in a `finally` block on apply would be the way to go.
