### ISSUE TITLE
PlasmaClient crash in jenkins

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#2494]
### System information
- **OS Platform and Distribution (Linux): amplab.cs.berkeley.edu/jenkins**:
- **Ray installed from**: source
- **Ray version**: 0.5
- **Python version**: 2.7
- **Exact command to reproduce**: This is observed in Jenkins, but not every time. 
We can observe this in following jobs:
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6894/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6884/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6875/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6872/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6944/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6945/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6975/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7061/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/8114/console

### Describe the problem

`/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:625 Check failed: object_entry != objects_in_use_.end() `
Ray check failed in Plasma and Plasma client crashed.

My [PR](https://github.com/apache/arrow/pull/2273) is not updated to build_arrow.sh now, so this is not the reason. 

Is it possible that this problem is caused by concurrent issue?

### Source code / logs

```bash
+ docker run --rm --shm-size=10G --memory=10G fd152a894916bd3654e208581c3857becbc2a9697e5f90026cfcdfbc4f6e07d0 python /ray/python/ray/rllib/train.py --env CartPole-v1 --run A3C --stop '{"training_iteration": 2}' --config '{"num_workers": 2, "use_pytorch": true}'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:38879 to respond...
Waiting for redis server at 127.0.0.1:49882 to respond...
Warning: Reducing object store memory because /dev/shm has only 10737418240 bytes available. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 48}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui78905.ipynb?token=794a2b6322d4b59deef83c08f3511d9d6fc9c66a18d7de8b
======================================================================

WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARNING: Serializing objects of type <class 'ray.rllib.evaluation.sample_batch.SampleBatch'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
WARN: gym.spaces.Box autodetected dtype as <type 'numpy.float32'>. Please provide explicit dtype.
Constructing fcnet [256, 256] <class 'torch.nn.modules.activation.Tanh'>
/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:625 Check failed: object_entry != objects_in_use_.end() 
The worker with ID 44a1032b64a1692685b17498830027bf6e23c503 died or was killed while executing the task with ID f2995b4cc6e08e38dbe1c233e848177ddb28a19b
Remote function train failed with:

Traceback (most recent call last):
  File "/ray/python/ray/worker.py", line 932, in _process_task
    *arguments)
  File "/ray/python/ray/actor.py", line 261, in actor_method_executor
    method_returns = method(actor, *args)
  File "/ray/python/ray/tune/trainable.py", line 117, in train
    result = self._train()
  File "/ray/python/ray/rllib/agents/a3c/a3c.py", line 101, in _train
    self.optimizer.step()
  File "/ray/python/ray/rllib/optimizers/async_gradients_optimizer.py", line 43, in step
    gradient, info = ray.get(fut)
  File "/ray/python/ray/worker.py", line 2478, in get
    raise RayGetError(object_ids, value)
```

**Comment by guoyuhong** [comment]
@pcmoritz Do you have any ideas about this issue?

**Comment by robertnishihara** [comment]
I've seen that specific fatal error in the plasma store before. Do you have a reliable way to reproduce it?

**Comment by guoyuhong** [comment]
I don't have a reliable way to reproduce it. This happens randomly in Jenkins.

**Comment by guoyuhong** [comment]
@robertnishihara @pcmoritz I think I get some hints. I may caused by some concurrent problem. Most listed errors have the following pattern: 
```bash
/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:625 Check failed: object_entry != objects_in_use_.end()
The worker with ID c2d25a4dd6afa0dc04266a9bc76433a2a40887c7 died or was killed while executing the task with ID 332fcfb5148df6497e5722a70b3d4d9f37887527
```
This pattern means this error happens when we want to kill tasks. And [this page](https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6945/console) gives some more hints:
```bash
/ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:625 Check failed: object_entry != objects_in_use_.end() 
/ray/src/local_scheduler/local_scheduler_algorithm.cc:384 Check failed: _s.ok() Bad status: IOError: Connection reset by peer
Traceback (most recent call last):
  File "/ray/python/ray/workers/default_worker.py", line 69, in <module>
    ray.worker.global_worker.main_loop()
  File "/ray/python/ray/worker.py", line 1090, in main_loop
    self._wait_for_and_process_task(task)
  File "/ray/python/ray/worker.py", line 1047, in _wait_for_and_process_task
    self._process_task(task)
  File "/ray/python/ray/worker.py", line 959, in _process_task
    ray.utils.format_error_message(traceback.format_exc()))
  File "/ray/python/ray/worker.py", line 969, in _handle_process_task_failure
    self._store_outputs_in_objstore(return_object_ids, failure_objects)
  File "/ray/python/ray/worker.py", line 883, in _store_outputs_in_objstore
    self.put_object(object_ids[i], outputs[i])
  File "/ray/python/ray/worker.py", line 396, in put_object
    self.store_and_register(object_id, value)
  File "/ray/python/ray/worker.py", line 331, in store_and_register
    self.task_driver_id))
  File "/ray/python/ray/utils.py", line 332, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 397, in pyarrow._plasma.PlasmaClient.put
    buffer = self.create(target_id, serialized.total_bytes)
  File "pyarrow/_plasma.pyx", line 301, in pyarrow._plasma.PlasmaClient.create
    check_status(self.client.get().Create(object_id.data, data_size,
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
    raise ArrowIOError(message)
ArrowIOError: Broken pipe
```
I think the concurrent issue happened in following steps:
1. A task was scheduled in one worker. 
2. This task was killed in during it was running.
3. The task was almost finished and it was putting the output objects into the Plasma store.
4. The backend called `finish_killed_task` in `local_scheduler_algorithm.cc` to put dummy objects to the output objects. However, it looked at the Plasma Store but found the objects existing. Therefore, this [line of checking](https://github.com/ray-project/ray/blob/master/src/local_scheduler/local_scheduler_algorithm.cc#L384) failed.
5. The PlasmaClient in worker.py failed also at `create` function.

The problem should happen when two clients want to create the same object Id at the same time.

**Comment by guoyuhong** [comment]
@raulchen @eric-jj @zhijunfu

**Comment by raulchen** [comment]
Does this issue only happen to legacy code? (because the check you mentioned is in `local_scheduler_algorithm.cc`.)
If so, I think we can leave it alone, because this doesn't seem to be causing a big trouble.

**Comment by robertnishihara** [comment]
If it's a bug with the plasma store, then that will continue to be a problem. However, if it's a bug with our usage of the plasma store in the local scheduler, then it's probably ok to ignore for a little while.

**Comment by guoyuhong** [comment]
@robertnishihara Unfortunately, this error happened in raylet backend. Here is the example: https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7190/console . [Node Manager](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L755) will put some invalid arrow objects to indicate that the task was killed, which may has conflict with driver. I cannot repro it in my local environment. It is hard to debug.

**Comment by bigdata2** [comment]
Has there been an update on this issue? Please see #3628 to reproduce it with another example.
