### ISSUE TITLE
[Core \ State Observability] Use Submission client  

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#24956]
### Description

When the state APIs are used, we need direct communication to the API server (dashboard.py).

When we send a request to the API server, we currently use a hand-written client code. https://github.com/ray-project/ray/blob/f781622f8652c16bbd1845b9d05b121ae2cbafea/python/ray/experimental/state/api.py#L35

However, we'd like to instead implement the standard client following the same patterns from other part of code base. This can be done by subclassing the `SubmissionClient` class. https://github.com/ray-project/ray/blob/f781622f8652c16bbd1845b9d05b121ae2cbafea/dashboard/modules/dashboard_sdk.py#L179

Currently, this pattern is used for `JobSubmissionClient` ttps://github.com/ray-project/ray/blob/88dfc20c6e0b6d57794cdb565f221aa99c0b4882/dashboard/modules/job/sdk.py#L30 and `ServeSubmissionClient` (https://github.com/ray-project/ray/blob/f781622f8652c16bbd1845b9d05b121ae2cbafea/dashboard/modules/serve/sdk.py#L19). We'd like to implement the same pattern for state API. 

This can be done in this way;
(1) Create experimental/state/sdk.py
(2) Implement `StateApiClient(SubmissionClient)` and abstracts out API calls there. 
(3) Make `experimental/state/api.py` uses the `StateApiClient` instead of manually-written `_list` function (https://github.com/ray-project/ray/blob/f781622f8652c16bbd1845b9d05b121ae2cbafea/python/ray/experimental/state/api.py#L16)

NOTE: In the long term, this client can be auto-generated using OpenAPI (cc @alanwguo). However, it will take a while until we get that point.

**Comment by rickyyx** [comment]
I will be working on this week.
