### ISSUE TITLE
[Core / State observability] Keep the task state after it is finished.  

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#24961]
### Description

Currently, we are querying all owners to get the task state. At this time, if the task has already finished, they are immediately GC'ed, which means we will lose the state of "finished" tasks.

There are 2 solutions here; 1. Keep the task spec after task is completed until it reaches to the bounded memory size. (2) Report all finished tasks state to GCS.

**Comment by Tehada** [comment]
I wish it was an officially supported way to connect ray with airflow to store task state, logs, etc -- all cool features of orchestrator. There was an [attempt](https://github.com/anyscale/airflow-provider-ray) to connect these tools, but the project looks abandoned, unfortunately.

**Comment by rickyyx** [comment]
I am taking a look at this

**Comment by scv119** [comment]
@rkooo567 do you have preference on the options?

**Comment by rkooo567** [comment]
I think we should go with option 1. Option 2 might be way more complicated, and we need to design it better. Option 1 also goes well with the historical buffer proposals
