### ISSUE TITLE
[Core] `bazel build -c fastbuild //:ray_pkg` fails on linux

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#24984]
### What happened + What you expected to happen

I was following the [instructions for building ray from source](https://docs.ray.io/en/latest/ray-contribute/development.html#fast-debug-and-optimized-builds); I ran `bazel build -c fastbuild //:ray_pkg` at the root of the repository. The build nearly finishes but before it does, I get an error about an uninitialized variable:

```
ERROR: /home/pdmurray/Desktop/workspace/ray/BUILD.bazel:782:11: Compiling src/ray/core_worker/gcs_server_address_updater.cc failed: (Exit 1): gcc failed: error executing command

...(huge gcc command removed here for brevity)

src/ray/core_worker/gcs_server_address_updater.cc: In constructor 'ray::core::GcsServerAddressUpdater::GcsServerAddressUpdater(std::string, int, std::function<void(std::__cxx11::basic_string<char>, int)>)':
src/ray/core_worker/gcs_server_address_updater.cc:24:28: error: member 'ray::core::GcsServerAddressUpdater::updater_io_service_' is used uninitialized [-Werror=uninitialized]
   24 |     : client_call_manager_(updater_io_service_),
      |                            ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Target //:ray_pkg failed to build
INFO: Elapsed time: 875.684s, Critical Path: 164.63s
INFO: 2795 processes: 1111 internal, 1684 linux-sandbox.
FAILED: Build did NOT complete successfully
```

It looks like `updater_io_service_` is not initialized before it is used in the constructor for `GcsServerAddressUpdater`. `updater_io_service_` contains state needed to talk to the system's io services; should the `GcsServerAddressUpdater` create a new `instrumented_io_context` instance, or should it be retrieved from somewhere else upon instantiation?

I'd be happy to submit a PR to correct this, if the maintainers would accept it.

### Versions / Dependencies

Bazel 5.1.1
Ray (`master` branch and `v1.12.0` tag were tried with the same result)
Python 3.9.12
`uname -rms`: Linux 5.17.7-arch1-2 x86_64
GCC 12.1.0

### Reproduction script

```bash
#!/bin/bash
bazel build -c fastbuild //:ray_pkg
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by mwtian** [comment]
Hi @peytondmurray, what is the version of `gcc`? Ray requires at least `gcc` 9.4. And feel free to contribute! I wonder if moving `updater_io_service_` to the 1st in class member variable list would fix the issue.

**Comment by peytondmurray** [comment]
@mwtian I'm running gcc 12.1.0.

> And feel free to contribute! 

Thanks, I intend to make a PR for this!

> I wonder if moving `updater_io_service_` to the 1st in class member variable list would fix the issue.

The build definitely succeeds when `updater_io_service_` is moved to the top, but is this an acceptable solution? I guess I'm just wondering if I should be initializing it from elsewhere, or whether a fresh instance is acceptable. After all, this is a helper class for the `CoreWorker`, which already contains an [`instrumented_io_context`](https://github.com/ray-project/ray/blob/995309f9a3216c7b125d241d09584434d3a11c18/src/ray/core_worker/core_worker.h#L1069).

**Comment by mwtian** [comment]
Thanks @peytondmurray! `instrumented_io_context` in Ray has a default constructor, so it can be default initialized as a class member. After reading [this](https://stackoverflow.com/questions/10720377/can-member-variables-be-used-to-initialize-other-members-in-an-initialization-li) stackoverflow question, indeed we should fix its order in the class member list, so that `updater_io_service_` is initialized when using it to initialize other member variables.
