### ISSUE TITLE
[Doc] Improve documentation on external Redis

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#24985]
Currently documentation on external Redis is scattered among different pages. We should gather the info and have at least one section for it.

**Comment by ring-pete** [comment]
@mwtian can you point me to a few of the pages referencing external redis?  I'm working on an implementation and would be interested in using external redis, so maybe I can also help update the docs.

**Comment by wilsonwang371** [comment]
AFAIK there are two things needed.
1. install redis package in ray docker image
2. set environment variable RAY_REDIS_ADDRESS

> @mwtian can you point me to a few of the pages referencing external redis? I'm working on an implementation and would be interested in using external redis, so maybe I can also help update the docs.

**Comment by YQ-Wang** [comment]
Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.

**Comment by wilsonwang371** [comment]
> Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.

thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml

Please take a look at this.

**Comment by YQ-Wang** [comment]
> > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> 
> thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> 
> Please take a look at this.

Are there any yamls without using KubeRay?

**Comment by wilsonwang371** [comment]
> > > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> > 
> > 
> > thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> > Please take a look at this.
> 
> Are there any yamls without using KubeRay?

i didn't get this part. what do you want here?

**Comment by ring-pete** [comment]
> > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> 
> thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> 
> Please take a look at this.

Does this map cleanly to non-kubernetes Ray clusters, or is that not a supported configuration yet?

**Comment by wilsonwang371** [comment]
> > > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> > 
> > thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> > 
> > Please take a look at this.
> 
> Does this map cleanly to non-kubernetes Ray clusters, or is that not a supported configuration yet?

Do u mean using external redis cluster that is outside kubernetes?

**Comment by ring-pete** [comment]
> > > > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> > > 
> > > 
> > > thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> > > Please take a look at this.
> > 
> > 
> > Does this map cleanly to non-kubernetes Ray clusters, or is that not a supported configuration yet?
> 
> Do u mean using external redis cluster that is outside kubernetes?

I mean not running a ray cluster in kubernetes.  my specific use case is a ray cluster on aws, and the goal is to have an HA head node.  thanks!

**Comment by wilsonwang371** [comment]
> > > > > Hey @wilsonwang371 , may I ask what is the current status for the external redis doc? If possible, it would be great to have a sample yaml file [like this](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml) for the external redis feature.
> > > > 
> > > > 
> > > > thanks for asking. currently, there is one yaml for external redis. https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml
> > > > Please take a look at this.
> > > 
> > > 
> > > Does this map cleanly to non-kubernetes Ray clusters, or is that not a supported configuration yet?
> > 
> > 
> > Do u mean using external redis cluster that is outside kubernetes?
> 
> I mean not running a ray cluster in kubernetes. my specific use case is a ray cluster on aws, and the goal is to have an HA head node. thanks!

currently, kuberay supports ray FT. If you need external redis, you can specify external redis using  RAY_REDIS_ADDRESS. You can take a look at the GCS FT document here: https://github.com/ray-project/kuberay/blob/master/docs/guidance/gcs-ft.md

**Comment by ring-pete** [comment]
Thanks @wilsonwang371 - i tested setting this on my end where I'm *not* running k8s and unfortunately it prevents the ray process from starting.  Here's an example:

```
export RAY_REDIS_ADDRESS="external-redis.host.com:6379" ; ray start  --head
<snip backtrace>
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/pete/ray/lib64/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1664215625.247040060","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1664215625.247039210","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

I've done a bit of exploration in the code base but it wasn't immediately obvious to me why this was not working as expected.

**Comment by wilsonwang371** [comment]
Here is how we use this variable:

![image](https://user-images.githubusercontent.com/3913185/192350283-5af96161-5f12-47c7-99d7-e6092c8b559b.png)

It seems like there are some connection issues in our case.

BTW, In order to use Ray FT, you need to use Kuberay. A manually started Ray cluster does not support Ray FT.

**Comment by YQ-Wang** [comment]
There is an opening PR for deploying the static Ray cluster with external Redis. https://github.com/ray-project/ray/pull/28687 Please feel free to take a look.

**Comment by DmitriGekhtman** [comment]
@iycheng @scv119 @jjyao could one of you triage/assign this -- we're getting a lot of questions from users on this

**Comment by jjyao** [comment]
@DmitriGekhtman we will cover it in the new core fault tolerance doc.

**Comment by DmitriGekhtman** [comment]
Added some formal labelling to indicate that we're on top of it! :) :)
