### ISSUE TITLE
[Core]: Unable to get large tensor object when using NodeAffinitySchedulingStrategy

### ISSUE THREAD

**Issue by a2bhulla** [ray-project/ray#24990]
### What happened + What you expected to happen

I have a cluster with two nodes and I am running two asks that are scheduled via `NodeAffinitySchedulingStrategy`. Each task computes a torch.nn.Linear layer and then returns the output, but when the shape of the matmul output is greater than `(1, 1, 128, 128) (MM_DIM = 128)` then the script below fails with:

At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object bcde2377213065e6ffffffffffffffffffffffff3700000001000000

I am not sure why increasing the shape of tensors exposes this failure. Is there any way I can mitigate this?

### Versions / Dependencies

ray, version 2.0.0.dev0
torch: '1.10.0+cpu'

### Reproduction script

```python
import ray
import torch
import torch.nn as nn
from ray.util.scheduling_strategies import NodeAffinitySchedulingStrategy

MM_DIM = 160

@ray.remote
def stage_one(input_actv):
    print(f"stage one is running on: {ray._private.services.get_node_ip_address()}")
    time.sleep(2)
    stage_one_mm = nn.Linear(MM_DIM, MM_DIM)
    torch_hidden = stage_one_mm(input_actv)
    return torch_hidden


@ray.remote
def stage_two(hidden_actv):
    print(f"stage two is running on: {ray._private.services.get_node_ip_address()}")
    time.sleep(2)
    stage_two_mm = nn.Linear(MM_DIM, MM_DIM)
    output = stage_two_mm(hidden_actv)
    return output


if __name__ == "__main__":
    ray.init(address='auto')
    time.sleep(5)

    print(f"There are {len(ray.nodes())} nodes!")

    shape = (1, 1, MM_DIM, MM_DIM)
    input_actv = torch.randn(shape)

    object_ids = []
    for _ in range(1):
        stage_one_id = stage_one.options(scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=ray.nodes()[0]['NodeID'], soft=False)).remote(input_actv)
        stage_two_id = stage_two.options(scheduling_strategy=NodeAffinitySchedulingStrategy(node_id=ray.nodes()[1]['NodeID'], soft=False)).remote(stage_one_id)
        object_ids.append(stage_two_id)

    unfinished = object_ids
    while unfinished:
        finished, unfinished = ray.wait(unfinished, num_returns=1)
        result = ray.get(finished)
        print(f"I am post processing {result[0].shape} - there are still {len(unfinished)} unfinished tasks")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by mwtian** [comment]
From `ray.exceptions.OwnerDiedError: Failed to retrieve object bcde2377213065e6ffffffffffffffffffffffff3700000001000000`, it seems there is a crash. Can you provide logs from both nodes for `/tmp/ray/session_latest/raylet.out`?

**Comment by a2bhulla** [comment]
node 0 logs: node0-raylet.out and node 1 is node1-raylet.out
[raylet.zip](https://github.com/ray-project/ray/files/8742450/raylet.zip)

**Comment by a2bhulla** [comment]
I also see the same thing when I run the example from [data pipelining](https://docs.ray.io/en/master/data/pipelining-compute.html)

```
import ray
import time


def func1(i: int) -> int:
    return i + 1



def func2(i: int) -> int:
    return i * 2


if __name__ == "__main__":
    ray.init(address='auto')
    time.sleep(2)

    # Create a dataset and then create a pipeline from it.
    base = ray.data.range(100)
    print(base)
    
    pipe = base.window(blocks_per_window=10)
    print(pipe)

    # Applying transforms to pipelines adds more pipeline stages.
    pipe = pipe.map(func1)
    pipe = pipe.map(func2)
    
    print(pipe)

    # Output can be pulled from the pipeline concurrently with its execution.
    num_rows = 0
    for row in pipe.iter_rows():
        num_rows += 1


    print("Total num rows", num_rows)
```

**Comment by mwtian** [comment]
Thanks for the info. The logs from Raylet do not show crash. It is possible they are killed by the OS. The data size in the examples do not seem to large enough to trigger out-of-memory kills.

I'm unable to reproduce the issue for the script above. cc @clarkzinzow @jianoaix have you seen similar issues before?

**Comment by clarkzinzow** [comment]
@mwtian we haven't seen such issues on such small data, so I'm wondering if this might be OS/setup-specific, especially since it fails with core Ray as well. @a2bhulla what OS are you using?

**Comment by a2bhulla** [comment]
```
OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.29
```

**Comment by GoingMyWay** [comment]
Similar issue, ray 1.13.0, `ray.get()` is slower than before.

**Comment by GoingMyWay** [comment]
Note that, initially, ray.get() is 50-60% slower than 1.11.0. Then, after many timesteps of training, ray.get() is faster and gradually become normal. Note that such behaviour is not frequent. Ray may keep such a slower speed during the whole training process.

In my case, the size of the data fetched by `ray.get()` is `60*50*88*88*8`.
