### ISSUE TITLE
[Core] async_generator has serialization issue

### ISSUE THREAD

**Issue by raceychan** [ray-project/ray#25018]
### What happened + What you expected to happen

when running remote method on actor,
an exception would be raised indicates that async generator object is not supported.
(Actor pid=18493) TypeError: cannot pickle 'async_generator' object

say we have a method like this:

```python
    async def start(self):
        while self.mail_box:
            message = self.mail_box.pop()
            result = await self.handle(message)
            yield result
```
such method would cause the serialization problem

```python
Traceback (most recent call last):
  File "reproduce.py", line 42, in <module>
    asyncio.run(main())
  File "/home/race/miniconda3/envs/myes/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/race/miniconda3/envs/myes/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "reproduce.py", line 36, in main
    results = await asyncio.gather(
  File "/home/race/miniconda3/envs/myes/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
ray.exceptions.RayTaskError(TypeError): ray::Actor.send() (pid=30402, ip=172.23.135.226, repr=<reproduce.Actor object at 0x7feac042c310>)
  File "/home/race/miniconda3/envs/myes/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/race/miniconda3/envs/myes/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "reproduce.py", line 23, in send
    results = await target.receive.remote(sender=self, msg=msg)
ray.exceptions.RayTaskError(TypeError): ray::Actor.receive() (pid=30403, ip=172.23.135.226, repr=<reproduce.Actor object at 0x7f978c1212e0>)
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/serialization.py", line 413, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/serialization.py", line 391, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/serialization.py", line 353, in _serialize_to_pickle5
    raise e
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/serialization.py", line 348, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/race/miniconda3/envs/myes/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 621, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'async_generator' object

```

### Versions / Dependencies

ray = 1.12.0
python = 3.8.10

### Reproduction script

```python
import ray, asyncio

@ray.remote
class Actor:
    def __init__(self, name):
        self.name = name
        self.mail_box = list()

    async def receive(self, sender: "Actor", msg):
        self.mail_box.append(msg)
        async for result in self.start():
            yield result

    async def start(self):
        while self.mail_box:
            message = self.mail_box.pop()
            result = await self.handle(message)
            yield result

    async def send(self, target: "Actor", msg):
        results = await target.receive.remote(sender=self, msg=msg)
        return results

    async def handle(self, msg):
        await asyncio.sleep(1)
        print(f"finished process {msg=}")
        return 1


async def main():
    race = Actor.remote(name="race")
    andrew = Actor.remote(name="andrew")
    results = await asyncio.gather(
        *[race.send.remote(andrew, "hello"), race.send.remote(andrew, "world")]
    )


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by czgdp1807** [comment]
Let me look into this.

**Comment by czgdp1807** [comment]
After replacing `race = Actor(name="race")` with `race = Actor.remote(name="race")` and `andrew = Actor(name="andrew")` with `andrew = Actor.remote(name="andrew")`, I executed your script and got the following error,

```bash
2022-05-20 10:13:06,537 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "../debug.py", line 60, in <module>
    asyncio.run(main())
  File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "../debug.py", line 54, in main
    race = Actor.remote(name="race")
  File "c:\users\gagan\ray_project\ray\python\ray\actor.py", line 522, in remote
    return self._remote(args=args, kwargs=kwargs, **self._default_options)
  File "c:\users\gagan\ray_project\ray\python\ray\util\tracing\tracing_helper.py", line 383, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "c:\users\gagan\ray_project\ray\python\ray\actor.py", line 808, in _remote
    creation_args = signature.flatten_args(function_signature, args, kwargs)
  File "c:\users\gagan\ray_project\ray\python\ray\_private\signature.py", line 114, in flatten_args
    raise TypeError(str(exc)) from None
TypeError: got an unexpected keyword argument 'name'
```

**Comment by raceychan** [comment]
> After replacing `race = Actor(name="race")` with `race = Actor.remote(name="race")` and `andrew = Actor(name="andrew")` with `andrew = Actor.remote(name="andrew")`, I executed your script and got the following error,
> 
> ```shell
> 2022-05-20 10:13:06,537 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8265
> Traceback (most recent call last):
>   File "../debug.py", line 60, in <module>
>     asyncio.run(main())
>   File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\ProgramData\Anaconda3\envs\ray_dev\lib\asyncio\base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "../debug.py", line 54, in main
>     race = Actor.remote(name="race")
>   File "c:\users\gagan\ray_project\ray\python\ray\actor.py", line 522, in remote
>     return self._remote(args=args, kwargs=kwargs, **self._default_options)
>   File "c:\users\gagan\ray_project\ray\python\ray\util\tracing\tracing_helper.py", line 383, in _invocation_actor_class_remote_span
>     return method(self, args, kwargs, *_args, **_kwargs)
>   File "c:\users\gagan\ray_project\ray\python\ray\actor.py", line 808, in _remote
>     creation_args = signature.flatten_args(function_signature, args, kwargs)
>   File "c:\users\gagan\ray_project\ray\python\ray\_private\signature.py", line 114, in flatten_args
>     raise TypeError(str(exc)) from None
> TypeError: got an unexpected keyword argument 'name'
> ```
thanks for the quick reply, i have edited my reproduce script to a correct version

**Comment by czgdp1807** [comment]
Thanks. I am able to reproduce your error now. Let me investigate what needs to be done to get this issue fixed.

**Comment by raceychan** [comment]
> Thanks. I am able to reproduce your error now. Let me investigate what needs to be done to get this issue fixed.

I have done a little research myself on this, and i am afraid that there is not quick fix for this, since the root of the issue is that python does not support pickling gengerator objects, i have found a issue to related to this
 "Make Generators Pickle-able"
https://bugs.python.org/issue1092962 
 and thus i assume async generator does not make a difference.
And at this point of time, i am not quite sure if this should be classified as a bug or it is actually a feature request, since its probably not a bug of ray but rather a nature of python pickle
should we find a way( either create a protocol or sth) to get generator supported?

**Comment by czgdp1807** [comment]
I checked. I think `yeild` results in a generator and its not possible to pickle generators. So may be you need to store the states of `receive` and `start` methods manually. Then whenever these methods are called first check if their respective states are available. If so then resume from there. Otherwise use the initial case for these functions.



> And at this point of time, i am not quite sure if this should be classified as a bug or it is actually a feature request, since its probably not a bug of ray but rather a nature of python pickle
> should we find a way( either create a protocol or sth) to get generator supported?

To support generators I think pickling approach has to be removed and something else should be used which satisfies the same purpose as pickling but also supports generators at the same time.

P.S. - https://stackoverflow.com/questions/28963354/typeerror-cant-pickle-generator-objects

**Comment by raceychan** [comment]
> I checked. I think `yeild` results in a generator and its not possible to pickle generators. So may be you need to store the states of `receive` and `start` methods manually. Then whenever these methods are called first check if their respective states are available. If so then resume from there. Otherwise use the initial case for these functions.
> 
> > And at this point of time, i am not quite sure if this should be classified as a bug or it is actually a feature request, since its probably not a bug of ray but rather a nature of python pickle
> > should we find a way( either create a protocol or sth) to get generator supported?
> 
> To support generators I think pickling approach has to be removed and something else should be used which satisfies the same purpose as pickling but also supports generators at the same time.
> 
> P.S. - https://stackoverflow.com/questions/28963354/typeerror-cant-pickle-generator-objects

yeah i looked up to that question too, thanks for your suggestion, im closing the issue for now

**Comment by czgdp1807** [comment]
If you want, I can think of a way to manually deal with `yeild`. Basically `yeild` returns a generator and pauses the function there. In the next call it resumes from there, right? So, may be we can do this manually without using `yeild`. If its okay with you I can try to figure out a way to get your script running without `yeild`. Just let me know.

**Comment by raceychan** [comment]
> If you want, I can think of a way to manually deal with `yeild`. Basically `yeild` returns a generator and pauses the function there. In the next call it resumes from there, right? So, may be we can do this manually without using `yeild`. If its okay with you I can try to figure out a way to get your script running without `yeild`. Just let me know.

it would be great if you can do that, and I appreciate it even if you don't! Please go ahead and give it a shot

**Comment by czgdp1807** [comment]
Let me try using `cloudpickle-generators`, and also try implementing `yeild` mannualy for @raceychan. Re-opening the issue.

**Comment by czgdp1807** [comment]
Its a bit typical to integrate `cloudpickle-generators`. I applied the following diff in `cloudpickle-generators` and called `cloudpickle_generators.register()` at a bunch of places but still it didn't work. Probably we need to only import `cloudpickle` as is and then call `dumps` as `cloudpickle.dumps`. Not sure if I should give more time to integrating `cloudpickle-generators`.

```diff
diff --git a/cloudpickle_generators/_core.c b/cloudpickle_generators/_core.c
index a79d07c..92618cb 100644
--- a/cloudpickle_generators/_core.c
+++ b/cloudpickle_generators/_core.c
@@ -44,7 +44,7 @@ PyGetSetDef unset_value_getsets[] = {
 };

 static PyTypeObject unset_value_type = {
-    PyVarObject_HEAD_INIT(&PyType_Type, 0)
+    PyVarObject_HEAD_INIT(NULL, 0)
     "cloudpickle_generators._core.unset_value_type",  /* tp_name */
     sizeof(PyObject),                                 /* tp_basicsize */
     0,                                                /* tp_itemsize */
@@ -143,7 +143,7 @@ PyMethodDef try_block_methods[] = {
 };

 PyTypeObject try_block_type = {
-    PyVarObject_HEAD_INIT(&PyType_Type, 0)
+    PyVarObject_HEAD_INIT(NULL, 0)
     "cloudpickle_generators._core.try_block",   /* tp_name */
     sizeof(try_block_object),                   /* tp_basicsize */
     0,                                          /* tp_itemsize */
diff --git a/setup.py b/setup.py
index 572f0c2..354b4ae 100644
--- a/setup.py
+++ b/setup.py
@@ -1,10 +1,21 @@
 #!/usr/bin/env python
 from setuptools import setup, Extension
+from sys import platform


 with open('README.rst') as f:
     long_description = f.read()

+
+if platform == "win32":
+if platform == "win32":
+    extra_compile_args = []
+else:
+    extra_compile_args=[
+        '-Wall',
+        '-Wextra',
+        '-Wno-missing-field-initializers',
+    ]
+
 setup(
     name='cloudpickle-generators',
     version='0.1.0',
@@ -41,11 +52,7 @@ setup(
         Extension(
             'cloudpickle_generators._core',
             ['cloudpickle_generators/_core.c'],
-            extra_compile_args=[
-                '-Wall',
-                '-Wextra',
-                '-Wno-missing-field-initializers',
-            ]
+            extra_compile_args=extra_compile_args
         ),
     ],
     install_requires=['cloudpickle'],
```

**Comment by czgdp1807** [comment]
> also try implementing `yeild` mannualy for @raceychan.

Hi. I tried something and it seems to be giving outputs (not sure if its correct output).

```python
import ray, asyncio

@ray.remote
class Actor:
    def __init__(self, name):
        self.name = name
        self.mail_box = list()
        self.start_state = {}

    async def receive(self, sender: "Actor", msg):
        self.mail_box.append(msg)
        _ = await self.start()
        index = self.start_state["index"]
        status = self.start_state["status"]
        return status[index]

    async def start(self):
        while self.mail_box:
            message = self.mail_box.pop()
            result = await self.handle(message)
            current_index = self.start_state.get("index", -1)
            self.start_state["index"] = current_index + 1
            if "status" not in self.start_state:
                self.start_state["status"] = []
            self.start_state["status"].append(result)
            return result

    async def send(self, target: "Actor", msg): 
        results = await target.receive.remote(sender=self, msg=msg)
        return results

    async def handle(self, msg):
        await asyncio.sleep(1)
        print(f"finished process {msg=}, {self}")
        return 1


async def main():
    race = Actor.remote(name="race")
    andrew = Actor.remote(name="andrew")
    results = await asyncio.gather(
        *[race.send.remote(andrew, "hello"), race.send.remote(andrew, "world")]
    )


if __name__ == "__main__":
    asyncio.run(main())
```

**Output**

```bash
2022-05-21 10:29:32,242 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8265
(Actor pid=2472) finished process msg='hello', <debug.Actor object at 0x0000026D4248FB80>
(Actor pid=2472) finished process msg='world', <debug.Actor object at 0x0000026D4248FB80>
```

**Comment by raceychan** [comment]
> ```python
>             message = self.mail_box.pop()
>             result = await self.handle(message)
>             current_index = self.start_state.get("index", -1)
> ```

i didnt have a chance to get into cloudpickle-generators before so the c code seems a bit overwhelming to me, are you suggesting that cloudlepickle-generators does not work (at least in your attemps) in this case?

**Comment by czgdp1807** [comment]
> are you suggesting that cloudlepickle-generators does not work (at least in your attemps) in this case?

Yeah, they don't work in my attempts. I tried to place it at a bunch of places in the ray code base but it doesn't work.

**Comment by raceychan** [comment]
> 

Yes sir, it is the correct output, it was brilliant how you did it.
let me make sure i did not get you wrong.
so what are you doing here is creating a dictrionary as a cotainer for the purpose of storing results.
basically,
while there are messages in the mail_box, for each message,
we process it then save it to the list acceessible by start_state['status'] 
and also save the index(order number of the result) to start_stat['index'], 
so the caller can get the result by calling status[index].


```python
# this would be a simplified version if i got it right
@ray.remote
class Actor:
    def __init__(self, name):
        self.name = name
        self.mail_box = list()
        self.start_state = []

    async def receive(self, sender: "Actor", msg):
        self.mail_box.append(msg)
        index = await self.start()
        return self.start_state[index] if index else None

    async def start(self):
        while self.mail_box:
            message = self.mail_box.pop()
            result = await self.handle(message)
            index = len(self.start_state) + 1
            self.start_state.append(result)
            return index
```

however, my main concern here is the usage of memory, 
 as the results returned by handle(msg) could be really big,
i was trying to use yield result to get help by the gc, and it seems that if we save results in start_stat['status'] without deleting elements inside from time to time, it will eventually gets too big.

**Comment by czgdp1807** [comment]
> however, my main concern here is the usage of memory,
as the results returned by handle(msg) could be really big,

We can remove already referred indices from the list. May be instead of a list use `dict` with index to status mapping. An index after being removed should be removed from the `dict`.

**Comment by czgdp1807** [comment]
@raceychan Here is a code which removes previously referred indices once they are used. Hope this should help with the memory issues in your use case.

```python
import ray, asyncio

@ray.remote
class Actor:
    def __init__(self, name):
        self.name = name
        self.mail_box = list()
        self.start_state = {}

    async def receive(self, sender: "Actor", msg):
        self.mail_box.append(msg)
        _ = await self.start()
        index = self.start_state["index"]
        status = self.start_state["status"]
        ret_value = status[index]
        status.pop(index)
        return ret_value

    async def start(self):
        while self.mail_box:
            message = self.mail_box.pop()
            result = await self.handle(message)
            current_index = self.start_state.get("index", -1)
            self.start_state["index"] = current_index + 1
            if "status" not in self.start_state:
                self.start_state["status"] = {}
            self.start_state["status"][current_index + 1] = result
            return result

    async def send(self, target: "Actor", msg): 
        results = await target.receive.remote(sender=self, msg=msg)
        return results

    async def handle(self, msg):
        await asyncio.sleep(1)
        print(f"finished process {msg=}, {self}")
        return 1


async def main():
    race = Actor.remote(name="race")
    andrew = Actor.remote(name="andrew")
    results = await asyncio.gather(
        *[race.send.remote(andrew, "hello"), race.send.remote(andrew, "world")]
    )


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by raceychan** [comment]
> 

this is awesome, thank you! i think this works in my situation, you might close the issue
