### ISSUE TITLE
[Tune] WandbLoggerCallback misreports System Metrics

### ISSUE THREAD

**Issue by vonHartz** [ray-project/ray#25019]
### What happened + What you expected to happen

When using the WandbLoggerCallback, I expect the System tab in Wandb to display accurate system metrics. However, the reported memory use is wrong.

![wandb-system-report](https://user-images.githubusercontent.com/17391760/169515378-a98b6208-29b0-4b98-8a06-6ae124104577.png)

While Wandb reports a memory use of ~2GB, the run actually uses 4GB (and tries to use even more, such that is killed on the machine I'm running on).

\time -v outputs:
```
User time (seconds): 4243.26
System time (seconds): 177.90
Percent of CPU this job got: 80%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:31:45
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 3541884
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 461
Minor (reclaiming a frame) page faults: 4848172
Voluntary context switches: 32429207
Involuntary context switches: 2147426
Swaps: 0
File system inputs: 67520
File system outputs: 168032
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 1
```

I know that there were memory leaks with DQN in the past, however afaik they were supposed to be resolved.

### Versions / Dependencies

Python 3.6.13
Ray 1.6.0
wandb 0.12.16

CentOS 7

### Reproduction script
```
from ray.tune.integration.wandb import WandbLoggerCallback

tune_config = {
    'buffer_size': 50000,
    'double_q': False,
    'dueling': False,
    'env': 'GymEnvWrapper',
    'env_config': 'Acrobot-v1',

    'evaluation_interval': 1,
    'final_prioritized_replay_beta': 0.5,
    'framework': 'tf',
    'learning_starts': 500,
    'lr': 0.001,
    'model': {
    	'conv_activation': 'relu',
        'conv_filters': [],
        'fcnet_hiddens': [512, 512],
        'use_lstm': False},
    'n_step': 1,
    'noisy': True,
    'num_atoms': 51,
    'prioritized_replay': False,
    'prioritized_replay_alpha': 0.5,
    'prioritized_replay_beta': 0.5,
    'sigma0': 0.1,
    'target_network_update_freq': 100,
    'timesteps_total': 20000,
    'train_batch_size': 128,
    'v_max': 100.0,
    'v_min': -100.0}


callbacks = [WandbLoggerCallback(
	project=WANDB_PROJECT,
	api_key_file=WANDB_API_KEY_FILE,
        log_config=True)]

run_name = 'dqn_test'

analysis = tune.run(
	'DQN,
	name=run_name,
	stop={
	    "timesteps_total": 1000000,
	},
	config=tune_config,
	callbacks=callbacks,
	checkpoint_at_end=True,
	local_dir='/tmp',
    )
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
Weights and biases reports the system metrics automatically. We don't feed anything into them. Thus it seems this is more of a weights and biases issue than a Ray/Rllib/Tune issue.

**Comment by scottsun94** [comment]
@vonHartz Is this issue resolved? Have you reported this issue to Weights and biases?

**Comment by scottsun94** [comment]
@vonHartz Ping ^

**Comment by vonHartz** [comment]
Apologies for the late reply!

I had the suspicion that this was linked to some memory leak within DQN.
However, I did not have the capacity to debug it further.
For this reason I did not report to wandb.
In the end I worked around it by using more RAM.
