### ISSUE TITLE
[Core] Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

### ISSUE THREAD

**Issue by mahuangxu** [ray-project/ray#25012]
### What happened + What you expected to happen

I got an error when running the following code with **multi-worker**:
ERROR:
```
(RolloutWorker pid=2591) E0520 15:17:56.430216750    2847 chttp2_transport.cc:1111]   **Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"**
(RolloutWorker pid=2592) E0520 15:17:56.429997321    2815 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2588) E0520 15:17:56.429843491    2814 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2590) E0520 15:17:56.430071007    2816 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2589) E0520 15:17:56.429672231    2782 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2589) 2022-05-20 15:17:56,437	ERROR worker.py:449 -- SystemExit was raised from the worker.
(RolloutWorker pid=2589) Traceback (most recent call last):
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 797, in ray._raylet.task_execution_handler
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 616, in ray._raylet.execute_task
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 656, in ray._raylet.execute_task
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 663, in ray._raylet.execute_task
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 667, in ray._raylet.execute_task
(RolloutWorker pid=2589)   File "python/ray/_raylet.pyx", line 614, in ray._raylet.execute_task.function_executor
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/_private/function_manager.py", line 701, in actor_method_executor
(RolloutWorker pid=2589)     return method(__ray_actor, *args, **kwargs)
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
(RolloutWorker pid=2589)     return method(self, *_args, **_kwargs)
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/actor.py", line 1324, in __ray_terminate__
(RolloutWorker pid=2589)     ray.actor.exit_actor()
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/actor.py", line 1412, in exit_actor
(RolloutWorker pid=2589)     ray.worker.disconnect()
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/worker.py", line 1672, in disconnect
(RolloutWorker pid=2589)     worker.gcs_error_subscriber.close()
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/_private/gcs_pubsub.py", line 306, in close
(RolloutWorker pid=2589)     self._stub.GcsSubscriberCommandBatch(req, timeout=5)
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/grpc/_channel.py", line 944, in __call__
(RolloutWorker pid=2589)     state, call, = self._blocking(request, timeout, metadata, credentials,
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/grpc/_channel.py", line 933, in _blocking
(RolloutWorker pid=2589)     event = call.next_event()
(RolloutWorker pid=2589)   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 338, in grpc._cython.cygrpc.SegregatedCall.next_event
(RolloutWorker pid=2589)   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 171, in grpc._cython.cygrpc._next_call_event
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/threading.py", line 246, in __enter__
(RolloutWorker pid=2589)     def __enter__(self):
(RolloutWorker pid=2589)   File "/home/mhx/anaconda3/envs/RLlib/lib/python3.8/site-packages/ray/worker.py", line 446, in sigterm_handler
(RolloutWorker pid=2589)     sys.exit(1)
(RolloutWorker pid=2589) SystemExit: 1
(RolloutWorker pid=2587) E0520 15:17:56.429773197    2750 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2596) E0520 15:17:56.430210222    2848 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2602) E0520 15:17:56.430515333    2867 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
(RolloutWorker pid=2601) E0520 15:17:56.430439596    2868 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
2022-05-20 15:17:56,547	INFO tune.py:701 -- Total run time: 250.95 seconds (250.69 seconds for the tuning loop).
```

### Versions / Dependencies

python 3.8

Package                  Version
------------------------ ---------
aiohttp                  3.8.1
aiohttp-cors             0.7.0
aioredis                 1.3.1
aiorwlock                1.3.0
aiosignal                1.2.0
anyio                    3.6.1
asgiref                  3.5.2
async-timeout            4.0.1
attrs                    21.2.0
blessed                  1.19.0
cachetools               4.2.4
certifi                  2021.10.8
charset-normalizer       2.0.7
click                    8.0.3
cloudpickle              1.6.0
colorful                 0.5.4
cycler                   0.11.0
Deprecated               1.2.13
dgl                      0.7.2
distlib                  0.3.4
dm-tree                  0.1.6
docutils                 0.18.1
fastapi                  0.78.0
filelock                 3.4.0
fonttools                4.28.2
frozenlist               1.2.0
future                   0.18.2
google-api-core          2.2.2
google-auth              2.3.3
googleapis-common-protos 1.53.0
gpustat                  1.0.0b1
grpcio                   1.42.0
gym                      0.18.0
h11                      0.13.0
hiredis                  2.0.0
idna                     3.3
imageio                  2.9.0
importlib-resources      5.4.0
jsonschema               4.2.1
kiwisolver               1.3.2
lz4                      3.1.3
matplotlib               3.5.0
mkl-fft                  1.3.1
mkl-random               1.2.2
mkl-service              2.4.0
msgpack                  1.0.2
multidict                5.2.0
networkx                 2.6.3
numpy                    1.21.4
nvidia-ml-py3            7.352.0
olefile                  0.46
opencensus               0.8.0
opencensus-context       0.1.2
packaging                21.3
pandas                   1.3.4
Pillow                   7.2.0
pip                      21.2.4
platformdirs             2.5.2
prometheus-client        0.12.0
protobuf                 3.19.1
psutil                   5.8.0
py-spy                   0.3.11
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pydantic                 1.9.1
pyglet                   1.5.0
pyparsing                3.0.6
pyrsistent               0.18.0
python-dateutil          2.8.2
pytz                     2021.3
PyWavelets               1.2.0
PyYAML                   6.0
ray                      1.12.1
redis                    4.0.2
requests                 2.26.0
rsa                      4.7.2
scikit-image             0.18.3
scipy                    1.7.1
setuptools               58.0.4
setuptools-scm           6.3.2
six                      1.16.0
smart-open               6.0.0
sniffio                  1.2.0
starlette                0.19.1
tabulate                 0.8.9
tensorboardX             2.4.1
tifffile                 2021.11.2
tomli                    1.2.2
torch                    1.10.0
torchaudio               0.10.0
torchvision              0.11.1
typing-extensions        3.10.0.2
urllib3                  1.26.7
uvicorn                  0.16.0
virtualenv               20.14.1
wcwidth                  0.2.5
wheel                    0.37.0
wrapt                    1.13.3
yarl                     1.7.2
zipp                     3.6.0

### Reproduction script
```
import ray
from ray import tune
from ray.rllib.agents.dqn import DQNTrainer
ray.shutdown()
ray.init()  
tune.run(DQNTrainer, config={"env": "CartPole-v0", 'framework': 'torch',"train_batch_size": 400,  'num_workers': 10, 'output': '/tmp/cartpole-out', 'output_max_file_size': 100}, checkpoint_at_end=True, checkpoint_freq=10, stop={'timesteps_total': 100000})
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by czgdp1807** [comment]
Let me look into this.

**Comment by czgdp1807** [comment]
I am able to train using your script. I don't get any error. However note that no GPUs are available on my machine. It has 8 CPUs and 16 GB RAM and its a windows machine. I changed `'num_workers': 10,` to `'num_workers': 7,` so that it matches with the number of CPUs I have.

**Comment by mwtian** [comment]
Thanks @mahuangxu for filing the bug report and @czgdp1807 for taking a look. I'm able to reproduce the issue on a Linux `m5.8xlarge` VM (32 vCPU). It seems GCS / Raylet is starved out of CPU when using 10 tune workers, becomes unresponsive and workers think the Raylet is dead. We can improve the robustness of health checking. Also running the script with #24928 fixed the issue as well.

**Comment by rkooo567** [comment]
Actually, I've seen this error before, and I think it is a core error due to some poor grpc configuration. cc @mwtian can you try reproducing the issue?

**Comment by rkooo567** [comment]
Btw, this could be also useful resource; https://stackoverflow.com/questions/66271810/grpc-error-on-long-connections-too-many-pings!
