### ISSUE TITLE
Use more modern python for official docker image

### ISSUE THREAD

**Issue by Tehada** [ray-project/ray#25024]
### Description

Official ray docker image uses python 3.7.7, which is quite ancient, tbh. [Pandas](https://pypi.org/project/pandas/) doesn't even support python below version 3.8. Also, many cool features have arrived in python since 3.7.7. Can we use ubuntu:22.04 for base image, which has python 3.10.4 in official repos? I was using custom docker image for ray with python 3.9.9, but it was quite a _pita_ to setup it correctly with required os dependencies and user. Still I have sometimes confusing problems due to differencies from official image -- ray assumes the presence of some deps in image (especially for cluster runs, which I use a lot). I would like to just use officially supported image of ray to run on clusters to avoid additional maintainace from my side, but with modern python. It seems that ray also should start to support python 3.10 (which should be easy, since 3.9 is already supported).

**Comment by mwtian** [comment]
Actually Ray does provide different docker images with Python 3.6~3.9, with Python 3.10 coming. For Python 3.9 images, you can find them in this list: https://hub.docker.com/r/rayproject/ray/tags?page=1&name=1.12.1-py39

I will update Ray documentation for docker image support.

**Comment by mwtian** [comment]
Pages that need to be updated:
https://docs.ray.io/en/latest/ray-overview/installation.html#docker-source-images
https://hub.docker.com/r/rayproject/ray

**Comment by Tehada** [comment]
Thanks, this is exactly, what I was looking for!
