### ISSUE TITLE
Jenkins test hanging problem

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#2503]
### System information
- **OS Platform and Distribution (Linux): amplab.cs.berkeley.edu/jenkins**:
- **Ray installed from**: source
- **Ray version**: 0.5
- **Python version**: 2.7
- **Exact command to reproduce**: This is observed in Jenkins, but not every time. 

### Describe the problem

Recently, the Jenkins tests failed mostly during test timeout. I push many [commits](https://github.com/ray-project/ray/pull/2490) trying to find out the cause.

After I updated the test to Python3, I managed to find some hints. I can print out the message when the subprocess is hanging. 
2 typical cases:
- https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6954/console
- https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/6953/console

Typical error message is:
```bash
STDERR:
The actor with ID bc4cea973e75ff180c3e3f8f4ca202d3624960f9 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 1 GPU 
The actor with ID b4c3cc8fa622e91644c105c877b6f9282997bcd1 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 1 GPU 
The actor with ID 7240f12807d73067e799c1dc651760544ac6bff5 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 1 GPU 
The actor with ID de611848ed65b64a9e2db423175f973f0b5ae0c3 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 1 GPU 
The actor with ID 4c1194a195a8b43d1d51c34d8c03f417590cc169 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 CPU 1 GPU 
Suppressing duplicate error message.
Suppressing duplicate error message.
some more : "Suppressing duplicate error message..."
```
The conclusion is that this is not a environment issue. It may be caused by some concurrent issue or the resource is too heavy for the requests.

**Comment by guoyuhong** [comment]
@raulchen Do you have some hint about this problem? Is it related to [this issue](https://github.com/ray-project/ray/issues/2449) ?

**Comment by raulchen** [comment]
I don't think it's related to #2495.

**Comment by guoyuhong** [comment]
@robertnishihara @pcmoritz Do you have any ideas about this issue?

**Comment by robertnishihara** [comment]
This is in `many_drivers_test.py`?

I haven't had a chance to look into it yet. Is it possible that resources are not being released properly when drivers exit? It's probably worth trying the test in xray and seeing if that fixes it, since it may not be worth tracking down the issue in legacy ray.
