### ISSUE TITLE
[Core | Python3.10] Upgrade pytest and fix all tests.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#25030]
### What happened + What you expected to happen

We need upgrade pytest to 6.2.4 to support python 3.10. However a bunch of tests are failing once we upgrade them.

### Versions / Dependencies

latest master / python 3.10

### Reproduction script

python ray/tests/...

**Comment by rkooo567** [comment]
cc @rickyyx @scv119 this is TODO for python 3.10

**Comment by rickyyx** [comment]
This could be closed right?
