### ISSUE TITLE
[Core] Potential Ray Memory Leak 

### ISSUE THREAD

**Issue by KMayank29** [ray-project/ray#25064]
I have just started using Ray Core to process large amount of documents in parallel. Right now I am developing a system on single node but unfortunately I ran into trouble due to potential leak of the Ray memory.
After the process ends it doesn't release the memory and I can see the Actors alive on `htop` .

**Dependencies**

- python: 3.9
- ray: 1.12.1
- ubuntu: 20.04 LTS
- spacy: v3.x

Below is the code architecture:

```python  
# driver.py
import ray

ray.init()
process_actors = [DataProcessor.remote(*args) for i in range(num_processes)]
ray.get([process_actor.process.remote() for process_actor in process_actors])
```

```python
# actor.py
@ray.remote
class DataProcessor:
    def __init__(self,*args):
        # init here
        
    def get_batch(self):
        '''
        The method returns batch of documents based on skip-query that is based on offset.
        '''
        for offset in range(*args):
            query = query_skip(*args)
            result = fetch_aggregate_data_from_mongo(query, *args)
            yield result
        
    def process(self):
        '''
        '''
        mongo_dataloader = self.get_batch()
        for i, results in enumerate(mongo_dataloader):
           batch_clean_articles = get_clean_text(*args)
        return True
```

```python
# nr_block.py

def get_clean_text(*args):
    # do something here....
    return result_nn
# result_nn:list of article objects
```
The memory constantly keep growing after each iteration of the process. It never releases. Please help me here.
![Screenshot from 2022-05-22 17-58-27](https://user-images.githubusercontent.com/36352999/169695176-a406b8a0-228a-4f8c-a38d-687e25e34986.png)

Thanks
Mayank

**Comment by robertnishihara** [comment]
Thanks for posting!

To make sure we understand what you are observing, can you confirm if each of the below points is correct?
1. The driver application runs successfully to completion and returns the intended results.
2. After the driver has exited successfully, the actor processes are still alive (as seen in htop).
3.  Each actor appears to be using a lot of memory (I assume you're referring to the **VIRT** column in htop, or are you looking at the **MEM%** column). Can you clarify how you know the actors are using a lot of memory?

**Comment by robertnishihara** [comment]
Additionally, I read through your code, but is it possible to share a runnable example that reproduces the problem

**Comment by robertnishihara** [comment]
Glad to hear it!
