### ISSUE TITLE
[Core] Infinite retry when spill fails

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#25085]
### What happened + What you expected to happen

When spilling an object fails due to 
```
2022-05-20 14:45:03,120 WARNING worker.py:1416 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 896, in ray._raylet.spill_objects_handler
  File "python/ray/_raylet.pyx", line 899, in ray._raylet.spill_objects_handler
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 666, in spill_objects
    return _external_storage.spill_objects(object_refs, owner_addresses)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 307, in spill_objects
    return self._write_multiple_objects(f, object_refs, owner_addresses, url)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/external_storage.py", line 137, in _write_multiple_objects
    raise ValueError(error)
ValueError: object ref 1c367dd987a9a540ffffffffffffffffffffffff0300000023000000 does not exist.
An unexpected internal error occurred while the IO worker was spilling objects: object ref 1c367dd987a9a540ffffffffffffffffffffffff0300000023000000 does not exist
```
seems it just keeps retrying.

Might be related to https://github.com/ray-project/ray/issues/17017

https://console.anyscale.com/o/anyscale-internal/projects/prj_JS35jSrv5JFxMqSZmQG7Yif7/clusters/ses_AAwENUbpq7JbYX5ueqMd55p5?command-history-section=command_history

### Versions / Dependencies

master

### Reproduction script

push-based shuffle chaos test

**Comment by stephanie-wang** [comment]
Do you know if this bug is blocking progress or is it just spurious logs?

**Comment by jjyao** [comment]
I think it will block: if we cannot spill, we cannot make room for pulling task args. But I need to double confirm that, it's not consistently happening though.

**Comment by stephanie-wang** [comment]
Came across this issue too during a test where the raylet is failing. Looks like it's because, after several retries, the owner marks the ObjectRef as failed and stores this as an error in plasma. Then the IO worker fails to spill it because of [this line](https://github.com/ray-project/ray/blob/master/python/ray/external_storage.py#L132). I'm not sure why it doesn't print the error about the metadata length, although that check also seems a bit fragile.
