### ISSUE TITLE
[air] Have a create_compatible_checkpoint convenient method

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#25094]
### What happened + What you expected to happen

In case that user only wants to use ray serve/batch prediction in a piecemeal fashion.
The generated checkpoint should also have preprocessors (although not fitted during training phase) if relevant.

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
I think we should consider this approach instead: https://github.com/ray-project/ray/issues/24977. I believe this will allow us to use BatchPredictor or ModelWrapperDeployment in a way that is agnostic to the Checkpoint.

**Comment by amogkam** [comment]
Resolved by #25444!
