### ISSUE TITLE
[Datasets] Add outputs to the `ray.data.range_*` examples

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25105]
### Description

Add outputs to the `ray.data.range_*` examples in the Ray Data API reference.

### Use case

The examples for `ray.data.range_*` functions don't show outputs.

```
>>> ds = ray.data.range_tensor(1000, shape=(3, 10))
>>> ds.map_batches(lambda arr: arr * 2, batch_format="pandas").show()
```

It'd be helpful to see what the data actually looks like.

```
>>> ds = ray.data.range_tensor(10, shape=(3,))
>>> ds.show(2)
{'value': array([0, 0, 0])}
{'value': array([1, 1, 1])}
```

**Comment by clarkzinzow** [comment]
@bveeramani This exists in the "Creating Datasets" docs in latest master, are you referring to in the API docs? https://docs.ray.io/en/master/data/creating-datasets.html#generating-synthetic-data

**Comment by bveeramani** [comment]
Yeah, I'm talking about the API reference. Updated the commented to clarify
