### ISSUE TITLE
[AIR] `TensorflowPredictor` adds extra axis

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25119]
### What happened + What you expected to happen

Here's the traceback:

> Traceback (most recent call last):
  File "module.py", line 20, in <module>
    predictions = predictor.predict(data)
  File "/private/tmp/.venv/lib/python3.8/site-packages/ray/ml/predictors/integrations/tensorflow/tensorflow_predictor.py", line 150, in predict
    prediction = model(tensor).numpy().ravel()
  File "/private/tmp/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/private/tmp/.venv/lib/python3.8/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
    raise ValueError(f'Input {input_index} of layer "{layer_name}" is '
ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 2), found shape=(4, 1, 2)

I expected Input 0 to have shape (4, 2) instead of (4, 1, 2).

### Versions / Dependencies

Ray: 4444150c2920f7c583a84eadadca649341c80d88
Python: 3.8.12
OS: MacOS

### Reproduction script

```
import numpy as np
import tensorflow as tf
from ray.ml.predictors.integrations.tensorflow import TensorflowPredictor

in_features = 2
out_features = 1
batch_size = 4

def build_model():
    return tf.keras.Sequential(
        [
            tf.keras.layers.InputLayer(input_shape=(in_features,)),
            tf.keras.layers.Dense(out_features),
        ]
    )

predictor = TensorflowPredictor(model_definition=build_model)

data = np.zeros(shape=(batch_size, in_features))
predictions = predictor.predict(data)
```

**Comment by peytondmurray** [comment]
Hi @bveeramani, I took a few minutes to look at this issue today. It looks like `TensorflowPredictor.predict` inadvertently adds a new axis to the input data when `predict()` is called without a `feature_columns` kwarg. I'll make a fix for this now, thanks for pointing this out!

**Comment by peytondmurray** [comment]
Ahh, I see you've already merged the change here: https://github.com/ray-project/ray/commit/fb22bc5ae3bed199e59586e8c6056788841feb50. Leaving this for now.
