### ISSUE TITLE
[AIR] Enable GPU prediction

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#25111]
### Description

Predictors for neural network inference (TorchPredictor, TFPredictor) can often leverage GPUs for inference (either offline or online).

Currently our deep learning predictors do not provide the ability to move the model to a GPU device for prediction.

### Use case

GPU inference with AIR predictors.

**Comment by ericl** [comment]
Closed by https://github.com/ray-project/ray/pull/26251
