### ISSUE TITLE
[Docs] [Serve] Have a consistent landing page style

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#25127]
### What happened + What you expected to happen

Serve landing page: https://docs.ray.io/en/master/serve/index.html

Datasets landing page: https://docs.ray.io/en/master/data/dataset.html

I think Serve should also have different "blocks" for *Getting Started* etc just like Datasets

### Versions / Dependencies

<= 1.13.0

### Reproduction script

None (this is a Docs issue)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by emjames** [comment]
Hi @zhe-thoughts, I gave it a go with #26029.

I look forward to your suggestions!
