### ISSUE TITLE
[AIR] Incorrect function names in `TorchTrainer` and `TensorflowTrainer` examples

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25143]
### What happened + What you expected to happen

The `train_loop_per_worker` code snippets contain `train.get_world_size()`, `train.get_world_rank()`, and `train.get_local_rank()`. But, those functions don't exist. The actual names are `train.world_size()`, `train.world_rank()` and `train.local_rank()`.

### Versions / Dependencies

N/A

### Reproduction script

See:
* https://docs.ray.io/en/master/ray-air/package-ref.html#ray.ml.train.integrations.tensorflow.TensorflowTrainer
* https://docs.ray.io/en/master/ray-air/package-ref.html#ray.ml.train.integrations.torch.TorchTrainer 

### Issue Severity

Low: It annoys or frustrates me.

**Comment by PranaySewatkar** [comment]
I would like to work on this issue ,if anyone working on it please let me know

**Comment by bveeramani** [comment]
>  I would like to work on this issue ,if anyone working on it please let me know

I don't think anyone's picked this up yet, so go for it!

**Comment by PranaySewatkar** [comment]
This comment is others who will see this comment in maybe after one or more days, that i am working on this issue, so don't work on it .

**Comment by Ariyaman** [comment]
Hi @PranaySewatkar i just had a question whether you are working on this issue till date or can i pick this up?

**Comment by Ariyaman** [comment]
Hi @bveeramani , I have raised a Draft PR to resolve this issue, please have a look whenever you get the chance. Thanks!

**Comment by PranaySewatkar** [comment]
I am working on this issue, my college exams ends yesterday, I am working
on it

**Comment by amogkam** [comment]
This is already closed- no need to work on this issue anymore
