### ISSUE TITLE
[Release] Ray 1.12.1 does not support Mac M1 

### ISSUE THREAD

**Issue by consultant-xyz** [ray-project/ray#25154]
Can not install ray 1.12.1 for mac M1.

**Comment by pcmoritz** [comment]
What is the error message you are getting?

**Comment by consultant-xyz** [comment]
It looks like the version is not released for mac M1.

**Comment by amogkam** [comment]
What python version do you have @consultant-xyz? M1 wheels are only build for Python 3.8 and 3.9.

**Comment by consultant-xyz** [comment]
On Python 3.9.

The latest version I can get is 1.12.0.

**Comment by amogkam** [comment]
@consultant-xyz can you try downloading from this link directly: https://files.pythonhosted.org/packages/17/a4/0949c91dbe54f3c5f1868b1fc145056c30d4031f77e131eb3027bd31b6f8/ray-1.12.1-cp39-cp39-macosx_10_15_x86_64.whl

**Comment by amogkam** [comment]
This wheel is there under the download files (https://pypi.org/project/ray/1.12.1/#files), though I'm not sure why it's complaining that there's no matching distribution.

**Comment by consultant-xyz** [comment]
In the pypi site, there is one file less for mac version 1.12.1 than version 1.12.0.

**Comment by consultant-xyz** [comment]
@amogkam this file does not work for m1. For m1, we need wheel like 
ray-1.12.0-cp38-cp38-macosx_11_0_arm64.whl

**Comment by consultant-xyz** [comment]
@amogkam There is no release for **-macosx_11_0_arm64.whl under the download files (https://pypi.org/project/ray/1.12.1/#files)

**Comment by amogkam** [comment]
Ah I see, I think I messed up in the upload process at some point. Let me upload them to Pypi as well. Sorry about the confusion!

**Comment by consultant-xyz** [comment]
Thanks!

**Comment by amogkam** [comment]
@consultant-xyz they have been uploaded! Can you try again?

**Comment by consultant-xyz** [comment]
@amogkam Thanks! It's working now.
