### ISSUE TITLE
[AIR] Document how to perform per-epoch shuffling

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25164]
### What happened + What you expected to happen

I want to shuffle my data every epoch, but there're no examples of how to do so with AIR.

There's an explanation of how to perform per-epoch shuffling with `DatasetPipeline`s, but AFAIK we're not supposed to use those with AIR?

Also see #24159 

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
This can be a small section added to https://docs.ray.io/en/master/ray-air/check-ingest.html

**Comment by richardliaw** [comment]
This is added
