### ISSUE TITLE
Cannot install wheel in docker

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#2516]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux d16d046fe9fa 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Ray installed from (source or binary)**:  source
- **Ray version**: 0.5.0
- **Python version**: Python 2.7.12 :: Anaconda 4.2.0 (64-bit)
- **Exact command to reproduce**:
pip install -U ray-0.5.0-cp36-cp36m-manylinux1_x86_64.whl

### Describe the problem

Install wheel inside a docker reported "not supported on this platform"

root@d16d046fe9fa:~# pip install -U ray-0.5.0-cp36-cp36m-manylinux1_x86_64.whl
ray-0.5.0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.

Do we have a way to do this in docker?

**Comment by robertnishihara** [comment]
I don't think this is related to docker. Since you are using Python 2.7, you need to install the wheel for Python 2.7 (the one you have is for 3.6).

**Comment by zhijunfu** [comment]
I see. Thanks!
