### ISSUE TITLE
[core][tests] Make dataset_shuffle_push_based_random_shuffle_1tb release test stable

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#25163]
### Description

This test is still flaky. It sometimes fails from workers crashing, most likely due to heap memory pressure.

**Comment by mwtian** [comment]
As mentioned in the sync up today, last 3 failures seem unrelated to Ray core stability / scalability:
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_T7NKdee42gmw2EmjhZ4KZFVa?command-history-section=command_history
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_BaQvEcFkrTvpmey8eNBJ8LRn?command-history-section=command_history
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_5C3BTR5pgGi8YDPyw3fDuyTa?command-history-section=command_history

**Comment by jjyao** [comment]
Already marked as stable.
