### ISSUE TITLE
[AIR] [Serve] Make tensor response less jank

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25166]
### What happened + What you expected to happen

Made a prediction against a deployed image classifier.

Got a janky looking response

```
(my-deployment pid=6230) INFO 2022-05-24 13:32:24,066 my-deployment my-deployment#NtySnw replica.py:478 - HANDLE __call__ OK 0.3ms
{'predictions': {'0': {'_tensor': [-0.7282236814498901,
    -2.272658348083496,
    -1.0713495016098022,
    -0.7097852826118469,
    -1.4099732637405396,
    -1.3684065341949463,
    -3.6283068656921387,
    -1.8969759941101074,
    -0.40979599952697754,
    -2.529226779937744]}}}
```

Expected something like

```
{'predictions': [[-0.7282236814498901,
    -2.272658348083496,
    -1.0713495016098022,
    -0.7097852826118469,
    -1.4099732637405396,
    -1.3684065341949463,
    -3.6283068656921387,
    -1.8969759941101074,
    -0.40979599952697754,
    -2.529226779937744]]}
```

### Versions / Dependencies

Ray: 1c2810085535ec42e6a1ee46f9d11a8484998903
Python: 3.8.12
OS: MacOS

### Reproduction script

Run #24633.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by edoakes** [comment]
@simon-mo

**Comment by simon-mo** [comment]
Looks like the main issue is tf predictor returns dataframe when you pass in numpy array. This should be part of @amogkam's predictor unification work.
