### ISSUE TITLE
[Core][GCS] Raylet crashes after losing connection to GCS

### ISSUE THREAD

**Issue by mwtian** [ray-project/ray#25175]
### What happened + What you expected to happen

This has been fairly common in nightly tests with many worker OOM kills, e.g. currently for `dataset_shuffle_push_based_random_shuffle_1tb`. Basically, when a node is near memory capacity, because of OOM score adjustments, workers are killed but Raylets can continue to run. However, after a few workers died, Raylets often lost connection to GCS and crashed as well. Example logs:
[raylet.log](https://github.com/ray-project/ray/files/8768089/raylet.1.log)

b17cbd825fe3fbde4fe9b03c9dd33be2454d4737 and 50d49a2d7aa59557eaacb7ea318ab38ff8e129a6 somewhat helped with the situation. The test is likely running longer because of these previous fixes. But the root cause is not addressed yet and the nightly test is still failing by getting stuck after a few Raylet failures.

cc @iycheng @stephanie-wang 

### Versions / Dependencies

Ray `master` branch

### Reproduction script

```
ANYSCALE_HOST=https://console.anyscale.com ANYSCALE_CLI_TOKEN=... ANYSCALE_CLOUD_ID=... ANYSCALE_PROJECT=... python release/ray_release/scripts/run_release_test.py --ray-wheels=master --no-terminate dataset_shuffle_push_based_random_shuffle_1tb
```
at f67871c1f7e79adc727b2a15311d9332832d2e8a

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment]
@iycheng do you know how to interpret these error messages? Does it mean that the GCS has crashed? Can we provide a better error message for these cases? I think it's pretty hard to understand the error as a user.

```
(raylet, ip=172.31.71.110) [2022-05-17 16:19:48,649 C 129 129] (raylet) gcs_rpc_client.h:505:  Check failed: absl::ToInt64Seconds(absl::Now() - gcs_last_alive_time_) < ::RayConfig::instance().gcs_rpc_server_reconnect_timeout_s() Failed to connect to GCS within 60 seconds
(raylet, ip=172.31.71.110) *** StackTrace Information ***
(raylet, ip=172.31.71.110)     ray::SpdLogMessage::Flush()
(raylet, ip=172.31.71.110)     ray::RayLog::~RayLog()
(raylet, ip=172.31.71.110)     ray::rpc::GcsRpcClient::CheckChannelStatus()
(raylet, ip=172.31.71.110)     boost::asio::detail::wait_handler<>::do_complete()
(raylet, ip=172.31.71.110)     boost::asio::detail::scheduler::do_run_one()
(raylet, ip=172.31.71.110)     boost::asio::detail::scheduler::run()
(raylet, ip=172.31.71.110)     boost::asio::io_context::run()
(raylet, ip=172.31.71.110)     main
(raylet, ip=172.31.71.110)     __libc_start_main
(raylet, ip=172.31.71.110) 
(raylet, ip=172.31.71.110)
```

**Comment by stephanie-wang** [comment]
@iycheng can you look into why this is happening? I'm able to reproduce it consistently with a more load-intensive version of the benchmark. It causes the head node raylet to crash and seems like this could be a regression.

`RAY_DATASET_PUSH_BASED_SHUFFLE=1 python dataset/sort.py --num-partitions=100000 --partition-size=1e7 --shuffle  # 1TB shuffle, 100k partitions`

[Example output](https://console.anyscale.com/o/anyscale-internal/projects/prj_ru3VRUcH2hwFyf4pGjMGzMDe/clusters/ses_YNDFvxrHVWZT5e23HM9Kkyjs?command-history-section=command_history)

**Comment by clarng** [comment]
Error in logs:

Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"

Seems this is no longer the case

**Comment by dss010101** [comment]
i seem to be getting this consistently running in a docker container.  where is this gcs_server.out file?

**Comment by aiakash** [comment]
@clarng im getting the same error
