### ISSUE TITLE
[RFC][Ray Core] Extend ray to support speculative execution for high-level frameworks

### ISSUE THREAD

**Issue by chaokunyang** [ray-project/ray#25182]
### Description
Speculative execution is used by framework widely to detect slow tasks, and execute task duplicate speculatively. When implementing such a pattern on ray, there are some ObjectRef resolving issues. Consider the following example, which is a dag built using ray tasks.
<img src="https://user-images.githubusercontent.com/12445254/170264355-8f2d11cc-5c1d-436b-ae09-7282b780175b.png" width=50% height=50%>
If we found task 1 is notably slower than 2~4 homogeneous tasks, we submitted a duplicate task1. And it run faster than original task, in order to update task1 output ObjectRef to all downstream tasks,  we need to iterate all downstream tasks recursively and resubmit  them too:
<img src="https://user-images.githubusercontent.com/12445254/170265397-f713dbb4-c31a-4834-ad46-0c2c5f4be208.png" width=50% height=50%>

This has two issues:
- Inconvenient to users. Users need  to iterate all downstream tasks recursively and resubmit  them too **for every duplicate task execution.** For now users also need to cancel those downstream tasks first too.
- Extra task arguments serialization overhead. All downstream tasks arguments need being serialized again.

# Solution 1 - Wait until all upstream tasks finish before scheduling the downstream tasks
This solution will affect pipeline scheduling. When upstream tasks are executing, ray can build task spec for all downstream tasks. But with this solution, all task specs are not built until all upstream tasks are finished.

It's also not intuitional for future-based async programing

# Solution 2 - Update ray task spec dynamically
If a duplicate task is finished, we can update all input ObjectRefs in task spec for all direct downstream tasks.

The API may be like `ray.update_inputs(downstream_task, [object_ref1, object_ref2, object_ref3, object_ref4, object_ref5])` or `ray.update_inputs(downstream_task, {1: object_ref1}`

# Solution 3 - Allow task run concurrently when call `remote`
This is not the scene for speculative execution. For speculative execution, we don't know which tasks will be slow tasks in advance, making all tasks run multiple replicas will waste lots of resource in vain.

# Solution 4 - Add `duplicate` API to ray task
When we find a slow task and want to duplicate it, we can just invoke `ObjectRef.duplicate` API to tell ray to submit the task again, the first finished output will be the final output for that  task.

For me, Solution4 is most reasonable, any suggestions?

### Use case

Mars graph scheduling

**Comment by zhe-thoughts** [comment]
Thanks @chaokunyang . Should this be a REP?

**Comment by chaokunyang** [comment]
> Thanks @chaokunyang . Should this be a REP?

Maybe we can discuss which solution should be used, than submit a REP for that solution? Or should we move this discuss to REP? @zhe-thoughts

**Comment by zhe-thoughts** [comment]
Hey @chaokunyang sorry I missed your question. I think we should create a REP for this cc @scv119 @jjyao

**Comment by dizhouwu** [comment]
Has this been updated yet?

**Comment by zheng-essential** [comment]
Do we have this yet
