### ISSUE TITLE
Ape-X hangs during actor creation after second ray.init() / ray.shutdown()

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#2518]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.4.0 (Also tried 0.5.0 which has the same issue)
- **Python version**: 3.5.2
- **Exact command to reproduce**: python3 -m unittest apex_test.py

### Describe the problem
I was trying to run multiple unit tests with the RLlib apex training for each test. The code is (apex_test.py):

```
import unittest

import ray
import ray.rllib.dqn as dqn


env_name = "CartPole-v0"


class TestApex(unittest.TestCase):

    _agent = None

    def setUp(self):
        config = dqn.apex.APEX_DEFAULT_CONFIG.copy()
        config["num_workers"] = 2
        ray.init()
        self._agent = dqn.ApexAgent(env=env_name, config=config)

    def test_first_time(self):
        for _ in range(2):
            self._agent.train()

    def test_second_time(self):
        for _ in range(2):
            self._agent.train()

    def tearDown(self):
        ray.worker.cleanup()
```
The problem is the Apex training is frozen when it starts the Apex training for the second time, and all CPU utilizations drop down to <20% then. It's also interesting that if we only have one test (for example without `test_second_time()` in this case), then everything's working fine without any issues. So I wonder if there're any issues for apex training on unit tests.

**PS.** Also tried the above code on Ray 0.5.0 (replace `import ray.rllib.dqn as dqn` with `import ray.rllib.agents.dqn as dqn`), and it has the same problem.

**Comment by RuofanKong** [comment]
@ericl thanks for comments! It makes sense, but isn't `ray.worker.cleanup()` supposed to delete actors?

Also, I think it's probably better to support `ray.init()` multiple times between tests to get the fresh cluster setup from the user perspective.

**Comment by ericl** [comment]
Yeah I think it should work. We should keep this bug open and try to come
up with a smaller reproduction case.

**Comment by ericl** [comment]
I think this issue is resolved in https://github.com/ray-project/ray/pull/2661
