### ISSUE TITLE
[AIR] Use "native" batch type in `BatchPredictor`

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#25195]
### Description

Currently `BatchPredictor` always uses the "pandas" batch format. This means even if your test dataset is entirely tensor based, it will be coerced into pandas format before being sent to the predictor.

This internal "coercion" is not made aware to the user.

Instead, after a numpy batch format is implemented in https://github.com/ray-project/ray/issues/24811, BatchPredictor should default to using "native" batch format instead of forcing into pandas.

Once we do this, we also need to add tests with BatchPredictor for both batch types.

### Use case

Batch prediction on Dataset of numpy data.

**Comment by clarkzinzow** [comment]
@amogkam FYI this should be doable now without completion of https://github.com/ray-project/ray/issues/24811, since #25531 has been merged into master. This should give you the NumPy batches with the `"native"` batch format as desired.
