### ISSUE TITLE
[AIR] Update kinks in examples

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#25197]
### Description

We have multiple AIR examples merged/in-flight. Since then there are new features that are merged/in-flight that can alleviate some of the kinks in these examples. We should go through all the examples and adjust them with these new features landed.

**Datasets**
- [x] Remove `TensorArray` from all examples
- [ ] Enable local shuffling for all training examples once https://github.com/ray-project/ray/pull/26094 is merged
- [x] See if Dataset UDFs can be replaced by new functionality that has been added to Datasets or BatchPredictor (such as `keep_columns` arg for `BatchPredictor.predict`)
- [x] Use `iter_torch_batches` and `to_tf` instead of `to_torch` and `iter_tf_batches`. PR for Tensorflow is already open here: https://github.com/ray-project/ray/pull/29462
- [x] Use numpy narrow waist in `BatchMapper` wherever applicable
- [x] Use numpy narrow waist in prediction wherever applicable. Blocked on #28917 

**Serve**
- [x] Re-enable batching for Serve `ModelWrapperDeployment` once https://github.com/ray-project/ray/pull/25003 is merged
- [x] Use built-in http adapters rather than a custom one once https://github.com/ray-project/ray/pull/25003 is merged

**General**
- [x] Use `ray[air]` install in all e2e examples instead of the individual `ray[data, serve]` etc.
- [ ] Use framework specific Checkpoints in all examples instead of generic AIR Checkpoint. Blocked on [#29458 ](https://github.com/ray-project/ray/issues/28910)

**Comment by amogkam** [comment]
As it stands various examples do things in different ways and sometimes differ from documentation (some examples use TensorArray, some examples implement a custom Serve pandas http adapter while others use the built-in one, examples use generic ray.air.Checkpoint while in docs we use framework specific checkpoints).

Having consistency across all of our examples and documentation is incredibly important to avoid confusing users and to only promote one standard way to do things.

**Comment by matthewdeng** [comment]
@amogkam going to assign this to just you for tracking purposes, but we can create separate issues and assign individual owners accordingly.

**Comment by h-vetinari** [comment]
This issue is milestoned for an already-released version -- should update the milestone or remove it.
