### ISSUE TITLE
[Dashboard][Doc] Views not clickable

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#25191]
### Description

Ray dashboard documentation, The Views tab is not clickable: https://docs.ray.io/en/latest/ray-core/ray-dashboard.html#logical-view
<img width="776" alt="Screen Shot 2022-05-25 at 14 30 32" src="https://user-images.githubusercontent.com/97252176/170370811-466d46ec-3260-4e30-9c6b-5408fde344ac.png">

### Link

https://docs.ray.io/en/latest/ray-core/ray-dashboard.html#logical-view

**Comment by tupui** [comment]
Indeed this part is a bit confusing but looking at the source it's actually just an image. So the intent, I suppose, is just to show how the tabs look like.

One could add a sentence listing all 4 tabs (and maybe replace the image with clickable selector to jump to sections).

**Comment by scottsun94** [comment]
We have changed the previous experimental dashboard to the default dashboard in 2.0. Dashboard documentation has been updated in master: https://docs.ray.io/en/master/ray-core/ray-dashboard.html.

This issue is not relevant then. Closing for now.
