### ISSUE TITLE
[AIR] Don't use the function name `build_model` in examples

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25204]
### Description

In many TensorFlow-related examples, we define a function called `build_model`.

```
def build_model():
    # toy neural network : 1-layer
    return tf.keras.Sequential(
        [tf.keras.layers.Dense(
            1, activation="linear", input_shape=(input_size,))]
    )
```

`build_model` is an inaccurate name. TensorFlow models have a `Model.build` method, but `Model.build` isn't actually called in any of the `build_model` functions. Rather, `build_model` returns an unbuilt model.

### Link

https://docs.ray.io/en/master/ray-air/package-ref.html

**Comment by matthewdeng** [comment]
Is this true? It doesn't seem like [tf.keras.Model](https://www.tensorflow.org/api_docs/python/tf/keras/Model) has a `build` method and the [TensorFlow Quickstart](https://www.tensorflow.org/tutorials/quickstart/beginner#build_a_machine_learning_model) seems to use the same terminology for instantiating a model this way.

**Comment by bveeramani** [comment]
Don't remember the context from when I opened the issue, but if the TensorFlow documentation uses this terminology it's probably fine.
