### ISSUE TITLE
[AIR] [CI] Tests aren't running for several modules

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#25209]
### What happened + What you expected to happen

The following test modules don't call `pytest` in a main method:
* test_huggingface_trainer
* test_huggingface_predictor
* test_dataset_utils
* test_lightgbm_predictor
* test_sklearn_predictor
* test_torch_predictor
* test_tensorflow_predictor

As a result, CI shows that these tests "pass" but the tests aren't actually getting run.

See also #25208 and #25207 

```
if __name__ == "__main__":
    import sys

    sys.exit(pytest.main(["-v", "-x", __file__]))
```

### Versions / Dependencies

Ray: fb2933a78f7587666911cfbba3a5d8ef637c0f9c

### Reproduction script

If you run `pytest python/ray/ml/tests/test_torch_predictor.py`, you should see `test_init` fail.

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
These are resolved
