### ISSUE TITLE
[Core] ray.cancel provides an option to respect max_retries of task

### ISSUE THREAD

**Issue by fyrestone** [ray-project/ray#25219]
### Description

Currently,  the task cancelled by `ray.cancel` will not be retried as documented https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-cancel

> Only non-actor tasks can be canceled. Canceled tasks will not be retried (max_retries will not be respected).

I think it will be very helpful if `ray.cancel` provides an option to decide whether cancelled task will be retried. The API can be:

```python
ray.cancel(
  object_ref: <Mock name='mock.ObjectRef' id='140586090734992'>,
  *,
  force: bool = False,
  recursive: bool = True,
  no_retries: bool = True  # Whether the cancelled task will not be retried, default is True
)
```

### Use case

Some slow or hang tasks can be detected and cancelled, it will be very useful that the cancelled task can be retried (better on another node):

``` python
@ray.remote(max_retries=3)
def compute(*input):
    # do some compute on inputs, and returns output.
    return output


# submit a DAG that
#     a    <--- hang
#    / \
#   b   c
#    \ /
#     d    <--- the result
a = compute.remote()
b = compute.remote(a)
c = compute.remote(a)
d = compute.remote(b, c)

# kill and retry the hang task a
ray.cancel(a, recursive=False, no_retries=False)

# we still can get the result d
print(ray.get(d))

**Comment by kfstorm** [comment]
@ijrsvt @stephanie-wang

**Comment by ijrsvt** [comment]
Two initial comments:
-  For that DAG to work, I'm fairly certain `recursive=False` would also need to be passed

**Comment by fyrestone** [comment]
> Two initial comments:
> 
> * For that DAG to work, I'm fairly certain `recursive=False` would also need to be passed
> * I think the name `no_retries` is confusing because it's unclear what is being retried (the cancellation or the task). I think something like `allow_task_retries` (default to `False`) makes a bit more sense.

Thanks. Yes, the `recursive=False` should be passed. The `no_retries` is similar to the `no_start` of `ray.kill(actor: ray.actor.ActorHandle, *, no_restart: bool = True)`, but it can be more clear by renaming to `no_task_retries`.

My point is to request an option for the `ray.cancel` to respect the `max_retries` of task.

**Comment by fyrestone** [comment]
@ijrsvt  @stephanie-wang Any plan for this feature request?

**Comment by raulchen** [comment]
BTW, for killing actors, we already have a similar option `ray.kill(actor, no_restart=True)`. So I think it makes sense to add such an option for `ray.cancel` as well. 
Regarding the name, I agree with @ijrsvt that `allow_task_retries` sounds clearer. But considering naming consistency, maybe we'll want to name it `no_retry`. I should be fine as long as the documentation is clear.
