### ISSUE TITLE
[Core] `memory` arg to `.remote` missing in docs

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#25215]
### Description

In the docs for [`ray.remote`](https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-remote) `memory` argument is not listed. But it is in the code and the doc section on memory management mentions it [in the examples](https://docs.ray.io/en/latest/ray-core/objects/memory-management.html). 

```python
# reserve 500MiB of available memory to place this task
@ray.remote(memory=500 * 1024 * 1024)
def some_function(x):
    pass
```

### Link

https://docs.ray.io/en/latest/ray-core/package-ref.html#ray-remote

**Comment by tupui** [comment]
Hi @jmakov, thank you for reporting. This is fixed in the latest version of the documentation: https://docs.ray.io/en/master/ray-core/package-ref.html#ray-remote
I will close this then.
