### ISSUE TITLE
[Docs] Add "Was this helpful?" button to our docs pages 

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#25228]
### Description

In many other great docs sites, like https://www.tensorflow.org/api_docs, there's a button at the end of the page to collect simple feedback.

This will help us more accurately improve our docs
<img width="132" alt="Screen Shot 2022-05-26 at 10 25 30 AM" src="https://user-images.githubusercontent.com/10713559/170542198-e65d545d-625f-4ee4-a13c-3de3ee26ae77.png">

### Use case

Improve our documentation.

**Comment by simon-mo** [comment]
Another good button would a "feedback" page link to github issues https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops#feedback

**Comment by DaeyangCho** [comment]
There is also a way to combine the two methods.
![Screenshot from 2022-05-27 15-00-14](https://user-images.githubusercontent.com/93561142/170639762-29d92b07-45b9-470e-a316-0e625e07245b.png)

**Comment by xiurobert** [comment]
Is there some kind of built in support for this feature in the documentation generator? Kind of seems like something that would require a backend.

**Comment by pcmoritz** [comment]
I created a PR for this in https://github.com/ray-project/ray/pull/26330 :)
