### ISSUE TITLE
[core] Node sometimes marked as dead due to lagging heartbeats in Datasets shuffle

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#25231]
### What happened + What you expected to happen

The datasets *random_shuffle_1tb nightly tests sometimes fail due to node crashes. These nodes all seem to be exiting because the time since the last heartbeat is too long.

```
Shuffle Map:  86%|████████▌ | 856/1000 [03:10<00:28,  5.12it/s]
2022-05-25 15:32:08,924	WARNING worker.py:1416 -- The node with node id: 46d26484351ee3b7169bce84082d6d6fb2a2167fe8df44c55fb49ddf and address: 172.31.73.171 and node name: 172.31.73.171 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
```

Seems like it is sometimes correlated with heap memory pressure from the task workers, but not always. Ideas to fix:
- Use a dedicated thread / IO service in the raylet to report heartbeats.
- Switch GCS to pull-based heartbeats instead of push.

### Versions / Dependencies

2.0dev

### Reproduction script

dataset_shuffle_random_shuffle_1tb and dataset_push_based_random_shuffle_1tb nightly tests.

[Example output](https://buildkite.com/ray-project/release-tests-branch/builds/586#0180fd43-9beb-4867-bbbb-d4146fc8c80d).

**Comment by matthewdeng** [comment]
@stephanie-wang is this still an issue?

**Comment by stephanie-wang** [comment]
I think the test was marked stable since then...I'll close the issue.
