### ISSUE TITLE
Issue on page /ray-core/package-ref.html

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#25252]
`placement_group` parameter is not documented for `ray.remote`.

Also, can we update the `ray.remote` signature to have an actual set of args/kwargs?

cc @rkooo567

**Comment by rkooo567** [comment]
Actually, this API will be deprecated and replaced by https://github.com/ray-project/ray/pull/24544 (PlacementGroupSchedulingStrategy).

But I realized this was actually never documented there. I think we can do
1. Update that docstring and say the arg is deprecated
2. Add proper deprecated warning

cc @jianoaix could be a potential work for 2.0 API cleanup

**Comment by rkooo567** [comment]
Should be handled in the master
