### ISSUE TITLE
[dashboard] need better support RAM when running ray in container 

### ISSUE THREAD

**Issue by scarlet25151** [ray-project/ray#25283]
### Description

When we using ray in container, the dashboard statistics is not so accurate.
for example: we can start a container using docker:
```bash
docker run -it -m 3g --cpus="2" -p 38265:8265 rayproject/ray:1.12.1 ray start --head --dashboard-host=0.0.0.0 --object-store-memory=2147741824 --block
```
we can check the memory limit in the container:
```
root@0a42345e3942:/home/ray# cat /sys/fs/cgroup/memory.max
3221225472
```
which is exactly `3 * 1024 * 1024 * 1024`, the same as 3G of what we've set.
However in dashboard
![image](https://user-images.githubusercontent.com/38214590/170838577-6c7686a3-a6c7-448a-8161-6953e6525482.png)
we can find that the memory limit is not the same as the container limit, but my real machines'.

so we would like to have an enhancement that the dashboard only reflect the quota of the container so that it would not confused the user.

btw, another thing is that it may be hard for us to tell the proportion of the plasma store and the heap memory in the usage. because plasma store is using a part of ram, it's hard for us to understand from the memory that what usage the ray processes take and what the plasma store take.
![image](https://user-images.githubusercontent.com/38214590/170839105-7b188d8b-3378-4906-aa11-bfa8f3721822.png)

### Use case

1. when user run ray inside a container that has quota and open the dashboard, the memory limit is align with the quota
2. we can see directly from the dashboard that how much memory the ray processes(actor/task) take.

**Comment by DmitriGekhtman** [comment]
Weird, RAM limit is supposed to be read from the cgroups.
I'll take a look into reproducing this bug on MacOS.

**Comment by DmitriGekhtman** [comment]
Hey @scarlet25151 sorry for the delay.
What procedure did you use to access the dashboard of the running container?

**Comment by DmitriGekhtman** [comment]
Oh, sorry I see the -p argument.

**Comment by DmitriGekhtman** [comment]
Yeah, I can reproduce this exactly as you describe it. Now, to debug.

**Comment by DmitriGekhtman** [comment]
Found the bug.

**Comment by DmitriGekhtman** [comment]
Fix: https://github.com/ray-project/ray/pull/25710

**Comment by scarlet25151** [comment]
Great Job! Much appreciate. Btw, will this pr be patch to the existing release version?

**Comment by DmitriGekhtman** [comment]
We're working on a Ray 1.13.1 patch release -- I will check to see if we can include the PR in the patch release.
