### ISSUE TITLE
[AIR] Support fitted preprocessors

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#25299]
### Problem

Currently, `ray.ml.Trainer` mentions that it will only fit the Preprocessor if it is not already fitted.

https://github.com/ray-project/ray/blob/94557e30951c64e64571256e5ccf4f529657084b/python/ray/ml/trainer.py#L257-L260

However, the implementation actually will cause the Preprocessor to be re-fitted on the train dataset.

https://github.com/ray-project/ray/blob/94557e30951c64e64571256e5ccf4f529657084b/python/ray/ml/trainer.py#L270-L273

https://github.com/ray-project/ray/blob/94557e30951c64e64571256e5ccf4f529657084b/python/ray/ml/preprocessor.py#L66-L67

### Background

This behavior was changed in https://github.com/ray-project/ray/pull/23700 to allow Preprocessors to be re-fit.

### Proposal

1. Add functionality to allow the user to pass in a fitted Preprocessor without re-fitting.
    1. This can be useful if you want to pass a preprocessed Dataset into Tune, and also have this fitted Preprocessor saved to the Checkpoint.
    2. Naive solution is to add a config arg that the user can use to toggle the behavior.
2. Update Trainer documentation to match actual behavior.

**Comment by justinvyu** [comment]
Preprocessors are deprecated. Can do something similar to this with the `metadata` argument of a trainer.
