### ISSUE TITLE
[Dashboard][Autoscaler] Don't render autoscaler config page.

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#25303]
### What happened + What you expected to happen

The dashboard tries to read an autoscaling config from a particular spot on disk.
However, for some deployment stacks, there isn't a local autoscaling config that sits on disk or the config isn't in the expected place.
In this case, dashboard fails to render the autoscaler config and shows an error page.

Task: Don't try to render the autoscaler config if the file is not in the expected place.

### Versions / Dependencies

Issue surfaces when deploying Ray by any means other than Ray cluster launcher with VMs.

### Reproduction script

Deploy Ray using a non-VM-based stack. Look at the autoscaler config page.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
@DmitriGekhtman We removed the config page in the new default dashboard.
Do you think there is a need to add it back?

**Comment by DmitriGekhtman** [comment]
I don't think so?
I think this issue is probably fine to close.

**Comment by scottsun94** [comment]
Okay. Closing it for now. Will create a new issue if we hear any feedback about it.
