### ISSUE TITLE
[Core] How do I write bazel to create a static link library for ray_api?

### ISSUE THREAD

**Issue by infzo** [ray-project/ray#25301]
### What happened + What you expected to happen

Ray provides `libray_api.so` as a dynamic link library for development, but when integrating with some other special components, the static link library .a file may be more convenient. 

I expected to generate a static link library by modifying the bazel file, but it failed. The generated static link library may be incomplete and has undefined errors when used.

### Versions / Dependencies

```
os      ubuntu20.04
python  3.8
ray     1.12.0
```

### Reproduction script

```python
bazel build --config=llvm //cpp:ray_api_static

# ../ray/cpp/BUILD.bazel
cc_library(
    name = "ray_api_static",
    srcs = glob([
        "src/ray/api.cc",
        "src/ray/api/*.cc",
        "src/ray/api/*.h",
        "src/ray/app/*.cc",
        "src/ray/app/*.h",
        "src/ray/runtime/*.cc",
        "src/ray/runtime/*.h",
        "src/ray/runtime/**/*.cc",
        "src/ray/runtime/**/*.h",
        "src/ray/runtime/task/*.cc",
        "src/ray/runtime/task/*.h",
        "src/ray/util/*.cc",
        "src/ray/util/*.h",
        "src/ray/*.cc",
        "src/ray/*.h",
    ]),
    hdrs = glob([
        "include/ray/*.h",
        "include/ray/**/*.h",
        "include/ray/**/**/*.h",
    ]),
    copts = COPTS,
    linkopts = ["-ldl"],
    linkstatic = True,
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//:core_worker_lib",
        "//:global_state_accessor_lib",
        "//:ray_common",
        "//:ray_util",
        "@boost//:callable_traits",
        "@boost//:dll",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@msgpack",
    ],
    # alwayslink = True,
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by SongGuyang** [comment]
@infzo Sorry for the late action. In our recent practice, we found that static library will bring some problems. For example, if the default_worker links libray_api statically and user lib links it statically or dynamically , there will be two different ray runtime instances in one worker process. It will bring some issues. So recently, we change to use dynamic library in default_worker https://github.com/ray-project/ray/pull/25720. And I think we shouldn't allow libray_api is linked statically.
