### ISSUE TITLE
[Autoscaler] expose upscaling_speed  and idle_timeout_minutes to values.yaml when using Helm

### ISSUE THREAD

**Issue by orcahmlee** [ray-project/ray#25312]
### Description

The [upscaling_speed](https://docs.ray.io/en/latest/cluster/config.html#upscaling-speed)  and [idle_timeout_minutes](https://docs.ray.io/en/latest/cluster/config.html#cluster-configuration-idle-timeout-minutes) properties are useful and it already in [RayCluster](https://github.com/ray-project/ray/blob/master/deploy/charts/ray/templates/raycluster.yaml#L13-L15). However, it not expose to [values.yaml](https://github.com/ray-project/ray/blob/master/deploy/charts/ray/values.yaml).

I think exposing these two properties to `values.yaml` would be useful for the end-users. If this enhancement is meaningful, I could contribute to it.

**Comment by DmitriGekhtman** [comment]
If you'd like to open a PR for this, I'd be glad to review!

**Comment by orcahmlee** [comment]
> If you'd like to open a PR for this, I'd be glad to review!

Hi @DmitriGekhtman ,
I've already opened a PR(https://github.com/ray-project/ray/pull/25495), please feel free to give me any advice.
