### ISSUE TITLE
[Autoscaler]  `ray down cluster.yaml` throws an exception

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#25321]
### What happened + What you expected to happen

Running `ray down -v -y examples/ray_cluster.yaml` throws an exception. Seems like for some reason `conda activate puma-lab` isn't called before `ray stop`. That worked in previous versions of `ray` - head and worker nodes had to be started by `conda activate puma-lab && ray start ...`, but nothing special needed to be provided for `ray down examples/ray_cluster.yaml`. Do we need to provide in `ray_cluster.yaml` an additional command under (undocumented) `worker_stop_ray_commands` & `head_stop_ray_commands` something like `- conda activate puma-lab && ray stop`?

Also `ray down` doesn't have a `--no-config-cache` flag as indicated in the exception output.
```bash
$ ray down -v -y examples/ray_cluster.yaml

Loaded cached provider configuration from /tmp/ray-config-0a5c23956a6655769c22af512053e6476c96a647
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Destroying cluster. Confirm [y/N]: y [automatic, due to --yes]
2022-05-31 21:47:25,841 INFO node_provider.py:49 -- ClusterState: Loaded cluster state: ['192.168.0.106', '192.168.0.107', '192.168.0.108', '192.168.0.101', '192.168.0.110']
Fetched IP: 192.168.0.101
Running `ray stop`
Command 'ray' not found, did you mean:
  command 'say' from deb gnustep-gui-runtime (0.29.0-2build1)
  command 'ra' from deb argus-client (1:3.0.8.2-6.1ubuntu1)
  command 'rar' from deb rar (2:5.5.0-1.1)
  command 'ra6' from deb ipv6toolkit (2.0+ds.1-1)
Try: sudo apt install <deb name>
Shared connection to 192.168.0.101 closed.
Command failed:

  ssh -tt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_2a8fab0747/c21f969b5f/%C -o ControlPersist=10s -o ConnectTimeout=120s toaster@192.168.0.101 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'

Exception occurred when stopping the cluster Ray runtime (use -v to dump teardown exceptions).
Ignoring the exception and attempting to shut down the cluster nodes anyway.
2022-05-31 21:47:27,261 INFO node_provider.py:158 -- NodeProvider: 192.168.0.101: Terminating node
2022-05-31 21:47:27,261 INFO node_provider.py:110 -- ClusterState: Writing cluster state: ['192.168.0.106', '192.168.0.107', '192.168.0.108', '192.168.0.101', '192.168.0.110']
Requested 1 nodes to shut down. [interval=1s]
0 nodes remaining after 5 second(s).
No nodes remaining.
```

### Versions / Dependencies

`env.yaml`:
```yaml
name: puma-lab
channels:
  - intel
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiohttp-cors=0.7.0=py_0
  - aioredis=1.3.1=py_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - blessings=1.7=py38h578d9bd_1006
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=hb9a14ef_9
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.5.18.1=ha878542_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - certifi=2022.5.18.1=py38h578d9bd_0
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py38h578d9bd_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorful=0.5.4=pyhd8ed1ab_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - distlib=0.3.4=pyhd8ed1ab_0
  - filelock=3.7.0=pyhd8ed1ab_0
  - frozenlist=1.3.0=py38h0a891b7_1
  - google-api-core=2.8.1=pyhd8ed1ab_0
  - google-auth=2.6.6=pyh6c4a22f_0
  - googleapis-common-protos=1.56.2=py38h578d9bd_0
  - gpustat=0.6.0=pyhd8ed1ab_1
  - grpcio=1.43.0=py38h2457d08_0
  - hiredis=2.0.0=py38h0a891b7_2
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - intelpython=2022.1.0=0
  - jsonschema=4.5.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=14_linux64_openblas
  - libcblas=3.9.0=14_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - liblapack=3.9.0=14_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libprotobuf=3.20.1=h6239696_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libunwind=1.6.2=h9c3ff4c_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.12=h166bdaf_0
  - msgpack-python=1.0.3=py38h43d8883_1
  - multidict=6.0.2=py38h0a891b7_1
  - ncurses=6.3=h7f8727e_2
  - numpy=1.22.4=py38h99721a1_0
  - nvidia-ml=7.352.0=py_0
  - opencensus=0.9.0=pyhd8ed1ab_0
  - opencensus-context=0.1.2=py38h578d9bd_5
  - openssl=3.0.3=h166bdaf_0
  - pip=21.2.4=py38h06a4308_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - protobuf=3.20.1=py38hfa26641_0
  - psutil=5.9.1=py38h0a891b7_0
  - py-spy=0.3.11=h060cca7_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=ha86cf86_0_cpython
  - python_abi=3.8=2_cp38
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - ray-core=1.12.1=py38hb9c8dfe_0
  - ray-default=1.12.1=py38h578d9bd_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - setproctitle=1.2.2=py38h0a891b7_2
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=6.0.0=pyhd8ed1ab_0
  - sqlite=3.38.0=hc218d9a_0
  - tk=8.6.12=h27826a3_0
  - typing-extensions=4.2.0=hd8ed1ab_1
  - typing_extensions=4.2.0=pyha770c72_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - virtualenv=20.14.1=py38h578d9bd_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h74280d8_2
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_0
```

### Reproduction script

```bash
conda create -n puma-lab python=3.8 -y
conda activate puma-lab
mamba install -c conda-forge ray-default
conda env export > env.yaml
ray up --no-config-cache examples/ray_cluster.yaml  -y
```
`ray_cluster.yaml`:
```yaml
cluster_name: default
provider:
  type: local
  head_ip: 192.168.0.101
  worker_ips:
    - 192.168.0.110
    - 192.168.0.106
    - 192.168.0.107
    - 192.168.0.108
auth:
  ssh_user: toaster
upscaling_speed: 1.0
idle_timeout_minutes: 5

# needed so we can run `setup commands`
file_mounts: {
      "/mnt/workspace/ray/mount_driver_node": "~/workspace/repos/puma-lab",
}
cluster_synced_files: []
file_mounts_sync_continuously: False
rsync_exclude:
  - "**/.git"
  - "**/.git/**"
rsync_filter:
  - ".gitignore"
initialization_commands: []
setup_commands:
  - mamba env create -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml || mamba env update -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
  # fix for installing MKL (numpy import fails without this) (https://community.intel.com/t5/Intel-oneAPI-AI-Analytics/oneAPI-AI-Anlytics-Toolkit-Install-via-Conda-Package-Manager-on/m-p/1381479)
  #- cp ~/mambaforge-pypy3/envs/puma-lab/lib/libmkl_rt.so.2 ~/mambaforge-pypy3/envs/puma-lab/lib/libmkl_rt.so.1
  - conda activate puma-lab && ray stop
  - conda activate puma-lab && ulimit -c unlimited && export RAY_DISABLE_MEMORY_MONITOR=1; MKL_NUM_THREADS=$(nproc); OPENBLAS_NUM_THREADS=$(nproc); OMP_NUM_THREADS=$(nproc) && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":8,"min_spilling_size":104857600,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/mnt/workspace/ray/object_spilling\"}}"}'
worker_start_ray_commands:
  # fix for installing MKL (numpy import fails without this) (https://community.intel.com/t5/Intel-oneAPI-AI-Analytics/oneAPI-AI-Anlytics-Toolkit-Install-via-Conda-Package-Manager-on/m-p/1381479)
  #- cp ~/mambaforge-pypy3/envs/puma-lab/lib/libmkl_rt.so.2 ~/mambaforge-pypy3/envs/puma-lab/lib/libmkl_rt.so.1
  - conda activate puma-lab && ray stop
  - conda activate puma-lab && ulimit -c unlimited && export RAY_DISABLE_MEMORY_MONITOR=1; MKL_NUM_THREADS=$(nproc); OPENBLAS_NUM_THREADS=$(nproc); OMP_NUM_THREADS=$(nproc) && ray start --address=$RAY_HEAD_IP:6379
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by wuisawesome** [comment]
The issue is that we expect `ray` to be on the `PATH` on the machine. Can you do `echo "conda activate puma-lab" >> .bashrc`?

**Comment by jmakov** [comment]
@wuisawesome it worked in previous versions. I'm not sure I want this in `.bashrc`. What if somebody uses a different `ray_cluster.yaml` and a different environment (`env.yaml`)?

**Comment by wuisawesome** [comment]
can you add that to your `setup_commands` not your AMI? you can't use multiple cluster yamls with the same cluster.

**Comment by jmakov** [comment]
You mean sth like `- mamba env create -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml || mamba env update -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml && conda activate puma-lab`? I have a running calculation that takes a few days, so I can't try it right now.

**Comment by wuisawesome** [comment]
I don't have much experience with mamba, but at the end of the day, you need to be able to run `ray ...` cli commands without prefacing them with ` conda activate ...` because the autoscaler's implicit commands won't do that. 

The easiest way is to just make your first `setup_command` `echo "conda activate puma-lab >> .bashrc`.

**Comment by jmakov** [comment]
> The easiest way is to just make your first `setup_command` `echo "conda activate puma-lab >> .bashrc`.

Will that not add the `activate` command to `.bashrc` every time the cluster is started so you'll end with a thousands of commands that will slow down starting the cluster eventually? Also I'm not sure I find any references in the [docs](https://docs.ray.io/en/latest/cluster/guide.html) which leads me to believe this is just an ad hoc solution to a bigger (design) problem/bug.

I'll try to test previous `ray` versions (pre 1.12.1) to see if this was introduced in 1.12.1 (also, where can I find any release notes on breaking changes?). But the running calculation on my cluster will take at least half of the Week so would be great if anybody could help to speed up fixing this.

**Comment by wuisawesome** [comment]
> I think your disposition is a cloud environment where instances are created and destroyed for every cluster up and down. In that environment I think your solution is great (although not sure if documented). 

Thanks for the clarification, I'll add an update to the docs. In general our cloud support is admittedly better than our on-prem support. 

> Also I'm not sure I find any references in the [docs](https://docs.ray.io/en/latest/cluster/guide.html) which leads me to believe this is just an ad hoc solution to a bigger (design) problem/bug.

Yeah, you're right. The direction we're moving towards is tighter integration of KubeRay/leveraging the kubernetes ecosystem's solution to these problems.

That being said, the most immediate solution to your problem is to use [docker](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml#L8). If you truly have hundreds of clusters, you may also need to manage logs, manage your docker image cache, etc at which point you may way to consider just jumping directly to a k8s solution.

**Comment by jmakov** [comment]
Just a ping that this is still the case in `ray` 1.13.0.

**Comment by BurakDmb** [comment]
Hi,

I'm trying to use ray clusters with conda installed.

By using this example (https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml) for local clusters, I managed to start a local cluster without docker (by using the `worker_start_ray_commands` and other configs to activate conda in cluster creation steps).

Unfortunately, my problem arises when I try to use a command like `ray submit example-full.yaml parallel_compute.py -v --start`. Ray python package is not found since this file is executed on the base conda environment, not the desired environment in which the ray is installed.

This is expected since you mentioned that autoscaler does not execute preface commands (such as conda activate). 
> I don't have much experience with mamba, but at the end of the day, you need to be able to run `ray ...` cli commands without prefacing them with ` conda activate ...` because the autoscaler's implicit commands won't do that.
> 
> The easiest way is to just make your first `setup_command` `echo "conda activate puma-lab >> .bashrc`.

Is there any chance to implement and add a new config element for autoscaler, which implicitly preface some commands? These commands need to be executed when the autoscaler is going to execute a command.

This feature allows different clusters (each of them uses different conda python environments for different dependencies) could be simultaneously used for different scenarios without changing any external files (.bashrc, etc.). Hard coding the conda environment or other commands in a .bashrc file is hard to manage/maintain in some cases.

If it's viable, such a configuration would be great for such purpose (variable names could be changed): 
```
head_setup_commands:
...
worker_setup_commands: 
...
head_start_ray_commands:
...
worker_start_ray_commands:
...
worker_preface_commands:
    # For Conda environments
    - conda activate ...
    # or for virtual environments
    - source myvenv/bin/activate
    # or for ROS source files
    - source /opt/ros/<distro>/setup.bash

```
