### ISSUE TITLE
[CORE] compiler warnings when building ray on windows

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#25320]
### What happened + What you expected to happen

Build has many compiler warnings on window. They are harmless but easy to avoid. Links are from a random CI run.
[`ray/common/task/task_spec.h(91): warning C4805: '^=': unsafe mix of type 'size_t' and type 'bool' in operation`](https://buildkite.com/ray-project/ray-builders-branch/builds/7851#01811aac-0fa2-41d5-a836-b81aa8487044/2290-2697) - appears over 100 times
[`ray/common/task/task_spec.h(99): warning C4805: '^=': unsafe mix of type 'size_t' and type 'bool' in operation`](https://buildkite.com/ray-project/ray-builders-branch/builds/7851#01811aac-0fa2-41d5-a836-b81aa8487044/2290-2700) - appears over 100 times
[`warning D9025 : overriding '/W3' with '/w`](https://buildkite.com/ray-project/ray-builders-branch/builds/7851#01811aac-0fa2-41d5-a836-b81aa8487044/2290-2639) appears 150 times

### Versions / Dependencies

building ray HEAD on windows with `pip install python`

### Reproduction script

`pip install python`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by DmitriGekhtman** [comment]
Hi @mattip I see some of your PRs are not getting attention from the Ray team. That shouldn't be the case, but if that happens, feel free to yell at us on the Ray Slack.

**Comment by mattip** [comment]
Closed by merging 25594
