### ISSUE TITLE
PPO num_gpus config does not work outside of Ray tune

### ISSUE THREAD

**Issue by efang96** [ray-project/ray#2532]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Ray installed from (source or binary)**:
Installed using pip install ray
- **Ray version**:
0.5.0
- **Python version**:
3.5.5
- **Exact command to reproduce**:
`
trainer = ppo.PPOAgent(env="my_env", config={
        "num_gpus":2,
        "tf_session_args": {
            "device_count": {
                "GPU": 2
            }
        }
`

### Describe the problem

It depends on `ray.get_gpu_ids()` but this value returns [], which is misleading when GPUs are actually available.

**Comment by ericl** [comment]
Did you set `num_gpus` in the PPO config? We won't try to request GPUs from ray unless that is set.

**Comment by ericl** [comment]
What happens when you run the multi GPU tuned example?

**Comment by ericl** [comment]
You shouldn't need to set any of those variables except num GPUs.

**Comment by efang96** [comment]
I think it does end up using the GPU (according to nvidia-smi at least), but ray logs that I'm only using CPU.

**Comment by richardliaw** [comment]
Can you provide some output for reference? (and also fill out the issue)

**Comment by ericl** [comment]
Hi, can you try running this:
```
./train.py --run=PPO --env=CartPole-v0 --config='{"num_gpus": 2}'
```

When I run that, I get:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/32 CPUs, 2/2 GPUs
Result logdir: /home/ubuntu/ray_results/default
RUNNING trials:
 - PPO_CartPole-v0_0:	RUNNING [pid=19209], 21 s, 4047 ts, 22.8 rew
```

Which indicates two GPUs are being used.

**Comment by efang96** [comment]
Seems like this is working, I pasted the output below:
```
== Status ==
Using FIFO scheduling algorithm.
Result logdir: /home/eecs/edward.fang/ray_results/default
PENDING trials:
 - PPO_CartPole-v0_0:	PENDING

Created LogSyncer for /home/eecs/edward.fang/ray_results/default/PPO_CartPole-v0_0_2018-08-01_13-13-29pux3ceu6 ->
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/88 CPUs, 2/8 GPUs
Result logdir: /home/eecs/edward.fang/ray_results/default
RUNNING trials:
 - PPO_CartPole-v0_0:	RUNNING

/data/efang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2018-08-01 13:13:39.309463: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
LocalMultiGPUOptimizer devices ['/gpu:0', '/gpu:1']
```

**Comment by ericl** [comment]
Oh, I see the problem, you're not running in Ray tune, so Ray doesn't assign the gpu ids properly without more manual work.

This PR https://github.com/ray-project/ray/pull/2535 should fix the issue. After that, you just need to set "num_gpus".

**Comment by efang96** [comment]
Great, thanks @ericl and @richardliaw !
