### ISSUE TITLE
[Serve] Unpin (or at least weaken) the uvicorn version dependency?

### ISSUE THREAD

**Issue by willfrey** [ray-project/ray#25340]
### Description

Is there any reason that uvicorn is pinned to version 0.16? The most recent version on PyPI is 0.17.6 now. It would be nice to have versioning be more flexible, so either requiring 0.16 or later (but perhaps limiting it to not including a full-blown 1.0 release or 0.18 if you want to be more conservative).

I can try to see if the tests pass with uvicorn 0.17.6 but I'm currently trying to figure out how to build the project locally so that I can run tests :)

Thought I'd just ask here about the version pinning in case you all have an answer already.

Thanks!

### Use case

I'd like to use ray[serve] with more recent versions of uvicorn.

**Comment by simon-mo** [comment]
for uvicorn pinning, I believe it's due some issue with 0.16.0 that has incompatibility with h11 dependencies, see https://github.com/ray-project/ray/pull/21612

I think it make sense to drop the pin, at least try it out. Here's a similar PR changing uvicorn dependencies:
https://github.com/ray-project/ray/pull/25027

**Comment by simon-mo** [comment]
and please let us know if this documentation helps for local dev: https://docs.ray.io/en/latest/ray-contribute/development.html
