### ISSUE TITLE
Automatically detect broken links in documentation 

### ISSUE THREAD

**Issue by sasha-s** [ray-project/ray#25356]
### Description

Followup to #25355

We should be detecting broken links on CI.

Could be (in theory) done by making linkcheck useful, or by verifying the generated HTMLs.

**Comment by simon-mo** [comment]
It's already part of our link check job, see:
https://buildkite.com/ray-project/ray-builders-branch/builds/7869#01811f5f-7e2d-41bc-bf93-9591972641f9/1525-3158

**Comment by sasha-s** [comment]
why do we have broken links then?

**Comment by simon-mo** [comment]
The link you started from is /latest, which was from previous version 1.12.1 which link check was not enabled. the /master starting point should be fine.
