### ISSUE TITLE
[Tune] Please bring SMAC3 to Ray Tune

### ISSUE THREAD

**Issue by circlecrystal** [ray-project/ray#25364]
### Description

In the official repo of BOHB (https://github.com/automl/HpBandSter), we saw that the author claimed:
"We don't maintain this repository anymore" & "Two successor packages which showed in our [HPOBench paper](https://arxiv.org/abs/2109.06716) superior performance".

One of these two packages, which is under highly active development, is smac3 (https://github.com/automl/SMAC3).

Therefore, it's safe to say smac3 is currently the SOTA HPO package. Please bring SMAC3 to Ray Tune, thanks!

### Use case

Aim for the HPO peak

**Comment by richardliaw** [comment]
that's awesome! thanks for raising this.

by any chance, would you be interested in making a contribution? Ray team would be happy to work with you collaboratively and shepherd your PR!

(it would also be really helpful for us as we're trying to improve the contribution journey)
