### ISSUE TITLE
[rllib] Improve model config documentation

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#2538]
I've been trying to use the model config as much as possible to avoid writing custom models, but often the documentation is difficult to understand.

For example, to understand the `conv_filters` option, the [documentation](https://ray.readthedocs.io/en/latest/rllib-models.html) says that the model config is documented in the [model catalog](https://github.com/ray-project/ray/blob/master/python/ray/rllib/models/catalog.py). In the source code, the model catalog documentation for `conv_filters` says `"conv_filters", # Filter configuration`. I had to grep the source code before finding out that `conv_filters` is a list of `[out_channels, kernel, stride]` from [visionnet.py](https://github.com/ray-project/ray/blob/master/python/ray/rllib/models/visionnet.py).

**Comment by ericl** [comment]
Would you mind submitting any quick fixes as a PR?

Note that in general for customizations it's better to just write a custom model instead, it amounts to copying the model source code and registering it. The amount of stuff we can support in a config is limited.

**Comment by drozzy** [comment]
Related question on SO: 
"ValueError: No default configuration for obs shape [6, 94], you must specify `conv_filters` manually as a model option. Default configurations are only available for inputs of shape [42, 42, K] and [84, 84, K]. You may alternatively want to use a custom model or preprocessor."
"For the (6,94) case, is the "dim" supposed to be 6 or 94? Is the conv_filters fine leaving as is, or is a certain network architecture necessary for each shape? If so, where is the link?"

https://stackoverflow.com/questions/57151612/what-is-the-appropriate-conv-filter-specifications-for-custom-observation-space

**Comment by dano000** [comment]
I'm having the same issue here:
```
ValueError: No default configuration for obs shape [1, 5], you must specify `conv_filters` manually as a model option. Default configurations are only available for inputs of shape [42, 42, K] and [84, 84, K]. You may alternatively want to use a custom model or preprocessor.
```

**Comment by ericl** [comment]
You can force using a fcnet as the custom model, or flatten your
observation. It's trying to create a convnet over the inputs and getting
confused about the shape.
