### ISSUE TITLE
[Serve] Refine Serve deployment status definitions

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#25381]
### Description

Currently, Serve deployments enter the `UPDATING` status [whenever they are deployed](https://github.com/ray-project/ray/blob/f76849f7887f3b8f7df6cc85670eda14ef2c0529/python/ray/serve/deployment_state.py#L1082), even if the the update doesn't actually change any deployments settings.

The feature request is to only change the deployment status to `UPDATING` when a deployment setting has changed.

### Use case

This allows Serve YAML config files to be applied blindly and repeatedly to a Ray cluster. YAML config users can then detect that the deployments are `UPDATING` when they're actually updating instead of whenever an update request has been issued.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @shrekris-anyscale is this under development / finished / or still needs work?

cc: @sihanwang41

**Comment by shrekris-anyscale** [comment]
Thanks for following up here @hora-anyscale. This should be resolved by #27000.
