### ISSUE TITLE
Include pyarrow_files/tensorflow in wheels

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2539]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: latest wheels
- **Ray version**: Current Master
- **Python version**: 2.7
- **Exact command to reproduce**:
```
import pyarrow.plasma as plasma
plasma.build_tensorflow_op()
```

### Describe the problem
The `pyarrow_files/tensorflow` directory is dropped by `setup.py`

cc @pcmoritz

**Comment by pcmoritz** [comment]
fixed in https://github.com/ray-project/ray/pull/2547
