### ISSUE TITLE
[operator]  When use ray cluster in k8s,  it is very difficult to view related log.

### ISSUE THREAD

**Issue by ggservice007** [ray-project/ray#25395]
### Description

When run the following command 
```sh
kubectl logs -f ray-ray-head-gcknv
```
get nothing, so it is difficult to maintain the ray cluster on k8s.

**Comment by scottsun94** [comment]
@ggservice007 Have you ever used the new dashboard in ray 2.0 to view logs?

cc: @DmitriGekhtman 
what's the recommended way to download/fetch logs when using KubeRay?

**Comment by scottsun94** [comment]
@ggservice007 Ping ^

**Comment by DmitriGekhtman** [comment]
Check the Ray docs for up to date tips on log aggregation tips for ray on k8s.
