### ISSUE TITLE
[DatasetPipeline] stage fusion prevents pipeline concurrency when blocks_per_window=1

### ISSUE THREAD

**Issue by cboulay** [ray-project/ray#25403]
### What happened + What you expected to happen

I cannot reproduce parallelization across stages as indicated in the pipeline documentation.

I have a workflow that requires each stage of processing comprise a single worker through which all blocks of data pass, perfectly sequentially. I am trying to simulate online processing of time series data. I cannot parallelize within a stage because the same process needs to see each block.

However, stage 1 can operate on block N while stage 2 is operating on block (N-1) and stage 3 is operating on block N-2. i.e., I would like to parallelize among stages.

Desired:

| TimeStep | Stage 1 | Stage 2 | Stage 3 |
| ---------  | ------- | -------- | -------- |
| 0               | Blk0      |               |                |
| 1               | Blk1       | Blk0       |                |
| 2               | Blk2      | Blk1       | Blk0        |

Observed:

| TimeStep | Stage 1 | Stage 2 | Stage 3 |
| ---------  | ------- | -------- | -------- |
| 0               | Blk0      |               |                |
| 1               |               | Blk0       |                |
| 3               |              |                | Blk0       |
| 2               | Blk1      |                |                |
| 2               |              | Blk1        |                |
| 2               |              |                | Blk1        |
| 2               | Blk2     |                |                |

I expect I'm just misunderstanding the API. Is what I want to achieve possible in Ray? The documentation implies that it is.

In the below script I do 2 stages only and I print out (stage#, blockID, time.time()).

I expect and get (stage1, block_0, T_01), (stage2, block_0, T_02) where T_02 is approximately 50 msec after T_01. In other words, stage 2 completes a block 50 msec after stage 1 completed the same block. This is fine.

I also expect (stage1, block_1, T_11) to have T_11 approximately 5 msec after T_02 or 55 msec after T_01, implying that stage1 is operating on block_1 while stage2 is operating on block_0. Instead I see that T_11 is ~110 msec after T_01, or about 55 msec after T_02.

```
(MyActor1 pid=56531) Stage1 0 1.411812 
(MyActor2 pid=56532) Stage2 0 1.476901 
(MyActor1 pid=56531) Stage1 1 1.542742 
(MyActor2 pid=56532) Stage2 1 1.5935948 
(MyActor1 pid=56531) Stage1 2 1.658131 
(MyActor2 pid=56532) Stage2 2 1.708926 
(MyActor1 pid=56531) Stage1 3 1.77351 
(MyActor1 pid=56531) Stage1 4 1.88875 
(MyActor2 pid=56532) Stage2 3 1.824411 
(MyActor1 pid=56531) Stage1 5 2.009174 
(MyActor2 pid=56532) Stage2 4 1.93956 
(MyActor1 pid=56531) Stage1 6 2.124833 
(MyActor2 pid=56532) Stage2 5 2.060121 
(MyActor1 pid=56531) Stage1 7 2.240583 
(MyActor2 pid=56532) Stage2 6 2.175609 
(MyActor2 pid=56532) Stage2 7 2.291593 
(MyActor1 pid=56531) Stage1 8 2.356102 
(MyActor2 pid=56532) Stage2 8 2.406862 
(MyActor1 pid=56531) Stage1 9 2.471957 
(MyActor2 pid=56532) Stage2 9 2.522917 
(MyActor1 pid=56531) Stage1 10 2.587265 
(MyActor2 pid=56532) Stage2 10 2.638421 
```

### Versions / Dependencies

ray: 1.12.0
Python 3.8.13
Apple Silicon (M1Pro)

### Reproduction script

```Python
import ray
import time
import numpy as np


def busy_wait(dt):
    current_time = time.time()
    while time.time() < current_time+dt:
        pass


class CallableClass1:
    def __init__(self):
        self._state = None

    def __call__(self, data):
        if self._state is None:
            # Do some first run setup, typically requiring info from data.
            self._state = 0 if isinstance(data[0], int) else 0.0
        # Use our state
        if not data[0] == self._state:
            print(f"Stage1: {data[0]} ≠ {self._state}")
        # Process the data
        assert np.all(np.diff(data) == 1)
        busy_wait(0.0012 * len(data))
        result = [_ * 2 for _ in data]
        # Update our state
        print("\nStage1", data[0]//50, time.time(), "\n")
        self._state += len(data)
        return result


class CallableClass2:
    def __init__(self):
        self._state = None

    def __call__(self, data):
        if self._state is None:
            self._state = 0
        if not data[0] == self._state:
            print(f"Stage2: {data[0]} ≠ {self._state}")
        assert np.all(np.diff(data) == 2)
        busy_wait(0.001 * len(data))
        result = [int(_/2) for _ in data]
        print("\nStage2", data[0]//100, time.time(), "\n")
        self._state += 2*len(data)
        return result


@ray.remote
class MyActor1(CallableClass1):
    def process(self, data):
        return self(data)


@ray.remote
class MyActor2(CallableClass2):
    def process(self, data):
        return self(data)


N_ROWS = 10_000
ds = ray.data.range(N_ROWS, parallelism=200)
pipe = ds.window(blocks_per_window=1)  # =1 required so the same actor at each stage sees all blocks

my_actor1 = MyActor1.remote()
my_actor2 = MyActor2.remote()

pipe = pipe.map_batches(lambda data: ray.get(my_actor1.process.remote(data)), batch_size=None)
pipe = pipe.map_batches(lambda data: ray.get(my_actor2.process.remote(data)), batch_size=None)

# Output can be pulled from the pipeline concurrently with its execution.
num_rows = 0
latest = -1
for batch in pipe.iter_batches():
    num_rows += len(batch)
    latest = batch[-1]
assert num_rows == N_ROWS, f"num_rows ({num_rows}) ≠ N_ROWS ({N_ROWS})"
assert latest == (N_ROWS - 1), f"latest ({latest}) ≠ N_ROWS-1 ({N_ROWS - 1})"
```

### Issue Severity

Low

**Comment by cboulay** [comment]
Thanks to @ericl 's [help in Slack](https://ray-distributed.slack.com/archives/C02PHB3SQHH/p1654216376863849?thread_ts=1654056153.405309&cid=C02PHB3SQHH), he identified that the problem is because of stage fusion optimization.

If I include

```
ctx = DatasetContext.get_current()
ctx.optimize_fuse_stages = False
```

then the script completes in 13.46 s. 

This is no longer blocking me, but I think maybe reflects a bug in how stage fusion optimization works. Maybe stage fusion should have some heuristic to abort if the number of stages after fusion would be <= `blocks_per_window`.

**Comment by ericl** [comment]
This is an interesting case where there is no data parallelism, and hence pipeline parallelism is the only way to speed things up. Stage fusion reduces memory overhead of the data parallel part, but in this case there wasn't much benefit since the data size was all in-memory anyway.

cc @clarkzinzow
