### ISSUE TITLE
[RLlib] get_filter_config for image component in ComplexInputNetwork

### ISSUE THREAD

**Issue by kk-55** [ray-project/ray#25401]
### What happened + What you expected to happen

In case your obs space is a Dict or Tuple space and there is no "conv_filters" key in your model_config, then by default `get_filter_config()` tries to find the conv filters for image components in the complex Dict or Tuple space, e.g. https://github.com/ray-project/ray/blob/8a9512bf629bcdd947d2b99c55b5c47e73cebfad/rllib/models/tf/complex_input_net.py#L64
But I guess it's a bug to give this method `obs_space.shape` as argument, since the obs space is a Dict or Tuple space and therefore `obs_space.shape` is `None`. I think it should be `component.shape`, where `component` is the image input.

### Versions / Dependencies

Ray 2.0.0.dev0, Python 3.9.12, Windows 10 Pro

### Reproduction script

Any example where no custom model is used and the obs space is a Dict or Tuple space containing an image component (3D Box).

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for reporting this! I'll try and get the linked PR merged soon. Let me know if you have more issues with this :)
