### ISSUE TITLE
[Core/Clusters] Guidance on how to size the Ray head

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#25410]
### Description

We should provide concrete info on how to size the Ray head node. This information should be informed by data from benchmarks.

See e.g.
https://ray-distributed.slack.com/archives/CN2RGCHRR/p1653918108654349

**Comment by wuisawesome** [comment]
Just throwing some brainstorming for what we could include in the docs. From my scalability work on ray core (which is where the existing guide information came from), the primary bottleneck was network bandwidth (and afaik it still is). 

I think the primary metrics we would want to look at are network bandwidth and resource report or heartbeat latency, as well as memory usage? 

@iycheng may have better or more detailed ideas now though.

**Comment by ecm200** [comment]
@wuisawesome I am not surprised to hear this. 

It is quite usual that the the lack of linear scaling of a given application is node network connection bounded. Although, this does depend on the type of application as well. One may expect a set of independent parallel tasks with relatively invariant computation time to scale more linearly than say a distributed computational task where regular updates between nodes is required per iteration of a computation.

So, I have a few broad questions on what these tests considered and what scenarios the documentation should attempt to cover moving forwards.

With regards to the scaling tests, I am wondering what type of computational problem was that for?

Was this cloud based or on a local networked machine?

For production applications, it's likely that the front end API which takes the part of the executing script could be in the same cloud infrastructure, indeed it could even be hosted on the same Kubernetes cluster, therefore this might break that dependency on network limiting scaling.

The requirement of the head node probably should also take into the account the type of Ray applications as well.

Will it be just `ray client` api model remote tasks executions?

Does using actors require more head node computational resource?

Does using the `ray job submission` api model require more head node computational resource?

**Comment by wuisawesome** [comment]
[Yes, improving the documentation of our scalability envelope is an entire separate question. @ecm200 you may be interested in reading this ](https://github.com/ray-project/ray/blob/master/release/benchmarks/README.md)

It is very heavily inspired by the [k8s scalability envelope](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md) and inherits many of the same properties.

Namely:

```
Some the properties of the envelope:

It's NOT a cube, because dimensions are sometimes not independent.
It's NOT convex.
As you move farther along one dimension, your cross-section wrt other dimensions gets smaller.
It's bounded.
It's decomposable into smaller envelopes.
```

**Comment by DmitriGekhtman** [comment]
bump

**Comment by wuisawesome** [comment]
@scv119

**Comment by scv119** [comment]
@iycheng @jjyao maybe something we can take as part of 2.2?
