### ISSUE TITLE
[KubeRay][Serve] autoscaler not removing worker nodes on if serve runs with argument --http-location EveryNode

### ISSUE THREAD

**Issue by ArzelaAscoIi** [ray-project/ray#25414]
### What happened + What you expected to happen

Ray autoscaler does not detect worker nodes as IDLE if serve is started with the `--http-location EveryNode`  argument. 
Scaling up the Counter example from the docs and using [this configuration of kuberay](https://github.com/askainet/ray-downscale-test/tree/main/kuberay) created replicas and started worker nodes. After the IDLE timeout was reached this, the replicas were removed, but the worker nodes kept running. 
If we remove the argument `--http-location EveryNode`, the worker nodes were removed. 

### Versions / Dependencies

Ray 1.12.0

(see https://github.com/askainet/ray-downscale-test)

### Reproduction script

https://github.com/askainet/ray-downscale-test

**Comment by DmitriGekhtman** [comment]
Ray pod autoscaling with KubeRay is alpha (experimental)
Can you try again using the (nightly) master branch operator from the KubeRay repo?
Let me know how it goes.

**Comment by DmitriGekhtman** [comment]
Also, in the dependencies: by Ray 1.2.0 do you mean "Ray 1.12.0"?

**Comment by ArzelaAscoIi** [comment]
Oh yes, there is a typo. I meant "Ray 1.12.0"

**Comment by askainet** [comment]
I'm sharing more debug logs to support our hypothesis that running `serve --http-location EveryNode` prevents the autoscaler from terminating nodes.

The problem with the autoscaler not excluding Ray Serve actor replicas from the resource usage metrics is that a cluster that scaled out to dozens of nodes will never be able to scale in when the demand drops, keeping several idle nodes with Ray Serve replicas that are not required to sustain the reduced load.

This is a log snippet from the autoscaler after only 1 replica of a Ray Serve deployment using 0.4 CPU is left in the cluster. The `load_metrics_report` used by the autoscaler to decide which nodes could be terminated includes the resource usage from the `ray::HTTPProxyActor` replicas of Ray Serve on each node:

```
2022-06-09 04:46:28,921 INFO monitor.py:494 -- Logging raw resource message pulled from GCS.
2022-06-09 04:46:28,921 INFO monitor.py:495 -- batch {
  node_id: "\0318>z\033\361\234\001*}\343\357\221\026\373\353L4%\034\024\177\026\\f\026\260\330"
  resources_available {
    key: "CPU"
    value: 1.0
  }
  resources_available {
    key: "memory"
    value: 536870912.0
  }
  resources_available {
    key: "node:10.244.0.9"
    value: 0.99
  }
  resources_available {
    key: "object_store_memory"
    value: 136926412.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 1.0
  }
  resources_total {
    key: "memory"
    value: 536870912.0
  }
  resources_total {
    key: "node:10.244.0.9"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 136926412.0
  }
  resource_load {
    key: "node:10.244.0.9"
    value: 0.01
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.9"
}
batch {
  node_id: "T\026\223t\241\r\207Zk\344\212\322\355\271\270\242E\3505\013Dl7\261\3340\252-"
  resources_available {
    key: "CPU"
    value: 1.0
  }
  resources_available {
    key: "memory"
    value: 536870912.0
  }
  resources_available {
    key: "node:10.244.0.12"
    value: 0.99
  }
  resources_available {
    key: "object_store_memory"
    value: 136926412.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 1.0
  }
  resources_total {
    key: "memory"
    value: 536870912.0
  }
  resources_total {
    key: "node:10.244.0.12"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 136926412.0
  }
  resource_load {
    key: "node:10.244.0.12"
    value: 0.01
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.12"
}
batch {
  node_id: "\316A\354\002\3431\352\272\3063s\324\361[Gv\235f\344\210$\005\272mYJ1C"
  resources_available {
    key: "CPU"
    value: 0.6
  }
  resources_available {
    key: "memory"
    value: 536870912.0
  }
  resources_available {
    key: "node:10.244.0.8"
    value: 0.99
  }
  resources_available {
    key: "object_store_memory"
    value: 136898150.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 1.0
  }
  resources_total {
    key: "memory"
    value: 536870912.0
  }
  resources_total {
    key: "node:10.244.0.8"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 136898150.0
  }
  resource_load {
    key: "CPU"
    value: 0.8
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.8"
}
batch {
  node_id: "\033&@-L\245\037u-t\002\264:_\352\271\376\023\340\366^\000\346\256<W\262\343"
  resources_available {
    key: "CPU"
    value: 1.0
  }
  resources_available {
    key: "memory"
    value: 536870912.0
  }
  resources_available {
    key: "node:10.244.0.10"
    value: 0.99
  }
  resources_available {
    key: "object_store_memory"
    value: 136927641.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 1.0
  }
  resources_total {
    key: "memory"
    value: 536870912.0
  }
  resources_total {
    key: "node:10.244.0.10"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 136927641.0
  }
  resource_load {
    key: "CPU"
    value: 0.4
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.10"
}
batch {
  node_id: "\370\332\334\322tg\255\362hA\3538W\267\243\247\326\034\323B\311\357dc1\0050\364"
  resources_available {
    key: "CPU"
    value: 1.0
  }
  resources_available {
    key: "memory"
    value: 536870912.0
  }
  resources_available {
    key: "node:10.244.0.11"
    value: 0.99
  }
  resources_available {
    key: "object_store_memory"
    value: 136935014.0
  }
  resources_available_changed: true
  resources_total {
    key: "CPU"
    value: 1.0
  }
  resources_total {
    key: "memory"
    value: 536870912.0
  }
  resources_total {
    key: "node:10.244.0.11"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 136935014.0
  }
  resource_load {
    key: "CPU"
    value: 0.4
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.11"
}
batch {
  node_id: "y\'\217a?\213;!\030)q\320\301\317\365V%;:\263N\343\020v\315\330\225\245"
  resources_available {
    key: "memory"
    value: 1000000000.0
  }
  resources_available {
    key: "node:10.244.0.7"
    value: 0.98
  }
  resources_available {
    key: "object_store_memory"
    value: 100000000.0
  }
  resources_available_changed: true
  resources_total {
    key: "memory"
    value: 1000000000.0
  }
  resources_total {
    key: "node:10.244.0.7"
    value: 1.0
  }
  resources_total {
    key: "object_store_memory"
    value: 100000000.0
  }
  resource_load {
    key: "CPU"
    value: 0.4
  }
  resource_load_by_shape {
  }
  node_manager_address: "10.244.0.7"
}
placement_group_load {
}

2022-06-09 04:46:28,921 INFO monitor.py:496 -- Done logging raw resource message.
2022-06-09 04:46:28,921 DEBUG gcs_utils.py:208 -- internal_kv_get b'autoscaler_resource_request' None
2022-06-09 04:46:29,218 INFO autoscaler.py:362 -- 
======== Autoscaler status: 2022-06-09 04:46:29.218918 ========
Node status
---------------------------------------------------------------
Healthy:
 1 head-group
 5 small-group
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.40000000000000036/5.0 CPU
 0.00/3.431 GiB memory
 0.00/0.731 GiB object_store_memory

Demands:
 (no resource demands)
2022-06-09 04:46:29,286 DEBUG gcs_utils.py:225 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 5 nodes\n - MostDelayedHeartbeats: {'10.244.0.9': 0.2973666191101074, '10.244.0.12': 0.2973365783691406, '10.244.0.8': 0.2973134517669678, '10.244.0.10': 0.29729223251342773, '10.244.0.11': 0.2972705364227295}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 0.4/5.0 CPU, 0.0 GiB/3.43 GiB memory, 0.0 GiB/0.73 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - small-group: 5" True None
2022-06-09 04:46:29,286 DEBUG legacy_info_string.py:26 -- Cluster status: 5 nodes
 - MostDelayedHeartbeats: {'10.244.0.9': 0.2973666191101074, '10.244.0.12': 0.2973365783691406, '10.244.0.8': 0.2973134517669678, '10.244.0.10': 0.29729223251342773, '10.244.0.11': 0.2972705364227295}
 - NodeIdleSeconds: Min=0 Mean=0 Max=0
 - ResourceUsage: 0.4/5.0 CPU, 0.0 GiB/3.43 GiB memory, 0.0 GiB/0.73 GiB object_store_memory
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
Worker node types:
 - small-group: 5
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:193 -- Cluster resources: [{'memory': 1000000000.0, 'object_store_memory': 100000000.0, 'node:10.244.0.7': 0.98}, {'memory': 536870912.0, 'object_store_memory': 136898150.0, 'CPU': 0.6, 'node:10.244.0.8': 0.99}, {'memory': 536870912.0, 'CPU': 1.0, 'object_store_memory': 136926412.0, 'node:10.244.0.12': 0.99}, {'memory': 536870912.0, 'node:10.244.0.9': 0.99, 'CPU': 1.0, 'object_store_memory': 136926412.0}, {'node:10.244.0.10': 0.99, 'object_store_memory': 136927641.0, 'CPU': 1.0, 'memory': 536870912.0}, {'node:10.244.0.11': 0.99, 'memory': 536870912.0, 'object_store_memory': 136935014.0, 'CPU': 1.0}]
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:194 -- Node counts: defaultdict(<class 'int'>, {'head-group': 1, 'small-group': 5})
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:211 -- Placement group demands: []
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:275 -- Resource demands: []
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:276 -- Unfulfilled demands: []
2022-06-09 04:46:29,611 DEBUG resource_demand_scheduler.py:284 -- Final unfulfilled: []
2022-06-09 04:46:29,692 DEBUG resource_demand_scheduler.py:309 -- Node requests: {}
2022-06-09 04:46:29,767 DEBUG gcs_utils.py:225 -- internal_kv_put b'__autoscaling_status' b'{"load_metrics_report": {"usage": {"memory": [0.0, 3684354560.0], "node:10.244.0.7": [0.020000000000000018, 1.0], "object_store_memory": [0.0, 784613629.0], "node:10.244.0.8": [0.010000000000000009, 1.0], "CPU": [0.40000000000000036, 5.0], "node:10.244.0.9": [0.010000000000000009, 1.0], "node:10.244.0.10": [0.010000000000000009, 1.0], "node:10.244.0.11": [0.010000000000000009, 1.0], "node:10.244.0.12": [0.010000000000000009, 1.0]}, "resource_demand": [], "pg_demand": [], "request_demand": [], "node_types": [[{"memory": 1000000000.0, "node:10.244.0.7": 1.0, "object_store_memory": 100000000.0}, 1], [{"node:10.244.0.8": 1.0, "memory": 536870912.0, "object_store_memory": 136898150.0, "CPU": 1.0}, 1], [{"node:10.244.0.9": 1.0, "object_store_memory": 136926412.0, "memory": 536870912.0, "CPU": 1.0}, 1], [{"node:10.244.0.10": 1.0, "memory": 536870912.0, "object_store_memory": 136927641.0, "CPU": 1.0}, 1], [{"memory": 536870912.0, "object_store_memory": 136935014.0, "node:10.244.0.11": 1.0, "CPU": 1.0}, 1], [{"object_store_memory": 136926412.0, "memory": 536870912.0, "node:10.244.0.12": 1.0, "CPU": 1.0}, 1]], "head_ip": null}, "time": 1654775188.9225554, "monitor_pid": 16, "autoscaler_report": {"active_nodes": {"head-group": 1, "small-group": 5}, "pending_nodes": [], "pending_launches": {}, "failed_nodes": []}}' True None
```

**Comment by DmitriGekhtman** [comment]
> Logging raw resource message pulled from GCS.

I'm glad you're able to make use of this [flag](https://github.com/ray-project/ray/pull/22136)!
I'm going to make a [note](https://github.com/ray-project/ray/issues/25636) to make this data visible by standard means.

**Comment by DmitriGekhtman** [comment]
So, the autoscaler's behavior in this case is in some sense "expected."

Tagging in on-call representative for the Serve team @architkulkarni.
The issue is that running `serve with argument --http-location EveryNode` causes >0 CPU actors to be place on all Ray workers. Then when the workload is done, the actors remain, the autoscaler sees >0 CPU usage, and the workers are not scaled down.

**Comment by simon-mo** [comment]
@DmitriGekhtman On Serve side we ensured http actors all allocated with num_cpus=0. you can see the regression test here: https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_standalone2.py#L650-L696

**Comment by architkulkarni** [comment]
@DmitriGekhtman this behavior (num_cpus=0) should be active in 1.12.0.  Is that consistent with what you see in the autoscaler logs?  I see 1 CPU available on each node but I'm not sure how to interpret that.  If there is 1 CPU total on each node then shouldn't the node by empty, so the autoscaler should remove the node?

**Comment by architkulkarni** [comment]
Note that we had another report of this issue about failing to downscale here https://github.com/ray-project/ray/issues/22734#issuecomment-1112710551 although we couldn't reproduce it.

**Comment by DmitriGekhtman** [comment]
> This is a log snippet from the autoscaler after only 1 replica of a Ray Serve deployment using 0.4 CPU is left in the cluster.

@askainet what version of Ray are you using? Looks like we're not expecting .4CPU from the http actors. Perhaps there's another stray, unrelated Ray task/actor?

@ArzelaAscoIi I realized autoscaler container envs are not currently exposed in the KubeRay operator. After I fix that, it should be possible to get a detailed list of resource demands.
(Also, nice GitHub handle, flashback to analysis class :) )

**Comment by askainet** [comment]
@DmitriGekhtman the original tests used these versions:
- v1.12.1 for the head and worker nodes
- ray-autoscaler:448f52
- kuberay/operator:69ecfce

After your comment, I have also tried v1.13.0 with the same result.

The 0.4 CPU actually comes from the deployment replica used by the script to run the test. The resources consumed by the Serve actor replicas (0.01 units of something) on every node are reflected in these particular metrics:

```
resources_available {
    key: "node:10.244.0.9"
    value: 0.99
  }
...
resources_available {
    key: "node:10.244.0.12"
    value: 0.99
  }
...
```

**Comment by architkulkarni** [comment]
Jumping in here because I remember this part-- the 0.01 requested resource of each IP is just a way to force the HTTPproxy actors to be scheduled one on each node (see https://github.com/ray-project/ray/blob/3278763dd7606abe070f9a53a851d8f59e0c705d/python/ray/serve/http_state.py#L126).

@DmitriGekhtman can confirm, but this shouldn't prevent the autoscaler from downscaling.

**Comment by DmitriGekhtman** [comment]
Ah, nice catch, this does prevent the autoscaler from downscaling. So the issue is diagnosed.

Any resource usage (resources_available < resources_total) prevents downscaling. (We have a [line item](https://github.com/ray-project/ray/issues/24323) to improve the docs on this point.) The individual node resource is not an exception.

On a related note, I think remember seeing some discussion on the Ray core side about potentially removing the individual node resource for performance reasons.
cc @ericl @jjyao @scv119

This ties directly into the [actor daemonset discussion](https://github.com/ray-project/ray/issues/25334)

I'm not 100% sure what the right immediate action is. In the long term, we need proper support for actor daemonsets.

A short-term solution would be to provide a flag to allow downscaling even when the individual node resource is in use.
Actually, I doubt this change in behavior would interfere with existing use-cases, so this flag could be on by default.
(We'd just need to document the change in behavior.)

**Comment by DmitriGekhtman** [comment]
I'll float the proposed solution in the relevant internal channels.

**Comment by architkulkarni** [comment]
Oh, interesting!  @simon-mo how could the test https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_standalone2.py#L650-L696 be passing then?  Does it have to do with the way we're mocking out the `worker_node_types` for the test?

For the solution, is placement groups with STRICT_SPREAD an option here? I could be way off the mark, haven't really used it before.

**Comment by DmitriGekhtman** [comment]
It scales down because the actor is killed, leaving 0 resource usage.
https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_standalone2.py#L687

**Comment by ericl** [comment]
So in 1.13, you can use NodeAffinityScheduling strategy to force actors on a node, and shouldn't need the custom resource any more. If we did that, does this resolve the issue? There wouldn't be a need to use placement groups at all then.

**Comment by DmitriGekhtman** [comment]
^ Ah, sounds like having Serve use Node affinity would solve this.

**Comment by DmitriGekhtman** [comment]
I believe this has been solved in the latest Ray and KubeRay versions.
Feel free to re-open if that's not the case.
