### ISSUE TITLE
[Datasets] TensorArray printing bug (for float arrays)

### ISSUE THREAD

**Issue by orm011** [ray-project/ray#25423]
### What happened + What you expected to happen

A pandas dataframe (or series) with a TensorArray column throws exception in __repr__() if the TensorArray element type is a float number (but works ok with an integer dtype inside the TensorArray).

```
import numpy as np
import pandas as pd
from ray.data.extensions import TensorArray

tint = TensorArray(np.arange(4).reshape(2,2))
# same as above but float
tfloat = TensorArray(np.arange(4).astype('float').reshape(2,2))

ser = pd.Series(tint)
r = ser.__repr__()
print(r)
# 0   [0 1]
# 1   [2 3]
# dtype: TensorDtype

ser = pd.Series(tfloat)
r = ser.__repr__() # throws exception
```

### Versions / Dependencies

ray.__version__, pd.__version__, np.__version__,sys.version_info

('1.12.1',
 '1.4.2',
'1.22.4',
 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0))

(though I've noticed this for several months, since last year)
I'm not clear what the contract with pandas.ExtensionArray is, it could be the issue is with pandas.

### Reproduction script
```
import numpy as np
import pandas as pd
from ray.data.extensions import TensorArray

tint = TensorArray(np.arange(4).reshape(2,2))
# same as above but float
tfloat = TensorArray(np.arange(4).astype('float').reshape(2,2))

ser = pd.Series(tint)
r = ser.__repr__()
print(r)
# 0   [0 1]
# 1   [2 3]
# dtype: TensorDtype

ser = pd.Series(tfloat)
r = ser.__repr__() # throws exception
```
### Issue Severity

Low: It annoys or frustrates me.

**Comment by orm011** [comment]
Just an additional note: the way pandas deals with Extension array formatting is as follows:
[ExtensionArrayFormatter]()

Specifically [this line](https://github.com/pandas-dev/pandas/blob/43a4bade627c7ae73f6b181dc4b087f11bca0619/pandas/io/formats/format.py#L1650)
converts the values into an array, which relies on  TensorArray.__array__.

An experiment where I extend TensorArray and over-ride __array__ to return a one dimensional numpy array of objects where each element object is itself an array shows this would make the formatting work fine. TensorArray has both .to_numpy() and __array__().

This doesn't explain why Integer arrays work well.

**Comment by clarkzinzow** [comment]
@orm011 Thank you for filing this issue! I'll look into this over the next week.

**Comment by orm011** [comment]
Thank you!
