### ISSUE TITLE
[Core] Loads report failed to catch killed driver.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#25429]
### What happened + What you expected to happen

When asks for resources more than the node has, it'll request from autoscaler for more nodes.

If the script asks for the resources got killed, the demand should recover to before.

it's not the case right now. For some cases, the demands will accumulate and never decrease.

### Versions / Dependencies

master

### Reproduction script

```
ray start --head --num-gpus=2
```

Then run
```
import ray
# ray.init(num_gpus=2, num_cpus=4)
ray.init(address='auto')

import os
import time
@ray.remote(num_gpus=3)
def use_gpu():
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
    time.sleep(1)

print(ray.get([use_gpu.remote(), use_gpu.remote()]))
```
Check `ray status`

Kill it 

Check `ray status`

The steps can be repeated and we'll see demand accumulates.

**Comment by rkooo567** [comment]
cc @iycheng can you confirm if it is P0?

**Comment by iycheng** [comment]
I think it's important to fix. @scv119  can decide the priority.

**Comment by iycheng** [comment]
Lower the priority given that it's not a blocker for 2.0
