### ISSUE TITLE
[air] Clarify the behavior of "resume_from_checkpoint" - does it also load the preprocessors included in checkpoint?

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#25441]
### What happened + What you expected to happen

It's not clear when we resume from checkpoint, is the original preprocessor state saved in the checkpoint loaded as well?

Reading the code, it seems we don't. Is this expected? Should we clarify the behavior here?

### Versions / Dependencies

Master

### Reproduction script

NA

### Issue Severity

Low: It annoys or frustrates me.

**Comment by richardliaw** [comment]
It needs to resume the entire state of the experiment. Does this break resume? If so, we should probably treat as P0

**Comment by amogkam** [comment]
Currently when resuming training from a checkpoint we don't load the preprocessor state. This means that the provided preprocessor is fitted again.

**Comment by justinvyu** [comment]
No longer have "preprocessors". Metadata field in the Trainers can be used to save arbitrary data with ckpts.
