### ISSUE TITLE
[Docs] API annotations break docstring rendering

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#25447]
### What happened + What you expected to happen

Adding API annotations (`@PublicAPI`, `@DeveloperAPI`) break how docstrings are rendered.

For example, here is the docstring for a method that is not annotated: 
![image](https://user-images.githubusercontent.com/8068268/171910813-40a0cf33-0629-4130-a1f5-bef2a2eb382b.png)

And here is the docstring for one that is:
![image](https://user-images.githubusercontent.com/8068268/171911497-eed4551f-cddb-4ef0-a199-795d17aa604b.png)

### Versions / Dependencies

Ray master

### Reproduction script

For example, see the `fit` method for this class https://docs.ray.io/en/master/ray-air/package-ref.html#trainer, compared to the docstring of other methods.

**Comment by amogkam** [comment]
cc @maxpumperla

**Comment by xwjiang2010** [comment]
Tried `functools.wrap` - does not help
Also see 
https://stackoverflow.com/questions/14383797/getting-sphinx-to-recognise-correct-signature/14448445#14448445
https://github.com/micheles/decorator

**Comment by zhe-thoughts** [comment]
Temporarily assigning to @maxpumperla but will follow up offline with Max

**Comment by bveeramani** [comment]
Fixed by #28499
