### ISSUE TITLE
[Serve][Doc] DAG Antipatterns

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#25472]
Now we have suggested patterns, we should also some common anti-patterns in Serve deployment graph

- too fine-grained splitting
- use handles in dynamic dispatch, when a static graph will do
- ...

**Comment by simon-mo** [comment]
@jiaodong anything to add here?

**Comment by jiaodong** [comment]
i think the highest priority one is re-assign variables in dag building that both sihan and i ran into while building benchmarks.
