### ISSUE TITLE
Tune / Jobs execution model broken due to change in runtime_env option behavior

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#25484]
The execution model of jobs is that the user defines a "job wide" working directory via runtime_envs. However, this recent PR breaks this by overwriting the entire job runtime_env when the user specifies a runtime_env option.

This means that if you try to set the env_vars for a task/actor, you get "ModuleNotFoundError", with no obvious way to figure out why.

This was caused by https://github.com/ray-project/ray/pull/24538

We should:
1. Revert the PR pending further discussion, to unbreak master, and
2. Ensure we have adequate tests to prevent this regression in the future.

**Comment by ericl** [comment]
This also means that Tune is broken in 2.0 for anyone submitting jobs, since Tune is setting env_vars naively using runtime_env.

**Comment by SongGuyang** [comment]
Can you use the API like：

Actor.options(runtime_env=ray.get_runtime_context().runtime_env.update({"X": "Y"}))

**Comment by ericl** [comment]
Yes, we could. But I don't think this is the first thing users will think of. Users shouldn't need to know about the working_dir in order to set their env vars.

**Comment by SongGuyang** [comment]
We already discussed this behavior for a few rounds. And there is a RPC issue for a long time.  I don't think reverting is the best choice currently. Of course, we can discuss anymore to optimize the inheritance.

**Comment by ericl** [comment]
I reviewed the previous discussion, and it appeared this issue Jobs did not come up. Given that this is new information, and empirically is breaking a huge fraction of our users (maybe 20%+ of Tune users), I think we need to revisit the decision.

**Comment by SongGuyang** [comment]
The change was merged after ray-1.x cut. Why it can affect users? It is a breaking change for 2.0.

**Comment by ericl** [comment]
We have users reporting Tune is completely broken in master due to this regression. This level of breakage is unacceptable even in master.

**Comment by simon-mo** [comment]
cc @edoakes @architkulkarni

**Comment by SongGuyang** [comment]
Do you have a UT for this in Tune? I didn't see any related failure in PR.

**Comment by ericl** [comment]
Indeed we didn't have an integration test. The specific scenario broken here is with jobs:

a.py:
```
def foo():
   pass
```

main.py:
```
from a import foo

def objective(*args):
    foo()
    
tune.run(objective)
```

If this is submitted as a job, this basic scenario will fail with ModuleNotFoundError, since the working_dir field gets overwritten by Tune internally setting some env_vars. I want to emphasize this is a general "foot gun" for Jobs that the proposed change introduced into the API, that any user naively trying to set env vars will run into, not just Tune.

**Comment by raulchen** [comment]
@ericl It looks like an issue on the Tune side, right? if so, can someone fix this asap? So we can revert that PR back before getting conflicts.

**Comment by raulchen** [comment]
https://github.com/ray-project/ray/pull/24538 is important for future Runtime Env development. And we've come to consensus that such a behavior change is acceptable for 2.0. 
I'd suggest fixing this compatibility issue on the Tune side. Also, we can think about how to identify this issue can print warnings when other users update to 2.0.

**Comment by ericl** [comment]
Wait: we do not have consensus on the API change any more: new information has come up that makes it seem like not a good idea...

**Comment by architkulkarni** [comment]
To summarize: The general problem is in Jobs:

If the user has a jobs script 
```python
# script.py
ray.init()

@ray.remote(runtime_env={"env_vars": {"A": "B"}})
def f():
    # Use some files in working_dir
    pass
```

And when the user submits their job (with `ray job submit --working-dir=/my/dir -- python script.py`) they expect their job to have access to the working dir, but with the new inheritance behavior they won't have access inside `f`.  The Tune issue was a specific case of this where the user is Ray Tune.

Here are the most obvious options.  Are there other options which are a compromise between these two? @SongGuyang @raulchen maybe you have some ideas?

### Option 1
- Add to the docs that all Ray Jobs users must use the API `runtime_env=ray.get_runtime_context().runtime_env.update({"X": "Y"})` in their Jobs scripts.
- Unrevert the inheritance PR, along with applying the above update within the Tune codebase.
### Option 2
- We decide that the new inheritance behavior is not worth the confusing API for Jobs users, despite it being an improvement in other ways.
- The PR stays reverted, and we stick with the old inheritance behavior.


I agree that the new API is not obvious for Jobs users.  It's not at the top of their mind that`working_dir` is a part of `runtime_env` (the API `ray job submit --working-dir=/my/dir -- python script.py` doesn't mention `runtime_env` anywhere.)

**Comment by architkulkarni** [comment]
Downgrading to P1 because the breakage was fixed by reverting the PR.

**Comment by ericl** [comment]
**Option 3**: Raise an error if the user specifies an override runtime_env that has less keys. For example, suppose:

Job runtime_env is {"working_dir": "/foo"}.
- Case 1: User specifies {"working_dir": "/bar", "env_vars": {"foo": "bar"}} -> OK
- Case 2: User specifies {"working_dir": None, "env_vars": {"foo": "bar"}} -> OK
- Case 3: User specifies {"env_vars": {"foo": "bar"}} -> ValueError: the runtime_env you specified must specify the working_dir key from the parent runtime_env. Use `ray.runtime_env.get_runtime_env.update({...})` to merge the runtime_envs.

**Comment by matthewdeng** [comment]
Throwing another idea into the pool, can we default to the existing merge logic and expose a flag that the user can set when using a runtime_env to discard the parent runtime_env?

**Comment by SongGuyang** [comment]
@architkulkarni First, we need a conclusion, option 1 or 2 or 3 or something, up to you guys. Second, we need a design about how to process the inheritance after we make all the runtime env modules to be separate plugins(I think we should do it in agent, instead of worker). Can you lead this two issues?

**Comment by architkulkarni** [comment]
> @architkulkarni First, we need a conclusion, option 1 or 2 or 3 or something, up to you guys. Second, we need a design about how to process the inheritance after we make all the runtime env modules to be separate plugins(I think we should do it in agent, instead of worker). Can you lead this two issues?

Yep, thanks for outlining the next steps. I'll make sure these issues have a conclusion.   I agree we need to properly design where to process the inheritance in case we use more complicated inheritance logic; I'll think about how to do this.

**Comment by SongGuyang** [comment]
Thanks, please ping us when you have conclusion and progress.

**Comment by hora-anyscale** [comment]
Per Triage Sync: Can you please confirm if this is still an issue and what the priority on this should be?

**Comment by architkulkarni** [comment]
The immediate issue is fixed and the conclusion is in https://github.com/ray-project/ray/issues/21818, but I still need to follow up with a design for long-term maintainability.  I'll move future discussion of the design to the linked RFC issue and close this issue.
