### ISSUE TITLE
ValueError: pyarrow.lib.DataType has the wrong size, try recompiling. Expected 56, got 48

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2549]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **Ray installed from (source or binary)**: binary (pip)
- **Ray version**: 0.5.0
- **Python version**: 3.6.3
- **Exact command to reproduce**:

```
$ ray --help
```

### Describe the problem

I just installed ray inside the virtualenv on my machine and running `ray --help` throws an error:

```
Traceback (most recent call last):
  File ".../virtualenv/aika36/bin/ray", line 7, in <module>
    from ray.scripts.scripts import main
  File ".../virtualenv/aika36/lib/python3.6/site-packages/ray/__init__.py", line 50, in <module>
    from ray.worker import (error_info, init, connect, disconnect, get, put, wait,
  File ".../virtualenv/aika36/lib/python3.6/site-packages/ray/worker.py", line 22, in <module>
    import pyarrow.plasma as plasma
  File "lib.pxd", line 41, in init pyarrow.plasma
ValueError: pyarrow.lib.DataType has the wrong size, try recompiling. Expected 56, got 48
```

**Comment by suquark** [comment]
@mitar I encountered this problem after interrupting the compilation before. It could be fix by deleting all pyarrow-related third-party tools and rebuild them. There seems to be some states cannot be reset by recompiling unless we delete them manually.

**Comment by mitar** [comment]
Hm, I was installing from pip?

**Comment by robertnishihara** [comment]
I'm not too sure what the issue could be here. Does it still happen if you install the nightly wheels? E.g., http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray.

**Comment by robertnishihara** [comment]
Is this in Docker? Do you have a Dockerfile that reproduces the issue? Or will it be difficult to recreate your environment?

**Comment by mitar** [comment]
Sadly it is outside. Inside Docker it works. :-)

**Comment by robertnishihara** [comment]
We just looked into it in person. Creating a new virtualenv fixed the issue. In the virtualenv that was failing, installing ray 0.4.0 caused the problem to go away. Then reverting back to 0.5.0 continued to work.

So, I have no idea what the issue is, but it seems to have gone away.
