### ISSUE TITLE
[Core] using `@ray.remote` on an extended class with __init_subclass__ causes the metaclass to initialize multiple times

### ISSUE THREAD

**Issue by anadahalli** [ray-project/ray#25491]
### What happened + What you expected to happen

`@ray.remote` on an extended class with `__init_subclass__` causes the metaclass to initialize multiple times.

The same can be observed also while creating the actor from the actor class.

### Versions / Dependencies

Ray version == 1.12.1

### Reproduction script

```python
import ray

ray.__version__  # 1.12.1

class Base:
    def __init_subclass__(cls, *args, **kwargs):
        print("init_subclass")

@ray.remote
class Actor(Base):
    def __init__(self):
        print("init")

""" stdout
init_subclass 
init_subclass
init_subclass 
"""

a = Actor.remote()

""" stdout
(pid=595687) init_subclass
(pid=595687) init_subclass
(Actor pid=595687) init
"""
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by tupui** [comment]
Hi @anadahalli, thank you for reporting. This is due to a few things. When an actor is created:

1. The class is initialized
2. `DerivedActorClass` is called to `actor class we are constructing inherits from the original class so it retains all class properties`

I am not sure about where the third call is coming from though.

**Comment by mattip** [comment]
Metaclasses are one way to condense more verbose code into more concise code by using metaprogramming. I would start with writing the more verbose code first, and then see how to proceed. 

Start with your higher-level APIs, get your tests in place to exercise them, implement as simply as possible, and only then start to refactor things to use more advanced techniques.
