### ISSUE TITLE
[RLlib] failing to log with IO operation on closed file

### ISSUE THREAD

**Issue by LunarEngineer** [ray-project/ray#25505]
### What happened + What you expected to happen

Running a PPO agent on a custom environment in the SageMaker Processing execution framework is dying when attempting to write to apparently closed log files.

## Error text file

```shell
Failure # 1 (occurred at 2022-06-03_18-00-46)
Traceback (most recent call last):
  File "/opt/.venv/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 901, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/opt/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/.venv/lib/python3.9/site-packages/ray/worker.py", line 1811, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPOTrainer.__init__()[39m (pid=392, ip=172.24.235.90, repr=PPOTrainer)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

[36mray::PPOTrainer.__init__()[39m (pid=392, ip=172.24.235.90, repr=PPOTrainer)
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 830, in __init__
    super().__init__(
  File "/opt/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 149, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 860, in setup
    self.validate_config(self.config)
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/ppo/ppo.py", line 268, in validate_config
    logger.info(
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1091, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1004, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/opt/.venv/lib/python3.9/site-packages/ray/tune/utils/util.py", line 184, in write
    self.stream1.write(*args, **kwargs)
ValueError: I/O operation on closed file.
```

## Standard Error / Output

An empty standard output file was generated.

This is the contents of the stderr.

```shell
[ERROR 2022-06-03 18:00:46,550] worker.py: 449  Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::PPOTrainer.__init__()[39m (pid=392, ip=172.24.235.90, repr=PPOTrainer)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

[36mray::PPOTrainer.__init__()[39m (pid=392, ip=172.24.235.90, repr=PPOTrainer)
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 830, in __init__
    super().__init__(
  File "/opt/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 149, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 860, in setup
    self.validate_config(self.config)
  File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/ppo/ppo.py", line 268, in validate_config
    logger.info(
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1091, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1004, in handleError
    sys.stderr.write('--- Logging error ---\n')
  File "/opt/.venv/lib/python3.9/site-packages/ray/tune/utils/util.py", line 184, in write
    self.stream1.write(*args, **kwargs)
ValueError: I/O operation on closed file.
```

## Configuration File

I'm supplying a yaml file.

```yaml
custom-ppo:
    env: CustomEnvironment-V0
    run: PPO
    stop:
        training_iteration: 2
    time_budget_s: 300
    log_to_file: true
    config:
        framework: torch
        kl_target: 0.01
        env_config:
            dataset: "/opt/ml/processing/input/data/training_fold.parquet"
            env_param_one: "TARGET"
            env_param_two: "THING"
            env_param_three: "OTHER_THING"
            env_param_four: "Last Thing"
            max_steps: 5
            batch_size: 5
```

### Versions / Dependencies

Debian Slim Bullseye

python>=3.9.10

gym==0.21.0
mlflow==1.24.0
numpy==1.22
sqlalchemy==1.4.35
torch==1.10.2
tensorflow==2.8.0
tensorflow-probability==0.16.0
ray[default]==1.12.0
ray[tune]==1.12.0
ray[rllib]==1.12.0
pyarrow==8.0.0
tune-sklearn==0.4.2
scikit-learn==0.24.2
scikit-optimize==0.8

### Reproduction script

I apologize, but I am not immediately capable of sharing an easily reproducible script; I understand that this makes this more difficult to debug and less likely to garner official support.

### Issue Severity

High: It blocks me from completing my task.

**Comment by LunarEngineer** [comment]
I'm attempting to remove the log to file to discern if this is the root cause of the issue. I will update this issue with more information as available.

**Comment by tupui** [comment]
Hi @LunarEngineer, thank you for reporting. It might be a permission issue with the process not having the required rights to access the location on the file system. Did you check that?

**Comment by LunarEngineer** [comment]
@tupui I can certainly check that, but I don't _think_ that's an issue. I'm assuming that the default ray file logging location is within the ray results folder and ray *is* writing out files.

Is the default location (i.e. when log to file is `true` in the loaded yaml) not within the ray results folder?

**Comment by tupui** [comment]
Logs are

**Comment by tupui** [comment]
Not sure how to help you more without a reproducer. I would try to debug what is `self.stream1` and see the args being passed. Check that the file in question is what is expected, etc.

**Comment by tupui** [comment]
Ah ok I see, so you were moving things around during the run so it would not find the files anymore. Thank you for the details, I will close it now as you are suggesting then.

**Comment by LunarEngineer** [comment]
@tupui do you mind if we revisit this? I was mistaken when I thought this was resolved.

I've managed to get a local environment up and running to emulate the prod env.

I am no longer moving files in the run and it is still dying.

When I investigate the stream device (I've monkey patched `ray/tune/utils/util.py::Tee` to print the data structure on init and write) I don't see any immediate difference in the objects. I will continue to investigate, but any direction you would be willing to provide would be very helpful.

**Comment by tupui** [comment]
Sure no problem I am still monitoring this.

**Comment by LunarEngineer** [comment]
To make things slightly more challenging it appears that the Ray exception is stalling execution of the container; it's just hanging.

**Comment by LunarEngineer** [comment]
Some additional context that may be helpful as I continue to troubleshoot.

When the PPO trainer instantiates and runs through the config validation it's dying when it tries to run logger.info.

When I comment out that line, specifically, the error is minorly different, but the similarities helped me narrow down where the issue is coming from.

```shell
(PPOTrainer pid=7028) 2022-06-07 13:04:13,249   ERROR worker.py:449 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPOTrainer.__init__() (pid=7028, ip=172.17.0.3, repr=PPOTrainer)
(PPOTrainer pid=7028)   File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 1035, in _init
(PPOTrainer pid=7028)     raise NotImplementedError
(PPOTrainer pid=7028) NotImplementedError
(PPOTrainer pid=7028)
(PPOTrainer pid=7028) During handling of the above exception, another exception occurred:
(PPOTrainer pid=7028)
(PPOTrainer pid=7028) ray::PPOTrainer.__init__() (pid=7028, ip=172.17.0.3, repr=PPOTrainer)
(PPOTrainer pid=7028)   File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 830, in __init__
(PPOTrainer pid=7028)     super().__init__(
(PPOTrainer pid=7028)   File "/opt/.venv/lib/python3.9/site-packages/ray/tune/trainable.py", line 149, in __init__
(PPOTrainer pid=7028)     self.setup(copy.deepcopy(self.config))
(PPOTrainer pid=7028)   File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/agents/trainer.py", line 911, in setup
(PPOTrainer pid=7028)     self.workers = WorkerSet(
(PPOTrainer pid=7028)   File "/opt/.venv/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 134, in __init__
(PPOTrainer pid=7028)     remote_spaces = ray.get(
(PPOTrainer pid=7028) ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
(PPOTrainer pid=7028)   class_name: RolloutWorker
(PPOTrainer pid=7028)   actor_id: 9a22a2bbea606fc14a89062f01000000
(PPOTrainer pid=7028)   pid: 7075
(PPOTrainer pid=7028)   namespace: d1f39eed-4d45-455b-83f8-8cca2440897e
(PPOTrainer pid=7028)   ip: 172.17.0.3
(PPOTrainer pid=7028) The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT
```

In the [PPO trainer](https://github.com/ray-project/ray/blob/releases/1.12.0/rllib/agents/ppo/ppo.py) it's not calling super().setup(), neither does it have a setup defined for the trainer class, so it's inheriting setup from trainer.

In the setup when it tries to run _init it sees the NotImplementedError and attempts to run a 'default' remote worker setup ([WorkerSet](https://github.com/ray-project/ray/blob/releases/1.12.0/rllib/evaluation/worker_set.py)).

It's here that it's dying when it attempts to pull back the remote space; unfortunately the sigterm isn't appropriately terminating the tune run and it's just hanging indefinitely, so the container doesn't exit, making debugging a bit more challenging.

I'm investigating to see why the remote workers are dying and why they are not appropriately logging their failure.

**Comment by LunarEngineer** [comment]
Digging into the RolloutWorker instantiation to see why it's failing I've got it isolated to the environment creation function. That's on me and I'll track that down.

From my point of view I do think that the execution framework failing to halt appropriately at this point *is* an issue. Would you prefer to use this space to continue that conversation?

**Comment by tupui** [comment]
It's fine to continue here. Thank you for investigating the issue @LunarEngineer
