### ISSUE TITLE
[RLlib] DQN uses torch.range which is depreceated

### ISSUE THREAD

**Issue by tzy004** [ray-project/ray#25503]
### What happened + What you expected to happen

Running DQN code with CarPole env with numbers of atoms greater than one (distributional Q-learning on) results in torch warning:

`(RolloutWorker pid=33510) /home/morlowski/.cache/pypoetry/virtualenvs/aipilot-ej63hvSG-py3.7/lib/python3.7/site-packages/ray/rllib/agents/dqn/dqn_torch_model.py:151: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
(RolloutWorker pid=33510)   z = torch.range(0.0, self.num_atoms - 1, dtype=torch.float32).to(`

I guess as well that after torch update warning may become error. 

### Versions / Dependencies

Linux Ubuntu 22.04 LTS
Ray @ 1.12.1
torch @ 1.10

### Reproduction script

import ray
from ray import tune

ray.init()

config = {
    "env": "CartPole-v1",
    "num_workers": 1,
    "train_batch_size": 128,
    "learning_starts": 128,
    "model": {"fcnet_hiddens": [32]},
    "framework": "torch",
    "num_atoms": 20,
}

tune.run("DQN", name="DQN_distributed", config=config, stop={"training_iteration": 100})

### Issue Severity

Low: It annoys or frustrates me.

**Comment by tupui** [comment]
Thank you for reporting @tzy004. Would you be interested in making a PR?
