### ISSUE TITLE
[Docs] [Job] Tail Job logs REST endpoint missing documentation

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#25512]
### Description

We only have it for the Python API and the CLI, documented here https://docs.ray.io/en/latest/cluster/jobs-package-ref.html#ray-job-submission-api-ref

But it's missing for the REST API.  (Documented here https://docs.ray.io/en/latest/cluster/job-submission.html#rest-api)

**Comment by rkooo567** [comment]
I think this should be done by the API server-level documentation. I think it is okay to add a doc as a short term solution. cc @alanwguo for the future work on the dashboard side (auto documenting REST APIs).

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/30417
