### ISSUE TITLE
[cli][usability] ray stop prints errors during graceful shutdown

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#25518]
### What happened + What you expected to happen

Sometimes when Ray is gracefully stopped with `ray stop` some of the helper processes still exit with non-zero exit codes. Ideally we should always exit 0 to avoid false alarms

### Versions / Dependencies

Master

### Reproduction script

https://discuss.ray.io/t/ray-on-slurm-shutdown-throws-errors/5939

### Issue Severity

Low: It annoys or frustrates me.

**Comment by simontindemans** [comment]
Specifically, this happens when ray is launched with the `--block` option.

**Comment by rickyyx** [comment]
Thanks @simontindemans for the minimal reproducible workflow! That's really helpful. 

 I think I have a good understanding of why this happens:
- `ray stop` sends SIGTERM to all the ray processes. 
- The reporting routine collects the dead processes and report their exit status (even 0) with false alarms. 


There are two issues that cause the false alarms: 
1. The cli reporting [routine](https://github.com/ray-project/ray/blob/64f9a9066fc371cd3c24e2f8093e6d7039d92c2c/python/ray/scripts/scripts.py#L915-L931) is falsely reporting dead processes even with exit code 0 (This should be an easy filter fix) 
2. Some of the processes (namely, `reaper`, `dashboard`, `log_monitor`), do not handle `SIGTERM`, unlike gcs_server [does](https://github.com/ray-project/ray/blob/87dc57df26c39c85e6068e9b7d7b8735f68992ca/src/ray/gcs/gcs_server/gcs_server_main.cc#L94-L103)

For 2, I could refactor the reporting routine code to ignore anything terminated with `SIGTERM`. Not sure if we want to change those processes to handle SIGTERM gracefully like gcs_server.  


@iycheng @scv119

**Comment by scv119** [comment]
@rickyyx sounds like handle SIGTERM gracefully is a better option?

**Comment by rickyyx** [comment]
> @rickyyx sounds like handle SIGTERM gracefully is a better option?

Yeah - I will look into that if that's not too involved and piggyback them in the PR addressing this.
