### ISSUE TITLE
ray.init() doesn't have the argument 'ignore_reinit_error'

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#2555]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.5.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: ray.init(ignore_reinit_error=True)

### Describe the problem
From the ray latest documentation, it looks like there's an argument `'ignore_reinit_error'` to set when we call `ray.init()`. However, when I do `ray.init(ignore_reinit_error=True)` in ray-0.5.0, it seems unable to find the argument. Wonder if I I missed anything or something incorrect.

**Comment by robertnishihara** [comment]
It's in the current master branch, so you need to install the latest version. See http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray

**Comment by RuofanKong** [comment]
Ahh i see. thanks! i thought it's supported in 0.5.0. close it now.
