### ISSUE TITLE
[Docs] Sort Ray version order

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#25555]
### Description

The Ray versions that pop up from the bottom right `v: latest` button should show up in order. However, they're currently out of order, with the latest releases inserted in the middle. This makes it harder to change versions, which is needed to permalink documentation.

<img width="1440" alt="Screen Shot 2022-06-07 at 11 34 14 AM" src="https://user-images.githubusercontent.com/92341594/172456937-3a636bc9-1924-471d-b52d-9f9ea805d816.png">

### Link

The versions pop up after clicking the version button on the bottom-right of [any page](https://docs.ray.io/en/latest/).

<img width="99" alt="Screen Shot 2022-06-07 at 11 38 59 AM" src="https://user-images.githubusercontent.com/92341594/172457744-e2119263-72fa-489b-a70f-844e9917f503.png">

**Comment by rkooo567** [comment]
seems like it is fixed
