### ISSUE TITLE
[docker] Open source GPU docker images fail to start with cuda error

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#25588]
### What happened + What you expected to happen

When starting any of the `nightly` docker images, we run into this:

```
 docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container: unknown.
```

The cause is likely that NVIDIA removed some drivers from their base image:

https://gitlab.com/nvidia/container-images/cuda/-/commit/da52c6cc317ea7f8afcb7d9bf75674ef51e28164?page=2

We should fix the docker image build.

### Versions / Dependencies

Master

### Reproduction script

--

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Bumping up to P0 now that we're starting process for 2.0 beta release

**Comment by amogkam** [comment]
Also after fixing this, we have to make sure that we change our release tests to run on nightly images again (#25373)

**Comment by krfricke** [comment]
Also @cadedaniel is working on adding a nightly test for OSS cluster launcher which should probably include these images.
