### ISSUE TITLE
[Core] Ray broken when the latest protobuf is used  (>= 4.21.1)

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#25638]
### What happened + What you expected to happen

Seems like Ray will be broken when protobuf >= 4.21.1 is used because it requires building protobuf using the version >= 3.19, but we are using protobuf 3.16 for our core dependency. https://github.com/ray-project/ray/blob/2614c24e475be13d4d67997edd35c19f53f6cb2c/bazel/ray_deps_setup.bzl#L91

```
  File "<stdin>", line 1, in <module>
  File "/Users/saitcakmak/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ray/__init__.py", line 108, in <module>
    import ray._raylet  # noqa: E402
  File "python/ray/_raylet.pyx", line 115, in init ray._raylet
  File "/Users/saitcakmak/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ray/exceptions.py", line 7, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "/Users/saitcakmak/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ray/core/generated/common_pb2.py", line 15, in <module>
    from . import runtime_env_common_pb2 as src_dot_ray_dot_protobuf_dot_runtime__env__common__pb2
  File "/Users/saitcakmak/opt/anaconda3/envs/py37/lib/python3.7/site-packages/ray/core/generated/runtime_env_common_pb2.py", line 42, in <module>
    serialized_options=None, json_name='packages', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  File "/Users/saitcakmak/opt/anaconda3/envs/py37/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

We fixed the issue by restricting the upper bound of the protobuf version https://github.com/ray-project/ray/issues/25282. However, this can still trigger the same issue when protobuf >= 4.21.1 is downloaded unexpectedly. For example,

```
pip install ray[default]
# Install protobuf >= 4.21.1 by mistake either directly or transitively
```

Ideally, we should just make it work when protobuf >= 4.21.1 is used. Based on the error message, it seems like upgrading the core protobuf version will just fix the issue (there could be other incompatibility issues, although I doubt there will be). 

### Versions / Dependencies

Master

### Reproduction script

N/A

**Comment by mvashishtha** [comment]
@rkooo567 @scv119 this is a bug with older versions of ray, too. ray 1.7, 1.11, 1.12.0, or 1.12.1 seem to pin protobuf >= 3.8.0, and they all break with the latest protobuf version, 4.21.1. Should the older ray versions be patched to say `protobuf<4.21.1`?

**Comment by rkooo567** [comment]
@mvashishtha @scv119 can confirm, but I think we will do the backport release to 1.13 (or maybe 1.12). Let's wait for his confirmation.

**Comment by mvashishtha** [comment]
@rkooo567 a clean install of ray 1.12.1 is broken because ray 1.12.1 requires the latest version of protobuf, and the latest version of protobuf is incompatible with ray 1.12.1. It looks like my comment [here](https://github.com/ray-project/ray/issues/25638#issuecomment-1154422416) in this thread has not been addressed. Among other things, a consequence of this problem is that Modin CI is currently failing, as [here](https://github.com/modin-project/modin/runs/6991648754?check_suite_focus=true). Modin has to pin ray<1.13 for other reasons (#25675), so it looks like we'll have to also pin protobuf<4.

Is it possible to modify older ray releases so that they either work with the latest version of protobuf, or specify an older version of protobuf?

cc @pyrito

**Comment by richardliaw** [comment]
> Is it possible to modify older ray releases so that they either work with the latest version of protobuf, or specify an older version of protobuf?

We can release a 1.13.1 soon, but we will not modify older ray versions since this will likely cause more problems in production (and breaks reproducibility for the rest of the world).

**Comment by devin-petersohn** [comment]
@richardliaw Modin doesn't work on 1.13 for the reasons above, could you also backport to 1.12 for a 1.12.2 release?

**Comment by crclark** [comment]
> We can release a 1.13.1 soon, but we will not modify older ray versions since this will likely cause more problems in production (and breaks reproducibility for the rest of the world).

We just hit this issue, too. Could you explain what problems modifying older versions of Ray would cause? As I understand it, all that needs to be done is adding stricter version bounds on protobuf so that an incompatible version won't be used.

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/25648 -> this was the fix for the root cause. Otherwise, you just need to avoid the grpcio version that causes this issue (which I believe was protobuf >= 3.15.3, < 4.0.0)
