### ISSUE TITLE
[RLlib]: JsonReader does not support multiple rollout workers

### ISSUE THREAD

**Issue by Rohan138** [ray-project/ray#25631]
### What happened + What you expected to happen

The current implementation of the JsonReader does not work correctly with multiple rollout workers (On both training and evaluation). Since all workers point to the same file, calling worker.sample() returns the same samples instead of independent steps/episodes.

We can fix this by deprecating the JsonReader (and all other readers e.g. D4RLReader) and just using DatasetReader to shard the input file for each worker. I'll put in a PR for this soon.

### Versions / Dependencies

ALL

### Reproduction script

Repro script: Run this from one dir above `ray`
```
import ray
from ray.rllib.algorithms.dqn import DQNConfig
import os
import numpy as np

cur_dir = os.getcwd()
path = cur_dir + "/ray/rllib/tests/data/cartpole/small.json"
assert os.path.isfile(path)

### With JsonReader
config = (
    DQNConfig()
    .environment(env="CartPole-v0")
    .rollouts(num_rollout_workers=2)
    .offline_data(input_=path)
)
trainer = config.build()
batches = ray.get([w.sample.remote() for w in trainer.workers.remote_workers()])
for k in batches[0].keys():
    # Batches are identical, not what we want
    assert np.all(batches[0][k] == batches[1][k])

### With DatasetReader, works correctly
config = (
    DQNConfig()
    .environment(env="CartPole-v0")
    .rollouts(num_rollout_workers=2)
    .offline_data(input_="dataset", input_config={"format": "json", "path": path})
)
trainer = config.build()
batches = ray.get([w.sample.remote() for w in trainer.workers.remote_workers()])
for k in batches[0].keys():
    # Batches are not identical, what we want
    assert np.any(batches[0][k] != batches[1][k])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
this should be solved by #26304
