### ISSUE TITLE
[Docs] Action Masking example for RLlib

### ISSUE THREAD

**Issue by vlainic** [ray-project/ray#25652]
### Description

I have a simple, yet helpful IMO, proposal to add a [link towards the action masking model](https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py) in the docs for [Parametric Action Spaces](https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces) where bolded:
"Depending on your use case it may make sense to use **just the masking**, just action embeddings, or both."

As this was not here, I was only looking into parametric_actions_model.py and got a bit lost - which is my fault ofc :see_no_evil:

### Link

https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces

**Comment by scv119** [comment]
@gjoliver let you triage.

**Comment by gjoliver** [comment]
I like the idea.
@christy, do you have time to make this small change?

**Comment by christy** [comment]
Hi @vlainic , 
Just checking if I understand this right.  You're suggesting addling these links to [docs page](https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces): 

1. Add link from text “just the masking” to https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py#L69 (since Torch models are our default)
2. Add link from text “just action embeddings” to https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole.py

**Comment by gjoliver** [comment]
@christy, I think it's simpler than that.
we just need to link the text "just the masking" in this page https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces to this example (without line #), https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py

**Comment by christy** [comment]
It looks to me like we only have runnable examples for the “just action embeddings" case.  Both of these examples?  

https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole.py  
 https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole_embeddings_learnt_by_model.py

Should we change the text to be clearer?

OLD
Depending on your use case it may make sense to use just the masking, just action embeddings, or both. For a runnable example of this in code, check out [parametric_actions_cartpole.py](https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole.py).

NEW
Depending on your use case it may make sense to use[ just the **masking**](https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py), [just action **embeddings**](https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole.py), or [**both**](https://github.com/ray-project/ray/blob/master/rllib/examples/models/parametric_actions_model.py). For a runnable example of "just action embeddings" in code, check out [parametric_actions_cartpole.py](https://github.com/ray-project/ray/blob/master/rllib/examples/parametric_actions_cartpole.py).

**Comment by vlainic** [comment]
> @christy, I think it's simpler than that. we just need to link the text "just the masking" in this page https://docs.ray.io/en/latest/rllib/rllib-models.html#variable-length-parametric-action-spaces to this example (without line #), https://github.com/ray-project/ray/blob/master/rllib/examples/models/action_mask_model.py

Yes, @gjoliver that was my initial idea, very simple - w/0 the lines and only action masking link. However @christy proposal is also fine with me 😄

**Comment by gjoliver** [comment]
yeah, I see what you mean now @christy.
that seems good to me too. thanks.

**Comment by christy** [comment]
closed by https://github.com/ray-project/ray/pull/26793
