### ISSUE TITLE
[Java] Allow Ray actors to start in a different namespace than the driver in Java API

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#25665]
### Description

The Java API should allow Ray actors to start in a different namespace than the driver.

In Python, this is allowed using the actor options. E.g.:

```python
ray.init(namespace="driver-namespace")

@ray.remote(namespace="actor-namespace")
class ExampleActor:
    ...

# Starts ExampleActor in the
# "actor-namespace" namespace
ExampleActor.remote()
```

More context can be found [here](https://discuss.ray.io/t/starting-java-actors-in-different-namespaces-than-the-ray-driver/6449).

### Use case

This provides finer-grained control over Ray actor behavior. Ray applications can make assumptions about their actors' namespaces regardless of the driver namespace.

**Comment by raulchen** [comment]
@simon-mo This change should be simple. I'll ask @jovany-wang to work on this when he come back to work next week. Probably it will be done after 6/22, but definitely before 7/22.

**Comment by simon-mo** [comment]
Awesome thanks!

**Comment by jovany-wang** [comment]
Duplicate to #22563
