### ISSUE TITLE
[tests] Move some tests + consider using GNU Parallel for Jenkins?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2566]
### Describe the problem

Our testing/dev loop is pretty slow.

The Jenkins machines are more powerful than Travis (48 cores vs 2). 
Often times we are left waiting many hours for Travis tests to build, while the Jenkins tests execute almost instantly.

A lot of our Jenkins tests really only require 2 cores or so, so we can further optimize this by running these tests concurrently with something like GNU Parallel (which has [resource-based load balancing](https://www.gnu.org/software/parallel/parallel_tutorial.html#Limiting-the-resources))

I guess one of the big bottlenecks is just building the docker image in the first place, so we should maybe consider optimizing that.

**Comment by ericl** [comment]
It would be cool if Jenkins built the pip binary and all the rest of the tests used that.
