### ISSUE TITLE
Better way to obtain LSTM state for agent.compute_action

### ISSUE THREAD

**Issue by efang96** [ray-project/ray#2570]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Ray installed from (source or binary)**:
pip installed from Linux 3.5 wheel
- **Ray version**:
0.5.0
- **Python version**:
3.5.5
- **Exact command to reproduce**:
compute_action(self, observation, state=None, policy_id="default")

### Describe the problem

agent.compute_action requires a 'state' argument which is the hidden state of the RNN. The docstring says it is supposed to return the RNN state along with the action, but currently it only returns the action. There is also no way to obtain the initial state.

### Source code / logs

I am essentially running the following code:
```
lstm_state = [np.zeros(256), np.zeros(256)] # can't get initial state of RNN, so I initialize to 0 based on the shape wanted in the stack trace
action, lstm_state = agent.compute_action(state, lstm_state) # state is the current obs of the environment, this errors out saying 'np.float64 is not iterable', in other words it only returns the action value
```

**Comment by efang96** [comment]
Yes I will work on this tomorrow and get back to you, thanks!

**Comment by efang96** [comment]
Just left a PR, couldn't assign a reviewer for some reason. I just deleted the `[0]` at the end.

**Comment by whikwon** [comment]
Hello, I'm having a similar problem.

I am considering using lstm in ppo. In evaluation time, Is it necessary to continue to forward the previous hidden state forward step by step, right?

**Comment by ericl** [comment]
I just merged the PR fixing this, thanks!
