### ISSUE TITLE
[Docs] Suggestion of adding document

### ISSUE THREAD

**Issue by enori** [ray-project/ray#25715]
### Description

Hi, I recently started studying Ray and learned from the nice document. 
I would be honored to be of service to you and yours in the future.

I found mistakes in the document about [Ray Workflow](https://docs.ray.io/en/latest/workflows/basics.html) and would like to suggest adding an explanation to the documentation. 
May I send PR?

**Comment by pcmoritz** [comment]
Looks like this was fixed in https://github.com/ray-project/ray/pull/25800 :)
