### ISSUE TITLE
[tune] prepopulate using known scores

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2571]
We are using Ray Tune on top of our AutoML pipeline search. What we are trying to achieve is that we first find as suitable ML pipeline. The pipeline has some free hyper-parameters. We then are trying to use Ray Tune to optimize those hyper-parameters.

But in the process of searching for a pipeline, we have to evaluate itself. We do this by scoring a pipeline using default hyper-parameters. Then we determine if we want to continue with full tuning. If we decide to do full tuning, the process starts again and we start evaluating samples of hyper-parameter values. This means that the work which was done during pipeline search is not reused.

So, i wonder, would it be possible to prepopulate Ray Tune with known scores for a set of hyper-parameters? We would then be able to provide for hyper-parameters what was the score for default values and this might then mean that at least one less run has to be done during tuning. If we will do more runs before to evaluate pipeline itself better, this would improve things even more and not duplicate the work.

**Comment by richardliaw** [comment]
Hey Mitar - are you asking specifically for the HyperOptSearch class or for any scheduler, like Hyperband or Median Stopping? Or something else?

Right now the above mentioned classes don't support setting state (ie providing the average reward at a certain iteration), but they can definitely be expanded to doing so.

**Comment by mitar** [comment]
For any tuning algorithm.

**Comment by richardliaw** [comment]
What would be your ideal interface? Like, `scheduler.checkpoint()` and `scheduler.restore()`?

**Comment by richardliaw** [comment]
This is sort of resolved with #5773
