### ISSUE TITLE
Ray is noisy on errors

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2572]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5 (d2ebe4d9a31fbb698ea96535a238e2aa956facb8)
- **Python version**: 3.6.3
- **Exact command to reproduce**:

```
>>> @ray.remote
... def foo():
...   raise Exception("foobar")
... 
>>> f = foo.remote()
>>> Remote function __main__.foo failed with:

Traceback (most recent call last):
  File "<stdin>", line 3, in foo
Exception: foobar


>>> 
>>> ray.get(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 2493, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(b727d6a106a261a6143f362e6035aea9e2724ad1). It was created by remote function __main__.foo which failed with:

Remote function __main__.foo failed with:

Traceback (most recent call last):
  File "<stdin>", line 3, in foo
Exception: foobar
```

As you see, when there is an exception in the remote function, I get some noisy output on my local console. This does not seem to be possible to disable? I do not need that because when I call `ray.get(f)` I do get that information in the exception. This above is just an example, in my real code I am not running this from command line interpreter so this direct messages are not helpful.

**Comment by suquark** [comment]
Ray starts a thread to print errors in SCRIPT_MODE.  You could start ray with SILENT_MODE instead.

**Comment by mitar** [comment]
What are all differences between those two modes? Where do I provide this configuration?

**Comment by robertnishihara** [comment]
`SLIENT_MODE` would works for that as @suquark mentioned. The purpose of `SILENT_MODE` was for tests where we deliberately trigger errors. However, I'd like to get rid of that mode and maybe make it a boolean flag to `ray.init`.

**Comment by mitar** [comment]
@robertnishihara Would you accept PR with this?

So overall, what I would like to achieve is that all logs come to Python logging on the driver. I first thought that this error is noisy because it bypasses logging, but then I realized that Ray is re-configuring logging to always go to stderr as well. Now that I undone that it is pretty neat.

What I would in fact want is that all logging from workers come over in real-time to the driver. See #2573.

**Comment by robertnishihara** [comment]
@mitar, is the thing you want essentially the same as https://github.com/ray-project/ray/issues/2173? If so, I think that would be useful.

You essentially want to redirect stdout/stderr of all of the workers in the cluster to stdout/stderr of the driver?
