### ISSUE TITLE
Document how to access logs (and stdout?) of tasks remotely

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2573]
I am running Ray on cluster using `ray start`. It seems all logs are going to `/tmp/raylogs` which cannot be configured (#2551). But I heard that there is a way to remotely access those logs as well through Redis. Can this be documented somewhere? Is it just logs from workers or all logs? And is it just logs or also stdout?

**Comment by robertnishihara** [comment]
Can try doing `ray.global_state.log_files()` and see if that does what you want?

**Comment by mitar** [comment]
Hm, I do not see worker logs there?

**Comment by mitar** [comment]
I think the issue with `log_files` is that it returns already printed output to the file, and not logger messages. So logger message are useful when they are not yet formatted because then the client (head) can control how logger messages are formatted and not workers. Or, you can store unstructured logger messages to the database.

**Comment by mitar** [comment]
So, my ideal API would be async API where I could subscribe to both stdout/stderr and logging output from all workers. The messages should not just be strings but also have metadata like which worker it is and so on.

In fact, Python logging does most of that already. So what I believe would be the best is that we would redirect all stdout/stderr (and warnings, too) to logging first. And then just provide a way to consolidate those logging messages (so raw logging messages, not the serialized to console ones) together. I have made [a context manager for this already](https://gitlab.com/datadrivendiscovery/d3m/blob/devel/d3m/utils.py#L559).

So, my plan for our system is to capture all stdout/stderr (and warnings) to logging inside a Ray task, and then store all logging to our MongoDB document for that task. The issue I am struggling with is how to do the same for any stdout/stderr, warnings, and logging which happen around running the task itself. I would like to have a way to do something about that. So one option could be to configure each worker this way myself, intercepting everything and doing it myself. Another, probably better for a general case, would be that Ray would be storing that to Redis: so stuff per worker and stuff per each task. And then have an API to or fetch or subscribe to that.

**Comment by mitar** [comment]
OK, I managed to implement this ourselves in parallel with Ray, without having to really change how Ray works. So I use `run_function_on_all_workers` to configure on all workers Python `logging`. I first redirect stdout and stderr to logging. And then I configure a handler for logging to store everything into our MongoDB.

So it is true that this collection of all logs through Redis so that it is accessible on the driver could be something Ray provides, but it seems it is doable to do also in parallel. So from my point of view at the moment this is something for Ray team to discuss. How would they like to manage logs and provide them to users. Is this something which should be part of Ray or not. In some way it is becoming then a cluster management code which maybe is not something Ray should care about. On the other hand, collection of errors and understanding what your tasks are doing remotely seems pretty useful to develop and debug.
