### ISSUE TITLE
[Data] Unintuitive behavior of .map() progress bar

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#25751]
### What happened + What you expected to happen

I'm running a large data processing workload, basically

```
ds = # Dataset with about 10000 file names
ds.map(lambda x: very_expensive_function_with_consitent_timing(x))
```

The behavior of the progress bar is pretty counter intuitive: It basically makes no progress for the first half of the processing (about 40 mins) and then good progress for the rest, slowing down at the end due to stragglers. I suspect what's going on is this: The data is broken up into blocks, and then the blocks are processed on each worker in parallel (and processing each block is *very* expensive). Only after the first block is processes by a worker will there be progress.

This looks like it is when looking at https://github.com/ray-project/ray/blob/fde61a77be59cf57844f7fa1484f8ac6e3a3aced/python/ray/data/_internal/compute.py#L72

Since I have so many data points, I would expect a bit more frequent feedback, not only after basically a lot of the data is already processed. Otherwise it feels like things are hanging at the beginning.

### Versions / Dependencies

Latest master

### Reproduction script

TKTK

### Issue Severity

Low: It annoys or frustrates me.

**Comment by Rosenberg37** [comment]
Any suggestion on this issue?
