### ISSUE TITLE
Support multi-language runtime

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#2576]
Hi Ray team,

We're planning to work on allowing multiple languages to run simultaneously on one Ray cluster. We've summarized a design doc [here](https://docs.google.com/document/d/1x9LNhb5nKfFE_oUVYHw9SAaZ7qosJCdQvjYFe8VVEYY/).

Please let us know if you have any comments. Thank you in advance. 

cc @robertnishihara @istoica @eric-jj @imzhenyu @mylinyuzhi @kingchin1218 @alexbao

**Comment by robertnishihara** [comment]
Thanks @raulchen, I just left some comments. This looks like a really good idea. I agree that Stage 1 should be fairly straightforward, so I'd suggest doing that first as its own PR.

**Comment by istoica** [comment]
@raulchen great feature, and nice document. Left a few comments as well. TL;DR: agree with @robertnishihara and you that we should do Stage 1 first; for Stage 2 I'd consider communication via named objects only as an alternative.

**Comment by raulchen** [comment]
@robertnishihara @istoica Thanks for your comments. I've replied them in the doc.

**Comment by raulchen** [comment]
Since everyone is okay with stage 1. We'll start working on stage 1 first. Changes will come in small PRs.

**Comment by raulchen** [comment]
Hi @robertnishihara and @atumanov, last time we discussed about the 2 options for stage 2: "XLangActor" vs "named actors". 

First, I think both APIs should be useful. And their internal implementations are exactly the same. Basically, we'll need to support creating actor handles and task specs of a different language. The only difference is how to get the handle on the highest level of the API. Thus, I'd like to support both, and allow users to choose whichever way works better in their cases (in the same way as they choose between regular actors and named actors).

Do you have any other concerns? If no, I'll start working on it next week. Thanks.
