### ISSUE TITLE
[Core][State Observability] ray logs errors when node-id is provided 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#25764]
### What happened + What you expected to happen

When I ran `ray logs [file] --node-id` in a real cluster, it seems like it is not working properly.

However, when I used `node-ip`, it worked perfectly.

### Versions / Dependencies

Master

### Reproduction script

run `ray logs [file] --node-id` in a real cluster,

**Comment by rkooo567** [comment]
cc @rickyyx

**Comment by rkooo567** [comment]
Just add unit tests with worker nodes

**Comment by rickyyx** [comment]
I don't think this is a bug anymore? I am not able to reproduce it though.
