### ISSUE TITLE
[RLlib] Doc string code examples should work

### ISSUE THREAD

**Issue by christy** [ray-project/ray#25777]
### Description

I happened to notice a docstring on master that did not work.

Steps to reproduce:

1. Open https://github.com/ray-project/ray/blob/master/rllib/algorithms/ppo/ppo.py#L51 
2. Follow instructions
3. Try running 
`from ray.rllib.algorithms.ppo import PPOConfig
config = PPOConfig().training(gamma=0.9, lr=0.01, kl_coeff=0.3)\
                    .resources(num_gpus=0)\
                    .rollouts(num_workers=4)`

What you get:
`TypeError: rollouts() got an unexpected keyword argument 'num_workers'`

Turns out there are updates to https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm.py which are not included in the ppo.py docstring yet.  

What you expect:
Doc string examples to work.

**Comment by avnishn** [comment]
At bare minimum, we could doctest the imports of docstrings. Still I'm not sure if we can fully do doctest for all of our apis, as we don't want the doctests to have long executions.s

**Comment by kouroshHakha** [comment]
`num_rollout_workers` is the right keyword instead of `num_workers`.

**Comment by zhe-thoughts** [comment]
Thanks for filing the issue @christy ! Could you update the title?

**Comment by zhe-thoughts** [comment]
I think this issue is still valid
