### ISSUE TITLE
[Data] write_parquet / read_parquet changes types

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#25771]
### What happened + What you expected to happen

When I write a dataset with write_parquet and then read it out again with read_parquet, the data type is changing.

This seems like a very annoying issue that should probably be fixed soon :)

### Versions / Dependencies

Ray 3.0.0.dev0

### Reproduction script

```python
import ray
ray.init()

ds = ray.data.from_items(["Hello", "world"])
ds.map(lambda s: len(s)).take(2) # Gives [5, 5]
ds.write_parquet("/tmp/testds")
ds2 = ray.data.read_parquet("/tmp/testds")
ds2.map(lambda s: len(s)).take(2) # Gives [1, 1]
# The underlying type changed from "str" to "ArrowRow"
```

**Comment by clarkzinzow** [comment]
Hmm I think this is expected?

`ds = ray.data.from_items(["Hello", "world"])` creates a simple dataset (list) of strings, while writing it out to Parquet converts it into a single-column table. In other words, your row is going from a single string to a dictionary with a single key-value pair, hence the length differences.

**Comment by clarkzinzow** [comment]
The `ds.write_parquet()` API calls out that it's only supported for datasets that are "convertible to Arrow records": https://docs.ray.io/en/master/data/package-ref.html#ray.data.Dataset.write_parquet

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/25778
