### ISSUE TITLE
ModuleNotFound Error: No module named 'ray.rllib.utils.atari_wrappers'

### ISSUE THREAD

**Issue by vruvora** [ray-project/ray#2578]
Hello Friends: I am receiving the following error `ModuleNotFoundError: No module named 'ray.rllib.utils.atari_wrappers'` when I try to roll out a checkpointed policy in RLLib. Can other people reproduce?  (https://github.com/ray-project/ray/blob/master/doc/source/rllib-training.rst)

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  MacOS Sierra Version 10.12.6
- **Ray installed from (source or binary)**: Binary 
- **Ray version**: 0.5.0
- **Python version**: 3.6.4
- **Exact command to reproduce**: `python ray/python/ray/rllib/rollout.py ~/ray_results/cartpole-es/ES_CartPole-v0_0_2018-08-06_12-08-39ow7iirjw/events.out.tfevents.1533582539.vvoras-MacBook-Pro.local --run ES --env CartPole-v0`

**Comment by aGiant** [comment]
I also had same problem under debian:
root@debian:~/ray/python/ray/rllib# python3 train.py --help
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from ray.test.cluster_utils import Cluster
ImportError: No module named 'ray.test.cluster_utils'

Has anyone solved this?

**Comment by robertnishihara** [comment]
You probably need to install ray from the nightly wheels. See the relevant
section under https://ray.readthedocs.io/en/latest/installation.html.

**Comment by HibaAhmed18** [comment]
Hi, I have the following error:
platform linux -- Python 3.6.9, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /home/user/project/sequential_social_dilemma_games, inifile:
collected 1 item / 1 errors                                                                                                                                                                                

================================================================================================== ERRORS ==================================================================================================
___________________________________________________________________________________ ERROR collecting tests/test_envs.py ____________________________________________________________________________________
ImportError while importing test module '/home/user/project/sequential_social_dilemma_games/tests/test_envs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_envs.py:15: in <module>
    from social_dilemmas.envs.cleanup import CleanupEnv
../social_dilemmas/envs/cleanup.py:5: in <module>
    from social_dilemmas.envs.map_env import MapEnv, ACTIONS
../social_dilemmas/envs/map_env.py:8: in <module>
    from ray.rllib.env import MultiAgentEnv
../../causal/lib/python3.6/site-packages/ray/rllib/__init__.py:11: in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
../../causal/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py:2: in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
../../causal/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py:20: in <module>
    from ray.rllib.evaluation.sampler import AsyncSampler, SyncSampler
../../causal/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py:15: in <module>
    from ray.rllib.evaluation.tf_policy_graph import TFPolicyGraph
../../causal/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py:12: in <module>
    import ray.experimental.tf_utils

E   ModuleNotFoundError: No module named 'ray.experimental.tf_utils'

**Comment by HibaAhmed18** [comment]
Ubuntu 18.04.4 LTS
python :3.6.9 
ray  0.6.1
