### ISSUE TITLE
[RLLib] RNN and DQN issues in the release 1.13

### ISSUE THREAD

**Issue by n30111** [ray-project/ray#25792]
### What happened + What you expected to happen

In the recent release of ray 1.13, RNN (for custom models) is broken for `tf2/tfe` backend due to the following line:
https://github.com/ray-project/ray/blob/releases/1.13.0/rllib/policy/rnn_sequencing.py#L201
The same thing working in the master branch as the above line was removed
https://github.com/ray-project/ray/blob/master/rllib/policy/rnn_sequencing.py#L199

Solution: Either reverting the changes in release 1.13 or use `list(padded_inputs.shape)[1:]`

DQN issue:
In this line below `range(..,)` was used for float inputs, which breaks the code,
https://github.com/ray-project/ray/blob/releases/1.13.0/rllib/agents/dqn/dqn.py#L239
it returns floats
https://github.com/ray-project/ray/blob/e4ce38d001dbbe09cd21c497fedd03d692b2be3e/rllib/agents/dqn/dqn.py#L177

The same thing is fixed in the master branch:
https://github.com/ray-project/ray/blob/master/rllib/algorithms/dqn/dqn.py#L308

### Versions / Dependencies

Ray 1.13.0

### Reproduction script

```
from ray.rllib.agents import dqn


config = dqn.DEFAULT_CONFIG.copy()
config["training_intensity"] = 1
config["rollout_fragment_length"] = 4
config["num_envs_per_worker"] = 1
config["num_workers"] = 1
trainer = dqn.DQNTrainer(config, env="LunarLander-v2")
for i in range(2):
    trainer.train()
    print(i)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
We likely won't backport this fix to 1.13.0. We'll consider adding it to 1.13.1.

In the meantime, you can install the nightly ray build by running `ray install nightly`, which should unblock you for now.

**Comment by n30111** [comment]
Thanks a patch release will work fine.

**Comment by cipollone** [comment]
I see the 1.13.1 is tagged but not released yet. How can I install that version? It's not on master yet, so the [doc](https://docs.ray.io/en/latest/ray-overview/installation.html#installing-from-a-specific-commit) does not apply

**Comment by sven1977** [comment]
Closing this issue, which has been fixed on master. Installing the latest nightly will fix the problem.
