### ISSUE TITLE
[Tune] Reporters do not apply sort_by_metric if metric is passed through tune.run.

### ISSUE THREAD

**Issue by VeronikaPolakova** [ray-project/ray#25802]
### Reporters do not apply `sort_by_metric` if metric is passed through `tune.run`.

I tried to pass `metric` argument to `CLIReporter`, however, I obtained this error:
```
raise ValueError(
                "You passed a `metric` or `mode` argument to `tune.run()`, but "
                "the reporter you are using was already instantiated with their "
                "own `metric` and `mode` parameters. Either remove the arguments "
                "from your reporter or from your call to `tune.run()`"
            )
```
Based on the error message I removed `metric` argument from the reporter and I expected that `sort_by_metric` will be applied on `metric` passed in `tune.run`. However, sorting was not applied and when I searched a bit more I found this piece of code in `TuneReporterBase`:
```
if metric is None or mode is None:
     self._sort_by_metric = False
else:
     self._sort_by_metric = sort_by_metric
 ```
It silently turns `sort_by_metric` boolean to False in the case that `metric` or `mode` is not known directly in the reporter initialization. It doesn't reflect, that `tune.run` passes `metric` and `mode` using `TuneReporterBase.setup` method. 

In my opinion `sort_by_metric` parameter should be changed not in the initialization, but in `TuneReporterBase.set_search_properties` method, which is called from `TuneReporterBase.setup`. Or at least, there should be warning message, that user's wish cannot be fulfilled with the reporter settings.

### Versions / Dependencies

`Ray 1.13.0`

### Reproduction script

```
from ray import tune
from ray.tune.suggest.hebo import HEBOSearch

def objective(config):
    """Objective function to minimize (minimum in 0, 0)"""
    fxy = (config["x"]) ** 2 + (config["y"]) ** 2
    tune.report(fxy=fxy)

def tune_parameters():
    config = {
            "x": tune.randint(-5, 5),
            "y": tune.randint(-5, 5),
        }

    optimizer = HEBOSearch()
    reporter = tune.CLIReporter(
        metric_columns=["fxy"],
        sort_by_metric=True,
    )
    analysis = tune.run(
            objective,
            metric="fxy",
            mode="min",
            search_alg=optimizer,
            num_samples=10,
            config=config,
            progress_reporter=reporter
    )

if __name__ == "__main__":
    tune_parameters()
```

Reporter output:
```
+--------------------+------------+------------------+-----+-----+-------+
| Trial name         | status     | loc              |   x |   y |   fxy |
|--------------------+------------+------------------+-----+-----+-------|
| objective_92cdfe22 | TERMINATED | 172.17.0.2:9234  |  -5 |  -5 |    50 |
| objective_9396a980 | TERMINATED | 172.17.0.2:9440  |   0 |   0 |     0 |
| objective_93981ad6 | TERMINATED | 172.17.0.2:9234  |   2 |  -3 |    13 |
| objective_93ab66ea | TERMINATED | 172.17.0.2:9550  |  -3 |   2 |    13 |
| objective_93acb1c6 | TERMINATED | 172.17.0.2:9234  |  -2 |  -2 |     8 |
| objective_93adfd56 | TERMINATED | 172.17.0.2:9555  |   3 |   3 |    18 |
| objective_93af2fc8 | TERMINATED | 172.17.0.2:9234  |   1 |  -4 |    17 |
| objective_93b0b974 | TERMINATED | 172.17.0.2:9560  |  -4 |   1 |    17 |
| objective_93b1fcc6 | TERMINATED | 172.17.0.2:10213 |   1 |   2 |     5 |
| objective_951f9c9e | TERMINATED | 172.17.0.2:10219 |  -3 |  -2 |    13 |
+--------------------+------------+------------------+-----+-----+-------+
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
Hey @VeronikaPolakova thanks for the clean issue description and repro. Your assessment and suggested solution look right! Would you be interested in making a fix for this?

**Comment by VeronikaPolakova** [comment]
Hey @matthewdeng, thanks for your reaction. I made a try with the PR: https://github.com/ray-project/ray/pull/25853
But I must admit it was quite painful to follow your manual for contributing. 
Firstly I came across this issue with Python3.9: https://github.com/numba/llvmlite/issues/531#issuecomment-757179869.
And secondly, when I switch from Python 3.9 to Python 3.8, I came across this error, when trying to check unittests related to this issue:
```
(ray-venv-38)  (~/ray)  pytest -v -s python/ray/tune/tests/test_progress_reporter.py

ImportError while loading conftest '/home/vpolakova/ray/python/ray/tune/tests/conftest.py'.
python/ray/__init__.py:115: in <module>
    import ray._raylet  # noqa: E402
python/ray/_raylet.pyx:129: in init ray._raylet
    from ray.util.scheduling_strategies import (
python/ray/util/__init__.py:4: in <module>
    from ray._private.services import get_node_ip_address
python/ray/_private/services.py:30: in <module>
    import psutil
python/ray/thirdparty_files/psutil/__init__.py:102: in <module>
    from . import _pslinux as _psplatform
python/ray/thirdparty_files/psutil/_pslinux.py:26: in <module>
    from . import _psutil_linux as cext
E   ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/home/vpolakova/ray/python/ray/thirdparty_files/psutil/__init__.py)
```
Please let me know if I should create another issues or I am just doing something wrong. Thanks

FYI: I will be nonresponsive now for approx. 14 days.

**Comment by matthewdeng** [comment]
@VeronikaPolakova nice! 

Thanks for sharing this honest feedback - I'd love to make sure this experience is made easier for new time contributors. This is a common issue that people have run into and the fix is documented [here](https://docs.ray.io/en/latest/ray-overview/installation.html#troubleshooting). Would it be helpful if this is moved to [this page](https://docs.ray.io/en/latest/ray-contribute/development.html)?

**Comment by VeronikaPolakova** [comment]
Thank you, @matthewdeng, for sharing the troubleshooting link. I would definitely vote for moving it to the suggested page because as a new contributor you will definitely read it. :slightly_smiling_face:

**Comment by matthewdeng** [comment]
Thanks @VeronikaPolakova for the feedback, I've merged a [PR](https://github.com/ray-project/ray/pull/26166) to move it!

**Comment by blacksnail789521** [comment]
For those people who have also encountered this problem with PyTorch and Ray Tune, we need to set both `metric` and `mode`, not only for the scheduler but also for the `CLIReporter`.
