### ISSUE TITLE
[Datasets] [RayDP] RayDP dependency on MLDataset breaks Datasets + RayDP integration test

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25816]
### What happened + What you expected to happen

the ci breaks because 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/20907377/173927816-fd9564f2-67ef-4686-b6b4-ae69b9f45017.png">

when we run this test, we got the error
<img width="922" alt="image" src="https://user-images.githubusercontent.com/20907377/173928077-4cde725d-cb03-4e72-b272-98df90508259.png">

it is because this is decrypted. 
https://github.com/ray-project/ray/tree/ray-1.13.0/python/ray/util/data

the solution is to update raydp? @matthewdeng @iycheng 

### Versions / Dependencies

ray dp

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by JiahaoYao** [comment]
and this one is removed in https://github.com/ray-project/ray/tree/master/python/ray/util/data

**Comment by JiahaoYao** [comment]
by the way, i heard 
> This should all be fixed in RayDP with this commit: https://github.com/oap-project/raydp/commit/fbff273370de898a241a695121a58be4c6b33c83. I’m guessing that the issue is that making MLDataset an optional dependency of RayDP hasn’t been released yet, and our CI isn’t installing latest RayDP master

**Comment by Yard1** [comment]
@clarkzinzow that commit actually still makes it fail for me locally, as the exception raised is an `ImportError` and not a `ModuleNotFoundError`.

**Comment by Yard1** [comment]
@clarkzinzow @clarkzinzow that commit actually still makes it fail for me locally, as the exception raised is an `ImportError` and not a `ModuleNotFoundError`. (also cc @jjyao )

**Comment by Yard1** [comment]
```
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
python/ray/data/tests/test_raydp_dataset.py:3: in <module>
    import raydp
venv/lib/python3.8/site-packages/raydp/__init__.py:18: in <module>
    from raydp.context import init_spark, stop_spark
venv/lib/python3.8/site-packages/raydp/context.py:28: in <module>
    from raydp.spark import SparkCluster
venv/lib/python3.8/site-packages/raydp/spark/__init__.py:18: in <module>
    from .dataset import spark_dataframe_to_ray_dataset, \
venv/lib/python3.8/site-packages/raydp/spark/dataset.py:36: in <module>
    from ray.util.data import MLDataset
E   ImportError: cannot import name 'MLDataset' from 'ray.util.data' (unknown location)
```

**Comment by Yard1** [comment]
Opened a PR here - https://github.com/oap-project/raydp/pull/246

**Comment by JiahaoYao** [comment]
the PR is now merged.
