### ISSUE TITLE
[Core] Changing the OMP_NUM_THREADS with num_cpus

### ISSUE THREAD

**Issue by pratkpranav** [ray-project/ray#25837]
### Description

I was trying to use Ray Core for parallelising my task over nodes in a cluster. However my task were build in C++ and they are optimized by openmp. The problem is that even if I set num_cpus to K, the OMP_NUM_THREADS remain to be 1. So, one feature what we can do is if a user sets num_cpus to K, OMP_NUM_THREADS should be increased to K.

### Use case

People do assume that if we change num_cpus to K, the omp_num_threads to be K too. But it remain to be 1. Could we add something to make sure that when num_cpus to K, the omp_num_threads should also be change to K.

**Comment by richardliaw** [comment]
I'm a big fan of this user request and I think it makes a lot of sense.

cc @scv119 @ericl what are your thoughts? this is a small change and would help with a lot of performance-sensitive ray applications.

**Comment by ericl** [comment]
Yeah, this seems like a no-brainer, similar to how we set CUDA_VISIBLE_DEVICES.

**Comment by jmakov** [comment]
@pratkpranav are you talking about `ray.remote(num_cpus=_K_)`? If that's the case env vars can be set like (and that's documented):
```python
ray.init(
            runtime_env={
                "working_dir": workdir,
                "excludes": ["*.txt", "bin", "doc", "examples", "notebooks"],
                "env_vars": {
                    # force `ray` to not kill a proces on OOM but use SWAP instead
                    "RAY_DISABLE_MEMORY_MONITOR": "1",
                    # force use of all cores on a node (will throw a warning since not an integer, but works)
                    "MKL_NUM_THREADS": "",
                    "OPENBLAS_NUM_THREADS": "",
                    "OMP_NUM_THREADS": ""}
            }, ...
```

**Comment by scv119** [comment]
Ricky maybe you can take it next sprint? should be a very simple change

**Comment by richardliaw** [comment]
Have we fixed this issue btw? This seems to come up very frequently.

**Comment by richardliaw** [comment]
let's not bump it to P0 (just to keep good hygiene, since it's not a real P0), but maybe just take it on the next sprint?

**Comment by ericl** [comment]
Saw another user ran into this for TF training--- should definitely prioritize.

**Comment by rickyyx** [comment]
Will get to it this week.
