### ISSUE TITLE
which concept can change resource dynamicly?

### ISSUE THREAD

**Issue by whitelilis** [ray-project/ray#25850]
In version 0.8.5,  ray.experimental.set_resource()  can dynamic change resource when clientId running, now which concept can do like this?  Cluster ? Actor ? PlaceGroup? Or what?

If some role can, how?
Thanks.

I expect this because I want to map some business concept into it: some TEAM has resource, and they can dynamicly change it. For example, buy new node, decommission node. And there are many TEAMS.

**Comment by whitelilis** [comment]
Does someone have idea ?

**Comment by scv119** [comment]
hi @whitelilis, this api has been deprecated and will be removed in the future releases. So today you can only request resource at actor/task/placement group creation and those resource will be automatically released during the construction of the actor/task/placement group.
