### ISSUE TITLE
[Serve] Replicas with Stable Identifiers

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#25864]
### Description

In Serve, replicas are assigned random identities. This makes is hard to address any of them individually. One can imagine the following use case:
- A group of replicas started with placement_group strict_spread
- One replica failed and killed, Serve controller starts new replica.
- The replica has a new actor name. The old one is no longer addressable. 

One potential solution is to index each replicas being started, and upon termination, give the new replica the smallest unassigned index.

These actor handles can be retried with `ray.get_actor(REPLICA_NAME_INDEX)`.

```
MonitorDeployment.options(num_replicas=10, name="Monitor").deploy()

[ray.get_actor(f"Monitor#{i}" for i in range(10)]
```

**Comment by edoakes** [comment]
@simon-mo I think this could actually simplify the controller logic as well -- each deployment can have `num_replicas` "slots" and each replica occupies a given slot (stable even if its health check fails and it restarts).
