### ISSUE TITLE
[Docs] Search redirects to latest

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#25860]
## Reproduction
1. Go to https://docs.ray.io/en/master/
2. Search for something and hit enter.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/3967392/174125849-8ad676b2-dd68-4615-aef2-90af3ecaddc7.png">
3. End up on latest.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/3967392/174125665-48600064-2e6f-4dbd-a637-12cc3beede9b.png">

## Expectation
Search page matches the version that they're on.

**Comment by sumanthratna** [comment]
just noticed this issue myself, should be easy to fix though: https://github.com/ray-project/ray/blob/0d5131ba37306f20bc420860932c476b3c96e6bd/doc/source/_static/js/docsearch.js#L25

**Comment by maxpumperla** [comment]
needs to be a root relative link

**Comment by sumanthratna** [comment]
for docsearch (autosuggest results), we need to implement this: https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
