### ISSUE TITLE
Ray Job Submission demo failed with "/bin/sh: 1: python script.py: not found"

### ISSUE THREAD

**Issue by biello** [ray-project/ray#25886]
### Description

run as this doc https://docs.ray.io/en/latest/cluster/kubernetes.html#running-ray-programs-with-ray-jobs-submission,  but get failure
```
ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- "python script.py"
Job submission server address: http://127.0.0.1:8265
2022-06-17 17:45:53,800	INFO dashboard_sdk.py:276 -- Uploading package gcs://_ray_pkg_bbcc8ca7e83b4dc0.zip.
2022-06-17 17:45:53,801	INFO packaging.py:414 -- Creating a file package for local directory './'.

-------------------------------------------------------
Job 'raysubmit_atVWB1NFmsaReD8s' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_atVWB1NFmsaReD8s
  Query the status of the job:
    ray job status raysubmit_atVWB1NFmsaReD8s
  Request the job to be stopped:
    ray job stop raysubmit_atVWB1NFmsaReD8s

Tailing logs until the job exits (disable with --no-wait):
/bin/sh: 1: python script.py: not found

---------------------------------------
Job 'raysubmit_atVWB1NFmsaReD8s' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs:
/bin/sh: 1: python script.py: not found
```

**Comment by biello** [comment]
have no clue at all, help needed

**Comment by richardliaw** [comment]
Is there a 'script.py' in your current working directory?

Ray job submission requires a local set of files to be available. (`ls | grep script.py`)

**Comment by valliscooper** [comment]
I can add to this that I have the exactly the same problem. and:

`/home/cooper/ray/tests/test-001$ ls | grep script.py
script.py
`

using at present nighly image and equivalent python 3.7.7 version on linux host. same problem with latest image

**Comment by biello** [comment]
Yes, I do have a 'script.py' in current working directory

**Comment by scv119** [comment]
@DmitriGekhtman let you to triage.

**Comment by DmitriGekhtman** [comment]
Will look into it reproducing the issue.

**Comment by biello** [comment]
@DmitriGekhtman any news?

**Comment by Michaelvll** [comment]
I just met a similar problem. It seems if you remove the `"` around the entrypoint or the `--` before it. The problem will go away.

**Comment by biello** [comment]
@Michaelvll Thank you for your reply，but it seems not the problem.  I tried below but still get the "not found" failure

```
ray job submit "echo test" 
Job submission server address: http://127.0.0.1:8265

-------------------------------------------------------
Job 'raysubmit_KmU2sSNZ55LS8R5m' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_KmU2sSNZ55LS8R5m
  Query the status of the job:
    ray job status raysubmit_KmU2sSNZ55LS8R5m
  Request the job to be stopped:
    ray job stop raysubmit_KmU2sSNZ55LS8R5m

Tailing logs until the job exits (disable with --no-wait):
/bin/sh: 1: echo test: not found

---------------------------------------
Job 'raysubmit_KmU2sSNZ55LS8R5m' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs:
/bin/sh: 1: echo test: not found


```

**Comment by Michaelvll** [comment]
@biello Oops, sorry. Just tried again. Seems only `ray job submit -- echo test` works. Updated the previous comment. : )

**Comment by DmitriGekhtman** [comment]
Thanks for your patience https://docs.ray.io/en/master/cluster/kubernetes.html#running-ray-programs-with-ray-jobs-submission

We have fixed this in the master docs 
and added a warning
https://github.com/ray-project/ray/pull/25519

It should be `ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- python script.py` without quotes.

I wonder if for certain doc fixes, we should pick directly into "latest" docs rather than waiting for the next release.

**Comment by biello** [comment]
oh, it works! 

`ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- python script.py` works too!

Thank you so much, you saved my day!
