### ISSUE TITLE
[Ray feature request] enables to kill / stop worker on the dashboard 

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#25891]
### Description

![image](https://user-images.githubusercontent.com/20907377/174344888-9eb1a9e5-2ded-44fd-b232-5162dcf986ef.png)

is it possible to add the button to kill one ray worker on the dashboard? 

### Use case

1. ppl seem to prefer using the dashboard to monitor their experiments and provide `terminate` button would be convenient to them. (without going back to terminal and type `kill -9 $PID`.)
2. if the worker is idle, i would like to clean the dashboard instead of leaving the workers there

**Comment by scv119** [comment]
@alanwguo let you to triage.
