### ISSUE TITLE
Cannot serialize with Ray what I can with Plasma

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2589]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5 (d2ebe4d9a31fbb698ea96535a238e2aa956facb8)
- **Python version**: 3.6.3
- **Exact command to reproduce**:

I have a custom value I have registered custom serializers with pyarrow:

```
from pyarrow import lib as pyarrow_lib

pyarrow_lib._default_serialization_context.register_type(
    List, 'custom_list',
    custom_serializer=list_serializer,
    custom_deserializer=list_deserializer,
)
```

This makes it work well with regular plasma client. But when I try to store it with `ray.put`, I get warnings and error:

```
WARNING: Serializing objects of type <class 'custom_list'> by expanding them as dictionaries of their fields. This behavior may be incorrect in some cases.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 2513, in put
    worker.put_object(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 395, in put_object
    self.store_and_register(object_id, value)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 330, in store_and_register
    self.task_driver_id))
  File "/usr/local/lib/python3.6/dist-packages/ray/utils.py", line 324, in _wrapper
    return orig_attr(*args, **kwargs)
  File "pyarrow/_plasma.pyx", line 397, in pyarrow._plasma.PlasmaClient.put
  File "pyarrow/serialization.pxi", line 338, in pyarrow.lib.serialize
  File "pyarrow/error.pxi", line 89, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: This object exceeds the maximum recursion depth. It may contain itself recursively.
```

So it seems Ray ignores custom serializers one registers with pyarrow. I think Ray should automatically inherit those serializers from pyarrow.

Or at least `ray.register_custom_serializer` should be documented. :-)

**Comment by robertnishihara** [comment]
There's some documentation at http://ray.readthedocs.io/en/latest/api.html#ray.register_custom_serializer.

That said, I do want to rework the serialization to make it more robust and handle these kinds of situations automatically.

**Comment by mitar** [comment]
Oh, I missed that. I will then close this issue.

**Comment by mingfeisun** [comment]
> There's some documentation at http://ray.readthedocs.io/en/latest/api.html#ray.register_custom_serializer.
> 
> That said, I do want to rework the serialization to make it more robust and handle these kinds of situations automatically.

The link expired. Would you like to provide a new link to help explain?

**Comment by robertnishihara** [comment]
https://docs.ray.io/en/master/package-ref.html#ray.register_custom_serializer
