### ISSUE TITLE
Object hash mismatch for Python dictionaries

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#259]
Python dictionaries (even when the insertion order was the same) do not have a deterministic key ordering. This means that we can get an object hash mismatch for dictionaries, even though the key-value pairs are the same.

Better code example to come, but this can be seen on this [branch](https://github.com/stephanie-wang/ray/tree/put-reconstruction). Run the following command on python (v3.5):
`python test/stress_tests.py ReconstructionTests.testPut`

**Comment by robertnishihara** [comment]
That's really interesting/unexpected. See this issue http://stackoverflow.com/questions/14956313/dictionary-ordering-non-deterministic-in-python3.

Looks like dictionaries and sets will be the most common place where this comes up.

**Comment by robertnishihara** [comment]
We stopped recording the hashes I believe, so haven't run into this recently.
