### ISSUE TITLE
[docs] RLLib docs still show production RL conference notices even though it was months ago

### ISSUE THREAD

**Issue by waleedkadous** [ray-project/ray#25917]
### What happened + What you expected to happen

Go to: https://docs.ray.io/en/latest/rllib/rllib-training.html

At the bottom of the document, you will find this notice. That event was (as of today) almost 3 months ago.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/2716496/174456278-52954859-b1c4-47a8-a66e-f4ddd52c140c.png">

### Versions / Dependencies

N/A

### Reproduction script

N/A

**Comment by ArturNiederfahrenhorst** [comment]
See https://github.com/ray-project/ray/issues/25917
