### ISSUE TITLE
Get the number of Actors that are still running

### ISSUE THREAD

**Issue by zhanglirong1999** [ray-project/ray#25915]
### Description

When running distributed with ray, other workers will automatically end, but the worker as a server will not, and whether there is an API that can know that how many actors left. Thus I am able to use `ray.kill` to kill the last actor

### Use case

```python   
 if task_type == 'ps':
        server.join()
    elif task_type == 'worker':
        tf_config = {
            'ps_hosts': ps_hosts,
            'worker_hosts': worker_hosts,
            'type': task_type,
            'index': task_index,
            'is_chief': is_chief
        }
        tf_device = tf.device(
            tf.train.replica_device_setter(
                worker_device='/job:worker/task:%d' % task_index,
                cluster=cluster))
        return tf_config, server, tf_device
```

I want to kill the server actor,It uses `server.join()` to listen

**Comment by scv119** [comment]
@rkooo567 is it part of Ray observability plan?

**Comment by rkooo567** [comment]
I believe you can try https://docs.ray.io/en/master/ray-observability/state/state-api.html. IF you have any feedback to the API, plz lmk!
