### ISSUE TITLE
[Workflows] pyarrow.fs is not found 

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#25919]
### What happened + What you expected to happen

I'm trying to create a simple virtual actor (eventually looking to create and call virtual actors from within serve deployements).
I am getting that `pyarrow.fs` (which is lazily imported in `storage.py`) is not found. 

```bash
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.9/site-packages/ray/internal/storage.py", line 49, in get_filesystem
    return _get_filesystem_internal()
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.9/site-packages/ray/internal/storage.py", line 346, in _get_filesystem_internal
    _init_filesystem()
  File "/home/albert/miniconda3/envs/tha_py/lib/python3.9/site-packages/ray/internal/storage.py", line 361, in _init_filesystem
    import pyarrow.fs
ModuleNotFoundError: No module named 'pyarrow.fs'; 'pyarrow' is not a package
```

### Versions / Dependencies

ray, version 1.13.0

pyarrow 6.0.1

python 3.9

### Reproduction script

Start ray
```bash
ray start --init
```
Try to create a virtual actor:
```python
import ray
from ray import workflow

@workflow.virtual_actor
class TestWorkflow:
    def __init__(self, data):
        self.data = data

    def get(self):
        return self.data

if __name__ == '__main__':
    # pyarrow 6.0.1 is installed, so this statement works:
    import pyarrow
    
    ray.init(address='auto', storage="file:///tmp/ray/workflow_data")
    workflow.init()

    workflow_session = TestWorkflow.get_or_create('abc', 1.)
    assert 1. == workflow_session.get().run()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by tupui** [comment]
Hi @Joshuaalbert, thank you for reporting. Does `import pyarrow.fs` work in your env?

**Comment by Joshuaalbert** [comment]
`import pyarrow.fs` does not work (if I replace in the above script, where  `import pyarrow` works).

**Comment by Joshuaalbert** [comment]
Woah, silly mistake here! The script __name__ for debugging was called `pyarrow.py` and so it was importing itself and then obviously failed.
