### ISSUE TITLE
[Ray Core] Lack of documentation on ray head node

### ISSUE THREAD

**Issue by raceychan** [ray-project/ray#25958]
### Description

as i read through the documentation with some extra searches, there are few questions about the head node remained unaddressed in my mind. I will list some specific questions below, particularly the ones that I think would probably be helpful for others if documented.

1. is the ray head node scalable? if say we are in a k8s context, how much resources can a head node utilize? in the offical exmaple_full.yaml (https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kubernetes/example-full.yaml) i found that the head node is assigned with 1 cpu, is it true that a head node can only utilize one cpu? i really could not find much information about this.
2. is the scalability of ray limited by the head node, if so, how sharp is the curve? for a head node with one cpu, how many actors are expected to performant well?
3. is it possible to configure the resource of head node when run in the command line my local machine, with command like: 
 ray start --head?

**Comment by raceychan** [comment]
is this topic forbidden

**Comment by scv119** [comment]
hey @raceychan thanks for your interest in Ray, any question is welcome!
> is the ray head node scalable? if say we are in a k8s context, how much resources can a head node utilize? in the offical exmaple_full.yaml (https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kubernetes/example-full.yaml) i found that the head node is assigned with 1 cpu, is it true that a head node can only utilize one cpu? i really could not find much information about this.

The head node actually runs multiple critical components for Ray including GCS, dashboard, API Server. That's said depending on your cluster size it requires more resources (i.e. multiple cpus)

> is the scalability of ray limited by the head node, if so, how sharp is the curve? for a head node with one cpu, how many actors are expected to performant well?

Today we don't have curve but rather scalability envelop. https://github.com/ray-project/ray/blob/master/release/benchmarks/README.md has the information for the scalability you can expect from a 64 core head nodes.

> is it possible to configure the resource of head node when run in the command line my local machine, with command like:
> ray start --head?

The head node will creates multiple processes, and by default those processes could utilize all the (CPU/Memory) resources on that node.

**Comment by raceychan** [comment]
> hey @raceychan thanks for your interest in Ray, any question is welcome!
> 
> > is the ray head node scalable? if say we are in a k8s context, how much resources can a head node utilize? in the offical exmaple_full.yaml (https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kubernetes/example-full.yaml) i found that the head node is assigned with 1 cpu, is it true that a head node can only utilize one cpu? i really could not find much information about this.
> 
> The head node actually runs multiple critical components for Ray including GCS, dashboard, API Server. That's said depending on your cluster size it requires more resources (i.e. multiple cpus)
> 
> > is the scalability of ray limited by the head node, if so, how sharp is the curve? for a head node with one cpu, how many actors are expected to performant well?
> 
> Today we don't have curve but rather scalability envelop. https://github.com/ray-project/ray/blob/master/release/benchmarks/README.md has the information for the scalability you can expect from a 64 core head nodes.
> 
> > is it possible to configure the resource of head node when run in the command line my local machine, with command like:
> > ray start --head?
> 
> The head node will creates multiple processes, and by default those processes could utilize all the (CPU/Memory) resources on that node.

Tons of thanks to you, your reply really helps! 
In the last paragraph you mentioned that " by default those processes could utilize all the (CPU/Memory) resources on that node.", does that mean that if I assign a machine with 32 cpus and 64 gb memory as the head node, then the head node would utilize all of those resources? that sounds awesome! but is the same thing true for k8s? say if im about to deploy a static ray cluster on k8s, I am supposed to deploy both a service and a deployment for the head node, but then which really influence the performance of my head node? is there any example of best practice on that?

**Comment by DmitriGekhtman** [comment]
See also https://github.com/ray-project/ray/issues/25410
