### ISSUE TITLE
Ray needs pyarrow as proper install dependency for using Ray workflows

### ISSUE THREAD

**Issue by skrawcz** [ray-project/ray#25952]
This line of code will be hit and break if you don't have pyarrow installed and are using Ray workflows.

https://github.com/ray-project/ray/blob/c604bc23c7fa9c973d0900d721b83a1d3c30eebc/python/ray/internal/storage.py#L361

Stacktrace:
```
venv/lib/python3.7/site-packages/ray/workflow/api.py:57: in init
    ray.init(storage="file:///tmp/ray/workflow_data")
venv/lib/python3.7/site-packages/ray/_private/client_mode_hook.py:105: in wrapper
    return func(*args, **kwargs)
venv/lib/python3.7/site-packages/ray/worker.py:1040: in init
    head=True, shutdown_at_exit=False, spawn_reaper=True, ray_params=ray_params
venv/lib/python3.7/site-packages/ray/node.py:204: in __init__
    storage._init_storage(ray_params.storage, is_head=head)
venv/lib/python3.7/site-packages/ray/internal/storage.py:336: in _init_storage
    _init_filesystem(create_valid_file=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

create_valid_file = True, check_valid_file = True

    def _init_filesystem(create_valid_file: bool = False, check_valid_file: bool = True):
        """Fully initialize the filesystem at the given storage URI."""
        global _filesystem, _storage_prefix, _storage_uri
        assert _filesystem is None, "Init can only be called once."
    
        if not _storage_uri:
            raise RuntimeError(
                "No storage URI has been configured for the cluster. "
                "Specify a storage URI via `ray.init(storage=<uri>)`"
            )
    
>       import pyarrow.fs
E       ModuleNotFoundError: No module named 'pyarrow'

venv/lib/python3.7/site-packages/ray/internal/storage.py:361: ModuleNotFoundError
```

By default `pip install ray` does not install pyarrow - it should because it's a required dependency for Ray workflows.

**Comment by tupui** [comment]
Hi @skrawcz, thank you for reporting. I would think this is expected since you are calling `ray.workflow` which is not a core component. The `pyarrow` dependency is available as an extra with `pip install ray[data]`.

**Comment by skrawcz** [comment]
> Hi @skrawcz, thank you for reporting. I would think this is expected since you are calling `ray.workflow` which is not a core component. The `pyarrow` dependency is available as an extra with `pip install "ray[data]"`.
> 
> I would say that it might just needs some documentation on how to properly install ray to use the module. Other modules like `tune` have a installation instructions and refer to an extra with the name of the module. But as the doc suggests, `wokflow` is still in beta.

Yeah -- perhaps updating the docs would suffice then. Since I went to look at them and didn't see a special install requirement for it.
