### ISSUE TITLE
[<Ray component: java>] Detached Java Actor Not working

### ISSUE THREAD

**Issue by tomsunelite** [ray-project/ray#25955]
### What happened + What you expected to happen

detached java actor is not working(actor will be dead after driver exit) when creating a java actor with ActorLifetime.DETACHED option。 seems that the issue is caused by this code snippet in io_ray_runtime_task_NativeTaskSubmitter.cc

    if (java_actor_lifetime != nullptr) {
      is_detached = std::make_optional<bool>(
           env->IsSameObject(java_actor_lifetime, STATUS_DETACHED));
    }
and if i change these code to compare the ordinal of ActorLifetime object, the detached java actor will work correctly.

    if (java_actor_lifetime != nullptr) {
      // is_detached = std::make_optional<bool>(
      //     env->IsSameObject(java_actor_lifetime, STATUS_DETACHED));
      int lifetimeOrdinal = env->CallIntMethod(java_actor_lifetime, java_actor_lifetime_ordinal);
      int lifetimeDetachedOrdinal = env->CallIntMethod(STATUS_DETACHED, java_actor_lifetime_ordinal);
      is_detached = lifetimeOrdinal == lifetimeDetachedOrdinal;
    }

### Versions / Dependencies

ray 1.12.1 
MacOS 12

### Reproduction script

```code
public static void main(String[] args) {
        System.setProperty("ray.job.namespace", "test_namespace");
        Ray.init();
        ActorHandle<ConcurrentActor> myActor = Ray.actor(ConcurrentActor::new)
                    .setLifetime(ActorLifetime.DETACHED)
                .setName("ActorFromMain")
                .remote();
        System.out.println(myActor.task(ConcurrentActor::f1).remote().get());
    }

class ConcurrentActor {
    public long f1() {
        return Thread.currentThread().getId();
    }

    public long f2() {
        return Thread.currentThread().getId();
    }

    public long f3(int a, int b) {
        return Thread.currentThread().getId();
    }

    public long f4() {
        return Thread.currentThread().getId();
    }

    public long f5() {
        return Thread.currentThread().getId();
    }
}
```

**Comment by jovany-wang** [comment]
Sorry I can't get the reproduced script. We have the unit test to cover it, see https://github.com/ray-project/ray/blob/master/java/test/src/main/java/io/ray/test/ActorLifetimeTest.java#L21

or could you tell more details on how I can reproduce it.

**Comment by jovany-wang** [comment]
I reproduced it on my mac. It's weird that we haven't catch it in CI.

**Comment by jovany-wang** [comment]
Could you help to fix it in ordinal? And I'll investigate the CI issue later.

**Comment by tomsunelite** [comment]
please review the pr, thx
