### ISSUE TITLE
[<Ray component: Core] Advanced documentation still references cython_main and other Cython examples 

### ISSUE THREAD

**Issue by tginart** [ray-project/ray#25953]
### Description

The Cython examples have been removed since: https://github.com/ray-project/ray/commit/7f1bacc7dc9caf6d0ec042e39499bbf1d9a7d065

However, the docs (https://github.com/ray-project/ray/blob/c8f207f746e49c2beff7c5f8dfac877e5c577ba6/doc/source/ray-core/advanced.rst) still reference the Cython examples even as they've been removed. 

With that being said, does Ray still plan to support Cython developers in the long run?

**Comment by scv119** [comment]
nice catch. we should remove the doc.
