### ISSUE TITLE
[Serve] Serve CLI commands fail if address has a trailing slash 

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#25969]
### What happened + What you expected to happen

The Serve CLI commands fail when specifying an address with a trailing slash (e.g. `http://localhost:8265/` fails when `http://localhost:8265` succeeds). The trailing slash should be dropped.

### Versions / Dependencies

Ray on the latest master.

### Reproduction script

In terminal, run:

1. `ray start --head`
2. `serve status`
```console
Traceback (most recent call last):
  File "/Users/shrekris/miniforge3/envs/ae/bin/serve", line 33, in <module>
    sys.exit(load_entry_point('ray', 'console_scripts', 'serve')())
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shrekris/Desktop/ray/python/ray/serve/scripts.py", line 320, in status
    app_status = ServeSubmissionClient(address).get_status()
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/serve/sdk.py", line 40, in __init__
    self._check_connection_and_version(
  File "/Users/shrekris/Desktop/ray/python/ray/dashboard/modules/dashboard_sdk.py", line 209, in _check_connection_and_version
    raise RuntimeError(version_error_message)
RuntimeError: Serve CLI is not supported on the Ray cluster. Please ensure the cluster is running Ray 1.12 or higher.
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by millermuttu** [comment]
i am using ray 2.7.1 and this issue still persist.

i am trying to execute serve deploy xyz.yaml inside the kubernetes cluster which uses ray 2.7.1 ray image only 

and still get RuntimeError: Serve CLI is not supported on the Ray cluster. Please ensure the cluster is running Ray 1.12 or higher.
this error.

**Comment by shrekris-anyscale** [comment]
Thanks for posting @millermuttu. I tried to reproduce the issue by installing Ray 2.7.1 with Python 3.9 on a fresh conda environment on my laptop. All the following commands worked successfully for me:

```
ray start --head
serve deploy config.yaml
serve deploy config.yaml -a http://localhost:52365
serve deploy config.yaml -a http://localhost:52365/
serve status
serve status -a http://localhost:52365
serve status -a http://localhost:52365/
```

What do you get when you run `curl http://localhost:52365/api/ray/version` inside your Kubernetes cluster? For reference, on my laptop I get:

```
% curl http://localhost:52365/api/ray/version
{"version": "4", "ray_version": "2.7.1", "ray_commit": "9f07c12615958c3af3760604f6dcacc4b3758a47"}
```

Could you also run `echo $RAY_AGENT_ADDRESS` and post the value? For reference, when I set the `RAY_AGENT_ADDRESS` on my laptop to either `http://localhost:52365/` or `http://localhost:52365`, `serve status` still succeeds. As a sanity check, I tried setting it to the dashboard head address (`http://localhost:8265`), and as expected, `serve status` fails since the env var is expecting the agent address.

**Comment by shrekris-anyscale** [comment]
Adding a trailing slash to the version address does fail on my laptop, but I'm not sure if it's related:

```
% curl http://localhost:52365/api/ray/version/
404: Not Found
```
