### ISSUE TITLE
[Azure cluster launcher] Deletion takes ~10 minutes without stopped node caching, fast with stopped node caching

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#25971]
### What happened + What you expected to happen

This came up in a [Discuss post](https://discuss.ray.io/t/question-about-the-cache-stopped-nodes-option-in-the-cluster-yaml-file/6242?u=cade). The user highlights confusing, undesired behavior where the Azure cluster launcher waits for virtual machines to completely terminate (~10 minutes) when `cache_stopped_nodes=False`. The expected behavior is that node removal is fast, as is the behavior when `cache_stopped_nodes=True`. "Fast" here means `idle_timeout_minutes`.

The fix is to remove this blocking [`wait`](https://github.com/ray-project/ray/blob/fa32cb7c401f5afa9a7cfb160c22aa62578af1ee/python/ray/autoscaler/_private/_azure/node_provider.py#L309), so that the node provider makes the request to terminate the virtual machine, but does not block waiting for termination.

More context:
* https://discuss.ray.io/t/question-about-the-cache-stopped-nodes-option-in-the-cluster-yaml-file/6242/10?u=cade

### Versions / Dependencies

I presume the user tested on latest released Ray, but not sure. The root cause [is present in the 1.13 branch](https://github.com/ray-project/ray/blob/releases/1.13.0/python/ray/autoscaler/_private/_azure/node_provider.py#L309).

### Reproduction script

Use [example-full.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/azure/example-full.yaml) with [`cache_stopped_nodes=True|False`](https://github.com/ray-project/ray/blob/c3ac6fcf3fcc8cfe6930c9a820add0e187bff579/doc/source/cluster/config.rst#provider) and `idle_timeout_minutes=1`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by zhe-thoughts** [comment]
(Context: I’m doing a round of cleanup of waiting-for-triage issues)

I'm marking as P2 since on docs we have clarified Azure cluster launcher is community maintained. cc @AmeerHajAli to put in Infra backlog
