### ISSUE TITLE
Ray Python: cannot setup-env

### ISSUE THREAD

**Issue by brucez-anyscale** [ray-project/ray#26017]
### What happened + What you expected to happen

I follow this doc https://docs.ray.io/en/master/ray-contribute/development.html#building-ray-python-only to build ray from source.

However when I do `python python/ray/setup-dev.py`.
I find out that in the latest master, there is no more node.py and ray_constants.py.

### Versions / Dependencies

Latest Master

### Reproduction script

Run `python python/ray/setup-dev.py`

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
@ericl @pcmoritz  i believe this is related to the latest move to _private change?
