### ISSUE TITLE
[Ray operator] Reduce log level of Ray operator logs

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#26027]
### What happened + What you expected to happen

The logs produced by the Ray K8s operator (the one maintained in the Ray repo) are extremely verbose.
Fix that. (The fix is simple.)

### Versions / Dependencies

Ray master.

### Reproduction script

Look at operator logs.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scottsun94** [comment]
@DmitriGekhtman Are we still planning to improve in consideration of KubeRay?

**Comment by DmitriGekhtman** [comment]
Nope.
