### ISSUE TITLE
[C++ API] example run failed when build Ray from source

### ISSUE THREAD

**Issue by SongGuyang** [ray-project/ray#26031]
Currently, when we build Ray from source, the cpp example will run failed:
```
cd cpp/example && sh run.sh
```

The error message:
```
*** SIGSEGV received at time=1655979316 on cpu 22 ***
PC: @           0x4056ae  (unknown)  __gnu_cxx::__exchange_and_add()
    @     0x7f777b2bf670  (unknown)  (unknown)
    @           0x405745         32  __gnu_cxx::__exchange_and_add_dispatch()
    @           0x40c939         32  std::_Sp_counted_base<>::_M_release()
    @           0x40a8e1         32  std::__shared_count<>::~__shared_count()
    @           0x408f3a         32  std::__shared_ptr<>::~__shared_ptr()
    @           0x408f56         32  std::shared_ptr<>::~shared_ptr()
    @           0x40b22e        128  ray::Put<>()
    @           0x404c00        448  main
    @     0x7f777b2abb15  (unknown)  __libc_start_main
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325: *** SIGSEGV received at time=1655979316 on cpu 22 ***
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325: PC: @           0x4056ae  (unknown)  __gnu_cxx::__exchange_and_add()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @     0x7f777b2bf670  (unknown)  (unknown)
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x405745         32  __gnu_cxx::__exchange_and_add_dispatch()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x40c939         32  std::_Sp_counted_base<>::_M_release()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x40a8e1         32  std::__shared_count<>::~__shared_count()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x408f3a         32  std::__shared_ptr<>::~__shared_ptr()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x408f56         32  std::shared_ptr<>::~shared_ptr()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x40b22e        128  ray::Put<>()
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @           0x404c00        448  main
[2022-06-23 18:15:16,093 E 226366 226366] logging.cc:325:     @     0x7f777b2abb15  (unknown)  __libc_start_main
run.sh: line 10: 226366 Segmentation fault      LD_LIBRARY_PATH="$ROOT_DIR/thirdparty/lib" "${ROOT_DIR}"/bazel-bin/example
```

It comes up because we set the build option `build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` in the file `cpp/example/.bazelrc`. If you remove this build option, it works.

We set `D_GLIBCXX_USE_CXX11_ABI=0` because the released wheels of Ray are compiled with ABI=0 and we should guarantee the example works with the released wheels. 

We should find a way to support the both scenes(run example with source and released wheels).

The related issue https://discuss.ray.io/t/cpp-example-doesnt-work/5807 and https://github.com/ray-project/ray/issues/24566

**Comment by EnjianGong** [comment]
![image](https://user-images.githubusercontent.com/112852312/208090453-0ccce5dd-34f6-4115-a78b-75271c9c86f0.png)
I have a cmake project about MIP, so I need to use ray according to cmake, but after transforming it into cmake according to bazel, an exception as shown in the figure is thrown

**Comment by phetdam** [comment]
> but after transforming it into cmake according to bazel

I had the same issue as you until I realized I was *not* actually following the `BUILD.bazel`. For convenience in the exposition, let's define the following CMake `IMPORTED` shared library for `libray_api.so`:

```cmake
# IMPORTED shared library for libray_api
# this ties .so path, compile definitions, include dirs together in one place
add_library(ray::ray_api SHARED IMPORTED)
# set library location
set_target_properties(
    ray::ray_api PROPERTIES
    IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lib/libray_api.so
)
# set INTERFACE include directories
target_include_directories(
    ray::ray_api INTERFACE
    ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include
)
# set glibc ABI requirement (only do this for ray-cpp from binary wheels)
target_compile_definitions(ray::ray_api INTERFACE _GLIBCXX_USE_CXX11_ABI=0)
```

With this `ray::ray_api` target defined in your `CMakeLists.txt`, can you try adding the following:

```cmake
# create shared library that exports the Plus, Counter symbols
# note: SHARED works too, but there aren't any headers to use here.
# MODULE is more accurate since this .so is loaded with dlopen()
add_library(example_lib MODULE example.cc)
target_link_libraries(example_lib PRIVATE ray::ray_api)
```

This ensures that `example.cc` is built into a shared object that Ray will scan for exported symbols during runtime. As noted in the logging output of `example`, the current directory will by default be checked for dynamic libraries, so Ray will find the `libexample_lib.so` that CMake will build and be able to correctly run the `ray::Task(Plus)` as we expect:

```
<logging messages>

put_get_result = 100
task_result = 3
actor_task_result = 3
actor_task_result2 = 6
Stopped all 6 Ray processes.
```

You might think this is a bit redundant, which is true; there should be a way to make a [shared library executable](https://unix.stackexchange.com/a/223411/539461), but I haven't yet gotten that to work in CMake. I also think that in a production setting, you would probably have the `RAY_REMOTE` functions in a separate shared library anyways, so we don't have to worry about that particular use case much.
