### ISSUE TITLE
Ray tune tune.run keep_checkpoints_num=0 keeps all checkpoints

### ISSUE THREAD

**Issue by stephano41** [ray-project/ray#26038]
### What happened + What you expected to happen

```
analysis = tune.run(trainable,
                                config=config,
                                keep_checkpoints_num=0)
```
expected to happen: no checkpoints kept in output directory

what actually happened: All checkpoints were kept

### Versions / Dependencies

Ray 1.12.1
Python 3.8
Pytorch 1.11.0

### Reproduction script

```
analysis = tune.run(trainable,
                                config=config,
                                keep_checkpoints_num=0)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
Hey @stephano41, thanks for reporting this. Could you provide a simple repro of the issue?

**Comment by stephano41** [comment]
Hi here is a simple reproducible script adapted from the get started page and the pytorch examples for getting checkpointing to work:
```
from ray import tune
import ray

import torch
from pathlib import Path


# 1. Define an objective function.
def objective(config, checkpoint_dir=None):
    if checkpoint_dir:
        checkpoint = torch.load(checkpoint_dir)
        score = checkpoint['score']
        tune.report(score=score)
    else:
        for epoch in range(0, 10):
            score = config["a"] ** 2 + config["b"]

            with tune.checkpoint_dir(epoch) as checkpoint_dir:
                torch.save({'score': score}, Path(checkpoint_dir) / "model_checkpoint.pth")
                tune.report(score=score)


def main():
    # 2. Define a search space.
    search_space = {
        "a": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
        "b": tune.choice([1, 2, 3]),
    }

    # 3. Start a Tune run and print the best result.
    analysis = tune.run(objective, config=search_space, local_dir="./outputs/", keep_checkpoints_num=0, num_samples=50,
                        checkpoint_score_attr='score'
                        )
    print(analysis.get_best_config(metric="score", mode="min"))


if __name__ == '__main__':
    # pylint: disable=no-value-for-parameter
    ray.init()

    main()

```
I wonder if there is a function to call inside the objective function to check whether or not it should checkpoint, before saving things

**Comment by stephano41** [comment]
@matthewdeng any updates on this?

**Comment by matthewdeng** [comment]
Hi @stephano41, apologies for the delayed response here. There's recently been a refactoring done around checkpointing which should address this. Specifically, it should disallow `keep_checkpoints_num` from being set to 0:

```
RuntimeError: If checkpointing is enabled, Ray Tune requires `keep_checkpoints_num` to be None or a number greater than 0
```

Furthermore, it should address a bug where previously, an extra checkpoint was being stored (e.g. if you set `keep_checkpoints_num`  to 1 in your repro script, it would actually keep 2).

You can download a nightly wheel which contains this change by following the instructions [here](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies), or by running the `ray install-nightly` CLI command.

**Comment by stephano41** [comment]
Thank you, I'll check it out!
