### ISSUE TITLE
Timezone aware datetime objects lose timezone information through Ray

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2605]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5 (d2ebe4d9a31fbb698ea96535a238e2aa956facb8)
- **Python version**: 3.6.3
- **Exact command to reproduce**:

```python
import ray
ray.init()

import datetime
now = datetime.datetime.now(datetime.timezone.utc)

object_id = ray.put(now)
now2 = ray.get(object_id)

# now2 == datetime.datetime(2018, 8, 8, 13, 45, 42, 37048)
# now == datetime.datetime(2018, 8, 8, 13, 45, 42, 37048, tzinfo=datetime.timezone.utc)
```

**Comment by mitar** [comment]
I tried `ray.register_custom_serializer(datetime.datetime, class_id='datetime.datetime', use_pickle=True)` but it does not help.

**Comment by suquark** [comment]
@mitar It supposed to be a bug in `pyarrow`.

Here are the related codes:
https://github.com/apache/arrow/blob/aedba2cd81ce5703971fcc36667a817a0ed5b861/cpp/src/arrow/python/python_to_arrow.cc#L537-L551

`pyarrow` views `datetime.datetime` as a basic and terminal type, so it will not call any custom serializers. And it just saves the time part of `datetime.datetime` as a int64 type so the timezone info will lost.

They haven't implemented any utils for saving timezone:

https://github.com/apache/arrow/blob/30158ad5a068208237f3c30e6c9eb60454bae402/cpp/src/arrow/python/util/datetime.h

**Comment by mitar** [comment]
Any workaround here? Care to make a PR to fix this in pyarrow? Can this be somehow fixed in Ray without having to wait for pyarrow to fix this?

**Comment by suquark** [comment]
There are no direct workarounds.  A pre-serialization mechanism needed to be implemented before it is serialized by pyarrow. Coincidentally, I am refactoring the serialization part of the Ray, adding this functionality should be easy (See https://github.com/ray-project/ray/pull/2599).

I will make a PR to fix this in pyarrow later.

**Comment by mitar** [comment]
Any updates here?

**Comment by mitar** [comment]
Is this related to: https://issues.apache.org/jira/browse/ARROW-1435

**Comment by edoakes** [comment]
We're now using pickle5 for serialization, so this should be addressed. Could you try on latest ray?

**Comment by mitar** [comment]
Does pickle5 support efficient serialization of Pandas DataFrames?

**Comment by NumberChiffre** [comment]
I tried with datetime to generate dates and have the same issue addressed in this thread and https://issues.apache.org/jira/browse/ARROW-1435

This happens when a list of datetime objects get passed into ray.get. As stated in the description, pytz.utc.localize will solve the issue. I'm wondering if there is going to be any fix for this?
