### ISSUE TITLE
[Ray component: TPU autoscaler] not ip shows in the `ray status`

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#26066]
### What happened + What you expected to happen

```python
======== Autoscaler status: 2022-06-24 04:18:12.271411 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray_head_default
 4 ray_tpu-chip
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/386.0 CPU
 0.0/4.0 TPU
 0.00/936.219 GiB memory
 0.00/401.547 GiB object_store_memory

Demands:
 (no resource demands)
ubuntu@ray-hack-jax-pod-head-bf8ed344-compute:~$ ray get-worker-ips *yaml

```

there is no ips showing up in the `ray status`. 

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by JiahaoYao** [comment]
@DmitriGekhtman

**Comment by zhe-thoughts** [comment]
@rkooo567 Need your help triaging. Is this specific to Autoscaler? Or it's about `ray status` itself?

**Comment by DmitriGekhtman** [comment]
This dates to a June hackathon project: When using autoscaling, `ray status` does not show a list of IPs of nodes -- it just shows counts of each node type.

This issue could be interpreted as a feature request for `ray status` (always show IPs). I believe this request has come up before, so we could leave this open as a low-priority feature request issue.

Actually, showing IPs is part of what @wuisawesome's new experimental verbose flag to `ray status` does, see
https://github.com/ray-project/ray/pull/28392, so we can consider this issue closed once we promote the flag from its experimental state.

**Comment by wuisawesome** [comment]
Yep, if anyone stumbles upon this issue you can try out `ray status --verbose` on `ray >= 2.1.0`. Note it's experimental, and there are no official support guarantees right now.

**Comment by rkooo567** [comment]
You can also use `ray list nodes`

**Comment by rkooo567** [comment]
i think we can just close it now. Maybe when we promote ray status --verbose, we will forget about this issue. Please reopen if you disagree!

**Comment by steveepreston** [comment]
@JiahaoYao how you use `0.0/4.0 TPU`?
i have `0.0/4.0 TPU` too in TPU env, but when i set `tune.with_resources(train_model, resources={"cpu": 96, "tpu": 4}),` it Throws:

`Error: No available node types can fulfill resource request {'CPU': 96.0, 'tpu': 4.0}. Add suitable node types to this cluster to resolve this issue.`
