### ISSUE TITLE
[CI] `osx://python/ray/dashboard:modules/serve/tests/test_serve_head` is failing/flaky on master.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#26068]
- 4d8a82bdf6f0f11c17b6a7b987fcbce6cbeb1bbf FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8293#01818dac-597d-4d70-b52e-2de64c8440fb)
- 67140f2d267ac704a99d53df1e8ac0d6c5475a87 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8292#01818d97-b191-47cb-b80f-d96072087d21)
- 6552e096e6575e45df72501c5c1cf54f72bdbccf FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8285#01818b93-9a39-44e6-b646-fb36bc9035e8)
- 3d6df50258efe7d5af7a16b1ab8524588f0de5d6 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8284#01818b1c-6928-4b1f-bce6-a64841cdd193)
- a29eeaa1f645ee1b5c9494acdf41c34918324e12 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8277#0181885d-d481-4947-9828-2f73fd58dc54)
- 43aa2299e6623c8f8c7c4a1b80133459d0aa68b0 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8276#01818853-f3f2-4c1d-bb77-c645d250cdc3)
- ad12f0cd020ad736007fbd07baa6a70eb655328e FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8271#01818772-1011-4f6d-85ed-1ff9e16b42bf)
- fe4185974aa189a4ae7a395109604ec18273a168 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8268#018186e9-8a47-4ddb-8111-fea0f9dcecae)
- 7b8ea81f18b82b77530a21930e1169fee7fc6f5d FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8267#018186d5-b0f0-4d3f-aead-771680bf0385)
- e10876604d4ce1d5f8a8bbadaa4d4fd8548b4b66 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8263#018185fe-0986-426e-a8b4-05b9be6d13a7)
- d1d5fe61c2a5e515517c01de2878ca44d93562fc FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8262#018184e1-b171-4878-8310-4dad7cebedc4)
- 96693055bd4b466e438564f20e9adaef52e4471b FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8255#01818164-4e7c-4762-a7f0-bf93caf69716)
- e13cc4088a2a6fb7093ff0e55b2df02ab9b5d048 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8253#01817f2d-d0fe-416b-a82e-882c2b76e8e7)
- 3de4657caedefc9b25f18e92565ddf1bd3bcb74d FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8252#0181792a-7c25-4ac2-aa75-bd00e3d8fe27)
- 216aede789f65e48b1c5543669437fc9f869001d FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8250#0181790c-bd05-437b-953b-82d2155e5c0d)
- 1701b923bc83905f8961c06a6a173e3eba46a936 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8241#018173e6-141f-4b8c-942a-d87bbf2e0ec1)
- c2ab73fc40b087f999c7b89ee8361d276484a2f8 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8234#0181731f-84c7-4c1a-983e-3ee4eab940c3)
- 85be093a8440b746443df50213a0dae1b5fc9242 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8233#01817315-f284-4109-b66d-4af4efb2bffe)
- d90c6cfbd643668ee210eb8d40a370447825dab9 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8232#018172dd-abb2-42b9-b4f6-9a2506f0a4df)
- 438b6c78c8ed906fa3da539bf214f2cb54736b91 FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8231#018172dd-7469-48e0-85a6-2566d42840e4)
- b24c736bb8e5574d8bfbd71d2e8fc093e10c10ae FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8228#0181725b-80f2-406c-8e53-af7a6d58c1ef)
- edf16b8e2cee47de1039b816b230225a78c897ae FAILED [Buildkite :mac: :apple: Ray C++, Java and Libraries](https://buildkite.com/ray-project/ray-builders-branch/builds/8227#0181725a-035b-4e8f-bdf3-f335faf76517)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/dashboard:modules/serve/tests/test_serve_head-END
....

**Comment by simon-mo** [comment]
Should be closed by https://github.com/ray-project/ray/commit/4d8a82bdf6f0f11c17b6a7b987fcbce6cbeb1bbf

**Comment by architkulkarni** [comment]
Looks like it's still flaky.
<img width="1234" alt="Screen Shot 2022-06-28 at 1 22 22 PM" src="https://user-images.githubusercontent.com/5459654/176277776-bd1cd2c9-18af-48b6-925e-bccd95a922ad.png">

**Comment by simon-mo** [comment]
no more!  🎉 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/21118851/177626885-134f2c99-1367-4af3-bcf1-608552369403.png">
