### ISSUE TITLE
[kuberay][autoscaler] monitor.log might go missing, leading to crashlooping autoscaler

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#26064]
### What happened + What you expected to happen

There appear to be situations in which the file the autoscaler writes logs to might go missing, causing an exception:
```
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kuberay/run_autoscaler.py", line 48, in _run_autoscaler
    _setup_logging()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kuberay/run_autoscaler.py", line 80, in _setup_logging
    backup_count=ray_constants.LOGGING_ROTATE_BACKUP_COUNT,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/ray_logging.py", line 69, in setup_component_logger
    backupCount=backup_count,
  File "/home/ray/anaconda3/lib/python3.7/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/ray/anaconda3/lib/python3.7/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/ray/anaconda3/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/ray/anaconda3/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ray/session_latest/logs/monitor.log'
```
See https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1656042173496989
Some simple error handling in the method that writes logs should resolve this.

### Versions / Dependencies

Ray master? KubeRay master?

### Reproduction script

Run an autoscaling KubeRay cluster for a long time??
Might be hard to reproduce.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by DmitriGekhtman** [comment]
These changes should help: https://github.com/ray-project/ray/pull/26188

**Comment by DmitriGekhtman** [comment]
Permissions errors with the same file are also being reported.
We will see if this if this resolved in the latest update.

**Comment by DmitriGekhtman** [comment]
We should make sure this is definitively fixed before the Ray 2.0 release.

**Comment by DmitriGekhtman** [comment]
See also https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1657667989560389?thread_ts=1657663114.302419&cid=C02GFQ82JPM

**Comment by DmitriGekhtman** [comment]
Current status: Need to find out if issues recur with latest autoscaler changes.
Need to collect more data on the circumstances of the bug.

**Comment by alex-treebeard** [comment]
I'm facing this on ray `1.3.0` with kuberay on `781eed1`.

Happy to test a fix. Also keen to know about simple workaround (right now I just exec into the pod and create the file so I can try out the autoscaler)

**Comment by DmitriGekhtman** [comment]
Do you mean `Ray 1.13.0`?

@alex-treebeard could you confirm the image used by the autoscaler container from `kubectl get pod <head-pod>`?

**Comment by DmitriGekhtman** [comment]
Could you also share the stack-trace?

**Comment by DmitriGekhtman** [comment]
https://github.com/ray-project/kuberay/pull/391 should fix this

**Comment by DmitriGekhtman** [comment]
For extra safety, https://github.com/ray-project/ray/pull/26748 should also fix this.

**Comment by alex-treebeard** [comment]
@DmitriGekhtman apologies, yes I meant `1.13.0`

I'm using an application-specific autoscaler image to guarantee that the same Python/Ray versions are used for all containers.

I will try kuberay chart https://github.com/ray-project/kuberay/commit/dc771779cf4cb3cf413915d22bcbcc41abda3ef8 with its respective [image](https://hub.docker.com/layers/operator/kuberay/operator/dc77177/images/sha256-bd690791c1206bed7a1377d0886435819068f64b863367ad0db391a725c770ba?context=explore) to see if the issue is solved.

Please let me know if there are other packages I'll need to update other than these
