### ISSUE TITLE
[Rllib] This loss function acatually did not work and it did not override the one in base.

### ISSUE THREAD

**Issue by TransitGym** [ray-project/ray#26084]
https://github.com/ray-project/ray/blob/95fe3271ec4be041d9831d13277e3c791b49789d/rllib/examples/centralized_critic.py#L186

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for raising the issue. Can you please be more specific?
What do you mean by "This loss function acatually did not work"?
And why would it not override the one in base?
Can you explain how I can make the issue here more visible, so that I can work on it, please?
