### ISSUE TITLE
Java and Python `UniqueID` generation does not match

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#2608]
### Describe the problem
The Java and Python frontends currently use different algorithms to generate `TaskID`s and `ObjectID`s. Ideally, **they should both use the functions in `src/ray/id.h` to generate `UniqueID`s**. This is the code that is currently shared between the Python frontend and the Raylet backend.

This problem manifests itself when the Raylet backend tries to compute the `TaskID` of the task that generated a given `ObjectID`. It does this, for instance, when trying to decide whether to reconstruct an object. As of #2526, the exact sequence of steps is:
1. The `ReconstructionPolicy` is asked to reconstruct an `object_id`, which was computed with the code in `java/runtime-common/src/main/java/org/ray/core/UniqueIdHelper.java`.
2. The `ReconstructionPolicy` computes the task ID from `object_id`, but gets the wrong task ID, since it uses the `ComputeTaskId` helper function in `src/ray/id.h` to do so. It begins to listen for task lease notifications for the wrong task ID.
3. The `ReconstructionPolicy` soon times out the task since no notifications were received and attempts to reconstruct the task. However, it can't find the `TaskSpec` since it has the wrong task ID.

**Comment by robertnishihara** [comment]
@stephanie-wang thanks for reporting this!

cc @kingchin1218 @salah-man

**Comment by kingchin1218** [comment]
Thanks @stephanie-wang .

**Comment by stephanie-wang** [comment]
Great, thanks! @kingchin1218 and @raulchen, as a first step, we should at least make sure that the function to compute the task ID that created an object matches in both frontends. That way, at least we can have reconstruction work for the Java frontend.

**Comment by imzhenyu** [comment]
It is best that we can come up a manual id logic version defined in Java/Python/Core, respectively. And let's check their consistency upon every startup.

**Comment by jovan-wong** [comment]
@robertnishihara 
It's time to close this issue. :)

**Comment by robertnishihara** [comment]
Thanks!
