### ISSUE TITLE
[Datasets] Add a `local_only=True` option for reading and writing datasources.

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#26083]
A common pain point for users when reading data is that the data files may only be on local node's filesystem. When writing data, they may also wish to write to the local node filesystem. We could support these use cases with a `local_only` flag, e.g.:

```
ds = ray.data.read_csv("file.txt", local_only=True)
ds.write_csv("/tmp/out.txt", local_only=True)
```

Under the hood, this can just set the scheduling strategy of the read/write tasks to force them to be scheduled on the current node.

cc @clarkzinzow @jianoaix @richardliaw

**Comment by matthewdeng** [comment]
To consider: having this as a flag in the DatasetContext, and also whether this should just be for IO or expand to all scheduling.

**Comment by ericl** [comment]
I think this flag specifically only makes sense for read operations on files. It's basically saying to treat `file://` URIs as a local-only resources instead of networked. I don't know why you'd ever want this on other operations, which don't have such URI dependencies.

**Comment by clarkzinzow** [comment]
+1 to @ericl's assessment, the primary use case is wanting to read/write small datasets from/to local disk. A full-on local mode for all operations is out-of-scope for this feature IMO, and it can already be achieved with the hard local mode affinity scheduling strategy in the `DatasetContext` anyway (might be worth documenting this as a debugging route).

**Comment by jianoaix** [comment]
Is there any link to the existing use cases?

The use case I can think of for "read/write locally, process distributedly" is those highly compute-intensive workload, where  a small amount of data could use a large amount of CPUs.
