### ISSUE TITLE
[CI] `linux://rllib:test_sac` is failing on master.

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#26097]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/21118851/175752034-5efe9f28-4e96-410d-b4fa-2f8b54a79510.png">

The root cause was very likely probably 257e67474cbdaed3acf9049d27a6e540dd822f94

- f7d0ad3bb75ffafaa902363e4d32f19fff9dad21 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8337#018197f3-76e3-475f-b2a9-f4f08afdae84)
- f71a4680da1f47417e10343942f8a14487f82b53 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8336#018197f2-ba8f-4d58-8227-76458fd091a7)
- 6092869ff302c2dc34edd6ff97cf7809e22d8ebb FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8335#018197c9-5ce7-4380-a1c2-f5dc94b11737)
- 0ec198acc2d62a89960396db181165d4d90d0cb7 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8334#018197c3-fcfd-4253-bbcf-60fb2124f6bc)
- fcd583688a6c515a484948fd661b2a2e98c31ed9 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8333#018197bf-bcbe-4f8c-8d11-e801160d30a9)
- 97a9a20f749f7d9d261343dcc3e0e9855fc54408 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8332#018197a6-43d8-4e4a-b5cc-14296ccbf0a5)
- 95fe3271ec4be041d9831d13277e3c791b49789d FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8329#018196e7-fe6d-4a00-82d0-b2b5adf2af4e)
- ef8461abac7f06261c542e1f15fe3123985d9ca1 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8326#01819602-c5d4-45f0-9b7d-26cab2c06b50)
- 012306da68ca56814152fb39d485e31ac9f1017b FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8325#018195d5-eae4-4241-b3d2-1029bfa297c8)
- bed9083f35e4b1af08583dd29300b9e764c5860c FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8324#018195d6-17c0-4a80-af52-46c2867ff677)
- eee866d762b42765c416c696c20f36da2357887e FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8322#018194ca-0a6f-4e46-b342-9934f884ba7e)
- 257e67474cbdaed3acf9049d27a6e540dd822f94 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/ray-builders-branch/builds/8321#01819463-1b80-40e9-8c5a-70d463de290b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://rllib:test_sac-END
....

**Comment by gjoliver** [comment]
sorry, missed the ping. but the fix is in.
