### ISSUE TITLE
[Core] Ray 2.0 API deprecation

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#26095]
In Ray 2.0 we will deprecate a bunch of APIs to make APIs update-to-date. Most of the deprecations will stay stay backward compatible and just begin a deprecation warning.

The following is the list of changes by action items we'll take.

Log deprecation warning:
- [x] ray.init(): local_mode
- [x] ray.init(): job_config
- [x] ray.remote(): placement_group
- [x] ray.remote(): placement_group_bundle_index
- [x] ray.remote(): placement_group_capture_child_tasks
- [x] ray.get_dashboard_url()
- [x] ray.get_resource_ids()
- [x] ray.disconnect()
- [x] ray.connect()
- [x] ray.util.ActorGroup
- [x] ray.util.ActorPool

Make a new API and then log deprecation warning for the old:
- [x] Add get_xx_id() to return hex (rather than object), and then deprecate the xx_id() (which returns Cython object): the xx here can be node, task etc.

Remove:
- [ ] ray start: remove --plasma-store-socket-name
- [ ] ray start: remove --raylet-socket-name
- [ ] ray.remote(): object_store_memory
- [ ] autoscaler: https://github.com/ray-project/ray/issues/20837
- [x] ray.util.data.MLDataset: https://github.com/ray-project/ray/pull/25041

cc @scv119 @ericl @rkooo567 @jjyao

**Comment by scv119** [comment]
cc @clarng will help on the local_mode deprecation!
