### ISSUE TITLE
[tune] Cross-Framework Compatibility

### ISSUE THREAD

**Issue by joyyoj** [ray-project/ray#2612]
### Describe the problem
Currently, Trial and TrialRunner make ray-tune depend on ray that limit the use of ray-tune.
To make ray-tune capable of running on top of some other execution framework, we suggest to do some code refactoring on ray-tune.

1. add interface TrialExecutor that abstracts the execution of a Trial. 

2. replace the corresponding code in TrialRunner.

3. remove some execute releated function including start/stop/pause/resume from Trial.

### Source code / logs

    class TrialExecutor(object):
        def setup(self):
            import Trial
            pass

        def launch_trial(self, trial):
            raise NotImplementedError

        def stop_trial(self, trial, error=False, error_msg=None):
            raise NotImplementedError

        def pause_trial(self, trial):
            raise NotImplementedError

        def resume_trail(self, trial):
            raise NotImplementedError
        
        def recover_trial(self, trial):
            """ recover trial state from last checkpoint. """
            pass

        def get_running_trials(self):
            """ get running trials """
            raise NotImplementedError

        def fetch_next_result(self):
            raise NotImplementedError

        def debug_string(self):
            pass

    class RayTrialExecutor(TrialExecutor):
        ...

    class CustomTrialExecutor(TrialExecutor):
        ...
    class Trial:
        def __init__(self):
            self.status = Trial.PENDING
            self.trial_id = None
            self.num_failures = None
            self.max_failures = None

        def is_finished(self):
            pass

        def set_verbose(self):
            pass

        def update_last_result(self, result, terminate):
            pass

        def should_stop(self, result):
            pass

        def is_finished(self):
            pass

        def has_checkpoint(self):
            pass

        def should_checkpoint(self):
            pass

        def progress_string(self):
            pass

        def checkpoint(self):
            pass

        def restore(self, checkpoint_path):
            pass

    class RayTrial(Trial)
        def train_remote(self):
            pass
        pass
        ...
    
    class CustomTrial(Trial):
        ...

**Comment by richardliaw** [comment]
Thanks for opening this discussion.

The separation of execution and data is a good idea. That being said, can you clarify the functionality of the following methods:
 - `checkpoint`: this would mainly serialize meta-data?
 - `def train_remote(self)` - why is this function part of the Trial and not in the executor?

Overall, providing docstrings on these methods would be very beneficial for reading. Basically, for each class, the list of attributes and their description; for each method, a summary of the method, the args and the return values, and descriptions for each. Could you do that?

I'm also curious about the changes to be made in the TrialRunner, but I guess that will be better conveyed in the PR.

**Comment by joyyoj** [comment]
I added a PR here: https://github.com/ray-project/ray/pull/2646

**Comment by richardliaw** [comment]
Finished in #2646.
