### ISSUE TITLE
[Datasets] Add Polars backend for grouped and global aggregations.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#26131]
[Polars](https://www.pola.rs/) is one of the fastest and most memory-efficient single-node DataFrame libraries in existence and is Arrow-native. By porting our grouped and global aggregations to Polars, we should see the following benefits:
- faster aggregations (20x faster in prototyping)
- more memory-efficient aggregations
- less code complexity

**Comment by thatcort** [comment]
I love this! Would it be possible to expose Polars' expression API to operate over Ray Datasets?

**Comment by prrao87** [comment]
Hi, I just [saw](https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.map_batches.html) that `ray.data.Dataset` map batches only accepts numpy arrays and pandas DataFrames -- is there any progress in allowing users to bypass these primitives entirely and just use arrow-only primitives to interface with Ray's data plane?

**Comment by anyscalesam** [comment]
Per discussion with @c21 we have this in data already; super old ticket.
