### ISSUE TITLE
[Datasets] De-experimentalize lazy execution mode

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#26132]
Lazy execution mode has proven invaluable for decreasing execution time and decreasing memory utilization across most Datasets workloads. We should de-experimentalize lazy mode and encourage its use.

## De-experimentalization Criteria

To de-experimentalize this API, we must meet the following criteria:

- [ ] Full test suite passes under lazy mode (switching between eager and lazy mode down via a pytest fixture).
- [ ] Lazy mode is thoroughly documented in key concepts and user guides: usage examples, motivation, when to use eager mode vs. when to use lazy mode, etc.
- [ ] Datasets nightly tests pass under lazy mode.

**Comment by jianoaix** [comment]
This is done: https://github.com/ray-project/ray/pull/26934
