### ISSUE TITLE
[tune/rllib] Tuple space range problem

### ISSUE THREAD

**Issue by hfurkanbozkurt** [ray-project/ray#2614]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.5
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.5.0
- **Python version**: 3.6.6
- **Exact command to reproduce**: not applicable

### Describe the problem
 
In my environment, action space is the following:
```
Tuple([Discrete(20), Discrete(6)])
```
When I run a PopulationBasedTraining scheduler to train a PPO agent with that environment, ray does something strange.

Instead of selecting actions in ranges [0:20) and [0:6), it selects in ranges of [0:13) and [0:13). It would be great if you could help me to solve this problem.

**Comment by hfurkanbozkurt** [comment]
Hey, thank you for your answer.

The problem still exists without the PopulationBasedTraining scheduler.

Here is a little script to regenerate the problem:

```python
import gym
from gym.spaces import Tuple, Discrete, Box

import ray
from ray.tune import run_experiments
from ray.tune.registry import register_env

class RayEnv(gym.Env):
    def __init__(self):
        self.action_space = Tuple([Discrete(20), Discrete(6)])
        self.observation_space = Box(0, 1, (1,))

    def step(self, action):
        print("Action: {}, {}".format(*action))
        assert action[0] < 20 and action[1] < 6
        return self.observation_space.sample(), 0, False, {}

    def reset(self):
        return self.observation_space.sample()

def env_creator(env_config):
    return RayEnv()

def run():
    register_env("ray-env", env_creator)
    ray.init()
    run_experiments({
        "test": {
            "run": "PPO",
            "env": "ray-env",
        }})

if __name__ == "__main__":
    run()
```

**Comment by ericl** [comment]
Thanks for reporting this @hfurkanbozkurt , this should fix the issue: https://github.com/ray-project/ray/pull/2637/files

**Comment by hfurkanbozkurt** [comment]
Yes, it fixes the issue. Thank you for taking time to solve this problem @ericl and @richardliaw
