### ISSUE TITLE
Killing `ray start --block` should stop all child processes

### ISSUE THREAD

**Issue by jcrist** [ray-project/ray#2615]
It would be useful for deployment if `ray start --block` (or some other equivalent command) would start up all the Ray subprocesses in such a way that killing the initial command would stop all child processes. This makes it easier for Ray to be deployed using existing deployment tools which assume killing the started process fully cleans things up.

See https://github.com/ray-project/ray/issues/2214#issuecomment-411659135.

**Comment by mitar** [comment]
See also #2587.

**Comment by mitar** [comment]
On Linux, the best way to assure this is by setting `pdeathsig` on a parent process. Then if the parent process dies, Linux kills also all children. In Python you can do this by adding to `subprocess` `Popen` call arguments:

```
preexec_fn=lambda: prctl.set_pdeathsig(signal.SIGKILL)
```

You [need this package](https://pythonhosted.org/python-prctl/).

**Comment by mitar** [comment]
The issue is that this is not graceful, but that is OK. You should gracefully try to kill stuff from the parent process while it is running, but if it dies, then the rest dies with it.

**Comment by mitar** [comment]
I would say that it might be better to just reuse some existing process supervisor here instead of reimplementing all this and figuring our all the details on how to manage subprocesses on various systems.

**Comment by mitar** [comment]
Isn't this also related to #2005?

**Comment by robertnishihara** [comment]
One related comment about this. `ray start --block` should probably exit if the child processes have died. It could just check periodically to see if the raylet that it started is still up and running and if not then exit.

**Comment by mitar** [comment]
Why not use `prctl.set_pdeathsig`? That works even with SIGKILL on the parent process.

**Comment by edoakes** [comment]
Unfortunately `prctl` only works on Linux

**Comment by jcrist** [comment]
For this use case I commonly have child processes listen on a file descriptor inherited from the parent process (usually stdin), and shutdown when it closes. This allows children to monitor their parent in a cross-platform way.

**Comment by jcrist** [comment]
But yeah, as is I would not consider this fixed, as it doesn't handle SIGKILL, and still relies on the parent to properly stop all children.

**Comment by mitar** [comment]
Sure, if works only on Linux, but let's implement it for Linux at least.

**Comment by edoakes** [comment]
Inheriting a `PIPE` or file descriptor seems like a good solution, the tricky bit is that we're also spawning a redis server which we can't modify to monitor the pipe/FD. This can be addressed on linux using `set_pdeathsig` but would obviously prefer a portable solution. Any suggestions?

**Comment by jcrist** [comment]
In that case perhaps have a tiny shim process that starts redis as a child process, waits for its parent to die, then shuts redis down before exiting itself. Since the shim process should be low resources, it's unlikely to be killed by the OS or cluster-manager (e.g. YARN), and can react accordingly. On linux you could skip this and use `set_deathsig`, but you may want to keep things uniform across platforms for simplicity.
