### ISSUE TITLE
ray.util.iter.from_iterator Support working on GPUs

### ISSUE THREAD

**Issue by AI-Ahmed** [ray-project/ray#26157]
### Description

Hello guys,
    First of all, I liked your framework and how powerful it is. I have a generator that generates a torch.Tensor on GPU. If you can provide us with a feature that helps us to iterate over GPU generator that contains dict[Text, torch.Tensor] that generated from a class cannot access or modify. 

This generator is taking extensive time to finish the iteration. Therefore, It would be great if I can use 2 GPUs instead of one while iterating over this generator to cut off at least half of the time or may be based on the available GPUs. In my project, I can't use CPU, therefore `ray.util.iter.from_iterator` is giving me the warning to convert these tensors to CPU device.

I hope I was clear enough to help me. If you have any questions, please provide them to me and I will answer them, directly.

Best regards,

**Comment by stephanie-wang** [comment]
Currently Ray only supports CPU memory, so unfortunately I'm not sure if it can provide much support here.

To use 2 GPUs, you can specify the resources for a task or actor by specifying it in the ray.remote decorator: `@ray.remote(num_gpus=2)`.

Also as a friendly FYI, you may get a deeper discussion on discuss.ray.io. Happy to continue the conversation there as you develop your application further.

**Comment by AI-Ahmed** [comment]
First, I would like to thank you @stephanie-wang for how quickly you responded. Second, I would like to thank you for offering me to continue the discussion with you, it is meaning a lot to me.

If you have an email, I would appreciate sending you more details about what our startup is looking to achieve with Ray.

I have tested many other distribution systems such as numba, and accelerate, but I didn't see high potential from them due to the limitations in both libraries.

But when I tried Ray.io, I found this potential that I can do, and that's why I want to have a deep discussion with your team and see if what I am thinking about can be achieved using Ray.io.


We are looking for a way to handle the generators, returned data class objects, and multi-gradient calculations. I want to discuss with you the overall idea of how to do that and if this is something that can be done using Ray. There are third-party libraries that deliver generators that we can not adjust externally, but we can adjust the conditional function of it, but it needs to be serialised. I read almost everything regards these topics I mentioned to you here from Ray's documentation but I didn't find what I am looking for.

Please, I would like you to send me an email to send you more details.

Best regards,
