### ISSUE TITLE
[k8s] ConnectionError when using NGINX and Ray on k8s

### ISSUE THREAD

**Issue by tianbin-jiang** [ray-project/ray#26167]
### What happened + What you expected to happen

I have created a ray cluster 1.12.1 using helm chart, everything works good. However, I would like to use NGINX for reverse proxy. The ingress rule for this cluster port 10001 is configured as following:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
      ignore_invalid_headers on;
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ray-head
            port:
              number: 10001

The NGINX is installed using helm chart as well, using image: ingress-nginx/controller

The port 10001 client connection always timeout:

Error log:
File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/worker.py", line 887, in init
    return builder.connect()
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/client_builder.py", line 160, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/util/client_connect.py", line 36, in connect
    conn = ray.connect(
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/util/client/__init__.py", line 243, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/util/client/__init__.py", line 86, in connect
    self.client_worker = Worker(
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/util/client/worker.py", line 143, in __init__
    self._connect_channel()
  File "/Users/nix/miniforge3/envs/python38/lib/python3.8/site-packages/ray/util/client/worker.py", line 264, in _connect_channel
    raise ConnectionError("ray client connection timeout")
ConnectionError: ray client connection timeout

### Versions / Dependencies

Ray 1.12.1, Python 3.7.7, NGNIX 4.1.4

### Reproduction script

Ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
      ignore_invalid_headers on;
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ray-head
            port:
              number: 10001

### Issue Severity

High: It blocks me from completing my task.

**Comment by tianbin-jiang** [comment]
It seem the issue is due to 10001 port is using gRPC which is http2.0. 

See NGINX log when trying to connect with ray client 10001

grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 200 0 "-" "grpcurl/1.8.6 grpc-go/1.44.1-dev" 123 0.007 [default-ray-ray-head-10001] [] 172.17.0.9:10001 13 0.007 200 b87a1266c72fca494bba4b483fe2acef
127.0.0.1 - - [27/Jun/2022:05:04:21 +0000] "POST /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo HTTP/2.0" 200 0 "-" "grpcurl/1.8.6 grpc-go/1.44.1-dev" 15 0.002 [default-ray-ray-head-10001] [] 172.17.0.9:10001 13 0.001 200 b3aa07103d39f243cf704116e670ac74
127.0.0.1 - - [27/Jun/2022:05:05:11 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - 717e2bf989a52ddd267bbe86eb4f10f3
127.0.0.1 - - [27/Jun/2022:05:05:11 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - 0bd29d36fa9536ad6aee2800c22c2dfe
127.0.0.1 - - [27/Jun/2022:05:05:12 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - 4075731f1af5a31bdb12a8e47fc7007c
127.0.0.1 - - [27/Jun/2022:05:05:12 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - 869ada257838d2223e51f44316d68f1c
127.0.0.1 - - [27/Jun/2022:05:05:13 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - 85493555de3572d8b8fce5e7c28b8402
127.0.0.1 - - [27/Jun/2022:05:05:13 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - cf3f78f150cc591c6e09f192ba5c3764
127.0.0.1 - - [27/Jun/2022:05:05:16 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - e78567210ebd2fc961eb62bb53bcde3b
127.0.0.1 - - [27/Jun/2022:05:05:16 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - c814022748cdff195c63f13c340f5116
127.0.0.1 - - [27/Jun/2022:05:05:20 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - 42e517f3a11740d54201ef3f6886f646
127.0.0.1 - - [27/Jun/2022:05:05:21 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - 551c4966ed07b12d949b1e397f10fb7f
127.0.0.1 - - [27/Jun/2022:05:05:27 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - 986068dc3874cebee05b869abccbed4e
127.0.0.1 - - [27/Jun/2022:05:05:28 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - ddeab10bfcd4313d6563d664ead6d771
127.0.0.1 - - [27/Jun/2022:05:05:38 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.000 [] [] - - - - 73a43044ac17d935de9ab999dad4973f
127.0.0.1 - - [27/Jun/2022:05:05:38 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.001 [] [] - - - - ed46693a9fc0f2baf2aae44154e55690

**Comment by jiaodong** [comment]
cc: @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
> It seem the issue is due to 10001 port is using gRPC which is http2.0.

So, do you think it would help to use a different port?
I think we have some docs on setting up an ingress for Ray client...let me try to dig it up.

@ckw017 might have some input here from his experience working on Ray client on Kubernetes-based Ray clusters.
