### ISSUE TITLE
[core][C++ worker]Support specifying namespace when creating actors. 

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#26183]
### Description

namespace implementation([doc](https://docs.ray.io/en/latest/ray-core/namespaces.html)) has been implemented in Java/Python, but still not in C++ worker.
Now user can't specify namespace when creating c++ actors, but the actors are all assigned a default empty namespace(like [here](https://github.com/ray-project/ray/blob/master/cpp/src/ray/runtime/task/native_task_submitter.cc#L111)).
We will support it ASAP in order to
1. make namespace working in c++ worker
2. make namespace behavior consistent in x-lang scenario.

File this issue to track it.

cc @jovany-wang 

### Use case

https://github.com/ray-project/ray/pull/25305#issuecomment-1162577516

**Comment by jovany-wang** [comment]
Thanks a lot. 
FYI, the code path in Java is https://github.com/ray-project/ray/blob/master/java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java#L138-L139

**Comment by WangTaoTheTonic** [comment]
> Please update the issue description and title to provide more context (explain what a namespace is and why we need it for C++ worker).

Thanks for the reminding. I've update in the description.

**Comment by WangTaoTheTonic** [comment]
PR merged. Closing this.
