### ISSUE TITLE
[Core][tests] Latency reported by non_streaming_shuffle_100gb is not accurate 

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#26193]
### What happened + What you expected to happen

Recently the latency metric reported by this test was 103s, but the actual shuffle time reported by the script was:
```
Shuffled 95367 MiB in 52.5953323841095 seconds
```

Looks like this is because the reported metric includes the startup time for the test script in a subprocess, although I'm not sure why it took a full minute to do this.

### Versions / Dependencies

3.0dev

### Reproduction script

none

**Comment by jjyao** [comment]
This test is no longer there.
