### ISSUE TITLE
[Core] Microbenchmark performance regressions in multi_client_put_calls_Plasma_Store and client__tasks_and_put_batch

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#26195]
### What happened + What you expected to happen

There is a ~40% throughput drop between 6/9 and 6/10, commits 6f3de2af863cff95ff55a587003faf2b776fec65 and d0f975e00f32c5f632a39fbe8efb6df678f8b0a0. These are probably related.

### Versions / Dependencies

3.0dev

### Reproduction script

`ray microbenchmark`

**Comment by scv119** [comment]
(ray) chenshen@Chens-MacBook-Pro-16-inch-2019:~/Documents/source/ray(fix-cython-doc)$ git rev-list  6f3de2a..d0f975e --oneline
d0f975e00f [RLlib] Fix broken link replay buffer docs. (#25666)
dcfed617e5 [Core] fix gRPC handlers' unlimited active calls configuration (#25626)
6b9b1f135b [Deployment Graph] Move files out of `pipeline` folder (#25630)
2546fbf99d [Serve] Autoscaling for deployment graph (#25424)
1483c4553c use smaller instance for scheduling tests (#25635)
271c7d73ac [AIR][Serve] Add support for multi-modal array input (#25609)
7c39aa5fac [RLlib] Trainer.training_iteration -> Trainer.training_step; Iterations vs reportings: Clarification of terms. (#25076)
94d6c212df [RLlib] Replay Buffer API documentation. (#24683)
c3645928ca [RLlib] Fix no gradient clipping happening in QMix. (#25656)
730df43656 [RLlib] Issue 25503: Replace torch.range with torch.arange. (#25640)
b3a351925d [RLlib] Added meaningful error for multi-agent failure of SampleCollector in case no agent steps in episode. (#25596)
8af9ef8fee [RLlib] Discussion 6432: Automatic `train_batch_size` calculation fix. (#25621)
67b2eca6a2 Fix a few type annotations that may confuse people (#25645)
5586b89b1c [Serve] Improve logs for new Serve REST API (#25610)
445400d727 [CI] Print a summary of broken links in LinkCheck (#25634)
2614c24e47 [AIR] Add `predict_pandas` implementation (#25534)
88524d8b57 [air] add `CustomStatefulPreprocessor` (#25497)
