### ISSUE TITLE
Unmaintained anyscale and ray sub-projects need to be marked as deprecated or archived

### ISSUE THREAD

**Issue by glyfnet** [ray-project/ray#26199]
### What happened + What you expected to happen

The ray-project and anyscale organisation have unmaintained, non-functioning code repos that need to be moved to an archive section, or at the very least marked as DEPRECATED in the README.  Example: airflow-provider-ray. The public facing repo has many project forks,  side projects and meetup demo repos, so it may make sense to have a seperate project grouping for more transitory repos, and keep ray-project as exclusively for the widely used and maintained ray repos.

### Versions / Dependencies

none

### Reproduction script

https://github.com/anyscale/airflow-provider-ray

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
Closed per https://github.com/anyscale/airflow-provider-ray/pull/46
