### ISSUE TITLE
Don't rerun same task with same arguments if result is already available

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2620]
Currently it looks like every call to `.remote(...)` starts a new task no matter if the result for the same task and same arguments already exist. Ideally, for pure tasks, results could be reused instead of recomputed.

Is such memoization something which is aligned with Ray approach? Or should we build it on top of Ray with another layer of abstraction? I worry that in the latter case there would be additional latency to check another database for potential "arguments -> object" mappings which already exist.

**Comment by richardliaw** [comment]
I think @simon-mo has done something like this before as a higher layer of abstraction.

**Comment by simon-mo** [comment]
Yes. 

For pandas on ray we implemented memoizer by decorating @ray.remote calls 

https://github.com/modin-project/modin/blob/14240e1bb44f9aef65b612d5f69dcaa7eed03e28/modin/pandas/utils.py#L19-L105

**Comment by suquark** [comment]
@simon-mo I am curious that why don't you make use of bulit-in wrapper `functools.lru_cache` but create `LRUCache` instead?

**Comment by simon-mo** [comment]
@suquark It’s simply for python2 compatibility. Built-in wrappper was introduced in 3.4

**Comment by mitar** [comment]
@suquark It seems that currently there is hidden assumption that functions are pure because they are automatically retried if a worker dies. See #2635.

**Comment by robertnishihara** [comment]
@mitar its very common for functions to include randomness, e.g., to do a monte carlo estimate, you might do

```python
@ray.remote
def f():
    return np.random.uniform(0, 1)

np.mean(ray.get([f.remote() for _ in range(1000)]))
```

Memoization would cause this to behave in an unexpected way.

**Comment by raulchen** [comment]
@mitar I think caching the results among the cluster can be done by maintaining a cache Actor?
Generally, I think it's preferable to implement functionalities at application level whenever possible, instead of implement it in the ray core.

**Comment by mitar** [comment]
I think implementation at the application level would require additional round trips and thus increased latency. So it might not be the best approach for something so low level.

**Comment by raulchen** [comment]
```python
@ray.remote
class Foo:
    def __init__(self):
        self.cache = []
    def foo(self, param):
        if param not in self.cache:
            self.cache[param] = compute(param)
        return self.cache[param]
```
If you put the computation inside the cache actor, there's only one round trip. One right trip is inevitable, right?

**Comment by robertnishihara** [comment]
I believe we don't plan on doing this.

**Comment by adrianloy** [comment]
If someone stumbles upon this discussion: Consider checking out the flyte project which has a lot of features around caching. It is also able to integrate with ray.
