### ISSUE TITLE
[serve] Bad runtime_env causes traceback instead of a status message

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#26205]
Deployed a config with a bad runtime_env, e.g., `runtime_env: {"fake": "news"}`

```
ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.
ray::ServeController.get_serve_status() (pid=40678, ip=127.0.0.1, repr=<ray.serve.controller.ServeController object at 0x10db66520>)
  File "/Users/eoakes/code/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 360, in _create_runtime_env_with_retry
    runtime_env_context = await asyncio.wait_for(
  File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/Users/eoakes/code/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 317, in _setup_runtime_env
    await loop.run_in_executor(None, setup_plugins)
  File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/eoakes/code/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 303, in setup_plugins
    raise RuntimeError(f"runtime env plugin {name} not found.")
RuntimeError: runtime env plugin fake not found.
```

**Comment by hora-anyscale** [comment]
Per Triage Sync: @architkulkarni can you please repro on latest master?

cc: @sihanwang41

**Comment by architkulkarni** [comment]
@edoakes @shrekris-anyscale do you remember what the expected outcome is here? The traceback seems helpful and actionable.

**Comment by shrekris-anyscale** [comment]
I believe the issue is that we could validate this earlier (before submitting to the cluster) since `"fake"` isn't a valid `runtime_env` key. The error traceback could be more clear about this. @edoakes was there anything else?

**Comment by edoakes** [comment]
I think the issue is this should be presented as an explicit status message in the serve REST API. I'm not 100% sure though. @shrekris-anyscale could you try repro'ing it and checking that the behavior is as expected?

**Comment by edoakes** [comment]
Yeah when we call `get_serve_status` here it should give a status wrapping the error message, right now that itself is throwing an exception.

**Comment by edoakes** [comment]
Re-triaging as P1 because this could cause unexpected behavior in the Serve REST API (returning non-200 status code in this case)
