### ISSUE TITLE
Submitting a task with configurable num_return_vals should always return a list

### ISSUE THREAD

**Issue by ujvl** [ray-project/ray#2621]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.12
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0
- **Python version**: 2.7
- **Exact command to reproduce**: `my_task._submit(num_return_vals=1)`

### Describe the problem

If the `num_return_vals` parameter is *explicitly* passed into `task._submit()`, it should intuitively always return a list, even if the value passed in is 1. Currently it only returns a list of object IDs if `num_return_vals > 1`. This is because the user might be determining `num_return_vals` at runtime and shouldn't have to handle two cases separately.

**Comment by pcmoritz** [comment]
Yeah, that would be the right behavior!

Do you want to submit a small patch? You need to change the logic in
https://github.com/ray-project/ray/blob/909d7172b136cd563429a868365f440b78306452/python/ray/remote_function.py#L140
a little bit. The cases of explicitly set num_return_vals (=1) and the default (=None) are already distinct.

**Comment by robertnishihara** [comment]
Hmm, I can see arguments for both ways. Would you say the same of `@ray.remote`?
