### ISSUE TITLE
Metrics monitoring solution

### ISSUE THREAD

**Issue by mylinyuzhi** [ray-project/ray#2624]
Hi Ray team,
We want to collect the metrics, which from the ray-core and  the user code(user-define-metrics). 
In production environments, metrics monitor is very important. 

How about to import the [Prometheus](https://prometheus.io), it's the  popular monitoring solution and many languages are supported already and custom libraries are easy to implement.

The metrics solution is optional, ray could run without this.

Please let us know if you have any comments. Thank you in advance.

cc @robertnishihara  @eric-jj @alexbao @raulchen

**Comment by richardliaw** [comment]
Hi @mylinyuzhi, what specific metrics are you referring to for the ray-core? 

And by user code, do you mean application-level metric reporting?

**Comment by ericl** [comment]
Ray allocates Python workers dynamically, so in the absence of a fixed reporting port for application metrics reporting, you'll need to use pushgateway: https://github.com/prometheus/client_python#exporting-to-a-pushgateway

With regards to ray-core metrics, currently the Ray backend does not export any system level metrics, though this could potentially be done in the future via the prometheus C++ API.

**Comment by mylinyuzhi** [comment]
@richardliaw yes，the application owner some times need the application-level metric to monitor the health of the app

**Comment by mylinyuzhi** [comment]
@ericl yep, it need to use the push mode.
And  the Ray backend need to export system level metrics, e.g. the number of queued task, the total time of the task has queued. It is helpful for us to understand the health of the system.

**Comment by danielsuo** [comment]
cc @mihaic @gdoubleyew

**Comment by robertnishihara** [comment]
cc @imzhenyu

**Comment by robertnishihara** [comment]
This has been integrated.
