### ISSUE TITLE
[air] When passing datasets to AIR trainers, reserve a fraction of cluster CPUs for dataset execution

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#26243]
### Description

When users mix Dataset computations with Train computations (i.e., for data ingest: https://docs.ray.io/en/master/ray-air/check-ingest.html), currently Tune/Train do not reserve CPUs for Dataset tasks. This means that ingest could hang, or performance could be unpredictable, since Datasets is only able to use spare CPUs in the cluster.

The concrete proposal here is to add an option to placement groups to limit the fraction of CPUs on each node that can be reserved by the placement group bundles. Train can automatically set this when the user passes a Dataset to it, which will ensure that the Dataset has CPUs available for execution.

API:
```
ray.util.placement_group(..., max_cpu_fraction=0.8)
```

Implementation -wise, this can be implemented in the placement group scheduler by applying the max_cpu_fraction constraint when considering which nodes to place bundles in. We may also need to patch the autoscaler to take into account these constraints as well when packing bundles.

Related issue: https://github.com/ray-project/ray/issues/25110

**Comment by ericl** [comment]
@clarkzinzow could you add some details/link to your prototype PR here?

**Comment by clarkzinzow** [comment]
@ericl Can do!

**Comment by clarkzinzow** [comment]
@ericl Here is the PR with some TODOs, the placement group scheduler part appears to work as expected after some manual testing and the added test: https://github.com/ray-project/ray/pull/26245

**Comment by richardliaw** [comment]
Initial version completed
