### ISSUE TITLE
[air] All AIR examples need to be converted to use session.report

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#26258]
### What happened + What you expected to happen

Currently all the examples on master/docs seem to be still using `train.report`, etc.

### Versions / Dependencies

Master

### Reproduction script

...

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
Antoni wanted to take this part on.
cc @Yard1

**Comment by richardliaw** [comment]
awesome, thanks.
