### ISSUE TITLE
[core] JobSupervisor cannot be created because the Ray cluster cannot satisfy its resource requirements.

### ISSUE THREAD

**Issue by Anando304** [ray-project/ray#26260]
### **Context:**

I am following the trying to submit a ray job via the CLI and/or the Python SDK as described [here](https://docs.ray.io/en/latest/cluster/job-submission.html#using-the-cli-on-kubernetes). The ray cluster is running on K8's and I am trying to submit the job to the head node.

**Steps to reproduce problem listed below**

### Problem
It seems as though my job status is stuck in `PENDING`. I checked the Ray dashboard under Logical View, and it seems as though the JobSupervisor is in **Infeasible** status: `JobSupervisor cannot be created because the Ray cluster cannot satisfy its resource requirements.`

Any idea what I should change? I increased the resource cpu and memory limits but it still seems to give the same issue.

![job_submissionstatus](https://user-images.githubusercontent.com/45672939/176953792-e4370c6a-84c3-43ae-a120-b5f96a234ae3.png)

<img width="1488" alt="dashboard" src="https://user-images.githubusercontent.com/45672939/176953795-eeaea609-2a2e-4a86-b055-18e161c440a8.png">

I ran the following on the Kubernettes Ray Head Node for more information as well:
```
(base) ray@ray-head-86d4c465fd-lw49l:~$ python -c 'import ray; ray.init(address="auto"); print(ray.cluster_resources())'

{'CPU': 4.0, 'node:7.255.242.90': 1.0, 'memory': 2539692034.0, 'object_store_memory': 1121399192.0, 'node:7.255.243.24': 1.0, 'node:7.255.243.26': 1.0, 'node:7.255.243.25': 1.0}
```

### Steps to Reproduce Problem
**Setup Ray Cluster on K8's**
I am running Ray 1.13.0 locally and installed the Ray Image on a Kubernettes cluster using the following yaml file from the Ray Github. [ray-cluster.yaml](https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml).
- Install via `kubectl create -f ./ray-cluster.yaml

I port-forwarded the ray cluster to my local so that I can execute commands using the **_Ray CLI_** or **_Python SDK_** from my local machine onto K8's. I ran the following to achieve this:

- Find a `podName` to use: `kubectl get pods`
- `kubectl port-forward <podName> 8265:8265`
- `export RAY_ADDRESS="http://127.0.0.1:8265"`

**Ray App Script**
Utilized the same ray script from the quickstart. Here are the contents of that script(**firstProgram.py**):
```
from collections import Counter
import socket
import time

import ray


# Tells Ray to execute on Head node AND run in parallel.
ray.init(address="auto")

print(
  """This cluster consists of
    {} nodes in total
    {} CPU resources in total
""".format(
    len(ray.nodes()), ray.cluster_resources()["CPU"]
  )
)


@ray.remote
def f():
  time.sleep(0.001)
  # Return IP address.
  return socket.gethostbyname(socket.gethostname())


object_ids = [f.remote() for _ in range(10000)]
ip_addresses = ray.get(object_ids)

print("Tasks executed")
for ip_address, num_tasks in Counter(ip_addresses).items():
  print("    {} tasks on {}".format(num_tasks, ip_address))
```

**Ray CLI command for Job Submission**:
`ray job submit --runtime-env-json='{"working_dir": "./", "pip": ["requests==2.26.0"]}' -- python firstProgram.py`

**Comment by jiaodong** [comment]
cc: @DmitriGekhtman do you mind taking a look on Anando's k8s setup ? From job submission perspective we schedule `JobSupervisor` actor on headnode with its node name resources as you can see from the screenshot `node:7.255.243.24`, but it didn't seem available. I suspect it has something to do with ray dashboard not attached to ray cluster correctly, but not familiar with how our k8s launcher sets up everything.

**Comment by DmitriGekhtman** [comment]
I'll take a look.

It is recommended to use KubeRay to deploy. I'm surprised the manual K8s deployment instructions are still accessible. 
I'm noting the documentation issue.

**Comment by jiaodong** [comment]
Thanks for the quick response! Yes, indeed we should recommend new users to use KubeRay as default.

**Comment by Anando304** [comment]
I see, is there any work around without using KubeRay?

**Comment by DmitriGekhtman** [comment]
> I see, is there any work around without using KubeRay?

I'll experiment with the supplied config later today and let you know.

**Comment by Anando304** [comment]
I assume the CLI and/or Python SDK approaches should still work or are they no longer supported? Were you able to reproduce the same issue on your side?

**Comment by Anando304** [comment]
Ah perfect, thanks @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Thanks for the detailed reproduction!
Unfortunately, I was unable to replicate the issue following the reproduction steps -- the job ran successfully to completion.
If you'd like to schedule some time to pair program on this, let me know over on Slack.

**Comment by DmitriGekhtman** [comment]
@Anando304 and I looked at the issue together and were unable to detect any issues from the cluster scheduling / Ray resource annotation perspective.

In particular, we were able to successfully schedule a task requiring the "unavailable" node resource.

We may need help from the feature owners to get to the bottom of the issue.

**Comment by DmitriGekhtman** [comment]
That's correct!

**Comment by DmitriGekhtman** [comment]
Moreover, on my own GKE setup, I'm able to run everything successfully following the precise repro steps.

**Comment by architkulkarni** [comment]
On the off chance it's related to runtime_env somehow: is it possible to check `dashboard_agent.log` or `runtime_env_setup-*.log` on the head node to see if the runtime env setup succeeded or failed?  

We should be streaming an error to the local machine's command line if the runtime_env fails, but might be worth checking these logs just in case.  I don't think a runtime env setup failure should result in "infeasible" status anyway, but I'm not 100% sure.

**Comment by Anando304** [comment]
### **Problem Resolved**

**Problem Root Cause**
The problem seemed to be that the pip installations were getting blocked on the Kubernettes cluster since outbound internet access wasn't allowed due to security reasons. This caused connection timeouts and prevented the JobSupervisor from being executed correctly.

**Solution**
Adjusting the cluster to accept external traffic for pip libraries resolved the issue. Jobs are now succeeding!
