### ISSUE TITLE
[Core] ray.get becomes very slow when i increase the number of epochs

### ISSUE THREAD

**Issue by Medkne** [ray-project/ray#26270]
### What happened + What you expected to happen

I use ray.get(current_weights) to get the final weights of my model after finishing all epochs. The problem is when i use for example 2 epochs, ray.get(current_weights) takes 17s, and with 100 epochs takes 1000s. I don’t know why ?

```    
for epoch in range(n_epoch):
        for b in range(total_batch):
            gradients = [worker.compute_gradients.remote(current_weights) for worker in workers]
            current_weights = ps.apply_gradients.remote(*gradients)
        if (epoch + 1) % n_epoch == 0:
             weights = ray.get(current_weights)

```
As you can see, i don't use ray.get in the loop, and the duration changes with the number of epochs !

### Versions / Dependencies

Ray version : 1.13.0

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment]
Discussion is moved to [discuss.ray.io](https://discuss.ray.io/t/ray-get-becomes-very-slow-when-i-increase-the-number-of-epochs/6704/2).
