### ISSUE TITLE
Issue on page /train/examples/train_fashion_mnist_example.html

### ISSUE THREAD

**Issue by brown2021** [ray-project/ray#26285]
I tested this example swapping out a custom dataloader from that I created with the torchdata library. I am receiving errors like the below

  File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 317, in __getstate__
    value = pickle.dumps(self._datapipe)
AttributeError: Can't pickle local object 'S3ImageFolder.setup.<locals>.<lambda>'

I created the dataloader S3ImageFolder.  i have a lambda in the pipeline that is saying it is not serializable

     train = (
            train
            .map(lambda x: x[1])
        )

**Comment by xwjiang2010** [comment]
Hi @brown2021 
Could you share you entire script? Thanks!!

**Comment by xwjiang2010** [comment]
Got it, thanks!
I can't quite run this locally but could you try moving data loading steps into the `train` func?
The lines
```
dm.setup()
train_loader = dm.train_dataloader()
val_loader = dm.val_dataloader()
test_loader = dm.test_dataloader()
```
I believe the current way that `train` function is written implicitly captures some objects that cannot be pickled, causing the issue.

**Comment by brown2021** [comment]
When I do that i get the following error. Does Ray need to have map style dataset. I am trying to use an iterable because I want to be able to stream very large out of memory dataset in manageable batches.

  File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 337, in __len__
    raise TypeError(
TypeError: _IterDataPipeSerializationWrapper instance doesn't have valid length
(BackendExecutor pid=14235) 2022-07-05 15:40:17,357     ERROR worker.py:94 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::BaseWorkerMixin._BaseWorkerMixin__execute() (pid=14237, ip=127.0.0.1, repr=<ray.train.worker_group.BaseWorkerMixin object at 0x7f84a9cc3250>)
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/torch/utils/data/datapipes/iter/callable.py", line 120, in __len__
(BackendExecutor pid=14235)     return len(self.datapipe)
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/torch/utils/data/datapipes/iter/callable.py", line 121, in __len__
(BackendExecutor pid=14235)     raise TypeError(
(BackendExecutor pid=14235) TypeError: MapperIterDataPipe instance doesn't have valid length
(BackendExecutor pid=14235) 
(BackendExecutor pid=14235) During handling of the above exception, another exception occurred:
(BackendExecutor pid=14235) 
(BackendExecutor pid=14235) ray::BaseWorkerMixin._BaseWorkerMixin__execute() (pid=14237, ip=127.0.0.1, repr=<ray.train.worker_group.BaseWorkerMixin object at 0x7f84a9cc3250>)
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/worker_group.py", line 26, in __execute
(BackendExecutor pid=14235)     return func(*args, **kwargs)
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/backend.py", line 489, in end_training
(BackendExecutor pid=14235)     output = session.finish()
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/session.py", line 118, in finish
(BackendExecutor pid=14235)     func_output = self.training_thread.join()
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/utils.py", line 96, in join
(BackendExecutor pid=14235)     raise self.exc
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/utils.py", line 89, in run
(BackendExecutor pid=14235)     self.ret = self._target(*self._args, **self._kwargs)
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/ray/train/utils.py", line 138, in <lambda>
(BackendExecutor pid=14235)     return lambda: train_func(config)
(BackendExecutor pid=14235)   File "/Users/lecole/Documents/Development/DistributedTraining/ray_train.py", line 131, in train_func
(BackendExecutor pid=14235)     train_epoch(train_dataloader, model, loss_fn, optimizer)
(BackendExecutor pid=14235)   File "/Users/lecole/Documents/Development/DistributedTraining/ray_train.py", line 58, in train_epoch
(BackendExecutor pid=14235)     size = len(dataloader.dataset) // train.world_size()
(BackendExecutor pid=14235)   File "/Users/lecole/anaconda3/envs/playground/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 337, in __len__
(BackendExecutor pid=14235)     raise TypeError(
(BackendExecutor pid=14235) TypeError: _IterDataPipeSerializationWrapper instance doesn't have valid length
(playground) lecole@jonathans-MacBook-Pro-3 DistributedTraining %

**Comment by xwjiang2010** [comment]
@brown2021 
I believe Ray accepts Iter type dataset.
train_epoch` is where the error is thrown.
