### ISSUE TITLE
Encounter TypeError “too many positional arguments“

### ISSUE THREAD

**Issue by zxgm** [ray-project/ray#26283]
### What happened + What you expected to happen

I have encountered TypeError:too many positional arguments when Client call remote function that defined by Actor that have class member import from other module. The ray version 1.12.0
The reproduction code is in Section Reproduction script.

when execute _client.test1.remote function,encounter TypeError:
> Traceback (most recent call last):
>   File "Client.py", line 20, in <module>
>     a2 = _client.test1.remote(leagueId)
>   File "/usr/local/lib/python3.6/dist-packages/ray/util/client/common.py", line 539, in remote
>     self._signature.bind(*args, **kwargs)
>   File "/usr/lib/python3.6/inspect.py", line 2997, in bind
>     return args[0]._bind(args[1:], kwargs)
>   File "/usr/lib/python3.6/inspect.py", line 2924, in _bind
>     'too many positional arguments') from None
> TypeError: too many positional arguments

but update _client.test1.remote(leagueId) to _client.test1.remote(a=leagueId) that work fine.
Is this a feature or a bug?

### Versions / Dependencies

ray==1.12.0
Ubuntu18.04 WSL2 container in windows

### Reproduction script

Actor code:Server.py
```

import sys
import ray
sys.path.append("./")
from testA import ATest

@ray.remote
class ServerRay(object):
    def __init__(self) -> None:
        self.ab = ATest()

    def test(self):
        return "a"

    def test1(self, a):
        return a

if __name__ == "__main__":
    runtime_env = {"working_dir": "../testRay/"}
    ray.init(address="ray://xxxx:10001", namespace="DLInferServerNamespace", runtime_env=runtime_env)

    server = ServerRay.options(name="DLInferServer", 
        namespace="DLInferServerNamespace", max_concurrency=20).remote()
    
    print("Initialize Server success.")
    input()

```

ATest class code in testA.py file
```

class ATest(object):
    def __init__(self):
        pass

```

client code 
```

import ray

if __name__ == "__main__":
    ray.init(address="ray://xxxx:10001",namespace="DLInferServerNamespace")
    _client = ray.get_actor("DLInferServer",namespace="DLInferServerNamespace")

    print(_client)

    leagueId = 5
    execState_results_objId = _client.test.remote()
    print(ray.get(execState_results_objId))

    a2 = _client.test1.remote(leagueId) # work failed
    # a2=_client.test1.remote(a=leagueId) work fine
    print(ray.get(a2))

    input()

```

**Comment by tupui** [comment]
Hi @zxgm, thank you for reporting. I cannot reproduce your issue. Can you try with the new version? (1.13)

**Comment by zxgm** [comment]
I have encountered the same problem with new version(1.13.0).My environment:ubuntu18.04 WSL2 container in windows.Temporary solution:Use the key=value parameter to solve the problem

**Comment by tupui** [comment]
If you strip down your example to the bare minimum, does it still fail?

```python
import ray

ray.init()


@ray.remote
class ServerRay:
    def __init__(self):
        pass

    def test(self, a):
        return a


client = ServerRay.remote()
res = client.test.remote(5)
print(ray.get(res))

# and with ray.get_actor

client = ServerRay.options(name="toto").remote()
client_ = ray.get_actor("toto")
res = client_.test.remote(5)
print(ray.get(res))
```

**Comment by zxgm** [comment]
If  remove the line code 'self.ab = ATest()' in Server.py,that work fine.

**Comment by tupui** [comment]
@zxgm can you run the following? This is working fine on my side.

```python
import ray

ray.init()


class Toto:
    def __init__(self):
        pass


@ray.remote
class ServerRay:
    def __init__(self):
        self.ab = Toto()

    def test(self, a):
        return a


client = ServerRay.remote()
res = client.test.remote(5)
print(ray.get(res))

# and with ray.get_actor

client = ServerRay.options(name="toto").remote()
client_ = ray.get_actor("toto")
res = client_.test.remote(5)
print(ray.get(res))
```

**Comment by zxgm** [comment]
> @zxgm can you run the following? This is working fine on my side.
> 
> ```python
> import ray
> 
> ray.init()
> 
> 
> class Toto:
>     def __init__(self):
>         pass
> 
> 
> @ray.remote
> class ServerRay:
>     def __init__(self):
>         self.ab = Toto()
> 
>     def test(self, a):
>         return a
> 
> 
> client = ServerRay.remote()
> res = client.test.remote(5)
> print(ray.get(res))
> 
> # and with ray.get_actor
> 
> client = ServerRay.options(name="toto").remote()
> client_ = ray.get_actor("toto")
> res = client_.test.remote(5)
> print(ray.get(res))
> ```

It's working fine.If put the 'Toto' class code in same file with server.py, that's ok.Can you try to put Toto class to another file? The server.py and client.py connect to ray cluster that's already started by execute 'ray start --head'

**Comment by zxgm** [comment]
> 

It's working fine.If put the 'Toto' class code in same file with server.py, that's ok.Can you try to put Toto class to another file? The server.py and client.py connect to ray cluster that's already started by execute 'ray start --head'

**Comment by zxgm** [comment]
> @zxgm can you run the following? This is working fine on my side.
> 
> ```python
> import ray
> 
> ray.init()
> 
> 
> class Toto:
>     def __init__(self):
>         pass
> 
> 
> @ray.remote
> class ServerRay:
>     def __init__(self):
>         self.ab = Toto()
> 
>     def test(self, a):
>         return a
> 
> 
> client = ServerRay.remote()
> res = client.test.remote(5)
> print(ray.get(res))
> 
> # and with ray.get_actor
> 
> client = ServerRay.options(name="toto").remote()
> client_ = ray.get_actor("toto")
> res = client_.test.remote(5)
> print(ray.get(res))
> ```

It's working fine.If put the 'Toto' class code in same file with server.py, that's ok.Can you try to put Toto class to another file? The server.py and client.py connect to ray cluster that's already started by execute 'ray start --head'

**Comment by tupui** [comment]
@zxgm I still cannot reproduce. I have the following:

```python
# toto_class.py

class Toto:
    def __init__(self):
        pass

# toto_server.py

import ray

from toto_class import Toto

ray.init(address='auto')


@ray.remote
class ServerRay:
    def __init__(self):
        self.ab = Toto()

    def test(self, a):
        return a


client = ServerRay.remote()
res = client.test.remote(5)
print(ray.get(res))

# and with ray.get_actor

client = ServerRay.options(name="toto").remote()
client_ = ray.get_actor("toto")
res = client_.test.remote(5)
print(ray.get(res))
```

I start Ray with `ray start --head` and execute `python toto_server.py`.

I also tried with an extra file for a client like you have. It still works (just need to specify a namespace on top of a name).

**Comment by caseylai** [comment]
Encountered same issue in Ray 2.6.3, there is no obviously reason. Also I can add 'key=' to solve it, weird bug.

**Comment by pqlmwam** [comment]
same issue in Ray 2.39.0. I did a bit of debug and it seems that all the function signatures are wiped:
```
function_signature = self._ray_method_signatures[method_name]
```
All the methods inside self._ray_method_signatures have only **kwargs as arguments. Indeed, if I use arg_name=... is fine but any positional argument fails

**Comment by pqlmwam** [comment]
If you remove the imports, self._ray_method_signatures immediately populates with the right signatures, so it must be related to the import of local dependencies.

> same issue in Ray 2.39.0. I did a bit of debug and it seems that all the function signatures are wiped:
> 
> ```
> function_signature = self._ray_method_signatures[method_name]
> ```
> 
> All the methods inside self._ray_method_signatures have only **kwargs as arguments. Indeed, if I use arg_name=... is fine but any positional argument fails

**Comment by Clouder0** [comment]
Same issue here in Ray 2.41.0, Actor method signatures decay to kwargs only, but I failed to reduce our real scneario into a simplified minimal example.
