### ISSUE TITLE
[Ray : Train] Ray Train is not actually running parallelly ?

### ISSUE THREAD

**Issue by tianlinzx** [ray-project/ray#26294]
### What happened + What you expected to happen

We are running the officially example  '04-Ray-Train-with-PyTorch-FashionMNIST ' under  'academy/ ray-train'
We expect ray will utilize all 4 GPUs in ray cluster to run the same training job .
However ,we observe ray is running the same traing job per GPU, for 4 times.

If we want to use 4GPU to parallelly run the training job ? What should we do ?

### Versions / Dependencies

Ray 1.13.0

### Reproduction script

[https://github.com/anyscale/academy/blob/main/ray-train/04-Ray-Train-with-PyTorch-FashionMNIST.ipynb](https://github.com/anyscale/academy/blob/main/ray-train/04-Ray-Train-with-PyTorch-FashionMNIST.ipynb?rgh-link-date=2022-07-05T14%3A33%3A09Z)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by tianlinzx** [comment]
(BaseWorkerMixin pid=485, ip=10.244.5.187) 2022-07-04 22:29:11,826	INFO torch.py:98 -- Moving model to device: cuda:1
(BaseWorkerMixin pid=484, ip=10.244.5.187) 2022-07-04 22:29:11,845	INFO torch.py:98 -- Moving model to device: cuda:0
(BaseWorkerMixin pid=484, ip=10.244.5.187) 2022-07-04 22:29:11,848	INFO torch.py:132 -- Wrapping provided model in DDP.
(BaseWorkerMixin pid=485, ip=10.244.5.187) 2022-07-04 22:29:13,303	INFO torch.py:132 -- Wrapping provided model in DDP.
(BaseWorkerMixin pid=1161, ip=10.244.4.15) 2022-07-04 22:29:14,460	INFO torch.py:98 -- Moving model to device: cuda:0
(BaseWorkerMixin pid=1161, ip=10.244.4.15) 2022-07-04 22:29:14,462	INFO torch.py:132 -- Wrapping provided model in DDP.
(BaseWorkerMixin pid=1162, ip=10.244.4.15) 2022-07-04 22:29:14,806	INFO torch.py:98 -- Moving model to device: cuda:1
(BaseWorkerMixin pid=1162, ip=10.244.4.15) 2022-07-04 22:29:19,746	INFO torch.py:132 -- Wrapping provided model in DDP.
(BaseWorkerMixin pid=485, ip=10.244.5.187) Epoc: 50, Avg validation loss: 1.05, Avg validation accuracy: 60.00%
(BaseWorkerMixin pid=485, ip=10.244.5.187) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=484, ip=10.244.5.187) Epoc: 50, Avg validation loss: 1.02, Avg validation accuracy: 61.75%
(BaseWorkerMixin pid=484, ip=10.244.5.187) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=1162, ip=10.244.4.15) Epoc: 50, Avg validation loss: 1.07, Avg validation accuracy: 59.78%
(BaseWorkerMixin pid=1162, ip=10.244.4.15) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=1161, ip=10.244.4.15) Epoc: 50, Avg validation loss: 1.01, Avg validation accuracy: 62.43%
(BaseWorkerMixin pid=1161, ip=10.244.4.15) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=1162, ip=10.244.4.15) Epoc: 100, Avg validation loss: 1.03, Avg validation accuracy: 61.22%
(BaseWorkerMixin pid=1162, ip=10.244.4.15) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=1161, ip=10.244.4.15) Epoc: 100, Avg validation loss: 0.98, Avg validation accuracy: 63.57%
(BaseWorkerMixin pid=1161, ip=10.244.4.15) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=485, ip=10.244.5.187) Epoc: 100, Avg validation loss: 1.01, Avg validation accuracy: 61.02%
(BaseWorkerMixin pid=485, ip=10.244.5.187) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=484, ip=10.244.5.187) Epoc: 100, Avg validation loss: 0.98, Avg validation accuracy: 62.71%
(BaseWorkerMixin pid=484, ip=10.244.5.187) --------------------------------------------------------------------------------
CPU times: user 5.85 s, sys: 3.69 s, total: 9.54 s
Wall time: 20min 11s

**Comment by tianlinzx** [comment]
Above is the output for Step 7

**Comment by tupui** [comment]
Hi @tianlinzx, thank you for reporting. Where is this page coming from? Could you post a link instead? The issue is difficult to digest as it's not formatted.

**Comment by tupui** [comment]
Thank you, I will update your description with this link instead.

Did you manage to use multiple GPUs following another example from the documentation? Like the one I linked?

**Comment by xwjiang2010** [comment]
Thanks folks!
I have a clarification question. 
@tianlinzx Are you trying to run ddp on 4 GPUs, with each worker using 1 GPU? (so 4 workers all together) - just wondering since the example you linked is using 12 GPUs I think.

From the log, it seems ddp is doing what it's supposed to do - running parallelly on 4 GPUs:
```
BaseWorkerMixin pid=1161, ip=10.244.4.15
BaseWorkerMixin pid=1162, ip=10.244.4.15
BaseWorkerMixin pid=484, ip=10.244.5.187
BaseWorkerMixin pid=485, ip=10.244.5.187
```

**Comment by tianlinzx** [comment]
@xwjiang2010 Yes,it it running on 4 GPUs, but I wonder it is running the same traing task on 4 GPUs independently.
My target is to to split to train the model  parallelly on 4 GPUs to speed up the training ?
Are there any tickys ?

**Comment by tianlinzx** [comment]
@tupui @xwjiang2010 Since my Ray cluster has only 4 GPUs.
I have tried 1 worker, 2 worker, 4 workers. When I use 4 workder ,the training time is even longer than I used 2 GPUs.

**Comment by tianlinzx** [comment]
@tupui When I run https://github.com/anyscale/academy/blob/main/ray-train/02-Ray-Train-Quickstart-Distributed.ipynb this example using 2 GPUs, I encountered another error.

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?62f4554c-59a9-46bb-ac7a-f49a25cec7a6)
---------------------------------------------------------------------------
RayTaskError(RuntimeError)                Traceback (most recent call last)
/Volumes/Data/github/academy/ray-train/02-Ray-Train-Quickstart-Distributed.ipynb Cell 13' in <cell line: 3>()
      [1](vscode-notebook-cell:/Volumes/Data/github/academy/ray-train/02-Ray-Train-Quickstart-Distributed.ipynb#ch0000012?line=0) trainer = Trainer(backend="torch", num_workers=2,use_gpu=True)
      [2](vscode-notebook-cell:/Volumes/Data/github/academy/ray-train/02-Ray-Train-Quickstart-Distributed.ipynb#ch0000012?line=1) trainer.start()
----> [3](vscode-notebook-cell:/Volumes/Data/github/academy/ray-train/02-Ray-Train-Quickstart-Distributed.ipynb#ch0000012?line=2) results = trainer.run(train_func_distributed, config={'NUM_EPOCHS': [20, 40, 60]})

File ~/miniconda3/envs/python_385/lib/python3.8/site-packages/ray/train/trainer.py:356, in Trainer.run(self, train_func, config, callbacks, dataset, checkpoint, checkpoint_strategy)
    345 try:
    346     iterator = TrainingIterator(
    347         backend_executor=self._backend_executor,
    348         backend_config=self._backend_config,
   (...)
    354         run_dir=self.latest_run_dir,
    355     )
--> 356     for intermediate_result in iterator:
    357         for callback in callbacks:
    358             callback.process_results(intermediate_result)

File ~/miniconda3/envs/python_385/lib/python3.8/site-packages/ray/train/trainer.py:752, in TrainingIterator.__next__(self)
    750 if next_results is None:
    751     try:
--> 752         self._final_results = self._run_with_error_handling(
    753             self._finish_training
    754         )
...
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 529, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 3262, in mse_loss
    return torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!

**Comment by xwjiang2010** [comment]
> @xwjiang2010 Yes,it it running on 4 GPUs, but I wonder it is running the same traing task on 4 GPUs independently. My target is to to split to train the model parallelly on 4 GPUs to speed up the training ? Are there any tickys ?

When you say split, do you mean split the data or split the model? If we are talking about splitting the data, every worker will be running the same code. So say if you have a global batch size of 16 and 4 workers, each worker will get 1/4 of the batch, which is 4 for each worker.

**Comment by xwjiang2010** [comment]
> @tupui @xwjiang2010 Since my Ray cluster has only 4 GPUs. I have tried 1 worker, 2 worker, 4 workers. When I use 4 workder ,the training time is even longer than I used 2 GPUs.

This is definitely not expected. How are you configuring the batch size in both cases? And I am assuming epoch is the same in both cases?

**Comment by tianlinzx** [comment]
@xwjiang2010 
I am testing the example from https://github.com/anyscale/academy/blob/main/ray-train/04-Ray-Train-with-PyTorch-FashionMNIST.ipynb.

I just modified the number_of_workers in Step 6 from 1 to 2 and 4. 
I didn't make any changed the rest of the code including batch-size and epoch.

**Comment by xwjiang2010** [comment]
@tianlinzx 
for your comment [here](https://github.com/ray-project/ray/issues/26294#issuecomment-1175583466), the issue is that you need to use `to_device` to move the data onto GPU. You are right that we need to improve the tutorial here - it's pretty misleading rn. cc @amogkam 

as for this [example](https://github.com/anyscale/academy/blob/main/ray-train/04-Ray-Train-with-PyTorch-FashionMNIST.ipynb)

tried: 128 batch_size
4 GPU: 
CPU times: user 3.21 s, sys: 1.27 s, total: 4.48 s
Wall time: 9min 40s

2 GPU:
(BaseWorkerMixin pid=57383) Epoc: 50, Avg validation loss: 0.84, Avg validation accuracy: 70.25%
(BaseWorkerMixin pid=57383) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=57382) Epoc: 50, Avg validation loss: 0.85, Avg validation accuracy: 69.30%
(BaseWorkerMixin pid=57382) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=57383) Epoc: 100, Avg validation loss: 0.80, Avg validation accuracy: 71.23%
(BaseWorkerMixin pid=57383) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=57382) Epoc: 100, Avg validation loss: 0.81, Avg validation accuracy: 70.33%
(BaseWorkerMixin pid=57382) --------------------------------------------------------------------------------
CPU times: user 5.42 s, sys: 2.08 s, total: 7.5 s
Wall time: 18min 47s

And the validation is nowhere as good as the 4 worker case (which I forgot to paste, but it's > 85%)

Let me know if you want to pair programming on this together and we can find some time!

**Comment by tianlinzx** [comment]
Line21 is modified as below after adding "move_to_device=True"
   model = train.torch.prepare_model(model, move_to_device=True)
However the acceleration is not obvious as expected.

4 GPUs
(BaseWorkerMixin pid=8573, ip=10.244.4.40) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=2122, ip=10.244.5.18) Epoc: 100, Avg validation loss: 1.46, Avg validation accuracy: 45.98%
(BaseWorkerMixin pid=2122, ip=10.244.5.18) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=8567, ip=10.244.4.40) Epoc: 100, Avg validation loss: 1.47, Avg validation accuracy: 45.27%
(BaseWorkerMixin pid=8567, ip=10.244.4.40) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=2123, ip=10.244.5.18) Epoc: 100, Avg validation loss: 1.48, Avg validation accuracy: 45.66%
(BaseWorkerMixin pid=2123, ip=10.244.5.18) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=8573, ip=10.244.4.40) Epoc: 100, Avg validation loss: 1.50, Avg validation accuracy: 45.68%
(BaseWorkerMixin pid=8573, ip=10.244.4.40) --------------------------------------------------------------------------------
CPU times: user 3.63 s, sys: 2.04 s, total: 5.68 s
**Wall time: 5min 35s**

2 GPUs
(BaseWorkerMixin pid=2040, ip=10.244.5.18) Epoc: 50, Avg validation loss: 1.42, Avg validation accuracy: 47.29%
(BaseWorkerMixin pid=2040, ip=10.244.5.18) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=2041, ip=10.244.5.18) Epoc: 50, Avg validation loss: 1.45, Avg validation accuracy: 46.78%
(BaseWorkerMixin pid=2041, ip=10.244.5.18) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=2040, ip=10.244.5.18) Epoc: 100, Avg validation loss: 1.34, Avg validation accuracy: 49.38%
(BaseWorkerMixin pid=2040, ip=10.244.5.18) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=2041, ip=10.244.5.18) Epoc: 100, Avg validation loss: 1.36, Avg validation accuracy: 48.71%
(BaseWorkerMixin pid=2041, ip=10.244.5.18) --------------------------------------------------------------------------------
CPU times: user 3.76 s, sys: 2.36 s, total: 6.12 s
**Wall time: 6min 19s**

**Comment by tianlinzx** [comment]
Above examle the batch_size is 1024.
Test another two rounds when batch_size is 128

GPUs=2
(BaseWorkerMixin pid=276, ip=10.244.4.46) Epoc: 50, Avg validation loss: 0.89, Avg validation accuracy: 69.84%
(BaseWorkerMixin pid=276, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=275, ip=10.244.4.46) Epoc: 50, Avg validation loss: 0.86, Avg validation accuracy: 70.20%
(BaseWorkerMixin pid=275, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=276, ip=10.244.4.46) Epoc: 100, Avg validation loss: 0.82, Avg validation accuracy: 73.85%
(BaseWorkerMixin pid=276, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=275, ip=10.244.4.46) Epoc: 100, Avg validation loss: 0.79, Avg validation accuracy: 74.30%
(BaseWorkerMixin pid=275, ip=10.244.4.46) --------------------------------------------------------------------------------
CPU times: user 3.41 s, sys: 2.32 s, total: 5.74 s
Wall time: 7min 8s

GPUs=4
(BaseWorkerMixin pid=362, ip=10.244.4.46) Epoc: 50, Avg validation loss: 0.72, Avg validation accuracy: 73.00%
(BaseWorkerMixin pid=362, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=361, ip=10.244.4.46) Epoc: 50, Avg validation loss: 0.71, Avg validation accuracy: 73.09%
(BaseWorkerMixin pid=361, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=247, ip=10.244.5.20) Epoc: 50, Avg validation loss: 0.67, Avg validation accuracy: 75.15%
(BaseWorkerMixin pid=247, ip=10.244.5.20) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=248, ip=10.244.5.20) Epoc: 50, Avg validation loss: 0.71, Avg validation accuracy: 74.42%
(BaseWorkerMixin pid=248, ip=10.244.5.20) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=362, ip=10.244.4.46) Epoc: 100, Avg validation loss: 0.67, Avg validation accuracy: 75.14%
(BaseWorkerMixin pid=362, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=361, ip=10.244.4.46) Epoc: 100, Avg validation loss: 0.66, Avg validation accuracy: 74.38%
(BaseWorkerMixin pid=361, ip=10.244.4.46) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=247, ip=10.244.5.20) Epoc: 100, Avg validation loss: 0.61, Avg validation accuracy: 76.55%
(BaseWorkerMixin pid=247, ip=10.244.5.20) --------------------------------------------------------------------------------
(BaseWorkerMixin pid=248, ip=10.244.5.20) Epoc: 100, Avg validation loss: 0.65, Avg validation accuracy: 75.64%
(BaseWorkerMixin pid=248, ip=10.244.5.20) --------------------------------------------------------------------------------
CPU times: user 5.84 s, sys: 4.07 s, total: 9.91 s
Wall time: 19min 59s

**Comment by xwjiang2010** [comment]
Hmmm, just to make sure we are running the same example (as there are two in the thread already), are you using testing this [script](https://github.com/anyscale/academy/blob/main/ray-train/04-Ray-Train-with-PyTorch-FashionMNIST.ipynb)?
See my result [here](https://github.com/ray-project/ray/issues/26294#issuecomment-1177105132). We definitely are not expecting 4GPUs to take longer than 2GPUs time, if everything else stay the same.

**Comment by tianlinzx** [comment]
We are testing the same script .
I my ray cluster, I have 2 GPUs installed on  server 1 ,another 2 GPUs installed on  server 2 ?
Does this matter ?

**Comment by tupui** [comment]
It matters for small jobs. As any multi-cores strategy, it's only worth it if the unit of work is greater than the communications required between cores/nodes.

**Comment by tianlinzx** [comment]
@tupui Thanks . We will try more complicated training tasks later on and temporally close this issue.
