### ISSUE TITLE
ray.put starts to lag after pushing too many weights

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#263]
Original Issue:
In implementing RL algorithm A3C, workers will need to ship gradients back to the driver while the driver needs to ship updated policies back to the worker. After multiple iterations, the object store is overfilled and the eviction policy seems to slow down the entire algorithm.

The RL policy is represented by a convolutional neural network, with matrices of size:
[(4, 4, 16, 32), (256, 3), (1,), (8, 8, 4, 16), (3872, 256), (256, 1), (256,), (32,), (3,), (16,)]
Equivalently in bytes: [32912, 3184, 100, 16528, 3965040, 1136, 1120, 224, 108, 160]

Code to reproduce: 
```python
import numpy as np
import ray
import time

shapes = [(4, 4, 16, 32), (256, 3), (1,), (8, 8, 4, 16), (3872, 256), (256, 1), (256,), (32,), (3,), (16,)]
pseudo_weights = [np.random.rand(*s) for s in shapes]

ray.init(num_workers=1)

@ray.remote
def try_this(param):
	return param

log = []
remaining = []
test_weights = pseudo_weights
for i in range(500):
	start = time.time()
	param = ray.put(test_weights)
	log.append(time.time() - start)
	remaining.append(try_this.remote(param))
	ready, remaining = ray.wait(remaining)

	test_weights = ray.get(ready)[0]
	if i % 50 == 0:
		print log[-10:]
```
Log visualized here: 
![tmp](https://cloud.githubusercontent.com/assets/4529381/22812409/638773c6-eef9-11e6-8c59-d38621fb1d78.png)
begins to lag significantly after a few hundred iterations.

**Comment by robertnishihara** [comment]
Interesting, I tried a simpler version

```python
import ray
import time
import numpy as np

ray.init(num_workers=0)

x = np.zeros(10000000)

l = []
for i in range(500):
  start = time.time()
  ray.put(x)
  end = time.time()
  l.append(end - start)
```

And got a similar plot.

![put_plot](https://cloud.githubusercontent.com/assets/249517/22819057/3e13cc58-ef25-11e6-8d7f-1e63f3e84817.png)

**Comment by richardliaw** [comment]
If you zoom into the first 200, there should be a upward tick in the median time taken right?

Here's what my machine is showing (from a replicated run of your script)

![screenshot 2017-02-10 00 53 33](https://cloud.githubusercontent.com/assets/4529381/22820423/9360d268-ef2b-11e6-9e86-222a09358da8.png)

**Comment by robertnishihara** [comment]
The same plot but with  1GB object store memory (the previous plot was about 13GB).
![limited_memory](https://cloud.githubusercontent.com/assets/249517/22846923/da450316-ef9e-11e6-9d5e-1a6e8a274a52.png)

**Comment by robertnishihara** [comment]
This time with `x = np.zeros(10000000)` so the objects are 1/10th the size (and 1GB object store memory).
![smaller_objects](https://cloud.githubusercontent.com/assets/249517/22846973/23deb5ee-ef9f-11e6-96ef-3639c2fa6f32.png)

**Comment by pcmoritz** [comment]
This is the same workload in linux:

![plasma](https://cloud.githubusercontent.com/assets/113316/22847360/551e4e10-efa1-11e6-8a3d-8848bb84cbd4.png)

I think the large spikes we saw in mac os x with 13gb come from hitting the disk.

**Comment by robertnishihara** [comment]
Closing since I think we decided this was due to swapping.
