### ISSUE TITLE
[xray] GPU actors don't seem to run

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2631]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 8 p3.8xlarge
- **Ray installed from (source or binary)**: fix-plasma-sgd branch
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

This code seems to hang for a very long time:
 
```python
from __future__ import print_function

import tensorflow as tf
import ray

@ray.remote(num_gpus=8)
class Actor(object):
    def hello(self):
        a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
        b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
        c = tf.matmul(a, b)
        # Creates a session with log_device_placement set to True.
        sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
        # Runs the op.
        return (sess.run(c))

ray.init(redis_address="localhost:6379")

actors  = []
for a in range(8):
    actors += [Actor.remote()]
    import time
    time.sleep(5)

print(ray.get([a.hello.remote() for a in actors]))
```

### Source code / logs

if you run `nvidia-smi` on all nodes, you'll see that some of them will never register any running processes. However, individually ssh-ing into the node to run this code on 1 machine will work.

**Comment by robertnishihara** [comment]
@richardliaw This was probably fixed by the scheduling PR. Can you check if it works now?

**Comment by richardliaw** [comment]
This seems to work now.
