### ISSUE TITLE
WARNING: ray 1.13.0 does not provide the extra 'default'

### ISSUE THREAD

**Issue by jinfagang** [ray-project/ray#26319]
### What happened + What you expected to happen

WARNING: ray 1.13.0 does not provide the extra 'default'

### Versions / Dependencies

WARNING: ray 1.13.0 does not provide the extra 'default'

### Reproduction script

WARNING: ray 1.13.0 does not provide the extra 'default'

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
Hi @jinfagang could you provide a reproducible example for this?
