### ISSUE TITLE
[core] Improve usability for `ray.init` when there is an existing cluster

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#26329]
### Description

Two usability issues that I noticed:

1. `ray.init()` will always try to start a new standalone instance and will not warn you if there is an existing Ray instance on the same node. I think this is counter-intuitive to most newcomers and is a gotcha if you're trying to scale up from local development to a cluster.
2. When `ray.init()` is called implicitly (e.g., on the first `f.remote()` call), it will also default to the above behavior.

We can fix both by changing the default to `address="auto"`.

**Comment by rkooo567** [comment]
Should we do this as 2.0 API revamp? cc @jianoaix @jjyao @scv119

**Comment by pcmoritz** [comment]
How about we set `RAY_ADDRESS` in the cluster launcher? Then it is very clear which cluster we will connect to and we don't need to make the situation around auto starting clusters more complex :)

**Comment by DmitriGekhtman** [comment]
Because this requires modifying every supported deployment stack. 
Moreover, some users manually set up multi-node Ray clusters or build custom deployment systems.

Modifying `ray.init()` to look for an existing cluster would be simpler.
