### ISSUE TITLE
[RLlib] Build process broken on an M1

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#26324]
### What happened + What you expected to happen

Since #26069 , building on my M1 fails with the following output:

> ...
> [594 / 612] Compiling src/ray/gcs/gcs_server/gcs_server_main.cc; 17s darwin-sandbox ... (10 actions, 9 running)
>     ERROR: /Users/artur/code/ray/cpp/BUILD.bazel:87:10: Linking cpp/default_worker failed: (Aborted): cc_wrapper.sh failed: error executing command
>       (cd /private/var/tmp/_bazel_artur/5275745486df1b3805be5d731cd2c6db/sandbox/darwin-sandbox/11886/execroot/com_github_ray_project_ray && \
>       exec env - \
>         APPLE_SDK_PLATFORM=MacOSX \
>         APPLE_SDK_VERSION_OVERRIDE=12.3 \
>         PATH=/Users/artur/miniforge3/envs/ray/bin:/opt/python/cp36-cp36m/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/artur/bin \
>         XCODE_VERSION_OVERRIDE=13.3.0.13E113 \
>       external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-opt/bin/cpp/default_worker-2.params)
>     Execution platform: @local_config_platform//:host
> 
>     Use --sandbox_debug to see verbose messages from the sandbox
>     Undefined symbols for architecture arm64:
>       "ray::RunTaskExecutionLoop()", referenced from:
>           _main in default_worker.pic.o
>       "ray::Init(ray::RayConfig&, int, char**)", referenced from:
>           _main in default_worker.pic.o
>     ld: symbol(s) not found for architecture arm64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     Error in child process '/usr/bin/xcrun'. 1
>     external/local_config_cc/cc_wrapper.sh: line 69: 36984 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
>     INFO: Elapsed time: 20.258s, Critical Path: 19.92s
>     INFO: 13 processes: 10 internal, 3 darwin-sandbox.
>     FAILED: Build did NOT complete successfully
> ...

Reverting c8a90e00acba0081af5a4f6b3f676febe136e358 lets me build as usual.
`bazel clean --expunge` does not help.

### Versions / Dependencies

ab44133fba1fe2c3a05890a6d2a8d7b37b0acd43 builds fine
c8a90e00acba0081af5a4f6b3f676febe136e358 does not

Python 3.8.13

### Reproduction script

M1 system
Miniforge3-MacOSX-arm64.sh downloaded

```
bash Miniforge3-MacOSX-arm64.sh -b
conda install -c anaconda python=3.8 -y
git clone https://github.com/ray-project/ray.git
ray/ci/env/install-bazel.sh
brew update
brew install wget
pip install cython==0.29.21 pytest
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
conda install grpcio -y
cd ray/python
pip install -e '.' --verbose
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
Can't reproduce it locally.

**Comment by ArturNiederfahrenhorst** [comment]
@gjoliver can't reproduce locally, too.

Reverting the commit in question enables me to build again.
A fresh miniconda install and a fresh git clone won't help.
I'm keeping my hands off this for now to get other things done.

I'd like to leave the issue here so we can track this in case others experience this.

**Comment by larrylian** [comment]
I will find an m1 environment as soon as possible and fix this error。

**Comment by larrylian** [comment]
> crun

**Comment by larrylian** [comment]
> Hey @larrylian, this might not be an error on your side. All I can contribute to this is stating that I can compile fine without this commit and can not without. You can analyze this on my M1 if you like, especially since resolving this would benefit me.

I don't have a mac m1 environment for the time being, so I can't reproduce the positioning problem. How do I use your mac m1 environment analysis。

**Comment by ArturNiederfahrenhorst** [comment]
Hey @larrylian ,
Thanks for taking the time. I cherry picked your commit and also tried out a few other things until I found that nothing helps - except removing the additional linker option for os x. If nobody else is experiencing this issue and it will not gain attention over time, I'll assume the cause of this is hidden somewhere within other libraries on this Mac and reset it at some point.

Feel free to reopen this if you are experience the same issue.

**Comment by larrylian** [comment]
> Hey @larrylian , Thanks for taking the time. I cherry picked your commit and also tried out a few other things until I found that nothing helps - except removing the additional linker option for os x. If nobody else is experiencing this issue and it will not gain attention over time, I'll assume the cause of this is hidden somewhere within other libraries on this Mac and reset it at some point.

OK，Because I can't find the m1 environment now, I can't reproduce the problem. So I will not solve this problem yet. If anyone encounters it again, I will try to solve it.

**Comment by larrylian** [comment]
I have reverted my previous code, you can update the code and try again to see if there is still a problem.
https://github.com/ray-project/ray/pull/26438
