### ISSUE TITLE
import ray.rllib.ppo

### ISSUE THREAD

**Issue by CMXB** [ray-project/ray#2632]
Traceback (most recent call last):
  File "figure_eight.py", line 8, in <module>
    import ray.rllib.ppo as ppo
ImportError: No module named 'ray.rllib.ppo'

**Comment by CMXB** [comment]
the installation of ray is with the following command
sudo pip install ray

**Comment by CMXB** [comment]
UBUNTU 16.04 PYTHON 3.5

**Comment by ericl** [comment]
This has been moved to ray.rllib.agents.ppo in 0.5.0

**Comment by CMXB** [comment]
Thank a lot
