### ISSUE TITLE
[Runtime Environments] [Jobs] Propagate a warning when pip install hangs

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#26332]
### Description

In #26260, a job was stuck in `PENDING` because the `runtime_env` failed to `pip install` a package. The core issue was that the Kubernetes cluster disallowed outbound internet access, so the `pip install` hung indefinitely.

The only relevant message propagated back was `"Job has not started yet, likely waiting for the runtime_env to be set up."`. However, additional errors were logged about insufficient resources, which was a red herring during debugging.

The only way to detect that the `pip install` was hanging was to manually `exec` into a pod and try pip installing, which revealed the hang.

Ideally, Ray should instead detect the hang and propagate an error message specifically mentioning that the pip package’s install is hanging due to a network connection issue.

### Use case

This enables quicker debugging when `pip install` hangs.

**Comment by rkooo567** [comment]
Hmm this is a critical issue. We'd like to remove all these random hanging cases from Ray.

@architkulkarni should we probably have some sort of timeout to the API?

**Comment by DmitriGekhtman** [comment]
Adding to the confusion, the dashboard displayed a red herring about resource availability for the job scheduler actor :/

**Comment by architkulkarni** [comment]
I don't have a specific one in mind, but I know the pip and conda dependency resolver can be slow (googling "[conda install takes 10 minutes](https://www.google.com/search?q=conda+install+takes+10+minutes&oq=conda+install&aqs=chrome.0.69i59j69i57j0i131i433i512l5j69i65.926j0j7&sourceid=chrome&ie=UTF-8)" turns up some examples). I remember some users with heavyweight dependencies that took 10-20 minutes (maybe because pip install was installing from source) but I don't remember the details unfortunately.  

Still, I think you're right that 10 minutes will be sufficient for almost all cases, and in the error message we can show how to increase the timeout.

**Comment by architkulkarni** [comment]
It turns out we already have a default timeout of 10 minutes, but this was added after Ray 1.13 (which was used in the original issue.)

**Comment by rkooo567** [comment]
Have we done 

> Improve the error message;
However, additional errors were logged about insufficient resources, which was a red herring during debugging. -> can we make sure this error also includes runtime env?

? I think we shouldn't close it until this is supported

**Comment by architkulkarni** [comment]
I believe this referred to the dashboard message, which was updated in the PR.  @shrekris-anyscale were there other error messages involved here?

**Comment by shrekris-anyscale** [comment]
Yes, I believe there were errors in the dashboard about insufficient resources, so we tried increasing and decreasing the available number of CPUs. Is that what you mean by dashboard message? The actual issue turned out to be `pip` hanging, which is why we mentioned the resource error was a red herring.

**Comment by architkulkarni** [comment]
I'm referring to 

> It seems as though my job status is stuck in PENDING. I checked the Ray dashboard under Logical View, and it seems as though the JobSupervisor is in Infeasible status: JobSupervisor cannot be created because the Ray cluster cannot satisfy its resource requirements.

from the original issue.  https://github.com/ray-project/ray/issues/26260. 

The PR updates this specific message to include runtime env.  If that's the only error message that needed to be improved, we can close this issue

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/26911
