### ISSUE TITLE
[Core] Ray not available through pip for Python 3.10

### ISSUE THREAD

**Issue by aabmets** [ray-project/ray#26378]
### What happened + What you expected to happen

The command `pip install ray` fails to install Ray on Python 3.10 on Windows 10, because pip can't find a matching package of ray for Python 3.10.

Line nr 22 in Ray [setup.py file](https://github.com/ray-project/ray/blob/ea94cda1f3d0dc7fd39e259c7e82a07bdc9fafd3/python/setup.py) defines a list of supported Python versions, where version 3.10 is present:
`SUPPORTED_PYTHONS = [(3, 6), (3, 7), (3, 8), (3, 9), (3, 10)]`
But later in the file, Python 3.10 is not included in the PyPI classifiers list of the setup function.

### Versions / Dependencies

Python 3.10, Windows 10

### Reproduction script

pip install ray

### Issue Severity

High: It blocks me from completing my task.

**Comment by hora-anyscale** [comment]
Per Triage Sync: This was addressed
