### ISSUE TITLE
[Serve] `test_standalone2.py` is flaky due to `test_controller_recover_and_delete`

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#26372]
### What happened + What you expected to happen

`test_standalone2.py` is flaky:

<img width="1333" alt="Screen Shot 2022-07-07 at 3 20 33 PM" src="https://user-images.githubusercontent.com/92341594/177881094-3a1c39f6-5a6c-41cb-ba6f-271256750f83.png">

According to the tracebacks ([example](https://buildkite.com/ray-project/ray-builders-branch/builds/8517#0181d99a-d02e-44c2-a2b8-fde7a2378c3c)), the issue is in [`test_controller_recover_and_delete`](https://github.com/ray-project/ray/blob/43aa2299e6623c8f8c7c4a1b80133459d0aa68b0/python/ray/serve/tests/test_standalone2.py#L563).

This test checks whether a deployment deletion can be finished if the controller dies in the middle of it. It creates a 50-replica deployment, issues a deletion request, kill the controller, and checks whether the deletion is successful. However, it uses 50 replicas in the hopes that some replicas will still be alive when the controller is killed. This timing dependency makes the test prone to flakiness and makes it difficult to reduce the number of replicas used.

`test_controller_recover_and_delete` should be refactored to (1) stop being flaky and (2) stop relying on timing dependencies.

### Versions / Dependencies

Ray on the latest master. Test is flaking on Windows CI.

### Reproduction script

See [`test_controller_recover_and_delete`](https://github.com/ray-project/ray/blob/43aa2299e6623c8f8c7c4a1b80133459d0aa68b0/python/ray/serve/tests/test_standalone2.py#L563), and CI tracebacks ([ex. 1](https://buildkite.com/ray-project/ray-builders-branch/builds/8517#0181d99a-d02e-44c2-a2b8-fde7a2378c3c), [ex. 2](https://buildkite.com/ray-project/ray-builders-branch/builds/8505#0181d524-c4d7-49a6-bcc1-72ac3b5bd4e6), [ex. 3](https://buildkite.com/ray-project/ray-builders-branch/builds/8522#0181da78-ef50-4879-a51d-afd77c317dab)).

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by hora-anyscale** [comment]
Per Triage Sync: already fixed.

cc: @sihanwang41
