### ISSUE TITLE
[AIR][Dataset] Binary reading from s3 bucket is orders of magnitude slower than expected 

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#26383]
## Problem

Parallel download from S3 bucket with dataset on large # of image data with binary datasource performs worse than plain aws cp cli.

## Details 

While benchmarking AIR data ingest for imagenet, running the follow script with 20GB of images stored in single s3 bucket:

Worked e2e, 14mins doing data IO + processing, 40 secs doing “map” and actual prediction.

With plain aws s3 cp CLI, our hosts download speed is ~40MB/s, which will take ~8.5mins to download all files from s3. This leaves ~5.5 mins for actual processing of the images. 

Test environment's hardware NIC is 25Gbps.

dataset = ray.data.read_binary_files(paths=s3_url).fully_executed() took 
“Read” download from s3 took 775.8339920043945 secs, 26.4MB/s 

### Versions / Dependencies

On master

### Reproduction script

```
s3_url = "s3://air-cuj-imagenet-20gb"

import numpy as np
import pandas as pd
from io import BytesIO
from PIL import Image
import ray
from ray.air.util.tensor_extensions.pandas import TensorArray
from ray.train.torch import to_air_checkpoint, TorchPredictor
from ray.train.batch_predictor import BatchPredictor

from torchvision import transforms
from torchvision.models import resnet18

def convert_to_pandas(byte_item_list):
    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    images = [Image.open(BytesIO(byte_item)).convert('RGB') for byte_item in byte_item_list]
    images = [preprocess(image) for image in images]
    images = [np.array(image) for image in images]

    return pd.DataFrame({"image": TensorArray(images)})

# What is parallelism magic number?
dataset = ray.data.read_binary_files(paths=s3_url)
dataset = dataset.map_batches(convert_to_pandas)


model = resnet18(pretrained=True)

# # TODO: to_air_checkpoint should accept a model or a model state dict
ckpt = to_air_checkpoint(model=model)

predictor = BatchPredictor.from_checkpoint(ckpt, TorchPredictor)
predictor.predict(dataset, num_gpus_per_worker=1)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jiaodong** [comment]
Updated investigation findings with @clarkzinzow:

1) Change PyArrow to open_input_file() should bring it from 25MB/s to ~170MB/s with 7x improvement
   - This is due to open_input_stream() took ~1sec to read a single file and didn't quite work as our expected way.

2) There's still another 3x improvement opportunity by better parallelizing the workload or amortize cost of creating new workers / tasks as the max download we can get from S3 is around 500~600MB/s on this machine. Sample script with Ray parallelized read actors + threadpool executor reading boto3 https://gist.github.com/jiaodong/66301b13be6551b934e24de42b14a158

3) Using `meta_provider=ray.data.datasource.file_meta_provider.FastFileMetadataProvider()` helps to make bucket walk faster by bringing down a few seconds for 1GB bucket size. (Maybe we should make this default for s3 reading ?)

So items with highest ROI are 1) and 3) where 2) could be much more involved at Ray Core level. So this task serves as opportunity sizing.

**Comment by ericl** [comment]
For (2) wouldn't `read_binary_files(..., num_cpus=0.2)` increase the parallelism? Alternatively, we could also use multiple threads within the read task, that would probably be the simplest solution.

**Comment by jiaodong** [comment]
> For (2) wouldn't `read_binary_files(..., num_cpus=0.2)` increase the parallelism? Alternatively, we could also use multiple threads within the read task, that would probably be the simplest solution.

I gave that a try but didn't find significant speed increase however, sometimes even slower as ray will complain for too many tasks. So the numbers I got in 2) is purely from s3 boto reading that might be cutting corners, but it suggests s3 reading NIC is not the bottleneck, we're just not reading efficiently.

**Comment by clarkzinzow** [comment]
>For (2) wouldn't read_binary_files(..., num_cpus=0.2) increase the parallelism?

@ericl in my benchmarking increasing the number of parallel read tasks only slightly improved the throughput (~15%) for the many file case. Once I changed from streaming reads to random access reads, the optimal configuration was 1 read task per CPU core.
