### ISSUE TITLE
[Train] Add support for handling multiple batch data types for prepare_data_loader

### ISSUE THREAD

**Issue by VishDev12** [ray-project/ray#26385]
### What happened + What you expected to happen

When working with Ray Train, using the `ray.train.torch.prepare_data_loader` method with a dataset that returns a dictionary instead of a tuple from its `__getitem__` method causes issues.

That's because in the `_WrappedDataLoader` class, the `_move_to_device` method only deals with a tuple:

```python
return tuple(try_move_device(i) for i in item)
```

https://github.com/ray-project/ray/blob/6dd564d8b5123be5f3cf8e95197f4866c003b312/python/ray/train/torch/train_loop_utils.py#L539-L551

Ideally, this should deal with a dictionary type batch and an arbitrary level of nesting just like Pytorch does.

### Versions / Dependencies

Python: 3.8.10
Ray: Tested with 1.13.0. Code hasn't changed in master except for a move from `torch.py -> train_loop_utils.py`

### Reproduction script

Using any dataset that returns a dictionary from its __getitem__ method should demonstrate this issue.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by truelegion47** [comment]
Hi folks, I have a[ Draft PR](https://github.com/ray-project/ray/pull/26430) for this issue. Is this what we are intending to do here for dict handling ? Please provide feedback when you get a chance.
