### ISSUE TITLE
Add python redis package to ray Dockerfile

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/ray#26427]
### Description

To support Ray HA. currently we need external redis. For python to connect to redis server, we need python redis package. Currently, redis package is not installed in ray image. We need to have it installed in the dockerfile

For Kubeary to support Ray HA, in our current patch, we need to install redis package https://github.com/ray-project/kuberay/pull/294

@simon-mo @iycheng @brucez-anyscale @DmitriGekhtman @Jeffwan 

### Use case

Ray HA external redis connection.

**Comment by brucez-anyscale** [comment]
@iycheng Should we already have the package? Otherwise, how does the GCS access the redis now?

**Comment by DmitriGekhtman** [comment]
The GCS does not access Redis by default right now. I'll open a quick PR for this now.
