### ISSUE TITLE
Unclear how to configure huge tables and how it interacts with --object-store-memory

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#2644]
I think it is a bit unclear how Ray uses huge tables and how things should be configured. I think some improvements to [documentation](https://ray.readthedocs.io/en/latest/plasma-object-store.html#using-plasma-with-huge-pages) would be useful here.
* Example sets `/proc/sys/vm/nr_hugepages`. Does this mean `--object-store-memory` is ignored in this case and the memory is used based on `/proc/sys/vm/nr_hugepages`?
* What page size does Ray use? [For Huge Pages on Kubernetes](https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/) it seems host can expose huge pages of different sizes. Which size should be best for Ray? This probably depends on size of values being passed around?
* It would be great to have an example in documentation how to configure Ray with huge tables on Kubernetes.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.10
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5
- **Python version**: 3.6.3

**Comment by atumanov** [comment]
The documentation you linked offers an _example_ of configuring the use of hugepages system-wide. I.e., other applications, not just Ray, may have access to this pool of hugepages configured. Thus, `--object-store-memory` behaves in the same way it does without hugepages, namely, the total object store memory allocated shall not exceed the limit provided via `--object-store-memory`. The only undesirable interaction I can think of is the case when system-wide hugepages pool size is smaller than the object store memory limit specified with `--object-store-memory`.

Good question re: page size. Note that the object store will work with any mount point provided. Thus, it may work with 2MB as well as 1GB sized pages, as long as they were mounted using hugetlbfs, and the mountpoint -- provided to the plasma store on startup. This provides the flexibility for the plasma store to work with whatever existing configuration may already be in place for hugepages on the target platform.

**Comment by mitar** [comment]
Thanks for clarifications. I will make a PR adding those to documentation.

If `--object-store-memory` is not specified, will Ray use whole available space on the huge-tables mount point, or will it still depend the size based on the available memory on the node as a whole?

**Comment by ericl** [comment]
Auto-closing stale issue.

**Comment by mitar** [comment]
Hm, there was no warning that this will be closed? Generally, one first announce that an issue is stale. And close it later if nobody objects.

Anyway, this was pending answers before I could make a PR. I still think this would be useful addition to the documentation.
