### ISSUE TITLE
[RLlib] "TypeError: can't pickle _thread.lock objects"

### ISSUE THREAD

**Issue by xiaolongrenlzj** [ray-project/ray#26489]
### What happened + What you expected to happen

I'm new to Ray. Thanks for providing such a good project.

I'm trying to customize an environment based on gym.Env for Unreal Engine4. In the step() function, I need to send the action to UE4 by socket, so that the UE4 can listen to the port and make changes based on that.  The question is when I use a socketio client in the step function, I got "TypeError: can't pickle _thread.lock objects". 

Is there a way to solve this problem?

### Versions / Dependencies

ray= 1.13.0
python-socketio = 4.4.0

### Reproduction script

```
sio = socketio.Client()
class UnrealEnv(gym.Env):
     
    def __init__(self, env_config):
        super(UnrealEnv, self).__init__()
        self.action_space = gym.spaces.Discrete(5)
        self.observation_space = gym.spaces.Box(low=0, high=2, shape=(4,))
    
    def step(self, action):
        sio.emit('action2', str(cur_action))
        obs = [1,1,1,1]
        reward = 1
        done = True
        return obs, reward, done, {}
    
    def reset(self):
        self.cur_state =  [0.0, 0.0, 0.0, 0.0]
        return self.cur_state
```

**Comment by kouroshHakha** [comment]
is there a reason that you cannot create the client object inside the env?

**Comment by hora-anyscale** [comment]
Per Triage Sync: No author response, closing.
