### ISSUE TITLE
[Core] Add flag to to block `ray up` until workers are healthy 

### ISSUE THREAD

**Issue by iojw** [ray-project/ray#26499]
### Description

Currently, running the `ray up` command from a clean environment blocks until the head node is started. The worker nodes only begin launching after this, even if `min_workers` is specified. There should be a flag to `ray up` that blocks until `min_workers` worker nodes have started and are healthy.

cc @franklsf95 

### Use case

We are trying to run benchmarks on the Ray autoscaler using a script that launches a Ray cluster, then executes a script on the cluster. However, because there is no easy way of determining when all the worker nodes have started up, we have to use a script that polls `ray status` on the cluster periodically to determine when all workers have started. Having the suggested flag would allow us to accomplish this using the `ray up` command.

This is the gist of the script we currently rely on to poll the status of the autoscaler cluster:
```
while num_tries > 0:
    status = get output of running `ray exec cluster.yaml 'ray status'`
    if "no pending nodes" in status:
        print("Ray cluster is ready")
        return
    else:
        sleep for 60 seconds
    num_tries -= 1
```
Is there a better way of doing this? I think it would make sense to have a flag for `ray up` that accomplishes this, similar to the `--keep-min-workers` flag for `ray down`.

**Comment by franklsf95** [comment]
@stephanie-wang @ericl Do you think this makes sense? We can help contribute.

**Comment by ericl** [comment]
Makes sense! We could add a --wait-for-worker-nodes or something similar.
