### ISSUE TITLE
Jenkins failure with insufficient cluster resources

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#2649]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.5
- **Python version**: 2.6
- **Exact command to reproduce**: in Jenkins test.

### Describe the problem

Recently, there are many Jenkins test failures raising exception with "insufficient cluster resources". Some examples are here: 
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7267/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7313/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7443/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7441/console
https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/7444/console

@ericl reported this failure in https://github.com/ray-project/ray/pull/2581 .
### Source code / logs

```
Traceback (most recent call last):
  File "/ray/python/ray/rllib/train.py", line 118, in <module>
    run(args, parser)
  File "/ray/python/ray/rllib/train.py", line 112, in run
    queue_trials=args.queue_trials)
  File "/ray/python/ray/tune/tune.py", line 82, in run_experiments
    runner.step()
  File "/ray/python/ray/tune/trial_runner.py", line 119, in step
== Status ==
Using FIFO scheduling algorithm.

    trial.config)))
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 2 CPUs, 0 GPUs but the cluster only has 0 CPUs, 0 GPUs available. Pass `queue_trials=True` in ray.tune.run_experiments() or on the command line to queue trials until the cluster scales up. 

You can adjust the resource requests of RLlib agents by setting `num_workers` and other configs. See the DEFAULT_CONFIG defined by each agent for more info.

The config of this agent is: {"num_sgd_iter": 10, "timesteps_per_batch": 1000, "sgd_batchsize": 64, "env": "FrozenLake-v0", "num_workers": 1}
/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945
/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945
/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945
/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945
/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945
shut down callback manager
```

**Comment by guoyuhong** [comment]
Considering @raulchen 's PR https://github.com/ray-project/ray/pull/2613 which fixed the error message like `/ray/src/common/io.cc:119: Connection to socket failed for pathname /tmp/raylet42011945`, current Jenkins test failures have no this message. However, we can still find this message in the old test failures. I doubt that the driver is too fast and fails before the workers get connected. So we need a way to make the driver wait for the workers. @ericl

**Comment by ericl** [comment]
Is this the right solution here? I imagine that many times the user expects that ray.init() will ensure all the workers are up. Is it possible to add a barrier() to ray init for the workers, similar to in the legacy ray backend?

**Comment by guoyuhong** [comment]
@robertnishihara Do you have any idea of how to make the driver wait for the worker?

**Comment by robertnishihara** [comment]
@ericl @guoyuhong are you talking about making the driver wait for worker processes on the same machine to start up? Or are you talking about waiting for Ray on other machines to start up? We don't do either of these things (both in legacy Ray and the Raylet).

@ericl what assumptions does Tune make?

**Comment by ericl** [comment]
In legacy ray, ray.init(num_cpus=N) guarantees a query to Ray will return N
CPUs available.

**Comment by robertnishihara** [comment]
What kind of query are you referring to? Are you talking about `ray.global_state.client_table()`? If so, I think this behavior will be the same in both Ray and legacy Ray (in both cases, there is a brief window of time where the client table may be empty, but after that the local scheduler or raylet will be registered with N CPUs).

**Comment by guoyuhong** [comment]
@ericl I added the [code](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L1417) previously to wait until at least one raylet worker connected. But 1 CPU is not enough, right?

**Comment by ericl** [comment]
In local mode, there is only one raylet, so once it connects all the CPUs and GPUs of that node will show up simultaneously, right?

**Comment by robertnishihara** [comment]
@ericl that's right. They should all appear simultaneously.

**Comment by richardliaw** [comment]
Jenkins doesn't fail on this anymore.
