### ISSUE TITLE
Tasks that arrive before global scheduler receives any heartbeats never get scheduled.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#265]
If the global scheduler receives a task before it receives any heartbeats from the local schedulers, it will not be able to schedule that task (because there will be no local schedulers that satisfy the task's resource requirements).

This may be the source of hanging in some test cases, e.g., `testPassingInfoToAllWorkers` in https://travis-ci.org/ray-project/ray/jobs/200210187.

**Comment by atumanov** [comment]
I don't believe this has anything to do with resource requirements. This behavior was there before. If the global scheduler has no local schedulers connected, it can't assign the task to anybody. One possibility is to set its state back to WAITING, or we are going to have to start queueing tasks in the global scheduler and part with the current bufferless design...

**Comment by robertnishihara** [comment]
Good point. This was already happening whenever the global scheduler received a task before the global scheduler had registered any local schedulers. Now it is failing whenever the global scheduler receives a task before it has registered any local schedulers or before it has received any heartbeats.

**Comment by robertnishihara** [comment]
This was fixed by #306.
