### ISSUE TITLE
Observability: provide visibility into retried attempts

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#26524]
### Description

It would be great to get visibility into what happened that led to task or actor to ultimately fail, after exhausting retries, or whether retries occured that slowed down the workload.

If I set the retry count and it is used up, or if I set it to infinite retry, I would like to know what are the reasons for the failures, and when, to give me information to better root cause the issue, and possibly tweak these parameters

**Comment by rkooo567** [comment]
cc @rickyyx

**Comment by rickyyx** [comment]
Wondering why was it closed? Has the underlying retry mechanism changed so that this is no longer relevant? cc @clarng

**Comment by rkooo567** [comment]
I think we should do it for state API. Ideally by 2.1

**Comment by rkooo567** [comment]
@rickyyx will this be fixed as a part of your refactoring?

**Comment by rickyyx** [comment]
Yes, we should be able to include task retry count for each task in state api output.

**Comment by rickyyx** [comment]
We now have attempt_number in task states, multiple retry will show up as separate entries.
