### ISSUE TITLE
[Serve] [Ray Client] `serve.shutdown()` starts new Ray cluster

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#26527]
### What happened + What you expected to happen

After `ray.shutdown()` is called to disconnect from Ray Client, if you call `serve.shutdown()` a new Ray cluster is sometimes started.

`serve.shutdown()` should not create a new Ray cluster.

More details about this issue and a workaround can be found at https://discuss.ray.io/t/serve-shutdown-and-how-to-reconnect-to-cluster/6799.  The workaround is to use the private API `serve.context.set_global_client(None)`.

Calling `ray.shutdown()` followed by `serve.shutdown()` is the recommended way to disconnect from Ray Client when using Ray Serve, according to https://discuss.ray.io/t/exception-cant-run-an-actor-the-server-doesnt-have-a-handle-for/5181.

### Versions / Dependencies

This seems to be a new issue introduced in Ray 1.13.0.

### Reproduction script

```bash
ray start --head
```

```python
import ray
from ray import serve
ray.init("ray://localhost:10001")
ray.shutdown()
serve.shutdown() # This line starts a new Ray cluster.
```

A longer reproduction copied from https://discuss.ray.io/t/serve-shutdown-and-how-to-reconnect-to-cluster/6799:

```python
In [1]: import ray

In [2]: from ray import serve

In [3]: ray.init(address="ray://172.17.0.2:10001")
Out[3]: ClientContext(dashboard_url='172.17.0.2:8265', python_version='3.8.12', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', protocol_version='2022-03-16', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7ff974cd07c0>)

In [4]: serve.list_deployments()
Out[4]: {}

In [5]: ray.shutdown()

In [6]: serve.shutdown()

In [7]: ray.is_initialized()
Out[7]: False

In [8]: ray.init(address="ray://172.17.0.2:10001")
Out[8]: ClientContext(dashboard_url='172.17.0.2:8265', python_version='3.8.12', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', protocol_version='2022-03-16', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7ff974cd07c0>)

### "serve.list_deployments() is not called now"

In [9]: ray.shutdown()

In [10]: serve.shutdown()
2022-07-10 02:41:05,598	INFO services.py:1470 -- View the Ray dashboard at http://127.0.0.1:8265

### "Local cluster was created"

In [11]: ray.is_initialized()
Out[11]: True


In [12]: ray.init(address="ray://172.17.0.2:10001")
Out[12]: ClientContext(dashboard_url='172.17.0.2:8265', python_version='3.8.12', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', protocol_version='2022-03-16', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7ff974cd07c0>)

In [13]: serve.list_deployments()
Out[13]: {}

In [14]: ray.shutdown()

In [15]: serve.shutdown()
Exception: Ray Client is not connected. Please connect by calling `ray.init`.

In [16]: ray.is_initialized()
Out[16]: True

In [17]: ray.init(address="ray://172.17.0.2:10001")
Out[17]: ClientContext(dashboard_url='172.17.0.2:8265', python_version='3.8.12', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', protocol_version='2022-03-16', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7ff974cd07c0>)

In [18]: serve.list_deployments()
Caught schedule exception
Exception: Can't run an actor the server doesn't have a handle for
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simon-mo** [comment]
Ray Client is deprecated. Closing.

**Comment by sercanCyberVision** [comment]
@architkulkarni @simon-mo 
As Ray Client is deprecated, what is the alternative way to deploy an app to specific Ray Cluster now?

**Comment by architkulkarni** [comment]
You should be able to use https://docs.ray.io/en/latest/serve/api/index.html#serve-deploy and pass in the address of the dashboard of your Ray cluster.

**Comment by sercanCyberVision** [comment]
Thank you @architkulkarni, `serve deploy` what I was looking for.

There is only one issue: I am not able to use `--working-dir` option:
```
> serve deploy --address "http://kuberay-head-svc.kuberay:8265" --working-dir "./" app_config.yaml
...
Error: No such option: --working-dir
```

I saw this open issue https://github.com/ray-project/ray/issues/29354.
What is your recommendation to workaround this?
