### ISSUE TITLE
[air] Add set_preprocessor / get_preprocessor on the Predictor class

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#26528]
### Description

There is currently no way to get/set a preprocessor on a BatchPredictor / Predictor once created. This makes it very difficult to figure out how to pass a custom preprocessor to a predictor.

**Comment by amogkam** [comment]
@ericl would using to_air_checkpoint satisfy the use case?

You can create a checkpoint from a model and preprocessor and then pass that into the predictor.  cc @xwjiang2010 

https://docs.ray.io/en/master/ray-air/use-pretrained-model.html

**Comment by ericl** [comment]
What if I already have an AIR checkpoint and want to inspect or modify it?
You have to provide these kind of utility methods.

**Comment by Yard1** [comment]
We also have `load_checkpoint`. You could combine the two

**Comment by ericl** [comment]
@Yard1 I think the main issue here is discoverability. As a user, I spent upwards of 5 min trying to figure out how to do this. I would expect there to be some way to set a custom preprocessor in either Predictor directly, or if not, in Checkpoint. I think Checkpoint is the simplest change for now, since adding it to Predictor opens up some can of worms (two ways to set preprocessor).

Btw, for any object with attributes, we should make sure to have accessors (it helps to be consistent).
