### ISSUE TITLE
[AIR] Ensure TorchPredictor works with PredictorDeployment without manual conversion

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#26539]
### What happened + What you expected to happen

Currently this work for our notebooks:

```python
from ray import serve
from ray.serve import PredictorDeployment
from ray.serve.http_adapters import NdArray

def json_to_numpy(payload: NdArray) -> pd.DataFrame:
      """Accepts an NdArray JSON from an HTTP body and converts it to a Numpy Array."""
      # Have to explicitly convert to float since np.array reads as a double.
      arr = np.array(payload.array, dtype=np.float32)
      return arr

serve.start(detached=True)
deployment = PredictorDeployment.options(name="my-deployment")
deployment.deploy(TorchPredictor, latest_checkpoint, batching_params=False, model=Net(), http_adapter=json_to_numpy)
```

But ideally user shouldn't need to write another http adapter for it. We should have it fixed before AIR beta.

### Versions / Dependencies

master

### Reproduction script

https://github.com/ray-project/ray/pull/26453

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
wait, I think I have written something similar for another example:

```
from fastapi import Request

async def dataframe_adapter(request: Request):
    """Serve HTTP Adapter that reads JSON and converts to pandas DataFrame."""
    content = await request.json()
    return pd.DataFrame.from_dict(content)
```

Should this also work natively?

**Comment by jiaodong** [comment]
hmm isn't this also another custom adapter ? except this one returns pandas and the one in PR returns numpy

**Comment by jiaodong** [comment]
If you find the conversion type covered by one of the defaults in https://docs.ray.io/en/master/serve/http-adapters.html then i can be replaced by serve's built-in ones; otherwise we might need to stick with these for a bit.

I think the ideal case is for common cases we have all http adapters we need so just importing the right one is all we need ..

**Comment by xwjiang2010** [comment]
No I don't think they are covered there. But `to_numpy` or `to_pandas` seem pretty common cases to me..

**Comment by matthewdeng** [comment]
@jiaodong is this fixed?

**Comment by jiaodong** [comment]
i think it is, im not seeing any occurrence of `json_to_numpy ` in our codebase anymore. There's still a pandas one in [torch_incremental_learning.ipynb](https://sourcegraph.com/github.com/ray-project/ray/-/blob/doc/source/ray-air/examples/torch_incremental_learning.ipynb?subtree=true) tho that worth leaving this issue open until it's removed.

**Comment by jiaodong** [comment]
this is no longer the case in our notebooks, including torch_incremental_learning
