### ISSUE TITLE
[Feature][Autoscaler] Set RAY_ADDRESS env for the head pod #373

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#26542]
### Description

For deployment stacks that use node updaters (VMs and legacy K8s operator), have the autoscaler automatically set the following env for the head node
RAY_ADDRESS=localhost:<ray-head-port>

The effect of this is simply to allow connecting to Ray via ray.init() rather than ray.init("auto").

### Use case

Simplifies connecting to Ray.

**Comment by DmitriGekhtman** [comment]
cc @pcmoritz

**Comment by jjyao** [comment]
Make sure we set that for worker pods as well since driver can run on any node.

**Comment by DmitriGekhtman** [comment]
you are right...However, I am starting to think it'd be better simply to modify the `ray.init()` semantics and avoid messing with the env variables

**Comment by DmitriGekhtman** [comment]
Solved.
