### ISSUE TITLE
Find better default A3C hyperparams

### ISSUE THREAD

**Issue by luochao1024** [ray-project/ray#2654]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0
- **Python version**: 3.5.1
- **Exact command to reproduce**: 

### Describe the problem
 
I try to run A3C on different atari environments including BreakoutDeterministic-v4, SpaceInvadersDeterministic-v4, QbertDeterministic-v4. The command I use is

` python/ray/rllib/train.py --env=BreakoutDeterministic-v4 --run=A3C --config='{"num_workers": 16}'.
`

It seems like this command only works for Pong. When it comes to other atari games, it does not work.

After 3 hours trainning, the `episode_reward_mean `for Breakout can not exceed 10 and the `episode_reward_mean `for Qbert can not exceed 600. As for SpaceInvaders, the `episode_reward_mean `is always between 100 and 300. 

Does anyone successfully run A3C on any other environment except Pong on Ray? Can you share the configs with me?

**Comment by ericl** [comment]
cc @richardliaw

**Comment by ericl** [comment]
Won't fix -- A2C is probably the way to go in the future.
