### ISSUE TITLE
[RLlib] OPE QReg needs to be fixed

### ISSUE THREAD

**Issue by kouroshHakha** [ray-project/ray#26544]
### What happened + What you expected to happen

Q regression model assumes that the incoming data has an episodic structure which is not true in something like DQN algorithm when time-steps are shuffled and passed to the `estimator.train(batch)`.  We either have to enforce this requirement some how and error out when it's violated, or fix our estimator to take care of this issue. 

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by Rohan138** [comment]
Per discussion with @avnishn and @kouroshHakha, we're removing Q-Reg in #26279
