### ISSUE TITLE
[RLlib Release Tests] Learning Tests a-e and f-z are failing 

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#26579]
### What happened + What you expected to happen

learning tests should be passing.

### Versions / Dependencies

Master

### Reproduction script

n/a

**Comment by ArturNiederfahrenhorst** [comment]
Related: #26674, #26150 , #26152 and #26153.

**Comment by avnishn** [comment]
closed via https://github.com/ray-project/ray/pull/26586

**Comment by scv119** [comment]
looks there are new failures: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_zq3nnVGSB7d6cV7dm7Wsa788?command-history-section=command_history
