### ISSUE TITLE
[autoscaler/Feature Request] Add support for nvidia-docker for autoscaler

### ISSUE THREAD

**Issue by matthew-z** [ray-project/ray#2657]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5
- **Python version**: 3.6
- **Exact command to reproduce**:

 
### Describe the problem
It seems that `autoscaler` installs `docker` only at this moment, so it is difficult to passthrough GPU to the container. I think it will be great to add support for [`nvidia-docker`](https://github.com/NVIDIA/nvidia-docker).

The implementation should be straightforward. E.g., 

if `config["docker]["nvidia_docker"] == True`, `docker_install_cmds` function installs both docker and nvidia-docker. Then, modify `docker_run ` in `docker_start_cmds` for nvidia-docker to run nvidia-docker with the additional argument `run --runtime=nvidia`:

```    
docker_run = [
        "docker" , 
       "run --runtime=nvidia" if nvidia_docker else "run" ,  
       "--rm", "--name {}".format(cname), "-d", "-it",
       port_flags, mount_flags, env_flags, "--net=host", image, "bash"
    ]
```

**Comment by richardliaw** [comment]
Thanks for opening this issue! 

I agree that using nvidia-docker would be great to support. Would you be open to contributing this feature?

**Comment by matthew-z** [comment]
Sure. I will try to send a PR.
