### ISSUE TITLE
The @ray.remote decorator breaks Sphinx autoclass extension.  

### ISSUE THREAD

**Issue by martisak** [ray-project/ray#2658]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.5
- **Ray installed from (source or binary)**: both
- **Ray version**: 0.5.0
- **Python version**: Python 2.7.10
- **Exact command to reproduce**: See below.

### Describe the problem

Ray decorators breaks Sphinx autoclass extension.

If a class is decorated and documented using docstrings, documentation is not generated. The `MyClass` class can still be imported by Sphinx.

```
@ray.remote(num_gpus=1)
class MyClass(object):
    """ lorum ipsum """

...
```

I use the [Sphinx extension `sphinx.ext.autodoc`](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-automodule) to build my documentation.

See also [Civilize your Python @decorators](https://adambard.com/blog/civilize-your-python-decorators/)

### Source code / logs

To reproduce this issue, run the following inside a `virtualenv` or similar:

```
git clone git@github.com:martisak/ray_decorator_issue.git 
pip install -r requirements.txt
make html
```

Then open `build/html/index.html` in your favorite browser, which should look like the following.

![screenshot](https://github.com/martisak/ray_decorator_issue/raw/master/screenshot.png)

**Comment by richardliaw** [comment]
cc @robertnishihara

**Comment by robertnishihara** [comment]
Hi @martisak thanks for pointing that out!

I think it's just a matter of adding a line like `self.__doc__ = function.__doc__` in the constructor

https://github.com/ray-project/ray/blob/53f975559410918d0b7bbf1832ec5f339d652686/python/ray/remote_function.py#L47-L70

Would you be interested in submitting a PR and adding a test for this?

**Comment by martisak** [comment]
Hi @robertnishihara!

Unfortunately that didn't work, and neither did any of my other attempts. :(. 

If I add the line above, and do `print(self.__doc__)` then for a class nothing is printed or visible in the output.

It is however printed for a normal function such as the one below, but this function is not visible in the Sphinx output at all! 

```
@ray.remote
def myfunction(a):
    """
    This is my decorated function.

    :param a: A number
    :type a: int
    :returns: One more than a
    """

    return a + 1
```

**Comment by jsuarez5341** [comment]
Hi @robertnishihara -- just ran into the old issue myself today. Any ideas on how to fix it? Unless I'm missing an obvious workaround, this makes it pretty hard to get ray onto readthedocs

**Comment by robertnishihara** [comment]
@pcmoritz and @simon-mo you guys looked into this issue, right? Any thoughts about the best way to fix this for actors?

**Comment by simon-mo** [comment]
some combination of `wraps` and overriding `__doc__`, `__signature__` should do it.

**Comment by ericl** [comment]
Auto-closing stale issue.

**Comment by sofietorfs** [comment]
I'm using ray version 0.8.2 and python version 3.6.9 and I am experiencing the same problem.
I'm quite new to python and sphinx, so I don't understand the solution. Would it be possible for someone to explain it for me?

**Comment by IanAtDazed** [comment]
Is there a solution / work-around for this? Or is it not possible to use Sphinx autoclass for classes decorated with @ray.remote ?

**Comment by richardliaw** [comment]
One workaround would be to call ray.remote explicitly:
```
class ActorClass:
    pass

RemoteActorClass = ray.remote(ActorClass)

actor = RemoteActorClass.remote()

```
