### ISSUE TITLE
[air] Improvements to XGBoost Benchmarking script

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#26612]
- Could we have separate scripts for training and prediction? This is for readability: it's not great to have multiple workflows in the same script.
- Should make `@run_and_time_it` a common util
- `to_air_checkpoint(".", model)` <--- isn't the "." fishy?
- `batch_predictor.predict(ds.drop_columns(["labels"]))` <--- I think you can use the "feature_columns" arg of predict() that Amog added, instead of dropping labels.

_Originally posted by @ericl in https://github.com/ray-project/ray/pull/26608#pullrequestreview-1040785535_

**Comment by ericl** [comment]
Can we do this before merging https://github.com/ray-project/ray/pull/26608/files#diff-b16a9d2f3b7dc91a450950c3b85d726ebea905cfe1b3d45d757d2ff2b4fe61d5 ?

It should just take a few minutes.
