### ISSUE TITLE
[data] Enable fusion of read->write stages

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#26620]
### Description

Currently, stage fusion cannot fuse read to write stages (e.g., read->write, or read->map->write), since the write method of datasources does not support fusion with previous stages.

For batch prediction, this is usually OK since model output is relatively small, so there is little benefit from fusion. However in some scenarios where map output is large, this could improve efficiency substantially.

Fixing this issue would require changing the Datasource write API to generate write tasks that can be fused with previous read stages (converted to map_batches(do_write)).

cc @c21 @clarkzinzow

**Comment by c21** [comment]
It's done in master. Closing.
