### ISSUE TITLE
[core] Add API to get allocated resources in remote trainable

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#26658]
### Description

It would be great to be able to retrieve the number of allocated resources from within a remote task/actor:

```
@ray.remote(num_cpus=2, num_gpus=1)
def test_resources():
    assert get_available_resources()["CPU"] == 2
    assert get_available_resources()["GPU"] == 1

assert ray.get(test_resources.remote())
```

### Use case

In XGBoost-Ray and LightGBM-Ray we set the number of threads the native boosting libraries can use to the number of CPUs available to the actor. We currently use the deprecated API `ray.worker.get_resource_ids()` for that.

We can pass the allocated resources to the actor constructors, but it would be better to just query the source of truth. Also it would mean for tasks and actor constructors to have to accept more arguments. This feature is thus particularly useful for actors with dynamic or configurable resource specs (e.g. an AIR scaling config).

**Comment by rkooo567** [comment]
cc @scv119 I believe we don't have the corresponding API right now after the deprecation, and I think we should have one. I will mark it as a high priority item (P1).

**Comment by krfricke** [comment]
Just for planning, do we expect to get this in for 2.0 or not? If not we will try to find a workaround in the downstream libraries before release

**Comment by rkooo567** [comment]
We don't have a plan to support it before 2.0. What's the side effect of not doing this by 2.0?

**Comment by rkooo567** [comment]
and what's the workaround?

**Comment by rkooo567** [comment]
Closed via https://github.com/ray-project/ray/pull/26907/files
