### ISSUE TITLE
[RLlib] can't find ray.rllib.algorithms

### ISSUE THREAD

**Issue by AmmarRashed** [ray-project/ray#26660]
### What happened + What you expected to happen

Trying to run the following file with default args
https://github.com/ray-project/ray/blob/master/rllib/examples/two_step_game.py

ModuleNotFoundError: No module named 'ray.rllib.algorithms'

### Versions / Dependencies

ray 1.6.0
tensorflow 2.9.0

### Reproduction script

same as https://github.com/ray-project/ray/blob/master/rllib/examples/two_step_game.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by sharp-productions** [comment]
I think the issue is more widespread than two_step_game.py.  The issue appears to affect any file in that directory using `ray.rllib.algorithms`.  I also checked carpole_lstm.py, centralized_critic.py, and rock_paper_scissors_multiagent.py.  All exhibit the same behavior.

**Comment by sharp-productions** [comment]
Git bisect implies issue was introduced by https://github.com/ray-project/ray/commit/3815e52a61b6afe44b883d7d745fa00b599f66ca.

**Comment by sharp-productions** [comment]
It's still in the repo.  QMixConfig is located [here](https://github.com/ray-project/ray/blob/257e67474cbdaed3acf9049d27a6e540dd822f94/rllib/algorithms/qmix/qmix.py#L29).

**Comment by AmmarRashed** [comment]
> 

Yeah, but how to import it if "algorithms" is not found?
and even if you import ray.rllib.agents.qmix it is not there.

**Comment by mvindiola1** [comment]
@AmmarRashed @sharp-productions

Which version of Ray are you using? 

Master has changed significantly in preparation for the next release. You either need to look at the version with the tag of your installed release version or you need to install the nightly wheels.

**Comment by sharp-productions** [comment]
Awesome, thanks!

**Comment by kouroshHakha** [comment]
Yes, the solution to this problem is to update to the latest ray version.

**Comment by xiaoToby** [comment]
> Yes, the solution to this problem is to update to the latest ray version.

hello, I met the same problem. I want to know which version is to solve this problem. My version now is ray==1.13.0. I think it is the latest version now.

**Comment by kouroshHakha** [comment]
@xiaoToby Oh sorry if I wasn't clear. This is resolved on master which will be released in ray 2.0. You can either install master (by building ray locally), or pip install the release candidate (`pip install ray["rllib"]==2.0.0rc0`). If for some reason you need 1.13 you can use the old location of the algorithms which was in `rllib.agents` (so `rllib.agents.qmix` instead of `rllib.algorithms.qmix`)

**Comment by xiaoToby** [comment]
> 
thank you for your message!

**Comment by xiaoToby** [comment]
> @xiaoToby Oh sorry if I wasn't clear. This is resolved on master which will be released in ray 2.0. You can either install master (by building ray locally), or pip install the release candidate (`pip install ray["rllib"]==2.0.0rc0`). If for some reason you need 1.13 you can use the old location of the algorithms which was in `rllib.agents` (so `rllib.agents.qmix` instead of `rllib.algorithms.qmix`)

Thank you for your message!
