### ISSUE TITLE
[Serve] [CI] `windows://python/ray/serve:test_standalone2` is failing/flaky on master.

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#26664]
- 12825fc5aa0d98f49d121ec46507b25d1d3e2f82 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/ray-builders-branch/builds/8704#01820e84-0fab-4f68-b21f-1294e743253a)
- 569fe0109629048d08e1d9e023f7769f10bd2244 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/ray-builders-branch/builds/8701#01820de3-0647-492c-81eb-db1992516019)
- feb53d01ab718070584941d43a30e411cf72f5bf FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/ray-builders-branch/builds/8699#01820a70-b964-402b-aced-91214611c829)
- 988ffd494b6bcdf5d06463036e1728c534bab624 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/ray-builders-branch/builds/8684#0182079b-a47f-4e10-ac51-41074775da6f)
- fb54679a239e4c7368a72a2fe3023cac04380827 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/ray-builders-branch/builds/8683#018206d8-0c96-4a77-bf07-e764a3f87d69)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/serve:test_standalone2-END
....

**Comment by architkulkarni** [comment]
<img width="1746" alt="Screen Shot 2022-07-18 at 10 40 35 AM" src="https://user-images.githubusercontent.com/5459654/179570559-5e43cd02-905b-4db9-885f-4a860dcf11e9.png">
Unfortunately it gradually became flaky so it's not obvious which PR made it flaky.

It's timing out, but not always on the same test.  E.g. [here](https://buildkite.com/ray-project/ray-builders-branch/builds/8684#0182079b-a47f-4e10-ac51-41074775da6f/4220-5143) it times out on `test_update_num_replicas`, but in a couple of other failures it times out on `test_serve_namespace`

**Comment by simon-mo** [comment]
@architkulkarni can you open a PR to skip this test for now on Windows? The failing tests are mostly about working with multi-node and multi-node isn't supported workflow on Windows.

**Comment by architkulkarni** [comment]
Sure, I'll open a PR.  Didn't know multi-node wasn't supported on Windows
