### ISSUE TITLE
[RLlib] Learning Release Test

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#26674]
### What happened + What you expected to happen

For learning tests, we are probably not gonna fix all the long-standing learning related issues.
But should we give those important algorithms like APPO torch one more push?

### Versions / Dependencies

Master Head.

### Reproduction script

see releases/rllib/learning_test/

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
#26579 related
