### ISSUE TITLE
[Datasets] Raise descriptive error when expired AWS credentials are used

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#26672]
### Description

When using `ray.data.read_parquet` with S3 credentials that are expired, the error message is extremely uninformative and makes it sound like there is a bug in Ray Datasets (similar to https://github.com/ray-project/ray/issues/24184 and https://github.com/ray-project/ray/issues/19799).

The error message should clearly state that the AWS credentials are expired and the user needs to set valid credentials to read data from S3.

This happens even if the `anonymous` user is used for reading from S3, since pyarrow loads the credentials regardless.

**Comment by pcmoritz** [comment]
@dmatrix Can you add the error message here?

**Comment by dmatrix** [comment]
with `anonymous`

```
ds = ray.data.read_parquet([
    "s3://anonymous@ursa-labs-taxi-data/2009/01/data.parquet",
    "s3://anonymous@ursa-labs-taxi-data/2009/02/data.parquet",
])
```

```
File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When reading information for key '2009/02/data.parquet' in bucket 'anonymous@ursa-labs-taxi-data': AWS Error [code 100]: No response body.

```
And without the `anonymous`

# Read two Parquet files in parallel.
```
ds = ray.data.read_parquet([
    "s3://ursa-labs-taxi-data/2009/01/data.parquet",
    "s3://ursa-labs-taxi-data/2009/02/data.parquet",
])
```

 ```
File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: Error creating dataset. Could not read schema from 'ursa-labs-taxi-data/2009/01/data.parquet': When reading information for key '2009/01/data.parquet' in bucket 'ursa-labs-taxi-data': AWS Error [code 100]: No response body.. Is this a 'parquet' file?
```
