### ISSUE TITLE
[ML][nighly-test] Train_horovod_multi_node_test is failing 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26720]
### What happened + What you expected to happen

this is a release blocker, please triage.

### Versions / Dependencies

latest ray

### Reproduction script

https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=eEV0-NhAr6leVqaXtREv9Dac9epk5cVV-ZIJm-27j0EUa9wjk6jlLBxz_olU2qTM

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
Sorry this passed today; we can close this. (Closed the wrong test).

**Comment by richardliaw** [comment]
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_BrvUPqWndghFkzZaG35YDuqE
