### ISSUE TITLE
[Serve][nightly test]  Serve_single_deployment_1k_noop_replica is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26723]
### What happened + What you expected to happen

This is a release blocker, please investigate and triage.

### Versions / Dependencies

latest ray

### Reproduction script

https://docs.google.com/document/d/17hK2ZAEGRgF-JIticPSBZYumoTMQby7D8891KbVAVsM/edit#

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
seems to recovered by itself. 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/21118851/180516653-3499b957-c159-435b-8998-8f508907405e.png">
