### ISSUE TITLE
[Datasets] Revamp the release/nightly_tests/dataset/pipelined_training.py

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#26733]
This test tries to simulate the real workload from users. Right now it's a bit off and we need to make the setup more realistic.

Some feedbacks:
- The batch size 250k is too large: 8-50k is more close to real case
- Need larger number of files: currently we run at about 1000 files, but we'd stress it up to 20k files
- Need larger number of columns: e.g. 200 double columns, or 2 vector columns with each containing 100 doubles
- TiB size in-memory data
- File decompression inflation: e.g. 500MiB on disk file exploded to 150GiB in-memory data, leading to OOM
- machine type: 180GiB or 100GiB memory sized machines are more realistic -- using large instance may not simulate well
- Run a validation pipeline interleaved with training pipeline

**Comment by heyitsmui** [comment]
@yuduber @chongxiaoc @irasit, @jianoaix is trying work on benchmarking Ray datasets, including creating similar workloads like Uber. Can you guys take a look at this and provide some guidance? Thanks!

**Comment by irasit** [comment]
@yuduber Please share our stress testing setup with Jian.

**Comment by yuduber** [comment]
The test is defined in uber ml-code project under the folder:
/ml-code/platforms/maps/postprocessing/deepeta/pipelines/v5/experiments/rayhete_perf/

The preliminary results are like below:
DeepETA v5
----------
The folder contains two projects that are used to determine the baseline and stressed performance of ray heterogenous cluster.

The baseline used V6 prod model
The stressed used branch yud-unmodETACal/v1 ml-code/platforms/maps/postprocessing/deepeta/pipelines/v5/experiments/unmod_correction_features/treatment_unmod_bias_scalar_count_errvector_fewerfeatures/app_def.yaml

Both tests have fixed dataset and model specification.

These tests are manually run when we see major ml-code / pipeline config change.

We run them and try to capture time spent for different code block in train step.

After such manual run, we update the duration of each stage in each steps to keep track of the performance.

These e2e workflow is not run regularly because it is very resource intensive.

Performance summary:
2022/08/24
raw data: https://t3.uberinternal.com/browse/MA-17430

SUMMARY:

    BASELINE RUN:
        Dataset and columns:
            'needed_cols': 
                ['derived_geohash_begin_6_fh21', 'derived_geohash_end_7_fh18', 'derived_estimated_distance_m_after_QuantileDiscretizer_0', 'derived_unmodified_eta_sec', 'derived_geohash_begin_7_fh18', 'derived_haversine_distance_after_QuantileDiscretizer_0', 'ata_sec', 'derived_geohash_od_65shift_fh21b', 'derived_historical_seconds_after_QuantileDiscretizer_0', 'derived_estimated_distance_m', 'derived_map_data_vendor', 'derived_unmodified_eta_sec_after_QuantileDiscretizer_0', 'derived_weight_day_of_prediction', 'derived_umm_default_and_limit_seconds_ratio_after_QuantileDiscretizer_0', 'derived_geohash_od_65_fh21', 'derived_geohash_end_6shift_fh21b', 'indexed_derived_geohash_begin_5', 'derived_geohash_end_6_fh21', 'derived_minute_of_week', 'indexed_derived_geohash_begin_4']
            train:
                'total_mem_dataset_size': 1630547511024.0,
                'sum_file_sizes': 1546406457494,
                'total_files': 10742,
                'rowgroup_cnt': 21484,
                'n_row': 5994659967,
                'sum_row_group_n_row': 5994659967,
            val
                'total_mem_dataset_size': 64037335360.0,
                'sum_file_sizes': 48851902486,
                'total_files': 433,
                'rowgroup_cnt': 861,
                'n_row': 235431380,
                'sum_row_group_n_row': 235431380,
        Execution Duration break down:
            Repartition train dataset: N/A
            ParquetDataStats trainer dataset: 2059s
            ParquetDataStats val dataset: 75s
            Provision Ray Cluster: 1:47:00
            get_all_stats_from_dir using ray cluster: 39:45
            Ray.data prepare first window: 1:31:50
            Train on GPU: 4:37:00

    STRESS RUN:
        Dataset and columns:
            'needed_cols': 
                ['derived_geohash_begin_6_fh21', 'derived_geohash_end_7_fh18', 'derived_estimated_distance_m_after_QuantileDiscretizer_0', 'derived_unmodified_eta_sec', 'derived_geohash_begin_7_fh18', 'derived_n_observations_3_after_QuantileDiscretizer_0', 'derived_haversine_distance_after_QuantileDiscretizer_0', 'derived_n_observations_1', 'derived_n_observations_4', 'derived_geohash_od_65shift_fh21b', 'derived_umm_default_and_limit_seconds_ratio_after_QuantileDiscretizer_0', 'derived_geohash_od_65_fh21', 'derived_p50_unmod_err_4', 'derived_geohash_end_6shift_fh21b', 'derived_p50_unmod_err_2', 'indexed_derived_geohash_begin_5', 'derived_geohash_end_6_fh21', 'derived_minute_of_week', 'derived_p50_unmod_err_1_after_QuantileDiscretizer_0', 'indexed_derived_geohash_begin_4']
            train:
                'total_mem_dataset_size': 2219052109848.0,
                'sum_file_sizes': 552951168236,
                'total_files': 3000,
                'rowgroup_cnt': 3000,
                'n_row': 5660847219,
                'sum_row_group_n_row': 5660847219,
            val
                'total_mem_dataset_size': 64707944504.0,
                'sum_file_sizes': 53098518004,
                'total_files': 3514,
                'rowgroup_cnt': 3514,
                'n_row': 165071287,
                'sum_row_group_n_row': 165071287,
        Execution Duration break down:
            Repartition train dataset: 15:00
            ParquetDataStats trainer dataset: 1759s
            ParquetDataStats val dataset: 2159s
            Provision Ray Cluster: 22:30
            get_all_stats_from_dir using ray cluster: 14:50
            Ray.data prepare first window: 1:26:44
            Train on GPU: 7:02:00

**Comment by jianoaix** [comment]
Thank you folks. Can you help generate the *synthetic* input data that share similar characteristics as real data? We can upload it to S3 (e.g. today it's using randomly generated data at: 3://shuffling-data-loader-benchmarks/data/r10_000_000_000-f1000) and then use in this benchmark.
