### ISSUE TITLE
TypeError: 'NoneType' object is not callable in _resume_span in tracing_helper.py

### ISSUE THREAD

**Issue by rohan-r-kulkarni** [ray-project/ray#26740]
### What happened + What you expected to happen

I am writing a PPO training algorithm in RLlib on my custom environment. Everything works fine and increasing rewards are observed over training runs, but at the end of my script, I get the following error:
Exception ignored in: <function RolloutWorker.__del__ at 0x7f987c5da430>
Traceback (most recent call last):
  File "/opt/conda/envs/AstroCraft/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
I fixed this error myself by going into the source code of ray/util/tracing/tracing_helper.py lines 461 and 493, changing the conditional statement from
**if  not is_tracing_enabled() or _ray_trace_ctx is None:**
to
**if  _ray_trace_ctx is None or not is_tracing_enabled():**
This allows for short-circuiting of the _ray_trace_ctx, what I think is the NoneType object, and the algorithm runs smoothly.

### Versions / Dependencies

Ray 1.13.0
Python 3.8.13
Mac OS X

### Reproduction script

if  not is_tracing_enabled() or _ray_trace_ctx is None:

### Issue Severity

Low: It annoys or frustrates me.

**Comment by kouroshHakha** [comment]
Repeated issue: #26250
