### ISSUE TITLE
[core] Scheduling actors that shouldn't be placeable

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#26751]
### What happened + What you expected to happen

Imagine I have a 1-cpu cluster. I schedule a. `ray.remote(num_cpus=1)` actor. Now there are no available resources. Now I schedule an actor with `@ray.remote(num_cpus=None)`. There shouldn't be placement resources!!! Should there?

### Versions / Dependencies

Ray 1.13

### Reproduction script

```
import ray

ray.init(num_cpus=1)

@ray.remote
class Actor:
    def __init__(self):
        pass


    def ping(self):
        pass


temp = Actor.options(num_cpus=1).remote()
ray.get(temp.ping.remote())

print(ray.available_resources())

a = Actor.remote()
ray.get(a.ping.remote())
```

**Comment by zhe-thoughts** [comment]
@wuisawesome  I need your help triage this. What should be the priority? Thanks!

**Comment by anyscalesam** [comment]
I can no longer repro; closing.
