### ISSUE TITLE
[Core] Automatic adjustment of plasma-object-memory

### ISSUE THREAD

**Issue by Hoeze** [ray-project/ray#26795]
### Description

Would it be possible to automatically adjust the worker memory / object store memory fraction?

`ray.put()` should know how much memory it allocates.
Therefore, `ray` could simply adjust the ratio between object store memory and worker memory on the fly.

### Use case

I would like to use ray for spawning a `spark` cluster using `raydp`.
Here, I would like to run one large Spark executor on each node which takes all available cores and memory.
It is not necessary to have any (large) Plasma object store on these nodes.

**Comment by jjyao** [comment]
@Hoeze Could you set `--object-store-memory` when you start the worker nodes if you know you don't need that much of object store memory.
