### ISSUE TITLE
[tune] Cluster cannot handle lost machine

### ISSUE THREAD

**Issue by matthew-z** [ray-project/ray#2682]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.0
- **Python version**: 3.6
- **Exact command to reproduce**:
 
### Describe the problem
I created a cluster with autoscaler on AWS with this yaml config: https://gist.github.com/matthew-z/b5ff1ae4c9ecfb5cfe6c2b13001ea963 to run the hyperband example:
https://gist.github.com/matthew-z/45d444e9bb3c7b8297a8d154bef917c2

It works well at the beginning, but I want to check if the cluster can tolerant fault. I manually deleted a worker (like terminating a spot machine), then the main process printed the following error messages infinitely: 

> The actor with ID dffefae78689e169cd227cf78efba3bebf1e5981 is taking a while to be created. It is possible that the cluster does not have enough resources to place this actor (this may be normal while an autoscaling is scaling up). Consider reducing the number of actors created, or increasing the number of slots available by using the --num-cpus, --num-gpus, and --resources flags. The actor creation task is requesting 0 GPU 1 CPU
> Suppressing duplicate error message.
> Suppressing duplicate error message.
> Suppressing duplicate error message.
> Suppressing duplicate error message.
> ......

Also, I tried the same script on GCP and it has a similar issue.  I am not sure it if I missed something or it is a bug. 

### Source code / logs

Log: https://gist.github.com/matthew-z/30b03419ab9c78dd1cf1f208e7fd17e8

Global/Local Scheduler: https://gist.github.com/matthew-z/255f76ea469794259cbc28111728dec7

Monitor: https://gist.github.com/matthew-z/4734d5eab6e8d186b58540c13ebc4239

**Comment by matthew-z** [comment]
OK.....I guess currently the legacy global_scheduler doesn't handle Actor reconstruction correctly, but it seems that the remote function works well in this situation.

Look forward to raylet.

**Comment by matthew-z** [comment]
BTW, I noticed that if I call `ray stop` on worker node to disconnect a running worker from the header, the lost actor will be reconstructed correctly on another worker to continue the job.

However, if I disable the internet interface of the worker node directly, the actor cannot be reconstructed.

**Comment by ericl** [comment]
I believe this is expected since actor fault tolerance is not implemented in the legacy backend.

In the new backend there should be a way to turn this off @robertnishihara so that tune can recover the trials.

**Comment by matthew-z** [comment]
Thank you for the explanation. 

Yes, one of the reasons is that the legacy backed does not reconstruct an actor. However, I tried raylet and it does not show anything and hang in `ray.wait`.

I think the other problem is that `ray.wait` does not trigger reconstruction and simply hang there if a worker is dead. See #2691

**Comment by matthew-z** [comment]
BTW, it seems that currently raylet does not reconstruct the dead actor.

[The simple script](https://gist.github.com/matthew-z/b6c8aad8e13db686c7c80b1ba633bd74) raises the following error after I stop the worker node.

> Traceback (most recent call last):
>   File "/Users/zzh/PycharmProjects/tensorflow_learn/ray_playground/remote.py", line 26, in <module>
>     print(ray.get(s))
>   File "/usr/local/var/pyenv/versions/anaconda3-4.1.1/lib/python3.6/site-packages/ray/worker.py", line 2493, in get
>     raise RayGetError(object_ids, value)
> ray.worker.RayGetError: Could not get objectid ObjectID(01000000059524a0edb21ddc9a6242d905e19786). It was created by remote function <unknown> which failed with:
> 
> Remote function <unknown> failed with:
> 
> Invalid return value: likely worker died or was killed while executing the task.
>

**Comment by robertnishihara** [comment]
Actor fault tolerance actually is implemented in the legacy backend, but the behavior is to reconstruct the actor from the start (and replay all of its tasks), which isn't always possible if there are no resources available (e.g., GPUs) and it may take too long to be practical. There is support for checkpointing as well, but it is experimental.

The new approach introduces exceptions at the application level so that applications can decide how to handle actor failures, which should be more practical. Ultimately we will probably combine elements of these approaches.

**Comment by richardliaw** [comment]
Killing nodes should now be supported properly (and is tested) with #3238.
