### ISSUE TITLE
[Core] Ray cluster will crash after the program is executed several times

### ISSUE THREAD

**Issue by KepingYan** [ray-project/ray#26825]
### What happened + What you expected to happen

This crash occurs after the code runs several times:
```bash
Shuffle Map:  25%|██████████▍                              | 51/201 [00:01<00:01, 85.57it/s]
(pid=gcs_server) E0721 13:23:42.286716015 1531938 tcp_server_posix.cc:213]    Failed accept4: Too many open files
Shuffle Map:  77%|██████████████████████████████         | 155/201 [00:01<00:00, 306.09it/s]
```
Then I look into `/tmp/ray/session_latest/logs/gcs_server.err`, and its content is also:
```bash
E0721 13:23:42.286716015 1531938 tcp_server_posix.cc:213]    Failed accept4: Too many open files
```
This problem may be related to [[tune] A worker dies after 1000 samples](https://github.com/ray-project/ray/issues/11309), So I used 'ulimit -n xx' based on the comments. When I set 'ulimit -n 1024', the crash happens on the fourth run, and when I set 'ulimit -n 2048', the crash happens on the sixth run. It seems ulimit doesn't solve my problem very well. 

I also checked the number of files via `lsof| wc -l`(ulimit -n 1024). Just after the cluster is started, the number is `17778`. It increments after every execution, and after the third execution it is `47741`, then it crashes the fourth time.

Before it crashes, the number of files can decrease after about 10 minutes wait, and the code can execute successfully next time.

### Versions / Dependencies

Ray1.12.0/Ray 1.13.0
Python 3.8

### Reproduction script
```python
import ray
ray.init(address="auto")
line = 55423856
ds = ray.data.range(line) 
ds.repartition(24, shuffle=True)
```

**Comment by jjyao** [comment]
> Before it crashes, the number of files can decrease after about 10 minutes wait, and the code can execute successfully next time.

@KepingYan Sorry for the late response. Is my understanding correct that we don't have permanent file descriptor leak but just it's too slow to be recycled?

**Comment by jjyao** [comment]
Also I was not able to reproduce this issue. I ran the script 50+ times.

**Comment by KepingYan** [comment]
> > Before it crashes, the number of files can decrease after about 10 minutes wait, and the code can execute successfully next time.
> 
> @KepingYan Sorry for the late response. Is my understanding correct that we don't have permanent file descriptor leak but just it's too slow to be recycled?

Maybe, I set a large number for ulimit to avoid this problem. Thx.
