### ISSUE TITLE
[Ray Dashboard] Add which node is head node

### ISSUE THREAD

**Issue by triciasfu** [ray-project/ray#26835]
### Description

- on the main page, add which node is head node [See below] 
![image](https://user-images.githubusercontent.com/5885045/180273508-4695b801-987e-418e-bc00-08526031bc9e.png)

- Not sure what the current behavior of the ant dashboard but would be nice if we could pin the head node as the first row

**Comment by alanwguo** [comment]
@rkooo567, 

Is this data easily accessible from GCS?

**Comment by rkooo567** [comment]
It's not easily accessible. You might need to tweak core to get make it work. Or you can simply finding it by matching the IP address within the API server to one of available nodes (however, there is a few cases it doesn't work)

**Comment by rkooo567** [comment]
The top entry is always the head node now. Closing the issue.

**Comment by rkooo567** [comment]
We also need better identifier of the head node. @triciasfu suggested something like `ip-172-31-111-156 (Head)`.
