### ISSUE TITLE
[RLlib] R2D2(LSTM) not working with zero_init_states False and burn_in 0

### ISSUE THREAD

**Issue by Manuscrit** [ray-project/ray#26833]
### What happened + What you expected to happen

The sample batches sent for training get the batch size of their states_in wrong some of the time. This seems to be caused by `timeslice_along_seq_lens_with_overlap`. 

### Versions / Dependencies

RLlib 1.12
PyTorch 1.13 (MacOS M1) 

### Reproduction script

A temporary solution is to use 
"zero_init_states": True
Or to use 
"burn_in" > 0

Here are possible fixes to apply around this:
https://github.com/ray-project/ray/blob/1aad5d21364893ab072c680cb59df20a8241dea3/rllib/policy/rnn_sequencing.py#L499

Best guess fix:
```
                if begin == 0:
                    data[key] = np.zeros_like(sample_batch[key][0:1])
                else:
                    data[key] = sample_batch["state_out_{}".format(i)][begin - 1 : begin]
```
Maybe the right change is to also replace `begin` by `slice_begin`?

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by kouroshHakha** [comment]
Hello @Manuscrit, can you provide a repro script? Thanks.
