### ISSUE TITLE
[ML][Nightly test] investigate Train_horovod_multi_node_test failure 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26839]
### What happened + What you expected to happen

looks latest run of train_horovod_multi_node_test failed
[https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqey[…]iw8usrQ57b1M9Y?command-history-section=command_history](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_PJhVcb8q71iw8usrQ57b1M9Y?command-history-section=command_history)

### Versions / Dependencies

latest ray

### Reproduction script

run nightly test

### Issue Severity

High: It blocks me from completing my task.

**Comment by jiaodong** [comment]
ah looks like Matt was already on it :) I locally verified this test passed on my workspaces and closing the issue.
