### ISSUE TITLE
[Datasets] Avro and TF.records support  

### ISSUE THREAD

**Issue by daikeshi** [ray-project/ray#26843]
### Description

For better integration with existing data ecosystem, is it possible to support IO for avro and tf.records data storage format? 

### Use case

We have a lot of existing raw feature datasets stored as Avro and TF.recoerds, and it would be nice if Ray dataset can support these two formats.

**Comment by daikeshi** [comment]
cc @martinbomio

**Comment by clarkzinzow** [comment]
@matthewdeng TFRecords are now supported, should we rescope this to Avro support?
