### ISSUE TITLE
Issue on page /cluster/kuberay.html

### ISSUE THREAD

**Issue by KastanDay** [ray-project/ray#26864]
When following the Kuberay example documentation (to launch Kuberay in minikube) I get this error: 
```
The CustomResourceDefinition "rayclusters.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

To reproduce, follow the instructions exactly in /cluster/kuberay.html

```
$ kubectl apply -k "ray/python/ray/autoscaler/kuberay/config/default"

Error: 
namespace/ray-system unchanged
customresourcedefinition.apiextensions.k8s.io/rayservices.ray.io configured
serviceaccount/kuberay-operator unchanged
role.rbac.authorization.k8s.io/kuberay-operator-leader-election unchanged
clusterrole.rbac.authorization.k8s.io/kuberay-operator configured
rolebinding.rbac.authorization.k8s.io/kuberay-operator-leader-election unchanged
clusterrolebinding.rbac.authorization.k8s.io/kuberay-operator unchanged
service/kuberay-operator unchanged
deployment.apps/kuberay-operator unchanged
The CustomResourceDefinition "rayclusters.ray.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by pcmoritz** [comment]
@DmitriGekhtman Can you have a look at this?

**Comment by DmitriGekhtman** [comment]
I think we've fixed this in the master docs -- the solution is to use "create" instead of "apply."

I think we need to standardize a process for pushing typo fixes to the last release's documentation.

**Comment by DmitriGekhtman** [comment]
kubectl create -k

**Comment by pcmoritz** [comment]
@KastanDay Does using `kubectl create -k` fix it for you?

See also https://docs.ray.io/en/master/cluster/kuberay/quickstart.html (the master documentation for clusters is a moving target at the moment since we are presently working on that a lot)
