### ISSUE TITLE
[Core][Scheduler] fix task spread issue when dataset pipeline is involved. 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26878]
### What happened + What you expected to happen

When we run pipelined data processing (i.e. ds.read().window().map_batch().consume()), we observed uneven spread in preprocessing/map_batch phase. We believe this is due to the short coming of the current `SPREAD` strategy where excessive spillback happens when the node is running jobs from two different stages.

As @jjyao , @rkooo567  and I discussed, a simple fix would be avoid spillback with some timeout when `SPREAD` strategy is used.

As I tries to reproduce this, it seems ^ strategy worked.

Please see https://gist.github.com/scv119/5339b599ed14d010437c5a12d7aed96a to reproduce the imbalance issue, and how @jjyao's fix could work.

### Versions / Dependencies

latest ray

### Reproduction script

https://gist.github.com/scv119/5339b599ed14d010437c5a12d7aed96a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
Hmm, a timeout sounds a little brittle at first glance.

What is the underlying issue with spillback? It seems like it should be ok provided that:
(1) Spillback preserves SPREAD, i.e., we randomly / round robin select the node to spill back to.
(2) We only spillback to eligible nodes, that have free CPUs.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @jjyao can you please confirm this is fixed and close if so.

**Comment by jjyao** [comment]
It's been fixed.
