### ISSUE TITLE
[Core]  Image `rayproject/ray-ml:latest-py36-gpu` broken by default

### ISSUE THREAD

**Issue by meechos** [ray-project/ray#26886]
### Missing `kopf` package from `rayproject/ray-ml:latest-py36-gpu` image

Hello guys,
I’d like to use Ray with `python 3.`6 however it seems that the rayproject/ray-ml:latest-py36-gpu image is broken by default - missing deps. I attach below a stacktrace,  in case it can be reproduced.

### Versions / Dependencies

```
(base) ray@30a43972b4c2:~$ ray --version
ray, version 1.13.0
(base) ray@30a43972b4c2:~$ python --version
Python 3.6.12 :: Anaconda, Inc.
```

### Reproduction script

```
(ray) GBLON4WLZ57624:~ admin$ docker run --rm -it rayproject/ray-ml:latest-py36-gpu bash
(base) ray@30a43972b4c2:~$ ray --version
ray, version 1.13.0
(base) ray@30a43972b4c2:~$ python --version
Python 3.6.12 :: Anaconda, Inc.
(base) ray@30a43972b4c2:~$ ipython
Python 3.6.12 |Anaconda, Inc.| (default, Sep 8 2020, 23:10:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.3 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from ray.ray_operator.operator import main
---------------------------------------------------------------------------
ModuleNotFoundError            Traceback (most recent call last)
<ipython-input-1-57617b58aa11> in <module>
----> 1 from ray.ray_operator.operator import main

~/anaconda3/lib/python3.6/site-packages/ray/ray_operator/operator.py in <module>
   10 from typing import Optional
   11 
---> 12 import kopf
   13 import yaml
   14 

ModuleNotFoundError: No module named 'kopf'

In [2]: exit()
(base) ray@30a43972b4c2:~$ pip list | grep kopf
(base) ray@30a43972b4c2:~$
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ddelange** [comment]
this bug seems to have existed for quite some time 👀

https://github.com/ray-project/ray/blame/e69987bc966b9e7cfd8500918c977c05e5af6e34/python/setup.py#L120-L121

**Comment by ddelange** [comment]
@meechos https://github.com/ray-project/ray/pull/15787#discussion_r930429615

**Comment by zhe-thoughts** [comment]
@DmitriGekhtman could you help verify / triage? Looks like issue no longer valid

**Comment by DmitriGekhtman** [comment]
There's a missing dependency, but it only affects a deprecated Kubernetes operator which was meant to be run using Ray images for Python >= 3.7.

In other words, using the module ray.ray_operator is supported only for Python >= 3.7.
