### ISSUE TITLE
[Ray component: AIR] adding the jax into the ray

### ISSUE THREAD

**Issue by JiahaoYao** [ray-project/ray#26888]
### Description

I Tried two approaches to include the jax in the requirements [requirements_ml_docker.txt](https://github.com/ray-project/ray/blob/master/python/requirements_ml_docker.txt) and [requirements_dl.txt](https://github.com/ray-project/ray/blob/master/python/requirements/ml/requirements_dl.txt)

---------

approach one: use the latest jax version. The latest version of the jax also requires updating the tensorflow to the newer version (currently version of the tf is 2.6.2). One block on this is for the mac in the ci is only supports 2.6.2 (guess the mac docker version is slow. )

<img alt="image" width="1058" src="https://user-images.githubusercontent.com/20907377/172480248-188b8ddf-5080-469a-90d1-a65adbc1227b.png">

see detail in this [link](https://github.com/ray-project/ray/pull/25548)

-----
approach one: use a low version of jax to be compatible with the current tensorflow and torch version. the jax scipy conflicts with the global scipy. 

```python
    from jax.scipy.special import expit
  File "/opt/miniconda/lib/python3.6/site-packages/jax/scipy/__init__.py", line 18, in <module>
    from . import signal
  File "/opt/miniconda/lib/python3.6/site-packages/jax/scipy/signal.py", line 17, in <module>
    from jax._src.scipy.signal import (
  File "/opt/miniconda/lib/python3.6/site-packages/jax/_src/scipy/signal.py", line 15, in <module>
    import scipy.signal as osp_signal
AttributeError: module 'scipy' has no attribute 'signal'
```
see detail in this [link](https://github.com/ray-project/ray/pull/26870)

by the way, the Jaxtrainer needs the new functionality only in newer [jax version](https://github.com/google/jax/blob/jax-v0.3.0/jax/_src/distributed.py).

### Use case

this is a block.

**Comment by amogkam** [comment]
Seems like jax requires a specific scipy version which is different than what we have installed in CI.

**Comment by JiahaoYao** [comment]
yes, and it also passed `scipy` >=1.5 checking.
