### ISSUE TITLE
[tune] Request for a temporary releasing tag

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#2689]
### Describe the problem

Hi, could you please make a tag of the current master? Our project is a library that relies on the current version of ray.tune (the one with algorithm and scheduler separated). Although we can use the `pip install -U ray.whl` to develop, users would fail at `pip install ourproject` once we release.

The tag could be a temporary version as long as the `pip` can find it in the repository. Thanks

**Comment by robertnishihara** [comment]
@old-bear when are you planning on releasing?

**Comment by old-bear** [comment]
@robertnishihara It would be nice before 8.22

**Comment by matthew-z** [comment]
+1

Furthermore, I think it would be great  to name the current version in master branch like 0.6.0-dev-2688 (the last commit number). 

Currently it equals to the stable releasing tag, which is a bit confusing.

**Comment by robertnishihara** [comment]
@old-bear we are going to try to release 0.5.1 by 8/22. Currently the only thing we are waiting for is https://github.com/ray-project/ray/pull/2420 (and some testing), so it should be doable.

**Comment by robertnishihara** [comment]
@old-bear we're still working on #2420. If a one or two day delay is ok, then we will still have the release soon. Let me know if that is too much of a delay. If so, we can figure out something quicker.

**Comment by old-bear** [comment]
@robertnishihara Sure, a one or two day delay is fine for us. Let's say a release before 8/27?

**Comment by robertnishihara** [comment]
@old-bear we're still not quite ready to do the release. What about uploading the latest wheels from the S3 bucket to a throwaway PyPI project (e.g., ray-temp-08-27) so that they can be fetched from PyPI properly?

**Comment by old-bear** [comment]
@robertnishihara The temporary place may not work for us since it's not reachable due to security policy of untrusted source. What about a pre-release? say 0.5.1-alpha. It has lower priority which won't affect most users.

**Comment by robertnishihara** [comment]
Ok, we just merged https://github.com/ray-project/ray/pull/2749, so we need to do a bit of testing and assuming no serious issues come up should release 0.5.1 tomorrow. I'm listing the testing todos at https://github.com/ray-project/ray/pull/2755.
