### ISSUE TITLE
How to assign a task to a specific node(or machine)?

### ISSUE THREAD

**Issue by luochao1024** [ray-project/ray#2690]
### Describe the problem

Suppose I have 2 machine each with one node. I make machine A the head by `ray start --head --redis-port=6379
`. In machine B, I make it connect with the head by `ray start --redis-address=<redis-address>
`. 
Now I have the following script:
`@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()`

With this setting, I want to assign a task `node_id_address = ray.get(f.remote())` to machine A. How can I do that?

**Comment by raulchen** [comment]
AFAIK, that is not possible right now.

What's your purpose of doing this?

**Comment by mitar** [comment]
You could define custom resource available only for machine A and then set that your task requires that resource.

**Comment by atumanov** [comment]
We explicitly disallow exposing such topological details and using them for placement. This leads to problems. Typically, there's an underlying reason why a user wants to place a task on a specific physical machine, e.g., data locality, task affinity, or some special resources the user knows are on that machine. In most cases you can use custom resource labels to achieve this. Here's a good starting point for using custom resources:
https://ray.readthedocs.io/en/latest/resources.html#custom-resources

**Comment by luochao1024** [comment]
The communication within one node is much more efficient with share memory, so I want to place some tasks which communicate a lot with each other in the same nodes. I think the custom resource label will solve the problem.

**Comment by robertnishihara** [comment]
@luochao1024 this can be done using custom resources as @mitar suggested. See https://ray.readthedocs.io/en/latest/resources.html

**Comment by ericl** [comment]
Auto-closing stale issue.
