### ISSUE TITLE
[Serve] Support for additional ML serving hardware outside of GPUs, like AWS Inferentia

### ISSUE THREAD

**Issue by zoltan-fedor** [ray-project/ray#26916]
### Description

While GPUs are great for training ML models, when it comes to serving them, they are not very cost-effective (or fast).

There are now new chips specializing on ML model inference, which are faster and a lot more cost effective than GPUs. One of those is [AWS Inferentia](https://aws.amazon.com/machine-learning/inferentia/). See stats about their throughput and costs at https://aws.amazon.com/blogs/machine-learning/achieve-12x-higher-throughput-and-lowest-latency-for-pytorch-natural-language-processing-applications-out-of-the-box-on-aws-inferentia/

Ray Serve currently only supports GPUs. It would be nice to start extending that support to additional hardware specialized on inference like AWS Inferentia chips.

### Use case

I am trying to achieve cost-effective and high throughput inference on AWS EKS - on a cluster which has access to nodes with AWS GPUs and nodes with AWS Inferentia chips.

When serving models via custom applications, we had a great experience (both better speed and lower cost) with AWS Inferentia and would hope to be able to deploy onto AWS Inferentia nodes from Ray Serve too.

I believe the industry is heading towards ML inference on non-GPU hardware, which seems to have the potential to be a lot more efficient and cost-effective when it comes to inference, so I believe it is strategically necessary for all ML serving frameworks to start to support additional hardware specialized on inference outside of just the old GPUs.

### EDIT
After a bit more research it seemed that maybe the `accelerator_types` ([see](https://docs.ray.io/en/latest/ray-core/advanced.html?utm_source=pocket_mylist#accelerator-types)) might be able to address this, but that seems to be only for GPUs.
I am still not sure, whether the custom resources could be used though ([see](https://docs.ray.io/en/latest/ray-core/advanced.html?utm_source=pocket_mylist#dynamic-remote-parameters)).

**Comment by roelschr** [comment]
@zoltan-fedor have you made any progress here? Care to share your experience with Ray and Inferentia?

**Comment by zoltan-fedor** [comment]
@roelschr, I ended up not using Ray with Inferentia and in the end I have completely moved away from Ray Serve and switched to using NVIDIA Triton for model serving (for multiple reasons).
