### ISSUE TITLE
Fresh install does not start localhost:8888/notebooks

### ISSUE THREAD

**Issue by alexander-ossur** [ray-project/ray#2692]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS, 
- **Ray installed from (source or binary)**: Built Docker images
- **Ray version**: 0.5.0
- **Python version**:
- **Exact command to reproduce**: Please read below

### Describe the problem
A fresh Ubuntu 18.04.1 LTS on VirtualBox and Windows 8,1 as host
Docker installation went successfully: https://ray.readthedocs.io/en/latest/install-on-docker.html

Before running a Docker I get this:
> root@ubuntu-vm:~# sudo netstat -ntlp | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      794/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1139/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1139/sshd

Now, my intention is to expose all Docker ports to the Ubuntu localhost:
>  docker run --shm-size=7G --network host -t -i ray-project/examples

In the Docker start "Learning to play Pong":
> python /ray/examples/rl_pong/driver.py
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:54273 to respond...
Waiting for redis server at 127.0.0.1:10918 to respond...
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 12}.

> ======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui87634.ipynb?token=3d87212a1d5132af1aa2b4c07d49827c438a53cee1c8944b
======================================================================

Again let's check the open ports:
> root@ubuntu-vm:~# sudo netstat -ntlp | grep LISTEN
tcp        0      0 0.0.0.0:50984           0.0.0.0:*               LISTEN      4562/plasma_manager
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      794/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1139/sshd
tcp        0      0 0.0.0.0:27703           0.0.0.0:*               LISTEN      4546/redis-server *
tcp        0      0 0.0.0.0:50622           0.0.0.0:*               LISTEN      4552/redis-server *
tcp6       0      0 :::22                   :::*                    LISTEN      1139/sshd
tcp6       0      0 :::27703                :::*                    LISTEN      4546/redis-server *
tcp6       0      0 :::50622                :::*                    LISTEN      4552/redis-server *

Redis is running. Seems okay. Except :8888 port is missing in the list

Am I doing something wrong?

Thank you in advance.

**Comment by robertnishihara** [comment]
Can you check under `/tmp/raylogs/`? There should be some log files for the UI. Can you see if there's anything in there?

**Comment by alexander-ossur** [comment]
After "Learning to play Pong" execution Docker got several files in **/tmp/raylogs/**:
> -rw-r--r-- 1 root root    0 Aug 21 11:33 global_scheduler-2018-08-21_11-33-42-06039.err
-rw-r--r-- 1 root root    0 Aug 21 11:33 global_scheduler-2018-08-21_11-33-42-06039.out
-rw-r--r-- 1 root root 1168 Aug 21 11:34 log_monitor-2018-08-21_11-33-42-07891.err
-rw-r--r-- 1 root root    0 Aug 21 11:33 log_monitor-2018-08-21_11-33-42-07891.out
-rw-r--r-- 1 root root  252 Aug 21 11:34 monitor-2018-08-21_11-33-42-04805.err
-rw-r--r-- 1 root root    0 Aug 21 11:33 monitor-2018-08-21_11-33-42-04805.out
-rw-r--r-- 1 root root    0 Aug 21 11:33 plasma_manager_0-2018-08-21_11-33-42-08157.err
-rw-r--r-- 1 root root    0 Aug 21 11:33 plasma_manager_0-2018-08-21_11-33-42-08157.out
-rw-r--r-- 1 root root  137 Aug 21 11:33 plasma_store_0-2018-08-21_11-33-42-07963.err
-rw-r--r-- 1 root root    0 Aug 21 11:33 plasma_store_0-2018-08-21_11-33-42-07963.out
-rw-rw-r-- 1 root root 2507 Aug 21 11:33 ray_ui19798.ipynb
-rw-r--r-- 1 root root    0 Aug 21 11:33 redis-0-2018-08-21_11-33-41-04872.err
-rw-r--r-- 1 root root 1494 Aug 21 11:34 redis-0-2018-08-21_11-33-41-04872.out
-rw-r--r-- 1 root root    0 Aug 21 11:33 redis-2018-08-21_11-33-41-02588.err
-rw-r--r-- 1 root root 1494 Aug 21 11:34 redis-2018-08-21_11-33-41-02588.out
-rw-r--r-- 1 root root  138 Aug 21 11:33 webui-2018-08-21_11-33-42-01918.err
-rw-r--r-- 1 root root 3218 Aug 21 11:33 webui-2018-08-21_11-33-42-01918.out

log_monitor-2018-08-21_11-33-42-07891.err
> Beginning to track file /tmp/raylogs/redis-2018-08-21_11-33-41-02588.out
> Beginning to track file /tmp/raylogs/redis-2018-08-21_11-33-41-02588.err
> Beginning to track file /tmp/raylogs/monitor-2018-08-21_11-33-42-04805.out
> Beginning to track file /tmp/raylogs/monitor-2018-08-21_11-33-42-04805.err
> Beginning to track file /tmp/raylogs/log_monitor-2018-08-21_11-33-42-07891.out
> Beginning to track file /tmp/raylogs/log_monitor-2018-08-21_11-33-42-07891.err
> Beginning to track file /tmp/raylogs/global_scheduler-2018-08-21_11-33-42-06039.out
> Beginning to track file /tmp/raylogs/global_scheduler-2018-08-21_11-33-42-06039.err
> Beginning to track file /tmp/raylogs/plasma_store_0-2018-08-21_11-33-42-07963.out
> Beginning to track file /tmp/raylogs/plasma_store_0-2018-08-21_11-33-42-07963.err
> Beginning to track file /tmp/raylogs/plasma_manager_0-2018-08-21_11-33-42-08157.out
> Beginning to track file /tmp/raylogs/plasma_manager_0-2018-08-21_11-33-42-08157.err
> Traceback (most recent call last):
>   File "/ray/python/ray/log_monitor.py", line 134, in <module>
>     log_monitor.run()
>   File "/ray/python/ray/log_monitor.py", line 109, in run
>     time.sleep(1)
> KeyboardInterrupt

monitor-2018-08-21_11-33-42-04805.err
> Traceback (most recent call last):
>   File "/ray/python/ray/monitor.py", line 796, in <module>
>     monitor.run()
>   File "/ray/python/ray/monitor.py", line 764, in run
>     time.sleep(ray._config.heartbeat_timeout_milliseconds() * 1e-3)
> KeyboardInterrupt

plasma_store_0-2018-08-21_11-33-42-07963.err
> Allowing the Plasma store to use up to 3.34499GB of memory.
> Starting object store with directory /dev/shm and huge page support disabled

redis-0-2018-08-21_11-33-41-04872.out
> 24:M 21 Aug 11:33:41.830 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
> 24:M 21 Aug 11:33:41.830 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
> 24:M 21 Aug 11:33:41.830 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxcl$
> 24:M 21 Aug 11:33:41.831 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 1$
> 24:M 21 Aug 11:33:41.831 # Server started, Redis version 3.9.102
> 24:M 21 Aug 11:33:41.831 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcomm$
> 24:M 21 Aug 11:33:41.831 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues$
> 24:signal-handler (1534851273) Received SIGINT scheduling shutdown...
> 24:M 21 Aug 11:34:33.059 # User requested shutdown...
> 24:M 21 Aug 11:34:33.060 # Redis is now ready to exit, bye bye...

redis-2018-08-21_11-33-41-02588.out
> 20:M 21 Aug 11:33:41.727 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
> 20:M 21 Aug 11:33:41.727 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
> 20:M 21 Aug 11:33:41.727 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxcl$
> 20:M 21 Aug 11:33:41.728 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 1$
> 20:M 21 Aug 11:33:41.728 # Server started, Redis version 3.9.102
> 20:M 21 Aug 11:33:41.728 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcomm$
> 20:M 21 Aug 11:33:41.728 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues$
> 20:signal-handler (1534851273) Received SIGINT scheduling shutdown...
> 20:M 21 Aug 11:34:33.052 # User requested shutdown...
> 20:M 21 Aug 11:34:33.052 # Redis is now ready to exit, bye bye...

webui-2018-08-21_11-33-42-01918.err
> [C 11:33:45.964 NotebookApp] Bad config encountered during initialization:
> [C 11:33:45.964 NotebookApp] Unrecognized flag: '--allow-root'

webui-2018-08-21_11-33-42-01918.out
> The Jupyter HTML Notebook.
> 
> This launches a Tornado based HTML Notebook Server that serves up an
> HTML5/Javascript Notebook client.
> 
> Subcommands
> -----------
> 
> Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
> using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
> 
> list
>     List currently running notebook servers.
> 
> Options
> -------
> 
> Arguments that take values are actually convenience aliases to full
> Configurables, whose aliases are listed on the help line. For more information
> on full configurables, see '--help-all'.
> 
> --script
>     DEPRECATED, IGNORED
> --pylab
>     DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
> --debug
>     set log level to logging.DEBUG (maximize logging output)
> --no-browser
>     Don't open the notebook in a browser after startup.
> -y
>     Answer yes to any questions instead of prompting.
> --no-mathjax
>     Disable MathJax
> 
>     MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
>     very large, so you may want to disable it if you have a slow internet
>     connection, or for offline use of the notebook.
> 
>     When disabled, equations etc. will appear as their untransformed TeX source.
> --no-script
>     DEPRECATED, IGNORED
> --generate-config
>     generate default config file
> --certfile=<Unicode> (NotebookApp.certfile)
>     Default: u''
>     The full path to an SSL/TLS certificate file.
> --ip=<Unicode> (NotebookApp.ip)
>     Default: 'localhost'
>     The IP address the notebook server will listen on.
> --pylab=<Unicode> (NotebookApp.pylab)
>     Default: 'disabled'
>     DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
> --log-level=<Enum> (Application.log_level)
>     Default: 30
>     Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
>     Set the log level by value or name.
> --port-retries=<Integer> (NotebookApp.port_retries)
>     Default: 50
>     The number of additional ports to try if the specified port is not
>     available.
> --notebook-dir=<Unicode> (NotebookApp.notebook_dir)
>     Default: u''
>     The directory to use for notebooks and kernels.
> --keyfile=<Unicode> (NotebookApp.keyfile)
>     Default: u''
>     The full path to a private key file for usage with SSL/TLS.
> --client-ca=<Unicode> (NotebookApp.client_ca)
>     Default: u''
>     The full path to a certificate authority certificate for SSL/TLS client
>     authentication.
> --config=<Unicode> (JupyterApp.config_file)
>     Default: u''
>     Full path of a config file.
> --port=<Integer> (NotebookApp.port)
>     Default: 8888
>     The port the notebook server will listen on.
> --transport=<CaselessStrEnum> (KernelManager.transport)
>     Default: 'tcp'
>     Choices: [u'tcp', u'ipc']
> --browser=<Unicode> (NotebookApp.browser)
>     Default: u''
>     Specify what command to use to invoke a web browser when opening the
>     notebook. If not specified, the default browser will be determined by the
>     `webbrowser` standard library module, which allows setting of the BROWSER
>     environment variable to override it.
> 
> To see all available configurables, use `--help-all`
> 
> Examples
> --------
> 
>     jupyter notebook                       # start the notebook
>     jupyter notebook --certfile=mycert.pem # use SSL/TLS certificate
>

**Comment by alexander-ossur** [comment]
Probably **Unrecognized flag: '--allow-root'** is the clue

**Comment by robertnishihara** [comment]
@alexander-ossur good catch, I think that's the issue. I've seen some machines where that flag is required and others where it is unrecognized..

**Comment by robertnishihara** [comment]
Closing because this aspect of the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
