### ISSUE TITLE
[Core] Calling remote methods as local without `.remote()`

### ISSUE THREAD

**Issue by vaxenburg** [ray-project/ray#26936]
### Description

Allow calling methods on remote actors both with and without the `.remote()` suffix.

When called with `.remote()`, the behavior is the usual one, returning a future. When called without `.remote()`, the proposed new behavior is:

 ```python
actor.method() == ray.get(actor.method.remote())
```

That is, calling methods on remote actors as if the actors were local. I think this is also the behavior in a very similar DeepMind's library [Launchpad](https://github.com/deepmind/launchpad), where you can have it both ways -- with and without `.remote()`

In addition to actors, this could also be extended to remote functions (tasks).

### Use case

Concrete use case: I recently worked on integrating Ray with some 3rd party (DeepMind's) RL libraries, which of course are not aware of the Ray Core API, and had to imitate this behavior by writing [this wrapper](https://github.com/JaneliaSciComp/ray-janelia/blob/main/remote_as_local_wrapper.py) for Ray actors.

**Comment by scv119** [comment]
This is an interesting idea. any thought on this? @jjyao @rkooo567

**Comment by dmatrix** [comment]
IMHO, anywhere in the APIs we can remove redundancies or unnecessary additional code helps. This is one case where it makes sense.

**Comment by rkooo567** [comment]
Hmm in my personal opinion just making `actor.method()` blocking is prone to error (E.g., I forgot to use .remote occasionally, and if we support this, this becomes an unexpected behavior). Feel like if we support this, it should be more explicit.

**Comment by vaxenburg** [comment]
The blocking behavior is not an unexpected behavior. It is your normal synchronous way of calling methods on objects in general, outside of Ray or any other distributed setup. I'm pretty sure this normal behavior should be preserved and it should not raise an exception as it currently does. Not being able to resort to the normal blocking calls is far worse than `actor.method()` being "prone to errors", in my opinion.

Example: imagine you want to use Ray with a 3rd party library where one class (actor) calls a method on another class. It simply won't work with the current Ray API. It will raise an exception because that class will be calling other class' methods with `actor.method()`. What do you do in this case? Rewriting the library class (that is, replacing all `.method()` calls with `.method.remote()`) is not an option. You can write a wrapper to imitate this behavior, as I did. 

But why not just preserver the normal blocking `actor.method()` calls in the first place and let the user (me) decide which one to use?

**Comment by jjyao** [comment]
@vaxenburg could you help me understand the concrete use case more? Are you saying a third party library will take an arbitrary object (actor object or normal object) and call a method of it and you want the calling style to be the same?

**Comment by vaxenburg** [comment]
Imagine I import these two classes from a library. The library doesn't know anything about Ray.

```python
class Actor:
   def method(self):
      # do something here
      return result

class Caller:
    def __init__(self, actor):
        self.actor = actor
    def do_something(self):
        self.x = self.actor.method()
```

And I want to use them in my application _with_ Ray. I want this code to work without having to rewrite the library classes and/or writing a wrapper to imitate `actor.method()` calls:

```python
from library import Actor, Caller

Actor = ray.remote(Actor)
Caller = ray.remote(Caller)

actor = Actor.remote()
caller = Caller.remote(actor)

caller.do_something()  # This will throw error because of unsupported actor.method() call
```

**Comment by scv119** [comment]
@vaxenburg how about create a helper wrapper to wrap around ray actor, and auto generate the sync version of the function that's internally calls to `ray.get(delegate_.foo.remote())`?

**Comment by vaxenburg** [comment]
Yes, writing a wrapper is what I ended up doing as a workaround -- see above. My suggestion is to make it a part of the API instead of wrapping (just like it is a part of the API in [Launchpad](https://github.com/deepmind/launchpad).)

**Comment by jjyao** [comment]
The concern of adding a new api like this is that it will make apis more difficult to use since now people need to decide which one to use and most users should only use the remote version. Also even if we can call remote methods as local, it'll never be the same as calling a local method so we shouldn't be implicit here to avoid any surprises (that's actually why we introduced `.remote()` in the first place to be explicit that it's not a local method call).

I feel a simple utility wrapper is good balance here: you can use it to achieve your goal but it also doesn't add more complexity to the existing apis. For now I think you can continue using your wrapper and we can provide one with ray in the future so similar users don't need to write their own.

**Comment by vaxenburg** [comment]
I actually think this would let Ray be useful in so many other use cases, like mine where I had to use Ray with some other libraries and not being able to issue local calls with `actor.method()` was a major roadblock.

Also, regrading this:
> now people need to decide which one to use and most users should only use the remote version.

I think this is exactly the kind of decision that _should_ be made by the user, not the library designer. Not having this flexibility is a hugely excessive guardrail in my view.

That said, I get it that adding a new API is difficult. I just thought it's worth it in this case.
