### ISSUE TITLE
[doc] [State Observability] Document Python APIs.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#26949]
#### Python API Docs
Currently, only CLI is documented. We should document python APIs.

I think in the initial version, we can probably just document client APIs. But we might want to remove them in the future.

#### Other improvements
- [ ] Description on output/link to output scehma in doc/API intro

**Comment by rickyyx** [comment]
Is this 2.0 blocker?

**Comment by rkooo567** [comment]
Yes, but we can merge this after branch cut as a cherry pick (harmless to do that) I believe.

**Comment by aryanraj2713** [comment]
Can I work on the issue?

**Comment by rickyyx** [comment]
Hey @aryanraj2713 , thanks for your interest! I actually have a PR out for this already, sorry for not mentioning it in advance here. 

However, if you are interested in more other tasks, feel free to let me or @rkooo567 know!
