### ISSUE TITLE
[REQUEST] Could you please add some example for ray.tune in PyTorch?

### ISSUE THREAD

**Issue by HudsonHuang** [ray-project/ray#2694]
### System information
- **OS Platform and Distribution : Linux Ubuntu 16.04:
- **Ray installed from : binary
- **Ray version : 0.5.0
- **Python version: 3.6.3
- **Exact command to reproduce: None

### Describe the problem
Could you please add some example for ray.tune in PyTorch? Just a simple MNIST example would be fine.

Thank you very much.

**Comment by ericl** [comment]
I found an example from a previous issue here: https://github.com/ray-project/ray/issues/2096

Would you like to try it out, and if it works, make a pr to add it to the examples dir?

**Comment by HudsonHuang** [comment]
I will try it, thank you.

**Comment by ericl** [comment]
Looks like @richardliaw has this pr: https://github.com/ray-project/ray/pull/2708

**Comment by richardliaw** [comment]
#2708 addresses this and is now merged - you can check out the examples for PyTorch in Tune here: 

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch.py

Closing for now; feel free to reopen if any other issues arise.
