### ISSUE TITLE
[air] Enable actor task retries in BatchPredictor / ActorPoolStrategy

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#26991]
Currently, BatchPredictor does not offer fault tolerance since we do not enable Ray actor fault tolerance (https://docs.ray.io/en/master/ray-core/actors/fault-tolerance.html). This means that inference results cannot be reconstructed on failure, limiting use at very large scales.

Fortunately, Ray core already supports stateless actor task retries. This can be enabled by setting `max_restarts` and `max_task_retries` options for the actors used for ActorPoolStrategy.

There is one edge case to be aware of: if a failure is due to the Ray cluster shrinking in size, the recreated actor may be un-able to get rescheduled, leading to deadlock on reconstruction:
1. Suppose actors {A, B, C} are in the cluster, and a task is submitted to B.
2. Suppose the node holding B fails.
3. When the progress bar tries to confirm the result of B's task, we will hang forever since there is no space for B to be re-created.

We can work around this by ensuring ActorPoolStrategy deallocates idle actors as soon as possible (e.g., deallocates A and C as soon as they're done with their tasks).

We should:
- [ ] Enable actor fault tolerance in Datasets (e.g., as described above)
- [ ] Add chaos tests for BatchPredictor (pipelined / non-pipelined)
- [ ] Add this to our documentation for Datasets / BatchPredictor

Here's also a toy example that illustrates the current failure mode:
```
import ray
import sys

ds = ray.data.range(10)

def f(x):
    import random
    if random.random() > 0.8:
        print("Mock failure")
        sys.exit(1)
    return "ok"


class F:
    def __call__(self, x):
        return f(x)

#ds.map(f, compute="tasks").show()
ds.map(F, compute=ray.data.ActorPoolStrategy(4, 4)).show()
print("Succeeded despite failures")
```

**Comment by clarkzinzow** [comment]
>We can work around this by ensuring ActorPoolStrategy deallocates idle actors as soon as possible,

FYI [this PR](https://github.com/ray-project/ray/pull/24669) deallocates (terminates) idle actors if there's no more work to do, which is at least more eager than our current implementation.

**Comment by chaomengyuan** [comment]
Hi @ericl and @clarkzinzow, we internally want to use some "spot" GPU resources to run some Ray-based offline inference jobs. In such case, a fault tolerance/failure recovery strategy for ActorPoolStrategy is a "must-have" feature. I am wondering what is the current status of this issue? Is there a timeline for supporting this feature? Thanks.

**Comment by clarkzinzow** [comment]
Hi @chaomengyuan! The Datasets `ActorPoolStrategy` should inherit the same [fault-tolerance characteristics of Ray Core actors](https://docs.ray.io/en/master/ray-core/actors/fault-tolerance.html), i.e. if you set `max_restarts > 0` and `max_task_retries > 0` for the actors underlying the actor pool, Ray Core's lineage-based object reconstruction should work as expected. This actor configuration is exposed at the Datasets level via the [`.map_batches()` API](https://docs.ray.io/en/master/data/api/dataset.html#ray.data.Dataset.map_batches), e.g. the following would enable infinite actor restarts and actor task retries:
```python
pipe = ...
pipe = pipe.map_batches(..., compute="actors", max_restarts=-1, max_task_retries=-1)
```

I believe that this should work, cc @ericl and @stephanie-wang to confirm.

**Comment by chaomengyuan** [comment]
Hi @clarkzinzow! Thank you for your reply. So, does this mean that the doc here: [](https://docs.ray.io/en/latest/data/key-concepts.html#fault-tolerance) for the "compute=ActorPoolStrategy()" is outdated?

**Comment by clarkzinzow** [comment]
@chaomengyuan Good catch! We should update that section.
