### ISSUE TITLE
[Core] spilled object leaked.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#26994]
### What happened + What you expected to happen

Run the workload specified in https://gist.github.com/scv119/5339b599ed14d010437c5a12d7aed96a with larger dataset (i.e. 200GB data) and cancel the job while it's spilling. you will noticed that the spilled file is leaked, even `ray memory` reports no objects.

### Versions / Dependencies

latest ray

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
Target to finish by August 5th.

**Comment by nollied** [comment]
i'm having a similar problem, no objects are spilling to the disk however it appears that objects are not being garbage collected from plasma.

**Comment by rkooo567** [comment]
Do you also have the similar issues when you ctrl + C? @nollied

**Comment by nollied** [comment]
@rkooo567 i haven't noticed, but i wouldn't be surprised.

**Comment by clarng** [comment]
@avivhaber  let's sync with @scv119  on coming up with a repro

**Comment by scv119** [comment]
starting investigating. run the script for 20 consecutive runs seems no repro. so very likely we need to ctrl+C to interrupt the job in the middle.

**Comment by scv119** [comment]
i have a theory this might because of the the io worker deletion failure. i.e. the io worker failed to delete a file due to exception or io worker crash. One possibility is https://github.com/ray-project/ray/issues/26395 leads to duplicated file but there could be other failure models too.
