### ISSUE TITLE
[Tune][Air] Unreadable CLI report table due to `train_loop_config` string

### ISSUE THREAD

**Issue by Tonyhao96** [ray-project/ray#27011]
### Description

Hi,

How can I simplify the CLI progress reporter column names? Some features become too long to display, such as `train_loop_config/batch_size`. The `train_loop_config` string seems useless.

![Screenshot from 2022-07-26 19-48-20](https://user-images.githubusercontent.com/27758466/180999237-664190fc-3d19-4892-a007-5205d9de1b8a.png)

I am using the latest nightly version of Ray with the `Tuner` api:

```Python
tuner = Tuner(
        trainer,
        param_space={"train_loop_config": config})
```

### Use case

Allow users to remove/rename CLI report table columns

**Comment by xwjiang2010** [comment]
@krfricke is this already fixed by you?

**Comment by krfricke** [comment]
Hi @Tonyhao96, this is already possible with the `CLIReporter`:


```
tuner = tune.Tuner(
    trainer,
    param_space={
        "train_loop_per_worker": {
            "lr": tune.uniform(0.01, 0.04),
            "beta": tune.uniform(0.1, 0.2)
        }
    },
    run_config=air.RunConfig(
        progress_reporter=tune.CLIReporter(
            parameter_columns={
                "train_loop_per_worker/lr": "lr",
                "train_loop_per_worker/beta": "beta",
            }
        )
    )
)
```

might be a bit cumbersome to configure though, so we my want to simply this.
