### ISSUE TITLE
when possibly it will be available for windows? more than half of the world is using windows!

### ISSUE THREAD

**Issue by Khalilsqu** [ray-project/ray#2702]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by robertnishihara** [comment]
Hi @Khalilsqu, I'm closing this so that we can consolidate the discussion on #631. We are not working on it at the moment, but it's very doable. Some of the challenges are mentioned in that issue. Note that if you're using Windows 10, then you can run Ray on the Linux subsystem.

**Comment by Khalilsqu** [comment]
Thank you very much @robertnishihara for your response, I will give WLS a try,

**Comment by ErnstDinkelmann** [comment]
The only issue with using WSL is that you then lose CUDA/GPU support.
So you get the more efficient finding of hyper parameters for example, but the function runs so much slower.
Hope I have it wrong, but that's the way I understand it.
