### ISSUE TITLE
[Core] Ray start/stop/start does not work when using a custom temporary folder

### ISSUE THREAD

**Issue by jbedorf** [ray-project/ray#27021]
### What happened + What you expected to happen

The changes introduced [here](https://github.com/ray-project/ray/pull/26678) have as side effect that the following logic no longer works:

Start a cluster with a custom temporary folder: `ray start --head --temp-dir /tmp/bla`
Now stop any active ray cluster using the typical: `ray stop`

Now there is nothing running anymore, but when you next run:  `ray start --head --temp-dir /tmp/bla`

You get  this error:
`ConnectionError: Ray is trying to start at 192.168.XXX.XXX:6379, but is already running at 192.168.XXX.XXX:6379. `

This due to the file `ray_current_cluster` not being deleted when using a non-default temporary directory. The `stop` command does not allow you to specify the `temp-dir` and as such it will not find `ray_current_cluster`  file. But when you then try to start ray again it will fail due to the file still being there. You can work around this by manually deleting the file or specifying a different port.

### Versions / Dependencies

Nightly

### Reproduction script

```
ray start --head --temp-dir /tmp/bla
ray stop
ray start --head --temp-dir /tmp/bla
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
@scv119 @stephanie-wang seems a release blocker since it's a regression.
