### ISSUE TITLE
[Core] `TypeError: __init__() missing 2 required positional arguments: 'shape' and 'dtype'` when using `TensorDtype`

### ISSUE THREAD

**Issue by geoffreyangus** [ray-project/ray#27031]
### What happened + What you expected to happen

Hi all,

### 1. The Bug 

I am running into an issue on Ray nightly where I am seeing the following failure in our unit tests:

```
            # TODO(ujvl): Consider how to allow user to retrieve the ready objects.
            values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
            for i, value in enumerate(values):
                if isinstance(value, RayError):
                    if isinstance(value, ray.exceptions.ObjectLostError):
                        worker.core_worker.dump_object_store_memory_usage()
                    if isinstance(value, RayTaskError):
>                       raise value.as_instanceof_cause()
E                       ray.exceptions.RayTaskError(TypeError): ray::_map_block_nosplit() (pid=7733, ip=10.1.1.89)
E                         File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/ray/data/_internal/compute.py", line 449, in _map_block_nosplit
E                           for new_block in block_fn(block, *fn_args, **fn_kwargs):
E                         File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/ray/data/dataset.py", line 457, in transform
E                           applied = batch_fn(view, *fn_args, **fn_kwargs)
E                         File "/home/runner/work/ludwig/ludwig/ludwig/backend/ray.py", line 665, in to_tensors
E                           df[c] = df[c].astype(TensorDtype())
E                       TypeError: __init__() missing 2 required positional arguments: 'shape' and 'dtype'
```

### 2. Expected Behavior

`TensorDtype()` to initialize successfully. I'm not sure if the interface has actually changed, because when I attempted to pass in `shape` and `dtype`, I got the following error: 

```
TypeError: TensorDtype() takes no arguments
```

### 3. Useful Information

You can find the failing test in our GitHub workflow here: https://github.com/ludwig-ai/ludwig/runs/7524542472?check_suite_focus=true. It seems to have to do with these lines of code: https://github.com/ludwig-ai/ludwig/blob/a2bce0eddbc8c03cec94a819f43242c0fe7235f7/ludwig/backend/ray.py#L654-L670, reproduced here for convenience:

```
def to_tensors(df: pd.DataFrame) -> pd.DataFrame:
    for c in columns:
        df[c] = df[c].astype(TensorDtype())
    return df

# TODO(shreya): self.trainer_kwargs should have the correct resources; debug.
# trainer_kwargs = {**get_trainer_kwargs(), **self.trainer_kwargs}
num_cpus, num_gpus = self.get_resources_per_worker()

predictions = dataset.ds.map_batches(to_tensors, batch_format="pandas").map_batches(
    batch_predictor,
    batch_size=self.batch_size,
    compute="actors",
    batch_format="pandas",
    num_cpus=num_cpus,
    num_gpus=num_gpus,
)
```

This code block doesn't seem to cause any issues in our tests running Ray 1.12 and 1.13. 

### Versions / Dependencies

Ray nightly (July 26th, 2022)
Python 3.9
MacOS 12.3.1

### Reproduction script

I can't yet figure out how to create a narrow reproduction, as I don't fully understand why the issue is occurring in the first place– the attempt at a narrow reproduction in a Jupyter notebook seems to run successfully. That said, the error can be reproduced on local environments by running the above specified unit test within Ludwig.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarkzinzow** [comment]
Hey @geoffreyangus, this was a recent API change where `TensorDtype` now takes the `shape` and `dtype` of the tensor column elements as constructor arguments; if you don’t have that information on-hand, you can use `TensorArray` to do your cast instead (which most of our examples do as well as internally):
```python
from ray.data.extensions import TensorArray

def to_tensors(df: pd.DataFrame) -> pd.DataFrame:
    for c in columns:
        df[c] = TensorArray(df[c])
    return df
```
