### ISSUE TITLE
[AIR] Add tests for framework-specific checkpoints

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#27056]
### Description

`Checkpoint` is AIR's abstraction for persistent training state. Checkpoints store models and preprocessors. They also store framework-specific objects like HuggingFace tokenizers.

We previously exposed functions for loading and saving checkpoints like `ray.train.torch.utils.to_air_checkpoint`. However, to improve discoverability, we introduced framework-specific checkpoints like `TorchCheckpoint`. For more context, see [[AIR] Add framework-specific checkpoints](https://github.com/ray-project/ray/pull/26777) and  [[RFC] Eliminate free-floating "similar by convention" util functions from Train](https://github.com/ray-project/ray/pull/26651).

Unfortunately, we don't have unit-tests for any framework-specific checkpoints. 

We should unit test the public methods of:
* `HuggingFaceCheckpoint`
* `LightGBMCheckpoint`
* `RLCheckpoint`
* `SklearnCheckpoint`
* `TensorflowCheckpoint`
* `TorchCheckpoint`
* `XGBoostCheckpoint`

### Use case

N/A

**Comment by xwjiang2010** [comment]
@bveeramani Could you add some more details here? Thinking of having @justinvyu taking this on!

**Comment by heyitsmui** [comment]
@xwjiang2010 @bveeramani i am happy to take this on if this is not yet claimed!

**Comment by bveeramani** [comment]
Hey @heyitsmui, there's already a PR in review for this (https://github.com/ray-project/ray/pull/28049), but thank you for offering to help!
