### ISSUE TITLE
[AIR][Dataset] Cannot read two parquet files with `anonymous@`

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#27064]
### What happened + What you expected to happen

This issue is blocking P0 mass documentation failure before branch cut - https://github.com/ray-project/ray/issues/26410

Ray dataset's `read_parquet` API cannot read two files with `anonymous@` username, which is required for our CI.

### Versions / Dependencies

on master

### Reproduction script

So this works 
```
ds = ray.data.read_parquet(["s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet"])
```

And this works 
```
ds = ray.data.read_parquet(["s3://air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet"])
```

Also this works 
```
ds = ray.data.read_parquet([
    "s3://air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet",
    "s3://air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet",
])
```

But reading two files with username like `anonymous@` fails 
```
ds = ray.data.read_parquet([
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet",
    "s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet",
])
```

```
OSError: Failing to read AWS S3 file(s): ['air-example-data/ursa-labs-taxi-data/downsampled_2009_01_data.parquet', 'anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet']. Please check that file exists and has properly configured access. You can also run AWS CLI command to get more detailed error message (e.g., aws s3 ls <file-name>). See https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html and https://docs.ray.io/en/latest/data/creating-datasets.html#reading-from-remote-storage for more information.
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by pcmoritz** [comment]
Alright, so we can make this work by deploying Thomas' CI infra changes, so the CI has access to our buckets without the need for anonymous:

https://github.com/ray-project/buildkite-ci-stack/pull/34

We would need @krfricke or @simon-mo to review apply these terraform changes.

There might be a simpler solution for this. If we do the Terraform changes, we can also drop the `anonymous` in all the examples, which would be nice!

Also cc @thomasdesr

**Comment by jiaodong** [comment]
Yes dropping required `anonymous` for CI will be great for future use cases too, not sure if we can make it before branch cut tho.

Meanwhile I confirmed this function https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/data/datasource/file_based_datasource.py?L463:5 is returning wrong paths parsed. 

I don't mind giving it a shot to fix this use case but given how involved this function is / unit test status im afraid I might break others ...

**Comment by jiaodong** [comment]
After some digging the issue seems to have something to do with pyarrow's implementation.

This is how it resolves a file path when it knows about the filesystem, for example, s3:
```
    if filesystem is not None:
        filesystem = _ensure_filesystem(
            filesystem, allow_legacy_filesystem=allow_legacy_filesystem
        )
        if isinstance(filesystem, LocalFileSystem):
            path = _stringify_path(path)
        elif not isinstance(path, str):
            raise TypeError(
                "Expected string path; path-like objects are only allowed "
                "with a local filesystem"
            )
        if not allow_legacy_filesystem:
            path = filesystem.normalize_path(path)
        return filesystem, path
```

but it will incorrectly return wrong path. When our input path is `s3://anonymous@air-example-data/ursa-labs-taxi-data/downsampled_2009_02_data.parquet` with known file system type of S3, it will return full string rather than parsed {bucket}/{file_path}.

**Comment by jiaodong** [comment]
OK i put up a quite contained conditional to walk around pyarrow's return path with anonymous credential in https://github.com/ray-project/ray/pull/26983
