### ISSUE TITLE
[Core] Setting up actors on specific gpus 

### ISSUE THREAD

**Issue by DuoblaK** [ray-project/ray#27078]
### Description

Hello, I would like to ask you a question about actor running on gpu.
When I create an actor, how can I asign a specified GPU to the actor.
For example, there are 8 gpus on my machine, like gpu[0,1,2,3,4,5,6,7]
but gpu[2, 3, 4, 6] is broken, I want to create 4 actors running on gpu[0,1,5,7].
How can I do that?
For some reason, I don’t want to use CUDA_VISIBLE_DEVICE , is there any other way to do this? Thanks for your reading.

**Comment by kouroshHakha** [comment]
Hello @DuoblaK, unfortunately setting  `CUDA_VISIBLE_DEVICES` is the only way I know. Why is it that you don't wanna use `CUDA_VISIBLE_DEVICES`?

**Comment by DuoblaK** [comment]
> Hello @DuoblaK, unfortunately setting `CUDA_VISIBLE_DEVICES` is the only way I know. Why is it that you don't wanna use `CUDA_VISIBLE_DEVICES`?

Hello, glad to receive your reply.
Because in my case, I use more than one node, I cant set worker node's env on my head node. That's why SET_CUDA_DEVICE can't reach my request.
Or if I create a GPUActor, may the actor get the other gpu on the node? So I can schedule the actor to the gpu still on service.
Thanks a lot for your reply.

**Comment by jjyao** [comment]
You can set `CUDA_VISIBLE_DEVICE` inside your actor code (e.g. inside constructor) so it will run wherever your actor runs.
