### ISSUE TITLE
[Core]  Ray PlacementGroup Add a callback on a node failure

### ISSUE THREAD

**Issue by ljjsalt** [ray-project/ray#27076]
### Description

Currently, once a node down, the placement group won't be removed and converts to a pending state and waits to be rescheduled. Is this possible to add a call back so the process who created these placement groups can be notified when a placement group is being rescheduled?

I have checked related document, but seems no useful information is provided.
I can work on this feature if it's no there.

### Use case

A placement group has a running fault tolerant job which can be restarted. If the rescheduling can be notified, we will be able to restart the job on this placement group once it has been rescheduled.

For example,

```python
pg = ray.util.placement_group(...)
launch(fault_tolerant_job, pg)
while True:
     ray.wait([pg.rescheduled()])
     launch(fault_tolerant_job, pg)
```

`pg.rescheduled` is the methods to be implemented or I am looking for. This means whenever we know the placement group that is running a task is somehow rescheduled, we launch the job on this placement group again.

**Comment by ljjsalt** [comment]
[Hello, hello, is there anybody out there?

**Comment by scv119** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
@ljjsalt is this resolved? Why did you close the issue?

**Comment by ljjsalt** [comment]
> @ljjsalt is this resolved? Why did you close the issue?

I didn't resolve this issue, but it seems we are supposed to get the failure information from tasks/actors, instead of from the placement groups. Now I am able to achieve what I need, but I can reopen this issue if you think this is necessary.
