### ISSUE TITLE
[workflow] HTTP Event provider test runs too long

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#27109]
### What happened + What you expected to happen

Http event provider runs for a long time in CI. For exmaple, test_http_event_2 only has one test but it runs for 80s. We need to make sure it's expected or fix the bug or the test.

### Versions / Dependencies

master

### Reproduction script

buildkite ci check http event ptests

**Comment by klwuibm** [comment]
@yuanchi2807 and I conducted profiling experiments on a few workflow tests, including some that are not HTTP event provider related.  We instrumented the fixtures defined in `conftest.py` to measure the times a test spent on starting a Ray cluster, shutting down a Ray cluster, starting a Ray Serve, and shutting down a Ray Serve.  We log the timestamp before and after such a step and then calculate the elapse time for a cluster start/stop and a Ray Serve start/stop.  Here is a summary of the experiments conducted locally on a MacBook.   For reference, we also show the test times measured in [buildkite](https://buildkite.com/ray-project/ray-builders-branch/builds/8985#018240d3-c77a-4602-a3c7-5345fb88cde1).

I        workflow test   |  % on fixtures  | time on fixtures | total test time |  total test time (buildkite)  |
|  :----|   :----: | :-----: | :-----:  | :------: |
| `test_http_events  `          |       71.3%          |       87s               |       122s          |        153.7s      |
|` test_http_events_2  `      |          72.6%         |        45s              |          62s         |      79.3s   |
| `test_http_events_3 `       |          73.3%         |         88s             |        120s         |    151.3s    |
| `test_events  `                   |         71.2%          |        176s             |         247s        |    298.6s   |
| `test_basic_workflows_3 `|         70.7%          |         29s             |        41s           |    57.7s      |

The conclusions are:

1. The bulk of the total test times (about 70%) on HTTP event provider tests are spent on starting a cluster, starting a Ray Serve, shutting down a Ray Serve, and shutting down a cluster.
2. The % of time spent on these steps on the HTTP event provider tests are similar to that on other non HTTP event provider related tests (such as test_events and test_basic_workflows_3).
3. The test times of HTTP event provider tests seem as normal as those of other workflow tests.

**Comment by iycheng** [comment]
Ah, got it. Thanks for the detailed investigation. I just want to make sure no other issues. I think we can close this issue now.
