### ISSUE TITLE
[Ray Dashboard] Logs not showing up

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#27102]
### What happened + What you expected to happen

When you click on the Ray Dashboard’s logs, you don’t see any logs anymore for Ray actors or tasks. Instead you see

<img width="1440" alt="Screen Shot 2022-07-27 at 9 57 08 AM" src="https://user-images.githubusercontent.com/92341594/181307371-b5b969a7-b80f-4aa4-8166-40e2a6d58194.png">

### Versions / Dependencies

Ray on the latest master.

### Reproduction script

1. Start ray cluster with `ray start --head`

2. Run this script:

```python
import ray

ray.init(address="auto")

@ray.remote
class B:

    def __init__(self):
        print("hello")

b = B.remote()

@ray.remote
def f():
    print("check me out")

f.remote()
```

3. Check the Ray dashboard (at `localhost:8265`):

<img width="1440" alt="Screen Shot 2022-07-27 at 9 57 08 AM" src="https://user-images.githubusercontent.com/92341594/181307604-6f207f23-73e2-4f25-b44d-9394532f9606.png">

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by alanwguo** [comment]
To fix memory leaks, we are no longer caching logs in the backend and instead are using the state observability logs API.
As a result, we removed the ability to view logs at the node level. Worker level logs are still available. You can also use the new dashboard UI to view logs as well.

The UI has been updated to remove the button for node-level logs but it doesn't seem updated on your browser.
@shrekris-anyscale , how did you install ray from master? It seems the frontend has to be rebuild on your local machine by running `npm install && npm run build` from the `dashboard/client` folder.

**Comment by shrekris-anyscale** [comment]
Ah makes sense, I only rebuilt using `pip install -e . --verbose`.

**Comment by shrekris-anyscale** [comment]
After rebuilding, the logs appear correctly:

<img width="1440" alt="Screen Shot 2022-07-27 at 2 27 43 PM" src="https://user-images.githubusercontent.com/92341594/181375653-44420b0d-fe1b-4163-ad9f-9d8ed42ea079.png">
