### ISSUE TITLE
[rllib] es agent block

### ISSUE THREAD

**Issue by brantbzhang** [ray-project/ray#2710]
### System information
- **Linux Ubuntu 16.04
- **Ray installed from source
- **Ray version （0.5）2018.08.17 master
- **Python version 3.5
- **Exact command to reproduce**:

```
os.environ['RAY_USE_NEW_GCS']='on'
os.environ['RAY_USE_XRAY']='1'
import ray
import gym
from ray.tune.registry import register_env
import ray.rllib.agents.es as es
from ray.tune.logger import pretty_print,NoopLogger
config={
 'episodes_per_batch': 1000,
 'eval_prob': 0.003,
 'l2_coeff': 0.005,
 'noise_size': 25000,
 'noise_stdev': 0.02,
 'num_workers': 2,
 'observation_filter': 'MeanStdFilter',
 'return_proc_mode': 'centered_rank',
 'stepsize': 0.01,
 'timesteps_per_batch': 10000}
try:
    ray.shutdown()
except:
    pass
ray.init(num_workers=12)
policy = ray.experimental.SimpleGcsFlushPolicy()
ray.experimental.set_flushing_policy(policy)
register_env("TradeEnv", lambda config: TrainEnv(config))
agent = es.ESAgent(env="TradeEnv", config=config,logger_creator=lambda x:NoopLogger(None,None))
```

![image](https://user-images.githubusercontent.com/1318167/44457289-6c954700-a635-11e8-8294-2374862c2ce0.png)

custom env, it can use in other agent. eg. ppo,dqn
but in esagent,it say:
This worker was asked to execute a function that it does not have registered. You may have to restart Ray.

**Comment by ericl** [comment]
What condition triggers this, is it the custom env? Does it work if you don't set RAY_USE_XRAY?
