### ISSUE TITLE
[Preprocessors] Add robust default tokenization function

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#27129]
### Description

Default tokenization function for `Tokenizer` snd `CountVectorizer` doesn't handle punctuation, newlines, or casing.

For example,
```
"Hello, world!"
```

get's tokenized as 
```
["Hello,", "world!"]
```

instead of
```
["hello", "world"]
```

**Comment by richardliaw** [comment]
I'm thinking we shouldn't do this in AIR... users can use things like texthero or nltk to do a text sanitization operation first.

**Comment by bveeramani** [comment]
Closing this issue per @richardliaw's suggestion
