### ISSUE TITLE
ray.shutdown() is not called at the end of a ray.init() script running in a jupyter notebook

### ISSUE THREAD

**Issue by MattEWeber** [ray-project/ray#27121]
### What happened + What you expected to happen

This script

```
import ray
import time

ray.init()

@ray.remote(num_cpus=1)
def f(x):
    time.sleep(60)
    return x * x

futures = [f.remote(i) for i in range(30)]
print(ray.get(futures))
```

never has its driver marked as ended in the dashboard/snapshot endpoint after the script completes.

### Versions / Dependencies

ray version 1.13.0
Python 3.9.5

In Jupyter Python3 (ipykernel)

### Reproduction script

Upon further investigation it appears the `atexit` handler [here](https://github.com/ray-project/ray/blob/master/python/ray/_private/worker.py#L1585) isn't being called. I came to this conclusion from seeing that running this script two times in a row produces 

```
RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.
```
 This error goes away after calling
```
ray.shutdown()
```

So then I checked the behavior of `atexit` in a jupyter notebook for this simple script using `atexit`

```
import atexit

def print_stuff():
    print("atexit worked!")

atexit.register(print_stuff)

print("hello world")
```

The output from the terminal is
![Screen Shot 2022-07-27 at 2 17 04 PM](https://user-images.githubusercontent.com/3513451/181374109-f85832d7-62cd-409b-9a99-a948014ad077.png)

the output from the notebook is 
![Screen Shot 2022-07-27 at 2 17 51 PM](https://user-images.githubusercontent.com/3513451/181374162-dc9a48a1-7231-45f4-b590-53c0b7d41915.png)

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
Is this the case (shutdown not called) when it is not used with jupyter?

**Comment by MattEWeber** [comment]
No. Shutdown is called at the end of the script every other way I'm aware of running it (from the terminal, or from an interactive python shell like ipython)

**Comment by rkooo567** [comment]
Deprioritizing it until the meeting

**Comment by rkooo567** [comment]
maybe we can close it @MattEWeber ?

**Comment by richardliaw** [comment]
Driver shouldn't terminate until the jupyter notebook process is terminated.
