### ISSUE TITLE
Move shuffling-data-loader-benchmarks data to us-west

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#27147]
This bucket has data for nightly tests but is located in us-east. As we run tests in us-west, this unnecessarily hurts performance and increases cost.

We should "move" (semantically) this bucket to the us-west:
- Create a copy bucket (e.g. shuffling-data-loader-benchmarks-2)
- Delete the shuffling-data-loader-benchmarks bucket
- Re-create shuffling-data-loader-benchmarks (in us-west)
- Copy data from shuffling-data-loader-benchmarks-2 to shuffling-data-loader-benchmarks

This will interrupt the tests shortly, but generally deemed fine for nightly tests. However, we'd like to ensure release tests are not interrupted.

@scv119 LMK when the release tests are done and there is a 2+ hours slot for making the above move (and re-assign this back to me).

**Comment by ckw017** [comment]
Done
