### ISSUE TITLE
[Core] Deprecation annotation doesn't print deprecation wargnins 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#27145]
### What happened + What you expected to happen

Current `@deprecate` annotation doesn't print deprecation warnings because it doesn't have any code that does that. It only modifieds the docstring to mark the API is deprecated

We should fix this and make sure to verify deprecation warnings are printed correctly from deprecated APIs

### Versions / Dependencies

Master

### Reproduction script

Call `ray.get_runtime_context().node_id` (which is deprecated)

**Comment by scv119** [comment]
https://github.com/ray-project/ray/pull/31198
