### ISSUE TITLE
[CI]  //python/ray/tests:test_placement_group_scheduling_warning is failing 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27173]
### What happened + What you expected to happen

//python/ray/tests:test_placement_group_scheduling_warning is failing due to version string mismatch https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824270-e278-432c-8f26-42741c863dc6

please unbreak it now.

### Versions / Dependencies

releases/2.0.0 branch

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by jianoaix** [comment]
This might be the same issue as [#27176](https://github.com/ray-project/ray/issues/27176)

**Comment by rkooo567** [comment]
I think @jianoaix is right. Let's see if merging that PR fixes this issue.
