### ISSUE TITLE
[CI][Windows] test_storage failing on Windows

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27175]
### What happened + What you expected to happen

[CI][Windows] test_storage failing on Windows https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824255-06e2-42ec-bde7-9e4b5897f8b7

please unbreak it now

### Versions / Dependencies

latest ray

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by iycheng** [comment]
@suquark  could you give this a look?

**Comment by iycheng** [comment]
I think maybe let's skip it for now.

**Comment by suquark** [comment]
It seems a failure of `tests:test_storage`, not `test_storage` in workflow (the later should be the reason that we are assigned, I believe?). But let me take a look anyway.

**Comment by suquark** [comment]
The cause should be there are a leakage of Ray cluster from other tests; and because `ray.init` connects to existing cluster by default now, it connects to the existing cluster with `strorage=...`. That's why it failed.
