### ISSUE TITLE
[CI] //python/ray/workflow:tests/test_events timeout 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27178]
### What happened + What you expected to happen

//python/ray/workflow:tests/test_events timeout https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824276-86fa-4042-a879-14328448e942

please unbreak now

### Versions / Dependencies

releases/2.0.0

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by suquark** [comment]
should already be fixed by https://github.com/ray-project/ray/pull/27124. let's wait and see if it works or not

**Comment by scv119** [comment]
@suquark @iycheng send the cherry-pick PR?
