### ISSUE TITLE
[CI] Java test is failing on 2.0 branch

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27172]
### What happened + What you expected to happen

Java test is failing on 2.0 branch https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824270-e1f5-449e-a71d-6603cb092910

Please unbreak it now

### Versions / Dependencies

ray 2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by SongGuyang** [comment]
Thanks for this issue. Try to fix it https://github.com/ray-project/ray/pull/27183
