### ISSUE TITLE
[2.0][nightly] datasets_ingest_train_infer failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27181]
### What happened + What you expected to happen

 https://buildkite.com/ray-project/release-tests-branch/builds/833#018242a3-4dd2-4c10-9877-27caffe5f4a3

### Versions / Dependencies

releases/2.0.0

### Reproduction script

nightly test

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
The test timeout before training stage. Based on the truncated log remained from the stdout, it seems it never started the training. It should have print "Starting training..." after printing the Net's parameters. 

https://github.com/ray-project/ray/blob/baa14d695aafd0abb817026ddd4b4182f68f6b61/release/nightly_tests/dataset/ray_sgd_training.py#L336-L341

Had a few tries trying to reproduce the timeout but couldn't


One difference the timeout run had with the normal runs is: one of the trainer doesn't have GPU available: 
````
[2m[36m(BaseWorkerMixin pid=323, ip=10.0.0.213)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.33)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.28)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.66)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.61)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.8)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.147)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=298, ip=10.0.0.171)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=298, ip=10.0.0.117)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.202)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.245)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.80)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=299, ip=10.0.0.27)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.143)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.222)[0m Device: cuda:0
[2m[36m(BaseWorkerMixin pid=300, ip=10.0.0.108)[0m Device: cpu
```

Could someone know more about the behaviour of trainer and this workload comment if this will have the program stuck? 

@scv119 @matthewdeng

**Comment by rickyyx** [comment]
Retry succeeds on buildkite: https://buildkite.com/ray-project/release-tests-branch/builds/833#018245dc-10e1-40bb-9082-9a412692d392
