### ISSUE TITLE
[2.0][nightly] air_benchmark_xgboost_cpu_10 is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27185]
### What happened + What you expected to happen

 https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0ad6-430a-8256-910d336be1ce

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
Will be fixed by this pick: https://github.com/ray-project/ray/pull/27158

(already merged on master).

Successful run with 2.0.0 wheels: https://buildkite.com/ray-project/release-tests-pr/builds/11606#018243b9-54c8-4bad-b78d-2c39322c8bb5
