### ISSUE TITLE
[2.0][nightly] rllib_multi_gpu_with_lstm_learning_tests failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27188]
### What happened + What you expected to happen

7. rllib_multi_gpu_with_lstm_learning_tests https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0cb4-4ee9-8fba-40f4e2174fdc

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
https://github.com/ray-project/ray/pull/27207
