### ISSUE TITLE
[2.0][nightly] 8. serve_serve_cluster_fault_tolerance failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27189]
### What happened + What you expected to happen

8. serve_serve_cluster_fault_tolerance https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0d2c-4a28-b308-01092a229679

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
ack looking

**Comment by simon-mo** [comment]
API change broke it; sending fix PR now..

**Comment by simon-mo** [comment]
PR sent, please feel free to merge and disable this test.

**Comment by simon-mo** [comment]
Cherry pick PR https://github.com/ray-project/ray/pull/27206
