### ISSUE TITLE
[2.0][nightly] ml_user_tune_rllib_connect_test failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27186]
### What happened + What you expected to happen

5. ml_user_tune_rllib_connect_test https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0c38-4959-8f71-5e86f882c671

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
Will be closed by this pick: https://github.com/ray-project/ray/pull/27162

(already merged on master)
