### ISSUE TITLE
[2.0][nightly]  rllib_multi_gpu_learning_tests failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27187]
### What happened + What you expected to happen

 rllib_multi_gpu_learning_tests https://buildkite.com/ray-project/release-tests-branch/builds/831#01824205-0cad-48a1-9df6-b3eb7917fee8

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
https://github.com/ray-project/ray/pull/27207
