### ISSUE TITLE
[Flaky dashboard] Broken test on 2.0 branch doesn't appear in the master branch and flaky dashboard 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#27190]
### What happened + What you expected to happen

E.g., https://github.com/ray-project/ray/issues/27173

It is broken in 2.0 branch, but it doesn't appear in the flaky dashboard.

Same for https://github.com/ray-project/ray/issues/27172

cc @simon-mo 

### Versions / Dependencies

master

### Reproduction script

N/A

**Comment by rkooo567** [comment]
cc @scv119 

@simon-mo can you quicky check why it is the case?

**Comment by simon-mo** [comment]
> //python/ray/tests:test_placement_group_scheduling_warning is failing due to version string mismatch https://buildkite.com/ray-project/ray-builders-branch/builds/9013#01824270-e278-432c-8f26-42741c863dc6

Working as intended? The version string IS different on master vs release branches?

Java is being fixed.

**Comment by rkooo567** [comment]
It was because of some release branch specific code. Closing it
