### ISSUE TITLE
[AIR] Fix  //doc/source/tune/examples:sigopt_example

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#27203]
### What happened + What you expected to happen

Notebook is broken due to missing permission first, maybe more issues down the road. @Yard1 looked into it earlier and we're creating this issue to keep track of it.

### Versions / Dependencies

master

### Reproduction script

`bazel test //doc/source/tune/examples:sigopt_example`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Yard1** [comment]
Duplicate of https://github.com/ray-project/ray/issues/26567
