### ISSUE TITLE
Logging prefix no longer showing

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#27220]
### What happened + What you expected to happen

The Ray logging prefix seems to have vanished:

```
>>> ray.data.range(1)
⚠️  The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
Dataset(num_blocks=1, num_rows=1, schema=<class 'int'>)
```

You used to get the WARN, file name, etc. before the message.

### Versions / Dependencies

master

### Reproduction script

see above

**Comment by scv119** [comment]
@rkooo567 @rickyyx in case you changed anything recently?

**Comment by rkooo567** [comment]
After the initial bisect, it seems like this is from this PR: https://github.com/ray-project/ray/pull/26678. Keep looking
