### ISSUE TITLE
[Data] run small scale of dataset chaos integration test in CI

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27257]
### What happened + What you expected to happen

Today we run a bunch of dataset chaos test in nightly test to catch regressions. However, a lot of them can be easily caught by **a multi-node integration tests** running in CI/buildkite instead. 
we should do that, which saves a lot of money and makes it easier/faster to detect regressions.

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
@matthewdeng @c21 this looks important, can you help triage?

**Comment by c21** [comment]
@scv119 - this is a good idea, I will look into it.

**Comment by c21** [comment]
We are gradually adding the tests, example - https://github.com/ray-project/ray/blob/master/release/release_tests.yaml#L6549 . Closing this issue.
