### ISSUE TITLE
Fail to start the agent

### ISSUE THREAD

**Issue by lupan2005** [ray-project/ray#2726]
I tried to setup  a ray cluster but failed to start the agent.  Below is the screen capture:
$ sshpass -p lupan parallel-ssh -P -H 10.212.146.98 -l lupan -A 'ray stop'
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
[1] 11:58:25 [SUCCESS] 10.212.146.98

$ sshpass -p lupan parallel-ssh -P -H 10.213.64.152 -l lupan -A 'ray stop'
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
[1] 11:58:32 [SUCCESS] 10.213.64.152

$ sshpass -p lupan parallel-ssh -P -H 10.213.64.152 -l lupan -A 'ray start --head --redis-port=6394'
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
10.213.64.152: Using IP address 10.213.64.152 for this node.
{'node_ip_address': '10.213.64.152', 'raylet_socket_names': [], 'local_scheduler_socket_names': ['/tmp/scheduler50793460'], 'redis_address': '10.213.64.152:6394', 'object_store_addresses': [ObjectStoreAddress(name='/tmp/plasma_store83038804', manager_name='/tmp/plasma_manager46963667', manager_port=39606)], 'webui_url': 'http://localhost:8888/notebooks/ray_ui83717.ipynb?token=bceff9c2b8b60fa39982bab0782f7e97d6de15fa3d7a8399'}

Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 10.213.64.152:6394

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="10.213.64.152:6394")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
[1] 11:59:00 [SUCCESS] 10.213.64.152

$ sshpass -p lupan parallel-ssh -P -H 10.212.146.98 -l lupan -A 'ray start --redis-address 10.213.64.152:6394'
Warning: do not enter your password if anyone else has superuser
privileges or access to your account.
[1] 11:59:17 [FAILURE] 10.212.146.98 Exited with error code 1
$ Exited with error code 1
Exited: command not found
$

**Comment by richardliaw** [comment]
Can you try `sshpass -p lupan parallel-ssh -P -H 10.212.146.98 -l lupan
-A 'which ray'`?

And also, what version of Ray do you have on that machine? (i.e., is it
installed from pip or wheels or source?)
