### ISSUE TITLE
[2.0][Data] chaos_pipelined_ingestion_* tests failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27265]
### What happened + What you expected to happen

the [chaos_pipelined_ingestion_..](https://buildkite.com/ray-project/release-tests-branch/builds/837#01824a5f-cac7-4678-8b7d-3d1e7d9276b6) is still failing while the non-pipelined chaos tests are now passing after https://github.com/ray-project/ray/pull/27149 fix the split ownership. We should drill down to this and see why it failed.

### Versions / Dependencies

releases/2.0.0
this should fail on master as well.

### Reproduction script

run release test

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
cc @c21 @jjyao @jianoaix @matthewdeng

**Comment by scv119** [comment]
recent failures on master:
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_mjSqcfTS3Cmg8PjnCbJ3uFaq

**Comment by scv119** [comment]
https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_EAW7ndR7UUia8CVtiPBGU2mH
--

**Comment by jianoaix** [comment]
oh, the OwnerDiedError is back:
ray.exceptions.OwnerDiedError: Failed to retrieve object 0062b6757247b5dfffffffffffffffffffffffff0300000002000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.
