### ISSUE TITLE
[2.0][Nightly]  ml_user_ray_lightning_user_test_master is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27274]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/837#0182494c-c441-4a80-bbd7-172f03886d1b

this failed with latest nightly release build. is this a rc0 release blocker @matthewdeng ?

### Versions / Dependencies

releases/2.0.0

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by JiahaoYao** [comment]
sounds good

**Comment by matthewdeng** [comment]
Not a release blocker, just test dependency needs to be pinned.

**Comment by JiahaoYao** [comment]
@scv119 @matthewdeng this will unbreak this https://github.com/ray-project/ray/pull/27290, do u want to merge?

**Comment by JiahaoYao** [comment]
and how to do the release test by my self?

**Comment by matthewdeng** [comment]
Fixed by https://github.com/ray-project/ray/pull/27418
