### ISSUE TITLE
[Core] PlacementGroup `wait` hangs with infeasible placement group

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#27287]
### What happened + What you expected to happen

Running the below script hangs. I would expect `pg.wait(1)` to finish after 1 second and return False since the PlacementGroup is not feasible.

### Versions / Dependencies

Ray master

### Reproduction script

```python
import ray
ray.init(num_cpus=1)
from ray.util import placement_group
pg = placement_group(bundles=[{"CPU": 2}])
ready = pg.wait(1) # Hangs forever
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
Looks like this happens from 1.13 too. It is a critical issue because the `wait` API should return in the given second.

Will take a look soon.

**Comment by rkooo567** [comment]
Ricky is off for a week. I will fix it

**Comment by scv119** [comment]
@rickyyx @rkooo567 are we working on this one?

**Comment by rickyyx** [comment]
guess it's time to pass back to me lol - Sang is OOO next week.
