### ISSUE TITLE
[doc][tune] Annotated Examples + Link to Tutorial

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2728]
### Describe the problem
It would be great to annotate a couple key examples (i.e., Keras, PyTorch) for Tune on the documentation page and also some notes on the source code README.

A FAQ would be nice, now that more issues have been raised.

**Comment by roshansridhar** [comment]
I looked through the previous issues and found a trainable function example for pytorch but unable to get a trainable class working. Could we get an example of that?

**Comment by richardliaw** [comment]
Working on this in #2708.
