### ISSUE TITLE
[Data] ValueError in TableRow for dataset with numpy arrays in cells

### ISSUE THREAD

**Issue by marcm-ml** [ray-project/ray#27305]
### What happened + What you expected to happen

When I create ray datasets from pandas dataframes that include some n-dim numpy arrays in its cells, I get an error when printing a ```ray.data.TableRow``` object. This happens with any function that returns those objects, e.g. ```ds.show```, ```ds.iter_rows``` but not ```ds.iter_batches``` which simply works (see reproduction script below). I first encountered this when I wanted to read audio data (which is inherintely an array) by using ```dt.read_from_binary(..)``` and then transforming the data to arrays using soundfile module and ```ds.map_batches```.

I don't know if I am doing something wrong or if this is actualy a bug.

Side note:
If I work purely in pandas, this error does not occur.

The error:
```python
File /usr/local/lib/python3.9/site-packages/ray/data/dataset.py:1731, in Dataset.show(self, limit)
   1723 """Print up to the given number of records from the dataset.
   1724 
   1725 Time complexity: O(limit specified)
   (...)
   1728     limit: The max number of records to print.
   1729 """
   1730 for row in self.take(limit):
-> 1731     print(row)

File /usr/local/lib/python3.9/site-packages/ray/data/row.py:36, in TableRow.__str__(self)
     35 def __str__(self):
---> 36     return str(self.as_pydict())

File /usr/local/lib/python3.9/site-packages/ray/data/row.py:33, in TableRow.as_pydict(self)
     30 def as_pydict(self) -> dict:
     31     """
     32     Convert to a normal Python dict. This will create a new copy of the row."""
...
     60 except AttributeError:
     61     # Fallback to the original form.
     62     return item

ValueError: can only convert an array of size 1 to a Python scalar
```

### Versions / Dependencies

numpy==1.22.4
pandas==1.4.3
ray==1.13.0

### Reproduction script

```python
import pandas as pd
import numpy as np
import ray
import ray.data as rd

ray.init()

data = pd.DataFrame({"array": [np.random.randn(10)]})

ds = rd.from_pandas(data)

batch = next(ds.iter_batches())  # works
print(type(batch["array"].iloc[0]))  # ndarray

# next(ds.iter_rows())       # throws error
ds.show()                    # throws error
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Hey @marcm-ml, I just tried this out with Ray version 2.0.1 and it seems to be fixed! Please re-open if you have any other issues.
