### ISSUE TITLE
[core] PlacementGroupSchedulingStrategy does not support placement_group=None

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#27328]
### What happened + What you expected to happen

The docstring says

```
    Attributes:
        placement_group: the placement group this actor belongs to,
            or None if it doesn't belong to any group.
```

but the implementation says:

```
        if placement_group is None:
            raise ValueError(
                "placement_group needs to be an instance of PlacementGroup"
            )
```

We should either adjust the docstring or allow None again.

It seems like passing `scheduling_strategy="DEFAULT"` achieves the same job, though this is not well documented.

### Versions / Dependencies

Master, 2.0.0rc0

### Reproduction script

```
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy

PlacementGroupSchedulingStrategy(placement_group=None)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
cc @jjyao this looks like a regression. Can you confirm that?

**Comment by jjyao** [comment]
Thanks @krfricke for catching this!

@rkooo567 I thought it's working and it's already mentioned in the ray pg doc. But apparently this is not the case and code snippet in the doc is not tested by CI so we didn't catch this earlier. I'll fix this.
