### ISSUE TITLE
[AIR][Image] Improve error message for ImageFolderDatasource when size/mode is missing

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#27329]
### Description

For an image dataset that consists of images of various sizes and mode (grayscale, rgb) we would run into issues regarding ensuring all image tensors we're dealing with are uniform in size (H, W, C) when TensorArray auto casting is by default enabled.

```python
    dataset = ray.data.read_datasource(
        ImageFolderDatasource(), root=files_dir, size=(300, 300), mode="RGB"
    )
```

## If we miss "mode"

```python
    dataset = ray.data.read_datasource(
        ImageFolderDatasource(), root=files_dir, size=(300, 300)
    )
```
Error message  -  https://gist.github.com/jiaodong/3ddaf99666c599b0c8409ef9bffb8d88

## If we miss "size"

```python
    dataset = ray.data.read_datasource(
        ImageFolderDatasource(), root=files_dir, mode="RGB"
    )
```

Error message  -  https://gist.github.com/jiaodong/feebe20566ff8231e3c3355bd7d124dd

## Work to be done

For both cases, the error message is somewhat not super actionable -- changing auto casting flag, figure how to use TensorArray and change their implementation. But the issue can be easily resolved by just applying both flags. We should improve error message to make it simple for user to just get it right upstream.

This also helps to simplify our dataset memory size estimation, since statically given size + mode = static in-memory size.

**Comment by bveeramani** [comment]
Closing because I don't think this is an issue anymore:

```python
import numpy as np
from PIL import Image

import ray

image0 = Image.fromarray(np.zeros((512, 512, 3), dtype=np.uint8))
image1 = Image.fromarray(np.zeros((100, 100, 3), dtype=np.uint8))
image2 = Image.fromarray(np.zeros((100, 100), dtype=np.uint8))
image0.save("/tmp/image0.png")
image1.save("/tmp/image1.png")
image2.save("/tmp/image2.png")


ds = ray.data.read_images("/tmp").materialize()
```
