### ISSUE TITLE
[core] Update memory accounting 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#27336]
### What happened + What you expected to happen

Right now we compute total system memory by looking at the limit set by cgroup if it exists or fall back to system info (e.g. meminfo for linux), and then take the smaller of the two values. And we do the same for calculating used memory.

But this leads to inconsistency. Cgroup used memory could be higher or lower than what is computed by system info, which is based on mem total - mem available from meminfo (linux). This leads to the situation where we usually just take the used memory from system info, even when Ray is running within a Docker.

Based on the current logic the behavior is as follows:
A) Ray managed by cgroup with memory limit set to 'unlimited'
- the memory limit is from OS, memory usage is from OS --> usage should be from cgroup

B) Ray managed by cgroup with memory limit set (a value smaller than total memory)
- the memory limit is from cgroup, memory usage is from OS --> usage should be from cgroup

C) Ray not managed by cgroup
- the memory limit is from OS, memory usage is from OS --> working as intended

As part of this work we should also clean up how memory should be tracked in Ray. 
- Make sure the memory tracked is consistent between the code in c++ and the agent (P0)
- Support cgroup v1 and v2 / docker (P0) 
- Don't contradict with the K8s memory tracker / pod-based memory pressure eviction (P0)
- non-docker (P1)

### Versions / Dependencies

latest

### Reproduction script

This is needed for Ray-based memory management work

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarng** [comment]
A  instance of memory accounting in our dashboard, showing memory from object store tracked in the worker

![Image](https://user-images.githubusercontent.com/22830327/183219020-598f8c17-ffb8-4bb7-900f-13122dac31fc.png)

**Comment by hora-anyscale** [comment]
Per Triage Sync: @clarng what use cases are impacted here?

Cc: @ericl

**Comment by clarng** [comment]
Addressed by https://github.com/ray-project/ray/pull/29103 (cgroup v1)

and tracking the cgroup v2 change in https://github.com/ray-project/ray/issues/29474

**Comment by clarng** [comment]
> Per Triage Sync: @clarng what use cases are impacted here?
> 
> Cc: @ericl

The impact is the user may see inconsistency between how memory is reported in Ray vs other modules like cadviser that is used for docker, the user may also see memory accounting issues where the node may have (or not have) memory when it is otherwise, making it difficult to debug when there is a issue that might be related to memory usage
