### ISSUE TITLE
[Datasets] Avoid unnecessary execution/read to improve `limit()` performance 

### ISSUE THREAD

**Issue by c21** [ray-project/ray#27340]
### Description

Current dataset.limit() calls into `_split_at_indices()` and it foces executing of all blocks before split - https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/split.py#L257 . This is bad for performance because if user runs limit(N) on a large dataset with small N numbers of rows, it would foce run the whole dataset and immediately drop most of rows.

In `limit()`, we should look into number of rows from each block's metadata, and discards the unused blocks before split.

### Use case

Improve the performance for a typical use case when user has a large data source and only wants to reads a small portion of rows from it. `ds.read_xxx().limit(N)`

**Comment by c21** [comment]
Assigning to @clarkzinzow as he already has a fix on the fly!

**Comment by matthewdeng** [comment]
Hmm for performance would this require adding back optimized support for  `_split_at_index(return_right_half=False)`?

**Comment by matthewdeng** [comment]
What about other use-cases? Does this apply to datasets with blocks that contain more than 1 row per file? Any reason to not generalize `_split_at_index` to contain this logic?

**Comment by c21** [comment]
@matthewdeng it should work for block with more than 1 row. But I got your point @matthewdeng, let's wait for @clarkzinzow as he is doing the PR. Good code review question!
