### ISSUE TITLE
[ci] Mac CI is not reporting the right status in buildkite

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#27358]
### What happened + What you expected to happen

Here the test failed, but the tab there is still green. We should make the tab red if there is anything failed:

https://buildkite.com/ray-project/ray-builders-branch/builds/9136#01825b2a-51fd-4ffb-9e76-9d2b871585ee

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/ray-builders-branch/builds/9136#01825b2a-51fd-4ffb-9e76-9d2b871585ee

### Issue Severity

High: It blocks me from completing my task.

**Comment by iycheng** [comment]
@simon-mo  I'm not sure what's happening, but somehow the buildkite doesn't show the right result. I feel this is important since we are using this to merge PR.

**Comment by simon-mo** [comment]
I don't have the bandwidth at the moment. Can any oncalls help take a look?

**Comment by simon-mo** [comment]
I think @jjyao recently fixed it for windows.

**Comment by iycheng** [comment]
@jjyao do you know the root cause of this? (if you don't know this and have no bandwith, we can try to get some oncall working on this)

**Comment by rickyyx** [comment]
Seems either buildkite doesn't pick up the bazel failure (likely the case), or bazel doesn't exit with errors. I am trying to reproduce it somewhere. 

For now, please do look over the top sections of the build 
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/11676094/182715181-f778dcc8-c8e3-4548-9035-f37c82575e50.png">

**Comment by rickyyx** [comment]
This should be fixed by https://github.com/ray-project/ray/commit/5298ee83b2a261e08ddade76681d1f933f273ad0
