### ISSUE TITLE
[Core] Support `rediss://` - TCP protected external Redis instances

### ISSUE THREAD

**Issue by zoltan-fedor** [ray-project/ray#27371]
### Description

While external Redis instances are supported, it seems that TCP protected Redis instances (which are called with `rediss://`) are not supported.

In the `RAY_REDIS_ADDRESS` env variable you can't supply `rediss://{IP | HOST}:{PORT}`, as it only expects `{IP | HOST}:{PORT}` and doesn't use the `rediss://` schema part.

This would be helpful, as for Ray HA you should be using Redis HA - which is what cloud providers (Azure Cache for Redis, AWS Elasticache) offer, but they are usually setup with TCP protection (eg `rediss://`).

The need for `rediss://` support has already been mentioned earlier at https://github.com/ray-project/ray/issues/17400#issuecomment-901637069, but it seems it was never acted on.

### Use case

The use case is to to connect to cloud-provided Redis instances (Azure Cache for Redis, AWS Elasticache, etc) - which are typically HA Redis instances, but also require `rediss://` for TCP protected connections.

Currently with Ray you cannot use `rediss://` instances as external storage.

**Comment by iycheng** [comment]
Discussed it offline with @zoltan-fedor and here is some conclusions:

- hiredis support ssl https://github.com/redis/hiredis/blob/c78d0926bf169670d15cfc1214e4f5d21673396b/README.md#ssltls-support So we are going to use that
- We'll introduce more os envs related to this. So the certs are passed by os envs.
- We'll support `rediss://host:ip`, `redis://host:ip` the former one will create a secured context and the latter one is just like `host:ip`.
- Password will be sent from `ray start --head --redis-password` for now. Later refactoring is necessary to make it better.

The backend storage support right now is not pluggable, we should make it more general and easy to extend to support other storages and at that time, we'll revisit the APIs here and make it better.

**Comment by iycheng** [comment]
Lower the priority to P0 given that we are not able to support this in ray  2.0. We'll defer this feature in ray 2.1.
