### ISSUE TITLE
[Core][nightly] autoscaling_shuffle_1tb_1000_partitions is failing 

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27378]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_HcQ71ka5v6XYfE16WKLXBuME?command-history-section=command_history

### Versions / Dependencies

latest ray

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
Did some bisecting it seems the test is just running slower. I also can't reproduce it on OSS cluster, so it's highly likely due to the test infra change. Specifically https://github.com/anyscale/product/issues/12829

**Comment by hora-anyscale** [comment]
Per Triage Sync: Flaky test
