### ISSUE TITLE
Force implementation of get_initial_state method in subclasses

### ISSUE THREAD

**Issue by eringrant** [ray-project/ray#2739]
By default, any subclass of `PolicyGraph` is assumed not to be stateful, as the default initial state is set to null: 
https://github.com/ray-project/ray/blob/aa014af85b551d37bc77179b3aaeafccc848aec0/python/ray/rllib/evaluation/policy_graph.py#L160

I would suggest raising a `NotImplementedError` here so that the user decides whether or not the policy is stateful across timesteps (without subclassing a child of `PolicyGraph`).

**Comment by ericl** [comment]
Yeah I think this would be very helpful for custom policy implementations. Would you be interested in submitting a patch?

**Comment by simon-mo** [comment]
@sven1977 @ericl is this still an issue? It so please re-open
