### ISSUE TITLE
[tune] Add option to checkpoint model at end of training

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2740]
### Describe the problem
Currently we checkpoint models only periodically. However this might not coincide with the exact end of training. It would also be useful to add an option to checkpoint them while terminating a trial, so that the user can retrieve the final parameters as well as the final score.

**Comment by Kaahan** [comment]
Would we want this to be added to the experiment options (where checkpoint frequency is set)? Or somewhere in the trail runner?

**Comment by ericl** [comment]
I think it makes sense to be at the same place checkpoint_freq is set, for consistency. That way, it can also work with RLlib: https://github.com/ray-project/ray/issues/2742

**Comment by Kaahan** [comment]
Makes sense, I'll take a shot at it
