### ISSUE TITLE
Issue on page /train/examples/train_fashion_mnist_example.html

### ISSUE THREAD

**Issue by ming-shy** [ray-project/ray#27419]
1.I just copied the example from the official documentation, and it didn't get any errors or log output, and it felt like it was running forever without knowing if it was actually executing.

2.Also how to use RAY Train on K8S? Note: The RAY cluster has been deployed on K8S without errors.

3.Examples provided in official documentation are completely inoperable, unpractical, and difficult to understand.

**Comment by jjyao** [comment]
@amogkam Could you take a look at this issue?

**Comment by amogkam** [comment]
Hey @ming-shy, apologies for the late response!

We would really like to help you out here. Are you still running into this issue? It would help if you can paste your cluster configuration and the stdout you are seeing when running the example.

I am also happy to pair program with you to get this working for you. Let me know if that would help! Thanks!

**Comment by richardliaw** [comment]
Going to close this out for now since it's likely that @ming-shy has moved on - but please feel free to get back to us @ming-shy !
