### ISSUE TITLE
Save checkpoint when the training ends 

### ISSUE THREAD

**Issue by RodgerLuo** [ray-project/ray#2742]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from**: Source  
- **Ray version**: 0.5.0
- **Python version**: 3.6

### Describe the problem

It seems the checkpoint of the last iteration cannot be saved when "stop" is activated. 

For example, for the hyper-parameters below:

    pendulum-apex-ddpg:
        env: Pendulum-v0
        run: APEX_DDPG
        checkpoint_freq: 1
        stop:
            episode_reward_mean: -160

The checkpoint when the episode_reward_mean hits -160 is not saved. It would be nice to have this feature so the optimal model from the training can be obtained.

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/2740 (coincidentally, just reported earlier today)
