### ISSUE TITLE
[rllib] Ape-X support for multi-agent

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2743]
### Describe the problem

Currently IMPALA and Ape-X don't support multi-agent. This is relatively straightforward for fix:
- for ape-x, we just need to keep a replay buffer per policy (similar to SyncReplayOptimizer).

**Comment by sanjeevanahilan** [comment]
I'm curious for an update on this. I tried multi-agent training with IMPALA and training seemed to progress fine according to my various performance metrics on tensorboard. However, when restoring from checkpoint, despite a successful restore the policies revert to being completely untrained:

`(pid=32676) 2019-12-13 11:20:15,817	INFO trainable.py:358 -- Restored from checkpoint: /home/sanjeevan/ray_results/simple_target_speed_varies/IMPALA_MultiEnv_0_2019-12-12_17-36-26k0dbeik2/checkpoint_700/checkpoint-700`

I regularly use PPO in the exact same set up (decentralised multi-agent training) and have had no issues restoring the trained policy.

**Comment by simonsays1980** [comment]
@sven1977 Can we close this? APEX-DQN and APEX-DDPG as well as IMPALA exist now for Multi-Agent. 

See [documentation](https://docs.ray.io/en/latest/rllib/rllib-algorithms.html)
