### ISSUE TITLE
Default Concurrency Group section python block missing a bracket

### ISSUE THREAD

**Issue by wjrforcyber** [ray-project/ray#27430]
### Description

A right bracket is missing.

### Link

https://docs.ray.io/en/latest/ray-core/actors/concurrency_group_api.html

In **Default Concurrency Group** section, a right bracket in python block after "io":2 is missing, this error is only on this website, the repository is fine.

`@ray.remote(concurrency_groups={"io": 2)`

**Comment by jovany-wang** [comment]
Good catch! Could you post a PR to fix it? And I think it should be picked to 2.0.0. @scv119 CC

**Comment by wjrforcyber** [comment]
> Good catch! Could you post a PR to fix it? And I think it should be picked to 2.0.0. @scv119 CC

Like I said, I want to fix and PR it but it seems the doc in GitHub is correct, only the one on the website missing a bracket...😂

**Comment by jovany-wang** [comment]
Hum. It fixed in https://github.com/ray-project/ray/pull/24532

I think there is no need to fix on the released version.

**Comment by jovany-wang** [comment]
Feel free to reopen it once you have any question.
