### ISSUE TITLE
Ray 2.0rc0 released -- `pip install "ray==2.0.0rc0"`!

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#27477]
### Description

Hi community!

Ray team just published the first release candidate (`rc0`) of the upcoming 2.0.0 release! This will be a major release after about two years of the 1.x line, with many new features including [Ray AI Runtime](https://docs.ray.io/en/master/ray-air/getting-started.html) (Beta), [KubeRay](https://docs.ray.io/en/master/cluster/cluster_under_construction/ray-clusters-on-kubernetes/index.html) (Beta), and more!

Having a **high quality** release is our utmost priority, and your feedback on the release candidate would be tremendously valuable for this purpose.

Please `pip install "ray==2.0.0rc0"` and share your feedback! Either of the below works:
- The [ray-2-0-feedbacks](https://join.slack.com/share/enQtMzg5MzE0NTU4NzIzNS0zNDg3MzYxNTMzN2E2ZGY5NWQ5YzliZjg1Yjc5YWI5ZmYwM2FjYzM5NDU2YTM4NTEzYTVmMDM1ZjFmZGIwNDA4) Slack channel
- discuss.ray.io 
- File issues here

Thanks!

**Comment by aabmets** [comment]
Is Ray 2.0 compatible with Python 3.10?

**Comment by aabmets** [comment]
@zhe-thoughts 
Is Ray 2.0 compatible with Python 3.10?

**Comment by zhe-thoughts** [comment]
@aabmets Ray 2.0 has experimental level support for Python 3.10. More work is ongoing under https://github.com/ray-project/ray/pull/21221. cc @pcmoritz

**Comment by acxz** [comment]
With the actual release of ray 2.0.0, should this issue be closed, @zhe-thoughts?

**Comment by zhe-thoughts** [comment]
@acxz Yup absolutely. Thanks for the note!
