### ISSUE TITLE
[AIR] Make `MultiHotEncoder` consistent with `OneHotEncoder`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#27484]
### Description

Make `MultiHotEncoder` create a new column for each category instead of modifying the input column in place. Additionally, update `OneHotEncoder` to remove support for collections of categories. 

**Before**
```
                            name      genre
0                 Shaolin Soccer  [1, 1, 1]
1                          Moana  [1, 1, 0]
2  The Smartest Guys in the Room  [0, 0, 0]
```

**After**
```
                            name      column_action   column_comedy    column_sports
0                 Shaolin Soccer 
1                          Moana
2  The Smartest Guys in the Room
```

### Use case

This makes `MultiHotEncoder` consistent with `OneHotEncoder`, which produces a new column for each category. 

```
>>> encoder = OneHotEncoder(columns=["color"])
>>> encoder.fit_transform(ds).to_pandas()
           color_blue  color_green  color_red
        0           0            0          1
        1           0            1          0
        2           0            0          1
        3           0            0          1
        4           1            0          0
        5           0            1          0
```

This change would also make it easier to use to `Concatenator` preprocessor.

**Comment by Yard1** [comment]
Hey @bveeramani this would go contrary to the point of MultiHotEncoder. It is supposed to maintain the same number of columns (see https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html for reference). The output you suggest can already be obtained with OneHotEncoder, so this would also be just duplicating functionality.

**Comment by bveeramani** [comment]
I'm not sure if I understand. Could you explain why we'd maintain the same number of columns with `MultiHotEncoder` but not `OneHotEncoder`? sklearn's `MultiLabelBinarizer` and `OneHotEncoder` implementations both transform data into an ndarray of shape (# samples, # categories).

I know you can achieve the proposed output with `OneHotEncoder`, but IMO `OneHotEncoder` shouldn't support collections of labels.  I think `OneHotEncoder` should only work with individual labels because:
* **It makes our implementation consistent with sklearn**. sklearn raises an error: `TypeError: Encoders require their input to be uniformly strings or numbers. Got ['list']`
* **It simplifies `OneHotEncoder`**. It's easier to understand and explain `OneHotEncoder` if it works with a single type of data.
* **It makes `OneHotEncoder` outputs consistent with `MultiHotEncoder` outputs.** It's confusing if two preprocessors with similar names and functions produce outputs with different schemas. 

Also, if the whole point of `MultiHotEncoder` is to maintain the same number of columns,  then `MultiHotEncoder` is already obsolete. It's functionally equivalent to `Compose(OneHotEncoder, Concatenator)`.
