### ISSUE TITLE
Discussion about job management agent

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#2748]
@robertnishihara @pcmoritz @istoica 

Hi,

There has been a lot of discussions on job submission and we're about to work on it.

Right now we're thinking about implementing the job submission with a single http portal, plus a job management agent which runs on each machine in the cluster.  

When user submits a job, http server upload the files (java jars, python scripts) for this job to a place, and write the location to GCS, and the agent running on each machine would then download the files to its local drive, and communicate with local node manager when it's ready.

The goal for the agent is to:
- download submitted job files to local drive, and communicate with Node manager on whether it's ready to execute tasks for a particular job. Java jar files can be very large, e.g. a few hundred megabytes.
- manage all the job files on local machine.
- manage sharing same libraries among different jobs.
- retrieve tasks status for a given job from local node manager, and return to http server for aggregation.

I'd like to seek your comments on this. Do you prefer that we have a separate agent for this, or do we want to put this functionality to node manager?

Thanks!

Update: Here's the current [proposal](https://docs.google.com/document/d/1LUc8ZRpm2aL6rSg5h91N7_OjodeOtEVmC1NydHMncIc/edit) to support job management.

**Comment by zhijunfu** [comment]
FYI  @eric-jj @raulchen @imzhenyu

**Comment by raulchen** [comment]
I prefer having a separate agent. Most of these logics are independent of Ray core. Whenever possible, I think it's always more preferable to keep the core simple and clean. 

However, there's one exception here. The agent should also be responsible for cancelling a job. This requires the node manager to provide some interfaces to the agent.

**Comment by robertnishihara** [comment]
Can you precisely define the term *job*? In particular, how does it relate to the current concept of *driver*. Is it essentially a one-to-one mapping?

This feels like it should *not* be in the node manager, though I haven't thought about it very deeply.

**Comment by zhijunfu** [comment]
@robertnishihara Job refers to the one discussed in this [PRD](https://docs.google.com/document/d/1yPTn6kMwIjdo_dpFBqb0_FwtNVCXEaiSwKWaLyQmUl4/edit#). Yes there's a one-to-one mapping between _job_ and _driver_, on the other hand, _job_ concept has a broader scope than a _driver_. Generally, job refers to all the tasks (directly or indirectly invoked) by a driver. 

There are a couple of differences:
- When user submits a job, he could provide job name, code files (jars or python scripts), resource requirement, priorities .etc, these all refers to the whole job instead of the driver itself.
- When the driver terminates, current raylet behaviors is other actors would continue to run, and the job would only finish until all the tasks for this job complete. 
- When user kill a job, or get a job status, this also refers to all the tasks for this job.

**Comment by zhijunfu** [comment]
@raulchen Yes job cancellation would need node manager interfaces regardless of whether we use a separate agent.  If we go with the agent approach, the agent can communicate with local node manager using local scheduler client; otherwise if we put this functionality to node manager, then http server would talk to node manager using TCP.

**Comment by robertnishihara** [comment]
@zhijunfu When a driver exits, we should clean up its state, e.g., kill its running tasks and actors, remove its tasks from the scheduling queues, etc. "Job cancellation should be able to just use the same mechanism, right?

**Comment by robertnishihara** [comment]
@zhijunfu This mechanism is already in place (though not all of the cleanup is implemented).

When a driver dies (either gracefully or ungracefully), it triggers a `DisconnectClient` message handler in the node manager, which runs this code.

https://github.com/ray-project/ray/blob/90ae8f11df178f56f39980e7a97eb96c5e4c2124/src/ray/raylet/node_manager.cc#L581-L590

This event is received by all of the other node managers and processed in 

https://github.com/ray-project/ray/blob/90ae8f11df178f56f39980e7a97eb96c5e4c2124/src/ray/raylet/node_manager.cc#L214-L224

As you can see, a bunch of cleanup still needs to be implemented, but this code path does what you described.

Nothing additional would need to be done to handle job cancellation. If there is a "job manager", it can just send a kill signal to the job process and that should trigger the above cleanup.

**Comment by zhijunfu** [comment]
@robertnishihara  Thanks for the pointers!  Hum I was actually looking at an older version of code which doesn't have the driver table stuff, which led me to think about the broadcast approach. This looks good, thanks again.

**Comment by raulchen** [comment]
I think one problem with the current mechanism is that doesn't work well for long-running programs.

We have a use case where the driver simply pulls up a bunch of long-running actors and then the actors just work on their own (sometimes indefinitely). However, because the lifecycle of the actors are bound to the driver, the driver has to be sleeping there without doing anything. Moreover, if the driver accidentally dies, the whole system may go down as well. 

If we have job management, a more natural process will be:
1) user submits a job and gets a job id;
2) driver pulls up actors and exits soon;
3) user can cancel the job at any point through a web portal

**Comment by zhijunfu** [comment]
@raulchen  One problem with that is how to determine that all the tasks and actors of a given job have completed, if we untie task/actor lifecycle from driver. 

We need to know job completion in order to properly cleanup stuff in gcs and plasma, and to return properly status when user queries job status.  Looks like it needs information from all the node managers, to make sure that there are no remaining tasks for a given job, querying GCS is not sufficient as it only contains finished/running tasks. It seems like we'd have a service which periodically queries node managers on whether a job is finished? 

An alternative way is to divide jobs into two categories: jobs that completes itself, and jobs that are long running and are supposed to be killed explicitly. In the former case actor lifecycle is still bound to driver, and in the latter case we allow actors to run after driver terminates, until the job is killed explicitly from portal. There are also some complexities in this case though.

**Comment by mylinyuzhi** [comment]
@raulchen we maybe need to  introduce a new api like Ray.driverExit().   it means the long-running driver has completed it's own work, notify the NodeManager that it wants to exit, and the actors  continue to work until the job canceled by user.

**Comment by robertnishihara** [comment]
@raulchen @mylinyuzhi What about having different semantics for "regular actors" and "named actors"? E.g.,
- "regular actor" lifetimes are always tied to the lifetime of the driver that created them
- "named actors" always persist until they are explicitly deregistered.

**Comment by raulchen** [comment]
@robertnishihara I prefer to adding a orthogonal option for resource lifecycle management, rather than binding it to named actors. Because
1) Other than actors, other resources also need to be cleaned up, e.g., objects, running tasks, per-driver info in GCS. These resources can not be bound to named actors.
2) named actors and regular actors should only differ in the way to get the actor handle, not in the behavior of lifecycle. because users sometimes may also want a regular actor to persist (no need to register it), and want a named actor to be cleaned up after driver exists (no need to always remember to deregister it).

**Comment by ericl** [comment]
Auto-closing stale issue.
