### ISSUE TITLE
[Tune: Python] Pytorch-lightning deprecated hooks in TuneReportCallback

### ISSUE THREAD

**Issue by davzaman** [ray-project/ray#27487]
### What happened + What you expected to happen

1. Getting a ton of warnings from pytorch-lightning about deprecation of certain hooks.
2. Expect no warnings.
3. The `TuneCallback` has old hooks such as [`keyboard_interrupt`](https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py#L165) which have been deprecated.
The most list of the deprecated hooks and their new versions (In pl v1.6+) are:
- `on_keyboard_interrupt` -> `on_exception`
- `on_init_start` -> just deprecated no new version
- `on_init_end` -> just deprecated no new version
- `on_batch_start` -> `on_train_batch_start`
- `on_batch_end` -> `on_train_batch_end`
- `on_epoch_end` -> `on_<train/validation/test>_epoch_end`
- `on_epoch_start` -> `on_<train/validation/test>_epoch_start`

### Versions / Dependencies

ray-tune                  1.12.1 
pytorch-lightning         1.6.5
python                    3.9.13 
(installed using mamba)
OS: Ubuntu 18.04.4 LTS (Bionic Beaver)

### Reproduction script

```python
from pytorch_lightning import Trainer, LightningModule
from torch import rand
from torch.nn import Linear
from torch.nn.functional import mse_loss
from torch.optim import Adam
from torch.utils.data import DataLoader, TensorDataset
from ray.tune.integration.pytorch_lightning import TuneReportCallback


class Model(LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = Linear(20, 4)

    def forward(self, x):
        return self.l1(x)

    def training_step(self, batch, batch_nb):
        x, y = batch
        loss = mse_loss(self(x), y)
        return loss

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=0.02)


trainer = Trainer(callbacks=[TuneReportCallback()], fast_dev_run=True)
model = Model()
dataset = TensorDataset(rand((16, 20)), rand(16))
train_loader = DataLoader(dataset, batch_size=4)
trainer.fit(model, train_loader)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
Hey @davzaman, thanks for the clean report and especially for listing out the mappings!

Would you be interested in contributing a PR for this?

**Comment by davzaman** [comment]
Hi @matthewdeng I can definitely look into it! I'll go ahead and clean it up and submit and link a PR when I think it's ready.

**Comment by davzaman** [comment]
The PR is here! #27770
