### ISSUE TITLE
[Core] Autoscaled nodes stuck in launching status 

### ISSUE THREAD

**Issue by mdagost** [ray-project/ray#27515]
### What happened + What you expected to happen

@DmitriGekhtman This is the ticket I opened in regards to [this forum issue](https://discuss.ray.io/t/aws-nodes-stuck-in-launching-when-upscaling-after-downscaling/7058) that you commented on.

I dug a bit deeper, and here is what I observed.  I launched a 5 worker cluster of on-demand instances on AWS and started a Ray Tune job running.  I went into the AWS console and manually terminated one of the instances.  I watched as ray marked the node as failed and then successfully launches a new node:

![Screen Shot 2022-08-04 at 12 34 05 PM](https://user-images.githubusercontent.com/1334817/182936163-0e434ee5-2278-4863-a048-999508620d3a.png)

However, as you can see at the bottom, there is an exception in one of the threads:

```
Traceback (most recent call last) :
File "/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run0)
File "/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ray/autoscaler/private/node_launcher.py",line101,inrun
self.prom metrics.failed create nodes.inc(count)
TypeError: inc() takes 1 positional argument but 2 were given
```

It does indeed look like there is a bug [here](https://github.com/ray-project/ray/blob/b2b11316cd0be45857b157d39ab4a89ffaf059b3/python/ray/autoscaler/_private/node_launcher.py#L124) and [here ](https://github.com/ray-project/ray/blob/b2b11316cd0be45857b157d39ab4a89ffaf059b3/python/ray/autoscaler/_private/node_launcher.py#L61). That `inc` function shouldn't have any arguments because I don't have Prometheus and it falls back to that `NullMetric` class defined [here](https://github.com/ray-project/ray/blob/b2b11316cd0be45857b157d39ab4a89ffaf059b3/python/ray/autoscaler/_private/prom_metrics.py#L194).

After the node successfully launced and Tune resumed using it, I tried killed a few more nodes and saw the behavior I'd seen before--`ray monitor` showed them as launching indefinitely but they never appeared in the AWS Console.  The log outputs just show

```
2022-08-04 18:14:55,930 INFO autoscaler.py:1219--StandardAutoscaler:Queue1newnodesforlaunch
2022-08-04 18:14:55,930 INFO monitor.py:369--
:event_summary:Adding 1 nodes of type ray_gpu_worker,
```

without any of the lines like

```
2022-08-04 17:33:38,070 INFO node provider.py:429
2022-08-04 17:33:38,070 INFO node provider.py:447
Launched 1 nodes [subnet id=subnet-Obd88b0541f8a38fc]
Launched instance i-0624e2171d5bc839b [state=pending, info=pending]
```

that you can see in the first screenshot.

Oddly enough, I killed this cluster, booted another, and tried to reproduce.  This time, when I killed the first node, it didn't start a new one.  Not sure why it would be intermittent, or if somehow the exception that got printed in the first log just didn't show up in this one.

### Versions / Dependencies

The local where is submit is running ray==1.13.0 with python 3.9.5.  The cluster is running python 3.7.7 with ray==1.13.0

### Reproduction script

There isn't an easy snippet to reproduce, but I listed steps above.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mdagost** [comment]
Confirmed that this was reproducible with a third run--launched fine with the `inc` exception after the first killed node, stuck in launching after that.

**Comment by DmitriGekhtman** [comment]
Thank you for pointing this out.
Let's start by fixing the bug.

**Comment by DmitriGekhtman** [comment]
I've opened a fix PR here.
https://github.com/ray-project/ray/pull/27532

**Comment by mdagost** [comment]
@DmitriGekhtman do you know which release this will end up in so that I can test it?

**Comment by DmitriGekhtman** [comment]
The next official release will be 2.0.0 in a week or so.
We should have a preview, 2.0.0rc1, out by Thursday!

For testing, it's also possible to deploy using the master branch -- if you are using a docker image to run Ray in the cluster, the relevant images are tagged "rayproject/ray:nightly". You can also pin a specific commit by using the first six characters of the SHA e.g. "rayrpoject/ray:f6328f".

**Comment by mdagost** [comment]
Awesome.  I'll wait for the RC.  Thanks!

**Comment by mdagost** [comment]
@DmitriGekhtman will the RC be a tag on GH that I can install?  I'm not using docker.

**Comment by mdagost** [comment]
This looks good to me now with the new rc!  I repeated the same test--manually killing instances by hand in the console--and the autoscaler successfully launches new nodes to replace them.
