### ISSUE TITLE
[Core] Autoscaled nodes stuck in launching status when AWS doesn't have capacity 

### ISSUE THREAD

**Issue by mdagost** [ray-project/ray#27521]
### What happened + What you expected to happen

I launched a cluster with 0 to 5 on-demand worker nodes and then started a Tune job.  When the Tune job started, the autoscaler tried to add 5 worker nodes.  However, there was no GPU capacity available in AWS and boto hits its max retries:

![Screen Shot 2022-08-04 at 4 36 50 PM](https://user-images.githubusercontent.com/1334817/182957186-01454361-ac82-4e9c-aa90-719d1be665c3.png)

When this happens, the nodes are stuck in a "launching" state forever, and the autoscaler never seems to try again to add any more capacity.

From looking at the source code, it appears that setting the env variable `BOTO_CREATE_MAX_RETRIES` to something very large could help to avoid this, but that's a hard workaround to discover.  This is pretty common to encounter when using GPU's, and especially when using spot instances.

### Versions / Dependencies

The local where is submit is running ray==1.13.0 with python 3.9.5. The cluster is running python 3.7.7 with ray==1.13.0

### Reproduction script

There isn't an easy snippet to reproduce, but I listed steps above.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
@DmitriGekhtman, @wuisawesome Could you take a look?

**Comment by mdagost** [comment]
This might be related to #27515 .  I can test when the release candidate comes out.

**Comment by wuisawesome** [comment]
Hmmm I think the current expected behavior is to keep retrying that error forever in case instances become available eventually. 

@mdagost can you confirm that these exceptions stop printing out (as opposed to just repeating the same exception with a slightly different timestamp)?

**Comment by mdagost** [comment]
@wuisawesome that is what I saw--they stopped printing out.  But it could be related to the other issue that I tagged.

**Comment by DmitriGekhtman** [comment]
I get the feeling it's related to the other issue. I've pinged the team for an update on the rc1 release timeline (should be quite soon).

**Comment by DmitriGekhtman** [comment]
Today or tomorrow for the rc1. Once it's ready, you can use `pip install -U "ray[default]==2.0.0rc1"` for installation.

**Comment by DmitriGekhtman** [comment]
The rc1 candidate is now available!

**Comment by mdagost** [comment]
This looks good to me now with the new rc!  When there is insufficient capacity, I see the scheduling continuing to try to launch new nodes.  I haven't verified that the new ones come up with capacity returns, but I don't see why they shouldn't.  Thanks!
