### ISSUE TITLE
[AIR] `Concatenator` is non-deterministic

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#27543]
### What happened + What you expected to happen

I tried to concatenate some columns to form a tensor, but the resulting tensor was different than I expected. I expected the tensor to have an order consistent with the input columns.

### Versions / Dependencies

**Ray**: 2.0.0rc0

### Reproduction script

Repeat this script a few times.

```
import pandas as pd
import ray
from ray.data.preprocessors import Concatenator

df = pd.DataFrame({
    "X": [0, 1, 2],
    "Y": [3, 4, 5]
})
ds = ray.data.from_pandas(df)

concatenator = Concatenator()
print(concatenator.fit_transform(ds).to_pandas())
```

You'll either get 

```
  concat_out
0     [0, 3]
1     [1, 4]
2     [2, 5]
``` 

or

```
  concat_out
0     [3, 0]
1     [4, 1]
2     [5, 2]
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
Did you check that the pandas dataframe is ordered correctly upon instantiation? AFAIK dicts are not guaranteed to be ordered right?

**Comment by bveeramani** [comment]
> Did you check that the pandas dataframe is ordered correctly upon instantiation?

Yeah. The ordering of the  transformed dataset is sometimes different than the input dataframe.

I think it's because we use `set` in `_transform_pandas`

https://github.com/ray-project/ray/blob/df124d0ad58ea7189e88f9fe42c1ee377ade9c8d/python/ray/data/preprocessors/concatenator.py#L85-L87

> AFAIK dicts are not guaranteed to be ordered right?

Dictionaries are insertion-ordered in Python 3.7.

**Comment by richardliaw** [comment]
Can you make a patch? Should be a one-line addition on L90:

```python
ordered_columns_to_concat = [col for df.columns if col in columns_to_concat]
```
