### ISSUE TITLE
[2.0][Nightly] chaos_dask_on_ray_large_scale_test_spilling failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27548]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_p9B7qwqjuaQQRAeihK6PPUVu

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by jianoaix** [comment]
It succeeded upon retrying, so might not be a real failure: https://buildkite.com/ray-project/release-tests-branch/builds/862#01826e85-c5b3-4cc9-b502-61c65f0b5ba5

Also at: https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_p9B7qwqjuaQQRAeihK6PPUVu?command-history-section=command_history
