### ISSUE TITLE
[2.0][Nightly]decision_tree_autoscaling_20_runs failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27549]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_f6AtBsMpM4ukbKxZtMEWMc4M?command-history-section=command_history

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@rickyyx can you check if this just running longer? if that's the case this is just another example of autoscaler getting slower. cc @wuisawesome

**Comment by wuisawesome** [comment]
@rickyyx can you try to repro manually? (i have a suspicion autoscaling takes longer when many release tests are run at once).

Also can we rerun the 1.13.0 version of this test (or some version that used to work), that way we can verify if it's an autoscaler or infra issue?

**Comment by rickyyx** [comment]
Running it manually, and with retry.
