### ISSUE TITLE
[2.0][nightly] rllib_learning_tests_apex failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27546]
### What happened + What you expected to happen

Looks it timed out. Please take a look!
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_4KqyqTPbi88KuUxhcMiXNiAP?command-history-section=command_history

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by kouroshHakha** [comment]
This does not seem to be a release blocker. It is running fine on both workspaces / release cluster. The error from buildkite also shows that the process was killed instead of an error. so it should be fine.
