### ISSUE TITLE
[2.0][CI] //python/ray/tune:test_actor_reuse  failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27551]
### What happened + What you expected to happen

https://buildkite.com/ray-project/ray-builders-branch/builds/9260#01826ca6-eb7d-4d44-83e8-398f5bc81dc6

### Versions / Dependencies

releses/2.0.0

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
cherry-pick PR sent out. 
https://github.com/ray-project/ray/pull/27556

**Comment by xwjiang2010** [comment]
Merged.
