### ISSUE TITLE
[2.0][CI] //python/ray/serve:test_standalone  failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27550]
### What happened + What you expected to happen

https://buildkite.com/ray-project/ray-builders-branch/builds/9260#01826ca3-babc-4c17-a086-5272736faeac

### Versions / Dependencies

releases/2.0.0

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
passed upon retry
