### ISSUE TITLE
[2.0][CI] //python/ray/tune:test_cluster failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27553]
### What happened + What you expected to happen

https://buildkite.com/ray-project/ray-builders-branch/builds/9260#01826ca6-eb9a-4783-9acf-f8e3fb18e4b4

### Versions / Dependencies

releases/2.0.0

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
dropping release-blocker after discussing with @matthewdeng
