### ISSUE TITLE
[Core] `__del__` is unexpectedly called when `ray.remote(Actor)` is GC'ed 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#27618]
### What happened + What you expected to happen

The following script prints "deleted", although it should not

```python3
import ray
ray.init()

class A:
    def __del__(self):
        print("deleted")

b = ray.remote(A)
del b
```

### Versions / Dependencies

master

### Reproduction script

look ^

**Comment by hora-anyscale** [comment]
Per Triage Sync: This is working as intended

cc: @ericl @pcmoritz

**Comment by rkooo567** [comment]
Hmm why is it working as intended? I think del is not expected to be called from the driver.
