### ISSUE TITLE
[tune/xgboost] Distributed hyper-tune on XGB by ray

### ISSUE THREAD

**Issue by creamiracle** [ray-project/ray#27638]
### What happened + What you expected to happen

Hey, I'm testing distributed XGB param-tune on two visual computers, all of them are using the same docker images.
I have done `ray start --head` to generate a master node, and use `ray start --address=xxxxx` to join the cluster on the other one.
After that I tried using the code you offer on the document, which is https://docs.ray.io/en/latest/ray-more-libs/xgboost-ray.html#hyperparameter-tuning the "Hyperparameter Tuning" part, and using `num_actors = 2 num_cpus_per_actor = 1`. By running the script, I can find some logs printed by it, but I can only see task on one ip address, such as below
+-------------------------+----------+-------------------+------------+-------------+-------------+
| Trial name              | status   | loc               |        eta |   max_depth |   subsample |
|-------------------------+----------+-------------------+------------+-------------+-------------|
| train_model_c5939_00000 | RUNNING  | 11.33.97.47:10676 | 0.00201739 |           7 |    0.755304 |
| train_model_c5939_00001 | PENDING  |                   | 0.0175339  |           7 |    0.555575 |
| train_model_c5939_00002 | PENDING  |                   | 0.00883734 |           7 |    0.716378 |
| train_model_c5939_00003 | PENDING  |                   | 0.0591364  |           6 |    0.970596 |
+-------------------------+----------+-------------------+------------+-------------+-------------+
It seems that I have not run the tunn task on both of them, I have googled for a long time, but still can't solve it, hope can get some help from you.
Thanks.

### Versions / Dependencies

python 3.7.12
ray 1.13.0
centos 7.2

### Reproduction script

```
from xgboost_ray import RayDMatrix, RayParams, train
from sklearn.datasets import load_breast_cancer

num_actors = 2
num_cpus_per_actor = 1

# Make sure to use the `get_tune_resources` method to set the `resources_per_trial`
analysis = tune.run(
    train_model,
    config=config,
    metric="train-error",
    mode="min",
    num_samples=4,
    resources_per_trial=ray_params.get_tune_resources())
print("Best hyperparameters", analysis.best_config)
```

**Comment by richardliaw** [comment]
Can you check the ray dashboard to see if actors are started on both? 

The IP address provided in the table is only for one of the actors that Tune/XGBoost starts. I suspect you'll see multiple processes started on the dashboard.

Moving forward, also recommend you check out the new XGBoostTrainer APIs for Ray: https://docs.ray.io/en/master/ray-air/key-concepts.html#trainers.

Hope that helps! Feel free to reopen this issue if you run into any issues.

**Comment by creamiracle** [comment]
> Can you check the ray dashboard to see if actors are started on both?
> 
> The IP address provided in the table is only for one of the actors that Tune/XGBoost starts. I suspect you'll see multiple processes started on the dashboard.
> 
> Moving forward, also recommend you check out the new XGBoostTrainer APIs for Ray: https://docs.ray.io/en/master/ray-air/key-concepts.html#trainers.
> 
> Hope that helps! Feel free to reopen this issue if you run into any issues.

Thanks for reply, I think I have found the reason.
I have also checked the link you offered before, but I got an error when import the `ray.air.config`, it seems that I can't find the "air" in ray. Is there any solution for that? The version is on the top of the before post.
Thanks.
