### ISSUE TITLE
[serve] Async Handle Memory Leak

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#27692]
### What happened + What you expected to happen

When testing serve HA, I test with the [PR](https://github.com/ray-project/ray/pull/27411) before it's merged and it's working good.

Today I merged the master (after the PR merged) and the testing shows the latency increased and throughput drops. 

I believe some change in the PR has regressions. I copied the serve directory in the good image to the master and it's working again.

### Versions / Dependencies

master

### Reproduction script

With https://github.com/ray-project/ray/pull/27691 it's working.

### Issue Severity

High: It blocks me from completing my task.

**Comment by iycheng** [comment]
cc @scv119  the release blocker

**Comment by iycheng** [comment]
@simon-mo @edoakes  could you take a look at this ASAP? Please check the PR to get some ideas of what might be wrong. Please let me know if there is anything I can help.

**Comment by sihanwang41** [comment]
> @simon-mo @edoakes could you take a look at this ASAP? Please check the PR to get some ideas of what might be wrong. Please let me know if there is anything I can help.

Hi @iycheng , do you mind sharing how you observe the latency? (any test script that we can reproduce?)

**Comment by iycheng** [comment]
@sihanwang41  Unfortunately, the nightly tests script still hasn't been merged yet https://github.com/ray-project/ray/pull/27413/files

But you can give it a try by running run_gcs_ft_on_k8s.py in /mnt/yic/ray/release/k8s_tests 
You need a k8s cluster to run this.


`RAY_IMAGE=DOCKER_IMAGE python ./run_gcs_ft_on_k8s.py`

**Comment by iycheng** [comment]
I run it by killing nodes (run_gcs_ft_on_k8s.py) and 

With the PR:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/74173148/183562315-950b0405-3bb2-4651-9fc6-8af9ee4988b7.png">

Without the PR:

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/74173148/183565258-5c0e2c6d-979c-4b55-bb12-bbf571f90d16.png">

**Comment by simon-mo** [comment]
This is weird... the commit you are using is inconsistent and definitely has bugs... 
- PyObjScanner's self._objects is set to a dict but we ended up appending
- We were defaulting to sync handle in that particular commit actually (for debugging purpose)
<img width="586" alt="image" src="https://user-images.githubusercontent.com/21118851/183568886-98fc76d0-91ac-4d62-8e31-b51311170238.png">

**Comment by simon-mo** [comment]
Can you try run it with `SERVE_DEPLOYMENT_HANDLE_IS_SYNC=1` (turn off async) and `SERVE_DEPLOYMENT_HANDLE_IS_SYNC=0` (new default behavior)?

**Comment by iycheng** [comment]
Sure, let me give it a try!

**Comment by iycheng** [comment]
@simon-mo Here is the result


- SERVE_DEPLOYMENT_HANDLE_IS_SYNC=1
  -  the failure is around 5%-10%
- SERVE_DEPLOYMENT_HANDLE_IS_SYNC=0
  -  the failure is very high (25%) and the QPS drops
- With that PR (that PR is just for reference of the diff between master and the good image)
  - the failure is around 1% (with retry, it should be 99.99%)

**Comment by simon-mo** [comment]
Hmm. The PR should be equivalent to the first one because of the sync handle block.

**Comment by iycheng** [comment]
Hmmm, my bad, I run 1) for a longer time and it looks very similar as 3). Maybe we can just disable it temporarily for now? 

But how is the sync one working now?

**Comment by iycheng** [comment]
Let me run it for a more longer time

**Comment by iycheng** [comment]
```
  123 ray       35  15   17.1g   3.3g  66448 S  84.7  10.7  13:26.72 ray::ServeRepli
 8479 ray       35  15   16.6g   2.8g  65748 S  85.3   9.1  11:10.96 ray::ServeRepli
   82 ray       35  15   11.3g 452964  66016 S  17.7   1.4   2:35.67 ray::HTTPProxyA
   59 ray       20   0   14.2g 183700  70312 S   7.0   0.6   0:39.92 python
    9 ray       20   0 1028732 160068  65088 S   0.0   0.5   0:01.56 ray
  119 ray       35  15   12.7g 157644  65748 S  22.7   0.5   3:05.19 ray::ServeRepli
  120 ray       35  15   12.7g 156904  65516 S  21.7   0.5   3:07.32 ray::ServeRepli
   38 ray       20   0  605476  96948  43508 S   3.3   0.3   0:28.19 python
```
A separate issue is that serve has mem leaking after running it for a while.

**Comment by simon-mo** [comment]
I can reproduce the separate issue locally. looking into it now

**Comment by iycheng** [comment]
Remove it as a release blocker given the sync version somehow working now.

**Comment by simon-mo** [comment]
@iycheng can update from using #27718 here?
