### ISSUE TITLE
[rlllib] Worker in cluster dies during training 

### ISSUE THREAD

**Issue by whikwon** [ray-project/ray#2770]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source 
- **Ray version**: 0.5.0
- **Python version**: 3.6.1
- **Exact command to reproduce**:

### Describe the problem

I'm running ray using cluster made up of five virtual machines. and I've noticed that one of the worker in cluster dies every 9 hours(not exactly) of training. Then, I have to stop ray and restore the checkpoint and rerun. 

![image](https://user-images.githubusercontent.com/30768596/44823526-e764f000-ac3b-11e8-827e-99eba2c52ae7.png)

**Comment by ericl** [comment]
Interesting, do you see any errors in /tmp/raylogs in the worker or dmesg output? It could be some memory / resource exhaustion error. It's also possible this is bug in the legacy ray backend. You can try the new backend in master with RAY_USE_XRAY=1 but it is not quite ready for production use.

**Comment by whikwon** [comment]
I can find two errors as below, could you check?

![image](https://user-images.githubusercontent.com/30768596/44830726-2dcb4680-ac5e-11e8-91d0-e2968d4c2f6d.png)

![image](https://user-images.githubusercontent.com/30768596/44830735-3885db80-ac5e-11e8-8585-c44424261a1f.png)

**Comment by whikwon** [comment]
When using ray cluster, which memory spaces should I have to manage? 

I recognized data generates in `/tmp/shm`, `/tmp/raylogs/`

**Comment by whikwon** [comment]
Use `RAY_USE_XRAY = 1` in where?

**Comment by ericl** [comment]
Just overall memory usage (see `top`). RAY_USE_XRAY is an environment variable.

Those log messages look normal, so it must be something else crashing.

**Comment by whikwon** [comment]
Hmm... OK. 

I think after updating ray It seems like `/dev/shm` fills faster than before. Is there any change around this?

**Comment by whikwon** [comment]
another error and it wasn't in the log file. 
![image](https://user-images.githubusercontent.com/30768596/44852799-25dfc680-ac9f-11e8-9ffa-fd1a2e0436b6.png)

**Comment by ericl** [comment]
That sounds like a memory leak in your app:
https://stackoverflow.com/questions/8378797/stdbad-alloc-am-i-using-too-much-memory

It's also possible the Ray object store, or some replay buffer is using too
much memory.

You can check system memory usage with monitoring tools or 'top' (RSS would
be the relevant measure). You can press 'M' to sort by that. That will tell
you which process is the cause to help narrow down the offending process.

**Comment by ericl** [comment]
Auto-closing stale issue.
