### ISSUE TITLE
[core] Prometheus service discovery file not found

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#27725]
### What happened + What you expected to happen

Followed the instructions [here](https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#prometheus-service-discovery-support) and I expected to find the service discovery file /tmp/ray/prom_metrics_service_discovery.json, but I did not find any.

### Versions / Dependencies

2.0

### Reproduction script

`ray start --head`

**Comment by scottsun94** [comment]
Is this fixed? @rkooo567

**Comment by rkooo567** [comment]
I can't reproduce this. Close for now
