### ISSUE TITLE
[Tune] Hanging when trying to retrieve data from node

### ISSUE THREAD

**Issue by sridharbalachandriah** [ray-project/ray#27729]
### What happened + What you expected to happen

1. Ray unable to retrieve objects from local plasma store on each of the cluster nodes.
2. A method is called to insert data into node local plasma store, for all nodes in a ray cluster. There after, a set of ray tasks are scheduled to retrieve this node local data from the plasma store through zero copy (using object-ids) and process the data.
3. On a 2 node cluster, this data retrieval on one of the node always hangs.

NOTE: The same code works fine with the same ray tune code and Apache plasma

### Versions / Dependencies

# conda list  ray
ray                       1.12.0                   pypi_0    pypi
ray-tune                  1.6.0            py39h06a4308_0

### Reproduction script
```
if __name__ == "__main__":
    bundles = [{"CPU": 1} for _ in range(len(ray.nodes()))]
    print("bundles : ",bundles)
    pg = placement_group(bundles=bundles, strategy="STRICT_SPREAD")
    ray.get(pg.ready())
    #node_train_data_to_plasma.remote()
    tasks = [
        node_train_data_to_plasma.options(placement_group=pg, placement_group_bundle_index=i).remote()
        for i in range(len(ray.nodes()))
    ]
    ips = ray.get(tasks)

    tune_pray(num_training_iterations=6)



@ray.remote(num_cpus=1)
def node_train_data_to_plasma():
    # Code to fetch data from store and push into plasma
    # This is executed per node.




def tune_pray(num_training_iterations):
    import tensorflow as tf

    sched = AsyncHyperBandScheduler(
        time_attr="training_iteration", max_t=400, grace_period=20)

    analysis = tune.run(
        train_pray,
        name='exp',
        scheduler=sched,
        metric="mean_accuracy",
        mode="min",
        verbose=3,
        stop={
            "mean_accuracy": 0.8,
            "training_iteration": num_training_iterations
        },
        num_samples=6,#10
        #resources_per_trial=tune.PlacementGroupFactory([{"CPU": 4}]),
        resources_per_trial={
            "cpu": 2,
            "gpu": 0
        },

        config={
            "threads": 5,
            "lr": tune.uniform(0.001, 0.1),
            "momentum": tune.uniform(0.1, 0.9)
        })




def train_pray(config):
'''
1. Fetch the data from plasma using the object-ids
2. Even though the object-ids are present, the objects are not pinned.
3. Processess on one of the node hangs.
'''
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
@sridharbalachandriah can you provide a simple reproducible script and more description about your cluster environment?

Where are you calling `node_train_data_to_plasma`? Can you try `@ray.remote(num_cpus=0)`?

**Comment by sridharbalachandriah** [comment]
@richardliaw here are the details:

1. In the code snippet provided above "node_train_data_to_plasma" is called before tune_pray(num_training_iterations=6) in the main.

2. The ray cluster is enabled with 2 nodes:
Ray start from the head node
============================
# ray start --head --port=6379  --object-store-memory=7864320000 --system-config='{"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/tmp/spill\"}}"}'

Ray start from the worker node
==============================
# ray start  --object-store-memory=7864320000 --address='12.2.0.2:6379'

3.   Can you try @ray.remote(num_cpus=0)? for node_train_data_to_plasma
When this is tried, the method is called on only one of the nodes. I want this to be called on all the nodes.

**Comment by sridharbalachandriah** [comment]
ray memory
======== Object references status: 2022-08-11 00:06:49.653850 ========
Grouping by node address...        Sorting by object size...        Display allentries per group...


--- Summary for node address: 172.23.0.23 ---
Mem Used by Objects  Local References  Pinned        Used by task   Captured in Objects  Actor Handles
786628152.0 B        16, (786628152.0 B)  0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           0, (0.0 B)

--- Object references for node address: 172.23.0.23 ---
IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref
172.23.0.23      1493575  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000003000000

172.23.0.23      1493575  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000007000000

172.23.0.23      1493575  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000009000000

172.23.0.23      1493575  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000005000000

172.23.0.23      1493141  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000007000000

172.23.0.23      1493141  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000005000000

172.23.0.23      1493141  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000009000000

172.23.0.23      1493141  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000003000000

172.23.0.23      1493575  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000002000000

172.23.0.23      1493575  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000008000000

172.23.0.23      1493575  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000006000000

172.23.0.23      1493575  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00181ec2e662d748ffffffffffffffffffffffff0300000004000000

172.23.0.23      1493141  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000004000000

172.23.0.23      1493141  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000002000000

172.23.0.23      1493141  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000006000000

172.23.0.23      1493141  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     00868e48e2fa9a94ffffffffffffffffffffffff0200000008000000

--- Summary for node address: 172.23.0.22 ---
Mem Used by Objects  Local References  Pinned        Used by task   Captured in Objects  Actor Handles
393314076.0 B        8, (393314076.0 B)  0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           0, (0.0 B)

--- Object references for node address: 172.23.0.22 ---
IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref
172.23.0.22      873906  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000007000000

172.23.0.22      873906  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000005000000

172.23.0.22      873906  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000003000000

172.23.0.22      873906  Worker  disabled                FINISHED        24251.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000009000000

172.23.0.22      873906  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000006000000

172.23.0.22      873906  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000004000000

172.23.0.22      873906  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000002000000

172.23.0.22      873906  Worker  disabled                FINISHED        98304268.0 B  LOCAL_REFERENCE     002ffa20ac4b2e6effffffffffffffffffffffff0300000008000000

To record callsite information for each ObjectRef created, set env variable RAY_record_ref_creation_sites=1

--- Aggregate object store stats across all nodes ---
Plasma memory usage 1125 MiB, 24 objects, 7.5% full, 7.5% needed
Objects consumed by Ray tasks: 1406 MiB.

**Comment by sridharbalachandriah** [comment]
@xwjiang2010, 
The dataset resides on a remote distributed store, accessible across nodes. I was not aware of tune.with_parameters(), Does tune-with-parameters push the data into one of the node store(example: head) and then the worker node will have to retrieve the data through head node object store. (using the fast ethernet)?

**Comment by xwjiang2010** [comment]
@sridharbalachandriah Thanks for the response.
`tune.with_parameters()` is useful when you have data on head node and would want other nodes to have access to it through object store.

For your case, I think the correct way of doing it is to implement a custom `ray.data.dataset` DataSource. https://docs.ray.io/en/latest/_modules/ray/data/datasource/datasource.html

You can then first load your customized data into Ray cluster and every node should have access to it.

**Comment by xwjiang2010** [comment]
@jianoaix @clarkzinzow

**Comment by jianoaix** [comment]
@sridharbalachandriah can you make you repro script runnable? Or even better, make it minimum. It's not clear to me how the current repro script map to what you described in What Happened. Thanks.

**Comment by sridharbalachandriah** [comment]
@xwjiang2010 , 
I have an experimental distributed store accessible to all the ray cluster nodes. I dont want the worker nodes in the cluster to go to the head node to fetch the data. The object access through the fast Ethernet does not suffice the needs. Is it possible to switch the network configuration for this object access across nodes in Ray for Plasma?.

@jianoaix ,
 At the moment I cannot have the complete repo script posted due to a dependency.
