### ISSUE TITLE
[Ray Plasma, remote storage support] 

### ISSUE THREAD

**Issue by sridharbalachandriah** [ray-project/ray#27730]
### What happened + What you expected to happen

1. Ray spillover / retrieval for  remote storage is **not performance optimized**. (https://docs.ray.io/en/latest/ray-core/objects/object-spilling.html) 
2. An experimental smart_open plugin for DAOS (https://docs.daos.io/v2.0/) was implemented and tested with Ray for remote storage spillover and retrieval of data from the ray cluster nodes. 
3. The performance of Ray based spillover and retrieval of data from DAOS is 2x slower when compared to a standalone application using the same DAOS smart_open interface. 

Queries / problems:
1. As per ray the architecture document https://docs.google.com/document/d/1lAy0Owi-vPz2jEqBSaHNQcy2IBSDEHyXNOQZlGuj93c/preview# there is a clear mention of "Distributed storage (S3). Speed of access may be slower" **are there any plans to make it performance optimized**?
2. Running the application for 3 iterations yields in a **hang**. 
3. Debugging through smart_open interfaces, we could see the distributed remote storage access is done from the requesting node( which is not clearly documented). 
```
### Versions / Dependencies

# conda list ray
# packages in environment at /root/anaconda3:
#
# Name                    Version                   Build  Channel
ray                       1.12.0                   pypi_0    pypi
ray-tune                  1.6.0            py39h06a4308_0

```

### Reproduction script

None. 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
@sridharbalachandriah 

Could you provide a repro for the hanging issue?
