### ISSUE TITLE
[Core] Add config option for Ray Node Runtime to specify visible cuda devices on a node

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#27739]
### Description

Add config option for Ray Node Runtime to specify visible cuda devices on a node:

Suppose on a machine, there are 4 GPUs, and GPU-0/ GPU-1 are used by other applications, and launching the Ray Node Runtime on this machine, using this config to limit the Ray Node Runtime only using GPU-2/GPU-3 on this machine.

Q: Does setting `VISIBLE_CUDA_DEVICES` environment variable addresses this issue ? I don't find related document. I only find a `--num-gpus` option for `ray start ...` CLI.

### Use case

We are working on code to run Ray over spark, this config is important to make Ray Node Runtime respect spark task resource allocation.

**Comment by jjyao** [comment]
You can start Ray with the number of logical gpus (--num-gpus) you specify (it doesn't have to be equal to the number of physical gpus on the host). You are also free to use any physical gpu when the task is executing (e.g. by manually setting `VISIBLE_CUDA_DEVICES`), RAY doesn't prevent you from doing that.

**Comment by WeichenXu123** [comment]
Thank you @jjyao 

But what I want to ask is how to control the GPU allocation for "Ray Node Runtime", not "Ray task",

suppose my machine has 4 physical GPUs,
and I run:

```
export VISIBLE_CUDA_DEVICES=2,3
ray start --num-gpus=2 ...
```

then Does the **Ray Node Runtime** will be limited to use the physical GPU-2, GPU-3  (i.e., when Ray tasks scheduled to this Ray Node, then only physical GPU-2/GPU-3 will be assigned to the task) ? (Suppose we forbid user to set their own `VISIBLE_CUDA_DEVICES ` or implement their own `use_gpu()`)

**Comment by jjyao** [comment]
If you forbid users to set their own `VISIBLE_CUDA_DEVICES` then I think it's not possible with current Ray. The reason is that Ray works with logical resources not physical resources and it's user's responsibility to map the logical one to the physical one (it's just by default, it happens to be a 1:1 mapping which is not the case in your scenarior).

**Comment by WeichenXu123** [comment]
@jjyao 
Thank you. Any plan to support this in Ray Node runtime ? We just need to add physical devices mapping config for "Ray Node Runtime". We can reuse the `VISIBLE_CUDA_DEVICES` env to setting it, like:

```
export VISIBLE_CUDA_DEVICES=2,3
ray start --num-gpus=2 ... # Ray Node Runtime reads the `VISIBLE_CUDA_DEVICES` env var, and restrict the Ray Node can only use  physical devices 2 and 3.
```

CC @mengxr

**Comment by jjyao** [comment]
There is no settled plan yet. I added to the backlog and will discuss with the team to see whether and when to support it.

**Comment by WeichenXu123** [comment]
> @jjyao Thank you. Any plan to support this in Ray Node runtime ? We just need to add physical devices mapping config for "Ray Node Runtime". We can reuse the `VISIBLE_CUDA_DEVICES` env to setting it, like:
> 
> ```
> export VISIBLE_CUDA_DEVICES=2,3
> ray start --num-gpus=2 ... # Ray Node Runtime reads the `VISIBLE_CUDA_DEVICES` env var, and restrict the Ray Node can only use  physical devices 2 and 3.
> ```
> 

@jjyao In my test I found Ray already support the feature I described, i.e. setting `VISIBLE_CUDA_DEVICES` environment variables for Ray Node Runtime to control which physical GPUs Ray Node can use.

**Comment by jjyao** [comment]
@WeichenXu123 

You are right. Sorry for the confusion. I'll update our documentation to mention this behavior.
