### ISSUE TITLE
Improve commit message quality

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#2773]
Currently, when we merge a PR, the commit message is sometimes the PR description, and sometimes a list of local commits.

I think neither of them is good. Because PR description may be too lengthy and contain unnecessary information, while the list of commits also contains useless details like 'address comments' or 'fix lint'.

I think a good commit message should be a summary of this PR that contains the following part:
1) the purpose of this commit.
2) how a new functionality is implemented (if applicable).
3) any implications, compromises, or tradeoffs introduced by this commit.
4) related issue numbers.
5) anything else?

The reason why the commit message is important is because it allows us to understand a commit quickly by just looking at `git log`, instead of going to github and read the whole conversation. And it's also locally searchable.

To resolve this problem, we can add a `commit message` section in the PR template to remind people to provide such a summary.

IMHO, in the long term, this would be beneficial for the codebase quality. 

Please let me know what you think about this.
@robertnishihara @atumanov @pcmoritz @stephanie-wang @richardliaw

**Comment by robertnishihara** [comment]
In this situation, I typically just modify the commit message by hand so that it looks reasonable. In particular, it's usually fine to just leave make it empty.

**Comment by raulchen** [comment]
@robertnishihara 
For simple PRs, it's fine to leave commit message empty or we manually modify it. 
But for the complex ones, I think the author knows the best how to summarize the changes.

The reason why I brought this up is because I've seen a lot of commits whose messages are very lengthy lists of local commit titles. These commit messages provide little information.

Thus, I'd like to figure out a guideline that we all can follow.

**Comment by robertnishihara** [comment]
@raulchen I agree that's a good idea. Do you know how other projects do this? E.g., Arrow has a script which autogenerates a commit message from the PR description.

**Comment by raulchen** [comment]
@robertnishihara I'm not familiar with how open source projects do this. I know about Facebook's way. At Facebook, the message of each diff (equivalent to a PR) must contain the following parts:
1) Title: one sentence that describe what this diff does.
2) Summary: more detailed description of what, why and how.
3) Test: how this diff has been tested, and how to reproduce the test.
4) Related tasks.

I also did some search about good PR templates, [this article](https://embeddedartistry.com/blog/2017/8/4/a-github-pull-request-template-for-your-projects) looks good.

I don't know how Arrow's script works. But generally, I think it makes sense to provide a good template with a few sections and explain what each section is about. And we can just keep certain sections in commit message.
