### ISSUE TITLE
Issue on page /data/examples/nyc_taxi_basic_processing.html

### ISSUE THREAD

**Issue by davidxiaozhi** [ray-project/ray#27738]
I want to use this framework, but I found that there are too few demos and the cost of getting started is very high. For example, I want to read tsv files
````python
from pyarrow import csv
parse_options = csv.ParseOptions(delimiter="\t")
meta_provider=DefaultFileMetadataProvider()
file = ray.data.read_csv("/home/maer/zhipeng.li/data2/day_1.tsv",parallelism=200, ray_remote_args={"num_cpus": 0.25},
                         meta_provider=meta_provider,
                         parse_options=parse_options)
````
He directly reported the following error:
File "/root/conda/lib/python3.9/site-packages/ray/data/read_api.py", line 529, in read_csv
    return read_datasource(
  File "/root/conda/lib/python3.9/site-packages/ray/data/read_api.py", line 269, in read_datasource
    block_list.ensure_metadata_for_first_block()
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/lazy_block_list.py", line 305, in ensure_metadata_for_first_block
    metadata = ray.get(metadata_ref)
  File "/root/conda/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/conda/lib/python3.9/site-packages/ray/worker.py", line 1831, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ArrowInvalid): ray::_execute_read_task() (pid=22123, ip=172.16.15.11)
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/lazy_block_list.py", line 451, in _execute_read_task
    block = task()
  File "/root/conda/lib/python3.9/site-packages/ray/data/datasource/datasource.py", line 146, in __call__
    for block in result:
  File "/root/conda/lib/python3.9/site-packages/ray/data/datasource/file_based_datasource.py", line 212, in read_files
    yield output_buffer.next()
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/output_buffer.py", line 74, in next
    block = self._buffer.build()
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/delegating_block_builder.py", line 64, in build
    return self._builder.build()
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/table_block.py", line 85, in build
    return self._concat_tables(tables)
  File "/root/conda/lib/python3.9/site-packages/ray/data/impl/arrow_block.py", line 91, in _concat_tables
    return pyarrow.concat_tables(tables, promote=True)
  File "pyarrow/table.pxi", line 2338, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Can't unify schema with duplicate field names.

By reading the source code and querying the official demo, I initially found that I might need to implement DefaultFileMetadataProvider myself
````python
meta_provider=DefaultFileMetadataProvider()
````
But I can't find any relevant information at all, and I expect the official to provide a lot of demos, which can reduce our learning cost

**Comment by c21** [comment]
file metadata provider is actually not related here. By default `read_csv` would only read the files with `.csv` extension and ignores all other files (so the `.tsv` file in your example). You can set `partition_filter` to `None` to disable this feature (i.e. not filter out files without `.csv` extension). We also fixed the error message to make it more understandable in https://github.com/ray-project/ray/pull/27353 in master.

Here is one example working on my side (please let me know if it does not work for you):

I created a TSV file from wikipedia - https://en.wikipedia.org/wiki/Tab-separated_values .
```
(chengsu-dev) chengsu@chengs-mbp tsv % cat chengsu.tsv 
Sepal length	Sepal width	Petal length	Petal width	Species
5.1	3.5	1.4	0.2	I. setosa
4.9	3.0	1.4	0.2	I. setosa
4.7	3.2	1.3	0.2	I. setosa
4.6	3.1	1.5	0.2	I. setosa
5.0	3.6	1.4	0.2	I. setosa
```

Then I can read it from Ray:

```
>>> import ray
>>> from pyarrow import csv
>>> parse_options = csv.ParseOptions(delimiter="\t")
>>> ds = ray.data.read_csv("/Users/chengsu/try/tsv/chengsu.tsv", partition_filter=None, parse_options=parse_options)
>>> ds
Dataset(num_blocks=1, num_rows=5, schema={Sepal length: double, Sepal width: double, Petal length: double, Petal width: double, Species: string})
>>> ds.take(1)
[{'Sepal length': 5.1, 'Sepal width': 3.5, 'Petal length': 1.4, 'Petal width': 0.2, 'Species': 'I. setosa'}]
```

**Comment by c21** [comment]
@davidxiaozhi - btw if above example is not working for you, it could be related to the schema of your TSV file. Please share your TSV file here, so we can debug further if needed.

**Comment by davidxiaozhi** [comment]
curl -O https://storage.googleapis.com/criteo-cail-datasets/day_1.gz
file=day_1.gz
dist=/path/
dist_file=day_1.tsv
 gzip -d -v -c ${file} >> "${dist}/${dist_file}"

**Comment by davidxiaozhi** [comment]
@c21  主要原因为数据当中存在异常数据,但是

**Comment by davidxiaozhi** [comment]
the dataset for error

**Comment by clarkzinzow** [comment]
@c21 @pcmoritz can this be closed now that https://github.com/ray-project/ray/pull/27850 has been merged?

**Comment by matthewdeng** [comment]
The `invalid_row_handler` issue should now also be resolved in master with https://github.com/ray-project/ray/issues/28326, although PyArrow 7.0 (which is when `invalid_row_handler` was introduced)  is not compatible with Datasets.

**Comment by pcmoritz** [comment]
@matthewdeng Do you know what prevents us from being compatible with a more recent PyArrow release?

**Comment by matthewdeng** [comment]
@pcmoritz the issue is being tracked in https://github.com/ray-project/ray/issues/22310, @clarkzinzow can shed more light on the forward fix for PyArrow 10.

**Comment by pcmoritz** [comment]
Ah this is https://issues.apache.org/jira/browse/ARROW-10739

Well, I don't think we can close this bug until that's resolved then :)

However if we install pyarrow >= 7.0, manually, I have now verified it works (on the latest master with Kai's fix):

test.tsv

```
Sepal length	Sepal width	Petal length	Petal width	Species
5.1	3.5	1.4	0.2	I. setosa
4.9	3.0	1.4	0.2	I. setosa
invalid
4.7	3.2	1.3	0.2	I. setosa
4.6	3.1	1.5	0.2	I. setosa
5.0	3.6	1.4	0.2	I. setosa
```

```python
import ray
from pyarrow import csv

def skip_comment(row):
    print("===skip:",row)
    return 'skip'

parse_options = csv.ParseOptions(delimiter="\t",invalid_row_handler=skip_comment)
ds = ray.data.read_csv("test.tsv", parse_options=parse_options, partition_filter=None)
ds.show()
```

Results in the correct
```
2022-09-07 20:04:51,361	INFO worker.py:1508 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266 
2022-09-07 20:04:53,039	WARNING read_api.py:291 -- ⚠️  The number of blocks in this dataset (1) limits its parallelism to 1 concurrent tasks. This is much less than the number of available CPU slots in the cluster. Use `.repartition(n)` to increase the number of dataset blocks.
(_execute_read_task pid=67767) ===skip: InvalidRow(expected_columns=5, actual_columns=1, number=4, text='invalid')
{'Sepal length': 5.1, 'Sepal width': 3.5, 'Petal length': 1.4, 'Petal width': 0.2, 'Species': 'I. setosa'}
{'Sepal length': 4.9, 'Sepal width': 3.0, 'Petal length': 1.4, 'Petal width': 0.2, 'Species': 'I. setosa'}
{'Sepal length': 4.7, 'Sepal width': 3.2, 'Petal length': 1.3, 'Petal width': 0.2, 'Species': 'I. setosa'}
{'Sepal length': 4.6, 'Sepal width': 3.1, 'Petal length': 1.5, 'Petal width': 0.2, 'Species': 'I. setosa'}
{'Sepal length': 5.0, 'Sepal width': 3.6, 'Petal length': 1.4, 'Petal width': 0.2, 'Species': 'I. setosa'}
```

@davidxiaozhi This should unblock you, but let us know if there is more trouble :)

**Comment by krfricke** [comment]
To use the patch from #28326 / #28327 without upgrading Ray, here is a workaround: https://github.com/ray-project/ray/issues/28326#issuecomment-1240448217
