### ISSUE TITLE
Where is the core_worker attribute defined, it is not defined in worker.py

### ISSUE THREAD

**Issue by young-chao** [ray-project/ray#27745]
### What happened + What you expected to happen

When I was looking into the actual object fetching flow of ray.get, I got stuck at worker.global_worker.core_worker because I found that I couldn't find where the core_worker property was defined at all.

### Versions / Dependencies

both 
ray==1.13.0
 and 
ray==3.0.0.dev

### Reproduction script

global_worker = Worker()

worker = global_worker
worker.check_connected()

data_metadata_pairs = self.core_worker.get_objects(
       object_refs, self.current_task_id, timeout_ms
)

**Comment by richardliaw** [comment]
Hope this helps!

https://github.com/ray-project/ray/blob/2246ea7fe4da3e1a447eb85401e38c7e805b8222/python/ray/_private/worker.py#L1971-L1989

**Comment by young-chao** [comment]
> Hope this helps!
> 
> https://github.com/ray-project/ray/blob/2246ea7fe4da3e1a447eb85401e38c7e805b8222/python/ray/_private/worker.py#L1971-L1989

Thank you!You solved my confusion。
