### ISSUE TITLE
Debug log level can not be configured for python processes

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#27740]
### Description

When troubleshooting some issues about runtime-env, debug log needed. But it seems that the debug level can not be set.

I've tried the following two ways：
1. set RAY_BACKEND_LOG_LEVEL=debug env
2. using `ray --logging-level=debug start --head` command to start ray cluster

What is the correct way to enable debug logging in python code ?

**Comment by MissiontoMars** [comment]
@SongGuyang

**Comment by WangTaoTheTonic** [comment]
This is nothing related with runtime env. The python worker sets the log level to INFO by default, which cannot be confiugred, IIRC.

**Comment by SongGuyang** [comment]
Yep, It's a common issue which is related to all the python processes(workers、agent、scripts、client server and so on.)

**Comment by WangTaoTheTonic** [comment]
I'll try to fix it.

**Comment by scottsun94** [comment]
cc: @rkooo567

**Comment by rkooo567** [comment]
@WangTaoTheTonic do you have a plan to make a PR? Otherwise I can fix it

**Comment by jovany-wang** [comment]
@rkooo567 It will be good if you take this.

**Comment by rkooo567** [comment]
Duplicated as https://github.com/ray-project/ray/issues/29758
