### ISSUE TITLE
No module named 'ray.tune.search'

### ISSUE THREAD

**Issue by azamatolegen** [ray-project/ray#27767]
### What happened + What you expected to happen

---------------------------------------------------------------------------
```
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_367/483132525.py in <module>
----> 1 from ray.tune.search.bayesopt import BayesOptSearch
      2 from ray import air
      3 
      4 # Define the search space
      5 search_space = {"lr": hp.loguniform("lr", 1e-10, 0.1)}

ModuleNotFoundError: No module named 'ray.tune.search'
```
### Versions / Dependencies
```
Kaggle Notebook:
Ray
1.13.0
Python version
3.7.12
Linux
5.10.133+
```
### Reproduction script
```
from ray.tune.search.bayesopt import BayesOptSearch
from ray import air

#### Define the search space
search_space = {"lr": hp.loguniform("lr", 1e-10, 0.1)}

algo = BayesOptSearch(random_search_steps=4)

tuner = tune.Tuner(
    train_loop,
    tune_config=tune.TuneConfig(
        metric="score",
        mode="min",
        search_alg=algo,
    ),
    run_config=air.RunConfig(stop={"training_iteration": 20}),
    param_space=search_space,
)
tuner.fit()
```

**Comment by xwjiang2010** [comment]
Hey @azamatolegen 
The code you are referring to is expecting newest Ray, which was not included in 1.13.0 release. Would you upgrade to the nightly wheel?

**Comment by azamatolegen** [comment]
@xwjiang2010 Thanks for your quick response. Sure, can you please show me how to install the right version?

**Comment by richardliaw** [comment]
Could you try installing via `pip install --pre -U ray`? This would install master: https://docs.ray.io/en/master/

Otherwise, you can also install `ray==1.13`. But make sure you're using `latest` docs: https://docs.ray.io/en/latest/

**Comment by azamatolegen** [comment]
@richardliaw  Thanks！After trying first approach I git this error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_17/483132525.py in <module>
----> 1 from ray.tune.search.bayesopt import BayesOptSearch
      2 from ray import air
      3 
      4 # Define the search space
      5 search_space = {"lr": hp.loguniform("lr", 1e-10, 0.1)}

/opt/conda/lib/python3.7/site-packages/ray/tune/search/__init__.py in <module>
      4 from ray.tune.search.repeater import Repeater
      5 
----> 6 from ray.tune.search.basic_variant import BasicVariantGenerator
      7 from ray.tune.search.variant_generator import grid_search
      8 from ray.tune.search.search_generator import SearchGenerator

/opt/conda/lib/python3.7/site-packages/ray/tune/search/basic_variant.py in <module>
      9 
     10 from ray.tune.error import TuneError
---> 11 from ray.tune.experiment.config_parser import _make_parser, _create_trial_from_spec
     12 from ray.tune.search.sample import np_random_generator, _BackwardsCompatibleNumpyRng
     13 from ray.tune.search.variant_generator import (

ModuleNotFoundError: No module named 'ray.tune.experiment.config_parser'; 'ray.tune.experiment' is not a package

**Comment by richardliaw** [comment]
Do you need to reset your Kaggle kernel? Wonder if things are left out of date from a previous version.

**Comment by richardliaw** [comment]
Can you try reproducing this on Colab? Unfortunately it's very hard for us to reproduce this..
