### ISSUE TITLE
[rllib] IMPALA throws ValueError for continuous action space

### ISSUE THREAD

**Issue by alexander-ossur** [ray-project/ray#2777]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.5.2
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Exact command to reproduce**: Please read below

### Describe the problem
Hello
Just playing a bit with IMPALA. 

#### Custom Environment
```
class CEnviroment (gym.Env):

	def __init__ (self, config):
		self.reward_range = (-1.0, 1.0)
		self.action_space = Box (-1.0, 1.0, shape = (1,), dtype = np.float32)
		self.observation_space = Box (...)
...
```
#### Main
```
agent_config__ = impala.DEFAULT_CONFIG.copy ()
agent_config__.update({
	"model": {
		"custom_model": ...,
		"custom_preprocessor": ...
	},
	"gamma": 0.99,
	"horizon": 2048,
	"num_workers": 12,
	"sample_batch_size": 2000,
	"num_envs_per_worker": 100,
	"vf_loss_coeff": 0.5,
	"entropy_coeff": 0.002
})

agent = impala.ImpalaAgent (env = ..., config = agent_config__)

result = agent.train ()
print (pretty_print (result))
```
#### Logs

> Using custom model my_model
> Traceback (most recent call last):  File "/home/aleksandr/Workspace/trad/tensorflow-test/ray_main_impala.py", line 244, in <module>
>     agent = impala.ImpalaAgent (env = env_name__, config = config__)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 186, in __init__
>     Trainable.__init__(self, config, logger_creator)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/tune/trainable.py", line 78, in __init__
>     self._setup()
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 221, in _setup
>     self._init()
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/impala/impala.py", line 85, in _init
>     self.env_creator, policy_cls)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 119, in make_local_evaluator
>     "inter_op_parallelism_threads": None,
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 159, in _make_evaluator
>     monitor_path=self.logdir if config["monitor"] else None)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 226, in __init__
>     policy_dict, policy_config)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 289, in _build_policy_map
>     policy_map[name] = cls(obs_space, act_space, merged_conf)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/impala/vtrace_policy_graph.py", line 157, in __init__
>     clip_pg_rho_threshold=self.config["vtrace_clip_pg_rho_threshold"])
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/impala/vtrace_policy_graph.py", line 69, in __init__
>     tf.float32))
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/ray/rllib/agents/impala/vtrace.py", line 141, in from_logits
>     actions.shape.assert_has_rank(2)
>   File "/home/aleksandr/anaconda3/envs/ml-agents/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 728, in assert_has_rank
>     raise ValueError("Shape %s must have rank %d" % (self, rank))
> ValueError: Shape (19, ?, 4) must have rank 2
> Terminated

#### Observation
My search leads to:
```
        def to_batches(tensor):
            if self.config["model"]["use_lstm"]:
                B = tf.shape(self.model.seq_lens)[0]
                T = tf.shape(tensor)[0] // B
            else:
                # Important: chop the tensor into batches at known episode cut
                # boundaries. TODO(ekl) this is kind of a hack
                T = (self.config["sample_batch_size"] //
                     self.config["num_envs_per_worker"])
                B = tf.shape(tensor)[0] // T
            rs = tf.reshape(tensor,
                            tf.concat([[B, T], tf.shape(tensor)[1:]], axis=0))
            # swap B and T axes
            return tf.transpose(
                rs,
                [1, 0] + list(range(2, 1 + int(tf.shape(tensor).shape[0]))))
```
... which creates a tensor rank 3.

**Comment by ericl** [comment]
Ah, the current implementation assumes discrete actions. It could be interesting to extend this to the continuous action case, though.

**Comment by alexander-ossur** [comment]
Thank you @ericl

**Comment by RylanSchaeffer** [comment]
Can a warning that IMPALA only currently supports discrete actions be added to the documentation? Not knowing this up front burnt a lot of my time.

**Comment by ericl** [comment]
Certainly.

The issue is that vtrace doesn't have a formulation for continuous action distributions here, so it's not that straightforward to enable.

**Comment by RylanSchaeffer** [comment]
Ok, thanks for clarifying :)

**Comment by RylanSchaeffer** [comment]
Wait. Don't several of the environments used by DeepMind in the Impala paper have continuous action spaces?

**Comment by RylanSchaeffer** [comment]
@ericl can you clarify why vtrace isn't applicable for continuous action distributions? I reread the paper, and it seems that as long as the agent is some flavor of an actor critic and importance sampling weights can be computed (which is doable under a continuous action distribution), vtrace's proposed formulation is applicable. What am I missing?

**Comment by ericl** [comment]
Oh, I'm just saying our impala implementation currently doesn't, and neither does the released reference code. It would be cool to try that out though, if you want to give it a shot.

**Comment by jayelm** [comment]
@RylanSchaeffer  did you try it out?

**Comment by RylanSchaeffer** [comment]
Hey Jesse 😄

I can't remember. If I did, that code is owned by the company I was working for at the time and I no longer have access.
