### ISSUE TITLE
PPO 0.5.0 -> 0.5.2 may have performance issue with the same config

### ISSUE THREAD

**Issue by alexander-ossur** [ray-project/ray#2778]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.5.0, 0.5.0 with #2535, 0.5.2
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Exact command to reproduce**: Please read below
- **Specs**: 12 vCPU, 1 GPU

### Describe the problem
Basically I am running same PPO config between the three cases and measure performance by "timesteps_this_iter / time_this_iter"

1. Ray 0.5.0: gives 30600÷30 = 1020 timesteps per second
2. Ray 0.5.0 with backported #2535: gives 30600÷15 = 2040 timesteps per second. Yes two times faster with GPU enabled
3. Ray 0.5.2: gives 6120÷15 = 408

Number 2 and 3 are showing same CPU and GPU loading pattern and the same amount of time per iteration.
Although "timesteps_this_iter" is much smaller.

**My question is: **does 0.5.2 got some calculation fix, or a bug, which gives a different "timesteps_this_iter"?****

### Source code / logs
```
agent_config__ = ppo.DEFAULT_CONFIG.copy ()
agent_config__.update({
	"model": {
		"custom_model": ...,
		"custom_preprocessor": ...,
	},

	"lambda": 0.8,
	"gamma": 0.99,
	"horizon": 2048,
	"num_workers": 12,
	"num_gpus": 1,
	"sample_batch_size": 2000,
	"timesteps_per_batch": 5000,
	"num_sgd_iter": 20,
	"sgd_batchsize": 4096,
	"num_envs_per_worker": 100,
	"clip_param": 0.2,
	"kl_coeff": 0.65,
	"kl_target": 0.0165,
	"vf_loss_coeff": 0.5,
	"entropy_coeff": 0.002,
	"sgd_stepsize": 0.0015025,
})
```

**Comment by ericl** [comment]
What type of environment are you using here?

**Comment by alexander-ossur** [comment]
I tested with that environment
```
class CEnviroment (gym.Env):

	def __init__ (self, config):
		self.reward_range = (-1.0, 1.0)
		self.action_space = Box (-1.0, 1.0, shape = (1,), dtype = np.float32)
		self.observation_space = Box (...)
...
```
And Model
```
class CModel (Model):

	def _build_layers (self, inputs, num_outputs, options):
		shape__ = (...)

		convs__ = options.get ("conv_filters", [
			[16, 8, 4],
			[32, 5, 3],
			[32, 5, 2],
			[512, 10, 1],
		])

		layer__ = tf.reshape (self.inputs, shape = [-1] + list (shape__))

		for i, (out_size, kernel, stride) in enumerate (convs__ [:-1], 1):
			layer__ = tf.layers.conv1d (activation = tf.nn.elu, inputs = layer__, filters = out_size, kernel_size = kernel, strides = stride, padding = "same")

		out_size, kernel, stride = convs__ [-1]
		layer__ = tf.layers.conv1d (activation = tf.nn.elu, inputs = layer__, filters = out_size, kernel_size = kernel, strides = stride, padding = "valid" )

		#
		layer1__ = slim.flatten (layer__)

		#
		layer2__ = slim.fully_connected (layer1__, 64, weights_initializer = xavier_initializer (), activation_fn = tf.nn.elu)
		layer3__ = slim.fully_connected (layer2__, 64, weights_initializer = xavier_initializer (), activation_fn = tf.nn.elu)

		output = slim.fully_connected (layer3__, num_outputs, weights_initializer = normc_initializer (0.01), activation_fn = None, scope = "fc_out")

		return output, layer3__
```

**Comment by ericl** [comment]
I think I know what's going on, it's an artifact of the particular configuration that's being used.

```
	"num_workers": 12,
	"sample_batch_size": 2000,
	"timesteps_per_batch": 5000,
```

So here, each worker will return a sample batch of 2000 steps. The driver will only wait for 5000 steps before continuing with optimization. This means that only 6000 of the 24000 steps per iteration are actually used for optimization!

In 0.5.0, we counted all the steps. In 0.5.2, we only count the steps used by the optimizer.

**Comment by alexander-ossur** [comment]
Thank you @ericl !

I made a changes following your post and can see times better performance and all 12 vCPU evenly loaded.

PS. Currently all these options are blackboxed for for me, hence the confusion.

PSS. Feel free to close the issue

**Comment by ericl** [comment]
Yeah, we should somehow expose documentation on the options better. They are only documented in python comments which isn't the most observable.
