### ISSUE TITLE
How to compile ray[default]

### ISSUE THREAD

**Issue by Jianzs** [ray-project/ray#27782]
I compiled Ray according to the [doc](https://docs.ray.io/en/latest/ray-contribute/development.html). The code can be run normally, but it will cause the Dashboard to not work properly, the same as just `pip install ray`. So, How to compile `ray[default]`？

**Comment by jjyao** [comment]
You just need to install extra dependencies specifiedy by `ray[default]`. Could you run `pip install ray[default]`?

**Comment by Jianzs** [comment]
I cannot run `pip install ray[default]` on Raspberry Pi. But I found the solution. 

First, build the wheel, `python3 setup.py bdist_wheel`. Then, enter the `dist` directory, and run `pip install xxxx.whl[default]`.
