### ISSUE TITLE
can not find previous version document

### ISSUE THREAD

**Issue by csaimd** [ray-project/ray#27786]
### Description

documents before version 1.11.0 cannot be viewed

**Comment by xwjiang2010** [comment]
cc @richardliaw 

Hi!
This is intended to encourage people to upgrade to newer versions.
We are deprecating old ray versions as we move towards ray 2.0.0. 
If you are interested in earlier versions, you can use the tagged ray version on the repo instead.
<img width="1722" alt="Screen Shot 2022-08-11 at 7 27 10 AM" src="https://user-images.githubusercontent.com/87673679/184156893-78f74a2d-212c-4811-887b-19ff18875de9.png">
