### ISSUE TITLE
[Tune] FileNotFoundError when resuming from Checkpoint

### ISSUE THREAD

**Issue by Stefan-1313** [ray-project/ray#27790]
### What happened + What you expected to happen

@xwjiang2010 
This issue is related to my post here: [discuss.ray.io](https://discuss.ray.io/t/filenotfounderror-when-resuming-from-checkpoint/7146?u=stefan-1313). You asked me to tag you here so here you go :).

**What goes wrong:**
When running a Ray Tune experiment in a Docker container, stopping the container, and restarting the constrainer, the checkpoint cannot be found and the run crashes. It also happens on Windows when I force stop the Python process (e.g. kill from a task manager).

The issue only occurs when I set the `tune.run()` argument `keep_checkpoints_num` to something other than `None`.

I can 100% reproduce this issue. From a docker container it is easier to reproduce because you can easily stop the container and everything inside it. I can also reproduce on Windows, **but I really have to kill the Python process**, meaning not letting it gracefully stop (so e.g. in PyCharm, hitting the red stop button multiple times quickly to really force stop Python (just pressing the red stop button once wil gracefully stop the Python Process and the issue will not reproduce)).

**Reproduction steps.**
Set `keep_checkpoints_num=2` .
I start the Docker container:

1. [This point is in practice not really a problem, but it may 'give a hint' / 'be related to' the other 2 points] If I kill the docker container before more than 2 iterations have been completed and then restart the container, resume always works, _although sometimes Tune start from te beginning!_ (It is easier to set `keep_checkpoints_num=5` and you will see the same when no more than 5 iterations may have been completed.)
Set `keep_checkpoints_num=2` again for the remainder...
2. Suppose I let a trail run for 4 iterations, if I kill the docker container, minimum 5 seconds after the 4th iteration finished (based on a print from callback log_trial_result) and then, restart the container, resume work as expected, and the first iteration printed is 5 (based on a print from callback log_trial_result) .
3. Suppose I let a trail run for 4 iterations, if I kill the docker container, maximum 1 seconds after the 4th iteration finished (based on a print from callback log_trial_result) and then, restart the container, resume fails with the above error. It tries to resume from the 2th iteration (sometimes the 3th), and it may be deleted already by `keep_checkpoints_num`. If I inspect the output folder I can see the checkpoint folder checkpoint_000004 exists, and the 2th (or sometimes the 3th) was already deleted because of `keep_checkpoints_num=2`.
Off course, you can encounter cases where the 2th checkpoint was not deleted (as it is just luck which checkpoints score such that `keep_checkpoints_num` keeps them). If you wait longer and run for more than 4 iterations, more checkpoints have been deleted and you increase the probability of Tune trying to resume from a deleted checkpoint.

**A detail.**
I can reproduce this 100% but the timing described above in point 2 and 3 is required. This suggest the probability of getting this error is small as termination then always has to happen max a few seconds after completing an iteration.
I use the Azure Machine Learning Service and when running there, my Docker containers get stopped once in a while because I run them on low-priority nodes.
Unfortunately, I almost always get this error `FileNotFoundError` when resume on Azure is attempted. I assume it is because of the same issue as described in this post. However, I cannot explain why the probability of this occurring on my Azure nodes seems to be much larger.

**My best guess regarding the cause.**
It think Tune does NOT look at which checkpoint folders are present when determining from which checkpoint to resume. I think this information is stored in another file.
But writing to this file might be buffered. When the Python process (or Docker container running Python) is abruptly stopped, the buffer is not flushed and Tune attempts to resume from a wrong checkpoint. Unfortunately, this wrong checkpoint has been deleted when the new checkpoint was created.
_So maybe force flushing this buffer before deleting the old checkpoint?_
This is just a guess, I don't have any references to the source code to back this up.

**Terminal output for point 2 and 3.**
After point 2, I get this kind of output (everything works as expected):
The container is restarted when you see the line `Start Ray Tune.` somewhere halfway. This `*** SIGTERM received at time=1660223520 on cpu 10 ***` and everything after until restart is because of stopping the Docker container.
```
Start Ray Tune.
2022-08-11 13:11:34,633 INFO trial_runner.py:510 -- No local checkpoint was found. Ray Tune will now start a new experiment.
2022-08-11 13:11:34,791 ERROR syncer.py:147 -- Log sync requires rsync to be installed.
(SimpleQTrainer pid=516) 2022-08-11 13:11:36,935        INFO simple_q.py:187 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
(SimpleQTrainer pid=516) 2022-08-11 13:11:36,935        INFO trainer.py:903 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 1 | Episode reward mean: -167.08
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 2 | Episode reward mean: -177.17
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 3 | Episode reward mean: -161.51
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 4 | Episode reward mean: -145.84
*** SIGTERM received at time=1660223520 on cpu 10 ***
PC: @     0x7fb7a8c9aad8  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7fb7a8c9f140  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2022-08-11 13:12:00,221 E 1 1] logging.cc:325: *** SIGTERM received at time=1660223520 on cpu 10 ***
[2022-08-11 13:12:00,221 E 1 1] logging.cc:325: PC: @     0x7fb7a8c9aad8  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-11 13:12:00,221 E 1 1] logging.cc:325:     @     0x7fb7a8c9f140  (unknown)  (unknown)
[2022-08-11 13:12:00,221 E 1 1] logging.cc:325:     @ ... and at least 1 more frames
Exception ignored in: <function RolloutWorker.__del__ at 0x7fb77e97d310>
Traceback (most recent call last):
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

Start Ray Tune.
2022-08-11 13:12:17,457 INFO trial_runner.py:515 -- A local experiment checkpoint was found and will be used to restore the previous experiment state.
2022-08-11 13:12:17,458 WARNING trial_runner.py:644 -- Attempting to resume experiment from /root/model_output/RayTesting_002. This will ignore any new changes to the specification.
2022-08-11 13:12:17,468 INFO tune.py:647 -- TrialRunner resumed, ignoring new add_experiment but updating trial resources.
2022-08-11 13:12:17,627 ERROR syncer.py:147 -- Log sync requires rsync to be installed.
(SimpleQTrainer pid=523) 2022-08-11 13:12:19,768        INFO simple_q.py:187 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
(SimpleQTrainer pid=523) 2022-08-11 13:12:19,768        INFO trainer.py:903 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(SimpleQTrainer pid=523) 2022-08-11 13:12:19,818        INFO trainable.py:588 -- Restored on 172.17.0.2 from checkpoint: /root/model_output/SimpleQTrainer_LunarLander-v2_1ff52_00000_0_2022-08-11_13-11-34/tmpc6nwcvm2restore_from_object/checkpoint-4
(SimpleQTrainer pid=523) 2022-08-11 13:12:19,818        INFO trainable.py:597 -- Current state after restoring: {'_iteration': 4, '_timesteps_total': None, '_time_total': 17.697097063064575, '_episodes_total': 16}
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 5 | Episode reward mean: -145.32
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 6 | Episode reward mean: -153.24
Trial: SimpleQTrainer_LunarLander-v2_1ff52_00000 | Training iteration 7 | Episode reward mean: -168.02
<-- CUT - All the way until completion without erros... -->
```

After point 3, I get this kind of output (you see the `FileNotFoundError: [Errno Path does not exist]` error):
The container is restarted when you see the line `Start Ray Tune.` somewhere halfway.  This `*** SIGTERM received at time=1660223333 on cpu 8 ***` and everything after until restart is because of stopping the Docker container.
```
Start Ray Tune.
2022-08-11 13:08:32,604 INFO trial_runner.py:510 -- No local checkpoint was found. Ray Tune will now start a new experiment.
2022-08-11 13:08:32,763 ERROR syncer.py:147 -- Log sync requires rsync to be installed.
(SimpleQTrainer pid=522) 2022-08-11 13:08:34,898        INFO simple_q.py:187 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
(SimpleQTrainer pid=522) 2022-08-11 13:08:34,898        INFO trainer.py:903 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Trial: SimpleQTrainer_LunarLander-v2_b375b_00000 | Training iteration 1 | Episode reward mean: -213.88
Trial: SimpleQTrainer_LunarLander-v2_b375b_00000 | Training iteration 2 | Episode reward mean: -217.36
Trial: SimpleQTrainer_LunarLander-v2_b375b_00000 | Training iteration 3 | Episode reward mean: -194.35
Trial: SimpleQTrainer_LunarLander-v2_b375b_00000 | Training iteration 4 | Episode reward mean: -190.43
*** SIGTERM received at time=1660223333 on cpu 8 ***
PC: @     0x7f3a9e681ad8  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f3a9e686140  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2022-08-11 13:08:53,973 E 1 1] logging.cc:325: *** SIGTERM received at time=1660223333 on cpu 8 ***
[2022-08-11 13:08:53,973 E 1 1] logging.cc:325: PC: @     0x7f3a9e681ad8  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-11 13:08:53,973 E 1 1] logging.cc:325:     @     0x7f3a9e686140  (unknown)  (unknown)
[2022-08-11 13:08:53,973 E 1 1] logging.cc:325:     @ ... and at least 1 more frames
Exception ignored in: <function RolloutWorker.__del__ at 0x7f3a74364310>
Traceback (most recent call last):
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable

Start Ray Tune.
2022-08-11 13:09:08,819 INFO trial_runner.py:515 -- A local experiment checkpoint was found and will be used to restore the previous experiment state.
2022-08-11 13:09:08,820 WARNING trial_runner.py:644 -- Attempting to resume experiment from /root/model_output/RayTesting_002. This will ignore any new changes to the specification.
2022-08-11 13:09:08,827 INFO tune.py:647 -- TrialRunner resumed, ignoring new add_experiment but updating trial resources.
2022-08-11 13:09:08,978 ERROR ray_trial_executor.py:533 -- Trial SimpleQTrainer_LunarLander-v2_b375b_00000: Unexpected error starting runner.
Traceback (most recent call last):
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 526, in start_trial
    return self._start_trial(trial)
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 433, in _start_trial
    self.restore(trial)
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 744, in restore
    obj = TrainableUtil.checkpoint_to_object(value)
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/utils/trainable.py", line 103, in checkpoint_to_object
    data_dict = TrainableUtil.pickle_checkpoint(checkpoint_path)
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/utils/trainable.py", line 83, in pickle_checkpoint
    checkpoint_dir = TrainableUtil.find_checkpoint_dir(checkpoint_path)
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/utils/trainable.py", line 118, in find_checkpoint_dir
    raise FileNotFoundError("Path does not exist", checkpoint_path)
FileNotFoundError: [Errno Path does not exist] /root/model_output/RayTesting_002/SimpleQTrainer_LunarLander-v2_b375b_00000_0_2022-08-11_13-08-32/checkpoint_000002/checkpoint-2
(SimpleQTrainer pid=521) 2022-08-11 13:09:11,160        INFO simple_q.py:187 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting `simple_optimizer=True` if this doesn't work for you.
(SimpleQTrainer pid=521) 2022-08-11 13:09:11,160        INFO trainer.py:903 -- Current log_level is ERROR. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
Traceback (most recent call last):
  File "/home/developer/workspace/main_MinWorkingExample.py", line 56, in <module>
    tune.run(SimpleQTrainer,
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/tune/tune.py", line 741, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [SimpleQTrainer_LunarLander-v2_b375b_00000])
Exception ignored in: <function RolloutWorker.__del__ at 0x7fe65b381310>
Traceback (most recent call last):
  File "/opt/conda/envs/cenv39ray/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
TypeError: 'NoneType' object is not callable
```

### Versions / Dependencies

I include a reproduction script including a docker and conda requirements file.
Basically Python 3.9 and Ray 1.13.0.

### Conda environment
I used this conda environment both on Windows and on Docker, just CPU for the sake of simplicity and size:
```
# conda_env_definition.yml

name: cenv39ray
channels:
- pytorch
- conda-forge
dependencies:
- python=3.9
- pytorch=1.11.0
- torchaudio
- torchvision
- cpuonly
- swig  # Needed to build 'box2d-py' in the pip install.
- pip=21.0.1
- pip:
   - ray==1.13.0
   - ray[tune]==1.13.0
   - ray[rllib]==1.13.0
   - box2d-py  # Because of using 'LunarLander-v2' environment.
   - psutil==5.8.0
   - gputil==1.4.0
```

### Docker container
Optional, build this docker image:
```
# dockerfile.txt

# Use base image having miniconda installed.
FROM continuumio/miniconda3

# For building pip package 'box2d-py' required because of using 'LunarLander-v2' environment.
RUN apt-get update && \
    apt-get install -y \
	gcc \
	g++

# Create environment variable for recognizing Docker container.
ENV RUNNING_IN_DOCKER_CONTAINER true

# Create conda environment.
COPY conda_env_definition.yml /data/conda_env_definition.yml
RUN conda env create --file=/data/conda_env_definition.yml
```

Command to build the Docker image:
`docker build -t ray_checkpoint_issue -f dockerfile.txt .`

Command to create the Docker container and start it (run from Powershell):
(Note, you need to change the volume path, I used the WSL-filesystem for the output folder (where the checkpoints are stored) to more closely resemble the situation on Azure, but this is not required.)
```
docker run -i -t `
    --name ray_checkpoint_issue `
	-v 'D:\dev\ray_checkpoint_issue:/home/developer/workspace' `
	-v '\\wsl$\Ubuntu-20.04\home\stefan\model_output:/root/model_output' `
	-w /home/developer/workspace `
	--shm-size=11gb `
	ray_checkpoint_issue `
	bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate cenv39ray && python -u main_MinWorkingExample.py'
```

Then, from Docker Desktop, you can stop/start the container from the 'containers' menu. When starting from Docker Desktop, also the Python code is automatically started again, just like Azure Machine Learning would do after a low-priority stop event.

### Python code
Minimum working example with only vanilla Ray blocks.
_Note, I messed around with the learning/exploration config to make sure this model does not train very wel! So that it is random if the next checkpoint performs better or worse than the previous. If you model trains too wel, last checkpoints are also the best and therefore only the last `keep_checkpoints_num` are kept, then the issue does not reproduce very well._

_Also, I increased `train_batch_size` from 32 to 1024 so a network update takes some time. This gives you the time to wait a wile before stopping the Python process, else, while you wait, already a new iterations is finished which interferes with the reproduction of the issue. If you system is much faster then mine, increase it further e.g. to 2048._

```
# Imports.
import os
import ray
from ray import tune
from ray.rllib.agents.dqn.simple_q import DEFAULT_CONFIG, SimpleQTrainer
from ray.rllib.utils.typing import TensorType
from ray.tune.logger import LoggerCallback


# Define a callback to print a line everytime an iteration is finished.
class TrailIterationProgressPrinterCallback(LoggerCallback):
    def log_trial_result(self, iteration: int, trial: "Trial", result: dict):
        print(f"Trial: {trial} | Training iteration {result['training_iteration']} | Episode reward mean: {result['episode_reward_mean']:.2f}")


# Configure checkpointing.
experiment_name = "RayTesting_002"
resume = "AUTO"
if os.getenv('RUNNING_IN_DOCKER_CONTAINER'):  # If running in a docker container, use a different path.
    local_dir = r'/root/model_output'
else:
    local_dir = r'D:\dev\ray_checkpoint_issue\Output'


# Create experiment config.
number_of_iterations = 20
env_name = "LunarLander-v2"

config_simple = DEFAULT_CONFIG.copy()
config_simple["env"] = env_name
config_simple["framework"] = "torch"
config_simple["_disable_preprocessor_api"] = True
config_simple["num_gpus"] = 0
config_simple["num_workers"] = 0
config_simple["lr"] = 0.00001
config_simple["rollout_fragment_length"] = 1
config_simple["train_batch_size"] = 1024  # Large, so training after an iteration takes some time and you can actually wait a while before stopping the Python process running this script.
config_simple["timesteps_per_iteration"] = 250
config_simple["target_network_update_freq"] = 500  # Default.
config_simple["log_level"] = "ERROR"
config_simple["explore"] = True
config_simple["exploration_config"] = {
    "type": ray.rllib.utils.exploration.epsilon_greedy.EpsilonGreedy,
    "initial_epsilon": 1.0,
    "final_epsilon": 0.99,  # use a random agent, so we get random checkpoints which perform better and are therefore kept.
    "epsilon_timesteps": config_simple["timesteps_per_iteration"] * number_of_iterations * 0.7,
    }

# Start tune and run experiments.
print('')
print('Start Ray Tune.')
tune.run(SimpleQTrainer,
         config=config_simple,
         callbacks=[TrailIterationProgressPrinterCallback()],
         stop={"training_iteration": number_of_iterations},
         verbose=0,
         resume=resume,
         checkpoint_freq=1,
         keep_checkpoints_num=2,
         checkpoint_score_attr='episode_reward_mean',
         local_dir=local_dir,
         name=experiment_name,
         )

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
Thank you @Stefan-1313 for such detailed writeup. Now I understand what is the difference between your setup and mine. 
In your setup, Ray Tune does not have the time to do final checkpointing (which updates what is the right ckpt to use when resuming the tune run).

From my understanding this is what is happening. Let's assuming that checkpoints are kept based on their chronological order - you can achieve this by not setting the scoring attr. 
1. ckpt_0004 is saved and  ckpt_0002 is deleted (since num_checkpoints = 2).
2. There is also an `experiment_state_xxx.json` file that keeps track of what checkpoint files each trial "current" has. See code pointers: `[load_trials_from_experiment_checkpoint](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L76)` and `[checkpoint](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L149)`. This information is out of date due to this throttling [logic](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L172). It still thinks that the current checkpoint is ckpt_0002, which is already deleted. The experiment checkpoint (`experiment_state_xxx.json` file) usually happens every 10s, unless the time used to do this checkpoint is too long to justify this frequency, when the period is further elongated. 

In a normal training setup, when the majority of the time is spent during training, I wouldn't be too worried about this. However, if each iteration is short and comparable to 10s. Then this kind of inconsistency becomes a problem. 

I wonder how long does your iteration take? 

This kind of inconsistency is sort of hard to avoid when the Tune program is hard killed like in your setup. However, I think we can be "smarter" when resuming Tune by checking what are available checkpoints and falling back somehow.

**Comment by Stefan-1313** [comment]
Hi @xwjiang2010 ,

Thanks for your in dept reply! Very interesting things you mention.
We are still developing our RL program with Ray so things are moving all the time.

---

> This kind of inconsistency is sort of hard to avoid when the Tune program is hard killed like in your setup

Usually, we run our code using Azure Machine Learning service on Low Priority nodes. Because of the low priority nodes, the docker container is stopped once in a while by Azure and restarted when Azure has sufficient compute capacity again. With the runs on Azure is where I noticed we very often got the `FileNotFoundError` when a resume was attempted. So that is why I started debugging locally in order to try to reproduce this. This GitHub issue is what about what I found :).

What I want to say, I have practically no control about this part. It is just Azure stopping the Docker container, and also Python in it. It gets not enough (or no) time to give Tune the change to do final checkpointing. I don't think it is a very unusual setup :). On Azure I don't know about another way except paying 10 times as much for dedicated compute capacity.

---

> I wonder how long does your iteration take?

On Azure, our iterations currently take about 200 to 250 seconds. So not very long, but long enough that I would expect the problem to almost never occur. But it (almost) always occurs :(. I cannot explain why it never works on Azure.

---

**Just an additional side note about what I see happening on Azure:**
I see 2 cases in my Azure runs:

1. As described in this GitHub issue, e.g. trying to resume from checkpoint 118 while checkpoint 119 has been created and checkpoint 118 has been deleted.
2. Sometimes it wants to resume from checkpoint e.g. 125 and says `FileNotFoundError` while the file is actually there, the path also seems ok (because it can also find the file to determine it wants to resume from checkpoint 125). I could not reproduce this locally, but though, if 1 is fixed, perhaps 2 also gets fixed as it might be related.

In multiple `RLlib` runs all started by the same `tune.run`, I see runs resuming and erroring on case 1, while others try to resume erroring on case 2. The ratio about 50-50 or in this order of magnitude.

A lot of new info, but for now, let's focus on case 1 here which I seem to be able to reproduce. But maybe it gives you a hint about a cause.

---

> The experiment checkpoint (experiment_state_xxx.json file) [...]

Very interesting file, it contains many usefull things for troubleshooting also! I can fine things like `local_dir` and `_local_checkpoint_dir` but I don't see where is stored to resume e.g. from checkpoint `checkpoint_000003`.

---

> There is also an experiment_state_xxx.json file that keeps track of what checkpoint files each trial "current" has. See code pointers: [load_trials_from_experiment_checkpoint](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L76) and [checkpoint](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L149). This information is out of date due to this throttling [logic](https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/execution/trial_runner.py?L172). It still thinks that the current checkpoint is ckpt_0002, which is already deleted. The experiment checkpoint (experiment_state_xxx.json file) usually happens every 10s, unless the time used to do this checkpoint is too long to justify this frequency, when the period is further elongated.

Maybe the throttling logic can be adapted? You want to store this kind of fallback information as fast as possible (I would say). As long as the information is not saved, the last known good checkpoint and resume information should not be deleted! In our code in the past we simply kept 2 (or optionally more) files for this. These file contained a flag which was set as final step to indicate all required data was saved correctly. We tried to resume from the newest file, which has this flag set. Maybe this is a more robust approach? Just an idea.

> However, I think we can be "smarter" when resuming Tune by checking what are available checkpoints and falling back somehow.

This sounds very good! It would be much better that if resuming from a checkpoints fails, `Tune` would try to resume from the before last checkpoint.
In addition, except for keeping the last x 'best' checkpoints, it would also be handy to keep the y 'last' checkpoints to have a more robust resume system. Off course this last idea is luxury :).

**Comment by xwjiang2010** [comment]
@Stefan-1313 Got it. What you said all makes total sense and is invaluable for us. (Fault tolerance is one big area we are going to focus on for the rest of the year).

I totally understand that when/how cloud provider kills nodes is entirely out of our user's control and that's exactly where Ray can do better to be more resilient to all that. So thank you for bringing this to our attention.

Along the lines of what we were saying, I think we could potential tackle this from two angles:
1. when checkpointing. Currently the "critical section" of this process is too big, resulting in more often inconsistency.
2. when resuming. We should be smarter.

cc @krfricke

**Comment by Stefan-1313** [comment]
@xwjiang2010 Thank you!

I'd let you to it, but if I can assist with testing something, let me know.

Last night I saw a resume on Azure which was successful! The exact same code, but with the only difference of setting `keep_checkpoints_num=None` (this was 5 before).

I had this only confirmed locally, but not yet on Azure as I have no control about when a resume is required. This is based on 1 observation for now, it could still be luck, but don't think so. Setting `keep_checkpoints_num=None` is a workaround for the short term, not ideal (especially with large checkpoints) but it seems to works.

**Comment by xwjiang2010** [comment]
For completeness, there is also this discussion: https://discuss.ray.io/t/tune-resume-with-trying-older-checkpoints/4624/7
