### ISSUE TITLE
[Data] Actor Configuration

### ISSUE THREAD

**Issue by thatcort** [ray-project/ray#27792]
### Description

We need the ability to configure data set transformation actors using runtime parameters. For example, 

This seems like a feature that could be implemented using named actors with options for specifying constructor params or an initialization method to be called.

### Use case

I have an actor that is used to calculate vector embeddings from a data set, but it needs to know the model to use at runtime. Then the actor pool for this transformation needs to be independent of other instantiations of the same class that use other models.

**Comment by xwjiang2010** [comment]
Thanks for putting this together.
I think there may be some misunderstanding about the mental model here. 
The actors are really pertained to one job. There are no actor pool hanging around for multiple jobs.
The actors are only created when you run one script and they are gone when it's finished. 
In that sense, actor is a "runtime" thing.

**Comment by thatcort** [comment]
@xwjiang2010 Thanks for that explanation. I thought they might get reused for other transformations.

Is there a way to configure them at runtime or is that still a valid feature request?

**Comment by xwjiang2010** [comment]
Does this work for you? Using `Task.__init__` you can configure the actors as you like.
```
class Task:
  def __init__(self, the_kind_of_sentence_transformer: str, **and_some_other_config):
    from sentence_transformers import SentenceTransformer
    self.model = SentenceTransformer(the_kind_of_sentence_transformer)
  def __call__(self, item):
    return self.model.encode(item)
    
data.map_batches(Task, compute=xxx, batch_size, num_gpus=1, etc)
```

**Comment by thatcort** [comment]
How do you pass in the value of `the_kind_of_sentence_transformer` in the `data.map_batches(...)` call?

**Comment by xwjiang2010** [comment]
got it. So you are right, the ctor of Task cannot take in arguments. Something like
```
class Task:
  def __init__(self):
    from sentence_transformers import SentenceTransformer
    # note: the_kind_of_sentence_transformer is implicitly captured when ray serializes the Task code to be sent to remote processes.
    self.model = SentenceTransformer(the_kind_of_sentence_transformer)
  def __call__(self, item):
    return self.model.encode(item)

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--type", type=str)
  data.map_batches(Task, xxx)
```

You then need to hook this up with some workflow/cron job in which to submit ray job - python my_script.pyy --type=xxx
xxx can be decided at runtime but at a higher level before executing the python script. For each run, xxx can be different, depending on your logic. Does that make sense?

**Comment by thatcort** [comment]
@xwjiang2010 Thanks for your help. In my code this comes in as a Ray Serve request that's then run with a Ray Workflow. Going from Serve -> command line isn't ideal.

This seems like a generally useful feature to have. E.g. What if I want to do translation and only get the languages at runtime. Then I'd want to configure which dictionaries are loaded in the same way.

**Comment by xwjiang2010** [comment]
@thatcort Can you let me know if the following is what you want?

1. user request comes in. The nature of this request is basically to kick off some batch prediction workload using some pretrained model. There is also configuration necessary for the workload - like the name of the model, the language to use etc. Those information are included as part of the request.
2. to handle this request, ray serve would want to start a ray workflow (that uses the Task class in the previous comment) and serve would just return this id to the user
3. later, the user may want to check out the result referencing the workflow id?

How about the following?
```
@serve.deployment
class MyDeployment:
    async def __call__(self, starlette_request: Request) -> Dict:
        type, language, input_data_path = parse_request(starlette_request)
       
        # run workflow asynchronously
        id = run_using_workflow(type, language, input_data_path)

        # Step 3: tensorflow output -> web output
        return {"workflow_id": id}
```

cc @simon-mo

**Comment by thatcort** [comment]
@xwjiang2010 Yes, at a high level, that's exactly what I need.

**Comment by clarkzinzow** [comment]
@thatcort @xwjiang2010 This kind of at-runtime multiplexing is already possible in Datasets (without having to dynamically define classes that close over args needed in its constructor) via providing a `CallableClass` to [`ds.map_batches()`](https://docs.ray.io/en/master/data/api/dataset.html#ray.data.Dataset.map_batches) along with constructor arguments that you wish to be passed through for initialization:
```python
class Task:
  def __init__(self, the_kind_of_sentence_transformer):
    from sentence_transformers import SentenceTransformer
    self.model = SentenceTransformer(the_kind_of_sentence_transformer)
  def __call__(self, item):
    return self.model.encode(item)

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--type", type=str)
  data.map_batches(Task, fn_constructor_args=(the_kind_of_sentence_transformer,))
```

**Comment by thatcort** [comment]
That solves it! Thank you, @clarkzinzow !

**Comment by xwjiang2010** [comment]
also @iycheng to see if this is intended usage pattern for workflow.

**Comment by thatcort** [comment]
`fn_constructor_args` isn’t listed in the API reference: https://docs.ray.io/en/latest/data/package-ref.html#ray.data.Dataset.map_batches

**Comment by richardliaw** [comment]
Should be added now! https://docs.ray.io/en/latest/data/api/dataset.html#ray.data.Dataset.map_batches
