### ISSUE TITLE
[RLlib] Excessive evaluation if rollout_fragment_length < timesteps_per_iteration

### ISSUE THREAD

**Issue by mgerstgrasser** [ray-project/ray#27821]
### What happened + What you expected to happen

If `rollout_fragment_length` is set to a value smaller than`timesteps_per_iteration` respectively `min_sample_timesteps_per_reporting`, then RLlib will evaluate (potentially much) more often than intended: Once it's in a training iteration where it should evaluate, it will call `Trainer.step()` many times, each time collecting only a small number of timesteps until it has collected enough to stop the iteration; however in *each* of those `step()` calls it will run evaluation, when I think the intention would be to only run it *once*. For very small rollout fragments, this can lead to prohibitively excessive amounts of evaluation. E.g. in the reproduction script below, rllib will run evaluation 10000 times with 10 episodes each, for 100k episodes, instead of 10 episodes, in every fifth training iteration. I assume the intended behavior and fix would be to only evaluate once, either in the first or final `step()` of a training iteration.

A workaround would be to set the timesteps per iteration / reporting to the same as the rollout fragment length, but then that leads to excessive amounts of data being logged, which can significantly slow down downstream data management and visualisation tools like tensorboard and wandb.

edit: A better workaround seems to be to set `min_time_s_per_reporting` to e.g. 60, then `evaluation_interval` effectively becomes measured by minutes, and at most ray should hang for a minute doing repeated evaluation, rather than potentially for a very long time. Still, this is not ideal if you want to be able to compare runs by environment steps sampled.

### Versions / Dependencies

ray==1.13.0

### Reproduction script

from copy import deepcopy

import ray
from ray import tune
from ray.rllib.agents.dqn.dqn import DEFAULT_CONFIG, DQNTrainer

config = deepcopy(DEFAULT_CONFIG)
config["rollout_fragment_length"] = 1
config["min_sample_timesteps_per_reporting"] = 10000
config["timesteps_per_iteration"] = 10000
config["evaluation_interval"] = 5
config["evaluation_duration"] = 10
config["evaluation_duration_unit"] = "episodes"
config["env"] = "SpaceInvadersNoFrameskip-v4"
ray.init(local_mode=True)
tune.run(DQNTrainer, config=config, verbose=3)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mvindiola1** [comment]
Hi @mgerstgrasser,

I noticed this error too.  Can you check if the error still exists in the nightly build.  When I checked I thought I saw it was fixed.

**Comment by mgerstgrasser** [comment]
Huh, you're right, it looks like it's been changed already. My bad! Thank you.
