### ISSUE TITLE
[docs] None of the doctests are running

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#27853]
### What happened + What you expected to happen

A the moment, all our doc tests are  `# doctest: +SKIP`ed. This makes us miss a bit opportunity to keep them in sync with the rest of the code and use them as unit tests.

I believe the reason is because in the documentation Ray is heavily mocked (e.g. all the C extensions are mocked). We should have a mode where this is not the case and run `make doctest` in that mode.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by maxpumperla** [comment]
@pcmoritz are you sure they don't run at all? In https://github.com/ray-project/ray/pull/23418 I fixed all 600 of them, skipping many, but certainly not all (I'd estimate around 40-50%). But at that point `make doctest` was running. Are you saying we deactivated this again since then?

**Comment by hora-anyscale** [comment]
Per Triage Sync: old issue, doc tests are running
