### ISSUE TITLE
[2.0][nightly-test] golden_notebook_modin/dask_xgboost_test failure

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27866]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/904#0182a037-832c-48a2-821d-595e851ca4b9
https://buildkite.com/ray-project/release-tests-branch/builds/904#0182a037-8332-4850-a6c4-b11a29a8f044

```


Traceback (most recent call last):
--
  |  
  | File "workloads/modin_xgboost_test.py", line 26, in <module>
  |  
  | main()
  |  
  | File "workloads/modin_xgboost_test.py", line 13, in main
  |  
  | import_and_execute_test_script(NOTEBOOK_PATH_RELATIVE_TO_RAY_REPO)
  |  
  | File "/tmp/release-efyovqqVql/release/golden_notebook_tests/workloads/util.py", line 13, in import_and_execute_test_script
  |  
  | assert notebook_path.exists()
  |  


```

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
https://github.com/ray-project/ray/pull/27865

**Comment by xwjiang2010** [comment]
@scv119 do you want to cherry-pick this one?

**Comment by scv119** [comment]
sgtm, let me do that.
