### ISSUE TITLE
[2.0][releases] air_benchmark_tensorflow_mnist_gpu_4x4 timed out

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27867]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/904#0182a037-82d3-4420-bd40-64262480f31b
```


[INFO 2022-08-15 00:49:42,587] log.py: 36  Did not find any results.
--
  | [INFO 2022-08-15 00:49:42,588] artifacts.py: 34  Wrote test config and result to artifacts directory: /tmp/artifacts
  | [ERROR 2022-08-15 00:49:42,588] run_release_test.py: 159  Cluster command timed out after 3600 seconds.
  | Traceback (most recent call last):
  | File "/tmp/release-oEvBIBWkqg/release/ray_release/glue.py", line 254, in run_release_test
  | command, env=command_env, timeout=command_timeout
  | File "/tmp/release-oEvBIBWkqg/release/ray_release/command_runner/sdk_runner.py", line 116, in run_command
  | f"Cluster command timed out after {timeout} seconds."
  | ray_release.exception.CommandTimeout: Cluster command timed out after 3600 seconds.
  |  


```

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
Looking at the log, seems legit timeout. 
@krfricke Are you ok to increase the timeout? Each portion is taking around 480 seconds and there are 6 of them. Plus some data downloading and initial setup.

**Comment by xwjiang2010** [comment]
actually does seem a true regression. On master: https://buildkite.com/ray-project/release-tests-branch/builds/893#0182943a-545e-4b2a-b245-4597853a6d17

Each leg only takes < 85 seconds. (comparing with 480 seconds)

**Comment by xwjiang2010** [comment]
let's see how the retry goes - https://buildkite.com/ray-project/release-tests-branch/builds/904#0182a21f-c89b-417c-bd76-57077090c412

**Comment by xwjiang2010** [comment]
Debugged this with @krfricke  actually the difference between the two is that one is smoke test. Preparing a PR to increase non-smoke test timeout.
