### ISSUE TITLE
[AIR] Thread creation FAILED in tensorflow training

### ISSUE THREAD

**Issue by guodashun** [ray-project/ray#27895]
### What happened + What you expected to happen

We test the tensorflow distributed training task in our local cluster(10 nodes with 64 cpus per node). We test the situation that train with a big number of workers.
```
ACTORS_NUM = 64 or more
trainer = Trainer(backend='tensorflow', num_workers=ACTORS_NUM, use_gpu=False)
```
The question is, when we set a num that is bigger than the num of CPU in one node, we get the error msg as follows:
```
 *** SIGABRT received at time=1660614327 on cpu 53 ***
PC: @     0x7f956de3cfb7  (unknown)  raise
    @     0x7f956e201980       3904  (unknown)
    @     0x7f6277c65be8        512  tensorflow::(anonymous namespace)::PThread::PThread()
    @     0x7f6277c65c61         96  tensorflow::(anonymous namespace)::PosixEnv::StartThread()
    @     0x7f627c9cd80d        400  Eigen::ThreadPoolTempl<>::ThreadPoolTempl()
    @     0x7f627c9cf0bf        512  tensorflow::thread::ThreadPool::ThreadPool()
    @     0x7f627c1a14fc        128  tensorflow::ComputePool()
2022-08-16 09:45:27.881548: F tensorflow/core/platform/default/env.cc:73] Check failed: ret == 0 (11 vs. 0)Thread creation via pthread_create() failed.
```
And we find when we add the param `resources_per_worker={"CPU": 2}` (CPU num per worker is 2 or more), the test program can work well. The test results can be summarized as follows:
| data_size | num_workers | cpu_per_workers | status |
| --------- | ----------- | --------------- | ------ |
| 3GiB      | 64          | 1               | FAILED |
| 3GiB      | 64          | 2               | PASSED |
| 3GiB      | 48          | 1               | PASSED |
| 300MiB    | 64          | 1               | FAILED |
| 300MiB    | 64          | 2               | PASSED |
| 300MiB    | 48          | 1               | PASSED |

I am confused if there is a bug in ray or in tensorflow.

### Versions / Dependencies

|  lib | version  |
| ------------ | ------------ |
|  python | 3.8.13  |
|  ray | 2.0.0rc0 & 1.13  |
|tensorflow|2.5.0|

### Reproduction script

```
ray_init() # something for ray initialization
df = load_data() # load data and return a modin data with shape (int(1e8), 5)

def test_tf():
    import tensorflow as tf
    batch_size = 1024
    epoch = 1
    
    train_set, test_set = train_test_split(df, train_size=0.9, random_state=42)
    dataset = ray.data.from_modin(train_set)


    def build_and_compile_model(config):
        model = tf.keras.Sequential(
            [
                tf.keras.layers.InputLayer(input_shape=(4,)),
                tf.keras.layers.Dense(10),
                tf.keras.layers.Dense(1),
            ]
        )

        model.compile(
            optimizer=tf.keras.optimizers.SGD(learning_rate=config.get("lr", 1e-3)),
            loss=tf.keras.losses.mean_squared_error,
            metrics=[tf.keras.metrics.mean_squared_error],
        )
        return model
    
    def train_func_distributed(config):
        strategy = tf.distribute.MultiWorkerMirroredStrategy()

        with strategy.scope():
            # Model building/compiling need to be within `strategy.scope()`.
            multi_worker_model = build_and_compile_model(config)
        
        # just for kill the annoying warning
        options = tf.data.Options()
        options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF

        ray_dtr = ray.train.get_dataset_shard().to_tf(
            label_column='labels',
            batch_size=batch_size,
            output_signature=(
                tf.TensorSpec(shape=(None), dtype=tf.dtypes.float64),
                tf.TensorSpec(shape=(None), dtype=tf.dtypes.float64),
            )
        ).with_options(options)
        
        results = []
        for _ in range(epoch):
            history = multi_worker_model.fit(ray_dtr)
            results.append(history.history)
        
        return results



    trainer = Trainer(backend='tensorflow', num_workers=64, use_gpu=False, resources_per_worker={"CPU": 1})
    trainer.start()
    results = trainer.run(
        train_func=train_func_distributed,
        dataset=dataset,
        config={"lr": 1e-3,}
    )
    trainer.shutdown()

test_tf()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
I looked up this return code (11) - it suggests that the machine is running low on resources.
To address this, you need to restrict how many workers are running simultaneously on the same machine. Limiting `num_workers` is one way, setting `resources_per_worker` to be larger than 1 CPU is another way. They are effectively doing the same thing.

**Comment by guodashun** [comment]
> setting resources_per_worker to be larger than 1 CPU is another way. 

emmm...It's not very clear for me that it is a way to limit the resource request.
As my test results,

>| index| data_size | num_workers | cpu_per_workers | status |
> |-------| --------- | ----------- | --------------- | ------ |
> |test 1| 3GiB      | 64          | 1               | FAILED |
> |test 2| 3GiB      | 64          | 2               | PASSED |
the two test has the same `num_workers` and the **test 2** set the `resources_per_worker` to be larger than 1. I think the **test 2** requests more resources than test 1, isn't it?

**Comment by xwjiang2010** [comment]
Hi @guodashun 
I think the problem is when there are too many workers placed on one machine, that machine's resources are used up, thus the error.

Say each machine has 4 cores. By default, 4 workers will be placed on the machine. Now, if we set `resources_per_worker=2`, only 2 workers can be placed on the machine. So the machine is less likely to run low on resources. Does that make sense?

**Comment by guodashun** [comment]
Yeah, thank you, I think I've got the point.
