### ISSUE TITLE
[AIR] Better error message for column dim mismatch 

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#27925]
### What happened + What you expected to happen

When iter tf batches like this .. 

```python
def to_tf_dataset(dataset: ray.data.Dataset, batch_size):
        def to_tensor_iterator():
            for batch in dataset.iter_tf_batches(
                batch_size=batch_size,
                prefetch_blocks=prefetch_blocks
            ):
                yield {k: v for k, v in batch.items() if k in feature_columns}, batch["label"]

        output_signature = (
            output_signatures,
            tf.TensorSpec(shape=(None, 500), dtype=tf.int64, name='label'),
        )
        tf_dataset = tf.data.Dataset.from_generator(
            to_tensor_iterator, output_signature=output_signature
        )
        return prepare_dataset_shard(tf_dataset)
```

We would see exception directly from TF level complaining about tensor dim mismatch, which could be caused by user upstream UDF.

```
(RayTrainWorker pid=88734) 2022-08-16 14:53:46.489790: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: TypeError: `generator` yielded an element of shape (40, 150) where an element of shape (None, 1, 150) was expected.
```

## Action needed 

Return which column is problematic so the error message is at least actionable.

### Versions / Dependencies

master

### Reproduction script

above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@jiaodong are you looking into this as part of the tensor story?

**Comment by jiaodong** [comment]
It's a bit orthogonal to it as this error is legit and expected, mostly just need to add column name on the mismatched dim so user has better clue what went wrong in UDF. I have this in backlog as "snacking" PR sometime

**Comment by richardliaw** [comment]
OK then let's dump this to P2. Seems like this can also be addressed by having a better to_tf story.
