### ISSUE TITLE
[AIR] Correct error doesn't propagate

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#27922]
### What happened + What you expected to happen

I tried to save my model with `session.report` and `TorchCheckpoint` but I got 

> RuntimeError: Some workers returned results while others didn't. Make sure that `session.report()` (legacy API:`train.report()` and `train.save_checkpoint()`) are called the same number of times on all workers.

See the [full traceback](https://gist.github.com/bveeramani/dfd0f2f4bbe8b2c916d6ba86ef5bc21d).

This issue arose while updating  [Training a Torch Classifier](https://docs.ray.io/en/master/ray-air/examples/torch_image_example.html) to use `TorchCheckpoint`.

### Versions / Dependencies

Ray: 436c89ba1a337fffcd6f46c78c4d5a5a3434d0a8
Python: 3.8.5
Cluster environment: default_cluster_env_nightly-ml_py38:1

### Reproduction script

```
import torch.nn as nn

from ray.air import session
from ray.air.config import ScalingConfig
from ray.train.torch import TorchCheckpoint, TorchTrainer


class Identity(nn.Module):
    def forward(self, x):
        return x


def train_loop_per_worker(config):
    model = Identity()
    for _ in range(2):
        checkpoint = TorchCheckpoint.from_model(model)
        session.report({}, checkpoint=checkpoint)


trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config=ScalingConfig(num_workers=2),
)
trainer.fit()
```

Interestingly, if you use `torch.nn.Identity` instead of `__main__.Identity`, then the program doesn't error.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
The more concerning thing to me is, why didn't this error show up?

**Comment by amogkam** [comment]
This is the same issue as this https://discuss.ray.io/t/error-occurs-when-call-save-checkpoint/4790/5.

Seems like the pickling/serialization issues are not actually being surfaced.

**Comment by amogkam** [comment]
@bveeramani can we add a `from_state_dict` method to `TorchCheckpoint`? Using state dicts should be the recommended way to save models, rather than the model directly.

**Comment by bveeramani** [comment]
@amogkam yeah, I can do that today.

**Comment by Yard1** [comment]
I tried to repro this on current master and:
a) the original picking issue is gone
b) trying to force an error in `torch.save` causes the correct message to be propagated.

Therefore, I think this issue can be closed as resolved. @bveeramani

**Comment by bveeramani** [comment]
Yeah, looks like it's been resolved. Closing.
