### ISSUE TITLE
[AIR/data] Use both CPU and GPU actors in ActorPool or Dataset for batch inference with different batch size.

### ISSUE THREAD

**Issue by rueian** [ray-project/ray#27953]
### Description

Hi, I would like to use all my computing resources to do batch inference. But it seems that the current API of ActorPool and Dataset can only utilize CPU or GPU actors, not both.

Says I have 100 pure CPU servers and 5 GPU servers. When I do this:
```python
pool = ActorPool([GPUModel.remote() for _ in range(5)])
[v for v in pool.map_unordered(lambda actor, batch: actor.inference.remote(batch), chunks(items, 200))]
```
All CPU servers are idle.

But if I do this:
```python
pool = ActorPool([GPUModel.remote() for _ in range(5)] + [CPUModel.remote() for _ in range(100)])
[v for v in pool.map_unordered(lambda actor, batch: actor.inference.remote(batch), chunks(items, 200))]
```
Then the whole pool becomes pretty slow because CPU actors take too many items due to the equal size of batches.
And this will end up GPU servers idle while CPU actors are busy for a long time.

So, I wish there is an API in ActorPool or Dataset that can do something similar to this:

```python
pool = ActorPool(
    [{'actor': GPUModel.remote(), 'batch_size': 1000} for _ in range(5)] + 
    [{'actor': CPUModel.remote(), 'batch_size': 10} for _ in range(100)]
)
[v for v in pool.batch_unordered(lambda actor, batch: actor.inference.remote(batch), items)]
```
This pool will keep taking batches from input items for idle actors while the required batch size is specified by actors.

I think this kind of behavior is helpful to utilize all the computing resources. Any feedback or suggestion is welcome, thanks.

**Comment by amogkam** [comment]
Hey @rueian, thanks for raising this! This is definitely a very interesting feature request and something we can look into supporting.

Quick question: for specifying the batch sizes for the CPU actors vs. GPU actors would you prefer that to be manually user specified or have it be automatically/dynamically determined by Ray Datasets for example?

And also just curious, for your batch prediction what data scale are you working at and what models are you using for prediction?

**Comment by rueian** [comment]
> Quick question: for specifying the batch sizes for the CPU actors vs. GPU actors would you prefer that to be manually user specified or have it be automatically/dynamically determined by Ray Datasets for example?

Sure, that will be very cool and save user a lot of time tuning the parameter if each batch size can be dynamically determined by Ray based on the round trip time of each actor.

> And also just curious, for your batch prediction what data scale are you working at and what models are you using for prediction?

In this case, I have millions of images every hour that need to be passed through a PyTorch model with a fixed computing cluster. That’s why I am looking into Ray to fully utilize the cluster. Thank you guys. Ray really helps me a lot. Currently I have implemented the proposed ActorPool by myself, and it works quite well.

**Comment by rueian** [comment]
Just for reference, here is an example implementation I currently used

https://gist.github.com/rueian/6cf8f6ef1f13bada90ac8ae92088f0ae
