### ISSUE TITLE
[2.0][nighly-test] air_benchmark_tune_torch_mnist_large_gpu failed

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#27989]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/918#0182af55-42a2-4436-946f-1d56833a1217
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_s1YsfvyYLjPcXzw7b6GWfdU5

### Versions / Dependencies

releases/2.0.0

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
```
RuntimeError: [Rank 1] Caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, TensorShape=[268298], Timeout(ms)=1800000) ran for 1801490 milliseconds before timing out.
```

This is the same as https://github.com/ray-project/ray/issues/27708

**Comment by matthewdeng** [comment]
Works on retry 
https://buildkite.com/ray-project/release-tests-branch/builds/918#0182b1d5-d9a4-435e-957c-bf3c2c7bc84e
