### ISSUE TITLE
Actor Handle datastructures can grow unbounded

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#2798]
Passing an actor into a task or pickling an actor handle will fork the handle and create a new ActorHandleID. These are never cleaned up, so it can cause the following datastructure to blow up:

https://github.com/ray-project/ray/blob/98fed67b452ae9aa172c3ef3b4a6538f97388ade/src/local_scheduler/local_scheduler_algorithm.cc#L56

The problem can for example be reproduced like this:
```
import ray

ray.init()

@ray.remote
class Actor(object):
    def __init__(self):
        pass

@ray.remote
def f(actor):
    pass

a = Actor.remote()

for i in range(1000000000):
    print(i)
    ray.get(f.remote(a))
```

**Comment by robertnishihara** [comment]
Probably the same as #5814.
