### ISSUE TITLE
Does ray have a way to apply a trained policy to a real game?

### ISSUE THREAD

**Issue by luochao1024** [ray-project/ray#2799]
Suppose we train a policy to play pong using IMPALA on ray. Does ray have a way to apply a trained policy to a real game like this one https://www.youtube.com/watch?v=V1eYniJ0Rnk&vl=en.

**Comment by ericl** [comment]
You can run rollout.py on the checkpoint, which I believe visualizes the game by default. See docs here: https://ray.readthedocs.io/en/latest/rllib-training.html#evaluating-trained-agents
