### ISSUE TITLE
[Ray submit] Cancellation of job submitted via `ray submit` does not cancel resource demands

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#28005]
### What happened + What you expected to happen

I created a cluster on AWS and submitted a job which required several worker nodes. Before the job finishes, if I cancel it using ctrl+c, the job cancels (dashboard shows no CPU utilization) but `ray status` still shows resource demands.

Since the resource demands still exist, the autoscaler will repeatedly create new nodes, then remove them after the idle timeout period, then create new nodes again.

This does not happen with `ray job submit`.

### Versions / Dependencies

I tried ray 1.13 and ray 2.0.0rc0

#### Repro steps:
1. Set up a cluster (a config is provided below) with a head node and worker nodes.
2. Create a Ray script which will use many CPUs, such that the autoscaler will add nodes to the cluster.
3. Run the script using `ray submit`:
```
$ ray submit <cluster-config>.yaml script.py
```
4. Use `ray status` to confirm that resource demands have been placed, and that additional nodes are being provisioned.
5. Kill the `ray submit` process via ctrl+c
6. Observe that the resource demands persist in `ray status`, and that additional nodes are provisioned, idle, decommissioned, then provisioned again, etc. The dashboard will show no CPU utilization.

#### Cluster yaml
This is for Ray 2.0.0rc0. Change the `image` for ray 1.13.
```
cluster_name: cade-bug-repro

upscaling_speed: 10
idle_timeout_minutes: 1

# The maximum number of worker nodes to launch in addition to the head
# node.
max_workers: 11

docker:
  image: "rayproject/ray:2.0.0-py36"
  #image: "rayproject/ray:1.13.1-py36-cpu"
  container_name: "ray_container"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    ssh_private_key: -----------

setup_commands: []
head_setup_commands: []
worker_setup_commands: []

provider:
  type: aws
  region: us-west-2
  availability_zone: us-west-2a

available_node_types:
  head:
    min_workers: 0
    max_workers: 0
    resources:
      CPU: 8
    node_config:
      KeyName: -----------
      InstanceType: m5.4xlarge
      ImageId: latest_dlami
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200

  # Configurations for the worker nodes.
  worker:
    min_workers: 0
    max_workers: 10
    resources:
      CPU: 16
    node_config:
      KeyName: -----------
      InstanceType: c5.4xlarge
      ImageId: latest_dlami
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200

head_node_type: head
```

#### Ray script
```
#!/usr/bin/env python

import ray
import random
import time
import math
from fractions import Fraction

ray.init(address='auto')

@ray.remote
def pi4_sample(sample_count):
    """pi4_sample runs sample_count experiments, and returns the
    fraction of time it was inside the circle.
    """
    in_count = 0
    for i in range(sample_count):
        x = random.random()
        y = random.random()
        if x*x + y*y <= 1:
            in_count += 1
    return Fraction(in_count, sample_count)


SAMPLE_COUNT = 1_000_000
FULL_SAMPLE_COUNT = SAMPLE_COUNT * 60 # 60 CPUs, which will request several worker nodes.
BATCHES = int(FULL_SAMPLE_COUNT / SAMPLE_COUNT)
print(f'Doing {BATCHES} batches')
results = [pi4_sample.remote(sample_count=SAMPLE_COUNT) for _ in range(BATCHES)]
output = ray.get(results)

pi = sum(output)*4/len(output)
print(float(pi))

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cadedaniel** [comment]
I spoke with @wuisawesome about a simpler reproduction script using a mock cluster, but couldn't reproduce the issue! This makes me suspect `ray submit` instead of the scheduler.
```
import ray
from ray.cluster_utils import AutoscalingCluster

cluster = AutoscalingCluster(
    head_resources={"CPU": 6},
    worker_node_types={
        "cpu_node": {
            "resources": {
                "CPU": 4,
                "object_store_memory": 1024 * 1024 * 1024,
            },
            "node_config": {},
            "min_workers": 0,
            "max_workers": 20,
        },
    },
)

cluster.start()
```

**Comment by jwlarocque** [comment]
Is there an easy way to correct the resource demands when this occurs?  (I've just been killing the whole cluster.)

**Comment by cadedaniel** [comment]
You can restart the Ray runtime: `ray up config.yaml --restart-only`. It should keep the nodes around and simply restart docker containers / ray processes.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @scv119 - this appears to be a core issue.

**Comment by wuisawesome** [comment]
There's another instance of the problem here: https://discuss.ray.io/t/the-pending-tasks-actors-remain-on-ray-cluster-when-the-driver-die-unexpected/7086/12

there's a chance that this is specific to `ray submit` and not a core bug, but really not clear rn.

**Comment by rkooo567** [comment]
I think this should be fixed in the master by @clarence-wu . Can you double check it?

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/issues/31154

**Comment by clarng** [comment]
Yea the PR fixes resource demands that are showing in ray status, so I think this is good to close @cadedaniel

**Comment by cadedaniel** [comment]
Can we attempt to repro the issue to make sure we didn't miss anything? I can try this week, maybe next

**Comment by wuisawesome** [comment]
@cadedaniel will assign to you. you can close it if you can't repro, otherwise feel free to pull someone else in to help out.
