### ISSUE TITLE
[AIR] Torch `UserWarning` during training

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28003]
### What happened + What you expected to happen

I ran `TorchTrainer.fit` and got an unexpected warning:
> (RayTrainWorker pid=3415) /Users/bveeramani/GitHub/ray/python/ray/air/_internal/torch_utils.py:122: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:178.)

### Versions / Dependencies

Ray: 7d981d6ced666a149049bf6887ba873c21979703

### Reproduction script

See "Training a Torch classifier" example.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
@krfricke can you take a look and see what is raising this warning, and if we should just entirely mute it?
