### ISSUE TITLE
[Graph] any exmaples on how to execute a DAG graph?

### ISSUE THREAD

**Issue by jinfagang** [ray-project/ray#28010]
### Description

DAG eseentially a series of models, among them maybe some are sequencial, some can be multi-processing.

Does there anyway (examples) to construct these DAGs and using ray for inference?

so that ray can automatically dispatch them in a multiple processing way/

### Use case

DAG eseentially a series of models, among them maybe some are sequencial, some can be multi-processing.

Does there anyway (examples) to construct these DAGs and using ray for inference?

so that ray can automatically dispatch them in a multiple processing way/

**Comment by architkulkarni** [comment]
Hi @jinfagang, Ray Seve provides a [Deployment Graph API](https://docs.ray.io/en/master/serve/key-concepts.html#deployment-graph), is this what you're looking for?

**Comment by jinfagang** [comment]
@architkulkarni Hi, actually am not serving it thought https.

What am looking for is just make my multiple models in a DAG and using ray to dispatch them in maximum multiple-processing way.

I don't want anything related about https since it will effect maximum efficiency. Does there any more pure && efficient way to make a DAG and then using it to run in ray?

To be specific, my model like this:

detection_modelA ----------->modelC

                                                           |
                                                           |

detection_modelB -----------> --------------> modelD----> output


As you can see, there are at least 2 model can run in multipleprocessing, how to use it avoiding serve?

**Comment by architkulkarni** [comment]
You can use Ray Serve without using HTTP, simply calling your models using Python handles as in the example I linked above.  Specifically, you can set `HTTPOptions` to  `"NoServer"` to disable the HTTP server: https://docs.ray.io/en/latest/serve/package-ref.html

**Comment by jinfagang** [comment]
@architkulkarni hi, how could I disable and enable customized method like RPC further?

**Comment by architkulkarni** [comment]
We don't support any customization with RPC, we only support querying endpoints from Python or from HTTP.  Could you share more details of your use case?

**Comment by jinfagang** [comment]
@architkulkarni actually this is what I want, I just need ray to run graph, when I get output, rest RPC handling by myself.

How to make it runing graph only without evolving anything about http? (it will cost time)

**Comment by architkulkarni** [comment]
You could use Ray Serve with `NoServer`, and nothing about HTTP would be involved.  Or perhaps you're looking for something like Ray Workflows? https://docs.ray.io/en/latest/workflows/basics.html

**Comment by jinfagang** [comment]
@architkulkarni waoo, workflow seems exactly what I want!!

Does there any example on workflow supports on a more complicated graph? Such as a graph which node has 2 inputs?
Also, may I ask, if two node are parallel ( they can runing meanwhile), will ray actually calculated it simuteneously?

**Comment by architkulkarni** [comment]
Sorry for the delayed reply, yes, I don't think there are any restrictions on the data type.
I found one basic example with two inputs here: https://docs.ray.io/en/latest/workflows/basics.html#retrieving-workflow-results (the`add` function)
And yes, parallel tasks will be calculated simultaneously.

**Comment by architkulkarni** [comment]
Closing because the question has been answered.
