### ISSUE TITLE
[CI] [core] `linux://python/ray/tests:test_cli` is failing/flaky on master.

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#28039]
- 227aef381a605cb1ebccbba4e84b840634196a35 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/ray-builders-branch/builds/9602#0182bd5b-f9cc-43e3-a133-f0eb1df3dcee)
- 227aef381a605cb1ebccbba4e84b840634196a35 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/ray-builders-branch/builds/9602#0182bd5b-f9dd-4fd2-8cd1-2a12a604488e)
- 11c9b1779d475f6f1d55ef63a4341d74cfb631a3 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/ray-builders-branch/builds/9601#0182bba8-3223-4d7c-8d49-439b8b4f3f8d)
- 11c9b1779d475f6f1d55ef63a4341d74cfb631a3 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/ray-builders-branch/builds/9601#0182bba8-3210-476b-9dcf-e81f6e97aa9c)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_cli-END
....

I saw this on PR #26295 after rebasing of master

**Comment by mattip** [comment]
The error is that moto (the boto3 mocking package) does [not have `describe_images`](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#ec2) for ec2 instances, so I wonder how this ever worked?
```
# moto (boto3 mock) only allows a hardcoded set of AMIs
--
        dlami = (
>           moto.ec2.ec2_backends["us-west-2"]
            .describe_images(filters={"name": "Deep Learning AMI Ubuntu*"})[0]
            .id
        )
E       AttributeError: 'AccountSpecificBackend' object has no attribute 'describe_images'
```

**Comment by clarng** [comment]
I think this issue is old but there seems to be a new issue with this test 

<img width="1662" alt="Screen Shot 2022-11-14 at 2 06 59 PM" src="https://user-images.githubusercontent.com/22830327/201778153-d58cdf80-c884-422a-afe3-9f9296366440.png">

**Comment by mattip** [comment]
The [error I see](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1043#01847761-c4b5-4c9a-9f5b-94ceccc151f1/1278-1874) is
```
_fail_if_false(
            head_proc.exitcode == 0,
>           head_output,
            f"Head process failed unexpectedly({head_proc.exitcode})",
        )
E       UnboundLocalError: local variable 'head_output' referenced before assignment

python/ray/tests/test_cli.py:515: UnboundLocalError
```

which seems to come from commit 3d8ca6cf0f. The code path is only triggered if there is another error, so it is not usually active.

**Comment by rkooo567** [comment]
I will take a look.  It should be because we removed some unused APIs from the dashboard, and the test somehow tests that
