### ISSUE TITLE
[Kubernetes][Autoscaler] Solidify interaction between Autoscaler and KubeRay operator

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#28036]
### Description

In the current implementation of the Autoscaler/KubeRay operator integration, there are gaps that can allow for race conditions.

Here's one possible idea for how an autoscaler update could look (we might need a bit of design discussion here): 

1. Make a single K8s API read query (list pods).
2. Compute the desired scale change.
3. Make a single K8s write request (patch RayCluster CR)
4. Provide some mechanism to wait for operator-managed cluster state to converge before submitting a patch.

### Use case

Build confidence that the Ray autoscaler works correctly on Kubernetes.

**Comment by kaushik143** [comment]
@DmitriGekhtman Have we finalized any design for reconciliation?

**Comment by DmitriGekhtman** [comment]
Design doc forthcoming! I'll have some ideas to share next week!

**Comment by DmitriGekhtman** [comment]
I've started implementing the proposal described here:
https://docs.google.com/document/d/1JyQINBFirZw7YenA_14zize0R3hIII1_fnfQytIXTPo/

Apologies in advance that the doc might be unfriendly to those who haven't worked on autoscaler development.
The proposal doesn't change architecture but rather just rewires some internal logic.

**Comment by DmitriGekhtman** [comment]
Handled in
https://github.com/ray-project/ray/pull/30281
https://github.com/ray-project/ray/pull/29933
https://github.com/ray-project/ray/pull/30502
https://github.com/ray-project/kuberay/pull/740
