### ISSUE TITLE
[Core] Example is broken: `ray.runtime_context.get_runtime_context()`

### ISSUE THREAD

**Issue by ofey404** [ray-project/ray#28042]
### Description

[Link](https://docs.ray.io/en/latest/ray-core/package-ref.html)

The example of `ray.runtime_context.get_runtime_context()` is garbled:

![image](https://user-images.githubusercontent.com/35857538/185833564-43f35b75-f46c-4e4c-8ad7-d88d62c55bed.png)

### Link

[source code section](https://docs.ray.io/en/latest/_modules/ray/runtime_context.html#get_runtime_context)

**Comment by ofey404** [comment]
I can fix it, but I am not sure how to build the documentation locally.

**Comment by richardliaw** [comment]
How about try just pushing a draft PR? We have a builder that runs on CI and you can view it after pushing

**Comment by matthewdeng** [comment]
Hey @ofey404, looks like this was already fixed in [master](https://docs.ray.io/en/master/ray-core/package-ref.html#runtime-context-apis) by #25006!

**Comment by ofey404** [comment]
> Hey @ofey404, looks like this was already fixed in [master](https://docs.ray.io/en/master/ray-core/package-ref.html#runtime-context-apis) by #25006!

Thank you for the attention!
