### ISSUE TITLE
[ray] model in onnxruntime runing with OMP doesn't work in ray

### ISSUE THREAD

**Issue by lucasjinreal** [ray-project/ray#28044]
### What happened + What you expected to happen

I have a model running in onnxruntime, when locally, multi-thead model runs faster than single-thread model,

but in ray, it was the same ,how could this possible?

### Versions / Dependencies

I have a model running in onnxruntime, when locally, multi-thead model runs faster than single-thread model,

but in ray, it was the same ,how could this possible?

### Reproduction script

I have a model running in onnxruntime, when locally, multi-thead model runs faster than single-thread model,

but in ray, it was the same ,how could this possible?

**Comment by matthewdeng** [comment]
Hey @jinfagang, I'm not familiar with onnxruntime but one possibility is that the number of threads is being limited by the `OMP_NUM_THREADS` environment variable, which Ray currently defaults to 1. 

See the note in [this section](https://docs.ray.io/en/latest/ray-core/configure.html#cluster-resources).

**Comment by jinfagang** [comment]
@matthewdeng Hi, I manually set that env to 8 already. Didn't work. My local inference (out of ray) works as expected.

**Comment by jinfagang** [comment]
@matthewdeng also, the num_cpus is CPU physic number or core number? How does a machine can have 8 cpus and 1 gpus?

**Comment by xwjiang2010** [comment]
@jinfagang do you have a repro script that I can try?
Also notice that `num_cpus` is just for resource accounting - it does not offer any kind of resource isolation.
Can you make sure that in the ray actor/task when you print `OMP_NUM_THREADS`, the output is larger than 1?

**Comment by jinfagang** [comment]
@xwjiang2010 the model is huge, hard to share it, does ray anywhere will limit cpu cores? what do u mean by `num_cpus` just for resource accounting? If that is limited cpu cores, then onnxrumtime unable to get more than 1 core at all. But I didn't set it at all. (I suppose num_cpus is the physic cpus in machine_

**Comment by xwjiang2010** [comment]
num_cpus is referring to physical cores.

Nonetheless, can you print out `OMP_NUM_THREADS` to make sure it's some expected number/not 1?

**Comment by jinfagang** [comment]
@xwjiang2010 Am haven't tried will try, But I forcely setted `OM_NUM_THTRADS` in my ort inference, it's certainly should be value I set, but not work as expected.

**Comment by jiaodong** [comment]
Do you have a minimal script for us to reproduce or more context / snippets for us to better understand your workload ?

**Comment by hora-anyscale** [comment]
Per Triage Sync: @jinfagang do you have a repro script here for us to review?

**Comment by zhe-thoughts** [comment]
Marking as P2 while we wait for repro. If verified this could be a P1
