### ISSUE TITLE
[Job] Leakage of `_monitor_job` corountine hanging the dashboard 

### ISSUE THREAD

**Issue by Michaelvll** [ray-project/ray#28058]
### Background
I submitted many jobs with ray job submit and those jobs were correctly finished, but at some point, `ray job list --address=http://127.0.0.1:8265/` fails to connect to the dashboard process and hangs at python/ray/dashboard/modules/job/sdk.py::212, i.e. trying to connect with the dashboard with requests.

### Debugging
I used the following cmd to check the internal behavior of the dashboard process: `py-spy dump --locals --pid <dashboard-pid>`. It seems that there is a _monitor_job thread hanging at `await job_supervisor.ping.remote()` in `dashboard/modules/job/job_manager.py::334`, but when I checked `ps aux | grep JobSupervisor`, all the supervisor actors have already exited, which I believe should be exited by `ray.actor.exit_actor()` in `dashboard/modules/job/job_manager.py::267`.

That probably means the `await job_supervisor.ping.remote()` in `dashboard/modules/job/job_manager.py::334` failed to raise an exception after the actor `job_supervisor` exited.

### Solution
After patching the `await job_supervisor.ping.remote()` in `dashboard/modules/job/job_manager.py::334` with  `ray.get(job_supervisor.ping.remote())`, the problem goes a way.

As suggested by @rkooo567, there is a better workaround for it.
```python
ref = job_supervisor.ping.remote()
not_ready = [ref]
while not_ready:
    ready, not_ready = ray.wait(ref, timeout=0.1)
    if ready:
        ray.get(ready)
    else:
        await asyncio.sleep(0)
```

### Issue
The `await actor.func.remote()` could probably ignore the exception raised for actor exit, which can be a bug for ray Core. Please feel free to change the title of this issue.

### Versions / Dependencies

python: 3.7.12
ray: 1.13.0
OS: Debian 4.19.249 (GCP image: projects/deeplearning-platform-release/global/images/common-cpu-v20220806)

### Reproduction script

I could not reproduce it with some simple codes. The problem will happen after about 200 jobs are submitted (the jobs will be submitted and finished every 10 mins and about 20 jobs will be in RUNNING status). 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
So, the high level thing you are doing is 

Submit 20 jobs -> keep calling ray jobs list -> Submit another 20 in 10 minutes

For the workload, is it actor-based or task based? Also how many actors do you usually create?

**Comment by hora-anyscale** [comment]
Per Triage Sync: @architkulkarni what's the current status?

**Comment by architkulkarni** [comment]
@hora-anyscale We haven't been able to reproduce it.  But based on the user's investigation in the issue, it seems like the root cause is an issue in Ray Core where `await` behaves differently from `ray.get()` in terms of how it handles exceptions.

**Comment by hora-anyscale** [comment]
cc: @ericl

**Comment by scv119** [comment]
up for grab

**Comment by rkooo567** [comment]
We need a repro script for this. @architkulkarni have you seen a similar issue from the job stress tests?

**Comment by architkulkarni** [comment]
@rkooo567 No, we haven't seen this issue unfortunately.

**Comment by rkooo567** [comment]
I will wait for the repro for this
