### ISSUE TITLE
[Core] ray get the memory used in wrong method 

### ISSUE THREAD

**Issue by csaimd** [ray-project/ray#28074]
### What happened + What you expected to happen

python file: /ray/python/_private/utils.py
### def get_used_memory():
    """Return the currently used system memory in bytes
    Returns:
        The total amount of used memory
    """
    # Try to accurately figure out the memory usage if we are in a docker
    # container.
    docker_usage = None
    # For cgroups v1:
    memory_usage_filename = "/sys/fs/cgroup/memory/memory.usage_in_bytes"
    # For cgroups v2:
    memory_usage_filename_v2 = "/sys/fs/cgroup/memory.current"
    if os.path.exists(memory_usage_filename):
        with open(memory_usage_filename, "r") as f:
            docker_usage = int(f.read())
    elif os.path.exists(memory_usage_filename_v2):
        with open(memory_usage_filename_v2, "r") as f:
            docker_usage = int(f.read())

    # Use psutil if it is available.
    psutil_memory_in_bytes = psutil.virtual_memory().used

    if docker_usage is not None:
        # We take the min because the cgroup limit is very large if we aren't
        # in Docker.
        return min(docker_usage, psutil_memory_in_bytes)

    return psutil_memory_in_bytes

ray get the docker used memory through the memory.usage_in_bytes file , but this value include file cache: inactive file and active file. in activate file hould not be regarded as used memory. In k8s or docker , determine whether the container is oom through container_memory_working_set_bytes, so I think  docker_usage should be calculated as follows: memory.usage_in_bytes - memory.stat[total_inactive_file]

### Versions / Dependencies

latest version

### Reproduction script

def get_used_memory():
    """Return the currently used system memory in bytes
    Returns:
        The total amount of used memory
    """
    # Try to accurately figure out the memory usage if we are in a docker
    # container.
    docker_usage = None
    # For cgroups v1:
    memory_usage_filename = "/sys/fs/cgroup/memory/memory.usage_in_bytes"
    # For cgroups v2:
    memory_usage_filename_v2 = "/sys/fs/cgroup/memory.current"
    if os.path.exists(memory_usage_filename):
        with open(memory_usage_filename, "r") as f:
            docker_usage = int(f.read())
    elif os.path.exists(memory_usage_filename_v2):
        with open(memory_usage_filename_v2, "r") as f:
            docker_usage = int(f.read())

    # Use psutil if it is available.
    psutil_memory_in_bytes = psutil.virtual_memory().used

    if docker_usage is not None:
        # We take the min because the cgroup limit is very large if we aren't
        # in Docker.
        return min(docker_usage, psutil_memory_in_bytes)

    return psutil_memory_in_bytes

**Comment by scottsun94** [comment]
cc: @rkooo567 @rickyyx

**Comment by rkooo567** [comment]
cc @DmitriGekhtman can you take a look at the issue?

**Comment by DmitriGekhtman** [comment]
This seems quite reasonable.
@csaimd would you like to open a PR implementing the suggested change?
I'd be glad to review and make sure it's merged!

**Comment by clarng** [comment]
fyi we already fixed this for cgroup v1 docker here : https://github.com/ray-project/ray/pull/29103, @avivhaber  is looking into fixing this for cgroup v2 docker

**Comment by csaimd** [comment]
> fyi we already fixed this for cgroup v1 docker here : #29103, @avivhaber is looking into fixing this for cgroup v2 docker

can this fix merge to other verson ,such as ray-1.5.1,ray-1.12.1 or others

**Comment by csaimd** [comment]
> fyi we already fixed this for cgroup v1 docker here : #29103, @avivhaber is looking into fixing this for cgroup v2 docker

@clarng can this fix merge to other verson ,such as ray-1.5.1,ray-1.12.1 or others

**Comment by clarng** [comment]
> > fyi we already fixed this for cgroup v1 docker here : #29103, @avivhaber is looking into fixing this for cgroup v2 docker
> 
> @clarng can this fix merge to other verson ,such as ray-1.5.1,ray-1.12.1 or others

We plan to do periodic 1.13.x release, and the next one would include this fix, still need to confirm on the timeline for the next 1.13.x release

Will this work for you?

**Comment by rkooo567** [comment]
cc @zhe-thoughts for the release related question; https://github.com/ray-project/ray/issues/28074#issuecomment-1287645600

**Comment by rkooo567** [comment]
@clarng is it okay to close this issue? Did we already make a fix for cgroup2?

**Comment by clarng** [comment]
cgroup v2 is fixed here https://github.com/ray-project/ray/pull/29709

closing

**Comment by DmitriGekhtman** [comment]
thanks @avivhaber!
