### ISSUE TITLE
[Tune] Absolute paths are stored in checkpoints and Tune cannot resume if checkpoints are moved

### ISSUE THREAD

**Issue by Stefan-1313** [ray-project/ray#28082]
### What happened + What you expected to happen

@xwjiang2010

The Ray Tune 'local_dir' contains two *.json files which saves the expriment config which is used when resuming from  a checkpoint. I noticed these files also store the 'local_dir' and other locations derived from it, as absolute paths.

Unfortunately, if you move the checkpoints to another location (or the location holding the checkpoints is mounted to a different path) results in failing of a resume by Tune.

To more clearly describe what is happening:

1. I submit a experiment (and Docker image) to my cloud provider service (Azure Machine Learning).
2. Azure will start the Docker container and **mount the output storage to a path** it likes. This path is proved to me as Environment Variable and as input argument to my Python script.
3. The experiment runs fine for a few hours and **create a checkpoint every 10 minutes**.
4. Because of computation capacity limitations, **Azure stops our Docker container** because we use discounted low priority nodes.
5. When sufficient computational capacity is available again, **Azure restarts our Docker container** and **mounts the output storage to a path** it likes.
6. Recently, Azure changed something and **now the mount path is different after a restart** :frowning: . No worries, as this new path is provided to me as Environment Variable and as input argument to my Python script. **All my previously outputted files and Tune checkpoints are accessible via this path** :smile: .
7. **I give Tune my new `local_dir`, Tune finds the checkpoints** (e.g. checkpoint_001700). However, directly after I get the `FileNotFoundError: [Errno Path does not exist]` (I checked, and checkpoint_001700 does exist). Which is logical as Tune starts using the path read from the checkpoint information which is a dead end now.

### My first thoughts about a solution direction is:
It may be better for Tune to only store paths relative to the `local_dir`, so if the contents of the `local_dir` gets (virtually) moved, and you update `local_dir` accordingly, the checkpoints remain valid and usable.

You can then even share your checkpoints with another user working with you on the same code. Or download a checkpoint from your cloud provider and use it locally to do some additional testing and/or analysis.

### Versions / Dependencies

Ray 1.13.0 (I checked, this also happens in Ray 2.0.0).
Python 3.9
(Mini)conda environment.

### Reproduction script

Instructions:

1. Just start an experiment with Tune and enable checkpointing.
2. Stop the experiment somewhere when some checkpoints have been created (because of some throttling logic in the checkpointing, wait at least 10 seconds after the first checkpoint has been created, preferably a little more, before stopping your experiment).
3. Move the `local_dir`, and adjust the path to the `local_dir` in your code accordingly.
4. Restart your code, you will find that: [a] Tune finds the checkpoint (reporting the new path) and [B] that it then complains `FileNotFoundError: [Errno Path does not exist]` reporting the previous path to local_dir.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
Hi @Stefan-1313, I'm taking on getting this issue resolved! I reproduced the issue by:
1. Training and killing the run in the middle/intentionally erroring out
2. Move the experiment directory
3. Use `Tuner.restore(new_experiment_path).fit()` to resume training, which loads the TrialRunner and Trials from JSON data that has the incorrect absolute paths.

Is "I give Tune my new `local_dir`" referring to passing the new path to `Tuner.restore` like I did in my step 3? I just want to clarify how you are specifying the new local_dir. If you have a script reproducing the issue, feel free to attach a snippet!

**Comment by Stefan-1313** [comment]
Hi @justinvyu ,

Thanks for taking on this issue!

I have a reproduce script you can use. Probably you can make it much more minimal, but it is still clear and easy so it does the job.

```
from ray import tune
import time
import os, json
from ray.tune.logger import LoggerCallback


class MyTrainable(tune.Trainable):

    def setup(self, config):
        self.timestep = 0
        self.is_restored = False

    def step(self):
        time.sleep(1)
        self.timestep += 1

        # Here we use `episode_reward_mean`, but you can also report other
        # objectives such as loss or accuracy.
        return {"my_metrics": self.timestep}

    def save_checkpoint(self, checkpoint_dir):
        path = os.path.join(checkpoint_dir, "checkpoint")
        with open(path, "w") as f:
            f.write(json.dumps({"timestep": self.timestep}))
        return path

    def load_checkpoint(self, checkpoint_path):
        with open(checkpoint_path) as f:
            self.timestep = json.loads(f.read())["timestep"]


# Define a callback to print a line everytime an iteration is finished.
class TrailIterationProgressPrinterCallback(LoggerCallback):
    def log_trial_result(self, iteration: int, trial: "Trial", result: dict):
        print(f'Trial: {trial} | iteration {result["training_iteration"]:3d}')


local_dir = r"C:\Test\InitialDir"  # <= Change local_dir here
# local_dir = r"C:\Test\MovedDir"  # <= Change local_dir here

tune.run(MyTrainable,
         name="my_run",
         callbacks=[TrailIterationProgressPrinterCallback()],
         local_dir=local_dir,
         resume="AUTO",
         checkpoint_freq=1,
         keep_checkpoints_num=None,
         checkpoint_score_attr="my_metrics",
         verbose=0,
         stop={"training_iteration": 500})

```




> 1. Training and killing the run in the middle/intentionally erroring out

Yes, do this.



> 2\. Move the experiment directory from `~/ray_results` -> `~/moved` for example

Yes, initially my `local_dir` is `C:\Test\InitialDir`.
Then, I move the experiment files (the content of the `local_dir`) to: `C:\Test\MovedDir`.



> 3\. Use `Tuner.restore(new_experiment_path).fit()` to resume training, which loads the TrialRunner and Trials from JSON data that has the incorrect absolute paths.

I'm not completely sure what you mean here, I just use `tune.run()` and control the resume behavior using the `resume` keyword argument and the other checkpoint related keyword arguments.  See my reproduction script.



> Is "I give Tune my new `local_dir`" referring to passing the new path to `Tuner.restore` like I did in my step 3? I just want to clarify how you are specifying the new `local_dir`. If you have a script reproducing the issue, feel free to attach a snippet!

See also my reply on your point 2 above.

Initially my `local_dir` is `C:\Test\InitialDir`. Start training and intentionally interrupt it somewhere halfway.
Then, I move the experiment files (the content of the `local_dir`) to: `C:\Test\MovedDir`.
Finally, I change my `local_dir` variable to `C:\Test\MovedDir` (see the comment `  # <= Change local_dir here` in my reproduction script).
When I start the run, I get the following output (I only copied the relevant output for this discussion):

```
2022-09-22 20:26:13,122	INFO worker.py:1518 -- Started a local Ray instance.
2022-09-22 20:26:15,935	INFO trial_runner.py:590 -- A local experiment checkpoint was found and will be used to restore the previous experiment state.
2022-09-22 20:26:15,935	INFO trial_runner.py:727 -- Using following checkpoint to resume: C:\Test\MovedDir\my_run\experiment_state-2022-09-22_20-25-48.json
2022-09-22 20:26:15,935	WARNING trial_runner.py:732 -- Attempting to resume experiment from C:\Test\MovedDir\my_run. This will ignore any new changes to the specification.
2022-09-22 20:26:15,939	INFO tune.py:651 -- TrialRunner resumed, ignoring new add_experiment but updating trial resources.

2022-09-22 20:26:18,463	ERROR trial_runner.py:980 -- Trial MyTrainable_5beef_00000: Error processing event.
ray.exceptions.RayTaskError(ValueError): ray::MyTrainable.restore() (pid=16572, ip=127.0.0.1, repr=<main.MyTrainable object at 0x000001A87D9350A0>)
  File "python\ray\_raylet.pyx", line 662, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 666, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 613, in ray._raylet.execute_task.function_executor
  File "C:\Users\Stefan\.conda\envs\cenv39rl2\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Stefan\.conda\envs\cenv39rl2\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\Stefan\.conda\envs\cenv39rl2\lib\site-packages\ray\tune\trainable\trainable.py", line 631, in restore
    raise ValueError(
ValueError: Could not recover from checkpoint as it does not exist on local disk and was not available on cloud storage or another Ray node. Got checkpoint path: C:\Test\InitialDir\my_run\MyTrainable_5beef_00000_0_2022-09-22_20-21-23\checkpoint_000034 and IP 127.0.0.1
```

When I created this issue, I was using Ray 1.13.0. Now, I'm using Ray 2.0.0. The error message changed a little (instead of `FileNotFoundError: [Errno Path does not exist]` something else is sprinted), but the underlying mechanism leading to this error seems identical.

**Comment by justinvyu** [comment]
Thanks for the detailed reply! I was reproducing the issue using the new Tune APIs (`Tuner.restore`) introduced in 2.0, but my fix should apply to the old `tune.run` codepath as well.

Sidenote: here are some resources for migrating to new APIs if you're interested:
- [Slack post with migration guides for all Ray libraries](https://ray-distributed.slack.com/archives/CMVUQ1KMX/p1661990605290689)
- [Tune migration guide](https://docs.google.com/document/d/1o-J5UAeH4M5gGN9BwdrCt1q-nLe58mp94xsmTaW0Flc/edit#)
