### ISSUE TITLE
slurm documentation removed 

### ISSUE THREAD

**Issue by tobiasweede** [ray-project/ray#28092]
### Description

Hi,

I cannot understand why you removed the helpful documentation on slurm.

This commit "cleaned up" legacy material. But in my opinion it is still relevant:

https://github.com/ray-project/ray/commit/52f7b898659b3a211575cd397ce8967cededd4f3

### Link

https://docs.ray.io/en/latest/cluster/slurm.html

**Comment by richardliaw** [comment]
Hey @tobiasweede , thanks for pointing this out! It seems like our search bar is broken, but rest assured this material is still on the website:

https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html?highlight=slurm

Hope that helps!
