### ISSUE TITLE
[Core] Treat conda as first-class citizen

### ISSUE THREAD

**Issue by Hoeze** [ray-project/ray#28117]
### Description

Shipping ray as a pip-package in production environments is difficult as it tends to pull other pip-dependencies which destroy the environment.

Would it be possible to always require working conda-package builds for new releases?
I.e. every time you release a new ray version, it should have the corresponding conda package released together with it.

### Use case

Shipping conda environments with ray to end-users.

**Comment by trenta3** [comment]
I would also like this. Conda environments are much easier to work with than pip ones
