### ISSUE TITLE
[core/data/windows] Cleaning spilled object Error

### ISSUE THREAD

**Issue by hungbui-io** [ray-project/ray#28112]
### What happened + What you expected to happen

I am doing distributed data loading with Ray Data. However, during repartition() step, it showed a error as bellow: 
`ERROR external_storage.py:353 -- Error cleaning up spill files. You might still have remaining spilled objects inside `ray_spilled_objects` directory.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\hung.bui\\AppData\\Local\\Temp\\ray\\session_2022-08-25_23-51-44_319651_13064\\ray_spilled_objects\\745080e71b5a40469bd78216635ff051-multi-6'`

Any suggestion for fixing this error is much appreciated!

### Versions / Dependencies

Ray 2.0, Python 3.8.10, Windows 10

### Reproduction script

import ray

data_dir = 'class_6.4MRows_25Cols.csv'
pipe = ray.data.read_csv(training_data_dir)
pipe = pipe.repartition(500).window(blocks_per_window=12)

**Comment by mattip** [comment]
Does this still reproduce on the latest ray release? Could you provide a sanitized version of the data file?

**Comment by jonar-ch** [comment]
> Does this still reproduce on the latest ray release? Could you provide a sanitized version of the data file?

This issue still reproduce. Python3.9.13, Ray 2.3.1.

**Comment by anyscalesam** [comment]
Closing as it's been some months with no response. Please re-open.
