### ISSUE TITLE
No matching distribution found for ray==2.0.0

### ISSUE THREAD

**Issue by KGKallasmaa** [ray-project/ray#28120]
### What happened + What you expected to happen

I  have a requirements.txt file where I listed that I wanted to install ray version 2.0.0
When I ran  pip3 install --user -r requirements.txt then I got this error:

No matching distribution found for ray==2.0.0

### Versions / Dependencies

Currently using Python 3.10. I also tested it with python 3.9

### Reproduction script

Create a new requirements.txt file with 1 dependnandy (ray==2.0.0)
run: pip3 install --user -r requirements.txt

**Comment by amogkam** [comment]
cc @scv119 @matthewdeng 

@KGKallasmaa is this in macOS? What is your OS version?

**Comment by matthewdeng** [comment]
+1 to Amog's question. Also what happens if you just do `pip3 install --user ray==2.0.0`?

**Comment by avatards** [comment]
Same thing. I had no problem with upgrading to 2.0.0 with Python 3.9 but installation support for 3.10 seems to be broken again.
pip3 install --user ray==2.0.0
ERROR: Could not find a version that satisfies the requirement ray==2.0.0 (from versions: none)                                                                                                         ERROR: No matching distribution found for ray==2.0.0

**Comment by scv119** [comment]
@avatards are you on windows? that might be the reason it's not supported. 
otherwise you can try to see if https://pypi.org/project/ray/2.0.0/#files has the wheels you need?

**Comment by avatards** [comment]
@scv119 Yes, you are right, this could be just a windows issue. I was under the impression support for python 3.10 was universal already since 1.13 although I didn't actually try installing it. I hope windows will be supported one day so I can use python 3.10.

**Comment by hora-anyscale** [comment]
Per Triage Sync: Python 3.10 is not currently supported in Windows.

**Comment by dss010101** [comment]
getting this error trying to install ray[default] on a python:latest docker image

```root@1b2f0114dfb1:/workspaces/asvc# pip install ray[default]
ERROR: Could not find a version that satisfies the requirement ray[default] (from versions: none)
ERROR: No matching distribution found for ray[default]```

**Comment by Fmstrat** [comment]
Looks like this has less to do with Docker and more to do with the dependency selection of Ray doesn't work with Python 3.11. Had to downgrade to 3.10.

https://github.com/ray-project/ray/issues/33524
