### ISSUE TITLE
[Core] read_csv read_json can't work without a suffix

### ISSUE THREAD

**Issue by goodwanghan** [ray-project/ray#28124]
### What happened + What you expected to happen

```python
import pandas as pd
import ray.data as rd

pd.DataFrame(dict(a=[0.1,0.2],b=[2,3])).to_csv("/tmp/file", index=False)
rd.read_csv(['/tmp/file']).to_pandas()
```

This will throw exception:
```
ValueError: number sections must be larger than 0.
```

### Versions / Dependencies

ray==2.0.0

### Reproduction script

```python
import pandas as pd
import ray.data as rd

pd.DataFrame(dict(a=[0.1,0.2],b=[2,3])).to_csv("/tmp/file", index=False)
rd.read_csv(['/tmp/file']).to_pandas()
```

**Comment by richardliaw** [comment]
This seems related to https://github.com/ray-project/ray/issues/26605

**Comment by c21** [comment]
```
rd.read_csv(['/tmp/file'], partition_filter=None).to_pandas()
```

Add `partition_filter=None` will bypass the files filtering, allow you to read all files you specify as CSV files.

We should really rethink the default behavior for `read_csv` now, it has caught users here and https://github.com/ray-project/ray/issues/26605 . Maybe we should set default behavior to not doing filtering.

**Comment by goodwanghan** [comment]
Thanks, I looked deeper into this problem. Here is a solution that fits my need, if you have the same issue, then you can do something similar. I want to accept files with .csv suffix, or no suffix but not `_SUCCESS`, so I will create a custom filter:

```python
class _FileFiler(FileExtensionFilter):
    def __init__(self, file_extensions: Union[str, List[str]], exclude: Iterable[str]):
        super().__init__(file_extensions, allow_if_no_extension=True)
        self._exclude = set(exclude)

    def _is_valid(self, path: str) -> bool:
        return pathlib.Path(
            path
        ).name not in self._exclude and self._file_has_extension(path)

    def __call__(self, paths: List[str]) -> List[str]:
        return [path for path in paths if self._is_valid(path)]
```

**Comment by c21** [comment]
@goodwanghan - I believe `_SUCCESS` is created by Spark or Hadoop. I see, so you also need file exclusion filtering here (exclude all files with `_SUCCESS` here for an example).

**Comment by matthewdeng** [comment]
@goodwanghan are you still running into any issues with this, after adding in `_FileFilter`?
