### ISSUE TITLE
Overhead toooo much

### ISSUE THREAD

**Issue by jinfagang** [ray-project/ray#28138]
### What happened + What you expected to happen

Any body can see this issue??? Tooooo much overhead in ray!! https://github.com/ray-project/ray/issues/7511#issuecomment-1229114440

### Versions / Dependencies

Any body can see this issue??? Tooooo much overhead in ray!! https://github.com/ray-project/ray/issues/7511#issuecomment-1229114440

### Reproduction script

Any body can see this issue??? Tooooo much overhead in ray!! https://github.com/ray-project/ray/issues/7511#issuecomment-1229114440

**Comment by robertnishihara** [comment]
Responded here https://github.com/ray-project/ray/issues/7511#issuecomment-1229125792.
