### ISSUE TITLE
[DAG] The behavior of Ray DAG is changed by #27411

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#28147]
### What happened + What you expected to happen

This is because of this code piece:

https://github.com/ray-project/ray/blob/328e6ac2f43db235d7fa26003549032b69cfeb02/python/ray/dag/py_obj_scanner.py#L77-L87

This code prevents cloudpickle to continue serialization for any non-native python objects (native objects includes bytes, str, dict, list, tuple etc). So if we embed any DAG node inside a namedtuple/defaultdict/frozenset etc, then they would not be captured by Ray DAG and will result in error during execution.

If this is an expected behavior, we must specify it clearly in the doc. The original implementation seems to improve efficiency, but it can be done in other ways that does not affect the original behavior.

### Versions / Dependencies

current upstream

### Reproduction script

```python
from collections import namedtuple

import ray

inputs = namedtuple("tuple", ["input"])


@ray.remote
def foo():
    pass


@ray.remote
def bar(x):
    pass


if __name__ == '__main__':
    ray.get(bar.bind(inputs(input=foo.bind())).execute())
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simon-mo** [comment]
> but it can be done in other ways that does not affect the original behavior.

@suquark, any suggestion here?

**Comment by suquark** [comment]
> > but it can be done in other ways that does not affect the original behavior.
> 
> @suquark, any suggestion here?

I think we can serialize the input and separate `DAGNode` from the input upon calling `.bind()`. This is similar to how we are handling objectrefs hidden in inputs. I may be able to handle this later if this is not an urgent issue for others.

**Comment by dizhouwu** [comment]
Has this been fixed yet?
