### ISSUE TITLE
Ray serve to support many models

### ISSUE THREAD

**Issue by zhifeng-huang** [ray-project/ray#28164]
### Description

The feature is to support many models in Ray serve. It is better if Ray serve can cache some of the models, and dynamically load models. I am not sure how to do this but we have many models and we want to save the loading time of the models.

### Use case

We have many many models, in the order of thousands or even more than ten thousands. We would love to use Ray Serve to serve the models if Ray Serve can cache the popular models. We are using actors now. Whenever there is a request, we create an actor and the actor will load the model from MLFlow and do the inference and the actor will be killed after the inference. It is desired to have a caching layer to cache the popular models so we do not need to load the model every time there is a request.

**Comment by zhifeng-huang** [comment]
@edoakes this is the ticket

**Comment by zhifeng-huang** [comment]
@simon-mo any update on this?

**Comment by simon-mo** [comment]
@sihanwang41
