### ISSUE TITLE
[Core] Enhance security to match H2O

### ISSUE THREAD

**Issue by mirekphd** [ray-project/ray#28165]
### Description

Comparison of Ray's current security mechanisms with those of H2O (see [H2O security](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/security.html)) reveals several shortcomings on the Ray's side. 

I think the most important issue is that the client-server API communication (on port 10001 by default) as well as the Dashboard web console (port 8265 -> 80/443) should be password-protected (configured both with environment variables and `ray` CLI args, and not (only) with config files, which are less convenient in containerized apps). As to the inter-node comms (port 6379), it is less urgent, because the attack surface is lower (no client tools).

For example, setting credentials could work like this:
* in the CLI:
`ray.init [..] --username=myusername --password=mypassword`
* in the python client:
`ray.init([..], username="myusername" --password="mypassword")`

or using env vars:

`export RAY_API_USERNAME=myusername; export RAY_API_PASSWORD=mypassword; ray start [..]`

### Use case

In multi-tenant environments such as corporate data centers running Kubernetes and clones (such as Openshift/OKD), where Ray with its more accurate python models aims to replace the battle-tested H2O with its Java models. 

Also note that adding a reverse proxy as a workaround would not solve the problem in case of the client-server API (where no HTTP(S) proxy would work given the binary protocol used there).

**Comment by pcmoritz** [comment]
cc @jdo-anyscale for visibility -- at the moment there is very little guidance on our security model and how people can expose things like client / dashboard / serve in a secure way :)

**Comment by mirekphd** [comment]
One would think that a missing method to set API and console credentials would be a more pressing security issue... for multi-tentant environments such as corporate clusters it is a required functionality, and competing distributed compute environments, like the abovementioned H2O, ship with it bundled-in out-of-the-box (no need to run reverse proxies on top).
