### ISSUE TITLE
[Core] Document the behavior that people can use VISIBLE_CUDA_DEVICES to control the GPUs a node can use

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#28169]
### Description

See https://github.com/ray-project/ray/issues/27739

**Comment by XuehaiPan** [comment]
I think it should be `CUDA_VISIBLE_DEVICES` (rather than `VISIBLE_CUDA_DEVICES`).

**Comment by jjyao** [comment]
This is documented now.
