### ISSUE TITLE
[air] clarify when to use RLTrainer

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#28168]
### Description

write a session to clarify the following question, which is pretty common

Hey Ray Community, just want to do a quick knowledge check. Is there a preferred method for kicking off hyper perameter experiments with RLlib? For example, is using tune.run(“PPO”) or is it better to pass a trainable using the new trainer integration ray.train.rl.RLTrainer()? What are the major differences between the two approaches? Thank you!

**Comment by justinvyu** [comment]
`RLTrainer` has been removed.
