### ISSUE TITLE
[Datasets] Use angled brackets for `Dataset` representation

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28178]
### Description

Title.

**Before**: 
`Dataset(num_blocks=10, num_rows=10, schema=<class 'int'>)`

**After**: 
`<Dataset num_blocks=10 num_rows=10 schema=<class 'int'>>`

### Use case

1. **It's more Pythonic**. From https://docs.python.org/3/library/functions.html#repr:
> For many types, [repr] function makes an attempt to return a string that would yield an object with the same value when passed to [eval()](https://docs.python.org/3/library/functions.html#eval); otherwise, **the representation is a string enclosed in angle brackets** that contains the name of the type of the object together with additional information often including the name and address of the object.

2. **It's less confusing**. For example, the current representation makes it look like you specify `num_blocks` in the `Dataset` constructor.

**Comment by ericl** [comment]
IIRC, we previously discussed and decided not to do this, since it is against most of the ML/data community conventions, e.g.,

```
In [6]: torch.tensor(3)
Out[6]: tensor(3)

In [7]: np.ndarray(3)
Out[7]: array([2.5235972e-316, 4.9406565e-324, 1.3833838e-322])

In [16]: spark.range(3)
Out[16]: DataFrame[id: bigint]
```
