### ISSUE TITLE
[tune] Better locality-aware scheduling for trials to better re-use data already loaded from previous trials

### ISSUE THREAD

**Issue by heyitsmui** [ray-project/ray#28214]
### Description

For Ray Tune runs e.g. with XGBoost Ray + Tune, we see some trials taking longer than others for actors to get ready e.g.

`(trainable pid=7084, ip=10.82.166.164) 2022-08-30 22:44:13,378	INFO main.py:1005 -- Waiting until actors are ready (240 seconds passed).`
vs.
`(trainable pid=3969, ip=10.82.166.166) 2022-08-30 22:58:30,454	INFO main.py:1005 -- Waiting until actors are ready (601 seconds passed).
`

Looking at this step (https://github.com/ray-project/xgboost_ray/blob/master/xgboost_ray/main.py#L1020), we're mostly just waiting for the data loading step to complete before starting the Trial.

Since each Trial is using the same dataset to train, it would be great if we can improve the strategies of scheduling actors for subsequent trials to better re-use data that are already loaded into the object store from previous trials. 

### Use case

Improve the E2E runtime of Tune jobs by reducing the per-trial scheduling latency.

**Comment by heyitsmui** [comment]
cc @krfricke

**Comment by xwjiang2010** [comment]
@Yard1 
also @amogkam - along the lines of some the discussions that we had recently..

**Comment by matthewdeng** [comment]
@jjyao this is another use-case for locality aware scheduling, but is more complex (assigning workers to dataset blocks)

**Comment by krfricke** [comment]
@Yard1 has this been fixed by your [recent changes to xgboost-ray](https://github.com/ray-project/xgboost_ray/commit/b7c3e7db9535b408e0b5cf46f14fcd4c591875ff)?

**Comment by Yard1** [comment]
I believe it should?
