### ISSUE TITLE
update to at least pyspark 3.3

### ISSUE THREAD

**Issue by micarlise** [ray-project/ray#28239]
### What happened + What you expected to happen

Currently, pyspark is locked to 3.1.2.  And this uses a version 1 of log4j.  Moving to pyspark 3.3 will mitigate this issue.

https://issues.apache.org/jira/browse/SPARK-37814

### Versions / Dependencies

ray[tune] 1.13.0

### Reproduction script

install ray[tune] and check log4j jar version in `/usr/local/lib/python3.X/dist-packages/pyspark/jars.

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
hey @micarlise can you share more about this?

Ray doesn't depend on pyspark...

**Comment by micarlise** [comment]
Hi @richardliaw I'm working on double checking this (maybe it's a different dependency in our requirements file).

Why is pyspark in python/requirements.txt: https://github.com/ray-project/ray/commit/1bb2b1fc49b2ad5efc2aeb3b7ea8a7db8ff6782b

**Comment by micarlise** [comment]
Closing this bug.  Doing:

```bash
python3 -m venv env
source env/bin/activate
pip install ray[tune]
```

no pyspark in site-packages. Sorry for the mistake issue.

**Comment by richardliaw** [comment]
No problem! For reference, requirements.txt is for us to test other optional integrations in our CI. Sorry for the confusion -- let us know if we can be helpful in any other way.

**Comment by micarlise** [comment]
@richardliaw that makes sense.  It was a red herring on our part, we had a container that scanned to log4j, and just did find pyspark and that req file came up.  I should have looked closer before putting up an issue.  Appreciate the turn around on this (we can continue to use rays!) 😄
