### ISSUE TITLE
[RLlib] first example in RLlib - Key Concepts #Algorithms doesn't work

### ISSUE THREAD

**Issue by RaymondKoopmanschap** [ray-project/ray#28237]
### Description

In https://docs.ray.io/en/master/rllib/core-concepts.html under the heading Algorithms and selecting 'RLlib algorithms and Tune' there is this example:
```
from ray import tune

# Configure.
from ray.rllib.algorithms import PPOConfig
config = PPOConfig().environment("CartPole-v0").training(train_batch_size=4000)

# Train via Ray Tune.
# Note that Ray Tune does not yet support AlgorithmConfig objects, hence
# we need to convert back to old-style config dicts.
tune.run("PPO", config=config.to_dict())
```
Which doesn't work for several reasons. 
It gives an import error: `ImportError: cannot import name 'PPOConfig' from 'ray.rllib.algorithms'`
When fixing this by replacing 
`from ray.rllib.algorithms import PPOConfig` with `from ray.rllib.algorithms.ppo import PPOConfig` I get the following error
`TypeError: environment() takes 1 positional argument but 2 were given`. This can be solved by using environment(env="CartPole-v0")

Also note that the `Basic RLlib algorithms` also doesn't work due to a similar reason.

### Link

https://docs.ray.io/en/master/rllib/core-concepts.html#algorithms

**Comment by Matkicail** [comment]
Yeah, I had the exact same issue trying it out today

**Comment by RaymondKoopmanschap** [comment]
I noticed this is fixed now.
