### ISSUE TITLE
[Ray Tune] Add a flag to output progress info to log file instead of standard out.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#28268]
### Description

![image](https://user-images.githubusercontent.com/19473861/188177548-be51150f-176d-4a4d-b124-93855bd45c53.png)

We found too many progress info in `driver.out` file which causes out of disk. While we do the training for a long time, driver.out has too many out of date progress info, which cannot be rotated and archived due to we use `print(progress_str)` instead of logging.

I'd like to add a flag to tell trails whether we should use log instead of print.

**Comment by jovany-wang** [comment]
I'm not sure who is the best one to take a look at this. so please @gjoliver and @rkooo567 to triage it.

**Comment by matthewdeng** [comment]
Hey @jovany-wang would reducing the frequency of reporting help? If so you may want to look at configuring the [ProgressReporter](https://docs.ray.io/en/master/tune/api_docs/reporters.html#tune-reporter-doc) to print less frequently and/or with less verbosity.

cc @xwjiang2010 on  the possibility of reusing the existing `log_to_file` or adding similar logic for overall progress reporting.

**Comment by jovany-wang** [comment]
@matthewdeng  @xwjiang2010 Could we prioritize it?  We have been suffering from it in Ray-1.4. And I found it's still not fixed in latest version.

**Comment by gjoliver** [comment]
@xwjiang2010 @krfricke 
let's standardize on whether we should logger.log() or print() these outputs everywhere.
also, for convenience, it may be awesome if we can turn a flag on to write to both places when needed.

**Comment by xwjiang2010** [comment]
@jovany-wang Can you say more about what is the issue?

Are you bothered by the amount of progress information or the fact that it cannot be easily rotated? Put it another way, do you prefer less information per progress_str, less frequency or just a way to archive older and less relevant progress_str (to avoid running out of space)?

Also can you say more about how changing to `logger.log()` can solve the issue? Is logrotation something managed natively by Python's logging module through some setup?

**Comment by jovany-wang** [comment]
> it cannot be easily rotated. 

This is the root cause I believe.

Firstly we should get a consensus on the point, that `printing to driver.out` is hard to rotate but the rotation of logger is already configured.
In Ant production environment, rotated files could be archived automatically.(I believe most of the production environments has the capability).

> Is logrotation something managed natively by Python's logging module through some setup?

YES. I'm not sure if we setup it in OSS Ray, but at least we did setup it in Ant internal.

Finally anyway, I believe in engineeing practice, outputting massive messages should be in logger instead of print. For backward compatibility, I propose that we add a flag which could be disabled by default.

**Comment by rkooo567** [comment]
+1 on using logger. Imo we should avoid using print and give more power to users for logging capability. Are we planning to handle this btw? @xwjiang2010. Maybe we can get help from them?

**Comment by xwjiang2010** [comment]
I am trying to understand what this request entails. Is the issue mainly with how ProgressReporter is implemented? mostly redirect `print_result` to a python logger?
@rkooo567 do you have pointers to how other libraries are doing it? e.g. ray serve etc

**Comment by rkooo567** [comment]
My understanding is that we should redirect these outputs to the logger, not a print so that users can have control over logs printed from the library @jovany-wang please comment if this makes sense (e.g., they can filter out some logs or change the severity threshold). @jovany-wang  Also, can you answer this question?

> Hey @jovany-wang would reducing the frequency of reporting help? If so you may want to look at configuring the [ProgressReporter](https://docs.ray.io/en/master/tune/api_docs/reporters.html#tune-reporter-doc) to print less frequently and/or with less verbosity.

For the serve, I'd like to ask @simon-mo @gjoliver (rllib) to understand how we are doing this in other libraries.

**Comment by simon-mo** [comment]
Serve encourages user to use the logger configured by Serve which redirects to file.

**Comment by jovany-wang** [comment]
@rkooo567 A custom ProgressReporter could address it. But even if it works, I still think it's too heavy. A clearer flag would be great to use for users who are using it for real world instead of research purpose.

**Comment by ericl** [comment]
It sounds like we should try to follow Serve's convention here for the output? Tune can probably configure the default logger to emulate the existing print behavior.

**Comment by xwjiang2010** [comment]
Update: still investigating this.
So for Tune logging, there is driver log, which I think we can configure it through a proper stream handler. There is also remote actor logs. Especially for TF case, this part of the output can be extremely cluttered. See example below

```
4/59 [=>............................] - ETA: 3s - loss: 2.3292 - accuracy: 0.1011
 5/59 [=>............................] - ETA: 3s - loss: 2.3308 - accuracy: 0.1012
[2m[36m(RayTrainWorker pid=245, ip=172.31.68.93)[0m 
 6/59 [==>...........................] - ETA: 3s - loss: 2.3281 - accuracy: 0.1030
[2m[36m(RayTrainWorker pid=243, ip=172.31.70.157)[0m 
 6/59 [==>...........................] - ETA: 3s - loss: 2.3281 - accuracy: 0.1030
[2m[36m(RayTrainWorker pid=244, ip=172.31.68.93)[0m 
 6/59 [==>...........................] - ETA: 3s - loss: 2.3281 - accuracy: 0.1030
[2m[36m(RayTrainWorker pid=244, ip=172.31.70.157)[0m 
 6/59 [==>...........................] - ETA: 3s - loss: 2.3281 - accuracy: 0.1030
[2m[36m(RayTrainWorker pid=243, ip=172.31.68.93)[0m 
 6/59 [==>...........................] - ETA: 3s - loss: 2.3281 - accuracy: 0.1030
[2m[36m(RayTrainWorker pid=246, ip=172.31.70.157)[0m 
```

I don't have a good answer for the remote actor part of the story. What do people feel here? Are people happy with just the tune driver log saved though python logging module? For remote actor log, one may have to dig through [worker-[worker_id]-[job_id]-[pid].[out|err]](https://docs.ray.io/en/latest/ray-observability/ray-logging.html#id1), which is offered as part of Core remote actor log, which automatically enables log rotation.

**Comment by xwjiang2010** [comment]
IIUC python logging module hardly works across multiple processes, let along processes on different nodes. So there has to be a mix of some customized approach to handle remote actor case.

**Comment by jovany-wang** [comment]
> IIUC python logging module hardly works across multiple processes, let along processes on different nodes. So there has to be a mix of some customized approach to handle remote actor case.

What's the case we should handle the logs for different processes?

**Comment by rkooo567** [comment]
> one may have to dig through [worker-[worker_id]-[job_id]-[pid].[out|err]](https://docs.ray.io/en/latest/ray-observability/ray-logging.html#id1), which is offered as part of Core remote actor log, which automatically enables log rotation.

Yeah I don't need to control this except the formatting and log level (no need to add additional handler). 

For the cluttered output, can you create a separate issue? Not sure if it is fixable, but we can take a look

**Comment by jovany-wang** [comment]
@xwjiang2010 @matthewdeng Any progress or we should close this ?
