### ISSUE TITLE
[Core] chaos_dask_on_ray_large_scale_test_no_spilling hanged without any error message.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#28272]
### What happened + What you expected to happen

https://console.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_izVRnU4vQZrkg6S7gyChRTtU?command-history-section=command_history

Looks like the script hangs for a long time and was killed without any explicit error or hints. 

### Versions / Dependencies

master

### Reproduction script

Run the test

**Comment by rkooo567** [comment]
cc @jjyao can you help finding the person to investigate this?

**Comment by stephanie-wang** [comment]
Downgrading since it is not currently failing consistently.

**Comment by richardliaw** [comment]
closing - we should reopen a new issue when we see failures again.
