### ISSUE TITLE
ray.wait causes silent crashes on actors

### ISSUE THREAD

**Issue by EricSteinberger** [ray-project/ray#28296]
### Description

Hi, long-term ray user here -- great work with the framework!

We find that ray.wait causes silent crashes. See minimal repro below

```
import ray
@ray.remote(num_cpus=1)
class A:
    def __init__(self):
        pass

    def blah(self):
        raise NotImplementedError

if __name__ == '__main__':
    ray.init(address="auto", log_to_driver=True)
    a = A.remote()

    ### Crashes as expected
    ray.get([
            a.blah.remote()
        ])


    ### Silently fails
    ray.wait([
            a.blah.remote()
        ])
```

Thank you!

### Use case

I think this is applicable broadly. For large-scale ML workloads, it's desirable to know when an actor method failed and how. We can of course substitute with ray.get but this will lead to silent errors -- very bad.

**Comment by rkooo567** [comment]
I think it is an expected behavior. You are expected to run ray.get on the result of ray.wait

```
objs = ray.wait([
            a.blah.remote()
        ])
ray.get(objs)
```

And if the returned ref is not handled, we print the error message to the driver (it's called unhandled exception).

**Comment by scottsun94** [comment]
@EricSteinberger Does @rkooo567 's answer address your issue?

**Comment by rkooo567** [comment]
Close since it is working as expected
