### ISSUE TITLE
ray builds need to clean up /tmp after building

### ISSUE THREAD

**Issue by shaneknapp** [ray-project/ray#283]
on the new/staging jenkins worker, the ray builds are leaving over 1k files in /tmp:

sknapp@amp-jenkins-staging-worker-02:/tmp$ ls -l scheduler* plasma_* | wc -l
1302

please ensure that this stuff gets cleaned up once builds are done.

thanks!

**Comment by robertnishihara** [comment]
Thanks for bringing this up. As a temporary fix, I added `rm /tmp/plasma* /tmp/scheduler*` to the end of the Jenkins build script.

**Comment by shaneknapp** [comment]
this makes me nervous, as you could potentially clobber other files created
in /tmp by other projects...  is there a cleanup method you can call
instead?

On Wed, Feb 15, 2017 at 12:59 PM, Robert Nishihara <notifications@github.com

**Comment by robertnishihara** [comment]
Good point, let me give this some more thought. I'd prefer to just not generate the files in the first place, which might be possible. Failing that, we can prefix the file names with a more unique string, although that isn't completely satisfying.

**Comment by robertnishihara** [comment]
We are now also dumping additional log files to `/tmp/raylogs/`, which needs to be cleaned up as well.

**Comment by robertnishihara** [comment]
Note that for continuous integration with Jenkins, we can put the cleanup in the Jenkins script.

In the general case, it seems ok to me to leave files in `/tmp`, since the files are not large.

Closing for now, please reopen if we should revisit this or if we should come up with a better solution.

**Comment by shaneknapp** [comment]
sgtm.
