### ISSUE TITLE
"ray stop" should not kill so much stuff.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2830]
For example, `ray stop` shouldn't kill all of the running jupyter notebooks and things like that (that weren't started by Ray).

**Comment by richardliaw** [comment]
RE: Jupyter, I thought it was scoped correctly to the notebooks that Ray starts: 

https://github.com/ray-project/ray/blob/4c0e2c3f58f18cccf44c7b3c69474302ecfa44e5/python/ray/scripts/scripts.py#L386-L396

**Comment by jey** [comment]
@richardliaw, I agree that the way jupyter is handled is the least offensive one, but the right way to do this would probably be to:

1. Record PIDs when launching children then use these recorded PIDs to send appropriate signals at shutdown.
2. Have children monitor their parent and exit when parent dies. For example, pass a pipe to the forked child process and use `select()` to notice when the pipe gets closed, indicating that the parent process exited.

**Comment by robertnishihara** [comment]
@richardliaw I see it looks like you're right. I guess the main one that could be problematic is the redis servers (and in rare cases any unfortunately named processes).

**Comment by jey** [comment]
Would it make sense to create new a process group for ray via `setpgid(0, 0)`? Could then `kill(-pgid, SIGQUIT)` or something.

**Comment by robertnishihara** [comment]
@jey Hmm, that seems like a good solution. I can't think of any obvious drawbacks..

**Comment by ericl** [comment]
Fixed.
