### ISSUE TITLE
[CI] `linux://python/ray/tests:test_cancel` is failing/flaky on master.

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28305]
- ea6d53dbf35a56bb87ecdfa2cc23bc9518a05f15 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9723#018311de-b925-4f11-b74f-4149fa23f978)
- 10e9422f8fe91c150083be24c4113c7f784cd487 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9721#01830fac-9902-42cf-adc8-298829948761)
- 10e9422f8fe91c150083be24c4113c7f784cd487 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9721#01830fac-9917-4338-b7a8-25b21bbdbf67)
- ce70b8b96ea21581a33475c4a405f1c5d99deaf5 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9719#01830311-d964-4a31-afe6-40210685af05)
- 8c0b0272cee095d3bd8f8c891d71e6a612539856 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9715#01830012-e733-4d58-b4ca-f90b471c3e64)
- 59be31d5583a3302e000feeba925e3eed1850eb2 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9714#0182ffc3-91ff-4a66-9410-3435f975a0cd)
- 57484b28cf2345f6f17d75928bfdbc097a4ce61d FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9711#0182ff18-5729-431d-af79-1de821dc29df)
- 57484b28cf2345f6f17d75928bfdbc097a4ce61d FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9711#0182ff18-5713-48eb-9508-141f5703b5fa)
- 5d31f2d4bc10b38a1c15a0c9282daace92c3cefd FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9710#0182ff17-e3c7-4805-b149-175d30bfb7de)
- 5779ee764db18f3bb3fa6d60540b3ad9f8f776bb FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9709#0182fef0-29df-4388-bd4a-7f3069f177da)
- 3590a86db0369ce8a8f9c3965cddc9e4c817c2b8 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9707#0182fe2b-f009-4a84-ae20-1d426e1d38b8)
- 8692eb620878cfe214fb670df5d4c1bf83ab6a51 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9704#0182fdaa-3001-4d32-b258-f6a7528c40d5)
- 48898aa03d2cab63dc8ba9a1dd6cb72397cc377d FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/ray-builders-branch/builds/9694#0182fa2f-6d4f-487c-bcd0-48bcc01f2555)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_cancel-END
....

Looks like it's failing after the memory monitor was turned on?

**Comment by stephanie-wang** [comment]
@clarng, could you look into this?

**Comment by clarng** [comment]
```


shutdown_only = None, use_force = True
--
  |  
  | @pytest.mark.parametrize("use_force", [True, False])
  | def test_recursive_cancel(shutdown_only, use_force):
  | ray.init(num_cpus=4)
  |  
  | @ray.remote(num_cpus=1)
  | def inner():
  | while True:
  | time.sleep(0.1)
  |  
  | @ray.remote(num_cpus=1)
  | def outer():
  |  
  | x = [inner.remote()]
  | print(x)
  | while True:
  | time.sleep(0.1)
  |  
  | @ray.remote(num_cpus=4)
  | def many_resources():
  | return 300
  |  
  | outer_fut = outer.remote()
  | many_fut = many_resources.remote()
  | with pytest.raises(GetTimeoutError):
  | >           ray.get(many_fut, timeout=1)
  | E           Failed: DID NOT RAISE <class 'ray.exceptions.GetTimeoutError'>


```

**Comment by clarng** [comment]
ran this locally on linux and could not reproduce the flakiness, checking the code and ci

**Comment by clarng** [comment]
Seems the threading fix also removed the flakiness

<img width="790" alt="Screen Shot 2022-09-07 at 10 09 35 AM" src="https://user-images.githubusercontent.com/22830327/188938995-e4fcb80a-daa4-4c61-a9de-862787111b16.png">

**Comment by stephanie-wang** [comment]
Great!
