### ISSUE TITLE
[AIR] TF-IDF preprocessor

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#28302]
### Description

TF-IDF is commonly used in NLP and has other uses. An AIR preprocessor would be useful. See https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html?highlight=tf+idf#sklearn.feature_extraction.text.TfidfTransformer

**Comment by matthewdeng** [comment]
Priority should be increased if there are more user requests.
