### ISSUE TITLE
[Serve] `serve run` doesn't update `host` and `port`

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#28312]
### What happened + What you expected to happen

Two users on the Ray Slack ([user 1](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1662014917984469), [user 2](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1662476823430989)) reported that `serve run` fails to set `host` and `port`.

`serve run` should set `host` and `port` successfully on a fresh Ray cluster.

### Versions / Dependencies

Unsure

### Reproduction script

For example, the second user's [graph](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1662489353168639?thread_ts=1662476823.430989&cid=CNCKBBRJL) was:

```python
from ray import serve
from ray.serve.drivers import DAGDriver
from ray.serve.deployment_graph import InputNode
from ray.dag.vis_utils import _dag_to_dot
from starlette.requests import Request
​
​
@serve.deployment
def unpack_request(http_request: Request) -> tuple[str, str]:
    return http_request.query_params.get("first_name"), http_request.query_params.get("last_name")
​
​
@serve.deployment
def capitalize(name: tuple[str, str], index: int) -> str:
    return name[index].capitalize()
​
​
@serve.deployment
def create_full_name(first_name: str, last_name: str):
    return " ".join((first_name, last_name))
​
​
with InputNode() as input:
    name = unpack_request.bind(input)
    first_name_cap = capitalize.bind(name, index=0)
    last_name_cap = capitalize.bind(name, index=1)
    full_name = create_full_name.bind(first_name_cap, last_name_cap)
​
graph = DAGDriver.bind(full_name)
​
# Visualize the graph
graph_as_dot = _dag_to_dot(graph)
print(graph_as_dot.to_string())
```

When they ran

`serve run "--address=ray://<my_ip>:10001" --host="0.0.0.0" --port=8080 ray_serve_example:graph`

they got:

```
The new client HTTP config differs from the existing one in the following fields: ['host', 'port']. The new HTTP config is ignored.
```

**Comment by erilju719** [comment]
**Versions/ Dependencies:**
Local machine: Windows 10, Python 3.9.13, ray==2.0.0
Remote machine: Ubuntu 18, Python 3.9.13, ray==2.0.0

**Comment by shrekris-anyscale** [comment]
I think I've figured out the root cause and a potential (temporary) workaround.

**Cause**

In Ray 2.0, the [`serve run` command starts Serve](https://github.com/ray-project/ray/blob/releases/2.0.0/python/ray/serve/scripts.py#L300) without passing in any user-configured `host` and `port` options.

#27026 updates `serve run`, so [it does pass in the `host` and `port`](https://github.com/ray-project/ray/pull/27026/files#diff-309b33091c76269e3d557d272f26e8cb5a9cda6fb4e0917bc05dc65d2c780ddbL300-R308), but unfortunately this PR wasn't included in the 2.0 release.

**(Temporary) Workaround**

**#27026 should be included in the next Ray release. You can use the [Ray nightly](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies) if you want to test your app using `serve run` and `host`/`port`.** `serve run` should work as expected with the nightly, but the nightly is not a suitable version to deploy to production with.

If you prefer, you can temporarily simulate `serve run`'s behavior through the Python API.

At the top of your script (after the imports), add these three lines:

```python
import ray
ray.init(address="ray://<my_ip>:10001", namespace="serve").  # Connects to remote cluster
serve.shutdown()  # Shuts down any running Serve app on the remote cluster
```

Then, at the end of your script (after storing the Serve app in a variable), use `serve.run()` and a blocking `while` loop to start the app:

```python
graph = DAGDriver.bind(...)
serve.run(graph, host="your_host", port=your_port)  # Launch the graph on the remote cluster

# Block until this script is killed manually with ctrl-c
import time
while True:
    time.sleep(10)
```

You can then run the app with

```console
python file_name.py
```

just like `serve run file_name:graph`.

**Example**

As an example, here's what the repro file would look like with the proposed workaround:

```python
from ray import serve
from ray.serve.drivers import DAGDriver
from ray.serve.deployment_graph import InputNode
from ray.dag.vis_utils import _dag_to_dot
from starlette.requests import Request
​

import ray
ray.init(address="ray://<my_ip>:10001", namespace="serve").  # Connects to remote cluster
serve.shutdown()  # Shuts down any running Serve app on the remote cluster
​
@serve.deployment
def unpack_request(http_request: Request) -> tuple[str, str]:
    return http_request.query_params.get("first_name"), http_request.query_params.get("last_name")
​
​
@serve.deployment
def capitalize(name: tuple[str, str], index: int) -> str:
    return name[index].capitalize()
​
​
@serve.deployment
def create_full_name(first_name: str, last_name: str):
    return " ".join((first_name, last_name))
​
​
with InputNode() as input:
    name = unpack_request.bind(input)
    first_name_cap = capitalize.bind(name, index=0)
    last_name_cap = capitalize.bind(name, index=1)
    full_name = create_full_name.bind(first_name_cap, last_name_cap)
​
graph = DAGDriver.bind(full_name)
​
# Visualize the graph
graph_as_dot = _dag_to_dot(graph)
print(graph_as_dot.to_string())

serve.run(graph, host="your_host", port=your_port)  # Launch the graph on the remote cluster

# Block until this script is killed manually with ctrl-c
import time
while True:
    time.sleep(10)
```

**Comment by erilju719** [comment]
Thanks a lot @shrekris-anyscale, it works as expected with the latest Ray nightly build! Feel free to close this issue now that I know it will be fixed in the next Ray release. How often do you release, BTW?

**Comment by shrekris-anyscale** [comment]
Great to hear it's working as expected @erilju719! We're still finalizing the upcoming Ray release timelines, but [in the past](https://pypi.org/project/ray/#history) we've released new minor versions every 1-2 months.
