### ISSUE TITLE
[Core] start DefaultWorker failed when args contains space

### ISSUE THREAD

**Issue by tomsunelite** [ray-project/ray#28331]
### What happened + What you expected to happen

 bug:
python setup_worker.py -Dray.job.code-search-path=/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar io.ray.runtime.runner.worker.DefaultWorker --language=JAVA

Error: Could not find or load main class IDEA

### Versions / Dependencies

ray version: 2.0.0
os: mac

### Reproduction script

python setup_worker.py -Dray.job.code-search-path=/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar io.ray.runtime.runner.worker.DefaultWorker --language=JAVA

**Comment by tomsunelite** [comment]
the original reason is that Ray starts DefaultWorker by bash in 2.0.0:
```code
            os.execvp("bash", args=["bash", "-c", command_str])
```
the above code is from https://github.com/ray-project/ray/blob/ray-2.0.0/python/ray/_private/runtime_env/context.py,
and the "command_str" may contain space character(s), and the space character is special character in bash, so we can fix it by the following change:

```bash
diff --git a/python/ray/_private/runtime_env/context.py b/python/ray/_private/runtime_env/context.py
index 8b2b9117f..95b4988f3 100644
--- a/python/ray/_private/runtime_env/context.py
+++ b/python/ray/_private/runtime_env/context.py
@@ -66,6 +66,7 @@ class RuntimeEnvContext:
         else:
             executable = "exec "
 
+        passthrough_args = [s.replace(" ", "\ ") for s in passthrough_args]
         exec_command = " ".join([f"{executable}"] + passthrough_args)
         command_str = " && ".join(self.command_prefix + [exec_command])
         # TODO(SongGuyang): We add this env to command for macOS because it doesn't
```

**Comment by jovany-wang** [comment]
Yes, good catch. Could you create a PR to fix it?

**Comment by tomsunelite** [comment]
> Yes, good catch. Could you create a PR to fix it?

sure, will do it later
