### ISSUE TITLE
[doc] Hard to install doc requirements on Mac M1

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#28356]
### What happened + What you expected to happen

I use **conda** to manage my environment. **conda** does not support Python-3.7 on M1 as shown in the following two links. However, the document dependencies require Python >= 3.5 and < 3.8.

- https://docs.conda.io/en/latest/miniconda.html
- https://repo.anaconda.com/pkgs/main/osx-arm64

```bash
cd doc
pip install -r requirements-doc.txt

# ERROR: Ignored the following versions that require a different python version: 0.0.12 Requires-Python >=3.5, <3.8
# ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
# ERROR: No matching distribution found for tensorflow
```

* Figure: Try to install Python-3.7 with **conda** on M1.
<img width="794" alt="Screen Shot 2022-09-07 at 2 37 49 PM" src="https://user-images.githubusercontent.com/20109646/188986973-02bd2bd8-1619-4d7a-b085-6286ce992659.png">

### Versions / Dependencies

* conda 4.14.0
* Python 3.8.13
* Mac M1

### Reproduction script

```
cd doc
pip install -r requirements-doc.txt
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by kevin85421** [comment]
cc @DmitriGekhtman @maxpumperla

**Comment by matthewdeng** [comment]
Oh does this work if you apply the following change? https://github.com/ray-project/ray/pull/28212

**Comment by kevin85421** [comment]
@matthewdeng Thank you! It works. 

Matthew's solution enables me to use `pip` to install tensorflow with the same Python version. However, I still cannot install `lightgbm` successfully. When I tried to comment out all dependencies in "Ray libraries", I can build the documents.

**Comment by matthewdeng** [comment]
Hm @richardliaw do we actually even need to install `xgboost-ray`/`lightgbm-ray` now that the direct references have been removed?

**Comment by richardliaw** [comment]
Not sure, let's try it out.

**Comment by matthewdeng** [comment]
I guess it doesn't work... https://buildkite.com/ray-project/ray-builders-pr/builds/44057#01831fc5-a4bf-427c-a47b-e973e93f5db8

@kevin85421 can you share what are the errors you're running into with `lightgbm`? Thanks!

**Comment by mattip** [comment]
What are the steps to reproduce the document build on M1, starting from `conda create` ?

**Comment by kevin85421** [comment]
I rebased the current master branch, and I could build the document on my M1 with Python 3.8.13 now. Honestly, I am not sure what happened. Thank @mattip and @matthewdeng for the follow-up. Feel free to close this issue.

**Comment by mattip** [comment]
Ok, thanks for getting back. Closing.
