### ISSUE TITLE
[CI] CI improvements for OSS

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#28359]
### What happened + What you expected to happen

 Unit tests lifecycle? Run more than 1 time in the master for every test
 CI: treat timeout as failure
 We need to check and monitor worker startup time

### Versions / Dependencies

latest ray

### Reproduction script

n/a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by aslonnie** [comment]
> Unit tests lifecycle? Run more than 1 time in the master for every test
not sure what this means.

> CI: treat timeout as failure
this is already the case?

> We need to check and monitor worker startup time
this seems like a separate issue for core team.

It is unclear what the issue is or what is actionable, either now or in the future. I am closing this.
