### ISSUE TITLE
[air] [ckpt] checkpoint of a single file

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#28352]
### What happened + What you expected to happen

Currently we have various forms for checkpoint: dir, uri, object_ref and dict

One missing piece is single file case. One naive way to go about it is to ask one to always provide its parent folder. The obvious downside is that this is inefficient when the folder contains a million other contents and all these contents will be serialized unnecessarily. 

e.g. my_model.h5 file

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
As a short-term workaround, can the user just make a temporary dir and save the file in it?

**Comment by krfricke** [comment]
We won't be supporting this (yet another checkpoint mode) - instead we'll probably double down on directories. For single files, we will have to create a separate directory.
