### ISSUE TITLE
[Core] a compile error about class xx has no member named 'msgpack_pack' when passing an object as parameter

### ISSUE THREAD

**Issue by madappie** [ray-project/ray#28366]
I am using ray cpp, and passing parameters like follows:
1. auto state = master.Task(&Master::init).Remote(g, wl).Get();
2. 
3. bool Master::init(ConstraintGraph& g, WorkList& initialWorklist) {
4.     std::cout<<"this is initializing master!" <<std::endl;
5.     return true;
6. }

The compiler reports the following errors, any one has ideas how to resolve it? 
   python3.7/site-packages/ray/cpp/include/msgpack/v1/object.hpp:631:11: error: ‘const class SVF::ConstraintGraph’ has no member named ‘msgpack_pack’

**Comment by SongGuyang** [comment]
Currently, the remote function arguments should be able to be serialized by MessagePack. Can you add the macro `MSGPACK_DEFINE` to your  user-defined class ConstraintGraph following the doc https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_packer#packing-classes?
