### ISSUE TITLE
[rllib] How to implement RL^2 architecture 

### ISSUE THREAD

**Issue by whikwon** [ray-project/ray#2836]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.0
- **Python version**: 3.6.1
- **Exact command to reproduce**:

### Describe the problem

I'm looking into the paper RL^2: Fast Reinforcement Learning via slow reinforcement learning, Yan Duan et al. https://arxiv.org/pdf/1611.02779.pdf

In this paper, each agent(trial) pass hidden state to next time step and when episode ends, last hidden states being passed to new episode's start state. 

As I know, Ray framework re-initialize the hidden state for every episodes in each agents and I want to implement the RL^2 above. 

For implementation, which scripts should I have to modify?

**Comment by ericl** [comment]
Do you actually have to modify the framework? It seems like all the changes can be handled in the environment only.

**Comment by whikwon** [comment]
@ericl Could you give me some ideas please? I have no idea how to handle in the environment.

**Comment by ericl** [comment]
It seems to me an trial just maps to multiple episodes, so maybe you can make an env that has multiple episodes per "episode"?

**Comment by 51616** [comment]
Follow up question about RL^2, from this figure in the paper, it seems like when the environment is reset the agent only takes new observation s0 w/o prev action and reward (i guess it uses placeholder for prev action and reward instead) to produce h4 compared to h3 where it uses s3, a2, r2 and d2 as inputs and not output any action in the environment. 

So my questions are
1. How can I produce h3 w/o output any actions to the environment or always use a placeholder action at the end of a logical episode (e.g., where can I somehow edit the flow of the rnn hidden state computation + action output)
2. How can I produce h4 with a placeholder for prev action and reward (what I'm doing now is uses SampleBatch.PREV_ACTIONS and PREV_REWARDS keys to access them). So I guess if I can edit the action output to output placeholder action, I can use my code as is but only changing the  flow of the rnn hidden state computation + action output?


![image](https://user-images.githubusercontent.com/20886355/90015431-cdaaff00-dcd2-11ea-8549-9399ba8b762d.png)
