### ISSUE TITLE
[rllib] ARS nan value in `EvalEpRewMean`

### ISSUE THREAD

**Issue by whikwon** [ray-project/ray#2839]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.2
- **Python version**: 3.6.1
- **Exact command to reproduce**:

### Describe the problem

I ran the `Pendulum-v0` using ARS algorithm (I didn't use tune for it.)
I could find that all the `Eval...` values are nans and other values exists. 

Is it normal or am I getting problem?

### Source code / logs

```python
agent = ars.ARSAgent(env="Pendulum-v0", config={
    "num_workers": 7, # 72 * 3 + 5
    "observation_filter": "MeanStdFilter",
    "sample_batch_size": 128,
    "batch_mode": "complete_episodes"
})
```

**Comment by whikwon** [comment]
And one more thing, I am not able to train `Pendulum-v0` using ARS, Loss doesn't decrease. Could you check that?

**Comment by eugenevinitsky** [comment]
Yes, I will look into this this evening.

**Comment by eugenevinitsky** [comment]
@whikwon technically this is normal; to save on run-time we have a config parameter called eval_prob that sets the probability of any rollout being used to actually evaluate the reward of the unperturbed policy weights. If you run it for long enough you will see a non NaN value, or you can increase eval_prob or increase the number of "deltas_used" in the config.

**Comment by eugenevinitsky** [comment]
@ericl this is also the behavior of ES. It does seem to be confusing to users, we could switch both so that there's always an evaluation rollout at the end of a set of perturbation rollouts.

**Comment by whikwon** [comment]
@eugenevinitsky Thank you. I think ARS doesn't train `Pendulum-v0`. I've ran it more than 3 hours with 8 cpus but can not find loss decrease. Could you check?

**Comment by eugenevinitsky** [comment]
Hi @whikwon could you post your config? I'll try and find a working config for you.

**Comment by ericl** [comment]
I see, probably the right thing is to eventually switch these to report the
mean of the last 100 rewards. Right now this is a bit hard since ES and ARS
are separated from the gradients based algorithms.

**Comment by whikwon** [comment]
@eugenevinitsky "even if you have num_workers set to 7, you're only getting 4 rollouts per iteration." means I can not increase the rollout speed even if I get more workers? 

How can I deal with it? 
(Configs are same as above)

**Comment by whikwon** [comment]
Should I have to set parameters num_deltas, deltas_used equal values of num_cpus * 4?

**Comment by eugenevinitsky** [comment]
Hi @whikwon, this is an issue of poor naming. num_deltas is the number of rollouts. You can set it to whatever number you want and increasing them should lead to convergence for more algorithms. Deltas_used is a parameter specific to the ARS algorithm; deltas_used is the number of rollouts that will actually go into the gradient. The number of rollouts is ranked by reward and only the top deltas_used number of rollouts are used.

**Comment by whikwon** [comment]
@eugenevinitsky I got it. Thank you so much.
