### ISSUE TITLE
Ray.tune.impl.tuner_internal.py 

### ISSUE THREAD

**Issue by ChVo24** [ray-project/ray#28402]
### What happened + What you expected to happen

Restoring the Tuner Trials on Windows yields FileExistsError. Solution would be in _restore_from_path_or_uri():

Adding in file tuner_internal.py, in function _restore_from_path_or_uri after line 217 within the loop:
                if os.path.isfile(new_exp_path / file_dir.name):
                    os.remove(new_exp_path / file_dir.name)

### Versions / Dependencies

OS: Windows 10
Python: 3.8
Ray: 2.0.0

### Reproduction script

Solution is already available in Bug description. This is an OS dependent error caused by rename(), because it works different on OS's.

**Comment by krfricke** [comment]
I think we can just use `file_dir.replace` instead of `file_dir.rename`. Do you want to file a quick PR for that? Otherwise I'm happy to do it.

**Comment by ChVo24** [comment]
Indeed replace would also work! Great, would be nice if you could do that :)

**Comment by krfricke** [comment]
Sure thing! Here we go: #28404 - will be merged later today. And thanks for raising this issue!
