### ISSUE TITLE
[Data] Quantile calculation

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#28408]
### Description

Quantile calculation is a common operation for various statistical and ML purposes (especially the case of calculating the median). It would be very helpful for both users and AIR preprocessor developers to have a Dataset API to efficiently calculate desired quantiles.

**Comment by Yard1** [comment]
@matthewdeng

**Comment by daikeshi** [comment]
I'm curious if Ray Data has the plan to implement this. Thank you.
