### ISSUE TITLE
[State API] Cannot connect to the dashboard server for the summary API

### ISSUE THREAD

**Issue by ankur6ue** [ray-project/ray#28429]
### What happened + What you expected to happen

Trying to use the summarize APIs to get a actor summary to kill any pending actors in my driver program. Setting: ray cluster running on a kubernetes cluster. I can successfully connect to the cluster like so:

Here 30423 is the port number where port 10001 is exposed by the nodeport service start by KubeRay operator
ray.init(address="ray://107.22.108.71:30423",
                 runtime_env={"working_dir": working_dir,
                              "excludes":["/models/*", "/scratch/*", ".cache/", "*.pkl", "*.flac"],
                              "env_vars":config})

However while using the observability APIs, 
from ray.experimental.state.api import summarize_tasks, list_actors, summarize_actors
ac = summarize_actors(address="107.22.107.71:32188")
32188 is the port that port 6379 is mapped to.
I get:
 Unable to connect to GCS at ray://107.22.107.71:32188. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.

Tried using the Ray CLI as well, and same thing happens. 

### Versions / Dependencies

Ray 2.0.0

### Reproduction script

from ray.experimental.state.api import summarize_tasks, list_actors, summarize_actors
ac = summarize_actors(address="107.22.107.71:32188")

**Comment by scottsun94** [comment]
@rickyyx @rkooo567

**Comment by scottsun94** [comment]
cc: @DmitriGekhtman

**Comment by rkooo567** [comment]
```
from ray.experimental.state.api import summarize_tasks, list_actors, summarize_actors
ac = summarize_actors(address="107.22.107.71:32188")
```

Do you run this code inside the k8s cluster? or outside?

**Comment by Christof23** [comment]
@ankur6ue you need to set `include_dashboard=True` when initialising the ray cluster, either in `ray.init(include_dashboard =true)` or `ray start --include-dashboard=true` using the cli.

**Comment by rickyyx** [comment]
Could you verify that `telnet 107.22.107.71 32188` is able to connect?
