### ISSUE TITLE
[Windows,Core] Windows wheel missing for ray-2.0.0-cp310

### ISSUE THREAD

**Issue by fehrin** [ray-project/ray#28447]
### What happened + What you expected to happen

1. The ray-2.0.0-cp310 wheel is missing for Windows, only Linux and MacOS are present.
2. The ray-2.0.0-cp310 wheel should be available for Windows too.

### Versions / Dependencies

Windows 10 Python 3.10 ray 2.0.0

### Reproduction script

no code snippet

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
fyi @scv119

**Comment by mattip** [comment]
They are available in the [nightly builds](https://docs.ray.io/en/master/ray-overview/installation.html?highlight=nightly#daily-releases-nightlies) at [this link](https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-win_amd64.whl]. Maybe the upload process at 2.0 release time missed them?

**Comment by ChucklesTheBeard** [comment]
Same deal, 2.0.1-cp310 for windows is missing.

**Comment by mattip** [comment]
Ray 2.2.0 was released and I do not see python3.10 wheels for windows on [pypi](https://pypi.org/project/ray/#files). Is there a way to update the release process?

**Comment by scv119** [comment]
cc @xwjiang2010 on the windows wheels.

**Comment by rickyyx** [comment]
Fixed the missing 2.2.0 window wheel for py3.10 and uploaded to pypi. https://pypi.org/project/ray/2.2.0/#files
