### ISSUE TITLE
[autoscaler] Support Environment Variables and Conda Environments

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#2845]
### Describe the problem
It would be nice to not need to append the environment variable and conda environment to each line of the setup, or even to add it to the bashrc.

**Comment by mccarthyryanc** [comment]
Old issue, but I just got started with ray and use conda. Would love the ability to define a conda env or install path to make initializing and running ray within a conda env easier.

**Comment by richardliaw** [comment]
In the cluster launcher, you should add a source activate call before each command:

`source {conda_env_activate} && COMMAND...`

Alternatively you can echo the activate call into `.bashrc` (`echo "source conda_env_activate" >> ~/.bashrc`) in the setup commands.
