### ISSUE TITLE
[rllib] ARS MeanStdFilter absent when restores

### ISSUE THREAD

**Issue by whikwon** [ray-project/ray#2849]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.2
- **Python version**: 3.6.3
- **Exact command to reproduce**:

### Describe the problem

I've restored the checkpoint-400, checkpoint-400.tune_metadata and params.json and I found all the values of `MeanStdFilter` are zeros. 
`MeanStdFilter((412,), True, True, None, (n=0, mean_mean=0.0, mean_std=0.0), (n=0, mean_mean=0.0, mean_std=0.0))`

How can I save and restore `MeanStdFilter` value correctly?

**Comment by whikwon** [comment]
I can't find the `sync_filter` function when restoring like in the [ppo.py].(https://github.com/ray-project/ray/blob/9ba751c29a24b7d68b1649670917d71637136429/python/ray/rllib/evaluation/policy_evaluator.py#L464)

**Comment by ericl** [comment]
@eugenevinitsky we should probably do the same as ES for filters?

**Comment by ericl** [comment]
I think we just don't sync the filter to the driver, but it should be updated fine on the workers still.

**Comment by whikwon** [comment]
@ericl I think if filter is not updated, i could not be able to do evaluation. Is it correct?

**Comment by ericl** [comment]
Yes. Evaluation is broken here.

**Comment by eugenevinitsky** [comment]
@ericl is anyone on this? If not, I'll try and grab this.

**Comment by ericl** [comment]
@eugenevinitsky not that I know of, thanks!

**Comment by eugenevinitsky** [comment]
@ericl it looks like this is probably happening in ES too

**Comment by krfricke** [comment]
Fixed 3 years ago by #2918
