### ISSUE TITLE
[jobs] cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by 1059692261** [ray-project/ray#28497]
### What happened + What you expected to happen

Dear all,
I try to submit a work using ray tune from my windows 10 laptop to our ray cluster,  which is deployed on several linux machines. And I encounter an error as shown below:
![image](https://user-images.githubusercontent.com/44863873/190038508-3734e49f-6d7c-4e24-af31-69573364f10d.png)
The code I run is actually a sample code from ray tune documentation. Is this a bug or am I missing something?  Any help would be appreciated!

### Versions / Dependencies

ray 2.0
python 3.8.5
os windows10

### Reproduction script
```
import ray
from ray import tune

def objective(config):
    score = config["a"] ** 2 + config["b"]
    return {"score": score}

ray.init(address="ray://10.128.2.64:30008")

search_space = {
    "a": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
    "b": tune.choice([1, 2, 3]),
}
    
tuner = tune.Tuner(objective, param_space=search_space)
results = tuner.fit()
print(results.get_best_result(metric="score", mode="min").config)
```

**Comment by richardliaw** [comment]
tagging in @mattip to help out here!

**Comment by pcmoritz** [comment]
It seems highly likely that this is due to the Ray Client and the code being pickled on the Windows host and then unpickled on the Linux server that runs the Ray Cluster -- I would recommend running the script from within the Ray cluster as a driver.

**Comment by pcmoritz** [comment]
I.e. if you replace
```
ray.init(address="ray://10.128.2.64:30008")
```
with
```
ray.init()
```
and run the script with `python script.py` from the head node it should work :)

**Comment by 1059692261** [comment]
> I.e. if you replace
> 
> ```
> ray.init(address="ray://10.128.2.64:30008")
> ```
> 
> with
> 
> ```
> ray.init()
> ```
> 
> and run the script with `python script.py` from the head node it should work :)

Thank you for your advice. However, submitting works from the head node would not be our goal. We actucally want to submit jobs from any remote hosts.

**Comment by richardliaw** [comment]
Can you try using Ray Job submission instead? https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html

**Comment by 1059692261** [comment]
> Can you try using Ray Job submission instead? https://docs.ray.io/en/latest/cluster/running-applications/job-submission/index.html

Sorry for the misleading statement. We need ray tune for hyperparameter tuning and except to submit the work programmatically.

**Comment by pcmoritz** [comment]
There are two possibilities to make it work:
- Use the Python API for job submission: https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#submitting-a-ray-job
- Put the tuning into a Ray task that you submit via the client:
```
import ray

ray.init(address="ray://10.128.2.64:30008")

@ray.remote
def tune_job():
    from ray import tune

    def objective(config):
        score = config["a"] ** 2 + config["b"]
        return {"score": score}

    search_space = {
        "a": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
        "b": tune.choice([1, 2, 3]),
    }
    
    tuner = tune.Tuner(objective, param_space=search_space)
    results = tuner.fit()
    return results.get_best_result(metric="score", mode="min").config

print(ray.get(tune_job.remote()))
```

For the latter, it avoids pickling the unpicklable object on your driver :)

I hope one of these ways works for your use case!

**Comment by pcmoritz** [comment]
Let us know which way you decide to use / works for your use case so we can add it to our documentation :)

**Comment by 1059692261** [comment]
> There are two possibilities to make it work:
> 
> * Use the Python API for job submission: https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#submitting-a-ray-job
> * Put the tuning into a Ray task that you submit via the client:
> 
> ```python
> import ray
> 
> ray.init(address="ray://10.128.2.64:30008")
> 
> @ray.remote
> def tune_job():
>     from ray import tune
> 
>     def objective(config):
>         score = config["a"] ** 2 + config["b"]
>         return {"score": score}
> 
>     search_space = {
>         "a": tune.grid_search([0.001, 0.01, 0.1, 1.0]),
>         "b": tune.choice([1, 2, 3]),
>     }
>     
>     tuner = tune.Tuner(objective, param_space=search_space)
>     results = tuner.fit()
>     return results.get_best_result(metric="score", mode="min").config
> 
> print(ray.get(tune_job.remote()))
> ```
> 
> For the latter, it avoids pickling the unpicklable object on your driver :)
> 
> I hope one of these ways works for your use case!

Both ways work for me, thank you so much @pcmoritz ! But I still have a few questions:
1、So I guess it is not possible to directly use ray tune to submit my work in my case, right?
2、How can I get my result back using ray job submission python sdk? 
Looking forward to your reply. Thanks again!

**Comment by richardliaw** [comment]
1 - that's right
2 - you'd have to write it to some cloud storage and fetch it back.

hope that helps!
