### ISSUE TITLE
[Docs] `Deprecated` annotation makes "Args" and "Returns" jank 

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28494]
### Description

<img width="662" alt="image" src="https://user-images.githubusercontent.com/26107013/190034765-709b380a-2ccc-4378-a7a3-0960b7c27062.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/26107013/190034794-e5465e28-d939-4cf0-a2df-b7e871791605.png">

**Comment by richardliaw** [comment]
Make a PR?

**Comment by richardliaw** [comment]
Good catch!

**Comment by richardliaw** [comment]
Actually, doesn't seem like Deprecated annotation is the cause, but rather the indentation from the method.

**Comment by bveeramani** [comment]
I think the `Deprecated` annotation is the cause. Adding additional indentation to the `message` variable fixes the error. 

Will open PR now

**Comment by richardliaw** [comment]
Sorry, what I meant was that all the API stability decorators exhibit the same issue (in that all, not just the deprecated annotation, don't work well when the docstring is indented).
