### ISSUE TITLE
[<Ray component: Core>] 

### ISSUE THREAD

**Issue by Fazziekey** [ray-project/ray#28501]
### Description

I used ray with my teammate on a cluster, but I always get failed like below if my teammate also use ray
![image](https://user-images.githubusercontent.com/55798671/190102454-efc28a8b-a11a-444b-9202-4429b81f7037.png)

**Comment by rkooo567** [comment]
Can you share the script you run? Also it seems like workflow related cc @iycheng

**Comment by Fazziekey** [comment]
![image](https://user-images.githubusercontent.com/55798671/190292724-0854f595-c4c3-455a-96b9-0a197dc3cd60.png)

**Comment by Fazziekey** [comment]
this is my code,and this is the link of repositories https://github.com/hpcaitech/FastFold
