### ISSUE TITLE
[Data] ray.data ignores schema if block contains zero rows

### ISSUE THREAD

**Issue by igolant** [ray-project/ray#28505]
### What happened + What you expected to happen

1. reading parquet with zero rows should keep schema (returns schema is None)
2. map_batches should return table with schema (returns schema is None)

see examples in reproduction scripts

### Versions / Dependencies

ray.__version__ = "2.0.0"

### Reproduction script

1. reading parquet with zero rows should keep schema (returns schema is None)
```
import pandas as pd

empty_df = pd.DataFrame({"type": ["type"], "id": [1]}).iloc[[]]
empty_df.to_parquet("/tmp/1.parquet")
empty_df = pd.read_parquet("/tmp/1.parquet")

print(empty_df.columns)

ds = ray.data.read_parquet("/tmp/1.parquet", parallelism=1)

assert ds.schema(), f"Schema should contain two columns!"
```

2. map_batches should return table with schema (returns schema is None)
```
t = (
    ray.data.range_table(10)
    .map_batches(lambda df: df.query("value >= 100").assign(one=1))
)

assert t.schema(), "Schema should contain two columns"
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
cc @jianoaix @clarkzinzow for triage.

**Comment by alonziltzer** [comment]
hi any update on this bug ? thanks
