### ISSUE TITLE
[AIR/Tune] HorovodTrainer (with Keras Model) apparently not writing metrics to results

### ISSUE THREAD

**Issue by voklejas2** [ray-project/ray#28510]
### What happened + What you expected to happen

Hi!

1. I've tried to implement a HorovodTrainer, to train a Keras Model, with Ray Tune, but it appears as though the results dict is not being updated with the specified "mean_accuracy" metric. The model will train as expected (with Horovod distributing the model/data over worker nodes), but I suspect that either the TuneReportCallback is not being used properly or that it's failing somehow because the Ray Tune cannot seem to find metrics at the end of a Trial. I have found that if I replace the HorovodTrainer with a simpler version of Ray's function API (same underlying Keras model), I don't have any problems and the results dict is updated with the metric. 

2. I expected that the HorovodTrainer would behave the same as that of the Function API.

3. The error reported at the end of the attempted run:

> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,012      WARNING session.py:82 -- Session not detected. You should not be calling `report` outside `tuner.fit()` or while using the class API.
> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,012      WARNING session.py:88 --   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 930, in _bootstrap
> (RayTrainWorker pid=46835)     self._bootstrap_inner()
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> (RayTrainWorker pid=46835)     self.run()
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 91, in run
> (RayTrainWorker pid=46835)     self.ret = self._target(*self._args, **self._kwargs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 155, in <lambda>
> (RayTrainWorker pid=46835)     return lambda: wrapped_train_func(config)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 141, in discard_return_wrapper
> (RayTrainWorker pid=46835)     train_func(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/u1/v/voklejas/repos/xtal_powder_pattern_ml/src/train/min_hvd_tune_repro.py", line 124, in worker_train(RayTrainWorker pid=46835)     model.fit(dataset,
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
> (RayTrainWorker pid=46835)     return fn(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/engine/training.py", line 1460, in fit
> (RayTrainWorker pid=46835)     callbacks.on_epoch_end(epoch, epoch_logs)
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/callbacks.py", line 416, in on_epoch_end
> (RayTrainWorker pid=46835)     callback.on_epoch_end(epoch, logs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/air/callbacks/keras.py", line 64, in on_epoch_end
> (RayTrainWorker pid=46835)     self._handle(logs, "epoch_end")
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/integration/keras.py", line 65, in _handle
> (RayTrainWorker pid=46835)     tune.report(**report_dict)
> (RayTrainWorker pid=46835)
> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,015      WARNING session.py:82 -- Session not detected. You should not be calling `checkpoint_dir` outside `tuner.fit()` or while using the class API.
> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,015      WARNING session.py:88 --   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 930, in _bootstrap
> (RayTrainWorker pid=46835)     self._bootstrap_inner()
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> (RayTrainWorker pid=46835)     self.run()
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 91, in run
> (RayTrainWorker pid=46835)     self.ret = self._target(*self._args, **self._kwargs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 155, in <lambda>(RayTrainWorker pid=46835)     return lambda: wrapped_train_func(config)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 141, in discard_return_wrapper
> (RayTrainWorker pid=46835)     train_func(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/u1/v/voklejas/repos/xtal_powder_pattern_ml/src/train/min_hvd_tune_repro.py", line 124, in worker_train
> (RayTrainWorker pid=46835)     model.fit(dataset,
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
> (RayTrainWorker pid=46835)     return fn(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/engine/training.py", line 1460, in fit
> (RayTrainWorker pid=46835)     callbacks.on_epoch_end(epoch, epoch_logs)
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/callbacks.py", line 416, in on_epoch_end
> (RayTrainWorker pid=46835)     callback.on_epoch_end(epoch, logs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/air/callbacks/keras.py", line 64, in on_epoch_end
> (RayTrainWorker pid=46835)     self._handle(logs, "epoch_end")
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/integration/keras.py", line 196, in _handle
> (RayTrainWorker pid=46835)     self._checkpoint._handle(logs, when)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/integration/keras.py", line 123, in _handle
> (RayTrainWorker pid=46835)     with tune.checkpoint_dir(step=self._cp_count) as checkpoint_dir:
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/contextlib.py", line 119, in __enter__
> (RayTrainWorker pid=46835)     return next(self.gen)
> (RayTrainWorker pid=46835)(RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,588      WARNING session.py:82 -- Session not detected. You should not be calling `report` outside `tuner.fit()` or while using the class API.
> (RayTrainWorker pid=46835) 2022-09-13 16:31:41,588      WARNING session.py:88 --   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 930, in _bootstrap
> (RayTrainWorker pid=46835)     self._bootstrap_inner()
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> (RayTrainWorker pid=46835)     self.run()
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 91, in run
> (RayTrainWorker pid=46835)     self.ret = self._target(*self._args, **self._kwargs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 155, in <lambda>
> (RayTrainWorker pid=46835)     return lambda: wrapped_train_func(config)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 141, in discard_return_wrapper
> (RayTrainWorker pid=46835)     train_func(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/u1/v/voklejas/repos/xtal_powder_pattern_ml/src/train/min_hvd_tune_repro.py", line 124, in worker_train
> (RayTrainWorker pid=46835)     model.fit(dataset,
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
> (RayTrainWorker pid=46835)     return fn(*args, **kwargs)
> (RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/engine/training.py", line 1460, in fit
> (RayTrainWorker pid=46835)     callbacks.on_epoch_end(epoch, epoch_logs)(RayTrainWorker pid=46835)   File "/global/common/software/nersc/pm-2022q2/sw/tensorflow/2.9.0/lib/python3.9/site-packages/keras/callbacks.py", line 416, in on_epoch_end
> (RayTrainWorker pid=46835)     callback.on_epoch_end(epoch, logs)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/air/callbacks/keras.py", line 64, in on_epoch_end
> (RayTrainWorker pid=46835)     self._handle(logs, "epoch_end")
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/integration/keras.py", line 197, in _handle
> (RayTrainWorker pid=46835)     self._report._handle(logs, when)
> (RayTrainWorker pid=46835)   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/integration/keras.py", line 65, in _handle
> (RayTrainWorker pid=46835)     tune.report(**report_dict)
> (RayTrainWorker pid=46835)
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.
> (RayTrainWorker pid=46835) WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op while saving (showing 1 of 1). These functions will not be directly callable after loading.Traceback (most recent call last):
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 839, in _wait_and_handle_event
>     self._on_training_result(
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 964, in _on_training_result
>     self._process_trial_results(trial, result)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1048, in _process_trial_results
>     decision = self._process_trial_result(trial, result)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1085, in _process_trial_result
>     self._validate_result_metrics(flat_result)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1181, in _validate_result_metrics
>     raise ValueError(
> ValueError: Trial returned a result which did not include the specified metric(s) `mean_accuracy` that `tune.TuneConfig()` expects. Make sure your calls to `tune.report()` include the metric, or set the TUNE_DISABLE_STRICT_METRIC_CHECKING environment variable to 1. Result: {'trial_id': '2ee7fe8e', 'experiment_id': '96335327476b46149e74f2b43a8197fb', 'date': '2022-09-13_16-31-28', 'timestamp': 1663111888, 'pid': 46801, 'hostname': 'nid001049', 'node_ip': '128.55.64.203', 'done': True, 'config/train_loop_config/lr': 0.01, 'config/train_loop_config/batch_size': 64}
> 
> During handling of the above exception, another exception occurred:Traceback (most recent call last):
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/tuner.py", line 234, in fit
>     return self._local_tuner.fit()
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py", line 283, in fit
>     analysis = self._fit_internal(trainable, param_space)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/impl/tuner_internal.py", line 380, in _fit_internal
>     analysis = run(
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/tune.py", line 722, in run
>     runner.step()
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 872, in step
>     self._wait_and_handle_event(next_trial)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 851, in _wait_and_handle_event
>     raise TuneError(traceback.format_exc())
> ray.tune.error.TuneError: Traceback (most recent call last):
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 839, in _wait_and_handle_event
>     self._on_training_result(
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 964, in _on_training_result
>     self._process_trial_results(trial, result)  File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1048, in _process_trial_results
>     decision = self._process_trial_result(trial, result)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1085, in _process_trial_result
>     self._validate_result_metrics(flat_result)
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/execution/trial_runner.py", line 1181, in _validate_result_metrics
>     raise ValueError(
> ValueError: Trial returned a result which did not include the specified metric(s) `mean_accuracy` that `tune.TuneConfig()` expects. Make sure your calls to `tune.report()` include the metric, or set the TUNE_DISABLE_STRICT_METRIC_CHECKING environment variable to 1. Result: {'trial_id': '2ee7fe8e', 'experiment_id': '96335327476b46149e74f2b43a8197fb', 'date': '2022-09-13_16-31-28', 'timestamp': 1663111888, 'pid': 46801, 'hostname': 'nid001049', 'node_ip': '128.55.64.203', 'done': True, 'config/train_loop_config/lr': 0.01, 'config/train_loop_config/batch_size': 64}The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/global/u1/v/voklejas/repos/xtal_powder_pattern_ml/src/train/min_hvd_tune_repro.py", line 206, in <module>
>     tune_horovod_train_model(
>   File "/global/u1/v/voklejas/repos/xtal_powder_pattern_ml/src/train/min_hvd_tune_repro.py", line 168, in tune_horovod_train_model
>     result_grid = tuner.fit()
>   File "/global/homes/v/voklejas/.local/perlmutter/tensorflow2.9.0/lib/python3.9/site-packages/ray/tune/tuner.py", line 236, in fit
>     raise TuneError(
> ray.tune.error.TuneError: Tune run failed. Please use tuner = Tuner.restore("/global/homes/v/voklejas/ray_results/hvd") to resume.
> (RayTrainWorker pid=46837) [2022-09-13 16:31:48.560443: E /tmp/pip-install-dbp27f35/horovod_18f6e6c694b94285bfe53445585605d7/horovod/common/operations.cc:654] [2]: Horovod background loop uncaught exception: [/tmp/pip-install-dbp27f35/horovod_18f6e6c694b94285bfe53445585605d7/third_party/gloo/gloo/transport/tcp/pair.cc:589] Read error [128.55.64.203]:50370: Connection reset by peer
> srun: launch/slurm: _task_finish: Received task exit notification for 1 task of StepId=3150754.8 (status=0x0100).
> srun: error: nid001049: task 0: Exited with exit code 1
> srun: launch/slurm: _step_signal: Terminating StepId=3150754.8
> 

### Versions / Dependencies

Ray: 2.0.0
OS: Custom Linux-based kernel (Perlmutter)
Python: 3.9.12
Tensorflow: 2.9.0
Horovod: 0.24.3

### Reproduction script
```
import tensorflow as tf
import argparse
import ray
from ray import air, tune
import horovod.tensorflow.keras as hvd
from ray.tune.schedulers import ASHAScheduler
from ray.tune.search.hyperopt import HyperOptSearch
from ray.tune.integration.keras import TuneReportCallback
from ray.tune.integration.keras import TuneReportCheckpointCallback
from ray.train.horovod import HorovodTrainer
from ray.air.config import ScalingConfig
from ray.tune.tune_config import TuneConfig
from ray.tune.tuner import Tuner
import sys
import numpy as np

class data_pipe():
    def __init__(self, n_samples=10000, size=3000, batch_size=64, num_epochs=10):

        self.n_samples = n_samples
        self.size = size
        self.x = np.random.rand(n_samples,size)
        y = np.random.randint(2, size=n_samples)
        self.y = np.reshape(y,(-1,1))
        self.batch_size = batch_size
        self.num_epochs = num_epochs

    def preprocess(self, row):
        PATTERN_COL = "intensity"
        features = tf.slice(row, [0], [self.size])
        label = tf.slice(row, [self.size], [1])
        label = tf.cast(label, tf.int32)
        encoded_labels = tf.one_hot(label, 2)
        features = tf.stack(values = features, axis = 0) #list o rank 0 tens->sngle rank 1 tensor
        features = tf.reshape(features,[features.shape[0],1])
        encoded_labels = tf.reshape(encoded_labels, [encoded_labels.shape[1]])

        return {PATTERN_COL: features}, encoded_labels    

    def get_tfdataset(self):
        gt = np.concatenate((self.x, self.y), axis=1)
        dataset = tf.data.Dataset.from_tensor_slices(gt)
        dataset = dataset.map(map_func=self.preprocess)

        buffer_size = 10 * self.batch_size + 1
        dataset = dataset.shard(hvd.size(), hvd.rank())
        dataset = dataset.repeat(self.num_epochs)
        dataset = dataset.repeat(count = self.num_epochs).batch(batch_size = self.batch_size)
        dataset = dataset.prefetch(buffer_size)

        return dataset

def worker_train(config):
    # https://github.com/tensorflow/tensorflow/issues/32159
    import horovod.tensorflow.keras as hvd
    import tensorflow as tf

    # Horovod: initialize Horovod.
    hvd.init()

    # Horovod: pin GPU to be used to process local rank (one GPU per process)
    gpus = tf.config.experimental.list_physical_devices('GPU')
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
    if gpus:
        tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

    epochs = 10
    bs = config["batch_size"]
    total_num_records = 10000
    dlen = 3000
    d = data_pipe(n_samples=total_num_records, size=dlen, batch_size=bs, num_epochs=epochs)
    dataset = d.get_tfdataset()
    num_steps = total_num_records//bs

    num_classes = 2
    problem_type = 'Classification'
    input_shape = (dlen, 1)
    inputs = tf.keras.Input(shape=input_shape, name='intensity')
    layer1 = tf.keras.layers.Conv1D(32, 8, strides=2, padding='same', kernel_initializer='he_normal')(inputs)
    layer2 =  tf.keras.layers.BatchNormalization()(layer1)
    layer3 = tf.keras.layers.Activation('relu')(layer2)
    layer4 = tf.keras.layers.GlobalMaxPooling1D()(layer3)
    layer5 = tf.keras.layers.Flatten(name='flatten')(layer4)
    outputs = tf.keras.layers.Dense(num_classes, activation='softmax')(layer5)

    model = tf.keras.Model(inputs, outputs)    

    # Add in LR scheduler here
    learn_rate = config["lr"]
    scaled_lr = learn_rate * hvd.size()
    opt = tf.optimizers.Adam(scaled_lr)

    # Horovod: add Horovod DistributedOptimizer.
    opt = hvd.DistributedOptimizer(
          opt, backward_passes_per_step=1, average_aggregated_gradients=True)
    #opt = tf.optimizers.Adam(learn_rate)

    model.compile(loss=tf.losses.BinaryCrossentropy(),
                      optimizer=opt,
                      metrics=['accuracy'],
                      experimental_run_tf_function=False)

    callbacks = [
        hvd.callbacks.BroadcastGlobalVariablesCallback(0),
        hvd.callbacks.MetricAverageCallback(),
        ]

    if hvd.rank() == 0:
        print('NUM DATASET RECORDS',dataset.cardinality().numpy())
        callbacks.append(TuneReportCallback( {"mean_accuracy": "accuracy"}, on="epoch_end"))
        callbacks.append(TuneReportCheckpointCallback(
                  metrics={"mean_accuracy": "accuracy"},
                  filename="model",
                  on="epoch_end"),)

    # Horovod: write logs on worker 0.
    verbose = 1 if hvd.rank() == 0 else 0
    model.fit(dataset,
              steps_per_epoch=num_steps // hvd.size(),
              batch_size=bs//hvd.size(),
              callbacks=callbacks,
              epochs=epochs,
              shuffle=True,
              use_multiprocessing=True)


def tune_horovod_train_model(num_workers, num_samples, use_gpu):
    num_training_iterations = 2
    horovod_trainer = HorovodTrainer(train_loop_per_worker=worker_train,
                                     scaling_config=ScalingConfig(
                                     num_workers=num_workers,
                                     use_gpu=use_gpu)
                                     )
    sched = ASHAScheduler(
                          time_attr='training_iteration',
                          max_t=100,
                          grace_period=10,
                          reduction_factor=3,
                          brackets=1)
    hyperopt = HyperOptSearch(metric="mean_accuracy", mode="max")    
    tuner = Tuner(horovod_trainer,
                  param_space={"train_loop_config":
                                                  {"lr": tune.choice([0.001, 0.005, 0.01]),
                                                    "batch_size": tune.choice([64]),
                                                  }
                              },
                  run_config=air.RunConfig(name="hvd",
                                           sync_config=tune.SyncConfig(syncer=None),  # Disable syncing bc using NFS
                                           stop={"mean_accuracy": 0.6, "training_iteration": num_training_iterations},
                                           checkpoint_config=air.CheckpointConfig(
                                                                                  checkpoint_score_attribute="mean_accuracy",
                                                                                  num_to_keep=2,
                                                                                  ),
                                          ),
                  tune_config=TuneConfig(search_alg=hyperopt,
                                         scheduler=sched,
                                         num_samples=num_samples,
                                         metric="mean_accuracy",
                                         mode="max")
                 )

    result_grid = tuner.fit()

    print("Best hyperparameters found were: ", result_grid.get_best_result(metric="mean_accuracy", mode="max").config)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--run_cluster", action="store_true")
    parser.add_argument("--gpu", action="store_true")
    parser.add_argument(
        "--smoke-test", action="store_true", help=("Finish quickly for testing.")
    )
    parser.add_argument("--num-workers", type=int, default=2)    
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using Ray Client.",
    )
    args, _ = parser.parse_known_args()
    if args.smoke_test:
        ray.init(num_cpus=2)
    elif args.run_cluster:
        print("Running using Ray Cluster")
        print(os.environ["ip_head"], os.environ["redis_password"])
        ray.init(address='auto',
                         _node_ip_address=os.environ["ip_head"].split(":")[0],
                         _redis_password=os.environ["redis_password"]
                )
    elif args.server_address:
        ray.init(f"ray://{args.server_address}")

    # import ray
    # ray.init(address="auto")  # assumes ray is started with ray up

    tune_horovod_train_model(
                 num_workers=args.num_workers,
                 num_samples=2 if args.smoke_test else args.num_workers,
                 use_gpu=args.gpu,
                )
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
Seems like a pretty bad bug. Assigning to @krfricke as DRI (feel free to hand this off, we can coordinate).

**Comment by justinvyu** [comment]
Hi @voklejas2, I reproduced the error with the script you provided. There are two ways of fixing the issue (I've also included an example of how to load checkpoints in both cases):

1. **Use the AIR Keras callback instead of the Tune callback.** This [section in the documentation](https://docs.ray.io/en/latest/train/dl_guide.html#logging-checkpointing-and-callbacks) goes over the differences between the Tune and Train sessions. The unified `session.report` API that's used in this AIR callback will distinguish between these sessions for you (for example, whether you're running a Train loop within a Tune experiment, or just a Tune experiment).
    - Take a look here to see what the AIR callback is doing: [AIR callback](https://github.com/ray-project/ray/blob/1dede1c296a29332171df87b31d9ba92c26b40f7/python/ray/air/callbacks/keras.py#L168).

```python
from ray.air.callbacks.keras import Callback as TrainReportCallback
from ray.air.constants import MODEL_KEY

# ...

def worker_train(config):
    # ...

    model = tf.keras.Model(inputs, outputs)
    if session.get_checkpoint():
        ckpt_dict = session.get_checkpoint().to_dict()
        layer_weights = ckpt_dict[MODEL_KEY]
        for (layer, weights) in zip(model.layers, layer_weights):
            layer.set_weights(weights)

    # ...

    # This callback will save the Keras model and report metrics
    callbacks.append(TrainReportCallback())
    model.fit(..., callbacks=callbacks)
```

The difference between the `tune.integration.keras.TuneReportCallback` and `air.callbacks.keras.Callback` is definitely something to clarify, see this other issue that had problems with the same thing: #25482.

2. **Directly using `session.report` to report metrics and checkpoint**
```python
from ray.air import session, Checkpoint

# ...

def worker_train(config):
    # ...

    model = tf.keras.Model(inputs, outputs)

    if session.get_checkpoint():
        ckpt_dict = session.get_checkpoint().to_dict()
        layer_weights = ckpt_dict["model_weights"]
        for (layer, weights) in zip(model.layers, layer_weights):
            layer.set_weights(weights)

    # ...

    callbacks = [
        hvd.callbacks.BroadcastGlobalVariablesCallback(0),
        hvd.callbacks.MetricAverageCallback(),
    ]
    # Don't use TuneReportCallback, use session.report instead
    train_history = model.fit(dataset,
              steps_per_epoch=num_steps // hvd.size(),
              batch_size=bs//hvd.size(),
              callbacks=callbacks,
              epochs=epochs,
              shuffle=True,
              use_multiprocessing=True)

    # Create checkpoint with Keras layer weights
    ckpt_dict = {
        "model_weights": [layer.get_weights() for layer in model.layers]
    }
    checkpoint = Checkpoint.from_dict(ckpt_dict)

    # Report the accuracy at the last epoch from the `model.fit`
    accuracy = train_history.history["accuracy"][-1]
    session.report({"mean_accuracy": accuracy}, checkpoint=checkpoint)
```

**Comment by voklejas2** [comment]
Many thanks! This resolved this change resolved the issue.

**Comment by justinvyu** [comment]
Glad to hear! I made one small update to the checkpoint loading to use the recommended framework-specific [`TensorflowCheckpoint`](https://docs.ray.io/en/latest/ray-air/package-ref.html#ray.train.tensorflow.TensorflowCheckpoint) rather than loading it as a dict and getting the weights key manually.
