### ISSUE TITLE
[tune] Documentation around syncing / saving / retrieving results is hard to understand

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#28528]
### Description

For the task of "I want to train 1000 models and retrieve each model result later", it's pretty hard to figure out how to do this. There are multiple doc issues:
1. There is no guide for "How to save and retrieve Tune results". This should be a core guide, not something spread out.
2. Several parts of the documentation say "Tune automatically syncs files to the head node". However, this is misleading-- you need to configure syncing, and in many sync modes the files never end up on the head node.
3. There are several ways to do the same thing: tune.log_model, using Checkpoint, saving a file to the current trial dir--- they need to be documented in the same place as different ways to achieve the same goal.
4. There is no documentation on how to retrieve the result of log_model, Checkpoint, etc. after the run has finished.

**Comment by ericl** [comment]
Here's a concrete suggestion on a guide for saving results:

## How to Save and Retrieve Trial Artifacts

### Saving Trial Artifacts

Some explanation of alternatives and when to use them. Limitations such as size, etc.

[Tab 1] -- Using local files
[Tab 2] -- Using Checkpoint (and also explanation of resuming from Checkpoint)
[Tab 3] -- Using log_model

### Reading Trial Artifacts

Explanation of relevant context.

[Tab 1] -- Reading files from local dir / synced dir
[Tab 2] -- Reading checkpoints
[Tab 3] -- Reading logged models

### Configuring Artifact Storage

Talk about what always works (only Checkpoint?). What works in certain cases (e.g., rsync). Recommended approaches.

**Comment by Yard1** [comment]
Looking into existing documentation, here is my journey right now:

1. As a user, I want to do hyperparameter tuning. I want to use a custom function, save the artifacts and metrics and analyze them later.
2. I open up Ray AIR user guides and land at https://docs.ray.io/en/master/ray-air/tuner.html
3. The note at the top guides me to Ray Tune documentation
4. I also see that there is a "How to analyze results?" section. This guides me to https://docs.ray.io/en/master/tune/examples/tune_analyze_results.html, which explains in detail how to analyze the results obtained after a run
5. Following up from 3, I land at the main Tune docs page.
6. If I go to Key Concepts page, I do not see anything about `with_parameters`. I can see how to create a basic trainable and a search space and I am linked to pages which contain more information.
7. https://docs.ray.io/en/master/tune/api_docs/trainable.html#trainable-docs shows me how to report metrics and checkpoint results. `with_parameters` is described at the end, but I don't really know how to use it. `with_resources` is not there.

I think what we have right now is scattered but linked together sufficiently well. Promoting `with_parameters` and explaining `with_resources` should cover the gaps.

**Comment by Yard1** [comment]
I expanded upon the Tune Trainable docs here - https://github.com/ray-project/ray/pull/30314

**Comment by matthewdeng** [comment]
@Yard1 I think there's still a sizable gap as a user to understanding how to work with Trial level checkpoints/artifacts/files as a whole.

As a user I need to stitch together the information from:
- [Trainable API Docs](https://docs.ray.io/en/master/tune/api_docs/trainable.html#function-api-checkpointing)
- [Analyzing Results](https://docs.ray.io/en/master/tune/examples/tune_analyze_results.html#accessing-checkpoints-and-loading-for-test-inference) 
- [Experiment Checkpoints](https://docs.ray.io/en/master/tune/tutorials/tune-checkpoints.html)
- [Logging](https://docs.ray.io/en/latest/tune/tutorials/tune-output.html#how-to-configure-trainable-logging)
- Sadly I couldn't even find the documentation where we talk about generically writing to the current working directory. 
- There is also some work around generic artifact syncing (https://github.com/ray-project/ray/issues/30071), which is closely related to the two previous items.

I do see a lot of value in adding a single User Guide with all of this information in the shape of Eric's proposal above, which can be linked to from the other pages.
