### ISSUE TITLE
[tune] ImportError when importing TrainingResult

### ISSUE THREAD

**Issue by albertaparicio** [ray-project/ray#2854]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 18.3
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.2
- **Python version**: 3.6.6
- **Exact command to reproduce**: `from ray.tune import TrainingResult`

### Describe the problem

When I try to import TrainingResult I get an ImportError. It was working well in version 0.5.0.

I have looked for references to this class in the code, but I cannot find it. It would like to know if this class is now located in another module or it has been eliminated altogether.

Thank you

**Comment by ericl** [comment]
Hey @albertaparicio, in 0.5.2 it has been replaced by just a `dict`.

**Comment by richardliaw** [comment]
I think we can close this for now and reopen if any followup questions arise.
