### ISSUE TITLE
[Ray Cluster][Autoscaler] Reduce # of redundant tags as we autoscale 

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#28545]
### Description

User reported that with ray cluster autoscaling to 16 hosts, we ended up with ~16 tags that could exceed limit of tags on GCP which requires user to hack around reducing them. We should be able to make them less verbose and scalable to GCP wrt to the tag count limit.

**Comment by zygi** [comment]
Specifically, GCP's labels are quite restrictive: you can have 64 k/v pairs each, with each key and value being max 63 chars. For normal nodes this isn't a problem, but we wrote an autoscaler provider for GCP TPU pod slices -- which means we can be creating up to 32 ray nodes backed by a single logical gcp instance (e.g. TPUv4-256). To fit the tags for all the ray nodes I've had to resort to some ugly label remapping/compression, and while that works, if it's possible to reduce tag usage on ray's side that would be much more preferable.

(One other alternative solution in our case would be to store ray tags not as gcp labels but as values in some other gcp k/v database service -- but that would introduce a ton of complexity we'd like to avoid.)

**Comment by jiaodong** [comment]
cc: @DmitriGekhtman this is one of the large model training users we're engaging with who might come visit us someday. Do you mind taking a closer look at this and we can discuss the actionable items needed ?

**Comment by DmitriGekhtman** [comment]
Similar to the other issue -- The overarching goal as I understand it is to provision Ray on TPU slices.
I think it would be ideal to work out a solution that doesn't involve the autoscaler.
