### ISSUE TITLE
[Tuner/RLlib] Failed restore tuner on Windows. 

### ISSUE THREAD

**Issue by flyinskybtx** [ray-project/ray#28558]
### Failed restore tuner on Windows. Urllib wrongly recognized Windows filepath as url
Tuner failed to restore from checkpoint (trainable.pkl) on Win10.

The ray_results location is "~/ray_results" by default, which is interpreted as "C://User/lxh/ray_results", and my trainable.pkl and tuner.pkl well exists.

by calling tuner.restore("C:\\Users\\lxh\\ray_results\\RocketHover"), it raise
_FileNotFoundError: [WinError 3] Failed copying '/Users/lxh/ray_results/RocketHover/trainable.pkl' to 'C:/Users/lxh/AppData/Local/Temp/tmp37l5utcitmp_experiment_dir/trainable.pkl'. Detail: [Windows error 3]_

I looked into the problem, tuner create an tuner_internal instance, which actually does the following:
passing restore_path=path to the constructer
calls self._restore_from_path_or_url(restore_path), which 
calls self._maybe_sync_down_tuner_state(path_or_uri), which 
firstly check restore_path by calling is_non_local_path_uri(restore_path),
which calls  urllib.parse.urlparse(uri) and here comes the problem!

by calling     parsed = urllib.parse.urlparse(uri)
the parsed.scheme=="file" is False because parsed.scheme is ''c" because the restore_path is something like "C:\\Users\\lxh\\ray_results\\RocketHover"

Afterwards, comes the error:
```
_FileNotFoundError: [WinError 3] Failed copying '/Users/lxh/ray_results/RocketHover/trainable.pkl'_ 
because the parser recognized the filepath as a url by starting with 'c:'
```
I think may it requires a fix to make the restore process compatible to Windows filesystem.

### Versions / Dependencies

Ray 2.0.0
OS: Win 10

### Reproduction script
```
  ray.init(local_mode=True)
  trainer = RLTrainer(
          algorithm='PPO',
          ...
          )
    tuner = Tuner(
        trainer,
    )
    tuner.restore("C:\\Users\\xxxx\\ray_results\\CustomEnvExampleXXXX")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
@justinvyu I think this might be somewhat related to the issue that you've been exploring?

**Comment by mattip** [comment]
This is similar to #22640, which was solved by avoiding the code path that uses urllib. One work-around is to avoid using the drive `C:` designation in the path.

**Comment by richardliaw** [comment]
^ workaround seems reasonable. closing this.
