### ISSUE TITLE
[Core] Can't use docker's SSH mount if using Ray as the base image

### ISSUE THREAD

**Issue by lewisbails** [ray-project/ray#28565]
### What happened + What you expected to happen

I'm trying to build a docker image with Ray's `2.0.0-py38-gpu` image as the base image, with the intention to use it as the node image in the cluster launcher yaml. However, it appears that I'm not able to mount my ssh key into the build process, unlike when I use another base image like `ubuntu:18.04`, `alpine` or `python:3.8.14-buster`. If I'm missing something please do tell, but otherwise I think there is an issue with the ray docker images (as this is not limited to `2.0.0-py38-gpu`.

### Versions / Dependencies

Debian 10
ray==2.0.0
docker==20.10.18

### Reproduction script

```bash
eval $(ssh-agent)
ssh-add
docker buildx build --ssh default -t example/ray .
```

```dockerfile
# dockerfile with ray as base image

# syntax=docker/dockerfile:1
FROM rayproject/ray:2.0.0-py38-gpu

# Install ssh client and git
RUN sudo apt update && sudo apt install openssh-client git -y

# Download public key for github.com
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

# Verify with github
RUN --mount=type=ssh ssh git@github.com

# git@github.com: Permission denied (publickey).
```

```dockerfile
# dockerfile with ubuntu as base image

# syntax=docker/dockerfile:1
FROM ubuntu:18.04
# or some other image like python:3.*.*-buster etc.

# Install ssh client and git
RUN apt-get update && apt-get install openssh-client git -y

# Download public key for github.com
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

# Verify with github
RUN --mount=type=ssh ssh git@github.com

# Hi lewisbails! You've successfully authenticated, but GitHub does not provide shell access.
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
Sorry about the delay, this issue somehow slipped. 

This sounds tricky - I am afraid I don't have enough knowledge on this to give a solution, but let me triage. 
In the meanwhile, @lewisbails do u have any updates or attempted walkaround you want to add to this?

**Comment by richardliaw** [comment]
Closing this as there is a workaround ^
