### ISSUE TITLE
[core] autoscaling_shuffle_1tb_1000_partitions failing on memory_monitor.cc assertion failure

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28563]
### What happened + What you expected to happen

```
    [2022-09-15 09:39:21,952 C 237 237] (raylet) memory_monitor.cc:121:  Check failed: (_left_ > _right_)  117896851456 vs 117896851456
```

Possibly also spurious kills by the memory monitor.

### Versions / Dependencies

good commit: 7ba37885c67844d2eb18a63dcf3b7ac7f66ce89f
bad commit: b878fd28d25f17d5bf23563f73c4ab19b6ab625e

### Reproduction script

-

**Comment by clarng** [comment]
The latest run failed, but not due to OOM since it didn't hit memory issues: 

https://ec2-7c1kalm-401tpox-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-staging.com/grafana/?orgId=1&token=mxhLMgoTV3oWkDtOY0eS6rv_7S1sj5DbfqOGaEQ8Auo&var-ClusterID=ses_pUEy8g4AW2fnPCnXNYuBkDwv&refresh=1m&from=now-2d&to=now

Seems the failure was due to something else, there was heartbeat failure possibly due to something happening in raylet?

```

(raylet) [failure_signal_handler.cc : 331] RAW: Signal 6 raised at PC=0x7f9d2e36600b while already in AbslFailureSignalHandler()
(raylet) *** SIGABRT received at time=1663720207 on cpu 10 ***
(raylet) [low_level_alloc.cc : 570] RAW: mmap error: 12
```

**Comment by clarng** [comment]
@scv119  should we keep this issue open or open a different one? The issue in the original title is resolved after we increased the memory threshold in the product / release test

**Comment by clarng** [comment]
Latest run failed for other reasons, seems raylet crashed

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_pUEy8g4AW2fnPCnXNYuBkDwv?command-history-section=command_history

Memory not an issue after we increased the threshold

https://ec2-7c1kalm-401tpox-0000-cust-mon.ray.aws-us-west-2-admin.anyscale-test-staging.com/grafana/?orgId=1&token=mxhLMgoTV3oWkDtOY0eS6rv_7S1sj5DbfqOGaEQ8Auo&var-ClusterID=ses_pUEy8g4AW2fnPCnXNYuBkDwv&refresh=1m&from=now-2d&to=now

**Comment by smithatv** [comment]
@clarng , we have  exactly similar issue .  can you please kindly help me with resolution .

**Comment by movy** [comment]
I just encountered same `[low_level_alloc.cc : 570] RAW: mmap error: 12` error after upgrading RAM from 64 to 128GB, yet I have never encountered this error on other identical machines with 128GB setup. Replacing newly installed memory now, to see whether it was a hardware issue.
