### ISSUE TITLE
[core] shuffle_1tb_5000_partitions times out with ObjectStoreFullError

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28561]
### What happened + What you expected to happen

[command_scd_YJyWmqHNMNXexvB6EdDzfUcz.log](https://github.com/ray-project/ray/files/9580472/command_scd_YJyWmqHNMNXexvB6EdDzfUcz.log)

### Versions / Dependencies

Last good commit: 9ff23cd6224a39254048738fcc469289df387d08
First bad commit: 71bb155c5568e693c6f06a9392889ce4085c7750

### Reproduction script

-

**Comment by scv119** [comment]
huh this is odd. nothing looks suspicious 
71bb155c55 [Datasets] Add Optional hint to compute parameter (#28431)
371866db28 Add a simple `ray_tasks` metric for tracking active and completed tasks. (#28459)
068c9d3f45 [Docs/AIR] Various fixes for AIR examples (#28364)
08275baee3 [Docs] Fix API annotations (#28499)
f0f0001172 [Datasets] Fix _get_read_tasks type hint (#28536)
c2bdee9fea [AIR] Deprecate `Checkpoint.to_object_ref` and `Checkpoint.from_object_ref` (#28318)
439de60140 [Datasets] Add `Literal` type hint to `batch_format` (#28432)
a9b9208e38 [RLlib] Add lr_schedule support to SimpleQ and PG. (#28381)
b878fd28d2 [air] Use self-hosted mirror for CIFAR10 dataset (#28480)
8f4f4d10b8 [doc] Fix tune stopper doctests (#28531)
21140c20c6 [doc/tune] fix tune stopper attribute name (#28517)
c6e71562c7 [autoscaler][observability] Experimental verbose mode (#28392)

**Comment by stephanie-wang** [comment]
Yeah, agreed, could be something changed in the infrastructure too. Let me try running this a few times and see what happens.

**Comment by stephanie-wang** [comment]
Seems like the error might be related to memory monitor but it's not clear. The only noticeable difference in the logs is that there are error messages from the memory monitor evicting workers, but not sure how it leads to ObjectStoreFullError. Possibly there is some other core bug that is causing some bad state when workers are killed often.

I think this issue is currently blocked since there are no related commits and there is no way to run the test without the memory monitor disabled to check.

**Comment by clarng** [comment]
looks like it is fixed now , e.g.

https://console.anyscale-staging.com/o/anyscale-internal/clusters/ses_yJ5rPfSrVGCt4ubwyHwfviba?command-history-section=head_start_up_log

**Comment by clarng** [comment]
Here's a run today

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_q8FSbfqSTBdQDY45EEY8RKzt?command-history-section=command_history

looks like the memory threshold is set to 0.8, which is too low as that would cause excessive retries and test failure. I am sending a PR to fix the threshold for our release test.

https://github.com/ray-project/ray/pull/28640

Also checking with Anyscale to see if they can also increase the value for their testing.

**Comment by clarng** [comment]
I'm not seeing this issue in the latest run after increasing the memory threshold in the product

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_pUEy8g4AW2fnPCnXNYuBkDwv?command-history-section=command_history
