### ISSUE TITLE
[tune] tf.Estimator Example

### ISSUE THREAD

**Issue by agniszczotka** [ray-project/ray#2856]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 
- **Ray installed from (source or binary)**: None
- **Ray version**: None
- **Python version**: 3.6
- **Exact command to reproduce**: None

Could you give an example of tensorflow Estimator (highlevel API) and PBT ?

**Comment by ericl** [comment]
Hey @agniszczotka , here's an example: https://github.com/sseveran/ray-tensorflow-trainable/blob/master/estimator.py

(this was from the dev list discussion here: https://groups.google.com/forum/#!searchin/ray-dev/estimator|sort:date/ray-dev/qQWJT84FeGg/juNuIvl5BAAJ)

**Comment by agniszczotka** [comment]
Het @ericl. I am afraid that your example does not work. Is there any chance for the contribution for tf.estimators used with tune-ray?

**Comment by agniszczotka** [comment]
yes, I have just finished working on that, and I am happy to share the example.

Another issue on the same topic is that [TensorFlow examples](https://ray.readthedocs.io/en/latest/tune-examples.html#tensorflow-examples) does not work correctly for any training scheduler which requires checkpointing. The issue is related (as far as my understanding goes) to the fact that after running trainable.restore(...) ray deletes the temporary directory with the TensorFlow checkpoint. The TensorFlow method self.saver.restore(self.sess, path) is just a declaration of restoring process, and it does not restore model in the place where declared. The restoration of the model variables happens when session.run(...) is performed, and this is the moment when variables are loaded from saved checkpoint to the tf.Graph().  Since checkpoint directory is deleted (in trainable.restore(...) ), the actual process fails.

Why ray.tune delete checkpoint directory in trainable.restore(...)?

**Comment by richardliaw** [comment]
That’s odd, restore shouldn’t delete the directory but restore_from_object
will (so the examples by themselves are probably fine but if you use PBT
they may all fail).

We probably want to add a flag to PBT to allow users to restore from disk..

**Comment by agniszczotka** [comment]
sorry my mistake, it is restore_from_object which cause a problem.
The flags to PBT to restore from disk would solve the problem. In my solution, I solved the problem by saving checkpoints independently to ray.tune. I save the path to dir tree with model checkpoints in a text file. I will prepare the estimator example an share with you soon.

**Comment by agniszczotka** [comment]
Please find a toy example for estimator and ray.tune
https://github.com/agniszczotka/PBT-TF.Estimator-with-Ray.Tune
I am happy to for you to put it on your website

**Comment by richardliaw** [comment]
Hey, btw, as a fix, maybe consider overriding `restore_from_object` and `save_to_object` methods of your Trainable class. This will avoid the directory deletion issue.

**Comment by agniszczotka** [comment]
@richardliaw thank you for your suggestion. It makes a lot of sense :).

**Comment by agniszczotka** [comment]
Thanks for the note :)
