### ISSUE TITLE
[Core/Dask On Ray] `ray_dask_get_sync` is buggy - missing one arg

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#28576]
### What happened + What you expected to happen

Line 555 of file `ray/util/dask/scheduler.py`, inside function `ray_dask_get_sync`, the `get_sync` function that calls `_apply_async_wrapper` which is missing a positional arg `scoped_ray_remote_args`, so the entire function is not usable. 

I assume it's a careless mistake when adding in the support of dask annotations? 

### Versions / Dependencies

`ray == 2.0.0`
`dask == 2022.7.0`

### Reproduction script

```
from ray.util.dask.scheduler import ray_dask_get_sync
from dask import delayed

@delayed
def add(x, y):
    return x + y

a = add(1,2)
b = add(3,4)
c = add(a, b)

ray_dask_get_sync(c.__dask_graph__(), ['c'])
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rickyyx** [comment]
@clarkzinzow (code owner) Looks like we are indeed missing an argument here?

**Comment by rickyyx** [comment]
@clarkzinzow Thanks clark! Will you have the bandwidth for the fix? 

Or if @mlguruz you are interested in a fix PR? Happy to shepherd it.

**Comment by mlguruz** [comment]
> @clarkzinzow Thanks clark! Will you have the bandwidth for the fix?
> 
> Or if @mlguruz you are interested in a fix PR? Happy to shepherd it.

hey - sorry for my super late reply. 

I actually modified the original `ray_dask_get` to work w/ the new `resource_manager` based execution so I'm not sure if my version if a good fit here...

**Comment by rickyyx** [comment]
Gotcha - let me see if folks from data could help fix this. 
cc @c21 @amogkam
