### ISSUE TITLE
[Jobs] [Dashboard] Job Submission logs for entrypoint scripts without ray.init() don't appear in dashboard UI

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#28577]
### What happened + What you expected to happen

In the "Jobs" tab, logs only appear for jobs that involve at least one Ray driver.

<img width="1733" alt="Screen Shot 2022-09-16 at 1 35 17 PM" src="https://user-images.githubusercontent.com/5459654/190728430-18e0f98f-ebbd-4025-9d36-c9db662e46f1.png">

To find the logs for `ray job submit`, you have to go to the "Logs" tab:
<img width="585" alt="Screen Shot 2022-09-16 at 1 35 37 PM" src="https://user-images.githubusercontent.com/5459654/190728485-ea5f3a93-126b-4457-843d-2425ef47ee66.png">

It should be possible to surface this log in the "Jobs" tab.

### Versions / Dependencies

Ray 3.0.0dev0, Python 3.8, Mac OS

### Reproduction script

`ray start --head`

`ray job submit -- echo hello`

```python
import ray
ray.init()
def f():
   print("hi from task")

print("hi from driver")
ray.get(f.remote())
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by alanwguo** [comment]
ah I see. This is only a bug for ray job submissions that don't have drivers.

If your submit a job that launches a ray driver, the logs button works.

**Comment by alanwguo** [comment]
@architkulkarni , the reason why the logs button doesn't show up for driverless job submissions is because we get the information about which node the driver is running via the driver info.

For job submissions, if I can assume the job is running in the head node, this can be an easier fix. However, I heard something that submission jobs may not always run in the head node soon. In that case, where can I find information about which node the submission is running on?

**Comment by architkulkarni** [comment]
@alanwguo Ah makes sense.  That's a good question, can we just use the Ray Job logs API (The REST API or the SDK)? That way the logic about figuring out which node the job is on can be handled internally by Ray Jobs and we don't have to duplicate it in the dashboard.

**Comment by scottsun94** [comment]
This seems a pretty bad experience if users cannot click logs button for all the jobs submitted by job apis. 

Is Archit's suggestion ^ a good option? @alanwguo

**Comment by alanwguo** [comment]
> This seems a pretty bad experience if users cannot click logs button for all the jobs submitted by job apis.
> 
> Is Archit's suggestion ^ a good option? @alanwguo

I agree we should fix, but it's not "all jobs" submitted by the job apis. Just the jobs without ray drivers.

I'll spend a little bit of time tomorrow looking into this a bit more closely.

**Comment by scottsun94** [comment]
Ah. Got it. Then it's less of a concern to me.

@architkulkarni When do people submit jobs without ray driver? This seems an edge case?

**Comment by architkulkarni** [comment]
If they want to run a command on the cluster, this is how they would do it. (`ray job submit -- my_cmd`) The command doesn't necessarily have to involve Ray.  But you're right that this isn't the main use case of Ray Jobs (which is to run jobs that use Ray.)

@alanwguo looks like the JobDetails has entries `driver_agent_http_address` and `driver_node_id` which may be relevant.

**Comment by alanwguo** [comment]
looks like `driver_agent_http_address` only gets filled for submission jobs. Is there any reason for this value not to be filled for driver jobs as well?

**Comment by architkulkarni** [comment]
> looks like `driver_agent_http_address` only gets filled for submission jobs. Is there any reason for this value not to be filled for driver jobs as well?

I don't think there's any particular reason.  Because they're just "driver jobs", the Ray Jobs API doesn't interact with them, so there wouldn't be any reason to interact with the JobAgent on that node, so maybe that's why it wasn't filled for driver jobs
