### ISSUE TITLE
[Datasets] Add custom datasource user guide.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#28571]
The ability for users to easily create a custom data connection via our [custom datasource API](https://docs.ray.io/en/master/data/api/input_output.html#datasource-api) is a great feature, but users have struggled creating custom datasources in the past without a user guide. We should have a thorough user guide for this feature.

**Comment by dmatrix** [comment]
Yes, the user guide, as a reference implementation of a data source, will provide immense value for third-party engineering teams who wish to integrate with Ray Data for data ingestion from their custom data source.

**Comment by jianoaix** [comment]
Fixed by https://github.com/ray-project/ray/pull/28717
