### ISSUE TITLE
[AIR] Allow for nested Chain preprocessors

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#28618]
### Description

Allow for Chains to be a part of other Chains. This is explicitly disabled right now, but I don't see a reason why it would need to be.

### Use case

This is a common pattern in scikit-learn - have a pipeline (chain) composed of pipelines. Eg. a categorical pipeline for categorical columns and a numeric pipeline for the rest.

**Comment by Yard1** [comment]
cc @xwjiang2010 (as last commit author) @clarkzinzow @bveeramani @matthewdeng

**Comment by xwjiang2010** [comment]
Actually I can't recall... @matthewdeng @clarkzinzow Do you still remember why?
