### ISSUE TITLE
[AIR] `WandbLoggerCallback` does not capture stdout

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#28645]
W&B has a feature to automatically capture console logs (stdout): https://docs.wandb.ai/quickstart

This is useful to be able to save the outputs from training or tuning experiemnts and easily access them from the web ui.

However, with out `WandbLoggerCallback`, these console logs are not captured. This is likely due to the fact we use wandb in separate processes.

I'll add a repro here later.

**Comment by krfricke** [comment]
@nikitavemuri is this still a problem?
