### ISSUE TITLE
[Core] [Docs] Clarify how fractional GPU is handled by Ray Core scheduler

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#28679]
### Description

It's becoming a common question how Ray Core schedule Tasks / Actors to meet the fractional GPU specification: https://docs.ray.io/en/master/ray-core/tasks/using-ray-with-gpus.html#fractional-gpus

We should clarify in docs that this is done by bin packing onto individual GPU devices (with a simple example)

**Comment by zhe-thoughts** [comment]
Still valid issue

**Comment by jjyao** [comment]
It's mentioned in the latest doc.
