### ISSUE TITLE
[core] Support num_returns="dynamic" generators for actor tasks

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#28681]
### Description

Support [generators](https://docs.ray.io/en/master/ray-core/tasks/generators.html#num-returns-set-by-the-task-executor) for actor tasks.

### Use case

Useful for `compute="actors"` and block splitting in Datasets.

**Comment by rickyyx** [comment]
Do we need to assign owners for this? @stephanie-wang @scv119

**Comment by stephanie-wang** [comment]
I'm hoping @c21 or @clarkzinzow can take the lead on it.
