### ISSUE TITLE
[Core/Dashboard]Timeline view of jobs task etc. similar to spark

### ISSUE THREAD

**Issue by EnjianGong** [ray-project/ray#28690]
### Description

How to provide a Timeline view of tasks during the entire ray scheduling process,  to assist in analyzing performance bottlenecks.

Hierarchical timeline views: job, task, actor
### Use case

Visualization

**Comment by EnjianGong** [comment]
[类似Spark的方式](https://spark.apache.org/docs/3.3.0/img/AllJobsPageDetail2.png)

**Comment by jiaodong** [comment]
Hi @EnjianGong can you edit the title with component and make issue description in English ? This will help a lot to communicate with broader ray community.

**Comment by pcmoritz** [comment]
@EnjianGong Have you had a look at https://docs.ray.io/en/latest/ray-core/troubleshooting.html#visualizing-tasks-in-the-ray-timeline? It provides a timeline similar to your suggestion :)
