### ISSUE TITLE
[Ray Serve] No method with new DAG for remote handle retrieval

### ISSUE THREAD

**Issue by get-a-grep** [ray-project/ray#28704]
### What happened + What you expected to happen

In version 1.13.0, if I were to have the following data management deployment:
```python
@serve.deployment(name = 'data_interface')
class DataInterface:
    async def modifyData(self, data: str):
        #Do something with the data
        return data
```
then I could call a serve handle from any other serve deployment in the same cluster by simply calling the following:
```python
DataInterface.get_handle(sync=False)
```

The problem is that these interfaces are deprecated in ray 2.0.0 in favor of the new DAG implementation. Most of the examples I've seen so far rely on calling `handle = serve.run(DataInterface.bind())` and using that handle to run a remote method with `ray.get()`. That's great but I don't necessarily want to restart the deployment each time just to get the handle. I want to be able to continue to do this basically:

```python
@serve.deployment(route_prefix = "/api", name = "my_api")
class MyAPI:
    def __init__(self):
        self.data_interface = DataInterface.gethandle(sync=False)

    @app.put("/mod/data")
    async def modifyData(self, data: str):
        data = await (await self.data_interface.modifyData.remote(data))
        return data
```

Is it possible to do something similar with the new DAG interface that I'm missing or is this a use-case that ray isn't planning on supporting? If the implementation has shifted so that I can call these remote methods a different way, that would be an extremely helpful bit of information. Any and all help on this is appreciated. Thanks in advance.

### Versions / Dependencies

Python: 3.10
Ray: 2.0.0
OS: Linux

### Reproduction script

Step 1, Have a deployment like this:
```python
@serve.deployment(name = 'data_interface')
class DataInterface:
    async def modifyData(self, data: str):
        #Do something with the data
        return data
```

Step 2, call it like this in another deployment:
```python
@serve.deployment(route_prefix = "/api", name = "my_api")
class MyAPI:
    def __init__(self):
        self.data_interface = DataInterface.gethandle(sync=False)

    @app.put("/mod/data")
    async def modifyData(self, data: str):
        data = await (await self.data_interface.modifyData.remote(data))
        return data
```

Step 3, realize these methods are now deprecated and pray you don't have to reorganize your whole application.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by shrekris-anyscale** [comment]
Ray 2.0 does let deployments call other deployments via handles. In 2.0, handles must be passed to deployments through their constructor. Here's an example with `DataInterface` and `MyAPI`:

```python
@serve.deployment(name = 'data_interface')
class DataInterface:
    async def modifyData(self, data: str):
        #Do something with the data
        return data

@serve.deployment(route_prefix = "/api", name = "my_api")
class MyAPI:
    def __init__(self, data_interface):
        self.data_interface = data_interface

    @app.put("/mod/data")
    async def modifyData(self, data: str):
        data = await (await self.data_interface.modifyData.remote(data))
        return data

data_interface = DataInterface.bind()
my_api = MyAPI.bind(data_interface)

app = my_api

serve.run(app)
```

Note that the constructor for `MyAPI` has changed to take in the `DataInterface` deployment. At runtime, the bound deployment is converted to a handle within the `MyAPI` deployment. There's more details about this type of model composition [in the docs](https://docs.ray.io/en/releases-2.0.0/serve/model_composition.html#composing-deployments-using-servehandles).

**Comment by udayk13** [comment]
Hi @get-a-grep, does this pattern work for you ? Do you have any other concerns here ?

**Comment by shrekris-anyscale** [comment]
Following up here– @get-a-grep does the example resolve the issue?

**Comment by get-a-grep** [comment]
Hey @shrekris-anyscale , this more or less confirms what I figured and read previously in those docs you linked. The only and biggest difference that I see here is the inability to retrieve application handles to a deployment that may lay outside of your pre-planned DAG structure by calling `ray.init()` and `get_handle()` in a component that didn't have to be a ray deployment. While that was likely never an intended use-case it is an unfortunate bit of lost functionality. Regardless, I think I understand the direction that this feature is moving in and have a better understanding of the new functionality now. Thanks for taking the time to look at this and help me out, this answers my question.

**Comment by shrekris-anyscale** [comment]
Serve now offers [`get_app_handle`](https://docs.ray.io/en/releases-2.8.0/serve/api/doc/ray.serve.get_app_handle.html) and [`get_deployment_handle`](https://docs.ray.io/en/releases-2.8.0/serve/api/doc/ray.serve.get_deployment_handle.html) APIs to get Serve handles at runtime.
