### ISSUE TITLE
[tune] Make it easier to implement a correct trainable class

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2870]
### Describe the problem
Currently, it is somewhat cumbersome to define a custom trainable, and the error messages aren't great (e.g., if you forget to return a result from _train(), you get "None has no attribute .copy".)

The class could be a lot more friendly to extend and provide better error messages. @richardliaw

**Comment by richardliaw** [comment]
Do you have a particular example of a cumbersome implementation/pain points?

**Comment by arcelien** [comment]
I think one way to make it easier for a new user to implement this correctly is to take some a good example file and create a tutorial explaining the details / how to use the functions correctly, like the pytorch or tensorflow tutorials. This way there's a good starting point that we know is correct.

It can be tricky implementing it from scratch by just reading the documentation (perhaps the section on the experiment class (in https://ray.readthedocs.io/en/latest/tune-usage.html#tune-overview) could have some examples of some valid arguments?

**Comment by arcelien** [comment]
I think it went pretty smoothly once I understood what every config option does / how each function in `Trainable` is called. I'm still trying to debug a few issues where resuming checkpoints results in poor performance after. I'll let you know if notice any issues later on.

**Comment by arcelien** [comment]
![image](https://user-images.githubusercontent.com/21133703/45701200-71a9c100-bb23-11e8-8a2c-ac806bd8b5c6.png)
A grid search run that seems a little buggy / low variance. Checking checkpointing implementation.

**Comment by richardliaw** [comment]
addressed in #2889
