### ISSUE TITLE
[tune] No incrementing key when using hyperopt

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2872]
### Describe the problem
If you use the hyperopt suggestor, the experiments are missing their incrementing tag. This makes it hard to figure out which trial ran first. Example:
```
Model_0
Model_0
Model_0
Model_0
Model_0
```

It should actually be:

```
Model_1
Model_2
Model_3
Model_4
Model_5
```

**Comment by richardliaw** [comment]
Addressed in #2874
