### ISSUE TITLE
[Pytest][Python] pytest failed with test_basic.py::test_nonascii_in_function_body[ray_start_shared_local_modes1]

### ISSUE THREAD

**Issue by artemisep** [ray-project/ray#28757]
### What happened + What you expected to happen

run the following:
python -m pytest -v -s python/ray/tests/test_basic.py

gave the following err:
ray/tests/test_basic.py::test_nonascii_in_function_body[ray_start_shared_local_modes1] ✓   98% █████████▊2022-09-24 14:31:41,451	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::throw_exception_fct1() (pid=429015, ip=192.168.0.111)
  File "/ray/tests/test_basic.py", line 910, in throw_exception_fct1
    raise Exception("Test function 1 intentionally failed.")
Exception: Test function 1 intentionally failed.
2022-09-24 14:31:41,452	ERROR worker.py:400 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::throw_exception_fct1() (pid=429015, ip=192.168.0.111)
  File "/ray/python/ray/tests/test_basic.py", line 910, in throw_exception_fct1
    raise Exception("Test function 1 intentionally failed.")
Exception: Test function 1 intentionally failed.

### Versions / Dependencies

Python 3.8.0
most recent ray dev build as of 09/24/2022, 14:41

### Reproduction script

python -m pytest -v -s python/ray/tests/test_basic.py

**Comment by rickyyx** [comment]
Hey @artemisep thanks for reporting. However, I think the task is supposed to fail if you look at the exception message, so it's not a failure. 

You should see the tests being `PASS` at the end. It will be easier to see if you just run w/o verbal flags. 
```
python -m pytest  python/ray/tests/test_basic.py
```
