### ISSUE TITLE
[Pytest][Python] pytest failed with test_basic.py::test_ray_options

### ISSUE THREAD

**Issue by artemisep** [ray-project/ray#28755]
### What happened + What you expected to happen

run the following:
python -m pytest -v -s python/ray/tests/test_basic.py

failed the following test
ray/tests/test_basic.py::test_ray_options ✓  
2022-09-24 14:31:23,760	INFO worker.py:1518 -- Connected to Ray cluster.
(raylet) [2022-09-24 14:31:23,796 E 428083 428096] (raylet) file_system_monitor.cc:135: Failed to parse spilling config, error message: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literalThe config string is probably invalid json: 
(raylet) [2022-09-24 14:31:23,623 E 427996 428020] (raylet) file_system_monitor.cc:135: Failed to parse spilling config, error message: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literalThe config string is probably invalid json:

should pass

### Versions / Dependencies

Python 3.8.0
most recent ray dev build as of 09/24/2022, 14:41

### Reproduction script

python -m pytest -v -s python/ray/tests/test_basic.py

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rickyyx** [comment]
https://github.com/ray-project/ray/issues/28757
