### ISSUE TITLE
[doc] conflict version requirement of protobuf by existing tensorflow and google-api-core

### ISSUE THREAD

**Issue by artemisep** [ray-project/ray#28754]
### Description

1. run pip install -r requirements-doc.txt
get error: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-core 2.10.1 requires protobuf<5.0.0dev,>=3.20.1, but you have protobuf 3.19.5 which is incompatible.

uninstalled protobuf and reintall: pip install protobuf==3.20.1

got the following error: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.
tensorboard 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.1 which is incompatible.

version requirement of protobuf by tensorflow 2.10.0 is in conflict with google-api-core 2.10.1

**Comment by zoetsekas** [comment]
same issue here, tried with various tensorflow versions with no luck

**Comment by dgutman** [comment]
Curious if there's been any clarity / updates on this.. I am trying to just install ray[default] .. but this protobuf issue is making a lot of things not work/crash and it's not clear if there's any obvious workaround

**Comment by TarekAloui** [comment]
Anyone has a solution for this?
