### ISSUE TITLE
[Core] ObjectRef's meta-data took too much memory under the large scale shuffle scenario 

### ISSUE THREAD

**Issue by NKcqx** [ray-project/ray#28765]
### Description

In the large scale shuffle scenario, some certain actors may used as intermediate objects' owners. In this case, the metadata memory overhead will be extremely large on those owners. 
The scenario can be reproduced by an equivalent case shown below:

```python
import ray
import time
import sys
import os, psutil
import matplotlib.pyplot as plt

ray.init()

@ray.remote
class Owner:
    def foo(self):
        return 1
o = Owner.remote()
assert ray.get(o.foo.remote())

@ray.remote
class A:
    def warmup(self, owner, batch_size=1):
        return [ray.put("data", _owner=owner) for _ in range(batch_size)]
a = A.remote()
assert ray.get(a.warmup.remote(o))

size = 100000
batch_size = 100
vec = [None] * size
interval = int(size * 0.02)
rss_list = []
x_axis = [ i * interval for i in range(int(size / interval))]

for i in range(size):
    # create a large number of objects and assign their owner to the special actor 'o'
    vec[i] = ray.get(a.warmup.remote(o))
```

This issue is same to the  #23604, but still requires more optimizations.

### Use case

Large scale shuffle ( > 10000 partitions)

**Comment by rickyyx** [comment]
cc @stephanie-wang do you have any recommended practices to mitigate this / or are you aware of any ongoing projects that would address this? 

cc @scv119

**Comment by scv119** [comment]
cc @kfstorm 
AFAIK @kfstorm are working on the improvement.

**Comment by NKcqx** [comment]
@scv119 thx for the quick reply. I'm now actively working on this project with @kfstorm . this issue
