### ISSUE TITLE
[Tune][Air] Links to Session Key-Concepts Page, but there is no section

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#28767]
### Description

The tune [function trainable](https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable/function_trainable.py#L597) has a deprecation warning in line 597 that links to a section on our key concepts page that does not exist.

### Link

https://docs.ray.io/en/master/ray-air/key-concepts.html#session

**Comment by maxpumperla** [comment]
we should definitely think about adding "session" as concept.
