### ISSUE TITLE
[Ray Core] large actor launch overhead.

### ISSUE THREAD

**Issue by marsupialtail** [ray-project/ray#28777]
### What happened + What you expected to happen

Maybe this is not an actual bug but expected behavior, but launching 4 actors take 1.2s on my machine. 

These actors do nothing, and I'd expect the overhead to be much lower.

In my actual system, launching 4 significantly more complicated actors take 2.4s. This is acceptable for long-running workflows but an unacceptable latency for interactive systems that has 100s of actors (making this actor launch latency approach 30s!).

I have reviewed all historical related issues but I'd like a definitive answer if ~1s is what I should expect for 4 actors. 

### Versions / Dependencies

ray 1.12

### Reproduction script

```
import ray
import time

N = 4
ray.init(ignore_reinit_error=True)
@ray.remote
class A:
    def __init__(self, a):
        self.a = a
        self.stuff = []
    def ping(self):
        return True
    def append(self, b):
        self.stuff.append(b)

start = time.time()
actors = {i: A.options(max_concurrency = 2, num_cpus=0.001,resources={"node:" + ray.worker._global_node.address.split(":")[0] : 0.001}).remote(i) for i in range(N)}
ray.get([actors[i].ping.remote() for i in range(N)])
print(time.time() - start)

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rickyyx** [comment]
Hey @marsupialtail , thanks for the issue and the mini reproducible script. 

I tried running on my dev machine, which took 0.6 secs, not that different in terms of orders of magnitude of yours.  

> I have reviewed all historical related issues but I'd like a definitive answer if ~1s is what I should expect for 4 actors.

The short answer is it depends, but I don't think it could under dozens of milliseconds etc. 
And yes, I think you are right, the start-up time is currently linear with number of actors as well.

We are aware of the bottleneck in actor start-up time, and there is ongoing work on the GCS to make actor management more scalable. cc @iycheng 

> This is acceptable for long-running workflows but an unacceptable latency for interactive systems that has 100s of actors

I am wondering what are the requirements of this interactive system that you are building? The original usecases of actors assume some sort of long-running lifetime, thus the initialization cost could be amortized. Would you be able to work with actors that don't require re-initialization across interaction?

**Comment by marsupialtail** [comment]
OK. This sounds good. I am rearchitecting my system to use fewer actors anyways. I have found that a good rule of thumb is you want to have one actor on each machine instead of each physical thread if you want good scale-up times. The actor on the machine functions as a task scheduler for that machine, and you just push tasks instead of launch new actors to do tasks.

**Comment by rickyyx** [comment]
> I have found that a good rule of thumb is you want to have one actor on each machine instead of each physical thread if you want good scale-up times. The actor on the machine functions as a task scheduler for that machine, and you just push tasks instead of launch new actors to do tasks.

Yes, you are absolutely right here.  Closing the issue for now - feel free to re-open or follow up.
