### ISSUE TITLE
[rllib] Reproduce Rainbow results

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#2884]
### Describe the problem

Per https://github.com/ray-project/ray/pull/2737, combining all the Rainbow configs does not yield performance as expected (in fact, sometimes DQN or DDQN performs consistently better).

It would be good to understand why / compare with reference implementations like dopamine.

**Comment by ericl** [comment]
@joneswong let's move the conversation here since that PR is hard to dig up.

**Comment by joneswong** [comment]
Hi Eric, @adoda have deployed Ray on a cluster of Alibaba and we will be able to run a lot of Ray experiments simultaneously. adoda and his colleagues are making attempts to compare Ray with some other RL packages. I think adoda and I  shall run some experiments for you.

**Comment by ericl** [comment]
Thanks @joneswong, let me know how I can help.

**Comment by joneswong** [comment]
The noisy network has NOT been used correctly if we make update (replay) step every 4 sample steps, because 
> the parameters are drawn from the noisy network parameter distribution after every replay step.
according to the paper <NOISY NETWORKS FOR EXPLORATION>.
I am not sure such a slight difference may affect the performance of Rainbow.

**Comment by joneswong** [comment]
Is it ensured to use max_priority instead of the dummy np.ones as the priorities of newly inserted samples?

```
    def add(self, obs_t, action, reward, obs_tp1, done, weight):
        """See ReplayBuffer.store_effect"""

        idx = self._next_idx
        super(PrioritizedReplayBuffer, self).add(obs_t, action, reward,
                                                 obs_tp1, done, weight)
        if weight is None:
            weight = self._max_priority
        self._it_sum[idx] = weight**self._alpha
        self._it_min[idx] = weight**self._alpha
```

```
   batch = SampleBatch({
        "obs": obs,
        "actions": actions,
        "rewards": rewards,
        "new_obs": new_obs,
        "dones": dones,
        "weights": np.ones_like(rewards)
    })
```

**Comment by adoda** [comment]
@ericl , we try to reproduce the experimental conclusion in the paper "Ray: A Distributed Framework for Emerging AI Applications".
Such as:
![image](https://user-images.githubusercontent.com/35217964/45990375-8f8e9d00-c0b2-11e8-9715-f2d9cd8ca1f6.png)

But we don't have  the benchmarks. We did some simulations of the benchmarks, which can't achieve the performance in the paper. So, can you help us with the benchmarks.

**Comment by ericl** [comment]
If I recall, you need to have multiple GCS shards to scale to that throughput. Cc @atumanov

**Comment by justinkterry** [comment]
@ericl Is this properly resolved now? Should the be closed?

Also, is there an example of what config to use to reproduce a rainbow DQN from the paper? I have to do that, and the documentation on it is very unclear.
