### ISSUE TITLE
[Datasets] Move `_add_partitions` logic to `TableBlockBuilder`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28868]
### Description

For context, read https://github.com/ray-project/ray/pull/28413#discussion_r981397002.

### Use case

* Cleaner abstractions
* Makes it easier to optimize

**Comment by hora-anyscale** [comment]
Per Triage Sync: @bveeramani added Ray 2.2 label as part of P1 triage/cleanup feel free to adjust.
