### ISSUE TITLE
[Core] Worker node ignoring --temp-dir option

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#28876]
### What happened + What you expected to happen

When we start a node we can specify `--temp-dir` but seems it only works if the node is the head node. If the node is a worker node, it will use the same temp-dir as the head node ignoring the --temp-dir that passes to it. This means we cannot use different temp-dir for different nodes in the cluster. 

### Versions / Dependencies

master

### Reproduction script

ray start --address=<head_node_address> --temp_dir=xxx

**Comment by jovany-wang** [comment]
Isn't that by designed?

**Comment by jovany-wang** [comment]
Actually I don't know whether it's by design either. Do you have use case to specify a different temp dir on work node?

**Comment by jovany-wang** [comment]
Actually I don't know whether it's by design either. Do you have use case to specify a different temp dir on work node?

**Comment by jjyao** [comment]
I don't have a real use case yet. It's just based on the documentation I thought it's possible but when I tried it out, it didn't work.

**Comment by jovany-wang** [comment]
So I believe the best action is to fix the doc and add an exception when specifying it on work node?

**Comment by WeichenXu123** [comment]
@jjyao 

This ticket does not address my demands.

My demands includes 2 issues:

1. We should allow each ray worker using an individual temp dir, so that when multiple worker runs on the same machine, suppose one worker exit, it can directly delete its temp dir for cleanup.

2. We hope to provide an option to specify log outputs path, currently log outputs are written into temp dir , but, log is different, temp data we should delete them once ray worker terminated, but logs we should preserve them, for following user debugging.

**Comment by jjyao** [comment]
@rkooo567 if we allow setting different temp-dir for different worker nodes, will this break dashboard or observability?

**Comment by jovany-wang** [comment]
> We should allow each ray worker using an individual temp dir

Does it work that we provide the `ray.get_worker_temp_dir()` API? It returns `{temp_dir}/{job_id}/{worker_id}`. The benefit is it can be auto GCed when job is finished or failed(to avoid disk full risk in a long running cluster.). @WeichenXu123 @jjyao

**Comment by WeichenXu123** [comment]
> > We should allow each ray worker using an individual temp dir
> 
> Does it work that we provide the `ray.get_worker_temp_dir()` API? It returns `{temp_dir}/{job_id}/{worker_id}`. The benefit is it can be auto-GCed when job being finished or failed(to avoid disk full risk in a long running cluster.). @WeichenXu123 @jjyao

This is a good idea to my senario.

**Comment by WeichenXu123** [comment]
@jjyao @jovany-wang  Another issue relating to one machine multiple ray nodes:

https://github.com/ray-project/ray/issues/30659

**Comment by rkooo567** [comment]
@WeichenXu123 we don't need multiple tmp dirs right? Each worker node has a different session id, so you just need to delete that one. tmp dir can be the same.

**Comment by rkooo567** [comment]
I am geared towards just raising an exception if this is configured from the worker node startup (and make it same as a head node) unless there's a appealing use cases

**Comment by WeichenXu123** [comment]
@rkooo567 

> Each worker node has a different session id, so you just need to delete that one.

This sounds good.

I think we can add an option in `ray start` CLI, like:
`ray start ... --delete-temp-on-exit`

WDYT ?

**Comment by rkooo567** [comment]
I think for this sort of feature, it is better to rely on the users instead of supporting it ourselves with an option. There may be questions like "how long is the grace period" or other complicated features that might need to come together. What about you just implement this way? 

```
# Bash script
ray start --block
# Remove tmp dir
```

**Comment by WeichenXu123** [comment]
@rkooo567 

```
# Bash script
ray start --block
# Remove tmp dir
```
This might be hard for ray-on-spark implementation. When ray on spark shutdown, spark task process received KILL signal and then os triggers a TERM signal for `ray start ...` process, and this implementation we have no chance to execute  "Remove tmp dir" when ray node shut down.

What about add a more clear option like:
`ray start ... --clean-temp-dir-on-shutdown` ?
