### ISSUE TITLE
[serverless] test_client test flaky on linux 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28871]
### What happened + What you expected to happen

<img width="1805" alt="image" src="https://user-images.githubusercontent.com/11676094/192880731-4512d8b6-8022-4ee7-b6fc-a070ce3c208e.png">

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment]
cc @ckw017 who is looking it already.

**Comment by rickyyx** [comment]
<img width="1805" alt="image" src="https://user-images.githubusercontent.com/11676094/193083812-8abf8e87-4226-4aea-bcfe-a6a30df4b198.png">

**Comment by ckw017** [comment]
Nature is healing
![image](https://user-images.githubusercontent.com/14043490/195447249-ba1a74f4-7ec4-46bb-a3aa-e4270284f385.png)
