### ISSUE TITLE
[autoscaler][flaky] osx://python/ray/tests:test_autoscaler

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28896]
### What happened + What you expected to happen

<img width="1817" alt="image" src="https://user-images.githubusercontent.com/11676094/193092715-522e1d80-c4c4-4615-8425-7ad2c1432b84.png">

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment]
Feel free to close if it's already tracked somewhere cc @DmitriGekhtman

**Comment by hora-anyscale** [comment]
Per Triage Sync: Test is still flaky, root cause unknown

**Comment by DmitriGekhtman** [comment]
@wuisawesome could you exclude this from the osx build?

**Comment by DmitriGekhtman** [comment]
(I'm not sure how to do that)
