### ISSUE TITLE
[<Ray Installation> Mac installation] 

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#28914]
### Description

Current instruction doesn't work: https://docs.ray.io/en/releases-2.0.0/ray-overview/installation.html
@ilee300a was able to install with an internal instruction doc.

@maxpumperla

**Comment by angelinalg** [comment]
@Wendi-anyscale Do you know if this is still an issue? If so, could you share the internal instruction doc?

**Comment by angelinalg** [comment]
@Wendi-anyscale, could you confirm if this is still a problem? If not, could you please close with the resolution reason? Thanks!

**Comment by Wendi-anyscale** [comment]
The issues has been resolved with the new updates!
