### ISSUE TITLE
[AIR] Let users store arbitrary data in framework-specific checkpoints

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#28910]
### Description

Currently, you can only store a model and preprocessor in a `TorchCheckpoint`. 
```
def from_model(
    cls,
    model: keras.Model,
    *,
    preprocessor: Optional["Preprocessor"] = None,
)
```

But, you might need to store other stuff like optimizer weights:

```
            checkpoint = {
                "model": model_without_ddp.state_dict(),
                "optimizer": optimizer.state_dict(),
                "lr_scheduler": lr_scheduler.state_dict(),            
            }
            if model_ema:
                checkpoint["model_ema"] = model_ema.state_dict()
            if scaler:
                checkpoint["scaler"] = scaler.state_dict()
```

**Comment by richardliaw** [comment]
(This needs a design doc / outline of user workflows / better understanding of how this will impact predictors)

**Comment by amogkam** [comment]
We should also make sure to do the following after this is supported:
1. Update examples to use framework specific checkpoints
2. Remove `from_checkpoint` usage in predictors

**Comment by bveeramani** [comment]
Closing because `TorchCheckpoint` isn't recommended anymore
