### ISSUE TITLE
[RLlib] Easily fetch an action probability distribution from trained policy

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#28923]
### Description

Users have to create an action distribution and pass the `action_dist_inputs` to get an action distribution from a policy.
Users have repeatedly asked how to get the distribution which makes it clear that the path is not intuitive.

[Exemplary question from the forums.](https://discuss.ray.io/t/fetch-action-probability-distribution-from-trained-policy/7722)

### Use case

Manually compute action distribution outputs, maybe plot them [...]

**Comment by benjaminpatrickevans** [comment]
@ ArturNiederfahrenhorst could you please show where this is included in the RLModules API, or provide an example of how to do this with the current API? Thank you
