### ISSUE TITLE
[Tune] Consistent memory leak in checkpointing logis 

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#28966]
### What happened + What you expected to happen

There seems to be a consistent memory leak somewhere in Tune checkpointing code, about 1GB/30mins.
This can be easily reproduced with the attached script.
Here is a Grafana chart showing the mem consumption of 3 testing runs:
1. Direct ``ppo.train()``
2. `Tuen.run(..., checkpoint_freq=1)`
3. `Tune.run() without checkpoint_freq`
<img width="1066" alt="Screen Shot 2022-10-02 at 3 09 56 PM" src="https://user-images.githubusercontent.com/6347585/193480914-81f24c5f-d2ae-4305-b6dd-41c20598c9b8.png">
Here is the tensorboard chart for the same 3 runs:
<img width="400" alt="Screen Shot 2022-10-02 at 3 12 02 PM" src="https://user-images.githubusercontent.com/6347585/193480924-927007ca-4e3a-4c66-9427-b68596aec942.png">

The reason I suspected checkpointing may be the problem was that, when I tracemalloc the whole Tune job, the top mem allocator was:
```
Top 10 lines
#1: mem_leak_simple.py:179: 1 objects 4665.8 KiB
  File "mem_leak_simple.py", line 179
    results = tune.run(
  File "/Users/jungong/ray/python/ray/tune/tune.py", line 726
    runner.step()
  File "/Users/jungong/ray/python/ray/tune/execution/trial_runner.py", line 888
    self.checkpoint()
  File "/Users/jungong/ray/python/ray/tune/execution/trial_runner.py", line 708
    self._checkpoint_manager.checkpoint(
  File "/Users/jungong/ray/python/ray/tune/execution/trial_runner.py", line 193
    _serialize_and_write()
  File "/Users/jungong/ray/python/ray/tune/execution/trial_runner.py", line 177
    "checkpoints": list(trial_executor.get_checkpoints().values()),
  File "/Users/jungong/ray/python/ray/tune/execution/ray_trial_executor.py", line 288
    self._cached_trial_state[trial.trial_id] = trial.get_json_state()
  File "/Users/jungong/ray/python/ray/tune/experiment/trial.py", line 833
    json_state = json.dumps(
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/json/__init__.py", line 234
    return cls(
  File "/Users/jungong/miniforge3/envs/main/lib/python3.8/json/encoder.py", line 202
    return ''.join(chunks)
```

### Versions / Dependencies

Master HEAD

### Reproduction script

```
import gym
from gym.spaces import Box, Discrete
import time

import ray
from ray import tune
from ray.rllib.examples.env.random_env import RandomEnv
from ray.rllib.algorithms.ppo.ppo import PPO


BLOCK_SIZE = 1024 * 10  # ~approx 10kB


def main():
    ray.init(local_mode=False)

    config = {
        "env": RandomEnv,
        "env_config": {
            "action_space": gym.spaces.Discrete(100),
            "observation_space": gym.spaces.Box(low=-1, high=1, shape=(1000,)),
        },
        "framework": "tf2",
        'model': {
            'fcnet_hiddens': [256, 256],
            'fcnet_activation': 'linear',
            'vf_share_layers': True,
        },
        "batch_mode": "complete_episodes",
        "rollout_fragment_length": 1,
        "train_batch_size": 200,
        "num_workers": 5,
        "num_envs_per_worker": 1,
        "num_sgd_iter": 2,
        "vf_loss_coeff": 1.0,
        "clip_param": 0.3,
        "num_gpus": 0,
        "grad_clip": 10,
        "recreate_failed_workers": True,
        "enable_connectors": tune.grid_search([True]),
    }


    results = tune.run(
        "PPO",
        name=f"test_mem_leak_{int(time.time())}",
        config=config,
        num_samples=1,
        stop={
            "time_total_s": 3600 * 10,
        },
        max_failures=10,
        resume="AUTO",
        # this seems to cause mem leak.
        # checkpoint_freq=1
    )

    '''
    ppo = PPO(config=config)
    while True:
        ppo.train()
    '''


if __name__ == "__main__":
    main()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
This is likely due to metadata being stored in the checkpoint, and rllib stores a lot of this.

Generally, we rarely have the case where we checkpoint multiple times a second (as we do here) and keep all the checkpoints. The problem can be avoided by e.g. setting `keep_checkpoints_num=10` or something.

Thus, this is more a usage error than an actual memory leak.

At the source, the issue seems to be that rllib reports an enormous set of values, including single batch results or lengths to tune, which might be a misuse of the tune report method. All these values are stored as checkpoint metadata.

In fact, when we drastically prune this metadata in the checkpoint manager like this

```
    def handle_checkpoint(self, checkpoint: _TrackedCheckpoint):
        # Set checkpoint ID
        if checkpoint.id is None:
            checkpoint.id = self._latest_checkpoint_id
        checkpoint.metrics = {"training_iteration": checkpoint.metrics["training_iteration"]}
```

the issue does not seem to come up.

<img width="1397" alt="Screen Shot 2022-10-03 at 11 51 00 AM" src="https://user-images.githubusercontent.com/14904111/193655879-7d4d6d53-a446-4e71-afb4-a4396515154d.png">

**Comment by gjoliver** [comment]
this is awesome.
so should we set the default value for keep_checkpoints_num to 1?
if users want more checkpoints in memory, they can do that by setting a larger number.
I actually don't know what the users can do with all these in-memory checkpoints.

**Comment by krfricke** [comment]
Just for clarification, these are actually on-disk checkpoints, but we do store metadata about them both on-disk and in-memory.

I don't think we should have any default value of `keep_checkpoints_num` - I think the default should be to keep all checkpoints and have the users specify if they want to delete some of them. We should document the implications both for disk storage and memory. To be clear, the provided example checkpoints every iteration, and we have multiple iterations per second, so this is _very_ often. Instead we should probably guide users to set a sensible checkpoint interval.

Two ideas on how to achieve this:

1. We could have a checkpoint_period which gives the time in seconds between to checkpoints (as an alternative to specifying the iterations)
2. We could measure the number of checkpoints per time interval and warn if checkpointing happens too often

What do you think?

**Comment by gjoliver** [comment]
oh, we should definitely keep all checkpoints on disk.
I was thinking if we really need to keep all the metadata in memory, which is the problem here.
why not just keep the metadata of the best checkpoint?

and I love both ideas. to get started, if only we can have a metric of percentage_of_time_spent_in_checkpointing, I feel like that will allow users to Tune the interval in a much more informative way, and will get us 80% there?

**Comment by krfricke** [comment]
We need to keep the metadata in memory to decide which checkpoints to keep. This metadata is just particularly large for rllib results. I think we could resolve this

1. Rllib reports less results, finds other ways to log timeseries etc to tensorboard, or
2. Only store checkpoint-bookkeeping related metadata in TrackedCheckpoint, keep rest of the metadata in the checkpoint directory

Generally I think this is not high priority as it is a usage error that comes with keeping literally hundreds or thousands of checkpoints. Measuring the time spent in checkpointing is a good idea though!

**Comment by gjoliver** [comment]
ok. I agree this may not be high priority. now that we are clear about the limitations of our system.
please add possible improvements to Tune's backlog however you see fit.
I am gonna close this issue now.
thanks.
