### ISSUE TITLE
How to specify the directory where to save the best checkpoint directories?

### ISSUE THREAD

**Issue by slala2121** [ray-project/ray#28973]
### Description

ray.air.session.report(https://docs.ray.io/en/latest/tune/api_docs/trainable.html?highlight=air.CheckpointConfig#class-api-checkpointing) mentions that it moves checkpoints to a new path. Is there a way to specify what path is (default is /tmp/)?

**Comment by matthewdeng** [comment]
Hey @slala2121, checkpoints will be ultimately moved to the checkpoint directory in your experiment/trial directory. 

In general this can be configured by in the [RunConfig](https://docs.ray.io/en/master/ray-air/api/doc/ray.air.RunConfig.html#ray.air.RunConfig) that you pass into the [Tuner](https://docs.ray.io/en/master/tune/api/execution.html). Let me know if this answers your question!
