### ISSUE TITLE
[core][release]  stress_test_dead_actors failure

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28987]
### What happened + What you expected to happen

[Nightly failure 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-891b-4772-a0c3-e61f1c97fa23)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_evpzMAypU1f9fp7e6GyCABdw)

It's probably an infra error as shown from the logs
```
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
INFO:__main__:Waiting for nodes 1/101
```

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by scv119** [comment]
looks like infra failures? we can close it.
