### ISSUE TITLE
[release][CI] serve_autoscaling_multi_deployment

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28985]
### What happened + What you expected to happen

[Build failure nightly 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-8897-4711-b324-d09bd1ae5c2d)
[Cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_AfbEin6jVtuziezQA9EEWHQ2)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by architkulkarni** [comment]
Transient failure in uploading the test files, fixed after restarting
