### ISSUE TITLE
[release][CI] serve_autoscaling_single_deployment

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28984]
### What happened + What you expected to happen

[Build falilure nighlty 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-8894-4b5d-8aaf-ff293e1d744d)
[Cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_7rnJCUvTesEBzHwzakyrsDm3?command-history-section=command_history)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by architkulkarni** [comment]
Transient failure in uploading the test files, fixed after restarting
