### ISSUE TITLE
[release][CI][core] dataset_shuffle_push_based_random_shuffle_100tb failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28989]
### What happened + What you expected to happen

[Build failure 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-895e-4448-a263-70a67104a6a8)

[Cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_VRFTQqgNMPBQKHWrgdPZcfrT?command-history-section=command_history)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment]
Passing now

**Comment by c21** [comment]
Still failing today - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-55f2-4edf-950e-1818560dcf62 .

**Comment by rickyyx** [comment]
Are you looking at this one @c21 or if you need triage?

**Comment by c21** [comment]
> ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.

This one is failed with OOM killer.

**Comment by c21** [comment]
cc @clarng and @scv119.

**Comment by c21** [comment]
should we disable OOM killer by hand now, or we should debug the underlying issue?

**Comment by clarng** [comment]
There is a known issue right now that affects ingest release test, we are planning to send out a PR to fix, if that doesn't merge in time we will disable it today

**Comment by scv119** [comment]
also shuffle is very advanced usecase, it's OK that v1 OOM killer doesn't work in this case.

**Comment by scv119** [comment]
latest run passed once we merged the OOM fixes.
