### ISSUE TITLE
[release][CI] rllib_multi_gpu_with_attention_learning_tests

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28980]
### What happened + What you expected to happen

[Build failure nightly 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-887e-4337-a517-4c8aa478887e)
[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_pDvBgsp2mNcpdZP47wuHvBcE)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rickyyx** [comment]
Any updates on this @sven1977 @avnishn ?

**Comment by avnishn** [comment]
I've run these tests again and it appears that they don't fail, but that we had some issue getting instances of the correct size for these tests. I'm going to be changing the compute config to use smaller instances, but more of them so that we get instances in time.
