### ISSUE TITLE
[release][CI] rllib_stress_tests-smoke-test failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28981]
### What happened + What you expected to happen

[Build failure nighlty 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#0183906e-8881-4fb9-b9ee-d4a52284e3ae)
[Clusrter](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_AfJ5RHvNxiJ5HuLeS5AJh4bw)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by ArturNiederfahrenhorst** [comment]
[We ran this](https://buildkite.com/ray-project/release-tests-branch/builds/1095#_) successfully today.
