### ISSUE TITLE
[relesae][CI] rllib_stress_tests

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#28998]
### What happened + What you expected to happen

[Build failure weekly 10/01](https://buildkite.com/ray-project/release-tests-branch/builds/1081#0183974c-98ce-4281-8d95-97018ce72134)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_TUnnS4cST52VpdwGqQQn62jV)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by ArturNiederfahrenhorst** [comment]
Most likely an infra issue that prevented trails from being scheduled, [ran successfully today](https://buildkite.com/ray-project/release-tests-branch/builds/1095).
