### ISSUE TITLE
[CI] `windows://python/ray/tests:test_runtime_env_working_dir_remote_uri` is failing/flaky on master.

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#29001]
- b01647c169340e3b50baa6bd59f8d67c93fd726d FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/300#01839553-d013-4188-8fe8-dfc586f4c7a3)
- 315c9f2e97bef36ecfd857583d304433e7ce523e FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/294#01839100-b6b1-4fdf-a13f-de3e5f61e8f2)
- db2f84bdfa49d218f97bf7f10678232bff8c48d5 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/287#01838f11-a81e-44fe-b003-4c35879b9bff)
- dff47047e75d490766658b48275c36c0b18f61f2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/259#01838751-8014-424e-b277-998abc60347f)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_runtime_env_working_dir_remote_uri-END
....

**Comment by hora-anyscale** [comment]
Per Triage Sync: No longer flaky - @wuisawesome confirmed.
