### ISSUE TITLE
RLLib multi-GPU optimizer

### ISSUE THREAD

**Issue by philljkc** [ray-project/ray#29024]
### What happened + What you expected to happen

I am running Ray Tune on a shared machine with other users, sshing in as my own user, with 2GPUS and 128 total threads. When I run even a training script with more than 1 GPU on the complex optimizer, it will start training but SIGNIFICANTLY slower (138 seconds for 8k timesteps) than the 1GPU run on a simple-optimizer (same number of timesteps in 1 second, if I run the below config with "num_gpus"=1 and "simple_optimizer"=True). To run on your end, possibly modify local_dir as well, as that's set to my system configuration.

Attached is a minimal script to demonstrate the issue. Thanks for reading, and let me know if you’d know why this is happening. 

### Versions / Dependencies

Ray 1.13.0, Python 3.7, run on Ubuntu 20.04.4 LTS. 

### Reproduction script

from ray import tune
​
config_test_multigpu = {
    "env": "CartPole-v1",
    'num_workers': 11,
    'num_gpus': 2,
    'sgd_minibatch_size': 2048
}
​
tune.tune.run('PPO',
                    stop={'episodes_total': 10000},
                    name='test_multi_gpu',
                     local_dir='/mnt/tank/philljkc/Dropbox (MIT)/ray_results',
                     config=config_test_multigpu, checkpoint_freq=1)

### Issue Severity

High: It blocks me from completing my task.

**Comment by gjoliver** [comment]
I tried this script on a g4dn.12xlarge instance with 4 GPUs.
even with ``'num_gpus': 2``, I can get about 8K timesteps / sec.
my instance has Tensorflow 2.6.2 and CUDA 11.2

Please re-open if you think we should try reproducing this problem some other way.

Thanks.

**Comment by philljkc** [comment]
I have CUDA 11.4 on my machine, and I'm not sure I can change it since I share the machine I'm working on. Do you think this might change things?
