### ISSUE TITLE
[release][ci] long_running_impala

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29023]
### What happened + What you expected to happen

[Nightly Build Failure 09/30](https://buildkite.com/ray-project/release-tests-branch/builds/1080#01839c55-02a4-40c2-b83b-3010c2f16af4)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_duWC3KrGHCEZknEnLFEXRVCU)

Looks like some cluster compute config not compatible with infra:
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/11676094/193703704-c09cb91a-4005-4864-a516-af8166415f86.png">

Seems to be relevant with this [PR](https://github.com/ray-project/ray/pull/28727)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by krfricke** [comment]
Should be fixed by #29041 pending successful run: https://buildkite.com/ray-project/release-tests-pr/builds/17083
