### ISSUE TITLE
[Windows][Runtime envs] System error when deploying with dependencies

### ISSUE THREAD

**Issue by jdonzallaz** [ray-project/ray#29037]
### What happened + What you expected to happen

Hi,

I'm getting a weird exception when deploying a model deployment with dependencies. 
The deployment is made using the following code: 
```python
deployment = ModelDeployment.options(
    name="model_name",
    ray_actor_options={"runtime_env": {"pip": ["rrcf==0.4.3"]}},
)
deployment.deploy(model)
```

First I'm getting multiple warnings saying the deployment is taking too long:
```
(ServeController pid=12896) WARNING 2022-10-04 08:40:34,678 controller 12896 deployment_state.py:1483 - Deployment "3_rrcf_3" has 1 replicas that have taken more than 30s to be scheduled. This may be caused by waiting for the cluster to auto-scale, or waiting for a runtime environment to install. Resources required for each replica: {"CPU": 1}, resources available: {"CPU": 10.9}.
```

Then I'm getting the following error:
```
(pid=) [symbolize_win32.inc : 53] RAW: SymInitialize() failed: 2147483653
(pid=) Fatal Python error: Aborted
(pid=) 
(pid=) Stack (most recent call first):
(pid=)   File "C:\Users\{UserFolder}\AppData\Local\Temp\ray\session_2022-10-04_09-03-51_665886_30440\runtime_resources\pip\3a53428f685dc54c380e327bda0b5a98136b53a4\virtualenv\lib\site-packages\ray\_private\worker.py", line 2001 in connect
(pid=)   File "C:\code\{CodeFolder}\venv\lib\site-packages\ray\_private\workers\default_worker.py", line 210 in <module>
```

I tried to reduce the CPU requirements of the deployment without success.  
I know Windows support for runtime environments is experimental, but you'll still certainly be interested in resolving this problem.

### Versions / Dependencies

- Windows 10
- Python 3.9.5
- Ray 2.0.0

### Reproduction script

```python
import time
import ray
from ray import serve

@serve.deployment(route_prefix=None, ray_actor_options={"num_cpus": 0.1})
class ModelDeployment:
    async def __call__(self, inputs):
        return "pred"

if __name__ == "__main__":
    ray.init()
    serve.start(detached=True, http_options={"host": "0.0.0.0"})

    deployment = ModelDeployment.options(
        name="RRCF",
        ray_actor_options={"runtime_env": {"pip": ["rrcf==0.4.3"]}},
    )
    deployment.deploy()

    while True:
        time.sleep(1)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mattip** [comment]
The crash maybe related to https://github.com/ray-project/ray/pull/23613#issuecomment-1132616875 around the version of grpcio. Ray 2.0.0 released with the requirement `grpcio >= 1.28.1, <= 1.43.0`, but the fix for that PR went into `1.46.2`, which was released May 16. The restriction on grpcio was changed in #28623 10 days ago, without any extra real other changes. Could you try `pip install "grpcio==1.48.1"` and see if the crash still happens?

**Comment by mattip** [comment]
> First I'm getting multiple warnings saying the deployment is taking too long

Are you deploying to a cloud machine or locally? The first time you deploy pip needs to download all the wheels and cache them.

**Comment by jdonzallaz** [comment]
All those tests were running locally, on a local Ray instance. I tried updating grpcio without success (same with its last version; 1.49.1).  
I tried letting it more time, but it never went up.

I also tested on our K8s cluster (Kuberay). It works perfectly with the deployment's runtime_env and went up really fast.

**Comment by simon-mo** [comment]
@jdonzallaz does this still happen locally? This looks like no a blocking problem in the production environment?

**Comment by jdonzallaz** [comment]
I tried again with the same reproduction script and version 2.0.1, but the same problem happens (locally).

No, in the production environment, it is not a blocking problem.

**Comment by anyscalesam** [comment]
@jdonzallaz still important to revisit this? if so can you attempt repro with latest ray271?

**Comment by anyscalesam** [comment]
Closing for now as no response @jdonzallaz please re-open if these does repro on latest ray release (28 at time of writing).
