### ISSUE TITLE
[RFC] [Datasets] Extend `to_tf` to provide more flexibility

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29030]
### Description

This is a follow-up to #29028 

## Proposal

Add a parameter `yield_fn` to `to_tf` that lets user specify how elements are yielded. 

### What should `yield_fn` accept as input?

**Option 1: `yield_fn` takes in the data normally yielded by `to_tf`**

```
Inputs = tf.Tensor | list[tf.Tensor] | dict[str, tf.Tensor]
Targets = tf.Tensor | dict[str, tf.Tensor]

def to_tf(..., yield_fn: Callable[[Inputs, Targets], ...]):
    ...
```

**Option 2: `yield_fn` takes in all of the data, and `feature_colums` and `label_columns` are ignored or passed to `yield_fn`**
```
# Ignored case
def to_tf(..., yield_fn: [dict[str, tf.Tensor]], ...]):
    ...

# Passed to `yield_fn` case
def to_tf(..., yield_fn: [str | list[str], str | list[str], dict[str, tf.Tensor]], ...]):
    ...
```

### What should `yield_fn` return as output?

**Option 1: `yield_fn` returns a tuple of inputs and targets**

```
Inputs = tf.Tensor | list[tf.Tensor] | dict[str, tf.Tensor]
Targets = tf.Tensor | dict[str, tf.Tensor]

def to_tf(..., yield_fn: Callable[[...], Tuple[Inputs, Targets]):
```

**Option 2: `yield_fn` can return anything, but the user needs to specify the output signature**

```
def to_tf(..., yield_fn: Callable[[...], Any], output_signature: Any):
```

### Use case

Two potential use cases are:

1. Your model expects a list of tensors instead of a `dict`.

```
def yield_fn(inputs, targets):
    return list(inputs.values()), targets
```

2. Performing data manipulations that are difficult to express as UDFs. cc @jiaodong I think you have examples of this?

**Comment by amogkam** [comment]
Dumb question, but for use case 1, can't I just convert a dict to a list?

**Comment by bveeramani** [comment]
> Dumb question, but for use case 1, can't the user just convert a dict to a list before passing to the model?

No. If you’re using Keras, you pass the TF Dataset created by `to_tf` directly to `Model.fit`. 

> For use case 2, isn't `yield_fn` already a UDF?

Basically, except the inputs are `dict[str, tf.Tensor`.
