### ISSUE TITLE
[Datasets] Deprecate `iter_tf_batches` in favor of `to_tf`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29031]
### Description

Once we complete these:
- [x] #29028 
- [x] #29030 

We should deprecate `iter_tf_batches`.

### Use case

There shouldn't be multiple ways to convert Ray datasets to TensorFlow datasets. Also, `iter_tf_batches` was added as a short-term solution.

**Comment by richardliaw** [comment]
Do all of our examples use to_tf now?

**Comment by bveeramani** [comment]
> Do all of our examples use to_tf now?

There's a separate PR for this: https://github.com/ray-project/ray/pull/29462.
