### ISSUE TITLE
[release][CI] long_running_many_tasks_serialized_ids

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29049]
### What happened + What you expected to happen

Failed test - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-54bb-4b72-b71d-980f47fc6cf3

Cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_GfeFcZAsVD5bUNcrQYzkWnTM

Didn't find useful information in command history.

### Versions / Dependencies

Master

### Reproduction script

As above

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
This has been manually terminated to unclog the pipeline.
