### ISSUE TITLE
[AIR] Deprecate then remove `Checkpoint.from_checkpoint`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29058]
### Why should we remove `from_checkpoint`?

`from_checkpoint` is a hack.

We added `from_checkpoint` as a short-term fix. https://github.com/ray-project/ray/pull/26777 introduced framework-specific checkpoints, and with this change, predictors expected users to pass framework-specific checkpoints like `TorchCheckpoint` instead of generic `Checkpoint` objects. The problem was that trainers converted framework-specific checkpoints to generic checkpoints (see https://github.com/ray-project/ray/issues/28134). To avoid this issue, we added `from_checkpoint` -- a method that'd let us convert generic checkpoints back to framework-specific checkpoints.

### What're we waiting for?

#28387 partially addressed the underlying issue. Trainers no longer convert framework-specific checkpoints to generic checkpoints.

That said, we can't deprecate `from_checkpoint` yet. Until #29857 is fixed, users might report generic `Checkpoint` objects. 

### See also 
* #29857 (this is blocking the deprecation)
* https://github.com/ray-project/ray/pull/26651 (motivation for framework-specific checkpoints)
* https://github.com/ray-project/ray/pull/26777 (adds framework-specific checkpoints + `from_checkpoint`)
* #28134 (trainer checkpoint conversion issue)
* #28387 (trainer checkpoint conversion fix)

**Comment by amogkam** [comment]
Thanks @bveeramani, this sgtm!

**Comment by richardliaw** [comment]
Can we close this out @bveeramani ?

**Comment by bveeramani** [comment]
@richardliaw Let me check with @Yard1 and @amogkam. IIRC there was a reason we couldn't do this yet, but I might be misremembering

**Comment by richardliaw** [comment]
Sounds good, please document the reason here when you hear back

**Comment by bveeramani** [comment]
Talked to @Yard1. Let's make `from_checkpoint` a developer API. We can't get rid of it because you can still report generic `Checkpoint`s.
