### ISSUE TITLE
[release][CI] long_running_node_failures

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29050]
### What happened + What you expected to happen

Failed test - https://buildkite.com/ray-project/release-tests-branch/builds/1090#01839fe4-54be-4b86-bd5a-b905e17cfd50

Cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_5sUswHFHfMvMxTn4SudTrjQS?command-history-section=command_history

### Versions / Dependencies

Master

### Reproduction script

As above

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
I've stopped some of the long running tests manually as they were blocking the release testing pipeline so this is not a bug.
