### ISSUE TITLE
`test_no_tasks` seems meaningless

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#2908]
### Describe the problem

I suppose it is a bug because it seems meaningless for a test. It should be `available_resources = ray.global_state.available_resources()` in the test.

If it is not a bug, there should be some comments to explain it.

### Source code / logs

https://github.com/ray-project/ray/blob/715ec1bca541df82c34cd37126e7c4bb2aeb9ed4/python/ray/test/test_global_state.py#L27-L30

**Comment by robertnishihara** [comment]
Yes, you're right about this test. It looks like a bug. @pschafhalter is that right?

**Comment by pschafhalter** [comment]
Right, that's a bug.

**Comment by robertnishihara** [comment]
Fixes #2914.
