### ISSUE TITLE
[rllib] ARS optimizer differs from paper

### ISSUE THREAD

**Issue by whikwon** [ray-project/ray#2909]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.2
- **Python version**: 3.6.3
- **Exact command to reproduce**:

### Describe the problem

In the ars.py code, the model use Adam optimizer for training. When I looked into the [paper](https://arxiv.org/pdf/1803.07055.pdf), SGD was used for training. 

Is there any reason or experimental result for using Adam rather than SGD?

**Comment by ericl** [comment]
I believe this code is directly adapted from the reference implemention cc @eugenevinitsky

**Comment by eugenevinitsky** [comment]
This is a mistake; thank you for catching it. The reference code used SGD as you pointed out, but Evolutionary Strategies used ADAM and that wound up getting copied over.

**Comment by eugenevinitsky** [comment]
@whikwon PR for this will be up shortly
