### ISSUE TITLE
[release][CI] tune_cloud_aws_durable_upload failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29094]
### What happened + What you expected to happen

[Failure build ](https://buildkite.com/ray-project/release-tests-branch/builds/1092#0183a524-1e14-49fa-a040-ed6727b2f7a9)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_fu4pHcR21JMd4D2r7mkXn3uW?command-history-section=command_history)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by matthewdeng** [comment]
@krfricke can I assign this to you?

**Comment by krfricke** [comment]
Retried 10 times so far and never ran into the issue, but continuing to explore...

**Comment by krfricke** [comment]
This is an error in the test script (fixed in #29129). Because the actual tune logic does work, this is not a release blocker.
