### ISSUE TITLE
comment duplicated 

### ISSUE THREAD

**Issue by songpengwei** [ray-project/ray#2910]
https://github.com/ray-project/ray/blob/3a3782c39fc2e75f53515660b866e7cc501b7704/src/common/state/task_table.h#L150

the second `task_table_add_task` may be `task_table_update`?

**Comment by robertnishihara** [comment]
Thanks @songpengwei, you're right, the second `task_table_add_task` should be `task_table_update`. You're welcome to submit a PR fixing this comment if you'd like. However, this code is largely outdated and replaced by the code in https://github.com/ray-project/ray/blob/master/src/ray/gcs/tables.h.

**Comment by songpengwei** [comment]
Thank you, I'm still reading the code after finishing the ray paper, I would be pleasure to contribute some code if it necessary in the future. Then I'll close it.
