### ISSUE TITLE
Ray Train: xgboost training causes OOMs when using scipy.sparse matrices

### ISSUE THREAD

**Issue by shahsmit1** [ray-project/ray#29118]
### What happened + What you expected to happen

Bug: During xgboost training using ray train, the node mem usage continuously increases and there is an OOM. The object store memory is pretty low, the source of the memory increase isn't known. 

Expected behavior: training completes

Logs:
```
2022-10-05 23:57:23,026	WARNING worker.py:1829 -- Warning: The actor GBDTTrainable is very large (18 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.
2022-10-05 23:57:23,123	WARNING util.py:220 -- The `start_trial` operation took 2.046 s, which may be a performance bottleneck.
2022-10-06 00:25:22,311	WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: f5009a0b2acb808416c8769d74b4d40d7f1b059401000000 Worker ID: 87529db22290f1425ab666d214d7354e259a981b414b90604204beb3 Node ID: 3085d388f09bdd820e4644f3e1898ddcec9a77ac69cf19c1d88f80e7 Worker IP address: 10.1.23.63 Worker port: 38407 Worker PID: 14227 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

### Versions / Dependencies

Ray version, installed in notebook 2.0.0. 
Other libraries: 
```
aiohttp==3.8.0
aiosignal==1.2.0
anyio==3.4.0
argon2-cffi==21.1.0
async-timeout==4.0.0
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
backports.zoneinfo==0.2.1
beautifulsoup4==4.9.3
bleach==4.1.0
bokeh==2.4.2
boto3==1.19.10
botocore==1.22.11
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
cgroupspy==0.2.1
chardet==4.0.0
charset-normalizer==2.0.7
click==7.1.2
cloudpickle==2.0.0
colorama==0.4.4
commonmark==0.9.1
conda==4.3.16
cryptography==3.3.2
cycler==0.11.0
Cython==0.29.24
dask==2021.11.2
dask-labextension==5.1.0
dateparser==0.7.6
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
dill==0.3.4
distlib==0.3.6
distributed==2021.11.2
docker==4.1.0
entrypoints==0.3
fastparquet==0.4.1
feedparser==5.2.1
filelock==3.8.0
frozenlist==1.2.0
fsspec==2022.7.1
google-auth==2.3.3
grafanalib==0.6.3
graphviz==0.14.1
grpcio==1.43.0
HeapDict==1.0.1
idna==3.3
importlib-resources==5.4.0
influxdb-client==1.21.0
ipykernel==6.6.0
ipython==7.30.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.1
Jinja2==3.0.3
jmespath==0.10.0
json5==0.9.6
jsonschema==4.2.1
jupyter==1.0.0
jupyter-client==7.1.0
jupyter-console==6.4.0
jupyter-core==4.9.1
jupyter-server==1.12.1
jupyter-server-proxy==3.2.0
jupyterlab==3.2.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
kubernetes==20.13.0
llvmlite==0.36.0
locket==0.2.1
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
memory-profiler==0.60.0
mistune==0.8.4
msgpack==1.0.2
multidict==5.2.0
nbclassic==0.3.4
nbclient==0.5.9
nbconvert==6.3.0
nbformat==5.1.3
nest-asyncio==1.5.4
networkx==2.6.3
nodejs==0.1.1
notebook==6.4.6
numba==0.53.1
numpy==1.21.4
nvidia-ml-py==11.450.51
oauthlib==3.1.1
optional-django==0.1.0
packaging==21.2
pandas==1.0.5
pandocfilters==1.5.0
parso==0.8.3
partd==1.2.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.1
pkg_resources==0.0.0
platformdirs==2.5.2
prometheus-client==0.12.0
prompt-toolkit==3.0.23
protobuf==3.20.1
psutil==5.8.0
ptyprocess==0.7.0
py-spy==0.3.10
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser==2.20
pydantic==1.8.2
Pygments==2.10.0
pygooglenews==0.1.2
Pympler==0.9
pyparsing==2.4.7
PyPDF2==1.26.0
pyrsistent==0.18.0
python-dateutil==2.8.2
python-snappy==0.5.4
pytz==2019.3
PyYAML==5.4.1
pyzmq==22.3.0
qtconsole==5.2.1
QtPy==1.11.2
ray==2.0.0
regex==2021.8.28
requests==2.26.0
requests-oauthlib==1.3.0
rich==10.9.0
rsa==4.7.2
ruamel.yaml==0.17.17
ruamel.yaml.clib==0.2.6
Rx==3.2.0
s3fs==0.4.2
s3transfer==0.5.0
scalene==1.3.12
scipy==1.7.0
Send2Trash==1.8.0
simpervisor==0.4
six==1.16.0
sniffio==1.2.0
snorkelflow @ file:///tmp/tmpn5a61l54/snorkelflow-0.0.0.1664836246-py3-none-any.whl
sortedcontainers==2.4.0
soupsieve==2.2.1
statsd==3.3.0
tabulate==0.8.10
tblib==1.7.0
tenacity==6.3.1
tensorboardX==2.5.1
terminado==0.12.1
testpath==0.5.0
thrift==0.15.0
toml==0.10.2
toolz==0.11.2
tornado==6.1
tqdm==4.64.1
traitlets==5.1.1
typing-extensions==3.10.0.2
tzlocal==3.0
urllib3==1.26.7
virtualenv==20.16.5
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
widgetsnbextension==3.5.2
wrapt==1.14.1
xgboost==1.6.2
xgboost-ray==0.1.10
yarl==1.7.2
zict==2.0.0
zipp==3.6.0
```
Python version: 3.8.0
Instance size: AWS ec2 m5.2xlarge, image: ubuntu

### Reproduction script

[xgboost_ray.pdf](https://github.com/ray-project/ray/files/9727144/xgboost_ray.pdf)
I can provide the X and Y that are used in the notebook via ray slack or other mediums (not able to upload .npz and .npy files here)

### Issue Severity

High: blocking us from onboarding to Ray Train

**Comment by shahsmit1** [comment]
More data on this slack thread: https://ray-distributed.slack.com/archives/C030EQH72GG/p1665016628560519

**Comment by amogkam** [comment]
Hey @shahsmit1 thanks for raising this! How large is your data size? The OOMing is happening due to heap memory being used, not object store memory which explains why you're not seeing object store memory being used much.

The peak heap memory usage for xgboost data ingest is ~3x the data size (you can read more here: https://github.com/ray-project/xgboost_ray#memory-usage) so if your data size is ~10GiB then this OOM might be expected.

**Comment by amogkam** [comment]
also cc @krfricke @Yard1

**Comment by shahsmit1** [comment]
I create a ray dataset from the pandas dataframe using `train_dataset = ray.data.from_pandas(X_df)`, and then dump it as follows: 
```
import pickle
pickled=pickle.dumps(train_dataset)
length_mib = len(pickled) // (1024 * 1024) 
print(length_mib) 
```
The ray dataset size is 18MB. If I dump the dataframe itself directly, then its 863 MB (not sure about the discrepancy). Regardless, both of sizes are way less that 10GiB
```
import pickle
pickled=pickle.dumps(X_df)
length_mib = len(pickled) // (1024 * 1024) 
print(length_mib) 
```
Is there a way I can figure out what is in the heap memory of the ray worker/actor?

**Comment by shahsmit1** [comment]
> The OOMing is happening due to heap memory being used, not object store memory
My understanding was that using ray dataset, the input train dataset is loaded onto the object store and mapped into the shared memory of the actors, so we shouldn't be using heap memory for each of the actors. Is that a wrong assumption? I am following the example here: https://docs.ray.io/en/latest/ray-air/trainer.html#trainer-basics

**Comment by amogkam** [comment]
Ray Datasets are just holding the reference to the actual data, so the size of the dataset object itself will be very small.

But if the dataset size is 863 MB then you definitely should not be OOMing...

**Comment by shahsmit1** [comment]
also, any pointers as to repartitioning the train dataset, or loading subset/chunks of data. Given that in my `ScalingConfig` I set `num_workers` to 3, should I be repartitioning the train dataset or is this handled internally?

**Comment by amogkam** [comment]
> My understanding was that using ray dataset, the input train dataset is loaded onto the object store

That's correct, but we may not always have zero copy reads in all cases. If you are using a Pandas dataframe certain dtypes may not be able to do zero copy reads. Do you mind sharing the columns and the dtypes of your pandas dataframe that's being used to create the Ray Dataset?

**Comment by shahsmit1** [comment]
Sure, attaching it below. Could it be because the columns are sparse, then they are being densified and causing OOMs?
<img width="468" alt="Screen Shot 2022-10-06 at 12 09 48 PM" src="https://user-images.githubusercontent.com/86746407/194398405-cf90711a-2e75-4e5e-b061-920223de97a4.png">

**Comment by shahsmit1** [comment]
Thanks Amog, very much appreciate your help!

**Comment by amogkam** [comment]
Repartitioning happens automatically internally if the number of blocks doesn't equal to the number of training workers.

**Comment by amogkam** [comment]
also cc @jiaodong

**Comment by shahsmit1** [comment]
also, for reference, vanilla xgboost runs fine on the same instance with the same set of inputs

**Comment by shahsmit1** [comment]
I was able to get a proper out of memory error once I scaled the instance size to 64G, seems like xgboost ray densifies the matrices and causes the OOM: `numpy.core._exceptions.MemoryError: Unable to allocate 105. GiB for an array with shape (500000, 28287) and data type int64` . In this case, will there be native support for `scipy.sparse` matrices, since the vanilla xgboost runs in less than 32G of memory, thanks

**Comment by shahsmit1** [comment]
@amogkam do you think support for `scipy.sparse` matrices would be something that is on ray train roadmap? It's a blocker for us since the densification of matrices implies an order of magnitude higher memory usage for distributed xgboost on ray train versus vanilla xgboost, thanks

**Comment by yangs16** [comment]
Any update on this issue? I also encountered the same problem when trying to play with 20newsgroups dataset:

```
import ray
import pandas as pd
from sklearn.datasets import fetch_20newsgroups_vectorized

news = fetch_20newsgroups_vectorized(subset="train")
df = pd.DataFrame.sparse.from_spmatrix(news.data, columns=['fea_%d' % i for i in range(0, news.data.shape[1])])
df['target'] = news.target

ds = ray.data.from_pandas(df)
```

**Comment by amogkam** [comment]
@yangs16 what is the issue you are running into?

**Comment by yangs16** [comment]
When I tried to fit a XGBoost model on 20newsgroups dataset with the following code snippet, it will fail due to memory errors.

`import pandas as pd
from sklearn.datasets import fetch_20newsgroups_vectorized

import ray
from ray.train.xgboost import XGBoostTrainer
from ray.air.config import ScalingConfig

news = fetch_20newsgroups_vectorized(subset="train")
df_train = pd.DataFrame.sparse.from_spmatrix(news.data, columns=news.feature_names)
df_train['target'] = news.target

news = fetch_20newsgroups_vectorized(subset="test")
df_test = pd.DataFrame.sparse.from_spmatrix(news.data, columns=news.feature_names)
df_test['target'] = news.target

ds_train = ray.data.from_pandas(df_train)
ds_test = ray.data.from_pandas(df_test)

trainer = XGBoostTrainer(
    label_column="target",
    params={"objective": "reg:squarederror"},
    scaling_config=ScalingConfig(num_workers=6),
    datasets={"train": ds_train, "valid": ds_test}
)

result = trainer.fit()`

With the native XGBoost library, it works very well.

`import pandas as pd
from sklearn.datasets import fetch_20newsgroups, fetch_20newsgroups_vectorized
import xgboost as xgb

news = fetch_20newsgroups_vectorized(subset='train')
X_train, y_train = news.data, news.target

news = fetch_20newsgroups_vectorized(subset='test')
X_test, y_test = news.data, news.target

dtrain = xgb.DMatrix(X_train, y_train)
dtest = xgb.DMatrix(X_test, y_test)

model = xgb.train(
    params={"objective": "multi:softmax", "num_class": 20, "nthread":6, "eval_metric":["mlogloss", "auc"]},
    dtrain=dtrain,
    evals=[(dtest, "validation"), (dtrain, "train")],
    num_boost_round=200,
    early_stopping_rounds=20
)`

It seems that with the Ray Dataset, the sparse matrix will be converted to a dense matrix, which will raise memory errors.

**Comment by amogkam** [comment]
Thanks for the repro @yangs16!

I looked into it, and looks like the problem does not come from Ray Datasets, but rather from XGBoost+Pandas itself.

You can see a simple example here: https://colab.research.google.com/drive/1SLRman_L4THZlTO22R9X36p48cFnS7Kw?usp=sharing

Creating a DMatrix out of the scipy sparse matrix directly works fine. However, if you convert that scipy matrix to a sparse pandas dataframe, then creating a DMatrix out of this dataframe OOMs, even when there is no Ray involved.

Seems that there is some weird interaction between sparse Pandas dataframes and XGBoost DMatrix in general. Ray Datasets does not densify the sparse pandas dataframe.

You can see my full reproduction here: https://colab.research.google.com/drive/1SLRman_L4THZlTO22R9X36p48cFnS7Kw?usp=sharing

I also posted a question on the XGBoost forum for this: https://discuss.xgboost.ai/t/dmatrix-oom-with-sparse-pandas-dataframe/3096

**Comment by amogkam** [comment]
As a workaround, you should be able to use XGBoostTrainer without Ray Datasets if you want to use scipy sparse matrices directly.
