### ISSUE TITLE
[rfc][AIR] API to fetch results from previously run trial

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#29137]
## Background

Prior to #29083, users did not have an easy way to retrieve tuning results from an existing experiment checkpoint.

While #29083 included a quick fix for this by introducing `Tuner.get_results()`, this change has not been thoroughly discussed, and alternatives have not been fully explored. This RFC tries to rectify this by opening up a discussion.

## Problem/Gap to close

Note: _currently_ refers to the state before #29083 was merged.

**User story 1:** A user runs a hyperparameter tuning run. In a separate script/later job, they need to access the results grid without re-running the tuning.

**Gaps:** This is possible by using `Tuner.restore()` followed by `Tuner.fit()`, which will be a no-op if training succeeded. However, the API calls are misleading.

**User story 2:** A user runs a hyperparameter tuning run, but it fails. The user wants to examine the results that have been reported so far without re-running any trials.

**Variant A:** The user only wants to resume training if no trial reached specific metrics already (e.g. if the maximum accuracy is less than a threshold).

**Gaps:** This is possible if `Tuner.restore(resume_unfinished=True, resume_errored=False, restart_errored=False)` is used. The API is clunky.

**User story 3:** A user runs a hyperparameter tuning run in a class and stored the tuner as `self.tuner`. A different method needs to access the results. At the moment, the user would have to store the retrieved ResultsGrid manually as another property of the class.

**Gaps:** Tuner does not have a way to retrieve results again. Arguably a problem that is easy to work around.

### Tuner.get_results() (see #29083 

In this solution the user uses `Tuner.restore(path)` to restore the tuner object and calls `Tuner.get_results()` to retrieve the latest results object.

Pros:
- Clear API that does not retrigger any runs
- Fulfills all 3 user stories

Cons:
- Users need to restore the full Tuner (which will fetch and deserialize the trainable, tuner, etc), instead of just constructing the ResultsGrid object

### ResultsGrid.from_uri() / .to_uri() / from_directory() / to_directory()

In this solution the user can use `ResultsGrid.to/from_uri/directory` to store and retrieve the results grid object.

Pros:
- Fulfills user stories 1 and 2
- Users don't interact with tuner anymore, but with the results object, which is arguably cleaner

Cons:
- Does not fulfill extension 2A as no Tuner object is available (would have to be restored separately)
- It's not clear if to_uri/directory should move the whole experiment dir including all trials + their checkpoints, or just a shallow metadata results object

## Proposed solution

#29083 solves all user stories in a simple way and is a rather non-invasive change.

In order to support analyzing results without restoring the full Tuner, we can support `ResultsGrid.from_directory/ResultsGrid.from_uri` or alternatively `ResultsGrid(path: Optional[str] = None)` which will only return the results grid object. This should be straightforward to implement as we can just pass the path onto the constructor of ExperimentAnalysis. This second extension would better fulfill user story 1.

cc @richardliaw @matthewdeng @ericl @xwjiang2010 @amogkam

**Comment by xwjiang2010** [comment]
cc @justinvyu

**Comment by richardliaw** [comment]
Doing both seems reasonable to me.

**Comment by amogkam** [comment]
Agreed doing both sounds good. 

A couple points:
- should we have `get_result_grid` be a property instead and called `last_results`?
- We should also add an analogous for Trainer- `last_result`

Regarding the `ResultGrid.to_uri`/`ResultGrid.to_dir` option, we should do the same for a base `Result` object also.
