### ISSUE TITLE
[Datasets] Make `to_tf` work with ragged tensors

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29136]
### Description

Title.

This depends on #29135 

### Use case

This'd let users convert datasets with differently-sized images to a TensorFlow dataset.

**Comment by matthewdeng** [comment]
Is there a workaround in the meantime? e.g. passing in an optional spec

**Comment by bveeramani** [comment]
> Is there a workaround in the meantime? e.g. passing in an optional spec

No. We could add an optional `output_signature` parameter, but I don't think we should introduce a parameter if it's going to be obsolete in a few weeks.
