### ISSUE TITLE
[release][CI] pg_long_running_performance_test

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29167]
### What happened + What you expected to happen

build failure - https://buildkite.com/ray-project/release-tests-branch/builds/1095#0183af7e-99af-4723-9a34-c84ec4160e92

cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_EbtyDQBxpcdnm5bLCFir3p2d

From the log, it's hard for me to see if it's a transient error or not. Creating an issue to check.

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
Looked into this one a bit
- no error in the driver script surfaced and the script gets killed before the timeout. 
- subsequent run successful and retry on the cluster successful. 
- the cluster is not on staging, so no logs available from the errored job unfortunately. 


Wondering if anyone with more context on placement groups could provide some insights?

**Comment by rickyyx** [comment]
Maybe relevant to this https://github.com/ray-project/ray/issues/28160 ?

**Comment by scv119** [comment]
it could be related to https://github.com/ray-project/ray/pull/29055

**Comment by scv119** [comment]
verified it's caused by https://github.com/ray-project/ray/pull/29055 and it's reverted.
