### ISSUE TITLE
[release][CI] inference

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29166]
### What happened + What you expected to happen

build failure - https://buildkite.com/ray-project/release-tests-branch/builds/1095#0183af7e-9945-4d77-b105-30694a258d3a

cluster - https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_8RfP4VztAY9MAENHQcZTTGdq?command-history-section=command_history

```
RuntimeError: CUDA out of memory. Tried to allocate 6.10 GiB (GPU 0; 14.56 GiB total capacity; 1.19 GiB already allocated; 500.50 MiB free; 1.20 GiB reserved in total by PyTorch)
```

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
Could we cherry-pick the PR?

**Comment by c21** [comment]
@rickyyx - yeah will do today.

**Comment by rickyyx** [comment]
Re-open to track [failures](https://buildkite.com/ray-project/release-tests-branch/builds/1114#0183d3c4-b077-47be-b2ac-dd3a7439bfcc) in release test. Close with cherry-pick PR.

**Comment by c21** [comment]
@rickyyx - https://github.com/ray-project/ray/pull/29361 should be ready to merge (only change in nightly test).
