### ISSUE TITLE
[CI][core] Move existing nightly tests from prod env to staging 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29169]
### What happened + What you expected to happen

We should move more tests from prod env to staging to catch any issues as early as possible!

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by clarng** [comment]
Is this blocked still?

**Comment by rickyyx** [comment]
Don't think this is blocked- this could be part of the Nightly test auditing project.
