### ISSUE TITLE
[AIR] DatasetContext values don't get propagated for BatchMapper preprocessors

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#29160]
### What happened + What you expected to happen

DatasetContext allows setting Datasets config values like the target max block size. Normally these are propagated from the driver to all tasks in the Dataset.

However, when using the AIR trainer, context changes made by the driver don't get propagated to the training dataset preprocessor. I think this is likely because the BatchMapper doesn't save the context, so when we pass the BatchMapper to the worker that actually creates the final Dataset, the driver's context values are lost.

### Versions / Dependencies

3.0dev

### Reproduction script

Following script shows that the map task doesn't inherit the DatasetContext set by the driver.

```python
import ray
from ray.data.preprocessors import Chain, BatchMapper
from ray.air.util.check_ingest import DummyTrainer
from ray.air.config import ScalingConfig

dataset = ray.data.range_tensor(500, shape=(80, 80, 4), parallelism=10)

def map_fn(batch):
  ctx = ray.data.context.DatasetContext.get_current()
  print(f"context.target_max_block_size: {ctx.target_max_block_size}")
  return batch * 2

# An example preprocessor chain that just scales all values by 4.0 in two stages.
preprocessor = BatchMapper(map_fn)

ctx = ray.data.context.DatasetContext.get_current()
ctx.target_max_block_size = 100
print(f"Set DatasetContext.target_max_block_size: {ctx.target_max_block_size}")

# Setup the dummy trainer that prints ingest stats.
# Run and print ingest stats.
trainer = DummyTrainer(
    scaling_config=ScalingConfig(num_workers=1, use_gpu=False),
    datasets={"train": dataset},
    preprocessor=preprocessor,
    num_epochs=1,  # Stop after this number of epochs is read.
    prefetch_blocks=1,  # Number of blocks to prefetch when reading data.
    batch_size=None,  # Use whole blocks as batches.
)
trainer.fit()
```

```
...
Set DatasetContext.target_max_block_size: 100
...
(_map_block_nosplit pid=41034) context.target_max_block_size: 536870912
...

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
@c21 can you take a look? Shouldn't `DatasetContext` be global?

**Comment by stephanie-wang** [comment]
Btw, for now I can workaround by calling the BatchMapper directly from the driver instead of passing it as the preprocessor to Train.

**Comment by clarkzinzow** [comment]
@matthewdeng @amogkam I believe this is because the preprocessor transform will be invoked from the Trainer's coordinator actor, right? So the `DatasetContext` that's propagated through to the `.map_batches()` tasks will be the default `DatasetContext` in the actor, rather than the updated `DatasetContext` in the driver.

**Comment by clarkzinzow** [comment]
@matthewdeng @amogkam Any opposition to solving this by capturing the driver-side `DatasetContext` in the `TrainTrainable` class definition closure and setting it (in the actor) in `Trainable.setup()`? https://github.com/ray-project/ray/blob/2b62bba7c4014c8d943b197bf8396df7dd0f82e3/python/ray/train/base_trainer.py#L421-L437

**Comment by amogkam** [comment]
@clarkzinzow @c21 what's the general solution for running Datasets inside other tasks/actors? Not necessarily AIR.

Should DatasetContext be attached to the dataset object when it is serialized/deserialized?

**Comment by amogkam** [comment]
yep @clarkzinzow your suggestion sounds good for AIR Trainers and we should make the change.

but the problem may also occur in other situations so a general solution would probably be best.

**Comment by c21** [comment]
yeah I agree, I think we should have the `DatasetContext` stored inside `Dataset`.

**Comment by clarkzinzow** [comment]
@c21 @amogkam That won't work, the `DatasetContext` needs to be propagated to Ray tasks, which do _not_ get passed the full `Dataset` object since the `Dataset` object contains object references for all data blocks, while Ray tasks typically operate on a single block (or a small subset of blocks, or chunks of a block).

**Comment by vedantroy** [comment]
Does this solve https://github.com/ray-project/ray/issues/29168?
