### ISSUE TITLE
Docker Builds: Differentiate Ray Versions?

### ISSUE THREAD

**Issue by bendemott** [ray-project/ray#29182]
### Description

I can't find a way to easily understand docker labels and ray major versions.

I spent several hours trying to understand if ray releases are `2.0.0` vs `3.0.0` - There's no tag that differentiates.
I don't see a `pypi` release for `3.0.0` yet - so the default install from pypi doesn't work with the most recent docker images, this makes it hard for newcomers - and no obvious way to understand the difference other than arbitrary errors from client/server differences.

### Use case

To find the last `2.0.0` build I had to perform a manual (human) binary search across 300 pages of releases
- The last *2.0.0* build was `rayproject/ray:444415-py39-cpu`

**Comment by krfricke** [comment]
- `rayproject/ray:latest` always points to the latest release
- `rayproject/ray:nightly` points to the latest _master_ build
- E.g. `rayproject/ray:2.0.0` points to the Ray 2.0.0 release
- You can see the latest release on [docs.ray.io](https://docs.ray.io/en/latest/) or on [github](https://github.com/ray-project/ray/releases/)

Version "3.0.0dev0" is a fake version used on master for development. The reason for this is that we need to specify some version, and and we want this version to be larger than the latest release to make sure pip prefers latest master over latest release. 

I'll keep this issue open as we may want to improve our documentation for this.
