### ISSUE TITLE
The training will be stuck

### ISSUE THREAD

**Issue by Stephen-Hao** [ray-project/ray#29197]
### What happened + What you expected to happen

When I run ray version 2.0 on the A10 server, the training will be stuck. How can I solve this problem?
![2nmQpDdKUC](https://user-images.githubusercontent.com/35420905/194684889-34665636-dedb-41dd-a9f4-391d46b401ff.jpg)

**Comment by richardliaw** [comment]
Hi @Stephen-Hao can you provide a reproduction script and a description of your cluster?
