### ISSUE TITLE
Silent ray exec failure?

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#2919]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.12
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.1
- **Python version**: 3.5.2
- **Exact command to reproduce**: N/A

### Describe the problem

Using ray exec I run the following command within a tmux window:
ray exec ray_autoscale.yaml "python flow/flow/benchmarks/rllib/ars_runner.py" --start --stop --cluster-name=test3
If I now close my laptop, at some point this will simply stop running without printing any errors. However, if I ssh onto the machine and run it from a tmux window there and exit, then the script will complete all 500 iterations

### Source code / logs

None

**Comment by ericl** [comment]
Doesn't closing your laptop hang up the connection and cancel the command?

I think you need to `exec --tmux` to detach it from your laptop.

**Comment by eugenevinitsky** [comment]
Ah perfect, thanks!
