### ISSUE TITLE
[Datasets] Can't import `read_tfrecords`

### ISSUE THREAD

**Issue by AmirBFar** [ray-project/ray#29201]
Hi, I have been getting `ImportError: cannot import name 'read_tfrecords' from 'ray.data' (.../venv/lib/python3.9/site-packages/ray/data/__init__.py)` when importing `read_tfrecords`. Any idea why is this happening?

**Comment by bveeramani** [comment]
Hey @AmirBFar, thanks for opening an issue! Could you tell us what version of Ray you're using? Also, could you share the full traceback?

**Comment by AmirBFar** [comment]
Hey @bveeramani . I am using 3.0.0.dev0. The full traceback is
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [38], in <cell line: 1>()
----> 1 from ray.data import read_tfrecords

ImportError: cannot import name 'read_tfrecords' from 'ray.data' (/usr/local/share/sciencebox/venv/lib/python3.9/site-packages/ray/data/__init__.py)`

I can definitely see `read_tfrecords` in `__init__.py` inside `__all__`.

**Comment by bveeramani** [comment]
Hmm...weird. Could you run this code snippet and let me know what you get?

```
import ray
print(ray.__commit__)
```

**Comment by AmirBFar** [comment]
`cba26cc83f6b5b8a2ff166594a65cb74c0ec8740`

**Comment by bveeramani** [comment]
Looks like you’re using a version of Ray from August 18 (https://github.com/ray-project/ray/pull/27994), but `read_tfrecords` was added in September (https://github.com/ray-project/ray/pull/28430). Could you try upgrading your Ray nightly and see if the error persists?

**Comment by AmirBFar** [comment]
I am trying to install the September commit with

`pip install https://s3-us-west-2.amazonaws.com/ray-wheels/master/e84f9a451b190d5e244cc73c15c662160727a4b7/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl`

and I get

`ERROR: HTTP error 404 while getting https://s3-us-west-2.amazonaws.com/ray-wheels/master/e84f9a451b190d5e244cc73c15c662160727a4b7/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl
ERROR: Could not install requirement ray==3.0.0.dev0 from https://s3-us-west-2.amazonaws.com/ray-wheels/master/e84f9a451b190d5e244cc73c15c662160727a4b7/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://s3-us-west-2.amazonaws.com/ray-wheels/master/e84f9a451b190d5e244cc73c15c662160727a4b7/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl for URL https://s3-us-west-2.amazonaws.com/ray-wheels/master/e84f9a451b190d5e244cc73c15c662160727a4b7/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl`

Any idea why is this happening?

**Comment by bveeramani** [comment]
Hmm...not sure. Maybe our documentation is out of date? Your install command looks okay to me.

I'm out of the office right now, but I can look into it when I get back next week.

In the mean time, is there any reason why you can't install the latest nightly?
```
pip uninstall -y ray
pip install "ray[data]" @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl
```

**Comment by bveeramani** [comment]
I think this is resolved? Feel free to re-open if there's more.
