### ISSUE TITLE
[Air|Tune] Ray 2.0 class-based training function support. 

### ISSUE THREAD

**Issue by Tonyhao96** [ray-project/ray#29209]
### Description

In Ray 2.0, we need to define PyTorch training function to apply `TorchTrainer` in below form:

```python
def train_loop_per_worker():
            ...

trainer = TorchTrainer(train_loop_per_worker)

```

But I need to obtain the model information and do some modifications (e.g., fusion) to the model during training. So how can I get the model from the function?

Seems `TrainingOperator` in Ray 1.0 can support my requirement (example below). Does Ray 2.0 plan to support class-based training definition form in the future?

```python
class TorchTrainingOperator(TrainingOperator):
    @override(TrainingOperator)
    def setup(self, config):
        # Create model.
        model = ResNet18(config)
        ...

        # Register all components.
        self.model, self.optimizer, self.criterion, self.scheduler = \
            self.register(models=model, optimizers=optimizer,
                          criterion=criterion, schedulers=scheduler)
        self.register_data(
            train_loader=train_loader, validation_loader=validation_loader)
```

### Use case

Model optimization during Tune process

**Comment by Yard1** [comment]
Is checkpointing the model using `TorchCheckpoint` sufficient for your use case?
