### ISSUE TITLE
[Ray Clusters on Azure] Specifying IP space and VNet info inside yaml config  

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#29215]
### Description

For now, to spin up a ray cluster on azure, we cannot pass in specific vnet / ip space information, based on this example (https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/azure/example-full.yaml) from the offical doc, which creates a problem for user permission constraints (e.g. cannot assign roles etc.).

Is there any workaround on this? 

### Use case

Launching clusters on Azure w/i a corporate setup where the users don't have full permissions.

**Comment by richardliaw** [comment]
@gramhagen could you take a look at this?

**Comment by gramhagen** [comment]
the head node uses a managed identity to create cluster nodes, so we need to be able to assign a contributor role for that identity. 

there are two typical workarounds
1. have an admin with required permissions deploy the cluster and users connect to deployed cluster
2. create a resource group and grant users necessary permissions for that resource group so they can deploy

**Comment by mlguruz** [comment]
> the head node uses a managed identity to create cluster nodes, so we need to be able to assign a contributor role for that identity.
> 
> there are two typical workarounds
> 
> 1. have an admin with required permissions deploy the cluster and users connect to deployed cluster
> 2. create a resource group and grant users necessary permissions for that resource group so they can deploy

Thank you for the quick reply!
So to be more accurate, the problem we're faced is the following:
"We want to use Ray using the yaml script, but we want to use a provate ip address space that we have defined. 
We connect to Azure via a Directconnect, and the azure account is blocked from the internet. 
So we need to create the Ray cluster, within a specific vnet (which already has a predefined ipspace for the head / nodes to use.). We would also like to specify a custom image for the head / nodes to use."

Is there anyway for us to can we specify an alternate image / location inside the yaml?

**Comment by gramhagen** [comment]
the easiest option would be to deploy as usual and peer the new vnet to your existing vnet.
there are two options you might want to adjust in the provider section of the yaml:
`use_internal_ips: True`
`subnet_mask: 10.0.0.0/16` adjust to satisfy allowable range when peering

if that doesn't work for you then you will need to modify the functionality of the python code and/or arm templates. (this will also be needed to provide a custom image).
easiest way to do that is pip install ray, find the location of the installed python / json files in your python environment and make necessary modifications.

ray/autoscaler/_private/_azure/azure-config-template.json is the arm template that controls creating the msi, nsg, and vnet. You can remove pre-existing resources from the resources section (just make sure you have hardcoded values for the variables that are returned at from the outputs section) 

ray/autoscaler/_private/_azure/azure-vm-template.json is the arm template for the vms (both head and worker nodes) you'll need to adjust the virtualMachines resource to point to your custom image. There's a variety of ways to reference an image so it will depend on how you are publishing it. I'd suggest using Azure Compute Gallery and adding the resource id to the image section.

sorry there's no easier way to override these things that I can think of.

**Comment by gramhagen** [comment]
> is it possible to have a `CustomAzureNodeProvider` and override some of the functions?

hmm, actually there does seem to be support for an 'external' node provider, see this line: https://github.com/ray-project/ray/blob/44fc6a36e5228a50f4bafe126c67ad73d78486eb/python/ray/autoscaler/_private/providers.py#L143

I think the provider section of the yaml would look something like
```
provider:
  type: external
  module: my_package.CustomAzureNodeProvider
```

i've never used this though, so let me know if that works.

**Comment by mlguruz** [comment]
> > is it possible to have a `CustomAzureNodeProvider` and override some of the functions?
> 
> hmm, actually there does seem to be support for an 'external' node provider, see this line:
> 
> https://github.com/ray-project/ray/blob/44fc6a36e5228a50f4bafe126c67ad73d78486eb/python/ray/autoscaler/_private/providers.py#L143
> 
> I think the provider section of the yaml would look something like
> 
> ```
> provider:
>   type: external
>   module: my_package.CustomAzureNodeProvider
> ```
> 
> i've never used this though, so let me know if that works.

Nice! Let me try that. 
I'm thinking of subclassing with a `CustomAzureNodeProvider` and modify the block below which is where the `.json` file is loaded:

```
  # load the template file
  current_path = Path(__file__).parent
  template_path = current_path.joinpath("azure-config-template.json")
  with open(template_path, "r") as template_fp:
      template = json.load(template_fp)
```
...although I don't see where the `azure-vm-template.json` file is loaded. Is it used at all? 

Also, regarding this output section:
```
    "outputs": {
        "publicIp": {
            "type": "array",
            "copy": {
                "count": "[parameters('vmCount')]",
                "input": "[reference(concat(variables('publicIpAddressName'), copyIndex())).ipAddress]"
            },
            "condition": "[parameters('provisionPublicIp')]"
        },
        "privateIp": {
            "type": "array",
            "copy": {
                "count": "[parameters('vmCount')]",
                "input": "[reference(concat(variables('networkInterfaceName'), copyIndex())).ipConfigurations[0].properties.privateIPAddress]"
            }
        }
    }
```
, how should I modify it to make it work w/ my custom vnet env etc.? Should I delete the public section and only keep the private one? 

Really appreciate your help!

**Comment by gramhagen** [comment]
> Nice! Let me try that. I'm thinking of subclassing with a `CustomAzureNodeProvider` and modify the block below which is where the `.json` file is loaded:
> 
> ```
>   # load the template file
>   current_path = Path(__file__).parent
>   template_path = current_path.joinpath("azure-config-template.json")
>   with open(template_path, "r") as template_fp:
>       template = json.load(template_fp)
> ```
> 
> ...although I don't see where the `azure-vm-template.json` file is loaded. Is it used at all?

these lines are from the config.py, the vm template is loaded in the node_provider.py module: https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/node_provider.py#L214

there's a static method at the bottom of that which calls bootstrap_azure, you will want to override that function to do your own thing during cluster setup.

> 
> Also, regarding this output section:
> 
> ```
>     "outputs": {
>         "publicIp": {
>             "type": "array",
>             "copy": {
>                 "count": "[parameters('vmCount')]",
>                 "input": "[reference(concat(variables('publicIpAddressName'), copyIndex())).ipAddress]"
>             },
>             "condition": "[parameters('provisionPublicIp')]"
>         },
>         "privateIp": {
>             "type": "array",
>             "copy": {
>                 "count": "[parameters('vmCount')]",
>                 "input": "[reference(concat(variables('networkInterfaceName'), copyIndex())).ipConfigurations[0].properties.privateIPAddress]"
>             }
>         }
>     }
> ```
> 
> , how should I modify it to make it work w/ my custom vnet env etc.? Should I delete the public section and only keep the private one?
> 
> Really appreciate your help!

you can keep that as is, and set `use_internal_ips: True` in the provider section of the yaml. That will not create any public ips and just use the private ip space.

**Comment by mlguruz** [comment]
> 



> > Nice! Let me try that. I'm thinking of subclassing with a `CustomAzureNodeProvider` and modify the block below which is where the `.json` file is loaded:
> > ```
> >   # load the template file
> >   current_path = Path(__file__).parent
> >   template_path = current_path.joinpath("azure-config-template.json")
> >   with open(template_path, "r") as template_fp:
> >       template = json.load(template_fp)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...although I don't see where the `azure-vm-template.json` file is loaded. Is it used at all?
> 
> these lines are from the config.py, the vm template is loaded in the node_provider.py module:
> 
> https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/node_provider.py#L214
> 
> there's a static method at the bottom of that which calls bootstrap_azure, you will want to override that function to do your own thing during cluster setup.
> 
> > Also, regarding this output section:
> > ```
> >     "outputs": {
> >         "publicIp": {
> >             "type": "array",
> >             "copy": {
> >                 "count": "[parameters('vmCount')]",
> >                 "input": "[reference(concat(variables('publicIpAddressName'), copyIndex())).ipAddress]"
> >             },
> >             "condition": "[parameters('provisionPublicIp')]"
> >         },
> >         "privateIp": {
> >             "type": "array",
> >             "copy": {
> >                 "count": "[parameters('vmCount')]",
> >                 "input": "[reference(concat(variables('networkInterfaceName'), copyIndex())).ipConfigurations[0].properties.privateIPAddress]"
> >             }
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > , how should I modify it to make it work w/ my custom vnet env etc.? Should I delete the public section and only keep the private one?
> > Really appreciate your help!
> 
> you can keep that as is, and set `use_internal_ips: True` in the provider section of the yaml. That will not create any public ips and just use the private ip space.

I was able to create a cluster using all my custom resources and stuff, running `ray up` using my custom node provider. 

However, I was getting this error:
```
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/click/core.py", line 1128, in __call__                                                                                                                  [0/10671]
    return self.main(*args, **kwargs)                 
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/click/core.py", line 754, in invoke 
    return __callback(*args, **kwargs)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/scripts/scripts.py", line 1206, in up
    create_or_update_cluster(
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 276, in create_or_update_cluster
    get_or_create_head_node(
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/commands.py", line 641, in get_or_create_head_node
    nodes = provider.non_terminated_nodes(head_node_tags)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 145, in non_terminated_nodes
    nodes = self._get_filtered_nodes(tag_filters=tag_filters)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 38, in wrapper
    return f(self, *args, **kwargs)
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 83, in _get_filtered_nodes
    nodes = [self._extract_metadata(vm) for vm in filter(match_tags, vms)]
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 83, in <listcomp>
    nodes = [self._extract_metadata(vm) for vm in filter(match_tags, vms)]
  File "/home/david.zhang/projects/zstar/envs/current_linux38/lib/python3.8/site-packages/ray/autoscaler/_private/_azure/node_provider.py", line 75, in match_tags
    if vm.tags.get(k) != v:
AttributeError: 'NoneType' object has no attribute 'get'
```
Do I need to specify the `tags` somewhere in the two json configs?

**Comment by gramhagen** [comment]
yes, vm tags are passed in here: https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/node_provider.py#L231

and used in the template here: https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/azure-vm-template.json#L189

**Comment by mlguruz** [comment]
> yes, vm tags are passed in here:
> 
> https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/node_provider.py#L231
> 
> and used in the template here:
> 
> https://github.com/ray-project/ray/blob/eacc763c84d47c9c5b86b26a32fd62c685be84e6/python/ray/autoscaler/_private/_azure/azure-vm-template.json#L189

I move forward further thanks to your help (really appreciate!), but got SSH errors onto *head node* now.
```
<1/1> Setting up head node                                  
  Prepared bootstrap config                                                                                                  
  New status: waiting-for-ssh                                                                                                
  [1/7] Waiting for SSH to become available                                                                                  
    Running `uptime` as a test.                                                                                              
    Fetched IP: 10.24.9.4                                                                                                    
ssh: connect to host 10.24.9.4 port 22: Connection timed out                                                                 
    SSH still not available (SSH command failed.), retrying in 5 seconds.
```

I read the the autoscaler code and compared my custom json w/ the default ones (i.e. `azure-vm-template` and `azure-config-template`). 
It seems that `azure-vm-template` uses this `"Microsoft.Compute/virtualMachines"` block as a template for generating / scaling workers, but can I ask which part handles the generation of head node specifically? 

I do see the `yaml` file distinguishes worker node from head node, but the default json templates doesn't seem to treat head and worker differently. 

We do have slightly different subnet ips for head and workers.
```
"subnetWorkers": "10.24.9.0/24",
"subnetHead": "10.24.8.0/24",
```

Do you know how to pass in those, either from yaml (as parameters) or directly into json?

**Comment by gramhagen** [comment]
https://github.com/ray-project/ray/blob/acd8fbaa95e5fdb8498a4522e81f9be368b70178/python/ray/autoscaler/_private/commands.py#L739 is where the head node is created, it uses the same json template as the worker nodes, but passes the head node config parameters from the yaml.
Right now the subnet mask is defined in the provider section of the yaml, but if you need separate options for the head node and workers you will need to add that into the azure_arm_parameters section of the yaml instead (under available_node_types->node_config). Then update the node_provider python code and json to pass those in similar to how vmTags and other params are managed.

**Comment by mlguruz** [comment]
> https://github.com/ray-project/ray/blob/acd8fbaa95e5fdb8498a4522e81f9be368b70178/python/ray/autoscaler/_private/commands.py#L739
> 
> is where the head node is created, it uses the same json template as the worker nodes, but passes the head node config parameters from the yaml.
> Right now the subnet mask is defined in the provider section of the yaml, but if you need separate options for the head node and workers you will need to add that into the azure_arm_parameters section of the yaml instead (under available_node_types->node_config). Then update the node_provider python code and json to pass those in similar to how vmTags and other params are managed.

Got it. This is super helpful. Let me try that. 

Btw - I'm on 3.0.0-dev, and I see there are a few changes from 2.0. I assume the interfaces for 3.0.0dev is where we are going?

**Comment by mlguruz** [comment]
> https://github.com/ray-project/ray/blob/acd8fbaa95e5fdb8498a4522e81f9be368b70178/python/ray/autoscaler/_private/commands.py#L739
> 
> is where the head node is created, it uses the same json template as the worker nodes, but passes the head node config parameters from the yaml.
> Right now the subnet mask is defined in the provider section of the yaml, but if you need separate options for the head node and workers you will need to add that into the azure_arm_parameters section of the yaml instead (under available_node_types->node_config). Then update the node_provider python code and json to pass those in similar to how vmTags and other params are managed.

Ok - I've managed to successfully launch & kill the head node using our specific network setup thanks to your help!!

The current issue I'm having is the autoscaling failed on Authentication:

The log I see when I do `ray monitor XXX.yaml` is the following:
```
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send                                                                                                                                                                    [755/45338]
    response = self.next.send(request)                                                                                                                                                                                                                                                
  [Previous line repeated 1 more time]                                                                                                                                                                                                                                                
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send                                                                                                                                                                 
    response = self.next.send(request)                                                                                                                                                                                                                                                
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 446, in send                                                                                                                                                                    
    response = self.next.send(request)                                                                                                                                                                                                                                                
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 116, in send                                                                                                                                                           
    self.on_request(request)                                                                                                                                                                                                                                                          
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request                                                                                                                                                      
    self._token = self._credential.get_token(*self._scopes)                                                                                                                                                                                                                           
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/identity/_credentials/default.py", line 172, in get_token                                                                                                                                                               
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)                                                                                                                                                                                                           
  File "/home/ray/anaconda3/lib/python3.8/site-packages/azure/identity/_credentials/chained.py", line 108, in get_token                                                                                                                                                               
    raise ClientAuthenticationError(message=message)                                                                                                                                                                                                                                  
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.                                                                                                                                                     
Attempted credentials:                                                                                                                                                                                                                                                                
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.                                                                                                                                                      
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.                                                                                                                                                                             
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.                                                                                                                               
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.                                                                                                                                                                                         
        AzureCliCredential: Azure CLI not found on path                                                                                                                                                                                                                               
        AzurePowerShellCredential: PowerShell is not installed                                                                             
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.                                                                                                                              
2022-10-14 06:44:40,288 WARNING chained.py:107 -- DefaultAzureCredential failed to retrieve a token from the included credentials.                                                                                                                                                    
Attempted credentials:                                               
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.                                                                                                                                                      
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.                                  
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.                                                                                                                               
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.                                              
        AzureCliCredential: Azure CLI not found on path              
        AzurePowerShellCredential: PowerShell is not installed                                                                             
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.                                                                                                                              
2022-10-14 06:44:40,289 ERROR autoscaler.py:359 -- StandardAutoscaler: Error during autoscaling.
```
It seems that I'm missing some Authentication variable setup? 
b/c I can't re-create msi/vnet/..., I'm not sure if those authentication tokens are set during that creation process...
if not, if there anyway I could pass-in? 

I'm sorry for this back-and-forth but there's really little out there for my situation. 
Once again, really appreciate your help!

**Comment by mlguruz** [comment]
> there are other ways to do this, if you have an existing service principal or managed identity you could re-use that, but identity mgmt is honestly the most painful (and least documented) part of automated resource deployment. so you'll have to do a lot of digging and testing on your own if you want to go a different way.

I see - so far I created a managed identity and may I ask which one of these ID's I should be using for MSI:
- MSI name 
- Client ID
- Object (principal) ID

thank you so much!

**Comment by mlguruz** [comment]
> I see - so far I created a managed identity and may I ask which one of these ID's I should be using for MSI:
> 
> * MSI name
> * Client ID
> * Object (principal) ID
> 
> thank you so much!

I got it - although I see in your template, you're asking for direct input of resource id:
```
        "msi": {
            "type": "string",
            "metadata": {
                "description": "Managed service identity resource id."
            }
        },
        "nsg": {
            "type": "string",
            "metadata": {
                "description": "Network security group resource id."
            }
        }
```
maybe could just set that as "name", and then in the resource section do `resourceId(...)` ?

**Comment by mlguruz** [comment]
@gramhagen 

I was able to move even further so I think the MSI is working. 

I got below permission error. Does it mean I don't have enough permission? Thanks!!

```
azure.core.exceptions.HttpResponseError: (AuthorizationFailed) The client '0fe12cd5-734d-4425-9083-3ac7c27499a5' with object id '0fe12cd5-734d-4425-9083-3ac7c27499a5' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptio
ns/d0843096-edb1-4da9-a29f-5c2d059cc3ff/resourceGroups/ZSTAR/providers/Microsoft.Compute' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed           
Message: The client '0fe12cd5-734d-4425-9083-3ac7c27499a5' with object id '0fe12cd5-734d-4425-9083-3ac7c27499a5' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/d0843096-edb1-4da9-a29f-5c2d059cc3ff/resourceGroups
/ZSTAR/providers/Microsoft.Compute' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

**Comment by gramhagen** [comment]
yeah, i usually grant contributor scope over the resource group to the msi, you can have more fine-grained controls but I don't know the full extent that's required so you can adjust and iterate a bit to test that out.

**Comment by mlguruz** [comment]
> yeah, i usually grant contributor scope over the resource group to the msi, you can have more fine-grained controls but I don't know the full extent that's required so you can adjust and iterate a bit to test that out.

Got it - let me work on it now. Super helpful!!

**Comment by mlguruz** [comment]
> yeah, i usually grant contributor scope over the resource group to the msi, you can have more fine-grained controls but I don't know the full extent that's required so you can adjust and iterate a bit to test that out.

Good morning 

Thank you again for the great help! 

Following your instructions, I eventually get autoscaling working on our custom Vnet env after modifying (hacking) the templates and `config.py`/`node_provider.py` quite a bit. Once again, truly appreciate your great advice! 

There are, however, a few areas where either my current workaround isn't perfect (or simply hacky), or, areas we eventually hope to get to, that I'm hoping to get your opinions on:

- since `config.py` is changed (`node_provider.py` is fine as I can subclass and there is an entry point from `.yaml`), to make head -> workers autoscaling work, I had to specify custom cmds to ...
1. sync up my custom `_azure` subdirs to head from launcher node
2. install ray library on head
3. remove `_azure` subdir in ray library
4. symlink my custom `_azure` that I sync'ed to head to the head ray library 
5. then launch workers 

... it's certainly hacky, and I'm not sure what you think would be a better way to handle this?

- so far everything is not happening in docker yet, but that's where we're moving to eventually. I can kinda replicate my hacky practice above in docker I think, but again, if there are more robust way to do this, I would love to. 
- we have Azure NetApp setup, and we definitely wanna access data from netapp directly when running workers. Do you know how we could mount the netapp volume onto the remote Azure instances? or one step further, how to mount NetApp volume to docker containers (--mount?)

Looking forward to your comments & thoughts. Thanks!

**Comment by gramhagen** [comment]
yeah, i think leveraging kubernetes will hopefully make this easier to deploy across cloud, as long as Azure supports the necessary fundamental kubernetes functionality, the configuration _shouldn't_ really be different, (other than skus and what not).

i'd love to test out the docker setup on AKS, but I haven't had a lot of time to experiment. I think this is the right direction to go however and will lead to less maintenance and more shared / standardized support across clouds. So I'm glad you were able to hack the necessary changes, but I'm not sure which parts could be leveraged more broadly.

i don't have a lot of suggestions for mounting volumes other than adding worker node configuration steps or a custom image that already has the mount applied?

i'm curious if you think there are aspects that would be useful to pull back in to the main codebase, or changes that would make it easier to customize?

**Comment by mlguruz** [comment]
> yeah, i think leveraging kubernetes will hopefully make this easier to deploy across cloud, as long as Azure supports the necessary fundamental kubernetes functionality, the configuration _shouldn't_ really be different, (other than skus and what not).

that makes sense, and we're making efforts in that direction. 

> i'd love to test out the docker setup on AKS, but I haven't had a lot of time to experiment. I think this is the right direction to go however and will lead to less maintenance and more shared / standardized support across clouds. So I'm glad you were able to hack the necessary changes, but I'm not sure which parts could be leveraged more broadly.

yeah sys & py versioning is critical to me so docker is a natural candidate.

> i don't have a lot of suggestions for mounting volumes other than adding worker node configuration steps or a custom image that already has the mount applied?
> 
> i'm curious if you think there are aspects that would be useful to pull back in to the main codebase, or changes that would make it easier to customize?

absolutely. through out the pass wk or so customization process, below is what I hope we could expose to pub:
1. msi - I struggled a lot on making sure the managed identity has the correct perms and stuff. also, as of 3.0.0dev, I see this is exposed as a "parameter" expecting the entire resource id. I think we should prob update the official doc on this, as if i'm not mistaken, for any custom vnet, this is a  required input.
2. subnet - different subnets for head & worker - so far honestly, I don't know how to separate this two. For now, I'm pointing to one spot. Maybe we could consider relaxing and allowing different subnets for head and workers 
3. nsg - this part is easier vs msi, but w/o your help, it's gonna take me way longer to figure out the right input and where to specify those inputs. 

as an update, I'm testing out using our own custom azure machine image w/ netapp access mounted. 
Currently I'm getting error:
```
Exception Details:      (InvalidParameter) The following list of images referenced from the deployment template are not found: Publisher: XXXX, Offer: XXXX, Sku: XXXX, Version: 2.0.0. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage for instructions on finding available images.
```
I assume in the codebase we assume downloading from marketplace? 
in my situation where I'm using customized machine image, what additional values I should specify to make it accessible?

I've set the values for image `publisher/offer/sku/version`, but I got stuck on that error above. 

Thanks!

**Comment by gramhagen** [comment]
if you've created your own image and are hosting it using azure compute gallery it will have an id, you can use that in the imagereference field of the vm template instead of publisher/offer/sku/version
https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?pivots=deployment-language-arm-template

this is definitely something that should be exposed so people can use their own images
