### ISSUE TITLE
[Ray DAG] Incorrect number of actors when invoke `execute()` multiple times.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#29217]
### What happened + What you expected to happen

```python
a = MyActor.bind()
x = a.f.bind().execute()
y = a.f.bind().execute()
print(f"{ray.get([x, y])}")
```
2 actors will be created.

### Versions / Dependencies

all

### Reproduction script

```python
a = MyActor.bind()
x = a.f.bind().execute()
y = a.f.bind().execute()
print(f"{ray.get([x, y])}")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jovany-wang** [comment]
@jiaodong Please help triage. @simon-mo CC as well.

**Comment by jovany-wang** [comment]
A same issue https://github.com/ray-project/ray/issues/24198

**Comment by jiaodong** [comment]
@jovany-wang this is expected because your script calls `.execute()` twice, and we don't preserve or re-use actors across distinct DAG invocations.

Actor is re-used for single invocation like this:

```python
import ray

@ray.remote
class MyActor:
    def __init__(self):
        print("hiii")

    def f(self):
        return 1

@ray.remote
def func(x, y):
    return x + y

a = MyActor.bind()
x = a.f.bind()
y = a.f.bind()
dag = func.bind(x, y)
print(f"{ray.get(dag.execute())}")
"""Output 
2
(MyActor pid=56772) hiii
"""
```

**Comment by jovany-wang** [comment]
Any motivation that we don't reuse the actor or node? or is it possible to flag on when we need reuse the dag node?

For the iterations of training, if we execute at the end of the DAG, it‘s significantly inefficient because we need to submit around 10K tasks: 
```python
epochs = 1000
steps = 100

model = MyModel()

for epoch in epochs:
    for step in steps:
        model.train.bind()
    w = model.get_w.bind()
    w_mean = np.mean.bind(w1, w2, ...)
    model.set_w(w_mean)

xxx.execute() # TO SLOW
```

What I'd like looks like:

```python
epochs = 1000
steps = 100

model = MyModel()

for epoch in epochs:
    for step in steps:
        model.train.bind()
    w = model.get_w.bind()
    w_mean = np.mean.bind(w1, w2, ...)
    model.set_w(w_mean).execute()    # Submit around 10 tasks.
```

**Comment by jiaodong** [comment]
Well it's just not a critical feature for its initial design and implementation, but can be added a new feature if we need to, such as long running actors for serving. Ray Tune also has similar setup to reuse actors across multiple runs.

**Comment by jovany-wang** [comment]
Replaced in #29247
