### ISSUE TITLE
[Tune] Ray Tune Gave Improper Warning about `checkpoint_dir`

### ISSUE THREAD

**Issue by yinweisu** [ray-project/ray#29216]
### What happened + What you expected to happen

I got the warning of having checkpoint in the trainable_func parameter
```bash
/home/ubuntu/anaconda3/envs/ag_dev/lib/python3.7/site-packages/ray/tune/trainable/function_trainable.py:644: DeprecationWarning: `checkpoint_dir` in `func(config, checkpoint_dir)` is being deprecated. To save and load checkpoint in trainable functions, please use the `ray.air.session` API:

from ray.air import session

def train(config):
    # ...
    session.report({"metric": metric}, checkpoint=checkpoint)

For more information please see https://docs.ray.io/en/master/ray-air/key-concepts.html#session
```
I then removed it and migrated to session.report() with checkpoint. But then I got warning of not using checkpoint_dir.
```
WARNING function_trainable.py:620 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)
```

Expected Behavior:
There shouldn't be a warning

Our use case wrap ray inside and we don't want user to see this warning. This warning would be confusing to the user. Wonder how can I get rid of it or just suppress the warning?

### Versions / Dependencies

Ray 2.0
Ubuntu

### Reproduction script

```python
from ray.air import session
from ray import tune
from ray import air

def objective(x, a, b):  # Define an objective function.
    return a * (x ** 0.5) + b


def model_trial(config, c):  # Pass a "config" dictionary into your trainable.
    from ray.air.checkpoint import Checkpoint

    for x in range(20):  # "Train" for 20 iterations and compute intermediate scores.
        score = objective(x, config["a"], config["b"])

        session.report({"score": score}, checkpoint = None) # Send the score to Tune.

# Pass in a Trainable class or function, along with a search space "config".
tuner = tune.Tuner(
    tune.with_parameters(
        tune.with_resources(model_trial, {"CPU": 1}),
        c=1
    ),
    param_space={"a": 2, "b": 4},
    tune_config=tune.TuneConfig(
        metric='score',
        mode='min',
    ),
)

results = tuner.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
@justinvyu can I assign you to this one? Should be a quick fix

**Comment by justinvyu** [comment]
Yep, can take it on.

**Comment by yinweisu** [comment]
Any workaround I can have to suppress the warning for now?

**Comment by justinvyu** [comment]
Hi @yinweisu, the warning is indeed incorrect and shouldn't affect anything. The PR above should fix remove the warning, feel free to ignore it in the meantime.

**Comment by yinweisu** [comment]
Hi @justinvyu, I understand the warning won't affect anything. However, we wrap ray tune inside our package, and the warning could be very confusing to the user. It would be better if we could suppress it.

**Comment by justinvyu** [comment]
Got it, I misunderstood. You can try setting the logging level within `ray.init(logging_level=logging.ERROR)` to suppress all warnings/info logs (will only print for errors).
