### ISSUE TITLE
[RFC] [AIR] Batch size for preprocessor transforms

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#29229]
## User workflow
**Workflow 1**: I am doing GPU prediction. I also have a preprocessor that has high heap memory pressure leading to OOMs with too much parallelism or large batch sizes. I want to either decrease my batch size for preprocessing, or reduce my preprocessing parallelism by requesting more CPUs for each `map_batches` task.

**Workflow 1, variant 1**: Same as above, except my GRAM is a lot lower than RAM. So I need to use a smaller batch size for prediction than for preprocessing.

**Workflow 2**: I am doing training and am passing in a Preprocessor to my Trainer. Same as for prediction- my UDF has high heap memory pressure leading to OOMs with the default batch size. I would like to decrease my batch size to prevent OOMs.

## Current State
**Prediction**:
When doing GPU prediction with CPU preprocessing, these two stages cannot be fused as each operation has different resource requirements. Currently, users can configure prediction (things like batch size, num resources per task/actor), but for preprocessing, the default args for `map_batches` are used and cannot be configured. This forces a batch size of 4096 which may be large for certain preprocessors.

https://github.com/ray-project/ray/blob/master/python/ray/train/batch_predictor.py#L226 

**Training**:
We call `preprocessor.transform` which calls `dataset.map_batches` with the default batch size of 4096. There is no way to configure this. 

https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessor.py#L253
https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessor.py#L255

## Proposal
Make preprocessing batch size configurable.

### Option 1: Configured at higher level Trainer and BatchPredictor
Add a `batch_size` arg to `Preprocessor.transform`.

Add configuration options at the `Trainer` and `BatchPredictor` level which will forward to `Preprocessor.transform`.

More concretely:
1. Add a `override_preprocess_batch_size` arg to `BatchPredictor.predict` to use as the arguments for Preprocessing `map_batches`. If not doing GPU prediction, then this arg is ignored as preprocessing+prediction are fused into a single stage. If not specified, the same batch size will be used for prediction and preprocessing.
2. For API consistency we also should introduce an equivalent way to configure preprocess batch size for training. We add a `transform_batch_size` arg to `DatasetConfig` which will pipe through to `Preprocessor.transform`

Pros:
- A different batch size can be used for preprocessing during training vs. preprocessing during prediction. This is useful for independently tuning batch size for each use case as cluster config for training and prediction are often different (and RAM might be different on each).

Cons:
- API is too clunky. Configured in different places for training vs. prediction vs. standalone preprocessors.
- Cannot configure batch size independently for each preprocessor in a chained setting

#### New API after the changes:
Addition of `batch_size` arg to `Preprocessor.transform`:
```python
def transform(self, dataset: Dataset, batch_size: int = 4096) -> Dataset:
```

Addition of `preprocess_batch_size` arg to `BatchPredictor`:

```python
 def predict(
        self,
        data: Union[ray.data.Dataset, ray.data.DatasetPipeline],
        *,
        feature_columns: Optional[List[str]] = None,
        keep_columns: Optional[List[str]] = None,
        batch_size: Optional[int] = None,
        preprocess_batch_size: Optional[int] = None,
        min_scoring_workers: int = 1,
        max_scoring_workers: Optional[int] = None,
        num_cpus_per_worker: Optional[int] = None,
        num_gpus_per_worker: Optional[int] = None,
        separate_gpu_stage: bool = True,
        ray_remote_args: Optional[Dict[str, Any]] = None,
        **predict_kwargs,
    ) -> ray.data.Dataset:
```

Addition of `transform_batch_size` to `DatasetConfig`:

```python
fit: Optional[bool] = None
split: Optional[bool] = None
required: Optional[bool] = None
transform: Optional[bool] = None
transform_batch_size: int = 4096
use_stream_api: Optional[bool] = None
stream_window_size: Optional[float] = None
global_shuffle: Optional[bool] = None
randomize_block_order: Optional[bool] = None
```

### Option 2: Tie batch size to the Preprocessor instance
 Have `batch_size` tied to the preprocessor via an arg passed to `Preprocessor.__init__`. This is already being done for `BatchMapper`: https://github.com/ray-project/ray/pull/29193, but we would need to extend this to all Preprocessors.

Pros:
- Cleaner API. Batch size is configured for each preprocessor and in only one place.
- Can configure batch size independently for each preprocessor

Cons:
- Cannot use a different batch size for training vs. prediction. The available resources and cluster configuration for training vs. prediction may be different, so you might want to tune each independently depending on available RAM.
- `transform_batch_size` doesn't make sense for the online serving case. There's batching at the Ray Serve level that's independent of this.

#### New API after the changes:
No longer make `Preprocessor` an abstract class. Add an `__init__` method  that takes in a `transform_batch_size` to `Preprocessor.__init__`.

```python
class Preprocessor:
    def __init__(self, transform_batch_size: int = 4096):
        ...
```

**Comment by ericl** [comment]
I think my main concern here is having two separate configs. Could we make it by default use the present batch size config for both, and then call the new flag `override_preprocess_batch_size` to clear up the use case?

Btw, I don't think None is a great default. It may be better to make it mandatory as an argument.

**Comment by clarkzinzow** [comment]
Also, +1 to @ericl's suggestion of sharing `batch_size` between the preprocessor and predictor by default, and having `preprocessor_batch_size` override that sharing. I think we could still have:
```python
        batch_size: Optional[int] = None,
        preprocess_batch_size: Optional[int] = None,
```
where the docstring for `preprocess_batch_size` indicates that, if not specified, `batch_size` will be used (i.e. I don't think we need to name it `override_preprocess_batch_size`, which is quite verbose). I think that I've seen this "override if given" pattern elsewhere in ML libs.

**Comment by amogkam** [comment]
@richardliaw good point, added it as an option

@ericl @clarkzinzow removed the section about the defaults. We can make that decision separately in a future RFC. Also renamed tp `override_preprocessor_batch_size`

**Comment by amogkam** [comment]
Updated the issue- can you guys take another look? Thanks!

**Comment by Yard1** [comment]
This may be too radical, but how about using a context manager to set batch size for all preprocessor operations inside the context?

**Comment by clarkzinzow** [comment]
>For API consistency we also should introduce an equivalent way to configure preprocess batch size for training. We add a transform_batch_size arg to DatasetConfig which will pipe through to Preprocessor.transform

@amogkam We need to be able to set `batch_size` at a per-preprocessor level, since different preprocessors will have different batch size requirements (e.g. differing peak memory utilization in relation to batch size).

**Comment by jiaodong** [comment]
Vote for option 2) with the following high level assumptions:

- Each preprocessor should have a default `batch_size`
- Different preprocessors can have different optimal batch_size depending on the workload 
- Preprocessor's batch_size is by default preserved across training and prediction 
- Trainer / Predictor act as the consumer of dataset, which have its own requirement of `batch_size` that does not overlap with preprocessor batch sizes. 
- Consumer (Trainer / predictor) can always get and override its preprocessor batch_size if needed.

**Concrete example:**

Preprocessor ->  A, B
Trainer -> T
Predictor -> P
Checkpoint -> C

E2E Workflow: 
- A() -> B(batch_size=1024) -> T(batch_size=128) -> C
  - This leads to A with batch_size = 4096, B with batch_size = 1024, T with 128 and all persisted in checkpoint 
  - Upon checkpoint resume, user T can train with T(batch_size=256) which by default uses A=4096, B=1024 for preprocessing
-  C -> P(batch_size=512)
  - This by default uses A=4096, B=1024, P=512
  - User can optionally fetch A & B to change their batch size to fine tune e2e throughput

**Comment by amogkam** [comment]
@clarkzinzow yeah that's a good point, updated the rfc

**Comment by amogkam** [comment]
@jiaodong yeah that's a good point.

So basically seems like Option 2 is the best approach.
To change the batch size for prediction, the user can modify the preprocessor stored in the checkpoint with a new batch size.

The missing piece here is with Option 2 we also need a setter for batch size: `preprocessor.set_batch_size()`

So user can do something like this
```python
preprocessor = Preprocessor(transform_batch_size=1024)
trainer = Trainer(preprocessor)
trainer.fit(). checkpoint.to_uri(s3_path)
```

In a separate prediction cluster, change the batch size of the preprocessor for prediction
```
checkpoint = Checkpoint.from_uri(uri_path)
preprocessor = checkpoint.get_preprocessor()
preprocessor.set_transform_batch_size(256)
predictor = BatchPredictor.from_checkpoint(checkpoint)
```

**Comment by ericl** [comment]
I actually don't think it's a good idea to support per preprocessor batch
size. The implementation complexity of this is very high, especially if it
breaks fusion across preprocessing stages.

Why not just have users set the batch size to be small enough for all
preprocessors so it won't OOM?

**Comment by richardliaw** [comment]
The per-preprocessor API perhaps is too much boilerplate/configuration complexity. 

The main problem with the batch size too small is the h2d right? though not clear if that is going to be the bottleneck necessarily.

**Comment by clarkzinzow** [comment]
>I actually don't think it's a good idea to support per preprocessor batch
size. The implementation complexity of this is very high, especially if it
breaks fusion across preprocessing stages.

@ericl This wouldn't break fusion across preprocessing stages, we can (and already do) support fusing `.map_batches()` calls with different batch sizes.

**Comment by amogkam** [comment]
cc @c21- it seems that stage fusion is supported for multiple `map_batches` calls with different batch sizes.

**Comment by c21** [comment]
We don't do `map_batches` fusion by default, right? We only do it in lazy execution mode.

**Comment by amogkam** [comment]
Right, but that's true regardless of what the batch size is.

**Comment by ericl** [comment]
AIR force enables lazy mode for BatchPredictor, so we can assume it's on.

**Comment by amogkam** [comment]
> AIR force enables lazy mode for BatchPredictor, so we can assume it's on.

I don't think this is currently the case...where is this happening in the code?

**Comment by ericl** [comment]
Ah, I'm mistaken. It's not force enabling lazy mode, but you do effectively get stage fusion when using most preprocessors after a `read` stage. This is since the `read` stage is always partially lazy. Hence, as long as you only have map_batches after the read, you effectively have a fully lazy plan / execution.

**Comment by ericl** [comment]
We should probably just explicitly call .lazy() in BatchPredictor and avoid relying on this.

**Comment by clarkzinzow** [comment]
> We should probably just explicitly call .lazy() in BatchPredictor and avoid relying on this.

Strong +1 to this, and the same goes for when triggering preprocessing before training, especially since at most **one** preprocess transform (i.e. `.map_batches()` operation) will be fused into the read stage on an eager dataset; all subsequent preprocessor transforms will be unfused.

**Comment by c21** [comment]
> We should probably just explicitly call .lazy() in BatchPredictor and avoid relying on this.

+1 as well. This will be much cleaner.

**Comment by amogkam** [comment]
So just to summarize the discussion:

Makes sense to set datasets to lazy by default for BatchPredictor, but seems orthogonal to the API discussion about batch size. Fusion should work regardless of what the batch size is of multiple map batches calls.

Seems the primary pushback to option 2 is that there is too much configuration complexity?

**Comment by jiaodong** [comment]
> Seems the primary pushback to option 2 is that there is too much configuration complexity to have to set it for each preprocessor?

We can always have a simple default option (like batch size = block size, or batch size = 4096) for all preprocessors without enforcing them right ? I think for 95%+ of the case end user will never need to know or tune it, but for internal developers be able to use this flag can benefit efficiency and benchmarking.

**Comment by clarkzinzow** [comment]
I think we need tiers of overridable defaults here, both at a single preprocessor level and at a global level:
1. Default batch size for **all** preprocessors that preprocessors or the caller can override.
2. Default batch size for **each** preprocessor that caller can override.
3. API for callers (training, prediction) to override batch sizes.

One question I have is whether (3) should be a single batch size for all preprocessors, or if we should support overriding single preprocessors in a chain at call time.

**Comment by amogkam** [comment]
@clarkzinzow @ericl and I chatted just now.

The decision is to go with Option 1, and introduce option 2 if needed down the line.

We will change the default batch size at the AIR level to be less than 4096 (probably make it 256 by default). And we will also log a warning if batch size is not specified for training or prediction.
