### ISSUE TITLE
[tune] hyperband bug

### ISSUE THREAD

**Issue by joyyoj** [ray-project/ray#2923]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

Maybe a bug in HyperBandScheduler.choose_trial_to_run.
In current implementation, hyperband is a list, its member can be None.

**Comment by ericl** [comment]
I don't think that can actually happen, do you have a test case that can reproduce this?

**Comment by richardliaw** [comment]
I think this is superceded by #2955.
