### ISSUE TITLE
[Ray DAG] Proposal on submitting DAG tasks in stage, instead of submitting a whole DAG.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#29247]
### Description

A previous issue #29217

### Use case

An initial idea on the API could be:
```python
case 1:
a = MyActor.bind()
a.f.bind().execute()
a.g.bind().execute(skip_if_node_ready=True) # we don't create any actor any more, just reuse `a`.

case 2:
f_node = f.bind()
f_node.execute()  # submit a task of `f`
f_node.execute(skip_if_node_ready=True)  # not submit any task, just retrieve the result from the last invocation.
```

**Comment by jovany-wang** [comment]
@jiaodong anybody from your team could work on this feature?

**Comment by jiaodong** [comment]
@jovany-wang most active user / developer of DAG is Serve team, Ray Workflow is a bit inactive now.

**Comment by jovany-wang** [comment]
@simon-mo Is this feature needed in Serve?

**Comment by simon-mo** [comment]
No at the moment. We only use DAG as API layer and perform transformation.
