### ISSUE TITLE
how to hide process command line parameters like --redis_password 5241590000000000 on command line gcs_server

### ISSUE THREAD

**Issue by jmsi** [ray-project/ray#29246]
### Description

how to hide process command line parameters like --redis_password 5241590000000000 on command line gcs_server,?If the password is shown on process command line,maybe it can cause security problem
  my ray version is 1.12.1, please help me, thanks a lot

**Comment by rkooo567** [comment]
cc @iycheng

**Comment by rkooo567** [comment]
Btw, from ray 1.12, we removed Redis. So the password there has no meaning I think

**Comment by zhenfeng-cao** [comment]
same problem preventing me from using ray.... is it possible to hide any hardcoded password?

**Comment by zhenfeng-cao** [comment]
hi @rkooo567 @iycheng I just upgraded to 2.2 and retried (starting ray from command line). it still prints the (default) redis password...

A better design may have the following features:
1. no display of any sensitive information in thread/process log (to be more exact, password should not be explicitly used as an arguement when starting ray from command line---this may not be safe)
2. no hardcoded password in any file/args (instead, users may read from system envs or some 3rd-party authentication api/system)

thanks.

**Comment by zhenfeng-cao** [comment]
@rkooo567 @iycheng 
any update? thank you.

**Comment by rkooo567** [comment]
Btw, we don't use Redis at all, so that argument has no meaning from the latest version. I think we should just simply remove https://github.com/ray-project/ray/blob/92ef37d81545b6c2f17b066fcbcde3e4ee3fbbcd/python/ray/_private/services.py#L1335

cc @iycheng is there any concern doing this when using external redis?
