### ISSUE TITLE
[Core] Enabling IBM Cloud integration.

### ISSUE THREAD

**Issue by dlasecki** [ray-project/ray#29256]
### Description

This feature will allow people to use Ray on IBM Cloud. It will be analogous to how other cloud providers are supported already, e.g. Google Cloud Platform, AWS, ... .
On the more technical level, it will be achieved by:

a) Implementing the `NodeProvider` interface for IBM Cloud.
 https://github.com/ray-project/ray/tree/master/python/ray/autoscaler

b) Contributing a YAML file with relevant configuration settings for IBM Cloud.

It would also include extending the Ray documentation accordingly.

### Use case

A user wants to run Ray using IBM Cloud infrastructure. They can see the documentation of Ray with support for IBM Cloud and discover that they need to use the `NodeProvider` implementation for IBM Cloud together with a YAML configuration to run their workflows.

**Comment by dlasecki** [comment]
If you need a hand on this, I might be able to jump in.

**Comment by DhavalRepo18** [comment]
@dlasecki I was looking for similar support. It will be a great benefits for a tool we are developing.
