### ISSUE TITLE
[Core] Authentication in ray head nodes

### ISSUE THREAD

**Issue by IceKhan13** [ray-project/ray#29260]
### Description

Implement authentication mechanism for ray (head) nodes.

It is reopen of similar issue https://github.com/ray-project/ray/issues/17730

As far as I understand ray uses grpc protocol somehow. Maybe send passoword/token as part of grpc metadata, or something along those lines. https://grpc.io/docs/guides/auth/#extending-grpc-to-support-other-authentication-mechanisms

### Use case

As a user I want to expose my head nodes to be accessible in client mode. In order to do so securely I need some kind of authentication mechanism. Before 2.0 it was possible to set redis password (I think). 
Password or token would be really nice to have.

**Comment by IceKhan13** [comment]
If you need a hand on this, I might be able to jump in

**Comment by shishir-narayan** [comment]
Any updates here? This would be very useful for us. We want to use this feature to pass a Kubernetes Service Account JWT down to the worker.
