### ISSUE TITLE
Asynchronous training and sampling always get plasma errors

### ISSUE THREAD

**Issue by luweichao** [ray-project/ray#2926]
### System information
- ubuntu 16.04
- ray installed by pip
- ray-0.5.2
- python 3.6.5

### Describe the problem
- Architecture: I setup a distributed training system using ray and tensorflow. It consists of three parts: [driver] - [remote learner-sampler] - [remote actor].
-- The driver is the entry point, which starts multi remote learners to do distributed training. Each remote learner starts a tf-server and use a sampler. Samplers start remote actors. Learners use samplers to collect samples from remote actors. Actors start environments to collect data.
-- Leaners, samplers and actors all have two types: synchronous and asynchronous. Asynchronous ones use background threads to do their jobs, while synchronous leaners and actors are remotely called by driver and samplers correspondingly.
- Problem: I use all of the combinations to do the training, but only one combination can run without any errors, it is [driver] - [sync-learner/sync-sampler] - [sync actor]. Every other combinations will get plasma errors of either one below
-- /ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:628 Check failed: object_entry != objects_in_use_.end()
-- /ray/thirdparty/build/arrow/cpp/src/plasma/client.cc:630 Check failed: object_entry->second->count >= 0

Are there any possible solutions?

**Comment by ericl** [comment]
Do you have a script that can reproduce this issue?

**Comment by luweichao** [comment]
My original project has many dependencies and it is a internal project. I wrote a simple script to reproduce the issue but it runs without errors.
https://github.com/luweichao/tests/blob/master/ray/distributed_controller.py

**Comment by luweichao** [comment]
@ericl 
My original project has many dependencies and it is a internal project. I wrote a simple script to reproduce the issue but it runs without errors.
https://github.com/luweichao/tests/blob/master/ray/distributed_controller.py

**Comment by simon-mo** [comment]
Does this still happen on latest master? If so please re-open this issue, thanks!
