### ISSUE TITLE
[Ray AIR: Ray Data] 

### ISSUE THREAD

**Issue by dmatrix** [ray-project/ray#29267]
### What happened + What you expected to happen

- [ ] #29271

```

train_dataset: ray.data.Dataset = ray.data.read_datasource(
    SimpleTorchDatasource(), dataset_factory=train_dataset_factory
)
test_dataset: ray.data.Dataset = ray.data.read_datasource(
    SimpleTorchDatasource(), dataset_factory=test_dataset_factory
)
```

Since Ray data uses Pandas internally as its representation, this should be implicitly converted, not explicitly done by the user. 

```from typing import Tuple
import pandas as pd
import torch


def convert_batch_to_pandas(batch: Tuple[torch.Tensor, int]) -> pd.DataFrame:
    images = [image.numpy() for image, _ in batch]
    labels = [label for _, label in batch]
    return pd.DataFrame({"image": images, "label": labels})


train_dataset = train_dataset.map_batches(convert_batch_to_pandas)
test_dataset = test_dataset.map_batches(convert_batch_to_pandas)
```

- [x] #29270

![Screen Shot 2022-10-12 at 12 04 50 PM](https://user-images.githubusercontent.com/1117597/195426939-ecc889a7-3b05-4dd3-ab2c-5011e44997cd.png)

### Versions / Dependencies

- Ray Nightly builds
- Python 3.8+
- macOS Monterey

### Reproduction script

You can run one of these scripts and see the warning messages.

 * https://docs.ray.io/en/master/ray-air/examples/torch_image_example.html
 * https://github.com/dmatrix/misc-code/blob/master/py/ray/rayair/examples/cifar-10/cifar.ipynb

### Issue Severity

Low: It annoys or frustrates me.

**Comment by amogkam** [comment]
1 is no longer an issue with the recent strict mode developments. All datasets are treated as tabular datasets now.
