### ISSUE TITLE
[CI] `linux://python/ray/train:test_gpu` is failing/flaky on release branch.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29299]
- 4b605c24aeb991e4b693f8fa37fc967079d3ec22 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/498#0183ce28-68b0-4e81-b4d4-63909e9df9d7)
- 6bac4ab766d3c738bb816cb5fd6801aaab4388f4 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/495#0183cded-4ab5-4dd6-b3ea-d488a6604c53)
- 429c0e88cd0bc96f75e5125525bd660232eddcbb FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/493#0183cda3-d271-4b0d-ade0-be1a3a2229d8)
- 40811d7029b8ce721713a3532596e1aba9646ab0 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/492#0183cd9f-f951-4ee9-aa2a-a889e27622f7)
- 34cd1cbccf295db77fcfb5f81421e295f2664643 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/487#0183cd52-77e7-4140-a1b5-c13783900adb)
- f2dacc017c066f975ef24c67eed0411cdfac12d2 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/486#0183cd4f-7d35-42b6-aec5-ed91d9c870d9)
- 223ce3988e0a424d33a557c616eff6dd140b812c FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/482#0183cb57-20a6-4b27-b149-7bb983003ecc)
- 75e9722a4d9c0d8d5cb0c37eb6316553f9e0789e FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/481#0183cac0-74c0-4a96-81aa-3d12a9f1f775)
- 49a27f2b52475142a08fa771637b3b5a01fc1701 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/480#0183ca4f-07cb-476c-ae42-7716f96d0e94)
- 5229df15ab71baf22ade6a3ff14e921be10b3a25 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/477#0183c9b8-4f8a-4da9-a400-d545e4e05ca5)
- 44fc6a36e5228a50f4bafe126c67ad73d78486eb FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/474#0183c991-ac6c-4902-892e-91c3e0c034b3)
- 7d3eeb13032f341627015353214524fe09fad6a6 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/473#0183c98c-2485-4009-920d-268113d2d82c)
- 4b79a6f1d270658eca3bf65df2b16b4e512f6513 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/469#0183c94c-65f4-4a09-81aa-7b5d71144f3f)
- c9875edafc167d70c55fef54cc045f14f39b19a5 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/468#0183c946-b088-4339-8b31-9ff075d23f37)
- 60840b5498a8e5e8fc6b1bbeadaaa5c210b62624 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/465#0183c901-1478-42a4-a5ed-4b80ddb78d1e)
- 297341e107daee1ea3aff991ae8ea8c90993c683 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/460#0183c868-9f50-4989-b153-f8e9bf4debeb)
- d89a66401719996b3f56b2769ca24d5fc20aa889 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/455#0183c831-7593-4a19-a91b-9e120d4846fe)
- 217dcd7f18cd4ce0025a68bd46f0bf249c09870d FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/454#0183c806-61cd-4ac6-8344-66cbb2de223a)
- 217dcd7f18cd4ce0025a68bd46f0bf249c09870d FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/451#0183c4e2-7244-427e-b931-3e3e68530d74)
- 1bd8ab9b421a58cd07fe4ca015c07e5fd0070059 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/450#0183c4b1-49f5-4d45-911b-4a6e91fd5f85)
- 91040d91bba3cdfc29475b77e8d199884469ab86 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/379#0183aefd-576f-4d74-b455-3eced0ab5e47)
- 8486ddd1bf909449a22262c52a90f8359797fc16 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/378#0183aef8-ee16-4cf5-9fad-c326f0b5e8d0)
- 7e939d79bcc68603b7c9a99fa6ef880dd526e931 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/377#0183aeef-f145-4257-aa9f-ae59634ccec9)
- 4732753327109d5c33b4cf69d375730057efc631 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/376#0183aee1-2dde-48a6-8e1d-f8ffce438752)
- 68a35fceef6a47fa3e3da41041ee32dafe7f24a8 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/375#0183aec9-28c0-465b-9f05-db096f629ae1)
- 23b3a599b9df8100558c477e94b0b19b1a38ac27 FAILED [Buildkite :tv: :steam_locomotive: Train GPU tests ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/374#0183aec0-8b6d-428e-a1fc-90eedbf969c2)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/train:test_gpu-END
....

**Comment by jiaodong** [comment]
https://github.com/ray-project/ray/pull/29297

**Comment by rickyyx** [comment]
Let's get this cherry picked to release branch. 
Reopnening to track the cherry-pick

**Comment by jiaodong** [comment]
@rickyyx FYI the merged PR simply splits tests so you can expect the failure has low risk to 2.1 release

**Comment by rickyyx** [comment]
Will you be opening a cherry pick for this jiao? @jiaodong

**Comment by jiaodong** [comment]
hmm i don't think it's necessary, we don't need to fix anything in 2.1 code itself, just the way we structure tests to accommodate cuda 11.6 update

**Comment by rickyyx** [comment]
Let's still cherry pick this in - generally we try to make CI green rather than have exceptions. Otherwise there will be too many false positives in the CI, which makes it hard to track the status. cc @matthewdeng

**Comment by jiaodong** [comment]
this issue is good to close and not release blocker anymore ?
