### ISSUE TITLE
[CI] `linux://doc:datasets_train` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29300]
- 6bac4ab766d3c738bb816cb5fd6801aaab4388f4 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/495#0183cded-4abb-42bd-b14a-98d9e5125a64)
- 34cd1cbccf295db77fcfb5f81421e295f2664643 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/487#0183cd52-77ed-49ae-96bd-e339fa193182)
- 5229df15ab71baf22ade6a3ff14e921be10b3a25 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/477#0183c9b8-4f90-4dfe-b814-651d7f51a01d)
- 44fc6a36e5228a50f4bafe126c67ad73d78486eb FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/474#0183c991-ac72-4f3d-8860-1027c6ac5216)
- c9875edafc167d70c55fef54cc045f14f39b19a5 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/468#0183c946-b091-4335-b08c-1dec08dd9fee)
- 60840b5498a8e5e8fc6b1bbeadaaa5c210b62624 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/465#0183c901-147e-4a16-b5e0-dc9fdc6e6a3a)
- 297341e107daee1ea3aff991ae8ea8c90993c683 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/460#0183c868-9f56-4cce-8b75-788a26a0d33b)
- 217dcd7f18cd4ce0025a68bd46f0bf249c09870d FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/451#0183c4e2-7249-4080-91cf-29461e7fe792)
- 9a7aa243aa6a74e146a7ce03d3e4d51a6917d43c FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/446#0183bd72-7e14-48aa-88bd-f5d6ea06e52e)
- 47aa6c432353fb22a81103c28dc343b6d9407d52 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/428#0183b4a7-64ff-4812-a617-6532a0870d5a)
- da6adbb5d6c692cc65d08a7cd4a72b4da72c4f93 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/426#0183b497-8074-44d7-9cd2-b7477916baac)
- 081ce2fe4e88ae5f36aa0a6b45fb7048c01947c7 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/402#0183b0d5-41d2-4df3-99d5-3306f63f44a2)
- d7b2b49a962bf33dae7a50376f159ab15d80800f FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/392#0183afcb-6b00-40b8-9ac5-6693d3bcd949)
- 3ede830f747a47570c337f361fc76721cdd9a00e FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/385#0183af51-e02d-4bc9-aa0a-09c2eae138da)
- 65a8b0f8c27f0b9049b21b2b9bc9ed07782b9e81 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/380#0183aeff-4ff8-407d-b2c1-f6c6ae60ab1a)
- 91040d91bba3cdfc29475b77e8d199884469ab86 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/379#0183aefd-5775-4d88-ae69-5bf877c75748)
- 8486ddd1bf909449a22262c52a90f8359797fc16 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/378#0183aef8-ee1b-4517-86f6-823342ded5d8)
- 7e939d79bcc68603b7c9a99fa6ef880dd526e931 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/377#0183aeef-f16f-46ac-9934-ab997fb05603)
- 4732753327109d5c33b4cf69d375730057efc631 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/376#0183aee1-2de3-41d0-95f5-9489bef838c4)
- 68a35fceef6a47fa3e3da41041ee32dafe7f24a8 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/375#0183aec9-28c8-4e09-989f-cc1d7eea5c54)
- 23b3a599b9df8100558c477e94b0b19b1a38ac27 FAILED [Buildkite :tv: :database: :steam_locomotive: Datasets Train Integration GPU Tests and Examples (Python 3.7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/374#0183aec0-8b75-4c39-9780-bb3240b8db5d)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc:datasets_train-END
....

**Comment by rickyyx** [comment]
Failure on release branch: https://buildkite.com/ray-project/oss-ci-build-branch/builds/488#0183cd54-7535-4e9e-8420-3076ccebc871

**Comment by matthewdeng** [comment]
Hmmm @amogkam any ideas about this one?

```
opt/bin/doc/datasets_train.runfiles/com_github_ray_project_ray/doc/source/ray-core/_examples/datasets_train/datasets_train.py", line 350, in train_epoch
--
  | loss = criterion(outputs, labels.float())
  | File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
  | return forward_call(*input, **kwargs)
  | File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 716, in forward
  | reduction=self.reduction)
  | File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/functional.py", line 2960, in binary_cross_entropy_with_logits
  | return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
  | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
```

I originally thought it was due to https://github.com/ray-project/ray/pull/29104 but see that it's already checked in...

**Comment by amogkam** [comment]
The example should use `train.torch.get_device()` instead of manually doing it 

```
# Setup device.
    device = torch.device(
        f"cuda:{session.get_local_rank()}"
        if use_gpu and torch.cuda.is_available()
        else "cpu"
    )
```

**Comment by amogkam** [comment]
https://github.com/ray-project/ray/pull/29305
