### ISSUE TITLE
[CI] //rllib:learning_tests_* failures

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29301]
### What happened + What you expected to happen

rllib:learning_tests_cartpole_alpha_star
rllib:learning_tests_cartpole_appo_no_vtrace
rllib:learning_tests_cartpole_separate_losses_appo
rllib:learning_tests_multi_agent_cartpole_appo

[Failure build](https://buildkite.com/ray-project/oss-ci-build-branch/builds/488#0183cd4f-aa9f-45bc-b2ff-d5eb9b7779c3)

### Versions / Dependencies

release branch 

### Reproduction script

NA

**Comment by rickyyx** [comment]
Looks it being fixed in master - cherry picks?

**Comment by gjoliver** [comment]
these are being fixed by https://github.com/ray-project/ray/pull/29249
