### ISSUE TITLE
[CI] `linux://python/ray/tests:test_client` is failing/flaky on release branch.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29304]
[Release branch test failure](https://buildkite.com/ray-project/oss-ci-build-branch/builds/488#0183cd49-9c21-4802-8d54-756bf2435c0b)

Looks green on master, maybe need cherry-picks?

**Comment by ckw017** [comment]
It was fixed by this: https://github.com/ray-project/ray/pull/28835

That PR only changed test files though, doesn't change any ray functionality.

**Comment by rickyyx** [comment]
Oh yeah - let's still do that.

**Comment by rickyyx** [comment]
Closed by #29317
