### ISSUE TITLE
BAZEL: redis build resets all compiler-related environment variables

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#29323]
This line https://github.com/ray-project/ray/blob/25c2a4dbea83c0c9b355d1271e9ea159cb612927/bazel/BUILD.redis#L45

was added in #18622, it seems the intention is to work around limitations in CI. It has the effect of resetting compilation to the platform defaults, and breaks the build on platforms like conda that use these environment variables and more to layer their own preferences on top of the bare platform ones. It seems like there are more users who would prefer their choices are respected when building redis. Is it required?

**Comment by mattip** [comment]
I am a bit confused by this: I thought somewhere along the line redis was no longer required for ray? See for instance ray-project/ray#29372

**Comment by mattip** [comment]
Couldn't the entire redis bazel build be removed and another method used to install a vanilla upstream version?

**Comment by scv119** [comment]
@iycheng might the best person to answer here.

**Comment by iycheng** [comment]
From the description it seems:

```
Currently when we want to compile the project with clang, we specify CC=clang which still uses libstdc++ from GCC toolchain. There are compile failures when upgrading C++ standard to 17. This PR generates a config to use clang together with libc++ when Bazel config --config=llvm is specified. The config generation can be ran from CI or other Ubuntu systems. Developers on MacOS don't need this config because this toolchain is already the default.

Rolling forward the upgrade of C++ standard to 17 from Yi (https://github.com/ray-project/ray/pull/18455), which seems to work now.
The C++ standard upgrade requires running C++ / ASAN / TSAN tests with --config=llvm as well. With libc++ ASAN enabled container-overflow check which uncovers two issues that are fixed.
```

**Comment by h-vetinari** [comment]
Not stale
