### ISSUE TITLE
[release][CI] rllib_multi_gpu_learning_tests failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29320]
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1108#0183cdac-c9ef-4ed7-9e8c-84c63db642d4)

[Cluster failure](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_A1hVuZGVctnd5xmDJx1xJ7mu?command-history-section=command_history)

```
_samples() from rllib.policy.sample_batch` instead. This will raise an error in the future!

Traceback (most recent call last):
  File "multi_gpu_learning_tests/run.py", line 21, in <module>
    results = run_learning_tests_from_yaml(yaml_files)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/rllib/utils/test_utils.py", line 740, in run_learning_tests_from_yaml
    max_report_frequency=30,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 877, in run_experiments
    callbacks=callbacks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 771, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [IMPALA_CartPole-v0_c2d3a_00011])
```

### Versions / Dependencies

2.1 release 

### Reproduction script

NA

**Comment by rickyyx** [comment]
Maybe not agent leak. cc @gjoliver

**Comment by gjoliver** [comment]
this one @avnishn will extend the deadline for IMPALA torch a little bit.
the algorithm is fine.
taking release blocker tag off.
thanks.

**Comment by gjoliver** [comment]
works fine now after the mem leak is fixed. performance likely got boosted a bit.
closing.
