### ISSUE TITLE
[release][CI] rllib_stress_tests failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29321]
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/release-tests-branch/builds/1108#0183cdac-c9f7-4b5c-a530-81e453d90569)

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_gxSxeL3vJw6gNAfQusV9akpM?command-history-section=command_history)

Looks different from the previous failure: #28998 

Please help double-check. 

### Versions / Dependencies

release branch 2.1 

### Reproduction script

NA

**Comment by rkooo567** [comment]
cc @gjoliver for the status?

**Comment by gjoliver** [comment]
works fine now with the mem issue fixed.
closing. thanks.
