### ISSUE TITLE
[CI] `linux://python/ray/train:test_torch_trainer` is failing/flaky on release 2.1.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29334]
[Build failure ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/507#0183d27f-8e01-43c7-ab7a-ca3f54881338)

**Comment by jiaodong** [comment]
This should be addressed with low risk of regression in 2.1 release 
<img width="1501" alt="Screen Shot 2022-10-14 at 11 19 19 AM" src="https://user-images.githubusercontent.com/6372689/195914584-b26b0a5c-dff6-41af-bdf9-fc56ca3c024b.png">

**Comment by rickyyx** [comment]
Probably need a cherry-pick

**Comment by jiaodong** [comment]
@rickyyx , @amogkam  just told me the cherrypick PR for this issue is already merged.

**Comment by rickyyx** [comment]
Closed by https://github.com/ray-project/ray/commit/f55df44e97a3b41d22c2951e76faabd7f95f2f75
