### ISSUE TITLE
[release][CI] test_multinode_sync failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29333]
### What happened + What you expected to happen

[Build failure ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/507#0183d278-b863-4a17-8af7-74e38caab3ab)

Interestingly - this test is not captured on flaky dashboard, neither is it reported on the oss tests result? https://b534fd88.us1a.app.preset.io/superset/sqllab?savedQueryId=93

### Versions / Dependencies

release 2.1

### Reproduction script

NA

**Comment by krfricke** [comment]
Passed on retry https://buildkite.com/ray-project/oss-ci-build-branch/builds/507#0183d3a7-95ad-4b7b-8445-aa02653a4d53
