### ISSUE TITLE
[CI] `linux://rllib:test_apex_ddpg` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29339]
- 28c0553f8f6478795fd18be2421efb61ec6035cb FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/504#0183d240-5fc0-4f34-a29b-3299778f07b5)
- 75a0c491e8ee4009e8828081059cfc98543c4d51 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/434#0183b53a-2f2d-407c-b8d5-bcc39b938152)
- 47aa6c432353fb22a81103c28dc343b6d9407d52 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/428#0183b4a3-0a0c-4edf-a6bd-9ff7ed63ecba)
- 31347c026e985e9baa438bdaa3159fb5cd7dea6c FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/425#0183b46e-38d5-49c2-9e49-57eaad0d1799)
- 1ac75f9fea2c70f3905daccafd1ae0d595cda732 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/416#0183b3ff-8369-4d7e-80a4-bf3ff8333419)
- 4652752e8620c1251b74930b512c6620ee9bc0f4 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/415#0183b3fd-3b04-477e-9d88-7820ff4dd373)
- c5c3e6ccaccee430330c078ffb68bd12e7866e04 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/403#0183b2a4-2740-42b3-ae58-262f5da5dc9e)
- 081ce2fe4e88ae5f36aa0a6b45fb7048c01947c7 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/402#0183b0d2-f71c-4ddd-8b3c-be26ed32b4de)
- 366f2a9c687f709134c69adb0de94c3f079d2f3a FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/400#0183b07c-d25d-4154-9c14-2bc4851be300)
- 251903bc49b5a29a8185e0fa58d67c64fe2fc076 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/394#0183afd5-f7ea-49e3-8dc1-56ddf52b4e2f)
- 0ee478b13152254380f3dd638bd666a114fd6e67 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/393#0183afc8-7b4c-40cc-aaf8-6c52527ba9c5)
- 29791d9acedaa4700d0b9dccecab4cddfcfd64b4 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/391#0183afbf-f33f-4959-948f-2ec079fb3681)
- fd0148878d9b13449f708ae521d9bb1678c69b10 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/389#0183af6e-4b68-4ffb-b2ed-b19d507f084b)
- 849afc63e55ab15e63c1ed86e08c81d449b1f7e8 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/384#0183af16-e934-400f-8379-b9333dd1fab9)
- 65a8b0f8c27f0b9049b21b2b9bc9ed07782b9e81 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/380#0183aefb-300f-4266-b1bf-ec382be8b11e)
- 91040d91bba3cdfc29475b77e8d199884469ab86 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/379#0183aef8-f293-4dc5-91c7-cacb080b61fd)
- 8486ddd1bf909449a22262c52a90f8359797fc16 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/378#0183aef6-a56e-43ba-b8d3-3f7a5c176c97)
- 7e939d79bcc68603b7c9a99fa6ef880dd526e931 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/377#0183aeeb-6d2f-45c9-9c20-c344407f56d7)
- 4732753327109d5c33b4cf69d375730057efc631 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/376#0183aede-ee43-44c7-b77f-577f2f2cf327)
- 68a35fceef6a47fa3e3da41041ee32dafe7f24a8 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/375#0183aec6-f828-4870-9649-fe69eddb2796)
- 23b3a599b9df8100558c477e94b0b19b1a38ac27 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/374#0183aebc-43fe-4019-9c69-3cc1bfbb4dd4)
- b5687a1aaa3dc72dfde9758e730607a4ab22afe4 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/369#0183ae40-b759-4b77-b9be-09392d037f9d)
- e142be077f0c727ab11ba51ecaba9a98b7bfe474 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/368#0183adea-c056-41ba-a462-9578946af391)
- b510640f15a0fa4782b83ec2ea0749386b615b15 FAILED [Buildkite :brain: RLlib: Algorithm Tests (specific algos)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/367#0183ade5-1c38-4ded-8efc-5e54ceb005d8)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://rllib:test_apex_ddpg-END
....

**Comment by rickyyx** [comment]
Marking it as release blocker for now since it is showing up in the release branch CI as well: https://buildkite.com/ray-project/oss-ci-build-pr/builds/2138#0183d2a7-1715-49d7-afb9-1c1bae966d09

**Comment by gjoliver** [comment]
I looked at this test. I don't know what we can do tbh.
when it passes, it passes. when it times out, pytest just hangs at "collecting tests ..." without any error logs.

**Comment by gjoliver** [comment]
I am willing to declare this non-release blocking.

**Comment by rickyyx** [comment]
@gjoliver Looks like there are some failure output w.r.t this test in this [build](https://buildkite.com/ray-project/oss-ci-build-branch/builds/556#0183e754-d158-4a43-be26-86851a7d1990), maybe this will help root-causing.

**Comment by gjoliver** [comment]
I don't see anything 😢 
since this has been flaky for at least a quarter now, I am gonna say this is not release blocking for now.
thanks man.

**Comment by gjoliver** [comment]
huh, thanks I didn't notice it. taking a look.

**Comment by gjoliver** [comment]
job received a sigterm from where ...

**Comment by rickyyx** [comment]
no more relevant?
