### ISSUE TITLE
Trying to install RLlib: Scalable Reinforcement Learning on Windows 10

### ISSUE THREAD

**Issue by X-I-O-N** [ray-project/ray#2933]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

Windows 10
Ray is not installing
Python 3.6.4
pip install ray[rllib]

### Describe the problem

I work on windows for machine learning partly due to the exe files I connect my developments to. Anyways, I have tried the default pip install ray[rllib] command to install the package and the error is:

Could not find a version that satisfies the requirement ray[rllib] (from versions: )
No matching distribution found for ray[rllib]

Is Rllib not compatible with windows? If not, what can I do to make ends work?

**Comment by ericl** [comment]
Some people have had success using the Windows subsystem for linux, though I haven't tried it personally. You might run into some issues with GPU support though.
