### ISSUE TITLE
[Tune] Ray Tune Checkpoint Warning with PL Checkpoint Callbacks 

### ISSUE THREAD

**Issue by yinweisu** [ray-project/ray#29340]
### What happened + What you expected to happen

I got the following warning when using PL Ray Tune checkpoint callback:
```bash
/home/ubuntu/anaconda3/envs/test_multimodal/lib/python3.8/site-packages/ray/tune/trainable/function_trainable.py:642: DeprecationWarning: `checkpoint_dir` in `func(config, checkpoint_dir)` is being deprecated. To save and load checkpoint in trainable functions, please use the `ray.air.session` API:

from ray.air import session

def train(config):
    # ...
    session.report({"metric": metric}, checkpoint=checkpoint)

For more information please see https://docs.ray.io/en/master/ray-air/key-concepts.html#session
```

### Versions / Dependencies

Ray 2.0
Ubuntu

### Reproduction script

Just the official example:
https://docs.ray.io/en/latest/tune/examples/tune-pytorch-lightning.html#

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @Yard1 - please review

**Comment by richardliaw** [comment]
@Yard1 could you follow up here?

**Comment by movy** [comment]
Same here, still not sure what this error wants me to do.

**Comment by Yard1** [comment]
This will be removed when we fully deprecate `tune.report` in a future release.

**Comment by yinweisu** [comment]
This still present for ray 2.4
I wonder is there a way to suppress the warning? I tried to set the logging level to logging.ERROR but still printing the warning

**Comment by justinvyu** [comment]
`tune.report` is hard-deprecated in 2.7. See migration guide: https://docs.google.com/document/d/1J-09US8cXc-tpl2A1BpOrlHLTEDMdIJp6Ah1ifBUw7Y/edit#heading=h.xi4qh6ve48tm
