### ISSUE TITLE
[RLlib] `examples/replay_buffer_api.py` is broken

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#29367]
### What happened + What you expected to happen

`examples/replay_buffer_api.py` was misconfigured in the BUILD bazel file and not being tested in CI at all. It throws an exception.

### Versions / Dependencies

master

### Reproduction script

`examples/replay_buffer_api.py`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Yard1** [comment]
@avnishn

**Comment by hora-anyscale** [comment]
Per Triage Sync: closing
