### ISSUE TITLE
Ray scripts

### ISSUE THREAD

**Issue by andreichalapco** [ray-project/ray#29383]
### What happened + What you expected to happen

Hi,

when running the minimal tests via `python -m pytest -v python/ray/tests/test_mini.py` I noticed that some deprecated error are comming through that could be fixed.

1. python-3.10.7/lib64/python3.10/site-packages/requests/__init__.py:43: DeprecationWarning: 'urllib3[secure]' extra is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    import urllib3

2. /python-3.10.7/lib64/python3.10/site-packages/ray/scripts/scripts.py:14: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.dir_util import copy_tree

For the second deprecation warning I already found a solution with `shutil.copytree`. If you're interested I could also make a pull request.
The first deprecation error will I think be fixed by the requests package contributors.

### Versions / Dependencies

Ray version: 
Version: 3.0.0.dev0
Python 3.10.7

### Reproduction script

```sh
python -m pytest -v python/ray/tests/test_mini.py
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
cc @rickyyx @scv119 another deprecated APIs for Python 3.10. I will leave it up to you guys for triaging process

**Comment by rickyyx** [comment]
Hmmm, I somehow have troubles reproducing it. 

```
(python310-3) ➜  ray git:(ricky/pin-six-for-py310) python -m pytest -v python/ray/tests/test_mini.py

Test session starts (platform: linux, Python 3.10.6, pytest 7.0.1, pytest-sugar 0.9.5)
cachedir: .pytest_cache
rootdir: /data/home/rickyx/ray/python
plugins: anyio-3.6.1, timeout-2.1.0, sugar-0.9.5, shutil-1.7.0, rerunfailures-10.2, lazy-fixture-0.6.3, forked-1.4.0, docker-tools-3.1.3, asyncio-0.16.0, virtualenv-1.7.0
collecting ... 
 ray/tests/test_mini.py::test_basic_task_api ✓                                                                                 33% ███▍      
 ray/tests/test_mini.py::test_put_api ✓                                                                                        67% ██████▋   
 ray/tests/test_mini.py::test_actor_api ✓                                                                                     100% ██████████

Results (15.99s):
       3 passed
(python310-3) ➜  ray git:(ricky/pin-six-for-py310) python -V
Python 3.10.6
(python310-3) ➜  ray git:(ricky/pin-six-for-py310) ray --version
ray, version 3.0.0.dev0
(python310-3) ➜  ray git:(ricky/pin-six-for-py310) 
```

Maybe I need a fresh env? cc @andreichalapco Would you also share on your setup steps? Maybe I could follow the same. I am pretty sure it's my local env.

**Comment by andreichalapco** [comment]
So I've built Ray (Python only by following the documentation at https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray-python-only). 
Next I've installed all dependencies via: ```pip install -r python/requirements.txt``` and lastly I run the test via 
```python -m pytest -v python/ray/tests/test_mini.py```

**Comment by rickyyx** [comment]
Thanks @andreichalapco 
Also, just for full disclosure - we will be working on python3.10 support for 2.2 so I will maybe revisit this in the next few days (or a week or two).

**Comment by andreichalapco** [comment]
No problem! Just wanted to let you know. Just wanted to make a small contribution :)

**Comment by pcmoritz** [comment]
@andreichalapco Do you think you can help here and create a PR since you already have a fix? That would be really appreciated.

We do want to make sure there are no deprecation warnings in our code!
