### ISSUE TITLE
[rllib] Hindsight Experience Replay (HER) implementation

### ISSUE THREAD

**Issue by rcremese** [ray-project/ray#29397]
### Description

I just try to reactivate an old feature request (https://github.com/ray-project/ray/issues/8526)
Is there any chance to have an implementation of [HER](https://proceedings.neurips.cc/paper/2017/hash/453fadbd8a1a3af50a9df4df899537b5-Abstract.html) in rllib ? If not, what is needed to be modified to implement it ? 

I just started to use rllib and due to the abscence of this feature I shifted to Stable Baseline, which is not best move to do (I know). I would be ready to contribute if someone points me to the right direction.

### Use case

Based on [Andrychowicz, M., Wolski, F., Ray, A., Schneider, J., Fong, R., Welinder, P., ... & Zaremba, W. (2017). Hindsight experience replay. Advances in neural information processing systems, 30](https://proceedings.neurips.cc/paper/2017/hash/453fadbd8a1a3af50a9df4df899537b5-Abstract.html), this feature speeds-up training for off-policy RL algorithm like SAC.

**Comment by ls3030** [comment]
I cannot believe it is August 2023 and Ray still does not have Hindsight Experience Replay but Stable Baselines does. HER is a very powerful way to improve SAC. Please open this enhancement and add to Ray. This has been requested in 2020, 2021, 2022, and still in 2023.
