### ISSUE TITLE
[release][CI] ml_user_xgboost_gpu_connect_latest failed

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29398]
### What happened + What you expected to happen

[Cluster](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_6g2uwk2rawaXG4LjNSRZpDf2?drivers-section=interactive-sessions)

[Build ](https://buildkite.com/ray-project/release-tests-branch/builds/1123#0183d941-484f-45a8-b1ad-26f1d1e2e2e0)

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by matthewdeng** [comment]
Looks transient based on the retry

**Comment by matthewdeng** [comment]
@jiaodong  can you take a look and see if this should be a release blocker? I think it might be an xgboost issue, but the part that worries me is that the error was not safely handled/terminated, but instead it just hangs.

**Comment by jiaodong** [comment]
trying my best along with two other new release blockers that popped up today

**Comment by jiaodong** [comment]
looks like just flakiness to me. Kai helped to kick off a retry on the failed buildkite run and it passed: https://buildkite.com/ray-project/release-tests-branch/builds/1123#0183e2d3-f26e-4d87-96da-7018069fd066

**Comment by jiaodong** [comment]
New issue discovered by this is we left the cluster running much longer than needed with 4 p3.2xlarge hosts .. that costs us $350 that could've been just < $5 on the happy path. Looking into client timeout error now.

**Comment by rickyyx** [comment]
So I guess I will remove release-blocker but keep the issue open.

**Comment by hora-anyscale** [comment]
Per Triage Sync: closing as transient, if it happens again re-open
