### ISSUE TITLE
[Docker] ray serve is not able to be used in ray-ml image

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#29396]
### What happened + What you expected to happen

FastAPI is pined in the requirements.txt file, but ray-ml image is still installing the 0.85.0 version

### Versions / Dependencies

N/A

### Reproduction script

N/A

**Comment by amogkam** [comment]
Reopening to track cherry pick

**Comment by rickyyx** [comment]
Could this one be closed after merging #29481 ?
