### ISSUE TITLE
[docs/docker] Add documentation for development with Ray Dockers

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#29416]
### Description

Some users have historically tried to use Ray Dockers for development purposes. If we can add documentation for these issues/questions, this would be great!

This has run into a variety of issues/gotchas. For example:

https://stackoverflow.com/questions/65884838/docker-permissions-issue-writing-to-txt-file-with-simple-python-script 
https://github.com/ray-project/ray/issues/13602#issue-791002990

Also there have been asks around docker compose:

* https://github.com/MarvinSt/ray-docker-compose
* https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1660689729338179

**Comment by rkooo567** [comment]
+1. I've seen many users starting from deploying on docker
