### ISSUE TITLE
[xray] Object manager does not limit number of outgoing connections for Pull requests

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#2941]
### Describe the problem
`Pull` requests are sent by the object manager on the main thread using a synchronous WriteMessage. This artificially limited the number of connections to each remote object manager to 1. Once this is switched to using an asynchronous WriteMessage (#2939), there is no longer any limit to the number of connections per remote object manager.

We should fix this by limiting the total number of connections allowed in the object manager `ConnectionPool`.

**Comment by guoyuhong** [comment]
FYI: 
https://github.com/ray-project/ray/pull/2259

**Comment by stephanie-wang** [comment]
Thanks, @guoyuhong. The plan is to send `Pull` requests asynchronously in the future, so even though there will still only be one thread accessing the connection pool, we will have to make sure that it doesn't accidentally create multiple connections.

Are you interested in implementing this (once the asynchronous `WriteMessage` change is implemented and merged)?

**Comment by guoyuhong** [comment]
Yes, of course. Please cc me when you have the `WriteMessage` change ready.

**Comment by robertnishihara** [comment]
@guoyuhong, #2939 has been fixed now :)
