### ISSUE TITLE
[runtime env / doc] Clarity for Docker vs Runtime envs /ray-core/handling-dependencies.html

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#29415]
I got a question from a user here:

```
Why do you need to specify a runtimeEnv as part of a job if you can load in a docker image?
I think it just makes it confusing - like I'm not sure if there are multiple ways to do it or if I'm not doing it right
If I push my own docker layer up I can just use that in the cluster yaml right
```

cc @architkulkarni can you take a look at this? Specifically, add a section in the documentation about Ray runtime envs vs docker and when you should use each.

**Comment by architkulkarni** [comment]
<img width="1130" alt="Screen Shot 2022-10-17 at 3 06 29 PM" src="https://user-images.githubusercontent.com/5459654/196292697-605acb13-0a8e-4040-8f3a-0e2fbc3543b5.png">
Currently we have "For production usage or non-changing environments, we recommend installing your dependencies into a container image and specifying the image using the Cluster Launcher. For dynamic environments (e.g. for development and experimentation), we recommend using runtime environments." 

I can try to make it more prominent and add more details
