### ISSUE TITLE
[Core] NCCL_BLOCKING_WAIT=1 leads to performance regression

### ISSUE THREAD

**Issue by lly-zero-one** [ray-project/ray#29419]
### What happened + What you expected to happen

Looks like NCCL_BLOCKING_WAIT is set to 1 for detecting node failure: https://github.com/ray-project/ray/blob/d99eff919bf785f911e4eebc87ddc4960344a139/python/ray/train/torch/config.py#L103 

But this will lead to significant performance regression, since CPU will stop scheduling new operator during the waiting. Can we just default it to zero to avoid the user setting in env variable?

More detail can be found in https://github.com/pytorch/pytorch/issues/87036

### Versions / Dependencies

2.0

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by hora-anyscale** [comment]
Per Triage Sync: significant performance regression, please prioritize for 2.2?

**Comment by amogkam** [comment]
Thanks @lly-zero-one for raising the issue!

PR to change this is here: #29562 
The PR is currently blocked on: https://github.com/ray-project/ray/issues/29576
