### ISSUE TITLE
how to  pip install ray==0.7.1 on windows

### ISSUE THREAD

**Issue by nankaimy** [ray-project/ray#29455]
### What happened + What you expected to happen

how to  pip install ray==0.7.1 on windows,thanks

### Versions / Dependencies

how to  pip install ray==0.7.1 on windows,thanks

### Reproduction script

how to  pip install ray==0.7.1 on windows,thanks

**Comment by Iqigai** [comment]
I have a similar issue, it is impossible to install any version of ray on windows 10, python 3.10 I get the message:
C:\WINDOWS\system32>pip install ray
ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray

**Comment by duburcqa** [comment]
`ray==0.7.1` is more than 3 years old (Jul 2019), way before Windows was officially supported, not to mention Python 3.8 and upward...
