### ISSUE TITLE
[Core][OOM Prevention] Calculate memory usage in cgroup v2.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#29474]
### What happened + What you expected to happen

Today we calculate the memory usage for  cgroup v1 and bare linux; but the support for cgroup v2 is yet to be implemented. (reference PR https://github.com/ray-project/ray/pull/29103)

We can follow https://github.com/google/cadvisor/blob/master/container/libcontainer/handler.go#L836 to calculate the current memory usage for cgroup v2.

Ideally we want add test in CI for this too. This might require you to start a cgroup based test, there are some examples you can follow https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tests/test_gcs_ha_e2e.py

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarng** [comment]
Adding https://github.com/ray-project/ray/issues/29873 to add CI test
