### ISSUE TITLE
[CI] `linux://rllib:connectors/tests/test_agent` is failing/flaky on master/release 2.1 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29472]
- 2a2001d95f9fcddd763043efecc1512e32ff2f36 FAILED [Buildkite :brain: RLlib: Everything else (env-, evaluation-, ... dirs)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/533#0183d797-df76-4ef6-908d-84530f503426)
- 9fb3bc5639493c0d6756d57b6ae02581f138df87 FAILED [Buildkite :brain: RLlib: Everything else (env-, evaluation-, ... dirs)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/524#0183d455-050d-42c4-a19e-306a6340ec55)
- d62373f0b7d0e492797b787c91517b8e1de93740 FAILED [Buildkite :brain: RLlib: Everything else (env-, evaluation-, ... dirs)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/511#0183d327-60f3-4b69-a55a-bce6c21ecf24)
- 0be436768a65ba2bcf1c2c5f1073131940e4f0f5 FAILED [Buildkite :brain: RLlib: Everything else (env-, evaluation-, ... dirs)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/421#0183b449-2baa-4c64-a6cb-aa4c81ba8b98)
- 47a46e49b5094877240eed120646ac293c656cef FAILED [Buildkite :brain: RLlib: Everything else (env-, evaluation-, ... dirs)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/418#0183b414-779c-49ba-b75e-f5b3cb617540)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://rllib:connectors/tests/test_agent-END
....

**Comment by rickyyx** [comment]
Release [branch timeout](https://buildkite.com/ray-project/oss-ci-build-branch/builds/598#0183f121-d061-4346-91a3-24c87d6ac7c2)

Let me know if this should be a release blocker.

**Comment by gjoliver** [comment]
this one is already fixed in MASTER. I don't know if we need to cherry pick the fix, since it's a fix for the test.
let me know.
otherwise, it should be safe to just close this one.

**Comment by rickyyx** [comment]
Cherry picked in.
