### ISSUE TITLE
[Datasets] Concatenating large chunks of string/binary/list columns in Arrow tables can cause offset overflow.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#29492]
There's a [long-known bug in Arrow](https://issues.apache.org/jira/browse/ARROW-9773) where concatenating large chunks of string/binary/list columns in Arrow tables can cause offset overflow. We should try to work around this at the Datasets level, detecting this at concatenation time and upcasting the 32 bit int offsets to 64 bit offsets **before** the concatenation, if possible.

**Comment by pcmoritz** [comment]
Linking the Arrow github issue here: https://github.com/apache/arrow/issues/25822

**Comment by scottjlee** [comment]
This results in errors similar to:
```
pyarrow.lib.ArrowInvalid: offset overflow while concatenating arrays
```

With an increasing number of users reading large datasets (e.g. https://github.com/ray-project/ray/issues/41411), we should prioritize this work.

**Comment by alexeykudinkin** [comment]
Related issues

 - https://github.com/ray-project/ray/issues/46434
 - https://github.com/ray-project/ray/issues/47448
