### ISSUE TITLE
[xray] Heartbeats on large clusters lead to Redis congestion

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#2949]
### Describe the problem
Heartbeats are implemented as an all-to-all pubsub. Each node subscribes to the same Redis channel. On an interval, each node publishes a heartbeat to the channel and in turn receives a heartbeat per node in the cluster. If N is the number of nodes, this will lead to N^2 communication, which causes Redis congestion on larger clusters. This can lead to delays in heartbeat delivery, causing nodes to get marked mistakenly as dead.

A solution is to batch recent heartbeats at a central location (e.g., the raylet monitor) and publish the batch instead, so that we only have 2N messages every heartbeat interval.

@ujvl and I have an initial implementation [here](https://github.com/stephanie-wang/ray/commits/batch-heartbeats).

**Comment by robertnishihara** [comment]
Fixed by https://github.com/ray-project/ray/pull/3011.
