### ISSUE TITLE
[xray] Visualization/debugging tool for task and object lifetime on the backend

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#2951]
### Describe the problem
It is very difficult to debug performance in the backend and the only options right now are basically to log different events and/or use boost::asio's [handler tracking](https://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/overview/core/handler_tracking.html). The former is time-consuming and the latter is difficult to parse.

It would be great if we had some type of debugging tool that allowed us to discover when relevant events happened in the backend for a given task or object. For a given task, I would like to quickly learn when the task was:
- received
- forwarded
- ready for execution
- assigned to a worker

For a given object, I would like to quickly learn when:
- the object is local or evicted
- a `Pull` request is sent for the object
- an object data transfer from a remote object manager starts and ends
- an object data transfer to a remote object manager starts and ends

If we could also quickly look up task specifications, we could also discover the above object information for one of its arguments, which is very useful for determining why a task might be slow to be assigned, for instance.

Open to other useful information to include and what the UI/UX should be.

**Comment by micafan** [comment]
Our team is trying to solve problems such as health monitoring and performance analysis. 

For now, it is hard to know the bottleneck of the system, or what kind and how many errors have occurred. The log does not contain all informations. Even if it is, outputting and processing logs is very expensive, more importantly, it will affect performance.

Our solution is to collect statistics on necessary paths.e.g.: the number of errors,  the number of queued tasks, time overhead for each phase of tasks(percentile value, such as P99). 
With statistics, most of the monitoring and analysis problems can be solved.  In this case, it’s no need to record details for each task or object.

**Comment by ericl** [comment]
I think both approaches are necessary: for overall health monitoring and analysis, aggregate statistics should be enough. However for debugging, often you will need to know the exact sequence of events that occurred to diagnose the root cause of the issues.

There are open source tools available for both statistics reporting and tracing/debugging. For example, https://github.com/census-instrumentation/opencensus-cpp/blob/master/README.md integrates metrics and tracing and can export to visualization systems like zipkin.

**Comment by ericl** [comment]
It seems you can model objects and task lifetimes with span objects https://github.com/census-instrumentation/opencensus-cpp/blob/master/opencensus/trace/examples/span_example.cc

So for example, a local object can be 1:1 with a local span. The span can have annotations for events associated with it, and linked with data transfer requests / copies of the object on other nodes. You can then visualize this by searching for the object span in zipkin, or by telling census to print to stdout.

**Comment by zhijunfu** [comment]
Something like ETW tracing on windows, or dtrace on unix?
