### ISSUE TITLE
[Datasets] Make it easier to run all data workload in a heterogeneous cluster

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#29519]
It's an architecture pattern in Ray to run data workload in a group of CPU nodes (aka. data nodes) and ML workload in a group of GPU nodes (aka. training nodes), forming a heterogeneous cluster. We already have a few users run this in production successfully.

The way to achieve this via setting custom_resource for CPU nodes (e.g. {"DATA_NODE": 1000000}, 1 million units of a virtual custom resource called DATA_NODE), and then when launching a ray task/actor, user specify that it's required to have DATA_NODE resource to run the task/actor. Ray will do the right thing to schedule them onto nodes with DATA_NODE resource available.

The UX problem of this is that the user will have to set this resource requirement in each Dataset API, otherwise the execution may be scheduled onto GPU nodes.

A better way is to have a custom resource flag in DatasetContext which applies to all Dataset operations so they all happen in data nodes.

cc @jjyao @yuduber

**Comment by ericl** [comment]
Hmm isn't an easier way to set num_cpus=0 for the GPU nodes, if you really don't want any stray tasks running on it?

**Comment by jianoaix** [comment]
Yeah, that should work. @yuduber is this sufficient/convenient for your use case?

**Comment by richardliaw** [comment]
Closing this for now since it seems like there is a workaround. @yuduber can reopen if necessary
