### ISSUE TITLE
[air] Preprocessing with new column names does not work for CPU processing

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#29524]
### What happened + What you expected to happen

I'm working on smoke testing in the PR: https://github.com/ray-project/ray/pull/29173

In particular, I'm trying to introduce a smoke test for the gpu_batch_prediction test. This smoke test will run on CPU.

https://github.com/ray-project/ray/pull/29173/files#diff-53bdec7252c0a7c7488d370da89e1b552e05af54afb6e053fd2de1b36b6ab2eb

When running this, I run into this issue:

```
ray.exceptions.RayTaskError(KeyError): ray::BlockWorker.map_block_nosplit() (pid=6668, ip=127.0.0.1, repr=<ray.data._internal.compute.BlockWorker object at 0x116eddc10>)
  File "/Users/kai/coding/ray/python/ray/data/_internal/compute.py", line 318, in map_block_nosplit
    **fn_kwargs,
  File "/Users/kai/coding/ray/python/ray/data/_internal/compute.py", line 484, in _map_block_nosplit
    for new_block in block_fn(blocks, *fn_args, **fn_kwargs):
  File "/Users/kai/coding/ray/python/ray/data/dataset.py", line 547, in transform
    batch = batch_fn(batch, *fn_args, **fn_kwargs)
  File "/Users/kai/coding/ray/python/ray/train/batch_predictor.py", line 199, in __call__
    prediction_batch = batch[feature_columns]
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/indexing.py", line 1374, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['image'], dtype='object')] are in the [columns]"
```

The problem seems to be that in GPU prediction, we apply the preprocessor first and then do feature column selection, but in CPU prediction this is reversed (because fused?).

### Versions / Dependencies

master

### Reproduction script

```
python air_tests/air_benchmarks/workloads/gpu_batch_prediction.py --dataset-size-gb=1 --smoke-test
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
As a success criteria, this issue should be closed once we have added unit smoke tests for gpu_batch_prediction and pytorch_training_e2e

**Comment by clarkzinzow** [comment]
Oh wow, this is a great point! We should definitely delay the feature column selection until preprocessing has completed within the predictor.

@amogkam What if we pushed feature column selection into [`Predictor.predict(batch, feature_columns, **kwargs)`](https://github.com/ray-project/ray/blob/02f911ce78137cb63ecb685a8ef8e56dcb60062c/python/ray/train/batch_predictor.py#L198-L203) as a top-level arg and did the column selection after applying the preprocessor, before handing off to [`Predictor._predict_pandas()`](https://github.com/ray-project/ray/blob/02f911ce78137cb63ecb685a8ef8e56dcb60062c/python/ray/train/predictor.py#L158)?

**Comment by amogkam** [comment]
@clarkzinzow I think we should separate out all of these things (preprocessing, feature column selection, prediction, and keep column selection) as separate stages. Then in BatchPredictor, make the dataset lazy and therefore delegate to Datasets to make all the stage fusion decisions.

At the BatchPredictor level, we don't need to do stage fusion special casing like this. Stage fusion is contained in one level of abstraction.

Does this make sense to you @clarkzinzow? I'll write up an RFC if so.

**Comment by amogkam** [comment]
So concretely, feature column and keep column selection can just become preprocessors.
