### ISSUE TITLE
[Tune] [Docs] `PlacementGroupFactory` reference should link to Placement Group guide

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29525]
### Description

[ray.tune.execution.placement_groups.PlacementGroupFactory](https://docs.ray.io/en/latest/tune/api_docs/internals.html#ray.tune.execution.placement_groups.PlacementGroupFactory) talks about placement groups and bundles, but doesn't define either term. So, we should link to the [placement group user guide](https://docs.ray.io/en/latest/ray-core/placement-group.html).

### Link

https://docs.ray.io/en/latest/tune/api_docs/internals.html#ray.tune.execution.placement_groups.PlacementGroupFactory

**Comment by ayushthe1** [comment]
hey @bveeramani ,i would like to work on this issue.

**Comment by ayushthe1** [comment]
#self-assign

**Comment by ayushthe1** [comment]
hey @bveeramani ,i am getting some confusion in how to add link in `internal.rst` file. I see that it inside `internal.rst` file there is a section called [PlacementGroupFactory](https://github.com/ray-project/ray/blob/0959f44b6fc217a4f2766ed46a721eb79b067b2c/doc/source/tune/api_docs/internals.rst#placementgroupfactory) which points to [class PlacementGroupFactory](https://github.com/ray-project/ray/blob/305905f469b0c8c351670b276b54a0d3d77bc242/python/ray/tune/execution/placement_groups.py#L73) in file `placement_groups.py`. 
So in which of the 2 files should i add the link ?

**Comment by bveeramani** [comment]
Hey @ayushthe1, thanks for taking on this issue!

I don't think you actually need to update `internal.rst`. You could just replace
```
placement group
``` 
with 
```
:ref:`placement groups <ray-placement-group-doc-ref>`
```

in the `PlacementGroupFactory` docstring. 

For example,

```
class PlacementGroupFactory:
    """Wrapper class that creates placement groups for trials.

    This function should be used to define resource requests for Ray Tune
    trials. It holds the parameters to create 
    :ref:`placement groups <ray-placement-group-doc-ref>`.
    At a minimum, this will hold at least one bundle specifying the
    resource requirements for each trial:

    ...
```

**Comment by ayushthe1** [comment]
Thanks @bveeramani ,i made a pr for this issue ,could you please review it.
