### ISSUE TITLE
How to config the backend logging flexibly

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#2953]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**: 0.5X
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

Current backend logging level is fixed. If we want to change the logging level, we need to do re-compiling. Our users have the following requirements:
1. The logging level should be changed at runtime without re-compiling. 
2. The logging level in the client dynamic lib (e.g. local_scheducler_client, plasma client in both java and python) should also be able to get changed.
3. The logging level for stderr and logging file should be different. 

For Requirement 1, what do you think is the best practice?
1. Environment variable: users need to change the environment variables for all machines in a cluster, which is not convenient. 
2. Argument: this is not convenient for dynamic libs.
3. Using config files: Java uses this method. Will backend use this also?

**Comment by guoyuhong** [comment]
@robertnishihara @pcmoritz @stephanie-wang

**Comment by robertnishihara** [comment]
@guoyuhong to clarify, recompiling is too much work, but it is ok to restart the cluster to change the logging level, is that right?

We should probably make it possible to the relevant information into `ray start` via a command line argument (the argument could either be the logging level or it could be a path to a config file).

However, all of these solutions require doing work on every machine (either changing the command line argument or modifying the config file), right?

**Comment by guoyuhong** [comment]
@robertnishihara Yes, restarting is fine. 
If we change the config file and leverage the deploying system to deploy the file and restart the binary, we don't necessarily to do it in every machine.

**Comment by mylinyuzhi** [comment]
Actually in a production environment，we need the process reload the level config without restart, this is very helpful for troubleshooting

**Comment by rkooo567** [comment]
This is already done by env var.
