### ISSUE TITLE
[Core] Eagerly importing non-core subpackages slows down Python worker startup

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#29557]
Certain Ray subpackages are expensive to import, either due to their size, dependencies, or their import-time logic that must be executed. E.g. a change in a Datasets import caused a regression for the many_tasks nightly test, despite many_tasks only using Ray Core. However, we want subpackages like `data` and `workflow` to be accessible via attributes on a simple `import ray` import:
```python
import ray
ds = ray.data.read_parquet(...)
```

## Possible Solution

One solution is to delay the import of these expensive subpackages until attribute access, e.g. none of the Datasets code will be run until `ray.data` is accessed.

**Comment by rkooo567** [comment]
This is the issue that we are handling from the pr right?

**Comment by clarkzinzow** [comment]
PR reverted due to flaky GCS tests: https://github.com/ray-project/ray/pull/29659

**Comment by clarng** [comment]
bumping this to P0 since we believe it is causing nightly failure : https://github.com/ray-project/ray/issues/29911
