### ISSUE TITLE
[Datasets] Print out dataset statistics automatically after execution

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29560]
### Description

Datasets statistics are very helpful for debugging and monitoring status. Currently the stats can only be printed manually via [Dataset.stats()](https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L3524) method from user side. This is inconvinent and add overhead from user side. We should allow to print out dataset statistics automatically after executing the dataset. This behavior can be disabled by default, and add a new config in `DatasetContext` to allow user to enable it.

Code pointers:
* [Dataset.stats()](https://github.com/ray-project/ray/blob/master/python/ray/data/dataset.py#L3524)
* [ExecutionPlan.stats()](https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/plan.py#L341)
* [ExecutionPlan.execute()](https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/plan.py#L284)
* [DatasetContext](https://github.com/ray-project/ray/blob/master/python/ray/data/context.py#L82)

**Comment by clarkzinzow** [comment]
I was thinking about this a few weeks ago, always printing out the Datasets stats by default (disablable via the dataset context or an arg) makes a lot of sense once we have lazy execution by default.

**Comment by clarkzinzow** [comment]
For eager execution, we should only do this if we can print out incremental stats (e.g. for the most recently executed stage) rather than the aggregate stats (for all stages), and I don't know if we should print them out by default since that may be a bit spammy. 🤔 Could be controlled by the progress bar flag, I suppose.

**Comment by c21** [comment]
> For eager execution, we should only do this if we can print out incremental stats (e.g. for the most recently executed stage) rather than the aggregate stats (for all stages)

Yes, I agree. Print out all stages are too spammy. As part of the issue, we can add logic to print the newly executed stages stats.

**Comment by rkooo567** [comment]
Another useful feature can be CLI? similar to state API (ray-data stats [stage_id]) or sth like that.
