### ISSUE TITLE
[rllib]Misleading use of sgd_batch_size & train_batch_size in multi_gpu_optimizer

### ISSUE THREAD

**Issue by praveen-palanisamy** [ray-project/ray#2957]
### Describe the problem

The use of `sgd_batch_size` and `train_batch_size` in `multi_gpu_optimizer.py` is misleading. As per the [discussion](https://groups.google.com/forum/#!topic/ray-dev/k34oCTCJ6os), the intended use is indeed to do a number of epochs with minibatchs (M) sampled from the training batch within each outer-loop iteration (Currently used only by the Actor-Critic style PPO implementation)

The minibatch size (through the `sgd_minibatch_size` config parameter) is supposed to be << `train_batch_size` but, in the current implementation of `localMultiGPUOptimizer`, the `train_batch_size` is more or less ignored by the optimizer interface (?) and the `sgd_minibatch_size` is used as the batch_size to perform `num_sgd_iter` number of SGD updates.
 
##### Minimal example to illustrate the misuse:

`python ray/rllib/train.py --env=PongDeterministic-v4 --run=PPO --config '{"num_workers":2, "sample_batch_size":2, "sgd_minibatch_size":16, "train_batch_size":4, "num_gpus":2}`

Note that the `"sgd_minibatch_size":16` is >> `"train_batch_size":4` but RLlib trains it with no complains and the training batch size used in an iteration is not 64. This makes it difficult to compare performance.

**Comment by ericl** [comment]
I don't think train_batch_size is ignored right? https://github.com/ray-project/ray/blob/995ac24a2ca9a0623cb2598c897d5fefb508a523/python/ray/rllib/optimizers/multi_gpu_optimizer.py#L102

I guess in your example, what's going on is that the minibatch size is rounded down to 4. So it becomes non-minibatch SGD. Is that the concern?

**Comment by praveen-palanisamy** [comment]
Hmmm. The capping of sgd_batch_size to 4 in the above example should be fine. Not a concern.

So, this dig started because the number of samples used to train in one outer loop iter by PPO was not matching the intended values. I think I pre-maturely settled on the suspicion that it is due to the above described mismatch. It actually turns out to be due to the batch mode ( especially with complete_episodes). 

As I understand, in the complete_episodes batch mode, the minibatch-sgd/train-batch size configs will not have any effect & the number of steps used in one training iter totally depends on the env & its dynamics (hopefully they have timeouts). right?

**Comment by praveen-palanisamy** [comment]
Is this not a concern in general?
Because, if there are a number of policy evaluators with several env instances per evaluator/worker  and if each of the rollout it going to have infinite horizon (complete episodes), then the actual batch size used in one SGD step may be much higher & probably may result in GPU OOM.

**Comment by ericl** [comment]
I agree the default behavior of complete_episodes probably isn't great. We could potentially default to truncate_episodes instead, to make the batch size fixed.

**Comment by ericl** [comment]
@praveen-palanisamy let me know what you think of https://github.com/ray-project/ray/pull/2967

**Comment by praveen-palanisamy** [comment]
The change to the default looks fine & will help in some cases to avoid unexpected behaviors by default.

**Comment by praveen-palanisamy** [comment]
Closing the issue since enough clarify was brought in by #2967  way back in time.
