### ISSUE TITLE
[Datasets] `Dataset.take` flattens `ArrowTensorType` tensors

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29590]
### What happened + What you expected to happen

Called `Dataset.take` on a dataset containing `ArrowTensorType` tensors. Expected NumPy arrays, but got a flattened list instead. 

See repro.

### Versions / Dependencies

**Ray**: de238dd626a48a16c8b3cd006f3482db75f63a83
**Arrow**: `pyarrow==9.0.0`

### Reproduction script

```
import numpy as np
import pandas as pd
import ray
from ray.data.extensions import TensorArray

arrow_ds = ray.data.from_items(4 * [{"image": np.zeros((32, 32, 3))}])

df = pd.DataFrame({"image": TensorArray(np.zeros([4, 32, 32, 3]))})
pandas_ds = ray.data.from_pandas(df)

print(arrow_ds)
# Dataset(num_blocks=4, num_rows=4, schema={image: ArrowTensorType(shape=(32, 32, 3), dtype=double)})
print(pandas_ds)
# Dataset(num_blocks=1, num_rows=4, schema={image: TensorDtype(shape=(32, 32, 3), dtype=float64)})

arrow_image = arrow_ds.take(1)[0]["image"]
print(type(arrow_image))  # <class 'list'>
print(len(arrow_image))  # 3072

pandas_image = pandas_ds.take(1)[0]["image"]
print(type(pandas_image))  # <class 'numpy.ndarray'>
print(pandas_image.shape)  # (32, 32, 3)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarkzinzow** [comment]
This is a bug in Arrow 8+, fixed in this PR: https://github.com/ray-project/ray/pull/29161

Closing since we don't yet support Arrow 8+ in Datasets.
