### ISSUE TITLE
[Observability] No way to get head node ID

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#29607]
### Description

Ray has the concept of "head node" and "worker nodes", but there is no Ray API to get which node is the head node.  We should surface this information in the State API somehow.

### Use case

Certain Ray processes (GCS, dashboard head) only run on the head node.  For debugging these processes, it's useful to run certain commands specifically on the head node.  To do this programmatically with Ray (e.g. using `ray job submit`), we need to know the head node ID.

### Potential Implementations 
**Adding the head node info:** 
We could add a `--head` flag to the raylet start-up flag: https://github.com/ray-project/ray/blob/70fcb2a8d077bca2b755af67d002ef6db625a7db/python/ray/_private/services.py#L1587-L1589

And, then propogate this information to the GCS [node's table](https://github.com/ray-project/ray/blob/d1d32d715e7de18093edc8a47bc3f06fcd5b5299/src/ray/protobuf/gcs.proto#L284-L291), when the node registers itself with [GCS](https://github.com/ray-project/ray/blob/4d0ce8d383d76b1754e04bc2d3e21f6072e2d35d/src/ray/raylet/raylet.cc#L126).  

**Propogating the info to state API**
We could then include the information [here](https://github.com/ray-project/ray/blob/c1916b040e848ef2e72a3d0e71e366d90fd29771/python/ray/experimental/state/common.py#L420), we should be able to get it automatically when we [query GCS ](https://github.com/ray-project/ray/blob/e331f6ebaff01d051790df87f5b62d4751833834/src/ray/gcs/gcs_server/gcs_node_manager.cc#L148-L163) for the nodes info afterwards

**Comment by architkulkarni** [comment]
cc @rkooo567 Happy to submit a PR for this if you have some pointers! I guess there first needs to be a design for how best to surface this information in the State API.

**Comment by rkooo567** [comment]
I think we can pass --head = 1 / 0 to the head node raylet and include that information to GCS' node info table!

**Comment by rkooo567** [comment]
and it'd be great if you can help on this

**Comment by rkooo567** [comment]
Ping me or schedule a meeting if you need more information!

**Comment by rkooo567** [comment]
I will assign you @architkulkarni as I know you are working on this

**Comment by valiantljk** [comment]
Hi @architkulkarni @rkooo567 , I think this is a very useful feature. Even though Ray is trying to target a serverless architecture, where no explicit distinction of head and worker should exist. Current Ray architecture (e.g., gcs on head only), and lots of usecases (tasks scheduling avoids head, etc), are still prefer a clear boundary of head and workers. So something like this will be very helpful:
```
ray.get_head_id()
```

**Comment by rkooo567** [comment]
@rickyyx will fix this issue.

**Comment by rickyyx** [comment]
This is currently done - one could have the `is_head_node` info in output of `ray list nodes`

**Comment by danielgafni** [comment]
Corresponding Python code: 

```python
def get_head_node_id() -> str:
    from ray.util import state

    nodes = state.list_nodes(filters=[("is_head_node", "=", True)])

    assert len(nodes) == 1, "There should be exactly one head node"

    return nodes[0].node_id
```
