### ISSUE TITLE
[Dashboard] Can't see GPU usage in `ray-ml:latest-gpu` Docker image 

### ISSUE THREAD

**Issue by liangyu-1** [ray-project/ray#29602]
### What happened + What you expected to happen

ray cluster mode dashboard, cannot see the gpu usage

docker image: ray-ml:latest-gpu

when I reinstall gpustat, then I cannot use the tensorflow

### Versions / Dependencies

ray 2.0.0
ray-ml:latest-gpu
python 3.7

### Reproduction script

When I import gpustat.core in the docker, it shows this:
Please reinstall gpustat
pip install -force-reinstall gpustat 
if it still does not fix the problem, manually fix midianlpy installation
pip uninstall nvidia-ml-py3
pip install --force-reinstall nvidia-ml-py<=11.495.46

**Comment by liangyu-1** [comment]
this is the screenshot when I import gpustat inside the docker:
![WechatIMG2854](https://user-images.githubusercontent.com/62563545/197717703-36ce067a-0eda-431c-a8de-b511f6a38a3b.png)

**Comment by rkooo567** [comment]
cc @DmitriGekhtman do you have any guess?

**Comment by DmitriGekhtman** [comment]
Just a process question --
@kevin85421 I seem to recall you encountered the same thing on K8s. Did you post an issue then? (Is this a duplicate?)

@liangyu-1 can you tell us about how you set up your Ray cluster? (Did you use the cluster launcher to set up Ray on VMs? Are you using Kubernetes?)

**Comment by bveeramani** [comment]
Hey folks, look like this is a known issue that's been fixed on master: https://github.com/ray-project/ray/pull/26295#issuecomment-1189832249.

@liangyu-1 the nightly `rayproject/ray-ml:nightly-gpu` image work.

**Comment by rkooo567** [comment]
@liangyu-1 can you verify that? Please reopen the issue if this is not fixed in the master!
