### ISSUE TITLE
[jobs] Define a proto API for checking job status

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#29621]
## The Problem

Currently, we have two "overlapping" concepts of jobs:
- GCS Jobs (a Ray driver)
- Submitted jobs (Job submitted to the Ray job server)

There are two ways to check on the status of jobs: using the GCS `ListAllJobs` endpoint (which contains only partial data), and the dashboard list jobs endpoint.

Currently to get full job status from the cluster, you need to query both and join them (based on `gcs_job_table_entry.job_config.metadata["job_submission_id"])`. This has a couple problems:
1. Callers need to hit two separate endpoints, one of which is returning pickled Python bytes (difficult to interpret in other languages).
2. The cluster doesn't fate share with the job server, so it's possible for jobs to still be running even if the job server is down.

## Proposed Solution

1. Have the job server store extended JobInfo in a proto or JSON form, instead of pickled Python data. The proto/JSON JobInfo can still be stored in the internal KV.
2. Enhance `ListAllJobs` to pre-join the data from `job_submission_id` in the internal KV. This means that GCS will need to lookup the extended JobInfo for jobs that have `job_submission_id` defined.
3. Add a `limit` field to ListAllJobs to bound the number of returned jobs.

**Comment by rkooo567** [comment]
Hey @ericl is this something we should prioritize for ray 2.2?

**Comment by architkulkarni** [comment]
@ericl I likely won't have time to finish this before Ray 2.2 because I need to prioritize Jobs GA, is that okay or are there other 2.2 features that depend on this?  Because it's an internal enhancement that doesn't affect the user-facing API, I think it can be done after Jobs GA.

**Comment by architkulkarni** [comment]
Discussed offline, this remains P1 but will likely be fixed after the Ray 2.2 branch cut.

**Comment by hora-anyscale** [comment]
If there is alignment on the above, move to the "Ray 2.3" label?
