### ISSUE TITLE
[CI] `linux://python/ray/tests:test_object_manager` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29625]
- 031fb44311da77ef93f45f74a3a4560ef25cb0bd FAILED [Buildkite :redis: (External Redis) (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/686#01840b14-9feb-416b-8f85-0f77820ec17f)
- c0284c071dc16b3481d8488a3fe3a9311b8ddd60 FAILED [Buildkite :redis: (External Redis) (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/662#0183fbdc-ac5b-43c1-8894-0a143216ff84)
- 7c287ac4d052d0e4c951fe5b074a71fd687a0a60 FAILED [Buildkite :redis: (External Redis) (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/618#0183f3f6-226a-41e5-8c92-c40a74e1cbe8)
- 426f5399d4d850914eced3883887306620b49355 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/582#0183ecd1-6771-43f2-89d2-a4bf47976c80)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_object_manager-END
....

**Comment by scv119** [comment]
looks the test is inherently flaky?
