### ISSUE TITLE
Ray crashes when writing large df to csv

### ISSUE THREAD

**Issue by RehanSD** [ray-project/ray#29668]
### What happened + What you expected to happen

When Modin writes a large dataframe to CSV, the Ray workers OOM and then crash, and the whole process hangs. More information can be found [here](https://github.com/modin-project/modin/issues/2999).

### Versions / Dependencies

Ray 2.0.1
Ubuntu 20.04

### Reproduction script

```python
import modin.pandas as pd
df = pd.concat([
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-02.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-03.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-04.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-05.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-06.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-07.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-08.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-09.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-10.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-11.csv", quoting=3),
pd.read_csv("s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-12.csv", quoting=3),
])

df.to_csv('nyc_taxi.csv', index=False)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jianoaix** [comment]
@RehanSD Can you provide a repro script using Ray Data APIs? That'd be easier for Ray team to debug it.

**Comment by richardliaw** [comment]
@jianoaix This isn't using Ray Data.  @RehanSD please create a repro using the Ray APIs (data or core or whatever). Thanks!

**Comment by richardliaw** [comment]
I guess @rkooo567 has been shepherding this.

**Comment by rkooo567** [comment]
@RehanSD how big is each csv file?

**Comment by scv119** [comment]
@RehanSD it really depends on your implementation. i.e. it could be that the library (modin) uses a lot of heap memory when doing the sort; which likely leads to OOM.

We have an experimental feature available in ray master and next release. https://docs.ray.io/en/master/ray-core/scheduling/ray-oom-prevention.html I'd suggest to enable it, it will give you a bit more information if the application is really using excessive memory.

**Comment by scv119** [comment]
cc @clarng

**Comment by YarShev** [comment]
@RehanSD, are we still experiencing the issue?
