### ISSUE TITLE
[CI] Fix `Tune multinode tests` so spot instance preemption doesn't show as flaky

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29669]
Looks like there's an issue in the flaky tracker which causes `Tune multinode tests` to show up as flaky when it shouldn't. According to @simon-mo the test runs were preempted (spot instances) and thus shouldn't show up in the tracker.

see https://anyscaleteam.slack.com/archives/CLJQR6420/p1666641768698169

**Comment by krfricke** [comment]
So the previous failures are due to spot instances failing. Presumable `m5.large` get preempted often. The automatic retries seem to succeed eventually

**Comment by krfricke** [comment]
This should just not turn up in the flaky test tracker I think

**Comment by cadedaniel** [comment]
I will change the title to "Fix `Tune multinode tests` so spot instance preemption doesn't show as flaky"

**Comment by cadedaniel** [comment]
fixed by @simon-mo
