### ISSUE TITLE
Ray restricted podsecuritystandards for enterprise security and Kubeflow integration

### ISSUE THREAD

**Issue by juliusvonkohout** [ray-project/ray#29665]
### Description

@Jeffwan @DmitriGekhtman related to https://github.com/kubeflow/kubeflow/issues/6680 and https://github.com/ray-project/kuberay/issues/502

You can build the OCI images however you want, you just need to adhere to the official safe Kubernetes "Restricted PSP" standard https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted .

If you have a good architecture, just enforcing the restricted PSP on your namespace should be enough. You can also set the pod securitycontext manually to the values from the restricted set. The most important ones are to block anything that starts with host or privilege escalation and runasroot. If your images crash then please check whether you forgot to set proper file permissions on the working directories. If you need help on that level feel free to reach out on the Kubeflow slack or LinkedIn. I can also provide you Podsecuritypolicies if your clusters are below 1.23.

To properly build your images there are thousand of guides out there, but the most common stuff is :
For example use USER 1000:0 at the end of the Dockerfiles to build the OCI image. Make sure working directories are created with 777 file permissions and of course do not use and drop all capabilities such as SYS_ADMIN, SYS_CHROOT (done by the restricted PSP) etc. Use proper networking ports above 1024, do not use insecure setuid or setuid binaries and so on, just the same stuff that you would do for any proper Linux userspace application.

As long as all pods (Worker/head/raylet) run with the restricted PSS that is fine. This is needed to prevent that the cluster can be more easily hacked as described in the kubernetes PSS documentation linked above. Adding isolation within the Worker/Raylet pod is not essential (but still desired in general) for kubeflow integration, since the users will only have access to their own on-demand created kuberay clusters in their own namespaces. They can damage their clusters in their own namespace anyway if they wish to do so.

This can of course happen in parallel with the other integration tasks.

So far i only checked the kuberay implementation here https://github.com/ray-project/ray/issues/14077#issuecomment-1283208595 Please point me to the the other implementation that you want to use instead and the Dockerfiles for the corresponding  OCI images.

### Use case

Official Kubernetes Enterprise security standards and integration with Kubeflow.

**Comment by DmitriGekhtman** [comment]
> Adding isolation within the Worker/Raylet 

This part is beyond near-term scope; for now, "Ray node == K8s pod" is the only architecture we can feasibly maintain.

> Enterprise security standards

This the Ray team must make sure to nail down.

Adding the experts from the Ray team to comment on secure image building.
Any thoughts, @ijrsvt @aslonnie @thomasdesr @simon-mo ?

**Comment by simon-mo** [comment]
Is there a scanner/tool we can use to check (and therefore plan out to fix) the gap in our current docker images?

**Comment by juliusvonkohout** [comment]
> Is there a scanner/tool we can use to check (and therefore plan out to fix) the gap in our current docker images?

Yes let's start with https://kubernetes.io/docs/concepts/security/pod-security-admission/ use a modern cluster 1.24+ with that enabled and you can audit any violations. 1.24-1.25 is what kubeflow 1.7 will require and it supports the podadmission controller.

Here is an example, but with the wrong profelile (baseline instead of restricted) https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/

**Comment by juliusvonkohout** [comment]
You need to add USER 1000:0 at the end of your Dockerfiles. Then run your cicd test and I bet you will already get some error messages regarding file permissions. I think that is the first step and afterwards I would focus on PSS

**Comment by simon-mo** [comment]
I believe we already met the requirements regarding uid, gid, ports, etc...

https://github.com/ray-project/ray/blob/69b3e3c0aced4aac2e19505d759d3cf137c8f96d/docker/base-deps/Dockerfile#L16-L17

We can go test against a modern cluster and audit violations. I think there is a misunderstanding here that Ray, on its critical path, and the default configurations, do not run as root at all and do not use podman or any other container tools. 

The snippet you linked in thread is referring to an experimental feature that has not been recommended to any user to try out yet. https://github.com/ray-project/ray/blob/3e357c8ae3edf24b0d753e02f128dd933a54770a/python/ray/_private/runtime_env/container.py#L26-L37

This means Ray deployments on K8s should not require any privileges.

**Comment by juliusvonkohout** [comment]
@simon-mo that sounds amazing. Yes, please test it in enforcing mode with a some workloads and then you can also advertise in the main GitHub readme, that it runs according to kubernetes restricted PSS. This goes for the operator as well as the cluster.

If that is solved the integration into Kubeflow is rather straightforward, just some boring controller and UI writing, RBAC Rules, Istio polices etc. for automation. This pod security part was worrying me the most ;-) regarding the Notebook (will be renamed to workbenches) integration we will also find something simple.

**Comment by DmitriGekhtman** [comment]
We can use this workload https://docs.ray.io/en/master/cluster/kubernetes/examples/ml-example.html as the example.
@simon-mo would you mind assigning someone to carry out the check?

**Comment by DmitriGekhtman** [comment]
cc @sihanwang41 @kevin85421

**Comment by kevin85421** [comment]
I will take a look at this issue.

**Comment by juliusvonkohout** [comment]
Alright now that https://github.com/ray-project/ray/pull/31563 is merged i think only https://github.com/ray-project/kuberay/pull/866 is missing. We can then start the integration into Kubeflow on 30th of January  if you have time then @kevin85421

**Comment by kevin85421** [comment]
We decided to integrate with Kubeflow without Docker image update from Ray. See https://github.com/kubeflow/manifests/pull/2383 for more details.
