### ISSUE TITLE
[Tune] [Datasets] Calling dataset.repartition(1) from within a Trainable cause trials to get stuck in running mode.

### ISSUE THREAD

**Issue by jharaldson** [ray-project/ray#29662]
### What happened + What you expected to happen

1. When we call `dataset.repartition(1)` from within a Tune Trainable function, this results in the trials getting stuck in running mode. This is also the case for calling `dataset.write_parquet()` from within a Tune Trainable function.

2. We have a function `simulate()` that is used to generate data. This function is input to Tune as a trainable function. The `simulate()` function aims to leverage Ray Dataset to take a list of returned values from one or more simulations and write the resulting dataset to local storage. We would like each parquet file to be fairly large e.g. 100MB. For this reason we run several simulations and use `dataset.union()`  to append new data to the dataset. Finally we want to write a single file and therefore used `dataset.repartition(1)` (see reproduction script below). To allow for a low memory solution we would like to append data as we iterate every simulation, i.e. "stream" data to a file (see workaround script below).

3. Logs
```
Current time: 2022-10-25 13:38:59 (running for 00:00:19.01)
Memory usage on this node: 7.3/45.9 GiB
Using FIFO scheduling algorithm.
Resources requested: 12.0/12 CPUs, 0/0 GPUs, 0.0/24.31 GiB heap, 0.0/12.16 GiB objects
Result logdir: /home/ejohara/ray_results/simulate_2022-10-25_13-38-40
Number of trials: 20/20 (8 PENDING, 12 RUNNING)
+----------------------+----------+-----------------------+--------+
| Trial name           | status   | loc                   |   seed |
|----------------------+----------+-----------------------+--------|
| simulate_5634d_00000 | RUNNING  | 172.31.205.43:1061121 |      0 |
| simulate_5634d_00001 | RUNNING  | 172.31.205.43:1061158 |      1 |
| simulate_5634d_00002 | RUNNING  | 172.31.205.43:1061161 |      2 |
| simulate_5634d_00003 | RUNNING  | 172.31.205.43:1061165 |      3 |
| simulate_5634d_00004 | RUNNING  | 172.31.205.43:1061168 |      4 |
| simulate_5634d_00005 | RUNNING  | 172.31.205.43:1061171 |      5 |
| simulate_5634d_00006 | RUNNING  | 172.31.205.43:1061174 |      6 |
| simulate_5634d_00007 | RUNNING  | 172.31.205.43:1061177 |      7 |
| simulate_5634d_00008 | RUNNING  | 172.31.205.43:1061180 |      8 |
| simulate_5634d_00009 | RUNNING  | 172.31.205.43:1061183 |      9 |
| simulate_5634d_00010 | RUNNING  | 172.31.205.43:1061186 |     10 |
| simulate_5634d_00011 | RUNNING  | 172.31.205.43:1061189 |     11 |
| simulate_5634d_00012 | PENDING  |                       |     12 |
| simulate_5634d_00013 | PENDING  |                       |     13 |
| simulate_5634d_00014 | PENDING  |                       |     14 |
| simulate_5634d_00015 | PENDING  |                       |     15 |
| simulate_5634d_00016 | PENDING  |                       |     16 |
| simulate_5634d_00017 | PENDING  |                       |     17 |
| simulate_5634d_00018 | PENDING  |                       |     18 |
| simulate_5634d_00019 | PENDING  |                       |     19 |
+----------------------+----------+-----------------------+--------+


(scheduler +29s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +29s) Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
```

5. Workaround
A workaround is to use pyarrow directly. A problem with this workaround is that we need to keep track of the data schema as we store the Tensor object as a bytes object. It would be nice to leverage the pyarrow support in Ray to do all reading and writing.

```
import ray
from ray import tune
from ray.tune import Tuner
import os
import pyarrow as pa
import pyarrow.parquet as pq
from ray.tune.trainable import session
import numpy as np

def write_pyarrow(writer, data, path):
  filepath = os.path.join(path, 'data.parquet')
  data_pa = pa.Table.from_pylist(data)
  if writer is None:
    writer = pq.ParquetWriter(filepath, data_pa.schema)
  writer.write_table(data_pa)

def simulate_pyarrow(config):
  data_records = []
  writer = None
  logdir_trial = session.get_trial_dir()
  for i in range(10):
    data = [{'x': np.ones((50,50,3)).tobytes()} for _ in range(100)]
    data_records += data
    writer = write_pyarrow(writer, data_records, logdir_trial)

def main():
  ray.init()
  tuner = Tuner(simulate_pyarrow,
                param_space = {'seed': tune.grid_search(range(20))})
  tuner.fit()

if __name__ == "__main__":
  main()
```

### Versions / Dependencies

```
Ray == 2.0.1
Python == 3.8
```

### Reproduction script

```
import ray
from ray import tune
from ray.tune import Tuner
from ray.tune.trainable import session
import numpy as np

def simulate(config):
  dataset = None
  for i in range(10):
    ds = ray.data.from_items([{'x': np.ones((50,50,3))} for _ in range(100)]) # results returned from simulation
    if dataset is None:
      dataset =  ds
    dataset = dataset.union(ds)
  logdir_trial = session.get_trial_dir()
  dataset.write_parquet(logdir_trial)

def main():
  ray.init()
  tuner = Tuner(simulate,
                param_space = {'seed': tune.grid_search(range(20))})
  tuner.fit()

if __name__ == "__main__":
  main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
Was able to reproduce on my laptop. Here's a simplified repro:

```
import ray
from ray import tune
from ray.tune import Tuner
from ray.tune.trainable import session

NUM_VALUES = 20

def trainable(config):
  ds = ray.data.range(1)
  logdir_trial = session.get_trial_dir()
  ds.write_csv(logdir_trial)

tuner = Tuner(trainable, param_space = {'seed': tune.grid_search(range(NUM_VALUES))})
tuner.fit()
```

Interestingly, the code works fine if `NUM_VALUES` is 9, but runs forever if `NUM_VALUES` is 10. I have 10 CPUs available. Maybe that's related?

**Comment by matthewdeng** [comment]
Hey @jharaldson,

Looks like this is because Ray Datasets operations require CPU resources to execute, and all the CPUs in your cluster have already been reserved by the concurrently running Tune Trials.

For more information and workarounds, check out [Datasets and Tune](https://docs.ray.io/en/master/data/dataset-internals.html#datasets-and-tune)!

**Comment by jharaldson** [comment]
@matthewdeng, the mentioned workaround in the docs would add too much overhead in our scenario, basically one additional CPU per data generating process. Think it is clear that Ray Datasets should not be used in the way described in the issue description.

A follow-up question that is slightly off topic. What would be the preferred way of writing data to disc in the context described here? I.e. we run 100 000+ simulations that generate data and would like to have a low memory solution where data is continuously written to disk (not kept in memory). We can use the proposed workaround given in the issue description, but we would then miss out on functionality that has been built into Ray Dataset. We can step away from using Tune and use the following [solution](https://discuss.ray.io/t/streaming-data-for-training-evaluation-inference/4830/4?u=jharaldson) to iteratively generate chunks of data (combined with this [pattern](https://docs.ray.io/en/latest/ray-core/tasks/patterns/too-many-results.html)) that we write to disc. The main reason we use Tune is to get grid search and sampling out of the box, as well as not having to deal with available CPUs, log directories etc.

**Comment by matthewdeng** [comment]
Hey @jharaldson, sorry for the delay in response on my end. Were you able to find a working solution for this workload?

Another approach that would allow you to have the benefits of both Tune and Data would be to instead tweak your _cluster_ resource configuration. For example, it looks like the cluster you are using has 12 CPUs - if you initialize your cluster with `num_cpus=24` and set `max_concurrent_trials=12`, you can still run 12 concurrent trials while having 12 "CPU"s available for scheduling Datasets tasks.

**Comment by jharaldson** [comment]
@matthewdeng, sorry for even longer delay in responding, we ended up using TensorArray from ray.data.extensions and ParquetWriter from pyarrow.parquet to write the data to disk, sample by sample.
