### ISSUE TITLE
[CI] `bk://:mac: :apple: Ray C++ and Java ` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29672]
`bk://:mac: :apple: Ray C++ and Java` is broken for a while

https://flaky-tests.ray.io/

**Comment by architkulkarni** [comment]
I can look at post-wheel tests, most of them are runtime env tests which require the Ray wheel to be built to insert it in a conda env.

@cadedaniel The title of this issue doesn't match the description, is it C++/Java or post-wheel-tests?

**Comment by cadedaniel** [comment]
Oh.. the link to create the C++/java was too long so I tried creating it from another but forgot to update title

it's `bk://:mac: :apple: Ray C++ and Java `

**Comment by jjyao** [comment]
Java tests are failing: https://buildkite.com/ray-project/oss-ci-build-branch/builds/697#01840c5e-eb77-45fe-88d2-bb116216d391

**Comment by jovany-wang** [comment]
It seems the flaky tests were introduced in https://github.com/ray-project/ray/pull/28367 , create a new PR to fix it.
