### ISSUE TITLE
[AIR] Nightly test regression of air_benchmark_xgboost_cpu_10

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29681]
### What happened + What you expected to happen

Last successful run (10/19): https://buildkite.com/ray-project/release-tests-branch/builds/1138
First failed run (10/20): https://buildkite.com/ray-project/release-tests-branch/builds/1143

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Looks like `xgboost_train_gpu` is failing for the same reason: https://buildkite.com/ray-project/release-tests-branch/builds/1150#01840c2d-ea09-4b50-9763-5d2359f89935
