### ISSUE TITLE
[CI] `bk://:python: Minimal install 3.10` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29680]
Also 3.8 and 3.9

```
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

I thought Sang's PR would fix this but it didn't https://github.com/ray-project/ray/pull/29657

- bf22325eb518c4a42242a88031909869da003850 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/723#01841098-0e54-4c99-9e44-31eb11785577)
- 51a7b093c9fd56d4b7a14d4159fe6a6bf770742e FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/722#01841070-81d6-4321-ac8f-e1f53c19359e)
- b0bd2700a5f14d8d11555677805d773b7beb9bd4 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/721#01841058-3a9a-41c3-b41b-f05ef7bb781f)
- 2485464918e62cebd2ca3ed139316fd81c4a15e9 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/720#01841051-c100-4522-82b3-97edf8bb51ec)
- e464bf07af9f6513bf71156d1226885dde7a8f46 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/718#01841043-5daa-473a-a427-c74de03fbc2a)
- 9b29fd6501ff0e3e69d0333bf214482b86f9e97f FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/717#0184101e-1d47-40d5-b99b-13368d972304)
- 2ca05c84d0eca54ea2cfd438577afe40be796cd8 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/716#01841018-cf07-40bd-be70-a63ee15bd5c0)
- 97e120d3835f239cc3fd4886996faf4d9bff46e4 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/714#01841013-d26a-4c27-8f29-a64bd148b741)
- 2b6f88e34ccdd83f270d80e2076a56848498c5f9 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/713#01841009-1705-4c00-9529-6fffc305eca3)
- 1b52e9999c0e7c90fd84c30d03ecc5e7c37847c5 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/712#01840fd8-4061-4edf-963f-7b0b5cd4f7ab)
- 813e1a857d5dfc060b3b6cb846157fdca425e6b0 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/710#01840f9c-9a38-4fe6-ba65-78efe7a249e5)
- 8e3e741d9b94a2694e789d4bcdff16e4c27a501c FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/708#01840f35-fe70-4b5d-a66d-6237106a2748)
- 398300252611547acc4d47b2f645e580e828965b FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/707#01840e3b-38c7-444f-878a-c9a0f2a12239)
- 45420f56688d4017cb5e63b229d822bbe722f1a5 FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/704#01840d0d-2336-430d-b0f3-85be63276457)
- aa9a53a3e5cf8a337871920daf9bc65c090d9c0d FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/703#01840d06-459e-4459-9464-335cbd517b53)
- 22445794362933cb08cc652ca955f18aef1effff FAILED [:python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/702#01840cdd-53ff-4881-94a3-c13254985c33)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:python: Minimal install 3.10-END
....

**Comment by rickyyx** [comment]
Showing up in the release branch as well - seems this is a CI tooling issue. 

A similar failure is https://buildkite.com/ray-project/oss-ci-build-branch/builds/735#018414e6-709a-4313-a47e-82f674690c6a

This is probably not release blocking - but once we have a fix, it will be great to cherry-pick in. 

cc @scv119 @c21

**Comment by cadedaniel** [comment]
Thanks @krfricke for fixing this with https://github.com/ray-project/ray/pull/29727!
