### ISSUE TITLE
Issue on ray installation for M1 macbook 8 GB Ram

### ISSUE THREAD

**Issue by 0315jaewon** [ray-project/ray#29705]
Hello, when I try to install ray (using pip install -e . --verbose), when my computer is near done compiling the relevant files, it begins to slow down extremely and lags out making my computer freeze and crash. Other members in my research group are not facing this problem despite one of them using the exact same laptop model as me (macbook M1 chip 8 GB RAM). I tried compiling using half the RAM but I run into the same problems. Any suggestions regarding how I'd go about resolving this issue?

**Comment by cadedaniel** [comment]
Is it possible that you're running x86 python on the emulator? It's a guess, although I experienced some performance issues on M1 because I was using x86 python. 

Can you share some logs or list of processes during the slowdown?

**Comment by 0315jaewon** [comment]
<img width="1192" alt="Screen Shot 2022-10-25 at 11 15 53 AM" src="https://user-images.githubusercontent.com/112059352/198156878-0d26b034-d8fe-4ead-bd80-95b0cb4e17b2.png">

**Comment by 0315jaewon** [comment]
How can I know whether I'm running x86 python on the emulator or not? I attached a photo of the logs when it begins to slow down (I've previously tried to leave it to run but it just slows down even more – taking 4000 seconds+ per update but making no compilation progress).  If I leave it on for longer, it ultimately just makes my computer freeze and crash

**Comment by cadedaniel** [comment]
Oh, actually bazel will use Java. When you're compiling, can you look in the Activity Monitor and tell if the java processes are running with `Kind` as `Intel` or `Apple`?

Here's a screenshot from my m1 machine (The python process is running on Intel, the kernel is running natively)
<img width="377" alt="Screen Shot 2022-10-26 at 4 29 17 PM" src="https://user-images.githubusercontent.com/950914/198157649-d35e9fda-4cc8-441f-a278-86ba4c295ea8.png">

Also, what does memory usage look like once it starts slowing down? Do the bazel processes consume so much memory that it is trying to compress/page to disk?

**Comment by 0315jaewon** [comment]
<img width="958" alt="Screen Shot 2022-10-26 at 4 37 32 PM" src="https://user-images.githubusercontent.com/112059352/198158510-76dd1961-bf41-4c41-9d0a-4e96b78d11ec.png">
I just restarted the compiling process and I'm around 40% on the way so I'll post my activity monitor when it slows down, but I sent a screenshot above containing what I know so far. On the CPU tab of the activity monitor, java is running with Kind as "Apple" but python3.8 is running as kind "Intel".

**Comment by 0315jaewon** [comment]
<img width="956" alt="Screen Shot 2022-10-26 at 4 53 43 PM" src="https://user-images.githubusercontent.com/112059352/198160096-a619dbde-628b-4e2b-a7f7-c9d999512b3a.png">
Yeah it seems like the bazel processes consume too much memory and compress it to disk.

**Comment by cadedaniel** [comment]
Can you confirm that before the compilation starts there's low memory utilization? If that's confirmed, then we can look into an issue. Perhaps we can use Slack for efficiency.

**Comment by 0315jaewon** [comment]
I can confirm that before compilation starts there is low memory utilization – the bar graph below indicating memory pressure isn't red at all and my computer doesn't slow down at all. To give you exact numbers, the memory used is at 7.00 GB while the physical memory is 8.00 GB (I'm not completely sure if this is not considered low memory utilization though).

**Comment by 0315jaewon** [comment]
Where can I find the link to join the slack channel for Ray?

**Comment by cadedaniel** [comment]
There were some other processes on the machine consuming available memory. Once @0315jaewon restarted their machine, the build completed successfully.
