### ISSUE TITLE
[CI] `linux://python/ray/tune:test_progress_reporter` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29714]
98da29 [Agent] Make agent shutdown more informative and graceful (#29540) [0 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841519-2f8c-45a3-91dc-197132fcf9b6)

182744 [RLlib] AlgorithmConfig: Next steps (volume 01); Algos, RolloutWorker, PolicyMap, WorkerSet use AlgorithmConfig objects under the hood. (#29395) [0 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/736#018413b7-de65-42c2-a00d-1aa9efdd7211)

37de81 [RLlib] RLModule base class, RLModule PR 3/N (#29642) [0 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/734#0184130c-88dc-4c9c-b2ac-27cb963c2190)

875193 [CI] Increase latency threshold in `tune_torch_benchmark` (#29688) [1 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/733#018412c7-9cc7-4134-8937-ed6dc2c56043)

7a50e2 [Core] fix test_object_directory_failure flakiness [1 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/731#018412a1-7bbc-457a-bf5f-7cd29eddd6a4)

161567 Optimize task metrics to avoid synchronous recording overhead. (#29678) [1 days ago]

[linux Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841286-1a74-4bd6-b352-930db8c29230)

**Comment by bveeramani** [comment]
Fixed by https://github.com/ray-project/ray/pull/29748
