### ISSUE TITLE
[CI] `linux://python/ray/tests:test_exit_observability` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29715]
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FLAKY [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841512-f482-425f-81b2-2f7b8d323bbd)
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841512-f490-4bd1-b3ec-5f2549b8ce18)
- 182744bbd151c166b8028355eae12a5da63fb3cc FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/736#018413b1-1935-423a-b107-9fd5e67451e3)
- 37de814a8598e0ea3dea23d5ae0caf9df54fa0e6 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/734#01841305-cbc9-415e-9eb2-3b99f5fa691f)
- 824c79011e32fa4a0e9c409ef55a62a05fb70da8 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/732#018412a4-e036-4706-a744-4a408ee04882)
- 7a50e23478a32687e87528b2fbdae3ce953ae579 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/731#0184129c-95c2-4cf8-b28e-2081d9ae42e6)
- 161567dbd93f94bef941c17779d3880f310a0373 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841280-1286-4208-8705-0bf81fe1bb31)
- 161567dbd93f94bef941c17779d3880f310a0373 FAILED [Buildkite :python: (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/730#01841280-1278-421e-8cf1-bea6b8d04b14)
- 160c3cfa8959d133088bc56ecf9443351c17a558 FLAKY [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/689#01840bdc-aea8-4e5d-8218-6f9ff905714a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_exit_observability-END
....

**Comment by rickyyx** [comment]
This should be addressed by this: https://github.com/ray-project/ray/issues/29715
