### ISSUE TITLE
[CI] `linux://python/ray/tune:test_result_grid` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29719]
- 98da294f0b8fbf0ab9d94ebd552c4d78b4d3aaf8 FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/737#01841519-2f8c-45a3-91dc-197132fcf9b6)
- 182744bbd151c166b8028355eae12a5da63fb3cc FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/736#018413b7-de65-42c2-a00d-1aa9efdd7211)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tune:test_result_grid-END
....

**Comment by bveeramani** [comment]
Looks like this was caused by https://github.com/ray-project/ray/pull/29395 and then fixed when it was reverted by https://github.com/ray-project/ray/pull/29742.

![image](https://user-images.githubusercontent.com/26107013/198242410-d98b2fe6-271b-4dc2-8092-7d17f7e39390.png)
