### ISSUE TITLE
[RLlib|Tune] Migrating from ray 0.x to ray 1.x

### ISSUE THREAD

**Issue by alexeyev** [ray-project/ray#29724]
### Description

Dear colleagues, thank you for the cool product.

I've seen some tips on how to convert a project from the 1.x `ray` version to the 2.x `ray` version.

May I wonder, are there any guidelines on how to migrate a relatively old project (mid-2019) from 0.7.x to 1.x (and after that, hopefully, to 2.x)?

E.g. `rllib.models.Model` -> `ModelV2`, `ray.tune.function` -> callback objects, etc. I could try and guess, of course, but I really hope there are some instructions so as not to introduce any unpredictable unfamiliar-API-related bugs :) Any pointers are very much welcome.

Thanks.

Related SO question: https://stackoverflow.com/questions/74168655/migration-tips-for-ray-rllib-models-deprecationwarning-model-has-been-deprec

**Comment by cadedaniel** [comment]
cc @kouroshHakha @bveeramani @richardliaw

**Comment by bveeramani** [comment]
Hey @alexeyev, thanks for reaching out!

I'm not aware of any 0.x to 1.x migration guide. I'll ask my teammates if they know of any. 

For information on migrating from 1.x to 2.x, see https://github.com/ray-project/ray/issues/28223.

**Comment by ArturNiederfahrenhorst** [comment]
From RLlib, there is no guide for doing that jump.
If you have specific questions, feel free to post them on [the forum](https://discuss.ray.io/c/rllib/7) or look for some answers there.

**Comment by alexeyev** [comment]
Hi @bveeramani @ArturNiederfahrenhorst, thank you for the quick response!

> feel free to post them on [the forum](https://discuss.ray.io/c/rllib/7) or look for some answers there.

I probably will, thanks :)
