### ISSUE TITLE
[Core] Fix flaky memory_monitor_test

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#29757]
### What happened + What you expected to happen

<img width="1590" alt="Screen Shot 2022-10-27 at 7 38 12 AM" src="https://user-images.githubusercontent.com/18510752/198318214-71593e00-c9fa-4c96-8036-249f528f2a17.png">

Seems like the test is very flaky

### Versions / Dependencies

master

### Reproduction script

n/a

**Comment by clarng** [comment]
<img width="1576" alt="Screen Shot 2022-11-01 at 4 01 13 PM" src="https://user-images.githubusercontent.com/22830327/199358389-0908e2f7-62c4-4d65-af75-3f9be2930c61.png">

**Comment by rkooo567** [comment]
interesting.. is it automatically fixed?
