### ISSUE TITLE
[core] 1000000_queued_time metric regression in single_node test 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29766]
### What happened + What you expected to happen

There is regression on the metric: 
https://b534fd88.us1a.app.preset.io/superset/explore/p/NDd911495p6/

However, there's no known regression PR yet due to its large variance and slow regression trend. More investigation is needed to figure out the root cause. 

### Versions / Dependencies

NA

### Reproduction script

NA

**Comment by rkooo567** [comment]
<img width="481" alt="Screen Shot 2022-12-12 at 2 58 06 PM" src="https://user-images.githubusercontent.com/18510752/207173358-e383005f-3daa-46ee-8a9a-01c5a422658d.png">

seems to be recovered
