### ISSUE TITLE
[Core][Tune] Last run hangs when using Pytorch

### ISSUE THREAD

**Issue by harkash** [ray-project/ray#29775]
### What happened + What you expected to happen

Hello, 

I recently setup a new conda environment with Python 3.8, Pytorch 1.12 and Ray 2.0.0 (recently downgraded to 1.9.1 hoping it would fix the issue). 

When I do a grid search (around 50 runs in total), the last one or two processes just hang. It just says running but nothing happens. I am forced to cancel that experiment (Ctrl + C) and redo only the missing runs separately.
In my previous conda env (Python 3.6, Pytorch 1.9 and Ray 1.9.1), I dont think this issue exists. 

After looking through the issues here on Github, these could be related, though I am not making use of Lightning (https://github.com/ray-project/ray/issues/27493, https://github.com/ray-project/ray/issues/28197). The workaround seems to set a flag relevant to Pytorch Lightning (`ray.init(runtime_env={"env_vars": {"PL_DISABLE_FORK": "1"}})`). 

I was wondering if there was something that works with native Pytorch as well. 

### Versions / Dependencies

Python 3.9, Ubuntu, Ray 2.0.0 (and 1.9.1), Pytorch 1.12.0

### Reproduction script

The official tutorial (https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html) should also see this issue, but I can provide a minimal example if need be. 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by harkash** [comment]
I have since tried running different things a few times. I think the last process gets stalled/hangs about 50% of the time. I am not able to figure out under what conditions that happens.

Whenever the stalling occurs, one process hangs indefinitely (could be in the first epoch or 15th or whenever). However, one of the runs I did saw about 4 processes hanging from a grid search of 48 runs.

**Comment by bveeramani** [comment]
Hey @harkash, could you share a minimal reproducible example with us?
