### ISSUE TITLE
[release] air_benchmark_tune_torch_mnist_large_gpu keeps timing out

### ISSUE THREAD

**Issue by c21** [ray-project/ray#29777]
### What happened + What you expected to happen

Examples:

https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841b05-9162-4cab-9116-d9027a756bd1
https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841a5c-c8b9-4f1a-aa7d-c9d5f5c24d5d
https://buildkite.com/ray-project/release-tests-branch/builds/1163#01841826-0352-40fb-854f-91cfc10a89e6

The test are running longer than expected, so timed out. Wondering is this the timeout threshold set to tight, or it's a real slow-running issue?

### Versions / Dependencies

releases/2.1.0

### Reproduction script

nightly test as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
Might be infra timeout 
```
(scheduler +59m58s) Error: No available node types can fulfill resource request defaultdict(<class 'float'>, {'GPU': 8.0, 'CPU': 16.0}). Add suitable node types to this cluster to resolve this issue.
```

**Comment by bveeramani** [comment]
Yeah, looks like it's timing out because of infra issues.

This error message repeats 50+ times before the test times out.
```
2022-10-27 13:17:39,209	WARNING insufficient_resources_manager.py:133 -- Ignore this message if the cluster is autoscaling. No trial is running and no new trial has been started within at least the last 60.0 seconds. This could be due to the cluster not having enough resources available to start the next trial. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.

[2m[1m[33m(scheduler +5m46s)[0m Error: No available node types can fulfill resource request defaultdict(<class 'float'>, {'CPU': 16.0, 'GPU': 8.0}). Add suitable node types to this cluster to resolve this issue.
```

**Comment by c21** [comment]
Thanks folks for checking!

**Comment by xwjiang2010** [comment]
driving by, as I am trying to optimize our release tests by keeping an eye on current failures. 

btw, I think this is a real issue.

from this log
```
== Status ==
Current time: 2022-10-27 13:15:09 (running for 00:03:40.21)
Memory usage on this node: 4.8/186.6 GiB 
Using FIFO scheduling algorithm.
Resources requested: 0/384 CPUs, 0/32 GPUs, 0.0/1052.18 GiB heap, 0.0/414.09 GiB objects (0.0/8.0 accelerator_type:T4)
Result logdir: /home/ray/ray_results/TorchTrainer_2022-10-27_13-11-28
Number of trials: 1/1 (1 PENDING)
+--------------------------+----------+-------+
| Trial name               | status   | loc   |
|--------------------------+----------+-------|
| TorchTrainer_8a9b9_00000 | PENDING  |       |
+--------------------------+----------+-------+


[2m[1m[33m(scheduler +4m3s)[0m Error: No available node types can fulfill resource request defaultdict(<class 'float'>, {'GPU': 8.0, 'CPU': 16.0}). Add suitable node types to this cluster to resolve this issue.
```

Suspecting https://github.com/ray-project/ray/pull/29133

not release blocking

**Comment by hora-anyscale** [comment]
Per Triage Sync: @c21 if you feel p1 is incorrect, please update
