### ISSUE TITLE
[dashboard] ray 2.0.1 not showing dashboard information

### ISSUE THREAD

**Issue by yzs981130** [ray-project/ray#29795]
### What happened + What you expected to happen

The dashboard-related information is missing when setting `--include-dashboard=true`. However, the dashboard is started. The correlating log is attached below.

```
(ray_2_0) $ ray start --head --include-dashboard=true
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: <head_node_ip_address>

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address=<head_node_ip_address>

  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto')

  To connect to this Ray runtime from outside of the cluster, for example to
  connect to a remote cluster from your laptop directly, use the following
  Python code:
    import ray
    ray.init(address='ray://<head_node_ip_address>:10001')

  If connection fails, check your firewall settings and network configuration.

  To terminate the Ray runtime, run
    ray stop
```

### Versions / Dependencies

ray, version 2.0.1
python 3.9.13

Ray is installed by `pip install "ray[default]"==2.0.1`

### Reproduction script

ray start --head --include-dashboard=true

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
thanks for the report! include-dashboard is true by default btw. I believe we never printed this information to the output of ray start. I am planning to add the information for ray 2.2

**Comment by yzs981130** [comment]
> thanks for the report! include-dashboard is true by default btw. I believe we never printed this information to the output of ray start. I am planning to add the information for ray 2.2

Thanks for the information! I got mixed up with the `ray.init()` and `ray start`. Sorry for the inconvenience.

**Comment by rkooo567** [comment]
This is fixed
