### ISSUE TITLE
[core][state observability] ray logs follow on monitor.log not working 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#29790]
### What happened + What you expected to happen

Seems to be not following. 

### Versions / Dependencies

2.0.0

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_9bUyvcEZt1erMzKjr38hRUPs/ses_qmd7vvgBD4cZfBRD9rTSVLxH

**Comment by cadedaniel** [comment]
Assigning P1 for now cc @rickyyx

**Comment by rickyyx** [comment]
This is probably not a bug - but due to the fact that `monitor.log` is overwritten with each entry rather than appended.

**Comment by scottsun94** [comment]
Related to this one reported by @galenhwang : https://github.com/ray-project/ray/issues/29928

**Comment by rickyyx** [comment]
We could close this - it's the same issue
