### ISSUE TITLE
[Autoscaler] Do not abort the autoscaler when there are many errors during update 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#29791]
### What happened + What you expected to happen

Right now if there are exceptions happening during update (cumulative) and exceed the threshold (`AUTOSCALER_MAX_NUM_FAILURES = env_integer("AUTOSCALER_MAX_NUM_FAILURES", 5)`), the autsocaler aborts itself. We should handle this more gracefully than aborting the process. 

 https://github.com/ray-project/ray/blob/aecba4d418043f8f9c690481dda5f64259494e9d/python/ray/autoscaler/_private/autoscaler.py#L365, 

### Versions / Dependencies

master

### Reproduction script

raise exceptions more than 5 times in the autoscaler

**Comment by rkooo567** [comment]
Related https://discuss.ray.io/t/ray-status-couldnt-find-the-ray-cluster-despite-a-working-cluster/7999

**Comment by wuisawesome** [comment]
Btw downgrading this to p1 because it wasn't actually the issue in 1/2 of the incidents, though we should fix it (and i will still do it)

**Comment by architkulkarni** [comment]
Hi @rkooo567 , what would your recommendation be for a more graceful behavior here?

**Comment by rkooo567** [comment]
I think this behavior is actually removed. We can probably close it. 

Imo the right behavior is to retry with some backoff + reset the failure count when it succeeds again.
