### ISSUE TITLE
[CI] `osx://python/ray/tests:test_object_store_metrics` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#29803]
- 949a8348137a104fe65ff2e46f93b95a6f7c479e FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/762#01841dd9-b8d1-4b41-af5b-df9c3021ce7e)
- b218ae7e4a77728cb988dbc12130378e977a2a7b FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/761#0184196a-f19d-45bd-8c15-2052773b5e19)
- e7a614f3886e67ecf3f518c6663813be3a5faf4f FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/760#01841908-04ad-4d09-b6e3-612235d8af90)
- f67b1ab0bd2b0aae8af575299aa27e912d09cb53 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/758#01841867-fa5c-47bd-b049-5f0fa29f5195)
- 9a95d77be8fda5392b58020f0648b11b2b92dbd5 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/754#01841775-1371-461f-bab4-909e7746b9ee)
- 12b579d95e5ce14564897b5b508ae92c8bbdd7b9 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/753#0184174d-1c40-4c14-9ac9-ea081407b4d9)
- e1dedb3ae7997dba7f0aae9e988562ef8ac1016a FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/751#01841729-6a2e-421b-a4bc-61163ed77e87)
- 26be31c76f7e80ebeeaa2d90c0a7af7c93061ace FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/750#01841728-21b1-4f93-95d8-a68f9937bbdf)
- ec4637d24cdd71239b3a700ae1c11bfb736a06c8 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/749#018416e8-865d-456b-b314-8f72df0bc023)
- 5da96b813e0c8986634af62783b3718752edea5a FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/747#01841691-b13d-484f-ab0f-5d4b0f98115f)
- de238dd626a48a16c8b3cd006f3482db75f63a83 FLAKY [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/673#01840260-dd6a-44c6-a703-152aef43312d)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_object_store_metrics-END
....

**Comment by cadedaniel** [comment]
@rickyyx looks like this started failing with https://github.com/ray-project/ray/pull/29485

**Comment by rickyyx** [comment]
Let's revert it for now - something wrong with macos there. I will follow up.

**Comment by cadedaniel** [comment]
Hm, I tried reverting but looks like another merge touched one of the same files after this was merged. Will see if it's easy to fix.
```diff
diff --cc src/ray/util/counter_map.h
index 2a758c99f,58d529ce8..000000000
--- a/src/ray/util/counter_map.h
+++ b/src/ray/util/counter_map.h
@@@ -47,22 -44,12 +47,29 @@@ class CounterMap
      on_change_ = on_change;
    }

++<<<<<<< HEAD
 +  /// Flush any pending on change callbacks.
 +  void FlushOnChangeCallbacks() {
 +    if (on_change_ != nullptr) {
 +      for (const auto &key : pending_changes_) {
 +        on_change_(key);
 +      }
 +    }
 +    pending_changes_.clear();
 +  }
 +
 +  /// Increment the specified key by `val`, default to 1.
 +  void Increment(const K &key, int64_t val = 1) {
 +    counters_[key] += val;
 +    total_ += val;
++=======
+   /// Increment the specified key by one.
+   void Increment(const K &key) {
+     counters_[key] += 1;
+     total_ += 1;
++>>>>>>> parent of 5da96b813 ([core][metric] Add fallback memory and seal memory breakdown (#29485))
      if (on_change_ != nullptr) {
 -      on_change_(key, counters_[key]);
 +      pending_changes_.insert(key);
      }
    }

```
