### ISSUE TITLE
Help us improve Ray AIR experience!

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#29858]
Hey all! 

Interested in helping us improve the experience of using Ray with PyTorch and get incentive at the same time?

All you need to do is [register here](https://airtable.com/shrpEdgk3D59lCmdH). Our team will reach out to confirm and schedule the time with you. 

The session will be 1:1 45-mins exploring some Ray 2.0 experience with a Ray team member set up. In respect of your time, we are providing an Amazon gift card incentive.

Slots are limited:fire:

*There won’t be effort trying to sell anything in this call.*

**Comment by mronda** [comment]
What about Ray and Keras?

**Comment by bveeramani** [comment]
Hey @mronda, we're not focusing on Keras + AIR at the moment. That said, we have plans to focus on it in the near future.

I'll let you know!
