### ISSUE TITLE
[core] add CI test for cgroup v2 memory accounting

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#29873]
### What happened + What you expected to happen

add a CI unit test for https://github.com/ray-project/ray/issues/29474

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by clarng** [comment]
@avivhaber  can you add commands to repro the problem where cgroup v2 is not always present ?

**Comment by avivhaber** [comment]
As per [here](https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version), you can check a machine's cgroup version by running `stat -fc %T /sys/fs/cgroup/`.

If the output is `cgroup2fs`, you're on v2.
If the output is `tmpfs`, you're on v1.

Steps I did:

1. Pull the `rayproject/ray-deps:nightly-py37-cpu` docker image (you can substitute 37 with your desired python version). This is the base image that `ray-ci` uses.
2.  Execute into the docker container and run the `stat -fc %T /sys/fs/cgroup/` command.
a. On docker desktop on my intel macbook, the output is `cgroup2fs`.
b. On an ec2 ubuntu 20.04 instance, the output is `tmpfs`.

Despite the exact same image, the cgroup version is different. This indicates that the cgroup version is a property of the OS of the host machine, not of the docker image.
