### ISSUE TITLE
Issue on page /rllib/core-concepts.html

### ISSUE THREAD

**Issue by Athe-kunal** [ray-project/ray#29887]
Your issue content here.
```
from ray.rllib.algorithms import PPOConfig
```
should be modified to
```
from ray.rllib.algorithms.ppo import PPOConfig
```

And rest of the code for setting environment is also showing error

**Comment by maxpumperla** [comment]
@Athe-kunal this seems to be fixed on master (https://docs.ray.io/en/master/rllib/core-concepts.html) and will be in the next official release.
