### ISSUE TITLE
[Tune] Access `trial_dir` inside Trainable `step` 

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#29894]
### Description

I'm hoping to write out non-trivial amount of data in each `setup` call from `Trainable` (cls or function), in which I need to access the `trial_dir`. 

I see in Ray 3.0.0dev, there is a public API for me to do that (here: https://docs.ray.io/en/master/_modules/ray/air/session.html), but it's missing from the latest 2.0.1. 

Can we add that to the next release? 

Related issue ticket: https://github.com/ray-project/ray/issues/10839

### Use case

One example could be what stated above.

Another more general case would be - although in simple case, we can call `session.report` for trial checkpointing, but there are cases where you can't decide when to trigger checkpoint, e.g. event-driven (something happens, you checkpoint, but you can't decide apriori). 

To achieve checkpointing in the suggested way, you have to call `session.report` in all those listener callbacks (e.g. `on_XXXX`). This brings up an issue that it makes all the listener objects un-picklable (not to mention achieving parallelization).

To workaround this, I'm writing my own checkpointing code, which involves writing out data/states. 

On this, if there are better ways, please do suggest. Thanks

**Comment by justinvyu** [comment]
Hi @mlguruz,

Tune already changes each actor's working directory to its trial directory by default. Additional trial information can be saved by using relative paths to the working dir.

```python
class MyTrainable(tune.Trainable):
    def setup(self, config):
        print(os.getcwd())  # ~/ray_results/<exp-name>/<trial-dir>
        open("text.txt", "w").write(...)  # Save to files in the trial directory
```

The `Trainable` docs explains why this is the default behavior: [Trainable API reference.](https://docs.ray.io/en/master/tune/api_docs/trainable.html#tune-trainable-class-api)

> Tune will convert this class into a Ray actor, which runs on a separate process. By default, Tune will also change the current working directory of this process to its corresponding trial-level log directory self.logdir. This is designed so that different trials that run on the same physical node won’t accidentally write to the same location and overstep each other.

In terms of the use case you're describing, is it possible to elaborate a bit more on how you are currently using it, and what the gaps in the functionality are? (Can continue posting on the [Slack thread](https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1667056254060409).)

**Comment by mlguruz** [comment]
Thank you @justinvyu ! 
For Function API, I guess I need to call get_trial_dir right? This seems to be a 3.0.0dev (public) behavior?

**Comment by justinvyu** [comment]
The Function API should also switch the working directory to the trial directory, so saving to relative paths within your custom training function should work the same as the Class API case.

**Comment by mlguruz** [comment]
> The Function API should also switch the working directory to the trial directory, so saving to relative paths within your custom training function should work the same as the Class API case.

Ok - so you're saying I can just do 

```
def get_trial_dir():
   from ray.air.session import get_trial_name
   return os.path.join(os.getcwd(), get_trial_name())
```
... to get the `trial_dir` when I'm in a ray tune session?

**Comment by mlguruz** [comment]
> The Function API should also switch the working directory to the trial directory, so saving to relative paths within your custom training function should work the same as the Class API case.

This seems to work:

```
def get_trial_dir() -> str:
    """Trial id for the corresponding trial."""
    if _get_session() is None:
        raise RuntimeError          # `_get_session` prints out warning itself already.
    return os.getcwd()      # see: https://github.com/ray-project/ray/issues/29894#issuecomment-1300773205
```
