### ISSUE TITLE
[Core] Support pip secure installs

### ISSUE THREAD

**Issue by LarsDu** [ray-project/ray#29904]
### Description

`ray-project` current supports installing `pip` based `runtime_env` installs to add python packages. However, this process can be haphazard from a both a security and a reproducibility perspective for the following reasons:

- A package number without a matching hash is no guarantee that the underlying package hasn't changed
- Malicious actors can tamper with package wheels without users noticing.

Right now pip offers a secure install option which allows specification of package hashes for added security.
https://pip.pypa.io/en/stable/topics/secure-installs/

Additionally, the poetry package manager also offers this option under the hood with `poetry.lock` files which hash the underlying packages.: https://python-poetry.org/docs/basic-usage/#installing-with-poetrylock

We request  for an option to specify package hashes for runtime installs.

### Use case

Users should be able to specify hashes in their requirements dicts and Ray should be able to check that hashes match with user-specified hashes.

(Optional) Ideally, there would also be an option to pass poetry.lock files to achieve equivalent reproducibility.

**Comment by architkulkarni** [comment]
Thanks for the request @LarsDu ! Actually, if I understand https://pip.pypa.io/en/stable/topics/secure-installs/#hash-checking-mode correctly, this (along with all other `pip` options that can be specified per requirement) should already be automatically supported in `runtime_env`, for example:
`runtime_env={"pip": ["FooProject==1.2 --hash=sha256:2cf2", ...]}`.

Does that work for your use case?

**Comment by LarsDu** [comment]
Wow @architkulkarni, I did not realize this was actually already in place. Could you direct me to where this propagates through the codebase? All pip arguments are supported as part of runtime_env?

I'd like to verify this on my end tomorrow, but I can close this request if someone can verify that this indeed works.

**Comment by architkulkarni** [comment]
@LarsDu Sure, this part is quite simpleminded, we just concatenate the lines into a `requirements.txt` file and call `pip install requirements.txt`.  https://github.com/ray-project/ray/blob/master/python/ray/_private/runtime_env/pip.py#L333

Global pip arguments aren't yet supported, only those that can be specified per-line.  I will update the docs to make this all clearer.

**Comment by LarsDu** [comment]
Thank you so much @architkulkarni! I'll close out this issue
