### ISSUE TITLE
[core] stress_test_many_tasks perf regression 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#29913]
### What happened + What you expected to happen

regression with 
stage_2_avg_iteration_time
stage_4_spread

### Versions / Dependencies

master

### Reproduction script

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_GrmSDmBLK9ywjyXcH8LZEJE4

**Comment by clarng** [comment]
looks like stage_4_spread regression is a red herring, the metrics actually improved recently

<img width="969" alt="Screen Shot 2022-11-02 at 11 34 37 AM" src="https://user-images.githubusercontent.com/22830327/199574222-2b93a9f1-b74d-48d4-9625-45d530253f52.png">

there looks like a regression in stage_3 that is different from that one for stage_2

stage_2:
<img width="948" alt="Screen Shot 2022-11-02 at 11 34 17 AM" src="https://user-images.githubusercontent.com/22830327/199574506-1a123450-3d49-4c1f-8cf9-3c96f34a93c2.png">

stage_3:
<img width="933" alt="Screen Shot 2022-11-02 at 11 34 26 AM" src="https://user-images.githubusercontent.com/22830327/199574526-c2aa79b7-d599-42bf-8701-257f099465ba.png">

**Comment by rkooo567** [comment]
Hey @clarng can you help find other assignee for this task? I have other P0 I should take over...

https://github.com/ray-project/ray/issues/29944

**Comment by clarng** [comment]
based on team discussion the P0 core metrics are the core benchmark, i think this is P1

**Comment by rkooo567** [comment]
I don't think we will take any actions here. Closing it
