### ISSUE TITLE
[core] shuffle_1tb_1000_partition shuffle time regression

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#29914]
### What happened + What you expected to happen

regression in time by ~35%

### Versions / Dependencies

master

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_eARjk1mVnjXtuAeD587e76QT

**Comment by clarng** [comment]
looks like the metric is creeping up slowly over time, doesn't appear to have a single offending commit

also the regression report is ~40% the min was on sept 14 and max on sept 27, seems the metric itself is pretty unstable

we might want to figure out how to improve the detection if nothing else, since it may keep alarming


<img width="775" alt="Screen Shot 2022-11-02 at 11 47 39 AM" src="https://user-images.githubusercontent.com/22830327/199576236-2d293f04-d241-4a6d-9cbd-79d09c33d424.png">

**Comment by jjyao** [comment]
Based on the graph, I think it's a false alarm.
