### ISSUE TITLE
[ml release] air_benchmark_tensorflow_mnist_gpu_4x4 times out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#29922]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1173#0184278f-8911-45b4-9f78-7233e2a2a64e

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
seeing
at around `2022-10-29 23:52:57`, starting tf_ray, finished at around `2022-10-30 00:06:00`
then starting tf_vanilla
1st try fails at 00:21 at epoch 200
2nd try fails at 00:36 at epoch 200
3rd try succeeds 

But the two failed tries causes the overall test to time out in the end.
@krfricke do you know why the vanilla try fail at times?

cc @bveeramani

**Comment by xwjiang2010** [comment]
```
Vanilla TF run failed: [36mray::CommandRunner.run_command()[39m (pid=44631, ip=172.31.70.157, repr=<benchmark_util.CommandRunner object at 0x7f5cc6a9aed0>)
  File "/home/ray/oss-release-tests-2/workloads/benchmark_util.py", line 72, in run_command
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/ray/oss-release-tests-2/workloads/tensorflow_benchmark.py', 'worker', '--num-epochs', '200', '--num-workers', '16', '--rank', '9', '--worker-ip-ports', '172.31.94.194:55019,172.31.94.194:36421,172.31.94.194:42759,172.31.94.194:59875,172.31.68.93:46341,172.31.68.93:42113,172.31.68.93:46545,172.31.68.93:34959,172.31.70.157:38197,172.31.70.157:33697,172.31.70.157:53035,172.31.70.157:37903,172.31.94.94:57809,172.31.94.94:51683,172.31.94.94:60143,172.31.94.94:48723', '--batch-size', '64', '--use-gpu']' died with <Signals.SIGABRT: 6>.
```

**Comment by xwjiang2010** [comment]
```
Vanilla TF run failed: [36mray::CommandRunner.run_command()[39m (pid=40198, ip=172.31.70.157, repr=<benchmark_util.CommandRunner object at 0x7f5569ebe090>)
  File "/home/ray/oss-release-tests-2/workloads/benchmark_util.py", line 72, in run_command
  File "/home/ray/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/ray/oss-release-tests-2/workloads/tensorflow_benchmark.py', 'worker', '--num-epochs', '200', '--num-workers', '16', '--rank', '9', '--worker-ip-ports', '172.31.94.194:49791,172.31.94.194:54161,172.31.94.194:47155,172.31.94.194:43883,172.31.68.93:35331,172.31.68.93:34259,172.31.68.93:45223,172.31.68.93:49665,172.31.70.157:56119,172.31.70.157:35245,172.31.70.157:54721,172.31.70.157:42339,172.31.94.94:57259,172.31.94.94:49147,172.31.94.94:33871,172.31.94.94:45483', '--batch-size', '64', '--use-gpu']' died with <Signals.SIGABRT: 6>.
```

Both times failed with rank 9, out of 16 workers.

**Comment by xwjiang2010** [comment]
always seems `172.31.70.157` that's having an issue out of so many different nodes...

sigabrt seems to suggest memory corruption from within the application itself.

**Comment by xwjiang2010** [comment]
wondering if this is the head node that is under memory pressure...

**Comment by xwjiang2010** [comment]
Another instance: 

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_nBJeS1ag1Ys4kByHP9LZBXNB?command-history-section=command_history

**Comment by xwjiang2010** [comment]
[Run 1/3] Running Tensorflow Ray benchmark
2022-11-12 22:44:41

...
<failed two vanilla runs in the middle>
[694096] subprocess.CalledProcessError: Command '['python', '/home/ray/oss-release-tests-2/workloads/tensorflow_benchmark.py', 'worker', '--num-epochs', '200', '--num-workers', '16', '--rank', '7', '--worker-ip-ports', '172.31.79.86:50515,172.31.79.86:43535,172.31.79.86:45467,172.31.79.86:40385,172.31.205.6:57267,172.31.205.6:47823,172.31.205.6:52241,172.31.205.6:36673,172.31.166.132:39167,172.31.166.132:59443,172.31.166.132:53845,172.31.166.132:55479,172.31.226.87:49669,172.31.226.87:33511,172.31.226.87:36055,172.31.226.87:56593', '--batch-size', '64', '--use-gpu']' died with <Signals.SIGABRT: 6>.


[1048024] subprocess.CalledProcessError: Command '['python', '/home/ray/oss-release-tests-2/workloads/tensorflow_benchmark.py', 'worker', '--num-epochs', '200', '--num-workers', '16', '--rank', '11', '--worker-ip-ports', '172.31.79.86:33103,172.31.79.86:59043,172.31.79.86:39721,172.31.79.86:35865,172.31.205.6:52393,172.31.205.6:51663,172.31.205.6:44947,172.31.205.6:36935,172.31.166.132:59223,172.31.166.132:34873,172.31.166.132:48335,172.31.166.132:45263,172.31.226.87:36869,172.31.226.87:45335,172.31.226.87:52515,172.31.226.87:37665', '--batch-size', '64', '--use-gpu']' died with <Signals.SIGABRT: 6>.
...



Finished Ray training (200 epochs) in 965.66 seconds (local training time: 950.88s)
Finished vanilla training (200 epochs) in 1110.35 seconds (local training time: 1106.03s). Observed loss = 0.5263


[Run 2/3] Running Tensorflow Ray benchmark
2022-11-12 23:57:21 
<(1h 13 minutes passed since the start of the test) by this point, we are doomed to be out of time already.>

**Comment by xwjiang2010** [comment]
actually this time, the failure workers happened to be on different nodes..

**Comment by justinvyu** [comment]
Smoke test version (2 nodes, 2 workers per node) also has the vanilla TF run fail: [cluster link](https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_mWECugke9RzMh79BZQqeykjN/clusters/ses_ruyBekz4Z3Zxs1fJtQ5hy4bn?command-history-section=head_start_up_log)

Plan now is to debug with the 2x2 smoke test.

Also, a separate issue: currently, if all 3 retries of the vanilla TF run fail, then a vanilla runtime of 0 seconds gets added to the results, which brings the vanilla runtime average down, which causes the test assertion at the end to fail.

**Comment by xwjiang2010** [comment]
Thanks @justinvyu 

Yeah then let's debug on 2 X 2 case. 

> Also, a separate issue: currently, if all 3 retries of the vanilla TF run fail, then a vanilla runtime of 0 seconds gets added to the results, which brings the vanilla runtime average down, which causes the test assertion at the end to fail.

We can fix this by throwing a dedicated error.

**Comment by xwjiang2010** [comment]
things are significantly slower as well after we upgrade our docker cuda version?

cc @amogkam 

![Screen Shot 2022-11-17 at 5 21 42 PM](https://user-images.githubusercontent.com/87673679/202594918-afaa0223-8f8b-4a4b-b76b-5d0cced9338f.png)


Also @justinvyu found out this may be a native issue with Mirrored Strategy: https://github.com/tensorflow/tensorflow/issues/55250
Kai already referenced it here https://github.com/ray-project/ray/pull/26776

For both reasons, I am proposing to mark this test unstable. It's not giving us any value at this point. @amogkam wdyt?
