### ISSUE TITLE
[Job Submission] Agent logs are streamed to driver when ray job submission SDK is used 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#29944]
### What happened + What you expected to happen

Looks like when the job submission SDK is used, all of the agent logs start streaming to stderr, which will be redirected to the parent stderr (raylet), which in turn prints logs to drivers. This will make the driver extremely spammy, especially given we have 1 agent per node. 

One suspicion is that when the job agent calls `ray.init` for job submission, it screws up the logging config. 

### Versions / Dependencies

master

### Reproduction script

Run `test_jobs_cluster_events ` in this PR https://github.com/ray-project/ray/pull/29196/files#diff-eefc9640224890baa2551cc2cf9c657799cfb4828bdaba128da17fea5f57ce4d (this will be merged soon)

**Comment by architkulkarni** [comment]
Sample driver output:

```
collecting ... 2022-11-02 01:30:21,563	INFO worker.py:1528 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265/ 
Test successful job run.
(raylet) 2022-11-02 01:30:26,650	INFO worker.py:1351 -- Connecting to existing Ray cluster at address: 127.0.0.1:64389...
(raylet) 2022-11-02 01:30:26,657	INFO worker.py:1528 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265/ 
(raylet) 2022-11-02 01:30:26,677	INFO job_manager.py:637 -- Starting job with submission_id: raysubmit_5epDrgS1YpjHqN7z
(raylet) 2022-11-02 01:30:26,678	INFO job_manager.py:586 -- Head node ID found in GCS; scheduling job driver on head node 1f9c8ca7a8cc972404e7f7da7854f8562f00d1b68ee172e2b80dd6b0
(raylet) 2022-11-02 01:30:26,723	INFO runtime_env_agent.py:323 -- Creating runtime env: {"env_vars": {"RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES": "1"}} with timeout 600 seconds.
```

**Comment by rkooo567** [comment]
After @architkulkarni 's initial investigation, the issue seems like Ray corrupts some of logging configuration (this start happening because we start ray.init from the agent, which streams logs to the driver). I assume the same issue happened with the dashboard before. I will take it over and fix it.
