### ISSUE TITLE
[Observability Documentation] Unable to follow instructions for starting prometheus on Mac

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#29950]
### What happened + What you expected to happen

I followed the instructions in the **Getting Started (Single Node)** section of this page https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#getting-started-single-node.

When I ran `./prometheus --config.file=./prometheus.yml`, I got the following popup. I wasn't sure how to get around this.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/249517/199560604-de92c115-5631-476f-bc53-85dfa2c282fc.png">
****

### Versions / Dependencies

MacOS 10.15.7
Ray: Latest nightly e85355b9b593742b4f5cb72cab92051980fa73d3
Python: 3.7.4

### Reproduction script

See above

### Issue Severity

Blocker for using Prometheus.

**Comment by rkooo567** [comment]
This is the Mac specific issue (when the binary is downloaded, it is not authorized). You can fix it by going to the finder and open the binary by right click -> open IIRC. But we will update the documentation and add a troubleshoot guide.

**Comment by rkooo567** [comment]
cc @alanwguo

**Comment by alanwguo** [comment]
Yes, this is a fairly common Mac issue (not specific to Ray). I can add a "common issues" section and link to the mac docs: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

FYI: @scottsun94 who ran into the same thing
