### ISSUE TITLE
[Java] Flakey case testNestedObjectId

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#29967]
https://buildkite.com/ray-project/oss-ci-build-pr/builds/3784#018432f6-be58-47e5-8cbd-90961fc20b05

testNestedObjectId failed flakey on master. It might be caused by some change of object ref under the hook.

**Comment by jovany-wang** [comment]
Hi @ConeyLiu  do you have bandwidth to take a look?

**Comment by ConeyLiu** [comment]
Hi @jovany-wang, thanks for pinging me. I have not kept following the source code of Ray for a long time. So my apology, I could not provide some knowledge about the failed UT.

**Comment by ConeyLiu** [comment]
cc @kira-lin my have some hints on this.

**Comment by kira-lin** [comment]
@jovany-wang I may not have the bandwidth to look into it now. When does it appear? Is it due to a particular PR?
