### ISSUE TITLE
[Datasets] In Arrow 10+, S3 errors raised due to permission issues can vary beyond our current pattern matching

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#29994]
We currently pattern match against exception messages to determine if an S3 error that was raised is due to a permissions issue; this allows us to raise a more informative, more actionable Datasets-level error for the user. In Arrow 10+, Arrow may raise a few other S3 error messages than our current pattern matching supports.

We should expand our error message pattern matching to cover these new error messages.

**Comment by pcmoritz** [comment]
In particular, we should make sure to always also show the original Arrow error message now, since it container important information now about what is going wrong (e.g. the concrete S3 API call that caused the problem).
