### ISSUE TITLE
[Datasets] Make TFRecords datasource return Arrow Tables, similar to our other datasources.

### ISSUE THREAD

**Issue by clarkzinzow** [ray-project/ray#30003]
The current `TFRecordsDatasource` [returns Pandas DataFrames](https://github.com/ray-project/ray/blob/45cdd3872e59324803b49e1cd097349d6bf4b9be/python/ray/data/datasource/tfrecords_datasource.py#L36), which can result in slower downstream preprocessing and/or inference routines. Since Arrow Tables are typically a more efficient data representation, have faster compute kernels, and have a more consistent zero-copy exchange with NumPy and Torch/TensorFlow tensors, we should try to return Arrow Tables from the datasource instead.

**Comment by matthewdeng** [comment]
@c21 is this closed by https://github.com/ray-project/ray/pull/30390? 😄

**Comment by c21** [comment]
@matthewdeng - yeah, closing this issue as be completed by https://github.com/ray-project/ray/pull/30390 .
