### ISSUE TITLE
[Tune][Docs] `ResultGrid` reference doesn't contain `ResultGrid`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30002]
### Description

The "ResultGrid (tune.ResultGrid)" page of the Tune API reference doesn't actually contain the `ResultGrid` reference. It only contains the `ExperimentAnalysis` reference.

### Link

https://docs.ray.io/en/latest/tune/api_docs/result_grid.html

**Comment by justinvyu** [comment]
I think this is fixed by https://github.com/ray-project/ray/pull/29670 on master.

**Comment by bveeramani** [comment]
Ah, you're right! Will close this issue as it's not necessary anymore.
