### ISSUE TITLE
[CI] `bk://:mac: :apple: Wheels and Jars` red

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#30026]
<img width="849" alt="Screen Shot 2022-11-04 at 10 12 33 AM" src="https://user-images.githubusercontent.com/950914/200035617-2e4af490-b60e-4547-bef9-05f478d8d311.png">

**Comment by clarng** [comment]
trying another patch https://github.com/ray-project/ray/pull/30085

**Comment by clarng** [comment]
yet another try https://github.com/ray-project/ray/pull/30088

**Comment by clarng** [comment]
Close for now, will revisit better fix or clean up of the CI steps
