### ISSUE TITLE
[CI] `bk://:windows: Wheels` red

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#30027]
<img width="606" alt="Screen Shot 2022-11-04 at 10 15 32 AM" src="https://user-images.githubusercontent.com/950914/200036309-f1f77684-1ae7-4ad6-a55b-b946060c0211.png">

**Comment by clarng** [comment]
looks like nodejs version changed, trying to pin

**Comment by clarng** [comment]
seems like 
- nodejs can be pre-installed with different versions on the windows machine
- if nodejs is not pre-installed it will try to download and fail to install, thus failing the Wheel

This happens only with the Build target, but not Build & Test, trying to clone the setup

**Comment by clarng** [comment]
Seems to have self recovered

<img width="1567" alt="Screen Shot 2022-11-06 at 9 19 06 AM" src="https://user-images.githubusercontent.com/22830327/200185129-538f8084-4d83-4974-90bc-5aba4693222d.png">

**Comment by clarng** [comment]
<img width="1603" alt="Screen Shot 2022-12-13 at 11 12 50 AM" src="https://user-images.githubusercontent.com/22830327/207424591-ece3d352-4a4e-417e-9f50-2ff6c9a6f9a2.png">
