### ISSUE TITLE
[Tune] Add documentation for ray.tune.TuneConfig

### ISSUE THREAD

**Issue by arnavgarg1** [ray-project/ray#30040]
### Description

At the moment, there's no good way to find documentation for tune.TuneConfig on the Ray documentation link. The only way I've found is to actually go into the Ray project code and find it here (https://github.com/ray-project/ray/blob/master/python/ray/tune/tune_config.py#L12). Can we add this to the docs?

### Link

https://github.com/ray-project/ray/blob/master/python/ray/tune/tune_config.py#L12

**Comment by matthewdeng** [comment]
`TuneConfig` is technically being displayed in the [AIR API References](https://docs.ray.io/en/latest/ray-air/package-ref.html#ray.tune.tune_config.TuneConfig) but can certainly be cleaned up and made more discoverable. @justinvyu maybe you can address this as part of the API reference separation work?

**Comment by justinvyu** [comment]
@matthewdeng Yes, planning to put it in a better place!

**Comment by matthewdeng** [comment]
Marking this as closed by https://github.com/ray-project/ray/pull/32311! This is now appropriately placed with the [`Tuner` documentation](https://docs.ray.io/en/master/tune/api/execution.html).
