### ISSUE TITLE
[Datasets] Override `pickle.dumps(ds)` behavior to be same as `ds.serialize_lineage()`

### ISSUE THREAD

**Issue by c21** [ray-project/ray#30058]
### Description

From Ray Tune, there's requirement to checkpoint and restore dataset in multiple places (according to @justinvyu and @xwjiang2010). It seems more convenient if Dataset can provide same behavior when calling `pickle.dumps(ds)` (i.e. to copy lineage, remove computed blocks object refs).

### Use case

Ray Tune restore

**Comment by clarkzinzow** [comment]
@c21 Hard -1 to this, we purposefully didn't do this.
- `ds.serialize_lineage()` is for serializing the lineage to recreate the `Dataset` such that the lineage can be persisted to disk and recreate on another cluster. To do this, we need to purge the Ray objects (which can't be shared across Ray clusters) and store the lineage to recreate the `Dataset`.
- `pickle.dumps(ds)` is used for sending a `Dataset` from one Ray node to another (e.g. as the argument of a task), and should include the Ray objects pointing to the computed data, *not* the lineage to recreate the objects.

These are fundamentally two different use cases. If we adopted lineage-based serialization for `pickle.dumps()`, we'd be recreating the `Dataset` from scratch in every trainer.

**Comment by clarkzinzow** [comment]
If we know that we're going to be restoring the `Dataset` on the same cluster and that the underlying Ray objects holding the data will still exist (or will be recomputable via Ray Core's lineage-based object reconstruction), then we can have a fast-path restoration that uses the existing `pickle.dumps()` path.

If we're wanting this to work automatically for `Dataset` restoration, we could augment the `ds.serialize_lineage()` to not purge Ray objects, and upon restoration, try to use the Ray objects, and if they aren't recoverable (e.g. owners are dead or we're on a different cluster), we can use the lineage to recreate the `Dataset`.

@xwjiang2010 @justinvyu Could you comment more on the use case?

**Comment by jianoaix** [comment]
Yeah these are two different cases. Passing dataset around in a Ray cluster should not clear objects. I think the question is what does it mean "in multiple places" for the issue here.

**Comment by justinvyu** [comment]
This question is coming from these two tickets: https://github.com/ray-project/ray/issues/29595 and https://github.com/ray-project/ray/issues/29597, where we are trying to resume a Tune experiment on a different cluster, and a dataset has been serialized with the Trainer.

Your explanation of why this shouldn't be the default makes sense, and I think Tune needs to manually save the dataset lineage instead of just doing a `pickle.dump(trainer)` like we're [doing now](https://github.com/ray-project/ray/blob/e466a9e6b81ef1763c62d244cc7751879f4d5bf0/python/ray/tune/impl/tuner_internal.py#L126).

**Comment by clarkzinzow** [comment]
@justinvyu You should coordinate with @xwjiang2010, we already implemented a Tune-level serialization hook covering this for checkpoints:
- https://github.com/ray-project/ray/blob/f1882f90cf2d91f5d802b7dffd41db5e306d6e6c/python/ray/tune/execution/trial_runner.py#L192-L193
- https://github.com/ray-project/ray/blob/e466a9e6b81ef1763c62d244cc7751879f4d5bf0/python/ray/tune/impl/out_of_band_serialize_dataset.py

**Comment by matthewdeng** [comment]
> If we're wanting this to work automatically for `Dataset` restoration, we could augment the `ds.serialize_lineage()` to not purge Ray objects, and upon restoration, try to use the Ray objects, and if they aren't recoverable (e.g. owners are dead or we're on a different cluster), we can use the lineage to recreate the `Dataset`.

For Ray AIR, this proposal is desirable. Though we have the serialization hook for Tune parameter space, this currently doesn't cover the case where the `Dataset` is directly serialized as part of the `Trainer`. Though I'm not sure how generalizable this is for _all_ Datasets.

@clarkzinzow @c21 would this fit into the Datasets execution refactor?

**Comment by clarkzinzow** [comment]
@matthewdeng This could be cleaner with the execution refactor, but we could do this now pretty easily if this feature sounds compelling.
