### ISSUE TITLE
[air] Documentation: How to get things in and out of Ray AIR

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#30074]
It is currently not clearly documented how the input (e.g. data, configuration) and output (e.g. metrics, checkpoints) of Ray AIR works. We should add a nice overview in the Ray AIR documentation.

**Comment by xwjiang2010** [comment]
May be related? https://github.com/ray-project/ray/issues/30158
https://github.com/ray-project/ray/issues/29949

**Comment by richardliaw** [comment]
This is a redundant with https://github.com/ray-project/ray/issues/28528 . I'll close this for now and assign Antoni to the other one.
