### ISSUE TITLE
Problems with launching a Ray cluster

### ISSUE THREAD

**Issue by hbodory** [ray-project/ray#30092]
I created a virtual Windows Server 2019 machine and installed Python using the Anaconda distribution. On this machine made a new virtual environment and installed Ray 2.0.1 using the command pip install -U "ray[default]". Then I created 2 copies of this machine to ensure that all three servers have the same Python and Ray versions. I opend the ports 3389, 6379, 8265, 10000-10004 on all of the 3 virtual machines. I am able to start the head node typing the command ray start --head --port=6379, see the attached screenshot headNode.PNG.  However, when I try to connect one of the other 2 servers with the head node using ray start --address=86.119.35.227:6379 (the IP address of the head node is 86.119.35.227), a ConnectionError will be raised, see the attached screenshot error.PNG. How can I solve this issue?
 
![headNode](https://user-images.githubusercontent.com/24809337/200529179-3f0fac2d-9957-4d99-bc05-701bb67feb5c.PNG)
![error](https://user-images.githubusercontent.com/24809337/200529218-62c94860-ebbd-4d18-8153-cd3aae9f0165.PNG)

**Comment by DmitriGekhtman** [comment]
Multi-node Ray clusters with Windows nodes are not yet officially supported.
