### ISSUE TITLE
[Datasets] [Release] remove `datasets_preprocess_ingest` 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30108]
### What happened + What you expected to happen

cc @c21 
As discussed in oncall handoff, I think the data team wanted to go ahead and remove this test.

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by c21** [comment]
@xwjiang2010 - yeah, will remove this nightly test.

**Comment by c21** [comment]
Nightly test is removed, closing.
