### ISSUE TITLE
Rainbow for Pytorch?

### ISSUE THREAD

**Issue by gorogm** [ray-project/ray#3012]
Dear Developers,

I didn't receive answer on ray-dev@ for two weeks, so let's see here :)

I am curious if the DQN / Rainbow implementation can be run with either TF or Pytorch backend? I couldn't find info specificly about it.
Did anybody run trainings to compare them?

Thanks,
Márton

**Comment by ericl** [comment]
Hey @gorogm, we have a TF implementation here: https://ray.readthedocs.io/en/latest/rllib-algorithms.html#deep-q-networks-dqn-rainbow

There isn't one for PyTorch.

**Comment by richardliaw** [comment]
should be supported now: https://docs.ray.io/en/latest/rllib-algorithms.html#feature-compatibility-matrix
