### ISSUE TITLE
[ray core] Support GPU to GPU Communication Between Actors/Task

### ISSUE THREAD

**Issue by mjshare** [ray-project/ray#30138]
### Description

Problem description:
Currently, ray object stores are used for communication between ray actors. When GPUs are used, GPU passthrough is not supported. As a result, the data transmission delay is long and the PICE bandwidth becomes a bottleneck.
Expectations:
1. Ray Actors/Tasks can support GPU passthrough when running GPU tasks. I know that the ray community is working on this project. What is the current progress? Will the underlying technology use ucx_py?

2. In addition, it is expected that data in Arrow format can be transmitted between GPUs.

**Comment by jovany-wang** [comment]
I still don't know what's the best way we transmit data between GPUs, implementing in object store or building on the top of ray core.

Also CC @jiaodong for more details.

**Comment by mjshare** [comment]
> I still don't know what's the best way we transmit data between GPUs, implementing in object store or building on the top of ray core.
> 
> Also CC @jiaodong for more details.

 @jiaodong Do you know any more details?

**Comment by jiaodong** [comment]
@mjshare in our discussions we didn't see the ROI to build it at Ray Core level yet and current pattern is still leave if at application level. There're a few successful use cases that enabled it even for HPC workload, such as https://github.com/alpa-projects/alpa.

The mechanism under the hood is setup actors with registered uuid for each buffer, such as 
```
Actor A gets an instruction SEND BUFFER (UUID= 5) to ACTOR (ACTOR_UUID=B)
Meanwhile actor B will get an instruction "RECV BUFFER (UUID=6)" from ACTOR (ACTOR UUID=A)
```
so the only inter-actor communication is sending the string instructions around, where actual communication happens via NCCL by `ray.collective`.

**Comment by mjshare** [comment]
> @mjshare in our discussions we didn't see the ROI to build it at Ray Core level yet and current pattern is still leave if at application level. There're a few successful use cases that enabled it even for HPC workload, such as https://github.com/alpa-projects/alpa.
> 
> The mechanism under the hood is setup actors with registered uuid for each buffer, such as
> 
> ```
> Actor A gets an instruction SEND BUFFER (UUID= 5) to ACTOR (ACTOR_UUID=B)
> Meanwhile actor B will get an instruction "RECV BUFFER (UUID=6)" from ACTOR (ACTOR UUID=A)
> ```
> 
> so the only inter-actor communication is sending the string instructions around, where actual communication happens via NCCL by `ray.collective`.

Did you know that someone uses ucx-py for GPU passthrough?

**Comment by scv119** [comment]
merge the issue into #30094
