### ISSUE TITLE
[tune] `CLIReporter` cannot parse customized metrics specified from TuneConfig as `metric` correctly in `sort_by_metric`

### ISSUE THREAD

**Issue by spacegoing** [ray-project/ray#30144]
### What happened + What you expected to happen

Lets say I assign a customized metric to `TuneConfig` and customized a CLIReporter while setting `sort_by_metric=True`

```python

reporter = CLIReporter(
    metric_columns={
        "custom_metrics/perbatch_reward_perstep_mean":
            "t_rew_ts",
        "evaluation/custom_metrics/perbatch_reward_perstep_mean":
            "e_rew_ts",
    },
    sort_by_metric=True,
)

Tuner = tune.Tuner(
    algo_name,  # We'll be using the builtin PPO agent in RLLib
    run_config=air.RunConfig(
        progress_reporter=reporter),
    tune_config=tune.TuneConfig(
        mode="max",
        metric=checkpoint_metric,
        search_alg=search_alg,
    ),
    param_space='evaluation/custom_metrics/perbatch_reward_perstep_mean'
)
```

The problem is that in `progress_reporter.py`, there are code snippets do not always use `unflattened_lookup()` and results in `key not found error`

<img width="888" alt="Screen Shot 2022-11-10 at 00 43 07" src="https://user-images.githubusercontent.com/5180020/200889416-71d91a18-49b2-4751-bfdc-51ede0058940.png">

<img width="981" alt="Screen Shot 2022-11-10 at 00 45 29" src="https://user-images.githubusercontent.com/5180020/200889923-bd08ff58-e3d7-4be4-9794-147288803c56.png">

### Versions / Dependencies

ray 2.0.0

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
Thanks a bunch for reporting this! We'll find someone to take this.
