### ISSUE TITLE
[RLlib] ParameterNoise postprocessing overwrites actions in sample batch to non-noisy actions

### ISSUE THREAD

**Issue by mgerstgrasser** [ray-project/ray#30147]
### What happened + What you expected to happen

The ParameterNoise postprocessing method right now (inadvertently) overwrites all the actions in the sample batch with the non-noisy actions. I.e. if the original policy would have taken action 0, but because of the parameter noise we took action 1 and got reward 10 etc, the postprocessing will change the sample batch from `action 1, reward 10, etc` to `action 0, reward 10, etc`, even though it wasn't action 0 that led to that reward etc. This is because it passes a reference to the sample batch into `policy.compute_actions_from_input_dict()` as the input dict, which overwrites the actions in whatever is passed to it.

I can't see how we would want to put the non-noisy actions together with the rewards, next state etc generated from noisy actions. But I also just wanted to double check that I'm not misunderstanding how parameter noise is supposed to work.

I've opened a PR to fix this by passing a copy of the sample batch instead: #30145

### Versions / Dependencies

ray==2.0.1

### Reproduction script

I don't have a reproduction script right now because making one self-contained would take much more work than just fixing the issue, but let me know in case the fix doesn't look obviously benign to you.

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hey @mgerstgrasser great catch! Looks reasonable to me. Can you come up with a small repro script? Ideally something that we can turn into a unit test? Thanks anyways 👍

**Comment by mgerstgrasser** [comment]
@ArturNiederfahrenhorst  I'd need a little bit of time to extricate this out of a much larger project, but yes, I could come up with a repro script where due to the bug a SimpleQ algorithm will fail to learn on a very simple two-armed bandit. More of a integration test though, not sure how I would unit test just the exploration class. Also, for that bandit setting, a few different things have to come together to make things break end-to-end:
1. Two possible actions, a0 giving small or negative reward, a1 giving larger positive reward. Average of the two rewards must be positive. Just a single state s0.
2. A simple linear policy (essentially just two model parameters, one for `q(s0,a0)` and one for `q(s0,a1)`
3. `normc` initializer setting weights to +- 0.01 (is that intentional that it's always just one of the two values, not e.g. a normal distribution?)
4. Deterministic tie-breaking, i.e. if `q(s0,a0) == q(s0,a1)` then output action a0 always. 
 
3.+4. combined mean that in 3/4 of random seeds, initially the (non-noisy) policy will always output a0 (one possible initialization has `q(s0,a0) == 0.01 > q(s0,a1) == -0.01` and two have `q(s0,a0) == q(s0,a1) == +-0.01`). With parameter noise we end up collecting half-and-half experiences from a0 and a1; due to the bug all of these are rewritten to be experiences from the non-noisy action a0. Since the average reward is positive, `q(s0,a0)` will therefore increase, and we end up learning to always perform action a0, even though a1 has better reward.

Not sure if this could be made into a unit test easily. Also I don't know if that `normc` behavior is intended? Let me know if you think this would be useful as a repro script.

**Comment by mgerstgrasser** [comment]
@ArturNiederfahrenhorst @sven1977 Just wanted to check if this can be merged? (PR just went stale again.)

**Comment by ArturNiederfahrenhorst** [comment]
Hi @mgerstgrasser ,

Very interesting combination of circumstances.
Thanks for explaining.

Ad 3. : The norm initializer is intentional and has empirically led to some good results as a default.

**Comment by Rohan138** [comment]
Closing per discussion in #30145 (issue no longer appears, seems to have been fixed)
