### ISSUE TITLE
[Tune] Document the parameter passing and connection from param_space to trainable

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#30158]
This is recording a user feedback where the user felt unclear:
- What can be put in param_space
- How the param_space is connected to trainable
- How to pass args that are not part of the Trainer's constructor args

cc @xwjiang2010

**Comment by justinvyu** [comment]
Closing as this should be clarified by [this user guide](https://docs.ray.io/en/releases-2.3.0/tune/tutorials/tune_get_data_in_and_out.html#getting-data-into-tune) by @Yard1.
