### ISSUE TITLE
Make distributed SGD implementation fault tolerant.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3016]
We already have the actor fault tolerance primitives in place, so it should just be a matter of using them in the SGD implementation.

**Comment by richardliaw** [comment]
(or try out different SGD implementations, including https://arxiv.org/abs/1710.06952 which claims very nice performance and scaling without requiring high availability)

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
