### ISSUE TITLE
[Ray Cluster]How to persist the state of ray cluster

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#30171]
I have deployed some services on the ray cluster. When there is a problem with the cluster and need to restart the cluster, how to restore some of the previously deployed services?
is there any suggestions?

**Comment by DmitriGekhtman** [comment]
There is support for fault-tolerant deployments of Ray Serve on Kubernetes.
https://docs.ray.io/en/latest/serve/production-guide/kubernetes.html

If those docs don't answer your question, I recommend opening a discussion thread with more details on discuss.ray.io
