### ISSUE TITLE
[core] Access ObjectRefs created by a dynamic generator before the task is complete

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#30192]
### Description

Currently dynamic generators do not return any ObjectRefs until the task is entirely done, which may be an issue if other tasks want to use partial results before the task is complete. We could support this in Ray core by passing back some ObjectRefs from the generator task to the driver while the task is still executing. Alternatively, one could achieve similar behavior by splitting the generator task into multiple smaller generator tasks, each returning the index that the next task should start from.

### Use case

The main use case would be fine-grained pipelining between the generator task and the driver or another task using the results. However, the concrete applications of this are not clear yet, especially when we would need this compared to the described alternative. So we may not need to support this behavior natively in Ray core.

**Comment by rkooo567** [comment]
This is handled!
