### ISSUE TITLE
how to set the max_t 

### ISSUE THREAD

**Issue by yjgeno** [ray-project/ray#30202]
There are two places where we can define the iteration numbers:

```
tune_config = tune.TuneConfig(scheduler = ASHAScheduler(max_t = 100, ...) )
run_config = air.RunConfig(stop={ "training_iteration": 100})
```

How does ray internally determine the number of iterations? 
Does the final report report each model's best metric or the last epoch metric? If the former one is the case, am I suppose to set a significantly large number for the iteration and tune other hyperparameters?

**Comment by matthewdeng** [comment]
Hey @yjgeno,

`training_iteration` is defined by the number of calls to `session.report()`.  If you set different values (see example below), then the Trial will be terminated after the smaller number of iterations is completed.

```python
tune_config = tune.TuneConfig(scheduler = ASHAScheduler(max_t = max_training_iteration_1, ...) )
run_config = air.RunConfig(stop={ "training_iteration": max_training_iteration_2})
```

The final report will include whatever metric you choose to report in it, which should typically be the last epoch metric. However, you can then access the [experiment results](https://docs.ray.io/en/master/tune/examples/tune_analyze_results.html) and look through the historical metrics that were [reported through a Trial](https://docs.ray.io/en/master/tune/examples/tune_analyze_results.html#trial-level-analysis-working-with-an-individual-result)!

**Comment by yjgeno** [comment]
Hi @matthewdeng thanks for your reply, this is helpful.
So a good practice might be I save the tune result, look through all trials' historical metrics after that, and retrieve the checkpoint of the best model?

Is there any way we could tune the iteration number? I am not sure whether it is still a hyperparameter tuning problem though

**Comment by matthewdeng** [comment]
Yeah, that should work, but let me know if it doesn't.

> Is there any way we could tune the iteration number?

You can also pass in a number of iterations as part of the `param_space`, and terminate the script when you get that number of iterations.
