### ISSUE TITLE
[Java] ray jars is not releasing properly 

### ISSUE THREAD

**Issue by kira-lin** [ray-project/ray#30206]
### What happened + What you expected to happen

Currently, the ray snapshot jars is not uploading. In addition, the stable version of ray jars is not released at the same time as ray python. As ray slows down its releasing pace, it becomes very inconvenient for us to enable new java features.

We hope that ray snapshot jars can be uploaded daily, or weekly, and that ray stable jars can be released automatically when python releases.

@jovany-wang 

### Versions / Dependencies

ray java

### Reproduction script

N/A

**Comment by matthewdeng** [comment]
Hey @jovany-wang, regarding the stable jars we pushed versions 2.0.1 and 2.1.0 to Maven two days ago on 11/09/22. As of yesterday we saw that they were not visible on https://mvnrepository.com/artifact/io.ray/ray-api but were in https://repo1.maven.org/maven2/io/ray/ray-api/. Did you need to do anything to get them to surface in https://mvnrepository.com/artifact/io.ray/ray-api?

cc @c21

**Comment by jovany-wang** [comment]
@matthewdeng  It's ok. There should be a little delay in [https://mvnrepository.com](https://mvnrepository.com/artifact/io.ray/ray-api)

**Comment by c21** [comment]
Hi @kira-lin - the Java jar for Ray 2.1.0 and 2.0.1 were released last week. Could you help check if it works on your side now? Thanks.

**Comment by kira-lin** [comment]
Yes, I can now fetch the stable jars to compile in CI. Thanks @c21
