### ISSUE TITLE
Issue on page /data/api/grouped_dataset.html

### ISSUE THREAD

**Issue by PraneshMP** [ray-project/ray#30205]
```
import ray
from ray.data.aggregate import AggregateFn
ds = ray.data.range(100) 
grouped_ds = ds.groupby(lambda x: x % 3) 
grouped_ds.aggregate(AggregateFn( 
    init=lambda k: [], 
    accumulate=lambda a, r: a + [r], 
    merge=lambda a1, a2: a1 + a2, 
    finalize=lambda a: a 
)) 
```

When I try to run this example code, I am getting error on "accumulate", Should accumulate be replaced by accumulate_row? 

My versions are 

Python version:	3.8.13
Ray version:	2.0.1

**Comment by matthewdeng** [comment]
Hey @PraneshMP yeah that's right! This was fixed in https://github.com/ray-project/ray/pull/30083 and now shows the correct code in the [master documentation](https://docs.ray.io/en/master/data/api/grouped_dataset.html).
