### ISSUE TITLE
[RLLib] Customized metrics is missing the last observation

### ISSUE THREAD

**Issue by spacegoing** [ray-project/ray#30213]
### What happened + What you expected to happen

Please correct me if I'm wrong.

In current logic, `outputs.append(RolloutMetrics)` is called before `on_episode_step` and `on_episode_end`, snippets shown below. So that the last obs' customized metrics never gets reported.

<img width="1266" alt="Screen Shot 2022-11-12 at 01 31 13" src="https://user-images.githubusercontent.com/5180020/201397500-bc6ebb5a-64ff-47ae-a888-0da29f957e4d.png">
<img width="1283" alt="Screen Shot 2022-11-12 at 01 34 22" src="https://user-images.githubusercontent.com/5180020/201397478-f15623e6-de0f-4c57-9b3d-80f2acd4bcf3.png">

### Versions / Dependencies

2.0.0

### Reproduction script

As above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Hey @spacegoing , thanks for filing this! I think you are right. I moved the rollout-metrics-append after the last callback in the above PR. LEt's see whether all tests pass. Happy to merge this after that.
