### ISSUE TITLE
[CI] `linux://doc:source/rllib/doc_code/getting_started` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#30211]
- a683bc658587e8db71cc0507d5b6f5784113da6d FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1032#018466f7-bf40-4295-aae9-7d2474ebe517)
- 51ea8410331dd2dd5b1aa7a21d2feb9c0f662a8f FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1031#01846637-134f-41b0-a850-0441642ea46a)
- 8f3bc61d0a829b14a6249a2e0b7b147f59bfafae FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1030#01846565-0a85-4ffa-a77f-5ef915e20148)
- d092300b336c69c1cefa019b3812b4a34138afac FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1029#0184647a-dac3-4d40-b46c-e166e51e999d)
- 9da53e3e5a6ec7b9bea32cd68f00f3e9468056ef FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1028#01846475-384b-42d5-ab65-cc2fcbeed0dd)
- 27201bbf2c2aed42bf82f096fdf6e597de0e6e89 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1025#018463d8-3777-47cd-8008-c26d154a7db4)
- 4b17fccecebcdcc2c01f13a9ce9259918b3c66c4 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1024#018463d5-18a1-400b-9c4d-ae741498295f)
- a1ff9b9aa457b20b8294cf953ef711c5f969f027 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1023#018463d1-a799-4761-96cc-b5cf0a5421b7)
- f9173a189023ccf4b4b09cf1533c628da13d000b FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1022#01846385-d88d-4d38-a538-b981c83eb63c)
- 20d1a704e3058e1b7645f51b629d58dd633e0dc0 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1021#01846363-df33-4c76-8a86-cb3b3f25e82c)
- ce6625c5019d921e4bc1fc007133119574a0940d FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1020#0184630e-6865-4b7b-93d4-db5e74f47c6e)
- 3d9920b0a7bdea12f59ac9041f44bb0fe85d8d6f FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1019#01846307-74a9-4d26-b306-f7a40e6a0135)
- 83a6c054016ba0e5f52387c52e028ecf27dca127 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1018#018462f7-eec7-438a-b995-91999a048f01)
- 993008e1ed8c592b268f0e66dac3260c8a14a893 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1017#018462a6-2396-4060-9139-28e6204388bb)
- d7132a4e220ef3fa5ee2f91e9cd10e6037a70be0 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1016#01846275-d249-49cb-bbcd-cd48235c5527)
- 656320209a09e2ec1e67446fe46f677495bc9c0e FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1015#01846268-fad4-474d-bc90-1b8977970e3a)
- acf996a45e4754519fbbdf92d934bb349085ce7a FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1014#018461c6-8b6f-40f1-bb2b-6bf81c67cddb)
- e715a8b7616f9f24839531fcefc1420f79ab13ec FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1013#01846141-c5cd-43c4-bfae-1f784777a538)
- 093c8dc1c92d79ad5349544c69933671c6bd658c FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1012#01846140-09bd-4fb7-90a6-e61fd233949b)
- 23f460b0fed058e10f1918ece3046976b9b71f5c FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1011#01846097-1335-45e2-b9bf-5b90d675318d)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc:source/rllib/doc_code/getting_started-END
....

**Comment by clarng** [comment]
@richardliaw  do you know who might be the a good person to look at this ? seems rl lib related

**Comment by clarng** [comment]
//doc:source/rllib/doc_code/getting_started                              FAILED in 3 out of 3 in 100.1s
--
  | Stats over 3 runs: max = 100.1s, min = 99.4s, avg = 99.7s, dev = 0.3s
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/doc/source/rllib/doc_code/getting_started/test.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/doc/source/rllib/doc_code/getting_started/test_attempts/attempt_1.log
  | /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/testlogs/doc/source/rllib/doc_code/getting_started/test_attempts/attempt_2.log

**Comment by clarng** [comment]
latest commit touching this file

commit 23f460b0fed058e10f1918ece3046976b9b71f5c
Author: Max Pumperla <max.pumperla@googlemail.com>
Date:   Thu Nov 10 08:56:04 2022 +0100

    [RLlib] AlgorithmConfig docs (#29796)

**Comment by ArturNiederfahrenhorst** [comment]
This has been fixed in #30252
