### ISSUE TITLE
[Tune] Scope of `Tuner.restore()` functionality is unclear in docs

### ISSUE THREAD

**Issue by wxie2013** [ray-project/ray#30223]
### What happened + What you expected to happen

The resumed run has identical best values as the first run. In another word, the tuning doesn't make further progress when resuming the runs.  I expect every time the code is run, it will resume from the last checkpoint and produce better results. 

### Versions / Dependencies

ray2.10

### Reproduction script

      import os
      from ray import tune, air
      from hyperopt import hp
      from ray.tune.search.hyperopt import HyperOptSearch
      from ray.air import session
      from ray.air.checkpoint import Checkpoint

      # 1. Define an objective function.
      def objective(config):
          score = config["a"] ** 2 + config["b"]
          session.report({'SCORE':score})

      # 2. Define a search space.
      search_space = {
          "a": hp.uniform("a", 0, 1),
          "b": hp.uniform("b", 0, 1)
          }

      raw_log_dir = "ray_log"
      raw_log_name = "example"
      log_dir = os.path.join(os.getcwd(), raw_log_dir, raw_log_name)
      if os.path.exists(log_dir) == False:
          print('--- this is the 1st run ----')
          algorithm = HyperOptSearch(search_space, metric="SCORE", mode="max")
          tuner = tune.Tuner(objective,
                  tune_config = tune.TuneConfig(
                      num_samples = 1, # number of tries. too expensive for Brian2
                      search_alg=algorithm,
                      ),
                  param_space=search_space,
                  run_config = air.RunConfig(local_dir = raw_log_dir, name = raw_log_name) # where to save the log which will be loaded later
                  )
      else: #note: restoring described here doesn't work: https://docs.ray.io/en/latest/tune/tutorials/tune-stopping.html
          print('--- previous run exist, continue the tuning ----')
          tuner = tune.Tuner.restore(log_dir)

      results = tuner.fit()
      print(results.get_best_result(metric="SCORE", mode="max").config)

### Issue Severity

High: It blocks me from completing my task.

**Comment by wxie2013** [comment]
Thanks @justinvyu for the inputs. I apparently had a misunderstanding of "not finished".

**Comment by wxie2013** [comment]
Hi @justinvyu, here is a follow-up question. The current restore() function can resume the tuning if the status is not "terminated". If the status is "terminated", the restore() function will just print out the finished results.  How should one proceed in the following scenario: 

    -   the 1st run is finished, i.e. with status "terminated" after running 100 samples. 
    -   After a few days, one want to running more samples, e.g. 200 sample, starting from where the 1st run left off so that the final result is equal to run 300 samples in one go.  

restore() function doesn't seem to be able to handle this case.   One can certainly set a "not_finished" mark when the 1st run is finished and continue to the 2nd round.  Is this the only way to resume the tuning?

**Comment by justinvyu** [comment]
Hi @wxie2013,

Currently, the functionality of `Tuner.restore` is only to pick up from where you left off for unfinished trials, as well as giving your the option to restart or resume errored trials.

Adding more samples to the experiment is not currently supported. However, for your scenario, it might make sense to do the following:
1. Start a new Tune experiment with `num_samples=200`.
2. Create the search algorithm, then **load the search algorithm state** from the previous run. See the second code snippet in [this section](https://docs.ray.io/en/latest/tune/api_docs/suggestion.html#saving-and-restoring).

```python
search_alg = HyperOptSearch()
search_alg.restore_from_dir(
  os.path.join(raw_log_dir, raw_log_name))
tuner = Tuner(objective, ..., tune_config=TuneConfig(num_samples=200, search_alg=search_alg))
results = tuner.fit()
```

3. At the end, you'll have 2 different experiments, one with 100 samples, and one with 200 samples, and you would be able to access the results of each experiment with `Tuner.restore(path).get_results()`.

**Comment by wxie2013** [comment]
Thanks @justinvyu for the further inputs. It would be helpful for new users to clarify it in the document. As it is right now, the document gives a impression that  the restore() can continue with a finished run.  I only figured out that this is not the case by looking over the source code comments.

**Comment by justinvyu** [comment]
Re-opening since clarifications have not been upstreamed to the docs yet.
