### ISSUE TITLE
Building Ray from Source

### ISSUE THREAD

**Issue by ksterx** [ray-project/ray#30234]
### What happened + What you expected to happen

Hi,

I tried to build Ray from the source by following the [documentation](https://docs.ray.io/en/latest/ray-contribute/development.html#building-ray).
After forking and cloning Ray repository, I did the following commands:
```bash
conda create -n ray python=3.8
conda activate ray
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
cd ray
python python/ray/setup-dev.py
```
Then I encountered the error↓
```bash
python python/ray/setup-dev.py 
Traceback (most recent call last):
  File "python/ray/setup-dev.py", line 6, in <module>
    import argparse
  File "/home/ksterx/miniconda3/envs/ray/lib/python3.8/argparse.py", line 88, in <module>
    import re as _re
  File "/home/ksterx/miniconda3/envs/ray/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/home/ksterx/miniconda3/envs/ray/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/home/ksterx/Development/PythonProjects/ray/python/ray/types.py", line 1, in <module>
    from typing import Generic, TypeVar
  File "/home/ksterx/miniconda3/envs/ray/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/home/ksterx/miniconda3/envs/ray/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/home/ksterx/Development/PythonProjects/ray/python/ray/types.py)
```

### Versions / Dependencies

conda version: 22.9.0
ray version: 3.0.0.dev0

### Reproduction script

```bash
conda create -n ray python=3.8
conda activate ray
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
cd ray
python python/ray/setup-dev.py
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by hora-anyscale** [comment]
Per Triage Sync: @simon-mo thoughts on this?

**Comment by simon-mo** [comment]
@ksterx this is because you have a file called `types.py` in the directory, this messes up Python's dependency resolution process, and mistaking using your file instead of the standard library's types module.

```
  File "/home/ksterx/Development/PythonProjects/ray/python/ray/types.py", line 1, in <module>
```

renaming your file should help.

**Comment by jaidisido** [comment]
@simon-mo I had the same issue:
```
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/Users/jaidi/Github/ray/python/ray/types.py)
```
What I don't understand is it for us to rename that file? `types.py` is a file that already exists in the Ray repo, we did not add it. So suggesting that we rename it is a bit strange no?

**Comment by simon-mo** [comment]
@jaidisido You raised a valid point. 

@scv119 can you help finding the right person to look into this dev ux issue? Thanks!
