### ISSUE TITLE
[ray.serve] Increasing the num_replicas, the RPS does not change.

### ISSUE THREAD

**Issue by robindume** [ray-project/ray#30246]
I am trying to deploy a image decoder srever (python3.6.9+ cv2 + ray 1.13.0, only use CPU).
I change the "num_replicas" from 1 to 16, but the RPS does not change. My logic CPU number is 80.
The code is like below, it is very simple:
`
@serve.deployment(num_replicas=4, ray_actor_options={"num_cpus": 1, "num_gpus": 0})
class PreprocessHandler():

    def __init__(self, ):
        pass
    
    def preprocess(self, im_byte):
        img = cv2.imdecode(np.asarray(bytearray(im_byte), dtype='uint8'), flags=cv2.IMREAD_COLOR) #bgr
        return img 
    
    async def __call__(self, request):
        im_byte = await request.body()
        img = self.preprocess(im_byte)
        return "successful"

deployment_graph = PreprocessHandler.bind()
`

**Comment by edoakes** [comment]
Stale, reopen if still an issue
