### ISSUE TITLE
[Core] clarify the failure semantics of `was_current_actor_reconstructed` API and improve the implementation

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#30249]
### 1. Background

I'm proposing announcing deprecating `was_current_actor_reconstructed` API, as the reasons:
- It can't show a correct state in some corner cases. 
- It makes too many complications when actor fails in constructor. #13578
- It's not easy to define the state `restarted` in some cases. like, if the constructor was finished, but the reply RPC failed, should it be `restarted` or not?
- If users depend on the API for their failure tolerance of actor, it may make mistake, like
```python
@ray.remote
class My:
    def __init__(self):
        if was_current_actor_reconstructed:
            # failover code path
        else:
           # do initialization. construction code path
```
If it failed before initialization, the initialization can't be executed any longer.

### 2. Best practice to handle actor failure
It's the best practice to handle actor failure that we always check the state via external persist storage, like:
```python
@ray.remote
class My:
    def __init__(self):
        if persist_storage.exists(a_unique_key):
            # failover code path
        else:
           # do initialization  #Note that, you should make initialization be idempotent
           # persist_storage.write(a_unique_key)
```

### 3. Our actions to do
1. Mark the API as `deprecate`
2. Remove it in ray 3.0

**Comment by jovany-wang** [comment]
@rkooo567 @ericl @jjyao CC

**Comment by jovany-wang** [comment]
In distributed practices, most actions should be idempotent and depends on the external persist key to archieve the goal.

**Comment by jjyao** [comment]
@jovany-wang I didn't find `was_current_actor_restarted` in the codebase, what's the exact name of the API?

**Comment by jovany-wang** [comment]
@jjyao https://github.com/ray-project/ray/blob/master/python/ray/runtime_context.py#L222

**Comment by jjyao** [comment]
ok, so the API is `was_current_actor_reconstructed`, could you update the PR description to reflect that?

**Comment by scv119** [comment]
hmm why don't we change the implementation instead.

if we implement `was_current_actor_reconstructed` with `persist_storage.exists(a_unique_key)` and always call ` persist_storage.write(a_unique_key)`; that's identical to your proposed best practice?
```
@ray.remote
class My:
    def __init__(self):
        if persist_storage.exists(a_unique_key):
            # failover code path
        else:
           # do initialization  #Note that, you should make initialization be idempotent
           # persist_storage.write(a_unique_key)
```

**Comment by pcmoritz** [comment]
@scv119 Sounds like a reasonable proposal, if we do this, let's also consider the impact on performance if we always do `persist_storage.write(a_unique_key)` in the constructor :)

**Comment by jovany-wang** [comment]
So if we do this, maybe it's more reasonable to introduce a new state for actor instead of using persist storage.
Once the constructor is created at the first time, a new state `CREATED` should be set(It can be added to the create actor RPC reply, to avoid RPC roundtrip).

```python
def was_current_actor_reconstructed():
    return `CREATED` was set

def MyActor:
    def __init__(self):
        if was_current_actor_reconstructed():
           # failover code path
        else:
            # initialize...
```

**Comment by scv119** [comment]
@jovany-wang yes, the proposed solution sounds reasonable to me.
