### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by EugeneKormin** [ray-project/ray#30250]
### Description

I copied code from doc.ray.io, but i get an error, probably im doing smth wrong. Also it is not clear why tensorflow is used although, pytorch shall be used as per config.

https://colab.research.google.com/drive/1e6v-Kh7AANrLJlvYpbcAqv_t3qmiCQUY#scrollTo=h-C_rVgk8P5p

**Comment by sven1977** [comment]
Hey @EugeneKormin , could you fix the description of your issue as well as provide a concise, self-sufficient reproduction script that we can just copy/paste/run to see the error on our side? Otherwise, we won't be able to debug this and help you. Thanks! :)
