### ISSUE TITLE
ray.put/get doesn't preserve numpy dtypes on single values

### ISSUE THREAD

**Issue by MQQ** [ray-project/ray#3026]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS/Linux
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.3
- **Python version**: 2.7.13
- **Exact command to reproduce**: See below

### Describe the problem
When I use `ray.put` and `ray.get` on a numpy array, it preserves the numpy data types well. But if I try to do put and get on a single numpy.float64 or on a customized data structure that contains single numpy dtype values, I get back native python types. 

Is this behavior expected? Though it doesn't matter much for computation purpose, the implicit conversion may lead to hidden bugs.   

### Source code / logs
```
In [5]: id_ = ray.put(numpy.array([1]))

In [6]: type(ray.get(id_)[0])
Out[6]: numpy.int64

In [7]: id_ = ray.put(numpy.int64(1))

In [8]: type(ray.get(id_))
Out[8]: int

In [9]: id_ = ray.put(numpy.array([1.0]))

In [10]: type(ray.get(id_)[0])
Out[10]: numpy.float64

In [11]: id_ = ray.put(numpy.float64(1.0))

In [12]: type(ray.get(id_))
Out[12]: float

In [13]: id_ = ray.put({'value': numpy.float64(1.0)})

In [14]: type(ray.get(id_)['value'])
Out[14]: float
```

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
