### ISSUE TITLE
[Core] Provide good error message if the factional resource precision is beyond 0.0001

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#30260]
### What happened + What you expected to happen

Sort of an implementation detail: currently the precision of resource requirement is 0.0001.

```
#define RESOURCE_UNIT_SCALING 10000
FixedPoint(double d) { i_ = (int64_t)(d * RESOURCE_UNIT_SCALING); }  // NOLINT
```

To avoid any surprises, we should have a good error message if user provides a double that's beyond the supported precision.

### Versions / Dependencies

master

### Reproduction script

```
f.options(0.0000001).remote()
# ideally this should err
```

**Comment by DmitriGekhtman** [comment]
@jjyao could you add a priority label?
