### ISSUE TITLE
Missing a ')' at the end of the first paragraph of "What type of GPU".

### ISSUE THREAD

**Issue by RangerNJU** [ray-project/ray#30283]
### Description

Missing a ')' at the end of the first paragraph of "What type of GPU".

Checkout using Chrome or Chromium-based Edge: https://docs.ray.io/en/latest/cluster/vms/user-guides/large-cluster-best-practices.html#vms-large-cluster:~:text=leverage%20GPUs%20well)-,What%20type%20of%20GPU%3F,-The%20latest%20gen

### Link

https://docs.ray.io/en/latest/cluster/vms/user-guides/large-cluster-best-practices.html#vms-large-cluster

**Comment by scottsun94** [comment]
@RangerNJU Do want to submit a PR to fix it? It is pretty simple. Just follow [this](https://docs.ray.io/en/latest/ray-contribute/docs.html)

**Comment by angelinalg** [comment]
Created this PR: https://github.com/ray-project/ray/pull/31950
