### ISSUE TITLE
[release] [core] chaos_pipelined_ingestion_1500_gb_15_windows failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30298]
https://buildkite.com/ray-project/release-tests-branch/builds/1196#01847834-c3e0-4b08-933b-92ac4ce4199e

**Comment by clarng** [comment]
Can't repro after 2 re-runs on the failed cluster

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_kYxe81L8d5YUtQpUaUN7vK96?command-history-section=command_history&drivers-section=interactive-sessions

**Comment by xwjiang2010** [comment]
Thanks @clarng ! Feel free to drop the tags if the team thinks it's non-release blocker.

**Comment by clarng** [comment]
Seems flakey, the test is passing again:

https://buildkite.com/ray-project/release-tests-branch/builds/1197#01847d5a-ee4b-475a-90d6-d07abe707ab1

**Comment by iycheng** [comment]
It only failed once. Seems the same to the other chaose tests (https://github.com/ray-project/ray/issues/30424)

Suggest close this one. cc @scv119
