### ISSUE TITLE
[release][rllib] rllib release tests are failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30299]
Global tracker for rllib release tests failures for 2.2.

The majority of learning tests are failing.

Several long running rl tests are failing:
apex, impala.

https://buildkite.com/ray-project/release-tests-branch/builds/1196#01847834-c29d-493e-b456-042b270b5fba

**Comment by kouroshHakha** [comment]
a2c -- still failing, owner: @sven1977 
a3c -- still failing, owner: @kouroshHakha 
appo, ppo, impala -- fix has been made, if infra allows we will run the tests and merge the fix. ✅ 
multi-gpu tests are fixed. ✅ 
The rest are infra failures afaik.

**Comment by xwjiang2010** [comment]
![Screen Shot 2022-11-18 at 8 27 18 AM](https://user-images.githubusercontent.com/87673679/202753512-b9b266ac-4123-4ba2-99b9-f6bea1754af0.png)

Most updated run from yesterday.
Things are getting better. @kouroshHakha could you update when the appo/ppo/impala fixes are landed.

Also just want to be clear, there are also two long running rllib tests are failing consistently:
long_running_apex/impala - will they be fixed as well?

cc @zhe-thoughts

**Comment by xwjiang2010** [comment]
Can this be closed @kouroshHakha ?

**Comment by kouroshHakha** [comment]
This is all green. Closing it now.
