### ISSUE TITLE
[Ray Core] Fail to connect to ray cluster

### ISSUE THREAD

**Issue by maximilianolucius** [ray-project/ray#30292]
### What happened + What you expected to happen

I get the following message when conecting a new node to a local cluster ...

Local node IP: 172.16.0.31
[2022-11-15 07:03:38,731 I 28432 28432] global_state_accessor.cc:357: This node has an IP address of 172.16.0.31, while we can not find the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.

It is a local cluster of Ubuntu 20.04LTS servers (8 nodes), all of them with Python 3.9.15, ray 2.10.

Best,

Max

### Versions / Dependencies

It is a local cluster of Ubuntu 20.04LTS servers (8 nodes), all of them with Python 3.9.15, ray 2.10.

### Reproduction script

1) Start the head with commands ...
source venv/bin/activate
ray start --head

2) Add a node with the commands ...
source venv/bin/activate
ray start --address=172.16.0.121:6739

Then the message appears.

**Comment by iycheng** [comment]
@hora-anyscale are you connecting to a ray cluster from a node not in the cluster?

**Comment by rkooo567** [comment]
Close as stale. Please follow up with the question ^ if the issue still persists.
