### ISSUE TITLE
[rllib][ci] The following rllib tests are failing/very flaky

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30300]
The team to decide whether to fix them or disable them (at least for the 2.2 release branch).

current top 3 are:
test_memory_leak_a3c
test_memory_leak_ppo
learning_tests_stateless_cartpole_r2d2

**Comment by kouroshHakha** [comment]
@xwjiang2010 The memory leak and r2d2 tests have been flakey and are not blockers.

**Comment by sven1977** [comment]
Closing this issue. Currently, the #1 flakey test is batch_norm_model_tf. Tests sometimes also become flakey due to infra reasons. We'll continue monitoring all RLlib CI-tests and continue un-flaking the biggest offenders.
