### ISSUE TITLE
reward during the training process remains .nan in all iterations

### ISSUE THREAD

**Issue by cli0** [ray-project/ray#3030]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip version
- **Ray version**: 0.5.3
- **Python version**: Python 3.6.6

### Describe the problem

I am trying to train a very basic DQN Agent using the Python API code in the documentation as follows:

```
import gym, os, ray
import ray.rllib.agents.dqn as dqn
from ray.tune.logger import pretty_print

ray.init()
config = dqn.DEFAULT_CONFIG.copy()
env = gym.make("myenv-v02")
agent = dqn.DQNAgent(config=config, env="myenv-v02")

for i in range(1000):
   result = agent.train()
   print(pretty_print(result))

   if i % 100 == 0:
       checkpoint = agent.save()
       print("checkpoint saved at", checkpoint)
```

The problem is that in all of the iteration I get:

```
episode_len_mean: .nan
episode_reward_max: .nan
episode_reward_mean: .nan
episode_reward_min: .nan
episodes: 0

```

Reward does not change, it remains nan from beginning to the end.

I test my environment in the following test:

```
import gym

if __name__ == "__main__":

    env = gym.make('myenv-v02')
    env.reset()
    for i_episode in range(2):
        for t in range(2):
            action = env.action_space.sample()
            observation, reward, done, info = env.step(action)
            print(observation)
            print(reward)
```

And I get properly changing values for observation (state) and rewards.

What am I doing wrong with the ray code? Why is my reward nan?

**Comment by ericl** [comment]
Is it possible your environment hasn't terminated yet? Rewards are only reported once an episode completes.

**Comment by bywbilly** [comment]
I have experience the same situation where I just run python3 train.py -f tuned_examples/pong-dqn.yaml, then I found a lot of nan in reward. 

Here is a graph:

![image](https://user-images.githubusercontent.com/10766902/46891698-c4cc1680-ce38-11e8-9cc5-013385dea549.png)

I am still working on fixing it.

**Comment by ericl** [comment]
@bywbilly that's weird that you have `episodes: 0` in your result. Are you on 0.5.3? Since august we have been smoothing all results over the past 100 episodes so that shouldn't happen.

**Comment by ericl** [comment]
i.e., the metrics code returns `episodes_this_iter` now: https://github.com/ray-project/ray/blob/65dcafdc3f916579fbc495fef3de5bcec266cb1c/python/ray/rllib/evaluation/metrics.py#L67

**Comment by raghu1121** [comment]
Any updates on this? I have the same experience. Once in a while i see episodes: 5 and see a reward, otherwise .nan

**Comment by ericl** [comment]
Are you on latest?

**Comment by jamescasbon** [comment]
I'm seeing this too.  Are there any parameters that matter wrt to the number of steps before the episode ends?

**Comment by raghu1121** [comment]
I used  timesteps_per_iteration equal to number of steps in each episode. It worked for me.

**Comment by ericl** [comment]
Thanks for reporting this, the issue was that DQN didn't use the code path with smoothing.

**Comment by mingjunwang88** [comment]
I saw this issue too. my Env did not output did not use done. So I have to make sure at some point to make sure episode output done=True.

**Comment by billyjason** [comment]
setting horizon config does the job, you don't need to change your environment if the episode does not have a terminal state
