### ISSUE TITLE
[release][dataset] ray-data-bulk-ingest-out-of-core-benchmark is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30315]
https://buildkite.com/ray-project/release-tests-branch/builds/1196#01847834-c283-4bc5-b128-dcbe469b0c71

**Comment by xwjiang2010** [comment]
@c21 could you help triage? Thanks!

**Comment by cadedaniel** [comment]
I'll take this! cc @c21

**Comment by cadedaniel** [comment]
Spoke with @stephanie-wang, looks like a failure in test logic (the OutOfDisk error is expected). I will mark as unstable so this isn't release blocking.
