### ISSUE TITLE
[autoscaler][kuberay-ish] `ray status` falsely reports nodes as active when updater threads are disabled

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#30328]
### What happened + What you expected to happen

When updater threads are disabled, `ray status` falsely reports nodes as active before they've connected to the cluster. 

This is mostly relevant to node providers like kuberay or 3rd party node providers which don't use updater threads.

### Versions / Dependencies

master

### Reproduction script

Run a simple script on a machine with an 8 cpu head node and min 0, max 10, 8 cpu workers.

```
import ray
import time

@ray.remote
def foo():
    time.sleep(5 * 60)


ray.get([foo.remote() for _ in range(200)])
```

observe

```
======== Autoscaler status: 2022-11-15 18:20:23.282168 ========
Node status
---------------------------------------------------------------
Healthy:
 10 worker-node-type-0
 1 head-node-type
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 88.0/88.0 CPU
 0.00/542.317 GiB memory
 0.00/102.167 GiB object_store_memory
```

separately, you can try ` len([node for node in ray.nodes() if node["Alive"]])` at the same time and observe it evaluate to `6`. 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by wuisawesome** [comment]
cc @DmitriGekhtman one of use should probably take this on.

**Comment by DmitriGekhtman** [comment]
Cannot confirm this behavior on KubeRay:
```
Healthy:
 1 head-group
Pending:
 10.4.0.11: small-group, waiting
 10.4.0.12: small-group, waiting
 10.4.1.14: small-group, waiting
 10.4.0.13: small-group, waiting
 10.4.1.12: small-group, waiting
 10.4.1.13: small-group, waiting
 10.4.0.14: small-group, waiting
 10.4.0.10: small-group, waiting
 10.4.1.15: small-group, waiting
 10.4.1.11: small-group, waiting
```

**Comment by DmitriGekhtman** [comment]
The issue is likely the terribly confusing contract for determining the status tag in "no updaters mode".

**Comment by DmitriGekhtman** [comment]
The autoscaler does not set tags in "no updaters" mode.
For this reason `provider.node_tags[TAG_RAY_STATUS]` must be calculated by the node provider based on its knowledge of the node's state.
Semantics for the status tag are explained here: https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/batching_node_provider.py#L48
