### ISSUE TITLE
[Tune + Train] AIR Trainers currently get converted to Trainables multiple times unnecessarily

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#30321]
When using Tune with Train (`Tuner(trainer)`), the trainer is currently being converted to a Tune `Trainable` multiple times. This is possibly expensive, since `BaseTrainer.as_trainable` will put all of its config (which could contain a large checkpointed model in `resume_from_checkpoint`) into the object store from a call to `tune.with_parameters`.

In `TunerInternal`, the `Trainer` is converted to a `Trainable` in a few places:
1. `_maybe_warn_resource_contention`
2. `_setup_create_experiment_checkpoint_dir`
3. `fit`

**Comment by Yard1** [comment]
Should we implement some caching here?

**Comment by justinvyu** [comment]
Yep, I have a PR that I'll put up in a bit with this.
