### ISSUE TITLE
[release][serve] serve_single_deployment_1k_noop_replica is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30345]
https://buildkite.com/ray-project/release-tests-branch/builds/1197#01847d5a-ed5b-49cf-8199-7006a936ce97

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_Fu9iLaiiEXRkGBxzP56Q5C2d?command-history-section=command_history

Sample logs
HTTP response body: {"error":{"detail":"Encountered an error while interacting with AWS: \u001b[36mray::_start_from_remote_span()\u001b[39m (pid=4904, ip=10.0.1.87)\n  File \"./backend/server/common/telemetry/ray_tracing/functions.py\", line 173, in _start_from_remote_span\n    return function(*args, **kwargs)\n  File \"./backend/server/api/product/services/session_tasks_service.py\", line 335, in get_execution_log\n    return runner.get_execution_logs(session_command_id, start_line, end_line)\n  File \"/app/product_api_image.binary.runfiles/product/backend/server/session.py\", line 1310, in get_execution_logs\n    Config=TransferConfig(use_threads=False),\n  File \"/app/product_api_image.binary.runfiles/py_deps_boto3/boto3/s3/inject.py\", line 195, in download_file\n    callback=Callback,\n  File \"/app/product_api_image.binary.runfiles/py_deps_boto3/boto3/s3/transfer.py\", line 320, in download_file\n    future.result()\n  File \"/app/product_api_image.binary.runfiles/py_deps_s3transfer/s3transfer/futures.py\", line 103, in result\n    return self._coordinator.result()\n  File \"/app/product_api_image.binary.runfiles/py_deps_s3transfer/s3transfer/futures.py\", line 266, in result\n    raise self._exception\n  File \"/app/product_api_image.binary.runfiles/py_deps_s3transfer/s3transfer/tasks.py\", line 269, in _main\n    self._submit(transfer_future=transfer_future, **kwargs)\n  File \"/app/product_api_image.binary.runfiles/py_deps_s3transfer/s3transfer/download.py\", line 357, in _submit\n    **transfer_future.meta.call_args.extra_args,\n  File \"/app/product_api_image.binary.runfiles/py_deps_botocore/botocore/client.py\", line 508, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/app/product_api_image.binary.runfiles/py_deps_opentelemetry_instrumentation_botocore/opentelemetry/instrumentation/botocore/__init__.py\", line 201, in _patched_api_call\n    raise error\n  File \"/app/product_api_image.binary.runfiles/py_deps_opentelemetry_instrumentation_botocore/opentelemetry/instrumentation/botocore/__init__.py\", line 162, in _patched_api_call\n    result = original_func(*args, **kwargs)\n  File \"/app/product_api_image.binary.runfiles/py_deps_botocore/botocore/client.py\", line 915, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found"}}

**Comment by xwjiang2010** [comment]
@sihanwang41 can you help take a look and see if it is release blocker?

**Comment by xwjiang2010** [comment]
no clue about this test but could be related to recent botoclient throttling issue: https://anyscaleteam.slack.com/archives/CKD613X8S/p1668550119283729

**Comment by sihanwang41** [comment]
Intermitted failures.
