### ISSUE TITLE
[BUG][Object Store] ray.put with argument `_owner` will lost the reference of inner objects

### ISSUE THREAD

**Issue by Catch-Bull** [ray-project/ray#30341]
### What happened + What you expected to happen

In function [HandleAssignObjectOwner](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L3355), inner objects are not borrowed by the outer object's owner, will cause fewer references to inner objects than expected.

proposal: borrow inner objects on function [HandleAssignObjectOwner](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/core_worker.cc#L3355)

Do you have any other better solutions? I will fix this bug within a week

### Versions / Dependencies

ray: master, commit: abeb36ecb882919452e7fcc868bfbe876e6319c2

### Reproduction script

``` python
def test_owner_assign_inner_object(ray_start_regular):
    @ray.remote
    class Owner:
        def warmup(self):
            pass

    owner = Owner.remote()
    ray.get(owner.warmup.remote())

    class OutObject:
        def __init__(self, ref):
            self._ref = ref

    inner_ref = ray.put("test")
    out_ref = ray.put(OutObject(inner_ref), _owner=owner)

    del inner_ref
    time.sleep(10)
    # will raise ray.exceptions.GetTimeoutError
    assert ray.get(ray.get(out_ref)._ref, timeout=5) == "test"
```

**Comment by clarng** [comment]
Seems this is not a regression but an existing bug, hence downgrading to P1
