### ISSUE TITLE
[tune] Custom Loggers

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3034]
Currently, when we run experiments using `run_experiments`, the trial always defines a logger as https://github.com/ray-project/ray/blob/master/python/ray/tune/trial.py#L167.

How can we use customized log creator? For example, one may want to add the hyperparameters into the prefix of the name of the log directory.

**Comment by richardliaw** [comment]
Hm, currently there is no easy way to do this; a similar issue has been raised here: https://github.com/ray-project/ray/issues/2985

I can get to this later this week though; can you give an example for what you mean by adding hyperparameters into the prefix of the log directory?

**Comment by llan-ml** [comment]
For example, when I run the following code:
<pre>
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import ray
import ray.tune as tune
from ray.rllib.models import ModelCatalog
from ray.rllib.models.lstm import LSTM


ray.init()

ModelCatalog.register_custom_model("lstm", LSTM)
config = {
    "gamma": 0.995,
    "lambda": 0.96,
    "kl_coeff": 0.0,
    "entropy_coeff": 0.0,
    "clip_param": 0.2,
    "num_sgd_iter": 30,
    "lr": 5e-5,
    "horizon": 200,
    "sample_batch_size": 3200,
    "train_batch_size": 50000,
    "batch_mode": "complete_episodes",
    "num_envs_per_worker": 16,
    "num_workers": 16,
    "num_cpus_per_worker": 2,
    "simple_optimizer": True,
    "vf_share_layers": True,
    "model": {"custom_model": "lstm",
              "use_lstm": False,
              # "lstm_cell_size": 128,
              "max_seq_len": 64}}

config.update({
    "gamma": tune.grid_search([0.99, 0.995])})

tune.run_experiments({
    "test": {
        "run": "PPO",
        "env": "Ant-v2",
        "stop": {"training_iteration": 1000},
        "config": config
    }
})
</pre>
There will be two folders:
<pre>
(anaconda3-5.2.0) lanlin@DRL-100-104:~$ ls ray_results/test
PPO_Ant-v2_0_gamma=0.99_2018-10-09_18-52-2044u2j6gb  PPO_Ant-v2_1_gamma=0.995_2018-10-09_18-52-20tgcbnqef
</pre>

The information about the parameter `gamma` is added into the names of directories since we use `tune.grid_search` to declare it. For other parameters in `config`, we have to check them in the folders.

In some cases, we maybe need to change some parameters in `config` manually after ran some experiments. Therefore, I'd like to name a folder with some extra parameters, which will be modified potentially, like `PPO_Ant-v2_0_gamma=0.99_lambda=0.96_clip_param=0.2_2018-10-09_18-52-2044u2j6gb`.

**Comment by ericl** [comment]
Btw for manually set params, a trivial grid search will make them appear, e.g., `clip: grid_search([0.2])`.

**Comment by llan-ml** [comment]
I noticed that a trial is always started in the driver worker, so I tried to pass an extra argument `logger` into `Experiment` and just input a customized log creator into `run_experiments` as follows:
<pre>
def logger_creator(spec, tag=0):
    config = spec["config"]
    local_dir = spec["local_dir"]
    upload_dir = spec["upload_dir"]

    if not os.path.exists(local_dir):
        os.makedirs(local_dir)

    names = ["gamma", "lambda", "clip_param", "kl_coeff"]
    custom_str = "_".join(
        ["{}={}".format(name, config[name]) for name in names])
    timestr = datetime.today().strftime("%Y-%m-%d_%H-%M-%S")
    logdir_prefix = "_".join([spec["run"], config["env"], tag, custom_str, timestr])
    logdir = tempfile.mkdtemp(prefix=logdir_prefix, dir=local_dir)
    return UnifiedLogger(config, logdir, upload_dir)

tune.run_experiments({
    "test": {
        "run": "PPO",
        "env": "CartPole-v1",
        "logger": logger_creator,
        "stop": {"training_iteration": 1000},
        "config": config
    }
})
</pre>
In addition, I slightly modified several other files:
<pre>
class Experiment(object):
    def __init__(self, ..., logger=None):
        spec = {..., "logger": logger}

class Trial(object):
    def __init__(self, ..., logger=None):
        ...
        self.result_logger = logger
        self.logdir = logger.logdir if logger else None
        ...

# ray/tune/config_parser.py
def create_trial_from_spec(...):
    if spec["logger"]:
        logger_creator = spec.pop("logger")
        logger = logger_creator(spec, trial_kwargs.get("experiment_tag", 0).split("_")[0])
    else:
        logger = None
    ...
    return Trial(..., logger=logger)

# ray/tune/suggest/variant_generator.py
def _unresolved_values(spec):
    ...
    for k, v in spec.items():
        if k == "logger":
            continue
    ...
</pre>

**Comment by richardliaw** [comment]
@llan-ml, to be clear, is what you want a custom logdir creator, rather than a custom logger?

Specifically, this part: 
https://github.com/ray-project/ray/blob/master/python/ray/tune/trial.py#L180-L182

**Comment by hartikainen** [comment]
Being able to templatize log folder names would be useful for me too. Currently, many of my `grid_search` values include tuples etc., which tend to clutter the log dirs, while I usually only care about the id of the trial.

The interface could be something like this:
```
tune.run_experiments({
    ...,
    'config': {
        'policy_params': {
            'type': 'gaussian',
            'kwargs': {
                'hidden_layer_sizes': (256, 256, 256)},
                ...
            },
         },
        ...
    },
    'log_dir_template': f"custom_directory_{config['policy_params']['kwargs']['hidden_layer_sizes']}"
})
```

The format string obviously requires python 3, but there's probably a way achieve something similar in python 2 as well.
