### ISSUE TITLE
[ml-release] tune scalability single node result throughput flaky

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30370]
https://buildkite.com/ray-project/release-tests-branch/builds/1199#01848282-8bfa-4bfe-ae27-48805a209096

**Comment by xwjiang2010** [comment]
See [dashboard](https://b534fd88.us1a.app.preset.io/superset/dashboard/36/?native_filters_key=vP1wHXjcm3GV51FDYceU3yryVtUuN9d9L76j-UqGurecIKNT1c8ihuI-3up-BT64)

There is very negligible upward shifting over the course of last year but should not be 2.2 release blocking.

**Comment by matthewdeng** [comment]
@xwjiang2010 is this still failign?
