### ISSUE TITLE
ImportError for pyarrow after clean build from source

### ISSUE THREAD

**Issue by pethor** [ray-project/ray#3037]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9.5
- **Ray installed from (source or binary)**: source
- **Ray version**: Oct 6 master @ 2d35a97
- **Python version**: 3.5.3
- **Exact command to reproduce**: import ray

### Describe the problem

The installation of Ray works without problems after installing flex and bison. After issuing `import ray` in the Python shell, I get the following error.

```
>>> import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pethor/temp/ray/python/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/pethor/temp/ray/python/ray/pyarrow_files/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/pethor/temp/ray/python/ray/pyarrow_files/pyarrow/libparquet.so.11: undefined symbol: _ZNK5boost16re_detail_10650131cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
```
I have read #2191 and #2483 but there does not seem to be a solution. This seems to be related to cmake flags for the custom pyarrow build. Any suggestions @robertnishihara or @devin-petersohn?

**Comment by devin-petersohn** [comment]
Does the same thing happen when you install from the [wheels](https://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray)?

**Comment by pethor** [comment]
@devin-petersohn If I use the current wheel version 0.5.3 it works just fine. This issue only appears when building from source.

**Comment by devin-petersohn** [comment]
@pethor No problem! I wanted to see if we could narrow the search space a little.

Before rebuilding Ray, could you try doing a `git clean -f -f -x -d`? It might be an issue with an older Arrow.

Alternatively we could try a fresh clone into a completely different location.

**Comment by pethor** [comment]
@devin-petersohn I've performed a `git clean -f -f -x -d` and pulled the newest version (ef1f2fd), created a clean new virtual environment and still get the same error upon `import ray`. Cloning it into a fresh location with another virtual environment produces the same result.

**Comment by devin-petersohn** [comment]
cc @pcmoritz 

This is the farthest I can help, unfortunately. @pcmoritz is there anything you can think of that would cause or fix this?

**Comment by chuxi** [comment]
@pethor 

It may be caused by different version of python. Do you have any failed build before? And check the directory, `build/external/arrow/src/arrow_ep/python/build` which is the pyarrow setup.py result. There should only contains `lib.xxx` and `temp.xxx` two directories. Make sure clean them before rebuilt. Besides, also the directory `/path/to/ray/python/ray/pyarrow_files/pyarrow`.

The clean work should be done when you run `make clean` under `build` directory. reference from `cmake/Modules/ThirdpartyToolchain.cmake` 

```
  # clean the arrow_ep/python/build/lib.xxxxx directory,
  # or when you build with another python version, it creates multiple lib.xxxx directories
  set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_MAKE_CLEAN_FILES "${ARROW_SOURCE_DIR}/python/build/")
  set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_MAKE_CLEAN_FILES "${CMAKE_SOURCE_DIR}/python/ray/pyarrow_files/pyarrow")
```

If `make clean` does not work, it may be caused by the boost regex lib, from the error info. And you can check your boost build result `build/external/boost-install/lib`, it should contain `libboost_regex.a`.

**Comment by pethor** [comment]
@devin-petersohn Thanks for your suggestions!
@chuxi This is interesting. I have moved to a different machine (same setup, mirrored node, new virtual environment, fresh `git clone`) and now get a different error message when building, maybe I have rebuilt on the same directory. 

```
...
[ 80%] Linking CXX executable ../../release/plasma_store_server
    [ 80%] Built target plasma_store_server
    CMake Error at thrift_ep-stamp/thrift_ep-download-RELEASE.cmake:16 (message):
      Command failed: 1
    
       '/home/pethor/envs/ray2/lib/python3.5/site-packages/cmake/data/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/pethor/temp2/ray/build/external/arrow/src/arrow_ep-build/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-download-RELEASE-impl.cmake'
    
      See also
    
        /home/pethor/temp2/ray/build/external/arrow/src/arrow_ep-build/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-download-*.log
    
    
    CMakeFiles/thrift_ep.dir/build.make:89: recipe for target 'thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-download' failed
    make[5]: *** [thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-download] Error 1
    CMakeFiles/Makefile2:443: recipe for target 'CMakeFiles/thrift_ep.dir/all' failed
    make[4]: *** [CMakeFiles/thrift_ep.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make[3]: *** [all] Error 2
    CMakeFiles/arrow_ep.dir/build.make:110: recipe for target 'external/arrow/src/arrow_ep-stamp/arrow_ep-build' failed
    make[2]: *** [external/arrow/src/arrow_ep-stamp/arrow_ep-build] Error 2
    CMakeFiles/Makefile2:335: recipe for target 'CMakeFiles/arrow_ep.dir/all' failed
    make[1]: *** [CMakeFiles/arrow_ep.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2
...
```
The `thrift_ep-download-out.log` contains
```
-- Downloading...
   dst='/home/students/petschen/temp2/ray/build/external/arrow/src/arrow_ep-build/thrift_ep-prefix/src/thrift-0.11.0.tar.gz'
   timeout='none'
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
-- Retrying...
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz'
```
and the `thrift_ep-download-err.log` contains
```
CMake Error at thrift_ep-stamp/download-thrift_ep.cmake:159 (message):
  Each download failed!

    error: downloading 'http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz' failed
         status_code: 56
         status_string: "Failure when receiving data from the peer"
         log:
         --- LOG BEGIN ---
           Trying 163.172.17.199...

  TCP_NODELAY set

  Connected to archive.apache.org (163.172.17.199) port 80 (#0)

  GET /dist/thrift/0.11.0/thrift-0.11.0.tar.gz HTTP/1.1

  Host: archive.apache.org

  User-Agent: curl/7.60.0

  Accept: */*

  

  Recv failure: Connection reset by peer

  Closing connection 0

  

         --- LOG END ---
```
The machines have access to the internet, manually downloading the desired file `http://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz` with `curl` works just fine.

**Comment by chuxi** [comment]
@pethor  

it is a network problem... In China, we have been used to it.

once the thirft is built, just copy it out and set THRIFT_HOME env variable. So in the build process, it will use local thrift instead of downloading.
referrer to:
https://github.com/ray-project/ray/pull/2963

**Comment by pethor** [comment]
@chuxi I guess it was just a one-of error -- I've built Ray again from scratch; now building works again and I get the same error I originally got (see below). This time, there are definitely no old build artifacts lying around, it is completely fresh. 
```
>>> import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pethor/temp4/ray/python/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/pethor/temp4/ray/python/ray/pyarrow_files/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/pethor/temp4/ray/python/ray/pyarrow_files/pyarrow/libparquet.so.11: undefined symbol: _ZNK5boost16re_detail_10650131cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_

```

> It may be caused by different version of python. 

What do you mean by different version of python? Do I have to use a specific version?

> Do you have any failed build before? And check the directory, `build/external/arrow/src/arrow_ep/python/build` which is the pyarrow setup.py result. There should only contains `lib.xxx` and `temp.xxx` two directories. Make sure clean them before rebuilt. Besides, also the directory `/path/to/ray/python/ray/pyarrow_files/pyarrow`.
> 
> The clean work should be done when you run `make clean` under `build` directory. reference from `cmake/Modules/ThirdpartyToolchain.cmake`

I've used a clean, new version. 

> If `make clean` does not work, it may be caused by the boost regex lib, from the error info. And you can check your boost build result `build/external/boost-install/lib`, it should contain `libboost_regex.a`.

`build/external/boost-install/lib` contains
```
libboost_filesystem.a  libboost_regex.a  libboost_system.a
```
so I guess the build worked. Could it be a linking issue?

**Comment by chuxi** [comment]
@pethor  do you have env variable BOOST_ROOT?  and do you have installed boost version? 

I think your build is succeeded, but can you check the output of cmake in building process? It will show you which dependency version used to build arrow/pyarrow.

It is a linking issue, no symbol found. So it means linked to a wrong boost regex lib version.

**Comment by pethor** [comment]
@chuxi I do not have `BOOST_ROOT` set in my session, but I have boost installed (1.58.0). I think cmake should be able to find boost in its default location. 

The verbose build log contains the following lines regarding boost:

```
...
Added static library dependency glog: /home/pethor/temp5/ray/build/external/glog-install/lib/libglog.a
-- Boost root: /home/pethor/temp5/ray/build/external/boost-install
-- Boost include dir: /home/pethor/temp5/ray/build/external/boost-install/include
-- Boost system library: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a
-- Boost filesystem library: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
Added static library dependency boost_system: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a
Added static library dependency boost_filesystem: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
...
DCMAKE_CXX_FLAGS=-g;-O3; -D_GLIBCXX_USE_CXX11_ABI=0;-DARROW_BUILD_TESTS=off;-DARROW_HDFS=on;-DARROW_BOOST_USE_SHARED=off;-DPYTHON_EXECUTABLE:FILEPATH=/home/pethor/temp5/ray/venv/bin/python3;-DARROW_PYTHON=on;-DARROW_PLASMA=on;-DARROW_TENSORFLOW=on;-DARROW_JEMALLOC=off;-DARROW_WITH_BROTLI=off;-DARROW_WITH_LZ4=off;-DARROW_WITH_ZSTD=off;-DFLATBUFFERS_HOME=/home/pethor/temp5/ray/build/external/flatbuffers-install;-DBOOST_ROOT=/home/pethor/temp5/ray/build/external/boost-install;-DGLOG_HOME=/home/pethor/temp5/ray/build/external/glog-install;-DARROW_WITH_THRIFT=ON;-DARROW_PARQUET=ON;-DARROW_WITH_ZLIB=ON
...
-- Downloading...
   dst='/home/pethor/temp5/ray/build/external/boost/src/boost_1_65_1.tar.gz'
   timeout='none'
...
[ 22%] Performing configure step for 'arrow_ep'
    -- The C compiler identification is GNU 6.3.0
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Arrow version: 0.11.0 (full: '0.11.0-SNAPSHOT')
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
    clang-tidy not found
    clang-format not found
    infer not found
    INFOCompiler command: /usr/bin/c++
    INFOCompiler version: Using built-in specs.
    COLLECT_GCC=/usr/bin/c++
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c
,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexe
cdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug 
--enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enab/home/pethor/temp5/ray/build/external/boost-install/include
    -- Boost libraries: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.a/home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a/home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
    Added static library dependency boost_system: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a
    Added static library dependency boost_filesystem: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
    Added static library dependency boost_regex: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.ale-defau
lt-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-
java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 -
-with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-mul
tilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux
-gnu
    Thread model: posix
    gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

    INFOCompiler id: GNU
    Selected compiler gcc 6.3.0
    -- Performing Test CXX_SUPPORTS_SSE3
    -- Performing Test CXX_SUPPORTS_SSE3 - Success
    -- Performing Test CXX_SUPPORTS_ALTIVEC
    -- Performing Test CXX_SUPPORTS_ALTIVEC - Failed
    Using optional gold linker (version 1.14)
    Configured for RELEASE build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
    -- Build Type: RELEASE
    -- BOOST_VERSION: 1.67.0
    -- BROTLI_VERSION: v0.6.0
    -- DOUBLE_CONVERSION_VERSION: v3.1.1
    -- FLATBUFFERS_VERSION: 02a7807dd8d26f5668ffbbec0360dc107bbfabd5
    -- GBENCHMARK_VERSION: v1.4.1
    -- GFLAGS_VERSION: v2.2.0
    -- GLOG_VERSION: v0.3.5
    -- GRPC_VERSION: 1.14.1
    -- GTEST_VERSION: 1.8.0
    -- JEMALLOC_VERSION: 17c897976c60b0e6e4f4a365c751027244dada7a
    -- LZ4_VERSION: v1.7.5
    -- ORC_VERSION: 1.5.1
    -- PROTOBUF_VERSION: v3.6.1
    -- RAPIDJSON_VERSION: v1.1.0
    -- SNAPPY_VERSION: 1.1.3
    -- THRIFT_VERSION: 0.11.0
    -- ZLIB_VERSION: 1.2.8
    -- ZSTD_VERSION: v1.2.0
    -- Found pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
    -- Boost version: 1.65.1
    -- Found the following Boost libraries:
    --   regex
    --   system
    --   filesystem
    -- Boost include dir: /home/pethor/temp5/ray/build/external/boost-install/include
    -- Boost libraries: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.a/home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a/home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
    Added static library dependency boost_system: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_system.a
    Added static library dependency boost_filesystem: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_filesystem.a
    Added static library dependency boost_regex: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.a
    ...
```
so it should link against the new Ray specific boost library if I interpret the log file correctly. Do you agree?

**Comment by chuxi** [comment]
@pethor 

I think I know the issue

```
    Added static library dependency boost_regex: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.ale-defau

```

it should be `libboost_regex.a`

you can try to add  `libboost_regex.a` in  `BoostExternalProject.cmake`

```
set(Boost_SYSTEM_LIBRARY ${Boost_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}boost_system${CMAKE_STATIC_LIBRARY_SUFFIX})
  set(Boost_FILESYSTEM_LIBRARY ${Boost_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}boost_filesystem${CMAKE_STATIC_LIBRARY_SUFFIX})

# set the regex lib also
```
append it here
```
set(Boost_BUILD_PRODUCTS ${Boost_SYSTEM_LIBRARY} ${Boost_FILESYSTEM_LIBRARY})
``

and finally add to `ExternalProject_Add` `BUILD_BYPRODUCTS`

It is a bug maybe caused by your operating system. You can create a pull request to fix it. Because I have no your environment and can not test it.

**Comment by pethor** [comment]
@chuxi I have performed the changes in `BoostExternalProject.cmake` you suggested and the log line regarding `boost_regex` now looks like this:
```
Added static library dependency boost_regex: /home/students/petschen/temp5/ray/build/external/boost-install/lib/libboost_regex.a
```
I guess you are referencing the line in the excerpt from the log I pasted -- this must be a copy &  paste error on my side, sorry for that. In the original log there is no such thing. 

> I think I know the issue
> 
> ```
>     Added static library dependency boost_regex: /home/pethor/temp5/ray/build/external/boost-install/lib/libboost_regex.ale-defau
> ```
> 
> it should be `libboost_regex.a`

After the changes in the cmake file I still get the same error as before:
```
>>> import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/students/petschen/temp5/ray/python/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
  File "/home/students/petschen/temp5/ray/python/ray/pyarrow_files/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/students/petschen/temp5/ray/python/ray/pyarrow_files/pyarrow/libparquet.so.11: undefined symbol: _ZNK5boost16re_detail_10650131cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
```

**Comment by pethor** [comment]
I have just set up a new virtual machine with the most recent Debian (9.5), installed all dependencies of Ray as required and got the exact same error as above. This means, that it does not build on any recent Debian, not just on my system.

**Comment by chuxi** [comment]
@pethor  I am also confused.

we build it on mac, ubuntu and centos. And recently, the parquet build is included in arrow itself. Here the libparquet has undefined symbol problem which caused by boost regex. 

can you post the build log of pyarrow?

you can use `make -j1` instead of `make -jxxx` in build.sh, which use only one thread to build. It helps a lot for analyze the whole process

**Comment by chuxi** [comment]
Hi @pethor 

I searched the log and find the relative code about boost is `PYARROW_BOOST_USE_SHARED=on`

em...

I suggest you try this, which use static boost lib for pyarrow:

```
    set(pyarrow_ENV
      "PKG_CONFIG_PATH=${ARROW_LIBRARY_DIR}/pkgconfig"
      "PYARROW_WITH_PLASMA=1"
      "PYARROW_WITH_TENSORFLOW=1"
      "PYARROW_BUNDLE_ARROW_CPP=1"
      "PARQUET_HOME=${PARQUET_HOME}"
      "PYARROW_WITH_PARQUET=1"
      "PYARROW_WITH_STATIC_BOOST=1"
      "PYARROW_PARALLEL=")
```

if it still does not work, add more about using static parquet. `PYARROW_WITH_STATIC_PARQUET=1`

**Comment by pethor** [comment]
Hi @chuxi 
Thanks for your suggestion! Adding `"PYARROW_WITH_STATIC_BOOST=1"` in `ThirdpartyToolchain.cmake` solved the issue! Now, one simply has to install `pyarrow` via pip and everything seems to work fine. I guess this is not a solution that is suitable for integration into the master branch; why does Ray build pyarrow from scratch anyway?

**Comment by pethor** [comment]
Hi @chuxi !
Thanks for your suggestions! Adding `"PYARROW_WITH_STATIC_BOOST=1"` to `ThirdpartyToolchain.cmake` solved the issue (in some sense)! Then it is necessary to install `pyarrow` via pip since it is not found otherwise. I guess this is not the intended solution, but it seems to work. Do you think we should create a pull request for this?

**Comment by chuxi** [comment]
@pethor

Great! I think it is a good idea to create a pull request.

I noticed the pyarrow boost before and now I know what problem it causes...
