### ISSUE TITLE
[Core] ray.wait(fetch_local=True) does not prefetch more than num_returns objects

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#30375]
## What happened + What you expected to happen

When you specify `ray.wait(objs, fetch_local=True, num_returns=N)`, the expected behavior is that we send a fetch request for `len(objs)` objects to the raylet. Internally, the raylet persists these fetch requests until the current task finishes or the worker is killed. This enables users to use `ray.wait` repeatedly in a loop to prefetch objects.

However, there is a bug where instead of issuing `len(objs)` fetch requests, we issue `N` requests. This is due to a logic error in `core_worker.cc` that incorrectly skips over objects not in the ready set. The following patch fixes the issue:

```
--- a/src/ray/core_worker/core_worker.cc
+++ b/src/ray/core_worker/core_worker.cc
@@ -1260,20 +1260,11 @@ void RetryObjectInPlasmaErrors(std::shared_ptr<CoreWorkerMemoryStore> &memory_st
   for (auto iter = memory_object_ids.begin(); iter != memory_object_ids.end();) {
     auto current = iter++;
     const auto &mem_id = *current;
-    auto ready_iter = ready.find(mem_id);
-    if (ready_iter != ready.end()) {
-      std::vector<std::shared_ptr<RayObject>> found;
-      RAY_CHECK_OK(memory_store->Get({mem_id},
-                                     /*num_objects=*/1,
-                                     /*timeout=*/0,
-                                     worker_context,
-                                     /*remote_after_get=*/false,
-                                     &found));
-      if (found.size() == 1 && found[0]->IsInPlasmaError()) {
-        plasma_object_ids.insert(mem_id);
-        ready.erase(ready_iter);
-        memory_object_ids.erase(current);
-      }
+    auto found = memory_store->GetIfExists(mem_id);
+    if (found != nullptr && found->IsInPlasmaError()) {
+      plasma_object_ids.insert(mem_id);
+      ready.erase(mem_id);
+      memory_object_ids.erase(current);
     }
   }
 }
```

This is the root cause of https://github.com/ray-project/ray/issues/23983

## Benchmarks

After applying this patch, the wait based prefetch time improved considerably (about on par with the actor prefetcher):

```
Actor prefetcher
------------------
Runs: 15.7s, 14.2s, 17.2s, 10.2s ~= 14.3 seconds mean

Wait prefetcher (old)
------------------
Runs: 23.4s, 18.3s, 19.5s, 19.8s ~= 20.2 seconds mean

Wait prefetcher (after this PR)
------------------
Runs: 11.2s, 12.7s, 17.1s, 12.8s ~= 13.4 seconds mean
```

The script I used was this (run on a two-node cluster):

```
import ray
import time
import numpy as np

# 15GB
ds = ray.data.range_tensor(100000, shape=(80, 80, 3), parallelism=200)
print(ds.size_bytes() / 1e9, "GB")

context = ray.data.context.DatasetContext.get_current()
context.actor_prefetcher_enabled = False

start = time.time()
latencies = []
for _ in ds.iter_batches(batch_size=None, prefetch_blocks=5):
    latencies.append(time.time() - start)
    start = time.time()
    if len(latencies) % 10 == 0:
            print("Latencies (mean/50/90)", np.mean(latencies), np.median(latencies), np.quantile(latencies, 0.9))

print(ds.stats())
```

**Comment by ericl** [comment]
Yes, that's right. The raylet is internally tracking `worker_id -> List[ObjectId]` in DependencyManager, removing the pull request when the object becomes local or the worker is removed. Each call to ray.wait() adds any new refs to that list for the worker.

The only inefficiency I can see here is that the object might get evicted prior to ray.get() on the Python side, but that probably doesn't happen very often in practice.

**Comment by scv119** [comment]
also with the proposed fix, we need to change the ray.wait based refetcher's num_returns >= 2? otherwise it doesn't do the prefetching work.

**Comment by ericl** [comment]
Nope, it should just work as long as you pass in all the references to the wait call, independently of the num_returns setting.

**Comment by cadedaniel** [comment]
I confirmed that Eric's patch appears to fix the issue. See this PR https://github.com/ray-project/ray/pull/30724. Waiting for tests to pass, then will merge + create cherry-pick PR for 2.2.
