### ISSUE TITLE
[Datasets] Should remove actor-based prefetcher after #30375 is addressed

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#30380]
1. Wait for https://github.com/ray-project/ray/issues/30375 to be resolved
2. Disable the actor-based prefetcher and verify performance parity.

**Comment by c21** [comment]
Good win to get rid of actor-based prefetcher.

**Comment by c21** [comment]
@ericl - this cannot catch 2.4 right?

**Comment by ericl** [comment]
This is a identified correctness issue (actor based prefetcher can cause object store memory leaks), so removing it is high priority.

**Comment by ericl** [comment]
> Disable the actor-based prefetcher and verify performance parity.

I think we still have to do this.
