### ISSUE TITLE
Illegal instruction when Tensorflow is installed.

### ISSUE THREAD

**Issue by martisak** [ray-project/ray#3039]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04.5 LTS, Linux ray-master 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**This is a virtual machine in an OpenStack environment.** 

- **Ray installed from (source or binary)**: Source (ray-project/examples, ray-project/deploy images, binary)
- **Ray version**: git, 0.5.3
- **Python version**: Python 3.5.2, 3.5.6, 2.7.15
- **Exact command to reproduce**: `pip install ray tensorflow; python -c "import ray"`

### Describe the problem
When installing Tensorflow via pip (as in the `examples` image), Ray crashes with "Illegal instruction".  This is also true when basing the Docker image on `tensorflow/tensorflow:latest-gpu-py3`.

Trying to reproduce this in a virtual environment was easy.

```
pip install ray
(ray) martisak@ray-master:~/devel/ray$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
[...]
```

and then

```
pip install tensorflow
[...]
(ray) martisak@ray-master:~/devel/ray$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
Illegal instruction (core dumped)
```

I have also reproduced the problem in Docker.

**Using my Docker-image**

```
martisak@ray-master:~$ docker run -it martisak/ray-demo python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
Illegal instruction (core dumped)
```

**Using ray-project/deploy**

```
martisak@ray-master:~/ray$ docker run -it ray-project/deploy python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
```

**Using ray-project/example**
Built using `./build-docker.sh`.

```
martisak@ray-master:~/ray$ docker run -it ray-project/examples python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
Illegal instruction (core dumped)

```
**Using modified ray-project/example**

The examples Dockerfile was modified and the line installing Tensorflow removed.
`RUN pip install gym[atari] opencv-python==3.2.0.8 tensorflow lz4 keras` seems to be the offending line. 

```
martisak@ray-master:~/ray$ docker run -it ray-project/examples python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
```

## Source code / logs

```
(ray) martisak@ray-master:~/devel/ray$ pip freeze | grep "tensorflow\|ray"
ray==0.5.3
tensorflow==1.11.0
```

```
(ray) martisak@ray-master:~/devel/ray$ grep flags /proc/cpuinfo | uniq
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni vmx ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer hypervisor lahf_lm kaiser tpr_shadow vnmi flexpriority ept vpid tsc_adjust arat
```

Note `avx`/`avx2` missing.

Feel free to suggest a way to get better logs :)

Thank you!

**Comment by martisak** [comment]
Seems related? https://github.com/tensorflow/tensorflow/issues/17411
So then probably not an issue related to Ray ...

```
(ray) martisak@ray-master:~/devel/ray$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)
```

**Comment by martisak** [comment]
In case anyone else ends up here - "solved" by downgrading to Tensorflow 1.5. I am not sure if this has any drawbacks. The `hyperopt` example crashed, but other things run nicely.

**Comment by robertnishihara** [comment]
@martisak, thanks for posting this!

Does `import tensorflow` work with Tensorflow 1.11? (1.11 was the one that was failing with Ray, right?)

**Comment by martisak** [comment]
@robertnishihara I was going to apologize for submitting it :p, since it doesn't seem to be related to your project :)

No, Tensorflow 1.11 does not work. I have stepped back one version at the time until it 1.5 which works. This seems to be the latest `pip` version which was compiled without AVX/AVX2 support, so it makes sense that this is the cause.
