### ISSUE TITLE
Improve visibility of API annotations

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30396]
### Description

The developer API annotation isn't discoverable. It's plaintext, and it's easily missed if the docstring is long. 

This is a problem because some users call developer APIs thinking they're intended for end-users.

![image](https://user-images.githubusercontent.com/26107013/202385068-72621330-cd91-4678-980b-59d8ec6e4ef9.png)

**Comment by richardliaw** [comment]
Can we just make the annotation bold? i.e.,

**DeveloperAPI**: This api is a developer API

**Comment by richardliaw** [comment]
I don't think we should move it to the top.

The number of docstrings that are as long as map_batches should be small. Similarly, I generally see "versionadded" to be on the bottom (which has a roughly similar connotation).
