### ISSUE TITLE
[Datasets] Hide `ArrowRow` and `PandasRow` abstractions

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30400]
### Description

If you take items from a dataset, you get `ArrowRow`s or `PandasRow`s.
```
>>> ds = ray.data.range_table(1)
>>> type(ds.take(1)[0])
<class 'ray.data._internal.arrow_block.ArrowRow'>
```

This is bad because it leaks implementation details, like how we use Arrow.

We could hide the implementation details by following the [pimpl pattern](https://en.cppreference.com/w/cpp/language/pimpl).

### Use case

Leaky abstractions are bad.

**Comment by clarkzinzow** [comment]
May want to consolidate this with: https://github.com/ray-project/ray/issues/30402
