### ISSUE TITLE
[Datasets] Unexpected argument error in Jupyter notebooks

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#30405]
### What happened + What you expected to happen

I created a synthetic dataset. I expected to see the dataset representation without errors, but got a `TypeError` instead.

Looks like this was introduced in this PR: https://github.com/ray-project/ray/pull/30039/files#r1018696149.

### Versions / Dependencies

Ray: b0efdb8d9645add54f51aa18cbcf1530dab82791

### Reproduction script

![image](https://user-images.githubusercontent.com/26107013/202393839-59d73d41-a236-4d67-8eaa-cfe6c113f96e.png)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by peytondmurray** [comment]
@bveeramani If it's okay with you, I'll just drop the `stacklevel` kwarg for python < 3.8. We _could_ backport the stacklevel feature, but it would take a bunch of lines of code and probably isn't worth the maintenance effort. As I see it, `3.7` will be reaching end of life in 7 months, and we'll probably want to drop support around them anyway. What do you think?

**Comment by bveeramani** [comment]
@peytondmurray yeah, that totally makes sense to me.
