### ISSUE TITLE
[release][core] chaos_many_tasks_no_object_store is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30424]
https://buildkite.com/ray-project/release-tests-branch/builds/1199#01848282-8ca1-4fd8-9197-80b0492513da

**Comment by xwjiang2010** [comment]
@iycheng @scv119 could you triage as core-oncall? Thanks!

**Comment by iycheng** [comment]
The test only failed once. The log is not enough to check what's happening. I'd think close this one. @scv119 how do you think?
