### ISSUE TITLE
[Datasets] [Release] Ray-date-bulk-ingest-file-size-benchmark timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30447]
https://buildkite.com/ray-project/release-tests-branch/builds/1201#018487a9-0179-47cc-8875-0f6af7d3f629

**Comment by xwjiang2010** [comment]
@cadedaniel could you help triage? Thanks!

**Comment by cadedaniel** [comment]
Same story as the other one -- let's mark as unstable and follow up as a P1.
