### ISSUE TITLE
[Clusters] Specify ray ssh port

### ISSUE THREAD

**Issue by ewzeng** [ray-project/ray#30452]
### Description

`ray up` will hang if I run ssh services behind a port that is not port 22. This is probably because `ray up` uses port 22 to ssh into nodes.

It would be nice if I could specify which port ray uses for ssh.

### Use case

Before running a ray application in the cloud, I would like to test the application locally. To do so, I spin up a docker container (as the head node), bind port 22 of the container to `localhost:22`, and run `ray up`.

However, sometimes I use `localhost:22` for my laptop's ssh services. In this case, I would like to bind port 22 of the container to something like `localhost:1234` (or whatever port I'm not using) and have ray use `localhost:1234` instead.

**Comment by YuhangSong** [comment]
It would be great if I can specify ssh port when using ray up, in the yaml, I have been looking into the code and it does not seem to have such support

**Comment by romilbhardwaj** [comment]
+1 - this is a blocker for my application. My VMs expose SSH on a port different from 22, and there's no way for me to specify the port number to use for SSH. Maybe it should be a field in under `auth` in the [cluster YAML](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml)?

**Comment by jayes97** [comment]
Hi, can anyone provide support or work around to this?

**Comment by jayes97** [comment]
> +1 - this is a blocker for my application. My VMs expose SSH on a port different from 22, and there's no way for me to specify the port number to use for SSH. Maybe it should be a field in under `auth` in the [cluster YAML](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml)?

Here is solution to this https://discuss.ray.io/t/question-how-to-set-ssh-port-for-nodes-in-auto-scaler-yaml/1972/2?u.
Host should have host_ip instead of alias.

**Comment by thiswillbeyourgithub** [comment]
> +1 - this is a blocker for my application. My VMs expose SSH on a port different from 22, and there's no way for me to specify the port number to use for SSH. Maybe it should be a field in under auth in the [cluster YAML](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml)?

Same for me here in 2025. Related to #15225 and #5950 

This seems so weird to me: ray is pretty customizable and well thought out but come one, it is often recommended to change the SSH port to something else than 22. Especially because ray is usually run in situations where you can't easily change that (i.e. part of a laboratory).

Either there is a dumb parameter I'm not seeing in which case it should be explicitly mentioned in the docs, or this simple feature would well be worth the 20 minutes of anyone on the dev team to implement.
