### ISSUE TITLE
[Core] Support retry_exceptions on Actors

### ISSUE THREAD

**Issue by thatcort** [ray-project/ray#30456]
### Description

Ray tasks have the option to retry on user code exceptions by setting `retry_exceptions=True`. Ray actors should have this same option.

### Use case

I was stuck choosing between actors for concurrency control or tasks for retry logic. More context is available here: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1668728093320269

**Comment by rkooo567** [comment]
cc @scv119 maybe we can prioritize for ray 2.3? It's weird we only have this option on tasks

**Comment by alexeykudinkin** [comment]
This has been addressed (at some point):
https://docs.ray.io/en/latest/ray-core/fault_tolerance/actors.html#actor-method-exceptions
