### ISSUE TITLE
Tasks hang after restarting Ray

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#3045]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04, 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.3
- **Python version**: 3.5.2, 3.6.6
- **Exact command to reproduce**:
```python
import ray

@ray.remote
def f():
   return 1

ray.init()
print(ray.get(f.remote()))

ray.shutdown()
ray.init()

print(ray.get(f.remote()))   # Ray hangs here
```

### Describe the problem

Ray hangs when launching tasks after restarting Ray with `ray.shutdown(); ray.init()`. It appears that there's an issue with persisting remote functions/classes because the following code snippet works which re-defines `f()`:
```python
import ray

@ray.remote
def f():
   return 1

ray.init()
print(ray.get(f.remote()))

ray.shutdown()
ray.init()

@ray.remote
def f():
   return 1

print(ray.get(f.remote()))   # Ray does not hang here
```

**Comment by robertnishihara** [comment]
This is a known issue, and I guess we haven't figured out the desired behavior yet. E.g., see https://github.com/ray-project/ray/issues/1798 or https://github.com/ray-project/ray/issues/1970.

**Comment by robertnishihara** [comment]
Closing, to consolidate with #1970.
