### ISSUE TITLE
[CI] `windows://python/ray/tests:test_runtime_env` is failing/flaky on master.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30474]
- 289394e281b76316bdafdf4a8a257271863e3fdf FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1151#0184893c-3db7-4714-9d8a-c8051a484229)
- 23fa7c32023b0b698d24c7b5bc8e5c4d8612476b FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1150#01848931-e652-4089-b612-465851cc9ab8)
- ca00916a7917aa5114a1b5b4981a4001a491008b FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1144#01848845-da0b-4ae4-bf12-d145b46ab375)
- f89986f3031584ae60e3540b6c728f441e6714df FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1140#01848803-5802-4fe1-87f8-028e47c0d2b6)
- 00f00f02ed06dcff3115fa15d4d0ee7ba920b0b9 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1135#0184877b-39af-48da-87d0-bd43a7a91744)
- f0fc8d071c51ac171e1c7a17afbf0a7f19c5db20 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1132#0184873d-176f-46a5-8541-7a2c217cd3cd)
- 14e9826deeab0c5c4142eb09bca4a92efd6694b9 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1125#018486f5-9ec5-4268-b257-4ae8cf9e7fb8)
- 53183ff06af59dca750271884422cac3471517dc FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1124#018486db-af60-4b60-a286-33f595f43515)
- 64131d6dece417f78d0a947166a10e3848172f90 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1121#018486bd-7444-456c-848c-ae383fb2dfc5)
- 6895ae8c73a841bde55b58defa40a0c4a835a98f FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1118#018486aa-8f0d-4c92-96b5-dc63219e6de6)
- 79d12c0756695fb249b84e84d6898f6aa4815712 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1117#01848694-df52-4229-9c63-c25303fcc361)
- c51b0c9a5664e5c6df3d92f9093b56e61b48f514 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1113#018484f8-0ac5-48c1-a906-ec1d7bc76826)
- b0efdb8d9645add54f51aa18cbcf1530dab82791 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1112#0184844f-c3d5-40c0-866a-e394d7bc06ed)
- e80eec9ec3ffc7f7c5df742177037302fd4314ac FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1107#018483ee-fb5e-46b1-bd54-fe1626e8d531)
- d2f250fd888b07baa2de86b68448a289cb68f44e FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1106#018483ed-8799-4e0a-8767-ba02e44d1f09)
- e0fff54d4a95e0b57b7e6a846f6269d84d27ab3a FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1103#018483ba-bc57-4bfb-81f4-d159da4d7104)
- 8802ca39ef66c5651a4b007f00e191f962f724b9 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1100#01848383-a7b5-4204-a485-67f645c40188)
- 3d8c68dbab8cbac5b61eedd4c9d4e37a07eb20b6 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1095#0184830e-8346-4741-a174-dfd441d61d0b)
- 3fbd9a66389fd720cb38da252498b7d485beeedc FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1092#018482d8-3483-4eb7-a7f8-9db4f6e7fdb5)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_runtime_env-END
....

**Comment by xwjiang2010** [comment]
@architkulkarni could you help triage? This test has been pretty flaky recently.

**Comment by rkooo567** [comment]
cc @architkulkarni has this been fixed?

**Comment by xwjiang2010** [comment]
@rkooo567 not fixed, just skipped for now.
