### ISSUE TITLE
ray stop not killing redis

### ISSUE THREAD

**Issue by npyoung** [ray-project/ray#3049]
When stopping and then starting ray on a head node, I get an error:

```Exception: Couldn't start Redis. Check log files```

The last line in the redis logs complains that the port is already in use.

```# Creating Server TCP listening socket *:6379: bind: Address already in use```

 I can verify that redis is still running. Running `pkill redis` stops redis and allows ray to start. Note that when stopping ray, ray reports

```
local_scheduler: no process found
raylet: no process found
raylet_monitor: no process found
```
and proceeds without error.

### Steps to reproduce
- `ray start --head --no-ui --redis-port 6379`
- `ray stop`
- `ray start --head --no-ui --redis-port 6379`

### System information
- Ubuntu 18.04, 16.04, 14.04
- Installed from pip
- Ray version 0.5.3
- Python 3.6

**Comment by robertnishihara** [comment]
Hmm, we're running 

https://github.com/ray-project/ray/blob/6240ccbc6edeafd2e3223be1edb1448f3ea5d0ca/python/ray/scripts/scripts.py#L381-L386

to kill Redis. It should probably be called `redis-server` and not `redis`. Is there some reason that it's different on your machine?

**Comment by npyoung** [comment]
I do see `redis-server` running after running `ray start ...`. After running `ray stop`, `redis-server` keeps running. It gets killed when I run `pkill redis`, and then I'm able to start ray again.

Note this doesn't seem to happen when I start ray with `--use-raylet`

**Comment by npyoung** [comment]
Actually, it also happens when using raylet. If I just start and stop it works, but if I run a few tasks in the middle, I can't start ray after stopping due to `redis-server` running and using the port I want.

**Comment by robertnishihara** [comment]
That's very strange. Not sure what the issue could be.

**Comment by richardliaw** [comment]
Is this reproducible on AWS?

**Comment by npyoung** [comment]
Yes, this is reproducible on AWS and still an issue on 0.6.1.

**Comment by richardliaw** [comment]
Hey, @npyoung, I'm trying to reproduce this on a fresh instance: 

```bash
Installing collected packages: ray
Successfully installed ray-0.6.1
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(tensorflow_p36) ubuntu@ip-172-31-5-118:~$ ray start --head --no-ui --redis-port 6379
WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
Using IP address 172.31.5.118 for this node.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-01-11_21-34-58_8922/logs.
Waiting for redis server at 127.0.0.1:6379 to respond...
Waiting for redis server at 127.0.0.1:30165 to respond...
Starting the Plasma object store with 6.489074892 GB memory using /dev/shm.
{'node_ip_address': '172.31.5.118', 'redis_address': '172.31.5.118:6379', 'object_store_addresses': ['/tmp/ray/session_2019-01-11_21-34-58_8922/sockets/plasma_store'], 'raylet_socket_names': ['/tmp/ray/session_2019-01-11_21-34-58_8922/sockets/raylet'], 'webui_url': ''}

Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 172.31.5.118:6379

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="172.31.5.118:6379")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
(tensorflow_p36) ubuntu@ip-172-31-5-118:~$ ray stop
WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
(tensorflow_p36) ubuntu@ip-172-31-5-118:~$ ray start --head --no-ui --redis-port 6379
WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.

Using IP address 172.31.5.118 for this node.
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-01-11_21-35-09_9098/logs.
Waiting for redis server at 127.0.0.1:6379 to respond...
Waiting for redis server at 127.0.0.1:34704 to respond...
Starting the Plasma object store with 6.489074892 GB memory using /dev/shm.
{'node_ip_address': '172.31.5.118', 'redis_address': '172.31.5.118:6379', 'object_store_addresses': ['/tmp/ray/session_2019-01-11_21-35-09_9098/sockets/plasma_store'], 'raylet_socket_names': ['/tmp/ray/session_2019-01-11_21-35-09_9098/sockets/raylet'], 'webui_url': ''}

Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --redis-address 172.31.5.118:6379

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(redis_address="172.31.5.118:6379")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
```
Anything I'm doing wrong?

**Comment by npyoung** [comment]
That's exactly what I'm doing, but I get an error instead of ray starting the 2nd time! This is also preventing `ray up` from restarting cluster services.

I'm using p3.8xlarge instances with the Deep Learning AMI (ami-3b6bce43). Maybe try on that AMI?

**Comment by npyoung** [comment]
It seems to be related to using an older Deep Learning AMI. I'm not having problems on the Deep Learning version 25 AMI.
