### ISSUE TITLE
[release][core] agent_stress_test is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30494]
https://buildkite.com/ray-project/release-tests-branch/builds/1202#01848cdc-3024-4057-8897-42b1709345c6

**Comment by rkooo567** [comment]
I will handle this. It is because of rllib broken in the master (this test uses rllib under the hood). I will fix it by just not using rllib for this workload.

**Comment by rkooo567** [comment]
PR ^
