### ISSUE TITLE
[release][serve] long_running_serve is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30497]
https://buildkite.com/ray-project/release-tests-branch/builds/1202#01848cdc-2ee2-45a6-bd49-7d7d2951604b

**Comment by sihanwang41** [comment]
closed. since the latest tests passed. https://buildkite.com/ray-project/release-tests-branch/builds/1209#0184a298-d1de-49f4-92c9-5941d29fa570
