### ISSUE TITLE
[RLlib] Environment not returning correct observation (mismatch with env's observation space).

### ISSUE THREAD

**Issue by johnnykre** [ray-project/ray#30521]
### What happened + What you expected to happen

```
/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/worker.py", line 2289, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.sample() (pid=332658, ip=10.0.1.30, repr=<ray.rllib.evaluation.rollout_worker._modify_class.<locals>.Class object at 0x7fa3b031bfd0>)

/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 74, in check_shape
    raise ValueError(
ValueError: Observation ([...] dtype=float32) outside given space (Box(0.0, 1.0, (64,), float32))!
```

### Versions / Dependencies

 OS: Ubuntu 20.04.5 LTS x86_64

Dependencies :
    - ray==2.1.0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.13=haa1d7c7_1
     - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-probability==0.18.0
     - gym==0.23.1

### Reproduction script
```
# config = (
#
#     SACConfig()
#     .environment(
#
#         # Env class to use (here: our gym.Env sub-class from above).
#
#         env=Xhay )
#
#         # Config dict to be passed to our custom env's constructor
       .rollouts(num_rollout_workers=8)
#
#     # Parallelize environment rollouts.
#
#    .rollouts(num_rollout_workers=8)
# )
#
# # Use the config's `build()` method to construct a PPO object.
#
# algo = config.build()
#
#
#
# # Train for n iterations and report results (mean episode rewards).
#
# # Since we have to guess 10 times and the optimal reward is 0.0
#
# # (exact match between observation and action value),
#
# # we can expect to reach an optimal episode reward of 0.0.
#
# print(time.datetime.now()-t0)
#
# print("**********************************")
# for i in range(100):
#
#     results = algo.train()
#
#     print(f"Iter: {i}; avg. reward={results['episode_reward_mean']}")
#     print(time.datetime.now()-t0)
```
### Issue Severity

High: It blocks me from completing my task.

**Comment by johnnykre** [comment]
hi @wuisawesome  thanks for the response , actually was trying to use ray , for training SAC for my custom gym environment , so while doing i was getting some error as shown above i.e 

Errors in between : 
/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/_private/worker.py", line 2289, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RolloutWorker.sample() (pid=332658, ip=10.0.1.30, repr=<ray.rllib.evaluation.rollout_worker._modify_class.<locals>.Class object at 0x7fa3b031bfd0>)

/miniconda3/envs/rllib/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 74, in check_shape
    raise ValueError(
ValueError: Observation ([...] dtype=float32) outside given space (Box(0.0, 1.0, (64,), float32))


**CODE :** 

import gym
import ray
from ray.rllib.algorithms.sac import SACConfig
from xhay_GYM_ENV import  *

# Define your problem using python and openAI's gym API:

class Xhay(gym.Env):

    """Environment in which an agent must learn to repeat the seen observations.



    Observations are float numbers indicating the to-be-repeated values,

    e.g. -1.0, 5.1, or 3.2.



    The action space is always the same as the observation space.



    Rewards are r=-abs(observation - action), for all steps.

    """



    def __init__(self, config):

        # Make the space (for actions and observations) configurable.

        self.action_space = ([-1.0, 1.0 ])

        # Since actions should repeat observations, their spaces must be the

        # same.

        self.observation_space = self.action_space

        self.cur_obs = None

        self.episode_len = 0



    def reset(self):

        """Resets the episode and returns the initial observation of the new one.

        """

        # Reset the episode len.

        self.episode_len = 0

        # Sample a random number from our observation space.

        self.cur_obs = self.observation_space.sample()

        # Return initial observation.

        return self.cur_obs



    def step(self, action):

        """Takes a single step in the episode given `action`



        Returns:

            New observation, reward, done-flag, info-dict (empty).

        """

        # Set `done` flag after 10 steps.

        self.episode_len += 1

        done = self.episode_len >= 10

        # r = -abs(obs - action)

        reward = -sum(abs(self.cur_obs - action))

        # Set a new observation (random sample).

        self.cur_obs = self.observation_space.sample()

        return self.cur_obs, reward, done, {}





config = (

    SACConfig()
    .environment(

    # Env class to use (here: our gym.Env sub-class from above).

    env=Xhay )

    .rollouts(num_rollout_workers=8)

    # Parallelize environment rollouts.
 
)

# Use the config's `build()` method to construct a PPO object.

algo = config.build()



# Train for n iterations and report results (mean episode rewards).

# Since we have to guess 10 times and the optimal reward is 0.0

# (exact match between observation and action value),

# we can expect to reach an optimal episode reward of 0.0.

print(time.datetime.now()-t0)

print("**********************************")
for i in range(100):

    results = algo.train()

    print(f"Iter: {i}; avg. reward={results['episode_reward_mean']}")
    print(time.datetime.now()-t0)

**Comment by sven1977** [comment]
Hey @johnnykre , thanks for filing this issue.

The error indicates that your env is NOT returning a correct observation.

In your env code, I see that you set `self.action_space = ([-1.0, 1.0])`, which is not the correct way of defining a space. You rather have to use a `gym.Space` instance to define your action and observation spaces.

Please refer to the `gym/gymnasium` documentation first.

Also, please post a fully self-contained, self-sufficient reproduction script that we can just copy/paste and run and then verify your reported error. What you have pasted above is not runnable by us.

Thanks :)
