### ISSUE TITLE
[RLlib] How to register a custom policy

### ISSUE THREAD

**Issue by matteobettini** [ray-project/ray#30530]
### Description

PR #27016  Introduced a warning for custom policies, suggesting to register them.

There is no documentation on how to do this. 

How should one register a custom policy?

**Comment by sven1977** [comment]
Hey @matteobettini . I see this comment here from @gjoliver on your question in the PR:

```
return None above.
in this case, we will checkpoint the raw policy class for the user and print a warning message.
I feel like if you want to use custom policy, then you'd better handle compatibility yourself?
```

So we currently do not register custom policies. To explain a little: The registration is there to avoid having to add code into our (pickle-based) checkpoints (i.e. a checkpoint should rather contain the string "APPOTorchPolicy" than the python code `ray.rllib.algorithms.appo.appo_torch_policy::APPOTorchPolicy`). This is done such that checkpoints are more robust against changing the underlying policy code in future versions. However, for custom policies, users should handle this backward compatibility themselves.

I feel the same way as you, though, we should not warn in this case as then, it would always create a warning upon using a custom policy.

**Comment by gjoliver** [comment]
thanks for the really good feedback.
we can also add a simple registration method for custom policies.
that way, users can upgrade their implementation without having pickle issues.
I will take this TODO.
