### ISSUE TITLE
Integration of aim metric tracker as an alternative to tensorboardx in ray tune

### ISSUE THREAD

**Issue by ju2ez** [ray-project/ray#30537]
### Description

I suggest integrating the aim metric tracker to ray tune as an alternative to tensorboardx. 

I already have a working implementation of this inspired by https://github.com/ray-project/ray/blob/master/python/ray/tune/logger/tensorboardx.py and I am already in touch with aim: 
https://github.com/aimhubio/aim/issues/2369

If this feature is considered useful I'm happy to implement it.

### Use case

Tensorboardx has some donwsides to it like poor scalability and having another open source metrics tracker as a possible alternative could be quite valuable.

**Comment by richardliaw** [comment]
@ju2ez that's awesome. I think you could open a pull-request here? cc @krfricke to make the final call.

**Comment by ju2ez** [comment]
> @ju2ez that's awesome. I think you could open a pull-request here? cc @krfricke to make the final call.

@richardliaw , thanks for the reply :) 
Only the test are missing but PR is already out. 

https://github.com/ray-project/ray/pull/30674
