### ISSUE TITLE
[RLlib] PGAgent crashes on attempt to save checkpoint

### ISSUE THREAD

**Issue by marlonjan** [ray-project/ray#3053]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 
- **Ray installed from (source or binary)**: binary (pip)
- **Ray version**: 0.5.3
- **Python version**: 3.6.4
- **Exact command to reproduce**: see below

### Describe the problem

The code below raises a NotImplementedError in ray.tune.trainable.Trainable._save. Replacing "PG" with "PPO" avoids the crash, so it seems PGAgent just doesn't implement the _save method.

### Source code / logs

```python
import ray
import ray.tune as tune
from ray.tune import Experiment


if __name__ == "__main__":
    ray.init()
    tune.run_experiments(
        Experiment(
            name="PG_Crash",
            run="PG",
            stop={"iterations_since_restore": 2},
            checkpoint_at_end=True,
            config={"env": "CartPole-v1"},
        )
    )
```

**Comment by ericl** [comment]
I think this is fixed in https://github.com/ray-project/ray/pull/2982, which will be in the next release.
