### ISSUE TITLE
[CI] `linux://python/ray/tune:test_commands` is failing/flaky on master.

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#30541]
- ddfeae3c86b997e7a0bf1391f37d2831a2da3542 FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1195#01849a2c-4c71-4d3e-ae06-33f0c90a61e8)
- 073e7bc04d989607848552537f9f5ac91fa07d85 FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1194#01849a26-f367-434d-8c81-32cbe16ad16d)
- df76ac7975334a5fec7affcc910076ca435fb772 FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1152#01848b8b-8cf0-4522-a079-fb14d0b365ec)
- 161de0b74a660ab6af3e889c1f465059e7fc6334 FAILED [Buildkite :octopus: Tune tests and examples (small)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1134#0184878d-ca2a-4baa-a811-6ecd72bd5704)

Recently started failing from https://github.com/ray-project/ray/commit/073e7bc04d989607848552537f9f5ac91fa07d85

```
>       assert sum(times) / len(times) < 6.0, "CLI is taking too long!"
--
  | E       AssertionError: CLI is taking too long!
  | E       assert (32.00284552574158 / 5) < 6.0
  | E        +  where 32.00284552574158 = sum([6.6674323081970215, 6.387358903884888, 6.3391945362091064, 6.313596248626709, 6.2952635288238525])
  | E        +  and   5 = len([6.6674323081970215, 6.387358903884888, 6.3391945362091064, 6.313596248626709, 6.2952635288238525])
  |  
  | python/ray/tune/tests/test_commands.py:61: AssertionError


```

<img width="1596" alt="Screen Shot 2022-11-21 at 9 24 30 AM" src="https://user-images.githubusercontent.com/3887863/203120556-c8b34c35-f94a-4a84-87c8-a97fa75e1d8e.png">

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tune:test_commands-END
....

**Comment by xwjiang2010** [comment]
still happening now. will try to take a look this sprint.
