### ISSUE TITLE
[CI] `linux://python/ray/tests:test_output` is failing/flaky on master.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30549]
- 03081998f71fedcc74a7e552aaff412aee79acdc FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1204#01849c02-a52b-4130-983f-b742c6e780e7)
- 03081998f71fedcc74a7e552aaff412aee79acdc FAILED [Buildkite :python: Minimal install 3.9](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1204#01849c02-9d1c-4df7-a1a6-f7fd85179275)
- 03081998f71fedcc74a7e552aaff412aee79acdc FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1204#01849bf3-6032-46ca-80a8-22e0f36fe581)
- 03081998f71fedcc74a7e552aaff412aee79acdc FAILED [Buildkite :python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1204#01849bf3-6038-44ff-97e0-a2885426903d)
- 03081998f71fedcc74a7e552aaff412aee79acdc FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1204#01849c02-9f93-4c7a-9cb3-09623eb7dc92)
- 5fa41327fa69de85424a6b3bec33fda99667f6fc FAILED [Buildkite :python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1203#01849be5-8be9-460d-914d-31722f21c93b)
- 5fa41327fa69de85424a6b3bec33fda99667f6fc FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1203#01849be5-8bde-4bd2-9745-b14d901be902)
- 5fa41327fa69de85424a6b3bec33fda99667f6fc FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1203#01849be5-8be1-4453-8254-e4405aebda37)
- 5fa41327fa69de85424a6b3bec33fda99667f6fc FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1203#01849be5-8be3-43cd-9e85-ce672368ce14)
- 5fa41327fa69de85424a6b3bec33fda99667f6fc FAILED [Buildkite :python: Minimal install 3.9](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1203#01849be5-8be6-4b7b-89b1-9e6598650206)
- 0f246debed7ec8e2e853e8236774410719f0f532 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1202#01849bc2-cc10-4fed-a90c-e47779434988)
- 0f246debed7ec8e2e853e8236774410719f0f532 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1202#01849bc2-cc13-4b37-af7c-e9f3a12802cd)
- 0f246debed7ec8e2e853e8236774410719f0f532 FAILED [Buildkite :python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1202#01849bcb-b807-41d1-88f6-540ad984d58c)
- 0f246debed7ec8e2e853e8236774410719f0f532 FAILED [Buildkite :python: Minimal install 3.9](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1202#01849bcb-b33f-4801-8570-b57c647a50b1)
- 0f246debed7ec8e2e853e8236774410719f0f532 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1202#01849bcb-b591-4df3-9b47-af96d28491ff)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849bc9-d02a-41ea-8aa2-3af30804a977)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :python: Minimal install 3.9](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849bb4-1ab2-4eef-8b6a-388fd77afac0)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849bb4-1aaa-4e16-bbf4-889f3554b9cc)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849bb4-1aad-490d-838a-3a28df85abe6)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849bc9-d103-42aa-aaf1-af7434088019)
- 9db0471c64a9d25a9c9e86a5d902cec0d905237b FAILED [Buildkite :python: Minimal install 3.10](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1178#01848fc0-8f3f-4a5d-bc06-23876a39f7cb)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_output-END
....

**Comment by xwjiang2010** [comment]
suspecting https://github.com/ray-project/ray/pull/29820

cc @wuisawesome

**Comment by wuisawesome** [comment]
Reverted, https://github.com/ray-project/ray/pull/30551

**Comment by xwjiang2010** [comment]
Thanks!
