### ISSUE TITLE
[CI][serve] `linux://python/ray/tests:test_runtime_env_complicated` is failing/flaky on master and 2.2 branch.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30565]
- 988f61c9f32e244d4028843cea10c75a6fa331f7 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1214#01849ca8-e84d-4cf3-8965-c525575d39fc)
- 988f61c9f32e244d4028843cea10c75a6fa331f7 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1214#01849ca8-e850-443b-827a-914577ed7e1a)
- 520fe92cd2dc1d715442dc889d59fdffafd3b1c7 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1213#01849ca3-a454-467b-a648-f21a1f4e627f)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849c90-5525-45b4-b836-b8e4d7f9b8c5)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849cb9-0778-4517-a60e-e79e4e397f6b)
- 29b8640cced93733e5346bd47fae18dd209b6940 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1211#01849cb7-36a9-4e71-9d9e-271ef9794b4f)
- 00d43d39f58f2de7bb7cd963450f7a763b928d10 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1210#01849cae-21c6-4934-8d54-92514d55f1f2)
- f9092dc55e662db00309c4345f744d399a00b9b9 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1209#01849c61-0696-4fd9-9555-6b73d12cde74)
- acff8b6fa615bfe6463fd76660b14ef2bbafda42 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1207#01849c48-9a08-4dfe-9101-cbe6e76f0a10)
- 4671cbf0bf9c2757c5ce267b7db8e6177f66d880 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1206#01849c45-07b6-4f99-a05c-7fafc094606a)
- 4671cbf0bf9c2757c5ce267b7db8e6177f66d880 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1206#01849caf-f9dc-48e7-b8d2-4a482465a61f)
- ba18004dc020a9d85526be599baf519d92bd0e37 FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1205#01849c45-0a8f-4aca-a536-28b4e707a60c)
- 3eaf3beb03cb330122bf8ebce8efa320780da5ce FAILED [Buildkite :ferris_wheel: Post-wheel tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1201#01849c39-8466-46cf-b392-60ded7af6bb4)
- b8b32f3e1b4f878ab784cc331aa595fea483f8b5 FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1200#01849c39-8608-4d35-8a1d-b5d435e45142)
- 3ea03183fbbacd0f538cf6ee333ae4d475915cbf FAILED [Buildkite :python: Minimal install 3.8](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1199#01849c02-99e0-4fc3-aa7b-b6ac7c76aa6e)
- 5f54406c1c271117872061c90a5651834d6b2fb5 FAILED [Buildkite :python: Minimal install 3.7](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1197#01849bd6-0917-4d11-b727-f513497e6921)
- 26318068fe7fa153bf09dd8cee7b3a0b092883b7 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1122#018486d3-e28e-4ac2-8a42-21c25a04aba8)
- 64131d6dece417f78d0a947166a10e3848172f90 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1121#01848730-9a51-4290-a67d-97ffa6d242e7)
- 973a6eecafaa8722fc9cd5bdeae671b67648dfd4 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1119#018486b4-5fb5-4f77-a793-c50869422ddb)
- 87b821cc7567f284afbe0420ae152b488a352086 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1116#01848617-cba7-42ed-8058-aaae69c1eae4)
- ab60fa496453cadba051a036d27fd9d640b4c093 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1115#018485e1-df17-43d5-82cb-98864cf18b05)
- d59f189540b14269f49d976ba60e97b804f011ba FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1114#01848546-05ba-46b2-b7e9-e19d20af0864)
- c51b0c9a5664e5c6df3d92f9093b56e61b48f514 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1113#0184850c-1135-4776-9bca-c472f4eb4113)
- b0efdb8d9645add54f51aa18cbcf1530dab82791 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1112#01848458-3783-488b-8d9b-fc6c790978f6)
- 177cb44febe9056dc8465577bb34ad5192eb3f47 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1111#0184844d-b5f6-45ab-bbfa-459dfb8f57e7)
- c7115135ea131b29bd6ff3d32e4f90297e5e770e FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1110#01848416-041e-4fc4-87cd-eabbe113c11b)
- aa49c7a01b0877e6305c8c1423aded4abaf6f5d5 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1109#01848406-dbae-49b7-abdf-9f4e31ab52c7)
- 326da4664da68b184484a8b317c73dd0cb168f23 FAILED [Buildkite :python: Minimal install 3.6](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1108#01848400-d560-491f-b867-b17c07752429)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_runtime_env_complicated-END
....

**Comment by xwjiang2010** [comment]
```


(raylet)   File "/ray/python/ray/_private/workers/default_worker.py", line 8, in <module>
--
  | (raylet)     import ray
  | (raylet)   File "/ray/python/ray/__init__.py", line 163, in <module>
  | (raylet)     from ray import autoscaler  # noqa: E402,F401
  | (raylet)   File "/ray/python/ray/autoscaler/__init__.py", line 1, in <module>
  | (raylet)     from ray.autoscaler import sdk
  | (raylet)   File "/ray/python/ray/autoscaler/sdk/__init__.py", line 1, in <module>
  | (raylet)     from ray.autoscaler.sdk.sdk import (
  | (raylet)   File "/ray/python/ray/autoscaler/sdk/sdk.py", line 9, in <module>
  | (raylet)     from ray.autoscaler._private import commands
  | (raylet)   File "/ray/python/ray/autoscaler/_private/commands.py", line 23, in <module>
  | (raylet)     from ray.autoscaler._private.autoscaler import AutoscalerSummary
  | (raylet)   File "/ray/python/ray/autoscaler/_private/autoscaler.py", line 16, in <module>
  | (raylet)     from six.moves import queue
  | (raylet) ModuleNotFoundError: No module named 'six'


```

**Comment by xwjiang2010** [comment]
not sure which PR is correlated. Could be a dependency change. I will take a look tmr first.

**Comment by xwjiang2010** [comment]
checked with repro-ci but the test is passing there. @sihanwang41 could you take a look on this one as well? 
The failure seems pretty extensive. It's also showing up on release branch with
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f93-1b4d-4001-b496-29e7a23bafc3 (mac wheels and jars)
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849fa8-c73f-4d13-a204-d177afb6e8e0 (mac large)
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f9b-f00b-451a-b582-282982e645cd (linux post-wheel test)
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f9b-f00b-451a-b582-282982e645cd (minimal install 3.7)
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f9b-f00e-4db1-a453-fa2c5476875f (minimal install 3.8)

**Comment by xwjiang2010** [comment]
Rerun on release branch and seems to have recovered:
<img width="1172" alt="Screen Shot 2022-11-22 at 3 35 41 PM" src="https://user-images.githubusercontent.com/87673679/203442386-2db8f1e4-bf22-4cec-9f98-b5d624ff3e90.png">

https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#0184a151-b1a6-4d45-8201-926c51c7044d

Master also has recovered. Feels like some dependency is fixed externally. Will close out the bug for now.

**Comment by xwjiang2010** [comment]
Start to show up consistently on release branch again. And I guess the same for master. Still suspecting some external dependency change.

Links to CI on release branch: https://buildkite.com/ray-project/oss-ci-build-branch/builds?branch=releases%2F2.2.0

Tests that are affected: Linux post-wheel, Minimal Install 3.7/3.8. 

Can we do another round of sanity check and sign off for release?

**Comment by architkulkarni** [comment]
Summary of the issue:

Runtime env allows you to specify an existing conda environment for the Ray workers to use.  In the test for this, we set up a conda environment.  That conda environment needs to have Ray installed, so we install all of Ray's `"ray[default]"` dependencies.

Due to some unknown change in the dependency tree, the `pip install` of Ray's dependencies now takes forever (20+ minutes) due to [backtracking](https://pip.pypa.io/en/stable/topics/dependency-resolution/#backtracking). Here's the [partial sample output of that command.](https://gist.github.com/architkulkarni/2fb12a58c1a8da3eeafdab3bfd6d805d)

Since this was passing on the release branch and master until recently, I would say this failure is not a release blocker (though it's still P0 for me to find a way to fix it to unbreak the master CI).  

Two potential concerns:
- By saying it's not a release blocker and ignoring this test, we're trusting that none of the most recent cherry picks affect `runtime_env` `conda` feature.  I think this a valid assumption.
- Is it possible that due to the unknown dependency change, any user running `pip install "ray[default]"` will also experience 20+ minute install times for the same reason?  If so, that may be a release blocker in and of itself (independent of `runtime_env`), cc @xwjiang2010 .  I will test this manually.

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/34650
<img width="694" alt="Screenshot 2023-04-21 at 9 39 30 AM" src="https://user-images.githubusercontent.com/5459654/233689713-6ece51b8-1687-427e-82ac-411b5b81ae5c.png">
