### ISSUE TITLE
[RLlib] Official case failed in kaggle for lateset version.

### ISSUE THREAD

**Issue by adiyaDalat** [ray-project/ray#30568]
### What happened + What you expected to happen

Failed when running official getting start example from RLlib doc in kaggle.

Examples were the Taxi-v3 and SimpleCorridor in following page:
https://docs.ray.io/en/latest/rllib/index.html
https://docs.ray.io/en/master/ray-overview/index.html

### Versions / Dependencies

Latest version  using default lib of ray(2.0.0) in kaggle.

### Reproduction script

Copy directly from Taxi-v3 and SimpleCorridor examples in following page:
https://docs.ray.io/en/latest/rllib/index.html
https://docs.ray.io/en/master/ray-overview/index.html

**Error info as below:**

`
2022-11-22 04:02:04,944	WARNING ppo.py:359 -- `train_batch_size` (4000) cannot be achieved with your other settings (num_workers=3 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 1334.
(RolloutWorker pid=2175) /opt/conda/lib/python3.7/site-packages/gym/spaces/box.py:227: UserWarning: WARN: Casting input x to numpy array.
(RolloutWorker pid=2175)   logger.warn("Casting input x to numpy array.")
(RolloutWorker pid=2175) 2022-11-22 04:02:58,485	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2175, ip=172.19.2.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f64160b3c50>)
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 617, in __init__
(RolloutWorker pid=2175)     seed=seed,
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1790, in _build_policy_map
(RolloutWorker pid=2175)     merged_conf,
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 131, in create_policy
(RolloutWorker pid=2175)     self.seed,
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/policy.py", line 72, in create_policy_for_framework
(RolloutWorker pid=2175)     observation_space, action_space, merged_config
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo_tf_policy.py", line 102, in __init__
(RolloutWorker pid=2175)     self.maybe_initialize_optimizer_and_loss()
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 670, in maybe_initialize_optimizer_and_loss
(RolloutWorker pid=2175)     self._initialize_loss_from_dummy_batch(auto_remove_unneeded_view_reqs=True)
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 715, in _initialize_loss_from_dummy_batch
(RolloutWorker pid=2175)     -1.0, 1.0, shape=value.shape[1:], dtype=value.dtype.name
(RolloutWorker pid=2175)   File "/opt/conda/lib/python3.7/site-packages/gym/spaces/box.py", line 90, in __init__
(RolloutWorker pid=2175)     ), f"Expect all shape elements to be an integer, actual type: {tuple(type(dim) for dim in shape)}"
(RolloutWorker pid=2175) AssertionError: Expect all shape elements to be an integer, actual type: (<class 'tensorflow.python.framework.tensor_shape.Dimension'>,)

AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_27/1284837367.py in <module>
     61 )
     62 # Construct the actual (PPO) algorithm object from the config.
---> 63 algo = config.build()
     64 
     65 # Train for n iterations and report results (mean episode rewards).

/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm_config.py in build(self, env, logger_creator)
    308             config=self.to_dict(),
    309             env=self.env,
--> 310             logger_creator=self.logger_creator,
    311         )
    312 

/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py in __init__(self, config, env, logger_creator, **kwargs)
    306         }
    307 
--> 308         super().__init__(config=config, logger_creator=logger_creator, **kwargs)
    309 
    310         # Check, whether `training_iteration` is still a tune.Trainable property

/opt/conda/lib/python3.7/site-packages/ray/tune/trainable/trainable.py in __init__(self, config, logger_creator, remote_checkpoint_dir, custom_syncer)
    155         start_time = time.time()
    156         self._local_ip = self.get_current_ip()
--> 157         self.setup(copy.deepcopy(self.config))
    158         setup_time = time.time() - start_time
    159         if setup_time > SETUP_TIME_THRESHOLD:

/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py in setup(self, config)
    441                     # - e.args[0].args[2]: The original Exception (e.g. a ValueError due
    442                     # to a config mismatch) thrown inside the actor.
--> 443                     raise e.args[0].args[2]
    444                 # In any other case, raise the RayActorError as-is.
    445                 else:

python/ray/_raylet.pyx in ray._raylet.execute_task()

python/ray/_raylet.pyx in ray._raylet.execute_task()

python/ray/_raylet.pyx in ray._raylet.execute_task()

python/ray/_raylet.pyx in ray._raylet.execute_task()

python/ray/_raylet.pyx in ray._raylet.execute_task.function_executor()

/opt/conda/lib/python3.7/site-packages/ray/_private/function_manager.py in actor_method_executor()
    672                 return method(*args, **kwargs)
    673             else:
--> 674                 return method(__ray_actor, *args, **kwargs)
    675 
    676         # Set method_name and method as attributes to the executor closure

/opt/conda/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py in _resume_span()
    464             # If tracing feature flag is not on, perform a no-op
    465             if not _is_tracing_enabled() or _ray_trace_ctx is None:
--> 466                 return method(self, *_args, **_kwargs)
    467 
    468             tracer: _opentelemetry.trace.Tracer = _opentelemetry.trace.get_tracer(

/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py in __init__()
    615             policy_config,
    616             session_creator=tf_session_creator,
--> 617             seed=seed,
    618         )
    619 

/opt/conda/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py in _resume_span()
    464             # If tracing feature flag is not on, perform a no-op
    465             if not _is_tracing_enabled() or _ray_trace_ctx is None:
--> 466                 return method(self, *_args, **_kwargs)
    467 
    468             tracer: _opentelemetry.trace.Tracer = _opentelemetry.trace.get_tracer(

/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py in _build_policy_map()
   1788                 policy_spec.action_space,
   1789                 policy_spec.config,  # overrides.
-> 1790                 merged_conf,
   1791             )
   1792 

/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py in create_policy()
    129             self.worker_index,
    130             self.session_creator,
--> 131             self.seed,
    132         )
    133 

/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/policy.py in create_policy_for_framework()
     70                     with tf1.variable_scope(var_scope):
     71                         return policy_class(
---> 72                             observation_space, action_space, merged_config
     73                         )
     74         # For tf-eager: no graph, no session.

/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo_tf_policy.py in __init__()
    100             # Note: this is a bit ugly, but loss and optimizer initialization must
    101             # happen after all the MixIns are initialized.
--> 102             self.maybe_initialize_optimizer_and_loss()
    103 
    104         @override(base)

/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py in maybe_initialize_optimizer_and_loss()
    668         # Loss initialization and model/postprocessing test calls.
    669         self._init_optimizers()
--> 670         self._initialize_loss_from_dummy_batch(auto_remove_unneeded_view_reqs=True)
    671 
    672         # Create MultiGPUTowerStacks, if we have at least one actual

/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py in _initialize_loss_from_dummy_batch()
    713                 self.view_requirements[key] = ViewRequirement(
    714                     space=gym.spaces.Box(
--> 715                         -1.0, 1.0, shape=value.shape[1:], dtype=value.dtype.name
    716                     ),
    717                     used_for_compute_actions=False,

/opt/conda/lib/python3.7/site-packages/gym/spaces/box.py in __init__()
     88             assert all(
     89                 np.issubdtype(type(dim), np.integer) for dim in shape
---> 90             ), f"Expect all shape elements to be an integer, actual type: {tuple(type(dim) for dim in shape)}"
     91             shape = tuple(int(dim) for dim in shape)  # This changes any np types to int
     92         elif isinstance(low, np.ndarray):

AssertionError: Expect all shape elements to be an integer, actual type: (<class 'tensorflow.python.framework.tensor_shape.Dimension'>,)
(RolloutWorker pid=2174) 2022-11-22 04:03:01,826	WARNING env.py:143 -- Your env doesn't have a .spec.max_episode_steps attribute. This is fine if you have set 'horizon' in your config dictionary, or `soft_horizon`. However, if you haven't, 'horizon' will default to infinity, and your environment will not be reset.
(RolloutWorker pid=2174) /opt/conda/lib/python3.7/site-packages/gym/spaces/box.py:227: UserWarning: WARN: Casting input x to numpy array.
(RolloutWorker pid=2174)   logger.warn("Casting input x to numpy array.")
(RolloutWorker pid=2177) /opt/conda/lib/python3.7/site-packages/gym/spaces/box.py:227: UserWarning: WARN: Casting input x to numpy array.
(RolloutWorker pid=2177)   logger.warn("Casting input x to numpy array.")
(RolloutWorker pid=2174) 2022-11-22 04:03:02,035	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2174, ip=172.19.2.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f1603eb4cd0>)
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 617, in __init__
(RolloutWorker pid=2174)     seed=seed,
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1790, in _build_policy_map
(RolloutWorker pid=2174)     merged_conf,
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 131, in create_policy
(RolloutWorker pid=2174)     self.seed,
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/policy.py", line 72, in create_policy_for_framework
(RolloutWorker pid=2174)     observation_space, action_space, merged_config
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo_tf_policy.py", line 102, in __init__
(RolloutWorker pid=2174)     self.maybe_initialize_optimizer_and_loss()
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 670, in maybe_initialize_optimizer_and_loss
(RolloutWorker pid=2174)     self._initialize_loss_from_dummy_batch(auto_remove_unneeded_view_reqs=True)
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 715, in _initialize_loss_from_dummy_batch
(RolloutWorker pid=2174)     -1.0, 1.0, shape=value.shape[1:], dtype=value.dtype.name
(RolloutWorker pid=2174)   File "/opt/conda/lib/python3.7/site-packages/gym/spaces/box.py", line 90, in __init__
(RolloutWorker pid=2174)     ), f"Expect all shape elements to be an integer, actual type: {tuple(type(dim) for dim in shape)}"
(RolloutWorker pid=2174) AssertionError: Expect all shape elements to be an integer, actual type: (<class 'tensorflow.python.framework.tensor_shape.Dimension'>,)
(RolloutWorker pid=2177) 2022-11-22 04:03:02,075	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=2177, ip=172.19.2.2, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f0bbe5b5910>)
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 617, in __init__
(RolloutWorker pid=2177)     seed=seed,
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1790, in _build_policy_map
(RolloutWorker pid=2177)     merged_conf,
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/policy_map.py", line 131, in create_policy
(RolloutWorker pid=2177)     self.seed,
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/utils/policy.py", line 72, in create_policy_for_framework
(RolloutWorker pid=2177)     observation_space, action_space, merged_config
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/ppo/ppo_tf_policy.py", line 102, in __init__
(RolloutWorker pid=2177)     self.maybe_initialize_optimizer_and_loss()
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 670, in maybe_initialize_optimizer_and_loss
(RolloutWorker pid=2177)     self._initialize_loss_from_dummy_batch(auto_remove_unneeded_view_reqs=True)
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy_v2.py", line 715, in _initialize_loss_from_dummy_batch
(RolloutWorker pid=2177)     -1.0, 1.0, shape=value.shape[1:], dtype=value.dtype.name
(RolloutWorker pid=2177)   File "/opt/conda/lib/python3.7/site-packages/gym/spaces/box.py", line 90, in __init__
(RolloutWorker pid=2177)     ), f"Expect all shape elements to be an integer, actual type: {tuple(type(dim) for dim in shape)}"
(RolloutWorker pid=2177) AssertionError: Expect all shape elements to be an integer, actual type: (<class 'tensorflow.python.framework.tensor_shape.Dimension'>,)

`

### Issue Severity

High: It blocks me from completing my task.

**Comment by adiyaDalat** [comment]
Is new version(2.0.0+) of RLlib not compatible with Kaggle?

Seems that old version do not have this issue.

**Comment by sven1977** [comment]
Which Kaggle notebook did you use? And which initial install commands did you run before you copy/pasted the script and saw the above error?

**Comment by adiyaDalat** [comment]
> 

Thank you for your reply! 

I just created a new notebook, used Kaggle original environment/packages and run the official example. Showed as the link below:

https://www.kaggle.com/ady5215758/rllib-test
