### ISSUE TITLE
[CI][core] `bk://:serverless: Dashboard Tests` is failing/flaky on master.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30564]
- 6142f52ada995b7123ea7347a70613ca7b924e0c FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1217#01849caf-da0e-4025-8e17-11ff45576c27)
- e588e17023a87c4e37d0a154989698189cc0374f FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1216#01849cdd-ee24-4d6a-85da-ee0f7b478a8b)
- 00d43d39f58f2de7bb7cd963450f7a763b928d10 FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1210#01849cdd-d973-44b0-ac7b-af203b413918)
- 14e9826deeab0c5c4142eb09bca4a92efd6694b9 FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1125#0184873f-d095-42b7-baaa-4c77fcbcc8e7)
- 64131d6dece417f78d0a947166a10e3848172f90 FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1121#01848708-4f67-45a9-88a1-33ff2319f73d)
- aa49c7a01b0877e6305c8c1423aded4abaf6f5d5 FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1109#01848406-dba0-4f24-acea-49efb5eb32e9)
- 326da4664da68b184484a8b317c73dd0cb168f23 FAILED [:serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1108#01848400-d553-44b3-ae80-16b6dd646143)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:serverless: Dashboard Tests-END
....

**Comment by xwjiang2010** [comment]
```
console.error
--
  | Material-UI: the createMuiTheme function was renamed to createTheme.
  |  
  | You should use `import { createTheme } from '@material-ui/core/styles'`
```

**Comment by xwjiang2010** [comment]
Same signature of failure in release branch:
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f9b-effa-4fde-aabf-5d69367364d0

**Comment by clarng** [comment]
Trying a fix 

https://buildkite.com/ray-project/oss-ci-build-pr/builds/6117

**Comment by clarng** [comment]
looks green now

<img width="1504" alt="Screen Shot 2022-11-28 at 2 23 23 AM" src="https://user-images.githubusercontent.com/22830327/204387803-12c40b7a-9fb2-4d59-91ea-4a0dbecaae71.png">
