### ISSUE TITLE
[ci][runtime] test_runtime_env_working_dir is timing out on 2.2.0

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30589]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f93-1b5a-46fb-b5a4-9fa381351d6c

**Comment by xwjiang2010** [comment]
cc @zhe-thoughts @scv119 Could we find an owner for runtime related bugs? Archit is OOO this week.

**Comment by zhe-thoughts** [comment]
@architkulkarni @edoakes Could you take a look at this release blocker? Thanks!

**Comment by sihanwang41** [comment]
closed. Intermitted issue. (not reproducible)
