### ISSUE TITLE
[Test] test_cli.py still broken 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#30585]
### What happened + What you expected to happen

<img width="560" alt="Screen Shot 2022-11-22 at 8 15 23 AM" src="https://user-images.githubusercontent.com/18510752/203365298-4229a424-6427-470a-b731-637595140090.png">

Failed by different reasons

### Versions / Dependencies

/

### Reproduction script

/

**Comment by xwjiang2010** [comment]
still failing on release branch:

https://buildkite.com/ray-project/oss-ci-build-branch/builds/1231#01849f9b-f030-4a26-aa48-de511ad2fa80

```


assert not worker_proc.is_alive(), "worker node is not killed."
--
  | E       AssertionError: worker node is not killed.
  | E       assert not True
  | E        +  where True = <bound method BaseProcess.is_alive of <Process(Process-3, started)>>()
  | E        +    where <bound method BaseProcess.is_alive of <Process(Process-3, started)>> = <Process(Process-3, started)>.is_alive


```

**Comment by rkooo567** [comment]
This is not a release blocker. The test is flaky because of race condition that happens because GCS exits earlier than other components sometimes. I found adding time.sleep relieves the flakiness. I am trying to kill gcs after every other components are killed and see if that can fully fix the flakiness, but the issue doesn't have to be a release blocker (I assume this issue exists for a long time. )

**Comment by xwjiang2010** [comment]
@rkooo567 `test_cli` is now failing with a different signature: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1285#0184b9e8-e7cc-4814-b655-6008427369c3

Can you take another look and confirm that it's not release blocker?

**Comment by rkooo567** [comment]
Yeah it is the same type of issue. It doesn't have to be a release blocker. FYI, the issue will be fixed by this PR https://github.com/ray-project/ray/pull/30672 (need to still check why the test is still failing.. when I ran it myself, it passes 50 times in a row)

**Comment by rkooo567** [comment]
Should be fixed in the master. I will re
