### ISSUE TITLE
[RLlib]  custom_env example does not work

### ISSUE THREAD

**Issue by kunterbunt** [ray-project/ray#30582]
### What happened + What you expected to happen

Executing [the example script](https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py) throws the following error:

```
Running with following CLI options: Namespace(as_test=False, framework='tf2', local_mode=False, no_tune=False, run='PPO', stop_iters=50, stop_reward=0.1, stop_timesteps=100000)
2022-11-22 13:26:57,570 INFO worker.py:1528 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/home/seba/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/seba/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<path>/test_drl_custom_policy.py", line 161, in <module>
    get_trainable_cls(args.run)
AttributeError: 'dict' object has no attribute 'environment'
```

I tried both `tf` and `tf2`.

### Versions / Dependencies

- `tensorflow 2.11.0`
- `ray 2.1.0`
- `Python 3.8.12`
- `Linux manjaro 5.15.76-1-MANJARO #1 SMP PREEMPT Sat Oct 29 14:22:16 UTC 2022 x86_64 GNU/Linux`

### Reproduction script

Exactly [this script](https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py)

### Issue Severity

High: It blocks me from completing my task.

**Comment by anatolii-kotov** [comment]
I have the same issue on Mac OS 13.0.1 with Python 3.9.15, Pytorch and Ray 2.1.0

**Comment by signalprime** [comment]
Every time I come to try RLlib I'm met with an endless list of issues like this one which I just found.  What is the most recent stable version where things work with the examples?

**Comment by sven1977** [comment]
Seems to be resolved. Thanks for filing this issue and your answers @kunterbunt , @anatolii-kotov , and @signalprime !

**Comment by kunterbunt** [comment]
> Seems to be resolved. Thanks for filing this issue and your answers @kunterbunt , @anatolii-kotov , and @signalprime !

Shouldn't the example code be fixed before the issue is closed? Yes, the fix works, but should everyone who looks into your tutorials and demo code stumble upon this error, dig up this issue, find the reference to another issue, and manually apply the fix?

**Comment by amanarora28** [comment]
I am getting this error while running custom env form examples. 
Please help me resolve.
ValueError: Env must be of one of the following supported types: BaseEnv, gym.Env, MultiAgentEnv, VectorEnv, RemoteBaseEnv, ExternalMultiAgentEnv, ExternalEnv, but instead is of type <class '__main__.SimpleCorridor'>.
