### ISSUE TITLE
[release][rllib] appo learning test is failing on release branch

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30617]
See

https://buildkite.com/ray-project/release-tests-branch/builds/1209#0184a298-d20c-4655-8711-dd18335c9aa2

**Comment by xwjiang2010** [comment]
reward is just a little bit off:

```
Analyzing experiment appo-pongnoframeskip-v4-torch ...
 ... Trials: [APPO_PongNoFrameskip-v4_06cee_00000].
 ... Desired reward=18.0; desired throughput=None
 ... Not successful: Actual reward=17.97; actual throughput=2480.7492833460738
``

**Comment by kouroshHakha** [comment]
This is has almost met the reward criteria so it's def. learning it was just unlucky to pass the threshold. We should monitor the pass rate and if it's happening continuously lower the threshold a little bit. It's non-blocking for release.

**Comment by xwjiang2010** [comment]
Closing out. The team can track flakiness separately.
