### ISSUE TITLE
[RLlib] ray.rllib.policy.policy.Policy.compute_actions_from_input_dict() method return wrong actions shape while using cutomized Torch Model

### ISSUE THREAD

**Issue by ZedRover** [ray-project/ray#30613]
### What happened + What you expected to happen

I encountered this fuzzy problem when I use my customized torch model. My test model is like this 
```
class SimpleTorchModel(TorchModelV2, nn.Module):
    def __init__(self, obs_space, action_space, num_outputs, model_config, name):
        TorchModelV2.__init__(self, obs_space, action_space, num_outputs, model_config, name)
        nn.Module.__init__(self)
        input_dim = np.product(obs_space.shape)
        self.shared_fc = nn.Linear(input_dim, 128)
        self.actor = nn.Linear(128, action_space.shape[0])
        self.critic = nn.Linear(128, 1)
        
        self._feature = None
    
    def forward(self, input_dict, state, seq_lens):
        obs = input_dict["obs"].float() 
        # print('obs shape:',obs.shape)
        obs = obs.view(obs.shape[0],-1)
        self._feature = self.shared_fc.forward(obs)
        action_logits = self.actor.forward(self._feature)
        print('output action shape',action_logits.shape)
        return action_logits, state
    
    def value_function(self):
        value = self.critic.forward(self._feature)            
        return value.squeeze(1)
```
My action space is (6000,) and obs space is (3,6000). When I use this model in PPO, I got torch.distribution ValueError in the following figure
![image](https://user-images.githubusercontent.com/29392414/203489950-5ff502de-7b6b-4de0-8494-d58d8f9f0648.png)

And I think this means that the ActionDistribution is not correctly initialized. So I then print the action space in policy algo and model but it's all correct. And finally I found where the wrong action shape happened in  ray.rllib.policy.policy.Policy.compute_actions_from_input_dict(),the details are in the following figure,

![image](https://user-images.githubusercontent.com/29392414/203490445-ef3ad505-392c-46e0-a85e-6ea52f1a37f0.png)

And the Error is like this,

![image](https://user-images.githubusercontent.com/29392414/203491023-e5735e0f-81b4-44b1-902f-3f9d32ab4eea.png)

I'm confused about why the action space changed from 6000 to 3000 after 
`actions, state_outs, extra_outs = self.compute_actions_from_input_dict(
            self._dummy_batch, explore=False
        )`

### Versions / Dependencies

Python  3.7.7

ray                                    2.1.0
ray-cpp                                2.1.0
ray-lightning                          0.3.0
raydp-nightly                          2022.6.30.dev1

Docker Image: Ray-ml:latest,Ubuntu 18.04

### Reproduction script

I could provide it if somebody needs

### Issue Severity

High: It blocks me from completing my task.

**Comment by ZedRover** [comment]
I found that we can find the error just using PPOTorchPolicy class
![image](https://user-images.githubusercontent.com/29392414/203501236-c113de07-50c4-4b26-ace4-29d0d649f66c.png)
![image](https://user-images.githubusercontent.com/29392414/203501269-4f357717-db2b-47a0-a3cb-8c27a1900036.png)

**Comment by mvindiola1** [comment]
@ZedRover,

What kind of space is your action space?

**Comment by mvindiola1** [comment]
@ZedRover,

Can. you provide a reproduction script.

I have a hunch which is that in rllib when you have a continuous action space the output layer that goes into the action distribution has a shape of 2*num_outputs. Each action has two values goi g I to the action distribution. One represents the mean and the other the std of a gaussian distribution.

In your case the custom model should have an output layer of 2*6000. But if you did not do that and are only producing 6000 outputs then it would only generate 3000 actions.

**Comment by ZedRover** [comment]
![image](https://user-images.githubusercontent.com/29392414/204414611-6c71e324-c3e1-44ff-8598-82b96c709d60.png)
My customized model is like this. Should I change something in the forward method？

**Comment by mvindiola1** [comment]
I think it should be 2*action_space.shape[0] but we do not need to guess. 

You can get the required number like this:

```
from ray.rllib.models.catalog import ModelCatalog
_, actor_shape = ModelCatalog.get_action_dist(action_space, model_config)
... 
self.actor = nn.Linear(128, actor_shape) 
```

**Comment by ZedRover** [comment]
It really works. Thanks for your help!
