### ISSUE TITLE
[Serve] Memory leak from Ray serve deployment 

### ISSUE THREAD

**Issue by litttl** [ray-project/ray#30642]
### What happened + What you expected to happen

I use ray[serve] 2.1.0 to deploy my web serve. I found that there are memory leak happened.

I use the single node with the steps：
1. ray start --head
2. python my_serve.py

the key codes is as following:
__________________________________________________________________
my_serve.py
	ray.init(address='auto', namespace='serve')
	serve.start(http_options={'host':'0.0.0.0', 'port':9099}, detached=True)
	MyServe.deploy()

@serve.deployment(name=..., num_replicas=4, ray_actor_options={'num_gpus': 0.1}, route_prefix='/detect')
class MyServe:
	def __init__(self):
		...
	
	@serve.batch(max_batch_size=16, batch_wait_timeout_s=10)
    async def handle_batch(self, flask_requests):
		for flask_request in flask_requests:
			info = await flask_request.json()
			...
		
		return response
	
	async def __call__(self, request):
		return await self.handle_batch(request)
_____________________________________________________________________
		
Could anyone give me some advise?

### Versions / Dependencies

ray2.1.0

### Reproduction script

my_serve.py
	ray.init(address='auto', namespace='serve')
	serve.start(http_options={'host':'0.0.0.0', 'port':9099}, detached=True)
	MyServe.deploy()

@serve.deployment(name=..., num_replicas=4, ray_actor_options={'num_gpus': 0.1}, route_prefix='/detect')
class MyServe:
	def __init__(self):
		...
	
	@serve.batch(max_batch_size=16, batch_wait_timeout_s=10)
    async def handle_batch(self, flask_requests):
		for flask_request in flask_requests:
			info = await flask_request.json()
			...
		
		return response
	
	async def __call__(self, request):
		return await self.handle_batch(request)

**Comment by architkulkarni** [comment]
Hi @litttl,

How are you detecting the memory leak?  Can you share which process is leaking memory, and how fast?  Does it only happen when you're receiving requests, or does it still happen when there are no requests?
