### ISSUE TITLE
[ci] test_dataset is failing on release branch

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30644]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1255#0184a638-810b-4db5-9830-f1fa21c7f244

```


(_map_block_split pid=1248) Traceback (most recent call last):
--
  | (_map_block_split pid=1248)   File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_dynamic_generator_and_store_task_outputs
  | (_map_block_split pid=1248)   File "python/ray/_raylet.pyx", line 2421, in ray._raylet.CoreWorker.store_task_outputs
  | (_map_block_split pid=1248)   File "/ray/python/ray/data/_internal/compute.py", line 456, in _map_block_split
  | (_map_block_split pid=1248)     for new_block in block_fn(blocks, *fn_args, **fn_kwargs):
  | (_map_block_split pid=1248)   File "/ray/python/ray/data/dataset.py", line 595, in transform
  | (_map_block_split pid=1248)     yield from process_next_batch(batch)
  | (_map_block_split pid=1248)   File "/ray/python/ray/data/dataset.py", line 577, in process_next_batch
  | (_map_block_split pid=1248)     batch = batch_fn(batch, *fn_args, **fn_kwargs)
  | (_map_block_split pid=1248)   File "/ray/python/ray/data/dataset.py", line 735, in <lambda>
  | (_map_block_split pid=1248)     lambda batch: BlockAccessor.for_block(batch).select(columns=cols),
  | (_map_block_split pid=1248)   File "/ray/python/ray/data/_internal/simple_block.py", line 82, in select
  | (_map_block_split pid=1248)     "Column must be a single callable when selecting on Simple blocks, "
  | (_map_block_split pid=1248) ValueError: Column must be a single callable when selecting on Simple blocks, but got: [].


```

**Comment by xwjiang2010** [comment]
hmm, somehow I don't see the error or master branch...

**Comment by clarkzinzow** [comment]
@xwjiang2010 This is a Ray Core bug in task cancellation, where tasks cancelled while deserializing task arguments that's in the middle of non-reentrant imports (Arrow, Pandas, Torch, etc.) will crash the worker when trying to do the same imports while serializing the error object. See https://github.com/ray-project/ray/issues/30453#issuecomment-1320304768 for more context.

This appears to be mitigated by https://github.com/ray-project/ray/pull/30558, which might be why you're not seeing the failure on master, and this should be solved generically by https://github.com/ray-project/ray/pull/30476 once that's merged.

I would have expected this to be mitigated once this https://github.com/ray-project/ray/pull/30624 was merged into the release branch, was that not the case?

**Comment by xwjiang2010** [comment]
@clarkzinzow 
hmmm, I am afraid that the linked test [failure](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1255#0184a638-810b-4db5-9830-f1fa21c7f244) was after https://github.com/ray-project/ray/pull/30624 was merged.

**Comment by clarkzinzow** [comment]
@xwjiang2010 Ah yep, I forgot to update this thread! This turns out to be a **separate** Ray Core bug in the task cancellation protocol, namely handling tasks that are cancelled while they are queued (i.e. before they start running). I'm currently working on a fix with the Core folks.

**Comment by xwjiang2010** [comment]
Thanks @clarkzinzow ! Let's make sure the PRs are marked as release-blocking to track.
