### ISSUE TITLE
[Dashboard] Logs page links has issue if multiple ray nodes running on the same machine

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#30659]
### What happened + What you expected to happen

Logs page links has issue if multiple ray nodes running on the same machine.

e.g., if I starts 4 ray worker nodes on a machine, then, the dashboard logs page shows:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/19235986/203999417-37008e4a-234e-4f37-954e-ee4a7cf95497.png">

The 3 red lines links does not work.

### Versions / Dependencies

Ray master version.

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
cc @rkooo567 for triage

**Comment by WeichenXu123** [comment]
Another similar dashboard log page issue:
https://github.com/ray-project/ray/issues/30677

CC @rkooo567

**Comment by jovany-wang** [comment]
So interesting, i'm wondering why you need to run multiple nodes on a machine, and how you deploy your ray cluster.

**Comment by WeichenXu123** [comment]
@jovany-wang 

"run multiple nodes on a machine" is required by this case: https://github.com/ray-project/enhancements/blob/main/reps/2022-09-19-ray-on-spark.md

**Comment by jovany-wang** [comment]
So maybe adding the port to the links could fix your issue?
![image](https://user-images.githubusercontent.com/19473861/204272205-d3e965e3-8bd8-4f9d-a21b-da5bb460f20e.png)

**Comment by rkooo567** [comment]
Let's not use the port but use the node id instead

**Comment by rkooo567** [comment]
@WeichenXu123 do you guys have any interest in contributing? I'd love to help making a PR if you guys are interested

**Comment by jovany-wang** [comment]
Hum, IP will break our internal log links because we always start a new raylet process once the previous one gets dead as a fast failover.

**Comment by WeichenXu123** [comment]
@rkooo567 I am not familia with the part code, cannot contribute it for now.

**Comment by WeichenXu123** [comment]
> Hum, IP will break our internal log links because we always start a new raylet process as a fast failover once the previous one gets dead.

So what's the relationship with my case ?
My case I start 4 ray nodes in a machine, I think it should start 4 raylets processes correspondingly ?

**Comment by rkooo567** [comment]
@jovany-wang if we have node id, that should be okay?

```
<node_id>  <- this is unique
(<IP>) <- this is used
```

@WeichenXu123 in this case, you will have 4 unique node id and 1 IP addresses. E.g., 

```
010000 (127.0.0.1)
020000 (127.0.0.1)
030000 (127.0.0.1)
040000 (127.0.0.1)
```

and `ray list nodes` should tell you the node id of each raylet

**Comment by rkooo567** [comment]
And that would be equivalent to the original proposal you made, or would that be different? https://github.com/ray-project/ray/issues/30659#issuecomment-1328953303

**Comment by jovany-wang** [comment]
oh, my bad. They are the same.

**Comment by jovany-wang** [comment]
Node id looks good to me. @MisterLin1995 CC

**Comment by MisterLin1995** [comment]
I think it can help to solve @WeichenXu123 's problem and it's feasible.

**Comment by jovany-wang** [comment]
@MisterLin1995 will take this.

**Comment by WeichenXu123** [comment]
@jovany-wang @MisterLin1995 @rkooo567 
I just found that, if I set different `--dashboard-agent-listen-port` for each ray nodes, then the issue is addressed, like:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/19235986/205292920-41b9c25e-5727-4a12-8e26-26692d65264a.png">

**Comment by MisterLin1995** [comment]
> @jovany-wang @MisterLin1995 @rkooo567 I just found that, if I set different `--dashboard-agent-listen-port` for each ray nodes, then the issue is addressed, like: <img alt="image" width="620" src="https://user-images.githubusercontent.com/19235986/205292920-41b9c25e-5727-4a12-8e26-26692d65264a.png">

Actually it's kind of necessary to set different dashboard agent ports for different ray nodes otherwise worker nodes' dashboard agents won't work due to conflicted ports.

**Comment by WeichenXu123** [comment]
> Actually it's kind of necessary to set different dashboard agent ports for different ray nodes otherwise worker nodes' dashboard agents won't work due to conflicted ports.

I agree! So this should not be a bug.

**Comment by jovany-wang** [comment]
Yes. I think this issue could be closed.
