### ISSUE TITLE
[Dashboard] Jobs page does not show tasks

### ISSUE THREAD

**Issue by WeichenXu123** [ray-project/ray#30660]
### What happened + What you expected to happen

Jobs page does not show tasks.

My ray job has created several tasks, the node page can show them:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/19235986/204000178-a002c6a9-b313-447c-aca6-b7fb0c41e44f.png">

But job page does not show them, see following snapshots:

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/19235986/203999934-0eb87fdf-0d23-4723-b8a3-31d6a3a11b10.png">

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/19235986/204000008-72445748-2619-4418-8691-3f715076384c.png">

### Versions / Dependencies

Ray master version.

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
cc @rkooo567 for triage.

**Comment by rkooo567** [comment]
Do you have prometheus setup? This doesn't work without prometheus. cc @alanwguo we should make this more obvious from the UI (e.g., making a tooltip on unavailable text to explain how to set this up with a link)

**Comment by WeichenXu123** [comment]
@rkooo567 I haven't setup prometheus, I will try that.

**Comment by alanwguo** [comment]
I just noticed this today. The job detail page should show the same "unavailable" message and have the tooltip that's shown in the job list page. Will put up a fix and cherry-pick for 2.2

**Comment by alanwguo** [comment]
UI issue fixed by #30751 

@WeichenXu123, will keep this issue open until you confirm that setting up prometheus resolved your issue.

**Comment by WeichenXu123** [comment]
@alanwguo I tested. It works fine!

**Comment by Tom-Newton** [comment]
I think the cause is likely to be different but we are currently experiencing the same symptom on `2.51.1`. It looks like calls to `https://<ray-head-url>/api/v0/tasks/summarize?filter_keys=job_id&filter_predicates=%3D&filter_values=02000000` are returning 500 errors.
