### ISSUE TITLE
The webui_url for jupyter should contains the ip address 

### ISSUE THREAD

**Issue by adoda** [ray-project/ray#3066]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Red Hat 4.8.5-4
- **Ray installed from (source or binary)**: source
- **Ray version**: master
- **Python version**: 3.6
- **Exact command to reproduce**: ray start --head 

### Describe the problem

When we start ray, it will generate the web UI for jupyter, such as:
```
======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=ff1c08d8cf2bdfb1b6fa2aa385ca0d114ee6513582777990
======================================================================
```
The web UI is start with "http://localhost", so we can't access the url in other machine.

**Comment by radugrosu** [comment]
See https://ray.readthedocs.io/en/latest/webui.html?highlight=ssh%20-L#running-the-web-ui. Forward a local port of your choosing (say 9999) as described there and view the notebook on localhost:9999.

**Comment by robertnishihara** [comment]
Closing because the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
