### ISSUE TITLE
[ci][core] bk://:mac: :apple: Wheels and Jars is flaky

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30686]
on release branch: 
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1270#0184aa2f-4d93-4573-b67c-41a801f65913

on master:
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1288#0184bdb3-96a6-44cf-a13b-03473f0a2c18

Seems to have the same signature with:
"/Users/ec2-user/.zshrc: line 77: PS1: unbound variable"

**Comment by xwjiang2010** [comment]
My understanding is that this is not blocking release as the same failure happens for both master and release branch.
But want to confirm.

also cc @cadedaniel @clarence-wu who attempted to fix it before according to: https://anyscaleteam.slack.com/archives/CLJQR6420/p1667236766360979?thread_ts=1667235901.630159&cid=CLJQR6420

**Comment by cadedaniel** [comment]
I don't think this should block release. I didn't follow the attempted fixes closely, @clarng can you confirm whether this should be release blocking or not?

**Comment by scv119** [comment]
@iycheng to decide if this is a release blocker.

**Comment by iycheng** [comment]
@scv119  my feeling is that since it's not broken in ray 2.1 (https://buildkite.com/ray-project/oss-ci-build-branch/builds/1120#018486b8-ee35-4527-b2ce-140ae28678b5) and it seems that the whole test didn't run (2.1's run for 1-2 h and this only run for 30min). So we probably should fix this.

This one is the one creating wheels. If we skip this, I guess we won't have mac wheels.

**Comment by iycheng** [comment]
Ok, it seems that it's just flakey. For example, https://buildkite.com/ray-project/oss-ci-build-branch/builds/1306#0184c097-232a-494c-b22d-ff393e946217 finished on releases 2.2.0 branch.

I'd say, if it's just flakey, it's not an issue. @xwjiang2010 when you get errors like this, could you just retry? If you successfully finish it eventually and get the wheels, I think it's OK.

**Comment by xwjiang2010** [comment]
dropping release-blocker according to last comment.
