### ISSUE TITLE
[Core][nightly-test] chaos_dataset_shuffle_sort_1tb failing due to OOM killer

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#30680]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_zx9wmehu4fents5ge6itu2ye is failing. Reading the log seems the OOM killer is aggressively killing workers.

### Versions / Dependencies

latest

### Reproduction script

chaos_dataset_shuffle_sort_1tb

### Issue Severity

High: It blocks me from completing my task.

**Comment by clarng** [comment]
Looks like with the change it triggers ray.exceptions.ObjectFetchTimedOutError

Manually running the test I can see the OOM errors , the test still passed and finished 

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_xkmx8u2v5s7skku661x118zt?command-history-section=command_history

It is likely that the reduction in memory capacity is triggering more task being killed and higher likelihood of hitting the  object recovery error. 

We have a PR out to increase memory capacity to match previous amount

**Comment by scv119** [comment]
Action item: find root cause and reenable oom killer for this test.

**Comment by rkooo567** [comment]
Should be duplicate of https://github.com/ray-project/ray/issues/32046. Closing it as duplicate
