### ISSUE TITLE
[AIR] `DataParallelTrainer`s require redundant ScalingConfig if also passed through Tuner `param_space`

### ISSUE THREAD

**Issue by heng2j** [ray-project/ray#30695]
### What happened + What you expected to happen

Ray Tuner's `param_space` argument seems [support custom params with key "params"](https://github.com/ray-project/ray/blob/ray-2.1.0/python/ray/tune/tuner.py#L78-L99). However, when paired with [TorchTrainer](https://github.com/ray-project/ray/blob/master/python/ray/train/torch/torch_trainer.py#L15) which doesn't have the `params` attribute, will yield `TorchTrainer.__init__() got an unexpected keyword argument 'params'` . 

Is there any workaround for passing custom params in Tuner while using TorchTrainer in Ray 2.1.0?

### In addition,

why it is necessary to specify `ScalingConfig` during initialization of `TorchTrainer` even we can specify it in Tuner's `param_space` ?

For example, I can not initialize my trainer as simple as:

```python
    trainer = TorchTrainer(train_func)
```

Then set the `ScalingConfig` in Tuner:

```python
    tuner = Tuner(
        trainer,
        param_space={
            "train_loop_config": {
                "lr": tune.grid_search([0.001, 0.01, 0.05, 0.1]),
                "momentum": 0.8,
                "batch_size": 128 * args.num_workers,
                "test_mode": args.smoke_test,  # whether to to subset the data
                "data_dir": args.data_dir,
                "epochs": args.num_epochs,
            },
            "scaling_config" : ScalingConfig(
            num_workers=args.num_workers, use_gpu=args.use_gpu
        ),
        },
        tune_config=TuneConfig(
            num_samples=1, metric="loss", mode="min", scheduler=pbt_scheduler
        ),
        run_config=RunConfig(
            stop={"training_iteration": 3 if args.smoke_test else args.num_epochs},
            failure_config=FailureConfig(max_failures=3),  # used for fault tolerance
        ),
    )
```

If I run the code above, I will get:

```shell
Exception has occurred: ValueError
You must specify the 'num_workers' in scaling_config.

```

### Versions / Dependencies

**Ray:** 2.1.0
**Python:** 3.10
**OS:** Ubuntu 20.04.3 LTS 

### Reproduction script

I am using the official [`tune_cifar_torch_pbt_example.py`](https://github.com/ray-project/ray/blob/master/python/ray/train/examples/pytorch/tune_cifar_torch_pbt_example.py) as example. Please replace the following lines

```python

    trainer = TorchTrainer(
        train_func,
        scaling_config=ScalingConfig(
            num_workers=args.num_workers, use_gpu=args.use_gpu
        ),
    )

    tuner = Tuner(
        trainer,
        param_space={
            "train_loop_config": {
                "lr": tune.grid_search([0.001, 0.01, 0.05, 0.1]),
                "momentum": 0.8,
                "batch_size": 128 * args.num_workers,
                "test_mode": args.smoke_test,  # whether to to subset the data
                "data_dir": args.data_dir,
                "epochs": args.num_epochs,
            },
            "params" : {}
        },
        tune_config=TuneConfig(
            num_samples=1, metric="loss", mode="min", 
        ),
        run_config=RunConfig(
            stop={"training_iteration": 3 if args.smoke_test else args.num_epochs},
            failure_config=FailureConfig(max_failures=3),  # used for fault tolerance
        ),
    )

    results = tuner.fit()

    print(results.get_best_result(metric="loss", mode="min"))

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Hi @heng2j,

For the first question, the `param_space` with AIR Trainers will populate whatever arguments are available in the constructor. The `params` argument that you highlighted in the docstring refers to xgboost specific parameters as described in the docstring of `XGBoostTrainer`. For data parallel trainers such as `TorchTrainer`, the easiest way to pass in "custom parameters" is through `training_loop_config`. Take a look [here](https://docs.ray.io/en/latest/train/dl_guide.html#hyperparameter-tuning-ray-tune) for an example.

For the second question, I've attached a PR resolving this to the issue!

**Comment by heng2j** [comment]
Hi @justinvyu, thank you for your quick response! Sorry that I made the assumption that 'params' was a standard way to pass in custom parameters. Thank you for your suggestions, and I managed to add the "custom parameters" via the `training_loop_config`. 

And thank you for creating the PR to fix this issue! Much appreciate for your quick turnaround!
