### ISSUE TITLE
[tune] Exception raised when there is no more trials

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#3069]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.11
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 2.7
- **Exact command to reproduce**:

### Describe the problem

For `SeachAlgorithm`, if `next_trials` returns empty and `is_finished` yields `True`. The following happens in `TrialRunner`:
```
   def step(self):
        ...
        next_trial = self._get_next_trial()      <----- no more trial, which yields None here
        if next_trial is not None:
            self.trial_executor.start_trial(next_trial)
        elif self.trial_executor.get_running_trials():      <--- all trials completes, so no more running trials
            self._process_events()
        else:
            ....
            raise TuneError("Called step when all trials finished?")    <--- reach here
```

### Source code / logs

See above

For the solution, I think we can add
```
if not self._search_alg.is_finished():
    raise(...)
```

**Comment by richardliaw** [comment]
What is the situation where this occurs? Do you have an example for
reproducing?

**Comment by ericl** [comment]
We already check search_alg.is_finished() in runner.is_finished(), so I don't think we should even be entering step() if the search algo is finished.

**Comment by ericl** [comment]
I see, that makes sense!
