### ISSUE TITLE
[Datasets] Make Ray Data API reference page more easier to read

### ISSUE THREAD

**Issue by c21** [ray-project/ray#30692]
### Description

Current we have an Index Page - https://docs.ray.io/en/latest/data/api/api.html, and Individual API Page - https://docs.ray.io/en/latest/data/api/dataset.html#basic-transformations. It has two problems:

* The API Page has all APIs, which is crowded, hard to read, and pass around link to reference individual API. It also does not work well with search engine. E.g. Googling `ray data map_batches` does not show up the API page for `map_batches`. But googling `pyspark map` shows up the API page in first seveal results.
* Summary Page for a group of related APIs is hard to discover. Currently when user clicks "[Basic Transformations](https://docs.ray.io/en/latest/data/api/dataset.html#basic-transformations)" in our Index page - https://docs.ray.io/en/latest/data/api/api.html, it directs users to a page with all APIs -  https://docs.ray.io/en/latest/data/api/dataset.html#basic-transformations . We should have a Summary Page to list all APIs of `Basic Transformations`, and one-line explanation of those APIs.

It would be better to have flow as:

Index Page -> Summary Page -> Individual API Page.

1. Index page gives an index of all APIs based on category (current is good, no need to change)
2. Index page directs user to Summary page.
3. Summary page directs user to Individual API page (each API has its own page, not put them together).

E.g.
Index page: https://spark.apache.org/docs/latest/api/python/reference/index.html
Summary page: https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/series.html
Individual API page: https://spark.apache.org/docs/latest/api/python/reference/pyspark.pandas/api/pyspark.pandas.Series.map.html#pyspark.pandas.Series.map

### Link

https://docs.ray.io/en/latest/data/api/api.html

**Comment by c21** [comment]
cc @bveeramani, @matthewdeng, @clarkzinzow and @jianoaix for opinions.

**Comment by jianoaix** [comment]
The structure looks good to me. It seems a common structure, e.g. in addition to Spark, both Pandas and PyArrow are laid out this way as well: https://pandas.pydata.org/docs/reference/index.html, and https://arrow.apache.org/docs/python/api.html
