### ISSUE TITLE
[ci][rllib] lint is failing on release branch

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30713]
e.g. https://buildkite.com/ray-project/oss-ci-build-branch/builds/1285#0184b9ea-e667-4718-a665-74438016f546

we should not use absolute references but relative instead. Maybe take a look at example here: https://docs.ray.io/en/master/cluster/vms/references/ray-cluster-configuration.html#minimal-configuration

**Comment by xwjiang2010** [comment]
cc @Yard1

**Comment by xwjiang2010** [comment]
Dropping release blocker.
As a separate item, rllib team would evaluate updating to use relative links.

**Comment by ArturNiederfahrenhorst** [comment]
@xwjiang2010 I believe this is fixed?

**Comment by xwjiang2010** [comment]
See my last comment. I believe to prevent this from happening long term, rllib doc should use relative link rather than absolute link. 
This ticket is kept open in case that is something rllib team wants to adopt.

**Comment by ArturNiederfahrenhorst** [comment]
I'm taking this, thanks!

**Comment by ArturNiederfahrenhorst** [comment]
@maxpumperla can you have a look? I think ultimately we should never link to the repo anywhere, right?
