### ISSUE TITLE
[ci][rllib] two tests timing out

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30735]
test_dqn_frozenlake_v1: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1306#0184c0a8-ec12-40c1-a360-bc64fdd54bc9

batch_norm_model_dqn_tf: https://buildkite.com/ray-project/oss-ci-build-branch/builds/1306#0184c0a8-ec16-422e-be0f-ae5f7cb701fc

**Comment by xwjiang2010** [comment]
Let me know if this is just flakiness and I should ignore.

**Comment by xwjiang2010** [comment]
batch_norm_model_dqn_tf is also flaky on master, ignoring it after discussing with @kouroshHakha

**Comment by kouroshHakha** [comment]
Both tests seem to be non-blocker. `batch_norm_model_dqn_tf` is just flakey. `test_dqn_frozenlake_v1`'s error does not make sense and It runs fine both on master and even on this branch when checked out locally.
