### ISSUE TITLE
[Core/observability] "View the dashboard at..." message is printed even if `include_dashboard` is False

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#30759]
### What happened + What you expected to happen

If a user calls `ray.init(include_dashboard=False)` the `"Started a local Ray instance. View the dashboard at..."` message will still be printed, which is misleading.

The webpage can be opened, but no metrics will be fetched, making the dashboard unusable (as expected).

See https://discuss.ray.io/t/disable-dashboard/8471 for context

### Versions / Dependencies

master

### Reproduction script

`ray.init(include_dashboard=False)`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
cc: @rkooo567 Could we fix it really quickly and cherrypick it into 2.2 if possible?

**Comment by rkooo567** [comment]
this should be fixed
