### ISSUE TITLE
Multi-period observation input 

### ISSUE THREAD

**Issue by oroojlooy** [ray-project/ray#3075]
Hi, 

I was wondering is there any implementation to pass last m observation as input into either of rlLib algorithms? I checked to see if I can write a custom preprocessor function, but in that case I need a custom memory to keep previous observation and handling it with replay memory in off-policy algorithms would be easy. Since, the original DQN paper used such trick, I though probably it is developed and I just need to ask how to use it. 
I appreciate your comments.

Thanks,

**Comment by ericl** [comment]
Hey @oroojlooy, you can do this with a gym environment wrapper (basically a stateful preprocessor). We already do this for Atari envs, and you can find the code for this in atari_wrappers.py and use it to create a custom env of your own.

**Comment by oroojlooy** [comment]
Thanks @ericl, I see that `FrameStack(env,k)` manages this operation.
