### ISSUE TITLE
[core] Document Windows and OSX support for Ray clusters, support opt-in

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#30770]
### Description

Currently Ray will silently fail to work if a user attempts to create a Windows or OSX cluster. `ray start` works without issue but [this line](https://github.com/ray-project/ray/blob/398971210671336d1e9c63b068ef5798e96a7158/python/ray/_private/services.py#L624) causes the driver to always listen on a localhost address, which causes mysterious errors about being unable to retrieve an object when trying to run an application.

We should:

- [ ] document the fact that Windows and OSX cluster support is not guaranteed
- [ ] add a warning about this when running `ray start`
- [ ] add an opt-in flag for allowing the driver to start in cluster mode even if using windows or osx

**Comment by stephanie-wang** [comment]
As a temporary workaround, I believe you can do `ray.init(_node_ip_address="localhost")` but it's a bit of a hack and isn't guaranteed to work in the future.

**Comment by cadedaniel** [comment]
cc @jjyao FYI

**Comment by jjyao** [comment]
This is done as part of #31166
