### ISSUE TITLE
PPO without local evaluation

### ISSUE THREAD

**Issue by rjeli** [ray-project/ray#3077]
Hi,

I'm using rllib for PPO. My simulator involves a few nets for perception, so each env needs a GPU. I set `num_envs_per_worker` to 1 and `num_gpus_per_worker` to 1, and the remote evaluators work fine but there's still a local evaluator created, and it doesn't have a GPU assigned (`ray.get_gpu_ids()` is empty).

Is there a way to run PPO without a local evaluator? Thanks!

https://github.com/ray-project/ray/blob/a41bbc10ef5c3e0a8a3e8a36dbbe18171b556ada/python/ray/rllib/agents/ppo/ppo.py#L80

**Comment by rjeli** [comment]
I have it working by assuming GPUs 1-3 are allocated, then hardcoding the evaluator to check if `get_gpu_ids()` is empty and using GPU 0. Probably won't have this issue once I start cluster training...

**Comment by ericl** [comment]
@rjeli the GPU allocation to the local evaluator should be controlled by the num_gpus config (these GPUs are used for SGD).

The environment created in the local evaluator is not used if there are remote evaluators, so it should be ok to also not have GPUs for it.

**Comment by opherlieber** [comment]
Hi Eric,
What about the case where just the creation of the ENV (even if not used after creation) is very resource costly, or not even possible on the local evaluator machine (For example uses external hardware connected to the remote machine)
In this case would the correct way be to use the 'worker_index' value in the EnvContext passed to the creator? Is it safe to assume that worker_index=0 will always be the local evaluator?

Thank you

**Comment by ericl** [comment]
Yep, that should work. You can also modify/wrap the env to defer any
expensive work until reset() is called.

The reason the env is created locally is to get the observation and action
space, so that is all that is required to be available locally.

**Comment by opherlieber** [comment]
OK thanks! I'm actually using the AsyncSampler, and in this case the sampler on local evaluator is actually also running the policy<->env loop and gathering samples for a few iterations, until the AsyncSampler queue gets full afterwards it stops as the local PolicyEvaluator is not retrieving them.
For now I've implemented 'dummy' behavior in the reset/step for the local ENV case to overcome this.
