### ISSUE TITLE
[release][core] oom release test is failing

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30788]
https://buildkite.com/ray-project/release-tests-branch/builds/1227#0184c6bc-20d9-4cbd-8cae-edd222e3873d

Retrying now

**Comment by xwjiang2010** [comment]
Still failing after retry (the retry is just under the original linked try in buildkite UI)

**Comment by clarng** [comment]
oom killer is not enabled in the test:

(base) ray@ip-172-31-237-100:~/oss-release-tests-2$ grep -r memory_mon /tmp/ray/session_latest/logs/
/tmp/ray/session_latest/logs/raylet.out:[2022-11-30 07:11:54,261 I 247 247] (raylet) memory_monitor.cc:71: MemoryMonitor disabled. Specify `memory_monitor_interval_ms` > 0 to enable the monitor.

The cluster env is on commit f12d1f078ccd3df2217eb7fe79f992d8eb07df81 and does not contain the commit that enables it, can we rerun the test that contains commit f12d1f078ccd3df2217eb7fe79f992d8eb07df81

**Comment by clarng** [comment]
There is also an infra bug here
- the release test is run on the latest commit that removes the override in the cluster env
- the build is on an older commit that requires the cluster env override

hence we see the test fails on the branch and not on master

**Comment by xwjiang2010** [comment]
@clarng got it, thanks for the details!

The release infra is designed so - one can either choose to wait for the commit on head to be available, in which case the test code and the source code are exactly the same version; or one can opt to not wait and just grab the most recent available wheel on head. Note there is a delay between when a PR is landed and when the linux wheel is available for running the tests.

In this case, I opted to not wait (for the wheel of your PR to be avilable) which resulted in this discrepancy. 

I will just discard this particular test in this run and launch another one.

**Comment by xwjiang2010** [comment]
Running here: https://buildkite.com/ray-project/release-tests-branch/builds/1228

**Comment by clarng** [comment]
I am a bit confused - i thought we are not supposed to manually set the wheels per the run book:

https://www.notion.so/anyscale-hq/How-to-release-Ray-go-release-ray-28e4a2347577471288bbd7d64001fa88

Is there an issue with the run book ? If so we should update it 

Given this i am going to close this chalking it to infra issues, but please re-open if there is an issue with the code
