### ISSUE TITLE
[CI] `linux://:gcs_placement_group_manager_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#30799]
- 41a0a28045c02de8e0f681c7ed4f9441c8fb8a05 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1344#0184c68c-7f32-41d2-bb00-28c85d0aac16)
- 41a0a28045c02de8e0f681c7ed4f9441c8fb8a05 FAILED [Buildkite :cpp: Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1344#0184c68c-7f2f-4559-ab20-f86d22d0ff91)
- 47f8faa0f2389e6995b3cda6834adbbdac71316e FAILED [Buildkite :cpp: Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1318#0184c372-b8fe-44a2-ad46-5f1aee5eda4f)
- 373c30cc49120d991378996779d10fc1435007e7 FAILED [Buildkite :cpp: Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1312#0184c0e3-5c8a-4b99-a612-9102e88fcb35)
- bf0c99c2f5ee9745b43ff2dc3b247e7bcac7f428 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1297#0184bfd5-b51a-4291-88ff-047f1d3f310d)
- 46fecf93dd3987fd5dc8317600eb16addf3f2b5a FAILED [Buildkite :cpp: Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1284#0184b41b-619c-44d8-bbe2-01bb718452f1)
- 656577c6824016e18e05612127ab776fce1e5600 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1251#0184a5db-d24f-470d-9f43-deceda5784fb)
- 899ac8b546d8e016e6814f9183f1ad962027bc5e FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1243#0184a31d-35d2-4c01-8bd5-94859e5f492d)
- e6940a1edcce93e2ab9f4b422e4b9829b8914f0f FAILED [Buildkite :cpp: Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1242#0184a300-2660-4069-ad31-1d8fa22e4f20)
- 82a45658b7af62e06a6d1f6cdb63fc0f9bf28fb1 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1215#01849cc1-e3bc-46c5-bd53-f524fbcfda38)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:gcs_placement_group_manager_test-END
....

**Comment by cadedaniel** [comment]
I think Sang took this on https://github.com/ray-project/ray/issues/30573#issuecomment-1332230195
