### ISSUE TITLE
[Jobs] for `stop_job`, use SIGTERM followed by SIGKILL instead of immediately using SIGKILL

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#30803]
Currently we use SIGKILL to stop the process which runs the job entrypoint script: https://github.com/ray-project/ray/blob/87b821cc7567f284afbe0420ae152b488a352086/dashboard/modules/job/job_manager.py#L319

We should instead use SIGTERM to allow the process to exit gracefully, and only resort to SIGKILL after some timeout.

**Comment by edoakes** [comment]
Once we do, we should also update all relevant documentation.
