### ISSUE TITLE
[CI] `linux://rllib:learning_tests_multi_agent_cartpole_w_100_policies_appo` is failing/flaky on master.

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#30820]
- e78def4c701f934b094f1a50dbb2e5e11731a399 FAILED [Buildkite :brain: RLlib: Learning tests PyTorch](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1364#0184cad5-61c5-41b5-b504-b05936ca0104)
- ed3f3c08225c7049a96a290b586c67c37e2d0bc0 FAILED [Buildkite :brain: RLlib: Learning tests TF2-eager-tracing](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1361#0184ca54-c4b9-4d18-8697-b1e75c91786e)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://rllib:learning_tests_multi_agent_cartpole_w_100_policies_appo-END
....

**Comment by kouroshHakha** [comment]
PR here: https://github.com/ray-project/ray/pull/30823

**Comment by ArturNiederfahrenhorst** [comment]
<img width="1577" alt="Screenshot 2022-12-21 at 11 48 36" src="https://user-images.githubusercontent.com/9356806/208887650-53d5c451-ba5b-40d8-a95d-044c0dcca9e2.png">

https://github.com/ray-project/ray/pull/30823 has solved the issue afaics.
