### ISSUE TITLE
[RLlib] We should not checkpoint custom policies that are non-trainable

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#30840]
### Description

Often times user insert custom policies for evaluation or self-play purpose.
And we probably don't need to checkpoint them.
Not only this reduces the size of the checkpoints, there will also not be warning messages like "we don't recognize this policy, etc, etc".

**Comment by sven1977** [comment]
Good point. We should probably make this an opt-out, though. By default, checkpoint all policies. The user must then set a flag to NOT include non-trainable policies in the checkpoints.

**Comment by sven1977** [comment]
The problem with that is that then the `policy_mapping_fn` must also change. Otherwise, the checkpoint will be most likely dysfunctional.

**Comment by sven1977** [comment]
What we already have is this:

Selectively load only certain policy IDs from an existing checkpoint to at least reduce the restoration time (saving still requires writing ALL policies to disk). 
-> While providing that (reduced) list of policy IDs, the user also should always provide a new policy_mapping_fn.

See here:
https://docs.ray.io/en/master/rllib/rllib-saving-and-loading-algos-and-policies.html#multi-agent-algorithm-checkpoints

**Comment by gjoliver** [comment]
hmm interesting. we can't change the mapping function, because otherwise these checkpoints can't be used for fault tolerance purpose.
policy mapping function is actually a very tricky piece to have in checkpoints. they need to be pickled.
for inferencing use case though, we don't need the mapping function.

**Comment by sven1977** [comment]
We can add this option to the config: `config.checkpointing(checkpoint_trainable_policies_only=False)` to avoid this problem altogether for those users that need this behavior. Shouldn't be too hard.

**Comment by sven1977** [comment]
policy_mapping_fn are usually quite simple pieces of code. I don't see a huge problem having to save them (as pickle) along with the checkpoint (as we do right now). If we didn't do this, any checkpoint would NOT be self-sufficient.

**Comment by sven1977** [comment]
Made a PR. @gjoliver , please take a look and review. Thx! :)
