### ISSUE TITLE
[release][core] long_running_node_failure failed

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#30858]
https://buildkite.com/ray-project/release-tests-branch/builds/1232#0184cbd6-7254-4b60-8044-53100b51c137

@scv119 @stephanie-wang the test takes a day to finish. I already started rerun but would like to know if this is concerning.

**Comment by zhe-thoughts** [comment]
Thanks for catching this @xwjiang2010 . So the same test was passing in previous rounds of runs?

**Comment by stephanie-wang** [comment]
We're tracking the issue at #30588 and there does appear to be a more minor issue with the metrics reporting at the end of the test but the long-running test itself is passing. Will update on the other thread, but you can ignore the failure for the release.

**Comment by xwjiang2010** [comment]
Thanks @stephanie-wang !
Just for the record, the same test was passing before: https://buildkite.com/ray-project/release-tests-branch/builds/1227#0184c6bc-1fbe-4e5d-ad8e-bea93a698721

Does look like a metric reporting issue.
