### ISSUE TITLE
[CI] `osx://python/ray/tests:test_cancel` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#30899]
- 05b6f3f0b7709ee5900aad926ac3d484a8617acf FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1385#0184d03d-837d-445f-b382-58b7987ab557)
- 07b57cfe43c278015ad3f502fef322ae526e82f7 FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1375#0184ccee-60c6-4fa7-bb3a-c5480ee26145)
- b42155b3e4c2e8cbf1a0b10d350e47964d4a7325 FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1374#0184cc1f-e0a4-45aa-8954-94b221a8c916)
- ef7ed8976e20576159ea28ad6ad8856db229c0a8 FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1370#0184cd26-a818-4686-bf64-81e75f948f2d)
- eb8a54075e3f8936fb24cd4060043f9f7468405e FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1365#0184cad0-4e4a-4c89-8e8f-0e919efb095d)
- c3be24879a093a66f01f9d3991daa294372afdbd FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1358#0184c9c2-1aab-4cb1-a0ab-2e94aa069df9)
- ec9efa0fda6b7197378a1cf99e0497ae71066ebf FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1341#0184c665-2d3d-4bdf-88f3-308f9d8611f0)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_cancel-END
....

**Comment by rickyyx** [comment]
Hey @clarkzinzow - the old beast is back :( 

Seems to me it's a timeout issue on macos looking at the comments of the test. Should we disable it on macos if it's timeout critical and linux test should be sufficient since it should be platform independent?

**Comment by clarkzinzow** [comment]
@rickyyx Looks like it's timing out at 300 seconds while the Linux test is passing at ~170 seconds, and when the test does succeed on MacOS, it succeeds in the same amount of time as on Linux. So this seems like it might be some transient stalling on MacOS?

@scv119 @rkooo567 Should we consider this failure to be high-signal? Any votes on whether to skip?

**Comment by rickyyx** [comment]
> So this seems like it might be some transient stalling on MacOS?

I see, looking at the test logic again, seems there's no explicit wait, and not sure why this is actually timing out. Thought there was a `wait_condidtion` call.

**Comment by rkooo567** [comment]
Looks like lots of OSX tests started being flaky at the same time. Maybe the same root cause

**Comment by rickyyx** [comment]
I believe it's not just the mac issue (which causes the program to timeout). But there are runs where the test simply failed: 
https://buildkite.com/ray-project/oss-ci-build-branch/builds/1385#0184d03d-837d-445f-b382-58b7987ab557/936-2515

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/11676094/206602172-7f1a7638-7592-442e-b3d1-ae3ce138035f.png">

**Comment by clarkzinzow** [comment]
Ah, for those type of failures, I'm guessing that the `timeout_to_reach_arg_deserialization` is flaky for MacOS, since that timeout is tuned for Linux. I think skipping that particular test on MacOS would be reasonable, with a TODO issue to create a less fragile test.
