### ISSUE TITLE
[docs][Ray cluster] How to secure the jobs submission port?

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#30892]
### Description

Is there a way to secure the jobs submission port and how does one do this? Did a quick search in the docs but didn't see if this was documented anywhere.

**Comment by stephanie-wang** [comment]
cc @brucez-anyscale

**Comment by brucez-anyscale** [comment]
cc @sihanwang41 @simon-mo @tchordia

**Comment by simon-mo** [comment]
@architkulkarni

**Comment by sihanwang41** [comment]
added context: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1670178518671469

**Comment by 0x2b3bfa0** [comment]
#### See also
* #31980 
* 📖 [**Configuring Ray / TLS Authentication**](https://docs.ray.io/en/latest/ray-core/configure.html#tls-authentication)
