### ISSUE TITLE
Building with `make` is really slow and might be building unnecessarily

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3089]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.3
- **Python version**: N/A
- **Exact command to reproduce**: `make`

### Describe the problem
Incremental builds with `make` is now much slower and it appears to be recompiling dependences that are not necessary to recompile. Specifically, it appears to recompile for `pyarrow` every time, and it also does it twice for some reason.

This was most likely introduced by #2963.

### Source code / logs
Sample `make` output: [out.txt](https://github.com/ray-project/ray/files/2494522/out.txt)

**Comment by stephanie-wang** [comment]
@chuxi, do you have any ideas? Thanks!

**Comment by stephanie-wang** [comment]
@pcmoritz, @chuxi, do you have any ideas?

**Comment by robertnishihara** [comment]
Thanks @stephanie-wang, I'm seeing this issue as well.

**Comment by stephanie-wang** [comment]
I tried to look into this, but I don't understand the build system well enough to figure it out, unfortunately :(

Quick hack to make `make` faster in the meantime, though. Assuming you've already built `pyarrow`, you can go into `build/CMakeFiles/Makefile2` and comment out the rules for the target `CMakeFiles/pyarrow_ext.dir/all`.

**Comment by pcmoritz** [comment]
I did some more digging and this is unfortunately a bug in cmake: https://gitlab.kitware.com/cmake/cmake/issues/16419

I.e. in some cases, external projects are always rebuilt.
