### ISSUE TITLE
Remove usage of deprecated plasma client Get API.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3090]
The plasma client `Get` API has changed from

```cpp
Status Get(const ObjectID* object_ids, int64_t num_objects, int64_t timeout_ms,
           ObjectBuffer* object_buffers);
```

to 

```cpp
Status Get(const std::vector<ObjectID>& object_ids, int64_t timeout_ms,
           std::vector<ObjectBuffer>* object_buffers);
```

However, we're still using the old one in a bunch of places. We should convert it.

**Comment by suquark** [comment]
I found `ObjectBufferPool` heavily depends on the old one because it will chunk the buffer and do not want it to be released. Do you think it is still necessary to use the new interface?

**Comment by suquark** [comment]
And the implementation of the new API looks strange to me. "The objects that are automatically released by the client when their buffers get out of scope" are created inside `GetBuffers` through `wrap_buffer`. If my understanding is right, it will be released when `GetBuffers`, so `Get` will return a released buffer.

https://github.com/apache/arrow/blob/090a8c020611b2f75ec0e36d765cc6d48adbe9a7/cpp/src/plasma/client.cc#L470-L473
