### ISSUE TITLE
[CI] `osx://python/ray/tests:test_runtime_env_working_dir_remote_uri` is failing/flaky on master.

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#30928]
- 0dc65aedbe1a4f5aa5c5966fdcdc4b3c18ec345e FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1425#0184e65e-9bdf-41ee-9aa5-962edea0a077)
- fa09c05c2e39fb09e9ead842666e739a9d357977 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1407#0184dadc-2183-41ba-96b0-073f22a50543)
- 940fe109dc2c4e48d17caef89433b3e78e32de7e FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1395#0184d3e8-159f-4ce0-b09d-78e2a9f6354d)
- fd357f9d4d45ae33fc4718a209da070b0a7ea2f3 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1394#0184d3d3-36cd-485f-b935-20cfe1b811e6)
- c42b080617957030e57a565aa1c28be8b33e7e8e FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1377#0184ced4-0cd3-4c52-9951-e3c51da1bb84)
- eb8a54075e3f8936fb24cd4060043f9f7468405e FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1365#0184cad0-4e48-43e6-9c2e-b60b320dbc5c)
- ed3f3c08225c7049a96a290b586c67c37e2d0bc0 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1361#0184ca47-280d-4294-a2f6-5c9e69ed2b47)
- c3be24879a093a66f01f9d3991daa294372afdbd FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1358#0184c9c2-1aa9-40cf-8f91-8f18b05e23ad)
- 41a0a28045c02de8e0f681c7ed4f9441c8fb8a05 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1344#0184c800-9290-4023-bf36-9ff1b12a606a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_runtime_env_working_dir_remote_uri-END
....

**Comment by jjyao** [comment]
```
//python/ray/tests:test_runtime_env_working_dir_remote_uri                FLAKY, failed in 1 out of 2 in 902.0s
  | Stats over 2 runs: max = 902.0s, min = 371.7s, avg = 636.9s, dev = 265.1s
```

Time out.

**Comment by jjyao** [comment]
```
ray.exceptions.RuntimeEnvSetupError: Failed to set up runtime environment.
--
  | E                       Failed to create runtime environment for job 01000000 because the Ray agent couldn't be started due to the port conflict. See `dashboard_agent.log` for more details. To solve the problem, start Ray with a hard-coded agent port. `ray start --dashboard-agent-grpc-port [port]` and make sure the port is not used by other processes.
```

Port conflict
