### ISSUE TITLE
pending resources and running resources are different in slurm

### ISSUE THREAD

**Issue by wxie2013** [ray-project/ray#30925]
### What happened + What you expected to happen

I assigned number of nodes and cpus_per_node via the following command:

    #SBATCH --nodes=3
    #SBATCH --cpus-per-task=5

I expect the total number CPUs for this job is 3x5=15.  This is what's show in pending jobs status. As soon as the job start to run, the tot number of CPUs for this job become 3x24 = 72, where 24 is the total number of codes of each node.  I expect the resources when a jobs is pending and running should remain unchanged
    

### Versions / Dependencies

Ray2.1.0

### Reproduction script

This is the slurm script: 

    #!/bin/bash
    # shellcheck disable=SC2206
    # THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
    # THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!
    # https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html

    #SBATCH --job-name=test_1205-1035
    #SBATCH --output=test_1205-1035.log

    ### This script works for any number of nodes, Ray will find and manage all resources
    #SBATCH --nodes=3
    #SBATCH --exclusive
    ### Give all resources to a single Ray task, ray can manage the resources internally
    #SBATCH --ntasks-per-node=1
    #SBATCH --gpus-per-task=0
    #SBATCH --cpus-per-task=5
    #SBATCH --mem-per-cpu=3GB

    # Load modules or your own conda environment here
    # module load pytorch/v1.4.0-gpu
    # conda activate ${CONDA_ENV}

    # ===== DO NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING =====
    # This script is a modification to the implementation suggest by gregSchwartz18 here:
    # https://github.com/ray-project/ray/issues/826#issuecomment-522116599
    redis_password=$(uuidgen)
    export redis_password

    nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST") # Getting the node names
    nodes_array=($nodes)

    node_1=${nodes_array[0]}
    ip=$(srun --nodes=1 --ntasks=1 -w "$node_1" hostname --ip-address) # making redis-address

    # if we detect a space character in the head node IP, we'll
    # convert it to an ipv4 address. This step is optional.
    if [[ "$ip" == *" "* ]]; then
      IFS=' ' read -ra ADDR <<< "$ip"
      if [[ ${#ADDR[0]} -gt 16 ]]; then
        ip=${ADDR[1]}
      else
        ip=${ADDR[0]}
      fi
      echo "IPV6 address detected. We split the IPV4 address as $ip"
    fi

    port=6379
    ip_head=$ip:$port
    export ip_head
    echo "IP Head: $ip_head"

    echo "STARTING HEAD at $node_1"
    srun --nodes=1 --ntasks=1 -w "$node_1" \
      ray start --head --node-ip-address="$ip" --port=$port --redis-password="$redis_password" \
      --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
    sleep 30

    worker_num=$((SLURM_JOB_NUM_NODES - 1)) #number of nodes other than the head node
    for ((i = 1; i <= worker_num; i++)); do
      node_i=${nodes_array[$i]}
      echo "STARTING WORKER $i at $node_i"
      srun --nodes=1 --ntasks=1 -w "$node_i" ray start --address "$ip_head" --redis-password="$redis_password" \
      --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
      sleep 5
    done

    # ===== Call your code below =====
    python oo.py --ip_head $ip_head

Here is the python script, i.e. oo.py

    import os, time, ray, argparse
    import pandas as pd
    import multiprocessing
    from ray import tune, air
    from hyperopt import hp
    from ray.tune.search.hyperopt import HyperOptSearch
    from ray.tune.search import ConcurrencyLimiter

    # disable dash board. See: https://discuss.ray.io/t/disable-dashboard/8471
    parser = argparse.ArgumentParser()
    parser.add_argument('--ip_head', type=str, required=True)
    args = parser.parse_args()
    ray.init(address=args.ip_head)

    # 1. Define an objective function.
    def objective(config, data = None):
        #time.sleep(60)
        f = open(os.path.join(os.getcwd(), "oo.root"), "w")
        for i in range(10): # 10 epochs
            score = config["a"] ** 2 + config["b"]
            #SCORE 1st apparence which defines the key of the dictionary, i.e. metric="SCORE", 
            # or  return {"SCORE": score}
            tune.report(SCORE=score)  # this or the following return should work
            #return {"SCORE": score}

    # 2. Define a search space.
    search_space = {
        "a": hp.uniform("a", 0, 1),
        "b": hp.uniform("b", 0, 1)
        }

    raw_log_dir = "./ray_log"
    raw_log_name = "example"

    algorithm = HyperOptSearch(search_space, metric="SCORE", mode="max", n_initial_points=1)
    algorithm = ConcurrencyLimiter(algorithm, max_concurrent=8)
    if os.path.exists(os.path.join(raw_log_dir, raw_log_name)) == False:
        print('--- this is the 1st run ----')
    else: #note: restoring described here doesn't work: https://docs.ray.io/en/latest/tune/tutorials/tune-stopping.html 
        print('--- previous run exist, continue the tuning ----')
        algorithm.restore_from_dir(os.path.join(raw_log_dir, raw_log_name))

    # 3. Start a Tune run and print the best result.
    trainable_with_resources = tune.with_resources(objective, {"cpu": 1})
    #trainable_with_resources = tune.with_resources(objective, {"cpu": multiprocessing.cpu_count()})
    tuner = tune.Tuner(
            #tune.with_parameters(trainable_with_resources, data = "aaaa"),
            trainable_with_resources ,
            tune_config = tune.TuneConfig(
                num_samples = 10, # number of tries. too expensive for Brian2
                time_budget_s = 10000, # tot running time in seconds
                search_alg=algorithm,
                ),
            run_config = air.RunConfig(local_dir = raw_log_dir, name = raw_log_name) # where to save the log which will be loaded later
            )

    results = tuner.fit()
    best_result = results.get_best_result(metric="SCORE", mode="max")

### Issue Severity

High: It blocks me from completing my task.

**Comment by wxie2013** [comment]
It might be because of the following command: 

    trainable_with_resources = tune.with_resources(objective, {"cpu": 1})

The resource probably should be the one specified by slurm. The question is what resource should be set here to meet the requirement, i.e. total number of CPUs is 3*5 = 15 instead of 3*24 = 72

**Comment by tupui** [comment]
I think what is happening is that you are limiting the CPU only on the main node. Then when you are doing the subsequent `srun` calls, this is here that you should specify instead the CPU limits. Otherwise it takes a node and I don't know how it would know about limits you would said on the main node.

**Comment by tupui** [comment]
I meant to use `--cpus-per-task` on the `srun` command:

```
srun --nodes=1 --ntasks=1 --cpus-per-task=5 -w "$node_1" \
ray start --head --node-ip-address="$ip" --port=$port --redis-password="$redis_password" \
--num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus "${SLURM_GPUS_PER_TASK}" --block &
```

In any case, I would test the logic first without even using Ray. This way you are sure you use SLURM appropriately and only then plug in Ray.

**Comment by tupui** [comment]
I think you should not mix `--cpus-per-task` and `--num-cpus`.

As I said, don't use Ray for now and just try to figure out the correct options to make SLURM do the proper resource allocation. Only then plug in Ray.

**Comment by tupui** [comment]
Wait I did the wrong copy past for `srun`. It should have been the `srun` from the loop. Not the head node.

**Comment by wxie2013** [comment]
yes, I modified both places. You can see that in the updated 1st post in this thread.

**Comment by tupui** [comment]
What about the tests without Ray? Did you manage to get the result you wanted?

**Comment by tupui** [comment]
You see this running from the frontal node? Then yeah maybe something is up. I would suggest contacting your it for a SLURM question.

**Comment by wxie2013** [comment]
Will do. Thanks for all the inputs. I'm closing the thread.

**Comment by tupui** [comment]
Great thanks for reporting back and glad your issue is resolved!

**Comment by mattip** [comment]
I see `--exclusive` is mentioned [here](https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html#sbatch-directives) in the directives. Should it be removed or even commented out with a "don't do this" messsage?

**Comment by wxie2013** [comment]
I think the advantage of using  "--exclusive" option is to avoid port binding which is discussed in [https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html#id8](url). If multiple users can specify their only ports, their jobs should run fine.  Maybe we just leave a comment in the doc to notify users that this option will reserve the whole requested nodes for your jobs once it's being run?

**Comment by tupui** [comment]
Maybe we should add a warning with a link to the man page of SLURM suggesting to go through the options and before even using Ray, test the SLURM config by itself to verify that it's behaving as intended.
