### ISSUE TITLE
[AIR] Ray Trainer + Ray Tune hangs after completing first round of trials 

### ISSUE THREAD

**Issue by caesar025** [ray-project/ray#30942]
### What happened + What you expected to happen

When trying to run the Horvod Trainer+Tuner [example](https://docs.ray.io/en/latest/tune/examples/horovod_simple.html) from the Ray website, the trials hang after completing the first round of trials with the following error:

`Error: No available node types can fulfill resource request {'node:10.14.3.96': 0.01}. Add suitable node types to this cluster to resolve this issue.`

Since there is no change in available resources (and the first round of trials runs just fine) I assume there is some issue with the stopping of old and starting of new trials. I am also not sure where the "0.01" after the node-ip in the error message comes from.

The expected behavior is that ray starts the next round of trials. I am running 1 trial on 1 node (with 1 CPU and 1 GPU) on an HPC system. 

### Versions / Dependencies

Python 3.9.6
CUDA 11.5
Horovod 0.26.1
Ray 2.1.0

### Reproduction script

The example [Horovod script](https://docs.ray.io/en/latest/tune/examples/horovod_simple.html) from the Ray website. 

### Issue Severity

High: It blocks me from completing my task.

**Comment by Yard1** [comment]
Hey @caesar025 , thank you for the report. Can you run the following in a separate terminal on the same node that you are running the script while the tuning is ongoing and post the output?

`python -c "import ray; ray.init(); print(ray.nodes()); print(); print(ray.util.get_node_ip_address())"`

We suspect that the utility method we are using for obtaining the node IP address doesn't return the same values as in the nodes table.

**Comment by Yard1** [comment]
Thanks! That confirms our suspicions. I'll keep you posted.

**Comment by Yard1** [comment]
@caesar025 Are you using Ray Client (connecting to a remote cluster from a local machine)?

**Comment by caesar025** [comment]
@Yard1 I am running on one node of an HPC system that features 48 CPUs and 4 GPUs per node in total, but using only 1 CPU and 1 GPU for the trial. The script is running on the same machine as the trial and I am not using the Ray Client - as fas as I am concerned. 

My setup was working fine until Ray 1.9.

**Comment by Yard1** [comment]
Hey @caesar025, would it be possible to schedule a quick call after the holidays? It'd be great if I could see the issue in action in your environment.
