### ISSUE TITLE
How to use custom class objects and their instance & class methods inside all Ray remote functions?

### ISSUE THREAD

**Issue by mesutbicer** [ray-project/ray#3095]
First of all, I would lke to express that I examined ray-dev@googlegroups.com and couldnt find anything related to my requirement.

### My System information
- **OS Platform and Distribution**: Ubuntu 18.04.1 LTS
- **Ray installed from (source or binary)**: via pip3 install ray
- **Ray version** = 0.5.3:
- **Python version** = 3.6:

### My requirement briefly.
I want to create n different parallel remote tasks. One of these remote tasks will create custom class objects to a shared memory list and the another one will use this objects from shared memory list in a fifo style. How can I achieve this using ray framework?

From this perspective, you will see my test code below. In this code, I am creating 3 parallel task running at the background in line with producer-consumer approach. task1 and task2 are adding human objects to an actor based queue. And task3 deleting first object from this actor based queue. But the question is, why can not I use count_human method in my custom class in this scenario? (Note: Below you will see this instance method and the corresponding code line was commented.)

Thanks in advance.

```python
import ray

ray.init()

@ray.remote
class Queue_q(object):
    def __init__(self):
        self.liste = []

    def add(self, oge):
        self.liste.append(oge)
        return self.liste

    def fifo(self):
        del self.liste[0]
        return self.liste

    def show_queue(self):
        return self.liste

q1 = Queue_q.remote()
q2 = Queue_q.remote()
human_list = Queue_q.remote()

q2.add.remote(1)
q2.add.remote(2)
q2.add.remote(3)

# custom class
class Human(object):
    def __init__(self, name, surname):
        self.name = name
        self.surname = surname

    """
    def count_human(self):
        return len(human_list)
    """

@ray.remote
def task1():
    print("====================================================================")
    result = q1.add.remote("t1")
    print(ray.get(result))
    print("Length of q1: {}".format(len(ray.get(result))))

    result2 = q2.fifo.remote()
    print(ray.get(result2))
    print("Length of q2: {}".format(len(ray.get(result2))))

    h1 = Human("mesut", "bicer")
    print("{} was created and added to human queue.".format(h1.name))

    people = human_list.add.remote(h1)
    print(ray.get(people))
    print("Length of human list: {}".format(len(ray.get(people))))

@ray.remote
def task2():
    print("====================================================================")
    result = q1.add.remote("t2")
    print(ray.get(result))
    print("Length of q1: {}".format(len(ray.get(result))))

    result2 = q2.fifo.remote()
    print(ray.get(result2))
    print("Length of q2: {}".format(len(ray.get(result2))))

    h2 = Human("haktan", "bicer")
    print("{} was created and added to human queue".format(h2.name))

    people = human_list.add.remote(h2)
    print(ray.get(people))
    print("Length of human list: {}".format(len(ray.get(people))))

@ray.remote
def task3():
    print("====================================================================")
    result = q1.add.remote("t3")
    print(ray.get(result))
    print("Length of q1: {}".format(len(ray.get(result))))

    result2 = q2.fifo.remote()
    print(ray.get(result2))
    print("Length of q2: {}".format(len(ray.get(result2))))

    print("People queue now: {}".format(ray.get(human_list.show_queue.remote())))
    print("People queue and people: {} and {}".format(ray.get(human_list.show_queue.remote())[0].name, ray.get(human_list.show_queue.remote())[1].name))

    result3 = human_list.fifo.remote()
    print(ray.get(result3))
    print("Length of human list new: {}".format(len(ray.get(result3))))
    print("People queue now: {}".format(ray.get(human_list.show_queue.remote())))
    first_human_in_queue = ray.get(human_list.show_queue.remote())[0]
    print("People queue and people: {}".format(first_human_in_queue.name))


    #print("Number of people in the queue: {}".format(first_human_in_queue.count_human()))

if __name__ == '__main__':

    # Start 3 tasks in the background.
    x_id = task1.remote()
    y_id = task2.remote()
    z_id = task3.remote()

    # Block until the tasks are done and get the results.
    x, y, z = ray.get([x_id, y_id, z_id])

```

**Comment by chuxi** [comment]
I did not write python too much, can you have a try this?

https://stackoverflow.com/questions/1947904/how-can-i-pickle-a-nested-class-in-python

another three solutions I ever think: 

1. pre-install your module in all nodes
2. change current behavior, export a whole python scripts package(zip) to redis and in function_manager.py, when comes a task, extract the driver_id and get the zip package from redis if it is not in your sys.path
3. write a proxy python actor (or proxy function for python function), which would download the zip package from a http server (or file storage server, I would prefer redis again...). and then call your functions by the proxy actor. ( in the process, you need to serialize your methods and parameters, then the proxy actor should deserialize and execute it with updated sys.path)

**Comment by mesutbicer** [comment]
Thank you so much for your help, chuxi.

How can I install the module in all nodes?

**Comment by chuxi** [comment]
1. install in all nodes. `sudo pip3 install ray` will install the ray in system python path. instead, I would suggest you create a virtualenv (just custom the default_worker.py command passed to raylet, using /path/to/venv/bin/python3 to start worker which already uses the venv libraries) and install ray in it. After you install ray, your python ray worker can find ray lib. 

Besides, I use virtualenv to resolve version problem for ray applications. 

2. here your custom class (Human) is defined in driver. and ray will not serialize and export `Human`.(not sure, old implementation in my memory) You can install `Human` class on all nodes and then run your code.

**Comment by robertnishihara** [comment]
@mesutbicer thanks for posting this! Can you say what the error message is? It should definitely be possible to do the thing you're trying to do.

It may help to strip down the example to the minimum example that reproduces the issue.

**Comment by zhe-thoughts** [comment]
I'm closing this old issue which most likely is not needed anymore. @mesutbicer please reopen if needed! Thanks
