### ISSUE TITLE
[Ray Core] RLock not Serializable

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#30972]
### What happened + What you expected to happen

I used cachetools (lru cache) to cache things. 
Because cachetools uses RLock, I got pickle error below using `ray.cloudpickle`:
```
TypeError: cannot pickle '_thread.RLock' object
```
I understand lock is tricky. 
Yet you can pickle it using `dill`.
Any chance `ray.cloudpickle` can support `RLock` serialization? 

### Versions / Dependencies

ray == '2.1.0'
python == 3.8

### Reproduction script

```
from threading import RLock
from ray import cloudpickle as cpkl
lock = RLock()
_ = cpkl.dumps(lock)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
Hi @mlguruz, it is known that locks are not serializable in Ray. https://docs.ray.io/en/latest/ray-core/objects/serialization.html?highlight=lock#troubleshooting 

Local lock in Python (powered by kernel mutex) doesn't quite make sense in the distribute setting that Ray works in. We recommend instantiating the lock object in your remote processes. 

If you need synchronization, checkout https://docs.ray.io/en/latest/ray-core/actors/patterns/actor-sync.html
