### ISSUE TITLE
[core] stress_test_placement_group avg_pg_creation_time regression

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#30980]
### What happened + What you expected to happen

https://b534fd88.us1a.app.preset.io/superset/dashboard/p/AxJ0pXg0Gr2/
<img width="448" alt="image" src="https://user-images.githubusercontent.com/11676094/206594876-01c1dab0-effd-4bfb-ae0b-c0da2f687776.png">

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by rkooo567** [comment]
Do you know what's the offending PR? Besides, I think we can probably ignore this much of regression from pg (performance is not critical for pg creation )

**Comment by rickyyx** [comment]
It might be variance given it came down from the peak - but I was wondering if we have looked into the Nov 15 -22 jump.

**Comment by rickyyx** [comment]
If that's the case - should we not include this as a core benchmark?

**Comment by rkooo567** [comment]
but it'd be great to bisect at least to understand the offending commit

**Comment by rkooo567** [comment]
@rickyyx can you help finding an owner for bisect?

**Comment by rickyyx** [comment]
02f911ce78 Benchmarking Ray Data bulk ingest as input file size changes. (#29296)
2c032ebe0c [ci] Fix windows + mac requirements (#29506)
47a1b8914e [ci/release] Return with correct exit code (#29509)
6f5f1e6c84 Add wait_for_nodes stage for stress_test_dead_actors (#29391)
cf93dd72e2 [release][no_ci] remove datasets_ingest_train_infer and adjust datasets_preprocess_ingest. (#29447)
7afbbbcea1 Skip test on python 3.10 (#29498)
fcc0086154 Support custom resource with remote args in random_shuffle_each_window() (#29482)
93d58a13c3 [Serve][Doc] Fix batching tutorial code (#29467)
25390ff98d [doc][state observability] Updated exception/doc for state api when dashboard not available (#29390)
39d17cb40f [Core] Placement group parsing logic refactoring.  (#29141)
218f9ba631 [Metrics] Disable high cardinality operation metrics by default (#29451)
a04687c2e7 [Profile] Re-revert mem profile on dashboard/agent (#29454)
f993de39db [Metrics] Update default Grafana Dashboard Description (#29313)
9ece8acb0c [RLlib] Docs update: New Algorithm checkpoints, Policy checkpoints and Policy model exports in native format (#28812)
7c287ac4d0 [Core] Fix parallel schedule pg hangs (#29491)
d04f1dd7a6 [RLlib] fix replay_buffer_api test. (#29494)
8b800d7044 Mark remote cartpole tests exclusive to stablize them. (#29480)
769eda9723 Create docs for the metrics tab (#29414)
e93fa4b96c [metrics] Fix the ray_tasks{State="PENDING_ARGS_FETCH"} metric counting (#29392)
45d2bdbf33 [docker] Fix requirements files and installation in docker images (#29375)
8ce3ed5b76 Update instructions to build Ray from source on MacOS M1 (#29475)
0de2f18c25 [Core][nightly-test] mark chaos_dataset_shuffle_push_based_sort_1tb unstable #29483
69785334c4 [RLlib] Stablize tune_lin_ucb_train_recsim_env test. (#29477)
47594dd0b8 [Docker] Pin `fastapi` in a separate requirements file (#29441)

**Comment by rickyyx** [comment]
I think this is the culprit PR: https://github.com/ray-project/ray/commit/39d17cb40f3b0feb16c4c0078d227582ade395ec

It causes a ~10% regression
