### ISSUE TITLE
[core] grpcio thread pool issue on mac 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#30984]
### What happened + What you expected to happen

With grpcio >= 1.50.0, this PR is included: https://github.com/grpc/grpc/commit/6b95573959f4efd62c60a144b29b430e093d2813

Links https://github.com/grpc/grpc/issues/31772

And this has caused hanging of tests on mac, leading to multiple flaky tests. 
E.g. 
- https://github.com/ray-project/ray/issues/30954
- [osx://python/ray/tests:test_reconstruction](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1458#0184ef73-4ca6-4d21-ae7c-6fba362b0d05/2004-4542)
- [osx://python/ray/tests:test_placement_group](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1465#0184f2f2-3288-43db-b2cb-2b53688c2fd7/943-2191)

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
Mitigated: https://github.com/ray-project/ray/pull/30982

**Comment by PidgeyBE** [comment]
Are you sure this is a mac-only issue? Because we downgraded to ray 2.0.1 (to have grpcio<1.49) because we had this issue on linux as well...

**Comment by PidgeyBE** [comment]
Hi @rickyyx , sorry I lost track of your message.
> * Which version were you using previously before the downgrade?
Before the downgrade we were using `ray 2.2.0` , which has grpcio>1.49.
> * How frequently did this happen?
I don't quite remember. I don't think it was 100% of the time, but at least 50% or so.
