### ISSUE TITLE
【 important】Integrates ucx-py and cudf to support heterogeneous ray.

### ISSUE THREAD

**Issue by mjshare** [ray-project/ray#30988]
### Description

Currently, ray supports cudf, which will cause CPU and GPU transmission bottlenecks. ray can integrate ucx-py and cudf. ucx-py supports GPU passthrough. cudf is a GPU-friendly encapsulation.

**Comment by mjshare** [comment]
@alanwguo

**Comment by scv119** [comment]
let's merge the issue into #30094
