### ISSUE TITLE
[CI] `windows://python/ray/tests:test_task_metrics` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31029]
- b04f0e42dd888d57f7c49a4caa72cfbb038a075b FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1449#0184eea0-524a-4bec-a62f-01b8f43042d9)
- a841c07b2fae9bde536da55f087e5b90a118654d FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1446#0184ee89-1f52-4c56-85cc-25ef40820cab)
- 9e749ecbe471f4eb3a0cb24da81c6012e5da23fa FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1426#0184e66c-c599-411e-8203-6ab568499b8d)
- f40d6b693db0b89054affcfc5fc6229abf6fa27c FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1417#0184e45e-9645-4c12-99f4-494ec5ccd42e)
- f753b28053d1afc29d8da69a6dd6d77b11c9ef08 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1415#0184e394-97ef-4d88-9f0f-ba29f6848d75)
- 888d60b9715739adaa17a199ce377dcf8b8799c2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1404#0184d678-68cb-416d-80e9-49e0d1925e2b)
- 3885c377b2345174e7a26d1880563bf995bddd89 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1398#0184d4e0-0049-4915-97f4-ea8b9e9b3161)
- 940fe109dc2c4e48d17caef89433b3e78e32de7e FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1395#0184d3e8-599b-4ce1-b036-f26f64a4ec39)
- fd357f9d4d45ae33fc4718a209da070b0a7ea2f3 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1394#0184d3d3-324a-4706-9589-ae876acc5431)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_task_metrics-END
....

**Comment by rickyyx** [comment]
I believe it's mostly due to slowness in metrics showing up on windows. Are we tracking the metrics optimization in some other issues already? @rkooo567

**Comment by rkooo567** [comment]
I am planning to fix this by this sprint
