### ISSUE TITLE
[CI] `windows://python/ray/tests:test_object_spilling` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31031]
- 2bd709f56bf7042555e9bd79e91c553481359079 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1492#01850593-7da9-4cf1-89e2-b20e1a0c2ea5)
- 2c557edd0633004534146b93a91a417d0ad9ca09 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1470#0184f3e3-12e3-4a91-aae4-92af05c9cc3a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_object_spilling-END
....

**Comment by mattip** [comment]
The test no longer shows up on https://flaky-tests.ray.io/. Can we close this?
