### ISSUE TITLE
[core][nightly] decision_tree_autoscaling_20_runs fails with worker deaths

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31032]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-anyscale-staging-release/builds/89#01850486-4316-4c65-a34e-02406f873f67

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by clarng** [comment]
Seems it passed 9/10 times recently? 

https://buildkite.com/ray-project/release-tests-anyscale-staging-release/builds?branch=master

**Comment by clarng** [comment]
seems flaky for one run, will continue to monitor

**Comment by clarng** [comment]
looks green on the last 10 runs
