### ISSUE TITLE
[Tune] Switch to `NodeAffinitySchedulingPolicy` in Tune

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#31037]
### Description

We are currently using IP-based scheduling in Tune for eg. file syncing. This will be removed in the future. We should switch to the recommended way of scheduling tasks on specific nodes with `NodeAffinitySchedulingPolicy`.

See https://github.com/ray-project/ray/issues/31038 for the parent issue

**Comment by matthewdeng** [comment]
Closed by https://github.com/ray-project/ray/pull/32016
