### ISSUE TITLE
[Core] Tasks/actors with no resource requirements are not scheduled using placement groups as expected

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#31034]
### What happened + What you expected to happen

I specify an actor which uses a `STRICT_PACK` placement group scheduling strategy with `placement_group_capture_child_tasks=True`. That actor spawns several tasks which have no resource requirements (`num_cpus=0`). I expect the tasks to be scheduled on the same node as the actor, as the strategy is `STRICT_PACK`. Instead, the tasks are running on arbitrary nodes. This only happens if the tasks have no resource requirements.

### Versions / Dependencies

master (df13a1de135e99b2c4b0bd0d8d2621246a143d12)

### Reproduction script

```python
import ray
import ray.util
from ray.util.placement_group import placement_group
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy


@ray.remote
def task(ip):
    print(ip, ray.util.get_node_ip_address())
    assert ip == ray.util.get_node_ip_address()
    return


@ray.remote
class Actor:
    def __init__(self, task_cpus):
        self.task_cpus = task_cpus

    def run(self):
        task_with_cpus_set = task.options(num_cpus=self.task_cpus)
        ip = ray.util.get_node_ip_address()
        tasks = [task_with_cpus_set.remote(ip) for i in range(32)]
        ray.get(tasks)


pg = placement_group([{"CPU": 1}] * 8, strategy="STRICT_PACK")
ray.get(pg.ready())

ActorWithPlacementGroup = Actor.options(
    scheduling_strategy=PlacementGroupSchedulingStrategy(
        placement_group=pg, placement_group_capture_child_tasks=True
    )
)

# works
actor = ActorWithPlacementGroup.remote(task_cpus=1)
ray.get(actor.run.remote())

print("fail")

# fails
actor = ActorWithPlacementGroup.remote(task_cpus=0)
ray.get(actor.run.remote())
```

Run on a cluster with multiple nodes each with <= 8 CPUs (eg. https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_j4rphgl1yttb36lhzw59svlf/ses_subxaevyczw11qxaylf3m9qa)

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Looks like the same issue as https://github.com/ray-project/ray/issues/27931

**Comment by ericl** [comment]
Closed (duplicates https://github.com/ray-project/ray/issues/27931)
