### ISSUE TITLE
[train/tune] deprecate node:ip resources and use NodeAffinitySchedulingPolicy instead

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#31050]
### What happened + What you expected to happen

let's remove node:ip resources and use NodeAffinitySchedulingPolicy to schedule Actor associate to a node

master issue: https://github.com/ray-project/ray/issues/31038

### Versions / Dependencies

latest

### Reproduction script

n/a

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Taking a [quick glance](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+node:+file:train&patternType=standard&sm=1) it doesn't seem like there are any usages directly in Train. Usages are more likely to come from Tune (e.g. [_force_on_current_node](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/ray-project/ray%24+_force_on_current_node&patternType=standard&sm=1)).

There is a chance that the user manually passes in the node resource, is that something we should guard against within the Train library when validating resources or pass it through to Core?

**Comment by amogkam** [comment]
Seems like we should pass this along to Core so we have consistent handling for this.
