### ISSUE TITLE
Is it still not supported on the Windows platform?

### ISSUE THREAD

**Issue by msw0126** [ray-project/ray#3106]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by robertnishihara** [comment]
That's correct. Let's consolidate the discussion on #631.

**Comment by robertnishihara** [comment]
For anyone interested in trying out Ray on Windows, we have experimental support now (at least for Ray core and some (but not all) of the libraries).

You can try the nightly wheels at https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies.

**Comment by mehrdadn** [comment]
Please see [#631](/ray-project/ray/issues/631#issuecomment-648980254) for recent updates on Windows support!
