### ISSUE TITLE
[AIR/docs] Extend Checkpoint section in AIR key concepts

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#31065]
### Description

Checkpoint section in AIR key concepts should be extended to showcase common operations, such as getting the best checkpoint in result, getting the best checkpoint in the experiment, setting checkpoint config. Alternatively, we should add links to more detailed guides.

See https://discuss.ray.io/t/lightning-early-stopping-of-training-in-tune/8469/4 for an example of this documentation gap in action

### Link

https://docs.ray.io/en/master/ray-air/key-concepts.html

**Comment by justinvyu** [comment]
We have since added new user guides for using checkpoints.
