### ISSUE TITLE
[CI] `linux://python/ray/workflow:tests/test_basic_workflows_2` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#31090]
- 8e9fa223d35ec87fd33a8eb0fe706bc6a77dcf23 FAILED [Buildkite Workflow tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1512#01850d84-74c5-40bb-b24d-53a3719dda83)
- 5d60627e8be6123ef677c4a80cc03c675361f650 FAILED [Buildkite Workflow tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1474#0184f587-195a-441f-881b-92bec41ab8dc)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/workflow:tests/test_basic_workflows_2-END
....

**Comment by rickyyx** [comment]
Is this being worked on?
