### ISSUE TITLE
[docs] Improving the quality of search

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#31094]
### Description

_This is a starter issue for tracking our search quality on our documentation._

Right now it's very hard to find information on the documentation. The search bar is unfortunately pretty hard to use -- 

for example, in this search for "num_gpus", ideally the top result is for Ray Core, but in these search results unfortunately Ray core doesn't even show up.

<img width="445" alt="Screen Shot 2022-12-14 at 12 05 56 AM" src="https://user-images.githubusercontent.com/4529381/207540091-3480c9f1-0453-4b1b-ae08-0a270157ef55.png">

cc @ericxgao 
cc @maxpumperla

**Comment by richardliaw** [comment]
Another great example:

<img width="926" alt="Screen Shot 2023-01-11 at 2 49 47 PM" src="https://user-images.githubusercontent.com/4529381/211934847-06af170e-ee2e-4d3e-abe9-2ce49e68e707.png">

what i want is literally the very last result
<img width="713" alt="Screen Shot 2023-01-11 at 2 49 59 PM" src="https://user-images.githubusercontent.com/4529381/211934870-b5b8f7ce-6d02-4cc7-aa66-9dbb15b64eee.png">

**Comment by cadedaniel** [comment]
<img width="795" alt="Screen Shot 2023-01-12 at 4 11 38 PM" src="https://user-images.githubusercontent.com/950914/212207542-82aea191-76c8-46f8-bd37-f89ada4d0cd0.png">

**Comment by richardliaw** [comment]
@angelinafromanyscale

**Comment by angelinalg** [comment]
Can we somehow address this in the efforts that @maxpumperla is kicking off for 2.3?

**Comment by maxpumperla** [comment]
@angelinalg yes, the idea is to use this issue to collect problems and address them in the initiative, if possible.

**Comment by richardliaw** [comment]
This is mostly fixed!!!
