### ISSUE TITLE
[Tune] Logging error: ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by jbedorf** [ray-project/ray#31096]
### What happened + What you expected to happen

When using the Tune option `log_to_file=True` you will get a ValueError when one of your dependencies also modifies the basic Python logging infrastructure. In the particular example the error here is caused by the usage of MLflow. The error only occurs when you are initializing Ray in one file and have the Trainable in another file. Likely due to the way the imports work.

The solution would be to modify the function [here](https://github.com/ray-project/ray/blob/ray-2.2.0/python/ray/tune/utils/util.py#L257) into something like the below (and similar for the other functions such as seek and flush):

```
    def write(self, *args, **kwargs):
        for s in [self.stream1, self.stream2]:
            try:
                 s.write(*args, **kwargs)
            except ValueError:
                 pass
```

This is the same error as in #29080, with the difference that in this case I as end-user have no control over the library that causes this.

Example output on failure:
```
(TrainTrainable pid=26701)   File "/home/user/miniconda3/envs/ray/lib/python3.8/site-packages/ray/tune/utils/util.py", line 269, in write
(TrainTrainable pid=26701)     self.stream1.write(*args, **kwargs)
(TrainTrainable pid=26701) ValueError: I/O operation on closed file.
```
(TrainTrainable pid=26043)   File "/home/jbedorf/miniconda3/envs/deepsim/lib/python3.8/site-packages/ray/tune/utils/util.py", line 264, in write
(TrainTrainable pid=26043)     s.write(*args, **kwargs)
(TrainTrainable pid=26043) ValueError: I/O operation on closed file.

### Versions / Dependencies

Ray 2.2 / Python 3.8 / Linux / MLflow 1.27

### Reproduction script

The script has to be in two parts, otherwise the bug does not get triggered. Note that this example does not do anything, apart from triggering the bug. It is as simplified as possible to ensure the bug gets triggered.

file1.py
```
import ray
import file2

ray.init(ignore_reinit_error=True)
file2.TunerAIR()
```

file2.py
```
from ray.air.config import RunConfig, ScalingConfig
from ray.train.tensorflow import  TensorflowTrainer
from ray.tune.tuner import Tuner

# Note that in real world applications this would be import mlflow 
from mlflow.utils.logging_utils import _configure_mlflow_loggers
_configure_mlflow_loggers(root_module_name=__name__)

class TunerAIR:

    def train_func(self) -> None:
        pass

    def __init__(self):
        def train_loop(config) -> None:
            self.train_func()  # Without this the error does not occur

        trainer = TensorflowTrainer(
            train_loop_per_worker=train_loop,
            scaling_config=ScalingConfig(num_workers=1),
        )

        Tuner(trainable=trainer, run_config=RunConfig(log_to_file=True)).fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
Hey @jbedorf did some initial investigation and I think it may be the same issue as https://github.com/mlflow/mlflow/issues/4957, with mlflow prematurely closing handlers.

If I move the mlflow configuration to after Tuner instantiation, then I no longer get the issue.

```python
def train_loop(config) -> None:
    self.train_func()  # Without this the error does not occur

trainer = TensorflowTrainer(
    train_loop_per_worker=train_loop,
    scaling_config=ScalingConfig(num_workers=1),
)

tuner = Tuner(trainable=trainer, run_config=RunConfig(log_to_file=True))

from mlflow.utils.logging_utils import _configure_mlflow_loggers
_configure_mlflow_loggers(root_module_name=__name__)

tuner.fit()
```

**Comment by amogkam** [comment]
Going to close this for now, but please re-open if this is still an issue for you.

**Comment by jbedorf** [comment]
Hi @amogkam, thanks for looking into this. I think this is still a problem, your solution works on this toy example because it is a simplified version of the real application. In the real world I can't move those mlflow imports because they are an inherent part of the import and usage stack of mlflow (and actually take place much deeper in the execution).  The mlflow issue is over a year old so that clearly is not trivial to solve. 

It would make more sense to apply the fix that I outlined in the original post to the Ray stack to at least prevent these type of issues from crashing the whole execution stack. Especially given that there are many other libraries that also interact with the logging system that could be affected by this.

I'm happy to supply the PR for this to make Tune more stable if you think it will be merged.

**Comment by amogkam** [comment]
Got it, thanks for the explanation @jbedorf. That plan sounds good, a PR would be much appreciated!
