### ISSUE TITLE
[tune] Tensorboard

### ISSUE THREAD

**Issue by nrudakov** [ray-project/ray#31103]
### Description

Ray[tune] is using tensorboardX as a dependency. TensorboardX [requires](https://github.com/lanpa/tensorboardX/blob/9356270bce9e9d7e4f4ecedc85931b89f19a8a14/setup.py#L46) protobuf<=3.20.1
The latest version of onnx (1.13.0) [requires](https://github.com/onnx/onnx/blob/45f508bb7c3206cf504b923d54076e42d1ed591c/requirements.txt#L2) protobuf>=3.20.2
Therefore, it is impossible to use ray[tune] in the same environment with latest onnx.

### Use case

Suggestion is to switch from [tensorboardX](https://github.com/lanpa/tensorboardX) to [tensorboard](https://github.com/tensorflow/tensorboard) to be able to use [onnx](https://github.com/onnx/onnx) and ray[tune] in the same environment.

**Comment by amogkam** [comment]
Thanks for raising this @nrudakov! Do you get an error when trying to use onnx with ray tune? If so, could you share the stack trace?

**Comment by amogkam** [comment]
Got it yeah, pip will complain, but there might not be any actual errors during usage. Your script may still work despite this incompatibility.

Sometimes these requirements are not as strict in practice.

**Comment by nrudakov** [comment]
Pytorch-Lightning recently switched from tensorboard to tensorboardx [https://github.com/Lightning-AI/lightning/pull/15728](https://github.com/Lightning-AI/lightning/pull/15728)
So probably it makes sense to stay on tensorboardx. I'm closing this issue.
