### ISSUE TITLE
[Datasets] NumPy batch is significantly slower than Pandas batch in `map_batches` benchmark

### ISSUE THREAD

**Issue by c21** [ray-project/ray#31108]
### What happened + What you expected to happen

From https://github.com/ray-project/ray/pull/30961, found an edge case that NumPy batch is significantly slower than Pandas batch in `map_batches`.

```
ds = ray.data.read_parquet("s3://air-example-data/ursa-labs-taxi-data/by_year/2018/01")
batch_format = "numpy"
batch_size = 1024
ds = ds.map_batches(lambda ds: ds, batch_format=batch_format, batch_size=batch_size).map_batches(lambda ds: ds, batch_format=batch_format, batch_size=batch_size)
```

```
Running case: map-batches-numpy-1024-2-default
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:20<00:00, 20.88s/it]
Map_Batches: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [03:41<00:00, 110.81s/it]
Result of case map-batches-numpy-1024-2-default: {'time': 242.49983909800176}
Running case: map-batches-numpy-1024-2-lazy
Read->Map_Batches->Map_Batches: 100%|████████████████████████████████████████████████████| 1/1 [06:27<00:00, 387.63s/it]
Result of case map-batches-numpy-1024-2-lazy: {'time': 387.6311392719999}

Running case: map-batches-pandas-1024-2-default
Read->Map_Batches: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:48<00:00, 48.53s/it]
Map_Batches: 100%|████████████████████████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.36s/it]
Result of case map-batches-pandas-1024-2-default: {'time': 60.341881523001575}
Running case: map-batches-pandas-1024-2-lazy
Read->Map_Batches->Map_Batches: 100%|█████████████████████████████████████████████████████| 1/1 [01:35<00:00, 95.88s/it]
Result of case map-batches-pandas-1024-2-lazy: {'time': 95.88174996099951}
```

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by cadedaniel** [comment]
What's the status here? Is someone actively working on this?

**Comment by c21** [comment]
Removed as a release blocker for Ray 2.3, as this is not a new regression. Will continue debugging this after Ray 2.3.

**Comment by c21** [comment]
cc @yanxiaod123 to subscribe here, thanks.

**Comment by ericl** [comment]
This is pretty noticeable in benchmarks, though mitigated with higher levels of prefetching:
![Ingest_ Batch Formats and Prefetching (10x g4dn 4xl)](https://user-images.githubusercontent.com/14922/228404328-03c92a3a-d620-40d1-8606-d319dda2a959.png)

**Comment by yanxiaod123** [comment]
When ds.iter_batches, I tried to add different prefetch parameters, but it didn't work. I understand that prefetch is for getting ref objects, it doesn't work for memory copy.  [https://github.com/ray-project/ray/issues/33325](#33325)

**Comment by c21** [comment]
FYI the nightly test benchmark is `ray/release/nightly_tests/dataset/map_batches_benchmark.py`

**Comment by jjyao** [comment]
For eager mode:

The slowness is due to the second `map_batches`. One thing I found is that the first `map_batches` generates different number of output blocks depending on the batch_format (pandas generates 6 while numpy generates 2). Seems numpy format doesn't support dynamic block splitting.
