### ISSUE TITLE
[Dashboard] Better error message when stacktrace/flamegraph is not available.

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#31109]
### What happened + What you expected to happen

The error message when flamegraph is not available is confusing.

1. Create some actors
```
import ray
@ray.remote
class Foo:
    def ping(self):
        return 1

f = Foo.remote()
pings = [f.ping.remote() for _ in range(100)]
```

2. Click flame graph
![image](https://user-images.githubusercontent.com/9677264/207693931-9fbb3435-0e6b-4387-ba04-ad8dcd9a1cbc.png)

3. See this error message
```
Failed to execute `sudo -n $(which py-spy) record -o /tmp/ray/session_2022-12-13_23-03-10_714589_166/logs/flamegraph_6483_cpu_profiling.svg -p 6483 -d 5 -f flamegraph`.

Note that this command requires `py-spy` to be installed with root permissions. You
can install `py-spy` and give it root permissions as follows:
  $ pip install py-spy
  $ sudo chown root:root `which py-spy`
  $ sudo chmod u+s `which py-spy`

Alternatively, you can start Ray with passwordless sudo / root permissions.

=== stdout ===
py-spy> Sampling process 100 times a second for 5 seconds. Press Control-C to exit.



=== stderr ===
[2022-12-14T07:27:26.459031825Z ERROR inferno::flamegraph] No stack counts found
Error: Failed to write flamegraph: I/O error: No stack counts found
```

### Versions / Dependencies

Ray 2.2

### Reproduction script

See above

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
Btw, this is the py-spy error that happens when the process is idle https://github.com/benfred/py-spy/issues/321#issuecomment-731848950

Not sure what's the best way to improve this... maybe we can have additional string to explain it

**Comment by scottsun94** [comment]
The most confusing part is this:

> Note that this command requires `py-spy` to be installed with root permissions. You
> can install `py-spy` and give it root permissions as follows:
>   $ pip install py-spy
>   $ sudo chown root:root `which py-spy`
>   $ sudo chmod u+s `which py-spy`
> 
> Alternatively, you can start Ray with passwordless sudo / root permissions.

It makes people think that they may not have py-spy installed and ignore the real error messages in the stdout/stderr below

**Comment by alanwguo** [comment]
@rkooo567 @scottsun94 

I just tried running py-spy without permissions on both ubuntu and mac osx and it already gives this message:
```
Permission Denied: Try running again with elevated permissions by going 'sudo env "PATH=$PATH" !!'
```

Given that, should we just remove this note entirely?
