### ISSUE TITLE
[RLlib]  tune.uniform() doesnot work in AlgorithmConfig.training() after update to 2.2.0

### ISSUE THREAD

**Issue by james116blue** [ray-project/ray#31138]
### What happened + What you expected to happen
Error in version 2.2.0.

> in PPOConfig.training(self, lr_schedule, use_critic, use_gae, lambda_, kl_coeff, sgd_minibatch_size, num_sgd_iter, shuffle_sequences, vf_loss_coeff, entropy_coeff, entropy_coeff_schedule, clip_param, vf_clip_param, grad_clip, kl_target, vf_share_layers, **kwargs)
>     201 if isinstance(entropy_coeff, int):
>     202     entropy_coeff = float(entropy_coeff)
> --> 203 if entropy_coeff < 0.0:
>     204     raise ValueError("`entropy_coeff` must be >= 0.0")
>     205 self.entropy_coeff = entropy_coeff
> 
> TypeError: '<' not supported between instances of 'Float' and 'float'

In version 2.1.0 works perfectly

### Versions / Dependencies

Ray 2.2.0
python 3.8
Linux 

### Reproduction script

from ray.rllib.algorithms.ppo import PPOConfig, PPO
from ray import air
from ray import tune

config = PPOConfig()
config.training( 
     entropy_coeff=tune.uniform(0, 1),
 )
### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @james116blue ,

Changed to repro script to the following:

```
from ray.rllib.algorithms.ppo import PPOConfig
from ray import tune

PPOConfig().training(
lr=tune.randn(0.001, 0.0001),
)
```

Could not reproduce with that.

**Comment by james116blue** [comment]
Hi  @ArturNiederfahrenhorst,
thank you for your replay, but problem in line
`entropy_coeff=tune.uniform(0, 1),`

I update code in my issue

**Comment by ArturNiederfahrenhorst** [comment]
Hi @james116blue ,

You can't use tune like that.
RLlib does not know how to tune hyper parameters itself.
You can use these as part of tune.Tuner or tune.run.
Sorry for the confusion here 🙂
