### ISSUE TITLE
[CI] `bk://:book: LinkCheck` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#31137]
Seems this link is no longer there

https://github.com/ray-project/ray/tree/master/rllib/contrib/random_agent/random_agent.py

- 22af73253cd48fa134aee33c145b541c99acdc8b FAILED [:book: LinkCheck](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1537#0185167c-1765-4687-8281-9eb8bbe6b531)
- 64d744b4750b749cede563b04c5d32396470a236 FAILED [:book: LinkCheck](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1536#0185162e-32d5-4155-86a3-766485d3e00d)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:book: LinkCheck-END
....

**Comment by avnishn** [comment]
https://github.com/ray-project/ray/commit/6a01f2937bb9dab00eb5de394d6ba1cd49a6d044

looks like sven fixed

**Comment by clarng** [comment]
Failing again

https://buildkite.com/ray-project/oss-ci-build-branch/builds/2091#018608ae-a498-4ba6-bfbf-bdd11f3bf61e

**Comment by clarng** [comment]
This link seems to start failing?

(ray-overview/index: line   21) broken    https://www.kdnuggets.com/2019/11/speed-up-pandas-4x.html - 403 Client Error: Forbidden for url: https://www.kdnuggets.com/2019/11/speed-up-pandas-4x.html

**Comment by ArturNiederfahrenhorst** [comment]
This breaks frequently. I will unassign myself and close.
Latest fix: https://github.com/ray-project/ray/pull/32442

**Comment by rickyyx** [comment]
Looks like `tune/examples/tune-xgboost` has been breaking the linter check consistently?
