### ISSUE TITLE
[Core] The get_object_locations() not returning the node id

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#31144]
On master branch, running the following:
```
import ray

ds = ray.data.read_csv("s3://anonymous@air-example-data/iris.csv").fully_executed()

blocks = ds.get_internal_block_refs()
ray.wait(blocks, num_returns=len(blocks), fetch_local=False)
location_data = ray.experimental.get_object_locations(blocks)

print("ds location:", location_data)
```
It has:
`ds location: {ObjectRef(32d950ec0ccf9d2affffffffffffffffffffffff0100000002000000): {'node_ids': [], 'object_size': 7041}}`

**Comment by rkooo567** [comment]
maybe it is not in a plsma store but in a memory store since the size of object is small?

**Comment by rkooo567** [comment]
(object less than 100KB is not in plasma store)
