### ISSUE TITLE
[<Ray : Core>] Is it possible to provide a cmake template about CPP

### ISSUE THREAD

**Issue by EnjianGong** [ray-project/ray#31153]
### Description

I have a cmake project about MIP, so I need to use ray according to cmake, but after transforming it into cmake according to bazel, an exception as shown in the figure is thrown
![ray-cmake](https://user-images.githubusercontent.com/112852312/208091177-104c6cf0-5fd7-43b9-aead-3b8ed57ee638.PNG)

```
project(ray_cmake)
cmake_minimum_required(VERSION 3.9)
set(CMAKE_CXX_STANDARD 17)
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
 
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include)
add_executable(example example.cc) 
target_link_libraries(example ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lib/libray_api.so)
```

**Comment by EnjianGong** [comment]
`
project(ray_cmake)
cmake_minimum_required(VERSION 3.24)

set(CMAKE_CXX_STANDARD 17)
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

#link_directories(${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lib/libray_api.so)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include)

add_library(example SHARED ${CMAKE_CURRENT_SOURCE_DIR}/example.cc)
target_link_libraries(example ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lib/libray_api.so)
add_executable(main ${CMAKE_CURRENT_SOURCE_DIR}/example.cc)
target_link_libraries(main ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/lib/libray_api.so)
`

**Comment by EnjianGong** [comment]
`./main  --ray_code_search_path=example.so`

**Comment by cemlyn007** [comment]
Thank you for figuring this out and sharing it! Note that at runtime you guys might also need to add the directory for where to find `libray.so` to the environment variable `DYLD_LIBRARY_PATH` if you are on Mac.
