### ISSUE TITLE
IAM roles not being set for workers

### ISSUE THREAD

**Issue by npyoung** [ray-project/ray#3115]
It seems like the head node in an EC2 cluster gets assigned to a IAM role that lets it access all EC2 and S3 functionality, but the worker nodes do not. This prevents tasks that require direct S3 access from running on the worker nodes unless a `.aws/credentials`, `.boto` config, or other authentication method is synced up to the cluster.

It's a small thing, but it would be nice to just rely on the IAM roles to take care of S3 access. One less configuration to worry about.

### System information
- **OS Platform and Distribution**: Ubuntu 16.04 (EC2 Deep Learning AMI)
- **Ray installed from**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6

### Steps to reproduce
```ray up <my config.yaml> --num-workers 2```
Observe that worker nodes are not assigned a IAM role in the EC2 dashboard.

**Comment by ericl** [comment]
@npyoung it would be great if you could try out this patch: https://github.com/ray-project/ray/pull/3118

**Comment by npyoung** [comment]
Works for me, thanks!

**Comment by richardliaw** [comment]
Since we're reverting #3118 we should probably reopen this issue

**Comment by dekromp** [comment]
Hi,
is there any recommended solution to automate the e.g. S3 access of the workers yet?

**Comment by richardliaw** [comment]
A couple workarounds is to provide your security credentials via env var when you start the ray process or (in the very extreme), uploading an AWS credential file.

I couldn't figure out how to enable the Head Node to grant S3 access to the workers. 

For now, the above should work.

**Comment by kshuggins** [comment]
as an aside, for future users. 

using the default IAM role creation that ray uses doesn't permit IAM role pass through. So you can't just specify the correct Arn in the yaml config ( unless I seriously borked something ).

You also have to specify a permissions policy to permit it:
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::<role-to-constrain-it-to>*"
        }
    ]
}
```
