### ISSUE TITLE
[docs] Add a framework-centric overview 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#31150]
### Description

After talking to @pangw and @swaroopch today, both gave the feedback that our documentation is too "engineer-centric" and rather we should think about meeting the data scientist where they are.

Specifically, they suggested that we need to provide a "framework-centric" index for our documentation. For example,

* If I am a Pytorch user:
  * Here is how I scale my model training with Ray and Pytorch
  * Here is how I scale my model tuning with Ray and Pytorch
  * Here is how I scale my model serving with Ray and Pytorch

* If I am a Tensorflow user:
  * Here is how I scale my model training with Tensorflow
  * Here is how I scale my model tuning with Tensorflow
  * Here is how I scale my model serving with Tensorflow

They both mentioned that the Pandas -> Modin (scalable pandas) positioning was really easy for data scientists to understand, whereas for Ray it was harder for the data scientist to map.

cc @anabranch @maxpumperla @zhe-thoughts @ericl

**Comment by Wendi-anyscale** [comment]
Our previous study user data also support this! 
1 specific finding on their behavior: they always try to find which Ray API is the mirror version of PyTorch/TensorFlow(concept they are familiar with)
