### ISSUE TITLE
ray 2.0.0.dev0[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by aa-oo** [ray-project/ray#31151]
### Description

Hellow,i'm sorry to bother you.I want to use ray 2.0.0.dev0.But I don't know where I can find it.There is only version ray 3.0.0.dev0 in the documentation.Can you tell me where i can get it,thanks!

**Comment by sven1977** [comment]
Hey @aa-oo , thanks for filing this issue.
* All versions that have the "dev" in them are referring to the master branch (at that time). The current master branch version is called "3.0.0.dev0".
* To get a stable version of Ray, you can simply try `pip install ray==2.2` (brand new one) or some older versions like `pip install ray==2.1` or `pip install ray==2.0`.
