### ISSUE TITLE
Add Subscribe Ray newsletter to Ray docs 

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#31163]
### Description

- [ ] _Add_ Newsletter|Subscribe 

<img width="803" alt="Screen Shot 2022-12-16 at 11 19 14 AM" src="https://user-images.githubusercontent.com/97252176/208185935-c215b5fe-1e5d-4902-b293-248fa4f64439.png">

- [ ] _Add_ 📰 Subscribe Newsletter: Get the latest news from Ray in a monthly email: Ray updates, community highlights, events, useful tutorials, and more!
<img width="775" alt="Screen Shot 2022-12-16 at 11 20 11 AM" src="https://user-images.githubusercontent.com/97252176/208185944-d9b032ef-419d-40b4-901e-910973083153.png">

Subscribe link: https://share.hsforms.com/1Ee3Gh8c9TY69ZQib-yZJvgc7w85

### Link

https://docs.ray.io/en/latest/

**Comment by pcmoritz** [comment]
Great idea, I'm happy to make a PR for this -- do you have a particular emoji in mind you want for that entry?

Or any particular wording?

```
Subscribe to the Ray Newsletter: Learn about what is new in Ray -- the latest developments, user stories and events.
```

**Comment by Wendi-anyscale** [comment]
📰 Subscribe to the Ray Newsletter: Learn about what is new in Ray -- the
latest developments, user stories and events. 👆 like this!
