### ISSUE TITLE
[RLlib] Incompatibility of `AlgorithmConfig` and tune search APIs (after update to 2.2.0): Move all config checks into `AlgorithmConfig.validate` instead.

### ISSUE THREAD

**Issue by james116blue** [ray-project/ray#31174]
### What happened + What you expected to happen

When you try to define search space for _entropy_coeff_ in _PPOConfig_ with uniform distribution (_tune.uniform_):
```
config.training( 
   entropy_coeff=tune.uniform(0.0, 1.0), #<----this line gives error
)
```
you will get this next error
`TypeError: '<' not supported between instances of 'Float' and 'float'`

### Versions / Dependencies

Ray 2.2.0
Pytorch 1.13
python 3.8
Linux

### Reproduction script

```
from ray.rllib.algorithms.ppo import PPOConfig, PPO
from ray import air
from ray import tune

config = PPOConfig()
config.training(  # doctest: +SKIP
     entropy_coeff=tune.uniform(0.0, 1.0), #<----this line gives error
 )
config = config.environment(env="CartPole-v1")
config = config.framework("torch")

results = tune.Tuner(
    "PPO",
    run_config=air.RunConfig(stop={"training_iteration": 5}),
    tune_config=tune.TuneConfig(
        num_samples=5
    ),
    param_space=config.to_dict(),
).fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Hey @james116blue , thanks for raising this issue! This is actually a high-prio bug that we'll need to fix asap. :)
In the meantime, as a quick workaround, simply comment out the failing if-block checks and things should work fine. The actual solution will be for us to move all checks (even the simpler ones, like this one here) into the `validate` methods of the different AlgorithmConfigs. This way, only already resolved tune objects will be passed in.

**Comment by cwenner** [comment]
Thanks for this rapid development and fixes! Also ran into this problem
