### ISSUE TITLE
[job submission] Add driver exit code in JobInfo

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#31183]
### Description

The query result of jobs through job submission api `curl 'http://0.0.0.0:8266/api/jobs/'` looks like:

```json
  {
    "type": "SUBMISSION",
    "entrypoint": "python3.9 case1.py",
    "job_id": "02000000",
    "submission_id": "raysubmit_tndCXjZtTT13X7jD",
    "driver_info": {
      "id": "02000000",
      "node_ip_address": "127.0.0.1",
      "pid": "94633"
    },
    "status": "SUCCEEDED",
    "message": "Job finished successfully.",
    "error_type": null,
    "start_time": 1671433867107,
    "end_time": 1671434381364,
    "metadata": {},
    "runtime_env": {
      "working_dir": "gcs://_ray_pkg_1c2d7859d752eb23.zip",
      "env_vars": {
        "RAY_BACKEND_LOG_LEVEL": "debug"
      }
    }
  }
```

In our use case, ray job users want to obtain the driver's exit code which represents the actual exit reason of the job. For example, the driver process exit with code 100, which means OOM occurs in the job.

However, the existing query result from job submission api is lack of driver exit code. 

There are maybe two possible solutions：
1. add driver exit code field in JobInfo
2. reuse the existing `message` field, but need to make it structured, currently it is just a string that contains part of the job log

I'm glad to submit a PR if the feature makes sense.

**Comment by MissiontoMars** [comment]
@alanwguo @architkulkarni Please evaluate whether this feature makes sense.

**Comment by rkooo567** [comment]
I'd love to shepherd the PR if you submit one @MissiontoMars
