### ISSUE TITLE
[Datasets] Audit all code paths to use `np.array(dtype=object)` for ragged ndarrays

### ISSUE THREAD

**Issue by c21** [ray-project/ray#31182]
### What happened + What you expected to happen

NumPy is deprecating the implicit creation of ragged ndarrays with the np.array() constructor; now creating ragged ndarrays requires a dtype=object to be passed. This deprecation will now raise an error in the 1.24 release (released today), so we should do a quick audit of where we might be hit by this, and port to a more explicit ragged tensor construction.

https://github.com/numpy/numpy/pull/22004
https://github.com/numpy/numpy/releases/tag/v1.24.0

### Versions / Dependencies

master

### Reproduction script

as above

### Issue Severity

High: It blocks me from completing my task.

**Comment by cadedaniel** [comment]
I think there's more than just `dtype=object`, I also saw failures like `AttributeError: module 'numpy' has no attribute 'long'` and ` AttributeError: module 'numpy' has no attribute 'int'` in https://github.com/ray-project/ray/issues/31194 and https://github.com/ray-project/ray/issues/31193
