### ISSUE TITLE
[CI] `windows://python/ray/tests:test_numba` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#31193]
- 49b1ed180d0447bcfd82d819bc1d37ef024afbab FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1591#01852ac1-d82b-403a-84c9-bcf66e8b0f2c)
- 9bb62fbe30910078885faaf51b9172a1042e9117 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1590#01852a63-93b9-4e20-9f12-be23457fb417)
- d28552b7b61b4ba74563d7710fdd6b5562fe73a2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1589#01852a62-baeb-4ebd-b955-3b2daba42b3a)
- 608276bb96b5b49769cd8816414c280c5431d843 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1588#01852a5b-f1f3-49c5-bf91-72b9be8f9253)
- c03c4c67182d7f79d36465f2ffbef88b2b958afb FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1587#01852a30-52c8-4cca-93c7-590cc27d4acd)
- 24b6a8035aa2afac641024d4d6664b6c066f6d20 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1586#01852a25-8d20-4a73-8d6f-2a0350b7908f)
- 70b0d039da09cb35f5b4584e5a9603643cf29757 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1585#01852a24-6506-4d23-af8e-d6459c7ce41e)
- 98fef7732852cdb3e9377cd87c1ee1085b894928 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1584#018529b1-d575-4051-8dc7-2d023a28d8d0)
- 69b2506c281c777c44980c376497bc2a8d2ad051 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1583#018529b1-9831-4a55-a797-613abb294a97)
- 8f499013de9c7beaf7bf5537a70aaa8bf0322203 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1582#018528ce-12a0-43fb-9d9b-bc3182fafeb8)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_numba-END
....

**Comment by clarng** [comment]
\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_0v14o9j3\runfiles\com_github_ray_project_ray\python\ray\tests\test_tensorflow.py:124:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | c:\install\ray\python\ray\experimental\tf_utils.py:142: in set_flat
  | arrays = unflatten(new_weights, shapes)
  | c:\install\ray\python\ray\experimental\tf_utils.py:15: in unflatten
  | size = np.prod(shape, dtype=np.int)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | attr = 'int'
  |  
  | def __getattr__(attr):
  | # Warn for expired attributes, and return a dummy function
  | # that always raises an exception.
  | import warnings
  | try:
  | msg = __expired_functions__[attr]
  | except KeyError:
  | pass
  | else:
  | warnings.warn(msg, DeprecationWarning, stacklevel=2)
  |  
  | def _expired(*args, **kwds):
  | raise RuntimeError(msg)
  |  
  | return _expired
  |  
  | # Emit warnings for deprecated attributes
  | try:
  | val, msg = __deprecated_attrs__[attr]
  | except KeyError:
  | pass
  | else:
  | warnings.warn(msg, DeprecationWarning, stacklevel=2)
  | return val
  |  
  | if attr in __future_scalars__:
  | # And future warnings for those that will change, but also give
  | # the AttributeError
  | warnings.warn(
  | f"In the future `np.{attr}` will be defined as the "
  | "corresponding NumPy scalar.  (This may have returned Python "
  | "scalars in past versions.", FutureWarning, stacklevel=2)
  |  
  | # Importing Tester requires importing all of UnitTest which is not a
  | # cheap import Since it is mainly used in test suits, we lazy import it
  | # here to save on the order of 10 ms of import time for most users
  | #
  | # The previous way Tester was imported also had a side effect of adding
  | # the full `numpy.testing` namespace
  | if attr == 'testing':
  | import numpy.testing as testing
  | return testing
  | elif attr == 'Tester':
  | from .testing import Tester
  | return Tester
  |  
  | >       raise AttributeError("module {!r} has no attribute "
  | "{!r}".format(__name__, attr))
  | E       AttributeError: module 'numpy' has no attribute 'int'
 

<br class="Apple-interchange-newline">

**Comment by cadedaniel** [comment]
I have a PR to limit numpy to 1.24 as a short-term fix. There's some suggestion to instead remove the offending tests temporarily and fix the Ray Data usage of the broken APIs from @ericl. I don't have context on how difficult this is, so I am going to assign this to the current Data oncall cc @c21 .

**Comment by krfricke** [comment]
This has been fixed by #31394
