### ISSUE TITLE
[Dashboard] Link to view node's logs are broken

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#31196]
### What happened + What you expected to happen

- I am running ray locally via Python in Terminal. When I go to the logs page in the Ray Dashboard, I see one node with a link to view its logs. However, the actual log link is broken:
<img width="861" alt="Screenshot at Dec 19 12-48-49" src="https://user-images.githubusercontent.com/5122851/208521580-13c377a3-afe6-4035-b0b9-f623e93367c0.png">

I am currently able to get around this by instead navigating to the `Nodes` page, then clicking on the link in the `Logs` column:
<img width="1303" alt="Screenshot at Dec 19 12-52-48" src="https://user-images.githubusercontent.com/5122851/208521848-4b44172b-81cb-4b4a-8504-26aa3e566292.png">

### Versions / Dependencies

Ray: master
Python: 3.8.13

### Reproduction script

```
>>> import ray
>>> ray.init()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
Thanks for reporting! @scottjlee I believe this is related to this PR: https://github.com/ray-project/ray/pull/30824

This should be fixed asap. cc: @alanwguo @rkooo567

**Comment by alanwguo** [comment]
@scottjlee , is this still happening to you? I can't repro this right now

**Comment by scottjlee** [comment]
@alanwguo I just pulled master, rebuilt with `pip install -ve .`, and I'm seeing the same issue as above.
```
import ray
ray.init()
```

**Comment by alanwguo** [comment]
Confirmed that this is just an issue with scott's local environment. He had an outdated build of the frontend UI.
