### ISSUE TITLE
[CI] `linux://doc/source/ray-air/examples:upload_to_comet_ml` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31210]
- c2f6a70ba1f8c9e86bcf725ea2b7134ae2538baf FAILED [Buildkite :book: Doc examples with authentication ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1597#01852c94-669c-4019-b3bc-487e0ad5fcaf)
- f17375d3b4b4ee1e0d71267caf0e542e59e4ddf0 FAILED [Buildkite :book: Doc examples with authentication ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1596#01852c5e-5b4d-4af9-8c9b-a89ba3e31361)
- c6924372f9e001e43353c9aeb72ec9c3a69c2208 FAILED [Buildkite :book: Doc examples with authentication ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1595#01852c5b-80f0-4a2a-9f94-bb061c0fce18)
- 1bfc05a47a9578bfda341239ecfd9f0ca91cd946 FAILED [Buildkite :book: Doc examples with authentication ](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1594#01852c4e-ea8c-4e18-8374-3abddeba76b8)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc/source/ray-air/examples:upload_to_comet_ml-END
....

**Comment by cadedaniel** [comment]
Looks like some resource in cometml is no longer 'alive'

```


Traceback (most recent call last):
--
  | File "/ray/python/ray/tune/tuner.py", line 272, in fit
  | return self._local_tuner.fit()
  | File "/ray/python/ray/tune/impl/tuner_internal.py", line 432, in fit
  | analysis = self._fit_internal(trainable, param_space)
  | File "/ray/python/ray/tune/impl/tuner_internal.py", line 545, in _fit_internal
  | **args,
  | File "/ray/python/ray/tune/tune.py", line 732, in run
  | runner.step()
  | File "/ray/python/ray/tune/execution/trial_runner.py", line 988, in step
  | self._wait_and_handle_event(next_trial)
  | File "/ray/python/ray/tune/execution/trial_runner.py", line 967, in _wait_and_handle_event
  | raise TuneError(traceback.format_exc())
  | ray.tune.error.TuneError: Traceback (most recent call last):
  | File "/ray/python/ray/tune/execution/trial_runner.py", line 960, in _wait_and_handle_event
  | trial, result[_ExecutorEvent.KEY_FUTURE_RESULT]
  | File "/ray/python/ray/tune/execution/trial_runner.py", line 1048, in _on_saving_result
  | iteration=self._iteration, trials=self._trials, trial=trial
  | File "/ray/python/ray/tune/callback.py", line 325, in on_trial_save
  | callback.on_trial_save(**info)
  | File "/ray/python/ray/tune/logger/logger.py", line 145, in on_trial_save
  | self.log_trial_save(trial)
  | File "/ray/python/ray/air/integrations/comet.py", line 240, in log_trial_save
  | experiment.log_artifact(artifact)
  | File "/opt/miniconda/lib/python3.7/site-packages/comet_ml/_online.py", line 933, in log_artifact
  | "Experiment %r is not alive, cannot log artifact" % self
  | comet_ml.exceptions.ExperimentNotAlive: Experiment <comet_ml._online.Experiment object at 0x7f28e8bc9910> is not alive, cannot log artifact
```

**Comment by amogkam** [comment]
Hmm so seems like something with the networking in our CI or with Comet ML Servers


[COMET ERROR: Run will not be logged](https://www.comet.com/docs/v2/api-and-sdk/python-sdk/warnings-errors/#comet-error-run-will-not-be-logged)
This error is shown with a Python stack trace and indicates that the initial handshake between Comet and the server failed. This is usually a local networking issue or production downtime. Reach out on our [Slack channel](http://chat.comet.ml/) if you encounter this error.

**Comment by amogkam** [comment]
Per the Comet ML Slack, this is a known issue and has been fixed as of an hour ago. CI should start passing soon...I'll make sure to monitor it and will close this issue once it starts passing.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/8068268/208555233-85aa26ce-136a-4882-b057-0c7c5c20f462.png">

**Comment by amogkam** [comment]
This is passing now, going to close
