### ISSUE TITLE
[Datasets] `to_tf` fails when input `feature_columns` is a list of columns names.

### ISSUE THREAD

**Issue by n30111** [ray-project/ray#31229]
### What happened + What you expected to happen

When the input `feature_columns` is a list, it should returns a dictionary. But currently in the code it attempts to returns a set which fails. 

Root cause of this behaviour is this line: https://github.com/ray-project/ray/blob/releases/2.2.0/python/ray/data/dataset.py#L3155

### Versions / Dependencies

Ray: 2.2.0
Python: 3.8
OS: Ubuntu

### Reproduction script

```
import pandas as pd

import ray


df = pd.DataFrame({"X": [0, 1, 2], "Y": [3, 4, 5], "Z": [2,3,4]})
ds = ray.data.from_pandas(df)

ds_tf =ds.to_tf(["X", "Y"], "Z")

batch = next(iter(ds_tf))


print(batch)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Closed by https://github.com/ray-project/ray/pull/31228

**Comment by n30111** [comment]
@amogkam Can we have a patch release with the changes of #31228 , thanks.
