### ISSUE TITLE
Numpy 1.24 Support

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#31246]
## Context

Numpy [1.24.0](https://github.com/numpy/numpy/releases/tag/v1.24.0) was released on 12/18/22 and contains some breaking changes. This ticket tracks the changes needed to ensure Ray is compatible - full compatibility is targeted for the 2.3 release.

**Note:** This version was released for Python 3.8-3.11, so code/tests using an earlier version (i.e. 3.7) will not surface these incompatibilities.

## Failing Tests
- https://github.com/ray-project/ray/issues/31193
- https://github.com/ray-project/ray/issues/31194

## Mitigation
- https://github.com/ray-project/ray/pull/31240

## Fixes
- https://github.com/ray-project/ray/issues/31182 
- https://github.com/ray-project/ray/issues/31258
- https://github.com/ray-project/ray/issues/31277

**Comment by krfricke** [comment]
I think the only remaining issue is #31182. 

1. Why is there no test failing for this?
2. Can we prioritize fixing that?

**Comment by YQ-Wang** [comment]
@matthewdeng I tested Numpy 1.24.2 with Ray 2.4.0 and it seems failed. Do we have a timeline to support this?

**Comment by matthewdeng** [comment]
@YQ-Wang can you share what you're running and what the error you're getting is?

**Comment by YQ-Wang** [comment]
```
module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by matthewdeng** [comment]
@YQ-Wang yes `ray` should be fully compatible with `numpy` 1.24, which is the version contains in the Docker images. As always, it is still possible that other dependencies maybe introduce incompatibilities with `numpy`.

If you run into any issues, please re-open this issue!
