### ISSUE TITLE
Serve|Dashboard: Expose the timestamp for serve deployments

### ISSUE THREAD

**Issue by shawnpanda** [ray-project/ray#31251]
### Description

Request: Expose the timestamp of serve deployments under dashboard agent's api/serve/deployments endpoint.

This is something that is exposed under api/snapshot endpoint for deployments.

Tagging @shrekris-anyscale @alanwguo 

### Use case

I would like to understand the starting and ending time of each serve deployment.

**Comment by shrekris-anyscale** [comment]
Serve 2.x runs deployment graphs as a single unit. Would it be better to use the [`app_status`'s `deployment_timestamp`](https://github.com/ray-project/ray/blob/65d0c0aa48be8f9f7faae857d3ab71444997755a/python/ray/serve/_private/common.py#L42)?

You can get this timestamp from the `/api/serve/deployments/status` endpoint ([endpoint link](https://github.com/ray-project/ray/blob/3a93a81a435eaf133550305afd626125866b4db9/dashboard/modules/serve/serve_agent.py#L77), [status schema link](https://github.com/ray-project/ray/blob/3a93a81a435eaf133550305afd626125866b4db9/python/ray/serve/schema.py#L401)).
cc @edoakes

**Comment by shawnpanda** [comment]
Hey @shrekris-anyscale , I have 2 questions:
1. Is this timestamp guaranteed to exist?
2. If there is a serve update, will this timestamp be updated accordingly?

**Comment by shrekris-anyscale** [comment]
> Is this timestamp guaranteed to exist?

Yes. It gets updated with the current time whenever the user submits a Serve config. If no config has been submitted, this timestamp is `0.0`.

> If there is a serve update, will this timestamp be updated accordingly?

As long as the update is made via config (which is the expected way to deploy deployments in 2.x), the timestamp is updated accordingly. If the update is made using the 1.0 `.deploy()` Python API, the timestamp will not be updated.

**Comment by edoakes** [comment]
Good point @shrekris-anyscale, seems like we're ok to use the existing timestamp
