### ISSUE TITLE
[RLlib] `_check_view_requirement()` does not work with `Dict` space 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#31266]
### What happened + What you expected to happen

# What happened
I am training a policy with `Dict` action space. When running my algorithm I got the following warning: 

```
[-1.13909018 -0.00525073 -1.20116985 -0.13585699 -0.87877417 -0.26143172
 -1.13827956  0.24254586 -1.38049316 -0.59437531  1.          1.
  1.          0.          0.          1.          1.          1.
  0.          1.        ]
 does not match space of view requirements actions.
Provided tensor has shape (20,) and view requirement has shape shape None. Make sure dimensions match to resolve this warning
```
I followed the stack trace up to the `_check_view_requirement()` function that does not account for the `shape` of `Dict` or `Tuple` spaces when comparing the view requirement's space's shape with the data shape. 

# What you expected to happen
That all spaces are covered in the check. 

### Versions / Dependencies

Fedora 37
Python 3.9.4
Ray 2.2.0

### Reproduction script

Use any algorithm with a `Dict` action space (should also occur with a `Dict` obs space). 

### Issue Severity

Low: It annoys or frustrates me.

**Comment by pepi99** [comment]
Also have this problem

**Comment by simonsays1980** [comment]
This should be fixed in the master now

pepi99 ***@***.***> schrieb am Fr. 24. Feb. 2023 um 13:25:
