### ISSUE TITLE
[Datasets] Support arbitrary path parsing in `read_*` functions

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31291]
### Description

Update `ray.data.read_*` functions to support parsing arbitrary data from file paths.

This could look something like this:
```
ray.data.read_images(
    ...,
    path_parser: Callable[[str], dict[str, Any]] | None = None
)
```

### Use case

I'm training an image classifier, and I've encoded labels in the filenames. For example, one image filename is `248394-cat.png`.

Right now I need to use `include_paths` and write an additional UDF to extract this information:

```
dataset = ray.data.read_images(..., include_paths=True)

def parse_label(path: str) -> str:
    filename = Path(path).stem
    image_id, label = filename.split("-")
    return label

def parse_labels(batch: dict[str, np.ndarray]) -> dict[str, np.ndarray]:
    batch["label"] = np.array([parse_label(path) for path in batch["paths"])
    del batch["paths"]
    return batch

dataset = dataset.map_batches(parse_labels, batch_format="numpy")
```

It'd be nice if I could avoid writing a UDF:

```
def parse_path(path: str) -> dict[str, np.ndarray:
    filename = Path(path).stem
    image_id, label = filename.split("-")
    return {"label": label}

dataset = ray.data.read_images(..., path_parser=parse_path)
```

Note that I can't easily achieve this functionality with the `partitioning` parameter, because the partitioning API only supports HIVE and directory-style partitioning.

**Comment by clarkzinzow** [comment]
I think adding this as an option for the `partitioning` parameter makes the most sense, where there's a callable escape hatch.
