### ISSUE TITLE
[Java] ray_dist.jar not included in darwin arm64 whl files

### ISSUE THREAD

**Issue by trsudarshan** [ray-project/ray#31319]
### What happened + What you expected to happen

It seems Ray's .whl file for darwin arm64 is devoid of `jars/ray_dist.jar` while that for darwin x86_64 includes it. Besides, the 'Note' inside [https://docs.ray.io/en/latest/ray-overview/installation.html#install-ray-java-with-maven](https://docs.ray.io/en/latest/ray-overview/installation.html#install-ray-java-with-maven) mentions
```
When you run pip install to install Ray, Java jars are installed as well.
```

If ray_dist.jar is excluded by design, this section of the documentation could be made more specific as well as [https://docs.ray.io/en/latest/ray-overview/installation.html#m1-mac-apple-silicon-support](https://docs.ray.io/en/latest/ray-overview/installation.html#m1-mac-apple-silicon-support) could be updated to call out this exclusion. 
Else, is this something that can be resolved as a good first issue? 
Either way: I would like to help, with some guidance of course. Thank you.  

### Versions / Dependencies

Observed exclusion in at least versions 1.10.0 and 2.x.y. 

### Reproduction script

jar -tvf ray-2.1.0-cp39-cp39-macosx_11_0_arm64.whl | grep ray_dist
jar -tvf ray-2.1.0-cp39-cp39-macosx_10_15_x86_64.whl | grep ray_dist

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by zhe-thoughts** [comment]
Thanks for reporting this @trsudarshan ! Yes indeed if you could help work on this that'd be great.

**Comment by jovany-wang** [comment]
Hi @trsudarshan , as a quick fix, I'd like to fix the doc to tell users that it doesn't include ray_dist.jar for darwin arm64.
And then, as the following up stuff, we should investigate whether there's any issue when we build ray_dist.jar for darwin arm64.

It'll be great that if you help for this issue. I'll help to review and give you some guidelines on Ray Java if you need. Thanks.

**Comment by jovany-wang** [comment]
Hi @trsudarshan ,  any update?

**Comment by zhe-thoughts** [comment]
Gentle ping @trsudarshan . Thanks!

**Comment by jovany-wang** [comment]
Feel free to reopen when it's necessary.

**Comment by trsudarshan** [comment]
@jovany-wang @zhe-thoughts sorry could not get to this sooner since start of 2023. I recently [installed](https://docs.ray.io/en/latest/ray-overview/installation.html#m1-mac-apple-silicon-support) Ray v2.5.1 (Python) and can see `ray_dist.jar` included in the distribution placed in my Python's `site-packages` on my M1 machine. 
Perhaps for older versions where the issue exists, a documentation update would suffice?
