### ISSUE TITLE
[RLlib] Algorithms BC/MARWIL/CQL do support multi-GPU training, but config validation prevents them from running in this setup.

### ISSUE THREAD

**Issue by Emiyalzn** [ray-project/ray#31323]
### Description

In the current document of available RL algorithms, it seems that both BC (torch) and CQL (torch+tf) have supported multi-GPU training. But during training it throws problem "`num_gpus` > 1 not yet supported for CQL!"
I think you'd better modify your documentation, or, is there anyway to train CQL on multi-GPUs (wish to see this lol)?

### Link

https://docs.ray.io/en/latest/rllib/rllib-algorithms.html

**Comment by sven1977** [comment]
Hey @Emiyalzn , thanks for filing this issue! Actually, all these algos (BC, MARWIL, and CQL) do indeed support multi-GPU, but only our config validation method prevents this from working ok (it throughs the reported error). I'll remove these unnecessary checks from the `validate` methods in this PR (https://github.com/ray-project/ray/pull/31393).

In the meantime, please simply comment out these if blocks, e.g.:
```
        if self.num_gpus > 1:
            raise ValueError("`num_gpus` > 1 not yet supported for CQL!")
```
and things should just work.

**Comment by Emiyalzn** [comment]
Thank you! Now I can train my algorithms with multi-gpu smoothly🤩
