### ISSUE TITLE
can you not use python requests lib?

### ISSUE THREAD

**Issue by 8key** [ray-project/ray#3132]
the 'requests' package is dependent on 'chardet' package which is LGPL license. Is it possible to remove this dependence on 'requests'

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by ericl** [comment]
It looks like requests is already a soft import, so we should be good to just remove it from the dep list.

**Comment by ericl** [comment]
Actually, requests is not a ray dependency
```
$ pip show ray
Name: ray
Version: 0.5.3
Summary: UNKNOWN
Home-page: UNKNOWN
Author: None
Author-email: None
License: Apache 2.0
Location: /home/eric/Desktop/ray-private/python
Requires: numpy, funcsigs, click, colorama, pytest, pyyaml, redis, six, flatbuffers
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by richardliaw** [comment]
It is also used in the TuneClient code IIRC, but again, there it is not a
dependency.

**Comment by ericl** [comment]
Since legally it's fine: https://github.com/requests/requests/issues/3389
and we're not actually including it, resolving the issue.

This is the current transitive dep tree of Ray.
```
ray==0.5.3
  - click [required: Any, installed: 6.7]
  - colorama [required: Any, installed: 0.3.8]
  - flatbuffers [required: Any, installed: 2015.12.22.1]
  - funcsigs [required: Any, installed: 1.0.2]
  - numpy [required: Any, installed: 1.15.1]
  - pytest [required: Any, installed: 3.5.0]
    - attrs [required: >=17.4.0, installed: 17.4.0]
    - more-itertools [required: >=4.0.0, installed: 4.1.0]
      - six [required: >=1.0.0,<2.0.0, installed: 1.11.0]
    - pluggy [required: >=0.5,<0.7, installed: 0.6.0]
    - py [required: >=1.5.0, installed: 1.5.3]
    - setuptools [required: Any, installed: 40.4.1]
    - six [required: >=1.10.0, installed: 1.11.0]
  - pyyaml [required: Any, installed: 3.13]
  - redis [required: Any, installed: 2.10.5]
  - six [required: >=1.0.0, installed: 1.11.0]
```

**Comment by 8key** [comment]
Sounds reasonable

thanks
________________________________
