### ISSUE TITLE
[rllib] Add centralized critic docs for multi-agent

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3133]

**Comment by mhauskn** [comment]
@ericl Beyond the snippet in https://ray.readthedocs.io/en/latest/rllib-env.html?highlight=multiagent#implementing-a-centralized-critic, do you have any example scripts showing a centralized critic?

**Comment by ericl** [comment]
I think this PR is a concrete implemention
https://github.com/ray-project/ray/pull/3642
