### ISSUE TITLE
[CI] `linux://python/ray/train:test_base_trainer` is failing/flaky on master.

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31334]
- f40ac957cbd41c4f7b3d999eaa9075119f958881 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1654#01855492-48b3-4415-a78f-1575104acbcb)
- 01b19bafb224ddd2b7cc3aef557274ffb38c9c42 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1652#01854159-f9fe-4bc0-aa6d-0a7ddf718466)
- 37d951ed6bbe5fffd3baf165319550cae3269404 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1649#01853dab-5d0a-41e0-84ba-17f434b1c0a6)
- 4ed12712c4035b316a05b47e0218283cc87b662b FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1643#01853b8d-f1d2-4fb6-bfa3-d8bd37de7073)
- 0cd49130e669b296e3222c2d3eec8162ab34837f FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1636#01853876-0d9e-427b-9695-ac12b968f0d0)
- 7146df617a0dc47bc5a69449a00206e80aceddf7 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1633#0185386b-e006-4eaa-b8f6-26e245ef529e)
- a2634759c5db87d9de4ab02079ceb224be5ac169 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1632#018537fd-fc76-4f21-a557-d14adefba52a)
- 00152a4b4b732d59bd2656480f4dc41f213b1156 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1624#018535b0-3fb5-4153-be66-8940d81f21eb)
- a15037c167f7a9a0d4082075b9871b8baaabad69 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1614#018531b7-1c88-41bf-9af3-baa139f43e10)
- 9b497750c42458364108fa85563cd9028caa3237 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1613#0185319a-a07b-4c26-8b1f-b433d0d25807)
- 88b358486691e20f0ae60eaccfb26c70ed0c0439 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1610#01853102-2620-4fe4-b518-f5f91a98c212)
- 88b358486691e20f0ae60eaccfb26c70ed0c0439 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1610#018530fa-e1fe-463d-8683-a77809ed8a03)
- 1510fb2cd631b2776092fb45ee4082e5e65f16f8 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1607#01853049-1a78-43b8-8e16-7010de06b73d)
- a03a141c296da065f333ea81445a1b9ad49c3d00 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1606#01852fe0-9493-4502-91e5-ff086b31832f)
- 1bfc05a47a9578bfda341239ecfd9f0ca91cd946 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1594#01852c4e-ea27-4ed3-bfd1-78a833baf29d)
- 49b1ed180d0447bcfd82d819bc1d37ef024afbab FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1591#01852ad1-b88b-4bc0-bad4-8c3638b6643a)
- 24b6a8035aa2afac641024d4d6664b6c066f6d20 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1586#01852a33-4080-47d0-95a8-50607ecd160d)
- 80d0bc72f74d84ef3ee097f09797dcc2c4621070 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1571#01851f35-5b3c-42b9-8f07-aa6c53500ee3)
- f4032d7f8446a9c395a3cefc8be8dbc17412d08a FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1568#01851f1b-6725-407b-ad9b-e961676b0719)
- f4032d7f8446a9c395a3cefc8be8dbc17412d08a FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1568#01851f23-22fe-4aea-a35e-d10d869b166c)
- 5d81cf09b1f6125481c6f2e01f92bb0d23599c9f FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1566#01851d8d-cedc-4b13-ab2a-dab927f2af01)
- f8936f9c233abdf5c77894fa27410410c18d1947 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1559#01851b2f-3e37-4771-affa-cb4ad53522c3)
- d7c47425e6173c20a2de3d2e8a2e5d9a2f389b0a FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1553#01851967-a9e6-4f89-94ec-e141bfaa55af)
- 8208e4e9042cf7e9945b34c684112f3b7e8a8cb3 FAILED [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1544#0185180b-1fa2-413e-a526-b62cfd11f788)
- 9a2a742a089b2e8f9b301b4453a56193174e7102 FLAKY [Buildkite :steam_locomotive: Train tests and examples](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1542#01851799-5b64-4250-b5dc-26d3644e2ac9)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/train:test_base_trainer-END
....

**Comment by bveeramani** [comment]
Here's the relevant part of the log:

```
=================================== FAILURES ===================================
__________________________ test_reserved_cpu_warnings __________________________
 
ray_start_4_cpus = RayContext(dashboard_url='127.0.0.1:8265', python_version='3.7.9', ray_version='3.0.0.dev0', ray_commit='{{RAY_COMMIT_...3:62813', 'dashboard_agent_listen_port': 52365, 'node_id': 'b30884dd0998047db0283b31753c2e3ceded2c0be637b6ce93a1d93d'})
mock_tuner_internal_logger = <python.ray.train.tests.test_base_trainer.mock_tuner_internal_logger.<locals>.MockLogger object at 0x7f9140bab590>
 
    def test_reserved_cpu_warnings(ray_start_4_cpus, mock_tuner_internal_logger):
        def train_loop(config):
            pass
 
        # Fraction correctly specified.
        trainer = DummyTrainer(
            train_loop,
            scaling_config=ScalingConfig(num_workers=1, _max_cpu_fraction_per_node=0.9),
            datasets={"train": ray.data.range(10)},
        )
        trainer.fit()
        assert not mock_tuner_internal_logger.warnings
 
        # No datasets, no fraction.
        trainer = DummyTrainer(
            train_loop,
            scaling_config=ScalingConfig(num_workers=1),
        )
        trainer.fit()
        assert not mock_tuner_internal_logger.warnings
 
        # Should warn.
        trainer = DummyTrainer(
            train_loop,
            scaling_config=ScalingConfig(num_workers=3),
            datasets={"train": ray.data.range(10)},
        )
        trainer.fit()
        assert (
            len(mock_tuner_internal_logger.warnings) == 1
        ), mock_tuner_internal_logger.warnings
        assert "_max_cpu_fraction_per_node" in mock_tuner_internal_logger.warnings[0]
        mock_tuner_internal_logger.clear()
 
        # Warn if num_samples is configured
        trainer = DummyTrainer(
            train_loop,
            scaling_config=ScalingConfig(num_workers=1),
            datasets={"train": ray.data.range(10)},
        )
        tuner = tune.Tuner(trainer, tune_config=tune.TuneConfig(num_samples=3))
        tuner.fit()
        assert (
            len(mock_tuner_internal_logger.warnings) == 1
        ), mock_tuner_internal_logger.warnings
        assert "_max_cpu_fraction_per_node" in mock_tuner_internal_logger.warnings[0]
        mock_tuner_internal_logger.clear()
 
        # Don't warn if resources * samples < 0.8
        trainer = DummyTrainer(
            train_loop,
            scaling_config=ScalingConfig(num_workers=1, trainer_resources={"CPU": 0}),
            datasets={"train": ray.data.range(10)},
        )
        tuner = tune.Tuner(trainer, tune_config=tune.TuneConfig(num_samples=3))
        tuner.fit()
>       assert not mock_tuner_internal_logger.warnings
E       AssertionError: assert not ['Executing `.fit()` may leave less than 20% of CPUs in this cluster for Dataset execution, which can lead to resource contention or hangs. To avoid this, reserve at least 20% of node CPUs for Dataset execution by setting `_max_cpu_fraction_per_node = 0.8` in the Trainer scaling_config. See https://docs.ray.io/en/master/data/dataset-internals.html#datasets-and-tune for more info.']
E        +  where ['Executing `.fit()` may leave less than 20% of CPUs in this cluster for Dataset execution, which can lead to resource contention or hangs. To avoid this, reserve at least 20% of node CPUs for Dataset execution by setting `_max_cpu_fraction_per_node = 0.8` in the Trainer scaling_config. See https://docs.ray.io/en/master/data/dataset-internals.html#datasets-and-tune for more info.'] = <python.ray.train.tests.test_base_trainer.mock_tuner_internal_logger.<locals>.MockLogger object at 0x7f9140bab590>.warnings
 
python/ray/train/tests/test_base_trainer.py:294: AssertionError
```

**Comment by bveeramani** [comment]
Looks like this is still somewhat flaky, although it's a different error now:

```
def test_reserved_cpu_warnings(ray_start_4_cpus, mock_tuner_internal_logger):
--
  | # We use gc.collect in this test to ensure that all
  | # Ray actors & tasks are terminated in between .fit() calls,
  | # as the warning condition checks for available Ray resources.
  |  
  | def train_loop(config):
  | pass
  |  
  | # Fraction correctly specified.
  | trainer = DummyTrainer(
  | train_loop,
  | scaling_config=ScalingConfig(num_workers=1, _max_cpu_fraction_per_node=0.9),
  | datasets={"train": ray.data.range(10)},
  | )
  | trainer.fit()
  | gc.collect()
  | assert not mock_tuner_internal_logger.warnings
  |  
  | # No datasets, no fraction.
  | trainer = DummyTrainer(
  | train_loop,
  | scaling_config=ScalingConfig(num_workers=1),
  | )
  | trainer.fit()
  | gc.collect()
  | assert not mock_tuner_internal_logger.warnings
  |  
  | # Should warn.
  | trainer = DummyTrainer(
  | train_loop,
  | scaling_config=ScalingConfig(num_workers=3),
  | datasets={"train": ray.data.range(10)},
  | )
  | trainer.fit()
  | gc.collect()
  | >       assert (
  | len(mock_tuner_internal_logger.warnings) == 1
  | ), mock_tuner_internal_logger.warnings
  | E       AssertionError: []
  | E       assert 0 == 1
  | E         +0
  | E         -1
```

**Comment by Yard1** [comment]
I wonder if we should just mock `ray.available_resources()` here and simply make it return the intended number. I feel like that'd be fine, since all we want is to test the warning logic.
