### ISSUE TITLE
[Serve] Restore the ability to set `location` to `NoServer`

### ISSUE THREAD

**Issue by zoltan-fedor** [ray-project/ray#31344]
### What happened + What you expected to happen

With Ray Serve v1.x it was possible to set `location` to `NoServer`, when you did not want to access the Serve deployment via HTTP, only via Python handlers.

With the new Deployment API of Ray Serve v2.x, this is no longer possible. Now `location` is hardcoded to `EveryNode` (see https://github.com/ray-project/ray/blob/master/python/ray/serve/api.py#L483), so you are forced to run HTTP proxies even if you are not intending to use them.

I recommend to restore the ability to set `location` to `NoServer` with the new, v2.x Deployment API.

### Versions / Dependencies

Ray Serve v2.2.0

### Reproduction script

Any Ray Serve deployment script will do.

I took the example from https://docs.ray.io/en/latest/serve/migration.html#migrating-a-single-deployment-to-the-new-deployment-api:
```
@serve.deployment
class Model:
    def __call__(self, input: int):
        # some inference work
        return


handle = serve.run(Model.bind())  # => this will create Serve with the "EveryNode" option, you have no way around it
handle.remote(1)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

This has been discussed at https://ray-distributed.slack.com/archives/CNCKBBRJL/p1672187406054769?thread_ts=1672178048.704709&cid=CNCKBBRJL

**Comment by shrekris-anyscale** [comment]
This is resolved by #33160.
