### ISSUE TITLE
Request for releasing a new tag

### ISSUE THREAD

**Issue by old-bear** [ray-project/ray#3134]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.11
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 2.7
- **Exact command to reproduce**:

### Describe the problem

Hi, there are a few fixes and features of `ray.tune` which our project depends on since the last release 0.5.3. Moreover, we could not depend on the current master since our project is another python library for others to use. Is it possible to make a new release of the current version?

Thanks a lot

**Comment by old-bear** [comment]
@robertnishihara Thanks for reply. So how long do you expect would it to take for the next stable release? Is it possible to release the `ray.tune` part alone?

**Comment by old-bear** [comment]
Hi, any updates on this? Thanks

**Comment by robertnishihara** [comment]
We’re working on fixing some important bugs before releasing. I think two
weeks may be feasible.

**Comment by robertnishihara** [comment]
@old-bear wheels for 0.6.0 have now been uploaded to PyPI.
