### ISSUE TITLE
Expose and rename _submit API.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3135]
Currently, you can invoke remote functions in two ways

```python
@ray.remote(num_gpus=1)
def f(x, y, z=0):
    pass

f.remote(1, 2, z=3)

f._submit(args=[1, 2], kwargs={'z': 3})
```

The above two invocations are equivalent. However, `_submit` is strictly more general because you can also specify other things

```python
f._submit(args=[1, 2], kwargs={'z': 3}, num_return_vals=0, num_gpus=0)
```

I think we haven't really documented `_submit` because we aren't super happy with the name. But it's very useful and should probably be documented more clearly.

So what's the best name for this? Candidates include `_submit`, `submit`, `_remote`, or something else.

**Comment by istoica** [comment]
I'd prefer `_remote` from the name you mentioned. Typically `submit` is used for jobs in other  frameworks.

**Comment by stephanie-wang** [comment]
I'm not totally sure how the implementation would work, but one API that I sort of like it "promise chaining", from [javascript](https://javascript.info/promise-chaining). So in Ray, it could look something like:
```
f.remote(*args).with_resources({'gpus': 1})
```

**Comment by istoica** [comment]
I like @stephanie-wang's proposal. It should also work well for actor's method invocation.

**Comment by robertnishihara** [comment]
The chaining proposal feels unpythonic to me.

@ion, I think I also prefer `_remote` to `submit`/`_submit`.

**Comment by pcmoritz** [comment]
I agree @unpythonic and also prefer `_remote`

**Comment by istoica** [comment]
Just to make sure. This will work the same way for functions and method invocations, right?

**Comment by richardliaw** [comment]
Just wondering, what is the use case? What would be the benefits over a user just creating a different remote function?

```
def f(x, y, z=0):
    pass

f1 = ray.remote(num_gpus=1)(f)
f2 = ray.remote(num_return_vals=0, num_gpus=0)(f)

f1.remote(*args)
f2.remote(*args)
```

**Comment by robertnishihara** [comment]
Still need to document this somewhere, but this is basically done.
