### ISSUE TITLE
[ci][python3.11] Wheel build 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31362]
### What happened + What you expected to happen

Mac and Windows wheels for python3.11 are not supported yet: 
- Mac: CI machines don't have python 3.11 installed 
- Windows: Conda channels not supported. 

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
Looks like conda will be officially supported 3.11 in its up coming release. Will try to make ray work on 3.11 for non-linux once the conda release is out. 

https://github.com/conda/conda/issues/11170#issuecomment-1512166972

**Comment by ddelange** [comment]
just out of curiosity and willingness to help:
- is there a particular reason to use conda to build wheels?
- could you point me to the code?
- i set up a [build with cibuildwheel](https://github.com/MagicStack/asyncpg/blob/bf74e88bb5193b39cf942a6f0e9b838da3d0214a/.github/workflows/release.yml#L88-L90) before, did you also consider it? (it's from the python packaging authority and builds PEP conform on the [official manylinux images](https://github.com/pypa/manylinux))
  - the [resulting wheels](https://pypi.org/project/asyncpg/0.27.0/#files) will cover mostly any machine and will have the widest possible compatibility (although being built on the most recent OS versions)

**Comment by rickyyx** [comment]
> just out of curiosity and willingness to help:
> 
> * is there a particular reason to use conda to build wheels?
> * could you point me to the code?
> * i set up a [build with cibuildwheel](https://github.com/MagicStack/asyncpg/blob/bf74e88bb5193b39cf942a6f0e9b838da3d0214a/.github/workflows/release.yml#L88-L90) before, did you also consider it? (it's from the python packaging authority and builds PEP conform on the [official manylinux images](https://github.com/pypa/manylinux))
>   
>   * the [resulting wheels](https://pypi.org/project/asyncpg/0.27.0/#files) will cover mostly any machine and will have the widest possible compatibility (although being built on the most recent OS versions)

I think it was more of a historical reason - I don't think it's a must-have dependency. 

I believe the entry point for wheel building is here: https://github.com/ray-project/ray/blob/81a4a5ed2784e0bbc0bfb15f01e1f8b2207ba826/.buildkite/pipeline.build.yml#L7

**Comment by ddelange** [comment]
> Looks like conda (which ray depends on for wheel building process) will be officially supportinh 3.11 in its up coming release. Will try to make ray work on 3.11 for non-linux once the conda release is out.
> 
> [conda/conda#11170 (comment)](https://github.com/conda/conda/issues/11170#issuecomment-1512166972)

@rickyyx support is released https://github.com/conda/conda/commit/7ec97d67e05f63260628c33647c68cf455dfbc40 🚀

**Comment by ddelange** [comment]
Hi @rickyyx 👋

I saw ray 2.5.0 just landed, still without win and mac wheels. Is there manual intervention needed from your side for this ticket?

**Comment by rickyyx** [comment]
Yes, @ddelange we are looking into this now. Should be able to support both win + mac and potentially docker images from Ray for python 3.11 in 2.6.

**Comment by ddelange** [comment]
for future reference the corresponding mac PR: https://github.com/ray-project/ray/pull/36185
