### ISSUE TITLE
[<Ray component: Core>] @ray.remote function runs on head node instead of worker node

### ISSUE THREAD

**Issue by Yifan122** [ray-project/ray#31384]
### What happened + What you expected to happen

I run a python function on ray cluster with @ray.remote, but the function runs on head node instead of worker node
![image](https://user-images.githubusercontent.com/30310577/210167865-fcad9afb-e462-4fac-ba84-f06d4840a1e0.png)

### Versions / Dependencies

Ray version: 2.0.0

### Reproduction script

```
import ray

@ray.remote
def test_cpu3():
    import time
    time.sleep(150)
    return "done"

my_task = test_cpu3.remote()
ray.get(my_task)
```

### Issue Severity

None

**Comment by rkooo567** [comment]
Functions are scheduled on a node that has available cpus. So it is normal it is scheduled on a worker node. If you'd like to avoid it setting `--num-cpus` of a head node as 0 (`ray start --head --num-cpus=0`) or use the node affinity scheduling to avoid scheduling on a head node https://docs.ray.io/en/master/ray-core/scheduling/index.html#nodeaffinityschedulingstrategy

**Comment by Yifan122** [comment]
thanks a lot, it works
