### ISSUE TITLE
[tune] Ray tune KeyError: "hidden1" when tune hyper parameters of NN 

### ISSUE THREAD

**Issue by Dylan-Nico** [ray-project/ray#31387]
### What happened + What you expected to happen

I am using PytorchLightning module and I am trying to tune the hyperparameters of a NN with RayTune. Following this reference https://towardsdatascience.com/how-to-tune-pytorch-lightning-hyperparameters-80089a281646

I am a beginner in Pytorch lightning and ray tune, so I am not really sure of what I have done, but all seems okay to me. I would expect to see the results like the final script on the reference, but all I got are the execution epoch and the key ERROR instead of TERMINATE. Then, the error reported is KeyError: "hidden1". The variable 'hidden1' is the dimension of the hidden layers in my NN, and it is initialized in the __init()__ function, where the error is detected.

I am sorry if I am not clear, but this is the best explanation I got, since I'm a beginner. I can say that the NN works properly without ray tune. For class project purpose I have to do a hyper parameter tuning and so I added this method searching the web.

Thank you all for helping me.

### Versions / Dependencies

Pytorch version: 1.13.0
PytorchLightning version: 1.8.2
RayTune version:  2.2.0

### Reproduction script

class ClassificationMonk(pl.LightningModule):
    
    def __init__(self, input_dim, output_dim, config):
        super(ClassificationMonk, self).__init__()
        # First hidden layer
        hidden1 = config["hidden1"]
        self.linear1 = nn.Linear(input_dim, hidden1)
        self.act1 = nn.ReLU()
        # Second hidden layer
        self.linear2 = nn.Linear(hidden1, hidden1)
        self.act2 = nn.ReLU()
        # Third hidden layer
        self.linear3 = nn.Linear(hidden1,output_dim)
        self.act3 = nn.Sigmoid()
        self.loss_fun = nn.MSELoss()
        self.dicts = []
        self.lr = config["lr"]
        self.apply(self.init_weights)
    
    def init_weights(self,m):
        if isinstance(m, nn.Linear):
            torch.nn.init.xavier_uniform_(m.weight)
            m.bias.data.fill_(0.01)
    
    def forward(self, X):
        #Input to the first hidden layer
        X = self.linear1(X)
        X = self.act1(X)
        # Second hidden layer
        X = self.linear2(X)
        X = self.act2(X)
        # Third hidden layer
        X = self.linear3(X)
        X = self.act3(X)
        return X

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.lr,momentum=0.9)
        return optimizer
    
    def training_step(self, train_batch, batch_idx):
        X, y = train_batch 
        y_copy = y # Integer y for the accuracy
        X = X.type(torch.float32)
        y = y.type(torch.float32)  
        # forward pass
        y_pred = self.forward(X).squeeze()  
        # accuracy
        accuracy = Accuracy()
        acc = accuracy(y_pred, y_copy)
        # compute loss
        loss = self.loss_fun(y_pred, y)
        self.log_dict({'train_loss': loss, 'train_accuracy': acc}, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        return loss
    
    def validation_step(self, validation_batch, batch_idx):
        X, y = validation_batch
        X = X.type(torch.float32)
        # forward pass
        y_pred = self.forward(X).squeeze()        
        # compute metrics 
        accuracy = Accuracy()
        acc = accuracy(y_pred, y)
        loss = self.loss_fun(y_pred, y)
        self.log_dict({'validation_loss': loss, 'validation_accuracy': acc}, prog_bar=True, logger=True)
        return loss
    
    def validation_epoch_end(self, outputs):
        avg_loss = torch.stack(
            [x["val_loss"] for x in outputs]).mean()
        avg_acc = torch.stack(
            [x["val_accuracy"] for x in outputs]).mean()
        self.log("ptl/val_loss", avg_loss)
        self.log("ptl/val_accuracy", avg_acc)
    
    
    def test_step(self, test_batch, batch_idx):
        X, y = test_batch
        X = X.type(torch.float32)
        # forward pass
        y_pred = self.forward(X).squeeze()        
        # compute metrics   
        accuracy = Accuracy()
        acc = accuracy(y_pred, y)
        loss = self.loss_fun(y_pred, y)
        self.log_dict({'test_loss': loss, 'test_accuracy': acc}, on_epoch=True,on_step=False, prog_bar=True, logger=True)
        return loss
   
    max_epochs = 500 
    test_batch_size = 10

    # Defining a search space!
    config = {
         "hidden1": tune.choice([10, 15, 20]),
         "lr": tune.loguniform(1e-4, 1e-1),
         "batch_size": tune.choice([5, 10, 15])
    }

    def train_monks(config, num_epochs=10, num_gpus=0):
         input_dim = xtr.shape[1]
         model = ClassificationMonk(input_dim=input_dim, output_dim=1, config=config)
         train_loader = DataLoader(dataset = ClassificationMonkDataset(xtr, ytr), batch_size=config["batch_size"])
         validation_loader = DataLoader(dataset = ClassificationMonkDataset(xtr, ytr), batch_size=config["batch_size"])
         metrics = {"loss": "val_loss", "acc": "val_accuracy"}
         trainer = pl.Trainer(
             max_epochs=max_epochs,
             gpus=num_gpus,
             logger=CSVLogger(save_dir="logs/"),
             progress_bar_refresh_rate=0,
             callbacks=[TuneReportCallback(metrics, on="validation_end")])
         trainer.fit(model=model, train_dataloaders=train_loader,val_dataloaders=validation_loader) 
   

    num_samples = 10
    num_epochs2 = 10
    gpus_per_trial = 0 # set this to higher if using GPU

    trainable = tune.with_parameters(
        train_monks,
        num_epochs=num_epochs2,
        num_gpus=gpus_per_trial)

    analysis = tune.run(
        trainable,
        resources_per_trial={
            "cpu": 1,
            "gpu": gpus_per_trial
        },
        metric="loss",
        mode="min",
        num_samples=num_samples,
        name="tune_mnist")

    print(analysis.best_config)

### Issue Severity

None

**Comment by justinvyu** [comment]
Hi @Dylan-Nico,

It looks like the search space you defined isn't being passed into the `tune.run` call. You'll need to specify it through `tune.run(..., config=config)`.

Take a look at [this user guide](https://docs.ray.io/en/master/tune/tutorials/tune_get_data_in_and_out.html#search-space) for an explanation of how to get data into Tune (this is using the new Tuner API in Ray 2.x).

**Comment by justinvyu** [comment]
Closing as the question is resolved. Feel free to re-open with any followup questions!
