### ISSUE TITLE
[Tune] `TuneReportCallback` integration with pytorch-lightning/Hydra: renaming of the argument "on"

### ISSUE THREAD

**Issue by byfron** [ray-project/ray#31405]
### Description

Hi. This is just a suggestion, but the argument name "on" is pretty badly chosen. Does not really self-explain what's for, and I found some issues when integrating Ray-Tune with Hydra, because hydra automatically maps config file keywords named "on" to "True", so the whole thing becomes a bit messy when instantiating TuneReportCallback objects from Hydra. 

Besides, trying to google search for anything with the keyword "on" on it brings lots of useless results.  

Cheers

### Use case

Simply rename the keyword to "trigger_on"

**Comment by byfron** [comment]
For the record, subclassing TuneReportCallback is a good enough solution for the Hydra issue. So IMO this can be closed without fix.

**Comment by bveeramani** [comment]
Hey @byfron, thanks for the suggestion! 

I agree that `on` isn't a particularly descriptive name. That said, I'm not sure if it warrants a deprecation/API change.

Glad you were able to find a workaround to your problem.
