### ISSUE TITLE
[data] Improve str/repr of lazy Datasets

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#31417]
### Description

Currently, a lazy Dataset's string repr shows something like this:

```
>>> ray.data.range(10).map(lambda x: x).filter(lambda y: y)
Dataset(num_blocks=10, num_rows=?, schema=Unknown schema)
```

This doesn't provide a lot of useful information, and is also confusing to the user. We could improve this to something like this:

```
Dataset(num_blocks=10, <Pending execution: Map, Filter>)
```

Or even add a verbose form, like:
```
Dataset(num_blocks=10, num_rows=1000 schema=<class 'int'>)
  -> Map <function <lambda> at 0x7fb9919c8a60> (Pending execution)
  -> Filter <function <lambda> at 0x7fbbf9e45820> (Pending execution)
```

We should implement this prior to making lazy execution the default.

**Comment by c21** [comment]
Agree to make str/repr clearer. Print out the execution plan sounds good to me.
