### ISSUE TITLE
[RLlib] multi-gpu CQL doesn't work

### ISSUE THREAD

**Issue by Emiyalzn** [ray-project/ray#31427]
Hey @Emiyalzn , thanks for filing this issue! Actually, all these algos (BC, MARWIL, and CQL) do indeed support multi-GPU, but only our config validation method prevents this from working ok (it throughs the reported error). I'll remove these unnecessary checks from the `validate` methods in this PR (https://github.com/ray-project/ray/pull/31393).

In the meantime, please simply comment out these if blocks, e.g.:
```
        if self.num_gpus > 1:
            raise ValueError("`num_gpus` > 1 not yet supported for CQL!")
```
and things should just work.

_Originally posted by @sven1977 in https://github.com/ray-project/ray/issues/31323#issuecomment-1369489101_

**Comment by Emiyalzn** [comment]
Thank for Sven's help, Now I can run multi-GPU CQL on my machine. However, During my execution, another problem raises: the GPU overload imbalance. I run the experiment on a 4-GPU machine, and it turns out that the memory consumption on the first GPU is much larger than the others. However, I can run 4-GPU SAC smoothly with load-balance. Is there anything to be updated for multi-gpu CQL algorithm?

**Comment by Emiyalzn** [comment]
Update: I find the reason for the load imbalance is the `validate()` fn in class `CQLConfig`:
```python
        # CQL-torch performs the optimizer steps inside the loss function.
        # Using the multi-GPU optimizer will therefore not work (see multi-GPU
        # check above) and we must use the simple optimizer for now.
        if self.simple_optimizer is not True and self.framework_str == "torch":
            self.simple_optimizer = True
```
You hardly set the CQL optimizer to be the simple optimizer.

After I comment these lines, another bug occurs: 
```shell
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 364, in train
    result = self.step()
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 749, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 2623, in _run_one_training_iteration
    results = self.training_step()
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/algorithms/cql/cql.py", line 193, in training_step
    train_results = multi_gpu_train_one_step(self, train_batch)
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/execution/train_ops.py", line 164, in multi_gpu_train_one_step
    permutation[batch_index] * per_device_batch_size, buffer_index=0
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 607, in learn_on_loaded_batch
    tower_outputs = self._multi_gpu_parallel_grad_calc(device_batches)
  File "/home/lizn/miniconda3/envs/simul/lib/python3.7/site-packages/ray/rllib/policy/torch_policy.py", line 1196, in _multi_gpu_parallel_grad_calc
    raise output[0] from output[1]
ValueError: Error In tower 1 on device cuda:1 during multi GPU parallel gradient calculation:: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument tensors in method wrapper_cat)
``` 
I believe this bug occurs because the `towers` in `cql_loss()` fn are not correctly implemented. One step further, I find the gradient backward and optimizer step are performed in the loss function now (SAC optimization is not performed in the loss function), which may be the reason of the bug.
In a word, further modifications (in the loss function and the optimization step) should be made to enable multi-gpu CQL training.

**Comment by Emiyalzn** [comment]
`Bug` and `enhancement` tags can be added for this issue.

**Comment by sven1977** [comment]
Hey @Emiyalzn , thanks for re-raising this! You are right, this is still a problem with CQL. It's torch implementation seems to do something whacky, which prevents us to use multi-GPU for torch. Ok, I'll take another look.

**Comment by Emiyalzn** [comment]
Hey @sven1977 , I think I've found the core problem to enable multi-GPU CQL training. You can refer to my PR [#31466](https://github.com/ray-project/ray/pull/31466) for more details.
In a word, this line of code:
```python
# CQL Loss (We are using Entropy version of CQL (the best version))
    rand_actions = convert_to_torch_tensor(
        torch.FloatTensor(actions.shape[0] * num_actions, actions.shape[-1]).uniform_(
            action_low, action_high
        ),
    policy.device,
)
```
raises the device problem in CQL. And I change it to:
```python
# CQL Loss (We are using Entropy version of CQL (the best version))
    rand_actions = convert_to_torch_tensor(
        torch.FloatTensor(actions.shape[0] * num_actions, actions.shape[-1]).uniform_(
            action_low, action_high
        ),
    actions.device,
)
```
which successfully solves the problem. Now I can run multi-GPU CQL smoothly on my machine☺️
