### ISSUE TITLE
If the performance influenced by the tf.Session settings

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3142]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: latest
- **Python version**: 3.6

### Describe the problem
I define some gradient calculations in each remote evaluator. Therefore, I attempt to speed up by setting the `intra_op_parallelism_threads` and `inter_op_parallelism_threads` to `None` for each remote evaluator.

But I find that the execution time is longer than or almost the same with the time of setting those two arguments to `1`. I wonder whether it is expected.

More specifically, I set `batch_mode` to `complete_episodes`, where the number of returned samples is around `batch_steps * num_envs_per_worker`.

In scenario 1 (`batch_steps=4000, num_envs_per_worker=1`):
When `intra_op_parallelism_threads=inter_op_parallelism_threads=1`, the time is `33.94s`;
When `intra_op_parallelism_threads=inter_op_parallelism_threads=None`, the time is `41.36s`.

In scenario 2 (`batch_steps=200, num_envs_per_worker=20`):
When `intra_op_parallelism_threads=inter_op_parallelism_threads=1`, the time is `10.97s`;
When `intra_op_parallelism_threads=inter_op_parallelism_threads=None`, the time is `11.69s`.

In general, do you some advice how to adjust these two parameters, or just set them to `1`.

**Comment by ericl** [comment]
The reason they are set to 1 is to avoid hardware oversubscription, as by default Ray only allocates one CPU per worker. Allowing more parallelism within tensorflow can cause thrashing as the kernel now has to multiplex CPUs between multiple competing processes. The effect isn't large, but we found 1 to usually be the best setting for the workers.

**Comment by llan-ml** [comment]
Thanks for your reply.

I have another doubt about how ray does resource limitation internally. When we set `num_cpus=5`, it means that the corresponding task exactly occupies 5 CPUs, or it just decreases the available number of CPUs by 5 and the new task is pending if the available number is smaller than 5.

**Comment by ericl** [comment]
Yeah it's just accounting, there's no limit.
