### ISSUE TITLE
client.get_action Crashes Worker Thread

### ISSUE THREAD

**Issue by XanderKehoe** [ray-project/ray#31424]
### What happened + What you expected to happen

I am trying to implement a custom client/server communication (like https://github.com/ray-project/ray/blob/master/rllib/examples/serving/cartpole_client.py), but when I run the 'client.get_action(eid, obs)' function I am getting the following error: 

ValueError: Observation ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 6, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 4,
 1, 1,] dtype=float32) outside given space (Box(-inf, inf, (4,), float32))!

EDIT: . after obs values replaced with , to work with GitHub formatting.

I have tried passing in the obs argument as both a normal list and np.array.

I have reviewed https://github.com/ray-project/ray/issues/12940, but I did not find a solution that worked for me there.

The values shown in the error appear to equal the values I am passing into the get_action function.

Here is the full stack trace:
2023-01-03 20:00:47,111	INFO policy_client.py:337 -- The env you specified is not a supported (sub-)type of ExternalEnv. Attempting to convert it automatically to ExternalEnv.
2023-01-03 20:00:47,112	WARNING env.py:81 -- Env checking isn't implemented for VectorEnvs, RemoteBaseEnvs, ExternalMultiAgentEnv, ExternalEnvs or environments that are Ray actors.
2023-01-03 20:00:47,366	INFO policy.py:1134 -- Policy (worker=1) running on CPU.
2023-01-03 20:00:47,366	INFO tf_policy.py:155 -- Found 0 visible cuda devices.
2023-01-03 20:00:47,427	INFO dynamic_tf_policy_v2.py:711 -- Adding extra-action-fetch `action_prob` to view-reqs.
2023-01-03 20:00:47,428	INFO dynamic_tf_policy_v2.py:711 -- Adding extra-action-fetch `action_logp` to view-reqs.
2023-01-03 20:00:47,430	INFO dynamic_tf_policy_v2.py:711 -- Adding extra-action-fetch `action_dist_inputs` to view-reqs.
2023-01-03 20:00:47,431	INFO dynamic_tf_policy_v2.py:711 -- Adding extra-action-fetch `vf_preds` to view-reqs.
2023-01-03 20:00:47,431	INFO dynamic_tf_policy_v2.py:723 -- Testing `postprocess_trajectory` w/ dummy batch.
2023-01-03 20:00:48,693	INFO policy_client.py:273 -- Querying server for new policy weights.
2023-01-03 20:00:48,699	INFO policy_client.py:302 -- Generating new batch of experiences.
2023-01-03 20:00:48,699	INFO rollout_worker.py:822 -- Generating sample batch of size 1000
2023-01-03 20:00:50,748	INFO policy_client.py:281 -- Updating rollout worker weights and global vars None.
2023-01-03 20:01:14,328	INFO sampler.py:664 -- Raw obs from env: { 'cf875867a4404ec48ab8749ff5dc68f5': { 'agent0': [ 1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    6.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    6.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    4.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    6.0,
                                                    1.0,
                                                    6.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    5.0,
                                                    1.0,
                                                    4.0,
                                                    1.0,
                                                    1.0]}}
2023-01-03 20:01:14,329	INFO sampler.py:665 -- Info return from env: {'cf875867a4404ec48ab8749ff5dc68f5': {'agent0': {}}}
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\env\policy_client.py", line 303, in run
    samples = self.rollout_worker.sample()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\rollout_worker.py", line 828, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\sampler.py", line 92, in next
    batches = [self.get_data()]
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\sampler.py", line 285, in get_data
    item = next(self._env_runner)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\sampler.py", line 671, in _env_runner
    active_envs, to_eval, outputs = _process_observations(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\evaluation\sampler.py", line 922, in _process_observations
    prep_obs = preprocessor.transform(raw_obs)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\models\preprocessors.py", line 204, in transform
    self.check_shape(observation)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ray\rllib\models\preprocessors.py", line 74, in check_shape
    raise ValueError(
ValueError: Observation ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1,
 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1,
 1, 6, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 4,
 1, 1,] dtype=float32) outside given space (Box(-inf, inf, (4,), float32))!
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\logging\__init__.py", line 1081, in emit

### Versions / Dependencies

OS=Windows 10 Home
Python==3.8.3
Ray==2.1.0
scipy==1.10.0
numpy==1.21.0
tensorflow==2.11.0

### Reproduction script

if __name__ == "__main__":
    eid = client.start_episode(training_enabled=True)
    obs = GetObs()
    while True:
        action = client.get_action(eid, obs)  # error stems from here
        ...
    ...
    

### Issue Severity

High: It blocks me from completing my task.

**Comment by mvindiola1** [comment]
Hi @XanderKehoe,

The issue is that you defined the observation space as a Box of 4 values. The observation you shared has many more than 4 values. The error arises because the size of the space you defined and the size of the observation do not match.

**Comment by XanderKehoe** [comment]
@mvindiola1 Thanks for reaching out! I believe I see the issue now, for future viewers here was my issue.

The problem was not in my client-side script as I thought, but on the server-side script. Where in my algorithm config the observation_space was defined as a box of 4 values, as @mvindiola1 pointed out.
