### ISSUE TITLE
[RLlib]  Custom env does not have .spec.max_episode_steps attribute

### ISSUE THREAD

**Issue by rajfly** [ray-project/ray#31433]
### What happened + What you expected to happen

Custom environment using RLlib results in the following warning:

WARNING env.py:147 -- Your env doesn't have a .spec.max_episode_steps attribute. This is fine if you have set 'horizon' in your config dictionary, or `soft_horizon`. However, if you haven't, 'horizon' will default to infinity, and your environment will not be reset.

As a result, the custom breakout environment does not learn (rewards are stuck between 0-2 range). If I were to ditch the custom environment and just use the normal `ALE/Breakout-v5` env, I am able to train breakout to mean rewards of 30+.

The training config follows the example shown on the ray website which links to the ray rllib directory [here](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/dqn/atari-duel-ddqn.yaml).

**Reasons for using custom environment** 
I need to run breakout on torch and tf frameworks: `.framework(framework=tune.grid_search(['torch', 'tf', 'tf2']), eager_tracing=True)`. However, one key condition, to keep comparisons fair, is that I need all frameworks to experience the same environment initialisation for each reset, i.e., the frameworks should have the same reset seeds. I tried to achieve this by creating a custom env and incrementing the reset seed during each reset (incrementing the seed was implemented to ensure that the training process does not just use one seed). This way, all frameworks would more or less experience the same env initialisations. More elegant solutions would be appreciated.

**Additional questions which I have**
What does the seed in`.debugging()` actually set? Does it already ensure that each framework sees the same env initialisations for each reset? I.e., 
- reset 1 env obs for all frameworks: [0.123, 0.324, ....]
- reset 2 env obs for all frameworks: [0.567, 0.789, ....]
- ...
- ...

If it does, then there is no need for me to use the custom environment.

### Versions / Dependencies

- Ray 2.2.0
- Gym 0.23.1
- Python 3.9
- Ubuntu

### Reproduction script

```python
# set visible gpus
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

import ray
from ray import air, tune
from ray.rllib.algorithms.dqn.dqn import DQNConfig

import numpy as np
from ray.rllib.algorithms.callbacks import DefaultCallbacks
from ray.rllib.algorithms.algorithm import Algorithm

import gym
from gym.wrappers import RecordVideo
from ray.rllib.env.env_context import EnvContext

from ray.tune.registry import register_env

class Breakout(gym.Env):
    def __init__(self, config: EnvContext):
        self.reset_count = -1
        self.env = gym.make('ALE/Breakout-v5')
        self.config = config['name_prefix']
        self.config += '-wkr-' + str(config.worker_index)
        self.config += '-env-' + str(config.vector_index)
        if config['name_prefix'] == 'evl':
            self.env = RecordVideo(
                self.env, 
                video_folder='videos', 
                episode_trigger=lambda x: x % 10 == 0,
                name_prefix=self.config
            )
        self.action_space = self.env.action_space
        self.observation_space = self.env.observation_space
        print('env init: ' + self.config)
    
    def reset(self):
        self.reset_count += 1
        print('env reset: ' + self.config)
        return self.env.reset(seed=self.reset_count)
    
    def step(self, action):
        return self.env.step(action=action)

rllib_config = DQNConfig()\
    .environment(env="CustomBreakout", render_env=False, env_config={"name_prefix": "trn", "frameskip": 1})\
    .framework(framework=tune.grid_search(['torch', 'tf', 'tf2']), eager_tracing=True)
    .resources(num_gpus=1)\
    .debugging(seed=0)\
    .rollouts(rollout_fragment_length=4)\
    .training(
        double_q=True,
        dueling=True,
        num_atoms=1,
        noisy=False,
        replay_buffer_config={'type': 'MultiAgentReplayBuffer', 'capacity': 100000},
        num_steps_sampled_before_learning_starts=20000,
        n_step=1,
        target_network_update_freq=8000,
        lr=0.0000625,
        optimizer={'adam_epsilon': 0.00015},
        hiddens=[512],
        train_batch_size=32,
        )\
    .exploration(explore=True, exploration_config={'epsilon_timesteps': 200000, 'final_epsilon': 0.01})\
    .reporting(min_sample_timesteps_per_iteration=10000)\

air_config = air.RunConfig(
    name='DQN',
    checkpoint_config=air.CheckpointConfig(
        checkpoint_at_end=False
    ),
    log_to_file=True,
)

tuner = tune.Tuner(
    'DQN',
    param_space=rllib_config,
    run_config=air_config,
)

register_env("CustomBreakout", lambda config: Breakout(config))
ray.init()
tuner.fit()
ray.shutdown()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Hey @rajfly , thanks for posting this question.
Yes, if you set `seed` in your config's `debugging()` method, then all framework runs will be seeded in the exact same way. So yes, the seed is set once per experiment before the initial `reset()` (on the initial reset(seed=...) when using master, which now uses the gymnasium API).

**Comment by rajfly** [comment]
@sven1977 Thanks for the prompt reply! So just to confirm, let's say that each framework has 2 workers with 1 env for each worker. Am I correct to say that if I fix the seed in debugging `.debugging(seed=0)` the initial observations for the for each framework would be the exact same like this:

**torch first worker**
- episode 1 init obs: [a, b, c, ...]
- episode 2 init obs: [g, h, k, ...]
- ...

**tf first worker**
- episode 1 init obs: [a, b, c, ...]
- episode 2 init obs: [g, h, k, ...]
- ...


**torch second worker**
- episode 1 init obs: [t, y, u, ...]
- episode 2 init obs: [a, s, d, ...]
- ...

**tf second worker**
- episode 1 init obs: [t, y, u, ...]
- episode 2 init obs: [a, s, d, ...]
- ...

**Comment by sven1977** [comment]
Hey @rajfly , actually, since you are using different frameworks (which have different seeding and weight initialization behaviors), you might see differences already from the second timestep in the first episode on (as it might depend on the action, which the network chose).

Ah, yes, I see, this is your second question. :)

So yeah, if your weights were to be the same at startup, then the behavior would be exactly as you described until the first training update, which again might slightly behave differently between tf and torch optimizers/networks/RLlib Policies/etc...

There is currently not easy way to copy weights over from a tf policy to a torch one and vice versa. Our default networks are too different in terms of naming of the variables. We might take another shot at fixing that as we implement the new RLModule API, but it's not really super high prio as most users don't necessarily switch between frameworks "in flight" as you do in your experiments. Still, would be super nice to have this work more easily for debugging and comparison purposes.
