### ISSUE TITLE
[RLlib] rllib-cli examples fail: `stop` conditions are apparently no longer permitted in YAML?

### ISSUE THREAD

**Issue by cboettig** [ray-project/ray#31453]
Running almost any rlib cli example (eg from https://docs.ray.io/en/latest/rllib/rllib-cli.html) now fails with the error

```
ValueError: `stop` criteria only supported for python files.
```

This seems like a bug in the CLI, since just about all of the [examples](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/) seem to use yaml for tuned models and just about all of them include `stop` criteria.   Am I missing something?  I am seeing this on the current (2.2.0) release, haven't had issues running the examples using the rllib cli before.

**Comment by sven1977** [comment]
Hi @cboettig , thanks for filing this issue!
It is working on the current master branch (just tried it). I can confirm the above example is indeed NOT working in ray 2.2.

As a quick, monkey-patch workaround:
Can you replace this line in your ray/rllib/train.py file:
```
86:            if stop is not None and stop != "{}":
```

with this one here:
```
86:            if stop is not None and stop != "{}":
```
