### ISSUE TITLE
[Dataset] Split input files to launch as many read tasks as user-specified parallelism

### ISSUE THREAD

**Issue by c21** [ray-project/ray#31501]
### Description

Currently for our `read_xxx` APIs, we don't support launch multiple tasks to read one file. This becomes a problem when either (1).user specify parallelism, but they get surprisingly different run-time parallelism, when parallelism >> number_of_input_files, or (2).some input file is very large, so single task take more time to read it.

We have dynamic block splitting already, but that only resolves the problem of output, to make sure not OOM in the woker heap memory. We shall resolve the problem of input as well.

We can build this for popular APIs first  (such as `read_parquet`).

**Comment by c21** [comment]
cc @amogkam and @clarkzinzow when debugging PyTorch dataloader vs Ray dataset.

**Comment by clarkzinzow** [comment]
One easy win: pyarrow's `ParquetDataset` abstraction, which we use for the `ray.data.read_parquet()` API, [has a `split_row_groups` option](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html) that will create a dataset fragment for every row group, allowing Ray Datasets to read each row group in parallel. An expert user can current pass this in as `ray.data.read_parquet(..., dataset_kwargs={"split_row_groups": True})`, but this is not very discoverable.

We could expose this as a top-level `ray.data.read_parquet()` argument, and possibly turn it on by default (either always or if Parquet files are above a certain size).

**Comment by drcege** [comment]
It appears that the `split_row_groups` option has been removed. So what can be done to speed up parallel reads of a single large file?
