### ISSUE TITLE
[Core] Support Nvidia A10G accelerator_type

### ISSUE THREAD

**Issue by zoltan-fedor** [ray-project/ray#31533]
### Description

I could not find Nvidia's A10G as an accelerator type in https://github.com/ray-project/ray/blob/master/python/ray/util/accelerators/accelerators.py

### Use case

AWS offers the A10G in the p5. instance type (like p5.xlarge, p5.2xlarge, etc). We use that instance type along with p4dn (Nvidia Tesla T4). I would like to add A10G so code is more uniform.
```
from ray.util.accelerators import NVIDIA_TESLA_A10G

@ray.remote(num_gpus=1, accelerator_type=NVIDIA_TESLA_A10G)
def train():
    ....

**Comment by rkooo567** [comment]
cc @wuisawesome what does it take to support different accelerator types?
