### ISSUE TITLE
[Datasets] `Dataset.zip` doesn't work if blocks have different types

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31550]
### What happened + What you expected to happen

Tried to zip two datasets, got:
```
(do_zip pid=52072) ValueError: Cannot zip <class 'ray.data._internal.pandas_block.PandasBlockAccessor'> with block of type <class 'pyarrow.lib.Table'>
```

### Versions / Dependencies

Ray: 1012fbc375d55540fb944a1176a8a54af34182f6

### Reproduction script

```
import ray
import pandas as pd
df = pd.DataFrame({"spam": [0]})
ds1 = ray.data.from_pandas(df)
ds2 = ray.data.from_items([{"ham": [0]}])
ds1.zip(ds2)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
part of trend of aggregating Blocks of different type; for consideration as a larger project for ray210
