### ISSUE TITLE
[Datasets] Can't zip datasets with different number of blocks

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#31551]
### What happened + What you expected to happen

Tried to zip two datasets, but got
```
ValueError: Cannot zip dataset of different num blocks
```

### Versions / Dependencies

Ray: 1012fbc375d55540fb944a1176a8a54af34182f6

### Reproduction script

```
import ray
ds1 = ray.data.range(100).repartition(1)
ds2 = ray.data.range(100).repartition(2)
ds1.zip(ds2)
```

### Issue Severity

None

**Comment by c21** [comment]
Done by https://github.com/ray-project/ray/pull/32998, closing this issue.
