### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'ray.core.generated.ray.protocol'

### ISSUE THREAD

**Issue by LuckyZXL2016** [ray-project/ray#3157]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.5.3
- **Python version**: 3.6.5

### Describe the problem
When I build ray from the code of the github. It succeeded, but when I import ray, it occurs the problem :ModuleNotFoundError: No module named 'ray.core.generated.ray.protocol , so what should I do ?

**Comment by robertnishihara** [comment]
This is likely due to pulling a newer version of Ray after you compiled. I'd suggest wiping everything and making sure there are no copies of Ray installed anywhere. Then cloning a fresh copy and reinstalling.

**Comment by robertnishihara** [comment]
Installation has changed substantially, so the original error is likely no longer relevant.
