### ISSUE TITLE
[Datasets] Remove stats actor

### ISSUE THREAD

**Issue by c21** [ray-project/ray#31571]
### What happened + What you expected to happen

Stats actor is responsbile to keep the stats for read tasks only, and be accessed by driver when driver RPC to stats actor. This model has the weird timing issue that if `ds.stats()` is called immediately after read, the stats may not be up-dated. The reason is when ds.stats() is called and [stats actor does not get the metadata from read tasks yet](https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/stats.py#L249-L262). [Read tasks makes RPC to stats actor for sending the metadata](https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/lazy_block_list.py#L691). The read stats is stored in stats actor, and fetched into driver memory. so causes this timing issue here.

Plan here is to kill stats actor and move the read stats into driver memory directly.

### Versions / Dependencies

master

### Reproduction script

on master, this script may or may not print execution stats depending on timing:

```
import ray
import time

ds = ray.data.range_table(5)

for batch in ds.iter_batches():
    print(batch)

#time.sleep(3)

print(ds.stats())
print(ds.stats())
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jianoaix** [comment]
Just to note that to keep parity after removal, we need to improve the walltime tracking for stages in block metadata, potentially recording event timestamps. @scottjlee

**Comment by scottjlee** [comment]
keep
