### ISSUE TITLE
Incomplete specification of necessary gymnasium extras in `python/setup.py`?

### ISSUE THREAD

**Issue by h-vetinari** [ray-project/ray#31587]
The [spec](https://github.com/ray-project/ray/blame/master/python/setup.py#L267) of the dependency `gymnasium==0.26.3` for `ray[rllib]` in `python/setup.py` does not reflect the [specification](https://github.com/ray-project/ray/blame/master/python/requirements/ml/requirements_rllib.txt#L7-L8) in `python/requirements/ml/requirements_rllib.txt`, which uses `gymnasium[atari,mujoco]==0.26.3`.

Those gymnasium extras themselves cause a whole cascade of dependencies, and so this should be fully specified in `setup.py` -- not least because (so far) we use `setup.py` as a reference in conda-forge for what dependencies each `ray[variant]` has.

Also note that the `mujoco-py<2.2,>=2.1` pin [there](https://github.com/ray-project/ray/blame/master/python/requirements/ml/requirements_rllib.txt#L9-L10) does not correspond to `gymnasium[mujoco]` - the former is the original closed source versions, the latter includes a different `mujoco` (after the opensourcing), c.f. [here](https://github.com/Farama-Foundation/Gymnasium/blame/v0.26.3/setup.py#L40-L41)

_Originally posted by @h-vetinari in https://github.com/ray-project/ray/pull/31178#discussion_r1066561159_

**Comment by h-vetinari** [comment]
It would be very helpful to us in conda-forge if this could be fixed before the next release.

CC for awareness @richardliaw @cadedaniel @krfricke @vnlitvinov @mattip

On this note, it would also be great if gymnasium could be bumped to 0.27.1, because gymnasium 0.26.3 doesn't actually have `gymnasium[atari]`, but 0.27 does, see [here](https://github.com/conda-forge/gymnasium-feedstock/pull/16#issuecomment-1381096108) for more details.

**Comment by h-vetinari** [comment]
> CC for awareness @richardliaw @cadedaniel @krfricke @vnlitvinov @mattip

Gentle ping on this

**Comment by cadedaniel** [comment]
Hi @h-vetinari , can you help me understand the impact of this?

**Comment by h-vetinari** [comment]
> Hi @h-vetinari , can you help me understand the impact of this?

Hey @cadedaniel, happy to try:
* The dependency specification in `setup.py` and the requirements file for rllib should be in sync
* Ideally, the gymnasium version being used should be bumped (or the range increased) to allow 0.27. This should then obviate the need to include `gym[atari]` (which gymnasium 0.26 doesn't provide, but 0.27 does).
* The dependency changes should be tested, but I guess your CI is good enough for that.
* Not sure about any relevant API changes (other than the reinstatement of atari) between gymnasium 0.26 & 0.27, perhaps @pseudo-rnd-thoughts could chime in?

**Comment by cadedaniel** [comment]
> * The dependency specification in setup.py and the requirements file for rllib should be in sync

I will bring this up to an RLLib team member. For prioritization purposes, would really help to understand the concrete impact of when they're not in sync. Seems so far that the UX is poor for developers, since there are two purported sources of truth of requirements but actually there is only one. Is there anything else?

I'm not well versed with Python packaging, but seems to me that there should be some kind of linter for this..

**Comment by kouroshHakha** [comment]
@h-vetinari I think we don't necessary want setup.py to include env specific dependencies. requirement files are used for testing purposes. If you want to install the bare-bone of ray[rllib] that should only install gymnasium and not mujoco for example. Having said that bumping gymnasium from 0.26.3 to 0.27 seems reasonable. @sven1977 Do you have any concerns for this?

**Comment by h-vetinari** [comment]
> I think we don't necessary want setup.py to include env specific dependencies. requirement files are used for testing purposes only.

To be clear, I'm not saying that `pip install ray` should install everything from rllib, but `pip install ray[rllib]` _should_ install everything that's useful (or at least necessary) to run rllib, presumably (following the file name) as expressed by `requirements_rllib.txt`.

If there are certain test-only dependencies, those should be specified as such (e.g. name the file containing them `test_requirements_rllib.txt` and install those on top of `ray[rllib]` in CI).

**Comment by pseudo-rnd-thoughts** [comment]
The change between 0.26 and 0.27 is largely bug fixes and most importantly reading atari. There are no API changes between these versions

**Comment by mattip** [comment]
The requirement `gymnasium[atari,mujoco]==0.26.3` no longer appears in python/requirements. The additional requirements in `python/requirements/ml/rllib-test-requirements.txt` and `python/requirements_compiled.txt` are identical to the one in `python/setup.py`.

Closing, please reopen or open a new issue if there is still a problem.
