### ISSUE TITLE
Ray hanging forever on start

### ISSUE THREAD

**Issue by chrisorm** [ray-project/ray#3158]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6.5

### Describe the problem
We are trying to run ray with a large number of actors on a large number of aws instances (say 3000 actors distributed across 120 aws boxes, each with something like 16-30 cores (c4/c5 instances mainly)).

When we run, it is hit or miss if the jobs will actually start. Sometimes it all starts correctly, but other times it will simply hang. If we log onto the head node or any of the other nodes, the boxes appear to be completely idle in the cases where the jobs don't start. One of the first steps of each job will be to download some data and save it locally, and this normally does not happen, so it seems as if the failure happens at the distribution of the job stage, rather than within the job. 

Within local_scheduler_0_*.err, we see the following piece of logging info:

```*** Aborted at 1540830292 (unix time) try "date -d @1540830292" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7fb5c73b5040) received by PID 4754 (TID 0x7fb6f5eed740) from PID 18446744072757137472; stack trace: ***
    @     0x7fb6f58c2390 (unknown)
    @     0x7fb6f4d93c05 (unknown)
    @           0x48f04a sdscatlen
    @           0x48d370 __redisAppendCommand
    @           0x48b149 __redisAsyncCommand
    @           0x48ba2b redisvAsyncCommand
    @           0x48bacd redisAsyncCommand
    @           0x45cd65 redis_task_table_add_task()
    @           0x4604b1 init_table_callback()
    @           0x4612e1 task_table_add_task()
    @           0x4421d9 handle_actor_task_submitted()
    @           0x4428cf handle_actor_creation_notification()
    @           0x42f99c handle_actor_creation_callback()
    @           0x4593be redis_actor_notification_table_subscribe_callback()
    @           0x48b536 redisProcessCallbacks
    @           0x466f47 aeProcessEvents
    @           0x4671eb aeMain
    @           0x42def7 main
    @     0x7fb6f4c66830 __libc_start_main
    @           0x42f101 (unknown)
```
If we restart ray on the head and all the workers, it will eventually work, but it may take 5 or 6 restarts. 

- Increasing the resources - the boxes have ample room in both cpu and memory when this occurs, so we ruled out out of memory type errors.
- All jobs reliably run succesfully when run in batches on a smaller number of boxes and workers in a sequential fashion.
- Waiting - No change if we wait a long time, as far as we can tell, it will hang forever (consistent with a segfault in some child process).

Additionally, if we get a job to run reliably, and try to run another one after it without restarting Ray, we observe the same behaviour. Upon restarting we see the job run eventually (multiple retries often needed).

Would you happen to know anything that could be causing this? We only see this at scale, so reproducibility is hard too.

**Comment by robertnishihara** [comment]
@chrisorm thanks for reporting this! Could you try the latest nightly wheels to see if the issue is still present? You can install the relevant ones for Python 3.6 on Linux (instructions at https://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray) via

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
```

Another thing to try (before creating all of the actors but after running `ray.init(...)`) is to run `ray.global_state.client_table()` to see if it all of the nodes have connected successfully.

Are you saying that this has nothing to do with the specific job you're running? Do you see the same issue if you run a simpler job (e.g., just schedule a ton of tasks and return the IP addresses of the nodes that the tasks execute on to see if all nodes were used)?

**Comment by chrisorm** [comment]
@robertnishihara Using the latest wheel seems to solve the issue. Client table showed all the nodes connected succesfully. 

As far as we could see, this was not related to the specifics of the job (all of them could complete under different circumstances), but it seemed to be related to the load.

**Comment by robertnishihara** [comment]
Glad to hear it! Please feel free to reopen if it makes sense.
