### ISSUE TITLE
[Core] jemalloc error when calling remote for function

### ISSUE THREAD

**Issue by magerstein** [ray-project/ray#31607]
**What happened**
I have a GCP VM with 112 vCPUs and 896GB RAM.  I'm using Ray to score 2100 of logistic regression models.  I have a very large Scipy sparse matrix that I'm loading into shared memory that I slice to fit each model in parallel.  I'm initializing Ray with num_cpus=96.  When I call func.remote(args) in a list compression to create futures for 2100 calls to my score function, I get `(pid=67127) <jemalloc>: arena 0 background thread creation failed (11)`.  The script does not return any results event though futures continue to be generated and I continue to see the jemalloc error.

The error goes away if a lower num_cpus=80 and the script runs successfully.

**What you expected to happen**
Not expecting a thread error as I'm only using 96 out of 112 cpus.

**Version**
Debian GNU/Linux 10 (buster)
Ray 2.2.0

**Reproduction script**

```
ray.init(num_cpus=96)

feature_matrix_ref = ray.put(feature_matrix)
feature_flds_map_ref = ray.put(feature_flds_map)
cust_ids_ref = ray.put(cust_ids)

ray_futures = []
scores = []

for idx, row in df.iloc[:num_cpus].iterrows():
    ray_futures.append(score_model.remote(use_case, attribute, end_point, feature_matrix_ref, feature_flds_map_ref, cust_ids_ref)
    sleep(2)

idx = num_cpus    

while True:
    ready_ids, ray_futures = ray.wait(ray_futures, num_returns=1)
    scores.append(ray.get(ready_ids))
    
    if idx < len(df):
        row = df.loc[idx]
        ray_futures.append(score_model.remote(use_case, attribute, end_point, feature_matrix_ref, feature_flds_map_ref, cust_ids_ref))
        idx += 1
        sleep(1)

    if len(ray_futures) == 0:
        break
```

**Issue Severity**
Low.  I would like to take advantage of as many cores as possible when running Ray.

**Comment by rkooo567** [comment]
Seems like the error means there's not enough resources to create new threads https://stackoverflow.com/questions/31930947/perl-thread-creation-failed-pthread-create-returned-11

Ray creates additional threads (and jemalloc also can create its own thread pool I believe) for each worker, and I think your thread limit is probably not high enough. https://stackoverflow.com/questions/35696399/maximum-number-of-threads-allowed-to-run
