### ISSUE TITLE
[Core] Actors end up without gpu access in too (?) finegraned allocation

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#31605]
### What happened + What you expected to happen

When spawning actors with some small gpu fraction, I'd expect them to either be allocated that fraction or raise a warning/error out if they receive no gpu fraction.

Dashboard displaying that there is no GPU associated:
<img width="1436" alt="Screen Shot 2023-01-11 at 12 34 40 PM" src="https://user-images.githubusercontent.com/9356806/211912079-fbae66ee-17e3-40ac-b32b-9afef7f8f67c.png">

### Versions / Dependencies

master
Some g3 instance with plenty of GPU

### Reproduction script

import ray
import time

@ray.remote(num_gpus=2/22)
class SomeActor:
    pass

[SomeActor.remote() for i in range(21)]

while True:
    time.sleep(1)

### Issue Severity

None

**Comment by rkooo567** [comment]
If you don't use the fraction, dashboard still doesn't show the GPU usage?

**Comment by ArturNiederfahrenhorst** [comment]
If you use a larger fraction, dashboard shows the correct fraction!

**Comment by ArturNiederfahrenhorst** [comment]
I'm closing this issue since we don't ever provide GPU Util on an actor basis.
