### ISSUE TITLE
[CI] `linux://:pubsub_integration_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#31612]
It has 30% yellow build. Highly likely the testing issue rather than the correctness issue though. 

<img width="1665" alt="Screen Shot 2023-01-11 at 3 01 44 PM" src="https://user-images.githubusercontent.com/18510752/211936659-0caa3a98-6f24-41dd-ab68-3072250ae188.png">

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:pubsub_integration_test-END
....

**Comment by iycheng** [comment]
https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/src/ray/pubsub/test/integration_test.cc?L293-301
We should just try to cancel the request.

**Comment by rickyyx** [comment]
Any updates on this?

**Comment by iycheng** [comment]
no.

**Comment by iycheng** [comment]
I think I'm just going to increase 15 -> 60 maybe to see how things are going.
