### ISSUE TITLE
Error migrating from rllib 1.1.0 to 2.0.0 RayActorError [<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by siantist** [ray-project/ray#31630]
### What happened + What you expected to happen

I am running code that creates the RLlib trainer from the train_with_rlib code in https://github.com/mila-iqia/climate-cooperation-competition/blob/main/scripts/train_with_rllib.py within the create_trainer function: 
```
rllib_trainer = A2CTrainer(
        env=EnvWrapper,
        config=get_rllib_config(
            exp_run_config=exp_run_config, env_class=EnvWrapper, seed=seed
        ),
    )
```

The error that shows up is:

Traceback (most recent call last):
  File "scripts/train_with_rllib.py", line 502, in <module>
    trainer, save_dir = create_trainer(run_config)
  File "scripts/train_with_rllib.py", line 312, in create_trainer
    exp_run_config=exp_run_config, env_class=EnvWrapper, seed=seed
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/a2c/a2c.py", line 139, in setup
    super().setup(config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/a3c/a3c.py", line 161, in setup
    super().setup(config)
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 446, in setup
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/algorithms/algorithm.py", line 425, in setup
    logdir=self.logdir,
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 127, in __init__
    validate=trainer_config.get("validate_workers_after_construction"),
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/opt/conda/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: RolloutWorker
	actor_id: a55c46e2906ee7041a57bbeb01000000
	namespace: b33bcd4c-a0f2-468e-8479-303a92b1cb9d
The actor is dead because its owner has died. Owner Id: 01000000ffffffffffffffffffffffffffffffffffffffffffffffff Owner Ip address: 172.17.0.3 Owner worker exit type: SYSTEM_ERROR Worker exit detail: Owner's node has crashed.
The actor never ran - it was cancelled before it started running.
make: *** [train] Error 1
 
Edit/Note: I saw from https://github.com/ray-project/ray/issues/5820 that the actor will exit if the original handle to the actor is out of scope and to use 
```
c = Counter.remote()
named_actors.register_actor("global_counter", c) 
```
but I do not know where to change the code for named_actors.register_actor.

### Versions / Dependencies

Ray version 2.0.0
tensorflow==2.6.2
gym==0.23.1
ray=2.0.0
torch==1.9.0

### Reproduction script

python train_with_rllib.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Someone will have to put in the effort of upgrading [the script you referenced](https://github.com/mila-iqia/climate-cooperation-competition/blob/main/scripts/train_with_rllib.py) to use the higher level abstractions of ray 2.0 (or even better, 2.2). Without looking at the other repository in depth, I consider it highly unlikely that you'll need to change `named_actors.register_actor`.

The error message you posted is also missing the actual error itself. The error you posted shows the RolloutWorker dying, but there is an underlying reason it died which should have it's own error message. It might be something with the custom environment that needs migration.

Have a look at our migration guides for [Ray](https://docs.google.com/document/d/12ODPbhEzeyDRUt8ehHDiKCFoxksPWJOUNEicGhNxtRg/edit#) and more importantly for [RLlib](https://docs.google.com/document/d/1a3UEHEz6_Jth9O_2GR9Qp9c9IFyD5dObHCNSBsRgPGU/edit#heading=h.syyxjoxfu544)!

**Comment by siantist** [comment]
Thank you for the migration guides. 
Is the problem in the import in train_with_rllib.py,
```
from ray.rllib.agents.a3c import A2CTrainer
```
Do you know how to call the A2CTrainer in 2.0.0?

In ray/rllib/algorithms/a3c/a3c.py file, they have an example, 
```
Example:
 35         >>> from ray import tune
 36         >>> config = A3CConfig().training(lr=0.01, grad_clip=30.0)\
 37         ...     .resources(num_gpus=0)\
 38         ...     .rollouts(num_rollout_workers=4)
 39         >>> print(config.to_dict())
 40         >>> # Build a Algorithm object from the config and run 1 training iteration.
 41         >>> trainer = config.build(env="CartPole-v1")
 42         >>> trainer.train()
```
Do you know if I have to change my input arguments to 
```
rllib_trainer = A2CTrainer(
        env=EnvWrapper,
        config=get_rllib_config(
            exp_run_config=exp_run_config, env_class=EnvWrapper, seed=seed
        ),
    )
```
? 

Also, if they import A2CTrainer from the a3c folder and not the a2c folder, how is it different from importing from a2c.py?

**Comment by ArturNiederfahrenhorst** [comment]
In 2.0.0, you should just import A2C from ray.rllib.algorithms.a2c, together with it's config.
A2CTrainer is an alias nowadays to help people with old code, but we are deprecating it.
I'm not sure why you would import A2C from A3C instead of A2C, but it makes no difference, it's still the same A2C algorithm. Have you read the migration guides?
