### ISSUE TITLE
[RLlib] Cartpole cannot be run in 2.2.0

### ISSUE THREAD

**Issue by Pavel-Konarik** [ray-project/ray#31636]
### What happened + What you expected to happen

Attempting to run [cartpole_lstm.py](https://github.com/ray-project/ray/blob/master/rllib/examples/cartpole_lstm.py)
results in an error

```
File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/examples/env/stateless_cartpole.py", line 39, in reset
    return np.array([init_obs[0], init_obs[2]])
IndexError: tuple index out of range
```

Larger output
```
2023-01-12 15:48:03,300 ERROR trial_runner.py:1088 -- Trial PPO_StatelessCartPole_1a8b3_00000: Error processing event.
ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/tune/execution/ray_trial_executor.py", line 1070, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=179268, ip=192.168.1.201, repr=PPO)
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 239, in _setup
    self.add_workers(
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 612, in add_workers
    raise result.get()
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 473, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=179501, ip=192.168.1.201, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f893c61e6a0>)
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/utils/pre_checks/env.py", line 173, in check_gym_environments
    reset_obs = env.reset()
  File "/home/pavel/miniconda3/envs/ray3/lib/python3.9/site-packages/ray/rllib/examples/env/stateless_cartpole.py", line 39, in reset
    return np.array([init_obs[0], init_obs[2]])
IndexError: tuple index out of range
```

Similar (but no the same) error when using CartPole-v1 instead of stateless cartpole environment.
Edits: Struggling with code formatting

### Versions / Dependencies

OS: Ubuntu 22.04.1 LTS
Ray: 2.2.0

Pip Freeze:
absl-py==1.4.0
accelerate==0.5.1
aiohttp==3.8.3
aiosignal==1.3.1
ale-py==0.8.0
alembic==1.4.1
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
cached-property==1.5.2
cachetools==5.2.1
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi==1.15.1
charset-normalizer==2.1.1
chex==0.1.5
click==8.1.3
cloudpickle==2.2.0
coloredlogs==15.0.1
commonmark==0.9.1
contourpy==1.0.6
coolname==1.1.0
cycler==0.11.0
Cython==0.29.33
databricks-cli==0.17.4
datasets==2.0.0
decorator==5.1.1
dill==0.3.6
distlib==0.3.6
dm-tree==0.1.8
docker==6.0.1
docstring-parser==0.15
dopamine-rl==4.0.5
entrypoints==0.4
etils==1.0.0
exceptiongroup==1.1.0
fasteners==0.18
filelock==3.9.0
Flask==2.2.2
flatbuffers==1.12
flax==0.6.3
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2022.11.0
gast==0.4.0
gin-config==0.5.0
gitdb==4.0.10
GitPython==3.1.30
glfw==2.5.5
google-auth==2.16.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet==2.0.1
grpcio==1.51.1
gunicorn==20.1.0
gym==0.26.2
gym-notices==0.0.8
Gymnasium==0.26.3
gymnasium-notices==0.0.1
h5py==3.7.0
higher==0.2.1
huggingface-hub==0.11.1
humanfriendly==10.0
idna==3.4
imageio==2.24.0
imageio-ffmpeg==0.4.5
importlib-metadata==4.13.0
importlib-resources==5.10.2
iniconfig==2.0.0
itsdangerous==2.1.2
jax==0.4.1
jaxlib==0.4.1
Jinja2==3.1.2
jsonschema==4.7.2
kaggle-environments==1.7.11
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==15.0.6.1
lz4==4.3.2
Mako==1.2.4
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.3
Minigrid==2.1.0
mlagents-envs==0.28.0
mlflow==1.21.0
mosaicml==0.10.1
mpmath==1.2.1
msgpack==1.0.4
mujoco==2.2.0
mujoco-py==2.1.2.14
multidict==6.0.4
multiprocess==0.70.14
networkx==3.0
numpy==1.22.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
onnx==1.12.0
onnxruntime==1.12.0
open-spiel==1.2
opencv-python==4.7.0.68
opt-einsum==3.3.0
optax==0.1.4
orbax==0.1.0
packaging==21.3
pandas==1.5.2
PettingZoo==1.22.1
Pillow==9.4.0
platformdirs==2.6.2
pluggy==1.0.0
prometheus-client==0.15.0
prometheus-flask-exporter==0.21.0
protobuf==3.19.6
psutil==5.9.4
py-cpuinfo==8.0.0
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyDeprecate==0.3.2
pygame==2.1.2
pyglet==1.5.15
Pygments==2.14.0
PyJWT==2.6.0
pymunk==6.2.1
PyOpenGL==3.1.6
pyparsing==3.0.9
pyrsistent==0.19.3
pytest==7.2.0
python-dateutil==2.8.2
python-editor==1.0.4
pytorch-ranger==0.1.1
pytz==2022.7
PyWavelets==1.4.1
PyYAML==6.0
querystring-parser==1.2.4
ray==2.2.0
recsim==0.2.4
regex==2022.10.31
requests==2.28.1
requests-oauthlib==1.3.1
responses==0.18.0
rich==12.0.1
rsa==4.9
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.19.3
scipy==1.10.0
sentencepiece==0.1.96
six==1.16.0
smmap==5.0.0
SQLAlchemy==1.4.46
sqlparse==0.4.3
SuperSuit==3.7.0
sympy==1.11.1
tabulate==0.8.10
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.4.1
tensorflow==2.9.0
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.29.0
tensorflow-probability==0.17.0
tensorstore==0.1.30
termcolor==2.2.0
tf-slim==1.1.0
tf2onnx==1.12.1
tifffile==2022.10.10
tinyscaler==1.2.5
tokenizers==0.12.1
tomli==2.0.1
toolz==0.12.0
torch==1.12.1+cpu
torch-optimizer==0.3.0
torchmetrics==0.7.3
torchvision==0.13.1+cpu
tqdm==4.64.1
transformers==4.19.1
typer==0.6.1
typing_extensions==4.4.0
urllib3==1.26.14
virtualenv==20.17.1
websocket-client==1.4.2
Werkzeug==2.2.2
wrapt==1.14.1
xxhash==3.2.0
yahp==0.1.3
yarl==1.8.2
zipp==3.11.0

### Reproduction script

conda create -n ray python=3.9
conda activate ray
pip install "ray[rllib]" tensorflow torch
// Install deps
pip install -r https://raw.githubusercontent.com/ray-project/ray/master/python/requirements/ml/requirements_train.txt
pip install -r https://raw.githubusercontent.com/ray-project/ray/master/python/requirements/ml/requirements_rllib.txt
pip install -r https://raw.githubusercontent.com/ray-project/ray/master/python/requirements/ml/requirements_dl.txt
pip install -r https://raw.githubusercontent.com/ray-project/ray/master/python/requirements/ml/requirements_tune.txt
// Downgrade numpy due to #31293 
pip install numpy==1.23.5
python cartpole_lstm.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi, please always install the requirements from the version that you are installing.
If you are install ray 2.2, please install the requirements for ray 2.2 instead of the ones of our master branch.
Can you try that and see if it solves your problem?

**Comment by Pavel-Konarik** [comment]
It works like a charm, facepalm. Thank you for the sanity check.
