### ISSUE TITLE
"object already exists in the plasma store" 

### ISSUE THREAD

**Issue by valiantljk** [ray-project/ray#3163]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: SUSE Linux, Linux version 4.4.143
- **Ray installed from (source or binary)**: pip 
- **Ray version**: 0.5.3
- **Python version**: 3.6.6
- **Exact command to reproduce**: 

### Describe the problem
I have launched two MPI processes on the same node, and each process will call client to 
put a object into the plasma store, but it seems only one rank can put successfully, the second rank always fails with error "object already exists in the plasma store",

### Source code / logs
https://github.com/NERSC/pyprob/blob/distributed/plasma_mpi.py

**Comment by pia-ai** [comment]
the ""object already exists in the plasma store" error is caused by the same ObjectID, which is generated by the random.getrandbits(8) function,  has already defined in the plasma store.  the conflict is rare, do you have tried again? and the lib/random.py has not been modified?

**Comment by valiantljk** [comment]
Hi, I think you are right, I'm now able to to use multiple MPI clients to put objects, with user-defined object ID. I think the random.py is producing same objectID for those clients.

**Comment by valiantljk** [comment]
I think we can close this, unless there is an easy way to avoid the conflict of objectID in distributed environment.
