### ISSUE TITLE
Cannot copy a copy of an actor

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3166]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: latest a221f55b0d611de29324e3b1aa79eec1c10458ba
- **Python version**: 3.6.5
- **Exact command to reproduce**:
<pre>
import copy
import ray
from ray.rllib.utils import merge_dicts
ray.init()
@ray.remote
class Foo(object):
    def __init__(self):
        pass

foo = {"dummy": Foo.remote()}
foo_1 = merge_dicts(foo, {})
foo_2 = merge_dicts(foo_1, {})    # TypeError: a bytes-like object is required, not 'NoneType'
"""
or
"""
foo = Foo.remote()
foo_1 = copy.deepcopy(foo)
foo_2 = copy.deepcopy(foo_1)    # TypeError: a bytes-like object is required, not 'NoneType'
</pre>

Is this expected?

**Comment by ericl** [comment]
I don't think actor handles are copyable via copy. You should be able to pickle and unpickle them to achieve the same thing though.
