### ISSUE TITLE
[Core] Provide log file garbage collection  

### ISSUE THREAD

**Issue by MisterLin1995** [ray-project/ray#31689]
### Description

Make ray delete garbage(too old and not in use) log files automatically.

### Use case

Sometimes, we find our ray cluster worker nodes full of log files which makes it difficult to find the log we want, or in some extreme cases, it prevents the raylet from creating more workers since all inodes are taken up. This can happen we use long running ray clusters, or our applications create a lot of normal tasks or some actors frequently failover.

Currently we modified the dashboard log agent to do a periodically log file garbage collection to delete not in use and old enough log files. Also, we have a per node per job log number limit to prevent single job’s failover caused log number explosion.

I'd like to introduce this feature to ray and ask for suggestions on the best practice of log file garbage collection.

**Comment by jovany-wang** [comment]
It's useful for the production.

Are you going to delete the rotated log files?

**Comment by MisterLin1995** [comment]
>

**Comment by MisterLin1995** [comment]
> It's useful for the production.
> 
> Are you going to delete the rotated log files?

Well, in my original design, rotated log files will not be deleted when the process created them is still alive. But I guess it's possible and maybe useful to delete rotated log files.

**Comment by MisterLin1995** [comment]
> It's useful for the production.
> 
> Are you going to delete the rotated log files?

Well, in my original design, rotated log files will not be deleted when the process created them is still alive. But I guess it's possible and maybe useful to delete rotated log files.
