### ISSUE TITLE
[RLlib] Segmentation fault while using the OpenSpielEnv Wrapper with the Open Spiel Chess Environment

### ISSUE THREAD

**Issue by EpicLiem** [ray-project/ray#31687]
### What happened + What you expected to happen

I am experiencing a segmentation fault when attempting to train a chess agent using Open Spiel and RLlib. I have been using the Self Play with Open Spiel example script as a reference, but have replaced the connect_four environment with the chess environment. Furthermore, I have narrowed the issue down to the step function.

### Versions / Dependencies

OS=ubuntu 22.04
Tensorflow=2.11.0
Cuda=11.8
Nvidia Driver=520.56.06 \
Ray=2.2.0
OpenSpiel=1.2

### Reproduction script

```python
from ray.rllib.env.wrappers.open_spiel import OpenSpielEnv
import pyspiel


env = OpenSpielEnv(pyspiel.load_game("chess"))
env.num_agents = 2
env.reset()
state = env.action_space

while True:
    action = env.action_space.sample()
    print("action obtained")
    env.step(action=[env.state.current_player(), action])
    print("action executed")
    env.render(mode='human')
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @EpicLiem ,

I've played around with this and am confident that `OpenSpielEnv ` behaves fine.
Sadly, you can't simply catch a segfault so i don't know the exact offending line.
But it's almost certainly an error inside OpenSpiel that is not properly caught and raised to us.
Choosing valid actions might get rid of this problem.
We won't be able to fix this within the scope of RLlib, but maybe someone over at [openspiel](https://github.com/deepmind/open_spiel/issues) can shed some light on this.
I'm sorry that I can't be of any help here.

**Comment by ArturNiederfahrenhorst** [comment]
Feel free to reopen this if I've missed something though 🙂
