### ISSUE TITLE
[Ray cluster] Ray head pod not recreated when k8s worker dies

### ISSUE THREAD

**Issue by thien-nguyenthanh** [ray-project/ray#31690]
### What happened + What you expected to happen

For some reason, k8s replaces a worker that Ray's head is running on. 
Ray operator doesn't recreated Ray head.

### Versions / Dependencies

Ray 2.0.0
Python 3.7.7
OS: ubuntu 18.04

### Reproduction script

no

### Issue Severity

High: It blocks me from completing my task.

**Comment by DmitriGekhtman** [comment]
Could you describe your K8s setup?

**Comment by thien-nguyenthanh** [comment]
Hi @DmitriGekhtman 
I am running on AKS v1.23.12
Each Pod runs on entire k8s worker.

**Comment by DmitriGekhtman** [comment]
Are you using the (officially recommended) KubeRay operator to deploy your Ray cluster? If so, which version of the operator?

**Comment by thien-nguyenthanh** [comment]
@DmitriGekhtman Unfortunately, I am using ray-cluster helm chart. 
I am also planing to migrate to KubeRay.

**Comment by DmitriGekhtman** [comment]
I'd recommend migrating to KubeRay, which also has Helm charts for deployment.
The older operator is not maintained.
