### ISSUE TITLE
[RLlib] CQL Release Test is failing

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#31720]
### What happened + What you expected to happen

<img width="1357" alt="Screenshot 2023-01-17 at 17 15 46" src="https://user-images.githubusercontent.com/9356806/213056920-04a77179-14d0-46e8-b624-85fa3f7103c6.png">

https://buildkite.com/ray-project/release-tests-branch/builds/1289#_

### Versions / Dependencies

master

### Reproduction script

release tests

### Issue Severity

None

**Comment by cadedaniel** [comment]
Reopening this. With the Revert PR this fails for a different reason:
```
Analyzing experiment cql-halfcheetah-v4-torch ...
 ... Trials: [CQL_HalfCheetah-v4_93e99_00000].
 ... Desired reward=400.0; desired throughput=None
 ... Not successful: Actual reward=-260.1843278919615; actual throughput=3281.3059066157193
Traceback (most recent call last):
  File "learning_tests/run.py", line 66, in <module>
    "Not all learning tests successfully learned the tasks.\n"
ValueError: Not all learning tests successfully learned the tasks.
Results=
{'time_taken': 7422.460222625, 'trial_states': {'TERMINATED': 2}, 'last_update': 1674344487.999516, 'stats': {'cql-halfcheetah-v4-torch': {'episode_reward_mean': -260.1843278919615, 'throughput': 3281.3059066157193}}, 'passed': [], 'not_passed': ['cql-halfcheetah-v4-torch'], 'failures': {'cql-halfcheetah-v4-torch': 2}}
```

The run was on commit a830694359a272703aace4ac6f7e5f98b1d5d4a9, which has the revert PR: [git log](https://gist.github.com/cadedaniel/04876bc781cfd9d740eb74f49a098c93)

**Comment by cadedaniel** [comment]
cc @kouroshHakha

**Comment by kouroshHakha** [comment]
This the known regression of CQL due to data upgrades that we had.
