### ISSUE TITLE
[Serve] `long_running_serve_failure` is unstable

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#31741]
### What happened + What you expected to happen

The `long_running_serve_failure` test is unstable. It passes roughly 50% of the time:

<img width="600" alt="Screen Shot 2023-01-18 at 10 15 09 AM" src="https://user-images.githubusercontent.com/92341594/213261698-7abc7757-b8f0-47a0-a46a-63c76852b69a.png">

This test should be made stable for Ray 2.3.

### Versions / Dependencies

Ray on the current master.

### Reproduction script

`long_running_serve_failure` runs [this script](https://github.com/ray-project/ray/blob/7f431d705345fd99978ff97d10c0c92b7aec5d27/release/long_running_tests/workloads/serve_failure.py) over a long period of time.

### Issue Severity

None

**Comment by cadedaniel** [comment]
Bumping to release blocker, per @shrekris-anyscale this is to be made stable before 2.3. cc @sihanwang41

**Comment by cadedaniel** [comment]
What's the status here? Is someone actively working on it?

**Comment by shrekris-anyscale** [comment]
Yep, I'm working on it.

**Comment by shrekris-anyscale** [comment]
#31945 should address this issue. I kicked off a release test run to confirm: https://buildkite.com/ray-project/release-tests-branch/builds/1312#_

**Comment by shrekris-anyscale** [comment]
I started a test run, and it has been running successfully for 15+ hours without failing: https://buildkite.com/ray-project/release-tests-branch/builds/1319#_

I'll follow up with a PR that marks the release test as stable and adds an iteration limit, so it doesn't run forever.

**Comment by cadedaniel** [comment]
do you know if this release test has your latest fix?

https://buildkite.com/ray-project/release-tests-branch/builds/1318#0185fc29-1d52-4529-9222-5cddea6b4167

**Comment by Wordyka** [comment]
How to reproduce this bug?
