### ISSUE TITLE
[RLlib] Policy Server example (Simple cartpole env) throws RayActorError

### ISSUE THREAD

**Issue by YDenker** [ray-project/ray#31774]
### What happened + What you expected to happen

I tried to run the cartpole_server.py with a single worker as described in the description. I haven't made any changes to the script. 
$ python cartpole_server.py --num-workers 1
The resulting error file is attached:
[error.txt](https://github.com/ray-project/ray/files/10456654/error.txt)

ray.exceptions.RayActorError: The actor died because of an error raised in its creation task

### Versions / Dependencies

Ray-2.2.0 (i used the script from the main branch today (19-01-23)
Python 3.10.6
OS: Ubuntu 22.04.1 LTS

### Reproduction script

Literally the example script linked by the documentation:
https://github.com/ray-project/ray/blob/master/rllib/examples/serving/cartpole_server.py

### Issue Severity

None

**Comment by ArturNiederfahrenhorst** [comment]
Hey @YDenker ,

I can not reproduce this. Neither on master nor on Ray 2.2.0.
Are you using the plain example script? Without any modifications?

**Comment by YDenker** [comment]
Yes. This is a brand new Computer setup. I installed everything new including Ray 2.2.0. I copied the cartpole_server.py exactly as is into a separate file and tried to execute it with the above mentioned command.
I want to do modifications to the code eventually, but for now i left it as is.
