### ISSUE TITLE
[gcs][autoscaler] Stabilize the GCS/Autoscaler interface

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#31826]
### What happened + What you expected to happen

This is a tracking issue to stabilize the GCS/Autoscaler interface. Note this is a bug since multiple projects including kuberay expect this even though it isn't true!

[ ] Scheduling demands
[✅] Drain node
[ ] Internal KV (`ray status`) 
[ ] Internal KV (legacy info string) -- We may be able to just delete this one
[ ] Internal KV misc (like session_name) 
[ ] Prometheus metrics
[ ] Events

### Versions / Dependencies

Latest master

### Reproduction script

Swap the order of fields in `InternalKVGetRequest` in `gcs_service.proto` and run kuberay against this "nightly" build. `ray status` will stop working correctly.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
This is replaced by autoscaler v2 work.
