### ISSUE TITLE
Export checkpoint to TensorFlow or Torch model

### ISSUE THREAD

**Issue by cumberb1tch** [ray-project/ray#3183]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: installed by pip
- **Ray version**: 0.5.3
- **Python version**: 3.5.2
- **Exact command to reproduce**: None

### Describe the problem

I trained A3C model with Ray and as the result I have Ray checkpoints.
Is there an option to convert them to TensorFlow checkpoint or to Torch model?
Thank you for your help!

**Comment by ericl** [comment]
Hi, you can restore the agent and then use https://ray.readthedocs.io/en/latest/rllib-training.html#accessing-policy-state to generate a TF checkpoint if you want.

**Comment by cumberb1tch** [comment]
@ericl, thank you for confirming that it is real. But could you please kindly provide code snippet on how to do it? This seems non documented from my point of view.

**Comment by richardliaw** [comment]
should be supported in #3637. Please open a new issue if you have a different use case.
