### ISSUE TITLE
[Tune] Add TimeoutStopper for a single trial

### ISSUE THREAD

**Issue by nikosavola** [ray-project/ray#31849]
### Description

tune.stoppers could include a stopper for limiting the maximum time of a single trial, so like `MaximumIterationStopper` but for time.

Implementation would look very similar to [TimeoutStopper](https://docs.ray.io/en/latest/tune/api_docs/stoppers.html#id5)

### Use case

This would be useful when applying Ray Tune for trials with very long iterations (~hrs) that seem to not converge, but there is currently no mechanism to end these.

**Comment by justinvyu** [comment]
@nikosavola It's possible to get trial-level stopping based on time using something like:

```
from ray.tune import Tuner
from ray.air import RunConfig

tuner = Tuner(
    ...,
    run_config=RunConfig(
        stop={"time_total_s": 100},  # 100 seconds
    ),
)
```

`time_total_s` is added automatically to every trial result. Let me know if this is what you're looking for!

**Comment by justinvyu** [comment]
> I guess the Stoppers are called only after an iteration is finished. Maybe this is then better to do inside the trainable function with something like https://stackoverflow.com/questions/366682/how-to-limit-execution-time-of-a-function-call.

Yes, stoppers won't guarantee that your script runs for exactly N seconds, so the way you suggest would be a better way if you need more accurate stopping based on time.
