### ISSUE TITLE
[Ray API] io.ray.api.exception.RayActorException: The actor <id> died unexpectedly before finishing this task.

### ISSUE THREAD

**Issue by soodankit91** [ray-project/ray#31857]
### What happened + What you expected to happen

I am trying to invoke a python remote function from Java, using the exact same code as mentioned here:
https://docs.ray.io/en/latest/ray-core/cross-language.html#java-calling-python

I got this error:
root@<user>-ubuntu:/dev/Ray_Java/target# java -jar Ray_Java-1.0-SNAPSHOT-jar-with-dependencies.jar 
2023-01-23 11:00:10,206 INFO RunManager [main]: Ray runtime started @ _<ip>_.
Exeception occured The actor <id> died unexpectedly before finishing this task.
io.ray.api.exception.RayActorException: The actor 598f935b09bd3b6d54526d1301000000 died unexpectedly before finishing this task.
        at io.ray.runtime.object.ObjectSerializer.deserializeActorException(ObjectSerializer.java:257)
        at io.ray.runtime.object.ObjectSerializer.deserialize(ObjectSerializer.java:104)
        at io.ray.runtime.object.ObjectStore.get(ObjectStore.java:140)
        at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:144)
        at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:125)
        at io.ray.runtime.AbstractRayRuntime.get(AbstractRayRuntime.java:120)
        at io.ray.api.Ray.get(Ray.java:98)
        at io.ray.runtime.object.ObjectRefImpl.get(ObjectRefImpl.java:77)
        at demo.JavaCallPythonDemo.main(JavaCallPythonDemo.java:26)

JavaCallPythonDemo.java:26 is :
Assert.assertEquals(objRef1.get(), 1);

### Versions / Dependencies

OS: Ubuntu 20.04 [LTS]
Python: 3.8.10
Java: OpenJDK 11.0.17
Ray: 2.2
Apache Maven: 3.6.3 

### Reproduction script

[RayActor.zip](https://github.com/ray-project/ray/files/10480512/RayActor.zip)
I tried to run this example, in a single node cluster:
https://docs.ray.io/en/latest/ray-core/cross-language.html#java-calling-python. I've attached the Java and python files as zip. 
I have overwritten ray.conf file and specified run-mode as 'CLUSTER'
I am using this in a stand-alone maven project and have specified ray-api and ray-runtime dependencies in pom.xml. 
I have included maven-assembly plugin and am creating jar of this project using 'mvn install' and then later running this jar (having specified JavaCallPythonDemo.java as the main class).

I was able to initialize Ray from Java and run the jar generated by maven successfully. Here's a code for the same:

`package demo;

import io.ray.api.Ray;

public class RayInit {
    public static void main(String args[]) {
        Ray.init();
        System.out.println("is ray initialized: "+Ray.isInitialized());
        Ray.shutdown();
    }
}`

### Issue Severity

High: It blocks me from completing my task.

**Comment by scv119** [comment]
@jovany-wang would you be the right owner for this?

**Comment by jovany-wang** [comment]
> @jovany-wang would you be the right owner for this?
Sure/

Hi @soodankit91 sorry for the delay response as I didn't notice this issue.

**Comment by jovany-wang** [comment]
I guess the reason is we wrote a wrong package name for the python actor? Could you upload your python worker logs?
The log directory is `/tmp/ray/session_latest/logs`, you could upload the log directory.

**Comment by jovany-wang** [comment]
@XiaodongLv CC

**Comment by jovany-wang** [comment]
Also, you need to check whether your `ray_demo.py` is in your `PYTHONPATH`.
Otherwise I believe you need to specify the `code-search-path` configuration item in `ray.conf`. See https://github.com/ray-project/ray/blob/master/java/runtime/src/main/resources/ray.default.conf#L29

**Comment by XiaodongLv** [comment]
Hello, I have tested locally and have the same problem as you. I think about some questions,
1. We can view log files located in /tmp/ray/session_latest/logs, you will find error info, "No module named 'ray_demo'".
2. As you see, if the python file isn't in the resource directory, it won‘t be packaged in Jar.
3. If we submit Job, it must be failed.

So, I agree with @jovany-wang. 
More， If you have cloned ray, maybe can refer to the file named CrossLanguageInvocationTest.java in ray project, will you got it.

Best wishes!

**Comment by jovany-wang** [comment]
Maybe we should update the doc.

**Comment by jovany-wang** [comment]
It's not a bug, we should just let users know how we add the python file into the package path.

**Comment by soodankit91** [comment]
Thank you all for your response. I got busy with another project so I couldn’t check this. I'll try your suggestions.
