### ISSUE TITLE
[RLLIB] Example script not working

### ISSUE THREAD

**Issue by ArtRestoreAI** [ray-project/ray#31853]
### Description

when I try to run this example:
https://github.com/ray-project/ray/blob/master/rllib/examples/coin_game_env.py

I get the following error:

`AttributeError: 'AsymCoinGame' object has no attribute 'observation_space'`

### Link

https://github.com/ray-project/ray/blob/master/rllib/examples/coin_game_env.py

And the environment script is:
https://github.com/ray-project/ray/blob/master/rllib/examples/env/coin_game_non_vectorized_env.py

This is the class definition:

```
class AsymCoinGame(CoinGame):
    NAME = "AsymCoinGame"

    def __init__(self, config: Optional[dict] = None):
        if config is None:
            config = {}

        if "asymmetric" in config:
            assert config["asymmetric"]
        else:
            config["asymmetric"] = True
        super().__init__(config)
```

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for raising this! I've opened a PR to fix this.
