### ISSUE TITLE
[Dataset] `Dataset.to_pandas()` method incorrectly converts tables with a nested dict column

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#31860]
### What happened + What you expected to happen

If a Dataset contains a column with a nested dictionary containing a multi-dimensional numpy array, calling `to_pandas()` on the Dataset fails to correctly parse the columns by the top-level dict key name. See the below reproducible example for more details.

### Versions / Dependencies

Ray master

### Reproduction script

```
import numpy as np
import ray

>>> data = [{"dict_c": {"a": np.array([[1,2,3],[4,5,6]])}, "int_c": 1}]
>>> df = ray.data.from_items(data).to_pandas()
>>> df
                                      value
0  {'dict_c': {'a': [[1 2 3], [4 5 6]]}, 'int_c': 1}
```
We expect the converted `pd.DataFrame` to have two columns: one named `'dict_c'` which contains the dict, and another named `'int_c'` which contains an int. However, the resulting DataFrame contains a single column named `'value'` instead.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scottjlee** [comment]
Currently, we cannot construct a pyarrow array from multi-dimensional inputs:
```
>>> pa.Table.from_pydict({"a": np.array([[1,2],[3,4]])})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 1724, in pyarrow.lib.Table.from_pydict
  File "pyarrow/table.pxi", line 2368, in pyarrow.lib._from_pydict
  File "pyarrow/array.pxi", line 341, in pyarrow.lib.asarray
  File "pyarrow/array.pxi", line 311, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: only handle 1-dimensional arrays
```

This is the underlying root cause for why the reproducible script fails. When we try to build an `ArrowBlock`, the `_table_from_pydict()` call fails due to the above exception, resulting in falling back to constructing a `SimpleBlock` instead. As a result, when we call `.to_pandas()` on the resulting Dataset, this calls `SimpleBlockAccessor.to_pandas()`, which yields the DataFrame with a single `'values'` column: https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/simple_block.py#L96-L99

@clarkzinzow Is this construction of a Pyarrow table from a multi-dimensional array something that we expect to support in the near future?

**Comment by clarkzinzow** [comment]
@scottjlee Ideally Arrow would delegate to our tensor extension type when it encounters a NumPy ndarray in the attempted `pa.Table.from_pydict()`, but since that isn't possible yet, or only other alternative would be checking every column in the dictionary to see if it's a list of ndarrays. We already do something similar when casting from Pandas to Arrow, so doing that on table construction from the dict-of-column-lists seems reasonable to me.

I think doing an O(columns) check here would be best, where we only check if the first element in a column is an ndarray. How does that sound to you?

**Comment by scottjlee** [comment]
@clarkzinzow yeah makes sense, I tried implementing a check over each element of a dict element. Now the input `columns` into `pyarrow.Table.from_pydict(columns)` was:
```
defaultdict(<class 'list'>, {'A': [2], 'ndarr': <ray.air.util.tensor_extensions.arrow.ArrowTensorArray object at 0x13f12f580>
[
  [
    9,
    10,
    11,
    12
  ]
], 'nested': [{'nested_scalar_col': -3, 'nested_bool_col': True, 'nested_list_col': [7, 8, 9], 'nested_arr_col': <ray.air.util.tensor_extensions.arrow.ArrowTensorArray object at 0x13f12f460>
[
  [
    9,
    10,
    11
  ],
  [
    12,
    13,
    14
  ]
]}]})
```

but I still get this conversion error:
```
Could not convert <ray.air.util.tensor_extensions.arrow.ArrowTensorArray object at 0x13a2af040>
[
  [
    0,
    1,
    2
  ],
  [
    3,
    4,
    5
  ]
] with type ArrowTensorArray: did not recognize Python value type when inferring an Arrow data type
```
even after converting the ndarray inside the dict to a `ArrowTensorArray`. Am I approaching this incorrectly here or is this still not going to be supported by Arrow?

**Comment by scottjlee** [comment]
Looks like the reproducible example no longer has the error, so closing the issue. Please feel free to reopen if it is not resolved.
```
>>> data = [{"dict_c": {"a": np.array([[1,2,3],[4,5,6]])}, "int_c": 1}]
>>> df = ray.data.from_items(data).to_pandas()
>>> df
                          dict_c  int_c
0  {'a': [[1, 2, 3], [4, 5, 6]]}      1
```
