### ISSUE TITLE
[CI] `osx://python/ray/tests:test_gcs_fault_tolerance` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#31871]
- faa9a2c97a5b9237a013972e0c615a0d2f79431b FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1911#0185cc9f-9386-43a0-beed-395efff110c0)
- ceeace1dd7498066026835b181f7f614c33bf40f FAILED [Buildkite :mac: :apple: Medium A-J](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1879#0185c63c-a4b3-402b-aa9a-89e1e10458c2)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_gcs_fault_tolerance-END
....

**Comment by scv119** [comment]
@iycheng can you take an initial look to see if it's a real issue?

**Comment by iycheng** [comment]
It timeout sometimes in Mac. Seems like port conflicting. Linux runs well. But still very interesting why there is a conflict in port so frequently.
```




34944:M 12 Mar 2023 19:52:01.139 # Warning: Could not create server TCP listening socket ::*:49152: bind: Address already in use
  | 34944:M 12 Mar 2023 19:52:01.139 # Failed listening on port 49152 (TCP), aborting.
 

<br class="Apple-interchange-newline">

**Comment by rkooo567** [comment]
I think it can be fixed in the same way as this PR? https://github.com/ray-project/ray/pull/35127

**Comment by iycheng** [comment]
The root cause seems because the port issue.
