### ISSUE TITLE
[core] Explicitly test orphan grandchildren dependency when children exit

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31875]
### What happened + What you expected to happen

It has been found that when a child finishes, the grandchildren tasks if not awaited, will become orphans, and keep running even if the job finishes or grandparent finishes. 

### Versions / Dependencies

master

### Reproduction script

TODO

### Issue Severity

None

**Comment by rkooo567** [comment]
@rickyyx this will be done from your PR right?

**Comment by rickyyx** [comment]
oh right yes.
