### ISSUE TITLE
[CI] `linux://:gcs_server_rpc_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#31870]
- 58386d0d9aac53690ebcafcff78799b99d70d249 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1951#0185e03a-5bda-4289-8250-0d1979c309a0)
- 9ab64212e54b85151deec588a31c9a0974196845 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1947#0185dfda-e8bd-4ca8-bae7-38afc5dbcafe)
- 96854d5c29e65f7f923ae60308eb1dc4419c5ab8 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1946#0185ded9-ba8a-492c-a627-cd1821c3b844)
- ec3243d78726a2840f1323f997a210d1f33e5656 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1945#0185ddd3-40b6-4088-b819-02bc405699ff)
- 228b87ff506554c7fc2ab2f6797d828e2a6e6fe0 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1944#0185ddcd-fd82-4295-abd8-799733b7557e)
- c694dae0e2cda25672c82fd199cc2199d244f789 FAILED [Buildkite :cpp: Tests (UBSAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1942#0185dd89-cd5c-44e0-bb00-21409d55ef67)
- 1c5f513980c2b5b7661bf01b6f4af2fba236681d FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1937#0185d6b3-32b1-4bb3-8ade-e5120e4da21e)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:gcs_server_rpc_test-END
....

**Comment by iycheng** [comment]
@rickyyx I think it might be related  to my PR. I'm going to take this over.
