### ISSUE TITLE
[release][air] Release test failure: `[unstable] air_benchmark_tensorflow_mnist_gpu_4x4 [smoke test]`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#31882]
From https://buildkite.com/ray-project/release-tests-branch/builds/1303

```
RuntimeError: Training on Ray took an average of 102.06 seconds, which is more than 1.20x of the average vanilla training time of 66.35 seconds (1.54x). FAILED
```

**Comment by cadedaniel** [comment]
This is marked unstable -- is this failure a release blocker? cc @jiaodong @matthewdeng

**Comment by cadedaniel** [comment]
cc @krfricke , I think the oncall switched to you

**Comment by krfricke** [comment]
By default unstable tests are no release blockers.

I'll still take a look at this, but will remove the labels
