### ISSUE TITLE
Serialization of Python objects that contain multiple references to the same object are handled incorrectly.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#319]
For example, if a list contains multiple references to the same object, these references will be serialized as separate objects and deserialized as separate objects, giving rise to a different object on the other end. For example,

```python
import ray

ray.init()

l = 10 * [[0]]

print(l)  # [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]

l[0][0] = 1

print(l)  # [[1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

new_l = ray.get(ray.put(l))

print(new_l)  # [[1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

new_l[0][0] = 2

print(new_l)  # [[2], [1], [1], [1], [1], [1], [1], [1], [1], [1]]
```

**Comment by robertnishihara** [comment]
When serializing an object, we could keep track of all the objects that we encounter, and if there is a duplicate, we could raise an exception.

**Comment by mitar** [comment]
Why raise an exception? Why not remember that it is the same object, and then deserialize it in the same way?

**Comment by robertnishihara** [comment]
Agreed, we should handle this properly. I think the proposal to raise an exception was intended as a stopgap to warn people that the current behavior is incorrect.

**Comment by robertnishihara** [comment]
In terms of implementation, the Arrow format supports [dictionary encoding](https://github.com/apache/arrow/blob/master/format/Layout.md#dictionary-encoding), which basically lets you have multiple references to the same object. Presumably this feature could be used for serializing Python objects with multiple copies of the same internal object.

This should cover most important situations. However, if we do this, there will likely still be some shortcomings. In particular, consider the following.

```python
import numpy as np
import ray

ray.init()

x = np.zeros(3)

def f():
    return x
```

There is only one array involved.

```python
f()[0] = 1
assert x[0] == 1
```

However, suppose we wish to serialize the tuple `(x, f)`. Then we our serialization library will serialize `x` intelligently as an array. However, `f` is a function, which our serialization library will treat as a black box, so we'll fallback to cloudpickle for serializing `f`. When we deserialize things on the other side, the arrays `x` and `f()` will be different.

**Comment by mitar** [comment]
Hm, for use, I think we would be OK to have multiple references to the same object from one top-level object. So inside that object I would expect references to hold, not across.

So:

```python
@ray.remote
def f():
  x = np.zeros(3)
  return {'a': x, 'b', x}

result = ray.get(f.remote())
assert result['a'] is result['b']
```

**Comment by robertnishihara** [comment]
Related issue https://issues.apache.org/jira/browse/ARROW-1382

**Comment by robertnishihara** [comment]
This has been fixed.
