### ISSUE TITLE
[Data] `read_datasource` implementation does not match API

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#31906]
### What happened + What you expected to happen

In the `read_datasource`, we add additional logic to check the `paths` arg of the reader to see if they are compatible with Ray Client: https://github.com/ray-project/ray/blob/releases/2.2.0/python/ray/data/read_api.py#L261.

However, this implementation breaks the API: It assumes that this `paths` arg is of type `Union[str, List[str]]`

This assumption is not explicit in the API. This breaks certain cases with custom datasources that do not meet the above assumptions.

Users can currently get around this by not naming any of the `create_reader` args as `paths` to by pass the code in https://github.com/ray-project/ray/blob/releases/2.2.0/python/ray/data/read_api.py#L261.

But, we should move this `paths` checking logic outside of the generic `read_datasource` API and instead move it to a more specific `_read_file_datasource` API.

### Versions / Dependencies

master

### Reproduction script

```python
class CustomDataSource:
    def create_reader(self, paths: List[Tuple[int, str]]):
        ...
```

Having a custom datasource which takes in `paths` of `List[Tuple[int, str]]` will fail.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
Fixed by https://github.com/ray-project/ray/issues/40296
