### ISSUE TITLE
[Core] chaos_many_actors regression

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#31943]
### What happened + What you expected to happen

nightly test chaos_many_actors has been slowly regressed for the last month and eventually it hits the 3600 timeout. we need investigate why.

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
It's been consistently passing since 1/25.

**Comment by cadedaniel** [comment]
Failing again https://buildkite.com/ray-project/release-tests-branch/builds/1390#01863d6f-fb15-4ffc-8b6e-1f02bf14ac29

**Comment by cadedaniel** [comment]
We're hoping with the observability improvements we can solve this

**Comment by cadedaniel** [comment]
Should also make sure the test is testing something we care about

**Comment by rkooo567** [comment]
I believe @jjyao will take a look at this

**Comment by jjyao** [comment]
Duplicate: #34719
