### ISSUE TITLE
[Python 3.11] add docs for python 3.11 wheels

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#31942]
### Description

ensure we build the 3.11 wheel as part of 2.3 release and add link in https://docs.ray.io/en/latest/ray-overview/installation.html

**Comment by rickyyx** [comment]
It's there in the master https://docs.ray.io/en/master/ray-overview/installation.html

**Comment by pcmoritz** [comment]
If we already have some amount of experience with this now, it would be great to say a little more in the note `Python 3.11 support is experimental.` to the degree we are aware, for example `Most things are working, known limitations at the moment include X, Y, and Z.` :)

**Comment by grizzlybearg** [comment]
Are there any plans for windows python 3.11 wheels?

**Comment by ddelange** [comment]
@grizzlybearg see #31362

**Comment by markgoodhead** [comment]
> If we already have some amount of experience with this now, it would be great to say a little more in the note `Python 3.11 support is experimental.` to the degree we are aware, for example something like `Most things are working, known limitations at the moment include X, Y, and Z.` :)

We're considering migrating to 3.11 but Ray is a core dependency for us and the experimental warning is quite off-putting to say the least! It's been marked experimental since January - what are the outstanding issues that mean the wheel is kept in an experimental state?

**Comment by ddelange** [comment]
afaik the [last python 3.11 specific bugs](https://github.com/kserve/kserve/pull/3075#issuecomment-1677630840) were fixed starting with the Ray 2.7 release

**Comment by markgoodhead** [comment]
> afaik the [last python 3.11 specific bugs](https://github.com/kserve/kserve/pull/3075#issuecomment-1677630840) were fixed starting with the Ray 2.7 release

Ah thanks, so probably all that's needed here is to not mark the build as experimental any more?

**Comment by MiguelTerraNeves** [comment]
We have the same issue as markgoodhead. Are there any plans for when python 3.11 will no longer be tagged as experimental?

**Comment by jjyao** [comment]
We plan to do it in the Ray release 2.11.

**Comment by markgoodhead** [comment]
> We plan to do it in the Ray release 2.11.

Ray 2.11 looks to have just been released although I couldn't see this in the release notes? Did it not make the cut?

**Comment by jjyao** [comment]
3.11 is officially supported now.
