### ISSUE TITLE
Task dispatch makes a copy of the task queue

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3195]
### Describe the problem
Task dispatch iterates over the `READY` task queue to figure out which tasks can be dispatched to a worker. Currently, the code creates a copy of the queue due to the fact that the reference to the queue is instantiated with `auto` ([link](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L483)), rather than `auto &` or `const auto &`. It seems to be that way because that reference is later used to remove tasks from the queue ([link](url)).

We should change that code to instantiate the reference to the queue with `const auto &`, and make sure to remove all of the dispatched tasks from the `READY` queue outside of that loop.

### Source code / logs
This is part of the issue behind #3188.

**Comment by istoica** [comment]
This is fixed as part of https://github.com/ray-project/ray/pull/3234
