### ISSUE TITLE
[Dependency] Upgrade gRPC to 1.46.6

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#31956]
Upgrade to a version of gRPC that https://github.com/advisories/GHSA-cfmr-vrgj-vqwv in Zlib
* 1.46.6 has this patch: https://github.com/grpc/grpc/pull/31845

**Comment by ijrsvt** [comment]
If we cannot upgrade gRPC, we can try to apply that PR as a patch to our bundled version of gRPC

**Comment by cadedaniel** [comment]
Why is this necessary, given that our upper bound on grpc is > 1.46?

https://github.com/ray-project/ray/blob/6b081e9e000f181cb05036c91e3369e58c2baba3/python/requirements.txt#L25-L26

**Comment by ijrsvt** [comment]
The issue is that it is pinned in our Bazel dependencies:
https://github.com/ray-project/ray/blob/6b081e9e000f181cb05036c91e3369e58c2baba3/bazel/ray_deps_setup.bzl#L241

**Comment by cadedaniel** [comment]
cc @scv119 do you have time to pick this up?
