### ISSUE TITLE
[Core/Data] Ray::IDLE processes are not being cleaned up after the entrypoint exists

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#31967]
### What happened + What you expected to happen

Ray::IDLE processes stick around after the entrypoint is done and are not cleaned up. Furthermore, OOM killer doesn't prioritize killing them, meaning that if an actual workflow is scheduled on a node occupied by Ray::IDLE processes, it gets killed.

### Versions / Dependencies

master

### Reproduction script

Clone https://console.anyscale-staging.com/o/anyscale-internal/workspaces/expwrk_h985k2zsf6f6eb4f2lfduhvju6/ses_uspg7cc6dqvr1p39xqb4skiqay, replace the `sd_preprocessing.py` file with https://github.com/Yard1/Ray-StableDiffusion/blob/1433df10c07aa6f9bef1d90a42408c73ca5ba2c9/sd_preprocessing.py and run `bash run.sh` several times. One of the nodes will start filling up with Ray::IDLE after each run (seems to be always the same one).

This has been mitigated by importing `datasets`, `transformers` and `torchvision` inside the functions that will be mapped on a Ray Dataset instead of importing them at the top of the `sd_preprocessing.py` file.

### Issue Severity

High: It blocks me from completing my task.

**Comment by Yard1** [comment]
Looks to be a Datasets issue @rkooo567 @jianoaix :

```
--- Object references for node address: 172.31.247.238 ---
IP Address       PID    Type    Call Site               Status          Size    Reference Type      Object Ref                                              
172.31.247.238   533    Worker  (deserialize task arg)  -               5544.0 B  PINNED_IN_MEMORY    00b7e7961caf49354617a6eb88fa7d8fd321fe8c0100000002000000
                                 ray.data._internal.ex                                                                                                      
                                ecution.operators.map_                                                                                                      
                                task_submitter._map_ta                                                                                                      
                                sk                                                                                                                          

172.31.247.238   533    Worker  (deserialize task arg)  -               119906161.0 B  PINNED_IN_MEMORY    e5a95610215b2d7017e0e68710bc36500ce339080100000002000000
                                 ray.data._internal.ex                                                                                                      
                                ecution.operators.map_                                                                                                      
                                task_submitter._map_ta                                                                                                      
                                sk     
```

**Comment by Yard1** [comment]
May be related to https://github.com/ray-project/ray/issues/25699

**Comment by rkooo567** [comment]
Yeah looks like a similar issue

**Comment by ericl** [comment]
@clarng is this also a bug in the OOM killer? We should be killing idle processes first, presumably.

**Comment by ericl** [comment]
> Idle processes typically occupy very little space (hundreds of mb per
process) and if there is memory pressure chances are there won’t be idle
processes as the system is busy

This may be true on the normal case, but we should be more concerned about worst case conditions for the OOM killer, right? Clearly in this scenario, idle processes are consuming excess memory.

You can also imagine a user writing code that leaks huge amounts of memory in idle processes.

> We could use the oom killer to double as a tool to clean up memory leaking
processes, assuming the process is still tracked, but that may end up
hiding a real bug (like this one)

Idle workers are tracked in the worker pool too right?

**Comment by Yard1** [comment]
To add some context, it looks like the idle processes are holding pinned memory objects coming from `ray.data._internal.execution.operators.map_task_submitter._map_task `

**Comment by ericl** [comment]
I think that's a separate bug--- workers holding borrowed objects should still be eligible for eviction from the pool. Workers are only prevented from being killed if they own objects, which is not the case here (in Datasets, all objects are owned by the driver). cc @stephanie-wang

**Comment by clarng** [comment]
> > Idle processes typically occupy very little space (hundreds of mb per
> > process) and if there is memory pressure chances are there won’t be idle
> > processes as the system is busy
> 
> This may be true on the normal case, but we should be more concerned about worst case conditions for the OOM killer, right? Clearly in this scenario, idle processes are consuming excess memory.

Seems like the worker pool can detect bad idle workers and kill or restart them to fix the issue, based on the settings of the pool? Could we end up in a situation where the worker pool and OOM killer would step on each other, where one spawns workers and the other kills it?

> 
> You can also imagine a user writing code that leaks huge amounts of memory in idle processes.
> 
> > We could use the oom killer to double as a tool to clean up memory leaking
> > processes, assuming the process is still tracked, but that may end up
> > hiding a real bug (like this one)
> 
> Idle workers are tracked in the worker pool too right?

**Comment by ericl** [comment]
Actually, it seems the OOM killer is already killing idle workers today...?

Here's a script that demonstrates:

```
import ray
import time
import numpy as np
import threading
import tensorflow

def leak_mem_in_background():
    class Thread(threading.Thread):
        def run(self):
            x = []
            while True:
                print("Leaking memory in thread", len(x))
                x.append(np.ones(100_000_000))
    t = Thread()
    t.start()
    return t


@ray.remote
def evil_task():
    leak_mem_in_background()


ray.get(evil_task.remote())
time.sleep(999)  # We will eventually OOM due to the background leak in an idle worker.
```

This will eventually give you:

```
(raylet) [2023-01-27 13:06:31,905 E 2638410 2638410] (raylet) node_manager.cc:3035: 1 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: b2ea8b17398604f391ca1af3a06daf3067520a22314f7d0c5df247c4, IP: 192.168.5.130) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 192.168.5.130`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

```

**Comment by Yard1** [comment]
In my case, it sometimes picked the idle worker, sometimes the actual training worker. The latter seemed to be picked more often as they consumed more memory at the peak.

**Comment by ericl** [comment]
Ok--- so if we are already killing idle workers, and it's just a question of optimization, then I think we can close this issue as a duplicate of https://github.com/ray-project/ray/issues/25699

**Comment by Yard1** [comment]
Closed as duplicate of https://github.com/ray-project/ray/issues/25699

**Comment by clarng** [comment]
Also confirmed it will kill idle processes, in addition to the ones that are executing, since we expose all the workers to the oom killer:

in worker_pool.h

```
  struct State {
....

    /// All workers that have registered and are still connected, including both
    /// idle and executing.
    std::unordered_set<std::shared_ptr<WorkerInterface>> registered_workers;
```

in worker_pool.cc
```

WorkerPool::~WorkerPool() {
  std::unordered_set<Process> procs_to_kill;
  for (const auto &entry : states_by_lang_) {
    // Kill all the worker processes.
    for (auto &worker_process : entry.second.worker_processes) {
      procs_to_kill.insert(worker_process.second.proc);
    }
  }
  for (Process proc : procs_to_kill) {
    proc.Kill();
    // NOTE: Avoid calling Wait() here. It fails with ECHILD, as SIGCHLD is disabled.
  }
}
```
