### ISSUE TITLE
[docker][rfc] Roadmap for Docker images from Ray 2.3 onwards

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#31966]
We are currently adding support for arm64 Docker images here: https://github.com/ray-project/ray/pull/31861

This issue tracks the planned roadmap and open discussion points for the Ray Docker images and can be used for discussions.

### Ray 2.3

Ray 2.3 will be the first release for which we release arm64-compatible Docker images.

These images will be built for 
- CPU
- CUDA 11.2
- CUDA 11.3
- CUDA 11.6

The image tags will have a `-aarch64` suffix and thus need to be specified explicitly.

We will not publish 2.3.0 as `:latest-aarch64` - instead `:2.3.0-aarch64` has to be used explicitly. The reason for this is that we may remove suffixes completely in the next release, and then we would have a stale `:latest-aarch64` image pointing to an older release.

We will not build `ray-ml` images for aarch64. This is mostly due to lack of compatibility of some dependencies with arm64.

### Ray 2.4

For Ray 2.4, we aim to provide multiplatform images. This means that the suffixes will not be needed anymore: Docker will automatically choose the correct image given the regular tag.

This also means that we will likely stop publishing `-aarch64` tags to docker hub (hence why we don't publish `:latest-aarch64` in 2.3.0)

**Comment by pingsutw** [comment]
@krfricke any update on this? I didn't see multiplatform images on dockerhub.
