### ISSUE TITLE
[RLlib] algorithms/algorithm_config.py 

### ISSUE THREAD

**Issue by ninell-oldenburg** [ray-project/ray#31964]
### What happened + What you expected to happen

Hi,

I'm trying to run [this file](https://github.com/deepmind/meltingpot/blob/main/examples/rllib/self_play_train.py) from the [Deepmind Melting Pot project](https://github.com/deepmind/meltingpot) and keep getting the following error

```
 Traceback (most recent call last):
  File "/Users/nell/Documents/GitHub/norm-games/examples/rllib/self_play_train.py", line 158, in <module>
    main()
  File "/Users/nell/Documents/GitHub/norm-games/examples/rllib/self_play_train.py", line 138, in main
    config = get_config()
  File "/Users/nell/Documents/GitHub/norm-games/examples/rllib/self_play_train.py", line 60, in get_config
    config.num_workers = num_rollout_workers
  File "/Users/nell/miniforge3/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 2314, in __setattr__
    super().__setattr__(key, value)
AttributeError: can't set attribute 'num_workers'
```

I realized that the lines indicated here don't add up with the file under [rllib/algorithms/algorithm_config.py](https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm_config.py). Substituting the code with the git version did not work and installing from git also failed because of other dependency issues. Of course, I'm not entirely sure but I think it's likely that this is not caused by DM as they didn't alter their version since Nov IIUC.

Are you familiar with this kind of error?

Thanks in advance!

### Versions / Dependencies

Mac OS M1 chip
Python 3.10.8
pip 22.3.1 from /Users/nell/miniforge3/lib/python3.10/site-packages/pip (python 3.10)
ray, version 2.2.0

### Reproduction script

See https://github.com/deepmind/meltingpot/blob/main/examples/rllib/self_play_train.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by maxpumperla** [comment]
hey @ninell-oldenburg, can you try setting `num_rollout_workers` instead, as e.g. indicated here?

https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm_config.py#L125-L128

thank you

**Comment by ninell-oldenburg** [comment]
Works, thank you!
