### ISSUE TITLE
[CI] `linux://python/ray/data:tests/test_object_gc` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#31970]
- 1455a10feda52b80d28ced9411c4ab94e73ea9c3 FAILED [Buildkite Dataset tests (Arrow 7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1996#0185eb9b-a000-4f9e-b992-33d039f860c0)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:tests/test_object_gc-END
....

**Comment by cadedaniel** [comment]
this doesn't seem like a release blocker. confirm cc @scv119 ?

**Comment by jianoaix** [comment]
Duplicate with https://github.com/ray-project/ray/issues/32168
