### ISSUE TITLE
[Dashboard] dashboard showing stale pending nodes while the cluster is fully autoscaled.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#31982]
### What happened + What you expected to happen

start the [cluster](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_u9jnexvbz53n9vzfjgdpwu9d71?command-history-section=head_start_up_log) with 64 nodes. you will notice even it autoscaling finished, the number of pending nodes doesn't decrease to 0.

![image](https://user-images.githubusercontent.com/837180/214982725-1022e776-d843-4332-b72c-7147665b5394.png)

### Versions / Dependencies

master

### Reproduction script

run release test `many_tasks`. 
or run `python test_many_tasks.py --num-tasks=10000` on https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_u9jnexvbz53n9vzfjgdpwu9d71?command-history-section=head_start_up_log

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @wuisawesome this must be the report issue from the autoscaler. Do you know who's the best person to take this from the autoscaler?
