### ISSUE TITLE
[Data] Refactor methods calling into `map_batches`

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#32017]
There are a few dataset methods that directly call into `map_batches`: `random_sample`, `add_column`, `drop_columns`, `select_columns`.

With the new operator refactor, this means that the logical plan for these operations will show up as `MapBatches`. Instead, separate out the inner transform function in `map_batches`, and implement logical operators for these methods independently.

**Comment by amogkam** [comment]
cc @c21

**Comment by anyscalesam** [comment]
Closing for now - no plans and very low priority.
