### ISSUE TITLE
[Ray release infra] Flaky tests caused by autoscaling group killing instances while tests are running

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32013]
We autoscale the number of instances in our release BK queue:
![image](https://user-images.githubusercontent.com/950914/215224732-ceea4982-2dc4-407e-bcfa-ca7557654936.png)

They are not spot instances:
https://github.com/ray-project/buildkite-ci-stack/blob/c6041eb2a7245e683fd4b8f4c74090cdde56ebe5/ci-release-test-module/queues.tf#L43-L48

But we see cancellations (I notice it on a long running test) https://buildkite.com/ray-project/release-tests-branch/builds/1305#0185eb0c-78ed-4c0c-af6a-384ddf0fa193

```
[INFO 2023-01-26 12:42:55,298] sdk_runner.py: 135  ... command still running ...(78000 seconds) ...
[INFO 2023-01-26 12:43:25,272] sdk_runner.py: 135  ... command still running ...(78030 seconds) ...
[INFO 2023-01-26 12:43:55,668] sdk_runner.py: 135  ... command still running ...(78060 seconds) ...
[INFO 2023-01-26 12:44:25,548] sdk_runner.py: 135  ... command still running ...(78090 seconds) ...
[90m# Received cancellation signal, interrupting[0m
[31mðŸš¨ Error: The command exited with status -1[0m
```

This adds to flaky noise when running release tests. To reduce flakiness we should only kill instances that aren't running tests. Might be doable via BK metrics or a custom termination policy (lambda).

cc @krfricke

**Comment by hora-anyscale** [comment]
@krfricke - please share what you think the priority should be?

**Comment by cadedaniel** [comment]
Seeing this again in the 2.3 release https://buildkite.com/ray-project/oss-ci-build-branch/builds/2305#01863de4-0fdc-4044-8bfe-8c2a96860810

**Comment by cadedaniel** [comment]
I imagine there are some cost savings here as this causes tests to be reran

**Comment by aslonnie** [comment]
the build job was cancelled because the buildkite agent was lost (and probably not because the instance was killed due to autoscaling).

**Comment by can-anyscale** [comment]
sdk-runner is deprecated
