### ISSUE TITLE
[Dashboard] New timeline endpoint returns 900MB json file when there are only 3K tasks.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#32031]
### What happened + What you expected to happen

Based on the local run, 10K tasks should only produce about a 30MB file. If the file size becomes bigger than 100MB, it is almost unusable, so we should avoid it.

However, when I download the timeline file from many_tasks, it returns almost 1GB file, and it took 30 seconds dashboard time (which is very bad). I assume there's some inefficient logic when there are multi nodes involved.

Also, I found the latency of time is incorrect (maybe we did the wrong division). 

### Versions / Dependencies

master

### Reproduction script

run many_tasks and download a timeline json after the task is done

### Issue Severity

None

**Comment by rkooo567** [comment]
This is a release blocker. I should've marked long ago ,but I forgot. This is impacting the correctness of the feature, so we should fix it

**Comment by cadedaniel** [comment]
@rkooo567 cherry pick?
