### ISSUE TITLE
[Dependency] Specify numpy <= 1.23.5 or replace all np.bool with bool

### ISSUE THREAD

**Issue by elliottower** [ray-project/ray#32038]
### What happened + What you expected to happen

The [requirements](https://github.com/ray-project/ray/blob/master/python/requirements.txt#L30) specify numpy >= 1.19.3. In the [numpy version 1.24.0 release notes](https://github.com/numpy/numpy/releases/tag/v1.24.0), it shows the alias np.bool has been deprecated and throws an error. This is easily fixable by uninstalling numpy and reinstalling an earlier version of numpy, although it is probably more ideal to replace occurrences of np.bool with bool, to avoid conflicts with other packages.

As a side note some of the rllib example files have additional dependencies which are not listed anywhere I could find, such as multi_agent_cartpole.py which required tensorflow-probability and pygame to be installed as well. I figure this may be intentional as certain packages are only required for some games/examples, but it would be nice if you could just install ray[rllib] and run all the examples without worrying about dependencies.

### Versions / Dependencies

ray==2.2.0

### Reproduction script

git clone https://github.com/ray-project/ray.git
pip install ray
cd ray
pip install pygame tensorflow-probability
python ray/rllib/examples/multi_agent_cartpole.py

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment]
Regarding RLLib: We don't specify these requirements (just like we don't require TF or torch) because they are no hard-requirements. I agree that we should simply have a full and minimal install at some point, though.

**Comment by ArturNiederfahrenhorst** [comment]
The related PR I posted includes our mitigation of this issue.
I'll close this as we might at some point upgrade to numpy>=1.24 but today this issue is fixed on master and will not be cherry-picked.

**Comment by ArturNiederfahrenhorst** [comment]
@elliottower Feel free to repoen this you don't agree.

**Comment by YQ-Wang** [comment]
@ArturNiederfahrenhorst Do you know if numpy 1.24.2 is supported as if now?

**Comment by ArturNiederfahrenhorst** [comment]
@YQ-Wang  Not officially!

Today, we support the following versions depending on the Python version in our docker images:

Python version -> ("3.7", "3.8", "3.9", "3.10")
Numpy version -> ("1.14.5", "1.14.5", "1.19.3", "1.22.0")

Other versions are untested but might work.

**Comment by ArturNiederfahrenhorst** [comment]
Also, let's keep this discussion to https://github.com/ray-project/ray/issues/31246
