### ISSUE TITLE
[RLlib] 'PPOConfig' has no attribute 'overrides'

### ISSUE THREAD

**Issue by elliottower** [ray-project/ray#32039]
### What happened + What you expected to happen

Running training scripts involving PPO I run into errors because the overrides attribute no longer exists. In [multi_agent_cartpole.py](https://github.com/ray-project/ray/blob/master/rllib/examples/env_rendering_and_recording.py) I was able to fix the error by replacing `PPOConfig.overrides(model={...})` with `PPOConfig().training(model={...})`.
Also encountered #32038 when running this example but this seems to be a bigger issue (searching for PPOConfig.override shows ~10 different files with this same issue)

An example that I could not get working with this type of modification was [env_rendering_and_recording.py](https://github.com/ray-project/ray/blob/master/rllib/examples/env_rendering_and_recording.py), although judging by [#30949](https://github.com/ray-project/ray/issues/30949) rendering is currently not supported? In this case the error occurs in validation rather than training, and due to the flag render_env, which is not recognized in either training() or validate(). I was able to get that part of the code working by manually defining a new PPOConfig() and overriding render_env=True, but then ran into other issues. If anyone knows a workaround to get rendering working with the current version I would definitely be interested, as I was hoping to follow this example.

### Versions / Dependencies

ray==2.2.0
python==3.9

### Reproduction script

git clone https://github.com/ray-project/ray.git
pip install ray
cd ray
pip install pygame tensorflow-probability
python ray/rllib/examples/multi_agent_cartpole.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @elliottower Could it be that you have a version mismatch? It looks like you are cloning the master branch of the repository and execute it on Ray 2.2.0.
When executing on Ray 2.2.0, please only use examples from Ray 2.2.0.
Does the error persist if the versions match? I can not reproduce this on master.

**Comment by elliottower** [comment]
Hi Arthur, thanks for the help, it turned out you were right. Didn't realize that cloning the current master would mean that some examples would be broken, but trying the same thing in 2.2.0 worked successfully.
