### ISSUE TITLE
[Core] Export metrics to agent failed

### ISSUE THREAD

**Issue by hxq2146041** [ray-project/ray#32044]
### What happened + What you expected to happen

Install the ray distributed system on four servers.   The ray version is 1.8.0

code:
class Counter {
public:
	int count;
	Counter(int init){conut = init;}
	static Counter *FactoryCreate(int init) {return new Counter(init);}
	
	int Add(int x) {
		count += x;
		return count;	
	}
};

RAY_REMOTE(Counter::FactoryCreate, &Counter::Add);

int main(int argc, char **argv) {
	ray::ActorHandle<Counter> actor = ray::Actor(Counter::FactoryCreate).Remote(0);
	auto actor_object = actor.Task(&Counter::Add).Remote(3);
	int actor_task_result = *(ray::Get(actor_object));
	std::cout << "actor_task_result = "<< actor_task_result << std::endl;
}

After program execution:

$ray status
Demands:
{}: 1+ pending tasks/actors

Terminal output error：
metric_exporter.cc:206:Export metrics to agent failed: IOError:14: failed to connect to all addresses. This won`t affect Ray, but you can lose metrics from the cluster.

### Versions / Dependencies

ray version: 1.8.0
Python version: 3.9.9  
OS: openEuler

None

**Comment by ArturNiederfahrenhorst** [comment]
@hxq2146041 Could you provide the reproduction script in a more readable format and describe what you expected to happen, please?
