### ISSUE TITLE
[Autoscaler][GCP] TPU should be allowed as Head Node

### ISSUE THREAD

**Issue by bluecoconut** [ray-project/ray#32052]
### What happened + What you expected to happen

Autoscaler doesn't allow TPU nodes to act as head nodes

This code is in the `gcp/config.py`
```python
if _is_head_node_a_tpu(config):
  raise RuntimeError("TPUs are not supported as head nodes.")
```

https://github.com/ray-project/ray/blob/45ffe6eb99d96488fdec187bb47a4a78d9b5ee92/python/ray/autoscaler/_private/gcp/config.py#L290

Last I found was here: https://github.com/ray-project/ray/pull/17278/files#r677939519

When the original PR came in from @ijrsvt in July 2021 this didnt work, but now ~18 months later, as far as my tests show this should work just fine now. 

### Versions / Dependencies

Ray version: This is on master (v2.2 and v3) show this
TPU VM v2-8 on GCP

### Reproduction script

By manually making a service account on a TPU VM node with the same permissions, I was able to directly call and create a TPU worker node

```
$ cloud auth activate-service-account  ...

$ gcloud alpha compute tpus tpu-vm create ray-worker-12312df --version='v2-alpha' --zone=us-central1-f --accelerator-type="v2-8" --preemptible
Create request issued for: [ray-worker-12312df]
Waiting for operation [projects/approx-labs-research/locations/us-ce
ntral1-f/operations/operation-1675097649815-5f37e10619ee9-7df9192e-b
4985a36] to complete...done.                                        
Created tpu [ray-worker-12312df].
```

### Issue Severity

None

**Comment by ijrsvt** [comment]
cc @Yard1 do you have any additional context on why this wasn't allowed as a head node?

**Comment by Yard1** [comment]
That role didn't have the permissions back then. It is possible something was changed on Google's side, which would make this constraint unnecessary.

**Comment by bluecoconut** [comment]
I've thrown together a PR to fix this for now, and it seems to work just fine. (I'm running a cluster now, screenshots included in PR)

https://github.com/ray-project/ray/pull/32083

Extra oddity to get this to work is that the API is slightly different.

https://tpu.googleapis.com/$discovery/rest?version=v2alpha1
vs. 
https://www.googleapis.com/discovery/v1/apis/compute/v1/rest

The compute API uses `serviceAccounts` key, where the `ServiceAccount` object has a `scopes` key. (So this is the standard)
The TPU API uses `serviceAccount` key that takes a single `ServiceAccount` object, this `ServiceAccount` object has a `scope` key (that takes a list)
