### ISSUE TITLE
[Observability] Remove pin from opentelemetry packages

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#32051]
### What happened + What you expected to happen

Right now, the opentelemetry packages are pinned here:

https://github.com/ray-project/ray/blob/master/python/setup.py#L251

We should remove the pins and upgrade the packages in our CI

### Versions / Dependencies

Ray 2.2 and master

### Reproduction script

None

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
Status: Have a PR out ^
