### ISSUE TITLE
Why `time_this_iter_s` is a relatively very large number occasionally?

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3205]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3, and Tune and RLlib are replaced with the master version
- **Python version**: 3.6.5

### Describe the problem
When running a lot of trials in distributed mode, sometimes an iteration of a trial will execute for a very long time.

## Source code / logs
Here are some snippets:

"normal"
<pre>
Result for MAML_PointEnv_11_clip_param=0.3,inner_grad_clip=20.0,inner_lr=0.01,random_seed=2,vf_clip_param=5.0,vf_loss_coeff=0.01:
  date: 2018-11-03_01-16-44
  done: false
  experiment_id: a62bc95e5fce481bb2105b1756088142
  hostname: gpu-server-00
  info:
    entropy: 0.0
    kl: 0.0029529947554692627
    policy_Loss: 5.90388652086258
    total_loss: 6.3423635244369505
    vf_loss: 43.84770240783691
  iterations_since_restore: 14
  node_ip: 219.245.186.43
  pid: 143540
  time_since_restore: 92.81241869926453
  time_this_iter_s: 6.387654781341553
  time_total_s: 92.81241869926453
  timestamp: 1541179004
  timesteps_since_restore: 0
  training_iteration: 14
</pre>
"abnormal"
<pre>
Result for MAML_PointEnv_11_clip_param=0.3,inner_grad_clip=20.0,inner_lr=0.01,random_seed=2,vf_clip_param=5.0,vf_loss_coeff=0.01:
  date: 2018-11-03_01-33-53
  done: false
  experiment_id: a62bc95e5fce481bb2105b1756088142
  hostname: gpu-server-00
  info:
    entropy: 0.0
    kl: 0.006290532485581935
    policy_Loss: 2.644531507790089
    total_loss: 2.8712308585643767
    vf_loss: 22.669935321807863
  iterations_since_restore: 21
  node_ip: 219.245.186.43
  pid: 143540
  time_since_restore: 1122.104553937912
  time_this_iter_s: 951.0606498718262
  time_total_s: 1122.104553937912
  timestamp: 1541180033
  timesteps_since_restore: 0
  training_iteration: 21
</pre>
"normal"
<pre>
Result for MAML_PointEnv_11_clip_param=0.3,inner_grad_clip=20.0,inner_lr=0.01,random_seed=2,vf_clip_param=5.0,vf_loss_coeff=0.01:
  date: 2018-11-03_01-34-03
  done: false
  experiment_id: a62bc95e5fce481bb2105b1756088142
  hostname: gpu-server-00
  info:
    entropy: 0.0
    kl: 0.007101758290082217
    policy_Loss: 1.7242260288447142
    total_loss: 1.928725902736187
    vf_loss: 20.449988508224486
  iterations_since_restore: 23
  node_ip: 219.245.186.43
  pid: 143540
  time_since_restore: 1131.3009116649628
  time_this_iter_s: 4.561047792434692
  time_total_s: 1131.3009116649628
  timestamp: 1541180043
  timesteps_since_restore: 0
  training_iteration: 23
</pre>
"abnormal"
<pre>
Result for MAML_PointEnv_11_clip_param=0.3,inner_grad_clip=20.0,inner_lr=0.01,random_seed=2,vf_clip_param=5.0,vf_loss_coeff=0.01:
  date: 2018-11-03_01-50-30
  done: false
  experiment_id: a62bc95e5fce481bb2105b1756088142
  hostname: gpu-server-00
  info:
    entropy: 0.0
    kl: 0.009359711571596563
    policy_Loss: 0.3389931205660105
    total_loss: 0.593448705971241
    vf_loss: 25.445559597015382
  iterations_since_restore: 63
  node_ip: 219.245.186.43
  pid: 143540
  time_since_restore: 2117.925436735153
  time_this_iter_s: 717.1581523418427
  time_total_s: 2117.925436735153
  timestamp: 1541181030
  timesteps_since_restore: 0
  training_iteration: 63
</pre>
The status of this trial is always running.

**Comment by ericl** [comment]
This sounds like something is hanging. A typical culprit is that sometimes some environment has hung and if you're waiting for all of them to complete then that blocks the iteration (as in https://github.com/ray-project/ray/pull/3096)

It could also be something else stuck of course.

**Comment by llan-ml** [comment]
I think that the main issue lies in `ray.get` in multi-node mode. I also tried to use `py-spy` to inspect some hanging workers. Most of them are stuck in getting reset args, but some are stuck in getting weights of `MAMLOptimizer.step` as follows:
<pre>
Stack dump for lanlin   54800  0.8  0.1 11804708 334120 ?     Sl   17:25   0:14 /home/lanlin/.pyenv/versions/anaconda3-5.2.0/bin/python /home/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/workers/default_worker.py --node-ip-address=219.245.186.38 --object-store-name=/tmp/plasma_store32677489 --object-store-manager-name=/tmp/plasma_manager26233163 --local-scheduler-name=/tmp/scheduler67438114 --redis-address=219.245.186.38:32222
Thread 0x7FEAC53E5700 (active)
         _run (ray/import_thread.py:61)
         run (threading.py:864)
         _bootstrap_inner (threading.py:916)
         _bootstrap (threading.py:884)
Thread 0x7FEAE554D700 (active)
         _wrapper (ray/utils.py:387)
         retrieve_and_deserialize (ray/worker.py:434)
         get_object (ray/worker.py:551)
         get (ray/worker.py:2517)
         reset (/home/lanlin/Workspaces/morrl/reset_wrapper.py:36)
         reset (gym/core.py:308)
         <listcomp> (ray/rllib/env/vector_env.py:76)
         vector_reset (ray/rllib/env/vector_env.py:76)
         reset_sample (/home/lanlin/Workspaces/morrl/maml_policy_evaluator.py:84)
         sample (/home/lanlin/Workspaces/morrl/maml_policy_evaluator.py:100)
         _inner_update_once (/home/lanlin/Workspaces/morrl/maml_policy_evaluator.py:104)
         inner_update (/home/lanlin/Workspaces/morrl/maml_policy_evaluator.py:121)
         actor_method_executor (ray/actor.py:261)
         _process_task (ray/worker.py:945)
         _wait_for_and_process_task (ray/worker.py:1060)
         main_loop (ray/worker.py:1103)
         <module> (ray/workers/default_worker.py:88)
</pre>
<pre>
Stack dump for lanlin   34021  0.6  0.1 20028908 476476 ?     Sl   16:20   0:35 /home/lanlin/.pyenv/versions/anaconda3-5.2.0/bin/python /home/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/workers/default_worker.py --node-ip-address=219.245.186.38 --object-store-name=/tmp/plasma_store32677489 --object-store-manager-name=/tmp/plasma_manager26233163 --local-scheduler-name=/tmp/scheduler67438114 --redis-address=219.245.186.38:32222
Thread 0x7EFBF25C7700 (active)
         _run (ray/import_thread.py:61)
         run (threading.py:864)
         _bootstrap_inner (threading.py:916)
         _bootstrap (threading.py:884)
Thread 0x7EFC1272F700 (active)
         _wrapper (ray/utils.py:387)
         retrieve_and_deserialize (ray/worker.py:434)
         get_object (ray/worker.py:551)
         get (ray/worker.py:2511)
         step (/home/lanlin/Workspaces/morrl/maml_optimizer.py:39)
         _train (/home/lanlin/Workspaces/morrl/maml.py:150)
         train (ray/tune/trainable.py:146)
         train (/home/lanlin/Workspaces/morrl/maml.py:159)
         actor_method_executor (ray/actor.py:261)
         _process_task (ray/worker.py:945)
         _wait_for_and_process_task (ray/worker.py:1060)
         main_loop (ray/worker.py:1103)
         <module> (ray/workers/default_worker.py:88)
</pre>
Since the `env.reset` is call more often than `optimizer.step`, it's more possible to be stuck in `reset`.

**Comment by llan-ml** [comment]
@ericl I find that setting `intra_op_parallelism_threads=inter_op_parallelism_threads=1` for the local evaluator can avoid this issue. 

In the distributed mode, several local evaluators will be scheduled into the same node. Setting those two values to `None` may lead to some resource/thread problems. At least, I observe the following two problems:
- Some trials execute very slowly.
- As the experiments go on, the occupied memory will increase to a very large number. In my case, the occupied memory is ~100GB per node (the total memory is 256GB).

On the other hand, I guess the issue with memory will further lead to some problems with `ray.get` and block the process.

**Comment by llan-ml** [comment]
After running several hours and running out of all pre-defined memory for plasma store, it throws `pyarrow.lib.ArrowIOError: Broken pipe`. Some previous issues have reported this problem, but the workarounds:
- https://github.com/ray-project/ray/issues/733#issuecomment-378776603 possibly cannot be directly used with Ray Tune.
- https://github.com/ray-project/ray/issues/1565#issuecomment-417972075 raises a new issue #3170 .

**Comment by ericl** [comment]
@llan-ml are you still running into this issue on master (besides the redis memory growth) or does #3243 solve it?

**Comment by llan-ml** [comment]
@ericl Do you mean `ArrowIOError`? I think this error raises when the allocated memory is used up.

For `ray==0.5.3`, #3243 actually spares more memory for redis servers, and the `ArrowIOError` is delayed, since the redis servers finally run out of the memory.

For master (9dd3eedbac31d93cc32e9e87d03e8d8da1507fa6), I have not run a tune experiment long enough. But I suppose `ArrorIOError` will still raise if redis servers run out of memory.

**Comment by ericl** [comment]
I see, should we close this issue then? I think the redis issue will be fixed in 0.6 (@robertnishihara ?)

**Comment by ericl** [comment]
Should we force intra_op_parallelism_threads to something lower perhaps, like 8?

**Comment by llan-ml** [comment]
On master, I didn't observe that the trial hangs up for a long time at some iteration. I also tested `8` and `None`, and they have almost the same performance in my case. But to avoid resource competition, I prefer a lower value. I think it's ok to close this issue.

**Comment by ericl** [comment]
Ok great. I made a pr to set the default to 8 on the driver.
