### ISSUE TITLE
[CI] `linux://python/ray/data:tests/test_dataset` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#32067]
- 907e9689ab600cc9393a5761090b2e3340831f3e FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2065#018603fe-13c0-46b1-9ac4-ca3bf8c18e5a)
- d390df83668c8e1670fb14087a8771d89a594a06 FAILED [Buildkite Dataset tests (Arrow 10)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2061#0186036d-cb12-4fb7-a4a7-b04ea63c8ab3)
- cc6d30a267c928db50fd9db48fc25ada779dff2f FAILED [Buildkite Dataset tests (Arrow 7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2049#0185f7de-abf5-41a8-9d54-a85a172d7b76)
- b58bb93dc7b28097cfdb4d6a40dee2ce7417583e FAILED [Buildkite Dataset tests (Arrow 10)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2045#0185f627-f0ac-4a22-a3b1-341d24395d2e)
- 00416d2c40ae9c1b91aa643e2a7bb65397063681 FAILED [Buildkite Dataset tests (Arrow 7)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2038#0185f5e1-dacc-4e4e-986e-9e6e6a198571)
- e753b03c23aa630d59c7f032cd6f17877788f950 FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2011#0185f079-5f04-46b5-a539-0ce6ea41edac)
- 39a901eb40aa1d55639ddd90bcd4094182e999a9 FAILED [Buildkite Dataset tests (Arrow 9)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2009#0185f03b-7e62-4b1c-8fc5-624a9df7c206)
- b7d6f2f04d1f3a02ddbacefd8a3639ed39bd783f FAILED [Buildkite Dataset tests (Arrow 9)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/1988#0185ea92-e711-49b0-8ae6-b4c8549ff191)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:tests/test_dataset-END
....

**Comment by rickyyx** [comment]
cc data oncall

**Comment by jianoaix** [comment]
This should have been fixed at: https://github.com/ray-project/ray/pull/31930. Is it not the case?

**Comment by rickyyx** [comment]
Looks like the test is kind of flaky?

**Comment by rickyyx** [comment]
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/11676094/215593670-800e5249-016d-4ed4-877c-cb0ddc78451a.png">

**Comment by jianoaix** [comment]
Yeah, it however doesn't seem to have any failed tests, so unclear what's failing, e.g. https://buildkite.com/ray-project/oss-ci-build-branch/builds/2061#0186036d-cb12-4fb7-a4a7-b04ea63c8ab3 cc @krfricke

**Comment by cadedaniel** [comment]
This is causing false-positives in the 2.3 Ray release. I haven't seen it fail, just timing out 3/3.

**Comment by jianoaix** [comment]
Got a failure with useful message: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2165#_

It looks there was a running cluster when this test tried to start a new one, fix: https://github.com/ray-project/ray/pull/32200

**Comment by c21** [comment]
update: https://github.com/ray-project/ray/pull/33101/ is merged, and should fix the flaky completely.

Seeing promising trend now as below. Will wait for 1 day before closing this issue.

<img width="1642" alt="Screen Shot 2023-03-07 at 12 35 22 PM" src="https://user-images.githubusercontent.com/4629931/223546316-cec0e2ff-3919-4b4c-96de-7b695fd843a8.png">
