### ISSUE TITLE
[Ray 2.3 release] many_nodes_actor_test_on_v2 fails inexplicably

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32060]
BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1315#0185f566-3dfe-4417-bb59-29c0b0d7edfa

The first try failed on a BuildKite timeout (is this an issue?). The second try has a failure exitcode but the logs look like it succeeded. Logs: https://gist.githubusercontent.com/cadedaniel/80c95c799d8c1e2541e2b38ac02c6a46/raw/5e2277a5108d01607d59fa22eb5e6a0ae7344f04/gistfile1.txt

```
Waiting for cluster to be up: 4064->4064->4064
Start launch actors
Status: 20000/20000, 1043.7020626
Actor launch time: 14.368878342000016 (20000 actors)
Actor ready time: 1043.7021312149998 (20000 actors)
Total time: 1058.0710095569998 (20000 actors)
Through put: 18.90232301929691
```

**Comment by iycheng** [comment]
Hmmm, it passed here: https://buildkite.com/ray-project/release-tests-branch/builds/1320#0186048f-41f6-4d3c-a6bd-8877c98a78aa

I think maybe because https://github.com/ray-project/ray/pull/31995 got reverted and it got remerged this morning.

I'm rerunning the whole test to see what happened.

**Comment by iycheng** [comment]
https://buildkite.com/ray-project/release-tests-branch/builds/1323#018604d5-f09a-42c7-ba11-53d0fe74bdd5

I think it looks good now. Close it. Feel free to reopen it if it still fails.
