### ISSUE TITLE
[rllib] TF eager error

### ISSUE THREAD

**Issue by Ai360n** [ray-project/ray#32098]
### What happened + What you expected to happen

Hello,

I have trained an agent in customized environment and now when I restore the check points, I get this warning and it can not load the check points appropriately:
 Cannot restore an optimizer’s state for tf eager!
Keras is not able to save the v1.x optimizers (from tf.compat.v1.train) since they aren’t
compatible with checkpoints.

However, I had selected framework=‘tf2’ and eager_tracing=True in configuration dict.

Could you help me to solve this problem?

Thanks in advance

### Versions / Dependencies

Python = 3.10
Ray = ray 2.2.0
OS = Linux Ubuntu
tf = Tensorflow 2.11

### Issue Severity

Low: It annoys or frustrates me.

**Comment by Ai360n** [comment]
Ray's developers do not know how this problem can be solved ?

**Comment by hora-anyscale** [comment]
@Ai360n - can you please share a more detailed repro script?

**Comment by Ai360n** [comment]
class GDGR(gym.Env):
def init(self,env_config):
…
def reset(self):
…
def step(self, action):
…

…
.
ray.init(num_gpus=1,num_cpus = 4)
config = DEFAULT_CONFIG.copy()

.
.
.

register_env(“GDGR”, lambda config …)
.
.
.
config[“soft_horizon”] = 2048
config[“framework”] = “tf2”
.
.
.
.
Trainer = ppo.PPOTrainer(config=config)

.
.
.
.
Training process …

For loading, I used this:

algo = Algorithm.from_checkpoint(path)

**Comment by ArturNiederfahrenhorst** [comment]
Hi, before we dive into this. could you try this with a PPO config? 

The reproduction script lacks imports and such things, so I can not reproduce atm.

**Comment by avnishn** [comment]
This is still lacking the proper information that we need to reproduce it. Can you provide a full reproduction scrip that we can run out of the box?

Thanks

**Comment by Ai360n** [comment]
> Hi, 
> Thanks for reporting this.
> Before we dive into this. could you try this with a PPO config? 
> The reproduction script lacks imports and such things, so I can not reproduce atm.

Hello,
Thank you so much.
I solved this issue by my approach. But, before I release my solution, I had a question.
How I could use callbacks in Trainer.train() ? To get and save metrics or infromation about training?


Thanks in advance

**Comment by bonti69** [comment]
@Ai360n  What is the solution to this problem? I am facing the same issue.

**Comment by ArturNiederfahrenhorst** [comment]
@bonti69 Feel free to post your reproduction script here so we can work on a solution.

**Comment by avnishn** [comment]
closing this for now as there is no repro script

**Comment by kapsl** [comment]
I have the same error message

**Comment by ArturNiederfahrenhorst** [comment]
@kapsl Thanks for bringing it up.
Please post a reproduction script and reopen the issue if you don't see it solved.
