### ISSUE TITLE
[Dashboard] Object store metric (max) is not accurate in ray dashboard

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#32092]
### What happened + What you expected to happen

I set the object store to 15GiB. The time-series metric shows a different max number which is incorrect. The node table shows the right number.

![image](https://user-images.githubusercontent.com/9677264/215638182-32c0c41f-f629-4bc2-a47c-158420a29534.png)
![image](https://user-images.githubusercontent.com/9677264/215638200-f0212f75-1916-4522-bdb8-d036493c907e.png)

### Versions / Dependencies

nightly

### Reproduction script

open a single-node cluster and you'll see this discrepency.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ericl** [comment]
Is this a GiB vs GB mixup? Presumably the underlying unit is bytes, so the y-axis is indeed incorrect and should say "GB" instead of "GiB".

It would be helpful to post the output of `ray.available_resources()` to get the ground truth number in this case.

**Comment by scottsun94** [comment]
<img width="463" alt="Screen Shot 2023-01-31 at 12 56 44 PM" src="https://user-images.githubusercontent.com/9677264/215881464-c851d355-48d9-44b5-8813-d4777318cfbf.png">
@ericl you are right. Basically, it is 16106127360.0 bytes, which is 15GiB and 16.1GB. The node table and the chart actually use the wrong units?

We should just be consistent. Shall we pick GiB or GB in the dashboard?

**Comment by rkooo567** [comment]
Is this same for memory field?
