### ISSUE TITLE
[tune/train] remove train's auto-filled fields like `_training_iteration` etc that are duplicated with tune 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32111]
### What happened + What you expected to happen

train session doesn't keep track of `_training_iteration` correctly - it's always resetting to 0 upon restore. 
tune session already has another one called `training_iteration`. 

We should remove those duplicated ones as train is always executed using tune now.

The same for `_time_this_iter_s`.

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
cc @amogkam 
is there any concern about that?

**Comment by amogkam** [comment]
Sgtm

**Comment by xwjiang2010** [comment]
current:

```
Result for TorchTrainer_d105f_00001:
  _time_this_iter_s: 44.51650929450989
  _timestamp: 1675583491
  _training_iteration: 1
  date: 2023-02-04_23-51-32
  done: false
  experiment_id: 1fce989d7b024802bfe7c64db4d0c870
  hostname: ip-172-31-167-98
  iterations_since_restore: 1
  loss: 1.5769963838435985
  node_ip: 172.31.167.98
  pid: 7410
  should_checkpoint: true
  time_since_restore: 49.9669713973999
  time_this_iter_s: 49.9669713973999
  time_total_s: 49.9669713973999
  timestamp: 1675583492
  timesteps_since_restore: 0
  training_iteration: 1
  trial_id: d105f_00001
  warmup_time: 0.1430068016052246
```
