### ISSUE TITLE
[tune] tracking ticket for tune `log_to_file` feature request from community

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32142]
### Description

https://docs.ray.io/en/latest/tune/tutorials/tune-output.html

Please comment on this ticket what is your ideal workflow working with logs in trainables! We want to make it happen!

**Comment by daveqs** [comment]
Generating logs in trainables is currently breaking FLAML AutoML's Ray Tune backend. I have described the specifics on the Ray community slack in

https://ray-distributed.slack.com/archives/CNECXMW22/p1706587052182639
