### ISSUE TITLE
[Datasets][Doc] Update Ray Data documentation and code snippet for 2.3 release

### ISSUE THREAD

**Issue by c21** [ray-project/ray#32144]
### Description

Given we enabled lazy execution by default in 2.3, we need to check all code snippet and documentation for Ray Data. We also need to communicate to users in the doc, that the currently execution becomes lazy.

Will split the work between @c21, @jianoaix and @clarkzinzow.

**Comment by c21** [comment]
Working on this via https://github.com/ray-project/ray/pull/32394 and https://github.com/ray-project/ray/pull/32387

**Comment by cadedaniel** [comment]
Closing this cc @c21
