### ISSUE TITLE
[CI] `//python/ray/data:tests/test_object_gc` is flaky in master

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32168]
* https://buildkite.com/ray-project/oss-ci-build-branch/builds/2138#01860d2e-08c3-436d-ad22-f8115a3b567e

```
>       assert "Spilled" not in meminfo, meminfo
E       AssertionError: --- Aggregate object store stats across all nodes ---
E         Plasma memory usage 370 MiB, 663 objects, 55.43% full, 0.0% needed
E         Spilled 672 MiB, 1115 objects, avg write throughput 423 MiB/s
E         Objects consumed by Ray tasks: 5133 MiB.
E         
E       assert 'Spilled' not in '--- Aggrega... 5133 MiB.\n'
E         'Spilled' is contained here:
E           --- Aggregate object store stats across all nodes ---
E           Plasma memory usage 370 MiB, 663 objects, 55.43% full, 0.0% needed
E           Spilled 672 MiB, 1115 objects, avg write throughput 423 MiB/s
E         ? +++++++
E           Objects consumed by Ray tasks: 5133 MiB.
```

**Comment by cadedaniel** [comment]
Oh, I thought this wasn't flaky but I must have checked the wrong test in the flaky test tracker.
<img width="385" alt="Screen Shot 2023-02-01 at 8 58 42 AM" src="https://user-images.githubusercontent.com/950914/216110383-f51fc86c-342f-4e7b-af89-4f64aba424c3.png">

**Comment by jianoaix** [comment]
It's been stable now:
<img width="750" alt="Screen Shot 2023-03-13 at 1 10 21 PM" src="https://user-images.githubusercontent.com/99709935/224821021-37c16607-31c3-455f-8d18-650ed02de5a3.png">
