### ISSUE TITLE
[core] `long_running_node_failures (24d0376)` weekly test failure

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32180]
* BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1328#01860e31-1e58-4868-86c6-a1ea9871a2e9
* Cluster: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_s995zcp3417cgack7jg1mypawy?command-history-section=command_history&drivers-section=interactive-sessions

```
Iteration 280:
  - Iteration time: 66.5609016418457.
  - Absolute time: 1675286765.9613054.
  - Total elapsed time: 10903.077851772308.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 295, in __init__
    self._plasma_store_socket_name,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/services.py", line 436, in wait_for_node
    raise TimeoutError("Timed out while waiting for node to startup.")
TimeoutError: Timed out while waiting for node to startup.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workloads/node_failures.py", line 68, in <module>
    cluster.add_node()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/cluster_utils.py", line 224, in add_node
    spawn_reaper=self._shutdown_at_exit,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/node.py", line 299, in __init__
    "The current node has not been updated within 30 "
Exception: The current node has not been updated within 30 seconds, this could happen because of some of the Ray processes failed to startup.
```

**Comment by cadedaniel** [comment]
Happened again on retry https://buildkite.com/ray-project/release-tests-branch/builds/1328#01860f03-4417-4793-8c75-d97bf73b624f

**Comment by cadedaniel** [comment]
Talked to Yi and Shomil. The test has a virtual cluster, so single node (but Ray thinks it's multiple nodes). So unlikely to be an issue with product. Next steps are to see when this started failing.

**Comment by cadedaniel** [comment]
cc @iycheng can you take this on?

**Comment by iycheng** [comment]
@cadedaniel  I might not have time on this since I'm working on https://github.com/ray-project/ray/issues/32090 which seems tricky. Do you mind finding someone else?

**Comment by cadedaniel** [comment]
I'm not sure why it's failing -- I don't see anything out of the ordinary in the raylet logs of the "nodes". Also the longest living raylet (from the logs) is only 11 seconds. So I'm not sure what is taking longer than 30s.
```
...
10.797 raylet.257.out_end00
10.876 raylet.261.out_end00
11.065 raylet.248.out_end00
```

**Comment by cadedaniel** [comment]
Created https://github.com/ray-project/ray/pull/32303 to hopefully allow us to solve this the next time it happens. I don't think there's anything we can do for now; we should remove release-blocking status.
