### ISSUE TITLE
[Ray release infra] `.buildkite/copy_files.py` is flaky, failing with `Getting Presigned URL, status_code 502`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32185]
I'm seeing this failure on a range of different CI tests (commit and release). 

Example BuildKite: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2143#01860e3d-938d-4a7f-aa4f-b903f40da171

```
+ python .buildkite/copy_files.py --destination logs --path /tmp/bazel_event_logs
--
  | Getting Presigned URL, status_code 502
  | errored, retrying...
  | {"message": "Internal server error"}
  | Getting Presigned URL, status_code 502
  | errored, retrying...
  | {"message": "Internal server error"}
  | Getting Presigned URL, status_code 502
  | errored, retrying...
  | {"message": "Internal server error"}
  | Getting Presigned URL, status_code 502
  | errored, retrying...
  | {"message": "Internal server error"}
  | Getting Presigned URL, status_code 502
  | errored, retrying...
  | {"message": "Internal server error"}
  | still errorred after many retries
```

**Comment by cadedaniel** [comment]
At the very least, we should improve this retry function to throw an exception (with full stacktrace) on retry failures. https://github.com/ray-project/ray/blob/master/.buildkite/copy_files.py#L18

**Comment by hora-anyscale** [comment]
@krfricke - what priority should this be?

**Comment by hora-anyscale** [comment]
@cadedaniel - also, could you please provide the impact and severity of what you are seeing? Is this still happening and how often?

**Comment by aslonnie** [comment]
what is behind this vop4ss7n22.execute-api.us-west-2.amazonaws.com ? how is that being hosted?

**Comment by can-anyscale** [comment]
After much investigation, this 502 error comes down to a layer of stacks. At the end of that stack is an aws lambda function. The logs is all together to super hard to spot the what errors it come from, but manage to combine the error time series metric, time stamp and buildkite id, here is the error "<Timestamp> <Request_ID> Task timed out after 3.01 seconds".

Metrics also shown that there are a good number of requests just right about the 3 mark limit, which does collerate with the number of concurrent requests as well.

I increased the timeout so this should/hopefully go away. Will think later if/why we do aws request/lambda to see if we can just move this upload logic into ci/cd itself.

**Comment by can-anyscale** [comment]
This has gone for 3 days now. Closing.
