### ISSUE TITLE
[Serve] Converting serve config to KubeRay config compatible format

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/ray#32197]
### Description

The `serve build` command currently only supports either creating a KubeRay compatible config with the `-k` flag (with camel casing) or a serve config with snake case. Having a command that supports converting existing serve config to KubeRay config compatible format or even directly integrating it to a sample KubeRay config would be very useful.

### Use case

I prefer having all deployment config to be directly written in the yaml file instead of specifying some config in the code, using the `serve build` command to generate a yaml file and adding the runtime env in the file later. I use this yaml file to test code locally using `serve run`.

Now when I want to deploy my code on Kubernetes, I need to copy-paste the config to the KubeRay config and then manually change the snake case to camel case. I'm trying to automate this so that moving from local to production is easy by using a script like [this](https://gist.github.com/shrekris-anyscale/268182f6ad89d7a3e0a9eecc604045bf) to make the snake -> camel case conversion and automatically embedding the serve config to an existing / sample KubeRay config like [this one[(https://github.com/ray-project/kuberay/blob/release-0.3/ray-operator/config/samples/ray_v1alpha1_rayservice.yaml).

It would be very useful if the serve CLI had a command that would make it easier to move from a local setup to a production setup to avoid manual intervention.

**Comment by akshay-anyscale** [comment]
No longer needed due to changes planned in https://github.com/ray-project/kuberay/issues/1137

**Comment by smit-kiri** [comment]
> No longer needed due to changes planned in [ray-project/kuberay#1137](https://github.com/ray-project/kuberay/issues/1137)

That's perfect!
