### ISSUE TITLE
[CI] `//python/ray/serve:test_gradio` and `//python/ray/serve:test_gradio_visualization` flaky

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32201]
BuildKite: https://buildkite.com/ray-project/oss-ci-build-branch/builds/2161#018610f0-6a6e-4896-96e2-45b8e4754cb5
They timed out in 3/3 cases.

**Comment by sihanwang41** [comment]
@zcin feel free to close it if that is fixed.

**Comment by zcin** [comment]
Closing as it has not been flaky on master.
