### ISSUE TITLE
[core/tune] Performance regression in tune_scalability_bookkeeping_overhead

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#32202]
Bisection revealed that the offending commit is either https://github.com/ray-project/ray/commit/d74e4c42ebd03d8ce274a84591043bd004c7b522 or https://github.com/ray-project/ray/commit/b2c5e63bf7df2b105dbdcaeb558c682c9103712f.

d74e4c42ebd03d8ce274a84591043bd004c7b522 Started failing: https://buildkite.com/ray-project/release-tests-branch/builds/1349#_

But 47bb652de59e0fc7fde26262b48918cdd7ffa64c passed: https://buildkite.com/ray-project/release-tests-branch/builds/1348#018614a4-c26b-48cb-8f95-b9afaef8aa9f

The test starts 10k trials and measured time until completion. It should finish below 600 seconds but started taking ~1000 second after the offending commit.

**Comment by cadedaniel** [comment]
Assigning to Kai until we have more information

**Comment by krfricke** [comment]
Confirmed it's https://github.com/ray-project/ray/commit/d74e4c42ebd03d8ce274a84591043bd004c7b522

Last passing commit ([b2c5e63bf7df2b105dbdcaeb558c682c9103712f](https://buildkite.com/ray-project/release-tests-branch/builds/1350)): https://buildkite.com/ray-project/release-tests-branch/builds/1348#018614a4-c26b-48cb-8f95-b9afaef8aa9f

Failing commit (d74e4c42ebd03d8ce274a84591043bd004c7b522): https://buildkite.com/ray-project/release-tests-branch/builds/1349

Passing:

```
  time_taken = 785.9125583
```

Failing:

```
[ERROR 2023-02-02 17:30:12,614] run_release_test.py: 157  Took too long to complete (time_taken=981.51 > 800).
```

**Comment by zhe-thoughts** [comment]
Thanks @krfricke . Are we reverting https://github.com/ray-project/ray/commit/d74e4c42ebd03d8ce274a84591043bd004c7b522?

**Comment by krfricke** [comment]
I'm not sure if any other commits or blockers depend on it so will refer to core (cc @rickyyx) to decide. But generally would be in favor for reverting

**Comment by rickyyx** [comment]
Trying a few forward fix today. Will give an update. If not, we could revert.

**Comment by cadedaniel** [comment]
Leaving open until it's cherry picked

**Comment by zhe-thoughts** [comment]
@cadedaniel I guess we can close this now? Thanks
