### ISSUE TITLE
[Ray 2.3 Release] Failure in `dataset_shuffle_sort_1tb` "no locations were found for the object"

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32203]
Marking as a release blocker until we think otherwise.
BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1333#0186130c-207a-4e3e-a563-a8f2f329b498

```
ray.exceptions.RayTaskError: ray::_sample_block() (pid=143721, ip=172.31.205.93)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.ObjectFetchTimedOutError: Failed to retrieve object f57510499cea6ea7ffffffffffffffffffffffff0300000002000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

Fetch for object f57510499cea6ea7ffffffffffffffffffffffff0300000002000000 timed out because no locations were found for the object. This may indicate a system-level bug.
```

**Comment by cadedaniel** [comment]
Retrying it here https://buildkite.com/ray-project/release-tests-branch/builds/1333#01861511-8d2d-4af5-a7d6-1af2dd30fea1

**Comment by zhe-thoughts** [comment]
Hi @cadedaniel , looks like this has failed again?

**Comment by cadedaniel** [comment]
cc @jianoaix can you look into this release test failure?

**Comment by cadedaniel** [comment]
I retried this and it failed due to timeout. There were OOM messages in the logs. So one hypothesis is that the OOMs are new and causing this test to fail.

* https://buildkite.com/ray-project/release-tests-branch/builds/1333#01861511-8d2d-4af5-a7d6-1af2dd30fea1
* https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_vb2ewp35c1ax1ykw49x5nwyely?command-history-section=command_history&drivers-section=interactive-sessions

**Comment by cadedaniel** [comment]
I'm also seeing `dask_on_ray_1tb_sort` fail with similar OOM messages. Not sure if they're related. https://buildkite.com/ray-project/release-tests-branch/builds/1332#018615fa-2699-4d69-a504-30fb4eda57ad

**Comment by jianoaix** [comment]
The commit causing this failure may be in range from d15ccfcdf290e554846d2fddf2b8cf5d659e9892 to 6d39879899eb03c5eec0790b972da82a64c04d94. We can bisect this range.

**Comment by zhe-thoughts** [comment]
Thanks @jianoaix !

@jianoaix @c21 : should we revert #32160?

**Comment by jianoaix** [comment]
That PR is a bug fix, so we'll need to keep it (unless we revert even more). We'll work on debugging/fixing it today.

**Comment by c21** [comment]
Update:

We did more debugging and found https://github.com/ray-project/ray/pull/32160 is not the root cause.
The root cause is highly likely OOM-related and unfortunately non-deterministic. We need to keep looking at it.
https://github.com/ray-project/ray/pull/32329 should fix the nightly test to surface the real root cause when it's failed.

**Comment by jianoaix** [comment]
Now it seems more difficult to reproduce; had a few runs but none of them failed. Trying a few more.

**Comment by jianoaix** [comment]
Yet to produce a failure to see the log. I'm running two concurrently now and should get result in about half hour.
Previously it didn't log anything about the failure before it re-ran the execution with `ds.stats()` which then hit timeout.

**Comment by cadedaniel** [comment]
Are you running on master or the release branch? It's possible something changed in master

**Comment by jianoaix** [comment]
master, sounds good to start a few in 2.3 branch.

**Comment by jianoaix** [comment]
The failure/flakiness ran by master's nightly recently has been consistent, it's likely reproducible (just needs a few more tries):
<img width="1685" alt="Screen Shot 2023-02-09 at 3 35 42 PM" src="https://user-images.githubusercontent.com/99709935/217963040-65395ace-5d07-406c-934e-ea28a155f458.png">

**Comment by jianoaix** [comment]
Ok, got log from a failure now: https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_jxk4uxrewk4lvkstygni9q6641

It's failing on OOM:
```
Traceback (most recent call last):
  File "dataset/sort.py", line 174, in <module>
    raise exc
  File "dataset/sort.py", line 122, in <module>
    ds.fully_executed()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/dataset.py", line 3945, in fully_executed
    self._plan.execute(force_read=True)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/plan.py", line 536, in execute
    dataset_uuid=self._dataset_uuid,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/legacy_compat.py", line 84, in execute_to_legacy_block_list
    bundles = executor.execute(dag, initial_stats=stats)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/bulk_executor.py", line 82, in execute
    return execute_recursive(dag)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/bulk_executor.py", line 62, in execute_recursive
    op.inputs_done()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/operators/all_to_all_operator.py", line 57, in inputs_done
    self._output_buffer, self._stats = self._bulk_fn(self._input_buffer, ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/execution/legacy_compat.py", line 245, in bulk_fn
    block_list, ctx, input_owned, block_udf, remote_args
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/stage_impl.py", line 214, in do_sort
    return sort_impl(blocks, clear_input_blocks, key, descending)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/sort.py", line 153, in sort_impl
    clear_input_blocks,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/shuffle.py", line 117, in execute
    new_metadata = reduce_bar.fetch_until_complete(list(new_metadata))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/data/_internal/progress_bar.py", line 76, in fetch_until_complete
    for ref, result in zip(done, ray.get(done)):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py", line 2391, in get
    raise value
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 172.31.168.7, ID: b562bad5e2d1df7ff24635eeb87fd02f736594b61d49941aea197143) where the task (task ID: 049cde2ae8f42f3cca424a2eb2f4f363c23d944803000000, name=reduce, pid=100516, memory used=3.02GB) was running was 54.74GB / 57.60GB (0.950292), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 7c69a053bf2ba6079e914f111a4a051e128f73949cd67bfd0a219d47) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 172.31.168.7`. To see the logs of the worker, use `ray logs worker-7c69a053bf2ba6079e914f111a4a051e128f73949cd67bfd0a219d47*out -ip 172.31.168.7. Top 10 memory users:
PID	MEM(GB)	COMMAND
1242	5.30	ray::IDLE_SpillWorker
124	3.94	/home/ray/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=...
100516	3.02	ray::reduce
```
I think @clarng is working on a change to avoid throwing this error, which should be able to fix this test.

Maybe one followup left for us is to figure out if there is a regression in memory efficiency.

**Comment by c21** [comment]
just FYI I don't think there's any code change for `sort()` in 2.3.

**Comment by cadedaniel** [comment]
@clarng can you advise here? would changing to `retriable_lifo` fix this issue? https://github.com/ray-project/ray/pull/32361/files

**Comment by jianoaix** [comment]
I'm trying with `retrieable_lifo` for this test:
- https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_a53nr1iil5b1byejpel5bfny7x
- https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_wibni8tdvw4rrpd8st7xzvega8

**Comment by clarng** [comment]
These are orthogonal issues, we've seen this happen with chaos test as well, when we kill nodes it could fail the applicatio

**Comment by jianoaix** [comment]
This test is killing a task, should it not throw OOM in this case?

**Comment by clarng** [comment]
Not it should not, it will get OOM Error and retry

**Comment by jianoaix** [comment]
Both above tests passed. @clarng do you recommend enabling `retriable_lifo` for this test as well?

**Comment by jianoaix** [comment]
Verified with another 4 times and they all passed. Enabling it: https://github.com/ray-project/ray/pull/32417

**Comment by clarng** [comment]
The test passed when we submitted the PR (https://buildkite.com/ray-project/release-tests-pr/builds/26717), but looks like it is causing flakiness
