### ISSUE TITLE
[Datasets] Support reading compressed TFRecord file

### ISSUE THREAD

**Issue by c21** [ray-project/ray#32205]
### Description

We found user has use case to read compressed TFRecord file (gzip in the particular case). PyArrow already provide a [pyarrow.CompressedInputStream](https://arrow.apache.org/docs/python/generated/pyarrow.CompressedInputStream.html) wrapper to read compressed file, so we can easily add support to read TFRecord file with common compression algorithms (“bz2”, “brotli”, “gzip”, “lz4” or “zstd”).

### Use case

Unblock users to read TFRecord file with Ray Data for training workload.

**Comment by scottjlee** [comment]
I found that I was able to read compressed TFRecord file using the `arrow_open_stream_args` arg of `ray.data.read_tfrecords` ([pyarrow docs](https://arrow.apache.org/docs/python/generated/pyarrow.fs.FileSystem.html#pyarrow.fs.FileSystem.open_input_stream)):

```
import tensorflow as tf
import os

import tempfile

features = tf.train.Features(
    feature={
        "int64": tf.train.Feature(int64_list=tf.train.Int64List(value=[1])),
        "int64_list": tf.train.Feature(
            int64_list=tf.train.Int64List(value=[1, 2, 3, 4])
        ),
        # "int64_empty": tf.train.Feature(int64_list=tf.train.Int64List(value=[])),
        "float": tf.train.Feature(float_list=tf.train.FloatList(value=[1.0])),
        "float_list": tf.train.Feature(
            float_list=tf.train.FloatList(value=[1.0, 2.0, 3.0, 4.0])
        ),
        # "float_empty": tf.train.Feature(float_list=tf.train.FloatList(value=[])),
        "bytes": tf.train.Feature(bytes_list=tf.train.BytesList(value=[b"abc"])),
        "bytes_list": tf.train.Feature(
            bytes_list=tf.train.BytesList(value=[b"abc", b"1234"])
        ),
        # "bytes_empty": tf.train.Feature(bytes_list=tf.train.BytesList(value=[])),
    }
)
example = tf.train.Example(features=features)

options = tf.io.TFRecordOptions(compression_type="GZIP")
example_path = os.path.join(tempfile.gettempdir(), "example.tfrecords")
with tf.io.TFRecordWriter(example_path, options=options) as writer:
    writer.write(example.SerializeToString())

import ray
ds = ray.data.read_tfrecords([example_path], arrow_open_stream_args={"compression": "gzip"})
ds.take()
>>> [{'int64': 1, 'int64_list': [1, 2, 3, 4], 'float': 1.0, 'float_list': [1.0, 2.0, 3.0, 4.0], 'bytes': b'abc', 'bytes_list': [b'abc', b'1234']}]
```

[TFRecords supports `GZIP` and `ZLIB`](https://www.tensorflow.org/api_docs/python/tf/io/TFRecordOptions#args), both of which work with the `read_tfrecords` compression type specified as `"gzip"`. Is this existing path sufficient, or do we want to explicitly expose the compression type as an arg of `ray.data.read_tfrecords`?
