### ISSUE TITLE
[java] Documentation for Java?

### ISSUE THREAD

**Issue by tungwini** [ray-project/ray#3221]

**Comment by jovany-wang** [comment]
What kinds of documentation do you refer to?

**Comment by ggdupont** [comment]
Not sure about the request by @tungwini but on my end I would be glad to have a kind of quickstart for java application setup over ray. Not really on the API usage part (it's already quite clear with the examples in tutorial), but more on the steps to setup and deploy a standalone application from scratch. 

@robertnishihara started something here: https://github.com/ray-project/ray/pull/2094 but it seems not up-to-date.

**Comment by tungwini** [comment]
It's been a while, but I believe I was looking for quick start instructions for java (like Python)

**Comment by raulchen** [comment]
@tungwini @ggdupont sorry for missing this issue. In the [README file under java directory](https://github.com/ray-project/ray/tree/master/java), there're some docs that may be helpful for you:
- [Installation guide](https://github.com/ray-project/ray/blob/master/java/doc/installation.rst)
- [API doc](https://github.com/ray-project/ray/blob/master/java/doc/api.rst)
- [Tutorial with more examples](https://github.com/ray-project/ray/tree/master/java/tutorial)

Please let me know if what you're interested in is missing. We're working on enhancing the docs.

**Comment by jovany-wang** [comment]
@tungwini  @ ggdupont
If I understand it correctly, you need a tutorial how to start a cluster and how to run your App on it?

We can start a Java cluster like the way of starting Python cluster in the near future.
@raulchen but it looks like that  we don't have this kind of tutorial right now?

**Comment by ggdupont** [comment]
@jovany-wang yes that would be great.

Right now I'm trying to follow this process by @robertnishihara : https://github.com/ray-project/ray/pull/2094#issuecomment-391912704

I updated the procedure and intend to submit a PR, but I'm still having issues with unsatisfied libraries... Getting it to work on a cluster is the next step.

**Comment by jovany-wang** [comment]
@ggdupont  
Maybe you can request your PR first, then we could solve the issues together based your PR.

**Comment by ggdupont** [comment]
@raulchen yes the comment from @robertnishihara is not up-to-date. However it goes a bit further than the examples from the java exercises: it's was really java app from scratch. The exercises are running fine on my end but I can't build my app inside the maven tutorial project. I really want an independent application with my own libs and all. I'll try to work on it in the next days.

Then for the cluster part, I can wait on the PR you mentioned.

**Comment by jovany-wang** [comment]
@ggdupont 
This https://github.com/ray-project/ray/pull/3838 PR may help you to start a Ray cluster to run Java codes.

**Comment by richardliaw** [comment]
Should be done.

**Comment by raulchen** [comment]
@tungwini Please see https://docs.ray.io/en/master/ for the latest Java doc.
