### ISSUE TITLE
[Core] Actor `__ray_terminate__` seems to always be marked as failed when an actor terminates.

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#32220]
### What happened + What you expected to happen

I'm running a slightly modified ray air example for distributed training + tuning: https://gist.github.com/alanwguo/4aa1965eaab1091e3caf91b7bc507e1d

The job successfully finishes but the TrainingActors  __ray_terminate__ tasks always seem to fail when the actors are killed.

<img width="1654" alt="Screenshot 2023-02-03 at 8 34 42 PM" src="https://user-images.githubusercontent.com/711935/216749455-0bec31ad-483e-423d-81fb-857702efd02b.png">

### Versions / Dependencies

Nightly

### Reproduction script

https://gist.github.com/alanwguo/4aa1965eaab1091e3caf91b7bc507e1d

### Issue Severity

Low: It annoys or frustrates me.

**Comment by alanwguo** [comment]
I was able to easily get the stack trace using the new dashboard UI:
```
<class 'SystemExit'>
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 857, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 861, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 803, in ray._raylet.execute_task.function_executor
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/actor.py", line 1330, in __ray_terminate__
    ray.actor.exit_actor()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/actor.py", line 1397, in exit_actor
    raise exit
SystemExit: 0
```

**Comment by chongxiaoc** [comment]
We see this is still happening with Ray Train using Ray 2.5.

**Comment by xieus** [comment]
@chongxiaoc Thanks for bring this up. We are looking into this and I will circle back.

@matthewdeng Could you take a quick look and recommend a desirable behavior from Train/Tune respective?

**Comment by matthewdeng** [comment]
Hmm looks like it's due to some worker shutdown logic we have here:

https://github.com/ray-project/ray/blob/d508b6a95ed815cd540773cfe8dade6ec37daa4a/python/ray/train/_internal/worker_group.py#L206-L231

What's the recommended way to cleanup Actors? To simplify things perhaps we could just directly call `ray.kill`? In practice I'm not sure what benefit this graceful shutdown logic provides.

**Comment by rkooo567** [comment]
@rickyyx can we close it?

**Comment by HeeebsInc** [comment]
i am facing the same issue. Its not a blocker, but like OP mentioned, its a bit frustrating to see a task "fail" when it actually just completed.  There seems to be a delay between the actor getting killed/going out of reference, to when it sends success to the dashboard, causing the dashboard to show failure.  

In the dashboard we see failures (though we know it succeeded, with the following message)

```
Error Type: WORKER_DIED

Worker running the task (d8552d4c7587710c40b8fd8ec2668baff7da390ede1252b3edc3942a) died with exit_type: 1 with error_message: Worker exits because the actor is killed. The actor is dead because all references to the actor were removed.
```
