### ISSUE TITLE
[Ray 2.3 Release] `stress_test_many_tasks.json ` `stage_3_time` has 17% regression in 2.3.0

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32235]
From preliminary performance comparison PR: https://github.com/ray-project/ray/pull/32086/files
* stage_0_time 54% regression
* stage_3_time 17% regression

**Comment by cadedaniel** [comment]
@rickyyx: The 54% regression might just be due to high variance

![image](https://user-images.githubusercontent.com/950914/217060263-41f8a3bf-9c9b-469c-a126-9cd2b1daecd3.png)

**Comment by cadedaniel** [comment]
The release test is timing out, likely because of this https://buildkite.com/ray-project/release-tests-branch/builds/1333#0186150b-32aa-4666-aaa2-688171f796f3

**Comment by rkooo567** [comment]
We will see if @rickyyx's work on microbenchmark will fix stage 3

**Comment by scv119** [comment]
confirmed regression is caused by d74e4c42eb

**Comment by scv119** [comment]
[d74e4c42eb](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_ytldcckb9i4jmyykvir5sfu6n1?command-history-section=head_start_up_log) [core][state] Adjust worker side reporting with batches && add debugstring (remerging #31840) (#32057)
INFO:__main__:Finished stage 1 after 383.62558245658875 seconds.
[b2c5e63bf7](https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_lfxx3ex25eq2d6zt16zmznifk4?command-history-section=head_start_up_log) [Core] Join Ray Jobs API `JobInfo` with GCS `JobTableData` (#31046)
INFO:__main__:Finished stage 1 after 237.37327575683594 seconds.
INFO:__main__:Finished stage 2 after 257.5613226890564 seconds.
