### ISSUE TITLE
[tune] migrate all external APIs off of _TrackedCheckpoint 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32244]
### What happened + What you expected to happen

We should migrate all external APIs off of _TrackedCheckpoint. For example tune Callback interface.

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
This is done (callback exposes a `train.Checkpoint` directly now)
