### ISSUE TITLE
[tune] HyperOptSearch should merge configs for better Rllib compatibility

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3225]
For now, the suggested config of HyperOpt directly override `experiment.spec["config"]` (https://github.com/ray-project/ray/blob/master/python/ray/tune/suggest/suggestion.py#L94), which have two issues:
- `env` is missing, and it will throw an error when instantiate an agent.
- Other custom configs, which do not need to tune, are also missing, e.g., agent.config["model"]["custom_model"].

The following changes can repair the bug:
<pre>
            #spec = copy.deepcopy(experiment_spec)
            #spec["config"] = suggested_config
            self._counter += 1
            tag = "{0}_{1}".format(
                str(self._counter), format_vars(suggested_config))
            spec = ray.rllib.utils.merge_dicts(experiment_spec, {"config": suggested_config})
</pre>
and we can tune parameters using HyperOpt and pass some custom options:
<pre>
config = {
    # "random_seed": grid_search([1, 2, 3, 4, 5]),
    # "inner_lr": grid_search([0.01]),
    # "inner_grad_clip": grid_search([10.0, 20.0]),
    # "clip_param": grid_search([0.1, 0.2, 0.3]),
    # "vf_loss_coeff": grid_search([0.01, 0.02, 0.05, 0.1, 0.2]),
    # "vf_clip_param": grid_search([5.0, 10.0, 15.0, 20.0]),
    "model": {
        "custom_model": "maml_mlp",
        "fcnet_hiddens": [100, 100],
        "fcnet_activation": "tanh",
        "custom_options": {"vf_share_layers": True}
    }
}

space = {
    "random_seed": hp.choice("random_seed", [1, 2, 3, 4, 5]),
    "inner_lr": hp.choice("inner_lr", [0.01]),
    "inner_grad_clip": hp.choice("inner_grad_clip", [10.0, 20.0]),
    "clip_param": hp.choice("clip_param", [0.1, 0.2, 0.3]),
    "vf_loss_coeff": hp.choice("vf_loss_coeff", [0.01, 0.02, 0.05, 0.1, 0.2]),
    "vf_clip_param": hp.choice("vf_clip_param", [5.0, 10.0, 15.0, 20.0])
}

algo = HyperOptSearch(space, reward_attr="reward_attr")
scheduler = AsyncHyperBandScheduler(
    time_attr="training_iteration",
    reward_attr="reward_attr")
run_experiments(
    {
        "maml_point": {
            "run": "MAML",
            "env": env_cls.__name__,
            "stop": {"training_iteration": 9999},
            "config": config,
            "local_dir": "/ray_results"
        }
    },
    search_alg=algo,
    scheduler=scheduler
    # with_server=True
)
</pre>
On the other hand, the current experiment tag generated by HyperOpt only keeps the last character of each var name (https://github.com/ray-project/ray/blob/master/python/ray/tune/suggest/variant_generator.py#L76), and the name of a trial is like `MAML_PointEnv_1_m=0.1,p=20.0,r=0.01,d=4,m=10.0,f=0.01`. Is this intentional? I think it's quite not convenient when visualizing in TensorBoard or post-processing files in `ray_results`.

**Comment by richardliaw** [comment]
Sorry that this took forever to get to - I've opened #3584 for this. Is the `merge_dict` important?
