### ISSUE TITLE
[RLLib] __common__ key not supported in info dict of vectorized MultiAgentEnv

### ISSUE THREAD

**Issue by Paolo-Fermin** [ray-project/ray#32267]
### The bug + expected behavior 
[Issue #20727](https://github.com/ray-project/ray/issues/20727) requested that a `__common__` key be allowed in the info dictionary returned by MultiAgentEnv to account for any information that is not tied to any particular agent. This feature was added in [Feature #20793](https://github.com/ray-project/ray/pull/20793). However, the capability is no longer included in ray 2.2.0. 

### Useful information
This [guard](https://github.com/ray-project/ray/blob/5503bcdb7f70bc7dcfaaf174a48441de8f7070c1/rllib/env/multi_agent_env.py#L665) in line 665 of multi_agent_env.py prevents the use of any key in the info dict that is not in the observation dict. This is called within the send_actions() method that is used to send actions to vectorized environments

### Versions / Dependencies

Ray 2.2.0
gym 0.26.2
Python 3.8
Ubuntu 20.04

### Reproduction script
```python
import gym
from ray.rllib.env import MultiAgentEnv

class MultiAgentCommonInfoEnv(MultiAgentEnv):
    def __init__(self, agents):
        self.agents = agents
        self.observation_space = gym.spaces.Discrete(2)
        self.action_space = gym.spaces.Discrete(2)

    def reset(self):
        obs = {agent: 0 for agent in self.agents}
        infos = {agent: "agent info" for agent in self.agents}
        infos["__common__"] = "common info"
        return obs, infos

    def step(self, action_dict):
        obs = {agent: 0 for agent in self.agents}
        rew = {agent: 0 for agent in self.agents}
        dones = {agent: False for agent in self.agents}
        infos = {agent: "agent info" for agent in self.agents}
        infos["__common__"] = "common info"
        return obs, rew, dones, infos


if __name__ == "__main__":
    # instantiate an env
    env = MultiAgentCommonInfoEnv(["agent0", "agent1"])

    # the environment on its own supports __common__ key
    env.reset()
    _, _, _, infos = env.step({"agent0": 0, "agent1": 0})
    assert "__common__" in infos

    # wrap env with a MultiAgentEnvWrapper by calling to_base_env
    # this occurs during tune training
    env = env.to_base_env(lambda _: MultiAgentCommonInfoEnv)

    # send actions to the vectorized environment
    # this throws the error
    obs, rew, dones, infos = env.send_actions({0: {"agent0": 0, "agent1": 0}})
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
@sven1977 What's the idea behind [that guard](https://github.com/ray-project/ray/blob/5503bcdb7f70bc7dcfaaf174a48441de8f7070c1/rllib/env/multi_agent_env.py#L665)?

**Comment by sven1977** [comment]
Hey @Paolo-Fermin , thanks for filing this. I don't recall, when and why we introduced this multi-agent key check, but yes, it would definitely make sense to continue allowing for a `__common__` key. We'll fix this in a PR.

In the meantime, can you try to remove the if-check in the linked code and see whether this simple hack would fix your issue?

**Comment by Paolo-Fermin** [comment]
Just built and ran your linked fork and looks like those changes fix my issue!
