### ISSUE TITLE
[tune/train] move execution related constant from `tune/result.py` to `air`

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32260]
### What happened + What you expected to happen

move execution related constant from `tune/result.py` to `air`. They are relevant beyond just tune concept.

e.g. currently `from ray.tune.result import TRAINING_ITERATION` should be scoped to `air`.

param_space, experiment related stuff should stay though.

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
This is mostly done, but should be moved to `ray.train` instead since `ray.air` is going to be removed
