### ISSUE TITLE
[Ray 2.3 Release] `shuffle_1tb_5000_partitions` failing with OOM-related errors

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32272]
Failed twice in a row on master branch on Jan 31.

I suspect it's the same issue as https://github.com/ray-project/ray/issues/32195 and https://github.com/ray-project/ray/issues/32203

* BuildKite: https://buildkite.com/ray-project/release-tests-branch/builds/1321#018604d7-86a6-4d31-be0f-2f184274d52f
* Anyscale: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_hkf1p9x61hkd22ysp87bjsh6ac?command-history-section=command_history

```
ray.exceptions.OwnerDiedError: Failed to retrieve object 00c24d5df3b26aefffffffffffffffffffffffff03000000ea240000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*932061f3dc6ded9ee31ec7d808c93f35e0d4a01ab45e04fbe1d24277*` at IP address 172.31.141.102) for more information about the Python worker failure
```

**Comment by jianoaix** [comment]
In Dataset all the objects are owned by the driver node, so if owner of an object has exited, it already means that the entire job should have finished.

**Comment by jianoaix** [comment]
I think the issue here might be the objects are not actually owned by driver. This test is running a legacy script (python/ray/experimental/shuffle.py), which isn't really Dataset. It actually created objects that are not owned by driver (https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/python/ray/experimental/shuffle.py?L190). This is not safe with the OOM killer mechanism which can then kills the object owners. cc @clarng 

We should remove this test and use https://sourcegraph.com/github.com/ray-project/ray@master/-/blob/release/nightly_tests/dataset/sort.py?L118&subtree=true for testing random shuffle.

**Comment by jianoaix** [comment]
Actually this should be orthogonal to OOM killer as it kills tasks not node. Here it's just the non-driver owner nodes make it less fault-tolerant.

**Comment by cadedaniel** [comment]
Removing release-blocker label, @zhe-thoughts is 75% confident it's not a release blocker because "the scenario of the disabled test is too far from real workloads". He will discuss with relevant folks over the weekend to confirm.

**Comment by cadedaniel** [comment]
Sang ran this test on the 2.2.0 wheel and 2.3.0 wheel, we don't see any obvious memory usage regression (if anything it improved). 

### 2.2
<img width="451" alt="2 2-shuffle_1tb_5000_partitions" src="https://user-images.githubusercontent.com/950914/218240897-c687d93f-a872-4453-8dcc-8b4a39db621a.png">

### 2.3
<img width="828" alt="2 3-shuffle_1tb_5000_partitions" src="https://user-images.githubusercontent.com/950914/218240902-e1d45cb8-74ca-4b12-91d2-960ec9774bf4.png">

**Comment by rkooo567** [comment]
cc @c21 did you try introducing 5000 partition test using dataset shuffle?
