### ISSUE TITLE
[data] More clearly label data community integrations

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#32280]
We should more clearly label our data community integrations as (1) community-maintained and (2) not officially supported: https://docs.ray.io/en/master/data/integrations.html

We can do this by renaming the integrations page to "Community Integrations", and adding verbiage / disclaimers to each landing page.

**Comment by c21** [comment]
https://docs.ray.io/en/master/data/integrations.html is already removed, closing this issue.
