### ISSUE TITLE
[RLlib][Catalog] Encoder breaks when `fcnet_hiddens = [10]`

### ISSUE THREAD

**Issue by kouroshHakha** [ray-project/ray#32309]
### What happened + What you expected to happen

If you run [this unit test](https://github.com/ray-project/ray/blob/master/rllib/algorithms/ppo/tests/test_ppo_rl_trainer.py#L48) with `fcnet_hiddens = [10]` instead of `fcnet_hiddens = [10, 10]`, the construction of the RLModule will break due to some changes that were made to the encoder from the catalog side of things. Basically the issue is that the 10 will get assigned to pi_head's hidden dim and there won't be anything left for the encoder. 

### Versions / Dependencies

master

### Reproduction script

Explained. 

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for raising this, I'm providing a fix in https://github.com/ray-project/ray/pull/32310 and will ping you soon.
