### ISSUE TITLE
[docs]front-end issue: search dropdown 

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#32318]
### Description

In the Search dropdown, I cannot scroll to the bottom of the dropdown. Instead, the scroll command affects the main page in the background. 

https://user-images.githubusercontent.com/122562471/217619458-589f3405-3b1f-4e3d-a7b5-8a85078a262f.mov

**Comment by maxpumperla** [comment]
ideally we simply solve this via this one https://github.com/ray-project/ray/pull/31992
