### ISSUE TITLE
[Datasets] ray.data.read_parquet argument 'tensor_column_schema' unable to pass

### ISSUE THREAD

**Issue by vsriram23** [ray-project/ray#32354]
### What happened + What you expected to happen

I have created parquet files with tensor data.

When I tried to read them as ray dataset by providing the argument 'tensor_column_schema' as below

ds = ray.data.read_parquet(path,tensor_column_schema={"data": (np.float32, (2, 2, 3))})

I get this error:
TypeError: from_fragment() got an unexpected keyword argument 'tensor_column_schema'

I also tried with dataset_kwargs as below

ds = ray.data.read_parquet(path,dataset_kwargs={'tensor_column_schema':{"data": (np.float32, (2, 2, 3))}})

which gives this error:

File "/opt/conda/lib/python3.8/site-packages/ray/data/datasource/parquet_datasource.py", line 61, in prepare_read
pq_ds = pq.ParquetDataset(
TypeError: __new__() got an unexpected keyword argument 'tensor_column_schema'

### Versions / Dependencies

Ray installed through pip and version is 1.9.0

### Reproduction script

import ray
import os, glob
import numpy as np
import pandas as pd

arr = np.arange(24).reshape((3, 2, 2, 2))
df = pd.DataFrame({
    "one": [1, 2, 3],
    "two": [tensor.tobytes() for tensor in arr]})

ds = ray.data.from_pandas([df])
ds.write_parquet(spath)

ds = ray.data.read_parquet(
    spath, tensor_column_schema={"two": (np.int8, (2, 2, 2))})

print(ds.schema())

sample-snippet grabbed from here
https://docs.ray.io/en/latest/data/dataset-tensor-support.html#:~:text=Cast%20from%20data%20stored%20in%20C%2Dcontiguous%20format%3A

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Hey @vsriram23-- the problem is that I think you are using examples/code snippets from more recent versions of Ray, but the actual version you are using is 1.9.

`tensor_column_schema` is not in the 1.9 API, hence it's just getting forwarded directly to Pyarrow. Can you make sure you use the same Ray version as the documentation you are looking at?

**Comment by vsriram23** [comment]
Thanks @amogkam, moving to ray 2.2.0 fixed the issue :)
