### ISSUE TITLE
RLlib CQL evaluation result is NaN

### ISSUE THREAD

**Issue by DailiZhang2010** [ray-project/ray#32365]
### What happened + What you expected to happen

I have the offline data in the path_out
I use the offline data for both of training and evaluation (I know it is not right, but just for the seek of making it work. :-) )
The code is simple. The majority of lines are just to setup the config and evaluation_config

The "eval_results["episode_reward_mean"]" is None
Please see the script.
I cannot share the data, but wonder if anyone can spot what setup I did wrong.
Thanks.

### Versions / Dependencies

Ray 2.2.0
OS: macOS Monterey
Python: 3.9

### Reproduction script

evaluation_config=(
        cql.CQLConfig()
        .offline_data(input_="dataset",
            input_config={
                "paths": [path_out],
                "format": "json",
            }
        )
        .evaluation(
        evaluation_interval=1,
        evaluation_duration=10,
        evaluation_num_workers=1,
        evaluation_duration_unit="episodes",
        evaluation_config={"input": path_out},
        off_policy_estimation_methods={
            "is": {"type": ImportanceSampling},
        },
    )
)

evaluation_config.action_space=gym.spaces.Box(
            low=np.array([0,0]), high=np.array([5000,5000]), dtype=np.float32)
evaluation_config.observation_space=gym.spaces.Box(
            low=np.array([0,0]), high=np.array([5000,50000]), dtype=np.float32)

config = (
        cql.CQLConfig()
        .framework(framework="torch")
        .rollouts(num_rollout_workers=0)
        .training(
            n_step=3,
            bc_iters=0,
            clip_actions=False,
            tau=0.005,
            target_entropy="auto",
            q_model_config={
                "fcnet_hiddens": [256, 256],
                "fcnet_activation": "relu",
            },
            policy_model_config={
                "fcnet_hiddens": [256, 256],
                "fcnet_activation": "relu",
            },
            optimization_config={
                "actor_learning_rate": 3e-4,
                "critic_learning_rate": 3e-4,
                "entropy_learning_rate": 3e-4,
            },
            train_batch_size=256,
            target_network_update_freq=1,
            num_steps_sampled_before_learning_starts=256,
        )
        .reporting(min_train_timesteps_per_iteration=1000)
        .debugging(log_level="INFO")
        .offline_data(input_="dataset",
            input_config={
                "paths": [path_out],
                "format": "json",
            }
        )
    )
config.action_space=gym.spaces.Box(
            low=np.array([0,0]), high=np.array([5000,5000]), dtype=np.float32)
config.observation_space=gym.spaces.Box(
            low=np.array([0,0]), high=np.array([5000,100000]), dtype=np.float32)

config.evaluation_config=evaluation_config
config.always_attach_evaluation_results=True

num_iterations = 5
min_reward = -300

cql_algorithm = cql.CQL(config=config)
learnt = False
for i in range(num_iterations):
    print(f"Iter {i}")
    eval_results = cql_algorithm.train().get("evaluation")
    if eval_results:
        print("... R={}".format(eval_results["episode_reward_mean"]))
        if eval_results["episode_reward_mean"] >= min_reward:
            if args.as_test:
                print("Test passed after {} iterations.".format(i))
                quit(0)
            learnt = True
            break

### Issue Severity

None

**Comment by DailiZhang2010** [comment]
Looks like the actions from the trained policy is out of spec. That might be the reason.

**Comment by ArturNiederfahrenhorst** [comment]
@DailiZhang2010 ,

Since your environment does not step through episodes, there is no episode_reward_mean that RLlib could calculate.
However, there should be a `off_policy_estimator` key in your results that estimates it's performance.
If you still hit an issue with that info, please let us know.

**Comment by joshuaspear** [comment]
> @DailiZhang2010 ,
> 
> 
> 
> Since your environment does not step through episodes, there is no episode_reward_mean that RLlib could calculate.
> 
> However, there should be a `off_policy_estimator` key in your results that estimates it's performance.
> 
> If you still hit an issue with that info, please let us know.
> 
> 

Would this also explain why the "episodes_this_iter" is not populated I.e., it only gets populated when using a simulator and not an offline dataset from a file. I had a similar question to OP. Thanks

**Comment by avnishn** [comment]
yes that is correct @joshuaspear. closing this for now as it isn't a bug.
