### ISSUE TITLE
[Job] Job supervisor logs are not printed to worker output

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#32377]
### What happened + What you expected to happen

Job supervisor info logs are not printed to worker output

### Versions / Dependencies

master

### Reproduction script

run any job submission workload

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @architkulkarni (idk if it)

**Comment by architkulkarni** [comment]
Looks like the logs are being printed successfully.

```bash
ray start --head
ray job submit -- echo hello
```

In `dashboard_agent.py`:
```
2023-03-06 13:08:41,366	INFO job_manager.py:808 -- Starting job with submission_id: raysubmit_NK5dVXsqWnQMNM6d
```

In `worker-[...].py`:
```
:job_id:01000000
:actor_name:JobSupervisor
[...]
2023-03-06 13:08:43,482	INFO job_manager.py:390 -- Submitting job with RAY_ADDRESS = 127.0.0.1:6379
```
