### ISSUE TITLE
[RLlib] adapting self_play_with_open_spiel to work with pettingzoo.classic environments

### ISSUE THREAD

**Issue by elliottower** [ray-project/ray#32382]
### What happened + What you expected to happen

I am trying to load the pettingzoo.classic.connect_four environment, but am running into issues related to observation space and action space. I believe the issue is that in all the other examples using pettingzoo, they use games which have a single observation, whereas in pettingzoo.classic the observation consists of a dict with keys "action_mask" and "observation". 

My starting point is [self_play_with_open_spiel.py](https://github.com/ray-project/ray/blob/master/rllib/examples/self_play_with_open_spiel.py), as it also uses connect four and I thought should be relatively straightforward to adapt to a different environment type. 

In issue [#30596](https://github.com/ray-project/ray/issues/30596) it is suggested to use an older pettingzoo version (1.15) in order to avoid issues with Gymnasium rather than gym, so I have been using that version. I tried with the most recent version (1.22.3) as well and had the same issues. 

I got an error about conv filter sizes and needing to define custom conv filters, but I figured before dealing with that I should get the environment loaded first, so I changed the agents to both be random. Any help would be appreciated, sorry for the long post but figured I would include all the relevant info just to make sure it's easier to find issues.

Here is the error I ran into (sorry if copypasting here makes it hard to read):

> == Status ==
> Current time: 2023-02-09 16:51:31 (running for 00:00:00.29)
> Memory usage on this node: 10.6/16.0 GiB 
> Using FIFO scheduling algorithm.
> Resources requested: 3.0/12 CPUs, 0/0 GPUs, 0.0/3.87 GiB heap, 0.0/1.94 GiB objects
> Result logdir: /Users/elliottower/ray_results/PPO
> Number of trials: 1/1 (1 RUNNING)
> +------------------------------+----------+-----------------+
> | Trial name                   | status   | loc             |
> |------------------------------+----------+-----------------|
> | PPO_connect_four_e981e_00000 | RUNNING  | 127.0.0.1:77163 |
> +------------------------------+----------+-----------------+
> 
> 
> 2023-02-09 16:51:51,365	ERROR trial_runner.py:1088 -- Trial PPO_connect_four_e981e_00000: Error processing event.
> ray.exceptions.RayTaskError(TypeError): ray::PPO.train() (pid=77163, ip=127.0.0.1, repr=PPO)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 367, in train
>     raise skipped from exception_cause(skipped)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 364, in train
>     result = self.step()
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 749, in step
>     results, train_iter_ctx = self._run_one_training_iteration()
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2623, in _run_one_training_iteration
>     results = self.training_step()
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 318, in training_step
>     train_batch = synchronous_parallel_sample(
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 85, in synchronous_parallel_sample
>     sample_batches = worker_set.foreach_worker(
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 696, in foreach_worker
>     handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 73, in handle_remote_call_result_errors
>     raise r.get()
> ray.exceptions.RayTaskError(TypeError): ray::RolloutWorker.apply() (pid=77170, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7feead1917f0>)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 183, in apply
>     raise e
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/utils/actor_manager.py", line 174, in apply
>     return func(self, *args, **kwargs)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/execution/rollout_ops.py", line 86, in <lambda>
>     lambda w: w.sample(), local_worker=False, healthy_only=True
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 900, in sample
>     batches = [self.input_reader.next()]
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 92, in next
>     batches = [self.get_data()]
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 285, in get_data
>     item = next(self._env_runner)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 671, in _env_runner
>     active_envs, to_eval, outputs = _process_observations(
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py", line 922, in _process_observations
>     prep_obs = preprocessor.transform(raw_obs)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 206, in transform
>     self.check_shape(observation)
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 68, in check_shape
>     if not self._obs_space.contains(observation):
>   File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/gym/spaces/box.py", line 143, in contains
>     x = np.asarray(x, dtype=self.dtype)
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
> The trial PPO_connect_four_e981e_00000 errored with parameters={'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, '_fake_gpus': False, 'custom_resources_per_worker': {}, 'placement_strategy': 'PACK', 'eager_tracing': False, 'eager_max_retraces': 20, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'env': 'connect_four', 'env_config': {}, 'observation_space': None, 'action_space': None, 'env_task_fn': None, 'render_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'disable_env_checking': False, 'num_envs_per_worker': 5, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'sample_async': False, 'enable_connectors': False, 'rollout_fragment_length': 'auto', 'batch_mode': 'truncate_episodes', 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'validate_workers_after_construction': True, 'ignore_worker_failures': False, 'recreate_failed_workers': False, 'restart_failed_sub_environments': False, 'num_consecutive_worker_failures_tolerance': 100, 'horizon': None, 'soft_horizon': False, 'no_done_at_end': False, 'preprocessor_pref': 'deepmind', 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'compress_observations': False, 'enable_tf1_exec_eagerly': False, 'sampler_perf_stats_ema_coef': None, 'gamma': 0.99, 'lr': 5e-05, 'train_batch_size': 4000, 'model': {'_use_default_native_models': False, '_disable_preprocessor_api': False, '_disable_action_flattening': False, 'fcnet_hiddens': [512, 512], 'fcnet_activation': 'tanh', 'conv_filters': None, 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': False, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'framestack': True, 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1}, 'optimizer': {}, 'max_requests_in_flight_per_sampler_worker': 2, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'input_config': {}, 'actions_in_input_normalized': False, 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_config': {}, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'offline_sampling': False, 'evaluation_interval': None, 'evaluation_duration': 10, 'evaluation_duration_unit': 'episodes', 'evaluation_sample_timeout_s': 180.0, 'evaluation_parallel_to_training': False, 'evaluation_config': None, 'off_policy_estimation_methods': {}, 'ope_split_batch_by_episode': True, 'evaluation_num_workers': 0, 'always_attach_evaluation_results': False, 'enable_async_evaluation': False, 'in_evaluation': False, 'sync_filters_on_rollout_workers_timeout_s': 60.0, 'keep_per_episode_custom_metrics': False, 'metrics_episode_collection_timeout_s': 60.0, 'metrics_num_episodes_for_smoothing': 100, 'min_time_s_per_iteration': None, 'min_train_timesteps_per_iteration': 0, 'min_sample_timesteps_per_iteration': 0, 'export_native_model_files': False, 'logger_creator': None, 'logger_config': None, 'log_level': 'WARN', 'log_sys_usage': True, 'fake_sampler': False, 'seed': None, 'worker_cls': None, '_tf_policy_handles_more_than_one_loss': False, '_disable_preprocessor_api': False, '_disable_action_flattening': False, '_disable_execution_plan_api': True, 'simple_optimizer': -1, 'replay_sequence_length': None, 'lr_schedule': None, 'use_critic': True, 'use_gae': True, 'kl_coeff': 0.2, 'sgd_minibatch_size': 128, 'num_sgd_iter': 20, 'shuffle_sequences': True, 'vf_loss_coeff': 1.0, 'entropy_coeff': 0.0, 'entropy_coeff_schedule': None, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'grad_clip': None, 'kl_target': 0.01, 'vf_share_layers': -1, 'lambda': 1.0, 'input': 'sampler', 'multiagent': {'policies': {'main': <ray.rllib.policy.policy.PolicySpec object at 0x7f98546c6f40>, 'random': <ray.rllib.policy.policy.PolicySpec object at 0x7f98546d30d0>}, 'policy_mapping_fn': <function policy_mapping_fn at 0x7f98537a3160>, 'policies_to_train': [], 'policy_map_capacity': 100, 'policy_map_cache': None, 'count_steps_by': 'env_steps', 'observation_fn': None}, 'callbacks': <class '__main__.SelfPlayCallback'>, 'create_env_on_driver': False, 'custom_eval_function': None, 'framework': 'tf', 'num_cpus_for_driver': 1, 'num_workers': 2}. Error file: /Users/elliottower/ray_results/PPO/PPO_connect_four_e981e_00000_0_2023-02-09_16-51-30/error.txt

### Versions / Dependencies

(result of pip freeze --local)
absl-py==1.4.0
aiosignal==1.3.1
astunparse==1.6.3
attrs==22.2.0
cachetools==5.3.0
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_477u68wvzm/croot/certifi_1671487773341/work/certifi
charset-normalizer==3.0.1
click==8.1.3
cloudpickle==2.2.1
contourpy==1.0.7
cycler==0.11.0
decorator==5.1.1
distlib==0.3.6
dm-tree==0.1.8
filelock==3.9.0
flatbuffers==23.1.21
fonttools==4.38.0
frozenlist==1.3.3
gast==0.4.0
google-auth==2.16.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
gym==0.21.0
gym-notices==0.0.8
gymnasium==0.27.1
gymnasium-notices==0.0.1
h5py==3.8.0
idna==3.4
imageio==2.25.0
importlib-metadata==6.0.0
importlib-resources==5.10.2
jax-jumpy==0.2.0
jsonschema==4.17.3
keras==2.11.0
kiwisolver==1.4.4
libclang==15.0.6.1
lz4==4.3.2
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.2
matplotlib==3.6.3
mdurl==0.1.2
msgpack==1.0.4
networkx==3.0
numpy==1.23.1
oauthlib==3.2.2
open-spiel==1.2
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
PettingZoo==1.15.0
Pillow==9.4.0
pkgutil_resolve_name==1.3.10
platformdirs==2.6.2
protobuf==3.19.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pygame==2.1.2
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
pytz==2022.7.1
PyWavelets==1.4.1
PyYAML==6.0
ray==2.2.0
requests==2.28.2
requests-oauthlib==1.3.1
rich==13.3.1
rsa==4.9
scikit-image==0.19.3
scipy==1.10.0
six==1.16.0
tabulate==0.9.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.30.0
tensorflow-probability==0.19.0
termcolor==2.2.0
tifffile==2023.1.23.1
torch==1.13.1
typer==0.7.0
typing_extensions==4.4.0
urllib3==1.26.14
virtualenv==20.17.1
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.12.0

### Reproduction script

(Copy of self_play_with_open_spiel, with the env creation changed to use ettingzoo rather than openspiel, and PPOConfig multi_agent.policies PolicySpec having extra arguments observation_space and action_space, and being defined to both be RandomPolicy as a starting point to load the environment)

```
"""Example showing how one can implement a simple self-play training workflow.

Uses the open spiel adapter of RLlib with the "connect_four" game and
a multi-agent setup with a "main" policy and n "main_v[x]" policies
(x=version number), which are all at-some-point-frozen copies of
"main". At the very beginning, "main" plays against RandomPolicy.

Checks for the training progress after each training update via a custom
callback. We simply measure the win rate of "main" vs the opponent
("main_v[x]" or RandomPolicy at the beginning) by looking through the
achieved rewards in the episodes in the train batch. If this win rate
reaches some configurable threshold, we add a new policy to
the policy map (a frozen copy of the current "main" one) and change the
policy_mapping_fn to make new matches of "main" vs any of the previous
versions of "main" (including the just added one).

After training for n iterations, a configurable number of episodes can
be played by the user against the "main" agent on the command line.
"""

import argparse
import numpy as np
import os
from pettingzoo.classic import connect_four_v3
import sys

import ray
from ray import air, tune
from ray.rllib.algorithms.callbacks import DefaultCallbacks
from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.examples.policy.random_policy import RandomPolicy
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from ray.rllib.policy.policy import PolicySpec
from ray.tune import CLIReporter, register_env

parser = argparse.ArgumentParser()
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "torch"],
    default="tf",
    help="The DL framework specifier.",
)
parser.add_argument("--num-cpus", type=int, default=0)
parser.add_argument("--num-workers", type=int, default=2)
parser.add_argument(
    "--from-checkpoint",
    type=str,
    default=None,
    help="Full path to a checkpoint file for restoring a previously saved "
    "Algorithm state.",
)
parser.add_argument(
    "--env", type=str, default="connect_four", choices=["connect_four"] # TODO: add other pettingzoo envs?
)
parser.add_argument(
    "--stop-iters", type=int, default=200, help="Number of iterations to train."
)
parser.add_argument(
    "--stop-timesteps", type=int, default=10000000, help="Number of timesteps to train."
)
parser.add_argument(
    "--win-rate-threshold",
    type=float,
    default=0.95,
    help="Win-rate at which we setup another opponent by freezing the "
    "current main policy and playing against a uniform distribution "
    "of previously frozen 'main's from here on.",
)
parser.add_argument(
    "--num-episodes-human-play",
    type=int,
    default=10,
    help="How many episodes to play against the user on the command "
    "line after training has finished.",
)
args = parser.parse_args()


def ask_user_for_action(time_step):
    """Asks the user for a valid action on the command line and returns it.

    Re-queries the user until she picks a valid one.

    Args:
        time_step: The open spiel Environment time-step object.
    """
    pid = time_step.observations["current_player"]
    legal_moves = time_step.observations["legal_actions"][pid]
    choice = -1
    while choice not in legal_moves:
        print("Choose an action from {}:".format(legal_moves))
        sys.stdout.flush()
        choice_str = input()
        try:
            choice = int(choice_str)
        except ValueError:
            continue
    return choice


class SelfPlayCallback(DefaultCallbacks):
    def __init__(self):
        super().__init__()
        # 0=RandomPolicy, 1=1st main policy snapshot,
        # 2=2nd main policy snapshot, etc..
        self.current_opponent = 0

    def on_train_result(self, *, algorithm, result, **kwargs):
        # Get the win rate for the train batch.
        # Note that normally, one should set up a proper evaluation config,
        # such that evaluation always happens on the already updated policy,
        # instead of on the already used train_batch.
        main_rew = result["hist_stats"].pop("policy_main_reward")
        opponent_rew = list(result["hist_stats"].values())[0]
        assert len(main_rew) == len(opponent_rew)
        won = 0
        for r_main, r_opponent in zip(main_rew, opponent_rew):
            if r_main > r_opponent:
                won += 1
        win_rate = won / len(main_rew)
        result["win_rate"] = win_rate
        print(f"Iter={algorithm.iteration} win-rate={win_rate} -> ", end="")
        # If win rate is good -> Snapshot current policy and play against
        # it next, keeping the snapshot fixed and only improving the "main"
        # policy.
        if win_rate > args.win_rate_threshold:
            self.current_opponent += 1
            new_pol_id = f"main_v{self.current_opponent}"
            print(f"adding new opponent to the mix ({new_pol_id}).")

            # Re-define the mapping function, such that "main" is forced
            # to play against any of the previously played policies
            # (excluding "random").
            def policy_mapping_fn(agent_id, episode, worker, **kwargs):
                # agent_id = [0|1] -> policy depends on episode ID
                # This way, we make sure that both policies sometimes play
                # (start player) and sometimes agent1 (player to move 2nd).
                return (
                    "main"
                    if episode.episode_id % 2 == agent_id
                    else "main_v{}".format(
                        np.random.choice(list(range(1, self.current_opponent + 1)))
                    )
                )

            new_policy = algorithm.add_policy(
                policy_id=new_pol_id,
                policy_cls=type(algorithm.get_policy("main")),
                policy_mapping_fn=policy_mapping_fn,
            )

            # Set the weights of the new policy to the main policy.
            # We'll keep training the main policy, whereas `new_pol_id` will
            # remain fixed.
            main_state = algorithm.get_policy("main").get_state()
            new_policy.set_state(main_state)
            # We need to sync the just copied local weights (from main policy)
            # to all the remote workers as well.
            algorithm.workers.sync_weights()
        else:
            print("not good enough; will keep learning ...")

        # +2 = main + random
        result["league_size"] = self.current_opponent + 2


if __name__ == "__main__":
    ray.init(num_cpus=args.num_cpus or None, include_dashboard=False)

    # Way from rock_paper_scissors_multiagent.py
    # register_env("connect_four", lambda _: PettingZooEnv(connect_four_v3.env()))

    # Way from multi_agent_independent_learning.py
    def env_creator(args):
        return PettingZooEnv(connect_four_v3.env())

    env = env_creator({})
    register_env("connect_four", env_creator)

    def policy_mapping_fn(agent_id, episode, worker, **kwargs):
        # agent_id = [0|1] -> policy depends on episode ID
        # This way, we make sure that both policies sometimes play agent0
        # (start player) and sometimes agent1 (player to move 2nd).
        return "main" if episode.episode_id % 2 == agent_id else "random"

    config = (
        PPOConfig()
        .environment("connect_four")
        .framework(args.framework)
        .callbacks(SelfPlayCallback)
        .rollouts(num_envs_per_worker=5, num_rollout_workers=args.num_workers)
        .training(num_sgd_iter=20, model={"fcnet_hiddens": [512, 512]})
        .multi_agent(
            # Initial policy map: Random and PPO. This will be expanded
            # to more policy snapshots taken from "main" against which "main"
            # will then play (instead of "random"). This is done in the
            # custom callback defined above (`SelfPlayCallback`).
            policies={
                # Our main policy, we'd like to optimize.
                "main": PolicySpec(observation_space=env.observation_space["observation"], action_space=env.observation_space["action_mask"], policy_class=RandomPolicy),
                # An initial random opponent to play against.
                "random": PolicySpec(observation_space=env.observation_space["observation"], action_space=env.observation_space["action_mask"], policy_class=RandomPolicy),
            },
            # Assign agent 0 and 1 randomly to the "main" policy or
            # to the opponent ("random" at first). Make sure (via episode_id)
            # that "main" always plays against "random" (and not against
            # another "main").
            policy_mapping_fn=policy_mapping_fn,
            # Always just train the "main" policy.
            policies_to_train=[],
        )
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    stop = {
        "timesteps_total": args.stop_timesteps,
        "training_iteration": args.stop_iters,
    }

    # Train the "main" policy to play really well using self-play.
    results = None
    if not args.from_checkpoint:
        results = tune.Tuner(
            "PPO",
            param_space=config,
            run_config=air.RunConfig(
                stop=stop,
                verbose=2,
                progress_reporter=CLIReporter(
                    metric_columns={
                        "training_iteration": "iter",
                        "time_total_s": "time_total_s",
                        "timesteps_total": "ts",
                        "episodes_this_iter": "train_episodes",
                        "policy_reward_mean/main": "reward",
                        "win_rate": "win_rate",
                        "league_size": "league_size",
                    },
                    sort_by_metric=True,
                ),
                checkpoint_config=air.CheckpointConfig(
                    checkpoint_at_end=True,
                    checkpoint_frequency=10,
                ),
            ),
        ).fit()

    # Restore trained trainer (set to non-explore behavior) and play against
    # human on command line.
    if args.num_episodes_human_play > 0:
        num_episodes = 0
        config.explore = False
        algo = config.build()
        if args.from_checkpoint:
            algo.restore(args.from_checkpoint)
        else:
            checkpoint = results.get_best_result().checkpoint
            if not checkpoint:
                raise ValueError("No last checkpoint found in results!")
            algo.restore(checkpoint)

        # Play from the command line against the trained agent
        # in an actual (non-RLlib-wrapped) open-spiel env.
        human_player = 1
        env = connect_four_v3.env()

        while num_episodes < args.num_episodes_human_play:
            print("You play as {}".format("o" if human_player else "x"))
            time_step = env.reset()
            while not time_step.last():
                player_id = time_step.observations["current_player"]
                if player_id == human_player:
                    action = ask_user_for_action(time_step)
                else:
                    obs = np.array(time_step.observations["info_state"][player_id])
                    action = algo.compute_single_action(obs, policy_id="main")
                    # In case computer chooses an invalid action, pick a
                    # random one.
                    legal = time_step.observations["legal_actions"][player_id]
                    if action not in legal:
                        action = np.random.choice(legal)
                time_step = env.step([action])
                print(f"\n{env.get_state}")

            print(f"\n{env.get_state}")

            print("End of game!")
            if time_step.rewards[human_player] > 0:
                print("You win")
            elif time_step.rewards[human_player] < 0:
                print("You lose")
            else:
                print("Draw")
            # Switch order of players
            human_player = 1 - human_player

            num_episodes += 1

        algo.stop()

    ray.shutdown()

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @elliottower ,

Regarding the convolution layers, we do provide some default configurations but can not cover all observations spaces.
Regarding the error: When executing this with a newer version of Ray, you get an error that is more specific:
```
[...]
(PPO pid=42653) Entire first structure:
(PPO pid=42653) {'observation': ., 'action_mask': .}
(PPO pid=42653) Entire second structure:
(PPO pid=42653) .
[...]
```

In your multi-agent policy configuration dict, you specify
`PolicySpec(observation_space=env.observation_space["observation"]`
That is not the observation space. The observation space includes the action mask.
Furthermore, the action space is not the action mask, but you specify `action_space=env.observation_space["action_mask"]`.

You will have to specify the observation and action space of the environment here.
Please let us know if this works for you.

**Comment by elliottower** [comment]
Thanks for the help, makes sense that the observation space would include the action mask. 

Upon further inspection it looks like the `OpenSpielEnv` method used in ``self_play_with_open_spiel.py`` flattens the observation space, is this a common practice? It looks like the `PettingZooEnv` function doesn't flatten observations by default and I can't find an option to, so I am trying to use supersuit to flatten the observation in the `env_creator` call but it's giving me some issues as it seems `ss.flatten_v0` doesn't expect a dict. Is there a better way to do this? (error message below)

I'm currently working on making a FlattenedEnv wrapper to manually flatten the observation, but it doesn't seem the cleanest way of doing things and I think using supersuit or some built in wrapper would be more ideal. 

For my personal project I've also made the wrapper convert the gymnasium.spaces objects to gym.spaces to make it compatible, but I am unsure if this will result in other issues down the line. Maybe there are more elegant ways to get around this? 

When you say newer versions do you mean to use the most up to date main? In a previous issue (#32206) I was told to instead use ray 2.2.0 in order for it to work. As a side question, is there any estimated timeline for gymnasium support with RLlib? I see PR #31960 was merged and seems to have some sort of gymnasium support, but not sure if this means full support or not.

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 37, in flatten_v0
    return basic_obs_wrapper(env, basic_transforms.flatten, True)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 20, in basic_obs_wrapper
    return observation_lambda_v0(env, change_obs, change_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/wrapper_chooser.py", line 24, in __call__
    return self.aec_wrapper(env, *args, **kwargs)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/lambda_wrappers/observation_lambda.py", line 30, in __init__
    self.observation_space(agent)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/lambda_wrappers/observation_lambda.py", line 61, in observation_space
    return self.change_obs_space_fn(old_obs_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 14, in change_space
    space = module.change_obs_space(space, param)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/basic_transforms/flatten.py", line 11, in change_obs_space
    return convert_box(lambda obs: change_observation(obs, obs_space, param), obs_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/basic_transforms/__init__.py", line 5, in convert_box
    new_low = convert_obs_fn(old_box.low)
AttributeError: 'Dict' object has no attribute 'low'
(raylet) [2023-02-12 15:41:08,872 E 8517 7509295] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-02-12_15-40-35_799762_8502 is over 95% full, available space: 16877006848; capacity: 401000603648. Object creation will fail if spilling is required.
(raylet) [2023-02-12 15:41:18,927 E 8517 7509295] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-02-12_15-40-35_799762_8502 is over 95% full, available space: 16876732416; capacity: 401000603648. Object creation will fail if spilling is required.
(raylet) [2023-02-12 15:41:28,988 E 8517 7509295] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-02-12_15-40-35_799762_8502 is over 95% full, available space: 16876740608; capacity: 401000603648. Object creation will fail if spilling is required.
(raylet) [2023-02-12 15:41:39,042 E 8517 7509295] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-02-12_15-40-35_799762_8502 is over 95% full, available space: 16877281280; capacity: 401000603648. Object creation will fail if spilling is required.
(raylet) [2023-02-12 15:41:49,105 E 8517 7509295] (raylet) file_system_monitor.cc:105: /tmp/ray/session_2023-02-12_15-40-35_799762_8502 is over 95% full, available space: 16877613056; capacity: 401000603648. Object creation will fail if spilling is required.
a = ss.generic_wrappers.flatten_v0(env.unwrapped)
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 37, in flatten_v0
    return basic_obs_wrapper(env, basic_transforms.flatten, True)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 20, in basic_obs_wrapper
    return observation_lambda_v0(env, change_obs, change_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/wrapper_chooser.py", line 24, in __call__
    return self.aec_wrapper(env, *args, **kwargs)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/lambda_wrappers/observation_lambda.py", line 30, in __init__
    self.observation_space(agent)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/lambda_wrappers/observation_lambda.py", line 61, in observation_space
    return self.change_obs_space_fn(old_obs_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/generic_wrappers/basic_wrappers.py", line 14, in change_space
    space = module.change_obs_space(space, param)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/basic_transforms/flatten.py", line 11, in change_obs_space
    return convert_box(lambda obs: change_observation(obs, obs_space, param), obs_space)
  File "/Users/elliottower/anaconda3/envs/ray/lib/python3.8/site-packages/supersuit/utils/basic_transforms/__init__.py", line 5, in convert_box
    new_low = convert_obs_fn(old_box.low)
AttributeError: 'Dict' object has no attribute 'low'
```

**Comment by elliottower** [comment]
Edit: figured out supersuit's lambda observation wrapper can be used for exactly this purpose. Have things up and running now.

**Comment by george-skal** [comment]
Hi @elliottower ,

I want to use connect four from classic of pettingzoo and when I use flatten_v0 I get AttributeError: 'Dict' object has no attribute 'low' as well.
I found the lambda observation wrapper, but no documentation on how to use it, so I get some errors.
Can you explain me what you did, or how to use it to flatten the observations?

Many thanks,
George

**Comment by elliottower** [comment]
> Hi @elliottower ,
> 
> I want to use connect four from classic of pettingzoo and when I use flatten_v0 I get AttributeError: 'Dict' object has no attribute 'low' as well. I found the lambda observation wrapper, but no documentation on how to use it, so I get some errors. Can you explain me what you did, or how to use it to flatten the observations?
> 
> Many thanks, George

Connect four and all pettingzoo classic games have their action mask encoded in the observation as well, making it a dict rather than a box/discrete/space that has .low property. I’d have to see your code but I would guess you can index into the observation space with the key “observation” and that would fix it.

**Comment by elliottower** [comment]
But for better feedback post on the farama discord channel, in the #pettingzoo channel. I haven’t used SuperSuit extensively so can’t be 100% sure. The link is on the pettingzoo repo. 

For reference with connect four though you can also see my PR which was created based on this issue. I haven’t had time to update it or get it merged but it may be of use as a reference.

**Comment by george-skal** [comment]
Hi @elliottower ,

thanks I will post there.
I thought you used a ready lampda wrapper from supersuit. Can you tell exactly ehich PR should I look at?
Thanks.

**Comment by elliottower** [comment]
https://github.com/ray-project/ray/pull/34696
