### ISSUE TITLE
[docs] Google search for Ray dashboard returns docs from 1.11.0

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#32381]
### Description

Not sure if we can fix this but the top search result for Ray Dashboard is a doc from 1.11.0: https://www.google.com/search?q=ray+dashboard&oq=ray+dashboard&aqs=chrome..69i57j0i512l9.8195j0j7&sourceid=chrome&ie=UTF-8

**Comment by maxpumperla** [comment]
@angelinalg we recently touched up the `robots.txt` and should, in the near future, only see crawler / search engine results from latest or master. In other words, this hopefully resolves itself over time.

Would be great if you could keep an eye on that, and maybe even help set up a document with problematic google queries like this one.

**Comment by angelinalg** [comment]
I tried the search again and it is now pointing to 2.3.0 docs. Closing this as fixed.
