### ISSUE TITLE
[air] unnecessary ser/deser of Checkpoint when shipping it using object store 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32385]
### What happened + What you expected to happen

Currently we have unnecessary ser/deser of Checkpoint when shipping it across object store for batch prediction.

For example, for `Checkpoint.from_uri`, instead of only putting uri_path into object store and have every actor work with it, we put all data into object store.

The same issue for EFS backed setup. The fact that checkpoint uses `local_path` representation does not necessarily mean that it needs to be serialized entirely. 

We should in general design Checkpoint in a way that supports EFS regime and uri (both of which are our most targeting scenarios) effectively. 

Moreover, the current Checkpoint class is pretty cumbersome to work with. See such an example here: https://github.com/ray-project/ray/pull/32386

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
cc @krfricke @gjoliver @matthewdeng

**Comment by Yard1** [comment]
I think it may actually work without involving object store for `from_uri`

**Comment by Yard1** [comment]
This also applies to training (from Train worker to Tune Trainable). Furthermore, in the case of Train, we receive checkpoints from all ranks, but only actually use rank 0.

**Comment by anyscalesam** [comment]
@matthewdeng have we addressed this as part of the new checkpoint implementation as part of ray27?

**Comment by matthewdeng** [comment]
Yes this is fixed in the new checkpoint implementation
