### ISSUE TITLE
[CI] [core] `stress_test_state_api` release test is flaky and has error message that looks like real failure

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32416]
This test failed twice during the 2.3 release process; we should deflake, or improve the error message so that it doesn't look like a release blocking failure.

* https://github.com/ray-project/ray/issues/32005
* https://github.com/ray-project/ray/issues/32415

**Comment by cadedaniel** [comment]
cc @rickyyx

**Comment by scv119** [comment]
this is done? @rickyyx
