### ISSUE TITLE
CUDA cannot see >1 GPU from multi-GPU tasks after running single-GPU tasks

### ISSUE THREAD

**Issue by npyoung** [ray-project/ray#3245]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04 Deep Learning AMI
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6
- **Exact command to reproduce**:

```python
import ray
ray.init(use_raylet=True)

n = 1
N = 4

@ray.remote(num_gpus=n)
def few_gpu_work():
    import pycuda.driver as cuda
    cuda.init()
    return cuda.Device.count()
    
@ray.remote(num_gpus=N)
def many_gpu_work():
    import pycuda.driver as cuda
    cuda.init()
    return cuda.Device.count()
    
# Test many_gpu function
n_dev = ray.get([many_gpu_work.remote()])
print("{:d} devices found".format(n_dev[0])) # finds 4 devices

# Do some single gpu work
# make use of every GPU
n_dev = ray.get([few_gpu_work.remote() for _ in range(4)])
for nd in n_dev:
    print("{:d} devices found".format(nd))
# first response above finds 4 devices
# subsequent three each find only 1 device

# Now test the many_gpu function again
n_dev = ray.get([many_gpu_work.remote()])
print("{:d} devices found".format(n_dev[0])) # finds 1 device this time!
```

### Describe the problem
After tasks requesting a small number of GPUs (`n`) are run, subsequent tasks requiring more GPUs (`N`) can only see `n` GPUs.

Similar to #3198, if you print the value of `CUDA_VISIBLE_DEVICES` inside the remote functions, you do get a list of the appropriate length. It seems like calling `pycuda.driver.Device.count()` directly invokes a method in the CUDA C++ library.

**Comment by robertnishihara** [comment]
Setting `max_calls=1` in the remote decorator should fix the issue.

Sounds like `pycuda` is not cleaning up after itself, so we can just kill the worker instead.

See https://github.com/ray-project/ray/issues/616 for another example.

**Comment by richardliaw** [comment]
Closing this for now as `max_calls` seems to be a workable fix.
