### ISSUE TITLE
[release] job_runner didn't submit job successfully but the error shows up as application error 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32468]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1390#01863d6f-fab1-47d6-b84f-1b44326e9fcf

cluster: https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_jandxcdzfrrs6xrqilf9b9aqek?command-history-section=runtime_env_log&drivers-section=runs

There is no log showing up in interactive session. 

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
cc @krfricke @Yard1 

```


Traceback (most recent call last):
--
  | File "/tmp/release-L9lFxomu4C/release/ray_release/glue.py", line 313, in run_release_test
  | command, env=command_env, timeout=command_timeout
  | File "/tmp/release-L9lFxomu4C/release/ray_release/command_runner/job_runner.py", line 119, in run_command
  | raise CommandError(f"Command returned non-success status: {status_code}")
  | ray_release.exception.CommandError: Command returned non-success status: -1

```

**Comment by Yard1** [comment]
I don't think it's worth working on this as we'll move to Anyscale Jobs soon anyway.

**Comment by xwjiang2010** [comment]
> 

The same for using Anyscale job API. We should make sure that job submission error is captured as it is.

**Comment by Yard1** [comment]
It should already be captured in the Anyscale Job runner I am working on

**Comment by xwjiang2010** [comment]
ok sounds good!
