### ISSUE TITLE
[Serve|Metrics] Metric instantiation blocks forever (only in Ci/Cd deployments)

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#32472]
### What happened + What you expected to happen

We use github actions to do Ci/Cd. When trying to create a Serve deployment with metrics, it blocks.

## What is happening

The deployment is never started up, and continues to block. Removing `self.metric = Gauge('foo', description="bar", tag_keys=('baz',))` everything works.

Then this message is repeatedly printed out every 1.5 seconds:

 `(raylet) [2023-02-11 22:51:40,030 I 3951 3951] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1`

However, when we deploy the same exact code on another computer, e.g. dev's local machines, there is no problem.

## What we expect

The metrics should instantiate properly all the time. There should be no difference between machines.

### Versions / Dependencies

ray 2.2.0
python 3.10.8

### Reproduction script

We start up a single node ray using this command.

```bash
ray start --head --port=6379 --redis-shard-ports=6380,6381 --object-manager-port=22345 --node-manager-port=22346 --dashboard-host=0.0.0.0
```

```python
  @serve.deployment(route_prefix=None, name="metrics")
  class Metrics:
      def __init__(self):
          self.metric = Gauge('foo', description="bar", tag_keys=('baz',))
  
  
  if __name__ == "__main__":
      asyncio.set_event_loop(asyncio.new_event_loop())
      if not ray.is_initialized:
          raise RuntimeError("Ray must be initialised first.")
  
      ray.init(address='auto')
      serve.start(detached=True, http_options={"host": host, "port": port})
  
      Metrics.options(num_replicas=1, ray_actor_options={"num_cpus": 0}).deploy()
```
### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
@Joshuaalbert could you give more details about what machine this failed versus succeeded on? What were the operating systems? Does it always fail on a particular machine?

**Comment by Joshuaalbert** [comment]
This is a github action running on `ubuntu-latest`

**Comment by Joshuaalbert** [comment]
I'm trying to create a minimal example now

**Comment by Joshuaalbert** [comment]
Discovered that there was this error in logs that was hidden due to the way we run our Ray programs. So the deployment wasn't running and tests were failing because the deployment didn't run.

```bash
(ServeController pid=2663)     self.relative_h_time_offset = Histogram('relative_h_time_offset',
(ServeController pid=2663)   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/ray/util/metrics.py", line 252, in __init__
(ServeController pid=2663)     raise ValueError(
(ServeController pid=2663) ValueError: Invalid `boundaries` argument at index 0, [-1.0, 1.0]. Use positive values for the arguments.
```

I had not seen that prometheus only allows strictly positive observations in histograms. https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations

P.s. if someone from Serve team would be willing to have a call with us to understand our usage of Ray, that would be good. We were discussing at the Summit about going to Anyscale, however our decision was to first ensure that we can get things fully operating with pure open source support before moving further. We think we have a relevant case that you'll see more cases like ours in the near future given the popularity of conversational models like chatgpt.
