### ISSUE TITLE
webui bokeh error

### ISSUE THREAD

**Issue by radugrosu** [ray-project/ray#3248]
### System information
- **OS Platform and Distribution: Ubuntu 17.04**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3 (latest wheels)
- **Python version**: 3.6.6
- **Exact command to reproduce**: Run `ray.init()`, open the webui notebook and run the cell with `ui.task_completion_time_distribution()`

### Describe the problem
```
 BokehJS 1.0.1 successfully loaded.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b2a48ce2af48> in <module>
----> 1 ui.task_completion_time_distribution()

~/bin/anaconda3/lib/python3.6/site-packages/ray/experimental/ui.py in task_completion_time_distribution()
    440             plot_width=500,
    441             plot_height=500,
--> 442             toolbar_location="below"),
    443         notebook_handle=True)
    444 

~/bin/anaconda3/lib/python3.6/site-packages/bokeh/layouts.py in gridplot(children, sizing_mode, toolbar_location, ncols, plot_width, plot_height, toolbar_options, merge_tools)
    302     children = _handle_children(children=children)
    303     if ncols:
--> 304         if any(isinstance(child, list) for child in children):
    305             raise ValueError("Cannot provide a nested list when using ncols")
    306         children = list(_chunks(children, ncols))

TypeError: 'Figure' object is not iterable
```

This appears to have persisted through several ray and bokeh version upgrades.

**Comment by mattearllongshot** [comment]
It looks like some of the underlying interface may have changed? `_truncated_task_profiles` is just returning an empty list for me which seems to be used by most of the commands.  It'd be good to see this working again though as it looks like a great tool for diagnosing performance issues.

**Comment by Deepak3994** [comment]
@radugrosu 

Did you got the solution for you question?

**Comment by robertnishihara** [comment]
@Deepak3994 @radugrosu I'm closing this issue because the underlying UI is changing. As of https://github.com/ray-project/ray/pull/4066 we've moved away from the Jupyter notebook approach and toward a more dynamic UI. It's still very experimental and provides limited information, but that will change.
