### ISSUE TITLE
[Serve] annotation for tag_keys is wrong

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#32494]
### What happened + What you expected to happen

The annotation for metric tag_keys is `tag_keys: Optional[Tuple[str]] = None`, however you want that to be `tag_keys: Optional[Tuple[str, ...]] = None` to indicate that it's not a 1-tuple, but rather a variable length tuple where all the elements are str.

### Versions / Dependencies

ray 2.2

### Reproduction script

N/A

### Issue Severity

Low: It annoys or frustrates me.

**Comment by hora-anyscale** [comment]
@Joshuaalbert - can you please clarify the metric you are referring to?

**Comment by Joshuaalbert** [comment]
No problem, here's a screenshot of the issue in particular. It is picked up by the IDE. Just change `tag_keys: Optional[Tuple[str]]` -> `tag_keys: Optional[Tuple[str, ...]]`

![Screenshot from 2023-02-17 16-34-38](https://user-images.githubusercontent.com/14807032/219798161-61afc190-cbd3-42a2-b2b6-50b49672de64.png)

**Comment by anyscalesam** [comment]
@Joshuaalbert  can you open a PR; we'll shepherd this through.

**Comment by Joshuaalbert** [comment]
fixed
