### ISSUE TITLE
Ray hangs when using unpickle-able cython enum

### ISSUE THREAD

**Issue by radugrosu** [ray-project/ray#3249]
### System information
- **OS Platform and Distribution: Ubuntu 16.04 and 17.04**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3 (latest wheels)
- **Python version**: 3.6.6
- **Exact command to reproduce**: See below.

### Describe the problem

The following code fails (possibly expectedly) with an `AttributeError: 'dict' object has no attribute '_member_names'`.
```
from enum import Enum
import ray

ray.init()

@ray.remote
class C:
    def __init__(self, a = 1):
        self.a = a
        
    def update(self, a):
        self.a += a.value
        
    def run(self):
        return self.a
    
class D(Enum):
    a = 5

actor = C.remote(0)
actor.update.remote(D.a)
ray.get(actor.run.remote())
```

This alerts the user of the problem, and they can take the necessary steps to work around it.

If the enum used is a **cython** enum, however, ray just hangs, giving absolutely no indication of what the problem could be (The code below is just for illustration and reproducibility, but the issue happens irrespective of where the cython enum is being defined). 
```
%%cython
cpdef enum D:
    a = 5
```

The log files in `/tmp/ray/session*/logs` also contain no clue. Could you be so kind and provide a hint of how to go about debugging / figuring out such issues in the future? Thanks!

**Comment by richardliaw** [comment]
This works now.
