### ISSUE TITLE
Ray not handling heartbeat dropping

### ISSUE THREAD

**Issue by chrisorm** [ray-project/ray#3251]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 17.04
- **Ray installed from (source or binary)**: Source - Latest build (from s3)
- **Ray version**:Latest build (from s3)
- **Python version**: 3.6.5

### Describe the problem
We are running a large cluster on AWS EC2 instances. We find from time to time we experience outages or problems with one of the AWS instances in the cluster. When this happens, Ray crashes with an error about the heartbeat timing out. 

Other than simply catching this problem, and essentially handling scheduling/recovery ourselves, is there any way to ensure that Ray does the expect thing of restarting that work on available nodes? 

Thanks for your help in advance!

**Comment by ericl** [comment]
The autoscaler is supposed to do this automatically -- are you able to use that to manage your cluster?

**Comment by mattearllongshot** [comment]
Hi, I've just tried configuring our cluster (otherwise using the same code and performing the same test as @chrisorm) and I still see the heartbeat issue.  Symptoms are that we get the following text on stderr after trying to `ray.get` the result of our actors:
```
The node with client ID cce8c1b64f90b4356f87ed2c10bcdacae6367d3d has been marked dead because the monitor has missed too many heartbeats from it.
```
...repeating (but with a different ID), and we concurrently get:

```
---------------------------------------------------------------------------
RayGetError                               Traceback (most recent call last)
<timed exec> in <module>

~/conda/envs/venv/lib/python3.6/site-packages/ray/worker.py in get(object_ids, worker)
   2347             for i, value in enumerate(values):
   2348                 if isinstance(value, RayTaskError):
-> 2349                     raise RayGetError(object_ids[i], value)
   2350             return values
   2351         else:

RayGetError: Could not get objectid ObjectID(01000000ddbef6f9d4e92ddfa91c638e76809238). It was created by remote function <unknown> which failed with:

Remote function <unknown> failed with:

Invalid return value: likely worker died or was killed while executing the task; check previous logs or dmesg for errors.
```
While this is happening workers on the head still run (eating up lots of CPU), but there's no way to recover the results because the `ray.get` call has already raised.

**Comment by mattearllongshot** [comment]
Note that one of the nodes dies (not sure why).  The auto-scaler does bring up a replacement but we still can't recover the partial job, plus we're not sure what's causing the node to become unreachable in the first place.  Do you have any ideas?

**Comment by ericl** [comment]
You mean you're seeing the VM become unreachable? That could be because of running out of memory.

> Invalid return value: likely worker died or was killed while executing the task; check previous logs or dmesg for errors.
Any way to get the logs on that node? (in /tmp/ray, and dmesg) note that some extra debug info has been merged recently so using latest might help.

**Comment by richardliaw** [comment]
Closing because stale.
