### ISSUE TITLE
[AIR] `Trainer` references don't show useful signature

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#32522]
### Description

<img width="768" alt="image" src="https://user-images.githubusercontent.com/26107013/218667684-4de0da86-4c2e-4e1b-b4b9-86810874b5c7.png">

### Link

https://docs.ray.io/en/latest/ray-air/package-ref.html#tensorflow

**Comment by matthewdeng** [comment]
Closing this one as duplicate of https://github.com/ray-project/ray/issues/33429 (which has more info).
