### ISSUE TITLE
[Data] DatasetPipeline.to_tf() fails due to mismatch in input arguments to Dataset.to.tf()

### ISSUE THREAD

**Issue by jharaldson** [ray-project/ray#32529]
### What happened + What you expected to happen

DatasetPipeline.to_tf() is broken in Ray 2.2.0, parameters needs to be alligned with Dataset.to_tf()
The following two inputs are required, but deviates from the input to Dataset.to_tf():
1. output_signature - Dataset.to_tf() does not take this variable as input
2. label_column - Dataset.to_tf() takes a plural of this variable: **label_columns** and accepts a list as well.

Seems this is not an issue in Ray 2.3.0 as we are now working with dataset iterators instead of data pipelines. 

### Versions / Dependencies

Ray 2.2.0

### Reproduction script

Can provide a script if necessary, but the issue is quite obvious.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by amogkam** [comment]
Hey @jharaldson-- yes this is a good callout! This should be fixed by #32531. But as you pointed out, in 2.3, the `DatasetIterator` API is already the same as `Dataset.to_tf`.
