### ISSUE TITLE
[Data] Guide on moving from Torch DataLoader to Ray Datasets

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#32547]
This request has come up multiple times.

Have a migration guide moving from PyTorch Dataloaders to Ray Datasets

**Comment by c21** [comment]
+1, IMO this is valuable and we should do it.

**Comment by kellyyke** [comment]
+1, this would definitely be helpful

**Comment by amogkam** [comment]
Didn't realize there was a duplicate: #31418

Let's consolidate discussion in #31418. Closing this issue.
