### ISSUE TITLE
[Ray 2.3 Release] Validate `xgboost_ray`, `lightgbm_ray` work on latest Ray release

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32549]
Specifically, test this on the product. We changed a patch version in the ML images after product began validation.

https://github.com/ray-project/ray/pull/32514/files#diff-bf0fa076f1cffbbd5cb3443b209890b0bb0f2c733925eb2d5a105123214a117aR7-R8

**Comment by Yard1** [comment]
I can confirm this works on the 2.3 ML image.
