### ISSUE TITLE
[AIR] Result.checkpoint get deleted based on `checkpoint_score_attribute `

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#32545]
### What happened + What you expected to happen

```python
checkpoint_config = CheckpointConfig(num_to_keep=1, checkpoint_score_attribute="acc", checkpoint_score_order="max")

run_config = RunConfig(
    name="resnet-finetune",
    local_dir="/tmp/ray_results",
    sync_config=SyncConfig(),
    checkpoint_config=checkpoint_config
)
...

result = Trainer.fit()
print(result.checkpoint)
>>> None
```

I was trying to use default sync logic with local storage + `checkpoint_score_attribute`. Only the checkpoint with best score will be saved to the head node, and all the others will be removed. However, the `result.checkpoint` still holds the path to the latest checkpoint, which has been deleted already.

### Versions / Dependencies

Ray 2.2

### Reproduction script

```python
checkpoint_config = CheckpointConfig(num_to_keep=1, checkpoint_score_attribute="acc", checkpoint_score_order="max")

run_config = RunConfig(
    name="resnet-finetune",
    local_dir="/tmp/ray_results",
    sync_config=SyncConfig(),
    checkpoint_config=checkpoint_config
)
...

result = Trainer.fit()
print(result.checkpoint)
>>> None
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@woshiyyya @justinvyu this still relevant in latest implementation of checkpointing as part of AI Libraries GA?

**Comment by justinvyu** [comment]
This should no longer be an issue -- the new checkpoint manager has a unit test that checks this specific issue.
