### ISSUE TITLE
[RLlib] SAC algorithm fails when used with pytorch for discrete actions

### ISSUE THREAD

**Issue by rajfly** [ray-project/ray#32567]
### What happened + What you expected to happen

When running the SAC algorithm on cartpole env grid searching over tf2 and torch frameworks (following the tuned example [here](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/sac/cartpole-sac.yaml)), torch seems to fail while tf2 seems to work. Both torch and tf2 has the same hyperparameters and thus, there seems to be a bug with the torch implementation. The training graph is shown below where torch is the grey line and tf2 is the blue line. When run with the pendulum env, they seem to have similar performance and thus I suspect the bug is with regards to discrete environments.

<img width="508" alt="Screenshot 2023-02-15 at 9 43 47 PM" src="https://user-images.githubusercontent.com/35727146/219045277-7676f78d-e52f-4c9f-a40c-68086627b547.png">

### Versions / Dependencies

Ray 2.2.0
Gym 0.23.1
Python 3.9
Ubuntu

### Reproduction script

```python
# set visible gpus
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1,2"

import ray
from ray import air, tune
from ray.rllib.algorithms.sac.sac import SACConfig

rllib_config = SACConfig()\
    .framework(framework=tune.grid_search(['torch', 'tf2']), eager_tracing=True)\
    .environment(env='CartPole-v1', render_env=False,)\
    .resources(num_gpus=1)\
    .debugging(seed=0)\
    .training(
        gamma=0.95,
        target_network_update_freq=32,
        tau=1.0,
        train_batch_size=32,
        optimization_config={'actor_learning_rate': 0.005, 'critic_learning_rate': 0.005, 'entropy_learning_rate': 0.0001},
        )\

air_config = air.RunConfig(
    name='SAC',
    stop={'timesteps_total': 10000000},
    checkpoint_config=air.CheckpointConfig(
        checkpoint_at_end=True
    ),
    local_dir='~/Projects/rl-diff-test/results',
    log_to_file=True,
)

tuner = tune.Tuner(
    'SAC',
    param_space=rllib_config,
    run_config=air_config,
)

ray.init()
tuner.fit()
ray.shutdown()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by avnishn** [comment]
I'm not sure if this is a bug. SAC does not work well typically on discrete action spaces. 

If you want an algorithm that works will on discrete action spaces I'd pick instead from appo/dqn/apex

**Comment by avnishn** [comment]
Can we instead open a post on discuss.ray.io? I'm happy to discuss this more over there.

**Comment by rajfly** [comment]
> Can we instead open a post on discuss.ray.io? I'm happy to discuss this more over there.

Hi @avnishn, sure I've created a post [here](https://discuss.ray.io/t/sac-algorithm-fails-when-used-with-pytorch-for-discrete-actions/9420?u=rajfly). Good point but I still think its a bug related to the frameworks since one framework is able to do well while the other fails.

**Comment by christianjcc** [comment]
Issue ever resolved?
