### ISSUE TITLE
WebUI might not be terminated correctly in some situations

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3256]
Even after ray stop, in some situations the WebUI server seems to not be terminated and therefore the log files cannot be deleted:

```
jupyter-n 26532 ubuntu  cwd    DIR   0,72     4096 4160775699 ../ray_logs
jupyter-n 26532 ubuntu    1w   REG   0,72        0 4161271123 ../ray_logs/logs/webui.out
jupyter-n 26532 ubuntu    2w   REG   0,72      418 4161271124 ../ray_logs/logs/webui.err
```

**Comment by robertnishihara** [comment]
Closing because the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
