### ISSUE TITLE
[CI] `linux://doc:source/ray-core/doc_code/actor_checkpointing` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#32589]
- 0202379cae125860a46bdb2b80e5023bd81dba76 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2350#018652c2-f1a8-42d0-a4ef-62fe9cb4e7ae)
- 4ffa7fd87fc0e63aaf7e75a3154778fccb394f08 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2315#01864c2b-a467-4bb2-997f-23bc75c4df17)
- 2e9b83423b39431090d5a653d272f413a010e523 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2312#01864bbd-f6d3-4836-a55c-9cb7d005e500)
- b4ad23a6051862ace309c2009fb66f9166ed3b7a FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2258#018638c9-e195-4734-9b66-dd6fcbda164a)
- 188c4115eaa7827b60e0770aa4230fe53882977b FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2253#01863858-4aeb-4b71-972c-a9c32d107f12)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc:source/ray-core/doc_code/actor_checkpointing-END
....

**Comment by jjyao** [comment]
I think it's fixed by #32829
