### ISSUE TITLE
[dashboard] Logs button shows for dead nodes but doesn't work

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#32593]
Repro: start multi-node cluster, kill node.

<img width="1418" alt="Screen Shot 2023-02-15 at 5 48 58 PM" src="https://user-images.githubusercontent.com/9871461/219220925-f22a8e69-2aec-4486-ae5d-6d90bccafe9f.png">

**Comment by rkooo567** [comment]
We don't support accessing logs from dead nodes. I guess we can just remove the button or add a tooltip to explain it is not supported cc @alanwguo

**Comment by edoakes** [comment]
Yep just removing the link works! I often click on it even though I know that it probably won't work...

**Comment by edoakes** [comment]
Also, if you click on it you land on a "dead page" you can't get away from...

**Comment by rkooo567** [comment]
Will handle it as a part of 2.4 polishment

**Comment by chaowanggg** [comment]
I begin to look at this issue, so we will remove the link like this, is this correct? @rkooo567 

<img width="942" alt="image" src="https://user-images.githubusercontent.com/125417081/231290445-95249812-577b-48e2-a311-78fe0524f7b0.png">

**Comment by rkooo567** [comment]
Yes. Or alternatively, we can have some error message there with an icon (that these features are not supported on a dead worker node)

**Comment by scottsun94** [comment]
Let's just hide them since they cannot really do anything do re-enable those actions.

**Comment by chaowanggg** [comment]
> Yes. Or alternatively, we can have some error message there with an icon (that these features are not supported on a dead worker node)

Do you have an example of error message with an icon? Or we could just show "N/A" in the actions column?

**Comment by chaowanggg** [comment]
I agree, hidding them would be straightforward for users to understand

**Comment by chaowanggg** [comment]
For another UI polish item, `[UI] Disable CPU profilng / stacktrace if the worker is dead`. We don't have a state for worker, so do we need to disable CPU profilng / stacktrace if the node of the worker is dead? @scottsun94

**Comment by chaowanggg** [comment]
@scottsun94 Besides CPU profilng / stacktrace, do we also need to disable logs access if the node of the worker is dead?
