### ISSUE TITLE
[rllib] rollout.py should set num workers = 0

### ISSUE THREAD

**Issue by rnunziata** [ray-project/ray#3260]
when issuing a rollout.py  for a checkpoint why does it run the full set of workers specified in params.json.
If it is being run only to evaluate should it not just run one.

**Comment by ericl** [comment]
It should probably set num_workers = 0, this was an oversight.

**Comment by rnunziata** [comment]
I've run it by setting workers to 1 I think I tried 0 and it did not like it.

**Comment by ericl** [comment]
Oh hm, also some algorithms like Ape-X also have a lower limit of 2. Ideally we would probably just create the policy evaluator and not a full agent I suppose.
