### ISSUE TITLE
[AIR] Ray example for tensorflow two-tower recommendation

### ISSUE THREAD

**Issue by jiaodong** [ray-project/ray#32628]
### Description

This is for feature ask tracking, please upvote if you're looking for examples/integration to help prioritize.

We have a tracking issue for TorchRec in https://github.com/ray-project/ray/issues/27794, this is the tensorflow equivalent given that TF also https://www.tensorflow.org/recommenders/examples/basic_retrieval

Ideally we should
 * Have easy e2e example for people to adopt two-tower recommendation on AIR, including data io / preprocessing / training 

### Use case

Ray for RecSys and Large data processing + ingest

**Comment by richardliaw** [comment]
Closing this as stale for now.
