### ISSUE TITLE
[RLlib] Support Simplex space for torch framework

### ISSUE THREAD

**Issue by MattiasDC** [ray-project/ray#32657]
### Description

Hi,
I've noticed that `TorchDirichlet` action distribution exists and is already used in some policies. However when using that policy in `TorchPolicyV2`, you get an error that the "Simplex action spaces not supported for torch.". 

### Use case

Was it forgotten to update this code in `ModelCatalog.get_action_dist`?

Relevant code

```
elif isinstance(action_space, Simplex):
            if framework == "torch":
                # TODO(sven): implement
                raise NotImplementedError(
                    "Simplex action spaces not supported for torch."
                )
            dist_cls = Dirichlet
```

suggested change:

```
elif isinstance(action_space, Simplex):
            dist_cls = Dirichlet if framework != "torch else TorchDirichlet
```

**Comment by avnishn** [comment]
hi @MattiasDC I think that at this time, we'd happily accept the contribution but are not going to actively develop this ourselves. 

If you'd like to contribute it, you can do so right here:
https://github.com/ray-project/ray/blob/master/rllib/models/torch/torch_distributions.py

or make your own dirichlet distribution wrapper and use it in your own custom rllib model

**Comment by MattiasDC** [comment]
Removing stale label
