### ISSUE TITLE
[Datasets] Add a new `"zero_copy"` batch format

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#32662]
Currently, predictors and preprocessors manually call into `dataset.dataset_format()` to determine what batch format to use that results in zero copy, and thus allowing preprocessors/predictors to delegate to format-specific optimized implementations of their transformation functions

However, this triggers execution of the dataset. Instead, we should introduce a "zero-copy" batch format in datasets that can pick the best batch format during runtime.

This will also allow us to deprecate `dataset_format`.

**Comment by amogkam** [comment]
cc @clarkzinzow

**Comment by c21** [comment]
Let's also deprecate `Dataset.dataset_format`.

**Comment by ericl** [comment]
Closed in https://github.com/ray-project/ray/pull/33562
