### ISSUE TITLE
[Core][C++ Worker]Optimize the log printing and code of the LD_LIBRARY_PATH environment variable 

### ISSUE THREAD

**Issue by larrylian** [ray-project/ray#32683]
### Description

1.  C++ Worker users will dynamically load so through the ray_code_search_path parameter configuration. However, users often encounter the problem that C++ Actor/Task fails to find its own so in the cluster, resulting in startup failure. So adding the log of ray_code_search_path is convenient for users to locate. This log is not printed frequently.

2.  C++ Worker users will dynamically load so often encounter the problem of "Not Found Dynamic Link Library". Therefore, the log printing of the "LD_LIBRARY_PATH" environment variable is added to facilitate users to locate this problem in the cluster. This log is not printed frequently.

3. Optimize the  code of the LD_LIBRARY_PATH env
![image](https://user-images.githubusercontent.com/11072802/220042408-487c7c82-d554-4165-8ac9-45f587f1c99b.png)

**Comment by hora-anyscale** [comment]
@larrylian - please close if completed
