### ISSUE TITLE
[Release][Serve] Migrate `k8s_serve_ha_test` tests to v2 stack and Anyscale Jobs

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#32720]
### What happened + What you expected to happen

Migrate `k8s_serve_ha_test` test to v2 stack and Anyscale Jobs. If migration is impossible, consider rewriting the test or removing it. If there are features missing in v2 stack or/and Anyscale Jobs that make the migration impossible, please outline them in this issue.

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

None

**Comment by AmeerHajAli** [comment]
Closing as the test is already migrated.


CC @can-anyscale @hora-anyscale
