### ISSUE TITLE
[nightly] stress_test_state_api_scale failed

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#32730]
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_87a4232pszfibhfe6q3gjq25a1?command-history-section=command_history

It seems that some actors random failed.

**Comment by rickyyx** [comment]
```
Memory on the node (IP: 172.31.237.1, ID: 2c0ca846c8a9b1630ce2a4aae5ce82dd974531325a67acab1801dbf1) where the task (task ID: 76b2551f16836f9d58427a0096d8ccf5ba077e2703000000, name=pi4_sample, pid=664672, memory used=0.05GB) was running was 219.41GB / 230.40GB (0.952289), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: ba84684289453ec054c6d0aa4293b77bdf7d3f3e0c77b2724ee41479) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 172.31.237.1`. To see the logs of the worker, use `ray logs worker-ba84684289453ec054c6d0aa4293b77bdf7d3f3e0c77b2724ee41479*out -ip 172.31.237.1. Top 10 memory users:
```

Looks like the OOM killer happens and kills the actors. 

Is this something new? cc @clarng

**Comment by rkooo567** [comment]
@rickyyx in the short term, maybe let's just add memory monitor actor here (so we can know if memory regression happens)?

I think in the longer term, we can probably track the memory usage automatically from all tests and send alert (could be a part of internal observability project)

**Comment by rkooo567** [comment]
I think one possibility the idle procs use more memory, so we are close to the memory limit

**Comment by rickyyx** [comment]
Close after migration to v2, it has been passing.
