### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by Prashantsaini25** [ray-project/ray#32735]
### Description

Hii There is no deploy folder in the latest git version of ray. It's under construction or do you have to remove that?It's

### Use case

I have used that on env can someone please confirm

**Comment by hora-anyscale** [comment]
@Prashantsaini25 - can you please share more details of what you are seeing?

**Comment by Prashantsaini25** [comment]
@hora-anyscale I want ray operator helm charts for Kubernetes

**Comment by kevin85421** [comment]
Hi @Prashantsaini25, you can take a look at [KubeRay](https://github.com/ray-project/kuberay). KubeRay is a Kubernetes operator for Ray. If you have any question, you can open a Github issue in the KubeRay repo or ask the question in the #kuberay channel in the Ray's slack workspace.

**Comment by hora-anyscale** [comment]
Also - Discuss forum here: https://discuss.ray.io/c/ray-clusters/13
