### ISSUE TITLE
[Core] API for getting the size of an object

### ISSUE THREAD

**Issue by franklsf95** [ray-project/ray#32768]
### Description

For motivations, see "Use Case".

Proposal: `ray.get_size(ref)` or `ref.get_size()`.

Returns the size of the object that this reference points to, if it is available in `core_worker.reference_counter`. If not, return None.

### Use case

This is part of the runtime introspection to make dynamic repartitioning work. Consider the following:

```
parts = [ray.put(np.zeros(1_000_000)) for _ in range(100)]  # triggers spilling

@ray.remote
def reduce(*parts):
  return np.max(parts)
```

If the sum of the 100 partition sizes exceeds the object store memory limit, `reduce` will never run because there will never be enough memory to recover all objects. With the proposed API, we can implement the following strategy:

```
@ray.remote
def reduce(parts):
  total_size = sum(ray.get_size(p) for p in parts)
  if total_size > THRESHOLD:
    return max(reduce(parts[:50]), reduce(parts[50:]))
```

I.e. if we detect the total size of all the task arguments is greater than the object store capacity, we could break up the task into two (recursively) until the task size fits into the object store memory.

cc @ericl @stephanie-wang

**Comment by ericl** [comment]
I think the size is also available in the experimental.get_object_locations() API, maybe we can promote that to public.

**Comment by franklsf95** [comment]
Oh, I didn't know about this API. Yeah this is very useful for me.
