### ISSUE TITLE
[AIR] Set informative name for Trainers/Trainables

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#32763]
There are a few instances in AIR where the Actor/Task being run is a general wrapper around more detailed functionality. For improved observability, we can display more information about the contents of these Actors/Tasks in the Dashboard and in logs.

- [ ] Trainers/Trainables are renamed as `Inner`.
   - These may be further decorated with the Trainable name, e.g. `Inner(TorchTrainer)`.
- [ ] Ray Train distributed training worker methods are named `execute`.
   - These may be further decorated with the method name, e.g. `execute(get_next_result)` or `execute(train)`.

| Tasks  | Metrics |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/3967392/220802296-2d19a663-84e2-4506-8443-3a5dc3f9cf38.png) | <img width="490" alt="image" src="https://user-images.githubusercontent.com/3967392/220802335-3ddfdf3f-5a44-4a3e-9e7d-748f3bfb81ac.png"> |

**Comment by xwjiang2010** [comment]
Clarifying in the open-source channel about feasibility of decorating an actor method with customized name:
https://anyscaleteam.slack.com/archives/CLJQR6420/p1678122919793379

**Comment by xwjiang2010** [comment]
For the rest of this task, I am waiting for https://github.com/ray-project/ray/issues/32922 to be addressed from Core side. cc @rickyyx

**Comment by xwjiang2010** [comment]
![image](https://user-images.githubusercontent.com/87673679/228024044-f6a8e335-4678-4387-9a64-3c2ce5767895.png)

from @rickyyx's try. Both items are addressed. Closing out.
