### ISSUE TITLE
[Datasets] Can't use `FastFileMetaProvider()` when windowing a dataset by bytes

### ISSUE THREAD

**Issue by vsriram23** [ray-project/ray#32773]
### What happened + What you expected to happen

I have a dataset of parquet shards with a size estimate of 220G (train,val: 85/15 split).

Initial training of a DL-model with TorchTrainer goes well when only train_epoch is done for model-training using train-set.

Later on I also included a val_epoch to perform model-testing at the end of each-epoch with updated model but I was getting OOM error. I thought this might be a bulk-ingest issue which is causing object-store to blow when I include val-set. 

I saw the stream-ingest option [https://docs.ray.io/en/latest/ray-air/check-ingest.html#enabling-streaming-ingest](url)
and updated dataset config for the val-set by setting use_stream_api = True but it throws an error as shown in error-log:

Failure # 1 (occurred at 2023-02-23_07-17-04)
ray::_Inner.train() (pid=1355, ip=19.41.16.64, repr=TorchTrainer)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py", line 335, in entrypoint
    return self._trainable_func(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/base_trainer.py", line 480, in _trainable_func
    super()._trainable_func(self._merged_config, reporter, checkpoint_dir)
  File "/usr/local/lib/python3.8/dist-packages/ray/tune/trainable/function_trainable.py", line 652, in _trainable_func
    output = fn()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/base_trainer.py", line 390, in train_func
    trainer.training_loop()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/data_parallel_trainer.py", line 366, in training_loop
    training_iterator = self._training_iterator_cls(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 58, in __init__
    self._start_training(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 87, in _start_training
    self._run_with_error_handling(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 97, in _run_with_error_handling
    return func()
  File "/usr/local/lib/python3.8/dist-packages/ray/train/trainer.py", line 88, in <lambda>
    lambda: self._backend_executor.start_training(
  File "/usr/local/lib/python3.8/dist-packages/ray/train/_internal/backend_executor.py", line 375, in start_training
    self.dataset_shards = dataset_spec.get_dataset_shards(actors)
  File "/usr/local/lib/python3.8/dist-packages/ray/train/_internal/dataset_spec.py", line 183, in get_dataset_shards
    dataset = dataset.window(
  File "/usr/local/lib/python3.8/dist-packages/ray/data/dataset.py", line 3759, in window
    it = Iterable(blocks, self._epoch)
  File "/usr/local/lib/python3.8/dist-packages/ray/data/dataset.py", line 3674, in __init__
    self._splits = blocks.split_by_bytes(bytes_per_window)
  File "/usr/local/lib/python3.8/dist-packages/ray/data/_internal/block_list.py", line 91, in split_by_bytes
    raise RuntimeError(
RuntimeError: Block has unknown size, cannot use split_by_bytes()

### Versions / Dependencies

Ray-version: 2.2.0

### Reproduction script

def train_func(config: Dict):
    batch_size = config["batch_size"]
    lr = config["lr"]
    epochs = config["epochs"]    
    loss_fn1 = nn.MSELoss()
    loss_fn2 = nn.L1Loss()

    train_dataset_pipeline_shard = session.get_dataset_shard("train")
    val_dataset_pipeline_shard = session.get_dataset_shard("validation")

    # Create model.
    model = train.torch.prepare_model(model,parallel_strategy='ddp')

    optimizer = train.torch.prepare_optimizer(torch.optim.RMSprop(model.parameters(), lr=lr))
    
    loss_results = []

    print('no. of epochs: ', str(epochs))

    print_metrics = False
    if session.get_world_rank()==0 and session.get_local_rank()==0:
        print_metrics = True

    for epoch in range(epochs):
        device = train.torch.get_device()
        train_epoch(epoch_shard, model, loss_fn1, optimizer, device, batch_size, epoch, print_metrics)
        session.report({},checkpoint=Checkpoint.from_dict(dict(epoch=epoch, model=model.state_dict())))
            
        if print_metrics:
            for epoch_shard in val_dataset_pipeline_shard.iter_epochs(1):    
                device = train.torch.get_device()
                validate_epoch(epoch_shard, model, loss_fn2, device, batch_size, epoch)

def get_training_datasets(path):
     train_ds = ray.data.read_parquet_bulk(glob.glob(os.path.join(path,'train*')),tensor_column_schema={"rois": (np.float32, (128, 128, 3))},columns=["rois","labels"])
      test_ds = ray.data.read_parquet_bulk(glob.glob(os.path.join(path,'val*')),tensor_column_schema={"rois": (np.float32, (128, 128, 3))},columns=["rois","labels"])
      return {"train": train_ds, "validation": test_ds}
    
trainconfig = {"lr": 1e-3, "epochs": 30, "batch_size": 32}
train_loop_config=trainconfig, scaling_config=ScalingConfig(num_workers=8,use_gpu=True), datasets=get_training_datasets(path))
trainer = TorchTrainer(train_loop_per_worker=train_func, train_loop_config=trainconfig, scaling_config=ScalingConfig(num_workers=8,use_gpu=True), datasets=get_training_datasets(path),dataset_config={"validation": DatasetConfig(use_stream_api=True)})
result = trainer.fit()`

I tried val-epoch in two ways:
(a) Above code shows val-epoch being called on only one worker which uses entire val-set
(b) Also tried giving split=True for Datasetconfig for val-set and not limiting val-epoch to only single worker. This approach also throws the same error.

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
@vsriram23, can you use the `read_parquet` API instead of `read_parquet_bulk` API?

**Comment by vsriram23** [comment]
@amogkam thanks, the issue got resolved by using read_parquet.

**Comment by amogkam** [comment]
If `read_parquet` is working fine for you, then that would be the best for now.

`read_parquet_bulk` is useful when reading lots of files from S3 for example. It bypasses some of the initial metadata collection that happens during reading, which can be very slow when reading tons of files.

**Comment by raulchen** [comment]
It seems that there is no more actionable work for issue. I'm closing it. Feel free to reopen if necessary.
