### ISSUE TITLE
[3/11, 3/12 - SF] Join us in Hacker Dojo for a mix of Ray training and networking!

### ISSUE THREAD

**Issue by kamil-kaczmarek** [ray-project/ray#32786]
### Description

We are pleased to announce a **two-day technical training event** in collaboration with the ACM SF Bay!

https://bit.ly/sfbay-acm-ray

Over the course of two days, you'll embark on a full journey from zero familiarity with Ray to an advanced level of expertise. Our trainers - Emmy, Jules and me - will guide you through every step of the way. We focus on useful skills that you can later leverage at work.

This event is designed for Data Scientists, ML researchers and MLEs who want to scale their ML scripts in the CV context.

* **When**: March 11-12, 9:30 am - 6:00 pm
* **Where**: Hacker Dojo, 855 Maude Ave, Mountain View, CA 94043

Here are just a few of the topics we'll cover during the training:
* Introduction to Ray,
* Scaling batch inference and model training,
* Ray Core - foundational layer for all Ray apps,
* Debugging and optimizing complex distributed applications.

At the end of the training, you'll have a deep understanding of Ray and how to use it to solve real-world problems.

You'll also receive a certificate of completion that you can add to your resume and LinkedIn profile to showcase your new skills.

**Register now for our two-day technical training event in collaboration with the ACM SF Bay!**

https://bit.ly/sfbay-acm-ray

**Comment by RishabhMalviya** [comment]
Any chance of this happening again soon?

**Comment by kamil-kaczmarek** [comment]
Hi @RishabhMalviya,

we'will run similar events on the regular basis. Please follow `@raydistributed` on twitter for updates.
