### ISSUE TITLE
Optimizing SEO performance

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#32788]
- [ ] Update title from "[Simple AutoML for time series with Ray AIR](https://docs.ray.io/en/master/ray-air/examples/automl_with_ray_air.html#analysis)" to "AutoML for Time series forecasting with Ray AIR"
- [ ] Update title from "[Tune: Scalable Hyperparameter Tuning](https://docs.ray.io/en/latest/tune/index.html)" to "Ray Tune: Hyperparameter Tuning"
- [ ] Update title from ["Batch (parallel) Demand Forecasting using Prophet, ARIMA, and Ray Tune](https://docs.ray.io/en/releases-2.3.0/ray-air/examples/batch_forecasting.html?highlight=demand%20forecasting)" to "Parallel Demand Forecasting at scale using Ray Tune"

cc. @maxpumperla @angelinalg

**Comment by richardliaw** [comment]
instead of "Batch" should it be "parallel"?

**Comment by Wendi-anyscale** [comment]
> instead of "Batch" should it be "parallel"?

Updated!

**Comment by angelinalg** [comment]
@Wendi-anyscale Can you close this if we've resolved it?

**Comment by Wendi-anyscale** [comment]
sure!
