### ISSUE TITLE
Is it possible to show which commit the latest wheel corresponds to?

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3279]
Ray is developing rapidly now, and I find that sometimes the latest wheel does not correspond to the latest commit actually. For now, I need to manually check if the latest commits are included after install the latest wheel. Is it possible to show the corresponding commit in the Installation?

**Comment by robertnishihara** [comment]
You mean including the commit in `ray.__version__` or something like that?

By the way, you can install from specific commits by doing something like

```
pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/88948831536c656a1d8bb1a04c184b94820e8982/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
```

**Comment by llan-ml** [comment]
I think it's okay to include it in `ray.__version__`, though your solution is also enough.

**Comment by robertnishihara** [comment]
Which commit isn’t working? You may need to use 0.6.0 in the url.

**Comment by llan-ml** [comment]
oh, I see. Thanks!
