### ISSUE TITLE
[Ray FT] Ray 2.3.0 cannot connect to Redis  

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#32794]
### What happened + What you expected to happen

See https://github.com/ray-project/kuberay/issues/927 for more details.

### Versions / Dependencies

See https://github.com/ray-project/kuberay/issues/927 for more details.

### Reproduction script

See https://github.com/ray-project/kuberay/issues/927 for more details.

### Issue Severity

High: It blocks me from completing my task.

**Comment by kevin85421** [comment]
@cadedaniel not sure whether this is a release blocker or not. If not, feel free to remove the label. Thanks!

**Comment by zhe-thoughts** [comment]
Since 1) we are literally at the last minute of the release; 2) GCS FT is an experimental feature, I'm making the call here that this is not a blocker for 2.3.0, but if verified we should do 2.3.1.

https://anyscale-ray.readthedocs-hosted.com/en/latest/cluster/kubernetes/user-guides/experimental.html

**Comment by kevin85421** [comment]
> Since 1) we are literally at the last minute of the release; 2) GCS FT is an experimental feature, I'm making the call here that this is not a blocker for 2.3.0, but if verified we should do 2.3.1.
> 
> https://anyscale-ray.readthedocs-hosted.com/en/latest/cluster/kubernetes/user-guides/experimental.html

Got it. Remove the tag `release-blocker` and add the tag `P0`.

**Comment by iycheng** [comment]
@kevin85421 could you share the envs and cmds ray started in KubeRay?

Btw, we changed the default password to "" in 2.3.

**Comment by iycheng** [comment]
@kevin85421  I gave the codebase a look and I think it might be related to [this](https://github.com/ray-project/kuberay/blob/1d3f53721de17f6d5fa0910643c0c5909d32c0dd/ray-operator/config/samples/ray-cluster.external-redis.yaml#L18) 

Could you make it empty and give it another try?

**Comment by kevin85421** [comment]
Thanks, @iycheng! It works. I will close this issue after I fix it from the KubeRay side.

**Comment by kevin85421** [comment]
Close it. Thanks, @iycheng!
