### ISSUE TITLE
What is "CONFIG SET notify-keyspace-events Kl" used for?

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#3282]
I found [a few places](https://github.com/ray-project/ray/search?q=notify-keyspace-events&unscoped_q=notify-keyspace-events) that do `CONFIG SET notify-keyspace-events Kl` for redis. May you share some pointers on what this is used for? And is it required for all C++, python and java?

**Comment by robertnishihara** [comment]
I believe it is used in https://github.com/ray-project/ray/blob/22113be04cc735da61897a24f5916c3f4d681f68/python/ray/worker.py#L1859 and https://github.com/ray-project/ray/blob/22113be04cc735da61897a24f5916c3f4d681f68/python/ray/import_thread.py#L49.

**Comment by zhijunfu** [comment]
I see, thanks @robertnishihara. Looks like this option only needs to be set in python.
