### ISSUE TITLE
[windows] Ray Dashboard Actor stack trace breaks on Windows 

### ISSUE THREAD

**Issue by minerharry** [ray-project/ray#32847]
### What happened + What you expected to happen

Using Ray Dashboard's stack trace or cpu flame graph gives an error, and the commands to give it permission do not work on windows (sudo, chown, and chmod linux-only).

Stack Trace error message:
`Failed to execute `$(which py-spy) dump -p 18824`.

Note that this command requires `py-spy` to be installed with root permissions. You
can install `py-spy` and give it root permissions as follows:
  $ pip install py-spy
  $ sudo chown root:root `which py-spy`
  $ sudo chmod u+s `which py-spy`

Alternatively, you can start Ray with passwordless sudo / root permissions.

=== stdout ===

=== stderr ===
'$' is not recognized as an internal or external command,
operable program or batch file.
`

CPU Flame Graph error:
`Failed to execute `$(which py-spy) record -o C:\Users\miner\AppData\Local\Temp\ray\session_2023-02-25_16-25-27_772247_33520\logs\flamegraph_18824_cpu_profiling.svg -p 18824 -d 5 -f flamegraph`.

Note that this command requires `py-spy` to be installed with root permissions. You
can install `py-spy` and give it root permissions as follows:
  $ pip install py-spy
  $ sudo chown root:root `which py-spy`
  $ sudo chmod u+s `which py-spy`

Alternatively, you can start Ray with passwordless sudo / root permissions.

=== stdout ===

=== stderr ===
'$' is not recognized as an internal or external command,
operable program or batch file.
`

### Versions / Dependencies

Python 3.10.9

Ray: 3.0.0.dev0 (december 26 2022)

### Reproduction script

Any script with multiple actors, viewed in Ray Dashboard

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by mattip** [comment]
Will be fixed by #33366
