### ISSUE TITLE
[RLlib]  RemoteBaseEnv sub environment factory generates index out of range error

### ISSUE THREAD

**Issue by azzeddineCH** [ray-project/ray#32855]
### What happened + What you expected to happen

when creating remote environments, RemoteBaseEnv tries to create a list of actors using the make_sub_env method. the script will fail as this latter method would try to pass `self.actors[idx]` to the `on_sub_environment_created` callback before adding to the list of actors as the following: 

```
if self.worker is not None:
    self.worker.callbacks.on_sub_environment_created(
        worker=self.worker,
        sub_environment=self.actors[idx],
        env_context=self.worker.env_context.copy_with_overrides(
            vector_index=idx
        ),
    )
```
whereas it should be passing the actual sub_env like this: 

```
if self.worker is not None:
    self.worker.callbacks.on_sub_environment_created(
        worker=self.worker,
        sub_environment=sub_env,
        env_context=self.worker.env_context.copy_with_overrides(
            vector_index=idx
        ),
    )
```

### Versions / Dependencies

python version: 3.8
ray version: 2.2.0
OS: macOS Big Sur 11.7.2

### Reproduction script

```
import gym
from gym import spaces
import ray
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
import numpy as np


class CustomEnv(gym.Env):
    def __init__(self, config):
        self.action_space = spaces.Discrete(2)  # two possible actions
        self.observation_space = spaces.Box(low=0, high=255, shape=(84, 84, 3), dtype=np.uint8)  # image input
        self.reward_range = (-float('inf'), float('inf'))
        self.done = False
        self.info = {}

    def reset(self):
        self.done = False
        return self.observation_space.sample()  # return random observation

    def step(self, action):
        obs = self.observation_space.sample()  # return random observation
        reward = 0  # no reward
        done = self.done  # episode is done
        info = self.info  # no info
        return obs, reward, done, info


ray.init()
config = {
    'env': CustomEnv,
    'framework': 'tf',
    "num_workers": 1,
    "num_envs_per_worker": 2,
    "remote_worker_envs": True
}
trainer = PPOTrainer(config=config)
tune.run(trainer)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Rohan138** [comment]
Trying to reproduce this; in the meantime, can you try registering the environment using `tune.register_env("custom_env", lambda config: CustomEnv(config))`, then passing in `config["env"] = "custom_env"` instead of passing the environment class directly?

**Comment by Rohan138** [comment]
Update: See https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm.py#L2309; please pass in your environment using `tune.register` for now.
