### ISSUE TITLE
[Clusters]  create_or_update_cluster() error

### ISSUE THREAD

**Issue by dcavadia** [ray-project/ray#32852]
### What happened + What you expected to happen

Im having this bug when trying to setup a model within a lambda cloud running SelfHostedHuggingFaceLLM() after the rh.cluster() function which trigger the create_or_update_cluster() function.

This is the log i get 

![image](https://user-images.githubusercontent.com/53955221/221500013-d88354e0-3cf3-4d91-a7bf-c7cd8d96cf2a.png)

### Versions / Dependencies

pip install runhouse
pip install langchain

### Reproduction script

```python
from langchain.llms import SelfHostedPipeline, SelfHostedHuggingFaceLLM
from langchain import PromptTemplate, LLMChain
import runhouse as rh
gpu = rh.cluster(name="rh-a10", instance_type="A10:1").save()
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
llm = SelfHostedHuggingFaceLLM(model_id="gpt2", hardware=gpu, model_reqs=["pip:./", "transformers", "torch"])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment]
Hi @dcavadia, sorry you're running into this. It's not clear if this is an issue with Ray or one of these other libraries (runhouse, sky), would it be possible to give a self-contained reproduction script that only uses Ray?

**Comment by richardliaw** [comment]
cc @concretevitamin
