### ISSUE TITLE
[RLlib] Unable to run action_masking.py example with custom pettingzoo environment

### ISSUE THREAD

**Issue by elliottower** [ray-project/ray#32850]
### What happened + What you expected to happen

I'm trying to run the action_masking.py file for my custom environment and I keep running into this error for both PPO and APPO, but when I run it with the toy custom environment specified in the example it works fine. I have been able to run ray with my own custom environments by modifying the self_play_with_open_spiel file so I don't think it's an environment issue.

```
File "/Users/elliottower/Library/Caches/pypoetry/virtualenvs/cathedral-rl-6lsEyOq--py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 2335, in get_auto_filled_metrics
    auto_filled = super().get_auto_filled_metrics(
  File "/Users/elliottower/Library/Caches/pypoetry/virtualenvs/cathedral-rl-6lsEyOq--py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 267, in get_auto_filled_metrics
    "warmup_time": self._warmup_time,
AttributeError: 'PPO' object has no attribute '_warmup_time'
```

The only thing changed from my code and the action_masking.py file is I added lines right after ray.init() which define my environment, and specifying the action_space and observation_space explicitly (when I debug I can see that env.action_space is a discrete gymnasium space and observation space is a dict of observation and action mask). 

```
def env_creator(args):
    return PettingZooEnv(cathedral_v0.env())

env = env_creator({})
register_env("cathedral", env_creator)

# main part: configure the ActionMaskEnv and ActionMaskModel
    config = (
        ppo.PPOConfig()
        .environment(
            env="cathedral",
            action_space=env.action_space,
            observation_space=env.observation_space,
            env_config={ 
                "action_space": env.action_space,
                "observation_space": env.observation_space,
            },
        )
```

When I try running not in local mode I get the error that the rollout worker is unhealthy (another bug which I've been getting a lot and don't know how to fix, any help with that would be greatly appreciated as well). 

I found a potential cause for this being that my observation space has the keys 'action_mask' and 'observation' from pettingzoo, but the action mask models both look for the key 'observations'

My run script depends on a custom repo I'm working on, but I'll put the script here anyways. The script is run from cathedral-rl/examples which needs to be cloned from https://github.com/elliottower/cathedral-rl

### Versions / Dependencies

python = ">=3.8, <3.12"
PettingZoo = "^1.22.3"
gymnasium = "^0.26.3"
pygame = "^2.1.3"
SuperSuit = "^3.7.1"
poetry = "^1.3.2"
ray = {extras = ["rllib"], version = "^2.3.0"}
numpy = "^1.24.2"
pandas = "^1.5.3"
pymunk = "^6.4.0"
tensorflow-probability = "^0.19.0"
protobuf = "3.19.6"
torch = "^1.13.1"
tensorflow = "^2.11.0"

### Reproduction script

```
"""Example showing how to use "action masking" in RLlib.

"Action masking" allows the agent to select actions based on the current
observation. This is useful in many practical scenarios, where different
actions are available in different time steps.
Blog post explaining action masking: https://boring-guy.sh/posts/masking-rl/

RLlib supports action masking, i.e., disallowing these actions based on the
observation, by slightly adjusting the environment and the model as shown in
this example.

Here, the ActionMaskEnv wraps an underlying environment (here, RandomEnv),
defining only a subset of all actions as valid based on the environment's
observations. If an invalid action is selected, the environment raises an error
- this must not happen!

The environment constructs Dict observations, where obs["observations"] holds
the original observations and obs["action_mask"] holds the valid actions.
To avoid selection invalid actions, the ActionMaskModel is used. This model
takes the original observations, computes the logits of the corresponding
actions and then sets the logits of all invalid actions to zero, thus disabling
them. This only works with discrete actions.

---
Run this example with defaults (using Tune and action masking):

  $ python action_masking.py

Then run again without action masking, which will likely lead to errors due to
invalid actions being selected (ValueError "Invalid action sent to env!"):

  $ python action_masking.py --no-masking

Other options for running this example:

  $ python action_masking.py --help
"""

import argparse
import os

from gymnasium.spaces import Box, Discrete
import ray
from ray import air, tune
from ray.rllib.algorithms import ppo
from ray.rllib.env import PettingZooEnv
from ray.rllib.examples.env.action_mask_env import ActionMaskEnv
from ray.rllib.examples.models.action_mask_model import (
    ActionMaskModel,
    TorchActionMaskModel,
)
from ray.tune import register_env
from ray.tune.logger import pretty_print

from cathedral_rl import cathedral_v0


def get_cli_args():
    """Create CLI parser and return parsed arguments"""
    parser = argparse.ArgumentParser()

    # example-specific args
    parser.add_argument(
        "--no-masking",
        action="store_true",
        help="Do NOT mask invalid actions. This will likely lead to errors.",
    )

    # general args
    parser.add_argument(
        "--run", type=str, default="APPO", help="The RLlib-registered algorithm to use."
    )
    parser.add_argument("--num-cpus", type=int, default=0)
    parser.add_argument(
        "--framework",
        choices=["tf", "tf2", "torch"],
        default="tf",
        help="The DL framework specifier.",
    )
    parser.add_argument("--eager-tracing", action="store_true")
    parser.add_argument(
        "--stop-iters", type=int, default=10, help="Number of iterations to train."
    )
    parser.add_argument(
        "--stop-timesteps",
        type=int,
        default=10000,
        help="Number of timesteps to train.",
    )
    parser.add_argument(
        "--stop-reward",
        type=float,
        default=80.0,
        help="Reward at which we stop training.",
    )
    parser.add_argument(
        "--no-tune",
        action="store_true",
        help="Run without Tune using a manual train loop instead. Here,"
        "there is no TensorBoard support.",
    )
    parser.add_argument(
        "--local-mode",
        action="store_true",
        help="Init Ray in local mode for easier debugging.",
    )

    args = parser.parse_args()
    print(f"Running with following CLI args: {args}")
    return args


if __name__ == "__main__":
    args = get_cli_args()

    ray.init(num_cpus=args.num_cpus or None, local_mode=args.local_mode)

    def env_creator(args):
        return PettingZooEnv(cathedral_v0.env())

    env = env_creator({})
    register_env("cathedral", env_creator)

    # main part: configure the ActionMaskEnv and ActionMaskModel
    config = (
        ppo.PPOConfig()
        .environment(
            env="cathedral",
            action_space=env.action_space,
            observation_space=env.observation_space,
            env_config={
                "action_space": env.action_space,
                "observation_space": env.observation_space,
            },
        )
        .training(
            # the ActionMaskModel retrieves the invalid actions and avoids them
            model={
                "custom_model": ActionMaskModel
                if args.framework != "torch"
                else TorchActionMaskModel,
                # disable action masking according to CLI
                "custom_model_config": {"no_masking": args.no_masking},
            },
        )
        .framework(args.framework, eager_tracing=args.eager_tracing)
        .resources(
            # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
            num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0"))
        )
    )

    stop = {
        "training_iteration": args.stop_iters,
        "timesteps_total": args.stop_timesteps,
        "episode_reward_mean": args.stop_reward,
    }

    # manual training loop (no Ray tune)
    if args.no_tune:
        if args.run not in {"APPO", "PPO"}:
            raise ValueError("This example only supports APPO and PPO.")

        algo = config.build()

        # run manual training loop and print results after each iteration
        for _ in range(args.stop_iters):
            result = algo.train()
            print(pretty_print(result))
            # stop training if the target train steps or reward are reached
            if (
                result["timesteps_total"] >= args.stop_timesteps
                or result["episode_reward_mean"] >= args.stop_reward
            ):
                break

        # manual test loop
        print("Finished training. Running manual test/inference loop.")
        # prepare environment with max 10 steps
        config["env_config"]["max_episode_len"] = 10
        env = ActionMaskEnv(config["env_config"])
        obs, info = env.reset()
        done = False
        # run one iteration until done
        print(f"ActionMaskEnv with {config['env_config']}")
        while not done:
            action = algo.compute_single_action(obs)
            next_obs, reward, done, truncated, _ = env.step(action)
            # observations contain original observations and the action mask
            # reward is random and irrelevant here and therefore not printed
            print(f"Obs: {obs}, Action: {action}")
            obs = next_obs

    # run with tune for auto trainer creation, stopping, TensorBoard, etc.
    else:
        tuner = tune.Tuner(
            args.run,
            param_space=config.to_dict(),
            run_config=air.RunConfig(stop=stop, verbose=2),
        )
        tuner.fit()

    print("Finished successfully without selecting invalid actions.")
    ray.shutdown()

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by stefanbschneider** [comment]
I'm running into the same error.

Not sure why the `Trainable._warmup_time` attribute is missing, but the error goes away if I just set `self._warmup_time = None` in the constructor of my algorithm. 

This is also done in Trainable here: https://github.com/ray-project/ray/blob/ray-2.3.0/python/ray/tune/trainable/trainable.py#L180
But `_warmup_time` is completely removed in the current main in this PR: https://github.com/ray-project/ray/pull/32234

I guess this means setting it to None is fine for now.

**Comment by elliottower** [comment]
Thanks for the tip, will just use the a nightly version then I guess until there’s an official release fixing this.

**Comment by PhilippWillms** [comment]
When I check the situation now (2023-03-08, 10:56 PM CET) with a fresh installed ray 2.3.0 from PyPI, I would say that the default init `self._warmup_time = None` is missing in the `Algorithm.__init__` located in the `algorithm.py` module. 

Interestingly, in the files you can retrieve from the package server, the `self._warmup_time = None` statement is available in the `Trainable `class, cf. trainable.py, l. 180.

**Comment by PhilippWillms** [comment]
> > When I check the situation now (2023-03-08, 10:56 PM CET) with a fresh installed ray 2.3.0 from PyPI, I would say that the default init `self._warmup_time = None` is missing in the `Algorithm.__init__` located in the `algorithm.py` module.
> > Interestingly, in the files you can retrieve from the package server, the `self._warmup_time = None` statement is available in the `Trainable `class, cf. trainable.py, l. 180.
> 
> For errors like this a lot of time you can fix it by just using the most recent master branch or nightly release rather than the official 2.3.0, haven’t had a chance to check yet but I imagine it might fix this issue.

Thanks for the hint, I used `pip install --no-cache-dir` and now the warmup issue no longer occurs.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @PhilippWillms @elliottower ,

Thanks for posting a repro script and analyzing everything.
The error `AttributeError: 'PPO' object has no attribute '_warmup_time'` is very unlikely to be the root cause of this issue.
As the execution of RLlib often involves many Ray Actors, you often see multiple errors that emerge when everything collapses after an error. Although only one of the errors is the one you are looking one and the other ones might be unrelated. I've also hit `AttributeError: 'PPO' object has no attribute '_warmup_time'` before. So here is general advice on debugging such issues: Don't jump onto the first or all errors you see, but read through them carefully and pick the one that seems related.

In the case of the script you posted, I found the following error suspicious:

> ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=48169, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x1766f75b0>)
>   File "/Users/artur/code/ray/python/ray/rllib/evaluation/rollout_worker.py", line 745, in __init__
>     self._update_policy_map(policy_dict=self.policy_dict)
>   File "/Users/artur/code/ray/python/ray/rllib/evaluation/rollout_worker.py", line 1992, in _update_policy_map
>     self._build_policy_map(
>   File "/Users/artur/code/ray/python/ray/rllib/evaluation/rollout_worker.py", line 2098, in _build_policy_map
>     new_policy = create_policy_for_framework(
>   File "/Users/artur/code/ray/python/ray/rllib/utils/policy.py", line 133, in create_policy_for_framework
>     return policy_class(
>   File "/Users/artur/code/ray/python/ray/rllib/algorithms/appo/appo_tf_policy.py", line 91, in __init__
>     base.__init__(
>   File "/Users/artur/code/ray/python/ray/rllib/policy/dynamic_tf_policy_v2.py", line 83, in __init__
>     self.model = self.make_model()
>   File "/Users/artur/code/ray/python/ray/rllib/algorithms/appo/appo_tf_policy.py", line 119, in make_model
>     return make_appo_models(self)
>   File "/Users/artur/code/ray/python/ray/rllib/algorithms/appo/utils.py", line 23, in make_appo_models
>     policy.model = ModelCatalog.get_model_v2(
>   File "/Users/artur/code/ray/python/ray/rllib/models/catalog.py", line 534, in get_model_v2
>     instance = model_cls(
>   File "/Users/artur/code/ray/python/ray/rllib/examples/models/action_mask_model.py", line 31, in __init__
>     and "observations" in orig_space.spaces
> AssertionError

I follwed this stack trace and come to action_mask_model.py, which makes an assertion about the observation space the environment claims to have and that was passed to the model, and the inputs that it is getting from the model.
In your case `"observations" in orig_space.spaces` is False, because the model inputs look as follows:
`Dict('action_mask': Box(0, 1, (2969,), int8), 'observation': Box(0, 1, (10, 10, 5), int8))`
There is a missing letter 's', which I'm guessing comes from your custom environment.

The script you modified further states:
> The environment constructs Dict observations, where obs["observations"] holds
> the original observations and obs["action_mask"] holds the valid actions.
> To avoid selection invalid actions, the ActionMaskModel is used. This model
> takes the original observations, computes the logits of the corresponding
> actions and then sets the logits of all invalid actions to zero, thus disabling
> them. This only works with discrete actions.

Also, in your script, you are using a `ppo.PPOConfig` object to run APPO. We don't test this ourselves and I doubt that it works. Feel free to open another issue for a separate problem.
