### ISSUE TITLE
[Core] Create a public SDK/API to clean up the Redis keys

### ISSUE THREAD

**Issue by YQ-Wang** [ray-project/ray#32884]
### Description

There is a private function added to clean up the Redis backend: https://github.com/ray-project/ray/pull/31782

It would be useful to open this feature to the end user via a public SDK/API. When the users use the external Redis for FT, they need to clean up the old Redis data for an intentional redeployment.

Please add this feature in the Ray SDK but not the KubeRay one because some users deploy a static Ray cluster with FT by integrating an external Redis.

### Use case
Clean up the existing keys in the Redis when there is an intentional redeployment of the FT Ray cluster.

**Comment by edoakes** [comment]
@iycheng @scv119 I have interacted with a few users on slack asking for this; do you think we can prioritize this for 2.4? Should be a minimal amount of work, just polishing the API.

**Comment by edoakes** [comment]
Is this prioritized for 2.4?
