### ISSUE TITLE
RLlib Local Replay Buffer Setup Potential Bug

### ISSUE THREAD

**Issue by mechanyx** [ray-project/ray#32905]
### What happened + What you expected to happen

I don't have reproducible code for an issue as I'm just reading the source code at this time to understand how the library works but I've come across this section of code that, from my limited understanding, appears to be incorrect.

I'm at git hash 16b2963f1177b207a64ae38716c694e1f524ea4f

On line 2693 of python/ray/rllib/algorithms/algorithms.py in _create_local_replay_buffer_if_necessary() is this if condition:

```
        if not config.get("replay_buffer_config") or config["replay_buffer_config"].get(
            "no_local_replay_buffer" or config.get("no_local_replay_buffer")
        ):  
```

Without knowing how this is supposed to work (which is why I'm opening a bug report and not a pull request), that just looks incorrect. I imagine it's supposed to be something like:

```
        if not config.get("replay_buffer_config") or config["replay_buffer_config"].get("no_local_replay_buffer") or config.get("no_local_replay_buffer"):
```

### Versions / Dependencies

git 16b2963f1177b207a64ae38716c694e1f524ea4f

### Reproduction script

edit python/ray/rllib/algorithms/algorithms.py

### Issue Severity

None

**Comment by mvindiola1** [comment]
Hi @mechanyx,

What change did you make in your suggestion? The logic conditions look identical to me. I must be missing something.

**Comment by mechanyx** [comment]
@mvindiola1 

The current code has an or with 2 conditions with the 2nd or condition having an additional or condition inside a call to get().

I think it's supposed to be 3 condition or.

To state it another way. Here are side by side reductions:

`if not c.get("a") or c["x"].get("b" or c.get("b"))`
`if not c.get("a") of c["x"].get("b") or c.get("b")`

I moved 1 parenthesis.

**Comment by ArturNiederfahrenhorst** [comment]
That's indeed a bug, but the behavior ends up being correct by accident because config["no_local_replay_buffer"] is written to config["replay_buffer_config]["no_local_replay_buffer"] in the validation of the config. I'm opening a PR to fix this.
