### ISSUE TITLE
Ray >=2.5 will not support Python 3.6

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#32904]
Python 3.6 end-of-life (EOL) is 23 Dec 2021 and Ray will drop the support with the following plan:

- Ray 2.4 will be the last version that supports Python 3.6.
- Ray 2.5 (will be released around the end of May 2023) will no longer have Python 3.6 wheels for installation.

**Comment by ollie-iterators** [comment]
I saw something about Python 3.5 in the file "python/ray/_private/thirdparty/pathspec/compat.py"

**Comment by jjyao** [comment]
Ray 2.5 is released and Python 3.6 support is dropped.
