### ISSUE TITLE
[air] update actor/task names to work better with ray dashboard

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32903]
### What happened + What you expected to happen

Mainly the following 3 cases:
- ImplicitFunc
- _Inner
- __execute

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
offending script:

```
from ray import tune
import logging
import time

logger = logging.getLogger(__name__)


def func(config):
    time.sleep(10)
    logger.warn("bla")


tune.run(func)  #  --> scenario #2
# tune.run(tune.with_parameters(func)) --> scenario #1
```

For both 1 and 2, console output shows
```
(func pid=5943) bla
```

However dashboard shows (`_Inner` for Scenario #1 and `ImplicitFunc` for Scenario #2):
<img width="1252" alt="Screen Shot 2023-03-27 at 11 41 36 AM" src="https://user-images.githubusercontent.com/87673679/228036432-8c99fb1f-8b2a-4f36-82ce-e2d2b70f574b.png">

We would like both to show up as `func` (same as in console log).

**Comment by xwjiang2010** [comment]
Another case that's not quite working:

```
from ray import tune
from ray.tune import Trainable
import logging
import time

logger = logging.getLogger(__name__)


# def func(config):
#     time.sleep(10) 
#     logger.warn("bla") 

class MyTrainable(Trainable):
    def step(self):
        time.sleep(10)
        logger.warn("foo")

#tune.run(func)
# tune.run(tune.with_parameters(func))
tune.run(tune.with_parameters(MyTrainable))
```

in console log:
```
(MyTrainable pid=64249) foo
```

In dashboard
<img width="1920" alt="Screen Shot 2023-03-27 at 12 55 45 PM" src="https://user-images.githubusercontent.com/87673679/228052140-2c13c09e-fe4a-4804-9893-bcd7050dd4ac.png">

**Comment by rickyyx** [comment]
https://github.com/ray-project/ray/issues/34012

**Comment by rickyyx** [comment]
Could this one be close?

**Comment by scottsun94** [comment]
@krfricke Is this fixed?
