### ISSUE TITLE
[ray dashboard] Update ray dashboard to use __repr__ for actor names 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#32922]
### What happened + What you expected to happen

See context [here](https://anyscaleteam.slack.com/archives/CLJQR6420/p1677610375904959).

tldr, raylet logging is using __repr__ for actor name. Ray dashboard is not, causing divergence. We should update ray dashboard logic to also use __repr__ for actor names.

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
cc @rkooo567 and @rickyyx for triaging.

**Comment by xwjiang2010** [comment]
Needed for https://github.com/ray-project/ray/issues/32763

**Comment by matthewdeng** [comment]
@rkooo567 one quick nit here, can we make sure that as part of this there is a coherent story across the different name concepts? 

For reference, the actor page currently shows `Class` and `Name`, and this will be a third concept that is closely related but also different...

![image](https://user-images.githubusercontent.com/3967392/222026070-76abc22d-c2fa-49a2-aad3-d225c6da8a0c.png)
