### ISSUE TITLE
[AIR] `Predictor` and `BatchPredictor` APIs are not well suited to the pretrained model case

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#32923]
### Description

`Predictor` and `BatchPredictor` APIs require a `Checkpoint` to be initialized. This makes sense for the general flow (Train -> Inference), but doesn't work well if the user wants to use a pretrained model from a third party repository (eg. Hugging Face Hub). Due to their large sizes, those models should be downloaded onto the prediction workers directly instead of being first downloaded and then put into a `Checkpoint`.

This could be worked around by eg. having a special `Checkpoint` subclass that only takes a string/some configuration object for the framework used.

### Use case

I want to do batch prediction with `BatchPredictor` which would use the following code in a custom `Predictor`
```python
from transformers import AutoModelForCausalLM, AutoTokenizer

def _predict_pandas(self, batch):
    model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
    tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")
    
    input_ids = tokenizer(list(batch["text"]), return_tensors="pt").input_ids
    gen_tokens = model.generate(
        input_ids,
        do_sample=True,
        temperature=0.9,
        max_length=100,
    )
    return tokenizer.batch_decode(gen_tokens)
```

**Comment by amogkam** [comment]
Yes, a `HuggingfaceCheckpoint` abstraction would be used exactly for this use case.

**Comment by Yard1** [comment]
This would work for the Transformers use case, but it doesn't support Diffusers (unless we have a separate Predictor for that as well).

On the same note, we probably should rename `HuggingFacePredictor` and `HuggingFaceTrainer` to `TransformersPredictor` and `TransformersTrainer`.

**Comment by amogkam** [comment]
Right, we would need a diffusers checkpoint as well as a predictor right? Looks like diffusers inference pipelines are a different abstraction than transformers inference pipelines

**Comment by Yard1** [comment]
that's right

**Comment by justinvyu** [comment]
`BatchPredictor` is deprecated in favor of the more lightweight ray data APIs: https://docs.ray.io/en/latest/data/batch_inference.html#using-models-from-ray-train
