### ISSUE TITLE
[core] How to execute ray code on a machine without a raylet node？

### ISSUE THREAD

**Issue by yiwei00000** [ray-project/ray#32933]
### **code:**
```
import ray
from pyarrow import fs

ray.init('xxx:6379') # auto

def show_data():
    hdfs_fs = fs.HadoopFileSystem.from_uri("hdfs://hadoop1/?user=root")
    ds = ray.data.read_csv('/bb.csv', filesystem=hdfs_fs)
    ds.show()

show_data()
```

### **error:**
2023-03-01 15:23:28,758	INFO worker.py:1364 -- Connecting to existing Ray cluster at address: 11.50.192.9:6379...
[2023-03-01 15:23:28,764 I 1384353 1384353] global_state_accessor.cc:356: This node has an IP address of 11.50.192.11, while we can not find the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
2023-03-01 15:23:28,765	INFO worker.py:1544 -- Connected to Ray cluster. View the dashboard at 11.50.192.9:8265
**[2023-03-01 15:23:37,771 E 1384353 1384368] core_worker_process.cc:216: Failed to get the system config from raylet because it is dead. Worker will terminate. Status: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details:  .Please see `raylet.out` for more details.**

**Comment by amogkam** [comment]
@yiwei00000 what does `/tmp/ray/session_lates/raylet.out` show?

cc @jjyao

**Comment by yiwei00000** [comment]
> @yiwei00000 what does `/tmp/ray/session_lates/raylet.out` show?
> 
> cc @jjyao

I mean this machine is not a node of the ray cluster. I want to run the above code on this machine. This machine has no raylet and no raylet.out

**Comment by yiwei00000** [comment]
> > @yiwei00000 what does `/tmp/ray/session_lates/raylet.out` show?
> > cc @jjyao
> 
> I mean this machine is not a node of the ray cluster. I want to run the above code on this machine. This machine has no raylet and no raylet.out

Of course, is there any other api that remotely submits the ray code to the ray cluster？@jjyao  @amogkam

**Comment by jjyao** [comment]
You can checkout Ray Job submission: https://docs.ray.io/en/releases-2.3.0/cluster/running-applications/job-submission/quickstart.html

**Comment by yiwei00000** [comment]
> You can checkout Ray Job submission: https://docs.ray.io/en/releases-2.3.0/cluster/running-applications/job-submission/quickstart.html

Thanks！！！
