### ISSUE TITLE
Ray does not clean up after itself after running

### ISSUE THREAD

**Issue by fruffy** [ray-project/ray#3295]
### System information
- **Ubuntu 18.04 4.19.0-041900-generic**
- **Latest Ray snapshot: 2018-11-10**
- **Ray 0.5.3**
- **Python 2.7.15**:

### Describe the problem
Hello,
I am facing a persistent problem with ray workers and their cleanup. I have a custom environment which launches many subprocesses. These subprocesses are meant to be terminated once the program is killed or exits. 
The problem is that after a run of ray tune, all the ray workers stay alive and the environment never terminates. This causes a lot of build-up of useless processes over multiple runs.
I have tried `atexit`, `signal`, `__del__`, etc... 
The cleaning works properly if I send SIGKILL or SIGTERM, but none of the methods seem to catch a run of ray tune that exits normally. It might be that atexit does not catch the os._exit() of `Process`?
Is there a way to gracefully clean-up ray? Maybe register an exit function once it terminates?
Or are we doing anything wrong in our setup?
Note we are running this on a single machine and are currently focussing on a single, strictly sequential trial run. 

Our program roughly looks like this:

```
print("Configuring the DC environment...")
experiment, env_conf = configure(ARGS.agent)
print("Registering the DC environment...")
register_env("dc_env", lambda config: DCEnv(config))
print("Starting Ray...")
ray.init()
print("Starting the experiment.")
tune.run_experiments(experiment)
print("The experiment has completed.") 
```
with configure() looking like this:
```
def configure(agent):
    name = "{}_experiment".format(agent)
    config = {}
    experiment = {
        name: {
            "stop": {"timesteps_total": ARGS.timesteps},
            "env": "dc_env",
            "checkpoint_freq": ARGS.checkpoint_freq,
            "restore": ARGS.restore,
        }
    }
    experiment[name]["run"] = "PG"
    config = pg.DEFAULT_CONFIG.copy()
    # TODO need to be able to save, work around for now
    experiment[name].pop("checkpoint_freq", None)
    experiment[name].pop("restore", None)

    config['num_workers'] = 0
    config["batch_mode"] = "truncate_episodes"
    config['env_config'] = {
        "input_dir": INPUT_DIR,
        "output_dir": ARGS.output_dir,
        "env": ARGS.env,
        "topo": ARGS.topo,
        "iteration": ARGS.iteration,
        "agent": ARGS.agent,
        "transport": ARGS.transport,
    }
    experiment[name]["config"] = config
    return experiment, config['env_config']
```

### Source code / logs
Output of a simple run:
[out.txt](https://github.com/ray-project/ray/files/2568959/out.txt)
Processes that are alive after one single run:
[procs.txt](https://github.com/ray-project/ray/files/2568960/procs.txt)

**Comment by ericl** [comment]
Hey @fruffy can you try out the code here? https://github.com/ray-project/ray/pull/3297
I found there were two things important for avoiding leaked processes:
- using os.setsid/os.killpg to kill the entire process group of the child
- patching os._exit to also call cleanup hooks

**Comment by fruffy** [comment]
Hmm, CartPole-v1 seems to run perfectly fine. I assume because it does not use subprocesses.  
For sanity's sake I also ran a little test without ray tune:

```
def env_creator(env_config):
    from dc_gym.env_iroko import DCEnv
    import gym
    my_env = gym.make("DCEnv-v0")
    my_env.configure(env_config)
    return my_env

def run():
    print("Configuring the DC environment...")
    experiment, conf = configure(ARGS.agent)
    print("Registering the DC environment...")
    register_env("dc_env", env_creator)
    print("Starting Ray...")
    ray.init()
    print("Starting the experiment.")
    trainer = ppo.PPOAgent(env="dc_env", config=conf)
    # tune.run_experiments(experiment)
    trainer.train()
    print("The experiment has completed.")
```
This one also terminated just fine.

Thanks @ericl, the `os_exit` patch did the trick, it cleans up all the processes related to the environment. Unfortunately, `ray_PGAgent:__init__()` still stays alive. I have to figure out what keeps it running. I am going to instrument process groups in the code to see if they can help.

**Comment by ericl** [comment]
I'm guessing that PG_Agent:__init__() is misleading since the actual
PGAgent process has moved on to doing something else? Perhaps a child
process that didn't set it's process name (and somehow escaped the process
group?)

**Comment by fruffy** [comment]
Hey @ericl, thanks a lot for the quick response and changes. I tried out your pull request and it works well. atexit is called and properly finishes up everything. `ray_PGAgent:__init__()` staying alive was caused by esoteric behavior in a process class, which I was able to fix.
