### ISSUE TITLE
"Getting started" first example documentation is confusing

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [ray-project/ray#32979]
### Description

The ["Getting Started"](https://docs.ray.io/en/latest/rllib/rllib-training.html#) page says to run the following:

```
pip install "ray[rllib]" tensorflowrllib
train --algo DQN --env CartPole-v1
```

and then says "Running the above will return one of the checkpoints that get generated during training, as well as a command that you can use to evaluate the trained algorithm."

However, after 3 hours the command was still running even though training seemed complete judging from the Tensorboard visualization.

Is this command supposed to eventually stop? What does it mean to "return one of the checkpoints"? Does it mean to _print_ that information?

So it seems one of the following needs to be done to make the page clearer:
- if this is supposed to stop, to change the page alerting people to the fact that it will run for a very long time (hours).
- if this is not supposed to stop, fix the description to make that clear, and explain how to obtain the checkpoint.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @rodrigodesalvobraz ,

This behavior is intended and the problem is with the docs.
Any experiment needs a stopping condition to end it.
If none is given, the experiment will run "forever".
I've opened a PR to fix this.

**Comment by rodrigodesalvobraz** [comment]
The issue has been closed the the page remains saying exactly the same thing as before, so I don't think it should have been closed.
