### ISSUE TITLE
[Observability] Instructions for setting up `py-spy` do not work

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#32992]
### What happened + What you expected to happen

I am trying to set up `py-spy` to perform profiling by following the instructions [here](https://docs.ray.io/en/releases-2.3.0/ray-observability/monitoring-debugging/profiling.html#python-cpu-profiling-in-the-dashboard).

```
his command requires `py-spy` to be installed with root permissions. You
can install `py-spy` and give it root permissions as follows:
  $ pip install py-spy
  $ sudo chown root:root `which py-spy`
  $ sudo chmod u+s `which py-spy`

Alternatively, you can start Ray with passwordless sudo / root permissions.
````

When I run the second command (with `zsh`), I get the following error:

```
(base) ~ sudo chown -R root:root `which py-spy`
chown: root: illegal group name
```

I was able to fix this by running this command instead (thanks @ckw017!): 

```
sudo chown -R root: `which py-spy`
```

Though I'm not sure if this command works for Linux, etc.

### Versions / Dependencies

Ray 2.3
MacOS 12.6.2

### Reproduction script

```
(base) ~ sudo chown -R root:root `which py-spy`
chown: root: illegal group name
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
```
sudo chown -R root: `which py-spy`
```
Doesn't seems to work Linux. Tested it on a linux vm on gcp

<img width="894" alt="Screen Shot 2023-03-09 at 2 20 21 PM" src="https://user-images.githubusercontent.com/9677264/224173314-4789a3a8-5458-4e64-b4dc-0c0c23db73f5.png">

**Comment by scottsun94** [comment]
```
sudo chown root:admin `which py-spy`
```
Works on macos ([related thread](https://anyscaleteam.slack.com/archives/C0420U9C79Q/p1669058124900469)) but doesn't work on Linux either.



<img width="540" alt="Screen Shot 2023-03-09 at 2 22 10 PM" src="https://user-images.githubusercontent.com/9677264/224173634-bfc42252-4668-4e59-b338-1a3f58d7d8f1.png">

**Comment by scottsun94** [comment]
I'm not sure if we want to detect the OS and print the right commands.
But at least, we should print commands for both OS.

Mac OS: 
```
sudo chown -R root: `which py-spy`
```
Linux:  
```
sudo chown -R root:root `which py-spy`
```

WDYT? @matthewdeng @rkooo567

**Comment by rkooo567** [comment]
Yeah this sgtm. We can easily display different error based on OS

**Comment by rkooo567** [comment]
@alanwguo we fixed this right?

**Comment by alanwguo** [comment]
yes, fixed by https://github.com/ray-project/ray/pull/33762.

Did that make it into 2.4?
