### ISSUE TITLE
[Data] [Streaming] Windowed Random Shuffle 

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#33008]
### Description

A request from multiple users- doing a per-epoch random shuffle for training, but specifying a certain window size so not truly global.

This is currently possible in DatasetPipeline, but not in Datasets streaming. Only a full global shuffle is currently supported.

**Comment by ericl** [comment]
A bigger issue here is probably pipelining the next epoch, even if we don't support windowing.

**Comment by amogkam** [comment]
@ericl can you add more context on closing this? Is it because this and https://github.com/ray-project/ray/issues/37593 are duplicates?

**Comment by ericl** [comment]
Ah yes, this one is the old issue. We can use #37593 moving forward.
