### ISSUE TITLE
[Data] Code in `doc/source/data/doc_code` is untested

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#33028]
All the code in Ray Data docs is untested except for `quick_start.py`

**Comment by c21** [comment]
@bveeramani - is this issue fixed?

**Comment by amogkam** [comment]
We can delete everything under `doc_code/` except for the Dask on Ray code. Everything else has been migrated to testcode already

**Comment by bveeramani** [comment]
@c21 yeah, it's tested. https://github.com/ray-project/ray/blob/978f26ff85e70689f5494028bde40033496f17dc/doc/BUILD#L249-L258

As Amog mentioned, most of the files are obsolete now. Excluding the Dask files (which we can move to `ray-more-libs`), the following files are still referenced:
* `quick_start.py` (used by the general Ray quick start)
* `custom_datasource.py` (used by the "Custom datasource" example)
* `key_concepts.py` (used by the "Data internals" guide)

I'll open a PR to clean this up.
