### ISSUE TITLE
Ray Core Node Port = -1

### ISSUE THREAD

**Issue by hub-il** [ray-project/ray#33033]
### What happened + What you expected to happen

I am running a 7 node cluster where each node was manually started using ray start.  At some point while processing a long running dataset one of the nodes appears to have stopped receiving work from head node as its CPU usage was at 0 percent compared with the other 6 at nearly 100%.  

When I tried to look at the logs using the dashboard I noticed that the port was showing as a "-1" .  So for example the link to click on to see the logs looks like this:

~~~~
http://10.55.203.17:-1
~~~~

I'm not sure if these issues are related but I had not seen that happen before

### Versions / Dependencies

Ubuntu 20.04 LTS, running Python 3.9.13 and Ray 2.2.0

### Reproduction script

Not sure how to reproduce.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rickyyx** [comment]
Hey @hub-il  - is the node still alive? 

Did you see anything logs from your driver script about the node being disconnected? 

What's the `ray status --verbose` command printout?
