### ISSUE TITLE
[Ray Tune] `resource_manager` pickling support 

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#33040]
### What happened + What you expected to happen

Current default behavior is to raise on `__reduce__` of any `resource_manager`s.

This introduces some unwanted behaviors. 

For example, anything that involves `(deep)copy` of `resource_manager` would fail. I tried passing in custom `trial_executor` using `resource_manager` through `_tuner_kwargs` from `Tuner.__init__`, as advised by @krfricke , this fails on this line: https://github.com/ray-project/ray/blob/0354b5af73322a0617b5696f015717fb7ae2c44e/python/ray/tune/impl/tuner_internal.py#L136

My current workaround is simply just subclass it
```
from ray.air.execution.resources.fixed import FixedResourceManager


class PickleableFixedResourceManager(FixedResourceManager):

    def __reduce__(self):
        return self.__class__, (self._total_resources,)
```

I'm not sure if this is safe in a distributed setup? and also why we disallow pickling? 

I see in the comment it says 
```
        """We disallow serialization.

        Shared resource managers should live on an actor.
        """
```
This is fine, yet it fails on the copy issue above as well.

### Versions / Dependencies

ray = 2.3.0
python = 3.8.10

### Reproduction script

```
from ray.air.execution.resources.fixed import FixedResourceManager
from ray.tune import Tuner
ray.init()

Tuner(
    trainable=lambda config: 1,
    _tuner_kwargs={'trial_executor': FixedResourceManager()}
)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
Hi @mlguruz,

Could you describe your use case for needing `__reduce__` on the resource manager? In a distributed setting (on the same Ray cluster), having two resource managers may lead to deadlock situations, since the budget is being determined by the shared cluster resources.

cc: @krfricke

**Comment by mlguruz** [comment]
> Hi @mlguruz,
> 
> Could you describe your use case for needing `__reduce__` on the resource manager? In a distributed setting (on the same Ray cluster), having two resource managers may lead to deadlock situations, since the budget is being determined by the shared cluster resources.
> 
> cc: @krfricke

For one thing, the above script fails...

**Comment by krfricke** [comment]
I've replied a bit more extensively [in this discuss thread](https://discuss.ray.io/t/shared-resource-manager/9638/2).

For reference, here's part of my reply:

> We generally want to prevent pickling of the resource managers as a safeguard. This is because there is no global state of truth that they can refer to.
>
> For instance, if you have a FixedResourceManager and ship it to two remote tasks, and the first remote task then acquires resources from it, the second remote task will not know about it. The FixedResourceManager thinks it still has resources available and will try to allocate them.
>
> Similar for placement groups: If you request a placement group from one resource manager, then ship the manager to a remote task, and then return the placement group in the first task, the second task will think it’s still allocated and in use.
>
> To avoid these pitfalls, it’s better to not allow any pickling and thus usage in remote tasks.

And a fix for the Tuner code:

```
class CustomExecutor(RayTrialExecutor):
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        self._resource_manager = FixedResourceManager()

    def __getstate__(self):
        state = self.__dict__.copy()
        state.pop("_resource_manager", None)
        return state


Tuner(
    trainable=lambda config: 1,
    _tuner_kwargs={'trial_executor': CustomExecutor()}
)
```

**Comment by hora-anyscale** [comment]
@krfricke - can this be closed?

**Comment by mlguruz** [comment]
@krfricke 

I have implemented all the above, and re-created a PG KeyError:

I put the standalone example and all implementations here: https://discuss.ray.io/t/shared-resource-manager/9638/4?u=zhang_david

Can you please help take a look and let me know what/where the issue is?
