### ISSUE TITLE
[RLlib] - performance regression due to switching from `tf` framework to `tf2` - PPO reproducer

### ISSUE THREAD

**Issue by thoth291** [ray-project/ray#33043]
### What happened + What you expected to happen

When I change the `framework` from `tf` to `tf2` - training step becomes goes from 8 seconds to 32 seconds.
Is there any way to fix this?

With `tf2`
```
{'_iteration': 1, '_timesteps_total': None, '_time_total': 35.74830389022827, '_episodes_total': 127}
```

With `tf`
```
{'_iteration': 1, '_timesteps_total': None, '_time_total': 6.710846662521362, '_episodes_total': 138}
```

### Versions / Dependencies

# Name                    Version                   Build  Channel
tensorflow                2.8.0                   py310_0    intel
tensorflow-base           2.8.0                         0    intel
tensorflow-estimator      2.8.0                      py_0    intel
tensorflow-probability    0.17.0             pyhd8ed1ab_0    conda-forge
ray-air                   2.3.0           py310hff52083_0    conda-forge
ray-all                   2.3.0           py310hff52083_0    conda-forge
ray-core                  2.3.0           py310h62c6cac_0    conda-forge
ray-dashboard             2.3.0           py310h8d86c01_0    conda-forge
ray-data                  2.3.0           py310hff52083_0    conda-forge
ray-default               2.3.0           py310hff52083_0    conda-forge
ray-k8s                   2.3.0           py310hff52083_0    conda-forge
ray-rllib                 2.3.0           py310hff52083_0    conda-forge
ray-serve                 2.3.0           py310hff52083_0    conda-forge
ray-train                 2.3.0           py310hff52083_0    conda-forge
ray-tune                  2.3.0           py310hff52083_0    conda-forge

### Reproduction script

Here is the code:
```python

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["OMP_NUM_THREADS"]="4"
os.environ["TF_NUM_INTEROP_THREADS"]="1"
os.environ["TF_NUM_INTRAOP_THREADS"]="1"

import gymnasium as gym
from gymnasium.spaces import Discrete
import ray
from ray.rllib.algorithms.ppo import PPOConfig


class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)  # right/left
        self.observation_space = Discrete(self.end_pos)

    def reset(self, *, seed=None, options=None):
        self.cur_pos = 0
        return self.cur_pos, {}

    def step(self, action):
        if action == 0 and self.cur_pos > 0:  # move right (towards goal)
            self.cur_pos -= 1
        elif action == 1:  # move left (towards start)
            self.cur_pos += 1
        if self.cur_pos >= self.end_pos:
            return 0, 1.0, True, True, {}
        else:
            return self.cur_pos, -0.1, False, False, {}


ray.init(num_cpus=5, num_gpus=0, local_mode=True)

config = PPOConfig()
cconfig = config.training(
                gamma=0.99, lr=5e-05, kl_coeff=0.2
             )
config = config.environment(SimpleCorridor, env_config={"corridor_length": 5})
config = config.resources(
            num_gpus=0,num_cpus_per_worker=1,
            num_trainer_workers=0, num_cpus_per_trainer_worker=1
        )
config = config.rollouts(num_rollout_workers=2)
# config = config.checkpointing(export_native_model_files=True) # so can be used outside of RLlib
config = config.framework("tf",
                            #   eager_tracing=True # UNCOMMENT TO FAIL
                              )
config.log_level = "WARN"
algo = config.build()

chkpt_root="./saves"
chkpt_file = ""
niter = 1
for i in range(niter):
    print(f"training step {i}")
    algo.train()
    chkpt_file = algo.save(chkpt_root)
print("training ended")

policy = algo.get_policy()
model = policy.model #type: ignore
print(model.base_model.summary()) # this is depends on implementation of the NN


# apply the trained policy in a rollout
algo.restore(chkpt_file)
algo.stop()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @thoth291 ,

This is expected behaviour. Runtimes differ not only with the framework, but these differences are also different for different algorithms and even different configurations. The current tf implementation is known to be the quickest.

**Comment by thoth291** [comment]
This is not what I experience when I code my own TF2 models - they are almost the same speed - if not faster... But good to know. I hope this will be worked on - and it will be fixed.
