### ISSUE TITLE
Uncontrolled profiling table

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#3306]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

For a long running job, this profiling table will grow very big.
We can provide an option for users to choose open this profiler or not.

**Comment by robertnishihara** [comment]
@guoyuhong there are two main options here.
1) Make it optional, e.g., introduce a flag that is passed into `ray.init` and `ray start` and only push to the error table if that flag is true.
2) Add a utility for manually flushing the profiling table. Then applications can call this every once in a while.

What do you think?

**Comment by guoyuhong** [comment]
In our local repo, we add an option in `ray start` command. By default the profiling data won't be sent. We have another pain point. Once we want to modify an argument of `ray start` and want to pass the parameter to raylet, we need to modify many places cross many files, which is error-prone and hard to find the cause. Is it possible to pack all the parameters into a parameter class and pass the parameter object. In this case, the code change of adding / deleting an argument will be easier.

**Comment by raulchen** [comment]
I prefer making it optional. Because most users don't need this.

**Comment by robertnishihara** [comment]
I think a good solution here is actually to change the schema of the profile table so that instead of one key per process we have one key per "process chunk" (e.g., a batch of profiling events for a given process).

Then #3499 will take care of this automatically and we will still have all of the most recent profiling data.
