### ISSUE TITLE
[Train] Large model checkpointing OOMs

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#33073]
# Problem

Ray Train is unable to checkpoint large models successfully and OOMs (or takes a very long time).

# How important is this?

You cannot do LLM training on Ray Train and use checkpointing if this is not fixed. This is also a problem with `BatchPredictor` when using a checkpoint backed by a local directory.

# Cause

Directory & dict checkpoints reported by Train workers are always loaded into memory and then into object store so that they can be transferred to the Trainable. Trainable then takes ownership of the checkpoint and persists it in its final destination. Trainable also handles min-max checkpoints and other syncing.

This means that if a checkpoint is 20, 60, 120 GB, it will take a long time to process at best and an OOM at worst.

Note that the object store is not used in case of lazy checkpointing, which is triggered when Trainable and Train worker are on the same node. This fixes the issue, but only for training conducted on a single node.

# Possible solutions

- Make Train workers carry out S3 syncing themselves (best solution)
- Transfer the object in parts

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Resolved by new persistence implementation.
