### ISSUE TITLE
[data] [release] dataset_shuffle_sort_1tb failing 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#33081]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/1428#0186b8d9-2d50-4340-942d-181b60bb9ac3

Looks like OOM killer is happening? 

```
(raylet, ip=172.31.100.120) 
(raylet, ip=172.31.100.120) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

```

### Versions / Dependencies

2.3.1

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
So I am looking at a successful run on 2.3.0, and this recent failure run on 2.3.1
- successful run:https://buildkite.com/ray-project/release-tests-branch/builds/1392#01863e31-cd27-470e-aefa-81cce5743296
- failure run: https://buildkite.com/ray-project/release-tests-branch/builds/1428#0186b8d9-2d50-4340-942d-181b60bb9ac3


They have very similar node memory pattern: 
- Success: 
![image](https://user-images.githubusercontent.com/11676094/223292942-88b1f5eb-292e-42d9-8b34-a4b769eaabf1.png)

- Failure:
![image](https://user-images.githubusercontent.com/11676094/223293061-6f0d48da-336e-410d-81a3-566ee05eedba.png)


Also I think both have OOM killing happened. It just the failure seems to be running slower. And from the number of retries on the failure (retry 5 times all failed), it might not be a transient issue.

**Comment by rickyyx** [comment]
cc @jianoaix @clarng @scv119 @zcin

**Comment by clarng** [comment]
The OOM logs are expected (we get that even on green runs)

This is passing on master on v2 stack, we should patch in https://github.com/ray-project/ray/pull/32838 to 2.3.1

cc @jjyao

**Comment by clarng** [comment]
Latest runs on master is passing

https://buildkite.com/ray-project/release-tests-branch/builds/1426#0186a986-7048-43aa-bfff-86f4fda39923

https://buildkite.com/ray-project/release-tests-branch/builds/1431#0186b8fd-9af3-4462-ba81-0b6d19d5db1f

**Comment by amogkam** [comment]
@zcin's manual test with 2.3.1 and jobs+v2 stack is also passing.

Seems that this is an issue only with v1 stack, so going to close this issue.
