### ISSUE TITLE
[core][regression] stress_test_many_tasks stage 2 iteration time regressed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#33109]
### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/11676094/223539887-e3c351ee-7eb4-4149-a5ce-83a2aa6ddb12.png)

The regressed run:  https://buildkite.com/ray-project/release-tests-branch/builds/1422#0186a469-3543-48b5-8b93-72eb2babe6e9

```


success = 1
--
  | stage_0_time = 14.051025390625
  | stage_1_time = 209.2648332118988
  | stage_1_avg_iteration_time = 20.926473641395567
  | stage_1_max_iteration_time = 21.831929922103882
  | stage_1_min_iteration_time = 19.814006090164185
  | stage_2_time = 624.006796836853
  **| stage_2_avg_iteration_time = 124.80094919204711**
  | stage_2_max_iteration_time = 129.2098777294159
  | stage_2_min_iteration_time = 111.39928102493286
  | stage_3_creation_time = 4.525249004364014
  | stage_3_time = 2752.206174850464
  | stage_4_spread = 0.7294987588020061


```

Previously OK run:  https://buildkite.com/ray-project/release-tests-branch/builds/1420#01869f4c-afd4-4e0e-9e1f-931e175517a8

```


success = 1
--
  | stage_0_time = 12.599125623703003
  | stage_1_time = 234.92321872711182
  | stage_1_avg_iteration_time = 23.49231152534485
  | stage_1_max_iteration_time = 24.10273838043213
  | stage_1_min_iteration_time = 22.334192276000977
  | stage_2_time = 287.8835096359253
  | stage_2_avg_iteration_time = 57.57652711868286
  | stage_2_max_iteration_time = 58.57548189163208
  | stage_2_min_iteration_time = 54.61402702331543
  | stage_3_creation_time = 4.729832887649536
  | stage_3_time = 2623.647858142853
  | stage_4_spread = 0.7062336670593987


```

All the commits in between

fdf986615a [Serve] Expose FastAPI docs path (#32863)
4d0ce8d383 [Core] Write ray address even if ray node is started with --block (#32961)
bfba96c64e [Train] Fix failing `test_torch_trainer` (#32963)
ff66e0ef1b [AIR/Docs] Large model inference examples (#32874)
787865bbea Optimize submit Ray task with many positional arguments (#32478)
35153ff6f4 [Datasets] Fix typos in collate_fn error message (#32949)
69dede8af2 [Serve] Add Multi-App REST API (#32642)
ae665a3c7d [Train] Support returning multiple devices in `train.torch.get_device()` (#32893)
28753577f7 Streaming executor fixes #4 (#32882)

Bisecting with core changes. 

### Versions / Dependencies

NA

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
So this is the PR https://github.com/ray-project/ray/commit/787865bbeaf242e27adc7a4b249db13c6eeab77a


Thoughts on how we could fix the regression? 

cc @fyrestone @jjyao @rkooo567

**Comment by fyrestone** [comment]
So, which case is broken by my PR?

**Comment by fyrestone** [comment]
Is it means that submit task faster makes the execution slower?

**Comment by rickyyx** [comment]
stress_test_many_tasks's stage 2. 

I think it is submitting tasks with large number of  dependencies: https://github.com/ray-project/ray/blob/e56665ef6c686582683f0a6a090037bff26f058a/release/nightly_tests/stress_tests/test_many_tasks.py#L77

**Comment by rickyyx** [comment]
Closing the issue since it was reverted. Feel free to reopen with different labels for tracking.

**Comment by rkooo567** [comment]
My assumption is there's an edge case we didn't handle properly?

**Comment by fyrestone** [comment]
> My assumption is there's an edge case we didn't handle properly?

I will dig into this issue. Thanks.
