### ISSUE TITLE
[Serve] Allow loading different weights/versions onto a replica of ray serve deployment 

### ISSUE THREAD

**Issue by brosand** [ray-project/ray#33107]
### Description

Per https://discuss.ray.io/t/automating-the-serving-of-many-different-models/9573/4, I would like to be able to load different weights on replicas of a deployment, and route requests to the relevant replica based on the loaded weight. This would allow me to load a set of different models on to those deployments, and easily switch between them without having to create new deployments for each model.

This feature is not necessarily specific to weights, but rather to the core principle of many semi-identical deployments (all with the same use case). Another solve would be some way to live update the deployment graph without restarting the cluster, so that a new deployment could be added in, creating a new route for a user query.

Thanks in advance for helping with this.

### Use case

The use case that we would like to see supported is the ability to maintain a rayservice or running serve instance that can hold arbitrary models for a given model type. An example of this would be a service for GPT models, in which there are many different GPT models, and a user might wish to add a new model, and then route predict requests to that new model, while still allow the serving of the old models depending on the request, without shutting down and restarting the cluster/service.

**Comment by sihanwang41** [comment]
Hi @brosand, can you take a look https://github.com/ray-project/ray/issues/33253 ? We are gathering more comments & advance for the API, we hope it can cover your use case with this feature support.

**Comment by edoakes** [comment]
closing in favor of https://github.com/ray-project/ray/issues/33253
