### ISSUE TITLE
[data][streaming] Add benchmark for many file reading

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#33116]
In the current nightly test, we have tests that handle up to ~1000 files. However in real use cases from multiple users using streaming execution (or Datasets in general), they have tens of thousand of files on S3, and hit issues like metadata fetching.

We need to cover this scenario in our tests with a benchark to handle many files (e.g. 50k files on S3). Since the point is num of files instead of total bytes, we can generate many small files. We can use this util tool to generate S3 files: https://github.com/ray-project/ray/blob/master/release/nightly_tests/dataset/parquet_data_generator.py.

**Comment by c21** [comment]
Current Parquet benchmark: ray/release/nightly_tests/dataset/read_parquet_benchmark.py
