### ISSUE TITLE
Unable to build from source on Mac OSX 10.9

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#3315]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.9
- **Ray installed from (source or binary)**: source
- **Ray version**: current master
- **Python version**: 3.6
- **Exact command to reproduce**: -

### Describe the problem

This seems to be introduced from #3218. cc @pcmoritz 

### Source code / logs

```
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3.6  -DPYARROW_BUILD_PARQUET=on -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_BUILD_PLASMA=on -DPYARROW_USE_TENSORFLOW=on -DPYARROW_BUNDLE_ARROW_CPP=ON -DCMAKE_BUILD_TYPE=release /Users/DevinPetersohn/software_builds/ray/build/external/arrow/src/arrow_ep/python
    error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.7" but "10.9" during configure
```

**Comment by robertnishihara** [comment]
I think that line with `10.7` was added by @pcmoritz in https://github.com/ray-project/ray/pull/3218 to make it build on MacOS 10.14.

Note that we're seeing a similar error (but with 10.9 -> 10.14) in this comment https://github.com/ray-project/ray/pull/3218/files#r231489034 from @raulchen.

@pcmoritz do you know we actually need to set `MACOSX_DEPLOYMENT_TARGET` somewhere else as well (perhaps to 10.7)?

**Comment by pcmoritz** [comment]
@lucfisc Can you try if this fixes it for you? https://github.com/ray-project/ray/pull/3337
