### ISSUE TITLE
[Datasets] Deflake test_object_gc.py

### ISSUE THREAD

**Issue by c21** [ray-project/ray#33177]
### Description

there're two tests are flaky:

`test_iter_batches_no_spilling_upon_no_transformation`
`test_iter_batches_no_spilling_upon_transformations`

<img width="1659" alt="Screen Shot 2023-03-09 at 1 29 54 PM" src="https://user-images.githubusercontent.com/4629931/224164265-e581bb76-97f6-4a4d-9cf2-d147282629b2.png">

**Comment by jianoaix** [comment]
Duplicate with https://github.com/ray-project/ray/issues/32168

**Comment by c21** [comment]
Cool, closing this one.
