### ISSUE TITLE
[Dashboard] Provide better error messages when dashboard failed to start

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33172]
### What happened + What you expected to happen

Currently the error message is not helpful for users to debug. If possible, we should provide more details like possible reasons and how to fix them.

> Failed to start the dashboard , return code -11

https://github.com/ray-project/ray/issues/32312
https://github.com/ray-project/ray/issues/32693
https://discuss.ray.io/t/failed-to-start-the-dashboard-return-code-11/9665/3

### Versions / Dependencies

any

### Reproduction script

n/a

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
I don't know if it is true... When the dashboard fails to start we also print the log files. I don't think we can do anything better than this.

**Comment by rkooo567** [comment]
Looks like it was the user env issue (see the discussion), and we already should have clear error messages. Closing the issue for now.
