### ISSUE TITLE
[Dashboard] Stack trace for worker process in ray dashboard don't work on Windows

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33193]
### What happened + What you expected to happen

Tested stack trace with @pcmoritz on a Windows PC. It doesn't work but @pcmoritz has a fix for that. We should also make sure it works on WSL.

cc: @rkooo567 

![IMG_2462](https://user-images.githubusercontent.com/9677264/224209842-9ff6a5bd-54fd-44c9-a629-e02040db7cae.jpg)

### Versions / Dependencies

Ray 2.3

### Reproduction script

windows env

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by pcmoritz** [comment]
One easy fix that we tried, which fixes it on windows is to replace `$(which py-spy)` with `py-spy`

@rkooo567 Do you think that's the right way forward here? Would it cause other problems?

**Comment by rkooo567** [comment]
I assume py-spy vs $(which py-spy) is 99% of the time the same? @ericl curious if you know any difference? 

Also cc @mattip for ^ question.

**Comment by ericl** [comment]
The reason for the `which` is to resolve the absolute path for `sudo`. We could probably only do it for the sudo path.

**Comment by mattip** [comment]
> We could probably only do it for the sudo path.

That makes sense to me. In any case `py-spy` must be a binary inside the virtualenv/conda environment for windows since it uses python.

**Comment by mattip** [comment]
Grepping around for `which py-spy` shows two uses in `dashboard/modules/reporter/profile_manager.py` (the one from `trace-dump` in the error above and another in `cpu_profile`) and one in `python/ray/scripts/scripts.py` in the `stack` CLI command, which also hard-codes use of sudo.

**Comment by pcmoritz** [comment]
I created a fix for the dashboard in https://github.com/ray-project/ray/pull/33366 :)
