### ISSUE TITLE
[docs] document @serve.deployment parameters in the API ref

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#33191]
### Description

It's not easy to find the parameters for @serve.deployment in the API ref, specifically, the num_replicas argument for serve.deployment. It's mentioned this guide: https://docs.ray.io/en/latest/serve/production-guide/config.html#overriding-deployment-settings
It seems to make sense to have this in the API ref. 

The only place I found the deployment schema was in the JSON in - https://docs.ray.io/en/latest/serve/api/rest_api.html#config-schema and the autoscaling parameters here - https://docs.ray.io/en/latest/serve/scaling-and-resource-allocation.html#autoscaling-config-parameters

cc: @akshay-anyscale @edoakes @sihanwang41 @pcmoritz @shrekris-anyscale

**Comment by akshay-anyscale** [comment]
I believe this is resolved in @edoakes latest PR - https://github.com/ray-project/ray/pull/34711
