### ISSUE TITLE
[data][streaming] Support epoch in streaming Dataset

### ISSUE THREAD

**Issue by jianoaix** [ray-project/ray#33205]
Currently, if users want to run multiple epoch on the same Dataset, they use `ds.repeat(N)`. This will return a `DatasetPipeline` which is a series of N original dataset.

We need this similar support in streaming Dataset (without using `DatasetPipeline`). We have early users of streaming Dataset ask for this feature.

**Comment by jianoaix** [comment]
We can work around this by repeating the dataset like `datasets = [ds] * N` for N epochs.
The main drawback is that there will be no overlapped processing across epochs.

**Comment by ericl** [comment]
Duplicate of https://github.com/ray-project/ray/issues/33008 (and DataIterator integration)
