### ISSUE TITLE
[core][perf] single_node large_object_time regression

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#33202]
### What happened + What you expected to happen

`large_object_time` from test `single_node` regressed ~50% (consistently across three runs) between 2.3.0 and 2.3.1
From 325 -> 487
https://github.com/ray-project/ray/pull/33197/files#diff-656f13e098270dac02931057378e430f823d210eba57f3eff0361cc39f4cb944L5-R5

### Versions / Dependencies

2.3.0, 2.3.1

### Reproduction script

Run 1: https://buildkite.com/ray-project/release-tests-branch/builds/1434#0186bf18-9f5d-4ea9-a263-18024c8a709e
Run 2: https://buildkite.com/ray-project/release-tests-branch/builds/1439#0186c949-483f-41b3-bc4e-011798f8b759
Run 3: https://buildkite.com/ray-project/release-tests-branch/builds/1440#0186c9c4-f90d-4302-a794-bd0aec40763d

### Issue Severity

None

**Comment by cadedaniel** [comment]
Can we kick off some more runs on `2.3.0`? The hypothesized underlying issue is increased network latency in EBS due to an AWS-internal change. If this is true, then `2.3.0` will see consistently elevated rates as well.

**Comment by zcin** [comment]
Sure, I'll try that.

**Comment by zcin** [comment]
Tested `single_node` on the v2 stack using 2.3.0 and 2.3.1 wheels, there is no performance regression seen there. Closing this as @rickyyx and @scv119 believe this is likely not an actual regression, and instead due to v1 infra issues.
