### ISSUE TITLE
[Dependencies] [runtime_env] Upgrade the version of boto3 (AWS Python SDK)

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#33256]
### Description

The version of `boto3` included in the Ray image is outdated. For instance, while the `rayproject/ray:2.3.0` image provides boto3 version 1.4.8 (Nov. 21, 2017), a more recent version (1.26) is currently available as per https://pypi.org/project/boto3/#history.

It may be painful for users want to use AWS on Ray Pods. For example, users want to download their S3 buckets via boto3 in Ray Pods. `boto3` should initialize the credentials automatically by reading some environment variables. However, `boto3` 1.4.8 is too old, so it will not do it automatically.

<details>
<summary>script 1</summary>

```python
import boto3

s3 = boto3.client('s3')
bucket_name = $BUCKET_NAME
key = $OBJECT_KEY
filename = $FILENAME

s3.download_file(bucket_name, key, filename)
```
</details>

<details>
<summary>script 2</summary>

```python
import os
import boto3
def assumed_role_session():
    role_arn = os.getenv('AWS_ROLE_ARN')
    with open(os.getenv("AWS_WEB_IDENTITY_TOKEN_FILE"), 'r') as content_file:
        web_identity_token = content_file.read()
    role = boto3.client('sts').assume_role_with_web_identity(RoleArn=role_arn, RoleSessionName='assume-role',
                                                             WebIdentityToken=web_identity_token)
    credentials = role['Credentials']
    aws_access_key_id = credentials['AccessKeyId']
    aws_secret_access_key = credentials['SecretAccessKey']
    aws_session_token = credentials['SessionToken']
    return boto3.session.Session(aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,
                              aws_session_token=aws_session_token)

session = assumed_role_session()
s3 = session.client("s3")
bucket_name = $BUCKET_NAME
key = $OBJECT_KEY
filename = $FILENAME
s3.download_file(bucket_name, key, filename)
```
</details>

This is very painful for users: 
* It is hard to debug.
* Users need to rewrite their boto3 scripts.

I simplify a lot of context in this issue. See this [link](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1678303095557969) for more context.

**Comment by kevin85421** [comment]
While I believe this issue should be labeled as P0, I think it would be best to leave the final decision to the community.

**Comment by kevin85421** [comment]
It is more serious than my first thought. If users want to download `working_dir` via their private S3 buckets in RayService, **runtime environment** will use `boto3` to download the `working_dir`. However, the request will be denied. See https://github.com/ray-project/kuberay/pull/958#discussion_r1134613211 for more details.

<img width="1354" alt="Screen Shot 2023-03-13 at 3 14 43 PM" src="https://user-images.githubusercontent.com/20109646/224844673-04da701e-ae38-4e0f-822a-d5f3b5ab7112.png">

Reproduce:
* Update `working_dir` to point to a private S3 bucket.
* Log in to the head Pod, and run `serve status`.

**Comment by kevin85421** [comment]
cc @gvspraveen @architkulkarni

**Comment by architkulkarni** [comment]
@kevin85421 Thanks for the investigation and for filing this!  Based on the hypothesis, it sounds like this isn't a recent regression though, right? I'm trying to figure out why we haven't seen this issue before

**Comment by kevin85421** [comment]
> Based on the hypothesis, it sounds like this isn't a recent regression though, right? I'm trying to figure out why we haven't seen this issue before

Some possible reasons:
* Users use public S3 buckets on EKS.
* Users use other protocol instead of S3.

**Comment by architkulkarni** [comment]
cc @sihanwang41 could you help assign a priority here? I guess it's P0 or P1, depending on how common/important the workflow is among Serve users

**Comment by architkulkarni** [comment]
I guess this isn't Serve-specific, it affects any user of `runtime_env` with an S3 url.  It looks like our official position in the docs is that we tell the user to install `boto3` themselves. (`boto3` isn't part of `requirements.txt` so it isn't installed when a user runs `pip install "ray[all]"`, but it does appear in the Docker image, @ijrsvt do you know if there's any danger in upgrading this?)  https://github.com/ray-project/ray/blob/52f406a2ce4bb1081c4c5a1e9297b82e5f67f58a/docker/ray-deps/Dockerfile#L17 
I don't know if we have a policy of including more dependencies in the Ray images than you get when installing Ray with `pip`, but I think it makes sense to upgrade the version here since we seem to be including it already.

**Comment by ijrsvt** [comment]
@architkulkarni Should be fine--Boto3 is very cautious about maintaining backwards compatability.
