### ISSUE TITLE
[Dataset] Random Access Dataset returns None on transformed Datasets

### ISSUE THREAD

**Issue by mattsgithub** [ray-project/ray#33266]
### What happened + What you expected to happen

**The Bug**
If you read a dataset from parquet, run a transformation (e.g., `select_columns`), and then run `ds.to_random_access_dataset(....)` you will find the returned records tend be `None`. If no transformations are applied, it works fine.

**Expected Behavior**
`ds.to_random_access_dataset` should return values for the supplied keys regardless if data transformations are applied or not.

**Summary**
When using the random access dataset in Ray, I found if you read a dataset from parquet and do a transformation (select_columns, impute, etc) and then run `ds.to_random_access_dataset`--the returned values for keys will be None. However, if no transformations are applied, it works correctly.

A guaranteed way to always get the right behavior is to run map_batches:
```python
ds = ds.map_batches(fn=lambda batch: batch, batch_format="pyarrow")
```

before running ds.to_random_access_dataset . If you do this, everything will work correctly. The list of batch_formats are _pyarrow_, _numpy_, and _default_. If I change the previous line to have batch_format of default, you will recover the bug.

If you look at the source code of random_access_dataset in Ray, there is this check
```python
self._format = dataset.dataset_format()
if self._format not in ["arrow", "pandas"]:
	raise ValueError("RandomAccessDataset only supports Arrow-format datasets.")
```
But this check is not sufficient to guarantee that all block formats are either pyarrow or numpy. There might be a simple way in Ray to check the block formats (e.g., `get_internal_block_refs()`, `BlockAccessor`).

### Versions / Dependencies

**Versions / Dependencies**
**Ray:** 2.2.0
**Python:** 3.8
**Cluster**: 10 CPU nodes / 1 GPU node
**Base image**: rayproject/ray-ml:2.2.0-py38-gpu@sha256:8699c155ccebcff0a04c832fd10d8ae0ea444c0b123a9037029e4f23ea703fb5

### Reproduction script

```python
"""
- The dataset I'm working has about ~200 million rows
- Each parquet file is ~25 MB
- There are ~65 parquet files for the dataset
- The node index column is a unique integer starting from 0 and up to N - 1 where N is the number of rows
"""
from gcsfs import GCSFileSystem
fs = GCSFileSystem()
ds = ray.data.read_parquet(f"gs://......", filesystem=fs)
ml_features = ["f1", "f2"]
metadata = ["node_index"]
ds = ds.select_columns(metadata + ml_features)
ds = ds.to_random_access_dataset(key="node_index")

# Returns None for each record
result = ds.multiget([0, 10, 100, 1000)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by c21** [comment]
Thanks @mattsgithub reporting!

**Comment by denadai2** [comment]
fyi This issue is still valid :(

**Comment by denadai2** [comment]
@c21 just to clarify, are you closing it because RandomAccessDataset will be discarded in the future?
