### ISSUE TITLE
[Data] `grouped_ds.aggregate` does not execute the dataset plan 

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#33280]
### What happened + What you expected to happen

This docstring says that calling `aggregate` will trigger execution of my data pipeline. But, calling it on a grouped dataset seems to just return the plan rather than execute anything. This may just be outdated documentation.

https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.aggregate.html#ray-data-dataset-aggregate

### Versions / Dependencies

2.3.0

### Reproduction script

```python
import ray

ds = ray.data.read_parquet(
    "s3://anonymous@m5-benchmarks/data/train/target.parquet",
    columns=["item_id", "timestamp", "demand"]
)
[sample] = ds.take(1)
print(ds.take(1))  # `item_id` is clearly a string
print("\nitem_id type:", type(sample["item_id"]))

print("\n schema:", ds.schema()) # Schema shows it being a dict with string as a value

grouped_ds = ds.groupby("item_id")
# Doesn't work because sort doesn't work on a dict
# Sort + shuffle involved in the groupby
aggregated = grouped_ds.aggregate(ray.data.aggregate.Count())
print("\nplan:", aggregated)  # This thing is a plan instead of fully executing.
# Docstring says otherwise

# I have to call take for this to execute
aggregated.take(1)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by c21** [comment]
@justinvyu - actually I think you should refer to this API page - https://docs.ray.io/en/latest/data/api/doc/ray.data.grouped_dataset.GroupedDataset.aggregate.html . `GroupedDataset` is different from `Dataset`.

**Comment by c21** [comment]
Closing this but let me know if you are still seeing the issue, thanks.
