### ISSUE TITLE
[core] unpin libffi=3.3 once conda resolves the dependency issue

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#33299]
### What happened + What you expected to happen

as title, we should unpin it once the root cause is resolved. https://github.com/ray-project/ray/pull/33294 

blocked by https://github.com/conda/conda/issues/12287#issuecomment-1443016695

### Versions / Dependencies

latest

### Reproduction script

latest

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scv119** [comment]
nothing we can do here. the root cause seems not fixed yet.

**Comment by can-anyscale** [comment]
@rickyyx this issue will probably block docker build for python 3.11 (https://github.com/ray-project/ray/blob/master/docker/base-deps/Dockerfile#L60), libffi=3.3 is not compatible with python 3.11

**Comment by rickyyx** [comment]
maybe we could try unpinning it?

**Comment by jjyao** [comment]
Fixed by #41339
