### ISSUE TITLE
[rllib] Best way to access Q values with DQN

### ISSUE THREAD

**Issue by nflu** [ray-project/ray#3330]
What is the best way to access the Q values of a state (state meaning a state in the MDP not the state of the model) of a DQN Agent? 

The `DQNPolicyGraph` class has an instance attribute `self.output_actions` but I don't see any instance attribute that has the Q values.

One thing I considered was loading the parameters from the `policy_map` of the evaluator and then constructing a graph to use them, but that seems like redoing a lot of work already done in the `DQNPolicyGraph` class.

**Comment by ericl** [comment]
Hey @nflu, indeed the q values are private to that class. The best way to get around this would be to modify the graph class in the source code (this requires rebuilding ray, or editing the locally installed files).

**Comment by nflu** [comment]
Thanks. I was just curious if there was any built in feature to get them that didn't require editing the source code.

**Comment by mynkpl1998** [comment]
@nflu Hey, Can you share the code snippet to access q values ?
Thanks.

**Comment by junkudo** [comment]
@nflu  @ericl  - is this still the current approach we should take to access the q values?

**Comment by junkudo** [comment]
Never mind! I think the documentation resolves this :) https://docs.ray.io/en/releases-0.8.0/rllib-training.html
