### ISSUE TITLE
[Data] `map_batches` progress bar percentage doesn't get to 100% and exits

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#33317]
### What happened + What you expected to happen

The progress bar seems to track progress based on `num_output_blocks_written / num_input_blocks`, but this leads to an incomplete progress bar when the map batches finishes. Functionality is right, displayed progress is just wrong.

### Versions / Dependencies

2.3.0

### Reproduction script

```python
>>> preds = ds.map_batches(do_prediction, batch_format="numpy")
MapBatches(PredictCallable), 0 actors [34 locality hits, 0 misses]:  17%|█████████                                            | 34/200 [00:37<03:01,  1.09s/it]
>>> preds
Dataset(num_blocks=34, num_rows=3925, schema={predictions: ArrowTensorType(shape=(1000,), dtype=float)})
>>> ds
Dataset(num_blocks=200, num_rows=3925, schema={image: ArrowTensorType(shape=(3, 224, 224), dtype=float)})
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by c21** [comment]
@justinvyu - just wondering is same issue happening on master as well? Could you help give a try? Also could you share the full script? Thanks.

**Comment by bveeramani** [comment]
Asked Justin about this over Slack. To reproduce:

```
git clone -b doc/example_templates https://github.com/justinvyu/ray.git .
cd doc/source/examples/01_batch_inference
```

Run `batch_inference.ipynb`
