### ISSUE TITLE
[Ray Datasets] More actors are created than what's specified by ActorPoolStrategy in DatasetPipeline

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#33354]
### What happened + What you expected to happen

Datasets transformations fixed-size actor pool is not working with window pipeline.
When I use ActorPoolStrategy with window and pipeline, actor poll size is not fixed and the actor is frequently killed and initialized.
Expect the actor pool size is fixed and can be reused.

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/16042235/225500385-508afc1e-9884-41d7-854f-1be210f01743.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/16042235/225501257-551f4a5b-662f-498d-a3b5-5c0bf78e26ab.png">

### Versions / Dependencies

ray, version 2.2.0

### Reproduction script

```python
import ray
import pandas
import numpy
from ray.data import ActorPoolStrategy
import time

# Dummy model to predict Iris variety.
def predict_iris(df: pandas.DataFrame) -> pandas.DataFrame:
    time.sleep(3)
    conditions = [
        (df["sepal.length"] < 5.0),
        (df["sepal.length"] >= 5.0) & (df["sepal.length"] < 6.0),
        (df["sepal.length"] >= 6.0)
    ]
    values = ["Setosa", "Versicolor", "Virginica"]
    return pandas.DataFrame({"predicted_variety": numpy.select(conditions, values)})

class IrisInferModel:
    def __init__(self):
        self._model = predict_iris
        print("=====IrisInferModel init=====")
        time.sleep(1)

    def __call__(self, batch: pandas.DataFrame) -> pandas.DataFrame:
        return self._model(batch)

ds = ray.data.read_csv("example://iris.csv").repartition(150)

# method1: not window, not pipeline, ActorPoolStrategy workers well, there are fixed-size actor pool
# predicted = ds.map_batches(
#     IrisInferModel, compute=ActorPoolStrategy(3, 3), batch_size=1).fully_executed()

# method2: with window and pipeline, actor poll size is not fixed and the actor is frequently killed and initialized
predicted = ds.window(blocks_per_window=1).map_batches(
    IrisInferModel, compute=ActorPoolStrategy(3, 3), batch_size=1)

for batch in predicted.iter_batches():
    print(batch)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by c21** [comment]
cc @jianoaix

**Comment by jianoaix** [comment]
This seems like https://github.com/ray-project/ray/issues/26396. The current recommendation is using the new streaming executor: https://docs.google.com/document/d/1BXd1cGexDnqHAIVoxTnV3BV0sklO9UXqPwSdHukExhY/edit#. @v4if

**Comment by v4if** [comment]
> This seems like #26396. The current recommendation is using the new streaming executor: https://docs.google.com/document/d/1BXd1cGexDnqHAIVoxTnV3BV0sklO9UXqPwSdHukExhY/edit#. @v4if

Thanks. Streaming executor exactly what is needed. And is DatasetPipeline will be deprecated?

**Comment by jianoaix** [comment]
Yep, deprecation will follow once streaming executor is fully landed.
