### ISSUE TITLE
can find the import modulefrom ray.test.cluster_utils import Cluster

### ISSUE THREAD

**Issue by stellaxu** [ray-project/ray#3335]
When I run 'train.py' in rllib, I find that there is an additional import code compared with the previous one:
"from ray.test.cluster_utils import Cluster". 

I tried all of the ways of installing ray in the documentation, but the issue still exists.

Finally, I comment this sentence, and it works smoothly.

However, what about this code's function and why the system cannot find this import module?

Thxs.

Weinan

**Comment by richardliaw** [comment]
This should be addressed in person already. Feel free to reopen if issues arise.
