### ISSUE TITLE
[AIR] Persisted `Checkpoint` format is unclear

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#33362]
**User Journey:** I want to persist a `Checkpoint` from one script and load it back in another.

**Example Workflow:**
1.  Create a simple dictionary checkpoint.
```python
from ray.air import Checkpoint

checkpoint = Checkpoint.from_dict({"key": "value"})
checkpoint.to_directory("my_checkpoint")
```

2. Check output directory structure.
```
.
└── my_checkpoint
    └── dict_checkpoint.pkl
```

3. Load checkpoint back into memory.
```python
from ray.air import Checkpoint

checkpoint = Checkpoint.from_uri("my_checkpoint")
data_dict = checkpoint.to_dict()
```

4. Verify contents of the result.
```python
print(data_dict)
```
```python
{'key': 'value', '_metadata': _CheckpointMetadata(checkpoint_type=<class 'ray.air.checkpoint.Checkpoint'>, checkpoint_state={})}
```
**Issues/Confusion:**
1. There are numerous entrypoints for creating a `Checkpoint`.
2. It is not clear how to persist a `Checkpoint`.
3. It is not clear what the format of the written directory checkpoint is.
    - Specifically, what the difference between `my_checkpoint` and `dict_checkpoint.pkl` is.
4. It is not clear how to load a checkpoint into memory.
    - In this example, both `from_directory` and `from_uri` work.
5. The final dictionary contains additional metadata that I did not expect to be included based on what I wrote.
6. More generally, there is little documentation working with pure `Checkpoint` objects.
    - The [API reference](https://docs.ray.io/en/latest/ray-air/api/checkpoint.html) does not contain sufficient information to interact with a `Checkpoint` throughout its lifecycle.

**Suggestions:** 
1. A User Guide can be added to describe the different ways of interacting with a `Checkpoint`.
2. In the long run, we may want to simplify the `Checkpoint` API so that it is more intuitive.

**Comment by ericl** [comment]
We've also had a long outstanding todo to save each key as a separate file, right?

**Comment by matthewdeng** [comment]
Oops @ericl missed your comment. Could you share more context/motivation on this todo?

**Comment by ericl** [comment]
I'm also forgetting a bit of the context here, unfortunately.  It seems potentially more robust as you can independently load and save each key.
