### ISSUE TITLE
Redis module datastructures

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3336]
Currently we use ZSets to store our GCS datastructures. They require the keys to be unique which is not always the case in practice (e.g. for duplicate error messages).

We should consider using redis datastructures that allow duplicate entries, for example streams (https://redis.io/topics/streams-intro)

See https://github.com/ray-project/ray/commit/1be1455d869860e0ce0f9aadfdf38bffd6f7260b#diff-1ed7548b25e1646a9d4b87c8392f550aR314

A workaround for this was implemented in https://github.com/ray-project/ray/pull/3316

**Comment by robertnishihara** [comment]
I think Redis lists would also work for this purpose.
