### ISSUE TITLE
[core] Multiprocessing interactions with Ray

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#33398]
### What happened + What you expected to happen

We're seeing quite a few github issues with people reporting the inability to use multiprocessing with Ray. 

This issue aims to collect them all together.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

**Comment by kimjoyc** [comment]
How can we help with this? We are looking to see if there were any parallel computing tasks to contribute onto this repository. 

@hmk46 @depetrol
