### ISSUE TITLE
[Autoscaler] No workers started if --num-cpus is set to 0 on the head

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#3339]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **Ray installed from (source or binary)**: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
- **Ray version**: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
- **Python version**: 3.6.6
- **Exact command to reproduce**:  `ray up` with head node `--num-cpus 0` and worker node `--num-cpus 27`, `min_workers 0`, then try run the following code on the head:

```
@ray.remote
class Actor:
    def run(self):
        return 42

actors = [Actor.remote() for _ in range(5)]
ray.get([a.run.remote() for a in actors])
```

### Describe the problem
We expect in this scenario for one or more workers to be automatically spawned, however instead we get the following error messages from the Python `ray.get` process:

```
The task with ID 00000000c13adb2667e43e58be4c3df9e8162c58 is infeasible and cannot currently be executed. It requires {CPU,0.000000} for execution and {CPU,1.000000} for placement. Check the client table to view node resources.
The task with ID 000000006fe30c263f11b0ef55347db054002d13 is infeasible and cannot currently be executed. It requires {CPU,0.000000} for execution and {CPU,1.000000} for placement. Check the client table to view node resources.
The task with ID 000000005b742b846ed2c74a549e0d7df6ec86a0 is infeasible and cannot currently be executed. It requires {CPU,0.000000} for execution and {CPU,1.000000} for placement. Check the client table to view node resources.
The task with ID 0000000035996220855b0b6e9d23155dd1b8d7a7 is infeasible and cannot currently be executed. It requires {CPU,0.000000} for execution and {CPU,1.000000} for placement. Check the client table to view node resources.
The task with ID 00000000c577c4cf7ff646d6f907fbd69b59653e is infeasible and cannot currently be executed. It requires {CPU,0.000000} for execution and {CPU,1.000000} for placement. Check the client table to view node resources.
```

And the following output in monitor.err on the head node:

```
StandardAutoscaler [2018-11-16 16:30:39.881507]: 0/0 target nodes (0 pending)
 - NodeIdleSeconds: Min=196 Mean=196 Max=196
 - NumNodesConnected: 1
 - NumNodesUsed: 0.0
 - ResourceUsage: 0.0/0.0 b'CPU', 0.0/0.0 b'GPU'
 - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
```

Note that new nodes are booted if there are >0 `--num-cpus` on the head, although we've intentionally underspecced the head node so that we can run it long term, but not have it running any jobs (hence `--num-cpus` 0).  The advantage here is we can kick a job off overnight and leave the system running --- the more expensive worker instances will self-terminate when the job is finished, while the cheap head node will be waiting with results in the morning.

**Comment by mattearllongshot** [comment]
Perhaps a slightly separate issue too, but related, from inspecting the autoscaler code it looks as if the number of target workers (`target_num_workers`) is based on the current number of nodes used (`cur_used`) divided by `target_frac` (0.8 by default).

Seeing as `cur_used` is always going to be less than the number of booted nodes, and 1 / 0.8 = 1.25, does this mean that the number of extra nodes to be booted will only 25% more than the currently booted number?  So it could take many iterations to get up to 90 nodes or so?

Let me know if I've misunderstood, and thanks in advance for your help.

**Comment by mattearllongshot** [comment]
Ah yes, looks like that one.  Thanks!  Is a fix for this scheduled?  We were planning on having a light-weight head node with 0 min-workers, and then having the workers scale up  and down (based on queued jobs) so a fix for this would fit the bill perfectly.

**Comment by richardliaw** [comment]
I think #3530 is a nice workaround for this - closing for now.
