### ISSUE TITLE
Redirecting All Ray Logging to a single file

### ISSUE THREAD

**Issue by amohar2** [ray-project/ray#33418]
### What happened + What you expected to happen

Is there a way to redirect all Ray logs (from workers, actors, monitoring, dashboard, etc.) to a single file defined by the user?
I found this reference which shows how to redirect the logs to stderr but I was wondering if I can provide a custom filename instead: [Logging — Ray 2.3.0 1](https://docs.ray.io/en/latest/ray-observability/ray-logging.html#redirecting-ray-logs-to-stderr)

Also, what if I want to redirect the logs from other nodes to a single file on the head node? Is there a way to accomplish this goal?

Finally, if the user can redirect the logs to a single file, does that mean the logging directory created under /tmp/ directory will not be created? In my environment there are restrictions on writing to disk, so I want to avoid writing to disk space as much as possible

### Versions / Dependencies

Ray 2.3.0

### Reproduction script

Will be updated

### Issue Severity

None

**Comment by rkooo567** [comment]
> Also, what if I want to redirect the logs from other nodes to a single file on the head node? Is there a way to accomplish this goal?

We don't plan to support this natively. I think the best way to achieve this is to use redirect_to_stderr env var, and then you capture them + write to a single file manually. 

> Finally, if the user can redirect the logs to a single file, does that mean the logging directory created under /tmp/ directory will not be created? In my environment there are restrictions on writing to disk, so I want to avoid writing to disk space as much as possible

I don't think so. There are other files that are needed under this directory. The contents under /tmp/ray/session_*/logs will be empty.
