### ISSUE TITLE
[installation] grpc conflict for Ray due to ray 2.3

### ISSUE THREAD

**Issue by creamiracle** [ray-project/ray#33417]
### What happened + What you expected to happen

The situation here is:
1. At 2022/12, we built a dockerfile to use ray, which contains "**centos7+jdk1.8.0_u20+ray2.0**", everything went well at that time.
2. At 2023/03, we need to update java version to fit our new recommends, but something goes wrong here, the image contains "centos7+jdk1.8.0_u191+ray2.3", and when we use `"ray start"`, we get error "Waiting for thread pool to idle before forking".
3. After checking the issue here: https://github.com/grpc/grpc/issues/31885, we find that the reason is **grpcio**, which version is 1.52.0(installed automaticlly, seems installed by ray), and we change it to **1.48.2**, then the bug is fixed.
So, I think maybe there should be some tips for this package when using the new ray.

### Versions / Dependencies

centos7+jdk1.8.0_u20+ray2.0

### Reproduction script

see above

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
Thanks for reporting. I think for now we will take no actions here for now unless others report it.

**Comment by rickyyx** [comment]
So seems this is happening not just on macOS.... 

See this as well: https://github.com/ray-project/ray/issues/30984#issuecomment-1471715389

@scv119
