### ISSUE TITLE
[Release][Core] Migrate core test to v2 stack and Anyscale Jobs 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#33414]
### What happened + What you expected to happen

Details are in this PR https://github.com/ray-project/ray/pull/33288

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rickyyx** [comment]
This is currently blocked by this: https://github.com/ray-project/ray/issues/33891

**Comment by rkooo567** [comment]
OSS side work is done, and we migrate all tests back now. However, the squashfs issue hasn't been resolved
