### ISSUE TITLE
[Tune]  TuneReportCallback raising a ValueError in Lightning 2.0

### ISSUE THREAD

**Issue by adamgayoso** [ray-project/ray#33426]
### What happened + What you expected to happen

By upgrading to lightning 2.0, we are seeing the following error with the use of Ray's `TuneReportCallback`

```
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 421, in __init__
    self._callback_connector.on_trainer_init(
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py", line 79, in on_trainer_init
    _validate_callbacks_list(self.trainer.callbacks)
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py", line 252, in _validate_callbacks_list
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/callback_connector.py", line 252, in <listcomp>
    stateful_callbacks = [cb for cb in callbacks if is_overridden("state_dict", instance=cb)]
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/lightning/pytorch/utilities/model_helpers.py", line 34, in is_overridden
    raise ValueError("Expected a parent")
ValueError: Expected a parent
```

which is derived from here 

https://github.com/Lightning-AI/lightning/blob/1156eb74aef23fa1a43069d20e652ba5a9dfd77e/src/lightning/pytorch/utilities/model_helpers.py#L22-L34

### Versions / Dependencies

ray==2.2.0
lightning==2.0.0

### Reproduction script

Sorry I do not have an easily reproducible script, but I will test if it happens with a tutorial on the ray docs site.

### Issue Severity

High: It blocks me from completing my task.

**Comment by dcheney01** [comment]
I have the same problem
ray==2.3.0
lightning==2.0.0

when defining the trainer with the TuneReportCallback it throws the same error mentioned above. When I do not include the callback, I get
`ValueError: Trial returned a result which did not include the specified metric(s) `loss` that `tune.TuneConfig()` expects." which is expected`

This is how I am defining the trainer. 
```
trainer = pl.Trainer(
                        max_epochs=config['max_epochs'], 
                        callbacks=[
                                TuneReportCallback(
                                    metrics={
                                        "loss": "val_loss",
                                        "mean_accuracy": "val_accuracy"
                                    }
                                    )
                                    ]
                        )
```

**Comment by gjoliver** [comment]
@woshiyyya multiple reports. do you mind take a look since you are working on PTL these days?

**Comment by blacksnail789521** [comment]
Here's a polished version of your text:

I am using `TuneReportCheckpointCallback` and encountering the same error, even after downgrading `lightning` to version 1.9.0. I suspect that the issue arose from changing the import statement from `import pytorch-lightning as pl` to `import lightning as L`.

**Comment by woshiyyya** [comment]
Can you try to `pip install pytorch_lightning==2.0.0` so that the import path should be correct.

**Comment by adamgayoso** [comment]
I will try but I thought pip install lightning also installs pytorch_lightning exactly for this reason.

**Comment by adamgayoso** [comment]
I am using this as a workaround:

```
class _TuneReportCallback(TuneReportCallback, pl.Callback):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

however, it would be great to refactor the imports perhaps to try to import via lightning paths and then fallback to pytorch_lightning

https://github.com/ray-project/ray/blob/069586377a4d7b7ed3a3345b7d3efc238f1a7359/python/ray/tune/integration/pytorch_lightning.py#L5

**Comment by crazyn2** [comment]
Same issue. Looking forward to its solution.

**Comment by woshiyyya** [comment]
Close this issue since we've migrated to the TorchTrainer API, which provides supports for Lightning 2.0.
