### ISSUE TITLE
[AIR][RLlib] Any solutions to train Large Language Models with RLHF on Ray?

### ISSUE THREAD

**Issue by weberxie** [ray-project/ray#33436]
### Description

Training LLM with RLHF, the number of parameters of LLM may be up to 175B.

**Comment by Yard1** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
I believe this is a duplicate of #33021 . Closing this here, let's continue the conversation there!

**Comment by zhanghaoie** [comment]
Any updates?
