### ISSUE TITLE
[CI] `linux://:gcs_client_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#33475]
- f59cbd63e0caaa0cb5ce1887b6cf2652dcfc77d5 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2821#018700b3-f3cc-4649-9f46-e2160abd6492)
- 52f0ee8934499d1bfa2824c3a4528aecae49e687 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2816#0186fff9-2ebd-4a6a-8a56-86735173c62c)
- ed2982f3fb01f42e38ed23530f32191028bff86c FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2814#0186ffe0-52c2-4768-8bf2-3ddd8b4ec945)
- 6f27610543477e7b28acebe42dce6548b7b71e03 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2810#0186fb8b-823e-4761-bb2f-7cdbc8685285)
- 9e81c1404ba97ec84124719de08d4cb42375eb76 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2809#0186fb8b-5507-4a71-a976-b175ac1cf13a)
- 872896f2117c9f2b17818cf7c370d0ef95efbc8a FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2808#0186fb8b-66c4-431e-87d9-28cbb67cd5da)
- 46bd490b88f1a66927a15e77a295c2159505334c FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2795#0186f053-95ed-404b-9576-e1a85d89d743)
- 76fd2cdffc77ddb638c57624d9cf46eb192856d2 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2790#0186ee33-18e7-4b3f-a8d1-357ae86ffd34)
- 327bdfb924387e5ec8ff1083027d08eb3729ca8a FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2780#0186ec93-32f3-4749-ac89-a228dc37ac05)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:gcs_client_test-END
....

**Comment by rkooo567** [comment]
cc @iycheng

**Comment by iycheng** [comment]
The test seems hard to reproduce. 

```
//:gcs_client_test                                                        FLAKY, failed in 1 out of 101 in 62.2s
```
It seems that the destruction got some issues.

**Comment by rkooo567** [comment]
Have you tried with the repro_ci.py? Maybe it is easier to repro that way?

**Comment by iycheng** [comment]
> Have you tried with the repro_ci.py? Maybe it is easier to repro that way?

I'm trying with repro_ci.py
