### ISSUE TITLE
[CI] Unclear failure message: `Command returned non-success status: 137`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#33493]
Seeing this in a few different tests in the same weekly test run:
* https://buildkite.com/ray-project/release-tests-branch/builds/1453#0186f87a-ee23-4d7a-a2a2-2a8f647e1e8a
* https://buildkite.com/ray-project/release-tests-branch/builds/1453#0186f87a-ee26-4ebc-ae65-213d5b75bfd0
* https://buildkite.com/ray-project/release-tests-branch/builds/1453#0186f87a-ee2c-478d-9944-804b1d33f9e7
* https://buildkite.com/ray-project/release-tests-branch/builds/1453#0186f87a-ee2f-49a0-aabf-c2f4d4bdd3e2
* https://buildkite.com/ray-project/release-tests-branch/builds/1453#0186f87a-ee31-4e1f-9286-9c54288c5ea7 (this one also has some grpc failure messages but I am 90% confident those are expected in this test)

```
[ERROR 2023-03-19 01:26:03,953] glue.py: 420  Command returned non-success status: 137
--
  | Traceback (most recent call last):
  | File "/tmp/release-ueEKWd3mnO/release/ray_release/glue.py", line 364, in run_release_test
  | raise_on_timeout=not is_long_running,
  | File "/tmp/release-ueEKWd3mnO/release/ray_release/command_runner/sdk_runner.py", line 160, in run_command
  | raise CommandError(f"Command returned non-success status: {status_code}")
  | ray_release.exception.CommandError: Command returned non-success status: 137
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/tmp/release-ueEKWd3mnO/release/ray_release/glue.py", line 374, in run_release_test
  | raise TestCommandError(e)
  | ray_release.exception.TestCommandError: Command returned non-success status: 137
```

**Comment by cadedaniel** [comment]
cc @can-anyscale @aslonnie for triaging

**Comment by aslonnie** [comment]
stale now.
