### ISSUE TITLE
[Core] apparent `many_nodes` perf degredation

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#33492]
Need to investigate and understand why we see a throughput drop.

<img width="689" alt="Screen Shot 2023-03-20 at 5 39 51 PM" src="https://user-images.githubusercontent.com/950914/226494563-29076576-a1d2-4b25-959d-832de228135d.png">

**Comment by jjyao** [comment]
For the same wheel, same v1 stack, two runs have completely different perf:



https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_az6t3jfgujvf6c22gylz1vd8gc: "tasks_per_second":6.933557980640119

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_2vsy5hhye3jvnd4mefl6wmiszr:
tasks_per_second = 203.0012778376907

**Comment by clarng** [comment]
Seems like the way we calculate the rate is sensitive to noise:

rate = num_tasks / (end_time - start_time - sleep_time)

**Comment by jjyao** [comment]
For the bad run above there were node failures due to GCS health check failures. For the good run above there were no node failures.

**Comment by jjyao** [comment]
I run the test on v2 stack, the perf was good (it didn't have node failures): https://buildkite.com/ray-project/release-tests-pr/builds/33356#01873601-f3d7-49d2-afc0-da7c3d70c283

**Comment by jjyao** [comment]
It's hard for me to run this test on v1 stack, launching 250 nodes has very low success rate on v1.

**Comment by jjyao** [comment]
After migrating back to v2 stack, the perf number went back.
