### ISSUE TITLE
[Data] collate_fn in iter_torch_batches could be a bottleneck

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#33508]
### Description

[The current implementation](https://github.com/ray-project/ray/pull/32412) does custom batching in a sequential manner. In some cases that the user-defined `collate_fn` consumes much time, the overall dataset pipeline is still slow. In contrast, the `collate_fn` in pytorch DataLoader executes in parallel.

**Comment by amogkam** [comment]
this will be fixed by https://github.com/ray-project/ray/pull/33510!

the `_collate_fn` will run in a threadpool

**Comment by genesis-jamin** [comment]
Was this feature every implemented? #33510 seems to have been closed without merging, and from viewing the flame graph I'm seeing significant time spent in my custom collate function.

**Comment by justinvyu** [comment]
@genesis-jamin  The linked PR was a prototype that got split into multiple PRs that have already been merged.
1. https://github.com/ray-project/ray/pull/33575
2. https://github.com/ray-project/ray/pull/33605
3. https://github.com/ray-project/ray/pull/33620
