### ISSUE TITLE
[ray.util.spark] Dashboard no longer available

### ISSUE THREAD

**Issue by fedassembly** [ray-project/ray#33521]
### What happened + What you expected to happen

Until this week I was able to access the Ray dashboard on Databricks. Now I no longer can.

### Versions / Dependencies

Ray 2.3.0
Databricks DBR 12.2 ML LTS
AWS instance

### Reproduction script

```
from ray.util.spark import setup_ray_cluster

setup_ray_cluster(...)
```

This used to output an HTML block with a link to the dashboard

I can manually get the link with this, but the page shows 502 Bad Gateway

```
from ray.util.spark.cluster_init import _setup_ray_cluster

cluster = _setup_ray_cluster(...)
cluster.wait_until_ready() # this won't output the link because ray_ctx.address_info.get("webui_url", None) is falsy
cluster.start_hook.on_ray_dashboard_created(cluster.ray_dashboard_port)
```

And if I do curl {cluster_ip}:{dashboard_port} I get curl: (7) Failed to connect to {cluster_ip} port {dashboard_port}: Connection refused

I also tried to spin up a cluster from Databricks web terminal. I passed the dashboard options to`ray start` with the same result. I didn't try `ray dashboard` though.

### Issue Severity

High: It blocks me from completing my task.

**Comment by nathan-az** [comment]
@fedassembly just want to confirm you are also installing at least the default extras `%pip install ray[default]` as opposed to just `%pip install ray`? I believe the `default` extras are required for the dashboard.

**Comment by fedassembly** [comment]
@nathan-az THANKS!! yes that was the issue. 

I had been using `ray[default]` in my initial test. Since I was quite happy with it, I decided to add ray as a cluster library but instead of `[default]` I put `[tune]`.

I would probably add something along these lines

```
try:
    __import__("ray.dashboard.optional_deps")
except ModuleNotFoundError:
    _logger.warning("Optional dependencies to launch the optional dashboard API server cannot be found. ",
                    "They can be installed with pip install ray[default].")
```

here

https://github.com/ray-project/ray/blob/a74e563c560fe5628f96bc62dda3139c946fb585/python/ray/util/spark/cluster_init.py#L107-L112
