### ISSUE TITLE
[CI] MacOS build/test outage in Feb '23

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#33530]
We had an outage in our MacOS build/test fleet. I am not sure what action items we can take to fix this/improve this for the future; we should postmortem or just ask around to see if there's anything we should do so this isn't as bad next time.

* https://anyscaleteam.slack.com/archives/CLJQR6420/p1677107459953169
* https://anyscaleteam.slack.com/archives/CLJQR6420/p1676586912560139

![image](https://user-images.githubusercontent.com/950914/226692869-ce21f3fb-c23e-4686-98a2-583395aee6d8.png)

**Comment by cadedaniel** [comment]
FYI @krfricke @rkooo567 @justinvyu in case you have anything to add (ideas to improve for next time). Was there a postmortem for this?

**Comment by rkooo567** [comment]
I think the main issue was the only Kai knows how to fix the issue. I remembered @zhe-thoughts said we would do postmortem for this one.

**Comment by zhe-thoughts** [comment]
This should be on the backlog of @can-anyscale . Let's finish the current effort of GCE release testing and see which other P0/P1 issue should be picked up.

**Comment by aslonnie** [comment]
macos tests are back on line. now sure how it was fixed though..
