### ISSUE TITLE
[Core] Docker containers require `--network host` to function correctly. 

### ISSUE THREAD

**Issue by joncarter1** [ray-project/ray#33534]
### **The bug**
Ray clusters formed from a collection of Docker containers do not work correctly unless each container uses the host network namespace.

### **Expected behaviour**
Exposing only the ports specified in the documentation (https://docs.ray.io/en/latest/ray-core/configure.html) should be sufficient to run Ray.

### **Actual behaviour**
See 'Reproduction script' below.
In short, the Ray cluster runs into errors for different configuration attempts (Docker + Ray CLI flags).

### Why this should be fixed
It enables better isolation of containers from the host, which has a number of benefits:
1. A clear understanding of exactly what ports Ray requires is important from a security perspective.
2. Allows multiple Ray containers on a single machine, which can improve modularity.

Better isolation will also help to deploy Ray on alternative cloud providers such as Hashicorp Nomad (something I am working on).

### Possible solution
The issue seems to arise due to the [following line](https://github.com/ray-project/ray/blob/5f8630384746b6030d089ec40fa01d52d0f4268e/dashboard/head.py#L126) (L126) in `dashboard/head.py`:
```
        self.ip = ray.util.get_node_ip_address()
```
which returns the container IP address (e.g. 172.17.0.2) when not running in `--network host` mode.
On L323, this incorrect ip:port is put into the GCS server which then causes downstream problems.
In my use-case, since the dashboard runs on the head node, replacing the IP address on L126 with the IP address of the GCS server (L128, which matches --node-ip-address) appears to fix the problem.

#### Outstanding unknowns/issues
1. The port for the 'dashboard head grpc address' is currently not configurable (set to random value):
https://github.com/ray-project/ray/blob/5f8630384746b6030d089ec40fa01d52d0f4268e/dashboard/head.py#L132-L134
Should this also be exposed? This port appears in the `dashboard_agent.log` of other nodes (from [event_agent.py](https://github.com/ray-project/ray/blob/5f6bd3bdc0b569b9248e0ebf84a45437f73c58ed/dashboard/modules/event/event_agent.py#L56)) so my assumption is yes.

2. What is the appropriate way to ascertain the publicly reachable IP address for the dashboard head process?

### Versions / Dependencies

Using the Docker image `rayproject/ray:2.3.0` running on a Ubuntu 20.04 host

### Reproduction script

**Scenario 1** - Ray containers on different machines using the --node-ip-address flag:

Command 1 (on machine 1):
```
docker run -it -p 10000-10050:10000-10050 rayproject/ray:2.3.0 ray start --block --disable-usage-stats --node-manager-port 10000 --object-manager-port 10001 --dashboard-agent-grpc-port 10003 --dashboard-agent-listen-port 10004 --metrics-export-port 10005 --port 10006 --dashboard-port 10007 --ray-client-server-port 10008 --min-worker-port 10010 --max-worker-port 10040 --ray-client-server-port 10046 --head --dashboard-host 0.0.0.0 --node-ip-address $MACHINE1_IP
```
Command 2 (on machine 2):
```
docker run -it -p 10000-10050:10000-10050 rayproject/ray:2.3.0 ray start --block --disable-usage-stats --node-manager-port 10000 --object-manager-port 10001 --dashboard-agent-grpc-port 10003 --dashboard-agent-listen-port 10004 --metrics-export-port 10005 --min-worker-port 10010 --max-worker-port 10040 --address="$MACHINE1_IP:10006" --node-ip-address $MACHINE2_IP
```
Results in the following warning in `dashboard.log`:
```
WARNING node_head.py:222 -- Head node is not registered even after 10 seconds. The API server might not work correctly. Please report a Github issue. Internal states :{'head_node_registration_time_s': None, 'registered_nodes': 2, 'registered_agents': 2, 'node_update_count': 114, 'module_lifetime_s': 80.2459077835083}
```
The resulting Ray cluster is unstable when using the job submission API. The following script:
```
from ray.job_submission import JobSubmissionClient

if __name__ == "__main__":
    client = JobSubmissionClient("http://MACHINE1_IP:10007")
    client.submit_job(entrypoint="ls")
```
_sometimes_ results in the following error:
`aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`
This does not always occur but I have not been able to figure out why it does/does not.

Whenever the error does occur, a worker node is marked as 'Dead' in the dashboard. However, the worker container doesn't report an error on either stdout/stderr and keeps running. If there are many nodes in the cluster, repetition of the job submission causes an additional worker to be marked as 'Dead' each time until there are none left. Once all are dead and only the host remains, the job submission works successfully.

**Scenario 2 - Ray containers on the same machine with the --node-ip-address flag:**
Commands are similar to those of scenario 1. The same error using the job submission is encountered.

**Scenario 3 - Ray containers on different machines without the --node-ip-address flag:**

Command 1 (on machine 1):
```
docker run -it -p 10000-10050:10000-10050 rayproject/ray:2.3.0 ray start --block --disable-usage-stats --node-manager-port 10000 --object-manager-port 10001 --dashboard-agent-grpc-port 10003 --dashboard-agent-listen-port 10004 --metrics-export-port 10005 --port 10006 --dashboard-port 10007 --ray-client-server-port 10008 --min-worker-port 10010 --max-worker-port 10040 --ray-client-server-port 10046 --head --dashboard-host 0.0.0.0 
```
Command 2 (on machine 2):
```
docker run -it -p 10000-10050:10000-10050 rayproject/ray:2.3.0 ray start --block --disable-usage-stats --node-manager-port 10000 --dashboard-agent-grpc-port 10003 --dashboard-agent-listen-port 10004 --metrics-export-port 10005  --object-manager-port 10006 --min-worker-port 10010 --max-worker-port 10040 --address="$MACHINE1_IP:10006"
```
after around 10 seconds this results in
```
Some Ray subprocesses exited unexpectedly:
  raylet [exit code=1]
```
on machine 2.

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Thanks for the detailed report!!
