### ISSUE TITLE
[CI] `linux://python/ray/air:test_dataset_config` is flaky on master.

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#33594]
It appears that `python/ray/air/tests/test_dataset_config.py::test_global_shuffle` is flaky as it checks if two 5 element lists get shuffled differently. However, considering that we do not set any seed (and I don't think we have an API for that yet), it is not uncommon for the two lists to simply be randomly shuffled in the same way.

Until we introduce an API to set a seed, a simple (though imperfect) mitigation could be to just increase the sizes of the datasets from 5 to eg. 5000.

- fde3e720d1a275ad34dffe65ed539dfc1c3b2085 FLAKY [Buildkite :airplane: AIR tests (ray/air)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2868#01870a1c-dd07-456e-a3d4-e9b038956c65)
- 61ae0497aa6fdf2c234184b0baf8df7d50a45191 FLAKY [Buildkite :airplane: AIR tests (ray/air)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2866#01870849-0e20-4d4a-a1bd-3a0fff1cd4b2)
- 636a69984eac35e371f1776bb0e45ab9f26239b0 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2861#018706a3-2527-4644-bded-6e4da3b849d1)
- 25ad8f997d46fc0a0ccae77da1f0257463055b79 FLAKY [Buildkite :airplane: AIR tests (ray/air)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2844#018704fd-ae5c-4cbe-8962-c4007c082fde)
- 930c2ed9297b056b1935d76997e64f989e193101 FLAKY [Buildkite :cold_face: :python: Ray Python legacy dependency ML compatibility tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2832#0187018b-7133-4fa2-89a3-368d8b182046)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/air:test_dataset_config-END
....

**Comment by Yard1** [comment]
@stephanie-wang, what's the progress on the improved API for `DatasetConfig`? I recall you were working on that, and the ability to pass a seed there was discussed.

**Comment by anyscalesam** [comment]
dataset_config is deprecated; test is no longer relevant. cc @c21
