### ISSUE TITLE
test_task_events test is failing regularly now

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#33632]
### What happened + What you expected to happen

Test_task_events is timing out regularly now.

<img width="1167" alt="Screenshot 2023-03-23 at 11 51 07 AM" src="https://user-images.githubusercontent.com/46904826/227260635-f318cb74-e84a-4337-a976-125c460e7552.png">

### Versions / Dependencies

Main branch

### Reproduction script

Look at https://flakey-tests.ray.io/?owner=core

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
@ollie-iterators Thanks for contributing by opening all these issues concerning failing tests in the past few days.
We have an internal on-call rotation for all of these tests and usually see the failing tests on [flakey-tests.io ](https://flakey-tests.ray.io/) before we are able to look at your issues.
