### ISSUE TITLE
[rllib] Implement I/O API

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3363]
### Describe the problem
Implement the I/O API as described here: https://docs.google.com/document/d/1tv0wcFy23tcZmDbMWse_VaUHN3KyL7_uK-R_qTasaoI/edit#heading=h.jwrrnrt5guaj

TODO: 
- [x] basic API
- [x] figure out if logging postprocessed batches is necessary for any use cases or if we can get away with just recording the raw transitions
- [x] multi-agent / event format support
- [x] docs

**Comment by janislavjankov** [comment]
Hi @ericl, thanks for working on this! How will the train loop change in order to get the train iteration align with the length of the offline data?
For example let's say I have DQN agent with its default configuration to collect 1000 timesteps per iteration, i.e. `"timesteps_per_iteration": 1000`, and my data is 500 timesteps. Seems like that currently calling `agent.train()` will block until the buffer is filled which in that case will be never. I did try this with ExternalEnv implementation with the same outcome.

**Comment by ericl** [comment]
The current implemention will loop over the input data indefinitely, so in this case you would end up with a batch of the same data duplicated twice. You can also decrease the batch sizes to avoid buffering as much though this may impact performance.

**Comment by janislavjankov** [comment]
Ah, I see that _next_file selects a random file so loops forever! Have you considered allowing the InputReader-s to throw StopIteration (behaving like iterator) or some other way to signal that we've reached the end of the data?
Let's say I have a scenario like the batched RL example and I train my policy on one hour batches, potentially with different number of timesteps per the 1 hour batch. I'll need to keep track of how many have been processed after each train iteration and exit the train loop before repeating too much the same data - not ideal. If I'm to provide a custom InputReader I'll need to figure out a way to supply data upon request even if I'm at the EOF.
How will the framework handle an exception in the reader?

**Comment by ericl** [comment]
Hm, one option is to raise some exception like yourself in the reader like
StopIteration. The exception will be propagated up to the train call
(though it may be wrapped in RayTaskError).

I think it's also reasonable to loop over the data multiple times and stop
after a fixed number of optimization passes. There's a little bit of
efficiency trade-off but I doubt it will be large compared to the impact of
other training hyperparameters. Algorithms like DQN will be buffering the
inputs in their replay buffer, so you'll see the same data item multiple
times anyways unless you set the buffer size to be very small.

**Comment by janislavjankov** [comment]
Agree, the effects in the majority of the cases would be negligible. Older buffered experience might be evacuated earlier than expected though as result of the multiple iterations over the data.
Looks like there might be additional work needed to get the different implementations handle the exception properly.

**Comment by ericl** [comment]
Yeah, I think there are a few edge cases:
- some algorithms assume you can always get train batches of a certain size. If this cannot be met due to end-of-input, you'll have to discard the entire train batch (probably negligible in most cases).
- some algorithms do many iterations per train() step, so it is undesirable to fail an entire train step when only one sub-iteration fails

Another option may be to return a "we have reached the end" signal, and stop training at the end of the current train step. A small fraction of the input data will be read twice, but this makes it easier to reason about when input is "done" at least.

We'll also have to support a sequential access mode for file inputs instead of random.
