### ISSUE TITLE
[CI] `linux://python/ray/tune:test_trial_runner_3` is failing/flaky on master.

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#33680]
- cd704855793b269b4ca3591bf3132a9982860db8 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2929#0187141f-b68b-4b8d-ba95-771c22d46a09)
- 3ca473f62241ec20192d0504e5aa3e0c01b9a173 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2928#0187141b-3501-4e68-927e-1cf4db96c864)
- ed5590797c98bd59e1e59dd5866a4679bafb6432 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2927#01871414-04a8-426b-9c49-b8ddda9287ee)
- 08699c5d259a12002063b7f7c2e35fcd9dbd7057 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2926#018713eb-3d16-4123-afb9-db2078d1a704)
- 903f7b65a5d8368422e2c6adc437b495d08e40b7 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2925#018713c0-8033-4b16-99ef-e17351def2e7)
- 77a42d809302f9c84168d98d15dcb0ad35199ad7 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2922#0187128e-afef-42b8-86e6-09155188a794)
- fe730c5ae03f027d02685b2d1d82a1d6b89bfecb FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2921#01871274-3715-4c6f-bfbb-ec920b6eb576)
- 6f699452ff8fea3e1629e4c664d855c57cf75605 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2920#0187120d-902c-4a03-8368-128f3fc71d91)
- 29979aeb3c85bea1c8903bfcbf1dea0dcc6b2578 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2919#018711bd-2e7e-41c3-9075-b8626400f555)
- 1ca7547db1bcd94c76fb20dba2515f0e8512d839 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2918#018711aa-9b4a-4f43-889e-2988e3d7c973)
- d8eff4e94d19c21b7663b8487b2f3bd16fd211c2 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2917#01871188-d7d0-4751-87e1-86da7d4c31b3)
- 2f01e4dab148df4eb655d32f0d1c7b24303e21ce FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2916#01871187-f1c4-4604-be54-367944c84dac)
- 4bec2fdfa5f1d797223080d8e8cfdf56624729c4 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2915#01871172-2932-40dc-bee6-fd449d859bfa)
- 38f4f86b9ae413701c5612efa9908227dec3a113 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2914#01871172-3253-4188-8498-c1c34903efa9)
- c5c09e80b7a72d39a010c70ea9226d6cbe7b4420 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2913#0187113e-9b2b-4c3c-95f9-a0beb3e0e2f9)
- f22fc1112245426824c42e2324ae900eff9138e0 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2912#0187113a-c726-4867-8189-73a0165bd9f3)
- 227f75c4a21fdab19682e2f05bfb5da37daf2b4f FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2911#01871122-3605-4ac2-a64d-2929a7c627cb)
- 3d1f6b4aeca5d39b4cb48c91c5f1d578114f9775 FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2910#0187110e-d792-4e73-b92a-fb2e5334ccb5)
- d4ee925d198a0236b548426bf4725de48f604e8e FAILED [Buildkite :octopus: Tune tests and examples (medium)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2909#018710cb-1dea-42cc-8732-7ff0f8553556)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tune:test_trial_runner_3-END
....

**Comment by justinvyu** [comment]
No longer failing.
