### ISSUE TITLE
[RLlib] TorchPolicyV2 number of variables should match the number of the return from action_sampler_fn

### ISSUE THREAD

**Issue by niujh** [ray-project/ray#33716]
### What happened + What you expected to happen

ray.rllib.policy.torch_policy_v2::TorchPolicyV2
line number 1075: number of variables should match the number of the return from action_sampler_fn

so:
-line number 1074: action_dist = dist_inputs = None
-line number 1075:  actions, logp, state_out = self.action_sampler_fn

+line number 1074: action_dist = None
+line number 1075:  actions, logp, **dist_inputs ,** state_out = self.action_sampler_fn

### Versions / Dependencies

ray==2.3.0
python==3.10
OS==wsl2

### Reproduction script

go [What happened]

### Issue Severity

None

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for reporting this!
