### ISSUE TITLE
[Tests] Fix two skipped Windows test for test_task_event_2.py

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#33738]
### What happened + What you expected to happen

See details.

https://github.com/ray-project/ray/pull/33704#issuecomment-1484622830

It seems to be a real bug. We should fix it. 

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by rickyyx** [comment]
There are a few other known issues with task failure states not being done properly for the dashboard. Since it's still a beta feature, and the fix might be high-risk based on https://github.com/ray-project/ray/pull/33818, should we not make it release blocking?

**Comment by rickyyx** [comment]
hmm, actually might be a test issue. Let me give it a try for short fix.

**Comment by rkooo567** [comment]
Keep it open until test_task_logs_info_basic is fixed in windows (we disabled this feature for now).

**Comment by rkooo567** [comment]
we fixed the main issue here, so it is not a release blocker anymore

**Comment by rickyyx** [comment]
Fixed by https://github.com/ray-project/ray/pull/33818
