### ISSUE TITLE
[Core] Better handling of redis errors

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#33744]
### What happened + What you expected to happen

When we use ray with external redis, sometimes redis returns REDIS_REPLY_ERROR and we are not handle it properly.

### Versions / Dependencies

master

### Reproduction script

#33733

### Issue Severity

None

**Comment by jjyao** [comment]
For 2.4, we should audit all redis calls and retry REDIS_REPLY_ERROR

**Comment by iycheng** [comment]
Close since duplicate with this https://github.com/ray-project/ray/issues/32541

**Comment by edoakes** [comment]
@iycheng these issues not the same

**Comment by jjyao** [comment]
The printed out error message is `redis_context.cc:67: Check failed: false Got an error in redis reply: MOVED 11267 10.0.18.181:6379`

**Comment by iycheng** [comment]
@edoakes I think for Redis failures, right now, we don't do anything to fix this since it's just not easy. Blindly retry won't work and is worse IMO. (refer to https://github.com/ray-project/ray/issues/34014 for details).

**Comment by edoakes** [comment]
@iycheng thanks for the leader election fix!

I think we should still leave this issue open and prioritize improving how we handle reply codes. Not having any form of retries or gracefully handling error codes makes the system unstable. What do you think?

**Comment by iycheng** [comment]
@edoakes  it's tracked here https://github.com/ray-project/ray/issues/34014
