### ISSUE TITLE
Actors scheduled unevenly

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#3374]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
- **Ray version**: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.3-cp36-cp36m-manylinux1_x86_64.whl
- **Python version**: 3.6.5
- **Exact command to reproduce**:

Boot a 50 node cluster (I have 50x c4.8xlarge), and run the following on the head node:
```
@ray.remote
class Actor:
    def run(self):
        time.sleep(10)
        return socket.gethostname(), os.getpid(), time.time()

actors = [Actor.remote() for _ in range(27 * 50)]
results = ray.get([actor.run.remote() for actor in actors])
from collections import Counter
print(Counter(ip for ip, *_ in results))
```

### Describe the problem
We see the workers that actors get assigned to are not evenly spread:
```
Counter({'ip-10-2-245-81': 36, 'ip-10-2-252-126': 35, 'ip-10-2-243-113': 34, 'ip-10-2-255-79': 34, 'ip-10-2-255-238': 32, 'ip-10-2-246-234': 32, 'ip-10-2-243-132': 31, 'ip-10-2-240-171': 31, 'ip-10-2-247-19': 31, 'ip-10-2-244-201': 31, 'ip-10-2-244-229': 31, 'ip-10-2-241-13': 31, 'ip-10-2-241-122': 30, 'ip-10-2-247-140': 30, 'ip-10-2-248-54': 30, 'ip-10-2-255-75': 29, 'ip-10-2-249-107': 28, 'ip-10-2-254-3': 28, 'ip-10-2-245-102': 28, 'ip-10-2-254-50': 28, 'ip-10-2-254-169': 27, 'ip-10-2-246-123': 27, 'ip-10-2-245-233': 27, 'ip-10-2-255-50': 27, 'ip-10-2-255-201': 27, 'ip-10-2-242-215': 27, 'ip-10-2-252-97': 27, 'ip-10-2-243-29': 27, 'ip-10-2-246-50': 27, 'ip-10-2-255-224': 26, 'ip-10-2-248-240': 26, 'ip-10-2-250-200': 26, 'ip-10-2-255-234': 25, 'ip-10-2-254-150': 25, 'ip-10-2-246-24': 25, 'ip-10-2-247-6': 25, 'ip-10-2-248-176': 25, 'ip-10-2-246-113': 25, 'ip-10-2-248-241': 24, 'ip-10-2-243-8': 24, 'ip-10-2-249-131': 24, 'ip-10-2-251-2': 23, 'ip-10-2-245-165': 23, 'ip-10-2-249-40': 23, 'ip-10-2-248-85': 22, 'ip-10-2-246-210': 20, 'ip-10-2-242-147': 20, 'ip-10-2-245-47': 19, 'ip-10-2-244-97': 19, 'ip-10-2-249-169': 18})
```

In contrast if functions are used:

```
@ray.remote
def job():
    time.sleep(10)
    return socket.gethostname(), os.getpid(), time.time()

results = ray.get([job.remote() for _ in range(27 * 50)])
```

Then the jobs are distributed evenly:
```
Counter({'ip-10-2-248-241': 27, 'ip-10-2-245-165': 27, 'ip-10-2-243-29': 27, 'ip-10-2-245-102': 27, 'ip-10-2-255-75': 27, 'ip-10-2-246-24': 27, 'ip-10-2-250-200': 27, 'ip-10-2-246-50': 27, 'ip-10-2-241-122': 27, 'ip-10-2-249-107': 27, 'ip-10-2-246-113': 27, 'ip-10-2-254-150': 27, 'ip-10-2-245-233': 27, 'ip-10-2-245-47': 27, 'ip-10-2-247-6': 27, 'ip-10-2-249-169': 27, 'ip-10-2-249-40': 27, 'ip-10-2-251-2': 27, 'ip-10-2-243-8': 27, 'ip-10-2-252-126': 27, 'ip-10-2-246-210': 27, 'ip-10-2-247-19': 27, 'ip-10-2-241-13': 27, 'ip-10-2-252-97': 27, 'ip-10-2-248-176': 27, 'ip-10-2-242-215': 27, 'ip-10-2-255-201': 27, 'ip-10-2-244-97': 27, 'ip-10-2-243-113': 27, 'ip-10-2-254-50': 27, 'ip-10-2-255-79': 27, 'ip-10-2-246-123': 27, 'ip-10-2-254-169': 27, 'ip-10-2-248-240': 27, 'ip-10-2-255-50': 27, 'ip-10-2-244-229': 27, 'ip-10-2-240-171': 27, 'ip-10-2-255-224': 27, 'ip-10-2-249-131': 27, 'ip-10-2-247-140': 27, 'ip-10-2-255-238': 27, 'ip-10-2-245-81': 27, 'ip-10-2-248-85': 27, 'ip-10-2-242-147': 27, 'ip-10-2-246-234': 27, 'ip-10-2-255-234': 27, 'ip-10-2-254-3': 27, 'ip-10-2-243-132': 27, 'ip-10-2-248-54': 27, 'ip-10-2-244-201': 27})
```

I have `--num-cpus` set to 27 on the workers and 0 on the head.  The uneven distribution means batches can take longer because nodes that are assigned >27 jobs will have to wait for an earlier job to finish (in this case taking 20s rather than 10s).

We also need to run more jobs than nodes at times, so we can't simply assign num_cpus=1 to our actors to guarantee an even spread, although we similar problems with some workers assigned more actors.

**Comment by robertnishihara** [comment]
I think the difference here is that the `job` tasks take 10 seconds so in order to execute them quickly they need to be spread out evenly.

However, the actor `run` method, which also takes 10 seconds, is only executed after the actor has already been created somewhere so the fact that it takes 10 seconds doesn't affect where the actor is located. Currently, there are actually three separate tasks here:
1. The actor creation task.
2. The `__init__` task.
3. The `run` task.

The actor creation task is scheduled somewhere and essentially turns the worker that it runs on into an actor. Once this has happened, all subsequent actor methods will run on that worker. The `__init__` task just runs the actor constructor. Currently this is a separate task, but it will be fused with the actor creation task in the future.

You could try something like, start each node with an additional custom resource, e.g.,
```
ray start ... --resources={"Custom":27}
```
and then declare the actor class with `@ray.remote(resources={'Custom': 1})`.

**Comment by mattearllongshot** [comment]
The fractional num_cpu trick works great for us. Thanks for the tip!
