### ISSUE TITLE
[infra] Release test failures: failing to download log from s3 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33759]
### What happened + What you expected to happen

Release test is quite unstable with a bunch of errors related to s3 logs download, example run:
https://buildkite.com/ray-project/release-tests-branch/builds/1479#_

Example test:
https://buildkite.com/ray-project/release-tests-branch/builds/1479#0187244b-ee17-4926-a2bd-ee478c3c41c8

Seems the logic is governed by _anyscale_job_wrapper

### Versions / Dependencies

master

### Reproduction script

Run nightly 

### Issue Severity

None

**Comment by clarng** [comment]
@Yard1  can you help triage ? Thanks

**Comment by Yard1** [comment]
This is a product issue as the workload isn't being ran in the first place (thus no logs are generated, thus they cannot be downloaded)

**Comment by clarng** [comment]
Duplicate of https://github.com/anyscale/product/issues/19025
