### ISSUE TITLE
Travis stress tests failing nondeterministically

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3375]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Ray installed from (source or binary)**: source
- **Python version**: all

### Describe the problem

We have some Travis tests that fail pretty frequently that I believe are introduced by some recent PRs.

As of #3347: `test/component_failures_test.py::test_raylet_failed` and `test/component_failures_test.py::test_plasma_store_failed`

As of #3011: `test/stress_tests.py::test_multiple_recursive[4] `

**Comment by xutianming** [comment]
I notice that none of recent pull requests, including those that are approved, could pass all the Travis tests.
