### ISSUE TITLE
[Dataset] Filtered Parquet `dataset.count()` returns incorrect row count based on input Dataset metadata

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#33766]
### What happened + What you expected to happen

When a Parquet Dataset is created and a `filter` is applied, calling `.count()` on the resulting filtered dataset will incorrectly use the original dataset's metadata in calculating the row count. We should instead clear the `num_rows` attribute of the `filter`ed dataset's metadata so that it does not use the incorrect upstream value. For now, the workaround is the call `fully_executed()` on the Dataset to obtain the correct row count.

### Versions / Dependencies

Ray master

### Reproduction script

```
import ray
import pyarrow as pa

all = ray.data.read_parquet("example://iris.parquet")
filtered = ray.data.read_parquet("example://iris.parquet", filter=pa.dataset.field("sepal.length") > 5.0)

print(all.count()) # prints 150
print(filtered.count()) # prints 150, but should be smaller
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by deanwampler** [comment]
Thanks for creating this ticket. I recommend having `count()` execute the code to determine the correct count, or at least document the known behavior, if you don't want to change the behavior.

**Comment by scottjlee** [comment]
Note for implementation later: I think we can check if `reader_args("filter") is not None`, then reset `meta.num_rows` to `None` in https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/parquet_datasource.py#L275
