### ISSUE TITLE
[rllib] Add Soft Actor-Critic implementation

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#3376]
Soft Actor-Critic (SAC) [1] is currently one of the most efficient model-free RL algorithms available. Its sample-complexity is close to the best model-based reinforcement learning methods while still having the scalability and simplicity of model-free methods.

It would be nice to have a scalable implementation of SAC available in rllib. I'm planning to contribute this sometime in the near future, but would like to know if there are some existing efforts going on in order to avoid redundant work.

Other existing implementations:
- https://github.com/rail-berkeley/softlearning
- https://github.com/haarnoja/sac
- https://github.com/openai/spinningup/tree/master/spinup/algos/sac

[1] https://arxiv.org/pdf/1801.01290.pdf

**Comment by ericl** [comment]
@hartikainen this would be great to have!

FYI @joneswong in case you were planning to look at this

**Comment by hartikainen** [comment]
The experimental version of SAC got merged in yesterday. We should still benchmark and verify the results on the standard mujoco tasks:
- [ ] Ant
- [ ] HalfCheetah
- [ ] Hopper
- [ ] Humanoid
- [ ] Walker
- [ ] Pendulum

**Comment by richardliaw** [comment]
@ericl we can close this?
