### ISSUE TITLE
[Core] Support iterable Object references

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#33790]
### Description

Ray has support for generator tasks- tasks that yield outputs instead of returning them

```python
@ray.remote
def task():
    for i in range(4):
        yield i
```

However, the object reference that is returned when calling this task is only complete when the entire generator has finished. It does not return an object reference that can be iterated upon and return results as they are ready.

This limits the use of generator tasks, preventing it from being uses as a solid solution for being able to return very large objects in chunks without object spilling.

### Use case

I have a task that returns a very large object. Putting this object into the object store will lead to spilling.

Instead, I want to effectively "stream" this object by yielding it in chunks. Each chunk can be processed by a downstream task, thus clearing this chunk from the object store freeing up space for the next chunk.

With this approach, my task can return very large objects without spilling.

**Comment by rkooo567** [comment]
You are talking about fixing this limitation right? https://docs.ray.io/en/master/ray-core/tasks/generators.html#limitations

cc @stephanie-wang for the feedback

**Comment by rkooo567** [comment]
cc @c21 how do you guys handle the similar situation? I believe dataset also uses generator?

**Comment by amogkam** [comment]
@rkooo567 this is currently not handled in Datasets, which is why I'm making this issue :)

**Comment by rkooo567** [comment]
This seems to be a pretty reasonable request to me, and the current behavior is also not very intuitive. 

cc @scv119 for thoughts. I think someone in our team can take this with other generator issues and fix it?

**Comment by c21** [comment]
>how do you guys handle the similar situation? I believe dataset also uses generator?

@rkooo567 - this is the improvement we think Core can help. Currently we are already using generator API for output blocks. But couldn't work around the limitation as @amogkam discovered.

**Comment by scv119** [comment]
```
import ray
import asyncio

@ray.remote
class A:
    def __init__(self):
        self.cache = {}
        pass

    async def hi(self):
        for i in range(5):
            yield i
            await asyncio.sleep(1)

    async def generator_wrapper(self, session_id):
        if session_id not in self.cache:
            self.cache[session_id] = self.hi()
        generator = self.cache[session_id]
        return await generator.__anext__()


a = A.remote()

for _ in range(5):
  print(ray.get(a.generator_wrapper.remote("123")))
```
I think at end of the day we need something like this into ray core 
so when you call ray.get(hi…) it actually returns you a handler, in this example, the session_id, and your follow up call will go into the generator_wrapper  with the session_id
and core will handle the GC of the session_id and worker side of generator when the client is done, or the generator has finished.

**Comment by rkooo567** [comment]
I think we also need to change the semantics of the API. Right now, it is possible you pass around the generator, and it can be consumed by many tasks/actors concurrently, which doesn't go well with normal generator design (it can be consumed only once), but possible with the current semantics.

**Comment by rkooo567** [comment]
Current status: We have 2 prototypes that make it work in application layer or core. I will write up a design doc in a few days and discuss the final actions here.

**Comment by amogkam** [comment]
cc @raulchen This is useful for Ray Data with transformations that are returning a large amount of data. The UDFs can yield chunks of this data (like https://docs.ray.io/en/latest/data/transforming-datasets.html), but this data still piles up since currently generator actor tasks are not considered complete until the entire generator has finished.

This change to ray Core allows us to get intermediate results from the generator and dispatch them to downstream operators, preventing these large objects from needing to pile up in the object store.

**Comment by rkooo567** [comment]
It is supported in the master now. We need a bit more work to make the APIs public
