### ISSUE TITLE
except Exception in config.py masks ClientError that should be raised

### ISSUE THREAD

**Issue by GiliR4t1qbit** [ray-project/ray#3380]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.6 (17G65) 
- **Ray installed from (source or binary)**: binary (via pip)
- **Ray version**: 0.5.3
- **Python version**: 2.7.14
- **Exact command to reproduce**: ray up ray/autoscaler/example-full.yaml 
(for a user that does not have GetInstanceProfile permissions, but does have CreateInstanceProfile permissions...)

### Describe the problem
In the above scenario - user does not have GetInstanceProfile, but does have CreateInstanceProfile, and the DEFAULT_RAY_INSTANCE_PROFILE already exists: 
The code (see ray/autoscaler/aws/config.py) tries to get the profile named DEFAULT_RAY_INSTANCE_PROFILE but fails due to a permissions error, and not because it does not exist. It goes on to assume that it does not exist, so it tries to create it, at which point it fails, since it already exists!

The error looks like this:

```
EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreateInstanceProfile operation: Instance Profile ray-autoscaler-v1 already exists.
```

I think I see what's happening and  why it's happening:
The function `_configure_iam_role()` calls `_get_instance_profile()` to check if the instance profile already exists. If None is returned, it assumes that the profile does not exist and that it should create the profile. However, `_get_instance_profile()` includes an `except Exception: return None`, so it returns None, which is assigned to the profile variable in `_configure_iam_role()`, if any kind of exception occurs when trying to get the profile, including a permissions issue. Essentially, it is masking the ClientError exception. This is very confusing to the user, since they get the wrong error - should be showing a permissions error, but shows an already exists error. Although it's true that the profile already exists, that's not the issue! 

### Source code / logs
Current source code for `_get_instance_profile()`:

```
def _get_instance_profile(profile_name, config):
    iam = _resource("iam", config)
    profile = iam.InstanceProfile(profile_name)
    try:
        profile.load()
        return profile
    except Exception:
        return None
```

A possible fix is to catch the exception associated with a missing profile, and return None, and avoid catching other exceptions, like so:
```
def _get_instance_profile(profile_name, config):
    iam = _resource("iam", config)
    profile = iam.InstanceProfile(profile_name)
    try:
        profile.load()
        return profile
    except botocore.errorfactory.NoSuchEntityException:
        return None
```
Note that the `_get_role()` function has a very similar structure, so it might need be changed as well, for the same reason:
```
def _get_role(role_name, config):
    iam = _resource("iam", config)
    role = iam.Role(role_name)
    try:
        role.load()
        return role
    except botocore.errorfactory.NoSuchEntityException:
        return None
```

**Comment by ericl** [comment]
Hm, I think that the intent is only to catch exceptions that indicate the Role / Profile does not exist. So we could catch those and turn those to None, but let any other exceptions through.

**Comment by GiliR4t1qbit** [comment]
@ericl: yes, of course, you are right. I caught the error when trying to get a role or profile that don't exist, and in both cases it is `botocore.errorfactory.NoSuchEntityException`. I've edited the above message to reflect this change (avoids clutter). Let me know what you think and I can make a PR.

**Comment by GiliR4t1qbit** [comment]
@ericl: I went ahead and made a PR.
