### ISSUE TITLE
[ml] air_benchmark_tensorflow_mnist_cpu_4x1  test failure

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33828]
### What happened + What you expected to happen

Run 3/3] Observed results:  {'tensorflow_mnist_ray_time_s': 115.974105904, 'tensorflow_mnist_ray_local_time_s': 103.89113332499994, 'tensorflow_mnist_ray_loss': 0.6817492246627808, 'tensorflow_mnist_vanilla_time_s': 106.94805699299991, 'tensorflow_mnist_vanilla_local_time_s': 103.64440587900003, 'tensorflow_mnist_vanilla_loss': 0.6823894381523132}
Results: {'tensorflow_mnist_ray_num_runs': 3, 'tensorflow_mnist_ray_time_s_all': [118.689526253, 118.06114832499998, 115.974105904], 'tensorflow_mnist_ray_time_s_mean': 117.57492682733333, 'tensorflow_mnist_ray_time_s_sd': 1.160656545964602, 'tensorflow_mnist_ray_time_local_s_all': [104.835003626, 105.36044978300004, 103.89113332499994], 'tensorflow_mnist_ray_time_local_s_mean': 104.69552891133333, 'tensorflow_mnist_ray_time_local_s_sd': 0.6078994491750526, 'tensorflow_mnist_ray_loss_mean': 0.6857340137163798, 'tensorflow_mnist_ray_loss_sd': 0.002987067236800975, 'tensorflow_mnist_vanilla_time_s_all': [106.49746996900001, 104.842337251, 106.94805699299991], 'tensorflow_mnist_vanilla_time_s_mean': 106.09595473766664, 'tensorflow_mnist_vanilla_time_s_sd': 0.9053267434860385, 'tensorflow_mnist_vanilla_local_time_s_all': [0.0, 101.51751491500005, 103.64440587900003], 'tensorflow_mnist_vanilla_local_time_s_mean': 68.38730693133336, 'tensorflow_mnist_vanilla_local_time_s_sd': 48.364923434816426, 'tensorflow_mnist_vanilla_loss_mean': 0.4536181688308716, 'tensorflow_mnist_vanilla_loss_std': 0.32076048435939464}
Traceback (most recent call last):
  File "workloads/tensorflow_benchmark.py", line 440, in <module>
    main()
  File "workloads/tensorflow_benchmark.py", line 436, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "workloads/tensorflow_benchmark.py", line 391, in run
    f"Training on Ray took an average of {times_local_ray_mean:.2f} seconds, "
RuntimeError: Training on Ray took an average of 104.70 seconds, which is more than 1.20x of the average vanilla training time of 68.39 seconds (1.53x). FAILED

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1493#01872a7e-b09e-469e-a168-05e970838a7d

### Issue Severity

None

**Comment by clarng** [comment]
tagging ML-oncall

**Comment by krfricke** [comment]
This is the culprit:

```
	'tensorflow_mnist_vanilla_local_time_s_all': [0.0, 101.51751491500005, 103.64440587900003],
```

the vanilla script failed three times in the first iteration, reporting as 0 seconds.

The Ray times are very similar:

```
	'tensorflow_mnist_ray_time_local_s_all': [104.835003626, 105.36044978300004, 103.89113332499994],
```

Thus this is not a regression in Ray, but just an artifact of the test.

This is not release blocking, so I'm closing this. cc @matthewdeng
