### ISSUE TITLE
[CI] `linux://python/ray/tune:test_client` is failing/flaky on master.

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#33833]
### `grpcio` Issue
https://github.com/grpc/grpc/issues/32758

### Original Failure

- af759eb7c99079be63c523b869178eb76b65c4ec FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3031#01872a3d-ac4d-4f27-ad48-6a98c3b97dab)
- d418fa77f8dbc77a546ee9eee654957841ff75ef FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3030#01872a03-aa82-4c0e-a0a0-c0488a904503)
- 23c8012f80f8658bd281ea9c114c2dca96a01c7e FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3029#01872981-9175-4b27-ae80-354bc7bb2279)
- bb1909c2676ccca6714448de18287fb4b0cfc67d FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3028#0187297f-764d-440e-8f5b-8fcf28e8084b)
- 25d99175687c332ceb2c777c1b686c2622e3e769 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3026#0187296c-ec88-4d12-92fb-92c919711467)
- 97f8ba1d5de8db9e35087ef4a75f5ee9ea87a4f7 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3025#0187296c-e673-4bdf-8c08-ae2c66bc51d5)
- 50d7852f831e141300bc7b7a0ce535456a479340 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3024#01872933-eafa-406a-ab46-94dcc8ad9bc4)
- 724466996220c35431f44f1c0cf5a66cc223eb73 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3023#01872913-aa12-4b7c-92c9-5d9f1f57a1dc)
- 43109936fddc98bd2343305c50d76b3a0ab454e0 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3021#01872703-a36b-41d0-a182-ed443d924281)
- 02568af425f50e8fc6bcaf05804c5aeb7e54ea5a FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3019#018726f8-b32d-4f84-bfc5-d3e2dc766a6e)
- 27c4dd6b0b3a911e6a1a531083c7c342c34bac1a FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3018#018726f7-e1f7-4096-bff1-3699715ccfee)
- 6453e8ff2a172b95ff59a9ea9f9649784f628676 FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3016#018726d5-1319-42fa-bedd-5d57fb4013d9)
- 950fc333d1eaf35ef31e9b98059f989c605662af FAILED [Buildkite :tropical_fish: ML Libraries w/ Ray Client Examples (Python 3.7).](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3015#018726d3-bf45-43d8-825e-57dfbccf6b75)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tune:test_client-END
....

**Comment by matthewdeng** [comment]
I was able to narrow down this repro. It appears to be specific to the usage of Ray Client.

```python
import pytest
import sys

import ray
from ray.util.client.ray_client_helpers import ray_start_client_server

@pytest.fixture
def start_client_server():
    ray.init(num_cpus=1)
    with ray_start_client_server() as client:
        yield client
    ray.shutdown()

@pytest.fixture
def ray_start():
    address_info = ray.init(num_cpus=1)
    yield address_info
    ray.shutdown()

# Works if I change `start_client_server` to `ray_start` or remove it.
def test_dataloader(start_client_server): 
    from torch.utils.data import DataLoader
    from torchvision import datasets
    from torchvision.transforms import ToTensor

    dataset = datasets.FashionMNIST(root="/tmp/data", download=True, transform=ToTensor())
    dataloader = DataLoader(dataset, batch_size=1, num_workers=2)

    for inputs, labels in dataloader:
        pass


if __name__ == "__main__":
    sys.exit(pytest.main(["-v", __file__]))
```

**Comment by matthewdeng** [comment]
Opened a tracking ticket in `grpcio` here: https://github.com/grpc/grpc/issues/32758

**Comment by pcmoritz** [comment]
Quick update here: This can actually be resolved in either one of two ways:

- Setting `torch.multiprocessing.set_start_method('spawn')` to use spawn instead of fork for the DataLoader
- Running the DataLoader not on the client side -- with what we already have in https://github.com/ray-project/ray/issues/35472, the Python workers are now free of Python grpc dependencies, so the problem wouldn't occur there

**Comment by matthewdeng** [comment]
Ah for the second one, the original issue was indeed happening on the server side - it was failing inside a Tune job which would run the dataloader in the Tune Trainable worker process. When originally working on this I simplified the repro script to run on the client side.

One thing to verify with https://github.com/ray-project/ray/issues/35472 is if the following works:
```python
def test_dataloader(start_client_server): 
   
    @ray.remote
    def run_dataloader()
        from torch.utils.data import DataLoader
        from torchvision import datasets
        from torchvision.transforms import ToTensor

        dataset = datasets.FashionMNIST(root="/tmp/data", download=True, transform=ToTensor())
        dataloader = DataLoader(dataset, batch_size=1, num_workers=2)

        for inputs, labels in dataloader:
            pass
    
    ray.get(run_dataloader.remote())
```

**Comment by pcmoritz** [comment]
Got it! I think the grpcio removal shifted the failure to the client side actually (the validation part) -- this was the failure I was debugging: https://buildkite.com/ray-project/oss-ci-build-pr/builds/24127#0188764f-fb16-468f-8364-2ad872b9496e

**Comment by matthewdeng** [comment]
Oh wow, taking a look at the original runs it seems like that's where it actually ended up failing too 😵
