### ISSUE TITLE
[AIR output] Tune concepts are leaked when I only used a trainer

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33839]
### What happened + What you expected to happen

1. Ran pytorch_training_e2e.py. The warning is very confusing since it mentions `trials` and `tune`
```
(autoscaler +10s) Adding 1 node(s) of type worker-node-type-1.
2023-03-28 15:27:35,585 WARNING insufficient_resources_manager.py:128 -- Ignore this message if the cluster is autoscaling. You asked for 1.0 cpu and 1.0 gpu per trial, but the cluster only has 0 cpu and 0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
```

2. Ran` tensorflow_benchmark.py` in release test with `AIR_VERBOSITY=1`

When trying to force stop the execution via `cmd+c`. I saw messages related to `trial` and `experiment`
```
^C2023-03-28 18:19:28,738       WARNING tune.py:185 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
```
and
```
2023-03-28 18:19:09,796 ERROR tune.py:941 -- Trials did not complete: [TensorflowTrainer_886ed_00000]
2023-03-28 18:19:09,797 WARNING tune.py:955 -- Experiment has been interrupted, but the most recent state was saved.
Continue running this experiment with: Tuner.restore(path="/home/ray/ray_results/TensorflowTrainer_2023-03-28_18-17-54", trainable=...)
```

3. When I ran `air_benchmark_xgboost_cpu_10 `
```
2023-03-28 13:51:14,756 WARNING trial_runner.py:1576 -- The maximum number of pending trials has been automatically set to the number of available cluster CPUs, which is high (176 CPUs/pending trials). If you're running an experiment with a large number of trials, this could lead to scheduling overhead. In this case, consider setting the `TUNE_MAX_PENDING_TRIALS_PG` environment variable to the desired maximum number of concurrent trials.
```

```
2023-03-28 14:04:06,409 WARNING util.py:244 -- The `process_trial_save` operation took 3.927 s, which may be a performance bottleneck.
2023-03-28 14:04:06,409 WARNING trial_runner.py:887 -- Consider turning off forced head-worker trial checkpoint syncs by setting sync_on_checkpoint=False. Note that this may result in faulty trial restoration if a failure occurs while the checkpoint is being synced from the worker to the head node.
```

### Versions / Dependencies

nightly

### Reproduction script

workloads/tensorflow_benchmark.py in release test

### Issue Severity

Low: It annoys or frustrates me.

**Comment by krfricke** [comment]
Unfortunately, we can't get rid of all tune-related messages just yet. This requires more progress in the layering refactor we're aiming to tackle.

I'll reply one-by-one.

> ### What happened + What you expected to happen
> 
>     1. Ran pytorch_training_e2e.py. The warning is very confusing since it mentions `trials` and `tune`
> 
> 
> ```
> (autoscaler +10s) Adding 1 node(s) of type worker-node-type-1.
> 2023-03-28 15:27:35,585 WARNING insufficient_resources_manager.py:128 -- Ignore this message if the cluster is autoscaling. You asked for 1.0 cpu and 1.0 gpu per trial, but the cluster only has 0 cpu and 0 gpu. Stop the tuning job and adjust the resources requested per trial (possibly via `resources_per_trial` or via `num_workers` for rllib) and/or add more resources to your Ray runtime.
> ```

I agree this is confusing, and it's rather easy to solve. I fixed this in https://github.com/ray-project/ray/pull/35003


> 
>     2. Ran` tensorflow_benchmark.py` in release test with `AIR_VERBOSITY=1`
> 
> 
> When trying to force stop the execution via `cmd+c`. I saw messages related to `trial` and `experiment`
> 
> ```
> ^C2023-03-28 18:19:28,738       WARNING tune.py:185 -- Stop signal received (e.g. via SIGINT/Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C (or send SIGINT/SIGKILL/SIGTERM) to skip. 
> ```
> 

I'll keep this for now. It's not ideal with "experiment state" but I think it's not very confusing. The `tune.py` will only go away once we refactor the layering.


> and
> 
> ```
> 2023-03-28 18:19:09,796 ERROR tune.py:941 -- Trials did not complete: [TensorflowTrainer_886ed_00000]
> 2023-03-28 18:19:09,797 WARNING tune.py:955 -- Experiment has been interrupted, but the most recent state was saved.
> Continue running this experiment with: Tuner.restore(path="/home/ray/ray_results/TensorflowTrainer_2023-03-28_18-17-54", trainable=...)
> ```

This is actually confusing and I'll also aim to address this in https://github.com/ray-project/ray/pull/35003.


> 
>     3. When I ran `air_benchmark_xgboost_cpu_10 `
> 
> 
> ```
> 2023-03-28 13:51:14,756 WARNING trial_runner.py:1576 -- The maximum number of pending trials has been automatically set to the number of available cluster CPUs, which is high (176 CPUs/pending trials). If you're running an experiment with a large number of trials, this could lead to scheduling overhead. In this case, consider setting the `TUNE_MAX_PENDING_TRIALS_PG` environment variable to the desired maximum number of concurrent trials.
> ```

This is actually a bug (it shouldn't come up at all, the maximum number of pending trials should just be 1). I've fixed this in https://github.com/ray-project/ray/pull/35003

> 
> ```
> 2023-03-28 14:04:06,409 WARNING util.py:244 -- The `process_trial_save` operation took 3.927 s, which may be a performance bottleneck.
> 2023-03-28 14:04:06,409 WARNING trial_runner.py:887 -- Consider turning off forced head-worker trial checkpoint syncs by setting sync_on_checkpoint=False. Note that this may result in faulty trial restoration if a failure occurs while the checkpoint is being synced from the worker to the head node.
> ```

This is a bit too intrusive to change at the moment, it may be mitigated once we decide if Trial should become an AIR concept or remain tune-only.
