### ISSUE TITLE
[serve] release test failure: long_running_serve_failure

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33868]
### What happened + What you expected to happen

[INFO 2023-03-29 08:40:58,971] sdk_runner.py: 140  ... command still running ...(6990 seconds) ...
--
  | [INFO 2023-03-29 08:41:28,714] sdk_runner.py: 140  ... command still running ...(7020 seconds) ...
  | [INFO 2023-03-29 08:41:58,355] sdk_runner.py: 140  ... command still running ...(7050 seconds) ...
  | [INFO 2023-03-29 08:42:28,842] sdk_runner.py: 140  ... command still running ...(7080 seconds) ...
  | [INFO 2023-03-29 08:42:58,465] sdk_runner.py: 140  ... command still running ...(7110 seconds) ...
  | [INFO 2023-03-29 08:43:28,553] sdk_runner.py: 140  ... command still running ...(7140 seconds) ...
  | [INFO 2023-03-29 08:43:58,641] sdk_runner.py: 140  ... command still running ...(7170 seconds) ...
  | [INFO 2023-03-29 08:44:28,525] sdk_runner.py: 140  ... command still running ...(7200 seconds) ...
  | [ERROR 2023-03-29 08:44:58,216] glue.py: 420  Command returned non-success status: 137
  | Traceback (most recent call last):
  | File "/tmp/release-o8AoP3QZw9/release/ray_release/glue.py", line 364, in run_release_test
  | raise_on_timeout=not is_long_running,
  | File "/tmp/release-o8AoP3QZw9/release/ray_release/command_runner/sdk_runner.py", line 160, in run_command
  | raise CommandError(f"Command returned non-success status: {status_code}")
  | ray_release.exception.CommandError: Command returned non-success status: 137
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/tmp/release-o8AoP3QZw9/release/ray_release/glue.py", line 374, in run_release_test
  | raise TestCommandError(e)
  | ray_release.exception.TestCommandError: Command returned non-success status: 137
  | 🌍 Terminating cluster | 0s
  | 🚨 Handling errors | 0s
  | 📝 Reporting results | 1s
  | [INFO 2023-03-29 08:44:59,905] log.py: 11  Test long_running_serve_failure finished after 0.00 seconds. Last logs:
  |  
  | (ServeController pid=458318) INFO 2023-03-29 08:44:47,294 controller 458318 deployment_state.py:1165 - Deploying new version of deployment zbmTEWpKoY.
  | (ServeController pid=458318) INFO 2023-03-29 08:44:47,365 controller 458318 deployment_state.py:1384 - Adding 1 replica to deployment zbmTEWpKoY.
  | (ServeController pid=458318) INFO 2023-03-29 08:44:50,991 controller 458318 deployment_state.py:1148 - Deleting deployment zbmTEWpKoY.
  | (ServeController pid=458318) INFO 2023-03-29 08:44:51,067 controller 458318 deployment_state.py:1410 - Removing 1 replica from deployment 'zbmTEWpKoY'.
  | (ServeController pid=458318) INFO 2023-03-29 08:44:52,063 controller 458318 deployment_state.py:1165 - Deploying new version of deployment FdzAoWHDcT.
  | (ServeController pid=458318) INFO 2023-03-29 08:44:52,121 controller 458318 deployment_state.py:1384 - Adding 1 replica to deployment FdzAoWHDcT.
  | (ServeController pid=458318) WARNING 2023-03-29 08:44:52,683 controller 458318 deployment_state.py:651 - Actor for replica jofQxhOQoa#KfOMHa crashed, marking it unhealthy immediately.
  | (ServeController pid=458318) WARNING 2023-03-29 08:44:52,683 controller 458318 deployment_state.py:1602 - Replica jofQxhOQoa#KfOMHa of deployment jofQxhOQoa failed health check, stopping it.
  | (ServeController pid=458318) WARNING 2023-03-29 08:44:52,882 controller 458318 deployment_state.py:651 - Actor for replica rmLhyfEocl#OAYiHZ crashed, marking it unhealthy immediately.
  | (ServeController pid=458318) WARNING 2023-03-29 08:44:52,882 controller 458318 deployment_state.py:1602 - Replica rmLhyfEocl#OAYiHZ of deployment rmLhyfEocl failed health check, stopping it.
  |  

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1494#01872d8c-3be5-45a2-9c5e-ef4b5585aec8

### Issue Severity

None

**Comment by clarng** [comment]
Tagging serve oncall

**Comment by sihanwang41** [comment]
https://github.com/ray-project/ray/pull/33921
testing in v2 stack.

**Comment by sihanwang41** [comment]
And also monitor a side bug:
https://github.com/ray-project/ray/pull/33890
