### ISSUE TITLE
[ray.util.spark] Databricks proxy URL link for ray dashboard does not appear until notebook cell completes execution

### ISSUE THREAD

**Issue by nathan-az** [ray-project/ray#33866]
### What happened + What you expected to happen

**What happened**

The link to the Databricks proxy for the ray dashboard does not appear until after the cell containing the cluster startup is fully executed. i.e. if the cell contains some compute in addition to the cluster start, that compute must finish before the dashboard link is provided. If all ray code is contained in one cell (e.g. importing code which runs some ray workload), then the entire ray compute will finish before the dashboard link is displayed.

**What I expect to happen**

The link to the Databricks proxy for the ray dashboard should be produced in some capacity immediately after the cluster starts.

**Useful information**

The method responsible for this is [display_databricks_driver_proxy_url](https://github.com/ray-project/ray/blob/master/python/ray/util/spark/databricks_hook.py#L33). The behaviour is probably caused by use of `displayHTML` as opposed to outputting to the stdout/stderr either directly or through a logger.

I was able to work around it with the following code:
```py
from pyspark.sql import SparkSession


def get_databricks_proxy_url():
    spark_context = SparkSession.builder.getOrCreate().sparkContext

    driverLocal = spark_context._jvm.com.databricks.backend.daemon.driver.DriverLocal
    commandContextTags = driverLocal.commandContext().get().toStringMap().apply("tags")
    orgId = commandContextTags.apply("orgId")
    clusterId = commandContextTags.apply("clusterId")

    template = "https://dbc-dp-{orgId}.cloud.databricks.com/driver-proxy/o/{orgId}/{clusterId}/{port}/"
    from ray.util.spark.cluster_init import _active_ray_cluster

    port = _active_ray_cluster.ray_dashboard_port
    proxy_url = template.format(orgId=orgId, clusterId=clusterId, port=port)
    return proxy_url
```
The output from the above function is then printed/logged after cluster start.

Unfortunately, the above is not optimal since I am directly accessing the private global variable `_active_ray_cluster`. 

### Versions / Dependencies

Databricks runtime (DBR): 12.2 LTS ML
Operating system: Linux-5.4.0-1096-aws-x86_64-with-glibc2.31
ray[default]: 2.3.1
python: 3.9.5

### Reproduction script

```py
from time import sleep
from ray.util.spark import setup_ray_cluster, MAX_NUM_WORKER_NODES, shutdown_ray_cluster

setup_ray_cluster(
    num_worker_nodes=MAX_NUM_WORKER_NODES,
    num_cpus_per_node=4,
)

shutdown_ray_cluster()

print("beginning sleep")
sleep(5)
print("ending sleep")
```
If one cell contains all code in the above block, the link to the Databricks proxy for the ray dashboard will not be presented until after the final print statement.

### Issue Severity

Low: It annoys or frustrates me. (Note that this could reasonably be Medium or High for users who use the dashboard as a key profiling tool)

**Comment by WeichenXu123** [comment]
Can you split 
```
setup_ray_cluster(
    num_worker_nodes=MAX_NUM_WORKER_NODES,
    num_cpus_per_node=4,
)
```
as one cell as a workaround ? :)

**Comment by nathan-az** [comment]
> Can you split
> 
> ```
> setup_ray_cluster(
>     num_worker_nodes=MAX_NUM_WORKER_NODES,
>     num_cpus_per_node=4,
> )
> ```
> 
> as one cell as a workaround ? :)

Thanks for the reply. That isian option and is quite natural in a notebook setting, which I assume is why the bug wasn't caught earlier. 

However, this bug affects writing end-to-end ray functionality in a separate codebase and importing + invoking it in the notebook. This is somewhat prohibitive for creating tooling for others which abstracts the ray aspect away from the end-user.

Right now my preferred workaround with the current functionality has been to encapsulate ray workloads with a context manager which essentially just starts and stops the cluster, but prints the dashboard IP to stdout.

```py
@contextlib.contextmanager
def spark_ray_context(
    num_worker_nodes: int = MAX_NUM_WORKER_NODES, num_cpus_per_node: int = 4
):
    setup_ray_cluster(
        num_worker_nodes=num_worker_nodes,
        num_cpus_per_node=num_cpus_per_node,
    )
    if is_in_databricks_runtime():
        proxy_url = get_databricks_proxy_url()
        print(f"\n\nAccess dashboard from {proxy_url}\n\n")

    yield
    shutdown_ray_cluster()
```
