### ISSUE TITLE
[CI] `linux://python/ray/data:test_huggingface` is failing/flaky on master.

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33886]
- 816ef72c789a3165db2ae503afc4911892abafb9 FAILED [Buildkite Dataset tests (bulk executor)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3042#01872f0e-c862-4419-9329-e15820b77ad2)
- 816ef72c789a3165db2ae503afc4911892abafb9 FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3042#01872f0e-c86d-4603-ba7d-f9622db5ce8d)
- 1c2e8e2dddeb457ecb3911cf66b05109aef60f98 FAILED [Buildkite Dataset tests (bulk executor)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3041#01872ee3-38a8-424d-bc55-f8409cd685fb)
- 1c2e8e2dddeb457ecb3911cf66b05109aef60f98 FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3041#01872ee3-38b3-4a56-bbc6-93750ffb4660)
- e6c8109401eb043de1afb4007773d5d8b2cead0b FAILED [Buildkite Dataset tests (bulk executor)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3040#01872ee0-d04e-4c40-9c6f-021f7aa05aef)
- e6c8109401eb043de1afb4007773d5d8b2cead0b FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3040#01872ee0-d059-4882-9ef6-4058a2ee9f56)
- fe109b06ef6186f3c69c62f2c673801c5b9d03b4 FAILED [Buildkite Dataset tests (bulk executor)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3039#01872ed3-ae20-405a-be55-e204dd8052c9)
- fe109b06ef6186f3c69c62f2c673801c5b9d03b4 FAILED [Buildkite Dataset tests (Arrow 6)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3039#01872ed3-ae2c-4572-bbe7-1dded226bcb6)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_huggingface-END
....

**Comment by clarng** [comment]
looks like new failure in ci

**Comment by matthewdeng** [comment]
cc @scottjlee FYI looks like we pin `datasets==2.0.0` in `requirements_train.txt`, if we want to make it consistent in `requirements_data.txt`?
