### ISSUE TITLE
Work on reducing the number of unused arguments in functions 

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#33882]
### What happened + What you expected to happen

According to codefactor, ray has 2,559 unused arguments in this repository.

It would be nice if this was much smaller and would possibly make it easier to maintain the code.

### Versions / Dependencies

Main branch

### Reproduction script

Main branch

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
This is common in certain design patterns.
For example, if you have multiple classes implementing the same, general, interface.
In RLLib, for example, we'll never get around this.
I don't think there there is good action we can take to resolve this issue so I'm closing it.
