### ISSUE TITLE
[tune] Support for custom endpoint-url in S3 LogSyncer

### ISSUE THREAD

**Issue by frthjf** [ray-project/ray#3390]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Ray installed from (source or binary)**: -
- **Ray version**: 0.5.3
- **Python version**: 3
- **Exact command to reproduce**: -

### Describe the problem

Tune already supports [log syncing](https://github.com/ray-project/ray/blob/master/python/ray/tune/log_sync.py) to AWS S3. However, there is no way to configure custom endpoint urls to use S3 compatible storages like [Minio](https://minio.io/). It would be great if it would be possible to optionally specify a custom endpoint that is being used in the boto sync command, e.g. ``aws --endpoint-url http://my-custom-endpoint s3 sync {} {}`` [here](https://github.com/ray-project/ray/blob/master/python/ray/tune/log_sync.py#L120)

I'd suggest that users can specify a custom endpoint as query string, for example:
```python
remote_dir='s3://mybucket?endpoint_url=http://my-custom-endpoint'
```

**Comment by richardliaw** [comment]
Sorry for the late reply; thanks for posting this.

Just to understand your suggestion - should the custom endpoint be parsed by Tune?

**Comment by frthjf** [comment]
Basically yes, parse the option from query string to modify the terminal command, for example by adding something like
```python
if remote_dir.find('?') >= 0:
    remote_dir, query = remote_dir.split('?')
    endpoint_url = parse_qs(query).get('endpoint_url', [None])[0]
    if endpoint_url:
        self.aws_sync_command = "aws s3 sync --endpoint-url " + quote(endpoint_url) + " {} {}"
```
to the LogSyncer constructor.

However, I've found that there is an [suggestion at the aws-cli tracker](https://github.com/aws/aws-cli/issues/1270) which would allow to configure the endpoint directly via the aws-cli config. That would be much cleaner, since it's sort of a limitation at their end. So I'm not sure whether it's worth to write and maintain extra parsing logic.

The other perhaps simpler and more generic thing we could do is to make the sync command itself customizable, e.g. exposing it as a module level variable. That way one could put the --endpoint-url in and also use other custom commands and sync scripts.

**Comment by richardliaw** [comment]
OK I'll open a PR for a customizable sync command later this week and will update this issue.

Let me know if there's any other pain points.

**Comment by frthjf** [comment]
Great, thanks!

**Comment by richardliaw** [comment]
@frthjf, check out https://ray.readthedocs.io/en/latest/tune-usage.html#custom-sync-upload-commands. 

I think what you'd want to do is something like:
```
exp = Experiment(
    name="experiment_name",
    run=MyTrainableClass,
    sync_function="aws s3 sync --endpoint-url {}".format(endpoint_url)) + " {local_dir} {remote_dir}"
)
```

Let me know if that works (and feel free to close the issue if it does)!

**Comment by frthjf** [comment]
Thanks @richardliaw, that's great!
