### ISSUE TITLE
[Tune] how to save the best result?

### ISSUE THREAD

**Issue by chjq201410695** [ray-project/ray#3391]
How to get the best result in tranable function mode, since there are no impliment of _save().   I know the ray_result file save all intermediate procedures.  however, if I set the num_samples = 200, finding the best result is not an easy work.

**Comment by richardliaw** [comment]
@chjq201410695, thanks for opening this issue. What is your workflow like? Do you want to find the best model in the same python process after your experiment? Or do you want to find the best model after your experiment process is done?

For the former, you can do something like https://github.com/ray-project/tutorial/blob/master/tune_exercises/helper.py#L68

For the latter, you can maybe load all the JSON files into a dataframe and then check the max for the column of interest.

Tune should probably provide some utilities for post-experiment analysis. It would be great to get your input on what you'd like to see!

**Comment by chjq201410695** [comment]
> @chjq201410695, thanks for opening this issue. What is your workflow like? Do you want to find the best model in the same python process after your experiment? Or do you want to find the best model after your experiment process is done?
> 
> For the former, you can do something like https://github.com/ray-project/tutorial/blob/master/tune_exercises/helper.py#L68
> 
> For the latter, you can maybe load all the JSON files into a dataframe and then check the max for the column of interest.
> 
> Tune should probably provide some utilities for post-experiment analysis. It would be great to get your input on what you'd like to see!

That‘s great ! It is a very clear response. Thanks a lot.
