### ISSUE TITLE
[docs] gpt-j fine-tune example OOM

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#33917]
On 16 g4dn.4xlarge we get

```
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 10.0.28.197, ID: 4882ecc5af7a8b7bafccf68e80a436b129accc9760b372fd170021cc) where the task (actor ID: 6f0ca7df62d130414691908c01000000, name=RayTrainWorker.__init__, pid=3458, memory used=54.94GB) was running was
55.83GB / 57.60GB (0.969247), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 6968feddcee8b90349e2941dba9966b39cefd72750a8378975a39508) because it was the most recently scheduled task; to see more information
about memory usage on this node, use `ray logs raylet.out -ip 10.0.28.197`. To see the logs of the worker, use `ray logs worker-6968feddcee8b90349e2941dba9966b39cefd72750a8378975a39508*out -ip 10.0.28.197. Top 10 memory users:
PID     MEM(GB) COMMAND

```

However running 16 g4dn.8xlarge will run properly.

**Comment by richardliaw** [comment]
We would need to change:

```
In order to run this example, make sure your Ray cluster has access to at least one GPU with 16 or more GBs of memory. The amount of memory needed will depend on the model. This notebook is being tested with 16 g4dn.4xlarge instances.
```

to g4dn.8xlarge.

**Comment by waleedkadous** [comment]
It did OOM at the very end as it was checkpointing, actually. But I validated that moving to g4dn.8xlarge fixed the problem.

**Comment by Yard1** [comment]
If you are using the default syncing mechanism (which pulls from worker nodes to head node), then yes, not having enough memory on the head node can cause it (though then that would also happen if you changed the node types).

I'll make a PR to update this in the short term and run some tests later

**Comment by waleedkadous** [comment]
Sounds good. I will rerun with a head node with more memory to see if that
fixes the issue.

**Comment by Yard1** [comment]
BTW. we are running this notebook as a release test with the following cluster configuration:

- g4dn.4xlarge as a head
- 15x g4dn.4xlarge as workers

Because the rank 0 worker is on the head node, no syncing happens, thus there are no OOMs. Therefore, the description is correct. We can update it to make it clearer (and the solution to avoid the OOM is to use cloud checkpointing).

**Comment by waleedkadous** [comment]
At least in the context of Anyscale (perhaps because there is extra stuff running on the head node), this did not work. I had to increase the head node to a g4dn.8xlarge for this to work. It did work once I made it that size, however.

**Comment by Yard1** [comment]
Were you running it on 2.3 or nightly?

**Comment by waleedkadous** [comment]
Was running 2.3.
