### ISSUE TITLE
[rllib] TorchDiagGaussian implementation issue

### ISSUE THREAD

**Issue by fzdy1914** [ray-project/ray#33910]
### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/35621726/228732031-65190d6e-31b7-4a60-9f3e-abb3b3a018d9.png)

![image](https://user-images.githubusercontent.com/35621726/228732170-5c1b6e29-4c63-49a5-926b-4d2fc99ceb17.png)

It looks like, in TorchDiagGaussian, we should also use dim=-1. 

I encountered an error when running with an action space like: 

self.action_space = spaces.Box(
    low=np.array([0]),
    high=np.array([1]),
    dtype=np.float64
)

### Versions / Dependencies

ray==2.3.0

### Reproduction script

self.action_space = spaces.Box(
    low=np.array([0]),
    high=np.array([1]),
    dtype=np.float64
)
Using the default PPO training.

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
@fzdy1914 Can you post a full reproduction script, please?

The samples from these distributions should be 2D, their shape being [batch_dim, action_space_dim].
Therefore, it should not make a difference, because index 1 and -1 both signify the action space dimension.
