### ISSUE TITLE
[core] pgs_per_second regression

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33925]
### What happened + What you expected to happen

REGRESSION 14.62%: pgs_per_second (THROUGHPUT) regresses from 17.712835160069687 to 15.122576617790921 (14.62%) in 2.4.0/benchmarks/many_pgs.json

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1495#01872ebc-01fb-466a-8309-ca698bf752a2

### Issue Severity

None

**Comment by clarng** [comment]
https://buildkite.com/ray-project/release-tests-branch/builds/1499

**Comment by rkooo567** [comment]
pg is not a performance-sensitive API, so I think this much of regression is okay. cc @scv119 @jjyao please lmk if you disagree.

**Comment by jjyao** [comment]
I think my only concern is that if we have slight regression for each release, the accumulation might be significant enough.  @rkooo567 do you have a definition of `too slow`, how may pgs_per_second is too slow?

**Comment by rkooo567** [comment]
@iycheng is looking at the fix. It should be due to the same problem (syncer regression)
