### ISSUE TITLE
[core] stress test many tasks regressions 

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33931]
### What happened + What you expected to happen

from release logs : https://github.com/ray-project/ray/issues/33888

<img width="866" alt="Screen Shot 2023-03-30 at 11 12 37 AM" src="https://user-images.githubusercontent.com/22830327/228926863-d415769c-8424-4959-9d73-b1f194f3e144.png">

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1493#01872a7e-b290-4ec3-847b-c0653de973a7

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @scv119 for the stage 0.

stage 3 is expected. No need to investigate. 
stage 4 seems like an improvement?  (is it latency or throughput?)
