### ISSUE TITLE
[RLLib] Checkpoint ID gets reset when loading a model

### ISSUE THREAD

**Issue by atapley** [ray-project/ray#33934]
### What happened + What you expected to happen

I would like to train, save, load, and then resave a model but keep the checkpoint IDs consistent. For example, if I load a checkpoint with the ID 5 and retrain for 5 more iterations, it should be saved as `checkpoint_000010`, but it is currently saved as `checkpoint_000005` which overwrites the original model save.

### Versions / Dependencies

python = "~3.9"
ray = {extras = ["rllib"], version = "^2.3.0"}
torch = "^1.12.0"
torchaudio = "^0.12.0"
torchvision = "^0.13.0"

Ubuntu 18.04.6 LTS

### Reproduction script

```
from ray.rllib.algorithms.ppo import PPOConfig
from ray.tune.logger import pretty_print


algo = (
    PPOConfig()
    .rollouts(num_rollout_workers=1)
    .resources(num_gpus=0)
    .environment(env="CartPole-v1")
    .build()
)

algo.train()
path = algo.save()
print(path) # should be checkpoint_000001
algo.stop()

algo = Algorithm.from_checkpoint(path)
new_path = algo.save()
print(new_path) # should be checkpoint_000002 but is checkpoint_000001 again
algo.stop()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by Rohan138** [comment]
The `load_checkpoint` and `save_checkpoint` methods only save and restore the weights, not metadata such as the iteration. You should use the `save` and `restore` methods instead as follows:

```
from ray.rllib.algorithms.ppo import PPOConfig

config = (
    PPOConfig()
    .rollouts(num_rollout_workers=1)
    .resources(num_gpus=0)
    .environment(env="CartPole-v1")
)
algo = config.build()

algo.train()
path = algo.save()
print(path) # prints checkpoint_000001
algo.stop()

algo = config.build()
algo.restore(checkpoint_path=path)
algo.train()
new_path = algo.save()
print(new_path) # prints checkpoint_000002
algo.stop()
```

**Comment by Rohan138** [comment]
Marking as closed; by the way, if any docs/tutorials use `save` and `load_checkpoint`, please let us know so we can fix this.

**Comment by atapley** [comment]
Just wanted to come back and say I had found the `from_checkpoint()` call from this doc page - https://docs.ray.io/en/latest/rllib/rllib-saving-and-loading-algos-and-policies.html#how-do-i-restore-an-algorithm-from-a-checkpoint
