### ISSUE TITLE
[core] perf regression : placement group  create / removal

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33948]
### What happened + What you expected to happen

Reporting regression in 2 separate tests

REGRESSION 52.19%: placement_group_create/removal (THROUGHPUT) regresses from 927.1420650048237 to 443.2617952441349 (52.19%) in 2.4.0/microbenchmark.json

REGRESSION 19.57%: avg_pg_remove_time_ms (LATENCY) regresses from 0.8356835120128541 to 0.9992335435431319 (19.57%) in 2.4.0/stress_tests/stress_test_placement_group.json

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-pr/builds/33295#0187345e-42fb-4135-9ffc-ad8e23cd1f07

https://buildkite.com/ray-project/release-tests-pr/builds/33296#0187345f-89ce-4b4a-b4fd-aec46f96b763

### Issue Severity

None

**Comment by clarng** [comment]
<img width="420" alt="Screen Shot 2023-03-30 at 3 13 54 PM" src="https://user-images.githubusercontent.com/22830327/228975700-d126f24c-8cd8-49f8-90f0-5fbe30736988.png">

**Comment by iycheng** [comment]
The root cause is that the raylet reports too many msgs to the GCS. PG scheduling is centralized, to resource broadcasting is not useful for this.

I'll see how to make it better.

**Comment by rkooo567** [comment]
@iycheng why do we send more data after the syncer? Thought it reserves the previous behavior (pull once a second + we overwrite previous data)
