### ISSUE TITLE
[core] perf regression: 1_1_actor_calls_async

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#33949]
### What happened + What you expected to happen

REGRESSION 8.88%: 1_1_actor_calls_async (THROUGHPUT) regresses from 8098.766293651375 to 7379.572758156523 (8.88%) in 2.4.0/microbenchmark.json

last run shows worse results 

{'perf_metric_name': '1_1_actor_calls_async', 'perf_metric_value': 6939.589314887375, 'perf_metric_type': 'THROUGHPUT'}

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-pr/builds/33295#0187345e-42fb-4135-9ffc-ad8e23cd1f07

### Issue Severity

None

**Comment by clarng** [comment]
Due to https://github.com/ray-project/ray/pull/32943 per https://github.com/ray-project/ray/issues/33924#issuecomment-1494991412

**Comment by zhe-thoughts** [comment]
@rickyyx did we verify the above? Thanks!

**Comment by rickyyx** [comment]
Yes, the PR fixed the regression : https://github.com/ray-project/ray/pull/34056#issuecomment-1496800690

Waiting for cherry pick to be merged to close this: https://github.com/ray-project/ray/pull/34101#issuecomment-1502046722
