### ISSUE TITLE
[AIR] Allow `BatchMapper` to take in callable classes 

### ISSUE THREAD

**Issue by Yard1** [ray-project/ray#33956]
### Description

We should extend `BatchMapper` preprocessor to also be able to take in callable classes with the Actor compute strategy (https://docs.ray.io/en/latest/data/transforming-datasets.html#callable-class-udfs) for stateless transformations where we want to save time on the initialisation step in each batch.

**Comment by Yard1** [comment]
cc @amogkam @gjoliver

**Comment by bveeramani** [comment]
Closing this issue because `BatchMapper` is deprecated
