### ISSUE TITLE
[serve] Application can be marked `DEPLOY_FAILED` but the deployments are actually `HEALTHY`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#33974]
This can happen if the `serve.run` call in the task spawned by the controller runs and submits the application, but then the task fails for some reason.

My $0.02 is we should refactor this to make the task atomic from the perspective of the controller -- it returns the built app instead of calling back into the controller to deploy it.

**Comment by edoakes** [comment]
Note that this can be mitigated by retrying in an external component.

**Comment by edoakes** [comment]
Agree that application status can include more than just deployment status, but right now it's sometimes showing `DEPLOY_FAILED` when everything else succeeded and is healthy which is not good.

Yep that's what I'm thinking too. So basically:

- On deploy, we should add the info to application state manager
- During reconciliation, application state manager spawns the task if necessary or else checks its status. If it failed, we can check if it should be retried else mark the application as `DEPLOY_FAILED`.
- The task should just return the built application data structure. When it succeeds, application state manager calls an internal method to deploy the deployments.

The task should now have no side effects (unless the user does something weird) which also helps handle failure scenarios such as the controller crashing (we can just respawn the task).

**Comment by shrekris-anyscale** [comment]
Synced offline; reassigning to @zcin for now.

**Comment by zcin** [comment]
Done with https://github.com/ray-project/ray/pull/34328
