### ISSUE TITLE
[air/train] Distributed Optimizer for model parallel

### ISSUE THREAD

**Issue by liuchanglab** [ray-project/ray#33990]
### Description

When we train large model such as GPT3, we need to use model parallel for optimizer. However, ray can not support distributed optimizer for model parallel?

**Comment by richardliaw** [comment]
Ray does support model parallelism -- we will offer some examples in 2.4.

Here is an example for training (which uses master/nightly build) -- https://docs.ray.io/en/master/ray-air/examples/gptj_deepspeed_fine_tuning.html.

Hope that helps!

Related issue: https://github.com/ray-project/ray/issues/21508
