### ISSUE TITLE
[RLlib|AIR|Tune] Connect W&B as of type DefaultCallbacks for Ray Train Config API

### ISSUE THREAD

**Issue by PhilippWillms** [ray-project/ray#33992]
### Description

As per my observation, the `WandbLoggerCallback` is usable with `ray.tune` only. 

Apart from that, with ray 2.0 a new config-API for the ray Rllib was introduced. This defines the formerly dict-style to inline-method style. There is also an interface available to define callbacks.

It would be great if we could use it in the following way.

    config = (
        ppo.PPOConfig()
        .environment(...)
        .framework(...)
        .resources(...)
        .rollouts(...)
        .training(...)
        .callbacks(WandbLoggerCallback(project="rl-chem-prod-scheduling", sync_tensorboard=True, upload_checkpoints=True)
     )

BUT today this leads to the following issue:

> ValueError: `config.callbacks_class` must be a callable method that returns a subclass of DefaultCallbacks, got <ray.air.integrations.wandb.WandbLoggerCallback object at 0x0000024918F97C10>!

### Use case

As the usage of `tune `comes with multiple side-effects on Trainer/Algorithm configs,. the interoperability between the new API-based config style based on final `algo.train() `and the `tune.run()` idea based on a trainable func is not always given. To my idea, the feature request contributes to a more consistent way in upcoming releases for RLLib Train and Tune.

**Comment by Rohan138** [comment]
RLlib and Tune/AIR use different callbacks classes. You should pass the `WandbLoggerCallback` directly to `tune.run` or `tune.Tuner`: https://docs.ray.io/en/latest/tune/examples/tune-wandb.html
