### ISSUE TITLE
[Data] small issue on API docs 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#34004]
### Description

The example on this page: https://docs.ray.io/en/latest/data/api/doc/ray.data.read_images.html#ray.data.read_images

suggests

```
import ray
path = "s3://air-example-data-2/movie-image-small-filesize-1GB"
ds = ray.data.read_images(path)  
ds  
```

but I think this should be

```
path = "s3://anonymous@air-example-data-2/movie-image-small-filesize-1GB"
```

to make it work.

**Comment by amogkam** [comment]
What's the difference @maxpumperla?

**Comment by maxpumperla** [comment]
ah sorry, forgot to add the `@anonymous` above @amogkam
