### ISSUE TITLE
[Data] For BatchInference workloads, make clear what the golden path is

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#34006]
### Description

Working on the [object detection CUJ](https://docs.google.com/document/d/1v5Kzp_o3LpgYU1ZFa7-7H3uYDyDLqaDG7epUkjSgwh8/edit#) and playing dumb a little, from the material we have on our docs it's not clear at all how to do batch inference e.g. with a HF model in "the right way". The examples we have all use `map_batches` afaict, but we also have dedicated AIR abstractions like the `HuggingFacePredictor` for that.

How do we make this clear and discoverable? 

- We should certainly invest in more examples, e.g. by making these dog fooding sessions dedicated, polished examples.
- Also, let's make sure to give clear and actionable advice on our docs for workloads like this.

**Comment by richardliaw** [comment]
I believe we've done a heavy pass on the docs and now we no longer show the Predictor interface!
