### ISSUE TITLE
What is vf_explained_var and var_gnorm ? 

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#3401]
Hi, Can anyone explain the meaning of vf_explained_var and var_gnorm? What does this represent?

**Comment by ericl** [comment]
Explained variance of the value function: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/a3c/a3c_tf_policy_graph.py#L114

Global norm of the policy variables: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/a3c/a3c_tf_policy_graph.py#L112

**Comment by okvlam** [comment]
the provided link is not available as showing error 404

> Explained variance of the value function: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/a3c/a3c_tf_policy_graph.py#L114
> 
> Global norm of the policy variables: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/a3c/a3c_tf_policy_graph.py#L112
