### ISSUE TITLE
[CI] `air_benchmark_xgboost_cpu_10` results aren't uploaded to Databricks

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#34025]
If the prediction time exceeds the prediction time threshold (450s), then the results aren't uploaded to Databricks.

For example, look at [this test run from February 21](https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_nltqmbvtuhjbiuu3senydsbedp?pjd-section=last-log):

```
Results: {'training_time': 778.8808449190001, 'prediction_time': 1544.04337004}
Traceback (most recent call last):
  File "workloads/xgboost_benchmark.py", line 179, in <module>
    main(args)
  File "workloads/xgboost_benchmark.py", line 159, in main
    f"Batch prediction on XGBoost is taking {prediction_time} seconds, "
RuntimeError: Batch prediction on XGBoost is taking 1544.04337004 seconds, which is longer than expected (450 seconds).
Subprocess return code: 1
...
{"collected_metrics":true,"last_prepare_time_taken":7.519578995999993,"prepare_return_codes":[0],"return_code":1,"total_time_taken":2386.448083592,"uploaded_metrics":true,"uploaded_results":true,"workload_time_taken":2325.152163422}| ###
```

The job logs suggest that the results have been uploaded (`"uploaded_results":true`).

But, if you run the following query:

```sql
SELECT DATE(timestamp_millis(cast(report_timestamp_ms AS BIGINT))) as __timestamp
	-- regex matches to either `master` or `releases/x.y.z`
	, regexp_extract(wheel_url, ".+\/ray-wheels\/(master|releases\/\\d\.\\d.\\d)", 1) AS branch
	, get_json_object(results, "$.prediction_time") as prediction_time
FROM oss_ci.ray_release_test_result
WHERE group = "AIR tests"
  AND name = "air_benchmark_xgboost_cpu_10"
ORDER BY `__timestamp` DESC
```

you'll see that there aren't any `prediction_time` values above 450. Instead, all the values are null.

**Comment by matthewdeng** [comment]
@krfricke does the release test infra upload results based on the return code?

**Comment by krfricke** [comment]
It shouldn't - the expected behavior is that all results (especially failures) are uploaded. Otherwise our dashboard wouldn't be very useful.
Maybe this is something that regressed in the transition to anyscale jobs. I can take a look tomorrow.
