### ISSUE TITLE
[Core] Enhance `ActorPool` to eliminate the need for specifying `ActorPoolStrategy` in `map_batches`

### ISSUE THREAD

**Issue by zhe-thoughts** [ray-project/ray#34034]
### Description

In https://github.com/ray-project/enhancements/pull/25, at this stage we are going with the intermediate option of asking the user to specify `ActorPoolStrategy` when doing Batch Inference. 

As part of the REP, we have agreed to "make ActorPool smarter" to eliminate this need. This enhancement needs to be based on more user feedback (from their real workloads)

### Use case

In Batch Inference, it is ideal to automatically decide the number of Actors and the amount of CPU / GPU resources for each Actor (each Actor holding a model replica)

**Comment by jjyao** [comment]
@zhe-thoughts why is it `core`?

**Comment by zhe-thoughts** [comment]
> why is it `core`?

I thought `ActorPool` is part of Core. Is it not?

**Comment by raulchen** [comment]
Dup as https://github.com/ray-project/ray/issues/40725
