### ISSUE TITLE
[docker] Docker Tags Page Won't Load

### ISSUE THREAD

**Issue by thatcort** [ray-project/ray#34049]
### What happened + What you expected to happen

The Ray Docker tags won't load. Navigating to https://hub.docker.com/r/rayproject/ray/tags gives the error message: "An error occurred while loading the tags."

I asked Docker Hub about the error and they responded:

```
Upon checking internally with the engineering team, it appears that you have more than 200,000 tags within the repository rayproject/ray. This is not a recommended approach since this is a Docker Hub limitation where slowness/failures could occur when there are too many tags in a repository.

As a general recommendation, we recommend setting a limit of maximum 1000 tags within a repo and not exceeding the limit. We are planning on enforcing such limit in the future but there is no ETA at the moment. 
```

Not being able to browse the tags makes it difficult to understand what combinations of Ray, CUDA, Python are available.

### Versions / Dependencies

All

### Reproduction script

https://hub.docker.com/r/rayproject/ray/tags

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by krfricke** [comment]
Hi @thatcort, thanks for raising this. We're aware and trying to mitigate this - most likely we'll periodically remove the large number of per-commit and per-day tags that are older than e.g. 2 weeks. 

cc @can-anyscale

**Comment by aslonnie** [comment]
cleaned up old tags.


and it can load now:

<img width="1113" alt="image" src="https://github.com/ray-project/ray/assets/95255098/ca291e01-33ec-470a-ad72-a1138b391110">

still quite slow though

**Comment by aslonnie** [comment]
`rayproject/ray-ml` has 5k tags now but are still failing/very slow to load. I do not really understand the mechanism or implementation behinds it.

**Comment by aslonnie** [comment]
- we will consider stop publishing per commit docker images.
- if that still does not help, we will provide an alternative tags list somewhere..

**Comment by aslonnie** [comment]
loading now. maybe docker hub fixed their loading bug.

**Comment by aslonnie** [comment]
proof: 
<img width="741" alt="image" src="https://github.com/ray-project/ray/assets/95255098/6639b785-b6ce-4dde-a078-6d3a640b86c2">
