### ISSUE TITLE
[Serve] test_serve_agent_fault_tolerance flacky 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#34054]
### What happened + What you expected to happen

https://flakey-tests.ray.io/?owner=serve

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

**Comment by shrekris-anyscale** [comment]
This test hasn't been very flaky lately:

<img width="1336" alt="Screen Shot 2023-06-22 at 6 19 22 PM" src="https://github.com/ray-project/ray/assets/92341594/edd3e8af-d34e-4b75-83a9-f3f7dfe67000">

I'll close this issue for now. If the test becomes flaky again, we can reopen it.
