### ISSUE TITLE
Mac wheels building failure

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#34075]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/3159#01874e11-0689-428f-aa68-533a63791f42

Mac test failed due to:
```
> rm -rf /tmp/bazel_event_logs
  | > export BUILDKITE_HOOK_EXIT_STATUS=1
  | > BUILDKITE_HOOK_EXIT_STATUS=1
  | > export BUILDKITE_HOOK_WORKING_DIR=/Users/ec2-user/.buildkite-agent/builds/bk-macos-branch-arm64-queue-i-02879e59fe8133d49-1/ray-project/oss-ci-build-branch
  | > BUILDKITE_HOOK_WORKING_DIR=/Users/ec2-user/.buildkite-agent/builds/bk-macos-branch-arm64-queue-i-02879e59fe8133d49-1/ray-project/oss-ci-build-branch
  | > buildkite-agent env dump
  | > exit 1
  | 🚨 Error: The command exited with status 1
  | Running local post-command hook | 0s
  | $ .buildkite/hooks/post-command
  | user command error: The plugin macos-sandbox command hook exited with status 1
  | Uploading artifacts | 14s
  | $ buildkite-agent artifact upload /tmp/artifacts/.*/**
  | 2023-04-04 21:05:23 INFO   Found 6 files that match "/tmp/artifacts/.*/**"
  | 2023-04-04 21:05:23 INFO   Uploading to default Buildkite artifact storage
  | 2023-04-04 21:05:23 INFO   Creating (0-6)/6 artifacts
  | 2023-04-04 21:05:23 INFO   Uploading artifact 01874e16-b4cd-4310-b01b-8d6f52b0381e tmp/artifacts/.whl/ray_cpp-3.0.0.dev0-cp39-cp39-macosx_11_0_arm64.whl (23426268 bytes)
 

<br class="Apple-interchange-newline">

**Comment by iycheng** [comment]
@krfricke do you have some idea about this?

**Comment by krfricke** [comment]
The actual failing part is that it fails in one of the tests:

<img width="403" alt="Screenshot 2023-04-06 at 7 18 00 AM" src="https://user-images.githubusercontent.com/14904111/230278419-7069d182-5ff2-42c8-ba9d-f36856918e0a.png">

The logs reveal:

<img width="1275" alt="Screenshot 2023-04-06 at 7 18 50 AM" src="https://user-images.githubusercontent.com/14904111/230278553-daed8110-cd9e-4752-a8a2-67aa75691725.png">

(this does not show up in succeeding builds).

However, another fishy thing is that this fails after only 6 minutes:
<img width="204" alt="Screenshot 2023-04-06 at 7 19 21 AM" src="https://user-images.githubusercontent.com/14904111/230278617-f83cd4e4-c607-4bd2-a8ee-b19b6f900bf9.png">

I'm wondering if this is left-over state from previous jobs on the runner instance. The wheels are actually built so maybe looking at them will help investigate this.

**Comment by krfricke** [comment]
FWIW, the wheels seem to work locally.

I've tried restarting the build instance but it did not help. I will now terminate it to see if this changes things.

**Comment by iycheng** [comment]
Co-assign to @jjyao  who will cover my oncall duty.

**Comment by zhe-thoughts** [comment]
@iycheng @jjyao could you help provide an ETA? Thanks!

**Comment by clarng** [comment]
Still needs cherry pick
