### ISSUE TITLE
[serve][dashboard] Show controller & HTTP proxy status in the dashboard

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#34078]
If the HTTP proxy is dead/unhealthy/not responding, I have no way to see it. Same with the controller.

This depends on: https://github.com/ray-project/ray/issues/19151

**Comment by alanwguo** [comment]
This is blocked by https://github.com/ray-project/ray/issues/19151 and also on work to add an API to get metadata about these entities.

@akshay-anyscale , is this still planned for this sprint? It seems like this will be a really nice fix to get in by ray 2.5? 

CC: @zcin @edoakes

**Comment by scottsun94** [comment]
Design proposal is here: https://github.com/ray-project/ray/issues/34076

**Comment by akshay-anyscale** [comment]
19151 is now completed

**Comment by scottsun94** [comment]
This issue is fixed now.
