### ISSUE TITLE
[dashboard][serve] Link to Ray Serve controller & HTTP proxy logs in the dashboard

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#34076]
### Description

I currently have to track these down manually. Users won't know how to do it. Basically everything under `serve/` logs dir should be discoverable in the dashboard.

**Comment by alanwguo** [comment]
Where do you recommend these links be? We don't really surface the HTTP proxy or Ray serve controller concepts in the UI today.

CC: @scottsun94

**Comment by edoakes** [comment]
I think we probably should surface them... maybe in a closed-by-default "system" tab or something?

In most cases users shouldn't have to care but if something is going wrong it's good to have visibility.

**Comment by scottsun94** [comment]
@edoakes @alanwguo Please take at the two options and leave your comments.

1. Keep the system info, app info, and metrics in the same page. (collapse the system info by default)
<img width="891" alt="Screen Shot 2023-04-25 at 4 05 44 PM" src="https://user-images.githubusercontent.com/9677264/234390667-bdb7db72-2fbe-4832-ae59-52f195b82788.png">
<img width="890" alt="Screen Shot 2023-04-25 at 4 05 49 PM" src="https://user-images.githubusercontent.com/9677264/234390672-5c751655-44b8-41cb-b342-56fbd3b8eebe.png">

2. Separate the system info from app info and metrics
<img width="1020" alt="Screen Shot 2023-04-25 at 4 02 06 PM" src="https://user-images.githubusercontent.com/9677264/234390978-9e3ce825-b54c-4c83-aa01-267b1901a9e7.png">
 
<img width="890" alt="Screen Shot 2023-04-25 at 4 05 38 PM" src="https://user-images.githubusercontent.com/9677264/234391026-e99c2a0a-5970-4087-b735-49c12c5d38d1.png">


Option 1 has all the info in the same page and users don't have to switch between different pages.
Option 2 has cleaner UI and is less overwhelming to users.

**Comment by edoakes** [comment]
Preference for the 1st one for me because:
1. the icons are not very intuitive (easy to overlook)
2. the overhead of seeing "System" as a closed tab is very small
3. Having a navigation bar at the top and on the side seems excessive

**Comment by scottsun94** [comment]
I'm fine with going with 1st for now. WDYT? @alanwguo 

If we go with this route, when serve is not started, let's just replace everything with a warning? (currently we put the warning within the system tab)

<img width="936" alt="Screen Shot 2023-04-25 at 5 25 09 PM" src="https://user-images.githubusercontent.com/9677264/234407531-432cc789-89f6-47c3-bbfb-858ec9847739.png">

**Comment by scottsun94** [comment]
As suggested by @sijieamoy , can we also add an error badge next to the "System" title when either controller or http proxy is unhealthy? This should guide users to expand and investigate the errors there.

<img width="1061" alt="Screen Shot 2023-05-01 at 3 12 29 PM" src="https://user-images.githubusercontent.com/9677264/235540635-85ea635a-ee38-40b5-bad7-044b01cbbc5d.png">

**Comment by alanwguo** [comment]
do HTTP Proxies recover after they are marked as unhealthy?
If they instead get replaced by new proxies, then once one is marked unhealthy, we'll show this big red error icon until the cluster dies? Seems too permanent for a long-running service.

@edoakes @sihanwang41  thoughts?

**Comment by edoakes** [comment]
@alanwguo this really shouldn't ever happen... if it does, it's basically a "system error" state that we don't handle today. So it's appropriate for it to be big and red :)

**Comment by scottsun94** [comment]
Fixed
