### ISSUE TITLE
[autoscaler] Workers can silently fail to start.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3408]
If the `worker_start_ray_commands` are incorrect, then the resulting error can be lost into the void. I encountered this when doing

```
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --redis-address=$RAY_HEAD_IP:6379 --resources={"Custom":1}
```

That seemed to fail, but I couldn't find the error message anywhere.

The failure is presumably the escaping issue in https://github.com/ray-project/ray/issues/3407.

Of course, if I watch the monitor logs, then I do see that the nodes failed to start.

**Comment by ericl** [comment]
If it shows up in the monitor logs, then it's fine right? That's where users should look for cluster setup issues.

**Comment by robertnishihara** [comment]
That would be fine. I don't remember seeing the actual error message (just something like "nodes failed to start"), but I need to double check that.
