### ISSUE TITLE
[Ray component: Core] RFC: add ability to specify a network interface from the command line

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#34094]
### Description

Pulled out of [issue 22732](https://github.com/ray-project/ray/issues/22732#issuecomment-1492026407)

Systems with more than one network interface can specify `ray start --node-ip-address`. This should be used globally:
- in `GcsServerAddress`
- as a default for `RAY_REDIS_ADDRESS` if it is not specified
- in the autoscalar when starting workers
- a new `--address` option should be added to `ray stop` to specify which nodes to kill
Also, when starting workers, `ray start --address 172.0.0.1:6379` should use an IP address in the local node which is in the same subnet as `172.0.0.1`.

### Use case

Systems with more than one network interface (often occurs in SLURM systems) can fail to connect to the HEAD node. See for instance these related issues:
- Allow calling `ray stop --address 172.0.0.1:6379` to only kill the processes using that address (in case others are running) (#11509)
- Improve the warning message if the address is already in use (#26390)
- Add the address to the "Next Step" suggestions in the output after calling `ray job submit (#20441) and to the output of `ray start` (#18513)
- Emit a better error if `--node-ip-address` is not `localhost` when calling `ray start` (#19052, maybe #17769)
- When running `! ray start --head` in a jupyter notebook, it immediately crashes. Use `ray.init()` instead (not clear how this is connected?( (issue #22326)
- Using ray on a machine with 3 IP addresses, want the workers to all report the HEAD address (#8430, closed)
- When running a worker inside a docker, the desired address for connection may change (#5371)

In all these cases, and maybe more (around SLURM clusters) using more than one network interface causes problems since the way to connect to the HEAD node and its services is not well defined.

Implementing this feature would lead to a better UX experience and clearer error logs.

Edit: `ray start --node-ip-address`, not `ray start --address`. Perhaps this too should be clarified.

**Comment by rkooo567** [comment]
cc @peytondmurray

**Comment by peytondmurray** [comment]
To give a little more context for this work, this issue most frequently comes up in HPC environments, where multiple network interfaces are more common. In addition to the list of issues above, the [Ray support forum](https://discuss.ray.io/) has also seen a steady stream of support requests regarding this - see for example these discussions:

* [Ray on SLURM, unmatched Raylet address](https://discuss.ray.io/t/ray-on-slurm-unmatched-raylet-address/8509)
* [Client can’t find Raylet address in Ray > 1.5](https://discuss.ray.io/t/client-cant-find-raylet-address-in-ray-1-5/3943)
* [Ray on SLURM/HPC: starting worker nodes simultaneously](https://discuss.ray.io/t/ray-on-slurm-hpc-starting-worker-nodes-simultaneously/6399)
* [Ray on slurm - different ip addresses of worker nodes](https://discuss.ray.io/t/ray-on-slurm-different-ip-addresses-of-worker-nodes/6071)

With that in mind, I'd also like to think about how we can give users the information they need to understand and fix the issue themselves, by giving better error messaging. So in addition to adding an option to `ray start --address`, it might be useful if there is a check for other network interfaces, and a suggestion for the user on _what to do_, which is part of what is currently missing.

From one of the support threads above, the user posted this log message:

```
[2022-05-09 01:50:04,704 I 95279 95279] global_state_accessor.cc:357: This node has an IP address of xxx.xx.xxx.236, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
```

Here, the node address has no corresponding Raylet address - can we add a check for that, and an error message that suggests what to do about it? Or, does it make sense to automatically use the correct interface?

**Comment by jjyao** [comment]
Currently, if you have multiple IPs, you can use `--node-ip-address` to specify one: `ray start --head --node-ip-address=xxxx`. We need to make sure the specified node ip address is propagated to all the ray processes (currently it's not always the case #33541).

`ray.init()` also supports specifying a node ip via `ray.init(_node_ip_address=xxxx)`.

We should make sure `--node-ip-address` works well in all cases and add good documentation about how to use it.

**Comment by mattip** [comment]
The messaging in `ray start --head` seems to be pretty good. The messaging if the worker cannot connect needs improvement. It repeatedly says
```
023-05-17 19:58:01,008	ERROR utils.py:1389 -- Failed to connect to GCS. 
Please check `gcs_server.out` for more details.
2023-05-17 19:58:01,008	WARNING utils.py:1395 -- Unable to connect to GCS at 10.0.0.22:6380.
Check that (1) Ray GCS with matching version started successfully at the specified address,
and (2) there is no firewall setting preventing access.
```

This should say something about being unable to connect to ray head, and then "check (1) ray head was started at 10.0.0.22:6380 (2) the IP address 10.0.0.22 can be reached from this worker and (3) there is no firewall setting preventing access."

**Comment by mattip** [comment]
Documentation: there should be a FAQ on the [slurm page](https://docs.ray.io/en/latest/cluster/vms/user-guides/community/slurm.html#examples-and-templates) about networking issues, describing `--node-ip-address` and how to determine (using nstat?) how to reach the head node from a perhaps masked docker/slurm machine

**Comment by mattip** [comment]
The two PRs that came out of the discussion of this issue were closed, so I am going to close the issue. There is probably more to do, but I think we have provided enough information for most users to find their way through using more than one network interface.
