### ISSUE TITLE
[Core] Clean up process leaks in worker processes, even if worker process crashes

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#34125]
In https://github.com/ray-project/ray/pull/33976 we fix certain worker child process leaks by listing them and killing them when the core worker shuts down. This is not a complete solution, as it will still leak processes if the worker process crashes.

We should have a better story around cleaning up leaked processes. One potentially solid implementation is to configure the raylet with `PR_SET_CHILD_SUBREAPER`, so that all orphaned descendant processes are re-parented to the raylet. The raylet would then periodically poll its immediate child processes and clean up any that are not known worker processes.

**Comment by clarng** [comment]
this is important as the os or oom killer may kill the worker process, i.e. crash is part of 'normal' operation

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/issues/26118 Duplicates

**Comment by cadedaniel** [comment]
Closing in favor of https://github.com/ray-project/ray/issues/26118
