### ISSUE TITLE
[Tune] What is the parameters set that PBT copies from ? (question) 

### ISSUE THREAD

**Issue by chjq201410695** [ray-project/ray#3416]
I have two questions:

1. How do I  properly use PBT combining with a kind of search algorithm?

According to my understanding, in this case, program chooses a set of hyperparameters through search algorithm as initial hyperparameters firstly. then, PBT will make some mutations based on the initial hyperparameters during training progress.  that's right?

So, a proper way that combines PBT with a kind of search algo may be: 

① set a related large interval of hyperparameters in search algos, and set a smaller interval to hyperparam_mutations?

or,
② set hyperparam_mutations instead of search algos.

2. How does a worker of PBT copy the hypermeters from other workers?

if I set a search algo. the worker of PBT copy hypermeters from the search_space of the search algo, or from the hypermeters set by hyperparam_mutations in PBT?

Looking forward your response, thank you~

**Comment by richardliaw** [comment]
Closing this for now, but feel free to reopen if you have questions.
