### ISSUE TITLE
[data] release test failure: streaming_data_ingest_benchmark_1tb

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34162]
### What happened + What you expected to happen

test failing with no clear reason, asking infra team to see if it should have logs

### Versions / Dependencies

2.4.0

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1535#0187581b-8a96-4646-ab3b-d67f117d1301

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
@clarng : so when was the last time this test was passing? Thanks

**Comment by clarng** [comment]
> @clarng : so when was the last time this test was passing? Thanks

on release branch it was passing Tuesday, the new cherry picks since then don't seem related to this failure

Also the test didn't run at all, looks like Ray didn't come up - still digging

**Comment by jianoaix** [comment]
Since it's infra error, re-trying it to see if the test can get to run and pass.

**Comment by jianoaix** [comment]
And it passed: https://buildkite.com/ray-project/release-tests-branch/builds/1535#01875cc0-92ff-4d5b-9f1a-bbdf53bbbf52

**Comment by clarng** [comment]
looks like the agent got killed, which causes the raylet to die and not come up. Not sure yet if this is infra or ray

**Comment by clarng** [comment]
seems like this could be due to port conflict in product, not a release blocker
