### ISSUE TITLE
[core][state] Task backend : detached actor handling

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#34176]
Handling detached actor tasks properly. If the task that submits the detached actor fails, detached actor tasks should not be marked failed.

**Comment by rickyyx** [comment]
We should also handle detached actor when job finishes. Right now, if a job finishes, any running tasks from the detached actor would be marked as failed incorrectly.

**Comment by rkooo567** [comment]
@rickyyx is this not fixed yet?

**Comment by rickyyx** [comment]
i beleive this is fixed since we also clean up after worker died.
