### ISSUE TITLE
[Data] UX improvements

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#34175]
UX improvements for Datasets

- [ ] #34540
- [ ] #34541
- [ ] If the output batch contains a single column and that columns name is "__value__", then strip the column
- [ ] Same thing as 3 but for output rows as well as batches
- [ ] Get rid of "default" batch format, and default to "pandas" instead.

cc @c21 @ericl

**Comment by ericl** [comment]
It sounds good, but (1) needs more specification. Do you mean that rows should just be 1-sized batches (remove the concept of rows)? For both map() and iter_rows()?

> Get rid of "default" batch format, and default to "pandas" instead.

Makes sense, though we would break for simple row right?

**Comment by amogkam** [comment]
For 1, it wouldn't be a full batch, but would use Pandas/Arrow's concepts of a row instead of ours. Like `pd.Series` instead of our own PandasRow.

**Comment by amogkam** [comment]
Hmm yeah simple batches would be tricky. Should we make batch_format required then?

**Comment by ericl** [comment]
Maybe we should just rename default to pandas, and have simple blocks bypass pandas for now. That's the current semantics for "default" anyways.

**Comment by amogkam** [comment]
Currently "default" also has a separate path for tensor datasets which return Numpy array. I think this should just go down the Pandas path as well.

**Comment by ericl** [comment]
For (1) I think it makes sense for pandas, but Arrow doesn't have a row format I believe. Array is a type not a row.

**Comment by amogkam** [comment]
3-5 are resolved by strict mode, but re-opening as 1 and 2 are unresolved still

**Comment by ericl** [comment]
I don't think (1) is valid: tablerow is basically a dict, which is more consistent with the new numpy default format as well.

(2) will be tackled later with the streaming doc update.

Let's file separate issues for doc updates if necessary.

**Comment by amogkam** [comment]
For 1, we don’t want to return dict for pandas and arrow batch format. For numpy, this is fine, but we should probably get rid of the TableRow abstraction.

will leave this open until we can create separate issues.

**Comment by amogkam** [comment]
Created separate issues for the remaining concerns. Going to close this one.
