### ISSUE TITLE
[data] release test failure: dataset_shuffle_push_based_random_shuffle_100tb

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34170]
### What happened + What you expected to happen

started to fail recently (timing out) after running 8 hrs

e.g. https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_jv6r66hzdef9zx4dylhkmfxsga

success run before took 3 hrs to finish : https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_vc3t9r3se8lkd1za9w1enfssng

<img width="1433" alt="Screen Shot 2023-04-07 at 12 45 10 PM" src="https://user-images.githubusercontent.com/22830327/230668308-3f950716-4f0b-4ebf-a9c2-026bd25ce4e5.png">
<img width="1055" alt="Screen Shot 2023-04-07 at 12 44 59 PM" src="https://user-images.githubusercontent.com/22830327/230668321-c7c1b1af-d5d5-49cf-ae08-a5cdf57ccc03.png">

### Versions / Dependencies

master and  2.4.0

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_jv6r66hzdef9zx4dylhkmfxsga

### Issue Severity

None

**Comment by jianoaix** [comment]
Was it failing *after* the cherrypicks made in last couple days?

**Comment by clarng** [comment]
the run that first fail was apr 2 on master, branch cut happened on 4th

**Comment by jianoaix** [comment]
bisecting: https://buildkite.com/ray-project/release-tests-pr/builds?branch=master

**Comment by jianoaix** [comment]
The test tool itself is broken, seems missing dependency:

```
Traceback (most recent call last):
--
  | File "ray_release/scripts/run_release_test.py", line 18, in <module>
  | from ray_release.glue import run_release_test
  | File "/tmp/release-u8BE1A8z33/release/ray_release/glue.py", line 11, in <module>
  | from ray_release.command_runner.anyscale_job_runner import AnyscaleJobRunner
  | File "/tmp/release-u8BE1A8z33/release/ray_release/command_runner/anyscale_job_runner.py", line 22, in <module>
  | from ray_release.file_manager.job_file_manager import JobFileManager
  | File "/tmp/release-u8BE1A8z33/release/ray_release/file_manager/job_file_manager.py", line 8, in <module>
  | from google.cloud import storage
  | ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)
```

**Comment by jianoaix** [comment]
While the test tool is broken for bisecting, I'm looking at logs. It seems the successful run actually had more spilling:
- Successful run: `(raylet, ip=10.0.10.197) Spilled 2099323 MiB, 367864 objects, write throughput 885 MiB/s.`
- Failed run: `(raylet, ip=10.0.40.230) Spilled 524833 MiB, 100387 objects, write throughput 1093 MiB/s. `

This may indicate the failed run was completely stuck and not making progress (not even spilling to disk), and then got timeout.

**Comment by jianoaix** [comment]
So the bisecting pointed to this PR the culprit: https://github.com/ray-project/ray/commit/adb67759459bb3b69402bf9b21a3fb7f6791c628
The job: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_7b65v5tgs7uwsh975wbckkvvau
@clarng 

The commit right before this PR passed: eae4e78a412867f7e375ed7fe22d47e4ce4ffb2b: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_4a8rsymheiljps4javg4gfbb6v

And all trials earlier than this PR.

**Comment by ericl** [comment]
It actually makes sense that PR would regress this (actually, that was one of the main potential regression concerns of that change).

Let's split into a short term and long term resolution?

- Short term I think we should add a ray config to allow reverting to the previous behavior. We can turn this on by default for this test only, I think, since it is a niche use case for now.

- Longer term we should probably adapt the scheduling API to allow more flexible level of softness.

@jjyao what do you think of this plan?

**Comment by jjyao** [comment]
Given it does have negative impact on some workloads, should we keep the old behavior by default for the sake of backward compatibility and safety. 

For 2.4 we can introduce a private (used by dataset only) `_spill_on_unavailable` option to `NodeAffinitySchedulingStrategy` and only set to true by dataset. It should be a pretty small change and I can get it done by EOD.

**Comment by ericl** [comment]
I'm ok with that plan, but can we also figure out the proper API in 2.5?

**Comment by jjyao** [comment]
Yes. So 2.4 we use the private option. In 2.5 we figure out the proper API, remove the private option and pick the default behavior.

**Comment by jianoaix** [comment]
@jjyao The PR seems to break the CI: https://buildkite.com/ray-project/oss-ci-build-pr/builds/18212

**Comment by jjyao** [comment]
@jianoaix which CI test? I checked https://flakey-tests.ray.io/ which looks good.
