### ISSUE TITLE
Raylet dies if driver exits before a worker returns from `ray.get`

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3418]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Ray installed from (source or binary)**: source

### Describe the problem
1. A worker for a job is blocked in a `ray.get`.
2. The driver for the job exits.
3. The raylet learns about the driver removal, and cleans up local state. This removes all tasks for the job in the local queue and kills the blocked worker.
4. The raylet processes the blocked worker's disconnection. It calls `HandleTaskUnblocked` and then fails [here](https://github.com/ray-project/ray/blob/0d56fc10ccf0802ae7b335532698b4b1fc573fe4/src/ray/raylet/node_manager.cc#L1240) because the task has already been removed in step 3.

There are two ways to fix the issue. One is to just skip the calls to `HandleTaskUnblocked` if the worker is already dead. This will work, but it's brittle since any accounting usually done in `HandleTaskUnblocked` will have to be duplicated in step 3. In fact, this is already partly true for task dependency management, which is currently done [here](https://github.com/ray-project/ray/blob/0d56fc10ccf0802ae7b335532698b4b1fc573fe4/src/ray/raylet/node_manager.cc#L564), instead of relying on the cleanup for failed tasks in [NodeManager::TreatTaskAsFailed](https://github.com/ray-project/ray/blob/0d56fc10ccf0802ae7b335532698b4b1fc573fe4/src/ray/raylet/node_manager.cc#L1085).

I think the better way to do this is to only remove tasks that are not `RUNNING` or `BLOCKED` when cleaning up tasks for a dead driver. The remaining tasks will then get cleaned up once their corresponding workers exit.

### Source code / logs
```
F1127 19:24:45.846309 23444 scheduling_queue.cc:236]  Check failed: task_ids.size() == 0
*** Check failure stack trace: ***
    @           0x598438  google::LogMessage::Fail()
    @           0x59837c  google::LogMessage::SendToLog()
    @           0x597cbe  google::LogMessage::Flush()
    @           0x597ab9  google::LogMessage::~LogMessage()
    @           0x4e3c80  ray::RayLog::~RayLog()
    @           0x563164  ray::raylet::SchedulingQueue::RemoveTasks()
    @           0x563332  ray::raylet::SchedulingQueue::RemoveTask()
    @           0x51d15c  ray::raylet::NodeManager::HandleTaskUnblocked()
    @           0x527dde  ray::raylet::NodeManager::ProcessDisconnectClientMessage()
    @           0x5289a8  ray::raylet::NodeManager::ProcessClientMessage()
    @           0x4985ac  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionIN5boost4asio5local15stream_protocolEEEElPKhEZNS1_6raylet6Raylet12HandleAcceptERKNS3_6system10error_codeEEUlS8_lSA_E0_E9_M_invokeERKSt9_Any_dataOS8_OlOSA_
    @           0x4ef2c0  ray::ClientConnection<>::ProcessMessage()
    @           0x4ef813  ray::ClientConnection<>::ProcessMessageHeader()
    @           0x4eadb8  boost::asio::detail::read_op<>::operator()()
    @           0x4eb4d6  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @           0x490e08  boost::asio::detail::epoll_reactor::descriptor_state::do_complete()
    @           0x491768  boost::asio::detail::task_io_service::run()
    @           0x48854e  main
    @     0x7f2d0aa7b830  __libc_start_main
    @           0x48caa9  _start
    @              (nil)  (unknown)
```

**Comment by robertnishihara** [comment]
@stephanie-wang this has been fixed, right?

**Comment by stephanie-wang** [comment]
I believe so.
