### ISSUE TITLE
[dashboard] dashboard error because of gpustat version 1.1

### ISSUE THREAD

**Issue by yuanwu2017** [ray-project/ray#34196]
### What happened + What you expected to happen

2023-04-09 08:36:28,479 ERROR services.py:1195 -- Failed to start the dashboard: Failed to start the dashboard, return code 1
 The last 10 lines of /tmp/ray/session_2023-04-09_08-36-26_413307_64/logs/dashboard.log:
  File "/usr/local/lib/python3.8/dist-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 52, in <module>
    import gpustat.core as gpustat
  File "/usr/local/lib/python3.8/dist-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/usr/local/lib/python3.8/dist-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/usr/local/lib/python3.8/dist-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'

There is no error when using the gpustat 1.0.0

### Versions / Dependencies

Ray 2.2.0

### Reproduction script

ray start --node-ip-address=${head_address} --head --dashboard-host='0.0.0.0' --dashboard-port=8265

### Issue Severity

None

**Comment by scottsun94** [comment]
cc: @alanwguo @rkooo567

**Comment by rkooo567** [comment]
let me try repro when I have bandwidth

**Comment by mattip** [comment]
Can you verify what version of nvml you are using (either `pip list` or `conda list`) ?

**Comment by yuanwu2017** [comment]
# ls -al $(python -c 'import pynvml; print(pynvml.__file__)')
-rw-r--r-- 1 root staff 113 May 17 01:31 /usr/local/lib/python3.8/dist-packages/pynvml/__init__.py
# sha1sum $(python -c 'import pynvml; print(pynvml.__file__)')
cce9f10ef0eeed0de26d200ceea3632692da884d  /usr/local/lib/python3.8/dist-packages/pynvml/__init__.py
# pip list | grep nvidia
nvidia-ml-py                11.525.112

**Comment by wookayin** [comment]
The pynvml.py file is only 113 Bytes which is weird. Can you paste the content of the file?

**Comment by yuanwu2017** [comment]
```
# cat /usr/local/lib/python3.8/dist-packages/pynvml/__init__.py
from .nvml import *

from ._version import get_versions
__version__ = get_versions()['version']
del get_versions
```

**Comment by yuanwu2017** [comment]
According to @wookayin analysis, the wrong pynvml should be used in my environment. If most people don't have this issue, I think this issue can be closed. I will continue to see who introduced this wrong package. thanks.
