### ISSUE TITLE
rsync_up should be rsync-up?

### ISSUE THREAD

**Issue by lw394** [ray-project/ray#3419]
### System information
- OSX 10.12.6:
- installed from binary:
- ray 0.5.3:
- python 2.7:

ray rsync_up example-full.yaml /local/path/to/folder /home/ubuntu/folder

### Describe the problem
Small error in documentation (https://ray.readthedocs.io/en/latest/autoscaling.html#manually-synchronizing-files)
should be `-` and not `_`

### Source code / logs
Error: No such command "rsync_up".

**Comment by richardliaw** [comment]
Seems to work for me... can you try `ray --help`?

**Comment by ericl** [comment]
Mine seems to have changed to `-` as well...

**Comment by ericl** [comment]
Click broke it: https://github.com/pallets/click/issues/1123
