### ISSUE TITLE
[Infra] Cluster launcher release test failure (aws_cluster_launcher)

### ISSUE THREAD

**Issue by clarng** [ray-project/ray#34230]
### What happened + What you expected to happen

oss tracker for the same issue in anyscale: https://github.com/anyscale/product/issues/19019

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1470#018710b9-a17d-40b1-a360-9358290f29f3

### Issue Severity

None

**Comment by architkulkarni** [comment]
Closed by https://github.com/anyscale/product/pull/19270

**Comment by architkulkarni** [comment]
It passed the last few runs (Wed/Thur/Fri of last week), let me know if it fails again!

**Comment by clarng** [comment]
thanks, verified it is also fixed on release branch : https://buildkite.com/ray-project/release-tests-branch/builds/1535
