### ISSUE TITLE
[GreenRay] Continuous run for Core release tests

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#34242]
Capture a list of tasks to:
- Setting up the ability to run only tests based on AI-selection algorithm
- Run AI-selected tests continuously (on a few hours basis)

**Comment by aslonnie** [comment]
do we still target to use "AI-selection"?

**Comment by can-anyscale** [comment]
We might or might not need it for weekly release, I'm not sure yet ;)

**Comment by can-anyscale** [comment]
we're actually going this now ;)
