### ISSUE TITLE
[GreenRay] Automated fixing release test failures

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#34243]
Capture a list of tasks to:
- Detect when a core release tests start to fail
- Classify infra vs application code issue
- Open issues for repetitive application code issue
- Bisect and auto-revert blame PRs

**Comment by aslonnie** [comment]
> Bisect and auto-revert blame PRs

do we still plan to do this part?

**Comment by can-anyscale** [comment]
Yess, we will need to do auto-revert for weekly release

**Comment by can-anyscale** [comment]
bisect and blame is done; we didn't do auto-revert, the blame rate is manageable by human
