### ISSUE TITLE
[serve] Implement backpressure by rejecting queries if `max_concurrent_queries` is exceeded

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#34280]
Currently `max_concurrent_queries` is only respected by the caller. The replica will queue queries indefinitely, as will the HTTP proxy. This causes stability issues if the system is overloaded.

Proposed changes:

- In each replica, if `max_concurrent_queries` is exceeded, raise a `BackpressureException` with a relevant message.
- Support configuring `max_concurrent_queries` in the HTTP options in the config. In the HTTP proxy if `max_concurrent_queries` is exceeded (or a `BackpressureException` is returned by a downstream replica), return a [503 service unavailable](https://www.rfc-editor.org/rfc/rfc7231#section-6.6.4) code.

**Comment by edoakes** [comment]
Notes to self:

- Ensure that the HTTP proxy can spawn > `max_concurrent_queries` coroutines.
- Make updating `max_concurrent_queries` require a "heavyweight update" (can't be dynamically set anymore).

**Comment by sihanwang41** [comment]
> In each replica, if max_concurrent_queries is exceeded, raise a BackpressureException with a relevant message.
Another solution: In the replica level, we can rely on the ContextVar to have a timeout stuff (set start time in the context var and passed into the replica). If timing out, we can directly raise timeout exceptions. 
It might be easier for customer to understand (qps is not very intuitive to tune). downside is that we introduce another concept to control the system pressure.

BTW I am seeing https://www.uvicorn.org/settings/#resource-limits `limit-concurrency` might help our use case.
