### ISSUE TITLE
Reduce the lineage and object checkpointing overhead

### ISSUE THREAD

**Issue by adoda** [ray-project/ray#3429]
### Describe the problem

Reduce the lineage and object checkpointing overhead. 

We are building a Ray cluster for our employees to submit their machine learning tasks, including deep learning and reiforcement learning tasks. As a production system (and a potential cloud service), stability and fault tolerance are quite essential for us. Currently, Ray already provides some fault tolerance features, such as actor checkpointing and object reconstruction. We are interested in contributing more to help ensure the quality of service.

According to the early discussion between us, the community currently has no plan for [Object Checkpointing](https://docs.google.com/document/d/1lCIECdrVGGrn0U-SaDG8bCum8ztbs55At11BiFzeT7c/edit#heading=h.1qt4ke77ip3e). We internally discussed about it and propose a desgin for it.
### Source code / logs

We create a product requirement document (PRD) for this issue:
https://docs.google.com/document/d/1hNsCZa1yvNN7R5clj4OoMReistgZg97az5uuEhC5Pbc/edit

**Comment by robertnishihara** [comment]
Thanks @adoda, in the doc, could you say more about the requirements? For example, what scenario or application currently does not work well that needs to be supported?

cc @ujvl @stephanie-wang

**Comment by adoda** [comment]
Ok, we will add more info about the requirements. @xutianming

**Comment by xutianming** [comment]
@robertnishihara Object checkpointing is aimed to bound the cost of object reconstruction which is originally proposed in [this prd](https://docs.google.com/document/d/1lCIECdrVGGrn0U-SaDG8bCum8ztbs55At11BiFzeT7c/edit#) (probably from @stephanie-wang)

**Comment by ujvl** [comment]
[Here's](https://docs.google.com/document/d/1kAz1vIxXjDr1lIOR47-GZboHq5CwLrNWu4FqP9UaIYw/edit?usp=sharing) an updated doc (WIP) based on that one. It would be helpful to get some feedback, particularly on the user API, and more clarity on your specific use cases.

**Comment by adoda** [comment]
Thanks @ujvl , the doc is very helpful. Do you have a implementation or any plan for it?

**Comment by ujvl** [comment]
@adoda Not yet, will give it a go some time these next couple weeks.

**Comment by xutianming** [comment]
@ujvl Thanks for providing the current progress. I made some comments in your design doc. 

We are interested in taking part in the implementation of it.

**Comment by xutianming** [comment]
@ujvl Currently, we don't have any specific use cases that require checkpointing. We are just starting to build the Ray cluster, but we have much experience on Tensorflow. 

Our user applications mainly run on 2 clusters with hundreds of GPU cards and hardware failures are pretty common. Tensorflow has few fault tolerance features so Ray is a great complement. Good checkpointing mechanism could fasten object reconstruction (which is the main fault tolerance feature of Ray, I think), increase job completion rate and resource utilization. 

As a computing platform supporting more than 2000 developers, we might not focus on specific use cases, but we care much about cluster stability, efficiency and resource usage.

**Comment by ujvl** [comment]
Can you expand on how _object_ checkpointing will help from a cluster stability/resource utilization standpoint with running Ray as a cloud service? Is the concern that GCS will accrue large amounts of metadata over time as many jobs are submitted? That is mitigated from garbage collection at the driver completion level. Object checkpointing isn't necessary to keep the cluster's memory utilization low from that perspective.

My understanding is that checkpointing would only be helpful for long-running applications, in which case the question is what long running applications would be using tasks over actors? (correct me if I'm wrong anywhere)

**Comment by xutianming** [comment]
> Can you expand on how _object_ checkpointing will help from a cluster stability/resource utilization standpoint with running Ray as a cloud service? Is the concern that GCS will accrue large amounts of metadata over time as many jobs are submitted? That is mitigated from garbage collection at the driver completion level. Object checkpointing isn't necessary to keep the cluster's memory utilization low from that perspective. Or are there other concerns that this would address?

Sorry for misusing "resource utilization". I meant to say "effective resource utilization" or "reduce waste of resource". 
Object checkpointing helps object reconstruction by reducing duplicated computation. Recalculating lost objects is a waste of resource. 

> My understanding is that checkpointing would only be helpful for long-running applications, in which case the question is what long running applications would be using tasks over actors? (correct me if I'm wrong anywhere)
I think most long running applications could use actors.

**Comment by stephanie-wang** [comment]
@xutianming, do you have a minimal application example that we could use to test object-level checkpointing? Right now I think we're struggling to find an example where it is not enough to simply checkpoint actor state, since that is where most of the state for a long-running job actually ends up getting stored.

**Comment by xutianming** [comment]
How about this one? @stephanie-wang 
`@ray.remote
def func_a():
	# Do complicated computation
	time.sleep(3600)
	return 1

@ray.remote
def func_b(arg):
	return arg + 1

@ray.remote
class ActorA(object):
	def func_c(self):
		a_ret = func_a.remote()
		# Do complicated computation
		time.sleep(3600)
		# Plasma store evicts a_ret
		return func_b.remote(a_ret)`

**Comment by adoda** [comment]
For this example, Could it failover from the functions table in GCS？ @stephanie-wang 

And this is other example:

```
import ray
import os
import random

@ray.remote
def f():
  test_obj = random.random()
  return test_obj

@ray.remote
class TestActor(object):
  def run(self):
    result = ray.get(f.remote())
    return result

ray.init(redis_address=os.environ.get("REDIS_ADDRESS"))
actor = TestActor.remote()
print("----:", ray.get(actor.run.remote()))
```

Could we failover from actor's ckpt when 'test_obj' is loss?

**Comment by robertnishihara** [comment]
@adoda @xutianming are you concerned about the scenario where the object is lost because of a failure or because of eviction? In the eviction case, I think we can come up with solutions to prevent the eviction from happening in the first place. In the failure case, rerunning the task seems probably ok because failures should be infrequent.

Or am I misunderstanding the scenario that you have in mind?

**Comment by xutianming** [comment]
> @adoda @xutianming are you concerned about the scenario where the object is lost because of a failure or because of eviction? In the eviction case, I think we can come up with solutions to prevent the eviction from happening in the first place. In the failure case, rerunning the task seems probably ok because failures should be infrequent.
> 
> Or am I misunderstanding the scenario that you have in mind?

Rerunning the task (aka. object reconstruction) is enough currently. Checkpointing is just designed to improve object reconstruction.

As to fault tolerance, supporting actor reconstruction has higher priority.
