### ISSUE TITLE
[RLlib] - Looks like the commented code in cartpole_lstm.py example is outdated

### ISSUE THREAD

**Issue by heng2j** [ray-project/ray#34316]
### What happened + What you expected to happen

Hi Team,

While I was debugging my issue for running inference on my trained PPO agent with LSTM wrapper, I discovered that these commented code in [cartpole_lstm.py](https://github.com/ray-project/ray/blob/master/rllib/examples/cartpole_lstm.py#L87-L118).

I am getting the following error when running the example with the cemented code. 
`TypeError: compute_single_action() takes from 1 to 3 positional arguments but 5 were given`

Can you advise? 

Thank you,
Heng 

### Versions / Dependencies

Ray 2.2.0
Python 3.8
MacOS

### Reproduction script

https://github.com/ray-project/ray/blob/master/rllib/examples/cartpole_lstm.py#L87-L118
```
    # To run the Algorithm without ``Tuner.fit``, using our LSTM model and
    # manual state-in handling, do the following:

    # Example (use `config` from the above code):
    # >> import numpy as np
    # >> from ray.rllib.algorithms.ppo import PPO
    # >>
    # >> algo = PPO(config)
    # >> lstm_cell_size = config["model"]["lstm_cell_size"]
    # >> env = StatelessCartPole()
    # >> obs, info = env.reset()
    # >>
    # >> # range(2) b/c h- and c-states of the LSTM.
    # >> init_state = state = [
    # ..     np.zeros([lstm_cell_size], np.float32) for _ in range(2)
    # .. ]
    # >> prev_a = 0
    # >> prev_r = 0.0
    # >>
    # >> while True:
    # >>     a, state_out, _ = algo.compute_single_action(
    # ..         obs, state, prev_a, prev_r)
    # >>     obs, reward, done, truncated, _ = env.step(a)
    # >>     if done:
    # >>         obs, info = env.reset()
    # >>         state = init_state
    # >>         prev_a = 0
    # >>         prev_r = 0.0
    # >>     else:
    # >>         state = state_out
    # >>         prev_a = a
    # >>         prev_r = reward

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by heng2j** [comment]
Okay never mind, I should have read the documentation first: https://docs.ray.io/en/latest/rllib/package_ref/algorithm.html?highlight=compute_single_action#ray.rllib.algorithms.algorithm.Algorithm.compute_single_action.

I am able to run it after specify `prev_action` and `prev_reward`

```python
a, state_out, _ = algo.compute_single_action(obs, state, prev_action=prev_a, prev_reward=prev_r)
```

**Comment by heng2j** [comment]
I will still open this issue until the Ray team aware that we still need to update the comments in https://github.com/ray-project/ray/blob/master/rllib/examples/cartpole_lstm.py#L87-L118

**Comment by Rohan138** [comment]
Putting in a PR to fix this now, thanks for bringing this up!
