### ISSUE TITLE
CPU Cores are not fully utilized.

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#3433]
### System information
-  **OS Platform and Distribution **: Ubuntu 16.04.2 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6.7

### Describe the problem
I am using rllib A3C algorithm to train an agent using 12 workers. My machine is an 32 core (12 Physical cores) machine. However, when I checked the cpu usage using htop none of the core was being fully utilized. Most of the processes are **ray_Policy Evaluator** which are in Sleep state for most of the time. 

### Source code / logs
Here is the algorithm configuration file I used.

`local-view:
  env: tsim-v0
  run: A3C
  checkpoint_freq: 500
  config:
    num_workers: 12
    sample_batch_size: 1
    use_pytorch: false
    vf_loss_coeff: 0.5
    entropy_coeff: -0.01
    gamma: 0.99
    grad_clip: 40.0
    lambda: 1.0
    horizon: 2000
    lr: 0.0001
    observation_filter: NoFilter
    callbacks:
      on_episode_end: None
    model:
      use_lstm: true`

Here is the screenshot showing CPU usage.

[screenshot](https://imgur.com/a/z5gt3Nz)

**Comment by ericl** [comment]
I think this just means that the bottleneck is applying gradients. If you want to increase the compute on the workers you can increase the sample batch size which will improve learning as well up to a point.

**Comment by mynkpl1998** [comment]
Thanks, @ericl. I increased the batch size to 256 and CPU utilization of each core went up.
