### ISSUE TITLE
[CI] `linux://python/ray/tests:test_cancel` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#34343]
- 09278eb222555bacfa2dfe60fb11a1854dbd6066 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3348#018776e2-fedc-44d1-b3c0-b5d9ceb602fe)
- 05f6e5d0844144ee9ec1e2c32c3a880dfc707c4d FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3347#018776e0-5525-4b75-b810-8cb60a24b3b5)
- c65de685f138f52f40a9c5c744318b26f6f87f30 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3346#018776d7-b969-4a69-a074-bed30bcb094d)
- c65de685f138f52f40a9c5c744318b26f6f87f30 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3346#018776d7-b987-4716-80a8-db62ccf1d662)
- 7fbc1fc05b230c6e0d04031dced824a04e14a3bd FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3336#01877689-dd16-4e21-93d8-96be4d57a25e)
- c9b3c0edd9fa4eabf51cb8ecde705fd378434db1 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3331#0187764a-3afc-45f5-be03-7a6e1a4bec8a)
- e3594e679da026efe74b47de10673e2b4305c343 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3330#01877633-3838-4b22-9a15-2b190058c28b)
- 0ecc1b8d2bfe703bcb9a125b8b75e546f8668a23 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3325#0187746c-c3f6-43a7-aaa3-05d8e9a09a03)
- 156be229fe2e0f2ac5db1d38d777fb2ee69c3510 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3300#0187720c-1162-4ab0-8ad5-fae809bc80da)
- d947fb025c6dcf2b88e54a2657f8c88833b3cbbb FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3298#018771b6-baa3-4165-8c4f-518d8ff855aa)
- 384446845f936f714bf2bd9f8f772c6b1ddf35f7 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3295#01877150-4713-4c94-9a43-1f2a6e602a61)
- 4168b9bdae689f92bf37c5b780bba3e788106801 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3286#01876e79-1d4c-4d8d-a536-07278946f2c9)
- 6fca66776f83c3a06dfdf4fc961f2ea33af443be FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3281#01876e19-6044-4df4-8d47-4faaa83191fb)
- f255ddae8c43c09db0d657f3ee807684835b1af7 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3280#01876df4-f959-4fdb-9be4-e8668aef48f6)
- 0a8471e428db203e4905428cf2566a4a1dbfdab5 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3279#01876dd3-6999-42ba-870d-8bf3405fe93f)
- 64b69dc2df7837d0171ae3890479206f3dc3b9ce FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3278#01876da7-74d0-4594-9af3-6f5c4b858769)
- d9aacb6de8c72b15a622ebcd4e6c36bc4a67dd88 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3272#01876d3e-4b89-4620-8a98-ba19ac75bc53)
- 45b9067b5f0c463a62eb5ac50dadcbb13399a982 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3271#01876d3c-787a-4fee-aeab-7394579b5c99)
- 79989b8f73ae4ea49fddc05fa4aa06a8fb5fe4d0 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3270#01876d1a-ede7-42c4-a1a3-5865dc3cbfab)
- aaac9cdc2300089a688ee8581e9f5e85816ff3df FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3268#01876cdd-b526-42f8-8c6f-8e9434fde5c3)
- 8c283cb449f1c28bc5276fc56075c9a6d59f99f2 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3264#01876c79-a7f7-4958-807a-c2d53e44c152)
- 10861d9f2ef19e845186b8925053a11c6812a161 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3260#01876913-3a7d-4e68-ad9d-d8f761506b8c)
- bd525f3ba30492d0fa55ffa002bcc188818debc5 FAILED [Buildkite :redis: (External Redis) (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3259#01876910-827b-4227-956c-00d2abca89cb)
- 82434e20372e6fc80c452a6b502174959fa61984 FAILED [Buildkite :python: (Medium A-J)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3252#01875ee5-73cd-480e-9650-8700509966fe)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_cancel-END
....

**Comment by rkooo567** [comment]
cc @vitsai @rickyyx what about @vitsai takes this as she is working on cancel issue now?

**Comment by rkooo567** [comment]
@vitsai thanks for taking this!

**Comment by rickyyx** [comment]
Looks fixed! 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/11676094/232930454-0e7ad7fc-f2dc-4823-830c-0a906a5c356c.png">
