### ISSUE TITLE
[CI] `linux://:gcs_client_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#34344]
- e3533efbc98b9beb7c2ab1bd549dbb00cf72d30a FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3344#018776bc-f111-4888-919d-160b0f11319d)
- b01f7bceab5b0d2d0a84762c50e37c36e4459b65 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3313#01877309-ca0c-4fe6-9677-3d0b018d31fb)
- a9431c7e4a2846a773cbd9a689bb23db0a0d7cc8 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3308#01877277-c089-45d9-8e65-7b2e3a77a6c6)
- 4013930146add5f3cac3ba04a4896969ac0f3655 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3306#0187725a-09ae-480b-b46a-85df3ceb169c)
- d1e762982380cac938af0969f66e9f82a73d6697 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3292#0187708c-b184-42db-9d97-dd58f9fdbe40)
- f255ddae8c43c09db0d657f3ee807684835b1af7 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3280#01876df4-f900-40da-ad91-20ef4544a1f6)
- 4ad2cd162befd196b8210b0a572744dacb9b67cf FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3274#01876d95-33fe-4069-9a21-3e35132037ba)
- aaac9cdc2300089a688ee8581e9f5e85816ff3df FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3268#01876cdd-b4f7-4f74-b5fb-dab4590c5ca4)
- 4e1f42b5c8fc673e2b76a052e65ec977e4190f93 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3265#01876c8e-d6d0-436c-ad16-96cca85c6c67)
- 7ceb761330cb3edaaf457b4ea53ea9fb66dd3611 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3263#01876c79-9c7e-48a3-9d98-bc14ed0e96cb)
- a1a6902010dae553001da5d083907806fac74052 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3245#01875d5b-56c5-4216-bf4d-5f02bad936c9)
- 968f6e9132d5f6da76c05eee648a77b6bf0cc98e FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3229#0187580d-7c2e-42f6-a366-287e819eae66)
- 4c4f35a0b4fcfcba9928a363459d0844d738d84f FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3207#01875427-0605-41a9-af97-50987983e5a3)
- 3d335e1b2284866ee8078dc0af28bf7df4a2b586 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3205#018753b0-3c3e-4e37-b837-791bc2549803)
- fb441cedc92a663d4a11e2592803702910fb42e4 FAILED [Buildkite :cpp: Tests (ASAN)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3204#01875395-6e36-4bcd-8a6e-65346b80d588)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:gcs_client_test-END
....

**Comment by rickyyx** [comment]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/11676094/233131197-effb68f2-4a3a-42a0-b8a5-a3c63ba79b77.png">
Doesn't look like it worked?
