### ISSUE TITLE
Java tests are failing.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3434]
The Java tests were broken by https://github.com/ray-project/ray/pull/3422.

**Comment by stephanie-wang** [comment]
Looks like it's because that PR requires getting the dummy object returned by the actor creation task, and it is not filled in correctly in the Java frontend: [code](https://github.com/ray-project/ray/blob/master/java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java#L175).
