### ISSUE TITLE
Support commandline flags from user code in RayServe

### ISSUE THREAD

**Issue by xuanbozeng** [ray-project/ray#34351]
### Description

Currently, there is no clean way of passing user-defined flags (e.g., by argparse or gflags) in RayServe. For example,
- "serve run user_script.py --user_flag" assumes the flag is for Ray rather than for  user_script.py.
- Although "python user_script.py --user_flag" may not crush, these flags are still ignored by a serve.deployment decorated class. 
Another issue is if a user defines his/her own flags and intended to use them in a serve.deployment decorated class, an "unknown flags" failure will pop up due to unrecognized flags from Ray worker (e.g., --node-ip-address).

A potential  interface for allowing user-defined flags is to use "--":
serve run user_script:user_handle --<ray_flag> -- --<user_flag>

### Use case

The commandline flag is very common for any production-serving code.

**Comment by kevin85421** [comment]
@akshay-anyscale could you triage it? Thanks!

**Comment by akshay-anyscale** [comment]
This will be supported through https://github.com/ray-project/ray/issues/34542

**Comment by edoakes** [comment]
@xuanbozeng @kevin85421 please see the RFC and feel free to comment there :)
