### ISSUE TITLE
Ray 2.4.0 autoscaler for v1 k8s stack on GCP is broken

### ISSUE THREAD

**Issue by aslonnie** [ray-project/ray#34375]
### What happened + What you expected to happen

Expects to scale up / down with CPUs on a test, but it is not scaling. More details posted in slack.

### Versions / Dependencies

ray 2.4.0 release candidate

### Reproduction script

````
import ray
import time

ray.init()

@ray.remote(num_cpus=1)
def f(x):
    time.sleep(60)
    return x * x

futures = [f.remote(i) for i in range(30)]
print(ray.get(futures))
````

### Issue Severity

High: It blocks me from completing my task.

**Comment by wuisawesome** [comment]
@aslonnie please cherry pick #19620 or wait for it to merge, then create a _new_ ci namespace/branch and try again. Note that pushing to an existing one likely won't work (since there's state in product config repo that isn't flushed).

**Comment by aslonnie** [comment]
I think you mean https://github.com/anyscale/product/pull/19620

**Comment by aslonnie** [comment]
this seems to be fixed now.
