### ISSUE TITLE
[Data] Add example to ray.data.Dataset.schema

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#34405]
### Description

CSAT feedback from March 6, 2023: A simple example would be much more helpful!

I believe the redirected URL is here: https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.schema.html

https://analytics.google.com/analytics/web/#/report/content-event-events/a154591315w164762454p165427173/_u.date00=20221101&_u.date01=20230414&_.advseg=&_.useg=&_.sectionId=&_r.drilldown=analytics.eventCategory:RateTheDocs,analytics.eventAction:Suggestion,analytics.eventLabel:-%20A%20simple%20example%20would%20be%20much%20more%20helpful!&explorer-table.plotKeys=%5B%5D

### Link

https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.schema.html

**Comment by anyscalesam** [comment]
Reviewed with @c21 downgrading to p2 as scale and no escalations.

**Comment by richardliaw** [comment]
Example is added!
