### ISSUE TITLE
[CI] `osx://python/ray/dashboard:modules/reporter/tests/test_reporter` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#34408]
- b8bd7205733101bb1a67a3bcfbc97583b89572f4 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3392#01878035-9652-4c36-a4a6-c16e12dda062)
- 1f7058ee40b32c49b353e8e00806325744122d17 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3389#01877e7e-7f15-4e23-b961-cef7524a9ae6)
- 242d7b4b96cd5761b1b8a35bbff9c9e94865ba2b FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3386#01877d58-6285-41ec-8501-42c3d933b9f7)
- df53c234dc12631c495173350a18bf6e3004b112 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3385#01877cb6-3445-4455-9c82-840cb15c6840)
- 4571f1c1a2372e095a4c10d73bd4f17bfd1295f5 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3384#01877caf-d632-4845-b670-040fa796c18d)
- e86b562c316916bd999b7955ab04cfb6788770fb FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3383#01877c78-38bc-4574-9296-bf7c40bdcd6b)
- 3ea9f729cc6373b1d53fd55c02935879e24c4940 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3382#01877c6a-43aa-4947-ab5d-a2034e642e91)
- 687fdcfe51f2558f1bf900a87e111b95c1015e40 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3381#01877c5c-0534-4cf3-8d7c-a32d2446c6c7)
- f93b6f1cf5e79261da0b9ef67abefbfd4d384cad FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3380#01877c58-800a-404c-97bf-b2477995dab8)
- 17eb052ccda6a4bd90580a1ae9d3780a79bc2640 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3379#01877c3f-45ac-4e8c-8e9b-1a9b4d9071ca)
- d6071a6dcb8fb87d2f64c7dd9683093163357bf3 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3378#01877c15-493e-45cb-ad7b-2273676356e4)
- f1b14d28761496358d8312d147fe6718e9139392 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3377#01877bd2-902b-4875-bb5f-7473728b2293)
- 10d0b8a632f2a1d66d1e1a31b124b58167f62053 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3375#01877b8f-fa27-4fa4-8782-8fbe2cbe1443)
- 120e0593664a6aa2317dc8fca3366edb653adfc4 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3374#01877b83-7ee2-4ae4-822c-ec52ff55f856)
- 98c6cd40b8491b6b794d70d45a65ef9b7c49479d FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3373#01877b80-5355-4f16-b932-c8ac5a7c3d2b)
- a821719691233e91a6c2652d94f6c9f4aa2c8c9f FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3372#01877b70-b05f-4d33-afd4-6a3cc0b33e0b)
- 1a0989a1c09581a799be28bdd2a09470cd928b28 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3371#01877b60-bbbf-4858-8fb1-bd2dfbf01da9)
- 250ecb8e59673260c88d31a15e021be2f3c95e0a FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3370#01877b4f-03a1-4a62-86a0-eaad10f3de93)
- 5c2d5f650dc89cd7352816f19e08c807d59ac40e FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3367#01877ac1-92a4-4ece-8ab6-69fed067cf0e)
- 4f2c770effc9c74a4ae575b50e16f6448fa04696 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3366#01877ab6-dc08-45fa-8ab4-e0d8d0fb12b5)
- 688ddf6ff84c93fcb4514ce1b1b57db3114a44e2 FAILED [Buildkite :mac: :apple: Ray Core Unit Tests and Dashboard](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3365#01877a99-e8b8-4dd5-9fbc-6d4e78b73f6a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/dashboard:modules/reporter/tests/test_reporter-END
....

**Comment by rickyyx** [comment]
Seems to be broken by this: https://github.com/ray-project/ray/commit/5e85794c0a06821df33634751411dbe7a3fd638b

**Comment by rkooo567** [comment]
@chaowanggg is this fixed?

**Comment by chaowanggg** [comment]
@chaowanggg Yes, this is fixed by reverting my PR

**Comment by rkooo567** [comment]
@chaowanggg I still see this is broken in the master?

**Comment by rkooo567** [comment]
<img width="1372" alt="Screenshot 2023-08-28 at 10 36 44 PM" src="https://github.com/ray-project/ray/assets/18510752/9ee6b727-a337-44c5-8e71-ae5fe76b596c">

**Comment by chaowanggg** [comment]
> 

Yes, that is because I merged the PR to fix the issue after reverting it. However, per our discussion before, the CI did not trigger mac test cases before merged into master. And I already made a new PR to fix the mac test cases error

**Comment by GeneDer** [comment]
Cherry-pick PR: https://github.com/ray-project/ray/pull/39027
