### ISSUE TITLE
[bug] Actor handle cannot be handled twice

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#3440]
Script to reproduce:
```
ray.init()

@ray.remote
class Foo(object):
    def method(self):
	pass

f = Foo.remote()
ray.get(f.method.remote())
f1 = ray.worker.pickle.loads(ray.worker.pickle.dumps(f))
ray.get(f1.method.remote())
f2 = ray.worker.pickle.loads(ray.worker.pickle.dumps(f1))
ray.get(f2.method.remote())
```

Right now, the above script will fail, because when we pickle and unpickle f1 to get f2. `f1._ray_actor_handle_id` is None. Then this line will fail: https://github.com/ray-project/ray/blob/07d8cbf414df48fc186f3b859512b50c2700c92c/python/ray/actor.py#L756.

However, if it's also wrong to simply change that line to `previous_actor_handle_id=ray.ObjectID(state["previous_actor_handle_id"])) if state["previous_actor_handle_id"] else None`. Because then f2's `previous_actor_handle_id` will be None and it will be considered as the original handle. 

Also, If I let f2 share f1's `previous_actor_handle_id`, this script still doesn't work. because `f1.method.remote()` and `f2.method.remote()` will use the same handle id (because of `compute_actor_handle_id_non_forked`) and counter to submit task. The latter task will be dropped by raylet, because raylet thinks it's a duplicate task submission. 

@robertnishihara @stephanie-wang what do you think is the best way to fix this issue?

**Comment by robertnishihara** [comment]
Related to https://github.com/ray-project/ray/issues/2115.

This is a bit tricky. Actor handles are a bit brittle currently in the way they can be used and passed around.

**Comment by stephanie-wang** [comment]
In #3560, I'm changing this to always set an actor handle ID, so we no longer store `"previous_actor_handle_id"`.

How does the following solution sound?
1. The original handle has `num_forks = 0, handle_id = nil`.
2. If the handle is passed into another task, then we do `handle.num_forks += 1` and store the new handle ID as `handle_id' = hash(handle.handle_id || num_forks)`. When the handle is unpickled as part of the task argument, it uses `handle_id'` as its handle ID directly.
3. If the handle is pickled, then we do `handle.num_forks += 1` and store the new handle ID as `handle_id' = hash(handle.handle_id || num_forks)`. When the handle is manually unpickled, it takes the stored value and hashes it with the current task ID, so its ID will be `hash(handle_id' || worker.current_task_id)`.

**Comment by raulchen** [comment]
@stephanie-wang sounds good to me.

**Comment by stephanie-wang** [comment]
No longer relevant.
