### ISSUE TITLE
[CI] Mac tests don't run automatically on every PR, causing us to break master if we break them

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#34409]
When someone creates a PR in ray-project/ray, we will run tests for that PR in buildkite. The MacOS tests are opt-in by default (cost reasons?). This causes us to occasionally miss running mac tests which breaks master.

See "Click here to run Mac OS" button below:

<img width="1142" alt="Screen Shot 2023-04-14 at 11 18 24 AM" src="https://user-images.githubusercontent.com/950914/232125415-97d93dff-1f9e-40bc-8590-e9ca59673c2b.png">

The impact is higher number of reverts and slower dev velocity

**Comment by rickyyx** [comment]
Also, I think if we enabled on all PRs, there might be a huge backlog on the mac tests (so simply enabling them by default might not be enough. We prob need more machines to keep up with the PR number)

cc @krfricke  and @rkooo567

**Comment by hora-anyscale** [comment]
@can-anyscale - can you please assign a priority label and remove 'triage'

**Comment by aslonnie** [comment]
won't fix.

mac tests are very expensive. we won't test it on every PRs. The test fixture / setup is also very fragile.

we can reconsider this when core team has a clearer macos golden workflow setup.

cc @jjyao

**Comment by aslonnie** [comment]
and we should be testing apple silicon ones too..
