### ISSUE TITLE
Documentation says that one can run "ray submit" but the submit command doesn't seem to exist

### ISSUE THREAD

**Issue by GiliR4t1qbit** [ray-project/ray#3441]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.13.6 
- **Ray installed from (source or binary)**: binary (via pip)
- **Ray version**: 0.5.3
- **Python version**: 2.7.14
- **Exact command to reproduce**: "ray submit cluster.yaml --tmux --start --stop tune_experiment.py" (after running "ray up cluster.yaml") see: https://github.com/ray-project/ray/blob/master/doc/source/autoscaling.rst

### Describe the problem

The [documentation](https://github.com/ray-project/ray/blob/master/doc/source/autoscaling.rst) for the autoscaler mentions the following:

> 
> You can also use ray submit to execute Python scripts on clusters. This will rsync the designated file onto the cluster and execute it with the given arguments.
> 
>     # Run a Python script in a detached tmux session $ ray submit cluster.yaml --tmux --start --stop tune_experiment.py
> 

However, trying to run the above gives the following error:

> Usage: ray [OPTIONS] COMMAND [ARGS]...
> 
> Error: No such command "submit".

Running `ray --help` gives a list of available commands which does not include `submit`.

**Comment by richardliaw** [comment]
Hey; can you try installing the latest snapshot of master? https://ray.readthedocs.io/en/latest/installation.html

**Comment by GiliR4t1qbit** [comment]
You are right, once I did that I see that the submit command is included.... I find that a bit confusing - that some documented features aren't in the latest pip release, but I guess it's unavoidable. I'll just check that it's working as documented, and if so this issue can be closed.

**Comment by GiliR4t1qbit** [comment]
I can confirm that ray submit does work as expected, once one has installed the bleeding edge version of ray. So, happy for this issue to be closed. By the way, nice work on the autoscaler, it's very cool!
