### ISSUE TITLE
[Serve dashboard] Show `serve status` output in ray dashboard for serve users

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#34438]
### Description

`serve status` output is very helpful for serve users to debug issues. Ideally, users can find the equivalent info in the serve UI of the Ray Dashboard
https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1681496424381359

**Comment by scottsun94** [comment]
The new serve ui in ray dashboard in 2.4 may already cover all the info in `ray status` output.

Waiting for Ben to confirm.

**Comment by alanwguo** [comment]
There are some missing pieces. Those are in this ticket: https://github.com/ray-project/ray/issues/34078

**Comment by scottsun94** [comment]
Fixed
