### ISSUE TITLE
[Tune] Example using outdated tune.report -> session.report

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#34434]
### Description

Feedback from CSAT from Dec 27, 2022:

"guide still using deprecated API (e.g. tune.report instead of session.report)"

https://analytics.google.com/analytics/web/#/report/content-event-events/a154591315w164762454p165427173/_u.date00=20221001&_u.date01=20230413&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:RateTheDocs,analytics.eventAction:Suggestion,analytics.eventLabel:guide%20still%20using%20deprecated%20API%20(e.g.%20tune.report%20instead%20of%20session.report)

### Link

https://docs.ray.io/en/master/tune/getting-started.html

**Comment by xwjiang2010** [comment]
cc @matthewdeng since there is work to fix `session.report`, there may be some dependencies.

**Comment by justinvyu** [comment]
Fixed in 2.7 docs revamp
