### ISSUE TITLE
[ray and Jupyter] Add a "disconnect" button for the output of ray.init in jupyter

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#34431]
### Description

When people run `ray.init()` in jupyter, it starts a ray job automatically and users can view it in Ray Dashboard.
<img width="548" alt="Screen Shot 2023-04-14 at 1 19 46 PM" src="https://user-images.githubusercontent.com/9677264/232170976-71f7d76a-390d-4307-b58c-583d0e53fdf7.png">

In order to kill the ray job, users have to run `ray.shutdown()`. People are not aware of this and it's easy to forget about it.
First, we should make it easier to do. Can we add a button like `disconnect` 

<img width="903" alt="Screen Shot 2023-04-14 at 3 53 10 PM" src="https://user-images.githubusercontent.com/9677264/232171700-83604da4-4731-4628-bfb5-8f8c18a63cb4.png">

### Use case

see above

**Comment by scottsun94** [comment]
cc: @richardliaw

**Comment by peytondmurray** [comment]
Great idea, I'll take this one!
