### ISSUE TITLE
[Raytune] segmentation fault encountered in data loader worker when num_workers > 1 and pin_memory = True

### ISSUE THREAD

**Issue by wzWang1991** [ray-project/ray#34456]
### What happened + What you expected to happen

We are seeing segmentation fault in the data loader worker after some "iterations" and in the main thread, it shows "RuntimeError: DataLoader worker (pid(s) 1760256, 1760385) exited unexpectedly".

Note that it only happens on 8-card machine with 2 physical cpu. It was fine with 4 card and 1 single physical cpu. And it's also ok if num_workers == 1 and pin_memory=False for dataloader. Otherwise, there will be similar issue. And this is also ok without Raytune, though I can only choose to run one training on one card or several cards, which is different that raytune starts 8 training on 8 cards at the same time.

### Versions / Dependencies

Ray 2.3.0
Pytorch 2.0

### Reproduction script

```
from ray.air import ScalingConfig
from ray.train.torch import TorchTrainer, TorchConfig
from torch.utils.data import DataLoader

import ray
from ray import tune

def trainable(config):
    N = 100000000
    train_data = list(range(N))
    loader_params = {'num_workers': 2, 'pin_memory': True}
    train_loader = DataLoader(train_data, drop_last=True,
                              batch_size=64, **loader_params)
    for i, item in enumerate(train_loader):
        if i % 10000 == 0:
            print(i)

def main():
    trainer = TorchTrainer(
        trainable,
        torch_config=TorchConfig(backend='nccl', init_method='tcp'),
        scaling_config=ScalingConfig(use_gpu=True, num_workers=1,
                                     trainer_resources={"CPU": 2}, resources_per_worker={"GPU": 1}))
    
    tuner = tune.Tuner(
        trainer,
        tune_config=tune.TuneConfig(
            metric="loss",
            mode="min",
            num_samples=100,
        ),
        param_space={"train_loop_config": {}},
        run_config=ray.air.RunConfig(local_dir="/tmp/test")
    )
    results = tuner.fit()

if __name__ == "__main__":
    main()
```

You will see the issue when it prints about 240000.

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hey @wzWang1991 can you check what version of `grpcio` you are using by calling `pip freeze | grep grpcio`? I believe this may be the same issue as https://github.com/ray-project/ray/issues/34194, in which `grpcio 1.53.0` is causing the problem.

**Comment by wzWang1991** [comment]
Thank you! It's exactly grpcio==1.53.0rc2.

Let me try 1.51.1 and get back to you.

**Comment by wzWang1991** [comment]
I verified and downgrading it fixed the issue. Thank you!
