### ISSUE TITLE
Some node is marked dead

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3446]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 447604a9fe6a3cac68f9bccfe3f090466c9559c5
- **Python version**: 3.6.5

### Describe the problem
<pre>
The node with client ID 1eadc9db2f074bfec34caf25dd5bf1f99fad0d59 has been marked dead because the monitor has missed too many heartbeats from it.
</pre>
and then some remote functions fail due to `likely worker died or was killed while executing the task`.

But there is no problem of dead node with `ray==0.5.3`

**Comment by ericl** [comment]
Can you attach the raylet logs / debug_state.txt files for this on https://gist.github.com ?
cc @stephanie-wang any other things that may help debug?

**Comment by stephanie-wang** [comment]
@llan-ml, can you also provide some information about your cluster configuration (e.g., what type of machines, how many)?

**Comment by llan-ml** [comment]
Sorry, I cannot reproduce this now. Perhaps our intranet was not stable then.

**Comment by richardliaw** [comment]
Closing this for now; feel free to reopen if issue arises again.
