### ISSUE TITLE
a list of numpy to ray dataset, why dataset.take get the shape is not same origin numpy

### ISSUE THREAD

**Issue by yanxiaod123** [ray-project/ray#34518]
### What happened + What you expected to happen

I generate ray dataset from a list of numpy, the list length is 1000, and every numpy shape is 448 * 224 * 3. When i run dataset.take(1)[0], i what to get numpy shape is 448 * 224 * 3, but i get shape is 224*3 actually.

### Versions / Dependencies

ray==3.0.0.dev0

### Reproduction script

arr = [np.random.randint(10, size=(448, 224, 3)) for _ in range(1024)]
dataset: Dataset = ray.data.from_numpy(arr)
print(dataset.take(1)[0].shape)

### Issue Severity

High: It blocks me from completing my task.

**Comment by c21** [comment]
Hi @yanxiaod123 - Ray Data flattens the outermost dimension when storing numpy ndarray. So that's why you get each row as a (224*3) ndarray, and totally there're 458752 rows (1024*448). If you want to store each ndarray as whole, you can add an extra dimension of 1:

```py
>>> arr = [np.random.randint(10, size=(1, 448, 224, 3)) for _ in range(1024)]
>>> ds = ray.data.from_numpy(arr)
>>> ds
MaterializedDataset(
   num_blocks=1024,
   num_rows=1024,
   schema={data: numpy.ndarray(shape=(448, 224, 3), dtype=int64)}
)
```
