### ISSUE TITLE
[Data]  iter_tensor_batches_benchmark_multi_node.gce regressions on GCE

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#34532]
### What happened + What you expected to happen

The release test  iter_tensor_batches_benchmark_multi_node experiences regressions when running on GCE stack.

Test run: https://buildkite.com/ray-project/release-tests-branch/builds/1575

Understanding the regression is crucial for us as we are onboarding customers to GCE stack in a week

### Versions / Dependencies

Latest version of Ray

### Reproduction script

Re-run the test on buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Checked the GCE compute config and seems like it's set up correctly. 

Took a look at the logs, and I'm not sure why this test is failing on GCE.

Here's a gist containing the logs for AWS and GCE: https://gist.github.com/bveeramani/809c5b24e7d7d8c3382618d6d6104f72.

And here's a summary:

**AWS**
```
Result of case tfrecords-images-100-256: {'time': 0.06479635800008055}
Result of case tfrecords-images-100-2048: {'time': 3.71467114699999}
Result of case tfrecords-images-1000-mix: {'time': 0.05040225200002624}
Result of case tfrecords-random-int-1g: {'time': 270.63967487499997}
Result of case tfrecords-random-float-1g: {'time': 262.41669915}
Result of case tfrecords-random-bytes-1g: {'time': 36.31453858500004}
```

**GCE**
```
Result of case tfrecords-images-100-256: {'time': 0.11246879999998782}
Result of case tfrecords-images-100-2048: {'time': 3.969540747999986}
Result of case tfrecords-images-1000-mix: {'time': 0.0678202810000812}
Result of case tfrecords-random-int-1g: {'time': 1231.250032476}
# Timeout
```

**Comment by can-anyscale** [comment]
Sorry I gave the wrong test name, it's iter_tensor_batches_benchmark_multi_node.gce
