### ISSUE TITLE
[release] bisect tool doesn't seem to handle boundary condition right

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#34544]
given

```
0e0c150655 [Dataset] Reset row count when filtering on Dataset reading from Parquet (#34372)  --> FAIL


ffeedbf63e [data] Add usage tag for which block formats are used (#34384). --> ?


d86624502b [Dataset] Validate sort key in `Sort` LogicalOperator (#34282)  --> SUCCESSFUL
```

The tool is rerunning `0e0c150655` while it should be running `ffeedbf63e`

[run](https://buildkite.com/ray-project/release-tests-bisect/builds/55#01879660-e86d-463d-a3e1-5e576d1dd135)

**Comment by can-anyscale** [comment]
Should be fix now in master as well with https://github.com/ray-project/ray/pull/34536
