### ISSUE TITLE
[Datasets] Dataset leaks object store memory

### ISSUE THREAD

**Issue by polikutinevgeny** [ray-project/ray#34557]
### What happened + What you expected to happen

What happened: after creating dataset, reading it into memory, then deleting the local reference to the dataset its data remain in the shared object store. `ray memory` at the time reports a lot of `CAPTURED_IN_OBJECT` objects. After about 10 minutes (seems to be pretty consistent, as if on some timer) memory is released. This becomes a problem when working with large datasets and memory is constrained. 

What I expected to happen: memory should have been released after deleting the reference.

#25249 seems somewhat relevant

### Versions / Dependencies

Ray 2.3.1, Python 3.10.10, Linux 6.2.10-arch1-1

### Reproduction script

```python
import os
os.environ["RAY_record_ref_creation_sites"] = "1"

import ray
import ray.data
import time


def print_free_memory():
    print(ray.available_resources()["object_store_memory"])


ray.init(num_cpus=8, object_store_memory=8 * 10**9)
print_free_memory()
dataset = ray.data.range(10 ** 7).fully_executed()
print_free_memory()
del dataset
print_free_memory()

for i in range(60):
    time.sleep(60)
    print(i + 1, end=" ")
    print_free_memory()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by raulchen** [comment]
I can reproduce this issue. Need further triage on who is holding the object refs.

**Comment by anyscalesam** [comment]
@raulchen can you re-run on latest master to determine repro; if repros we should hold bar at fixing this for ray210

**Comment by raulchen** [comment]
Re-ran this and confirmed the issue no longer existed.
