### ISSUE TITLE
[Job] Failed to find working dir because the working_dir is specified after the entrypoing.

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#34561]
### What happened + What you expected to happen

When following the job cli get-started doc, I failed to run a job initially because I specified the `working-dir`
 after the entrypoint. (previously I run into this issue but didn't really dive a bit deeper into the cause)

The doc didn't mention this so it was a bit hard to figure out why the driver script cannot be found. The CLI reference does show that the options should be ahead of entrypoint. However, new users will not really look at the doc that closely and will run into similar issues.

Here are my suggestions:
1. Ideally, the order doesn't matter. We don't require users to put entrypoint at the end.
2. Practically, provide warnings when people add options behind entrypoint.

```
(ray) huaiwei@Huaiweis-MacBook-Pro-16-inch-2019 job-test % ray job submit --working-dir . -- python job.py
Job submission server address: http://127.0.0.1:8265
2023-04-18 22:38:33,527	INFO dashboard_sdk.py:317 -- Uploading package gcs://_ray_pkg_5c4dc888f7ad1609.zip.
2023-04-18 22:38:33,528	INFO packaging.py:520 -- Creating a file package for local directory '.'.

-------------------------------------------------------
Job 'raysubmit_xYJnCnX4uQxQrH9e' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_xYJnCnX4uQxQrH9e
  Query the status of the job:
    ray job status raysubmit_xYJnCnX4uQxQrH9e
  Request the job to be stopped:
    ray job stop raysubmit_xYJnCnX4uQxQrH9e

Tailing logs until the job exits (disable with --no-wait):
2023-04-18 22:38:37,239	INFO worker.py:1314 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
2023-04-18 22:38:37,240	INFO worker.py:1432 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...
2023-04-18 22:38:37,331	INFO worker.py:1607 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265
[0, 1, 4, 9]

------------------------------------------
Job 'raysubmit_xYJnCnX4uQxQrH9e' succeeded
------------------------------------------

(ray) huaiwei@Huaiweis-MacBook-Pro-16-inch-2019 job-test % ray job submit -- python job.py --working-dir .
Job submission server address: http://127.0.0.1:8265

-------------------------------------------------------
Job 'raysubmit_6RR6wzwUBJdP1qpa' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_6RR6wzwUBJdP1qpa
  Query the status of the job:
    ray job status raysubmit_6RR6wzwUBJdP1qpa
  Request the job to be stopped:
    ray job stop raysubmit_6RR6wzwUBJdP1qpa

Tailing logs until the job exits (disable with --no-wait):
python: can't open file 'job.py': [Errno 2] No such file or directory

---------------------------------------
Job 'raysubmit_6RR6wzwUBJdP1qpa' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs (truncated to 20,000 chars):
python: can't open file 'job.py': [Errno 2] No such file or directory
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
cc: @architkulkarni @edoakes @akshay-anyscale 
btw, who should own ray job stuff down the road, I feel guilty of keeping pinging @architkulkarni

**Comment by architkulkarni** [comment]
1. We must require the entrypoint to be at the end, because we need to support the case where the user's entrypoint command itself has arguments (e.g. `ray job submit -- python my_script.py --myarg=myval`)
2. We shouldn't emit a warning in this case because it's a legitimate use case and might be annoying for users repeatedly using the command.  

I think the best thing to do is add a brief warning in the doc, @scottsun94 want to take a stab at it?

There might be other solutions I'm missing though.  Jobs is owned by Platform team, but I can help out with issues as they arise.

**Comment by scottsun94** [comment]
> We must require the entrypoint to be at the end, because we need to support the case where the user's entrypoint command itself has arguments (e.g. ray job submit -- python my_script.py --myarg=myval)
We shouldn't emit a warning in this case because it's a legitimate use case and might be annoying for users repeatedly using the command.

Thanks for the context. +1 to documentation change.

However, the options like working-dir, metadata, etc. should be reserved options? It should be safe to print a warning whenever users add those after entrypoint?
