### ISSUE TITLE
[core][ci] decision_tree_autoscaling_20_runs.aws fails 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#34574]
### What happened + What you expected to happen

Seems object owner died unexepctedly. 

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_cnqbvlf2nd29xkk4lcuid5zkl8

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by scv119** [comment]
task killed by ray oom killer, due to the overall memory usage above 0.95 threshold.  closing it for now, if this happens again we should disable ray oom killer for this task.
