### ISSUE TITLE
[ml][release] tune_worker_fault_tolerance is failing consistently on master

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#34580]
### What happened + What you expected to happen

tune_worker_fault_tolerance test is failing consistently at least twice in a row in master

Bisect ([tune_worker_fault_tolerance](https://buildkite.com/ray-project/release-tests-bisect/builds/74)) seems to point to this https://github.com/ray-project/ray/commit/4367c80f36066b880a409bbb98c7055cff1abdcf. Does it make any sense?

### Versions / Dependencies

nightly build

### Reproduction script

run release test on master

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
> Bisect ([tune_worker_fault_tolerance](https://buildkite.com/ray-project/release-tests-bisect/builds/74)) seems to point to this https://github.com/ray-project/ray/commit/4367c80f36066b880a409bbb98c7055cff1abdcf. Does it make any sense?

This commit unfortunately looks completely unrelated.

**Comment by can-anyscale** [comment]
bummer ;)

**Comment by xwjiang2010** [comment]
already tracked [here](https://github.com/ray-project/ray/issues/34508). Closing this one.

**Comment by xwjiang2010** [comment]
We believe this is a Core issue and handed over to Core team to investigate for now.
