### ISSUE TITLE
[rllib] Callbacks for better custom metrics

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3459]
https://github.com/ray-project/ray/blob/7abfbfd2f7c5878aaa7bc878b55ef00d31cf3ebc/python/ray/rllib/evaluation/sampler.py#L345-L368

The callback `on_episode_step` should be called after `episode.batch_builder.add_values` is called, in order to avoid that there are no values added to the builder at the first step.

**Comment by ericl** [comment]
Isn't it already after add_values()?

**Comment by AlessandroZavoli** [comment]
I think this issue is still relevant.
Moreover, the callbacks seem not very well documented, yet
