### ISSUE TITLE
Serve number of replica metrics

### ISSUE THREAD

**Issue by akshay-anyscale** [ray-project/ray#34601]
### What happened + What you expected to happen

<img width="842" alt="Screenshot 2023-04-19 at 3 44 45 PM" src="https://user-images.githubusercontent.com/122416226/233215650-72fe699b-7ef7-49f1-a344-1afc3a1fb622.png">

There's only one replica running but the metrics show 7 replicas.
<img width="447" alt="Screenshot 2023-04-19 at 3 45 09 PM" src="https://user-images.githubusercontent.com/122416226/233215710-cc3798c1-ce3e-4b82-a950-16bb0b88a80c.png">
<img width="934" alt="Screenshot 2023-04-19 at 3 45 38 PM" src="https://user-images.githubusercontent.com/122416226/233215784-516d1ab8-a2ab-4d66-a261-90e320feb7a1.png">

### Versions / Dependencies

nightly

### Reproduction script

Try setting autoscaling config, min = 1, max = 4,  start with initial replicas as 4 and let it scale down

### Issue Severity

None

**Comment by akshay-anyscale** [comment]
Please link the PR if this is fixed.

**Comment by sihanwang41** [comment]
https://github.com/ray-project/ray/pull/34761
