### ISSUE TITLE
[Serve] Json formatting the log

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#34600]
### Description

Json formatting the log message will help user to better parse the log.

INFO 2023-04-18 10:01:18,864 deployment_full_chatbot_DAGDriver full_chatbot_DAGDriver#bBVPnk replica.py:527 - PREDICT OK 9704.4ms

{level: INFO,
timestamp: 2023-04-18 10:01:18,864,
deployment: deployment_full_chatbot_DAGDriver
tag: full_chatbot_DAGDriver#bBVPnk
file: replica.py:527
msg: PREDICT OK 9704.4ms
}

**Comment by akshay-anyscale** [comment]
https://github.com/ray-project/ray/pull/35118
