### ISSUE TITLE
[RLlib] concat_samples() not support Torch GPU tensors

### ISSUE THREAD

**Issue by ZaberKo** [ray-project/ray#34622]
### What happened + What you expected to happen

`ray.rllib.policy.sample_batch.concat_samples()` does not support SampleBatch with Torch GPU tensors.
The reason is that the underlying method used for concat is `np.concatenate` in https://github.com/ray-project/ray/blob/5b99dd9b79d8e1d26b0254ab2f3d270331369a0e/rllib/utils/numpy.py#L109

Some additional handling should be made here to support this scenario. An example case is that I implemented a GPU-based replay buffer, and need concat some addtional data to the sampled data from the replay buffer.

### Versions / Dependencies

ray 2.3.1

### Reproduction script

```
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for reporting this. I can reproduce and have put up a fix.

**Comment by ArturNiederfahrenhorst** [comment]
@ZaberKo The RLlib team has decided that, since SampleBatch is not explicitly intended to manipulate GPU tensors, we'll not support this for now. (See discussion on the related PR).

**Comment by ArturNiederfahrenhorst** [comment]
Feel free if you see something fundamentally wrong with this.
