### ISSUE TITLE
[Data] Local read throws exception if Ray cluster is not initialized

### ISSUE THREAD

**Issue by c21** [ray-project/ray#34631]
### What happened + What you expected to happen

Local read throws exception if Ray cluster is not initialized. We should fix it.

User report: https://discuss.ray.io/t/explicit-call-to-ray-init-need-when-reading-from-local/10241/2
Local read: https://docs.ray.io/en/master/data/creating-datastreams.html#reading-from-local-storage
Code pointer: https://github.com/ray-project/ray/blob/master/python/ray/data/read_api.py#L360-L369

### Versions / Dependencies

master

### Reproduction script

```py
>>> import ray
>>> ds = ray.data.read_parquet("local://<any-random-parquet-file-on-laptop>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chengsu/ray/python/ray/data/read_api.py", line 630, in read_parquet
    return read_datasource(
  File "/Users/chengsu/ray/python/ray/data/read_api.py", line 366, in read_datasource
    ray.get_runtime_context().get_node_id(),
  File "/Users/chengsu/ray/python/ray/runtime_context.py", line 105, in get_node_id
    assert ray.is_initialized(), (
AssertionError: Node ID is not available because Ray has not been initialized.
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by raulchen** [comment]
@c21 @ericl 
I just checked `ray.data.range`, `ray.init` is triggered by `client_mode_should_convert(auto_init=True)`, when calling `get_current_placement_group`. 
We could also add `client_mode_should_convert` to `read_datasource`. But this won't cover all the cases in the future. Should we just add `ray.init` to a unified code entrance of `ray.data`?
Also, it looks weird that `ray.init` is coupled with client mode.

**Comment by ericl** [comment]
I think the bug here is that get_runtime_context doesn't trigger implicit Ray initialization, similar to the other Ray APIs. It's probably missing some decorator like the one ray.put() etc have.
