### ISSUE TITLE
write multiple environments in yaml

### ISSUE THREAD

**Issue by stellaxu** [ray-project/ray#3463]
Hi, 
if I want to run different environments(like atari games), but I do not want to use "grid search". Is there any way to make it?

I try to write:
 "   env:
           - Freeway-v0
           - MontezumaRevenge-v0
           - Frostbite-v0
           - Seaquest-v0
  and 
     env:
           Freeway-v0
           MontezumaRevenge-v0
           Frostbite-v0
           Seaquest-v0  "
and both of them cannot be compiled

Thxs.

**Comment by ericl** [comment]
Here's one example: https://github.com/ray-project/ray/blob/master/python/ray/rllib/tuned_examples/atari-impala.yaml

You can also concatenate multiple experiments files into one and it will work as long as they have different names. For example, atari-impala: , atari-impala2: ...
This is the same as having multiple keys in the dict passed to run_experiments() in tune.

**Comment by stellaxu** [comment]
Thanks for your suggestion~~

**Comment by richardliaw** [comment]
Closing for now, but let us know if you have any further questions!
