### ISSUE TITLE
[Ray: Core] cannot install latest version 2.3.1 on MacOS with Python 3.7

### ISSUE THREAD

**Issue by JoshuaZe** [ray-project/ray#34666]
### What happened + What you expected to happen

I am a user of macOS with Intel Core, and i have to use python3.7 for my development. 
However, i can not install the latest version 2.3.1 of ray, as latest ray does not provide a distribution that works for my platform.

### Versions / Dependencies

OS version and name: macOS 11.6
Python version in Virtualenv: 3.7.16

for other library 
pyproject.toml: https://gist.github.com/JoshuaZe/67713634324a4647243de8dad2c5438c

### Reproduction script

```
(my-example-package-py-3.7) % pip install ray==2.3.1
ERROR: Could not find a version that satisfies the requirement ray==2.3.1 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.1.post1, 1.1.0, 1.2.0, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0rc0, 1.7.0, 1.7.1, 1.8.0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.9.1rc0, 1.9.1, 1.9.2, 1.10.0rc0, 1.10.0, 1.11.0rc1, 1.11.0, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.3.0rc0, 2.3.0)
ERROR: No matching distribution found for ray==2.3.1
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ammirsm** [comment]
Facing the same issue.

```
  • Installing ray (2.3.1): Failed

  RuntimeError

  Unable to find installation candidates for ray (2.3.1)

  at /opt/homebrew/Cellar/poetry/1.4.2/libexec/lib/python3.11/site-packages/poetry/installation/chooser.py:109 in choose_for
      105│ 
      106│             links.append(link)
      107│ 
      108│         if not links:
    → 109│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      110│ 
      111│         # Get the best link
      112│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      113│ 
```
**Versions / Dependencies**

Python 3.11.3 
MacOS 13.0 (22A380)
M1 CPU.

**Comment by rickyyx** [comment]
hey @JoshuaZe  Thanks for reporting. This seems to be a mistake. We are looking into it and will update once we upload the wheels to pypi. 


@ammirsm , python 3.11 wheels are still not available on mac yet for Ray. We are working on it (there were a few blockers on Ray's dependencies). See this issue for tracking https://github.com/ray-project/ray/issues/31362

**Comment by chrisgoddard** [comment]
+1 on this issue - not working on either my intel or M1 mac.

**Comment by rickyyx** [comment]
Hey @chrisgoddard which python version you are using?

**Comment by rickyyx** [comment]
We have just uploaded wheels for py3.7. Sorry for the delay. cc @JoshuaZe

**Comment by XavierGeerinck** [comment]
Just checking, this appears to still not work at my side

```
  • Installing ray (2.3.1): Failed

  RuntimeError

  Unable to find installation candidates for ray (2.3.1)
```

**Comment by chrisgoddard** [comment]
Apologies I missed the original version listed in the original question - I'm actually on 3.11

**Comment by rickyyx** [comment]
> Just checking, this appears to still not work at my side (Python 3.7.13 on Mac M1)
> 
> ```
>   • Installing ray (2.3.1): Failed
> 
>   RuntimeError
> 
>   Unable to find installation candidates for ray (2.3.1)
> ```

Hey @XavierGeerinck - It seems ray doesn't have m1 support with 3.7 (same with conda, which we depends on for wheels building right now). 

Would upgrading to py 3.8 and above be a viable option for you?

**Comment by XavierGeerinck** [comment]
Hi @rickyyx ! I indeed noticed it a bit late, it's for me an option but had to figure out - as I am using the kuberay operator - how to do so. But apparently there was an image tag so got it working now, thanks!! :)

**Comment by chrisgoddard** [comment]
Happy to out this in a different issue as it's not relevant to 3.7 but what is the timeline on 3.11 support for other platforms (not just Linux)?

**Comment by rickyyx** [comment]
Hey @chrisgoddard - you could subscribe to this issue: https://github.com/ray-project/ray/issues/31362

**Comment by rickyyx** [comment]
Closing this since missing mac wheel for py3.7 has been uploaded. Feel free to re-open/comment if there's any issue.

**Comment by chimmykk** [comment]
same issue occuring now on Intel Mac OS

ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement ray==2.10.0 (from versions: none)
ERROR: No matching distribution found for ray==2.10.0

Current  python --version
Python 3.13.0
