### ISSUE TITLE
[Cluster Launcher] [State API] [Jobs] Add API to get head node IP

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#34685]
### Description

Right now there doesn't seem to be a simple programmatic way to get the head node IP address once you've started the cluster. 

To brainstorm some possible APIs:
Cluster launcher API: `ray get-head-ip my_cluster_config.yaml`, to be run after `ray up my_cluster_config.yaml`. Probably too specific a function for a top level command though.
State API: This might already be supported with `ray list nodes --filter is_head_node=True`. In this case do we just need to highlight it in the docs? However, I think this won't work outside the cluster unless you provide the head node IP address, which we don't have.

### Use case

Requested by users: 
- User 1: https://discuss.ray.io/t/retrieving-ip-address-of-head-node-from-ray-up/10280

> I am looking to launch multiple remote Ray clusters ON AWS from the same machine concurrently.
> 
> To accomplish this I was looking to run “ray up” via the CLI followed by “JobSubmissionClient().submit_job()” via the Python client.
> 
> From looking at the docs, I haven’t found a good way to find the IP address of the head node to instantiate the JobSubmissionClient with (outside of grepping through the output of the ray up call).
>
> This seems like it would be a very common thing to do, so it feels like I am using Ray incorrectly.
- User 2: 

> I see, as long as we have the address, and pass it to job_submission_client. Is there any better to way to get the headnode address? I searched around and did not find a good way to obtain it, other than address = ray.init().

**Comment by scottsun94** [comment]
cc: @rickyyx @rkooo567 

People can use 
`ray exec` and `ray list nodes --filter is_head_node=True` together for this?

**Comment by rickyyx** [comment]
> I think this won't work outside the cluster unless you provide the head node IP address, which we don't have.

Yes, if one's outside a ray cluster, they need to provide a head node address. 

However, getting a remote cluster's address w/o specifying a head node (or some sort of identifier to the cluster) sounds like we might need some additional work on the client side? 
- e.g. ray up or ray init on the client side might need to persist something on the client's end?

> ray exec and ray list nodes --filter is_head_node=True together for this?
Does ray exec also need a ray cluster address?

**Comment by wuisawesome** [comment]
Wait are you literally looking for `ray get-head-ip`?

**Comment by architkulkarni** [comment]
Okay, that's pretty crazy, neither I nor the other two users noticed `ray get-head-ip cluster.yaml` already exists... https://docs.ray.io/en/latest/cluster/cli.html#ray-get-head-ip

I guess the solution here is just to make it more prominent in the docs (maybe just make a reference to this in the Jobs docs where we talk about the head IP address).

Should we also print it out in the "things you can do" after running `ray up`? I think we can just print all the commands, there's only 5 (not counting `ray submit` which we want to deemphasize in favor of jobs, and `ray start` and `ray stop` which aren't relevant, and `ray up` which was just run):
```
ray down
ray exec
ray attach
ray get_head_ip
ray monitor
```

**Comment by wuisawesome** [comment]
imo the only ones you should do after running `ray up` are `ray down`, `ray-get-head-ip`, `ray attach` (for debugging only)

**Comment by scottsun94** [comment]
@architkulkarni Shall we also print `ray job submit`?
