### ISSUE TITLE
[serve] Allow querying if a client has disconnected their request in the fastapi integration

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#34682]
### Description

cc: @edoakes

[slack thread](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1682105223478299)

Allow detecting if a user has disconnected their fastapi/starlette request, e.g. make the `request.is_disconnected()` work. Right now it always returns true.

### Use case

I want to detect that a user dropped their http request. I want to use this information to cancel a long running (e.g. ~10s) pipeline of ML jobs.

My idea was to use `request.is_disconnected()` from starlette/fastapi, but I am having issues. While this function works for a vanilla fastapi app served by `uvicorn`, it just always returns true when used within ray.

Here is a full reproduction [example](https://github.com/shayanhoshyari/ray-playground/tree/main/fastapi-disconnect)

@edoakes confirmed that this is not possible now so making this feature request.

**Comment by edoakes** [comment]
@shayanhoshyari this is working by default now in ray 2.6
