### ISSUE TITLE
[core][nightly] threaded_actors_stress_test.aws failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#34693]
### What happened + What you expected to happen

The worker failed with 
```
(pid=5523, ip=10.0.48.132) Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
```

Looks like there are a few incidents similar to this as well

### Versions / Dependencies

NA

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_uf3z2a6lf4tidsbdbwt7tt5yvu

### Issue Severity

None

**Comment by rickyyx** [comment]
Waiting for more repro if possible.

**Comment by jjyao** [comment]
Consistently passing.
