### ISSUE TITLE
[Core] Cancel to functions on actor 

### ISSUE THREAD

**Issue by shiranbi** [ray-project/ray#34698]
### Description

Currently ray.cancel works on references created by calling remote functions (tasks)
I would to be able to cancel remote functions on actors that
1. have not started (most important)
2. trigger keyboard interrupt on remote functions in actors that are currently running
all of this without killing the actor

### Use case

In my use case the actor state is created during it's initialization and it may take a long time
the remote function calls do not change the state (i have several reasons for using actors over tasks, one of which is the cached state during initialization).

in cases where i need to stop my flow, i need to do it as fast as possible and to be able to start a new flow equally as fast.
This means that killing the actor is not an option since the creation and initiallization of a new one will take a long time
waiting for all remote functions that were triggered to finish is also a bad option since that may take a while.

so being able to cancel them is important

**Comment by rkooo567** [comment]
We will work on it soon. It is the same issue as https://github.com/ray-project/ray/issues/34961. I will close it as duplicate and update other ticket
