### ISSUE TITLE
[core][nightly] chaos_many_actors.aws failed 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#34719]
### What happened + What you expected to happen

The test was slow to complete before timeout. 

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1596#0187a5e6-2b3b-4994-a281-ac6e19fc75e9

### Issue Severity

None

**Comment by rickyyx** [comment]
cc @jjyao

**Comment by jjyao** [comment]
For the warm up phase of the test:

A successful run took 20 minutes: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_x2f5bsbzzcn64lhyx9efgrybzr?pjd-section=ray-logs-download-cli-tab

A timed out run took 60 minutes: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_n892tih3ieaszb3sv6exs4nepz?pjd-section=ray-logs-download-cli-tab

there is no node failure involved during the warm up phase.

**Comment by jjyao** [comment]
Seems the issue is related to #34805

Before: https://buildkite.com/ray-project/release-tests-pr/builds/36671#0187cb68-e6f4-46d5-a8b4-dc4861277b4c

After: https://buildkite.com/ray-project/release-tests-branch/builds/1619#0187cb61-8051-44fb-800b-e9707937b98c

**Comment by can-anyscale** [comment]
w00t, after much attempt but I managed to bisect to https://github.com/ray-project/ray/commit/429c965cc453bb58cdd768a1d0ed92f4c87fd490 as well. Bisect job: https://buildkite.com/ray-project/release-tests-bisect/builds/119#0187cf9e-e8c2-4271-aa2d-7ed2c92a51d1 (I have to increase the test timeout to 4000 for bisect to run reliably, the test seems to be a bit flaky at 3600 timeout).
