### ISSUE TITLE
[CORE] ray cluster deployed on k8s: both the head and worker pod crashed due to raylet's expanding memory usage.

### ISSUE THREAD

**Issue by fp5601106001** [ray-project/ray#34739]
### What happened + What you expected to happen

I have deployed a ray clusters on kubernetes with some small mods on "https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/kubernetes/configs/static-ray-cluster.with-fault-tolerance.yaml", the detail:

kind: Pod
apiVersion: v1
metadata:
  name: deployment-ray-head-78ff9d6d75-2vvw8
  generateName: deployment-ray-head-78ff9d6d75-
  namespace: e0122x301ejl
  labels:
    app: ray-cluster-head
    component: ray-head
    pod-template-hash: 78ff9d6d75
    type: ray
  annotations:
    cni.projectcalico.org/containerID: 48b8afbe01aa593d067bd7557b98133e837a85d66620b3488ac226e34aa08dd2
    cni.projectcalico.org/podIP: 172.25.244.254/32
    cni.projectcalico.org/podIPs: 172.25.244.254/32
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - name: ray-env-log
      persistentVolumeClaim:
        claimName: ray-env-log
    - name: ray-env-result
      persistentVolumeClaim:
        claimName: ray-env-result
    - name: ray-env-model
      persistentVolumeClaim:
        claimName: ray-env-model
    - name: ray-env-static
      persistentVolumeClaim:
        claimName: ray-env-static
    - name: ray-env-data
      persistentVolumeClaim:
        claimName: ray-env-data
    - name: platform-data
      persistentVolumeClaim:
        claimName: platform-data
    - name: dns-resolv
      configMap:
        name: dns-resolv
        defaultMode: 420
    - name: tmp-ray
      hostPath:
        path: /tmp/ray
        type: Directory
    - name: kube-api-access-p89g5
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: ray-head
      image: 'rayproject/ray:2.3.0'
      command:
        - /bin/bash
        - '-c'
        - '--'
      args:
        - >-
          ray start --head --port=6380 --num-cpus=$MY_CPU_REQUEST
          --dashboard-host=0.0.0.0 --object-manager-port=8076
          --node-manager-port=8077 --dashboard-agent-grpc-port=8078
          --dashboard-agent-listen-port=52365 --block
      ports:
        - containerPort: 6380
          protocol: TCP
        - containerPort: 10001
          protocol: TCP
        - containerPort: 8265
          protocol: TCP
      env:
        - name: RAY_JOB_ALLOW_DRIVER_ON_WORKER_NODES
          value: '1'
        - name: NAMESPACE
          value: tenant
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
              divisor: '0'
        - name: DEPLOY_MODE
          value: '4'
        - name: RAY_TASK_MAX_RETRIES
          value: '0'
      resources:
        limits:
          cpu: '8'
          memory: 16G
        requests:
          cpu: '8'
          memory: 16G
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: ray-env-log
          mountPath: /home/ray/env/log
        - name: ray-env-result
          mountPath: /home/ray/env/result
        - name: ray-env-model
          mountPath: /home/ray/env/model
        - name: ray-env-static
          mountPath: /home/ray/env/static
        - name: ray-env-data
          mountPath: /home/ray/env/component_data
        - name: platform-data
          mountPath: /home/ray/env/data
        - name: dns-resolv
          readOnly: true
          mountPath: /etc/resolv.conf
          subPath: resolv.conf
        - name: tmp-ray
          mountPath: /tmp/ray
        - name: kube-api-access-p89g5
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        tcpSocket:
          port: 8077
        initialDelaySeconds: 15
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: coredns
      image: >-  $coredns image
      command:
        - ./coredns
        - '-conf=conf/Corefile'
        - '-namespace=${NAMESPACE}'
        - '-gateway=$(GATEWAY_IP)'
      env:
        - name: GATEWAY_IP
          value: tenant
        - name: NAMESPACE
          value: tenant
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 16Mi
      volumeMounts:
        - name: kube-api-access-p89g5
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: k8s-master01
  securityContext: {}
  imagePullSecrets:
    - name: regcred
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

Without submitting any job, I found that the memory usage of the head pod and worker pod is growing slowly.  And finally, the head pod and worker pod crashed as memory usage reaches 99%.
![image](https://user-images.githubusercontent.com/16399261/234187695-b4d6dc80-0236-4e1e-9cd4-cd68b3529667.png)
![image](https://user-images.githubusercontent.com/16399261/234188004-c9df34e5-9d9c-4e1b-8997-a8026eb7caee.png)

the resource usage inside the container is as below: raylet occupied 16g memory without workload.
![image](https://user-images.githubusercontent.com/16399261/234188324-a72f457f-cb77-445f-82f2-418717683bb8.png)

the raylet.out on dashboard page: (tail -500)
![image](https://user-images.githubusercontent.com/16399261/234192271-73d67772-2eb5-4d39-8ace-0614a278d78c.png)

there comes about 300 new logs per sec. By the way, I didn't do gcs fault tolerance, so redis is included in the ray head.

I'm not sure whether the pod restart is caused by raylet printing a lot of logs - because after I set the BACKEND_LOG_LEVEL environment variable to 'error', the problem still exists. however the raylet do generate 20GB log in a few days.

“du -h --max-depth=1” @/tmp/ray：the left  is ray on k8s，and the right is ray started via  docker（"ray start --head"）
<img width="870" alt="62b3b0b85c1b7ee01986fbdc4bdd194c" src="https://user-images.githubusercontent.com/16399261/234186288-126e2ae9-fc07-4237-83d6-32461fe58545.png">

is there any similar issue？how to solve the increasing-memory problem of raylet？

### Versions / Dependencies

ray2.3.0, python3.9, centos7

### Reproduction script

refer to the previous yaml

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
So is it correct you just start a cluster and wait for a few days, the raylet memory grows to 8GB (Btw, you should look at RES not the virtual memory from the top).

**Comment by fp5601106001** [comment]
> So is it correct you just start a cluster and wait for a few days, the raylet memory grows to 8GB (Btw, you should look at RES not the virtual memory from the top).

yes，I left it for a few days, and found that the head and worker pod restarted for many times. 
however, it seems it's caused by some of the conf I applied to the yaml.
1. set a coredns with both the head and worker respectively.
2. use the k8s hpa for auto-scaler service.
3. map /tmp/ray to host path.
And, I started a cluster with this file 'https://raw.githubusercontent.com/ray-project/kuberay/release-0.5/ray-operator/config/samples/ray-cluster.autoscaler.yaml', and it doesn't seem to have the problem.

**Comment by rkooo567** [comment]
Hmm I see. so without the restart issue, memory usage seems okay?

**Comment by fp5601106001** [comment]
> Hmm I see. so without the restart issue, memory usage seems okay?

Well, I think the restart issue results from raylet memory problem.  the raylet prints about 300 such msg per second. 

![](https://user-images.githubusercontent.com/16399261/234192271-73d67772-2eb5-4d39-8ace-0614a278d78c.png)

**Comment by yvmilir** [comment]
Hello, I have also encountered a similar issue where memory is constantly growing, but my raylet does not output a lot of logs. But I'm sorry I didn't understand what you modified to solve this problem. Can you explain it in detail? Thank you very much.
