### ISSUE TITLE
Migrate Python C extension to Cython?

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#3474]
Currently, we use C extension to bridge Python and C++ code, e.g., for local scheduler client, and some data structures like Task and ObjectID. 

One pain point is that C extension is inconvenient to use. For example, 1) if I want to change parameters of Task's constructor, I have to be very careful to handle [PyArg_ParseTuple](https://github.com/ray-project/ray/blob/06f6431765b16da7cdb924cb4716a35acf0fba84/src/ray/raylet/lib/python/common_extension.cc#L387); 2) there's a lot of boilerplate code that converts Python objects to C++ objects; etc.

If we convert these files to Cython, code will be much cleaner and easier to write. 

Any other pros and cons?

**Comment by robertnishihara** [comment]
I think this is a great idea.

The only "con" I can think of is that @pcmoritz has seen bugs in Cython before and it can be challenging to find these, whereas the C extensions seem pretty reliable. But overall I think this is a good decision.

**Comment by pcmoritz** [comment]
Yeah, I think this is the right way forward! While we are at it, we should also modernize the LocalSchedulerClient to be more idiomatic C++.

I'm not concerned about the bugs in Cython as they can be worked around and Cython has worked very well for Plasma.

**Comment by robertnishihara** [comment]
Yes, this is the issue for modernizing the Raylet client. https://github.com/ray-project/ray/issues/3014

This should probably be done before the switch to Cython since it will make switching to Cython easier.

**Comment by robertnishihara** [comment]
Fixed by #3541.
