### ISSUE TITLE
containers OOM on jenkins unit tests

### ISSUE THREAD

**Issue by atumanov** [ray-project/ray#3476]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu Linux (jenkins image)
- **Ray installed from (source or binary)**: 0.7-snapshot (master)
- **Ray version**: upstream/master
- **Python version**: all
- **Exact command to reproduce**:

`docker run --rm --shm-size=10G --memory=10G 7cebc354a08219bde7461ad729457195862d8db69765a360b9b0ab8d2861eb10 python /ray/python/ray/rllib/test/test_checkpoint_restore.py`

### Describe the problem
Unit tests causing container kernel panics when unable to allocate memory.

### Source code / logs
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.693368] SLUB: Unable to allocate memory on node -1 (gfp=0x2088020)
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.693373]   cache: mnt_cache(76589:73d47e08a2f6d9a995d4f3f76fc9f0bf5ef4421bec2d61c1ad1ae182d0237fee), object size: 384, buffer size: 384, default order: 2, min order: 0
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.693375]   node 0: slabs: 24, objs: 944, free: 0
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.693376]   node 1: slabs: 11, objs: 462, free: 0
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.733300] SLUB: Unable to allocate memory on node -1 (gfp=0x2088020)
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.733306]   cache: mnt_cache(76589:73d47e08a2f6d9a995d4f3f76fc9f0bf5ef4421bec2d61c1ad1ae182d0237fee), object size: 384, buffer size: 384, default order: 2, min order: 0
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.733309]   node 0: slabs: 24, objs: 944, free: 0
Dec  4 13:54:04 amp-jenkins-staging-worker-01 kernel: [518099.733312]   node 1: slabs: 14, objs: 588, free: 0
Dec  4 13:54:12 amp-jenkins-staging-worker-01 kernel: [518107.345192] SLUB: Unable to allocate memory on node -1 (gfp=0x2088020)
Dec  4 13:54:12 amp-jenkins-staging-worker-01 kernel: [518107.345197]   cache: blkdev_ioc(76589:73d47e08a2f6d9a995d4f3f76fc9f0bf5ef4421bec2d61c1ad1ae182d0237fee), object size: 104, buffer size: 104, default order: 0, min order: 0
Dec  4 13:54:12 amp-jenkins-staging-worker-01 kernel: [518107.345199]   node 0: slabs: 19, objs: 741, free: 0
Dec  4 13:54:12 amp-jenkins-staging-worker-01 kernel: [518107.345200]   node 1: slabs: 13, objs: 507, free: 0
Dec  4 13:54:56 amp-jenkins-staging-worker-01 dockerd[79228]: time=“2018-12-04T13:54:56-08:00” level=info msg=“shim reaped” id=73d47e08a2f6d9a995d4f3f76fc9f0bf5ef4421bec2d61c1ad1ae182d0237fee
Dec  4 13:54:56 amp-jenkins-staging-worker-01 dockerd[79228]: time=“2018-12-04T13:54:56.996016671-08:00” level=info msg=“ignoring event” module=libcontainerd namespace=moby topic=/tasks/delete type=“*events.TaskDelete”

Reported by @shaneknapp .
PR submitted to address the issue #3475

**Comment by shaneknapp** [comment]
i would just like to note that we really can't go much higher than 20G for things like this...  our workers have a finite amount of RAM and it's needed for things like, oh, other non-ray builds.  ;)

**Comment by atumanov** [comment]
@shaneknapp , yeah, I think that we can bring it back down to 10GB once #3478 is fixed.

**Comment by atumanov** [comment]
closed via merged #3475
