### ISSUE TITLE
[Core] Release Tests many_pgs.aws test failed with an unexpected node failure.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#34767]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_3xk3v1cxt6ek9xw5mjkuk9bsst?job-logs-tab=logs_contents_tab

I looked at the code, and the dead raylet has 2 weird things.

1. It received a SIGTERM, which is kind of unexpected? 
2. The log indicates there are two GCS sending the resource broadcast to it. I am not sure how this is possible.

### Versions / Dependencies

master

### Reproduction script

See the link

### Issue Severity

None

**Comment by rkooo567** [comment]
Hmm seems like it passed 2 times in a row in the master when I retried.

It is probably a flaky case that happened due to the issue @iycheng bring it up. I will double check code tmrw to verify if his theory makes sense and add better logs so that we can debug it again when this happens again. After this I will close the issue for now.

**Comment by rkooo567** [comment]
Discussed offline with @iycheng My expectation is the issue is due to some random bugs from lightweight heartbeat, and when we turn on the syncer, it should disappear. @iycheng can you tell me the timeline to re-enable syncer?

**Comment by iycheng** [comment]
@rkooo567 it should be this week.

**Comment by iycheng** [comment]
Hi @rkooo567 I just reassigned this to me since it depends on syncer. I'll double check this test when it's enabled.

**Comment by iycheng** [comment]
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_vfjkijr5vd2unzcybvlcc5vfb3

**Comment by iycheng** [comment]
https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_c4bdz4zm7qib3hnyz2kcshxz4b
