### ISSUE TITLE
[Windows] Could not import resource module (on Windows)

### ISSUE THREAD

**Issue by ciaociaoyu** [ray-project/ray#34791]
### What happened + What you expected to happen

When I try to initial ray (use ray.init()), it comes error message"Could not import resource module (on Windows)"
And I found that in the worker.py, it tries to run "import resource", and then error happens.

### Versions / Dependencies

ray=2.4
python=3.9
OS=Windows 11

### Reproduction script

import ray
ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @mattip to triage the issue

**Comment by rkooo567** [comment]
Actually, we just need to check if the platform is window before importing this module. I will make a PR today

**Comment by mattip** [comment]
I see a 3 appearances of this:
```
$ git grep "import resource\>"
python/ray/_private/worker.py:        import resource
python/ray/_private/worker.py:        logger.debug("Could not import resource module (on Windows)")
python/ray/data/block.py:    import resource
release/nightly_tests/dataset/sort.py:import resource
```

The one in `worker.py` is guarded and will only report in debug mode.

The one in `block.py` is also guarded and will silently swallow the import exception.

The last one in `dataset/sort.py` is not guarded, but is that the one being hit? 

@ciaociaoyu could you provide the entire traceback? Maybe there is some other error?

**Comment by rkooo567** [comment]
> The one in worker.py is guarded and will only report in debug mode.

I feel like the message is from just this. But I also would like to get the confirmation. It looks like the logging level is also debug, so unless you turn on the debug log, it shouldn't come up.

**Comment by xieus** [comment]
@mattip @rkooo567  What is the action item on this issue? 

Mark the issue as "external-author-action-required" as it seems that we need input from @ciaociaoyu.

**Comment by anyscalesam** [comment]
@ciaociaoyu waiting on that traceback from you before we can proceed further; can you advise please?
