### ISSUE TITLE
[Serve] Cannot get serve deployment after a RayCluster recovers

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#34799]
### What happened + What you expected to happen

Sample errors:

* https://github.com/ray-project/kuberay/actions/runs/4803933930/jobs/8549008055
* https://github.com/ray-project/kuberay/actions/runs/4803514923/jobs/8548183947
* https://github.com/ray-project/kuberay/actions/runs/4803226177/jobs/8548296771
* https://github.com/ray-project/kuberay/actions/runs/4803164696/jobs/8547481983

### TL;DR
* [fail test](https://github.com/ray-project/kuberay/blob/ca929e932066fe04c226479fc1c6a8089af6bcaa/tests/compatibility-test.py#L111): This test uses some deprecated serve API. See this [PR](https://github.com/ray-project/kuberay/pull/650) for more details.

* Step 1: [test_ray_serve_1.py](https://github.com/ray-project/kuberay/blob/ca929e932066fe04c226479fc1c6a8089af6bcaa/tests/config/ray-cluster.ray-ft.yaml.template#L164)
* Step 2: Kill the gcs_server process on the head Pod
* Step 3: [test_ray_serve_2.py](https://github.com/ray-project/kuberay/blob/ca929e932066fe04c226479fc1c6a8089af6bcaa/tests/config/ray-cluster.ray-ft.yaml.template#L189) (Fail to get the serve deployment created by Step 1)

### Possible root cause
This test starts to fail consistently yesterday. In addition, the last time that the test passes is 2 days ago ([link](https://github.com/ray-project/kuberay/actions/runs/4791743716)). The failure is highly possible to be caused by #34260. 

```sh
# If the tag of RAY_IMAGE is not X.Y.Z or nightly, please update the function `is_feature_supported(ray_version, feature)` as follows before running the following commands.

# def is_feature_supported(ray_version, feature):
#     """Return True if `feature` is supported in `ray_version`"""
#     return True

# rayproject/ray:8728c7 => The commit (#34102) before #34260 => Succeed
RAY_IMAGE=rayproject/ray:8728c7 python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee log

# rayproject/ray:992808 => #34260 => Fail
RAY_IMAGE=rayproject/ray:992808 python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee log
```

#### rayproject/ray:2.3.0 (pass)

```sh
# path: kuberay/
RAY_IMAGE=rayproject/ray:2.3.0 python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee log
```

<img width="1269" alt="Screen Shot 2023-04-26 at 12 43 22 PM" src="https://user-images.githubusercontent.com/20109646/234698941-633710dd-82a0-4af0-99b8-44eba8339a78.png">
<img width="1403" alt="Screen Shot 2023-04-26 at 12 43 43 PM" src="https://user-images.githubusercontent.com/20109646/234698957-ff5a788f-5352-42e5-80fb-4788d1a02207.png">

#### rayproject/ray:nightly (fail)

```sh
# path: kuberay/
RAY_IMAGE=rayproject/ray:nightly python3 tests/compatibility-test.py RayFTTestCase.test_ray_serve 2>&1 | tee log
```

<img width="1279" alt="Screen Shot 2023-04-26 at 1 18 15 PM" src="https://user-images.githubusercontent.com/20109646/234699006-a5e896b8-6f55-4d65-8a07-6b32af6bfbcc.png">
<img width="1398" alt="Screen Shot 2023-04-26 at 1 18 35 PM" src="https://user-images.githubusercontent.com/20109646/234699020-88fe94e6-8cc2-4a8d-ab63-6b262f847b07.png">

### Versions / Dependencies

See above

### Reproduction script

See above

### Issue Severity

High: It blocks me from completing my task.

**Comment by kevin85421** [comment]
cc @sihanwang41 @edoakes

**Comment by kevin85421** [comment]
cc @architkulkarni @gvspraveen

**Comment by sihanwang41** [comment]
hi @kevin85421 ,

get_deployment() is v1 api which is deprecated mode and it shouldn't be used for the test script. (All our kuberay usage is under v2 api assumption)
Suggestion: **you can send requests to verify the service availability.**
If you want to use handle.remote() to send requests, then you try 

```
from ray.serve.context import get_global_client
handle = get_global_client().get_handle("default_MyModelDeployment", sync=True)
```

**Comment by kevin85421** [comment]
Thanks @sihanwang41!
