### ISSUE TITLE
Ray Core.: ray start --resource not parsed correctly (Windows)

### ISSUE THREAD

**Issue by Sahand-Razzaghi** [ray-project/ray#34818]
### What happened + What you expected to happen

The command line parser which parses the JSON dict on running the command **ray start** seems to be buggy on Windows.
(I checked Linux as well and everything is fine there)

After setting everything up the following command throws an error on the resource argument even though everything is correlty written and according to the documentation:

`ray start --head --resources='{"special_hardware": 1, "custom_label": 1}'`

with the error being: 
`--resources` is not a valid JSON string.
Valid values look like this: `--resources='{"CustomResource3": 1, "CustomResource2": 2}}'`

### Versions / Dependencies

Windows 10 Enterprise
Python version 3.10.10 
Ray version 2.4.0

### Reproduction script

Set up the environment from scratch (on a Windows machine!) by opening a terminal (cmd or powershell):

`conda create --name ray_latest -c conda-forge python=3.10`

activate env and install ray 

```
conda activate ray_latest 
pip install 'ray[default]==2.4'
```

Now run 
`ray start --head --resources='{"special_hardware": 1, "custom_label": 1}'`

Error message: 
`--resources` is not a valid JSON string.
Valid values look like this: `--resources='{"CustomResource3": 1, "CustomResource2": 2}}'`

(PS: The given example from the error message has an additional curly bracket at the end as well)

I tested the same behavior on Linux, and it works... so seems to be a specific Windows problem.

### Issue Severity

High: It blocks me from completing my task.

**Comment by mattip** [comment]
Windows terminal requires double quotes for command line arguments, and json parsing also requires double quotes. So do something like
```
ray start --head --resources="{\"special_hardware\":1, \"custom_label\":1}"
```

Is there a place the `--resources` option is documented that this could be added?

**Comment by Sahand-Razzaghi** [comment]
Thanks @mattip, this solved the issue on the windows cmd. 
Interestingly this still does not work in powershell (but thats a minor issue).
