### ISSUE TITLE
Ray Core:  System may hang when the task number is large on a single  machine of  many   cpu cores 

### ISSUE THREAD

**Issue by luxunxiansheng** [ray-project/ray#34829]
### What happened + What you expected to happen

refer to the discussion [System will be halted when tasks number is large](https://discuss.ray.io/t/system-will-be-halted-when-tasks-number-is-large/9754)(https://discuss.ray.io/t/system-will-be-halted-when-tasks-number-is-large/9754)

CentOS 7
ray 2.3
128 logical cores
thread limits: 4096

### Versions / Dependencies

2.3

### Reproduction script

see the above

### Issue Severity

High: It blocks me from completing my task.

**Comment by luxunxiansheng** [comment]
I tried and it did work.

**Comment by rkooo567** [comment]
Maybe we should close the issue? I think the action item from our end is to update the doc regarding the thread limits

**Comment by luxunxiansheng** [comment]
so far this issue, I think it is ok to close it .  Thanks for your helps.      In the future version,  maybe a better solution is to catch the exceptions thrown by the system when it is not able to create the  thread pool.   From system desgin 's perspective, it is better for ray  to  take a defensive way to keep itself alive.   I think this isseu now can easily to be reproduced just lowering the ulimit and to see what will happen.   

Thanks again for your time.

**Comment by rkooo567** [comment]
Hmm yeah Let me keep the issue open. I think we can at least raise a better error message.

**Comment by rkooo567** [comment]
(also feel free to contribute!)
