### ISSUE TITLE
Report "No handlers could be found for logger 'ray.worker' when importing ray

### ISSUE THREAD

**Issue by xutianming** [ray-project/ray#3482]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **Ray installed from (source or binary)**: source, latest master
- **Ray version**:0.6.0
- **Python version**: Anaconda Python 2.7.15
- **Exact command to reproduce**: import ray

### Describe the problem

Ray reports "No handlers could be found for logger 'ray.worker' " when importing ray.
![image](https://user-images.githubusercontent.com/4970790/49569693-9c135980-f96f-11e8-8d7c-f1dff842456b.png)

More error messages are printed when calling "ray.init(use_raylet=True)"
![image](https://user-images.githubusercontent.com/4970790/49569764-cd8c2500-f96f-11e8-8c0e-5cdfc823155e.png)

### Source code / logs

An recent pull request [#3415](https://github.com/ray-project/ray/pull/3415) moved setproctitle to ray[debug] and setproctitle is not installed by default.

Without setproctitle installed, the warning message on [#L79](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L79) should be printed. But logger has not been correctly configured using logging.basicConfig.

**Comment by ericl** [comment]
How about we change it to a print() then?

IMO we should consider switching to a more sane logging module such as https://pypi.org/project/glog/.

**Comment by xutianming** [comment]
@ericl I made a pull request [#3483](https://github.com/ray-project/ray/pull/3483)
We can move any logger.warn after calling logging.basicConfig for now.
Glog seems great.
