### ISSUE TITLE
[Core] Logs look weird in Jupyter environment 

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#34831]
### What happened + What you expected to happen

It seems logs can get buffered somewhere, and only show up with the next runs of a remote function.
Run the repro script multiple times in a notebook cell, and you will see.

### Versions / Dependencies

Master HEAD

### Reproduction script

```
import ray

settings_dictionary = {
        "Setting_1" : {
            "DIVISIONS": "A,B,C", 
            "NAME": "ABC_GROUP",
        },
        "Setting_2" : {
            "DIVISIONS": "D,E", 
            "NAME": "DE_GROUP",
        },
        "Setting_3" : {
            "DIVISIONS": "W,X,Y,Z", 
            "NAME": "WXYZ_GROUP",
        }
}

@ray.remote(num_cpus=1)
def score(value):
    print(value["NAME"])
    return len(value["DIVISIONS"].split(","))


# Launch four parallel scoring tasks
futures = [score.remote(value) for key, value in settings_dictionary.items()]

# Retrieve results
print(ray.get(futures))
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@rkooo567 is this being looked at?

**Comment by rkooo567** [comment]
No. I have no bandwidth to take this. What's the priority for this task now?

**Comment by matthewdeng** [comment]
Can we have this addressed by the end of May?

cc @GokuMohandas

**Comment by GokuMohandas** [comment]
yup that sounds good

**Comment by rickyyx** [comment]
This could be fixed with `RAY_DEDUP_LOGS=0` I think. Trying to find a fix.
