### ISSUE TITLE
[serve] Cancel the remote call in HTTPProxy if user drops request

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#34841]
### Description

I would like to help add a feature to ray serve's `HTTPProxy` to cancel the task it submits to the (fastapi) deployment if the user sending the http request, drops the request.

Making an issue here as advised by @richardliaw to initiate the discussion. I am open to be the main driver for adding this feature. I am looking for
- Feedback: is ray open to this addition.
- A partner to help move the PR from initial concept to ray community standard.

More details: I would like (perhaps always on, or maybe tied to a config) to monitor if the connection is dropped here in [ray/serve/_private/http_proxy.py](https://github.com/ray-project/ray/blob/releases/2.4.0/python/ray/serve/_private/http_proxy.py#L117), and if gets dropped call `ray.cancel(object_ref)` on it.

### Use case

We have very heavy ML pipelines that include multiple calls across deployments. If an http request drops (which can happen as a user of UI on frontend might keep changing their mind about what input to pass to their genAI workflow), we don't want the rest of pipeline to spend any resource on it.

Since the pipeline consists of various `await`s (both including delegating to asyncio threadpools and inter deployment communcation), there is plenty  of opportunities for the task to be cancelled. As long as HTTPProxy detects the dropped connections and calls `ray.cancel(..., recursive = True)` on the top level task handle, the cancellation should work automatically.

**Comment by shayanhoshyari** [comment]
Trying to play around with the code a bit, I see that I also need https://github.com/ray-project/ray/issues/22450 - if the scope of `issues/22450` then my fallback is https://github.com/ray-project/ray/issues/34682 - that feature can unblock us too.

**Comment by richardliaw** [comment]
Thanks for opening up this issue! This is awesome. @sihanwang41 or @edoakes will get back to you shortly.

**Comment by edoakes** [comment]
cc @scv119 @rkooo567 we've had a number of feature requests lately related to cancelling tasks in Ray Serve. Do we have an estimate of how much work it would be to support cancelling actor tasks (that use `asyncio`)?

**Comment by edoakes** [comment]
This is done :)
