### ISSUE TITLE
Document in RLlib compatibility matrix which algorithms support data ingest

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#3485]
In documentation in [section on RLlib environments](https://ray.readthedocs.io/en/latest/rllib-env.html#rllib-environments) there is a compatibility matrix for various features of algorithms. Later on, there is a [section on data ingest](https://ray.readthedocs.io/en/latest/rllib-env.html#data-ingest), which notes that one can use `log_action` to ingest previous logs. But in section on [`log_action`](https://ray.readthedocs.io/en/latest/rllib-env.html#logging-off-policy-actions) it is written that just some algorithms support that. So, the question is, which ones? Could this be added to compatibility matrix? And is is true that algorithm has to support off-policy logging to support data ingest?

**Comment by ericl** [comment]
The API works with any algorithm, but whether the algorithm can learn meaningfully on the data depends on whether it is off policy or not. Certainly PPO would not for example.
