### ISSUE TITLE
[AIR] `MLFlowCallback` passes entire `train_loop_config` dict to parallel coordinates

### ISSUE THREAD

**Issue by GokuMohandas** [ray-project/ray#34857]
For a tuning experiment, we pass in a `param_space` with the `train_loop_config` like so:

```python
# Parameter space
param_space = {
    "train_loop_config": {
        "dropout_p": tune.uniform(0.3, 0.9),
        "lr": tune.loguniform(1e-5, 5e-4),
        "lr_factor": tune.uniform(0.1, 0.9),
        "lr_patience": tune.uniform(1, 10),
    }
}
```

I need to pass it in this way, as opposed to directly passing in the contents of `train_loop_config` under `param_space` because I pass in a `TorchTrainer` as my `trainable` to `Tuner`. 

```python
# MLflow callback
mlflow_callback = MLflowLoggerCallback(
    tracking_uri=MLFLOW_TRACKING_URI,
    experiment_name=experiment_name,
    save_artifact=True)

# Run configuration
checkpoint_config = CheckpointConfig(num_to_keep=1, checkpoint_score_attribute="val_loss", checkpoint_score_order="min")
stopping_criteria = {"training_iteration": train_loop_config["num_epochs"]}  # auto incremented at every train step
run_config = RunConfig(
    callbacks=[mlflow_callback],
    checkpoint_config=checkpoint_config,
    stop=stopping_criteria,
)

...

# Trainer
trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    train_loop_config=train_loop_config,
    scaling_config=scaling_config,
    datasets={"train": train_ds, "val": val_ds},
    dataset_config=dataset_config,
    preprocessor=get_preprocessor(),
)

# Tuner
tuner = Tuner(
    trainable=trainer,
    run_config=run_config,
    param_space=param_space,
    tune_config=tune_config,
)
```

This produces the following parallel coordinates plot on MLflow (note that it appears as dictionaries on the plot as opposed to the individual hyperparameters):

![Image](https://user-images.githubusercontent.com/8000987/235048756-e7b14982-d597-4662-a763-c8a1f5a36d98.png)

and `train_loop_config` is the only available option under the Params dropdown:

![Image](https://user-images.githubusercontent.com/8000987/235048808-09526e35-f516-4881-b067-83022580ac2b.png)

To fix this, I modified this [line](https://github.com/ray-project/ray/blob/master/python/ray/air/integrations/mlflow.py#L310) by creating a separate callback class:

```python
# Fixing https://github.com/ray-project/ray/blob/3aa6ede43743a098b5e0eb37ec11505f46100313/python/ray/air/integrations/mlflow.py#L301
class MLflowLoggerCallbackFixed(MLflowLoggerCallback):
    def log_trial_start(self, trial: "Trial"):
        if trial not in self._trial_runs:
            tags = self.tags.copy()
            tags["trial_name"] = str(trial)
            run = self.mlflow_util.start_run(tags=tags, run_name=str(trial))
            self._trial_runs[trial] = run.info.run_id
        run_id = self._trial_runs[trial]
        config = trial.config
        self.mlflow_util.log_params(run_id=run_id, params_to_log=config["train_loop_config"])

# MLflow callback
mlflow_callback = MLflowLoggerCallbackFixed(
    tracking_uri=MLFLOW_TRACKING_URI,
    experiment_name=experiment_name,
    save_artifact=True)
```

Note that the only modification is `params_to_log=config["train_loop_config"]` instead of `params_to_log=config` at the very end of the callback's `log_trial_start` function. And this produces the correct parallel coordinates plot:

![Image](https://user-images.githubusercontent.com/8000987/235048936-e5addbb2-3963-401c-b384-738add92d794.png)

**Comment by krfricke** [comment]
Thanks for raising this. I think the correct solution here is to just flatten the `config` dict before uploading it to mlflow. This is because we could potentially tune parameters outside the train loop config, so we shouldn't just report that inner layer.

With this it will look like this:

<img width="422" alt="Screenshot 2023-05-05 at 11 52 42 AM" src="https://user-images.githubusercontent.com/14904111/236439553-b8be18be-dbf9-49db-8e89-f769713dfcfa.png">
<img width="881" alt="Screenshot 2023-05-05 at 11 53 15 AM" src="https://user-images.githubusercontent.com/14904111/236439652-de7450b9-ffca-44d8-a06f-3b10d70c76b6.png">
