### ISSUE TITLE
[core] Placement group allocation is ignored if no resources are passed

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#34866]
### What happened + What you expected to happen

When an actor is scheduled in a placement group with STRICT_PACK, we would expect it to be "within" that placement group, even if it doesn't require any resources.

However, this is currently not the case: when an actor is scheduled with e.g.

```
pg = placement_group([{"CPU": 4}, {"CPU": 4}], strategy="STRICT_PACK")
actor = ActorCls.options(placement_group=pg, placement_group_bundle_index=0, num_cpus=0).remote()
```

it is _not_ always colocated with the other bundles of the placement group.

This however leads to problems when we actually expect colocation. For instance, in Ray AIR, the trainers regularly have 0 resources allocated, as they are mostly starting sub-training actors. But this can lead to inefficient data transfer, as data (e.g. checkpoints) still has to be shipped to the trainable.

Expected behavior: If I pass `placement_group_bundle_index=0`, I expect the actor to be co-located with that bundle.

### Versions / Dependencies

Ray 2.4, latest master

### Reproduction script

On a 2 node cluster with 8 CPUs per node

```
import ray
from ray.util.placement_group import placement_group


ray.init()


pg1 = placement_group([{"CPU": 4}, {"CPU": 4}], strategy="STRICT_PACK")
pg2 = placement_group([{"CPU": 4}, {"CPU": 4}], strategy="STRICT_PACK")


@ray.remote
class Actor:
	def get_ip(self):
		return ray.util.get_node_ip_address()
		
		
actor1a = Actor.options(placement_group=pg1, placement_group_bundle_index=0, num_cpus=0).remote()
actor1b = Actor.options(placement_group=pg1, placement_group_bundle_index=0, num_cpus=4).remote()
actor1c = Actor.options(placement_group=pg1, placement_group_bundle_index=1, num_cpus=4).remote()

actor2a = Actor.options(placement_group=pg2, placement_group_bundle_index=0, num_cpus=0).remote()
actor2b = Actor.options(placement_group=pg2, placement_group_bundle_index=0, num_cpus=4).remote()
actor2c = Actor.options(placement_group=pg2, placement_group_bundle_index=1, num_cpus=4).remote()

ips_1_f = [actor1a.get_ip.remote(), actor1b.get_ip.remote(), actor1c.get_ip.remote()]
ips_2_f = [actor2a.get_ip.remote(), actor2b.get_ip.remote(), actor2c.get_ip.remote()]

ips_1 = ray.get(ips_1_f)
ips_2 = ray.get(ips_2_f)

print(ips_1)
print(ips_2)
```

The result is stochastic.

Outputs (I ran it multiple times):

```
['10.0.0.44', '10.0.0.51', '10.0.0.51']
['10.0.0.51', '10.0.0.44', '10.0.0.44']
```

```
['10.0.0.51', '10.0.0.44', '10.0.0.44']
['10.0.0.44', '10.0.0.51', '10.0.0.51']
```

```
['10.0.0.44', '10.0.0.44', '10.0.0.44']
['10.0.0.51', '10.0.0.51', '10.0.0.51']
```

But only the last one is expected!

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Fixed by #43269
