### ISSUE TITLE
Issue on page /rllib/index.html

### ISSUE THREAD

**Issue by Yanipo5** [ray-project/ray#34875]
> If you want to learn more about the RLlib training API, [**_you can learn more about it here_**](https://docs.ray.io/en/latest/rllib/rllib-training-api). Also, see [here for a simple example on how to write an action inference loop after training.](https://github.com/ray-project/ray/blob/master/rllib/examples/inference_and_serving/policy_inference_after_training.py)

https://docs.ray.io/en/latest/rllib/rllib-training-api - 404

This link needs to be re aligned.

**Comment by Rohan138** [comment]
Will be fixed by #35675
