### ISSUE TITLE
[docs][clusters] Remove Ray Client from the side nav 

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#34872]
### Description

Reduce the visibility of Ray Client since we discourage users from using it.
@richardliaw, let me know if we should take down the page completely.

### Link

https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html

**Comment by richardliaw** [comment]
Let's not remove the page completely!

**Comment by angelinalg** [comment]
After consulting with @pcmoritz, I will not remove it from the side nav. Instead, the plan is to update the graphic on the Jobs Overview page, removing Ray Client as the third option for running a Ray Job, or some way de-emphasize it from the above-the-fold content.

**Comment by angelinalg** [comment]
Thanks @architkulkarni for updating the diagram.

Closed with https://github.com/ray-project/ray/pull/38337
