### ISSUE TITLE
Error on ES when running `python rollout.py` from checkpoint

### ISSUE THREAD

**Issue by stellaxu** [ray-project/ray#3489]
- I use the original ES to run the rollout.py from checkpoint. 
- 
- However, the render window shows that no matter what env I run, the agent does not move any more, and the reward keeps 0. Would you please help me to check the reason and how to solve it?
- 
- I guess it may be because setting the env in rollout.py file:
-     if hasattr(agent, "local_evaluator"):
-         env = agent.local_evaluator.env        
-     else:
-         env = ModelCatalog.get_preprocessor_as_wrapper(gym.make(args.env))
- 
- For A3C, PPO etc. algorithms, env is set as "env = agent.local_evaluator.env", and the rollout works fine.
- For ES, env is set as "env = ModelCatalog.get_preprocessor_as_wrapper(gym.make(args.env)) ", and the rollout works strange.
- 
- In addition, within ES code, if I use the deepmind wrap for the environment of Atari(   Code like this:     
- if is_atari(self.env):
-             self.env = wrap_deepmind(self.env,dim=84,framestack=4)), 
- the rollout.py cannot pass the compilation. I guess it may be due to "env = ModelCatalog.get_preprocessor_as_wrapper(gym.make(args.env))" as well.

Thanks a lot.

**Comment by ericl** [comment]
Hm if you change it to

```
    else:
        env = gym.make(args.env)
```

does it work then? I think the issue might be the observation gets preprocessed twice.

**Comment by stellaxu** [comment]
Hi, Eric:

Yes, based on your comment,both of the cases are solved in rollout case. 

Really thank you for your help~~
