### ISSUE TITLE
[Tutorials] Tutorials and docs for RLlib

### ISSUE THREAD

**Issue by ZiyiXia** [ray-project/ray#34890]
### Description

Hi, I found that the tutorial repo has been deprecated, and there are few examples in https://github.com/anyscale/academy. However, some of them do not run well in Google Colab. Will there be any update? Thanks!

**Comment by Rohan138** [comment]
Hi, which tutorials are you looking for specifically? The anyscale academy repo was for Ray Summit 2022. Please use the documentation: https://docs.ray.io/en/latest/rllib/index.html for reference.
