### ISSUE TITLE
[CI] `bk://:python: Minimal install 3.11` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#34927]
- 7071a4f3c380dcec144a900fd8349a8b181d5a01 FAILED [:python: Minimal install 3.11](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3699#0187d95c-e392-4286-b8cf-6cc4b7603e46)
- a538758c1076fd0a9791de3666a82b4c9c2d6541 FAILED [:python: Minimal install 3.11](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3654#0187c404-ce39-4eda-ae65-cc5092de4315)
- aeed2b3c58db4a505f2a5b5502e41898290effdb FAILED [:python: Minimal install 3.11](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3652#0187c3e5-133d-4258-bfbe-43e979b29507)
- 8728c77e89602663c5baf3cb27c30c4a16fa5027 FAILED [:python: Minimal install 3.11](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3601#0187b85a-7834-4c8b-a20e-cf750453c80e)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:python: Minimal install 3.11-END
....

**Comment by anyscalesam** [comment]
downgrading this to p1 since it's a python test and we're prioritizing linux for now; agree @rkooo567 ?

**Comment by rickyyx** [comment]
I don't think it's relevant anymore, this is the current test job: https://buildkite.com/ray-project/postmerge/builds/1662#018bcd7f-15f9-42e4-a4ef-75f5de9e8bac
