### ISSUE TITLE
[rllib] Model self loss isn't included in all algorithms

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3494]
### Describe the problem
https://groups.google.com/forum/#!topic/ray-dev/dk0erEEnkFY

In DQN, DDPG, IMPALA, and A3C, the gradients() function for the tf policy graph is overriden, but does not include model.loss().

The fix is to reference `self._loss` in gradients(), since that is always the total loss passed to TFPolicyGraph.

We should also add a simple test that the model self loss is improving for each algorithm (for example by just adding custom model with a free TF variable that gets sent to zero).

**Comment by ericl** [comment]
@megankawakami it would be great if you could look at this.

**Comment by stellaxu** [comment]
Does it mean that for example A3C work wrongly?

**Comment by ericl** [comment]
Only if you are using self supervised losses.

**Comment by stellaxu** [comment]
I got it , thanks.
