### ISSUE TITLE
[serve][docs] More clearly document the config file format in the API reference

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#34955]
We don't document the YAML config format in the docs right now (unless you reverse-engineer the REST API schemas).

Let's also think about how to unify the documentation for `@serve.deployment` and the config... ideally we only have a single source of truth for all of the options. There's currently a `DeploymentConfig` object -- maybe that should be it?

**Comment by edoakes** [comment]
@zcin maybe you can help out with this one? Let's only worry about documenting the multi-app format.

**Comment by cvarrichio** [comment]
I'm having extreme difficulty figuring out how to configure my yaml file to work property.  I'm trying to use ray to start up a gcp environment with an nvidia-l4 accelerator and spot pricing, but [none ](https://docs.ray.io/en/latest/cluster/vms/references/ray-cluster-configuration.html#cluster-configuration-available-node-types) of the [documentation ](https://docs.ray.io/en/latest/tune/tutorials/tune-distributed.html#tune-runs-on-preemptible-instances)seems to contain adequate information to succeed at this.  There needs to be documentation that covers every possible option.

**Comment by akshay-anyscale** [comment]
It's documented now https://docs.ray.io/en/latest/serve/configure-serve-deployment.html
