### ISSUE TITLE
[rllib] Should report all losses in metrics

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3495]
### Describe the problem

Currently the loss values are inconsistently reported across algorithms in metrics. We should always report (1) total loss, (2) policy / vf loss if present (or actor / critic loss), (3) model self loss().

For example, in a3c_tf_policy_graph this is already done correctly (see vf_loss and policy_loss in the stats_fetches dictionary).

There should also be a test that the right stats are returned for each gradient-based alg after a call to train().

**Comment by ericl** [comment]
@michaeltu1 it would be great if you could look at this.

**Comment by waldroje** [comment]
I have found the need to sometimes have multiple model loss ops that I want to identify, and make part of the graph... I accomplished this by passing back a dictionary of ops from the model.loss()... and then writing a custom policy_graph which added those ops to the total loss, and then also would add them to extra_compute_grad_fetches() which I could then access and display in tensorboard via custom optimizer...  might be worth a thought to consider more than a single model loss... but not sure how many would find useful...

**Comment by ericl** [comment]
Cc @AmeerHajAli this might be a good issue to get started on

**Comment by AmeerHajAli** [comment]
That sounds good!
