### ISSUE TITLE
[CI] `linux://python/ray/tests:test_autoscaler_aws` is failing/flaky on master.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#34962]
- 087afa40c9be1db07b2cbd277638283cc13ee678 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3712#0187dd6a-91b9-4e39-bba4-75d16839d0d0)
- 19c172b47df16f128aa61a70a6072af710c2fe96 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3711#0187dd51-9d55-45d5-a4a1-ebccaa9ace9c)
- ff11cb02ee9283d81b3079624b0d9fee6a4f123d FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3710#0187dcad-1ce4-48fc-8910-c74de1272e2f)
- 1564c519b05ca1a1871638f5279ef6b8132054d2 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3709#0187dbb9-63d5-4cf7-9dec-15e4f41d4eba)
- 24c3c4fc57ebacc505aec6e3640c5814b6fab2e9 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3708#0187db0e-f74d-48d3-bf9b-edb16535d370)
- d50f528b4d1786d28bb4e8870258aa2b5614c8f4 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3707#0187dacb-838c-4417-a829-976a9ead1dba)
- f04f5a5cbcb88a49d8a92b7254ba5030f6256b6f FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3706#0187da68-f150-4d37-8c82-8266c3afc8f3)
- f30f2edebb015dd533ef3d4c2e389ad8e5c65219 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3705#0187d9e3-6870-4aa3-84f6-fdfa6146c04b)
- 9f60a09919ac6e2369ff2f07a4ed053e36fbdcad FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3704#0187d9cf-0de3-42e7-b4bc-9693c48de14d)
- 11bf8f5bf6dc14b06b19f9679e20211f18bc34ed FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3703#0187d9cb-dfe2-41f3-baf9-73f28f928e07)
- 7138da55b2be5c87563acc3c86de400231d10850 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3702#0187d995-16c9-48f2-9069-526c80f24b8a)
- 947bceea4cbad8276ea70d74d5a9f7d7cabc250d FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3701#0187d98c-6ada-48d1-a725-076ee53bbca1)
- d87a2513e5c2c91b28258700b60ad9568fb3afea FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3700#0187d977-0a27-491f-80d4-55990f284c8a)
- 7071a4f3c380dcec144a900fd8349a8b181d5a01 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3699#0187d95c-e39b-4db2-8b64-5c44df3b91fe)
- 59822432c701eac4ef73f61f8978510c2f77345d FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3698#0187d93a-05c3-4fb4-a6c2-cdc64d26152c)
- e5a5b0d8d3b5b76d59f690586733cdc4d48ac64b FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3697#0187d918-b2cc-4889-b269-493eb94c939d)
- dbf77ee5f62f103745161d262c0e8875b950e68e FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3696#0187d8f4-61b3-4c29-9dba-82e9eba6a8e3)
- a34b2dc7bbf1b83eba91284c6348163ea439f7ea FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3695#0187d8e7-6f5e-4db4-95b9-543a899b030c)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_autoscaler_aws-END
....

**Comment by architkulkarni** [comment]
Closed by https://github.com/ray-project/ray/pull/34936
