### ISSUE TITLE
[core] cancelling actor tasks

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#34961]
We have multiple feature requests in Ray Serve to cancel tasks / handle HTTP timeouts

- https://github.com/ray-project/ray/issues/22450
- https://github.com/ray-project/ray/issues/34682
- https://github.com/ray-project/ray/issues/34841

It would be simple to implement these if it were possible to `ray.cancel` an object ref to an actor task in an asyncio actor. Ideally this would use the `asyncio.cancel` API so we can handle it gracefully.

**Comment by rkooo567** [comment]
I will take this after streaming is done

**Comment by rkooo567** [comment]
Also, we will make this work for regular actor.

See: https://github.com/ray-project/ray/issues/34698

**Comment by Abhyudhey** [comment]
+1

**Comment by rkooo567** [comment]
We are in progress with this issue!

**Comment by rkooo567** [comment]
The PR is merged. I will close the issue after updating the docstring of ray.cancel tomorrow

**Comment by rkooo567** [comment]
Here's the doc PR https://github.com/ray-project/ray/pull/38776

Note that we don't currently have a plan to support "interrupting a single threaded actor when it is executing". Please create an issue if this is an important use case for you.
