### ISSUE TITLE
[Ray Core] torch.compile raises `TypeError: cannot pickle 'ConfigModuleInstance' object` 

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#35001]
### What happened + What you expected to happen

Serialization of `torch.compile`-ed model (introduced since pytorch 2.0.0) seems unsupported. 

Might be a dup of https://github.com/ray-project/ray/issues/33743 , but that one was closed w/o a solution, so not sure of the status.

### Versions / Dependencies

Ray == 2.3.0
Python == 3.8.10
pytorch == 2.0.0

### Reproduction script

```
from ray import cloudpickle as pkl
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(100, 10)

    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))

mod = MyModule()
opt_mod = torch.compile(mod)
_ = pkl.dumps(opt_mod)
```

### Issue Severity

None

**Comment by matthewdeng** [comment]
Hey @mlguruz, can you explain your use case? Why do you expect/need the compiled model to be serializable?

**Comment by matthewdeng** [comment]
Would you be able to instantiate/compile the model within each Actor/Task process instead?

**Comment by mlguruz** [comment]
you mean something like:

```
@ray.remote(num_gpus=1)
def train(model):
      model_opt = torch.compile(model)
      ...

_ = ray.get(train.remote(model)) 
```

That's what I did I believe...

**Comment by matthewdeng** [comment]
Yeah, in the example you shared the compiled model will actually never be serialized, only the `model`. If the `model` itself is not serializable, you may also defer the creation of the model itself into the task.

Something like this:
```python
@ray.remote(num_gpus=1)
def train(create_model_func):
      model = create_model_func()
      model_opt = torch.compile(model)
      ...

_ = ray.get(train.remote(create_model_func)) 
```

In this example, only `create_model_func` needs to be serializable.

**Comment by mlguruz** [comment]
oh I see, so that everything happens on the worker. 
Yes - right now I'm init-ing the net on the driver, and the fit to the worker. 
Ok - will change and try again. 
Thanks !!

**Comment by matthewdeng** [comment]
@mlguruz cool let me know if that works and if so we can close this issue.

**Comment by mlguruz** [comment]
Will do. Feel free to close it now. If I ran into issues, I'll reopen it. Thanks !
