### ISSUE TITLE
[release-test] Micro-benchmark single_client_wait_1k regression

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#35015]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/74173148/236056370-8634cbc1-cd60-4c22-9d64-881416f532d3.png">

**Comment by iycheng** [comment]
The offending PR is: https://github.com/ray-project/ray/pull/34805

Pass to Chen for a look.

**Comment by scv119** [comment]
we probably need to optimize it. let me take a look tomorrow.

**Comment by scv119** [comment]
actually, the code path seems shouldn't be accessed since it only happens if fetch_local=True

**Comment by scv119** [comment]
huh, actually it's an improvements..

**Comment by scv119** [comment]
Checked again and don't see anything obviously optimizable. Close it for now since it's a bug fix.
