### ISSUE TITLE
[data] Not all progress bars can be disabled

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#35039]
### What happened + What you expected to happen

I'm trying to disable Ray Data progress bars for #34114, but it's not effective.

It seems like the `RAY_DATA_DISABLE_PROGRESS_BARS` variable only disables "sub-"progress bars, e.g.

```
Running: 0.0/16.0 CPU, 0.0/1.0 GPU, 0.0 MiB/4.28 GiB object_store_memory 0:   0%|                                                     | 0/10000 [00:00<?, ?it/s]
- Repartition: 0 active, 0 queued, 0.0 MiB objects, 0 output 1:   0%|                                                                 | 0/10000 [00:00<?, ?it/s]
  *- Repartition 2:   0%|                                                                                                             | 0/10000 [00:00<?, ?it/s]
```

becomes

```
- Repartition: 0 active, 0 queued, 0.0 MiB objects, 0 output 1:   0%|                                                                 | 0/10000 [00:00<?, ?it/s]
```

when run on the driver.

Additionally, the fact that `RAY_DATA_DISABLE_PROGRESS_BARS` is read on import means that setting the env variable e.g. via runtime_env is ineffective for the driver.

The problem persists in remote tasks.

### Versions / Dependencies

2.4.0 / master

### Reproduction script

```
import ray
import time


ray.init(runtime_env={"env_vars": {
    "RAY_DATA_DISABLE_PROGRESS_BARS": "1"
}})


def work(batch):
    time.sleep(0.5)
    return batch


def load_data():
    ds = ray.data.from_items(range(100_000))
    ds = ds.repartition(10000)
    ds.map_batches(work)
    return ds

ray.data.set_progress_bars(False)

ds = load_data()
print(ds.to_pandas())

# Also doesn't work well in remote tasks
# @ray.remote
# def remote_task():
#     ray.data.set_progress_bars(False)
#     ds = load_data()
#     print(ds.to_pandas())


# ray.get(remote_task.remote())
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
cc @ericl

**Comment by ericl** [comment]
Per https://github.com/ray-project/ray/issues/34114, for Tune/Train you still need to propagate the DataContext manually: https://github.com/ray-project/ray/issues/34114#issuecomment-1517066806

**Comment by ericl** [comment]
Let's consolidate discussion on the original issue.
