### ISSUE TITLE
[Tune] infinite stack recursion upon closing down after an error during debugging

### ISSUE THREAD

**Issue by oharboe** [ray-project/ray#35034]
### What happened + What you expected to happen

@maliberty I'm seeing a problem with infinite stack recursion upon closing down after an error during debugging.

The infinite stack recursion occurs here as the file handle to be flushed is closed:

https://github.com/ray-project/ray/blob/bedecacfd3a07868072e0478a459f3fed44b76d3/python/ray/tune/utils/util.py#L343

When a process starts, `sys.stdout` is owned by the system and it is responsible for shutting it down.

![image](https://user-images.githubusercontent.com/2798822/236171809-f4548b43-4d33-4638-9379-dc5d3d4578d3.png)

Tee(sys.stdout, somefile) is invoked multiple times. So my concern is who is responsible for closing sys.stdout?

https://github.com/ray-project/ray/blob/bedecacfd3a07868072e0478a459f3fed44b76d3/python/ray/tune/trainable/trainable.py#L1100

### Versions / Dependencies

ray 2.4.0

### Reproduction script

I'm only just getting started with ray and trying to get it into the debugger when I ran into this infinite recursion.

I'm trying to get https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/util/distributed.py to work.

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @matthewdeng

**Comment by rkooo567** [comment]
@matthewdeng I will leave it up to you for now!

**Comment by matthewdeng** [comment]
Assigning to @krfricke for a first look

**Comment by oharboe** [comment]
@maliberty FYI
