### ISSUE TITLE
[serve] Allow callback to be called in HTTPProxy constructor.

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#35046]
### Description

Allow custom callback to run in HTTPProxy actor.

### Use case

We would like to do some customization on all our deployments and actors. We can do that in the constructor, except for the HTTPProxy. example of things we would like to do

- logging config:
   - patch makeRecord: include our own request id from our own global context.
   - modify handlers: include the newly added info from makeRecord by changing the formatter of handlers.
- Connect to vscode debugger from their [API](https://github.com/microsoft/debugpy/blob/main/src/debugpy/public_api.py#L123)

**Comment by shayanhoshyari** [comment]
The proposed solution sounds great.

**Comment by edoakes** [comment]
@sihanwang41 I think let's go with just an environment variable for now until it's work and stable for this use case, then we can promote as a public API
