### ISSUE TITLE
[Train] Log message has residual from previous code

### ISSUE THREAD

**Issue by GokuMohandas** [ray-project/ray#35055]
Not sure if this is specific to logs from Trainer but logs show the output from the previous commands. So I have to rerun a piece of code multiple times to get rid of any residual outputs from the previous code.

**Note:** minimal reproducible example under Notes for this Project. But you can simply add a print statement inside your `train_loop_per_worker`, use `Trainer` to run this loop, watch the output. Then change the print statement inside `train_loop_per_worker`, rerun the Trainer with the new changed `train_loop_per_worker` and you'll see the same residual print message that would be displayed consistent with the original print statement.

**Comment by matthewdeng** [comment]
Is this happening in a Jupyter notebook? If so then I think this might be a duplicate instance of https://github.com/ray-project/ray/issues/34831.

**Comment by GokuMohandas** [comment]
Yup you're right @matthewdeng , let me close this one and point to #34831 in the project.
