### ISSUE TITLE
[Data] Splitting train dataset is random (with no way to configure deterministic behavior)

### ISSUE THREAD

**Issue by GokuMohandas** [ray-project/ray#35053]
When we pass in datasets along with a preprocessor to a `Trainer`, the datasets denoted as `train` will be automatically split over a number of workers. The issue is that this split happens randomly and it's not possible to control how this is done.

I already have `ray.data.DatasetContext.get_current().execution_options.preserve_order = True` set and passed in `randomize_block_order=False` into the DatasetConfig:

```python
ray.data.DatasetContext.get_current().execution_options.preserve_order = True

# Dataset config
dataset_config = {
    "train": DatasetConfig(randomize_block_order=False),
    "val": DatasetConfig(randomize_block_order=False),
}

# Trainer
trainer = TorchTrainer(
    ...
    datasets={"train": train_ds, "val": val_ds},
    dataset_config=dataset_config,
    ...
)
```

**Minimal reproducible example**: https://colab.research.google.com/drive/1H84pmEROJI38TzU_hbbwmFRuxM_tM5BP?usp=sharing (you can run it locally or on large enough cluster, need minimum 3 CPUs)

**Comment by ericl** [comment]
@c21 @raulchen I think we need to scope out the priority of a proper deterministic execution feature.

**Comment by raulchen** [comment]
@GokuMohandas I tried the notebook. In this case, we will only apply a `map_batches` op to the dataset. the DAG is `InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange->MapBatches(BatchMapper._transform_pandas)]`. 

Today although not all ops respect the `preserve_order` flag, all map-related ops should respect it. 
I'm wondering if the randomness could come from somewhere else.

**Comment by ericl** [comment]
Is this with multiple workers? The streaming_split() operator is not deterministic, so it might explain the nondeterminism even with map operators fixed.

**Comment by GokuMohandas** [comment]
Hey @raulchen, I see. I'll have to defer to @ericl as he will have more insight into some implicit source of randomness.

**Comment by raulchen** [comment]
Hey @GokuMohandas, I confirmed with @ericl. The [new ingestion API ](https://docs.ray.io/en/master/ray-air/check-ingest.html)should ensure determinism. Could you try this?
Regarding the new API, basically the main difference is that the dataset should be precessed before passing it to the trainer. 
For your notebook, we'll need to change Cell 15 to something like:
```python
train_ds = preprocessor.fit_transform(train_ds)
trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    scaling_config=scaling_config,
    datasets={"train": train_ds, "val": val_ds},
    preprocessor=preprocessor
)
trainer.fit()
```

**Comment by GokuMohandas** [comment]
Hey @raulchen, hmm unfortunately I still see random behavior even when performing the preprocessing prior to Training. Check out the [updated notebook here](https://colab.research.google.com/drive/1YNK8sO4XdjTPPdc32yieNO0yl3c7BQYy#scrollTo=KII2oH_lMmRp) (you will have to download and run locally on macbook because colab doesnt have enough CPUs).

**Comment by raulchen** [comment]
@GokuMohandas #36919 should fix this issue

**Comment by raulchen** [comment]
https://github.com/ray-project/ray/pull/36919 is merged. Please let me know if this issue is fixed.
