### ISSUE TITLE
[CI] `bk://:mac: :apple: Wheels and Jars (intel)` is failing/flaky on master.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#35054]
- adae99023aadfe15bd406c80c80457c790954cbd FAILED [:mac: :apple: Wheels and Jars (intel)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3761#0187e822-edac-44fe-8856-ed7b79c56186)
- 9e636a2a96d94409d913895601cbe1e6c605050d FAILED [:mac: :apple: Wheels and Jars (intel)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3760#0187e820-0075-43cc-9f57-da3dd0793f92)
- 857328f7edd6a147c7c986e2009104f2a9ad3486 FAILED [:mac: :apple: Wheels and Jars (intel)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3759#0187e813-57a5-4230-9958-3d0d533562d7)
- b5e5bd7beb1d725dbc7689ee1e7fa3c9a8bef771 FAILED [:mac: :apple: Wheels and Jars (intel)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3686#0187d62b-056c-48fa-a245-108ff7bd09e7)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:mac: :apple: Wheels and Jars (intel)-END
....

The error is:

```
> export BUILDKITE_HOOK_WORKING_DIR=/Users/ec2-user/.buildkite-agent/builds/bk-macos-branch-queue-i-0558c06aac793f697-1/ray-project/oss-ci-build-branch
--
  | > BUILDKITE_HOOK_WORKING_DIR=/Users/ec2-user/.buildkite-agent/builds/bk-macos-branch-queue-i-0558c06aac793f697-1/ray-project/oss-ci-build-branch
  | > buildkite-agent env dump
  | > exit 1
  | 🚨 Error: The command exited with status 1
  |  

<br class="Apple-interchange-newline">
```

The wheel actually has been built

<img width="720" alt="image" src="https://user-images.githubusercontent.com/74173148/236334151-5a0b77ba-b157-4f0a-b21a-6c2ba5f63a0b.png">

**Comment by rkooo567** [comment]
<img width="1387" alt="Screen Shot 2023-05-15 at 2 25 57 PM" src="https://github.com/ray-project/ray/assets/18510752/0eb11872-3480-4c58-8749-63401f5f1d3a">

seems to be fixed!
