### ISSUE TITLE
[core][release_test] tune_air_oom is jailed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35061]
### What happened + What you expected to happen

The following test has been jailed since it has been failing consistently for more than 2 weeks:
- tune_air_oom

It won't be run automatically on nightly run anymore, but you can still run them on cloud manually. Usually I'll create release-blocking issue for these, but I skip that tag for now since these tests are already pretty much ignored.

### Versions / Dependencies

master

### Reproduction script

buildkite

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
@c21 is taking a look at this issue for now. I will co-assign it to him (the failure is related to the data APi changes)

**Comment by rynewang** [comment]
@c21 any updates?

**Comment by anyscalesam** [comment]
closing - if we detect a fresh re-run we can assign and look at them.
