### ISSUE TITLE
Ray air: Did not find socket name /tmp/ray/session_2023-05-04_23-52-37_148997_237020/sockets/plasma_store

### ISSUE THREAD

**Issue by kaare-mikkelsen** [ray-project/ray#35077]
### What happened + What you expected to happen

I am running the ray lightning trainer example (https://docs.ray.io/en/latest/train/api/doc/ray.train.lightning.LightningTrainer.html#ray.train.lightning.LightningTrainer) inside a linux container, and am getting the following error message:

```
Traceback (most recent call last):
File “/opt/conda/envs/conda_container_env/lib/python3.9/site-packages/ray/_private/node.py”, line 292, in init
ray._private.services.wait_for_node(
File “/opt/conda/envs/conda_container_env/lib/python3.9/site-packages/ray/_private/services.py”, line 460, in wait_for_node
raise TimeoutError(
TimeoutError: Timed out after 30 seconds while waiting for node to startup. Did not find socket name /tmp/ray/session_2023-05-04_23-52-37_148997_237020/sockets/plasma_store in the list of object store socket names.
```

I have tried simply binding the /tmp/ folder to the container, to make sure it has access, but it seems that is not enough (at least, the error message didn't change). How do I progress from here? I have also reached out to the community surrounding the container type, but they seem unsure what exactly ray is trying to do. 

### Versions / Dependencies

ray: 2.4.0
python: 3.9.16
lightning-utilities: 0.8.0
OS: Ubuntu 22.04.1 LTS 

### Reproduction script

Unless someone is willing to build a singularity container, then it's quite hard to reproduce this, unfortunately. 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
This usually happens if Ray fails to start a node (ray start failed). Can you check
- ps aux | grep raylet to see if raylet is alive in your container?
- Also can you provide raylet.out/err & gcs_server.out/err logs to us?
