### ISSUE TITLE
It appears the PR about deflaking test_advanced_9 caused it to fail

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35076]
### What happened + What you expected to happen

The PR about deflaking test_advanced_9 has caused it to fail.

### Versions / Dependencies

main branch.

### Reproduction script

Check out https://flakey-tests.ray.io/

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
I believe we fixed it. Please reopen if it is not true!
