### ISSUE TITLE
[docs] fix link on landing page

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#35078]
### Description

The link for Ray Core goes to Installation page.

### Link

https://docs.ray.io/en/latest/

**Comment by simran-2797** [comment]
I had already fixed this few weeks back and it's merged in Master.

**Comment by angelinalg** [comment]
Yes, this was already merged into master and cherry picked to 2.4.0, but it wasn't showing up on the 2.4.0 release because the build failed. Sorry for the noise.
