### ISSUE TITLE
[data] [docs] fix broken examples that use session.get_dataset_shard("train")

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#35136]
### Description

Comment #14 from this friction log: https://docs.google.com/document/d/1fMF-Pt0gzJDhPJpmGQVUmEoUXsPwvSnHnJR058lLm8g/edit#

**Comment by c21** [comment]
@bveeramani - could you take a look? Thanks.

**Comment by bveeramani** [comment]
Spoke with @grimreaper offline -- the issue was due to upgrading from Ray 2.2 to Ray 2.4. Can't think of any actionable changes we should make to the docs, so I'm closing this issue.
