### ISSUE TITLE
[core][state] Worker launch time incorrect for driver

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#35130]
### What happened + What you expected to happen

```
-   worker_id: 01000000ffffffffffffffffffffffffffffffffffffffffffffffff
    is_alive: false
    worker_type: DRIVER
    exit_type: INTENDED_USER_EXIT
    node_id: 169643245001a3fd78e69da6084d3306fb8d7e312f19a6ee88183fdf
    ip: 127.0.0.1
    pid: 44527
    exit_detail: Shutdown by ray.shutdown().
    worker_launch_time_ms: 18446744073709551615
    worker_launched_time_ms: 18446744073709551615
    start_time_ms: '2023-05-08 21:36:46.864000'
    end_time_ms: '2023-05-08 21:36:47.977000'
```

where

```
    worker_launch_time_ms: 18446744073709551615
    worker_launched_time_ms: 18446744073709551615
```

### Versions / Dependencies

master

### Reproduction script

run a driver script and then `ray list workers --detail` 

### Issue Severity

None

**Comment by ProjectsByJackHe** [comment]
> ### What happened + What you expected to happen
> ```
> -   worker_id: 01000000ffffffffffffffffffffffffffffffffffffffffffffffff
>     is_alive: false
>     worker_type: DRIVER
>     exit_type: INTENDED_USER_EXIT
>     node_id: 169643245001a3fd78e69da6084d3306fb8d7e312f19a6ee88183fdf
>     ip: 127.0.0.1
>     pid: 44527
>     exit_detail: Shutdown by ray.shutdown().
>     worker_launch_time_ms: 18446744073709551615
>     worker_launched_time_ms: 18446744073709551615
>     start_time_ms: '2023-05-08 21:36:46.864000'
>     end_time_ms: '2023-05-08 21:36:47.977000'
> ```
> 
> where
> 
> ```
>     worker_launch_time_ms: 18446744073709551615
>     worker_launched_time_ms: 18446744073709551615
> ```
> 
> ### Versions / Dependencies
> master
> 
> ### Reproduction script
> run a driver script and then `ray list workers --detail`
> 
> ### Issue Severity
> None

I tried running without the humanify features, and still get the wrong data.

Yeah I have no idea why this is happening. I suspect it doesn't have anything to do with the formatting logic, but maybe with the way the data is generated in the first place?
