### ISSUE TITLE
Is it possible to export Tensorflow SavedModel from PolicyGraph for serving?

### ISSUE THREAD

**Issue by xutianming** [ray-project/ray#3513]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **Ray installed from (source or binary)**:source
- **Ray version**:0.6.0
- **Python version**:Anaconda 2.7.15
- **Exact command to reproduce**:

### Describe the problem

Related Issues [#3183](https://github.com/ray-project/ray/issues/3183) [#2764](https://github.com/ray-project/ray/issues/2764) 

I am trying to export DQNPolicyGraph as Tensorflow SavedModel for online serving using [SavedModelBuilder Api](https://www.tensorflow.org/guide/saved_model). 

I added following codes in tf_policy_graph.py for experiment.
![image](https://user-images.githubusercontent.com/4970790/49789533-33f5b680-fd67-11e8-8c31-7ab48130a87a.png)

The exported model seems empty. Do you have any suggestions?

**Comment by ericl** [comment]
Perhaps you're not using the right session and/or graph? TFPolicyGraph has `self._sess`.

**Comment by xutianming** [comment]
> graph
I tried self._sess, too. saved_model.pb could be generated but there were no variables.
I also tried to restore self._sess from a previously saved checkpoint.
![image](https://user-images.githubusercontent.com/4970790/49841752-c5126f00-fdf3-11e8-93b4-e524795076e6.png)

self._obs_input is a placeholder and self._sampler is a tensor.

**Comment by Rajamohanreddyai** [comment]
Hello all, just follow the below video and export your own model with in a 10 seconds

https://youtu.be/w0Ebsbz7HYA
