### ISSUE TITLE
[Tune] Log csv files using double quotes

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3514]
Is it possible to write the keys of dicts in `results` using double quotes? 

For now, when analyzing the results in csv files, I want to transform a string to a dict using `json.loads`, and it raises `JSONDecodeError: Expecting property name enclosed in double quotes`. Although this can be replaced with `ast.literal_eval` or `eval`, it seems that `json.loads` is a preferable way to do this.

**Comment by richardliaw** [comment]
Can you try loading the JSON output too? There should be a `result.json` that has properly formatted json outputs for results.

Alternatively, after #3465 goes in today, if the above doesn't resolve your issue, it wouldn't be hard for you to try out something custom-made.
