### ISSUE TITLE
No handlers could be found for logger "ray.worker"

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#3515]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.13.6
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.0
- **Python version**: 2.7.10
- **Exact command to reproduce**: pip install ray==0.6.0; run python then run `import ray`

### Describe the problem

Upon import you get the following error and nothing else: 
No handlers could be found for logger "ray.worker"
### Source code / logs

No handlers could be found for logger "ray.worker"

**Comment by robertnishihara** [comment]
Thanks @eugenevinitsky! Should be fixed in the current master. Can you try that out?

**Comment by eugenevinitsky** [comment]
Ah yes, I will in a bit! This is from an attempt to install on another labs machine.
