### ISSUE TITLE
[Serve] Old Logs causing out of memory issues for scaling cluster

### ISSUE THREAD

**Issue by kyle-v6x** [ray-project/ray#35154]
### What happened + What you expected to happen

We're running a Serve deployment on AWS to run GPU inference. The deployment is running pseudo-permanently. We are having issues with old log files (i.e head/logs/old) taking up way too much space, and eventually crashing the head instance.

Reading through documentation, it's difficult to know if there is some bug here, regarding recycling of worker nodes.

The cluster scales from 1-30 workers, and workers are cached in AWS. However, the Ray Dashboard shows that each time a worker is killed, and relaunched, a new worker ID and log is created and there are thousands of dead nodes tracked in the dashboard. This results in thousands of large old log files which are not handled by log rotation (as the logs are different).

The especially problematic log files are over 150k lines each and of the format:
`worker-12b4d8641c7f0da733ccadc0a4765fc7f69dfb3ccfab07b3b7478a7d-01000000-18912.out`

`/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-112118833ef0817e690f9a3144ac850677aa7917780e2102ab64ea95-01000000-10417.err161958/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-7851624c0da5f6dce0802a9a6817f27767d39033034b1441ab574d83-01000000-22277.err161959/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-016b2d0d5d1d7721a38637074bc28b0f3adbe64b0e07971adcef6a68-01000000-19384.out161960/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-a178f7e1f81e4caf1f20849d9f53e7d144e3fcd6514d4408277f9184-01000000-25707.err161961/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-8ed6f2039af1a770972e0be9184820e0438ea3caf38c3a552b61d984-01000000-5873.err161962/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-c9538152736311bfe6940b0e90b15a03463de005107728c9231072aa-01000000-3792.out161963/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-b137e32175cd639536c21452861585f89fd8f4dfae2a410bb75fc3d4-01000000-14197.out161964/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-c0e0f46ca76de9edea01551cba4231d7dcf02472ea5bf7c4ec221905-01000000-3414.err161965/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-6bec5589446c6057fa65da535c8758cd5e188c96d43e0d63eb43e2ae-01000000-9836.err161966/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-089b81c104cbebea1a4b27f81e534bd27eb2b5c1705cf39b0c17e5c6-01000000-8366.out161967/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-5d6765d4a116256e85c2e69aa23b37d6506bc4e406be11fb49d2a3be-01000000-1448.err161968/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-4c2f31b538e21deee6a433daa3c1819a0b191bf95eefc4912267dff4-01000000-14143.out161969/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-96a1b54c494658516ac53d436add855643173791d1d12f3a03353994-01000000-16094.err161970/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-5881441c27f74e8475f93dcb0c6a7c4f36d06f300ae1b9e2fb335c3c-01000000-966.out161971/tmp/ray/session_2023-04-26_04-05-46_373468_338/logs/old/worker-b06cb116ef78472a38e4e4a13095c03af3920b36ab0bb2e7f001d90b-01000000-25652.out`

Is this inteanded behaviour? It seems like this must be a common issue as it doesn't seem like a particularely special use-case.

### Versions / Dependencies

[requires]
python_version = "3.8"

[packages]
boto3 = "==1.26.112"
tqdm = "==4.65.0"
soundfile = "==0.12.1"
ray = {version = "==2.2.0", extras = ["serve"]}

### Reproduction script

As it is cloud-related I'm unable to provide a direct reproduction script.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by os-a2** [comment]
[Raylet and Python/Java worker logs are not rotating](https://docs.ray.io/en/latest/ray-observability/ray-logging.html#log-rotation)

I think you need to set up log rotations by yourself using something like logrotate

**Comment by kyle-v6x** [comment]
This should be fixed with https://github.com/ray-project/ray/pull/31844

**Comment by kyle-v6x** [comment]
Should be fixed with: https://github.com/ray-project/ray/pull/31844
