### ISSUE TITLE
[RLlib] ApexDQN does not train cartpole

### ISSUE THREAD

**Issue by trirpi** [ray-project/ray#35175]
### What happened + What you expected to happen

When training ApexDQN the following is shown as a warning and no training progression is made:

    (autoscaler +31s) Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.

Ray status shows the following:

```
======== Autoscaler status: 2023-05-09 19:24:44.732585 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_f1cdf190699783dab2746e5868d19c969c135f148ff114d2820f8d33
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 4.0/4.0 CPU
 0B/2.17GiB memory
 0B/1.09GiB object_store_memory

Demands:
 {'CPU': 1.0}: 28+ pending tasks/actors
```

Exact same code with PPO or DQN works perfectly.

### Versions / Dependencies

OS: same problem on Mac & Ubuntu
Python: 3.9
Ray: 2.3.1

Computer has 8 cpus, no gpu

### Reproduction script

```
import ray
from ray.rllib.algorithms.apex_dqn import ApexDQNConfig

if __name__ == "__main__":
    ray.init(num_cpus=4, num_gpus=0)
    alg = ApexDQNConfig().resources(num_gpus_per_worker=0, num_gpus=0).environment("CartPole-v1").build()
    alg.train()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by avnishn** [comment]
@trirpi this is happening probably because your algo is requesting 5 cpus in order to run the experiment. Try reducing the number of rollout workers, replay actors, or setting num_cpus_for_driver=0.

**Comment by denfromufa** [comment]
@trirpi did you resolve this issue, @avnishn is there any working experiment for apex_dqn? The docs seem outdated.
