### ISSUE TITLE
[AIR] Correctly unpack metrics with "/" in their names

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#35187]
### What happened + What you expected to happen

In #35000 , we unflattened the metrics for `trial.last_result`. However, if the metric name itself has a "/" character, it will be unflatten into a dictionary instead, which should not happen. One release test [failed](https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_4k4fdm16cci36ks4n4sna2hqjg) because of this change.

e.g.
```
metric = {"ptl/val_accuracy": 0.9}
# after dict unflatten
metric = {"ptl": {"val_accuracy": 0.9}}
```

One fact: The users should be able to use metrics with '/'. For example, it's meaningful for wandb because the metrics with the same prefix will be grouped together.

#### Potential Solution:

Instead of flatten into a string delimited by '/', we flatten into a tuple. 
```
Current way:
{"a": {"b": {"c": 1}}} -> {"a/b/c": 1}

After change:
{"a": {"b": {"c": 1}}} -> {("a", "b", "c")": 1}
```

### Versions / Dependencies

on master branch

### Reproduction script

`/Users/yunxuanx/Code/ray/release/lightning_tests/workloads/test_tuner.py`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@krfricke

**Comment by woshiyyya** [comment]
Reviving this issue cause I saw some users in 2.4 are using code below. Upgrade to 2.5 will break their code. 

```python
best_checkpoint = result.checkpoint
best_metrics = result.metrics
for checkpoint, metrics in result.best_checkpoints:
    if metrics["metrics/val/auroc"] > best_metrics["metrics/val/auroc"]:
        best_checkpoint = checkpoint
        best_metrics = metrics
```
