### ISSUE TITLE
[core][release-test] benchmark_worker_startup.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35183]
### What happened + What you expected to happen

benchmark_worker_startup.aws has been failing for 3 days. I cannot bisect because whatever broke it is outside of Ray. It is marked as unstable as well so if we think it's not worth fixing I'll just jail it.

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1641#0187ff1f-27fd-4316-ae43-4d8b692ac095

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by cadedaniel** [comment]
I can take this @scv119 , looks like our infra provider has a new default runtime env, need to either remove the tests with empty runtime env or find a way around the new runtime env
