### ISSUE TITLE
Fatal Python error with redis memory limit enabled

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#3519]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: cffe8f98063eed002c15509c2143c1cc04a53d77
- **Python version**: 3.6.5

### Describe the problem
I build a 10-node cluster with 5 redis shards and `redis-max-memory=30GB` per data shard.

After running for a long time, the console shows
<pre>
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1212 04:42:45.582706 25291 local_scheduler_client.cc:354] Problem communicating with raylet from worker: check logs or dmesg for previous errors.
*** Check failure stack trace: ***
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home1/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/worker.py", line 2513 in wait
  File "/home1/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 188 in get_next_available_trial
  File "/home1/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 238 in _process_events
  File "/home1/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 118 in step
  File "/home1/lanlin/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/ray/tune/tune.py", line 108 in run_experiments
  File "main_train.py", line 184 in <module>
</pre>

### Source code / logs
Here are some other logs https://gist.github.com/llan-ml/e40e57fe4e78a50448bb00a54cf11ec0.

**Comment by ericl** [comment]
Relevant bit here
```
W1212 03:57:10.389991 24878 client_connection.cc:247] [worker]ProcessMessage with type 8 took 249 ms.
W1212 04:37:49.193456 24878 node_manager.cc:243] Last heartbeat was sent 2706 ms ago 
F1212 04:42:45.231518 24878 node_manager.cc:492] Failed to update state to DEAD for actor 6681125417e8c0e2a8a51f474ed0cafb498578bf
*** Check failure stack trace: ***
    @           0x577d46  google::LogMessage::Fail()
    @           0x577c92  google::LogMessage::SendToLog()
    @           0x577616  google::LogMessage::Flush()
    @           0x577425  google::LogMessage::~LogMessage()
    @           0x4ddc18  ray::RayLog::~RayLog()
    @           0x50cfae  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDERK15ActorTableDataTEZNS0_6raylet11NodeManager23HandleDisconnectedActorES6_bEUlS3_S6_S9_E_E9_M_invokeERKSt9_Any_dataS3_S6_S9_
    @           0x4bbc8f  _ZNSt17_Function_handlerIFbRKSsEZN3ray3gcs3LogINS3_8UniqueIDE14ActorTableDataE8AppendAtERKS6_SA_RSt10shared_ptrI15ActorTableDataTERKSt8functionIFvPNS4_14AsyncGcsClientESA_RKSC_EESN_iEUlS1_E_E9_M_invokeERKSt9_Any_dataS1_
    @           0x4d9ce9  (anonymous namespace)::ProcessCallback()
    @           0x4d9f2b  ray::gcs::GlobalRedisCallback()
    @           0x5281e6  redisProcessCallbacks
    @           0x4dd6a3  RedisAsioClient::handle_read()
    @           0x4ddb31  boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @           0x4978e1  boost::asio::detail::task_io_service::run()
    @           0x48ff9e  main
    @     0x7fc933031830  __libc_start_main
    @           0x4947d1  (unknown)
pure virtual method called
terminate called without an active exception
Fatal Python error: Aborted
```

**Comment by ericl** [comment]
@pcmoritz @swang the actor table shouldn't be in the sharded redis right? So perhaps this isn't related to the GCS lru?

**Comment by llan-ml** [comment]
I set up a cluster with 4 nodes and 3 redis shards, and run [script](https://gist.github.com/llan-ml/f11cf6c98a2f21074121dd2574b7463f). I try `redis-max-memory` being 1, 2, and 5GB.
For 1 and 2GB, the raylet_0.err is
<pre>
...
W1212 15:43:01.526669 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:43:44.084280 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:43:49.698982 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:44:00.658151 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:44:10.986420 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:44:25.281145 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:44:30.767060 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:44:41.737710 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:45:23.080502 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:45:53.069020 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
W1212 15:45:53.074594 47534 client_connection.cc:116] ServerConnection has 1024 buffered async writes
E1212 15:49:20.308598 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309281 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309420 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309497 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309551 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309595 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.309901 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.884644 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.885020 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.885272 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
E1212 15:49:20.885344 47534 node_manager.cc:1567] The output of an actor task is required, but the actor may still be alive. If the output has been evicted, the job may hang.
F1212 15:49:22.193502 47534 node_manager.cc:1556]  Check failed: lineage_cache_.ContainsTask(task_id) Task metadata not found in either GCS or lineage cache. It may have been evicted by the redis LRU configuration. Consider increasing the memory allocation via ray.init(redis_max_memory=<max_memory_bytes>).
*** Check failure stack trace: ***
    @           0x577d46  google::LogMessage::Fail()
    @           0x577c92  google::LogMessage::SendToLog()
    @           0x577616  google::LogMessage::Flush()
    @           0x577425  google::LogMessage::~LogMessage()
    @           0x4ddc18  ray::RayLog::~RayLog()
    @           0x515de1  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDEEZNS0_6raylet11NodeManager24HandleTaskReconstructionES6_EUlS3_S6_E0_E9_M_invokeERKSt9_Any_dataS3_S6_
    @           0x4d84f0  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDERKSt6vectorINS0_8protocol5TaskTESaIS9_EEEZNS1_5TableIS4_NS8_4TaskEE6LookupES6_S6_RKSt8functionIFvS3_S6_RKS9_EERKSI_IFvS3_S6_EEEUlS3_S6_SD_E_E9_M_invokeERKSt9_Any_dataS3_S6_SD_
    @           0x4c7428  _ZZN3ray3gcs3LogINS_8UniqueIDENS_8protocol4TaskEE6LookupERKS2_S7_RKSt8functionIFvPNS0_14AsyncGcsClientES7_RKSt6vectorINS3_5TaskTESaISC_EEEEENKUlRKSsE_clESM_
    @           0x4d9ce9  (anonymous namespace)::ProcessCallback()
    @           0x4d9f2b  ray::gcs::GlobalRedisCallback()
    @           0x5281e6  redisProcessCallbacks
    @           0x4dd6a3  RedisAsioClient::handle_read()
    @           0x4ddb31  boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @           0x4978e1  boost::asio::detail::task_io_service::run()
    @           0x48ff9e  main
    @     0x7f9a08fc0830  __libc_start_main
    @           0x4947d1  (unknown)
</pre>

For 5GB, the raylet_0.err is
<pre>
...
I1212 16:58:22.393203  8906 node_manager.cc:1680] Resubmitting task 0000000093bb42f53d1f5b41b77ff6369bf50555 because ForwardTask failed.
I1212 16:58:22.418032  8906 node_manager.cc:1680] Resubmitting task 000000004cedc5baebf29afe67f68efccc1e0435 because ForwardTask failed.
I1212 16:58:22.437892  8906 node_manager.cc:1680] Resubmitting task 00000000e905c93ebc86c42d866f87af367d0f32 because ForwardTask failed.
I1212 16:58:22.440747  8906 node_manager.cc:1680] Resubmitting task 000000007963d2119ceeed1859acaa2be6ac67b2 because ForwardTask failed.
I1212 16:58:22.450469  8906 node_manager.cc:1680] Resubmitting task 000000005c47cb5953f9945ef995dc3e26d1d10a because ForwardTask failed.
I1212 16:58:22.496278  8906 node_manager.cc:1680] Resubmitting task 0000000051a874f5c5d06279c073c30f72c311d1 because ForwardTask failed.
I1212 16:58:22.512140  8906 node_manager.cc:1680] Resubmitting task 0000000042f03ca3ca5cfada967981552bfd4f78 because ForwardTask failed.
I1212 16:58:22.515924  8906 node_manager.cc:1680] Resubmitting task 00000000e59dbddf74707d7369c542c03f31636d because ForwardTask failed.
I1212 16:58:22.555151  8906 node_manager.cc:1680] Resubmitting task 00000000c50f8e57f47f5c183ecbe4d9299bc616 because ForwardTask failed.
F1212 16:58:27.903470  8906 node_manager.cc:492] Failed to update state to DEAD for actor 9e3b2dec63e702765b755c26f7370665fda8e9ac
*** Check failure stack trace: ***
    @           0x577d46  google::LogMessage::Fail()
    @           0x577c92  google::LogMessage::SendToLog()
    @           0x577616  google::LogMessage::Flush()
    @           0x577425  google::LogMessage::~LogMessage()
    @           0x4ddc18  ray::RayLog::~RayLog()
    @           0x50cfae  _ZNSt17_Function_handlerIFvPN3ray3gcs14AsyncGcsClientERKNS0_8UniqueIDERK15ActorTableDataTEZNS0_6raylet11NodeManager23HandleDisconnectedActorES6_bEUlS3_S6_S9_E_E9_M_invokeERKSt9_Any_dataS3_S6_S9_
    @           0x4bbc8f  _ZNSt17_Function_handlerIFbRKSsEZN3ray3gcs3LogINS3_8UniqueIDE14ActorTableDataE8AppendAtERKS6_SA_RSt10shared_ptrI15ActorTableDataTERKSt8functionIFvPNS4_14AsyncGcsClientESA_RKSC_EESN_iEUlS1_E_E9_M_invokeERKSt9_Any_dataS1_
    @           0x4d9ce9  (anonymous namespace)::ProcessCallback()
    @           0x4d9f2b  ray::gcs::GlobalRedisCallback()
    @           0x5281e6  redisProcessCallbacks
    @           0x4dd6a3  RedisAsioClient::handle_read()
    @           0x4ddb31  boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @           0x4978e1  boost::asio::detail::task_io_service::run()
    @           0x48ff9e  main
    @     0x7f8c7c9d8830  __libc_start_main
    @           0x4947d1  (unknown)
</pre>

**Comment by ericl** [comment]
I tested and this fixes the issue: https://github.com/ray-project/ray/pull/3525/files
