### ISSUE TITLE
[core][state] Add bundles to node information in State API placement groups

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#35209]
### What happened + What you expected to happen

We could add the bundle id to node mapping as this PR https://github.com/ray-project/ray/pull/35122

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

**Comment by larrylian** [comment]
https://github.com/ray-project/ray/pull/35122  The PR has merged. Has this PR met your requirements already？

**Comment by rickyyx** [comment]
I think it would require extra work in state API to also surface the info as #35122 did.

**Comment by rickyyx** [comment]
Oh, no, I think what I mean is to add the info in the output of `ray list nodes` CLI.

**Comment by larrylian** [comment]
@rickyyx 
The node id information where the bundles are located is already included in the return information of the "ray list --detail placement-groups" command.
![image](https://github.com/ray-project/ray/assets/11072802/0dda3e3b-2a58-4411-8dcd-aad731a796f5)

**Comment by rickyyx** [comment]
Oh nice, didn't know that. This is great! We could close this now?
