### ISSUE TITLE
[Train] LightningTrainer supports `pl.Trainer.test()` for batch inference example

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#35225]
### Description

Currently, the users have to set aside a dedicated GPU solely for the `pl.Trainer.test` method because the `LightningTrainer` uses autoscaling for the training process, while has no support for inference. 

- The users still want to leverage the native pytorch lightning interfaces like `on_test_batch()`, `on_test_epoch_end()`.
- It's not convenient for them to create a batch predictor to do batch inference if they are not highly relied on Ray Data.

**Comment by richardliaw** [comment]
Let's get the next level of detail - what would the API look like exactly?

**Comment by woshiyyya** [comment]
My preliminary thoughts are: 
- we can provide the same interface as the `ptl.Trainer` does:
```python
# lightning's API
Trainer.test(model=None, dataloaders=None, ckpt_path=None, verbose=True, datamodule=None)
Trainer.predict(model=None, dataloaders=None, datamodule=None, return_predictions=None, ckpt_path=None)

# Our API
LightningTrainer.test(**kwargs)
LightningTrainer.predict(**kwargs)
```

- Instead of kicking off a new trial like in `Trainer.fit()`, we can start the distributed process group in `test()` and `predict()` with the tools like: 
https://github.com/ray-project/ray/blob/805e6ce456fd54096cb7665a4a9687955d84ad71/python/ray/air/util/torch_dist.py#L95


The benefits are:
- Easy to use: 
  - Users don't have to create new configs and new objects. Just reuse their `LightningTrainer`.
  - Same interface, zero migration cost.
- Support distributed inference over sharded model (e.g. FSDP, deepspeed)

Still some concerns arounds integrating with Ray Data:
  - How to get `session` outside a trial, so that we can get dataset_shards?
  - For `predict()`, how to aggregate the outputs?

**Comment by richardliaw** [comment]
What are the downsides of using Ray Data for batch prediction?

Assume we have something like:

```python
ds = ray.data.from_ptl_datamodule(datamodule)
predictor = trainer.to_predictor()
ds.map_predictor(predictor)
```

**Comment by woshiyyya** [comment]
I think using Ray Data for batch prediction is the right direction. The only downside is the current design of LightningPredictor.

Firstly, `LightningPredictor` basically is equivalent to TorchPredictor. It treats LightningModule as a torch model, and returns the output of `self.forward()`. It doesn't utilize important lightning APIs like (`predict_step()`, `on_predict_batch_end()`, `on_predict_epoch_end()`) for post processing. 

**Why these post-processing APIs are important?**
From my point of view, aggregating and processing tensor outputs in PyTorch Tensor format is way more convenient than dealing with pandas/numpy array. As you can imagine, rewriting that post-processing code again with weird pandas operations would not be pleasant.  Also, it will reduce the migration cost.

Secondly, `LightningPredictor` requires the model fits into a single GPU. Then all the large-model prediction won't work, since you have to shard model params across multiple workers.
