### ISSUE TITLE
Frequent tune_server_test failure. 

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#3522]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

In recent PR and merged commits, there are many tune_server_test.py failure.
```
python/ray/tune/test/tune_server_test.py::TuneServerSuite::testStopTrial /Users/travis/.travis/job_stages: line 104: 11134 Abort trap: 6           python -m pytest -v --durations=10 python/ray/tune/test/tune_server_test.py
The command "python -m pytest -v --durations=10 python/ray/tune/test/tune_server_test.py" exited with 134.
```

Example:
https://travis-ci.com/ray-project/ray/jobs/164550194
https://travis-ci.com/ray-project/ray/jobs/164589013
https://travis-ci.com/ray-project/ray/jobs/164531599
https://travis-ci.com/ray-project/ray/jobs/164137927
https://travis-ci.com/ray-project/ray/jobs/164135154

**Comment by richardliaw** [comment]
has this occurred recently?

**Comment by guoyuhong** [comment]
It looks like this test failure is gone in recent Travis tests. I will close this issue. Thanks, everyone!
