### ISSUE TITLE
[ml][release-tests] xgboost_train_gpu.aws, many other rllib release tests failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35237]
### What happened + What you expected to happen

xgboost_train_gpu.aws, many other rllib release tests failed: https://buildkite.com/ray-project/release-tests-branch/builds/1644#01880462-441f-468a-b019-c020527b1837

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1644#01880462-441f-468a-b019-c020527b1837

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by can-anyscale** [comment]
Multiple bisect points to this as the blame PR: https://github.com/ray-project/ray/commit/03774748d1a8e7545bf17b5e47619850794d949c. Please review and revert if it makes sense, Thankkks

**Comment by can-anyscale** [comment]
CC: @krfricke

**Comment by matthewdeng** [comment]
The PR looks unrelated, the job did not even start. Looks related to the release of `urllib3` version 2.0?

**Comment by can-anyscale** [comment]
@matthewdeng that makes sense, somehow it only relates to some of the ml/rllib tests

**Comment by can-anyscale** [comment]
Fix now \o/
