### ISSUE TITLE
More descriptive errors for malformed spaces in gym environments

### ISSUE THREAD

**Issue by rueberger** [ray-project/ray#3527]
I've been trying to get `rllib` working with a custom `gym` environment which had some problems with it. The errors I've been getting have been a bit mysterious. I think it should be relatively easy to throw more descriptive exceptions, and I would be interested in taking a pass at it. 

In particular, I would like to throw more descriptive errors for at least the following cases:

- Not all elements of a compound space (Tuple/Dict) are of type `gym.Space`
- Observations returned by `env.step` are not elements of the declared observation space

What do you think? Would this be difficult to integrate?

**Comment by rueberger** [comment]
Would also be nice to check that `env.reset` returns an observation.  

Currently you get an  `AttributeError: 'NoneType' object has no attribute 'items'` at `rllib.models.preprocessors` L169.

**Comment by ericl** [comment]
@rueberger this would be great to have.
