### ISSUE TITLE
Make sure task lease keys don't get evicted from Redis.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3531]
There is no need to evict task lease keys because these naturally expire anyway. Eviction of a task lease key can pretty easily lead to spurious reconstruction.

One (approximate) way to do this would be to put an upper bound on the task lease renewals (e.g., several minutes), so that they get touched frequently enough that LRU eviction doesn't affect them.

A more reliable option would be to simply not perform LRU eviction on the task lease keys (e.g., by moving them to a separate collection of Redis shards).

@stephanie-wang @ericl

**Comment by raulchen** [comment]
Speaking of capping the task lease renewal timeout, I think we should do that regardless of this issue, otherwise task reconstruction could be super slow if the task is a long-running task.

**Comment by robertnishihara** [comment]
This is likely to be fixed by #3707 although it is not guaranteed.

**Comment by robertnishihara** [comment]
No longer relevant.
