### ISSUE TITLE
[docs] new CSAT widget design

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#35336]
### Description

The Crisp integration for Kapa (https://github.com/ray-project/ray/pull/35125) will be in the lower right hand corner of the docs pages where the CSAT (thumbs up, thumbs down) widget is currently. We should keep the CSAT because it is giving us valuable signal, but the UI can be improved. @simran has a proposal to move it to the lower left hand side of each doc page with a new design. 

@peytondmurray will also add the GA4 tag so we can see the data in GA4.

### Link

This change would affect every page.

**Comment by simran-2797** [comment]
[link to the new design](https://www.figma.com/file/y0v6uCrZJsTK2zpMaudeEP/Ray-landing-page?type=design&node-id=813%3A6788&t=u8Sdxn1UAzoFgS73-1)
