### ISSUE TITLE
[release-test] dask_on_ray_1tb_sort is failing

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#35363]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_1ehareaa8hi99c6rpa9xdl53ht

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by can-anyscale** [comment]
@scv119 : this test is now passing on master; can you help reconfirm and close the issue if that's true

**Comment by scv119** [comment]
[ERROR 2023-05-12 03:27:27,054] anyscale_job_wrapper.py: 290  Timed out. Time taken: 7200.075921197

**Comment by scv119** [comment]
@can-anyscale unlikely a release blocker.

**Comment by jjyao** [comment]
Consistently passing now.
