### ISSUE TITLE
component failures test fails on test_actor_creation_node_failure

### ISSUE THREAD

**Issue by atumanov** [ray-project/ray#3537]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac xcode7
- **Ray installed from (source or binary)**: master
- **Ray version**: upstream/master
- **Python version**: py27
- **Exact command to reproduce**:
`python -m pytest -v --durations=10 test/component_failures_test.py`

### Describe the problem
unit test failure on test/component_failures_test.py::test_actor_creation_node_failure

### Source code / logs
```
test/component_failures_test.py::test_actor_creation_node_failure /Users/travis/.travis/job_stages: line 104: 15520 Abort trap: 6           python -m pytest -v --durations=10 test/component_failures_test.py

travis_time:end:0c607c80:start=1544658534685472000,finish=1544658686671340000,duration=151985868000
[0K[31;1mThe command "python -m pytest -v --durations=10 test/component_failures_test.py" exited with 134.[0m
```

**Comment by zhe-thoughts** [comment]
Closing as most likely it's not an issue anymore
