### ISSUE TITLE
Issue in ray.train.Trainer module in nightly build version '3.0.0.dev0'

### ISSUE THREAD

**Issue by quamernasim** [ray-project/ray#35379]
### What happened + What you expected to happen

Hi Guys,

About a year ago, I installed the nightly build version '3.0.0.dev0' of Ray. And since then I've been using ray.train.Trainer module to do all of my hyperparameter tuning. Shown below

```
trainer = Trainer("torch", num_workers=args.num_workers, use_gpu=True, resources_per_worker={"CPU": 6, "GPU": 1})

config = {
     # model parameters, leaving this blank for now
}

reporter = CLIReporter(metric_columns=["loss", "class_error", "training_iteration"])

trainable = trainer.to_tune_trainable(train_ray_tuner)
result = tune.run(trainable, config=config, num_samples=args.num_samples, local_dir=pjoin(args.local_dir, config['output_dir']), 
                                 keep_checkpoints_num=1, progress_reporter=reporter,log_to_file = True)# verbose = 0)

best_trial = result.get_best_trial("class_error", "min")
```

Earlier this week, when I wanted to deploy the model on VM, I installed the nightly build of ray version '3.0.0.dev0' using the following command `pip install -U "ray[tune] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl"`.

I checked the Ray version, and it was what I wanted ('3.0.0.dev0')

But this version of the ray is giving an error saying.

ImportError cannot import the name 'Trainer' from'ray.train'

Can someone suggest why this is happening and what is the solution? When I have the same version, why would it give an error?
Or can someone provide me with a commit hash that has got Trainer? so that I can use that to install it

### Versions / Dependencies

python version: 3.8.12
ray version: 3.0.0.dev0
os: Ubuntu 20.04

### Reproduction script

install this 

`pip install -U "ray[tune] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl"`

And try this script
```
from ray.train import Trainer
trainer = Trainer("torch", num_workers=args.num_workers, use_gpu=True, resources_per_worker={"CPU": 6, "GPU": 1})

config = {
     # model parameters, leaving this blank for now
}

reporter = CLIReporter(metric_columns=["loss", "class_error", "training_iteration"])

trainable = trainer.to_tune_trainable(train_ray_tuner)
result = tune.run(trainable, config=config, num_samples=args.num_samples, local_dir=pjoin(args.local_dir, config['output_dir']), 
                                 keep_checkpoints_num=1, progress_reporter=reporter,log_to_file = True)# verbose = 0)

best_trial = result.get_best_trial("class_error", "min")
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
Hi @quamernasim,

Which version of Ray is the script you're running from? The `Trainer` API has been deprecated for a few releases now.

Take a look at this guide to convert Pytorch code to the new AIR `TorchTrainer` API: [link to the guide](https://docs.ray.io/en/latest/ray-air/examples/convert_existing_pytorch_code_to_ray_air.html)

**Comment by gjoliver** [comment]
3.0.0.dev0 is a floating version number that means the latest master branch.
so every time you download a wheel that is version 3.0.0.dev0, you are getting a different version of wheel depending on the state of the Ray repo at that moment.
the API you are using has long been deprecated. please update your code.
thanks and sorry about the confusion.
