### ISSUE TITLE
[docs] Welcome Landing Page card is not clickable

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#35397]
### Description

The "Install Ray" card is not clickable, which is not consistent with the other two cards. I'm also wondering, from a UX perspective, do we want to have both the card and CTA be clickable? Whatever we decide, let's make them consistent.

### Link

https://docs.ray.io/en/latest/index.html

**Comment by simran-2797** [comment]
@angelinalg : PR for the fix - https://github.com/ray-project/ray/pull/35783
