### ISSUE TITLE
[rllib] Port pymarl/starcraft multi-agent examples and algorithms

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3540]
### Describe the problem

We should port the envs from https://github.com/oxwhirl/pymarl_alpha and also some of the algorithms as examples (probably QMix).

It looks like the code structure already operates on batches so it shouldn't be too hard to adapt to the policy graph interface.

**Comment by richardliaw** [comment]
Closed with #3542 and #3548.

cc @samvelyan and @tabzraz
