### ISSUE TITLE
[Core] abnormal memory increase in head node gcs

### ISSUE THREAD

**Issue by AndreKuu** [ray-project/ray#35429]
I am using ray job to do some batch data processing. I found abnormal memory increase in head node and the memory used by gcs server. Continuously growing by 8 GB per hour util OOM and the job actually hangs.

This situation didn’t happen from the beginning of job or in some small jobs. This only happened when job ran for more than 6 hours and more than 50000 tasks.

Other related information:

Using kubernetes manage head node and worker nodes;
1. The number of worker nodes is 400.
2. Only one job is running when this situation happened.
3. Both CPU and GPU tasks exist.
4. Worker nodes go online and offline a few times because of OOM and disk pressure.
5. log_to_driver == False

When the usage of gcs memory in head node began to increase abnormally, looks like no more task agent created any more. It looks like this job also hangs.
Any ideas?

### Versions / Dependencies

version:  ray 2.0.1 

### Reproduction script

-

### Issue Severity

None

**Comment by rkooo567** [comment]
Can you confirm if the same issue happens when you use the latest Ray? (2.4).

**Comment by AndreKuu** [comment]
您的邮件已收到，祝好。------KuU

**Comment by rkooo567** [comment]
cc @iycheng can you double check if this is the same issue as what you investigating?

**Comment by cadedaniel** [comment]
cc @vitsai find a similar release test and see if there's a similar pattern (memory leak in gcs)

**Comment by AndreKuu** [comment]
> Can you confirm if the same issue happens when you use the latest Ray? (2.4).

Ok~ I have this plan in mind to upgrade the version of ray. I will take more information and logs of gcs back after upgrade.

**Comment by vitsai** [comment]
Running 10k tasks every 30 minutes on 400 nodes for 6 hours showed a potential raylet memory leak similar to what @iycheng is investigating. Removing release blocker tag and changing to P1 for now.

**Comment by vitsai** [comment]
Seems to have been tracked in #35632

**Comment by scv119** [comment]
potentially fixed by https://github.com/ray-project/ray/pull/35673

**Comment by rkooo567** [comment]
> Running 10k tasks every 30 minutes on 400 nodes for 6 hours showed a potential raylet memory leak similar to what @iycheng is investigating.

actually I am a bit confused. @vitsai do you see the leak or not? Also did you run the workload against the master? 

If it is the same issue as @iycheng and if you run against the master, it shouldn't show up?

**Comment by vitsai** [comment]
Yes, I verified that the issue was fixed by nightly but was still present in 2.4. Let's reopen if this recurs after 2.5

**Comment by AndreKuu** [comment]
> Yes, I verified that the issue was fixed by nightly but was still present in 2.4. Let's reopen if this recurs after 2.5

yes . I used ray 2.4.0 reproduced this problem.

**Comment by vitsai** [comment]
A fix has gone into 2.5, which we should be releasing this week.

**Comment by AndreKuu** [comment]
> A fix has gone into 2.5, which we should be releasing this week.

Yes, i already noticed this message. Thanks a lot. I uploaded this memory increasing unexceptly with ray 2.4.0.  If there is attention to help and ensure the repair of the problem. https://github.com/AndreKuu/ray_logs/blob/master/gcs_server.out

**Comment by AndreKuu** [comment]
The follow-up of this issue includes whether version 2.5.0 will encounter the same issue in the discussion https://discuss.ray.io/t/issue-abnormal-memory-increase-in-head-node-gcs/10691
