### ISSUE TITLE
Question: PPO act deterministically?

### ISSUE THREAD

**Issue by MoggeM** [ray-project/ray#3543]
Hi,

I am wondering how I get a trained PPO to act deterministically?

Is it enough to set the config option "free_log_std" to True after you restore the agent or do I have to do something else?

**Comment by MoggeM** [comment]
To clarify, I am trying to train a discrete PPO agent and I need to evaluate how well it performs in an operative environment. 

So far I have found that it samples the actions from the ActionDistribution by tf.multinomial but I cant find how to return the inputs without sampling

**Comment by ericl** [comment]
For evaluation you can try setting the std to zero in the action distribution code here: https://github.com/ray-project/ray/blob/master/python/ray/rllib/models/action_dist.py#L134
