### ISSUE TITLE
[CI] `linux://doc:source/serve/doc_code/app_builder` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#35449]
<img width="518" alt="Screen Shot 2023-05-17 at 11 16 27 AM" src="https://github.com/ray-project/ray/assets/950914/e1ea4921-8388-4998-a28a-b738f4e6bc93">

- 1bd30c32974f0827c3a42bf328c95c719f5e74b3 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3960#01882a58-d08c-4966-abfd-2498f8b4e568)
- cde7109a244ce40ed15a7259669b55301a6ace74 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3959#01882a1a-6339-4baf-98b5-ffb556e63e03)
- 119e12bb5d1b009f791d7cc4d52bb790196640c7 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3958#018828e0-f327-4518-bb6c-6627c8c2d6f7)
- 9cd509723494eb861c77a989cfa880ec384d31c6 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3957#018827af-c006-4703-9936-ecff2ddcafcf)
- a9f333a9068b37951b2c2d827f1e9f0c39123581 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3956#0188279e-14b0-4942-823d-c0f0dfbb91b8)
- 8b264df18bbdbf96c79f94ac22b528aaadc6efdd FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3953#01882725-581f-440d-83c0-9075b5862b7c)
- f31d70e6be5db7432e1f82c87bde2c3b410f9552 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3952#01882717-f706-4355-9c81-f6c76edc634d)
- 7e61d0bafc61f365f456d4147e50820c0b74743a FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3951#018826e6-67b9-435f-8a7b-f029a24e8971)
- ea6b926605566f3c6d95f3849771ad048409adde FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3950#018826d0-2b9f-4876-9272-399166f3bc8a)
- fa077fbcbd4c6331d5860e41c5503c84dcb5c1f6 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3949#018826c4-2f26-42b0-a419-82e6d501b4e2)
- 736060e7344cbfcb5105541baa6e6da1fe72857a FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3948#018826b2-ccfd-42ac-9210-2c868adf42ad)
- 53c638fd1b977e0ca5f23317792b880eca6aa8da FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3947#018826aa-8dfd-4b72-8a57-d1c38a5647aa)
- e19ab035679926fd95e19138707974ca3b09a4de FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3946#018826a5-0f7b-4069-8a8b-bf61eab18bb7)
- 1ccd59a2a5b5a2235f5f98adf5f0bba398271bbc FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3945#0188266c-9927-427d-844e-830286d4e21f)
- 8c2e850d8d5f4554afe6a2397ff5f702489db023 FAILED [Buildkite :book: Doc tests and examples (excluding Ray AIR examples)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3944#01882660-98ae-4467-a144-5b6f87f610d8)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc:source/serve/doc_code/app_builder-END
....

**Comment by sihanwang41** [comment]
https://github.com/ray-project/ray/pull/35515#event-9284308562
