### ISSUE TITLE
[batch predictor] BatchPredictor error with keep_columns arg

### ISSUE THREAD

**Issue by vsriram23** [ray-project/ray#35441]
### What happened + What you expected to happen

When I try to do inference of a model using BatchPredictor with preprocessor it throws an error if I use keep_columns arg like this:

ValueError: The `fn` you passed to `map_batches` returned a `dict`. `map_batches` expects all `dict` values to be of type `numpy.ndarray`, but the value corresponding to key 'names' is of type <class 'pandas.core.series.Series'>. To fix this issue, convert the <class 'pandas.core.series.Series'> to a `numpy.ndarray`.

Without keep_columns arg there is no error but I need it to save additional info along with predictions.

### Versions / Dependencies

Ray 2.3
Python 3.6

### Reproduction script

`import ray
from ray.train.torch import TorchCheckpoint, TorchPredictor
from ray.train.batch_predictor import BatchPredictor
from ray.data.preprocessors import BatchMapper

def model_preprocess(batch):
    for i,b in enumerate(batch['rois']):
        batch['rois'][i]=torch.reshape(torch.tensor(b),[3,256,256]).float()
    print(batch)
    return batch

test_ds = ray.data.read_parquet(glob.glob(os.path.join(data_path,'*')),tensor_column_schema={"rois": (np.float64, (256, 256, 3))},columns=["rois","names"])
prep = BatchMapper(model_preprocess,batch_format="pandas")

# Create model
ckpt = TorchCheckpoint(ckpt_path)
model_infer = ckpt.from_model(model,preprocessor=prep)

# do prediction
batch_predictor = BatchPredictor(model_infer, TorchPredictor)

batch_size = 1024*8
pipeline = batch_predictor.predict_pipelined(test_ds, blocks_per_window=32, feature_columns=["rois"],keep_columns=("names"),batch_size=batch_size, num_gpus_per_worker=1, min_scoring_workers=8)

for result_batch in pipeline.iter_batches(batch_size=batch_size):
    print("Pipeline result", result_batch)`

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Hey @vsriram23, unfortunately I am not able to reproduce using dummy data on both Ray 2.3 or 2.4.

Do you have a fully reproducible example?

**Comment by bveeramani** [comment]
Closing because `BatchPredictor` is deprecated
