### ISSUE TITLE
[CI] `bk://:book: Lint` is failing/flaky on master.

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#35454]
- ae5e1c7acca1073f6e16d7428e46f46e2535d2e8 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3961#01882ac6-3b31-4971-a30c-13e8590af71f)
- 1bd30c32974f0827c3a42bf328c95c719f5e74b3 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3960#01882a4d-847a-4df1-84ec-ab5ab5a9a039)
- 1ccd59a2a5b5a2235f5f98adf5f0bba398271bbc FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3945#01882664-ebcd-4700-a434-4649de9af79d)
- 681ce0d9fe55df16ee293cfb15544c5f775f692a FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3941#0188263f-c072-45f2-9a6b-0b5f6cb08b4a)
- 42a8d1489b37243f203120899a23d919dc85bf2a FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3940#01882556-04c9-4d13-832e-7408d07aef85)
- a86254773609e10d38183b173d53f6b3279d3485 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3939#01882540-a904-47cf-85f1-fa6450f1a15e)
- 37fa98f339f0ee21ce80147511f559a6a1ecb15e FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3931#018822c2-9d05-492f-ba88-6e9f907ffae7)
- 5ccbb7c934489843eb664d93ca6534cddeabc750 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3930#018822bc-1fe2-4726-8bd2-053388974989)
- 35cb004987fde69de7fa3c5a470c0dad86d1ffd2 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3929#018822b7-5184-457c-8b23-cebacd9f3e91)
- 496024df480c74e83e31363155341605aa28b0bf FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3928#018822b6-26a6-4c14-8e5e-32c9463bc7c9)
- 5197da2c388a731c05b54b6228fb9800b96982a5 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3927#01882266-8666-4c6d-bfb1-07884e49810a)
- a21713ef373d00aab6647e0902f264f72c73dc52 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3926#01882224-bc53-4aff-b6e0-b6b4d6e561c2)
- 152e06dd6edab05790decfa225ed1e46b163416e FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3925#01882221-5905-442f-92e5-a0b530badd7a)
- 79784c5b4d623641b1e75e779d149678d7395512 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3924#01882211-123c-42ac-9057-5dcf7afd410b)
- 01f932cbf29205e8c60a2bce9f0fde4c4e9e83ce FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3923#018821ed-6bd5-43f7-b884-2e16c879c6ae)
- 2e08421413c4150a7f7af77b53cf36ea9f505978 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3922#018821e1-3425-45d5-805c-23254201c987)
- adddc2bc0c7b2a2c6849da87d03e0b8e2002ed32 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3921#018821dc-10b5-4d06-8e54-af12b03004bb)
- 6b7e4125f132c3eb1b6f74ac8fe5312afe725f46 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3920#018821c0-6109-4f85-9d7c-762c4d7485ca)
- 84833a424e1ebb2f439b02962809e5da33bbe60d FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3919#01882191-f53b-484e-a1af-9bad0498a319)
- c8fc8f636e3f23b6062ecfe182a729449f56fe62 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3918#0188217d-6484-444a-881b-68060a6c224c)
- 5a5155c7f49f720a2a548812057724a16d5d564f FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3917#0188217d-7378-445c-b0b1-6bee3a924fd2)
- 3ca86325d0a989c1fa059ff91d2d1edfb8d8f683 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3916#0188213e-414e-4261-8238-d05ab1c76ad9)
- c7337ca1d790b7577d9d1c3472cd3ccdebbfba81 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3915#01882107-c809-4b12-b051-d189647ed687)
- 20ee1647c887d98d3d0ce167180f14bf9cda111c FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3914#01882107-3706-4fde-99e5-c590ec4a1f36)
- 27f47134f1ace3bf1a7d827c9ef0a5a571b2e9f8 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3913#01882107-783c-49f5-8b1f-4caf0dede6dc)
- fdcc58b98d0345ec9cae67df6eb00de1438901e2 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3912#01882106-3c4d-4feb-a403-b013e29ba8a1)
- e08ef634207959892b2475efd1050a876d43e7a8 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3911#01882087-e938-4349-86a3-7bfb99041613)
- a0e318ba784d4cd5a53ed0e94bb21f299e2bdd5a FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3910#01882078-4876-444a-9487-50c34b58943f)
- 21e9d38320fd392fa34ce60b73277d367ddf5386 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3909#01882021-1a1b-4edf-b426-78aaf2d3c52a)
- 2dbe747ab6c5ce29cdc5eefb8287d496cca7990c FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3908#01881fa2-38d0-4f38-9e30-f6f2af0f6208)
- 5d0b15e1619425d02ccbccaf93d716bb7392a7e6 FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3907#01881f49-b1f0-4939-85c7-7a1115b852e7)
- 6088de3274ad3eac275a64e3ffceefb8828d5b8d FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3906#01881e94-185e-48d8-9bb4-fb2ab596ef9d)
- 3d977b8b6e65058e509d3bf25a9105b5a09a053c FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3905#01881de1-12c3-47bd-8278-d96120091c8c)
- ecd9996777d5c3751b100126fe4953f0b320f00d FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3904#01881dda-4286-4205-95a8-6c80bb7f7935)
- a38ed6e4e2911e286dca191235fb67232b66a54c FAILED [:book: Lint](https://buildkite.com/ray-project/oss-ci-build-branch/builds/3903#01881c4d-cab7-4c91-9e53-e352df6a9149)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:book: Lint-END
....

**Comment by cadedaniel** [comment]
Looks caused by https://github.com/ray-project/ray/pull/35395

<img width="255" alt="Screen Shot 2023-05-17 at 11 26 49 AM" src="https://github.com/ray-project/ray/assets/950914/74218164-6bfb-4f5d-8730-a30e7f57f625">

**Comment by ollie-iterators** [comment]
In release/ray_release/byod/byod.Dockerfile line 1:
--
  | # syntax=docker/dockerfile:1.3-labs
  | ^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.

It was mentioned in https://github.com/ray-project/ray/pull/35484 that the solution is to add a newline to the dockerfile
