### ISSUE TITLE
[release-tests] stress_test_state_api_scale.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35460]
### What happened + What you expected to happen

stress_test_state_api_scale.aws has been failing and is blocking 2.5 release. Please help review and resolve asap. 

I kicked off a bisect job here: https://buildkite.com/ray-project/release-tests-bisect/builds/158#_

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/1658#01882a6d-ba78-4de5-bc7d-ace4c9863af8

### Issue Severity

High: It blocks me from completing my task.

**Comment by can-anyscale** [comment]
Stack trace:



```
Traceback (most recent call last):
--
  | File "stress_tests/test_state_api_scale.py", line 435, in <module>
  | test()
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
  | return self.main(*args, **kwargs)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1055, in main
  | rv = self.invoke(ctx)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/click/core.py", line 760, in invoke
  | return __callback(*args, **kwargs)
  | File "stress_tests/test_state_api_scale.py", line 384, in test
  | test_many_actors(num_actors=n)
  | File "stress_tests/test_state_api_scale.py", line 171, in test_many_actors
  | limit=STATE_LIST_LIMIT,
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/state_api_test_utils.py", line 94, in invoke_state_api
  | ), f"Calling {state_api_fn.__name__}({kwargs}) failed with {repr(e)}."
  | AssertionError: Calling list_actors({'filters': [('state', '=', 'ALIVE'), ('class_name', '=', 'test_many_actors.<locals>.TestActor')], 'limit': 1000000, 'timeout': 600, 'raise_on_missing_output': False}) failed with AssertionError('Calling State API failed. len(res)=(280): None').
```

**Comment by can-anyscale** [comment]
Bisect blamed https://github.com/ray-project/ray/commit/9cd509723494eb861c77a989cfa880ec384d31c6 which is already reverted in master

**Comment by rickyyx** [comment]
Waiting for the recent master run: https://buildkite.com/ray-project/release-tests-branch/builds/1661#01882e29-dec0-41dd-ab05-c6837bb5d77e

I took a look at the failure - looks like it's not related to state API itself. If the bisect blame makes sense, the ^ run should be passing.

**Comment by rickyyx** [comment]
It's passing in the branch: https://buildkite.com/ray-project/release-tests-branch/builds/1663#_

I am going to rewrite the test logic actually - i think the current test has sub-optimal behaviour.

**Comment by rkooo567** [comment]
@rickyyx has this been handled? I am seeing the same test timed out https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_11e3xukjjaqtvqjq6qwrm4w3qk

<img width="1484" alt="Screen Shot 2023-06-01 at 6 28 00 AM" src="https://github.com/ray-project/ray/assets/18510752/5684f442-d2be-41c8-957a-21b0e77ea6a9">

**Comment by can-anyscale** [comment]
This test failed again on the release branch, as well as master: https://buildkite.com/ray-project/release-tests-branch/builds/1737#01887793-b405-482c-80bd-53b8155ebb0b

**Comment by can-anyscale** [comment]
Confirm that https://github.com/ray-project/ray/commit/5180f0f8f0dd70de18295d7a8ad7e391ccd1c29d broke this test (bisect job: https://buildkite.com/ray-project/release-tests-bisect/builds/203#_). CC: @rickyyx
