### ISSUE TITLE
[Ray Core] Make `pip install ray` work without Python grpcio dependency

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#35472]
### Description

The Python grpc dependency is causing a number of problems:

- It causes problems to install Ray on M1 macs
- It has often had bugs that caused problems in the past (see the yanking history in https://pypi.org/project/grpcio/#history)
- It causes dependency problems with user libraries and other dependencies (see https://github.com/ray-project/ray/issues?q=is%3Aissue+grpcio)
- It is a fairly heavy dependency

Only depending on grpc C++ has the added benefit that we can statically link in a particular version of gRPC for every Ray version, which makes debugging much easier (vs. having to support a full matrix of versions).

Therefore it would be desirable to remove it as a dependency from Ray. This issue is about the first step of removing the dependency from Ray Core, i.e. make `pip install ray` not install the grpcio package. The grpcio package will still be installed for `pip install "ray[default]"` and other full packages (e.g. runtime_environments and the dashboard will still need the dependency). However once we remove grpcio from Ray Core / user code, we can upgrade grpc to a newer version which provides native M1 mac support.

We have done a number of steps to support this:

- https://github.com/ray-project/ray/pull/33769
- https://github.com/ray-project/ray/pull/34393
- https://github.com/ray-project/ray/pull/34706
- https://github.com/ray-project/ray/pull/35094

After this we should remove remaining imports etc., see also https://github.com/ray-project/ray/compare/master...pcmoritz:ray-1:remove-more-grpc.

**Comment by xieus** [comment]
Talked to @scv119. We will start looking into this item right after R2.5.

**Comment by pcmoritz** [comment]
There is good progress on this, but it is unlikely for https://github.com/ray-project/ray/pull/36917 to land before the 2.6 branch cut and that's the last big chunk of work required for this -- so we will need to postpone this to 2.7.

**Comment by pcmoritz** [comment]
Last piece of work for the minimal `pip install ray` installation is here: https://github.com/ray-project/ray/pull/38243 🥳 Thanks a lot to @rynewang for all his efforts on this :)

**Comment by rkooo567** [comment]
IIUC, this is finished & merged
