### ISSUE TITLE
[serve] wrong bash command in stable diffusion example

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#35470]
### Description

![image](https://github.com/ray-project/ray/assets/9677264/cf913bca-3908-41b9-8ea1-9725c3a4b573)

**Comment by richardliaw** [comment]
btw, next time I recommend just editing in line and posting the PR -- it should be much faster.

**Comment by sihanwang41** [comment]
https://github.com/ray-project/ray/pull/34426
