### ISSUE TITLE
[Core|RLlib|] Maybe you called ray.init twice by accident?

### ISSUE THREAD

**Issue by pepi99** [ray-project/ray#35495]
### What happened + What you expected to happen

I got this error:

RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

I only call ray.init() once around my all of my classes/scripts.

### Versions / Dependencies

ray 2.4.0
MacOS
Python 3.7

### Reproduction script

from environments.multi_action_order_environment import MultiActionOrderEnvironment
from networks.custom_network import CustomModel

import ray
from ray.tune.registry import register_env
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.models import ModelCatalog

config = {config code here}
ray.init()
trainer = PPOTrainer(config=config)

# training code

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by pepi99** [comment]
Yup, I get that. However, I am calling it only once across all of my files.

**Comment by pepi99** [comment]
Solution: remove ray.init() from my main script. I suppose it is now called somewhere internally in Ray so not to bother user with that command.

**Comment by pepi99** [comment]
Please someone confirm that this is the case and close the issue with the confirmation.

**Comment by Rohan138** [comment]
What version of ray are you on? I could not reproduce it on the current master:

```
import ray
from ray.tune.registry import register_env
from ray.rllib.algorithms.ppo import PPO as PPOTrainer
from ray.rllib.models import ModelCatalog

ray.init()
```

**Comment by ArturNiederfahrenhorst** [comment]
I canot not reproduce on master either.
Generally, you don't need to call ray.init() here because instantiating a Trainer (nowadays called `Agorithm`) instantiates a new ray cluster or connects to one if already present.
