### ISSUE TITLE
[Core] Import in Colab produces error

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#35490]
### What happened + What you expected to happen

Went to colab
Created a [notebook](https://colab.research.google.com/drive/1ig9MkL6HDGlOLArugfeKHLpFllSptixC#scrollTo=FvmJR8W8VbFM)
Installed 2.5 wheels from latest build
Imported and initialized ray -> AttributeError

<img width="1014" alt="Screenshot 2023-05-17 at 22 21 53" src="https://github.com/ray-project/ray/assets/9356806/30a52159-5c7e-4a6c-842a-5b18c0052caf">

### Versions / Dependencies

2.5.0 branch

### Reproduction script

.

### Issue Severity

None

**Comment by scottsun94** [comment]
@peytondmurray We should handle this issue when we try to merge this feature https://github.com/ray-project/ray/pull/34815 in the future

**Comment by peytondmurray** [comment]
Yep, this should get fixed to emit a warning here, because ipywidgets is outdated, resulting in this error.

**Comment by scottsun94** [comment]
> Yep, this should get fixed to emit a warning here, because ipywidgets is outdated, resulting in this error.

If possible, can we emit "INFO" level message instead? This feature should be nice-to-have for now. We don't need to warn users to upgrade. It should just work as usual + a little message that recommends users to upgrade for better output.

**Comment by can-anyscale** [comment]
Can we assign an owner for this @ArturNiederfahrenhorst , thank you
