### ISSUE TITLE
PPO rollout.collect_samples() throws away up to half the samples

### ISSUE THREAD

**Issue by opherlieber** [ray-project/ray#3549]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**:  0.6.0
- **Python version**: 3.6.7
- **Exact command to reproduce**: rllib train --run PPO --env BreakoutNoFrameskip-v4 --config '{"num_workers":16,"num_envs_per_worker":1,"sample_batch_size":128,"train_batch_size":2048,"sgd_minibatch_size":512,"num_sgd_iter":4}'
(Plus added debug prints in PolicyEvaluator.sample() to count how many actual steps were sampled by all evaluators. Overall they sampled 2x more steps than the timesteps reported by each training iteration)

### Describe the problem

It looks like collect_samples() in ppo/rollout.py never gets/waits-on the last sample() request of each agent, essentially throwing away those samples (or they get stuck in the DB?), or maybe I am missing something in how ray handles this.
In the worst case (When train_batch_size=sample_batch_size*num_workers) this seems to throw away half the samples.

**Comment by ericl** [comment]
The samples are just lost in that case. I was looking at how to make this more intuitive earlier since I ran into a related issue with even more waste. Can you try this PR out? https://github.com/ray-project/ray/pull/3552

Another workaround is to make sure the sample batch size is sufficiently small (e.g., 100) compared to the train batch size, so that the waste proportion is also small.

**Comment by opherlieber** [comment]
Thanks I'll have a look, though that implementation would essentially sample exactly 1 time per remote evaluator (for the case where 'train_batch_size=sample_batch_size*num_workers*num_envs_per_worker').
What about cases where some of the evaluators generate samples faster or have occasional delays? 
Would it make sense to retain the 'agent_dict' for the next train iteration, at least if 'sample_async' is enabled, or maybe with a separate flag?

**Comment by ericl** [comment]
I thought about adding that optimization, but this use case might be better by served by proper async PPO, which is hopefully coming soon.

You can also set `straggler_mitigation=True` and `train_batch_size = K * sample_batch_size * num_workers * num_envs_per_worker` which bounds the waste to ~`1 / K`.

**Comment by opherlieber** [comment]
Thanks, I will look into large K option as well, although a large K would likely cause the AsyncSampler queue to fill up in my use-case and stall the sampling, even with the sampling being slower than the training (I think it's limited to queue size 5 at the moment)
But proper async PPO sounds like a good solution for my use-case, glad to hear it's in the works, thank you.
