### ISSUE TITLE
I think that the example of rl-pong is not trained in a parallel way

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#355]
for i in range(batch_size):
      grad = ray.get(grads[i])   

_only one task is exectuting, and the others are waiting_

is that right?

**Comment by robertnishihara** [comment]
It's possible that this is happening.

After doing

```python
import ray
ray.init()
```

Can you print the output of the following?

```python
import time

@ray.remote
def f():
  time.sleep(1)

start = time.time()
ray.get([f.remote() for _ in range(5)])
end = time.time()

print(end - start)
```

Could you also print the output of

```python
import psutil

print(psutil.cpu_count())
```

By default, when `ray.init` is called, it checks the number of CPUs and won't schedule more than that number of things at a time.

I suspect this will be fixed by telling Ray there are a larger number of CPUs.

```python
ray.init(num_cpus=10)
```

Can you try that?

I'll think about the best way to update the example to avoid this problem.

**Comment by raopku** [comment]
import ray
#ray.init()
import time
@ray.remote
def f():
    time.sleep(1)
start = time.time()
ray.get([f.remote() for _ in range(20)])
end = time.time()

print(end-start)

it turns out to be 2.095, for it is obvious that the remote function was exectured parallel.

however, in example of rl-pong , maybe something is different : _ray.env.env = ray.EnvironmentVariable(env_initializer, env_reinitializer)_

i have tested in two ways:

First way: 
#     grads_col = ray.get(grads)
#     reward_sums_col = ray.get(reward_sums)
    for i in range(batch_size):
      grad = ray.get(grads[i])
      reward_sum = ray.get(reward_sums[i])
      for k in model: grad_buffer[k] += grad[k] # accumulate grad over batch
      running_reward = reward_sum if running_reward is None else running_reward * 0.99 + reward_sum * 0.01
      print("Batch {}. episode reward total was {}. running mean: {}".format(batch_num, reward_sum, running_reward))

it takes about 24-25 second every batch(10)

Second way:
    grads_col = ray.get(grads)
    reward_sums_col = ray.get(reward_sums)
    for i in range(batch_size):
      grad =grads_col[i]
      reward_sum = reward_sums_col[i]
      for k in model: grad_buffer[k] += grad[k] # accumulate grad over batch
      running_reward = reward_sum if running_reward is None else running_reward * 0.99 + reward_sum * 0.01
      print("Batch {}. episode reward total was {}. running mean: {}".format(batch_num, reward_sum, running_reward))

it takes about 24-25 second every batch(10) too...

**Comment by robertnishihara** [comment]
Can you tell me the following?

1. How many cores are on the machine? What is the output of `import psutil; psutil.cpu_count()`?
2. What operating system are you using?
3. What Python distribution are you using (e.g., Anaconda, or the version of Python that came with the system, etc).
4. Does numpy seem to be using multiple cores? For example, if you do `x = np.zeros((4000, 4000)); np.dot(x, x)`, and then open `top` in another tab, what percent CPU utilization does Python have?

One common problem is that numpy tries to use a bunch of cores, and so when you run multiple tasks that all use numpy, they each try to use all of the cores and the result is inefficient (there is often no speedup).

To get around this, you might try doing

```
export MKL_NUM_THREADS=1
```

before running the script.

**Comment by raopku** [comment]
How many cores are on the machine? What is the output of import psutil; psutil.cpu_count()?
24
What operating system are you using?
Ubuntu14.04
What Python distribution are you using (e.g., Anaconda, or the version of Python that came with the system, etc).
Anaconda2 python2.7
Does numpy seem to be using multiple cores? For example, if you do x = np.zeros((4000, 4000)); np.dot(x, x), and then open top in another tab, what percent CPU utilization does Python have?
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                   
 2672 dl        20   0 25.034g 0.012t  11288 R  2354  9.7  13:30.59 python                                                    
    8 root      20   0       0      0      0 S   0.7  0.0   0:56.89 rcu_sched                                                 
 2114 dl        20   0   48668   9888   3404 S   0.7  0.0   0:00.53 redis-server                                              
 2723 dl        20   0   25216   3304   2480 R   0.7  0.0   0:00.39 top                                                       


Is there something wrong?

**Comment by robertnishihara** [comment]
I'm not completely confident that I'm reading this correctly, but it looks to me like numpy is using `2354%` CPU (so I guess about 23.5 cpus) for the matrix multiplication.

I'd suggest trying to restrict numpy to a single core via `export MKL_NUM_THREADS=1`. It should be enough to do that before you run the script. Although you could also do the following inside of `compute_gradient`.

```python
@ray.remote(num_return_vals=2)
def compute_gradient(model):
  import os
  os.environ["MKL_NUM_THREADS"] = "1"
  ...
```

I'll be offline for a bit, but let me know if this works!

**Comment by raopku** [comment]
I have tryed to export MKL_NUM_THREADS=1
logs looks like this:
One Batch.............................takes time:22.6780068874
3972 is training begin.....
3972 is training end.....
3975 is training begin.....
3975 is training end.....
3974 is training begin.....
3974 is training end.....
3973 is training begin.....
3973 is training end.....
3971 is training begin.....
3971 is training end.....
3979 is training begin.....
3979 is training end.....
3976 is training begin.....
3976 is training end.....
3977 is training begin.....
3977 is training end.....
3978 is training begin.....
3978 is training end.....
3980 is training begin.....
3980 is training end.....

it still takes 20-26s every batch(10).

**Comment by raopku** [comment]
if i set batch size = 1
logs looks like this:
One Batch.............................takes time:2.37597608566
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.2379090786
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:1.92952990532
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.558396101
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.08501601219
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.24023890495
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.25252509117
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.51341581345
5133 is training begin.....
5133 is training end.....
One Batch.............................takes time:2.21458387375

compare to batch size =10
2.21 * 10 = 22.10.

**Comment by robertnishihara** [comment]
I just tried this out on an X1 instance.

WITHOUT `export MKL_NUM_THREADS=1`, we see poor performance. This confirms what you've been seeing.

- `batch_size = 1`, each thing takes about **1 or 2** seconds.
- `batch_size = 10`, each thing takes about **11** seconds.
- `batch_size = 50`, each thing takes about  **60** seconds.

WITH `export MKL_NUM_THREADS=1`. Things look much better.

- `batch_size = 1`, each thing takes about **1.5 to 2.5** seconds.
- `batch_size = 10`, each thing takes about  **2.5** seconds.
- `batch_size = 50`, each thing takes about  **2.5 to 3** seconds.

Can you confirm that `MKL_NUM_THREADS` was properly set, but adding the line

```python
import os
print("XXX", os.getenv("MKL_NUM_THREADS"))
```

inside of the `compute_gradient` remote function and seeing what gets printed?

**Comment by robertnishihara** [comment]
Ok, maybe your numpy is not using MKL, perhaps it is using OpenBLAS. Can you try doing the following **before running the script** (it seems that this has to be done before numpy is imported).

```
export OPENBLAS_NUM_THREADS=1 
```

Can you share the output of

```python
import numpy
numpy.__config__.show()
```

That should tell us whether MKL or OpenBLAS is being used.

**Comment by raopku** [comment]
After export OPENBLAS_NUM_THREADS=1 , It works. Thank you very much. 
I have another question about this example.
```
    grads_col = ray.get(grads)
    reward_sums_col = ray.get(reward_sums)
    for i in range(batch_size):
      grad = grads_col[i]
      print(str(i)+" is trainging in "+ str(ray.get(pids[i]))  +" and it is done!")
      reward_sum = reward_sums_col[i]
      for k in model: grad_buffer[k] += grad[k] # accumulate grad over batch
      running_reward = reward_sum if running_reward is None else running_reward * 0.99 + reward_sum * 0.01
      print("Batch {}. episode reward total was {}. running mean: {}".format(batch_num, reward_sum, running_reward))
```
I can understand that all the tasks will be dispatched by 
schedulers. Thus, all tasks in a batch is exectuted parallel.

However , how can the example below achieves a parallel effect?
```
    for i in range(batch_size):
      grad_id, reward_sum_id, pid = compute_gradient.remote(model_id)
      grads.append(grad_id)
      reward_sums.append(reward_sum_id)
      pids.append(pid)
#     grads_col = ray.get(grads)
#     reward_sums_col = ray.get(reward_sums)
    for i in range(batch_size):
      grad = ray.get(grads[i])
      print(str(i)+" is trainging in "+ str(ray.get(pids[i]))  +" and it is done!")
      reward_sum = ray.get(reward_sums[i])
      for k in model: grad_buffer[k] += grad[k] # accumulate grad over batch
      running_reward = reward_sum if running_reward is None else running_reward * 0.99 + reward_sum * 0.01
      print("Batch {}. episode reward total was {}. running mean: {}".format(batch_num, reward_sum, running_reward))
```

I think every ray.get(object_id) is a block method. Only one task is exectuted. The others tasks have not been dispatched by schedulers because no one call the ray.get() method on them.

**Comment by robertnishihara** [comment]
I believe you're asking about the following situation, where we launch some tasks, and then call `ray.get` on the results one after another.

```python
import ray
import time

ray.init()

@ray.remote
def f():
  time.sleep(1)
  return 1

# Launch some tasks.
results = []
for i in range(4):
  results.append(f.remote())

# Get all of the results.
for i in range(4):
  ray.get(results[i])
```

Is that correct?

All of the calls to `f` can be executed in parallel. The reason for this is that **execution in Ray is not lazy**, and so it will not wait for a call to `ray.get` to begin executing a task.

You're right that `ray.get` will block until the object is available. However, `ray.get` does not actually *trigger* the execution of the task.

To demonstrate this, you can try waiting a little bit before running the second for loop and it should return immediately.

**Comment by raopku** [comment]
Thank you very much. _execution in Ray is not lazy_
I suddenly see the light

**Comment by robertnishihara** [comment]
Great! And I'm glad the example finally worked out!
