### ISSUE TITLE
AsyncSampler auto-concat feature causes non-requested batch size increase

### ISSUE THREAD

**Issue by opherlieber** [ray-project/ray#3550]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.0
- **Python version**: 3.6.7
- **Exact command to reproduce**: rllib train --run PPO --env CartPole-v0 --config '{"train_batch_size":200,"sample_batch_size":200,"num_workers":1,"sample_async":true,"observation_filter":"NoFilter"}'

### Describe the problem

When working with the AsyncSampler, the auto-concat feature in the 'get_data()' routine causes sample sizes which exceed the 'batch_steps' passed to PolicyEvaluator, when using batch_mode="truncate_episodes". 
In this mode the doc says the batch size will be exactly 'batch_steps * num_envs', however due to auto-concat feature, assuming the ENV is faster than the training, we will get the entire queue as additional data (in the provided example command, we get 1200 train steps each iteration instead of the requested 200, due to the AsyncSampler queue size of 5).

In case of batch_mode="complete_episodes", the auto-concat feature has no effect (Since each rollout always ends with 'done')

The comment suggests this is to improve A3C performance, which it probably does for fast envs, but that would always be true by increasing the batch size. 
In many algorithms it's important to have a fixed batch size using 'truncate_episodes', while still using the AsyncSampler (For example for real-time environments which continue running during train time)

Maybe make the auto-concat an optional configuration? Maybe as part of a new 'batch_mode' option (batch_mode="max_available"?)

**Comment by ericl** [comment]
Yeah this has been problematic before. I would be in favor of removing this batching behavior entirely, since I suspect you can tune some hyperparameters to get a similar effect. Also, A3C performance is not that important to preserve since there are much faster algorithms.

cc @richardliaw

**Comment by ericl** [comment]
By the way, using the async sampler doesn't guarantee the env will keep running during training time if the buffer fills up. If that sort of off-policy sampling is ok, why not use IMPALA which will gather experiences asynchronously without needing to use async_sampler: True?

**Comment by richardliaw** [comment]
Yeah we should probably remove that batching behavior; it’s confusing...

**Comment by opherlieber** [comment]
> By the way, using the async sampler doesn't guarantee the env will keep running during training time if the buffer fills up. If that sort of off-policy sampling is ok, why not use IMPALA which will gather experiences asynchronously without needing to use async_sampler: True?

I'm trying also IMPALA but want also the option to use other algos like PPO. In my particular use-case the training is much faster than the ENVs so the buffer shouldn't fill, but still the training phase takes ~500ms and that make the ENV unplayable if sampling isn't async.
I'm mainly looking into trying to train on actual games in real-time where the environment isn't a fully controlled emulation like atari/gym-retro that waits/pauses until getting the next step (Like a regular windows game or flash game or mobile game). 
I don't see how to avoid slightly off-policy sampling for this case but still want the ability to try algorithms like PPO.

I noticed also the 'ExternalEnv' option, is that more suitable for such a use-case than the AsyncSampler?

**Comment by ericl** [comment]
> I noticed also the 'ExternalEnv' option, is that more suitable for such a use-case than the AsyncSampler?

Hm it should be subject to the same limitations in that if you aren't actively sampling, the env could be stalled.
