### ISSUE TITLE
[CI] [Core] Apparent throughput regressions in several benchmarks

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#35517]
<img width="732" alt="Screen Shot 2023-05-18 at 1 49 48 PM" src="https://github.com/ray-project/ray/assets/950914/01a1c00d-ec65-4609-b1d7-30a7f8d1380c">
<img width="710" alt="Screen Shot 2023-05-18 at 1 49 41 PM" src="https://github.com/ray-project/ray/assets/950914/05d9c9a8-bcd2-411c-b021-98bb3c37648d">
<img width="742" alt="Screen Shot 2023-05-18 at 1 49 35 PM" src="https://github.com/ray-project/ray/assets/950914/7f7708b5-532d-483b-af08-76bed94159cb">

**Comment by cadedaniel** [comment]
Going to first see if these regressions made it into the release branch.

**Comment by rickyyx** [comment]
I am looking into the microbenchmarks - I am pretty confident it's my PR that caused it.

**Comment by jjyao** [comment]
It's a real regression and made it into the release branch.

**Comment by cadedaniel** [comment]
assigning to you @rickyyx lmk if you're not working on it

**Comment by cadedaniel** [comment]
duplicate of https://github.com/ray-project/ray/issues/35598, other two metrics have recovered
