### ISSUE TITLE
[CI] [Windows] [Ray Client] Unskip `windows://python/ray/tests:test_multiprocessing_client_mode`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#35553]
### What happened + What you expected to happen

This test became flaky on Windows (https://github.com/ray-project/ray/issues/35526) and was skipped in https://github.com/ray-project/ray/pull/35534.  We should unskip this test.

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

None

**Comment by anyscalesam** [comment]
@can-anyscale can you share how one is able to manually kick off a CI test after we believe it's been unflaked? @mattip  can help here else @architkulkarni can check tonight if the CI is passing now?
