### ISSUE TITLE
[clouldpickle]  More diagnostics and logging 

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#35555]
### Description

Add logging to what cloud pickle is doing. At the very least the inputs and the size of the object that is going to be serialized. More info such as the hierarchy of objects that is being traversed is also helpful.

### Use case

It can often happen that we send an unintended input to cloud pickle that has unwanted consequences. For example if you have a torch or numpy sub matrix you might think that this is a small matrix, but in fact internally it just holds reference to a larger matrix.

When you pass this to ray.put() or .remote() functions, then a huge value will be serialized (due to referencing the original large tensor). 

Currently, there is no diagnostics in ray to monitor/debug this kind of accidents.

**Comment by richardliaw** [comment]
So there exists this really poor version of this with `inspect_serializability` https://docs.ray.io/en/latest/ray-core/api/doc/ray.util.inspect_serializability.html

Maybe we can productionize it?

**Comment by rkooo567** [comment]
@richardliaw  That API has been pretty actively used and it is actually used to produce the error message by default as well.

@shayanhoshyari 

1. How do you notice when you have this sort of "accident"?
2. Is the requirement that you'd like to know exactly which object is serialized & which object is not (for zero copy)?

**Comment by shayanhoshyari** [comment]
> How do you notice when you have this sort of "accident"?

I would like to be able to consult logs or metrics/telemetry and see the amount of data being serialized.

> Is the requirement that you'd like to know exactly which object is serialized & which object is not (for zero copy)?

That is a nice to have. But actually the first requirement is just seeing what is being serialized (logging and tracing/metrics). This way if we see we are serializing much more data (e.g. ~GB when we expect ~MB) than expected, we know that we are doing something wrong. E.g.  we are serializing subviews of torch matrices that are attached to their graph! instead of detaching them.

**Comment by jjyao** [comment]
For the metrics, we can look at the current object store size ones as an approximation.
