### ISSUE TITLE
[serve][dashboard] Previous status message remains when app transitions from `DEPLOY_FAILED` to `DEPLOYING`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#35601]
I had an import error, then fixed it and re-deployed on the same cluster. The message still showed the previous exception traceback so I was confused thinking it hadn't updated. Turns out it was in the process of redeploying.

<img width="905" alt="Screen Shot 2023-05-22 at 8 38 38 AM" src="https://github.com/ray-project/ray/assets/9871461/6830dec8-385b-4306-a80e-91a6246e1eb6">

**Comment by edoakes** [comment]
Also remains when it transitions to `RUNNING`:

<img width="893" alt="Screen Shot 2023-05-22 at 8 58 33 AM" src="https://github.com/ray-project/ray/assets/9871461/1a16ff2a-b2a1-4a99-86d8-466d4abeedaf">

This is a really bad UX

**Comment by scottsun94** [comment]
Dup of this? https://github.com/ray-project/ray/issues/35508

**Comment by edoakes** [comment]
Closing in favor of https://github.com/ray-project/ray/issues/35508
