### ISSUE TITLE
[Train] LightningTrainer failed to auto-restore if `ckpt_path` provided in `LightningConfigbuilder.fit_param()`

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#35613]
### What happened + What you expected to happen

If users provide a `ckpt_path` in `LightningConfigBuilder.fit_param()`, when resuming training from a failed run, LightningTrainer will always resume training from that `ckpt_path` again, instead of the latest AIR checkpoint.

Code: https://github.com/ray-project/ray/blob/0fd06ad6fd54045e038f58ff75abd72c7adb2511/python/ray/train/lightning/lightning_trainer.py#L543-L549

Instead, we should always restore from the latest AIR checkpoint, if we can get it from the session, regardless of whether the user provided a `ckpt_path` or not.

### Versions / Dependencies

master

### Reproduction script

```python
lightning_config = (
    LightningConfigBuilder()
    .module(
        ...
    )
    .trainer(
        ...
    )
    .fit_params(
        train_dataloaders=train_loader,
        val_dataloaders=val_loader,
        ckpt_path="YOUR_CKPT_PATH"
    )
    .build()
)
```

Together with a FailureConfig
```python
run_config = RunConfig(
    ...,
    failure_config=FailureConfig(max_failures=3), 
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by dzikrisyairozi** [comment]
can you give me more proper reproduction script
