### ISSUE TITLE
Not Scaling GPU Resources

### ISSUE THREAD

**Issue by kevinzakka** [ray-project/ray#3561]
Hello,

First of all thanks for the amazing library. I've managed to write a custom trainable pytorch script for hyperparameter tuning and am running it on an AWS p3.8x large. There are 4 gpus and I am specifying that in the config file.

I am able to successfully run the script with no errors but tune will only run on 1 GPU (verified through nvidia-smi). The other 3 gpus remain idle.

I am not sure how to debug this and would appreciate some help.

Thank you!

**Comment by ericl** [comment]
How are you configuring the experiment? You probably need something like

`trial_resources: {"gpu": 1, "cpu": 1}`

and then you should see 4/4 GPUs, 4/N CPUs used in the status with 4 concurrent trials running. If you don't set the GPU option then CUDA_VISIBLE_DEVICES will be set to the empty string I think.

**Comment by kevinzakka** [comment]
@ericl there seems to be a bug actually. Here's my observation so far:

* {"gpu": 4, "cpu": 0}: only runs on 1 GPU
* {"gpu": 2, "cpu": 0}: runs on 2
* {"gpu": 3, "cpu": 0}: only runs on 1.

Also, pytorch data loaders usually run on the CPU. Does that mean I have to specify a CPU resource for every GPU resource I request?

**Comment by ericl** [comment]
I see the problem. When you say GPU:4, that's 4 gpus *per trial*. So you
want gpu: 1.

You probably don't need to explicitly request CPUs unless you find your
machine is getting overloaded, since GPUs will be the bottleneck.

**Comment by kevinzakka** [comment]
@ericl ah that makes sense. So then if I do assign 2 GPUs per trial and a trial corresponds to X epochs for a specific set of parameters, how do they get split up on both GPUs? Does ray automatically do batch splitting?

**Comment by ericl** [comment]
Ray will set CUDA_VISIBLE_DEVICES to the two GPU IDs assigned to your
trial, but it's up to your code to use the assigned GPUs for training.

**Comment by kevinzakka** [comment]
@ericl I see, I'd still have to wrap my code with pytorch's `nn.DataParallel` then. Thanks for the quick help btw!
