### ISSUE TITLE
[Core] [2023-05-20 05:18:33,131 C 151 151] (gcs_server) gcs_actor_manager.cc:1271:  Check failed: iter != actor_task_specs.end() 

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#35622]
### What happened + What you expected to happen

[2023-05-20 05:18:33,131 C 151 151] (gcs_server) gcs_actor_manager.cc:1271:  Check failed: iter != actor_task_specs.end() 

### Versions / Dependencies

2.4.0

### Reproduction script

https://console.anyscale.com/o/anyscale-internal/services/service2_ft2lspe385g81ptalr2nqk161i

### Issue Severity

None

**Comment by can-anyscale** [comment]
Hmm, if this is already a regression in 2.4 and we survive it for a month, why it becomes a release blocker now?

**Comment by scv119** [comment]
guilty until proven innocent
