### ISSUE TITLE
[Core] Cherry pick streaming generator PRs 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#35634]
### What happened + What you expected to happen

We want to support the streaming generator for ray serve by Ray 2.5. We need to cherry-pick all these commits. 

- [x] https://github.com/ray-project/ray/pull/35291
    - https://github.com/ray-project/ray/pull/35656
- [x] https://github.com/ray-project/ray/pull/35324
    - https://github.com/ray-project/ray/pull/35682
- [x] https://github.com/ray-project/ray/pull/35325
    - https://github.com/ray-project/ray/pull/35708
- [x] https://github.com/ray-project/ray/pull/35584
    - https://github.com/ray-project/ray/pull/35752
- [x] https://github.com/ray-project/ray/pull/35591
    - https://github.com/ray-project/ray/pull/35707
- [x] https://github.com/ray-project/ray/pull/35747
    - https://github.com/ray-project/ray/pull/35772
- [x] https://github.com/ray-project/ray/pull/35712
    - https://github.com/ray-project/ray/pull/35794
- [x] https://github.com/ray-project/ray/pull/35766
    - https://github.com/ray-project/ray/pull/35803
- [x] https://github.com/ray-project/ray/pull/35720
    - https://github.com/ray-project/ray/pull/35811

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by can-anyscale** [comment]
This is an additional feature instead of a a release-blocker fix. Can this wait until 2.6?

**Comment by xieus** [comment]
@can-anyscale This streaming feature is a top priority in collaboration with Serve team. If it doesn't ship, we may have a delayed delivery of LLM serving feature. We should prioritize this.

**Comment by can-anyscale** [comment]
@xieus ack!

**Comment by zhe-thoughts** [comment]
cc @waleedkadous @edoakes 

Yes, @can-anyscale I added you to an email thread

**Comment by edoakes** [comment]
There will be additional Ray Serve PRs to pick, should all be ready by EOW

**Comment by ArturNiederfahrenhorst** [comment]
@zhe-thoughts @edoakes @rkooo567 
As far as I can tell, all the PRs listed here have been merged.
If no tests fail, is this release-blocker resolved?

**Comment by zhe-thoughts** [comment]
I agree it can be resolved.

**Comment by rkooo567** [comment]
Should be good to go!
