### ISSUE TITLE
[Core] decision_tree_autoscaling_20_runs failed once

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#35630]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_emrscqf6wwf1v821m7yy6p5ymr

### Versions / Dependencies

master

### Reproduction script

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_emrscqf6wwf1v821m7yy6p5ymr

### Issue Severity

None

**Comment by iycheng** [comment]
The recent failure is due to infra error I think:

https://buildkite.com/ray-project/release-tests-probes/builds/631#01888eaa-5445-48a4-865b-37c4c6fba890
https://buildkite.com/ray-project/release-tests-probes/builds/631#01888eaa-5448-4699-8a6f-7a00ac7c6a05


I can't reproduce the error in the description. Still looking.

**Comment by iycheng** [comment]
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_se74v8e3jsys1hnmgyi8jijgwz
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_gix38bnw7ul6v32ab67s1yvwcg
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_6g34f4bj4dhymqsiglx1y3nqkx
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_9n88dfrhkpsbvtgbu5atw4qgdf

Run several times and all passed :( still checking

**Comment by iycheng** [comment]
```
[2023-05-20 08:33:38,869 W 106010 106113] reference_count.cc:1546: Object locations requested for 005c1e3d3a28bc71ffffffffffffffffffffffff020000000d000000, but ref already removed. This may be a bug in the distributed reference counting protocol.
```

**Comment by iycheng** [comment]
This seems like a race condition in ref counting.

When the worker want to fetch the object, the ref has been deleted somehow.

**Comment by iycheng** [comment]
After studying around, I think this is pretty hard to debug given that it's never being reproduced :(

**Comment by fishbone** [comment]
It runs good for now. Close it
