### ISSUE TITLE
[docs][serve]Broken link 

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#35665]
### Description

Someone reported this to Robert: 

"Robert, I was reading some Ray docs, and noticed there's a broken link on the [getting started](https://docs.ray.io/en/latest/ray-overview/getting-started.html) page:
[How to launch a Ray Serve API on a remote cluster (AWS)](https://jbesomi.com/ray-serve-remote-cluster)"

### Link

https://docs.ray.io/en/latest/ray-overview/getting-started.html

**Comment by shrekris-anyscale** [comment]
This link existed in [Ray 2.4.0](https://docs.ray.io/en/releases-2.4.0/ray-overview/getting-started.html#blog-and-press):

<img width="672" alt="Screen Shot 2023-06-23 at 7 35 57 PM" src="https://github.com/ray-project/ray/assets/92341594/8282bb6b-c602-4722-9527-5d484cd31503">

It was removed starting in [Ray 2.5.0](https://docs.ray.io/en/releases-2.5.0/ray-overview/getting-started.html#blog-and-press):

<img width="673" alt="Screen Shot 2023-06-23 at 7 36 26 PM" src="https://github.com/ray-project/ray/assets/92341594/3d2f3f20-523e-4ae5-8c44-3be251876dd8">

I'll close this issue as resolved.
