### ISSUE TITLE
[contrib] Upstream vscode debugger implementation into ray 

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#35674]
### Description

We have developed a concise mechanism to run all ray deployments in vscode debugger without needing any attaching. 

The way it works is that it will remember the vscode server config from main process, then pass it to all deployments. The deployments will then try to connect back to vscode debugging server.

- If you run the serve.run() code outside vscode debugger, create_pydenv_config will return None and nothing happens.
- If you run the serve.run() code in vscode debugger, you can see all the processes in the same debugger instance.

A caveat of this code is that it expects that everything is on same localhost, but it is not a hard limitation and can be lifted.

__The request is to integrate this feature natively into ray.__

Here is the code:

<details>

<summary> connect_to_pydev.py </summary>

```py
import importlib
import logging
import os
import sys
import logging
from pathlib import Path
from typing import Any

from pydantic import BaseModel

logger = logging.getLogger(__name__)

class PydevConfig(BaseModel):
    sys_path: str
    client: str
    port: int
    client_access_token: str
    ppid: int


def get_debugpy() -> Any:
    try:
        return importlib.import_module("debugpy")
    except Exception:
        return None


def break_in_vscode() -> None:
    """Breaks into the debugger if it is connected."""
    debugpy = get_debugpy()
    if debugpy is None:
        return
    if debugpy.is_client_connected():
        debugpy.breakpoint()


def connect_to_pydev(config: PydevConfig | None) -> None:
    print(config)
    if config is None:
        return

    sys_path = config.sys_path
    sys.path.append(sys_path)

    logging.info("Added debupy sys path %s", sys_path)

    debugpy = get_debugpy()
    if debugpy is None:
        logger.exception("debugpy was not available to the raylet even after adding the required syspath. Bailing out.")
        return

    logging.info("Imported debugpy")

    if debugpy.is_client_connected():
        logger.warning("debugpy client already connected.")
        return

    client = config.client
    port = config.port
    client_access_token = config.client_access_token

    pydevd = debugpy.server.api.pydevd
    pydevd.SetupHolder.setup = {
        "ppid": config.ppid,
        "client": client,
        "port": port,
        "client-access-token": client_access_token,
    }

    logging.info("Connecting to debugpy at %s: %s", client, port)
    debugpy.connect([client, port], access_token=client_access_token)

    logger.info("Waiting for debugger connection.")
    debugpy.wait_for_client()
    logger.info("Connected to the debugger.")


def create_pydev_config() -> PydevConfig | None:
    debugpy = get_debugpy()
    if debugpy is None:
        logger.info("Pydev is not available, vs code debug support is not available.")
        return None

    if not debugpy.is_client_connected():
        logger.info("No VS code was available during boot.")
        return None

    pydevd = debugpy.server.api.pydevd
    setup = pydevd.SetupHolder.setup

    pydev_config = PydevConfig(
        ppid=os.getpid(),
        sys_path=str(Path(debugpy.__file__).resolve().parents[1]),
        client=setup.get("client"),
        port=setup.get("port"),
        client_access_token=setup.get("client-access-token"),
    )

    logger.info("Created VSCode pydev config %s", pydev_config)
    return pydev_config

```

</details>

<details>

<summary> Usage </summary>

```py

# In the deployment

@serve.deployment
class MyDeployment:

def __init__(self, pydev_config: PydevConfig | None):
    if pydev_config is not None:
        connect_to_pydev(pydev_config)


## Binding the deployment
pydev_config = create_pydenv_config()
deployment = MyDeployment.bind(pydev_config)
serve.run(deployment)
```

</details>

### Use case

It is very useful for debugging deployments. And as easy debugging is one of Ray's goals, it would be a nice addition.

The debugger can handle both scenarios
- Deploying things locally
- Deploying things to ray cluster running remotely (supported by vscode, but not integrated into the referenced code)

So even if a user does not have a beefy GPU machine, but they have a remote cluster running, they still can debug things which is quite nice.

**Comment by richardliaw** [comment]
This is awesome! Also cc @sofianhnaide and @alanwguo and @pcmoritz here -- Shayan has an implementation here already for integrating vscode debugger into Ray, and is looking to upstream. 

Who is the owner here?

**Comment by scottsun94** [comment]
cc: @rkooo567

**Comment by zhe-thoughts** [comment]
Awesome work @shayanhoshyari and team!

**Comment by rkooo567** [comment]
Excited for the contribution!

**Comment by rkooo567** [comment]
(please ignore the priority assignment. it is just to not close this issue.)

**Comment by achordia20** [comment]
This is awesome! Is there a plan to integrate this within Ray directly?

**Comment by richardliaw** [comment]
cc @sofianhnaide for visibility.

We're currently working on productionizing and polishing a version of this internally. Will provide an update in the next month!

**Comment by shayanhoshyari** [comment]
https://github.com/ray-project/ray/pull/42311
