### ISSUE TITLE
[Dashboard] Runtime env errors using job submission API is hard to find

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#35685]
### What happened + What you expected to happen

When running into a runtime env error in the jobs api, the only way i can find anything about it is going to the `runtime_env_agent.log` file.

This should be front and center in the job detail page.
<img width="1720" alt="Screenshot 2023-05-23 at 2 52 37 PM" src="https://github.com/ray-project/ray/assets/711935/92a55694-28c9-489e-abbd-b0971df019cf">

### Versions / Dependencies

2.4.0

### Reproduction script

```
import ray
from ray.job_submission import JobSubmissionClient

client = JobSubmissionClient("http://127.0.0.1:8265")

job_id = client.submit_job(
    # Entrypoint shell command to execute
    entrypoint="echo hi",
    # Runtime environment for the job, specifying a working directory and pip package
    runtime_env={
        "working_dir": "./",
        "pip": ["asdfsadfasfdsafdasfds"],
    },
)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by architkulkarni** [comment]
More generally, (not just for runtime env), when a job enters FAILED, it would make sense to display the `message` field which includes the traceback from the failure.

In this case, it looks like 
```
In [7]: pprint.pprint(client.get_job_info(job_id).message)
('runtime_env setup failed: Failed to set up runtime environment.\n'
 'Could not create the actor because its associated runtime env failed to be '
 'created.\n'
 'Traceback (most recent call last):\n'
 '  File '
 '"/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", '
 'line 351, in _create_runtime_env_with_retry\n'
 '    runtime_env_context = await asyncio.wait_for(\n'
 '  File '
 '"/Users/archit/anaconda3/envs/ray-py38/lib/python3.8/asyncio/tasks.py", line '
 '494, in wait_for\n'
 '    return fut.result()\n'
 '  File '
 '"/Users/archit/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", '
 'line 311, in _setup_runtime_env\n'
 '    await create_for_plugin_if_needed(\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/plugin.py", line '
 '254, in create_for_plugin_if_needed\n'
 '    size_bytes = await plugin.create(uri, runtime_env, context, '
 'logger=logger)\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/pip.py", line 474, '
 'in create\n'
 '    return await task\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/pip.py", line 456, '
 'in _create_for_hash\n'
 '    await PipProcessor(\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/pip.py", line 362, '
 'in _run\n'
 '    await self._install_pip_packages(\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/pip.py", line 338, '
 'in _install_pip_packages\n'
 '    await check_output_cmd(pip_install_cmd, logger=logger, cwd=cwd, '
 'env=pip_env)\n'
 '  File "/Users/archit/ray/python/ray/_private/runtime_env/utils.py", line '
 '101, in check_output_cmd\n'
 '    raise SubprocessCalledProcessError(\n'
 'ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[9] '
 'failed with the following details.\n'
 'Command '
 "'['/tmp/ray/session_2023-05-23_15-31-00_774734_59509/runtime_resources/pip/f436168bffe7b51521440d04a0e32aeb317ff6b1/virtualenv/bin/python', "
 "'-m', 'pip', 'install', '--disable-pip-version-check', '--no-cache-dir', "
 "'-r', "
 "'/tmp/ray/session_2023-05-23_15-31-00_774734_59509/runtime_resources/pip/f436168bffe7b51521440d04a0e32aeb317ff6b1/requirements.txt']' "
 'returned non-zero exit status 1.\n'
 'Last 50 lines of stdout:\n'
 '    ERROR: Could not find a version that satisfies the requirement '
 'asdfsadfasfdsafdasfds (from versions: none)\n'
 '    ERROR: No matching distribution found for asdfsadfasfdsafdasfds\n')
```

**Comment by alanwguo** [comment]
That seems like a general fix we should apply right away. One solution, can we just log the job message into the raysubmit_12345 driver log file?

I can also add the message to the UI

**Comment by architkulkarni** [comment]
In the case of an application error, it should already be logged there.  If the error happens before the entrypoint script is executed (before the JobSupervisorActor runs), it isn't currently logged, but it should be possible to add it

**Comment by alanwguo** [comment]
> In the case of an application error, it should already be logged there. If the error happens before the entrypoint script is executed (before the JobSupervisorActor runs), it isn't currently logged, but it should be possible to add it

okay, please make this change. Separately, i'll also display the message in the UI.

**Comment by alanwguo** [comment]
removing release-blocker, since only my PR should block the release

**Comment by scottsun94** [comment]
@architkulkarni Do you have a timeline for adding this to the logs?

**Comment by architkulkarni** [comment]
Closing this issue, created a new issue for the logs here: https://github.com/ray-project/ray/issues/35997.

There's no timeline currently. Tentatively assigning P2, but will leave it to @akshay-anyscale to triage and prioritize.
