### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by allseeworld** [ray-project/ray#35699]
### What happened + What you expected to happen

One cbc in ray ran at full capacity for three days
![image](https://github.com/ray-project/ray/assets/48939352/b9622685-9640-4aae-ad6e-6e8d62b027eb)

### Versions / Dependencies

2.4.0 k8s

### Reproduction script

cbc came out on its own

### Issue Severity

High: It blocks me from completing my task.

**Comment by pcmoritz** [comment]
I'm pretty sure this is your own "cbc" command that is just running as the "ray" user (which is the default user in the Ray docker images). There is no "cbc" command run as part of Ray.

It seems cbc is a branch and cut command line utility from the coin-or suite (for mixed integer programming). Maybe you were parallelizing an algorithm related to that and the command takes a long while to execute?

**Comment by allseeworld** [comment]
> 我很确定这是您自己的“cbc”命令，它只是作为“ray”用户（这是 Ray docker 镜像中的默认用户）运行。没有作为 Ray 的一部分运行的“cbc”命令。
> 
> 似乎 cbc 是来自 coin-or 套件（用于混合整数编程）的分支和剪切命令行实用程序。也许您正在并行化与此相关的算法并且命令需要很长时间才能执行？

Well, I did use an algorithm package, thank you
