### ISSUE TITLE
[AIR] computer_vision_test is too big

### ISSUE THREAD

**Issue by gjoliver** [ray-project/ray#35692]
### Description

our ray_air/doc_code/computer_vision.py test is too heavy.
it runs 5 batch inference jobs in both tf and torch in a loop, and is taking longer than 15mins to finish.
we changed it to "enormous", to unblock the release for now.

it would be nice to reduce the size while still testing the functionalities.
for example, use a much smaller dataet, or run this on GPU node, etc.
the problem with large tests is that our CI takes a long time to finish.

cc @richardliaw 

### Link

https://github.com/ray-project/ray/blob/master/doc/source/ray-air/doc_code/computer_vision.py

**Comment by bveeramani** [comment]
Thanks! The dataset size is limited to 32 rows, so I'm not how much using a smaller dataset will help, but I'll take a look.

**Comment by richardliaw** [comment]
how about let’s  run it on the GPU runners?
