### ISSUE TITLE
[Core][Serve] Memory leak in Ray components and modules

### ISSUE THREAD

**Issue by Lorien2027** [ray-project/ray#35714]
### What happened + What you expected to happen

We have a Serve application for which we are doing load testing. It consists of 2 nodes (head and worker), approximately 50 thousand requests are processed during the day and about 40 remote tasks are called for each request from the actors. We observe an increase in memory both in ray components (Raylet, Serve Controller, Serve Controller:listen_for_change) and in modules over time. At about 12:00, the flow of requests was stopped - the memory of ray components continued to grow, and the increase in modules slowed down, but did not stop (about 30 MB in each from 12:00 to 15:00). The number of requests is constant over time, autoscaler is turned off. Examples are given only for 2 modules (memory increases for all). 
Module 1:
![deployment_1](https://github.com/ray-project/ray/assets/61617389/d0da2bb2-e899-41ea-86d6-428a9ed8b669)
Module 2:
![deployment_2](https://github.com/ray-project/ray/assets/61617389/95019dfb-7d6f-4e13-99fb-71d9dd5b4f4d)
HTTP Proxy Actor:
![http_proxy_actor](https://github.com/ray-project/ray/assets/61617389/afa357d7-4072-4876-8fed-0c810ebf5aef)
Raylet:
![raylet](https://github.com/ray-project/ray/assets/61617389/473ca2c9-3fa5-4a8d-8803-55d482709468)
Serve Controller:
![serve_controller](https://github.com/ray-project/ray/assets/61617389/8a636e0f-2b94-4cb3-aacc-43d0de38017f)
Serve Contoller:listen_for_change
![serve_controller_listen_for_change](https://github.com/ray-project/ray/assets/61617389/4847e1ea-4290-4cd9-91ac-26448f2c538b)
Head Node:
![head_node](https://github.com/ray-project/ray/assets/61617389/cd33b856-baf1-4150-b5d9-2ac1bc4551b7)
Worker Node:
![worker_node](https://github.com/ray-project/ray/assets/61617389/1e1351fc-a545-4314-9a77-b8bf7cc6ce88)

### Versions / Dependencies

ray 2.4.0

### Reproduction script

It will take an additional 1-2 weeks to create a minimal script, since we cannot provide the source code.

### Issue Severity

High: It blocks me from completing my task.

**Comment by larrylian** [comment]
@Lorien2027 
1. Do you have a way to core dump the process's memory and analyze which memory block is growing?
2. Do you use placement groups?
3. Do you have a way to monitor the memory size of Ray object store?
4. Your actors are always resident, right? You don't frequently create new actors, right?

**Comment by xieus** [comment]
Great analysis. 

cc: @scv119 @iycheng

**Comment by Lorien2027** [comment]
We also observed in ray 2.3 an increase in raylet memory without changing `kill_idle_workers_interval_ms` about 2 months ago. But I don't remember the same for modules at that time (maybe I didn't notice).

**Comment by rkooo567** [comment]
I have a couple more questions. Also, we don't need a exact repro. If you tell us your setup in details, we can build a mock script and test memory usage growth over time. For example, you can tell us sth like 

- X number of actors. X number of nodes.
- X number of requests to X actors
- Run for X hours
- Each request take X time. 
- All the private config change if you made it

Also a couple of additional questions;

1. What do you mean by module 1 & module 2?
2. Does raylet usage growth forever or stop at some point? 

> We disabled autoscaler and also added kill_idle_workers_interval_ms = 0, as we noticed that more than 10 thousand workers were created per day.

This is pretty weird. If there are the same number of actors, workers are not supposed to be created. Is this issue still happening even without autoscaler? Also, what's happening if you don't set kill_idle_workers_interval_ms & just turn off the autoscaler? 

Also the main leak seems to be from the serve controller. cc @sihanwang41 have you seen a similar memory leaking issue? Seems important to fix.

**Comment by Lorien2027** [comment]
@rkooo567 

> X number of actors

20 serve deployment modules, 10 replicas each. A total of 200 actors.

> X number of nodes 

One node with two containers (head and worker). 

> X number of requests to X actors

20 requests constantly to Serve HTTP (FastAPI). When one of the requests is completed, a new one is added. 

> Run for X hours

Minimum 48-72 hours. 

> Each request take X time

From 30 seconds to 3 minutes. 

> All the private config change if you made it

Only `kill_idle_workers_interval_ms = 0`.  

> What do you mean by module 1 & module 2?

Two serve deployment modules (a dashboard with the amount of memory for all their replicas). 

> Does raylet usage growth forever or stop at some point?

 We will check closer to the end of next week, as we will make another launch for a longer period. 

> This is pretty weird. If there are the same number of actors, workers are not supposed to be created. Is this issue still happening even without autoscaler? Also, what's happening if you don't set kill_idle_workers_interval_ms & just turn off the autoscaler?

 Workers are created not for actors, but for the tasks that we call from the actors. In total, 20-40 remote functions are called per request and the default `kill_idle_workers_interval_ms` is 200 ms, which is very small. The exit status of the workers was that they had been idle for too long.

**Comment by Lorien2027** [comment]
I also updated `DEFAULT_LATENCY_BUCKET_MS` in `ray/serve/_private/constants.py` as the default buckets are too small for our processing time.
`DEFAULT_LATENCY_BUCKET_MS = [
    1,
    2,
    5,
    10,
    20,
    50,
    100,
    200,
    500,
    1000,
    2000,
    5000,
    10000,
    15000,
    20000,
    25000,
    30000,
    35000,
    40000,
    45000,
    50000,
    55000,
    60000,
    70000,
    80000,
    90000,
    100000,
    110000,
    120000,
    130000,
    140000,
    150000,
    160000,
    170000,
    180000,
    195000,
    210000,
    225000,
    240000,
    255000,
    270000,
    285000,
    300000,
    315000,
    330000,
    345000,
    360000,
    420000,
    480000,
    540000,
    600000,
    900000,
    1800000,
    3600000
]`

**Comment by shrekris-anyscale** [comment]
@Lorien2027 a few more questions:

1. Do the Ray tasks that get launched on each request contain handles to the Serve deployments?
2. Do the Ray tasks terminate completely once they're finished? Do they release all memory?
3. Do the Serve deployments crash and get restarted often?
4. What's the output of `serve status`? Are all the deployments healthy?

**Comment by shrekris-anyscale** [comment]
For context, it's strange that `ServeContoller:listen_for_change` is growing in memory. [Here's](https://github.com/ray-project/ray/blob/a38ddb1372f9fbba128ea9d19e88b86de8b468f6/python/ray/serve/controller.py#L208-L219) its code. It's only called whenever a `LongPollClient` or reset. `LongPollClients` are initialized in only two places– [the HTTPProxy](https://github.com/ray-project/ray/blob/a38ddb1372f9fbba128ea9d19e88b86de8b468f6/python/ray/serve/_private/http_proxy.py#L348-L354) and the ServeHandle (which contains a [Router](https://github.com/ray-project/ray/blob/a38ddb1372f9fbba128ea9d19e88b86de8b468f6/python/ray/serve/_private/router.py#L408-L417)). If the application is somehow creating a lot of ServeHandles and never freeing them, that could cause this increase.

**Comment by Lorien2027** [comment]
1. No, the only difference is that some functions use a global detached actor, which acts as the `_owner` parameter of the `ray.put` call. We use it in order not to lose references to objects, since we transfer large numpy arrays between different modules. For example, https://github.com/ray-project/ray/issues/12635 . Plasma memory is released automatically at the end of processing. 
2. Yes
3. No
4. They are healthy all the time, according to ray dashboard. The following error is displayed on `serve status` https://github.com/ray-project/ray/issues/34882 .



We checked another cluster that was active for more than 5 days, it processed requests for less than 30 minutes at the very beginning, then no requests were received. Raylet memory has stabilized, while the memory of the remaining components and all Serve Deployment Modules increases over time. This is quite strange in the absence of requests.

Raylet
![raylet](https://github.com/ray-project/ray/assets/61617389/fd916ffb-35b1-4675-91fa-7efd30440721)

listen_for_change
![ray_listen_for_change](https://github.com/ray-project/ray/assets/61617389/a86bd7fc-f2ad-470e-a1ea-607852a173a9)

Ray IDLE
![ray_idle](https://github.com/ray-project/ray/assets/61617389/d2f38b4c-0e5c-4442-abc1-e0caf2e7a7e8)

Agent
![agent](https://github.com/ray-project/ray/assets/61617389/9e3aa0c9-ece6-4368-91da-ebe8b91b2547)

One of Serve Deployment Modules
![module](https://github.com/ray-project/ray/assets/61617389/4a5399fe-77d3-4250-b616-524ee40dd15e)

**Comment by Lorien2027** [comment]
@shrekris-anyscale 
1. A small clarification, we only use the Core API for the global detached actor, for example: 
```
owner = GlobalOwner.options(name="GlobalOwner", lifetime="detached", get_if_exists=True).remote()
ray.get(owner.alive.remote()) # waiting for the creation of an actor
.....
owner = ray.get_actor("GlobalOwner")
data_ref = ray.put(data, _owner=owner)
```

Thus, the Serve API is not used. An interesting point is that the memory of this global actor also increases over time, although no requests are received, and all objects from previous requests have been removed from plasma.

**Comment by hyrmec** [comment]
Hello! I also faced this problem and here is what I dug up on it:
I think that the problem lies in unicorn and according to the comment of the guys in this issue (the problem cannot be fixed for a very long time) it is recommended to replace unicorn with hypercorn.
https://github.com/tiangolo/fastapi/discussions/9082

**Comment by smit-kiri** [comment]
Hi! We're seeing the same issue on our workload with Ray 2.6
Our graphs for each component look the same as mentioned in the description.

We only have one application with 6 deployments and a total of 8 replicas. We do not use FastAPI.
Each deployment is independent and they receive different number of requests, but in total they receive anywhere between 3 - 30 requests / minute in different parts of the day.

We use KubeRay to deploy the service and the memory usage drops every time we deploy a new image. 

The raylet and ServeController usage increases ~150MB / day and HTTPProxyActor usage increases by ~130 MB / day. Memory usage for each deployment is much less, anywhere between ~10 MB to ~30 MB / day.

**Comment by shrekris-anyscale** [comment]
Thanks for posting at @smit-kiri!

> Memory usage for each deployment is much less, anywhere between ~10 MB to ~30 MB / day.

Is the deployment memory usage growing by 10-30 MB each day, or is it roughly constant at that rate?

**Comment by smit-kiri** [comment]
> Thanks for posting at @smit-kiri!
> 
> > Memory usage for each deployment is much less, anywhere between ~10 MB to ~30 MB / day.
> 
> Is the deployment memory usage growing by 10-30 MB each day, or is it roughly constant at that amount?

It flattens out, for example one deployment's usage increased by ~60 MB the first day, ~30 MB in the second day ~20 MB the third day.
We're updating the image pretty frequently right now so we don't have data points for a longer period of time

**Comment by smit-kiri** [comment]
> Thanks for posting at @smit-kiri! I have some follow up questions:
> 
1. Does your Serve app start any other Ray tasks or actors?
> It does not.
2. Roughly how many bytes of data are you sending in your requests?
> 
> 
> Memory usage for each deployment is much less, anywhere between ~10 MB to ~30 MB / day.
> 
3. Is the deployment memory usage growing by 10-30 MB each day, or is it roughly constant at that amount?
> 
> It flattens out, for example one deployment's usage increased by ~60 MB the first day, ~30 MB in the second day ~20 MB the third day.
> We're updating the image pretty frequently right now so we don't have data points for a longer period of time
> 
> 
4. Do the requests usually finish as expected?
> Yes, all requests were successful.
5. Do clients often disconnect before a request is finished?
> Nope.
6. Do requests often get queued up on the proxy?
> Nope.

**Comment by shrekris-anyscale** [comment]
Thanks for the follow-up. Just to clarify

> Roughly how many bytes of data are you sending in your requests?

I was wondering how many bytes were in the body of each request that gets sent to Serve. E.g. if you're including some a text in each request, maybe this is just a few bytes. If you're including images, maybe it's a few megabytes. Could you clarify?

**Comment by smit-kiri** [comment]
> Thanks for the follow-up. Just to clarify
> 
> > Roughly how many bytes of data are you sending in your requests?
> 
> I was wondering how many bytes were in the body of each request that gets sent to Serve. E.g. if you're including some a text in each request, maybe this is just a few bytes. If you're including images, maybe it's a few megabytes. Could you clarify?

Majority (~90%) of the requests have an average text length of ~100 characters. Others have larger text of ~10K characters

**Comment by alexeykudinkin** [comment]
@smit-kiri can you share what uvicorn version you're using?

**Comment by akshay-anyscale** [comment]
hi @smit-kiri / @Lorien2027 we fixed most of the memory leaks in 2.7. Could you try upgrading and let us know if the issues still persist?

**Comment by smit-kiri** [comment]
The head node memory utilization now looks like this, the utilization increases for some time after we deploy a new `RayService` and then it levels off.

![Screenshot 2023-10-30 at 9 30 08 AM](https://github.com/ray-project/ray/assets/98415378/468e0e21-27d8-4da0-979d-b864f079171d)

^Here, I'm using the `ray_node_mem_used` metric, I'm not sure if that is correct. 

![Screenshot 2023-10-30 at 9 48 20 AM](https://github.com/ray-project/ray/assets/98415378/e03f4095-cad1-44e1-afb6-964840d797f1)

^This graph compares the two metrics `sum(ray_node_mem_used{pod="head-pod-name"}) by (pod)` and `sum(ray_component_rss_mb{pod="head-pod-name"} * 1e6) by (pod)`

But in general, looks like the memory leak is fixed!

**Comment by akshay-anyscale** [comment]
thanks for confirming
