### ISSUE TITLE
Recently some tests have been waiting for a long time on the main branch for commits

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35713]
### What happened + What you expected to happen

Some tests have been waiting for over 5 hours to be run on the main branch recently.

This is a bit strange.

<img width="1201" alt="2023-05-24_09-19-40" src="https://github.com/ray-project/ray/assets/46904826/a4a328d3-cb62-43bb-b4fc-02fd593cf022">

### Versions / Dependencies

Main branch

### Reproduction script

Look at a recent commit in the link: https://github.com/ray-project/ray/compare/119e12bb5d1b009f791d7cc4d52bb790196640c7...master

### Issue Severity

Low: It annoys or frustrates me.

**Comment by can-anyscale** [comment]
We double the GPU machines to reduce the load. Feel free to open the issue and let me know if the situation is still annoying.
