### ISSUE TITLE
The c++ compiler is not able to compile a simple test program

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#3575]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 10.13.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: pip install -e . --verbose

### Describe the problem

Installation fails.

### Source code / logs

   -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
    CMake Error at /usr/local/Cellar/cmake/3.13.1/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
      The C++ compiler

        "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

      is not able to compile a simple test program.

      It fails with the following output:

        Change Dir: /Users/eugenevinitsky/Desktop/Research/Bayen/Code/causal-ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeTmp

        Run Build Command:"/usr/bin/make" "cmTC_a6438/fast"
        /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_a6438.dir/build.make CMakeFiles/cmTC_a6438.dir/build
        Building CXX object CMakeFiles/cmTC_a6438.dir/testCXXCompiler.cxx.o
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6   -o CMakeFiles/cmTC_a6438.dir/testCXXCompiler.cxx.o -c /Users/eugenevinitsky/Desktop/Research/Bayen/Code/causal-ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
        warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
        1 warning generated.
        Linking CXX executable cmTC_a6438
        /usr/local/Cellar/cmake/3.13.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a6438.dir/link.txt --verbose=1
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_a6438.dir/testCXXCompiler.cxx.o  -o cmTC_a6438
        clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
        ld: library not found for -lstdc++
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make[4]: *** [cmTC_a6438] Error 1
        make[3]: *** [cmTC_a6438/fast] Error 2

**Comment by eugenevinitsky** [comment]
Unclear if this is the same issue as was occurring in: #3413

**Comment by eugenevinitsky** [comment]
Other things that might be helpful:
 Kernel Version: Darwin 17.7.0

**Comment by eugenevinitsky** [comment]
Resolved by reverting to: https://github.com/ray-project/ray/commit/1a926c9b7cd379fd8156e2829ff56290858c743c#diff-fe154a0f53f3f81f170fe583db3611ed

**Comment by robertnishihara** [comment]
I think this issue should be gone now that we're building with Bazel.
