### ISSUE TITLE
master branch unit test issues

### ISSUE THREAD

**Issue by atumanov** [ray-project/ray#3576]
Unit tests intermittently or consistently failing on the master branch:

- [x] `test/stress_tests.py::test_multiple_recursive[4]` stalled/hanging on linux py35 master https://github.com/ray-project/ray/commit/3822b20319536cae6cf1c4b9bf301f778ba2ae82
**Exact command to reproduce**: `python -m pytest -v --durations=10 test/stress_tests.py`
**Python version**: py35
**Ray version**: master https://github.com/ray-project/ray/commit/3822b20319536cae6cf1c4b9bf301f778ba2ae82
**OS**: Linux 
RESOLUTION: (skipped)

- [x] Frequent tune_server_test failure: https://github.com/ray-project/ray/issues/3522 (Richard)
RESOLUTION: Doesn't appear anymore

- [x]  unit test failure on test/component_failures_test.py::test_actor_creation_node_failure: https://github.com/ray-project/ray/issues/3537
RESOLUTION: Doesn't appear anymore

- [ ] `test/component_failures_test.py::test_plasma_store_failed`
   - https://github.com/ray-project/ray/issues/3375
   - Last reported: 1/6 https://api.travis-ci.com/v3/job/168500169/log.txt

- [ ] `test/actor_test.py::test_actors_and_tasks_with_gpus_version_two`
   - last reported: 1/9 https://travis-ci.com/ray-project/ray/jobs/169116474

- [ ] `test/monitor_test.py::test_cleanup_on_driver_exit_many_redis_shards
   - last reported: 1/15 https://travis-ci.com/ray-project/ray/jobs/170421142

- [ ] `test/runtest.py::test_multithreading`
   - last reported: 1/15 https://travis-ci.com/ray-project/ray/jobs/170694875
### Describe the problem
I'll use this issue to keep track of unit test failures on the master branch

**Comment by robertnishihara** [comment]
Thanks @atumanov, note there are also a number of test failures documented in https://github.com/ray-project/ray/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22test+failure%22+ and the Jenkins tests have been failing pretty consistently recently.

**Comment by guoyuhong** [comment]
@robertnishihara  How about use the change in https://github.com/ray-project/ray/pull/3569/files . I run 10 time for this test use `-s` option. It looks like the time is normal.
```
max: 282.50s call     test/stress_tests.py::test_multiple_recursive[4]
min: 85.89s call     test/stress_tests.py::test_multiple_recursive[4]
```
We can mitigate the problem first.

**Comment by simon-mo** [comment]
These tests are all fixed now, tracking them at https://ray-travis-tracker.herokuapp.com/
