### ISSUE TITLE
"ray/python/ray/tune/integration/wandb.py" should be removed

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35781]
### What happened + What you expected to happen

ray/python/ray/tune/integration/wandb.py has a comment at the top of the file saying: # Deprecated: Remove whole file in 2.5

The current version of ray is 2.5, so this should be removed.

### Versions / Dependencies

Main branch

### Reproduction script

Look at: "ray/python/ray/tune/integration/wandb.py"

### Issue Severity

Low: It annoys or frustrates me.

**Comment by krfricke** [comment]
Thanks, fixing in #36860
