### ISSUE TITLE
[Train] `trainer.pkl` file should not keep the `resume_from_checkpoint` field 

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#35813]
### What happened + What you expected to happen

To allow restoration, the args passed into a `BaseTrainer` are saved as a `trainer.pkl` file. However, `resume_from_checkpoint` should not be saved, as `Trainer.restore()` just resumes from the latest checkpoint, ignoring the choice.

This is especially bad if the checkpoint is really large.

### Versions / Dependencies

2.4

### Reproduction script

todo

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
@justinvyu what happens if there are no checkpoints?

**Comment by justinvyu** [comment]
Looks like if no checkpoint is found by Tune, then the trainer will use this saved `resume_from_checkpoint`. So it may not be correct to drop this field, since then the run would start from scratch rather than the `resume_from_checkpoint`.

The problem is probably better described as:
* If `resume_from_checkpoint` is a directory backed checkpoint, then pickling it will serialize the full directory contents as a dict, then dump that to the `trainer.pkl` file.
* The node to node transfer serialization logic is being used here unintentionally.

The `resume_from_checkpoint` behavior makes more sense to configure in the training loop rather than needing users to user `Trainer.restore` along with `resume_from_checkpoint`. For example:
1. For `HuggingFaceTrainer`, I'll just create an init function that uses `AutoModel.from_pretrained` to initialize a model with pretrained weights.
2. For `TorchTrainer`, I can initialize my model however I want.
3. I think `LightningTrainer`, `XGBoostTrainer`, and `LightGBMTrainer` are the only ones that cannot customize the model initialization easily right now.

**Comment by justinvyu** [comment]
No longer relevant after new `Checkpoint` API in 2.7+.
