### ISSUE TITLE
[Job] Ray job in Running status despite the actual script completing

### ISSUE THREAD

**Issue by hanyuyangddgh** [ray-project/ray#35827]
### What happened + What you expected to happen

The script completed in 3 mins, but the Ray job status is still in Running after 30 mins, see the screenshot below:

![image](https://github.com/ray-project/ray/assets/110043060/0aa9ced8-a2c0-4e81-bbb8-e19188689ae9)

Here are the CLI output and log files you requested:
```
(base) ray@lucent-canary-05252023-210839-head-njvh7:~$ ray job list
Job submission server address: http://10.4.143.25:8080/
[JobDetails(type=<JobType.SUBMISSION: 'SUBMISSION'>, entrypoint='python forecasting_job.py XXX', job_id='02000000', submission_id='raysubmit_M5Khhh4MxjxwUUk7', driver_info=DriverInfo(id='02000000', node_ip_address='10.4.143.25', pid='2659'), status=<JobStatus.RUNNING: 'RUNNING'>, message='Job is currently running.', error_type=None, start_time=1685049676881, end_time=None, metadata={}, runtime_env={'working_dir': 'gcs://_ray_pkg_187761afbf32a071.zip', 'excludes': ['.cache', '.direnv'], 'pip': {'packages': ['forecast-factory>=12'], 'pip_check': False}, 'env_vars': {'LUCENT_TRAINING_ENVIRONMENT': 'job'}, '_ray_commit': 'cf7a56b4b0b648c324722df7c99c168e92ff0b45'}, driver_agent_http_address='http://10.4.143.25:52365/', driver_node_id='40bf4f728dfb667209907464efaa796b578377ec348c622feaf8888e')]
(base) ray@lucent-canary-05252023-210839-head-njvh7:~$ ray job status raysubmit_M5Khhh4MxjxwUUk7
Job submission server address: http://10.4.143.25:8080/
Status for job 'raysubmit_M5Khhh4MxjxwUUk7': RUNNING
Status message: Job is currently running.
```

[dashboard_agent.log](https://github.com/ray-project/ray/files/11578242/dashboard_agent.log)
[dashboard.log](https://github.com/ray-project/ray/files/11578243/dashboard.log)

### Versions / Dependencies

839591177169.dkr.ecr.us-west-2.amazonaws.com/open-source-mirror/dockerhub/rayproject/ray-ml:2.4.0-py38-gpu

### Reproduction script

Slack channel context: https://ray-distributed.slack.com/archives/C03EFLGKN56/p1679406788051519

### Issue Severity

High: It blocks me from completing my task.

**Comment by alanwguo** [comment]
do you mind also sharing your script @hanyuyangddgh ?

**Comment by architkulkarni** [comment]
cc @akshay-anyscale for triage

**Comment by architkulkarni** [comment]
I think we concluded offline that this wasn't an issue with Ray Job API, and it's still unclear if the failure of the script to exit is related to Ray or if it's just from application code.  @hanyuyangddgh do you mind updating this issue with the latest status of your debugging?

**Comment by anyscalesam** [comment]
@hanyuyangddgh please re-open if this is an issue on latest ray.
