### ISSUE TITLE
[Core] Ray build fails with gcc-13

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#35832]
### What happened + What you expected to happen

Ray currently fails to build with gcc-13. See https://github.com/ray-project/ray/issues/35200 for more information.

### Versions / Dependencies

Ray: Most recent commit on `master` (3d124ccaba5582ef9aa39ddbc5e7851d9a78c656)
Python: Tried with 3.10.8 and 3.11.2, but I think it doesn't matter
OS: Linux 6.3.4-arch1-1 x86_64
gcc: 13.x

### Reproduction script

Calling `pip install -v .[all]` inside `ray/python` will fail with gcc-13. Although the docs do explicitly say to build with gcc-9, I've been able to build with later versions including gcc-12.

I tested a few minutes ago, and as a workaround setting `CC` to an older version (and possibly doing a `bazel clean --expunge`) will allow the project to build.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by aslonnie** [comment]
it is all updated to use clang-12 now.
