### ISSUE TITLE
[Core] [FR] Access actor name (and other options) from within the actor

### ISSUE THREAD

**Issue by erezinman** [ray-project/ray#35849]
### Description

I wish to access the actor's metadata from within the actor (e.g. for logging purposes), and specifically the named actor's name.

### Use case

For example, for logging, I wish I could do:

```python
import ray
import ray.actor
import loguru

@ray.remote
class Actor:
    def __init__(self):
        actor_name = ray.actor.get_current_actor_options()['name']  # OR
        actor_name = ray.actor.get_current_actor_name()
        loguru.logger.add(sink=f'logs/{actor_name }.log')
```

or similar. Also, PID, worker ID, etc. and other metadata could be nice.

**Comment by rkooo567** [comment]
We have https://docs.ray.io/en/master/ray-core/api/doc/ray.runtime_context.RuntimeContext.html#ray.runtime_context.RuntimeContext. But it seems like accessing actor name & worker id is not supported yet. It is pretty easy, so we welcome contribution!

**Comment by jjyao** [comment]
`get_worker_id()` is already added to RuntimeContext so we just need to add `get_actor_name()`.

**Comment by jonathan-anyscale** [comment]
Feature added!
