### ISSUE TITLE
[core] Kill worker children process even when raylet exits.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#35842]
### What happened + What you expected to happen

Right now, we have policy that when the worker exits, it'll kill all its children otherwise there might be some leak.

But one corner case is that if the raylet died, the worker won't kill itself, but instead it'll just exit which could lead to the worker leak.

There are two cases here:
- Worker crashed
  - which should fail the children too, but is also not easy to fix and needs some os support for it.
- Worker can exit by itself
  - which we should cover because we have control of this.

### Versions / Dependencies

master

### Reproduction script

Refer to this PR https://github.com/ray-project/ray/pull/35840

### Issue Severity

None

**Comment by stephanie-wang** [comment]
I wonder if we should actually do this? For Ray processes, we should definitely clean them up, but I think if the application starts some child processes from a task/actor, arguably we should just follow the normal OS behavior. What do you think, @iycheng ?

**Comment by iycheng** [comment]
@stephanie-wang I think this is just a corner cases which is not covered by https://github.com/ray-project/ray/pull/33976

I think whether to clean up child process or not is an open question.

The [PR](https://github.com/ray-project/ray/pull/33976) covered the cases when ray worker exits, it'll cleanup the children pids. But if the worker crashed, the cleanup is not done. I feel we just need to ensure the behavior is the same.
