### ISSUE TITLE
Release tests long_running_serve_failure.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#35851]
### What happened + What you expected to happen

Release tests long_running_serve_failure.aws failed on release 2.5.0 branch, and I think on master too
- https://buildkite.com/ray-project/release-tests-branch/builds/1705#_

### Versions / Dependencies

master
release 2.5.0

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by aslonnie** [comment]
https://buildkite.com/ray-project/release-tests-branch/builds/1705#01885ee3-a9b3-48ee-a96f-75e0b7c8eb1a
