### ISSUE TITLE
[Metrics] Using an incorrect autoscaler metrics for the dashboard.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#35864]
### What happened + What you expected to happen

Currently, the dashboard uses the incorrect autoscaler metrics that are leaking. We should replace metrics. See https://github.com/ray-project/ray/pull/34471#issuecomment-1512271755 for more details.

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @zhe-thoughts we should've fixed this by 2.5, but this was slipped (mostly due to me having an interrupt around the end of the release). Do you think this is reasonable to pick? Without this fix, the dashboard metrics in the main overview page will have a leaking # of nodes. I think we should fix this. cc @scottsun94. It is almost done, and I can make a PR today.

**Comment by scottsun94** [comment]
I think we should checkrrypick this since mutiple internal people have reported this in the dogfooding of batch cuj and other cujs. This is such an obvious mistake that probably a lot of people will run into.

**Comment by zhe-thoughts** [comment]
Thanks for working on this @rkooo567 . Where is the PR link?
