### ISSUE TITLE
Removal from ray 1.8 has not happened yet

### ISSUE THREAD

**Issue by ollie-iterators** [ray-project/ray#35888]
### What happened + What you expected to happen

In the file: "ray/src/ray/common/ray_config_def.h", there is a TODO statement that says that RAY_CONFIG(bool, legacy_scheduler_warnings, false) should be removed after Ray 1.8.

This has not happened yet and ray is in version 2.4 going on 2.5.

### Versions / Dependencies

main branch

### Reproduction script

Look at "ray/src/ray/common/ray_config_def.h"

### Issue Severity

Low: It annoys or frustrates me.

**Comment by can-anyscale** [comment]
@hora-anyscale: I think this should go to one of the OSS team but I'm not sure who, maybe core?

**Comment by jjyao** [comment]
It's removed now.
