### ISSUE TITLE
Better error message for "The task with ID x is a driver task and so the object created by ray.put could not be reconstructed."

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#3588]
### Describe the problem

I would like a better error message for the following errors:

```The task with ID 00000000xxx is a driver task and so the object created by ray.put could not be reconstructed.```

This error will print indefinitely and multiple Modin users report this issue. 

- It would be nice to throw an exception. This way, we could catch the error an potentially throw our own.
- I would like to have more information about which lines of code are causing this error. There are many places where we `ray.put`, and for debugging purposes I would like to have some (even small) trace of the origin of the object.

### Source code / logs

```python
import ray
ray.init(object_store_memory=2**20) # small object store to simulate 
import modin.pandas as pd
import numpy as np

frame_data = np.random.randint(0, 100, size=(1000, 100))
df = pd.DataFrame(frame_data)
print(df)
```

**Comment by richardliaw** [comment]
Hm, I think this is no longer an error message that we report. Do please open a new issue if you see this again.
