### ISSUE TITLE
[Doc] Remove stale Lightning docs and released tests

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#35893]
### Description

As we are migrating from ray_lightning to LightningTrainer, it becomes necessary to eliminate the old documentation to minimize any confusion for our users. Additionally, we should also remove the release tests for ray_lightning to streamline the testing process.

**Comment by ddelange** [comment]
Hi :wave:

Is there more info or relevant issues concerning `ray_lightning` deprecation you could link to?

**Comment by matthewdeng** [comment]
https://github.com/ray-project/ray_lightning/issues/258
