### ISSUE TITLE
[KubeRay] Ray autoscaler spawns hundreds of pods

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/ray#35901]
### What happened + What you expected to happen

Ray's autoscaler continues to create pods on unhealthy nodes, the pods become stuck in pending, the autoscaler retries, and then a large amount of pods are stuck in pending. Seeing over 100s of pods stuck in this pending state.

Back referencing this issue since code is maintained in this repository, not Kuberay. https://github.com/ray-project/kuberay/issues/1108

### Versions / Dependencies

Python 3.9
Ray 2.4.0

### Reproduction script

Submit a Ray job that is forced to schedule onto an unhealthy GPU node.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
cc @kevin85421

**Comment by peterghaddad** [comment]
Hi @kevin85421 happy to take a poke at this issue and create a PR. Any thoughts on best approach given the autoscaler's current implementation?
