### ISSUE TITLE
[Train/Tune] Trainable keeps multiple copies of model checkpoint which might cause OOM.

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#35918]
### What happened + What you expected to happen

We observed that the head node used an unusually large amount of memory during model training. The user is using LightningTrainer with a 3GB model, while the head node is using over 12 GB of memory. 

After some investigating, we discovered that we have multiple copies of byte-type AIR checkpoint in the Trainable(2x) and Tuner(1x), which is causing the issue. The workaround is to schedule the Trainable on the worker node, so that the head node only has one copy. Eventually, we need to keep as few copies as possible to optimize memory usage.

### Versions / Dependencies

master

### Reproduction script

TODO @woshiyyya add reproducible scripts.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
No longer the case in 2.7+
