### ISSUE TITLE
[CI] `linux://python/ray/tests:test_gcp_node_provider` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#35925]
- 6f2424ffab4bbf30f76a7139811fc1ed3e2f7d00 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4207#01886f20-1c6a-40b3-830d-142c8bf234ed)
- 5b5d83cef97f877d28bafd06360eee58dc37419a FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4206#01886ebd-0bda-4e16-8b6c-09217c8e2d20)
- 04eabd898eeb95f34792a4e298c4fc6018b1a83b FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4205#01886e96-5db3-4f1e-bf5e-bdd37fb564fd)
- 7d52c2fa69d66ce9e05281e4f402f03964bcb7c4 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4204#01886e67-77ab-4139-bba0-5e66c024aa0c)
- 95d0772642f1d5930ee75eaf3c23bd5997a36ea3 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4203#01886e65-2be8-4353-b998-d5ca6593181b)
- afdfb3e9110f98745a5c4cf731893db423fed459 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4202#01886e48-435f-4a42-9754-57d05f18446d)
- 8c3e0b3ca056a2eb4150a893a6ee127595d0285c FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4200#01886ddf-5aa8-4ec2-ba26-c30abcd9045d)
- 4105241579a6c3a18eec905ac15b81fc322cad5a FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4199#01886dde-c444-454c-b58d-0ea0e049729b)
- 9ba2a9ba1c2019011df1f60e71b956c463db7e3c FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4198#01886ddd-92ef-4f7c-88b6-43a324b2e132)
- 2da356f62b3da96374f01fbd0575f8f65453f162 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4197#01886ddb-cbe6-4b89-89cd-831782e361d7)
- e5d8b28f53fb1b8f6cb7d1220886617eb9a3fc07 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4196#01886dbc-c88a-4874-a357-6a4dee6ca728)
- 44de9b7044d4919c420222dedc1c4a0de6aab185 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4195#01886dbc-e967-4528-9d5a-2915dea21296)
- d4a89008950b7a03cd6b721026cc4cb59b1b1c31 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4194#01886db2-687b-400b-b800-fcd0a3d133e9)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_gcp_node_provider-END
....

**Comment by bveeramani** [comment]
Closed by #35910
