### ISSUE TITLE
[Serve] Introduce new deployment state in the deployment for autoscaling. 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#35948]
### Description

Currently autoscaling event will trigger deployment to be 'UPDATING'. 

It is useful to differentiate the autoscaling state out of the UPDATING state for better observability. (Sometimes autoscaling will trigger too often, it will cause confusion to the user.)

**Comment by edoakes** [comment]
Simplest version is to just avoid state changing to `UPDATING` on autoscaling changes
