### ISSUE TITLE
[tune] Broken examples on latest docs

### ISSUE THREAD

**Issue by justusschock** [ray-project/ray#3598]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.0
- **Python version**: 3.7
- **Exact command to reproduce**:  `from ray.tune import sample_from`

### Describe the problem
Commit #3457 adds tune.sample_from, which is already used in the [examples of 0.6.0](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch.py) but not introduced in 0.6.0 binaries via pip

Could you either update the binaries or provide a workaround?

Thanks in advance!

**Comment by jstamand** [comment]
I've got the same issue.

I tried building from source and that doesn't work either...

**Comment by richardliaw** [comment]
Thanks for reporting this! The fast workaround is to install a latest snapshot of master from here: https://ray.readthedocs.io/en/latest/installation.html

I'll add a note into the examples page indicating that you may need the latest snapshot of master for them to work.

I'll close this issue for now, and feel free to reopen if any other issues arise.
