### ISSUE TITLE
[Jobs] Append error traceback to job driver log

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#35997]
### Description

Currently, the output of the `entrypoint` script in a Ray Job is streamed to the log file `job-driver-[submission_id].log` on disk.  In particular, if there is an exception raised in the script, the traceback will appear in the log file with no additional work needed.

However, if there's an internal error that happens before the `entrypoint` script is executed (for example, if the runtime environment fails to set up for the `JobSupervisor` actor, or if there is some other error) then the details only appear in the `JobInfo.message` field, not in the log file.

The enhancement request is to always include this traceback in the log file, creating the log file if it doesn't exist.

**Comment by scottsun94** [comment]
This fix will be prioritized after ray summit. cc: @akshay-anyscale
