### ISSUE TITLE
[Data] Empty stats on `StreamSplitDataIterator`s resulting from `streaming_split()`

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#36006]
### What happened + What you expected to happen

The stats are missing (empty string) from `DatasetIterator`s resulting from `streaming_split()`, after execution. See below for reproducible example.

### Versions / Dependencies

Ray master, Python 3.9

### Reproduction script

```import ray; import time

def pause(x):
    time.sleep(.0001)
    return x

ds = ray.data.range(10000)
ds = ds.map(lambda x: x)
ds = ds.map(pause)

@ray.remote
def consume(p):
    for x in p.iter_batches():
        pass

    print("Finish consume")
    stats = p.stats()
    print(f"Emit DatasetStats: {stats}")
    print(type(stats))

a, b = ds.streaming_split(2)
ray.get([consume.remote(a), consume.remote(b)])
```

### Issue Severity

None

**Comment by ericl** [comment]
Will take a look.

**Comment by scottjlee** [comment]
Oh yeah sorry for the notification, I accidentally moved this around in the sprint planning GH project and it reassigned the issue. Thanks

**Comment by ericl** [comment]
Per user report, this doesn't include iterator stats.
