### ISSUE TITLE
How does ray schedule tasks to custom resources?

### ISSUE THREAD

**Issue by wind818** [ray-project/ray#36016]
### Description

A custom resource is defined on the ray cluster head. When using **Ray.remote()**, how does ray identify the existence of a custom resource  resource on the node,

### Use case

`ray start --head --num-cpus=4 --num-gpus=2 --resources='{"special_hardware": 2 --port 2345}' `

Each **special_hardware** is a node, 
how to start the cluster, so that the cluster knows which node has **special_hardware**, 
how to write a script so that ray can call the node with **special_hardware** remotely? And run computation tasks on **special_hardware**

**Comment by rkooo567** [comment]
every Ray resources are actually a string -> float pair. So num_cpus=4 is technically equivalent to "CPU": 4 (also meaning CPU cannot be used for custom resources). 

In terms of scheduling, Ray knows {string -> float} resources from the cluster and just schedules on a node that has the resources (in a simplified way)

For more details regarding scheduling, you can see https://docs.ray.io/en/latest/ray-contribute/whitepaper.html#whitepaper.

**Comment by rkooo567** [comment]
I will close the issue as it is a question. Please follow up with me if you have any other question!
