### ISSUE TITLE
[Serve] graceful_shutdown_timeout_s is not working

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#36022]
### What happened + What you expected to happen

```
from ray import serve

@serve.deployment(graceful_shutdown_timeout_s=9999)
def fn():
    return

serve.run(fn.bind())

serve.delete("default")
```

Deletion finish very fast.

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by edoakes** [comment]
@sihanwang41 I think it's working as expected. This is the timeout after which to give up graceful shutdown and force-kill the actor. In your code sample, there are no requests outstanding so graceful shutdown will complete quickly.

To test the logic you need to have `__del__` hang or a request pending forever.

**Comment by sihanwang41** [comment]
I printed inside the code, I get 2 seconds here https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L682

**Comment by sihanwang41** [comment]
mis used the variable :)
