### ISSUE TITLE
[core] Primary copies are spilled when secondary copies could have been evicted

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#36044]
When running workloads that read secondary copies onto a node, Ray seems to sometimes spill primary copies on the node before it evicts secondary copies on the node. This leads to unnecessary spilling, since evicting secondary copies doesn't spill.

The following can reproduce the issue on a 6-node cluster (with total ~200GB object store memory, plenty to fit all the objects without spilling):

```
import ray
import numpy as np

# Spread data onto all nodes.
@ray.remote
def gen():
    return np.ones(1024 * 1024 * 1024, dtype=np.uint8)

refs = [gen.options(scheduling_strategy="SPREAD").remote() for _ in range(50)]  # 50GiB

# Iterate over the data on the worker nodes from the head node.
for i in range(10):
    for j, r in enumerate(refs):
        print("Iteration", i, j)
        ray.get(r)

```

![Screenshot from 2023-06-02 14-56-18](https://github.com/ray-project/ray/assets/14922/c2352e10-2c8c-441a-9407-6a93f6d42473)

You can see that a small fraction of the memory is spilled, which is not necessary. The spilling doesn't happen if you prevent the tasks from running on the head node, suggesting that the spilling is only due to primary copies created on that node.

**Comment by ericl** [comment]
FYI @c21 this reproduces the issue you were debugging earlier in just core

**Comment by c21** [comment]
The user impacted is able to work around, so it's not blocking them. btw this happens in the context of Ray Data+Train without streaming split integration. Do not think this is a release blocker for Ray 2.7 for now.
