### ISSUE TITLE
[Tune] TypeError: run() got an unexpected keyword argument 'storage_path'

### ISSUE THREAD

**Issue by ericbhanson** [ray-project/ray#36061]
### What happened + What you expected to happen

Trying to adapt the example at https://pytorch.org/tutorials//beginner/hyperparameter_tuning_tutorial.html to restore experiments in case of a machine failure, as I'm using free cloud resources that can be interrupted before my model is finished to run my code. I am setting the storage_path='path/to/dir' as explained in the help text of https://github.com/ray-project/ray/blob/master/python/ray/tune/tune.py, but I get an TypeError: run() got an unexpected keyword argument 'storage_path' error from Python when doing so. 

### Versions / Dependencies

Ray: 2.4.0
Python: 3.9.16

### Reproduction script

`result = tune.run( partial(cifar, data_dir=data_dir), resources_per_trial={"cpu": 5, "gpu": gpus_per_trial}, config=config, num_samples=num_samples, scheduler=scheduler, resume='AUTO', storage_path=data_dir, )`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by justinvyu** [comment]
@ericbhanson 

`storage_path` was introduced in 2.5.0. If you upgrade the Ray version, it should solve your problem.

The argument was `local_path` in versions <= 2.4. Closing for now -- feel free to re-open if this doesn't solve the issue.
