### ISSUE TITLE
[AIR] Checkpoints get uploaded twice in the cloud checkpointing case.

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#36074]
### What happened + What you expected to happen

Currently, if the trainer saves the checkpoint in the trial directory first, and then reports to the session, we upload both of them to cloud storage. This is unnecessary, so we need to filter out the unnecessary files and only upload the ones we need. The current workaround is to save ckpt outside working dir/trial dir.

### Versions / Dependencies

master

### Reproduction script

```python

def train_loop():
    torch.save(dummy_checkpoint, 'dummy_checkpoint.pth')
    ckpt = TorchCheckpoint.from_dict(dummy_checkpoint)
    session.report(metrics={"a": 1}, checkpoint=ckpt)

trainer = ray.train.torch.TorchTrainer(
    train_loop_per_worker=train_loop,
    storage_path=YOUR_S3_BUCKET_URI,
    scaling_config=ray.air.config.ScalingConfig(
        # `num_workers` is the total number of GPUs.
        num_workers=2,
        use_gpu=False,
    ),
)
trainer.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by justinvyu** [comment]
Trial artifacts are not uploaded by default anymore. New temporary directory pattern recommended in docs examples avoids this problem: https://docs.ray.io/en/latest/train/user-guides/checkpoints.html#saving-checkpoints-during-training
