### ISSUE TITLE
[serve] distinguish A100-80 GB and A100-40GB in automatic resource detection

### ISSUE THREAD

**Issue by shayanhoshyari** [ray-project/ray#36131]
### Description

Ray init will automatically detect NVIDIA gpu accelerators https://github.com/ray-project/ray/commits/master/python/ray/util/accelerators/accelerators.py. However, it does not distinguish between 40GB and 80GB memory A100 gpus (i.e. the P4D and P4De amazon EC2 instances).

This can cause issues as a deployment with accelerator_type=A100 and num_gpu = 1 might get a 40GB or a 80GB share.

The request here is to distinguish these accelerator types.

### Use case

When both P4D and P4De are available in a cluster, this will ensure a deployment lands on the correct node; and have correct GPU share to use.

**Comment by movchan74** [comment]
Looks like the issue was addressed already: bd620437d85f1205421862c372b688709ae9eb5c
