### ISSUE TITLE
[Core] CPU count in available_resources() does not match CPU count from psutil 

### ISSUE THREAD

**Issue by ericbhanson** [ray-project/ray#36262]
### What happened + What you expected to happen

I'm running Ray Tune on a Paperspace machine that has 8 CPUs, but I noticed from the Tune dashboard that there are only 5 CPUs available. If I run `psutil.cpu_count(logical=False)` or `psutil.cpu_count(logical=True)` I get a CPU count of 8 as expected, but if I run `ray.init()` and then `ray.available_resources()`, I get a CPU count of 5.

### Versions / Dependencies

Python: 3.9.16
Ray: 2.40

### Reproduction script

import psutil
import ray

print(psutil.cpu_count(logical=False))
print(psutil.cpu_count(logical=True))

ray.available_resources()

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericbhanson** [comment]
@scv119 It’s running inside of a Jupyter notebook. Otherwise I’m not aware of anything else running.

**Comment by ericbhanson** [comment]
@scv119 I just tried running it within a terminal inside of Paperspace's interface and I'm getting the same CPU count.

**Comment by ericbhanson** [comment]
Also I want to note that I'm now running on Ray 2.5 instead of 2.4.

**Comment by rickyyx** [comment]
Thanks @ericbhanson ! I will try repro on my end.

**Comment by ericbhanson** [comment]
Not sure why, but a more recent release seems to have fixed the issue, as I'm no longer seeing. Closing...
