### ISSUE TITLE
[Dashboard] Add datasource param for grafana dashboard

### ISSUE THREAD

**Issue by jiwq** [ray-project/ray#36300]
### Description

We had some K8s clusters run ray clusters, and each K8s cluster had one Prometheus and share the same Grafana, but ray not support this scenario.

In here, we propose a feature add datasource param for Grafana dashboard.

### Use case

We use the `R` as the the Ray Cluster, and `K` as the K8s cluster, and `P` as the prometheus cluster, and `G` as the Grafana.

R1 run on K1 and use P1 to collect the metrics. R2 run on K2 and use P2 to collect the metrics. Now, we only use G1 to view all the cluster's metrics by only switch the dashboard's datasource.

**Comment by alanwguo** [comment]
Thanks for taking this on!
