### ISSUE TITLE
[Ray Train] Explain how to set timeout when using PyTorch Lightning Trainer 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36315]
### Description

It seems that users need to set `timeout` using [torchConfig](https://docs.ray.io/en/latest/train/api/doc/ray.train.torch.TorchConfig.html?highlight=torch_config).

It's not clear when I should set it in ray.train.lightning.LightningConfigBuilder.strategy or in TorchCnfig.

**Comment by scottsun94** [comment]
cc: @woshiyyya @matthewdeng

**Comment by woshiyyya** [comment]
Yeah that's a problem, and I think this is action item of unifying configurations for lightning and AIR.

Currently we have two sets of configuration for Lightning and Ray AIR (checkpoint configs, backend configs, and scaling configs), which makes it hard for users to figure out the right place to provide them. 

The ideal state from my mind is the user only need to provide lightning config, and we'll create a corresponding AIR config for them. But still there are many details to consider. I can draft a proposal on this topic later.

**Comment by scottsun94** [comment]
This should be straightforward in 2.7? @woshiyyya

**Comment by woshiyyya** [comment]
For the new API, they still need to specify timeouts in `TorchConfig` instead of `RayDDPStrategy`. 

I think we still need to update the docstring for RayDDPStrategy to clarify this.
