### ISSUE TITLE
[Train] Improve Pytorch Lightning Trainer's W&B integration example

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36311]
### Description

People with private W&B instances need to do` wandb.login(key=…, host=<private W&B instance URL>)` for it to work properly in the `WandbLoginCallback`.

We should mention it in this [example](https://github.com/ray-project/ray/blob/3e21650b60d714cb03677b20e5dd0fdf5862aa5a/doc/source/train/examples/lightning/lightning_exp_tracking.ipynb) or other examples we talk about `wandb.login`.

**Comment by scottsun94** [comment]
@woshiyyya @matthewdeng

**Comment by woshiyyya** [comment]
Actually I think it's something that the users should know. They should log into their private wandb server with host_ip even without ray. But yeah, I think it's a plus to mention it in our docs.

**Comment by scottsun94** [comment]
Shall we close it now? @woshiyyya

**Comment by woshiyyya** [comment]
Yes we already have a user guide for experiment tracking. Let's close this.
