### ISSUE TITLE
[docs] fix all :book: Documentation CI failures 

### ISSUE THREAD

**Issue by maxpumperla** [ray-project/ray#36323]
### What happened + What you expected to happen

After reactivating strict builds in https://github.com/ray-project/ray/pull/36206, we now have a couple of previously hidden errors and warnings in CI that we should fix as soon as possible. I'm grouping the types of issues I see for better allocation:

- [x] Issues with the `MOCK` directive in Core,  Data and Observability:

```
/ray/doc/source/data/inspecting-data.rst:117: WARNING: 'MOCK' is not a valid option.
...
/ray/doc/source/ray-core/actors/async_api.rst:52: WARNING: 'MOCK' is not a valid option.
...
  | /ray/python/ray/runtime_context.py:docstring of ray.runtime_context.RuntimeContext.get_task_id:28: WARNING: 'MOCK' is not a valid option.
  | /ray/python/ray/util/actor_pool.py:docstring of ray.util.actor_pool.ActorPool.get_next_unordered:31: WARNING: 'MOCK' is not a valid option.
  | /ray/python/ray/util/actor_pool.py:docstring of ray.util.actor_pool.ActorPool.map_unordered:32: WARNING: 'MOCK' is not a valid option.
  | /ray/doc/source/ray-core/handling-dependencies.rst:777: WARNING: 'MOCK' is not a valid option.
  | /ray/doc/source/ray-observability/user-guides/debug-apps/general-debugging.rst:121: WARNING: 'MOCK' is not a valid option.
```

- [ ] Autosummary issues in Observability, Serve, Workflows:

```
  | /ray/doc/source/ray-observability/reference/api.rst:22: WARNING: autosummary references excluded document 'ray.util.state.summarize_actors'. Ignored.
...
  | /ray/doc/source/serve/api/index.md:22: WARNING: autosummary references excluded document 'ray.serve.deployment_decorator'. Ignored.
...
  | /ray/doc/source/workflows/api/execution.rst:6: WARNING: autosummary references excluded document 'ray.workflow.run'. Ignored.
```

- [ ] undefined reference in Data:
```
  | /ray/python/ray/data/datasource/datasource.py:docstring of ray.data.datasource.datasource.Datasource:12: WARNING: undefined label: custom_datasources
```

- [x] undefined reference in Core:

```
  | /ray/doc/source/ray-core/handling-dependencies.rst:686: WARNING: undefined label: runtime-env-auth
```

- [x] Weird issue in Tune (didn't find the root cause):
```
  | source/tune/examples/experiment-tracking.rst:4: WARNING: duplicate label tune-experiment-tracking-ref, other instance in /ray/doc/source/tune/examples/experiment-tracking.rst
```

### Versions / Dependencies

master

### Reproduction script

make html

### Issue Severity

None

**Comment by maxpumperla** [comment]
#36359 the `MOCK` warnings seem to have already been addressed, which by the numbers were the predominant failure here.

**Comment by angelinalg** [comment]
I'll take a look at the observability ones as they are likely from the restructuring work I did for 2.5.

**Comment by angelinalg** [comment]
Hmm...I was wrong. The observability ones don't seem to be something I know how to fix. @rkooo567, would you take a look? I can fix if I did cause them. I just need some guidance.

**Comment by rickyyx** [comment]
@maxpumperla - is this caued by this? https://github.com/ray-project/ray/blame/319080c9350b3634c40aa63fa3ca8e02365bb161/doc/source/conf.py#L191
