### ISSUE TITLE
[core] Actor creation throughput has gone down since June 7

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#36342]
### What happened + What you expected to happen

Throughput seems to have dipped over the past 5 days.

### Versions / Dependencies

Current

### Reproduction script

<img width="373" alt="Screenshot 2023-06-12 at 2 09 51 PM" src="https://github.com/ray-project/ray/assets/7005244/cac72a76-34b9-41a9-bbb4-5fef9fd7a4c6">

### Issue Severity

None

**Comment by scv119** [comment]
let's observe for a little bit longer

**Comment by xieus** [comment]
The Actor creation throughput went back up above 800 since June 30th and remains above the threshold. I think we can close this ticket. 

cc: @scv119 

![image](https://github.com/ray-project/ray/assets/12957223/6164eb0b-a42b-4e17-a9d5-55344f4fe20d)

**Comment by jjyao** [comment]
It's good now.
