### ISSUE TITLE
[Core] Cluster hangs when prestart_worker_first_driver is true

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#36349]
### What happened + What you expected to happen

When RAY_prestart_worker_first_driver is set to true, the cluster hangs. Seems to have been introduced by: 
 
https://github.com/ray-project/ray/commit/f3bd6c0009a7ae53488148b51457c8d6ebee6f97

### Versions / Dependencies

Nightly 2.5

### Reproduction script

https://ray-distributed.slack.com/archives/C04JR4HHEUS/p1686360576974809 for more information

### Issue Severity

None

**Comment by scv119** [comment]
note the user already have a work around

**Comment by rickyyx** [comment]
Asking for a repro.
