### ISSUE TITLE
Custom Resources from using `ray start` in CLI do not work as intended

### ISSUE THREAD

**Issue by lavkeshg** [ray-project/ray#36374]
Running into an issue where the examples for custom resources do not work in Powershell as intended.

`ray start --head --num-cpus=3 --num-gpus=4 --resources='{"special_hardware": 1, "custom_label": 1}'`

Should be straightforward enough, however it yields the following response,
`--resources` is not a valid JSON string.
Valid values look like this: `--resources='{"CustomResource3": 1, "CustomResource2": 2}}'`

I have also tried the example for "valid" values suggested in the error response,
`ray start --head --resources='{"CustomResource3": 1, "CustomResource2": 2}}'`

This yields the exact same error as well.

I have also tried wrapping the whole text further within quotes looking at some other issues, like so, 
`ray start --head --num-cpus=3 --num-gpus=4 --resources="'{ \"special_hardware\": 1, \"custom_label\": 1 }'"`
this didn't help either

I have attached the `environment.yml` used here.

`environment.yml`
`name: ray_unpack
channels:
  default
dependencies:
  python=3.8
  pip
  pip:
    - -r requirements.txt`
  
`requirements.txt`
`joblib==1.2.0
numpy==1.24.0
pandas==1.5.2
psycopg2==2.9.5
PyYAML==6.0
ray==2.5.0
SQLAlchemy==1.4.45`

I am running this on PSVersion: 5.1.17763.3770

Thank you!

**Comment by larrylian** [comment]
There is an error in your example above. The following is correct. You can use the following。
```
ray start --head --resources='{"CustomResource3": 1, "CustomResource2": 2}'
```

![image](https://github.com/ray-project/ray/assets/11072802/5c434273-cdb8-4224-9bc2-760dd5292a1d)

**Comment by lavkeshg** [comment]
Thanks for your response! However that didn't work either. The `}}` typo is something I took from what the error suggests. Please see the screenshot below, where I run the line from your response.
![image](https://github.com/ray-project/ray/assets/64500451/e16a1f3a-a313-495a-9c86-4bc941c29558)

**Comment by larrylian** [comment]
1. There is an extra `}` in this error message and we will fix it.
2. You try to remove the space in the middle.
![image](https://github.com/ray-project/ray/assets/11072802/36793994-a99f-4bce-bad3-4776e3c85fcf)

**Comment by lavkeshg** [comment]
removing whitespaces still gives the same issue, see below
![image](https://github.com/ray-project/ray/assets/64500451/2984c465-15da-4eb7-b0c3-33d03d58021b)

rather than this back and forth, does this `ray start` operation generate a log file which I can send you? Let me where would I be able to find that. Thank you!

**Comment by larrylian** [comment]
I will try to find a Windows environment and use PowerShell to reproduce the issue you encountered.
This will take a few days to complete.

**Comment by larrylian** [comment]
@lavkeshg  Today i reproduce the issue, you should use follow case:
```
ray start --head --resources='{\"CustomResource3\": 1, \"CustomResource2\": 2}'
```

**Comment by lavkeshg** [comment]
That worked for me! Thank you so much
