### ISSUE TITLE
[Data] Integrate with streaming generator

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#36444]
Today, a task in Ray Data can generates multiple blocks using "yield". But these blocks are not streamed to the downstream ops, because all the object refs will become available only when the task finishes. 

With the new [streaming generator](https://docs.google.com/document/d/1hAASLe2sCoay23raqxqwJdSDiJWNMcNhlTwWJXsJOU4/edit#heading=h.w91y1fgnpu0m) feature provided by Ray Core, now we can leverage it to stream these blocks. This optimization will be helpful for cases where an operator takes a small input but generates a large output.

**Comment by raulchen** [comment]
#37736 implements the prototype (only task-based map op). 

Microbenchmark results on my local laptop:
- Without streaming generator: total time: 34s, spilled data: 59GB 
- With: total time 17s, spilled data: 16GB

```python
import time

import numpy as np

import ray

ds = ray.data.range(1e6)

def foo(batch):
    data = [
        np.random.randint(0, 100, size=(100, 100), dtype=np.int64) for _ in range(len(batch['id']))
    ]
    return {"id": batch["id"], "data": data}

ds = ds.map_batches(foo, batch_size=100)

start = time.time()
for batch in ds.iter_batches():
    pass
print(time.time() - start)
```

**Comment by rkooo567** [comment]
> ideally, if when enabling streaming gen, there should be no spilling. Potential reasons: 1) streaming gen doesn't support back-pressure; 2) After data is consumed by "iter_batches", we don't release the objects quickly enough.

IIRC, if you add `del batch`, it is GC'ed immediately. Maybe it is something that should be transparently handled by the streaming generator.

**Comment by rkooo567** [comment]
Based on my observation, the python keeps the scope until the next for is returned from the next yield.

**Comment by raulchen** [comment]
`batch` is already in local memory. We need to free the data in object store. This needs to be done at Ray Data layer. Actually there is already such a mechanism [here](https://github.com/ray-project/ray/blob/585048c6c50934b914b885f25c4d05ba546a5f9a/python/ray/data/_internal/execution/interfaces/ref_bundle.py#L75). However, it's only used in the map op. While in this case, we also need to early free the data [returned by the StreamIterator](https://github.com/ray-project/ray/blob/585048c6c50934b914b885f25c4d05ba546a5f9a/python/ray/data/_internal/execution/streaming_executor.py#L116). 

I did a quick test locally, with the following patch. Total time for the `N=100k` **reduced from 134s to 0.7s** (when streaming gen is enabled). However, when streaming gen is not enabled, there is bug after applying this patch.

```
diff --git a/python/ray/data/_internal/execution/interfaces/ref_bundle.py b/python/ray/data/_internal/execution/interfaces/ref_bundle.py
index a37e5a2913..2a22c9f7b9 100644
--- a/python/ray/data/_internal/execution/interfaces/ref_bundle.py
+++ b/python/ray/data/_internal/execution/interfaces/ref_bundle.py
@@ -110,3 +110,7 @@ class RefBundle:
 
     def __hash__(self) -> int:
         return id(self)
+
+    def __del__(self) -> None:
+        if ray.is_initialized():
+            self.destroy_if_owned()
```

**Comment by raulchen** [comment]
Updating some issues from a large-scale video batch inference benchmark:

1) When using streaming gen, we need to reduce the ray.wait timeout in the streaming executor ([code](https://github.com/ray-project/ray/blob/aed66d22ab0af9f1928334d7bc11fff4e2e6b894/python/ray/data/_internal/execution/streaming_executor_state.py#L325-L329)). Because now data are output much faster, without this change the scheduler becomes the bottleneck. Alternatively, we can also reduce `num_returns`. But what is the reasonable number?
2) [OpState.outqueue_memory_usage](https://github.com/ray-project/ray/blob/aed66d22ab0af9f1928334d7bc11fff4e2e6b894/python/ray/data/_internal/execution/streaming_executor_state.py#L240C9-L240C30) is inefficient and it will be called frequently in the scheduling loop. We can optimize it by caching the value.
3) Consider a `read->preprocess->inference` DAG, the executor will first schedule as many read tasks as possible. These read tasks will exhaust all CPU resources. So even if the read tasks can stream-generate outputs, we don't have other resources to schedule the `preprocess` tasks to consume the outputs. This limitation makes streaming generators (almost) not more useful than non-streaming generators. To solve this issue, we need to limit the concurrent running tasks for each op (based on resource usages or num of tasks).

1) and 2) are fixed, and streaming generator is now slightly more performant. 3) is a larger issue, and not fixed yet.

**Comment by c21** [comment]
It's done.
