### ISSUE TITLE
[Job Detail Page] [Task Table] Allow profiling / stack trace view 

### ISSUE THREAD

**Issue by chaowanggg** [ray-project/ray#36485]
### Description

<img width="911" alt="image" src="https://github.com/ray-project/ray/assets/125417081/a839f777-8fdf-4d3a-b492-8f5438543090">

Where: [jobs/job_id](https://session-c2jy31ze7s6grzd92v66f3c4t1.i.anyscaleuserdata-staging.com/#/jobs/03000000), Task Table
What: 
1. In column `Action`, add profiling / trace stack

- For active task(with a worker id, state_enum begins with "running"), show the track stack/profiling
- For inactive task(without a worker id, state_enum is terminated, killed or pending, finished), do not show the link
- There is a race condition that a task already changed from running to terminated, but the UI is showed in "running", we should show an error if the user access the link

2. in task metadata section, also add one metadata "Action" with two links

**Comment by chaowanggg** [comment]
Let me clarify:

After the refactor of[ task status](https://github.com/ray-project/ray/pull/35138), we now have the status options existed in our codebase:

<img width="744" alt="image" src="https://github.com/ray-project/ray/assets/125417081/23277186-1fbf-4256-8d63-f07796532fac">

1. Here's when we should show "profiling" and "trace stack":
    For an active task, which means it has a worker_id  **AND** its state belongs to [RUNNING, UNKNOWN]
2. And here's when we should not show "profiling" and "trace stack":
   For an inactive task, which means it does not have a worker_id **OR**  its state belongs to [PENDING_ARGS_AVAIL,PENDING_NODE_ASSIGNMENT, SUBMITTED_TO_WORKER, FINISHED, FAILED]
3. Lastly, there is a race condition where a task's state has already changed from "running" to "terminated," but due to API delay, the UI still displays it as "running." In this situation, if there are any errors in the "profiling" and "trace stack" data, we should display the error message.


@alanwguo

**Comment by alanwguo** [comment]
only `RUNNING` should we show the button

**Comment by chaowanggg** [comment]
> for 3, the API will not error if the task is no longer running, this needs to be implemented still.
> 
> The API should implement this logic:
> 
> ```
> it should accept a task_id as an alternative parameter and then:
> 1. check if the task is still running or not.
> 2. if so, find the ip and pid of that task
> 3. do the existing behavior
> ```

Thanks for the detailed info!

**Comment by chaowanggg** [comment]
To clarify, my logic should be as follows:

1. Check if the task is still running.
2. If the task is running, find the IP and PID of that task, and generate a response based on the IP and PID.
3. If the task is not running, the response should be "Error: task is not running and could not fetch traceback/CPU flame graph info," and log an error message.
4. Proceed with the existing behavior: get self._stubs based on the "IP," and generate a response based on the "PID" and "IP."

It seems there might be a conflict between steps 2 and 4. In step 2, we could fetch the IP and PID of the running task, while in step 4, we could also get self._stubs based on the IP and PID of the query

**Comment by alanwguo** [comment]
what's the conflict?

**Comment by alanwguo** [comment]
@rickyyx @rkooo567. What is the best way to get task state info from `reporter_head.py`? Is it to fetch it from GCS? Or should they call state-api from there? Is there an existing pattern for this?

**Comment by rickyyx** [comment]
Maybe having a `StateAPIManager` like https://github.com/ray-project/ray/blob/736060e7344cbfcb5105541baa6e6da1fe72857a/dashboard/modules/state/state_head.py#L513

And calls it's method just like how the `state_head.py` does?

**Comment by alanwguo** [comment]
that sounds good!

**Comment by chaowanggg** [comment]
> what's the conflict?

There are two ways to obtain the IP and PID:

1. Getting them from the task.
2. Fetching them from the query.

The priority should be to directly use the IP and PID from the task. If the task does not provide the IP and PID, we can then use the IP and PID from the query. Is that correct?"

Example code is https://github.com/ray-project/ray/pull/36934/files#diff-3540e3dc6b989a66f62c1d9e6de1cbe39f4db0eb957435fbeef8719fa161c6d2

**Comment by alanwguo** [comment]
We should not use them from the query. The caller should only pass in either (1. task_id, OR 2. PID and IP). That way, the web UI won't need to separately fetch the PID and IP, it can just use the taskId which it already knows.

**Comment by chaowanggg** [comment]
@alanwguo That makes sense! Thanks

**Comment by chaowanggg** [comment]
#37043
