### ISSUE TITLE
[UI] [Serve Replica] Making the log link works

### ISSUE THREAD

**Issue by chaowanggg** [ray-project/ray#36487]
### Description
<img width="1862" alt="image" src="https://github.com/ray-project/ray/assets/125417081/d5f99862-f217-4549-9f2b-cb5065bcf80e">

Where: [Serve Replica](https://session-c2jy31ze7s6grzd92v66f3c4t1.i.anyscaleuserdata-staging.com/#/serve/applications/default/default_DAGDriver/default_DAGDriver%23YaXHho), Tasks History -> Actions -> Log not working

What: Fix the link and make it jump to the task log

To note, I believe the log link is broken for all three pages: ServeReplica, JobDetail and ActorDetail

**Comment by sihanwang41** [comment]
Hi @chaowanggg , could you help to provide more context why it is not working? what log file should be provided? Thx! Basically all the logs files are under /tmp/ray/session_latest/logs/serve.

**Comment by chaowanggg** [comment]
https://github.com/ray-project/ray/pull/36659
