### ISSUE TITLE
[2.5.1] Release test air_example_gptj_deepspeed_fine_tuning.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36507]
### What happened + What you expected to happen

Release test air_example_gptj_deepspeed_fine_tuning.aws failed on 2.5.1

Buildkite: https://buildkite.com/ray-project/release-tests-branch/builds/1803#0188c259-e81b-4e33-8ed5-81d041682814

### Versions / Dependencies

2.5.1

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
This is failing due to datasets not being pinned, and the latest version (2.13.0) breaks our `TransformersTrainer`. This is being fixed on master: https://github.com/ray-project/ray/pull/36276
