### ISSUE TITLE
[2.5.1] Release test air_example_opt_deepspeed_batch_inference failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36506]
### What happened + What you expected to happen

Release test air_example_opt_deepspeed_batch_inference failed on 2.5.1

Buildkite: https://buildkite.com/ray-project/release-tests-branch/builds/1803#0188c475-ef1e-4548-a262-2301fb1b5353

Error:

`ImportError: cannot import name 'deprecate_ndim_indexing' from 'pandas.core.indexers' (/home/ray/anaconda3/lib/python3.9/site-packages/pandas/core/indexers/__init__.py)`

### Versions / Dependencies

2.5.1

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by krfricke** [comment]
Looks like this is the same issue as here: #36505

**Comment by krfricke** [comment]
The 2.5.1 image has the correct pandas version installed and the test is [passing on master](https://buildkite.com/ray-project/release-tests-branch/builds/1807#0188c86c-d99f-43d0-a04c-b50595b73445). I'll close this as fixed.
