### ISSUE TITLE
[Train] Throw error messages if `dataset_iter_config` is not set in LightningTrainer.

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#36509]
### Description

User reports that they found an obscure particularity with the lightning trainer in combination with ray datasets:
The `datasets_iter_config` argument will be None if unset, but this will lead to an obscure error: 

```
TypeError: An invalid dataloader was returned from `RayDataModule.train_dataloader()`. Found <torch.utils.data.dataloader.DataLoader object at 0x7f2280356710>.
```

We should raise an error with clear message to ask the users to provide a `dataset_iter_config`.

**Comment by matthewdeng** [comment]
Should we just use a default value if the user passes in None?

**Comment by woshiyyya** [comment]
Yeah, we can pass a empty dict, which would use the default values defined in [dataset.iter_torch_batches()](https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.iter_torch_batches.html#ray.data.Dataset.iter_torch_batches). 

But I think it's better to make it mandatory when the users provided ray datasets, we don't want to silently set the default batch size for the users.
