### ISSUE TITLE
[Release process] Distribution of responsibilities in cherry picking process not clear

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#36519]
### What happened + What you expected to happen

Our cherry-picking process' rules are not enforced.
This makes it so that, as a release manager, you have to double check on all steps taken by contributers in the cherry-picking process. Most notably, we don't protect the release branch, so it's easy for a release manager to not be aware of PRs that made it into the release branch and be caught off guard by that.

### Versions / Dependencies

any

### Reproduction script

none

### Issue Severity

None

**Comment by hora-anyscale** [comment]
@richardliaw @zhe-thoughts - what do you folks think about making the release branch protected during the Ray release process?

**Comment by zhe-thoughts** [comment]
+1 to do it. I don't see much downside. @ArturNiederfahrenhorst could you suggest the steps we should take to implement this?

**Comment by ArturNiederfahrenhorst** [comment]
According to the instructions at https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule, making a branch protected requires access to the settings of the repository. I don't have this. Do we have someone else than Philipp with these powers @richardliaw  ? 🙂

**Comment by ArturNiederfahrenhorst** [comment]
I can make this part of the revamped release guide. 

Imo a couple of higher-level folks should also be able to merge. 
Maybe Richard, Eric, Zhe, .. to account for out-of-the-ordinary situations.
