### ISSUE TITLE
[Release Process] (possibly) lower the duration of long_running_tests

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36528]
### What happened + What you expected to happen

long_running_tests take too long to run, finish and debug

In particular, during 2.5.0 release, long_running_serve_test failure is one of the 1-day tests that we have. This test has been flaky since the beginning of the release, but two week into the release process, it starts to fail consistently.

The existence of a failure of this type of test will delay the release on average 7 days.

We currently have 16 tests in this long_running class. It would be better if we have less.

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

**Comment by hora-anyscale** [comment]
@sihanwang41 - could you please prioritize fixing the flakiness of long_running_serve_test ?

**Comment by sihanwang41** [comment]
Hi @can-anyscale , are you specifically referring to the serve test? `long_running_tests` include lots of tests. Do you have test name which one takes too long?

**Comment by can-anyscale** [comment]
@sihanwang41 I was referring to long_running_tests in general, but the serve test was the one in particular we running into in 2.5.0 release. For serve test in particular, do we need to run it a day or something like 12 hour is enough?

**Comment by hora-anyscale** [comment]
@Cuong Nguyen ***@***.***> - could you please enumerate all 12 tests
and the teams they belong to in this issue?

~=r

**Comment by can-anyscale** [comment]
@hora-anyscale totally

ml
- long_running_horovod_tune_test
- long_running_many_ppo
- long_running_pbt
- long_running_distributed_pytorch_pbt_failure


core
- long_running_actor_deaths
- long_running_many_actor_tasks
- long_running_many_drivers
- long_running_many_tasks
- long_running_many_tasks_serialized_ids
- long_running_node_failures

rllib
- long_running_apex
- long_running_impala

serve
- long_running_serve
- long_running_serve_failure
- long_running_many_jobs

**Comment by hora-anyscale** [comment]
Thanks Cuong!

@Sihan Wang ***@***.***> - would you be able to audit the Serve
ones to confirm:

1. The test is needed.
2. The duration the test is running is appropriate, if not please adjust to
the correct time.

~=r
