### ISSUE TITLE
[<Ray component: data>] Can't turn off 'Ray Data requires schemas' waring

### ISSUE THREAD

**Issue by stevenhubhub** [ray-project/ray#36574]
### What happened + What you expected to happen

I have changed the parameters as instructed in the following documentation:
ds.iter_batches(batch_format=“numpy”)
https://docs.ray.io/en/master/data/faq.html#migrating-to-strict-mode

But I still get a warning message.

### Versions / Dependencies

python: 3.9.16
os: windows 11 pro
cpu: amd
ray: 2.5.0

### Reproduction script

![image](https://github.com/ray-project/ray/assets/122353354/b9409b33-d2b9-4e12-95ed-08bbedc67471)

### Issue Severity

None

**Comment by bveeramani** [comment]
Hey @stevenhubhub, thanks for opening this issue. Looks like we always raise a warning, even if you're not doing anything wrong.

https://github.com/ray-project/ray/blob/586c376e0769082cb5cfa1333e8264a5fa6b73ec/python/ray/data/dataset.py#L252-L253

**Comment by pcmoritz** [comment]
Sorry for the inconvenience -- we wanted to make sure people don't miss this important API update and we are going to get rid of the warning next release: https://github.com/ray-project/ray/pull/36472
