### ISSUE TITLE
[<Ray component: cluster>] Repeated process message output

### ISSUE THREAD

**Issue by stevenhubhub** [ray-project/ray#36573]
### What happened + What you expected to happen

(ActorName pid=26536) 2023-06-20 21:36:15.603 | ERROR...... [repeated 2x across cluster]
(ActorName pid=6064) 2023-06-20 21:36:15.603 | ERROR ......

### Versions / Dependencies

python: 3.9.16
os: windows 11 pro
cpu: amd
ray: 2.5.0

### Reproduction script

I only set up the code to output a message to the screen once, but when I executed it, I did get repeated output from different Actor processes;
![image](https://github.com/ray-project/ray/assets/122353354/d9203092-2e4e-47fe-86e5-51931c8081a4)

(I'm currently using a local ray instance.)

### Issue Severity

None

**Comment by mattip** [comment]
@stevenhubhub could you copy-paste text not pictures? Please provide a reproducer or at least some idea of what your code looks like. What operating system, what version of python, what version(s) of ray did you try? Where did you get them (it seems there are hints of anaconda, or are you using a miniconda variant)? How did you install ray?
