### ISSUE TITLE
[<Ray component: Data>] streaming_executor.py:149 -- Shutting down

### ISSUE THREAD

**Issue by stevenhubhub** [ray-project/ray#36572]
### What happened + What you expected to happen

2023-06-20 21:21:09,065	INFO streaming_executor.py:149 -- Shutting down <StreamingExecutor(Thread-3, stopped daemon 21792)>.

### Versions / Dependencies

python: 3.9.16
os: windows 11 pro
cpu: amd
ray: 2.5.0 

### Reproduction script

This issue does not exist in version 2.4.0;
When I build a multi-instance task with 2.5.0 I get this red error message, I don't know what it means;

### Issue Severity

None

**Comment by pcmoritz** [comment]
It will be released as part of Ray 2.6. For the time being, it is safe to just ignore the additional message :)
