### ISSUE TITLE
[CI] `linux://python/ray/dashboard:modules/job/tests/test_http_job_server` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#36582]
- 05eea3844a3c980b159d223460e690b3a74b4712 FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4538#0188d87d-d85e-4f0e-8045-a99a40551d25)
- 42e06e3948434d5434cba573bd4ed17eecb0e3c3 FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4537#0188d83c-ae59-43b4-93af-5dc457afdfdb)
- 3eba893933da5da2db7e8a58e911b9d7bab44169 FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4536#0188d809-448c-4d52-8647-c57b195f53cc)
- 344fbe30e14f085fd92de9547f6c909e1d22757d FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4535#0188d7bf-3172-4b58-9898-77f9935073dc)
- 5385b3269c742f482290dd824c2cc34cc794449b FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4534#0188d6ed-c3b6-412d-9f3b-5a11aa38381c)
- 1529f1df549aa5f331010b6691d6bd4e20a2caab FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4533#0188d5ca-606c-4206-bf96-745a70663e86)
- 8290bd112c181769bcdf6cc77572b48697bcee88 FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4532#0188d53a-c311-49ed-9fd2-1ad3d57bd16b)
- d2073615b1cbedb148d792290442e75892e77456 FAILED [Buildkite :serverless: Dashboard Tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4531#0188d4bd-9d52-4d00-b8ca-511509f7137b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/dashboard:modules/job/tests/test_http_job_server-END
....

**Comment by scottjlee** [comment]
Dupes of https://github.com/ray-project/ray/issues/36582 and https://github.com/ray-project/ray/issues/36649, so closing.
