### ISSUE TITLE
[Ray Data] partition_filter on parquet not working as expeted

### ISSUE THREAD

**Issue by camenares** [ray-project/ray#36597]
### What happened + What you expected to happen

1. Setting `partition_filter` when calling `ray.data.read_datasource` with `ParquetDatasource()` read files beyond the`FileExtensionFilter`. 
2.  I would expect files with an extension not `*.parquet` to be ignored by the reader.
3.  See image and logs

<img width="998" alt="image" src="https://github.com/ray-project/ray/assets/32527085/df541f87-341c-4aaa-b098-0ac90567e6ab">

Additionally, if I instead give a path like `paths=["gs://some-gcs/bucket-path/file-path"],` to avoid giving a `partition_filter`,  I get the following error:

```
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/serialization.py", line 369, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/serialization.py", line 275, in _deserialize_object
    return RayError.from_bytes(obj)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/exceptions.py", line 40, in from_bytes
    return RayError.from_ray_exception(ray_exception)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/exceptions.py", line 49, in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
```

### Versions / Dependencies

ray: 2.3.0
python: 3.9
OS: posix/Linux 5.10.176+

### Reproduction script

```python
import ray
from ray.data.datasource import ParquetDatasource

ray.shutdown()
ray.init(
    address="auto",
    runtime_env={"pip": ["tfx_bsl"]},
)

parquet_extension_filter = FileExtensionFilter("parquet")

data = ray.data.read_datasource(
    ParquetDatasource(),
    paths="gs://some-gcs/bucket-path/with-more-than-.parquet",
    filesystem="set-file-system",
    partition_filter=parquet_extension_filter,
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
We no longer use the file extension filter, but instead have a separate parameter `file_extensions` for whitelisting - 

```

ds = ray.data.read_parquet(
    "./examples/data/parquet_images_mini",
    file_extensions=["*.parquet"],
)
print(ds.take(1))
```
