### ISSUE TITLE
[tune] Checkpoint/Restore API for TrialScheduler and SearchAlgorithms

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3659]
### Describe the problem
After #3309, Tune should support saving and restoring state back into the SearchAlgorithm and TrialScheduler as part of the global checkpoint mechanism.

**Comment by krfricke** [comment]
This has been addressed by #9803. Do we need to implement this for schedulers as well or can this be closed?

**Comment by richardliaw** [comment]
I think we can keep this open, there's still a couple search alg/schedulers to be done.
