### ISSUE TITLE
[CI] `bk://:ferris_wheel: Wheels and Jars` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#36603]
- b314206e140b8e644637706378bc17ae7f73ab09 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4550#0188da38-0545-4970-b658-fd05201a5bc6)
- ec72e01908d0c7b96bbf40f370c006f694aa2dc2 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4549#0188da19-f228-4406-8297-498cc43247b0)
- a3ec4a936e8aa09bfac96f30f697c7046fd22a9b FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4548#0188d9fd-2fe0-437e-8fbd-f13bdcb3bd2a)
- fb9faa3e3bd23e396038ea938016bbefb621a016 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4547#0188d9ed-6dec-4798-8023-c37a6d601f1e)
- 9efe17e43decb8e6780097ecc171bff0fc59d7a5 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4546#0188da08-f034-49a4-8b98-c967f8498088)
- efec6610fd54425682766bdc0c234c05bcc5442a FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4545#0188d9de-f399-4d0f-ad65-b0a9bc515a56)
- ce03ce2ecb7d72c313d6f9288a91a8428bb86f16 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4544#0188d9df-0fc1-494e-8812-614e7c7a33c9)
- 1658a42307c5d1d6f25026d2f34cb03b4d2a60d7 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4543#0188d9de-d259-4a73-ac59-5eb4eefe5ba1)
- 9fe4d6f3477dd51868af203b7fc8b0b1395bfb03 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4542#0188d9df-0ebe-4292-88ea-ecae5c880840)
- 3ced85cd933eae4597e93ec12bbd86231e819e99 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4541#0188d9de-a29a-4a92-a6cb-eb9a4b333e48)
- c77ea54576ef641882d13d97b9a47bc532fdcd2d FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4464#0188b694-76cc-4950-8401-dc30b42efb0e)
- 3d0e46e3610a10a4bf74dca7ea5fb3cad67d7b1b FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4460#0188b672-b0d6-4f50-8a04-48cd1f09b9c3)
- 3e5cd965f1b8c62e0e7a4d15aecaf1d2e84d95a6 FAILED [:ferris_wheel: Wheels and Jars](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4455#0188b602-bec2-409e-a2c5-81aedc4ce6b4)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:ferris_wheel: Wheels and Jars-END
....

**Comment by aslonnie** [comment]
the error does not seem to be related to the PR though.

**Comment by aslonnie** [comment]
> the error does not seem to be related to the PR though.

nevermind, I take it back; seems related.
