### ISSUE TITLE
[Serve][Tune]  test_ray_tune_basic test is failing on master

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#36649]
### What happened + What you expected to happen

test_http_job_server.py:test_ray_tune_basic is failing on master. 
<img width="1131" alt="image" src="https://github.com/ray-project/ray/assets/6515354/fd34a646-29b1-40e2-bf0e-8dfe3c83ae72">

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by pcmoritz** [comment]
A user also ran into this, we should make sure to fix it!

**Comment by matthewdeng** [comment]
Closing this as a duplicate of #36658 since there's more context in that thread.
