### ISSUE TITLE
[rllib] Exception: Unknown config parameter `sgd_stepsize`

### ISSUE THREAD

**Issue by inoryy** [ray-project/ray#3665]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.1
- **Python version**: 3.6.7
- **Exact command to reproduce**: N/A

### Describe the problem
Following the basic usage example from [the docs](https://ray.readthedocs.io/en/latest/rllib-training.html#python-api) without any changes immediately results in this error.  
I guess `sgd_stepsize` param was replaced by something? It's still mentioned throughout the docs and example configs.

### Source code / logs

```python
import ray
import ray.tune as tune

ray.init()
tune.run_experiments({
    "my_experiment": {
        "run": "PPO",
        "env": "CartPole-v0",
        "stop": {"episode_reward_mean": 200},
        "config": {
            "num_gpus": 0,
            "num_workers": 1,
            "sgd_stepsize": tune.grid_search([0.01, 0.001, 0.0001]),
        },
    },
})
```

**Comment by ericl** [comment]
Oops, this should be replaced by 'lr' now, thanks for reporting.
