### ISSUE TITLE
[core][release test] Unstable stress_test_state_api_scale.aws

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#36675]
### What happened + What you expected to happen

Test was failing due to failures that were orthogonal to what the test was testing: https://github.com/ray-project/ray/issues/36445

Root cause to be done. 

### Versions / Dependencies

master

### Reproduction script

na

### Issue Severity

None

**Comment by can-anyscale** [comment]
Same with https://github.com/ray-project/ray/issues/36445

**Comment by can-anyscale** [comment]
Should be fixed with https://github.com/ray-project/ray/pull/36882

**Comment by can-anyscale** [comment]
Fix with https://github.com/ray-project/ray/pull/36882
