### ISSUE TITLE
[Tune] Update deprecated Optuna APIs

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#36685]
Optuna has upgraded some of their Distribution classes. As such, we should upgrade the Tune code to use the new replacements.

| Deprecated | New |
|--------|--------|
| IntUniformDistribution | IntDistribution |
| UniformDistribution | FloatDistribution |
| LogUniformDistribution | FloatDistribution | 

**Optuna API References:** [optuna.distributions](https://optuna.readthedocs.io/en/stable/reference/distributions.html)
**Relevant Code:** [optuna_search.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/search/optuna/optuna_search.py)

**Comment by Harshal662** [comment]
i can do that
