### ISSUE TITLE
[rllib] ES hangs on custom env

### ISSUE THREAD

**Issue by fywu85** [ray-project/ray#3669]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip installl ray
- **Ray version**: 0.6.1
- **Python version**: 3.5.6
- **Exact command to reproduce**:
```
git clone https://github.com/flow-project/flow.git
cd flow
git checkout es-debug
pip install -e .
cd examples/rllib
python figure_eight_ppo.py  # This will successfully terminate after ~45 seconds.
python figure_eight_es.py  # This will run forever, which is a problem.
```

### Describe the problem

ES agent seems to hang forever in a custom setup.

### Source code / logs

The runner script can be  found here: https://github.com/flow-project/flow/tree/master/examples/rllib.

**Comment by ericl** [comment]
Perhaps try 'ray stack' to see where it is hanging?

Cc @eugenevinitsky

**Comment by eugenevinitsky** [comment]
@fywu85 is this still an issue?
