### ISSUE TITLE
[Data] `DatasetContext` isn't propagated to worker nodes

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#36694]
### What happened + What you expected to happen

I tried to disable block splitting when I read files and perform shuffles, but it didn't work. I'm running Ray on a 10 node cluster, and I ran into the issue while reading Parquet files.

### Versions / Dependencies

e50e182e20431f785b73278636dc8ea51187ed86

### Reproduction script

TK

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
Yea you need to propagate it manually.

**Comment by bveeramani** [comment]
Closing because you can't disable block splitting anymore, so this isn't an issue. See https://github.com/ray-project/ray/pull/38235
