### ISSUE TITLE
Problems when creating multiple raylets with the given socket name

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#3671]
### Describe the problem

In this section, if `num_local_schedulers` is bigger than 1, and `raylet_socket_name` is not `None`, we will create multiple raylets using the same socket.

https://github.com/ray-project/ray/blob/b8a9e3f1064c6f8d754884fd9c75e0b2f88df4d6/python/ray/services.py#L1433-L1441

A solution is to check we only have 1 raylet when `raylet_socket_name` is not `None`.  But I still don't understand why we need mutiple raylets in the same node.

**Comment by zhijunfu** [comment]
It's probably for testing & debugging, sometimes it's very helpful to test multi-node scenarios with a single machine.

**Comment by robertnishihara** [comment]
Yeah, it's for testing. However, now that we have `ray.test.cluster_utils`, I would like to remove this code path and only use `ray.test.cluster_utils`.

**Comment by suquark** [comment]
OK, I would like to create a PR to remove related code path. It can make the code look better and less confusing.
