### ISSUE TITLE
[Serve] Ray Serve Autoscaler does not relinquish cluster nodes when scaling down 

### ISSUE THREAD

**Issue by pandemosth** [ray-project/ray#36749]
### What happened + What you expected to happen

The problem occurs in a serve application with multiple autoscaling deployments. Under normal load the cluster looks something like this:

- Head Node
- GPU Worker Node 1
   - Deployment A replica 1
   - Deployment B replica 1
   - Deployment C replica 1

Under load, the autoscaler adds a replica for Deployment A, which triggers the cluster autoscaler to add a 2nd GPU worker:

- Head Node
- GPU Worker Node 1
   - Deployment A replica 1
   - Deployment B replica 1
   - Deployment C replica 1
 - GPU Worker Node 2
   - Deployment A replica 2

When the demand spike is over, the ray serve autoscaler removes replica 1, leaving:

- Head Node
- GPU Worker Node 1
   - Deployment B replica 1
   - Deployment C replica 1
 - GPU Worker Node 2
   - Deployment A replica 2
   
As a result, the cluster continues running a 2nd GPU worker unnecessarily. I would expect replica 2 to be selected for removal so that GPU node 2 can be relinquished.

Without this working correctly, autoscaling is a bit pointless as the cluster scales up on first spike in demand and never scales down.

   
   
   

### Versions / Dependencies

Ray 2.5.0

### Reproduction script

I think a test for this could be added here, but not sure

[python/ray/serve/tests/test_cluster.py](https://github.com/ray-project/ray/blob/2.5/python/ray/serve/tests/test_cluster.py)

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
This is tracked in #20599. That thread proposes two approaches to downscaling intelligently, so the cluster can be scaled down. We're planning to implement the first approach in #36588. This doesn't quite solve the case raised in this issue, but there doesn't seem to be an optimal one-size-fits-all policy.

I'll close this issue, and we can consolidate the conversation in #20599.
