### ISSUE TITLE
[State CLI] `ray get nodes` or `ray get actors` without ID should just list them

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#36777]
### Description

As a user who briefly scans the state CLI doc, the first thing I might try is 

```
ray get nodes
```

to show info for all the nodes.  (Not specific to `nodes`, just using it for this example.) This outputs

```
Usage: ray get [OPTIONS] {actors|placement-
               groups|nodes|workers|tasks|objects|cluster-events} ID
Try 'ray get --help' for help.

Error: Missing argument 'ID'.
```

The error is clear enough, but I think we can reduce friction even further by 
- At the very least, suggest "Did you mean `ray list nodes`?"
- Or, just make `ray get nodes` alias to `ray list nodes`.

**Comment by architkulkarni** [comment]
Users familiar with `kubectl` might be used to running `get X` to get a list of resource X.

**Comment by rkooo567** [comment]
This is the intentional UX and we have no plan to change it. The purpose is to not mix up different APIs (cc @rickyyx )

**Comment by architkulkarni** [comment]
Are you against adding a suggestion "Did you mean `ray list nodes`?"

**Comment by rickyyx** [comment]
> Are you against adding a suggestion "Did you mean `ray list nodes`?"


This is nice.

**Comment by suhas-bn-1412** [comment]
Hi @rickyyx , can I work on this? Seems like a good place to start contributing.
If you've not started working on it already, I'd be happy to work on this.
Thank you!
