### ISSUE TITLE
Release test ray-data-bulk-ingest-file-size-benchmark.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36779]
Release test **ray-data-bulk-ingest-file-size-benchmark.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1823#0188ea53-f994-42d4-8936-5f670823a201 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
Close - wait on re-run and we can cut one again.
