### ISSUE TITLE
Release test ray-data-bulk-ingest-out-of-core-benchmark.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36778]
Release test **ray-data-bulk-ingest-out-of-core-benchmark.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1823#0188ea53-f997-4bcf-a4e4-f03bcfb29316 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
Close - wait on re-run and we can cut one again.
