### ISSUE TITLE
Release test ray-data-bulk-ingest-heterogeneity-benchmark.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36776]
Release test **ray-data-bulk-ingest-heterogeneity-benchmark.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1823#0188ea53-f99a-4fe5-af56-2f313cc1e036 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
Close - wait on re-run and we can cut one again.
