### ISSUE TITLE
Cannot import 'sample_from' in python hyperband_example.py

### ISSUE THREAD

**Issue by suleka96** [ray-project/ray#3680]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: installed through pip command given in documentation
- **Ray version**: 0.6.0
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Exact command to reproduce**: compilation error
- **IDE**: PyCharm Professional 2018.3.2

### Describe the problem
the 'sample_from' function cannot be imported. It was written in [this](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperband_example.py) example code.

### Source code / logs
/home/suleka/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/suleka/Documents/sales_prediction/LSTM_hyperband_and_hyperopt_withoutzero.py", line 10, in <module>
    from ray.tune import grid_search, run_experiments, register_trainable, Trainable, sample_from
ImportError: cannot import name 'sample_from'

**Comment by richardliaw** [comment]
Hi Suleka,

Can you try `pip install -U ray==0.6.1`?

**Comment by suleka96** [comment]
Thanks, this worked.
