### ISSUE TITLE
[Core] L4 GPUs are not detected by Ray

### ISSUE THREAD

**Issue by ghpu** [ray-project/ray#36806]
### What happened + What you expected to happen

Nvidia L4 gpus are not recognised. They are now available on GCP with the accelerator name "nvidia-l4".

### Versions / Dependencies

ray : 2.5
python: 3.10

### Reproduction script

no script.

### Issue Severity

Medium

**Comment by rkooo567** [comment]
We rely on `GPUtil` that uses `nvidia-smi` under the hood. Can you check your nvidia-smi is able to detect that GPU?

**Comment by ghpu** [comment]
Thank you, my problem lies in the nvidia driver not being up to date for L4 support on GCE default COS image.

**Comment by rkooo567** [comment]
We can update the doc for this !
