### ISSUE TITLE
Release test benchmark_worker_startup.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#36811]
Release test **benchmark_worker_startup.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1827#0188f67a-3531-4afe-a525-65ce29e4f58f for more details.

Managed by OSS Test Policy

**Comment by rkooo567** [comment]
@can-anyscale are you planning to do bisect?

**Comment by can-anyscale** [comment]
@rkooo567 yeah a bisect was triggered https://buildkite.com/ray-project/release-tests-bisect/builds/297, it thinks that the failure is bogus and will go by itself after retry

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1832#0188fe57-d384-4c4f-8c8e-935c389794a3
