### ISSUE TITLE
[docs][data] definition for Datasource 

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#36819]
### Description

Having trouble finding a definition for `Datasource`. It's referred to in the `Fine-tuning a Torch object detection model`. The definition in the example says, "A Datasource is an object that reads data of a particular type. " What is the output of a Datasource after it reads data? This is in the `Creating a custom datasource` section. What is the difference between a Datasource and a custom datasource? 

### Link

https://docs.ray.io/en/master/ray-air/examples/torch_detection.html#define-a-custom-datasource

**Comment by anyscalesam** [comment]
I think we can close this; re-reading through the Datasource documentation now it seems pretty clear that Datasource is the base class in which you can inherit and define any custom datasource, where, after you also inherit and write the read and write functions; becomes a Dataset that you can use the same ol' distributed capabilities of Ray Data to iterate/read/ingest from/to.
