### ISSUE TITLE
[AIR Output] Not sure if some metrics for lightning trainer are unnecessary

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36818]
### What happened + What you expected to happen

Ran the basic lightning example here: https://docs.ray.io/en/latest/train/examples/lightning/lightning_mnist_example.html

Is it necessary to show `_report_on` and `step`? 

cc: @yunxua

```
Training finished iteration 1 at 2023-06-26 09:36:10. Total running time: 1min 57s
╭──────────────────────────────────────╮
│ Training result                      │
├──────────────────────────────────────┤
│ time_this_iter_s            17.95661 │
│ time_total_s                17.95661 │
│ training_iteration                 1 │
│ _report_on           train_epoch_end │
│ epoch                              0 │
│ step                             108 │
│ train_loss                    0.3444 │
│ val_accuracy                 0.92421 │
│ val_loss                    -9.03381 │
╰──────────────────────────────────────╯

Training saved a checkpoint for iteration 1 at: /tmp/ray_results/ptl-mnist-example/LightningTrainer_4859f_00000_0_2023-06-26_09-34-12/checkpoint_000000

```

### Versions / Dependencies

nightly

### Reproduction script

https://docs.ray.io/en/latest/train/examples/lightning/lightning_mnist_example.html

### Issue Severity

Low: It annoys or frustrates me.

**Comment by krfricke** [comment]
We can probably exclude `_report_on` easily. `step` seems to be populated by lightning itself - let's accept it for now until we have a more generalized way to exclude things like this
