### ISSUE TITLE
Ray exits with error after finishing a large numbers of tasks

### ISSUE THREAD

**Issue by xutianming** [ray-project/ray#3682]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux CentOS 7
- **Ray installed from (source or binary)**:source
- **Ray version**:0.6.1
- **Python version**:Miniconda 2.7.15
- **Exact command to reproduce**:
```python
import time
import ray

num_trials = 3
num_tasks = 1000000
ray.init(num_cpus=16)

@ray.remote
def task():
    pass

total = 0
for _ in range(num_trials):
    start = time.time()
    l = [task.remote() for _ in range(num_tasks)]
    ray.get(l)
    end = time.time()
    time.sleep(5)
    total = total + (end-start)
    print("Time consumed:", end-start)

print("Avg time consumed:", total*1.0/num_trials)
```

### Describe the problem

Ray failed to exit gracefully when running above codes.

### Source code / logs

![image](https://user-images.githubusercontent.com/4970790/50632148-dfb6ae80-0f81-11e9-8a34-0533ac6af590.png)

**Comment by robertnishihara** [comment]
Can you check under `/tmp/ray` and see if there are any logs indicating what went wrong?

**Comment by raulchen** [comment]
It looks that raylet crashed. Can you check if there's any error message at the end of `/tmp/ray/session-***/logs/raylet_0.err` file?

**Comment by xutianming** [comment]
Close this issue because it can not be reproduced with latest master.
Probably already fixed.
