### ISSUE TITLE
[AIR output] Leak of trial concept in Ray Train output 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36832]
### What happened + What you expected to happen

Not sure if this has been discussed before. Cannot find the previous issue any more.

I ran the PTL advanced train example: https://docs.ray.io/en/latest/train/examples/lightning/lightning_cola_advanced.html and saw this.
```
2023-06-26 13:37:36,038 WARNING trial_runner.py:928 -- Consider turning off forced head-worker trial checkpoint syncs by setting sync_on_checkpoint=False. Note that this may result in faulty trial restoration if a failure occurs while the checkpoint is being synced from the worker to the head node.
```

### Versions / Dependencies

nightly

### Reproduction script

https://docs.ray.io/en/latest/train/examples/lightning/lightning_cola_advanced.html

### Issue Severity

Low: It annoys or frustrates me.

**Comment by woshiyyya** [comment]
@scottsun94 A quick question: Are we trying to hide this concept of "trial" totally from the users? What's the alternative term we should use for it instead?

**Comment by scottsun94** [comment]
There is no "trial" concept in Ray Train I assume?
What term does PTL use?

**Comment by anyscalesam** [comment]
Head node syncing is gone so this isn't applicable anymore.
