### ISSUE TITLE
[Core] Unable to get`gcs_address` when connected to an external cluster

### ISSUE THREAD

**Issue by wizrds** [ray-project/ray#36833]
### What happened + What you expected to happen

When trying to use `ray.get_runtime_context().gcs_address` while connected with an external cluster then it fails with: 
```
Traceback (most recent call last):
  File "/home/user/Documents/scripts/test_ray.py", line 5, in <module>
    print(ray.get_runtime_context().gcs_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Documents/scripts/.venv/lib/python3.11/site-packages/ray/runtime_context.py", line 342, in gcs_address
    self.worker.check_connected()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_ClientWorkerPropertyAPI' object has no attribute 'check_connected'
```

However it works when not passing a cluster address to `ray.init()`:
```
2023-06-26 15:18:49,896 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
192.168.1.216:47634
```

### Versions / Dependencies

Ray: `2.5.1`
Python: `3.11.2`

### Reproduction script

Fails:
```py
import ray

ray.init("ray://localhost:10001")

print(ray.get_runtime_context().gcs_address)
```

Works:
```py
import ray

ray.init()

print(ray.get_runtime_context().gcs_address)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @ckw017 can you take a look at this issue? I think this API is not implemented for the ray client. 

cc @wizrds is it possible for you to use https://docs.ray.io/en/master/cluster/running-applications/job-submission/index.html instead of ray client? We no longer encourage people to use ray client and instead use the job API for the stability.

**Comment by wizrds** [comment]
> is it possible for you to use https://docs.ray.io/en/master/cluster/running-applications/job-submission/index.html instead of ray client? We no longer encourage people to use ray client and instead use the job API for the stability.

@rkooo567 Even for just submitting remote functions?

**Comment by rkooo567** [comment]
yeah the recommended solution is to submit a job using the job API. Is there a special reason why you should stick to ray client?

**Comment by ckw017** [comment]
Opened up a fix, but might be a wheel before it makes it into a release. We recommend jobs, but if you need to be immediately unblocked you can make the call through a remote function:

```
@ray.remote
def get_gcs_address_client_mode():
  return ray.get_runtime_context().gcs_address
```

**Comment by wizrds** [comment]
> yeah the recommended solution is to submit a job using the job API. Is there a special reason why you should stick to ray client?

We're making use of DAGNodes and executing them on an external cluster, and they are assembled at runtime. Can you share some insight into how I may use the Jobs API for this? It seems to me like it's purely for running static python scripts in the cluster unless I'm missing something.
