### ISSUE TITLE
[Serve] [Docs] Add an end-to-end example using streaming

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#36845]
### Description

Serve has recently added streaming and WebSocket support. There should be an end-to-end example that walks users through how to use these for their own workloads.

**Comment by wjn0** [comment]
I'm interested in connecting Ray streaming support with HuggingFace's streaming text generation support as implemented in `TextIteratorStreamer`.

I've got something working using Ray Serve (including some model composition where both models are streaming), built-in Python threading `Queue`s and HTTP streaming responses in Ray 2.5.0. It seems like maybe better support is coming for this use case. Is there a link that summarizes the planned implementation?

Cheers!

**Comment by shrekris-anyscale** [comment]
Hi @wjn0, your implementation seems similar to our plan to support HuggingFace's streaming text generation. Please feel free to take a look at https://github.com/ray-project/ray/pull/36961 for some code examples, and let us know what you think!

**Comment by shrekris-anyscale** [comment]
[From @wjn0](https://github.com/ray-project/ray/pull/36961#issuecomment-1613806430) (in https://github.com/ray-project/ray/pull/36961):

> @shrekris-anyscale This is very cool! My version of the LLM actor is very similar -- my only small addition was some cancellation logic to kill the thread holding the streamer using a `threading.Event` (when the user indicates, via the API actor).
> 
> A quick follow-up question, if you don't mind: for my use case I glued together two streaming actors using a custom Ray queue-like actor. I'm wondering if the new API will eventually let me do this without using a queue? I'm envisioning something like:
> 
> ```python
> @ray.remote
> def iterable_task1(prompt):
>     for text in generator(prompt):
>         yield text
> 
> @ray.remote
> def iterable_task2(prompt):
>     for text in iterable_task1.remote(prompt):
>         yield {"text": text, "transformed": transform(text)}
> 
> class APIIngress:
>     # ...
>     @app.get("/transformed_text")
>     def transformed_text(prompt):
>         return StreamingResponse(iterable_task2.remote(prompt))
> ```
> 
> with the response streaming "live" over the wire. My understanding of the current state of the `@num_returns(...)`  API is that this particular use case is unsupported even with experimental streaming enabled. I really appreciate your work on this set of features so far!

**Comment by shrekris-anyscale** [comment]
We are planning to eventually support chaining generators like this without needing queue actors like this. I'm not sure if we have a timeline yet though. cc @edoakes
