### ISSUE TITLE
[AIR output] Tune error table is a bit spammy and confusing.

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#36854]
### What happened + What you expected to happen

Here is the output when I run this [train+tune example](https://docs.ray.io/en/latest/train/examples/pytorch/tune_cifar_torch_pbt_example.html): https://gist.github.com/scottsun94/f678f42c074ac7d5b3963e953a58cace 

1. The table of errored trials kept getting printed, which made me feel that the trials kept failing at first.
2. I don't understand what `1*` meant and a footnote was printed only below the last 2 tables.

```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name                   # failures   error file                                                                                                                │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ TorchTrainer_8e6b3_00002             1*   /home/ray/ray_results/TorchTrainer_2023-06-26_21-39-09/TorchTrainer_8e6b3_00002_2_lr=0.0500_2023-06-26_21-39-09/error.txt │
│ TorchTrainer_8e6b3_00001             1*   /home/ray/ray_results/TorchTrainer_2023-06-26_21-39-09/TorchTrainer_8e6b3_00001_1_lr=0.0100_2023-06-26_21-39-09/error.txt │
│ TorchTrainer_8e6b3_00003             1*   /home/ray/ray_results/TorchTrainer_2023-06-26_21-39-09/TorchTrainer_8e6b3_00003_3_lr=0.1000_2023-06-26_21-39-09/error.txt │
│ TorchTrainer_8e6b3_00000             1*   /home/ray/ray_results/TorchTrainer_2023-06-26_21-39-09/TorchTrainer_8e6b3_00000_0_lr=0.0010_2023-06-26_21-39-09/error.txt │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
3. It seems that some trials got restarted (their config got printed twice), but the trial table showed them as running all the time? Is there anything wrong (but there is no error about it)?

### Versions / Dependencies

nightly

### Reproduction script

https://docs.ray.io/en/latest/train/examples/pytorch/tune_cifar_torch_pbt_example.html

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by krfricke** [comment]
1. Fair point, I think we should only print the table for fully failed trials during tuning and the full table (including footnotes) at the end
2. See above, this will be resolved if we just print these trials at end
3. All trials should have errored and the error should have been printed. I couldn't find a trial in the output where this wasn't the case, do you have an example?

**Comment by scottsun94** [comment]
3. That makes sense. NVM.
