### ISSUE TITLE
[Frontend CI] Remove nvm to enhance the efficiency of our CI processes.

### ISSUE THREAD

**Issue by chaowanggg** [ray-project/ray#36871]
### Description

A question from @aslonnie:

We currently utilize both npm and nvm in our dashboard to manage package dependencies and versions. However, we are considering the possibility of removing nvm to enhance the efficiency of our CI processes.

Is it feasible to eliminate nvm from our dashboard without compromising CI efficiency?

**Comment by chaowanggg** [comment]
@alanwguo

**Comment by aslonnie** [comment]
just to clarify, it is fine to use nvm for dev workflow. just that on ci pipelines (especially on Linux ones), we can just install the particular version of node+npm directly, like using the following:

https://github.com/nodesource/distributions#installation-instructions

**Comment by aslonnie** [comment]
the downside of using nvm is that it installs stuff into the home directory, and add hooks into `.bashrc`, where on CI, it is not always the case that the `.bashrc` will be called (because it does not need to launch an interactive shell).

**Comment by chaowanggg** [comment]
> just to clarify, it is fine to use nvm for dev workflow. just that on ci pipelines (especially on Linux ones), we can just install the particular version of node+npm directly, like using the following:
> 
> https://github.com/nodesource/distributions#installation-instructions

Thanks for the clarification!
