### ISSUE TITLE
PPO with LSTM - max_seq_len 

### ISSUE THREAD

**Issue by aGiant** [ray-project/ray#3689]
### System information
- **Ubuntu 18.04 LTS**:
- **Ray installed from pip install ray[rllib]**:
- **0.6.0**:
- **Python 3.6**:
- **Exact command to reproduce**:

### Describe the problem

config["num_gpus"] = 0
config["num_workers"] = 1
config["sample_batch_size"] = 2592
config["train_batch_size"] = 7776
config['model']["use_lstm"] = True
config['model']["max_seq_len"] = 200#24*12*3
config['model']["lstm_cell_size"] = 256
config['model']["lstm_use_prev_action_reward"] = True

### Source code / logs
Traceback (most recent call last):
  File "/home/llu/c7_triangle/train.py", line 73, in <module>
    result = agent.train()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 278, in train
    result = Trainable.train(self)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 94, in _train
    fetches = self.optimizer.step()
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 153, in step
    [tuples[k] for k in state_keys]))
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_impl.py", line 166, in load_data
    "got only {} total.".format(len(smallest_array)))
**ValueError: Must load at least 1 tuple sequence per device, got only 39 total.** 

Last description is misleading for understanding the error. What's the relationship betwee max_seq_len, sample_batch_size, train_batch_size?

Configure File:

{'monitor': False, 'log_level': 'INFO', 'callbacks': {'on_episode_start': None, 'on_episode_step': None, 'on_episode_end': None, 'on_sample_end': None, 'on_train_result': None}, 'model': {'conv_filters': None, 'conv_activation': 'relu', 'fcnet_activation': 'tanh', 'fcnet_hiddens': [256, 256], 'free_log_std': False, 'squash_to_range': False, 'use_lstm': True, 'max_seq_len': 200, 'lstm_cell_size': 256, 'lstm_use_prev_action_reward': True, 'framestack': True, 'dim': 84, 'channel_major': False, 'grayscale': False, 'zero_mean': True, 'custom_preprocessor': None, 'custom_model': None, 'custom_options': {}}, 'optimizer': {}, 'gamma': 0.99, 'horizon': None, 'env_config': {}, 'env': None, 'clip_rewards': None, 'clip_actions': True, 'preprocessor_pref': 'deepmind', 'num_workers': 1, 'num_gpus': 0, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, 'custom_resources_per_worker': {}, 'num_cpus_for_driver': 1, 'num_envs_per_worker': 1, 'sample_batch_size': 2592, 'train_batch_size': 7776, 'batch_mode': 'truncate_episodes', 'sample_async': False, 'observation_filter': 'MeanStdFilter', 'synchronize_filters': True, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_evaluator_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'compress_observations': False, 'collect_metrics_timeout': 180, 'input': 'sampler', 'input_evaluation': None, 'output': None, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'multiagent': {'policy_graphs': {}, 'policy_mapping_fn': None, 'policies_to_train': None}, 'use_gae': True, 'lambda': 1.0, 'kl_coeff': 0.2, 'sgd_minibatch_size': 128, 'num_sgd_iter': 30, 'lr': 5e-05, 'lr_schedule': None, 'vf_share_layers': False, 'vf_loss_coeff': 1.0, 'entropy_coeff': 0.0, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'kl_target': 0.01, 'simple_optimizer': False}

**Comment by aGiant** [comment]
another error by calling compute_action():

Traceback (most recent call last):
  File "/home/llu/c7_triangle/train.py", line 61, in <module>
    act = agent.compute_action(env.observation)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 364, in compute_action
    policy_id=policy_id)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 491, in for_policy
    return func(self.policy_map[policy_id])
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 363, in <lambda>
    lambda p: p.compute_single_action(filtered_obs, state)[0],
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/policy_graph.py", line 91, in compute_single_action
    [obs], [[s] for s in state], episodes=[episode])
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 160, in compute_actions
    prev_reward_batch)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 236, in _build_compute_actions
    (self._state_inputs, state_batches)
AssertionError: ([<tf.Tensor 'default/c:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'default/h:0' shape=(?, 256) dtype=float32>], [])

Training LSTM using 
self.action_space = Box(low = -1, high = 1, shape = (self.components*len(self.symbol),), dtype = numpy.float32)
self.observation_space = Box(low = -1, high = 1, shape = (len(self.names),), dtype = numpy.float32)

Everything went well by setting config['model']["max_seq_len"] = 120, in stead of 200. I'm totally lost here.

**Comment by aGiant** [comment]
That works! Many thanks!
But I didn't use any GPU in my VM environment, config["num_gpus"] = 0.

One question remains: how can I **compute action** from observation and actions **using LSTM** and last_action=True? Can you give me any **example** about how to call the agent.compute_action() function ? Or some pre-processing must be done before calling that function?

Thanks again :)

**Comment by aGiant** [comment]
I haven't found any implementation for compute_actions() under the link: ray/python/ray/rllib/evaluation/policy_graph.py. And what should I inlcude in the code in oder to call the implmented function for compute_actions()?
Thx :)

**Comment by ericl** [comment]
It's an abstract method so there's no implementation there, but you can see examples of how it's called.
In sampler:
https://github.com/ray-project/ray/blob/c4cba98c7531d99bd97070cccd797ad74a8ceccb/python/ray/rllib/evaluation/sampler.py#L462

Basically, you just need to pass in batches of obs, state, prev_action, prev_reward, etc., as lists.

**Comment by aGiant** [comment]
obs, prev_action and prev_reward are clear. But what's the defintion of state? LSTM state, or env state?

**Comment by aGiant** [comment]
Try to call like this:
act = agent.local_evaluator.policy_map["default"].compute_actions(list(env.observation), [], list(act), [env.reward]).

Got error:
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    act = agent.local_evaluator.policy_map["default"].compute_actions(list(env.observation), [], list(act), [env.reward])
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 160, in compute_actions
    prev_reward_batch)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 236, in _build_compute_actions
    (self._state_inputs, state_batches)
AssertionError: ([<tf.Tensor 'default/c:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'default/h:0' shape=(?, 256) dtype=float32>], [])

**Comment by ericl** [comment]
Yea, that assert is raised since you didn't pass in the lstm state batches. If you see the error it says the expects two [?, 256] tensors (c and h) for state_batches.

Example of getting the initial state (they are basically zero arrays):
https://github.com/ray-project/ray/pull/3643/files#diff-421f7bb46be7057c728fb7d2cb067af6R109

**Comment by aGiant** [comment]
code: 
state = agent.local_evaluator.policy_map["default"].get_initial_state()
act = agent.local_evaluator.policy_map["default"].compute_actions(list(env.observation), state, list(act), [env.reward])
still keep erroring:

Traceback (most recent call last):
  File "train.py", line 66, in <module>
    act = agent.local_evaluator.policy_map["default"].compute_actions(list(env.observation), state, list(act), [env.reward])
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 161, in compute_actions
    return builder.get(fetches)
  File "/home/llu/.local/lib/python3.6/site-packages/ray/rllib/utils/tf_run_builder.py", line 50, in get
    self.fetches, self.feed_dict))
ValueError: Error fetching: [<tf.Tensor 'default/add_1:0' shape=(?, 21) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_3:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'default/rnn/while/Exit_4:0' shape=(?, 256) dtype=float32>, {'vf_preds': <tf.Tensor 'default/value_function/Reshape:0' shape=(?,) dtype=float32>, 'logits': <tf.Tensor 'default/add:0' shape=(?, 42) dtype=float32>}], feed_dict={<tf.Tensor 'default/obs:0' shape=(?, 432) dtype=float32>: [0.05345214, -0.05785464, -0.04902136, 0.07541901, -0.03901618, -0.027390447, 0.08762517, -0.18583602, -0.01516552, 0.08226993, -0.001418014, -0.14326207, 0.011734192, 0.07674922, -0.095640995, 0.029332876, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.38887417, 0.28062546, 0.2852992, 0.4110888, 0.29111078, 0.29922396, 0.4301249, 0.2157833, 0.3106138, 0.44282365, 0.3255022, 0.23735078, 0.34135664, 0.4571707, 0.2616658, 0.3631157, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.2148267, 0.06776069, 0.08891927, 0.23087816, 0.11084845, 0.13398492, 0.24890019, -0.36446464, 0.15596896, 0.24605033, 0.17679633, -0.17712587, 0.19078964, 0.23524511, -0.03431394, 0.20237036, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.45368832, 0.35668156, 0.36777407, 0.46622956, 0.3791972, 0.39196035, 0.4770526, 0.12718661, 0.4054045, 0.47786024, 0.41998896, 0.22503954, 0.43126246, 0.47865665, 0.30139583, 0.4419223, 0.48239896, 0.4838882, 0.48380134, 0.48206457, 0.48366168, 0.4835012, 0.48232242, 0.4837095, 0.4833337, 0.48225906, 0.48306525, 0.48411092, 0.48276156, 0.48121682, 0.48407727, 0.4826188, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.17856264, 0.12714055, 0.1413681, 0.17119089, 0.15624411, 0.17197222, 0.17508924, -0.25380996, 0.18519698, 0.18032104, 0.19709428, -0.064327896, 0.20016153, 0.17506821, 0.054721303, 0.19092262, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.42198762, 0.378304, 0.38604146, 0.4259178, 0.39421898, 0.4028, 0.4368969, 0.182232, 0.41060954, 0.4489425, 0.42102888, 0.27884576, 0.425971, 0.45907104, 0.34025186, 0.4234452, 0.47460353, 0.47523227, 0.47515976, 0.47427413, 0.47506955, 0.47491077, 0.47408685, 0.47539163, 0.4747815, 0.47387475, 0.4747928, 0.4754815, 0.4747216, 0.47304073, 0.47539356, 0.47472364, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191, 0.191], <tf.Tensor 'default/seq_lens_1:0' shape=(?,) dtype=int32>: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.]), <tf.Tensor 'default/action_1:0' shape=(?, 21) dtype=float32>: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], <tf.Tensor 'default/prev_reward:0' shape=(?,) dtype=float32>: [0], <tf.Tensor 'default/PlaceholderWithDefault:0' shape=() dtype=bool>: False, <tf.Tensor 'default/c:0' shape=(?, 256) dtype=float32>: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32), <tf.Tensor 'default/h:0' shape=(?, 256) dtype=float32>: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)}
Then it stopped.

**Comment by ericl** [comment]
You'll need to reshape it properly to add the batch dim, i.e., state=[[s] for s in initial_state]

You can also try out the update to agent.compute_action() here: https://github.com/ray-project/ray/pull/3697
This is the non-batched form.

**Comment by aGiant** [comment]
Thanks!
It will be officially released in next version, right?
