### ISSUE TITLE
[build] How to build on centos7?

### ISSUE THREAD

**Issue by starstream** [ray-project/ray#36898]
### What happened + What you expected to happen

May I ask how to build with centos7? I tried to build with centos7 (gcc7 glibc1.17). Since yum only provides bazel4.2.1, I rebuilt bazel. error:/root/bin/bazel build --verbose_failures -- //:ray_pkg //cpp:ray_cpp_pkg

However, pip install ray is available, how do you support centos7

### Versions / Dependencies

ray2.5 centos7 python3.9 gcc7 glibc1.17

### Reproduction script

none

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
We are using manylinux environment to build wheels. That's probably why it works with centos.

**Comment by cadedaniel** [comment]
@starstream are you blocked by this? can you share error logs?

**Comment by jjyao** [comment]
Please follow https://docs.ray.io/en/latest/ray-contribute/development.html to bulid Ray from source code.
