### ISSUE TITLE
Re-enable test_multiple_recursive

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3700]
This test tends to fail (especially on Linux builds), so as of #3683, it is skipped.

This issue supersedes the following issues:
https://github.com/ray-project/ray/issues/2811
https://github.com/ray-project/ray/issues/3060

Perhaps we should investigate + aim to re-enable at some point?

**Comment by robertnishihara** [comment]
This is important because that test hits code paths that otherwise are not used.

**Comment by robertnishihara** [comment]
The test is still skipped.
