### ISSUE TITLE
Error restoring PPO with different number of workers

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3702]
This issue is hard to reproduce (but logging here for now).

When restarting PPO with varying number of workers (different number than before checkpoint), this error sometimes occurs:

```
I0106 15:49:59.277251 135106 node_manager.cc:1731] Resubmitting task 0000000010c2bd8ece1c85aaf5a0fecdc8af4bf8 on client 58f9398f02f17800c647c7634f9727df3b03b2d6
Pushing error to dirver, type: task, message: ray_PPOAgent:restore_from_object() (pid=12406, host=havoc)
ray.worker.RayTaskError: Invalid return value: likely worker died or was killed while executing the task; check previous logs or dmesg for errors.
.
Error restoring runner.
Traceback (most recent call last):
  File "/data/rliaw/miniconda3/envs/ray/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 322, in restore
    ray.get(trial.runner.restore_from_object.remote(value))
  File "/data/rliaw/miniconda3/envs/ray/lib/python3.6/site-packages/ray/worker.py", line 2292, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:restore_from_object() (pid=12406, host=havoc)
ray.worker.RayTaskError: Invalid return value: likely worker died or was killed while executing the task; check previous logs or dmesg for errors.

Error starting runner. Trying again without checkpoint.
```

**Comment by JourneyGo** [comment]
I met this so many times and did not know the reason.

`Traceback (most recent call last):
  File "/home/gaoqi/anaconda2/envs/RAY_ENV/lib/python2.7/site-packages/ray/tune/ray_trial_executor.py", line 311, in restore
    ray.get(trial.runner.restore_from_object.remote(value))
  File "/home/gaoqi/anaconda2/envs/RAY_ENV/lib/python2.7/site-packages/ray/worker.py", line 2386, in get
    raise value
RayTaskError: ray_worker (pid=32483, host=gpu02)
RayTaskError: Invalid return value: likely worker died or was killed while executing the task; check previous logs or dmesg for errors.`

And it is not that hard to reproduce in my cases. I got this error almost 50% of my expriments.
