### ISSUE TITLE
Release test rllib_learning_tests_sac_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#37037]
Release test **rllib_learning_tests_sac_torch.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1855#01891c32-c129-40f4-b573-9a19e86cbb73 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
@avnishn the machine does not have enough memory

**Comment by avnishn** [comment]
it looks like the machine failed to bring up a third node actually. I could experiment with node types? but I don't think this is a release blocker.

**Comment by can-anyscale** [comment]
@avnishn the compute config only declares 2 nodes, was that a bug

**Comment by can-anyscale** [comment]
Passed on release branch, probably just flaky

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1861#01892162-da29-4d9b-b9f7-02971fe79bd8
