### ISSUE TITLE
Cannot Start Ray Cluster - Pydantic < 2.0

### ISSUE THREAD

**Issue by JasonZhao2** [ray-project/ray#37034]
### What happened + What you expected to happen

Ran into an issue while initializing Ray today (as seen in the picture below). Seems like it was already reported in Ray https://github.com/ray-project/ray/issues/37019. I tried the fix suggested (downgrading Ray to 1.10) however and it still threw the same error. 

<img width="852" alt="RayOof" src="https://github.com/ray-project/ray/assets/110079447/ccb499a7-0136-420e-94f4-3f0a6fcec06c">

### Versions / Dependencies

Package                  Version
------------------------ -------------
aiohttp                  3.8.4
aiohttp-cors             0.7.0
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    23.1.0
blessed                  1.20.0
blinker                  1.4
boto3                    1.26.165
botocore                 1.29.165
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
colorful                 0.5.5
command-not-found        0.3
cryptography             3.4.8
dbus-python              1.2.18
distlib                  0.3.6
distro                   1.7.0
distro-info              1.1build1
filelock                 3.12.2
frozenlist               1.3.3
google-api-core          2.11.1
google-auth              2.21.0
googleapis-common-protos 1.59.1
gpustat                  1.1
grpcio                   1.51.3
httplib2                 0.20.2
idna                     3.4
importlib-metadata       4.6.4
jeepney                  0.7.1
jmespath                 1.0.1
jsonschema               4.17.3
keyring                  23.5.0
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
more-itertools           8.10.0
msgpack                  1.0.5
multidict                6.0.4
netifaces                0.11.0
numpy                    1.25.0
nvidia-ml-py             11.525.112
oauthlib                 3.2.0
opencensus               0.11.2
opencensus-context       0.1.3
packaging                23.1
pip                      22.0.2
platformdirs             3.8.0
prometheus-client        0.17.0
protobuf                 4.23.3
psutil                   5.9.5
py-spy                   0.3.14
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pydantic                 1.10.0
PyGObject                3.42.1
PyJWT                    2.3.0
pyparsing                2.4.7
pyrsistent               0.19.3
python-apt               2.4.0+ubuntu1
python-dateutil          2.8.2
PyYAML                   5.4.1
ray                      2.5.1
requests                 2.31.0
rsa                      4.9
s3transfer               0.6.1
SecretStorage            3.3.1
setuptools               59.6.0
six                      1.16.0
smart-open               6.3.0
systemd-python           234
typing_extensions        4.7.1
ubuntu-advantage-tools   8001
ufw                      0.36.1
unattended-upgrades      0.1
urllib3                  1.26.16
virtualenv               20.21.0
wadllib                  1.3.6
wcwidth                  0.2.6
wheel                    0.37.1
yarl                     1.9.2
zipp                     1.0.0

### Reproduction script

import ray
ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
It looks like `pydantic` released [a few patch versions](https://pypi.org/project/pydantic/#history) after `1.10.0`. Could you retry with version [`1.10.10`](https://pypi.org/project/pydantic/1.10.10/)?

**Comment by JasonZhao2** [comment]
No dice, unfortunately. I am running this in WSL, could that be the issue? The script I'm running is from https://github.com/ray-project/langchain-ray/tree/main/embedding_pdf_documents for your reference. 

<img width="713" alt="RayOof2" src="https://github.com/ray-project/ray/assets/110079447/943c60ff-f40e-4c94-a35e-01c0d816a055">

**Comment by alanwguo** [comment]
@JasonZhao2 that's strange for some reason ray is not picking up pydantic `1.x`. Can you open a python interpreter and import pydantic and print out `pydantic.__version__`?

**Comment by JasonZhao2** [comment]
I think I figured it out. The example script I was using just got ray from "pip install ray[default]", which must have be overriding my pydantic install with the new 2.0 version every time. Sorry for taking up your time ~
