### ISSUE TITLE
Error while running test/runtest.py

### ISSUE THREAD

**Issue by Deepak3994** [ray-project/ray#3705]
I have followed the installation from source and have successfully installed Ray. To test the installation i ran "python -m pytest test/runtest.py", but i get the following error 

__________________________________________________________ ERROR collecting test/runtest.py ___________________________________________________________
ImportError while importing test module '/home/ubuntu/ray/test/runtest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/runtest.py:9: in <module>
    import setproctitle
E   ImportError: No module named setproctitle

Kindly help.

**Comment by robertnishihara** [comment]
I've had issues running `runtest.py` in the past as well.

- Do you have `setproctitle` installed?
- Can you try the following?
    ```
    export PYTHONPATH="$PYTHONPATH:./test/"
    python -m pytest -v --durations=10 test/runtest.py
    ```
- Do other tests work for you? E.g., `python -m pytest -v test/actor_test.py`.

**Comment by Deepak3994** [comment]
![runtest](https://user-images.githubusercontent.com/20994657/50749448-eafd2900-1264-11e9-8431-d2686e284e1f.png)

I get the same error while running "export PYTHONPATH="$PYTHONPATH:./test/"
python -m pytest -v --durations=10 test/runtest.py"

And, this command "python -m pytest -v test/actor_test.py" executed succefully. I got output as passed.

**Comment by Deepak3994** [comment]
Hey, got it worked. I had missed the "setproctitle" library.

Thank you.
