### ISSUE TITLE
Release test rllib_learning_tests_dqn_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#37078]
Release test **rllib_learning_tests_dqn_tf.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/1861#01892162-da0a-4381-9445-ab0a708e046c for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
The machine runs out of memory

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by avnishn** [comment]
fixed by #37154

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/1873#01892f3a-375e-4990-b524-4f0881b5e7c5
