### ISSUE TITLE
[Serve] Ray Serve complains about _ClientWorkerPropertyAPI.check_connected when using remote cluster

### ISSUE THREAD

**Issue by xgao1023** [ray-project/ray#37083]
### What happened + What you expected to happen

We're using Ray Serve to scale out a web API application written in Fast API.
We have to use a remote cluster by calling ray.init("ray://xxxxxx") because the Ray cluster is managed seperately (not in our application)

The web service can start without issue. But quickly get into this error after a few web requests.

```
  File "/opt/python/cp38-cp38/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/python/cp38-cp38/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/ray/serve/_private/replica.py", line 224, in handle_request
    return await self.replica.handle_request(query)
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/ray/serve/_private/replica.py", line 631, in handle_request
    num_running_requests = self._get_handle_request_stats()["running"]
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/ray/serve/_private/replica.py", line 450, in _get_handle_request_stats
    actor_stats = ray.runtime_context.get_runtime_context()._get_actor_call_stats()
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/ray/runtime_context.py", line 354, in _get_actor_call_stats
    worker.check_connected()
AttributeError: '_ClientWorkerPropertyAPI' object has no attribute 'check_connected'.
```

I think it's related to https://github.com/ray-project/ray/issues/36833

### Versions / Dependencies

OS: RedHat UBI 8 (running inside Docker container)
Host OS: RedHat Enterprise Linux 8
Python: 3.8.16
Ray: 2.5.0

### Reproduction script

```
@serve.deployment(name=default_config.get('name', 'WebApp'),
				  route_prefix='/')
@serve.ingress(app)
class WebAPI:
	pass

ray.init("ray://xx.xx.xx.xx:10001)   # Using a remote ray cluster
serve.run(WebAPI.bind(), host="my-url.domain, port=80)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
@xgao1023 Yea, I think the issue you mentioned did indeed fixed it. I do see `check_connected()` getting implemented https://github.com/ray-project/ray/blob/9ec342c88b4ffc91a717e6f2acbe279d4143d425/python/ray/util/client/runtime_context.py#L60 Can you try to use nightly and see if that fixes your issue? 

Nightly releases can be found https://docs.ray.io/en/latest/ray-overview/installation.html?highlight=nightly#daily-releases-nightlies

**Comment by GeneDer** [comment]
Close staled issue
