### ISSUE TITLE
[tune[ partial function cannot be registered as trainable

### ISSUE THREAD

**Issue by justusschock** [ray-project/ray#3710]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.1
- **Python version**: 3.7
- **Exact command to reproduce**:

The following code fails:
```
def dummy_fn(c, a, b):
    print("Called")

from functools import partial
from ray.tune import register_trainable
register_trainable("test", partial(dummy_fn, c=None))

```

while the following code works:
```
def dummy_fn(a, b):
    print("Called")

from functools import partial
from ray.tune import register_trainable
register_trainable("test", dummy_fn)

```
### Describe the problem
The first code sample does not work, despite the function (after the `partial`) fullfills all requirements to be properly registered.

### Source code / logs
Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/temp/schock/conda/envs/delira_new/lib/python3.7/site-packages/ray/tune/registry.py", line 35, in register_trainable
    if not issubclass(trainable, Trainable):
TypeError: issubclass() arg 1 must be a class
```

**Comment by richardliaw** [comment]
@justusschock I've opened #3711 which should fix this.
