### ISSUE TITLE
[Core] Dask on Ray 1Tb sort is OOM killed

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#37100]
### What happened + What you expected to happen

https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_ld21bezf5i7p48jefdw97u8lwf

Looks like the driver is OOM killed.

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
Should we close this as a dup of https://github.com/ray-project/ray/issues/36812?
