### ISSUE TITLE
[Data] "Computer vision" uses deprecated APIs

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#37126]
### Description

```python
trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    train_loop_config={"batch_size": 32, "lr": 0.02, "epochs": 1},
    datasets={"train": dataset},
    dataset_config={
        "train": DatasetConfig(per_epoch_preprocessor=per_epoch_preprocessor)
    },
    scaling_config=ScalingConfig(num_workers=2),
    preprocessor=preprocessor,
)
```

`DatasetConfig` is deprecated, and this example raises a warning like 

> The dict form of `dataset_config` is deprecated. Use the DataConfig class instead. Support for this will be dropped in a future release.

### Link

https://docs.ray.io/en/master/ray-air/computer-vision.html?highlight=datasetconfig#training-vision-models

**Comment by pcmoritz** [comment]
There are a few more places that currently use this, the ones I am aware of:

- computer_vision.py
- torch_detection.ipynb
- datasets_train.py
- data_benchmarks.py

**Comment by bveeramani** [comment]
@angelinalg did we remove this guide? I can't seem to find it in the documentation or source code
