### ISSUE TITLE
[Tune] Ray tune Pytorch Lightning integration hook confusion

### ISSUE THREAD

**Issue by florianblume** [ray-project/ray#37139]
### What happened + What you expected to happen

When setting the Pytorch Lightning hook on `TuneCallback` it expects the hook to be without the leading `on_`. This is stated in the init of `TuneCallback` but since I create the callback based on a config I never saw this hint.

The error handling of setting the hook then looks like follows (see https://github.com/ray-project/ray/blob/master/python/ray/tune/integration/pytorch_lightning.py#L58):

```python
if f"on_{hook}" not in _allowed_hooks:
    raise ValueError(
        f"Invalid hook selected: {hook}. Must be one of "
        f"{_allowed_hooks}"
```

Meaning if I set `on_train_epoch_end`  it will print "Invalid hook selected: on_train_epoch_end. Must be one of " and will continue to print exactly "on_train_epoch_end" as a valid hook. It would be more consistent to then print again `on_{hook}` - that would have made it clear to me immediately.

On a different note I'm wondering why the `on_` is even prepended manually. In case at some point there will be a PL hook that does not have an `on_` (for whatever reason), the code needs to be changed anyways.

### Versions / Dependencies

Ray version 2.5.1

### Reproduction script

```python
from ray.tune.integration.pytorch_lightning import TuneReportCallback
callback = TuneReportCallback(metrics=['loss'], on='on_train_epoch_end')
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by woshiyyya** [comment]
Hey @florianblume , thank you for surfacing this API issue. We'll consider this issue internally. 

One thing to mention is that we are not actively maintaining this `TuneReportCallback`, and recommend using the new `LightningTrainer` API. You can create a customized callback in more lightning style and call `session.report` within that callback.
