### ISSUE TITLE
[Serve] Stable Diffusion Web UI example

### ISSUE THREAD

**Issue by seanxlliu** [ray-project/ray#37133]
### Description

Anyone got chance to have a try to run the popular project [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) on Ray?

I got lots of serialization issues, when I tried to run it on Ray Serve. 

### Use case

Run stable-diffusion-webui on a Ray cluster.

**Comment by rkooo567** [comment]
cc @shrekris-anyscale @edoakes do we have any examples running stable difussion?

Also, @seanxlliu can you provide a script you used and the error messages?

**Comment by edoakes** [comment]
Here is an example Serve app running stable diffusion: https://github.com/anyscale/docs_examples/blob/main/stable-diffusion/app.py

**Comment by GeneDer** [comment]
Also the tutorial page is https://docs.ray.io/en/latest/serve/tutorials/stable-diffusion.html

But I think this issue is more about hosting a webapp on Serve rather than specifically to run stable diffusion models tho

**Comment by GeneDer** [comment]
Closed due to inactivity. Please check out the tutorial and example code to see if those helps you running stable diffusion.
