### ISSUE TITLE
Wrong information on source/cluster/configure-manage-dashboard.md

### ISSUE THREAD

**Issue by DrCHall** [ray-project/ray#37138]
### Description

The documentation in `source/cluster/configure-manage-dashboard.md` says gives the example that `RAY_GRAFANA_HOST=55.66.77.88:3000` and implies that this is true for RAY_PROMETHEUS_HOST and RAY_GRAFANA_IFRAME_HOST. However, that is incorrect! All three must have the http:// prefix to work. Here's an example from a working `cluster.yaml` that would be helpful to other users as well:
```yaml
head_start_ray_commands:
    - ray stop
    - export RAY_GRAFANA_HOST="http://localhost:3000" && export RAY_PROMETHEUS_HOST="http://localhost:9090" && export RAY_GRAFANA_IFRAME_HOST="http://55.66.77.88:3000" && ulimit -n 65536 && ray start --head --port=6379 --dashboard-host=55.66.77.88 --dashboard-port=8265 --autoscaling-config=~/ray_bootstrap_config.yaml
```

### Link
[Configuring and Managing Ray Dashboard](https://docs.ray.io/en/latest/cluster/configure-manage-dashboard.html)

**Comment by scottsun94** [comment]
This is already fixed in 2.7: https://docs.ray.io/en/latest/cluster/configure-manage-dashboard.html
