### ISSUE TITLE
[<Ray component: cluster>] About head and nodes local Redis

### ISSUE THREAD

**Issue by stevenhubhub** [ray-project/ray#37136]
### Description

I want to use redis to build a cache pool to cache some special things that I need (so that each node can access the cache pool when it needs such things), I am going to set up a redis environment on the head and each node (i.e. the worker in each node only gets what it needs from the local redis cache, and the redis between each node are isolated from each other). Will this have any serious impact on the running of the ray cluster? Or my way isn't the best way.

### Use case

This is an article I found about the relationship changes between ray and redis, and I don't know if I need to pay attention to this in order to fulfill my above requirements.

https://www.anyscale.com/blog/redis-in-ray-past-and-future

**Comment by rkooo567** [comment]
We don't have redis anymore. It is unlikely introduce any issue unless redis instances on each node uses lots of resources ray needs.
