### ISSUE TITLE
[Core] Potential regression in `stress_test_many_tasks.json` `stage_0_time`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#37183]
From https://github.com/ray-project/ray/pull/37084 

```
REGRESSION 24.28%: stage_0_time (LATENCY) regresses from 8.748622179031372 to 10.872691631317139 (24.28%) in 2.6.0/stress_tests/stress_test_many_tasks.json
```

**Comment by xieus** [comment]
Assign to @cadedaniel tentatively.

**Comment by jjyao** [comment]
<img width="1449" alt="Screenshot 2023-07-10 at 10 17 10 PM" src="https://github.com/ray-project/ray/assets/898023/e9426497-c7fc-4223-957b-7670f76684e4">

It's noise.
