### ISSUE TITLE
[Core] Potential regression in `stress_test_many_tasks.json ` `stage_3_creation_time`

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/ray#37184]
From https://github.com/ray-project/ray/pull/37084

```
REGRESSION 13.28%: stage_3_creation_time (LATENCY) regresses from 3.7931106090545654 to 4.29669189453125 (13.28%) in 2.6.0/stress_tests/stress_test_many_tasks.json
```

**Comment by xieus** [comment]
Assign to @cadedaniel tentatively.

**Comment by rynewang** [comment]
![image](https://github.com/ray-project/ray/assets/56065503/ffc4ef4a-a082-46b2-9d0a-a1956a0c9116)

This metric is not particularly stable. It's wiggling a lot and this particular "regression" is a noise.
