### ISSUE TITLE
[Ray Data: Docs] Ray Data example for iterating over batches should include S3 URL to actual images

### ISSUE THREAD

**Issue by dmatrix** [ray-project/ray#37208]
### Description

This[ doc snippet ](https://docs.ray.io/en/latest/data/iterating-over-data.html#iterating-over-batches)in Ray Data will not work. Instead of using `ds = ray.data.read_images("example://image-datasets/simple")`, we should have directory of images in the S3 bucket just as we do for the `iris.csv` dataset
```

ds = ray.data.read_csv("s3://anonymous@air-example-data/iris.csv")

for batch in ds.iter_batches(batch_size=2, batch_format="pandas"):
    print(batch)
```
This example bellow from the docs will not work for `Torch or Numpy`, since the user executing this won't have anything in the "example//" path directory; it does not exsist.

The easy fix might be:
```
ds = ray.data.read_images("s3://anonymous@air-example-data-2/imagenette2/val/")

for batch in ds.iter_batches(batch_size=2, batch_format="numpy"):
    print(batch)
```
However, for PyTorch may require a collating function, I think, if the images are of different sizes or require ragged tensor. For the other bits of documentation on Ray Data, for[ transforming rows for images](https://docs.ray.io/en/latest/data/transforming-data.html#transforming-rows), we should use real images so that they work.

### Link

https://docs.ray.io/en/latest/data/iterating-over-data.html#iterating-over-batches

**Comment by c21** [comment]
cc @bveeramani and @amogkam.

**Comment by bveeramani** [comment]
@dmatrix what happened when you tried the code snippet locally?

**Comment by dmatrix** [comment]
I ran locally, in may conda env with 2.5.1 installed, and as I understand that "example://URL" refers the directory packaged with 2.5.1. It can't find example directory in the installed packages.

<img width="1686" alt="Screenshot 2023-07-11 at 7 37 51 PM" src="https://github.com/ray-project/ray/assets/1117597/cc1344d8-cb68-4825-9d06-f5a034980d16">

**Comment by dmatrix** [comment]
```
find /opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages/ -name examples -print
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//altair/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//xgboost_ray/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//torch/utils/benchmark/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//torch/testing/_internal/distributed/rpc/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//numpy/core/tests/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//ray/air/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//ray/rllib/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//ray/tune/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//ray/train/examples
/opt/homebrew/Caskroom/miniforge/base/envs/ray-core-tutorial/lib/python3.8/site-packages//boto3/examples
```

None of this directory has images.

**Comment by amogkam** [comment]
Ah yes that's right. Same issue as here: https://github.com/ray-project/ray/pull/33016.

This should be a P0, since the green CI is a false positive right now...

@bveeramani @c21

**Comment by amogkam** [comment]
This is now the second time this has happened- https://github.com/ray-project/ray/issues/32901.

Should be a pretty quick fix to upload the data to S3. And we should remove support for `example://` since it never worked in the first place.

**Comment by amogkam** [comment]
Also cc @can-anyscale @aslonnie fyi as an interesting case study.

the problem here is that certain files are included when building from source (as done in CI) but not when building the wheel.

As a result, these examples that assume the files exist are passing in CI, but are failing for users who install ray from pypi.

**Comment by dmatrix** [comment]
Also, we may want to indicate in the docs what example://URL means, and is that a general form or practice to use to include files as part of bundled pypi wheel? There's a difference, as I understand, between `file:URL`? Any <type:<URL> that ray.data.read_* supports should be explained in the parameters section.
