### ISSUE TITLE
ID types should be made type safe.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#3721]
Right now in the backend, all ID types like `ObjectID`, `ActorID`, etc are just typedefs of `UniqueID`. This means you can pass an `ActorID` as an `ObjectID` argument to some function, which has lead to bugs (during development) in the past.

**Comment by pcmoritz** [comment]
The same goes for the python side. Everything is an ObjectID, which can lead to strange situations @istoica ran into this when developing https://github.com/ray-project/ray/pull/3624: An actor ID was an object id under the hood and when passing that to a task, ray tried to fetch the object.

**Comment by robertnishihara** [comment]
Fixed by #4185.

**Comment by laxatives** [comment]
Has C++ type safety been extended to type hinting in the Python API?
