### ISSUE TITLE
[Core] "ValueError" For "num_cpus" worker option == 1.5

### ISSUE THREAD

**Issue by SebastianMorawiec** [ray-project/ray#37241]
### What happened + What you expected to happen

What happens:
When using num_cpus option = 1.5 for worker, Ray throws out "ValueError: Resource quantities >1 must be whole numbers."

What is expected to be happen:
Either accept fractions, or document. Current documentation states that fractions are accepted without limitations stated

### Versions / Dependencies

ray 2.4, MACOS M1 (although, I'm quite sure it does not matter)

### Reproduction script

```
import ray


@ray.remote(num_cpus=1.5)
def task():
    return 5


if __name__ == "__main__":
    result = ray.get(task.remote())
    print(result)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Tanmoy037** [comment]
I want to try this, please assign this to me.

**Comment by andreichalapco** [comment]
Hello so I suppose this is just changing the documentation. We need to mention in the documentation that the fractional input should be between 0 and 1.

**Comment by Tanmoy037** [comment]
> Hello so I suppose this is just changing the documentation. We need to mention in the documentation that the fractional input should be between 0 and 1.
Hi thank you for explaining, I understood what change I should mention in the doc but I'm new to the project can you just give me a hint about the file structure?
