### ISSUE TITLE
[docs] Ensure all examples are tagged to appear in the Examples Gallery

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#37253]
### Description

All examples that we want to appear in the Examples Gallery need to be tagged in a way that the Examples Gallery will pick them up. For example, the Use Cases examples should match the filtered Examples Gallery. Same for the library example pages.

We should do this for 2.6 so that the user experience is consistent using the Examples Gallery or searching through the docs. Does this mean we need tags that correspond to each library?

### Link

https://docs.ray.io/en/master/ray-overview/examples.html
https://docs.ray.io/en/master/data/examples/index.html
https://docs.ray.io/en/master/ray-air/examples/index.html
https://docs.ray.io/en/master/ray-core/examples/overview.html
https://docs.ray.io/en/master/train/examples.html
https://docs.ray.io/en/master/tune/examples/index.html
https://docs.ray.io/en/master/serve/tutorials/index.html
https://docs.ray.io/en/master/rllib/rllib-examples.html

**Comment by peytondmurray** [comment]
> Does this mean we need tags that correspond to each library?

Yes, we will want that. At a bare minimum a user should be able to type in `air` and get ray air examples to show up. We might also consider adding one button in the sidebar for each Ray library.
