### ISSUE TITLE
[docs] update the CNAME setting for ReadTheDocs

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#37270]
### Description

Releases are using ReadTheDocs.org but should be ReadTheDocs.com.

For reference:
Looking at the domain, it's still configured to point at `[readthedocs.org](http://readthedocs.org/)`: 

;; ANSWER SECTION:
[docs.ray.io](http://docs.ray.io/). 300 IN CNAME [readthedocs.io](http://readthedocs.io/).

This means all traffic to that domain will be redirected there. If you click into the `Edit` button, it will show you the domain you need this DNS record to point at.

**Comment by angelinalg** [comment]
@ijrsvt, would you mind updating this issue with what you did? You can close this issue afterwards, or assign it back to me and I will close it. Thanks!

**Comment by ijrsvt** [comment]
I added a CNAME record to the `ray.io` Route 53 Hosted Zone for the following:
```
8d85bbd3.domains.readthedocs.com
```
Dig now shows:
```
;; ANSWER SECTION:
docs.ray.io.            267     IN      CNAME   8d85bbd3.domains.readthedocs.com.
8d85bbd3.domains.readthedocs.com. 267 IN CNAME  proxy-fallback.readthedocs-hosted.com.
```
