### ISSUE TITLE
[tune] Compatibility with gin-config

### ISSUE THREAD

**Issue by nush-1qb** [ray-project/ray#3732]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS High Sierra (10.13.4)
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.1
- **Python version**: 3.6.0
- **Exact command to reproduce**: `python -m main --gin_config=./config.gin`

### Describe the problem

_**Preface: I followed [this example](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_ray.py) as my main guide.**_

My project uses [gin-config](https://github.com/google/gin-config) for tuning my hyper parameters. The problem I am seeing is that the worker threads don't see the gin configs, but the parent thread does. Specifically, when I print `gin.config._CONFIG` in `__main__()` it is not empty, but it is empty when I print it in `train()` (the entry point for `ray.tune`)

Additionally, when I try to run the code below, I get this error:
```
TypeError: main() missing 2 required positional arguments: 'app' and 'print_gpus'
  No values supplied by Gin or caller for arguments: ['app', 'print_gpus']
  Gin had values bound for: []
  Caller supplied values for: ['path']
  In call to configurable 'main' (<function main at 0x12b7e8950>)
```

### Source code / logs

*main.py*
```python
import os
# To suppress unnecessary tensorflow warnings
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'

import tensorflow as tf
import numpy as np
import sys, gin
from absl import flags

import ray
import ray.tune as tune

status_reporter = None  # used to report training status back to Ray

@gin.configurable
def main(path, app, print_gpus):
    if print_gpus:
        print('Available GPUS:', get_available_gpus())

    # Load and run the App specified in the gin config file.
    app_obj = load_app(app)
    app_obj.run()

def train(config, reporter):

    global status_reporter
    status_reporter = reporter

    print(gin.config._CONFIG)  # empty...

    tf.app.run(main=main)

experiment_spec = tune.Experiment(
    "experiment",
    run = train,
    stop = {
        "mean_accuracy": 0.99
    },
    config = {
        "learning_rate": tune.sample_from(lambda spec: np.random.uniform(0.0001, 0.001)),
        "batch_norm": tune.grid_search([True, False]),
    }
)

if __name__ == '__main__':

    flags.DEFINE_multi_string(
      'gin_config', None, 'List of paths to the config files.')
    flags.DEFINE_multi_string(
      'gin_binding', None, 'Newline separated list of Gin parameter bindings.')

    FLAGS = flags.FLAGS

    # Parse the FLAGs
    FLAGS(sys.argv)

    # To make a singleton that provides the path to the tensor log directory.
    gin.external_configurable(get_log_loc)

    # gin.parse_config_file(os.path.join(root_dir(), 'base.gin'))
    gin.parse_config_files_and_bindings(FLAGS.gin_config, FLAGS.gin_binding)

    print(gin.config._CONFIG) # not empty

    ray.init()
    tune.run_experiments(experiment_spec)
```

*config.gin*
```
# This needs to exist to specify that this app has to be selected.
main.app = 'test'
main.print_gpus = False
```

**Comment by richardliaw** [comment]
This is a quick hack to get you running off the ground - basically, gin relies on the global scope, which could be a bit problematic because all of these tune training functions are on different Python processes.

This forces gin to remain in the local scope, which is packaged nicely when ported onto separate processes.


```python
def train(config, reporter):
    @gin.configurable
    def main(path, app, print_gpus):
        if print_gpus:
            print('Available GPUS:', get_available_gpus())

        # Load and run the App specified in the gin config file.
        app_obj = load_app(app)
        app_obj.run()
    
    gin.parse_config_file("path/to/config.gin")
    tf.app.run(main=main)
```

Let me know what you think!

**Comment by nush-1qb** [comment]
Thanks @richardliaw 

I didn't think about putting `main` in `train` to share the scope.

Thanks!

**Comment by nush-1qb** [comment]
Actually after trying that, I noticed that the working directory changes while inside the worker method.

As such, the relative paths to the config file, *AND* the relative paths inside that are contained _inside_ my gin config file stop working.

Is there any way to work around this?

**Comment by richardliaw** [comment]
I think if you run distributed, it might mess with the checkpointing - but
if only running locally, you should be fine...

**Comment by nush-1qb** [comment]
hmm, yeah the goal is definitely to run it distributed, so we will have to see.
