### ISSUE TITLE
[Core] Using placement group doesn't set OMP_NUM_THREADS properly

### ISSUE THREAD

**Issue by xwu99** [ray-project/ray#37384]
### What happened + What you expected to happen

Using placement group doesn't set task/actor OMP_NUM_THREADS properly. It is always 1.

The reproducer output:

python test-omp-num-threads.py 
2023-07-13 11:35:04,962 INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
(test_omp_num_threads pid=1003999) in task OMP_NUM_THREADS: 5
(test_omp_num_threads pid=1003999) in task OMP_NUM_THREADS: 1
(TestActor pid=1007156) in actor OMP_NUM_THREADS: 4
(TestActor pid=1007234) in actor OMP_NUM_THREADS: 1

### Versions / Dependencies

2.5.1

### Reproduction script

```python
import os
import ray

from ray.air import ScalingConfig
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy

@ray.remote(num_cpus=4)
class TestActor:
    def test(self):
        omp_threads = os.environ["OMP_NUM_THREADS"]
        print(f"in actor OMP_NUM_THREADS: {omp_threads}")

@ray.remote(num_cpus=5)
def test_omp_num_threads():
    omp_threads = os.environ["OMP_NUM_THREADS"]
    print(f"in task OMP_NUM_THREADS: {omp_threads}")

ray.init()

scaling_config = ScalingConfig(
        trainer_resources={"CPU": 20},
        use_gpu=False,
        num_workers=2,
        resources_per_worker={"CPU": 3},
    )

pg = scaling_config.as_placement_group_factory().to_placement_group()

# Task PG
test_omp_num_threads_pg = test_omp_num_threads.options(
    num_cpus=scaling_config.num_cpus_per_worker,
    scheduling_strategy=PlacementGroupSchedulingStrategy(
        placement_group=pg, placement_group_capture_child_tasks=True
    ),
)

ray.get(test_omp_num_threads.remote())
ray.get(test_omp_num_threads_pg.remote())

# Actor PG
test_actor_pg_cls = TestActor.options(
    num_cpus=scaling_config.num_cpus_per_worker,
    scheduling_strategy=PlacementGroupSchedulingStrategy(
        placement_group=pg, placement_group_capture_child_tasks=True
    ),
)

test_actor_vanilla_ref = TestActor.remote()
ray.get(test_actor_vanilla_ref.test.remote())
test_actor_pg_ref = test_actor_pg_cls.remote()
ray.get(test_actor_pg_ref.test.remote())

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by larrylian** [comment]
I will first reproduce the issue and identify the root cause.

**Comment by larrylian** [comment]
For get_assigned_resources() return {"CPU_group_e765be422c439de2cd263c5d9d1701000000":5"} then get("CPU") is none.  I will fix this.
![image](https://github.com/ray-project/ray/assets/11072802/3f7cd05e-4276-42c4-9b98-851d864fbd90)
