### ISSUE TITLE
[RLlib] Upgrade the gymnasium dependency to version the latest version (gymnasium==0.28.1)

### ISSUE THREAD

**Issue by ChrisMcCarthyDev** [ray-project/ray#37393]
### Description

Ray is still using gymnasium 0.26.2 which was released back in October 2022! Get Ray using latest version of gymnasium (0.28.1), or at least the latest major release (0.28.0).

### Use case

Now that Stable baselines3 has fully transitioned to Gymnasium, it would be great if both packages were using the same version of gymnasium. I'm working on a project that uses both Ray with RLlib and Stable Baselines3. We're hoping to be able to finally move from gym to gymnasium and still support both Ray RLlib and Stable Baselines3, but currently things don't work due to Ray still using gymnasium 0.26.2.

Since gymnasium 0.26.2 there have been loads of new features, bug fixes, and even two major releases. 

- [The first major release of gymnasium (0.27.0)](https://github.com/Farama-Foundation/Gymnasium/releases/tag/v0.27.0)
- [The second major release of gymnasium (0.28.0)](https://github.com/Farama-Foundation/Gymnasium/releases/tag/v0.28.0)

**Comment by grizzlybearg** [comment]
I agree

**Comment by ArturNiederfahrenhorst** [comment]
Related to https://github.com/ray-project/ray/issues/34396

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for opening this issue! This is an ongoing process but we hope to finish soon @sven1977

**Comment by visuallization** [comment]
Looking very forward to this! Any ideas when this will be merged?

**Comment by ChrisMcCarthyDev** [comment]
Very happy to see this PR https://github.com/ray-project/ray/pull/35698 has now been merged. Any ideas around release date?

**Comment by ArturNiederfahrenhorst** [comment]
@ChrisMcCarthyDev Around three weeks.
