### ISSUE TITLE
Ray with ssh tunneling and redis adress 127.0.0.1

### ISSUE THREAD

**Issue by fchouteau** [ray-project/ray#3739]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.1
- **redis version** tested with 3.0.1 and 2.10.6
- **Python version**: 3.6.8
- **Exact command to reproduce**:

On the distant machine:
```bash
ray start --head \
          --node-ip-address=127.0.0.1 \
          --redis-port=6379 \
          --object-manager-port=2384 \
          --node-manager-port=2385 \
          --num-redis-shards=1 \
          --redis-shard-ports=6380
```

On the local machine:

SSH to distant machine with port forwarding:
```bash 
ssh user@ray-node-head -L 6379:localhost:6379 -L 6380:localhost:6380 -L 2384:localhost:2384 -L 2385:localhost:2385 -L 8888:localhost:8888 -N -f 
```

Then trying to run:
```bash
ray start --node-ip-address=127.0.0.1 --redis-address=127.0.0.1:6379 --object-manager-port=2384 --node-manager-port=2385
```

### Describe the problem

Hello,

I am trying to use ray with an ssh tunnel, meaning that I start ray on machine A, then ssh from machine B to machine A with the correct port forwarding, then try to ray start in machine B.

The use case would be being able to run remote tasks on machine A from machine B (i.e. num-cpu=0 on machine B)

It may be beyond what ray is designed for, neverthless it doesn't seem like a far fetched use case.

I am getting the error:
```
Waiting for redis server at [my-local-ip:6379] to respond...
Failed to connect to the redis server, retrying.
```
What you can see is that `services.get_node_ip_address()` rewrote the ip to the local ip address...

But when calling `redis_client = redis.StrictRedis(host=redis_ip_address, port=redis_port, password=password)` then `redis_client.client_list()` witht the local IP, it fails, whereas if I call the same API with "127.0.0.1:6379" it succeeds.

So, hacking ray/scripts/scripts.py to actually use `redis_address = "127.0.0.1:6379"` around here https://github.com/ray-project/ray/blob/master/python/ray/scripts/scripts.py#L327 let ray start:

```
[2019-01-10 13:43:57,059][__main__][start_ray][INFO] Using IP address 10.100.59.32 for this node.
[2019-01-10 13:43:57,596][__main__][start_ray][INFO] {'redis_address': '127.0.0.1:6379', 'node_ip_address': 'publicip', 'redis_shards': ['publicip:6380'], 'object_store_addresses': ['/tmp/ray/session_2019-01-10_13-43-57_21473/sockets/plasma_store'], 'raylet_socket_names': ['/tmp/ray/session_2019-01-10_13-43-57_21473/sockets/raylet'], 'webui_url': ''}
[2019-01-10 13:43:57,597][__main__][start_ray][INFO] 
Started Ray on this node. If you wish to terminate the processes that have been started, run

    ray stop

```

I can't do ray.init() because I guess this is the same issue.

Questions:
- Did I do something wrong in the first place ?
- Is my use case "allowed" by ray ?
- Would it be possible to ave a "--dont-rewrite-ip" or something like this that would prevent rewriting the ip ?

**Comment by konstantinmiller** [comment]
I have the same issue in a different use case. 

I have two docker containers running on my local machine (for testing purposes). One is running head, the other one worker. The head is exposing all the ports, and the worker is using `--net=host`. 

When I try to run ray in the worker container, using the same command as in the original post by @fchouteau , I'm using `127.0.0.1` as IP address. However, ray resolves it to a different IP address, which is probably the local address of the docker container. It then fails to connect to reddis.

Doing `telnet 127.0.0.1 6379` works from both the worker container, and the host.

is it possible to force ray to use `127.0.0.1` when connecting to reddis?

**Comment by TillBeemelmanns** [comment]
Did you solve that problem ? I have the same problem on a distributed cluster and I am getting the error 
`Failed to connect to ray node XXX with status: IOError: Connection refused. This may be since the node was recently removed.`

**Comment by robertnishihara** [comment]
I wouldn't expect this approach to work out of the box. One reason is that the machines need to communicate in an all-to-all manner (at least over the object manager and node manager ports).

**Comment by robertnishihara** [comment]
Can you elaborate on why you want to use port forwarding?

**Comment by thavlik** [comment]
I just tried this and ran into the same issue. Port forwarding all the service ports (which can be done with a single kubectl command) allows your pc to function as a job pod. Right now I'm trying to use it to debug jobs...

**Comment by episodeyang** [comment]
The use case is to connect to a head_node in a cluster, so that I can run local python code on the cluster workers.

**Comment by episodeyang** [comment]
Current the issue is that the ray client resolves the wrote IP address. On local, `reddis-cli` works with the host name `127.0.0.1` **and** `localhost`. However `ray` resolves to the external IP of my local worker.

**Comment by richardliaw** [comment]
@episodeyang The workaround right now is to use `ray submit {cluster.yaml} python_script.py`
