### ISSUE TITLE
[Tune] Lightning not supported 

### ISSUE THREAD

**Issue by pdr9908** [ray-project/ray#37416]
### What happened + What you expected to happen

Hello! As described [here](https://github.com/Lightning-AI/lightning/discussions/16688), pytorch lightning was renamed and the new package lightning.pytorch is not yet supported by Ray. I get the following error when trying to tune my neural net which uses the new lightning package: 

`ValueError: 'module_class' must be a subclass of 'pl.LightningModule'`

This can be fixed by replacing `import lightning.pytorch as pl` by `import pytorch_lightning as pl` (and installing the correct package); however, other parts of my code depend on the new lightning package.

### Versions / Dependencies

PyTorch Lightning 2.0.3
Lightning 2.0.3
Python 3.10.6
Ray 2.5.1

### Reproduction script

```
import lightning.pytorch as pl
from ray.train.lightning import LightningConfigBuilder


class MyNet(pl.LightningModule):
    def __init__(self) -> None:
        super().__init__()


LightningConfigBuilder().module(cls=MyNet).build()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by woshiyyya** [comment]
Hey @pdr9908 , thanks for surfacing this issue. We'll consider including the new namespace `lightning.pytorch` for LightningTrainer.

**Comment by pdr9908** [comment]
Thanks! @woshiyyya

**Comment by woshiyyya** [comment]
Resolved by this PR: https://github.com/ray-project/ray/pull/39841
