### ISSUE TITLE
[CI] `linux://python/ray/tests:test_scheduling_debug_mode` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#37423]
- 229c70bfdd22683db5430d6568b116d62ffd79e1 FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4984#01895314-144c-4bde-a258-ab99f76fdae0)
- 63fc6c9cf9f72d80ce49fc250f1392b10315dd8c FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4980#01895128-fafc-4e28-ae79-884f509d89c9)
- 8f737c4763a2953ff4b65424aa03c404e0f778c1 FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4978#018950e9-9750-4597-a3bb-10bbaf6ca4dd)
- 49e884d0faeb5b2b4213150cf2ae3d4b51d69cf9 FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4977#018950b9-6e2c-4e97-9b5a-d770a18cc0ca)
- 61401dad861bff84e4c0b82f561ff539ac54b4ff FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4976#01895074-86f7-48a4-a6b4-b8147da435a7)
- da39640a8220a1d360e7f11b0538ee93de4d5aa5 FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4975#0189506b-c7e7-4b13-ab68-febfbd57f9a8)
- 58f5de1ddb9455c8fce3dc4dc51de39d835f3aff FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4950#01894b79-0bbf-4633-b9ef-8238816cf2d1)
- efdf5a99846a0ca062500d4051aa4078a5d855bd FAILED [Buildkite :python: Debug Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/4923#01894681-a9b0-444a-a872-011dac291273)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_scheduling_debug_mode-END
....

**Comment by jjyao** [comment]
It's no longer flaky.
