### ISSUE TITLE
[rllib]compute_advantages doesn't support a critic without GAE

### ISSUE THREAD

**Issue by nflu** [ray-project/ray#3746]
Looks like this was a [planned feature](https://github.com/ray-project/ray/blob/7edc677304f90bcab0a01e9722e59e36dd9afcb0/python/ray/rllib/evaluation/postprocessing.py#L47) that got overlooked. Seems like a simple fix but maybe I'm missing something.

**Comment by ericl** [comment]
Yeah I think this is basically a couple line fix.

**Comment by richardliaw** [comment]
Hey Neil,

Would you be interested in opening a PR for the fix? We'll help you clean
it up into a good state and get it merged.

Thanks!
Richard

**Comment by nflu** [comment]
[Done.](https://github.com/ray-project/ray/pull/3778)

**Comment by roireshef** [comment]
Please look at https://github.com/ray-project/ray/pull/6941
I have been testing it to work on my project - training converges, actually better than using GAE, for my problems.
