### ISSUE TITLE
[tune] Support restoring from S3 checkpoints

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3747]
Consider supporting some subset of the following:

1. Trial Restore from S3 url.
2. Experiment restoring from S3 url.

cc @hartikainen feel free to add more details

**Comment by ericl** [comment]
Would this be a matter of rsyncing the state back when starting (since I think the checkpoint data is already synced up to s3?)

**Comment by richardliaw** [comment]
Hm, I think so. It probably isn't necessary to support
`Trial(restore=s3_path)` right?

**Comment by hartikainen** [comment]
For me, it would be extremely useful if I could:
1. Start an experiment from scratch on autoscaler 
  - `ray exec ./config/ray-autoscaler.yaml "python -m examples.development.main --mode=gce --universe=gym --domain=Swimmer --task=Default --exp-name=${EXPERIMENT_NAME} --num-samples 3 --upload-dir=gs://${GS_BUCKET}/ray/results" --start --stop --tmux`
2. Later, restore the same experiment on autoscaler
  - `ray exec ./config/ray-autoscaler.yaml "python -m examples.development.main --mode=gce --universe=gym --domain=Swimmer --task=Default --exp-name=${NEW_EXPERIMENT_NAME} --num-samples 3 --upload-dir=gs://${GS_BUCKET}/ray/results --restore=${EXPERIMENT_NAME}" --start --stop --tmux`

**Comment by richardliaw** [comment]
Should be closed by #4450.
