### ISSUE TITLE
[core][release test] many nodes regression

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#37482]
### What happened + What you expected to happen

<img width="510" alt="Screen Shot 2023-07-17 at 2 19 05 PM" src="https://github.com/ray-project/ray/assets/18510752/a46dbeb0-640e-4205-bf6a-051bf515ce64">

Seems like there was a significant regression from 7/5~7/7

It is probably due to the PR we merged and reverted. We should verify if the latest master has the same regression. 

### Versions / Dependencies

master

### Reproduction script

run many_nodes

### Issue Severity

None

**Comment by scv119** [comment]
<img width="405" alt="image" src="https://github.com/ray-project/ray/assets/837180/0951b412-5a14-4fd3-9c7c-d8188a4aa42d">
looks it recovered.

waiting game worked i guess.
