### ISSUE TITLE
[AIR] Deprecating `BatchPredictor` in favor of Ray Datasets for offline batch inference.

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#37489]
In Ray 2.6, [`ray.train.batch_predictor.BatchPredictor`](https://docs.ray.io/en/latest/ray-air/api/doc/ray.train.batch_predictor.BatchPredictor.html) will be marked as a deprecated API. It will be removed in Ray 2.7.

Please leave any comments or concerns on this thread below -- we would be happy to better understand your perspective.

## Motivation
In Ray 2.5 and master, there have been numerous improvements to the core Ray Data APIs for better usability. This removes the need for a separate, higher-level `BatchPredictor` API. As a result, we will be deprecating it in favor of having only 1 API for scalable offline batch inference.

## Migration
[`BatchPredictor.predict`](https://docs.ray.io/en/latest/ray-air/api/doc/ray.train.batch_predictor.BatchPredictor.predict.html#ray.train.batch_predictor.BatchPredictor.predict) is now replaced by using [`map_batches` directly on the Dataset](https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.map_batches.html#ray.data.Dataset.map_batches) with a class UDF.

**Before**

```python
import numpy as np
import torch
import torch.nn as nn

import ray
from ray.train.torch import TorchCheckpoint, TorchPredictor
from ray.train.batch_predictor import BatchPredictor

ds = ray.data.from_numpy(np.ones((1, 100)))
model = nn.Sequential(nn.Linear(in_features=100, out_features=1), nn.Sigmoid())

checkpoint = TorchCheckpoint.from_model(model)
batch_predictor = BatchPredictor.from_checkpoint(checkpoint, predictor_cls=TorchPredictor)
predictions = batch_predictor.predict(ds, min_scoring_workers=2, max_scoring_workers=2, dtype=torch.float32)
```

**After**
```python
from typing import Dict
import numpy as np
import torch
import torch.nn as nn

import ray

ds = ray.data.from_numpy(np.ones((1, 100)))

class TorchPredictor:
    def __init__(self):
        self.model = nn.Sequential(nn.Linear(in_features=100, out_features=1), nn.Sigmoid())
        self.model.eval()

    # Logic for inference on 1 batch of data.
    def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        tensor = torch.as_tensor(batch["data"], dtype=torch.float32)
        with torch.inference_mode():
            # Get the predictions from the input batch.
            return {"output": self.model(tensor).numpy()}

# Use 2 parallel actors for inference.
scale = ray.data.ActorPoolStrategy(size=2)
predictions = ds.map_batches(TorchPredictor, compute=scale)
```

See the [Ray Data Batch Inference user guide](https://docs.ray.io/en/master/data/batch_inference.html#) for more details.

### Migrating `BatchPredictor.predict` arguments to `dataset.map_batches`
How to migrate the full set of `BatchPredictor` arguments is described below.

| BatchPredictor.predict arguments    | dataset.map_batches                                |
|-------------------------------------|---------------------------------------------------|
| data                                | The dataset you call `map_batches` on (`data.map_batches(...)`)                   |
| feature_columns                     | Configure this in the `__call__` method of the class UDF                 |
| keep_columns                        | Configure this in the `__call__` method of the class UDF                 |
| batch_size                          | `batch_size` arg to `map_batches`                               |
| min_scoring_workers                 | `ActorPoolStrategy` passed as the `compute` arg to `map_batches`      |
| max_scoring_workers                 | `ActorPoolStrategy` passed as the `compute` arg to `map_batches`      |
| num_cpus_per_worker                 | `num_cpus` arg to `map_batches`                                  |
| num_gpus_per_worker                 | `num_gpus` arg to `map_batches`                                  |
| separate_gpu_stage                  | No longer applicable                                          |
| ray_remote_args                     | `**kwargs` to `map_batches`                                      |
| **predict_kwargs                    | No longer applicable                                          |

### Can I still use AIR Checkpoints?

Yes, you can still continue to use AIR Checkpoints instead of loading in a pre-trained model directly. 

In the `__init__` method of the callable class UDF, you can extract the model from your Checkpoint to use for inference. Then you can call the fitted preprocessor and the model in the `__call__` method.

```python
import numpy as np
import torch
import torch.nn as nn

import ray
from ray.train.torch import TorchCheckpoint
from ray.train.batch_predictor import BatchPredictor

ds = ray.data.from_numpy(np.ones((1, 100)))
model = nn.Sequential(nn.Linear(in_features=100, out_features=1), nn.Sigmoid())

checkpoint = TorchCheckpoint.from_model(model)

# Extract and apply the fitted preprocessor if applicable.
fitted_preprocessor = checkpoint.get_preprocessor()
preprocessed_ds = fitted_preprocessor.transform(ds)

class TorchPredictor:
    def __init__(self):
        self.model = checkpoint.get_model()

    # Logic for inference on 1 batch of data.
    def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        tensor = torch.as_tensor(batch["data"], dtype=torch.float32)
        with torch.inference_mode():
            # Get the predictions from the input batch.
            return {"output": self.model(tensor).numpy()}

# Use 2 parallel actors for inference.
scale = ray.data.ActorPoolStrategy(size=2)
predictions = preprocessed_ds.map_batches(TorchPredictor, compute=scale)
```

### How do I specify `feature_columns` and `keep_columns`?
You can do this in the `__call__` method of your class UDF.

```python
from typing import Dict
import torch
import torch.nn as nn

import ray

ds = ray.data.read_images(...)

feature_column = "feature"
keep_column = "label"

class TorchPredictor:
    def __init__(self):
        self.model = ...
        self.model.eval()

    # Logic for inference on 1 batch of data.
    def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        tensor = torch.as_tensor(batch[feature_column], dtype=torch.float32)
        with torch.inference_mode():
            # Get the predictions from the input batch.
            return {"output": self.model(tensor).numpy(), keep_column: batch[keep_column]}

# Use 2 parallel actors for inference.
scale = ray.data.ActorPoolStrategy(size=2)
predictions = ds.map_batches(TorchPredictor, compute=scale)
```

### Can I still use built-in Predictors?

Yes, you can still use built-in Predictors by wrapping them in a class UDF.

```python
import numpy as np
import torch
import torch.nn as nn

import ray
from ray.train.torch import TorchCheckpoint
from ray.train.batch_predictor import BatchPredictor

ds = ray.data.from_numpy(np.ones((1, 100)))
model = nn.Sequential(nn.Linear(in_features=100, out_features=1), nn.Sigmoid())

checkpoint = TorchCheckpoint.from_model(model)

# Extract and apply the fitted preprocessor if applicable.
fitted_preprocessor = checkpoint.get_preprocessor()
preprocessed_ds = fitted_preprocessor.transform(ds)

class TorchPredictorWrapper:
    def __init__(self):
        self.predictor = TorchPredictor(model=checkpoint.get_model(), use_gpu=True)

    # Logic for inference on 1 batch of data.
    def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        return self.predictor.predict(batch)

# Use 2 parallel actors for inference.
scale = ray.data.ActorPoolStrategy(size=2)
predictions = preprocessed_ds.map_batches(TorchPredictorWrapper, compute=scale, num_gpus=1)
```

**Comment by anyscalesam** [comment]
@amogkam is this done? If so - can you close?
