### ISSUE TITLE
[data] Add single-node data ingest benchmark to release tests

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#37497]
### Description

Re-enable / update ray-data-bulk-ingest* release tests to use the streaming backend. We should test the following:
- tf.data vs ray.data on preprocessed TFRecords:
  - 32 vs 512 imgs/file
  - w/ and w/o transforms
- torch dataloader vs ray.data
  - from local images vs S3
  - w/ and w/o transforms

**Comment by c21** [comment]
This is done. Closing the issue.
