### ISSUE TITLE
[dashboard] Option to generate flame-graph for Python workers

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#37491]
### Description

The driver flamegraph is very useful but often we want to see the flamegraph for actual tasks too. It would be great to have an opt-in way to do this for workers.

**Comment by stephanie-wang** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
It is actually already possible (you can do it from the cluster view)?

**Comment by rkooo567** [comment]
@stephanie-wang can you lmk if ^ satisfies your requirement? I will close the issue for now
