### ISSUE TITLE
<Ray document: tune>

### ISSUE THREAD

**Issue by DavidYoonsik** [ray-project/ray#37505]
### Description

![스크린샷 2023-07-17 오후 6 12 38](https://github.com/ray-project/ray/assets/9669800/0d7b5875-a227-4b65-954a-53d78a0e767f)

**Comment by DavidYoonsik** [comment]
Fixed typo

**Comment by angelinalg** [comment]
Fixed in master. Thank you!
<img width="803" alt="Screenshot 2023-08-01 at 11 49 43 AM" src="https://github.com/ray-project/ray/assets/122562471/55f9d43e-075c-4d85-b9a9-9db881ebd676">
