### ISSUE TITLE
Ray depends on pytest in setup.py

### ISSUE THREAD

**Issue by devin-petersohn** [ray-project/ray#3751]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: WSL
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.1
- **Python version**: 3.6
- **Exact command to reproduce**: `pip install ray`

### Describe the problem

I don't think we need to be depending on `pytest` for the library itself. If travis needs pytest, we can just install it in `install_dependencies` script. Is there a particular reason that ray depends on `pytest` always?

### Source code / logs
N/A

**Comment by robertnishihara** [comment]
I guess one option is to put it in `tests_require`, e.g.,

https://github.com/apache/arrow/blob/54b35b4c13a8904286eca80bb76d9f4e7b619a87/python/setup.py#L556-L557

**Comment by devin-petersohn** [comment]
Is it a jenkins issue? We have a `requirements.txt` in Modin that includes all the testing requirements.

**Comment by richardliaw** [comment]
We should just put it in .travis.yml and requirements.txt for jenkins,
right?

**Comment by robertnishihara** [comment]
It should be in the `setup.py` because the tests depend on it. If not `install_requires` then at least `tests_require`.

We don't have a `requirements.txt`.

Out of curiosity, what is the issue with the current approach?

**Comment by devin-petersohn** [comment]
In the spirit of python, we should only install what is necessary for the users' environments as `install_requires`. More specifically for me, Modin tests rely on a specific version of pytest, and this overwrites it every time. I think it should be in `tests_require` as it is not a dependency of Ray itself.

**Comment by olivierlefloch** [comment]
Would it be possible to move `pytest` out of the installation requirements (`tests_require` would be fine)? I don't want to install it in the code I deploy, but `ray` requires it as things stand.

**Comment by robertnishihara** [comment]
I agree with that. It should only be necessary for the tests.
