### ISSUE TITLE
[Serve] Ingress applications start up "successfully" even if their startup hook fails

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/ray#37575]
### What happened + What you expected to happen

When an ASGI app is used as an `ingress` in a Ray Serve application, if the `startup` lifecycle event fails, Ray Serve still considers the application to have successfully started up.

This causes issues because the application might not be in a stable/correct state if startup fails. For example, I'm running Ray Serve under KubeRay. We start various background `async` tasks in our `startup` event via the Starlette/FastAPI [`lifespan` hook](https://fastapi.tiangolo.com/advanced/events/#lifespan-events). If these tasks fail to be started for whatever reason, we want the Serve application deployment to fail so that (for example) a newly-started `RayService` does not become stable and replace the old (presumably working) `RayService` (and then KubeRay would retry until it worked). The same would apply to individual Serve deployment replicas running inside an existing `RayService`.

The relevant code seems to be at https://github.com/ray-project/ray/blob/ae783b54f8e1d16cace4ad8a616486f3d2faef58/python/ray/serve/_private/http_util.py#L402
which is where the startup event is triggered by the Serve replica.

Looking at the equivalent block in `uvicorn`, they check whether the `lifespan` says they should exit after startup: https://github.com/encode/uvicorn/blob/8239373ec649b1a41179070b6ba2c8dc549df63e/uvicorn/server.py#L63-L92

The failure is recorded on the lifespan object here https://github.com/encode/uvicorn/blob/8239373ec649b1a41179070b6ba2c8dc549df63e/uvicorn/lifespan/on.py#L115-L121 and here https://github.com/encode/uvicorn/blob/8239373ec649b1a41179070b6ba2c8dc549df63e/uvicorn/lifespan/on.py#L45-L60

### Versions / Dependencies

```console
$ python --version
Python 3.10.6
```

```console
$ pip list
Package                      Version
---------------------------- ----------
ray                          2.5.1
starlette                    0.27.0
uvicorn                      0.23.1
```

### Reproduction script

```python
# lifespan_example.py

from contextlib import asynccontextmanager
from typing import AsyncIterator

from fastapi import FastAPI
from ray import serve
from starlette.responses import PlainTextResponse


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    raise Exception("Failing app startup...")

    yield


app = FastAPI(lifespan=lifespan)


@app.get("/liveness")
def liveness() -> PlainTextResponse:
    return PlainTextResponse("ok")


@serve.deployment
@serve.ingress(app)
class FastAPIDeployment:
    pass


serve_app = FastAPIDeployment.bind()
```

Running this under Ray Serve does show the error, but afterwards, Ray Serve still considers the application to have started successfully:

```console
$ serve run lifespan_example:serve_app
2023-07-19 12:30:47,544	INFO scripts.py:404 -- Running import path: 'lifespan_example:serve_app'.
2023-07-19 12:30:50,750	INFO worker.py:1627 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
(ServeController pid=21332) INFO 2023-07-19 12:30:55,025 controller 21332 deployment_state.py:1298 - Deploying new version of deployment default_FastAPIDeployment.
(HTTPProxyActor pid=21339) INFO:     Started server process [21339]
(ServeController pid=21332) INFO 2023-07-19 12:30:55,087 controller 21332 deployment_state.py:1537 - Adding 1 replica to deployment default_FastAPIDeployment.
(ServeReplica:default_FastAPIDeployment pid=21340) Traceback (most recent call last):
(ServeReplica:default_FastAPIDeployment pid=21340)   File ".../lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
(ServeReplica:default_FastAPIDeployment pid=21340)     async with self.lifespan_context(app) as maybe_state:
(ServeReplica:default_FastAPIDeployment pid=21340)   File ".../lib/python3.10/contextlib.py", line 199, in __aenter__
(ServeReplica:default_FastAPIDeployment pid=21340)     return await anext(self.gen)
(ServeReplica:default_FastAPIDeployment pid=21340)   File ".../lifespan_example.py", line 11, in lifespan
(ServeReplica:default_FastAPIDeployment pid=21340)     raise Exception("Failing app startup...")
(ServeReplica:default_FastAPIDeployment pid=21340) Exception: Failing app startup...
(ServeReplica:default_FastAPIDeployment pid=21340)
(ServeReplica:default_FastAPIDeployment pid=21340) Application startup failed. Exiting.
2023-07-19 12:30:57,052	SUCC scripts.py:424 -- Deployed Serve app successfully.
```

And lets it serve requests:
```console
$ curl 'localhost:8000/liveness'
ok
```

```
2023-07-19 12:34:26,943	SUCC scripts.py:424 -- Deployed Serve app successfully.
(ServeReplica:default_FastAPIDeployment pid=21670) INFO 2023-07-19 12:34:31,448 default_FastAPIDeployment default_FastAPIDeployment#DAdLem vNtWwaRikF /liveness default replica.py:654 - __CALL__ OK 6.7ms
```

If you try the same thing under `uvicorn`, the applications fails to start up, as expected:

```console
$ uvicorn lifespan_example:app
INFO:     Started server process [21710]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File ".../lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File ".../lifespan_example.py", line 11, in lifespan
    raise Exception("Failing app startup...")
Exception: Failing app startup...

ERROR:    Application startup failed. Exiting.
```

And just to prove the point, it's not running after startup fails:
```console
$ curl 'localhost:8000/liveness'
curl: (7) Failed to connect to localhost port 8000 after 5 ms: Couldn't connect to server
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by edoakes** [comment]
@JoshKarpel thanks for the detailed writeup! This looks to just be an oversight on our end; this should definitely cause the replica to fail to start.

Would you be interested in contributing a fix? Should be as simple as checking the `lifespan.should_exit` and raising an exception from within [_run_asgi_lifespan_startup](https://github.com/ray-project/ray/blob/ae783b54f8e1d16cace4ad8a616486f3d2faef58/python/ray/serve/_private/http_util.py#L396)

**Comment by edoakes** [comment]
I would suggest putting a test in [test_fastapi](https://github.com/ray-project/ray/blob/master/python/ray/serve/tests/test_fastapi.py).

You should just need to `serve.run` an application whose deployment fails ASGI lifespan on and check that it raises a `RuntimeError`.

**Comment by JoshKarpel** [comment]
> Would you be interested in contributing a fix? Should be as simple as checking the `lifespan.should_exit` and raising an exception from within [_run_asgi_lifespan_startup](https://github.com/ray-project/ray/blob/ae783b54f8e1d16cace4ad8a616486f3d2faef58/python/ray/serve/_private/http_util.py#L396)

Can do! Questions:
1. Is there a particular exception I should raise? It looks like the underlying error isn't stored on the `LifespanOn`, unfortunately 🤔 
2. Is there a particular method/pattern for testing this kind of thing somewhere in the test suite?

**Comment by edoakes** [comment]
Sigh @ the exception not being stored. That should be ok -- I assume it will get printed to the logs anyways.

I'd suggest raising a `RuntimeError` like:
```python
raise RuntimeError("ASGI LifespanOn event failed. Check replica logs for details.")
```
