### ISSUE TITLE
[Serve] Confusing output in controller logs

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#37589]
### What happened + What you expected to happen

<img width="1188" alt="Screenshot 2023-07-18 at 4 03 10 PM" src="https://github.com/ray-project/ray/assets/9677264/091b0b0f-b66a-4df1-95c3-95adb9e9aae8">

Is "task" a Ray task? If not, can we avoid using it in case of confusion.

Can we change it to something like?

> Deployed app '...' successfully

### Versions / Dependencies

~~Nightly~~  2.4

### Reproduction script

n/a

### Issue Severity

Low: It annoys or frustrates me.

**Comment by shrekris-anyscale** [comment]
Yep, it's a Ray task. When a Serve app is launched via config file, a Ray task is used to pull its `runtime_env` and start the app.

I agree that the log is a bit confusing, so we should update that as you suggested.

**Comment by zcin** [comment]
Hi @scottsun94, do you have a repro script? It's strange that the name is an empty string on nightly, we should have disallowed that.

**Comment by scottsun94** [comment]
@zcin 
actually, it was on 2.4, not nightly. My fault. The empty string is probably normal in 2.4.
