### ISSUE TITLE
[Docs] Fix broken example links and add them back in to the example gallery

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#37618]
### Description

Previously, two examples were removed to fix linkcheck issues, and are omitted from the example gallery: https://github.com/ray-project/ray/pull/37502. We should add these back in with corrected links:

- https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_roboschool_ray
- https://www.uber.com/blog/elastic-xgboost-ray/

FYI @simran-2797 @angelinalg

**Comment by simran-2797** [comment]
@peytondmurray 
We should remove the first example.
We can add the second example in the example gallery (and link it to uber blog)

**Comment by peytondmurray** [comment]
@simran-2797 What's the fixed link for the second example? When I last checked the one given above was failing linktest checks.

**Comment by simran-2797** [comment]
Syncing on slack.

**Comment by anyscalesam** [comment]
Per check in with @peytondmurray there is still one example that is broken; @simran-2797 were you going to chase down where it should redirect to?

**Comment by simran-2797** [comment]
The 1st example is not a valid example anymore because it was removed. @peytondmurray, following up on our chat on Slack a few weeks back, did you get a chance to add the second link to the example gallery and try the linktest checks? 
cc: @anyscalesam
