### ISSUE TITLE
[<Ray Docs>] Request Ray dashboard metrics reference 

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#37615]
### Description

From recent Ray docs IA user sessions, we found **a common question** users ask:
❓“Is there a list like API reference for what metrics Ray dashboard serves?”

**Why do users ask this question?**
Users associate metrics with Monitoring and Debugging, and look for information leading by metrics: 
 - “What metrics does the Ray dashboard serve?”
 - “How to collect the metrics?”
 - “How to consume the metrics?” 

**improvements to make:**

- Add the list of available metrics reference in Ray dashboard documentation
cc. @scottsun94 @angelinalg

**Comment by WIND-D** [comment]
2/6 users asked about these questions in the sessions.

**Comment by Wendi-anyscale** [comment]
https://github.com/ray-project/ray/issues/37631. resolves the question of "How to collect and consume metrics" for Cluster launcher and KubeRay. 

Like API reference, the user brought up a good point on having a  single hub of the truth: a complete list of all the available metrics to find specific metrics faster.

Worth considering providing a table or list view?

**Comment by scottsun94** [comment]
> Like API reference, the user brought up a good point on having a single hub of the truth: a complete list of all the >available metrics to find specific metrics faster.
>
>Worth considering providing a table or list view?

There is already one: https://docs.ray.io/en/latest/ray-observability/reference/system-metrics.html#system-metrics. And the user did notice it while he walked through the "[Collecting and monitoring metrics](https://docs.ray.io/en/latest/cluster/metrics.html)" page with us in the call. The main issue is that he couldn't find this page originally when he went through the KubeRay get started example. This is what we tried to address in https://github.com/ray-project/ray/issues/37631.


Btw, we should to the other user too and understand why they had this issue.

**Comment by Wendi-anyscale** [comment]
sg, I will provide more data points when other users meet related issues.
