### ISSUE TITLE
[tune] local storage_path treated as remote on windows

### ISSUE THREAD

**Issue by MatFl** [ray-project/ray#37639]
### What happened + What you expected to happen

On a windows machine running a local experiment using tune.run wrongly uses the user dir.
When setting storage_path to a relative local dir (e.g. ./results) is expanded to an absolute path in the experiment:
https://github.com/ray-project/ray/blob/6fcbb6a6c561ea9e60abeef23f22a8bae2883211/python/ray/tune/experiment/experiment.py#L175

This path then starts with C:\\...

The trial_runner gets fed this full path of the experiement and also tries to resolve local and remote path from it.
https://github.com/ray-project/ray/blob/6fcbb6a6c561ea9e60abeef23f22a8bae2883211/python/ray/tune/execution/trial_runner.py#L153

The check in the utils treats the drive letter C:\\ as a scheme and thus uses the default path (userdir) for the local path.
https://github.com/ray-project/ray/blob/6fcbb6a6c561ea9e60abeef23f22a8bae2883211/python/ray/tune/utils/util.py#L185

### Versions / Dependencies

2.6.0

### Reproduction script

# simplified
ray.init(local_mode=True)
tune.run({"storage_path" : "./results"})

### Issue Severity

Low: It annoys or frustrates me.

**Comment by RocketRider** [comment]
I just faced the same issue! But for me it was crashing the training as it tried to save something without the needed permission to do so at the user folder.

**Comment by xwjiang2010** [comment]
@MatFl, thanks for the detailed report. The issue seems to be that urllib doesn't interpret windows path correctly. To unblock you, is it possible to add `if parsed.scheme and parsed.scheme not in ["C:\", ...]` to the line you pointed to?

@krfricke @justinvyu fyi, seems we are getting rid of using `urllib` and will just use pyarrow (which handles windows path correctly) soon?

**Comment by justinvyu** [comment]
This should be fixed in 2.7+.
