### ISSUE TITLE
python: air/_internal

### ISSUE THREAD

**Issue by path-park** [ray-project/ray#37652]
### What happened + What you expected to happen

When we don't have pyarrow installed import ray, we see:
```
    _cached_fs: Dict[tuple, Tuple[float, pyarrow.fs.FileSystem]] = {}
E   AttributeError: 'NoneType' object has no attribute 'fs'
```

in remote_storage.py, there is a try to catch exception when importing pyarrow, but it does not check that pyarrow was imported before attempting to use pyarrow.fs on this line:

[remote_storage.py](
https://github.com/ray-project/ray/blob/30d0c0dfc0a17444b230ab7f6fe295482f8da728/python/ray/air/_internal/remote_storage.py#L142)

### Versions / Dependencies

pyarrow is *not* installed

### Reproduction script

```
from ray import tune
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by richardliaw** [comment]
cc @justinvyu @matthewdeng @ericl 

Do we need to make pyarrow a requirement for Tune?

**Comment by matthewdeng** [comment]
It already is:

https://github.com/ray-project/ray/blob/a0fdde1ab10ae4c0d8e2249f6122c9159eb1963f/python/setup.py#L273

**Comment by path-park** [comment]
ok it looks like I was not correctly specifying the "tune" extra. Sorry about the spurious issue. Thanks!
