### ISSUE TITLE
[Cluster] ray up doesn't work in 2.6

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#37664]
### What happened + What you expected to happen

`ray up python/ray/autoscaler/aws/example-full.yaml` can create the cluster with head node but worker node cannot be started correctly. The error message is that it cannot connect to GCS.

### Versions / Dependencies

2.6

### Reproduction script

`ray up python/ray/autoscaler/aws/example-full.yaml`, changing min_workers for worker node to `1`.

### Issue Severity

None

**Comment by rkooo567** [comment]
@rickyyx @scv119 and I identified the root cause (thanks @matthewdeng being present around us while we are debugging). @rickyyx's going to take over the issue. Here's the root cause; https://github.com/ray-project/ray/pull/35649/files
