### ISSUE TITLE
[Core] Importing ray disables all pre-existing loggers after version 2.6

### ISSUE THREAD

**Issue by zigaLuksic** [ray-project/ray#37711]
### What happened + What you expected to happen

After the changes in 2.6.0 importing `ray` disables all pre-existing loggers, for example:
```python
LOGGER = logging.getLogger(__name__)

assert not LOGGER.disabled

import ray

assert LOGGER.disabled
```
Loggers created after `ray` has been imported are fine. This is causing issues for us in cases where a different package is imported before `ray` is, since we are unable to access it's logs.

The logger disabling happens [here](https://github.com/ray-project/ray/blob/master/python/ray/_private/log.py#L130). If this was not intended, one can add the option `'disable_existing_loggers': False` when creating `dictConfig`.

If this was intended, I would greatly appreciate any tips on what the official approach is.

### Versions / Dependencies

tested on Python 3.11 with `ray >= 2.6.0`

### Reproduction script

```python
LOGGER = logging.getLogger(__name__)

assert not LOGGER.disabled

import ray

assert LOGGER.disabled
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rkooo567** [comment]
cc @rickyyx (we should track this for 2.6.2)

**Comment by peytondmurray** [comment]
There's already a PR open for this: https://github.com/ray-project/ray/pull/36306.

**Comment by garrettwrong** [comment]
We also encountered this in ASPIRE unit tests (some check logger outputs).  Following. Thanks.
