### ISSUE TITLE
[Ray Data] Cannot delete and release resources of a Ray Dataset with streaming_split in the middle of `iter_batches`

### ISSUE THREAD

**Issue by lee1258561** [ray-project/ray#37721]
### What happened + What you expected to happen

One of the use case we want to achieve is that we want to consume a dataset for the first X iteration of training, and then switch to another dataset for Y iteration of training, and that is not a full epoch. Not calling the next() on the iterator won’t stop the dataset to process the data from the background. And _MapWorker still occupied the CPU and memory to prevent other dataset execution

We try to do:
```
del dataset_iterator 
```
but it does not shutdown the StreamingExecutor

While if I explicitly do:
```
ray.kill(dataset_iterator._coord_actor)
```
I managed to kill all the _MapWorker. it seems like the StreamExecutor is only init in the SplitCoordinator, and don't have any hooks to shutdown from DatasetIterator or Dataset. It will be great to introduced some hooks in the DatasetIterator to terminal the executor in the middle of execution.

### Versions / Dependencies

Python: 3.8
Ray: 2.4.0, 2.6.0

### Reproduction script
```
import ray
import time


def pause(x):
    time.sleep(1)
    return x


ds = ray.data.range(10000000)
ds = ds.map_batches(
    pause,
    compute=ray.data.ActorPoolStrategy(
        min_size=30,
        max_size=30,
        max_tasks_in_flight_per_actor=1,
    )
)


NUM_WORKERS = 8
NUM_ITERS = 5


@ray.remote
def consume(it):
    cur_iter = 0
    for x in it.iter_batches():
        if cur_iter >= NUM_ITERS:
            break

        time.sleep(3)
        cur_iter += 1

    print(f"Base dataset: {it._base_dataset._current_executor}")
    print(f"coordinator: {it._coord_actor}")
    
    del it  # This does not work
    # ray.kill(it._coord_actor)  # Need to explicitly kill SplitCoordinator


    # Expect: After deleting should see ray dashboard has no _MapWorker alive.
    # Actual: _MapWorker is alive until the program ended.
    print("I stopped")
    time.sleep(120)


iters = ds.streaming_split(NUM_WORKERS)
ray.get([consume.remote(it) for it in iters])
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ericl** [comment]
cc @raulchen @c21

**Comment by anyscalesam** [comment]
@lee1258561 is this still an issue?
