### ISSUE TITLE
[Core] [Dead link] Dead link to the ray logging page

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#37803]
### What happened + What you expected to happen

One of the OSS users reported the dead link to ray loggin gpage.
![342e1d19a53fc91802dcfe1fdb888a46](https://github.com/ray-project/ray/assets/9677264/24711352-b1da-48cf-bbef-5e34dd657acd)

https://docs.ray.io/en/latest/ray-observability/ray-logging.html 

### Versions / Dependencies

2.6.1

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
I have added a redirect rule on readthedocs.com and the link itself should work now but we need to fix the code.

**Comment by kevin85421** [comment]
I am currently going through observability issues and have opened a PR at https://github.com/ray-project/ray/pull/44073 to fix this issue.
