### ISSUE TITLE
[data] Retry failed write tasks internally

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#37813]
### Description

Write tasks can fail due to transient errors like rate limiting. We should retry the write internal to the task, which is cheaper.

**Comment by anyscalesam** [comment]
@bveeramani have we completed this yet?

**Comment by bveeramani** [comment]
@c21 this was fixed by https://github.com/ray-project/ray/pull/38773, right?

**Comment by bveeramani** [comment]
Fixed by https://github.com/ray-project/ray/pull/41263 and https://github.com/ray-project/ray/pull/38773
