### ISSUE TITLE
[rllib] Saving episode trajectories during training

### ISSUE THREAD

**Issue by mzat-msft** [ray-project/ray#37849]
### What happened + What you expected to happen

I would like to save for each episode the observation space and action space with timestep granularity.
The way I’m trying to achieve this is using the on_postprocess_trajectory callback. There, I have both postprocessed_batch and original_batches that provide access to a SampleBatch object. In that object, I have what seems to be actions, but these actions are transformed.
Is there an easy way to get the environment representation of the action?

### Versions / Dependencies

ray==2.5.0

### Reproduction script
```python
class TrajectoryCallback(DefaultCallbacks):
    def on_postprocess_trajectory(
        self,
        *,
        worker,
        episode,
        agent_id,
        policy_id,
        policies,
        postprocessed_batch,
        original_batches,
    ):
        obs = postprocessed_batch['obs']
        actions = postprocessed_batch['actions']
        episode_id = postprocessed_batch['eps_id']
        rewards = postprocessed_batch['rewards']
        terminated = postprocessed_batch['terminateds']
        truncated = postprocessed_batch['truncateds']
        step_id = postprocessed_batch['t']
```
### Issue Severity

None

**Comment by ArturNiederfahrenhorst** [comment]
Hi @mzat-msft,

```
from ray.rllib.utils.spaces.space_utils import get_original_space
from ray.rllib.models.modelv2 import restore_original_dimensions

```

From worker, you can get the observation space with `worker.observation space`
You can then restore the original dimensions with `restore_original_dimensions`.

Feel free to reopen the issue if things don't work.

**Comment by mzat-msft** [comment]
Thanks Artur, that should help for the `observation_space`, however I was actually after the `action_space`. Any pointer for that?

**Comment by ArturNiederfahrenhorst** [comment]
I've updated my original comment to include more info in this!
