### ISSUE TITLE
[CI] `bk://:windows: Wheels` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#37867]
- 4297ca6c2a363c982de14722e4d9bae7812eb44f FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5178#018998c6-40f7-49f0-ab3e-76e28bbe0ebb)
- a92899d7120aac2ebc2b4b338e6ded0fb946d9ad FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5177#0189988c-7293-4047-aecc-6a8e16e86a5f)
- 8e4b6b0dd21a588e4d4fb83afb9a5f7819e3678f FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5176#01899847-80f5-49ba-939a-1b4b8dd2fad6)
- 5ce25a57a0949673d17f3a8784f05b2d65290524 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5175#018997f3-8c80-4a78-a00a-36c1625570d3)
- cd328f949ebb6adaac1bd3f73221bc87792a0fa6 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5174#01899599-e510-4808-abdd-439fdb55be41)
- 49b4e8bd33219e53ac535f60c51ac9b44b7cbb3b FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5173#018994c8-4d5d-4c93-ac51-46375186b231)
- 1ab20e852ff83b70a5c85b1ddb7647ed309bb9d8 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5172#018994bc-e9d5-4a15-905b-5d8ea8772805)
- 56b52705d5dcd6562a1dc9f2c11d8f362146db87 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5171#018994b9-b6b6-440e-b0f3-4253b39b27e7)
- 052fb7899a1f966f8fa5223601c5fb4542dea2ae FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5170#0189944f-badd-4cca-a9d5-d1e101f4751e)
- 9952c3ab2e2be808c5dafc8064dbfaec36708f95 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5169#018993c2-42d4-45b6-bcac-d525d31102c4)
- f42872abe3dcc49520206ef07bc9501c82f21a49 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5165#01899394-e6db-4a5e-92ae-02c6daefc8d0)
- d2b573052b613d482297f908bbf6373b134ab1ec FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5164#01899369-419f-4279-b203-eeeb284d2505)
- 8a4cb0cf756e32ccd58f725e287d397f6dc5364b FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5163#01899357-7289-4057-ac2f-170833d8d557)
- f29dafb3b9ac1fbc1163c590c246a62bde73e470 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5162#01899374-3227-4209-afde-01d49bf6e747)
- b3d141f9f8237110e566842ae58367a7fc19487b FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5161#0189932e-b236-4efd-ab1f-98bd989d07a5)
- 945304e69b64d7d576cd2e2b1b5f9ee4ca874bfa FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5160#0189932e-db17-4c04-b6b4-820102780fe5)
- b344fee5c443d56f3bfd62acb167b270b1c5fab0 FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5159#0189932a-0ab5-4b28-84e3-9527e1bb4ec0)
- 68410b64476982166539ae3dcd527bce03a69a6e FAILED [:windows: Wheels](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5157#018992cb-4cd7-480e-9d50-39398814beb3)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-bk://:windows: Wheels-END
....

**Comment by can-anyscale** [comment]
conda is probably installed when the rayproject/buildenv:windows image is built. I'm not sure what pipeline builds that though. @rickyyx or @krfricke do you know? thankkks

**Comment by mattip** [comment]
Maybe [this](https://github.com/ray-project/buildkite-ci-stack/blob/b588d47be2a1946f2575b36d4972adbb0d6c2a79/packer/windows/docker/install/miniconda.ps1#L1) is relevant, from the ray-project/buildkite-ci-stack repo?
That is installing Miniconda3-py38_4.10.3-Windows-x86_64.exe, from two years ago, where the latest is Miniconda3-py38_23.5.2-0-Windows-x86_64.exe

**Comment by mattip** [comment]
Closed by #38022
