### ISSUE TITLE
[Data] `FileNotFound` error when using local scheme

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#37866]
### What happened + What you expected to happen

I tried to read some images from the head node using the local scheme, but the file metadata provider raised an error saying that the file couldn't be found. 

This bug might occur because metadata fetching tasks aren't scheduled on the head node (even when you use the `local://` scheme):

https://github.com/ray-project/ray/blob/d7dfdd8cc7614a959a3190aef4a8da5c23c4f518/python/ray/data/datasource/file_based_datasource.py#L800-L809

### Versions / Dependencies

Ray: 56b52705d5dcd6562a1dc9f2c11d8f362146db87
Arrow: 6.0.1

### Reproduction script

@xwjiang2010 

### Issue Severity

Medium

**Comment by xwjiang2010** [comment]
Probably due to some nuances with how my workspace is set up. Closing it for now. But thanks Balaji!
