### ISSUE TITLE
[AIR]: duplicated value of session.get_world_rank() 

### ISSUE THREAD

**Issue by chongxiaoc** [ray-project/ray#37873]
### What happened + What you expected to happen

`session.get_world_rank()` returns same rank value in different workers.
This seems a bug since we expect each Ray worker gets different rank value.

### Versions / Dependencies

Ray 2.5.0
PyTorch 2.0.1

### Reproduction script

```
import os
import ray

from ray.air import session
from ray.air.config import ScalingConfig
from ray.train.torch.torch_trainer import TorchTrainer

ray.init()

######## Using it in the *per worker* train loop (TrainSession) #######
def train_func():
    print("world size: %d, world rank: %d." % (session.get_world_size(), session.get_world_rank()))

trainer_init_config = {}
scaling_config = ScalingConfig(num_workers=4, use_gpu=True, resources_per_worker={"GPU": 1, "CPU": 4})
trainer = TorchTrainer(
    train_loop_per_worker=train_func,
    scaling_config=scaling_config
)
result = trainer.fit()

ray.shutdown()
```

Expected:

```
world size: 4, world rank:  0.
world size: 4, world rank:  1.
world size: 4, world rank:  2.
world size: 4, world rank:  3.

```

Got:

```
(RayTrainWorker pid=37158) world size: 4, world rank: 0.
(RayTrainWorker pid=37159) world size: 4, world rank: 1. [repeated 3x across cluster]

```

If I set `os.environ["RAY_DEDUP_LOGS"] = "0"`, it doesn't help

```
(RayTrainWorker pid=37801) world size: 4, world rank: 0.
(RayTrainWorker pid=37802) world size: 4, world rank: 1. [repeated 3x across cluster]
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
I think the dedupe thing is fuzzy matching. Assigning to Core team to see why turning off dedup logs doesn't help.

**Comment by matthewdeng** [comment]
You may need to set `os.environ["RAY_DEDUP_LOGS"] = "0"` when starting your Ray cluster. 

The implementation of the log duplication is that it will ignore numbers, so it would consider these outputs from different workers the same and de-duplicatable.

**Comment by chongxiaoc** [comment]
> You may need to set `os.environ["RAY_DEDUP_LOGS"] = "0"` when starting your Ray cluster.

Okay, let me try this.

**Comment by chongxiaoc** [comment]
verified it is working with 
```
export RAY_DEDUP_LOGS=0 ray start ...
```
```
(RayTrainWorker pid=4498) world size: 4, world rank: 3.
(RayTrainWorker pid=4495) world size: 4, world rank: 0.
(RayTrainWorker pid=4497) world size: 4, world rank: 2.
(RayTrainWorker pid=4496) world size: 4, world rank: 1.
Trial TorchTrainer_c082a_00000 completed. Last result: 
```

thx @matthewdeng
