### ISSUE TITLE
[Dashboard] When a certain number of jobs are submitted, the job interface is unstable

### ISSUE THREAD

**Issue by AndreKuu** [ray-project/ray#37894]
### What happened + What you expected to happen

When I submit some jobs to a header node, the job API became unstable. Head node has a lot of resources, like CPU and mem. But the concurrency capability is still not very good. Here are the some cases:
1. When there are over 30 running jobs, for example, Submitting jobs with jobs api became easy to fail. What I mean is not just that there will be a lot of pending jobs, Instead, submit an interface error or timeout. I am curious why the concurrency ability is several orders of magnitude weaker than I imagined.
2. Still the scene above, some pending jobs or running jobs easy to become a failed state.I can confirm that this is not the job itself failed. I consider that it may caused by job agent itself.
3. some loading errors like these:
![image](https://github.com/ray-project/ray/assets/76543919/0484a732-c2f0-4c99-bd69-a3f119de68d0)
4. When over 400 jobs are completed, new job cannot submit successfully any more.
5. Besides submitting interfaces, Under high load conditions(Only a few dozen tasks), stop job API and some other job related api also unstable.

Any advice? Close log redirection to head node will help? 

### Versions / Dependencies

2.5.0

### Reproduction script

Some simple concurrent test job script.

### Issue Severity

None

**Comment by GeneDer** [comment]
Hi @AndreKuu Can you describe your environment and the script you are running a bit more and maybe try out a newer version of Ray (e.g. 2.7.1)? 

I ran the following scripts
```
# long_running.py
import ray
import time

@ray.remote
def hello_world(time_diff):
    return f"hello world: {time_diff}"

ray.init()
start_time = time.time()
diff = time.time() - start_time
while diff < 600:
    print(ray.get(hello_world.remote(diff)))
    time.sleep(1)
    diff = time.time() - start_time

```
and submit job with 
```
# script.sh
#!/bin/bash

counter=1
while [ $counter -le 500 ]
do
echo $counter
((counter++))
ray job submit -- python long_running.py --no-wait &
done
echo All done

```

Ran `script.sh` on Anyscale Workspace with m5.8xlarge instance and Ray 2.7.1. It has no issue submitting and completing 500 of those jobs in parallel
![image (1)](https://github.com/ray-project/ray/assets/7553988/80a797cf-a7b5-492e-ade6-521199dba458)

Quickly submitting another 100 of the same jobs also completed successfully
![image (2)](https://github.com/ray-project/ray/assets/7553988/ff29719d-ced0-4783-bbfe-a49e7b3a851c)

**Comment by GeneDer** [comment]
@AndreKuu Ping again to see if you have tried it on newer version of Ray and still seeing this issue or if we can consider this resolved?

**Comment by AndreKuu** [comment]
Ok， i will consider that integrate with the lastest version of ray. But I want to confirm first if it's a problem fixed between 2.5 and 2.7 ？

**Comment by hefeiyun** [comment]
it seems not fixed.

**machine**: 
cpu: 20, mem: 64G
ulimit -u: 32768

**ray**: ray[default]==2.7.1

**code**:
# long_running.py
`import ray
import time

@ray.remote(num_cpus=1, scheduling_strategy="SPREAD")
def hello_world(time_diff):
    time.sleep(500)
    return f"hello world: {time_diff}"

ray.init()
start_time = time.time()
diff = time.time() - start_time
while diff < 50:
    print(ray.get(hello_world.remote(diff)))
    time.sleep(1)
    diff = time.time() - start_time`


# long_running.sh
`#!/bin/bash

counter=1
while [ $counter -le 500 ]
do
echo $counter
((counter++))
RAY_ADDRESS='http://172.16.10.61:8888' DEFAULT_JOB_START_TIMEOUT_SECONDS=300 ray job submit --no-wait -- python long_running.py &
done
echo All done
`

**cmd**: 
ray start --head --port=6666 --dashboard-host=0.0.0.0 --dashboard-port=8888

when the 500 jobs submitted, 
some job fail:
![image](https://github.com/ray-project/ray/assets/20881860/2ea77c65-e5cf-4626-8f82-66cabfb2d37b)
the head will fail:
![image](https://github.com/ray-project/ray/assets/20881860/283d308f-21ad-4373-9fbb-9411a58c0aef)
some job pending:
![image](https://github.com/ray-project/ray/assets/20881860/0d9c59e9-5048-4685-8814-b7b54de4c221)

**Comment by GeneDer** [comment]
@hefeiyun Are you running this on Python 3.7? We already dropped the support of Python 3.7, would suggest to use 3.9 or 3.10. Also, can you use latest Ray 2.8.0?

**Comment by hefeiyun** [comment]
@GeneDer 
ray used too many thread for this 500 jobs:
![image](https://github.com/ray-project/ray/assets/20881860/a54e6948-1409-4031-8aec-261f683ff109)

**Comment by hefeiyun** [comment]
> @hefeiyun Are you running this on Python 3.7? We already dropped the support of Python 3.7, would suggest to use 3.9 or 3.10. Also, can you use latest Ray 2.8.0?

ray: 2.7.1

**Comment by hefeiyun** [comment]
> @hefeiyun Are you running this on Python 3.7? We already dropped the support of Python 3.7, would suggest to use 3.9 or 3.10. Also, can you use latest Ray 2.8.0?

python3.8 ok?

**Comment by GeneDer** [comment]
Python 3.8 is still supported, but would suggest a later version if you are upgrading anyways

**Comment by hefeiyun** [comment]
![image](https://github.com/ray-project/ray/assets/20881860/9f952019-601f-4d12-be02-2d5b1202c912)
![image](https://github.com/ray-project/ray/assets/20881860/53cb180f-9b6c-4506-9644-9db24071fa0b)
![image](https://github.com/ray-project/ray/assets/20881860/6cb4667e-b653-4ad6-92a5-2b27b62185c4)
![image](https://github.com/ray-project/ray/assets/20881860/a0f8850b-bd54-4315-9ea0-d12bb429b7ad)

still crash and pending: python9, ray2.8

**Comment by GeneDer** [comment]
I ran your scripts on m5.8xlarge instance again and still seeing all of them succeeded. Not really sure what's the disconnect 😅
<img width="1704" alt="image" src="https://github.com/ray-project/ray/assets/7553988/b9474b2c-bc84-49f5-8846-14a0027105ba">

**Comment by hefeiyun** [comment]
> I ran your scripts on m5.8xlarge instance again and still seeing all of them succeeded. Not really sure what's the disconnect 😅 <img alt="image" width="1704" src="https://user-images.githubusercontent.com/7553988/283011334-b9474b2c-bc84-49f5-8846-14a0027105ba.png">

what your ulimit -a ?
set ulimit -u =32768 ?

**Comment by GeneDer** [comment]
`ulimit -u` is unlimited for me tho, not sure if that makes a difference? 
Also, just to share, htop looks like this on my machine when running the job 
<img width="785" alt="image" src="https://github.com/ray-project/ray/assets/7553988/000db952-8d16-454f-89b7-8599b8957c42">

**Comment by hefeiyun** [comment]
> set ulimit -u =32768

set ulimit -u =32768 and top -H

**Comment by GeneDer** [comment]
Why do you want to set ulimit to 32768?

**Comment by hefeiyun** [comment]
> Why do you want to set ulimit to 32768?

on some machine, 32768 is the default limit val

**Comment by hefeiyun** [comment]
> `ulimit -u` is unlimited for me tho, not sure if that makes a difference? Also, just to share, htop looks like this on my machine when running the job <img alt="image" width="785" src="https://user-images.githubusercontent.com/7553988/283012167-000db952-8d16-454f-89b7-8599b8957c42.png">

if do not have root, you can run in docker: --ulimit nproc=32768

**Comment by GeneDer** [comment]
Just started another instance, set ulimit -u 32768, and submitted another 500 jobs. Don't see any failures on my end.
<img width="416" alt="image" src="https://github.com/ray-project/ray/assets/7553988/bd33a325-ddb9-4180-88cb-fb815eaa42b5">
<img width="758" alt="image" src="https://github.com/ray-project/ray/assets/7553988/2254302b-3002-4df4-b8e6-2713f6d312f0">
<img width="1631" alt="image" src="https://github.com/ray-project/ray/assets/7553988/a88ea7c3-280b-481b-9377-21b903860392">

When you upgraded, did you restart your Ray cluster? Also, maybe try to set `ulimit -u unlimited` to see if that helps? 

If it continue to fail, can you also share at which point it fails? I only submit 500 jobs because in the initial post you mentioned the jobs starts to fail after 400. Are you still seeing issues at 30 jobs in your 20 core machine?

**Comment by hefeiyun** [comment]
> Just started another instance, set ulimit -u 32768, and submitted another 500 jobs. Don't see any failures on my end. <img alt="image" width="416" src="https://user-images.githubusercontent.com/7553988/283017784-bd33a325-ddb9-4180-88cb-fb815eaa42b5.png"> <img alt="image" width="758" src="https://user-images.githubusercontent.com/7553988/283017053-2254302b-3002-4df4-b8e6-2713f6d312f0.png"> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/7553988/283017183-a88ea7c3-280b-481b-9377-21b903860392.png">
> 
> When you upgraded, did you restart your Ray cluster? Also, maybe try to set `ulimit -u unlimited` to see if that helps?
> 
> If it continue to fail, can you also share at which point it fails? I only submit 500 jobs because in the initial post you mentioned the jobs starts to fail after 400. Are you still seeing issues at 30 jobs in your 20 core machine?

strange, you can create threads over the limit, so sysctl -w kernel.pid_max=32768?

**Comment by hefeiyun** [comment]
> Just started another instance, set ulimit -u 32768, and submitted another 500 jobs. Don't see any failures on my end. <img alt="image" width="416" src="https://user-images.githubusercontent.com/7553988/283017784-bd33a325-ddb9-4180-88cb-fb815eaa42b5.png"> <img alt="image" width="758" src="https://user-images.githubusercontent.com/7553988/283017053-2254302b-3002-4df4-b8e6-2713f6d312f0.png"> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/7553988/283017183-a88ea7c3-280b-481b-9377-21b903860392.png">
> 
> When you upgraded, did you restart your Ray cluster? Also, maybe try to set `ulimit -u unlimited` to see if that helps?
> 
> If it continue to fail, can you also share at which point it fails? I only submit 500 jobs because in the initial post you mentioned the jobs starts to fail after 400. Are you still seeing issues at 30 jobs in your 20 core machine?

en, so many threads is bug?

**Comment by hefeiyun** [comment]
> Just started another instance, set ulimit -u 32768, and submitted another 500 jobs. Don't see any failures on my end. <img alt="image" width="416" src="https://user-images.githubusercontent.com/7553988/283017784-bd33a325-ddb9-4180-88cb-fb815eaa42b5.png"> <img alt="image" width="758" src="https://user-images.githubusercontent.com/7553988/283017053-2254302b-3002-4df4-b8e6-2713f6d312f0.png"> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/7553988/283017183-a88ea7c3-280b-481b-9377-21b903860392.png">
> 
> When you upgraded, did you restart your Ray cluster? Also, maybe try to set `ulimit -u unlimited` to see if that helps?
> 
> If it continue to fail, can you also share at which point it fails? I only submit 500 jobs because in the initial post you mentioned the jobs starts to fail after 400. Are you still seeing issues at 30 jobs in your 20 core machine?

The fact may be: ray create too many threads, and if over the limit, ray would crash.

**Comment by hefeiyun** [comment]
> Just started another instance, set ulimit -u 32768, and submitted another 500 jobs. Don't see any failures on my end. <img alt="image" width="416" src="https://user-images.githubusercontent.com/7553988/283017784-bd33a325-ddb9-4180-88cb-fb815eaa42b5.png"> <img alt="image" width="758" src="https://user-images.githubusercontent.com/7553988/283017053-2254302b-3002-4df4-b8e6-2713f6d312f0.png"> <img alt="image" width="1631" src="https://user-images.githubusercontent.com/7553988/283017183-a88ea7c3-280b-481b-9377-21b903860392.png">
> 
> When you upgraded, did you restart your Ray cluster? Also, maybe try to set `ulimit -u unlimited` to see if that helps?
> 
> If it continue to fail, can you also share at which point it fails? I only submit 500 jobs because in the initial post you mentioned the jobs starts to fail after 400. Are you still seeing issues at 30 jobs in your 20 core machine?

yes, restart ray, or even restart the system first

**Comment by GeneDer** [comment]
Yea, I think it's expected. If you need that many job running at the same time, would be a good idea to setup some worker nodes to do it if they won't all fit into one single node. But at least to your original issue, you are able to run 30 jobs and can continue to submit jobs on your 20 core machine now right?

**Comment by hefeiyun** [comment]
> Yea, I think it's expected. If you need that many job running at the same time, would be a good idea to setup some worker nodes to do it if they won't all fit into one single node. But at least to your original issue, you are able to run 30 jobs and can continue to submit jobs on your 20 core machine now right?

This bug only occurs occasionally， and we are locating it.

**Comment by hefeiyun** [comment]
> Yea, I think it's expected. If you need that many job running at the same time, would be a good idea to setup some worker nodes to do it if they won't all fit into one single node. But at least to your original issue, you are able to run 30 jobs and can continue to submit jobs on your 20 core machine now right?

it is the head node crash, not the worker node

**Comment by GeneDer** [comment]
We can probably implement some kind of job queue for the Jobs to fix the issue, does that sound good to you? I'm not really sure what else we can help here without able to reproduce the issue on our machines😅

**Comment by hefeiyun** [comment]
> We can probably implement some kind of job queue for the Jobs to fix the issue, does that sound good to you? I'm not really sure what else we can help here without able to reproduce the issue on our machines😅

we have modified the system config pid_max to a largger val.
here we just report this issue or fault: ray used so many threads, and may easily crash on hundreds of job.

I prefer to give more details to help you reproduce the issue.

**Comment by GeneDer** [comment]
Totally, thanks for sharing raising pid_max fixed the issue. Yes, I can confirm running this on my local machine with less resource and `ulimit -u` can cash Ray's GCS. Created a separate [issue](https://github.com/ray-project/ray/issues/41241) to implement the job queue to fix it :)
