### ISSUE TITLE
Unify resource management between tasks and actors.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#379]
There are some inconsistencies in the way we are managing resources (CPUs and GPUs).

- Right the local scheduler ignores the dynamic resource capacity of the node when scheduling actor tasks.
- Tasks that use GPUs don't have access to `ray.get_gpu_ids()`.
- When we reserve GPUs for actors and GPUs for tasks, these things are completely disjoint from one another. For example, GPUs are reserved for tasks by local schedulers and GPUs are reserved for actors by Redis. They should both be done by the local scheduler.

**Comment by atumanov** [comment]
I'm assuming this inconsistency was introduced by #242 , commit 12a68e84d293c29150fc91f7218b7ae6eae7657e ?

**Comment by robertnishihara** [comment]
Yeah, that's right (that was the PR that introduced actors).

**Comment by robertnishihara** [comment]
Here's one possibility. We can reason about three things separately: *tasks*, *actors*, and *actor methods*.

**At a high level:**
- Tasks can use both CPUs and GPUs.
    - A task is executed only when enough CPU and GPU resources are available.
    - When a task finishes, it returns its CPU and GPU resources.
    - When a task blocks, it returns **only its CPU resources**.
- Actors use only GPUs.
    - An actor is not scheduled only when enough GPU resources are available.
    - When an actor is removed, it returns its GPU resources.
- Actor methods use only CPUs.
    - An actor method is only executed when enough CPU resources are available.
    - When an actor method finishes, it returns its CPU resources.
    - When an actor method blocks, it returns its CPU resources.

It would be preferable if we could handle CPUs and GPUs identically, but the fact that CPUs can be virtualized and GPUs can't makes them pretty different. Also the fact that each GPU has its own memory is a pretty significant practical difference.

**Comment by istoica** [comment]
1) What is the policy to map actors on nodes? I'd suggest allocating a new actor to the worker node with the lowest number of workers, and break the ties randomly.
2) Clarification question: I assume that all the methods of the same actor use the same amount of CPU resources, right?

**Comment by robertnishihara** [comment]
Currently the policy for deciding which node to create an actor on is the following:
- Choose randomly.
- Unless the actor requires GPUs. In that case choose randomly but subject to the constraint that the node has enough available GPUs.

Your suggestion sounds better (in addition it should probably have some awareness of the number of CPUs/GPUs on each node).

Currently the API doesn't provide a way to indicate different CPU requirements for different actor methods.

**Comment by robertnishihara** [comment]
Note that in #496, we have the local scheduler do bookkeeping of available GPU IDs and so that is handled consistently between actor methods and remote functions.

However, actor methods are currently completely unaware of CPU resources. The following should be done.

1. When an actor method starts executing, the local scheduler should acquire CPU resources for it.
2. When an actor method finishes executing, the local scheduler should release CPU resources for it.
3. When an actor method finishes executing, we may need to trigger the dispatch of other actor methods or other tasks.
4. When a task finishes executing, we may need to trigger the dispatch of actor methods.

**Comment by robertnishihara** [comment]
This is fixed by #682.
