### ISSUE TITLE
[Train]  Creating a LightningCheckpoint from a s3 checkpoint file uri

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#37908]
### Description

Currently in order to create a LightningCheckpoint from a s3 checkpoint file, the checkpoint needs to be downloaded first. Some user wants the ability to create a LightningCheckpoint directly from a s3 uri.

**Comment by matthewdeng** [comment]
This is not something that we are planning to support, but the workflow around this will be made cleaner and more transparent for the user as part of the Checkpoint/Predictor changes in https://github.com/ray-project/ray/issues/37868.
