### ISSUE TITLE
Ray docker image with cuda 12.1

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#37907]
### Description

Our docker image only supports CUDA version up to 11.8 but some users want 12.1

**Comment by rickyyx** [comment]
should we assign this to someone?

**Comment by xieus** [comment]
@can-anyscale @aslonnie 

cc: @rickyyx

**Comment by aslonnie** [comment]
cuda121 support already added in ray 2.7

**Comment by aslonnie** [comment]
cc @kouroshHakha @xwjiang2010

**Comment by aslonnie** [comment]
@krfricke did the work.
