### ISSUE TITLE
[Data] Ray 2.6 introduces breaking change when reading empty pyarrow tables

### ISSUE THREAD

**Issue by jaidisido** [ray-project/ray#37928]
### What happened + What you expected to happen

In Ray 2.6, this code:
```
import ray
import pyarrow as pa

ds = ray.data.from_arrow_refs([pa.Table.from_arrays([])])
```
raises:
```
AssertionError: (pyarrow.Table

----, BlockMetadata(num_rows=0, size_bytes=0, schema=, input_files=[], exec_stats={'wall_time_s': 0.0013057249999999243, 'cpu_time_s': 0.0013049999999998896, 'node_id': '541ad2bf9373c8827759aec55e29a4ce552d1721f79c641a75802e3b'}))
```

In Ray 2.5 and below, it returns an empty Ray dataset as expected

### Versions / Dependencies

Ray 2.6

### Reproduction script

See above

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
`from_arrow_refs` only works with Ray object references, not with Pyarrow tables directly.

Use `from_arrow` instead

```
ds = ray.data.from_arrow([pa.Table.from_arrays([])])
```
