### ISSUE TITLE
Clean up and document debug logging for Ray

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3794]
Currently the logging level "INFO" is hardcoded here:

https://github.com/ray-project/ray/blob/3027dde3037af9924d9ee31533d6c525b30214c6/src/ray/raylet/main.cc#L20

It should be possible to configure that at runtime via ray.init/ray start (e.g. via _internal_config).

**Comment by raulchen** [comment]
@guoyuhong already implemented this, you can set `export RAY_BACKEND_LOG_LEVEL=debug` to turn on debugging log.

**Comment by guoyuhong** [comment]
Here is the PR: https://github.com/ray-project/ray/pull/3662 .
