### ISSUE TITLE
[CI][Core] `linux://python/ray/tests:test_memory_pressure` is failing/flaky on master.

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#37954]
- 79859abad8143f9751a10643ba6e2d890c852418 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5192#01899b95-d3b3-4a92-956e-0779d958f772)
- d650f03444d99d73a49383030c8c9a641d53d854 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5186#018999d7-f7c3-4032-b5d5-d79bd875c2d6)
- 56b52705d5dcd6562a1dc9f2c11d8f362146db87 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5171#018994c2-c9b6-492e-97ad-7d18814a7f53)
- 0a383da4a3bf1b2802b07246264b32a519f3e095 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5133#01898e88-6565-464b-b134-e030736c3747)
- 6ac4521f2a666b1dff8912f455ac928cbe91c5f4 FAILED [Buildkite :python: (Medium K-Z)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5111#01898a0b-3499-40b1-85ec-457885027ae3)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_memory_pressure-END
....

**Comment by rkooo567** [comment]
duplicate https://github.com/ray-project/ray/issues/37483
