### ISSUE TITLE
[devprod] print out release test `pip freeze` results 

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#37955]
### Description

After migrating release tests to BYOD, it's not clear to me how to see the dumped `pip freeze` results without cloning and starting the workspace.

The information used to be under `Local environment information`, which is now empty.

**Comment by xwjiang2010** [comment]
cc @can-anyscale @aslonnie

**Comment by can-anyscale** [comment]
@xwjiang2010 good call out, I wonder if this works https://github.com/ray-project/ray/blob/master/release/ray_release/byod/requirements_byod_3.8.txt. They are basically the pip freeze content but they are checked in the repo. 

There are also other flavors such as requirements_ml_byod_3.8/9.txt that is for the ray-ml image.

**Comment by can-anyscale** [comment]
@xwjiang2010 totally

> how is this file different than requirements_ml_xxx under the same path?
The .txt files (requirements_byod_3.8.txt, requirements_ml_byod_3.8.txt) are ones that engineers can use to add dependencies for their tests. The correponding .in files (requirements_byod_3.8.in, requirements_ml_byod_3.8.in) are the compiled versions. Human should not change them. They can be compiled using bazel.

> is this file the de-facto requirement for all ml release tests?
Yes, and also for all tests that use ray-ml image

> does this file change over time? Say someone checks in some new test that adds a new dependency, does that change the content of this file? Do I need to cross reference that when I am debugging a certain release test failing at a given time?
The file can change and tracked through source control. Someone can change the content of the file, but they can only do that through a PR. You can cross reference the snapshot of that file by checking the version of the file at the commit hash you run the release tests against.


Hope this helps. I'm working on putting all of these into a Wiki and send to engineers soon.

**Comment by xwjiang2010** [comment]
Since this file can change and possibly each test may `pip install` new dependencies depending on the nature of the test, I still feel like a dump of ultimate truth is the easiest for debugging. Then I don't need to go through the thought process that my test failed on time A, certain change is checked in at time B, time B is less or greater than time A, is there possibly a race etc.

**Comment by aslonnie** [comment]
one possible way is to run a `pip list` on the built images, and upload the result as a buildkite build artifact

**Comment by aslonnie** [comment]
won't do it. one can just download the image and inspect. we are not going to list all deps in logs. also most of the deps are pinned today.
