### ISSUE TITLE
[RLLib]  Key value error trying to run DreamerV3 on cartpole

### ISSUE THREAD

**Issue by jadkins99** [ray-project/ray#37964]
### What happened + What you expected to happen

Key value error trying to run DreamerV3 on cartpole. 
![Screenshot from 2023-07-31 19-35-48](https://github.com/ray-project/ray/assets/48653578/de18a128-a110-4e17-ac5b-8bcec0f2d848)
 

`rllib train --run DreamerV3 --env CartPole-v0`

### Versions / Dependencies

ray, version 2.6.1
Python version 3.10
ubuntu 22.04

### Reproduction script

`rllib train --run DreamerV3 --env CartPole-v0`

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
@sven1977 I can reproduce this.

**Comment by sven1977** [comment]
Thanks for raising this @jadkins99 !
This will be fixed with this PR here (which will be merged today):
https://github.com/ray-project/ray/pull/38461

There will also be a better README that describes all one needs to know for running other, more custom (non gym-registered) envs.

**Comment by GeneDer** [comment]
The PR is already in the release branch. Closing now. Feel free to reopen and drop release-blocker tag if there are more work to do
