### ISSUE TITLE
pyarrow.lib.PlasmaStoreFull: object does not fit in the plasma store

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#3796]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.1
- **Python version**: 3.5.2
- **Exact command to reproduce**: Explained below, custom script using rllib and Tune. 

### Describe the problem

Almost immediately after running my script I receive the error log below. The script is also attached. 
If you want to run it, you can install Flow (happy to help with this) and run the multiagent_bottleneck.py script on the itsc_bottleneck_exps branch. 

### Source code / logs

[error.txt](https://github.com/ray-project/ray/files/2766711/error.txt)

[run_script.txt](https://github.com/ray-project/ray/files/2766718/run_script.txt)

**Comment by eugenevinitsky** [comment]
A few other pieces of information that might be helpful:
- This script is being run on a c4.4xlarge machine
- This error does not occur if I decrease the number of requested CPUs to 3

**Comment by ericl** [comment]
I'm wondering how big the experience batches you are collecting are. Maybe decrease the train/sample batch size?

**Comment by eugenevinitsky** [comment]
Probably quite large; there are about 50 agents in the system so its however many rollouts times horizon times 50. Okay, thanks!
