### ISSUE TITLE
Setup Nightly Builds

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3798]
We should have a pip channel like `pip install ray-nightly`.

This is not hard to setup, and should just be part of our nightly stress testing suite.

**Comment by robertnishihara** [comment]
We should probably do this by having a cron job, e.g., on Jenkins, that does the following:
1. Look at GitHub/Travis and find the latest commit where the wheels successfully built.
2. Pull all of those wheels from the S3 bucket for that commit (and check that the correct number of wheels are present).
3. Rename the wheels appropriately.
4. Upload them to PyPI.

**Comment by richardliaw** [comment]
@pschafhalter and I are doing this right now

**Comment by robertnishihara** [comment]
After playing around with `pip` a bit more, I think we actually need to do almost nothing to get this working.

The following already "almost" works.

```
pip install --no-cache-dir -U ray --find-links https://s3-us-west-2.amazonaws.com/ray-wheels/latest/
```

I say "almost" because it currently finds `ray==0.6.3` instead of `ray==0.7.0.dev0`. I've tried adding `--pre` and `ray==0.7.0dev0` but that didn't quite work. Not quite sure what the issue is, but this can be worked around.

@richardliaw @pschafhalter @pcmoritz

**Comment by richardliaw** [comment]
Hm, I took a look at this - 
```
╰─ pip install --no-cache-dir -U ray --find-links https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ -v

Created temporary directory: /private/var/folders/05/8j_ttn9s7cqdf1cdnr8mq6w40n25bb/T/pip-ephem-wheel-cache-KKAQXx
Created temporary directory: /private/var/folders/05/8j_ttn9s7cqdf1cdnr8mq6w40n25bb/T/pip-req-tracker-tX6tzT
Created requirements tracker '/private/var/folders/05/8j_ttn9s7cqdf1cdnr8mq6w40n25bb/T/pip-req-tracker-tX6tzT'
Created temporary directory: /private/var/folders/05/8j_ttn9s7cqdf1cdnr8mq6w40n25bb/T/pip-install-_9Tybb
Looking in links: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/
2 location(s) to search for versions of ray:
* https://pypi.org/simple/ray/
* https://s3-us-west-2.amazonaws.com/ray-wheels/latest/
Skipping link https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ (from -f); not a file
Getting page https://pypi.org/simple/ray/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/ray/ HTTP/1.1" 200 12494
Analyzing links from page https://pypi.org/simple/ray/
```

**Comment by robertnishihara** [comment]
I see, I think we need to put an `index.html` in the folder with some metadata.

**Comment by richardliaw** [comment]
Actually now that we have a website, perhaps we can actually publish these links somewhere!
