### ISSUE TITLE
[Data] Support reading Hugging Face dataset in distributed streaming way

### ISSUE THREAD

**Issue by c21** [ray-project/ray#37990]
### Description

Currently [from_huggingface()](https://github.com/ray-project/ray/blob/master/python/ray/data/read_api.py#L2084) would load the Hugging Face dataset in-memory in a single node. This is working for small size of dataset, but not large size. For example, user hit OOM issue when trying to use https://huggingface.co/datasets/togethercomputer/RedPajama-Data-1T . We should change the API to make the reading in a streaming way across multiple tasks.

Hugging Face dataset streaming - https://huggingface.co/docs/datasets/stream
split_dataset_by_node - https://huggingface.co/docs/datasets/package_reference/main_classes#datasets.distributed.split_dataset_by_node

### Use case

Read large scale Hugging Face dataset efficiently for fine tuning LLM

**Comment by matthewdeng** [comment]
Related: https://github.com/ray-project/ray/issues/37591 

cc @raulchen if you want to de-duplicate

**Comment by c21** [comment]
ah closing this in favor of the existing one - https://github.com/ray-project/ray/issues/37591 .
