### ISSUE TITLE
[core][autoscaler] Placement group showing up as pending while being allocated

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#38006]
### What happened + What you expected to happen

Placement group load is showing up as pending even though the placement group might have been scheduled. 

### Versions / Dependencies

master

### Reproduction script

```
import time

# Import placement group APIs.
from ray.util.placement_group import (
    placement_group,
    placement_group_table,
    remove_placement_group,
)

# Initialize Ray.
import ray


# Reserve all the CPUs of nodes, X= num of cpus, N = num of nodes
while True:
    pg = placement_group([{"CPU": X}] * N)
    ray.get(pg.ready())
    remove_placement_group(pg)
    time.sleep(2)

```

### Issue Severity

None

**Comment by xieus** [comment]
Is this impacting Serve workload?

**Comment by rickyyx** [comment]
> Is this impacting Serve workload?

Yes - techinically all ray workloads.
