### ISSUE TITLE
[Core] Running import ray breaks logging in Ray 2.6

### ISSUE THREAD

**Issue by cread** [ray-project/ray#38019]
### What happened + What you expected to happen

A change was made to how Ray configures logging in version 2.6 that breaks logging.

The easiest way to demonstrate this is with using `pytest`. If you have a test that uses the `pytest` [caplog-fixture](https://docs.pytest.org/en/7.4.x/how-to/logging.html#caplog-fixture), if you simply have

```python
import ray
```

in the test file, or loaded via a dependency of the code being tested, the runtime logging configuration will be broken to the extent that the test fails.

Ray should **NOT** be executing code or changing the runtime configuration at import time.

This is blocking us from upgrading from Ray 2.5.1 as it breaks other logging within our system.

### Versions / Dependencies

Python: 3.10
Ray: 2.6.1

### Reproduction script

The repro cannot be reduced to a single file, but I have a simple repro available at https://github.com/cread/pytest-caplog-ray

### Issue Severity

High: It blocks me from completing my task.

**Comment by richardliaw** [comment]
Hey @cread thanks a bunch for opening this issue; we've seen this reported a couple times. The fix is already landed on master I believe, and we're planning to release 2.6.2 to address this in the next 2 weeks.

Hope that helps. 

https://github.com/ray-project/ray/issues/37711

**Comment by richardliaw** [comment]
OK this should be fixed in this PR - https://github.com/ray-project/ray/pull/36306

**Comment by rkooo567** [comment]
The fix is merged in the master, and will be included in ray 2.6.2.  cc @rickyyx is leading the 2.6.2 release, and he will confirm the timeline for the release

**Comment by scv119** [comment]
offending PR https://github.com/ray-project/ray/pull/34182/files

**Comment by xieus** [comment]
@cread Chris, Ray 2.6.2 is released today with an proper fix.
https://github.com/ray-project/ray/releases/tag/ray-2.6.2

Please check it out and let us know how it goes. Thank you for your patience and understanding.
