### ISSUE TITLE
[Tune]  conservative scheduling when using resource allocation based on memory

### ISSUE THREAD

**Issue by Geoffreyvd1** [ray-project/ray#38059]
### What happened + What you expected to happen

I have 20gb memory free, i set 2,5 gb memory per thread. However it only spawns 5 threads, instead of 8. I would expect some buffer, but this seems a bit to conservative?

### Versions / Dependencies

2.4.0

### Reproduction script

```
trainable_with_resources = tune.with_resources(
        train_rl, {"memory": calculate_mem_usage_per_thread()}
    )  # buffer 5 mil = 3gb ram  # can also limit cpu, gpu
    tuner = tune.Tuner(
        trainable_with_resources,
        param_space=hp_config,
        tune_config=tune.TuneConfig(
            num_samples=3,
        ),
        run_config=air.RunConfig(local_dir="./logs/hptuning-results"),
    )
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
@Geoffreyvd1 can you clarify what your cluster configuration looks like, and what the output of `ray status` shows when you do this? `memory` is treated as a virtual resource and will only limit the scheduling if it cannot fit any more on your cluster.
