### ISSUE TITLE
[wheels][core] Missing window wheels for 2.6.2

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#38101]
### What happened + What you expected to happen

We were not able to generate windows wheels for 2.6.2 due to CI outage. 

Windows wheel built is now fixed, building wheels and adding them to pypi. 

### Versions / Dependencies

2.6.2

### Reproduction script

NA

### Issue Severity

None

**Comment by lovettchris** [comment]
thanks do you have an ETA on this?

**Comment by rickyyx** [comment]
Working on it today/tmrw!

**Comment by rickyyx** [comment]
Just uploaded! @lovettchris 

Sorry for the delay and thanks for your understanding.

**Comment by lovettchris** [comment]
Works great, you rock! Thanks for the quick turn-around!  We are having way too much fun with rllib over here in Microsoft Research so really appreciate having both Linux and Windows versions working and compatible across platforms.  I actually have a question for you, do you know if each version of Ray[rllib] is supposed to have compatibile saved rllib checkpoints (we are using torch framework with rllib).  Or should we expect the checkpoints to not work across versions? Or is there official release notes that will give us this information somewhere?
