### ISSUE TITLE
Release test rllib_learning_tests_ddpg_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38122]
Release test **rllib_learning_tests_ddpg_torch.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2023#0189c0c6-c040-426e-ae36-8e838fb2ff0a for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
We fixed most of rllib tests, but the ddpg now fails due to some deprecated fields

**Comment by can-anyscale** [comment]
Also cc: @sven1977 for the blamed commit

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
Closing this issue. Algo has been removed from RLlib.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/9188#018dcfe3-5a8b-4904-ac33-5cbebe47e906
