### ISSUE TITLE
Release test workspace_template_many_model_training.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38123]
Release test **workspace_template_many_model_training.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2024#0189c0d0-6a9d-43d4-9e0b-7a7ba0aa6654 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2027#0189cee6-3415-46f7-9c24-a205106b04ff

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2037#0189d988-e9f5-442b-9c50-f52a12140c56

**Comment by can-anyscale** [comment]
Look like the notebook is broken again? @xwjiang2010 

```
+ jupyter nbconvert --to script --output _test start.ipynb
[NbConvertApp] Converting notebook start.ipynb to script
[NbConvertApp] Writing 10270 bytes to _test.py
+ ipython _test.py
  File /tmp/ray/session_2023-08-09_02-07-40_134844_51/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_workspace_template_many_model_training_aws_lkhqkmwqid__anyscale_pkg_07fd88626b83ecdff43cb598369c95f4/_test.py:49
    from ray.train RunConfig
                   ^
SyntaxError: invalid syntax
```

**Comment by xwjiang2010** [comment]
yeah I will push a change. @can-anyscale can we add something at CI level for detecting broken notebooks? Maybe this is a request for devprod team :)

**Comment by can-anyscale** [comment]
we definitely need unit-test for these yes
