### ISSUE TITLE
Support passing in bytes data directly to ray.data.read_binary_files()

### ISSUE THREAD

**Issue by hwuiwon** [ray-project/ray#38138]
### Description

Support passing in bytes data directly to ray.data.read_binary_files() as a parameter.

### Use case

Flexibility to integrate with diverse data sources and preprocessing steps before leveraging Ray for distributed processing. The user doesn't have to write to temporary files just to interface with the Ray API.

**Comment by amogkam** [comment]
Hey @hwuiwon, if you have in-memory data already loaded in as bytes, you can take a look at how to load that in here: https://docs.ray.io/en/latest/data/loading-data.html#loading-data-from-other-libraries
