### ISSUE TITLE
AccelerateTrainer does not load accelerate_config file properly with deepspeed plugin

### ISSUE THREAD

**Issue by Rubertos** [ray-project/ray#38158]
### What happened + What you expected to happen

By setting,

```
AccelerateTrainer( train_loop_per_worker= train_loop_per_worker, scaling_config=scaling_config, accelerate_config='/some/path/default_config.yaml')
```

it ends up with the error:

```
File "/some/path/accelerate/utils/launch.py", line 264, in prepare_deepspeed_cmd_env
if is_port_in_use(main_process_port):
 File "/some/path/accelerate/utils/other.py", line 184, in is_port_in_use
 return s.connect_ex(("localhost", port)) == 0
TypeError: 'str' object cannot be interpreted as an integer
```

Meanwhile, if I set the attribute accelerate_config={}, it works correctly, but it does not work in deepspeed environment.

Moreover, even though I changed the above line in other.py as :
```
return True
```
it returns an error that tensors must be contiguous.

To sum up, I think there are two bugs..

1. AccelerateTrainer does not properly load accelerate_config file.
2. AccelerateTrainer does not work correctly with deepspeed plugin.

### Versions / Dependencies

ray 2.6.1
transformers 4.31.0
accelerate 0.21.0
deepspeed 0.10.0

### Reproduction script

```
ray.init(address='auto', _node_ip_address='head.node.ip.address')

trainer = AccelerateTrainer( train_loop_per_worker= train_loop_per_worker, scaling_config=scaling_config, accelerate_config='/some/path/default_config.yaml')

trainer.fit()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by xwjiang2010** [comment]
Can you share the config file?

**Comment by tongyifan** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/train/huggingface/accelerate/accelerate_trainer.py#L374

`main_process_port` should be int type but string given

**Comment by Rubertos** [comment]
> Can you share the config file?

Sorry for the late reply. 

compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /some/path/ds_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by Rubertos** [comment]
> https://github.com/ray-project/ray/blob/master/python/ray/train/huggingface/accelerate/accelerate_trainer.py#L374
> 
> `main_process_port` should be int type but string given

I modified the source code of accelerate/utils/other.py as follows:

`s.connect_ex(("localhost", int(port))) == 0`


Then, instead of the error in the original post, the following error arises:

```
File "/some/path/accelerate/utils/launch.py", line 265, in prepare_deepspeed_cmd_env
    raise ConnectionError(
ConnectionError: Tried to launch distributed communication on port `53151`, but another process is utilizing it. Please specify a different port (such as using the `----main_process_port` flag or specifying a different `main_process_port` in your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this to `0`.
```

**Comment by Rubertos** [comment]
> Can you share the config file?

Moreover, at the start of running, it shows the following message :

```
(pid=31938) [2023-08-21 07:49:45,988] [INFO] [real_accelerator.py:158:get_accelerator]
 Setting ds_accelerator to cuda (auto detect)
Training started without custom configuration.
```

**Comment by tongyifan** [comment]
> > https://github.com/ray-project/ray/blob/master/python/ray/train/huggingface/accelerate/accelerate_trainer.py#L374
> > `main_process_port` should be int type but string given
> 
> I modified the source code of accelerate/utils/other.py as follows:
> 
> `s.connect_ex(("localhost", int(port))) == 0`
> 
> Then, instead of the error in the original post, the following error arises:
> 
> ```
> File "/some/path/accelerate/utils/launch.py", line 265, in prepare_deepspeed_cmd_env
>     raise ConnectionError(
> ConnectionError: Tried to launch distributed communication on port `53151`, but another process is utilizing it. Please specify a different port (such as using the `----main_process_port` flag or specifying a different `main_process_port` in your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this to `0`.
> ```

same with you😢

**Comment by xwjiang2010** [comment]
Thanks for the info.
We are actually recommending [this way](https://github.com/ray-project/ray/pull/38513/files) of integrating with accelerate and deepspeed. Could you take a look and see if that works?
cc @woshiyyya

**Comment by woshiyyya** [comment]
Yes please directly setup configurations in `Accelerator` object in your code, and run a TorchTrainer. We are deprecating `AccelerateTrainer` in the next release.

Details: https://docs.ray.io/en/master/train/huggingface-accelerate.html#train-hf-accelerate

**Comment by Rubertos** [comment]
> Yes please directly setup configurations in `Accelerator` object in your code, and run a TorchTrainer. We are deprecating `AccelerateTrainer` in the next release.
> 
> Details: https://docs.ray.io/en/master/train/huggingface-accelerate.html#train-hf-accelerate

That is weird. I actually had no problem using deepspeed+accelerate using TorchTrainer. However, the reason why I tried to switch from TorchTrainer to AccelerateTrainer was that, it seems there is some bug in TorchTrainer when quantizing a model (e.g. load in 4 bits). When using TorchTrainer, the log message always shows that bitsandbytes is not compiled with GPU support even though it is compiled with GPU.

However, i found that quantization of a model WORKS correctly with AccelerateTrainer WITHOUT using deepspeed ( though, with deepspeed, the error in the original post arises).

If AccelerateTrainer is going to be deprecated, would you please that quantization bug for TorchTrainer?

**Comment by xwjiang2010** [comment]
This is weird. TorchTrainer being a distributed launcher of things, I don't see how it can interfere with `bitsandbytes`. That being said, I realize we also don't have a test that runs the two together. If you have a script that can easily repro this, we can take a look.

**Comment by woshiyyya** [comment]
The problem is that AccelerateTrainer is a thin wrapper around TorchTrainer and it doesn't make any difference other than parsing and setting the acceleration configuration, which can also be done with the configuration in "Accelerator". 

Can you share the code that has the bitsandbytes error so we can help diagnose the issue. Also did you quantize the model inside or outside the `train_loop_per_worker`? We recommend put everything inside the training function.

**Comment by Rubertos** [comment]
> The problem is that AccelerateTrainer is a thin wrapper around TorchTrainer and it doesn't make any difference other than parsing and setting the acceleration configuration, which can also be done with the configuration in "Accelerator".
> 
> Can you share the code that has the bitsandbytes error so we can help diagnose the issue. Also did you quantize the model inside or outside the `train_loop_per_worker`? We recommend put everything inside the training function.

I put everything inside the train_loop_per_worker. Since I cannot directly share the script because of security issue, I will briefly summarize the code and post it here tomorrow.. Thank you in advance.

**Comment by matthewdeng** [comment]
Marking this ticket as closed because the `AccelerateTrainer` has been deprecated. @Rubertos if you're still running into the issue with quantization could you create a new issue for it? Thanks!
