### ISSUE TITLE
[Autoscaler] Over counting pending demands, resulting in over provisioning of nodes

### ISSUE THREAD

**Issue by llidev** [ray-project/ray#38189]
### What happened + What you expected to happen

Possible Bug :bug:

Hi, when use autoscaler, I observe that the usage status report is not consistent with the demand: The sum of resource in use plus pending demands is sometimes greater than the actual request, causing autoscaler provision more nodes than need.

A little detail of my setting: I’m using a custom node provider on my private compute platform. In the cluster yaml file, I have a node type called trainer with custom resource {"trainer": 1, ...}. In my job, I spawn 64 actors, each requires resources={"trainer": 1}. The cluster starts with 0 trainer, and I expect the autoscaler can scale up to 64 trainer without any issue.

At the time when all actors are created, I can see the the correct number of pending actors, and 64 trainers are being provisioned:

```
Resources
---------------------------------------------------------------
Usage:
 0.0/1.0 CPU
 0B/10.24GiB memory
 0B/9.22GiB object_store_memory

Demands:
 {'CPU': 1.0, 'trainer': 1.0}: 64+ pending tasks/actors
```
However, when some actors starts landing on new nodes, I see the sum of pending actors plus  trainer in use is greater than 64! For example, in below autoscaler _update call, I have 30/30 trainers and 37+ pending tasks/actors, giving a total of 67 `trainers`.

```
Resources
---------------------------------------------------------------
Usage:
 30.0/31.0 CPU
 ...
 30.0/30.0 trainer

Demands:
 {'CPU': 1.0, 'trainer': 1.0}: 37+ pending tasks/actors
```

In the next autoscaler _update call, the count came back to normal (36 + 28 = 64):

```
Resources
---------------------------------------------------------------
Usage:
 36.0/37.0 CPU
 ...
 36.0/36.0 trainer

Demands:
 {'CPU': 1.0, 'trainer': 1.0}: 28+ pending tasks/actors
```
This causes the autoscaler decides to provision 3 more trainer nodes even though they are not needed. Even worse, the over-provisioned nodes are released only after the idle timeout reached, which is 15 mins in my config, resulting in waste of GPU resource.

I wonder if this is a known issue, and if there is a way on the client side to mitigate.

### Versions / Dependencies

ray==2.6.1

### Reproduction script

N/A

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
Thanks @llidev . What would you say about the Severity? Is it a blocker for you?

**Comment by llidev** [comment]
Hi @zhe-thoughts , although I do have some workaround at my node provider layer, I believe this is a serious but needs more attention.

Also, I wonder if it's related to https://github.com/ray-project/ray/issues/38004?

**Comment by rickyyx** [comment]
Yes - i think this is what #38004 is about. Should be fixed in Ray 2.6.3 that's coming up in this week or next.

**Comment by rickyyx** [comment]
Since it's now in master @llidev if you are able to work with a nightly wheel, please try it out if you get the chance!

Thanks.

**Comment by llidev** [comment]
@rickyyx thanks for providing the fix. I just tried the the 2.6.3 release. I can see it has been improved there, but the issue seems still there occasionally.

`2023-08-15 22:31:10,035`: 28+72 = 100
```
Resources
---------------------------------------------------------------
Usage:
 28.0/28.0 CPU

Demands:
 {'CPU': 1.0}: 72+ pending tasks/actors
```

`2023-08-15 22:31:18,332`: 36+65=101
```
Resources
---------------------------------------------------------------
Usage:
 36.0/36.0 CPU

Demands:
 {'CPU': 1.0}: 65+ pending tasks/actors
```

`2023-08-15 22:31:27,388`: 48+52=100
```
Resources
---------------------------------------------------------------
Usage:
 48.0/48.0 CPU

Demands:
 {'CPU': 1.0}: 52+ pending tasks/actors
```

**Comment by rickyyx** [comment]
Hey @llidev - thanks for the verification. We are indeed aware of possible inconsistencies even with this PR https://github.com/ray-project/ray/pull/38093 that fixes the node level inconsistency. 

The underlying issue is we get resource usage and demand from nodes asynchronously, and each view from individual nodes might not add to a consistent global view. 

A fix is non trivial and we are starting the design discussion around it, and we are hoping to get it in by ray 2.8 (which might be in a few weeks likely after September's Ray summit). Will keep this issue updated when we have a design/prototype out. 

As of now, I think a workaround is to configure your actors to use maybe 1/2 less CPU than the total possible cluster resources  (yes, it's rather hacky and definitely ideal)

**Comment by llidev** [comment]
Thank you @rickyyx for the update. I understand the root cause is non-trivial and require major refactoring. 

My current workaround is to reduce the noise from inconsistencies: my custom node provider only adds nodes when the input `count` are constant for past 3 `_update` iterations. It works fine for now, but just slows down the upscaling.

**Comment by rkooo567** [comment]
Closing the issue as duplicate https://github.com/ray-project/ray/issues/36926
