### ISSUE TITLE
GCP Autoscaling failure when GPU>1

### ISSUE THREAD

**Issue by anthonytec2** [ray-project/ray#3823]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.14.2
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.2
- **Python version**: 3.6.7
- **Exact command to reproduce**: ray up ray-cluster.yaml

### Describe the problem
Whenever I try to scale my head node to have more than 1 GPU ray fails on sshing into the head node when performing ray up. I have confirmed that my quota will allow for more than 1 GPU on a given node and have been able to manually setup a head node with more than 1 GPU. Although when using the autoscaler the code fails. Also, I am using GCP as my cloud platform

### Source code / logs
ray-cluster.yaml
cluster_name: default
min_workers: 0

initial_workers: 0
max_workers: 16
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: gcp
    region: us-east1
    availability_zone: us-east1-b
    project_id: mlwork-216319 

auth:
    ssh_user: abisulco

head_node:
    machineType: n1-standard-16
    guestAccelerators:
      - acceleratorType: projects/mlwork-216319/zones/us-east1-b/acceleratorTypes/nvidia-tesla-p100
        acceleratorCount:  4
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          sourceImage: projects/mlwork-216319/global/images/head-rl-img2 u
    scheduling:
      - preemptible: false
        onHostMaintenance: TERMINATE
        automaticRestart: true

worker_nodes:
    machineType: n1-standard-16 
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          sourceImage: projects/mlwork-216319/global/images/worker-rl-img2  # Ubuntu
    scheduling:
      - preemptible: true

setup_commands:
  - sudo apt update
  - cd Halite && git fetch && git checkout img && git pull origin img
head_setup_commands: []

worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --head
      --redis-port=6379
      --object-manager-port=8076
      --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --redis-address=$RAY_HEAD_IP:6379
      --object-manager-port=8076

LOG
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/cloudresourcemanager/v1/rest
yfile_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/iam/v1/rest
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest

URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances?filter=%28%28labels.ray-node-type+%3D+head%29%29+AND+%28%28status+%3D+RUNNING%29+OR+%28status+%3D+PROVISIONING%29+OR+%28status+%3D+STAGING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
This will create a new cluster [y/N]: Launching new head node...
URL being requested: POST https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances?alt=json
Waiting for operation operation-1548166458610-5800c97d1924b-53d6004d-2d6df498 to finish...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166458610-5800c97d1924b-53d6004d-2d6df498?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances?filter=%28%28labels.ray-node-type+%3D+head%29+AND+%28labels.ray-launch-config+%3D+c9e21564b89c16f83832d2b87cd90fed81e15729%29+AND+%28labels.ray-node-name+%3D+ray-default-head%29%29+AND+%28%28status+%3D+RUNNING%29+OR+%28status+%3D+PROVISIONING%29+OR+%28status+%3D+STAGING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
Updating files on head node...
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Updating ray-default-head-bf509bff to 46845d34a24aeb9fe556596b55b5cf5cf99adede, logging to (console)
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: POST https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff/setLabels?alt=json
Waiting for operation operation-1548166525791-5800c9bd2ab1a-afdb1610-a859edb0 to finish...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166525791-5800c9bd2ab1a-afdb1610-a859edb0?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166525791-5800c9bd2ab1a-afdb1610-a859edb0?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166525791-5800c9bd2ab1a-afdb1610-a859edb0?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166525791-5800c9bd2ab1a-afdb1610-a859edb0?alt=json
Done.
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for IP of ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Waiting for SSH to ray-default-head-bf509bff...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
NodeUpdater: Error updating Unable to SSH to nodeSee (console) for remote logs.
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff?alt=json
URL being requested: POST https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances/ray-default-head-bf509bff/setLabels?alt=json
Waiting for operation operation-1548166851177-5800caf37aac8-e6f433fe-1f2f9c42 to finish...
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166851177-5800caf37aac8-e6f433fe-1f2f9c42?alt=json
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/operations/operation-1548166851177-5800caf37aac8-e6f433fe-1f2f9c42?alt=json
Done.
Process NodeUpdaterProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 104, in run
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 89, in run
    self.do_update()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ray/autoscaler/updater.py", line 155, in do_update
    assert ssh_ok, "Unable to SSH to node"
AssertionError: Unable to SSH to node
URL being requested: GET https://www.googleapis.com/compute/v1/projects/mlwork-216319/zones/us-east1-b/instances?filter=%28%28labels.ray-node-type+%3D+head%29+AND+%28labels.ray-launch-config+%3D+c9e21564b89c16f83832d2b87cd90fed81e15729%29+AND+%28labels.ray-node-name+%3D+ray-default-head%29%29+AND+%28%28status+%3D+RUNNING%29+OR+%28status+%3D+PROVISIONING%29+OR+%28status+%3D+STAGING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
Updating 35.190.163.11 failed

**Comment by Neo-X** [comment]
What was the problem?
