### ISSUE TITLE
[Serve] Batch method hung and stopped processing requests

### ISSUE THREAD

**Issue by psydok** [ray-project/ray#38249]
### What happened + What you expected to happen

1. Requests are no longer batched and processed by the model. The response from service `STTService` was not returned.
2. The console should display how many requests got into the batch, but nothing was displayed, except for what I output before calling `self.handle_batch(...)` function
3. I cannot reproduce this issue. After restarting the service (which, by the way, was launched through `docker-compose`), everything worked again. Prior to this, the service worked stably for about 20 days. There was no load on the service, the work took place as usual.

### Versions / Dependencies

- Ray 2.3.0 
- Python 3.10.9 
- Linux
- Docker image: rayproject/ray-ml:2.3.0-py310-gpu

PS tried to update Ray to 2.5.0 seems to have returned an error with a memory leak, so they returned 2.3.0

### Reproduction script

```python
@serve.deployment(is_driver_deployment=True, name="grpc_service")
class STTService(stt_pb2_grpc.STTServicer, gRPCIngress):
    def __init__(self):
        self._asr_inference = ASRInference()
        super().__init__()
   
 @serve.batch(max_batch_size=3, batch_wait_timeout_s=0.1)
    async def handle_batch(
        self, requests: RequestBatch
    ) -> List[stt_pb2.RecognizeResponse]:
        _logger.info(f"Count of requests in batch: {len(requests)}")  # <---  stopped logging in the console. it means requests stopped getting into the batch
        results = self._asr_inference(
            request.audio.audio_content
            for request in requests
        )
        return [self._get_response(text) for text in results]

    @set_timer
    async def Recognize(
        self, request: stt_pb2.RecognizeRequest, context: grpc.ServicerContext
    ) -> stt_pb2.RecognizeResponse:
        _logger.info(f"Request came to service: {request.recognition_config.filename}")  # <--- this log always appears in the console
        return await self.handle_batch(request)

```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by shrekris-anyscale** [comment]
> I cannot reproduce this issue. After restarting the service (which, by the way, was launched through docker-compose), everything worked again. 

@psydok have you seen this issue again? It sounds like it only happened once, and then when you restarted, batching started working again. Is that correct?

**Comment by GeneDer** [comment]
Close staled issue
