### ISSUE TITLE
[Core] Replace pkg_resources to importlib.metadata

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#38257]
### What happened + What you expected to happen

From @hauntsaninja 

`import pkg_resources` is an incredibly slow to import (time proportional to the size of the venv). it’s also deprecated and raises deprecation warnings. in 3.8 and higher you can use importlib.metadata. 3.7 is dead, but you can sys.version_info gate to use pkg_resources, or use the importlib_metadata backport. 

it’d be cool if ray could run tests with warnings set to error!

I also found deprecation warnings from this packages + it spends lots of time when starting a new ray worker. So it'd be great if we can remove the usage. 

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by jjyao** [comment]
@rkooo567 can you assign a priority?

**Comment by JonathanRaynerMonumo** [comment]
@rkooo567 should this be re-opened due to the [revert of the fix](https://github.com/ray-project/ray/issues/41675)?

**Comment by rkooo567** [comment]
I hasn't been reverted. I also verified pkg_resources are still not used
