### ISSUE TITLE
Specify `s3fs` as a dependency (perhaps gated behind the tune extra)

### ISSUE THREAD

**Issue by lukehsiao** [ray-project/ray#38260]
### What happened + What you expected to happen

Ray recommends users install s3fs in tune:

```
❯ rg "(from|import).*s3fs" -t py
python/ray/data/tests/test_numpy.py
285:        from s3fs.core import S3FileSystem
327:        from s3fs.core import S3FileSystem

python/ray/tune/tests/test_syncer.py
947:        import s3fs  # noqa: F401

python/ray/tune/syncer.py
29:    import s3fs
```

Yet, the `ray` package does NOT specify this as a dependency. 

This means if a user does not manually specify the dependency themselves and hit that code path, they will get this warning: https://github.com/ray-project/ray/blob/e148c42e37e5da28a894df73e37152cacfe76eb1/python/ray/tune/syncer.py#L254-L259

Ray could instead specify just install the preferred default.

Note that Ray already seems to do this for `fsspec`.

For example

```diff
diff --git a/python/setup.py b/python/setup.py
index 0e5160f3aba5..91985e68a500 100644
--- a/python/setup.py
+++ b/python/setup.py
@@ -270,7 +270,7 @@ def get_packages(self):
             else "grpcio",
         ],
         "serve": ["uvicorn", "requests", "starlette", "fastapi", "aiorwlock"],
-        "tune": ["pandas", "tensorboardX>=1.9", "requests", pyarrow_dep],
+        "tune": ["pandas", "tensorboardX>=1.9", "requests", pyarrow_dep, "s3fs"],
         "observability": [
             "opentelemetry-api",
             "opentelemetry-sdk",
```

### Versions / Dependencies

Ray <= 2.6.2

Other versions not relevant.

### Reproduction script

```
$ python -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install ray[tune,default]
(.venv) $ pip show s3fs
WARNING: Package(s) not found: s3fs
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
Not sure if we'd want to include this, since not all users may be using S3.

cc @krfricke @justinvyu FYI

**Comment by lukehsiao** [comment]
> Not sure if we'd want to include this, since not all users may be using S3.
> 
> cc @krfricke @justinvyu FYI

That's a fair point. Another option might be to make a new extra (e.g., `s3`). 

I only mention this because as a user it feels bad to specify a dependency even though it's really used indirectly, not at all by my own code.

Given it's only for ray, I'd love to install `ray[s3,...]`, rather than installing s3fs separately myself to just be unused.

This helps because if I later remove ray, I don't also have to remember to remove s3fs, it will just happen.

**Comment by matthewdeng** [comment]
Makes sense. I checked with the team, we are planning to clean up this custom s3fs path, which should remove the need for this message/dependency.
