### ISSUE TITLE
[rllib] Support counterfactual evaluation in offline mode

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3827]
### Describe the problem

We should support some form of CPE (initially, IS and WIS are easiest). This should be straightforward for complete episode batches. (and even partial episode batches, if the estimation isn't an absolute reward).

**Comment by tengteng** [comment]
👍 @OuHangKresnik and I are just looking at this feature.
https://github.com/facebookresearch/Horizon Already have this implemented.
