### ISSUE TITLE
[train] Add `metadata` argument to Trainer

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#38288]
Add a `metadata` arg to the Trainer class, which is a generalization / replacement of the previous `preprocessor` arg. Unlike preprocessor, it is an opaque, JSON serializable dict.
- This will become available to Training workers via the context/sesion API.
- It will also be automatically propagated to the Checkpoints reported by Trainers.
- The automatically propagated keys will have less precedence than metadata keys explicitly set by users on the Checkpoint object reported.
- Add a simple example to the data preprocessing section.

**Comment by richardliaw** [comment]
As part of this PR let's add a simple example to the data preprocessing section.

**Comment by amogkam** [comment]
Re-opening as 

> Add a simple example to the data preprocessing section.

is still TODO. Just want to make sure that this is tracked. I am assuming this is coming in the part 2 PR.

**Comment by ericl** [comment]
I had filed a followup issue for that already --- so this can be correctly closed.
