### ISSUE TITLE
[air] API cleanup for leaving beta

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#38289]
In Ray 2.7, we are seeking to finalize the Ray AIR APIs. This means all major API changes need to happen in 2.7. Ideally, Ray 2.8 becomes a purely internal cleanup / has minor API changes only.

- In Ray 2.7, several APIs are being de-emphasized / "quarantined". This means they will be removed from our public docs, examples, and tutorials. However, the code and unit tests remain for now. They are being de-emphasized because they have proved to be of low value to users, but high maintenance cost, as well as increasing the conceptual complexity of AIR:
    - Preprocessors
        - https://github.com/ray-project/ray/issues/38288
        - https://github.com/ray-project/ray/issues/38290
    - *Predictor (including BatchPredictor and PredictorDeployment)
        - https://github.com/ray-project/ray/issues/37489
        - https://github.com/ray-project/ray/issues/38293
    - *Checkpoint (as well as the old air.Checkpoint class. There is a new, simplified train.Checkpoint class)
        - https://github.com/ray-project/ray/issues/38291
        - https://github.com/ray-project/ray/issues/38292
- Other major changes
    - New persistence API REP (https://github.com/ray-project/enhancements/blob/main/reps/2023-06-06-simplify-sync.md)
        - https://github.com/ray-project/ray/issues/38294
    - TorchTrainer subclass simplifications (https://github.com/ray-project/enhancements/blob/main/reps/2023-07-20-torch-trainer-apis.md)
        - https://github.com/ray-project/ray/issues/38295
    - Removing the "air" package namespace and consolidating on train (https://github.com/ray-project/enhancements/blob/main/reps/2023-07-08-air-surface-syntax.md)
        - https://github.com/ray-project/ray/issues/38296

See also the migration guide issue here: https://github.com/ray-project/ray/issues/37868
This issue is for work tracking.

**Comment by anyscalesam** [comment]
Reviewed today - on track to close remaining 3 sub GH Issues by RC deadline tomorrow.

**Comment by anyscalesam** [comment]
All children tasks look closed - @matthewdeng can we close this master task?
