### ISSUE TITLE
[tune/train] Implement new persistence strategy and roll out as default option

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#38294]
Implement the following REP: https://github.com/ray-project/enhancements/blob/main/reps/2023-06-06-simplify-sync.md

Subtasks:
- https://github.com/ray-project/ray/issues/38568
- https://github.com/ray-project/ray/issues/38573
- https://github.com/ray-project/ray/issues/38576
- https://github.com/ray-project/ray/issues/38572
- https://github.com/ray-project/ray/issues/38569
- https://github.com/ray-project/ray/issues/38612
- https://github.com/ray-project/ray/issues/38567
- https://github.com/ray-project/ray/issues/38570
- https://github.com/ray-project/ray/issues/38571
- https://github.com/ray-project/ray/issues/38574
- https://github.com/ray-project/ray/issues/38575
- https://github.com/ray-project/ray/issues/38577
- https://github.com/ray-project/ray/issues/38579
- https://github.com/ray-project/ray/issues/38589

Related prs:
- https://github.com/ray-project/ray/pull/37690
- https://github.com/ray-project/ray/pull/37909
- https://github.com/ray-project/ray/pull/37925
- https://github.com/ray-project/ray/pull/37962
- https://github.com/ray-project/ray/pull/37888
- https://github.com/ray-project/ray/pull/38057
- https://github.com/ray-project/ray/pull/38141
- https://github.com/ray-project/ray/pull/38143
- https://github.com/ray-project/ray/pull/38128
- https://github.com/ray-project/ray/pull/38284
- #38355 
- #38382 
- #38617 
- #38648 
- https://github.com/ray-project/ray/pull/38598

**Comment by anyscalesam** [comment]
Keep this open until docs merge as part of RC tomorrow @justinvyu

**Comment by anyscalesam** [comment]
Docs are all merged!
