### ISSUE TITLE
[air] Implement removing the "air" package namespace and consolidating on train

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#38296]
Implement the following REP: https://github.com/ray-project/enhancements/blob/main/reps/2023-07-08-air-surface-syntax.md

**Comment by anyscalesam** [comment]
Only remaining work is documentation follow up; this can come later.

**Comment by anyscalesam** [comment]
Reviewed - leaving it open @matthewdeng to sanity check.

**Comment by anyscalesam** [comment]
@matthewdeng to do one more pass this week.

**Comment by matthewdeng** [comment]
We took another pass this week and this should be done from the Train/Tune perspective for 2.7.
