### ISSUE TITLE
Convert Plasma socket code to asio

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#3833]
This would involve porting https://github.com/apache/arrow/blob/master/cpp/src/plasma/io.cc in a similar way as in https://github.com/ray-project/ray/pull/3784/files

This is needed for #631

**Comment by zhijunfu** [comment]
A related issue is to migrate from event loop to asio, as tracked in [#ARROW-4418](https://issues.apache.org/jira/browse/ARROW-4418)

**Comment by richardliaw** [comment]
closing this bc stale
