### ISSUE TITLE
[CI] `windows://python/ray/tests:test_actor_bounded_threads` is failing/flaky on master.

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#38330]
- c81267e93c22193a9b7e20fc5e775f6f36fb3571 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5392#0189e067-f660-4880-93f8-aefe97a07601)
- cd00abfcc8bfff739305c416d6756437d5dabd11 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5390#0189e04a-a496-4349-b07c-fb4d78f2dc6d)
- 03be66cc26d86652360e3f7096fbad1ed3554f77 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5389#0189e04a-49dc-4b0e-a363-aa1df9bb5e94)
- 3ef2c1511820b9dffa8ae142df4a7cfe60284872 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5387#0189e007-83d1-4242-8281-d4cb0619363b)
- c6514548ffa01f11f247bb8aff994f210ce546c8 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5386#0189dff5-5787-4c17-a061-22c108818975)
- b8fe3797dba46e2035950dd1aef133c347d88bc5 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5385#0189dff3-c086-4739-ac33-54406d406700)
- e3db80c38ed21386e78bb371e0e5fe8df5f27763 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5383#0189dfe6-110f-4f9f-965f-8dda5ad2d455)
- cfe608c83e0b9baeb94f5734f3535bebd9270732 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5381#0189ddfa-8327-43ee-b74f-73c032839e28)
- 0dd32ed58747326a657a872b6f8d0c3a0a778f78 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5376#0189dcc5-a287-46e3-87a0-3350fb782550)
- cb601f872f5d640f7f421a48642ee07faf64c63a FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5372#0189dc17-ea5d-4060-83e3-59f3f5efc72a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_actor_bounded_threads-END
....

**Comment by rickyyx** [comment]
@rynewang  seems this been failing on windows since you added it. Any idea why?

**Comment by rynewang** [comment]
Looks like timeout. Making it to medium...

**Comment by rkooo567** [comment]
<img width="1330" alt="Screenshot 2023-08-22 at 11 24 40 PM" src="https://github.com/ray-project/ray/assets/18510752/f6d0907c-3172-4a30-800f-9ffc15aeb965">

It seems still pretty flaky. @rynewang is this expected?
