### ISSUE TITLE
[tune] Incorrect end of trial increment for function API

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3834]
Seems to be an indexing problem when running experiments with the functional API. From the mailing list:

> I'm running with a simple trainable function (so no Trainable sub-classing) but I still seem to have every trial run have '2' as the iteration count, e.g. TERMINATED [pid=3942], 327 s, 2 iter <--- how is this possible? Surely there's only 'one' iteration per trial to be done if I'm not doing any checkpointing etc?

**Comment by gehring** [comment]
This question might be better in a standalone issue, but why is the function runner implementation so complex? Is there a reason why a multi-threaded solution with sleeps was used?

I think I might be able to propose/contribute an alternative design that would unify the logging behavior of the function API and the trainable API (and simplify function_runner.py) but I want to make sure I understand a bit better what led to this implementation.

**Comment by richardliaw** [comment]
@gehring Sorry missed your message - the function runner allows users to quickly integrate their original training loops into Tune without restructuring their code and only adding a reporter call. Does that make sense? Let me know what you had in mind

**Comment by richardliaw** [comment]
Hm,  this looks promising! I think the only thing is seeing whether or not
you can actually serialize the generator and pass it around to multiple
processes/machines.

That being said, if there's no weird gotchas, a prototype would be awesome!
It looks way cleaner (and obviously we would want to maintain support for
the reporter and Trainable for backwards compat).

Richard

**Comment by gehring** [comment]
Great! I opened a standalone issue (#3956) so we can close this one. I will probably be able to start writing a prototype this week. I wouldn't expect serialization to be more harder than what it is in the current solution so hopefully I don't encounter any weird issues!
