### ISSUE TITLE
Problems with ray cluster of more than 100 nodes

### ISSUE THREAD

**Issue by xutianming** [ray-project/ray#3836]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Ray installed from (source or binary)**: source
- **Ray version**:0.6.1
- **Python version**:Anaconda 2.7.15
- **Exact command to reproduce**:

### Describe the problem

I was trying to run a simple word2vec example on a ray cluster of 100~200 nodes.
https://github.com/xutianming/ray/blob/dev_word2vec/examples/word2vec/driver.py
This implementation is just for testing and it can be improved for better efficiency.

I was using a corpus of 1,800,000 words and the embedding size was 128. The weights size was around 1.8GB. It was a pretty large task but in practice the vocabulary could be even larger. 

Here are some problems pending investigation. 
The key to reproduce these problems is to scatter actors to every node (by specifying num_cpus of an actor to exceed half of cpu number of one node).

#### 1. Object Manager check failed
![image](https://user-images.githubusercontent.com/4970790/51651043-75fc5400-1fc5-11e9-963c-9f16c99ef122.png)

#### 2. RayTaskError: Invalid return value
![image](https://user-images.githubusercontent.com/4970790/51651478-012a1980-1fc7-11e9-96f1-3241316a85f3.png)

#### 3. Plasma Store eviction failed
Smaller tasks (around 10 nodes/actors) could run but plasma store (with 20GB memory) got full quickly. Pending object creation suffered from frequent object eviction due to lack of enough space which slowed down the cluster greatly.  The eviction policy even failed to delete any objects sometimes.
![image](https://user-images.githubusercontent.com/4970790/51651370-9082fd00-1fc6-11e9-9922-25a605006951.png)

**Comment by xutianming** [comment]
I looked into these problems these days. The problems were all caused by lack of enough plasma store space on driver node. I found an interesting problem that was worth noting.

1.  I created 99 actors that were scattered among 100 nodes. One node was scheduled onto the same machine with the driver.
```python
actor_list = [Word2VecModel.remote() for i in range(99)]
weight_list = [actor.step.remote() for actor in actor_list]
```
2. Every actor executed a task which created a object of around 1.8GB.
3. Then I started to pull the objects to the driver one by one using `ray.get`.
```python
for i in range(99):
    w = ray.get(weight_list[i])
```
![image](https://user-images.githubusercontent.com/4970790/52042058-2397d600-2577-11e9-9707-69884d774461.png)
![image](https://user-images.githubusercontent.com/4970790/52042112-4aeea300-2577-11e9-968a-c003379046bb.png)

4. As shown in above logs, the object was created on the driver node but soon got evicted due to lack of space.
5. After about 2 minutes, the driver started to retrieve the object using `ray.get`.
![image](https://user-images.githubusercontent.com/4970790/52042188-7a9dab00-2577-11e9-9910-23328dd4dd57.png)

6. Because the object `0100000055923bfa9e0a1975a1c8093051aad4f7 ` was already evicted, so the actor tried to resubmit the task.

7. The resubmitted task was ignore at [node_manager.cc#L1263](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L1263).
![image](https://user-images.githubusercontent.com/4970790/52042943-66f34400-2579-11e9-9948-3fcc4cbb96ed.png)

8. Then the task failed.

Is this the expected behavior ?

**Comment by stephanie-wang** [comment]
Thanks, @xutianming, that's very helpful! Yes, the problem with reconstructing evicted actor objects is that to do it, you have to roll back the actor to a previous state and play it forward again. Unfortunately, this can easily get unmanageable because it's possible you'd have to roll back another actor to reconstruct the first one, and so on.

We are interested in ways to prevent this problem, but we're not quite sure what APIs to provide yet. Things that might be helpful in your case are: (1) forcing all the actors to be placed on other nodes, and/or (2) pinning certain objects. Do you have any thoughts about how useful these or other APIs would be?

Also, in the future, we'd like to make the error messages better, so that it's immediately obvious that the task failed because its return objects were evicted. I opened an issue to track the progress for that (#3919).

**Comment by ericl** [comment]
Are there action items here?

**Comment by xutianming** [comment]
@ericl Currently [PR#4039](https://github.com/ray-project/ray/pull/4039) was the only action item. We'll get back to you if we have any new ideas.
