### ISSUE TITLE
[RLlib] Fix for #36814 (Multi-Categorical and logp) not in Ray 2.6

### ISSUE THREAD

**Issue by jdchn** [ray-project/ray#38371]
### What happened + What you expected to happen

The [Ray 2.6.0 Release Notes] mention an RLlib fix:

* Fix bug in Multi-Categorical distribution. It should use logp and not log_p. (#36814)

But the fix only exists on [master](https://github.com/ray-project/ray/blame/2330b5ad79ce11f6ce9f3dfac9e1aff6c6321a18/rllib/models/torch/torch_distributions.py#L313) — It is missing from tags [2.6.0](https://github.com/ray-project/ray/blame/ray-2.6.0/rllib/models/torch/torch_distributions.py#L321), [2.6.1](https://github.com/ray-project/ray/blame/ray-2.6.1/rllib/models/torch/torch_distributions.py#L321), and [2.6.2](https://github.com/ray-project/ray/blame/ray-2.6.2/rllib/models/torch/torch_distributions.py#L321).

The fix is also missing from the [Ray 2.6.2 source code] and [Ray 2.6.2 PyPI wheels].

See #36803 for a discussion on the original bug and its impact.

#35923 may (or may not) be related.

[Ray 2.6.0 Release Notes]: https://github.com/ray-project/ray/releases/tag/ray-2.6.0
[Ray 2.6.2 source code]: https://github.com/ray-project/ray/archive/refs/tags/ray-2.6.2.zip
[Ray 2.6.2 PyPI wheels]: https://pypi.org/project/ray/#files

### Versions / Dependencies

Ray 2.6.0, 2.6.1, 2.6.2

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @jdchn Once a release is out, fixes will only be included in following release (save for some very special cases).
It would have been good if the fix you are referring to would have made it into any of the 2.6 releases, but we did not cherry pick it because it was deprioritized. You will have to wait for Ray 2.7 - which will have this fix.
