### ISSUE TITLE
Can ray support develop RL apps intergrated with spark streaming and tensorflow 

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#384]
Deep Reinforcement learning needs the ability of deep learning. 
I believe reinforcement learning is the key app pattern of ray. And I also know Ray can be used with tensorflow.
However, to develop a real-time decision system, the streaming data support is also very import as well as deep learning support. Can ray support developing RL apps intergrated with spark streaming (or drrizle in the future) and tensorflow

Here is a picture of Ion Stoica's talk on spark summit
https://yqfile.alicdn.com/d1f22e69bbd4289f6719f6bda44393f32f75a839.png
It looks like Ray will support Spark.

**Comment by robertnishihara** [comment]
I agree that some form of streaming support is important, though I'm not yet sure what form that will take! So it's safe to say that integration with Spark Streaming is not on the near-term roadmap.

**Comment by robertnishihara** [comment]
Closing for now, but please reopen if you have more thoughts or questions about this!
