### ISSUE TITLE
[rllib] IMPALA implementation drops one experience per unroll

### ISSUE THREAD

**Issue by bjg2** [ray-project/ray#3841]
### Describe the problem
When calculating VTraceLoss in VTracePolicyGraph all the experiences from the unroll are taken except for the last one, which is used for bootstrap_value. As far as I can see, that experience is never learned on (that action/reward/behavior is just thrown away and not repeated in the next unroll). That experience should be repeated as the first experience of the next unroll.

### Source code / logs
In VTrace implementation in https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/impala/vtrace_policy_graph.py, take a look of VTraceLoss arguments (at the moment lines between 175 and 189). I haven't found the place in the code where the experience is repeated in the next batch.

**Comment by ericl** [comment]
Just curious, is this an issue for you? I can see it being a problem if episode lengths line up exactly with the batch size, but otherwise you just lose some tiny fraction of sample efficiency.

**Comment by bjg2** [comment]
Well, I wouldn't say it is a big issue, but the system drops some experiences. It could happen that experience carries important information, like a big reward or something. In the [deepmind implementation](https://github.com/deepmind/scalable_agent), they send the same experience again in the next batch.

**Comment by ericl** [comment]
Yeah I think it would be an option for IMPALA only, though the learning
impact won't be huge, since you're just randomly increasing the probability
of some samples -- so no bias, but a bit of extra variance.

**Comment by bjg2** [comment]
You would not `randomly increasing the probability
of some samples`, but would learn on samples that are currently not learned on. So you would not have them more than other samples, you would learn from each sample exactly once (currently rllib is not learning from the last sample of the unroll).

**Comment by ericl** [comment]
Yeah, I was referring to other algorithms if we were to enable repeat for
them. Though the converse is true, since the unrolls are random slices of
episodes there is no bias (unless the episode lengths align with batch
sizes, in which case learning could be severely impacted).

**Comment by bjg2** [comment]
Oh, I misunderstood, sounds good!
