### ISSUE TITLE
[Tune] Specify the timeout for each trial and use ray.tune.Stopper in air.RunConfig

### ISSUE THREAD

**Issue by nateyoder** [ray-project/ray#38421]
### Description

From the documentation it appears as though to stop individual trials after a certain amount of time you need to [specify stop as a dict with time_total_s](https://docs.ray.io/en/latest/tune/tutorials/tune-stopping.html#stop-trials-after-a-certain-amount-of-time) while the only Timeout option for the [run.tune.stopper.TimeoutStopper](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.stopper.TimeoutStopper.html) applies to the entire experiment budget. Because I would also like to use other stoppers (e.g. ExperimentPlateauStopper) I don't see any way to both set a time limit for individual trials AND use a CombinedStopper. The code currently does not appear to handle both: https://github.com/ray-project/ray/blob/2ffe613248f39ebea725c76a5e86dfcb2db6040d/python/ray/tune/experiment/experiment.py#L271-L300

**Comment by matthewdeng** [comment]
Can you pass in a list of different Callbacks?
