### ISSUE TITLE
[CI] `windows://python/ray/tests:test_cancel` is failing/flaky on master.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#38429]
- 50650d4e38b735ef38787a658fb94372f0b089c3 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5446#0189f554-b1cf-4a00-8091-20edc8664674)
- e08907ec95a93302d1f1a6c58e084e6155173bb8 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5440#0189f497-9461-4c66-88f1-dc02e7dbad55)
- b4d25102bb824a3b2a3db35f8d996a8fe2367932 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5432#0189e839-c78b-4561-aab6-8de1253f65e1)
- 7185307f9122c67bca4ba8ef430c5bcb9b8bf42c FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5430#0189e746-f007-4f35-b32c-e1cfb1b51a51)
- 13f2e1c250170923661add8b02e381701be23468 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5428#0189e6e5-53b7-4fb7-b5fa-b0c7b0666713)
- f1ead1484cb6b8afb29a44ce08746ca3c74ea453 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5427#0189e6e0-9412-40d5-b7f8-76b4c9a43942)
- 2330b5ad79ce11f6ce9f3dfac9e1aff6c6321a18 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5422#0189e614-ec4b-46d2-88f8-6fdbfb057df2)
- 3ef2c1511820b9dffa8ae142df4a7cfe60284872 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5387#0189e007-83d1-4242-8281-d4cb0619363b)
- 351cd3ed548be95018f5c6ae976db18c85813f5f FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5384#0189e099-27d5-44e9-830e-ffa58aee3d3e)
- e3db80c38ed21386e78bb371e0e5fe8df5f27763 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5383#0189dfe6-110f-4f9f-965f-8dda5ad2d455)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_cancel-END
....

**Comment by rkooo567** [comment]
I believe it will be fixed by https://github.com/ray-project/ray/pull/38559

**Comment by rkooo567** [comment]
Let's see how it goes

**Comment by rkooo567** [comment]
fixed

**Comment by rkooo567** [comment]
<img width="930" alt="Screenshot 2023-08-24 at 7 01 43 PM" src="https://github.com/ray-project/ray/assets/18510752/e0028224-a831-4c15-9088-03cbc936a8a9">
