### ISSUE TITLE
[CI] `osx://python/ray/tests:test_reconstruction` is failing/flaky on master.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#38431]
- b4d25102bb824a3b2a3db35f8d996a8fe2367932 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5432#0189e839-d29f-408a-9b98-36aa758e5b68)
- 6deefe6c22026d31a73c77e79fc5522f7f5c3f7d FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5419#0189e5f0-af6d-40ec-9433-c58e48c8ac01)
- 1409c96a9a99d1d798bcd1359e1b54a621da831e FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5403#0189e2d3-ee2f-43f9-b73d-5bfb4a591ea1)
- 49591f4c1630ff3d9d1108d699452a6ad58d3d55 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5401#0189e1e3-0139-4ed5-9582-63136628a97a)
- b5cccece76604f882613572fbf44ce98a7a68541 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5394#0189e090-81bf-4183-99ee-1a048b6df953)
- c81267e93c22193a9b7e20fc5e775f6f36fb3571 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5392#0189e067-f8fa-44ef-a5f3-7566e3590b6b)
- e699e98036960ad01cf686a51652ac32020ece8f FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5373#0189dc3a-3a6b-4451-95ff-c450bbfca155)
- 9c193f47ec44b80ccfd08ba9c14649944224cc95 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5355#0189d8a6-dd59-4f07-a937-893d5d5f1ae5)
- 36965bad8a7f381c121f580bdab12fc24b2229c0 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5354#0189d87c-d565-4b39-96fe-5c28fb4ff6bb)
- f55b25aa3edd02b1d1b2080ed67bed8c9ff66a1a FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5343#0189d725-5dc0-4e40-af46-1dcb1375a39c)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_reconstruction-END
....

**Comment by scv119** [comment]
might due to the same reason as osx://python/ray/tests:test_reconstruction_2

**Comment by stephanie-wang** [comment]
No longer flaky.
