### ISSUE TITLE
Hi, is there a way to  use GPUs and parallel CPUs at the same time?

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#3845]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

I create some actors to run the simulation to generate experiences, the policy network forward(net.forward) uses GPUs and the simulation(env.step) use the CPUs. However, the workers only use GPUs(I set the worker @ray.remote(num_gpus=2)), there is no parallel CPU processes happen. Is there a way to use multiple CPUs and GPUs both at the same time? Thanks.

**Comment by robertnishihara** [comment]
If you want the policy network to not use any CPU resources, then you can declare it with `@ray.remote(num_cpus=0, num_gpus=2)`. Let me know if that works for you.
