### ISSUE TITLE
[Data] Progress bars don't work correctly if block splitting

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#38482]
### What happened + What you expected to happen

At first, my progress bar says there are 20 blocks in total.

```
Running: 10.0/10.0 CPU, 0.0/0.0 GPU, 990.31 MiB/512.0 MiB object_store_memory:  60%|█████████▌      | 12/20 [00:04<00:02,  3.62it/s]
```

But once the progress bar gets to 100%, my program keeps running and the total number of blocks increases.

```
Running: 9.0/10.0 CPU, 0.0/0.0 GPU, 0.03 MiB/512.0 MiB object_store_memory: 100%|███████████████████| 46/46 [00:15<00:00,  3.35it/s]
```

### Versions / Dependencies

Ray: 50650d4e38b735ef38787a658fb94372f0b089c3

### Reproduction script

```python
import ray
import numpy as np


def generate_image(batch):
    batch["image"] = np.zeros((len(batch["id"]), 4028, 4028, 4))
    return batch


ds = ray.data.range(100).map_batches(generate_image).map(lambda row: row).materialize()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ericl** [comment]
Hmm, @raulchen I guess last time you changed this to update the "total" when we exceed the original total. Maybe we should try to extrapolate an estimated total based on `(num_output / num_finished) * original_total`?

**Comment by raulchen** [comment]
> Hmm, @raulchen I guess last time you changed this to update the "total" when we exceed the original total. Maybe we should try to extrapolate an estimated total based on `(num_output / num_finished) * original_total`?

Right, I was also thinking of doing this.

**Comment by scottjlee** [comment]
FYI @raulchen i asked @Zandew to take this issue -- let us know if you have any other thoughts
