### ISSUE TITLE
Release test tune_cloud_no_sync_down.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38492]
Release test **tune_cloud_no_sync_down.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2051#0189fd89-93d0-4cae-af4b-d7904cf27950 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by justinvyu** [comment]
This release test has been removed by https://github.com/ray-project/ray/pull/38478
