### ISSUE TITLE
[core] Potential performance regression during ray start due to new RPC

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#38509]
A new blocking RPC to GCS was added to ray start in https://github.com/ray-project/ray/pull/37583. Measure the regression and optimize if necessary.

**Comment by scv119** [comment]
cc @iycheng can you add a bit more details for the repro?

**Comment by vitsai** [comment]
Can check this with `ray start --head`.

**Comment by vitsai** [comment]
Root cause is the newly added blocking RPC when initializing the GCS client during ray start, which takes 5 seconds and occurs before all other processes are started. This RPC basically serializes the rest of ray start after GCS server completely starts.
