### ISSUE TITLE
[Core] holistic design for supporting accelerators in ray core

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#38504]
### Description

We have seen increasing demands for support accelerators in Ray core, including AWS neurons, TPUs, AMD GPUs and Intel accelerators. Currently we are doing it incrementally but we might lose the big picture. We should do a proper design after 2.7.

### Use case

intel https://github.com/ray-project/ray/pull/38553
aws https://github.com/ray-project/ray/pull/37998
tpu https://github.com/ray-project/ray/pull/38669
amd ?

_No response_

**Comment by scv119** [comment]
intel https://github.com/ray-project/ray/pull/38553
aws https://github.com/ray-project/ray/pull/37998
tpu https://github.com/ray-project/ray/pull/38669
amd ?

**Comment by xwu99** [comment]
> ### Description
> We have seen increasing demands for support accelerators in Ray core, including AWS neurons, TPUs, AMD GPUs and Intel accelerators. Currently we are doing it incrementally but we might lose the big picture. We should do a proper design after 2.7.
> 
> ### Use case
> intel #38553 aws #37998 tpu #38669 amd ?
> 
> _No response_

Intel GPU: #38533 
Intel Gaudi: #39759

**Comment by anyscalesam** [comment]
@jjyao @scv119 does the new abstraction layer implemented not address this or is there more we can do? cc @xieus

**Comment by jjyao** [comment]
Design is here: https://github.com/ray-project/enhancements/pull/46
