### ISSUE TITLE
ray.sleep?

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#3851]
Just a basic question about ray api:

- If I want to implement a `timer` that does some compute every x seconds, how should I implemented it efficiently in Ray? Does Ray support some sort of `thread_sleep` kind of API that will not consume resource when a task/actor needs to sleep for some time?

- Example:
```python
@ray.remote
def timer():
    # do some check
    ...
    # then schedule itself for next invocation
    timer.remote() # however I want this to be scheduled at least 5 seconds later. 
```

- Use case: [a queue monitor for prediction severing](https://github.com/simon-mo/corvette/blob/b667bfad645602c9b21b9678bacee3a4f8052b8c/corvette/frontend.py#L44-L69). so instead of calling the queue processing function non-stop, resulting 90% of the call are noops, I would like to call the queue processing function only when:
    - Some input was ingested in the queue
    - Some output was finished processing
    - Every 0.5 seconds for sanity check.

**Comment by ericl** [comment]
ray.remote(num_cpus=0) will do what you want I think. There is very little overhead in a sleeping process
