### ISSUE TITLE
[docs][docs infra] Cannot scroll to bottom of filter column in Examples Gallery 

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#38531]
### Description

Not able to scroll to the bottom of the filter column to choose "HuggingFace" unless I scroll to the bottom of the RHS column.
cc: @simran-2797 

Screen Recording 2023-08-16 at 4.03.59 PM

### Link

https://docs.ray.io/en/latest/ray-overview/examples.html

**Comment by peytondmurray** [comment]
I can't see the screen recording, but I can reproduce this. I'll make the tags section separately scrollable.
