### ISSUE TITLE
[Ray serve] internal log configurations overwrite my own loggers 

### ISSUE THREAD

**Issue by Toekan** [ray-project/ray#38556]
### What happened + What you expected to happen

Hey,

Thanks for all the great work on this package! 

I’ve been browsing through documentation and the python ray codebase, but can’t seem to find a solution.

I’m using ray serve (in the CLI, so ray serve my_script:my_model ) and I want all my logs to be fully in JSON format, unfortunately that seems a lot harder than expected. Whenever any of Ray’s functionality internally calls [configure_component_logger](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/logging_utils.py#L158), I don’t manage to undo some of the streamhandler’s prefixes. On top of that, configuring the `ray.server` loggers in MyModel's `__init__` gets undone later, I need re-configure the logger in exposed method on every call.

### Versions / Dependencies

Ubuntu 20
python 3.8
Ray[serve] 2.6.1

### Reproduction script

```
@serve.deployment
@serve.ingress(app)
class MyModel:
    def __init__(self):
         pass

    @app.get(
        "/health",
        summary="Health Check",
        description="Check whether the service is up and running.",
    )
    async def health(self):
        # Doing this in the init does not work to get a JSON formatted output, I have to do it in
        # the method...
        _logger = logging.getLogger("ray.serve")
        _logger.handlers.clear()
        handler = logging.StreamHandler()
        handler.setFormatter(get_formatter(log_format=LOG_FORMAT))
        _logger.addHandler(handler)

        _logger.info("I'm healthy!")

        return {"status": "healthy"}

my_model = MyModel.bind()
```

get_formatter is code I can’t share, but it creates a formatter (with structlog) that structures the logs into JSONs. Unfortunately two things break my approach here:

- Updating the handler in the init does not work, between the init and the method (here health), something happens that undoes my handler configuration. I suspect in RayServeWrappedReplicate [here](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L100).
- Even when I put the logging configuration in the method itself, just before doing the logging, my stdout logs get an unwanted prefix:

```
(ServeReplica:default_MyModel pid=382) {"event": "I'm healthy!", "level": "info"}
```

It should be possible to fully configure Ray Serve logging, without having to reconfigure the logger inside the non-init endpoints? It's ok to have attributes added (pid and model/actor in my log), but I would expect to have full control over the handlers, formatters and filters?

### Issue Severity

None

**Comment by akshay-anyscale** [comment]
did you try https://docs.ray.io/en/latest/serve/monitoring.html#json-logging-format for json logging?
