### ISSUE TITLE
[rllib] IMPALA creates not-needed environments

### ISSUE THREAD

**Issue by bjg2** [ray-project/ray#3856]
### Describe the problem
Every agent has local evaluator + wokers_num of remote evaluators. Each evaluator creates num_envs_per_worker environments, even the local one. In IMPALA training, local evaluator is used for optimizer and it does not use environments, so there is num_envs_per_worker too much. This can be a problem, as environments can use resources, as it is an example with SC2 environment we're using (each env takes ~0.5gb of RAM).

### Source code / logs
The mentioned code is in policy evaluator in the constructor in https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/policy_evaluator.py. All environments (local/remote) are treated equally. Local/remote evaluators are created in _make_evaluator at https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/agent.py.

**Comment by ericl** [comment]
The issue is that we need to create the env in order to get the action and observation spaces.

However, we won't call reset () until needed, so you can avoid this issue by moving expensive initialization code into reset(). Does that work?

**Comment by bjg2** [comment]
Well, I'm not sure because init takes ~15 seconds (probably not the best to be in reset), and reset method by design might be called more than once (though I'm not sure if rllib does so).

I created a gitlab fork and did the simplest hack making sure environment don't init external SC2 env when that env will not be used, but still having the env so that spaces can be found. At some point I will return and do the pull request, but I'm not sure if the solution for my problem aligns with all the other abstractions - you might want to do it differently, so I opened an issue for you to think about the problem.

**Comment by ericl** [comment]
Yeah, you have to a bit careful to avoid the issues you mentioned. We call reset() almost immediately so there's not much delay there. It is called more than once so you need to avoid doing duplicate work then.

Unfortunately I don't know if it's possible to get the obs and action spaces otherwise.

Btw there's an example of a SC2 env that does this deferred init: https://github.com/oxwhirl/smac/commit/91761f15c807be20f0a7f7968045e4f495ad8b16

**Comment by bjg2** [comment]
Changed to initialize environment in reset, and it works good enough for me. Feel free to close this issue if you think initialization in reset is by design, but maybe some other solution could be preferred.
