### ISSUE TITLE
Benchmark with jemalloc-based Arrow allocator

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#386]
This is not urgent, but @xhochy has seen pretty good speedups from using the jemalloc allocator in his workloads, so this may be useful

**Comment by robertnishihara** [comment]
This is already the default, right? https://github.com/apache/arrow/blob/a9f0c63ad9b8942f3287da2b7109d486d92731b0/cpp/CMakeLists.txt#L91

**Comment by xhochy** [comment]
No, it is build by default but you need to explicitly pass `arrow::jemalloc::MemoryPool::default_pool()` to each function. Otherwise you'll get the default POSIX one.

**Comment by robertnishihara** [comment]
Oh I see, thanks for the tip! We'll give it a try.

**Comment by robertnishihara** [comment]
Closing for now, by default we'll use whatever the Arrow default is.
