### ISSUE TITLE
Release test workspace_template_batch_inference.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38659]
Release test **workspace_template_batch_inference.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2058#018a1815-c1af-4ff8-a9ba-251fe76553d4 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: d76c1a1dd2e64f632b7166712e34f96ae932ba2d found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/539

**Comment by matthewdeng** [comment]
@raulchen  looks like this change affected a few tests in CI as well, could you take a look?

<img width="1445" alt="image" src="https://github.com/ray-project/ray/assets/3967392/dec6bdfc-6755-44a5-b7bb-90c05fadb82a">

**Comment by raulchen** [comment]
Taking a look.

**Comment by raulchen** [comment]
should be fixed by https://github.com/ray-project/ray/pull/38667
