### ISSUE TITLE
[CI] `windows://python/ray/tests:test_storage` is failing/flaky on master.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#38664]
- 03ae7790fb8c11a40f88c3186baf6556a2eaecdd FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5579#018a1814-960b-46be-9865-10a86d386dca)
- e1c48ab8b1225daa44ea63ed1e7dc956b0e7f411 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5577#018a14f6-55df-416c-9661-88ef6ae599ab)
- e78b0ef566a728f6c91caf84f1dd9192d30908f8 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5574#018a0bd1-cdec-493f-b523-b4ed7047c931)
- 8fcb4f8cfd928e45af57c5ad3e5e256ccd1ad5b0 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5565#018a0a1a-c11d-4b7b-8c82-7601a883bbb2)
- 55cf65d28821bc7cdfeba529ede1e1675e3c86d4 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5521#018a0180-868d-4f26-a210-8f4c5d79e3a6)
- 120d89287663926bbf6341a9f7b96b39293bd05b FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5491#0189fec2-2fe7-4de5-8914-56257aa68a2c)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_storage-END
....

**Comment by rkooo567** [comment]
Marked it as P1 for now. Seems not too bad in the recent runs
