### ISSUE TITLE
[CI] `linux://python/ray/tests:test_draining` is failing/flaky on master.

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#38666]
- 671cecc4877c9cb1beb2af1b4e485cd6bce0bf26 FAILED [Buildkite :python: core](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5510#018a009c-1bb6-495e-89ea-aa6e3c80e66a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_draining-END
....

**Comment by rkooo567** [comment]
Marked it P1 as this never fails 3 times in a row (only yellow)
