### ISSUE TITLE
Release test stress_test_many_runtime_envs.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38662]
Release test **stress_test_many_runtime_envs.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2057#018a1723-e524-4ddf-aab3-3976c3ae116d for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: f2f6358a89c5cbeb01e93a1bac6eb0b6070690ac found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/537

**Comment by iycheng** [comment]
@can-anyscale  this is marked as:
```
name:    stress_test_many_runtime_envs.aws
  | status:  transient_infra_error
  | runtime: 0.00
  | stable:  True

**Comment by iycheng** [comment]
Hmmm, weird, why this is claimed as infra error:

```
test_many_runtime_envs.py: error: argument --expected-file-count-in-working-dir: invalid int value: '2--node_id'
```

**Comment by can-anyscale** [comment]
The error classification is based on the return code from anyscale job submission, which I think is also based on ray job submission, so when that part is broken, it always report as infra error - it's not something that well defined especially for core tests

**Comment by iycheng** [comment]
@rynewang could you help fix this and run the release tests? It seems like you forget adding a space between parameters.

https://github.com/ray-project/ray/blob/master/release/nightly_tests/stress_tests/test_many_runtime_envs_runner.py#L53-L54

**Comment by iycheng** [comment]
@can-anyscale  Good to know. My previous impression is that `transient_infra_error` is not something we should look at.

Btw, is the bisecting working for this case? Seems it didn't catch the true offending commit.

**Comment by rickyyx** [comment]
https://github.com/ray-project/ray/pull/38683

**Comment by rickyyx** [comment]
@rynewang could you help take over this issue (and this PR https://github.com/ray-project/ray/pull/38683)? Looks like my attempts in https://github.com/ray-project/ray/pull/38683 doesn't work.

**Comment by rynewang** [comment]
#38772

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by rickyyx** [comment]
> Test has been failing for far too long. Jailing.

why did we downgrade it from P0? what's the jailing policy like? I am afraid this would slow down fixing any failed test if they have been failing for a while due to the lower priority and the jailed status.

**Comment by can-anyscale** [comment]
@rickyyx it was the automation doing under my avatar; we can always keep it as P0. I'll put up a PR.

**Comment by can-anyscale** [comment]
If this is not a release-blocker, can we mark it as unstable and cherry pick the PR, thankks

**Comment by GeneDer** [comment]
Yea, release branch is also failing. Would be great to mark it unstable and cherry pick the PR is it's no longer a release blocker🙏

**Comment by rynewang** [comment]
Marking it unstable for now; fix after 2.7

**Comment by rkooo567** [comment]
We discovered this issue from real user. We should fix this for 2.7

**Comment by rkooo567** [comment]
@rynewang can you provide your wheel to user asap to verify if it fixes their issue?

**Comment by rkooo567** [comment]
Decided not to mark it as a release blocker.
After analyzing logs, it seems to be very niche edge case, and the bug Ruiyang’s PR will handle was just a side effect of other issue.
We will try handling the other issue instead (we will just fail fast when this happens), and will find a proper fix for 2.8

**Comment by anyscalesam** [comment]
@rkooo567 should we downgrade this to p1 per your latest comment then?

**Comment by rkooo567** [comment]
No, we should fix it in 2.8! It is a known issue we decided to fix it for 2.8

**Comment by jjyao** [comment]
It's high risk change and only happen in rare cases so we will merge it to master but not cherry pick to 2.8.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2332#018b6afa-8f07-4956-ad3e-1529737580dc
