### ISSUE TITLE
[train][GA] Update `Trainable.save` and `Trainable.restore` APIs to DeveloperAPI

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#38675]
- [x] Annotate these methods, which are de-factor internal APIs - Kai to do this and cherry pick
- [x] Fix all usage in tests / examples - this is Done.
- [ ] Upgrade `_TrainingResult` to DeveloperAPI `TrainingResult` - This is out of scope for 2.7

**Comment by anyscalesam** [comment]
Open PR > target... 2.8 instead? This would affect cherry pick and make it super difficult. It's also a niche corner case that isn't critical to our users.

Open PR doesn't just add DeveloerAPI label; if that's just the scope we can do that. 

However the Open PR also changes the API always takes in and accepts Training results.

If it's just annotations this can be super easy to do and cherry pick for 2.7.

**Comment by anyscalesam** [comment]
Annotations done and picked into ray27rc. Target for 27 is done.
