### ISSUE TITLE
[Examples] Add MadeWithML notebook to Ray example gallery for "Natural Language Processing"

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#38679]
### Description

@GokuMohandas  has this wonderful notebook here on how to do NLP with Ray Train and finetune a model:

https://github.com/anyscale/Made-With-ML/blob/main/notebooks/madewithml.ipynb

We should add it to the example gallery to make it discoverable :)

**Comment by anyscalesam** [comment]
@angelinalg on next steps

**Comment by angelinalg** [comment]
@GokuMohandas, shall we work on this?

**Comment by angelinalg** [comment]
Added with https://github.com/ray-project/ray/pull/41328
