### ISSUE TITLE
[Train][Ray 2.7] Revamp Ray Train examples with new APIs

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#38681]
### Description

This is a progress tracking issue for all the example updates for Ray Train API Changes.

Add new basic examples:
- #38083 
- #37989 
- #38513

Revamp existing key examples:
- #38009 
- #38600 
- #38682 
- #38686 
- #38814

**Comment by anyscalesam** [comment]
@woshiyyya can we close this; all examples seems to be merged per the above definition.
