### ISSUE TITLE
CPU performance is only used by about 50%

### ISSUE THREAD

**Issue by wangp-nhlab** [ray-project/ray#38704]
### What happened + What you expected to happen

When I reproduce the example of ”Convert existing PyTorch code  to Ray [AIR“,](https://docs.ray.io/en/latest/ray-air/examples/convert_existing_pytorch_code_to_ray_air.html#convert-existing-pytorch-code-to-ray-air) i found that the CPU is not fully functional.
![图片1](https://github.com/ray-project/ray/assets/95683046/db1ebe46-7ba8-45f7-a859-e0dfe44ea21d)

![图片2](https://github.com/ray-project/ray/assets/95683046/f7a2f5e6-f816-4b56-9c29-06ac648d1a0f)

### Versions / Dependencies

ray   2.6.2
python 3.9
os ubuntu

### Reproduction script

example [https://docs.ray.io/en/latest/ray-air/examples/convert_existing_pytorch_code_to_ray_air.html#convert-existing-pytorch-code-to-ray-air](url)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by woshiyyya** [comment]
Hi @wangp-nhlab, that code example is more focusing on introduce Ray Train AIPs, while not trying to maximize the GPU memory util. You can always increase the batch size to use more GPU Memory.
