### ISSUE TITLE
[CI] `osx://python/ray/tests:test_plasma_unlimited` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#38722]
- 992d99bd4003152008414943cca5b78d5c3baa98 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5609#018a1b60-9c1b-44b6-9d30-e56838a0cbf2)
- 2f4b165b4788c88066cd2eb1a08400cd9a1ec938 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5608#018a1b5f-7666-454f-a786-d4e49f648c73)
- 6c1824ce833346f808e2d2bed6a8ef1d29b9a918 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5583#018a18fe-d3ba-4c40-9c83-b9c1a34b407f)
- f2a9ca8dec815ea1de41e785775ed2f2882cef17 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5580#018a1869-0187-4168-9012-318615b4b546)
- 4f5cadc3a5fb6495dc567c2bcdb714fcd8550b5c FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5557#018a06e8-0dd4-4c80-96a6-f4a49fd53070)
- 4d866464e3f31ec81120aceb153536b58c56cbc7 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5520#018a0167-e917-48ee-ae0d-e9898140dd7b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_plasma_unlimited-END
....

**Comment by scv119** [comment]
Looks no longer flaky - potentially fixed by stopping those back mac nodes.

**Comment by rkooo567** [comment]
duplicate https://github.com/ray-project/ray/issues/42537
