### ISSUE TITLE
[CI] `windows://python/ray/tests:test_actor_bounded_threads` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#38724]
- 1efd2e280d7a424d18d5afb8ca822fdfed966980 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5587#018a193d-c58b-43e9-a0dd-40ed9bd174a0)
- 03ae7790fb8c11a40f88c3186baf6556a2eaecdd FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5579#018a1814-960d-41a1-bafb-c893a8e4dce7)
- ca1a546ddd769fac2f0dde9847e937dd89bed17e FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5568#018a0a6d-169d-42e7-a3b2-f300cc727b14)
- a4b1340ea6fb71cc4b402f10d954fddd14999455 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5562#018a09d3-dd2f-4afc-afb0-00c6cc1b8b67)
- ec616c40e0cd09595b280c2b7e940d577e9109dd FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5559#018a0942-152f-4340-9166-092ea914d37f)
- b436657e772a4a0aac17ebf9edebccaa51627dd2 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5554#018a05f0-9c86-4825-9bc8-e8d680e01ebe)
- be2e406901869d9553cb35be0bc107739f3c2bc6 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5548#018a0569-27a3-4147-bb72-c33b68364b40)
- 47edb32eb78cb0b70e3702d0beb1fd75efff92d3 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5546#018a0573-0de0-4130-9f7b-6ae60ff1535b)
- e79c914cba74d782ba97bf2b03a6e75ebc3cc24e FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5541#018a04c0-06be-411a-a059-17fc7edd150d)
- f27bb15868c1e325d579ed25a5c2e7750bf9f3ae FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5535#018a045e-d1dc-412e-9638-1640d4967997)
- 55cf65d28821bc7cdfeba529ede1e1675e3c86d4 FAILED [Buildkite :windows: Build & Test](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5521#018a0180-868f-4c8c-8a8a-81bc895f9b63)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://python/ray/tests:test_actor_bounded_threads-END
....

**Comment by rkooo567** [comment]
@rynewang we should probably cherry pick the test fix (since we merged the gRPC PR to 2.7 branch)

**Comment by rynewang** [comment]
fixed
