### ISSUE TITLE
[tune] Option --no-cuda is misleading in mnist_pytorch.py example

### ISSUE THREAD

**Issue by vfdev-5** [ray-project/ray#3873]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.2
- **Python version**: 3.5
- **Exact command to reproduce**:

```
python3 mnist_pytorch.py
```

### Describe the problem

Argument parser's option `--no-cuda` which is False by default is misleading as `resources_per_trial` does not allocate a GPU.

https://github.com/ray-project/ray/blob/eddd60e14e95a2aadb06192bd141d06c68d5f082/python/ray/tune/examples/mnist_pytorch.py#L45-L49

https://github.com/ray-project/ray/blob/eddd60e14e95a2aadb06192bd141d06c68d5f082/python/ray/tune/examples/mnist_pytorch.py#L178-L180

Thanks

**Comment by richardliaw** [comment]
Nice catch! Would you be interested in pushing a fix?

**Comment by richardliaw** [comment]
I think maybe do something like `"gpu": int(not args.no_cuda)`, since you don't want to set it like that when CUDA is disabled. 

Updating deprecated things would be great; thanks!

**Comment by vfdev-5** [comment]
> I think maybe do something like "gpu": int(not args.no_cuda), since you don't want to set it like that when CUDA is disabled.

@richardliaw yes, but this is handled inside the trial code:
https://github.com/ray-project/ray/blob/eddd60e14e95a2aadb06192bd141d06c68d5f082/python/ray/tune/examples/mnist_pytorch.py#L62
so we can leave savely `"gpu": 1`.

**Comment by richardliaw** [comment]
If you leave “gpu”: 1, the example will not run if Ray does not detect a
GPU.

Thanks,
Richard
