### ISSUE TITLE
[train][GA] Investigate failure mode when error is raised during `on_trial_save` callback hook

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#38734]

**Comment by anyscalesam** [comment]
discovered during switching one of the release tests over; we're going to target this to be after branch cut

**Comment by justinvyu** [comment]
This is an extreme edge case that results from needing restore to a state that exactly matches CI test assertions. See https://github.com/ray-project/ray/pull/43689/files#diff-4e7d4f9dc17af4aefd57416159c0e35276f7c54e3b98292feace780df5bc9934R361-R371
