### ISSUE TITLE
[Train] Re-enable `xgboost-example` and `lightgbm-example` tests

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#38765]
These 2 tests were disabled in https://github.com/ray-project/ray/pull/38640/files#diff-d057af15699ae56c242974deac5a38d02ff02e7b11d6437869fbaf6ccb2f3a05R26-R29.

We need to re-enable them once XGBoost and LightGBM support the new `train.report` path.

**Comment by matthewdeng** [comment]
Closed by #38866.
