### ISSUE TITLE
Issue on page /serve/getting_started.html

### ISSUE THREAD

**Issue by samanvithms2002** [ray-project/ray#38777]
By following the starter commands as mentioned in this page, i am getting the following error:
ERROR 2023-08-23 15:25:21,277 http_proxy 127.0.0.1 router.py:538 - Unexpected error in fulfill_pending_requests.
(HTTPProxyActor pid=24884) Traceback (most recent call last):
(HTTPProxyActor pid=24884)   File "c:\Users\samanvith.ms\Documents\ray-serve\.venv\Lib\site-packages\ray\serve\_private\router.py", line 529, in fulfill_pending_requests
(HTTPProxyActor pid=24884)     async for candidates in self.choose_two_replicas_with_backoff(
(HTTPProxyActor pid=24884)   File "c:\Users\samanvith.ms\Documents\ray-serve\.venv\Lib\site-packages\ray\serve\_private\router.py", line 404, in choose_two_replicas_with_backoff
(HTTPProxyActor pid=24884)     chosen_ids = random.sample(
(HTTPProxyActor pid=24884)                  ^^^^^^^^^^^^^^
(HTTPProxyActor pid=24884)   File "C:\Python311\Lib\random.py", line 436, in sample
(HTTPProxyActor pid=24884)     raise TypeError("Population must be a sequence.  "
(HTTPProxyActor pid=24884) TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

This is happening at the ray-serve internal code which doesn't seem to allow the normal input.
The code run is the same Translator example which is written in the getting started page.

**Comment by GeneDer** [comment]
@samanvithms2002 Thanks for reporting it. I think this is already https://github.com/ray-project/ray/pull/37809 Please try again with Ray 2.7.0 or nightly to see it taking affect
