### ISSUE TITLE
[Core] When the GCS is restarted for HA, it overwrites the previous session directory

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#38796]
### What happened + What you expected to happen

When the GCS is restarted for HA, it overwrites the previous session directory.

It means when you create a new driver after GCS restarts, it will start using a new session_dir. 

This could impact correctness (and usability, for example, dashboard logs will lose previous logs) because there are some logic that we may depend on the session_dir. it is also a blocker to merge https://github.com/ray-project/ray/pull/37644

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by rkooo567** [comment]
What's the progress of this task? There's one issue that's blocked by this, so I'd like to understand the timeline

**Comment by iycheng** [comment]
@rkooo567 sorry I forgot this item :(  I'll sync with @vitsai today to get a clear timeline.

**Comment by vitsai** [comment]
We just synced; this should be done by Wednesday.

**Comment by rkooo567** [comment]
Thank you! This is very important to support multi cloud!

**Comment by vitsai** [comment]
Mis-scoped this, need 1 more day to merge.
