### ISSUE TITLE
[Data] Regression on `parquet_metadata_resolution` and other parquet read release tests

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#38790]
### What happened + What you expected to happen

The runtime for the release test `parquet_metadata_resolution` has increased ~30% in the last several weeks. We see similar regressions for other parquet read tests like `read_parquet_benchmark_single_node (many-files), (nyc-taxi)`

### Versions / Dependencies

ray master

### Reproduction script

release test `parquet_metadata_resolution`

### Issue Severity

High: It blocks me from completing my task.

**Comment by amogkam** [comment]
Looking at the commits this seems to be the relevant pr https://github.com/ray-project/ray/pull/38373

**Comment by c21** [comment]
Looking now.

**Comment by c21** [comment]
See the metrics dropped back to normal on release tests. Keep this open for one more day to make sure it's consistent, before closing the issue.

**Comment by c21** [comment]
Checked the release test metrics, it's consistent in past several days, closing the issue.
