### ISSUE TITLE
[docs] Review all libraries (Train, Data, Serve, Tune) and avoid leaky concepts

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#38795]
### Description

Similar to #38781, we should review the library documentation and identify any instances of:
* remote tasks
* remote functions
* remote objects
* remote actor
* placement groups

And make sure they are either:
* explained
* linked to the glossary term
* removed if unnecessary 

Maybe we can also have some check here but that might be overkill.

**Comment by richardliaw** [comment]
cc @matthewdeng @akshay-anyscale @c21

**Comment by c21** [comment]
Just to clarify on timeline, is it for 2.7?

**Comment by richardliaw** [comment]
My recommendation is P1.
