### ISSUE TITLE
Use clang-tidy to check C++ coding style.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#388]
For example, see https://github.com/apache/arrow/blob/master/.clang-tidy.

**Comment by wesm** [comment]
`clang-format` is much faster than clang-tidy and very useful for code reformatting (but not actually changing any code). clang-tidy can refactor and make actual code changes, but we haven't been using it yet in Arrow (would definitely like to)+

**Comment by mavam** [comment]
A lot of the simple "coding style" enforcements can indeed be covered by `clang-format`. But anything more complicated that operates on the C++ AST requires a more powerful  `clang-tidy`.
For example, enforcing a simple rule that the `typename` keyword should only be used with dependent types is within the realm of `clang-tidy` but exceeds the power of `clang-format`.

**Comment by robertnishihara** [comment]
Good points! We're already using `clang-format` for basic linting, but we're hoping to use `clang-tidy` to more comprehensively enforce style guides and to enforce a limited set of C++ features.

**Comment by richardliaw** [comment]
(closing this as stale)
