### ISSUE TITLE
[CI] `linux://python/ray/tests:test_scheduling_2_asan` is failing/flaky on master.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#38803]
- 48f7b81fa4eeab1eab23f955d6f211f8e6cb34ae FAILED [Buildkite :python: (ASAN tests)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5664#018a23fb-6df6-4682-a165-fba10bd41322)
- da9c511a340cf5e266877659e262bb599d039c54 FAILED [Buildkite :python: (ASAN tests)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5663#018a23dd-0924-486d-a901-36b870112a73)
- a7511a5458502227ffb0c22274b2c7580db8bb15 FAILED [Buildkite :python: (ASAN tests)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5658#018a2367-1b69-4840-8084-9c96da0bae3f)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_scheduling_2_asan-END
....

**Comment by jjyao** [comment]
Reproduced and confirmed that it's due to https://github.com/ray-project/ray/issues/38189
