### ISSUE TITLE
[docs][docs infra][train] Clean up dependencies for local docs build

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#38830]
### Description

An inherent conflict in protobuf version requirements for pytorch_lightning and tensorflow-macos is causing errors in building local docs on M1 laptops. Here are the errors from `pip install -r requirements-doc.txt`:

![Screenshot 2023-08-24 at 9 48 33 AM](https://github.com/ray-project/ray/assets/122562471/db7a49e3-e427-47ca-bd8d-01dea1b44a69)

This PR has a workaround that checks for the platform, but we should clean this up: https://github.com/ray-project/ray/pull/38631
(Thanks to @can-anyscale.)

The Train team is planning to update the pytorch_lightning version to 2.0 in the 2.8 release, which will remove the protobuf requirements: https://github.com/Lightning-AI/lightning/blob/ff5361604b2fd508aa2432babed6844fbe268849/requirements/base.txt#L11

cc: @matthewdeng @pcmoritz @can-anyscale 

### Link

https://github.com/Lightning-AI/lightning/blob/ff5361604b2fd508aa2432babed6844fbe268849/requirements/base.txt#L11

https://github.com/ray-project/ray/blob/master/python/requirements_compiled.txt#L431

https://github.com/ray-project/ray/blob/master/doc/requirements-doc.txt

**Comment by peytondmurray** [comment]
This will be addressed by https://github.com/ray-project/ray/pull/38817. We shouldn't have to install e.g. pytorch just to build docs - we should only have to install it if we are actually going to use it. So the list of dependencies will get much smaller and simpler to solve for doc builds once this gets merged.

**Comment by anyscalesam** [comment]
@matthewdeng can you review merged PR by @peytondmurray  above fixes the root issue? If yes, please close this parent ticket.

**Comment by angelinalg** [comment]
Can we close this now, @peytondmurray ?

**Comment by peytondmurray** [comment]
Yes, let's close this. Please open a new issue if there are further issues with doc dependencies.
