### ISSUE TITLE
Release test long_running_horovod_tune_test.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#38954]
Release test **long_running_horovod_tune_test.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2075#018a34b7-dcc4-4090-9e85-1b201acedc8a for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by woshiyyya** [comment]
I post a PR, hope it would fix. https://github.com/ray-project/ray/pull/39012

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2119#018a55a0-8ad3-46cb-adcd-28725a432bfa
