### ISSUE TITLE
RLlib: Pong benchmark example throws a ValueError

### ISSUE THREAD

**Issue by shehper** [ray-project/ray#38968]
### What happened + What you expected to happen

I tried running one of the [Pong example](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/ppo/pong-ppo.yaml) from [ray/rllib/tuned_examples/ppo](https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/ppo/pong-ppo.yaml).

I obtained "Value Error" reproduced below. 

### Versions / Dependencies

Python 3.9, 
Ray 2.6.3

### Reproduction script

rllib train file ppo-pong.yaml

where ppo-pong.yaml is the file mentioned above. I received the following error: 

ValueError: Your desired `train_batch_size` (5000) or a value 10% off of that
cannot be achieved with your other settings (num_rollout_workers=32;
num_envs_per_worker=5; rollout_fragment_length=20)! Try setting `rollout_fragment_length` to 'auto' OR 31.

The error originates from the function ['validate_train_batch_size_vs_rollout_fragment_length'](https://github.com/ray-project/ray/blob/0b6ca64a6f2220e99617eec16a6173b771e56c67/rllib/algorithms/algorithm_config.py#L3093) in the file ray/rllib/algorithms/algorithm_config.py. 

Either ppo-pong.yaml needs to be updated or this function needs to be removed/edited.  

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ArturNiederfahrenhorst** [comment]
I can reproduce.
@kouroshHakha @sven1977 @avnishn This is one of our most basic examples and it should 100% be working.

**Comment by sven1977** [comment]
Can we simply match the tuned_example file with the yaml file under `ray/release/rllib_tests/learning_tests/yaml/appo`? That one uses Pong as well and works as it's a release test.

**Comment by sven1977** [comment]
Ah, I see, we need to simply change `rollout_fragment_length=auto`. That should fix it.

The problem is that the batch size must be composable of the number of envs in total (num_rollout_workers x num_envs_per_worker) and the rollout_fragment_length

```
ValueError: Your desired train_batch_size (5000) or a value 10% off of that
cannot be achieved with your other settings (num_rollout_workers=32;
num_envs_per_worker=5; rollout_fragment_length=20)! Try setting rollout_fragment_length to 'auto' OR 31.
```

cc: @simonsays1980 :)
