### ISSUE TITLE
[Ray] How to use Tensorflow Estimator ParameterServerStrategy with Ray?

### ISSUE THREAD

**Issue by supercocoa7654** [ray-project/ray#38972]
### Description

How to use Tensorflow Estimator ParameterServerStrategy with Ray?
It seems that there is no such part in the document.

**Comment by anyscalesam** [comment]
@c21 this reads like an offline batch inference item can you review here and see if this is something we want to target for ray 2.8?

**Comment by c21** [comment]
I think this is related to training. cc @matthewdeng.

**Comment by matthewdeng** [comment]
Ray Train doesn't support ParameterServerStrategy out of the box. For TensorFlow you can use the TensorflowTrainer with MultiWorkerMirroredStrategy as described [here](https://docs.ray.io/en/releases-2.7.0/train/distributed-tensorflow-keras.html).
