### ISSUE TITLE
[AIR] How to set `max_actor_restarts` when using `ray.train.xgboost.XGBoostTrainer`

### ISSUE THREAD

**Issue by caren-guo** [ray-project/ray#39022]
### Description

`ray.train.xgboost.XGBoostTrainer` does not have a way to specify `max_actor_restarts` like one would in `xgboost_ray.train(..., ray_params=RayParams(num_actors=10, cpus_per_actor=8, max_actor_restarts=3))`

The new `ScalingConfig` and `RunConfig` does not allow setting this, and `max_failures` in `FailureConfig` seems to be a different thing. Is it possible to make `max_actor_restarts` customizable in the new `ray.train.xgboost` package?

**Comment by woshiyyya** [comment]
@krfricke Can you take a look?

**Comment by caren-guo** [comment]
After trying it out a bit more, I think `FailureConfig` is enough for my use case for now. Sorry about the confusion - closing the issue!
