### ISSUE TITLE
[Dashboard UI] `CPU Flame Graph` and `Stack Trace` are put on the same line together

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#39026]
### What happened + What you expected to happen

<img width="872" alt="Screenshot 2023-08-28 at 2 13 49 PM" src="https://github.com/ray-project/ray/assets/9677264/cf6c6e66-d5fd-4836-b017-794e8ec9ef1f">

We shouldn't put them next to each other

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
cc: @rickyyx @rkooo567

**Comment by scottsun94** [comment]
cc: @rkooo567 @chaowanggg 
If possible, we should include it in 2.7.1. A really bad UI bug.

**Comment by scottsun94** [comment]
@alanwguo @chaowanggg
If possible, we should include it in 2.7.1. A really bad UI bug.

**Comment by chaowanggg** [comment]
Will fix it
