### ISSUE TITLE
[ray.train] Context managers will not trigger `__exit__` in the distributed part of the code on exceptions.

### ISSUE THREAD

**Issue by gabriel-andersson** [ray-project/ray#39055]
### What happened + What you expected to happen

Using `ray.train.torch.TorchTrainer`, when the training is done within a context-manager, and if the training is aborted because of an error in one of our multiple workers, the context managers `__exit__` is only called in the worker that encountered the error. 
This is also a problem if we stop a job through the python api, then the context-manager is not closed properly in any of the workers, since `__exit__`  is not called.

Ray sends a SIGTERM to the python process. One workaround would have been to use `signal.signal` and do something like the outcommented code in the example below. However, python only allows the usage of `signal` in the main thread of the main interpreter. So that will not work.

### Versions / Dependencies

ray[all]==2.5.1

### Reproduction script

```
import signal
import sys
import time
from types import TracebackType
import ray.air
import ray.air.session
import ray.train.torch

class TrainingState:
    def __init__(self,):
        pass

    def _handle_interupt(self):
        sys.exit()

    def __enter__(self) -> None:
        # signal.signal(signal.SIGTERM, self._handle_interupt)  
        print("Enter handler from worker: ", ray.air.session.get_world_rank())

    def __exit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
    ) -> None:
        print("exit handler triggered from worker: ", ray.air.session.get_world_rank())

def _train_dummy() -> None:
    with TrainingState():
        print("Start to train from worker: ", ray.air.session.get_world_rank())
        if ray.air.session.get_world_rank() == 0:
            raise ValueError("this is a test error")
        
        time.sleep(2)


def train_distributed() -> None:
    scaling_config = ray.air.ScalingConfig(
        num_workers=2,
        use_gpu=False,
    )
    run_config = ray.air.RunConfig(
        local_dir="/tmp/ray_results/",
        verbose=0,
    )
    trainer = ray.train.torch.TorchTrainer(
        train_loop_per_worker=_train_dummy,  # noqa
        scaling_config=scaling_config,
        run_config=run_config,
    )
    trainer.fit()

if __name__ == "__main__":
    res = train_distributed()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by gabriel-andersson** [comment]
Any input / updates regarding this?

**Comment by gabriel-andersson** [comment]
Any input / updates on this?

**Comment by anyscalesam** [comment]
Ping @woshiyyya on this cc @matthewdeng

**Comment by woshiyyya** [comment]
@gabriel-andersson Currently Ray Train doesn't support signal handling since the `train_func` is launched as a subthread. We will consider adding support for this feature in the future release.

ref: https://github.com/ray-project/ray/pull/42814#issuecomment-1917652038

**Comment by gabriel-andersson** [comment]
> @gabriel-andersson Currently Ray Train doesn't support signal handling since the `train_func` is launched as a subthread. We will consider adding support for this feature in the future release.

Okay, I see. Do you have any kind of time estimate of when it could be happening?

**Comment by woshiyyya** [comment]
Sorry that we are not planning to add it in the near future. Can you find some workaround for it?

**Comment by woshiyyya** [comment]
Close this issues for now. 

Ray Team is doing inital exploration on architecture revamping. We've put this signal handling as a feature that need to support.
