### ISSUE TITLE
[Serve] Allow configure http_middlewares through Python API

### ISSUE THREAD

**Issue by TracebaK** [ray-project/ray#39051]
### Description

Hi, I’m deploying my model using Ray Serve and I want to rate limit my service. I tried to use rate limit middlewares in FastAPI but it seems it is a "replica" level rate limit, which means when I have more than one replicas for an application, their request throughput are calculated identically. Since I want to have an "serve" level rate limit feature, I think the middleware should run in the HTTPProxyActor and I do find param `http_middlewares` in the source code. However, I didn't find it in the documentation about how to configure this parameter. Since `serve.start()` is already a deprecated API, I'm wondering if you could allow us to pass our middlewares or `http_options` to `serve.run()`. It could be something that lookes like this:

```
def run(
    target: Application,
    _blocking: bool = True,
    host: str = DEFAULT_HTTP_HOST,
    port: int = DEFAULT_HTTP_PORT,
    name: str = SERVE_DEFAULT_APP_NAME,
    route_prefix: str = DEFAULT.VALUE,
    middlewares: List[starlette.middleware.Middleware] = None    # pass my middlewares...
) -> Optional[RayServeSyncHandle]:
    """Run an application and return a handle to its ingress deployment.

    The application is returned by `Deployment.bind()`. Example:

    .. code-block:: python

        handle = serve.run(MyDeployment.bind())
        ray.get(handle.remote())

    Args:
        target:
            A Serve application returned by `Deployment.bind()`.
        host: Host for HTTP servers to listen on. Defaults to
            "127.0.0.1". To expose Serve publicly, you probably want to set
            this to "0.0.0.0".
        port: Port for HTTP server. Defaults to 8000.
        name: Application name. If not provided, this will be the only
            application running on the cluster (it will delete all others).
        route_prefix: Route prefix for HTTP requests. If not provided, it will use
            route_prefix of the ingress deployment. If specified neither as an argument
            nor in the ingress deployment, the route prefix will default to '/'.

    Returns:
        RayServeSyncHandle: A handle that can be used to call the application.
    """
    client = _private_api.serve_start(
        detached=True,
        http_options={"host": host, "port": port, "location": "EveryNode", "middlewares": middlewares},    # ...And put it in the http_options
    )
```

**Comment by GeneDer** [comment]
@TracebaK Just FYI we decided to revive the `serve.start` api https://github.com/ray-project/ray/pull/38362 So feel free to continue use it to start Serve going forward 🙂

Also note, `serve.run` is intended to use to for deploy apps and not to intended to start serve. Proxy related options will likely to be ineffective in a few release on `serve.run`.

**Comment by GeneDer** [comment]
Close staled issue
