### ISSUE TITLE
Release long_running_serve_failure.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#39053]
### What happened + What you expected to happen

Release test long_running_serve_failure.aws failed. Seehttps://buildkite.com/ray-project/release-tests-branch/builds/2093#018a3f69-fd25-4b8a-a467-ccf5b391e018 for more details.

### Versions / Dependencies

Both on master and releases/2.7.0 branch

### Reproduction script

buildkite

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
CI fix PR merged https://github.com/ray-project/ray/pull/39146
