### ISSUE TITLE
[rllib] Add gradient noise scale for debugging

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#3907]
### Describe the problem
It would be great to add https://arxiv.org/pdf/1812.06162.pdf as another debug metric, similar to the explained variance metric. This would help to diagnose issues related to batch size tuning.

cc @michaelzhiluo

**Comment by waldroje** [comment]
Do you anticipate going anywhere with this feature?  I was reading through that paper today, and seems like a useful metric when working across diverse envs. I'd be interested in just the metric itself, rather than any automatic batch size scaling...

**Comment by ericl** [comment]
We never had much luck reproducing the results, even with the "exact" variant of computing gradients one sample at a time... either a bug or some other trouble.
