### ISSUE TITLE
[Core] Runtime env agent is leaked when raylet dies unexpectedly. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39092]
### What happened + What you expected to happen

We introduced the runtime env agent process in Ray 2.7. Looks like the agent is not killed when raylet is killed unexpectedly and leak the processes (which doesn't happen for dashboard agent)

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @scv119 we just discovered this issue, and actually the fix PR is already out.

**Comment by xieus** [comment]
Great. Thanks for taking care of this issue. @rynewang pls link the PR to this issue when ready.
