### ISSUE TITLE
[Core][GCS FT] Two alive head nodes will be present after the original head node recovers from a failure

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#39122]
### What happened + What you expected to happen

KubeRay has several tests for GCS fault tolerance, and I observed that there will be 2 alive head Pods for ~10 seconds in the Ray cluster after the head node recovers from a failure. Therefore, using `ray list nodes` might show more than 1 "ALIVE" head nodes in the cluster temporarily. This may lead to an issue where the Serve controller believes it hasn't been scheduled to the head node, and as a result, it raises an [exception](https://sourcegraph.com/github.com/ray-project/ray@2f12a4b9845244d6043d3615ed4863456dae02a1/-/blob/python/ray/serve/controller.py?L119). To avoid this issue, I added a workaround retry logic in `test_ray_serve_1` to wait until only 1 head node is alive.

<img width="1593" alt="Screen Shot 2023-08-30 at 11 57 17 AM" src="https://github.com/ray-project/ray/assets/20109646/51db48ab-a010-4fee-849b-17f86eed3c4b">

### Versions / Dependencies

2.6.3 & nightly

I believe this is not a new behavior.

### Reproduction script

See https://github.com/ray-project/kuberay/pull/1364 for more details.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by kevin85421** [comment]
cc @iycheng @edoakes

**Comment by rkooo567** [comment]
cc @vitsai has this been fixed?

**Comment by vitsai** [comment]
This one is not a release blocker, right?

**Comment by rkooo567** [comment]
Oh I thought it was fixed by the cluster id thing?
