### ISSUE TITLE
[tune] PBT (Memory Checkpointing) using TF-Saver is broken

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3912]
Another issue on the same topic is that [TensorFlow examples](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_ray_hyperband.py) does not work correctly for any training scheduler which requires checkpointing. The issue is related (as far as my understanding goes) to the fact that after running trainable.restore(...) ray deletes the temporary directory with the TensorFlow checkpoint. The TensorFlow method self.saver.restore(self.sess, path) is just a declaration of restoring process, and it does not restore model in the place where declared. The restoration of the model variables happens when session.run(...) is performed, and this is the moment when variables are loaded from saved checkpoint to the tf.Graph().  Since checkpoint directory is deleted (in trainable.restore(...) ), the actual process fails.

Why ray.tune delete checkpoint directory in trainable.restore(...)?

_Originally posted by @agniszczotka in https://github.com/ray-project/ray/issues/2856#issuecomment-459011993_

**Comment by richardliaw** [comment]
Looks like this is actually still an issue.

**Comment by richardliaw** [comment]
We should have a PBT + TF Saver example that we fix.

**Comment by wzy816** [comment]
+1

**Comment by richardliaw** [comment]
Fixed in #4043.
