### ISSUE TITLE
[core] Fix the LD_PRELOAD

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#39135]
After [this PR ](https://github.com/ray-project/ray/pull/38644)when LD_PRELOAD with tcmalloc, it will crash. This needs to be fixed before 2.7 release.

**Comment by rkooo567** [comment]
what is "this PR"?

**Comment by iycheng** [comment]
@rkooo567  fixed the description (https://github.com/ray-project/ray/pull/38644)
