### ISSUE TITLE
WARNING: Serializing the class <class 'collections.OrderedDict'> failed, so are are falling back to cloudpickle.

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#3914]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Source code / logs

Is there a way to get rid of that warning? Or this warning is okay?  I pass a pytorch state_dict() object to the remote worker. Thanks.

**Comment by robertnishihara** [comment]
I don't see this error. Can you post a code snippet that reproduces the problem? What version of Ray are you using?

**Comment by zhan0903** [comment]
It seems because I store that pytorch model on GPUs(self.cuda()); when I do not use self.cuda(), the warning disappears. So I have to move the model to CPU firstly? Can I store the model on GPUs and operate on GPUs seems faster?

**Comment by robertnishihara** [comment]
Can you try again with the latest wheels (not from PyPI, but from the master), see https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master.

**Comment by zhan0903** [comment]
I tried the latest wheels(0.6.3?) and still got this warning, and got this error "TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. "  Do I have to generate the experiences(use simulator) on CPUs instead of GPUs? It seems I cannot pass the CUDA tensors between works/actors.

**Comment by kiddyboots216** [comment]
@pcmoritz the above thread was due in part to the error you just fixed so maybe we can try and fix this now? Would be good since model state_dicts are OrderedDicts in PyTorch so that's what we're serializing a lot of the time.

**Comment by robertnishihara** [comment]
I think this has been fixed.
