### ISSUE TITLE
raylet crash caused by incorrect protocol version in received messages

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#3915]
Recently we encountered this crash a few times in our testing environments, when raylet receives bad messages with incorrect ray protocol version in its header, from some miscellaneous sources. It looks like some programs are connecting to the port of node manager / object manager in our environment, but it's not fully understood yet what these programs are. 

We added some guards to make sure we only check for this version from valid clients - workers, drivers, object managers, and node managers, and ignore the bad messages from other unknown sources. After these guards are added, we never see such crashes.

Not sure if this issue is particular to our environments, or how common it is.  If it can be useful to others as well, I can send out my fix for this problem and probably submit a PR.  

client_connection.cc:220:]  Check failed: read_version_ == RayConfig::instance().ray_protocol_version()
*** Check failure stack trace: ***
    @           0x6345dd  google::LogMessage::Fail()
    @           0x6371d5  google::LogMessage::SendToLog()
    @           0x6340b9  google::LogMessage::Flush()
    @           0x6342fe  google::LogMessage::~LogMessage()
    @           0x534f10  ray::RayLog::~RayLog()
    @           0x53ded7  ray::ClientConnection<>::ProcessMessageHeader()
    @           0x53b0f7  boost::asio::detail::read_op<>::operator()()
    @           0x53b588  boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @           0x4c98a0  boost::asio::detail::epoll_reactor::descriptor_state::do_complete()
    @           0x4c951f  boost::asio::detail::task_io_service::run()
    @           0x4bf4df  main
    @     0x2ae896b11c05  __libc_start_main
    @           0x4c60e1  (unknown)
    @              (nil)  (unknown)

**Comment by pcmoritz** [comment]
We have also seen this recently, why don't you submit the PR?

**Comment by zhijunfu** [comment]
yes I just saw the discussions in the other thread, will do

**Comment by pcmoritz** [comment]
https://github.com/ray-project/ray/pull/4003
