### ISSUE TITLE
[Core][Streaming Generator] Lineage reconstruction is not working if generator ref is GC'ed. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39151]
### What happened + What you expected to happen

Currently, if the generator ref is GC'ed, all the result report will be ignored. 

This means if the user GC the generator ref after their work is done, and if lineage reconstruction is triggered, the result is ignored, and the ray.get will hang (because the result will never be rewritten).

We can fix this by keep the generator ref alive until the lineage for the task is released. 

### Versions / Dependencies

master

### Reproduction script

See unit tests https://github.com/ray-project/ray/pull/38982

### Issue Severity

None

**Comment by rkooo567** [comment]
This has been worked around

**Comment by rkooo567** [comment]
@raulchen last time, you mentioned this caused the memory leak from data. Does it block ray data GA?

**Comment by raulchen** [comment]
@rkooo567 yes

**Comment by anyscalesam** [comment]
@stephanie-wang is this on track to make branch cut for Ray 2.10?

**Comment by khluu** [comment]
ETA Friday https://anyscaleteam.slack.com/archives/C01DVKB5SHE/p1709166109960119?thread_ts=1709165365.785589&cid=C01DVKB5SHE

**Comment by stephanie-wang** [comment]
Removing as release blocker since it is not a regression for streaming generator. Ray Data has a workaround for now. The problem with the workaround is that for very long Data jobs, the workaround causes a slow memory leak. So we will try to get the fix in for 2.10 but it's not blocking the release.
