### ISSUE TITLE
[core] health check failure on long latency cluster

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#39169]
### What happened + What you expected to happen

In a long latency cluster, for example a cross continent one, we sometimes observe health check failure, although the nodes are actually healthy. This makes the gcs/autoscaler to think it's dead and remove it. We need to understand why this happens and how to be more resilient.

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
I think this is fixed
