### ISSUE TITLE
[RLlib] Issues with RLModules/Learner + evaluation workers and not using KL loss

### ISSUE THREAD

**Issue by edcxan** [ray-project/ray#39174]
### What happened + What you expected to happen

Currently there are several bugs/incomplete code within RL module preventing it from working properly with multi-agent, multi-policy PPO (and possibly other algorithms.) Some of them I have managed to patch and they are:
1. In algorithm.py's add_policy, the learner api block needs to be moved under the evaluation workers block otherwise add_policy will always fail if evaluation workers exist, due to` policy = self.get_policy(policy_id)` in the learner api block conflicting with policy and policy_cls (can only have 1) when adding to evaluation workers.
2. In algorithm.py's remove_policy, we need to add a block to remove modules from the learner group as well:

` if self.config._enable_learner_api:`
`            self.learner_group.remove_module(`
`                module_id=policy_id,`
`            )`

3. In ppo_learner.py's remove_module, the two coeff .pop's can fail if they do not exist, for example if not using entropy coeff scheduler. Should return None if the keys do not exist:

`self.curr_kl_coeffs_per_module.pop(module_id, None)`
 `self.entropy_coeff_schedulers_per_module.pop(module_id, None)`

4. In ppo_torch_learner.py's additional_update_for_module, `assert sampled_kl_values, "Sampled KL values are empty."` needs to be moved under a `if hps.use_kl_loss:` since they will not exist if not using KL loss.

### Versions / Dependencies

ray==2.6.3

### Reproduction script

Using any of the functions described with RL Module

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ArturNiederfahrenhorst** [comment]
Hi @edcxan,
these are all valid points. Getting the RLModules / Learner stack is high priority for the RLlib team.
Can you put up a PR with the items? Ideally, if you have a short script that creates errors _without_ your changes but does not create errors _with_ your changes, that would be great and accelerate the process.
Do you think that would be possible?

Thanks for raising this issue in any case!
