### ISSUE TITLE
Ray doesn't start properly with TLS enabled

### ISSUE THREAD

**Issue by amohar2** [ray-project/ray#39191]
### What happened + What you expected to happen

I want to start Ray with TLS communication enabled. I followed the steps provided in Ray documentation here https://docs.ray.io/en/latest/ray-core/configure.html#tls-authentication however, Ray creates the following error:

$ ray start --head --port 8786
Usage stats collection is disabled.

Local node IP: 101.109.125.116
Traceback (most recent call last):
  File "/scratch/py_3.8.6/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/scripts/scripts.py", line 2422, in main
    return cli()
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 852, in wrapper
    return f(*args, **kwargs)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/scripts/scripts.py", line 737, in start
    node = ray._private.node.Node(
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/node.py", line 287, in __init__
    self.start_head_processes()
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/node.py", line 1121, in start_head_processes
    self._write_cluster_info_to_kv()
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/node.py", line 1070, in _write_cluster_info_to_kv
    ray_usage_lib.put_cluster_metadata(self.get_gcs_client())
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/usage/usage_lib.py", line 521, in put_cluster_metadata
    gcs_client.internal_kv_put(
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/gcs_utils.py", line 198, in wrapper
    return f(self, *args, **kwargs)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/gcs_utils.py", line 317, in internal_kv_put
    reply = self._kv_stub.InternalKVPut(req, timeout=timeout)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:101.109.125.116:8786: Peer name 101.109.125.116 is not in peer certificate"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:101.109.125.116:8786: Peer name 101.109.125.116 is not in peer certificate {grpc_status:14, created_time:"2023-09-01T00:49:46.334785704+00:00"}"
>

After some digging, I realized that during key/certificate generation I have to provide the IP address of my node in X509 Subject Alternative Name of the generated certificate. After this change I can now start Ray, however I realized that Ray starts incompletely without spawning the gcs_server:

$ ray start --head --port 8786
Usage stats collection is disabled.

Local node IP: 101.109.125.116

--------------------
Ray runtime started.
--------------------

Next steps
  To connect to this Ray runtime from another node, run
    ray start --address='101.109.125.116:8786'
  
  Alternatively, use the following Python code:
    import ray
    ray.init(address='auto')
  
  To see the status of the cluster, use
    ray status
  To monitor and debug Ray, view the dashboard at 
    127.0.0.1:8265
  
  If connection fails, check your firewall settings and network configuration.
  
  To terminate the Ray runtime, run
    ray stop

As it can be seen, it seems that Ray started successfully, however, seems that at some point gcs_server process crashes, since "ray status" will show the following after few seconds:

$ ray status
Traceback (most recent call last):
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/ray/_private/gcs_utils.py", line 120, in check_health
    resp = stub.CheckAlive(req, timeout=timeout)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/scratch/py_3.8.6/lib64/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:101.109.125.116:8786: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:101.109.125.116:8786: Failed to connect to remote host: Connection refused {created_time:"2023-09-01T00:58:15.955988226+00:00", grpc_status:14}"
>
Ray cluster is not found at 101.109.125.116:8786

Here is also snippet of gcs_server.err:

E0901 00:56:32.714599637    3179 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:32.813311165    3169 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:32.951246426    3170 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:33.233182211    3171 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:33.675231252    3169 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:34.433248439    3171 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:35.441436367    3182 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:37.276279934    3172 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
[2023-09-01 00:56:37,713 E 3141 3141] (gcs_server) gcs_rpc_client.h:203: Failed to connect to GCS at address 127.0.0.1:8786 within 5 seconds.
E0901 00:56:39.289362790    3182 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:41.423345940    3171 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:43.173352063    3172 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:44.934355020    3758 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:47.063378429    3764 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:49.424345373    3763 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:51.126330552    3170 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:53.263326773    3762 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:55.377321628    3764 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:57.117396650    3757 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:56:59.300343371    3763 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:01.223288256    3757 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:03.412356129    3763 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:05.420348626    3758 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:07.045348175    3764 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:08.843356659    3757 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:10.501414381    3764 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:12.698414227    3763 ssl_transport_security.cc:1910] No match found for server name: 127.0.0.1.
E0901 00:57:14.403701435    3763 ssl_transport_security.cc:1495] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.

### Versions / Dependencies

Ray 2.3.0
grpcio 1.51.3

### Reproduction script

Provided above

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
Are you still seeing this issue? Or did you end up finding the problem?

**Comment by amohar2** [comment]
Sorry yes, I missed part of the instructions on the page. Will close this issue now.

**Comment by rkooo567** [comment]
that's great!
