### ISSUE TITLE
Backend error information should be propagated to RayTaskError

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#3919]
### Describe the problem
If a task fails to be executed (e.g., because it is a task for an actor that is not reconstructable), the backend stores an invalid Arrow object in the object store, which the frontend interprets as a `RayTaskError` exception. There are many possible causes for a task failure in the backend, and we should propagate that information to the application to make debugging easier.

**Comment by stephanie-wang** [comment]
@raulchen, I believe you guys said that you had an internal implementation of this, right? Would you guys be able to open a PR for it? Thanks!

**Comment by raulchen** [comment]
We introduced a `UnreconstructableException` to indicate that an object is lost and cannot be reconstructed. This is done by putting a special string in object's metadata. I think it also makes sense to do the same thing for `TreatTaskAsFailed`, and throw something like `TaskFailureException`.

I'll refine code and open an PR. But I'll be on vocation next week. I'll work on that in the week after next week.

**Comment by stephanie-wang** [comment]
Okay, that would be great, thanks!

Have a good vacation :)
