### ISSUE TITLE
[Core][Perf] microbenchmark single_client_tasks_async regression

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39216]
### What happened + What you expected to happen

```
REGRESSION 9.59%: single_client_tasks_async (THROUGHPUT) regresses from 10940.075908384719 to 9890.90145401096 (9.59%) in 2.7.0/microbenchmark.json

```

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rickyyx** [comment]
This has been hitting [11k -> 9.5k] on the master - more of a variance than regression IMO. 

![image](https://github.com/ray-project/ray/assets/11676094/c930bcb4-f2d4-4133-b699-7c1a57c5c214)

https://b534fd88.us1a.app.preset.io/superset/explore/p/Woy7xr59kq1/

cc @GeneDer @rkooo567

**Comment by rickyyx** [comment]
Close since this is variance.
