### ISSUE TITLE
[AI] [Docs] Ask AI button is malformed

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#39227]
### Description

The `Ask AI` button is malformed on [`master`](https://docs.ray.io/en/master/serve/index.html):

<img width="95" alt="Screen Shot 2023-09-01 at 1 52 59 PM" src="https://github.com/ray-project/ray/assets/92341594/a51076a4-e05a-4de3-bfe3-de496954b678">

For reference, here's what it looks like on [`latest`](https://docs.ray.io/en/latest/serve/index.html#rayserve):

<img width="107" alt="Screen Shot 2023-09-01 at 1 52 21 PM" src="https://github.com/ray-project/ray/assets/92341594/4ad121f8-a795-40bf-b39a-1469390b06ae">

**Comment by anyscalesam** [comment]
this doesn't really fit anywhere; ill fix this as part of ray 2.8 release
