### ISSUE TITLE
[data] datacontext setting does not work for preprocessor

### ISSUE THREAD

**Issue by daikeshi** [ray-project/ray#39237]
### What happened + What you expected to happen

Setting `DataContext.get_current().enable_tensor_extension_casting = False` won't work for BatchMapper preprocessor. This config is not "global". It only works when it's set in the `train_loop_per_worker`  function used by the Trainer. 

### Versions / Dependencies

Ray 2.6.3

### Reproduction script

```python
ctx = DataContext.get_current()
ctx.enable_tensor_extension_casting = False

def pd_batch(df):
    return df

batch_mapper = BatchMapper(pd_batch, batch_format="pandas")

def train_loop_per_worker(config):
   # enable_tensor_extension_casting works here but not outside train_loop_per_worker
   # ctx = DataContext.get_current()
   # ctx.enable_tensor_extension_casting = False
   ...

trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    train_loop_config=...,
    datasets=...,
    preprocessor=batch_mapper,
    scaling_config=...,
    run_config=...,
)
result = trainer.fit()
```

### Issue Severity

None

**Comment by scottjlee** [comment]
It looks like this issue also occurs without the use of preprocessors. Based off the reproducible given above, I further narrowed it down into a runnable example:

```
import ray
from ray.data.context import DataContext
from ray.data.preprocessors import BatchMapper, StandardScaler
from ray.train.torch import TorchTrainer
from ray.air.config import ScalingConfig


ctx = DataContext.get_current()
ctx.enable_tensor_extension_casting = False

def train_loop_per_worker():
    # enable_tensor_extension_casting works here but not outside train_loop_per_worker
    # ctx = DataContext.get_current()
    # ctx.enable_tensor_extension_casting = False
    ctx_worker = DataContext.get_current()
    assert ctx_worker.enable_tensor_extension_casting is False

trainer = TorchTrainer(
    train_loop_per_worker=train_loop_per_worker,
    datasets={"train": ray.data.range(10)},
    scaling_config=ScalingConfig(num_workers=1),
)
result = trainer.fit()
```

**Comment by scottjlee** [comment]
It looks like https://github.com/ray-project/ray/pull/29192 attempts to fix a similar issue and adds a unit test related to this issue. But in https://github.com/ray-project/ray/pull/38640, we remove this test as we deprecate the `preprocessor` arg.

**Comment by scottjlee** [comment]
Thanks for reporting the issue, we debugged the issue and confirmed that the root cause is that only the `DataContext`'s `ExecutionOptions` are being passed to the train workers. We are discussing internally about how to set the full `DataContext` for the streaming executor.
