### ISSUE TITLE
[RLlib] example code `self_play_with_open_spiel.py` doesn't work

### ISSUE THREAD

**Issue by a4rcvv** [ray-project/ray#39254]
### What happened + What you expected to happen

When I run `ray.rllib.examples.self_play_with_open_spiel` (https://github.com/ray-project/ray/blob/master/rllib/examples/self_play_with_open_spiel.py), it throws `NotImplementedError` after the training has finished.

```
  ...
  File ".../site-packages/ray/rllib/core/rl_module/rl_module.py", line 621, in load_state
    raise NotImplementedError
NotImplementedError
```

### Versions / Dependencies

Ray 2.6.3, Python 3.10.12, macOS 13.5.1 (M1 chip)

### Reproduction script

```sh
python -m ray.rllib.examples.self_play_with_open_spiel --stop-iters=1
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Hey @a4rcvv, thanks for raising this! Indeed, we need to test further how the new stack behaves on these more complex multi-agent scenarios. However, this script does work on master and will work properly on Ray 2.7.

Some output from running this on my laptop in the master branch for fw=torch.
```
Trial PPO_open_spiel_env_bbed7_00000 finished iteration 2 at 2023-09-09 09:02:12. Total running time: 29s
╭────────────────────────────────────────────────────────────╮
│ Trial PPO_open_spiel_env_bbed7_00000 result                │
├────────────────────────────────────────────────────────────┤
│ episodes_total                                         366 │
│ num_env_steps_sampled                                 8000 │
│ num_env_steps_trained                                    0 │
│ sampler_results/episode_len_mean                   21.2781 │
│ sampler_results/episode_reward_mean             -0.0925134 │
╰────────────────────────────────────────────────────────────╯

```

One thing, though, it does require you to install `pip install open_spiel`.

**Comment by sven1977** [comment]
Closing this issue now.
