### ISSUE TITLE
[Core][Performance] single_client_tasks_and_get_batch regression

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39259]
### What happened + What you expected to happen

<img width="765" alt="Screenshot 2023-09-05 at 11 06 35 PM" src="https://github.com/ray-project/ray/assets/18510752/d8b76982-7337-45e9-a95b-7726bad3534a">

The test seems to regress lately. We should

1. Find the root cause commit
2. Check if it is included in 2.7. So far, the regression seemed to happen "after branch cut". 

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by vitsai** [comment]
Bisected to: https://github.com/ray-project/ray/pull/38323

Matches attached dashboard for this metric as well. 
<img width="1231" alt="Screenshot 2023-09-06 at 10 36 22 AM" src="https://github.com/ray-project/ray/assets/7005244/47ab09c4-1237-4af6-883e-ccabd4304d33">

**Comment by vitsai** [comment]
Specifically, this regression is explained by the bit of extra overhead in unconditionally executing 
```
    setattr(
        function,
        "__signature__",
        _add_param_to_signature(
            function,
            inspect.Parameter(
                "_ray_trace_ctx", inspect.Parameter.KEYWORD_ONLY, default=None
            ),
        ),
    )
```
during `_inject_tracing_into_function(` when defining a remote function, which had only been executed upon `_is_tracing_enabled()` before this PR. 

Unfortunately, `_is_tracing_enabled()` is not accurate until init is called as it must retrieve the value from the KV store through GCS.

**Comment by edoakes** [comment]
would prefer to avoid purely reverting https://github.com/ray-project/ray/pull/38323 as it's a bugfix we prioritized due to user requests

is there another way to solve the above issue without unconditionally injecting the parameter? one possibility would be to inject the parameter lazily upon first invocation. then we can guarantee it happens post-`ray.init`
