### ISSUE TITLE
[Air] Can XGBoost training support `'objective': 'survival:aft'`? 

### ISSUE THREAD

**Issue by caren-guo** [ray-project/ray#39266]
### Description

The official XGBoost library supports AFT survival analysis: https://xgboost.readthedocs.io/en/stable/tutorials/aft_survival_analysis.html

I wonder if Ray XGBoost can support this as well? Right now using this objective causes
```
xgboost.core.XGBoostError: [17:50:25] ../src/objective/aft_obj.cu:76: Check failed: info.labels_lower_bound_.Size() == ndata (0 vs. 4) :
```

Since we don't have a way to set the lower_bound and higher_bound

```
>>> X = np.array([[1, -1], [-1, 1], [0, 1], [1, 0]])
>>> dtrain = RayDMatrix(X)
>>> y_lower_bound = np.array([      2.0,     3.0,     0.0,     4.0])
>>> y_upper_bound = np.array([      2.0, +np.inf,     4.0,     5.0])
>>> dtrain.set_float_info('label_lower_bound', y_lower_bound)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'RayDMatrix' object has no attribute 'set_float_info'
```

**Comment by anyscalesam** [comment]
@matthewdeng can you take a look and set priority for this one?

**Comment by matthewdeng** [comment]
cc @krfricke

**Comment by caren-guo** [comment]
Actually found a way to do this, sorry about the false alarm!

**Comment by matthewdeng** [comment]
@caren-guo could you share how you ended up solving this? Thanks!
