### ISSUE TITLE
[CI] `linux://python/ray/tests:test_typing` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39305]
....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_typing-END
....

**Comment by rkooo567** [comment]
<img width="1351" alt="Screenshot 2023-09-06 at 7 04 12 PM" src="https://github.com/ray-project/ray/assets/18510752/1ec47f55-98ec-4cdf-9f1e-cde14210ef8c">

**Comment by anyscalesam** [comment]
Overall "flakiness" is yellow; we are going to focus on reds for Linux first.
