### ISSUE TITLE
 OSS CI test_gcs_ha_e2e_2 failing

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39318]
In :python: civ1 tests
https://buildkite.com/ray-project/oss-ci-build-branch/builds/5897#018a691b-187d-4cf3-97fd-ca39286c81f2/4977-5517

**Comment by GeneDer** [comment]
@rynewang Please pass to new oncall or find a new owner if you are no longer oncall

**Comment by rkooo567** [comment]
I think we don't need to handle this. This is a new test, and the flakiness is due to how test is written not the actual bug. We can fix it in ray 2.8

**Comment by GeneDer** [comment]
The thing is it failed 3 times straight in the release branch 😅 If there is no bug and we are not planning to fix it, can we take it out for now?

**Comment by rkooo567** [comment]
we are planning to fix it for 2.8. If you want to take it out for 2.7 branch, we can do that

**Comment by GeneDer** [comment]
yes, please. Just add a `@pytest.mark.skip` should be good

**Comment by GeneDer** [comment]
Cherry-pick PR merged https://github.com/ray-project/ray/pull/39369 and seeing the test passing https://buildkite.com/ray-project/oss-ci-build-branch/builds/5959#018a70c5-ea48-43dd-9ba6-577003aaf822
