### ISSUE TITLE
OSS CI tune_hvd_keras failing

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39317]
In 2/3 🥶 :python: Ray Python 3.7 legacy dependency ML compatibility tests
https://buildkite.com/ray-project/oss-ci-build-branch/builds/5897#018a691b-2578-460a-9d63-23506e65f9a5/5891-6125

**Comment by GeneDer** [comment]
@matthewdeng I know your team is still working to fix it. But just create this issue to track it

**Comment by matthewdeng** [comment]
Ah yes this is fixed in master, I will make a cherry-pick PR for this.

**Comment by GeneDer** [comment]
Cherry pick PR merged https://github.com/ray-project/ray/pull/39368 and seeing the test passing https://buildkite.com/ray-project/oss-ci-build-branch/builds/5959#018a70c5-dcc3-4dea-af9c-c9b3025b1577
