### ISSUE TITLE
[ray tune + ray core]: Cannot schedule X with the placement group because the resource request {'X': 1, 'CPU': 1} cannot fit into any bundles for the placement group, [{'CPU': 1.0}].

### ISSUE THREAD

**Issue by fy222fy** [ray-project/ray#39311]
### What happened + What you expected to happen

I am using ray-tune to tune a project already based on ray-core. That is the 'objective' function contains 'ray.remote'.
However, when I add options with 'resource', the ray tune will return following error:

Cannot schedule ray_func with the placement group because the resource request {'X': 2, 'CPU': 1} cannot fit into any bundles for the placement group, [{'CPU': 1.0}].

I'm not sure if there's a problem with my use.

### Versions / Dependencies

ray == 2.6.3

### Reproduction script

``` python
import ray
from ray import tune


@ray.remote
def ray_func(x):
    return x


def objective(config):
    obj_ref = ray_func.options(resources={"X": 2}).remote(config['b'])
    score = ray.get(obj_ref)
    return {'score': score}


if __name__ == '__main__':
    ray.init(address='local', num_cpus=32, resources={'X': 16}, log_to_driver=True)
    # print(objective({'b':1}))
    search_space = {"b": tune.grid_search([0, 1, 2, 3])}
    tuner = tune.Tuner(objective, param_space=search_space)
    results = tuner.fit()
    print(results.get_best_result(metric="score", mode="max").config)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by xwjiang2010** [comment]
can you take a look at the guide here? https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html

**Comment by fy222fy** [comment]
Thanks a lot! I didn't notice this guide before.
