### ISSUE TITLE
[ml] Update pinned dependencies for Ray 2.7

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#39338]
This issue tracks pinned dependency versions for Ray 2.7.

- [x] Compare the compiled dependencies [here](https://github.com/ray-project/ray/blob/master/python/requirements_compiled.txt) with the previous version tracked [here](https://docs.ray.io/en/master/ray-overview/installation.html#installed-python-dependencies).
- [x] Update dependencies as needed.
    - [x] `pyarrow` has downgraded from 12.0.1 to 6.0.1. This is undesirable and is being investigated in #39290.
- [ ] Publish new versions for 2.7.

**Comment by krfricke** [comment]
We'll publish the new versions after #39452 is merged and the docker images have been built. This is part of the release process.

**Comment by anyscalesam** [comment]
looks like this has been picked successfully by @GeneDer  - @matthewdeng  can we close this out?

**Comment by matthewdeng** [comment]
Going to mark this as resolved as the final step of publishing the versions for 2.7 is tracked in the release process.
