### ISSUE TITLE
Implement GlobalState In Java worker

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#3933]
There is just a `RedisClient` in Java worker currently.
And it's inconvenient for us to work for other features in Java worker like https://github.com/ray-project/ray/pull/3839 and https://github.com/ray-project/ray/pull/3838 right now. 

So It's time to implement `GlobalState` like python worker with following features:
1). Implement redis shards.
2). Implement `GlobalState.lookupTable()` with `get()` because there is no `executeCommand()` in Jedis.
3). Align the APIs with Python as more as possible.

### Usages:
```Java
// public APIs:
GcsClient gcsClient = Ray.getGcsClient();
List<NodeInfo> nodes = gcsClient.getAllNodeInfo();
```

### TODOs:
- [x] redis shards
- [x] GcsClient
- [ ] Align APIs with Python `global_state`

**Comment by robertnishihara** [comment]
@jovany-wang this is a great idea! A couple comments.

1 I'd actually like to rethink the Python global state API, e.g., maybe something like
    - `ray.global_state.task_table()` -> `ray.tasks()`
    - `ray.global_state.object_table()` -> `ray.objects()`
    - `ray.global_state.client_table()` -> `ray.nodes()`
    - and so on...
2. We should see what can be moved into C++ so we can share as much code as possible between Python and Java if this makes sense.

**Comment by jovany-wang** [comment]
@suquark Any idea for moving some thing about `GlobalState` to C++?

**Comment by jovany-wang** [comment]
Since we'd like to avoid exposing `GcsClient` to normal users, this issue could be closed.
