### ISSUE TITLE
[Data] Actor contructor with args

### ISSUE THREAD

**Issue by luke-han** [ray-project/ray#39366]
### Description

Sometimes actor classes' constructor for Ray Data need arguments, but I don't know how to specify the constructor's positional / keyword arguments.

### Use case

Sample code:
```python
class ModelPredictor:
    def __init__(self, model_path: str):
        self.model = load_model(model_path)

    def __call__(self, sample: dict[str, Any]) -> dict[str, Any]:
        pred = self.model.predict(sample['jpg'])
        sample['pred'] = pred
        return sample

pipe = ray.data.read_parquet(...)
pipe.map(ModelPredictor, num_gpus=1, compute=ray.data.ActorPoolStrategy(min_size=1, max_size=2))
     .write_parquet(...)
```

**Comment by luke-han** [comment]
I thought partial function can be an workaround for this like I used for `ray.util.iter.from_iterators`, but `map` treats function parameter as Task.

Sample code for `ray.util.iter.from_iterators`
```python
from functools import partial

import ray
import webdataset as wds


def wds_generator(paths):
    dataset = wds.WebDataset(paths)
    for sample in dataset:
        yield sample

def ray_generator(partitioned_wds_paths):
    generator_funcs = [partial(wds_generator, paths) for paths in partitioned_wds_paths]
    return ray.util.iter.from_iterators(generator_funcs).gather_async()
```

Possible workaround if map takes function as class constructor
```python
pipe.map(partial(ModelPredictor, model_path), num_gpus=1, compute=ray.data.ActorPoolStrategy(min_size=1, max_size=2))
```

**Comment by scottjlee** [comment]
In the `map` function, is the `fn_constructor_args` helpful? In the example use case above, you would be able to pass args to `ModelPredictor` using this parameter.

https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.map.html

**Comment by raulchen** [comment]
Closing this issue as the above suggestion should help. Feel free to reopen if there are other issues.
