### ISSUE TITLE
Ray >=2.8 will not support Python 3.7

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#39395]
### Description

Python 3.7 end-of-life (EOL) is 2023-06-27 and Ray will drop the support with the following plan:

- Ray 2.7 will be the last version that supports Python 3.7.
- Ray 2.8 will no longer have Python 3.7 wheels for installation.

**Comment by jjyao** [comment]
https://github.com/ray-project/ray/issues/38257

**Comment by glennmoy** [comment]
As part of this, are there plans to revert commiting the auto-generated proto files introduced in https://github.com/ray-project/ray/pull/39210

> For now, we check in the auto generated proto source files for python since we need to use an old version of protoc to support python 3.7. Once we deprecate 3.7, we can undo this part.
