### ISSUE TITLE
[Rllib] TorchMultiDistribution to_deterministic function has very slight bug

### ISSUE THREAD

**Issue by Phirefly9** [ray-project/ray#39411]
### What happened + What you expected to happen

The TorchMultiDistribution to_deterministic function has a bug that makes it unusable when setting explore=False, which is the way my team runs evaluations.

https://github.com/ray-project/ray/blob/master/rllib/models/torch/torch_distributions.py line 540
`dist.to_deterministic for dist in self._flat_child_distributions` should be `dist.to_deterministic() for dist in self._flat_child_distributions`  (missing parenthesis on to_deterministic)

this matches the implementation for TorchMultiCategorical seen on line 382

### Versions / Dependencies

This bug seems to be in any version of ray since 2.4
I tested it on 2.6.3

### Reproduction script

I'm not sure a good way to do this as we are currently upgrading our code to 2.6.3, I can look into it if required

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
PR in review. Thanks for raising this issue (and providing the solution!) @Phirefly9 :)

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for raising this!
