### ISSUE TITLE
[core] Async actor logs sometimes missing 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#39410]
### What happened + What you expected to happen

When async actors tasks are run, we have seen race where task log information from the same task were reported even though the actual event loop is running different async actor tasks. 

This has been root caused since async actor tasks's runtime context in CoreWorker was out of sync with the context env of async actor's event loops. 

### Versions / Dependencies

master

### Reproduction script

see test_state_api_log.py::test_task_log

### Issue Severity

None

**Comment by anyscalesam** [comment]
Will re-review after current scope of Ray28 issues.

**Comment by rickyyx** [comment]
https://github.com/ray-project/ray/pull/41563
