### ISSUE TITLE
[Serve] Proxies get stuck in backoff

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#39418]
### What happened + What you expected to happen

@edoakes, @akshay-anyscale, @alexeykudinkin, and I ran a service with 100 worker nodes, 16 CPUs per node, and 1600 no-op replicas (all on worker nodes). We ran a Locust workload with 3500 users that constantly sent synchronous requests. We observed that periodically, one proxy would have all its scheduling tasks enter backoff.

<img width="1342" alt="Screen Shot 2023-09-07 at 4 17 11 PM" src="https://github.com/ray-project/ray/assets/92341594/f4a368e0-72e2-4ce9-bc41-8588d343f9c0">

<img width="1344" alt="Screen Shot 2023-09-07 at 4 17 29 PM" src="https://github.com/ray-project/ray/assets/92341594/e5014dd0-43c5-4c03-806e-51c8a6d6eecd">

During this period (which lasts 3-5 minutes), the proxy wouldn't respond to any requests. Eventually, all the requests are disconnected, and after some time the proxy fails health checks and gets restarted.

**Relevant Links:**
* [Locust file](https://github.com/ray-project/serve_workloads/blob/c4c331f3d2ca5a68499e6398a3bab6e6aebc3f30/microbenchmarks/qps_test_locustfile.py)

### Versions / Dependencies

Ray on the latest `master` with a custom wheel that adds metrics for number of scheduling tasks.

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by edoakes** [comment]
Closed by ^
