### ISSUE TITLE
Accessing Q values of DQN or APEX Agent

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#3942]
Hi,

How can we access the q values for APEX and DQN Agent ? I looked at the code at the but PolicyGraph doesn't exposes the q values. I want to check what are the q values but having hard time in accessing them using Rllib.

**Comment by ericl** [comment]
I've pushed a commit here in this PR that adds it to extra_compute_action_fetches(): https://github.com/ray-project/ray/pull/3941/commits/2bcbb76b26bded25454ac3355bb2fbc455e6b820

The easiest way to access it is probably `agent.get_policy().compute_single_action(obs)`, and it will be returned as part of the extra action fetches.
