### ISSUE TITLE
Ray CPP

### ISSUE THREAD

**Issue by MMorente** [ray-project/ray#39447]
### What happened + What you expected to happen

I am building the ray cpp example with cmake. In order for it to run I need to create a so file and an executable and link the so file to the exe. Why is this needed? The error seems to be that the remote functions are not registered when building only an executable.

I have also tried to create a so with just the remote functions but this also fails.

PS: The includes. flags and linking of libray are properly set up.

### Versions / Dependencies

ray-cpp 2.6.3

### Reproduction script

see ray cpp example source code

### Issue Severity

High: It blocks me from completing my task.

**Comment by larrylian** [comment]
> 1. Why so file is this needed? 
As long as you need to use your functions, the process needs to include the definition of these function.
"example.so" is used for remote method invocation. The worker process will dynamically link "example.so" and execute your own methods. 

> 2. I have also tried to create a so with just the remote functions but this also fails. 
What is the error message?  Do you set `--ray_code_search_path` ?

>  I am building the ray cpp example with cmake.
I recommend using Bazel for building and referring to the configuration in our Bazel project.

**Comment by MMorente** [comment]
The error message is "Executable function not found" when calling the remote function. I copy below an example of decoupling the remote functions.

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)
project(RayTest LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

include_directories(/cluster/MOMA348/ray_issue/include)

find_library(RAY_API
    NAMES ray_api
    HINTS /cluster/MOMA348/ray_issue/lib
)

if(NOT RAY_API)
    message(FATAL_ERROR "Ray API not found")
endif()

add_library( REMOTE_LIB
    remote.h
    remote.cpp
)       
target_link_libraries(REMOTE_LIB ${RAY_API})

add_executable(RayTest main.cpp)
target_link_libraries(RayTest REMOTE_LIB)
``` 
remote.h
```c++
int compute(int i);
``` 
remote.cpp
```c++
#include "remote.h"

int compute(int i){
    return i;
}
``` 
main.cpp
```c++
#include <ray/api.h>
#include <vector>

#include "remote.h"

RAY_REMOTE(compute)

int main(int argc, char** argv){
    ray::RayConfig config;
    config.address = "";

    ray::Init(config);
    std::vector<ray::ObjectRef<int>> results;
    for (int i = 0; i < 10; i++){
        results.push_back(ray::Task(compute).Remote());
    }

    for (auto& res : ray::Get(results)){
        std::cout << *res < std::endl;
    }

    ray::Shutdown();
    return 0;
}
``` 
I have also tried calling RAY_REMOTE(compute) in my RemoteLib library but that doesn't seem to work either. I suppose I am misunderstanding how the remote functions are used.

Sadly, currently, we cannot used bazel in my project and we are stucked with Cmake.

**Comment by ManuelMorente** [comment]
Adding argc and argv to the init method makes that warning go away, but the output is still the same: 

ray::internal::RayFunctionNotFound:  Executable function not found, the function name compute

**Comment by rkooo567** [comment]
cc @larrylian to follow up!

**Comment by larrylian** [comment]
> Adding argc and argv to the init method makes that warning go away, but the output is still the same:
> 
> ray::internal::RayFunctionNotFound: Executable function not found, the function name compute

@MMorente 
1. Can you show your startup command?
2. Do you set the param (--ray_code_search_path=xxxxx/xxx.so ) ?

**Comment by MMorente** [comment]
The startup command is ./RayTest --ray_code_search_path=/abspathtosofile

**Comment by larrylian** [comment]
@MMorente 
Moving `RAY_REMOTE(compute)` from main.cpp to remote.cpp and try again. 
`comupte` function must register in so file by `RAY_REMOTE(compute)`.

**Comment by MMorente** [comment]
@larrylian I have already tried that, I keep getting the same error.

**Comment by MMorente** [comment]
@larrylian Apparently, after starting to load the shared lib it skips it.

```shell
[2023-10-08 19:47:33,221 I 1456 1456] event.cc:234: Set ray event level to warning
[2023-10-08 19:47:33,221 I 1456 1456] event.cc:342: Ray Event initialized for CORE_WORKER
[2023-10-08 19:47:33,222 I 1456 1478] accessor.cc:611: Received notification for node id = 5fb26f369578b441f7866b3343d9ea6757cbd3cebdd4f9c98d792f79, IsAlive = 1
[2023-10-08 19:47:33,222 I 1456 1478] core_worker.cc:4100: Number of alive nodes:1
[2023-10-08 19:47:33,222 I 1456 1456] abstract_ray_runtime.cc:55: Native ray runtime started.
[2023-10-08 19:47:33,222 I 1456 1456] function_helper.cc:156: LD_LIBRARY_PATH: /home/theadmin/.local/lib/python3.8/site-packages/ray/cpp/lib:/home/theadmin/test/build/libREMOTE_LIB.so
[2023-10-08 19:47:33,222 I 1456 1456] function_helper.cc:28: Start loading the library "/home/theadmin/test/build/libREMOTE_LIB.so".
[2023-10-08 19:47:33,224 I 1456 1456] function_helper.cc:72: The library "/home/theadmin/test/build/libREMOTE_LIB.so" isn't integrated with Ray, skip it.

```

**Comment by larrylian** [comment]
@MMorente 

1. Are you sure you moved the code `RAY_REMOTE(compute)` to remote.cpp?
2. Can you show me `ldd libREMOTE_LIB.so`?

**Comment by MMorente** [comment]
@larrylian ldd libREMOTE_LIB.so showed that ray lib was not linked, even though it was linked in the cmake file.

This line in CMakeLists.txt fixes the issue. 
```shell
set(CMAKE_CXX_FLAGS "-Wl,--no-as-needed")
``` 
Now it is able to find the remote functions and everything works.
