### ISSUE TITLE
[CI] `linux://python/ray/tests:test_reference_counting` is failing/flaky on master.

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#39481]
- b13fe598010f64dd4e880d640c86e2aae9a9129a FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6002#018a759a-9eca-470b-9127-8dfc0c0706b5)
- 2de69a571e26e654927fc23659e0a6decf5bd665 FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/628#018a7547-a767-4ede-bdf1-e21bb217c4b6)
- 85186b67b4c45ec8ecb7344e63e28476baf81531 FAILED [Buildkite :redis: (External Redis) (Large)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5947#018a6d61-620f-48fb-b498-21065a06ff32)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_reference_counting-END
....

**Comment by rkooo567** [comment]
<img width="719" alt="Screenshot 2023-09-09 at 2 27 17 PM" src="https://github.com/ray-project/ray/assets/18510752/d856870f-7edf-4ab4-9b19-9172efb75338">
 
seems fixed
