### ISSUE TITLE
Monitor process dumps error messages out into notebooks, even if expected

### ISSUE THREAD

**Issue by ls-daniel** [ray-project/ray#3952]
Dumping what I've been able to figure out about this:

In ray/src/raylet/monitor.cc, the Monitor exists, which periodically checks for client heartbeats. If a client misses a beat, this kicks in:

```
 54         std::string type = "node_removed";                                      
 55         std::ostringstream error_message;                                       
 56         error_message << "The node with client ID " << it->first << " has been marked "
 57                       << "dead because the monitor has missed too many heartbeats "
 58                       << "from it.";                                            
 59         // We use the nil JobID to broadcast the message to all drivers.        
 60         RAY_CHECK_OK(gcs_client_.error_table().PushErrorToDriver(               
 61             JobID::nil(), type, error_message.str(), current_time_ms()));
```

However, the python-based autoscaler terminates nodes during normal operation; that's what autoscaling is. In a jupyter notebook, if nodes are taken down due to idle, the notebook gets spammed with red errors, but they're not really errors.

Unsure about the best way to handle this because presumably this is desired behaviour in the case that a node explodes or something (e.g. AWS spot instance being killed).

Thoughts?

**Comment by robertnishihara** [comment]
@ls-daniel good point, one possibility is to have the autoscaler kill nodes in a more graceful manner (e.g., by sending a notification of some sort to the monitor), although it's nice to be able to use the same code path for everything.

**Comment by richardliaw** [comment]
Closing this bc stale but feel free to open a new issue.
