### ISSUE TITLE
[Tune] Clean up type checks in register_trainable

### ISSUE THREAD

**Issue by gehring** [ray-project/ray#3954]
~It seems like line 36 of tune/registry.py is not doing a proper isinstance check.~

Currently, it checks for `type` instead of what (I am guessing) should be `Trainable`:
```python
if isinstance(trainable, type):
    logger.debug("Detected class for trainable.")
```

EDIT: I got confused by the isinstance check for `type` since this check pass for built-in like `str` and `int`. I now understand the role of those checks. I think those few lines could be clean up to make its purpose clear.

**Comment by gehring** [comment]
@richardliaw I was original confused by these checks and made the error of thinking it was a typo. Sorry for the mix up! Though now that I've already spent some time on what wasn't really an issue, I'm thinking it could still be good to clean up and comment to make the purpose of these checks very clear.

The reason I'm thinking this would be beneficial is that `register_trainable` is likely to be one of the first methods people would look at if they are having trouble satisfying the API's requirements (because of some confusion or another).

I'll fix the pull request but before I do, I'm curious to know if there is a particular reason why callable classes are treated differently than regular functions? Could the checks only verify that a  callable or Trainable subclass was given?

**Comment by richardliaw** [comment]
Yeah; the callables are used for things like `partial_functions` (https://github.com/ray-project/ray/issues/3710) that don't caught as functions are still registered properly. 

The Trainable -> Callable fallback check procedure is probably OK, though I don't actually think it's a necessary change. I think if anything we can just add more comments and not change the existing logic?

`register_trainable` is essentially implicit at this point though, so it's a bit surprising that users would even exposed to this.

**Comment by richardliaw** [comment]
(Closing this with PR)
