### ISSUE TITLE
OSS CI `test_actor_bounded_threads` failure

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#39547]
Fails in multiple places known to be caused by gRPC upgrade
- :redis: (External Redis) (Medium K-Z): https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a813c-8446-4677-afcf-fc68a46fdca0/1782-2769
- 6/6 :windows: Build & Test: https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a813c-4e55-4554-9242-cb954ee51fd7/5597-10431
- :mac: 🍎 Medium K-Z: https://buildkite.com/ray-project/oss-ci-build-branch/builds/6072#018a7d8a-a1b9-4e31-96dd-e9d8791aef13/5059-5788

**Comment by GeneDer** [comment]
CC: @xieus @rkooo567 just in case if Jiajun is OOO, can you find an owner for this?

**Comment by GeneDer** [comment]
@rynewang Not sure if you are working on a fix. Just want to check in, if not, we should probably just add a `@pytest.mark.skip` annotation so at least it will be green for the release

**Comment by jjyao** [comment]
@rynewang lets also skip in the release branch as well.

**Comment by rynewang** [comment]
I will skip it and fix it afterwards.

**Comment by rynewang** [comment]
fixed in https://github.com/ray-project/ray/pull/39608 .
