### ISSUE TITLE
[tune] Simplify FunctionRunner and unify logging behavior with Trainable

### ISSUE THREAD

**Issue by gehring** [ray-project/ray#3956]
### Describe the problem
Currently, the function runner is quite complex for a wrapper and involves hard coded sleeps which can cause results to skipped over when they occur too fast. This issue is meant as a feature request for a simpler function runner with logging following the same behavior as the Trainable class.

### Related issues
#3834

**Comment by gehring** [comment]
@richardliaw I missed the change to [which fields](https://github.com/ray-project/ray/blob/7c3274e65b75d4533b744639e8fb62fb05bf7f75/python/ray/tune/tests/test_trial_runner.py#L114) are checked in the consistency check.

Not a pressing issue but I do think that all the auto-filled results that aren't different by design should be checked, not only the user provided results. The intent would be to test that all logged results (including auto-filled) are invariant to the which API is used, i.e., class API vs function API, excluding fields that are meant to be unique(-ish) to each trial or result, e.g., `PID`, `experiment_id`, `timestamp`.

Things like `timesteps_*`, `episodes_*`, or `training_iteration`, should probably be tested for consistency with regards to when/how they are added and updated across APIs even when not provided by the user. It might be worth re-opening this issue until the checking method is updated. What do you think?

**Comment by richardliaw** [comment]
Yeah that's actually a good point; it should actually be quite an easy fix. Let's reopen this issue for now.

**Comment by richardliaw** [comment]
Fixed in #4421.
