### ISSUE TITLE
[docs] [docs infra] Put in scroll bar for code snippets

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#39611]
### Description

Code example indentation is not great when the width of the code components are not wide enough. We can fix this with a scroll bar. Wrapping of long lines of code are difficult to read.

![image (7)](https://github.com/ray-project/ray/assets/122562471/d7dbe000-20da-4f58-8f8e-909d286caef4)

### Link

For example:
https://docs.ray.io/en/master/train/examples/pytorch/dreambooth_finetuning.html#distributed-training

**Comment by angelinalg** [comment]
Let's figure out what the root case issue is because @peytondmurray found this related PR that deliberately removed the scrollbar: https://github.com/ray-project/ray/pull/24873

**Comment by peytondmurray** [comment]
The scrollbar is enabled by default with the newest version of `pydata-sphinx-theme`, so this is fixed by #41115. Closing as complete.
