### ISSUE TITLE
[serve] Unexpected error in fulfill_pending_requests - Python 3.11 experimental

### ISSUE THREAD

**Issue by wjn0** [ray-project/ray#39642]
### What happened + What you expected to happen

Cut and paste the code from this [example](https://docs.ray.io/en/latest/serve/tutorials/text-classification.html) into `api.py` and then run `serve run api:entrypoint --host 0.0.0.0`. Request `http://localhost:8000/docs`

Expected: request succeeds.

What happened: Error stacktrace:

```
(HTTPProxyActor pid=48335) ERROR 2023-09-13 16:15:10,275 http_proxy REDACTED cflhMmvLLP /docs default router.py:538 - Unexpected error in fulfill_pending_requests.
(HTTPProxyActor pid=48335) Traceback (most recent call last):
(HTTPProxyActor pid=48335)   File "/home/username/.cache/pypoetry/virtualenvs/projectname-M_olJHsL-py3.11/lib/python3.11/site-packages/ray/serve/_private/router.py", line 529, in fulfill_pending_requests
(HTTPProxyActor pid=48335)     async for candidates in self.choose_two_replicas_with_backoff(
(HTTPProxyActor pid=48335)   File "/home/username/.cache/pypoetry/virtualenvs/projectname-M_olJHsL-py3.11/lib/python3.11/site-packages/ray/serve/_private/router.py", line 404, in choose_two_replicas_with_backoff
(HTTPProxyActor pid=48335)     chosen_ids = random.sample(
(HTTPProxyActor pid=48335)                  ^^^^^^^^^^^^^^
(HTTPProxyActor pid=48335)   File "/lmod/packages/python/3.11.3/lib/python3.11/random.py", line 439, in sample
(HTTPProxyActor pid=48335)     raise TypeError("Population must be a sequence.  "
(HTTPProxyActor pid=48335) TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

### Versions / Dependencies

Python 3.11.3, Ray 2.6.3, Linux (Ubuntu)

### Reproduction script

https://docs.ray.io/en/latest/serve/tutorials/text-classification.html

Seems likely due to a behaviour change in `random.sample`:

> Changed in version 3.11: The population must be a sequence. Automatic conversion of sets to lists is no longer supported.

However, the simple fix of replacing `random.sample(x, ...)` with `random.sample(sorted(x), ...)` results in an error on `asyncio.wait`, likely due to this behaviour change:

> Changed in version 3.11: Passing coroutine objects to wait() directly is forbidden.

... so I think maybe `router.py` just needs to be made compatible with Python 3.11 throughout. Duplicate of #38777 but wanted to include additional detail.

Note for other users- Python 3.11 support is experimental, and downgrading seems to make things work fine.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by GeneDer** [comment]
@wjn0 Thanks for reporting it. I think this is already https://github.com/ray-project/ray/pull/37809 Please try again with Ray 2.7.0 or nightly to see it taking affect
