### ISSUE TITLE
[serve] Very high CPU usage for proxying streaming requests

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#39643]
Aviary/Endpoints has a "router" deployment which proxies streaming requests between a downstream model and the HTTP proxy.

This causes the router to become the bottleneck and it is not able to saturate even a single GPU for an LLM inference workload.

Strangely, all of the requests were also flowing through the HTTP proxy but it was not maxing its CPU (was hovering around 40%) and therefore wasn't a bottleneck.

This indicates that it may be related to the generator yielding codepath, as the router deployment's replicas yield results through Ray's generator codepath while the HTTP proxy sends them over the uvicorn `ASGI` interface (which is likely more optimized).

CPU profile of the router deployment replica (was not able to get a native trace):

![endpoints_cpu_profile](https://github.com/ray-project/ray/assets/9871461/38bd58c3-01de-484d-b3a1-5ffd9d21c3fe)

CPU profile of the HTTP proxy (was not able to get a native trace):

![proxy_cpu_profile](https://github.com/ray-project/ray/assets/9871461/166f3a28-2e46-4b9a-b46f-a71dbc4961d0)

**Comment by edoakes** [comment]
Empirically, the router seemed to be able to proxy only about 30 streaming requests/responses before maxing out its CPU. This is much lower than expected; we should be able to handle at least a few hundred concurrent requests (similar to max throughput of a single HTTP proxy).

**Comment by alexeykudinkin** [comment]
@edoakes can you upload the flamegraphs SVGs?

**Comment by edoakes** [comment]
The above are SVGs

**Comment by rkooo567** [comment]
This is a high priority item to fix it in 2.9
