### ISSUE TITLE
[Doc] Fix broken links in Ray docs - turn on nitpicky mode

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#39658]
### Description

Running sphinx with [nitpicky mode enabled](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky) generates warnings about all references that cannot be found. Currently we don't do this, and as a result we are missing broken sphinx references, like these the [two references to private methods in this section](https://docs.ray.io/en/master/serve/model_composition.html#advanced-convert-a-deploymentresponse-to-a-ray-objectref).

I ran `make develop` with nitpicky mode enabled and count 5435 broken references in the documentation. Lots of these will probably be fixable with some tweaks to documentation build parameters, intersphinx mappings, and so on, but I'm starting this issue here to keep track of them. CC @angelinalg 

Here's the full list: [warnings.txt](https://github.com/ray-project/ray/files/12604892/warnings.txt)

Aside from fixing these reference, we should also aim to enable nitpicky mode in the sphinx docs so these don't keep sneaking past CI.

**Comment by matthewdeng** [comment]
Nice! I [tried](https://github.com/ray-project/ray/pull/39448) this last week as well but did not follow up, thanks for creating an issue to track this. 😄

**Comment by peytondmurray** [comment]
Moving on this now. This will be accomplished in a few separate PRs to minimize codeowner impact.

- [ ] Turn on nitpicky mode; set `default_role = 'code'` instead of `py:obj` so that we stop interpreting everything in single backticks as a reference to a python object
- [ ] Fix issues in each library separately
