### ISSUE TITLE
[tune] Open file handles but never close them in Trainable

### ISSUE THREAD

**Issue by timediv** [ray-project/ray#3965]
This file is cluttered with functions opening file handles but never closing them

https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable.py

**Comment by ericl** [comment]
Aren't they closed automatically by python ref counting?

**Comment by timediv** [comment]
They are garbage collected eventually, but it is bad practice and results in a bunch of warnings in my Std error.
https://stackoverflow.com/q/1832528/1116010

**Comment by ericl** [comment]
I see, that makes sense to clean up then.
