### ISSUE TITLE
[Train] 04_finetuning_llama_2_with_deepspeed has some issues with checkpoints 

### ISSUE THREAD

**Issue by kouroshHakha** [ray-project/ray#39671]
### What happened + What you expected to happen

After the recent changes on the checkpointing side, I noticed that the checkpoints produced by template do not behave as if they were fine-tuned. We reproed this by running the template for 1 epoch and the checkpoint_00000 behaves like the base model repeating itself. When I compared the content, the model.safetensors file was missing. Something has gone wrong with the checkpointing with recent changes. 

### Versions / Dependencies

N/A

### Reproduction script

run the workspace and evaluate via Aviary

### Issue Severity

High: It blocks me from completing my task.

**Comment by nidhishs** [comment]
Hi, was this bug fixed? Encountered the same `checkpoint_00000` file instead of a safe tensors file when running the following example: https://docs.ray.io/en/latest/train/examples/deepspeed/gptj_deepspeed_fine_tuning.html
