### ISSUE TITLE
[RLlib] Include `info` into the `_Episode` class 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#39682]
### Description

So far `info` has not been needed by DreamerV3, but to use the `_Episode` also fro other algorithms the `info` should be added to the `_Episode`.

**Comment by sven1977** [comment]
PR in flight by @simonsays1980 👍 https://github.com/ray-project/ray/pull/39732

**Comment by simonsays1980** [comment]
this has been implemented months ago.
