### ISSUE TITLE
Cannot specify dashboard grpc port

### ISSUE THREAD

**Issue by amohar2** [ray-project/ray#39693]
### What happened + What you expected to happen

I am working on a system that have limited number of open ports and before starting Ray, I need to specify all the ports used by Ray. I can fix all the ports either using Ray CLI or using environment variables, except dashboard grpc port, which is currently set to be picked randomly upon dashboard startup. This is defined in ray/dashboard/head.py as follows:
    self.server = aiogrpc.server(options=(("grpc.so_reuseport", 0),))

Is there anyway this can be fixed?

### Versions / Dependencies

ray==2.3.0

### Reproduction script

See issue description

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@scottsun94 @alanwguo where should this go to? Exp team the right landing spot?

**Comment by scottsun94** [comment]
https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1695661285498159
@rynewang and @rkooo567 followed up here

**Comment by scottsun94** [comment]
a p0 issue opened here: https://github.com/ray-project/ray/issues/39866

**Comment by rkooo567** [comment]
Duplicate as https://github.com/ray-project/ray/issues/39866. 

```
    server = aiogrpc.server(options=(("grpc.so_reuseport", 0),))

    grpc_port = ray._private.tls_utils.add_port_to_grpc_server(
        server, f"{grpc_ip}:{grpc_port}"
    )
```
Regarding the server port allocation, we have the next line that allocates the correct port
