### ISSUE TITLE
[Dashboard] should hide internal job created from dashboard

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39696]
### What happened + What you expected to happen

![Screenshot 2023-09-08 at 9 11 19 PM](https://github.com/ray-project/ray/assets/18510752/7a9ac202-1be0-4c83-819b-48e5b7453892)

Looks like the driver created from ray dashboard is displayed to the job page. we should hide it. 

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by scottsun94** [comment]
Is there an ETA for this?

**Comment by scottsun94** [comment]
cc: @rkooo567 @rickyyx

**Comment by rkooo567** [comment]
Working on it. Beg of next Mon is ETA

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/39912 (not ready yet)

**Comment by GeneDer** [comment]
@rickyyx Talked with @rkooo567 that this should be for Ray 2.7.1. But do let us know if it's not happening by Wednesday🙏
