### ISSUE TITLE
[Doc] Search links on `master` docs link to `latest` docs 

### ISSUE THREAD

**Issue by peytondmurray** [ray-project/ray#39702]
### Description

If you search for a term in the left hand searchbar in the `master` docs, results from the `latest` docs come up. If you click on one of the search results, it takes you to the `latest` doc page for that result.

This is frustrating because sometimes things in `master` are not present in `latest`, and vice versa. Maybe others feel differently, but I think if you're in the `master` docs and you do a search, it should contain results only from `master`; basically, `master` and `latest` should be separate search domains.

**Comment by angelinalg** [comment]
Yes, our open source license with Algolia allows a single index and we create it with latest. We don't have plans to upgrade this in the near future.
