### ISSUE TITLE
[Security] Any system or user with access to Ray Dashboard can read all local files 

### ISSUE THREAD

**Issue by DanMcInerney** [ray-project/ray#39701]
### What happened + What you expected to happen

Users with access to the dashboard can read any file on the Ray server through this LFI vulnerability. This was marked informative, was curious about the community's take on it. Informational or valid? https://huntr.mlsecops.com/bounties/5039c045-f986-4cbc-81ac-370fe4b0d3f8/

### Versions / Dependencies

Latest

### Reproduction script

https://huntr.mlsecops.com/bounties/5039c045-f986-4cbc-81ac-370fe4b0d3f8/

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
cc @ijrsvt can you follow it up?

**Comment by anyscalesam** [comment]
@thomasdesr please triage

**Comment by scottsun94** [comment]
@DanMcInerney let us know if you have follow-up questions. Otherwise, we can close it?

**Comment by zhe-thoughts** [comment]
Ray 2.8.1 was released. Please try it out. Thanks for reporting @DanMcInerney and please reopen this issue as you see fit
