### ISSUE TITLE
[<Ray observability>] User feedback on lmproving logging

### ISSUE THREAD

**Issue by Wendi-anyscale** [ray-project/ray#39712]
### Description

Please see user feedback:
_"Improve logging, in general to have an ability to pass custom logger which will be used by every worker, example use case - pass a loguru logger with additional metadata fields and Google cloud logging sink, currently Ray internals like WorkflowManager is not configurable at all, already running task workers have some issues when reconfigured. "

cc. @richardliaw @scottsun94

**Comment by scottsun94** [comment]
Does this https://docs.ray.io/en/latest/ray-observability/user-guides/configure-logging.html#structured-logging meet the requirement? Can you ping the user who gave the feedback? @Wendi-anyscale

**Comment by Wendi-anyscale** [comment]
Sure, I will create a group chat on ray slack

**Comment by rkooo567** [comment]
This should already work with ^

**Comment by jjyao** [comment]
Closing since this is already supported as mentioned above.
