### ISSUE TITLE
[question] D4PG - mujoco implementation

### ISSUE THREAD

**Issue by Scitator** [ray-project/ray#3976]
Hi,

Thanks for your RL framework, looks very promising. Currently I am interested in implementation of current RL algorithms. So, I wonder have you already done any experiments with mujoco environments? If so, are there any experiment configs available? For cheetah or humanoid, for example.

**Comment by ericl** [comment]
There's one for PPO / half cheetah here (tuned for walltime): https://github.com/ray-project/rl-experiments

The tuned_examples dir also has several configs for mujoco / PPO.

None for DDPG though, that's a Todo.

**Comment by richardliaw** [comment]
Closing this for now
