### ISSUE TITLE
[Core] Find gpustats alternative 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39779]
### Description

Seems like the library is not widely used, and we should consider if there's any more popular library used for GPU monitoring.

**Comment by WeichenXu123** [comment]
@rkooo567 

I observed that `pip install "ray[default] == 2.10.0" does not install `gpustat`, does it mean Ray 2.10 doesn't need gpustat library any more ?

Thx

**Comment by rkooo567** [comment]
yeah I believe so. related PR https://github.com/ray-project/ray/commit/9f30c6be040e2c8ba1a8faf8d3925a0801b36f7e
