### ISSUE TITLE
Ray LLM Finetuning

### ISSUE THREAD

**Issue by mayyank-dpa** [ray-project/ray#39848]
### Description

Can you add LoRA-adapted version of this script(https://github.com/ray-project/ray/tree/master/doc/source/templates/04_finetuning_llms_with_deepspeed)? You have used it in one of your blog post (https://www.anyscale.com/blog/fine-tuning-llms-lora-or-full-parameter-an-in-depth-analysis-with-llama-2)

**Comment by kouroshHakha** [comment]
added https://github.com/ray-project/ray/pull/37794
