### ISSUE TITLE
Ray object owner unknown error for max_calls=1 and local_mode=True

### ISSUE THREAD

**Issue by marcm-ml** [ray-project/ray#39853]
### What happened + What you expected to happen

When starting ray.init with `local_mode=True` and calling a remote function with `max_calls=1`, the script exits with error:

```python
ValueError: 
An application is trying to access Ray objects whose owner is unknown(<some-uuid>). 
Please make sure that all Ray objects you are trying to access are part of the current Ray session. 
Note that object IDs generated randomly (ObjectID.from_random()) or out-of-band (ObjectID.from_binary(...)) cannot be passed as a task argument because Ray does not know which task created them. 
If this was not how your object ID was generated, please file an issue at https://github.com/ray-project/ray/issues/
```

When not enabling local_mode, it works fine. The same is true, when setting max_calls to 0. If you set max_calls to some integer x, then the same error occurs after x amount of calls. 

I guess this make sense, as max_calls will terminate the worker after that many function calls. However for local mode, the worker is also the main process and then the cluster is terminated?

My proposal would be to either not have this termination in the local_mode or at least provide some warnings. I know the local_mode is a experimental feature

### Versions / Dependencies

ray==2.3.1

### Reproduction script

```python
import ray


@ray.remote(max_calls=1, max_retries=3, num_cpus=1)
def dummy_task(arg1: str):
    return "hello" + arg1


def main():
    ray.init(include_dashboard=False, local_mode=True)

    ref = dummy_task.remote("world")

    value = ray.get(ref)

    print(value)


if __name__ == "__main__":
    main()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
Local mode has been deprecated since Ray 2.0. https://github.com/ray-project/ray/blob/ad1e06bdbcb901914280dcc4b7400092ccafbdc1/python/ray/_private/worker.py#L1232 We recommend you to use the Ray debugger for a better debugging experience https://docs.ray.io/en/master/ray-observability/user-guides/debug-apps/ray-debugging.html

**Comment by rkooo567** [comment]
Closing the issue cuz we are not maintaining this feature anymore
