### ISSUE TITLE
[Cluster launcher] gcp_cluster_launcher_latest_image failed

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#39883]
### What happened + What you expected to happen

https://buildkite.com/ray-project/release-tests-branch/builds/2188#018ab8bf-5c4c-45fd-a593-ec3ae5b7eda0

### Versions / Dependencies

master

### Reproduction script

run the job

### Issue Severity

None

**Comment by rkooo567** [comment]
cc @rickyyx to find the owner

**Comment by rkooo567** [comment]
cc @rickyyx can we close this?

**Comment by rickyyx** [comment]
Fixed by https://github.com/ray-project/ray/pull/40066
