### ISSUE TITLE
[ci] Ray logs for non linux CI machines

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#39885]
### What happened + What you expected to happen

Currently, we don't have a good way to debug and repro a ci test failure on windows/mac.

Surfacing the ray cluster logs for the specific tests failure is critical for debugging in this case. 

With a given test failure, we should make available the ray logs that are generated by the test failure. (e.g. logs under `ray/<session_for_test_failure>/logs` 

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@rickyyx would the surfacing of this be via our CI pipeline itself (hence why it's assigned to @can-anyscale). Setting it to P2.

**Comment by rickyyx** [comment]
What does P2 mean here?  I believe this is something high value to all OSS devs productivity since the lack of logs on non linux CI basically makes all test failures non-debuggable. Not sure what other issues are being marked  >P2, but this probably is a bit more important than what P2 usually sounds ( not gonna do in the next release IIUC)

> @rickyyx would the surfacing of this be via our CI pipeline itself (hence why it's assigned to @can-anyscale).

Yes, it will be through CI.

**Comment by can-anyscale** [comment]
Yes we aligned this to be P0 for the next sprint. It went into go/okr.

**Comment by can-anyscale** [comment]
This is already done
