### ISSUE TITLE
[Core] Fix building Ray from source code on mac 13.5.2+ and clang 15+

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#39906]
### What happened + What you expected to happen

Building Ray from source code will fail on mac 13.5.2+ and clang 15+. We should fix it.

One issue is https://github.com/redis/redis/issues/12585

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by raulchen** [comment]
Add the following to your `.bazelrc` for a temporary workaround.
```
build --action_env=CPPFLAGS="-Wno-strict-prototypes -Wno-implicit-function-declaration -DMAC_OS_X_VERSION_10_6"
build --copt=-Wno-error=deprecated-builtins --copt=-Wno-error=deprecated-declarations
```

**Comment by GeneDer** [comment]
Just nuked everything and retried with modifying `.bazelrc` in the ray repo. This totally worked! Thanks @raulchen!!
