### ISSUE TITLE
[Core] Incorporate node draining reason to the node death message

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#39904]
### What happened + What you expected to happen

Currently when a node is DEAD due to node draining, we cannot know that from node's death message. We should let people know why a node is dead and if it's due to node draining, what the exact draining reason is.

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by rkooo567** [comment]
1. Add exit code for task/actor/node failure exceptions messages
2. Adding the actual node failure reason to node dead error message.

Scoped to 2.9

**Comment by kevin85421** [comment]
@jjyao Do we need to include this issue in Ray 2.10? If not, I can take the issue.

**Comment by jjyao** [comment]
It's not Ray 2.10.

**Comment by jjyao** [comment]
Fixed by #45320
