### ISSUE TITLE
[Docs] Ask AI button is clipped

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#39911]
### Description

The ask AI button currently looks off. Max mentioned that it probably has something to do with updated css from some plugin.

<img width="74" alt="Screenshot 2023-09-27 at 11 42 45 AM" src="https://github.com/ray-project/ray/assets/122562471/98ef6c88-c77f-42db-9dcf-4437c0e96889">

### Link

https://docs.ray.io/en/latest/

**Comment by angelinalg** [comment]
Looks like the logo is clipped.

**Comment by angelinalg** [comment]
From Emil @ Kapa:

Looks like the default basis.css conflicts based on how Sphinx builds static sites for the figure element.
However adding these two CSS selectors to docs/source/_static/custom.css should fix it:
#kapa-widget-container figure {
  padding: 0 !important;
}

.mantine-Modal-root figure {
  padding: 0 !important;
}
