### ISSUE TITLE
[Core] Incorrect namings in ray.util.accelerators

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#39925]
### What happened + What you expected to happen

Nvidia retired the Tesla brand in May 2020, reportedly because of potential confusion with the [brand of cars](https://en.wikipedia.org/wiki/Tesla,_Inc.).[[1]](https://en.wikipedia.org/wiki/Nvidia_Tesla#cite_note-1) Its new GPUs are branded Nvidia Data Center GPUs,[[2]](https://en.wikipedia.org/wiki/Nvidia_Tesla#cite_note-2) as in the [Ampere](https://en.wikipedia.org/wiki/Ampere_(microarchitecture)) A100 GPU.[[3]](https://en.wikipedia.org/wiki/Nvidia_Tesla#cite_note-3)

but we are naming A100 as `NVIDIA_TESLA_A100`

https://github.com/ray-project/ray/blob/baa861dc5a7967dd903d1b64e88277e3e76d6047/python/ray/util/accelerators/accelerators.py#L6

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

Low: It annoys or frustrates me.

**Comment by anyscalesam** [comment]
Reviewed last week as part of weekly triage of all open issues; will investigate more to decide priority by next Wednesday.

**Comment by jjyao** [comment]
Duplicate of #40767
