### ISSUE TITLE
[Cluster launcher] `botocore` is a dependency that isn't automatically installed by Ray

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#39941]
### What happened + What you expected to happen

Installing the Ray nightly wheel should include all dependencies. However this isn't the case 

```
pip install "ray[default]@https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp39-cp39-macosx_11_0_arm64.whl"
```

```
ray up
```

This leads to a modulenotfounderror for `botocore`. The workaround is to `pip install boto3` but ideally it should be automatically installed.  (A separate issue -- once this is fixed, we should also print a friendly error message if the user forgot to install `ray[default]` and instead just installed `ray`.)

### Versions / Dependencies

Mac M1 python 3.9

### Reproduction script

above

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by architkulkarni** [comment]
cc @hongchaodeng

**Comment by BwL1289** [comment]
@architkulkarni @hongchaodeng not sure this is the place to ask.

We already have `boto3` and `botocore` installed and don't want them to be installed again while launching the cluster. Is there a way to skip installation on cluster launch? 

Also, somewhat related, we get a `.bashrc no file or directory` on launch. Not sure what the cluster is attempting to do with it, but do you know of a way to rectify this as well?

**Comment by BwL1289** [comment]
Nevermind, I figured it out both of the above. My apologies.
