### ISSUE TITLE
[Docker] Issue pulling some docker tags

### ISSUE THREAD

**Issue by colineles** [ray-project/ray#39940]
### What happened + What you expected to happen

Unable to pull some docker images for some versions of ray:

```
=> ERROR [internal] load metadata for docker.io/rayproject/ray-ml:2.5.0.b0924d-py310-gpu                                                                                                                                          1.1s
 => [auth] rayproject/ray-ml:pull token for registry-1.docker.io                                                                                                                                                                   0.0s
------
 > [internal] load metadata for docker.io/rayproject/ray-ml:2.5.0.b0924d-py310-gpu:
------
Dockerfile:1
--------------------
   1 | >>> FROM rayproject/ray-ml:2.5.0.b0924d-py310-gpu
   2 |     # https://github.com/ray-project/ray/blob/master/docker/ray-ml/Dockerfile
   3 |
--------------------
ERROR: failed to solve: rayproject/ray-ml:2.5.0.b0924d-py310-gpu: docker.io/rayproject/ray-ml:2.5.0.b0924d-py310-gpu: not found
```

Other versions seem to work without issue e.g. rayproject/ray:2.7.0.d37759-py310-cu121 

### Versions / Dependencies

rayproject/ray:2.5.0.b0924d-py310-cu118

### Reproduction script

```
docker pull rayproject/ray:2.5.0.b0924d-py310-cu118
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by aslonnie** [comment]
please use release tags, like `rayproject/ray:2.7.0-py310-cu121` or `rayproject/ray-ml:2.5.0-py310-gpu`, without the commit prefix.

ones with commit prefix are temporary and will be cleaned up periodically. docker hub has issues with too many tags in one repo, so we cannot keep them for ever. (and docker hub recently introduced an UI issue where a deleted tag can still be shown in the Web UI..)
