### ISSUE TITLE
[docs][docs infra] confusing side nav behavior

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#39959]
### Description

When I'm in the Ray Train > Ray Train API sub-directory of the LHS nav, and I collapse the Ray Train API level, I expect to stay in the Ray Train level. However, I am popped into the Ray Data level. This is disorienting.
cc: @emmyscode 

https://github.com/ray-project/ray/assets/122562471/d72e4962-8e8f-4927-9dfa-1c6726e50268

**Comment by peytondmurray** [comment]
Fixed by #41115.
