### ISSUE TITLE
Ray Tune and Aim Callback

### ISSUE THREAD

**Issue by jeremyforest** [ray-project/ray#39977]
Error when running Aim callback. Wasn't  expecting a not installed type of error.

Trying out Aim Callback within Ray Tune. Encounter the following error  ```"aim must be installed!. You can install aim with the command: `pip install aim`." ``` . But I previously installed it using poetry so something seemed wrong. 
Digging into the ray and aim code I think what's happening is that the aim api has changed in 4.0. 

Ray import aim in aim.py at line 18 with the following code:
``` 
try:
    from aim._sdk import Repo, Run
```

which should now become:

```
try:
    from aim import Repo, Run
```

The other solution would be to enforce a dependency of aim version <4 .  

Either case, should be an easy fix.

### Versions / Dependencies

Hitting the error with

```
[tool.poetry.dependencies]
python = ">=3.10, <3.11"
sapicore = { git = "https://github.com/cplab/sapicore.git" }
wandb = "^0.15.4"
ray = {extras = ["air", "tune"], version = ">=2.7.0"}
dash = "^2.13.0"
torch = {url = "https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.0.1%2Bcpu.cxx11.abi-cp310-cp310-linux_x86_64.whl"}
dash-bootstrap-components = "^1.5.0"
aim = ">=4"
```

and not with 
```
[tool.poetry.dependencies]
python = ">=3.10, <3.11"
sapicore = { git = "https://github.com/cplab/sapicore.git" }
wandb = "^0.15.4"
ray = {extras = ["air", "tune"], version = ">=2.7.0"}
dash = "^2.13.0"
torch = {url = "https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.0.1%2Bcpu.cxx11.abi-cp310-cp310-linux_x86_64.whl"}
dash-bootstrap-components = "^1.5.0"
aim = ">=3.17.5, <4"
```

### Reproduction script

Using the example script from the doc reproduces the issue when the aim version is 4.0 and solves it with aim 3.17.5 for example

```
import numpy as np

import ray
from ray import train, tune
from ray.tune.logger.aim import AimLoggerCallback




def train_function(config):
    for _ in range(50):
        loss = config["mean"] + config["sd"] * np.random.randn()
        train.report({"loss": loss})


tuner = tune.Tuner(
    train_function,
    run_config=train.RunConfig(
        callbacks=[AimLoggerCallback()],
        storage_path="/tmp/ray_results",
        name="aim_example",
    ),
    param_space={
        "mean": tune.grid_search([1, 2, 3, 4, 5, 6, 7, 8, 9]),
        "sd": tune.uniform(0.1, 0.9),
    },
    tune_config=tune.TuneConfig(
        metric="loss",
        mode="min",
    ),
)
tuner.fit()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Closing this issue as aim 4 was yanked from pypi, feel free to create a new issue if any new issues come up!
