### ISSUE TITLE
[docs][docs infra] landing page video not indexable

### ISSUE THREAD

**Issue by emmyscode** [ray-project/ray#39973]
### Description

This was flagged as an issue with Google Search Console that a video on the Ray landing page is "too tall." This has been detected since Thursday September 14.

This isn't a major problem, since the video is a YouTube video, so if people search for this video, it will be indexed via YouTube and will be discoverable that way. However, if it's a simple fix, then it may be worth just decreasing the height below 1080px.

cc: @angelinalg @sijieamoy 

### Link

The affected site URL: https://docs.ray.io/en/latest/index.html
The affected video: https://www.youtube.com/embed/Iu_F_EzQb5o?modestbranding=1
The support description: https://support.google.com/webmasters/answer/9495631

**Comment by anyscalesam** [comment]
@emmyscode can you please add a priority label and remove triage after having done so. It's assigned to @peytondmurray are y'all aligned on who will take the next step here?

**Comment by emmyscode** [comment]
The only thing I'm able to see on my end from the Google Search Console is whether this is still an issue, how long it's been happening, and roughly what the cause is. If this happens to be a simple fix, then it would be great to have this video be indexable in Google Search. Otherwise, the back-up is that the YouTube video is still indexed if people search for it and the Ray docs landing page will be indexed as a search result, just without the accompanying video in preview.

**Comment by peytondmurray** [comment]
:point_up: @anyscalesam I'm happy to look closer at this one this week. I'll start by checking the commit history for Sept 13-14 to see what changed in the docs, and will report back with my findings.

**Comment by emmyscode** [comment]
The landing page video is already indexed by Google Search Console with YouTube, and the new designs for the landing page omit the video, so let's not fix this.
