### ISSUE TITLE
[SERVE] FastAPI deployment in 3.11 and Ray Experimental is broken

### ISSUE THREAD

**Issue by dioptre** [ray-project/ray#39974]
### What happened + What you expected to happen

I had to downgrade to Python 3.10 to get it to work.

Got coro errors.

### Versions / Dependencies

Try any basic fastapi wrapper deployment per the examples

### Reproduction script

```
from fastapi import FastAPI, APIRouter, status, Request
from ray import serve
from ray.serve.api import build
from starlette.requests import Request
import requests, json


app = FastAPI() 

@app.get("/")
async def read_root():
    return "pong"
    

@serve.deployment
@serve.ingress(app)
class RayWrapper:
  pass



if __name__ == "__main__":
    serve.start(detached=True,http_options={
        "port": 8000
    })
    serve.run(RayWrapper.bind())
    #json_doc = json.dumps({ 'user_input' : 1, 'history' : 2 })
    print(requests.get('http://localhost:8000/'))
```

poetry
```
[tool.poetry]
name = "rayserve"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.11"
ray =  [
  { platform="darwin", extras = ["serve","default"], url = "https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp311-cp311-macosx_11_0_arm64.whl"},
  { platform="linux", extras = ["serve","default"], url = "https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp311-cp311-manylinux2014_x86_64.whl"},
]
fastapi = "^0.103.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by edoakes** [comment]
@dioptre I have added some CI builds that are testing Ray Serve (including FastAPI support) and am not seeing any issues. Could you please try with the nightly builds and let me know if you still see any problems?

https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies

**Comment by edoakes** [comment]
Unable to reproduce and newly-added Python 3.11 tests are consistently passing; please file a new issue with a reproduction if you run into something similar!
