### ISSUE TITLE
[Core] Disallow fractional support for neuron_cores accelerators

### ISSUE THREAD

**Issue by chappidim** [ray-project/ray#39980]
### Problem
Neuron cores by default doesn't allow space sharing. Implies two process cannot use a neuron_core/device in parallel.
Ref: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-runtime/nrt-troubleshoot.html#neuron-core-is-in-use.

Acceptance criteria
* Throw validation exception if user pass fractional values for neuron_core resources
* Unit-tests

**Comment by rkooo567** [comment]
@chappidim we are going to assign it to you. Can you tell us the timeline of the fix?

**Comment by jjyao** [comment]
This is disallowed now.
