### ISSUE TITLE
[Serve]  Serve run raises AssertionError: Module: http does not have ClientBuilder.

### ISSUE THREAD

**Issue by dw011** [ray-project/ray#39988]
### What happened + What you expected to happen

I'm trying to deploy a serve app to a Ray cluster running on a VM on AWS. The [documentation](https://docs.ray.io/en/latest/serve/advanced-guides/deploy-vm.html) currently says to use `serve deploy`, but I've heard that is deprecated in favor of `serve run`. So, here's the procedure I'm using. Please correct me if this is wrong.

1. I port-forward the Ray Dashboard as follows:

```
ray dashboard serve.yml
```

2. In another terminal, I attempt to launch the service on the remote cluster.

```
serve run -a http://localhost:8265 serve.yml
```

I get the following stack trace.

```
Traceback (most recent call last):
  File "/Users/daniel/src/api-venv/bin/serve", line 8, in <module>
    sys.exit(cli())
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/ray/serve/scripts.py", line 479, in run
    ray.init(
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/ray/_private/worker.py", line 1336, in init
    builder = ray.client(address, _deprecation_warn_enabled=False)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/ray/client_builder.py", line 376, in client
    builder = _get_builder_from_address(address)
  File "/Users/daniel/src/api-venv/lib/python3.10/site-packages/ray/client_builder.py", line 344, in _get_builder_from_address
    assert "ClientBuilder" in dir(
AssertionError: Module: http does not have ClientBuilder.
```

I expected this to deploy/start the service on the remote cluster. But maybe I'm not using it correctly?

### Versions / Dependencies

I'm running Python 3.10 and Ray 2.7.0 both locally on macOS and remotely using [rayproject/ray-ml:2.7.0-py310-cpu](https://hub.docker.com/layers/rayproject/ray-ml/2.7.0-py310-cpu/images/sha256-c19bbd35b2793768035c567fe7a477fb785daa9855bb413079287a0ef3cf0b5e?context=explore).

### Reproduction script

I'm just running the CLI as described above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by soloman1124** [comment]
hi, also encounter this issue, and support and suggestion is appreciate thanks!

**Comment by shrekris-anyscale** [comment]
> The [documentation](https://docs.ray.io/en/latest/serve/advanced-guides/deploy-vm.html) currently says to use `serve deploy`, but I've heard that is deprecated in favor of `serve run`

Where did you hear `serve deploy` is deprecated? I'd recommend using `serve deploy` for this case.

**Comment by dw011** [comment]
> > The [documentation](https://docs.ray.io/en/latest/serve/advanced-guides/deploy-vm.html) currently says to use `serve deploy`, but I've heard that is deprecated in favor of `serve run`
> 
> Where did you hear `serve deploy` is deprecated? I'd recommend using `serve deploy` for this case.

Thanks! When troubleshooting I stumbled on a discussion online pointing to [here](https://github.com/ray-project/ray/blob/8d286f03ce39e8856d1ffaa20f377e4bda24dc26/python/ray/serve/deployment.py#L255-L267) and noting the deprecation message. But you're right, yes, `serve deploy` does seem to be the right way to do it. (Sorry for the confusion. I'm brand new to Ray and still trying to get my footing.)

I think this is more of a documentation issue, not a bug in Ray as I originally thought. I was confused about the two "dashboards" in Ray one at port 8265 and the other at port 52365, called the "Dashboard Agent." The exception I hit above is due to connecting to the wrong one.

To illustrate, the following steps attempt to port-forward to the Dashboard (8265) and will raise the exception above. (This was a user error on my part.)

```
ray dashboard cluster_config.yml
serve run -a http://localhost:8265 serve_config.yml
```

But I guess best practice is not to use port-forwarding but to `ssh` to the remote cluster and run `ray deploy` via the remote shell. The follow workflow works for me on AWS EC2.

1. Get a shell on the remote cluster.

```
ray attach cluster_config.yml
```

2. From the remote shell, deploy.

```
serve deploy serve_config.yml
```

It might be good to mention this in the [docs](https://docs.ray.io/en/latest/serve/advanced-guides/deploy-vm.html), which currently don't specify how to access the remote cluster. But that's another issue. There doesn't seem to be a bug here, so I'm gonna close it.

**Comment by shrekris-anyscale** [comment]
> Thanks! When troubleshooting I stumbled on a discussion online pointing to [here](https://github.com/ray-project/ray/blob/8d286f03ce39e8856d1ffaa20f377e4bda24dc26/python/ray/serve/deployment.py#L255-L267) and noting the deprecation message. But you're right, yes, serve deploy does seem to be the right way to do it. (Sorry for the confusion. I'm brand new to Ray and still trying to get my footing.)

Ah got it, thanks for elaborating! No worries at all about the confusion btw– that just means we can do a better job with our docs 🙂

> serve run -a http://localhost:8265 serve_config.yml

`serve run` uses Ray client to connect to the Ray cluster. The Ray client address format is `ray://[hostname]:[head node port]`. By default, the head node port is `10001`. For your example, the address would likely be `ray://[public ip address of EC2 instance]:10001`. See [this docs section](https://docs.ray.io/en/releases-2.7.1/serve/advanced-guides/dev-workflow.html#testing-on-a-remote-cluster) for more info.

Note that the EC2 instance should already have a Ray cluster running, so it can respond to the `serve run` command.

> But I guess best practice is not to use port-forwarding but to ssh to the remote cluster and run ray deploy via the remote shell. The follow workflow works for me on AWS EC2.

You should be able to run `serve deploy` without attaching to the remote cluster using `ray attach`. `serve deploy`'s `--address` option takes an address to the remote cluster's dashboard agent. Setting that address should let `serve deploy` submit the config file to the remote cluster. If that doesn't work, then there's probably a bug.

By the way, starting in Ray 2.8 the Serve REST API will also be accessible through the dashboard port (8265). That means `serve deploy` will work with port `8265` as you tried.
