### ISSUE TITLE
[tune] Hyperband terminates after just one iteration.

### ISSUE THREAD

**Issue by Spandan-Madan** [ray-project/ray#3999]
Hey!

This is a question to make sure that I am using hyperband with tune right. I am using it to optimize hyperparameters for my semantic segmentation pipeline. I adapted the mnist_pytorch.py tutorial for my use case.

It simply states 8 configurations in the beginning, and goes through all of them. There's no second iteration. This confuses me as I think there should be successive halving where it suggests new configurations based on the first calculated 8 configurations. Or am I wrong?

**Comment by richardliaw** [comment]
Oh; for Asynchronous Hyperband, the scheduler doesn't create new configurations based on the first; the successive halving happens on the fly; where you may start with 10 trials, and a third of the trials are terminated (or not, depending on how aggressive you set your early stopping).

Does that make sense? Let me know if it's confusing.

**Comment by Spandan-Madan** [comment]
Makes sense! So technically, it seems like only one iteration but it's not. Once the program ends and lists the results of all the "TERMINATED" configurations it's basically found the best of them. Right?

**Comment by richardliaw** [comment]
Yeah; it is finished with its evaluation at that point.
