### ISSUE TITLE
Release test rllib_learning_tests_bc_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40007]
Release test **rllib_learning_tests_bc_torch.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2208#018aef76-ec25-4c10-81de-484fd11bc3b9 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
PR with a fix in review.

**Comment by sven1977** [comment]
Both BC tests now passed:
https://buildkite.com/ray-project/release-tests-pr/builds/55914#018b3cdb-56ba-40a8-97ee-4e7779173050

Merged PR into master. Should be good now.

@can-anyscale , could we unjail the release test? Thanks! :)

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2268#018b3efb-1340-4c3d-bea0-45d7bd92362f

**Comment by can-anyscale** [comment]
@sven1977 hi yess, let's close this and check the result tonight

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release-tests-branch/builds/2269#018b41cb-4154-45ec-bd57-bc64e6778778
