### ISSUE TITLE
[Tune/Air] Setting a custom storage_path in air.RunConfig creates duplicates in default and specified storage directory

### ISSUE THREAD

**Issue by oliversefrin** [ray-project/ray#40009]
### What happened + What you expected to happen

**1. the bug:**
I'm running a RLlib reinforcement learning algorithm using ray.tune with a user-specified `storage_path` and `name` in the air.RunConfig, as shown in the minimal example. 
Instead of having the results in `storage_path/name`, another results directory gets created in `~/ray_results/name`. The latter directory also gets updated with TensorBoard results during the training run. Only at the end of training, the TensorBoard file (as well as the checkpoint directory) appear in the correct directory.

**2. expected behavior:**
the results are only supposed to be created in the specified storage path.

### Versions / Dependencies

Ray: 2.7.0
Python: 3.9.18
OS: Ubuntu 22.04.02

### Reproduction script

```
from ray import air, tune
from ray.rllib.algorithms.ppo import PPOConfig


algo_config = PPOConfig().environment("CartPole-v1").framework("torch")

tuner = tune.Tuner(
    "PPO",
    param_space=algo_config.to_dict(),
    run_config=air.RunConfig(
        name="run_01",
        storage_path="~/ray_results/CartPole-v1",
        stop={"episode_reward_mean": 475},

    ),
)

tuner.fit()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by grizzlybearg** [comment]
I noticed this too. It forces me to allocate double the space required

**Comment by anhnami** [comment]
Had the same issue.

**Comment by fardinabbasi** [comment]
> ### What happened + What you expected to happen
> **1. the bug:** I'm running a RLlib reinforcement learning algorithm using ray.tune with a user-specified `storage_path` and `name` in the air.RunConfig, as shown in the minimal example. Instead of having the results in `storage_path/name`, another results directory gets created in `~/ray_results/name`. The latter directory also gets updated with TensorBoard results during the training run. Only at the end of training, the TensorBoard file (as well as the checkpoint directory) appear in the correct directory.
> 
> **2. expected behavior:** the results are only supposed to be created in the specified storage path.
> 
> ### Versions / Dependencies
> Ray: 2.7.0 Python: 3.9.18 OS: Ubuntu 22.04.02
> 
> ### Reproduction script
> ```
> from ray import air, tune
> from ray.rllib.algorithms.ppo import PPOConfig
> 
> 
> algo_config = PPOConfig().environment("CartPole-v1").framework("torch")
> 
> tuner = tune.Tuner(
>     "PPO",
>     param_space=algo_config.to_dict(),
>     run_config=air.RunConfig(
>         name="run_01",
>         storage_path="~/ray_results/CartPole-v1",
>         stop={"episode_reward_mean": 475},
> 
>     ),
> )
> 
> tuner.fit()
> ```
> 
> ### Issue Severity
> Low: It annoys or frustrates me.

Same issue!

**Comment by dihaitz04** [comment]
Maybe this workaround by setting the os.environ["TUNE_RESULT_DIR"]=storage_path helps you!
https://discuss.ray.io/t/tune-results-saved-in-ray-results-in-addition-to-local-storage-dir-if-tune-result-dir-not-set/12421

**Comment by terryzhao127** [comment]
Same issue on using Ray train
