### ISSUE TITLE
[data] Enforce hard limit on block sizes

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#40026]
While after https://github.com/ray-project/ray/issues/39647 we'll have warnings about large block sizes, there are still some circumstances in which we can exceed the block size. Exceeding the target block size causes spilling and other scheduling issues.

This happens in the following known situations:
- datasource reads, if the reader is returning batches larger than the block size already (and there isn't any SplitBlocks call)
- map_batches UDFs, if the UDF returns a batch larger the target block size

And the following unavoidable situations:
- whenever a single row exceeds the target block size

We should extend #39647 to add hard asserts once the avoidable situations are fixed (i.e., raise an AssertionError whenever a multi-row block significantly exceeds the target map or shuffle block size, because this indicates a bug).

cc @c21 @raulchen @stephanie-wang

**Comment by anyscalesam** [comment]
@stephanie-wang can we close?
