### ISSUE TITLE
[CI] `osx://python/ray/tests:test_shuffle` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40024]
- 16b65c3fe40d591e02790635857382e91f12833b FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6268#018af152-245e-499f-b6e5-9fd22c62684b)
- 59c36be8b49a5e939e34177375dad68e400af8b3 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6238#018adca3-4904-4a4d-94f4-a03ee45c9fcf)
- da44df1cac8f9d5ad79c50796e1bf7526e2c7482 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6237#018adc9f-6ac3-420e-a2b9-3c8e7601ca70)
- 94ed6f99a33efe22d4c6086685054ab7c344d5bb FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6224#018ad849-4267-4624-b277-f96713c6d544)
- ca96a1e17b6444ba53c9500a8b0ba2fa654b9152 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6206#018ad2a6-1da2-4a6e-a65b-1e8ad60936bb)
- c87fef352f197ed226f0fa48a1ecb6d1de9dcc65 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6192#018ace02-2f3b-48d6-87c4-5d56698b8d6c)
- 7fb768c778f58f475e8782103123b2746bdd5392 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6170#018ab915-b71b-4b27-91dc-07cee08aeea5)
- df8dd535e897fdbdc0083f77f9abc01fe6248f84 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6168#018ab8f3-1986-47f3-89ec-a491df029481)
- 1fbb1439508f70cc69c3e47d72b210f13087ab82 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6167#018ab8af-b67a-47b3-88f9-c9df8ba48647)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_shuffle-END
....

**Comment by rickyyx** [comment]
Looks no longer the case.
