### ISSUE TITLE
[CI] `osx://python/ray/tests:test_actor_resources` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40023]
- 52a9a6c773650ba11801f6f5592d6348141e3882 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6269#018af157-c707-48c8-bd7e-a6ab00230f5d)
- 6f99b2cd5e54b9eabe6d338af165ec400f31f5e2 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6249#018ade6b-fcdd-4226-ac81-9d2640d86386)
- 33cb47b316b450724a459d5f7a36c3711e345e60 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6195#018ace1a-682c-430e-969e-890aa72e183c)
- 1bf3e9f3b12176c5536e322fbdd7febd52770518 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6184#018abec5-b56b-42e6-a769-fff4db34b5ca)
- 35a54d852ad7005d52d61308c7a39c1e8c3fe905 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6173#018ab997-6bad-41d8-bfbd-da6032e80918)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_actor_resources-END
....

**Comment by jjyao** [comment]
It's green now.
