### ISSUE TITLE
[autoscaler] File mounts rsync should allow options/filters

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4004]
Autoscaler currently transfers files between nodes using rsync. It would be nice if I could specify rsync options through autoscaler config. For example, I would like to ignore all the files in a .gitignore, which I believe in rsync could be achieved with `rsync --filter="dir-merge,- .gitignore"`. Maybe add a new field `file_mounts_command` or `file_mounts_options` to autoscaler config?

**Comment by richardliaw** [comment]
hmm, what about like `rsync_options` or something?

**Comment by hartikainen** [comment]
That sounds good to me, although it might be a bit confusing for people who don't know that file mounts are handled by rsync.

**Comment by stevenlin1111** [comment]
Would it also be possible to provide an option for executing the file mounting (`mkdir` and `rsync`) commands with `sudo`?

**Comment by preeth1** [comment]
Is there currently any workaround for this?

**Comment by richardliaw** [comment]
This should be fixed via #11512 !
