### ISSUE TITLE
[train] HuggingFace transformers `RayTrainReportCallback` saves contents under a nested `checkpoint` folder

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#40082]
The default HF transformers integration is the `RayTrainReportCallback` which reports a Train checkpoint for the user. The basic problem is that when I use this callback:

```python
result = trainer.fit()

with result.checkpoint.as_directory() as checkpoint_dir:
    AutoModel.from_pretrained(checkpoint_dir)  # this does not work
    AutoModel.from_pretrained(os.path.join(checkpoint_dir, "checkpoint"))  # this works, but is not obvious / undocumented
```

We don't show how to use this checkpoint in many places. The only place that I could find was this advanced example: https://docs.ray.io/en/latest/train/examples/deepspeed/gptj_deepspeed_fine_tuning.html#generate-text-from-prompt

We don't explain that you need to load the checkpoint from a subdirectory ("/checkpoint", rather than just the download dir):

```python
model = GPTJForCausalLM.from_pretrained("/mnt/local_storage/checkpoint")
```

We also possibly copy the checkpoint unnecessarily: should we instead save it the way we show it in this docs example? https://docs.ray.io/en/latest/train/user-guides/checkpoints.html#saving-checkpoints-during-training

cc: @woshiyyya

**Comment by anyscalesam** [comment]
@woshiyyya which ray release do we want to target this doc update for?

**Comment by woshiyyya** [comment]
Got it, I think we should update the documentation in 2.8
