### ISSUE TITLE
[core] flakey tests

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40152]
### What happened + What you expected to happen

Please help review and reduce the list of core + serverless flaky tests
- https://github.com/ray-project/ray/blob/master/ci/ray_ci/core.tests.yml
- https://github.com/ray-project/ray/blob/master/ci/ray_ci/serverless.tests.yml

### Versions / Dependencies

master

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
We have no capacity now to handle this as 2.8 P0. We have several tasks to unflake flaky linux tests scoped for Ray 2.8. For the rest of them, we may need to handle it from Ray 2.9. cc @xieus

**Comment by rkooo567** [comment]
we are in progress with this, and have separate issues to track it
