### ISSUE TITLE
[rllib] AsyncGradientsOptimizer keeps only one remote worker's "stats" (bug?)

### ISSUE THREAD

**Issue by dpad** [ray-project/ray#4017]
I am not sure if this is intentional or if I am misunderstanding the way things should work in RLLib, but I noticed that a step in AsyncGradientsOptimizer appears to keep only the last set of "stats" information it sees from its remote workers. See `ray/rllib/optimizers/async_gradients_optimizer.py`:

```python
    ...
        while pending_gradients:
                ...  # gets future for a remote evaluator calling compute_gradients(sample())
                gradient, info = ray.get(future)
                e = pending_gradients.pop(future)

                if "stats" in info:
                    self.learner_stats = info["stats"]  # <-- only keeps the last seen info["stats"]

            if gradient is not None:
                with self.apply_timer:
                    self.local_evaluator.apply_gradients(gradient)
        ...

    def stats(self):
        return dict(
            PolicyOptimizer.stats(self), **{
                ...
                "learner": self.learner_stats,  # <-- only outputs one single set of info["stats"]
            })
```

I have implemented an algorithm that utilises N remote_evaluators and outputs some custom statistics for each (e.g. a "loss" function of the computed gradient). However, if I understand correctly, using this optimizer means that only one (potentially random) of remote workers has its "loss" reported on each optimizer step.

Of course I could implement my own optimizer or monkey-patch this, but I imagine instead there should be some sort of flexibility in defining how stats are aggregated or otherwise reported. Perhaps some kind of callback function for merging stats (e.g. maybe as a user I want to average some stats across the remote evaluators) or some overrideable methods (so I don't have to re-write the entire optimizer step)?

**Comment by ericl** [comment]
Auto-closing stale issue.
