### ISSUE TITLE
[Core] Ray workers are not killed by SIGTERM

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40182]
### What happened + What you expected to happen

It looks like Ray workers are not killed by SIGTERM. We have several code that uses SIGTERM to terminate worker processes, and this means that those workers are always ungracefully terminated, which means it will not run critical destructor (it is important for ML workloads). I.e., cleaning up child processes.

### Versions / Dependencies

master

### Reproduction script

send sigterm to a ray worker and see what happens. 

### Issue Severity

None

**Comment by rkooo567** [comment]
the original issue due to this issue; https://github.com/ray-project/ray/issues/40189

**Comment by YQ-Wang** [comment]
Just want to add my observation. When I run a ray job in the ray cluster, the driver code in the ray head is not able to catch the exception after I terminate the worker node ungracefully.

**Comment by rkooo567** [comment]
Hmm I think it may take some time until it can detect ungraceful failures. For example, detecting a ungraceful node failure would take 30 seconds ~ 1 minute.

**Comment by YQ-Wang** [comment]
> Hmm I think it may take some time until it can detect ungraceful failures. For example, detecting a ungraceful node failure would take 30 seconds ~ 1 minute.

Yeah, it cannot detect the ungraceful failure like forever. It always stuck in running status even though the worker node is down.

**Comment by rkooo567** [comment]
Hmm intersting. That seems an orthogonal issue from this particular issue (probably related to keepalive). Is it possible to create a new issue with a reproducible script?
