### ISSUE TITLE
[Rllib] Can't Restore Self-Play Checkpoints (or Checkpoints with many legacy policy Ids) with Ray Tune

### ISSUE THREAD

**Issue by heng2j** [ray-project/ray#40183]
### What happened + What you expected to happen

Hello Ray RLlib Team,

We've recently concluded our [4-week Deep RL Bootcamp](https://github.com/stresearch/STR_DeepRL) and have been using Ray RLlib (2.5.1) as our primary training framework. The bootcamp wrapped up with a 1v1 competition, where each cohort member trained an agent with customized algorithm configurations, observation & action spaces, and reward structures to their needs. We've designed our environment to support heterogeneous agent configurations and architectures. We also utilizing Self-Play as our primary training scheme. Our [self-play training callback](https://github.com/stresearch/STR_DeepRL/blob/hw3/multigrid/utils/training_utilis.py#L427-L506) drew inspiration from the [official RLlib Self-play example (Ray 2.3.1)](https://github.com/ray-project/ray/blob/ray-2.3.1/rllib/examples/self_play_with_open_spiel.py).

However, we encountered an issue during the development of our evaluation script. While restoring checkpoints trained with Self-play, to ensure the complete restoration of the algorithm and facilitate two heterogeneous agents within the same environment, we had to use the [`Tune.trainable.restore()`](https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable/trainable.py#L890-L894) method. Initial attempts to [simply restore policy from a checkpoint and set policy weights](https://github.com/stresearch/STR_DeepRL/blob/998cd0306fc5888df413553603d036724028cc17/multigrid/scripts/visualize.py#L224-L244) were insufficient, as it did not restore the heterogeneous agent to its fully trained state.

Furthermore, the this implementation of using [`Tune.trainable.restore()`](https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable/trainable.py#L890-L894) doesn't allow us to specify a `policy_id`, even though the subsequent [`Algorithm._checkpoint_info_to_algorithm_state()`](https://github.com/ray-project/ray/blob/master/rllib/algorithms/algorithm.py#L2638-L2648) method that being used in `restore()` does. This posed a challenge as our cohort members had to include all legacy policies in the final evaluation (~300MB per checkpoint), even when only the main policy was required. Excluding these legacy policies caused the workflow to break due to missing policy_ids.

While we understand our Self-play checkpoint restoration use-case might be an edge case, and [`Tune.trainable.restore()`](https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable/trainable.py#L890-L894) might cater more to generic scenarios, we believe it's important to share this with you.

As we look towards future Deep RL classes and aim to upgrade and use the new RL Modules, we're interested in building an agent pool with diverse agents for a variety of collaborative and competitive tasks. 

Going forward for future Cohorts we are planning to upgrade our codebase to use RL Module and more. Therefore, we would like to find a better solution for our use case, as we are trying to create an agent pool with heterogeneous agents to perform a variety of collaborative and competitive tasks. Could you provide guidance on the best way to restore agent states in a shared environment?

We're eager to collaborate on a solution and are more than willing to make contributions back to the community through Pull Requests or other means.

Thank you for your attention and support!

### Versions / Dependencies

Ray 2.5.1
Python 3.10
MacOS & Ubuntu 22.04

### Reproduction script

We provided an pertained checkpoint [here](https://github.com/stresearch/STR_DeepRL/tree/hw3/submission/pretrained_checkpoints/DTDE_1v1), and you can use the following VSCode Launch command to run the evaluation in debug mode.

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
     
        {
            "name": "Visualize Trained Agent - DTDE-1v1",
            "type": "python",
            "request": "launch",
            "program": "multigrid/scripts/visualize.py",
            "args": ["--env", "MultiGrid-CompetativeRedBlueDoor-v3-DTDE-1v1-Death_Match", "--num-episodes", "10",
                    "--load-dir","/Users/zla0368/Documents/RL/RL_Class/code/test_hw/week-3-intro-to-marl-heng4str/submission/ray_results/Self_Play_Testing/PPO_MultiGrid-CompetativeRedBlueDoor-v3-DTDE-1v1-Death_Match_d909d_00000_0_2023-09-26_22-23-30/checkpoint_000050" ,
                    "--render-mode", "human",
                    "--gif", "DTDE-1v1-red_blue_eval_50_testing",
                    "--policies-to-eval", "red_0", "blue_0",
                    "--eval-config", "{\"team_policies_mapping\": {\"red_0\" : \"your_policy_name\"  }}"
            ],
            "justMyCode": false
        },
       
    ]
}






```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Hey @heng2j , if you "only" want to run your restored Algorithm inside an evaluation environment loop using only certain policies, you should probably checkout this API here and use the entire Algorithm checkpoint for that:

```
# search for your checkpoint (sub)directory, in which exists a file `algorithm_state.pkl`.
# This one is the "main" checkpoint dir that we will use in the below code

checkpoint_dir = [see comments above]

from ray.rllib.algorithms.algorithm import Algorithm

algo = Algorithm.from_checkpoint(checkpoint_dir, policy_ids=[list of policy IDs you would like to recover; all other policies will NOT be included in the restored algorithm])

# Compute actions for individual policies.
action = algo.compute_single_action([obs], [state]?, policy_id=[the policy ID you would like to use])
```

**Comment by sven1977** [comment]
It's great to hear that your organization/company is moving towards RLlib. We are actively working on finalizing the "new API stack" and it will be infinitely simpler and more transparent to use and get started with than the "old API stack" (which you are using right now).

**Comment by heng2j** [comment]
Thank you @sven1977 for the pointer! This is very helpful! We will update our codebase with the `Algorithm.from_checkpoin()`. And we will keep a eyes on the updated documentations / examples on the "new API stack"!  

Thank you and the Team for keep making RLlib better and more user friendly for the RL community!
