### ISSUE TITLE
[Ray Data] Ordering fails on first call to iter_rows 

### ISSUE THREAD

**Issue by keerthanvasist** [ray-project/ray#40216]
### What happened + What you expected to happen

Does Ray guarantee ordering of rows? Which operations don't guarantee ordering?

When I first start a python session, and run this, it fails.
```
import ray
nums = []
for row in ray.data.range(1000).iter_rows():
    nums.append(row['id'])    
new_nums = list(nums)
assert sorted(nums) == new_nums
But, if I first start session, and run this, it doesn't fail.
```
Subsequent runs of the same is successful. 

However, when I first start a python
```
import ray
nums = []
data = ray.data.range(1000).materialize()
for row in data.iter_rows():
    nums.append(row['id'])    
new_nums = list(nums)
assert sorted(nums) == new_nums
```
`materialize()` seems to have this effect.

### Versions / Dependencies

Python 3.10.13
Ray 2.6.3

### Reproduction script

Reproducible script is provided above.

### Issue Severity

High: It blocks me from completing my task.

**Comment by keerthanvasist** [comment]
@raulchen Can you please take a look?

**Comment by itsparth** [comment]
Preserving order is not guaranteed in ray streaming by default, you can use the following to preserve ordering.
ctx = ray.data.DataContext.get_current()
ctx.execution_options.preserve_order = True

**Comment by keerthanvasist** [comment]
Is there a performance impact of this?
