### ISSUE TITLE
[ci][clusters] Cluster launcher tests failing to retrieve ssh keys 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#40228]
### What happened + What you expected to happen

We are seeing test failures for all cluster launcher tests (where it fails to download ssh keys). 

### Versions / Dependencies

https://buildkite.com/ray-project/release-tests-branch/builds/2239#018b0442-c1d4-4de6-88a0-627a1ec6d3e0

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/2239#018b0442-c1d4-4de6-88a0-627a1ec6d3e0

### Issue Severity

None

**Comment by rickyyx** [comment]
Assigning to @can-anyscale as of now since this looks like a test infra issue.

**Comment by rickyyx** [comment]
Looks like the role configs are not setup properly - @gvspraveen is this something you could hep triage and take a look for the clsuter launchers failures?

**Comment by architkulkarni** [comment]
Cluster launcher seems to be passing https://buildkite.com/ray-project/release-tests-branch/builds/2356, it may have been a transient issue 

We can reopen if this crops up again.
