### ISSUE TITLE
[Data] Issue with backpressure when used with python generators 

### ISSUE THREAD

**Issue by itsparth** [ray-project/ray#40287]
### What happened + What you expected to happen

When using Ray(streaming) with python generators for a dataset, the backpressure is not handled properly, and objects are spilled to disk causing slowdown. Below is an example function which is passed into flat_map to generate more than one row for each input rows.
```python
def read_video(batch: Dict) -> Generator[Dict, None, None]:
    while True:
        # Yield very large objects
        yield {"frames": np.zeros((1080, 1920, 3), dtype=np.uint8)}
```

The expectation was the ray would only fetch a value from generator based on the available object store memory instead of spilling to disk.

Reference slack discussion: https://ray-distributed.slack.com/archives/C02PHB3SQHH/p1695967735631919

P.S. I cannot use read_binary in my case to read videos due to complex read requirements.

### Versions / Dependencies

Ray: 2.7
Python: 3.8.10
OS: Windows 10 with WSL (Ubuntu 18.04)

### Reproduction script

Please see the attached colab example
https://colab.research.google.com/drive/1BlEu_xmtqSgjHTKsNavSOsCKZ8CGwEv6?usp=sharing#scrollTo=oua-xSKBB4PY

Or use the following code
```python
from typing import Dict, Generator
import ray
import numpy as np
import ray.data
import time

ray.init()
ray.data.DataContext.get_current().execution_options.verbose_progress = True

def read_video(batch: Dict) -> Generator[Dict, None, None]:
    while True:
        # Yield very large objects
        yield {"frames": np.zeros((1080, 1920, 3), dtype=np.uint8)}


def process(batch: Dict) -> Dict:
    # Dummy processing
    time.sleep(5)
    return batch

def clear(batch: Dict) -> Dict:
    # Clear out all in-memory data, only keep output shapes
    return {"shapes": [output.shape for output in batch["frames"]]}


ds = (
    ray.data.from_items(["test.mp4"], parallelism=1)
    .flat_map(read_video, num_cpus=0.5)
    .map_batches(process, zero_copy_batch=True, batch_size=10)
    .map_batches(clear)
    .show(1000)
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by raulchen** [comment]
This is a known issue and [being worked on](https://github.com/ray-project/ray/pull/40387).  It's planed to be experimental in 2.8, and official in 2.9.
