### ISSUE TITLE
Stdout/stderr from all drivers are streamed to all other drivers.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4029]
As of https://github.com/ray-project/ray/pull/3892, the stdout/stderr of all drivers is streamed to all other drivers. An individual driver can opt out by calling `ray.init(..., log_to_driver=False)`.

To reproduce this, do the following.

1. Start Ray.

    ```
    ray start --head --redis-port=6379
    ```

2. Start a driver that prints stuff.

    ```python
    import ray
    import sys
    import time
 
   ray.init(redis_address='localhost:6379')

    @ray.remote
    def f():
        while True:
            print('hi')
            sys.stdout.flush()
            time.sleep(0.1)

    f.remote()
    ```

3. Start another driver, and see that it receives the stdout from the first driver.

    ```python
    import ray

    ray.init(redis_address='localhost:6379')
    ```

### Some options to address this.

1. Workers can belong to specific drivers (this means logs will be complicated for cross driver applications, e.g., named actors).
2. Workers can redirect there stdout/stderr on a per-task basis.
3. Workers can print extra annotations in their stdout/stderr which the log monitor can parse and use to choose which drivers to publish to.

**Comment by virtualluke** [comment]
I like option 3.  

For option 2 what kind of api were you thinking about?  Like an additional keyword in ray.remote decoration?

I am already making use of this feature a little and find it handy to include timestamp and function name to each stdout.  Not saying these should be added by default but giving that as an example.

**Comment by robertnishihara** [comment]
Option 2 would not require the user to do anything. Instead, there would one log file per worker/driver combination, and whenever a worker executes a task for a given driver, it logs to the file for that worker/driver combination. This would all be done under the hood.

**Comment by virtualluke** [comment]
2 or 3 sound fine to me then.  I am not doing cross driver work yet so that isn't an issue for me.

**Comment by AdamGleave** [comment]
If this isn't going to be fixed soon, can we at least document it somewhere prominently? This was very confusing to me for a while: now I know what's causing it, it's largely a non-issue, as I can look at output from my other logging methods.

**Comment by robertnishihara** [comment]
Thanks @AdamGleave for bringing this up. I'll take a look at fixing it this week.

**Comment by ericl** [comment]
@edoakes @simon-mo isn't this kind of a deal breaker for serve?

**Comment by simon-mo** [comment]
In deployment, Serve's drivers are short-running script so this doesn't matter too much. However, I agree P1 is the correct priority

**Comment by ericl** [comment]
@ijrsvt I'm stealing this issue for now, you don't need to worry about it.

**Comment by ijrsvt** [comment]
Thanks Eric!

**Comment by SnowWalkerJ** [comment]
Is this problem solved? I am still getting output from all drivers at version 0.8.6

**Comment by simon-mo** [comment]
This should solved. If you still see all logs then it's a bug. Can you post a new issue with a reproducible example? Thanks!
