### ISSUE TITLE
[Data] Add `include_paths` option to `read_json`

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#40307]
### Description

Some `read_xxx` APIs like `read_binary_files` expose a `include_paths` option. 

https://github.com/ray-project/ray/blob/2dc51f0ce19f6700ebdf08b65379c1bcc29a4d3c/python/ray/data/read_api.py#L1633-L1637

However, other APIs like `read_json` don't have this option.

https://github.com/ray-project/ray/blob/2dc51f0ce19f6700ebdf08b65379c1bcc29a4d3c/python/ray/data/read_api.py#L1018-L1033

For consistency, we should add it to all file-related read APIs.

**Comment by krishkhimasia** [comment]
I would like to work on this issue, can this please be assigned to me?

**Comment by Dv04** [comment]
Hello, if this issue still needs solving, I would like to work on this.

**Comment by anyscalesam** [comment]
@Dv04 for sure - can you pick up from the PR that @hartikainen had started? @c21 has left some comments to correct the implementation/approach.
