### ISSUE TITLE
Ray Cluster

### ISSUE THREAD

**Issue by MMorente** [ray-project/ray#40314]
### What happened + What you expected to happen

I have setup a ray cluster using kuberay operator for my Google Cloud environment. The issue is that I need to manually add a Windows machine to the ray cluster, I have already setup the required env var in windows and I can connect from the windows machine to the ray cluster deployed with kuberay. The problem is that after 1 minute the node corresponding to the windows machine dies, the logs only say that it got a timeout. During that minute the node is alive, I have checked the status of every node in the cluster.

### Versions / Dependencies

Ray 2.7.1/Python 3.8.13

### Reproduction script

-

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@gvspraveen can you please review and triage?

**Comment by mattip** [comment]
Can you give a more complete reproducer? How do you start the cluster and what do you run on the windows machine? Can the windows machine execute any ray remote code during the minute it is working?

**Comment by mattip** [comment]
Can you add a non-windows machine to the cluster or does it also die after a minute?

**Comment by MMorente** [comment]
> Can you add a non-windows machine to the cluster or does it also die after a minute?

Hello there. The problem was that I needed to add a new Firewall rule opening the ports. Now the node doesn't die and everything works. 

I still think it's quite weird that it was able to make a connection for 1 minute, from my point of view it shouldn't have been able to connect at all.

**Comment by mattip** [comment]
> I needed to add a new Firewall rule opening the ports

Might be worth adding a note to the documentation somewhere about this. I have seen the firewall pop-ups when starting `ray init` the first time.

> it was able to make a connection for 1 minute

I may not have actually connected, that may have been a time out while it tried unsuccessfully to connect.

**Comment by mattip** [comment]
@MMorente  Thanks for following up
