### ISSUE TITLE
[docs] Examples Gallery doesn't have edit button

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#40319]
### Description

Could we put back the edit button on the Examples Gallery page? A button to do a quick edit should be available on all docs pages.
cc: @simran-2797 

### Link

https://docs.ray.io/en/latest/ray-overview/examples.html

**Comment by peytondmurray** [comment]
![image](https://github.com/ray-project/ray/assets/14017872/fc890cb0-78a1-4d25-ab87-c4a76e3684bd)

Fixed by #41115.
