### ISSUE TITLE
Better worker pool strategy

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#4033]
1) Avoid creating too many workers than necessary.
    Currently, raylet will start num-of-cpus workers at startup. But this number could sometimes be much larger than necessary (assuming an app that only use actors, not normal tasks), so many workers would end up being idle forever.

2) Garbage-collecting unused workers. 
   Sometimes an app could submit a large number of tasks all at once, and raylet would start the same number of workers to execute them. But after that, the workers will never be cleaned up. We should consider killing idle workers periodically to save resources.

See #3882 for related discussions.

**Comment by robertnishihara** [comment]
Relevant discussion in #3882.

**Comment by richardliaw** [comment]
Think this is fixed.
