### ISSUE TITLE
weights does not updated through policy.set_weights(theta) 

### ISSUE THREAD

**Issue by stellaxu** [ray-project/ray#4034]
In ES policies.rollout function, if I change the weights to theta inside policies.rollout by calling "policies.set_weights(theta)", why does the value of weights not change at all (when I call policies.get_weights()?"

If I want to change the weight value to theta inside the policies.rollout function, how to realize it?

Thanks a lot.

**Comment by ericl** [comment]
I think that should work. Is it possible something is setting weights again before you call get_weights()?

**Comment by stellaxu** [comment]
> I think that should work. Is it possible something is setting weights again before you call get_weights()?

in do_rollouts function of ES, the policy.set_weights(params+perturbation) works, and it sets the weight value of the network before calling policies.rollout().
in policies.rollout() function, if I want to modify the weight value, I call policy.set_weights(theta) and it does not work.  I think the reason may not be setting weights again before call get_weights since each worker works independently, and I have tried a lot of different values of theta, the policy.get_weights() is still the value of params+perturbation assigned to the worker instead of theta.

it's a little bit strange

**Comment by pedropla** [comment]
I've had a somewhat similar issue with set_weights. I've inherited from the PPOPolicyGraph and then in my subclass I've had the __init__() call self.set_weights() after calling the super init. The weights for that graph get set correctly (as verified by prints), but once I call the main agent.get_policy().get_weights() the weights are no longer the ones assigned in the policy graph init. I'm guessing they are being overwritten somewhere but I haven't found where.

**Comment by pengzhenghao** [comment]
I think I found the reason. The agent holds many workers in its `trainer.workers`, which is a container `workerset` which contains one local worker and many remote workers.

So when you do `policy.set_weight`, or `agent.get_policy().get_weights / set_weights`, you are actually operating on the policy staying at local worker, leaving the policies staying at remote workers unchanged.

So to set or get weights for all policies, you need to:

```python
        # function to call for each worker (including remote and local workers)
        def init_worker(worker):
            # function for each policy within one worker.
            def _init_policy(policy, _):
                policy.get_weight() # or set_weight(weight)
            worker.foreach_policy(_init_policy)

        trainer.workers.foreach_worker(init_worker)
```

**Comment by richardliaw** [comment]
Closing because stale; feel free to reopen.
