### ISSUE TITLE
[Tune] CLIReporter fails to report memory usage.

### ISSUE THREAD

**Issue by max0x7ba** [ray-project/ray#40355]
### What happened + What you expected to happen

After updating from ray-tune-1.13.0 to ray-tune-2.6.3, `CLIReporter` no longer reports memory usage.

ray-tune-1.13.0 output:
```
== Status ==
Current time: 2023-08-12 01:57:43 (running for 00:00:05.01)
Memory usage on this node: 2.1/39.2 GiB
Using MedianStoppingRule: num_stopped=0.
Resources requested: 2.0/32 CPUs, 0/0 GPUs, 0.0/34.37 GiB heap, 0.0/0.07 GiB objects
Result logdir: /home/max/ray_results/...
Number of trials: 1/4 (1 RUNNING)
```

ray-tune-2.6.3 expected output from https://docs.ray.io/en/releases-2.6.3/tune/api/reporters.html
```
== Status ==
Memory usage on this node: 11.4/16.0 GiB
Using FIFO scheduling algorithm.
Resources requested: 4/12 CPUs, 0/0 GPUs, 0.0/3.17 GiB heap, 0.0/1.07 GiB objects
Result logdir: /Users/foo/ray_results/myexp
Number of trials: 4 (4 RUNNING)
```

ray-tune-2.6.3 actual output lacks the line with `Memory usage on this node:`:
```
== Status ==
Current time: 2023-10-15 22:11:40 (running for 00:00:30.39)
Using MedianStoppingRule: num_stopped=0.
Logical resource usage: 4.0/4 CPUs, 0/0 GPUs (0.0/1.0 accelerator_type:G)
Result logdir: /home/max/ray_results/...
Number of trials: 3/4 (1 PENDING, 2 RUNNING)
```

I have used memory usage report for automated capacity planning. `CLIReporter` failing to report memory usage broke my automation.

How do I get `Memory usage on this node:` line back, please?

### Versions / Dependencies

ray-tune-2.6.3

### Reproduction script

TBD

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Hi could you share more about how you use this?

cc @scottsun94 do you remember whether this was intentionally removed with the new console output?

**Comment by scottsun94** [comment]
> Hi could you share more about how you use this?
> 
> cc @scottsun94 do you remember whether this was intentionally removed with the new console output?

I think this was intentional because based on our experience, people didn't often use logical memory resources for scheduling, especially for train and tune users.

However, @max0x7ba it seems that you are using logical memory resources for scheduling. Can you elaborate on "I have used memory usage report for automated capacity planning"?

**Comment by max0x7ba** [comment]
I use these log lines to get maximum RAM utilization on the worker nodes to allocate sufficient amount of RAM for Google Compute Engine instances:

```
gawk -F': |/' '/^Memory usage on this node/ { if(m<$2) m=$2 } END { if(m>0) printf "ray.tune memory usage maximum was %.1f GiB.\n", m }'
```

I can see that `JupyterNotebookReporter` still reports RAM usage, but `CLIReporter` no longer does.

**Comment by max0x7ba** [comment]
I managed to work-around the issue and restore the lost memory usage log line with a `CLIReporter`-derived class:

```
import ray.tune
from psutil import virtual_memory

_GB_MULT = 1024 ** -3

class CLIReporter2(ray.tune.CLIReporter):
    def __init__(self, *a0, **a1):
        os.environ["RAY_AIR_NEW_OUTPUT"] = "0"
        super().__init__(*a0, **a1)

    def report(self, trials, done, *sys_info):
        vm = virtual_memory()
        total_gb = vm.total * _GB_MULT
        used_gb = (vm.total - vm.available) * _GB_MULT
        memory_usage_msg = f"Memory usage on this node: {used_gb:.1f}/{total_gb:.1f} GiB."
        return super().report(trials, done, *sys_info, memory_usage_msg)
```

Output:

```
== Status ==
Current time: 2023-10-16 02:43:26 (running for 00:03:01.77)
Using MedianStoppingRule: num_stopped=0.
Logical resource usage: 2.0/32 CPUs, 0/0 GPUs (0.0/1.0 accelerator_type:G)
Memory usage on this node: 33.5/125.7 GiB.
Current best trial: b6b3a1c9 with ...
Result logdir: /home/max/ray_results/...
Number of trials: 4/4 (4 TERMINATED)
```

I get good mileage out of these status log lines in Google Compute Engine.

**Comment by scottsun94** [comment]
By logical resources, I was referring to Ray's resource concept: https://docs.ray.io/en/latest/ray-core/scheduling/resources.html, which is different from the physical hardware usage.

BTW. In your workaround, it only reports the memory usage on the head node (where the ray driver/script runs). How do you use it for capacity planning? What actions will you take base don it?

**Comment by max0x7ba** [comment]
I run Ray Tune in single-node mode, where the head and worker are the same host.

**Comment by matthewdeng** [comment]
Ah thanks for clarifying this is potentially helpful for the single node case, but has caused confusion for users in the past for multi-node, where they were not sure where this was being calculated. 

My recommendation would be similar to what you've done, which is to implement and control this behavior separately. Another more programatic way to do this is by just defining a callback, which can handle this logic independent of the console output.
