### ISSUE TITLE
Broken "Read the docs" link on Ray marketing site

### ISSUE THREAD

**Issue by cmdecker95** [ray-project/ray#40398]
### Description

Hey there! Loving Ray, but as I was perusing the marking site `ray.io`, I noticed that the "Read the docs" call-to-action button (see screenshot) has a broken link.

Specifically, the button on `ray.io/ray-sgd` wants to navigate to exactly this url:
```
https://www.ray.io/docs.ray.io/en/latest/train/train.html
```
I'm positive you mean for the `href` to be:
```
https://docs.ray.io/en/latest/train/train.html
```

I would've fixed it myself, but I couldn't find the repo for your marketing site anywhere on your GitHub (which is fine). Anyway, hope this helps get you more conversions! Have a good one.

<img width="731" alt="Screenshot 2023-10-16 at 10 08 08 PM" src="https://github.com/ray-project/ray/assets/50999401/5ee46624-d4ea-4e46-ab56-9d1d9260960a">

### Link

Problem found here: https://www.ray.io/ray-sgd
Bad URL (current): https://www.ray.io/docs.ray.io/en/latest/train/train.html
Good URL (recommended): https://docs.ray.io/en/latest/train/train.html

**Comment by anyscalesam** [comment]
thanks for raising this - will fix

**Comment by anyscalesam** [comment]
this is fixed - try now. closing.
