### ISSUE TITLE
Able to pass size=0 in ActorPoolStrategy

### ISSUE THREAD

**Issue by malhotra18** [ray-project/ray#40393]
Incorrect sequence of conditions identified in `compute.py`

```
        if size:
            if size < 1:
                raise ValueError("size must be >= 1", size)
            if max_size is not None or min_size is not None:
                raise ValueError(
                    "min_size and max_size cannot be set at the same time as `size`"
                )
            min_size = size
            max_size = size
```

when `size=0` is passed `ValueError` won't get raised as uber level condition expression will be false.

**Comment by anyscalesam** [comment]
@malhotra18 good catch - can you raise a PR for this?

**Comment by xingyu-long** [comment]
Hi @anyscalesam, I've raise the PR (https://github.com/ray-project/ray/pull/47072) to fix this issue, could you take a look? thanks!
