### ISSUE TITLE
[RLlib] Saving an environment independent rllib checkpoint isn't possible anymore

### ISSUE THREAD

**Issue by karstenddwx** [ray-project/ray#40397]
### What happened + What you expected to happen

Saving an environment independent rllib checkpoint isn't possible anymore. The learning environment implementation used for training isn't necessarily available on deployment environment, why restoring/unpickling a checkpoint w/o the need of the learning environment makes sense.
With previous versions a checkpoint could be restored w/o the dependence of the learning environment implementation, setting "env=None" in the algorithm config.

### Versions / Dependencies

ray 2.6
python 3.10
ubuntu 22.04

### Reproduction script

`alg_class = get_trainable_cls("DQN")`
`config['env'] = None`
`config.pop('env_config')`
`algorithm = alg_class(config=config)`
`algorithm.restore(checkpoint_path)`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by sven1977** [comment]
Hey @karstenddwx , thanks for raising this issue. I don't actually think that this would have ever worked, not providing an env, b/c of the need for RLlib to know about the spaces for creating the policy/ies in your algorithm.

The code below does work fine. Could you confirm that doing this would help you with the problem?

```
from ray.rllib.algorithms.ppo import PPOConfig
import gymnasium as gym


env = gym.make("CartPole-v1")

config = (
    PPOConfig()
    .environment("CartPole-v1")
)
algo = config.build()
algo.train()
dir = algo.save()
algo.stop()

# "Fix" config: Remove Env, BUT provide spaces information manually, such that RLlib can create the policies correctly.
config.environment(
    None,
    observation_space=env.observation_space,
    action_space=env.action_space,
).rollouts(num_rollout_workers=0)
algo2 = config.build()
algo2.restore(dir)

# print some actions
print(algo2.compute_single_action(env.reset()[0]))  # [0] -> env.reset returns obs and infos
print(algo2.compute_single_action(env.reset()[0]))
print(algo2.compute_single_action(env.reset()[0]))
```

**Comment by karstenddwx** [comment]
Hi Sven, thanks for looking into this.
I can confirm that not providing an env has still worked with ray 2.5.1, but not with 2.6.

I have to do some refactoring to be able to run it the AIR 2.x way (build/train/save). I'll let you know whether it works as you suggested.
