### ISSUE TITLE
Issue on page /train/examples/lightning/dolly_lightning_fsdp_finetuning.html

### ISSUE THREAD

**Issue by hengqujushi** [ray-project/ray#40401]
I got an error when I run the notebook. Key error message is below: 

"ValueError: You selected an invalid strategy name: `strategy=<ray.train.lightning._lightning_utils.RayFSDPStrategy object at 0x7f05009c5a90>`. It must be either a string or an instance of `lightning.pytorch.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai"

**Comment by justinvyu** [comment]
This should be resolved in 2.8+ by https://github.com/ray-project/ray/pull/39841.

Feel free to re-open if you're still seeing this issue.
