### ISSUE TITLE
[tune] Checkpoint is not saved in certain scenarios

### ISSUE THREAD

**Issue by xdever** [ray-project/ray#4041]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.3
- **Python version**: 3.7.2
- **Exact command to reproduce**:
Run the script below.

### Describe the problem
I found this problem while using population based training for hyperparameter tuning, but it might be relevant for other cases too. The problem becomes apparent when setting the checkpoint_freq of the Experiment and the perturbation_interval of the PopulationBasedTraining to the same value in a resource-constrained environment: no checkpoint will be ever saved.

On timesteps when the hyperparameters are perturbed, because of resource limits the training is paused, checkpoint will never be saved. The source code responsible for this is in trial_runner.py, line 401, the TrialScheduler.PAUSE branch. The piece of relevant code is below:

```python
if decision == TrialScheduler.CONTINUE:
    self._checkpoint_trial_if_needed(trial)
    self.trial_executor.continue_training(trial)
elif decision == TrialScheduler.PAUSE:
    self.trial_executor.pause_trial(trial)
elif decision == TrialScheduler.STOP:
    # Checkpoint before ending the trial
    # if checkpoint_at_end experiment option is set to True
    self._checkpoint_trial_if_needed(trial)
    self.trial_executor.export_trial_if_needed(trial)
    self.trial_executor.stop_trial(trial)
```
In a resource-constrained environment the PopulationBasedTraining usually decides to pause the training, which causes the checkpoint not to be saved.

### How to reproduce
The example below is based on https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/pbt_example.py
Added checkpoint_freq, modified perturbation_interval, and added resources_per_trial to limit the number of running processes and force scheduler to pause, like in real, GPU-constrained scenario.

If you check the resulting directory structure, no checkpoints will be present. If you change the perturbation_interval to 2, every second checkpoint will be saved (note that checkpoint_freq is still 1 in this case).

```python
#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import json
import os
import random
import time
import multiprocessing

import ray
from ray.tune import Trainable, run_experiments
from ray.tune.schedulers import PopulationBasedTraining


class MyTrainableClass(Trainable):
    """Fake agent whose learning rate is determined by dummy factors."""

    def _setup(self, config):
        self.timestep = 0
        self.current_value = 0.0

    def _train(self):
        time.sleep(0.1)

        # Reward increase is parabolic as a function of factor_2, with a
        # maxima around factor_1=10.0.
        self.current_value += max(
            0.0, random.gauss(5.0 - (self.config["factor_1"] - 10.0)**2, 2.0))

        # Flat increase by factor_2
        self.current_value += random.gauss(self.config["factor_2"], 1.0)

        # Here we use `episode_reward_mean`, but you can also report other
        # objectives such as loss or accuracy.
        return {"episode_reward_mean": self.current_value}

    def _save(self, checkpoint_dir):
        path = os.path.join(checkpoint_dir, "checkpoint")
        with open(path, "w") as f:
            f.write(
                json.dumps({
                    "timestep": self.timestep,
                    "value": self.current_value
                }))
        return path

    def _restore(self, checkpoint_path):
        with open(checkpoint_path) as f:
            data = json.loads(f.read())
            self.timestep = data["timestep"]
            self.current_value = data["value"]

    def reset_config(self, new_config):
        self.config = new_config
        return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    args, _ = parser.parse_known_args()
    if args.smoke_test:
        ray.init(num_cpus=4)  # force pausing to happen for test
    else:
        ray.init()

    pbt = PopulationBasedTraining(
        time_attr="training_iteration",
        reward_attr="episode_reward_mean",
        perturbation_interval=1,
        hyperparam_mutations={
            # Allow for scaling-based perturbations, with a uniform backing
            # distribution for resampling.
            "factor_1": lambda: random.uniform(0.0, 20.0),
            # Allow perturbations within this set of categorical values.
            "factor_2": [1, 2],
        })

    # Try to find the best factor 1 and factor 2
    run_experiments(
        {
            "pbt_test": {
                "checkpoint_freq": 1,
                "run": MyTrainableClass,
                "stop": {
                    "training_iteration": 20 if args.smoke_test else 99999
                },
		"resources_per_trial": {"cpu":multiprocessing.cpu_count()},
                "num_samples": 10,
                "config": {
                    "factor_1": 4.0,
                    "factor_2": 1.0,
                },
            }
        },
        scheduler=pbt,
        verbose=False)
```

**Comment by richardliaw** [comment]
Would a fix just be to have `self._checkpoint_trial_if_needed(trial)` also run in the PAUSE branch?

**Comment by xdever** [comment]
Yes, I already tried it out, and it works. Even better, move self._checkpoint_trial_if_needed(trial) before the if block to not duplicate code. I am happy to make a PR, just I am not sure why it was not in that branch (just for performance?) and does it have any side effects that I am not aware of.

**Comment by richardliaw** [comment]
I think the main thing was that we previously didn’t duplicate checkpoints
when we used to checkpoint to disk when pausing and obviously a bug at this
point.

I don’t think there’s any particular side effects off the top of my head,
but we should definitely add tests to make sure it is working aa expected.

A PR would be awesome!

Thanks,
Richard
