### ISSUE TITLE
[Tune]  latest release doesn't generate tuner.pkl during tuning

### ISSUE THREAD

**Issue by lukakap** [ray-project/ray#40491]
### What happened + What you expected to happen

I am running Ray Tune algorithms and during tunning doesn't generate tuner.pkl in experiment directory. I tested it on 2.6.3 and works fine. I checked on several different scheduler and search algorithms but result is same.

### Versions / Dependencies

ray == 2.7.1

### Reproduction script

.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Hey could you share a repro script for this?

**Comment by justinvyu** [comment]
@lukakap The file should still be generated, but one behavioral change in Ray 2.7 may explain why you're not finding it where you expect:

If you set the `RunConfig(storage_path="s3://...")`, the `tuner.pkl` file will now be written directly to S3, without saving a local copy.

Another question: How are you using this `tuner.pkl` file? The contents of this file are technically implementation details and could change arbitrarily across releases.

**Comment by lukakap** [comment]
I am using it for experiment restore. So when it is not inside experiment path directory, restore is not working. I will try to write down some repro script, but now this problem is inside complex solution so I can not easily send you repro script.

**Comment by justinvyu** [comment]
Are you following the `Tuner.restore(...)` message that shows up after interrupting training? There's a known issue that this is outputting the wrong restoration path in the case that you set a custom `storage_path`. What's the `storage_path` you set, and what's the path you're passing into `Tuner.restore`?

**Comment by justinvyu** [comment]
@lukakap I ran into the same `tuner.pkl` is not found error by configuring `RunConfig(local_dir=...)` rather than using the environment variable `RAY_AIR_LOCAL_CACHE_DIR=...`.

Could you try setting this environment variable instead? See here: https://docs.ray.io/en/latest/train/user-guides/persistent-storage.html#setting-the-intermediate-local-directory

**Comment by justinvyu** [comment]
Closing as the above workaround seems to resolve the issue for me. Feel free to reopen with more info if I don't have the same failure scenario.
