### ISSUE TITLE
Control the ratio of sampled vs trained in SyncReplayOptimizer

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#4049]
### Describe the problem

The ratio of sampled vs trained in SyncReplayOptimizer can be controlled by specifying `sample_batch_size` and `train_batch_size`.
However, in some cases, we have to use `batch_mode: complete_episodes`, e.g., use parameter space noise without ApeX.
In this case, how to control the ratio between sampled and trained?
If there is no way, how about adding an argument for SyncReplayOptimizer to control this ratio?

**Comment by ericl** [comment]
One option would to be to train multiple times to maintain the ratio automatically. I don't think anyone currently runs DQN in complete episodes so this wouldn't be surprising behavior.
