### ISSUE TITLE
[Data] `read_tfrecords_benchmark_single_node` release test regression

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#40508]
### What happened + What you expected to happen

Observed a ~2x time regression in `read_tfrecords_benchmark_single_node` for the following sub-cases:

- `tfrecords-random-int-1g`
- `tfrecords-random-float-1g`
- `tfrecords-random-bytes-1g`

<img width="1382" alt="Screenshot at Oct 19 15-51-12" src="https://github.com/ray-project/ray/assets/5122851/d567937a-d4ef-4a4a-bb10-2daf92ef05fa">

### Versions / Dependencies

ray master

### Reproduction script

release test as above

### Issue Severity

None

**Comment by raulchen** [comment]
@stephanie-wang This regression is caused by https://github.com/ray-project/ray/pull/39710, assigning the issue to you.
