### ISSUE TITLE
A mixture of on-policy and off-policy

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#4050]
### Describe the problem

A trick used in training DQN for some environments like HFO is to use a mixture of on-policy and off-policy target.
Concretely, in computing the TD error, part of the target is based on the Bellman equation as usual (i.e., r + \gmma * Q'(s', a')), and another part is the cumulative rewards sampled.
The first one is biased but stable especially when we use a target q-net. The later is unbiased but not to mention the variance, the behavior policy is different from the one being optimized.
This trick has been introduced in many materials and I recently noticed it in the [source code of a HFO solution](https://github.com/mhauskn/dqn-hfo/blob/c7b0a73de07078e248015d44573d8dcadd6fb8d1/src/dqn.cpp#L897)

**Comment by ericl** [comment]
Interesting, is there a reason it isn't the `min` of the two targets? The on policy Q estimate is an lower bound right?

**Comment by joneswong** [comment]
Ignoring the policy lag, the estimation of target q-net is a mean Q(s, a) of \pi, the sampled cumulative rewards is a **sample** of Q(s, a) of \pi. Taking min operator must introduce an underestimate bias even larger than that of twin q-net.

**Comment by ericl** [comment]
Hm right, so I guess another way to interpret this is as a mixture of n-step Q updates for n=1 and n=infinity.

We could make n_step take a distribution over n I suppose, though I don't know what reasonable choices here are, i.e. why n={1, inf} is better than say n=3.

**Comment by joneswong** [comment]
We also think this trick is not that common. Particularly, \sum_{n=t}^{T} r_n is an unbiased estimation of Q(s_t, a_t) of the behavior policy, using the it for the target of Q(s_t, a_t) of the current policy seems unreasonable to me.
