### ISSUE TITLE
[Air] Ray Result object not properly deserialized 

### ISSUE THREAD

**Issue by daturkel** [ray-project/ray#40535]
### What happened + What you expected to happen

Ray automatically saves a metrics to a `result.json` file, and users can reinstantiate results with `Result.from_path(<PATH TO result.json)`. However, during deserialization in `from_path`, the metrics are read with [pd.json_normalize(json_list, sep="/")](https://github.com/ray-project/ray/blob/e19b0eb1cb898f4f38349783fd8f86cbc8c60b83/python/ray/air/result.py#L156), then the `latest_metrics` are built by taking the [last row of that dataframe and using the `to_dict` method](https://github.com/ray-project/ray/blob/e19b0eb1cb898f4f38349783fd8f86cbc8c60b83/python/ray/air/result.py#L166). It's that `latest_metrics` object which is passed to the `metrics` kwarg to create the `Result` object that is returned.

The result of the combined `sep="/"` and `to_dict()` call is that the metrics end up collapsing nested dicts into `/`-separated strings. In particular, this means that the config (which is considered part of the metrics) is collapsed into `{"config/key_1": "val_1", "config/key_2": "val_2"}`.

Then when we use the `Result.config` property to fetch the config from the result, it [tries to do](https://github.com/ray-project/ray/blob/e19b0eb1cb898f4f38349783fd8f86cbc8c60b83/python/ray/air/result.py#L67) `self.metrics.get("config")`, except there is no more `config` key, only the `config/foo` nested keys.

I believe the fix for this is relatively simple and if someone gives the go-ahead, I'm happy to create a PR:

[Current implementation](https://github.com/ray-project/ray/blob/e19b0eb1cb898f4f38349783fd8f86cbc8c60b83/python/ray/air/result.py#L153-L156)
```python
if result_json_file.exists():
    with open(result_json_file, "r") as f:
        json_list = [json.loads(line) for line in f if line]
        metrics_df = pd.json_normalize(json_list, sep="/")

# (a few lines later)
latest_metrics = metrics_df.iloc[-1].to_dict() if not metrics_df.empty else {}
```

Proposed implementation
```python
if result_json_file.exists():
    with open(result_json_file, "r") as f:
        json_list = [json.loads(line) for line in f if line]
        metrics_df = pd.json_normalize(json_list, sep="/")
        # use the parsed json dict directly
        latest_metrics = json_list[-1]
```

### Versions / Dependencies

Python 3.10.x
Ray 2.7.1

### Reproduction script

This can be reproduced with any ray `Result` object:

```python
result_1 = <some ray result>
result_2 = Result.from_path(result_1.path)
assert result_1.config is not None
assert result_2.config is None
```

(I used [this example](https://docs.ray.io/en/latest/train/examples/pytorch/torch_fashion_mnist_example.html#torch-fashion-mnist-ex) to verify.)

<img width="1553" alt="Screen Shot 2023-10-20 at 3 36 39 PM" src="https://github.com/ray-project/ray/assets/1828387/35979cab-e920-45b9-af32-979275be7a15">

### Issue Severity

Low: It annoys or frustrates me.

**Comment by gresavage** [comment]
one problem I see with the proposed solution is that loading from a `progress.csv` was not considered. May just be a simple matter of changing [L153-L166](https://github.com/ray-project/ray/blob/e19b0eb1cb898f4f38349783fd8f86cbc8c60b83/python/ray/air/result.py#L153-L166) to the following instead:

```python
        if result_json_file.exists():
            with open(result_json_file, "r") as f:
                json_list = [json.loads(line) for line in f if line]
                metrics_df = pd.json_normalize(json_list, sep="/")
                latest_metrics = json_list[-1] if json_list[-1] else {}
        # Fallback to restore from progress.csv
        elif progress_csv_file.exists():
            metrics_df = pd.read_csv(progress_csv_file)
            latest_metrics = metrics_df.iloc[-1].to_dict() if not metrics_df.empty else {}
        else:
            raise RuntimeError(
                f"Failed to restore the Result object: Neither {EXPR_RESULT_FILE}"
                f" nor {EXPR_PROGRESS_FILE} exists in the trial folder!"
            )
```

I'm not sure, but I think reading from `progress.csv` might also need to be checked for how results are flattened and restored in the dataframe.

Unfortunately I'm having other issues with AIR corrupting trial checkpoint data so I can't confirm at the moment.

**Comment by daturkel** [comment]
That's a great point @gresavage ! I was a bit unclear about the circumstances under which `progress.csv` would exist but `result.json` wouldn't... Maybe if training failed to complete? It seems to me that `result.json` contains more info (namely, it contains the config information, which `progress.csv` does not).

Anyway, since `progress.csv` doesn't contain the config information, we can't hope to restore the config to the `Result` itself, but your proposal does at least re-create the `latest_metrics` in that branch of the if-else logic so the code would still execute.
