### ISSUE TITLE
[CI] `linux://python/ray/tests:test_output` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40540]
- 23eb7f749ab889ca0ebf81bea93197ea62696cc3 FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1277#018b4e4f-b101-40c6-8aa7-eb5a74dfd2fe)
- dc944fe7d9f3fae70359a87b77ed96bcd647e6bc FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1177#018b3d16-2d35-4742-997e-a08deea5ec03)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_output-END
....

**Comment by can-anyscale** [comment]
This might alleviate the issue: https://github.com/ray-project/ray/pull/40615

**Comment by jonathan-anyscale** [comment]
> This might alleviate the issue: #40615

Looks reasonable for me. The red failures were from dashboard not being properly setup which failed other test cases.

For the yellow failures, it's caused by `test_dedup_logs()` which still being investigated

**Comment by rkooo567** [comment]
It is the CI issue, so we won't mark it as a release blocker.
