### ISSUE TITLE
[CI] `osx://python/ray/tests:test_placement_group` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40543]
- a1ac74f7b414204e382e4c33bee0e990bd87a8f0 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6560#018b4a5e-58ae-46f9-a9fb-0813d517c91f)
- 2d726098cfcac35686fe2a23528469bf25dc9592 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6559#018b4a1b-3cd0-4936-b552-5147a843b8d4)
- 3c0476aa9c9ae1b5f6d9042061ad34ac80167bd2 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6558#018b4a12-10f5-4795-ac32-b55726bb88a2)
- af332f41e9e1fcda3622952cba16c13d25c76b17 FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6557#018b49ed-5db5-44c8-83aa-7ffb76dade14)
- a2ef28db16233da3b189846bdfe7e802cfae875d FAILED [Buildkite :mac: :apple: Large](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6484#018b3b8a-02e0-4ae1-9dbb-39fee8e84694)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_placement_group-END
....

**Comment by anyscalesam** [comment]
@can-anyscale shouldn't this be jailed? given it was marked 3w ago as flaky?

**Comment by jjyao** [comment]
It's green now.
