### ISSUE TITLE
Release test air_example_gptj_deepspeed_fine_tuning.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40547]
Release test **air_example_gptj_deepspeed_fine_tuning.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2283#018b51b7-8f07-493f-8a96-5ebc31b3cd93 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 3d2d4fe8162e24d637e3f098541c817f268ab4cb found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/678

**Comment by matthewdeng** [comment]
Blamed commit looks unrelated, but sanity checking a revert here https://buildkite.com/ray-project/release-tests-pr/builds/56708
