### ISSUE TITLE
Release test `rllib_stress_tests` failed

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#40567]
https://buildkite.com/ray-project/release-tests-branch/builds/2282#018b5007-4270-4847-ab21-0404b471e850

**Comment by anyscalesam** [comment]
@vitsai is this blocker for ray28?

**Comment by aslonnie** [comment]
> @vitsai is this blocker for ray28?

yes, the release test is failing.

**Comment by can-anyscale** [comment]
The smoke version fails as well, in case it's easier to use that for debugging

**Comment by zhe-thoughts** [comment]
@sven1977 could you update an ETA of fixing? Thanks

**Comment by sven1977** [comment]
Taking a look!

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/40656
Tests running right now to confirm ...

cc: @zhe-thoughts

**Comment by sven1977** [comment]
This is not an RLlib issue, but a possible bug in one of our dependencies (minigrid and/or matplotlib). I removed minigrid from the release app-config, it's not required anyways.

**Comment by anyscalesam** [comment]
Update here that PR with the removal is in and picked; awaiting approval to merge into release branch cc @kouroshHakha @sven1977 @can-anyscale
