### ISSUE TITLE
[Serve] Change log statement level or convert to metric

### ISSUE THREAD

**Issue by volks73** [ray-project/ray#40564]
### Description

The Ray Serve replica prints an `INFO` statement for every `__Call__` method with a status, typically `OK`, and the latency of the method, e.g., `7.2ms`. For example,

```sh
api  (ServeReplica:default:Api pid=161) INFO 2023-10-12 16:58:11,742 Api default#Api#LcrBZT 587c924c-8794-4006-85ce-e7912ee4994d /api/app/status default replica.py:749 - __CALL__ OK 7.2ms
```

This causes a lot "noise" in STDOUT and in the logs. We disable the messages using a filter, but this feels like a hack:

```python
class NoServeReplicaFilter(logging.Filter):
    def filter(self, record):
        return not (
            record.levelname == "INFO"
            and "__CALL__ OK" in record.msg
            and record.filename == "replica.py"
            and record.module == "replica"
        )

serve_logger = logging.getLogger("ray.serve")
serve_logger.addFilter(NoServeReplicaFilter())
```

The log statement appears to be more for debugging than information, but it also appears to be logging a metric, call latency. I would like to request the log statement be modified to reduce the "noise" in the logs. I see the following options:

1. Change the statement level from `INFO` to `DEBUG`. The default level for most application is `INFO` so the statement is currently logged all the time, but the statement appears to be more useful for debugging.
2. Change to a Prometheus metric and drop the log statement. Since the log statement includes the call latency, this "feels" more like a metric than a log statement. Thus, the log statement should be converted to a metric using Prometheus instrumentation.

It is possible I am missing some configuration or environment variable that could be used to disable this specific log statement. The filter is scoped to Ray Serve.

### Use case

I believe I address this in the description.

**Comment by edoakes** [comment]
The first PR for that was merged: https://github.com/ray-project/ray/pull/40465

Implementation coming this week

**Comment by volks73** [comment]
Great, thank you for the update. I look forward to the `logging_config` feature.
