### ISSUE TITLE
[ci] 1000000_queued_time regression

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#40605]
### What happened + What you expected to happen

`1000000_queued_time` probably does have a regression, but it seems less serious than 20%, seems to be 185 -> 200, ~8%

<img width="1337" alt="image" src="https://github.com/ray-project/ray/assets/11676094/a7d8c20e-5570-4160-b397-ac7282357721">

### Versions / Dependencies

2.8

### Reproduction script

NA

### Issue Severity

None

**Comment by rickyyx** [comment]
This is the root cause: 2a0f0e55df

**Comment by rkooo567** [comment]
Discussed with @jjyao and @rickyyx 

The PR has been reverted from Ray 2.8. We decided to bear the perf regression in the master since it improves the observability greatly, and the impact is very minimal (small regression from extremely stress tests, and other tests didn't seem to be affected)
