### ISSUE TITLE
Out of Memory Error on a GPUs causes device error

### ISSUE THREAD

**Issue by JessicaSchrouff** [ray-project/ray#4061]
### System information
- **OS Platform and Distribution**: Mint 19 (Ubuntu 18.04)
- **Ray installed from (source or binary)**: latest wheel
- **Ray version**: 0.6.3
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
I am running ray Tune on an AWS instance with 8 GPUs. For some reason, I get out of memory errors on some trials, while being able to run most of them. However, I also started getting 

> invalid device ordinal

errors, as if ray was not able to get the correct device number anymore. It does not happen immediately after an OOM error, and I could not find a pattern in how these 2 errors correlated (if they do).

### Source code / logs
Full error:
> Traceback (most recent call last):
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 230, in fetch_result
    result = ray.get(trial_future[0])
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/ray/worker.py", line 2132, in get
    raise value
ray.worker.RayTaskError: [36mray_worker[39m (pid=2873, host=b75ac73b9f01)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/src/prodo_learn/tasks/pred_types/hyper.py", line 78, in _setup
    self.model = train_params["model"].to(device=self.device)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/opt/anaconda/envs/default/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
>

Parts of the code dealing with GPUs:
```python
class MainArgs(Trainable):
    def _setup(self, config):
        torch.manual_seed(args.seed)
        args.cuda = not args.no_cuda and torch.cuda.is_available()
        if args.cuda:
            torch.cuda.manual_seed(args.seed)
            dev_ids = ray.get_gpu_ids()
            self.device = torch.device("cuda", dev_ids[0])
        else:
            self.device = torch.device("cpu")
        self.model = train_params["model"].to(device=self.device)
    def _train(self):

[...]

sched = AsyncHyperBandScheduler(
            time_attr="training_iteration", reward_attr="val_acc", max_t=50, grace_period=5
        )

tune.run_experiments(
    {
        "exp": {
            "local_dir": args.output_dir,
            "run": MainArgs,
            "stop": {"timesteps_total": 50},
            "resources_per_trial": {"cpu": 4, "gpu": 0 if args.no_cuda else 1},
            "num_samples": args.n_samples,
            "config": {
                "zparams": {
                    "args": args,
                    "train": {"data": loadpin, "meta": metadata, "model": module.Model},
                }
            },
        }
    },
    verbose=1,
    scheduler=sched,
    search_alg=HyperOptSearch(space, reward_attr="val_acc"),
)
```

Any help would be appreciated.
Thank you!

**Comment by robertnishihara** [comment]
If you print `dev_ids` in one of the trials that fails, what is it?

**Comment by JessicaSchrouff** [comment]
Hi Robert,

I do not have that output unfortunately. I send everything to AWS and printing things to the console gets a bit lost in ray output and difficult to locate afterwards.
On the trials that did not fail, the ```dev_ids``` seemed OK.
To give you an idea, I requested 200 trials. 124 of those trials failed, 76 because of the device ordinal error (the rest being out of memory). The first error to appear is OOM, but then they are interleaved, with no specific pattern, apart the fact that the device error does not start before trial 33.
I will try on a smaller dataset to get the output, but if I don't get OOMs, it might not reproduce.
Thank you for the help!
Best,
Jessica

**Comment by JessicaSchrouff** [comment]
Hi Robert,
I tried to print the device id when it failed to put the model on it, but I could not get the output from AWS back.
I have increased the worker memory, so encounter less memory errors, but I still have quite a few of these device errors: 2 OOM, then 14 device errors on 60 trials. Here is a snapshot of the error logs with their trial ID and timing so you can see the timeline (OOMs highlighted).
![screenshot from 2019-02-20 11-07-10](https://user-images.githubusercontent.com/6248934/53088013-7a525900-3500-11e9-86f0-f1a9f976c5d2.png)


Is there anything I can do about this error? Maybe block errored trials for a bit to ensure that the device becomes available again? 
In the logs, it says I am using 7 out of 8 GPUs only when there is an error, so my guess is that the device id is the `missing' device, which does not seem to be `detected' at that moment.
Thank you for the help!
Best,
Jessica

**Comment by richardliaw** [comment]
This may have been because we didn't release the GPUs fast enough. 

Closing because stale, but do feel free to reopen this if it is still an issue.

**Comment by crypdick** [comment]
@richardliaw I think I am encountering this issue now. Some tune trials (but never the first) are failing on the first batch of the first epoch, even with batch size 32 on a p2.8xlarge, 50-layer net. For now I'm going to just set `raise_on_failed_trial=False`. I am just doing random hparam search so I don't believe these failed trials are a big problem to me, but I could this being a deal-breaker for someone using a Bayesian search
