### ISSUE TITLE
Batch Inference Issue with ray.data.dataset.MaterializedDataset 

### ISSUE THREAD

**Issue by bussrakrkmz** [ray-project/ray#40654]
### What happened + What you expected to happen

While converting the numpy array to ray dataset and working on distributed batch inference to an LLM Model, we found that all but one worker was killed by ray.kill. When we examined it in detail, we saw that the numpy array turned into MaterializedDataset type. Thinking that this was the reason for the problem, when we put the data in the numpy array into a txt file, read it with RayData's read_text function, and made distributed inference again, we saw that all workers were working.

### Versions / Dependencies

Ray version : 2.7.1
Python Version: 3.10.4
Linux version : Ubuntu 20.04.6 LTS

### Reproduction script

  from typing import Dict
  import numpy as np
  import time
  import ray
  from ray.train import Checkpoint
  
  arr_np = np.asarray([
  "what is the weather today in Istanbul ?",
  "what is the weather today in Ankara ?",
  "what is the weather today in Gaziantep ?",
  "what is the weather today in Balikesir ?",
  "what is the weather today in Yozgat ?",
  "what is the weather today in Istanbul ?",
  "what is the weather today in Ankara ?",
  "what is the weather today in Gaziantep ?",
  "what is the weather today in Balikesir ?",
  "what is the weather today in Yozgat ?",
  "what is the weather today in Istanbul ?",
  "what is the weather today in Ankara ?",
  "what is the weather today in Gaziantep ?",
  "what is the weather today in Balikesir ?",
  "what is the weather today in Yozgat ?",
  ])
  
  arr = np.repeat(arr_np, repeats = 1)
  
  print(len(arr))
  
  
  ds = ray.data.from_numpy(arr)
  
  
  
  
  class HuggingFacePredictor:
      def __init__(self):
          from transformers import pipeline
          start = time.time()
         
          self.model = pipeline("text-generation", model="gpt2-large" , device="cuda")
  
          end = time.time()
          print("---------2-------")
          print(end-start)
  
      def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, list]:
          print("Başladı")
          start = time.time()
          predictions = self.model(list(batch["data"]), max_length=20, num_return_sequences=1)
          start2 = time.time()
          batch["output"] = [sequences[0]["generated_text"] for sequences in predictions]
          end = time.time()
          print("---------1-------")
          print(end-start)
          print(end-start2)
          time.sleep(50)
          return batch
  
  
  
  
  start = time.time()
  predictions = ds.map_batches(
      HuggingFacePredictor,
      num_gpus=0.5,
      batch_size=3,
      compute=ray.data.ActorPoolStrategy(size=6),
      ).take_batch(15)
  
  end = time.time()
  print("---------------3-----------------")
  print(predictions)
  print(end-start)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by raulchen** [comment]
hey @bussrakrkmz, your assumption is right, converting in-memory numpy data to a Ray Dataset needs to materialize the data in local process memory. This is inefficient for large amount of data. 
Storing the data in files can help. As data can be read in parallel and in a streaming way. Instead of text files, parquet files can be more efficient. 
Glad you worked around the issue. It seems that nothing else needs to be done. I'll close this issue.
