### ISSUE TITLE
[Core] Update tensorflow dependency to 2.12+

### ISSUE THREAD

**Issue by gresavage** [ray-project/ray#40669]
### Description

protobuf < 3.20 has an issue where `builder.py` is missing. See [here](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal)

This causes logging callbacks to *fail* to generate a `tf_events` file and therefore logging to tensorboard is "broken"

Currently the user is required to know about the issue and either `curl` `builder.py` into the correct path, install ray and then separately install the latest protobuf, or generate tensorboard logs post-facto from `progress.csv` or `results.json` files.

Tensorflow is currently on release 2.14.0, with dependency on protobuf 3.20+ starting in 2.12.0.

### Use case

Update affected `requirements.txt` to point to more recent tensorflow releases which, in-turn will allow `protobuf` to update to > 3.20 when the problem is fixed.

**Comment by gresavage** [comment]
`TensorboardX` will also have to be updated to (I think) `2.6.2`

**Comment by anyscalesam** [comment]
You should be able to specify your required lib versions in requirements.txt (or however you are configuring your dependencies) Ray does not have any upper bound for protobuf.

**Comment by gresavage** [comment]
Thanks for the tip @anyscalesam, sorry I did not respond sooner - the issue arises with `tensorflow` dependency, not `protobuf` directly. Since `tensorflow==2.11`  depends on `protobuf<3.20` there is no dependency solution for `ray[all]==2.7.1` with `protobuf>=3.20`. So although `ray` doesn't provide an upper bound directly on `protobuf`, by pinning `tensorflow==2.11` then `protobuf` is indirectly pinned to (I believe) `3.19.6` and thus the issue.

If I specify `protobuf>3.20` in `requirements.txt` then there is no valid solution. For `pip` this can obviously be brute-forced however if a project uses something such as `poetry` to resolve dependencies this becomes quite a nuisance to overcome.

I am honestly surprised that not more people have discovered the issue with `tfevents` files not being generated due to this missing `builder.py` in `protobuf`.

**Comment by anyscalesam** [comment]
Thanks @gresavage - where are you finding the tf2.11 pin for ray271? ray shouldn't have any dependency on a specific 271 version.

**Comment by gresavage** [comment]
@anyscalesam welp... I'm an idiot and sorry for wasting your time - it looks like the only pin to 2.11 anymore is in the dockerfile requirements:

https://github.com/ray-project/ray/blob/releases/2.7.1/python/requirements/ml/dl-gpu-requirements.txt#L3
https://github.com/ray-project/ray/blob/releases/2.7.1/python/requirements/ml/dl-cpu-requirements.txt#L4

The conflict I had was coming from another package we develop which pinned to TF 2.11. It has been a while since I messed around on the problem I was having and I misremembered the origin of the package conflict

So sorry :(
