### ISSUE TITLE
WARNING: Falling back to serializing objects of type <class 'torch.nn.backends.thnn.THNNFunctionBackend'> by using pickle. This may be inefficient.

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#4067]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux RedHat 7.3
- **Ray installed from (source or binary)**:
- **Ray version**: 0.6.3
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem

I create a pytorch model in a remote actor and use this actor to generate experiences(Cuda tensor). I got this warning. Why? Thanks.

### Source code / logs

``` WARNING: Falling back to serializing objects of type <class 'torch.nn.backends.thnn.THNNFunctionBackend'> by using pickle. This may be inefficient.```

**Comment by ash1995** [comment]
@zhan0903 Did you solve this issue?

**Comment by richardliaw** [comment]
Try moving the tensor to cpu(). Closing because stale, but feel free to reopen this issue with a reproducible script.
