### ISSUE TITLE
Ray Import Error: Dynamic Module Definition

### ISSUE THREAD

**Issue by Wapaul1** [ray-project/ray#407]
When I import ray in an IPython instance for python 3, it fails and reports the following error:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
\<ipython-input-1-69e510513f49> in <module>()
----> 1 import ray

/home/ubuntu/ray/python/ray/__init__.py in <module>()
      3 from __future__ import print_function
      4
----> 5 from ray.worker import (register_class, error_info, init, connect, disconnect,
      6                         get, put, wait, remote, log_event, log_span,
      7                         flush_log)

/home/ubuntu/ray/python/ray/worker.py in <module>()
     22 # Ray modules
     23 import ray.pickling as pickling
---> 24 import ray.serialization as serialization
     25 import ray.services as services
     26 import ray.numbuf

/home/ubuntu/ray/python/ray/serialization.py in <module>()
      5 import numpy as np
      6
----> 7 import ray.numbuf
      8 import ray.pickling as pickling
      9

/home/ubuntu/ray/python/ray/numbuf/__init__.py in <module>()
     17
     18 try:
---> 19   from ray.core.src.numbuf.libnumbuf import (deserialize_list, numbuf_error,
     20                                              numbuf_plasma_object_exists_error,
     21                                              read_from_buffer,

ImportError: dynamic module does not define init function (PyInit_libnumbuf)
```

**Comment by robertnishihara** [comment]
I think I've seen this error in situations where Ray may have been compiled against one version of Python (e.g., Python 2) and imported in another (e.g., Python 3). Is there a chance something like that is happening?

**Comment by robertnishihara** [comment]
Note that when you compile Ray, cmake will look for Python libraries to use to build Ray's Python C extensions. It will find the Python libraries that are associated with the version of Python that is found when you run `which python` from the command line. So if you call `setup.py install` with a version of Python that is different from the one that `which python` finds, then you will probably encounter this problem. For example, this could happen if you do `python3 setup.py install`.

This problem is probably the same as #241.

**Comment by Wapaul1** [comment]
Yep that was the issue. I accidentally installed Ray on Python 2 and was trying to import it in Python 3. I uninstalled Ray on python 2, re-cloned the repository, and installed Ray on Python 3 to fix it.

**Comment by robertnishihara** [comment]
Ok, great!
