### ISSUE TITLE
[Templates] Finetuneing template 04 OOMS due to gpu memory leak when using LoRA + V100s

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [ray-project/ray#40714]
### What happened + What you expected to happen

[Fine-tuning template 04](https://github.com/ray-project/ray/tree/master/doc/source/templates/04_finetuning_llms_with_deepspeed) OOMs under specific circumstances.

Start an AWS _or_ GCP V100 node.
Deploy the template.
Run `./run_llama_ft.sh --size=7b --lora`.

This will OOM after a while after GRAM fills up. GRAM usage will fill up linearly with steps strongly suggesting a memory leak.
Attempts to reproduce this on AWS's p4des or G5s failed. So this appears to be more or less specific to V100s.

Screenshot shows GRAM (orange) on runs with different context lengths (8, 4, 1 in this order) with LoRA on a V100.
(The final run with batch size 1 grows to approx 100% before crashing).
![Screenshot 2023-10-25 at 10 36 51](https://github.com/ray-project/ray/assets/9356806/16c8b4a4-6993-4ae6-86a0-381818f264fa)

This is how it looks like on some A100s and should look like (no linear increase, just a flat GRAM curve (orange)).
<img width="545" alt="Screenshot 2023-10-26 at 11 16 26" src="https://github.com/ray-project/ray/assets/9356806/4d2ae96c-f4cb-4b25-aa64-9ab6435cca46">

### Versions / Dependencies

master
https://github.com/ray-project/ray/tree/master/doc/source/templates/04_finetuning_llms_with_deepspeed

### Reproduction script

. 

### Issue Severity

None

**Comment by kouroshHakha** [comment]
some related issues found online: 
https://github.com/microsoft/DeepSpeed/issues/3002
https://github.com/microsoft/DeepSpeed/issues/3378

**Comment by mak-454** [comment]
+1 we are facing this same issue with 4 A10 node (AWS g5.12xlarge )

**Comment by woshiyyya** [comment]
@mak-454 Did you use Ray? Or LoRA + Deepspeed only?

**Comment by mak-454** [comment]
@woshiyyya am using  https://github.com/ray-project/ray/blob/master/doc/source/templates/04_finetuning_llms_with_deepspeed/finetune_hf_llm.py
and running it with --lora option.
**Few more details**
Setup - single node AWS g5.12xlarge. It has 4 a10 nodes.
Batchsize - 4
ND - 4
Block size - 512
Lora config and deepspeed config from the dir - https://github.com/ray-project/ray/blob/master/doc/source/templates/04_finetuning_llms_with_deepspeed

**Comment by mak-454** [comment]
@woshiyyya  It seems to be going fine and GPU utilization seems to be stable after commenting the line https://github.com/ray-project/ray/blob/8504563be5302f424f6efa7ba38c03ddccb3622b/doc/source/templates/04_finetuning_llms_with_deepspeed/finetune_hf_llm.py#L402

**Comment by woshiyyya** [comment]
@mak-454 Interesting! Let us repro it on our side and get back to you.
