### ISSUE TITLE
[data] refine concepts in user-facing APIs

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#40725]
Today, some concepts in Data APIs are either inaccurate, or unnecessary to expose. Examples are:
* `parallelism` currently actually means number of partitions, instead of number of concurrent tasks. 
* `TaskPoolStrategy/ActorPoolStrategy` expose too many Ray Core-level details that are hard to understand for people who only want to use Ray Data.

**Comment by anyscalesam** [comment]
@c21 planning to do for this week.

**Comment by anyscalesam** [comment]
@c21  can you link the PR; only remaining is docs. sitll on track for ray29

**Comment by c21** [comment]
https://github.com/ray-project/ray/pull/41948 is the PR to be merged to 2.9.

**Comment by anyscalesam** [comment]
Did the above get picked in successfully @c21 ?

**Comment by c21** [comment]
@anyscalesam - targeting to get https://github.com/ray-project/ray/pull/41963 in by EOD today.
