### ISSUE TITLE
`test_request_timeout` made more flaky by Intel GPU PR

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#40724]
https://github.com/ray-project/ray/pull/40587
<img width="1113" alt="Screenshot 2023-10-26 at 1 29 36 PM" src="https://github.com/ray-project/ray/assets/7005244/b9ec398e-3121-4228-b6d4-b914cdf88e82">

**Comment by anyscalesam** [comment]
![Image](https://github.com/ray-project/ray/assets/116198444/ae9ab16d-d0b3-4493-8e1f-9f4402050de9)

looks ot be passing now; but also skipping... closing
