### ISSUE TITLE
[CI] `linux://python/ray/tests:test_memory_pressure` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40730]
- d2a2e76397913a999ae56e76ea8629c8867035cf FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6677#018b6e20-585d-4bbd-b977-4f9d22743ad1)
- e96398a87abcb47d1f3198bc14eaa613ab7b3846 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6676#018b6e17-741f-4a06-a0ee-7e61042f4934)
- 1e3917a093afdc47875d29fb4ff63f1218682809 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6672#018b6dbd-7fa3-4b09-b059-be1ac008bb7d)
- 5918c5e4efe908ffd1d4785c22b95a0b6b848dc0 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6670#018b6db0-9595-4278-9ac8-466356e1b9b0)
- 632a297e426d6775029cba71e93985e082b6a395 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6668#018b6d96-bb94-4c2e-a7a0-7fb130896a0d)
- 69522ff67cbf6a7422fac74e387ce9e72edbfc29 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6667#018b6d5a-007f-4b82-9198-cfc41caa0182)
- f5fbe8b67805ad45148dc5dca88d49448aabceda FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6664#018b6c8a-6528-4e4b-8f42-27ed6fb0599f)
- c0a6e55696aebb2fb2f6e21bf0770df81eea8029 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6659#018b69bc-7469-4226-9a46-bc75cf0f1578)
- 7787b2e489c59fb317f7f1334a168e4e0433771c FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6657#018b690c-b656-48a9-94e0-d21790dd7c92)
- 2add5cd2eeb9df2ccd96894bb910475e447f11b1 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6656#018b6914-82c3-4f0f-baa9-4f274420aad2)
- a7ae2f10bd7a47585674a53e16b5a57b76731d6e FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6654#018b6901-c94f-4e78-8193-29cca88dff27)
- 8f9069eb1a3dab560e64a4b64fd765f12614d8a5 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6649#018b6812-9f16-44f1-a94a-c67f1b280046)
- fe6d5f44a5253191900fed9ab4547e3d2f3f26a9 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6643#018b654f-edaf-4069-80db-11faea541b7e)
- 8cfc894d9f718424ccb20f29e27e966381db890e FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6642#018b653f-10fb-4e86-a83d-42bdd89bcbf1)
- 792e4e6cad8cd6e2d9eb3188c7afcef3ca6410eb FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6639#018b64e2-8a49-4688-8275-22c42b7d6704)
- f1a34b9f3e9956473a4e2066f6ebce1e8c0538a5 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6636#018b642f-b69e-4e14-b55f-1e640f516157)
- 99543b26cf981629eb228dbb5e691574052a7f86 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6628#018b62bb-cc3a-41b8-a0ad-f9a3ea2edd32)
- c051a01953230c48cf8ad77edc288b75e7b9ab45 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6613#018b5eef-525e-4bba-9ef4-ae3fc968bf83)
- 1c405fc2b0ef7fbb2c5146ff19d1093646878310 FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6610#018b5eda-b575-4450-a529-b935d25911a9)
- df3237ae4f19458ef12411315a986a1a618de6bf FAILED [Buildkite :python: civ1 tests](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6608#018b5ed6-49e0-4aeb-a752-99b631d2e2b6)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_memory_pressure-END
....

**Comment by anyscalesam** [comment]
@can-anyscale any reason this isn't jailed?

**Comment by rkooo567** [comment]
There's no "jailed test" now

**Comment by anyscalesam** [comment]
@can-anyscale why is this still in v1 CI?

**Comment by can-anyscale** [comment]
@anyscalesam we moved it back to civ1 to see if it becomes less flaky but I think it's still flaky; let's investigate otherwise we can decide if we want to jail it in civ2

**Comment by anyscalesam** [comment]
it's still pretty flaky... 
![image](https://github.com/ray-project/ray/assets/116198444/1989989d-995f-4da6-8b18-92abeac04403)
@rkooo567 this is linux do we want to keep p0 for this as something we want to fix and block on for ray29 release?

**Comment by rkooo567** [comment]
Yes. I am planning to fix it

**Comment by anyscalesam** [comment]
I'm re-opening this at P1 as there's been a string of failures the last couple of days.

**Comment by anyscalesam** [comment]
anddd it is passing again. definitely one test that i will dig deeper into in the new year to verify reasoning of flakiness.

**Comment by rkooo567** [comment]
It's passing because I fixed it in my free time lol

**Comment by can-anyscale** [comment]
Need to give you more free time ;))
