### ISSUE TITLE
[Data] Streaming executor backpressure

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#40754]
Ray Data now has switched to the streaming execution backend. For Datasets that don't have aggregation operators, all data should be streamed through all the operators. However, if any operator is slow, data will pile up in the buffer and may cause OOM, disk spilling, or even out-of-disk errors. 

As of Ray 2.7, we have implemented following backpressure mechanisms:
1. [Resource-based backpressure](https://github.com/ray-project/ray/blob/745dc26c9f62dcdb2114f48257988059db46b4cb/python/ray/data/_internal/execution/streaming_executor_state.py#L442): check if there are enough resources to run a new op. 
1. [Actor pool map backpressure](https://github.com/ray-project/ray/blob/d018b4c436367ec30d21d6dfb3b6019bf3c7ef36/python/ray/data/_internal/execution/operators/actor_pool_map_operator.py#L120): check free slots for actor-based map operators.
1. [Prioritize ops with least output buffer](https://github.com/ray-project/ray/blob/745dc26c9f62dcdb2114f48257988059db46b4cb/python/ray/data/_internal/execution/streaming_executor_state.py#L485): the idea is to allocate more resources for the downstream operators. 

Despite above mechanisms, there are still some scenarios where backpressure doesn't work properly.

1. The executor will allocate all resources for the upstream operators, making downstream operators have no resource to run and to consume the upstream outputs. 
    1. An experimental feature (concurrency-cap backpressure) will be implemented in 2.8 to address this issue. It's disabled by default in 2.8. See https://github.com/ray-project/ray/pull/40275 for how to enable it and other details.
1. When a single task is too big, data will be outputted in a streaming manner. But the output is not backpressure. 
    1. If you see this issue, you may want to increase the `parallelism` in your read op (e.g., `ray.data.read_image(..., parallelism=N)`), so that each task is more fine-grained. This can usually solve most cases, unless one single file is too big.
    1. A new experimental feature (streaming output backpressure) will be implemented in 2.8. It's also disabled by default. See https://github.com/ray-project/ray/pull/40387 for how to enable it and other details. 
1. Slow consumer doesn't trigger backpressure. See https://github.com/ray-project/ray/issues/40753. Planned in 2.9.
1. The resource-based backpressure doesn't consider the real resource usage.
    1. Currently it only consider the logical resources (e.g., num_cpus/num_gpus), we should use the metrics in `OpRuntimeMetrics` to make the calculation more accurate.

**Comment by raulchen** [comment]
Updates on the 2 new backpressure policies:
* StreamingOutput backpressure works well on benchmarks. It will be enabled by default in 2.9. 
* ConcurrencyCap backpressure still needs more improvements. It will be enabled by default in 2.10. https://github.com/ray-project/ray/issues/41193

**Comment by bveeramani** [comment]
Fixed by #43171
