### ISSUE TITLE
[ci] manual release test broken on CI

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#40762]
### What happened + What you expected to happen

Seems we are no longer able to create manual release runs w/o specifc wheels link? 

https://buildkite.com/ray-project/release-tests-branch/builds/2349#_

<img width="1247" alt="image" src="https://github.com/ray-project/ray/assets/11676094/5cf32829-a516-4f8e-930b-84d9c80c31ca">

### Versions / Dependencies

master

### Reproduction script

https://buildkite.com/ray-project/release-tests-branch/builds/2349#_

### Issue Severity

None

**Comment by aslonnie** [comment]
wheels link is not support for some time.

will leave it for @can-anyscale to fix / clean up.

**Comment by aslonnie** [comment]
everything is basically building from source with caching now

**Comment by rickyyx** [comment]
> wheels link is not support for some time.
> 
> will leave it for @can-anyscale to fix / clean up.

I think wheel link is still working? But rather the branch/commit hash is not working.

**Comment by can-anyscale** [comment]
The new release test pipeline fixed this
