### ISSUE TITLE
[CI] `linux://python/ray/tests:test_usage_stats` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40786]
....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_usage_stats-END
....

**Comment by jjyao** [comment]
It has been consistently passing now.

<img width="567" alt="Screenshot 2023-11-03 at 8 37 52 AM" src="https://github.com/ray-project/ray/assets/898023/be8616b1-dfe5-4b60-ac8a-e1846d6444bf">
