### ISSUE TITLE
[tune] Add options to remove default logger. 

### ISSUE THREAD

**Issue by 24hours** [ray-project/ray#4078]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.6.1
- **Python version**: 3.6.7
- **Exact command to reproduce**: 

### Describe the problem
Currently running experiment in ray tune `run_experiments` will automatically produce log 
using `[_JsonLogger, _TFLogger, _CSVLogger]`. I added my own customer logger to format TFboard output into my own liking and realize that `_TFLogger` is still active thus cluttering my TFboard. Should we turn off default logger when custom logger is present or add new flag to turn them off.

**Comment by richardliaw** [comment]
OK, we can have a flag to opt-out of default loggers. so this would be like

`run_experiments(..., default_loggers=False)`

Would you be interested in posting a PR for this?
