### ISSUE TITLE
Actor placement and task scheduling are not aware of each other.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#408]
This is most relevant in the case of actors and tasks that both require GPUs (perhaps not the most common case).

Suppose that we have two machines each with 1 GPU. We create one actor that uses 1 GPU and one task that uses 1 GPU. It is possible that they will be placed on the same machine. In that case, if the actor is created first, the task will never get scheduled because the actor may be around forever.

```python
import ray
import time

# This example should be run on a two node cluster in which each node has a single GPU.
ray.init(redis_address=...)

@ray.actor(num_gpus=1)
class Foo(object):
  def __init__(self):
    pass

@ray.remote(num_gpus=1)
def f():
  return 1

# Create an actor. This uses 1 GPU.
Foo()

time.sleep(1)

# Wait for the GPU task to finish. This may hang.
ray.get(f.remote())
```

**Comment by robertnishihara** [comment]
There are a number of approaches to fixing this.

1. Force actor placement and GPU scheduling to all go through the global scheduler (however, this might break down with multiple global schedulers depending on how we do it).
2. Force GPU tasks and actors to coordinate with Redis to figure out which GPUs to use.
3. If a local scheduler is assigned a GPU task but can't run it in the forseeable future because actors have acquired all of the GPUs, it could push the task back to the global scheduler or assign it directly to another local scheduler.

**Comment by raopku** [comment]
Has the problem been solved?

**Comment by robertnishihara** [comment]
Not yet.

**Comment by robertnishihara** [comment]
This was fixed long ago.
