### ISSUE TITLE
ray.data.dataset.MaterializedDataset is not working multiple worker

### ISSUE THREAD

**Issue by bussrakrkmz** [ray-project/ray#40804]
### What happened + What you expected to happen

While converting numpy array to ray dataset and working on distributed batch inference to an LLM Model, we found that all but one worker was killed by ray.kill. When we examined it in detail, we saw that the numpy array turned into MaterializedDataset type. Why are workers being killed instead of working in MaterializedDataset and only 1 worker is left standing? According to your documentation, distributed says it will work, but it doesn't and it gives an error that the workers were killed by ray.kill.

### Versions / Dependencies

Ray version : 2.7.1
Python Version: 3.10.4
Linux version : Ubuntu 20.04.6 LTS

### Reproduction script

from typing import Dict
import numpy as np
import time
import ray
from ray.train import Checkpoint

arr_np = np.asarray([
"what is the weather today in Istanbul ?",
"what is the weather today in Ankara ?",
"what is the weather today in Gaziantep ?",
"what is the weather today in Balikesir ?",
"what is the weather today in Yozgat ?",
"what is the weather today in Istanbul ?",
"what is the weather today in Ankara ?",
"what is the weather today in Gaziantep ?",
"what is the weather today in Balikesir ?",
"what is the weather today in Yozgat ?",
"what is the weather today in Istanbul ?",
"what is the weather today in Ankara ?",
"what is the weather today in Gaziantep ?",
"what is the weather today in Balikesir ?",
"what is the weather today in Yozgat ?",
])

arr = np.repeat(arr_np, repeats = 1)

print(len(arr))

ds = ray.data.from_numpy(arr)

class HuggingFacePredictor:
def __init__(self):
from transformers import pipeline
start = time.time()

self.model = pipeline("text-generation", model="gpt2-large" , device="cuda")

end = time.time()
print("---------2-------")
print(end-start)

def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, list]:
print("Başladı")
start = time.time()
predictions = self.model(list(batch["data"]), max_length=20, num_return_sequences=1)
start2 = time.time()
batch["output"] = [sequences[0]["generated_text"] for sequences in predictions]
end = time.time()
print("---------1-------")
print(end-start)
print(end-start2)
time.sleep(50)
return batch

start = time.time()
predictions = ds.map_batches(
HuggingFacePredictor,
num_gpus=0.5,
batch_size=3,
compute=ray.data.ActorPoolStrategy(size=6),
).take_batch(15)

end = time.time()
print("---------------3-----------------")
print(predictions)
print(end-start)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by kocmurat93** [comment]
i think , it is bug too :) i am waiting your response

**Comment by raulchen** [comment]
MaterializedDataset should work with multiple workers. I ran your script on my laptop, it works well. 
If you are seeing a worker process being killed. It's most likely due to OOM. consider reducing the size of `ray.data.ActorPoolStrategy(size=6)`.
if you have more detailed error information, please paste it here.

**Comment by bussrakrkmz** [comment]
The only error message it gives in the logs is "The actor is dead because it was killed by `ray.kill`." . Workers die directly before they are started.

**Comment by bussrakrkmz** [comment]
It works with 1 worker, but multiple workers do not work in a distributed manner. Can you look at the status of all your workers in Ray Dashboard and share them here?

**Comment by raulchen** [comment]
Passing a MaterializedDataset to multiple workers is very common in Ray Data. We have a lot of test coverage on this case. I'm pretty confident this won't be an issue. 
It should be something else that caused the issue in your case, which I guess is likely to be OOM.
We need more information, such as logs, to further triage this issue.

**Comment by anyscalesam** [comment]
@bussrakrkmz can you please attach your full log output so we can look into this further?
