### ISSUE TITLE
[data] Capture Data-internal exceptions

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#40802]
### Description

Currently Data throws all exceptions to the user, both from user-defined code and Data-internal code. Errors are not differentiated, which makes it difficult to understand the error output.

Ideally, we should capture exceptions from user-defined code, throw these as a separate type of error, and match the stacktrace to the original user code. Also, we should improve the error message for Data-internal errors to direct the user to file a GitHub issue.

**Comment by scottjlee** [comment]
Closed by https://github.com/ray-project/ray/pull/43251

**Comment by c21** [comment]
The original PR is reverted. Reopening.
