### ISSUE TITLE
[Core] Legacy memory document will be invoked when "RAY_memory_monitor_refresh_ms" = 0 is not documented.

### ISSUE THREAD

**Issue by kasakun** [ray-project/ray#40873]
### Description

Hi I am using ray 2.2 and I found when I turned off ray memory monitor according to [official doc](https://docs.ray.io/en/releases-2.2.0/ray-core/scheduling/ray-oom-prevention.html). Ray memory monitor still chimes in and kills my jobs.

After digging into it, I found this [PR ](https://github.com/ray-project/ray/pull/29837)intentionally enables legacy memory monitor if that env is set to zero, however this is not documented anywhere in ray 2.2. It is confusing because the doc only mention one env to turn off the feature, but in practice we need another flag "RAY_DISABLE_MEMORY_MONITOR" to turn it off. 

It seems there is another [PR](https://github.com/ray-project/ray/pull/31993) to remove the legacy monitor completely.

Could you please update the 2.2's doc to make it clearer?

### Link

https://docs.ray.io/en/releases-2.2.0/ray-core/scheduling/ray-oom-prevention.html

**Comment by angelinalg** [comment]
Defering to eng to determine final priority. It seems like a P1, to me.

**Comment by anyscalesam** [comment]
Thank you for raising this @kasakun but we typically don't maintain older documentation versions; is this still an issue on latest ray release docs?

**Comment by kasakun** [comment]
> Thank you for raising this @kasakun but we typically don't maintain older documentation versions; is this still an issue on latest ray release docs?

No it isn’t since the legacy monitor is completely removed. We can close the ticket
