### ISSUE TITLE
[core] placement group asan failure

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#40872]
https://buildkite.com/ray-project/oss-ci-build-branch/builds/6720#018b8377-00bc-45d0-9682-81186a71d207/278-806

**Comment by vitsai** [comment]
cc @rkooo567

**Comment by vitsai** [comment]
This is a flaky test that failed on an earlier release run, looks like race to erase element in SchedulePendingPlacementGroups and should not be new, we can fix in next release.

**Comment by anyscalesam** [comment]
@vitsai so that would be target ray29?

**Comment by rkooo567** [comment]
@vitsai has other priorities for 2.9. let's aim for 2.10. I dont think this failure is also that critical (it must be test issue)
