### ISSUE TITLE
Release test deployment_graph_wide_ensemble.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40889]
Release test **deployment_graph_wide_ensemble.aws** failed. See https://buildkite.com/ray-project/release/builds/183#018b8f0b-8acd-4c92-bdcb-3111b518c79e for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 4db6a25ab22f565e6df31d092b3916b3289f38df found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/717

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
@shrekris-anyscale can you please prioritize investigating into the failure of this test?

**Comment by edoakes** [comment]
Was fixed by https://github.com/ray-project/ray/pull/40932

Latest run pass: https://buildkite.com/ray-project/release-tests-branch/builds/2356#018b7f4e-f6db-4eb7-91ea-1945e3081677/undefined-1

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/795#018bb34d-6dd7-4a9a-8c69-6c6ab0b69ba2
