### ISSUE TITLE
[CI] `osx://python/ray/tests:test_state_api_log` is failing/flaky on master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#40901]
- 8b0670e121898a8a6a031c795ad52a404d2b7343 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6756#018b8e75-78f3-4ed5-80a5-e8f5c10c2676)
- d67d0240f29f3e173530bc78096863c546319ba3 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6752#018b8d1e-8533-48fc-ac70-f92ce5e2c353)
- 9febd97d89750338590f955bf960b2a1f0b4f28f FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6747#018b8c1b-b858-4c8f-8d28-497b99933f4b)
- f71b6c348943439d502ce6a620fcb6283a86185b FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6745#018b8be9-708c-4a71-9c84-336a932ebe48)
- 27bfaec22647862c749a206ac119f20c028f7ece FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6738#018b892b-63cf-4fc5-b2a9-3bae2fad8443)
- 93c8f6166d1626f0e988e4f5aa33fb7cdb5fe599 FAILED [Buildkite :mac: :apple: Medium K-Z](https://buildkite.com/ray-project/oss-ci-build-branch/builds/6737#018b8929-a6a3-4c2d-ae13-815c2d0bf255)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-osx://python/ray/tests:test_state_api_log-END
....

**Comment by jjyao** [comment]
It's green now.

<img width="896" alt="Screenshot 2024-01-10 at 9 34 05 AM" src="https://github.com/ray-project/ray/assets/898023/c9f5ccce-a472-4eb5-bbde-eff4ce17b47c">
