### ISSUE TITLE
[RLLib] README needs updating to install gymnasium instead of gym

### ISSUE THREAD

**Issue by chrisyeh96** [ray-project/ray#40910]
### Description

The README for Ray RLLib incorrectly suggests installing `gym` instead of the newer `gymnasium` package

https://github.com/ray-project/ray/blob/master/rllib/README.rst#installation-and-setup

> TensorFlow:
> 
> ```
> $ conda create -n rllib python=3.8
> $ conda activate rllib
> $ pip install "ray[rllib]" tensorflow "gym[atari]" "gym[accept-rom-license]" atari_py
> $ # Run a test job:
> $ rllib train --run APPO --env CartPole-v0
> ```
> 
> PyTorch:
> 
> ```
> $ conda create -n rllib python=3.8
> $ conda activate rllib
> $ pip install "ray[rllib]" torch "gym[atari]" "gym[accept-rom-license]" atari_py
> $ # Run a test job:
> $ rllib train --run APPO --env CartPole-v0 --torch
> ```

Please update the readme installation instructions to include the correct packages.

**Comment by angelinalg** [comment]
Defering to eng to determine final priority. It seems like a P1, to me.
