### ISSUE TITLE
[Core] Can't determine reason for ray failure

### ISSUE THREAD

**Issue by dioptre** [ray-project/ray#40920]
### What happened + What you expected to happen

We use ray serve and fastapi.

Occasionally we get this error:
"didn't find failure cause for task"

This occurs during a ray worker / function task on a ray.get( after a remote( call.

It typically happens after an internet disconnect or a long time and brings down our entire system/api without recovery.

We've had some grpc and auth errors in the recent past that might be related

This is somewhat reproducible if you close your laptop lid for some time and reopen it again.

No error logs are reported in the called function. No exceptions are triggered (I wrapped the called function in a try/except with no output).

This is very worrying. The service should at least die properly so we can restart it.

### Versions / Dependencies

2.7.1

### Reproduction script

TBA

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
@dioptre could you give more details on your setup? Are you running the Ray cluster entirely on your laptop? How are you connecting to the Ray cluster? cc @rkooo567

**Comment by dioptre** [comment]
Have a single machine cluster setup - happens both running ray start or just in process. We have a similar setup on production so its a little worrying.

**Comment by shrekris-anyscale** [comment]
Is your cluster machine the laptop, or is it a separate remote machine that you connect to with the laptop?

**Comment by dioptre** [comment]
Having problems especially on my laptop so far.

**Comment by shrekris-anyscale** [comment]
I see, could you provide a minimal repro script? It's strange that internet connectivity and closing the laptop lid affects the Ray cluster. Ray clusters shouldn't need to connect to the internet.
