### ISSUE TITLE
[Core] Getting the job list from gcs might hang, causing /api/jobs to time out.

### ISSUE THREAD

**Issue by MissiontoMars** [ray-project/ray#40922]
### What happened + What you expected to happen

In our production environment, we have noticed that the /api/jobs endpoint sometimes experiences a 504 timeout, resulting in the inability to load the jobs page on the dashboard. 

We have identified several anomalies in the GCS logs.
```
$cat gcs_server.out |grep -E "all job info|Connected to|Failed to get is_running_tasks" -i
[2023-11-03 10:57:58,133 I 123 123] (gcs_server) gcs_job_manager.cc:149: Getting all job info.
[2023-11-03 10:57:58,134 D 123 123] (gcs_server) core_worker_client_pool.cc:42: Connected to [fdbd:dc03:13:644::21]:0
[2023-11-03 10:59:17,683 W 123 123] (gcs_server) gcs_job_manager.cc:227: Failed to get is_running_tasks from core worker: GrpcUnavailable: RPC Error message: failed to connect to all addresses; RPC Error details: 
[2023-11-03 10:59:17,683 I 123 123] (gcs_server) gcs_job_manager.cc:185: Finished getting all job info.
```
Getting all job info takes about 80s!!

Due to our unique network environment, we have enabled the --min-worker-port=0 --max-worker-port=0 option when starting Ray. This allows the workers to choose their own port for the gRPC server. However, this causes the port for the driver in the job table to remain as 0 because the actual port is not assigned when writing the job information.
https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L1376

II searched through the Ray code repository and it seems that is_running_tasks is not being used. Additionally, we haven't encountered similar issues in our production environment. Therefore, I have removed the code that retrieves is_running_tasks from the driver, and it appears to be working fine.
https://github.com/ray-project/ray/blob/master/src/ray/gcs/gcs_server/gcs_job_manager.cc#L222

### Versions / Dependencies

Ray v2.6

### Reproduction script

1. RAY_BACKEND_LOG_LEVEL=debug ray start --head --include-dashboard=true  --min-worker-port=0  --max-worker-port=0
2. submit a job by job submit cli
3. curl /api/jobs or update jobs tab on dashboard.

### Issue Severity

None

**Comment by MissiontoMars** [comment]
@architkulkarni Could you please help me take a look at this issue? Thank you.

**Comment by architkulkarni** [comment]
@MissiontoMars I think this issue might be related: https://github.com/ray-project/ray/issues/39947 It was fixed in Ray 2.8.  Does the issue persist for you in Ray 2.8?

**Comment by MissiontoMars** [comment]
@architkulkarni I'm afraid these two issues might have different causes. The core issue here is that when using "--min-worker-port=0 --max-worker-port=0", the driver port is always set to 0 when calling NumPendingTasks, which causes the NumPendingTasks to never succeed.

**Comment by MissiontoMars** [comment]
@architkulkarni I have tested with Ray 2.8, and the issue still persists.

**Comment by rynewang** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/46335

**Comment by larrylian** [comment]
Hi, thanks. I will reply to you soon when I'm back.
