### ISSUE TITLE
[Core] ReleaseCpuResourcesFromUnblockedWorker doesn't work for PG CPU resource

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#40925]
### What happened + What you expected to happen

It seems that if I call ray.get inside a task that's running in a placement group, i.e. to wait for other tasks to finish then it doesn't always release the CPU resources back to the placement group for those other tasks to complete. I seem to be able to get it to deadlock this way. I know it doesn't happen outside of placement groups

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by rkooo567** [comment]
should be fixed with virtual cluster
