### ISSUE TITLE
[data] ArrowInvalid error when selecting only a subset of partition columns in read_parquet or similar

### ISSUE THREAD

**Issue by wingkitlee0** [ray-project/ray#40945]
### What happened + What you expected to happen

An error (`pyarrow.lib.ArrowInvalid: Invalid column index to set field.`) occurs under the following conditions:
* reading a partitioned parquet dataset (`read_parquet`, `read_parquet_bulk` etc)
* and using `columns` that does not include all the partition columns

For example, partition columns "x" and "y", and we set columns=["y"]. Pyarrow's ParquetDataset works fine with this combination

Expected: returns a Ray dataset with specified columns without error.

Information:
The error occurs in 
```
 line 463, in _read_fragments
    table = table.set_column(
```
which is inside a for-loop over a list of partition columns.

### Versions / Dependencies

ray nightly: `941abb6ecb (HEAD -> master, upstream/master, origin/master, origin/HEAD) [Data] Test Data code snippets (#40434)`

python 3.11
OS: WSL2, ubuntu 22
pyarrow 12.01

### Reproduction script

```
import pyarrow as pa
import pyarrow.dataset
import ray.data

def main():
    d = {
        "x": [0, 0, 1, 1, 2, 2],
        "y": ["a", "b", "a", "b", "a", "b"],
        "z": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
    }
    table = pa.Table.from_pydict(d)

    pyarrow.dataset.write_dataset(
        table,
        base_dir="example",
        format="parquet",
        partitioning=["x", "y"],
        partitioning_flavor="hive",
    )

    print(table)

    ds = ray.data.read_parquet(
        "example",
        columns=["y", "z"],  # ["x", "y", "z"] would work
    )
    print(ds.take_all())


if __name__ == "__main__":
    main()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@bveeramani to review and aim to merge by EOW.
