### ISSUE TITLE
Release test rllib_learning_tests_es_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40966]
Release test **rllib_learning_tests_es_tf.aws** failed. See https://buildkite.com/ray-project/release/builds/447#018ba3f6-4c3d-4712-8a19-9981cf981b89 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/41297

**Comment by sven1977** [comment]
Closing this issue. Algo has been removed from RLlib.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/9188#018dcfe5-5fb2-4d45-9c13-28d41abbfdc3
