### ISSUE TITLE
Release test rllib_learning_tests_es_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40967]
Release test **rllib_learning_tests_es_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/447#018ba3f9-57cd-4c55-a00a-9233a89e37b9 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/41297

**Comment by sven1977** [comment]
Closing this issue. Algo has been removed from RLlib.
