### ISSUE TITLE
Release test rllib_learning_tests_slateq_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40968]
Release test **rllib_learning_tests_slateq_tf.aws** failed. See https://buildkite.com/ray-project/release/builds/447#018ba413-0e12-4936-9349-b13abd935a83 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
@sven1977 sorry for the spam, let me know if in the future you just want to get one master task for all of these

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/41297

**Comment by sven1977** [comment]
Closing this issue. Algo has been removed from RLlib.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/9188#018dd01b-2baf-49ed-9033-372e508ea7c1
