### ISSUE TITLE
Release test rllib_multi_gpu_with_lstm_learning_tests.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#40973]
Release test **rllib_multi_gpu_with_lstm_learning_tests.aws** failed. See https://buildkite.com/ray-project/release/builds/447#018ba435-b9e7-4572-8187-26e03b9002fc for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
PR in review: https://github.com/ray-project/ray/pull/41297
