### ISSUE TITLE
[rllib] Question regarding twin-Q usage in DDPG

### ISSUE THREAD

**Issue by KarlJosef** [ray-project/ray#4103]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: latest
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
When activating the `twin_q` functionality in DDPG the following loss specific operations are defined when creating the policy graph (see `ActorCriticLoss`):

```
q_t_selected = tf.squeeze(q_t, axis=len(q_t.shape) - 1)
if twin_q:  
    twin_q_t_selected = tf.squeeze(q_t, axis=len(q_t.shape) - 1)  
    q_tp1 = tf.minimum(q_tp1, twin_q_tp1)  
```
In this case `q_t_selected` and `twin_q_t_selected` hold the same operation. Probably `twin_q_t_selected` need to be adjusted the following way:
```
twin_q_t_selected = tf.squeeze(twin_q_t, axis=len(q_t.shape) - 1)  
```

**Comment by ericl** [comment]
Yes, that looks like a bug. cc @joneswong

**Comment by joneswong** [comment]
yes, we must optimize both of the two q-net. twin_q_t should be used here.

**Comment by joneswong** [comment]
I invoked a pr for this bug: #4108
