### ISSUE TITLE
[memory leak] worker can not release all memory after ray job finished

### ISSUE THREAD

**Issue by gtarcoder** [ray-project/ray#41047]
### What happened + What you expected to happen

**what happened:**  
worker does not release all memory after ray job finished.

As below image shows, after ray job finishes, the worker 'cluster-demo-halei-worker-postprocessor-h66jx' still consumes 5.88G of 18.63G memory, but there is only one process '/home/ray/anaconda3/bin/python' which consumes 66.16MB of 18.63GB memory.

<img width="1136" alt="image" src="https://github.com/ray-project/ray/assets/11898942/44ba076b-a5e4-4740-8a95-ebbbb2891658">

seems there is much memory not released. (as the below image shows, these memory are consumed by raylet...)

<img width="1266" alt="image" src="https://github.com/ray-project/ray/assets/11898942/e2fa5a4d-bed0-476e-9b4d-dab6344ed736">

**expected behavior: ** 
after job finishes, only a little memory consumes in worker.

### Versions / Dependencies

ray version 2.7.1

### Reproduction script

`a heavy job`

### Issue Severity

High: It blocks me from completing my task.

**Comment by gtarcoder** [comment]
hi @ericl ， any advice here?

**Comment by z4y1b2** [comment]
Is your issue related to this PR which will be included in 2.9? https://github.com/ray-project/ray/pull/40370

**Comment by anyscalesam** [comment]
Plasma store memory (SHR) is not expected to be released; we allocate upfront and it is reused (roughly 30% of memory alloc). cc @rkooo567
