### ISSUE TITLE
[tune] Implement scikit-learn SearchCV API?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4105]
GridSearchCV and RandomizedSearchCV are APIs that are very popular in the machine learning community. Providing a similar API (like `tune.GridSearchCV` or `tune.SearchCV`) might be good, even as an exercise, to see what Tune is missing for the more general use case.

**Comment by bfortuner** [comment]
+1 Useful for my organization. We're considering using Dask for this purpose.

https://ml.dask.org/hyper-parameter-search.html

**Comment by mslapek** [comment]
I saw it as an interesting feature - so I gave it a try :sunglasses:

**Comment by richardliaw** [comment]
Just to move conversation back here from #6504, there is already some work being done in https://github.com/ray-project/tune-sklearn as an experimental fork and faster iteration.

**Comment by richardliaw** [comment]
See other repo.
