### ISSUE TITLE
[<Ray component: Ray Train>] Support Tensorflow ParameterServerStrategy

### ISSUE THREAD

**Issue by supercocoa** [ray-project/ray#41089]
### Description

Can Ray Support Tensorflow ParameterServerStrategy?

**Comment by matthewdeng** [comment]
Yes, this can be implemented on top of Ray Core, similar to https://docs.ray.io/en/master/ray-core/examples/plot_parameter_server.html

**Comment by supercocoa** [comment]
Can this be implemented inside Ray Train? Like this 「MultiWorkerMirroredStrategy」
