### ISSUE TITLE
[Data] allow increasing DEFAULT_WAIT_FOR_MIN_ACTORS_SEC

### ISSUE THREAD

**Issue by danielgafni** [ray-project/ray#41091]
### Description

The default value of 10 minutes is not enough in some situations (like waiting for a Kubernetes cluster to autoscale GPU nodes). 

Probably should be an option in `DataContext`?

Right now the value is hard-coded and used [here](https://github.com/ray-project/ray/blob/8af874e834f8ae9c2bbfa8a9c76d434781c2048c/python/ray/data/_internal/execution/operators/actor_pool_map_operator.py#L118)

**Comment by c21** [comment]
Hi @danielgafni  - you can directly change the `DEFAULT_WAIT_FOR_MIN_ACTORS_SEC` value in your Python code.

```py
from ray.data._internal.execution.operators import actor_pool_map_operator
actor_pool_map_operator.DEFAULT_WAIT_FOR_MIN_ACTORS_SEC = xxx
```

**Comment by danielgafni** [comment]
Hey, that's exactly what I did. 
However, this doesn't seem like the best UX (or practice). Having dedicated settings would be more discoverable and convenient.

**Comment by c21** [comment]
Yes that make sense, we will add the setting to `DataContext` later on.
