### ISSUE TITLE
[Core] Pydantic 2.5 breaks Ray 2.8 installation

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#41095]
### What happened + What you expected to happen

![image](https://github.com/ray-project/ray/assets/38871737/81216bf6-f91c-417e-bc13-b0ce1958f097)

the new version of pydantic causes an issue that crashes ray cluster creation. Has something to do with dashboard creation. 

### Versions / Dependencies

ray 2.8
pydantic 2.5 
python 3.9 3.10 

### Reproduction script

```
import pydantic

import ray
ray.init()
ray.shutdown()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by shrekris-anyscale** [comment]
For now, I'd recommend using Pydantic 2.4. We're planning on adding Pydantic 2 support in Ray 2.9, so that should fix this issue. See https://github.com/ray-project/ray/issues/38977 for more info.

**Comment by shrekris-anyscale** [comment]
[This change](https://github.com/ray-project/ray/pull/40831) removed the monkeypatch workaround, so this failure shouldn't occur on `master`.

**Comment by aslonnie** [comment]
how did `pydantic==2.5` get installed here?

**Comment by ddelange** [comment]
ref https://github.com/ray-project/ray/pull/40451

**Comment by shrekris-anyscale** [comment]
We've merged the changes to make Ray compatible with Pydantic 2.5+. You can start using Pydantic 2.5+ with Ray 2.9, which should be out at the end of December.

This issue should no longer happen starting in Ray 2.9, so I'll close it.
