### ISSUE TITLE
[core] Node preemption information not surfaced upon actor death

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#41107]
When an actor dies due to its node being preempted, the surfaced error is indistinguishable from any other actor death. Partition the space of actor death errors more finely to surface preemption (retryable death) to the user.

**Comment by Basasuya** [comment]
Hi vitsai, I have some question about how does gcs server judged node being preempted?
if a node is removed / sigterm / heartbeat lost  all means is preempted?
Thx
@vitsai
