### ISSUE TITLE
[Train] Loading preprocessor fails with Ray 2.8 

### ISSUE THREAD

**Issue by n30111** [ray-project/ray#41116]
### What happened + What you expected to happen

Ray saved the preprocessor metadata using `base64` encoding, but in the `FrameworkCheckpoint.get_preprocessor` it tries to load using `hex`, which is not compatible with `base64`.

Metadata encoding link: https://github.com/ray-project/ray/blob/ray-2.8.0/python/ray/data/preprocessor.py#L320

Get preprocessor link: https://github.com/ray-project/ray/blob/ray-2.8.0/python/ray/data/preprocessor.py#L320 

### Versions / Dependencies

Ray 2.8, Python 3.8

### Reproduction script

N/A

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
FrameworkCheckpoints was deprecated. For preprocessing it's recommended to use Ray Data map_batches instead.
