### ISSUE TITLE
[Train] `AWS Error NETWORK_CONNECTION during HeadObject operation: curlCode: 43` during checkpoint reporting

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#41137]
### What happened + What you expected to happen

This pyarrow bug shows up flakily when doing the existence check for this *empty* marker file. This file is used to determine whether all nodes are writing to a shared storage.

The failure happens flakily for s3 storage with the default pyarrow filesystem.

```python
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/session.py", line 587, in new_report
    persisted_checkpoint = self.storage.persist_current_checkpoint(checkpoint)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/storage.py", line 549, in persist_current_checkpoint
    self._check_validation_file()
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/storage.py", line 508, in _check_validation_file
    if not _exists_at_fs_path(fs=self.storage_filesystem, fs_path=valid_file):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/train/_internal/storage.py", line 255, in _exists_at_fs_path
    valid = fs.get_file_info(fs_path)
  File "pyarrow/_fs.pyx", line 571, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: When getting information for key 'euser_w4ej7snhlu6itki2li9gdl5j1k/TorchTrainer_2023-11-14_07-12-43/.validate_storage_marker' in bucket 'endpoints-fine-tuning-artifacts-staging': AWS Error NETWORK_CONNECTION during HeadObject operation: curlCode: 43, A libcurl function was given a bad argument
```

### Versions / Dependencies

2.7, 2.8

### Reproduction script

TODO

### Issue Severity

High: It blocks me from completing my task.

**Comment by justinvyu** [comment]
https://github.com/apache/arrow/issues/35365

**Comment by justinvyu** [comment]
Here's what we tried:
1. Patch the storage context to save the file with some contents. Our hypothesis was the empty file causing some issues.
2. Reinit the filesystem `storage.storage_filesystem = pyarrow.fs.S3FileSystem()`. Our hypothesis was that the pickled version of the pyarrow filesystem from the head node (on AWS) is incompatible on the worker node.
3. Try some different s3 operations on the pyarrow filesystem. Once it fails with the error, running any other commands in the same process (via a debug session) will result in the same error.
4. Use s3fs instead of pyarrow s3. This worked in 5/5 runs, so we can workaround with it.
5. Increasing the max attempts of the pyarrow s3 filesystem, but this just led to the command hanging due to retrying and 
failing with the same error.

**Comment by ykoyfman** [comment]
@justinvyu What version of pyarrow are you seeing this with? We have also been running into this error with pyarrow 11.0-13.0. (Not with Ray train, but other Ray jobs.)

**Comment by justinvyu** [comment]
These experiments were done with the latest version as of 11/14/23 which was pyarrow 14.

@ykoyfman Have you also been seeing that the failure is flaky, but once it happens, every subsequent pyarrow fs call will give the same error?

What other Ray jobs are you running? And do you use pyarrow directly or is pyarrow used implicitly in the implementation of Ray (ex: Ray Data)?

**Comment by ykoyfman** [comment]
> pyarrow 14.

Thanks @justinvyu - this is good to know!

> Have you also been seeing that the failure is flaky, but once it happens, every subsequent pyarrow fs call will give the same error?

Yes, this is the behavior we observed as well.

We have a variety of workloads distributed via Ray actors and tasks and a combination of both direct pyarrow and ray.data  - this error primarily occurs with direct pyarrow access.

**Comment by justinvyu** [comment]
cc @ericl @kouroshHakha

**Comment by justinvyu** [comment]
@EthanMarx Sorry for missing this -- take a look at this section of the user guide: https://docs.ray.io/en/latest/train/user-guides/persistent-storage.html#fsspec-filesystems

**Comment by justinvyu** [comment]
I think this may be fixed in pyarrow 15+ as seen from my investigation here: https://github.com/anyscale/product/issues/25536#issuecomment-2067338008

Closing for now.
