### ISSUE TITLE
[docs infra] column overwrites next column

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#41145]
### Description

The long name doesn't wrap within the boundaries of the column.
<img width="1283" alt="Screenshot 2023-11-14 at 4 33 59 PM" src="https://github.com/ray-project/ray/assets/122562471/1ee30ecd-4bfd-4ff6-9d9f-7bbf2ea19565">

### Link

https://docs.ray.io/en/master/ray-core/api/scheduling.html

**Comment by angelinalg** [comment]
Another example: 
![image (8)](https://github.com/ray-project/ray/assets/122562471/1a69f7c2-f9c8-4ebe-b1fd-92c39f6f01d8)

**Comment by anyscalesam** [comment]
@angelinalg is this truly p0 (it means it's gotta make it into the current target ray release _and_ most likely get in a couple of days if possible into nightly).

in the context of docs basically ASAP. This has been open for 3w with no update still...

**Comment by peytondmurray** [comment]
This issue was opened while the major docs upgrade was completed, so my focus was there. I'll fix it this afternoon.
