### ISSUE TITLE
[rllib] distributed SGD / distributed gradient accumulation

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#4115]
Currently rllib multi-gpu is limited to using the GPUs on a single node. We should integrate https://ray.readthedocs.io/en/latest/distributed_sgd.html to scale out optimization to multiple nodes for large models.

This makes sense to do after https://github.com/ray-project/ray/issues/3816

**Comment by richardliaw** [comment]
Closing this for now because we have a impl that uses torch.distributed. Feel free to reopen if this is wrong..
