### ISSUE TITLE
[CI] `linux://python/ray/data:test_file_based_datasource` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41169]
- 227fe5dba383d2374b91309dd644ae9c1b886b00 FAILED [Buildkite :database: data: arrow 6 tests](https://buildkite.com/ray-project/postmerge/builds/1686#018bd409-1143-4f6a-bb2f-fb5b2dc592c2)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_file_based_datasource-END
....

**Comment by can-anyscale** [comment]
Open this issue for book keeping that I moved the test to flaky state in https://github.com/ray-project/ray/pull/41165

**Comment by bveeramani** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/41171

**Comment by can-anyscale** [comment]
Beautiful!
