### ISSUE TITLE
[CI] `linux://python/ray/data:test_streaming_integration` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41176]
....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_streaming_integration-END
....

**Comment by can-anyscale** [comment]
This test has been marked as flaky for a while. I just open an issue now to track it.

**Comment by c21** [comment]
@Zandew - can you help take a look if anything abnormal for the test recently? Looks like become stable now.

**Comment by anyscalesam** [comment]
Reviewed - next step here Andrew please investigate into the prior flakiness and determine if it's bad test, bad code, or bad infra.

**Comment by Zandew** [comment]
I think it is related to #41258

**Comment by anyscalesam** [comment]
@Zandew what is the next step here? did we confirm root cause is #41258? If so are we going to target fixing the root cause so these tests will be passing in time for the ray29 cherry pick deadline?

**Comment by Zandew** [comment]
> @Zandew what is the next step here? did we confirm root cause is #41258? If so are we going to target fixing the root cause so these tests will be passing in time for the ray29 cherry pick deadline?

It looks like #41461 introduce some other issues but they look simple to fix, just some incompatible args. But #41258 still exists too, and I don't know the root cause for that yet.

**Comment by anyscalesam** [comment]
Any progress here @Zandew?

@can-anyscale  we've failed this correct? Since it's looking bright red in our CI right now.

**Comment by Zandew** [comment]
I haven't made any progress on the root cause. It looks like the recent red is coming from a new pr #41637
