### ISSUE TITLE
[data] Enable ConcurrencyCap backpressure by default

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#41193]
Backpressure master issue: #40754.

ConcurrencyCap backpressure is implemented but not enabled by default. 

We found some issues based on our benchmarks:
* There is no upper bound for the concurrency cap. For the cap has ramped up, it's no longer effective.
* Ramping up can be very slow for some workloads. 
* Configures can probably be simplified.

The plan is to allow setting the multiplier to 1 (so effectively we have a global max concurrency) in 2.9.
In 2.10, we'll allow setting min/max concurrency per operator. and making the initial cap detection smarter.

**Comment by anyscalesam** [comment]
@raulchen how much work left here?

**Comment by raulchen** [comment]
@anyscalesam Still the same as the PR description. I added the size label.

**Comment by raulchen** [comment]
Update: for 2.10, we plan to (1) enable this policy with unlimited cap by default; (2) connect the new `concurrency` parameter to this policy, so users can manually specify concurrency ranges for each operator; (3) also support `concurrency` parameter for task pool-based operators.

**Comment by raulchen** [comment]
closing as done by @c21
