### ISSUE TITLE
[tune] Trial scheduler should allow decreasing metric attribute

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4120]
### Describe the problem
Right now, all the trial schedulers have a `reward_attr` attribute, which is assumed to be increasing. It would be nice if I could use decreasing metric as the scheduling metric.

**Comment by ericl** [comment]
Maybe allow either `minimize_attr` or `maximize_attr` args?

**Comment by richardliaw** [comment]
@hershg will take this
