### ISSUE TITLE
[CI] `linux://:gcs_placement_group_manager_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41215]
- 4fd91439ed015fc419f80f4f1346fd898fc87a83 FAILED [Buildkite :ray: core: cpp ubsan tests](https://buildkite.com/ray-project/postmerge/builds/1705#018bd93c-b9f5-4adc-9a85-acd55427a4e4)
- 473d8f51eb44562fa96d99db9adf41e90402a467 FAILED [Buildkite :ray: core: cpp ubsan tests](https://buildkite.com/ray-project/postmerge/builds/1680#018bd0c9-bed5-4c65-81d3-6b787d940195)
- e51a226a032e654cbe45170f79776da3b12249ce FAILED [Buildkite :ray: core: cpp tests](https://buildkite.com/ray-project/postmerge/builds/1666#018bcf6a-52a4-4cb4-ba3c-e1b95d0e90b6)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://:gcs_placement_group_manager_test-END
....

**Comment by anyscalesam** [comment]
Resolving this as this is showing very green last 2w

**Comment by can-anyscale** [comment]
This one still looks pretty baddd 

<img width="1421" alt="Screenshot 2023-11-20 at 2 33 18 PM" src="https://github.com/ray-project/ray/assets/128072568/fc7b3923-6828-453b-9921-efe236aec4e7">

**Comment by anyscalesam** [comment]
reviewed last week in core sprint review; don't have bandwidth right now but team is still planning to fix this for 29 release. cc @rkooo567 @jjyao @xieus

**Comment by anyscalesam** [comment]
@can-anyscale im doing a search for "gcs_placement_group_manager_test" but nothing is coming up in go/flaky. is this test not in rotation anymore; how can i systematically check which tests are in rotation in buildkite?

**Comment by can-anyscale** [comment]
@anyscalesam look like the test still run in buildkite and stable https://buildkite.com/ray-project/postmerge/builds/2197#018c6f79-6329-46e9-b430-7cbe6a1a28d2/6-267; to find it on buildkite you just need to know its job; i just happen to know this is a core cpp tests.

**Comment by rkooo567** [comment]
I think some of tests that pass 100% of time don't come up
