### ISSUE TITLE
Performance regression for task submission

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#4122]
```
import ray
ray.init()
@ray.remote
def f():
    return None
%timeit result = ray.get([f.remote() for _ in range(10000)])                                                                                                                 
```

current master:
```
6.72 s ± 485 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

0.6.3:
```
5.26 s ± 92.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

0.6.1:
```
5.08 s ± 192 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by pcmoritz** [comment]
before the inline object PR:
```
5.42 s ± 278 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

after the inline object PR:
```
6.2 s ± 402 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So it doesn't seem to make things faster at least.

**Comment by stephanie-wang** [comment]
Ah I'm guessing part of the slowdown from the inline objects PR is that the [call](https://github.com/ray-project/ray/blob/master/src/ray/object_manager/object_manager.cc#L153) to create the inlined object in the local object store is done on the main thread right now, and it is blocking.

**Comment by pcmoritz** [comment]
This was in part fixed by https://github.com/ray-project/ray/pull/4125, but there is more work to be done to speed this up.
