### ISSUE TITLE
[Ray component: Core] How to know if my task is currently executing (not just scheduled)?

### ISSUE THREAD

**Issue by adivekar-utexas** [ray-project/ray#41257]
### Description

It's a simple request which I have not been able to find easily.

I want to know if my task (i.e. either a standalone function annotated with @ray.remote, or a function of an Actor class created with @ray.remote) is running. 

If I run the task 100 times on a cluster of 50 CPUs, 50 of them will be scheduled.
I want to know, at any point, which ones are executing and which ones are scheduled.

I have searched Google a good amount but genuinely cannot find this for some reason.

### Link

Missing documentation in: https://docs.ray.io/en/latest/ray-core/tasks.html

**Comment by jjyao** [comment]
@adivekar-utexas You can see from the Ray dashboard or using https://docs.ray.io/en/latest/ray-observability/reference/api.html
