### ISSUE TITLE
A small modification of ray.data.Dataset.sort()

### ISSUE THREAD

**Issue by veryhannibal** [ray-project/ray#41265]
# Description
I have a suggestion about the ray.data.Dataset.sort() method to meet the requirement of some special computation scenarios. Only some minor modification is need. 
User can specify the boundaries so the dataset will be divided into blocks according to the specified boundaries while sorting.

### 1. Add boundaries parameter to the sort method of ray.data.Dataset :
    def sort(
        self,
        key: Union[str, List[str], None] = None,
        descending: Union[bool, List[bool]] = False,
        boundaries: Optional[list] = None, # Example:[10, 20,30]
    ) :
        sort_key = SortKey(key, descending, boundaries)
        plan = self._plan.with_stage(SortStage(self, sort_key))

        logical_plan = self._logical_plan
        if logical_plan is not None:
            op = Sort(
                logical_plan.dag,
                sort_key=sort_key,
            )
            logical_plan = LogicalPlan(op)
        return Dataset(plan, logical_plan)`

### 2.  Add an attribute named _boundaries to the class SortKey in ray.data._internal.sort :
    class SortKey:
    """SortKey class to convert between different sort args formats."""

        def __init__(
            self,
            key: Optional[Union[str, List[str]]] = None,
            descending: Union[bool, List[bool]] = False,
            boundaries: Optional[list] = None,
        ):
            if key is None:
                key = []
            if isinstance(key, str):
                key = [key]
            if not (isinstance(key, list) and all(isinstance(k, str) for k in key)):
                raise ValueError(
                    f"Key must be a string or a list of strings, but got {key}."
                )
            if isinstance(descending, bool):
                descending = [descending for _ in key]
            elif isinstance(descending, list):
                if len(descending) != len(key):
                    raise ValueError(
                        "Length of `descending` does not match the length of the key."
                    )
                if len(set(descending)) != 1:
                    raise ValueError("Sorting with mixed key orders not supported yet.")
            self._columns = key
            self._descending = descending
            self._boundaries = boundaries
        
        @property
            def boundaries(self):
                return self._boundaries

### 3. The function sort_impl in ray.data._internal.sort:
    def sort_impl(
        blocks: BlockList,
        clear_input_blocks: bool,
        sort_key: SortKey,
        ctx: Optional[TaskContext] = None,
    ) -> Tuple[BlockList, dict]:
        stage_info = {}
        blocks_list = blocks.get_blocks()
        if len(blocks_list) == 0:
            return BlockList([], []), stage_info
    
        num_mappers = len(blocks_list)
        # Use same number of output partitions.
        num_reducers = num_mappers
        # TODO(swang): sample_boundaries could be fused with a previous stage.
        # Determine whether the user has specified boundaries
        if not sort_key.boundaries: 
            boundaries = sample_boundaries(blocks_list, sort_key, num_reducers, ctx)
        else:
            boundaries = [(b, ) for b in sort_key.boundaries]
            num_mappers = len(boundaries) + 1
            num_reducers = num_mappers
        _, ascending = sort_key.to_pandas_sort_args()
        if not ascending:
            boundaries.reverse()
    
        context = DataContext.get_current()
        if context.use_push_based_shuffle:
            sort_op_cls = PushBasedSortOp
        else:
            sort_op_cls = SimpleSortOp
        sort_op = sort_op_cls(map_args=[boundaries, sort_key], reduce_args=[sort_key])
        return sort_op.execute(
            blocks,
            num_reducers,
            clear_input_blocks,
        )

### 4. The function generate_sort_fn in ray.data._internal.planner.sort:
    def generate_sort_fn(
        sort_key: SortKey,
            ) -> AllToAllTransformFn:
            """Generate function to sort blocks by the specified key column or key function."""

        def fn(
            sort_key: SortKey,
            refs: List[RefBundle],
            ctx: TaskContext,
        ) -> Tuple[List[RefBundle], StatsDict]:
            blocks = []
            metadata = []
            for ref_bundle in refs:
                for block, block_metadata in ref_bundle.blocks:
                    blocks.append(block)
                    metadata.append(block_metadata)
            if len(blocks) == 0:
                return (blocks, {})
            sort_key.validate_schema(unify_block_metadata_schema(metadata))
    
            num_mappers = len(blocks)
            # Use same number of output partitions.
            num_outputs = num_mappers
    
            # Sample boundaries for sort key.
            # Determine whether the user has specified boundaries
            if not sort_key.boundaries:
                boundaries = SortTaskSpec.sample_boundaries(blocks, sort_key, num_outputs)
            else:
                boundaries = [(b, ) for b in sort_key.boundaries]
                num_outputs = len(boundaries)  + 1
            _, ascending = sort_key.to_pandas_sort_args()
            if not ascending:
                boundaries.reverse()
            sort_spec = SortTaskSpec(boundaries=boundaries, sort_key=sort_key)
    
            if DataContext.get_current().use_push_based_shuffle:
                scheduler = PushBasedShuffleTaskScheduler(sort_spec)
            else:
                scheduler = PullBasedShuffleTaskScheduler(sort_spec)
    
            return scheduler.execute(refs, num_outputs, ctx)

    # NOTE: use partial function to pass parameters to avoid error like
    # "UnboundLocalError: local variable ... referenced before assignment",
    # because `key` and `descending` variables are reassigned in `fn()`.
    return partial(fn, sort_key)

# Use case

In a multi-party computing or federated learning scenario, the data of multiple parties needs to be aligned, so each participant needs to sort and partition their dataset according to the same rules.
![image](https://github.com/ray-project/ray/assets/43735106/bfd6c139-b3cf-4eb9-b41d-84fdd38731a0)

**Comment by jiwq** [comment]
It's useful for us, can you submit a MR?

**Comment by veryhannibal** [comment]
> It's useful for us, can you submit a PR?

Thanks for your attention and suggestion. I have submitted, may you please review my request, thanks.

**Comment by wingkitlee0** [comment]
This is interesting, as I thought about a related issue/enhancement when working a recent PR #40778 about groupby. 
Use case: When using `groupby` in a partitioned dataset, it's often that group-key is bounded by the partitions (e.g., a time column in a dataset partitioned by date). Since Ray's `groupby` sorts dataset by the group key(s), the ability of specifying the group boundaries is helpful.

**Comment by anyscalesam** [comment]
@veryhannibal thank you for submitting the pr; @stephanie-wang left some comments can you advise on them in the PR so we can than merge and close this ticket?

**Comment by veryhannibal** [comment]
> @veryhannibal thank you for submitting the pr; @stephanie-wang left some comments can you advise on them in the PR so we can than merge and close this ticket?

Thank you for your attention, I will reply to all comments.😁
