### ISSUE TITLE
Ray remote task + fastapi memory leak

### ISSUE THREAD

**Issue by vonsago** [ray-project/ray#41260]
### What happened + What you expected to happen

I started a fastapi app and an interface continuously created remote tasks.

I use `memray` tool get memory leak report:

After 1w+ request "/tasks": 
0x1	56.3 MiB	malloc 1239346	 invocation at /usr/local/lib/python3.10/site-packages/ray/remote_function.py:411

After 2w+ request "/tasks": 
0x27	150.3 MiB	malloc	3198029	invocation at /usr/local/lib/python3.10/site-packages/ray/remote_function.py:411

![image](https://github.com/ray-project/ray/assets/22726829/8e61fa8f-ccaa-4551-88a8-c1b516f6ed70)

![image](https://github.com/ray-project/ray/assets/22726829/e73a7a6a-67e9-45c0-8e09-d4e0db260408)

### Versions / Dependencies

ray version == 2.7.1, and ray cluster run in docker.

### Reproduction script

Here is my fastapi.py
```
@ray.remote
def run_task(entrypoint, tid, metadata):
    entrypoint += f" --job='{json.dumps(metadata)}'"
    cmd = shlex.split(entrypoint)
    logging.info(f"run {cmd}")
    with Popen(args=cmd) as p:
        ...

@app.post("/tasks/")
async def fop_jobs(req: FopReq):
    a = run_fop.options(
        num_cpus=req.entrypoint_num_cpus,
        num_gpus=req.entrypoint_num_gpus,
        runtime_env=req.runtime_env
    ).remote(req.entrypoint, req.tid, req.metadata)
    return req

if __name__ == "__main__":
    uvicorn.run(app, host='0.0.0.0', port=8000)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
What's the `memray` command you ran? Did you monitor the memory of the driver process?

**Comment by vonsago** [comment]
@jjyao I have tried some ways which is `memray run fastapi.py` and `memray run --native fastapi.py`. As you said, I checked the memory of the process through the top command and it is indeed continuing to grow.

**Comment by vonsago** [comment]
I also have the same problem with the ray 2.8.0 version. And these three time points that memory is growing likely to cause this problem?
![image](https://github.com/ray-project/ray/assets/22726829/3173b654-e4d2-4af1-b25c-ae37ae193ee4)
![image](https://github.com/ray-project/ray/assets/22726829/996d4ab9-e6c6-45b8-8288-99d791d58aeb)
![image](https://github.com/ray-project/ray/assets/22726829/1b7dd632-0605-4e51-ac13-db55807d0791)

**Comment by vonsago** [comment]
In order to exclude fastapi factors, I use this test.py has the same problem.

```
import time
import ray
import uuid
import shlex
import json
import uvicorn
import logging
import subprocess

from subprocess import Popen

@ray.remote
def run_fop(entrypoint, submission_id, metadata):
    cmd = shlex.split(entrypoint)
    logging.info(f"run fop pass serve {cmd}")
    with Popen(args=cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) as p:
        ...

runtime_env = {
        "working_dir": "https://git.[somethins]",
        "pip": ["pydantic==2.3.0"],
        "env_vars": {
            "RUN_ENV": "uat"
        }
}


metadata = {
        "biz_metadata": "{\"flow\":\"md5\",\"fop\":\"md5\",\"smid\":\"id\",\"upos_uri\":\"urixxxx\",\"wrk_random\":\"189728\"}",
        "submission_id": "test14"
 }

if __name__ == "__main__":
    s = "sdfas12387461982734619823746198237461982374691283746918273649812763498127634987162349876213496128974619287649817263498126734986213846128976349817263498126394876129837461928374691283746918237469123784691823746918732649182736491823764918273649182736491823764198237649182376419283764192873649128736491873246198237461982374619827364198273469182375610237586123908476192387461928374691823469182736498123649123"
    for i in range(100000):
        a = run_fop.options(
            num_cpus=0.5,
            num_gpus=0,
            runtime_env=runtime_env
            ).remote("python3 -c \"import logging; for i in range(100): logging.info(s)\"", f"tt{i}", metadata)
        print(a)
        # ray.get(a)
        time.sleep(0.05)
```

after about 1 hour:
 607501 root      20   0 14.421g 168.2m  47.8m S  67.7  0.3  59:37.83 /usr/local/bin/python3.10 /usr/local/bin/memray run --native -+

![image](https://github.com/ray-project/ray/assets/22726829/cd308fc9-2f80-4fbf-b04c-08f3e3a29836)
![image](https://github.com/ray-project/ray/assets/22726829/ec4ab8fa-ed4e-4fa6-b4c3-d2bf93c1c3ae)

file detail: [memray-flamegraph-test1.py.633207.html.zip](https://github.com/ray-project/ray/files/13434402/memray-flamegraph-test1.py.633207.html.zip)

**Comment by vonsago** [comment]
I should have found the cause of the leak, I'm trying to verify and fix it. The reason may be that the function release `Disconnect` is not called in [this place](https://github.com/ray-project/ray/blob/master/src/ray/rpc/worker/core_worker_client_pool.cc#L40) after worker exit

**Comment by rkooo567** [comment]
Let us know if this fixes the issue.

**Comment by jjyao** [comment]
@vonsago I was not able to reproduce the memory leak.

Could you run the following `test.py` (same as yours but without runtime env)

```
import time
import ray
import uuid
import shlex
import json
import uvicorn
import logging
import subprocess

from subprocess import Popen

@ray.remote
def run_fop(entrypoint, submission_id, metadata):
    cmd = shlex.split(entrypoint)
    logging.info(f"run fop pass serve {cmd}")
    with Popen(args=cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) as p:
        ...

metadata = {
        "biz_metadata": "{\"flow\":\"md5\",\"fop\":\"md5\",\"smid\":\"id\",\"upos_uri\":\"urixxxx\",\"wrk_random\":\"189728\"}",
        "submission_id": "test14"
}

if __name__ == "__main__":
    s = "sdfas12387461982734619823746198237461982374691283746918273649812763498127634987162349876213496128974619287649817263498126734986213846128976349817263498126394876129837461928374691283746918237469123784691823746918732649182736491823764918273649182736491823764198237649182376419283764192873649128736491873246198237461982374619827364198273469182375610237586123908476192387461928374691823469182736498123649123"
    for i in range(100000000000000):
        a = run_fop.options(
            num_cpus=0.5,
            num_gpus=0,
            ).remote("python3 -c \"import logging; for i in range(100): logging.info(s)\"", f"tt{i}", metadata)
        print(a)
        # ray.get(a)
        time.sleep(0.05)
```

and use `top` to monitor the driver process memory usage and see if it has increasing memory usage. You can do something like `watch -n 5 top -p <driver_pid> -n 1`

**Comment by vonsago** [comment]
@jjyao This is also a point of confusion for me. It is easy to reproduce this problem in version 2.8.0, but in the master branch I need to run fastapi.py and test.py at the same time and maintain the same qps as the total resource amount to reproduce it. But it can be reproduced in a similar way anyway. The key point seems to be options.num_cpus=0.5 instead of 1. For specific phenomena, you can see that ray list workers continue to increase.

I add one debug log at core_worker_pool.cc CoreWorkerClientPool::GetOrConnect `RAY_LOG(DEBUG) << "Connected to " << addr_proto.ip_address() << ":" << addr_proto.port() << " size: " << client_map_.size();`

here is result of build by branch of master.
[2023-11-27 22:30:55,540 D 1182 1217] core_worker_client_pool.cc:42: Connected to 10.23.176.225:10004 size: 1
// ...            10 min interval, size 1 to 1914
[2023-11-27 22:41:54,014 D 1182 1217] core_worker_client_pool.cc:42: Connected to 10.23.176.225:13439 size: 1914

This `client_map_` will continue to grow and will not be released.

At the same time, I also noticed your comment in my code. That was my mistake. I am still looking for a way to let the `idle worker` on the `worker node` notify the `driver worker` on the `head node` that its `idle worker` has exited and destroyed the `client_map_` record to ensure the size.

**Comment by jjyao** [comment]
@vonsago Thanks for the detailed explanation. I checked the code seems we, indeed, don't remove dead workers from `client_map_`.

**Comment by jjyao** [comment]
I have some ideas on how to fix it. Let me put up a PR.

**Comment by jjyao** [comment]
Simpler repro: 

```
import ray

ray.init()

@ray.remote(max_calls=1)
def f():
  pass

while True:
  ray.get(f.remote())
```

**Comment by vonsago** [comment]
@jjyao I found that there is no connection established from idle worker to driver worker. I want to confirm whether this understanding is correct. If so, fixing the problem involves establishing a connection with a client, calling `dissconnect` and then disconnecting the client.

**Comment by jjyao** [comment]
@vonsago the issue is that `disconnect` is not called so `client_map_` keeps increasing.

**Comment by vonsago** [comment]
@jjyao I know it's because of this, but I'm not sure which module calls `disconnect`.

**Comment by jjyao** [comment]
@vonsago I guess it's hard to know which module should call it since you don't know if you still need the connection in the near future. Instead I have #41535 that tries to fix it in another way. Could you try it out and see if it fixes the memory leak of your workload. Let me know which python version you are using, I can give you the corresponding wheel.

**Comment by jjyao** [comment]
@vonsago can you try this wheel (https://ray-ci-artifact-pr-public.s3.amazonaws.com/cbd696e980a700a88799aea8e43cde67cdc25431/tmp/artifacts/.whl/.whl/ray-3.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl) and see if it fixes the leak?

**Comment by vonsago** [comment]
@jjyao Thank you for solving the problem quickly. I will try to verify your solution later. My solution: when idle receives the pushtask request, it establishes a connection and requests the driver worker to release the connection when the idle exits. [#41395](https://github.com/ray-project/ray/pull/41395). I wonder if this approach is more concise.

**Comment by jjyao** [comment]
@vonsago Just checking to see if you get a chance to verify whether my PR fixes the memory leak?

**Comment by vonsago** [comment]
@jjyao Your PR works fine, it can fix the memory leak
