### ISSUE TITLE
[data] Fix data arrow nightly tests

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41275]
### What happened + What you expected to happen

Fix data arrow nightly releases before ray 2.9 release. Feel free to close if this has been duplicated, tracked somewhere else

### Versions / Dependencies

master

### Reproduction script

CI

### Issue Severity

High: It blocks me from completing my task.

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_backpressure_policies-END
....

**Comment by bveeramani** [comment]
Duplicate of #41139
