### ISSUE TITLE
[Jobs] OpenAPI doc for `submit_job` is missing the `entrypoint_memory` argument

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#41277]
### Description

The OpenAPI doc for the Job REST API https://docs.ray.io/en/latest/cluster/running-applications/job-submission/api.html#/paths/~1api~1jobs/post is missing the field `entrypoint_memory` https://docs.ray.io/en/latest/cluster/running-applications/job-submission/doc/ray.job_submission.JobSubmissionClient.submit_job.html#ray-job-submission-jobsubmissionclient-submit-job which was added in Ray 2.8.0.

**Comment by RaffaGonzo** [comment]
I can take this on, I just want to clarify, is this an issue with just the documentation or is this also a code issue in the API

**Comment by RaffaGonzo** [comment]
@architkulkarni Ok fantastic, I fixed it in the openapi.yml file but when I went to do the PR I got 403 permission denied, I think that means I'm not part of the organization, so I was wondering how I could be added, of if there's a way around this?

**Comment by architkulkarni** [comment]
Can you add more details about what command you ran, the error you got, and maybe a screenshot? Anyone should be able to submit a PR even if they're not in the organization.

**Comment by architkulkarni** [comment]
Oh, you need to fork the repo first, did you do that? You can't make branches on our repo, you'll need to do it on your fork.  But you can still make a PR from your fork to our repo.

**Comment by RaffaGonzo** [comment]
@architkulkarni I did fork it I just hadn't realized I needed to push to the fork. it should be good to go now though, it just needs a review.

**Comment by architkulkarni** [comment]
Ah makes sense, thanks! If you'd like to open a PR to update the contributor docs, that would also be appreciated, we want those to be as clear as possible. I think other people will run into the same issue
