### ISSUE TITLE
Problem with the webUI for Ray cluster

### ISSUE THREAD

**Issue by Deepak3994** [ray-project/ray#4128]
Hi,

I have a problem when i launch the webUI for the ray cluster. I am not able to view the cpu utilization. I have attached the images below, if anyone has come across this issue kindly help.
![cluster-usage](https://user-images.githubusercontent.com/20994657/53230970-f1792000-36ad-11e9-9451-aa25c426a319.png)
![cpu-usage](https://user-images.githubusercontent.com/20994657/53230971-f1792000-36ad-11e9-8249-9f2329f4d914.png)
![task-duration](https://user-images.githubusercontent.com/20994657/53230973-f1792000-36ad-11e9-8fc6-1063c48af632.png)

**Comment by Deepak3994** [comment]
Hi,

Do anyone knows why i am getting that "Figure object is not iterable" when i try to check the CPU utilization.

**Comment by robertnishihara** [comment]
Closing because the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.

**Comment by Deepak3994** [comment]
Hi @robertnishihara 

I am still facing the same eroor, in the web-UI. Does the new UI code works properly on Jupyter notebook?

I get the bellow error,
![task-duration-error](https://user-images.githubusercontent.com/20994657/53780636-5133be80-3f2b-11e9-8f32-ea1945b45560.png)

Kindly help

**Comment by robertnishihara** [comment]
Hi @Deepak3994, this part of the UI has been deprecated in the latest release (which is about to happen (0.6.4)). The most important part of the UI is the timeline, which you can use by following the instructions at https://ray.readthedocs.io/en/latest/user-profiling.html#visualizing-tasks-in-the-ray-timeline.
