### ISSUE TITLE
[Dashboard] Can't download the task timeline when use url path as the dashboard entry point

### ISSUE THREAD

**Issue by jiwq** [ray-project/ray#41292]
### What happened + What you expected to happen

Can't download the task timeline when use url path as the dashboard entry point. 

Example:
- Dashboard URL: http://example.com/ray/dashboard/
- Task Timeline Download URL:
    - Expected: http://example.com/ray/dashboard/api/v0/tasks/timeline?download=1&job_id=${jobId}
    - Actual: http://example.com/api/v0/tasks/timeline?download=1&job_id=${jobId}

### Versions / Dependencies

Ray versions: 2.8.0, 2.7.1 and so on. Not related to Python, OS and other libraries.

### Reproduction script

Should config the url path request rules in your web server or load balancer. 

NGINX Example:
```
Server {
    listen: 8090
    server_name: example.com
    
    location /ray/dashboard/ {
        proxy_pass  http://x.x.x.x:8265
    }
}
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
PR is out @alanwguo can you review?
