### ISSUE TITLE
[rllib] How to train IMPALA on multiple environment?

### ISSUE THREAD

**Issue by jincongho** [ray-project/ray#4130]
As title, how do I train IMPALA on multiple Atari environment multi-task as in the original paper?

(Not sure if here's the place to ask question.)

**Comment by ericl** [comment]
Hey @jincongho, you can make a multi-task env like so: https://ray.readthedocs.io/en/latest/rllib-env.html#configuring-environments

**Comment by jincongho** [comment]
Thanks! I'll try this and get back.

**Comment by jincongho** [comment]
Hi, sorry to bother again. How can I report multiple episode reward for each environment after each iteration? Currently, I can only get this:

    episode_reward_max: 2.0
    episode_reward_mean: -1.2727272727272727
    episode_reward_min: -21.0

Which module should I put this feature? policy evaluator?

**Comment by jincongho** [comment]
Also, how can the multitask generator change task (eg: stop certain environment) according to iteration, performance, etc?

**Comment by ericl** [comment]
Check these out:
https://ray.readthedocs.io/en/latest/rllib-training.html#callbacks-and-custom-metrics
https://ray.readthedocs.io/en/latest/rllib-training.html#example-curriculum-learning

You'll have to report them as custom metrics since the default ones don't make sense.

**Comment by ericl** [comment]
> Also, how can the multitask generator change task (eg: stop certain environment) according to iteration, performance, etc?

For this one, I think you can have a `on_train_result` callback that updates the envs (similar to the curriculum learning examples -- putting the two together).

**Comment by jincongho** [comment]
So to reiterate, my goal is to reimplement IMPALA original paper: train a single network on multiple environments in parallel and report metrics for each environments. Does code below exactly the same as the paper?

```
class MultiTaskEnv(gym.Env): 
    def __init__(self, env_config):
        if env_config.worker_index%2==0:
          self.env = gym.make("BreakoutNoFrameskip-v4", full_action_space=True)
          self.name= "BreakoutNoFrameskip-v4"
        else:
          self.env = gym.make('PongNoFrameskip-v4', full_action_space=True)
          self.name= 'PongNoFrameskip-v4'
        self.env = wrap_deepmind(self.env)
        self.action_space = self.env.action_space
        self.observation_space = self.env.observation_space

    def reset(self):
        return self.env.reset()
    
    def step(self, action):
        return self.env.step(action)

def on_episode_end(info):
    episode = info["episode"]
    episode.custom_metrics[info['env'].vector_env.envs[0].name] = episode.total_reward

tune.run_experiments({
    "multitask": {
        "run": "IMPALA",
        "env": "multitask",
        "stop": {"timesteps_total": 2 * 2000000},
        "config": {
            "num_gpus": 1,
            "num_workers": 6,
            "num_envs_per_worker": 10,
            "callbacks": {
                "on_episode_end" : tune.function(on_episode_end),
            }
        }
    },
})
```

**Comment by ericl** [comment]
That code looks correct to me, though I don't know if it's an exact match for the paper. Maybe ask the authors?

**Comment by jincongho** [comment]
Ok, thanks for all the advice =)

**Comment by jincongho** [comment]
Hi, I was having problem with the multitask performance logging with `custom_metrics`. I tried a lot of times using function below:
```
def on_episode_end(info):
    episode = info["episode"]
    episode.custom_metrics[info['env'].vector_env.envs[0].name] = episode.total_reward
```
But the metrics always different from the real reward. At the end, I tracked down the issue at `sampler.py` line 543:
```
def _fetch_atari_metrics(base_env):
    """Atari games have multiple logical episodes, one per life.

    However for metrics reporting we count full episodes all lives included.
    """
    unwrapped = base_env.get_unwrapped()
    if not unwrapped:
        return None
    atari_out = []
    for u in unwrapped:
        monitor = get_wrapper_by_cls(u, MonitorEnv)
        if not monitor:
            return None
        for eps_rew, eps_len in monitor.next_episode_results():
            atari_out.append(RolloutMetrics(eps_len, eps_rew, {}, {monitor.spec.id: eps_rew}))
    return atari_out
```
Because each episode can be split into multiple Rollout, `episode.total_reward` won't be accurate in Atari environment. Also, at line 344:
```
atari_metrics = _fetch_atari_metrics(base_env)
if atari_metrics is not None:
    for m in atari_metrics:
        outputs.append(
            m._replace(custom_metrics=episode.custom_metrics))
```
Multiple atari rollout from same episode will use same `custom_metrics`. I don't see any way to split the reward manually in `on_episode_end`. I was forced to change the code in the `sampler.py`:
```
for m in atari_metrics:
    outputs.append( m)
...
for eps_rew, eps_len in monitor.next_episode_results():
    atari_out.append(RolloutMetrics(eps_len, eps_rew, {}, {monitor.spec.id: eps_rew}))
```

This comment is to help anyone attempting to do multitask. I'm not sure whether and how the code maintainer would like to add this to the library.
