### ISSUE TITLE
[doc][Train] `LightningTrainer` migration guide should go over how to migrate `LightningCheckpoint` usage

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#41321]
### Description

We do not show how to load a generic checkpoint saved by the default lightning report callback.

### Link

https://docs.ray.io/en/latest/train/getting-started-pytorch-lightning.html#lightningtrainer-migration-guide

**Comment by anyscalesam** [comment]
@justinvyu are we trying to get this in for ray29?

**Comment by justinvyu** [comment]
Yeah I'm doing it now

**Comment by matthewdeng** [comment]
Oh btw we are removing the migration guides in https://github.com/ray-project/ray/pull/41276

**Comment by justinvyu** [comment]
Oh ok I can close this if so. Some users still seemed to be migrating, do you think it makes sense to keep for 1 more release?

**Comment by matthewdeng** [comment]
Oh I think we can just point them to 2.8 docs... but I guess it would be missing this 🙉
