### ISSUE TITLE
[rllib] data shuffle in ppo does not work 

### ISSUE THREAD

**Issue by linshuxi** [ray-project/ray#41332]
### What happened + What you expected to happen

data shuffle in ppo does not work

### Versions / Dependencies

2.8.0

### Reproduction script

data shuffle in ppo does not work

### Issue Severity

None

**Comment by anyscalesam** [comment]
@linshuxi can you supply a repro script and error output; there's not enough information in this ticket.

**Comment by anyscalesam** [comment]
Closing - @linshuxi please reopen once you've provided the above.
