### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by birdmw-launch** [ray-project/ray#4136]
Fresh install on latest VirtualBox
Linux Ubuntu 18.04
Anaconda5 python 3.6.8

libgcc_s.so.1 must be installed for pthread_cancel to work
Fatal Python error: Aborted

Aborted (core dumped)
(base) mbird@mbird-VirtualBox:~/Desktop/mancala$

===

Tried conda install libgcc

tried sudo apt-get install libgcc

tried sudo apt-get install gcc

tried sudo apt-get install build-essentials

tried update & upgrade

**Comment by elgalu** [comment]
did you fix it?
