### ISSUE TITLE
[Doc] Contributor guide makes no mention of forking the repo

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#41402]
To contribute to Ray, the user first needs to fork the repository.  If they try to directly push a branch to the main repo instead of their fork, they will encounter a 403 permission denied error.

However, "fork" isn't mentioned anywhere in the contributor guide https://docs.ray.io/en/latest/ray-contribute/getting-involved.html.  Right now it's only mentioned in a separate page linked from one of the steps https://docs.ray.io/en/latest/ray-contribute/development.html#clone-the-repository, and even there it's a bit buried.

We should make it clear that the first step is to fork the Ray repository.

_Originally posted by @architkulkarni in https://github.com/ray-project/ray/issues/41277#issuecomment-1828352187_

**Comment by justina777** [comment]
Hi @architkulkarni , I updated the doc and submitted a MR. Could you please review it?
