### ISSUE TITLE
[<Ray component: Ray data>]  OOM for the repartition

### ISSUE THREAD

**Issue by Bye-legumes** [ray-project/ray#41415]
### What happened
When Ray reads a large data (>2G) and performs the repartition operation, it needs at least 20GB of memory for this task. Each worker will use 2GB of memory.
```
doc_ds: Dataset = ray.data.read_parquet("hdfs://sebmc4:9900/msmarco2/msmarco_parquet/msmarco_doc_17")
doc_ds = doc_ds.repartition(1000)
doc_ds = doc_ds.sort(key = 'docid')
``` 
![tmp](https://github.com/ray-project/ray/assets/121425509/5f378704-7206-4a78-bb5f-cb600ed4a155)

### What I expected
Suppose the data is 2GB. If there are more than 10 blocks (workers) for the repartition operation, the memory used in each worker will be less than 200M.

### DataSet
Data set is from 
https://msmarco.z22.web.core.windows.net/msmarcoranking/msmarco-docs.tsv.gz
Unzip the file and load the data locally or from HDFS.
modify line in attachment to change the data path.
```
doc_ds: Dataset = ray.data.read_parquet("hdfs://sebmc4:9900/msmarco2/msmarco_doc_17")

```

### Versions / Dependencies

2.8.0

### Reproduction script
[sort_bug.txt](https://github.com/ray-project/ray/files/13493026/sort_bug.txt)

### Issue Severity

None

**Comment by anyscalesam** [comment]
@Bye-legumes can you provide the full code, specifically how you're materializing and reading in the data?

**Comment by Bye-legumes** [comment]
I just add the full code and rerun the test with larger mermoy. My data is only 2GB, but the memory spill is 130GB from the log from raylet.
![tmp](https://github.com/ray-project/ray/assets/121425509/4ba71664-9a53-4977-bf3c-0313be80715a)

![tmp](https://github.com/ray-project/ray/assets/121425509/3fc7ef1f-3cc2-481f-bea1-618b167eb569)

**Comment by raulchen** [comment]
`repartition` api is not optimized with streaming execution yet. All data will be loaded memory. If your purpose is to change the number of rows in each block, a workaround would be using `map_batches(lambda x: x, batch_size=N)`

**Comment by Bye-legumes** [comment]
close
