### ISSUE TITLE
[core][FT] Redis client does not redirect to new shard upon receiving MOVED

### ISSUE THREAD

**Issue by vitsai** [ray-project/ray#41416]
A MOVED error indicates that the specified key should map to a different node. To find that key, the client should follow the MOVED error and redirect the request to the new node.

**Comment by architkulkarni** [comment]
Discussed offline, not a release blocker.

**Comment by anyscalesam** [comment]
@jjyao was this abandoned; still relevant to pick up and close out?

**Comment by jjyao** [comment]
The original issue has been fixed by #42040
