### ISSUE TITLE
[Serve] Serving multiple Diffusers models on one GPU leads to OOM 

### ISSUE THREAD

**Issue by tomchify** [ray-project/ray#41432]
### What happened + What you expected to happen

Hi. I’m trying to run multiple Diffusers models for inference on one GPU but am hitting OOM issues.

I tried to modify the Stable Diffusion and FastAPI tutorial ([Serving a Stable Diffusion Model — Ray 2.8.0](https://docs.ray.io/en/latest/serve/tutorials/stable-diffusion.html)) to be able to serve both SD XL 1.0 and Kandinsky 2.2. The code is below.

1. The bug:
Unfortunately, when I start ray serve (serve run serve_oom_test:entrypoint &), inference tasks complete for one model (either one), but when I make request to the other model after that, it crashes with OOM (on a Nvidia 3090 24gb). The stable_diffusion_xl_1_0 deployment doesn’t release memory, and neither does the kandinsky.

2. Expected behavior:
I should be able to make api request to this server, alternating between SD XL and Kandinsky and whichever deployment/model is not in use should be released from memory to prevent OOM.

Could anyone help point me at the correct way to release memory from @serve.deployment environments, with a composition of models? I tried to make some actors with the @ray.remote syntax instead, but all the ways I tried crashed, so not sure what to do.

The code below can be saved to serve_oom_test.py. Then run with:
serve run serve_oom_test:entrypoint &
and then make a get request to that server at /run_tasks_test

### Versions / Dependencies

ray                       2.8.0
diffusers                 0.22.0.dev0
fastapi                   0.104.0
Python 3.10.13
Ubuntu

### Reproduction script

```
from fastapi import FastAPI
from fastapi.responses import Response
import torch
from ray import serve
from ray.serve.handle import DeploymentHandle

app = FastAPI()


@serve.deployment(
    ray_actor_options={"num_cpus": 0, "num_gpus": 0},
    autoscaling_config={"min_replicas": 0, "max_replicas": 1},
)
class TextToImage:
    def __init__(
        self,
        stable_diffusion_xl_1_0_model_handle,
        kandinsky_2_2_model_handle,
    ):
        self.stable_diffusion_xl_1_0: DeploymentHandle = (
            stable_diffusion_xl_1_0_model_handle.options(
                use_new_handle_api=True,
            )
        )
        self.kandinsky_2_2: DeploymentHandle = kandinsky_2_2_model_handle.options(
            use_new_handle_api=True,
        )

    async def generate_for_task(self, task: any):
        inputs = task.get("inputs")
        ai_model = inputs.get("ai_model", "")

        if ai_model == "stabilityai/stable-diffusion-xl-base-1.0":
            output = await self.stable_diffusion_xl_1_0.generate_for_task.remote(task)
        elif ai_model == "kandinsky-2-2":
            output = await self.kandinsky_2_2.generate_for_task.remote(task)

        print("TextToImage.generate_for_task output", output)
        return output


@serve.deployment(
    ray_actor_options={"num_gpus": 1, "num_cpus": 0},
    autoscaling_config={"min_replicas": 0, "max_replicas": 1},
)
class StableDiffusionXL_1_0:
    def __init__(
        self,
    ):
        from diffusers import DiffusionPipeline, AutoencoderKL

        vae = AutoencoderKL.from_pretrained(
            "madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16
        )
        self.pipe = DiffusionPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            vae=vae,
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True,
        )
        self.pipe = self.pipe.to("cuda")

        self.refiner = DiffusionPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-refiner-1.0",
            text_encoder_2=self.pipe.text_encoder_2,
            vae=self.pipe.vae,
            torch_dtype=torch.float16,
            use_safetensors=True,
            variant="fp16",
        )
        self.refiner = self.refiner.to("cuda")

    async def generate_for_task(
        self,
        task: any,
    ):
        # extracting pipe inputs from task hidden here, like prompt = task.get("prompt")...
        prompt = "Test prompt"
        neg_prompt = "low quality"
        num_inference_steps = 25
        guidance_scale = 7.5
        width = 1024
        height = 1024
        image = self.pipe(
            prompt,
            num_images_per_prompt=1,
            negative_prompt=neg_prompt,
            num_inference_steps=int(num_inference_steps),
            guidance_scale=guidance_scale,
            width=width,
            height=height,
        ).images[0]
        return image


@serve.deployment(
    ray_actor_options={"num_gpus": 1, "num_cpus": 0},
    autoscaling_config={"min_replicas": 0, "max_replicas": 1},
)
class Kandinsky_2_2:
    def __init__(
        self,
    ):
        from diffusers import KandinskyV22PriorPipeline, KandinskyV22Pipeline

        self.pipe_prior = KandinskyV22PriorPipeline.from_pretrained(
            "kandinsky-community/kandinsky-2-2-prior", torch_dtype=torch.float16
        )
        self.t2i_pipe = KandinskyV22Pipeline.from_pretrained(
            "kandinsky-community/kandinsky-2-2-decoder", torch_dtype=torch.float16
        )
        self.pipe_prior = self.pipe_prior.to("cuda")
        self.t2i_pipe = self.t2i_pipe.to("cuda")

    async def generate_for_task(self, task: any):
        prompt = "Test prompt"
        neg_prompt = "low quality"
        num_inference_steps = 25
        guidance_scale = 7.5
        width = 1024
        height = 1024
        generator = torch.Generator(device="cuda")
        results = self.pipe_prior(prompt, neg_prompt, generator=generator)
        image_embeds, negative_image_embeds = results.to_tuple()
        image = self.t2i_pipe(
            image_embeds=image_embeds,
            negative_image_embeds=negative_image_embeds,
            num_inference_steps=num_inference_steps,
            generator=generator,
            height=height,
            width=width,
        ).images[0]
        return image


@serve.deployment(num_replicas=1)
@serve.ingress(app)
class APIIngress:
    def __init__(self, text_to_image_model_handle: DeploymentHandle):
        self.text_to_image: DeploymentHandle = text_to_image_model_handle.options(
            use_new_handle_api=True
        )

    @app.get(
        "/run_tasks_test",
        responses={200: {"content": {"text/plain": {}}}},
        response_class=Response,
    )
    async def generate(self):
        # task = get_task(task_id)
        sd_xl_task = {
            "inputs": {
                "ai_model": "stabilityai/stable-diffusion-xl-base-1.0",
                # other inputs...
            }
        }
        kandinsky_task = {
            "inputs": {
                "ai_model": "kandinsky-2-2",
                # other inputs...
            }
        }

        output = await self.text_to_image.generate_for_task.remote(sd_xl_task)
        output = await self.text_to_image.generate_for_task.remote(kandinsky_task)
        output = await self.text_to_image.generate_for_task.remote(sd_xl_task)
        output = await self.text_to_image.generate_for_task.remote(kandinsky_task)
        return Response(content="test success", media_type="text/plain")


sdxl_responder = StableDiffusionXL_1_0.bind()
kandinsky_2_2 = Kandinsky_2_2.bind()
t2i_responder = TextToImage.bind(sdxl_responder, kandinsky_2_2)


entrypoint = APIIngress.bind(
    t2i_responder,
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by tomchify** [comment]
FYI: this is the console log I see after trying to run one deployment after a different deployment on the same server:

(ServeReplica:default:APIIngress pid=1346403) mark_task_as_started text-to-image__e67367c330dff62d6418ccab51afc903
(ServeController pid=1346323) INFO 2023-11-29 20:49:22,491 controller 1346323 deployment_state.py:1481 - Autoscaling replicas for deployment TextToImage in application default from 0 to 1. Current ongoing requests: [], current handle queued queries: 1.
(ServeController pid=1346323) INFO 2023-11-29 20:49:22,495 controller 1346323 deployment_state.py:1668 - Adding 1 replica to deployment TextToImage in application 'default'.
(raylet) E1129 20:49:22.899110778 1346720 thread_manager.cc:42]       Could not create grpc_sync_server worker-thread
(raylet) E1129 20:49:22.899130657 1346720 thread_manager.cc:145]      assertion failed: worker->created()
(raylet) *** SIGABRT received at time=1701290962 on cpu 5 ***
(raylet) PC: @     0x7f16772d400b  (unknown)  raise
(raylet)     @     0x7f16775f1420  (unknown)  (unknown)
(raylet)     @     0x7f167624ac68        144  grpc::Server::Start()
(raylet)     @     0x7f1676251c71        288  grpc::ServerBuilder::BuildAndStart()
(raylet)     @     0x7f1676123a22        560  ray::rpc::GrpcServer::Run()
(raylet)     @     0x7f1675e84f98        960  ray::core::CoreWorker::CoreWorker()
(raylet)     @     0x7f1675e8b447        624  ray::core::CoreWorkerProcessImpl::CoreWorkerProcessImpl()
(raylet)     @     0x7f1675e8c54f         80  ray::core::CoreWorkerProcess::Initialize()
(raylet)     @     0x7f1675d4ba1f       2016  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
(raylet)     @     0x7f1675d4ccc9         48  __pyx_tp_new_3ray_7_raylet_CoreWorker()
(raylet)     @           0x4f6083  (unknown)  _PyObject_MakeTpCall
(raylet)     @           0x740ce0  (unknown)  (unknown)
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361: *** SIGABRT received at time=1701290962 on cpu 5 ***
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361: PC: @     0x7f16772d400b  (unknown)  raise
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f16775f1420  (unknown)  (unknown)
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f167624ac68        144  grpc::Server::Start()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1676251c71        288  grpc::ServerBuilder::BuildAndStart()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1676123a22        560  ray::rpc::GrpcServer::Run()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1675e84f98        960  ray::core::CoreWorker::CoreWorker()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1675e8b447        624  ray::core::CoreWorkerProcessImpl::CoreWorkerProcessImpl()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1675e8c54f         80  ray::core::CoreWorkerProcess::Initialize()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1675d4ba1f       2016  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @     0x7f1675d4ccc9         48  __pyx_tp_new_3ray_7_raylet_CoreWorker()
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @           0x4f6083  (unknown)  _PyObject_MakeTpCall
(raylet) [2023-11-29 20:49:22,911 E 1346720 1346720] logging.cc:361:     @           0x740ce0  (unknown)  (unknown)
(raylet) Fatal Python error: Aborted
(raylet)
(raylet) Stack (most recent call first):
(raylet)   File "/home/user/wrkai-vastai/.env/lib/python3.10/site-packages/ray/_private/worker.py", line 2284 in connect
(raylet)   File "/home/user/wrkai-vastai/.env/lib/python3.10/site-packages/ray/_private/workers/default_worker.py", line 247 in <module>
(raylet)
(raylet) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, uvloop.loop, ray._raylet, charset_normalizer.md (total: 9)
(ServeController pid=1346323) WARNING 2023-11-29 20:49:52,536 controller 1346323 deployment_state.py:1974 - Deployment 'TextToImage' in application 'default' has 1 replicas that have taken more than 30s to be scheduled. This may be due to waiting for the cluster to auto-scale or for a runtime environment to be installed. Resources required for each replica: {}, total resources available: {}. Use `ray status` for more details.

**Comment by pringwong** [comment]
When you define an actor class using ray_actor_options={"num_gpus": 1 "num_cpus": 0},  the actor created from this class must have one GPU reserved for it for the duration of the actor's lifetime. Since you have only one GPU, you will only be able to create one such actor. 

In Ray's internal implementation, it seems that the GPU card and memory occupation are applied using num_gpus, so you can set the num_gpus to 0.5, so that in the case of only 1 GPU card, the application can be successful, so as to avoid the log problem you sent above. However, you should note that 0.5 cards is not enough to load your model, you need to initialize your model at each call and empty your video memory usage at the end, which can be done by (for example):

```
del self.pipe
del self.refiner
gc.collect()
torch.cuda.empty_cache()
```

**Comment by tomchify** [comment]
Thank for that context Pring. So currently Ray Serve won't be able to actually run multiple models on one GPU, keeping the last one in memory unless there is memory pressure, is that correct?

**Comment by shrekris-anyscale** [comment]
Ray Serve doesn't do any physical memory isolation itself. The `num_gpus` is used a logic resource to determine where to schedule Ray tasks and actors (such as the deployment replica). Setting `num_gpus=0.5` on your replica tells Ray that it can schedule 2 replicas on a node with 1 GPU. However, it's the replicas' responsibilities ensure that they don't consume too much memory and trigger an OOM.

**Comment by pringwong** [comment]
> So currently Ray Serve won't be able to actually run multiple models on one GPU, keeping the last one in memory unless there is memory pressure, is that correct?

If the sum of required memory for all models does not exceed the memory of 1 GPU, you can run multiple models on one GPU in Ray Serve without releasing memory of any model.

> Or is it possible to keep a variable of the last model used, and make remote calls to delete the pipes from unused models?
It's possible to do that. At least, it can complete your task.

**Comment by shrekris-anyscale** [comment]
> Ray Serve doesn't do any physical memory isolation itself.

I was a little off about this– it turns out Ray does provide _some_ physical isolation for GPUs. Ray automatically sets the `CUDA_VISIBLE_DEVICES` env var when an actor sets `num_gpus` to attempt to limit which GPUs the actor can access. If actors are using fractional GPUs, then Ray will attempt to pack the actors into the same GPU before moving onto another GPU. See [these docs](https://docs.ray.io/en/releases-2.8.0/ray-core/tasks/using-ray-with-gpus.html#using-gpus-in-tasks-and-actors) for more info.

If multiple actors are packed into the same GPU, it's still their responsibility to make sure that the GPU memory doesn't overflow.

**Comment by shrekris-anyscale** [comment]
@tomchify are you still running into issues? Is there anything we can help with?

**Comment by shrekris-anyscale** [comment]
Since there's no further action items for this issue, I'll close it. @tomchify Please feel free to reopen it if we haven't addressed your concerns fully.
