### ISSUE TITLE
`len(object_id)` should raise an exception.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4143]
```python
x_id = ray.put(1)
print(len(x_id))  # '20'
```

Instead of returning `20`, this should raise an exception. If someone is calling `len` on a `ray.ObjectID` it is almost certainly a bug (in particular, they think that a remote function is returning a list of object IDs, but in fact it is returning 1 object ID.

**Comment by hpandeycodeit** [comment]
@robertnishihara I will do it.
