### ISSUE TITLE
[CI] The git hook is invalid if the project location changed

### ISSUE THREAD

**Issue by jiwq** [ray-project/ray#41435]
### Description

In the ray project, we used the `setup_hooks.sh` to create the symbolic links to the relative hook script and these links used the absolute path, if the project location changed will cause can't find the real files.

Recommend to replace with the relative path.

### Use case

case 1: 
In ray project root dir, exec `sh setup_hook.sh`

case 2: 
exec `sh {PATH_TO_RAY_PROJECT}/setup_hook.sh`

**Comment by anyscalesam** [comment]
This seems like a good idea to do; @can-anyscale @aslonnie can y'all review @jiwq 's PR please?
