### ISSUE TITLE
Data - better error messaging

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#41455]
### Description

Specifically for:

- streaming_generator()
- map() / map_batches()
    - CUJ user was using a map function with an error. The output stack trace is very long, and it's hard to find the root error.
- read_parquet() / read_images()
    - CUJ user tried reading parquet files with read_images, the error shown is: `ValueError: No input files found to read. Please double check that 'file_extensions' field is set properly.`. This may be confusing to the user because the input files do exist, they are just not found because `file_extensions` is set to `["png", "jpg", ...]` internally.

**Comment by anyscalesam** [comment]
see go/ray-data-cuj > I believe the CUJ test for both Amelie and Pouyan ran into this. @c21 can you pop in the link to the Zoom call so @Zandew can have the raw data for this?

**Comment by Zandew** [comment]
The user errors for `map / map_batches` have already been solved by hao's pr, that makes user error more clear. I will address the read api error message
