### ISSUE TITLE
Update installation docs to describe how to build Ray with Bazel.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4146]

**Comment by robertnishihara** [comment]
Both https://github.com/ray-project/ray/blob/master/doc/source/installation.rst and https://github.com/ray-project/ray/blob/master/java/doc/installation.rst need to be updated.

**Comment by bjg2** [comment]
What's the change? We synced and first couldn't build, then we did `git clean -f -f -x -d` and installed `cython==0.29.5` and now we get `Segmentation fault (core dumped)`, how to build now?

**Comment by pcmoritz** [comment]
If you clean it and run `pip install -e .` that's the right way to do it, but you also have to use anaconda packages for development right now, see https://github.com/ray-project/ray/issues/4129

If you install tensorflow and scipy from anaconda and use opencv-python-headless instead of opencv-python, the segfaults will go away (TensorFlow and opencv-python are distributing non-compliant wheels and they are clashing with current up-to-date pyarrow wheels).

I'm currently working on getting a version of the pyarrow wheels up that don't clash with TensorFlow and then this problem will go away. See also https://groups.google.com/forum/#!search/manylinux1/ray-dev/gbYKK9Gy_ns/PYuai11YAgAJ.

**Comment by denkoRa** [comment]
Hi @pcmoritz , I took your advice, executed `git clean -f -f -x -d` and installed tensorflow/scipy via anaconda (tensorflow-gpu 1.12.0 and scipy 1.2.0) and installing opencv-python-headless, and still I am having the same problem with `Segmentation fault (core dumped)`. I am using bazel version 0.22.0 and anaconda version 1.7.2.

Steps taken:
- I created conda python 3.6.6 env and activated it
- Installed conda requirements `conda install -y tensorflow-gpu==1.12.0 scipy==1.2.0`
- Installed pip requirements (ray as well as my project requirements):
```
gym==0.11.0
numpy==1.15.1
portpicker==1.3.0
psutil==5.5.0
opencv-python-headless==4.0.0.21
lz4==2.1.6
cmake==3.13.3
cython==0.29.0
setproctitle==1.1.10
# For visualization
pygame==1.9.4
# For clevr environment
mlagents-envs==0.6.1
# For dmlab environment
https://s3-eu-west-1.amazonaws.com/public-wman/DeepMind_Lab-1.0-py3-none-any.whl
# For sc2 environment
dm-sonnet==1.23
git+ssh://git@gitlab.com/wingman-ai/pysc2.git@030dc744
# For openai atari environment
gym[atari]==0.11.0
```
- Installed ray via `pip install -e .`
- Started my rllib dependent app, which crashed with segmentation fault.

This mini test works for me too. 
```
import ray

ray.init()

@ray.remote
def func(num):
    return num + 6

ray.get(func.remote(5))
```

It appears that it crashes when I `import ray.tune`. Basically this is enough for me to get `Segmentation fault` 
```
>>> import ray.tune
Segmentation fault (core dumped)
```
Without ray.tune module I can run my app just fine.

Note that my peers managed to get ray working with same or similar setup. Do you have any advice on how to fix that issue?

**Comment by pcmoritz** [comment]
@denkoRa Thanks for the report!

I'm currently in the process of building pyarrow wheels that should be more compatible with TensorFlow and scipy.

Could you edit ray/build.sh and replace

```
  $PYTHON_EXECUTABLE -m pip install \
      --target=$ROOT_DIR/python/ray/pyarrow_files pyarrow==0.12.0-RAY \
      --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/bf0f3a15e0d6583cfaedbca508627b06746fa41a/index.html
```

with

```
  $PYTHON_EXECUTABLE -m pip install \
      --target=$ROOT_DIR/python/ray/pyarrow_files \
      https://s3-us-west-2.amazonaws.com/arrow-wheels/tmp/pyarrow-0.13.0.RAY2-cp36-cp36m-linux_x86_64.whl
```

rerun setup.py and let me know if that fixes your problem? (this is a *temporary* fix to try this out in your environement and will only work with python 3.6).

In my testing, the only remaining incompatibility of the new wheels is with opencv-python, but if I replace it with opencv-python-headless everythong works fine for me.

Thanks for your help!

**Comment by denkoRa** [comment]
@pcmoritz it works after those changes. Thanks a lot!

**Comment by Maxwell2017** [comment]
Hi @denkoRa ，I am currently trying to use rllib to train a dmlab30 game. Have you succeeded? How should I use gym to Package dmlab30, I am new to RL, sorry for the basic question。
