### ISSUE TITLE
[Tune] How do I load weights from Trials?

### ISSUE THREAD

**Issue by shakkeel1330** [ray-project/ray#4148]
### System information
- **OS Platform and Distribution -- Ubuntu 18.04**:
- **Ray installed from -- Source**:
- **Ray version -- 0.6.3**:
- **Python version -- 3.6.7**:
- **Exact command to reproduce**:

### Describe the problem
I was trying to load a model from trials using the [helper.py](https://github.com/ray-project/tutorial/blob/master/tune_exercises/helper.py#L68). But I keep getting the following error.

### Source code / logs
```
Creating model...
'checkpoint'
Loading failed. Trying next model
Creating model...
'checkpoint'
Loading failed. Trying next model
Creating model...
'checkpoint'
Loading failed. Trying next model
Creating model...
'checkpoint'
Loading failed. Trying next model
```

**Comment by richardliaw** [comment]
Can you post the entire stack trace?

**Comment by shakkeel1330** [comment]
Sorry for the trouble. I was not saving the model weights while running the `make_model()` function. Noticed it only when I gave a thorough look at your tutorial. Thanks for responding :)
Closing the issue.
