### ISSUE TITLE
[CI] `linux://doc/source/ray-air/examples:gptj_serving` is failing/flaky on master.

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#41491]
- 077addb20ae09fa9cf25a2e4a1830c2172111dd4 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1855#018c1abe-8c2b-4b58-84f0-0a2590b68170)
- 40073ee036a9c13f9bc5c96c357ee1a707ecb728 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1851#018c1944-0da5-4f39-a884-6715496f1da7)
- ab1532c5790fd3efa6afbe156a71841cb0fa7a63 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1848#018c1904-572a-49c4-b1e7-cbda0e9d0172)
- 9afdf6d5f58b31256b32e3175035303cf0d1b199 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1843#018c1853-80dc-4141-9caa-fd945a4df3f2)
- fa4963bf88c6adce09da1e20816a983e377aeea9 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1826#018c13bb-0cc4-440b-ac0c-310c0bf2decc)
- 55ae63bc3219219bd69fa8fada036f47c37644b0 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1824#018c1346-3ec8-4da2-aba4-8bad13a51ac4)
- d432bd689216422288ff40d52e997e86c53f5dad FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1820#018c123a-713b-48c3-8d87-fb09b47fb58b)
- 7b33cd8c5e5cc84c2995da00cefe16f462c15881 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1811#018c113c-3b04-4f92-918b-e909cb8b773d)
- d3ac31ec80691714c88dfd140b9383dae6d6645b FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1800#018bfd9b-4a57-45eb-a673-95ec1011c4ee)
- 28fdcb6f6b5141a953b5d3a02167d12996f66bfb FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1797#018bfbd8-5713-43ca-b3e2-1c30e136c43c)
- 3eeb3de509710de897128cf188358e509b09d9a1 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1795#018bf99e-72b1-4609-9c99-1f17f6f1378c)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc/source/ray-air/examples:gptj_serving-END
....

**Comment by anyscalesam** [comment]
@justinvyu can we upgrade this to p0 given it's a linux release test and something when it gets to ray210 release we would block correct?

**Comment by justinvyu** [comment]
@anyscalesam Yes let's fix it. I think it's caused by some external change (GPU out of memory error without any code change on our side).

```
(ServeReplica:default:PredictDeployment pid=12306)     attn_outputs = self.attn(
--
  | (ServeReplica:default:PredictDeployment pid=12306)   File "/opt/miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
  | (ServeReplica:default:PredictDeployment pid=12306)     return forward_call(*args, **kwargs)
  | (ServeReplica:default:PredictDeployment pid=12306)   File "/opt/miniconda/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
  | (ServeReplica:default:PredictDeployment pid=12306)     output = old_forward(*args, **kwargs)
  | (ServeReplica:default:PredictDeployment pid=12306)   File "/tmp/ray/session_2023-11-29_11-26-47_341554_8580/runtime_resources/pip/9fc91d65ff21920e7899b7316ff121f0058d7e36/virtualenv/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 254, in forward
  | (ServeReplica:default:PredictDeployment pid=12306)     present = (key.to(hidden_states.dtype), value)
  | (ServeReplica:default:PredictDeployment pid=12306) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 14.56 GiB total capacity; 11.48 GiB already allocated; 1.50 MiB free; 11.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
