### ISSUE TITLE
[core][runtimenv] worker_process_setup_hook not working with ray job 

### ISSUE THREAD

**Issue by rickyyx** [ray-project/ray#41493]
### What happened + What you expected to happen

and maybe not working with ray serve config as well. 

```
(base) ray@ip-10-0-54-240:~/default$ python run.py 
Traceback (most recent call last):
  File "/home/ray/default/run.py", line 15, in <module>
    job = client.submit_job(entrypoint="python script.py", runtime_env={"worker_process_setup_hook": lambda: logging_setup})
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/sdk.py", line 238, in submit_job
    r = self._do_request("POST", "/api/jobs/", json_data=json_data)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 303, in _do_request
    return requests.request(
  ....
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

### Versions / Dependencies

master

### Reproduction script

```
import ray
import logging

def logging_setup():
   logger = logging.getLogger("ray")
   logger.setLevel(logging.DEBUG)

job = client.submit_job(entrypoint="python script.py", runtime_env={"worker_process_setup_hook": lambda: logging_setup})
```

### Issue Severity

None

**Comment by rkooo567** [comment]
I think it is kind of expected. Feel like the best practice is 

1. users are supposed to use this in ray.init instead of job submission (otherwise we should serialize function in user's local machine and send it to the cluster)
2. if users use job submission, they should use the string-based API

**Comment by rkooo567** [comment]
we should write the correct error msg & documentation

**Comment by rickyyx** [comment]
> 1. otherwise we should serialize function in user's local machine and send it to the cluster)

Why don't we do this then? This is what the runtime env already doing with ray.init right?

**Comment by rkooo567** [comment]
but if you run job submission, the local machine and cluster can easily have the different dependencies (same issue as ray client), which can bring lots of headache. I think it is possible to make it work, but it'd be pretty rought user experience

**Comment by anyscalesam** [comment]
@rkooo567 any update on progress here?

**Comment by rkooo567** [comment]
I am going to target fixing it by next Mon

**Comment by rkooo567** [comment]
It is my next task (I have 3 blockers, and 1 of them is done)

**Comment by rkooo567** [comment]
> hmmm, i might be misunderstanding the worker setup hook's usecase, but Isn't the worker setup function expected to be run on the remote cluster tho? Like it's just some part of code in the entrypoint script moved before task is run?

@rickyyx let's sync up this offline? I think it is a bit weird you are defining the setup function for your driver inside "job submission script". IMO the setup function should reside in the driver code, not in the submission code. 

I.e., 
1. If you submit a job via SDK, you should define the module name
2. If you want to directly insert a function, it should be inside ray.init()

**Comment by rkooo567** [comment]
Verified the same code doesn't work in Ray 2.6 (meaning it is not regression)
