### ISSUE TITLE
[CI] `linux://python/ray/data:test_consumption` is failing/flaky on master.

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#41543]
- 54f75d177814e8a1864fb514c0bf6199d2a19ae6 FAILED [Buildkite :database: data: arrow nightly tests](https://buildkite.com/ray-project/postmerge/builds/1791#018bf92d-c4aa-46d2-8f1a-604d2b2a1c68)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_consumption-END
....

Not blocking for ray210...

**Comment by bveeramani** [comment]
Looks like this hasn't failed in some time

<img width="1612" alt="image" src="https://github.com/ray-project/ray/assets/26107013/ac0ccc7c-aa9e-4e76-b8a1-368f46c4528b">
