### ISSUE TITLE
[CI] `linux://python/ray/tests:test_metrics_agent` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41548]
- 32f3b23e699ffe2024409b5f2bf8614babfdee76 FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1887#018c2215-8107-4beb-84a2-22d0f98e6e3e)
- d6d2deef5278812a8f93e4a7d982d51d7b53b51a FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1882#018c2028-c83d-47cb-bce7-0d697017a2ef)
- 42c8e0bd3c52fe9036a57dbba4b3bd9e3829075d FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1881#018c1fe5-173f-4070-b717-dd050adf3d8b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_metrics_agent-END
....

**Comment by anyscalesam** [comment]
@rickyyx ray29 release blocker?
