### ISSUE TITLE
cluster update script throws exception on Ubuntu 18.04

### ISSUE THREAD

**Issue by yangpeiren** [ray-project/ray#4155]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.0 dev0
- **Python version**: 3.6.5
- **Exact command to reproduce**:
set -i

### Describe the problem

I was trying to build up a private cluster with script, but each command in the setup_commands or head_setup_commands or worker_start_ray_commands causes the same exception: subprocess.CalledProcessError: Command 'xxx' returned non-zero exit status 127, which is an error of "command not found" according to this [question](https://stackoverflow.com/a/19328244) on StackOverflow. The line of code which causes this exception can be found [here](https://github.com/ray-project/ray/blob/615d5516d1e26bba933d3094b0b745895a2ab350/python/ray/autoscaler/updater.py#L284) in ray project.

The line is:
```python
if emulate_interactive:
            force_interactive = (
                "set -i || true && source ~/.bashrc && "
                "export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ")
            cmd = "bash --login -c {}".format(quote(force_interactive + cmd))
```

So I tried the command one by one to find out which is not exist, the first command "set -i" gives out an error already: "bash: set: -i: invalid option".

I tried this command on Ubuntu 16.04, everything goes well, then I figured out that the bash versions between them are different:

On Ubuntu 16.04 LTS:

GNU bash, Version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.

On Ubuntu 18.04 LTS:

GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.

And I've tried on different machines with 18.04, non of them works well with "set -i", could you please check this and update the line of the code?

Maybe rewirte line 286 from:

```python
cmd = "bash --login -c {}".format(quote(force_interactive + cmd))
```

to

```python
cmd = "bash --login -c -i {}".format(quote(force_interactive + cmd))
```
and remove the "set -i" in line 284?

**Comment by vakker** [comment]
I'm having the same problem if I run `ray exec minimal.yaml 'echo "hello world"'` with an Ubuntu 18.04 instance on GCP.

**Comment by yangpeiren** [comment]
I have fixed it by changing the source code in updater.py according to the proposal above, i.e.:

remove the `set -i` in line 284 and add the `-i` in line 286.

Let me create a PR and see the developing team's opinion.
