### ISSUE TITLE
[Ray Tune] train_fn without `checkpoint_dir` kwarg raises a false deprecation warning 

### ISSUE THREAD

**Issue by AnirudhDagar** [ray-project/ray#41562]
### What happened + What you expected to happen

I've a question regarding how [_detect_checkpoint_function](https://github.com/ray-project/ray/blob/40073ee036a9c13f9bc5c96c357ee1a707ecb728/python/ray/tune/utils/util.py#L587) is being used for [raising the deprecation warning](https://github.com/ray-project/ray/blob/40073ee036a9c13f9bc5c96c357ee1a707ecb728/python/ray/tune/trainable/util.py#L127-L132) if a `checkpoint_dir` kwarg is present in the trainable function.

In case the user setup their trainable (train function/train_fn) with multiple parameters (see MRE snippet below) that are being passed using [ray.tune.with_parameters](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.with_parameters.html?highlight=tune.with_parameters#ray.tune.with_parameters), it will raise the deprecation warning everytime even when the kwargs of the trainable function specifically don't have `checkpoint_dir` in them.

### Reproduction script

```
from ray import tune

trainable_kwargs = {'kwarg1': 1, 'kwarg2': 2}
def train_fn(config, **trainable_kwargs):
  pass

tuner = tune.Tuner(
    tune.with_parameters(train_fn, **trainable_kwargs),
)
```

### Reproduction script output

```
In [1]: from ray import train, tune
   ...:
   ...: trainable_kwargs = {'kwarg1': 1, 'kwarg2': 2}
   ...:
   ...: def train_fn(config, **trainable_kwargs):
   ...:   pass
   ...:
   ...: tuner = tune.Tuner(
   ...:     tune.with_parameters(train_fn, **trainable_kwargs),
   ...: )
---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
Cell In[1], line 9
      5 def train_fn(config, **trainable_kwargs):
      6   pass
      8 tuner = tune.Tuner(
----> 9     tune.with_parameters(train_fn, **trainable_kwargs),
     10 )

File /opt/conda/envs/ag_py311/lib/python3.11/site-packages/ray/tune/trainable/util.py:315, in with_parameters(trainable, **kwargs)
    310 if _detect_checkpoint_function(trainable, partial=True):
    311     from ray.tune.trainable.function_trainable import (
    312         _CHECKPOINT_DIR_ARG_DEPRECATION_MSG,
    313     )
--> 315     raise DeprecationWarning(_CHECKPOINT_DIR_ARG_DEPRECATION_MSG)
    317 def inner(config):
    318     fn_kwargs = {}

DeprecationWarning: Accepting a `checkpoint_dir` argument in your training function is deprecated.
Please use `ray.train.get_checkpoint()` to access your checkpoint as a
`ray.train.Checkpoint` object instead. See below for an example:

Before
------

from ray import tune

def train_fn(config, checkpoint_dir=None):
    if checkpoint_dir:
        torch.load(os.path.join(checkpoint_dir, "checkpoint.pt"))
    ...

tuner = tune.Tuner(train_fn)
tuner.fit()

After
-----

from ray import train, tune

def train_fn(config):
    checkpoint: train.Checkpoint = train.get_checkpoint()
    if checkpoint:
        with checkpoint.as_directory() as checkpoint_dir:
            torch.load(os.path.join(checkpoint_dir, "checkpoint.pt"))
    ...

tuner = tune.Tuner(train_fn)
tuner.fit()
```

Is this is not a possible use case, because atm it is causing a deprecation warning even though I'm not passing any `checkpoint_dir` argument. I think the [logic](https://github.com/ray-project/ray/blob/40073ee036a9c13f9bc5c96c357ee1a707ecb728/python/ray/tune/utils/util.py#L593-L599) is incorrect here. This code snippet worked perfectly fine with `ray==2.6.3`. I can reproduce the issue starting `ray>=2.7.0`

### Versions / Dependencies

Python 3.11.0
ray==2.8.1
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Comment by ddelange** [comment]
maybe cc @justinvyu via https://github.com/ray-project/ray/pull/39093

**Comment by AnirudhDagar** [comment]
Dropping a little reminder regarding this issue, would really appreciate if someone from ray team could take a look. Thanks! :)

**Comment by justinvyu** [comment]
@AnirudhDagar Thanks for raising this issue! The error is getting raised unintentionally, because the `**trainable_kwargs` can technically take in any parameter name, including `checkpoint_dir`. So, when we do `_detect_checkpoint_function` and try to bind `checkpoint_dir` to the signature, it works out and raises the deprecation warning.

To fix this, avoid using `**kwargs` in your function arguments:

```python
from ray import tune

trainable_kwargs = {"kwarg1": 1, "kwarg2": 2}


def train_fn(config, kwarg1=None, kwarg2=None):
    pass


tuner = tune.Tuner(
    tune.with_parameters(train_fn, **trainable_kwargs),
)
```

One other thing: this check/deprecation warning will be removed by the next release -- we wanted to leave it for some time for migration purposes.

I'll close this issue for now, but feel free to re-open and ask any followups!

**Comment by ddelange** [comment]
hi @justinvyu 👋 in which release will the deprecation warning be removed? 2.9 just came out with the warnings still in place

**Comment by justinvyu** [comment]
Hi, the workaround above should remove the warning, but I will remove these deprecation warnings fully in 2.10. I'll re-open this issue to track that and will update this thread once it's done.

**Comment by AnirudhDagar** [comment]
Thanks @justinvyu for sharing the details on this, looking forward to the 2.10 release.

**Comment by ddelange** [comment]
hi @justinvyu :wave: friendly ping on this one

**Comment by justinvyu** [comment]
@ddelange Thanks for the reminder, see the PR!
