### ISSUE TITLE
[CI] `windows://:metric_exporter_grpc_test` is failing/flaky on master.

### ISSUE THREAD

**Issue by fishbone** [ray-project/ray#41594]
- 19bedd127edfcc6d15379f46df500fa263510cce FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1915#018c3644-86fb-46e1-9a39-e9c014e40719)
- 48c6d89a2ea1e50fbb18d6d6aadae4c49930865d FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1912#018c35fb-8f6d-4788-a5a9-c7c9cf6b3dbd)
- 84ba7402315d0755e93bc9c7d03942cda4d28864 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1908#018c3326-f709-44d0-bd00-93408302efaa)
- 5d13766dd51df3f3e412dd2ee10aedc7988a5dc8 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1904#018c27d3-e46a-4e34-a1eb-d542951e6016)
- bc096cbe309d99b38d27395a0c9c0ac05c67ea01 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1899#018c260f-d51f-4e1b-9ed2-26f814b44cf5)
- c61c95723b1c88748c444c55dd375672d5cc8bef FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1897#018c2401-ee4a-4be3-9133-35b0a3aea316)
- 53d5e2e6ef34a05a4642f26ae61f92849037ea07 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1885#018c21ae-1a1d-49f5-b0a3-727b1400347a)
- f83749b75b33e267a755a04de1de3587626f10ec FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1870#018c1df4-4e3a-44e6-8454-e697ec753e7b)
- c913358c1a85dc341e6abe5cce815d42ac11280c FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1868#018c1dbc-d4fe-4be5-b049-039e39971de2)
- 339b1c8ccb51de1af12319be8b375e31b24861f8 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1844#018c1868-cfa6-45fe-a04c-a35f038418a9)
- 9afdf6d5f58b31256b32e3175035303cf0d1b199 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1843#018c1853-8079-4240-9dc8-6ab906ce087e)
- ca5132236efc3143eaa2f62446110f57ba57956e FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1825#018c136c-8281-481d-ba3a-cad0cd67cac2)
- 55ae63bc3219219bd69fa8fada036f47c37644b0 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1824#018c12ef-2e73-4c0c-8bac-613cc6ff5184)
- 2bc0494633b489b8622e9afd86cfc3ef9e960dd5 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1822#018c12c3-3634-477f-a831-73aea728400b)
- d432bd689216422288ff40d52e997e86c53f5dad FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1820#018c123a-70ee-4e51-9ff7-b9124ebefcd3)
- 68a1adca74df1a4d7d8a39b4ce2fa713c360cb77 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1819#018c122c-ec26-4687-8fdc-350d6d9860f0)
- 7b33cd8c5e5cc84c2995da00cefe16f462c15881 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1811#018c113c-3abc-49d9-8d43-e4d88a215f2a)
- 790c5064f82e973d9d964f6e962a27e8fa8cd79d FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1806#018c0878-4bab-4ab7-9526-cebf9843e271)
- 28fdcb6f6b5141a953b5d3a02167d12996f66bfb FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1797#018bfbd8-56c5-4891-9ac9-f4cf44639db0)
- 9b9fb55435398cb43423acc17d6a59fba49645e3 FAILED [Buildkite :windows: core tests](https://buildkite.com/ray-project/postmerge/builds/1790#018bf92d-883e-4a56-88fa-6d70561c72ff)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-windows://:metric_exporter_grpc_test-END
....

**Comment by anyscalesam** [comment]
@can-anyscale test seems to be passing now; should we close? cc @mattip

**Comment by anyscalesam** [comment]
<img width="1632" alt="image" src="https://github.com/ray-project/ray/assets/116198444/5ff7612f-641b-4a8d-b7b5-daa3adc0cffb">
looks passing... closing for now. @can-anyscale are you running windows test gh issues where they open/close so we can eventually gather metadata on flakiness and prioritize test rewrite for the ones that keep opening/closing?

**Comment by can-anyscale** [comment]
sorry i missed it, looks legit yes
