### ISSUE TITLE
Interaction between ray actors and multiprocessing

### ISSUE THREAD

**Issue by snailrowen1337** [ray-project/ray#4159]
I would want to combine ray together with python multiprocessing and was wondering, is it possible to have ray actors own a ```multiprocessing.Queue```? I'd want to initialize the actors with such a queue and wonder if one can expect it to work. Obviously, if the actor is on another node it wouldn't work, but if the worker process is on the same node as the main process.

**Comment by raulchen** [comment]
Do you want to use a `multiprocessing.Queue` to share data between an actor and the driver?

That won't work, because, as you've said, the actor could be on a different node.

Can you just use remote calls to pass data? Is there any issue of doing so?

**Comment by snailrowen1337** [comment]
yes, that's what I'd want. I want to pass very small data types and want to avoid the overhead of ray serialization -- the documentation says "You will be unlikely to see speedups if your tasks take less than ten milliseconds.". Assuming that the actor is on the same node, does ray support this mode?

**Comment by ericl** [comment]
I think those queues will work, have you tried passing it as an argument to an actor?

Another alternative is to use the object store as a queue, bypassing task scheduling:
https://gist.github.com/ericl/4533032645686635e4e6d834da716dd1

**Comment by raulchen** [comment]
`multiprocessing.Queue` should also need serialization, see https://github.com/python/cpython/blob/d5a551c2694e32835bcdafc01d611f3227ca36b3/Lib/multiprocessing/queues.py#L239.

But using remote tasks also includes task scheduling overhead. As @ericl mentioned above, you can use object store to bypass the overhead.

**Comment by snailrowen1337** [comment]
I'll try the object store, thanks!!

**Comment by frthjf** [comment]
Hi, I've been looking for a Ray-based queue solution that circumwents the remote() call overhead. @ericl, the gist is very useful! Is there a way to have multiple actors feed and consume such a queue at the same time?

I have a setup where multiple actors generate data that is processed by another actor. The result of the processing has to be send back to producing actors. Something like this:

![actor-setup](https://user-images.githubusercontent.com/5411942/65895095-c6bd1b80-e3a2-11e9-9460-9b23d9c9860d.png)

My current setup is very slow and I'm wondering whether a smarter queueing system could help.

**Comment by lenassero** [comment]
Hi !
I am trying to use the `ray.experimental.queue.Queue` across multiple actor processes.
In the simple case, I am testing it for one actor process as follows:

```python
import os
import ray
import time

from multiprocessing import Process
from ray.experimental.queue import Queue

@ray.remote
class MyProcessActor(Process):
    def __init__(self, queue):
        Process.__init__(self)
        self.queue = queue

    def run(self):
        print(f"{os.getpid()} init")
        while True:
            item = self.queue.get(True)
            print(f"{os.getpid()}: {item}")
            time.sleep(1)  

queue1 = Queue()
process = MyProcessActor.remote(queue1)
process.start.remote()
```
This results in the following error:
```
4590 init
 *** Aborted at 1588171887 (unix time) try "date -d @1588171887" if you are using GNU date ***
0x0 (unknown)
(pid=4550, ip=172.30.2.61) *** SIGSEGV (@0x21) received by PID 4550 (TID 0x7f3d6ffff700) from PID 33; stack trace: ***
0x7f3d89a2c390 (unknown)
0x7f3d87c5f5d3 grpc_core::LockfreeEvent::SetReady()
0x7f3d87c5e0d1 pollset_work()
 0x7f3d87c374c5 cq_next()
0x7f3d87c37b6b grpc_completion_queue_next
0x7f3d87b71941 grpc_impl::CompletionQueue::AsyncNextInternal()
0x7f3d878a1e21 ray::rpc::ClientCallManager::PollEventsFromCompletionQueue()
0x7f3d8726cb8e (unknown)
 0x7f3d89a226ba start_thread
 0x7f3d88c0541d clone
```

Do you have an idea why ?
Thank!

**Comment by bionicles** [comment]
It would be hugely useful to have a simple solution for this sort of producer-consumer pattern (env-agent) where producers and consumers are agent pools

**Comment by crypdick** [comment]
@frthjf did you figure out that implementation? I'm trying to do the exact same thing with Ray Serve and S3 client actors.

**Comment by frthjf** [comment]
Hi @crypdick, unfortunately not but it's been a while since I've last worked on this. I believe `ray.util.queue` was not available back then, so might be worth a new try?

**Comment by crypdick** [comment]
@GoingMyWay I went with the ray.util.queue for a while and later went with using Ray datasets.

**Comment by GoingMyWay** [comment]
> @GoingMyWay I went with the ray.util.queue for a while and later went with using Ray datasets.

@crypdick Thanks for the quick response. Does Ray Datasets can do for the producer-consumer pattern (env-agent) where producers and consumers are agent pools?

**Comment by crypdick** [comment]
@GoingMyWay sorry for the late response, I'm on vacation. I am not familiar with the env-agent pattern, but I've made Ray Pipelines with mappers and reducers. You can set an agent pool with one of the optional kwargs, which I don't know off the top of my head. I used this for batch processing, though. If you need an eternal process then this is probably not a good fit.
