### ISSUE TITLE
[Serve] `__del__` method is not called when the replica dies during `__init__`

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#41606]
### What happened + What you expected to happen

In plain Python, when an object raises an exception during the `__init__` method, its `__del__` method is still executed by the garbage collector:

```
>>> class A:
...     def __init__(self):
...         raise RuntimeError("hi")
...     def __del__(self):
...         print("DEL RAN!")
...
>>> a = A()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
RuntimeError: hi
>>> del a
DEL RAN!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
```

However, in Serve, if a replica dies while running `__init__`, its `__del__` method is not called. E.g.

```python
# File name: repro.py

import time
from ray import serve

@serve.deployment
class HangDeployment:

    def __init__(self):
        time.sleep(100000)

    def __del__(self):
        print("hello")

app = HangDeployment.bind()
```

```
# In terminal
$ ray start --head
$ serve run repro:app

# In separate terminal window
$ ray list actors
...
2  55fd1550f84c5aee9fa91b8d01000000  ServeReplica:default:HangDeployment  ALIVE    01000000  SERVE_REPLICA::default#HangDeployment#BAoZZi
...

$ python
>>> import ray
>>> ray.init(address="auto")
>>> replica_handle = ray.get_actor(name="SERVE_REPLICA::default#HangDeployment#BAoZZi", namespace="serve")
>>> ray.kill(replica_handle)
```

`"hello"` never gets printed in the first terminal window.

### Versions / Dependencies

Ray on the latest `master`.

### Reproduction script

See description.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by shrekris-anyscale** [comment]
FYI @edoakes

**Comment by hangg112233** [comment]
It seems like in Serve 2.9.3, `__del__` was being called but then in 2.10.0, it is not, perhaps as a result of [this change](https://github.com/ray-project/ray/pull/42298/files#diff-9b13fed1caa40bb539db22cd9d9037c16afe1942376c58b95688de72744090aaL1043)

In our use case, we had models that upon init would download some files to disk. In the `__del__` method we put some cleanup logic to remove the files, such that if the model was destroyed or initialization failed, the files would get cleaned. So 2.10.0 breaks that particular functionality for us.

**Comment by edoakes** [comment]
> It seems like in Serve 2.9.3, `__del__` was being called but then in 2.10.0, it is not, perhaps as a result of [this change](https://github.com/ray-project/ray/pull/42298/files#diff-9b13fed1caa40bb539db22cd9d9037c16afe1942376c58b95688de72744090aaL1043)
> 
> In our use case, we had models that upon init would download some files to disk. In the `__del__` method we put some cleanup logic to remove the files, such that if the model was destroyed or initialization failed, the files would get cleaned. So 2.10.0 breaks that particular functionality for us.

Sorry about that. We will try to get a fix for this in before the next branch cut.

**Comment by hangg112233** [comment]
Thank you!
