### ISSUE TITLE
[Docs] Theme revamp:  primary sidebar

### ISSUE THREAD

**Issue by simran-2797** [ray-project/ray#41618]
### Description

Change the style of the navigation bar to kickoff the ray docs theme redesign project. 
Summary of changes: 
1. Font type change, let's not make changes to font size
2. Add styles to the nav bar as per the design 
3. The nav bar should not have any margins on the left side as shown in the figma 
4. Add a gradient (light version and dark version) to the background of ray docs

[Figma designs](https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=8%3A2244&mode=design&t=1LB8jzUvQjJHF0Ex-1)
cc: @angelinalg 

Doc for overriding colors: https://docs.google.com/document/d/1cxfBVKYSmGSCnq8PXWmxT4Ji0jD8fkYrSJ_A77EK9m4/edit?usp=sharing

**Comment by peytondmurray** [comment]
Thanks for this, we'll get this implemented. I had a few questions, though:

> Add icons to the nav bar

It looks like there are two designs here, one with icons and one without. Which one do you want to use? Can we get rid of the one you don't want?

![image](https://github.com/ray-project/ray/assets/14017872/bbc0469b-4020-479e-b398-f8af155cd465)

> The nav bar should not have any margins on the left side as shown in the figma

It looks like there is lots of margin on the side here. You're asking for it to be removed when I implement it?

![image](https://github.com/ray-project/ray/assets/14017872/6ad70246-c7c4-419b-b5a2-7990c4b9c527)

**Comment by simran-2797** [comment]
> Thanks for this, we'll get this implemented. I had a few questions, though:
> 
> > Add icons to the nav bar
> 
> It looks like there are two designs here, one with icons and one without. Which one do you want to use? Can we get rid of the one you don't want?
> 
> ![image](https://private-user-images.githubusercontent.com/14017872/288163251-bbc0469b-4020-479e-b398-f8af155cd465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDE5ODYsIm5iZiI6MTcwMTgwMTY4NiwicGF0aCI6Ii8xNDAxNzg3Mi8yODgxNjMyNTEtYmJjMDQ2OWItNDAyMC00NzllLWIzOTgtZjhhZjE1NWNkNDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE4NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNWQ1MzA1ZjRhOGFlZjFmMDEwNTI2MjZmYWY2ZGVmYzJkYzk1NGY5NDc4Mjk3NTI2MWVhZjM5MzI2YTcwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLZLJOXBAe-2EPlj8BxVNJdErXmfZumKUi9IZSNdhAo)
> 
> > The nav bar should not have any margins on the left side as shown in the figma
> 
> It looks like there is lots of margin on the side here. You're asking for it to be removed when I implement it?
> 
> ![image](https://private-user-images.githubusercontent.com/14017872/288163004-6ad70246-c7c4-419b-b5a2-7990c4b9c527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDE5ODYsIm5iZiI6MTcwMTgwMTY4NiwicGF0aCI6Ii8xNDAxNzg3Mi8yODgxNjMwMDQtNmFkNzAyNDYtYzdjNC00MTliLWI1YTItNzk5MGM0YjljNTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE4NDEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTg4OTRjNmVmMjMwMmFiYjY4Y2E3MmU5MDYyZDE1MzY4NWJkM2EwYzU2ZWI2NjEzYzJhNjM1ZDBhY2UyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J_XyvYc61GQI7Udn8ljJKD-MqwHC8Fr9p1GVXezFe6Y)

1. Let's start with the nav with icons and then we can get feedback and remove later. 
2. My bad. Let's reduce the margin. I image the nav bar looking like this - https://lightning.ai/docs/pytorch/stable/

**Comment by peytondmurray** [comment]
Sorry, I'm still not clear on the left hand margin. The pytorch-lightning docs have lots of left hand margin on the primary sidebar:

![image](https://github.com/ray-project/ray/assets/14017872/6896989b-7c2c-4051-be96-2e5fd4809510)

Or are you talking about changing the whitespace on both the left and right sides of the page?
![bitmap](https://github.com/ray-project/ray/assets/14017872/4f78abd0-7841-466d-9d90-84b02d3baa8b)

**Comment by peytondmurray** [comment]
After a discussion yesterday, it sounds like we should not add icons here because the ray libraries each have their own icons, so this branding would conflict with that.

**Comment by simran-2797** [comment]
Yes, no icons @peytondmurray 
I updated the description
