### ISSUE TITLE
[docs infra] Replace Examples pages under individual libraries (Data, Serve, Train, Tune, RLlib) with a pre-filtered Example Gallery page

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#41616]
### Description

The Examples pages under each library are not standardized but are curated. They should match a filtered view of the Example Gallery. For example, the Train>Examples page should have the same examples as Example Gallery with the Model training filter on. 

### Link

* https://docs.ray.io/en/latest/ray-core/examples/overview.html
* https://docs.ray.io/en/latest/data/examples/index.html
* https://docs.ray.io/en/latest/train/examples.html
* https://docs.ray.io/en/latest/tune/examples/index.html
* https://docs.ray.io/en/latest/rllib/rllib-examples.html

**Comment by angelinalg** [comment]
@amogkam also made this request on June 5th, 2023: 
[@Max]
 is it possible to link to the example gallery with pre-selected tags?
Also, is there a way to do "or" based filtering (give me all the examples with workload X or workload Y) instead of "and" based?
I'm looking to see if in Ray Data we can link to the global examples gallery with pre-selected filters, rather than maintain a separate, independent gallery. But this would require being able to select multiple workloads

**Comment by peytondmurray** [comment]
> is it possible to link to the example gallery with pre-selected tags?
Yeah, I wrote a custom sphinx directive for this: `query-param-ref`. Then I added some js which applies filters based on the URL query parameters. There are a few cases where we use this in the code. If you can't find any examples, let me know and I'll hunt one down.

> Also, is there a way to do "or" based filtering (give me all the examples with workload X or workload Y) instead of "and" based?
Well, there were some very specific requests around this kind of querying when we originally built out the example gallery.

![image](https://github.com/ray-project/ray/assets/14017872/9c1ef436-abec-45ec-8da7-7d4bce63cdc6)

Currently, there are 4 groups of tags you can filter by. If you select two tags in the same group, an `or` will be used, so you get the set containing both tags. If you select tags in different groups, you get `and`, so you get the intersection of the examples containing those tags.

> I'm looking to see if in Ray Data we can link to the global examples gallery with pre-selected filters, rather than maintain a separate, independent gallery. But this would require being able to select multiple workloads

Yep, I think we can already do this. The first solution to come to mind is to make a page template that redirects to the example gallery with the appropriate tags specified as URL query parameters. There's probably other ways to do this as well.

**Comment by peytondmurray** [comment]
Closing as complete in #42862.
