### ISSUE TITLE
Ray Core: Can't get attribute 'RayTrainReportCallback' on <module  'ray.train.huggingface.transformers._transformers_utils'

### ISSUE THREAD

**Issue by robinsonmhj** [ray-project/ray#41659]
### What happened + What you expected to happen

get the following error while running this [example](https://docs.ray.io/en/latest/train/examples/deepspeed/gptj_deepspeed_fine_tuning.html)
Put failed:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 results = trainer.fit()                                                                      │
│   2                                                                                              │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/base_trainer.py:570 in fit     │
│                                                                                                  │
│   567 │   │   from ray.tune import TuneError                                                     │
│   568 │   │   from ray.tune.tuner import Tuner, TunerInternal                                    │
│   569 │   │                                                                                      │
│ ❱ 570 │   │   trainable = self.as_trainable()                                                    │
│   571 │   │   param_space = self._extract_fields_for_tuner_param_space()                         │
│   572 │   │                                                                                      │
│   573 │   │   if self._restore_path:                                                             │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/base_trainer.py:825 in         │
│ as_trainable                                                                                     │
│                                                                                                  │
│   822 │   │   trainable_cls = self._generate_trainable_cls()                                     │
│   823 │   │                                                                                      │
│   824 │   │   # Wrap with `tune.with_parameters` to handle very large values in base_config      │
│ ❱ 825 │   │   return tune.with_parameters(trainable_cls, **base_config)                          │
│   826                                                                                            │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/tune/trainable/util.py:292 in        │
│ with_parameters                                                                                  │
│                                                                                                  │
│   289 │   # Objects are moved into the object store                                              │
│   290 │   prefix = f"{str(trainable)}_"                                                          │
│   291 │   for k, v in kwargs.items():                                                            │
│ ❱ 292 │   │   parameter_registry.put(prefix + k, v)                                              │
│   293 │                                                                                          │
│   294 │   trainable_name = getattr(trainable, "__name__", "tune_with_parameters")                │
│   295 │   keys = set(kwargs.keys())                                                              │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/tune/registry.py:296 in put          │
│                                                                                                  │
│   293 │   def put(self, k, v):                                                                   │
│   294 │   │   self.to_flush[k] = v                                                               │
│   295 │   │   if ray.is_initialized():                                                           │
│ ❱ 296 │   │   │   self.flush()                                                                   │
│   297 │                                                                                          │
│   298 │   def get(self, k):                                                                      │
│   299 │   │   if not ray.is_initialized():                                                       │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/tune/registry.py:308 in flush        │
│                                                                                                  │
│   305 │   │   │   if isinstance(v, ray.ObjectRef):                                               │
│   306 │   │   │   │   self.references[k] = v                                                     │
│   307 │   │   │   else:                                                                          │
│ ❱ 308 │   │   │   │   self.references[k] = ray.put(v)                                            │
│   309 │   │   self.to_flush.clear()                                                              │
│   310                                                                                            │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:24 in     │
│ auto_init_wrapper                                                                                │
│                                                                                                  │
│   21 │   @wraps(fn)                                                                              │
│   22 │   def auto_init_wrapper(*args, **kwargs):                                                 │
│   23 │   │   auto_init_ray()                                                                     │
│ ❱ 24 │   │   return fn(*args, **kwargs)                                                          │
│   25 │                                                                                           │
│   26 │   return auto_init_wrapper                                                                │
│   27                                                                                             │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:102 in  │
│ wrapper                                                                                          │
│                                                                                                  │
│    99 │   │   │   # Legacy code                                                                  │
│   100 │   │   │   # we only convert init function if RAY_CLIENT_MODE=1                           │
│   101 │   │   │   if func.__name__ != "init" or is_client_mode_enabled_by_default:               │
│ ❱ 102 │   │   │   │   return getattr(ray, func.__name__)(*args, **kwargs)                        │
│   103 │   │   return func(*args, **kwargs)                                                       │
│   104 │                                                                                          │
│   105 │   return wrapper                                                                         │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/util/client/api.py:52 in put         │
│                                                                                                  │
│    49 │   │   │   args: opaque arguments                                                         │
│    50 │   │   │   kwargs: opaque keyword arguments                                               │
│    51 │   │   """                                                                                │
│ ❱  52 │   │   return self.worker.put(*args, **kwargs)                                            │
│    53 │                                                                                          │
│    54 │   def wait(self, *args, **kwargs):                                                       │
│    55 │   │   """wait is the hook stub passed on to replace `ray.wait`                           │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/util/client/worker.py:496 in put     │
│                                                                                                  │
│   493 │   │   │   │   "call 'put' on it (or return it)."                                         │
│   494 │   │   │   )                                                                              │
│   495 │   │   data = dumps_from_client(val, self._client_id)                                     │
│ ❱ 496 │   │   return self._put_pickled(data, client_ref_id, _owner)                              │
│   497 │                                                                                          │
│   498 │   def _put_pickled(                                                                      │
│   499 │   │   self, data, client_ref_id: bytes, owner: Optional[ClientActorHandle] = None        │
│                                                                                                  │
│ /opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/util/client/worker.py:510 in         │
│ _put_pickled                                                                                     │
│                                                                                                  │
│   507 │   │   resp = self.data_client.PutObject(req)                                             │
│   508 │   │   if not resp.valid:                                                                 │
│   509 │   │   │   try:                                                                           │
│ ❱ 510 │   │   │   │   raise cloudpickle.loads(resp.error)                                        │
│   511 │   │   │   except (pickle.UnpicklingError, TypeError):                                    │
│   512 │   │   │   │   logger.exception("Failed to deserialize {}".format(resp.error))            │
│   513 │   │   │   │   raise                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: Can't get attribute 'RayTrainReportCallback' on <module 
'ray.train.huggingface.transformers._transformers_utils' from 
'/opt/conda/envs/domino-ray/lib/python3.10/site-packages/ray/train/huggingface/transformers/_transformers_utils.py'
>

### Versions / Dependencies

ray==2.8.0
ray-cpp==2.8.0
accelerate==0.16.0
transformers==4.26.0
pytorch-lightning==1.9.5
torch==2.0.1
torchaudio==2.0.2
torchmetrics==1.2.1
torchvision==0.15.2
deepspeed==0.9.2

### Reproduction script

get the error while running in cluster mode
results = trainer.fit()

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Could you clarify what you mean by "in cluster mode"?

**Comment by robinsonmhj** [comment]
@matthewdeng I was running the job in a cluster with several nodes, which is not running it in a local machine.

**Comment by woshiyyya** [comment]
Hi @robinsonmhj , are you still having this issue?

**Comment by robinsonmhj** [comment]
not anymore if I submit the job to a cluster. You can close it
