### ISSUE TITLE
[tune]  Nevergrad asks for picklability when searching with Pymoo

### ISSUE THREAD

**Issue by goncamateus** [ray-project/ray#41653]
### What happened + What you expected to happen

When trying to instantiate a NevergradSearch with nevergrad.optimizers. Pymoo, nevergrad returns "ValueError: If you want picklability you should have asked for it".

This is new a feature for the ConfiguredOptimizer, and ray-tune did not follow it yet.

It is easily fixed adding the following code on [this part](https://github.com/ray-project/ray/blob/3546c41b9996c36d0f1bba497dc660d3fcfc59a7/python/ray/tune/search/nevergrad/nevergrad_search.py#L205):
```python 
if isinstance(self._opt_factory, ConfiguredOptimizer):
    self._nevergrad_opt.enable_pickling()
```

I don't know if it should be ConfiguredOptimizer or nevergrad.optimizers.Pymoo. Need tests if it is only for Pymoo optimizers.

### Versions / Dependencies

python==3.10
ray==2.8.1
nevergrad==1.0.1
OS==Ubuntu 22.04

### Reproduction script

```python
from ray.tune.search.nevergrad import NevergradSearch
search_algo = NevergradSearch(
            optimizer=ng.optimizers.Pymoo(algorithm="ga"),
            metric="mse",
            mode="min",
            points_to_evaluate=current_best_params,
        )
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hey @goncamateus, we've actually recently removed `NevergradSearch` due to low usage. Would you be able to use one of the other search algorithms?

**Comment by goncamateus** [comment]
Oh, I see. Is there a framework that includes Particle Swarm Optimization or Genetic Algorithm?
