### ISSUE TITLE
[Core] OSX gcs fault tolerance tests are flaky

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#41675]
### What happened + What you expected to happen

<img width="509" alt="Screenshot 2023-12-07 at 7 51 46 AM" src="https://github.com/ray-project/ray/assets/18510752/3243b1c1-41be-45ad-a021-bdd9c6069082">

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rkooo567** [comment]
I feel like it is just this PR actually. Maybe trying reverting it? 

![Image](https://github.com/ray-project/ray/assets/18510752/2aad2fef-ebed-4536-be0e-e013d3ec0677)

**Comment by rickyyx** [comment]
yeah, i have a revert here, still validatng: https://github.com/ray-project/ray/pull/41774

**Comment by anmyachev** [comment]
Hi @rickyyx! Looks like you reverted my fix: #41774. Could you give some context? Maybe I can improve it.

**Comment by rickyyx** [comment]
Hey @anmyachev - I didn't. The PR was closed rather than reverted. We thought it was root cause for some regression but found out not related!

**Comment by anmyachev** [comment]
Oh I see, I just read [the comment](https://github.com/ray-project/ray/issues/38257#issuecomment-1873931382) and didn't look carefully, sorry for the inconvenience :)
