### ISSUE TITLE
[rllib] Batch prev_action field is always numpy array of zeros

### ISSUE THREAD

**Issue by bjg2** [ray-project/ray#4167]
Batch prev_action field is filled with `episode.prev_action_for(agent_id)` in [sampler.py line 389](https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/sampler.py#L389), which boils down to `_agent_to_prev_action` in [episode.py](https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/episode.py), which is never assigned to. `episode.prev_action_for(agent_id)` will always return numpy array of zeros.

Not sure if any algorithm uses prev_actions, but if it does it is getting wrong values. If neither algorithm uses it then it should be deleted.

**Comment by ericl** [comment]
Ironically, we already had a unit test for this, but the test data was also all zeros so it passed.
