### ISSUE TITLE
[CI] `linux://python/ray/tests:test_reference_counting` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41684]
- 9516630cc8287b744b54bded0bee7fd1aa064d16 FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1962#018c40de-23f6-46c1-a961-fedc0f9260a7)
- 9516630cc8287b744b54bded0bee7fd1aa064d16 FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1962#018c40de-23fa-445c-87a6-5ae9afa71a9a)
- 968aac2e19b45c2221edaa189333710dc777e9e3 FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1959#018c4084-e2a3-4b76-957e-9221d5ac776d)
- 96a5f260812f5f02c5871285530316fa77d13114 FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1955#018c402d-836c-4eaa-b5e4-5d0deca4aff7)
- 6948c204055def067af598cdbd37d6399b8731ae FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1954#018c3fc5-bb25-4962-8e05-244c9b622045)
- 7e9043c38d76412c310fcf6e3fff79cb55d481da FAILED [Buildkite :ray: core: python tests](https://buildkite.com/ray-project/postmerge/builds/1953#018c3fc4-5960-4457-b875-7cc09b08c448)
- 5d13766dd51df3f3e412dd2ee10aedc7988a5dc8 FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1904#018c27e2-63a6-4fb0-9f46-70d834aea24d)
- c61c95723b1c88748c444c55dd375672d5cc8bef FAILED [Buildkite :ray: core: redis tests](https://buildkite.com/ray-project/postmerge/builds/1897#018c2401-ee12-4b36-97fc-537bdcc3e27a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_reference_counting-END
....

**Comment by architkulkarni** [comment]
@xieus could you please help find an assignee for this issue?

**Comment by jjyao** [comment]
<img width="1583" alt="Screenshot 2024-01-10 at 9 28 03 AM" src="https://github.com/ray-project/ray/assets/898023/01d99525-04ef-495c-9306-61098adcc54f">
