### ISSUE TITLE
[Serve] Duplicate pymodules in the serve details. 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/ray#41690]
### What happened + What you expected to happen

serve details.includes duplicated items in py_modules when setting working_dir. 

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

**Comment by zhe-thoughts** [comment]
@sihanwang41 @edoakes (I'm not familiar enough in this module)

Could you help me understand why having this kind of duplication is a P0 issue?

**Comment by zhe-thoughts** [comment]
Thanks, I agree it is a release blocker
