### ISSUE TITLE
[CI] `linux://doc:datasets_train` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41734]
- e06a47677fb39f1cd8328d89f3bff31a5a882b09 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1990#018c472c-0481-4af6-a5f3-a2096f432ab7)
- 905796e82aafd64d66a7d6d12e3b48d87058c400 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1970#018c43f1-358d-4145-b496-94396d8b7214)
- 906df203a41414abacc265a90a696e8e273e3faf FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1963#018c4103-7192-41e3-b2e8-fe7111916c17)
- 27b794cd1d48d3e79dffae5f56cb9845a1a0e7af FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1956#018c4052-bd5a-426b-926a-4be69966a503)
- 620ffe1a52d3b392f657179074fcb50d1824f48e FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1945#018c3c9d-8406-44ce-aa1c-fedadc347430)
- 55838fc47bf5531d7c73c9b48064a6d1fd4f2d12 FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1920#018c3763-55ce-4970-9b51-e37591b1636e)
- e941a2f238f446dbfc078fa4f3b7d07d8daf4e3d FAILED [Buildkite :train: ml: train gpu tests](https://buildkite.com/ray-project/postmerge/builds/1917#018c3677-c4c6-4cf7-94bc-7fa2a63855fc)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://doc:datasets_train-END
....

**Comment by scottjlee** [comment]
discussed with train team, action items:
- @woshiyyya will move it out of doctests into a formal train test, so we can get actual failure errors
- if needed, I will assist with debugging the data failure
