### ISSUE TITLE
[RLlib] - `SingleAgentEpisode.init()` throws an error when initialized empty with `len_lookback_buffer>0` 

### ISSUE THREAD

**Issue by simonsays1980** [ray-project/ray#41730]
### What happened + What you expected to happen

Initializing the `SingleAgentEpisode` with no data but a positive lookback buffer throws an error in the `validate()` function: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: __len__() should return >= 0
```

### Versions / Dependencies

Ray master
Fedora 37

### Reproduction script

```python
SingleAgentEpisode(len_lookback_buffer=10)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by simonsays1980** [comment]
@sven1977 In regard to the error that occurred always in the `validate()` method I adjusted the `__len__` of the buffer to use the `max(_, 0)`. Imo this is a good solution as the length should never consider the lookback (e.g. in comparisons between different data) anyway - and especially not, if the data length is smaller than the lookback.

**Comment by sven1977** [comment]
I think that's a correct fix. Keep in mind that the `len_lookback_buffer` in the constructor should only be a suggestion, meaning if the data (provided also in the constructor) is not even as long as `len_lookback_buffer`, then we should simply create all `InfiniteLookbackBuffer` instance inside SingleAgentEpisode with the smaller number.

**Comment by simonsays1980** [comment]
True. I think another possibility is to set 

```python
self.lookback = lookback if lookback <= len(self.data) else len(self.data)
```
in `BufferWIthInifniteLookback.init()`. However, then we have to take care of this relation when setting the extra model outputs in the `SingleAgentEpisode` as these get defined via the `defaultdict`.
