### ISSUE TITLE
[Serve] Gracefully shut down unhealthy replicas

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#41742]
### Description

Currently, when replicas fail enough health checks, they're considered unhealthy. Serve then shuts down these unhealthy replicas immediately.

Instead, Serve should shut them down gracefully.

### Use case

This gives unhealthy replicas extra time to finish processing requests.

**Comment by smit-kiri** [comment]
I like this idea! Although this could mean a longer downtime in case ALL replicas for a deployment are unhealthy. What's the default for graceful_shutdown_timeout_s and can it be configured by setting an environment variable for example?

**Comment by edoakes** [comment]
@smit-kiri the default is 30s and it can be set for each deployment via the `graceful_shutdown_timeout_s` parameter
