### ISSUE TITLE
[CI] Core dashboard tests flaky with "Failed to fetch"

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#41753]
### What happened + What you expected to happen

Example 1 (2.9.0 release branch premerge): https://buildkite.com/ray-project/premerge/builds/14041#018c4afa-0625-4c28-8a73-3aa0646b2bdf/276-1012

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python-cryptography/python3-cryptography_2.8-3ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
--
  | E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/b/bluez/bluez_5.53-0ubuntu3.6_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
  | E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/b/bluez/libbluetooth3_5.53-0ubuntu3.6_amd64.deb  404  Not Found [IP: 91.189.91.81 80]
  | E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Example 2: (master) https://buildkite.com/ray-project/premerge/builds/14042#018c4731-03e0-4fa8-a419-d40bd4a33feb/275-1004

```

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python-cryptography/python3-cryptography_2.8-3ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.91.83 80]
--
  | E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


```
It might be an issue where the server is intermittently down.  I don't think the files have been permanently removed, because the set of missing files is different in the above two repros, and some more recent runs passed, e.g. https://buildkite.com/ray-project/postmerge/builds/2008

### Versions / Dependencies

see above

### Reproduction script

above

### Issue Severity

None

**Comment by architkulkarni** [comment]
Note: there's no evidence of this on https://flaky-tests.ray.io/ so it's easy for this to get hidden. It must be failing before https://flaky-tests.ray.io/ can track it.

**Comment by aslonnie** [comment]
should be fixed already.
