### ISSUE TITLE
[Build] Unable to build Ray on MacOS 14.1.2 (Sonoma)

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#41780]
### What happened + What you expected to happen

I tried building Ray on [the latest `master`](https://github.com/ray-project/ray/commit/5edabc7b2f92712982b0e590f739eb0110d80176) on MacOS 14.1.2 (Sonoma), and it failed with the following exception:

```
(ae) shrekris@Shreyas-MacBook-Pro python % pip install -e . --verbose
Using pip 23.2.1 from /Users/shrekris/miniforge3/envs/ae/lib/python3.8/site-packages/pip (python 3.8)
...
    # Configuration: 88932aa92c474e778228566e656d94a65d6b4db648eb7d1b93c3c9b29641417f
    # Execution platform: @local_config_platform//:host

    Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
    src/ray/object_manager/common.cc:28:3: error: 'sem_init' is deprecated [-Werror,-Wdeprecated-declarations]
      sem_init(&rw_semaphore, PTHREAD_PROCESS_SHARED, 1);
      ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here
    int sem_init(sem_t *, int, unsigned int) __deprecated;
                                             ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:211:40: note: expanded from macro '__deprecated'
    #define __deprecated    __attribute__((__deprecated__))
                                           ^
    src/ray/object_manager/common.cc:42:13: error: 'sem_destroy' is deprecated [-Werror,-Wdeprecated-declarations]
      RAY_CHECK(sem_destroy(&rw_semaphore) == 0);
                ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been explicitly marked deprecated here
    int sem_destroy(sem_t *) __deprecated;
                             ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:211:40: note: expanded from macro '__deprecated'
    #define __deprecated    __attribute__((__deprecated__))
                                           ^
    2 errors generated.
    INFO: Elapsed time: 395.434s, Critical Path: 27.01s
    INFO: 7663 processes: 3919 internal, 3744 darwin-sandbox.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully
...
```

The root cause seems to be that the following semaphore calls raise deprecation warnings in the latest version of Apple Clang (which comes packaged with Xcode Command Line Tools). I believe the deprecation warnings are treated as errors due to [this build configuration](https://github.com/ray-project/ray/blob/5edabc7b2f92712982b0e590f739eb0110d80176/.bazelrc#L47).

1. [`sem_init` call](https://github.com/ray-project/ray/blob/5edabc7b2f92712982b0e590f739eb0110d80176/src/ray/object_manager/common.cc#L28)
2. [`sem_destory` call](https://github.com/ray-project/ray/blob/5edabc7b2f92712982b0e590f739eb0110d80176/src/ray/object_manager/common.cc#L42)

There are StackOverflow threads ([example](https://stackoverflow.com/questions/27736618/why-are-sem-init-sem-getvalue-sem-destroy-deprecated-on-mac-os-x-and-w)) that mention these calls are deprecated, but strangely these threads are from many years ago. I have been successfully building Ray from source on MacOS Monterey using Xcode CLT (and Apple Clang) version 13.0 for the last couple years.

### Versions / Dependencies

Ray on `master`
MacOS 14.1.2
Python 3.8

```
(ae) shrekris@Shreyas-MacBook-Pro ray % bazel --version
bazel 5.4.1
(ae) shrekris@Shreyas-MacBook-Pro ray % xcode-select --version
xcode-select version 2403.
(ae) shrekris@Shreyas-MacBook-Pro ray % clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(ae) shrekris@Shreyas-MacBook-Pro ray % gcc --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Reproduction script

Clone Ray from the latest `master` and try building it by following [the docs](https://docs.ray.io/en/master/ray-contribute/development.html#building-ray-on-linux-macos-full).

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
Those lines seem to have been added by this PR: https://github.com/ray-project/ray/pull/41515/files#diff-c4cd2c2ae0cc025f39ffc802bf3da4d772f511ffbf76b11997615165f0d1c25cR28-R42

**Comment by shrekris-anyscale** [comment]
For now, one workaround is to comment out [this build configuration line](https://github.com/ray-project/ray/blob/5edabc7b2f92712982b0e590f739eb0110d80176/.bazelrc#L47) and then run `pip install -e . --verbose` as usual. The warnings still show up, but the build proceeds. I'm not sure what the consequences are, but I verified that I can run a simple Ray program:

```
(ae) shrekris@Shreyas-MacBook-Pro python % python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:21:23) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> from ray import serve
>>> ray.init()
2023-12-10 01:24:16,032	INFO worker.py:1746 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
RayContext(dashboard_url='127.0.0.1:8265', python_version='3.8.12', ray_version='3.0.0.dev0', ray_commit='{{RAY_COMMIT_SHA}}', protocol_version=None)
>>> @ray.remote
... def f():
...     return "hello"
... 
>>> ray.get(f.remote())
'hello'
```

**Comment by jjyao** [comment]
The PR is already reverted.
