### ISSUE TITLE
[Runtime] Release test ml_user_tune_rllib_connect_test.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41819]
### What happened + What you expected to happen

https://buildkite.com/anyscale/runtime-release/builds/431#018c5b87-314a-401e-b5d1-2d4c2d35b3f0

`ray.rllib.examples.tune.framework` cannot be found

### Versions / Dependencies

Runtime

### Reproduction script

Runtime

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
PR merged. Closing this issue.
