### ISSUE TITLE
Issue on page /train/train.html

### ISSUE THREAD

**Issue by Han-taz** [ray-project/ray#41823]
The following error occurs when using the Hugging Face Trainer.

ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.

**Comment by justinvyu** [comment]
@Han-taz Which example are you running into difficulties with? (could you provide a link/code snippet?)

**Comment by matthewdeng** [comment]
Hey @Han-taz, the `HuggingFaceTrainer` is deprecated. Could you take a look at this [Get Started with Hugging Face Transformers](https://docs.ray.io/en/releases-2.8.1/train/getting-started-transformers.html) guide and see if it solves the problem for you?
