### ISSUE TITLE
[Runtime] Release test many_nodes_actor_test_on_v2.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#41820]
### What happened + What you expected to happen

https://buildkite.com/anyscale/runtime-release/builds/431#018c5bc5-460d-48f8-af78-6f987b5b4565

Test finished successfully!
(DashboardTester pid=6081) 404 Client Error: Not Found for url: http://10.0.15.49:8265/log_index

### Versions / Dependencies

runtime

### Reproduction script

runtime

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
Ah it is due to changes from log API.

@rickyyx do you know which API we should use in this case?

**Comment by rickyyx** [comment]
I believe this is the /v0/api/logs

**Comment by rickyyx** [comment]
why it's failing now only? That change has been there for at least 1 week+?

**Comment by rickyyx** [comment]
Gotcha - was there a oss counter part failure?

**Comment by can-anyscale** [comment]
OSS tests are passing just fine

**Comment by can-anyscale** [comment]
Latest oss run: https://buildkite.com/ray-project/release-tests-branch/builds/2386#018c5b2f-bf93-459d-81e0-99c845a070ce

**Comment by rickyyx** [comment]
interesting - i would expect both oss/runtime affected by this change assuming they are essentially the same test/code base/test runner?

**Comment by rkooo567** [comment]
@can-anyscale btw, while we should fix the dashboard tester, it shouldn't affect the test result (test still should pass). dashboard tester runs in a separate actor and just prints logs when query fails, but it doesn't fail the test.

```
[ERROR 2023-12-12 02:39:39,710] util.py: 137  Retry function call failed due to An error occurred (404) when calling the HeadObject operation: Not Found in 10 seconds...

<br class="Apple-interchange-newline">
```

I suspect this is the actual error?

**Comment by rkooo567** [comment]
also verified OSS error has the same message as dashboard tester failure. So runtime failure is not related to test itself (but should be related to the ray_release issue). If you look at job logs, it successfully finished the test

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/41864 This PR fixes the dashboard tester error messages, but that error message should be unrelated to the failure. From the logs, the test itself seems passing. @can-anyscale I am going to remove a release blocker in this case?

**Comment by can-anyscale** [comment]
@rkooo567 SGTM!

**Comment by rkooo567** [comment]
@can-anyscale can I close this? Or do you want to keep it open for investigation?

**Comment by can-anyscale** [comment]
@rkooo567 let's close, the test is passing now on runtime ;)
