### ISSUE TITLE
[DOCS Theme] Change the theme of the top navigation bar 

### ISSUE THREAD

**Issue by simran-2797** [ray-project/ray#41838]
### Description

1. Change the theme and styles of the top nav bar
2. Add a gradient to the background (gradient colors are different for light mode and dark mode)

Figma - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=1%3A176&mode=design&t=vSJREt0q8rq72Tu8-1

**Comment by peytondmurray** [comment]
Quick update: this issue is on hold until a few questions about the design are resolved.

**Comment by peytondmurray** [comment]
A few notes on scope of work, as the designs show some changes which needed clarification:

1. The logo shouldn't be changed to the gradient in the design; we will keep it as-is
2. The new navbar background colors in dark and light mode _also_ apply globally to `--pst-color-on-background`
3. The new navbar shouldn't drop the chevrons as per the design - we will keep them as-is
4. Although the styles of the search button have been modified, no change in behavior is implied by these changes. We will be keeping the current behavior (i.e. the "search bar" is just a button that opens up a modal dialog where users can search)
5. The currently active page is bolded in the top nav bar, not just `Docs`
