### ISSUE TITLE
f() takes 0 positional arguments but * were given

### ISSUE THREAD

**Issue by ppo55665566** [ray-project/ray#4184]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: source(pip)
- **Ray version**: 0.6.2
- **Python version**: 3.6.0
- **Exact command to reproduce**:

### Describe the problem

I use ray to parallel my function, but sometimes the code gets wrong. f() takes 0 positional but 4 were given. This seems my remote function get_frames_ray not found. I'm sure this function is there and with @ray.remote annotation
### Source code / logs

the traceback info is as follows:
File "preprocess_main1.py", line 52, in main
    splitdirs, phtodirs = do_work(args[0], args[1], args[2], args[2], args[3])
  File "preprocess_main1.py", line 160, in do_work
    [get_frames_ray.remote(id, param[0], param[1], di) for param in params])
  File "/data/env/anaconda/envs/tensorflow/lib/python3.6/site-packages/ray/worker.py", line 2202, in get
    raise value
ray.worker.RayTaskError: ray_worker (pid=42899, host=cslg-data-mgai-10-200-16-91)
TypeError: f() takes 0 positional arguments but 4 were given

**Comment by pcmoritz** [comment]
Hey, thanks for the report! Can you attach a full minimal example to reproduce this?

**Comment by ppo55665566** [comment]
OK, in my project, there are one python packages, in package A, I defined a remote function get_frames_ray in a.py, and call this function in the same package, but in b.py. The code is like this,

MyProject/packageA/a.py:
import ray
@ray.remote
def get_frames_ray(param1, param2, param3, params):
    print(param1, param2, param3, params)
    return param2

MyProject/packageA/b.py:
from a import get_frames_ray
import ray
ray.init(num_cpus=4)
params=[('a', 'b'), ['c', 'd']]
id='123'
di='456'
result = ray.get([get_frames_ray.remote(id, param[0], param[1], di) for param in params])

**Comment by ppo55665566** [comment]
Plus, in the code I attached before, the import code can only wirte like from a import get_frames_ray, when I use from packageA.a import get_frames_ray, the function call will perform normally in pycharm, but when I run this code in command line, it will raise the TypeError: f() takes 0 positional arguments but 4 were given sometimes, I already added packageA's path to sys.path

**Comment by alvarodemig** [comment]
Any update? im having the same issue

**Comment by robertnishihara** [comment]
@alvarodemig no update at the moment, though it should be easy to work around by not using `*` in the function signature.

**Comment by vaibhavsingh007** [comment]
Facing same issue when reading a csv using modin.pandas.read_csv().
Stack trace excerpt: 

~/.local/lib/python3.6/site-packages/modin/engines/ray/generic/io.py in _read_csv_from_file_ray(cls, filepath, kwargs)
    490         # or based on the column(s) that were requested.
    491         if index_col is None:
--> 492             row_lengths = ray.get(index_ids)
    493             new_index = pandas.RangeIndex(sum(row_lengths))
    494         else:

~/.local/lib/python3.6/site-packages/ray/worker.py in get(object_ids)
   2245             if isinstance(value, RayError):
   2246                 last_task_error_raise_time = time.time()
-> 2247                 raise value
   2248 
   2249         # Run post processors.

RayTaskError: ray_worker (pid=209, host=vsingh3-v3-jupyterhub-vsing20-1-m7bwl)
TypeError: f() takes 0 positional arguments but 6 were given

**Comment by richardliaw** [comment]
Closing because stale but feel free to reopen (with a reproducible example).

**Comment by iamihgam** [comment]
One can define it under a class as below and adding self since @staticmethod does not work with ray to avoid self
@ray.remote
class  frames:
       def __init__(self, param1, param2, param3, param4, params)
              self.param1 = param1
              self.param2 = param2
              self.param3 = param3
             self.param4 = param4

       def get_frames_ray(param1, param2, param3, params):
                 print(param1, param2, param3, params)
                 return param2

results can be called by  get_frames.remote(p1,p2, etc) or ray.get( ) method
