### ISSUE TITLE
[Core] long_running_many_actor_tasks.aws failed

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#41866]
### What happened + What you expected to happen

Seems like the test failed because the dashboard agent exits. 

https://buildkite.com/ray-project/release-tests-branch/builds/2384#018c5b33-27f0-461e-a406-b332beab2b0e

Trying to repro in this PR https://github.com/ray-project/ray/pull/41865

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by rkooo567** [comment]
@architkulkarni when you retried, did it pass? It seems like the failure is from the release branch

**Comment by architkulkarni** [comment]
<img width="1264" alt="Screenshot 2023-12-13 at 1 17 39 PM" src="https://github.com/ray-project/ray/assets/5459654/76af7849-a963-4017-a0e9-598dcd7ac9f2">
@rkooo567 from your link https://buildkite.com/ray-project/release-tests-branch/builds/2384#018c5b33-27f0-461e-a406-b332beab2b0e, it looks like it was automatically retried and passed.

**Comment by rynewang** [comment]
This test is passing for a long time. Should close.

https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=berd0AzZYMfocS5-Kj3TIMU938dGP5y0LrTaPX-nWgDX1vSoikN_cQUkzdaJbQyF

<img width="1171" alt="image" src="https://github.com/ray-project/ray/assets/56065503/74415acb-c6fc-4f6b-aaf7-f1f434959eab">
