### ISSUE TITLE
[tune] Restoring trial results in confusing log results.

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4187]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.2
- **Python version**: 3.6
- **Exact command to reproduce**: n/a

### Describe the problem
When tune restores a failed trial it automatically *appends* all the results to the csv of the old result. This results in a confusing series like this:
![newplot 72](https://user-images.githubusercontent.com/2308543/53515263-67023900-3a7e-11e9-98e8-f12f42493ec9.png)

Here, two of the trials failed at around 250 steps due to a preempted instance. Tune correctly restores those runs, but the output is confusing because the first 250 steps are present twice in the csv.

My suggestion is: when restoring a trial, create a backup of the old csv, and then for the restored trial, clear the results beyond the restore point before appending new results to it.

Any thoughts @ericl @richardliaw?

**Comment by ericl** [comment]
There's this time since last restore metric which makes this clear. Btw. If
you have checkpoints, then having it in a single file makes more sense
since the disruption is much less.

**Comment by richardliaw** [comment]
I think it's a limitation of the visualization framework (viskit) not to be able to support different X-axis values.

To work around this, one option would be to just use a custom logger which implements your proposal (or push upstream this logger, called something like `ViskitLogger` that does this) I think for the generic Tune CSVLogger (that one can process with pandas or something), keeping it in one file would be OK (and consistent with other default loggers).

**Comment by ericl** [comment]
What I'm saying is that this is the "correct" visualization -- if you have checkpointing enabled. The fact that it drops to zero is just because the trial could not find a checkpoint to resume from.

You could also write a script that looks for "time_since_restore" and rewrites the CSVs to remove the earlier data.

**Comment by hartikainen** [comment]
I would actually argue that this is not just a limitation with the visualization. Suppose a case where my experiment lasts for 5 episodes and fails and restores once after the second iteration. The `training_iteration` values in the csv series would end up looking something like: `1,2,1,2,3,4,5`, and no matter what visualization I use, it would end up being weird looking graph because the x-axis values are not unique.

The same thing that happens with Viskit also happens on tensorboard:
![image](https://user-images.githubusercontent.com/2308543/53523885-e0a42200-3a92-11e9-9f49-72bfdaaea23f.png)

I could use the relative or wall clock time as the x-axis here, but I don't think that's a good option either because I would want to align multiple series based on their x-values. Here's what the relative time looks like on tensorboard:
![image](https://user-images.githubusercontent.com/2308543/53524045-4690a980-3a93-11e9-909d-9cda1a958d12.png)

**Comment by hartikainen** [comment]
@ericl your suggestion about script that looks for `time_since_restore` is what I'm doing at the moment, but I don't think that's the best user experience for this. Are there any cases where you would by default need to access the part of the result that has been rerun?

**Comment by ericl** [comment]
Well as I mentioned, if you have checkpointing enabled then the graph will
look relatively normal. Also with things like PBT it is useful to have the
timeline be complete.

**Comment by hartikainen** [comment]
Even with checkpointing enabled, I personally think it would be better to have the x-axes be aligned. I fully agree about the PBT case though.

I think I can live with the custom cleanup scripts for now. Maybe more users have the same issue we should figure out a way to handle this.

**Comment by hartikainen** [comment]
Here's my script for cleaning the results if anyone else needs to do something similar: https://gist.github.com/hartikainen/1226bd3ab5cddc6ae6d8fc373b42a9bd
