### ISSUE TITLE
[CI] `linux://python/ray/tests:test_gcs_fault_tolerance` is failing/flaky on master.

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#41879]
....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tests:test_gcs_fault_tolerance-END
....

**Comment by rickyyx** [comment]
Should be fixed by https://github.com/ray-project/ray/pull/41846

**Comment by anyscalesam** [comment]
passing
