### ISSUE TITLE
Duplicate tags caused `git pull` always assume that there are new tags to be synchronized

### ISSUE THREAD

**Issue by jiwq** [ray-project/ray#41872]
### What happened + What you expected to happen

When I execute the `git pull` command always output the below info which annoys me.
```
(raydev) ➜  ray git:(master) git pull
From github.com:ray-project/ray
 * [new tag]               ray-1.12.0 -> ray-1.12.0
 * [new tag]               ray-1.5.1  -> ray-1.5.1
 * [new tag]               ray-1.12.0 -> ray-1.12.0
 * [new tag]               ray-1.5.1  -> ray-1.5.1
Already up to date.
```

I checked the tag list found the duplicate tags and as I know git is case-insensitive, but I don't know why it exists in ray project.
<img width="304" alt="Screenshot 2023-12-14 at 01 33 59" src="https://github.com/ray-project/ray/assets/1187607/baf8225c-6268-439b-a65c-fc1f7146bd43">

<img width="303" alt="Screenshot 2023-12-14 at 01 26 19" src="https://github.com/ray-project/ray/assets/1187607/61071d39-8cb6-4ee0-bcdf-bb630d4b72c9">

Should we can delete the `Ray-1.5.1` and `Ray-1.12.0`?

### Versions / Dependencies
OS version: macOS 14.1.2
git version: 2.39.3 (Apple Git-145)

### Reproduction script

```
(raydev) ➜  ray git:(master) git pull
From github.com:ray-project/ray
 * [new tag]               ray-1.12.0 -> ray-1.12.0
 * [new tag]               ray-1.5.1  -> ray-1.5.1
 * [new tag]               ray-1.12.0 -> ray-1.12.0
 * [new tag]               ray-1.5.1  -> ray-1.5.1
Already up to date.
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by anyscalesam** [comment]
@aslonnie do you have rights to do this (I do not).

**Comment by aslonnie** [comment]
deleted.

**Comment by aslonnie** [comment]
fwiw, git tag itself is not always case sensitive. it depends on the filesystem's filename implementation.

**Comment by aslonnie** [comment]
but we should make the repo osx/windows friendly anyways, so nice find.
