### ISSUE TITLE
[Doc] Pressing ray-core -> example drop down expands wrong place

### ISSUE THREAD

**Issue by MaxVanDijck** [ray-project/ray#41933]
### Description

Pressing the arrow for the `Examples` drop down under the ray core docs opens the `User Guides` drop down, see attached screen recording

https://github.com/ray-project/ray/assets/50382570/2ed9fd33-7072-45f9-930d-e7208f82621a

*However* clicking on the work `example` itself does the correct behaviour

https://github.com/ray-project/ray/assets/50382570/4c1f5e06-5507-4adb-bf96-893ae1be37e8

### Link

https://docs.ray.io/en/latest/ray-core/patterns/limit-pending-tasks.html

**Comment by jjyao** [comment]
Confirmed it's fixed in 2.9.0
