### ISSUE TITLE
Ability to use Ray Debug with VS Code Remote Debugging

### ISSUE THREAD

**Issue by alikleit** [ray-project/ray#41953]
### Description

Right now, we are able to debug ray scripts using Terminal and following the guidelines provided by the Ray Debug documentation, where `ray debug` starts a debugging session in the Terminal, and preview the list of available breakpoints across a cluster as indexes to start the process. 

We would like to have the ability to use Ray Debug with VS Code Remote Debugging as an enhancement and a more user-friendly way for debugging.

### Use case

With the ability to attach Ray Debug to VS Code Remote Debugging, this feature will allow us to interactively step through the breakpoints and inspect variables with the standard way of the vs code editor, and possibly with pycharm.

For that, I've asked  if the feature is currently enabled via the ray forum under this [link](https://discuss.ray.io/t/vscode-breakpoint-will-be-bypassed-even-with-local-mode-true/8493/6?u=alikleit) where we did not get a reply. Posted the same question on Slack where a member of the ray team responded that It’s not supported yet. and you may add this support in the future.

Any updates or insights regarding the feasibility of this enhancement would be valuable

Thanks!

**Comment by anyscalesam** [comment]
currently this is unplanned but we may consider this in the future! closing this for now

**Comment by mgerstgrasser** [comment]
For anyone who might end up here from google: This is actually possible! Following the [debugpy documentation](https://github.com/microsoft/debugpy?tab=readme-ov-file), put the following into your code, somewhere  early on in the ray actor you want to debug (e.g., inside the constructor):
```
import debugpy
debugpy.listen(("localhost", 5678))
```
Then, create a "Python: Remote Attach" debug configuration in VS Code and point it to port 5678. If you have multiple copies of that actor, figure out some sort of local rank and add that to the port number, or similar.

@anyscalesam FYI, in case this is still something you're looking into.

**Comment by mgerstgrasser** [comment]
@anyscalesam Would it make sense to add a brief note to the Ray documentation about this? It's not just VS Code, PyCharm has a similar functionality (see https://github.com/ray-project/ray/issues/14005#issuecomment-802842126 ), but it's not apparent at all right now from the documentation that it's possible to debug Ray through any kind of IDE.

**Comment by anatolii-kabanov** [comment]
Addition to @mgerstgrasser (Thank you by the way). Who would like to use vs code to debug ray. Here is the launch config to attach to any process:
```
{
      "name": "Attach to Process",
      "type": "debugpy",
      "request": "attach",
      "processId":"${command:pickProcess}",
      "pathMappings": [
        { "localRoot": "${workspaceFolder}", "remoteRoot": "." },
      ],
}
```
After the launch of your app and your actors. You can find all live actor processes via that "Attach to Process" launch with the name or with PID: 
![image](https://github.com/ray-project/ray/assets/59233507/1d044f6e-f3c7-4a9f-8c24-3dbb78707091)
and choose a remote process that you would like to attach.

To definitely reach breakpoint you may be required to use _debugpy.breakpoint()_ directly in your ray function and put vs code breakpoint anywhere in this function after _debugpy.breakpoint()_:

```
 def actor_function(self):
    import debugpy
    debugpy.breakpoint()

```

**Comment by dddraxxx** [comment]
I use the following code to debug:
```
try:
    import debugpy
    debugpy.listen(5678)
    print("\033[92mDebugger waiting\033[0m")
    debugpy.wait_for_client()
except:
    print("\033[91mError in debugpy\033[0m")
```
this is easier to stop and no need to control on which rank.

**Comment by exped1230** [comment]
Ray debugger is very convenient: https://www.aidoczh.com/ray/ray-observability/ray-distributed-debugger.html
