### ISSUE TITLE
[data] Allow Dataset to be split based on row value

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#41969]
### Description

Dataset.split() and Dataset.split_at_indices() both split based on the number of rows, but sometimes it is useful to be able to split on the row value.

### Use case

During training, creating test datasets that are based on the data itself, e.g., based on timestamp.

**Comment by stephanie-wang** [comment]
There may be a good enough workaround here by calling Dataset.filter() twice.

**Comment by richardliaw** [comment]
Closing this in favor of https://github.com/ray-project/ray/issues/45634
