### ISSUE TITLE
Long-running Ray task does not return/shut-down, causing ray.get to block forever

### ISSUE THREAD

**Issue by sfriedowitz** [ray-project/ray#41960]
### What happened + What you expected to happen

We are running into an issue where a Ray task doing some long-lasting computation does not properly return/shut down, causing a call to `ray.get` to block forever on its completion. In the real application, this task is using GPUs to run an evaluation benchmark against a machine learning model, which can take upwards of 1-2 hours. 

However, I have been able to reproduce the issue with dependency-free code that just involves a sleeping loop within the remote task. Please see the reproduction script below.

Here are some symptoms I've identified of the issue:
- The remote task stays alive in a running state forever. Using various debugging statements within the code, I have been able to verify that the task does run without error and reach the return statement of the remote function.
- This hanging behavior only occurs on tasks lasting in the range of 1.5-2 hours. This is rather empirical, but the same code (in both the live application and the repro script) will finish and shut down if it takes less time than this.
- I have observed this issue regardless of whether or not we request GPUs on the remote task. Setting `num_cpus=1, num_gpus=0` shows the same behavior.

Questions I have:
- I am by no means an expert using the Ray Core API. Am I simply doing something wrong in how I am configuring and executing the task?
- Because the live application can run for >=2 hours and require GPUs, I have tried to avoid running the heavy portions on the entrypoint directly in favor of the `ray.remote` task. Is this best practice?
- If this is a known issue, are there any fixes that you can suggest trying?

### Versions / Dependencies

ray[default]==2.7.0

### Reproduction script

Here is the entrypoint executed via the Ray jobs API:

```
import ray
import time
import datetime


@ray.remote
def remote_task(task_length: float) -> float:
    task_end_time = time.time() + task_length
    while True:
        if time.time() > task_end_time:
            break
        print("Task going to sleep...")
        time.sleep(10)
    print("Task finished sleeping -- returning.")
    return task_end_time


if __name__ == "__main__":
    task_length = datetime.timedelta(hours=2).seconds
 
    # The reason for using `.options` to specify the `num_cpus` and `num_gpus` 
    # is that in the live application, we pass these values dynamically to the entrypoint.
    remote_func = remote_task.options(num_cpus=1, num_gpus=1)
    
    print("Waiting on remote...")
    result = ray.get(remote_func.remote(task_length))
    print(f"Obtained remote result: {result}")
```

### Issue Severity

None

**Comment by rkooo567** [comment]
I am running this to see if I can reproduce the issue.

**Comment by ruisearch42** [comment]
I ran the script with (num_cpus=1, num_gpus=0) and was not able to reproduce:
```
(remote_task pid=8024) 2024-03-06 00:31:12.447930: Task going to sleep...
(remote_task pid=8024) 2024-03-06 00:31:22.454542: Task going to sleep...
(remote_task pid=8024) 2024-03-06 00:31:32.463040: Task going to sleep...
(remote_task pid=8024) 2024-03-06 00:31:42.471519: Task going to sleep...
(remote_task pid=8024) 2024-03-06 00:31:52.480599: Task going to sleep...
Obtained remote result: 1709714301.033468
(remote_task pid=8024) Task finished sleeping for 7200 seconds -- returning.
```

I used Ray 2.9.3 and modified the script a little (for more debug statements):
```
import ray
import time
import datetime


@ray.remote
def remote_task(task_length: float) -> float:
    task_end_time = time.time() + task_length
    while True:
        if time.time() > task_end_time:
            break
        c = datetime.datetime.now()
        print(f"{c}: Task going to sleep...")
        time.sleep(10)
    print(f"Task finished sleeping for {task_length} seconds -- returning.")
    return task_end_time


if __name__ == "__main__":
    task_length = datetime.timedelta(hours=2).seconds

    # The reason for using `.options` to specify the `num_cpus` and `num_gpus`
    # is that in the live application, we pass these values dynamically to the entrypoint.
    remote_func = remote_task.options(num_cpus=1, num_gpus=0)

    print("Waiting on remote...")
    result = ray.get(remote_func.remote(task_length))
    print(f"Obtained remote result: {result}")
```

**Comment by ruisearch42** [comment]
A second try gave me the same result:

```
(remote_task pid=35768) 2024-03-06 12:43:52.959127: Task going to sleep...
(remote_task pid=35768) 2024-03-06 12:44:02.960327: Task going to sleep...
(remote_task pid=35768) 2024-03-06 12:44:12.966625: Task going to sleep...
Obtained remote result: 1709758690.668441
(remote_task pid=35768) Task finished sleeping for 7200 seconds -- returning.
```

**Comment by anyscalesam** [comment]
Closing as unable to repro since no response from @sfriedowitz  - ty @ruisearch42 for looking into it.
