### ISSUE TITLE
Reduce the times for flushing json object to log_file

### ISSUE THREAD

**Issue by adoda** [ray-project/ray#4197]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: source
- **Ray version**: master
- **Python version**: python 2.7
- **Exact command to reproduce**:

### Describe the problem

The code for JsonLogger:
```python
143 class _JsonLogger(Logger):
144     def _init(self):
145         config_out = os.path.join(self.logdir, "params.json")
146         with open(config_out, "w") as f:
147             json.dump(
148                 self.config,
149                 f,
150                 indent=2,
151                 sort_keys=True,
152                 cls=_SafeFallbackEncoder)
153         config_pkl = os.path.join(self.logdir, "params.pkl")
154         with open(config_pkl, "wb") as f:
155             cloudpickle.dump(self.config, f)
156         local_file = os.path.join(self.logdir, "result.json")
157         self.local_out = open(local_file, "a")
158
159     def on_result(self, result):
160         json.dump(result, self, cls=_SafeFallbackEncoder)
161         self.write("\n")
162
163     def write(self, b):
164         self.local_out.write(b)
165         self.local_out.flush()
166
167     def flush(self):
168         self.local_out.flush()
169
170     def close(self):
171         self.local_out.close()
```
When we write a result using JsonLogger, it will call:
```python
json.dump(result, self, cls=_SafeFallbackEncoder)
```
The 'json.dump' while call 'self.write' for writing object to file, it will call many times for one result.
For example, in the case of 'SimpleCorridor', it will call 600 times for one result.

So, when we writing log to remote distributed filesystem, one call 'flush function' may cost 10~100ms which depends on the network performance.

So it may cost a lot of time to flush one json result.

We could call 'flush' in the function of 'on_result', then it will flush one time for one result.

**Comment by richardliaw** [comment]
Closed by #4198.
