### ISSUE TITLE
Failure in the test of plasma manager failure.

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#420]
It happened here: https://travis-ci.org/ray-project/ray/builds/217422276

The relevant part of the log:
```
testPlasmaManagerFailed (__main__.ComponentFailureTest) ... Exception in thread Thread-1:

[...]

[INFO] (/Users/travis/build/ray-project/ray/src/plasma/plasma_store.cc:791) Disconnecting client on fd 17

/Users/travis/.travis/job_stages: line 53: 20869 Abort trap: 6           python test/component_failures_test.py
```

I cannot reproduce it locally.

**Comment by robertnishihara** [comment]
Hm, maybe the local scheduler is exiting and killing the driver, perhaps in https://github.com/ray-project/ray/blob/227c916c250020cd362345f533f9d01f76264a64/src/local_scheduler/local_scheduler.cc#L190.

It's possible the same thing is going on in #383.

**Comment by robertnishihara** [comment]
Closing this because I have not seen this failure in a long time. The test has been failing a lot, but with the error described in #871.
