### ISSUE TITLE
 Performance Testing of Ray and torchrun

### ISSUE THREAD

**Issue by Lvjinhong** [ray-project/ray#42006]
I'm very fortunate to see such an excellent high-performance distributed engine. However, I have some questions during usage. I've been using torchrun to initiate distributed inference, but recently, I noticed some impact on speed when using Ray. Here, I just want to inquire about some general strategies rather than specific details:

Does Ray's general distributed solution sacrifice certain performance compared to torchrun?

**Comment by anyscalesam** [comment]
hey @Lvjinhong glad to see you joining the community; these sort of questions are best discussed in discourse and/or in our Slack. 

Can you ask the same question there and I can route to the right folks at Anyscale who can address your question (you'll get much better response from community members as well there).

**Comment by anyscalesam** [comment]
https://discuss.ray.io/

Sign up for Slack access here: https://docs.google.com/forms/d/e/1FAIpQLSfAcoiLCHOguOm8e7Jnn-JJdZaCxPGjgVCvFijHB5PLaQLeig/viewform

**Comment by Lvjinhong** [comment]
> https://discuss.ray.io/
> 
> Sign up for Slack access here: https://docs.google.com/forms/d/e/1FAIpQLSfAcoiLCHOguOm8e7Jnn-JJdZaCxPGjgVCvFijHB5PLaQLeig/viewform

thanks
