### ISSUE TITLE
ray.init 无法启动，执行命令一直卡在此处

### ISSUE THREAD

**Issue by ocuiz** [ray-project/ray#42010]
### What happened + What you expected to happen

import ray 
ray.init()
我在本地使用这个命令的时候，目前就一直卡在这里
按道理会输出初始化的Ray集群的信息

然而目前没有相关日志

考虑是我升级了我的macos系统版本后发生的这个情况，我在macOS Ventura | 13.6.2版本还是没有问题的，前几天升级了
macOS Sonoma | 14.1.2之后就发现了这个问题

### Versions / Dependencies

ray | 2.1.0
cloudpickle | 1.6.0
protobuf | 4.23.4
python | 3.9
macOS Sonoma | 14.1.2

### Reproduction script

import ray 
ray.init()
<img width="522" alt="截屏2023-12-19 21 06 17" src="https://github.com/ray-project/ray/assets/77309066/4d9db835-1bad-4dfc-a951-0439e68af762">

### Issue Severity

None

**Comment by ocuiz** [comment]
谢谢各位，已经解决了，更换了原本grpcio==1.60.0 为 grpcio==1.44.0 即可，有需要的小伙伴可以参考尝试一下

**Comment by jjyao** [comment]
The issue is resolved by using grpcio 1.44.0. You can also try to upgrade Ray to the latest version.
