### ISSUE TITLE
Error installing Ray "/usr/bin/env: 'python': No such file or directory".

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4202]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source at 4dc683d39ee9ecf45e6a8339deb11128731b12e8
- **Ray version**: 0.7.0.dev0
- **Python version**: Python 3.6.3 :: Anaconda, Inc.

Python is installed.

```
$ which python
/home/ubuntu/anaconda3/bin/python
$ which pip
/home/ubuntu/anaconda3/bin/pip
```

Yet `pip install -e . --verbose fails with

```
    ERROR: /home/ubuntu/ray/BUILD.bazel:363:1: Executing genrule //:python/ray/_raylet.pyx_cython_translation failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

    Use --sandbox_debug to see verbose messages from the sandbox
    /usr/bin/env: 'python': No such file or directory
    Target //:ray_pkg failed to build
```

I also tried with `--verbose_failures --sandbox_debug`, but didn't see any additional interesting information.

Full log attached.
[log.txt](https://github.com/ray-project/ray/files/2917146/log.txt)

**Comment by richardliaw** [comment]
Should be fixed..? Generally, ray is hard to build ... but feel free to reopen.

**Comment by GithubZhitao** [comment]
I ALSO Meet this problem when I compile ray 2.9.0 on macOS Sonoma 14.2.1

Any one knows why ?

**Comment by avicennax** [comment]
Likewise hit this issue building running Ubuntu on WSL.
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
WSL version:
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.5039
```

Following: https://docs.ray.io/en/latest/ray-contribute/development.html#preparing-to-build-ray-on-linux; created a conda environment first. All other steps ran and completed successfully per the guide. Also seems like in the shell where I launch: `pip install -e . --verbose` - python is resolvable on my path, per:
```
ray/python on  master via 🐍 v3.10.16 via 🅒 raydev took 20s
13:57:26 ❯ /usr/bin/env python
Python 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:16:10) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by HiromuHota** [comment]
Had this issue and figured out what was missing.
I ran the same thing with debug/verbose and found that they run things with `PATH=/bin:/usr/bin:/usr/local/bin`.
```
ERROR: /home/ubuntu/workspace/ray/BUILD.bazel:3031:12: Executing genrule //:python/ray/_raylet.pyx_cython_translation failed: (Exit 127): linux-sandbox failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/4290ce986e8ce190cc1dd876b241b0e5/sandbox/linux-sandbox/2399/execroot/com_github_ray_project_ray && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    TMPDIR=/tmp \
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/install/20da5ab742b8d3d499c34fdafcd3c8b8/linux-sandbox -t 15 -w /home/ubuntu/.cache/bazel/_bazel_ubuntu/4290ce986e8ce190cc1dd876b241b0e5/sandbox/linux-sandbox/2399/execroot/com_github_ray_project_ray -w /tmp -w /dev/shm -S /home/ubuntu/.cache/bazel/_bazel_ubuntu/4290ce986e8ce190cc1dd876b241b0e5/sandbox/linux-sandbox/2399/stats.out -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 external/cython/cython.py --cplus python/ray/_raylet.pyx --output-file bazel-out/k8-opt/bin/python/ray/_raylet.cpp')
```

I had no `python` in any of `/bin`, `/usr/bin`, or `/usr/local/bin`. When I created one, the issue is gone. Hope this helps.

**Comment by my-vegetable-has-exploded** [comment]
"BAZEL_ARGS="--action_env=PATH" pip install -e . --verbose" 
This command works for me.
