### ISSUE TITLE
[Serve] Patching the asyncio-loop fails from Ray 2.8

### ISSUE THREAD

**Issue by Martin4R** [ray-project/ray#42035]
### What happened + What you expected to happen

We used the library nest-asyncio within our serve deployments with Ray 2.7. It patches the asyncio-eventloop.
In Ray 2.8 suddenly the asyncio-eventloop was replaced with a 'uvloop', which is non-patchable. 
This currently breaks our code.
Also this change is not mentioned in the release-notes of Ray 2.8, so that maybe other users with frameworks which expect the asyncio-loop to be patchable will run into this issue.

@sihanwang41 suggested a workaround on [Slack](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1702659586734409?thread_ts=1702647465.783779&cid=CNCKBBRJL) to set RAY_SERVE_DEBUG_MODE=1 to get the asyncio-eventloop back, but this would also enable other debug output etc. 

it would be good if there would be a proper option which only sets the eventloop back to the asyncio-eventloop without enabling other debug output.

This is somewhat related to https://github.com/ray-project/ray/issues/20169 because we currently use nest-asyncio to execute synchronous code within Ray serve and still be able to make .remote() calls to other serve deployments.

### Versions / Dependencies

Works in Ray 2.7, fails in Ray 2.8.
Python 3.10.8
nest-asyncio 1.5.8

### Reproduction script

import nest_asyncio  # https://pypi.org/project/nest-asyncio/  used in version 1.5.8

@serve.deployment()
class TestDeployment:
    def __init__(self):
        loop = asyncio.get_running_loop()
        nest_asyncio.apply(loop)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by alexeykudinkin** [comment]
@Martin4R uvloop is just being installed by default now with Serve, which by itself bumps up performance of HTTP/gRPC applications by about 10-20%.

However, it's not a requirement to use Serve and you can switch it off by simply removing uvloop from dependencies (in that case we'll fallback to use default Python asyncio impl.

**Comment by Martin4R** [comment]
Hi @alexeykudinkin ,
it is not that simple because uvloop comes as a transitive dependency of Ray serve. So I cannot exclude it. 
Can you therefore please reopen the ticket?

Details:
Ray serve installs uvicorn[standard] in the setup.py:
![image](https://github.com/ray-project/ray/assets/112665668/bfa3ce2a-09c3-4f65-b357-4e2acac25525)

uvicorn[standard] adds uvloop:
![image](https://github.com/ray-project/ray/assets/112665668/4c867cb3-3b51-4fc6-b353-c50f1e517d2d)

**Comment by alexeykudinkin** [comment]
`RAY_SERVE_DEBUG_MODE` currently exclusively controls whether we're using `asyncio` or `uvloop` and doesn't have any other side-effects so you should be good with that.

Are you asking for an explicit lever to control what loop is going to be used (like `RAY_SERVE_EVENT_LOOP_IMPL=asyncio`)?

**Comment by Martin4R** [comment]
Yes, I think the RAY_SERVE_EVENT_LOOP_IMPL would be a good solution. 
From RAY_SERVE_DEBUG_MODE=1 I would think of stuff like fine granular log level, maybe time measurements and other things which are necessary for debugging, that's why it feels not right to use this.
