### ISSUE TITLE
[Core] container runtime_env detecting `env_vars` when none specified

### ISSUE THREAD

**Issue by salotz** [ray-project/ray#42058]
### What happened + What you expected to happen

I was advised in #37293 to update to ray 2.9.0 that container runtime_env feature would be fixed. I just updated my cluster to run with `rayproject/ray:2.9.0-py311`. And confirmed versions on the dashboard.

I now get this:

```console
$ ray job submit --runtime-env-json '{"container": {"image": "rayproject/ray:2.9.0-py311"}}' -- python -V
Job submission server address: http://localhost:41000

-------------------------------------------------------
Job 'raysubmit_71P2PFNyQv8hwnnK' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_71P2PFNyQv8hwnnK
  Query the status of the job:
    ray job status raysubmit_71P2PFNyQv8hwnnK
  Request the job to be stopped:
    ray job stop raysubmit_71P2PFNyQv8hwnnK

Tailing logs until the job exits (disable with --no-wait):

---------------------------------------
Job 'raysubmit_71P2PFNyQv8hwnnK' failed
---------------------------------------

Status message: Failed to start supervisor actor raysubmit_71P2PFNyQv8hwnnK: 'The 'container' field currently cannot be used together with other fields of runtime_env. Specified fields: dict_keys(['container', 'env_vars'])'
```

### Versions / Dependencies

```console
$ ray --version
ray, version 2.9.0

$ python -V
Python 3.11.6
```

### Reproduction script

```sh
ray job submit --runtime-env-json '{"container": {"image": "rayproject/ray:2.9.0-py311"}}' -- python -V
```

I can post my cluster yaml if you think that would help, but it has templating etc. that makes it not so simple to post.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by ecm200** [comment]
I would like to add that I am seeing the same issue as well.
I formed the submission using the python sdk from the ray package, to submit the ray job submission type job using the class `JobSubmissionClient`. I confirmed that the dictionary relating to the `runtime_env` variable only has the entry for `container`.

```
2024-01-12 15:48:20.175 | INFO     | ray.dashboard.modules.job.sdk:submit_job:249 - Job Submission Request: JobSubmitRequest(entrypoint='/home/ray/anaconda3/bin/python /home/ray/entry.py nta-sim', submission_id='9ba5e6dcb2144c29bc8702f0d78ba1e3', job_id=None, runtime_env={'container': {'image': 'rayclusternodes.azurecr.io/mpdsim-1.2.0-ray-2.9.0:latest', 'worker_path': '/root/python/ray/_private/workers/default_worker.py', 'run_options': ['--cap-drop SYS_ADMIN', '--log-level=debug']}}, metadata={'entrypoint_num_cpus': '0', 'entrypoint_num_gpus': '0', 'resource': "{'headnode-num-cpus': 1}"}, entrypoint_num_cpus=0, entrypoint_num_gpus=0, entrypoint_memory=None, entrypoint_resources={'headnode-num-cpus': 1})
```

However, on submission, the job fails and reports the following:

```
Failed to start supervisor actor 9ba5e6dcb2144c29bc8702f0d78ba1e3: 'The 'container' field currently cannot be used together with other fields of runtime_env. Specified fields: dict_keys(['container', 'env_vars'])'
```



I am running `python 3.10.13` and `ray 2.9.0`.
I followed the recommendation to install `podman` into the standard ray docker image, and then deployed this to a Kubernetes Cluster. The base image used was `rayproject/ray:2.9.0-py310-cpu`.

**Comment by prd-tuong-nguyen** [comment]
same problem with you @ecm200

**Comment by sbag-cmt** [comment]
Using ray 2.10.0 on Databricks; seeing the same problem

**Comment by anyscalesam** [comment]
@zcin does the new runtime env as containers help mitigate this issue? (note still experimental)

**Comment by Phlip79** [comment]
I am running into the same issue on version 2.34.0. I suspect this is happening on the server-side as my job is being submitted successfully. I know my docker image has environment variables, possibly that's the root cause.

Why can `env_vars` and `container` not be set at the same time?

**Comment by Phlip79** [comment]
Looks like #42121 would fix this bug. I added a comment there.
