### ISSUE TITLE
[Docs] Update the homepage 

### ISSUE THREAD

**Issue by simran-2797** [ray-project/ray#42068]
### Description

Update the homepage of ray docs as per the new design - 
Light mode - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=129%3A1083&mode=design&t=pNlPOuLgqsCOAl2z-1
Dark mode - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=19%3A466&mode=design&t=pNlPOuLgqsCOAl2z-1

(Let's set a max width of the whole container so that it doesn't look odd on really big screen sizes)

cc: @angelinalg

**Comment by peytondmurray** [comment]
> (Let's set a max width of the whole container so that it doesn't look odd on really big screen sizes)

@simran-2797 Any update here? I'm working on this currently.
