### ISSUE TITLE
[Core] A way to disable RAY_task_events_report_interval_ms for particular actor.

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#42076]
### Description

For Serve, we want to disable RAY_task_events_report_interval_ms for proxy and replica actors since they introduce lots of traffic to GCS and those traffic cost money in the multi-AZ setup.

**Comment by jjyao** [comment]
cc @rickyyx @rkooo567 @edoakes

**Comment by rkooo567** [comment]
let's fix this in 2.10?

**Comment by rkooo567** [comment]
maybe we can have optional field to disable task metric collection?

**Comment by rickyyx** [comment]
Does it work with runtime env on the actor?

**Comment by jjyao** [comment]
Yea, that'll probably just work.

**Comment by khluu** [comment]
ETA fixed by Feb28/29 https://anyscaleteam.slack.com/archives/C01DVKB5SHE/p1709166053311979?thread_ts=1709165365.785589&cid=C01DVKB5SHE
