### ISSUE TITLE
Core: cannot build on windows

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#42098]
### What happened + What you expected to happen

I am trying to build ray 2.9.0 on windows. I tried copying exactly what is done in the [`.buildkite/windows_ci.sh`](https://github.com/ray-project/ray/blob/master/.buildkite/windows_ci.sh), which has worked for me in the past:
```
wget "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-windows-amd64.exe" -o C:\bazel\bazel.exe
SET BAZEL_PATH=C:\bazel\bazel.exe
SET BAZEL_SH=C:\Program Files\Git\bin\bash.exe
SET PATH=%PATH%;C:\bazel
python -m pip install . -vv
```

but this fails to build protobuf.

This is a minimal reproducer for the problems I am having with the conda-forge migration to 2.9.0 xref conda-forge/ray-packages-feedstock#135

### Versions / Dependencies

ray 2.9.0, python3.10, windows.

### Reproduction script

```
wget "https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-windows-amd64.exe" -o C:\bazel\bazel.exe
SET BAZEL_PATH=C:\bazel\bazel.exe
SET BAZEL_SH=C:\Program Files\Git\bin\bash.exe
SET PATH=%PATH%;C:\bazel
python -m pip install . -vv
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by mattip** [comment]
Is there a build log from a CI run I can look at to see how it compares?

**Comment by stephanie-wang** [comment]
Hi @mattip, you could take a look at the CI builds from master. Here's a link to the [build](https://buildkite.com/ray-project/oss-ci-build-branch/builds/7393#018ccad9-bcf8-4903-bb04-9bd3f3d92e02) from the latest commit.

**Comment by mattip** [comment]
Right, I looked at those logs and couldn't figure out where my build differs. The buildkite build uses a docker image, I wonder if something there is very different from my local setup (and Azure Build Pipeline as used by conda-forge) that is causing the build to fail.

**Comment by aslonnie** [comment]
assigning to @can-anyscale who optimized the Windows build on CI recently.

**Comment by can-anyscale** [comment]
it might be because the character limit on windows, can you try `https://github.com/ray-project/ray/blob/master/ci/env/install-bazel.sh#L128`

**Comment by mattip** [comment]
Thanks, adding `startup --output_user_root=d:/tmp` to `~/.bazelrc` did allow the build to complete. Closing.

**Comment by mattip** [comment]
This may be worth adding to the documentation about building on windows.
