### ISSUE TITLE
[serve] `NoneType` error in `test_websockets.py`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#42124]
I get the following noisy error message consistently on master from `test_websockets.py`:
```
tests/test_websockets.py::test_send_recv_text_and_binary
[None] 2023-12-28 12:33:37,339  INFO worker.py:1752 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(ProxyActor pid=88661) INFO 2023-12-28 12:33:39,189 proxy 127.0.0.1 proxy.py:1126 - Proxy actor e272e59b8f42243a00fb168101000000 starting on node f0d3af22761b6257dfd13a796b03ddeb3a8db1386fe23557207ad294.
(ProxyActor pid=88661) INFO 2023-12-28 12:33:39,191 proxy 127.0.0.1 proxy.py:1329 - Starting HTTP server on node: f0d3af22761b6257dfd13a796b03ddeb3a8db1386fe23557207ad294 listening on port 8000
(ProxyActor pid=88661) INFO:     Started server process [88661]
(ServeController pid=88659) INFO 2023-12-28 12:33:39,291 controller 88659 deployment_state.py:1567 - Deploying new version of deployment WebSocketServer in application 'default'. Setting initial target number of replicas to 1.
(ServeController pid=88659) INFO 2023-12-28 12:33:39,394 controller 88659 deployment_state.py:1851 - Adding 1 replica to deployment WebSocketServer in application 'default'.
PASSED(ProxyActor pid=88661) INFO:     ('127.0.0.1', 59728) - "WebSocket /" [accepted]
(ProxyActor pid=88661) INFO:     connection open
(ServeReplica:default:WebSocketServer pid=88663) INFO 2023-12-28 12:33:40,281 default_WebSocketServer y6cep0z2 eff5f22f-e7aa-456b-8aea-f646f0ad00b3 / replica.py:748 - __CALL__ OK 5.4ms
(ProxyActor pid=88661) ERROR:    Exception in ASGI application
(ProxyActor pid=88661) Traceback (most recent call last):
(ProxyActor pid=88661)   File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 203, in run_asgi
(ProxyActor pid=88661)     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
(ProxyActor pid=88661)   File "/Users/eoakes/miniforge3/envs/ray/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
(ProxyActor pid=88661)     return await self.app(scope, receive, send)
(ProxyActor pid=88661)   File "/Users/eoakes/code/ray/python/ray/serve/_private/proxy.py", line 1092, in __call__
(ProxyActor pid=88661)     await self.app(scope, receive, send_with_request_id)
(ProxyActor pid=88661)   File "/Users/eoakes/code/ray/python/ray/serve/_private/proxy.py", line 859, in __call__
(ProxyActor pid=88661)     await send(message)
(ProxyActor pid=88661)   File "/Users/eoakes/code/ray/python/ray/serve/_private/proxy.py", line 1085, in send_with_request_id
(ProxyActor pid=88661)     if message["type"] == "http.response.start":
(ProxyActor pid=88661) TypeError: 'NoneType' object is not subscriptable
```

**Comment by sihanwang41** [comment]
Sending `None` message doesn't make sense to me.  The serve [code](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/proxy.py#L1040) logic issue is that websockets server didn't send any message when it exists, so `proxy_asgi_receive_task` is not done, which makes the `status` is None. (this is a bug to me). But following two scenarios, one is causing the issue, the other one is not. I need to more investigation.

this is working script: (client send message to the server only)
```
from fastapi import FastAPI, WebSocket, WebSocketDisconnect

from ray import serve
import time
from websockets.sync.client import connect


app = FastAPI()

@serve.deployment
@serve.ingress(app)
class WebSocketServer:
    @app.websocket("/")
    async def ws_handler(self, ws: WebSocket):
        await ws.accept()

        try:
            msg = await ws.receive_text()
        except Exception:
            pass



serve.run(WebSocketServer.bind())

msg = "Hello from client"

url = "ws://localhost:8000/"
with connect(url) as websocket:

    websocket.send(msg)
```

this is having issue script (Server sends message to the client only).
```
from fastapi import FastAPI, WebSocket, WebSocketDisconnect

from ray import serve
import time
from websockets.sync.client import connect


app = FastAPI()

@serve.deployment
@serve.ingress(app)
class WebSocketServer:
    @app.websocket("/")
    async def ws_handler(self, ws: WebSocket):
        await ws.accept()

        try:
            await ws.send_text("hello from server")
        except Exception:
            pass

serve.run(WebSocketServer.bind())

msg = "Hello from client"

url = "ws://localhost:8000/"
with connect(url) as websocket:
    msg = websocket.recv()

    pass
```

**Comment by sihanwang41** [comment]
> Sending `None` message doesn't make sense to me. The serve [code](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/proxy.py#L1040) logic issue is that websockets server didn't send any message when it exists, so `proxy_asgi_receive_task` is not done, which makes the `status` is None. (this is a bug to me). But following two scenarios, one is causing the issue, the other one is not. I need to more investigation before i can make a fix confidentially.
> 
> this is working script: (client send message to the server only)
> 
> ```
> from fastapi import FastAPI, WebSocket, WebSocketDisconnect
> 
> from ray import serve
> import time
> from websockets.sync.client import connect
> 
> 
> app = FastAPI()
> 
> @serve.deployment
> @serve.ingress(app)
> class WebSocketServer:
>     @app.websocket("/")
>     async def ws_handler(self, ws: WebSocket):
>         await ws.accept()
> 
>         try:
>             msg = await ws.receive_text()
>         except Exception:
>             pass
> 
> 
> 
> serve.run(WebSocketServer.bind())
> 
> msg = "Hello from client"
> 
> url = "ws://localhost:8000/"
> with connect(url) as websocket:
> 
>     websocket.send(msg)
> ```
> 
> this is having issue script (Server sends message to the client only).
> 
> ```
> from fastapi import FastAPI, WebSocket, WebSocketDisconnect
> 
> from ray import serve
> import time
> from websockets.sync.client import connect
> 
> 
> app = FastAPI()
> 
> @serve.deployment
> @serve.ingress(app)
> class WebSocketServer:
>     @app.websocket("/")
>     async def ws_handler(self, ws: WebSocket):
>         await ws.accept()
> 
>         try:
>             await ws.send_text("hello from server")
>         except Exception:
>             pass
> 
> serve.run(WebSocketServer.bind())
> 
> msg = "Hello from client"
> 
> url = "ws://localhost:8000/"
> with connect(url) as websocket:
>     msg = websocket.recv()
> 
>     pass
> ```

Ignore the scenario described above, they both can be abstracted that serve code doesn't handle the scenario that websocket server is not sending disconnect message.
