### ISSUE TITLE
[Core] Nsys can't capture any information

### ISSUE THREAD

**Issue by onedayherocoming** [ray-project/ray#42139]
### What happened + What you expected to happen

I use Nsys feature  released in version 2.8.0, I use the code in doc. However, the file generated by nsys didn't have any information.

### Versions / Dependencies

ray 2.9.0
python 3.8

### Reproduction script

```
import torch
import ray
import cupy

ray.init()


@ray.remote(
    num_gpus=1,
    runtime_env={
        "nsight": "default",
    },
)
class RayActor:
    def run(self):
        a = torch.randint(0, 2, [128, 2, 2048, 2048]).cuda()
        b = torch.randint(0, 2, [128, 2, 2048, 2048]).cuda()
        for _ in range(10):
            c = a * b
        print("Result on GPU:", c)

ray_actor = RayActor.remote()
ray.get(ray_actor.run.remote())
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by onedayherocoming** [comment]
In addition, when I use the following code, I can obtain cuda information normally:
```
import torch
import ray
import time

ray.init()

@ray.remote(
    num_gpus=1,
    runtime_env={
        "nsight": {
            "-t": "cuda,cudnn,cublas,nvtx",
            "stop-on-exit": "true",
        }
    },
)
def run_indenpent():
    a = torch.randint(0, 2, [128, 2, 2048, 2048]).cuda()
    b = torch.randint(0, 2, [128, 2, 2048, 2048]).cuda()
    for _ in range(5):
        c = a * b
        time.sleep(0.01)
    print("Result on GPU:", c)

ray.get(run_indenpent.remote())
```

Why I can't get any information in class use case?

**Comment by simonguo-cohere** [comment]
I am experiencing similar issue too. In the ray log directly I don't see any nsys file being generated. I also ssh it into the worker and tried `nsys sessions list` but don't see any active nsys session. I might be missing something and would really appreciate your help!

**Comment by jjyao** [comment]
@simonguo-cohere I think you found the cause of your issue. Could you reply what your fix is. This might help the other user as well.

**Comment by simonguo-cohere** [comment]
Hey folks, I was able to debug the issue. I was not setting up the `nsight` logging arguments in the correct place to be included in runtime argument. A good way to check is to search the ray logs and see if `nsys` if successfully registered for runtime argument. Thanks @jjyao @cadedaniel  for your help and looking at the PR implementation #19631 really helped me.

**Comment by leo6022** [comment]
@simonguo-cohere I still don't understand how you fixed it. How to set nsight logging. Could you explain it in detail?

**Comment by simonguo-cohere** [comment]
@leo6022  apologies for the delay! I suggest starting with the small example on the Ray doc with `nsight` in the decorator arguments (that's all you really need if you are setting up Ray correctly), and check in the ray log (runtime argument) to see if that shows up!

**Comment by mystoryfantacy** [comment]
> @leo6022 apologies for the delay! I suggest starting with the small example on the Ray doc with `nsight` in the decorator arguments > `runtime_env` (that's all you really need if you are setting up Ray correctly), and check in the ray log (runtime argument) to see if that shows up!

Hello @simonguo-cohere  I check the runtime_env log, the nsys args used for ray.Actor are same as those for ray.Task. However the nsys can not capture gpu information on ray.Actor. it works well with the ray.Task. Do you have any idea about this situation. 

the test code is:
```python
@ray.remote(num_gpus=1, runtime_env={"nsight": "default"})
class RayActor:
    def run(self):
        with nvtx.annotate(message="ray_worker", color="green"):
              a = torch.tensor([1.0, 2.0, 3.0]).cuda()
              b = torch.tensor([4.0, 5.0, 6.0]).cuda()
              c = a * b
       print("Result on GPU:", c)

ray_actor = RayActor. remote()
ray . get (ray_actor. run. remote())

@ray. remote(num_gpus=1, runtime_env={"nsight": "default"})
def run2():
    with nvtx.annotate(message="ray_worker", color="green"):
        a = torch.tensor([1.0, 2.0, 3.0]).cuda()
        b = torch.tensor([4.0, 5.0, 6.0]).cuda()
        c = a * b

        print ("Result on GPU:", c)

ray.get(run2. remote())
```
nsys-report about RayActor (has no gpu information):
<img width="759" alt="image" src="https://github.com/ray-project/ray/assets/5829623/325970be-ebf0-4332-8683-3fb34d6fc9ab">

nsys-report about ray.Task run2 (do have gpu information):
<img width="1208" alt="image" src="https://github.com/ray-project/ray/assets/5829623/521b34ed-4475-4347-84f5-b4993f61084d">

Any help will be appreciated.

**Comment by warpmatrix** [comment]
I just met the same issue as @mystoryfantacy and also checked the `runtime_env_agent.log` and `raylet.out`, which shows it generated `.nsys-rep` expectedly and used the right arguments. @anyscalesam May be the issue should be reopen.

**Comment by crazy-JiangDongHua** [comment]
I also met the same issue as @mystoryfantacy, it generated .nsys-rep expectedly but has no gpu information when use vllm workers, which are actors. More detailed information [here](https://github.com/vllm-project/vllm/issues/5132).@anyscalesam May be the issue should be reopen.

**Comment by simonguo-cohere** [comment]
@mystoryfantacy for me nsys worked on a Ray.Actor setup since it is a dedicated Ray worker (single Python process which nsys could be launched with). 

@jjyao @cadedaniel would you have some insights that could help some of those folks?

**Comment by mystoryfantacy** [comment]
> @mystoryfantacy for me nsys worked on a Ray.Actor setup since it is a dedicated Ray worker (single Python process which nsys could be launched with).
> 
> @jjyao @cadedaniel would you have some insights that could help some of those folks?

I found a solution was to use -c (capture-range argument) and run cuda task more than once. Then the nsys can capture the gpu information while still missing the begin part.

**Comment by JackyMa1997** [comment]
@Rhys-Q sry to bother you, is the bug still here?

**Comment by mystoryfantacy** [comment]
I am not sure if the bug is still there. I had work around it to produce the nsys report on demand. Sorry I didn't have any more information on this problem.
________________________________
发件人: JackyMa ***@***.***>
发送时间: 2025年8月20日 19:52
收件人: ray-project/ray ***@***.***>
抄送: mystoryfantacy ***@***.***>; Mention ***@***.***>
主题: Re: [ray-project/ray] [Core] Nsys can't capture any information (Issue #42139)

[https://avatars.githubusercontent.com/u/130123145?s=20&v=4]JackyMa1997 left a comment (ray-project/ray#42139)<https://github.com/ray-project/ray/issues/42139#issuecomment-3205933031>

@Rhys-Q<https://github.com/Rhys-Q> sry to bother you, is the bug still here?

―
