### ISSUE TITLE
Ray deployment logging to stdout

### ISSUE THREAD

**Issue by feketedavid1012** [ray-project/ray#42133]
### What happened + What you expected to happen

Hi,
I'm trying to create a deployment with logging, but the logging doesn't work in the deployment endpoints.
This is the code what I use:
```
import logging
import ray
from fastapi.openapi.docs import get_swagger_ui_html
from ray import serve

app = FastAPI(debug=True)
ray.init(address="auto")
serve.start(detached=True,http_options={"host": "0.0.0.0", "port": 9000})

logger = logging.getLogger("ray.serve")
logger.info('API is starting up')


@serve.deployment(name="main")
@serve.ingress(app)
class ModelServer:
    def __init__(self):
        logger.info("Start")
        print("Start")
        self.model_path = "model"

    @app.get("/health")
    def get(self):
        logger.info("I'm healthy!")
        print("Healthy")
        return "Welcome to the model server."

    @app.get(
        "/docs",
        include_in_schema=False,
    )
    async def custom_swagger_ui_html(self):
        """Return the swagger docs route."""
        return get_swagger_ui_html(
            openapi_url=app.openapi_url,
            title=app.title + " - Swagger UI",
            oauth2_redirect_url=app.swagger_ui_oauth2_redirect_url,
        )


serve.run(ModelServer.bind(), route_prefix = "/")
```
The "API is starting up" and "Start" logs are show up, while the "I'm healthy" or "Healthy" don't. I guess it should be something with the uvicorn or HTTP logs (not connected to the stdout?), because when I used older ray version with uvicorn I could see every log properly.

### Versions / Dependencies

python = ">=3.8,<3.11"
fastapi = "^0.78.0"
ray = {extras = ["default"], version = "^2.9.0"}

### Reproduction script

app = FastAPI(debug=True)
ray.init(address="auto")
serve.start(detached=True,http_options={"host": "0.0.0.0", "port": 9000})

logger = logging.getLogger("ray.serve")
logger.info('API is starting up')

@serve.deployment(name="main")
@serve.ingress(app)
class ModelServer:
    def __init__(self):
        logger.info("Start")
        print("Start")
        self.model_path = "model"

    @app.get("/health")
    def get(self):
        logger.info("I'm healthy!")
        print("Healthy")
        return "Welcome to the model server."

    @app.get(
        "/docs",
        include_in_schema=False,
    )
    async def custom_swagger_ui_html(self):
        """Return the swagger docs route."""
        return get_swagger_ui_html(
            openapi_url=app.openapi_url,
            title=app.title + " - Swagger UI",
            oauth2_redirect_url=app.swagger_ui_oauth2_redirect_url,
        )

serve.run(ModelServer.bind(), route_prefix = "/")

### Issue Severity

None

**Comment by kevin85421** [comment]
* [test.py](https://gist.github.com/kevin85421/34baa982c5ce5647ff36be367cc61b28): I've modified the script you provided slightly.

```sh
# Ray 2.9.0
serve run test:model_server
curl -X GET 127.0.0.1:9000/health
```

Both "I'm healthy!" and "Healthy" are shown in the STDOUT. See the following screenshot for more details.

<img width="1439" alt="Screen Shot 2024-03-17 at 12 22 54 AM" src="https://github.com/ray-project/ray/assets/20109646/a3a96d70-de13-437c-93fe-0dd9f3b3bf37">
