### ISSUE TITLE
Release test gcp_cluster_launcher_gpu_docker failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42134]
Release test **gcp_cluster_launcher_gpu_docker** failed. See https://buildkite.com/ray-project/release/builds/4990#018cba22-f770-4147-8d80-e32b4def8fc5 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
@kevin85421 is this one go to oss infra team? thankks

**Comment by kevin85421** [comment]
Yes, the VM launcher belongs to the OSS infra team. Archit is currently OOO and will be back next Monday. cc @architkulkarni

**Comment by anyscalesam** [comment]
bump @architkulkarni please triage

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
@architkulkarni is this test important (defined as something we would block on if still failing ahead of a ray release)?

**Comment by architkulkarni** [comment]
Yes. I think all tests are blocking unless marked "unstable".

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/5909#018d025b-1015-4a51-8805-b84181fe6383

**Comment by architkulkarni** [comment]
Seems to be a transient failure, it passed when I reran it here: https://buildkite.com/ray-project/release/builds/5994 (note `release_images` tests are expected to fail).

**Comment by anyscalesam** [comment]
@can-anyscale can you review and close if true?

**Comment by can-anyscale** [comment]
We only run this once a week so let's wait until this weekend and see what happens

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/6304#018d2673-5cd3-451f-b074-54dc13add090

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/7031#018d4a7d-5287-48bd-b354-450a62ce08b6

**Comment by architkulkarni** [comment]
All the GCP tests are failing with the same error since some time after last Thursday:

"Job terminated before cluster was launched. No logs available."

For some reason the "outer" cluster is failing to start within 30m (the cluster for the Anyscale job, as opposed to the "inner" cluster which is launched by the script in this test).

Not all GCE env tests are failing, just the GCP cluster launcher tests.  Still trying to figure out why, maybe it can be fixed by changing the compute config.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/8076#018d9265-f1a9-4f9e-b993-daedabfbbcbb
