### ISSUE TITLE
[Serve] Memory leak after upgrading from 2.8.1 to 2.9.0 

### ISSUE THREAD

**Issue by morhidi** [ray-project/ray#42144]
### What happened + What you expected to happen

After upgrading Ray version from 2.8.1 to 2.9.0 we noticed a memory leak `ray_node_mem_used`  on the head node. <img width="898" alt="image" src="https://github.com/ray-project/ray/assets/53612764/9c719159-6492-4e46-af8a-863ae948849a">

### Versions / Dependencies

2.9.0 

### Reproduction script
Load is 200 QPS

```python
import logging

from fastapi import FastAPI, Request
from fastapi.encoders import jsonable_encoder
from ray import serve
from starlette.responses import JSONResponse

logger = logging.getLogger("ray.serve")

app = FastAPI()


@serve.deployment
@serve.ingress(app)
class ModelServer:

    def __init__(self):
        logger.info("Initialized")


    @app.post("/inference")
    def inference(self, request: Request) -> JSONResponse:

        response = {
            "result": "OK"
        }

        return JSONResponse(content=jsonable_encoder(response))

esp_model_app = ModelServer.bind()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
Thanks @morhidi for all your help with narrowing down this issue. With the following repro, we observe a memory leak:

<details>
  <summary>Repro</summary>

  ```python
  import logging
  
  from fastapi import FastAPI, Request
  from fastapi.encoders import jsonable_encoder
  from ray import serve
  from starlette.responses import JSONResponse
  
  logger = logging.getLogger("ray.serve")
  
  app = FastAPI()
  
  
  @serve.deployment
  @serve.ingress(app)
  class ModelServer:
  
      def __init__(self):
          logger.info("Initialized")
  
  
      @app.post("/inference")
      def inference(self, request: Request) -> JSONResponse:
  
          response = {
              "result": "OK"
          }
  
          return JSONResponse(content=jsonable_encoder(response))
  
  esp_model_app = ModelServer.bind()
  ```
</details>

2.8.1 head node memory:

<img width="1357" alt="Screenshot 2024-01-04 at 9 55 10 AM" src="https://github.com/ray-project/ray/assets/92341594/e58d8dc4-4ced-4db3-80df-e5d9642e9da5">

2.9.0 head node memory:

<img width="1353" alt="Screenshot 2024-01-04 at 9 55 51 AM" src="https://github.com/ray-project/ray/assets/92341594/9307fb6e-b652-46d8-8159-9fe6386a1de6">

**Comment by shrekris-anyscale** [comment]
The process growing in memory seems to be the GCS server. Here's some `top` outputs over time (courtesy of @morhidi):

<details>
  <summary>top outputs</summary>

  <img width="632" alt="Screenshot 2024-01-04 at 10 01 11 AM" src="https://github.com/ray-project/ray/assets/92341594/910193d4-876a-496e-b9fe-9d76193c5e49">

  <img width="631" alt="Screenshot 2024-01-04 at 9 59 10 AM" src="https://github.com/ray-project/ray/assets/92341594/20bbdbeb-606d-4905-a796-6445ac4263d5">
  
  <img width="631" alt="Screenshot 2024-01-04 at 9 59 22 AM" src="https://github.com/ray-project/ray/assets/92341594/53b25aa6-748b-4bc2-8201-9fcfa6583a3c">

</details>

**Comment by shrekris-anyscale** [comment]
Here are the keys from the internal kv list in the Ray 2.9.0 cluster:

<details>
  <summary>KV keys</summary>

  ```
  >>> import ray
  >>> import ray.experimental.internal_kv as kv
  >>> ray.init(address="auto")
  >>> import json
  >>> print(json.dumps([str(key) for key in kv._internal_kv_list("")], indent=4))
  [
      "b'CLUSTER_METADATA'",
      "b'ActorClass:01000000:](\\xc1\\xe2\\xe9\\x1e\\xb6\\x9b\\x96\\xbc\\x0f\\xdc&\\x90\"\\x95Y@\\xcf\\xf5\\x07\\xbai\\x9f\\x9f9f\\xfe'",
      "b'extra_usage_tag_serve_http_proxy_used'",
      "b'extra_usage_tag_serve_num_apps'",
      "b'extra_usage_tag_serve_num_deployments'",
      "b'extra_usage_tag_serve_num_gpu_deployments'",
      "b'temp_dir'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:8a1c4ff64b9a2ad2ccaddd3b4c5a88972f5ef16bb895cfdef755013e'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:51b003aa8458aaed48d101050c3429d5eb6b0cd4360dcf848302dbb8'",
      "b'dashboard'",
      "b'extra_usage_tag_gcs_storage'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:239fec11187df96c8e7608901552ecabfefdd5c3a8c3a8d7e56ee0a1'",
      "b'DashboardMetricsAddress'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:b0986c77e97fca702edc1ce3599d387de773ebfee7b54f996bb25f9f'",
      "b'SERVE_CONTROLLER_ACTOR-_ray_internal_dashboard-serve-application-state-checkpoint'",
      "b'SERVE_CONTROLLER_ACTOR-_ray_internal_dashboard-serve-app-config-checkpoint'",
      "b'SERVE_CONTROLLER_ACTOR-_ray_internal_dashboard-serve-deployment-state-checkpoint'",
      "b'extra_usage_tag_dashboard_metrics_prometheus_enabled'",
      "b'SERVE_CONTROLLER_ACTOR-_ray_internal_dashboard-serve-endpoint-state-checkpoint'",
      "b'extra_usage_tag_num_drivers'",
      "b'extra_usage_tag_serve_get_deployment_handle_api_used'",
      "b'RemoteFunction:01000000:\\xe6\\x9bI\\xc8\\x99\\xcd\\x91\\xcb\\xbb\\xf6]\\xecj\\x05\\x0c\\xa8\\tU{Y\\xe1l\\x04\\xa7$3\\x04O'",
      "b'RemoteFunction:01000000:\\x1e>\\xdc\\xfa\\xe9&l\\x88?+\\xc8\\x17\\x86\\xb5\\x8cUt\\x7f~TQ\\xc7B%l\\xad\\xae\\x9d'",
      "b'library_usage_serve'",
      "b'extra_usage_tag_pg_num_created'",
      "b'extra_usage_tag_serve_rest_api_version'",
      "b'extra_usage_tag_serve_api_version'",
      "b'ActorClass:01000000:\\x1d\\x19\\xaa+\\xce\\x87\\xc7\\xd3\\x06\\xc6\\x9et\\x1a\\xb3\\xcb\\xece\\x99\\x02i\\xfe\\xb2UIo\\x07>\\x8f'",
      "b'head_node_id'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:ca9e904f57a85065adc08c45d3487dfd6cf3632abc544c53a6e43e19'",
      "b'webui:url'",
      "b'SERVE_CONTROLLER_ACTOR-_ray_internal_dashboard-serve-logging-config-checkpoint'",
      "b'ActorClass:01000000:F\\xb49\\xa2\\xb5\\x97\\x7f\\xa76\\xdd\\xc7\\xb0\\n\\xf9\\xc7\\xc9+5\\x9es\\x00\\x96\\xe2\\xa2\\xbc\\x7f|8'",
      "b'ray_cluster_id'",
      "b'ray_client_server'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:171f40ad49706c7557fb3e6d5f99888a1399eb91eec1c8d94a1a9d09'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:6b833e51c96ef6b7a1cdb4db86afce4c2ee8e2468bb822bd18bfc38a'",
      "b'extra_usage_tag_actor_num_created'",
      "b'hardware_usage_Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:d5c9da700adc3c0046e412223f7ba63f4eb94cacfdfa304a64d8cc33'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:c600bdaa5fde305e6ad5a0861e72a6d50cfaa0ac829eee898bd9874e'",
      "b'session_dir'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:550c9f52029ca67360b183880513790f8b02334d95d0c7aa1e363b95'",
      "b'extra_usage_tag_dashboard_metrics_grafana_enabled'",
      "b'extra_usage_tag_serve_fastapi_used'",
      "b'__autoscaler_v2_enabled'",
      "b'extra_usage_tag_num_actor_tasks'",
      "b'extra_usage_tag_num_actor_creation_tasks'",
      "b'session_name'",
      "b'DASHBOARD_AGENT_PORT_PREFIX:bc01916ca0020fdb0d6c0a2b77177e3caef8ab023bb63ce0c20b971e'",
      "b'extra_usage_tag_num_normal_tasks'",
      "b'extra_usage_tag_dashboard_used'",
      "b'dashboard_rpc'"
  ]
  >>> len(kv._internal_kv_list(""))
  53
  ```
</details>

**Comment by iycheng** [comment]
I'll take a look.

**Comment by iycheng** [comment]
[prof.pdf](https://github.com/ray-project/ray/files/13837289/prof.pdf)

It seems the events data take some space. Let me increase the interval and reduce the observability events.

**Comment by iycheng** [comment]
This logic doesn't exist in 2.8.1. So high probably it's because of this.

**Comment by iycheng** [comment]
Removed the logic and run it again. Waiting for result.

**Comment by iycheng** [comment]
The memory looks stable after removing it. I'll sync with @rickyyx  to see how to fix it.

**Comment by mbalassi** [comment]
Great, @iycheng and @shrekris-anyscale. Thanks for the fast repro and investigation.

**Comment by iycheng** [comment]
The memory is pretty stable. I'll dig deeper

**Comment by iycheng** [comment]
It looks like the size of this field never got GC https://github.com/ray-project/ray/blob/master/src/ray/protobuf/gcs.proto#L204

Not sure what's the correct logic for this. I'll sync it offline with @rickyyx

**Comment by iycheng** [comment]
@morhidi as @rickyyx mentioned that setting `RAY_enable_timeline=0` can mitigated this.

**Comment by morhidi** [comment]
> `RAY_enable_timeline=0`

Thank you folks, we're on KubeRay. Where should this property go?

**Comment by shrekris-anyscale** [comment]
> Thank you folks, we're on KubeRay. Where should this property go?

Set the env var directly on the Ray containers in both the [`headGroupSpec`](https://github.com/ray-project/kuberay/blob/5b1a5a11f5df76db2d66ed332ff0802dc3bbff76/ray-operator/config/samples/ray-service.text-ml.yaml#L49-L66) and [`workerGroupSpec`](https://github.com/ray-project/kuberay/blob/5b1a5a11f5df76db2d66ed332ff0802dc3bbff76/ray-operator/config/samples/ray-service.text-ml.yaml#L82-L94). You can follow the syntax from [this example](https://github.com/ray-project/kuberay/blob/83327f222ebe8ff5c1497f874c88a78fb384d8f3/ray-operator/config/samples/ray-service.high-availability.yaml#L135-L143).

**Comment by morhidi** [comment]
I've applied the suggested workaround, and can confirm things looking better with it:
<img width="813" alt="image" src="https://github.com/ray-project/ray/assets/53612764/eb8f9ffe-0d60-466c-945f-a2a2e4b27cfd">

Looking forward to the final fix. Thanks @shrekris-anyscale @rickyyx for the extra efforts with the investigation

**Comment by shrekris-anyscale** [comment]
I retried the repro with the fix. There's no longer a memory leak:

<img width="1367" alt="Screenshot 2024-01-09 at 11 37 29 AM" src="https://github.com/ray-project/ray/assets/92341594/7efe3d3e-6cbe-4146-ad3c-d3b5b475b44e">
