### ISSUE TITLE
[Ray Serve] Request rate limiting

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#42155]
### Description

Request rate limiting, can add a rejection policy when the traffic is large to prevent the service from being DDoSed and be able to respond to new normal requests.

### Use case

As an example, service deployment that has 100ms latency, due to machine resource constraints there are only two replicas, serving a traffic load of 30 QPS. Latency will also increase since new requests have to wait for old requests to finish processing, new requests will time out when traffic is heavy.

**Comment by edoakes** [comment]
@v4if we are considering adding a parameter `max_queued_queries`. This would cause new requests to be dropped if there are already `max_queued_queries` requests that are trying to be scheduled by a proxy or `DeploymentHandle`.

Would that work for your use case?

**Comment by v4if** [comment]
> @v4if we are considering adding a parameter `max_queued_queries`. This would cause new requests to be dropped if there are already `max_queued_queries` requests that are trying to be scheduled by a proxy or `DeploymentHandle`.
> 
> Would that work for your use case?

It works. Looking forward to this feature.

**Comment by edoakes** [comment]
Great -- we are targeting the upcoming Ray 2.10 release for this feature.
