### ISSUE TITLE
[data] retry metadata fetching tasks

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#42153]
Sometimes transient errors may happen during metadata fetching tasks. One example is `OSError: When reading information for key '...' in bucket '...': AWS Error ACCESS_DENIED during HeadObject operation: No response body.`.

We should support retrying metadata fetching tasks based on the error types. 

For now, we can work around this issue by patching the following diff. 
```diff
diff --git a/python/ray/data/datasource/file_meta_provider.py b/python/ray/data/datasource/file_meta_provider.py
index d6d705d899..86eb93b503 100644
--- a/python/ray/data/datasource/file_meta_provider.py
+++ b/python/ray/data/datasource/file_meta_provider.py
@@ -529,7 +529,7 @@ def _fetch_metadata_parallel(
     **ray_remote_args,
 ) -> Iterator[Meta]:
     """Fetch file metadata in parallel using Ray tasks."""
-    remote_fetch_func = cached_remote_fn(fetch_func, num_cpus=0.5)
+    remote_fetch_func = cached_remote_fn(fetch_func, num_cpus=0.5, retry_excpetions=True)
     if ray_remote_args:
         remote_fetch_func = remote_fetch_func.options(**ray_remote_args)
     # Choose a parallelism that results in a # of metadata fetches per task that

```

**Comment by raulchen** [comment]
already implemented.

**Comment by lightertu** [comment]
Thans Hao, I got the same error `AWS Error ACCESS_DENIED during HeadObject operation` while fetching object metadata from S3. 

I am 100% sure I have permission and I saw some other tasks that do the same thing succeed. I suspect I got throttled by s3 instead of permission denied. Should we fix the error message instead?

**Comment by raulchen** [comment]
`AWS Error ACCESS_DENIED during HeadObject operation`
@lightertu this error is raised by pyarrow (ray data uses pyarrow internally). And I believe the error message is originally returned by AWS server. 
Do you mind sharing how you set your credentials? We've also seen a similar issue where some tasks get this error, while some don't. We haven't figured out the root cause yet.

**Comment by lightertu** [comment]
Hi @raulchen thanks for getting back to me. I think PyArrow is sending misleading error codes. I setup credentials by using an execution role assumed by each pod on a AWS EKS cluster, the data is in the same account, and the role has full s3 access. So it cannot be a access denied issue. I notice after I lowered the throughput of my Ray job, eg reading larger s3 files. The issue goes away.

**Comment by raulchen** [comment]
@lightertu actually in our workload, we checked w/ AWS people. the server indeed got unauthorized requests. and that workload also used the `role_arn` API. We don't know the root cause yet. but after reducing concurrency, the issue was gone. so we suspect there may be a bug in PyArrow when concurrency is high.
