### ISSUE TITLE
[<Ray Core>] Addition '1' for the object id.

### ISSUE THREAD

**Issue by Bye-legumes** [ray-project/ray#42198]
### What happened + What you expected to happen

When I trace the log of ray driver, sometimes there will be addition "1" in the object id. I have to deleted '1' inside of the object id to keep query.  Here is the log file
![20240105-111056(WeLinkPC)](https://github.com/ray-project/ray/assets/121425509/4408d0fe-a0a2-45eb-967f-4a8d33c01fed)

### Versions / Dependencies

ray 2.8.1

### Reproduction script

```
import ray
import time
ray.init()
import numpy as np

@ray.remote
def generate_data(x):
    return np.ones((10,10))

@ray.remote
def aggregate_data(x, y, z):
    return x + y +z

data = [generate_data.remote(i) for i in range(300)]

res = []
while len(data) > 1:
    res.append(aggregate_data.remote(data.pop(0), data.pop(0),data.pop(0)))


a = ray.get(res)
print(a[0])
```

### Issue Severity

None

**Comment by stephanie-wang** [comment]
How often do you see this behavior? Does it cause any other issues or is it just that the logging is wrong?

**Comment by Bye-legumes** [comment]
I can not reproduce that..Sorry
