### ISSUE TITLE
[CI] `linux://python/ray/data:test_huggingface` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42192]
- cc61565848769efc8ccd28a463a441ede3bb9734 FAILED [Buildkite :database: data: arrow 6 tests](https://buildkite.com/ray-project/postmerge/builds/2368#018cd6d7-1511-4e51-ab4b-8712c3444719)
- b7d71b26af535e8de9a358a80b5eebb79e35a879 FAILED [Buildkite :database: data: arrow 6 tests](https://buildkite.com/ray-project/postmerge/builds/2366#018cd63a-f478-4c0b-be05-66744228f437)
- 2b57ee9bcf48dc665aac487dafd0044b65bc652c FAILED [Buildkite :database: data: arrow 6 tests](https://buildkite.com/ray-project/postmerge/builds/2365#018cd5be-46c4-4cfe-8cea-bf901f8e841a)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/data:test_huggingface-END
....

**Comment by can-anyscale** [comment]
Please help investigate and fix. It's broken not due to a code change so I jail this to unblock premerge https://github.com/ray-project/ray/pull/42193.

**Comment by can-anyscale** [comment]
I think it's still failing on the nightly version of this test https://buildkite.com/ray-project/postmerge/builds/2470#018cf566-0efd-46a3-83d6-8acab80c045a

**Comment by scottjlee** [comment]
I think this is passing on master now for nightly: https://buildkite.com/ray-project/postmerge/builds/2574#018d1d4f-5acb-4752-8215-70a3dffea219/186-912
