### ISSUE TITLE
Ray Dashboard: Better GPU utilization visibility

### ISSUE THREAD

**Issue by gvspraveen** [ray-project/ray#42208]
### Description

Feedback from @robin-anyscale:

Sometimes i dont know which GPU did ray cluster used for scaling, so i typically click on GRAM to find the accelerator (its cool that it tells me the GPU used) but i dont see same behavior when i click on GPU tab (marked in red). It will be great if we can see it consistently in both the places or find what gpu is being used from some other place

![image](https://github.com/ray-project/ray/assets/543829/80e2eb23-57e7-463d-bcd3-73ee90293312)

### Use case

Debugging serve workloads

**Comment by scottsun94** [comment]
@alanwguo and I chatted a bit about burning down this kind of polish/friction items.

@gvspraveen maybe we can leverage the ux friction slots we have?

**Comment by architkulkarni** [comment]
Thanks @robin-anyscale , just to clarify, is the desired behavior that "NVIDIA L4" appear as a tooltip when you mouse over the GPU entry, just like how it currently does when you mouse over the GRAM entry?

We could also maybe always display it in the GPU entry where it currently says [0], but I'm not sure if that will take too much space.

**Comment by architkulkarni** [comment]
<img width="188" alt="Screenshot 2024-01-09 at 3 23 46 PM" src="https://github.com/ray-project/ray/assets/5459654/9ae26b55-0b63-405f-9760-131f438529ee">
Actually, for the GPU column, the tooltip currently appears, but only if you hover over the "[0]" part, not over the utilization bar.

For the GRAM column, the tooltip appears if you hover over the "[0]" part or the utilization bar.  <img width="197" alt="Screenshot 2024-01-09 at 3 24 26 PM" src="https://github.com/ray-project/ray/assets/5459654/0c21a27f-aabc-4355-a5a1-3b31d36051ef">

So I think we just need to make sure that the tooltip appears when hovering over the utilization bar in the GPU column.

**Comment by scottsun94** [comment]
> 
> 
> 
> 
> Actually, for the GPU column, the tooltip currently appears, but only if you hover over the "[0]" part, not over the utilization bar.
> 
> 
> 
> <img width="188" alt="Screenshot 2024-01-09 at 3 23 46 PM" src="https://github.com/ray-project/ray/assets/5459654/9ae26b55-0b63-405f-9760-131f438529ee">
> 
> 
> 
> For the GRAM column, the tooltip appears if you hover over the "[0]" part or the utilization bar.  <img width="197" alt="Screenshot 2024-01-09 at 3 24 26 PM" src="https://github.com/ray-project/ray/assets/5459654/0c21a27f-aabc-4355-a5a1-3b31d36051ef">
> 
> 
> 
> So I think we just need to make sure that the tooltip appears when hovering over the utilization bar in the GPU column.

+1. Let's start with only tooltip. We can add the text into [0] if needed down the road.
