### ISSUE TITLE
[data] Improve StreamingOutputBackpressurePolicy

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#42217]
StreamingOutputBackpressurePolicy has been tested with many large-scale benchmarks and real-world workloads. Generally, this feature can greatly improve stability and avoid OOMs. 

Currently, the default behavior is to allow pending at most 10 blocks at the streaming generator level, and 20 blocks at the op output queue level ([link](https://github.com/ray-project/ray/blob/152ef7fd4b6383d2574a736d483ada7a01f3b2ea/python/ray/data/_internal/execution/backpressure_policy/streaming_output_backpressure_policy.py#L20-L47)). The main reason why we use number of blocks instead of byte size to limit the buffer is because each task will yield 2 objects (a block and a metadata) each time and we don't want the streaming generator to be blocked in the middle. 

With the above default value, the pending buffer size should be (10 + 20) * block_size. where block_size is usually 128MB. 

With the current implementation, there will be issues for some small-scale jobs: 
1. Sometimes due to bad parallelism computation (e.g., https://github.com/ray-project/ray/issues/41496), the block size can be much smaller than 128MB. In such case, the pending buffer size is too small, and the scheduling overhead will cause a perf regression. 
2. for other cases where the total object store memory is limited, the default 3.75GB buffer size is too large.

Thus, to solve these issues, we can 1) make the op output queue buffer to be determined by byte size. note, the streaming generator buffer is still determined by number of objects due to the above-mentioned reason. 2) also consider remaining available object store memory when determine the op output queue buffer.

master issue: https://github.com/ray-project/ray/issues/40754

**Comment by stephanie-wang** [comment]
> for other cases where the total object store memory is limited, the default 3.75GB buffer size is too large.

What happens in this case? Deadlock / slowdown?

I think it'd be good to do something adaptive here. Like if there are N stages total, give each stage a buffer of size `object store memory limit / N`.

**Comment by raulchen** [comment]
> What happens in this case? Deadlock / slowdown?

The backpressure would be not strict enough for this case, and spilling will still happen. But it's better than no backpressure.

> I think it'd be good to do something adaptive here. Like if there are N stages total, give each stage a buffer of size object store memory limit / N.

I thought of this. Determine the limit based on object store memory makes sense. But it may not be optimal to evenly distribute the memory for stages. Because output sizes of different stages are usually different.

**Comment by raulchen** [comment]
> But it may not be optimal to evenly distribute the memory for stages. Because output sizes of different stages are usually different.

Instead of assigning the available object store memory evenly for each op in the beginning, an alternative approach can probably better deal with this issue. that is, in each scheduling loop iteration, assign the current available object store memory evenly for each op. 

I tried these 2 approaches with `ray-data-resnet50-ingest-file-size-benchmark`, the latter indeed works better. The former has a 30+% perf regression compared with no backpressure, and the latter is only <5%.
