### ISSUE TITLE
PPO terminates silently

### ISSUE THREAD

**Issue by dmadeka** [ray-project/ray#4222]
When trying to run PPO - after xMM iterations (typically 100MM). the agent stops running. Im not sure if some sort of early stopping condition is being placed or there are other factors (like ray workers crashing)

**Comment by ericl** [comment]
Silent termination is unexpected. Is there anything in the Ray session logs dir that you can share?

**Comment by richardliaw** [comment]
This should be fixed; feel free to file a new issue if this is still the case.
