### ISSUE TITLE
[Doc] [Ray Job] `delete` is missing from SDK and CLI doc

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#42275]
### Description

The `delete` method was added in https://github.com/ray-project/ray/pull/30056 but it's missing from the following doc pages:
- https://docs.ray.io/en/latest/cluster/running-applications/job-submission/cli.html
- https://docs.ray.io/en/latest/cluster/running-applications/job-submission/jobs-package-ref.html

It should be added to these pages.

**Comment by chrislevn** [comment]
Hi @architkulkarni, I created a PR #42555 for this issue.
