### ISSUE TITLE
Wait order should be randomized by default

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#4231]
### Describe the problem
Consider the following piece of code
```
ids = [actors[i].f.remote() for i in range(10)]
while True:
    [id] = ray.wait(ids, num_returns=1)
    ids[ids.index(id)] = actors[ids.index(id)].f.remote()
```

In a scenario where the bottleneck becomes the wait loop, actor 0 will get much more work than later actors. This is because wait() prioritizes by the order of ids passed in. This is undesirable for a few reasons:
- it might be important for the application to balance work equally across actors
- actor 0's work items might be lighter than other actors, in which case global throughput is severely impacted as heavy weight work is never scheduled

To avoid unfairness, one simple fix is to shuffle the ids:
```
ids = [actors[i].f.remote() for i in range(10)]
while True:
    [id] = ray.wait(random_shuffle(ids), num_returns=1)
    ids[ids.index(id)] = actors[ids.index(id)].f.remote()
```

We should consider doing this by default, since this issue is particularly subtle (e.g., this was just recently discovered in Ray tune).

### Source code / logs
https://github.com/ray-project/ray/blob/6f46edca5184ac81f2b010bf769e3d0cbbc828ef/src/ray/object_manager/object_manager.cc#L691

**Comment by ericl** [comment]
@istoica points out we could achieve this very cheaply by randomizing the start index in object_manager.cc:691

@robertnishihara any thoughts?

**Comment by virtualluke** [comment]
adding random_shuffle to some of my waits similar to above, nice find (will see how it impacts things).  I definitely have very non homogeneous work loads between actors.

**Comment by richardliaw** [comment]
Closing because stale. Feel free to reopen if necessary.
