### ISSUE TITLE
[Core] mac tests start failing after upgrading the base version to Python 3.9

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#42312]
### What happened + What you expected to happen

```
(SignalActor pid=80705) *** SIGSEGV received at time=1704825819 ***
(SignalActor pid=80705) [2024-01-09 18:43:39,434 E 80705 1008238] logging.cc:361: *** SIGSEGV received at time=1704825819 ***
(SignalActor pid=80705) Fatal Python error: Segmentation fault
(SignalActor pid=80705)
(SignalActor pid=80705) Stack (most recent call first):
(SignalActor pid=80705) <no Python frame>
```

Seems like there is a mysterious segfault that causes mac tests to fail when running ray with Python 3.9. Since we will stop supporting python 3.8, we should fix this issue asap. 

### Versions / Dependencies

master

### Reproduction script

run some of failed mac tests

### Issue Severity

None

**Comment by anyscalesam** [comment]
@aslonnie @can-anyscale can we delay this to ray2.11 since we're delaying our py upgrade plans (py38 base and py311 ceiling) one release?

**Comment by aslonnie** [comment]
> @aslonnie @can-anyscale can we delay this to ray2.11 since we're delaying our py upgrade plans (py38 base and py311 ceiling) one release?

oss / core team should decide. REEf team does not own the decision. people can always choose to disable/ignore the test. REEf team just wants the decision to be expressed explicitly on CI/CD process.

**Comment by anyscalesam** [comment]
Closing this since we fixed all tests kudos @jackhumphries
