### ISSUE TITLE
potential bug in actor_manager

### ISSUE THREAD

**Issue by harrycoder28** [ray-project/ray#42334]
### What happened + What you expected to happen

It lies in the function "_try_start_actors" in "ray.air.execution._internal.actor_manager", line 323
the variable "started_actors" is not updated along with the while loop as it supposed to.
Maybe u forget to write started_actors+=1 at the end of each loop.

### Versions / Dependencies

ray 2.9.0

### Reproduction script

it lies in the source code

### Issue Severity

None

**Comment by anyscalesam** [comment]
@harrycoder28 how did you discover this; were you trying to run something or were you just browsing the source?
