### ISSUE TITLE
Python 3.8 deprecation in Ray 2.11

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#42343]
We are planning to deprecate Python 3.8 support for Ray 2.11 and beyond, as the EOL is quickly approaching https://devguide.python.org/versions/).

Please leave any questions/comments below!

**Comment by anyscalesam** [comment]
@can-anyscale when do you think you'll be able to attempt an image build of both ray and ray-ml and provide a list of breaking dependencies that we can then assign to the relevant Ray team to resolve?

**Comment by can-anyscale** [comment]
**Mar 13 updates**

Done:
- ray py3.8 is now completed deprecated in master branch (after ray 2.10 branch cut)

In progress:
- non-test breaking initial dependency upgrade (https://github.com/ray-project/ray/pull/42104, ETA: merge early next week)
- test-breaking dependency upgrade + ray.ml.311 image built (https://github.com/ray-project/ray/pull/43402, ETA: merge next week)

Remaining work:
- March 20-31: fixing forward test failures for python 3.11
- April 1st: ray 2.11 release

**Comment by can-anyscale** [comment]
Related issues:
- https://github.com/ray-project/ray/issues/44077

**Comment by abitrolly** [comment]
2.11 is released last week https://github.com/ray-project/ray/releases

Is there anything left to be done here? I am asking, because this issue blocks Python 3.12 support.

**Comment by can-anyscale** [comment]
this is now done, thank you folks
