### ISSUE TITLE
[Data] Ray fails when using `map_groups` function and Gpus as Actors  

### ISSUE THREAD

**Issue by shivraj95** [ray-project/ray#42340]
## Description 

When using [map_groups](https://docs.ray.io/en/latest/data/api/doc/ray.data.grouped_data.GroupedData.map_groups.html) and setting the arg _**num_gpus**_  > 0, Ray will raise an exception:  
> ValueError(
>             "`batch_size` must be provided to `map_batches` when requesting GPUs. "
>             "The optimal batch size depends on the model, data, and GPU used. "
>             "It is recommended to use the largest batch size that doesn't result "
>             "in your GPU device running out of memory. You can view the GPU memory "
>             "usage via the Ray dashboard."
>         )
> 
from this [code block](https://github.com/ray-project/ray/blob/3f7f1b52c840d6780fd89ef9bc125ff96eb68e52/python/ray/data/block.py#L110).

### Versions / Dependencies

This bug will occur for all Python and Ray versions as of post date. 

### Reproduction script

This must be run on a cluster with GPU workers. 

```
ds = ray.data.from_items([ 
    {"group_id": 1, "value": 1},
    {"group_id": 1, "value": 2},
    {"group_id": 2, "value": 3},
    {"group_id": 2, "value": 4}])

ds.groupby('group_id').map_groups(lambda x: {"result": np.array([g["value"][0]])}, num_gpus=1)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by bveeramani** [comment]
Ah, yeah. I was able to reproduce this.

Shouldn't be too hard to fix.

**Comment by anyscalesam** [comment]
@bveeramani ETA on fix? cc @c21
