### ISSUE TITLE
[Cluster] Assistance Needed with Resource Allocation Issues in Ray Cluster

### ISSUE THREAD

**Issue by wjd5480** [ray-project/ray#42411]
I am currently facing a challenge with resource allocation in my Ray cluster, and I’m seeking your advice and assistance to resolve it.

Issue Description: I am running a distributed task using Ray, which involves processing large amounts of data and performing embeddings using GPU. However, I’m encountering an issue where the tasks in map_batches are not completing and remain indefinitely in a paused state. The status displays as follows: “Running: 1.0/960.0 CPU, 80.0/80.0 GPU, 0.51 MiB/278.69 GiB object_store_memory: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1527/1528 [01:09<00:00, 1.76it/s]”.

Additionally, I receive a warning indicating resource limitations: “Warning: The following resource request cannot be scheduled right now: {‘CPU’: 1.0}. This is likely due to all cluster resources being claimed by actors.”

Attempts at Resolution: I have tried several approaches to address this issue, including adjusting batch sizes, optimizing task management, and even considering increasing the number of nodes in my cluster. Unfortunately, none of these solutions have resolved the problem.

Request for Assistance: Could anyone in the community advise on how to handle this situation? Are there specific configurations or adjustments within Ray that I might be overlooking? Any insights or suggestions would be greatly appreciated.

Thank you in advance for your time and help.

### Versions / Dependencies

ray 2.9.0

### Reproduction script

```python
ds = ds.map_batches(
    Embed,
    batch_size=200,
    concurrency=80,
    num_gpus=1,
)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@rynewang can you help here?

**Comment by rkooo567** [comment]
@bveeramani have you heard of the similar issues before?

@wjd5480 when you see this warning, what's the output of `ray status`? Can you show us?

**Comment by bveeramani** [comment]
I haven't seen this issue in specific, but I have some ideas.

@wjd5480 are you running anything else on the Ray cluster? 

Also, one workaround you might want to try is to add `num_cpus=0` to your `map_batches`. Not confident it'll fix your problem, but it's worth a shot.

**Comment by rkooo567** [comment]
@wjd5480 

Can you also check the dashboard and see what's running / pending when you are in this state?

**Comment by rkooo567** [comment]
P1.5 until author takes actions and we can figure out the root cause in more details. The provided repro doesn't work.
