### ISSUE TITLE
[CI] `linux://python/ray/serve/tests:test_model_composition` is failing/flaky on master.

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42415]
- b74f9255b2f45869e5ec67626d0595dca6bddc78 FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2542#018d124f-99d1-47e2-b7d6-489b792ab065)
- 8af9a4086b3c3fce4b1fe0d1c05d2a4add0586e5 FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2541#018d11ef-6d17-44f7-9bf8-6f1d95bb8a4e)
- 8af9a4086b3c3fce4b1fe0d1c05d2a4add0586e5 FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2540#018d1128-039f-46d1-a937-6e4ed2aed8c2)
- 1dd1e6f0b052d4d9501b2596b3c8749d0035bccf FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2539#018d10e7-5b86-46ac-994d-c18061bf8376)
- b8f3f134e7ab1886d4b8bd2c9c91ad439e5eaf9b FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2538#018d104d-bf83-4eb9-9461-22f3375f7d64)
- 53e9b33acbe75cebda04ac9ed7d8aad99c5a0176 FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2537#018d0e4b-ca3c-48e0-b699-174dc8329c3a)
- 7d79eb24d0f23d40de9fc87a5c4e3260159a2fd3 FAILED [Buildkite :ray-serve: serve: serve minimal](https://buildkite.com/ray-project/postmerge/builds/2536#018d0cc9-6d6e-413b-8309-f4bea25c7e78)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/serve/tests:test_model_composition-END
....

**Comment by can-anyscale** [comment]
This is completely failing on premerge/postmerge so I move it to flaky to unblock.

**Comment by GeneDer** [comment]
PR merged, closing
