### ISSUE TITLE
[data] adding more info to data dashboard

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#42437]
currently, data dashboard is still missing some information that we have in the progress bar. For example, output queue size, number of active/finished/failed tasks, number of blocks. Ideally we should add all metrics from `OpRuntimeMetrics` and `OpState`.

**Comment by bveeramani** [comment]
Adding on to this, here's the information I'd like to see:
* Input queue size (in bytes as a stacked line graph, and in blocks as a regular line graph)
* Output queue size (in bytes as a stacked line graph, and in blocks as a regular line graph)
* Cycle time (in seconds as a histogram)
* Output size (in bytes as a histogram)
* Number of outputs (as a histogram)

**Comment by bveeramani** [comment]
Clarification on my earlier comment -- by cycle time, I mean the time in seconds it takes for a task to produce an output. For example, a map operator that performs inference might take a few seconds to produce each output.

This metric can help you understand where the bottleneck is.

We don't currently track it.
