### ISSUE TITLE
[Core] [JobSubmissionClient] Ray Head does create Worker nodes when submitting a job with JobSubmissionClient

### ISSUE THREAD

**Issue by sercanCyberVision** [ray-project/ray#42432]
### What happened + What you expected to happen

We have implemented one of the recommended best practices for our Ray cluster, following the guidelines outlined [here](https://github.com/ray-project/kuberay/blob/master/docs/best-practice/worker-head-reconnection.md#best-practice). Specifically, we have set `num-cpus: 0` in `rayStartParams` of `headGroupSpec`. This configuration ensures that the Ray scheduler skips the head node when scheduling workloads.

When submitting jobs with the Ray client on port `10001`, we encounter no issues. The worker nodes are created as expected, and our sample job is executed properly. However, when we submit the same sample (even its trimmed version) job using `JobSubmissionClient` on port `8265`, the head node fails to create any workers, leading to a significantly prolonged execution time of 3 minutes:

![image](https://github.com/ray-project/ray/assets/73108963/f14d4326-5c19-491c-b562-9817a3b6c002)

Please note, when we specify `entrypoint_num_cpus` during job submission, the process works as expected.

This issue not only results in a huge performance difference but also exposes the head node to potential risks.

Please advise on any insights or recommendations to address this issue.

### Versions / Dependencies

Ray version is 2.7.0

### Reproduction script

The job submission script:
```
import ray
from ray.job_submission import JobSubmissionClient
import time

# Ray cluster information
ray_head_ip = "kuberay-head-svc.kuberay.svc.cluster.local"
ray_head_port = 8265
ray_address = f"http://{ray_head_ip}:{ray_head_port}"

# Submit Ray job using JobSubmissionClient
# With this entrypoint_num_cpus = 3, it works fine
client = JobSubmissionClient(ray_address)
job_id = client.submit_job(
    entrypoint="python fibonacci.py",
    runtime_env={
        "working_dir": "./",
    }
)

print(client.__dict__)
print(f"Ray job submitted with job_id: {job_id}")

# Wait for a while to let the jobs run
time.sleep(1)

job_status = client.get_job_status(job_id)
get_job_logs = client.get_job_logs(job_id)
get_job_info = client.get_job_info(job_id)
async for lines in client.tail_job_logs(job_id):
    print(lines, end="") 

# Disconnect from the Ray cluster
ray.shutdown()
```

The job:
```
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_series = [0, 1]
        while len(fib_series) < n:
            fib_series.append(fib_series[-1] + fib_series[-2])
        return fib_series

if __name__ == "__main__":
    result = fibonacci(100000)
    print(result)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by architkulkarni** [comment]
Thanks for the question! By default, the job entrypoint script runs on the head node. 0 cpus are allocated to the entrypoint script by default, so it runs on the head node even if the head node has 0 cpus.

To force the entrypoint script to run on a worker node, you would indeed need to set `entrypoint_num_cpus` as you have done.  You can see https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#specifying-cpu-and-gpu-resources for more details.

Does that help?

**Comment by sercanCyberVision** [comment]
Thank you, @architkulkarni, for the response. Is there a way to configure this behaviour during deployment to ensure it works for all job submissions? Currently, with this approach, relying on every individual end-user to include specific configuration for job execution creates complexity and exposes the head node to potential risks.

**Comment by architkulkarni** [comment]
Currently there's no way to configure the behavior during deployment. Even ignoring this feature, if the end user has access to Ray job submission, they can always schedule Ray tasks and actors to run on the head node, for example by using https://docs.ray.io/en/latest/ray-core/api/doc/ray.util.scheduling_strategies.NodeAffinitySchedulingStrategy.html in their Ray script to make it run on the head node.

**Comment by sercanCyberVision** [comment]
@architkulkarni, we have been using Ray-Client (10001) for job execution, and we would like to replace it with Ray-Submit (8265). When we set `num-cpus: 0` in `rayStartParams`, Ray-Client handles job executions as expected without requiring end-users to explicitly specify resources. We expected a similar behavior with Ray-Submit.

Do you anticipate implementing this feature in Ray-Submit in the future, ensuring that all jobs are executed by worker nodes without relying on external actions?

**Comment by architkulkarni** [comment]
If the issue is important to you, it would be great if you could open an github issue with it as a feature request.  If it turns out to be an important feature for many users, we may be able to prioritize it.  So far we haven't heard from users requesting this feature.  

Unfortunately there isn't a one-to-one mapping between Ray Client and Ray Jobs.  In your example, if you were using Ray Client you would likely wrap `fibonacci` in a Ray task (otherwise `fibonacci` would run on the client machine).  Putting the computation in a Ray task (with `@ray.remote`) is the recommended approach for Ray jobs as well.

**Comment by sercanCyberVision** [comment]
@architkulkarni, thank you much for all the details! It is more clear now.

**Comment by sercanCyberVision** [comment]
I have created a feature request https://github.com/ray-project/ray/issues/42436. Closing this ticket.

**Comment by jeffreylutz** [comment]
Hey.  There is a better way that Ray-Submit will support.  Set the ray clsuter yaml head node to resources: {"CPU": 0}   No jobs will ever run on the head node.

Reference:  https://docs.ray.io/en/latest/cluster/vms/user-guides/large-cluster-best-practices.html#vms-large-cluster-configure-head-node
