### ISSUE TITLE
[Tune][RLlib]Making 'local_dir' support remote storage such as hdfs

### ISSUE THREAD

**Issue by xutianming** [ray-project/ray#4244]
### Describe the problem

Currently ray tune writes logs and results (logs, tune checkpoint, tensorflow summary, etc.) to local storage.

In our scenario, users doesn't have direct access to ray clusters and are not allowed to log onto the machines for security reasons. To help them access ray logs when debugging, I am planning to make `local_dir` support HDFS.

To implement this, it seems that I have to change every  `open` to [smart_open](https://github.com/RaRe-Technologies/smart_open). I also have to handle all the `os.makedirs` to support remote storage. I don't think it is a good solution because it introduces too much complexity to ray codebase.

I also considered `upload_dir` option but it uploads after finishing the experiments. `local_dir` is more realtime and better for debugging.

Do you have any good suggestions ?

**Comment by ericl** [comment]
I think upload_dir supports periodic uploading, would that work? I believe it syncs every 5 minutes to remote storage. cc @hartikainen

**Comment by adoda** [comment]
Is better if the interval can be configured.
Other question is: We could upload 'ckpt file' to hdfs, but it  does not support to  restore from hdfs.
@ericl

**Comment by xutianming** [comment]
> I think upload_dir supports periodic uploading, would that work? I believe it syncs every 5 minutes to remote storage. cc @hartikainen

Yes, I checked the code. `upload_dir` supports periodic uploading which is great for us.
As mentioned by @adoda , after uploading ray results ( including xx.tune_metadata file) onto HDFS, users might want to recover training from HDFS using `restore` option. I think using `smart_open` to replace `open` [here](https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable.py#L299) should be good.

**Comment by ericl** [comment]
Agree that it should be configurable.

I thought restore already worked though since we sync the entire directory, @richardliaw (or is that whole-experiment only)?

**Comment by hartikainen** [comment]
I don't think the tune restore currently supports other than local files, although I think it would be useful to be able to restore experiments (either full experiment or single trials) from e.g. s3 or hdfs. There's an issue here: https://github.com/ray-project/ray/issues/3747.

**Comment by richardliaw** [comment]
This will make much more sense after the changes in https://github.com/ray-project/ray/pull/4234 -- we can then remove `Experiment(restore=str)` (which only supports 1 trial) in favor of something like `run(local_dir=..., upload_dir=HDFS_PATH, resume=True)`

@xutianming, @adoda how do your users launch experiments? Do they use `run_experiments` or a lower-level API?

**Comment by xutianming** [comment]
@richardliaw Most of our users use `run_experiments` and in most cases there is only one trial.
They usually do the following things:
- inherit one of existing agents (such as DQNAgent)
- add their own logics
- train the model using `run_experiments`
- export the TensorFlow graph
- do online experiments (through A/B test)
- collect more data
- restore the model and continue training

Users don't have access to ray cluster directly and can only submit jobs to our system.
When submitting jobs, they can provide some remote storage to read data (checkpoint) from and store the training results.

**Comment by richardliaw** [comment]
#4450 allows the user to specify arbitrary synchronizations with storage. Also, syncing is quite frequent (every 5 minutes). Please try those out and let me know if this is still an issue! @xutianming @adoda

**Comment by yushan111** [comment]
> #4450 allows the user to specify arbitrary synchronizations with storage. Also, syncing is quite frequent (every 5 minutes). Please try those out and let me know if this is still an issue! @xutianming @adoda

@richardliaw Could you please elaborate how to do this in this specific case? It will be really helpful if you could provide an example. (P.S. it seems only s3 and gs prefixes are allowed for remote_dir https://github.com/ray-project/ray/blob/master/python/ray/tune/syncer.py#L224)
