### ISSUE TITLE
[core] Release test failure:  microbenchmark.aws

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#42468]
### What happened + What you expected to happen

This release test triggers segfaults in Get in core worker.

```
[failure_signal_handler.cc : 332] RAW: Signal 11 raised at PC=0x3c05348 while already in AbslFailureSignalHandler()
PC: @          0x3c05348  (unknown)  (unknown)
    @     0x7f93d6153420       3328  (unknown)
    @     0x7f93d4a93393        384  ray::core::CoreWorkerMemoryStore::GetImpl()
    @     0x7f93d4a93b5c         64  ray::core::CoreWorkerMemoryStore::Get()
    @     0x7f93d4a93d6d        208  ray::core::CoreWorkerMemoryStore::Get()
    @     0x7f93d4a1d55e       1088  ray::core::CoreWorker::Get()
    @     0x7f93d48da02b        256  __pyx_pw_3ray_7_raylet_10CoreWorker_41get_objects()
    @           0x4f9ba6  1782318592  method_vectorcall_VARARGS_KEYWORDS
    @           0x73a180  (unknown)  (unknown)
[2024-01-14 23:45:22,436 E 4140 94486] logging.cc:361: *** SIGSEGV received at time=1705304722 on cpu 33 ***
```

Job: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_55byrxm51x8vrxkd7ibd8ubdx3

This failure is reproducible, as it has failed for several days in a row.

<img width="957" alt="image" src="https://github.com/ray-project/ray/assets/56065503/3b9bffb2-f219-42a8-b155-189b11d88401">

Test dashboard: https://b534fd88.us1a.app.preset.io/superset/dashboard/19/?native_filters_key=f_UyxTYCHuaxOY4XawEbbHMypZcR6jdn0seOvE9rhsMXVoio2a2eQWYcLETouIcq

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

High: It blocks me from completing my task.

**Comment by rynewang** [comment]
cc @rkooo567 @rickyyx @jjyao

**Comment by rkooo567** [comment]
@ericl it seems like after the FT PR, the segfault happens in normal ray workloads too, not just from compiled DAG

**Comment by rickyyx** [comment]
The original issue is https://github.com/ray-project/ray/issues/42292

**Comment by rkooo567** [comment]
cc @stephanie-wang do you have some bandwidth to actually take this issue?

**Comment by rkooo567** [comment]
duplicate https://github.com/ray-project/ray/issues/42602
