### ISSUE TITLE
[Core] Incorrect link to ray.remote package reference

### ISSUE THREAD

**Issue by aalmah** [ray-project/ray#42502]
### Description

The link to `ray.remote` api doc after the first code cell points to the core API main page (https://docs.ray.io/en/latest/ray-core/api/index.html), while it should point to https://docs.ray.io/en/latest/ray-core/api/doc/ray.remote.html

### Link

https://docs.ray.io/en/latest/ray-core/tasks.html#ray-remote-functions

**Comment by angelinalg** [comment]
Nice catch, @aalmah. This looks like a good candidate for using the GH UI to fix. Basically, there is a link on the page, called `Edit on GitHub`. Click on that and it sets up a PR for you. When you submit it, it will kick off a CI build and you can verify the fix before you submit the PR for approval. Let me know if you would like me to show you.

**Comment by geoffreylgv** [comment]
Hi @angelinalg, can I work on it ?
If so, kindly assign it to me
