### ISSUE TITLE
Tensorflow Eagertensor.numpy() doesn't work in remote functions.

### ISSUE THREAD

**Issue by axeln31459** [ray-project/ray#4250]
### System information
- Archlinux kernel 4.20.12-arch1-1-ARCH
-Tensorflow r1.13
- **Ray installed from (source or binary)**: binary pip
- **Ray version**:0.6.3
- **Python version**:3.7.2
- **Exact command to reproduce**:
call .numpy() on eagertensor in remote function, see code below.

### Describe the problem
For EagerTensors the .numpy() method throws the following error. In the local version the same code works, see code below. 

Local version works:  2.0
Traceback (most recent call last):
  File "debug.py", line 17, in <module>
    ray.get([convert_eager_numpy_remote.remote() for _ in range(10)])
  File "/usr/lib/python3.7/site-packages/ray/worker.py", line 2123, in get
    raise value
ray.worker.RayTaskError: ray_worker:__main__.convert_eager_numpy_remote() (pid=23592, host=airfin)
  File "debug.py", line 11, in convert_eager_numpy_remote
    return t.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'

### Source code / logs
import tensorflow as tf
import ray

def convert_eager_numpy():
    t=tf.constant(2.0,dtype=tf.float32)
    return t.numpy()

@ray.remote
def convert_eager_numpy_remote():
    t=tf.constant(2.0,dtype=tf.float32)
    return t.numpy()

ray.init()
tf.enable_eager_execution()
print("Local version works: ",convert_eager_numpy())
ray.get([convert_eager_numpy_remote.remote() for _ in range(10)])

**Comment by pcmoritz** [comment]
It could be possible that eager mode in the workers is not enabled. Can you
test if the following makes it work?

import tensorflow as tf
import ray

def convert_eager_numpy():
    t=tf.constant(2.0,dtype=tf.float32)
    return t.numpy()

@ray.remote
def convert_eager_numpy_remote():

    tf.enable_eager_execution()


    t=tf.constant(2.0,dtype=tf.float32)
    return t.numpy()

ray.init()
tf.enable_eager_execution()
print("Local version works: ",convert_eager_numpy())
ray.get([convert_eager_numpy_remote.remote() for _ in range(10)])

**Comment by axeln31459** [comment]
Thanks for the quick response, that works. I'll close the issue.
