### ISSUE TITLE
The many_tasks.py long running stress test crashes after an hour.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4256]
The relevant test is https://github.com/ray-project/ray/blob/master/ci/long_running_tests/workloads/many_tasks.py.

The issue appears to be that the node runs out of memory because the first raylet has many GB of messages buffered and waiting to be written to the other raylets. I determined this by looking at `debug_state.txt`.

**Comment by richardliaw** [comment]
Closing because stale. Feel free to reopen if necessary.
