### ISSUE TITLE
[serve] Smoothing factor blocks downscaling at small number of replicas

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#42612]
When there is a small number of replicas, and smoothing factor is small (any number < 1 can run into this issue), the smoothing factor can block downscaling because of the dampening effect it has + we use ceiling. Smoothing factor should not block downscaling.

**Comment by zcin** [comment]
Closed by https://github.com/ray-project/ray/pull/42394

**Comment by kyle-v6x** [comment]
As I mentioned in https://github.com/ray-project/ray/pull/42394, the non-linearity in the new logic is very non-intuitive and removes some usefull properties of downscaling factor. Untill this is resolved we've reverted our inference clusters to `<2.10`
