### ISSUE TITLE
[serve] Add default configuration for autoscaling that works out of the box

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#42613]
Provide a default configuration for autoscaling that works out of the box.

**Comment by edoakes** [comment]
Specifically, this means that setting: `num_replicas="auto"` should be sufficient for basic POCs.

**Comment by edoakes** [comment]
One issue here is the default for `max_concurrent_queries` is too high right now (100). We should change this in an upcoming release.

As a temporary fix, when `num_replicas="auto"` is set and `max_concurrent_queries` is unset, we'll default it.

Open question: what should the defaults be? To start, let's go with `max_concurrent_queries=5` and `target_num_ongoing_requests_per_replica=0.4*max_concurrent_queries=2`.

**Comment by edoakes** [comment]
Plan is:
- `target_num_ongoing_requests_per_replica` will default to `0.4* max_concurrent_queries` when not set.
- For 2.10, when `num_replicas="auto"` is set AND `max_concurrent_queries` is not set AND `target_num_ongoing_requests_per_replica` is not set, we’ll set max_concurrent_queries=5 (value is up for discussion).
- We’ll also add a warning and in 2.10 that the default will change and change the default entirely in 2.11.
