### ISSUE TITLE
[serve] Add autoscaling load test(s) as serve release test(s)

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#42611]
* Deploy an autoscaling application that runs a realistic workload (e.g. resnet)
* Run a load test against the application (e.g. using locust)
* Check that the deployment autoscales reasonably well:
  * When load increases, the number of replicas should also increase
  * Latency should stay relatively constant (there may be spikes that go back down when load increases)

**Comment by edoakes** [comment]
@zcin could you please break this into sub-issues?

**Comment by edoakes** [comment]
Marking P2 as draining is prioritized over it
