### ISSUE TITLE
[core] Object store transfer performance is poor

### ISSUE THREAD

**Issue by iycheng** [ray-project/ray#42632]
Benchmark script https://gist.github.com/lee1258561/e29a2322c19254c673a0c9f63af9aa54

Setup: 10 workers nodes 10Gbps NIC and 1 header node 100 Gbps.

The throughput is around 2-3GB/s.

<img width="1423" alt="image" src="https://github.com/ray-project/ray/assets/74173148/fff44df1-58bd-4104-ab06-45e29206849f">

On each node, the throughput is around 200-300MB. Highly the sender can't utilize the whole NIC due to some reason.

When tested with one node, the head node throughput is 200-300MB, so it scale very well with the number of nodes.

**Comment by iycheng** [comment]
One problem in the benchmark script is the way objects created. Objects are created by using the ray worker and this in the end could lead to too many owners. Each object has a different owner.

Though it shouldn't impact the performance so big, change it to something else does making things better.

[new scripts](https://gist.github.com/iycheng/573b868e21b0f9c955ef9c7986d47e3e)

<img width="278" alt="image" src="https://github.com/ray-project/ray/assets/74173148/7f6ee35d-82d2-4e99-a1a2-15d822dd7c6f">


```
Finished benchmark for total_size_MiB: 10737418240, block_size_MiB: 134217728, parallel_block: None
        ray.wait(fetch_local=True) Gbps: 44.925188296770976
        ray.wait(fetch_local=True) total time s: 1.912053108215332
        ray.get() Gbps: 16843.757372119668
        ray.get() total time s: 0.005099773406982422
Finished benchmark for total_size_MiB: 10737418240, block_size_MiB: 268435456, parallel_block: None
        ray.wait(fetch_local=True) Gbps: 48.67517767973902
        ray.wait(fetch_local=True) total time s: 1.7647464275360107
        ray.get() Gbps: 33906.26483998115
        ray.get() total time s: 0.002533435821533203
Finished benchmark for total_size_MiB: 10737418240, block_size_MiB: 536870912, parallel_block: None
        ray.wait(fetch_local=True) Gbps: 48.848062429669554
        ray.wait(fetch_local=True) total time s: 1.758500576019287
        ray.get() Gbps: 55823.980506606706
        ray.get() total time s: 0.0015387535095214844
```

Next step:

- Need to understand the true production workload
- Figure out why the original script is so slow compared with the new one.

**Comment by rkooo567** [comment]
@iycheng should we track this issue for ray 2.10? 

Also, what's the max bandwidth in this case?

**Comment by zen-xu** [comment]
Have you used [Ray Client](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html#ray-client) to connect to a Ray cluster? If so, this will be constrained by Python's gRPC serialization.

**Comment by iycheng** [comment]
> @iycheng should we track this issue for ray 2.10?
> 
> Also, what's the max bandwidth in this case?

> 10GB/s

**Comment by iycheng** [comment]
> Have you used [Ray Client](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html#ray-client) to connect to a Ray cluster? If so, this will be constrained by protobuf serialization.
> 
> also see #34772

Thanks @zen-xu for pointing it out. I don't use ray client in this case.

**Comment by iycheng** [comment]
I took another look and I feel the issue is that, there are some extra overhead which slow down the e2e performance.
It has nothing to do with the way objects are created.

The observation is that, the network usage actually is high

<img width="254" alt="image" src="https://github.com/ray-project/ray/assets/74173148/674af4fa-5924-473a-85f5-db7a18912037">



But the e2e performance is poor, only 30Gb/s


```
2024-01-24 13:08:15,079 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 10.0.59.98:6379...
2024-01-24 13:08:15,087 INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at https://session-lxgjneble3jd8gi5yfufuhbdkm.i.anyscaleuserdata-staging.com 
2024-01-24 13:08:15,096 INFO packaging.py:358 -- Pushing file package 'gcs://_ray_pkg_31b30bf8fe3979bdda35cc1f90879ab7.zip' (1.72MiB) to Ray cluster...
2024-01-24 13:08:15,104 INFO packaging.py:371 -- Successfully pushed file package 'gcs://_ray_pkg_31b30bf8fe3979bdda35cc1f90879ab7.zip'.
[2024-01-24 13:08:15,104 I 26655 26655] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet, ip=10.0.36.90) [2024-01-24 13:08:15,979 I 27464 27464] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
Finished benchmark for total_size_MiB: 53687091200, block_size_MiB: 536870912, parallel_block: None
        ray.wait(fetch_local=True) Gbps: 34.550865106563556
        ray.wait(fetch_local=True) total time s: 12.430853128433228
        ray.get() Gbps: 38556.56544985657
        ray.get() total time s: 0.011139392852783203
(raylet, ip=10.0.39.234) [2024-01-24 13:08:16,330 I 26952 26952] logging.cc:230: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1 [repeated 99x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
```

**Comment by rkooo567** [comment]
Finding root cause for this issue is P0 for 2.10. Depending on the scope, we can get everything we need in by 2.10 or 2.11
