### ISSUE TITLE
Release test iter_tensor_batches_benchmark_multi_node.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42646]
Release test **iter_tensor_batches_benchmark_multi_node.aws** failed. See https://buildkite.com/ray-project/release/builds/6576#018d3aad-c313-4f67-9ce5-c9c029ffa313 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by c21** [comment]
Hi @scottjlee can you help take a look?

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/9002#018dca9d-bee3-4b39-834b-2938635d4090
