### ISSUE TITLE
Release test workspace_template_serving_stable_diffusion.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42650]
Release test **workspace_template_serving_stable_diffusion.aws** failed. See https://buildkite.com/ray-project/release/builds/6577#018d3b02-8a8b-4cc4-9af3-18278df8e97d for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: cd8dd820ea20876e11f4574dc12dcdfca6cec18a found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/851

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/7064#018d54b8-2d5d-4446-b6d8-036ccb02ac13

**Comment by can-anyscale** [comment]
let's close to unjail

**Comment by edoakes** [comment]
Hooray!

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/7604#018d68d5-e3df-4581-a89c-52e2798b1ce3
