### ISSUE TITLE
[Train] Ray Train sets wrong interface on NCCL

### ISSUE THREAD

**Issue by surak** [ray-project/ray#42652]
### What happened + What you expected to happen

When using Ray on any supercomputer with infiniband interfaces, we noticed that ray sets the default to a strange default. Example of an output:

```
(RayTrainWorker pid=11904, ip=jwb0582i) jwb0582:11904:12354 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^lo,docker,veth
```

Looking for it, I found it at https://github.com/ray-project/ray/blob/52db1547994117792d65b0b67612385f4a4814c2/python/ray/train/constants.py#L101

Is there a justification for this line? By not setting it, it uses the default of the system, which is usually set by the sysadmins or by NCCL itself. When this is set by ray, things break.

### Versions / Dependencies

Ray 2.9.1, but happens in other versions. Multiple versions of NCCL, too. 

### Reproduction script

Any collective with ray

### Issue Severity

High: It blocks me from completing my task.

**Comment by matthewdeng** [comment]
Hey @surak, thanks for posting this issue. I think what you're saying makes sense. Let me take a look to see if it's possible to remove this default and use the system default instead.
