### ISSUE TITLE
[Dashboard] Dead head nodes shouldn't stay at the top.

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#42666]
### What happened + What you expected to happen

<img width="1678" alt="Screenshot 2024-01-24 at 11 22 32 AM" src="https://github.com/ray-project/ray/assets/9677264/820404a2-0deb-4c2d-bfb2-701e6af18806">

### Versions / Dependencies

2.9.0

### Reproduction script

n/a

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottsun94** [comment]
cc: @alanwguo

**Comment by alanwguo** [comment]
We can sort by state first and then node id. 

one concern I can think of that is the moment the node dies, it will disappear from view to the bottom. Seems like that should be okay?

**Comment by scottsun94** [comment]
> We can sort by state first and then node id.
> 
> one concern I can think of that is the moment the node dies, it will disappear from view to the bottom. Seems like that should be okay?

yeah. I think it's expected to see live nodes first.
