### ISSUE TITLE
Modernize Ray infrastructure and dependencies (Ubuntu, Cuda, Python, etc.)

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#42660]
### Description

This includes regular updates of ubuntu, cuda, python and other library dependencies on each Ray release

Current proposal for python upgrade lifecycle: https://docs.google.com/document/d/18ZhnyeFm6ewrYCPZtGxHqsBI-b9Oo6Dprkqfw4IsJwk/edit#heading=h.dx9ibbfyhwre

**Comment by besir-reddit** [comment]
> Current proposal for python upgrade lifecycle: https://docs.google.com/document/d/18ZhnyeFm6ewrYCPZtGxHqsBI-b9Oo6Dprkqfw4IsJwk/edit#heading=h.dx9ibbfyhwre

Is this document publicly available?

**Comment by aslonnie** [comment]
I am looking at this now. stay tuned.

**Comment by besir-reddit** [comment]
Thanks @aslonnie!

**Comment by aslonnie** [comment]
ubuntu base image and cuda have been upgraded in ray repo.

we are working on supporting python 3.12

not exactly sure about the rest of the scope/work items of this issue though.

@can-anyscale should we just close this for now?

**Comment by can-anyscale** [comment]
let's close, we probably need to do python 3.13 end this year
