### ISSUE TITLE
[bug] ray header and worker node starts concurrently and worker does not get header config correctly

### ISSUE THREAD

**Issue by chuxi** [ray-project/ray#4266]
### System information
- **Linux CentOS 7**:
- **Ray installed from Source**:
- **master branch**:
- **python 3.6**:
- **ray start --head --redis-port 6379 --include-java (node1)    && ray start --redis-address node1:6379 (node2)**:

### Describe the problem
if you start ray header on node1, and start ray worker on node2 concurrently, the worker may fail for it does not get `INCLUDE_JAVA` from redis and the worker raylet starts java initial worker processes which caused the `Language not supported` bug.

### Source code / logs

scripts.py
```python
        # Wait for the Redis server to be started. And throw an exception if we
        # can't connect to it.
        services.wait_for_redis_to_start(
            redis_ip_address, int(redis_port), password=redis_password)
```

node.py
```python
            # worker get the include_java from redis
            ray_params.include_java = (
                ray.services.include_java_from_redis(redis_client))
```

and it failed for raylet to start a java process
```
2019-03-05 15:53:33,032 I 11183 11183 node_manager.cc:368:] [ConnectClient] Trying to connect to client 07dd8853c2c603a6925e41eebc05c61bdc016485 at 11.146.154.109:36705
2019-03-05 15:53:33,757 F 11183 11183 worker_pool.cc:266:]  Check failed: state != states_by_lang_.end() Required Language isn't supported.
```

**Comment by raulchen** [comment]
Other python options may also this issue.

**Comment by richardliaw** [comment]
Closing because stale. Feel free to reopen if necessary.
