### ISSUE TITLE
Where is the dashboard?

### ISSUE THREAD

**Issue by fjibj** [ray-project/ray#4269]
I have installed ray with "pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.7.0.dev0-cp36-cp36m-manylinux1_x86_64.whl".
but when i "ray up"a cluster, or "ray.init()"in python script, i can't see the dashboard. Why??

[root@vcapp43 github]# python
Python 3.6.8 (default, Feb 21 2019, 19:12:46) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init()
2019-03-05 19:39:58,008	INFO node.py:439 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-03-05_19-39-58_4635/logs.
2019-03-05 19:39:58,114	INFO services.py:364 -- Waiting for redis server at 127.0.0.1:18485 to respond...
2019-03-05 19:39:58,228	INFO services.py:364 -- Waiting for redis server at 127.0.0.1:29176 to respond...
2019-03-05 19:39:58,231	INFO services.py:761 -- Starting Redis shard with 3.33 GB max memory.
2019-03-05 19:39:58,244	INFO services.py:1449 -- Starting the Plasma object store with 5.0 GB memory using /dev/shm.
{'node_ip_address': None, 'redis_address': '172.32.150.43:18485', 'object_store_address': '/tmp/ray/session_2019-03-05_19-39-58_4635/sockets/plasma_store', '
**webui_url': None**, 'raylet_socket_name': '/tmp/ray/session_2019-03-05_19-39-58_4635/sockets/raylet'}

**Comment by fjibj** [comment]
i know. 
should add the param **--include-webui**.
i.e.  
ray start --head --redis-port=6379 --include-webui

**Comment by fjibj** [comment]
But how to "ray up" a cluster with dashboard??

i find no "ray xxxx" command have the param --include-webui except "ray start".

**Comment by robertnishihara** [comment]
Hi @fjibj `ray start --head --redis-port=6379 --include-webui` is the way to go. That should start the dashboard. If you start the Ray processes via `ray.init()`, then pass in `ray.init(include_webui=True)`.

**Comment by ls-daniel** [comment]
The dashboard is broken in current master. It is impossible to start the reporter processes on the worker nodes without modifying the source code or manually bringing them up.

https://github.com/ray-project/ray/pull/4285 fixes it.

**Comment by robertnishihara** [comment]
Fixed by #4428.

**Comment by mirekphd** [comment]
Note that the argument name has changed to `ray.init(include_dashboardi=True)` and the intuitive `pip install ray` will _not_ install Ray Dashboard (one needs to use `pip install ray[default]` instead).
> If you start the Ray processes via `ray.init()`, then pass in `ray.init(include_webui=True)`.

**Comment by mthnguyen01** [comment]
I am having trouble viewing the dashboard too. I ran `ray.init()` and `ray.init(include_dashboard=True)` both doesn't work. I am currently trying to start ray via a docker container. Anyone has any suggestion? I tried checking `localhost:8265` but that didn't work.

**Comment by sxnityq** [comment]
I am facing the trouble to establish connection to ray dashboard too

```
response = ray.init(address="ray://<my host>:10001",
             include_dashboard=True)
```

I can connect to cluster and my code is running properly, but i actually can't see a dashboard
At the response i get:

`ClientContext(dashboard_url='' ", ....)`
