### ISSUE TITLE
[Core] Infinite gcs_server.exe Generation in windows 10

### ISSUE THREAD

**Issue by Wsirius** [ray-project/ray#42700]
### What happened + What you expected to happen

I am experiencing an issue while using the ray with Pyinstaller
where gcs_server.exe instances are continuously generated, causing a significant system load.

### Versions / Dependencies

**Environment:**
- Ray Version: 2.9.1
- Operating System: Windows 10
- Python Version: 3.10.9

### Reproduction script

**Reproduction Steps:**
### -- test.py --
```python
import ray
import time

def main():
    ray.init(num_cpus=4, include_dashboard=False)
    while True:
        print(1)
        time.sleep(1)

main()
```
this is small test
_ _ _
### -- test.spec --
```spec
a = Analysis(
    ['test.py'], pathex=[], binaries=[], datas=[],
    hiddenimports=[], hookspath=['hooks'],
    hooksconfig={}, runtime_hooks=[],
    excludes=[], noarchive=False,)

pyz = PYZ(a.pure)

exe = EXE(
    pyz, a.scripts, [], exclude_binaries=True,
    name='test', debug=False, bootloader_ignore_signals=False,
    strip=False, upx=True,  console=False, disable_windowed_traceback=False,
    argv_emulation=False, target_arch=None, uac_admin=True,
    codesign_identity=None, entitlements_file=None,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=True,
    upx_exclude=[], name='test',
)
```
In the hooks folder, there is code to copy the ray package
### -- hooks/hook-ray.py --
```python
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

hiddenimports = collect_submodules("ray")
datas = collect_data_files("ray", include_py_files=True)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by mattip** [comment]
Does this happen without pyinstaller?

**Comment by anyscalesam** [comment]
tag @Wsirius

**Comment by anyscalesam** [comment]
@Wsirius is there a reason you can't just use pip?

**Comment by Wsirius** [comment]
@anyscalesam I want to package a project containing the Ray library into an exe file using pyInstaller for distribution. Initially, I deployed the project using a different method, but my client prefers pyInstaller, so I'm still working on it.
