### ISSUE TITLE
Support for Custom Environments based on spaces.Dict?

### ISSUE THREAD

**Issue by RylanSchaeffer** [ray-project/ray#4270]
Many of Ray's RL algorithms make assumptions concerning the structure of the environment's action and observations spaces. For instance, DDPG only supports the `Box` action space:

```
class DDPGPolicyGraph(TFPolicyGraph):
    def __init__(self, observation_space, action_space, config):
        config = dict(ray.rllib.agents.ddpg.ddpg.DEFAULT_CONFIG, **config)
        if not isinstance(action_space, Box):
            raise UnsupportedSpaceException(
                "Action space {} is not supported for DDPG.".format(
                    action_space))
```

However, I would like to use custom environments that use spaces of [type `Dict`](https://github.com/openai/gym/blob/master/gym/spaces/dict_space.py), as this seems necessary to handle actions with different permissible ranges. Could these various algorithms be modified to support spaces.Dict?

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.3
- **Python version**: 3.6.7
- **Exact command to reproduce**:

**Comment by ericl** [comment]
I'm not sure how to represent Q values for these types of nested spaces. @joneswong did you have any ideas on more general support here (similar to the HFO hierarchical spaces paper?)

**Comment by ericl** [comment]
Actually, could you provide an example of why you'd need to use a Dict action space with DDPG? You can get pretty far with a Box.

**Comment by joneswong** [comment]
For HFO, a viable solution is to flatten the discrete part and the continuous part together as a 10-dimensional Box. Each action can be translated accordingly by your environment wrapper.

**Comment by joneswong** [comment]
so what's the space type of each element in your Dict? As DDPG only predict a continuous action, I think there are just several Box spaces in the Dict. In this case, just flatten them. Could you tell me your situation?

**Comment by bionicles** [comment]
Hi, I could definitely use support for dict because we're doing a molecular dynamics simulation which has multiple features and also variable num_atoms == different observation and action spaces, we wanted to pass multiple inputs to our agents (features and noise) and the thing works like a resnet + gan, using the features to transform the noise into the action, instead of directly transforming features into action

**Comment by bionicles** [comment]
just gonna try to work around this for now and simplify things

**Comment by bionicles** [comment]
will it be a huge problem if the environments are stateful? We want to calculate some supervised losses in the env which require access to the initial state of the simulation...

**Comment by joneswong** [comment]
Then only requirement on environment is to respect gym interface. Most environments are stateful. For complicated observation/action spaces, gym.spaces.Dict type is always a choice and the remaining things are defining a corresponding customized model class. For example, let the observation dict contains a set of candidate actions, etc. If there is assertion on the observation/action spaces in DQN/DDPG, you could also override it by creating your own agent class.

**Comment by richardliaw** [comment]
This should be done now (but feel free to reopen if not the case) cc @sven1977
