### ISSUE TITLE
what is the best version of TensorFlow in using attention_net_supervised.py?

### ISSUE THREAD

**Issue by SaraRezaei** [ray-project/ray#42732]
Ray used tf.enable_eager_execution() in attention_net_supervised.py that is useful for TensorFlow V.1.X because TensorFlow 2.0 has eager_execution enabled by defualt and so there is no need to run tf.enable_eager_execution(). 

On the other hand, Python 3.8+ support requires TensorFlow 2.2 or later.

As a result, I used TensorFlow 2.11.0 with python 3.8 and I commented  tf.enable_eager_execution() line. but I fall in many errors such as this:

 ValueError: Tensor("strided_slice_1:0", shape=(), dtype=int32) must be from the same graph as Tensor("strided_slice_1:0", shape=(), dtype=int32) (graphs are <tensorflow.python.framework.ops.Graph object at 0x7f4469767b80> and FuncGraph(name=update_step, id=139931793534112)).

(Notice: I must use Python 3.8 and Ray 1.8 because I'm using https://github.com/Replicable-MARL/MARLlib project and I can't upgrade them!)

**Comment by anyscalesam** [comment]
Best bet here @SaraRezaei  is to upgrade Replicable-MARL's Python and Ray versions; 1.8 is over 2Y old at this point.
