### ISSUE TITLE
Build Ray Java code with Bazel.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4273]
Currently it still uses cmake. Related to https://github.com/ray-project/ray/issues/2887. Some work was done on this in https://github.com/ray-project/ray/pull/3918.

**Comment by robertnishihara** [comment]
@guoyuhong What still needs to be done here? It'd be great to deprecate cmake as quickly as possible.

**Comment by jovany-wang** [comment]
We are working on this right now. I believe that it'll be met soon.

**Comment by pcmoritz** [comment]
We need to make sure that ray can still compile if the java development environment is not installed, i.e. there should be a flag to deactivate it, or it should be a separate target, or it should only be compiled if the java development headers are available.
