### ISSUE TITLE
Reduce warnings when running `ray stop`.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4274]
`ray stop` shouldn't output WARNING messages -- causes bad user experience.
```
(py36) ubuntu@ip-172-31-6-78:~$ ray stop
WARNING: Not monitoring node memory since `psutil` is not installed. Install this with `pip install psutil` (or ray[debug]) to enable debugging of memory-related crashes.
```

**Comment by ericl** [comment]
I'm wondering if we be smarter about adding psutil as a dep, that would eliminate this warning in most cases.

What if we auto-installed psutil if the `gcc` binary is found?

**Comment by robertnishihara** [comment]
Haha I mean `ray.init` could always try to `do `pip install psutil` in a subprocess, though it's a bit weird.

For the common case where you are installing Ray with `pip install ray`, I don't think we can actually include much "logic". Dependencies are all managed by pip.

**Comment by ericl** [comment]
I think we have a limited scope of freedom in setup.py to determine the contents of `requires`. This could involve running arbitrary code to see if gcc exists.

**Comment by robertnishihara** [comment]
@ericl that's right, but what I mean is if you just do `pip install ray` it don't think it runs `setup.py`.

**Comment by ericl** [comment]
What if we vendored psutil?
