### ISSUE TITLE
[ci] Minimal build tests install dependencies from latest Ray release instead of locally-installed version

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#42757]
Discovered in: https://github.com/ray-project/ray/pull/42740.

The [min.build.Dockerfile](https://github.com/ray-project/ray/blob/df3dd96c1e54df5428b6a6dc3f085103421cfc89/ci/docker/min.build.Dockerfile#L31) pulls the "extra" dependencies from the latest release on PyPI instead of the version being tested in CI.

**Comment by edoakes** [comment]
One idea for how to solve this:

Instead of duplicating the dependencies in `setup.py` and `requirements.txt`, only have them in `requirements.txt` and `requirements_{extra}.txt` for each extra target we have.

Then in the testing we can just directly install from those `requirements_{extra}.txt` files.

**Comment by can-anyscale** [comment]
This has been fixed with https://github.com/ray-project/ray/pull/42758
