### ISSUE TITLE
[core][dags] Support multiple args and kwargs in accelerated DAGs

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#42793]
### Description

Right now the experimental accelerated DAGs feature only supports a single argument and output per task. Ideally we want to be able to pass/return multiple. This can be done by serializing the argument list/dict and passing it through the channel, instead of [assuming and serializing only one value](https://github.com/ray-project/ray/blob/master/python/ray/experimental/channel.py#L118).

We should also support no-args.

**Comment by rkooo567** [comment]
This is needed for OSS vllm.
