### ISSUE TITLE
[Data] Measure time spent in Ray Data tasks

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#42801]
### Description

Measure the total time spent during:
- per-task serialization overhead
- actual work of task (the UDF)

### Use case

Additional stats collection for Ray Data performance debugging tool

**Comment by omatthew98** [comment]
The per task serialization occurs in Ray core code (`_raylet.pyx` [here](https://github.com/ray-project/ray/blob/3fe0c07a6e68102fe6d3b2e9d2548efc8d1dd4c1/python/ray/_raylet.pyx#L1647)), which will make it difficult to time this code and attribute it to datasets or operators. At the data level, we will focus on timing the total time of the Ray Data tasks and then the time spent in UDFs.
