### ISSUE TITLE
[Data] `ExtensionArrayFormatter` import error with pandas 2.2.0

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#42842]
### What happened + What you expected to happen

With the newly release version of pandas 2.2.0, the class `ExtensionArrayFormatter ` is no longer available, so we get the following error:
```
ImportError: cannot import name 'ExtensionArrayFormatter' from 'pandas.io.formats.format' (.../lib/python3.9/site-packages/pandas/io/formats/format.py)
```

The current workaround is to downgrade pandas to a lower version.

### Versions / Dependencies

ray master, pandas 2.2.0

### Reproduction script

```
import ray
ds = ray.data.range(10)
ds.take(10)
```

results in 
```
ImportError: cannot import name 'ExtensionArrayFormatter' from 'pandas.io.formats.format' (.../lib/python3.9/site-packages/pandas/io/formats/format.py)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by feuyeux** [comment]
```sh
pip install -U "ray[data]"
```

```sh
# workaround for https://github.com/ray-project/ray/issues/42842

pip uninstall pandas
pip install pandas==
pip install -Iv pandas==2.1.4
```

**Comment by scottjlee** [comment]
Closed by https://github.com/ray-project/ray/pull/42892, please merge in latest master and give it a try. If you continue to run into problems, feel free to re-open this issue.
