### ISSUE TITLE
[<Ray component: Core] Bad experience to debug ray job failure 

### ISSUE THREAD

**Issue by gtarcoder** [ray-project/ray#42865]
### Description

Is there a SOP to debug ray job failure?
Each time I meet a ray job failure, I will have to suffer a lot to debug, but almost all the time when it is related with OOM issue, I can not find the root cause of failure..

### Link

no

**Comment by anyscalesam** [comment]
@gtarcoder see here https://docs.ray.io/en/latest/ray-observability/user-guides/debug-apps/debug-memory.html
