### ISSUE TITLE
Ray timeout

### ISSUE THREAD

**Issue by erlan-11** [ray-project/ray#42908]
### What happened + What you expected to happen

```
INFO flwr 2024-02-01 10:09:24,690 | app.py:178 | Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2024-02-01 10:09:24,690][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\ray\_private\node.py", line 312, in __init__
    ray._private.services.wait_for_node(
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\ray\_private\services.py", line 463, in wait_for_node       
    raise TimeoutError(
TimeoutError: Timed out after 60 seconds while waiting for node to startup. Did not find socket name tcp://127.0.0.1:64131 in the list of object store socket names.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\Python_Project\main.py", line 33, in main
    history = fl.simulation.start_simulation(
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\flwr\simulation\app.py", line 211, in start_simulation      
    ray.init(**ray_init_args)
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper     
    return func(*args, **kwargs)
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\ray\_private\worker.py", line 1618, in init
    _global_node = ray._private.node.Node(
  File "D:\software\miniconda\envs\TFF3.9\lib\site-packages\ray\_private\node.py", line 317, in __init__
    raise Exception(
Exception: The current node timed out during startup. This could happen because some of the Ray processes failed to startup.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Versions / Dependencies

conda 24.1.0
Package                      Version
---------------------------- ----------
absl-py                      2.1.0
aiohttp                      3.9.3
aiosignal                    1.3.1
antlr4-python3-runtime       4.9.3
astunparse                   1.6.3
async-timeout                4.0.3
attrs                        23.2.0
Brotli                       1.0.9
cachetools                   5.3.2
certifi                      2023.11.17
cffi                         1.16.0
chardet                      5.2.0
charset-normalizer           2.0.4
click                        8.1.7
colorama                     0.4.6
contourpy                    1.2.0
cryptography                 41.0.7
cycler                       0.12.1
datasets                     2.16.1
dill                         0.3.7
filelock                     3.13.1
flatbuffers                  23.5.26
flwr                         1.6.0
flwr-datasets                0.0.2
fonttools                    4.47.2
frozenlist                   1.4.1
fsspec                       2023.10.0
gast                         0.5.4
gmpy2                        2.1.2
google-auth                  2.27.0
google-auth-oauthlib         1.2.0
google-pasta                 0.2.0
grpcio                       1.60.0
h5py                         3.10.0
huggingface-hub              0.20.3
hydra-core                   1.3.2
idna                         3.4
importlib-metadata           7.0.1
importlib-resources          6.1.1
iterators                    0.0.2
Jinja2                       3.1.3
jsonschema                   4.21.1
jsonschema-specifications    2023.12.1
keras                        2.15.0
kiwisolver                   1.4.5
libclang                     16.0.6
Markdown                     3.5.2
MarkupSafe                   2.1.3
matplotlib                   3.8.2
mkl-fft                      1.3.8
mkl-random                   1.2.4
mkl-service                  2.4.0
ml-dtypes                    0.2.0
mpmath                       1.3.0
msgpack                      1.0.7
multidict                    6.0.4
multiprocess                 0.70.15
networkx                     3.1
numpy                        1.26.3
oauthlib                     3.2.2
omegaconf                    2.3.0
opt-einsum                   3.3.0
packaging                    23.2
pandas                       2.2.0
Pillow                       10.0.1
pip                          23.3.2
protobuf                     3.20.3
pyarrow                      15.0.0
pyarrow-hotfix               0.6
pyasn1                       0.5.1
pyasn1-modules               0.3.0
pycparser                    2.21
pycryptodome                 3.20.0
pydantic                     1.10.14
pyOpenSSL                    23.2.0
pyparsing                    3.1.1
PySocks                      1.7.1
python-dateutil              2.8.2
pytz                         2023.4
PyYAML                       6.0.1
ray                          2.9.1
redis                        5.0.1
referencing                  0.32.1
requests                     2.31.0
requests-oauthlib            1.3.1
rpds-py                      0.17.1
rsa                          4.9
setuptools                   68.2.2
six                          1.16.0
sympy                        1.12
tensorboard                  2.15.1
tensorboard-data-server      0.7.2
tensorflow                   2.15.0
tensorflow-estimator         2.15.0
tensorflow-intel             2.15.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
torch                        2.2.0
torchaudio                   2.2.0
torchvision                  0.17.0
tqdm                         4.66.1
typing_extensions            4.9.0
tzdata                       2023.4
urllib3                      1.26.18
Werkzeug                     3.0.1
wheel                        0.41.2
win-inet-pton                1.1.0
wrapt                        1.14.1
xxhash                       3.4.1
yarl                         1.9.4
zipp                         3.17.0

### Reproduction script

```
from http import client
import hydra
from omegaconf import DictConfig, OmegaConf
from client import generate_client_fn
from dataset import Prepare_dataset

import flwr as fl

from server import get_on_fit_config ,get_evalulate_fn


@hydra.main(config_path="conf", config_name="base", version_base=None)
def main(cfg: DictConfig):
    # 1. Parse config & get experiment output dir 解析配置并获取实验输出目录
    print(OmegaConf.to_yaml(cfg))
    # 2. Prepare your dataset 准备数据集
    trainloaders, validationloaders, testloader = Prepare_dataset(cfg.num_clients, cfg.batch_size)

    # print(len(trainloaders), len(trainloaders[0].dataset))
    # 3. Define your clients 定义您的客户
    client_fn = generate_client_fn(trainloaders,validationloaders,cfg.num_classes)

    # 4. Define your strategy 确定战略
    strategy= fl.server.strategy.FedAvg(fraction_fit=0.00001,
                                            min_fit_clients=cfg.num_clients_per_round_fit,
                                            fraction_evaluate=0.00001,
                                            min_evaluate_clients=cfg.num_clients_per_round_eval,
                                            min_available_clients=cfg.num_clients,
                                            on_fit_config_fn=get_on_fit_config(cfg.config_fit),
                                            evaluate_fn=get_evalulate_fn(cfg.num_classes,
                                                                         testloader))
    # 5. Start Simulation 开始模拟
    history = fl.simulation.start_simulation(
        client_fn=client_fn,
        num_clients=cfg.num_clients,
        config=fl.server.ServerConfig(num_rounds=cfg.num_rounds),
        strategy=strategy,
    )
    # 6. Save your results 保存结果

if __name__ == "__main__":
    main()
```

### Issue Severity

High: It blocks me from completing my task.

Edit: formatting(@mattip)

**Comment by erlan-11** [comment]
This is code based on a tutorial for the Flower framework on YouTube, but the timeout occurs

**Comment by anyscalesam** [comment]
@mattip can you please triage and take a look

**Comment by mattip** [comment]
There is no config file so reproducing is difficult. I see that the list of packages includes `grpcio==1.6.0` and `pandas==2.2.0`. That version of pandas should be blocked due to #42842, but I think this issue might be caused by `grpcio`. Where are you getting the dependencies, from PyPI (`pip install...`) or from conda/anaconda (`conda install ...`)? Could you try installing `grpcio==1.57`, like the version [ray is built with](https://github.com/ray-project/ray/blob/c6ab40374eb6bdb2bfd2984d039a962946cdc318/bazel/ray_deps_setup.bzl#L237)

**Comment by mattip** [comment]
It may also be helpful to look at the logs in %TEMP%\ray to see if the worker is failing to start for some reason

**Comment by erlan-11** [comment]
> It may also be helpful to look at the logs in %TEMP%\ray to see if the worker is failing to start for some reason

I think it's probably because I'm using win11 that I can run correctly on Ubuntu

**Comment by mattip** [comment]
Why is there no python in your dependencies list? Maybe you got python via the app store, we have had reports that version is problematic.

**Comment by anyscalesam** [comment]
@erlan-11 can you respond to @mattip's clarifying question above?
