### ISSUE TITLE
[Data] `write_bigquery` errors don't propagate to driver 

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#42924]
### What happened + What you expected to happen

I ran a job that writes to BigQuery. I see errors like the following in STDOUT:

```
(Write pid=399, ip=192.168.9.90) google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table my-data-warehouse:ai.fact_completion_metrics. Field created_at has changed type from TIMESTAMP to FLOAT; reason: invalid, message: Provided Schema does not match Table my-data-warehouse:ai.fact_completion_metrics. Field created_at has changed type from TIMESTAMP to FLOAT 
```

But I don't see a traceback on the driver side, and when I check the status code I see 0
```
❯ echo $? 
0
```

The reason is that we don't call `ray.get` on the `_write_single_block` remote task. So, the error isn't propagated to the driver.

https://github.com/ray-project/ray/blob/55a4ee486cb1b8336fb462565100265550eb9f1b/python/ray/data/datasource/bigquery_datasink.py#L124

### Versions / Dependencies

55a4ee486cb1b8336fb462565100265550eb9f1b

### Reproduction script

...

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by bveeramani** [comment]
cc @matthew29tang

**Comment by ujjawal-khare-27** [comment]
Hey @bveeramani  I am not able to reproduce this.
