### ISSUE TITLE
[Dashboard] add filtering by job status to Jobs page

### ISSUE THREAD

**Issue by robcaulk** [ray-project/ray#42940]
### Description

As we are running many jobs, some are longer running than others, it would be really convenient to be able to sort the job list in the dashboard according to their "Status". In addition, sorting on all other columns such as "StartTime" and "EndTime".

![image](https://github.com/ray-project/ray/assets/20807672/a1817f1f-9f28-4653-966b-a345dffe441a)

### Use case

We need to be able to sort the Jobs list on the columns (ascending/descending).

**Comment by scottsun94** [comment]
This will be in our backlog for now. If anyone is interested in contribution, we will help review and land the PR.
