### ISSUE TITLE
[<Ray component: Serve|AWS|>] why am I using ray 2.9.1 to start a cluster? header ray for the cluster is 3.0.0dev0 

### ISSUE THREAD

**Issue by surreal-xiyichan** [ray-project/ray#42966]
### What happened + What you expected to happen

<img width="681" alt="image" src="https://github.com/ray-project/ray/assets/121000066/98d5b5ec-1b5e-4a2a-b315-53dc43286fbe">

i want to use ray 2.9.1

### Versions / Dependencies

ray 2.9.1
<img width="681" alt="image" src="https://github.com/ray-project/ray/assets/121000066/6c91aee3-ffd6-4be1-9cfb-d6a798eabb2a">

### Reproduction script

I refer to this document to use
https://docs.ray.io/en/latest/cluster/vms/getting-started.html#vm-cluster-quick-start

### Issue Severity

None

**Comment by iycheng** [comment]
It'll use whatever the ray installed on the node. Could you make sure the image you are using contains 2.9 ray?

**Comment by jjyao** [comment]
Yea, we have an issue for it: https://github.com/ray-project/ray/issues/34991. Close it as duplicate.
