### ISSUE TITLE
[Ray data] will ray data support read and write object systems like cos/oss

### ISSUE THREAD

**Issue by gtarcoder** [ray-project/ray#42971]
### Description

Ray data supports r/w s3 filesystem, but there are many object systems such as COS(https://www.tencentcloud.com/products/cos) and OSS(https://www.alibabacloud.com/product/object-storage-service). So I am wondering if ray can support r/w COS and OSS?

**Comment by raulchen** [comment]
I think they have S3-compatible APIs. then should already be supported. Ray Data uses PyArrow under the hood for accessing cloud storage. So if PyArrow supports them, Ray Data will as well.
