### ISSUE TITLE
Un-hard coding the autoscaler's SSH control path

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#4297]
This line was inserted into `ray.autoscaler.updater` to dramatically improve efficiency:

https://github.com/ray-project/ray/blob/e2e6ef198bb281151b7fd0ab478d44b2066c8f55/python/ray/autoscaler/updater.py#L25

Hard-coding has the disadvantage that in a cluster / HPC environment, multiple users running Ray would then not be possible because of permissions issues on that directory. Going to try to figure out a way to insert this as a `ray up` / `ray start` parameter.

**Comment by richardliaw** [comment]
Addressed.
