### ISSUE TITLE
[Doc] Support Community Examples

### ISSUE THREAD

**Issue by woshiyyya** [ray-project/ray#42983]
### Description

We've noticed many external example contributions these days. To consolidate these examples in to ray documentation and encourage more participation, we're planning to support "community examples" for open source users to contribute. These community examples will be maintained primarily by contributors.

### How to display them?
On each library's example page:
- Have a new section called "Community Examples", and put all the community examples into this section.
- The examples can be a link to an external repo, or a notebook in ray repo.

On Example Gallery:
- Create a card for each community example with an additional "Community Example" tag.
- Enable result filtering based on the "Community Example" tag.
- (Optional) Place all community examples at the end of filtered results.

### Maintenance Policy
- Issues related to these examples will be directed to the original authors.
- Ray Team will not setup CI/release tests for these examples.
- If critical issues have not been resolved for more than 2 (TBD) release cycles, we will remove them from the ray documentation.

**Comment by woshiyyya** [comment]
Currently we are refactoring the examples page. According to this [draft PR](http://train_transformers_glue_example/), the community examples will have all existing metadata(like framework, skill level, ...) and add another attribute `{"community_example": bool}`

**Comment by simran-2797** [comment]
design for example gallery - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=397%3A1375&mode=design&t=lXO7xuinlPpBwmxG-1
@peytondmurray @angelinalg

**Comment by simran-2797** [comment]
I thought "community example" was a confusing term. @angelinalg do you have any suggestions here?

**Comment by angelinalg** [comment]
@woshiyyya, may I ask, what is not clear about `Contributed by Ray Community`? The reader is in the Example Gallery, so the word `example` in `Community Example` is redundant. I think @simran-2797 is trying to be more descriptive. Are you concerned that the `Ray Community` may also be interpreted as Anyscale?

**Comment by woshiyyya** [comment]
Yes, because Anyscale Ray is part of the Ray community. I think the special term "Community Example" can distinguish this. But based on our discussion, I think "Contributed by Community" also looks clear to me.

**Comment by woshiyyya** [comment]
@anyscalesam doc infra team will help incorporating the changes and Libraries team will help migrating examples:)

**Comment by peytondmurray** [comment]
@simran-2797 What controls will we need for filtering community examples? I think we need something about this in the example gallery mockups.

**Comment by simran-2797** [comment]
@peytondmurray - Check out this design - https://www.figma.com/proto/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?page-id=1%3A10&type=design&node-id=397-1375&viewport=-10292%2C-7628%2C0.63&t=8I7J9HBD2Pdwj4RK-1&scaling=min-zoom&starting-point-node-id=1%3A176&show-proto-sidebar=1&mode=design
For filters, as you suggested, we can add another dropdown picker with the following options - "All examples","Contributed by Ray community", "Examples by the Ray team". 
@angelinalg Do you have any suggestions on the text for these filters?
