### ISSUE TITLE
All arguments to `_remote` should be optional. Currently `args` and `kwargs` are required.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4300]

**Comment by zbarry** [comment]
Since this is tagged "good first issue", would you mind elaborating a little bit on what `_remote` is referring to? Doesn't appear to be `func.remote()`.

**Comment by virtualluke** [comment]
From the source code in ray/remote_function.py :
```
def _remote(self,
                args=None,
                kwargs=None,
                num_return_vals=None,
                num_cpus=None,
                num_gpus=None,
                resources=None):
        """An experimental alternate way to submit remote functions."""
```
This allows setting those parameters in the remote call, vs decoration of the function.

**Comment by zbarry** [comment]
Ok, cool. So this would be a nicer way of implementing:

```python
def blah(arg):
    return thing

ray.remote(blah)(num_cpus=10000).remote(arg)
```

Where the alternative to having to hard code the number of CPUs in the decorator is just to not use it as a decorator?

**Comment by robertnishihara** [comment]
@justinwyang has been working on this in https://github.com/ray-project/ray/pull/4305.

@zbarry that's exactly right. And you're right it is already optional for remote function invocations. However, it isn't for actor creation and actor method invocation.
