### ISSUE TITLE
[Serve] Add inference serve example to run Stable Diffusion Inference using AWS Inferentia2

### ISSUE THREAD

**Issue by ratnopamc** [ray-project/ray#43018]
### Description

Add example of how to run inference using RayServe for Stable Diffusion model using AWS Inferentia2.
The example will showcase how to leverage AWS Inf2 instances to set up neuron libraries and use RayServe to run inference on a neuron compatible Stable Diffusion model. 

### Link

Add example for Stable Diffusion based inference similar to [aws-neuron BERT-base example](https://docs.ray.io/en/latest/serve/tutorials/aws-neuron-core-inference.html)

**Comment by ratnopamc** [comment]
You can assign this issue to me.

**Comment by GeneDer** [comment]
Sg, thanks @ratnopamc Feel free to let us know when the PR is ready or if you runs into any issue

**Comment by ratnopamc** [comment]
@GeneDer , I've raised a PR https://github.com/ray-project/ray/issues/43018 to store the output image. The github url of the image is referenced in the docs. Can you please merge the above PR? Once it's merged, I can push the PR for the doc changes. 
Thanks.

**Comment by GeneDer** [comment]
@ratnopamc I think you are referring to this PR? https://github.com/ray-project/ray/pull/43046 I see that DCO, premerge, and docs build all failed. Can you try to fix them? I think you tagged the right person for reviews. I can also ping them internally once I see those passing :)

**Comment by ratnopamc** [comment]
@GeneDer, Thanks for looking into this.
I raised https://github.com/ray-project/ray/issues/43018 for storing the output image.
And in https://github.com/ray-project/ray/pull/43046, I've referenced that image URL in the doc. I checked the failures; looks like premerge and doc build are failing due to "(serve/tutorials/aws-neuron-core-inference-stablediffusion: line  122) broken    https://raw.githubusercontent.com/ray-project/images/master/docs/serve/stable_diffusion_inferentia2_output.png - 404 Client Error: Not Found for url: https://raw.githubusercontent.com/ray-project/images/master/docs/serve/stable_diffusion_inferentia2_output.png". 
I am thinking we need to merge  https://github.com/ray-project/ray/issues/43018 first to get the jobs passed to have the image available.
Please let me know your thoughts.

**Comment by GeneDer** [comment]
Those links are confusing lol Got this merged https://github.com/ray-project/images/pull/18 But there are more issue with your PR tho, make sure to fix the rest

**Comment by ratnopamc** [comment]
@GeneDer thanks a lot for your review. All checks are passing now.

**Comment by GeneDer** [comment]
@ratnopamc just in case you missed the notification, can you address a few comments suggested by the docs team?

**Comment by ratnopamc** [comment]
@GeneDer, thanks. I resubmitted for review.
