### ISSUE TITLE
[Serve] When downscaling Serve prefers RUNNING nodes over STARTING ones

### ISSUE THREAD

**Issue by alexeykudinkin** [ray-project/ray#43034]
### What happened + What you expected to happen

In our Serve application, replicas `__init__` sequence could take anywhere from 1-10 min to boot up.

What we've noticed is that when downscaling Serve tends to sometime prefer killing `RUNNING` replicas over `STARTING` ones, even though i believe it's actually supposed to be preferring `STARTING` and `STOPPING` ones.

### Versions / Dependencies

2.9.1

### Reproduction script

Run Serve app withe deployment with multiple replicas, where each replica has slow `__init__`
Trigger upscaling, then immediately trigger downscaling
Serve seems to occasionally kill perfectly fine running replica causing a downtime even though there was starting replica that could have been axed instead

### Issue Severity

High: It blocks me from completing my task.

**Comment by edoakes** [comment]
Reopening until cherry picked
