### ISSUE TITLE
CI tests `test_output.py` for autoscaler v2 are flaky

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#43099]
Examples:
- Postmerge: https://buildkite.com/ray-project/postmerge/builds/2919
- Premerge: https://github.com/ray-project/ray/pull/43058
- Postmerge: https://buildkite.com/ray-project/postmerge/builds/2920

**Comment by aslonnie** [comment]
all min install tests are skipped here:
https://github.com/ray-project/ray/pull/43101

**Comment by anyscalesam** [comment]
@can-anyscale to check - is this still flaky?

**Comment by can-anyscale** [comment]
I don't think they are even running. Someone has to remove these conditions https://github.com/ray-project/ray/pull/43100/files from re-test.

**Comment by rickyyx** [comment]
They are fixed: 
<img width="1657" alt="image" src="https://github.com/ray-project/ray/assets/11676094/3322193d-01c5-48b4-8fe7-7907d01df878">

https://github.com/ray-project/ray/blob/master/python/ray/tests/test_output.py#L184
