### ISSUE TITLE
[Tune] Logging dir duplication

### ISSUE THREAD

**Issue by vakker** [ray-project/ray#43092]
### What happened + What you expected to happen

Running this:
```python
from ray import train, tune


def fcn(config):
    return 1


tuner = tune.Tuner(
    fcn,
    tune_config=tune.TuneConfig(num_samples=2),
    run_config=train.RunConfig(
        storage_path="/home/user/results", name="test_experiment"
    ),
)
results = tuner.fit()
```

This will produce the same logs in `/home/user/ray_results` and `/home/user/results`:
```
$ ls /home/user/results/test_experiment
basic-variant-state-2024-02-11_13-24-28.json  experiment_state-2024-02-11_13-24-28.json  fcn_e10e1_00000_0_2024-02-11_13-24-28  fcn_e10e1_00001_1_2024-02-11_13-24-28  tuner.pkl
$ ls /home/user/ray_results/test_experiment
basic-variant-state-2024-02-11_13-24-28.json  experiment_state-2024-02-11_13-24-28.json  fcn_e10e1_00000_0_2024-02-11_13-24-28  fcn_e10e1_00001_1_2024-02-11_13-24-28  tuner.pkl
```

I saw the syncing feature to sync logs and checkpoint, but I would expect to not have duplicate logs on a single machine. 
I saw the `TUNE_RESULT_DIR` env var, and also the `local_dir` option for `RunConfig`. So is this intended? If not, then what's the right way to specify the log dir? In previous versions there was a single log dir parameter. 

### Versions / Dependencies

Ray: 3.0.0.dev0 (updated today)
Python 3.10.7
OS: Ubuntu 20.04

### Reproduction script

See above.

### Issue Severity

~~Medium: It is a significant difficulty but I can work around it.~~
With the temp file issue this is HIGH, see comments below.

**Comment by jlshin** [comment]
I am also seeing a similar issue with using Ray 2.9. Notably, it looks like the default result directory is determined by one of three variables: https://github.com/ray-project/ray/blob/9641c72d80dc3fd24db62ba5ca9dcfa1bd4e7e3e/python/ray/train/constants.py#L13-L24

where `RAY_AIR_LOCAL_CACHE_DIR` is set by `local_dir`: https://github.com/ray-project/ray/blob/9641c72d80dc3fd24db62ba5ca9dcfa1bd4e7e3e/python/ray/tune/tune.py#L647-L650

Is this intentional? I thought `storage_path` was the replacement for `local_dir`

**Comment by vakker** [comment]
There's one more thing that I've just noticed, that Ray is logging also to `/tmp/ray` AND a lot of randomly generated `/tmp/tmp....` directories. I've just cleaned up 100GB of space from temp dirs of previous experiments.

**Comment by vakker** [comment]
Regarding the original issue, it seems that (roughly, I haven't thoroughly tested every possibility):
1. `storage_path` sets where the checkpoints are stored
2. `local_dir` sets where logs and some other stuff stored
3. `_get_defaults_results_dir` is called before `os.environ["RAY_AIR_LOCAL_CACHE_DIR"] = local_dir `, notably [here](https://github.com/ray-project/ray/blob/c1535c0bc5f94737cfd228736b781b1b872e10f0/python/ray/tune/impl/tuner_internal.py#L135), which will store the `tuner.pkl` file in the wrong place
4. if `local_dir` is not specified, then that duplicates the logs, but not the checkpoints

In any case, as a workaround to have the logs in the right place I have:
```python
logdir = ....

os.environ["TUNE_RESULT_DIR"] = logdir # should work with RAY_AIR_LOCAL_CACHE_DIR or TEST_TMPDIR too
tuner  = Tuner(
  ...
  storage_path = logdir,
  local_dir = logdir,
)

tuner.fit()
```

For example, leaving `local_dir` as `None` will result in the following in the CLI logs:
```
View detailed results here: /home/user/project-dir/PPO.2024-02-26.09:13:50
To visualize your results with TensorBoard, run: `tensorboard --logdir /home/user/ray_results/PPO.2024-02-26.09:13:50`
```

**Comment by Songloading** [comment]
I've also noticed the problem you mentioned. In my case, it seems that leaving ```name="test_experiment"``` out fixes the issue.

**Comment by woshiyyya** [comment]
cc @justinvyu

**Comment by justinvyu** [comment]
@vakker @jlshin @Songloading Thanks for raising this issue -- it's been a common source of confusion since the storage refactor in Ray 2.7.

Ray 2.10 has just been released with a few internal refactors that makes this configuration more straightforward: **you should only configure `RunConfig(storage_path)`.**

* Do not set `RAY_AIR_LOCAL_CACHE_DIR` or `TUNE_RESULT_DIR` env vars. These are no longer used.
* Do not set `RunConfig(local_dir)` -- this config will be going away fully in an upcoming release.
* Where will files be written?
    * `{storage_path}/{name}` -- `name` will be auto-generated if `RunConfig(name)` is not set.
    * We still keep a local "staging" copy of certain logfiles and metadata files on the driver.
        * The decision to keep this is so that Ray Train/Tune always goes through the same codepath for all possible `storage_path` configurations (local, s3, nfs, etc.).
        * This directory is now a subdirectory of the Ray temp session directory: `/tmp/ray/session_latest/artifacts/...`
        * This directory is also where Ray Core dumps logs. If `/tmp` is running out of space, then you can consider deleting `/tmp/ray/session_latest` after each training run. All files will already be uploaded to the `storage_path`.

Let me know if you're able to try this with the Ray 2.10 and if you have any remaining questions!

**Comment by justinvyu** [comment]
Question regarding this issue:

> Ray is logging also to /tmp/ray AND a lot of randomly generated /tmp/tmp.... directories.

What are the contents of these temp directories causing your tmp drive to run out of disk?

**Comment by vakker** [comment]
@justinvyu thanks, I'll test those and get back to you. I'm currently running some experiments, so I don't want to disturb things before that's all done.

Regarding the `/tmp/tmp*` dirs, I have these:
```sh
$ ls /tmp/tmp7rnwoi1i/
algorithm_state.pkl  policies  rllib_checkpoint.json
```

My hunch is that it's all happening [here](https://github.com/ray-project/ray/blob/fd0c148315c0f1afb97dee93ef635873e3a3eabf/rllib/algorithms/algorithm.py#L2260) and these are not moved or cleaned up later?

**Comment by justinvyu** [comment]
@vakker Thanks for clarifying, that's actually happening [here](https://github.com/ray-project/ray/blob/b75b4bdf24dd7a5ee83dbcc38114b4c5f33c1636/python/ray/tune/trainable/trainable.py#L439) for class trainables (which includes RLLib algorithms). Ray Tune creates a temporary directory for your checkpoint to be dumped to, but doesn't clean it up after it's uploaded to `storage_path`.

I'll put up a PR to fix this to clean up the temporary directories.
