### ISSUE TITLE
[tune] tune.function wrapper string representation is currently useless

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4311]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04/18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.4
- **Python version**: 3.6
- **Exact command to reproduce**: n/a

### Describe the problem
`tune.suggest.variant_generator.function` currently results in the following type of presentation in `params.json`: `"object_target_distance_reward_fn": "<ray.tune.suggest.variant_generator.function object at 0x7f5ced283978>"`. If I do a grid search over multiple different functions, there's currently no way to distinguish them in the results.

To fix this, `tune.function`s string representation should contain the string representation of the wrapped function.

**Comment by richardliaw** [comment]
Closed this via #4739.
