### ISSUE TITLE
[dashboard] py-spy flamegraph failures should have better docs

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#43129]
### What happened + What you expected to happen

In the dashboard one can trigger a flamegraph for a worker. This may not 100% work, e.g. 

1. If the process already exited
```
Failed to execute `['sudo', '-n', '/home/ray/anaconda3/bin/py-spy', 'dump', '-p', '2746']`.

=== stderr ===
Error: Failed to get process executable name. Check that the process is running.
Reason: No such file or directory (os error 2)
Reason: No such file or directory (os error 2)


=== stdout ===
```

2. if the job is sleeping
```
Failed to execute `['sudo', '-n', '/home/ray/anaconda3/bin/py-spy', 'record', '-o', PosixPath('/tmp/ray/session_2024-01-31_09-17-15_037017_341/logs/flamegraph_33695_cpu_profiling.svg'), '-p', '33695', '-d', '5', '-f', 'flamegraph']`.

=== stderr ===
[2024-01-31T22:37:27.932972718Z ERROR inferno::flamegraph] No stack counts found
Error: Failed to write flamegraph: I/O error: No stack counts found


=== stdout ===
py-spy> Sampling process 100 times a second for 5 seconds. Press Control-C to exit.
```

We know what's happening from py-spy, but a user may be clueless looking at them, e.g. when they click on a worker and got the "sleeping" result because it's waiting for a `ray.get`. 

We can do better by providing some Ray-provided words to instruct what's this error and what users should do. We can make it simple, that we don't parse the py-spy output and only give generic infos like:

```
- if you see "No such file or direction" your worker process may have been exited. 
- If you see "No stack counts found" your worker may be sleeping and did not have activity in the last 5s.
```

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

Low: It annoys or frustrates me.

**Comment by rynewang** [comment]
cc @anyscalesam

**Comment by scottsun94** [comment]
The suggestion makes sense.

**Comment by DarkTechPirate** [comment]
Why this isnt closed yet ?
