### ISSUE TITLE
Feature thought: exit code for `ray up` (and others?)

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#4314]
Example use case: in a data analysis pipeline, the first stage / job / task could be to start a Ray cluster with `ray up` & then continue or terminate the pipeline contingent on the success of this system call. Doesn't look like this is a thing yet in `scripts.py`(?)

**Comment by ericl** [comment]
Does 'ray submit' do what you want here?

**Comment by richardliaw** [comment]
I think `ray submit` should work here.
