### ISSUE TITLE
Release test xgboost_tune_small.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43155]
Release test **xgboost_tune_small.aws** failed. See https://buildkite.com/ray-project/release/builds/8408#018da6a4-c2a8-4382-b6c0-0c7d0a827ff2 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: eb8950b43f74b1ba2267d0b03b7aa1d1e88d6bee found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/869

**Comment by justinvyu** [comment]
@can-anyscale I specify the `xgboost_ray` / `lightgbm_ray` dependencies in `ml/core-requirements.txt`.

Is that enough for these packages to be included in the release test BYOD?

This test includes a post build script that reinstalls the package -- is this not necessary?

https://github.com/ray-project/ray/blob/c812e31cbd458553a819968ceadae5be34c85e27/release/ray_release/byod/byod_xgboost_test.sh#L7

**Comment by justinvyu** [comment]
Trying to remove it here: https://github.com/ray-project/ray/pull/43176

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/8839#018dc04c-5f6b-43c1-aa80-926374e8bd5f
