### ISSUE TITLE
[serve] Rename autoscaling-related API parameters

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#43180]
Making general naming improvements to autoscaling-related parameter names.

The following renaming will be rolled out in an incremental manner; both old and new versions of the names will be supported for one or more releases, before the old version is completely removed.

Autoscaling API changes:
* `max_concurrent_queries` -> `max_ongoing_requests`
* `target_num_ongoing_requests_per_replica` -> `target_ongoing_requests`
* `smoothing_factor` -> `scaling_factor`

**Comment by edoakes** [comment]
@zcin follow up for 2.11 to fully change
