### ISSUE TITLE
[Serve] Memory leak when using Ray Serve

### ISSUE THREAD

**Issue by geekboood** [ray-project/ray#43248]
### What happened + What you expected to happen

When using Ray Serve, I observe small amount of memory leak. And if I pass ObjectRefs from gateway deployment to another deployment, the Object store quickly filled up. 

memray flamegraph collected: 
[memray-flamegraph-3a39023baf736d1651d616cb01000000_mem_profile.zip](https://github.com/ray-project/ray/files/14318751/memray-flamegraph-3a39023baf736d1651d616cb01000000_mem_profile.zip)

ray memory output:
[ray_memory.txt](https://github.com/ray-project/ray/files/14318759/ray_memory.txt)

### Versions / Dependencies

Ray Version: 2.9.2
Python Version: 3.8.13

### Reproduction script

Just the pattern, not the real code I use. 
```
from starlette.requests import Request
from ray import serve

@serve.deployment()
class Dep1:
    def get_length(self, params: str):
        return len(params)
    
    def multiple_by_two(self, length: int):
        return length*2

@serve.deployment()
class Gateway:
    def __init__(self, dep1):
        self.dep1: Dep1 = dep1

    async def __call__(self, http_request: Request) -> str:
        raw_data = await http_request.body()
        length = self.dep1.get_length.remote(raw_data)
        length_ref = await length._to_object_ref()
        return await self.dep1.multiple_by_two.remote(length_ref)

if __name__ == "__main__":
    deployment = Gateway.bind(Dep1.bind())
    handle = serve.run(deployment)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
@geekboood Thanks for reporting the issue. Generally we are discouraging the use of advanced api such as `_to_object_ref`. In this case, `_to_object_ref` should only be used on short lived Ray Actor and/or Task. See doc: https://docs.ray.io/en/latest/serve/model_composition.html#advanced-convert-a-deploymentresponse-to-a-ray-objectref

Since you are calling methods on Serve deployments, I would suggest you to change the code to something like 
```
from starlette.requests import Request
from ray import serve

@serve.deployment()
class Dep1:
    def get_length(self, params: str):
        return len(params)
    
    def multiple_by_two(self, length: int):
        return length*2

@serve.deployment()
class Gateway:
    def __init__(self, dep1):
        self.dep1: Dep1 = dep1

    async def __call__(self, http_request: Request) -> str:
        raw_data = await http_request.body()
        length = self.dep1.get_length.remote(raw_data)
        # `length` being a `DeploymentResponse` can be passed into another 
        # `DeploymentHandle` directly to achieve model composition. 
        return await self.dep1.multiple_by_two.remote(length)

if __name__ == "__main__":
    deployment = Gateway.bind(Dep1.bind())
    handle = serve.run(deployment)

```

I would continue to look into possible fixes for the memory leak when using `_to_object_ref`. But please also let us know if this solves your usecase.

**Comment by geekboood** [comment]
I am afraid this won't solve my problem. 
My point is to share objects in object store to avoid repeated object serialization (which eat a lot of cpu). 
And if you manually put an object to the object store and pass the reference to a deployment, it also results in memory leak.
