### ISSUE TITLE
CI test linux://python/ray/data:test_streaming_integration is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43242]
CI test **linux://python/ray/data:test_streaming_integration** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/2991#018db45f-eb09-4ed0-8ebd-21a7ebab24d9
	- https://buildkite.com/ray-project/postmerge/builds/2990#018db44c-71d9-45c4-b4f5-c7ca8ae268f3
	- https://buildkite.com/ray-project/postmerge/builds/2989#018db43f-c6ff-4cf6-961c-8f422cd2b3b5
	- https://buildkite.com/ray-project/postmerge/builds/2988#018db42d-e282-4b0c-8c98-ea836a66d380
	- https://buildkite.com/ray-project/postmerge/builds/2987#018db403-67a0-442c-9fa8-0919a61dd716

DataCaseName-linux://python/ray/data:test_streaming_integration-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by c21** [comment]
@raulchen - can you help take a look? thanks.

**Comment by can-anyscale** [comment]
Revert PR to unblock: https://github.com/ray-project/ray/pull/43283

**Comment by can-anyscale** [comment]
Blame commit reverted

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3032#018dcc6a-3ffe-4964-8e1e-6384a67d71e1
