### ISSUE TITLE
Release test tune_scalability_xgboost_sweep.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43249]
Release test **tune_scalability_xgboost_sweep.aws** failed. See https://buildkite.com/ray-project/release/builds/8748#018db68a-a847-46e3-9c91-0e362f294bd3 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: eb8950b43f74b1ba2267d0b03b7aa1d1e88d6bee found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/883

**Comment by anyscalesam** [comment]
Samuel Chan
:spiral_calendar_pad:  [10:07 PM](https://anyscaleteam.slack.com/archives/D04TY7D0BLY/p1708322833395689)
hey justin - can you please take a look at https://github.com/orgs/anyscale/projects/76/views/1?pane=issue&itemId=53589070 and update the end date of when it will be fixed?


Justin Yu
:bulb:  [10:50 AM](https://anyscaleteam.slack.com/archives/D04TY7D0BLY/p1708455016281699)
Will be fixed today!
:ty:
1

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/9367#018dda7e-bc12-4f66-92bf-78f2463357aa
