### ISSUE TITLE
[rllib] Interpretation of Timestep

### ISSUE THREAD

**Issue by jincongho** [ray-project/ray#4328]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.4
- **Python version**: 3.6.4

How to interpret time step reported in RLlib training? For example:

`Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
IMPALA_PongNoFrameskip-v4_0:	RUNNING, [3 CPUs, 1 GPUs], [pid=12061], 374 s, 31 iter, 267000 ts, -20.6 rew`

For NoFrameskip Atari game, is the ts here refer to with frame skipped or without? I also noticed wrap_deepmind is being used on Atari (which implement MaxAndSkipEnv).

**Comment by ericl** [comment]
Here timesteps refers to transitions observed by the agent (so this would be after any frameskipping).
