### ISSUE TITLE
[Serve] Dynamic Request Batching not sending max_batch_size

### ISSUE THREAD

**Issue by shixianc** [ray-project/ray#43288]
### What happened + What you expected to happen

When using @serve.batch with max_batch_size of e.g. 280, it's not waiting for 280 requests before the batch_wait_timeout_s finishes. 
I tried even set the batch_wait_timeout_s to a super large value e.g. 5 seconds, still not working. 

### Versions / Dependencies

ray[serve]==2.9.2

### Reproduction script

In a deployment class for model (note: there's only 1 replica for this class):
```
@serve.batch(max_batch_size=256, batch_wait_timeout_s=5)
async def __call__(self, inputs: list[any]) -> list[any]:
    result = self.model.batch_predict(inputs)
    self.logger.info(f"length called: {len(inputs)}")
    return result
```

If I call the above method with below example scripts:
This is in the parent deployment class which serves http traffic.
```
inference_tasks = [self.model.remote(prompt) for prompt in prompts] # prompts with length 140 
inference_results = await asyncio.gather(*inference_tasks)
```

The logs show:
```
length called: 101
length called: 39
```

Does the dynamic batching depends on other parameters? like GPU memory?

### Issue Severity

organization productivity impaired

**Comment by GeneDer** [comment]
@shixianc thanks for reporting this issue! `max_concurrent_queries` (will be renamed as `max_ongoing_requests` after Ray 2.10 and up) seems to be bounding the requests. If you do something like the below, then you should start seeing "batching_issue.py:16 - length called: 256" in the logs.

```
from ray import serve
import logging
from starlette.requests import Request


@serve.deployment(max_concurrent_queries=256)
class Model:
    def __init__(self):
        self.logger = logging.getLogger("ray.serve")

    @serve.batch(max_batch_size=256, batch_wait_timeout_s=5)
    async def batch_predict(self, inputs: list[str]):
        self.logger.info(f"length called: {len(inputs)}")
        return [f"batch_predict({input})" for input in inputs]


@serve.deployment
class Inference:
    def __init__(self, _model):
        self.model = _model

    async def __call__(self, request: Request) -> list[any]:
        request_json = await request.json()
        prompts = request_json.get("prompts")
        responses = [self.model.batch_predict.remote(prompt) for prompt in prompts]
        return await asyncio.gather(*responses)


model = Model.bind()
inference = Inference.bind(model)
```
I will continue to look into a fix so user doesn't need to override unnecessary  `max_concurrent_queries`.

**Comment by GeneDer** [comment]
@shixianc Talked with the team about this. We will just log a warning to let the user know `max_concurrent_queries` should be reconfigured. Will not change the behavior for the code above.
