### ISSUE TITLE
need a command-line interface to query the state of the cluster

### ISSUE THREAD

**Issue by atumanov** [ray-project/ray#433]
We should really implement a simple command-line (not GUI) interface to query the current state of the cluster. Most importantly: all connected cluster worker nodes, their health, static (configured) and dynamic resource capacity, dispatch queue depth, waiting queue depth.

**Comment by robertnishihara** [comment]
Agreed. Something that let's us easily see how many nodes are in the cluster, how many CPUs/GPUs are on each node, etc. This information is pretty much all available in `ray.global_state.client_table()`, but it requires some parsing to extract the information.

**Comment by edoakes** [comment]
@zzyunzhi @pcmoritz can we implement this now using the same API that the dashboard uses?

**Comment by richardliaw** [comment]
This is now supported with `ray status`.
