### ISSUE TITLE
[Core]  `ray.get_gpu_ids` fails when CUDA_VISIBLE_DEVICES uses GPU UUIDs

### ISSUE THREAD

**Issue by joncarter1** [ray-project/ray#43314]
### What happened + What you expected to happen

`ray.get_gpu_ids` doesn't work when CUDA_VISIBLE_DEVICES is set using e.g. GPU UUIDs.
This is because the function tries to cast the IDs to integers:
https://github.com/ray-project/ray/blob/d77c96d855fb530d0aa62034645051c8afec28dd/python/ray/_private/worker.py#L995-L999
This affects downstream tooling, such as the PyTorch Distributed trainer, which rely on it:
https://github.com/ray-project/ray/blob/d77c96d855fb530d0aa62034645051c8afec28dd/python/ray/air/_internal/torch_utils.py#L24-L26

### Versions / Dependencies

Ray 2.9.2
Python 3.10.12
Ubuntu 22.04

### Reproduction script

Set visible GPUs using UUIDs:
```export CUDA_VISIBLE_DEVICES=$(nvidia-smi --query-gpu=uuid --format=csv | tail -n 1)```
then:
```python
import ray

@ray.remote(num_gpus=1)
def func():
    return ray.get_gpu_ids()

if __name__ == "__main__":
    ray.get(func.remote())
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by joncarter1** [comment]
Looks like this was changed in 2.8.0+ with #40286 FYI @jjyao

**Comment by jjyao** [comment]
Thanks @joncarter1 for reporting this. I'll fix it in the next release.
