### ISSUE TITLE
CI test windows://python/ray/tests:test_autoscaler is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43311]
CI test **windows://python/ray/tests:test_autoscaler** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3026#018dcb54-7172-49ef-9aeb-92f0947a8a96
	- https://buildkite.com/ray-project/postmerge/builds/3025#018dcafb-99ec-42da-b789-7a7eaef6f464
	- https://buildkite.com/ray-project/postmerge/builds/3024#018dca49-6405-451b-880a-504645ea8eb4
	- https://buildkite.com/ray-project/postmerge/builds/3023#018dca03-15f4-4e1f-a9dc-0193889f76db
	- https://buildkite.com/ray-project/postmerge/builds/3022#018dc9a1-018b-47d6-9f94-4fe315e81733

DataCaseName-windows://python/ray/tests:test_autoscaler-END
Managed by OSS Test Policy

**Comment by rickyyx** [comment]
This seems to never run on postmerge before?

**Comment by can-anyscale** [comment]
@rickyyx yes, you removed the 'no_windows' tag from the bazel config https://github.com/ray-project/ray/commit/a76fca6f1de7c5bb564c578787303b01a0c7d2d8; I think this test should not run on windows

**Comment by can-anyscale** [comment]
not a release blocker, the test should not run

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by rickyyx** [comment]
oh, might be a flaky dashboard issue? 
<img width="1145" alt="image" src="https://github.com/ray-project/ray/assets/11676094/a913febc-7065-4c02-859f-d056285c7130">

**Comment by can-anyscale** [comment]
ah yesss, it runs in the 'flaky test' jobs still in postmerge and not running in premerge (https://buildkite.com/ray-project/postmerge/builds/3106#018de410-2b74-48c8-8352-0c9440c3e978). Did we add the 'no_windows' tag back to the test bazel rule? If we need that to skip it completely.

**Comment by rickyyx** [comment]
> ah yesss, it runs in the 'flaky test' jobs still in postmerge and not running in premerge (https://buildkite.com/ray-project/postmerge/builds/3106#018de410-2b74-48c8-8352-0c9440c3e978). Did we add the 'no_windows' tag back to the test bazel rule? If we need that to skip it completely.

i think i did it here - or at least i thought i did it here https://github.com/ray-project/ray/commit/a10011db7a66ee70896f4dacc07b07d277fd45a4

**Comment by can-anyscale** [comment]
ahh yess this is my bad, i'll put up a PR to fix shortly

**Comment by can-anyscale** [comment]
https://github.com/ray-project/ray/pull/43440
