### ISSUE TITLE
[rllib] sampler.py get_data() timeout exception

### ISSUE THREAD

**Issue by flying-mojo** [ray-project/ray#4335]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.3 - 0.7.0.dev
- **Python version**: 3.5
- **Exact command to reproduce**: N/A run custom python script

### Describe the problem
Im using a custom env. Will also try to repro the problem using standard gym env.
When using IMPALA:
after about 1h of training (~1million steps) an exception is being raised from sampler.py:
File "/data/anaconda/envs/py35/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 159, in get_data
    rollout = self.queue.get(timeout=600.0)
  File "/data/anaconda/envs/py35/lib/python3.5/queue.py", line 172, in get
    raise Empty
queue.Empty

when i remove timeout=600.0 (i.e. set timeout to be infinite) than training of my experiment continues.

However when i run same env using PPO (continuous action space) then the same exception happens, but if i set timeout to be infinite than my experiment locks - all tasks just wait (output from ray stack - all threads wait like this):
Thread 0x7FD91DDBB700 (idle)
         wait (threading.py:293)
         put (queue.py:133)
         _run (ray/rllib/evaluation/sampler.py:157)
         run (ray/rllib/evaluation/sampler.py:130)
         _bootstrap_inner (threading.py:914)
         _bootstrap (threading.py:882)

My environments keep on running (i.e. they have not crashed or anything like this).

Another member of my team has experience the same locking in a completely different environment.

I have exchanged emails with Eric Liang on the support dev forum about it. Just logging an issue here for the record.

I will try to repro it using a non-custom gym environment.

It seems that the locking is related to the object store size/redis mem size (i.e. increasing both has made the time until a lock happens longer)

**Comment by ericl** [comment]
Does this also happen if sample_async=False? We usually never test with the async sampler so I wouldn't be surprised if there is some bug with it.

**Comment by flying-mojo** [comment]
Hi Eric!
I have not tried to run with sample_async=False, i will try and let you
know.
Jarek

**Comment by ericl** [comment]
Great. By the way, there is a way to emulate multiple nodes when testing on a single machine by passing `--ray-num-nodes` to `rllib train` -- that might help with coming up with a reproduction case.
