### ISSUE TITLE
Make Ray Dashboard serve page show both applications and deployments at the top level

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#43350]

**Comment by alanwguo** [comment]
The issue right now is that if an application fails in a way where a deployment does not start up, the status of that update is hard to find. IT can be found in logs, but it would be much much better to see the application metadata in the main table.

**Comment by alanwguo** [comment]
I think we can use the same columns and add an "Expand collapse" button in front of each application to show the deployments in that application.

For the existing columns, each of them make sense for either application or deployment. Route_prefix we can choose to make that an application level concept only.

**Comment by architkulkarni** [comment]
TODO: think about how to handle the "filter" area at the top
