### ISSUE TITLE
[Data] dataset_shuffle_sort_1tb failing on nightly tests

### ISSUE THREAD

**Issue by khluu** [ray-project/ray#43396]
### What happened + What you expected to happen

[dataset_shuffle_sort_1tb](https://buildkite.com/ray-project/release/builds/9287#018dd51e-2b37-446a-a2c0-770085973abd) failed on nightly . This test passed 3 days ago

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by khluu** [comment]
Data team is deprioritizing the fix for this until after branch cut: https://anyscaleteam.slack.com/archives/C01DVKB5SHE/p1708724977618549?thread_ts=1708718038.180029&cid=C01DVKB5SHE

**Comment by bveeramani** [comment]
@khluu looks like this test has been passing for the past several nightly runs. Should we close this Issue?

**Comment by khluu** [comment]
@bveeramani  This test starts failing again on release branch: https://buildkite.com/ray-project/release/builds/10874#018e222b-411d-4478-b4e6-be92f30bb07b

**Comment by bveeramani** [comment]
Test passes after https://github.com/ray-project/ray/commit/0664ec87612b33d89185423f641b5e4829ea0649. Shall we close? https://buildkite.com/ray-project/release/builds/11195#_
