### ISSUE TITLE
Improve usability of long running tests.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4342]
Some things that should be improved.
- Instead of using tmux, we should probably log to a file. Since it's difficult to scroll in tmux, error messages are often lost. This could also allow us to modify `check_workloads.sh --logs` to take a specific workload name and see the whole log file.
- When we run `check_workloads.sh --load`, it would be nice to see how long the test ran before it failed, e.g., how long until the last line was printed to its log file.

**Comment by ericl** [comment]
Btw, you can enable xterm scrolling in tmux with this conf (no idea why it isn't on by default): https://superuser.com/questions/310251/use-terminal-scrollbar-with-tmux?lq=1

**Comment by richardliaw** [comment]
Should be fixed now.
