### ISSUE TITLE
If a node dies causing a task to become infeasible, it can cause other raylets to die.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4344]
I've seen this check fail when running the `many_tasks.py` long running stress test.

https://github.com/ray-project/ray/blob/490d896f41c0d964fc7199a160d139360617bf0b/src/ray/raylet/node_manager.cc#L466-L470

I think the issue is that the first node dies for some unrelated reason causing a task to become infeasible. The second node then fails that `RAY_CHECK` because it wasn't expecting the task to be infeasible.

**Comment by richardliaw** [comment]
This is stale; should be fixed now.
