### ISSUE TITLE
Linux Wheels missing files from ray.experimental.serve

### ISSUE THREAD

**Issue by RehanSD** [ray-project/ray#4350]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: Ray installed using python binaries
- **Ray version**: 0.7.1dev
- **Python version**: 3.6
- **Exact command to reproduce**: pip install -U 
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.7.0.dev1-cp36-cp36m-manylinux1_x86_64.whl

### Describe the problem

I was trying to benchmark Simon's code on an EC2 instance, but after installing ray using the Linux Wheel for Python 3.6, the package was missing the examples, utils, and test folders from the ray.experimental.serve package.

**Comment by richardliaw** [comment]
Fixed.
