### ISSUE TITLE
[Doc] UI's background color is too intrusive 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#43518]
### Description

As noted in the title, the background color is too much and affects my reading.

<img width="1715" alt="Screenshot 2024-02-28 at 2 29 36 PM" src="https://github.com/ray-project/ray/assets/9677264/2dee37a2-7465-4da5-9d3e-61a9feaebe1f">

**Comment by scottsun94** [comment]
cc: @simran-2797

**Comment by simran-2797** [comment]
@peytondmurray 
Thanks for helping out with this. 
I just updated the designs here to make the gradient lighter. - https://www.figma.com/file/DjtgroLeO6BQSD6Si5dedw/Ray-docs-design-system?type=design&node-id=20%3A2017&mode=design&t=2GKZcgcLjNF6BrO8-1

**Comment by peytondmurray** [comment]
@simran-2797 I don't even see the gradient anymore in the light theme mockup. Is it even there? In the dark theme it looks like it's faintly there.
