### ISSUE TITLE
IMPALA for non-image inputs

### ISSUE THREAD

**Issue by gowthamnatarajan** [ray-project/ray#4352]
I see the IMPALA implementation has a conv net in it. I am interested in using IMPALA for non-image inputs. Can I use a custom network architecture instead?

**Comment by ericl** [comment]
Yes -- RLlib will choose a fully connected or conv net depending on your observation space, but you can also specify your own custom network: https://ray.readthedocs.io/en/latest/rllib-models.html

**Comment by gowthamnatarajan** [comment]
Thanks. 
This is a more generic question, but would appreciate some help. Have RL algorithms been used for variable length output using RNNs? My custor network would have a regular fully connected input and an RNN (of varying length) as an output.

**Comment by ericl** [comment]
Could you provide a more detailed example here -- is it that for a step of your agent you would use an RNN to generate some variable-length output to send to the environment?

**Comment by gowthamnatarajan** [comment]
The action space is not a single action as it is in most applications of RL. In my case, the action involves a set of steps. So, given a state as input, the output would be 2 to 6 steps. Then we can get the reward and continue the cycle.

Since I cannot the the real problem I am working on, I am giving a made up example:

The output (actions) could be any of the following:

- Don't do anything
- Buy 10 quantity of X
- Buy 10 quantity of X and Sell 5 quantity of Y
- Buy 13 quantity X, Sell 20 quantity of Z and Sell 3 quantity of W

This problem can be seen as having many items (A to Z) and they can be bought or sold and the quantity could be anything.

**Comment by ericl** [comment]
I see, in this case, I think you could represent the action space as a Tuple of individual action possibilities i.e., `Tuple([Box(...)] * MAX_OUTPUTS)` where each Box space is either the no-op action or a single buy/sell action. Internally in the model, you could have a RNN or RNN-like structure that generates outputs up to MAX_OUTPUTS and returns it as the tuple action. I don't know of any existing examples of this being done though.

Or each actions could be chosen "separately" without such a RNN to be noop/buy/sell (in which case the default fcnet would work).

There are some other ways to handling variable-length action spaces here: https://ray.readthedocs.io/en/latest/rllib-models.html#variable-length-parametric-action-spaces

**Comment by gowthamnatarajan** [comment]
The input to this is also a variable number of items. So the number of input items is not known. But the max number is knows. Do you think its better to use an RNN as input or use a regular NN and use padding with zeros in case the number of items is less than max?
