### ISSUE TITLE
[Data]  Avro Support for Ray Data

### ISSUE THREAD

**Issue by hebiao064** [ray-project/ray#43548]
### Description

For better integration with existing data ecosystem, is it possible to support IO for avro data storage format?

### Use case

We have a lot of existing raw feature datasets stored as Avro, and it would be nice if Ray dataset can support this format.

_No response_

**Comment by hebiao064** [comment]
Currently local testing is failing due to this:
```bash
Python 3.9.6 (default, Aug 11 2023, 19:44:50) 
[Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhe/oss/ray/python/ray/__init__.py", line 84, in <module>
    import ray._raylet  # noqa: E402
ModuleNotFoundError: No module named 'ray._raylet'
```

Will try clean up setup and do it again per suggestion from: https://github.com/ray-project/ray/issues/4727

**Comment by hebiao064** [comment]
@bveeramani Hi Balaji, thanks a lot for your help on providing review, guidance and contribute this issue, really appreciate it!

Would you please share the ETA when this PR could be used in next ray version?

**Comment by bveeramani** [comment]
Should be available soon! 

Tentatiely:
> Weekly release week of Apr 1, 2024 - Ray 2.11
> Weekly release week of Apr 8, 2024 - Ray 2.12
