### ISSUE TITLE
CI test linux://python/ray/train:deepspeed_torch_trainer is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43562]
CI test **linux://python/ray/train:deepspeed_torch_trainer** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3170#018df222-062d-4b31-b631-bec557c1ffc9
	- https://buildkite.com/ray-project/postmerge/builds/3169#018df221-4dd1-47bc-b404-884f4b3f36c4
	- https://buildkite.com/ray-project/postmerge/builds/3168#018df214-2a27-470e-a563-31a17b8dce18
	- https://buildkite.com/ray-project/postmerge/builds/3167#018df208-1ee8-44d7-877b-afef2a2c0251
	- https://buildkite.com/ray-project/postmerge/builds/3166#018df206-cc9e-4f50-8d45-3cb31de5cf5a

DataCaseName-linux://python/ray/train:deepspeed_torch_trainer-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3191#018df65e-bf97-49f6-ad68-dd6e449719e0

**Comment by woshiyyya** [comment]
From the error message, this appears to be caused by yesterday's huggingface_hub outage.

```
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like hf-internal-testing/tiny-random-gpt2 is not the path to a directory containing a config.json file.
--
  | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```
