### ISSUE TITLE
Current master ray wheel doesn't work

### ISSUE THREAD

**Issue by nikola-j** [ray-project/ray#4356]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: ray-0.7.0.dev1-cp36-cp36m-manylinux1_x86_64.whl
- **Python version**: 3.6.7
- **Exact command to reproduce**:
```bash
virtualenv -p python3 venv
source venv/bin/activate
pip install https://s3-us-west-2.amazonaws.com/ray-wheels/87bfa1cf82a53fc152cedb9c8bec3a7c73a56f5d/ray-0.7.0.dev1-cp36-cp36m-manylinux1_x86_64.whl
pip install gym tensorflow psutil
python -c 'from ray.rllib.models import ModelCatalog'
```

### Describe the problem
If you build the current master wheel from docker or download one built by travis from S3 ray segfaults.

### Source code / logs
```
Segmentation fault (core dumped)
```

**Comment by bjg2** [comment]
I experience the same issue, wheels built as described [here](https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md) are segfaulting when installed.

**Comment by pcmoritz** [comment]
Thanks for reporting this! I can reproduce the segfault and also verify
that it is fixed in https://github.com/ray-project/ray/pull/4281. Wheels
after that should work!

@bjg2:
The instructions in
https://github.com/ray-project/ray/blob/master/python/README-building-wheels.md
are outdated now, I'll update them.

**Comment by nikola-j** [comment]
Awesome, thanks guys!

**Comment by bjg2** [comment]
Thanks from me as well! :)

**Comment by robertnishihara** [comment]
@pcmoritz any idea what the prior issue was?

**Comment by pcmoritz** [comment]
For https://github.com/ray-project/ray/pull/4127 the previous fixes weren't sufficient any more. Fortunately the crashes are solved differently now.
