### ISSUE TITLE
[docs] Dark mode > search bar has low visibility

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#43566]
### Description

On master, the search bar outline and magnifying glass don't have enough contrast in dark mode.
<img width="826" alt="Screenshot 2024-02-29 at 10 52 46 AM" src="https://github.com/ray-project/ray/assets/122562471/aa4adc3b-81b8-4fc0-9820-6f474d9be9da">

### Link

[master branch](https://docs.ray.io/en/master/ray-core/walkthrough.html)

**Comment by simran-2797** [comment]
@peytondmurray Does the py-data spinx theme have a default search bar that we can use here? I think their default one should be good. Lmk if not, I can try another design.

**Comment by peytondmurray** [comment]
Yes: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/search.html

**Comment by simran-2797** [comment]
Okay. Can we try using this?
