### ISSUE TITLE
rllib using all available memory on server and crashing

### ISSUE THREAD

**Issue by natashamjaques** [ray-project/ray#4357]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.4
- **Python version**: 3.6.7
- **Exact command to reproduce**:
ray.init(num_cpus=FLAGS.num_cpus, object_store_memory=int(2e10), redis_max_memory=int(1e10))

Exact launching script here: https://github.com/eugenevinitsky/sequential_social_dilemma_games/blob/visible_actions/run_scripts/train_baseline_a3c.py

### Describe the problem
I'm trying to run a basic multi-agent A3C baseline using rllib on servers with ~250G of RAM. I'm running 2 copies of the code for each of 2 different environments. Unfortunately, even though I have manually capped the size of the object_store_memory and redis_max_memory in ray.init, it keeps eating all available memory (Ray object store gets to be 80G for 2 20G processes). 

The problem seems to be exacerbated by running the code more than once. Any chance the two processes are interfering with each other?

### Source code / logs
ray.exceptions.RayTaskError: ray_worker (pid=15727, host=matlaber3)
ray.exceptions.RayTaskError: ray_worker (pid=15727, host=matlaber3)
  File "/mas/u/jaquesn/venvs/empathy/lib/python3.6/site-packages/ray/memory_monitor.py", line 77, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node matlaber3 is used (191.44 / 201.41 GB). The top 5 memory consumers are:

PID     MEM     COMMAND
31571   22.95GB ray_DQNAgent:stop()
15728   22.51GB /mas/u/jaquesn/venvs/empathy/bin/python /mas/u/jaquesn/venvs/empathy/lib/python3.6/site-packages/ray
17100   21.15GB /mas/u/jaquesn/venvs/empathy/bin/python /mas/u/jaquesn/venvs/empathy/lib/python3.6/site-packages/ray
15706   21.15GB /mas/u/jaquesn/venvs/empathy/bin/python /mas/u/jaquesn/venvs/empathy/lib/python3.6/site-packages/ray
15714   21.15GB /mas/u/jaquesn/venvs/empathy/bin/python /mas/u/jaquesn/venvs/empathy/lib/python3.6/site-packages/ray

In addition, ~81.54 GB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`.

**Comment by robertnishihara** [comment]
Hey @natashamjaques, thanks for reporting this! The fact that the object store is using more than the specified amount is surprising.

If you check `/tmp/ray/session.../logs/plasma_store.err`, it should have a line at the top saying something like **Allowing the Plasma store to use up to 5.15396GB of memory.** What is that number in your case? There should also be a bunch of messages saying things like **I0313 14:33:23.732750 167351744 eviction_policy.cc:81] There is not enough space to create this object, so evicting 1 objects to free up 80000704 bytes. The number of bytes in use (before this eviction) is 80000704.**

If you just run a standalone script like

```python
import numpy as np
import ray
ray.init(object_store_memory=10**8)
x = np.zeros(10**7)
for _ in range(100):
    ray.put(x)
```

can you try that and share the resulting `plasma_store.err` log?

**Comment by ericl** [comment]
Is this still reproducible?

**Comment by natashamjaques** [comment]
Thanks for your help. I checked the session logs and it does have the line about allocating 20GB, and seems to be maintaining that amount:

$ more /tmp/ray/session_2019-03-13_14-40-27_13035/logs/plasma_store.err
I0313 14:40:27.623787 13180 store.cc:989] Allowing the Plasma store to use up to 20GB of memory.
I0313 14:40:27.624085 13180 store.cc:1016] Starting object store with directory /dev/shm and huge page support disabled
I0313 14:48:49.059474 13180 eviction_policy.cc:81] There is not enough space to create this object, so evicting 3272 objects to free up 4000517376 bytes. The number of bytes in use (before this eviction) 
is 19999584960.
I0313 14:49:15.452508 13180 eviction_policy.cc:81] There is not enough space to create this object, so evicting 2891 objects to free up 4000160704 bytes. The number of bytes in use (before this eviction) 
is 19997244864.

By the end of the file it goes straight from this to disconnecting with no other explanation of why it crashed:
I0317 19:30:33.593118 13180 eviction_policy.cc:81] There is not enough space to create this object, so evicting 3270 objects to free up 4000097344 bytes. The number of bytes in use (before this eviction) is 19999712512.
I0317 19:31:47.835347 13180 eviction_policy.cc:81] There is not enough space to create this object, so evicting 3270 objects to free up 4000091328 bytes. The number of bytes in use (before this eviction) is 19999696192.
I0317 19:32:34.913252 13180 store.cc:594] Disconnecting client on fd 27
I0317 19:32:35.221572 13180 store.cc:594] Disconnecting client on fd 31
I0317 19:32:35.234365 13180 store.cc:594] Disconnecting client on fd 11
I0317 19:32:36.149093 13180 store.cc:594] Disconnecting client on fd 38
I0317 19:32:36.591897 13180 store.cc:594] Disconnecting client on fd 21
I0317 19:32:36.835204 13180 store.cc:594] Disconnecting client on fd 43
I0317 19:32:36.895550 13180 store.cc:594] Disconnecting client on fd 18
I0317 19:32:37.011976 13180 store.cc:594] Disconnecting client on fd 16 ... etc

When I run the simple script, it looks like:
$ tail --lines=1000 /tmp/ray/session_2019-03-20_15-19-19_22390/logs/plasma_store.err
I0320 15:19:20.255589 23251 store.cc:989] Allowing the Plasma store to use up to 0.1GB of memory.
I0320 15:19:20.255806 23251 store.cc:1016] Starting object store with directory /dev/shm and huge page support disabled
I0320 15:19:38.165426 23251 eviction_policy.cc:81] There is not enough space to create this object, so evicting 1 objects to free up 80000704 bytes. The number of bytes in use (before this eviction) is 80000704.
I0320 15:19:38.171571 23251 eviction_policy.cc:81] There is not enough space to create this object, so evicting 1 objects to free up 80000704 bytes. The number of bytes in use (before this eviction) is 80000704.
....
I0320 15:19:38.765137 23251 eviction_policy.cc:81] There is not enough space to create this object, so evicting 1 objects to free up 80000704 bytes. The number of bytes in use (before this eviction) is 80000704.
I0320 15:19:43.206396 23251 store.cc:594] Disconnecting client on fd 7
I0320 15:19:43.238498 23251 store.cc:594] Disconnecting client on fd 10
I0320 15:19:43.238538 23251 store.cc:594] Disconnecting client on fd 8
I0320 15:19:43.238963 23251 store.cc:594] Disconnecting client on fd 11

So this all looks normal. But I do keep seeing out of memory errors reporting Ray is using a lot of memory. Any other suggestions?

**Comment by ericl** [comment]
`81.54 GB of shared memory is currently being used by the Ray object store`

I wonder if somehow there are old object store processes on the machine. Running `ray stop` or `pkill plasma` might help clean these up.

Also, is it possible to reproduce this with a normal gym env? I wonder if it could be some setting like a very large replay buffer for DQN (not sure about A3C).

**Comment by natashamjaques** [comment]
Oh, that's possible. Some of the other jobs died in weird ways, so maybe their object store processes didn't get de-allocated. I'll try `ray stop` and `pkill plasma`, thanks!

**Comment by robertnishihara** [comment]
@natashamjaques let us know if that turned out to be the problem!

**Comment by GoingMyWay** [comment]
This is a issue in ray 0.8.2 with offline data via setting the input config with a JSON dataset path.
