### ISSUE TITLE
[rllib] Add option to ignore crashed workers in RLlib

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#4358]
### Describe the problem
Currently RLlib will abort a trial if any worker fails. We should add an option to ignore crashed workers instead and continue training.

Also, we should bump timeouts to handle slow-initializing envs.

**Comment by SebastianBo1995** [comment]
Would it be possible to implement an option to define what rllib should do if the worker dies? So like it is implemented now to just ignore the worker or to try to initialise another environment. 

I unfortunately encounter some problems with couling rllib with a simulation environment, where the simulation diverges and the worker dies.

**Comment by jmugan** [comment]
I have the problem too in RLlib. One of the running training environments segfaults randomly with low probability and the whole thing comes down. Would be good to have a flag to say if a worker crashes start another one.

**Comment by jmugan** [comment]
Dang. "ignore_worker_failures" doesn't seem to help.
