### ISSUE TITLE
[rllib] off-policy estimator checking action_prob from wrong places.

### ISSUE THREAD

**Issue by tengteng** [ray-project/ray#4361]
I followed example code from [saving_experiences.py](https://github.com/ray-project/ray/blob/master/python/ray/rllib/examples/saving_experiences.py) trying to generate some offline experience for off-policy CPE but found this issue:

Later code in off_policy_estimator.py actually checks inconsistent places from for `action_prob`:
[L70](https://github.com/ray-project/ray/blob/master/python/ray/rllib/offline/off_policy_estimator.py#L70) and [L91](https://github.com/ray-project/ray/blob/master/python/ray/rllib/offline/off_policy_estimator.py#L91)

And even I put `action_prob` in both places it still hits an exception says it failed to find `action_prob` in info since it's an array of dicts (each dict contains `action_prob`).

**Comment by ericl** [comment]
I think this is working as intended:
- the action_prob for the offline data is read from batch["action_prob"]
- the action_prob for the current policy is read from the info return of policy.compute_actions()

An error can occur if either the action prob is missing from the batch, or if the policy does not has meaningful action prob (e.g., DQN without soft_q enabled).

**Comment by tengteng** [comment]
Sounds good. A better error message is definitely helpful.
