### ISSUE TITLE
[SERVE] Ray crashes on small load in fastapi

### ISSUE THREAD

**Issue by dioptre** [ray-project/ray#43625]
### What happened + What you expected to happen

Hi Y'all, We're doing some super basic load testing using fastapi and serve. We hit a /ping route which just returns a 200 (succcessfully) with a "pong" and receive cancellations for each request (which seems super off considering the responses return ok - https://docs.ray.io/en/latest/serve/http-guide.html#request-cancellation) - this leads to log saturation and the entire system crashes. This is most worrying. Wonder if anyone else has seen this behavior? Pretty easy to replicate, just create an async response and hit with a bunch (2000) of aiohttp.ClientSession() and watch ray crash.

```
INFO 2024-03-01 15:39:33,818 proxy 10.0.13.12 6a58555d-41e3-471e-8131-2c251c33b699 /api/v1/ping default proxy.py:1004 - Client for request 6a58555d-41e3-471e-8131-2c251c33b699 disconnected, cancelling request.
...
direct_actor_task_submitter.cc:36: Set max pending calls to -1 for actor 0daad9deb9b4210f86d1ec85010000006390

core_worker.cc:3680: Cancel an actor task 105daa52f5df1538f70ebb36eaf24914f8b9321c01000000 for an actor f70ebb36eaf24914f8b9321c010000006391
...
logging.cc:361: *** SIGSEGV received at time=1709306398 on cpu 21 ***

logging.cc:361: PC: @     0x7fb0d5c040cd  (unknown)  __pyx_f_3ray_7_raylet_report_streaming_generator_output()

logging.cc:361:     @     0x7fb0d7442520       3968  (unknown)

logging.cc:361:     @     0x7fb0d5b88c94         80  __pyx_pw_11cfunc_dot_to_py_74__Pyx_CFunc_object____object____StreamingGeneratorExecutionContext___to_py_1wrap()

logging.cc:361:     @     0x55be6868a42b  (unknown)  PyObject_Call

logging.cc:361:     @     0x7fb0d6aa1940  (unknown)  (unknown)
```

### Versions / Dependencies

Ray 2.8.0

### Client
```
import asyncio
import aiohttp

url = 'https://localhost/ping'
num = 4096

async def run(session):
    resp = await session.get(url)
    if resp.status != 200:
        print(resp.status)
        print(resp.headers)

async def main():
    async with aiohttp.ClientSession() as session:
        runs = []
        for i in range(num):
            runs.append(run(session))
        await asyncio.gather(*runs, return_exceptions=True)

if __name__ == "__main__":
    asyncio.run(main())
```
### Server
```
@router.get("/ping")
async def read_protected(request: Request):
    return {"msg": "pong"}
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
Hi @dioptre I tested with your code running using Ray Serve
```
from ray import serve
from starlette.requests import Request


@serve.deployment
async def read_protected(request: Request):
    return {"msg": "pong"}

app = read_protected.bind()
```
To start serve with your application can run `serve run deployment:app` 

Using exactly your client code runs without issue. Can you give it a try and let us know if this works for you??

**Comment by dioptre** [comment]
Ah we found out the issue, we had an override on the starlette exception handler and this was the culprit.

Thanks
