### ISSUE TITLE
CI test darwin://python/ray/tests:test_actor_retry is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43621]
CI test **darwin://python/ray/tests:test_actor_retry** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3208#018dfac9-4699-4130-89a6-ab05253209f6
	- https://buildkite.com/ray-project/postmerge/builds/3210#018df7b6-0e99-444f-a9cb-9ab8092ec5ef
	- https://buildkite.com/ray-project/postmerge/builds/3209#018df7b6-57a0-41b4-8d00-2c4a3bc1ac0f
	- https://buildkite.com/ray-project/postmerge/builds/3205#018dfa53-ccc3-4ec7-83a4-a4a02d2443ca
	- https://buildkite.com/ray-project/postmerge/builds/3206#018dfa48-5c3c-41be-9808-1d50ff4c7dcd

DataCaseName-darwin://python/ray/tests:test_actor_retry-END
Managed by OSS Test Policy

**Comment by anyscalesam** [comment]
@can-anyscale; confirmed not release-blocker for ray210 but need-to-fix for ray weekly releases

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3297#018e107a-4ae6-4823-aaf7-15ac5dbfa949
