### ISSUE TITLE
[tune] PyTorch: remove dependency of TensorFlow

### ISSUE THREAD

**Issue by zuoxingdong** [ray-project/ray#4365]
It will be very convenient to remove dependency of TensorFlow when using `ray.tune` for PyTorch.

**Comment by ericl** [comment]
I think we only have a soft dependency, so it's only imported if already installed. Is this not the case?

**Comment by richardliaw** [comment]
I'll close this for now as I think it's not actually a hard dependency; would be good to reopen if this is actually an issue.
