### ISSUE TITLE
CI test linux://python/ray/serve/tests:test_autoscaling_policy_with_queue_len_cache_disabled is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43653]
CI test **linux://python/ray/serve/tests:test_autoscaling_policy_with_queue_len_cache_disabled** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3237#018dfed4-0386-4b9a-97e3-cb6c8acdb251
	- https://buildkite.com/ray-project/postmerge/builds/3212#018df9ad-c5f5-4e0b-8352-5e0e8872b612
	- https://buildkite.com/ray-project/postmerge/builds/3208#018df753-0f7f-41cd-9e5e-331b151c6ed4
	- https://buildkite.com/ray-project/postmerge/builds/3193#018df676-8882-4341-8a62-b93b7de7790a
	- https://buildkite.com/ray-project/postmerge/builds/3183#018df59a-1fa1-428a-a4e5-4e71a29878d6

DataCaseName-linux://python/ray/serve/tests:test_autoscaling_policy_with_queue_len_cache_disabled-END
Managed by OSS Test Policy

**Comment by anyscalesam** [comment]
@GeneDer @shrekris-anyscale - failing release test - can y'all please take a look and make a decision on whether this should be a ray 2.10 release blocker?

**Comment by GeneDer** [comment]
@anyscalesam Yes, I think it should be a release blocker. I will take a look today

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3294#018e1044-5c86-4520-ad73-e2159b563f05

**Comment by anyscalesam** [comment]
@GeneDer did we root cause why it failed or is it just flaky in general?
