### ISSUE TITLE
[Data] Example in docstring for `Dataset.aggregate()`

### ISSUE THREAD

**Issue by kawinsw** [ray-project/ray#43660]
### Description

Not sure if I'm missing something - should the `merge` function below be `lambda a1, a2: a1 * a2` instead?

https://github.com/ray-project/ray/blob/457d6e930e2d87354c9462b150be26a592508ea1/python/ray/data/dataset.py#L1889-L1905

I'm assuming the intent here is to find the product of the `"number"` column in `ds`.

If so, the output would be `{'prod': 362880}` (product of the integers 1 thru 9).

### Link

https://docs.ray.io/en/master/data/api/doc/ray.data.Dataset.aggregate.html#ray.data.Dataset.aggregate

**Comment by bveeramani** [comment]
Nice catch! Would you want to open a PR to fix?

**Comment by kawinsw** [comment]
Haha, it's been a while. I believe this has since been fixed in #44634 (in fact, it seems like you fixed it)

**Comment by bveeramani** [comment]
Ah, haha. Forgot about that.

**Comment by kawinsw** [comment]
Thanks for the fix!
