### ISSUE TITLE
[ray cluster] prom_metrics_service_discovery.json not found

### ISSUE THREAD

**Issue by 23ewrdtf** [ray-project/ray#43668]
### What happened + What you expected to happen

I'm following this guide to install Prometheus to enable dashboards inside the head pod https://docs.ray.io/en/latest/cluster/metrics.html

My raycluster is running in default namespace.

I installed Prometheus in Prometheus namespace using this value file: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

I added:

```
    scrape_configs:
      - job_name: 'ray'
        file_sd_configs:
        - files:
          - '/tmp/ray/prom_metrics_service_discovery.json'
          refresh_interval: 1m
```

In the prometheus-server logs I'm getting an error: 

```
severity: "ERROR"
textPayload: "ts=2024-03-04T13:35:27.418Z caller=file.go:234 level=error component="discovery manager scrape" discovery=file config=ray msg="Error adding file watch" path=/tmp/ray/ err="no such file or directory""
```

When I open head pod dashboard I'm getting: 

```
Cluster utilization
Set up Prometheus and Grafana for better Ray Dashboard experience

Time-series charts are hidden because either Prometheus or Grafana server is not detected. Follow [these instructions](https://docs.ray.io/en/latest/ray-observability/ray-metrics.html) to set them up and refresh this page. .
```

The /tmp/ray/prom_metrics_service_discovery.json does exist in the head pod:

```
kubectl exec -it ray-head-xxxx -- cat /tmp/ray/prom_metrics_service_discovery.json
Defaulted container "ray-head" out of: ray-head, autoscaler
[{"labels": {"job": "ray"}, "targets": ["10.108.12.3:8080", "10.108.12.3:44217", "10.108.12.3:44227"]}]
```

### Versions / Dependencies

ray=2.5.0
Kubernetes: 1.27.8 GKE

### Reproduction script

none

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
Hi @23ewrdtf seems it's not a Ray issue but how the Prometheus is set up given `/tmp/ray/prom_metrics_service_discovery.json` exists in the head pod.
