### ISSUE TITLE
[rllib] Entropy coefficient in various algos

### ISSUE THREAD

**Issue by nikola-j** [ray-project/ray#4369]
### Describe the problem
In IMPALA and A3C entropy coeff is multiplied with the entropy but in PPO the negative of the entropy coeff is multiplied with entropy which creates inconsistencies between the algorithms.

I think it would be good to change them to use the PPO variant since this is a coefficient and the user shouldn't have to define the sign. And because same coefficient should be used between agents, so that agents can be changed and expected to work reasonably well with the same coefs. At least - change of sign in configs between agents is really unexpected and causes subtle bugs (it did so in our case).

**Comment by ericl** [comment]
Perhaps we can throw an error if the sign is unexpected, since it seems unlikely you'd want to penalize entropy?

The problem with changing it now is that it would break existing tuned hyperparameters. We could also rename the config.

**Comment by nikola-j** [comment]
Awesome work, thanks!
