### ISSUE TITLE
Release test rllib_learning_tests_appo_hybrid_api_stack_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43705]
Release test **rllib_learning_tests_appo_hybrid_api_stack_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/10431#018e0ec6-e96c-4cf9-8dc5-8b3aef8ee326 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/10617#018e12bd-3749-478b-bcd7-68ccca3889dd

**Comment by sven1977** [comment]
Old API stack: Release test has been removed. Closing this issue.
