### ISSUE TITLE
Release test rllib_learning_tests_dqn_old_api_stack_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43710]
Release test **rllib_learning_tests_dqn_old_api_stack_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/10431#018e0f24-c273-4049-a5e6-fe53bf66cfc0 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
Re-opening issue as test is still failing. Latest run: https://buildkite.com/ray-project/release/builds/10617#018e1340-4649-41fe-9197-fb8223f45672

**Comment by sven1977** [comment]
Old API stack: Release test has been removed. Closing this issue.
