### ISSUE TITLE
[Core] CI does not include CPP tests for Ray Core

### ISSUE THREAD

**Issue by ruisearch42** [ray-project/ray#43736]
### What happened + What you expected to happen

The CI tests do not include CPP tests for Ray Core. Example: https://buildkite.com/ray-project/premerge/builds/21240

Had a discussion with @rynewang , CPP tests should be covered in CI.

### Versions / Dependencies

Ray 2.9

### Reproduction script

N/A

### Issue Severity

None

**Comment by aslonnie** [comment]
it is conditioned to the change. you would need to change some c++ code to trigger cpp tests.

**Comment by aslonnie** [comment]
this is the condition to trigger cpp tests:

https://github.com/ray-project/ray/blob/master/ci/pipeline/determine_tests_to_run.py#L273

**Comment by aslonnie** [comment]
or:

https://github.com/ray-project/ray/blob/master/ci/pipeline/determine_tests_to_run.py#L370

**Comment by ruisearch42** [comment]
That makes sense. Thanks @aslonnie!
