### ISSUE TITLE
[Train] state_dict Key Truncation in RayFSDPStrategy leads to Unexpected key(s) Error

### ISSUE THREAD

**Issue by naity** [ray-project/ray#43744]
### What happened + What you expected to happen

**What happened:**
Regardless of the actual use case, keys in `state_dict` are unconditionally truncated based on the following code snippet in `RayFSDPStrategy`:
```
state_dict = self.model.state_dict()
prefix_len = len("_forward_module.")
return {k[prefix_len:]: v for k, v in state_dict.items()}
```
This results in the following error when attempting to load a saved checkpoint after training with `RayFSDPStrategy`:
```
RuntimeError: Error(s) in loading state_dict for MyLightningModule:
Missing key(s) in state_dict: "model.llm.embeddings.word_embeddings.weight",
Unexpected key(s) in state_dict: "ings.word_embeddings.weight",
```

**What you expected to happen:**
Please refrain from truncating `state_dict` keys in `RayFSDPStrategy` if not needed. A proposed solution is as follows:
```
state_dict = self.model.state_dict()
return {k.replace("_forward_module.", ""): v for k, v in state_dict.items()}
```
This proposed solution replaces "_forward_module." in `state_dict` keys instead of using string splicing.

### Versions / Dependencies

`Ray`: 2.9.3
`Python`: 3.10.13
`lightning`: 2.2.1

### Reproduction script

Providing a minimal example is challenging because it requires training a model and subsequently saving/loading the saved checkpoint. In contrast, the source code in `RayFSDPStrategy` is quite self-evident.

### Issue Severity

High: It blocks me from completing my task.

**Comment by naity** [comment]
Hi @matthewdeng Thank you so much for the update and for resolving the issue. However, I noticed that the accepted fix in  https://github.com/ray-project/ray/pull/43594 involves checking if each key starts with "_forward_module." and then performing string splicing if the condition is true, which seems tedious. In contrast, the solution I propose, using the `replace` method, is more straightforward and requires modifying only one line of code. Do you think it would be worthwhile to make the code more concise and readable using the proposed solution? If so, I can submit a new PR. Thank you!

**Comment by matthewdeng** [comment]
Ah I had thought about that too but decided against it in case `_forward_module.` was contained in the middle of the key (e.g. if it was somehow there in a nested attribute) and not just the start.

**Comment by naity** [comment]
I see, thank you for the clarification! I'll close the issue since it has already been fixed.
