### ISSUE TITLE
Do not upgrade Bazel to 0.23

### ISSUE THREAD

**Issue by guoyuhong** [ray-project/ray#4378]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

Now brew's version for Bazel is 0.23.2. However, 0.23.0 has a bug while building cython code, which I met the same problem as described in https://github.com/bazelbuild/bazel/issues/7607 .

**Comment by richardliaw** [comment]
Bazel issues should be fixed now.
