### ISSUE TITLE
[core][experimental] Support multi-node for shared memory channels and accelerated DAG

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#43828]
### Description

Shared memory channels currently only work for actors located on the same node. We should also support multi-node execution. This can be done by creating one shared memory buffer on the sender and another on the receiver. The receiver buffer could be read by multiple colocated downstream receivers. Initially, we can use RPC or TCP to copy the data between buffers.

**Comment by stephanie-wang** [comment]
This is mostly completed by #44094 by I believe there is one remaining TODO to support the driver as a reader.

**Comment by anyscalesam** [comment]
We also have to make sure we support objects larger than the gRPC limit

**Comment by rkooo567** [comment]
@stephanie-wang is driver as reader still not working?

**Comment by stephanie-wang** [comment]
Closing, we still have #47156 but that needs repro.
