### ISSUE TITLE
Question: Documentation for creating a new agent

### ISSUE THREAD

**Issue by dmadeka** [ray-project/ray#4384]
Is there a simple example of how to create an agent with a different loss and multiple policy networks from scratch?

**Comment by ericl** [comment]
Do you mean writing an algorithm from scratch? The pg algorithm is a pretty good example (it has a super simple loss): https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/pg/pg_policy_graph.py

**Comment by ericl** [comment]
> multiple policy networks

If you mean multi-agent here, QMIX is an example, otherwise there is the multi-agent API for running multiple agents/policies in one environment.

**Comment by richardliaw** [comment]
Should be fixed now.

**Comment by richardliaw** [comment]
Should be fixed now.
