### ISSUE TITLE
CI test windows://python/ray/serve/tests:test_autoscaling_policy_with_handle_metrics_disabled is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43848]
CI test **windows://python/ray/serve/tests:test_autoscaling_policy_with_handle_metrics_disabled** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3405#018e2152-46e8-4144-ac9e-93e6878d65d1
	- https://buildkite.com/ray-project/postmerge/builds/3396#018e2084-f6d2-4f7a-8b07-cb39601eef9f

DataCaseName-windows://python/ray/serve/tests:test_autoscaling_policy_with_handle_metrics_disabled-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by edoakes** [comment]
@GeneDer did your PR fix it?

**Comment by GeneDer** [comment]
My PR shorten the names so it's able to run on windows now

**Comment by can-anyscale** [comment]
ah yes probably my bad I think this test has been deleted/renamed; let's confirmed but otherwise don't worry about the automation

**Comment by edoakes** [comment]
ah yes it's probably because gene's PR changed the name :)

**Comment by can-anyscale** [comment]
CI test **windows://python/ray/serve/tests:test_autoscaling_policy_with_handle_metrics_disabled** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3464#018e35d1-91c6-4e45-90f6-eae4207e91ef
	- https://buildkite.com/ray-project/postmerge/builds/3416#018e2cf6-8c05-4260-84e9-35d8359d8779
	- https://buildkite.com/ray-project/postmerge/builds/3415#018e2beb-f873-44c8-b3e6-f04f50f2b61f
	- https://buildkite.com/ray-project/postmerge/builds/3411#018e27d0-0e9c-4eab-905c-e4f3839b0f2d
	- https://buildkite.com/ray-project/postmerge/builds/3410#018e26c5-a6b5-4b7e-bb96-7b96602456af

DataCaseName-windows://python/ray/serve/tests:test_autoscaling_policy_with_handle_metrics_disabled-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
test deleted
