### ISSUE TITLE
CI test linux://python/ray/tests:test_streaming_generator_regression is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43852]
CI test **linux://python/ray/tests:test_streaming_generator_regression** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3402#018e20bd-8ad0-4db6-86a9-ea7eeb68d97e

DataCaseName-linux://python/ray/tests:test_streaming_generator_regression-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
This one was opened due to a bug in CI (it fails only one so it's not that flaky), let's close to see if it happens again

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3505#018e3b5f-2402-4512-8bd2-b7dd32e7404d

**Comment by can-anyscale** [comment]
CI test **linux://python/ray/tests:test_streaming_generator_regression** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/3528#018e3eb1-299e-4fa5-be9c-905a330b85a3
	- https://buildkite.com/ray-project/postmerge/builds/3515#018e3e3f-4280-405a-8d3b-23a757e50943
	- https://buildkite.com/ray-project/postmerge/builds/3508#018e3d7c-d16b-4af5-a33e-73eb56a2512f
	- https://buildkite.com/ray-project/postmerge/builds/3460#018e3583-0785-4190-b9d2-7370ccb5173c
	- https://buildkite.com/ray-project/postmerge/builds/3453#018e34e6-d562-45df-9aee-b15ae4565b67

DataCaseName-linux://python/ray/tests:test_streaming_generator_regression-END
Managed by OSS Test Policy

**Comment by alexeykudinkin** [comment]
@can-anyscale test is failing b/c of filename:

```
[Errno 36] File name too long: '/artifact-mount/failed_test_logs/bazel-out::k8-opt::bin::python::ray::tests::test_streaming_generator_regression.runfiles::com_github_ray_project_ray::python::ray::tests::test_streaming_generator_regression.py::test_segfault_report_streaming_generator_output[ray_start_cluster0-0]_1709949220.7908.zip'
```

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/3752#018e8226-56c1-485e-8123-d321f80b8b94
