### ISSUE TITLE
<Ray train> deepspeed the checkpoint for each shard is the whole model instead of shard of the model

### ISSUE THREAD

**Issue by robinsonmhj** [ray-project/ray#43917]
### What happened + What you expected to happen

I am following this document below to fine tune llama2 7b model. 

https://docs.ray.io/en/latest/train/examples/lightning/vicuna_13b_lightning_deepspeed_finetune.html

After the training is done, I get a list of models(each worker produce a shard). However, the size of each shard of the model is the same with the original full model. When training a 70b model, the sync process gets timeout and dies

### Versions / Dependencies

ray[all]==2.9.2 transformers==4.30.2 
lightning==2.1.0 
SentencePiece==0.1.99 
pandas==2.1.1 
accelerate==0.20.3 
virtualenv==20.25.1 
datasets==2.18.0

### Reproduction script

https://docs.ray.io/en/latest/train/examples/lightning/vicuna_13b_lightning_deepspeed_finetune.html

### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
Hi @robinsonmhj , can you show us more details? Like the list of checkpoints, which files you were looking at, and how did you determine the size.

**Comment by robinsonmhj** [comment]
@woshiyyya sure. I am using the llama 2 7b, the size of the original model is about 7gb, however, after fine tuning it with 12 GPU, each shard in the checking point has about 6.3GB, see the output below

```
(base) sh-4.2$ ls -lh ./TorchTrainer_df11b_00000_0_2024-03-07_16-51-36/checkpoint_000000/checkpoint.ckpt/checkpoint
total 76G
-rw-r--r-- 1 root root 6.3G Mar  7 17:31 bf16_zero_pp_rank_0_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:22 bf16_zero_pp_rank_10_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:25 bf16_zero_pp_rank_11_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:36 bf16_zero_pp_rank_1_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:36 bf16_zero_pp_rank_2_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:36 bf16_zero_pp_rank_3_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:26 bf16_zero_pp_rank_4_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:27 bf16_zero_pp_rank_5_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:26 bf16_zero_pp_rank_6_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:25 bf16_zero_pp_rank_7_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:25 bf16_zero_pp_rank_8_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 6.3G Mar  7 17:24 bf16_zero_pp_rank_9_mp_rank_00_optim_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:25 zero_pp_rank_0_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_10_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_11_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:31 zero_pp_rank_1_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:25 zero_pp_rank_2_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:25 zero_pp_rank_3_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_4_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_5_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_6_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_7_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_8_mp_rank_00_model_states.pt
-rw-r--r-- 1 root root 173K Mar  7 17:19 zero_pp_rank_9_mp_rank_00_model_states.pt
```

**Comment by woshiyyya** [comment]
I think it's because it has both model weights and optimizer states.

https://github.com/huggingface/transformers/issues/22822#issuecomment-1513503504

In total it would be 7B (model weights) * 2 (bf16)  + 7B * 2 (optimizer states) * 4 (fp32)  = 70G

**Comment by robinsonmhj** [comment]
Thanks. However, the original model for llama2 7b is only 13.5G, does it only has the model weights?

How can I only store the weights in the checkpoint?

**Comment by justinvyu** [comment]
@robinsonmhj That's right, a custom callback following the one that we provide would be the way to do this.

**Comment by justinvyu** [comment]
Feel free to re-open if you have more questions.
