### ISSUE TITLE
CI test darwin://python/ray/tests:test_multiprocessing_client_mode is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#43937]
CI test **darwin://python/ray/tests:test_multiprocessing_client_mode** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge-macos/builds/120#018e33c4-25bc-4cb7-b12b-9920e2508417
	- https://buildkite.com/ray-project/postmerge-macos/builds/119#018e3379-cf30-4c54-91d7-633dbe452a64
	- https://buildkite.com/ray-project/postmerge-macos/builds/116#018e3342-e0c8-4eab-aaf7-f19a56a1ed78
	- https://buildkite.com/ray-project/postmerge-macos/builds/99#018e2a53-845b-4dc5-a14c-a46ac2a80678

DataCaseName-darwin://python/ray/tests:test_multiprocessing_client_mode-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Start failing as we now run with python 3.9

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/132#018e364a-c8bf-40e8-a5a4-987ab8abd484

**Comment by can-anyscale** [comment]
CI test **darwin://python/ray/tests:test_multiprocessing_client_mode** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge-macos/builds/130#018e370d-e9d6-4fcd-b5d9-fdcccf960367
	- https://buildkite.com/ray-project/postmerge-macos/builds/129#018e3583-4319-4165-8734-8264dd63a7fd
	- https://buildkite.com/ray-project/postmerge-macos/builds/124#018e34c2-2672-4f36-b843-7802c01d2974
	- https://buildkite.com/ray-project/postmerge-macos/builds/123#018e3478-639e-4a52-94f2-507a233c16c8
	- https://buildkite.com/ray-project/postmerge-macos/builds/122#018e344d-9e63-4425-8477-c837eb806e44

DataCaseName-darwin://python/ray/tests:test_multiprocessing_client_mode-END
Managed by OSS Test Policy

**Comment by anyscalesam** [comment]
discussed with team - we'll timebox all of these py39 failures and revisit wednesday. if it is a similar cause let's just fix it for all of them; else if it's more involved maybe we defer failing tests due to python39 to later.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/304#018e887a-b13a-4798-871c-e713ef8ba9b2

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/311#018e8b59-1bd1-40c6-937a-6db31ca719d5
