### ISSUE TITLE
LSTM cells in the output of a model

### ISSUE THREAD

**Issue by gowthamnatarajan** [ray-project/ray#4394]
In this section https://ray.readthedocs.io/en/latest/rllib-models.html#built-in-models-and-preprocessors
it says that LSTM cells can be added to the model. Does that mean, we can have multiple and variable number of actions in the model?

**Comment by ericl** [comment]
A LSTM model just means it can remember state from past observations of the MDP, it has nothing to do with the actions output of the model.

**Comment by evanatyourservice** [comment]
To piggyback on this question, is the default rllib lstm model stateful across batches?

And is even though lstm.py also uses _build_layers_v2 the fcnet is still in place before the LSTM layer?

**Comment by ericl** [comment]
LSTM state is carried across batches in sampling, but for training backprop
is limited by max_seq_len (or batch size if that's smaller).

And yes the default lstm option is added after some other preprocessing
model. If you define a custom rnn model though, this is not the case, and
you can define the full architecture as you wish.

**Comment by richardliaw** [comment]
Closing because stale, but should be fixed now.
