### ISSUE TITLE
Ray dashboard only shows head node

### ISSUE THREAD

**Issue by timediv** [ray-project/ray#4396]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.64
- **Python version**: 3.6
- **Exact command to reproduce**: Start head node and child nodes and open dashboard

### Describe the problem

The dashboard only shows the head node even though in fact tasks are running on multiple machines. Also does not show any tasks.

Totals: 1 node

**Comment by robertnishihara** [comment]
Should be fixed by #4428.

To see tasks, you can use the `ray timeline` command line command and then open the resulting file in chrome://tracing.

**Comment by joshuaathomas94** [comment]
This the issue that I'm currently having. From my remote node, I can run the ray start command and no errors appear, and I can even access the dashboard on the remote node. But the dashboard does not show when I add new nodes? 

I additionally tried the ray timeline command, but when I ran the command there was no data inside of the file generated.

**Comment by tg-bill** [comment]
Same issue here. I am following the doc here https://docs.ray.io/en/latest/cluster/guide.html#monitoring-the-cluster-via-the-dashboard, but the dashboard only shows head node.
