### ISSUE TITLE
[rllib] Remote worker envs cause memory leak

### ISSUE THREAD

**Issue by nikola-j** [ray-project/ray#4397]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: newest master
- **Python version**: 3.6.7
- **Exact command to reproduce**:
```python
import ray
import ray.tune as tune

ray.init()
tune.run_experiments({
    "my_experiment": {
        "run": "PPO",
        "env": "CartPole-v0",
        'stop': {
            'training_iteration': 3,
        },
        'num_samples': 10,
        "config": {
            "num_gpus": 1,
            "num_workers": 4,
            "num_envs_per_worker": 8,
            "remote_worker_envs": True,
            "lr": tune.grid_search([0.01, 0.001, 0.0001]),
        },
    },
})
```

### Describe the problem

When running rllib with remote worker envs and multiple tune trials the number of workers grows constantly between each trial until rllib crashes because of OOM.

### Source code / logs

```
2019-03-18 12:27:07,252	ERROR worker.py:1752 -- WARNING: X workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
```
Where X increases by 48 for each new trial until I run out of memory.

**Comment by ericl** [comment]
It looks like this is since the remote env actors aren't cleaned up. They probably could be killed with an `atexit ` hook or something? `agent._stop()` could also send remote calls to all the policy evaluators to clean up remote envs.
