### ISSUE TITLE
Inefficiency: worker_idle between actor methods

### ISSUE THREAD

**Issue by timediv** [ray-project/ray#4399]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.64
- **Python version**: 3.6
- **Exact command to reproduce**: Start head node, 1 child node; Create actor on child node, queue two remote method calls on actor.

### Describe the problem
I would expect both methods to run with basically no delay. Instead, the first method runs 12 ms, then there is a 63ms delay, and then the second method runs 10 ms.
This problem does not occur when the actor runs on the head node.

**Comment by raulchen** [comment]
Did you submit the actor tasks from the head node or the child node?

Also, could you try again with env var `export RAY_BACKEND_LOG_LEVEL=debug`, and paste the `raylet.err` logs of both nodes?

**Comment by richardliaw** [comment]
Closing because stale, but should be fixed now.
