### ISSUE TITLE
Log directory empty since upgrade from 0.63 to 0.64

### ISSUE THREAD

**Issue by timediv** [ray-project/ray#4400]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.64
- **Python version**: 3.6
- **Exact command to reproduce**: Starting ray and running any driver

### Describe the problem
Since upgrading from ray 0.63 to 0.64 the log directory appears to be empty.

```
/tmp/ray/session_2019-03-18_12-25-11_887819$ ls
logs  sockets
```
```
/tmp/ray/session_2019-03-18_12-25-11_887819/logs$ ls
```

**Comment by richardliaw** [comment]
Should be fixed now.
