### ISSUE TITLE
[Ray: Core] cannot install latest version on MacOS (Apple Silicon) with Python 3.12 #34666

### ISSUE THREAD

**Issue by tianhuil** [ray-project/ray#44014]
### What happened + What you expected to happen

This is what I get on Apple Silicon:
```
➜  /tmp pip install ray
ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray
➜  /tmp pyenv local 3.11
➜  /tmp pip install ray
Collecting ray
  Obtaining dependency information for ray from https://files.pythonhosted.org/packages/5e/1e/c82fd989b56cbf37b4596a2f23c6b0a06e6ca1bccfd5f7fbd71906e94e1d/ray-2.9.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading ray-2.9.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting click>=7.0 (from ray)

# installation works
```

**Unfortunately, it took me a good 2 hours to figure out that it would work on 3.11.**

3.12 was released in October, 2023.  If building the wheel is challenging, can you at least upload a wheel that crashes and nothing but tell me to use Python 3.11 when I import ray?

### Versions / Dependencies

Python 3.12

### Reproduction script

See above.

### Issue Severity

Low: It annoys or frustrates me.

**Comment by anyscalesam** [comment]
Python 3.12 is not quite supported yet; we just released experimental support at the Ray Core layer last week. Please refer to Ray Documentation here for supported Python versions. See here: https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies
