### ISSUE TITLE
[serve] Eagerly remove handle metrics during normal shutdown procedures

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#44047]
See https://github.com/ray-project/ray/issues/44046 for context.

The timeout is a good fail safe mechanism, but during normal proxy/replica shutdown we should not rely on it and instead eagerly remove the metrics. This can be done purely in the controller by tracking which actor ID the metric comes from.

**Comment by zcin** [comment]
closed by https://github.com/ray-project/ray/pull/44453
