### ISSUE TITLE
Release test long_running_pbt.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44060]
Release test **long_running_pbt.aws** failed. See https://buildkite.com/ray-project/release/builds/11444#018e4660-476e-4964-8f3f-edb888de37ea for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 82e6c40cbd236ef17ac16fd1131e71b3ed81187a found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/947

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
This test is owned by ml actually, @matthewdeng , @justinvyu  do we still want to keep this test, thankks

**Comment by justinvyu** [comment]
Let's remove the test to:
1. Minimize ML team x RLlib release test cross-team dependencies.
2. Remove this low-signal test: we already have alternative tests that run faster and test more targeted behavior. For example, `tune_with_frequent_pausing` is a test that checks pausing behavior. We can leave testing the PBT algorithm correctness to the unit tests.
