### ISSUE TITLE
[3.11 upgrade] rllib test failures

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44089]
### What happened + What you expected to happen

The following rllib tests failed on python 3.11 upgrade (https://buildkite.com/ray-project/premerge/builds/22125):

CPU tests:
- //rllib:test_impala
- //rllib:test_appo
- //rllib:examples/export/onnx_tf

GPU tests:
- //rllib:tests/test_checkpoint_restore_off_policy_gpu
- //rllib:tests/test_checkpoint_restore_ppo_gpu
- //rllib:tests/test_supported_spaces_ppo_no_preprocessor_gpu
- //rllib:test_repro_ppo
- //rllib:examples/deterministic_training_tf2
- //rllib:tests/test_supported_multi_agent_multi_gpu 

### Versions / Dependencies

https://github.com/ray-project/ray/pull/44075

### Reproduction script

Buildkite: https://buildkite.com/ray-project/premerge/builds/22125#018e4fc3-8677-4e37-ae3e-86191c3c7bf8
Reproduce locally:

CPU

> docker run -it --rm --entrypoint /bin/bash --env NVIDIA_DISABLE_REQUIRE=1 029272617770.dkr.ecr.us-west-2.amazonaws.com/rayproject/citemp:py311rllib
> bazel test --flaky_test_attempts=1 --test_output=streamed <BAZEL_TEST_TARGET>

GPU
docker run -it --rm --entrypoint /bin/bash --env NVIDIA_DISABLE_REQUIRE=1 029272617770.dkr.ecr.us-west-2.amazonaws.com/rayproject/citemp:py311rllibgpu
> bazel test --flaky_test_attempts=1 --test_output=streamed <BAZEL_TEST_TARGET>

### Issue Severity

High: It blocks me from completing my task.

**Comment by sven1977** [comment]
Mostly tensorflow compatibility (eager vs static graph) related problems. This might take a while to fix :(
