### ISSUE TITLE
[rllib] Misspelled key in .../tuned_examples/pendulum-ppo.yaml

### ISSUE THREAD

**Issue by jpiabrantes** [ray-project/ray#4411]
https://github.com/ray-project/ray/blob/c93eb126ec8946a35486b5ee60d4b95427a1be51/python/ray/rllib/tuned_examples/pendulum-ppo.yaml#L18

`observation_fliter` should be `observation_filter`.

**Comment by ericl** [comment]
Thanks! fixed in https://github.com/ray-project/ray/pull/4409
