### ISSUE TITLE
Cannot queue trials when there are no available cpus

### ISSUE THREAD

**Issue by jamescasbon** [ray-project/ray#4415]
### System information
- **Debian 8**:
- **binary**:
- **0.6.4**:
- **3.5.3**:
- **--run DQN --env CartPole-v0 --queue-trials --queue-trials --redis-address x.x.x.x:x**:

### Describe the problem

If I have zero cpus available I am unable to queue trials.  This is not great when using autoscaling. When using autoscaling on a cloud provider I want to start with 0 workers and 0 cpus on the head node.  However, I am unable to queue trials in this setup.

I believe this is the cause....

        can_overcommit = self._queue_trials

        if (resources.cpu_total() > 0 and currently_available.cpu <= 0) or \
           (resources.gpu_total() > 0 and currently_available.gpu <= 0) or \
           any((resources.get_res_total(res_name) > 0
                and currently_available.get(res_name) <= 0)
               for res_name in resources.custom_resources):
            can_overcommit = False  # requested resource is already s

**Comment by richardliaw** [comment]
This should be fixed.
