### ISSUE TITLE
[serve] Avoid blacklisting replicas that have intermittent network failures

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#44185]
Due to https://github.com/ray-project/ray/issues/29656, actors that have intermittent network failures will be marked as dead by Ray Core.

Currently we blacklist replicas that raise a `RayActorError`. In this case, the controller may not actually mark such replicas as dead, so we can get in a bad state where routers won't send requests to a replica but the controller isn't restarting it. If no replica set change occurs, the replicas will be stuck.

We can detect this case by checking for no "failure reason" set in the exception (TODO: need to verify this is reliable). Then instead of removing the replica for consideration, we can keep it in the replica set but clear its cache entry. That way we'll need to be able to actively probe it before new requests can be sent.

**Comment by edoakes** [comment]
An alternative option here would be to have a timeout on how long we remove the replica from consideration. If we haven't gotten an updated message from the controller after some period, we can re-add it to the set for consideration.

**Comment by edoakes** [comment]
Looking at the code for `RayActorError` it doesn't seem that there is a reliable way to check for this case (it only stores an error message). So we'll need to add that at a minimum.

**Comment by alexeykudinkin** [comment]
@edoakes so problematic part is that we split the responsibilities here and allow Routers to decide on the status of the downstream replica along with the Controller (creating multi-writer scenario).

I think we should just do following: 

 - Fully defer membership management to controller (ie Controller decides when Replica is both removed from the routing pools as well as restarted). In this particular case if the actor is _really_ dead, then it will fail health-checks as well.

**Comment by shrekris-anyscale** [comment]
@alexeykudinkin That's true, but we do this is an optimization. Assuming `RayActorError` actually means that the replica is dead, there's no reason the router should keep considering it for scheduling.

The problem here is that `RayActorErrors` can be raised if the replica is still alive, which is a bug. For now, we can mitigate this in Serve (https://github.com/ray-project/ray/pull/44193), but ultimately it needs to be fixed in Ray Core.

**Comment by edoakes** [comment]
The main case where this can become an issue is when the controller is down (for example during head node recovery). If this happens, we will continue attempting to route to dead actors until it comes back (which can be a long time).
