### ISSUE TITLE
[tune] Simplify and document semantics of auto-filled logging fields

### ISSUE THREAD

**Issue by gehring** [ray-project/ray#4419]
### Describe the problem
Currently, the behavior of several of the [auto-filled results](https://ray.readthedocs.io/en/latest/tune-usage.html#auto-filled-results) is opaque and poorly documented. It would be good to clearly and unambiguously document the semantics of every result not provided by the user that could be added or modified by tune.

### Possible issues to look into:
- [ ] Missing documentation for several auto-filled results. A (potentially non-exhaustive) list of such results: `timestamp`,  `time_since_restore`,  `experiment_id`, `date`. Granted, the semantics of these results should be fairly easy to deduce, I would still be good that document them.
- [ ] Missing documentation about how and when some of the  `*_this_iter` and `*_total` results are generated. For example, the default behavior of `timesteps_total` is to always report it if `timesteps_this_iter` is ever reported (even if just once) but never otherwise. This behavior isn't particularly complex but it is definitely non-obvious and, therefore, documented (related points below).
- [ ] The auto-filled results are entangled with rllib specific results. For example, episodic results (and arguable timesteps too) don't have any meaning in an arbitrary hyper-parameter optimization setting and might be best kept in rllib. This shouldn't require any significant refactoring (see bellow for a simple solution).
- [ ] Implement and document general `_this_iter`/`_total` suffix semantics to automatically and consistently handle results ending with `_this_iter`, e.g.,  the current timesteps and episodes results.
- [ ] (related to the previous points) The logic for counting [`timesteps_total`](https://github.com/ray-project/ray/blob/7c3274e65b75d4533b744639e8fb62fb05bf7f75/python/ray/tune/trainable.py#L168) and [`episodes_total`](https://github.com/ray-project/ray/blob/7c3274e65b75d4533b744639e8fb62fb05bf7f75/python/ray/tune/trainable.py#L175) is repeated and should be shared to avoid inconsistencies down the line.

#### More on `_this_iter`/`_total` suffix 
 This would be a powerful addition to the logging logic and would give the user (or related libraries, e.g., rllib!) the flexibility of tracking count-based results with little effort.  For example, imagine a user is working on some sort of planning (in the search-based sense) and learning algorithm where we might care about the number of failed searches (e.g., timeout). This could easily be tracked by reporting `num_search_failures_this_iter`, automatically causing a new corresponding results `num_search_failures_total` which is tracked from that point on.

Additionally, if desired, this mechanism could take care of counting the training iterations by simply adding a default `training_iterations_this_iter=1` to every result and renaming `training_iteration` to `training_iterations_total` (or a more succinct name). Beyond simplifying/unifying the code, this would allow users to override the default iteration count instead of forcing the creation of a custom counter, e.g., `my_training_iterations` or using a auto-filled with a less appropriate name, e.g., `timesteps_this_iter`, if the user has a need for it.

The way I see it, whether or not this is desirable boils down to whether or not this would add unnecessary complexity. I would argue that given timesteps and episodes already do this, this shouldn't be particularly more mysterious than the current behavior. In my opinion, either timesteps and episodes are refactored and tracked entirely within rllib, or it is kept as a well-documented general mechanism the user can reuse.

As always, I'm happy to help with this if there is interest.

### Related issues
#2561
#3226
#3956

**Comment by gehring** [comment]
@richardliaw This issue summarizes the remaining logging peculiarities I encountered that weren't caused by the class API vs function API logging issues. Let me know what you think!

**Comment by richardliaw** [comment]
Thanks again for opening this issue! Honestly, I think any additions/clarifications to the documentation would be incredibly helpful.

> Episodic results (and arguable timesteps too) don't have any meaning in an arbitrary hyper-parameter optimization setting and might be best kept in rllib. 

No strong opinion on this, though displaying `ts` is pretty helpful. cc @ericl 

RE: `_this_iter`/ `_total` - I think general-case handling here might not be needed and might introduce too much complexity. The value add doesn't seem too worth it to me; it's way easier to do this as a user in keeping a counter (or even in Pandas after your experiment with `cumsum` on your result dataframe). Definitely agree about the documentation though.
