### ISSUE TITLE
[Train] DeepSpeed ZeRO-3 optimizer errors with `transformers==4.30.0` on config initialization

### ISSUE THREAD

**Issue by sword865** [ray-project/ray#44204]
### What happened + What you expected to happen

When using Ray Train with DeepSpeed ZeRO-3, an incompatibility issue arises, resulting in an assertion error related to batch size parameters.

```assert train_batch == micro_batch * grad_acc * self.world_size, (
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 16 != 8 * 1 * 1
```

### Versions / Dependencies

```accelerate==0.25.0
deepspeed==0.13.5
ray==2.9.1
transformers==4.35.2
```

### Reproduction script

The issue can be reproduced by running a multi-GPU DeepSpeed job with ZeRO-3 and initializing TrainingArguments before Model Loading:

```
    training_args = TrainingArguments(...., deepspeed=deepspeed_zero3_config)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name, use_cache=False)
```

### Root Cause Analysis

The issue stems from the initialization process in AutoModelForCausalLM.from_pretrained, which activates DeepSpeed ZeRO-3:

https://github.com/huggingface/transformers/blob/v4.35.2/src/transformers/modeling_utils.py#L550

```
        if is_deepspeed_zero3_enabled():
            import deepspeed
            logger.info("Detected DeepSpeed ZeRO-3: activating zero.init() for this model")
            init_contexts = [deepspeed.zero.Init(config_dict_or_path=deepspeed_config())] + init_contexts

````

In the initialization function, DeepSpeed relies on the cdb to determine the world size:

https://github.com/microsoft/DeepSpeed/blob/v0.13.5/deepspeed/runtime/config.py#L724

```
        try:
            self.global_rank = dist.get_rank()
            if mpu is None:
                self.world_size = dist.get_world_size()
            else:
                self.world_size = mpu.get_data_parallel_world_size()

```
https://github.com/microsoft/DeepSpeed/blob/v0.13.5/deepspeed/comm/comm.py#L530

```
def get_world_size(group=None) -> int:
    """
    Returns the number of processes in the current process group
    Args:
        group (ProcessGroup, optional): The process group to work on. If None,
            the default process group will be used.
    Returns:
        The world size of the process group
        -1, if not part of the group
    """
    global cdb

    assert cdb is not None and cdb.is_initialized(
    ), 'DeepSpeed backend not set, please initialize it using init_process_group()'
    return cdb.get_world_size(group)

```

The cdb is initialized within the Accelerate library, provided that Torch's distributed framework has not already been initialized.

https://github.com/huggingface/accelerate/blob/v0.25.0/src/accelerate/state.py#L171
```
                if not torch.distributed.is_initialized():
                    from deepspeed import comm as dist

                    # DeepSpeed always uses nccl
                    kwargs.pop("backend", None)
                    if is_xpu_available and is_ccl_available():
                        # Set DeepSpeed backend to ccl for xpu
                        self.backend = "ccl"
                    elif is_npu_available():
                        self.backend = "hccl"
                    else:
                        self.backend = "nccl"
                    dist.init_distributed(dist_backend=self.backend, auto_mpi_discovery=False, **kwargs)

```

However, for Ray Train, since TorchTrainer initializes Torch's distributed framework, the condition `if not torch.distributed.is_initialized():` evaluates to false. Consequently, this prevents the initialization of cdb, leading to an incorrect assumption that world_size is 1, which in turn causes the aforementioned issue.

### Issue Severity

Here is a workaround by switching the positions of `training_args = TrainingArguments(...)` and `model = AutoModelForCausalLM.from_pretrained(...)`, but this may lead to potential OOM due to model can not be allocate in a memory-scalable fashion: (init `training_args` before `model`)
https://www.deepspeed.ai/tutorials/zero/#allocating-massive-megatron-lm-models

**Comment by matthewdeng** [comment]
Thanks for the detailed investigation! I believe the root cause of this is  https://github.com/huggingface/transformers/issues/28803.

As a workaround can you call `deepspeed.init_distributed()` at the start of your training function?

**Comment by sword865** [comment]
Thank you for the clarification. I think the root cause is that `DeepSpeed ZeRO-3` in `Accelerate` fails to function properly when the Torch distributed environment is initialized by the user or by another program, such as RayTrain.
By the way, directly using dist.init_distributed('nccl', auto_mpi_discovery=False) allows the model to load successfully, but it seems that the training process gets stuck.  Not sure but this may caused by misconfiguration of the communication backend. I am still exploring to find a better solution.

**Comment by sword865** [comment]
Indeed, utilizing deepspeed.init_distributed() appears to be a viable workaround. However, I am uncertain about potential side effects this may introduce. I will investigate further to ensure its reliability.
Thanks for your help.
