### ISSUE TITLE
CI test darwin://python/ray/dashboard:modules/job/tests/test_https_connection is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44210]
CI test **darwin://python/ray/dashboard:modules/job/tests/test_https_connection** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge-macos/builds/214#018e5f6b-d9e2-4795-a329-7127f14ee335
	- https://buildkite.com/ray-project/postmerge-macos/builds/212#018e5e61-7b8a-426e-ab96-98f53ceb1793
	- https://buildkite.com/ray-project/postmerge-macos/builds/211#018e5e00-50ee-405c-8a35-d4176434e8f7

DataCaseName-darwin://python/ray/dashboard:modules/job/tests/test_https_connection-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
https://github.com/ray-project/ray/commit/9088645ca3161b3908a260c3f9141a8dfc0b5669 could be the blame commit

**Comment by zcin** [comment]
> [9088645](https://github.com/ray-project/ray/commit/9088645ca3161b3908a260c3f9141a8dfc0b5669) could be the blame commit

I don't think it's related. Seeing errors like:
```
>       return rust_x509.create_x509_certificate(self, private_key, algorithm)
E       TypeError: create_x509_certificate() missing 1 required positional argument: 'rsa_padding'
```

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/215#018e615b-41e8-4b43-8aee-c81fc59ad465

**Comment by can-anyscale** [comment]
CI test **darwin://python/ray/dashboard:modules/job/tests/test_https_connection** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge-macos/builds/230#018e64cb-3d02-4b90-943d-db11a32676a3
	- https://buildkite.com/ray-project/postmerge-macos/builds/229#018e6492-3b6f-48ec-8e31-a745622e5974
	- https://buildkite.com/ray-project/postmerge-macos/builds/226#018e62de-3a2a-46a9-9018-46a224b03f14
	- https://buildkite.com/ray-project/postmerge-macos/builds/223#018e627a-1efd-4719-bf85-508453487c77
	- https://buildkite.com/ray-project/postmerge-macos/builds/214#018e5f6b-d9e2-4795-a329-7127f14ee335

DataCaseName-darwin://python/ray/dashboard:modules/job/tests/test_https_connection-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/231#018e66c6-3e22-414d-a6ef-72f558978fbc

**Comment by can-anyscale** [comment]
CI test **darwin://python/ray/dashboard:modules/job/tests/test_https_connection** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge-macos/builds/894#018f9e78-aebd-45ba-b199-c05c2716204d
	- https://buildkite.com/ray-project/postmerge-macos/builds/894#018f9da7-c19b-43cb-83de-d4cacf6a2cbe

DataCaseName-darwin://python/ray/dashboard:modules/job/tests/test_https_connection-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 74fc9be46e6d927d44ddb7b1ee74437e46aba802 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1153

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by can-anyscale** [comment]
it blames to a wrong commit because the build was broken mid-way hmm

**Comment by can-anyscale** [comment]
@hongchaodeng , @jjyao can you help take a look, could it be https://github.com/ray-project/ray/commit/61d9049628001ec6b2129c30d66eb741908994b3, thankks

**Comment by can-anyscale** [comment]
look like a transient issue, passing now

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge-macos/builds/934#018fa907-f2ad-4b66-8c49-d1bfd1443025
