### ISSUE TITLE
[Doc] [Polish] Front page icons appear blurry and off-center

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#44228]
### Description

Examples:
<img width="220" alt="Screenshot 2024-03-21 at 2 08 54 PM" src="https://github.com/ray-project/ray/assets/5459654/1ea48b9c-a1e6-4dec-9bfa-b94657b6bde7">
<img width="278" alt="Screenshot 2024-03-21 at 2 07 56 PM" src="https://github.com/ray-project/ray/assets/5459654/d3ac55dd-260d-4616-9ef8-1e343ecf8b43">
The blurriness is slight, but apparent on a high DPI display.

### Link

http://docs.ray.io

**Comment by den319** [comment]
Would you like to explain what you changes you are suggesting?

**Comment by architkulkarni** [comment]
I would expect the icons to either be high DPI or some kind of vector graphics, but I'm not an expert here and don't know how it's usually done.  And I feel like the icons should be better aligned with the title text "Learn basics" and "Ray Core", but I don't have a precise recommendation. cc @peytondmurray or @simran-2797 maybe?

**Comment by angelinalg** [comment]
@peytondmurray is actively working on a revision of this page. Let's see if this is in scope of that work.

**Comment by peytondmurray** [comment]
See https://github.com/ray-project/ray/issues/42068 for more information.
