### ISSUE TITLE
[Serve] Allow Serve+KubeRay to handle dynamically-created Serve applications smoothly

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/ray#44226]
### Description

This ticket is being created to track issues originally discussed at https://ray-distributed.slack.com/archives/CNCKBBRJL/p1710792087920309 ; I've copied in some of the conversation here to summarize the issue and potential solutions.

The way we’re using Serve is that we have two “static” Serve applications which are in our `start.yaml`/KubeRay `RayService` CR config. One is an HTTP ingress (and is marked as an ingress app), the other is a controller.
* The controller reconciles between Ray Serve and our model registry by dynamically creating and deleting Serve apps (i.e., we call `serve.run(...)` on a `Deployment` with dynamically-set `options` and `bind` parameters) for the models in the registry. 
* The HTTP ingress is the public API for our clients, and it routes requests to those Serve apps (via `serve.get_app_handle(...).remote(...)`).

This obviously isn’t the standard way of using either Serve 1.x or 2.x, but it was working well under 1.x (we were using `Deployment.deploy(...)` and whatnot instead), and it’s working under 2.x, except for some edge cases which are described below.

---

Problem 1: because we can’t have bare deployments under 2.x (without them being attached to apps) anymore, whenever the KubeRay operator does a `PUT /api/serve/applications/` to deploy the Serve app, the logic [here](https://github.com/ray-project/ray/blob/37751f1b66ff6bbff2312d7b4c3929371b1e535a/python/ray/serve/_private/controller.py#L802-L807) deletes all other applications - namely, the dynamic ones that our controller created!

KubeRay doesn’t only send that `PUT` during Ray cluster startup: it also sends it whenever the KubeRay operator restarts, because the state of “have I sent a `PUT` to this cluster yet” is stored in memory [here](https://github.com/ray-project/kuberay/blob/99c5a3ad20be79e643b4c4ab34976aa5855386c2/ray-operator/controllers/ray/rayservice_controller.go#L762-L764) (and [here](https://github.com/ray-project/kuberay/blob/99c5a3ad20be79e643b4c4ab34976aa5855386c2/ray-operator/controllers/ray/rayservice_controller.go#L792-L800) when the `RayService` changes). This is what triggers the problem for us (our KubeRay operator restarted and caused some downtime because it deleted all of our deployed models, which is how we found out about this problem).

What’s tricky here is that I don’t think Serve or KubeRay are doing anything wrong here (except maybe that the “have I sent a `PUT`” cache shouldn’t be in-memory). All of the above is exactly how a reconciling/idempotent operator flow should work, given how the Serve 2.x API treats apps. But it has this unfortunate interaction with dynamic applications.

Our immediate workaround is that we’re hacking our KubeRay operator so that it only sends the `PUT` in [this case](https://github.com/ray-project/kuberay/blob/99c5a3ad20be79e643b4c4ab34976aa5855386c2/ray-operator/controllers/ray/rayservice_controller.go#L780-L790), i.e., on startup/crash. So existing clusters won’t pick up any changes in the Serve config on the `RayService`, but that’s fine because we always roll a new container image version when we change those anyway, so the new cluster will get the new config.

--- 

Problem 2:

When KubeRay is checking whether Serve is ready, it checks the status of all applications that it gets back from the dashboard API, even ones that aren’t in the static `RayService` config (see [this loop](https://github.com/ray-project/kuberay/blob/f3f46cdbc73f26094ecbbd3e049e42c5694d365d/ray-operator/controllers/ray/rayservice_controller.go#L859)). We want KubeRay to ignore these - we’re managing the state of those applications ourselves, and we don’t want one failing to take down the whole cluster (e.g., if a user uploads a malformed model to the registry, we’ll just fail to load it and let the rest of the models keep running).

In particular, we were hitting these two blocks in KubeRay v1.0.0 https://github.com/ray-project/kuberay/blob/dcb5d3daa66175b1ff61f5ef4af90f4b44de2916/ray-operator/controllers/ray/rayservice_controller.go#L819-L842. If a single dynamic deployment was permanently unhealthy, it would mark the cluster as unhealthy in the first block, and unready in the second block. To fix that we patched that whole loop to only consider Serve apps that are present in the static config in the CR.

We’re patching our KubeRay so that it only considers the apps defined in the static `RayService` config there, which again fixes the problem for us - maybe another thing that could be an option in upstream `KubeRay`? Again, we’d be happy to contribute the code for this.

I believe it was `ServiceUnhealthySecondThreshold`, but also just the readiness check (though that didn’t take the cluster down, it just would have prevented rolling out new clusters).

> Would you mind sharing the use cases of dynamic Serve apps?

Our use case is that we want to load models from our model registry into Serve apps (1:1), then call them dynamically from our router ingress. We don’t know how many or what types of models (model types are 1:1 with Deployment types), etc. beforehand, so AFAIK this can’t be expressed through the static serve config on the CR, even if we had a separate controller service updating it, since we’re doing things like passing `.bind` parameters created at runtime.

But even if we could express it statically, we wouldn’t want to, because we also need KubeRay to not care about these dynamic apps, because their health or readiness does not indicate overall cluster health or readiness - we track that ourselves in our model controller and use its health/readiness to aggregate readiness information from the dynamic apps in a more flexible way. As an example, if a user of our platform uploads a malformed model that we fail to load, we want to still consider the Ray cluster and services as healthy/ready, because only that particular model is bad. 

---

After discussing with @edoakes and @kevin85421 on Slack, here's the proposed changes:

1. Add a new configuration option `update_serve_config_in_place` to the `RayService` CRD. When `true` (the default), KubeRay does what it does currently. When `false`, if the `ServiceConfigV2` field changes, KubeRay will instead roll an entirely new `RayCluster` to apply those changes to. This resolves our Problem 1. I can contribute this change in KubeRay.
2. @edoakes suggested that Serve could have an option in the config API that determines whether it will touch applications created by `serve.run`. Whether a Serve app was created via `serve.run` would also be available in the Serve status API. @edoakes offered to do this change (I'm not very familiar with the Serve internals so it would be harder for me to contribute there, though I'll note that it might be better to have an enum that describes the "source" of the app?). Once that Serve change is made, KubeRay can have another new configuration option that would make it A) not touch applications created by `serve.run` when it sends config updates, B) not consider applications created by `serve.run` when determining readiness. This would solve Problem 2. I can contribute this change in KubeRay.

TBD: if we do solution 2, do we even need solution 1? I haven't thought it through yet, but it seems that if KubeRay can be configured to never touch dynamic apps, that would resolve both problems in one go.

TBD: for solution 2, what will the exact new API in Serve be so that KubeRay can uptake it?

**Comment by edoakes** [comment]
Thanks for filing @JoshKarpel. Let me put a more precise API proposal (hopefully tomorrow) on this issue and we can iterate from there!

Btw, this should land in the next release which I believe is targeted to go out ~April 10.

**Comment by edoakes** [comment]
For (2), we need to handle but the apply (`PUT`) and status (`GET`) REST APIs. As a minimal first solution, I'd suggest:

- Internally in the controller, keep metadata of the `ApiSource` of each application (`REST_API`, `PYTHON_API`, maybe `JAVA_API`).
- Update the default behavior of the apply API to only delete applications whose source is `REST_API` (and adding an environment variable feature flag to disable the behavior as a failsafe). I can't see a time when we'd want the current behavior over this, but if it comes up we can add an explicit flag to the API.
- Return the `Source` of each application in the REST API response. Then Kuberay/other systems can do whatever they want  to filter/ignore some sources when calculating higher-level status.

Thoughts @JoshKarpel @zcin @shrekris-anyscale?

**Comment by JoshKarpel** [comment]
> * Update the default behavior of the apply API to only delete applications whose source is `REST_API` (and adding an environment variable feature flag to disable the behavior as a failsafe). I can't see a time when we'd want the current behavior over this, but if it comes up we can add an explicit flag to the API.

So the semantics of the `PUT` here would be that (by default) it is still idempotent/replacing, but only over the set of applications coming from the `REST_API`? Makes sense to me and sounds like an elegant solution on the Serve side.

Would the KubeRay changes need to be backwards-compatible with previous versions of Ray? I suppose that KubeRay could assume the source is `REST_API` if not present in the `GET` response, which would produce the current behavior. cc @kevin85421 on that.

**Comment by shrekris-anyscale** [comment]
@edoakes I think the first 2 parts of the minimal solution make sense. I think the the 3rd is a bit limiting though. 

Fundamentally, the API we want to express is that some apps should be managed by Serve itself, and some apps should be managed by external systems. It feels unnecessary to tie this split to the source of the API call (i.e. Python vs. REST). For example, in the future, we might want to provide a REST API method that allows users to submit an app that can be managed by an external system.

What if we introduce an `owner` field to each app? Apps owned by `"serve"` will be managed fully by Serve. For now, any app submitted by REST API will be owned by `"serve"`, and any app submitted by `serve.run` will be unowned (`owner=None`). In the future, perhaps users can set an `owner` explicitly for each app. We can return the `owner` in the status call.

**Comment by JoshKarpel** [comment]
> Fundamentally, the API we want to express is that some apps should be managed by Serve itself, and some apps should be managed by external systems. It feels unnecessary to tie this split to the source of the API call (i.e. Python vs. REST). For example, in the future, we might want to provide a REST API method that allows users to submit an app that can be managed by an external system.
> 
> What if we introduce an `owner` field to each app? Apps owned by `"serve"` will be managed fully by Serve. For now, any app submitted by REST API will be owned by `"serve"`, and any app submitted by `serve.run` will be unowned (`owner=None`). In the future, perhaps users can set an `owner` explicitly for each app. We can return the `owner` in the status call.

I really like this idea, but as an outsider I'm not quite sure what "owned by Serve" means - would KubeRay want to submit with `owner="kuberay"`?

**Comment by shrekris-anyscale** [comment]
Owned by `serve` means that the Serve controller determines when to maintain and when to terminate an application. For now, that just means that whenever Serve receives a new config, it'll terminate any existing applications that are owned by `serve` but aren't in the new config.

If an app isn't owned by Serve, the Serve controller will continue to reconcile it, but the controller will never delete it on its own. That's left up to an external system.

KubeRay doesn't need to own any apps. It can delegate app management to the Serve controller, as it does right now.

**Comment by edoakes** [comment]
> @edoakes I think the first 2 parts of the minimal solution make sense. I think the the 3rd is a bit limiting though.
> 
> Fundamentally, the API we want to express is that some apps should be managed by Serve itself, and some apps should be managed by external systems.

I disagree with this. The sticking point is just that the REST API and Python API have different semantics (REST API is declarative, Python API is imperative). Note that Kuberay is not really "managing" apps in any way, it's just directly applying the Serve config which has the semantic of being declarative and tearing down other apps.

**Comment by shrekris-anyscale** [comment]
> Note that Kuberay is not really "managing" apps in any way, it's just directly applying the Serve config which has the semantic of being declarative and tearing down other apps.

I agree about KubeRay. When I refer to an "external system" managing the Serve application, I'm referring to @JoshKarpel's setup where his application starts new Serve apps with `serve.run` that shouldn't be wiped away when a new config is applied. Those apps' lifetimes should only be terminated by @JoshKarpel's application, not Serve itself.

> The sticking point is just that the REST API and Python API have different semantics (REST API is declarative, Python API is imperative).

We do have these semantics currently, but in the future we may want to add imperative REST API commands, and this API would make that more challenging.

**Comment by edoakes** [comment]
> > Note that Kuberay is not really "managing" apps in any way, it's just directly applying the Serve config which has the semantic of being declarative and tearing down other apps.
> 
> I agree about KubeRay. When I refer to an "external system" managing the Serve application, I'm referring to @JoshKarpel's setup where his application starts new Serve apps with `serve.run` that shouldn't be wiped away when a new config is applied. Those apps' lifetimes should only be terminated by @JoshKarpel's application, not Serve itself.
> 
> > The sticking point is just that the REST API and Python API have different semantics (REST API is declarative, Python API is imperative).
> 
> We do have these semantics currently, but in the future we may want to add imperative REST API commands, and this API would make that more challenging.

Why would it make it more challenging? Wouldn't that just be an extension to add something like `Source.IMPERATIVE_REST_API`?

**Comment by edoakes** [comment]
> I’m also looking at supporting something similar and running into the same issues. I believe the fixes proposed here would solve most of it. I would just add, and I might be wrong here, that deploying an app dynamically using `serve.run` does not add the new application config to the key value store, which means it’s not fault tolerant. The method called by `serve.run` is the [deploy_application](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/controller.py#L699) one - which differently from the [deploy_config](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/controller.py#L733) one doesn’t add the application to the kv store and its therefore not fault tolerant. I would assume supporting fault tolerant dynamic apps should be a requirement for a potential solution.

@pedromb makes sense, actually @shrekris-anyscale brought this up as a concern as well. Actually the dynamic apps are already checkpointed to the KV store and are fault tolerant, but there is recovery logic that will delete them _if_ there has been a declarative config applied from the REST API.

So a very minor extension of the above proposal to also update this logic should address the issue.

**Comment by JoshKarpel** [comment]
@edoakes just wanted to check in on this part:

> Whether a Serve app was created via serve.run would also be available in the Serve status API. @edoakes offered to do this change (I'm not very familiar with the Serve internals so it would be harder for me to contribute there, though I'll note that it might be better to have an enum that describes the "source" of the app?). Once that Serve change is made, KubeRay can have another new configuration option that would make it A) not touch applications created by serve.run when it sends config updates, B) not consider applications created by serve.run when determining readiness. This would solve Problem 2. I can contribute this change in KubeRay.

Should I make another ticket for exposing the source in the application status API?

**Comment by edoakes** [comment]
> @edoakes just wanted to check in on this part:
> 
> > Whether a Serve app was created via serve.run would also be available in the Serve status API. @edoakes offered to do this change (I'm not very familiar with the Serve internals so it would be harder for me to contribute there, though I'll note that it might be better to have an enum that describes the "source" of the app?). Once that Serve change is made, KubeRay can have another new configuration option that would make it A) not touch applications created by serve.run when it sends config updates, B) not consider applications created by serve.run when determining readiness. This would solve Problem 2. I can contribute this change in KubeRay.
> 
> Should I make a follow-up issue for exposing the source in the application status API?

Hey Josh, sorry, just getting back from vacation today. Will get back tomorrow, need to noodle on the API change a little bit.

**Comment by JoshKarpel** [comment]
No worries, sounds good! Let me know if you think it's a change that could be made with minimal context, I'd be happy to contribute some code.

**Comment by edoakes** [comment]
@JoshKarpel sounds great, I think this should be fairly straightforward to add, so would be great if you can contribute it.

We'll need to add the field to the [ApplicationStatus](https://github.com/ray-project/ray/blob/8591d1bcd5092e22d1a1a6ca6e96aa2f2fdf5238/python/ray/serve/schema.py#L969) schema and then update the path where we populate it in the controller: https://github.com/ray-project/ray/blob/8591d1bcd5092e22d1a1a6ca6e96aa2f2fdf5238/python/ray/serve/_private/controller.py#L880.

Let's call the field "source" and move the existing enum I added in the previous PR to `schema.py` as well. In the field docstring, please mark this as a developer API that is subject to change (I do not want to commit to supporting it outside of KubeRay's usage right now).
