### ISSUE TITLE
Official Ray Docker image Error on Raspberry Pi

### ISSUE THREAD

**Issue by psytron** [ray-project/ray#44253]
### What happened + What you expected to happen

The official rayproject/ray docker image does not start on Raspberry Pi 

### Versions / Dependencies

Debian Bookworm:
Release date: March 15th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)

Docker: latest Docker version 26.0.0
Image: Official: rayproject/ray

### Reproduction script

To reproduce on Raspberry Pi run:
```
docker run -it rayproject/ray /bin/bash
```
Observe Error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

exec /bin/bash: exec format error
```

Container does not start.

### Issue Severity

None

**Comment by wingkitlee0** [comment]
Have you tried to use platform-specific image? see https://hub.docker.com/r/rayproject/ray/tags?page=1&name=cpu-aarch64
You may need to remove your current local image before pulling the new one. There are also some docker env variables to force using the ARM platform image.

**Comment by psytron** [comment]
Yes that tagged image works. Thanks @wingkitlee0
