### ISSUE TITLE
[Ray Init Is Failed] Ray CAN NOT start in a Big Machine 

### ISSUE THREAD

**Issue by duihuhu** [ray-project/ray#44296]
### What happened + What you expected to happen

1) I meet some bug in a  machine which has 192 CPUs. It does not occur in the another machine which has 64 CPUs. How can I do it ?

some bug information:
2)Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet.
[2024-03-26 09:34:50,573 E 1801210 1801210] logging.cc:97: Unhandled exception: St12system_error. what(): Resource temporarily unavailable
E0326 09:34:50.573117857 1801211 thd.cc:157]                           pthread_create failed: Resource temporarily unavailable

3)
pip3 install ray=2.9.3(2.10.0 also has it problem)
python3 test.py(which only has two line)

4)ulimit -a:
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 8255135
max locked memory       (kbytes, -l) 8192
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

### Versions / Dependencies

2.9.3

### Reproduction script

import ray
ray.init()

### Issue Severity

High: It blocks me from completing my task.

**Comment by lzy37ld** [comment]
Hey, bump into the same issues here. Wonder any suggestions?
