### ISSUE TITLE
[Data] read_json -> pyarrow has no attribute json

### ISSUE THREAD

**Issue by OtjuGit** [ray-project/ray#44294]
### What happened + What you expected to happen

Trying to load dataset from a json file:
Results in: AttributeError: module 'pyarrow' has no attribute 'json'

Possible fix in ray/data/datasource/json_datasource.py

line 44: import pyarrow as pa -> import pyarrow.json as pa
line 66: yield pa.json.read_json -> pa.read_json

### Versions / Dependencies

Ray: 2.10
Python: 3.10
OS: Windows

### Reproduction script

from ray.data.read_api import read_json
dataset = read_json("/dataset.json").materialize()

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by c21** [comment]
You may be using a too old PyArrow version. See https://arrow.apache.org/docs/python/json.html .
