### ISSUE TITLE
Docs page malformed on Chrome on iPhone

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#44346]
### Description

Docs page malformed on Chrome on iPhone
![image](https://github.com/ray-project/ray/assets/116198444/7a4323a6-5cfb-4d5b-860e-54f59da518c0)

**Comment by angelinalg** [comment]
Adding @aslonnie as an assignee as REEf will decide how to prioritize support of the mobile experience. Thanks for reporting.

**Comment by peytondmurray** [comment]
Confirmed this only happens on chrome, not firefox. The culprit is the background color gradient eating up space, `.bd-content::after`.

**Comment by peytondmurray** [comment]
Closed by https://github.com/ray-project/ray/pull/43545.
