### ISSUE TITLE
[core] If streaming generator callee lost 1 rpc, the caller hangs.

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#44357]
### What happened + What you expected to happen

In CoreWorker::ReportGeneratorItemReturns if the RPC to the caller failed, the streaming actor simply gives up and skip the element in sending, causing an infinite hang in the caller side.

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
Fixed by #47981
