### ISSUE TITLE
[Serve] chaining DeploymentHandle calls not work as expected

### ISSUE THREAD

**Issue by wuxibin89** [ray-project/ray#44354]
### What happened + What you expected to happen

Hi, we have a scenario where we want to chain multiple models with ray serve. With following reproduction script, we expect that Adder and Multiplier are fully pipelined like this:
![chain (1)](https://github.com/ray-project/ray/assets/10410189/b481684b-c006-44d3-8fe6-584d85eec3dd)

However, we observe that only the first request is pipelined while subsequent requests are blocked by `Adder`. We can see that requests 1~9 in Adder took 10s to finish, which block `Multiplier` to move on.
```bash
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:18:52,844 default_Adder qi76ahh6 2c775397-ece7-4d0e-a814-f80055af694d replica.py:366 - __CALL__ OK 1004.0ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:18:53,858 default_Multiplier sniawzyr 2c775397-ece7-4d0e-a814-f80055af694d replica.py:366 - __CALL__ OK 1006.0ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:18:53,859 default_Ingress 56u1aznz 2c775397-ece7-4d0e-a814-f80055af694d replica.py:366 - __CALL__ OK 2037.5ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,877 default_Adder qi76ahh6 da69e718-fdd0-4d40-ab07-5ab2ae21db6c replica.py:366 - __CALL__ OK 10036.7ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,878 default_Adder qi76ahh6 cc030961-8fc1-41c5-b767-a027d6e7b578 replica.py:366 - __CALL__ OK 10037.1ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,878 default_Adder qi76ahh6 e02e2004-7152-4778-805f-f13aa8185b34 replica.py:366 - __CALL__ OK 10037.1ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,878 default_Adder qi76ahh6 95677d87-1ea0-4f3d-b2f8-6d1dc0bb0e31 replica.py:366 - __CALL__ OK 10036.6ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,879 default_Adder qi76ahh6 27149064-8929-49bf-bff7-7c07e56dc4b2 replica.py:366 - __CALL__ OK 10036.7ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,879 default_Adder qi76ahh6 6d710e20-c28e-4488-83d3-086fc0d23626 replica.py:366 - __CALL__ OK 10036.8ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,879 default_Adder qi76ahh6 1afa7848-328a-49cd-af97-834fbf4e1aef replica.py:366 - __CALL__ OK 10036.5ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,879 default_Adder qi76ahh6 a42b44ae-592d-4bdd-baab-4b8242890232 replica.py:366 - __CALL__ OK 10036.6ms
(ServeReplica:default:Adder pid=94821) INFO 2024-03-29 20:19:01,880 default_Adder qi76ahh6 c4ae8079-4043-4537-a03c-9b576edade58 replica.py:366 - __CALL__ OK 10036.6ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:02,886 default_Multiplier sniawzyr da69e718-fdd0-4d40-ab07-5ab2ae21db6c replica.py:366 - __CALL__ OK 1005.9ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:02,888 default_Ingress 56u1aznz da69e718-fdd0-4d40-ab07-5ab2ae21db6c replica.py:366 - __CALL__ OK 11065.6ms
elapsed time: 19.11954092979431
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,922 default_Multiplier sniawzyr cc030961-8fc1-41c5-b767-a027d6e7b578 replica.py:366 - __CALL__ OK 9040.8ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,922 default_Multiplier sniawzyr e02e2004-7152-4778-805f-f13aa8185b34 replica.py:366 - __CALL__ OK 9040.6ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,923 default_Multiplier sniawzyr 95677d87-1ea0-4f3d-b2f8-6d1dc0bb0e31 replica.py:366 - __CALL__ OK 9040.3ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,923 default_Multiplier sniawzyr 27149064-8929-49bf-bff7-7c07e56dc4b2 replica.py:366 - __CALL__ OK 9040.3ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,924 default_Multiplier sniawzyr 6d710e20-c28e-4488-83d3-086fc0d23626 replica.py:366 - __CALL__ OK 9040.5ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,924 default_Multiplier sniawzyr 1afa7848-328a-49cd-af97-834fbf4e1aef replica.py:366 - __CALL__ OK 9040.7ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,924 default_Multiplier sniawzyr a42b44ae-592d-4bdd-baab-4b8242890232 replica.py:366 - __CALL__ OK 9040.8ms
(ServeReplica:default:Multiplier pid=94822) INFO 2024-03-29 20:19:10,925 default_Multiplier sniawzyr c4ae8079-4043-4537-a03c-9b576edade58 replica.py:366 - __CALL__ OK 9041.0ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,924 default_Ingress 56u1aznz cc030961-8fc1-41c5-b767-a027d6e7b578 replica.py:366 - __CALL__ OK 19103.2ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,925 default_Ingress 56u1aznz e02e2004-7152-4778-805f-f13aa8185b34 replica.py:366 - __CALL__ OK 19101.3ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,926 default_Ingress 56u1aznz 95677d87-1ea0-4f3d-b2f8-6d1dc0bb0e31 replica.py:366 - __CALL__ OK 19102.4ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,927 default_Ingress 56u1aznz 27149064-8929-49bf-bff7-7c07e56dc4b2 replica.py:366 - __CALL__ OK 19104.7ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,928 default_Ingress 56u1aznz 6d710e20-c28e-4488-83d3-086fc0d23626 replica.py:366 - __CALL__ OK 19105.4ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,929 default_Ingress 56u1aznz 1afa7848-328a-49cd-af97-834fbf4e1aef replica.py:366 - __CALL__ OK 19104.6ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,929 default_Ingress 56u1aznz a42b44ae-592d-4bdd-baab-4b8242890232 replica.py:366 - __CALL__ OK 19105.6ms
(ServeReplica:default:Ingress pid=94823) INFO 2024-03-29 20:19:10,929 default_Ingress 56u1aznz c4ae8079-4043-4537-a03c-9b576edade58 replica.py:366 - __CALL__ OK 19105.2ms
```

@edoakes @zcin

### Versions / Dependencies

ray==2.10.0

### Reproduction script

```python
# File name: chain.py
import time
from ray import serve
from ray.serve.handle import DeploymentHandle, DeploymentResponse


@serve.deployment
class Adder:
    def __init__(self, increment: int):
        self._increment = increment

    def __call__(self, val: int) -> int:
        # simulate compute intensive ops
        time.sleep(1)
        return val + self._increment


@serve.deployment
class Multiplier:
    def __init__(self, multiple: int):
        self._multiple = multiple

    def __call__(self, val: int) -> int:
        # simulate compute intensive ops
        time.sleep(1)
        return val * self._multiple


@serve.deployment
class Ingress:
    def __init__(self, adder: DeploymentHandle, multiplier: DeploymentHandle):
        self._adder = adder
        self._multiplier = multiplier

    async def __call__(self, input: int) -> int:
        adder_response: DeploymentResponse = self._adder.remote(input)
        # Pass the adder response directly into the multipler (no `await` needed).
        multiplier_response: DeploymentResponse = self._multiplier.remote(
            adder_response
        )
        # `await` the final chained response.
        return await multiplier_response


app = Ingress.bind(
    Adder.bind(increment=1),
    Multiplier.bind(multiple=2),
)

handle: DeploymentHandle = serve.run(app)

start_time = time.time()
results = [handle.remote(i) for i in range(10)]
for result in results:
    result.result()
end_time = time.time()
print(f"elapsed time: {end_time-start_time}")

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by shrekris-anyscale** [comment]
Thanks for submitting this @wuxibin89. I was able to validate your repro. I'm taking a look.

**Comment by alexeykudinkin** [comment]
@wuxibin89 i've run some experiments over the weekend and here are the conclusions: 

1. This is not a Ray Core issue: event-loop could *NOT* be blocked even if you offload your blocking activities into a separate Actor (blocking it just lead to unexpected side-effects like the one you observe in this issue)

2. Right approach to handling it is to offload *any* activity taking considerable amount of wall-clock time to complete (uninterrupted) and execute it in executor (using `loop.run_in_executor`) like you'd normally do in any async web app

So in this case if you run experiments @shrekris-anyscale provided above like following you'd get a) same behavior as sync implementation and b) see the pipelining you're expecting:

```
import time

import ray

ray.init()

@ray.remote
class Inner:

    def __init__(self):
        self.executor = ThreadPoolExecutor(1)

    async def run(self):
        start_time = time.time()

        # Code blocking I/O should be offloaded to an TPE
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(self.executor, time.sleep, 1)

        end_time = time.time()
        print(f"Inner call finished: {(end_time - start_time):.2f}s")

@ray.remote
class Outer:

    def __init__(self, inner_handle):
        self.inner_handle = inner_handle

    async def run(self):
        start_time = time.time()
        await self.inner_handle.run.remote()
        end_time = time.time()
        print(f"Outer call finished: {(end_time - start_time):.2f}s")

outer = Outer.remote(Inner.remote())
calls = [outer.run.remote() for _ in range(10)]
ray.get(calls)
```

**Comment by alexeykudinkin** [comment]
And here's the correct output code above produces:

```
2024-04-01 10:40:39,594	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
[2024-04-01 10:40:39,596 I 76194 57421105] logging.cc:234: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet) [2024-04-01 10:40:40,040 I 76218 57421351] logging.cc:234: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet) [2024-04-01 10:40:40,346 I 76220 57421856] logging.cc:234: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(raylet) [2024-04-01 10:40:40,395 I 76221 57421870] logging.cc:234: Set ray log level from environment variable RAY_BACKEND_LOG_LEVEL to -1
(Inner pid=76220) Inner call finished: 1.01s
(Outer pid=76221) Outer call finished: 1.08s
(Inner pid=76220) Inner call finished: 2.01s
(Outer pid=76221) Outer call finished: 2.01s
(Inner pid=76220) Inner call finished: 3.01s
(Outer pid=76221) Outer call finished: 3.02s
(Inner pid=76220) Inner call finished: 4.01s
(Outer pid=76221) Outer call finished: 4.02s
(Inner pid=76220) Inner call finished: 5.02s
(Outer pid=76221) Outer call finished: 5.02s
```

**Comment by wuxibin89** [comment]
@alexeykudinkin Thanks for your reply. I agree that any blocking code in async actor should be executed in a separate thread, that's how serve replica do. But the blocking still exists, so I suspect there maybe some problem in async actor's scheduling control loop.
https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/replica.py#L766-L785

**Comment by alexeykudinkin** [comment]
@wuxibin89 we can't replace `run_coroutine_threadsafe` with just `run_in_executor` b/c this code-path executes both sync and async methods

**Comment by alexeykudinkin** [comment]
To circle back on what we believe the real issue to be here:

## Non-issue

Invoking long-running, uninterrupted code inside _async_ methods is problematic whether you're using Ray or not (you will observe similar side-effects in any other frameworks like FastAPI for ex as well)

## Issue

However, if you declare method as _sync_, but your Ray Actor is actually _async_ (which is the case for Serve actors) all of the methods to be converted to be _async_ using `sync_to_async` utility ([REF](https://github.com/ray-project/ray/blob/6d53139e9e5bd65b1c1a80a5fe27215edb97a746/python/ray/_private/async_compat.py#L35)). 

Problem with this utility is that it's naively converting opaque sync code into async in an unsafe manner: in cases when sync code block is a long-running one (`time.sleep` in your example) this means that the event-loop running it will be blocked for arbitrary long periods of time potentially compromising other operations through so called [head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking) of the event-loop's queue.

This could lead to arbitrary side-effects, like for ex, what you're observing with responses seemingly being delayed until the last in the batch completes.

This is the issue we're going to be addressing to avoid this kind of unexpected behavior when combining both async and sync methods inside Ray Actors and Serve Deployments.

**Comment by alexeykudinkin** [comment]
This is a repro script for issue called out above using Ray (async) Actors:

```
import time
import ray

ray.init()


@ray.remote(num_cpus=1)
class Inner:

    # NOTE: It's crucial for Actor to be considered *async*, hence we add phony async method
    #       which is not used in this test
    async def foo(self):
        pass

    # This particular method is *sync* hence doing long-running blocking operation (emulated
    # by time.sleep) is considered ok in this case
    def run(self):
        start_time = time.time()
        time.sleep(1)
        end_time = time.time()
        print(f"Inner call finished: {(end_time - start_time):.2f}s")


@ray.remote(num_cpus=1)
class Outer:

    def __init__(self, inner_handle):
        self.inner_handle = inner_handle

    async def run(self):
        start_time = time.time()
        await self.inner_handle.run.remote()
        end_time = time.time()
        print(f"Outer call finished: {(end_time - start_time):.2f}s")


inner = Inner.remote()
outer = Outer.remote(inner)

calls = [outer.run.remote() for _ in range(5)]
ray.get(calls)

```

**Comment by alexeykudinkin** [comment]
Alright, wanted to give quick update on the state of discussion concerning this issue

 - We will NOT be changing current out-of-the-box behavior in Ray Core: reason for that is that offloading sync methods in async actors to a standalone executor will make code that has been previously thread-safe (since sync actors were executed in the same event-loop threads as async methods) and make it non-thread-safe, which is a breaking change that compromises a lot of code out there that we don't believe is worth risking stability of the existing workloads.

Instead we propose following changes 

 - Update Ray Core docs listing concrete [examples of what side-effects](https://github.com/ray-project/ray/issues/44354#issuecomment-2027490668) could be observed when combining async and sync methods. 
 - Suggestion to users in this case is either a) separate async and sync methods to different actors (so that sync methods aren't executed on the same event-loop or b) offload sync execution to a standalone `ThreadPoolExecutor`

Additionally

 - We'll be making changes in Ray Serve to align it with FastAPI semantics where sync methods are automatically offloaded to standalone `ThreadPoolExecutor` (which is a safe operation unlike in Ray Core)

**Comment by wuxibin89** [comment]
Great! We should be careful to do any break change to Ray Core. To Ray Serve, what if user define sync and async method at the same time (or should we ban this pattern)? Are we gonna offload sync methods to ThreadPoolExecutor and async methods to separate event loop thread, OR offload all sync and async methods to ThreadPoolExecutor?
```python
@serve.deployment
class Adder:
    def __init__(self, increment: int):
        self._increment = increment

    def compute(self, val: int) -> int:
        # simulate compute intensive ops
        time.sleep(1)
        return val + self._increment

    async def incr(self):
        self._increment += 1
        return self._increment


adder = Adder.bind(increment=1)
handle: DeploymentHandle = serve.run(adder)

result = handle.compute.remote(10)
print(f"result: {result.result()}")

result = handle.incr.remote()
print(f"result: {result.result()}")
```

**Comment by edoakes** [comment]
> Great! We should be careful to do any break change to Ray Core. To Ray Serve, what if user define sync and async method at the same time (or should we ban this pattern)? Are we gonna offload sync methods to ThreadPoolExecutor and async methods to separate event loop thread, OR offload all sync and async methods to ThreadPoolExecutor?
> 
> ```python
> @serve.deployment
> class Adder:
>     def __init__(self, increment: int):
>         self._increment = increment
> 
>     def compute(self, val: int) -> int:
>         # simulate compute intensive ops
>         time.sleep(1)
>         return val + self._increment
> 
>     async def incr(self):
>         self._increment += 1
>         return self._increment
> 
> 
> adder = Adder.bind(increment=1)
> handle: DeploymentHandle = serve.run(adder)
> 
> result = handle.compute.remote(10)
> print(f"result: {result.result()}")
> 
> result = handle.incr.remote()
> print(f"result: {result.result()}")
> ```

There will continue to be a single `asyncio` event loop / thread per replica. The sync methods will be run in an executor and the corresponding future will be awaited on the event loop.

**Comment by wuxibin89** [comment]
@edoakes Hi, any progress on this, in which version do we plan to fix this issue？

**Comment by edoakes** [comment]
PR open for it now: https://github.com/ray-project/ray/pull/45466, needs a little refinement. It'll be in next release but disabled by default (as it's a breaking change), then probably enabled by default in the following.
