### ISSUE TITLE
[tune] No attribute `tune.run`

### ISSUE THREAD

**Issue by kunalrdeshmukh** [ray-project/ray#4436]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem
I got below error while executing a ray.tune code - 

AttributeError: module 'ray.tune' has no attribute 'run' 

I faced same issue while importing
`from ray.tune import run` 

hence I went with `import ray.tune as tune`

### Source code / logs

     52     })
     53 scheduler = tune.schedulers.AsyncHyperBandScheduler(reward_attr="val_loss")
---> 54 tune.run(easy_objective,
     55     name="my_exp",
     56     search_alg=algo,

AttributeError: module 'ray.tune' has no attribute 'run

**Comment by richardliaw** [comment]
Can you pip install the latest snapshot of `ray`? (https://ray.readthedocs.io/en/latest/installation.html)

**Comment by kunalrdeshmukh** [comment]
Yes it worked. 
`pip install -U ray `

**Comment by kunalrdeshmukh** [comment]
![image](https://user-images.githubusercontent.com/6230929/54723366-97d90980-4b24-11e9-8897-2108f7abdce3.png)

This is still a problem.

**Comment by richardliaw** [comment]
Please install a snapshot wheel, not the latest release. Thanks!

**Comment by kunalrdeshmukh** [comment]
oh sorry I missed it. This worked.
