### ISSUE TITLE
specifying conda runtime_env using fullpath no longer works

### ISSUE THREAD

**Issue by deepio-oc** [ray-project/ray#44373]
### What happened + What you expected to happen

In earlier version of ray (2.6.3), I was able to specify full path to conda environment to select a specific conda environment. In latest version (2.9.3), I get an error 

`
  File "/usr/conda/lib/python3.10/site-packages/ray/_private/runtime_env/conda.py", line 348, in _create
    raise ValueError(
ValueError: The given conda environment '/usr/conda' from the runtime env {'_ray_commit': '62655e11ed76509b78654b60be67bc59f8f3460a', 'conda': '/usr/conda'} doesn't exist from the output of `conda env list --json`. You can only specify an env that already exists. Please make sure to create an env /usr/conda 
`

"/usr/conda" is present in `conda env list --json`.  This is broken by this PR

https://github.com/ray-project/ray/commit/69ed38b0efbb30576731c84d2886610b1d63ae7d

`envs = [Path(env).name for env in conda_env_list]` line is only checking the last path component and not the full path.

I tried specifying just the last path component but that also does not work. Conda environments created using -p prefix are no longer working.

### Versions / Dependencies

Ray: 2.9.3
Python: 3.10.13

### Reproduction script

```
import ray
ray.init(runtime_env={"conda": "/usr/conda"})
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jrandall** [comment]
This issue affects me as well (ray 2.10.0).

**Comment by jjyao** [comment]
@deepio-oc @jrandall just curious why you want to specify the full path instead of just the name?

**Comment by jjyao** [comment]
@deepio-oc @jrandall could you tell us a bit more why you want to use the fullpath?

**Comment by deepio-oc** [comment]
@jjyao conda allows creating environments using path (-p) or name (-n) option.  In our case, we have some environments using name (in our home directories) (which is on network filesystem) and some environments in /usr/conda (which is on SSD). So we need control on the path where conda envs are created. If I specify path while creating environment, conda does allow specifying name. So in ray.init I can only pass path.

**Comment by jjyao** [comment]
Got it. Thanks for the explanation.
