### ISSUE TITLE
Update for API changes in ARROW-782

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#444]
Just a heads up, I did some API normalization (methods instead of bare member access) in advance of Arrow 0.3, the impact on Ray should be relatively minor: https://github.com/apache/arrow/pull/520

**Comment by robertnishihara** [comment]
That looks good, thanks for the heads up!

**Comment by gdtm86** [comment]
@robertnishihara @pcmoritz - portions of ray have been updated in #461 to reflect API changes in ARROW. Should we go ahead and update in remaining places?

**Comment by robertnishihara** [comment]
What other parts of Ray need to be updated?

**Comment by gdtm86** [comment]
@robertnishihara - based on @pcmoritz 's comment on #461, I thought there might be other places that need to be updated.

> Yes, all the changes should be in the files here:
> https://github.com/ray-project/ray/tree/master/src/numbuf/cpp/src/numbuf
> and here:
> https://github.com/ray-project/ray/tree/master/src/numbuf/python/src/pynumbuf

**Comment by pcmoritz** [comment]
Oh, I think you found all the places that needed to be updated (otherwise ray wouldn't compile against the latest arrow).

**Comment by gdtm86** [comment]
@pcmoritz. That makes sense. I was just confirming. We can then close this case?

**Comment by robertnishihara** [comment]
This was addressed by #464.
