### ISSUE TITLE
Autoscaler resource usage is counted by IP, not unique worker?

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#4441]
It looks like resource usage for an autoscaling cluster is logged by the IP the nodes are on, not by the worker ID.

Resource info reports are generated by IP:

https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/autoscaler.py#L194-L200

These IPs come from a dictionary mapping from the client ID:

https://github.com/ray-project/ray/blob/master/python/ray/monitor.py#L129-L138

So it looks like a single `load_metrics` value probably gets set by each worker that shares the same IP, meaning that not all the resource usage is being accounted for. This hampers autoscaling efforts, because the number of workers are counted correctly, but the usage of only one of the nodes for a given IP is actually logged since they are constantly being overwritten.

When using Ray in a cluster environment, autoscaling is inevitably going to result in multiple workers getting spawned on the same physical cluster node, I would think. Would it be possible to change the `load_metrics` dictionary keys to a unique identifier per worker instead of per IP?

Is there any reason why `client_id` ( https://github.com/ray-project/ray/blob/master/python/ray/monitor.py#L130 ) couldn't be used as the dictionary key instead? As in:

```python
self.load_metrics.update(client_id, static_resources, dynamic_resources)
```

I'm not sure exactly what type `client_id` is, at the moment, but I'm guessing it's possible to make a unique hashable from it?

Edit: should have mentioned that I observed this phenomenon directly:

```
2019-03-20 17:12:24,390 INFO autoscaler.py:395 -- StandardAutoscaler: **** UPDATE LOOOP
2019-03-20 17:12:24,391 INFO autoscaler.py:525 -- ******* TARGET: FRAC: 0.75 | USED: 12.0 | IDEAL NODES: 16 IDEAL WORKERS: 15**************
2019-03-20 17:12:24,391 INFO autoscaler.py:637 -- StandardAutoscaler: 15/15 target nodes (0 pending)
```

I've ssh'd into all the nodes and confirmed that Ray workers were cranking. In this case, there were 4 workers that were spawned on physical cluster nodes that already had a Ray worker running.

**Comment by robertnishihara** [comment]
@zbarry thanks for reporting this, I think what we want is a mapping from `client_id` to "load".

However, there could be some other issues that arise when using more than one "Ray node" per "physical node", e.g., when we try to downscale, we run `ray stop`, which will kill all of the Ray nodes on a given physical node.

Also, we'll try to do the same `setup_commands` multiple times on the same physical node, and those could conflict with each other e.g., if they both try to clone the Ray repository or some library you have or install Python, etc.
