### ISSUE TITLE
Add more pytest flags when running in travis

### ISSUE THREAD

**Issue by williamma12** [ray-project/ray#4442]
I'm opening this issue to, hopefully, start a discussion on what pytest flags and, in turn, what we want displayed on the travis logs. 

Personally, `-v` flag is really helpful when debugging because it let's me know which tests travis failed or was hanging on and allows me to run just one test to try to recreate the issue locally. Without the `-v` flag, I find myself running an entire test file locally to determine which test travis failed on. 

Before we also had a [`-l` flag](https://docs.pytest.org/en/latest/usage.html#modifying-python-traceback-printing), which printed the local variables and I'm not sure how useful that was since I would always run the tests locally before looking at the local and travis traceback to determine the cause of the failing test.

@robertnishihara @ericl @pcmoritz Do you guys have any opinions on this issue and how best to proceed?

**Comment by robertnishihara** [comment]
Note @raulchen already opened  #4430.

**Comment by williamma12** [comment]
Oops nevermind then
