### ISSUE TITLE
Ray Serve docs - reorg Examples page

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#44457]
### Description

@peytondmurray, @akshay-anyscale @angelinalg and I had a discussion on how better to organize the Ray Serve examples page.

Instead of Beginner, Intermediate, Advanced in the current hierarchy of:

Beginner
Serve ML Models
Serve a Stable Diffusion Model
Serve a Text Classification Model
Serve an Object Detection Model

Intermediate
Serve an Inference Model on AWS NeuronCores Using FastAPI
Serve an Inference with Stable Diffusion Model on AWS NeuronCores Using FastAPI
Serve a model on Intel Habana Gaudi
Scale a Gradio App with Ray Serve
Serve a Text Generator with Request Batching
Serve a Chatbot with Request and Response Streaming
Serving models with Triton Server in Ray Serve

Advanced
Serve a Java App

We want to organize it into:

ML Applications
Serve ML Models
Serve a Stable Diffusion Model
Serve a Text Classification Model
Serve an Object Detection Model
Serve a Chatbot with Request and Response Streaming

Integrations
Scale a Gradio App with Ray Serve
Serve a Text Generator with Request Batching
Serving models with Triton Server in Ray Serve
Serve a Java App

AI Accelerators
Serve an Inference Model on AWS NeuronCores Using FastAPI
Serve an Inference with Stable Diffusion Model on AWS NeuronCores Using FastAPI
Serve a model on Intel Habana Gaudi
*Eventual AMD examples and further examples for different AI Accelerator Types

### Link

https://docs.ray.io/en/master/serve/examples.html

**Comment by akshay-anyscale** [comment]
Maybe instead of Model types we call it ML Applications . 
"Serve a Text Generator with Request Batching
Serve a Chatbot with Request and Response Streaming"
should go under that

**Comment by anyscalesam** [comment]
Discussed with @peytondmurray @angelinalg > currently higher priority projects with fixing internal links and raydocs logging
