### ISSUE TITLE
GetAllJobInfo `is_running_tasks` is not returning the correct value when driver starts ray

### ISSUE THREAD

**Issue by sofianhnaide** [ray-project/ray#44459]
### What happened + What you expected to happen

The `is_running_tasks` attribute on `GetAllJobInfo` is not returning the expected value (True) when no ray cluster is started, but it returns the correct value when a cluster is already started.

e.g.

```
import ray

@ray.remote
def f(x):
    import time
    time.sleep(5)
    return 0

ray.get([f.remote(i) for i in range(4)])

```

to reproduce:
1. Run `ray stop -f`
2. Run the script above and query the job API

Actual: while the task are in progress, the `is_running_tasks` flag should be True but it is False.
Expected: It should be True. If you repeat the steps above after pre-starting ray with `ray start --head`. The expected value is returned.

### Versions / Dependencies

2.10

### Reproduction script

import ray

@ray.remote
def f(x):
    import time
    time.sleep(5)
    return 0

ray.get([f.remote(i) for i in range(4)])

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rynewang** [comment]
Can repro. The probe code:

```
import ray

ray.init()

def f():
    client = ray.worker.global_worker.gcs_client
    job_id = ray.worker.global_worker.current_job_id.binary()
    all_job_info = client.get_all_job_info()
    for job_id in all_job_info:
        print(job_id, all_job_info[job_id].is_running_tasks)
        
f()
```

It prints the task running code's status = False, if the cluster is started from within the driver. Should be True.
