### ISSUE TITLE
[Job] Python module imports failing with ModuleNotFound errors after upgrading to Ray 2.10.0 from 2.6.1

### ISSUE THREAD

**Issue by shinysingh** [ray-project/ray#44467]
### What happened + What you expected to happen

I am importing some modules from different packages inside the main python ray job. The imports stopped working after upgrading Ray version from 2.6.1 to 2.10.0. 

### Versions / Dependencies

ray==2.10.0
python==3.8

### Reproduction script

The directory structure is as follows:
```
parent/
parent/folder1/subfolder1/foo.py
parent/folder2/main.py
```
foo.py
```
def method1():
    print("test")
```
main.py:
```
sys.path.append('folder1/subfolder1')
from foo import method1
```
The ray job is submitted as follows:
python3 main.py --runtime-env-json={"working_dir": "$HOME/parent/folder2"}

After upgrading to 2.10.0 the imports fail:
```
RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8/site-packages/ray/thirdparty_files', '/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8/site-packages/ray/_private/workers', '/tmp/ray/session_2024-04-03_15-21-07_932575_97334/runtime_resources/working_dir_files/_ray_pkg_a759fc744087258e', '/Users/shiny/.pyenv/versions/3.8.16/lib/python38.zip', '/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8', '/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8/lib-dynload', '/Users/shiny/.local/lib/python3.8/site-packages', '/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8/site-packages']:

ray::main() (pid=27284, ip=127.0.0.1)
ModuleNotFoundError: No module named 'foo'
```

I have also tried using importlib. This import also worked with Ray 2.6.1 but stopped working with 2.10.0
`
foo = importlib.import_module("folder1.subfolder1.foo")
`
With the following error:
```
ray::process_payload() (pid=32819, ip=127.0.0.1)
  File "/Users/shiny/.pyenv/versions/3.8.16/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle.py", line 457, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'folder1'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
@shinysingh I feel there are some missing parts in your scripts. I tried the following with latest master and seeing it working

main.py
```
import sys

sys.path.append('folder1/subfolder1')
# from folder1.subfolder1.foo import method1  # <- this also works
from foo import method1


method1()
```

and submit the job with 
```
 ray job submit --working-dir $HOME/parent -- python folder2/main.py
```

<img width="1191" alt="image" src="https://github.com/ray-project/ray/assets/7553988/aa6a1d7a-8eb6-48f4-8b41-038eed921665">

Can you double check with your job submit command maybe is pointing to the wrong path?

**Comment by GeneDer** [comment]
I also just tried it on Ray 2.6.1. Perhaps you meant to have `main.py` as the following?

```
import sys
import ray


sys.path.append('../folder1/subfolder1')
from foo import method1

@ray.remote
def run_task():
    method1()

if __name__ == "__main__":
    ray.init()
    
```
For me this works for both Ray 2.6.1 and 2.10.0. Using the one you provided (with or without import sys and ray) doesn't work for either). Also `--runtime-env-json` doesn't do anything in both cases as the script did not take the arg

**Comment by shinysingh** [comment]
I'm using runtime-env-json as shown in the Ray docs here: https://docs.ray.io/en/latest/ray-core/handling-dependencies.html

**Comment by shinysingh** [comment]
Can you tell us what we might be doing wrong here in that case? For us the main.py fails at runtime. Is it possible that the ray worker that executes the remote task doesn't have the module in its sys path?

**Comment by GeneDer** [comment]
Yea, I know that argument exist on `ray job submit` command that's why I suggested to run it that way. If you just run `python3 main.py --runtime-env-json={"working_dir": "$HOME/parent/folder2"}` then nothing is parsing out the arg despite those need to be stringify json   

There was a recent issue related to how sys.path works in Ray 2.10.0 https://github.com/ray-project/ray/issues/44329 But without sorting out how you run the job, it's hard for me to tell if those two are related. This import issue is already fixed at this point, so you can probably try nightly and test if your code works there. 2.11.0 will be cut this Friday and should be out soon thereafter

**Comment by shinysingh** [comment]
Oh I am using `ray job submit`
I also tried using the Python SDK
```
import ray
from ray.dashboard.modules.job.sdk import JobStatus, JobSubmissionClient

client = JobSubmissionClient("http://127.0.0.1:8265")
entrypoint = "python3 main.py"
client.submit_job(
            entrypoint=entrypoint,
            # Working dir
            runtime_env={
                "working_dir": f"${HOME}/parent/folder2",
            }
        )
```

**Comment by GeneDer** [comment]
@shinysingh if you have to use runtime env json, you can run the job like the following
```
ray job submit --runtime-env-json='{"working_dir": "'$HOME'/parent"}' -- python folder2/main.py
                                                                                           ^-- make sure this is interpolated.   ^--- main.py in folder2 in relation to the working_dir

```

And if you are submitting the code with Python SDK similarly you have to make sure the working dir is interpolated and the script is running in relation to the working dir. So maybe try this
```
from ray.dashboard.modules.job.sdk import JobStatus, JobSubmissionClient
import os

client = JobSubmissionClient("http://127.0.0.1:8265")
entrypoint = "python folder2/main.py". <- script at folder2 in relation to the working dir

client.submit_job(
    entrypoint=entrypoint,
    # Working dir
    runtime_env={
        "working_dir": f"{os.environ['HOME']}/parent",  <- getting HOME from env and interpolate the string
    }
)
```

**Comment by shinysingh** [comment]
Looks like this is a Ray 2.10 issue. I'll wait till there's a 2.11.0 release

**Comment by GeneDer** [comment]
Sg, that issue is already resolved tho. 2.11 should be out by Monday.

**Comment by shinysingh** [comment]
What release was it resolved it?

**Comment by GeneDer** [comment]
2.11

**Comment by GeneDer** [comment]
By that I meant it's already in nightly so if you want to test it out early you can 🙃

**Comment by shinysingh** [comment]
Hello, what's the ETA on the release?

**Comment by GeneDer** [comment]
There was some issue with the release, the current estimate is next Monday (4/22) if everything looks good

**Comment by shinysingh** [comment]
Hello, I see that 2.11.0 was released last week: https://github.com/ray-project/ray/releases/tag/ray-2.11.0
I"m not able to use it though.

**Comment by anyscalesam** [comment]
Closing as this has been resolved for a while @shinysingh were you able to grab latest ray and validate the fix?
