### ISSUE TITLE
[tune] tune has no attribute run

### ISSUE THREAD

**Issue by SumNeuron** [ray-project/ray#4448]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **Ray installed from (source or binary)**: pip installed
- **Ray version**: latest
- **Python version**: 3.5+
- **Exact command to reproduce**:

```bash
!pip install ray -q -U
```

```python
import ray
from ray import tune

ray.init()
def tune_wrapper(config, reporter):
    print(config)
    
all_trials = tune.run( #<-- from tune docs
    tune_wrapper,
    config={"momentum": tune.grid_search([0.1, 0.2])}
)
```

```

     4 all_trials = ray.tune.run(
      5     tune_wrapper,
      6     config={"momentum": tune.grid_search([0.1, 0.2])}

AttributeError: module 'ray.tune' has no attribute 'run'
```

### Describe the problem

Just trying to get tune to work and understand a bit more of the docs.

Wanted to print the config to see how it works.

**Comment by ericl** [comment]
Currently, run() is only available in the master build (the docs are a bit ahead of the stable release). You can change the version in the docs site to 0.6.4 and that should show run_experiments() instead.

**Comment by SumNeuron** [comment]
@ericl in the mean time can how can I use the function `run`?

```bash
pip install git+https://github.com/ray-project/ray.git@master
```

throws:

```bash
Collecting git+https://github.com/ray-project/ray.git@master
  Cloning https://github.com/ray-project/ray.git (to revision master) to /tmp/pip-req-build-pst4972c
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-pst4972c/
```

**Comment by SumNeuron** [comment]
@ericl I tried to combine sacred with ray tune but I am getting pickling errors...

https://colab.research.google.com/drive/1aJ3BviXE5k9yLXSd2UbHYQ9KsyV_4h0N#scrollTo=k812KMlNzXoj

**Comment by ericl** [comment]
You can find the latest wheels on this docs page: https://ray.readthedocs.io/en/latest/installation.html

**Comment by richardliaw** [comment]
The link to the latest wheels is here - `run` should be available there. https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master

@SumNeuron Users have gotten Sacred + Tune to work; can you open a new issue if you have a specific error? Thanks.

I'll lock this issue for now.

**Comment by richardliaw** [comment]
I'll close this for now since 0.6.5 has been released on pip.
