### ISSUE TITLE
[Data] Can't disable repartition progress bar

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#44480]
### What happened + What you expected to happen

I configured Ray Data to disable progress bars, but when I repartition I still see a progress bar.

### Versions / Dependencies

61b34ccd5fc3f58aa0aa1953665579ff1afced13

### Reproduction script

```
export RAY_DATA_DISABLE_PROGRESS_BARS=1
export RAY_DATA_VERBOSE_PROGRESS=0
```

```python
import ray

ray.data.range(100_000_000).repartition(10000).materialize()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jrosti** [comment]
This is same issue as
https://github.com/ray-project/ray/issues/44770
since the all AllToAll ops are impacted by this. 

PR https://github.com/ray-project/ray/pull/45136 fixes.

**Comment by c21** [comment]
https://github.com/ray-project/ray/pull/45136 fixed this.
