### ISSUE TITLE
Failed to build with bazel (:boost)

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#4451]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **Ray installed from (source or binary)**: source
- **Ray version**: latest
- **Python version**: 3.6.2
- **Exact command to reproduce**: `bazel build //:ray_pkg -c opt --verbose_failures`

### Describe the problem
Fail to build Ray because it cannot process the Boost dependence. It could because downloading Boost takes too much time (>2min)

### Source code / logs
```
Analysis of target '//:ray_pkg' failed; build aborted: no such package '@boost//': java.io.IOException: Error downloading
```

**Comment by raulchen** [comment]
Could this be due to slow network?  bazel build works well for me.

**Comment by suquark** [comment]
@raulchen Do you know how to adjust the 'download timeout' for bazel?

**Comment by raulchen** [comment]
I don't know. But please note, if you're using a proxy, you need to put the following in your `~/.bazelrc`, otherwise bazel won't pick up the env vars.
```
build --action_env=http_proxy
build --action_env=https_proxy
```
