### ISSUE TITLE
[Doc] Replace the link for "Manage Ray on Anyscale" button

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#44510]
### Description

Change the link to the sign-up form for the Private Preview of Anyscale-hosted Ray Platform.
https://forms.gle/DFin3AzKEDB19uXZ6

cc: @angelinalg

**Comment by aslonnie** [comment]
which/where is this link?

this seems like a content change? why is this related to doc infra?

**Comment by angelinalg** [comment]
This button appears in all the pages so it's in not in the MD files.

**Comment by aslonnie** [comment]
which button do we mean?

**Comment by scottsun94** [comment]
<img width="1712" alt="Screenshot 2024-04-05 at 4 54 09 @aslonnie  src="https://github.com/ray-project/ray/assets/9677264/6410c453-6a54-4e88-a009-2e45e4660385">
@lo

**Comment by aslonnie** [comment]
we want to change that to the form link?

do we want to change the text?

**Comment by aslonnie** [comment]
(ok.. sorry. I missed the issue title..)

**Comment by scottsun94** [comment]
Thx for the tip. Will do next time.
