### ISSUE TITLE
Release test rllib_learning_tests_cql_old_api_stack_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44521]
Release test **rllib_learning_tests_cql_old_api_stack_tf.aws** failed. See https://buildkite.com/ray-project/release/builds/12807#018eb11b-ffc1-4682-b9a2-dc906d1bd2ee for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: ddc00642a5f8b575cb0154678af79b697319cee7 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/980

**Comment by sven1977** [comment]
Old API stack: Release test has been removed. Closing this issue.
