### ISSUE TITLE
Release test rllib_learning_tests_appo_old_api_stack_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44549]
Release test **rllib_learning_tests_appo_old_api_stack_tf.aws** failed. See https://buildkite.com/ray-project/release/builds/12807#018eb90b-5f6f-4fc6-a3e0-943c7659b628 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by can-anyscale** [comment]
This is an old stack tensorflow rllib test so might potentially not a release blocker. I replace the weekly-release-blocker tag with release-blocker and ray 2.11 tag to generate a potential green candidate. We'll make a final decision next week.

**Comment by sven1977** [comment]
Old API stack: Release test has been removed. Closing this issue.
