### ISSUE TITLE
is there a plan that running on windows?

### ISSUE THREAD

**Issue by loveJasmine** [ray-project/ray#4455]

**Comment by raulchen** [comment]
There's already an issue #631 tracking windows support. However, there're still a lot of pending problems.
Closing this issue because it's duplicated. Feel free to reopen if you have more questions.

**Comment by robertnishihara** [comment]
For anyone interested in trying out Ray on Windows, we have experimental support now (at least for Ray core and some (but not all) of the libraries).

You can try the nightly wheels at https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies.

**Comment by mehrdadn** [comment]
Please see [#631](/ray-project/ray/issues/631#issuecomment-648980254) for recent updates on Windows support!
