### ISSUE TITLE
Release test rllib_learning_tests_marwil_old_api_stack_tf.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44553]
Release test **rllib_learning_tests_marwil_old_api_stack_tf.aws** failed. See https://buildkite.com/ray-project/release/builds/12870#018eb9d2-06f2-46e8-a1e4-a73762473aec for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by sven1977** [comment]
Old API stack: Release test has been removed. Closing this issue.
