### ISSUE TITLE
[job] Job log tailer doesn't work with binary data.

### ISSUE THREAD

**Issue by fishbone** [ray-project/ray#44575]
### What happened + What you expected to happen

When job logs are populated, the job supervisor sometimes just doesn't exit due to tailing the logs.
The issue is that if there is `\0` string, it might end up in a dead loop. The file is opened in text format and can't take care of the binary data very well.

### Versions / Dependencies

master

### Reproduction script

```
with open("zero", 'wb') as binfile:
    binfile.write(b'\x00' * 8)

from ray.dashboard.modules.job.utils import file_tail_iterator


for i in file_tail_iterator("zero"):
    pass
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by fishbone** [comment]
There are two ways to fix this one:
1. Fix the file_tail_iterator and escape the characters
2. When writing to the logs, escape it

The 1) might be a better way because it doesn't change what the output from the user side.

**Comment by alexeykudinkin** [comment]
@fishbone we should do both:

1. We need to put extra layers of defense, if any one failed

**Comment by alexeykudinkin** [comment]
Ok, so i've looked at this scenario and i actually don't think there's an issue:

```

from ray.dashboard.modules.job.utils import file_tail_iterator


with open("zero", 'wb') as binfile:
    binfile.write(b'\x00' * 8)


for i in file_tail_iterator("zero"):
    print(f">>> Read: {i}\n")
```

Will continuously spit out:

```
(ray) ➜  ray git:(master) ✗ python test.py | head -n 10
>>> Read: ['\x00\x00\x00\x00\x00\x00\x00\x00']

>>> Read: None

>>> Read: None

>>> Read: None

>>> Read: None

...
```

Looking at the `file_tail_iterator` it seems like it's actually designed to never return and continuously try to tail logs from the file, while its callers are expected to handle that by handling the cases when `None` is returned

**Comment by alexeykudinkin** [comment]
So real fix here is actually just make sure that once we reach the end of file we should not loop continuously but instead do interrupts to avoid burning CPU cycles unnecessarily.

**Comment by alexeykudinkin** [comment]
Closing in favor of https://github.com/ray-project/ray/issues/44659
