### ISSUE TITLE
[rllib] IMPALA on Atlantis Min, Max and Mean Stay Constant

### ISSUE THREAD

**Issue by jincongho** [ray-project/ray#4460]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.7.dev
- **Python version**: 3.6.8

### Describe the problem

IMPALA for Atlantis running using Atari-impala.yaml configuration produce weird performance. The mean stuck at a level, but min and max also stuck (possibly seems buggy).

![performance](https://i.ibb.co/n33NSgN/a.png)

**Comment by ericl** [comment]
Are the number of episodes increasing?

**Comment by jincongho** [comment]
Yes, you pointed out the issue! It is not increasing. What could potentially cause this?
I have run twice to verify the problem.

![episode](https://i.ibb.co/m03Bdqw/b.png)

**Comment by ericl** [comment]
Well, one possibility is the agent becomes so good the episode never terminates ;)

... Not sure though, perhaps setting an episode horizon makes sense? I think in papers they usually set something like a few hundred k steps.

**Comment by jincongho** [comment]
Haha, didn't thought of that possibility. I'll try the horizon out.

**Comment by jincongho** [comment]
I think your intuition could be right, I looked at the episode_this_iter.

![episode](https://i.ibb.co/T21Z2Tf/c.png)

However, gym by itself has a max_episode_steps=100000, but this my agent don't have any episode for 4M time steps. How does this relate? Suppose I want to achieve 773355 as in IMPALA paper, how long the horizon I should set so as not to drop episode too soon?

Thanks.

**Comment by ericl** [comment]
Could it a bug that the limit is not respected somehow? I'd try setting
horizon according to the hyperparams in the papers.

I think also they might be evaluating offline without a horizon.
