### ISSUE TITLE
[Data] "Rows Outputted" is 0 in Data dashboard

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#44635]
### What happened + What you expected to happen

I ran the repro script twice and expected to see 10 rows outputted, but instead I saw 0.

<img width="1637" alt="image" src="https://github.com/ray-project/ray/assets/26107013/44b17e41-93f9-40bc-9f82-120cdd5b9f42">

### Versions / Dependencies

2.10

### Reproduction script

```python
import ray
import time


def sleep(row):
    time.sleep(1)
    return row

ray.data.range(10, override_num_blocks=2).map(sleep).materialize()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by nyagah** [comment]
Instacart also reported this issue here: https://anyscaleteam.slack.com/archives/C0298K92YBV/p1712175551286209
