### ISSUE TITLE
[Serve] Passing ray.ObjectRef in any fashion as an argument to DeploymentHandle's method leads to a memory leak  

### ISSUE THREAD

**Issue by emsidorov** [ray-project/ray#44673]
### What happened + What you expected to happen

1. Passing `ray.ObjectRef` as argument or nested argument to `DeploymentHandle`'s method leads to a memory leak
2. Before ray 2.7.0 there were no `DeploymentResponse` and everything worked around `ray.ObjectRef`, so there were now issue in using a composition of `DeploymentHandle`s and `Tasks`. After ray 2.7.0 `DeploymentHandle`s started working with `DeploymentResponse` and compositions of `DeploymentHandle`s and `Tasks` stopped working in cases, when you want to pass `ray.ObjectRef` generated by ray `Task` to a `DeploymentHandle`, it started leaking
3. Object Memory Monitoring for 3 tests (test's setups can be seen in Reproduction Code Section)
   3.1. ![Test 1](https://github.com/ray-project/ray/assets/17572907/114fb8f5-b464-4e40-a888-824988761964)
   3.2. ![Test 2](https://github.com/ray-project/ray/assets/17572907/ab2a33d9-7cfc-49a0-b8ff-9b6fa6bf4538)
   3.3. ![Test 3](https://github.com/ray-project/ray/assets/17572907/c508c111-007b-4019-8faf-8e4894f333ec)

  

### Versions / Dependencies

rayproject/ray:2.10.0-py310-cpu
dependencies:
  - python==3.10.8
  - pip==23.0.1
  - pip:
    - ray[serve]==2.10.0
    - numpy==1.24.2
    - requests==2.28.2
    - fastapi==0.109.2
    - pydantic==1.10.7

### Reproduction script

Application Code

```python
from typing import List, Tuple, Dict, Any
from fastapi import FastAPI, Request
from ray import serve
from ray.serve.handle import DeploymentHandle, DeploymentResponse
import numpy as np
from ray import ObjectRef
import ray

app = FastAPI()

@ray.remote
def generate_array(size: Tuple[int, int, int]) -> np.ndarray:
    image = np.random.random(size)
    return image

@serve.deployment
class GeneratorModule:
    async def __call__(self, size: Tuple[int, int, int]) -> np.ndarray:
        image = np.random.random(size)
        return image
       
@serve.deployment
class ProcessorModule:
    async def __call__(self, image: np.ndarray, power: int) -> np.ndarray:
        image = np.power(image, power)
        return image

@serve.deployment
@serve.ingress(app)
class IngressModule:
    def __init__(self, generator_module: DeploymentHandle, processor_module: DeploymentHandle):
        self.generator_module = generator_module
        self.processor_module = processor_module

    @app.post('/process')
    async def process(self, request: Request) -> Dict[str, Any]:
        request = await request.json()
        if request['test'] == 0: # leaking
            array: ObjectRef = generate_array.remote([512, 512, 512])
        elif request['test'] == 1: # leaking
            array_resp: DeploymentResponse = self.generator_module.remote([512, 512, 512])
            array: ObjectRef = await array_resp._to_object_ref()
        elif request['test'] == 2: # not leaking
            array: DeploymentResponse = self.generator_module.remote([512, 512, 512])
        else:
            raise ValueError(f"Wrong value: {request['test']} for parametr test")
        image_resp: DeploymentResponse = self.processor_module.remote(array, 10)
        image: np.ndarray = await image_resp
        return {'max': image.max()}

app_graph = IngressModule.bind(generator_module=GeneratorModule.bind(), processor_module=ProcessorModule.bind())
```

Post Request Example

```python
response = requests.post(process_address, data=json.dumps({'test': 0}))
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by GeneDer** [comment]
Hi @emsidorov thanks for reporting the issue. This should be fixed by https://github.com/ray-project/ray/pull/43763 and coming out with Ray 2.11 very soon :)

**Comment by edoakes** [comment]
dup of https://github.com/ray-project/ray/pull/43763
