### ISSUE TITLE
[Data] Progress bar doesn't refresh if slow UDF

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#44689]
### What happened + What you expected to happen

I'm running a Ray Data job with a very slow UDF (15+ minutes per block). The progress bar doesn't update, so I'm not sure if Ray Data is just waiting for outputs, or if my program has actually hanged.

### Versions / Dependencies

905ca61afb1e24b876f4c8c17b78c192013b13e4

### Reproduction script

```python
import time

import ray


def sleep(batch):
    time.sleep(60)
    return batch


ray.data.range(10, override_num_blocks=10).map_batches(
    sleep, batch_size=None
).materialize()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by scottjlee** [comment]
@bveeramani just tried this on master, and i think the progress bars do render for me. Could you also try on your end and confirm?

**Comment by bveeramani** [comment]
Yeah, the bars do render.

To clarify, what I'm seeing is the progress bar stuck like this for a minute:
```
2024-06-27 14:34:51,740 INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange->MapBatches(sleep)]
Running 0:   0%|                                                                                   | 0/10 [00:00<?, ?it/s]
- ReadRange->MapBatches(sleep) 1:   0%|                                                            | 0/10 [00:00<?, ?it/s]
```

Whereas I'd like to see the timer increase so I know my program hasn't hanged:
```
2024-06-27 14:34:51,740 INFO streaming_executor.py:109 -- Execution plan of Dataset: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange->MapBatches(sleep)]
Running 0:   0%|                                                                                   | 0/10 [00:01<?, ?it/s]
- ReadRange->MapBatches(sleep) 1:   0%|                                                            | 0/10 [00:01<?, ?it/s]
```

**Comment by scottjlee** [comment]
Related to https://github.com/tqdm/tqdm/issues/861
