### ISSUE TITLE
Combining libarrow/libarrow_io/libarrow_ipc

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#447]
See https://github.com/apache/arrow/pull/516 -- the idea is to make building / linking simpler for users who are only using the core libraries. Since in many cases you would use all of these libraries, I thought it made sense to make them a single library

Figured I would do all the disruptive toolchain changes at once; I don't expect to make it a regular occurrence

**Comment by robertnishihara** [comment]
Addressed by #464.
