### ISSUE TITLE
[rllib] APEX batch replay not working and not using train batch size

### ISSUE THREAD

**Issue by opherlieber** [ray-project/ray#4470]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.14.2
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.4
- **Python version**: 3.6.2
- **Exact command to reproduce**: rllib train -f apex_batch_replay.yaml

### Describe the problem

When enabling batch_replay in APEX, it crashes on the first train step.
Also, I've noticed the batch replay option does not use the 'train_batch_size' value. For example in the attached configuration (sample_batch_size=10/train_batch_size=100 wouldn't it make sense to get 100/10=10 batches of 10 samples each for training each time from the batch replay buffer?)

### Source code / logs

Attached zip with the configuration yaml and log tail
[config_and_log.zip](https://github.com/ray-project/ray/files/3000512/config_and_log.zip)

**Comment by ericl** [comment]
Yes, I think this option is a little half baked at the moment. However you can change this bit of code here to produce a right sized batch: https://github.com/ray-project/ray/blob/c6f15a00576fdafbc5cb379c890839abe2bf407b/python/ray/rllib/optimizers/async_replay_optimizer.py#L356
