### ISSUE TITLE
Bug in setup_ray_cluster API used to setup ray clusters on databricks 

### ISSUE THREAD

**Issue by AkashBais** [ray-project/ray#44766]
### What happened + What you expected to happen

I am trying to setup a vanila ray cluster on databricks using the following code from the [tutorial](https://docs.databricks.com/en/machine-learning/ray-integration.html) 

```
from ray.util.spark import setup_ray_cluster, shutdown_ray_cluster

setup_ray_cluster(
  num_worker_nodes=2,
  num_cpus_per_node=4,
  collect_log_to_path="/dbfs/path/to/ray_collected_logs"
)

```
It gives the following error 
![image](https://github.com/ray-project/ray/assets/22378405/fd69429f-48a3-43ce-842d-8c4c1adae7d1)

By following the error message i added the num_worker_nodes argument to the code. But after adding the argument it says that the exact agrument is removed. How can a removed argument can be required at the same time.
Please let me know if this is expected behivour and If I am doing something wrong .
Thanks  

![image](https://github.com/ray-project/ray/assets/22378405/c113257b-10db-4d04-984d-50693df53fce)

### Versions / Dependencies

I am using 
Databricks Runtime version 13.3 LST
Spark --> 3.4.1
Ray --> '2.10.0'

### Reproduction script

from ray.util.spark import setup_ray_cluster, shutdown_ray_cluster

setup_ray_cluster(
  
  max_worker_nodes = 3,
  min_worker_nodes = 1,
  collect_log_to_path="/dbfs/path/to/ray_collected_logs"
)

setup_ray_cluster(
  
  max_worker_nodes = 3,
  min_worker_nodes = 1,
  num_worker_nodes = 2,
  collect_log_to_path="/dbfs/path/to/ray_collected_logs"
)

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
cc @WeichenXu123 can you take a look at this?

**Comment by WeichenXu123** [comment]
ah, Ray 2.10 changes params:

please see error message: 
<img width="590" alt="image" src="https://github.com/ray-project/ray/assets/19235986/cf3079af-4a99-4295-8527-99f988a0fcfd">

**Comment by AkashBais** [comment]
@WeichenXu123 , yes but if i follow the error message and remove 'num_worker_nodes' another error appears saying  'num_worker_nodes' is a required keyword argument for __setup_ray_cluster() but i am unable to set it as it is removed. I have attached both screenshots in the issue .

**Comment by WeichenXu123** [comment]
@AkashBais I guess you are using databricks runtime 13.3, we have internally patching code issue which causes the issue, recently we warm-fixed it. You can try it again or try on runtime >= 14.x
