### ISSUE TITLE
[TUNE] Install requirements in all hosts?

### ISSUE THREAD

**Issue by iitzco-asapp** [ray-project/ray#4476]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.4
- **Python version**: 3.6

### Describe the problem
When running a tune experiment in a multi-machine cluster, it seems that all requirements must be installed in all hosts. If not, a worker node can raise something like `ModuleNotFoundError: No module named torch`.

**Is this assumption right?**
**Is there an alternative to avoid the need of installing all dependencies in all hosts and install them only in the `head` node?** (If pip installing is just copying files to the `site-packages` folder mainly, a strategy involving rsyncing that folder to the worker nodes could be a possible path to solve this.)

**Comment by richardliaw** [comment]
Yeah, all requirements need to be installed on all hosts. I think for now Ray + Tune should probably avoid handling dependencies.

One option is to use the [Ray autoscaler for setup.](https://ray.readthedocs.io/en/latest/autoscaling.html#quick-start-private-cluster) This should allow you to easily specify installation instructions that are run on all machines of your cluster.

Let me know if that helps

**Comment by iitzco-asapp** [comment]
Yes this helps! Thanks for the answer.
