### ISSUE TITLE
CI test windows://python/ray/tests:test_unavailable_actors is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#44773]
CI test **windows://python/ray/tests:test_unavailable_actors** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/4026#018ee76d-f1d3-491c-a4cb-4f108c12bcde
	- https://buildkite.com/ray-project/postmerge/builds/4008#018ee247-9d9d-44a4-8d13-8e5af3d15693

DataCaseName-windows://python/ray/tests:test_unavailable_actors-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by rynewang** [comment]
should be fixed now

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/4215#018f1df5-a54e-448a-95b6-4e16335211e9
