### ISSUE TITLE
[Data] Ray Data Sort progress bar shown when progress bars are disabled 

### ISSUE THREAD

**Issue by jrosti** [ray-project/ray#44770]
### What happened + What you expected to happen

Sort progress bar is shown although disabling is requested by
`RAY_DATA_DISABLE_PROGRESS_BARS=1 RAY_DATA_VERBOSE_PROGRESS=0`

### Versions / Dependencies

2.10.0

### Reproduction script

See progress bar appearing here.
```
RAY_DATA_DISABLE_PROGRESS_BARS=1 RAY_DATA_VERBOSE_PROGRESS=0 python -c 'import ray.data as rd; rd.from_items(range(10**6)).sort("item").show(1)'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@jrosti would you be willing to contribute to fix this issue; we can pair you with an Anyscaler to help shepherd a PR through.

**Comment by jrosti** [comment]
> @jrosti would you be willing to contribute to fix this issue; we can pair you with an Anyscaler to help shepherd a PR through.

Sure, I can do the PR!

**Comment by anyscalesam** [comment]
Cool! Please link the PR to this issue when cut and label it with "data" "triage". @jrosti

**Comment by jrosti** [comment]
@anyscalesam it is now in review, but I did not have permissions to add labels.
