### ISSUE TITLE
[Serve] Allow Serve apps to not be exposed over HTTP

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/ray#44809]
### Description

When creating a Serve app, allow setting
```python
serve.run(..., route_prefix=None)
```
which would tell Serve that this app should not be registered in the HTTP proxy at all.

### Use case

Discussed here: https://ray-distributed.slack.com/archives/CNCKBBRJL/p1713375031622729?thread_ts=1713194071.772759&cid=CNCKBBRJL

When creating Serve apps dynamically, we might not want them to be exposed over HTTP. This has a few benefits:

- API design: a developer might want to explicitly control which of their Serve apps are exposed or not exposed over HTTP.
- Performance: the Serve HTTP Proxy needs to know about all apps so that it can route requests to them. Adding extra applications that requests will never be routed to requires the proxy to hold more `DeploymentHandle`s https://github.com/ray-project/ray/blob/5902af8475af478a0f7a9fa660876ffe85ecb99b/python/ray/serve/_private/proxy_router.py#L66, and to check more routes when doing prefix matching https://github.com/ray-project/ray/blob/5902af8475af478a0f7a9fa660876ffe85ecb99b/python/ray/serve/_private/proxy_router.py#L100 .

**Comment by JoshKarpel** [comment]
@edoakes question: above I've only described how it would work for `serve.run`. I haven't looked at the code yet, but I assume that it'll need be to allowed in more places, like from a static Serve config file?

**Comment by edoakes** [comment]
> @edoakes question: above I've only described how it would work for `serve.run`. I haven't looked at the code yet, but I assume that it'll need be to allowed in more places, like from a static Serve config file?

We can do the same in the config file:
```yaml
   route_prefix: null
```

**Comment by JoshKarpel** [comment]
Great news! As far as I can tell, this actually already works, and is sort-of documented here: https://github.com/ray-project/ray/blob/e4cb2feeee33cd24728ddb2ebded954863d59626/python/ray/serve/schema.py#L979-L981
 

And indeed, passing `route_prefix=None` to `serve.run` or setting `route_prefix: null` in a Serve config file does the right thing:
```python
import time

import requests
from ray import serve

@serve.deployment()
class D:
    async def __call__(self, *args, **kwargs):
        return "Hello, world!"


d = D.bind()

if __name__ == "__main__":
    serve.run(d, route_prefix=None)
    time.sleep(5)
    print(requests.get("http://localhost:8000/-/routes").json())  # {} 
    print('sleeping...')
    time.sleep(100000)
```
```
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
  - name: d
    route_prefix: null
    import_path: serve:d
```

It looks like the join point between the controller state and what the proxy ends up seeing is https://github.com/ray-project/ray/blob/7e315fe7e5ddc5b9ebec0fc50bd0e1d4fa28d621/python/ray/serve/_private/application_state.py#L344-L361 , and it implicitly handles deployments without `route_prefix`es, not caring whether they are ingress deployments for not.

Perhaps this was done for gRPC support? So that gRPC ingress didn't also imply an HTTP ingress route? https://github.com/ray-project/ray/blob/b3b79d2a27814392b22beca7d3100e3e8b108233/doc/source/serve/advanced-guides/grpc-guide.md#L141-L142

It's even tested! https://github.com/ray-project/ray/blob/b074a2f24443f50556479fff608e3f54c274a141/python/ray/serve/tests/test_http_routes.py#L74-L86

The main thing that's wrong seems to be the typing of the `route_prefix` argument - I'll take care of that, and poke around for any docs adjacent to the `route_prefix` that should discuss this.
