### ISSUE TITLE
carla.tcp.TCPConnectionError

### ISSUE THREAD

**Issue by Deepak3994** [ray-project/ray#4480]
I am running Ray on my local system, but i am facing the below error.

(pid=21716) Traceback (most recent call last):
(pid=21716)   File "/home/ubuntu/ray/python/ray/rllib/examples/carla/carla_env.py", line 321, in step
(pid=21716)     obs = self.step_env(action)
(pid=21716)   File "/home/ubuntu/ray/python/ray/rllib/examples/carla/carla_env.py", line 347, in step_env
(pid=21716)     reverse=reverse)
(pid=21716)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/client.py", line 145, in send_control
(pid=21716)     self._control_client.write(pb_message.SerializeToString())
(pid=21716)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/tcp.py", line 69, in write
(pid=21716)     self._reraise_exception_as_tcp_error('failed to write data', exception)
(pid=21716)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
(pid=21716)     raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
(pid=21716) carla.tcp.TCPConnectionError: (localhost:53755) failed to write data: [Errno 32] Broken pipe
(pid=21716) 
(pid=21716) Clearing Carla server state
(pid=21716) Initializing new Carla server...
(pid=21716) ERROR: tcpserver 53753 : error reading message: End of file 
(pid=21713) Error during step, terminating episode early Traceback (most recent call last):
(pid=21713)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/tcp.py", line 67, in write
(pid=21713)     self._socket.sendall(header + message)
(pid=21713) BrokenPipeError: [Errno 32] Broken pipe
(pid=21713) 
(pid=21713) During handling of the above exception, another exception occurred:
(pid=21713) 
(pid=21713) Traceback (most recent call last):
(pid=21713)   File "/home/ubuntu/ray/python/ray/rllib/examples/carla/carla_env.py", line 321, in step
(pid=21713)     obs = self.step_env(action)
(pid=21713)   File "/home/ubuntu/ray/python/ray/rllib/examples/carla/carla_env.py", line 347, in step_env
(pid=21713)     reverse=reverse)
(pid=21713)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/client.py", line 145, in send_control
(pid=21713)     self._control_client.write(pb_message.SerializeToString())
(pid=21713)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/tcp.py", line 69, in write
(pid=21713)     self._reraise_exception_as_tcp_error('failed to write data', exception)
(pid=21713)   File "/home/ubuntu/CARLA_0.8.4/PythonClient/carla/tcp.py", line 97, in _reraise_exception_as_tcp_error
(pid=21713)     raise TCPConnectionError('%s%s: %s' % (self._logprefix, message, exception))
(pid=21713) carla.tcp.TCPConnectionError: (localhost:17197) failed to write data: [Errno 32] Broken pipe

Kindly help..

**Comment by robertnishihara** [comment]
Looks like an error with Carla. You could try running with `ray.init(local_mode=True)` to see if the error can be debugged more easily.
