### ISSUE TITLE
[Tune] Broken Pipe error

### ISSUE THREAD

**Issue by jeremyasapp** [ray-project/ray#4482]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.4
- **Python version**: 3.6.5
- **Exact command to reproduce**: N/A

### Describe the problem

We are seeing a series of "Broken Pipe" errors, whenever we use more than a single factory machine. We haven't been able to identify the source of the error further than this. Note that the following stack trace prints many times during training, but somehow checkpoints and logs seem to end up syncing ok (not 100% of this yet), so it may be that Tune tries it again, and succeeds, or that this bug doesn't affect syncing in general.

Thanks in advance for your help!!

### Source code / logs
(pid=11478, ip=10.150.0.21) Traceback (most recent call last):
(pid=11478, ip=10.150.0.21)   File "/usr/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
(pid=11478, ip=10.150.0.21)     send_bytes(obj)
(pid=11478, ip=10.150.0.21)   File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
(pid=11478, ip=10.150.0.21)     self._send_bytes(m[offset:offset + size])
(pid=11478, ip=10.150.0.21)   File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
(pid=11478, ip=10.150.0.21)     self._send(header + buf)
(pid=11478, ip=10.150.0.21)   File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
(pid=11478, ip=10.150.0.21)     n = write(self._handle, buf)
(pid=11478, ip=10.150.0.21) BrokenPipeError: [Errno 32] Broken pipe

**Comment by jeremyasapp** [comment]
We've identified that the problem was on our end. Sorry about that.

**Comment by YuhangSong** [comment]
Hi Jeremy,

I encounter this also, but it does not seem to affect anything. What is the problem you identified and does this damage the results?

**Comment by jwohlwend** [comment]
Hi Yuhang, unfortunately I can't quite recall what the issue was but if I do remember I'll make sure to message back here. Good luck

**Comment by YuhangSong** [comment]
That will be great, thanks a lot!

Yuhang Song | Doctoral Student
Computer Science, University of Oxford
Email: Yuhang.Song@some.ox.ac.uk
Home: https://sites.google.com/view/yuhangsong/
