### ISSUE TITLE
[Data]  Does map_batches support runtime_env settings?

### ISSUE THREAD

**Issue by v4if** [ray-project/ray#44833]
### Description

In the scenario of offline batch processing tasks through ray.data, multiple operations may require different runtime environments. Is it supported to set the container environment through runtime_env?Similar to ray core's handling-dependencies documentation.

[handling-dependencies
](https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#api-reference)

<img width="1102" alt="image" src="https://github.com/ray-project/ray/assets/16042235/0118f429-f9d0-4af1-b0cc-286a63fdb3ef">

### Use case

There are multiple processing operators, and the operating environments are quite different. The operating environments need to be isolated through mirroring.

**Comment by bveeramani** [comment]
If it's supported by Ray Core, I can't think of any reason why this wouldn't work with the `ray_remote_args` argument of `Dataset.map_batches`.

What happens when you specify a `container`? Does it work as expected?

**Comment by v4if** [comment]
> If it's supported by Ray Core, I can't think of any reason why this wouldn't work with the `ray_remote_args` argument of `Dataset.map_batches`.
> 
> What happens when you specify a `container`? Does it work as expected?

tks. It works with `ray_remote_args `.
