### ISSUE TITLE
Ray v2.11.0 missing windows distribution

### ISSUE THREAD

**Issue by amirebrahimi** [ray-project/ray#44879]
### What happened + What you expected to happen

It looks like Windows binaries were not built/released with the latest Ray version?

### Versions / Dependencies

Ray v2.11.0
Python 3.9
Windows 10

### Reproduction script

`pip install ray==2.11.0` on Windows

### Issue Severity

High: It blocks me from completing my task.

**Comment by RocketRider** [comment]
I have the same issue. Tried to install with pip and poetry.

**Comment by anyscalesam** [comment]
@amirebrahimi @RocketRider - windows distros will be released as part of the full release versions on a ~6w cycle (denoted with 2.20, 2.30 etc) with the next one targeting early May.

**Comment by amirebrahimi** [comment]
Thanks for clarifying. I take that this will affect many people as it will be difficult to include version ranges in `pyproject.toml` now.

**Comment by anyscalesam** [comment]
@amirebrahimi this is a good point; are y'all on Windows and want to support a devex for your team where you want just >= than some version. does defaulting to latest or pinning to an explicit version work?

**Comment by amirebrahimi** [comment]
@anyscalesam - we utilize both Windows and Linux machines. We use poetry, so were setting the version to `^2.0.0`, which is equivalent to `>=2.0.0,<3`, but now have to use `~2.10.0`, which limits us to patch versions (i.e. `>=2.10.0,<2.11.0`)

**Comment by amirebrahimi** [comment]
It would be great if version solving would see that there are no Windows binaries for `2.11.0` and fallback to `2.10.0`, but it doesn't work that way. It only sees what versions are available.

**Comment by RocketRider** [comment]
Why can't you release the patch versions for windows? It would make it much easier. 

For example we are using the windows version locally but do use the linux version on our servers.

**Comment by amirebrahimi** [comment]
~Is this still true? It seems that ray is now getting windows builds regularly.~

Nevermind, I found #44276
