### ISSUE TITLE
Implement support for OpenCL

### ISSUE THREAD

**Issue by BnJam** [ray-project/ray#4487]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.3
- **Ray installed from (source or binary)**: pip package
- **Ray version**: 0.6.2
- **Python version**: 3.7.2
- **Exact command to reproduce**: N/A

### Problem
There is only support for CUDA enabled devices. OpenCL should be implemented to allow for a larger range of non-CUDA compatible devices to run Ray locally and to it's full effectiveness.

**Comment by pcmoritz** [comment]
Thanks! This would be a great addition. I'm not familiar with OpenCL, is there a command line variable like CUDA_VISIBLE_DEVICES we could set to make this work?

If you can submit a PR that'd be great!

https://github.com/ray-project/ray/search?q=CUDA_VISIBLE_DEVICES&unscoped_q=CUDA_VISIBLE_DEVICES
