### ISSUE TITLE
[Observability / Doc] Add support of ray debugger on windows 

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#44902]
### Description

According to https://discuss.ray.io/t/solution-found-using-rays-debugger-on-windows/14474, users need to modify the source code for ray debugger to work on windows.

1. We should just make it work on windows (it seems a trivial change)
2. if we don't get time to do 1, update the doc to clarify the limitation.

**Comment by scottsun94** [comment]
@anyscalesam

**Comment by OpenCoderX** [comment]
Nice, I came here to propose my own very similar fix to the _connect_pdb_client function, i've been using a locally patched version for a few weeks and have not found an issue. I'm glad to see a windows fix come in.

**Comment by JiangpengLI86** [comment]
Hi @OpenCoderX,

Have you tried my solution on your Windows PC? This modified function works on my computer, but I am not sure about the others.

Regards,

JL

**Comment by OpenCoderX** [comment]
I'll test your version.

**Comment by anyscalesam** [comment]
@mattip this seems related to the rpdb cross platform problem we discussed earlier in the morning; can you confirm? than prioritize to work on it after the 3-4 items we discussed.

**Comment by mattip** [comment]
The suggested change is this, which should also fix the previously mentioned #37145. I will turn this into a PR. Is this code tested?
```diff
diff --git a/python/ray/util/rpdb.py b/python/ray/util/rpdb.py
index e6a9769966..c5979d2c88 100644
--- a/python/ray/util/rpdb.py
+++ b/python/ray/util/rpdb.py
@@ -338,16 +338,24 @@ def _post_mortem():
 
 
 def _connect_pdb_client(host, port):
+    if sys.platform == 'win32':
+        import msvcrt
+
     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
     s.connect((host, port))
 
     while True:
         # Get the list of sockets which are readable.
-        read_sockets, write_sockets, error_sockets = select.select(
-            [sys.stdin, s], [], []
+        if sys.platform == 'win32':
+            ready_to_read = select.select([s], [], [], 1)[0]
+            if msvcrt.kbhit():
+                ready_to_read.append(sys.stdin)
+        else:
+            ready_to_read, write_sockets, error_sockets = select.select(
+                [sys.stdin, s], [], []
         )
 
-        for sock in read_sockets:
+        for sock in ready_to_read:
             if sock == s:
                 # Incoming message from remote debugger.
                 data = sock.recv(4096)
```

**Comment by anyscalesam** [comment]
merge it! :) @mattip

**Comment by mattip** [comment]
> Is this code tested?

This is tested in `test_ray_debugger_commands`, `test_ray_debugger_stepping`, and `test_ray_debugger_recursive` in `python/ray/tests/test_ray_debugger.py`. They are currently skipped on windows. I see they use pexpect.spawn, which [does not work on windows](https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows). I will see if I can get the alternative mentioned in the documentation, with many caveats, to work.
