### ISSUE TITLE
[tune] `tune.with_resources` with `PlacementGroupFactory` cannot find GPUs in `train_fn`

### ISSUE THREAD

**Issue by klarsdb** [ray-project/ray#44914]
### What happened + What you expected to happen

The bug
======

When passing a `ScalingConfig` or a `PlacementGroupFactory` to `tune.with_resources(..., resources=...)`, the `train_fn` is unable to identify GPUs.

Expected behavior
==============
Passing a [`PlacementGroupFactory`](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.with_resources.html) to `tune.with_resources` should correctly result in training with GPUs

Useful information
==============
See submitted reproduction script: only passing a `dict` to `tune.with_resources` actually results in `train_fn` identifying the machine GPUs.

### Versions / Dependencies

I have tried this in `ray=2.7.0` and `ray=2.10.0` on `python=3.11` in a clean environment.

### Reproduction script

```python
#!/usr/bin/env python
import time

import ray
from ray import tune
from ray.train import (
    report,
    ScalingConfig,
)
import torch


def train_fn(config: dict, a: float = 0.1):
    time.sleep(a * 0.2)
    num_gpu = torch.cuda.device_count()
    print(f'In train_fn: {num_gpu=}')
    report({'auc': 0.1, 'num_gpu': num_gpu})


def train():
    num_gpu = torch.cuda.device_count()
    print(f'In train: {num_gpu=}')

    scaling_config = ScalingConfig(
        resources_per_worker={'GPU': 1},
        num_workers=1,
        use_gpu=True,
    )

    tuner = tune.Tuner(
        tune.with_resources(
            train_fn,
            resources={'GPU': 1},      # <- only this way of specifying resources results in "In train_fn: 1"
            # resources=scaling_config,  # should work in 2.7.0 according to the documentation
            # resources=scaling_config.as_placement_group_factory(),
        ),
        param_space={'params': {'a': tune.uniform(0, 1)}},
        tune_config=tune.TuneConfig(num_samples=4),
    )
    results = tuner.fit()


if __name__ == "__main__":
    train()
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by matthewdeng** [comment]
In short, `ScalingConfig` shouldn't be used directly with `tune.with_resources`. This was cleaned up in 2.10 and removed from the supported types.

A longer answer is that the `ScalingConfig` is used for Ray Train, which will have a "controller" that corresponds to `train_fn`. Meanwhile, `resources_per_worker` is used for scheduling _additional_ workers from the controller. Here's a simple example, in which we introduce a `train_remote` task that uses 1 GPU and is called form `train_fn`.

```python
#!/usr/bin/env python
import time

import ray
from ray import tune
from ray.train import (
    report,
    ScalingConfig,
)
import torch

@ray.remote(num_gpus=1)
def train_remote():
    num_gpu = torch.cuda.device_count()
    print(f'In train_remote: {num_gpu=}')

def train_fn(config: dict, a: float = 0.1):
    time.sleep(a * 0.2)
    num_gpu = torch.cuda.device_count()
    print(f'In train_fn: {num_gpu=}')
    ray.get(train_remote.remote())
    report({'auc': 0.1, 'num_gpu': num_gpu})

def train():
    num_gpu = torch.cuda.device_count()
    print(f'In train: {num_gpu=}')

    scaling_config = ScalingConfig(
        resources_per_worker={'GPU': 1},
        num_workers=1,
        use_gpu=True,
    )

    tuner = tune.Tuner(
        tune.with_resources(
            train_fn,
            # resources={'GPU': 1},      # <- only this way of specifying resources results in "In train_fn: 1"
            # resources=scaling_config,  # should work in 2.7.0 according to the documentation
            resources=scaling_config.as_placement_group_factory(),
        ),
        param_space={'params': {'a': tune.uniform(0, 1)}},
        tune_config=tune.TuneConfig(num_samples=1),
    )
    results = tuner.fit()


if __name__ == "__main__":
    train()
```

Output:
```
(train_fn pid=3515, ip=10.0.97.245) In train_fn: num_gpu=0
(train_remote pid=3602, ip=10.0.97.245) In train_remote: num_gpu=1
```

**Comment by klarsdb** [comment]
Clear, so if you want to use a simple `train_fn` not as a "controller" but as a worker, you shouldn't use `ScalingConfig`, nor a `PlacementGroupFactory`, but directly specify the resources as a `dict` which would specify the resources per "instance" of `train_fn`?

**Comment by matthewdeng** [comment]
Yeah if you just want to describe how many resources `train_fn` should take, you should use a `dict`. If you want to schedule more tasks/actors (i.e. workers) from within `train_fn`, you can use a `PlacementGroupFactory` to specify a list of `dict`s.

**Comment by klarsdb** [comment]
Thanks, all clear then!
