### ISSUE TITLE
[rllib] SyncReplayOptimizer no need to require learng_starts < buffer_size

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#4497]
This [assertion](https://github.com/ray-project/ray/blob/master/python/ray/rllib/optimizers/sync_replay_optimizer.py#L72) is unnecessary in my opinion.

1. In some applications, we do want to waste the data at the beginning due to some reasons, e.g., the data are noisy or the pre-processor has to consume a lot of data to estimate some statistics accurately enough.

2. For restored agent, the buffer is empty but `num_sampled_steps` is restored. In this case, we have to set a `learning_starts` as what we want plus current `num_sampled_steps`. This certainly may be larger than the `buffer_size`, e.g., restored from a long trial.

**Comment by ericl** [comment]
Perhaps it can be changed to a warning instead?

**Comment by joneswong** [comment]
Replacing this hard one by a warning would be quite convenient for us.
