### ISSUE TITLE
Ray 2.12.0 not available for aarch64

### ISSUE THREAD

**Issue by SiRumCz** [ray-project/ray#45045]
### Description

the most recent version of ray that supports aarch64 is 2.10.0

**Comment by anyscalesam** [comment]
@aslonnie remind me - do we publish new pip and images for aarch64 in the 20/30/40 release cycles?

**Comment by aslonnie** [comment]
yes we published:

https://pypi.org/project/ray/2.20.0/#files

https://files.pythonhosted.org/packages/d7/a4/4c3367b704c36ebad4a74557ba9912674190dc0e5827ef4eeb6cf08f8c0c/ray-2.20.0-cp311-cp311-manylinux2014_aarch64.whl

**Comment by SiRumCz** [comment]
thanks!

**Comment by SiRumCz** [comment]
Sorry have to reopen this issue, latest 2.22.0 does not have aarch64 :-(

**Comment by aslonnie** [comment]
@SiRumCz could you say more about why you need it?

**Comment by anyscalesam** [comment]
@SiRumCz > FYI we've moved to a weekly release cadence so the reason you don't see previously we would release eg: ray 2.11, ray 2.12 and each of them would have aarch64 images for them every 6w

now we only build for macos and darwin on weekly release and in the new 6w release versions ie: ray 2.20, ray 2.30 we'll publish the aarch64 versions of it as well; so it's just a naming semantic.

is the 6w release cycle which we're sticking to not work out; we're actually not changing anything it's exactly the same cycle just more releases.
