### ISSUE TITLE
Config Does Not Accept Custom Parameters

### ISSUE THREAD

**Issue by kiddyboots216** [ray-project/ray#4505]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.6.5
- **Python version**: 3.7
- **Exact command to reproduce**: 
`run_experiments({
        "test": {
            "run": my_trainable_func,
            "env": multienv_name,
            "config": {
                "multiagent": {
                    "policy_graphs": policy_graphs,
                    "policy_mapping_fn": tune.function(lambda agent_id: f'agent_{agent_id}'),
                },
                "num_iters": 5
            },
            "resources_per_trial": {
                "cpu": 2,
                "gpu": 1,
            },
        }
    })`

### Describe the problem
I am trying to include custom config parameters which my_trainable_func uses, but seem unable to add anything because I get an unknown config parameter error. As per Issue #3160, @ericl has mentioned that many config parameters have been deprecated, but I'm curious to know what the intended way of adding algorithm-specific hyperparameters into the config is.

### Source code / logs
`Traceback (most recent call last):
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 90, in run
(pid=426)     self._entrypoint()
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 141, in entrypoint
(pid=426)     return self._trainable_func(config, self._status_reporter)
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 249, in _trainable_func
(pid=426)     output = train_func(config, reporter)
(pid=426)   File "<ipython-input-13-0b4744367540>", line 103, in fed_train
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/agent.py", line 276, in __init__
(pid=426)     Trainable.__init__(self, config, logger_creator)
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py", line 88, in __init__
(pid=426)     self._setup(copy.deepcopy(self.config))
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/agent.py", line 364, in _setup
(pid=426)     self._allow_unknown_subkeys)
(pid=426)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/util.py", line 89, in deep_update
(pid=426)     raise Exception("Unknown config parameter `{}` ".format(k))
(pid=426) Exception: Unknown config parameter `num_iters` `

**Comment by ericl** [comment]
This is probably since you are subclassing agent? Agent checks that no unknown config keys are present, to avoid typos in your experiment config.

If you want to add a custom key, you can add it to the default config of your custom agent. You can check out any of the existing agent classes for an example of the config.

**Comment by kiddyboots216** [comment]
Ah, to be clear, I was wondering whether there was a way to do this without subclassing Agent ('my_trainable_func' I am trying to Tune a function and not a class).

**Comment by ericl** [comment]
The exception you posted is originating from agent, so you must be calling agent code somehow.

**Comment by kiddyboots216** [comment]
Thanks Eric! Resolved; I was passing in the config (with custom parameters that were specific to my training function) into the Agent without removing the parameters beforehand. Now I know that I need to remove any parameters the Agent can't identify.
