### ISSUE TITLE
[rllib] Clarifying timesteps_per_iteration

### ISSUE THREAD

**Issue by ankeshanand** [ray-project/ray#4506]
Hi, 

I wanted to know more about what the `timesteps_per_iteration` parameter means in context of DQN based agents? Quick glance at the code: https://github.com/ray-project/ray/blob/cff08e19ff1606ef6e718624703e8e0da19b223d/python/ray/rllib/agents/dqn/dqn.py#L257-L261 
suggests that you optimize for  `timesteps_per_iteration` after each env step? That doesn't quite seem right since the default value for `timesteps_per_iteration` is 1000 which seems high . 

Also, does `timesteps_per_iteration` have a different connotation in case of distributed agents like ApeX?

**Comment by ericl** [comment]
This is a system-level parameter, and only affects the (system) performance of your agent. For example, if you set this value too small, then too many result logs may be produced, slowing down training.

The hyperparameter you're probably thinking of is train_batch_size and sample_batch_size: https://ray.readthedocs.io/en/latest/rllib-training.html#specifying-resources, which determine how many steps to sample from the env, and then how many steps to train on from the replay buffer.

Hope that makes sense.

**Comment by SebastianBo1995** [comment]
@ericl Just to clarify if I am wrong. It seems to me that RLLib trains after that ammount of done steps/episodes in the environment. 

For example a training with the following parameters: 
timesteps_per_iteration = 2 
train_batch_size = 32 
epochs = 5 

ends with 5 times Training the Agent and 10 collected Episodes. Then it would be imho not just a system level parameter or am I missing something? 

This means that for training the TD3-Agent for example it uses 2 to up to 32 steps? So after 100 eochs only 32 samples are used for learning? 

Thanks in advance.

**Comment by GoingMyWay** [comment]
Hi, if `timesteps_per_iteration` is not a necessary parameter, could you please delete is in future versions?
