### ISSUE TITLE
Trouble with recursive remote calls

### ISSUE THREAD

**Issue by akamaus** [ray-project/ray#451]
Hi, the following snippet doesn't work for me. Is recursion supported?
```
import ray
ray.init(num_workers=10)

@ray.remote
def async_inc(k):
    if k >= 0:
        r=async_inc.remote(k-1)
        return ray.get(r) + 1
    else:
        return 0

print(ray.get(async_inc.remote(5)))
```

```
RayGetError: Could not get objectid ObjectID(1a3c2e6450938e5226f120e34f7b0e60c45e8809). It was created by remote function __main__.async_inc which failed with:

Remote function __main__.async_inc failed with:

Traceback (most recent call last):
  File "<ipython-input-1-44885ce2c17a>", line 7, in async_inc
NameError: name 'async_inc' is not defined
```

**Comment by robertnishihara** [comment]
Thanks! I'm closing this because it's the same as #398, and we can continue the discussion there.

This seems to have broken.. let me see if I can figure out where it broke.

**Comment by robertnishihara** [comment]
FYI, your example should work now that #453 has been merged.

However, these kinds of things are tough to pickle, so we probably won't *fully* support recursive remote functions in the short term.

**Comment by akamaus** [comment]
Wow, works like a charm, indeed!
Many thanks for such a prompt fix :)
