### ISSUE TITLE
[ray] remove_from_object_store method

### ISSUE THREAD

**Issue by neychev** [ray-project/ray#4512]
ray version: 0.6.4 (stable)
OS version: Ubuntu 16.04

__Feature request:__

Maybe we could add function to remove some useless data from object store without restarting ray process? It could be useful in some cases (e.g. getting new datasets online and using them to update model parameters).

For now in `ray.tune.util.py` are present functions `pin_in_object_store` and `get_pinned_object`, referring to `put` and `get` functions from `ray.worker.py` correspondingly. As far as I can see, there is no chance to remove some object from object store but restart the process running ray. 

`pin_in_object_store` docstring says:
```
def pin_in_object_store(obj):
    """Pin an object in the object store.

    It will be available as long as the pinning process is alive. The pinned
    object can be retrieved by calling get_pinned_object on the identifier
    returned by this call.
    """

    obj_id = ray.put(_to_pinnable(obj))
    _pinned_objects.append(ray.get(obj_id))
    return "{}{}".format(PINNED_OBJECT_PREFIX,
                         base64.b64encode(obj_id.id()).decode("utf-8"))
```

**Comment by richardliaw** [comment]
cc @robertnishihara

**Comment by guoyuhong** [comment]
@neychev You can try `ray.internal.free` and the reference test is [here](https://github.com/ray-project/ray/blob/master/python/ray/tests/test_basic.py#L1405-L1489). Currently, there is not need to do flush, but you still need to wait some time for the object deletion operation.

**Comment by neychev** [comment]
Thanks. 
`ray.internal.free` does the trick. Just a comment to save it for future: `ray.internal.free` takes not transformed to string `object_id` returned by `pin_in_object_store` function, but the raw one. It is `ray.ObjectID` class instance. For example refer to the `get_pinned_object` in `ray.tune.util` module.

Copied code with exact transformation of `pinned_id` string:
```
# pin the object in object store
pinned_id = pin_in_object_store([1,2,3])

# ray constant from `ray.tune.util` module
PINNED_OBJECT_PREFIX = "ray.tune.PinnedObject:"

# transform string to ObjectID
object_id  = ObjectID(base64.b64decode(pinned_id[len(PINNED_OBJECT_PREFIX):]))

# remove the pinned object from object store
ray.internal.free([pinned_id])
```
