### ISSUE TITLE
Ray Summit 2024 CfP

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#45199]
Ray Summit 2024 will be September 30 to October 2 in SF.

We love to hear about everything the community has been working on -- including but not limited to

- Ray use cases
- AI platforms and infrastructure
- Scalable AI
- AI in production
- Large language models and other foundation models
- Generative AI
- Model training, model inference, batch workloads
- Cloud computing and serverless computing
- AI performance and cost efficiency

For more information, see [here](https://www.anyscale.com/blog/ray-summit-2024-call-for-proposals-is-now-open). Submit a [session proposal](https://raysummit.anyscale.com/flow/anyscale/raysummit2024/landing/page/eventsite?utm_source=cfpraydocs_gl=1*949o36*_ga*Mzk2ODgxMTUwLjE3MTM4OTE0NzM.*_ga_T6EXHYG44V*MTcxNDA3ODUzNC43LjAuMTcxNDA3ODUzNC42MC4wLjEyMDk3NzQ2MjE) to share your experience.

Looking forward to seeing everybody at the conference!

**Comment by peterghaddad** [comment]
@pcmoritz is there an estimated timeline for when submitters will be notified? Thanks!

**Comment by pcmoritz** [comment]
@peterghaddad Submitters should be notified by the end of June :)

**Comment by vermouth1992** [comment]
Hi, I still don't get a notification. When will the results be available?
