### ISSUE TITLE
[Worker] Recommended methodology to look into worker stuckness

### ISSUE THREAD

**Issue by sfc-gh-zhwang** [ray-project/ray#45192]
I am running 8 ray workers on a machine with 8 GPU cards, each worker is assigned with 1 GPU. 
For each worker, i am running, `nn.module.to('cpu')`, for most of the times, it succeed without any issue. However, sometimes, this function will stuck forever.
I checked CPU memory by running `free -h`, and I think there are plenty CPU memory left, and no CPU memory OOM.

I am modifying https://github.com/vllm-project/vllm, so I believe the ray version is `2.9.3`. Any idea of how to look into such kind of issue in general?

**Comment by anyscalesam** [comment]
@sfc-gh-zhwang might be better to follow up on vllm Github and/or over Slack to debug this (faster online than offline over GH).

Feel free to reach out to me on Slack if you can't get traction there (I would start on #serve channel)
