### ISSUE TITLE
[rllib] env.close() not called

### ISSUE THREAD

**Issue by FlyClover** [ray-project/ray#4520]
### System information
- **OS Platform and Distribution**:  Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.4
- **Python version**: 2.7
- **Exact command to reproduce**:

### Describe the problem

I have a custom Unity environment wrapped inside gym with subprocess. When running it inside rllib with tune, the close() seems never been called so there are lots of dangling subprocesses...
I check the code base and couldn't find any call to close() either. Is this a bug or something that I should handle in my environment?

**Comment by ericl** [comment]
I think https://github.com/ray-project/ray/pull/4521 should fix it, can you try it out?

**Comment by LQNew** [comment]
I also encountered this problem, I added close() function in the env clase , but it also seemed not to be called.
