### ISSUE TITLE
[tune] Specify `--columns` for CLI 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4523]
### Describe the problem
Right now it's not possible to specify the columns shown for `list-experiments` and `list-trials`. 

It's already implemented in `tune/commands.py`, but just needs to be exposed via `scripts.py`.

This should also support `result-columns`.

> This script is awesome. I was not able to find the tune CLI (even under ray in site_packages). However ran it manually via python <some_path>/python2.7/site-packages/ray/tune/scripts.py list-trials experiment2/ which produces experiment_tag besides other columns. However, is there a way to also show each hyperparameter separately and final metrics (i.e return value of _train()) after the trials terminate in separate columns? 

See: https://groups.google.com/d/msg/ray-dev/T5q7DkkGlpQ/ZzbOTIsVBwAJ

@andrewztan can you take a look at this?

cc @Nithanaroy

**Comment by andrewztan** [comment]
Sorry, what do you mean by `reset-columns`? What would that command look like? Thanks!

**Comment by richardliaw** [comment]
Oh `result_columns` are the keys in `last_result` (i.e., see `commands.list_trials(result_keys=RESULT_KEYS)`). Let me know if you have any questions...

**Comment by richardliaw** [comment]
BTW, this depends on #4519, so you can base a PR off of that.

The command would look like 

`tune ls [EXP_PATH] --columns id,name,cidr --result-columns mean_accuracy,mean_loss`

**Comment by richardliaw** [comment]
@Nithanaroy @BenMacKenzie, thanks to @andrewztan, this is now merged - feel free to try it out on the latest master!
