### ISSUE TITLE
CI test windows://python/ray/tests:test_get_locations is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#45278]
CI test **windows://python/ray/tests:test_get_locations** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/4408#018f6a8f-43b7-4299-8273-7605f463d09e
	- https://buildkite.com/ray-project/postmerge/builds/4408#018f6a48-484c-4f78-8823-18030c9603ab

DataCaseName-windows://python/ray/tests:test_get_locations-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: bfbdb3959acb2bdab72ff7b9b2f2f4764df20354 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1125

**Comment by can-anyscale** [comment]
Blamed commit: bfbdb3959acb2bdab72ff7b9b2f2f4764df20354 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1125

**Comment by can-anyscale** [comment]
Blamed commit: 108b7ba892a0978430bff227e5bc333b91dc3a90 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1125

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/4607#018fad1f-de4d-43b1-955f-55f33b83f08e

**Comment by can-anyscale** [comment]
CI test **windows://python/ray/tests:test_get_locations** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/4923#019017ca-027e-496e-a02c-1bef1eb85426
	- https://buildkite.com/ray-project/postmerge/builds/4923#0190178e-5166-421f-bba3-e95f79e67c86

DataCaseName-windows://python/ray/tests:test_get_locations-END
Managed by OSS Test Policy

**Comment by rynewang** [comment]
not again...?

**Comment by can-anyscale** [comment]
CI test **windows://python/ray/tests:test_get_locations** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/4923#019017ca-027e-496e-a02c-1bef1eb85426
	- https://buildkite.com/ray-project/postmerge/builds/4923#0190178e-5166-421f-bba3-e95f79e67c86

DataCaseName-windows://python/ray/tests:test_get_locations-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
this is fixed

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/4881#01900eef-7a19-4e3c-91f7-59e130213d42
