### ISSUE TITLE
[tune] Integration with TensorBoard HParams Dashboard

### ISSUE THREAD

**Issue by Nithanaroy** [ray-project/ray#4528]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.2
- **Python version**: 2.7
- **Exact command to reproduce**: NA

### Describe the feature request
Would it be possible to see the `ray.tune`'s results in Tensorboard's HParams https://www.tensorflow.org/tensorboard/r2/hyperparameter_tuning_with_hparams dashboard?

**Comment by richardliaw** [comment]
@adizim is taking a stab at this

**Comment by VCBE123** [comment]
ERROR logger.py:191 -- HParams failed with hparams['layers'] = 7, of unsupported type <class 'numpy.int64'>

**Comment by crypdick** [comment]
This doesn't seem to be working with TorchTrainer.as_trainable
