### ISSUE TITLE
[core][experimental] Support nested and dynamically sized GPU tensors via NCCL

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#45306]
### Description

#45092 introduces statically sized p2p transfer for GPU tensors via NCCL. We should also support GPU tensors that are stored inside other data on host memory, as well as dynamically sized tensors.

**Comment by anyscalesam** [comment]
@stephanie-wang is this something that is needed for integration with vLLM or is this a usability item to make it more natural for NCCL users to convert to ADAG?

**Comment by stephanie-wang** [comment]
It is both!

A lighterweight integration with vLLM is possible without this, but supporting this would mean that GPU-GPU communication can also be done through DAGs (instead of user code).
