### ISSUE TITLE
[core][experimental] Support broadcast NCCL ops in accelerated DAG

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#45308]
### Description

When the same GPU tensor is sent to multiple readers, we should use ncclBroadcast under the hood to reduce transfer time.

**Comment by rkooo567** [comment]
p2 for now (until we need more perf features)

**Comment by jeffreyjeffreywang** [comment]
I'm interested in this task and would love to work on it.

```
with InputNode() as inp:
    dag = sender.send.bind(shape, dtype, inp)
    dag = dag.with_type_hint(TorchTensorType(shape, dtype))
    o1 = receiver1.recv.bind(dag)
    o2 = receiver2.recv.bind(dag)
    dag = MultiOutputNode([o1, o2])
```

This should call `ncclBroadcast` under the hood as there are multiple receivers getting a tensor sent by a single sender. @stephanie-wang, is my understanding accurate?

**Comment by rkooo567** [comment]
actually this one I want to hold a little bit before we have more clear design. The reason is that broadcast is not always working well if all downstream tasks are not running at the same. For example;

```
with InputNode() as inp:
    dag = sender.send.bind(shape, dtype, inp)
    dag = dag.with_type_hint(TorchTensorType(shape, dtype))
    dag2 = receiver1.long_running.bind(inp)
    o1 = receiver1.recv.bind(dag)
    o2 = receiver2.recv.bind(dag)
    dag = MultiOutputNode([o1, o2, dag2])
```

In this case, receiver_1.recv starts after receiver1.long_running finishes, and because it is broadcasting receiver2.recv should wait, which is different from current semantics. I think we need more refined heuristic to support this instead of just using broadcasting for all cases

**Comment by jeffreyjeffreywang** [comment]
Got it, that makes a lot of sense. Do we have an estimated timeline for completing the design? Please let me know if there's anything I can help with!

**Comment by rkooo567** [comment]
I think following up with multi output ref (multi ray.get and skip deseriailzation) are good candidates!!

**Comment by rkooo567** [comment]
For this case, if you'd like to take it, I think we need 2 followups; 

- what's the perf benefit of send to N downstream actors vs broadcast it (we need to benchmark and measure it)
- what's the good heuristics? This is useful if we know all downstream tasks are available around the same time (common case in spmd).

**Comment by jeffreyjeffreywang** [comment]
Sounds good, I'll get started on the deserialization problem and get back to this issue after doing a bit more research.

**Comment by stephanie-wang** [comment]
I'm going to close this since we don't necessarily need a new API for it. It could be handled with https://github.com/ray-project/ray/issues/47938.
