### ISSUE TITLE
[Core] Receiving RuntimeEnvSetupError frequently after migrating from 2.3.0 to 2.20.0

### ISSUE THREAD

**Issue by raghumdani** [ray-project/ray#45311]
### What happened + What you expected to happen

We recently migrated Ray version from 2.3.0 to 2.20.0 and are seeing `RuntimeEnvSetupError` more frequently however we weren't seeing the same error before. 

Stack Trace:

```
Failed to create runtime env for job 02000000, status = IOError: on_read bad version, maybe there are some network problems, will fail the request.
```

### Versions / Dependencies

Ray: 2.20.0
Python: 3.10
OS: Ubuntu 20.04

### Reproduction script

- We are unable to reproduce this in testing environment yet as it seems it only occurs under high load. 
- A reasonable expectation here is to understand in what circumstances do we receive this error as it turns out this exception is coming from https://github.com/boostorg/beast/blob/2dcdef3890a4037a763cfe50243fffd8a9b5bd5a/include/boost/beast/http/detail/basic_parser.ipp#L380. 

### Issue Severity

None

**Comment by rynewang** [comment]
Duplicate for #45353
