### ISSUE TITLE
Release test microbenchmark_gpu_unstable failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#45322]
Release test **microbenchmark_gpu_unstable** failed. See https://buildkite.com/ray-project/release/builds/15427#018f75be-a498-4acd-bb22-a6a25439ef81 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by anyscalesam** [comment]
reviewed and triaged @stephanie-wang  to take a look

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/15978#018f9ec8-a3f1-4eed-a9c2-49c51a7ce011
