### ISSUE TITLE
[Client] Ray.initiallize() doesn't properly reflect ray status 

### ISSUE THREAD

**Issue by AlexCuadron** [ray-project/ray#45370]
### What happened + What you expected to happen

I tried connecting to a ray cluster using the ray client: `ray.init("ray://IP:10001", allow_multiple=True)
`. Which I successfully connect to as shown by this output:
```
2024-05-16 02:28:28,969 WARNING utils.py:1591 -- Python patch version mismatch: The cluster was started with:
    Ray: 2.12.0
    Python: 3.10.14
This process on Ray Client was started with:
    Ray: 2.12.0
    Python: 3.10.13

ClientContext(dashboard_url='172.17.0.2:8265', python_version='3.10.14', ray_version='2.12.0', ray_commit='549c4b7694483f6bc9e519b61e6f575e13510343', _num_clients=5, _context_to_restore=<ray.util.client._ClientContext object at 0x15473b599d50>, protocol_version=None)
```
Then I checked that the connection was established using: `ray.is_initialized()` But, to my surprise I get this output:
`False`.

The expected return should be `true`.

### Versions / Dependencies

Ray latest version, python 3.10, and Ubuntu 22 

### Reproduction script

ray.init("ray://IP:10001", allow_multiple=True)
ray.is_initialized()
Output should be true, but it is false

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rynewang** [comment]
We don't support Ray connections in different python versions. Please upgrade Python to the same version and retry.
