### ISSUE TITLE
Feature request: logging across raylets

### ISSUE THREAD

**Issue by phuicy** [ray-project/ray#4539]
### Logging

It would be great if logging in ray functions would be piped out, even over the network.
For example:
```python
logging.basicConfig(level=logging.INFO)
log = logging.getLogger("ray")

@ray.remote
def add2(a, b):
    log.info(str(a+b))
    return a + b
```

Additionaly it would be great if we could integrate into tqdm. For example:
```python
workers = [runner.remote() for i in range(number_of_demos)]
for worker in tqdm(workers):
    results = ray.get(worker) 
```

or alternatively:

```python
@ray.remote
def worker(pbar):
    pbar.update(10)
    return 'done'

with tqdm(total=100, desc="Training") as pbar:  
workers = [runner.remote(pbar) for i in range(10)]
results = [ ray.get(worker) for worker in workers ]
```

thanks,
Guy

**Comment by robertnishihara** [comment]
This already works. When I run your example, I see

```
(pid=16714) 2019-04-02 12:07:32,204	INFO <ipython-input-5-6c3ea3f23415>:6 -- 3
```

printed in the background.

**Comment by phuicy** [comment]
Ah, ok I can get `print()` to work but not `log.info`, even if the handler to pipe data into print, hmmm.

**Comment by richardliaw** [comment]
I think you just need to handle log config within the worker, though @rkooo567 should be fixing this.
