### ISSUE TITLE
Failed to install ray above 0.6.4 from source in Arm64 architecture

### ISSUE THREAD

**Issue by gliese581gg** [ray-project/ray#4548]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04 (Arm64 architecture)
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.4
- **Python version**: 3.6.7
- **Exact command to reproduce**: pip3 install -e . --verbose

Hi!

I'm trying to install ray 0.6.4 on the NVIDIA Xavier board which has Arm64 CPU.

However, install command fails with following error

```sh
Could not find a version that satisfies the requirement pyarrow==0.12.0.RAY (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0)
    No matching distribution found for pyarrow==0.12.0.RAY
```

I found out that build.sh is changed since 0.6.4 so it uses snapshot of pyarrow compiled in X86.

Therefore manually downloading and install whl didn't work.

Is there a workaround for this problem?

If pyarrow==0.12.0.RAY is same as pyarrow 0.12, can I install it and skip this part in build.sh?

**Comment by gliese581gg** [comment]
I found that there is RAY_USE_CMAKE option in build.sh

I will try this.

However, There is no cmake support since 0.6.5

Will there be a way to install ray > 0.6.5 in Arm64 machine in the future?

**Comment by sammuli** [comment]
@gliese581gg, I've also just this morning encountered this same issue trying to build on a power 9 machine. I had previously figured out a hack to get it built under 0.6.1, but the revised build system that downloads prebuilt wheels for dependencies doesn't work for non-standard architectures. I guess the question amounts to this: Is there a way to force builds of dependencies?

**Comment by pcmoritz** [comment]
@sammuli @gliese581gg You will need to install the pyarrow dependency separately, and comment out the following line from build.sh: https://github.com/ray-project/ray/blob/b0f6ddf6d103ad19844b129b62811c8ee9073ee1/build.sh#L98

Instruction to build pyarrow are here: https://arrow.apache.org/docs/developers/python.html#build-and-test

I usually install it with:
``
git clone https://github.com/apache/arrow/
cd arrow/cpp
mkdir build
cmake -DARROW_PLASMA=on -DARROW_PYTHON=on -DARROW_DEPENDENCY_SOURCE=BUNDLED ..
make -j8
sudo make install
``

and then
```
cd arrow/python
PYARROW_WITH_PLASMA=1 python setup.py install
```

If this works for you, we can create a PR to provide a flag for setup.py to do it automatically.

**Comment by yunqu** [comment]
Is there a stable version of pyarrow that is verified? I checked out a few tags, but the `make -j8` gave out some errors so I was not able to install it from source.

**Comment by sammuli** [comment]
Can't speak for the maintainers, but I just managed to get it compiled using the "apache-arrow-0.12.1" tag. Running on power 9 though, so you mileage may vary...

**Comment by yunqu** [comment]
Still no success on the `arrow` installation. Followed steps [here](https://arrow.apache.org/docs/developers/python.html#build-and-test) but `make` after `cmake` failed miserably.

**Comment by sammuli** [comment]
Well, that was quite a rabbit hole I had to follow, but I finally got it built on my power 9 system.

Some notes on the process:

I followed the instructions given by @pcmoritz above:

```
git clone https://github.com/apache/arrow/
cd arrow/cpp
mkdir build
cd build
cmake -DARROW_PLASMA=on -DARROW_PYTHON=on -DARROW_DEPENDENCY_SOURCE=BUNDLED ..
make -j8
sudo make install
```

Then (note the additional ARROW_HOME variable I needed to set, though there's probably a more elegant way of setting that with cmake):

```
cd arrow/python
PYARROW_WITH_PLASMA=1  ARROW_HOME=/usr/local python setup.py bdist_wheel
```
I had an older version of bazel, but that was no good, so I followed the instructions here (https://docs.bazel.build/versions/master/install-compile-source.html) and bootstrapped from a zip distribution of version 0.21.0.

Then finally, I had an outdated version of git, 1.8, (since I'm running on centos 7.4) which didn't have the command line flags that the ray build was expecting. So, I built a bleeding edge version (2.9.5).

I was then able to do

```
pip install -e . --verbose
```

The only other gotcha I encountered was needing to put the arrow .so files into my LD_LIBRARY_PATH, though I suspect that I didn't quite build arrow right. There's probably some rpath flag or another that might help that issue.

From there I was able to do a minimal "ray.put" and "ray.get" test and it seemed to work.

**Comment by yunqu** [comment]
I was finally able to build ray! It happens to me that the `cmake` version is bad so I had to switch back to the original version that comes with Ubuntu 18.04. After that fix everything works fine now.

@sammuli  I think the tweaks you did have been documented in their RTD:
```
export ARROW_HOME=$(pwd)/dist
export LD_LIBRARY_PATH=$(pwd)/dist/lib:$LD_LIBRARY_PATH
```
before you can run the `cmake`.

Another thing to consider, is perhaps adding that target `pyarrow-0.12.1-cp36-cp36m-linux_aarch64.whl` onto the Amazon S3 bucket so we can download from there and install. Otherwise users will have to bootstrap it manually.

**Comment by mzy2240** [comment]
> Well, that was quite a rabbit hole I had to follow, but I finally got it built on my power 9 system.
> 
> Some notes on the process:
> 
> I followed the instructions given by @pcmoritz above:
> 
> ```
> git clone https://github.com/apache/arrow/
> cd arrow/cpp
> mkdir build
> cd build
> cmake -DARROW_PLASMA=on -DARROW_PYTHON=on -DARROW_DEPENDENCY_SOURCE=BUNDLED ..
> make -j8
> sudo make install
> ```
> 
> Then (note the additional ARROW_HOME variable I needed to set, though there's probably a more elegant way of setting that with cmake):
> 
> ```
> cd arrow/python
> PYARROW_WITH_PLASMA=1  ARROW_HOME=/usr/local python setup.py bdist_wheel
> ```
> 
> I had an older version of bazel, but that was no good, so I followed the instructions here (https://docs.bazel.build/versions/master/install-compile-source.html) and bootstrapped from a zip distribution of version 0.21.0.
> 
> Then finally, I had an outdated version of git, 1.8, (since I'm running on centos 7.4) which didn't have the command line flags that the ray build was expecting. So, I built a bleeding edge version (2.9.5).
> 
> I was then able to do
> 
> ```
> pip install -e . --verbose
> ```
> 
> The only other gotcha I encountered was needing to put the arrow .so files into my LD_LIBRARY_PATH, though I suspect that I didn't quite build arrow right. There's probably some rpath flag or another that might help that issue.
> 
> From there I was able to do a minimal "ray.put" and "ray.get" test and it seemed to work.

Somehow even if I setup the arrow home, it still shows "arrow not found". Do you know what I missed here?

**Comment by crunchybugs** [comment]
This has been helpful: https://gist.github.com/yunqu/bdbe9c34b883398bf97cf5361db63171

However I've not managed to build any 0.8.x versions yet for aarch64.  I've already built pyarrow, and have bazel 2.1.0 installed.  It seems to fail when addressing the boost dependency

I had to remove `build --incompatible_depset_is_not_iterable=false` from .bazelrc

ERROR: 
/home/cruncybugs/.cache/bazel/_bazel_yuengpj1/c1a3a841f66e48ba49d6bff340d1db13/external/boost/BUILD.bazel:130:1: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).

    Conditions checked:
     @boost//:linux_arm
     @boost//:linux_ppc
     @boost//:linux_x86_64
     @boost//:osx_x86_64
     @boost//:windows_x86_64
    ERROR: Analysis of target '//:ray_pkg' failed; build aborted:

**Comment by yunqu** [comment]
Just want to comment that I am able to build ray 0.8.3 for both aarch64 and armv7l. Not a lot of things have to change, but boost patches are definitely needed.

**Comment by crunchybugs** [comment]
@yunqu:  What version of boost do you use, and what patches are applied?  This doc is super helpful:  https://gist.github.com/yunqu/bdbe9c34b883398bf97cf5361db63171

Any updates that you might suggest?  I've been building for a NVIDIA Jetson Nano.

**Comment by richardliaw** [comment]
BTW, @yunqu should we push this gist into the documentation?

**Comment by yunqu** [comment]
@crunchybugs  Patches are mentioned [here](https://github.com/ray-project/ray/issues/4309#issuecomment-590981016). Otherwise I think the instructions are basically the same. I bootstrapped bazel 1.1.0 and used that to build ray 0.8.3.

**Comment by crunchybugs** [comment]
Got 0.9.0.dev working using https://gist.github.com/heavyinfo/aa0bf2feb02aedb3b38eef203b4b8cc4.  I also needed to update scipy to 1.4.1 and gym to 0.17.1.

Thanks!

**Comment by LukeIreland1** [comment]
None of the above workarounds work for me.
