### ISSUE TITLE
Actor tasks take longer to return as more tasks complete.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#455]
This issue is introduced by commit 227c916. 

As first seen on the A3C example, here is a code snippet that illustrates the issue.

```
import ray
import numpy as np
from datetime import datetime
import pickle 
def timestamp():
    return datetime.now().timestamp()
    
ray.init(num_cpus=15)

@ray.actor
class Timer():
    def __init__(self, i):
        self.id_ = i

    def compute(self, params):
        arr = [np.random.randn(200, 200) for i in range(5)]
        return arr, timestamp(), self.id_

timers = [Timer(_) for _ in range(10)]
times = []
params = np.random.randn(200, 200)
task_list = [t.compute(params) for t in timers]
while True:
    done, task_list= ray.wait(task_list)
    _, _end, _id  = ray.get(done)[0]
    times.append(timestamp() - _end)
    params = np.random.randn(200, 200)
    if len(times) % 200 == 0:
        print("%d: Last 200 average times: %f" % (len(times) / 200, np.median(times[-200:])))
        if len(times) % 1000 == 0:
            with open("./easy_test.pkl", "wb") as f:
                pickle.dump(times, f)
    task_list.append(timers[_id].compute(params))
```
We see that the median/mean of the return time (time between task finishing on actor and driver receiving the results of the task) increases as more tasks finish.

The Y-axis is seconds and X-axis is Number of Tasks finished (in chunks of 500).

![screenshot 2017-04-11 17 12 25](https://cloud.githubusercontent.com/assets/4529381/24938315/347df8bc-1eeb-11e7-8038-31ebc04c69a9.png)

Here is the same metric on a commit prior to the one linked above. Notice that there is no slowdown.

![screenshot 2017-04-11 17 12 48](https://cloud.githubusercontent.com/assets/4529381/24938333/5bec9cf0-1eeb-11e7-9169-c83f53222321.png)

**Comment by pcmoritz** [comment]
Fixed by https://github.com/ray-project/ray/pull/469

The difference in a profiler:
Before (all the time is spent in operator==, create_object is only < 1%)
![plasma-before](https://cloud.githubusercontent.com/assets/113316/25156074/52121d56-244d-11e7-81b2-a6f58b796829.png)

After (a decent amount of time is now spent in create_object)
![plasma-after](https://cloud.githubusercontent.com/assets/113316/25156075/5538c4a8-244d-11e7-8bca-1b545a0d03ab.png)
