### ISSUE TITLE
[RayTrain] Checkpoint API to recover from checkpoint from previous runs

### ISSUE THREAD

**Issue by sathyanarays** [ray-project/ray#45516]
### Steps to reproduce
There are examples that illustrate checkpointing and recovering from checkpointing in the Ray training frameworks. One such [example](https://docs.ray.io/en/latest/train/user-guides/checkpoints.html) illustrates how to configure checkpointing to a pytorch training job.

#### 1. Trigger the training RayJob

```
 kubectl apply rayjob.yaml

```

#### 2. Kill the head pod
Let the training job make a couple of checkpoints and then kill the head pod.

```
kubectl delete pods rayjob-sample-raycluster-lv85g-head-tbfwq

```

#### 3. The new driver ignores the checkpoint
The current driver pod errors out and a new driver pod gets created. The new driver pod runs the training job again from scratch ignoring the checkpoints produced in the last run.

### Hacky Fix

To overcome this problem, we have to write a function with a tightly coupled logic. For example, look at the function `findLatestCheckpoint` in [this](https://gist.github.com/sathyanarays/c1cad159bc5f438b17431b6d75019de8) job definition.

### Use case

It would be great if we have an API that we can call and get the latest checkpoint location for the previous iteration of the given run.

**Comment by sathyanarays** [comment]
This relates to an issue in Kuberay: https://github.com/ray-project/kuberay/issues/2155

cc: @kevin85421

**Comment by kevin85421** [comment]
cc @matthewdeng

**Comment by sathyanarays** [comment]
> > It would be great if we have an API that we can call and get the latest checkpoint location for the previous iteration of the given run.
> 
> Do you mean a Ray Train API? It makes sense to me. cc @matthewdeng

@matthewdeng @kevin85421 , yes. Ray Train API that helps to find the last successful checkpoint.

**Comment by matthewdeng** [comment]
@sathyanarays is [this](https://docs.ray.io/en/latest/train/user-guides/fault-tolerance.html#auto-resume) the API you'd be looking for?

**Comment by sathyanarays** [comment]
@matthewdeng , yes. This works. Thank you for the pointers.
