### ISSUE TITLE
How to speed up ray.get() to get a large object from another node？ 

### ISSUE THREAD

**Issue by fighterhit** [ray-project/ray#45532]
There is an 800MB object on one node. The actor on this node first calls `ref=ray.put(obj)`, and then passes the returned object reference to the actor on another node. The actor obtains the object through `ray.get(ref)`, but sometimes it exceeds 2 minutes, this is incredible, what could be the reason for this? Is there any way to speed up the `ray.get(ref)`? Or is there a way to pass the object to another node in advance?

**Comment by rynewang** [comment]
Let's track this in the forum: https://discuss.ray.io/t/how-to-speed-up-ray-get-to-get-a-large-object-from-another-node/14778/5
