### ISSUE TITLE
Release test microbenchmark_gpu_unstable failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#45573]
Release test **microbenchmark_gpu_unstable** failed. See https://buildkite.com/ray-project/release/builds/16268#018fb8b7-03fe-4101-b4ac-b5e16830044b for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 93dce13cbcd6871afd0ed61bd46cd989945667f3 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1185

**Comment by anyscalesam** [comment]
not a weekly release blocker

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by stephanie-wang** [comment]
Seems this is working now.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/20028#0190ed90-c6a2-4450-bdc3-68d50be30353
