### ISSUE TITLE
[autoscaler] Hardcoded docker --net=host 

### ISSUE THREAD

**Issue by perara** [ray-project/ray#4558]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: ray-0.7.0.dev2
- **Python version**: 3.7.3
- **Exact command to reproduce**: ray up cluster.yaml

### Describe the problem
When using autoscaler, the docker command hardcodes --net=host in the docker run command. This makes it difficult to set up ray on servers running other services. Tried to remove the line and replace with bridge, but I could not make ray run with this configuration (with a few port binds)
1. Is it possible to support --net=bridge at all?
2. Which ports must be forwarded in order for this to work
3. Could it be patched in to select network type manually?

**Comment by richardliaw** [comment]
Yeah, this was a bit of a hack not to need to worry about ports, and we should make it more extensible. Can you post what you tried so far and what things you ran into?

Thanks!

cc @robertnishihara who wrote the original Ray/Docker docs.
