### ISSUE TITLE
[Data] method "write_row_to_file" from class "RowBasedFileDatasink"  writes empty files for blocks with no rows 

### ISSUE THREAD

**Issue by gabjou** [ray-project/ray#45587]
### What happened + What you expected to happen

I am writing a custom Ray Dataset loader "MyFileLoad" and writer "MyFileWrite" to process 10 files with unusable extension (e.g. ".edf" for instance) located in /testEDF/, when the Ray Dataset contains blocks with no rows ( because the number of actors does not correspond to the number of file) and after using write_row_to_file, Ray will create empty files for these empty blocks saved in the output dir /testEDF/ where the correctly created csv files are outside the output dir. I think it would make sense to implement the skipping solution from the closed issue https://github.com/ray-project/ray/issues/36123.

See example below for details.
<img width="369" alt="test2" src="https://github.com/ray-project/ray/assets/87657702/c95eaf25-c7a2-49bf-9362-751c83fb8260">
<img width="895" alt="test1" src="https://github.com/ray-project/ray/assets/87657702/58911e82-ab0e-49f7-ab97-2d3a391c1511">
<img width="875" alt="test3" src="https://github.com/ray-project/ray/assets/87657702/296d53c6-44f9-4e16-b5af-ca4a1ec993b6">

### Versions / Dependencies

ray
python 3.9
mne
edfio

############### Custom Class loader and writer implementation #######################
      from ray.data.datasource import RowBasedFileDatasink
      from ray.data import read_datasource
      from typing import List,Iterator,Dict,Any,Union
      from ray.data.block import Block
      from ray.data.datasource import FileBasedDatasource, RowBasedFileDatasink
      import pandas as pd
      from ray.data._internal.delegating_block_builder import DelegatingBlockBuilder

      class MyFileLoad(FileBasedDatasource):
  
            def __init__(self, pathEDFs: Union[str, List[str]]):
                super().__init__(
                    pathEDFs,
                    file_extensions=["edf"],
                )
  
            def _read_stream(self, f: "pyarrow.NativeFile", path: str) -> Iterator[Block]:
                # Each block contains one row
                ids = [int(num) for num in re.findall(r'\d+', path)][-1]
                raw = mne.io.read_raw_edf(path)
                data = raw.get_data()
                builder = DelegatingBlockBuilder()
                item = {"data":data,"ID":str(ids)}
                # item = {"edf": edf,"hypno":events_}
                builder.add(item)
                yield builder.build()

      class MyFileWrite(RowBasedFileDatasink):
            def __init__(self,path:str,file_format:str):
                super().__init__(path, file_format=file_format)
  
            def write_row_to_file(self, row: Dict[str, Any], file: "pyarrow.NativeFile"):
                pd.DataFrame(row["data"]).to_csv(row["ID"]+".csv")
############ main ##############
      import ray
      import os
      import mne
      import numpy as np
      import multiprocessing
      import re
      pathEDF = "testEDF"
      pathCSV = "testCSV"
      os.makedirs(pathEDF, exist_ok = True)
      os.makedirs(pathCSV, exist_ok = True)
      for i in range(10):
          if not os.path.exists(os.path.join(pathEDF,f"{str(i)}.edf")):
              info = mne.create_info(["Test"],1)
              edf = mne.io.RawArray(np.random.rand(100).reshape(1,-1), info)
              mne.export.export_raw(os.path.join(pathEDF,f"{str(i)}.edf"), edf)
      allEDFs = [os.path.join(pathEDF,f) for f in os.listdir(pathEDF)]
      ds = read_datasource(MyFileLoad(allEDFs),
                  num_cpus=1,
                  concurrency=int(multiprocessing.cpu_count()*0.3)-1)
      ds.write_datasink(MyFileWrite(pathCSV,"csv"))

### Issue Severity

Low: It annoys or frustrates me.

**Comment by raulchen** [comment]
Supposedly, you should use the `file` parameter for write operation.
