### ISSUE TITLE
[core][experimental] Allow custom NCCL group declaration in accelerated DAG

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#45593]
### Description

Currently, accelerated DAGs automatically create a NCCL group of actors based on the annotated DAG nodes. However, sometimes user code will already create a NCCL group, or they will want more explicit control over which actors are in the NCCL group, especially if there are multiple groups. To support this, we should allow the user to pass in custom NCCL groups when creating the accelerated DAG.

**Comment by anyscalesam** [comment]
@stephanie-wang how important is this; is this needed to enable pipeline parallel training? Or is this just a general ADAG devex improvement?

**Comment by stephanie-wang** [comment]
No, it should not be necessary. Just a UX improvement.

**Comment by rkooo567** [comment]
this is an important feature for vllm integration (and is explicitly asked)
