### ISSUE TITLE
[core] Killed detached actors from finished jobs leaks children actors

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#45596]
### What happened + What you expected to happen

When we have a detached actor spawning some (non-detached) actors in a placement group, and the detached actor dies, we expect the child actors also die, from at least 2 mechanisms:

1. its ancestor actor died so it should die
2. its PG removed so it should die

But it leaked. We need to fix both. 

This PR tracks the actor killing children mechanism. The PG killing mechanism is tracked in #45598.

### Versions / Dependencies

master

### Reproduction script

(todo)

### Issue Severity

High: it's blocking

**Comment by anyscalesam** [comment]
next steps - we need to make sure we can reliably repro

**Comment by rynewang** [comment]
This can be considered "fixed" with leftovers. So we should have 2 lines of defense against the leak; 1 has been fixed so the user should no longer find it leaking. I am working on the 2nd defense

**Comment by anyscalesam** [comment]
The issue for Endpoints should already mitigated; the remaining logic is we need to remove Actors if the PG has been removed.

**Comment by rynewang** [comment]
The PG leak is also root caused. PR under review.

**Comment by rynewang** [comment]
Merged https://github.com/ray-project/ray/pull/45854.
