### ISSUE TITLE
[core] Removed Placement group did not kill actors, if its ancestors are from detached actors.

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#45598]
### What happened + What you expected to happen

Part of https://github.com/ray-project/ray/issues/45596.

This issue tracks the PG killing acrors/tasks mechanism.

### Versions / Dependencies

master

### Reproduction script

(todo)

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
need reliable repro first
