### ISSUE TITLE
Ray hangs the 2nd time it is called

### ISSUE THREAD

**Issue by alvarodemig** [ray-project/ray#4562]
### System information
- **OS Platform and Distribution (e.g., macOS 10.13.4)**:
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.6.5
- **Python version**: 3.6.5

### Describe the problem
It is a flask+dash app.
Im running it on my local machine (8 cpus). I want to use ray to update a graph through a callback.
The first time it is called the app updates accordingly, but when I call it again by clicking something to change the inputs, it just hangs forever. No error.
The print statement of the parallel function does not work the 2nd time it is called. It always work for my_function.

A simplified structure would be something like this:

file1.py (help functions file)
@remote
def parallel_function():
    print('just to check i'm here)
    return result

file2.py (main file)
def my_function(x):
    print('im going to call the remote function!')
    objects_id =  [parallel_function.remote() for i in range(x)]
    return [ray.get(o) for o in objects_id]
my_function(10)

**Comment by robertnishihara** [comment]
Would you mind providing the code in a runnable form so that we can copy and paste the example to reproduce the error?

Also, please post complete instructions for reproducing the issue.

To format code, you can write

\`\`\`python
your code goes here
\`\`\`

**Comment by richardliaw** [comment]
closing because stale
