### ISSUE TITLE
[Core] GCS crashed with Check failed: sync_reactors_.find(reactor->GetRemoteNodeID()) == sync_reactors_.end()

### ISSUE THREAD

**Issue by jjyao** [ray-project/ray#45639]
### What happened + What you expected to happen

```
2024-05-29 22:51:16	[2024-05-29 22:51:15,987 C 4837 4890] (gcs_server) ray_syncer.cc:248: Check failed: sync_reactors_.find(reactor->GetRemoteNodeID()) == sync_reactors_.end()
```

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

**Comment by jjyao** [comment]
Added more logs to help debug when it happens again.

**Comment by anyscalesam** [comment]
@jjyao has it occurred again in the last couple of weeks?

**Comment by jjyao** [comment]
Downgrade it to P1 since we cannot reproduce it.
