### ISSUE TITLE
[tune] Resume experiments resets training_iteration

### ISSUE THREAD

**Issue by FlyClover** [ray-project/ray#4563]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: master
- **Python version**: 3.5
- **Exact command to reproduce**:

### Describe the problem

When resuming a tune experiment, I can see that it loads previous checkpoints with correct meta:

```
 RUNNING trials:
 - TrainWithValidation_0_entropy_coeff=0.1,action_set=discrete_fl,grad_clip=1,lr=0.0001,vf_loss_coeff=0.5:      RUNNING, [1 CPUs, 1 GPUs]
, [pid=39594], 37248 s, 500 iter, 122112 ts, -7.46 rew
```

However, after one iteration, the "training_iteration" gets reset:

```
 RUNNING trials:
 - TrainWithValidation_0_entropy_coeff=0.1,action_set=discrete_fl,grad_clip=1,lr=0.0001,vf_loss_coeff=0.5:      RUNNING, [1 CPUs, 1 GPUs]
, [pid=167908], 37280 s, 1 iter, 384 ts, nan rew
```

This will screw up the result log. Though I could write a post-process script like  #4187, it would be nice to just continue the training iteration counting.

**Comment by ericl** [comment]
Hm, do you have `checkpoint_freq` set for the individual trials? It seems like it restored the overall experiment state, but fell back to starting the trial from iter=0 since there isn't a per-trial checkpoint.

**Comment by FlyClover** [comment]
Yes, I set checkpoint_freq=500 and it indeed resumes from that point.

**Comment by ericl** [comment]
Are you able to reproduce with `rllib train --run=PG --checkpoint-freq=1 --resume --env=CartPole-v0`?

When I interrupted training and re-ran the above, it seemed to have the right iter on resume:
```
 - PG_CartPole-v0_0:	PENDING, [1 CPUs, 0 GPUs], [pid=10892], 13 s, 105 iter, 21000 ts, 166 rew
```

**Comment by FlyClover** [comment]
Turns out it's my bad. I wrapped the Agent class inside a Trainable class and doesn't fully initialize the agent instance.
