### ISSUE TITLE
`np.float` was a deprecated alias for the builtin `float`

### ISSUE THREAD

**Issue by Irvingwangjr** [ray-project/ray#45641]
### What happened + What you expected to happen

Running python/ray/util/collective/examples/nccl_allreduce_multigpu_example.py, have the following errors:
![image](https://github.com/ray-project/ray/assets/32162780/1c774cea-93a7-4912-bbcd-265528386393)

### Versions / Dependencies

Python 3.10.12; ray 2.9.3 cuda117

### Reproduction script

python python/ray/util/collective/examples/nccl_allreduce_multigpu_example.py

### Issue Severity

None

**Comment by Irvingwangjr** [comment]
![Uploading image.png…]()
this works

**Comment by x13n** [comment]
This was already fixed in https://github.com/ray-project/ray/pull/45092
