### ISSUE TITLE
[core][dashboard] GPUs in PGs are not shown in UI page

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#45658]
### What happened + What you expected to happen

If you have an actor with a GPU in a PG, it only shows the renamed GPU resource, and no GPU in the GPU column. 

![image](https://github.com/ray-project/ray/assets/56065503/c6176d1a-cda4-4894-8942-c8237d1bf711)

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jjyao** [comment]
Closed by #47754
