### ISSUE TITLE
Job launch script RLlib

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#4566]
Is there an easy way to iteratively launch EC2 jobs in RLlib like: https://github.com/justinjfu/doodad ?

**Comment by ericl** [comment]
I would recommend using `tune.run` to schedule your experiments onto an auto-scaling Ray cluster: https://ray.readthedocs.io/en/latest/autoscaling.html

You can use launch a new cluster per experiment with `ray submit` as well.

**Comment by richardliaw** [comment]
@richardrl, A quick command for you - `ray exec [CLUSTER_YAML] 'rllib train --run DQN --env CartPole-v0' --start`. 

We'll add an example page for launching EC2 experiments in Tune soon.

**Comment by richardliaw** [comment]
@richardrl let us know if you have any followup questions.
