### ISSUE TITLE
[RLlib] 'PPOConfig' object has no attribute 'env_runners'

### ISSUE THREAD

**Issue by ochapman-dphil** [ray-project/ray#45665]
### Description

The code section provided in the documentation does not run:

```python
from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.algorithms.callbacks import MemoryTrackingCallbacks
# Construct a generic config object, specifying values within different
# sub-categories, e.g. "training".
config = (PPOConfig().training(gamma=0.9, lr=0.01)
        .environment(env="CartPole-v1")
        .resources(num_gpus=0)
        .env_runners(num_env_runners=0)
        .callbacks(MemoryTrackingCallbacks)
    )
# A config object can be used to construct the respective Algorithm.
rllib_algo = config.build()
``` 
The following error is given:

```shell
    .env_runners(num_env_runners=0)
AttributeError: 'PPOConfig' object has no attribute 'env_runners'. Did you mean: 'env_runner_cls'?
``` 

### Link

Original comment referred to:
https://docs.ray.io/en/latest/rllib/rllib-training.html
Also found here:
https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#rllib-algorithms-doc

**Comment by PhilippWillms** [comment]
Interesting, on the sub-page of the docs describing explicitly the new API stack  - https://docs.ray.io/en/latest/rllib/rllib-new-api-stack.html - the `env_runners` are NOT described as a property of `PPOConfig`.

**Comment by ochapman-dphil** [comment]
Solved: Issue was caused by using an older version of Ray (2.12.0 I believe)

It's brilliant that the codebase is being updated in real-time. I think more visible communication about versions would be helpful with such large differences between them in such a short time!

**Comment by zlpiscoming** [comment]
Same problem for me. Which version of ray do you install to solve this problem?
