### ISSUE TITLE
[Data] Add API support for passing sample weights via ray.dataset.to_tf

### ISSUE THREAD

**Issue by japneet-anyscale** [ray-project/ray#45701]
### Description

Add support for ray.dataset.to_tf to pass sample weights

https://www.tensorflow.org/versions/r2.8/api_docs/python/tf/keras/Model#fit

API does not currently support the feature: 
https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.to_tf.html#ray-data-dataset-to-tf

**Comment by scottjlee** [comment]
@japneet-anyscale could you give more details / sample usage on how the new API would be used?

if i understand correctly, `Model.fit(...)` is for a Keras model, while the `Dataset.to_tf(...)` will produce a TF Dataset. So the two methods will be for different types

**Comment by scottjlee** [comment]
After internal discussion, got additional context. Current workaround is to create a new generator which yields the Dataset, and insert the sample_weights:
```
def generator():
                for batch in self.dataset.iter_batches(
                    batch_size=batch_size,
                ):
                    assert isinstance(batch, dict)
                    features = convert_batch_to_tensors(
                        batch, columns=feature_columns, type_spec=feature_type_spec
                    )
                    labels = convert_batch_to_tensors(
                        batch, columns=label_columns, type_spec=label_type_spec
                    )
                    sample_weights = convert_batch_to_tensors(
                        batch, columns=sample_weight_column, type_spec=sample_weight_spec
                    )
                    yield features, labels, sample_weights
```

**Comment by scottjlee** [comment]
We can add a new parameter `additional_type_spec` to `to_tf()`:
```
def to_tf(
    ...,
    additional_type_spec: Dict[str, "tf.TypeSpec"] = None
)
```

then update `generator()` to output sample_weights, similar to the example in the previous message above: https://github.com/ray-project/ray/blob/releases/2.11.0/python/ray/data/iterator.py#L820-L835

finally, the API usage would be
```
to_tf(..., additional_type_spec={sample_weight_column: sample_weight_spec})
```

**Comment by galyna-anyscale** [comment]
@scottjlee Would you be able to pick this item in this sprint?

**Comment by scottjlee** [comment]
yeah either me or @omatthew98 can pick it up for the upcoming sprint (assuming in the next 6 weeks)

**Comment by jeffreyjeffreywang** [comment]
Hey @scottjlee, this issue looks interesting to me and I'm more than happy to help resolve this problem in the next couple days if you don't have spare cycles to tackle it. I am also thinking about adding tests to `ray/python/ray/data/tests/test_tf.py` as we introduce a new parameter to `to_tf`. Let me know if you prefer taking it over, or otherwise I'll publish a PR in the next couple days! Thanks!

**Comment by scottjlee** [comment]
@jeffreyjeffreywang that sounds great, go for it! thanks!
