### ISSUE TITLE
[Ray Core] Multiple tasks on the same node calling ray.get for the same object will result in multiple copies

### ISSUE THREAD

**Issue by yx367563** [ray-project/ray#45731]
### What happened + What you expected to happen

My scenario is that a large number of tasks will rely on the same list, and after I store it via ray.put, I send the ObjectRef to all the tasks. However, I found that even if these tasks are running on the same Worker Node, it still copies this data N times, resulting in excessive memory usage and poor performance.
I found that Ray is optimized for shared memory for numpy arrays, but not for other data types. I would like to ask if there is any way to share other data types on the same node to achieve the same effect as numpy?

### Versions / Dependencies

Ray 2.23.0

### Reproduction script

If you execute the following code, you will find that the same node is full of memory, but if you change to a numpy data structure, there will only be one copy on a node.

```
import ray
from math import ceil
import time

@ray.remote
def get_object(objectref):
    sum = 0
    for i in objectref:
        sum += i
    time.sleep(3)
    return I

def test_objectref():
    context = ray.init()
    print(context)
    allocate_bytes = 1024 * 1024 * 1024
    record_list = [0] * ceil(allocate_bytes)
    objectref = ray.put(record_list)
    results = []
    for i in range(2000):
        results.append(get_object.options(memory=8 * 1024 * 1024 * 1024).remote(objectref))
    ray.get(results)

if __name__ == '__main__':
    test_objectref()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
@yx367563 Yea, this is expected as python list doesn't support the buffer protocol so we cannot implement zero-copy. Use numpy array if you want zero copy.
