### ISSUE TITLE
[data] `from_huggingface` should respect `HF_ENDPOINT` environment variable

### ISSUE THREAD

**Issue by ccll** [ray-project/ray#45730]
### What happened + What you expected to happen

Huggingface allow the user to download datasets/models from a mirror site with env var [HF_ENDPOINT](https://github.com/huggingface/huggingface_hub/blob/4a6ab99d7060d12fd462d6e35678bb51e33cdaa7/src/huggingface_hub/constants.py#L57), which also should be respected by `ray.data.from_huggingface()`.

### Versions / Dependencies

Ray: 2.23.0
Python: 3.11.8
OS: Ubuntu 22.04.4 LTS

### Reproduction script

Simplified demo from the [ray tutorial](https://docs.ray.io/en/latest/train/examples/transformers/huggingface_text_classification.html):
```python
# demo.py
# Run with `HF_ENDPOINT=https://hf-mirror.com python demo.py`

from datasets import load_dataset
import ray.data

# This would download and cache the meta data successfully from `HF_ENDPOINT` mirror.
datasets = load_dataset("glue", "cola")

# But this would fail trying to download parquet data from the official Huggingface site,
# from a restricted network environment, with HF_ENDPOINT ignored.
ray_datasets = {
    "train": ray.data.from_huggingface(datasets["train"]),
    "validation": ray.data.from_huggingface(datasets["validation"]),
    "test": ray.data.from_huggingface(datasets["test"]),
}
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by enori** [comment]
Hi, I would like to take on this issue. 
I'm new to this project and open-source contributions, but I'm eager to learn and contribute if necessary.
Thanks!

**Comment by enori** [comment]
This issue is related to Hugging Face Datasets, not Ray, so it must be addressed with the Hugging Face solution.

```py
# https://github.com/huggingface/datasets/blob/6548e0e282aeeda7bfb18beafbc65ebecd780c63/src/datasets/config.py#L25
25 | HF_ENDPOINT = os.environ.get("HF_ENDPOINT", "https://huggingface.co")
```

As shown above, I defnied the mirror site URL in the environment variable HF_ENDPOINT, and when I executed `python demo.py`, the result changed.
I am using a local Raycluster. If you use a remote Raycluster, you may also need to change the environment variable on the remote Raycluster.

**Comment by scottjlee** [comment]
Welcome @enori to Ray and thanks for the verification ! @ccll if you can verify that the suggested solution above works for you, we can close this issue.

**Comment by enori** [comment]
This is the result with the above script and command; 
```sh
$ cat demo.py 
# demo.py
# Run with `HF_ENDPOINT=https://hf-mirror.com python demo.py`

from datasets import load_dataset
import ray.data

import os
print(os.environ.get('HF_ENDPOINT'))

# This would download and cache the meta data successfully from `HF_ENDPOINT` mirror.
datasets = load_dataset("glue", "cola")

# But this would fail trying to download parquet data from the official Huggingface site,
# from a restricted network environment, with HF_ENDPOINT ignored.
ray_datasets = {
    "train": ray.data.from_huggingface(datasets["train"]),
    "validation": ray.data.from_huggingface(datasets["validation"]),
    "test": ray.data.from_huggingface(datasets["test"]),
}
print(os.environ.get('HF_ENDPOINT'))

$ HF_ENDPOINT=https://hf-mirror.com python demo.py -v
https://hf-mirror.com
2024-06-27 04:11:34,027 INFO worker.py:1761 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
https://hf-mirror.com  
```

And, it looks like this issue has already been solved in the Huggingface community. 
I think we can close this issue. What do you think?

**Comment by scottjlee** [comment]
@enori thanks for the detailed investigation! It makes sense to me, so going to go ahead and close the issue.

@ccll please feel free to re-open the issue if you continue to run into the same problem!
