### ISSUE TITLE
Prev_action, prev_reward not passed to rollout

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#4573]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: n/a
- **Ray installed from (source or binary)**: n/a
- **Ray version**: n/a
- **Python version**: n/a
- **Exact command to reproduce**:

### Describe the problem

rollout.py does not keep track of previous actions and previous observed rewards and pass them to compute_action.py. This obviously is an issue if the policy was trained with prev. observed rewards and actions.

**Comment by ericl** [comment]
Ah yeah @vladfi1 has a fix here: https://github.com/ray-project/ray/pull/4565

**Comment by eugenevinitsky** [comment]
Cool, resolved!
