### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by demian2435** [ray-project/ray#45748]
https://github.com/ray-project/ray/blob/d49f15b1112e67d15a80d696249f587ea7b95b57/python/ray/_private/accelerators/nvidia_gpu.py#L71

To solve this problem, I modifed the parameter to "utf-16"

**Comment by ossun** [comment]
you're PRO :3

**Comment by Aricept094** [comment]
> https://github.com/ray-project/ray/blob/d49f15b1112e67d15a80d696249f587ea7b95b57/python/ray/_private/accelerators/nvidia_gpu.py#L71
> 
> 
> 
> 
> 
> To solve this problem, I modifed the parameter to "utf-16"

It was one of the first solutions that i tested, the ray starts working but it is unstable for example the weight and biases integration goes berserk fails to capture the target variable and many more problems. While temporary i dont suggest it.

**Comment by jjyao** [comment]
This is nvidia driver bug and is tracked in https://github.com/gpuopenanalytics/pynvml/issues/53
