### ISSUE TITLE
More informative error message when OOM

### ISSUE THREAD

**Issue by vitchyr** [ray-project/ray#4576]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: pip (`ray[rllib,debug]==0.6.4`)
- **Ray version**: 0.6.4
- **Python version**: Python 3.6.5 
- **Exact command to reproduce**: N/A

### Describe the problem
When my computer ran out of memory, `ray` kept giving this error:

```

2019-04-05 05:49:56,489 INFO node.py:439 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-04-05_05-49-56_75/logs.
2019-04-05 05:49:56,598 INFO services.py:364 -- Waiting for redis server at 127.0.0.1:10324 to respond...
2019-04-05 05:49:56,718 INFO services.py:364 -- Waiting for redis server at 127.0.0.1:43731 to respond...
2019-04-05 05:49:56,720 INFO services.py:761 -- Starting Redis shard with 6.73 GB max memory.
2019-04-05 05:49:56,745 WARNING services.py:1326 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be ab
le to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 
'docker run'.
2019-04-05 05:49:56,746 INFO services.py:1449 -- Starting the Plasma object store with 10.09 GB memory using /tmp.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0405 05:49:56.771152    75 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-05_05-49-56_75/sockets/plasma_store, retrying 300 more times
E0405 05:49:57.171295    75 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-05_05-49-56_75/sockets/plasma_store, retrying 299 more times
E0405 05:49:57.571434    75 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-05_05-49-56_75/sockets/plasma_store, retrying 298 more times
E0405 05:49:57.971583    75 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-05_05-49-56_75/sockets/plasma_store, retrying 297 more times
E0405 05:49:58.371719    75 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2019-04-05_05-49-56_75/sockets/plasma_store, retrying 296 more times
```

It kept retrying until it ran out of tries. I think it'd be nice to have a more informative error message since it took a very long time to figure out that this was due to being out of memory.

**Comment by ericl** [comment]
Could you provide more details on what the memory issue was? It sounds like you're saying the node had too little memory available to start ray?

**Comment by vitchyr** [comment]
Correct. It's not that ray necessarily caused this OOM issue, but it'd be nice ray provided a more informative error message when this is why it fails.

**Comment by hartikainen** [comment]
@vitchyr Was this your computer running out of memory or disk space? If I remember correctly it was about the disk space that was causing this.

**Comment by vitchyr** [comment]
Yes, sorry this was disk space memory.

**Comment by robertnishihara** [comment]
Hm, the most informative error message above is

*WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to  'docker run'.*

- How much memory does the machine have?
- How much disk space does the machine have?
- Are there other instances of Ray running?
- Is there other stuff taking up space in `/dev/shm`?
- Are you running this inside of docker?
- Can you share the logs from `/tmp/ray/session_*/logs/plasma_store.*`?

**Comment by rkooo567** [comment]
In the latest master, when the node has 95% of memory usage, it should fail. So this must've been addressed.
