### ISSUE TITLE
[rllib]check_shape in preprocessors doesn't work with Dict action space

### ISSUE THREAD

**Issue by stefanpantic** [ray-project/ray#4578]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.0.dev2
- **Python version**: 3.6.8
- **Exact command to reproduce**: N/A

### Describe the problem

Getting a TypeError here:
```
TypeError: '<=' not supported between instances of 'int' and 'list'
```

I've narrowed it down to this function:
```
  def check_shape(self, observation):
        """Checks the shape of the given observation."""
        if self._i % VALIDATION_INTERVAL == 0:
            if type(observation) is list and isinstance(
                    self._obs_space, gym.spaces.Box):
                observation = np.array(observation)
            try:
                if not self._obs_space.contains(observation):
                    raise ValueError(
                        "Observation outside expected value range",
                        self._obs_space, observation)
            except AttributeError:
                raise ValueError(
                    "Observation for a Box space should be an np.array, "
                    "not a Python list.", observation)
        self._i += 1
```

Namely the line:
```
if not self._obs_space.contains(observation):
```

There sould be an aditional check for Dict action space here.

**Comment by ericl** [comment]
Could you provide an example check that fails but should succeed? As far as I can tell this handles dict spaces.

**Comment by nikola-j** [comment]
It seems that this just requires the observations to be numpy arrays, also the second ValueError output is incorrect if you are using an obs space other than box, it should probably be changed to: `"Every element of the observation should be a np.array"`

**Comment by ericl** [comment]
Ah yes, this is a partially a bug in gym that doesn't accept lists instead
of arrays. Which obs types besides Box also raises causes that error? I can
send a patch upstream to fix it for future gym versions.

**Comment by nikola-j** [comment]
multi_binary and multi_discrete will also cause the error, thanks

**Comment by nikola-j** [comment]
Awesome, thanks!

**Comment by rein1685** [comment]
I'm not sure because I'm studying RLLIB, but I think I found a solution.

Check your spaces.Box function. my env use MinMaxScalar, so I use

self.observation_space = spaces.Box(
            low=0, high=1, shape=(13, lookback_window_size + 1), dtype=np.float16)

but my observation has value 1.00000001, so I edit high 1 to 2.

now my code works well!
