### ISSUE TITLE
[Serve]  Optimize the get_deployment_statuses function 

### ISSUE THREAD

**Issue by jugalshah291** [ray-project/ray#45792]
### Description

In the [get_deployment_statuses](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/deployment_state.py#L2566C9-L2566C32) function we are iterating over all the deployments, in order to obtain status of small number of deployments. This is inefficient especially when you have a large of deployments running.

Simple optimization is to iterate over the `DeploymentID` rather than `self._deployment_state` or may be we can rethink the class structures
Additionally the  [get_deployment_statuses](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/deployment_state.py#L2566C9-L2566C32) function is called twice in the [_determine_app_status](https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/application_state.py#L503), may be we can call it once and reuse the output

### Use case

Our system is running a very large number of DeploymentHandles (see https://github.com/ray-project/ray/issues/44784 for more details). We've noticed that the Serve controller gets overloaded (>100% CPU usage) and a small percentage of this CPU usage is coming from the `get_deployment_statuses` function, which is called at multiple places.
It can be optimized to 

![image](https://github.com/ray-project/ray/assets/47508441/5afa9c9f-f36e-4a2b-bc95-2a7d4c1f5202)

![controller_1200_kuberay_hack_retry](https://github.com/ray-project/ray/assets/47508441/254708da-8b27-41ee-be17-75991b1f5c39)

**Comment by JoshKarpel** [comment]
I'm giving some optimizations on this method a try in our setup and if it produces good results I'll open a PR for them
