### ISSUE TITLE
A suspected bug when use multi-GPU across nodes

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#458]
I'm not sure if it's bug of my code or ray. 
The phenomenon is strange that when use multi-GPU across nodes, it just has a error of segmentation fault (core dumped). When the used GPUs do not come from different nodes, the code works ! (for example, set the number of actor to 4.  We have two nodes, and each node has four GPU)

Here is the error log. Yes, it is very short
```
**_Segmentation fault (core dumped)_**
```

Here is my code (I have removed the irrelevant part)
Firstly, let us define an actor.
```
import ray
ray.init(redis_address="9.91.9.123:6379")
class test(object):
    def __init__(self, model_config):
        import os

        os.environ['CUDA_VISIBLE_DEVICES'] = ','.join([str(i) for i in ray.get_gpu_ids()])
        from keras.models import model_from_config
        self.model = model_from_config(model_config, custom_objects={})
        self.weights = None
    def run(self):
        for i in range(1000):
            self.model.predict(np.zeros((100,1,4)))
        return 1

    def get_weights(self):
        import numpy as np
        return [np.zeros((2,2)),np.zeros((2,2))]

    def set_weights(self, weights):
        self.weights = weights
```
Then i define the model
```
import numpy as np
import gym
import ray
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten

model = Sequential()
model.add(Flatten(input_shape=(1,) + (4,)))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(2))
model.add(Activation('linear'))
```
then i start to train on two nodes, and each node has four GPUs.
The following code looks a bit complicated at first glance. In fact, 
it is a simple averaging operation between multiple agents' return weights
```
config = {
    'class_name': model.__class__.__name__,
    'config': model.get_config(),
}

agent_count = 8

cpu_actor = ray.actor(num_gpus=1)(test)
agents =[cpu_actor(config) for _ in range(agent_count)]
rollout = 20
for k in range(rollout):
    rewards=[]
    actions = []
    weights=[]
    for i in range(agent_count):
        actions.append(agents[i].run())
    for i in range(agent_count):
        id,actions = ray.wait(actions)
        rewards.append(ray.get(id))
    for i in range(agent_count):
        weights.append(ray.get(agents[i].get_weights()))
    newweights=[]
    for i in range(len(weights[0])):
        temp = np.zeros(weights[0][i].shape)
        for j in range(agent_count):
            temp += weights[j][i]/agent_count
        newweights.append(temp)
    idcol = []
    for i in range(agent_count):
        idcol.append(agents[i].set_weights(newweights))
    for i in range(agent_count):
        ray.wait(idcol)
    print("step {},reward {}".format(k,np.mean(rewards)))
```

**Comment by robertnishihara** [comment]
Which process is segfaulting (which error log is that message coming from)? If you look in `/tmp/raylogs/`, are there any interesting error messages in the log files there?

**Comment by raopku** [comment]
i think i can make things more easy to understand by simplify demo code.
```
import ray
ray.init(redis_address="9.91.9.123:6379")
class test(object):
    def __init__(self):
        self.weights = 0
    def get_weights(self):
        import numpy as np
        return [np.zeros((2,2)),np.zeros((2,2))]    

agent_count = 8
gpu_actor = ray.actor(num_gpus=1)(test)
agents =[gpu_actor() for _ in range(agent_count)]
```
There are eight actors in two nodes. Four of them are not on the same node as the driver.
One of the following command will fail. The one on the same node as the driver will success. And the other one will fail. 
```
ray.get(agents[0].get_weights())
ray.get(agents[7].get_weights())
```
It looks like ray can not get numpy array from actor which is not on the same node with driver ? 
And i did not find some special error logs in /tmp/raylogs/.

**Comment by raopku** [comment]
More interesting things come

```
import ray
ray.init(redis_address="9.91.9.123:6379")
class test(object):
    def __init__(self):
        self.weights = 0

    def get_weights(self):
        import numpy as np
        #weights = [np.zeros((2,2)),np.zeros((2,2))]
        return {"w1":np.zeros((2,2)),"w2":np.zeros((2,2))}

agent_count = 8
cpu_actor = ray.actor(num_gpus=0)(test)
agents =[cpu_actor() for _ in range(agent_count)]
```

```
ray.get(agents[1].get_weights()) 
result:
{'w1': array([[ 0.,  0.],
        [ 0.,  0.]]), 'w2': array([[ 0.,  0.],
        [ 0.,  0.]])}
```
However
```
ray.get(agents[7].get_weights()) 
result:
{'w1': 'w1', 'w2': 'w1'}
```
Why is {'w1': 'w1', 'w2': 'w1'} ?

**Comment by robertnishihara** [comment]
That's *extremely* strange. I've tried your example, but it works for me.

My best guess is the following. Maybe you are using two different commits of Ray on the two machines. If the commits of Ray are the same, it's possible that the commits of Arrow in `ray/src/numbuf/thirdparty/arrow` are slightly different. Can you check that?

I'd suggest doing `rm -rf ray/` and `pip uninstall ray` on both machines. Then re-clone the repository on both machines and reinstall. That might fix it.

Beyond that, I have a few questions:

1. Does the problem happen **consistently** for you on two nodes? That is, does it happen every single time you do the above experiment?
2. Does it **ever** happen if you use just one node? Or does the problem seem to **require** two nodes? Can you try **both** nodes individually and see if the problem can be made to appear?
3. Is there a chance you have slightly different versions of Python on the two machines (or two different versions of something else)? Not that that would explain this behavior.

Maybe there's a bug on our end.. 



@pcmoritz could there be a bug in numbuf that is leading to dictionaries of strings and numpy arrays sometimes being serialized incorrectly?

**Comment by raopku** [comment]
@robertnishihara you are absolutly right!
I have checked the git log, and there are two different versions of ray installed on two nodes!
Anyway the phenomenon is so strange and confused !
After reinstallation, things go well.
Thank you very much!

**Comment by robertnishihara** [comment]
Awesome, I'm glad to hear it!
