### ISSUE TITLE
How are the functions in the environment called?

### ISSUE THREAD

**Issue by gowthamnatarajan** [ray-project/ray#4580]
I will be creating a custom Environment.
Wanted to know how it will be used.
When will reset be called? When an episode ends, will reset be called and will the same object be reused? OR will a new object be created which would call init again?

I am planning to initialize my environment only in the init function and not in the reset function.

In the project I am working on, the start state is not the same. Every time an instance of my custom environment is created, the first state will be different. It is randomly generated.

**Comment by ericl** [comment]
We will call reset() every time the episode ends, and the object is reused.

**Comment by gowthamnatarajan** [comment]
How many instances of the class is created? Is it same as number of workers? I will be using PPO.

**Comment by ericl** [comment]
That's right.

**Comment by gowthamnatarajan** [comment]
Thanks. And I assume close is called at the end when training is done?

**Comment by ericl** [comment]
Yes.
