### ISSUE TITLE
C++ Python Cross-language invocation

### ISSUE THREAD

**Issue by jaystarshot** [ray-project/ray#45815]
### Use case

We have 2 tasks
task1 (can be thought as reading parquet files into memory)
task2 (using torch tensors do something)
We are thinking of having task1 in cpp and task2 in python. 
Does ray support that?
I saw some cross platform invocation documentation but that was mainly around java-cpp.
If cross platform is not the solution how can we manage this?

**Comment by jaystarshot** [comment]
cc: @SongGuyang

**Comment by SongGuyang** [comment]
Actually, we already have a simple cross language implementation between C++ and Python. But this feature is still experimental and we don't have official docs about it. You can learn from the two tests: PythonInvocationTest of cpp/src/ray/test/cluster/cluster_mode_test.cc and cpp/test_python_call_cpp.py.

**Comment by jaystarshot** [comment]
Thanks @SongGuyang I will definitely explore this, we from uber were very interested in trying out this approach. Since the reads can be vectorized and are generally better suited for c++ workloads. I saw your awesome doc [here](https://www.anyscale.com/blog/modern-distributed-c-with-ray)  which showed how to use ray-cpp.
 Do you also have any benchmark numbers vs python api showcasing the python overhead?
