### ISSUE TITLE
Error in Kubernetes yaml files

### ISSUE THREAD

**Issue by DuaneNielsen** [ray-project/ray#4581]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **Ray installed from (source or binary)**: not installed
- **Ray version**: latest master
- **Python version**: 3.6
- **Exact command to reproduce**: kubectl create -f ray/kubernetes/head.yaml

### Describe the problem
typo in kuber head.yaml  

I believe 

requiredDuringSchedulingIgnoreDuringExecution

should be 

requiredDuringSchedulingIgnore**d**DuringExecution

service/ray-head created
error: error validating "ray/kubernetes/head.yaml": error validating data: ValidationError(Deployment.spec.template.spec.affinity.podAntiAffinity): unknown field "requiredDuringSchedulingIgnoreDuringExecution" in io.k8s.api.core.v1.PodAntiAffinity; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by robertnishihara** [comment]
@DuaneNielsen Good catch! Would you be able to submit a pull request fixing this?

**Comment by DuaneNielsen** [comment]
Sure

On Mon, Apr 8, 2019 at 3:12 PM Robert Nishihara <notifications@github.com>
wrote:

> *CAUTION: This email originated from outside of Broadcom. Do not click
> links or open attachments unless you recognize the sender and know the
> content is safe.*
>
> @DuaneNielsen
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DuaneNielsen&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=OXK0v8FaD9soLy02fcZZT9gC57Fd39XmOwdHn8UlmOo&m=t_0GL470Oun7w3Y_t_y4v-ciX_LGE0R_AL-ALoJ4ppE&s=CNNNhc9l--waS-qPnYKAZf6fFTgdzm4INOZdKVCVvew&e=>
> Good catch! Would you be able to submit a pull request fixing this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ray-2Dproject_ray_issues_4581-23issuecomment-2D481027606&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=OXK0v8FaD9soLy02fcZZT9gC57Fd39XmOwdHn8UlmOo&m=t_0GL470Oun7w3Y_t_y4v-ciX_LGE0R_AL-ALoJ4ppE&s=ICsgTH96g3gkLL_9IPvdGY4BYFkXsci3bQm1L9yH9W0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKjsLO52TohISLkzZ-5FU9nXkkC2o4ETUsks5ve77XgaJpZM4cjAgU&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=OXK0v8FaD9soLy02fcZZT9gC57Fd39XmOwdHn8UlmOo&m=t_0GL470Oun7w3Y_t_y4v-ciX_LGE0R_AL-ALoJ4ppE&s=N9CoYtFMO-PzyVOoQIzDTp6ZEiyDMBtpjDmkfpvQHC0&e=>
> .
>


-- 
Duane
Broadcom
480 760 1559

**Comment by robertnishihara** [comment]
Fixed by #4582.
