### ISSUE TITLE
RLlib - The batch for module_id default_policy is empty!

### ISSUE THREAD

**Issue by timosturm** [ray-project/ray#45826]
### What happened + What you expected to happen

Ray throws an exception if the environment takes to long to perform a step: 

No samples returned from remote workers. If you have a slow environment or model, consider increasing the `sample_timeout_s` or decreasing the `rollout_fragment_length` in `AlgorithmConfig.env_runners().

This happens both if `enable_rl_module_and_learner` is True or False, and for `batch_mode` complete_episodes and truncate_episodes. **Ideally, I want to use `complete_episodes` for training!**

I added a short example below, using `time.sleep(1)` for simplicity instead of the real computations my environment performs. Setting the `sample_timeout_s` does not seem to affect this problem. Removing the costly computation works but is obviously not an option.

### Versions / Dependencies

python: 3.11.9
ray: 2.23.0

### Reproduction script

```python

from ray.rllib.algorithms import PPOConfig
from gymnasium import spaces
import numpy as np
import gymnasium as gym

class FakeEnv(gym.Env):
    action_space = spaces.Discrete(2)
    observation_space = spaces.Box(low=-1, high=1, shape=(2,), dtype=np.float32)
    counter = 0

    def __init__(self, *args, **kwargs):
        pass

    def step(
            self, action
    ):
        time.sleep(1) # or any other computation that takes a "long" time

        terminated = self.counter > 10

        if action == 0:
            return self.observation_space.sample(), 1, False, terminated, {}
        if action == 1:
            return self.observation_space.sample(), -1, True, terminated, {}

    def reset(
            self, *, seed=None, options=None,
    ):
        self.counter = 0
        return self.observation_space.sample(), {}

algo = (
    PPOConfig()
    .api_stack(enable_rl_module_and_learner=True)
    .environment(FakeEnv)
    .framework("torch")
    .env_runners(num_env_runners=1, num_envs_per_env_runner=1, batch_mode="complete_episodes", sample_timeout_s=3600)
).build()

algo.train()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by kamilmlodzikowski** [comment]
I am also facing the same issue.

**Comment by hervature** [comment]
Try running with 

```
.api_stack(
    enable_rl_module_and_learner=True,
    enable_env_runner_and_connector_v2=True
)
```

and

```
.env_runners(
    sample_timeout_s=None
)
```

I could not get it to work with parallel evaluation.

**Comment by simonsays1980** [comment]
@timosturm Thanks for raising this issue. This led us find a bug in our sampling logic which is fixed in the related PR and should go in the next days into master. 

The configuration posted by @hervature is the intended config to activate the new API stack and avoid the error referred to here.
