### ISSUE TITLE
Wheels for Windows on PyPI

### ISSUE THREAD

**Issue by YarShev** [ray-project/ray#45827]
### Description

Hy folks,

I just noticed that there are no longer wheels for Windows on PyPI starting [Ray 2.21.0](https://pypi.org/project/ray/2.21.0/#files). Did you intentionaly stop building wheels for Windows on PyPI? Although, there are builds for Windows on [conda-forge](https://anaconda.org/conda-forge/ray-core/files).

### Use case

Was Windows support dropped out completely or do you plan to support further?

**Comment by anmyachev** [comment]
@YarShev It seems to be related to the new release scheme: https://github.com/ray-project/ray/issues/44276

**Comment by YarShev** [comment]
That is probably the case. I wonder if Ray developers want to have aligned builds across PyPI and conda-forge?

cc @aslonnie, @zhe-thoughts

**Comment by anyscalesam** [comment]
We're considering - we actually didn't slow down anything more we just release for darwin and macos faster (once every week) and kept window releases at the same clip (once every 6w).

there's some dependency upgrades that we're taking care of first to make window package builds faster (ie: upgrading from bazel 5 to 6) and than we're planning to see if that simplifies the conda-forge package release process where we can also include window releases weekly as well.

stay tuned~; updates in a couple weeks time. cc @aslonnie

**Comment by aslonnie** [comment]
we are going to release windows on every release now.
