### ISSUE TITLE
[Core] Improve performance of actor task execution by amortizing cost of checking for `async` methods 

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/ray#45848]
### Description

While investigating https://github.com/ray-project/ray/issues/45777 I noticed an oddity in a flamegraph from the Serve Controller (attached): about 5% of time was being spent in `inspect.getmembers`, with no caller identified in the flamegraph (small-ish block on the right side of the graph).

![controller-under-load](https://github.com/ray-project/ray/assets/7133863/dc907728-8cd1-43ba-9f40-d343bd7ff59f)

I think this is coming from this chunk of code: https://github.com/ray-project/ray/blob/32cddaecac648fe663c2fef2e7ea8f24e03b234c/python/ray/_raylet.pyx#L1800-L1832

And in fact, if you look at the flamegraph, you'll see a bunch of other calls to similar functions from the `inspect` module which I believe map to other calls in this part of the Raylet. I suspect that these calls appear to come from nowhere in the flamegraph because I'm not running with `py-spy --native`, and the caller is a Cython function, so it won't appear in the stack trace.

I doubt these are very relevant in terms of latency, but they show up as a significant fraction of total time here (probably 5-10%) because the Controller is being hammered with RPCs for what is ultimately a cheap function call (see https://github.com/ray-project/ray/issues/45777).

Looking at the actual code, one solution that jumps out to me is caching. For example, https://github.com/ray-project/ray/blob/035224b52558047d2bb21df415ca75b2f91f0d4c/python/ray/_private/async_compat.py#L30-L32 can be cached - a function's `async`-ness is determined at creation time and can't change later under normal circumstances.

At a higher level, though it's possible for https://github.com/ray-project/ray/blob/32cddaecac648fe663c2fef2e7ea8f24e03b234c/python/ray/_raylet.pyx#L1801-L1803 to change after a class is defined (e.g., by dynamically adding a method to it), it seems like a reasonable restriction to base it on whether the class has any statically-defined `async` methods, so this could be calculated once during actor startup and saved for later.

https://github.com/ray-project/ray/blob/035224b52558047d2bb21df415ca75b2f91f0d4c/python/ray/_private/async_compat.py#L35-L44 Could also potentially be cached, so that you don't need to create a fresh wrapper function on every call to the same method.

I won't get too prescriptive and you may have better ways to profile what's happening here than I do so I'll stop there, but TLDR: doing all this checking over and over is surprisingly time-intensive!

### Use case

This would have a marginal latency improvement for any RPCs and seems especially relevant for high-throughput use cases where this becomes a non-trivial fraction of total time spent on a busy actor serving cheap requests (here it's `ServeController.record_handle_metrics`).

**Comment by JoshKarpel** [comment]
cc @edoakes @zcin , re: Serve Controller scaling

**Comment by jjyao** [comment]
@JoshKarpel Nice investigation. Would you mind creating the PR for this issue? We are happy to review it.

**Comment by JoshKarpel** [comment]
@jjyao I've got a few other performance issues that are higher priority for me at the moment, but I can work on this at some point
