### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by Lionss3000** [ray-project/ray#45856]
### Description

 File "D:\AI\Multi-agent Stock Trading\Multi-agent-Stock-Trading1", line 80, in <module>
    import ray
ModuleNotFoundError: No module named 'ray'

### Use case

2. 定义多智能体系统
使用 RLlib 来设置多个智能体，并配置不同的量化交易模型。

"""

import ray

**Comment by simonsays1980** [comment]
This is the `Ray project` github repository. What you are mentioning above is a another repo that is importing `ray`. You need to isntall ray first via `python -m pip install "ray[default,rllib,tune]"` from the command line.
