### ISSUE TITLE
Missleading information in doc and tutorial related to GPU usage

### ISSUE THREAD

**Issue by PgLoLo** [ray-project/ray#4587]
Both in documentation and examples (and pretty much everywhere where I was able to find the information) mentioned, that the user should control GPU usage by himself inside actors and remote functions that require GPUs (e.g. by setting CUDA_VISIBLE_DEVICE environment variable). 

Which is only partially true: according to my testing and [this](https://github.com/ray-project/ray/issues/975) issue, ray framework sets this variable by itself. It is VERY misleading and should be changed either in documentation and examples or in the behavior of ray.

Furthermore, in my opinion, this behaviour is very inconvenient, because nowadays frameworks (pytorch and tensorflow) gives an opportunity to control GPU usage not only by an environment variable. Also this behaviour overnight the CUDA_VISIBLE_DEVICE passed to the python program from the outside which prevents such a convenient way of limiting the program GPU usage to only the specific ones.

**Comment by ericl** [comment]
Could you provide links to the doc pages that should be changed?

By the way, if you set CUDA_VISIBLE_DEVICES then Ray will restrict scheduling to those specific GPUs. So it does work naturally for controlling GPU usage.
