### ISSUE TITLE
[docs] Column size for cards are not equal

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#45876]
### Description

Index page cards responsiveness behavior makes `Ray Clusters` card narrower than the `Ray Core` and `Ray Libraries` cards.
cc: @simran-2797 @cuong @peytondmurray 

<img width="1068" alt="Screenshot 2024-06-11 at 1 20 18 PM" src="https://github.com/ray-project/ray/assets/122562471/febc0d84-86be-4464-affc-335775d4e22b">

### Link

docs.ray.io

**Comment by simran-2797** [comment]
All the cards should be of the same width. If the page is divided into 12 columns, each card should occupy 4 cols.
