### ISSUE TITLE
[Core] ray.exceptions.RpcError: Sent message larger than max

### ISSUE THREAD

**Issue by tongtz** [ray-project/ray#45884]
### What happened + What you expected to happen

RpcError                                  Traceback (most recent call last)
File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\experiment\experiment.py:219, in Experiment.__init__(self, name, run, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, _experiment_checkpoint_dir, sync_config, checkpoint_config, trial_name_creator, trial_dirname_creator, log_to_file, export_formats, max_failures, restore, local_dir)
    218 try:
--> 219     self._run_identifier = Experiment.register_if_needed(run)
    220 except RpcError as e:

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\experiment\experiment.py:411, in Experiment.register_if_needed(cls, run_object)
    410 try:
--> 411     register_trainable(name, run_object)
    412 except (TypeError, PicklingError) as e:

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py:112, in register_trainable(name, trainable, warn)
    111     raise TypeError("Second argument must be convertable to Trainable", trainable)
--> 112 _global_registry.register(TRAINABLE_CLASS, name, trainable)

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py:239, in _Registry.register(self, category, key, value)
    238 if _internal_kv_initialized():
--> 239     self.flush_values()

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py:277, in _Registry.flush_values(self)
    276 for (category, key), value in self._to_flush.items():
--> 277     _internal_kv_put(
    278         _make_key(self.prefix, category, key), value, overwrite=True
    279     )
    280     self._registered.add((category, key))

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\_private\client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\experimental\internal_kv.py:94, in _internal_kv_put(key, value, overwrite, namespace)
     89 assert (
     90     isinstance(key, bytes)
     91     and isinstance(value, bytes)
     92     and isinstance(overwrite, bool)
     93 )
---> 94 return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0

File python\ray\_raylet.pyx:2143, in ray._raylet._auto_reconnect.wrapper()

File python\ray\_raylet.pyx:2120, in ray._raylet._auto_reconnect.wrapper()

File python\ray\_raylet.pyx:2221, in ray._raylet.GcsClient.internal_kv_put()

File python\ray\_raylet.pyx:410, in ray._raylet.check_status()

RpcError: Sent message larger than max (1624591702 vs. 536870912)

During handling of the above exception, another exception occurred:

TuneError                                 Traceback (most recent call last)
Cell In[16], line 56
     24 search_space = {
     25                 "learning_rate": tune.loguniform(1e-5, 1e-2),
     26                 "weight_decay": tune.loguniform(1e-5, 0.5),
   (...)
     29                 "neuron_decrease_rate": tune.choice([1]),
     30         }
     32 # tuner = tune.Tuner(
     33 #     tune.with_resources(
     34 #             tune.with_parameters(train_model),
   (...)
     54 
     55 # See the list of all search algorithms here: https://docs.ray.io/en/latest/tune/api_docs/suggestion.html
---> 56 analysis = tune.run(
     57         tune.with_parameters(train_model),   # the core training/testing of your model
     58 #         tune.with_resources(
     59 #             tune.with_parameters(train_model),
     60 #             resources={"cpu": cpu_cnt - 2, "gpu": gpu_cnt}),
     61         local_dir=os.getcwd(), # for saving the log files
     62         name="model_log", # name for the result directory
     63         metric='mean_f1',
     64         mode='max',
     65         search_alg=algo,
     66         scheduler=sched,
     67         stop = TrialPlateauStopper(metric = 'training_loss', grace_period = 3, mode = 'min'),
     68         # stop={  
     69                 # "mean_f1": 0.98,
     70                 # "training_iteration": 30  # number of epochs
     71           # },
     72         resources_per_trial={
     73                 "cpu": cpu_cnt - 2,
     74                 "gpu": gpu_cnt
     75          },
     76     num_samples=10, # how many hyperparameter combinations to try, can set to 30
     77     config=search_space,
     78     # keep_checkpoints_num=1, checkpoint_score_attr="mean_f1",
     79     callbacks=[MLflowLoggerCallback(
     80             experiment_name=experiment_name,
     81             save_artifact=False)],
     82 )
     83 print("Best config is:", analysis.best_config)
     84 ray.shutdown()

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\tune.py:857, in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, search_alg, scheduler, checkpoint_config, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, chdir_to_trial_dir, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, raise_on_failed_trial, callbacks, max_concurrent_trials, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, checkpoint_keep_all_ranks, checkpoint_upload_from_workers, trial_executor, local_dir, _experiment_checkpoint_dir, _remote, _remote_string_queue, _entrypoint)
    855 for i, exp in enumerate(experiments):
    856     if not isinstance(exp, Experiment):
--> 857         experiments[i] = Experiment(
    858             name=name,
    859             run=exp,
    860             stop=stop,
    861             time_budget_s=time_budget_s,
    862             config=config,
    863             resources_per_trial=resources_per_trial,
    864             num_samples=num_samples,
    865             storage_path=storage_path,
    866             _experiment_checkpoint_dir=_experiment_checkpoint_dir,
    867             sync_config=sync_config,
    868             checkpoint_config=checkpoint_config,
    869             trial_name_creator=trial_name_creator,
    870             trial_dirname_creator=trial_dirname_creator,
    871             log_to_file=log_to_file,
    872             export_formats=export_formats,
    873             max_failures=max_failures,
    874             restore=restore,
    875         )
    877 if fail_fast and max_failures != 0:
    878     raise ValueError("max_failures must be 0 if fail_fast=True.")

File ~\AppData\Local\anaconda3\Lib\site-packages\ray\tune\experiment\experiment.py:222, in Experiment.__init__(self, name, run, stop, time_budget_s, config, resources_per_trial, num_samples, storage_path, _experiment_checkpoint_dir, sync_config, checkpoint_config, trial_name_creator, trial_dirname_creator, log_to_file, export_formats, max_failures, restore, local_dir)
    220 except RpcError as e:
    221     if e.rpc_code == grpc.StatusCode.RESOURCE_EXHAUSTED.value[0]:
--> 222         raise TuneError(
    223             f"The Trainable/training function is too large for grpc resource "
    224             f"limit. Check that its definition is not implicitly capturing a "
    225             f"large array or other object in scope. "
    226             f"Tip: use tune.with_parameters() to put large objects "
    227             f"in the Ray object store. \n"
    228             f"Original exception: {traceback.format_exc()}"
    229         )
    230     else:
    231         raise e

TuneError: The Trainable/training function is too large for grpc resource limit. Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use tune.with_parameters() to put large objects in the Ray object store. 
Original exception: Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\tune\experiment\experiment.py", line 219, in __init__
    self._run_identifier = Experiment.register_if_needed(run)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\tune\experiment\experiment.py", line 411, in register_if_needed
    register_trainable(name, run_object)
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py", line 112, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py", line 239, in register
    self.flush_values()
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\tune\registry.py", line 277, in flush_values
    _internal_kv_put(
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\anaconda3\Lib\site-packages\ray\experimental\internal_kv.py", line 94, in _internal_kv_put
    return global_gcs_client.internal_kv_put(key, value, overwrite, namespace) == 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python\ray\_raylet.pyx", line 2143, in ray._raylet._auto_reconnect.wrapper
  File "python\ray\_raylet.pyx", line 2120, in ray._raylet._auto_reconnect.wrapper
  File "python\ray\_raylet.pyx", line 2221, in ray._raylet.GcsClient.internal_kv_put
  File "python\ray\_raylet.pyx", line 410, in ray._raylet.check_status
ray.exceptions.RpcError: Sent message larger than max (1624591702 vs. 536870912)

### Versions / Dependencies

ray == 2.6.0 or ray==2.10.0 has the same issue.
With the same set of data, I used to be able to run it in Feb 2024

### Reproduction script

analysis = tune.run(
        tune.with_parameters(train_model),   # the core training/testing of your model
        local_dir=os.getcwd(), # for saving the log files
        name="model_log", # name for the result directory
        metric='mean_f1',
        mode='max',
        search_alg=algo,
        scheduler=sched,
        stop = TrialPlateauStopper(metric = 'training_loss', grace_period = 3, mode = 'min'),
        # stop={  
                # "mean_f1": 0.98,
                # "training_iteration": 30  # number of epochs
          # },
        resources_per_trial={
                "cpu": cpu_cnt - 2,
                "gpu": gpu_cnt
         },
    num_samples=10, # how many hyperparameter combinations to try, can set to 30
    config=search_space,
    # keep_checkpoints_num=1, checkpoint_score_attr="mean_f1",
    callbacks=[MLflowLoggerCallback(
            experiment_name=experiment_name,
            save_artifact=False)],
)

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@tongtz can you try on the latest ray release (2.25 I think..)

**Comment by ruisearch42** [comment]
This could have been fixed in later versions: https://github.com/ray-project/ray/pull/43234

@tongtz can you try with latest Ray?

**Comment by tongtz** [comment]
This is solved after I remove some loaded pretrained model from the pipeline.

**Comment by tongtz** [comment]
This is solved after I remove some loaded pretrained model from the pipeline.
