### ISSUE TITLE
Improve task metrics graphs

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#45908]
1. Rename "Active tasks by name" to something like "requested tasks". Make it clear that they do not refer to running tasks but any tasks that has been requested to be sheduled.

2. Add a graph for "Running tasks by name" that doesn't include finished tasks

3. Rename "Active actors by name"

4. Add a graph for "rate of finished tasks per second", and "rate of started tasks per second"

![Image](https://github.com/ray-project/ray/assets/711935/683eae93-6dbd-4efe-97fb-842f19203af0)

**Comment by krtkvrm** [comment]
can I take this up ?

**Comment by alanwguo** [comment]
@krtkvrm. Yes, feel free to an open a PR!
