### ISSUE TITLE
[Core] conda package outdated

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#45900]
### What happened + What you expected to happen

conda packages are at version 2.23.0 whereas the latest release (a Week ago) is 2.24.0

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by anyscalesam** [comment]
@jmakov are you blocked by this; does upgrading the conda env post install via pip or other package managers run into conflicts/break the ray installation?

**Comment by jmakov** [comment]
@anyscalesam I'm maintaining a venv with a lot of packages and we try to keep everything up to date. The probl with ray is that every release fixes a couple of fundamental issues e.g. `ray up` still doesn't work, other on prem basic issues etc. so not having access to the latest version is a blocker, yes.

**Comment by jmakov** [comment]
I see currently the package versions match again. I'll close the issue.
