### ISSUE TITLE
[autoscaler] `ray attach CLUSTER.YAML --docker` 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4599]
It would be great to support this. 

This is related to #4183

**Comment by 7vikpeculiar** [comment]
Hi, can I work on this ?

**Comment by richardliaw** [comment]
Yes! That’d be awesome! Can you open a WIP PR as soon as possible (within the day or two)?

**Comment by 7vikpeculiar** [comment]
@richardliaw  can you tell me what needs to be done ?

**Comment by 7vikpeculiar** [comment]
I tried running the repo locally using [this](https://ray.readthedocs.io/en/latest/installation.html)

**Comment by ijrsvt** [comment]
This has been fixed long ago
