### ISSUE TITLE
Check that all nodes in a cluster are running the same Ray version

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#460]
We should make sure that problems like this don't happen:

https://github.com/ray-project/ray/issues/458

This probably involves checking that all git commit hashes (or release tags if Ray will be installed using pip or from a release tarball) in the cluster agree.

**Comment by robertnishihara** [comment]
This was also the purpose of having `RAY_PROTOCOL_VERSION` in `src/common/io.h`, but for that to be useful we need to increment the value at every commit.

**Comment by robertnishihara** [comment]
Let's track this separately in #1183.
