### ISSUE TITLE
[tune] Exposing the logger variable

### ISSUE THREAD

**Issue by stevenlin1111** [ray-project/ray#4610]
It would be nice if modifications to `result_logger` variable could be made in the middle of a trial. A use case would be if I have sequential sections to my trial and want different logging files for each section (e.g `part_1_progress.csv`, `part_2_progress.csv`).

**Comment by richardliaw** [comment]
oh you can do this with a custom logger

I would have the result_dict include some notification boolean that the custom logger uses to create a new file.

See: https://ray.readthedocs.io/en/latest/tune-usage.html (Custom logging section) and https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/logging_example.py

Let me know if that helps!

**Comment by stevenlin1111** [comment]
Ah yes this makes sense. Thanks!
