### ISSUE TITLE
[Ray Assistant] [Docs] broken copy button

### ISSUE THREAD

**Issue by angelinalg** [ray-project/ray#46137]
### Description

If I run the Ask AI from this page: [https://docs.ray.io/en/latest/ray-core/api/doc/ray.runtime_context.RuntimeContext.current_actor.html#ray-runtime-context-ru[…]econtext-current-actor](https://docs.ray.io/en/latest/ray-core/api/doc/ray.runtime_context.RuntimeContext.current_actor.html#ray-runtime-context-runtimecontext-current-actor)
And then ask it If I have an ActorHandle, how can I extract the underlying type of the actor?
cc: @brent-anyscale @can-anyscale @peytondmurray 

### Link

![image (10)](https://github.com/ray-project/ray/assets/122562471/571763bd-b87a-4aec-b644-23637f376a14)

**Comment by cristianjd** [comment]
Fixed with PR
