### ISSUE TITLE
[Data] read_parquet with shuffle="files" has not seed option

### ISSUE THREAD

**Issue by berangerd** [ray-project/ray#46177]
### What happened + What you expected to happen

Calling [ray.data.read_parquet](https://docs.ray.io/en/latest/data/api/doc/ray.data.read_parquet.html) with `shuffle="files"` calls `np.random.default_rng()` with no argument, see https://github.com/ray-project/ray/blob/9d661677f942ccd7dfbbf2c2838e5dad9f50d12e/python/ray/data/datasource/parquet_datasource.py#L304

It makes it impossible to have a deterministic behavior across runs since, as per [numpy.random.default_rng](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng), if the `seed` parameter is `None`, "fresh, unpredictable entropy will be pulled from the OS."

Would it be possible to add an optional integer `seed` parameter to Ray Data's `read_parquet` that would be forwarded to NumPy's `random.default_rng` to ensure reproducibility when needed?

### Versions / Dependencies

Ray 2.30, any OS and version of Python, any recent version of NumPy (not specific to 2.0).

### Reproduction script

```
ray.data.read_parquet(..., shuffle="files")
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anrooo** [comment]
Also would love to see this implemented across all file modes, uncontrollable randomness generally is anathema to good ML work.
