### ISSUE TITLE
CI test windows://python/ray/tests:kuberay/test_autoscaling_config is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#46178]
CI test **windows://python/ray/tests:kuberay/test_autoscaling_config** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/5048#01903931-0e65-4035-9011-4ff2141e9861
	- https://buildkite.com/ray-project/postmerge/builds/5053#01903b8e-545e-4ad1-8df8-12b0c071ee20

DataCaseName-windows://python/ray/tests:kuberay/test_autoscaling_config-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by can-anyscale** [comment]
Blamed commit: 50cbe6a709633eaa7371ec40b356978e6ad1512d found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1262

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/5030#01903667-1177-4a70-a938-aa9291f7f774

**Comment by can-anyscale** [comment]
CI test **windows://python/ray/tests:kuberay/test_autoscaling_config** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/5094#01904b2d-09bc-4ca4-8c57-6088ba3dd70f
	- https://buildkite.com/ray-project/postmerge/builds/5094#01904b02-b67f-49d4-a91a-429303a0427c

DataCaseName-windows://python/ray/tests:kuberay/test_autoscaling_config-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: c942d6038ac9d209cbca6d6c8fbca7ca218f8c5f found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1272

**Comment by kevin85421** [comment]
I will take a look.

**Comment by kevin85421** [comment]
Open a PR https://github.com/ray-project/ray/pull/46245

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/5129#0190554d-f214-497b-b34e-57d9c9336144
