### ISSUE TITLE
[Docs] Have latest minor version sorted on the top in the version navigation window

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#46189]
### Description

Since we had 2 digit minor version, the sorting in the navigation window of the doc pages has been sorting the latest version in between their single digit counterparts instead of on the top. Would be nice to see for example 2.30.0 on the top of the window instead of seeing 2.9.3 on the top.

![image (46)](https://github.com/ray-project/ray/assets/7553988/6ac8a4f5-ea46-4581-b270-04d3ef857728)

**Comment by angelinalg** [comment]
cc: @peytondmurray
