### ISSUE TITLE
[Doc] Use make clean instead of git clean

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/ray#46206]
### Description

The [troubleshooting section of the ducumentation](https://docs.ray.io/en/latest/ray-contribute/docs.html#troubleshooting) tells us to use `git clean` to clean build artifacts instead of `make clean`. However, this only works for `conda` environment. If developers use `pyenv` or `virtualenv`, the  `.venv/` folder and the `.python-version` file will be deleted, which causes problem. Therefore, it is better to write down which files to be deleted more completely in `Makefile` `clean` target instead of asking developers to run `git clean`.

Note: I am willing to work on this issue.

**Comment by angelinalg** [comment]
Thank you for filing this issue. @peytondmurray, I think you may have suggested `git clean`. Could you comment on this? Thanks! cc: @can-anyscale
