### ISSUE TITLE
[Ray Core] Get the list of failed remote tasks

### ISSUE THREAD

**Issue by yx367563** [ray-project/ray#46244]
### Description

In a Ray Job there will be a large number of remote tasks, for which eventually failed tasks, is there a way to get or export from the dashboard, if there are more failed tasks, manually count all the eventually failed tasks will be more troublesome

**Comment by jjyao** [comment]
You can use state api:

```
ray list tasks --filter="state=FAILED"
```

**Comment by yx367563** [comment]
In fact, this instruction displays all Tasks that have failed, including those that were eventually retried successfully, and the user only cares about those that ultimately failed
