### ISSUE TITLE
Warning printed when doing specific tab completions.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#4624]
I see the following warning printed when doing tab complete in IPython (sometimes).

*2019-04-14 06:51:31,696	WARNING worker.py:201 -- Calling ray.get or ray.wait in a separate thread may lead to deadlock if the main thread blocks on this thread and there are not enough resources to execute more tasks*

I can reproduce this on Linux (Ubuntu 16.04) with Python 3.6.3 (Anaconda) in IPython 6.1.0 by doing the following

1. Start `ipython`
2. Do `import ray`
3. Type `ray.worker.global_worker.`
4. Hit **tab** to autocomplete

That prints the warning (at least the first time I do it).

The relevant code block is 

https://github.com/ray-project/ray/blob/3838548356f9b186ca2ba0265d587f29a124e88e/python/ray/worker.py#L174-L210

cc @guoyuhong

**Comment by guoyuhong** [comment]
Do you think this is related to https://github.com/ray-project/ray/pull/4499 ?

**Comment by guoyuhong** [comment]
I don't have a machine like that. In my Mac and the CentOS like PC, I cannot repro that. I tried to repro that in a ubuntu 16.04 docker image. I cannot repro that either.

**Comment by robertnishihara** [comment]
Hm, I'm having trouble reproducing it now as well. I'll close this for now, but I suspect the issue is still around somewhere.
