### ISSUE TITLE
[<Ray component: RLlib] module 'numpy' has no attribute 'product'

### ISSUE THREAD

**Issue by revealAi** [ray-project/ray#46250]
### What happened + What you expected to happen

Cannot use Ray RLlib with numpy version 2.0. 

### Versions / Dependencies

ray[rllib]==2.30.0
numpy==2.0

### Reproduction script

pip3 install ray[rllib]==2.30.0 numpy==2.0

Run any examples that use RLlib.

### Issue Severity

High: It blocks me from completing my task.

**Comment by simonsays1980** [comment]
@revealAi Thanks for raising this issue. The mentioned PR should fix this error. These errors should however only occur in our old stack. Using the new stack should have `np.prod` in all logic. Maybe you want to give it a try.

**Comment by sven1977** [comment]
If you can't move to the latest master (the above PR will be merged any hour now), can you try:

```
pip install numpy==1.24.3
```

That fixed it in my case (being on an older RLlib version).

**Comment by sven1977** [comment]
Closing this issue.
