### ISSUE TITLE
[in-progress] Readers across different nodes - ADAG Developer Preview - Test Coverage

### ISSUE THREAD

**Issue by anyscalesam** [ray-project/ray#46269]
aDAG nodes can be read by multiple remote actors, but right now this only works if the remote actors are all on the same node.

**Comment by anyscalesam** [comment]
Throwing exception for now; probably good enough for Developer Preview... (not blocking). If we have time after test_channel try to get this one in.

**Comment by rkooo567** [comment]
can anyone give me some more context? @kevin85421 ?
