### ISSUE TITLE
[rllib] agents dies at time T, should the environment return obs after that?

### ISSUE THREAD

**Issue by PengZhenghao** [ray-project/ray#4627]
Not a software engineering issue. Just confusing on the output of environments.

Let's clarify the RLlib principles for a custom multi-agent environment:

1. Obs and Reward should have the same keys.
2. Infos's keys must be a subset of Obs.
3. For the convenient for post-processing the observation, the observation should basically have same shape, and must be numpy array (That means, None is not allow).
4. The `sampler` will take action for those agents whose keys appear in `Obs.keys()`.

Hope I understand everything correctly.

Now, suppose at timestep T, an agent die. More concretely, **it dies due to it's action at timestep T-1.** 

Therefore, the reward related to this action 'r(s_{t-1}, a_{t-1})' have to be calculated at timestep T, companied with the `done^{T}_{agent} = True` This means that the reward should be return in the next frame, namely the timestep T.

However, in Gym scenario, it's necessary to return a reward as well as an observation (at timestep T).

Now the strange thing happen: In order to get the final reward, which is important to evaluate the agent's final action at timestep T-1, we have to return the reward, as well as the observation at timestep T (Due to the principle 1 and 3).

However, the agent has dead before timestep T, so it's inappropriate / impossible to take an action at timestep T. But according to principle 4, RLlib sampler will still take action at timestep T according to the observation it receives (even though the observation is "the dying moment", and is not asked for further action).

This issue confuses me because: 

1. I am writing a custom multi-agent environment which add a check in it's `step` function, requiring the keys of input `action_dicts` should not include the keys of agents already dead, because it's impossible to process the actions of a dead agent. (My current workaround is to ignore those action).
2. I have a dead penalty for those agents who die because of their stupid actions, therefore the rewards after their 'dead-causing action' are important and have to be returned.

Maybe I am not correctly understand the whole process. I don't know what's the best practice since there are no multi-agent custom environment examples.

Hope somebody may clarify the whole process. Thanks!

**Comment by ericl** [comment]
Hm, is principle (4) correct? While an obs is returned for done agents in gym (which is a bit odd), I think these obs are ignored in the sampler if the agent is done:

https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/sampler.py#L414

If you have a script where an agent is getting an action from the sampler even after it set done=True in the last step, that would be useful to help reproduce. Btw I'm a bit confused by your example, are you saying the "dying" is delayed by 1 step so you can't return done=True at T-1? In that case it sounds like what you're currently doing is fine.

**Comment by PengZhenghao** [comment]
I made mistake on "principle 4", as the codes show what going on.

Saying "die at timestep T-1", I means the `done=True` and `reward=dead penalty` should be returned after the action `a_{t-1}` conducted. So more precisely saying, the transition at timestep T-1 to timestep T is: 

```
o_{t-1},
 a_{t-1}=dead-causing action,
 done_{T-1}=True,
 rew_{T-1}=dead penalty,
 o_{T}=the observation after agent die, required no further response
```.

It's my fault messing up the notation. Never mind. The reason is in Gym perspective, the `r_{T-1}, done_{T-1}` is computed by the `env.step(a_{T-1})` function. What I mean by saying timestep above is more like the procedure of what program is doing. Just ignore what I saying is you still confused...

Back to our topic, so RLlib really required an observation when returning `done=True` in MultiAgent scenario, even though this observation seems not be used in training (because all data should have same length, so `len(feed_actions)==len(feed_observation)`). Am I correct? 

PS: When looking this problem in the single agent base, everything seems to be natural..... Sorry for this naive problem.

**Comment by ericl** [comment]
Yeah, I think the last observation is not that useful for training. It can be set to all zeros or anything convenient.
