### ISSUE TITLE
[rllib] misleading sample_batch_size and train_batch_size in Multi-agent scenario.

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#4628]
Note that this is a different issue with #2957.

In multi-agent scenario, the `sample_batch_size` is the number of **environment steps** sampled from **each environment**, and the `train_batch_size` is the number of **environment steps** sampled from all available environments.

From standard single agent scenario these two words seems reasonable, since the data used to train the neural network has exactly the same number of the steps that be conducted in the environment.

But for the multi-agent scenario, the number of "data" fed to the neural network is **train_batch_size * num_agents_in_each_environment** (supposing the number of agents is a constant).

Those conclusion comes from the PPO implementation, I'm not sure what others algorithm does. I hope I understand things correctly.

I suggest to change the names of these two parameter to `sample_env_steps` and `train_env_steps`, or using a new parameter who have same name `train_batch_size` but automatically divided by `num_agents` in multiagent scenario, in order to be consist to the common understanding, or simply add more explanations in docs on this topic.

**Comment by ericl** [comment]
Yeah some renaming here makes sense. Another possibility is `sample_batch_size => env_unroll_length`, and `train_batch_size => train_env_steps`. I'm not sure if a standard convention has emerged in the community here.

**Comment by Rendok** [comment]
These names are very misleading even in a single agent environment

**Comment by richardliaw** [comment]
fixed!
