### ISSUE TITLE
[core] Cancelling tasks who is waiting for dependencies hangs result objects

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#46315]
### What happened + What you expected to happen

When you have a task returning a Ray Object, and the task is in "waiting dependencies" status; and you do `ray.cancel(ref)` on the ref. You expect the next `ray.get(ref)` raises `TaskCancelledError` but it hangs now.

This issue also applies for streaming generators, and when the task is resubmitted via lineage reconstruction.

This comes from https://github.com/ray-project/ray/blob/755a49bbc2345650ff90d4706d9c69f87b8a77bd/src/ray/core_worker/transport/direct_task_transport.cc#L798-L799

where if a task being cancelled have unresolved deps, it *does noop*.

This may be true in 4 yrs ago, but now we need to fail the task and mark all objects as failed with the exception.

### Versions / Dependencies

master

### Reproduction script

Run this script multiple times, it's 70% hanging and 30% passing.

```py
import ray
import numpy as np
import pytest
from ray._private.test_utils import SignalActor
import time

def test_cancel_pending_arg_running():
    with ray.init():
        @ray.remote(max_retries=-1)
        def wait_forever():
            print("wait_and_reset starting")
            while True:
                time.sleep(10000)

        @ray.remote(max_retries=-1)
        def has_deps(may_block):
            big = may_block
            return big * 2

        may_block = wait_forever.remote()
        ref = has_deps.remote(may_block)
        print(f"{ref=}")
        
        ready, not_ready = ray.wait([may_block, ref], timeout=1)
        assert not ready
        assert len(not_ready) == 2
        print(f"both are not ready: {may_block=}, {ref=}")

        # Now, the generator is pending arg. Cancel it.
        print("Cancelling")
        ray.cancel(ref)

        print("Getting")
        with pytest.raises(ray.exceptions.TaskCancelledError):
            ray.get(ref)  # This should raise TaskCancelledError, but hangs


if __name__ == "__main__":
    import os,sys

    if os.environ.get("PARALLEL_CI"):
        sys.exit(pytest.main(["-n", "auto", "--boxed", "-vs", __file__]))
    else:
        sys.exit(pytest.main(["-sv", __file__]))

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by dayshah** [comment]
@rynewang is this the same issue as https://github.com/ray-project/ray/issues/47649?

**Comment by rynewang** [comment]
I don't think so. The mentioned issue is about we have all handling code, just they deadlocked. This issue is about not really cancelling the task. I think even with https://github.com/ray-project/ray/pull/47833 this issue is not resolved. But you can do a test - if it magically solved then it's great!
