### ISSUE TITLE
No `log_to_driver` option in cli mode

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#4632]
When running `ray start` in command line mode, there isn't a `log_to_driver` option. Specifically, I'm looking for a way to easily disable `log_to_driver` on worker node. 

Context:
- PR #3892 was merged to provide log_to_driver option

**Comment by robertnishihara** [comment]
`ray start` starts up the cluster. Then many drivers can attach, and each driver needs to decide individually whether it wants to disable logging or not. So `log_to_driver` really only makes sense for a driver and not for `ray start`.

**Comment by simon-mo** [comment]
But is it possible to turn off log monitor and reporter in worker node? They used up CPU and redid resources. I observed a 5% constant utilization in one of the process. Because redis is event-loop based, the pub sub mechanism using to send logs also delay other GCS lookup.

**Comment by robertnishihara** [comment]
Philosophically, the way I'd prefer to deal with performance issues is by making the code fast/optimized as opposed to be providing options to turn off the various features. This discussion also came up with regard to profiling. There are times when you need the code to be fast and you also need logging, the dashboard, profiling, etc. If people turn off whatever features they don't need at the moment, then the features are much less likely to get faster.

That said, if there's some fundamental reason why we can't make the code faster, we can consider providing a flag to turn it off.

**Comment by mitar** [comment]
My reason for turning this of is because we are collecting and storing all logs ourselves already. So there is no need for duplicate logging.

**Comment by robertnishihara** [comment]
@mitar, sure there is no benefit to it, but is there any cost?

**Comment by mitar** [comment]
Hm, sending packages to Redis, I would guess it is? At least @simon-mo says 5% constant utilization. But I have not measured it myself.

**Comment by simon-mo** [comment]
Closing as the performance issue is stale and probably doesn't apply in Ray 1.0

**Comment by mitar** [comment]
There is no more central log collecting in Ray 1.0? Because if it is, it still applies.
