### ISSUE TITLE
How to guarantee the actor was shutted down?

### ISSUE THREAD

**Issue by PgLoLo** [ray-project/ray#4635]
I have an actor that performs some work with csv.writer. I read that actor should be destroyed right after the objects goes out of scope but it looks like it's not the case: csv.writer is not flushed after the actor goes out of scope.

How can I wait until the actor is completely destroyed?

**Comment by robertnishihara** [comment]
Can you post a runnable example that reproduces the issue?

If you want to manually kill an actor, you can either call `actor_handle.__ray_terminate__.remote()`. The default behavior is for the actor to be destroyed once `actor_handle` gets garbage collected (if you're using Python 2, then the timing of this can be a little unpredictable).

**Comment by richardliaw** [comment]
closing because stale.
