### ISSUE TITLE
[rllib] role of the train_batch_size in the A3C implementation

### ISSUE THREAD

**Issue by joonleesky** [ray-project/ray#4636]
In rllib.optimizers.AsyncGradientsOptimizer, 
`for e in self.remote_evaluators: `
&nbsp; &nbsp; `e.set_weights.remote(weights)`
&nbsp; &nbsp; `future = e.compute_gradients.remote(e.sample.remote())`
&nbsp; &nbsp; `pending_gradients[future] = e`
&nbsp; &nbsp; `num_gradients += 1`

Gradient updates seem to be based on the sample_batch_size and replacing the remote worker's weights seems to be based on the grads_per_step. <br>
What is the role of the train_batch_size in the A3C algorithm?
Can I think the train_batch_size is just equal to the sample_batch_size in this implementation?

Thank you!

**Comment by ericl** [comment]
I don't think that config is used by A3C.
