### ISSUE TITLE
[tune] trial state upon interruption of tune.run

### ISSUE THREAD

**Issue by to266** [ray-project/ray#4637]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary (pip)
- **Ray version**: 0.6.5
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem

This is actually a question/request. What happens is:

1. Run `ray.tune.run(MyTrainable, **other_args)`.
2. While (1) is training, interrupt (CTRL+C or some other signal).
3. The current state of the trials gets lost. I would like to be able to get/manipulate the runner state after the interrupt. 

Example usecase: graceful shutdown, where upon the interrupt all trials are investigated, and the best one (whatever it might mean) is checkpointed to a new location, for example `current-best` folder.

afaik currently to emulate behavior, either:
 - the logs in `local_dir` should be parsed manually, which is highly inconvenient, or
 - Instead of `ray.tune.run`, I would have to use my own function, which is nearly identical, except returns `runner.get_trials()` not only upon success, but also upon interrupts.

**Comment by richardliaw** [comment]
I think this should be addressed with the new Analysis/ExperimentAnalysis API.
