### ISSUE TITLE
[runtime_env] Passing NFS path to runtime_env raises error due to ValueError: ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#46379]
### What happened + What you expected to happen

To `ray.init(runtime_env={"working_dir": X})`, pass a path which has timestamps of zero (e.g., 1970). This can happen for NFS mounts often.

Ray will raise RuntimeEnvSetupError in:
```
ray/_private/runtime_env/packaging.py:531, in create_package(directory, target_path, include_parent_dir, excludes, logger)
    530 logger.info(f"Creating a file package for local directory '{directory}'.")
--> 531 _zip_directory(
    532     directory,
    533     excludes,
    534     target_path,
    535     include_parent_dir=include_parent_dir,
    536     logger=logger,
    537 )
...
File /usr/lib/python3.10/zipfile.py:364, in ZipInfo.__init__(self, filename, date_time)
    363 if date_time[0] < 1980:
--> 364     raise ValueError('ZIP does not support timestamps before 1980')
    366 # Standard values:
ValueError: ZIP does not support timestamps before 1980
```

### Versions / Dependencies

Latest Ray

### Reproduction script

This could probably be reproduced locally by manually setting the timestamps of a dir to 1970.

### Issue Severity

High: It blocks me from completing my task.

**Comment by ericl** [comment]
cc @edoakes

**Comment by pcmoritz** [comment]
@ericl Do you want to submit a patch? If yes I can review / merge it :)

**Comment by ericl** [comment]
Hey @pcmoritz, I don't have the bandwidth to work on Ray patches at the moment, but if it helps I can report that multiple users have run into this issue in the last few weeks.

**Comment by richardliaw** [comment]
seems like a 1-line change (strict_timestamps=False, for everywhere we use ZipFiles)?

@jjyao can someone on core team submit a quick PR?
