### ISSUE TITLE
[Data] Unclear what "it" represents in progress bars

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#46383]
## Description
Ray Data progress bars use the `tqdm` library, which outputs information related to iteration speeds:
```
- ReadParquet->SplitBlocks(67): 1 active, 0 queued, [cpu: 1.0, objects: 311.6MB]: 100%|██████████| 222/222 [00:09<00:00, 28.29it/s]
```

This is denoted with the `it/s` notation, which is not very clear what this means from Ray Data's perspective. We should modify this output to something more informative, such as `blocks/s` or `batches/s`. We can update the `unit` in `tqdm` call: https://tqdm.github.io/docs/tqdm/#format_meter

## Use case
Better understand Ray Data progress

**Comment by bt2513** [comment]
Hi! If no one is currently working on this issue, I would be happy to take it as a first contribution :)

**Comment by scottjlee** [comment]
@bt2513 yes definitely welcome to take this issue! please let us know if you have any questions
