### ISSUE TITLE
MemoryMonitor uses print instead of logger

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#4640]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.1
- **Python version**: 3.6.7

### Describe the problem

```
print("WARNING: Not monitoring node memory since `psutil` is not "
                  "installed. Install this with `pip install psutil` "
                  "(or ray[debug]) to enable debugging of memory-related "
                  "crashes.")
```

There is no way to suppress this message. If I install (or have on my system for other reasons) `psutil` then message is suppressed, but I cannot disable low memory exception (#4638).

**Comment by simon-mo** [comment]
psutil is now bundled so message shouldn't be printed. Closing...
