### ISSUE TITLE
[Data] Inefficient iteration over Arrow table columns

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#46482]
### What happened + What you expected to happen

Currently in Ray Data code, there are several places where we check if a column exists in an Arrow table. Examples:
- https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/arrow_block.py#L282
- https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/tfrecords_datasource.py#L83

To make this significantly more efficient, we can first create a set over the column names, then inside the for loop, check for set membership. An example of correctly handling this pattern is here: https://github.com/ray-project/ray/blob/master/python/ray/data/datasource/file_based_datasource.py#L392

We should fix the two cases above, as well as search for any other occurrences of this pattern that can be optimized. As a followup, we should also add a release test to microbenchmark these operations with tables involving a large number of columns (e.g. 5K columns).

### Versions / Dependencies

ray master

### Reproduction script

See above description

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by Bye-legumes** [comment]
see PR https://github.com/ray-project/ray/pull/46541
