### ISSUE TITLE
Error in example tune_tensorflow_autoencoder_example.py

### ISSUE THREAD

**Issue by mjovanovic9999** [ray-project/ray#46505]
### What happened + What you expected to happen

I was trying to run the basic example [https://github.com/ray-project/ray/blob/master/python/ray/train/examples/tf/tune_tensorflow_autoencoder_example.py](url) 

Gave me this error:

ValueError: `scaling_config` should be an instance of `ScalingConfig`, found <class 'dict'> with value `{'num_workers': 2, 'use_gpu': False}`.

This chage soloved the issue:

`scaling_config = dict(num_workers=num_workers, use_gpu=use_gpu)`

to:

`from ray.train import ScalingConfig`
...
`scaling_config = ScalingConfig(num_workers=num_workers, use_gpu=use_gpu)`

### Versions / Dependencies

ray, version 2.31.0
Python 3.9.19
Official docker image rayproject/ray

### Reproduction script

python tune_tensorflow_autoencoder_example.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by anyscalesam** [comment]
@mjovanovic9999 thanks for the find; can you submit a PR to fix the example in our docs? Assign to me as reviewer and I'll shepherd it through.
