### ISSUE TITLE
Test test_dataclient_disconnect is failing on microcheck

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#46677]
### What happened + What you expected to happen

The test test_dataclient_disconnect is failing on microcheck. It fails whenever it runs right after the test test_clint_init.

Script to reproduce:

```
pip install -U ray==2.32.0[all]
pip install pytest
bazelisk test --jobs=1 //python/ray/tests:test_client_init //python/ray/tests:test_dataclient_disconnect
```

### Versions / Dependencies

master

### Reproduction script

pip install -U ray==2.32.0[all]
pip install pytest
bazelisk test --jobs=1 //python/ray/tests:test_client_init //python/ray/tests:test_dataclient_disconnect

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
Fixed by #46680
