### ISSUE TITLE
ray 0.6.6 preprocessors incorrect observation space assertion

### ISSUE THREAD

**Issue by Guilherme-B** [ray-project/ray#4668]
With the new Ray release, 0.6.6, it seems to be that preprocessors are improperly asserting whether or not an observation is a part of the underlying space.

> ValueError: ('Observation outside expected value range', MultiDiscrete([250  12   8]), array([250,   0,   4]))

Full trace:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 443, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 315, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/worker.py", line 2193, in get
    raise value
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=8106, host=ip-172-31-85-198)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 333, in train
    raise e
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 322, in train
    result = Trainable.train(self)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 110, in _train
    fetches = self.optimizer.step()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 129, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 28, in collect_samples
    next_sample = ray.get(fut_sample)
ray.exceptions.RayTaskError: [36mray_worker[39m (pid=8082, host=ip-172-31-85-198)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 439, in sample
    batches = [self.input_reader.next()]
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 60, in next
    batches = [self.get_data()]
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 101, in get_data
    item = next(self.rollout_provider)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 317, in _env_runner
    soft_horizon)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 405, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 162, in transform
    self.check_shape(observation)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 61, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', MultiDiscrete([250  12   8]), array([250,   0,   4]))
```

**Comment by ericl** [comment]
Can you provide a reproduction snippet using https://github.com/openai/gym/blob/master/gym/spaces/multi_discrete.py?

I wonder if it's some dtype issue.

**Comment by Guilherme-B** [comment]
I'm not sure if this is what you are requesting, but, the used gym space constructor was:
`self.observation_space = spaces.MultiDiscrete([250, 11, 8])`

Let me know if this isn't the snippet you're referring to.

**Comment by ericl** [comment]
What is an example observation that fails the space.contains() check? For
example, Discrete(3).contains(4) == False.

**Comment by ericl** [comment]
Aha, actually your trace shows it: `ValueError: ('Observation outside expected value range', MultiDiscrete([250  12   8]), array([250,   0,   4]))`

250 is not a valid observation for Discrete(250), which is from 0..249. You probably want MultIDiscrete([251, 0, 4]) instead.

**Comment by jrich10** [comment]
`ValueError: ('Observation outside expected value range', Box(7,), array([1.4e-03, 1.4e-03, 1.4e-03, 1.4e-03, 3.0e+02,
       1.0e+03, 0.0e+00]))`

I'm currently having a similar issue. The code was working before the update and now after the update
I'm getting that ValueError

**Comment by ericl** [comment]
@jrich10 what's the full definition of your Box observation space? Probably it was incorrect before, but now we are enforcing the check...

**Comment by Guilherme-B** [comment]
> Aha, actually your trace shows it: `ValueError: ('Observation outside expected value range', MultiDiscrete([250 12 8]), array([250, 0, 4]))`
> 
> 250 is not a valid observation for Discrete(250), which is from 0..249. You probably want MultIDiscrete([251, 0, 4]) instead.

That's about it. Gym's documentation is scarce, upper bounds are exclusive, pythonic I guess.

**Comment by jrich10** [comment]
`self.observation_space = Box(low=-1.0, high=1.0, shape=(len(self.keys)-1, ), dtype=np.float32)`

Oh ok that makes sense. It might be the high, low. I thought it was weird that that was working but I thought maybe it was looking at normalized data

**Comment by NaRobBoo** [comment]
Getting a similar error. Does not appear to be a high low issue - tried arbitrarily large and small values. This environment works in other settings, so I'm not sure what is going on.

`self.observation_space = spaces.Tuple([
            spaces.Box(low=0, high=np.inf, shape=(1, 9, ), dtype=np.float64),
            spaces.Box(low=0, high=np.inf, shape=(1, 4, ), dtype=np.float64),
            spaces.Box(low=0, high=5000000, shape=(1, 3, ), dtype= np.uint32),
            spaces.Box(low=0, high=1, shape = (1, 25, ), dtype = np.float32),
            spaces.Box(low=-1, high=1, shape = (1, 21, ), dtype = np.float32),
            spaces.Box(low=0, high=1, shape = (1, 475, ), dtype = np.uint8),
            spaces.Box(low=-1, high=1, shape=(1, 62, ), dtype= np.int8)
            ])`

> ValueError: ('Observation outside expected value range', Tuple(Box(1, 9), Box(1, 4), Box(1, 3), Box(1, 25), Box(1, 21), Box(1, 475), Box(1, 62)), [array([0.85636002, 0.85870999, 0.85491002, 0.85758001, 0.85736001,
>        0.85970998, 0.85591   , 0.85788   , 1.55692995]), array([1000.,    0., 1000.,    0.]), array([2862,   19,    0], dtype=uint32), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>        0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), array([0.25416616, 0.        , 0.        , 0.        , 0.        ,
>        0.        , 0.        , 0.        , 0.        , 0.        ,
>        0.        , 0.        , 0.        , 0.        , 0.        ,
>        0.        , 0.        , 0.        , 0.6542695 , 0.75626147,
>        0.        ], dtype=float32), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=uint8), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
>        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)])
> 
> 
> 2019-04-30 13:37:28,198 INFO ray_trial_executor.py:179 -- Destroying actor for trial IMPALA_TestEnv_0. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
> 2019-04-30 13:37:28,201 INFO trial_runner.py:531 -- Attempting to recover trial state from last checkpoint.
> (pid=7270) 2019-04-30 13:37:28,193      INFO trainer.py:330 -- Worker crashed during call to train(). To attempt to continue training without the failed worker, set `'ignore_worker_failures': True`.
> == Status ==
> Using FIFO scheduling algorithm.
> Resources requested: 4/4 CPUs, 1/1 GPUs
> Memory usage on this node: 4.7/16.8 GB
> Result logdir: /home/ubnutu/ray_results/distributed-testing
> Number of trials: 1 ({'RUNNING': 1})
> RUNNING trials:
>  - IMPALA_TestEnv_0:   RUNNING, 1 failures: /home/ubuntu/ray_results/distributed-testing/IMPALA_TestEnv_0_2019-04-30_13-37-1919x9sl7a/error_2019-04-30_13-37-28.txt
> 
> (pid=7269) 2019-04-30 13:37:28,299      INFO policy_evaluator.py:437 -- Generating sample batch of size 48
> (pid=7269) 2019-04-30 13:37:28,371      INFO sampler.py:308 -- Raw obs from env: { 0: { 'agent0': [ np.ndarray((9,), dtype=float64, min=1.0, max=1.026, mean=1.02),
> (pid=7269)                    np.ndarray((4,), dtype=float64, min=0.0, max=1000.0, mean=500.0),
> (pid=7269)                    np.ndarray((3,), dtype=uint32, min=0.0, max=1015.0, mean=340.333),
> (pid=7269)                    np.ndarray((25,), dtype=float32, min=0.0, max=0.0, mean=0.0),
> (pid=7269)                    np.ndarray((21,), dtype=float32, min=-0.201, max=0.853, mean=0.056),
> (pid=7269)                    np.ndarray((475,), dtype=uint8, min=0.0, max=1.0, mean=0.025),
> (pid=7269)                    np.ndarray((62,), dtype=int8, min=0.0, max=0.0, mean=0.0)]}}
> (pid=7269) 2019-04-30 13:37:28,372      INFO sampler.py:309 -- Info return from env: {0: {'agent0': None}}

**Comment by ericl** [comment]
I'm wondering if it's this:

`shape=(1, 9, )` vs `(9,)`. I believe you shouldn't have the empty batch dimension in the observation space definition.

**Comment by NaRobBoo** [comment]
Thanks for the response. I made the change to remove the empty batch dimension and am still experiencing the problem. Strangely, it worked once, but trying to run it a second time (without any code changes) caused the error to reappear.

`
        self.observation_space = spaces.Tuple([
            spaces.Box(low=0, high=np.inf, shape=(9, ), dtype=np.float64),
            spaces.Box(low=0, high=np.inf, shape=(4, ), dtype=np.float64),
            spaces.Box(low=0, high=5000000, shape=(3, ), dtype= np.uint32),
            spaces.Box(low=0, high=1, shape = (25, ), dtype = np.float32),
            spaces.Box(low=-1, high=1, shape = (21, ), dtype = np.float32),
            spaces.Box(low=0, high=1, shape = (475, ), dtype = bool),
            spaces.Box(low=-1, high=1, shape=(62, ), dtype= np.int8)
            ])`

> ValueError: ('Observation outside expected value range', Tuple(Box(9,), Box(4,), Box(3,), Box(25,), Box(21,), Box(475,), Box(62,))

> Raw obs from env: { 0: { 'agent0': [ np.ndarray((9,), dtype=float64, min=1.0, max=1.026, mean=1.02),
(pid=2669)                    np.ndarray((4,), dtype=float64, min=0.0, max=1000.0, mean=500.0),
(pid=2669)                    np.ndarray((3,), dtype=uint32, min=0.0, max=1015.0, mean=340.333),
(pid=2669)                    np.ndarray((25,), dtype=float32, min=0.0, max=0.0, mean=0.0),
(pid=2669)                    np.ndarray((21,), dtype=float32, min=-0.201, max=0.853, mean=0.056),
(pid=2669)                    np.ndarray((475,), dtype=bool, min=0.0, max=1.0, mean=0.025),
(pid=2669)                    np.ndarray((62,), dtype=int8, min=0.0, max=0.0, mean=0.0)]}}

**Comment by ericl** [comment]
I would try to narrow this down by capturing the offending observation
(perhaps having your env write them to a file) and manually calling
observation_space.contains() on it to see what's going on.

The reason you might only see the error sometimes is since we only call
space.contains() 1 in every 1000 observations for performance reasons.

Eric

**Comment by christopher-hsu** [comment]
Hi, I am running into a similar issue. I am currently looking to run the Qmix alg on a custom multi agent environment, so I am using the env.with_agent_groups() in order to group the agents. The observation space needs to be in the Tuple() and so currently it is self._obs_space = Tuple(Box(14,), Box(14,)). I am looking to use agent.compute_actions(obs) (where agent is from the rollout implementation, i.e. get_agent_cls) in order to visualize my environment. During the compute_actions call, the preprocessor check fails which I believe is due to the Tuple.
isinstance(self._obs_space, gym.spaces.Box) 
Therefore, I think this is failing due to the fact that the Tuple is needed and it won't coincide with the single Box() observation space. Let me know if you agree with my deduction and if its okay to switch this check to be more broad to include the Tuple.

Thank you
Chris

**Comment by wegfawefgawefg** [comment]
Can I just disable bounds checking? I've seen like 5 different posts of this issue, and it's version dependent.
