### ISSUE TITLE
A3C Example Improvements

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#467]
Issues brought up by Sanjay: 

* pip install flatbuffers

* This error shows up since my tensorflow version is 0.12.head. I fixed this locally with:
http://stackoverflow.com/questions/11887762/compare-version-strings-in-python

You probably want to add a manual check to avoid another install dependency.

(segmentation) Sanjays-Air:ray sanjayk$ python examples/a3c/driver.py 1

Traceback (most recent call last):

  File "examples/a3c/driver.py", line 7, in <module>

    from runner import RunnerThread, process_rollout

  File "/Users/sanjayk/Documents/research/segmentation/ray/examples/a3c/runner.py", line 13, in <module>

    use_tf12_api = distutils.version.LooseVersion(tf.VERSION) >= distutils.version.LooseVersion('0.12.0')

  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/version.py", line 70, in __ge__

    c = self._cmp(other)

  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/version.py", line 337, in _cmp

    if self.version < other.version:

TypeError: unorderable types: str() < int()

* The A3C example is based on the openai starter and is actually not that great for more complex domains. This is partially due to the use of a softmax exploration policy which is really sensitive to initialization. We may want to change this to epsilon greedy as in the a3c paper.

**Comment by robertnishihara** [comment]
These are good points!

The `pip install flatbuffers` is already in the documentation for installing Ray and isn't specific to A3C.

Is the suggestion that we assert `tf.__version__[0] >= 1` or something like that?

As for changing the exploration policy, that probably makes sense.

**Comment by robertnishihara** [comment]
Closing, as these are from a while ago. Please reopen if they are still relevant.
