### ISSUE TITLE
[Core] Resources dict corrupted during cleanup between `ray.get` calls

### ISSUE THREAD

**Issue by bwohlberg** [ray-project/ray#46753]
### What happened + What you expected to happen

If `ray.available_resources()` is called between consecutive calls to `ray.get` to retrieve results from parallel execution of a remote function, the "CPU" key is missing from the resulting resources dict. (Not tested with GPUs, but the corresponding key is quite possibly also missing.) This issue is intermittent (it occurs frequently, but not on every run of the reproduction script below), and introduction of a short delay after the first `ray.get` call seems to prevent its occurrence.

It's presumably due to `ray.available_resources()` being queried during a cleanup period after the first `ray.get` call, but there doesn't seem to be any public API function to wait for this to complete, and inserting delays is a nasty and unreliable hack.

### Versions / Dependencies

ray 2.32.0, Python 3.10.13, Ubuntu 22.04.4

### Reproduction script

```python
import numpy as np
import warnings
import ray
ray.init()


@ray.remote
def rfunc(n):
    return np.ones((n, n))


rflist = ray.get([rfunc.remote(n) for n in range(8)])
print(len(rflist))

#import time
#time.sleep(0.1)

ar = ray.available_resources()
if "CPU" not in ar:
    warnings.warn("No CPU key in ray.available_resources() output.")

rflist = ray.get([rfunc.remote(n) for n in range(8)])
print(len(rflist))
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
Hi @bwohlberg, CPU doesn't exist in the `ray.available_resources()` meaning it's 0. Your code needs to do `ray.available_resources().get("CPU", 0)`. Will update the doc to make it clear.

**Comment by bwohlberg** [comment]
Thanks for the clarification. That still leaves the question, though, as to why `ray.available_resources` considers the CPU count to be 0, and it remains problematic even when one does use the recommended approach for querying it: without the `sleep` call, `ray.get` will not use the actual available resources.

**Comment by jjyao** [comment]
> It's presumably due to ray.available_resources() being queried during a cleanup period after the first ray.get call, but there doesn't seem to be any public API function to wait for this to complete, and inserting delays is a nasty and unreliable hack.

You are right that it takes sometime for `ray.available_resources()` to realize that CPUs are freed so think it's eventually consistent.

**Comment by bwohlberg** [comment]
Is there some way of determining when that's happened so one doesn't have to use the ugly `sleep` hack?

**Comment by jjyao** [comment]
Unfortunately, there is no way. What do you want to achieve? Maybe I can find a good enough workaround.

**Comment by bwohlberg** [comment]
We just want to be able to run `ray.get` multiple times within the same function, which doesn't seem like a very esoteric need. What's the recommended way of doing this?

**Comment by jjyao** [comment]
You can just do that without calling ray.available_resouces(). Still not sure why you want to call it.

**Comment by bwohlberg** [comment]
Ah, you mean that all CPUs are actually available to `ray.get`, it's just that the number reported by `ray.available_resources()` is wrong?

**Comment by jjyao** [comment]
Yes.

**Comment by bwohlberg** [comment]
OK, thanks, then I guess we can work around the issue.

**Comment by jjyao** [comment]
We will close it after adding the doc saying that if a resource is missing then the available quantity is 0.
