### ISSUE TITLE
[RLlib] DQN Torch modules `__init__.py` is missing. 

### ISSUE THREAD

**Issue by priyamDalmia** [ray-project/ray#46773]
### What happened + What you expected to happen

I am trying to run the RainbowDQN algorithm in RLllib. However, I encounter a problem when using the torch framework. More specifically, the torch rl modules for the DQN algorithm have not been properly initialized. I think that the module is missing the `__init__.py` file. 

```
 File "/Users/dalmia/.pyenv/versions/3.11.0/envs/crl/lib/python3.11/site-packages/ray/rllib/algorithms/dqn/dqn.py", line 497, in get_default_rl_module_spec
    from ray.rllib.algorithms.dqn.torch.dqn_rainbow_torch_rl_module import (
ModuleNotFoundError: No module named 'ray.rllib.algorithms.dqn.torch'
```

### Versions / Dependencies

ray 2.32.0

### Reproduction script

```
import gymnasium as gym
import ray
from ray.rllib.algorithms.dqn import DQNConfig

ray.init(
    num_cpus=1,
    local_mode=True,
)

env_name = "CartPole-v1"
env = gym.make(env_name)

algo_config = (
    DQNConfig()
    .environment(
        env=env_name,
    )
    .api_stack(
        enable_env_runner_and_connector_v2=True,
        enable_rl_module_and_learner=True,
    )
)
algo = algo_config.build()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by simonsays1980** [comment]
@priyamDalmia Great catch! Thanks for filing this. I have reviewed the quick fix from @MaxVanDijck and it should be in the release coming tomorrow.

**Comment by sven1977** [comment]
The PR has been merged. Closing this issue.

https://github.com/ray-project/ray/pull/46898
