### ISSUE TITLE
[core] Local Mode hashables

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4678]
Local mode is extremely helpful. Sometimes i write code that assumes that object IDs will be returned (object ids are hashable). 

If I return a dict (which is unhashable) in the remote task, switching onto local mode breaks my application.

My code is going to call “get” at some point anyways — is there any problem with returning a ObjectID of some sort in local_mode?

I'll add a mwe later this week.

**Comment by robertnishihara** [comment]
Fixed by https://github.com/ray-project/ray/pull/5060.
