### ISSUE TITLE
[autoscaler] GCP cluster start hangs on `uptime` command

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#4679]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: https://github.com/ray-project/ray/tree/d951eb740ffe22c385d75df62aa18da790706804
- **Python version**: 3.6
- **Exact command to reproduce**: `ray exec`

### Describe the problem
Something in autoscaler changed between https://github.com/ray-project/ray/tree/56a78baf677a345ae23035111f978dd695407d48 and https://github.com/ray-project/ray/tree/d951eb740ffe22c385d75df62aa18da790706804 (latest master), which causes the `uptime` command to hang, and thus the cluster never starting. Other autoscaler commands are broken as well, e.g. `exec`.

Tested on GCP, I don't know if this happens on AWS or local cluster.

I guess the broken change happened either in #4299 or #4285.

### Source code / logs
n/a

**Comment by hartikainen** [comment]
We really need better testing for these autoscaler changes. It feels like something breaks every time we make changes to it.

**Comment by ls-daniel** [comment]
Have you tried reverting these commits to test? I've reviewed both and can't see anything that would cause this issue, but I'm unable to test on GCP.

**Comment by hartikainen** [comment]
Yeah, I went back to the last commit before them and things work fine. I'll take a closer look when I find some time.
