### ISSUE TITLE
[experimental][adag] ray.get doesn't support list of aDAG refs

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#46808]
### What happened + What you expected to happen

ray.get works on a single aDAG ref but not a list of them.

### Versions / Dependencies

3.0dev

### Reproduction script

--

### Issue Severity

None

**Comment by gadevishal9** [comment]
Hello Stephanie! I’m interested in working on this issue. Should we process each compiled node sequentially or in parallel? Locally, the tests run fine in parallel, but I’m unsure if processing them that way might cause other issues.

**Comment by stephanie-wang** [comment]
Closed by #47305.

Sorry I missed your comment @gadevishal9! I think this issue is already closed but you could check out the [open issues](https://github.com/ray-project/ray/issues?q=is%3Aopen+is%3Aissue+label%3Aaccelerated-dag+label%3A%22good+first+issue%22) for another good starter one.
