### ISSUE TITLE
[Core] "Edit on Github" Links in documentation broken

### ISSUE THREAD

**Issue by petern48** [ray-project/ray#46817]
### Description

Many (probably all) of the "Edit on Github" links in the ray core API documentation pages are broken.

Here's an example. Clicking on [ray.get() page](https://docs.ray.io/en/latest/ray-core/api/doc/ray.get.html#ray.get), it leads me to the following [github page](https://github.com/ray-project/ray/edit/master/doc/source/ray-core/api/doc/ray.get.rst) that's not found. I'd be more than happy to fix these links as a new contributor, but I need help on locating where to find the proper pages.

**Comment by petern48** [comment]
Actually, it sounds like this [issue #46718](https://github.com/ray-project/ray/pull/46718) should address it. Would appreciate some confirmation from someone else, since it's already merged, but not updated yet.

**Comment by anyscalesam** [comment]
Yeap - this is fixed! Closing cc @petern48
