### ISSUE TITLE
[async] async_api doesn't work when the invoked function is running on a remote node.

### ISSUE THREAD

**Issue by gravitywp** [ray-project/ray#4681]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from source**:
- **ray 0.6.6**:
- **python3.6**:
- **Exact command to reproduce**:

### Describe the problem

when the run function and the remote_func are not running on the same node, the run function will never return, I checked out the implementation of  async_api.as_future doesn't see any code to request the object_id  corresponding data to the local object store. 

### Source code / logs

e.g.
`
@ray.remote
def remote_func():
    return "test"

async def run():
    result = await async_api.as_future(remote_func.remote())
    return result
`

**Comment by robertnishihara** [comment]
cc @suquark

**Comment by richardliaw** [comment]
should be fixed now.
