### ISSUE TITLE
[Tune] Exposing tunable parameters explicitly on trial config

### ISSUE THREAD

**Issue by julian-asapp** [ray-project/ray#4682]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS Mojave
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.4
- **Python version**: 3.6.6
- **Exact command to reproduce**: https://github.com/ray-project/ray/blob/master/python/ray/tune/ParallelCoordinatesVisualization.ipynb

### Describe the problem
In order to build *automatic* parallel coordinate views automatically while executing trials, or use Tensorboard [new native feature](https://www.tensorflow.org/tensorboard/r2/hyperparameter_tuning_with_hparams), it would be very useful if the list of parameters that are being tuned together with the values where exposed somewhere in the trial config that uses the resolved trial spec, as opossed to just mixed up with the rest of the configuration.

I can currently access that information with some complex and error-prone string manipulation of the logdir of the trial, and the `trial_name_creator` method in the experminet can help a little as well, but they all seem like bad solutions. Is there a recommended path to achieve this currently that I am missing, or would this be a valuable contribution?

**Comment by richardliaw** [comment]
So somehow having a list of the config keys that were resolved in the Trial object?

**Comment by julian-asapp** [comment]
Yes, exactly

**Comment by richardliaw** [comment]
OK, this is fixed with #5678
