### ISSUE TITLE
[Core] ray.init: allow users to modify timeout length

### ISSUE THREAD

**Issue by thvaisa** [ray-project/ray#46863]
### Description

Allow a user to modify timeout length when trying to connect to the ray node with ray.init

Currently, it is 60 sec or something, which can be too long for some users. Simple workaround is to launch a subprocess that checks what "ray status" returns.

### Use case

Let TIMEOUT be an arbitrary timeout period for ray init specified by a developer

1. A user sets up ray nodes with a command line or an external tool. 
2. The user launches software that tries to connect to the ray head node with ray.init(address, timeout=TIMEOUT)
3. if ray.init can not connect within TIMEOUT period, the ray.init throws an error

**Comment by rkooo567** [comment]
Right now, there are many different RPCs and work we are doing when ray.init is called. While we can allow to overwrite some RPC timeout, it is pretty tricky to set overall timeout across all work. 

How difficult is it to set this on your end? (something like start a timer thread and send keyboard interrupt to itself when ray.init doesn't finish in 30 seconds)?

**Comment by thvaisa** [comment]
> Right now, there are many different RPCs and work we are doing when ray.init is called. While we can allow to overwrite some RPC timeout, it is pretty tricky to set overall timeout across all work.
> 
> How difficult is it to set this on your end? (something like start a timer thread and send keyboard interrupt to itself when ray.init doesn't finish in 30 seconds)?

It was not difficult, and I solved the issue with the workaround as described in the description.

**Comment by rkooo567** [comment]
I will close the issue for now!
