### ISSUE TITLE
Actor class static methods are treated as instance methods

### ISSUE THREAD

**Issue by neychev** [ray-project/ray#4687]
Trying to call the staticmethod of ray Actor (class wrapped with @ray.remote) fails because the method awaits the `self` field.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary (pip)
- **Ray version**: 0.6.4
- **Python version**: 3.6.7
- **Exact command to reproduce**:
```
@ray.remote
class my_class:
    def __init__(self):
        self.a = 1
    
    def get_a(self):
        return self.a
    
    @staticmethod
    def static_sum(a, b):
        return a+b

mc = my_class.remote()
ray.get(mc.static_sum.remote(1, 2))
```
will fail with exception:
```
Exception: Too many arguments were passed to the function 'static_sum'
```
and calling 
```
ray.get(mc.static_sum.remote(1))
```
causes
```
RayTaskError: ray_my_class:static_sum() (pid=28795, host=***)
  File "<ipython-input-64-88df51b11f3a>", line 11, in static_sum
TypeError: unsupported operand type(s) for +: 'my_class' and 'int'
```

### Describe the problem
Actor static methods are treated as instance methods.

Additional question: Are there any ways to access the actor property (function wrapped with property decorator) or just instance field? They are not callable and not present in ActorHandle attributes.
e.g.
```
mc.a
```
causes
```
AttributeError: 'ActorHandle' object has no attribute 'a'
```

**Comment by robertnishihara** [comment]
Thanks for reporting this, would you be interested in submitting a patch for this?

Regarding accessing fields of an object, there isn't a way that is exposed right now. We could always expose the builtin methods like `__getattribute__`, which would make it possible. One reason for not making it too easy is that accessing a field feels very "cheap", but in our case it requires remote procedure calls, so isn't particularly cheap.

**Comment by neychev** [comment]
Thanks, @robertnishihara!

Talking about the patch, are the staticmethods supposed to be treated as remote functions or just ignored with some exception message?

About the accessing the fields: the documentation seems to lack this info. From the first view some people may get the incorrect understanding of ray remote actors.

**Comment by neychev** [comment]
Up (talking about the last comment)

**Comment by neychev** [comment]
Up

**Comment by ziyadedher** [comment]
This issue has been driving me a bit nuts lately, a made a simple change to fix it by treating static methods as class methods. See #6756.
