### ISSUE TITLE
Test the NIC name start with 'e' is not very robust

### ISSUE THREAD

**Issue by songpengwei** [ray-project/ray#4689]
https://github.com/ray-project/ray/blob/f39b6747e54cef62744d71f40737c89c06efc635/python/ray/reporter.py#L64

because in my environment, we name all the  NIC (network interface card) to 'ib0', then `determine_ip_address ` get a empty array and then `return addrs[0]` throw an Exception. Thus `Reporter` will not be started and the webui will be empty all the time.

I think the below code may be better?
```python
addrs = [
       x.address for k, v in psutil.net_if_addrs().items() if k != "lo"
       for x in v if x.family == AddressFamily.AF_INET
 ]
```

besides, if the `Reporter` can't start properly, we may need to log an error in the main process(that is, in output of  `ray start`)? or, the user may spend a of time to investigate why his webui always have no data.

**Comment by richardliaw** [comment]
cc @ls-daniel

**Comment by richardliaw** [comment]
BTW, @songpengwei can you make PR for this?

**Comment by jkerfs** [comment]
I think this is resolved by https://github.com/ray-project/ray/pull/5857/commits/7903dec41cf8e4e66dc3771c1b46c0fd8f296767
