### ISSUE TITLE
data return by redis pubsub is ’bytes‘ which can't be passed to `json.loads` in python3.5

### ISSUE THREAD

**Issue by songpengwei** [ray-project/ray#4690]
https://github.com/ray-project/ray/blob/f39b6747e54cef62744d71f40737c89c06efc635/python/ray/dashboard/dashboard.py#L275

**Comment by robertnishihara** [comment]
Thanks for pointing this out! Do you have an example of a script that causes this error?

**Comment by songpengwei** [comment]
just use python3.5 as the interpret, and check the webui, the error will be triggered

**Comment by mitchellstern** [comment]
Hi @songpengwei, this was fixed in #5466.
