### ISSUE TITLE
[core][adag] Avoid deserializing outputs that are not going to be used

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#46909]
### Description

Right now when a CompiledDAGRef goes out of scope, we get the result to release the physical buffer. However, we also deserialize the result ([here](https://github.com/ray-project/ray/blob/07c72af16197cf9f1a8802b0d5f1c0e34314f0ac/python/ray/experimental/compiled_dag_ref.py#L89)), which is not necessary since no one will use the result. We should remove this step.

**Comment by rkooo567** [comment]
Right now, how we get around the issue is by serializing it ourselves.

**Comment by kevin85421** [comment]
Closes by #47614
