### ISSUE TITLE
[core][data] Add an API to query actor state from an actor handle

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#46937]
When an actor is pending at the RESTART state, Ray Data wants to pause submitting new tasks to it. Currently there is no API (except for the heavy state API) to query the actor states. Ideally we can add a `actor_handle.get_state()` API to expose the info that is already available in the local core worker.

**Comment by alexeykudinkin** [comment]
Crux of the problem is the following (from @bveeramani)

 - When actor restarts, in case there are not enough resources, actor could get stuck in blocked state for a long time
 - Tasks scheduled to run on this actor will be blocked for a long-time

**Comment by alexeykudinkin** [comment]
@jjyao please update with ETA
