### ISSUE TITLE
Qmix Bug with Truncated Episodes or when max_seq_len is set

### ISSUE THREAD

**Issue by jacooba** [ray-project/ray#4693]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**:  0.6.2
- **Python version**:  3.5.5
- **Exact command to reproduce**: (running on custom env)

### Describe the problem

Qmix is set up to add padded q-values of -9999999 to the end of every sequence. These q-values are not being correctly masked out. They are ignored in terminal states, due to line 108 in qmix_policy_graph.py, however they are being used in non-terminal states that happen to be at the end of a sequence. This is causing astronomical TD-errors on my custom env with 1 agent.

The issue is also a bit more complicated than just masking them out, as the code tries to do: There does need to be a next state (observation) to complete the bootstrapped return. If it is simply masked out, then certain states will never receive a back propagated loss.

I would suggest also passing in next_states to the loss function (new_obs in samples dictionary I believe). If terminal states are not recorded with a next observation, then one can be added as padding, since it will be 0-ed out by (1 - terminated) in line 108 anyway.

This issue can be verified by truncating episodes and noting that reward + self.gamma*-9999999 is contained in the variable masked_td_error.

**Comment by ericl** [comment]
To clarify, this only happens if batch mode is set to truncate episodes?

**Comment by jacooba** [comment]
I assume it would also be an issue with complete episodes but with a max_seq_len less than the length of the episode. It seems to be an issue if there is a non-terminal state at the end of a sequence.

**Comment by jacooba** [comment]
I have attached code that I believe reproduces the same bug. The commands are:

python3 twostep_game_no_bug.py --run QMIX

python3 twostep_game_bug.py --run QMIX

the variable masked_td_error seems to still contain the dummy constant in the bug version.

[Qmix bug.zip](https://github.com/ray-project/ray/files/3116258/Qmix.bug.zip)

**Comment by ericl** [comment]
Hm I see. The proposed fix makes sense to me, and it also seems ok to potentially ignore the last state when truncating. Do you want to make a patch?

**Comment by jacooba** [comment]
Sure. I can't do it this second, but should have some time next week.
