### ISSUE TITLE
Ray Serve IDLE processes using 90% of CPU time 

### ISSUE THREAD

**Issue by DanielChern** [ray-project/ray#46964]
Hey Ray team
We noticed strange behavior with ray::IDLE threads,
When ray applications use ~80% of  CPU time  90% of that time is captured by a task called ray::IDLE.
We captured it using `perf sched record -- sleep 10 && perf sched latency -s runtime`. 
![image](https://github.com/user-attachments/assets/a3ec62df-a6a5-475c-a8ec-4018acc84a45)

Also, you can see that each RayServe process has several IDLE processes, some of them tuning for hours. 
![image](https://github.com/user-attachments/assets/99429ea7-8580-49c0-b33e-de53ac43c4dc)

Is this something that is expected and just a misleading thread name or maybe there is something wrong that we did?

### Versions / Dependencies

Node: GCP C3-standard-22 (22 vCPU  88 GB RAM)
Ray: `ray-ml:2.24.0-py310-gpu`
Ray Operator : v1.1.0
OS:  Linux 6.1.85

### Reproduction script

```python3
import numpy as np
import PIL.Image as Image
from nbcm.embeddings.clip import ClipEncoder
from ray import serve
from typing import List


@serve.deployment
class ClipServe:
    def __init__(self):
        self._model = ClipEncoder()
        ... some internal logic ...


    @serve.batch(max_batch_size=32, batch_wait_timeout_s=1)
    async def process(self, images: List[np.ndarray]) -> List[np.ndarray]:
        self.metric_logger.log_batch_size(len(images))
        image_list = [Image.fromarray(img) for img in images]
        embeddings = self._model.process(image_list)
        return [embedding.flatten().astype(float).tolist() for embedding in embeddings]

app = ClipServe.bind()

```

Ray start command (3 instances per node): 
```
ulimit -n 65536; ray start  --num-cpus=7  --memory=25000000000  --resources="{\"custom-node-cpu\":
      1}"  --address=clip-model-rayservice-raycluster-rnspv-head-svc.clip-model.svc.cluster.local:6379  --metrics-export-port=8080  --block  --dashboard-agent-listen-port=52365
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
Normally, when a new process is created, it becomes ray::IDLE. And whenever you schedule an actor, it becomes "ray::<actor_repr>"

Did you observe 90% CPU live, or is it trace captured from some duration? If it is the latter case, I think it is probably possible the tool captures the name ray::IDLE and then something else is scheduled on it after that.

**Comment by DanielChern** [comment]
First of all, tnx for the explanation.
this perf was captured from 10 seconds of CPU time, but we did that test many times on different nodes, and we saw the same result every time.

**Comment by rkooo567** [comment]
is it possible to capture the flamegraph when it uses 90% of cpus? (maybe use py-spy)?

**Comment by DanielChern** [comment]
sure 
Here 10 seconds of py-spy profiles of the ray::ServeReplica processes (you can see that our BL uses only 28%)
![image](https://github.com/user-attachments/assets/7351874a-f524-43b0-82c1-fda990db7f70)
![profile_2](https://github.com/user-attachments/assets/500a5e3b-c785-41a7-8c5c-0d99beecfd3c)

**Comment by rkooo567** [comment]
So this is not ray::IDLE process right? 

I guess it may be because ray::IDLE processes are started as soon as the cluster starts, so it has long cpu execution time when you aggregate threads run time?

**Comment by DanielChern** [comment]
Upon further investigation, it appears that the issue might simply be a matter of incorrect naming within the Linux threads.
I took the profile of another actor which downloaded images from the internet and then converted/resized them with PIL library. 
Meanwhile, in the Linux profile, I noticed that ray::IDLE has an internal process called `ImagingResampleHorizontal_8bpc`, part of the [PIL library](https://github.com/python-pillow/Pillow/blob/11b4df3ff9c02757eaf687ac13374f3525c8cb71/src/libImaging/Resample.c#L287). While this is only 8% of the profile, it still does not make sense why ray::IDLE  would call that function and it sounds like part of our actor business logic. 
Does it sound reasonable to you? If so, the issue can be closed.


![image](https://github.com/user-attachments/assets/47e94d19-c057-4cfd-8ade-309fecc0ebe4)

**Comment by DanielChern** [comment]
Ok so I managed to profile one of the IDLE processes and it does run our business logic ..... But it is only 20% of the run time (green box), what other 80% of the time I cannot understand (blue box) 
![image](https://github.com/user-attachments/assets/5a5cfcab-6801-4233-9199-9eadcfeac696)

**Comment by rkooo567** [comment]
you can probably use --native flags to see what's running there. But it does seem like it is just the naming issue to me

**Comment by DanielChern** [comment]
Ok, in that case, do you want to close the issue or live it so you can take care of the naming part?

**Comment by anyscalesam** [comment]
closing - please reopen if conclusion is incorrect.
