### ISSUE TITLE
[ray] workers stay after main process is finished

### ISSUE THREAD

**Issue by neychev** [ray-project/ray#4699]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.3 LTS
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.6.4 *update* 0.6.6 too
- **Python version**: 3.6.7
- **Exact command to reproduce**:

### Describe the problem

Seems similar to #3297
**Update**: occurs only in case when `redis_address` is specified in script. If ray is running locally, no problems are detected. 
Current behavior (0.6.4 & 0.6.6) with GPUs shows same problem. Remote functions that allocate GPU resources remain after main python script finishes and still uses some GPU memory. Calling `ray.shutdown()` manually doesn't help.

#### Additional info: seems like the problem is present only if started with head node 

```
+-----------------------------------------------------------------------------+                    │+-----------------------------------------------------------------------------+                      
| Processes:                                                       GPU Memory |                    │| Processes:                                                       GPU Memory |                      
|  GPU       PID   Type   Process name                             Usage      |                    │|  GPU       PID   Type   Process name                             Usage      |                      
|=============================================================================|                    │|=============================================================================|                      
|    0      4081      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                    │|    0      4179      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                      
|    1      4087      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                    │|    1      4194      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                      
|    2      4073      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                    │|    2      4180      C   ...esq/miniconda3/envs/py3_prod/bin/python   197MiB |                      
+-----------------------------------------------------------------------------+                    │+-----------------------------------------------------------------------------+ 
 ```

The process (e.g. 4073) is created by `raylet` process:
```
|-raylet(4060)-+-python(4072)-+-python(7152)
           |              |              |-{python}(4688)
           |              |              `-{python}(4689)
           |              |-python(4073)-+-python(6846)
```

**Comment by robertnishihara** [comment]
Thanks @neychev, that sounds like a bug. Can you share runnable code for reproducing the issue?

I thought that when a driver exits (or calls `ray.shutdown()`), all currently running tasks/actors created by that driver are killed, but there may be a bug.

**Comment by fruffy** [comment]
I am dealing with a similar problem. I use a lot of subprocesses in my environment which are typically cleaned up using `close()` or an `atexit` call. This normally works fine when I call ray directly. However, when I use indirection, ray does not terminate and leaves several `ray_PolicyEvaluator:sample()` processes behind.
For example, I have a run_ray.py file with this structure:
```
def main(args=None):
  ray.init(num_cpus=6, logging_level=logging.ERROR)
  log.info("Starting experiment.") 
  tune.run(...)
  ray.shutdown()

if __name__ == '__main__':
    main()
```
If I call `python run_ray.py` everything cleans up nicely. However, if I run `run_ray.py` from an external module (say as `run_ray.main(args)` from a `benchmark.py` file) all the processes are left after ray has finished running the trials. `ray.shutdown()` does not seem to do anything. My assumption right now is that `atexit` is not called, but there are no other means for me to terminate environments. Is there a way to make sure that ray processes call `env.close()` after finishing?

**Comment by neychev** [comment]
@robertnishihara I'll try to reproduce this bug in my own environment

**Comment by oshriPP** [comment]
I run into same issue.
One more way to reproduce the bug is using Pychram. 
And chose `Run with Python console` option in the run/debug configurations. 

**OS **: macOS Mojave 10.14.5
**Ray installed from (source or binary)**: pip
Ray version: 0.7.1
Python version: 3.7.3
