### ISSUE TITLE
[Dashboard] Add memory graphs optimized for OOM debugging

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#47007]
### Description

The current graph shows memory usage of each node along side the MAX memory across the cluster.

For OOM detection, we probably care more about % memory usage per node and should put extra emphasis on nodes with > 80% (or some other number) memory usage.

### Use case

Debug OOM as reason my workload crashed

**Comment by alanwguo** [comment]
Another thing we can try doing is make head node emphasized in the Grafana dashboards. Make the line double thick.

**Comment by Bye-legumes** [comment]
Let me try to solve this, I prefer to head node emphasized with double thick.
