### ISSUE TITLE
[core][aDAG] Hangs if same shared memory channel is read twice by one actor

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#47041]
### What happened + What you expected to happen

```
driver -> actor1.op ...
       |
       -> actor1.op ...
```

* This doesn't work. We should pass information about how many times the `MutableObject` should be read per actor from Python to C++ to avoid hanging.
  ```python
  with InputNode() as inp:
      d00 = worker_0.forward.bind(inp)  # worker_0 FWD
      d01 = worker_0.forward.bind(inp)  # worker_0 FWD
      d02 = worker_0.forward.bind(inp)  # worker_0 FWD
  ```

* Workaround: This works. Read the shared memory once, and then use `IntraProcessChannel` to transfer data between `read_input` and `forward`. In addition, this solution is more efficient. See #46431 for more details.
  ```python
  with InputNode() as inp:
      w0_input = worker_0.read_input.bind(inp)
      d00 = worker_0.forward.bind(w0_input, 0)  # worker_0 FWD
      d01 = worker_0.forward.bind(w0_input, 1)  # worker_0 FWD
      d02 = worker_0.forward.bind(w0_input, 2)  # worker_0 FWD
  ```

### Versions / Dependencies

nightly

### Reproduction script

see above

### Issue Severity

None

**Comment by stephanie-wang** [comment]
Can you add some more explanation of why this isn't working, so potentially someone can take over this issue?

**Comment by rkooo567** [comment]
what's the practical use case you pass the same input to the same actor multiple times?

**Comment by kevin85421** [comment]
> what's the practical use case you pass the same input to the same actor multiple times?

It's a common pattern for PP.
