### ISSUE TITLE
Error when downloading boost

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#4705]
On the latest master:

```
+ bazel build //:ray_pkg --verbose_failures
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
....................
INFO: SHA256 (https://github.com/jovany-wang/prometheus-cpp/archive/master.zip) = d0c773da8af3db99c543dd0413f4427d835170eddfd517bfeba104236a8d2c07
INFO: SHA256 (https://github.com/census-instrumentation/opencensus-cpp/archive/v0.3.0.zip) = e95cadb1941e1a0a698bf5c539a660ef57bc6a1ee2c0f3f76b23707a8dd6d229
DEBUG: /private/var/tmp/_bazel_pcmoritz/65b142b3f2651cc0f42773a358f37553/external/bazel_tools/tools/build_defs/repo/http.bzl:43:9: ctx.attr.build_file @com_github_nelhage_rules_boost//:BUILD.boost, path /private/var/tmp/_bazel_pcmoritz/65b142b3f2651cc0f42773a358f37553/external/com_github_nelhage_rules_boost/BUILD.boost
DEBUG: /private/var/tmp/_bazel_pcmoritz/65b142b3f2651cc0f42773a358f37553/external/bazel_tools/tools/osx/xcode_configure.bzl:87:9: Invoking xcodebuild failed, developer dir: /Applications/Xcode-beta.app/Contents/Developer ,return code 256, stderr: Process terminated by signal 15, stdout: 
ERROR: /Users/pcmoritz/ray/BUILD.bazel:70:1: no such package '@boost//': java.io.IOException: Error downloading [https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz] to /private/var/tmp/_bazel_pcmoritz/65b142b3f2651cc0f42773a358f37553/external/boost/boost_1_68_0.tar.gz: GET returned 403 Forbidden and referenced by '//:raylet_lib'
ERROR: Analysis of target '//:ray_pkg' failed; build aborted: no such package '@boost//': java.io.IOException: Error downloading [https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz] to /private/var/tmp/_bazel_pcmoritz/65b142b3f2651cc0f42773a358f37553/external/boost/boost_1_68_0.tar.gz: GET returned 403 Forbidden
INFO: Elapsed time: 30.004s
INFO: 0 processes.
```

Downloading the file with wget works fine for me. I wonder if somebody else has this problem, it might be transient.

Introduced in https://github.com/ray-project/ray/pull/4685.

**Comment by tirdtoon** [comment]
cause of boost at binary failed.
here it's worked for me->
1. ray$ git clone https://github.com/ray-project/rules_boost.git
2. ray$ nano rules_boost/boost/boost.bzl
change:
           urls = [
                "https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"
            ],

to:
            urls = [
                #"https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"
		"https://jaist.dl.sourceforge.net/project/boost/boost/1.68.0/boost_1_68_0.tar.gz"
            ],

3. ray$ nano  bazel/ray_deps_setup.bzl
comment rules boost repo in git:
    #git_repository(
    #    name = "com_github_nelhage_rules_boost",
    #    commit = "5171b9724fbb39c5fdad37b9ca9b544e8858d8ac",
    #    remote = "https://github.com/ray-project/rules_boost",
    #)

4. ray$ nano WORKSPACE
add this line:
local_repository(
   name = "com_github_nelhage_rules_boost",
   path = "rules_boost",
)

5. ray$ ./build.sh

**Comment by pcmoritz** [comment]
This was fixed for me by upgrading bazel (I had a very old version).

**Comment by ClarkZinzow** [comment]
It's probably (hopefully) transient, but I'm hitting this error consistently right now.

```
ERROR: An error occurred during the fetch of repository 'boost':
       java.io.IOException: Error downloading [https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz] to /home/clark/.cache/bazel/_bazel_clark/4b0c7d95a1a2a417d84b6788f088ac1e/external/boost/boost_1_71_0.tar.gz: GET re
turned 403 Forbidden
```

wget gives the same error.

```
$ wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
--2020-03-02 04:43:51--  https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 35.166.139.238, 52.39.25.243
Connecting to dl.bintray.com (dl.bintray.com)|35.166.139.238|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-02 04:43:51 ERROR 403: Forbidden.
```

**Comment by ClarkZinzow** [comment]
It looks like y'all moved to a ray-project fork of rules_boost in order to use bintray instead of sourceforge as the mirror.  Given that upstream rules_boost is now not only using bintray, but also [added an additional mirror HTTP archive for boost](https://github.com/nelhage/rules_boost/commit/6367a1ac9ba05318e170fc376d0aed335aa0d8e2#diff-112b8e930ed26844102977905a913d17), I think that it might be a good idea to switch back to upstream rules_boost and do away with the fork.

**Comment by yunqu** [comment]
Looks like with `ray-0.8.3`, the error becomes a warning which does not stop the building process anymore.

```
WARNING: Download from https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2 failed: class java.io.IOException GET returned 403 Forbidden
```

**Comment by iamsiddhantsahu** [comment]
I was also trying to build `ray-0.6.2` with Bazel version `6.2.1` and getting this exact same error. @pcmoritz How did you resolve your error? By just upgrading to a newer Bazel version? For me, even with the latest version of Bazel, I am getting this exact error.
