### ISSUE TITLE
[autoscaler] Improve backwards compatibility

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4706]
Right now, when configs are changed in a new PR, the prior versions of the autoscaler fail due to a strict validation check.

**Comment by robertnishihara** [comment]
Does this mean issuing deprecation warnings before introducing breaking changes? Backwards compatibility is great, but if there's a choice between the best API and a backwards compatible API, I think we should optimize for the best API going forwards.

**Comment by richardliaw** [comment]
No, this is just softening a check. Right now, if a new config value is introduced, the autoscaler fails.

**Comment by robertnishihara** [comment]
@richardliaw why is that? The minimal example includes almost no fields.. https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-minimal.yaml

**Comment by richardliaw** [comment]
Sorry for the late reply (also realize that my previous response probably needs more context) -

The autoscaler has a validation check that has a whitelist of allowed values. Your provided config is allowed to have a strict subset of the whitelist, but you're currently not allowed to add values that aren't on the whitelist (that's why the minimal example is OK). When a subset is given, the autoscaler autopopulates the config until it has all of the whitelist.

When new config values are added into the white list of your local Ray, and the cluster version of ray has a different whitelist, things silently fail with no clear workaround - sometimes upgrading to latest isn't an option. I'm just proposing to have an option to make the whitelist less strict so that different versions of ray can interoperate.

**Comment by rkooo567** [comment]
This should be resolved as we have public/private APIs now.
