### ISSUE TITLE
[rllib] NameError: global name 'ray' is not defined

### ISSUE THREAD

**Issue by karim174** [ray-project/ray#4707]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: 
- **Ray version**: ray 0.6.6
- **Python version**: 2.7 
- **Exact command to reproduce**:

### Describe the problem

This Problem prevails when using specifying the optimizer of  DDPG as Async Replay optimzier 
### Source code / logs

```
"File "/home/karimy/.local/lib/python2.7/site-packages/ray/rllib/agents/trainer.py", line 336, in train
    raise e
NameError: global name 'ray' is not defined
('Killing live simulation processes', set([]))

```

**Comment by robertnishihara** [comment]
Can you reliably reproduce this? Can you share a command or script that causes the issue?
