### ISSUE TITLE
[Data] Async `MapBatches` hangs upon exception raised from UDF

### ISSUE THREAD

**Issue by scottjlee** [ray-project/ray#47102]
### What happened + What you expected to happen

When using Ray Data's async `map_batches` API and an exception is raised from the UDF, the exception is not raised and the data execution will be hanging. See reproducible for a simple example

### Versions / Dependencies

ray master https://github.com/ray-project/ray/commit/b6d47928408504a1776ef92fccbda4d3a73ae5a5

### Reproduction script

```
import ray

class MyUDF:
    def __init__(self):
        pass

    async def __call__(self, batch):
        assert False
        yield batch

ds = ray.data.range(20)
ds = ds.map_batches(MyUDF, concurrency=2)
result = ds.materialize()
assert len(result) == 20
```
We should expect the script above to run to completion, but instead hangs forever without any indication of exception or failure.

### Issue Severity

None

**Comment by Bye-legumes** [comment]
@scottjlee  I add a exception queue to fix it and this is what look like now.
![image](https://github.com/user-attachments/assets/e40c26d4-9eef-4828-8aed-eab8b836d082)
