### ISSUE TITLE
Worker shared memory grows beyond object store size

### ISSUE THREAD

**Issue by louiskirsch** [ray-project/ray#4713]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7 dev 2
- **Python version**: 3.6.7

### Describe the problem
I have a worker whose shared memory size (RssShmem) keeps getting larger and large at a rate of 2 MB/s.
I figured it has to do with the ray objects I pass to its method.
Though, while my object store is limited to 1 GB (same for redis size) in size and objects are pruned correctly, the shared memory size keeps growing (past 20 GB). I've been struggling to isolate the issue. Can you give me some idea of what is stored in the shared memory except ray objects or why these might not be released even though they are no longer in the ray object store?

The general structure of the code is like this (but this does not reproduce the issue yet):
```
@ray.remote
class Worker:

    def work(self, data):
        ...
        return some_object


ray.init(object_store_memory=1000000000, redis_max_memory=1000000000)
worker = Worker.remote()
while True:
    out = ray.get(worker.work.remote(np.random.normal(size=[10000, 1000])))
    print(out)
```

I am also using the tensorflow ray store operation and the prefetch operation
```
raylet_client.fetch_or_reconstruct(ids, True)
```
Might this have anything to do with it?

**Comment by robertnishihara** [comment]
Does the application eventually crash from running out of memory?

Is it possible that the “out” variable never goes out or scope in Python?
That could prevent objects in the object store from being evicted.

Another possibility is that top or whatever took you are using to determine
memory usage is doing the bookkeeping incorrectly. I’ve seen this with
shared memory in the past.

**Comment by timediv** [comment]
The application did run out of memory but it seems like this was simply because the application did have slightly growing memory demands.

I believe your last statement was describing the problem: The memory bookkeeping was incorrect. I will try to verify that, but for now it looks like there is no memory leak!

**Comment by robertnishihara** [comment]
Great to hear. Let us know if the issue persists.

**Comment by TianhongDai** [comment]
Yup, I also have a similar issue, memory increases around 2MB/s.

**Comment by muhammadsyahyas** [comment]
> The application did run out of memory but it seems like this was simply because the application did have slightly growing memory demands.
> 
> I believe your last statement was describing the problem: The memory bookkeeping was incorrect. I will try to verify that, but for now it looks like there is no memory leak!

Do you already find how to get rid of the issue?
