### ISSUE TITLE
[core][adag] Support reading the same node from another DAG node and the driver

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#47156]
### What happened + What you expected to happen

Currently a DAG node can only be read by other DAG nodes or by the driver. We should support allowing it to be read by both. This should already work since the driver is represented by a proxy actor, so there might just be too strong of an assertion check right now.

### Versions / Dependencies

3.0dev

### Reproduction script

```python
with InputNode() as inp:
  x = a.foo.bind(inp)
  y = b.foo.bind(x)
  dag = MultiOutputNode([x, y])

dag = dag.experimental_compile()
```

### Issue Severity

None

**Comment by kevin85421** [comment]
This is duplicate with https://github.com/ray-project/ray/issues/47041

**Comment by stephanie-wang** [comment]
I don't think this is the same as #47041? This issue is reading the same channel from different actors, not reading the same channel multiple times from the same actor?
