### ISSUE TITLE
[core][aDAG] NestedTorchTensorNcclChannel should automatically detect whether the reader is on the same actor or not.

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#47169]
### What happened + What you expected to happen

```python
@pytest.mark.parametrize("ray_start_cluster_head_with_env_vars", [
        {
            "include_dashboard": True,
            "env_vars": {
                "NCCL_DEBUG": "WARN"
            },
            "num_gpus": 4,
        }
], indirect=True)
def test_basic(ray_start_cluster_head_with_env_vars, monkeypatch):
    monkeypatch.setattr(ray.dag.constants, "RAY_ADAG_ENABLE_DETECT_DEADLOCK", False)
    num_workers = 2
    workers = [Worker.remote(rank) for rank in range(num_workers)]
    with InputNode() as i:
        dag = workers[0].no_op.bind(i)
        dag = workers[1].no_op.bind(dag)
        dag.with_type_hint(TorchTensorType(transport=TorchTensorType.NCCL))
        branch1 = workers[0].no_op.bind(dag)
        branch2 = workers[1].no_op.bind(dag)
        dag = MultiOutputNode([branch1, branch2])
    compiled_dag = dag.experimental_compile()
    tensor_cpu = torch.zeros(10, 10)
    print(ray.get(compiled_dag.execute(tensor_cpu)))

    # Note: must teardown before starting a new Ray session, otherwise you'll get
    # a segfault from the dangling monitor thread upon the new Ray init.
    compiled_dag.teardown()
```

A CPU tensor will be implicitly converted into GPU tensor when it is sent by `NestedTorchTensorNcclChannel` (this issue is tracked by #46440). Therefore, worker1 sends the GPU tensor to worker0 and worker1. `self._nccl_group.send(tensor, rank)` will fail when the rank is the same as the writer.

1. In the short-term, we should improve observability. Users can't see useful error messages if `NCCL_DEBUG` is not set.
2. For a long-term solution, maybe we should detect whether the reader is on the same actor or not. If it is on the same actor, use the `IntraProcessChannel` instead.

### Use case

When we implement zero-bubble pipeline parallelism, `B` has a data dependency on its `W` (on the same actor) and on another actor's `B`. For the cross-actor communication, we want to use NCCL channel, and use `IntraProcessChannel` for the intra-actor communication. However, currently, if we specify 

```python
with_type_hint(TorchTensorType(transport=TorchTensorType.NCCL))
```

The `NestedTorchTensorNcclChannel` will be used, and it doesn't check whether the reader is on the same actor or not.

### Versions / Dependencies

nightly

### Reproduction script

see above

### Issue Severity

High: It blocks me from completing my task.

**Comment by stephanie-wang** [comment]
Hmm actually sorry I misunderstood this issue - yes, if the user tries to send a GPU tensor to the same actor, we should not attempt to create a NCCL channel and should just use the local channel.

Another case to figure out is if there are two actors on the same GPU, since NCCL doesn't support that. We could transfer through shared memory for now.
