### ISSUE TITLE
[Profiling/Nsight Systems] Remove high-overhead feature from the default config

### ISSUE THREAD

**Issue by snehakottapalli** [ray-project/ray#47178]
### Description

The default config for Nsight Systems currently turns on cudabacktrace
feature for all CUDA API calls. This is a very high overhead feature
that will perturb the timings of events collected by the tool. Remove
the high overhead cudabacktrace setting from the default config for
Nsight Systems.

### Use case

Reduce the overhead of profiling with the default config for Nsight Systems.

**Comment by rkooo567** [comment]
can you tell us about what cudabacktrace does briefly? 

@snehakottapalli also, feel free to make a contribution!

**Comment by snehakottapalli** [comment]
Nsight Systems provides the option --cudabacktrace to turn on the collection of backtraces when a CUDA API call is invoked. Significant runtime overhead may occur when this option is used. The CLI option --cudabacktrace can be set to all, none, kernel, memory, sync, or other to control which CUDA APIs should trigger the collection of a backtrace. Each value may be appended with a threshold after ‘:’. Threshold is duration, in nanoseconds, that CUDA APIs must execute before backtraces are collected, e.g. ‘kernel:500’. This feature is mainly used for debugging to understand which part of the code is launching CUDA kernels, CUDA memory operations and such.

From the documentation https://docs.nvidia.com/nsight-systems/UserGuide/index.html :

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>



  | Possible Parameters | Default | Description
-- | -- | -- | --
--cudabacktrace | all, none, kernel, memory, sync, other | none | When tracing CUDA APIs, enable the collection of a backtrace   when a CUDA API is invoked. Significant runtime overhead may occur. Values   may be combined using ‘,’. Each value except ‘none’ may be appended with a   threshold after ‘:’. Threshold is duration, in nanoseconds, that CUDA APIs   must execute before backtraces are collected, e.g. ‘kernel:500’. Default   value for each threshold is 1000ns (1us). Note: CPU sampling must be enabled.




</body>

**Comment by snehakottapalli** [comment]
I have created a pull request to close this issue. Please see https://github.com/ray-project/ray/pull/47180
