### ISSUE TITLE
[data] does ray.data support join operator? 

### ISSUE THREAD

**Issue by kadisi** [ray-project/ray#47174]
### Description

now ray.data support load, transform, iterate,shuffle operators. dose ray.data support join operator which can join two data sets through a unique primary key.

**Comment by scottjlee** [comment]
Currently, Ray Data does not support joins. Your best bet as of now is to perform the join somewhere upstream in your data pipeline, then read it into Ray Data.

**Comment by richardliaw** [comment]
Closing this as a repetition of https://github.com/ray-project/ray/issues/18911
