### ISSUE TITLE
[train][tune] Trainable doesn't accept RuntimeEnv 

### ISSUE THREAD

**Issue by dongreenberg** [ray-project/ray#47215]
### Description

In Runhouse, we're syncing the user's code onto the head node of the cluster and dynamically importing it within our HTTP server, which runs on top of Ray (it uses Actors to hold different server process replicas). As such, we call ray.init well before the user code is synced onto the cluster or known, so we can't include it explictly in the runtime_env. We want to support usage of Ray code within our user's programs, but Ray doesn't seem to find the Actor or Task underlying classes and functions within the new worker process at the time they're created (and unfortunately changes to sys.path or PYTHONPATH are not propagated into the worker). In order to create an Actor inside a Ray program which isn't included in ray.init, we have to do the following (or the equivalent using the decorator):
```
class MyActor:
   ...
   
pp = os.path.dirname(os.path.abspath(__file__)) + ":" + os.environ.get("PYTHONPATH", "")
my_actor = ray.remote(MyActor).options(runtime_env=RuntimeEnv(env_vars={"PYTHONPATH": pp})).remote()
ray.get(trainActor.setup.remote({"a": 1}))
```

This isn't ideal. I was suprised the module in which an Actor is defined isn't automatically synced into the worker.  But at least there's a workaround.

With Tune and Train there is no such workaround, because we can't control the runtime_env passed to the actors created by the Trainable class. The following fails in Runhouse, stating that the module in the which this code resides is not found when attempting to create the Trainable TemporaryActor internally:
```
class Trainable(tune.Trainable):
    ...

def find_minimum(num_concurrent_trials=2, num_samples=4, metric_name="score"):
    search_space = {
        "width": tune.uniform(0, 20),
        "height": tune.uniform(-100, 100),
    }
    tuner = tune.Tuner(
        Trainable,
        tune_config=tune.TuneConfig(
            metric=metric_name,
            mode="max",
            max_concurrent_trials=num_concurrent_trials,
            num_samples=num_samples,
            reuse_actors=True,
        ),
        param_space=search_space,
    )
    tuner.fit()
```

Ideally, we'd have a global setting within a given worker process that env vars should propogate into Actors or Tasks created within that process. That way, in both cases (Core and Tune/Train) we could just control the sys.path or PYTHONPATH and know that it would propagate, without having access to the RuntimeEnv. I think this is also a desirable property in general - propagating env vars through processes is a common pattern (e.g. for passing secrets).

Another option would be to honor runtime_env info when `ray.init(ignore_reinit_error=True, runtime_env=..., namespace="new_namespace")` is called with a different namespace than the current namespace, so Actors and Tasks created would have that namespace and runtime_env by default.

**Comment by justinvyu** [comment]
@dongreenberg Runtime environment propagation/inheritance should already work -- see the example below. Am I understanding your problem correctly?

```python
import os
import ray

ray.init(runtime_env={"env_vars": {"ASDF": "1"}})


@ray.remote
class A:
    def check(self):
        print(os.environ.get("ASDF"))


@ray.remote
def task():
    print(os.environ.get("ASDF"))

    subactor = A.remote()
    ray.get(subactor.check.remote())


ray.get(task.remote())
```

```
(task pid=96367) 1
(A pid=96369) 1
```

**Comment by justinvyu** [comment]
> I was suprised the module in which an Actor is defined isn't automatically synced into the worker.

The actor class is pickled over by itself, rather than packaging the full module it resides in. To ship over the local package, you can use the `py_modules` configuration in the runtime environment. See here: https://docs.ray.io/en/latest/ray-core/handling-dependencies.html#library-development

**Comment by dongreenberg** [comment]
Unfortunately no, this won't work. We are running an API server on top of Ray, so after we start Ray and ray.init, we're importing user code which is any Python, and can create ray tasks/actors or train/tune jobs inside it. We need to be able to manipulate the environment variables that all tasks or actors inherit *after* ray.init it is already called, and we don't have direct access to the runtime_env for the users tests or actors. Those are in their own code.

We could also have the users run ray.init themselves (be unaware that our server runs on Ray, which would be in separate ports), but I'm not sure if that "ray in ray" execution is a good idea. 

If we could just set environment variables in an Actor that subsequent actors or tasks created in that process (standard behavior for env vars), this would be fine too. 

WDYT?

**Comment by dongreenberg** [comment]
I figured out a complex workaround to this
