### ISSUE TITLE
[core] Update the `ray.get` documentation to clarify when an exception gets raised for a list of object refs 

### ISSUE THREAD

**Issue by justinvyu** [ray-project/ray#47231]
### Description

This bug highlighted a gap in the documentation: https://github.com/ray-project/ray/issues/47204

It's unclear *when* an error gets raised when one of the N tasks in a `ray.get` call fails. **The expected behavior should be raising immediately any one of the tasks fails.**

### Link

https://docs.ray.io/en/latest/ray-core/api/doc/ray.get.html#ray.get

> [Exception](https://docs.python.org/3/library/exceptions.html#Exception) – An exception is raised if the task that created the object or that created one of the objects raised an exception.

**Comment by anyscalesam** [comment]
Correct behavior is when something fails it should immediately raise an exception...

**Comment by jjyao** [comment]
@dentiny can you take this?

**Comment by dentiny** [comment]
> @dentiny can you take this?

Sure, seems a good opportunity to learn ray behavior :-) Let me know if I mis-undrerstand.
