### ISSUE TITLE
Rllib Contrib: Can alphazero folder be updated to latest library of ray 2.34.0?

### ISSUE THREAD

**Issue by tarunhike** [ray-project/ray#47296]
### Description

Currently alphazero in rllib contrib is requiring 2.5.1. Could you please upgrade this to current version 2.34.0?

Also, it looks like this isn't multiagent supported. Can you please add multiagent support?

**Comment by simonsays1980** [comment]
@tarunhike Thanks for raising this issue. The algorithms in `rllib_contrib` are not considered in current development and are also not considered in the near future to be updated to work with current Ray/RLlib versions. If `AlphaZero` will be implemented in our new stack depends, if many users demand it. So far you are the first requesting such an update.
