### ISSUE TITLE
Tensorflow RNN Error 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#473]
On a m4.16xlarge - The following error is thrown:
```
*** Error in `python': double free or corruption (!prev): 0x0000000000b16680 ***
Aborted (core dumped)
```
when the following script is run
```
import ray
import tensorflow.contrib.rnn as rnn

if __name__ == '__main__':
    ray.init()
```

**Comment by raopku** [comment]
@richardliaw 
The code works on my machine. I use tensorflow '0.11.0rc0'

**Comment by robertnishihara** [comment]
I'm going to close this because I haven't been able to reproduce this. If you experience this again, please reopen.
