### ISSUE TITLE
KeyError: 'weights' in RLlib using async_replay_optimizer

### ISSUE THREAD

**Issue by zhan0903** [ray-project/ray#4730]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

I met a KeyValue error just showed below. Why the sample batches of experiences have the attribute "weights"?  Thanks.

### Source code / logs

```python
In async_replay_optimizer.py", in add_batch
    row["new_obs"], row["dones"], row["weights"])
KeyError: 'weights'
```

**Comment by ericl** [comment]
Those are the importance weights for prioritized replay -- you can set those to all 1s if not sure.

**Comment by zhan0903** [comment]
> Those are the importance weights for prioritized replay -- you can set those to all 1s if not sure.
> 
> Btw, how did you come upon this error?

I think it is because there is something wrong with my DDPG pytorch graph implementation.  So how to implement the weights for prioritized replay using the pytorch? Thanks.

**Comment by ericl** [comment]
The prio weights are added by DDPGPostprocessing, which calls _postprocess_dqn(), in this function: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/dqn/dqn_policy_graph.py#L636

You should make sure your custom policy graph also adds the "weights" column to the batch in your graph postprocess function. It could just be `batch[PRIO_WEIGHTS] = np.ones_like(batch[SampleBatch.REWARDS])`.

**Comment by zhan0903** [comment]
> The prio weights are added by DDPGPostprocessing, which calls _postprocess_dqn(), in this function: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/dqn/dqn_policy_graph.py#L636
> 
> You should make sure your custom policy graph also adds the "weights" column to the batch in your graph postprocess function. It could just be `batch[PRIO_WEIGHTS] = np.ones_like(batch[SampleBatch.REWARDS])`.
Thanks, it works.

**Comment by zhan0903** [comment]
> The prio weights are added by DDPGPostprocessing, which calls _postprocess_dqn(), in this function: https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/dqn/dqn_policy_graph.py#L636
> 
> You should make sure your custom policy graph also adds the "weights" column to the batch in your graph postprocess function. It could just be `batch[PRIO_WEIGHTS] = np.ones_like(batch[SampleBatch.REWARDS])`.

Thanks. It works.
