### ISSUE TITLE
[Train] Placement group reserved resources breaking changes

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/ray#47316]
### What happened + What you expected to happen

![Screenshot from 2024-08-24 11-49-54](https://github.com/user-attachments/assets/3c663799-c360-4c0d-bdee-c8395c25f797)

- In Ray 2.9.0, the reserved resources for CPUs are `1, 2, 2`
- In Ray 2.34.0, the reserved resources for CPUs are `3, 2`

Is this a breaking change that is not documented?

In KubeRay example like this https://docs.ray.io/en/releases-2.34.0/cluster/kubernetes/examples/mnist-training-example.html

Because each nodes only have 2 CPUs, this example causes them to fail.

### Versions / Dependencies

2.34.0

### Reproduction script

https://docs.ray.io/en/releases-2.34.0/cluster/kubernetes/examples/mnist-training-example.html

Run the above example with both Ray 2.9.0 and Ray 2.34.0 and see the differences.

### Issue Severity

None

**Comment by MortalHappiness** [comment]
cc @kevin85421

**Comment by kevin85421** [comment]
cc @woshiyyya @justinvyu is this an expected breaking change? It breaks a KubeRay example. It's an easy fix for me, but not sure whether other Ray Train users will have the same issue or not.

**Comment by justinvyu** [comment]
This is a result of the `trainer_resources` bundle getting merged. You can work around this by setting `trainer_resources={"CPU": 0}`.
