### ISSUE TITLE
[Core] mypy failure when `.options(...)` is used on functions decorated with `@ray.remote`

### ISSUE THREAD

**Issue by milesvant** [ray-project/ray#47329]
### What happened + What you expected to happen

`RemoteFunction[N]` stubs don't include a `.options` function, leading to spurious type failures.

### Versions / Dependencies

Nightly Ray, Python 3.10, Ubuntu 22.04

### Reproduction script

```
import ray

@ray.remote
def fn(x: int) -> int:
    return 2 * x

def main() -> None:
    fn_with_cpus = fn.options(num_cpus=1)
    print(ray.get(fn_with_cpus.remote(4)))

if __name__ == "__main__":
    ray.init()
    main()
    ray.shutdown()
```

produces: `error: "RemoteFunction0[int, int]" has no attribute "options"  [attr-defined]`

### Issue Severity

Low: It annoys or frustrates me.

**Comment by zen-xu** [comment]
What you need is [sunray](https://github.com/zen-xu/sunray)

![Image](https://github.com/user-attachments/assets/428e0c06-55bf-4d06-970c-a91aa9375ea0)
