### ISSUE TITLE
[Core] Fix flaky test_placement_group_4.py

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47377]
### What happened + What you expected to happen

<img width="1643" alt="Screenshot 2024-08-27 at 9 31 31 PM" src="https://github.com/user-attachments/assets/26b0a1df-bc64-409b-9dbf-88f3f04dfec8">

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by anyscalesam** [comment]
@rkooo567 @rkooo567 this is not as weekly release blocker? cc @can-anyscale

**Comment by jjyao** [comment]
Our bot will create flaky test tickets. Closing this manually created one.
