### ISSUE TITLE
[Core] Fix flaky test_streaming_generator_2.py

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47376]
### What happened + What you expected to happen

<img width="1612" alt="Screenshot 2024-08-27 at 9 30 19 PM" src="https://github.com/user-attachments/assets/e46802f7-72f6-4188-9fb6-369498d8dbb1">

### Versions / Dependencies

master

### Reproduction script

n/a

### Issue Severity

None

**Comment by anyscalesam** [comment]
Not a weekly release blocker? @jjyao @rkooo567

**Comment by jjyao** [comment]
Our bot will create flaky test tickets. Closing this manually created one.
