### ISSUE TITLE
[ADAG][Experimental] Shutdown exception when inference with vllm + Adag

### ISSUE THREAD

**Issue by Bye-legumes** [ray-project/ray#47413]
### What happened + What you expected to happen

NOTE: The perf issue is resolved in the latest vllm. But it has shutdown issue https://github.com/ray-project/ray/issues/47413#issuecomment-2321506468.

~~I observed the performance regression when I use vllm with adag and that issue becomes when I use ray 2.35.0
My experiment setting is llama7b + TP=2 +  RTX A6000~~

~~Default with mp~~
~~Tokens per second: 4250.70 ~~

~~backend with ray
Tokens per second: 4258.55~~

~~backend with  adag (ray 2.34)
Tokens per second: 3235.51~~

~~backend with  adag (ray 2.35)
Tokens per second: 2928.51~~

### Versions / Dependencies

2.35.0

### Reproduction script

export DISTRIBUTED_EXECUTOR_BACKEND=ray
export VLLM_USE_RAY_SPMD_WORKER=1
export VLLM_USE_RAY_COMPILED_DAG=1
```
import time
from vllm import LLM, SamplingParams

# Set the tensor parallelism size
tensor_parallelism_size = 2

# Initialize the model
model_path = "/home/models/Llama-2-7b-hf"
llm = LLM(model=model_path, tensor_parallel_size=tensor_parallelism_size,distributed_executor_backend="ray")

# Define the batch of prompts
prompts = [
    "Once upon a time, in a land far, far away,",
    "The quick brown fox jumps over the lazy dog.",
    "In the midst of the dense forest, a lonely wolf howled at the moon.",
    "To be, or not to be, that is the question.",
    "Artificial intelligence is transforming the world."
]

# Set sampling parameters
sampling_params = SamplingParams(max_tokens=50, temperature=0.7)

# Warm-up the model with a simple inference
warmup_prompt = ["Warm-up prompt"]
llm.generate(warmup_prompt, sampling_params)

# Measure inference time
start_time = time.time()

# Perform batch inference
outputs = llm.generate(prompts*100, sampling_params)

# Calculate the number of tokens generated
total_tokens = sum(len(completion.token_ids) for output in outputs for completion in output.outputs)

# Calculate the total time taken for inference
total_time = time.time() - start_time

# Calculate tokens per second
tokens_per_second = total_tokens / total_time

print(f"Total tokens generated: {total_tokens}")
print(f"Total time taken (seconds): {total_time:.4f}")
print(f"Tokens per second: {tokens_per_second:.2f}")
```

### Issue Severity

None

**Comment by Bye-legumes** [comment]
@rkooo567 I just update the new ray and I found the regression becomes worse, can you check if my setting is correct? Thx

**Comment by rkooo567** [comment]
what's the vllm version @Bye-legumes ? 

besides, you may want to benchmark with temperature=0 and ignore_eos=True in sampling param because your output could be changed based on this setting. Let us check if there was any regression in our benchmark

**Comment by Bye-legumes** [comment]
> what's the vllm version @Bye-legumes ?
> 
> besides, you may want to benchmark with temperature=0 and ignore_eos=True in sampling param because your output could be changed based on this setting. Let us check if there was any regression in our benchmark


Thanks for you suggestions! I just check with your settings and my vllm version is 0.5.5 and I think it's at the same level now.
Default with mp
Tokens per second: 4538.54

backend with ray  (ray 2.35 + vllm 0.5.5)
Tokens per second: 4532.00

backend with  adag (ray 2.35 + vllm 0.5.5)
Tokens per second: 4466.62

Also, does this exception matters?
```
(RayWorkerWrapper pid=231861) INFO 08-30 10:49:32 custom_all_reduce.py:223] Registering 2275 cuda graph addresses
(RayWorkerWrapper pid=231861) INFO 08-30 10:49:32 model_runner.py:1300] Graph capturing finished in 13 secs.
Exception ignored in: <function LLMEngine.__del__ at 0x7f3fe16ab060>
Traceback (most recent call last):
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 492, in __del__
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 72, in shutdown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/dag/compiled_dag_node.py", line 1707, in teardown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/dag/compiled_dag_node.py", line 1505, in teardown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/logging/__init__.py", line 1489, in info
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/logging/__init__.py", line 1634, in _log
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/logging/__init__.py", line 1644, in handle
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/logging/__init__.py", line 978, in handle
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/_private/log.py", line 52, in emit
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function RayGPUExecutor.__del__ at 0x7f409eab05e0>
Traceback (most recent call last):
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 484, in __del__
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 72, in shutdown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/dag/compiled_dag_node.py", line 1707, in teardown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/dag/compiled_dag_node.py", line 1502, in teardown
  File "/home/zhilong/miniconda3/envs/vllm/lib/python3.11/site-packages/ray/dag/compiled_dag_node.py", line 1472, in wait_teardown
AttributeError: 'NoneType' object has no attribute 'GetTimeoutError'

```

**Comment by rkooo567** [comment]
that's great! that matches my expectation. I think it will have better perf for PP and low batch size (like online serving case).

regarding error, I think it is unexpected. Does it happen in the latest ray master?

**Comment by Bye-legumes** [comment]
> that's great! that matches my expectation. I think it will have better perf for PP and low batch size (like online serving case).
> 
> regarding error, I think it is unexpected. Does it happen in the latest ray master?

both vllm and ray are the latest.

**Comment by rkooo567** [comment]
@Bye-legumes we can repro it using the script you posted right? we will take a look

**Comment by rkooo567** [comment]
NOTE: perf issue is resolved. But it has shutdown issue. I changed the titile

**Comment by Bye-legumes** [comment]
> @Bye-legumes we can repro it using the script you posted right? we will take a look

yes, you can reproduce it. Also I submit this issue and a naïve solution for reference to vllm side https://github.com/vllm-project/vllm/issues/8208. And that can fix this issue. (In fact there are two issues, vllm side and ray side, both of them raise exception when shutting down)If you have better suggestions we can also try to fix from adag side.

**Comment by rkooo567** [comment]
I think ideally, adag should never had this issue in whatever circumstance. but we are in shortage of bandwidth now, and if you have some short-term solution, I'd love to review and merge it!

**Comment by Bye-legumes** [comment]
fixed now
