### ISSUE TITLE
[RLlib] Rename of `SingleAgentRLModuleSpec` to `RLModuleSpec` breaks restoring old checkpoints

### ISSUE THREAD

**Issue by Kakadus** [ray-project/ray#47426]
### What happened + What you expected to happen

I wanted to restore checkpoints created with ray v2.34.0 with ray v2.35.0, which errors with

```
>>> from ray.rllib.algorithms import Algorithm
>>> Algorithm.from_checkpoint(path=".../ray_results/pbt_humanoid_test/PPO_Humanoid-v4_3338d_00003_3_2024-09-09_00-46-34/checkpoint_000014")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.cache/pypoetry/virtualenvs/ray-f4XCQ9mO-py3.12/lib/python3.12/site-packages/ray/rllib/algorithms/algorithm.py", line 399, in from_checkpoint
    state = Algorithm._checkpoint_info_to_algorithm_state(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.cache/pypoetry/virtualenvs/ray-f4XCQ9mO-py3.12/lib/python3.12/site-packages/ray/rllib/algorithms/algorithm.py", line 3442, in _checkpoint_info_to_algorithm_state
    state = pickle.load(f)
            ^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'SingleAgentRLModuleSpec' on <module 'ray.rllib.core.rl_module.rl_module' from '.../.cache/pypoetry/virtualenvs/ray-f4XCQ9mO-py3.12/lib/python3.12/site-packages/ray/rllib/core/rl_module/rl_module.py'>
```

I expected to be able to restore checkpoints from older ray versions after the upgrade.

Adding a line like
```py
SingleAgentRLModuleSpec = RLModuleSpec
```
to `ray/rllib/core/rl_module.rl_module.py` allows me to continue from the old checkpoint.

This seems to be caused by https://github.com/ray-project/ray/pull/46840

### Versions / Dependencies

python 3.10.12 / 3.12.5
ray v2.35.0

### Reproduction script

Create a checkpoint with ray 2.34.0, upgrade to ray 2.25.0 and try to restore the checkpoint

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

edit: replaced the traceback with a more minimal one.

**Comment by simonsays1980** [comment]
@Kakadus thanks for raising this issue. We overhauled the checkpointing in newer version to give it a higher flexibility.

You could use `copyreg` and a dynamic binding to influence how `pickle` loads the `SingleAgentRLModuleSpec`: 

```python
import copyreg
import pickle
import ray.rllib.core.rl_module.rl_module as rl_module
from rl_module import RLModuleSpec


def single_agent_rl_module_spec_constructor(*args, **kwargs):
    """Constructor to replace SingleAgentRLModuleSpec with RLModuleSpec."""
    return RLModuleSpec(*args, **kwargs)

# Dynamically alias the old class name to the new one
rl_module.SingleAgentRLModuleSpec = RLModuleSpec

# Tell `pickle` how to handle old `SingleAgentRLModuleSpec` instances.
copyreg.pickle(
    ("ray.rllib.core.rl_module", "SingleAgentRLModuleSpec"),
    single_agent_rl_module_spec_constructor,
)

# Try loading the checkpoint.
Algorithm.from_checkpoint(...)

```

**Comment by Kakadus** [comment]
Thanks @simonsays1980

If I understand correctly, #47708 will prevent this type of error from happening in the future; making the created checkpoints more backward compatible, while this error has to be worked around. Would it make sense to merge #47560 then to have at least one release which is able to restore older checkpoints?
