### ISSUE TITLE
[<Ray component: data>]  Ray data can not handle big dataset.

### ISSUE THREAD

**Issue by luxunxiansheng** [ray-project/ray#47444]
### What happened + What you expected to happen

```
from datasets import load_dataset.     # hugging face's datasets

hf_dataset_stream = load_dataset("openwebtext", streaming=True, split="train")                                                                       
ray_ds_stream = ray.data.from_huggingface(hf_dataset_stream)                                                                                               
ray_ds_stream.write_parquet("outputpath"])
```

openwebtext is huge with 9B rows.  I would like to save it to a parquet file with a 32G RAM machine

Expected:
      The ray data can handle this smoothly .

What happended:
     OOM. 
![image](https://github.com/user-attachments/assets/9e2b3467-daad-4837-9b27-f8dc434f0bb5)

-----------------------------------
Is there any way to never load all the file content  into memory when using ray data ?  Suppose there are 10000 blocks, it is possible to streaming the 20 blocks into the memory and keep other blocks remaining in the disk?

If I missed something in doc, pls refer me to the links. 

Thanks a lot.

   

### Versions / Dependencies

2.34

### Reproduction script

`hf_dataset_stream = load_dataset("openwebtext", streaming=True, split="train")
ray_ds_stream = ray.data.from_huggingface(hf_dataset_stream)
ray_ds_stream.write_parquet("outputpath"])
`

### Issue Severity

High: It blocks me from completing my task.

**Comment by scottjlee** [comment]
Is this the `openwebtext` dataset being used here? https://huggingface.co/datasets/Skylion007/openwebtext

If so, it looks like this dataset does not have the auto-converted Parquet files; the text at the top of the page says:

>you can use [convert_to_parquet](https://huggingface.co/docs/datasets/main/en/cli#convert-to-parquet) from the datasets library


Which means that Ray Data will not be able to parallelize the reads across multiple parquet files. This is likely the reason why you are seeing OOMs, because this is basically doing a single-node read of the entire dataset.

You can try setting `from_huggingface(..., concurrency=1)`, `write_parquet(..., concurrency=N)`, so that the write operations can finish writing blocks faster than `from_huggingface` reads new data blocks into memory, so that you avoid having blocks queued up in memory.

**Comment by luxunxiansheng** [comment]
> Is this the `openwebtext` dataset being used here? https://huggingface.co/datasets/Skylion007/openwebtext
> 
> If so, it looks like this dataset does not have the auto-converted Parquet files; the text at the top of the page says:
> 
> > you can use [convert_to_parquet](https://huggingface.co/docs/datasets/main/en/cli#convert-to-parquet) from the datasets library
> 
> Which means that Ray Data will not be able to parallelize the reads across multiple parquet files. This is likely the reason why you are seeing OOMs, because this is basically doing a single-node read of the entire dataset.
> 
> You can try setting `from_huggingface(..., concurrency=1)`, `write_parquet(..., concurrency=N)`, so that the write operations can finish writing blocks faster than `from_huggingface` reads new data blocks into memory, so that you avoid having blocks queued up in memory.

Yes. I have split the dataset into 2000 files by my own to make Ray Data work.                                                                                but In my oppnion,  neither this approach nor `from_huggingface(..., concurrency=1)`, `write_parquet(..., concurrency=N)`  is an elegant  solution because it exposes too much  detail to Ray Data end user.   Ray data 's  streaming mechanism should take care of this somehow.

**Comment by scottjlee** [comment]
Yes, i agree that it's not ideal for users to fiddle with configs, but we currently don't have the bandwidth to work on a more intelligent auto-tune system for concurrency. We welcome contributions from the community :)

**Comment by luxunxiansheng** [comment]
> Yes, i agree that it's not ideal for users to fiddle with configs, but we currently don't have the bandwidth to work on a more intelligent auto-tune system for concurrency. We welcome contributions from the community :)

@_@. Understood.

**Comment by richardliaw** [comment]
Closing this issue for now - we can reopen when there's more interest/more contributors willing to help out!
