### ISSUE TITLE
[RuntimeEnv] RAY_RUNTIME_ENV_CREATE_WORKING_DIR is not used in env_vars

### ISSUE THREAD

**Issue by sisilmehta733** [ray-project/ray#47484]
### What happened + What you expected to happen

We'r using ray 2.35.0

Currently we use pip to install the dependencies in the runtime env. Some of the python dependencies are libraries in a private Google Artifact Repository. To fetch those, we'r using a pip.conf file that stores the extra-index-url with the access token.

The pip.conf file is uploaded with the current working dir. However, the pip install cmd that runs in the runtime env can't find the pip.conf file when using RAY_RUNTIME_ENV_CREATE_WORKING_DIR to reference the path. It seems "RAY_RUNTIME_ENV_CREATE_WORKING_DIR" is never used in the env_vars.

1. What is the right way to set the path of pip.conf file that is present in the working dir
2. What is the right way to ensure the env_vars has the right path and it is used during pip install

```
ray job submit --address="ip_address" \
--runtime-env-json='{"working_dir": ".", "pip": ["./requirements.txt"], "env_vars": {"PIP_CONFIG_FILE": "${RAY_RUNTIME_ENV_CREATE_WORKING_DIR}/pip.conf"}}' \
--no-wait \
--submission-id "test_job" \
-- python test_script.py
```

### Versions / Dependencies

ray 2.35.0

### Reproduction script

ray job submit --address="ip_address" \
--runtime-env-json='{"working_dir": ".", "pip": ["./requirements.txt"], "env_vars": {"PIP_CONFIG_FILE": "${RAY_RUNTIME_ENV_CREATE_WORKING_DIR}/pip.conf"}}' \
--no-wait \
--submission-id "test_job" \
-- python test_script.py

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
Hi @sisilmehta733 Can you have the extra index url inside the `requirements.txt` just like https://stackoverflow.com/questions/2477117/pip-requirements-txt-with-alternative-index so you don't need to set up env_vars and working_dir which are not designed to be used by the pip runtime env plugin.

**Comment by sisilmehta733** [comment]
Right we added the extra-index url inside the requirements.txt file and that worked out.
