### ISSUE TITLE
Subclasses of dict are not serialized correctly

### ISSUE THREAD

**Issue by andyljones** [ray-project/ray#4750]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.3
- **Ray installed from (source or binary)**: pip, which I think is binary?
- **Ray version**: 0.6.5
- **Python version**: 3.7.3
- **Exact command to reproduce**: See example below

### Describe the problem
Subclasses of `dict` returned from a remote function are deserialized as empty.

### Source code / logs
```python
import ray
ray.init()

class SubDict(dict):
    pass

@ray.remote
def f():
    return SubDict(a=1)

ray.get(f.remote()) # is empty
```

The workaround is to register a custom serializer with 

```ray.register_custom_serializer(SubDict, use_pickle=True)```

as suggested in the similar-but-possibly-unrelated OrderedDict subclassing issue [here](https://github.com/ray-project/ray/issues/1803#issuecomment-484260517).

**Comment by robertnishihara** [comment]
Thanks for posting the workaround. This is related to how pyarrow serializes objects, and is fixable.

**Comment by hartikainen** [comment]
cc @febert @orybkin this is the same issue that caused problems with your `AttrDict`.

**Comment by robertnishihara** [comment]
This is fixed (and there's no need for a workaround now).
