### ISSUE TITLE
Issue when installing ray on the server

### ISSUE THREAD

**Issue by stellaxu** [ray-project/ray#4751]
I have tried the following two ways to install ray:
i) git clone https://github.com/ray-project/ray.git

# Install Bazel.
ray/ci/travis/install-bazel.sh

cd ray/python
pip install -e . --verbose  # Add --user if you see a permission denied error.

and 
ii) pip install git+https://github.com/ray-project/ray.git#subdirectory=python

However, both of the installation methods make me encounter the same issues like the followings and the installation fails:
 + /usr/bin/bazel build //:ray_pkg --verbose_failures
  WARNING: Output base '/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/b3db6e5
3abb46b79c0d17fc1ae49278c' is on NFS. This may lead to surprising failures and u
ndetermined behavior.
  Problem with java installation: couldn't find/access rt.jar in /usr/lib/jvm/ja
va-10-oracle

Would you please help me to figure it out?

Thanks a lot.

**Comment by robertnishihara** [comment]
I suspect that is not the real error (since it just says "warning"). Can you include the full output from installation?

Also, if you want to build from source, then I recommend first cloning the repository and then installing from the local copy.

If you don't plan on modifying Ray, then I'd suggest not building from source and instead using the wheels that we publish, e.g., `pip install -U ray`. If you want the wheels for the latest commits, follow the instructions at https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master.

**Comment by stellaxu** [comment]
Hi, Robert:
Since I need to add algorithms to RLlib, perhaps I have to build from source.

The full output (starting from the point a little bit before the error occurs) is the following:
    Installing collected packages: numpy, six, pyarrow
    Successfully installed numpy-1.16.3 pyarrow-0.12.0.RAY six-1.12.0
    + export PYTHON_BIN_PATH=/work/xuweinan/anaconda3/bin/python
    + PYTHON_BIN_PATH=/work/xuweinan/anaconda3/bin/python
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + /usr/bin/bazel build //:ray_pkg --verbose_failures
    WARNING: Output base '/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c0c6c37ad0fdc6b363526c0a5807' is on NFS. This may lead to surprising failures and undetermined behavior.
    Problem with java installation: couldn't find/access rt.jar in /usr/lib/jvm/java-10-oracle
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/work/xuweinan/ray/python/setup.py", line 183, in <module>
        license="Apache 2.0")
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_d
evelopment
        self.run_command('build_ext')
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/work/xuweinan/ray/python/setup.py", line 74, in run
        subprocess.check_call(command)
      File "/work/xuweinan/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/work/xuweinan/anaconda3/bin/python']' returned non-zero
 exit status 1.
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-7qj5y9kt'
ERROR: Command "/work/xuweinan/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/work/xuweinan/ray/python
/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.cl
ose();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /work/xuweinan/ray/pyth
on/
Exception information:
Traceback (most recent call last):
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 912, in install
    install_options, global_options, prefix=prefix,
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 768, in install_editab
le
    cwd=self.setup_py_dir,
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/work/xuweinan/anaconda3/bin/python -c 'import setuptools, tokenize;__
file__='"'"'/work/xuweinan/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repla
ce('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with er
ror code 1 in /work/xuweinan/ray/python/

**Comment by stellaxu** [comment]
In addition, what do you mean by installing from the local copy?
thxs

**Comment by tmorgan4** [comment]
FYI, you can install ray via pip and then install just the tune and rllib libraries in development mode.  Unfortunately it results in a very fragile install that will delete your tune and rllib folders if you upgrade ray without removing the aliases first.  Details are found here:  https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install

**Comment by stellaxu** [comment]
Hi，currently there is another bug for installation. Would you please help me to figure it out? Thxs a lot.
The debug output is as follows: 

    + /home/eecs/xuweinan/.bazel/bin/bazel build //:ray_pkg --verbose_failures  
    WARNING: Output base '/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c
0c6c37ad0fdc6b363526c0a5807' is on NFS. This may lead to surprising failures and
 undetermined behavior.                                                         
    Starting local Bazel server and connecting to it...                         
    INFO: Invocation ID: 4ccf97d9-896c-4694-9b10-9326c6267ae9                   
    Loading:                                                                    
    Loading: 0 packages loaded                                                  
    Loading: 0 packages loaded                                                  
    Loading: 0 packages loaded                                                  
    Loading: 0 packages loaded                                                  
        currently loading:                                                      
    Analyzing: target //:ray_pkg (1 packages loaded, 0 targets configured)      
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)     
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)     
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)     
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)     
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
   ERROR: /work/xuweinan/ray/BUILD.bazel:611:1:no such package '@plasma//': Tr
aceback (most recent call last):                                                                                           
        File "/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c0c6c37ad0fdc
6b363526c0a5807/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163   
                _clone_or_update(ctx)                                           
        File "/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c0c6c37ad0fdc
6b363526c0a5807/external/bazel_tools/tools/build_defs/repo/git.bzl", line 73, in
 _clone_or_update                                                               
                fail(("error cloning %s:\n%s" % (ctx....)))                     
    error cloning plasma:                                                       
    Timed out; also encountered an error while attempting to retrieve output and
 referenced by '//:ray_pkg'                                                     
    ERROR: Analysis of target '//:ray_pkg' failed; build aborted: no such packag
e '@plasma//': Traceback (most recent call last):
        File "/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c0c6c37ad0fdc
6b363526c0a5807/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
                _clone_or_update(ctx)
        File "/home/eecs/xuweinan/.cache/bazel/_bazel_xuweinan/c6c4c0c6c37ad0fdc
6b363526c0a5807/external/bazel_tools/tools/build_defs/repo/git.bzl", line 73, in
 _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
    error cloning plasma:
    Timed out; also encountered an error while attempting to retrieve output
   INFO: Elapsed time: 885.971s                                                
    INFO: 0 processes.                                                          
    FAILED: Build did NOT complete successfully (3 packages loaded, 16 targets c
onfigured)
    FAILED: Build did NOT complete successfully (3 packages loaded, 16 targets c
onfigured)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/work/xuweinan/ray/python/setup.py", line 183, in <module>
        license="Apache 2.0")
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/__in
it__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/core.py", line 148,
 in setup
        dist.run_commands()
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 955,
 in run_commands
        self.run_command(cmd)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 974,
 in run_command                                                                 
        cmd_obj.run()                                                           
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/comm
and/develop.py", line 38, in run                                                
        self.install_for_development()                                          
      File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/setuptools/comm
and/develop.py", line 140, in install_for_development                           
        self.run_command('build_ext')                                           
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/cmd.py", line 313,
in run_command
        self.distribution.run_command(command)
      File "/work/xuweinan/anaconda3/lib/python3.6/distutils/dist.py", line 974,
 in run_command
        cmd_obj.run()
      File "/work/xuweinan/ray/python/setup.py", line 74, in run
        subprocess.check_call(command)
      File "/work/xuweinan/anaconda3/lib/python3.6/subprocess.py", line 311, in
check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/work/xuweina
n/anaconda3/bin/python']' returned non-zero exit status 1.                      
Cleaning up...                                                                  
Removed build tracker '/tmp/pip-req-tracker-ueb1nia_'                           
ERROR: Command "/work/xuweinan/anaconda3/bin/python -c 'import setuptools, token
ize;__file__='"'"'/work/xuweinan/ray/python/setup.py'"'"';f=getattr(tokenize, '"
'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"'
);f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" fa
iled with error code 1 in /work/xuweinan/ray/python/                            
Exception information:                                                          
Traceback (most recent call last):                                              
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/b
ase_command.py", line 178, in main                                              
    status = self.run(options, args)                                            
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/comm$
nds/install.py", line 414, in run                                               
    use_user_site=options.use_user_site,                                        
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/_
_init__.py", line 58, in install_given_reqs
    **kwargs
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/req/r
eq_install.py", line 768, in install_editable
    cwd=self.setup_py_dir,
  File "/work/xuweinan/anaconda3/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/work/xuweinan/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/work/xuweinan/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /work/xuweinan/ray/python/

**Comment by robertnishihara** [comment]
It seems like the error is related to cloning plasma... could there be any issue with the internet? Does the issue persist consistently?

**Comment by stellaxu** [comment]
Hi, Robert. Yes, this same issue happens every time when I installed on the atlas cluster, and is there any way to solve it?
Thxs.

**Comment by robertnishihara** [comment]
What happens if you run `git clone https://github.com/apache/arrow.git` on that machine? Does it work?

I'm not really sure what the issue is unfortunately.

**Comment by stellaxu** [comment]
Hi, Robert. I run the git code, but the installation still fails due to the same reason "ERROR: /work/xuweinan/ray/BUILD.bazel:611:1:no such package '@plasma//': Tr
aceback (most recent call last):". I think if this issue can be solved, then the installation on atlas would succeed.

**Comment by developeralgo8888** [comment]
i am having similar issues installing on UBUNTU 18.04 due to opencensus issues . when i try to build ray from the sources .  i am using   [ bazel release 0.25.3 ] . I also did the same process as @robertnishihara , but all did have the same failure. i even cleared all the wheel cache but that didnt help 



` Installing collected packages: six, numpy, pyarrow
    Successfully installed numpy-1.16.3 pyarrow-0.12.0.RAY six-1.12.0
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/pyarrow-0.12.0.RAY.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/six.py already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/__pycache__ already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/numpy already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/six-1.12.0.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/numpy-1.16.3.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/pyarrow already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/ray/pyarrow_files/bin already exists. Specify --upgrade to force replacement.
    + export PYTHON_BIN_PATH=/home/anaconda3/bin/python
    + PYTHON_BIN_PATH=/home/anaconda3/bin/python
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + /usr/local/bin/bazel build //:ray_pkg --verbose_failures
    Extracting Bazel installation...
    Starting local Bazel server and connecting to it...
    Loading:
    Loading: 0 packages loaded
    DEBUG: Rule 'com_github_checkstyle_java' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1552542575 +0800"
    Loading: 0 packages loaded
    DEBUG: Rule 'com_github_nelhage_rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556014830 +0800"
    INFO: SHA256 (https://github.com/jovany-wang/prometheus-cpp/archive/master.zip) = d0c773da8af3db99c543dd0413f4427d835170eddfd517bfeba104236a8d2c07
    DEBUG: Rule 'com_github_jupp0r_prometheus_cpp' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "d0c773da8af3db99c543dd0413f4427d835170eddfd517bfeba104236a8d2c07"
    Loading: 0 packages loaded
        currently loading:
    INFO: SHA256 (https://github.com/google/bazel-common/archive/f1115e0f777f08c3cdb115526c4e663005bec69b.zip) = 1e05a4791cc3470d3ecf7edb556f796b1d340359f1c4d293f175d4d0946cf84c
    DEBUG: Rule 'bazel_common' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "1e05a4791cc3470d3ecf7edb556f796b1d340359f1c4d293f175d4d0946cf84c"
    INFO: SHA256 (https://github.com/bazelbuild/bazel-skylib/archive/0.6.0.tar.gz) = eb5c57e4c12e68c0c20bc774bfbc60a568e800d025557bc4ea022c6479acc867
    DEBUG: Rule 'bazel_skylib' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "eb5c57e4c12e68c0c20bc774bfbc60a568e800d025557bc4ea022c6479acc867"
    Loading: 0 packages loaded
        currently loading:
    DEBUG: Rule 'com_github_google_flatbuffers' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1547755012 -0800"
    Analyzing: target //:ray_pkg (1 packages loaded, 0 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    Analyzing: target //:ray_pkg (3 packages loaded, 16 targets configured)
    DEBUG: Rule 'plasma' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1553452258 +0100"
    Analyzing: target //:ray_pkg (12 packages loaded, 132 targets configured)
    Analyzing: target //:ray_pkg (14 packages loaded, 149 targets configured)
    DEBUG: Rule 'com_github_google_glog' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1550458164 +0900"
    Analyzing: target //:ray_pkg (15 packages loaded, 291 targets configured)
    INFO: SHA256 (https://github.com/census-instrumentation/opencensus-cpp/archive/v0.3.0.zip) = e95cadb1941e1a0a698bf5c539a660ef57bc6a1ee2c0f3f76b23707a8dd6d229
    DEBUG: Rule 'io_opencensus_cpp' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e95cadb1941e1a0a698bf5c539a660ef57bc6a1ee2c0f3f76b23707a8dd6d229"
    DEBUG: Rule 'com_github_gflags_gflags' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "e171aa2d15ed9eb17054558e0b3a6a413bb01067", shallow_since = "1541971260 +0000" and dropping ["tag"]
    Analyzing: target //:ray_pkg (16 packages loaded, 342 targets configured)
    DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1552083078 -0500"
    ERROR: /developer/.cache/bazel/_bazel_root/81c22130781720e979ae3a33cb6d9ae2/external/io_opencensus_cpp/opencensus/copts.bzl:24:1: file '@com_google_absl//absl:copts/configure_copts.bzl' does not contain symbol 'GCC_FLAGS'
    ERROR: /developer/.cache/bazel/_bazel_root/81c22130781720e979ae3a33cb6d9ae2/external/io_opencensus_cpp/opencensus/copts.bzl:37:35: Traceback (most recent call last):
    	File "/developer/.cache/bazel/_bazel_root/81c22130781720e979ae3a33cb6d9ae2/external/io_opencensus_cpp/opencensus/copts.bzl", line 36
    		select({"//opencensus:llvm_compiler": (...)})
    	File "/developer/.cache/bazel/_bazel_root/81c22130781720e979ae3a33cb6d9ae2/external/io_opencensus_cpp/opencensus/copts.bzl", line 37, in select
    		LLVM_FLAGS
    global variable 'LLVM_FLAGS' is referenced before assignment.
    ERROR: /developer/.cache/bazel/_bazel_root/81c22130781720e979ae3a33cb6d9ae2/external/io_opencensus_cpp/opencensus/copts.bzl:42:14: global variable 'DEFAULT_COPTS' is referenced before assignment.
    INFO: An error occurred during the fetch of repository 'cython'
    INFO: Call stack for the definition of repository 'cython':
     - /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/bazel/ray_deps_setup.bzl:74:5
     - /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/WORKSPACE:5:1
    INFO: An error occurred during the fetch of repository 'com_google_googletest'
    INFO: Call stack for the definition of repository 'com_google_googletest':
     - /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/bazel/ray_deps_setup.bzl:48:5
     - /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/WORKSPACE:5:1
    Analyzing: target //:ray_pkg (16 packages loaded, 342 targets configured)
    Analyzing: target //:ray_pkg (16 packages loaded, 342 targets configured)
    ERROR: /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/BUILD.bazel:70:1: error loading package '@io_opencensus_cpp//opencensus/stats': Extension file 'opencensus/copts.bzl' has errors and referenced by '//:raylet_lib'
    ERROR: Analysis of target '//:ray_pkg' failed; build aborted: error loading package '@io_opencensus_cpp//opencensus/stats': Extension file 'opencensus/copts.bzl' has errors
    INFO: Elapsed time: 48.588s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (16 packages loaded, 342 targets configured)
    FAILED: Build did NOT complete successfully (16 packages loaded, 342 targets configured)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/setup.py", line 183, in <module>
        license="Apache 2.0")
      File "/home/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/setup.py", line 74, in run
        subprocess.check_call(command)
      File "/home/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/anaconda3/bin/python']' returned non-zero exit status 1.
  Rolling back uninstall of ray
  Moving to /home/anaconda3/bin/ray
   from /tmp/pip-uninstall-2ea_pzso/ray
  Moving to /home/anaconda3/bin/rllib
   from /tmp/pip-uninstall-2ea_pzso/rllib
  Moving to /home/anaconda3/bin/tune
   from /tmp/pip-uninstall-2ea_pzso/tune
  Moving to /home/anaconda3/lib/python3.7/site-packages/benchmarks/
   from /home/anaconda3/lib/python3.7/site-packages/~enchmarks
  Moving to /home/anaconda3/lib/python3.7/site-packages/ray-0.7.0.dist-info/
   from /home/anaconda3/lib/python3.7/site-packages/~ay-0.7.0.dist-info
  Moving to /home/anaconda3/lib/python3.7/site-packages/ray/
   from /home/anaconda3/lib/python3.7/site-packages/~ay
  Replacing /home/anaconda3/bin/ray from /tmp/pip-uninstall-2ea_pzso/ray
  Replacing /home/anaconda3/bin/rllib from /tmp/pip-uninstall-2ea_pzso/rllib
  Replacing /home/anaconda3/bin/tune from /tmp/pip-uninstall-2ea_pzso/tune
  Replacing /home/anaconda3/lib/python3.7/site-packages/benchmarks/ from /home/anaconda3/lib/python3.7/site-packages/~enchmarks
  Replacing /home/anaconda3/lib/python3.7/site-packages/ray-0.7.0.dist-info/ from /home/anaconda3/lib/python3.7/site-packages/~ay-0.7.0.dist-info
  Replacing /home/anaconda3/lib/python3.7/site-packages/ray/ from /home/anaconda3/lib/python3.7/site-packages/~ay
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-26o39y_z'
ERROR: Command "/home/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/
Exception information:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 910, in install
    install_options, global_options, prefix=prefix,
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 766, in install_editable
    cwd=self.setup_py_dir,
  File "/home/anaconda3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/anaconda3/bin/python -c 'import setuptools, tokenize;__file__='"'"'/developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /developer/Downloads/REINFORCEMENT_LEARNING_2019/ray/python/`

**Comment by stellaxu** [comment]
Hi, all, I have solved this issue by setting:
TEST_TMPDIR=/tmp/bazel before cloning the repository.
The installation of Ray succeeds using the clone the repository and pip install -e. verbose method.  Even when

Since by default, the bazel's output base is on NFS. Although it is a warning, it still make the installation fails.

Hope it works for both the potential users as well as the Ray developers.

**Comment by kiddyboots216** [comment]
@stellaxu I'm having the same problem where I can't install Bazel because of NFS, but just running "TEST_TMPDIR=/tmp/bazel" doesn't fix it, is there a second argument?
