### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] when i run ray.ini() it occurred the error FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/stat'

### ISSUE THREAD

**Issue by NJIER** [ray-project/ray#47524]
### What happened + What you expected to happen

when i run ray.ini() it occurs the error FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/stat'. More error related is "  with _open(fname) as f:
  File "/home/nawenjie/anaconda3/envs/as1/lib/python3.9/site-packages/ray/thirdparty_files/psutil/_common.py", line 799, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/stat'"
 I have run the code before and no error. Next time it occurred. There is no file named  stat in /proc/1/.  I know it is system file but i do nothing with /proc/1/ .

### Versions / Dependencies

_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
_tflow_select             2.3.0                       mkl  
abseil-cpp                20211102.0           hd4dd3e8_0  
absl-py                   2.1.0            py39h06a4308_0  
aiohappyeyeballs          2.4.0            py39h06a4308_0  
aiohttp                   3.10.5           py39h5eee18b_0  
aiosignal                 1.3.1                    pypi_0    pypi
astunparse                1.6.3                      py_0  
async-timeout             4.0.3            py39h06a4308_0  
attrs                     24.2.0                   pypi_0    pypi
blas                      1.0                    openblas  
blinker                   1.6.2            py39h06a4308_0  
brotli                    1.0.9                h5eee18b_8  
brotli-bin                1.0.9                h5eee18b_8  
brotli-python             1.0.9            py39h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.7.2             h06a4308_0  
cachetools                5.3.3            py39h06a4308_0  
cairo                     1.16.0               hb05425b_5  
certifi                   2024.8.30        py39h06a4308_0  
cffi                      1.16.0           py39h5eee18b_1  
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7            py39h06a4308_0  
contourpy                 1.2.0            py39hdb19cb5_0  
cryptography              41.0.3           py39h130f0dd_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9c0eb46_1  
dbus                      1.13.18              hb2f20db_0  
eigen                     3.4.0                hdb19cb5_0  
expat                     2.6.3                h6a678d5_0  
ffmpeg                    4.2.2                h20bf706_0  
filelock                  3.15.4                   pypi_0    pypi
flatbuffers               24.3.25              h6a678d5_0  
fontconfig                2.14.1               h4c34cd2_2  
fonttools                 4.51.0           py39h5eee18b_0  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
gast                      0.4.0              pyhd3eb1b0_0  
giflib                    5.2.1                h5eee18b_3  
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.29.0           py39h06a4308_0  
google-auth-oauthlib      0.5.2            py39h06a4308_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
graphite2                 1.3.14               h295c915_1  
grpc-cpp                  1.48.2               h5bf31a4_0  
grpcio                    1.48.2           py39h5bf31a4_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
h5py                      3.11.0           py39hbe37b52_0  
harfbuzz                  4.3.0                hf52aaf7_1  
hdf5                      1.12.1               h70be1eb_2  
icu                       58.2                 he6710b0_3  
idna                      3.8                      pypi_0    pypi
imageio                   2.33.1           py39h06a4308_0  
importlib-metadata        7.0.1            py39h06a4308_0  
importlib_resources       6.4.0            py39h06a4308_0  
intel-openmp              2023.1.0         hdb19cb5_46306  
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2            py39h06a4308_0  
jpeg                      9e                   h5eee18b_3  
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
keras                     2.12.0           py39h06a4308_0  
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.4.4            py39h6a678d5_0  
krb5                      1.20.1               h568e23c_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libbrotlicommon           1.0.9                h5eee18b_8  
libbrotlidec              1.0.9                h5eee18b_8  
libbrotlienc              1.0.9                h5eee18b_8  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                ha637b67_0  
libcurl                   8.2.1                h91b91d3_0  
libdeflate                1.17                 h5eee18b_1  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               h8f2d780_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libglib                   2.78.4               hdc74915_0  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libllvm14                 14.0.6               hdb19cb5_3  
libnghttp2                1.52.0               ha637b67_1  
libopenblas               0.3.21               h043d6bf_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.15                h37d81fd_1  
libprotobuf               3.20.3               he621ea3_0  
libssh2                   1.10.0               h37d81fd_2  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.3.2                h11a3e52_0  
libwebp-base              1.3.2                h5eee18b_0  
libxcb                    1.15                 h7f8727e_0  
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2            py39h06a4308_0  
matplotlib-base           3.9.2            py39hbfdbfaf_0  
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0            py39h5eee18b_1  
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.8                    pypi_0    pypi
multidict                 6.0.4            py39h5eee18b_0  
mysql                     5.7.24               he378463_2  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1                    pypi_0    pypi
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numpy                     2.0.2                    pypi_0    pypi
numpy-base                1.23.5           py39h1e6e340_0  
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
oauthlib                  3.2.2            py39h06a4308_0  
opencv                    4.6.0            py39ha16400d_5  
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.5.2                he7f1fd0_0  
openssl                   1.1.1w               h7f8727e_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 24.1             py39h06a4308_0  
pcre2                     10.42                hebb0a14_1  
pillow                    10.4.0           py39h5eee18b_0  
pip                       24.2             py39h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
ply                       3.11             py39h06a4308_0  
protobuf                  5.28.0                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pybind11-abi              4                    hd3eb1b0_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.8.0            py39h06a4308_0  
pyopenssl                 23.2.0           py39h06a4308_0  
pyparsing                 3.1.2            py39h06a4308_0  
pyqt                      5.15.10          py39h6a678d5_0  
pyqt5-sip                 12.13.0          py39h5eee18b_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.18               h7a1cb2a_0  
python-dateutil           2.9.0post0       py39h06a4308_2  
python-flatbuffers        24.3.25          py39h06a4308_0  
pyyaml                    6.0.2                    pypi_0    pypi
qt-main                   5.15.2               h5b8104b_9  
qt-webengine              5.15.9               h9ab4d14_7  
qtwebkit                  5.212                h3fafdc1_5  
ray                       2.35.0                   pypi_0    pypi
re2                       2022.04.01           h295c915_0  
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3           py39h06a4308_0  
requests-oauthlib         2.0.0            py39h06a4308_0  
rpds-py                   0.20.0                   pypi_0    pypi
rsa                       4.7.2              pyhd3eb1b0_1  
scikit-fmm                2024.5.29                pypi_0    pypi
scikit-learn              1.5.1            py39h1128e8f_0  
scipy                     1.13.1           py39heeff2f4_0  
setuptools                72.1.0           py39h06a4308_0  
sip                       6.7.12           py39h6a678d5_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.2.1                h6a678d5_0  
sqlite                    3.45.3               h5eee18b_0  
sympy                     1.13.2                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tensorboard               1.10.0                   pypi_0    pypi
tensorboard-data-server   0.7.0            py39h52d8a92_1  
tensorboard-plugin-wit    1.8.1            py39h06a4308_0  
tensorflow                2.12.0          mkl_py39h5ea9445_0  
tensorflow-base           2.12.0          mkl_py39he5f8e37_0  
tensorflow-estimator      2.12.0           py39h06a4308_0  
termcolor                 2.1.0            py39h06a4308_0  
threadpoolctl             3.5.0            py39h2f386ee_0  
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1            py39h06a4308_0  
torch                     2.4.1                    pypi_0    pypi
torchaudio                2.4.1                    pypi_0    pypi
torchvision               0.19.1                   pypi_0    pypi
tornado                   6.4.1            py39h5eee18b_0  
triton                    3.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0           py39h06a4308_0  
tzdata                    2024a                h04d1e81_0  
unicodedata2              15.1.0           py39h5eee18b_0  
urllib3                   2.2.2            py39h06a4308_0  
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0  
wrapt                     1.14.1           py39h5eee18b_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.4.6                h5eee18b_1  
yarl                      1.9.3            py39h5eee18b_0  
zipp                      3.17.0           py39h06a4308_0  
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2 

### Reproduction script

import os, ray, torch, random
import numpy as np
import tensorflow as tf
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions import Categorical
from torch.utils.tensorboard import SummaryWriter
from ppo_policy import Actor, Critic
from runner import RLRunner
from parameter import *

ray.init()
def find_last_step(event_file):
    last_step = None
    for event in tf.compat.v1.train.summary_iterator(event_file):
        if event.HasField('summary'):
            for value in event.summary.value:
                if event.step > (last_step if last_step is not None else -1):
                    last_step = event.step
    return last_step

def writeToTensorBoard(writer, tensorboardData, curr_episode):
    # each row in tensorboardData represents an episode
    # each column is a specific metric

    tensorboardData = np.array(tensorboardData)
    tensorboardData = list(np.nanmean(tensorboardData, axis=0))
    reward, actorLoss, criticLoss, entropy, travel_dist, success_rate, explored_rate = tensorboardData

    writer.add_scalar(tag='Perf/Reward', scalar_value=reward, global_step=curr_episode)
    writer.add_scalar(tag='Losses/Actor Loss', scalar_value=actorLoss, global_step=curr_episode)
    writer.add_scalar(tag='Losses/Critic Loss', scalar_value=criticLoss, global_step=curr_episode)
    writer.add_scalar(tag='Losses/Entropy', scalar_value=entropy, global_step=curr_episode)
    writer.add_scalar(tag='Perf/Travel Distance', scalar_value=travel_dist, global_step=curr_episode)
    writer.add_scalar(tag='Perf/Explored Rate', scalar_value=explored_rate, global_step=curr_episode)
    writer.add_scalar(tag='Perf/Success Rate', scalar_value=success_rate, global_step=curr_episode)

def main():
    log_reward_dir = log_dir + 'reward/'
    if not os.path.exists(log_reward_dir):
        os.makedirs(log_reward_dir)
    latest_event_files = [os.path.join(log_reward_dir, f) for f in os.listdir(log_reward_dir) if f.startswith('events.out.tfevents')] 

    if latest_event_files:
        latest_event_file = max(latest_event_files, key=os.path.getmtime)
        last_step = find_last_step(latest_event_file)
        if last_step is None:
            print("No steps found in the event file.")
            last_step = 0
    else:  
        print("No .tfevents files found in the directory.")
        last_step = 0
    writer = SummaryWriter(log_dir=log_reward_dir, comment='_scalars', filename_suffix = 'reward')

    # use GPU/CPU for driver/worker
    device = torch.device('cuda') if USE_GPU_GLOBAL else torch.device('cpu')
    local_device = torch.device('cuda') if USE_GPU else torch.device('cpu')
    
    
    # initialize neural networks
    actor_net = Actor(FCL_DIM, RESNET_LAYERS, IN_CHANNEL).to(device)
    critic_net = Critic(FCL_DIM, RESNET_LAYERS, IN_CHANNEL).to(device)

    # initialize optimizers
    actor_optimizer = optim.Adam(actor_net.parameters(), lr=LR, eps=EPS)
    critic_optimizer = optim.Adam(critic_net.parameters(), lr=LR, eps=EPS)

    curr_episode = 0

    # load model and optimizer trained before
    if os.path.exists(model_path + '/checkpoint.pth'):
        checkpoint = torch.load(model_path + '/checkpoint.pth', map_location=device)
        try:
            actor_net.load_state_dict(checkpoint['actor_model'])
            critic_net.load_state_dict(checkpoint['critic_model'])

            actor_optimizer.load_state_dict(checkpoint['actor_optimizer'])
            critic_optimizer.load_state_dict(checkpoint['critic_optimizer'])
            curr_episode = checkpoint['episode']
            print('Loading Model...')
        except:
            print("Error in Loading Model...")

    # get global networks weights
    weights_set = []
    if device != local_device:
        actor_weights = actor_net.to(local_device).state_dict()
        critic_weights = critic_net.to(local_device).state_dict()
        actor_net.to(device)
        critic_net.to(device)
    else:
        actor_weights = actor_net.to(local_device).state_dict()
        critic_weights = critic_net.to(local_device).state_dict()
    weights_set.append(actor_weights)
    weights_set.append(critic_weights)

    # distributed training if multiple GPUs available
    dp_actor_net = nn.DataParallel(actor_net)
    dp_critic_net = nn.DataParallel(critic_net)

    # launch meta agents
    meta_agents = [RLRunner.remote(i) for i in range(NUM_META_AGENT)]

    # launch the first job on each runner
    job_list = []
    for i, meta_agent in enumerate(meta_agents):
        curr_episode += 1
        job_list.append(meta_agent.job.remote(weights_set, curr_episode))
    
    # initialize metric collector
    metric_name = ['travel_dist', 'success_rate', 'explored_rate']
    training_data = []
    perf_metrics = {}
    for n in metric_name:
        perf_metrics[n] = []

    # initialize training replay buffer
    experience_buffer = []
    for i in range(8):
        experience_buffer.append([])
    
    # collect data from worker and do training
    try:
        while True:
            # wait for any job to be completed
            done_id, job_list = ray.wait(job_list)
            # get the results
            done_jobs = ray.get(done_id)
            
            # save experience and metric
            for job in done_jobs:
                job_results, metrics, info = job
                for i in range(len(experience_buffer)):
                    experience_buffer[i] += job_results[i]

            # launch new task
            curr_episode += 1
            job_list.append(meta_agents[info['id']].job.remote(weights_set, curr_episode))
            
            # start training
            if curr_episode % 1 == 0 and len(experience_buffer[0]) >= MINIMUM_BUFFER_SIZE:
                print("training")

                # keep the replay buffer size
                if len(experience_buffer[0]) >= REPLAY_SIZE:
                    for i in range(len(experience_buffer)):
                        experience_buffer[i] = experience_buffer[i][-REPLAY_SIZE:]

                indices = range(len(experience_buffer[0]))

                # training for n times each step
                for j in range(8):
                    # randomly sample a batch data
                    sample_indices = random.sample(indices, BATCH_SIZE)
                    rollouts = []
                    for i in range(len(experience_buffer)):
                        rollouts.append([experience_buffer[i][index] for index in sample_indices])

                    state_batch = torch.tensor(np.array(rollouts[0]), dtype=torch.float).to(device)
                    action_batch = torch.tensor(np.array(rollouts[1]), dtype=torch.int).to(device)
                    reward_batch = torch.tensor(np.array(rollouts[2]), dtype=torch.float).to(device)
                    state_next_batch = torch.tensor(np.array(rollouts[3]), dtype=torch.float).to(device)
                    finish_batch = torch.tensor(np.array(rollouts[4]), dtype=torch.float).to(device)
                    done_batch = torch.tensor(np.array(rollouts[5]), dtype=torch.float).to(device)
                    logprob_a_batch = torch.tensor(np.array(rollouts[6]), dtype=torch.float).to(device)
                    size_batch = torch.tensor(np.array(rollouts[7]), dtype=torch.int).to(device).squeeze(dim=1)

                    # PPO
                    adv = []
                    gae = 0
                    with torch.no_grad():
                        vs = dp_critic_net(state_batch)
                        vs_ = dp_critic_net(state_next_batch)

                        deltas = reward_batch + PPO_GAMMA * vs_ * (1.0 - finish_batch) - vs
                        for dlt, mask in zip(reversed(deltas.cpu().flatten().numpy()), reversed(done_batch.cpu().flatten().numpy())):
                            gae = dlt + PPO_GAMMA * PPO_LAMBD * gae * (1 - mask)
                            adv.insert(0, gae)
                        adv = torch.tensor(adv).float().to(device)
                        td_target = adv + vs
                        if USE_ADV_NORM:
                            adv = (adv - adv.mean()) / ((adv.std()+1e-5))

                    # distribution_h, distribution_w= dp_actor_net(state_batch, size_batch)
                    probs_h, probs_w= dp_actor_net(state_batch, size_batch)
                    distribution_h = Categorical(probs_h)
                    distribution_w = Categorical(probs_w)
                    dist_entropy = distribution_h.entropy() + distribution_w.entropy()
                    logprob_a_now_h = distribution_h.log_prob(action_batch[:,0].unsqueeze(1))
                    logprob_a_now_w = distribution_w.log_prob(action_batch[:,1].unsqueeze(1))
                    logprob_a_now = torch.cat([logprob_a_now_h,logprob_a_now_w],dim=1).sum(dim=1).squeeze()
                    
                    ratio = torch.exp(logprob_a_now - logprob_a_batch.sum(dim=1))  # a/b == exp(log(a)-log(b))
                    surr1 = ratio * adv
                    surr2 = torch.clamp(ratio, 1 - PPO_CLIP_RATE, 1 + PPO_CLIP_RATE) * adv
                    a_loss = -torch.min(surr1, surr2) - ENTROPY_COEF * dist_entropy
                    c_loss = F.mse_loss(dp_critic_net(state_batch), td_target)

                    actor_optimizer.zero_grad()
                    a_loss.mean().backward()
                    actor_optimizer.step()

                    '''update the critic'''
                    critic_optimizer.zero_grad()
                    c_loss.backward()
                    critic_optimizer.step()
                    
                    a_loss_mean = a_loss.mean().cpu().detach().numpy()
                    c_loss_mean = c_loss.cpu().detach().numpy()
                    entropy_mean = dist_entropy.mean().cpu().detach().numpy()

                # data record to be written in tensorboard
                perf_data = []
                for n in metric_name:
                    perf_data.append(np.nanmean(perf_metrics[n]))
                data = [reward_batch.mean().item(), a_loss_mean.mean().item(), c_loss_mean.item(), entropy_mean.item(), *perf_data]
                training_data.append(data)

            # write record to tensorboard
            if len(training_data) >= SUMMARY_WINDOW:
                writeToTensorBoard(writer, training_data, curr_episode)
                training_data = []
                perf_metrics = {}
                for n in metric_name:
                    perf_metrics[n] = []

            # get the updated global weights
            weights_set = []
            if device != local_device:
                actor_weights = actor_net.to(local_device).state_dict()
                critic_weights = critic_net.to(local_device).state_dict()
                actor_net.to(device)
                critic_net.to(device)
            else:
                actor_weights = actor_net.to(local_device).state_dict()
                critic_weights = critic_net.to(local_device).state_dict()
            weights_set.append(actor_weights)
            weights_set.append(critic_weights)

            # save the model
            if curr_episode % SAVE_MODEL_EPISODE == 0:
                print('Saving model', end='\n')
                if not os.path.exists(model_path):
                    os.makedirs(model_path)
                checkpoint = {"actor_model": actor_net.state_dict(),
                              "critic_model": critic_net.state_dict(),
                              "actor_optimizer": actor_optimizer.state_dict(),
                              "critic_optimizer": critic_optimizer.state_dict(),
                              "episode": curr_episode,
                              }
                path_checkpoint = model_path + "/checkpoint.pth"
                torch.save(checkpoint, path_checkpoint)
                print('Saved model', end='\n')
                    

    except KeyboardInterrupt:
        print("CTRL_C pressed. Killing remote workers")
        for a in meta_agents:
            ray.kill(a)

if __name__ == "__main__":
    main()

### Issue Severity

High: It blocks me from completing my task.

**Comment by afishspring** [comment]
Maybe "import ray" should be imported before all packages?
Like 
- 1 line "import ray"
- 2 line "import os, torch, random ..."
instead of "import os, ray, torch, random ..."
I'm not sure, but it somehow works in my project.

What's your solution, please?
