### ISSUE TITLE
[RLlib] AddColumnsFromEpisodesToTrainBatch assumes episode length >= 1

### ISSUE THREAD

**Issue by Mark2000** [ray-project/ray#47542]
### What happened + What you expected to happen

See #46721 .

### Versions / Dependencies

Ray 2.32.0, Python 3.10.11

### Reproduction script

See #46721 .

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by simonsays1980** [comment]
PR is merged
