### ISSUE TITLE
[tune] Add ability to resume TERMINATED/ERRORED trials

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4755]
This seems to be a common request - the larger problem here is that the TrialRunner is not its own long-running interactive process.

Having a service that users can submit, terminate, change the state of, and resume trials would be nice.

Comments welcome...

**Comment by ericl** [comment]
What happens if you `--resume` with a greater number of max_failures in the config?

**Comment by krfricke** [comment]
Solved via #10060

**Comment by fostiropoulos** [comment]
@krfricke does not address the issue of when a trial has been terminated and want to continue training from latest checkpoint for more epochs or different hyper-parameters. Any thoughts on this?

**Comment by davidhozic** [comment]
Doesn't #10060 solve only errored trials. What if I want to keep training the finished ones for 50M more steps?
