### ISSUE TITLE
Add RAM, CPU and GPU usage tracking

### ISSUE THREAD

**Issue by dulex123** [ray-project/ray#4760]
I think we should add suppport for tracking gpu/cpu/ram/vram usage in tensorboard. It can be done with gputil and psuti with tracking of usage every 1-2 secs. By default should be off. 

Thoughts on this appreciated.

**Comment by dulex123** [comment]
Does anybody know a way of writing notes to tensorboard? One thing it might be useful is for total ram/vram/num_cores availability. Because if we track percentage utilization 1-100% it will be ambiguous if we run on different PCs/instances.

**Comment by richardliaw** [comment]
This would probably instead go to the Ray dashboard? cc @robertnishihara @pcmoritz @pschafhalter

**Comment by dulex123** [comment]
@richardliaw Is there a way to see historical and not only real-time data with dashboard?

**Comment by richardliaw** [comment]
I think you'll have to add that functionality to dashboard separately...

Alternatively, as a preliminary first cut, if you want all of these stats colocated on TensorBoard, it could make sense to introduce a helper function that will return a dict of current GPU/CPU/Mem usage. Users can then optionally populate their result dict with the usage stats.

What do you think?

**Comment by dulex123** [comment]
@richardliaw sorry for late response, I wrote some code here not sure where it should be put in the ray code thou.. https://gist.github.com/dulex123/1f6f0cde45bd35aa67351803acf466f5

**Comment by richardliaw** [comment]
OK, I see- this could actually go in `logger.py`, though it will have to wait until a couple PRs land into master.

**Comment by richardliaw** [comment]
Actually looks like this is probably very useful; do you know what is the overhead for running these things? 

One possibility is to put it in a private method of Trainable.

**Comment by dulex123** [comment]
I have also implemented it in logger.py but not sure if thats the right abstraction, overhead as in miliseconds to execute?

**Comment by richardliaw** [comment]
Yeah, ms to execute

**Comment by dulex123** [comment]
Run takes between 0.02s and 0.055s. While get_data is 3.7670135498046875e-05s

**Comment by richardliaw** [comment]
OK let's add this as a helper method of Trainable for now, have it run every 5 seconds, and flag it off as experimental for now?

**Comment by dulex123** [comment]
@richardliaw Added a WIP PR. What kind of helper method did you have in mind? How do I "flag it off as experimental"?

Thanks!
