### ISSUE TITLE
worker aways dead and reconstruct  but the global_state has all the workers

### ISSUE THREAD

**Issue by xiefu5hh** [ray-project/ray#4761]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)pip:
- **Ray version**:0.6.6
- **Python version**:3.7.0
- **Exact command to reproduce**:

### Describe the problem
1、init ray in a small cluster 20
2、submit 10000 remote task in a time，each task is about  to run 3 seconds
3、 i see the worker.out , each worker aways run 1-5 task，and it will be dead,
the new worker rebuild
4、 the raylet.out print all the workers no matter the worker is dead
5、ray.global_state.works() print  all the workers no matter the worker is dead

**Comment by xiefu5hh** [comment]
now the worker in globalstate may be increase to 10 milion

**Comment by xiefu5hh** [comment]
reached_max_executions = (self.function_actor_manager.get_task_counter(
            driver_id, function_descriptor) == execution_info.max_calls)
        if reached_max_executions:
            self.raylet_client.disconnect()
            sys.exit(0)

because  reach the max worker?

**Comment by xiefu5hh** [comment]
i find it is the max_times  at the remote conf
@remote(maxtimes=5)
problem solves,but  i thing there may has some problem with this param .

**Comment by robertnishihara** [comment]
You're right, thanks for reporting this. We never garbage collect the contents of `ray.global_state.workers()`. We should probably just get rid of it as it is not used anywhere.
