### ISSUE TITLE
[Core] Add an "IsHeadNode" label to hardware utilization metrics 

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#47632]
### Description

We sometimes recommend that users disable compute on their head node so the ray cluster can survive when workload is heavy.

This can make aggregating hardware metrics difficult because if we include head node CPU utilization, the results are skewed. (Head node CPU usage is expected to be low and it will skew the results).

### Use case

Create a graph to show average CPU usage across cluster. 
Create a graph that shows number of unused CPUs in cluster.

**Comment by alanwguo** [comment]
As part of this, we should also update the Grafana dashboards to separate out head node utilization

**Comment by justin-miller-zefr** [comment]
I'd like to give this one a try if that's alright. 

I imagine in terms of determining the head node something like this could be used: https://github.com/ray-project/ray/blob/master/python/ray/serve/_private/utils.py#L427 along with https://github.com/ray-project/ray/blob/master/python/ray/_private/state.py#L888 to determine if the current node is the head node? If it's the head node then the label "IsHeadNode" could be applied to hardware utilization metrics, but I'm having a hard time figuring out where those are set up.

**Comment by mimiliaogo** [comment]
There should already be a column in the [protobuf message](https://github.com/ray-project/ray/blob/c2d9ca5769ce3c6b882d25a44abd06c03ab22012/src/ray/protobuf/gcs.proto#L367) that indicates whether a node is a head node. You can retrieve this information by calling [get_all_node_info()](https://github.com/ray-project/ray/blob/c2d9ca5769ce3c6b882d25a44abd06c03ab22012/python/ray/util/state/state_manager.py#L361).
@alanwguo not sure if this is what you want?

**Comment by alanwguo** [comment]
fixed by https://github.com/ray-project/ray/pull/47872

**Comment by justin-miller-zefr** [comment]
Ah ok.
