### ISSUE TITLE
[Core] Does default package really require memray a memory profiler? 

### ISSUE THREAD

**Issue by tleonhardt** [ray-project/ray#47651]
### Description

For reasons that are too lengthy to explain, the dependency on `memray` when installing `ray[default]` prevents me from being able to use `ray` in my environment.

To me it feels off that a memory profiler should be a hard requirement for installing `ray[default]`. 

Would there be any possibility of moving this requirement into a different optional dependency?

### Use case

I want to be able to install `ray[default]` without having to install `memray` (or any other memory profiler).

**Comment by rkooo567** [comment]
cc @jjyao 

I am pro to remove it from the default dependency. it is only used for dashboard memory profiling feature, and it could be a part of ray[observability]. And any ray[default] user, they can opt-in by downloading dependency manually.
