### ISSUE TITLE
[core][experimental] ADAG microbenchmark fails

### ISSUE THREAD

**Issue by kevin85421** [ray-project/ray#47667]
### What happened + What you expected to happen

https://github.com/ray-project/ray/pull/47564#issuecomment-2351601157

### Versions / Dependencies

https://github.com/ray-project/ray/pull/47564#issuecomment-2351601157

### Reproduction script

https://github.com/ray-project/ray/pull/47564#issuecomment-2351601157

### Issue Severity

None

**Comment by rkooo567** [comment]
fixed by https://github.com/ray-project/ray/pull/47683
