### ISSUE TITLE
[aDAG][Core] Weird exception if ref is deleted after adag teardown

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47687]
### What happened + What you expected to happen

We call ray.get on ref del, but if the dag is already teardown, it raises an weird exception

### Versions / Dependencies

master

### Reproduction script

```python3
import ray
from ray.dag import InputNode, MultiOutputNode

ray.init()

@ray.remote
class A:
    def f(self, inp):
        return 1

a = A.remote()
b = A.remote()
with InputNode() as inp:
    x = b.f.bind(inp)
    y = a.f.bind(inp)
    dag = MultiOutputNode([x,y ])
adag = dag.experimental_compile()
refs = adag.execute(1)
adag.teardown()

```

### Issue Severity

None

**Comment by ruisearch42** [comment]
Can you post the stack trace of the exception?

**Comment by AruparnaMaity** [comment]
Is this issue resolved? Or is someone working on this? @rkooo567 @stephanie-wang

**Comment by rkooo567** [comment]
@AruparnaMaity feel free to take it!

**Comment by rkooo567** [comment]
canot reproduce this anymore. I assume it is fixed
