### ISSUE TITLE
Allow fractional millisecond timeout for waits

### ISSUE THREAD

**Issue by Wapaul1** [ray-project/ray#477]
Currently the below fails.

To reproduce:

```python
import ray
import time
ray.init()
@ray.remote
def f():
  time.sleep(5)
ray.wait([f.remote()], timeout=0.1)
```

**Comment by robertnishihara** [comment]
This would be nice, but it's tricky because I don't think the underlying event loop that we're using (taken from Redis), does not support sub-millisecond timers (see https://github.com/ray-project/ray/blob/master/src/common/thirdparty/ae/ae.h#L111).

**Comment by robertnishihara** [comment]
For now this will not be supported.
