### ISSUE TITLE
[core][adag] aDAG silently errors if task bind args do not match function signature

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#47709]
### What happened + What you expected to happen

We should throw an error if a task's bind args do not match its function signature.

### Versions / Dependencies

3.0dev

### Reproduction script

```python
@ray.remote
class Actor:
  def foo(self):
    # doesn't take any args.
    return

a = Actor.remote()
with ray.dag.InputNode() as inp:
  # this line should error.
  dag = a.foo.bind(inp)
```

### Issue Severity

None

**Comment by kevin85421** [comment]
I can't reproduce this issue:

```python
import ray
from ray.dag import InputNode


@ray.remote
class Actor:
  def foo(self):
    # doesn't take any args.
    return

a = Actor.remote()
with InputNode() as inp:
  # this line should error.
  dag = a.foo.bind(inp)
compiled_dag = dag.experimental_compile()

ref = dag.execute(5)
print(ray.get(ref))
```

<img width="907" alt="image" src="https://github.com/user-attachments/assets/fb2fa903-7a4f-4480-83c0-458186cd16b5">

**Comment by rkooo567** [comment]
I think the ideal case is .bind raise an exception (because that's easiest to debug)

```
a.foo.bind(inp) requires a single input, but the function `Actor.foo` doesn't accept any argument 
```

**Comment by stephanie-wang** [comment]
Hmm @woshiyyya can you comment on your use case? I haven't tried to reproduce yet but I thought you ran into this bug earlier.

**Comment by rkooo567** [comment]
@stephanie-wang i actually already have a pr out to fix it I think

**Comment by stephanie-wang** [comment]
> @stephanie-wang i actually already have a pr out to fix it I think

Can you link to the PR and assign yourself? If not, this is a good first issue.

**Comment by rkooo567** [comment]
done!
