### ISSUE TITLE
[core][aDAG] Non-dag output cannot be an input of other dag

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#47723]
### What happened + What you expected to happen

not sure if it is intended. But we cannot pass non-dag-value to be an input of other dag. 

### Versions / Dependencies

master

### Reproduction script

```python3
import ray
ray.init()

from ray.dag import InputNode

@ray.remote
class A:
    def g(self, i):
        return 1
    
    def f(self, *a):
        print(a)


a = A.remote()
actors = [A.remote() for _ in range(4)]


with InputNode() as inp:
    activations = []
    for i, actor in enumerate(actors):
        activations.append((actor.g.bind(inp), i))
    dag = a.f.bind(*activations)
adag = dag.experimental_compile()
print(ray.get(adag.execute(1)))

```

### Issue Severity

None

**Comment by stephanie-wang** [comment]
@rkooo567 can you elaborate? I'm not sure from the example what you mean. Which line in the example shows the issue?

**Comment by rkooo567** [comment]
@stephanie-wang it looks like if we pass a tuple as an argument everything other than dag ref is ignored (in this case i, `activations.append((actor.g.bind(inp), i))`)

**Comment by stephanie-wang** [comment]
Oh got it, thanks! Hmm should we just disallow passing DAG ref inside other data structures for now? Otherwise I guess the other option is to serialize with placeholders for the DAG refs and then deserialize for each DAG invocation.

**Comment by ruisearch42** [comment]
As long as we throw an error, it should be OK

**Comment by dayshah** [comment]
https://github.com/ray-project/ray/pull/48302
Looks like @kevin85421 already merged a pr to do throw an error on this since this issue was created. Tested it works for the repo script, good to close?
