### ISSUE TITLE
Refine logs to resolve issues more easily

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#4774]
There are some pain points when we debug issues  in our practice, so I'd like to do some thing to improve experience:

1) add `INFO` log for actors when they receive `SIGTERM`. This'll help us to trace whether some one `kill`s them. (both cpp and python/java layers)

2) Separate user app logs from  Ray logs. It mixes app logs and Ray logs when users print their log messages at remote tasks. It is too hard to trace(also read the logs) once there are lots of app's logs. But currently, I haven't thought the solution of this, maybe it's a little  difficult because we should also let users print logs more naturally at remote tasks.

**Comment by robertnishihara** [comment]
1 seems like a good idea.

Regarding 2, I agree that it's important for people to be able to log naturally (not that logging could even occur in a library the user is using and the user may not have control over it).

**Comment by jovany-wang** [comment]
Regarding 2, a feasible solution is that we can print the logs of ray-workers into another log file, and at the same time,  we don't change the behavior of user's logs, so that users can print their logs naturally.

**Comment by jovany-wang** [comment]
@guoyuhong cc

**Comment by rkooo567** [comment]
It should be fixed now.
