### ISSUE TITLE
[Core] does ray support affinity scheduling for tasks or actions? 

### ISSUE THREAD

**Issue by kadisi** [ray-project/ray#47740]
### Description

Does Ray support affinity scheduling for tasks or actors, like pod affinity for k8s?

Allows a group of different tasks to run on the same node and share Object storage memory, reducing grpc transfers.

### Use case

In the ray data scenario, if there are multiple Physical operators of the ActorPoolMapOperator type, By using task affinity, objects generated by the parent Operator task can be directly consumed by tasks of the current Operator, reducing Object transfer across nodes.

**Comment by jjyao** [comment]
@kadisi You can use placement group to schedule a group of tasks on the same node.
