### ISSUE TITLE
[Observability] Ability to show timestamps in UTC 

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#47762]
### Description

A global button which will allow users to modify the timezone dates are shown. Ideally the user's setting is saved in local storage so they do not need to adjust every time.

May not be possible to adjust log line entries, but at least for some UI rendered dates we should be able to do it.

**Comment by nadongjun** [comment]
@alanwguo Hello, I wanted to check if this GitHub issue has been resolved or if work is ongoing. If it hasn't been resolved, I would like to take on this issue. Please assign me if possible. Thank you

**Comment by alanwguo** [comment]
@nadongjun , hi

This is not currently being worked on. Feel free to take it on, thanks!
