### ISSUE TITLE
[rllib] Replace result/info/config dict with dedicated classes

### ISSUE THREAD

**Issue by FedericoFontana** [ray-project/ray#4779]
### Describe the problem
This is a question about the design choice of passing config and state (e.g. callback args, trainer config) as `dict` instead of dedicated classes such as `Result`, `Info`, `Config`, `DefaultConfig`.

I find `dict` a lightweight solution which does the job, but dedicated classes would come with the following advantages:
- The user experience of setting a custom config of callback would improve by a lot (the try-and-see what keys are available would be replaced by a dedicated class instance with IDE friendly known attributes).
- methods like `PPOTrainer._validate_config` could be moved in `DefaultConfig._validate_config`, so that the responsibility of validating parameters will arguably be in a better class.
- Logic to retrieve/derive parameters (e.g. see [this](https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ppo/ppo.py#L132) if-elif-else) could be replaced by the property or method `DefaultConfig.rew_scale`.
- `with_common_config` would be replaced with the cleaner class inheritance.
- modules like [result.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/result.py) might be partially replaced by cleaner class attributes.
- easier to document.

**Comment by richardliaw** [comment]
I personally like the dict solution (at least for training results/`result.py`). I think the development/IDE friendliness is pretty fair; one option would be to have a Namespace wrapper around the config so that IDEs can function better?

cc @ericl

**Comment by ericl** [comment]
I think a namespace wrapper (i.e., namedtuple) is reasonable, though requiring a class import can also make things harder to use compared to a dictionary.
