### ISSUE TITLE
[Ray component: Core] Runtime Envs should support package installation with uv

### ISSUE THREAD

**Issue by colinjc** [ray-project/ray#47819]
### Description

[uv](https://docs.astral.sh/uv/) is a vastly faster at installing Python packages than Conda and Pip, so Ray should enable using it when defining runtime envs. 

uv has two interfaces, which would be nice to support separately - 

The `uv pip` interface is nearly drop-in compatible with pip with the exception of some outlier packages like `jax[tpu]`, and would be nice to have as an option. 

The `uv sync` interface is nicer, but would only really work by passing a pyproject.toml in as the argument much like runtime env's conda argument accepts a environment yaml path. 

### Use case

Runtime env creation now is quite slow. Having uv support would really improve the ux of iterating changes to a runtime env.

**Comment by jjyao** [comment]
We will pick it up if there is enough demand from OSS users.

**Comment by danielgafni** [comment]
Sounds like this would be really really great to have! 

`uv` installations from are 10-100x faster in my experience (especially from cache) so should really improve UX for heavy runtime environments like torch

**Comment by dbuades** [comment]
I agree that this would be great. We have moved from `poetry` to `uv` recently and the difference is staggering.

**Comment by jjyao** [comment]
cc @dentiny

**Comment by chainlink** [comment]
We've seen a huge increase in speed with uv and would love to see it as an option in Ray

**Comment by rynewang** [comment]
Hi all, does this interface look reasonable to you?

```py
runtime_env = {"pip": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"], "pip_check": False}}
```

Note the `uv_version` field in `pip`. If it's set, we use `uv` instead of `pip`. `uv_version` and `pip_version` can not both exist.

**Comment by jjyao** [comment]
What about we completely separate pip plugin and uv plugin:

```
runtime_env = {"uv": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"], "pip_check": False}}
```

`pip_version` is invalid in uv runtime env plugin.

**Comment by dentiny** [comment]
> What about we completely separate pip plugin and uv plugin:

@jjyao I think interface wise it makes sense, but implementation wise we would have quite a few duplicate code between pip vs uv.

`uv` could be a subset of `pip`, one justification is, the command for `uv` to install packages is `pip uv install`.

**Comment by jjyao** [comment]
We can have an implementation that share code between these two plugins. 

uv doesn't use pip, it just provides a pip like interface. I feel it's cleaner to explicitly separate them and this also gives us flexibility to support uv specific options in the future.


cc @pcmoritz for API discussion.

**Comment by danielgafni** [comment]
I think it would be best if Ray did both: 

1. Use `uv` instead of `pip` with the current `{"runtime_env": {"pip": ...}}` interface. This should be enabled by default. We can make a flag to disable `uv` in this interface just in case something goes wrong. This interface won't take any `uv`-specific parameters. This would immediately improve installation times for all Ray users. 
2. Add a new `{"runtime_env": {"uv": ...}}` interface which would mostly share the same code but also will be able to take some new `uv`-specific parameters.

**Comment by dentiny** [comment]
Hi I think we have multiple available solutions, just a brief summaries:
1. `uv` has higher priority than `pip`, with no user interface changed
1.1 Option-1: we use `uv` when installed, detect whether `uv` is installed, prefer `uv` is already installed; no user side change needed
1.2 Option-2: install and use `uv` in all cases
2. Use `uv` as a subcommand for `pip`
2.1 The interface would look pretty similar to what we have for `pip` command, which looks like 
```
runtime_env = {"pip": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"], "pip_check": False}}
```
`uv` is only selected when explicitly specified.
3. Use `uv` as a new command as a counterpart of `pip`, which looks similar to how we use `pip`/`conda` nowadays
```
runtime_env = {"uv": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"]}}
```

In rollout phase, one thing we could do to reduce risk is allow fallback to `pip` when package installation via `uv` fails.

**Comment by rynewang** [comment]
I feel silently changing implementations behind `pip` is so risky. Rather it's good to make `uv` opt-in, by either a `"uv"` plugin, or a `pip.uv_version` key.

**Comment by rynewang** [comment]
And no, we don't want the behavior to depend on "if uv exists on this machine". If we want uv and it does not exist we need to fail instead of falling back to pip.

**Comment by jjyao** [comment]
@colinjc @dbuades @chainlink any feedbacks on the above API proposals?

**Comment by colinjc** [comment]
I agree that swapping pip to uv blindly is very risky. They're not as 1:1 compatible as you would think, a lot of code would break due to the stricter constraint checking.

In the Ray docs it's mentioned that `pip` installs into the existing  , while `conda` creates an isolated one. Which approach will the uv env implement?

```
runtime_env = {"uv": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"]}}
```

I would make it more explicit that this is the `uv pip` interface, in case there's interest in adding `uv sync` support later.

Or support both in the same interface? 
 
```
{"uv": 
  {"version": "==0.1.1", "pip_packages": ["tensorflow"], "pyproject": "/path/to/pyproject.toml"}
}
```

**Comment by dbuades** [comment]
> I agree that swapping pip to uv blindly is very risky. They're not as 1:1 compatible as you would think, a lot of code would break due to the stricter constraint checking.
> 
> 
> 
> In the Ray docs it's mentioned that `pip` installs into the existing  , while `conda` creates an isolated one. Which approach will the uv env implement?
> 
> 
> 
> ```
> 
> runtime_env = {"uv": {"uv_version": "==0.1.1", "packages":["tensorflow", "requests"]}}
> 
> ```
> 
> 
> 
> I would make it more explicit that this is the `uv pip` interface, in case there's interest in adding `uv sync` support later.
> 
> 
> 
> Or support both in the same interface? 
> 
>  
> 
> ```
> 
> {"uv": 
> 
>   {"version": "==0.1.1", "pip_packages": ["tensorflow"], "pyproject": "/path/to/pyproject.toml"}
> 
> }
> 
> ```

Support for installing packages with `uv sync` with the `uv.lock` file would be great, since we wouldn't need to export a `requirements.txt` anymore and we would be sure that the exact project dependencies are installed.

**Comment by dentiny** [comment]
> I would make it more explicit that this is the uv pip interface, in case there's interest in adding uv sync support later.

Sounds good.

**Comment by dentiny** [comment]
Hi community, I'm working on runtime env setup with uv;
As the first milestone, I target at existing features for `pip`;
Let me know if you have any other feature requested specifically for `uv`.

**Comment by dbuades** [comment]
> > Support for installing packages with uv sync with the uv.lock file would be great, since we wouldn't need to export a requirements.txt anymore and we would be sure that the exact project dependencies are installed.
> 
> This really sounds like it should be a build step (in CI) instead. Curious to know why would you need to swap lock files at runtime?

Sorry for the delayed response, I was playing with Ray and uv today and came back to this thread.

We already export the lock to a `requirements.txt` file in the CI. However, `uv export` doesn't add external indexes and, although there are manual workarounds to add it afterwards, it doesn't guarantee perfect compatibility. This [comment](https://github.com/astral-sh/uv/issues/7496#issuecomment-2358527763) in the uv repo explains the reasoning well.

I think the support for `uv pip `currently implemented in Ray works perfectly fine. Adding support for `uv sync` would just be a nice-to-have feature for the future.

**Comment by vladjohnson** [comment]
Please enable support for this!

**Comment by vladjohnson** [comment]
@dentiny, is the pyproject.toml a supported source for dependency installation? Thanks!
