### ISSUE TITLE
[RLlib] Custom Env with action_mask runs into error "'Tensor' object has no attribute 'pop'"

### ISSUE THREAD

**Issue by PhilippWillms** [ray-project/ray#47853]
### What happened + What you expected to happen

Hello together,

trying to run the action_masking_example under `rllib/examples/rl_modules/action_masking_rl_module.py` after commit  https://github.com/ray-project/ray/commit/c9fa0464386fe4cd79a647e67cf6a37acdf96bde
with a dummy custom environment runs into an issue. 

Would be good to understand if the root cause is lying in the RLModule class (as the error trace suggests), or it is the environment injection.

I consider severity 'medium', as this issue blocks migration to new API stack.

> 2024-09-28 19:46:39,899 INFO worker.py:1790 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
> C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\gymnasium\envs\registration.py:693: UserWarning: WARN: Overriding environment rllib-single-agent-env-v0 already in registry.
>   logger.warn(f"Overriding environment {new_spec.id} already in registry.")
> 2024-09-28 19:46:49,627 INFO trainable.py:161 -- Trainable.setup took 13.361 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
> 2024-09-28 19:46:49,645 ERROR actor_manager.py:523 -- Ray error, taking actor 1 out of service. ray::SingleAgentEnvRunner.apply() (pid=29200, ip=192.168.178.26, actor_id=632506220daacc314a89714601000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000028259DF9B10>)
>   File "python\ray\_raylet.pyx", line 1862, in ray._raylet.execute_task
>   File "python\ray\_raylet.pyx", line 1803, in ray._raylet.execute_task.function_executor
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\function_manager.py", line 696, in actor_method_executor
>     return method(__ray_actor, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
>     return method(self, *_args, **_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\utils\actor_manager.py", line 192, in apply
>     raise e
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\utils\actor_manager.py", line 181, in apply
>     return func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\execution\rollout_ops.py", line 104, in <lambda>
>     else (lambda w: (w.sample(**random_action_kwargs), w.get_metrics()))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
>     return method(self, *_args, **_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\env\single_agent_env_runner.py", line 189, in sample
>     samples = self._sample_timesteps(
>               ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
>     return method(self, *_args, **_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\env\single_agent_env_runner.py", line 298, in _sample_timesteps
>     to_env = self.module.forward_exploration(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\core\models\specs\checker.py", line 273, in wrapper
>     raise initial_exception
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\core\models\specs\checker.py", line 231, in wrapper
>     return func(self, batch, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\core\models\specs\checker.py", line 345, in wrapper
>     output_data = func(self, batch, **kwargs)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\core\rl_module\rl_module.py", line 629, in forward_exploration
>     return self._forward_exploration(batch, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\examples\rl_modules\classes\action_masking_rlm.py", line 88, in _forward_exploration
>     outs = super()._forward_exploration(batch, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\algorithms\ppo\torch\ppo_torch_rl_module.py", line 35, in _forward_exploration
>     return self._forward_inference(batch)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\examples\rl_modules\classes\action_masking_rlm.py", line 75, in _forward_inference
>     action_mask, batch = self._preprocess_batch(batch)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\rllib\examples\rl_modules\classes\action_masking_rlm.py", line 127, in _preprocess_batch
>     action_mask = batch[Columns.OBS].pop("action_mask")
>                   ^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Tensor' object has no attribute 'pop'

### Versions / Dependencies

python=3.11.9
ray nightly built
torch==2.3.1+cu118
gymnasium==0.28.1

### Reproduction script

```
from gymnasium.spaces import Box, Discrete, Dict
import gymnasium
import numpy as np
from typing import OrderedDict, Tuple
import ray
from ray.rllib.algorithms.ppo import PPOConfig
from ray.rllib.core.rl_module.rl_module import RLModuleSpec
from ray.rllib.examples.rl_modules.classes.action_masking_rlm import (
    ActionMaskingTorchRLModule,
)
from pprint import pprint


class MyEnv(gymnasium.Env):
    """Custom environment with action masking."""

    def __init__(self, *args, **kwargs):  # noqa: D107
        self.action_space = Discrete(3)
        self.observation_space = Dict(
            {
                "action_mask": Box(
                    low=0, high=1, shape=(self.action_space.n,), dtype=np.int8
                ),
                "observations": Box(
                    low=0.0,
                    high=1.0,
                    shape=(12,),
                    dtype=np.float32,
                ),
            }
        )
        self.episode_done = False
        self._action_max_helper = np.ones(self.action_space.n, dtype=np.int8)
        self.state = np.zeros((12,), dtype=np.float32)

    def step(
        self, action: int
    ) -> Tuple[OrderedDict, float, bool, bool, dict]:  # noqa: D102
        reward = 0 - action
        self.state[action*4] = 1
        self._action_max_helper[action] = 0
        if all(self._action_max_helper[k] == 0 for k in range(3)):
            self.episode_done = True
        return self._get_state_repr(), reward, self.episode_done, False, {}

    def _get_state_repr(self) -> OrderedDict:
        return {
            "action_mask": self._action_max_helper,
            "observations": self.state,
        }

    def reset(
        self, *, seed=None, options=None
    ) -> Tuple[OrderedDict, dict]:  # noqa: D102
        self.episode_done = False
        self.state = np.zeros((12,), dtype=np.float32)
        self._action_max_helper = np.ones(self.action_space.n, dtype=np.int8)
        return self._get_state_repr(), {}


if __name__ == "__main__":
    config = (
        PPOConfig()
        .api_stack(
            enable_rl_module_and_learner=True,
            enable_env_runner_and_connector_v2=True,
        )
        .environment(MyEnv)
        .rl_module(
            model_config_dict={
                "post_fcnet_hiddens": [64, 64],
                "post_fcnet_activation": "relu",
            },
            rl_module_spec=RLModuleSpec(
                module_class=ActionMaskingTorchRLModule,
            ),
        )
        .evaluation(
            evaluation_num_env_runners=1,
            evaluation_interval=1,
            # Run evaluation parallel to training to speed up the example.
            evaluation_parallel_to_training=True,
        )
    )

    algo = config.build()

    # run manual training loop and print results after each iteration
    for i in range(10):
        result = algo.train()
        print(f"Training iteration: {i+1} done")
        pprint(result)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by npit** [comment]
The issue is that the `_preprocess_batch` in `action_masking_rlm.py` destructively pops the action mask from the batch during processing at he learner connectors in `learner.py`, resulting in that field missing later during the `_forward_train` call of the module.

A workaround (ugly) might be to change the `_preprocess_batch`:

```python

    def _preprocess_batch(
        self, batch: Dict[str, TensorType], **kwargs
    ) -> Tuple[TensorType, Dict[str, TensorType]]:
        """Extracts observations and action mask from the batch

        Args:
            batch: A dictionary containing tensors (at least `Columns.OBS`)

        Returns:
            A tuple with the action mask tensor and the modified batch containing
                the original observations.
        """
        # Check observation specs for action mask and observation keys.
        self._check_batch(batch)

        # Extract the available actions tensor from the observation.
        # Fix: maintain the action mask in the batch root to have access to it
        # after connector batch preprocessing
        if isinstance(batch[Columns.OBS], (dict, OrderedDict)):
            # store the mask
            action_mask = batch[Columns.OBS].pop("action_mask")
            batch["action_mask"] = action_mask

            # Modify the batch for the `PPORLModule`'s `forward` method, i.e.
            # pass only `"obs"` into the `forward` method.
            batch[Columns.OBS] = batch[Columns.OBS].pop("observations")
        else:
            # mask has been preprocessed away from the 'obs' field, 
            # but it's available at the dict root
            action_mask = batch['action_mask']

        # Return the extracted action mask and the modified batch.
        return action_mask, batch 

```

**Comment by PhilippWillms** [comment]
@npit : Thanks for the feedback. Were you able to reproduce my issue with the latest ray release?

**Comment by npit** [comment]
I am using the release of about a month ago (2.37.0). The latest release (2.39.0) breaks my workflow in other ways and the docs have been unhelpful, so I can't reproduce it.

**Comment by PhilippWillms** [comment]
After PR #49071, the issue described initally does not occur anymore.
