### ISSUE TITLE
[Docs] Replace Python version 3.8 with 3.9 in development doc

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/ray#47854]
### Description

Currently Ray no longer supports Python 3.8, so we need to replace all "3.8" strings in https://docs.ray.io/en/latest/ray-contribute/development.html, including the wheel link.

**Comment by win5923** [comment]
HI, @MortalHappiness, 
I would like to help resolve this issue.

**Comment by faresbouzayen** [comment]
Hi @MortalHappiness,

I'd like to help with this! I'll update all references to Python 3.8 in the development doc and ensure the wheel links are correct for Python 3.9.

Thanks!

**Comment by MortalHappiness** [comment]
Hi @faresbouzayen Thank you for your interest in contributing to Ray, but since @win5923 commented first, I assigned the issue to them. Feel free to look for other good first issues!
