### ISSUE TITLE
CI test linux://rllib:examples/rl_modules/autoregressive_actions_rl_module is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#47876]
CI test **linux://rllib:examples/rl_modules/autoregressive_actions_rl_module** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6445#01924ae0-ebd8-436e-85c2-53a980899914
	- https://buildkite.com/ray-project/postmerge/builds/6445#01924a92-23ec-4a0b-aa93-39cfc6af11af
	- https://buildkite.com/ray-project/postmerge/builds/6444#019249b2-2250-4c2c-9298-b2d89e3977f7
	- https://buildkite.com/ray-project/postmerge/builds/6441#01924679-9e62-4843-95ba-f2e360f141f0
	- https://buildkite.com/ray-project/postmerge/builds/6436#019244d5-9e75-41b3-b514-d4c500d647db

DataCaseName-linux://rllib:examples/rl_modules/autoregressive_actions_rl_module-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6446#01924ba0-f5a4-429e-8fde-a5db553a6a4d

**Comment by can-anyscale** [comment]
CI test **linux://rllib:examples/rl_modules/autoregressive_actions_rl_module** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6447#01924dfd-87b8-4cfd-9642-8fbeb5601286
	- https://buildkite.com/ray-project/postmerge/builds/6445#01924ae0-ebd8-436e-85c2-53a980899914
	- https://buildkite.com/ray-project/postmerge/builds/6445#01924a92-23ec-4a0b-aa93-39cfc6af11af
	- https://buildkite.com/ray-project/postmerge/builds/6444#019249b2-2250-4c2c-9298-b2d89e3977f7
	- https://buildkite.com/ray-project/postmerge/builds/6441#01924679-9e62-4843-95ba-f2e360f141f0

DataCaseName-linux://rllib:examples/rl_modules/autoregressive_actions_rl_module-END
Managed by OSS Test Policy

**Comment by simonsays1980** [comment]
@can-anyscale I will take a look at the `autoregressive-actions` one today.
