### ISSUE TITLE
[Serve] Ray Dashboard reports HTTP 204 under Error QPS

### ISSUE THREAD

**Issue by chasleslr** [ray-project/ray#47895]
### What happened + What you expected to happen

When a deployment returns an HTTP 204, it is reported as an error in the Ray Dashboard. Specifically, these queries are reported under the "Error QPS" charts. An HTTP 2xx should not be considered as an error.

<img width="1554" alt="Screenshot 2024-10-04 at 9 07 06 AM" src="https://github.com/user-attachments/assets/0f5b0a9d-a0b9-47d9-9b35-c62e8b53ae06">

### Versions / Dependencies

macOS 14.3
Python: 3.12
ray[serve] 2.37.0

### Reproduction script

```python
from ray import serve
from fastapi import FastAPI, Response


app = FastAPI()


@serve.deployment
@serve.ingress(app)
class Deployment:
    @app.post("/")
    def post(self, text: str) -> str:
        return Response(status_code=204)


deployment_app = Deployment.bind()
```

### Issue Severity

None

**Comment by Superskyyy** [comment]
I will fix that, current check is only checked against status code 200 

```
                            is_error=status_code != "200",

```

**Comment by Superskyyy** [comment]
Shall we consider whatever doesn't start with 2xx an error? I guess its more of a business-oriented decision but this sounds a general approach that fit most.

**Comment by edoakes** [comment]
@Superskyyy yes I think characterizing `2XX` as success sounds good to me, let me review the PR
