### ISSUE TITLE
[core][compiled graphs] Add CPU-based NCCL communicator for development

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#47936]
### Description

For development and debugging, it's useful to be able to run compiled graphs that contain NCCL transport hints using a CPU-based communicator. The communicator could use the Ray object store / a Ray actor to perform p2p and collective ops.

**Comment by Bye-legumes** [comment]
What is the different between this CPU-based NCCL communicator and this mock nccl in test? Or this is not for the test but fall back to CPU/shared memory is NCCL is not avaliable?

**Comment by dengwxn** [comment]
Assigned to @tfsingh and @anyadontfly.
I think this is mainly for tests.
For starters, we should work on all-reduce first. Here's a good picture to explain [collectives](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/collectives.html).

**Comment by stephanie-wang** [comment]
Actually it would be good to make this work for non-testing purposes, so that users can debug DAGs with collective ops on CPU.

**Comment by anyadontfly** [comment]
Commenting for assignment

**Comment by rkooo567** [comment]
who's going to take this task?

**Comment by stephanie-wang** [comment]
> who's going to take this task?

@tfsingh and @anyadontfly are working on this.
