### ISSUE TITLE
[Core] Dead actors not getting deleted from dashboard with RAY_maximum_gcs_destroyed_actor_cached_count env variable

### ISSUE THREAD

**Issue by ayush42** [ray-project/ray#47930]
### What happened + What you expected to happen

I want to delete the dead nodes and dead actors from the Ray Dashboard as they keep on increasing with every job. I figured out two environment variables for this configuration - 
**RAY_maximum_gcs_dead_node_cached_count** 
and 
**RAY_maximum_gcs_destroyed_actor_cached_count**

As expected, the dead nodes are getting deleted as their number goes past RAY_maximum_gcs_dead_node_cached_count.
But dead actors are not deleted even after their number goes past RAY_maximum_gcs_destroyed_actor_cached_count

I have set both RAY_maximum_gcs_dead_node_cached_count and RAY_maximum_gcs_destroyed_actor_cached_count to 5 in my RayCluster.
In the attached screenshots, you can find the count of dead nodes and actors. Dead actors count go beyond the expected number.

<img width="710" alt="image" src="https://github.com/user-attachments/assets/819e2daf-22c8-44f1-9ac7-b74ff6833b25">
<img width="737" alt="image" src="https://github.com/user-attachments/assets/1d2dc262-b637-4bcc-ad2a-a61b1aa6db72">
<img width="974" alt="image" src="https://github.com/user-attachments/assets/de7da092-6e7f-418b-ac3b-d35ce3549fcf">

### Versions / Dependencies

Kuberay Version : 1.1.1
Ray Version : 2.36.1
Image: **rayproject/ray:2.36.1-py310-cpu**
Tensorflow : 2.15.0

### Reproduction script

PFA files ( raycluster.yaml, ray-train.py ) inside **issue-report.zip**

1. kubectl config set-context --current --namespace=test-ray-cluster
2. kubectl apply -f raycluster.yaml
3. Find head service's external-ip with 'kubectl get service'
4. Submit ray-train.py with the JobSubmissionClient 
5. After job's success, check the count of dead nodes after idleTimeoutSeconds (configured in raycluster.yaml) seconds
6. After job's success, check the count of dead actors

```python
from ray.job_submission import JobSubmissionClient

dashboard_address = "http://1.2.3.4:8265" # find correct IP from step 3 above 
client = JobSubmissionClient(address=dashboard_address)
runtime_env = {
    "working_dir": ".",
    "pip": [
        "tensorflow==2.15.0"
    ]
}
job_id = client.submit_job(
    entrypoint="python ray-train.py",
    runtime_env=runtime_env,
    submission_id="mnist-test-tf-01")
print('job_id: ', job_id)
```
[issue-report.zip](https://github.com/user-attachments/files/17292810/issue-report.zip)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jjyao** [comment]
@dayshah can you help with reproduce it?

**Comment by dayshah** [comment]
So tried it out and can reproduce it with a just a basic creating and killing actors.
```
a1 = Actor.remote()
res = a1.sleep.remote(1)

for i in range(10):
    a = Actor.remote()
    time.sleep(0.5)
    ray.kill(a)

print(ray.get(res))
```

The interesting thing though is that the state cli does respect the RAY_maximum_gcs_destroyed_actor_cached_count that I set. So if I do ray list actors it will only show as many dead actors as my env variable, but the dashboard doesn't respect that number.

**Comment by jjyao** [comment]
@dayshah The enforcement of `RAY_maximum_gcs_destroyed_actor_cached_count` should be inside GCS (gcs_actor_manager.cc), we should see why it's not enforced there.

**Comment by dayshah** [comment]
So the issue is that there's actually a separate env variable RAY_DASHBOARD_MAX_ACTORS_TO_CACHE that controls the cache on the dashboard server side. https://docs.ray.io/en/latest/ray-observability/getting-started.html#actors-view 

https://github.com/ray-project/ray/blob/master/python/ray/dashboard/modules/actor/actor_head.py#L24. It kills dead actors from its cache every time the total number of actors goes over the number.

Should we unify ```RAY_maximum_gcs_destroyed_actor_cached_count``` and ```RAY_DASHBOARD_MAX_ACTORS_TO_CACHE``` to just ```RAY_maximum_gcs_destroyed_actor_cached_count```? And if so should the default be the 1000 from the dashboard one or 100000 from the gcs code? @jjyao
