### ISSUE TITLE
[data] read_parquet doesn't work for multiple parquet files with ragged ndarrays

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#47960]
When reading from multiple parquet files, if each file contains a different-shaped ndarray for the same column. The following error will be raised: `pyarrow.lib.ArrowTypeError: Casting from 'extension<ray.data.arrow_variable_shaped_tensor<ArrowVariableShapedTensorType>>' to different extension type 'extension<ray.data.arrow_tensor<ArrowTensorType>>' not permitted. One can first cast to the storage type, then to the extension type.`.

This is because schema is [only inferred based on the first parquet file](https://github.com/ray-project/ray/blob/46a97b80575824f501649cb3d2b887e6cbd0d91f/python/ray/data/_internal/datasource/parquet_datasource.py#L233-L236). This makes all read tasks output arrow tables with the same schema, although the actual data shape is different. Then when concatenating these tables, Ray Data [doesn't know](https://github.com/ray-project/ray/blob/46a97b80575824f501649cb3d2b887e6cbd0d91f/python/ray/data/_internal/arrow_ops/transform_pyarrow.py#L127) it needs to convert the tables to `ArrowVariableShapedTensorType`.

Repro script:
```python
import numpy as np

import ray

N = 3
output_path = "/tmp/output"

ds = ray.data.range(N)


def map(row):
    id = row["id"] + 1
    row["data"] = np.zeros((id * 100, id * 100), dtype=np.int8)
    return row


ds.map(map).repartition(N).write_parquet(output_path)

ds2 = ray.data.read_parquet(output_path, override_num_blocks=1)
ds2.take_all()
```

**Comment by raulchen** [comment]
One possible fix is to ignore the inferred schema when reading the file.

**Comment by raulchen** [comment]
also the schema inference is done by Arrow not Ray Data. There seems no argument in Arrow to let it infer schema based on multiple files

**Comment by bveeramani** [comment]
@raulchen just to confirm my understanding -- `ParquetDataset.schema` infers the schema based on the first file, and that's a PyArrow implementation detail?

One concern with I have with https://github.com/ray-project/ray/pull/47961 is that it'd prevent users from explicitly specifying the schema. This feature is implicit (you specify the schema through the `**arrow_parquet_args` parameter), but we test against it, and I'm not sure if it'd break some users' code.

One alternative approach would be to try-catch the line below. If it fails, we can perform the fixed-size array type to the more geneeral variable-shaped array type. This approach is hacky, but it'd enable users to continue specifying the schema.

https://github.com/ray-project/ray/blob/e0bcdd4cffe821ac8abdddcc0dd78a8c40c5e6ab/python/ray/data/_internal/arrow_ops/transform_pyarrow.py#L303

**Comment by raulchen** [comment]
> just to confirm my understanding -- ParquetDataset.schema infers the schema based on the first file, and that's a PyArrow implementation detail?

Yes

> One concern with I have with https://github.com/ray-project/ray/pull/47961 is that it'd prevent users from explicitly specifying the schema. This feature is implicit (you specify the schema through the **arrow_parquet_args parameter), but we test against it, and I'm not sure if it'd break some users' code.

Good call out. I also noticed this issue. Planning to update the PR to keep using the schema ONLY if the schema is set by users. 

> One alternative approach would be to try-catch the line below. If it fails, we can perform the fixed-size array type to the more general variable-shaped array type. This approach is hacky, but it'd enable users to continue specifying the schema.

The issue is that this line doesn't actually raise any error. It will return a table with wrong schema instead.

**Comment by bveeramani** [comment]
> The issue is that this line doesn't actually raise any error. It will return a table with wrong schema instead.

When I ran the repro above, seemed like the line directly raised the error:

```
Traceback (most recent call last):
  File "/Users/balaji/ray/1.py", line 20, in <module>
    ds2.take_all()
...
  File "/Users/balaji/ray/python/ray/data/_internal/arrow_ops/transform_pyarrow.py", line 303, in concat
    table = pyarrow.Table.from_arrays(cols, schema=schema)
  File "pyarrow/table.pxi", line 4723, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 1562, in pyarrow.lib._sanitize_arrays
  File "pyarrow/array.pxi", line 395, in pyarrow.lib.asarray
  File "pyarrow/table.pxi", line 574, in pyarrow.lib.ChunkedArray.cast
...
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Casting from 'extension<ray.data.arrow_variable_shaped_tensor<ArrowVariableShapedTensorType>>' to different extension type 'extension<ray.data.arrow_tensor<ArrowTensorType>>' not permitted. One can first cast to the storage type, then to the extension type.
```

> Good call out. I also noticed this issue. Planning to update the PR to keep using the schema ONLY if the schema is set by users.

Hadn't thought of this. Sounds like a good solution 👍🏾

**Comment by raulchen** [comment]
> When I ran the repro above, seemed like the line directly raised the error:

Oops, I thought you were referring to the table construction place in the read tasks. 

I've already gone with the other approach, which seems cleaner. 
Will revisit this again if that approach doesn't work.

**Comment by raulchen** [comment]
@srinathk10 thanks for the comment. 
The intended fix will indeed try to merge the schema (from `ArrowTensorType` to `ArrowVariableShapedTensorType`). 
For other conflicting cases, Ray Data currently doesn't have specific logic to handle the conflict. We just defer it to PyArrow to merge the schema when concatenating multiple tables. Or users can specify the schema manually. 
We will probably want to revisit the schema merging behavior later if new issues emerge.
