### ISSUE TITLE
Error starting new cluster

### ISSUE THREAD

**Issue by jheffez** [ray-project/ray#4799]
I'm a newbie. Followed the instructions in https://ray.readthedocs.io/en/latest/autoscaling.html to start a local cluster:
`ray.init(redis_address="localhost:6379")` gives the error:
`-su: syntax error near unexpected token `redis_address="localhost:6379"'`

Running ubuntu 18.04, Python 3.6.8, Ray 0.6.6 (fresh install today pip install ray[debug] )
Updated to 0.7 dev2, same error.

**Comment by robertnishihara** [comment]
Can you post the full backtrace?

**Comment by jheffez** [comment]
After some tinkering I figured that the line needs to be run from Python, not from bash (it may be helpful to clarify that in the link above).
Thanks.
