### ISSUE TITLE
[Data] Concatenate preprocessor does not preserve order of concatenation

### ISSUE THREAD

**Issue by martinbomio** [ray-project/ray#47996]
### What happened + What you expected to happen

Looks like the `Concatenator` preserves the order of the columns in the input pandas dataframe that is passed (in this [line](https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessors/concatenator.py#L156)), which means that if the df has a different order of columns at training and serving, it will be feeding bad inputs to the model

### Versions / Dependencies

Latest ray version

### Reproduction script

```python
    concatenate = Concatenator()
    df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
    concatenate.transform_batch(df)

#     concat_out
# 0     [1, 3]
# 1     [2, 4]

     other_df = pd.DataFrame({"B": [3, 4], "A": [1, 2]})
     concatenate.transform_batch(other_df)

#   concat_out
# 0     [3, 1]
# 1     [4, 2]
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by martinbomio** [comment]
There are multiple ways to fix this issue, one way which seems to be the most "correct" one is to make the `Concatenator ` fittable and "learn" the order of columns at training time. This way, we can apply that order of columns in [here](https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessors/concatenator.py#L159), instead of deriving the order on the fly [here](https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessors/concatenator.py#L156)

**Comment by richardliaw** [comment]
As discussed offline, I think the best thing here is just specify the columns ahead of time via `include`. This would allow the order to be explicit, avoid any new API semantics changes, and will satisfy the requirements as well.

What we need to do is just make sure the ordering semantics are guaranteed and documented properly.

**Comment by martinbomio** [comment]
thanks @richardliaw . I went ahead and changed https://github.com/ray-project/ray/pull/47997
