### ISSUE TITLE
[core][compiled graphs] Add asyncio version of nightly microbenchmark

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#48001]
### Description

Our nightly microbenchmark does not cover asyncio logic. We should add a nightly test that does the same logic as the current [microbenchmark](https://github.com/ray-project/ray/blob/d2b9a6bb4f6046da836ac37e00ee7f8491b5b67f/python/ray/_private/ray_experimental_perf.py) but with `enable_asyncio=True`.

**Comment by awesmubarak** [comment]
This looks straightforward, I'd love to pick it up and get involved

**Comment by stephanie-wang** [comment]
Thanks! I'll assign you for now.

**Comment by stephanie-wang** [comment]
Hi, @awesmubarak since there is no update in two weeks, I'm unassigning you for now. Feel free to reassign yourself if you have bandwidth to do it.

**Comment by xingyu-long** [comment]
Hi @stephanie-wang, I am pretty new to ray project (a few fixes for ray data), but I'd like to pick up more. Could I take this one? and I will follow up with you if I hit any issues. Thanks!

**Comment by jeffreyjeffreywang** [comment]
@stephanie-wang This issue was first brought up in #47860. But actually, I think we do have asyncio microbenchmark. https://github.com/ray-project/ray/blob/b2fafa38277dd70611342489f4cf72bf0628cade/python/ray/_private/ray_experimental_perf.py#L190
Are we considering extending the asyncio microbenchmark?

**Comment by stephanie-wang** [comment]
> @stephanie-wang This issue was first brought up in #47860. But actually, I think we do have asyncio microbenchmark.
> 
> https://github.com/ray-project/ray/blob/b2fafa38277dd70611342489f4cf72bf0628cade/python/ray/_private/ray_experimental_perf.py#L190
> 
> 
> Are we considering extending the asyncio microbenchmark?

Ah my mistake. Let's close this then.
