### ISSUE TITLE
CI test linux://python/ray/tests:test_redis_tls is flaky

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#48010]
CI test **linux://python/ray/tests:test_redis_tls** is consistently_failing. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6545#019289a4-ffb5-485d-9d4e-c00c02e98636
	- https://buildkite.com/ray-project/postmerge/builds/6545#0192896c-6860-4063-8754-264b62c142e7

DataCaseName-linux://python/ray/tests:test_redis_tls-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6547#01928bcc-2729-4e65-b7b6-d72484eb4b8e

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6548#01928ca4-7e11-4279-9191-58db4ddd52c1

**Comment by can-anyscale** [comment]
CI test **linux://python/ray/tests:test_redis_tls** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928c03-f082-4d05-96e1-ab18c0cea127
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928bcc-2733-4d15-b1b0-2e9eefe1d6f2
	- https://buildkite.com/ray-project/postmerge/builds/6545#019289a4-ffb5-485d-9d4e-c00c02e98636
	- https://buildkite.com/ray-project/postmerge/builds/6545#0192896c-6860-4063-8754-264b62c142e7

DataCaseName-linux://python/ray/tests:test_redis_tls-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6549#01928d83-53f2-4aee-9884-863197ba6317

**Comment by can-anyscale** [comment]
CI test **linux://python/ray/tests:test_redis_tls** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6548#01928ca4-7e19-4ecb-953c-5d2a3517cd57
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928c03-f082-4d05-96e1-ab18c0cea127
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928bcc-2733-4d15-b1b0-2e9eefe1d6f2
	- https://buildkite.com/ray-project/postmerge/builds/6545#019289a4-ffb5-485d-9d4e-c00c02e98636
	- https://buildkite.com/ray-project/postmerge/builds/6545#0192896c-6860-4063-8754-264b62c142e7

DataCaseName-linux://python/ray/tests:test_redis_tls-END
Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6550#01928e93-d12c-470b-9091-de7ce147e2e5

**Comment by can-anyscale** [comment]
CI test **linux://python/ray/tests:test_redis_tls** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/6549#01928d83-53f9-45e1-8b2c-2bfd39c3de63
	- https://buildkite.com/ray-project/postmerge/builds/6548#01928ca4-7e19-4ecb-953c-5d2a3517cd57
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928c03-f082-4d05-96e1-ab18c0cea127
	- https://buildkite.com/ray-project/postmerge/builds/6547#01928bcc-2733-4d15-b1b0-2e9eefe1d6f2
	- https://buildkite.com/ray-project/postmerge/builds/6545#019289a4-ffb5-485d-9d4e-c00c02e98636

DataCaseName-linux://python/ray/tests:test_redis_tls-END
Managed by OSS Test Policy

**Comment by rkooo567** [comment]
@can-anyscale this test failure doesn't come up to flaky dahsboard. do you know why?

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6555#019291cb-a731-4eab-919d-8ad5814a2853

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/postmerge/builds/6558#01929206-7219-4e68-9ddb-e0ae10a3fd7f
