### ISSUE TITLE
Docker Hub image tags missing for 2.37.0

### ISSUE THREAD

**Issue by guseggert** [ray-project/ray#48017]
### What happened + What you expected to happen

The semantic tags on Docker Hub (ex https://hub.docker.com/r/rayproject/ray/tags?name=latest-py310-cpu) still point to 2.36.1 instead of the latest release (2.37.0). This seems to affect all the non-commit-sha tags like "2.37.0-py310-cpu" as well. 

Things seem to work okay when I use the commit sha for the release (for me, `2.37.0.1b620f-py310-cpu`).

### Versions / Dependencies

Ray 2.37.0

### Reproduction script

```
$ docker run -it --rm rayproject/ray:latest-py310-cpu ray --version
ray, version 2.36.1
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by ajaichemmanam** [comment]
+1

**Comment by anyscalesam** [comment]
@can-anyscale @aslonnie this should be fixed now right?

**Comment by aslonnie** [comment]
Yes

**Comment by guseggert** [comment]
LGTM, thanks!
