### ISSUE TITLE
[Data]: SimpleImputer fails on transform_batch when column is completely missing from dataframe 

### ISSUE THREAD

**Issue by martinbomio** [ray-project/ray#48047]
### What happened + What you expected to happen

When providing a pandas dataframe without the expected column to impute a missing value for, the Imputer fails with a `KeyError` on this [line](https://github.com/ray-project/ray/blob/master/python/ray/data/preprocessors/imputer.py#L131).

The expected behavior would be that the column is added and imputed if it is missing from the dataframe.

### Versions / Dependencies

Latest ray

### Reproduction script

```python
import ray
from ray.data.preprocessors import SimpleImputer
import pandas as pd
import nump as np

ds = ray.data.from_items([{"A": 1, "B", np.nan}])
imputer = SimpleImputer(columns=list("B"), strategy="constant", fill_value=0)

fitted_imputer = imputer.fit(ds)

fitted_imputer.transform_batch(pd.DataFrame({"A": [1], "B": [np.nan]}))
#     A    B
# 0  1  0.0

fitted_imputer.transform_batch(pd.DataFrame({"A": [1]}))
# fails with `KeyError: B`
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by richardliaw** [comment]
oh I guess it makes sense, let's fix
