### ISSUE TITLE
ray installation broke with bazel 0.25.x

### ISSUE THREAD

**Issue by fywu85** [ray-project/ray#4810]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 19.04
- **Ray installed from (source or binary)**: source
- **Ray version**: latest
- **Python version**: 3.6 
- **Exact command to reproduce**: `pip install -e . --verbose`

### Describe the problem

pip install would fail with bazel version 0.25.x but bazel 0.24.1 works just fine. This is likely caused by https://github.com/census-instrumentation/opencensus-cpp/pull/307

**Comment by jovany-wang** [comment]
Thanks for reporting this, I'll take a look.

**Comment by tmorgan4** [comment]
Disclaimer: I know nothing about C++, opencensus or abseil but changing the commit in ray/bazel/ray_deps_setup.bzl from 88a152ae747c3c42dc9167d46c590929b048d436 to 5b65c4af5107176555b23a638e5947686410ac1f allowed me to build.
