### ISSUE TITLE
[tune] No module named 'ray.tune.analysis'

### ISSUE THREAD

**Issue by supermoduli** [ray-project/ray#4812]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
macOS Mojave 10.14.4
- **Ray installed from (source or binary)**:
`pip install --upgrade ray`
- **Ray version**:
0.6.6
- **Python version**:
3.7.2
- **Exact command to reproduce**:
`from ray.tune.analysis import ExperimentAnalysis`

### Describe the problem

I got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ray.tune.analysis'
```

**Comment by richardliaw** [comment]
Can you try installing the latest version of master https://ray.readthedocs.io/en/latest/installation.html?

**Comment by supermoduli** [comment]
Thanks. I did that, but got the exact same error.

> Can you try installing the latest version of master https://ray.readthedocs.io/en/latest/installation.html?

**Comment by richardliaw** [comment]
Oh, can you try replacing dev2 to dev3? The link shows: 
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.7.0.dev2-cp36-cp36m-manylinux1_x86_64.whl

but you want 
https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.7.0.dev3-cp36-cp36m-manylinux1_x86_64.whl

**Comment by richardliaw** [comment]
In fact I think `pip install -U ray` should work, as a release just happened.

**Comment by supermoduli** [comment]
Indeed, `pip install --upgrade ray` worked, since there is this new release. Thanks again.

**Comment by richardliaw** [comment]
no problem; closing for now.
