### ISSUE TITLE
[tune] SearchAlg, Schedulers should support string indexing

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4814]
It'd be great to be able to do `search_alg="bayesopt"` and `scheduler="asha"`.

**Comment by JosephTLucas** [comment]
I was looking through the code.  Is this already done?
https://github.com/ray-project/ray/blob/2677b7100306f2e5689ab6bebdc264a0e37930ae/python/ray/tune/tune.py#L283

**Comment by richardliaw** [comment]
Ah it's not actually done yet. Feel free to give it a shot; @ me if you get stuck!

**Comment by cocorosiekz** [comment]
How should we pass additional parameters for the SearchAlg or Scheduler if we use string indexing?

**Comment by richardliaw** [comment]
I think ideally there would be some default setting.

**Comment by sumanthratna** [comment]
since we now have `tune.create_searcher` and `tune.create_scheduler` (#10456), I don't think this is really necessary anymore. closing for now.
