### ISSUE TITLE
Ape-X with DQN causes unexpected_keyword errors

### ISSUE THREAD

**Issue by shufflebyte** [ray-project/ray#4817]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: mac OS Mojave 10.14.4 and Linux Ubuntu 16.10 on our server
- **Ray installed from (source or binary)**: pip install -U [link to wheel] (klicked the links for python 3.6.8
- **Ray version**:  0.7.0.dev2 (also tested ray 0.6.0 before)
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem
Hi there,
I tried to combine Ape-X with DQN and got the following error:
`TypeError: __init__() got an unexpected keyword argument 'schedule_max_timesteps'`
It seems as the AsyncReplayOptimizer class expects these three arguments (schedule_max_timesteps, beta_annealing_fraction, final_prioritized_replay_beta) although it does not process these arguments. 
Well, we fixed it by adding those arguments in the __init__() function of AsyncReplayOptimizer in async_replay_optimizer.py. But this does not feel like the right way to do it ;-). I will put you the code here, so you can see, what we exactly did.

### Source code / logs
**Traceback**
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
Policy server listening at localhost:9900
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/florian/workspaces/jass/bot/ray_server.py", line 199, in <module>
    main(sys.argv[1:])
  File "/Users/florian/workspaces/jass/bot/ray_server.py", line 175, in main
    "learning_starts": 20000,
  File "/Users/florian/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/rllib/utils/__init__.py", line 20, in __init__
    cls.__init__(self, *args, **kwargs)
  File "/Users/florian/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 293, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/Users/florian/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/Users/florian/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 393, in _setup
    self._init(self.config, self.env_creator)
  File "/Users/florian/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/rllib/agents/dqn/dqn.py", line 233, in _init
    **config["optimizer"])
TypeError: __init__() got an unexpected keyword argument 'schedule_max_timesteps'

**our config**
    ray.init()
    print("[RAY] Initialized")
    register_env("srv", lambda _: CartpoleServing())

    dqn = DQNAgent(
        env="srv",
        config={
            #Ape-X for gpu...
            "optimizer_class": "AsyncReplayOptimizer",
            "optimizer": merge_dicts(
                DQN_CONFIG["optimizer"], {
                    "max_weight_sync_delay": 400,
                    "num_replay_buffer_shards": 4,
                    "debug": False
                }),
            "schedule_max_timesteps": 100000,
            "n_step": 3,
            "target_network_update_freq": 500000,
            "timesteps_per_iteration": 25000,
            "per_worker_exploration": True,
            "worker_side_prioritization": True,
            "min_iter_time_s": 30,
            "lr": 0.0001,
            "num_workers": num_workers,
            "model": model,
            "gamma": 0.99,
            "noisy": True,
            "num_gpus": 0,
            "sample_batch_size": 512,
            "train_batch_size": 1024,
            "buffer_size": 500000,
            "learning_starts": 20000,
        })

**path to my async_replay_optimizer.py**
`~/anaconda3/envs/sc2/lib/python3.6/site-packages/ray/rllib/optimizers/async_replay_optimizer.py`

**code we have changed in async_replay_optimizer.py**
added this to __init()__ of class AsyncReplayOptimizer(PolicyOptimizer):
`
                 schedule_max_timesteps=0,
                 beta_annealing_fraction=0,
                 final_prioritized_replay_beta=0`

**Comment by ericl** [comment]
You should use "APEX" instead of "DQN" to enable AsyncReplayOptimizer (there's a snippet of code that handles this config discrepency in the DQN class).

This is kind of a bug, but I think it may make sense to remove the optimizer_class config since it's rarely used.

**Comment by shufflebyte** [comment]
Hi thank you for your help!
After using ApexTrainer, I could reverse my changes to the async_replay_optimizer and it works!
It works with the config and without, I tested both configurations. :-) 

I am currently doing a grid search to find good hyperparameters. Do you think, I need to repeat my last trainings or do you think with my changes in AsyncReplayOptimizer everything worked the right way?

**Comment by ericl** [comment]
I would probably try tuning hyperparams again for APEX, especially things
like batch size (which is made larger by default).

**Comment by shufflebyte** [comment]
Thanks! :-) I will close this now, since my original issue has been solved by you.
