### ISSUE TITLE
[serve] Unable to obtain JSON formatted logs

### ISSUE THREAD

**Issue by PioFro** [ray-project/ray#48182]
### What happened + What you expected to happen

When setting up the encoding in LoggingConfig in:
* serve.deployment decorator
* serve.run 
* config.yml
* set the deprecated RAY_SERVE_ENABLE_JSON_LOGGING=1
* set the new RAY_SERVE_LOG_ENCODING=JSON
It seems to be disregarded by ray which continues to format logs as it did by default.

Note that I've tried all of the above sequentially and all of them at the same time.

The output of request coming to the reproduction script looks like that
![Screenshot from 2024-10-22 11-46-22](https://github.com/user-attachments/assets/0d0dc9e1-a3d2-4c4a-8ad7-f1859e4893c4)

### Versions / Dependencies

OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS" 

PYTHON VERSIONS:
3.11.9 AND 3.10.14

RAY VERSION:
2.37.0

OTHER PYTHON PACKAGES:
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiohttp-cors              0.7.0
aiosignal                 1.3.1
annotated-types           0.7.0
anyio                     4.5.0
async-timeout             4.0.3
attrs                     24.2.0
cachetools                5.5.0
certifi                   2024.8.30
charset-normalizer        3.3.2
click                     8.1.7
colorful                  0.5.6
distlib                   0.3.8
dnspython                 2.6.1
email_validator           2.2.0
exceptiongroup            1.2.2
fastapi                   0.115.0
fastapi-cli               0.0.5
filelock                  3.16.1
frozenlist                1.4.1
google-api-core           2.19.2
google-auth               2.34.0
googleapis-common-protos  1.65.0
grpcio                    1.66.1
h11                       0.14.0
http-parser               0.9.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.2
idna                      3.10
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
linkify-it-py             2.0.3
markdown-it-py            3.0.0
MarkupSafe                2.1.5
mdit-py-plugins           0.4.2
mdurl                     0.1.2
memray                    1.14.0
msgpack                   1.1.0
multidict                 6.1.0
opencensus                0.11.4
opencensus-context        0.1.3
packaging                 24.1
pip                       24.2
platformdirs              4.3.6
prometheus_client         0.20.0
proto-plus                1.24.0
protobuf                  5.28.2
py-spy                    0.3.14
pyasn1                    0.6.1
pyasn1_modules            0.4.1
pycapnp                   2.0.0
pydantic                  2.9.2
pydantic_core             2.23.4
Pygments                  2.18.0
python-dotenv             1.0.1
python-multipart          0.0.10
PyYAML                    6.0.2
referencing               0.35.1
requests                  2.32.3
requests-toolbelt         1.0.0
requests-unixsocket       0.3.0
rich                      13.8.1
rpds-py                   0.20.0
rsa                       4.9
setuptools                65.5.0
shellingham               1.5.4
six                       1.16.0
smart-open                7.0.4
sniffio                   1.3.1
starlette                 0.38.5
textual                   0.79.1
typer                     0.12.5
typing_extensions         4.12.2
uc-micro-py               1.0.3
urllib3                   2.2.3
uvicorn                   0.30.6
uvloop                    0.20.0
virtualenv                20.26.5
watchfiles                0.24.0
websockets                13.0.1
wrapt                     1.16.0
yarl                      1.11.1

### Reproduction script
```python
import logging
from uuid import uuid4
from fastapi import FastAPI, Response
from ray.serve.schema import LoggingConfig
from ray import serve

LOGGER = logging.getLogger("ray.serve")

app = FastAPI()


@serve.deployment(num_replicas=1, logging_config=LoggingConfig(enable_access_log=False, encoding="JSON"))
class TestDeployment:
    def __init__(self) -> None:
        self.logger = logging.getLogger("ray.serve")
        pass

    async def handle_test(self, request_id: str = "no", logger_model_name: str = "no"):
        LOGGER.info("Test 'JSON' logs with extra", extra={"request_id": request_id, "model_name": logger_model_name})
        logging.info("no logger used just logging.info")
        print("just printing stuff")
        self.logger.info("self.logger")
        return Response(status_code=200)


@serve.deployment(num_replicas=1, logging_config=LoggingConfig(enable_access_log=False, encoding="JSON"))
@serve.ingress(app)
class APIIngress:

    def __init__(self, handle) -> None:
        self.handle = handle

    @app.get("/test")
    async def test(self):
        LOGGER.info("here in handler")
        return await self.handle.handle_test.remote(request_id=str(uuid4()), logger_model_name="model-name-in-req")


serve.run(
    APIIngress.bind(TestDeployment.bind()),
    blocking=True,
    logging_config=LoggingConfig(enable_access_log=False, encoding="JSON"),
)
```
### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jcotant1** [comment]
Hey @zcin any idea on this one?

**Comment by LauraMaassen** [comment]
We have the same problem. Our setup is:
OS:
DISTRIB_ID=EulerOS
DISTRIB_RELEASE=2.0
DISTRIB_DESCRIPTION=EulerOS 2.0 SP9

PYTHON VERSIONS:
3.10.12

RAY VERSION:
2.37.0

**Comment by PioFro** [comment]
It gets in a way of relaying container logs to some centralised logging solution but I can work around it with the file contents - it would be nice to just have the JSON output on the console but I guess it comes in a way of the dashboard logs solution.
