### ISSUE TITLE
[core][compiled graphs] Support ASCII based visualization for Compiled Graphs

### ISSUE THREAD

**Issue by ruisearch42** [ray-project/ray#48190]
### Description

Compared to graphviz, ASCII based visualization will be often more convenient for users and it's possible to test in CI.
https://github.com/ray-project/ray/pull/47586#discussion_r1808002878

**Comment by Bye-legumes** [comment]
I can try to add ASCII based visualization based on my current implementation.

**Comment by ruisearch42** [comment]
> I can try to add ASCII based visualization based on my current implementation.

Sounds good. Thanks!
