### ISSUE TITLE
[core] Task creation throughput regression

### ISSUE THREAD

**Issue by ruisearch42** [ray-project/ray#48298]
### What happened + What you expected to happen

<img width="1046" alt="Screenshot 2024-10-28 at 2 08 38 PM" src="https://github.com/user-attachments/assets/3eb48269-c102-4428-9b8f-beb927d327b0">

### Versions / Dependencies

head

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

**Comment by ruisearch42** [comment]
Investigation thread: https://anyscaleteam.slack.com/archives/C04TC79BYU9/p1730236743180449
The regression should come from some infra change

**Comment by jjyao** [comment]
<img width="485" alt="Screenshot 2024-11-14 at 3 11 35 PM" src="https://github.com/user-attachments/assets/1766afd4-bffc-452a-a2ab-293ce1acd24c">

Back to normal

**Comment by ruisearch42** [comment]
I ran a release test with the same commit, the throughput was 545, similar level as before the drop: https://buildkite.com/ray-project/release/builds/26079#01932d2b-9788-45d6-84fc-974ba1aa9166
This confirmed the issue was from infra layer and was resolved.
