### ISSUE TITLE
Test failure in TestPlasmaClient.test_hash on Travis.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#483]
I've been seeing this test failure ever since #479 (and never before that).

```
======================================================================

FAIL: test_hash (__main__.TestPlasmaClient)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "python/ray/plasma/test/test.py", line 226, in test_hash

    self.plasma_client.hash(object_id2))

AssertionError: '\xdf\x13\xbcy\xd9[s\xabz\x85\xdc\x0e\x01\x00\x00\x00 d\xe7P\xff\x7f\x00\x00\xae\x86\xdd\x0e\x01\x00\x00\x00' != '\xdf\x13\xbcy\xd9[s\xab\xe8PB\xc9\xdc\x7f\x00\x00 d\xe7P\xff\x7f\x00\x00\xae\x86\xdd\x0e\x01\x00\x00\x00'



----------------------------------------------------------------------

Ran 19 tests in 60.745s



FAILED (failures=1)

[0m

travis_time:end:1354476c:start=1493018593719606000,finish=1493018654826774000,duration=61107168000
[0K

[31;1mThe command "python python/ray/plasma/test/test.py" exited with 1.[0m
```

For example, see https://s3.amazonaws.com/archive.travis-ci.org/jobs/225090578/log.txt.

It's hard to see how #479 could be related, but we could try reverting it and see what happens.

I think I've only seen the failure on Python 2.7 on Mac OS X on Travis (and it happens pretty consistently there).

**Comment by richardliaw** [comment]
off the current master branch, I'm running jarvis with the MacOSX setup with python 2.7 on this specific subset of tests and I'm having trouble reproducing the bug. I'll try resetting to #600 to see if this is reproducible...

**Comment by robertnishihara** [comment]
I'd suggest modifying the `.travis.yml` file to run the test (and only the relevant test) in a loop. That might help to reproduce it.

**Comment by robertnishihara** [comment]
Closing this because I have not seen this error in a long time. Please reopen if this error occurs again.

**Comment by robertnishihara** [comment]
Reopening because it looks like the error is still around (see https://api.travis-ci.org/jobs/259566082/log.txt?deansi=true).

**Comment by robertnishihara** [comment]
Closing because I haven't seen this in a while. Anyway this test runs in the Arrow codebase now, see https://github.com/apache/arrow/blob/6299a9cfb314dc7a03fdafca41419a6be4300225/python/pyarrow/tests/test_plasma.py#L430
