### ISSUE TITLE
[tune] NotImplementedError 

### ISSUE THREAD

**Issue by zhaokang1228** [ray-project/ray#4833]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:binary
- **Ray version**:0.6.5
- **Python version**:3.5
- **Exact command to reproduce**:

### Describe the problem

The pbt_example.py can run successively.I used the function-based API and reporter was conducted within my function.
But, I got a tune error:

### Source code 

`
#!/usr/bin/env python

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import json
import os
import random
import time

import ray
from ray.tune import Trainable, run
from ray.tune.schedulers import PopulationBasedTraining

def easy_objective(config, reporter):
    import time
    time.sleep(0.2)
    for i in range(1000):
        reporter(
            timesteps_total=i,
            neg_mean_loss=-(config["height"] - 14)**2 +
            abs(config["width"] - 3))
        time.sleep(0.02)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    args, _ = parser.parse_known_args()
    if args.smoke_test:
        ray.init(num_cpus=4)  # force pausing to happen for test
    else:
        ray.init()

    pbt = PopulationBasedTraining(
        time_attr="timesteps_total",
        reward_attr="neg_mean_loss",
        perturbation_interval=10,
        hyperparam_mutations={
            # Allow for scaling-based perturbations, with a uniform backing
            # distribution for resampling.
            "height": lambda: random.uniform(0.0, 20.0),
            # Allow perturbations within this set of categorical values.
            "width": [1, 2],
        })

    # Try to find the best factor 1 and factor 2
    run(easy_objective,
        name="pbt_test111",
        scheduler=pbt,

        # reuse_actors=True,

        # verbose=1,
        **{
            "stop": {
                "timesteps_total": 20 if args.smoke_test else 100
            },
            "num_samples": 10,
            "config": {
                "height": 4.0,
                "width": 1.0,
            },
        })

`

### error log

`

== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 5.1/16.8 GB

== Status ==
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 1/8 CPUs, 0/0 GPUs
Memory usage on this node: 5.3/16.8 GB
Result logdir: /home/kangkang/ray_results/pbt_test111
Number of trials: 10 ({'PENDING': 9, 'RUNNING': 1})
PENDING trials:
 - easy_objective_1:	PENDING
 - easy_objective_2:	PENDING
 - easy_objective_3:	PENDING
 - easy_objective_4:	PENDING
 - easy_objective_5:	PENDING
 - easy_objective_6:	PENDING
 - easy_objective_7:	PENDING
 - easy_objective_8:	PENDING
 - easy_objective_9:	PENDING
RUNNING trials:
 - easy_objective_0:	RUNNING

2019-05-22 14:01:09,828	WARNING util.py:64 -- The `start_trial` operation took 1.0127665996551514 seconds to complete, which may be a performance bottleneck.
Result for easy_objective_3:
  date: 2019-05-22_14-01-10
  done: false
  experiment_id: 7e7197cc60f549d5ab9a5c6bd0abadf4
  hostname: kangkang-1994
  iterations_since_restore: 1
  neg_mean_loss: -98.0
  node_ip: 192.168.4.102
  pid: 6989
  time_since_restore: 0.2003629207611084
  time_this_iter_s: 0.2003629207611084
  time_total_s: 0.2003629207611084
  timestamp: 1558504870
  timesteps_since_restore: 0
  timesteps_total: 0
  training_iteration: 1
  
Result for easy_objective_2:
  date: 2019-05-22_14-01-10
  done: false
  experiment_id: 4ef48e43b4864631b2274dafad4f42ca
  hostname: kangkang-1994
  iterations_since_restore: 1
  neg_mean_loss: -98.0
  node_ip: 192.168.4.102
  pid: 6987
  time_since_restore: 0.2003781795501709
  time_this_iter_s: 0.2003781795501709
  time_total_s: 0.2003781795501709
  timestamp: 1558504870
  timesteps_since_restore: 0
  timesteps_total: 0
  training_iteration: 1
 ......
 ......
 ......
Result for easy_objective_4@perturbed[height=4.8,width=1]:
  date: 2019-05-22_14-01-15
  done: false
  experiment_id: e3dce174521a4888ae443ed128585673
  hostname: kangkang-1994
  iterations_since_restore: 1
  neg_mean_loss: -82.63999999999999
  node_ip: 192.168.4.102
  pid: 7370
  time_since_restore: 0.20229816436767578
  time_this_iter_s: 0.20229816436767578
  time_total_s: 0.20229816436767578
  timestamp: 1558504875
  timesteps_since_restore: 0
  timesteps_total: 0
  training_iteration: 1
  
2019-05-22 14:01:15,998	ERROR worker.py:1616 -- Possible unhandled error from worker: ray_WrappedFunc:save_to_object() (pid=6990, host=kangkang-1994)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 284, in save_to_object
    checkpoint_prefix = self.save(tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 241, in save
    checkpoint = self._save(checkpoint_dir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 419, in _save
    raise NotImplementedError
NotImplementedError
.......
......
......

2019-05-22 14:01:49,055	ERROR worker.py:1616 -- Possible unhandled error from worker: ray_WrappedFunc:restore_from_object() (pid=8644, host=kangkang-1994)
ray.exceptions.RayTaskError: ray_WrappedFunc:save_to_object() (pid=8364, host=kangkang-1994)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 284, in save_to_object
    checkpoint_prefix = self.save(tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 241, in save
    checkpoint = self._save(checkpoint_dir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 419, in _save
    raise NotImplementedError
NotImplementedError

2019-05-22 14:01:49,238	ERROR worker.py:1616 -- Possible unhandled error from worker: ray_WrappedFunc:save_to_object() (pid=8644, host=kangkang-1994)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 284, in save_to_object
    checkpoint_prefix = self.save(tmpdir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 241, in save
    checkpoint = self._save(checkpoint_dir)
  File "/usr/local/lib/python3.5/dist-packages/ray/tune/trainable.py", line 419, in _save
    raise NotImplementedError
NotImplementedError

Process finished with exit code 0

`

Thanks!

**Comment by zhaokang1228** [comment]
When the PBT scheduler is enabled, each trial variant is treated as a member of the population. Periodically, top-performing trials are checkpointed (this requires your Trainable to support **checkpointing**). [Population Based Training (PBT)](https://ray.readthedocs.io/en/latest/tune-schedulers.html#population-based-training-pbt)

**Comment by richardliaw** [comment]
Yeah, you need to implement your function as a Trainable. Did you figure it out?

**Comment by zhaokang1228** [comment]
OK! thank you！
