### ISSUE TITLE
ExternalEnv with Ape-X

### ISSUE THREAD

**Issue by synaptic** [ray-project/ray#4835]
### System information
- Linux Ubuntu 16.04
- Ray installed from binary (via conda)
- Ray version 0.6.5 (installed via https://github.com/ray-project/tutorial/blob/master/environment.yml) 
- Python version 3.6

### Describe the problem
I was trying to change the ExternalEnv serving example given here (https://github.com/ray-project/tutorial/blob/master/rllib_exercises/rllib_exercise03_serving.ipynb) to use Ape-X (ApexTrainer agent / AsyncReplayOptimizer optimizer class).  I specified 1 local evaluator and 2 remote evaluators.  However, because that example uses a hard-coded server IP address and port, it fails with "Address already in use" after the first local evaluator is started (the remote evaluators cannot use the same IP address and port).  

All the evaluators are instantiated by initializing and running the same SimpleServing class you find here (https://github.com/ray-project/tutorial/blob/master/rllib_exercises/serving/simple_policy_server.py).  I found a work-around which selects a random unused port number to open each time so there is no port collision.  It does run, but then the ports are random so it is harder to set up the clients (you have to grab them from the print out).  Is there an easier way to get this working with Ape-X?  I suppose I could start with port 8900 and keep incrementing it by 1 until it succeeds.  Are there any examples which use ExternalEnv with Ape-X?

**Comment by ericl** [comment]
You can deterministically assign ports by using env_config.worker_index, see here: https://ray.readthedocs.io/en/latest/rllib-env.html

**Comment by synaptic** [comment]
Thanks, that worked great!
