### ISSUE TITLE
Actor cannot be restored after killing a node.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#4840]
### How to reprod:
1) Start a Ray cluster with one node(called `nodeA`).
2) Run an actor(called `actorA`, with checkpointable) in the cluster.
3) Connect a new node(called `nodeB`) to the cluster.
4) Kill `nodeA`.

Then the `actorA` cannot be restored on the `nodeB` since there are no state info of `actorA` in the `actor_registry_` of `nodeB`'s NodeManager.

A feasible scenario is to load all actor info from `GCS` into `actor_registry_` when a node connecting to the cluster.

**Comment by jovany-wang** [comment]
@stephanie-wang  For this issue, I'd like to add the index for actor tables in redis module so that we can easily fetch all actors in cluster. What do you think of this?

**Comment by stephanie-wang** [comment]
One way to fix this would be to have `nodeB` look up `actorA` in the GCS if it cannot find an entry in its local `actor_registry_`. We do this already for a similar scenario, where `nodeB` wants to submit a task to `actorA` but doesn't have its location yet ([code](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L1603)).

**Comment by raulchen** [comment]
@stephanie-wang the problem is that `nodeB` never knows `actorA` had existed before.

**Comment by stephanie-wang** [comment]
> One way to fix this would be to have `nodeB` look up `actorA` in the GCS if it cannot find an entry in its local `actor_registry_`. We do this already for a similar scenario, where `nodeB` wants to submit a task to `actorA` but doesn't have its location yet ([code](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L1603)).

**Comment by stephanie-wang** [comment]
> @stephanie-wang the problem is that `nodeB` never knows `actorA` had existed before.

Right, because the pubsub notification from the actor table came before it connected, right? I'm suggesting that `nodeB` looks up the entry from the actor table once it hears about `actorA`'s failure.

**Comment by raulchen** [comment]
> > @stephanie-wang the problem is that `nodeB` never knows `actorA` had existed before.
> 
> Right, because the pubsub notification from the actor table came before it connected, right? I'm suggesting that `nodeB` looks up the entry from the actor table once it hears about `actorA`'s failure.

`nodeB` only gets notification of `nodeA`'s failure, it won't know the IDs of the actors that were on `nodeA`. So it can't look up the `actorA` exactly, it can only query the whole actor table (or query all actors on `nodeA` if we have such an index).

**Comment by stephanie-wang** [comment]
I see, are you suggesting that `nodeB` reconstructs `actorA` automatically? I was assuming that `nodeB` would only restore the actor if it needs some result from the actor, but yes, it may not have `actorA`'s ID otherwise.

**Comment by raulchen** [comment]
yeah, we need the failed actors to be reconstructed automatically. E.g., the source actors in streaming system. They pull data from external storage, no one would send them tasks to trigger reconstruction.

**Comment by jovany-wang** [comment]
@stephanie-wang @raulchen 
So the final approach may be creating an index from driver_id to actor_ids of this driver in GCS, right?

**Comment by raulchen** [comment]
I don't think this depends on indexing that. The node needs to load all existing actors on startup.

**Comment by jovany-wang** [comment]
> I don't think this depends on indexing that. The node needs to load all existing actors on startup.

Sorry, I meant adding a field to store all the actor_ids of the cluster in GCS.

**Comment by stephanie-wang** [comment]
Hmm is it feasible to do a `SCAN` of the actor table? This might be a good time to implement it, since we need it for #4935 too.

**Comment by raulchen** [comment]
yeah, we can simply `scan` by the actor table prefix

**Comment by jovany-wang** [comment]
This is already fixed.
