### ISSUE TITLE
[Data] Dataset operator names are confusing when operator ends with a number 

### ISSUE THREAD

**Issue by alanwguo** [ray-project/ray#48482]
### What happened + What you expected to happen

<img width="287" alt="Screenshot 2024-10-31 at 4 44 43 PM" src="https://github.com/user-attachments/assets/d3dc63fd-c13f-46ab-adcd-469e7d708c64">

Notice that the operator names end with an integer that represents the order of the operator.

When the operator name also has an integer at the end like `limit=5`, the order gets appended afterwards and it looks like `limit=56` which is very confusing.

### Versions / Dependencies

2.37.0

### Reproduction script

```
import ray
import time

def f(x):
    time.sleep(0.1)
    return x

def g(x):
    time.sleep(1)
    return x

ray.data.range(100).map(f).map(g, num_cpus=0.1).take_batch(5)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by gitlijian** [comment]
Hello Alanwguo, can I participate in resolving this issue? For example, in the situation you mentioned, can we check in advance whether the character 'limit=5' ends with a number between limit=5 and limit=56? If it ends with a number, we can add a '_' and 'limit=5->limit=5,6'.

**Comment by gitlijian** [comment]
Hello Alanwguo, can I participate in resolving this issue? For example, in the situation you mentioned, can we check in advance whether the character 'limit=5' ends with a number between limit=5 -> limit=56? If it ends with a number, we can add a '_' and 'limit=5->limit=5,6'.

**Comment by gitlijian** [comment]
Hello Alanwguo, can I participate in resolving this issue? For example, in the situation you mentioned, can we check in advance whether the character 'limit=5' ends with a number between limit=5 and limit=56? If it ends with a number, we can add a '_' and 'limit=5->limit=5_6'.
