### ISSUE TITLE
Pytorch's `requires_grad` attribute isn't serialized

### ISSUE THREAD

**Issue by andyljones** [ray-project/ray#4855]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.3
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.6.5
- **Python version**:  3.7.3
- **Exact command to reproduce**:

```python
import pyarrow as pa
import torch

# Create a tensor that requires a gradient
value = torch.tensor([], requires_grad=True)

# Set up the context
context = pa.default_serialization_context()
pa.register_torch_serialization_handlers(context)

# Write
scratch_buffer = pa.allocate_buffer(32*2**20)
writer = pa.FixedSizeBufferWriter(scratch_buffer)
pa.serialize_to(value, writer, context=context)

# Read
reader = pa.BufferReader(scratch_buffer)
result = pa.deserialize_from(reader, None, context=context)

# No longer requires gradient :(
result.requires_grad
```

### Describe the problem
If you serialize and deserialize a Pytorch tensor, `requires_grad` always comes back `False`. It's a problem with Pyarrow, but while writing up an issue in their tracker I realised my Pyarrow version was `0.12.0.RAY` so I don't want to drop it on their laps first - I don't know how serious Ray's modifications to Pyarrow are.

To catch some error-message-googling: my immediate symptom was passing a `torch.nn.Module` through the Ray object store and getting a 
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
error when I tried to backprop through it. The immediate workaround is to add a custom serializer for torch modules, with 
```python
ray.register_custom_serializer(torch.nn.Module, use_pickle=True)
```

**Comment by robertnishihara** [comment]
Thanks @andyljones! The relevant lines that need to change (in pyarrow) are 

https://github.com/apache/arrow/blob/d20640deb0cf585971c07221e17dc657e0cda66d/python/pyarrow/serialization.py#L230-L234

Ray doesn't modify pyarrow, however, we do build pyarrow wheels on Ubuntu 14.04 instead of an old CentOS version (for compatibility with TensorFlow).

Are there other fields like `requires_grad` that need to be serialized as well?

**Comment by andyljones** [comment]
Good point on what other fields there might be. I started to look at making a PR to fix this, but PyTorch tensors seem to have quite a list of fields
```python
', '.join(k for k in dir(torch.tensor([])) if not callable(getattr(value, k)))
>>> __array_priority__, __dict__, __doc__, __module__, __weakref__, _backward_hooks, _base, _cdata, _grad, _grad_fn, _version, data, device, dtype, grad, grad_fn, is_cuda, is_leaf, is_quantized, is_sparse, layout, name, output_nr, requires_grad, shape
```
Had a look at the [PyTorch](https://github.com/pytorch/pytorch/blob/444039c47bb997f698c2bd9481c8649188038c51/torch/serialization.py#L222-L298) serialization [code](https://github.com/pytorch/pytorch/blob/444039c47bb997f698c2bd9481c8649188038c51/torch/csrc/serialization.cpp) to see what actually needs to be serialized, but it's involved enough that I - knowing nothing about pyarrow or pytorch - am not gonna be able to figure it out in a morning. 

Pickle is fast enough for my purposes for now; I'll revisit this when that changes.
