### ISSUE TITLE
[<Ray Train: Train>] seems wrong world_size during multi workers multi NPU cards

### ISSUE THREAD

**Issue by lxmanutd** [ray-project/ray#48561]
### What happened + What you expected to happen

Hello, I am using scaling_config = ScalingConfig(num_workers=args.num_workers, resources_per_worker={"NPU":args.npu_per_worker}) in my training, and set num_works=2, npu_per_worker=2, then I hope it could use 2 works and each worker 2 NPU cards to work. 
But in effect, it really use 2 workers, but the world size is 2 which should be 2*2=4 and only 1NPU worked, that's npu 0, though we could use get_devices to get 2 npu. We can get npu-info from "npu-smi info" command,  from the following we can see only one npu card processing. Could you please help to check this? Thanks a lot

+------------------------------------------------------------------------------------------------+
| npu-smi 23.0.6.2                 Version: 23.0.6.2                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 107.3       43                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3862 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 99.1        44                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3179 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 218169        | ray_RayTrainW            | 558                     |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

(TorchTrainer pid=195626, ip=10.222.16.35) Started distributed worker processes: 
(TorchTrainer pid=195626, ip=10.222.16.35) - (node_id=cabfad70bb6bbbda626ac0e33340830bd3074a35a4854bcdf235a8be, ip=10.222.16.35, pid=195817) world_rank=0, local_rank=0, node_rank=0
(TorchTrainer pid=195626, ip=10.222.16.35) - (node_id=abaf5211037d036766687c4b948c35c03051ca7b2ad9da187844e613, ip=10.222.16.33, pid=232927) world_rank=1, local_rank=0, node_rank=1
(RayTrainWorker pid=195817, ip=10.222.16.35) [W compiler_depend.ts:623] Warning: expandable_segments currently defaults to false. You can enable this feature by `export PYTORCH_NPU_ALLOC_CONF = expandable_segments:True`. (function operator())
(RayTrainWorker pid=232927, ip=10.222.16.33) [W compiler_depend.ts:623] Warning: expandable_segments currently defaults to false. You can enable this feature by `export PYTORCH_NPU_ALLOC_CONF = expandable_segments:True`. (function operator())
(RayTrainWorker pid=195817, ip=10.222.16.35) Moving model to device: npu:0
(RayTrainWorker pid=232927, ip=10.222.16.33) Moving model to device: npu:0
(RayTrainWorker pid=195817, ip=10.222.16.35) Wrapping provided model in DistributedDataParallel.
(RayTrainWorker pid=232927, ip=10.222.16.33) Wrapping provided model in DistributedDataParallel.
(RayTrainWorker pid=232927, ip=10.222.16.33) get_checkpoint: Checkpoint(filesystem=local, path=/data/mlops/training/saves/ray/TorchTrainer_2024-11-05_17-43-03/TorchTrainer_5d7bb_00000_0_2024-11-05_17-43-08/checkpoint_000003)
(RayTrainWorker pid=232927, ip=10.222.16.33) get_checkpoint checkpoint_dir: /data/mlops/training/saves/ray/TorchTrainer_2024-11-05_17-43-03/TorchTrainer_5d7bb_00000_0_2024-11-05_17-43-08/checkpoint_000003
(RayTrainWorker pid=195817, ip=10.222.16.35) get_checkpoint: Checkpoint(filesystem=local, path=/data/mlops/training/saves/ray/TorchTrainer_2024-11-05_17-43-03/TorchTrainer_5d7bb_00000_0_2024-11-05_17-43-08/checkpoint_000003)
(RayTrainWorker pid=195817, ip=10.222.16.35) get_checkpoint checkpoint_dir: /data/mlops/training/saves/ray/TorchTrainer_2024-11-05_17-43-03/TorchTrainer_5d7bb_00000_0_2024-11-05_17-43-08/checkpoint_000003
(RayTrainWorker pid=195817, ip=10.222.16.35) curr epoch:  86
(RayTrainWorker pid=195817, ip=10.222.16.35) start to train epoch : 86
(RayTrainWorker pid=195817, ip=10.222.16.35) world_size is: 2
(RayTrainWorker pid=195817, ip=10.222.16.35) world_rank is: 0
(RayTrainWorker pid=195817, ip=10.222.16.35) node_rank is: 0
(RayTrainWorker pid=195817, ip=10.222.16.35) local_rank is: 0
(RayTrainWorker pid=195817, ip=10.222.16.35) devices is: [device(type='npu', index=0), device(type='npu', index=1)]
(RayTrainWorker pid=232927, ip=10.222.16.33) curr epoch:  86
(RayTrainWorker pid=232927, ip=10.222.16.33) start to train epoch : 86
(RayTrainWorker pid=232927, ip=10.222.16.33) world_size is: 2
(RayTrainWorker pid=232927, ip=10.222.16.33) world_rank is: 1
(RayTrainWorker pid=232927, ip=10.222.16.33) node_rank is: 1
(RayTrainWorker pid=232927, ip=10.222.16.33) local_rank is: 0
(RayTrainWorker pid=232927, ip=10.222.16.33) devices is: [device(type='npu', index=0), device(type='npu', index=1)]

### Versions / Dependencies

Ray, version 2.37.0
Platform: Linux-4.19.90-2107.6.0.0192.8.oe1.bclinux.aarch64-aarch64-with-glibc2.35
Python version: 3.10.14
PyTorch version: 2.1.0 (NPU)
Transformers version: 4.44.2
NPU type: Ascend910B2
CANN version: 8.0.RC3.alpha001

### Reproduction script

```
import os
from typing import Dict

import torch
from filelock import FileLock
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import Normalize, ToTensor
from tqdm import tqdm

import ray.train
from ray.train import ScalingConfig, Checkpoint, RunConfig
from ray.train.torch import TorchTrainer, TorchConfig
import tempfile


def get_dataloaders(batch_size):
    # Transform to normalize the input images
    transform = transforms.Compose([ToTensor(), Normalize((0.5,), (0.5,))])

    with FileLock(os.path.expanduser("~/data.lock")):
        # Download training data from open datasets
        training_data = datasets.FashionMNIST(
            root="~/data",
            train=True,
            download=True,
            transform=transform,
        )

        # Download test data from open datasets
        test_data = datasets.FashionMNIST(
            root="~/data",
            train=False,
            download=True,
            transform=transform,
        )

    # Create data loaders
    train_dataloader = DataLoader(training_data, batch_size=batch_size, shuffle=True)
    test_dataloader = DataLoader(test_data, batch_size=batch_size)

    return train_dataloader, test_dataloader


# Model Definition
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Dropout(0.25),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Dropout(0.25),
            nn.Linear(512, 10),
            nn.ReLU(),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


def train_func_per_worker(config: Dict):
    lr = config["lr"]
    epochs = config["epochs"]
    batch_size = config["batch_size_per_worker"]

    # Get dataloaders inside the worker training function
    train_dataloader, test_dataloader = get_dataloaders(batch_size=batch_size)

    # [1] Prepare Dataloader for distributed training
    # Shard the datasets among workers and move batches to the correct device
    # =======================================================================
    train_dataloader = ray.train.torch.prepare_data_loader(train_dataloader)
    test_dataloader = ray.train.torch.prepare_data_loader(test_dataloader)

    model = NeuralNetwork()

    # [2] Prepare and wrap your model with DistributedDataParallel
    # Move the model to the correct GPU/CPU device
    # ============================================================
    model = ray.train.torch.prepare_model(model)

    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=lr, momentum=0.9)
    
    # ====== Resume training state from the checkpoint. ======
    start_epoch = 0
    checkpoint = ray.train.get_checkpoint()
    print("get_checkpoint:", checkpoint)
    if checkpoint:
        with checkpoint.as_directory() as checkpoint_dir:
            print("get_checkpoint checkpoint_dir:", checkpoint_dir)
            model_state_dict = torch.load(
                os.path.join(checkpoint_dir, "model.pt"),
                # map_location=...,  # Load onto a different device if needed.
            )
            model.load_state_dict(model_state_dict)
            optimizer.load_state_dict(
                torch.load(os.path.join(checkpoint_dir, "optimizer.pt"))
            )
            start_epoch = (
                torch.load(os.path.join(checkpoint_dir, "extra_state.pt"))["epoch"] + 1
            )
    # ========================================================

    # Model training loop
    # for epoch in range(epochs):
    for epoch in range(start_epoch, epochs):
    # if False:
        print_worker_info(epoch)
        if ray.train.get_context().get_world_size() > 1:
            # Required for the distributed sampler to shuffle properly across epochs.
            train_dataloader.sampler.set_epoch(epoch)

        model.train()
        for X, y in tqdm(train_dataloader, desc=f"Train Epoch {epoch}"):
            pred = model(X)
            loss = loss_fn(pred, y)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        model.eval()
        test_loss, num_correct, num_total = 0, 0, 0
        with torch.no_grad():
            for X, y in tqdm(test_dataloader, desc=f"Test Epoch {epoch}"):
                pred = model(X)
                loss = loss_fn(pred, y)

                test_loss += loss.item()
                num_total += y.shape[0]
                num_correct += (pred.argmax(1) == y).sum().item()

        test_loss /= len(test_dataloader)
        accuracy = num_correct / num_total
        metrics={"loss": test_loss, "accuracy": accuracy}
        # ====== Save training state to the checkpoint. ======
        with tempfile.TemporaryDirectory() as temp_checkpoint_dir:
            print("tempfile.TemporaryDirectory():", temp_checkpoint_dir)
            checkpoint = None
            should_checkpoint = epoch % config.get("checkpoint_freq", 1) == 0
            if ray.train.get_context().get_world_rank() == 0 and should_checkpoint:
                torch.save(
                    model.state_dict(),  # NOTE: Unwrap the model.
                    os.path.join(temp_checkpoint_dir, "model.pt"),
                )
                torch.save(
                    optimizer.state_dict(),
                    os.path.join(temp_checkpoint_dir, "optimizer.pt"),
                )
                torch.save(
                    {"epoch": epoch},
                    os.path.join(temp_checkpoint_dir, "extra_state.pt"),
                )
            checkpoint = Checkpoint.from_directory(temp_checkpoint_dir)
            print("saving checkpoint: epoch:", epoch)
            ray.train.report(metrics, checkpoint=checkpoint)
        # ====== Save training state to the checkpoint end. ======


def train_fashion_mnist(num_workers=2, use_gpu=False):
    global_batch_size = 32

    train_config = {
        "lr": 1e-3,
        "epochs": 10,
        "batch_size_per_worker": global_batch_size // num_workers,
        "checkpoint_freq": 3,
    }

    # Configure computation resources
    ray.init(address="ray://10.222.41.164:10001")
    torch_config = TorchConfig(backend="hccl", timeout_s=18000)
    scaling_config = ScalingConfig(num_workers=num_workers, resources_per_worker={"NPU":2})

    # Initialize a Ray TorchTrainer
    trainer = TorchTrainer(
        train_loop_per_worker=train_func_per_worker,
        train_loop_config=train_config,
        torch_config=torch_config,
        scaling_config=scaling_config,
        run_config=RunConfig(storage_path="/data/mlops/training/saves/llama3-8b/lora/pytorch/"),
    )
    result = trainer.fit()
    print(f"Training result: {result}")

def print_worker_info(epoch):
    context = ray.train.get_context()
    # 获取当前训练作业的总工作节点数。
    print("start to train epoch :", epoch)
    world_size = context.get_world_size()
    print("world_size is:", world_size)

    # 获取当前工作节点的索引，通常用于区分不同的工作节点。
    world_rank = context.get_world_rank()
    print("world_rank is:", world_rank)

    # 获取当前节点的排名，这在多节点训练中很有用。
    node_rank = context.get_node_rank()
    print("node_rank is:", node_rank)

    # 获取当前工作节点上本地工作进程的索引。
    local_rank = context.get_local_rank()
    print("local_rank is:", local_rank)

    # 如果actor 有多个实例，这个 API 可以获取当前 actor 实例的排名。
    #actor_rank = context.get_actor_rank()
    #print("actor_rank is:", actor_rank)

    # 获取当前 actor 的索引，如果有多个 actor 实例的话。
    #current_actor_index = context.get_current_actor_index()
    #print("current_actor_index is:", current_actor_index)

    # 检查当前工作进程是否是本地的主进程。
    #is_local_master = context.is_local_master()
    #print("is_local_master is:", is_local_master)

    # 检查当前工作进程是否是全局的主进程。
    #is_world_master = context.is_world_master()
    #print("is_world_master is:", is_world_master)


if __name__ == "__main__":
    train_fashion_mnist(num_workers=2, use_gpu=True)

```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Bye-legumes** [comment]
Hi, There are two potential solutions here:
1. Change ray version to 2.9.0

2.If above doesnt work, can you update to the latest torch_npu and export the env before import torch_npu, i.e.
```
os.environ['ASCEND_RT_VISIBLE_DEVICES'] = "0,1,2,3"
import torch_npu
```

**Comment by lxmanutd** [comment]
> Hi, There are two potential solutions here:
> 
> 1. Change ray version to 2.9.0
> 
> 2.If above doesnt work, can you update to the latest torch_npu and export the env before import torch_npu, i.e.
> 
> ```
> os.environ['ASCEND_RT_VISIBLE_DEVICES'] = "0,1,2,3"
> import torch_npu
> ```

hello， Thanks a lot for your reply!  For solution 1, currently we are using ray version 2.37.0, is that newer that 2.9.0?  and it support NPU in 2.36.0.  For solution 2, if we want to run process in 2 NPU cards, the only thing we need to do is config the  scaling_config = ScalingConfig(num_workers=2, resources_per_worker={"NPU":2}), base "https://docs.ray.io/en/latest/train/user-guides/using-gpus.html",  should we set the ASCEND_RT_VISIBLE_DEVICES env?

**Comment by Bye-legumes** [comment]
> > Hi, There are two potential solutions here:
> > 
> > 1. Change ray version to 2.9.0
> > 
> > 2.If above doesnt work, can you update to the latest torch_npu and export the env before import torch_npu, i.e.
> > ```
> > os.environ['ASCEND_RT_VISIBLE_DEVICES'] = "0,1,2,3"
> > import torch_npu
> > ```
> 
> hello， Thanks a lot for your reply! For solution 1, currently we are using ray version 2.37.0, is that newer that 2.9.0? and it support NPU in 2.36.0. For solution 2, if we want to run process in 2 NPU cards, the only thing we need to do is config the scaling_config = ScalingConfig(num_workers=2, resources_per_worker={"NPU":2}), base "https://docs.ray.io/en/latest/train/user-guides/using-gpus.html", should we set the ASCEND_RT_VISIBLE_DEVICES env?

给我邮箱发一下你微信？我帮你看一下？

**Comment by lxmanutd** [comment]
> > > Hi, There are two potential solutions here:
> > > 
> > > 1. Change ray version to 2.9.0
> > > 
> > > 2.If above doesnt work, can you update to the latest torch_npu and export the env before import torch_npu, i.e.
> > > ```
> > > os.environ['ASCEND_RT_VISIBLE_DEVICES'] = "0,1,2,3"
> > > import torch_npu
> > > ```
> > 
> > 
> > hello， Thanks a lot for your reply! For solution 1, currently we are using ray version 2.37.0, is that newer that 2.9.0? and it support NPU in 2.36.0. For solution 2, if we want to run process in 2 NPU cards, the only thing we need to do is config the scaling_config = ScalingConfig(num_workers=2, resources_per_worker={"NPU":2}), base "https://docs.ray.io/en/latest/train/user-guides/using-gpus.html", should we set the ASCEND_RT_VISIBLE_DEVICES env?
> 
> 给我邮箱发一下你微信？我帮你看一下？

已发，thanks in advance!

**Comment by lxmanutd** [comment]
For model = ray.train.torch.prepare_model(model), seems it only uses device[0], how can we use all the NPUs if each worker has 8 NPUs?
