### ISSUE TITLE
[async] API doesn't work in async tools (e.g. Starlette)

### ISSUE THREAD

**Issue by minimaxir** [ray-project/ray#4856]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14.5
- **Ray installed from (source or binary)**: binary via pip
- **Ray version**: 0.7.0
- **Python version**: 3.7.3
- **Exact command to reproduce**: async_api.init()

### Describe the problem

Per [this line](https://github.com/ray-project/ray/blob/c2c501bbe6e1b57006e2d85811e838c6b50ae4f5/python/ray/experimental/async_api.py#L29), the Async API will throw an exception if an event loop is already running; unfortunately async frameworks like `Starlette` (and some nonasync frameworks like Jupyter Notebooks) start up an event loop by default, and attempting to create a new event loop just for the Async API doesn't work.

If there's a workaround where the API works with Starlette/Jupyter I'd be interested to see it.

**Comment by robertnishihara** [comment]
cc @suquark

**Comment by rkooo567** [comment]
This must be fixed in the latest master. Ray APIs are compatible to Python async APIs
