### ISSUE TITLE
Got failed "grpc_server_request_call": None, when using ray in the docker of ngc24.10

### ISSUE THREAD

**Issue by adoda** [ray-project/ray#48595]
### What happened + What you expected to happen

1. use the docker image by nvidia: nvcr.io/nvidia/pytorch:24.10-py3
2. install ray:  pip install ray[default]
3. start ray: ray start --head
4. execute the common: ray list nodes, then got error:

`ray list nodes
Usage: ray list [OPTIONS] {actors|jobs|placement-
                groups|nodes|workers|tasks|objects|runtime-envs|cluster-
                events}
Try 'ray list --help' for help.

Error: Failed to make request to http://127.0.0.1:8265/api/v0/nodes. Failed to connect to API server. Please check the API server log for details. Make sure dependencies are installed with `pip install ray[default]`. Please also check dashboard is available, and included when starting ray cluster, i.e. `ray start --include-dashboard=True --head`.`

5. we found the error message in dashboard.log:
![image](https://github.com/user-attachments/assets/1e35fdc5-1cb9-4bca-ae81-90abfe61c91c)

![image](https://github.com/user-attachments/assets/5aafa9b2-4c17-4be7-b788-6e1b5cacb7c2)

6. It's ok with docker images ngc24.06, ngc24.07

### Versions / Dependencies

docker: nvcr.io/nvidia/pytorch:24.10-py3
ray[dafault]==2.38.0

### Reproduction script

ray start --head
ray list nodes

### Issue Severity

High: It blocks me from completing my task.

**Comment by adoda** [comment]
I found the third-party library grpcio is corrupted in the docker image: nvcr.io/nvidia/pytorch:24.10-py3
pip3 uninstall grpcio -y

**Comment by rynewang** [comment]
Nice finding!

**Comment by lionkunonly** [comment]
This issue is met in ngc24.0 with ray 1.44.1. Will it be solved in newer version?
