### ISSUE TITLE
Mentioning scopes in TensorFlow layers increases performance significantly

### ISSUE THREAD

**Issue by kirarpit** [ray-project/ray#4861]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.2
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.0
- **Python version**: 3.6.8
- **Exact command to reproduce**: `python scratch.py`

### Describe the problem

I'm not 100% sure if this is a bug or a feature or if it has more to do with TensorFlow than Ray but if the "scope" argument is not mentioned while creating a network layer, then the learning performance of the agent reduces drastically. Please checkout the example below with the "reward_mean" chart.

### Source code

```
import ray
from ray import tune
from ray.rllib.models import Model, ModelCatalog
import tensorflow as tf
from ray.rllib.models.misc import normc_initializer, get_activation_fn


class CustomModel(Model):
    def _build_layers(self, inputs, num_outputs, options):
        import tensorflow.contrib.slim as slim

        hiddens = options.get("fcnet_hiddens")
        activation = get_activation_fn(options.get("fcnet_activation"))

        with tf.name_scope("fc_net"):
            i = 1
            last_layer = inputs
            for size in hiddens:
                label = "fc{}".format(i)
                last_layer = slim.fully_connected(
                    last_layer,
                    size,
                    weights_initializer=normc_initializer(1.0),
                    activation_fn=activation,
                    # scope=label # uncomment this
                )
                i += 1
            label = "fc_out"
            output = slim.fully_connected(
                last_layer,
                num_outputs,
                weights_initializer=normc_initializer(0.01),
                activation_fn=None,
                # scope=label # uncomment this
            )
            return output, last_layer


if not ray.is_initialized():
    ray.init()
ModelCatalog.register_custom_model("custom_model", CustomModel)

tune.run(
    "PPO",
    name="test_scope",
    stop={
        "time_total_s": 60*5,
    },
    config={
        "env": "CartPole-v0",
        "num_workers": 1,
        "model": {
            "custom_model": "custom_model",
        }
    }
)
```

I run the above code twice, once with the "scope" argument commented-out and once commented-in, in the "slim.fully_connected" layers at two places as shown in the code above.

Below is the chart showing average reward obtained by the PPO agent in the two cases. Blue is the case when "scope" argument is not provided and red when it is.

<img width="953" alt="Screenshot 2019-05-25 at 2 08 50 AM" src="https://user-images.githubusercontent.com/4123853/58366838-5a328d00-7e95-11e9-82dc-3e5770730a7f.png">

Any help understanding this behaviour is appreciated. Also, in case this is an expected behaviour, I think it might be worth it to mention it in the docs somewhere so that people don't end up wasting too much time on this.

Thanks!

**Comment by ericl** [comment]
Hmm, it seems this might be a layer reuse issue. My guess is that if you don't specify a scope then the layer reuses variables so all the layers end up sharing the same weights.

Why does this happen with PPO? It would be because the multi GPU optimizer creates models within a scope with auto reuse enabled.
