### ISSUE TITLE
Problem loading weights when testing in a notebook

### ISSUE THREAD

**Issue by pedropla** [ray-project/ray#4863]
### System information
- **OS Platform and Distribution**: Ubuntu with GPU for training Mac for testing
- **Ray installed from (source or binary)**: Pip
- **Ray version**: 0.6.2
- **Python version**: 3.6
- **Exact command to reproduce**: Python code

### Describe the problem

I have a custom model and custom environment which I train on the cloud using a GPU machine and an IMPALA agent. The action space is discrete with only 2 possible actions whereas the observable space is pretty big and a dict.

Once this trained to a satisfactory level on the cloud I downloaded the checkpoint and put together a simple notebook to test it out with exactly the same environment but on my local machine and using a python loop rather than Tune.

If I don't load the weights either by restoring from checkpoint or using set_weights from a pickled weight file then the actions returned are random as could be expected. However, once I load the weights either using agent.restore() or agent.get_policy().set_weights() the action is always the same regardless of of the observation data.

I am wondering if:

a) I am somehow not loading the weights correctly or perhaps not setting up the agent correctly.

b) There is some issue with the weights that were trained on a GPU and are now being used on a CPU.

c) Some other issue?

Are there any examples of taking a trained agent and running it from a python loop?

### Source code / logs

This is what the relevant code from my notebook looks like:

```
import gym, ray
import os
ray.init()

env=MyEnvironment()

from ray.rllib.agents import impala

#set up the agent
config = {"model":{"custom_model": 'MyModel'}}
agent = impala.ImpalaAgent(config=config, env=MyEnvironment)

agent.restore("path_to_checkpoint/checkpoint_xxxx/checkpoint-xxxx")

# also tried loading weights from a pickled file (with proper open, etc)
#with open('path_to_weights_file', 'rb') as weights_file:
#    weights = pickle.load(weights_file)
#agent.get_policy().set_weights(weights)

total_reward = 0
import random
done=False
observation=env.reset()
info = None
reward = None
action = None
while not done:
    action=agent.compute_action(observation)
    observation, reward, done, info = env.step(action)
    if action != 1:
        print ("action: {} reward: {} ".format(action, reward))
    total_reward+=reward
print(total_reward)

```

The print after the if action !=1 never gets called as the action is always 1. This is in contrast to what happens during training where both actions are called as needed.

**Comment by ericl** [comment]
The only difference I can think of is that weights don't include the observation filter, if those are enabled. Is it possible to reproduce this with say Cartpole env?

**Comment by pedropla** [comment]
I will try to create a reproducible project although I'm not sure if it will happen with cartpole as in my case the action space is discrete.

There is one other "strange" thing I've noticed which may or may not provide a clue to this behaviour. When I resume an experiment passing resume=True to tune.run_experiments, the first iteration tends to perform terribly (large negative deviation from saved checkpoint). However, the next and subsequent iterations usually perform within the range of the saved checkpoint.

Is there something that happens between each iteration that could explain this behaviour and which may not be happening when I manually load the weights which makes them not work in the same way they do in training?

**Comment by pedropla** [comment]
Forgot to answer the part about observation filter. I am not using any. The observation dict goes straight to the custom model.
