### ISSUE TITLE
[Core] Wrong return type annotation in ray.util.state.get_actor

### ISSUE THREAD

**Issue by miguelteixeiraa** [ray-project/ray#48694]
### What happened + What you expected to happen

[ray.util.state.get_actor](https://github.com/ray-project/ray/blob/3141dfe4031cc715515b365278cd1d6b8955154e/python/ray/util/state/api.py#L551) has a type annotation specifying that should return an optional[Dict] but it actually returns an Optional[[ActorState](https://github.com/ray-project/ray/blob/3141dfe4031cc715515b365278cd1d6b8955154e/python/ray/util/state/common.py#L416)] as the Docstring mentions.

### Versions / Dependencies

Ray versions that have State API.

### Reproduction script

```py
from time import sleep

import ray
from ray.util import state


ray.init()

@ray.remote
class CounterActor:
    def __init__(self):
        self._counter = 0

    def run(self):
        while True:
            sleep(1)
            self._counter += 1
            print(self._counter)


counter = CounterActor.options(name="named-actor").remote()

while True:
    sleep(1)
    actor = state.get_actor(id=counter._ray_actor_id.hex())
    print(actor.keys())
```
```py
    print(actor.keys())
          ^^^^^^^^^^
AttributeError: 'ActorState' object has no attribute 'keys'
```

### Issue Severity

Low:

**Comment by rynewang** [comment]
Hi @miguelteixeiraa thanks for flagging this! Would you mind contributing to Ray for this issue?
