### ISSUE TITLE
[core] Inconsistent timestamp handling

### ISSUE THREAD

**Issue by rynewang** [ray-project/ray#48760]
### What happened + What you expected to happen

`gcs::CreateErrorTableData` takes a `double timestamp`.

Here it takes milliseconds from std clock:
https://github.com/ray-project/ray/blob/d4e266003b08c221dbd5d47e3df21c07bfed84b2/src/ray/raylet/node_manager.cc#L2177

Here it takes nanoseconds from absl:
https://github.com/ray-project/ray/blob/d4e266003b08c221dbd5d47e3df21c07bfed84b2/src/ray/gcs/gcs_server/gcs_actor_manager.cc#L755

We need to:
1. figure out it takes ms or ns
2. fix by changing arg to absl::Time

### Versions / Dependencies

master

### Reproduction script

-

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by dentiny** [comment]
Reading through the initial PR (https://github.com/ray-project/ray/pull/2256/files), the unit is actually seconds.

**Comment by dentiny** [comment]
Then refactored to protobuf in https://github.com/ray-project/ray/pull/5024.
