### ISSUE TITLE
[docs]Is there any Chinese docs?

### ISSUE THREAD

**Issue by Hatuw** [ray-project/ray#4876]
What a excellent project!
I hope to translate the docs to Chinese or other languages. Is there any guide to contribute about the docs?
Btw, I think it would be better to separate "Ray Documentation" as a project : )

**Comment by robertnishihara** [comment]
Thanks @Hatuw, currently all of the documentation is under `ray/doc`. We want to keep it there so that it's easier to keep in sync with the rest of the code.

Currently we don't have any guidelines for contributing documentation. Can you share some examples of projects that have good documentation contribution guidelines?

**Comment by Hatuw** [comment]
@robertnishihara 

Aye. I think it is better to keep the docs under `ray/doc`. You can create some blank projects (eg. `ray/cn_doc`) under the ray project. Anyone who want to contribute the project can submit a PR~

(just like the [keras-team](https://github.com/keras-team))

**Comment by Senmumu** [comment]
hi guys, I'm translating the latest doc to Chinese version, and here is the link-> [link](https://github.com/Senmumu/ray_project_doc).  please consider adding this Chinese version when we finish this job.

**Comment by richardliaw** [comment]
Let me make a repo.

**Comment by richardliaw** [comment]
cc @senmumu https://github.com/ray-project/ray-docs-zh

**Comment by Senmumu** [comment]
> cc @Senmumu https://github.com/ray-project/ray-docs-zh

got it.

**Comment by Hatuw** [comment]
Great! This issue should be closed~

**Comment by richardliaw** [comment]
Thanks - please open a PR against the above repo when ready!

**Comment by Senmumu** [comment]
> Thanks - please open a PR against the above repo when ready!

sure.
