### ISSUE TITLE
[rllib] Distributed learning constantly crashing due to memory

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#4877]
Hi, I keep on getting memory error crashes. This happens with both, my own implementations as well as the pre-defined rl-experiments. I have 16 GB of RAM available:

```
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node Local is used (15.98 / 16.82 GB). The top 5 memory consumers are:

PID	MEM	COMMAND
4758	7.3GB	ray_ImpalaTrainer:train()
5113	4.5GB	ray_PolicyEvaluator
4753	4.5GB	ray_PolicyEvaluator:apply()
4761	4.49GB	ray_PolicyEvaluator:apply()
4756	4.49GB	ray_PolicyEvaluator:apply()

In addition, ~4.24 GB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`.
```

How can I fix this?

I'm also surprised by the large amount of memory used by each of the workers. In my own implementation I made sure that it never holds much memory. Why on earth are the individual worker RAM usages slowly growing all the time?

Note 1: I DID obviously try to reduce the object_store_memory to something smaller, but eventually the workers all grow too large in RAM usage and it crashes anyways.

Note 2: For the above output I was using the `rllib train -f pong-speedrun/pong-impala-fast.yaml` example, except I adapted it for 8 workers.

**Comment by ericl** [comment]
Are you using Ray < 0.7.0? Memory management is much improved since then due to: https://github.com/ray-project/ray/pull/4586

For example, I just tried running `rllib train -f pong.yaml --ray-object-store-memory=500000000` and after 1m timesteps it's still at <5G total: 

```
top - 00:48:38 up 24 min,  2 users,  load average: 8.44, 8.62, 5.49
Tasks: 636 total,   7 running, 629 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.6 us,  0.2 sy,  0.0 ni, 88.9 id,  0.3 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 50360921+total, 48268070+free, 16585828 used,  4342684 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 48489433+avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                      
 37102 ubuntu    20   0  0.495t 3.341g 993296 S  30.7  0.7   2:06.12 ray_ImpalaTrain              
 37100 ubuntu    20   0 3331620 902448 666000 R  79.5  0.2   5:16.87 ray_PolicyEvalu              
 37109 ubuntu    20   0 3331676 901556 665084 R  76.9  0.2   5:17.28 ray_PolicyEvalu              
 37118 ubuntu    20   0 3329556 900556 664124 R  76.9  0.2   5:16.79 ray_PolicyEvalu              
 37096 ubuntu    20   0 3331496 900320 663996 R  91.4  0.2   5:16.53 ray_PolicyEvalu              
 37116 ubuntu    20   0 3335716 900316 665904 S  96.0  0.2   5:15.77 ray_PolicyEvalu              
 37099 ubuntu    20   0 3329580 900084 663628 S  86.8  0.2   5:12.94 ray_PolicyEvalu              
 37119 ubuntu    20   0 3331552 899936 663508 R  82.2  0.2   5:15.39 ray_PolicyEvalu              
 37094 ubuntu    20   0 3333972 898996 664312 R  97.4  0.2   5:16.04 ray_PolicyEvalu              
```

> I'm also surprised by the large amount of memory used by each of the workers.

This is somewhat misleading the RSS value includes the object store shared memory (I would subtract out 4.2G from each). That doesn't explain why you ran out of memory, but object store + workers + tensorflow can add up, especially if not all 16G was available starting off.

**Comment by NikEyX** [comment]
Ok thanks for the explanation with regards to the memory used by workers.

I am using Ray Version 0.7.0 unfortunately, so probably looks like something different going on. Is there anything I can run on my end to help debug this issue? Any outputs I can provide you with?

**Comment by ericl** [comment]
Hm, could you provide a reproduction command with the yaml attached? Also,
it might be useful to know the TensorFlow version and so on.

**Comment by NikEyX** [comment]
Ok, I will provide this soon. In the meantime, is there any way to output the memory used by a worker at any given point? This could help me pin-point the issue. 

e.g. how can I get this output programmatically for each worker while running the code:

PID	MEM	COMMAND
4758	7.3GB	ray_ImpalaTrainer:train()
5113	4.5GB	ray_PolicyEvaluator

**Comment by ericl** [comment]
You can use the 'top' command and sort by memory by hitting 'M' (or any
other os memory monitor). The code for that is also in memory_monitor.py

**Comment by NikEyX** [comment]
I managed to create a small script for you that successfully replicates the issue and doesn't make any use of TensorFlow or PyTorch:

```
import psutil
import numpy as np
import ray
import time

PARAMETER_SIZE = 100000

ray.init()

@ray.remote
class ParameterServer(object):
    def __init__(self):
        self.params = np.zeros(PARAMETER_SIZE)

    def get_params(self):
        return self.params

    def update_params(self, grad):
        self.params += grad


@ray.remote
class Worker():
    def __init__(self, ps):
        self.ps = ps

    def RunEpisode(self):
        # we don't need the parameters, this is just to illustrate
        parameters = ray.get(self.ps.get_params.remote())

        grad = np.random.randn(PARAMETER_SIZE)

        self.ps.update_params.remote(grad)


parameter_server = ParameterServer.remote()
workers = [ Worker.remote(parameter_server) for _ in range(8)]

lastMemory = 0
lastPrint = 0
while True:
    runEpisodes = [ worker.RunEpisode.remote() for worker in workers ]

    ray.get(runEpisodes)
    ray.get(parameter_server.get_params.remote())

    if (time.time() - 1 > lastPrint):
        total_gb = psutil.virtual_memory().total / 1e9
        used_gb = total_gb - psutil.virtual_memory().available / 1e9

        print(f'Memory usage is {used_gb:.4f} / {total_gb:.4f} = {used_gb - lastMemory:+.4f}')

        lastMemory = used_gb
        lastPrint = time.time()
```

The output is as follows:

```
Memory usage is 7.1262 / 16.8164 = +7.1262
Memory usage is 7.8350 / 16.8164 = +0.7088
Memory usage is 8.5215 / 16.8164 = +0.6864
Memory usage is 9.1583 / 16.8164 = +0.6369
Memory usage is 9.7822 / 16.8164 = +0.6239
Memory usage is 10.3920 / 16.8164 = +0.6098
Memory usage is 11.0299 / 16.8164 = +0.6379
Memory usage is 11.7228 / 16.8164 = +0.6929
Memory usage is 12.2452 / 16.8164 = +0.5224
Memory usage is 12.2513 / 16.8164 = +0.0061
Memory usage is 12.2615 / 16.8164 = +0.0103
Memory usage is 12.2662 / 16.8164 = +0.0046
Memory usage is 12.2719 / 16.8164 = +0.0058
Memory usage is 12.2768 / 16.8164 = +0.0049
Memory usage is 12.2807 / 16.8164 = +0.0039
........................
Memory usage is 15.9316 / 16.8164 = +0.0005
Memory usage is 15.9335 / 16.8164 = +0.0019
Memory usage is 15.9373 / 16.8164 = +0.0038
Memory usage is 15.9401 / 16.8164 = +0.0028
Memory usage is 15.9436 / 16.8164 = +0.0035
Memory usage is 15.9476 / 16.8164 = +0.0040
Memory usage is 15.9499 / 16.8164 = +0.0024
Memory usage is 15.9558 / 16.8164 = +0.0059
Memory usage is 15.9603 / 16.8164 = +0.0045
Memory usage is 15.9670 / 16.8164 = +0.0068
Memory usage is 15.9724 / 16.8164 = +0.0054
Memory usage is 15.9708 / 16.8164 = -0.0016
Memory usage is 15.9756 / 16.8164 = +0.0048
Traceback (most recent call last):
  File "/home/XXXXX/Projects/memoryTest.py", line 45, in <module>
    ray.get(runEpisodes)
  File "/home/XXXXX/.local/lib/python3.7/site-packages/ray/worker.py", line 2197, in get
    raise value
ray.exceptions.RayTaskError: ray_Worker:RunEpisode() (pid=23262, host=Local)
  File "/home/XXXXX/.local/lib/python3.7/site-packages/ray/memory_monitor.py", line 77, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node Local is used (15.98 / 16.82 GB). The top 5 memory consumers are:

PID	MEM	COMMAND
23256	5.22GB	ray_ParameterServer
23249	5.2GB	ray_Worker
23259	5.2GB	ray_Worker:RunEpisode()
23254	5.2GB	ray_Worker
23250	5.2GB	ray_Worker:RunEpisode()

In addition, ~5.3 GB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`.
```

Can you confirm this happens to you as well? All memory should be released after RunEpisode has executed, so why does the memory keep on increasing?

**Comment by ericl** [comment]
That's actually expected unless you restrict the object store size. It
seems you started off with 7GB memory used, which explains why you run out
(Ray assumes it always can allocate 100% of the machine memory to itself by
default). Can you reproduce with object store memory limited to say 500MB?

Also note that RLlib uses rllib.utils.ray_get_and_free() to optimize its
internal memory usage by explicitly freeing memory, which isn't done in
this example.

Eric

**Comment by NikEyX** [comment]
Hi Eric,

Thanks for the prompt replies, really appreciate it.

I got two questions on that:

1) Isn't it quite an aggressive assumption of ray.init() to think it can get 100% of all machine memory? Most people who try Ray would certainly start with some fraction of RAM being in use, and this would eventually lead to a crash?
2) How come Ray keeps on adding memory? The code I wrote above has no lingering objects besides the original ParameterServer and the Workers. And the only variable that's being updated, is edited in-place. There shouldn't be anything that leads to consistent increase in memory. Everything should be freed by the garbage collection? Do I need to use rllib.utils.ray_get_and_free() for that purpose? I was kinda hoping that this would be done automatically and that I wouldn't need to rely on an rllib helper function. (If anything shouldn't that be part of ray directly?)
3) Can I ask why RLLib and Tune are part of Ray to begin with? It seems like they should be separate projects. I see Ray as replacement for multiprocessing only, since I have my own RL library that I prefer to use for my projects.

While I typed this up the code above ended up using more than 1 GB of memory, despite setting the object_store_memory to 500mb. Anything else I should try?
```
2019-05-28 20:10:21,724	INFO services.py:1441 -- Starting the Plasma object store with 0.5 GB memory using /dev/shm.
Ray Version: 0.7.0
Memory usage is 6.9679 / 16.8164 = +6.9679
Memory usage is 7.4013 / 16.8164 = +0.4334
Memory usage is 7.4054 / 16.8164 = +0.0041
Memory usage is 7.4064 / 16.8164 = +0.0010
Memory usage is 7.4715 / 16.8164 = +0.0651
Memory usage is 7.4727 / 16.8164 = +0.0012
Memory usage is 7.4737 / 16.8164 = +0.0010
Memory usage is 7.4763 / 16.8164 = +0.0026
Memory usage is 7.4770 / 16.8164 = +0.0007
....................................
Memory usage is 7.9929 / 16.8164 = +0.0000
Memory usage is 7.9933 / 16.8164 = +0.0005
Memory usage is 7.9936 / 16.8164 = +0.0002
Memory usage is 7.9938 / 16.8164 = +0.0002
Memory usage is 7.9938 / 16.8164 = +0.0000
Memory usage is 7.9940 / 16.8164 = +0.0002
Memory usage is 7.9958 / 16.8164 = +0.0018
Memory usage is 7.9963 / 16.8164 = +0.0005
Memory usage is 7.9966 / 16.8164 = +0.0003
Memory usage is 7.9968 / 16.8164 = +0.0002
Memory usage is 7.9973 / 16.8164 = +0.0005
Memory usage is 8.0061 / 16.8164 = +0.0088
Memory usage is 8.0112 / 16.8164 = +0.0051
Memory usage is 8.0165 / 16.8164 = +0.0052
Memory usage is 8.0134 / 16.8164 = -0.0031
Memory usage is 8.0138 / 16.8164 = +0.0004
Memory usage is 8.0139 / 16.8164 = +0.0001
Memory usage is 8.0104 / 16.8164 = -0.0035
Memory usage is 8.0083 / 16.8164 = -0.0020
Memory usage is 8.0112 / 16.8164 = +0.0028
Memory usage is 8.0219 / 16.8164 = +0.0107
Memory usage is 8.0228 / 16.8164 = +0.0009
Memory usage is 8.0246 / 16.8164 = +0.0018
Memory usage is 8.0254 / 16.8164 = +0.0008
```

And here TOP:

![image](https://user-images.githubusercontent.com/23219722/58520758-5b123a00-8187-11e9-8e01-de45589d671c.png)

**Comment by ericl** [comment]
Your run looks pretty good. I would expect some extra memory used by python
/ TensorFlow which accounts for the bit if extra overhead.

1. I agree, we should take account other applications using memory. The
original design assumed dedicated machines / containers running ray, which
isn't always the case.

2. Ray won't free memory until the object store limit is reached. This is
both since from it's perspective no one else is using the memory, and also
in the distributed setting it becomes difficult to determine which objects
are in use.

3. From a project perspective its easier to manage releases this way. That
said we are thinking of reorganizing the packages to make installation a
bit more modular.

**Comment by NikEyX** [comment]
Ok, thanks for your answers.

Is it possible to pre-reserve the memory used by Ray? That way the program would be unaffected from me doing other RAM intensive things. At a minimum I want the program to continue operating instead of crashing, so pre-allocating the memory would help.

**Comment by ericl** [comment]
Yes, one way to so this is to run a loop like this early in your program. This does take some time:

```
for x in range(1000):
   ray.put(1024*1024*100)
```

**Comment by NikEyX** [comment]
Thank you
