### ISSUE TITLE
Release test golden_notebook_torch_tune_serve_test.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#48773]
Release test **golden_notebook_torch_tune_serve_test.aws** failed. See https://buildkite.com/ray-project/release/builds/26154#01933934-00a4-4ebc-bbaf-7ab3ff697121 for more details.

Managed by OSS Test Policy

**Comment by aslonnie** [comment]
failing due to gpu shortage.

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.
