### ISSUE TITLE
[dashboard/core?] Disk space displayed in dashboard doesn't match size of disk.

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#48783]
### What happened + What you expected to happen

When setting `temp-dir` to a value on head it doesn't seem to be reflected in dashboard.

```
ray start --head --dashboard-host=0.0.0.0 --metrics-export-port=8090 --temp-dir=/path/bigdisk/temp
```

on worker it's started like this:

```
ray start --address="ray_head:${RAY_REDIS_PORT}"
```

The dashboard shows this

![image](https://github.com/user-attachments/assets/483f7420-adec-4218-90f6-9f7fd75d14f2)

The first line is the head node, the second is a worker node. Both are run in container in working directories volumes mounted to 10TB size disks. Why is the head showing only 50GB. That's the size of `/` on the host, which it shouldn't have access to.

### Versions / Dependencies

ray 2.37
also same on 2.39

### Reproduction script

```
ray start --head --dashboard-host=0.0.0.0 --metrics-export-port=8090 --temp-dir=/path/bigdisk/temp
```

look at dashboard

### Issue Severity

High: It blocks me from completing my task.

**Comment by gitlijian** [comment]
hi , @Joshuaalbert

**Comment by Joshuaalbert** [comment]
Another useful info: the head and worker docker storage drivers are different between the two nodes. On the head node it is using overlay2 (which is kernel space), and on the worker fuse-overlay (which is user space). When I updated the storage driver on the head node to fuse-overlay it started showing the correct storage size.

**Comment by Joshuaalbert** [comment]
Since his was solved by updating the overlay driver I close

**Comment by SaumyaAtLyric** [comment]
This is technically still an open issue right? The dashboard monitoring the `/` path and not the one passed in `--temp-dir`
