### ISSUE TITLE
[tune] Make PBT Quantile fraction configurable

### ISSUE THREAD

**Issue by timonbimon** [ray-project/ray#4881]
### Describe the problem

Currently PBT has the quantile fraction hardcoded to 25% (that is trials from the top 25% get transferred to the bottom 25%). 
It would be nice if this is configurable.

I have been bothering you guys with comments/issues for a while, so I'd be happy to use this as my first issue to contribute, if there are no objections from you guys or any reasons you see that this should not be configurable. :)

**Comment by richardliaw** [comment]
Yes! Feel free to contribute this. This would be good!
