### ISSUE TITLE
ValueError: Registry value for rllib_model/carla doesn't exist.

### ISSUE THREAD

**Issue by Deepak3994** [ray-project/ray#4882]
Hi,

I am trying to run rollout script on the trained carla model for some scenario. But i am getting the error as "ValueError: Registry value for rllib_model/carla doesn't exist". May i know what actually the problem is and why i am getting this error and how to resolve.

Kindly help.

**Comment by ericl** [comment]
Did you register them in the script? https://github.com/ray-project/ray/blob/master/python/ray/rllib/rollout.py#L33

**Comment by Deepak3994** [comment]
Yes @ericl 

I have registered my environment and have given the id as Carla-v0. When i check for registered gym environments using the python lines "from gym import envs; print(envs.registry.all())", it shows my environment id which i have registered.

**Comment by ericl** [comment]
Well first, the environment registration process is different with RLlib, as documented here: https://ray.readthedocs.io/en/latest/rllib-env.html

But regardless of that, I meant registering the model, not the env. See the comment in the script I linked above.

**Comment by Deepak3994** [comment]
@ericl 

Yes, I have done both the model registration as "ModelCatalog.register_custom_model("carla", CarlaModel)" and environment registration as "register_env("CarlaEnv", lambda _: CarlaEnv)".

**Comment by wangshuo1994** [comment]
@Deepak3994 Hi, have you solved the problem now? I am facing the same problem when I want to reproduce my RL training results through the checkpoint... Thank you.

**Comment by Forbu** [comment]
@wangshuo1994 Hi, I also have the same issue.

**Comment by Forbu** [comment]
Ok I just solve it ... The issue was that we have to make the register call in the ray session (between ray.init() and ray.shutdown())
