### ISSUE TITLE
Release test rllib_learning_tests_pong_appo_torch.aws failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#48842]
Release test **rllib_learning_tests_pong_appo_torch.aws** failed. See https://buildkite.com/ray-project/release/builds/26517#01934d7c-e1a2-4656-8598-ad9c5ef73483 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: 05915c1b389ab0bada23217a3cb2768311d1184b found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1765

**Comment by aslonnie** [comment]
should be fixed by https://github.com/ray-project/ray/pull/48869

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/26725#019357ee-c6df-4989-aabb-56b6039a1a52
