### ISSUE TITLE
ray stop on a node while running cause slowness

### ISSUE THREAD

**Issue by NirZarrabi** [ray-project/ray#4888]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.0
- **Python version**: 2.7
- **Exact command to reproduce**:

### Describe the problem

 if I can use ray in my code using a cluster I tried to parallelize a function on multiple nodes and stoping one of the nodes while running. This cause the run to be very slow in comparison to the regular case where no nose is stopped in the middle. That is, I want to be able to run a function on a pool of workers and disconnect\connect a node while running hoping ray can handle it. When testing this with a simple loop this causes the loop to get really really slow (but not to crash).

### Source code / logs

I started by writing on the main node:

`$ ray start --head --redis-port=6379`
Then, I connect 3 other nodes by:

`$ ray start --redis-address=HEAD_IP:6379`

so far so good. Now if I log in to python with one of the nodes and running the following code everything works as expected:
```
import ray
import time
import tqdm

ray.init(redis_address="IP:PORT")

@ray.remote
def f(i):
    time.sleep(1.0)
    return [ray.services.get_node_ip_address(), i]

res = []
workers = [f.remote(i) for i in range(1000)]
for w in tqdm(workers):
    res.append(ray.get(w))
print set([r[0] for r in res])
```
This code will run on my cluster in about 10 seconds.

Now, if I re-run the above code, but while running I stop a node by

`$ ray stop`
the loop will take a lot of time (as if I run it on a single core).

What am I missing? can I disconnect and connect nodes while running? 

Thanks

**Comment by rkooo567** [comment]
I think it makes sense because you'll lose one of the nodes for computation. Please reopen if there's anything we should address!
