### ISSUE TITLE
Passing big objects back to master process

### ISSUE THREAD

**Issue by neychev** [ray-project/ray#4889]
What if worker process need to pass some information back to the master and it is really big? (e.g. prediction on test dataset to use in further or returning the trained model to the master to construct the ensemble).

I have found two ways to do that:
1. Using the `reporter` API: just add corresponding argument to the reported and then retrieve the necessary information from the `trials` object. Such approach seems to me like a crunch.
In addition, it consumes the disc space, because the reporter output is being logged.
2. Using `pin_in_object_store` method. It has two main disadvantages:
1.1. The objects are stored in the memory till the ray process stops. Can be bypassed by https://github.com/ray-project/ray/issues/4512
1.2. One should be very careful using `pin_in_object_store` with trained models. The code below illustrates the issue: xgboost model is broken after loading (correct variant to do that is commented).

Example code:
```
import numpy as np

import ray
from ray.tune.util import pin_in_object_store, get_pinned_object

import xgboost as xgb


ray.init()

data = np.random.randint(-100, 100, (100, 20))
target = np.random.randint(-10, 10, (100, 1))
dmatrix = xgb.DMatrix(data=data, label=target)

test_data = np.random.randint(-100, 100, (10, 20))
test_dmatrix = xgb.DMatrix(data=test_data)

model = xgb.train(params={'eval_metric': 'rmse', 'objective': 'reg:linear'}, dtrain=dmatrix)

model.predict(test_dmatrix)

model_id = pin_in_object_store(model)

restored_model = get_pinned_object(model_id)

assert type(model) == type(restored_model)
restored_model.predict(test_dmatrix)

# Right variant to save the model:
# raw_model_id = pin_in_object_store(model.save_raw())
# new_model = xgb.Booster()
# new_model.load_model(get_pinned_object(raw_model_id))
# new_model.predict(test_dmatrix)
```

**Comment by pcmoritz** [comment]
@neychev Have you considered just using `ray.put` instead of `pin_in_object_store`? That will place it into the object store, but not pin it, which means it will get evicted from the store if it runs out of capacity. In this case you need to make sure that the object store is large enough to hold all the models for long enough (you can control the object store size with the `object_store_memory` parameter to `ray.init`).

**Comment by neychev** [comment]
Thanks. Maybe this should be added to the docs?

**Comment by rkooo567** [comment]
You can use ray.put, and the object lifetime is automatically managed by Ray (by distributed reference counting protocol).
