### ISSUE TITLE
[data] sort() does not work with string column with None

### ISSUE THREAD

**Issue by wingkitlee0** [ray-project/ray#48927]
### What happened + What you expected to happen

When applying `sort()` on a string column with `None`, it will raise the following error
```
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

### Versions / Dependencies

```
In [21]: ray.__version__
Out[21]: '2.39.0'
```

### Reproduction script

```
In [17]: df = pd.DataFrame({"x": [None, None, "a", "c", None]})

In [18]: df.sort_values(by="x")
Out[18]:
      x
2     a
3     c
0  None
1  None
4  None

In [19]: ds = ray.data.from_pandas(df)

In [20]: ds.sort("x").take_all()
```
gives an error. However, `pandas` Dataframe works.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by alexeykudinkin** [comment]
This should be fixed by https://github.com/ray-project/ray/pull/48750
