### ISSUE TITLE
[data][DataSink] allow passing write results to on_write_complete

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#48933]
Context https://github.com/ray-project/ray/pull/47942#issuecomment-2496067681

**Comment by chenkovsky** [comment]
@raulchen could you please help to review thir pr.

**Comment by kukushking** [comment]
Bumping this issue. Our code also depended on write output being available in on_write_completes (in our case just an filename of the written block - if there is more straightforward way to get output filenames lmk).

**Comment by kukushking** [comment]
Hi @raulchen is there any ETA for a release that includes this change?

**Comment by raulchen** [comment]
@kukushking it should be released in one week or two. there are still a few release blockers that need to be addressed.
