### ISSUE TITLE
Search algorithm for Random Search over hyperparameter space?

### ISSUE THREAD

**Issue by JuliusSchwartz** [ray-project/ray#4901]
### System information
- **Linux Ubuntu 18.04)**:

I'm using ray.tune with to optimise hyper-parameters for large neural network models. I have a mixture of discrete hyper-parameters (e.g. layer size) and continuous hyper-parameters (e.g. learning_rate). For parameters like layer size I have a predefined array of options ([64, 128, 512, 1024...]) for each layer. I'd like to be able to sample n random configurations from my hyper-parameter space and then use ASHA to schedule trials but I can't find any  method/module that does this.

**Comment by richardliaw** [comment]
I think you're looking for this? https://ray.readthedocs.io/en/latest/tune-usage.html#tune-search-space-default

This should support mixing continuous and discrete random searches.
