### ISSUE TITLE
[data] Torch to Ray dataset transform

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/ray#49040]
### Description

Implement a feature into the Ray Data API allowing torch datasets to ray dataset transformation.

### Use case

Code Example:
```
dataset = MyCustomTorchDataset(...)
ray_dataset = ray.data.from_torchdataset(dataset)
```

_No response_

**Comment by richardliaw** [comment]
Hi @peterghaddad we already have something here -- https://docs.ray.io/en/latest/data/api/doc/ray.data.from_torch.html
