### ISSUE TITLE
[data] Integrate the function of "withColumn" into the dataset. 

### ISSUE THREAD

**Issue by Jay-ju** [ray-project/ray#49063]
### Description

During the data processing, there are numerous operations to generate new label columns based on the existing ones. Therefore, it is hoped that an interface similar to withColumn in Spark can be provided here: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.withColumn.html

### Use case
```
DataSet.withColumn(self,
        value_func: Callable[[pa.RecordBatch], pa.RecordBatch],
        columns: Optional[list[str]] = None,
        batch_size: Optional[int] = None,
        reader_schema: Optional[pa.Schema] = None,)
```

**Comment by richardliaw** [comment]
Why do you need to do this in the datasource? 

We already have a `dataset.add_columns` API right?

https://docs.ray.io/en/latest/data/api/doc/ray.data.Dataset.add_column.html

**Comment by Jay-ju** [comment]
I'm aware of this api. However, I'd like to put this "add_column" into the interface of the data source, because we need to utilize the ability of the data source to merge columns, such as lance.merge_columns()

**Comment by richardliaw** [comment]
Could you show an example of things you'd want to do with the lance package?

**Comment by richardliaw** [comment]
Sorry, still not following. Especially this part:

>  If this is put into the "add_column" function in the dataset ... the entire table has to be rewritten. 

If you do something like:

```
ds = ray.data.read_lance(...)
ds.add_column("is_big_picture", lambda df: df["height"] && df["height"])
```

The underlying Lance table is not touched.

**Comment by Jay-ju** [comment]
> Sorry, still not following. Especially this part:
> 
> > If this is put into the "add_column" function in the dataset ... the entire table has to be rewritten.
> 
> If you do something like:
> 
> ```
> ds = ray.data.read_lance(...)
> ds.add_column("is_big_picture", lambda df: df["height"] && df["height"])
> ```
> 
> The underlying Lance table is not touched.

Yes. The newly added columns are only in the dataset (ds). If you want to reflect them in the Lance table, you need to use "insert overwrite" for the entire table.  this cost is too expensive. 
So here, it is hoped that when calling add_column, it is directly calling datasource.add_column.
```
lance_source = LanceDatasource("s3://lance_dataset/")
# read_datasource is executing readTask
ds = ray.data.read_datasource(source)
# add_column is executing addColumnTask
ds = ds.add_column()
```

**Comment by richardliaw** [comment]
this seems a little bit odd to be doing it in the readsource, but I can see
what you are doing.

Can you share a full rated script with me for what you’re trying to do?

**Comment by Jay-ju** [comment]
![image](https://github.com/user-attachments/assets/d313d727-77f4-4cc8-9950-5aaa969c04fc)
Similar to the implementation method in the figure, but want to package this implementation logic into the datasource instead of writing a map function externally.

**Comment by Jay-ju** [comment]
I have submitted the general implementation to https://github.com/ray-project/ray/pull/49070. Please help take a look.

**Comment by richardliaw** [comment]
Hi @Jay-ju - I don't think this is something we'd want to support. The main programming model for Ray Data is to do large scale data-processing in-memory, not necessarily to be a distributed LanceDB client.

I think the screenshot of what you've shared is actually the right way to use Ray Data, and not push any of the functionality into the library.

cc @alexeykudinkin @bveeramani if you have any more thoughts.

**Comment by Jay-ju** [comment]
> Hi @Jay-ju - I don't think this is something we'd want to support. The main programming model for Ray Data is to do large scale data-processing in-memory, not necessarily to be a distributed LanceDB client.Hi @Jay-ju - I don't think this is something we'd want to support. The main programming model for Ray Data is to do large scale data-processing in-memory, not necessarily to be a distributed LanceDB client.嗨 @Jay - 我不认为这是我们想要支持的事情。Ray Data 的主要编程模型是在内存中进行大规模数据处理，而不一定是分布式 LanceDB 客户端。
> 
> I think the screenshot of what you've shared is actually the right way to use Ray Data, and not push any of the functionality into the library.I think the screenshot of what you've shared is actually the right way to use Ray Data, and not push any of the functionality into the library.我认为您分享的内容的屏幕截图实际上是使用 Ray Data 的正确方式，而不是将任何功能推送到库中。
> 
> cc @alexeykudinkin @bveeramani if you have any more thoughts.cc @alexeykudinkin @bveeramani if you have any more thoughts.如果您还有其他想法，请@alexeykudinkin @bveeramani。

Here I would like to explain that this provides not only interfaces for Lance. For example, for Iceberg, there is also distributed processing of data sources in a distributed manner. 
Here, it provides a distributed execution logic for add_columns, update, delete, and compaction in addition to read/write for data sources. Instead of having to rewrite actors every time, there is too much repetitive content here.
 Personally, I think it should be abstracted. What do you think?

**Comment by richardliaw** [comment]
Here I think we'll probably not take the contribution at this time.

**Comment by Jay-ju** [comment]
> Here I think we'll probably not take the contribution at this time.

ok, i will close it here
