### ISSUE TITLE
Making default logging prefix more concise

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#4906]
Right now, we have `2019-05-30 11:34:42,798	WARNING`.

Would it be possible to shorten this? Something like:
```
        formatter = logging.Formatter(
            fmt="[%(levelname)s %(asctime)s],
            datefmt="%m-%d %H:%M:%S",
        )
```
This will look like `[WARNING 05-16 12:03:29]`. This saves about 8 characters.

cc @robertnishihara @pcmoritz.

**Comment by FedericoFontana** [comment]
levelname might correspond to a variable number of characters, thus the timestamp will not be aligned. This is a way to say that `[05-16 12:03:29 WARNING]` might be better than `[WARNING 05-16 12:03:29]`.

That being said, `05-16` in your example is not very clear to me (I'm from Europe). I like the square brackets but I would keep the millisecond.

I would favor readability over conciseness.

**Comment by robertnishihara** [comment]
I agree the square brackets are a nice touch, and I agree that readability is very important.
