### ISSUE TITLE
[RLlib] New API stack is enabled by default, but "New API stack migration guide" says the opposite

### ISSUE THREAD

**Issue by ema-pe** [ray-project/ray#49076]
### Description

Hi, I'm using Ray RLlib 2.40.0 and the new API stack is enabled by default, but the documentation web page "New API stack migration guide" in the "Change your AlgorithmConfig" section says that "RLlib turns off the new API stack by default for all RLlib algorithms", see the attached screenshot and code:

https://github.com/ray-project/ray/blob/22541c38dbef25286cd6d19f1c151bf4fd62f2ed/rllib/algorithms/algorithm_config.py#L417-L423

![1](https://github.com/user-attachments/assets/ae652aa1-274d-41e8-9df6-4b2daada19d9)

I think the documentation is wrong and out of date.

### Link

https://docs.ray.io/en/releases-2.40.0/rllib/new-api-stack-migration-guide.html#change-your-algorithmconfig

**Comment by simonsays1980** [comment]
@ema-pe thanks for raising this issue. You are right. We changed lately the default to the new API stack and forgot to change the docs accordingly. Great catch!
