### ISSUE TITLE
Release test compiled_graphs failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#49095]
Release test **compiled_graphs** failed. See https://buildkite.com/ray-project/release/builds/27435#019395a5-3e72-47f1-b2ea-ffad316459e9 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Blamed commit: dfb5800bc30366ebb0805a47f904c9c79b2b3501 found by bisect job https://buildkite.com/ray-project/release-tests-bisect/builds/1814

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by ruisearch42** [comment]
Fixed in https://github.com/ray-project/ray/pull/49177

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/27725#0193af4c-15f7-48bb-b80e-7e1c56e7dbde
