### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>] A metric name has a spelling error

### ISSUE THREAD

**Issue by wmy-dev** [ray-project/ray#49102]
### What happened + What you expected to happen

After getting the metrics of ray, I found a typo.
The spelling error of environment in 'ray_internal_num_processes_skipped_runtime_enviornment_mismatch_total'.

### Versions / Dependencies

2.38.0

### Reproduction script

You can get this metric by using `curl ${IP}:${--metrics-export-port}/metrics`.

### Issue Severity

None

**Comment by jjyao** [comment]
@wmy-dev a fix PR is very much welcomed :)
