### ISSUE TITLE
[Data] Ray 2.40 `add_column` Erroneous Assertion

### ISSUE THREAD

**Issue by ivanthewebber** [ray-project/ray#49114]
### What happened + What you expected to happen

Ray 2.40 introduces an assertion that a value is of type `pd.Series`, but this is erroneous. A dataframe may have a constant assigned as in the following example or be a geopandas series (which should subclass).

```python
>>> import pandas as pd
>>>
>>> # Create a sample DataFrame
...     "A": [1, 2, 3],
...     "B": [4, 5, 6]
... })
>>>
>>> # Assign a constant value to a new column "C"
>>> df["C"] = 10
>>>
>>> print(df)
   A  B   C
0  1  4  10
1  2  5  10
2  3  6  10
>>>
```

As a result of the change valid expressions like:
```python
q_ds = q_ds.add_column("_q", lambda _: True)
s_ds = s_ds.add_column("_q", lambda _: False)
```
no longer succeed.

### Versions / Dependencies

Ray 2.40

### Reproduction script
```python
import pandas as pd
import ray

df= pd.DataFrame({"geometry": [1, 2, 3]})

# Create Ray datasets
ds = ray.data.from_pandas(df)

ds = ds.add_column("works", lambda _: True)
ds = ds.add_column("works", lambda _: True)

# evaluates and fails
ds.materialize()
ds.show()
```
### Issue Severity

Low: It annoys or frustrates me.

**Comment by ivanthewebber** [comment]
Here is another issue with the function update; the [docstring says columns may be overridden](https://github.com/ray-project/ray/blob/8fe05532e7037aac1b9b3755f0053047dc0f1321/python/ray/data/dataset.py#L743C13-L744C39), but there is a [check raising an error if the column already exists](https://github.com/ray-project/ray/blob/8fe05532e7037aac1b9b3755f0053047dc0f1321/python/ray/data/dataset.py#L780C17-L781C55).

As a side note, after using `add_column` you can no longer get the `ds.columns()` without the `Dataset` being at least partially evaluated, but it should be possible to know the new column names as it is the same as before but with the additional column name provided as the first argument to `add_column`. My thought being it would be good to have a function that can add a column iff the column is not present without the cost of materializing the dataset like `if col not in ds.columns(): ds.add_column(col, func)`. However, this can also be accomplished with (pseudo-code lambda) `ds.map_batches(lambda df: (df[col] = func(df)) if col not in df else df)`.

**Comment by richardliaw** [comment]
@ivanthewebber good catch -- would you be willing to submit a PR?

**Comment by ivanthewebber** [comment]
If someone gets to it first I am finding other good first issues as well.

**Comment by ivanthewebber** [comment]
@richardliaw want to add yourself as a reviewer to the PR?
