### ISSUE TITLE
bug in remote function registration?

### ISSUE THREAD

**Issue by rueberger** [ray-project/ray#4913]
### System information
- **OS Platform and Distribution**: ubuntu 16.04
- **Ray installed from (source or binary)**:  binary
- **Ray version**: both 0.6.6 and 0.7 exhibit the same behavior
- **Python version**:  3.5.2
- **Exact command to reproduce**: forthcoming....

### Describe the problem

When running an actor method that runs other remote tasks, ray throws `"This worker was asked to execute a function that it does not have registered."` for functions that it should have registered.

In particular, this breaks tune when training involves running remote tasks.

#### background info

As this problem spans a lot of code, it will take some time to make a minimal reproducible example. For the time being, I will describe the relevant bits as best I can.

The package structure looks like this:

foo:
  - experiment.py: entry point into running experiment
  - batch_gen.py: uses several remote methods
  - hypersweep.py: hyperparams search is launched from here

The trial actors launched for the hyperparam search look like this:

```python
@ray.remote(num_gpus=1)
class RemoteTraining(object):
    def train(self):
        from foo.experiment import run_experiment
        run_experiment()
``` 

Note that  ` from foo.experiment import run_experiment` cannot  be a top-level import because in the real code, the equivalent of  `run_experiment` is not serializable (it's a [`sacred`](https://github.com/IDSIA/sacred)  experiment).

experiment.py looks like this
```python
from foo.batch_gen import batch_gen

def run_experiment():
     batch_generator =  batch_gen() # calls remote tasks to load data and initialize the batch gen
     # run experiment
      ...
```

batch_gen.py looks like this
```python
import ray

@ray.remote
def load_data(args):
    data_urls = split_urls()
    # load data
    ...
    return data

def split_urls():
    ...

def batch_gen(): 
    data = load_data()
    # yield batches 
    ...
```

#### the problem

The following crashes:

```python
import ray
ray.init()

from foo.hypersweep import RemoteTraining
training = RemoteTraining.remote()
training.train.remote() # ERROR: "This worker was asked to execute a function that it does not have registered."
```

On the other hand,  if I try the following we get an entirely different error:

```python
import ray
ray.init()
from  foo.batch_gen import *

from foo.hypersweep import RemoteTraining
training = RemoteTraining.remote()
training.train.remote() # ERROR: "File:  batch_gen.py, in load_data, NameError: name 'split_urls' is not defined"
```

It was this point I became confident that this is a bug in `ray`, or at least bizarre and undesirable behavior.

### Source code / logs

Minimal reproducible example forthcoming...

**Comment by rueberger** [comment]
OTOH, if I simply change the order of the imports: 

```python
import ray
from foo.batch_gen  import *
ray.init()

from foo.hypersweep import RemoteTraining
training = RemoteTraining.remote()
training.train() # works!
```

everything works. Bizarre. Is this intended behavior?

**Comment by songpengwei** [comment]
`training.train()` is intented? instead of 'training.train.remote()'

**Comment by rueberger** [comment]
Thanks, fixed.
