### ISSUE TITLE
RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry < 0) at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:325

### ISSUE THREAD

**Issue by sheetalsh456** [ray-project/ray#4916]
I'm training a PGTrainer using Pytorch and tune.run with the following command:

  
       tune.run(pg.PGTrainer,   
         local_dir=".", stop={"episode_reward_mean": 0.5}, 
         resources_per_trial={"cpu":1, "gpu":1},
         config={"env": "my_env",  
                                 "use_pytorch": True,
                                 "model": {"custom_model": "my_model"},
                                "num_workers": 2,
                                 "train_batch_size": 32,
                                 "sample_batch_size": 16,
                                 "num_envs_per_worker": 16,
                                 })

And I'm getting the error:

`
RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry < 0) at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:325
`

When I run the same with `"num_envs_per_worker": 1`, it works. 

I'm running in local mode. 
I don't understand how increasing the number of envs per worker causes a probability < 0 error with no other change in the code. 

Any leads will be appreciated!

**Comment by ericl** [comment]
Is it possible to reproduce with Cartpole? the following works for me on the latest wheel: `rllib train --run=PG --env=CartPole-v0 --config='{"use_pytorch": true, "num_envs_per_worker": 16, "train_batch_size": 32, "sample_batch_size": 16, "num_workers": 2}'`
