### ISSUE TITLE
Release test random_shuffle failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#49209]
Release test **random_shuffle** failed. See https://buildkite.com/ray-project/release/builds/27812#0193b481-9cc4-442e-a4b3-1a328e43fa60 for more details.

Managed by OSS Test Policy

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by bveeramani** [comment]
Closing because this test has been renamed
