### ISSUE TITLE
[data] Adding Resilience to map/filter for Handling Failures

### ISSUE THREAD

**Issue by ryan-minato** [ray-project/ray#49227]
### Description

Introduce a parameter in `map` and `filter` functions to tolerate failures gracefully. Instead of halting execution, the parameter would allow the function to fail with a warning, ensuring uninterrupted processing.

like this:
``` python
ds = ds.map(fn, allow_failure=False)
```

### Use case

While designing a pipeline to process a 2TB dataset scraped from the web, I encountered significant challenges due to the unpredictable nature of the input data. The pipeline worked seamlessly on a test set of 10k records, but when scaled to the full dataset, it crashed after processing several hundred gigabytes, wasting hours of computation time and causing considerable frustration.
Although it’s possible to catch exceptions manually and flag problematic data for filtering, Ray Data enforces strict key consistency for returned values. This requirement complicates error handling, forcing me to generate a lengthy series of placeholder values for failed cases.

Introducing a built-in recovery mechanism would make `map` (or `filter`) functions far more robust. With this feature, users could monitor error frequencies via warnings, empowering them to decide whether to address or disregard the issues, all while maintaining a smooth pipeline execution.

**Comment by richardliaw** [comment]
hmm, i think generally the recommendation here would be for the user to implement a try-catch themselves

**Comment by ryan-minato** [comment]
> hmm, i think generally the recommendation here would be for the user to implement a try-catch themselves

My current workaround is to do exactly that. However, even if I capture the error, I still have to create a meaningless default return. I cannot directly return None as it will raise an error, nor can I return a dictionary with different keys as this will also raise an error.
I'm processing Common Crawl-like data with Ray Data, extracting various information. This requires me to add excessive default returns at almost every step.

**Comment by ryan-minato** [comment]
btw, I haven't dived into ray data's implementation due to the bazel learning curve. 
Out of pure curiosity, I'd like to ask why a similar feature couldn't be added? Is it technically challenging or due to design philosophy?

**Comment by richardliaw** [comment]
As commented on the other PR, I believe using flat_map should work for your use case. Feel free to reopen if you have other issues.
