### ISSUE TITLE
[data] Enable None Return in map to Skip Unprocessable Rows

### ISSUE THREAD

**Issue by ryan-minato** [ray-project/ray#49228]
### Description

This proposal suggests allowing a `None` return from the `map` function to signal skipping the current row. Since `ray.data` already disallows returning Python Object, this approach can maintain compatibility.

For example, consider the following case. Rows with an `""` body column will be skipped and excluded from the output dataset. (effectively combining `map` and `filter` operations):
``` python
def func(doc):
  if doc["body"] == "":
     return
  try:
    soup = BeautifulSoup(doc["body"], 'html.parser')
  except as e:
    logging.warn(str(e))
    return
  # ...processing steps
  return { ... }

ds = ... # [{"url": "abc", "status_code": 200, "body": "<html> ..."}, {"url": "xyz", "status_code": 404, "body": ""}, ...]
ds = ds.map(func) # Output: [{"url": "abc", "key1": "itm1"}, ...]
```

This provides an alternative solution to address issue #49227 

### Use case

While building a processing pipeline for a 2TB web scraping dataset, I encountered significant challenges due to the unpredictability of input data collected from entire websites. The pipeline performed flawlessly on a test sample of 10k entries but failed during full-scale execution after processing hundreds of gigabytes, resulting in hours of wasted work—an incredibly frustrating experience.

Various issues, such as network transmission errors, can lead to data that cannot be successfully parsed into a DOM structure. Parsing itself is computationally expensive and often cannot be pre-validated.
Allowing the `map` function to return `None` when encountering such errors would streamline the process, enabling easier validity checks without redundant, costly operations.

**Comment by ryan-minato** [comment]
> Have you tried `map_batches` to skip rows?
> 
> or you can return with a status code column and filter them downstream
> 
> ```
> [{'status': 'success', 'url': 'abc', 'key1': 'itm1'}, 
> {'status': 'failed', 'url': '', 'key1': ''},
> ]
> ```

Given the non-vectorizable nature of my processing, batch_map hadn't crossed my mind. Thanks for the suggestion. For scenarios with a limited number of return keys, this could be a viable solution.

Preemptively returning a flag isn't appropriate for my use case. Specifically, I'm using Ray Data to handle Common Crawl-like data, involving morphological analysis. Each processing step yields a result with many keys. As it stands, Ray Data necessitates the creation of arbitrary initial values for every key.

**Comment by richardliaw** [comment]
OK, you can also use flat_map here which allows you to return 0 to N results too.

map_batches will be faster but think flat_map will work for your use case with minimal code changes.
