### ISSUE TITLE
Error in example notebook - examples/map_reduce.ipynb

### ISSUE THREAD

**Issue by dazzag24** [ray-project/ray#4923]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 
Ubuntu 18.04 on WSL (Windows 10)
- **Ray installed from (source or binary)**:

Installed using pipenv.

- **Ray version**:

0.7.0

- **Python version**:

3.6.7

### Describe the problem

When following the examples in https://github.com/ray-project/tutorial/blob/master/examples/map_reduce.ipynb

this cell:

`
import ray.experimental.ui as ui

ui.task_timeline()
`

Results in a error

`
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-f78e3281fe4b> in <module>
----> 1 import ray.experimental.ui as ui
      2 ui.task_timeline()

ModuleNotFoundError: No module named 'ray.experimental.ui'
`

**Comment by JasonWayne** [comment]
I think the tutorial is a bit outdated and if we need to see the UI, we can simply change the `ray.init` call in the notebook like this:
```python
ray.init(num_cpus=4, include_webui=True, ignore_reinit_error=True)
```
