### ISSUE TITLE
Release test batch_inference_hetero failed

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/ray#49232]
Release test **batch_inference_hetero** failed. See https://buildkite.com/ray-project/release/builds/27922#0193b9e0-6f16-4e84-95fb-0eccc844d41e for more details.

Managed by OSS Test Policy

**Comment by srinathk10** [comment]
Seems to have run into 3600 secs timeout.


[INFO 2024-12-12 09:04:34,164] ray_test_db.py: 44  Test object: {"name": "batch_inference_hetero", "group": "data-tests", "working_dir": "nightly_tests/dataset", "frequency": "weekly", "team": "data", "cluster": {"byod": {"type": "gpu"}, "cluster_compute": "autoscaling_hetero_compute.yaml"}, "run": {"timeout": 3600, "script": "python gpu_batch_inference.py --data-directory 10T-image-data-synthetic-raw-parquet --data-format parquet\n"}, "state": "failing"}

**Comment by can-anyscale** [comment]
Test has been failing for far too long. Jailing.

**Comment by omatthew98** [comment]
Fixed by https://github.com/ray-project/ray/pull/49348.

**Comment by can-anyscale** [comment]
Test passed on latest run: https://buildkite.com/ray-project/release/builds/29282#019425b2-f0d6-4f35-bd23-9f3e08e439e0
