### ISSUE TITLE
Embracing asyncio / Python >= 3.5?

### ISSUE THREAD

**Issue by wesm** [ray-project/ray#493]
Since it's 2017, with Ray being a new distributed computing framework without a lot of legacy baggage, I am curious if there is a particular reason to maintain Python 2.7 support, which you could use better and faster concurrency primitives in Python 3.5 and up. The Python data community is rapidly distancing itself from Python 2 with Python 2.7 end-of-life in 2020, so I don't think you'd be giving up much.

**Comment by pcmoritz** [comment]
For the performance critical parts of Ray (task submission and scheduling as well as object management) we are already using asynchronous IO in the C++ backend via an event loop. Most of the operations that happen in pure python are things like putting pickled function or actor code into redis or dealing with errors. These done only done once or are not on any critical path, so it is not clear what we would gain from using asyncio.

In the machine learning community there are (unfortunately) still many people who use Python 2.7, so it is nice to support it. But if there good reason to drop support, we'd consider it.

Our webui (which is in a very early prototype state) already uses asyncio and we are not planning to support Python 2.7 here.

**Comment by wesm** [comment]
Got it, since there's a C++ backend already, I wasn't sure whether the async event-loop part of the project was impacted in a meaningful way by Python's concurrency utilities. It might be useful to start a microbenchmark suite using ASV (https://github.com/spacetelescope/asv).

**Comment by pcmoritz** [comment]
Thanks for the pointer, we have been looking for something like this to track performance.

**Comment by robertnishihara** [comment]
One place that *could* be rewritten with asyncio is our worker processes in `worker.py`. In the current implementation, there are two threads.

1. The main thread runs an infinite loop where it gets a task from the local scheduler and executes the task.
2. A background thread has a Redis pubsub client which listens for new remote function definitions from Redis and fetches/unpickles them.

There is a small amount of coordination between the two threads using a lock.

Conceptually, this would probably be cleaner with Python 3's support for event loops.

**Comment by robertnishihara** [comment]
I'm closing this since supporting Python 2.7 is still very important for us. I created a separate issue (#606) to track the thread here about microbenchmarks and performance testing.

**Comment by wesm** [comment]
:+1:

**Comment by mitar** [comment]
So if I understand, Ray will not support asyncio on the client side? So I was looking into how to go around the fact that it blocks a thread while it is waiting for a result. What I would prefer is that it blocks in asyncio mode. Then I could have other things being done by the control process while it is waiting for tasks to finish on workers.

You are mentioning above that UI is using asyncio. And background C code is also event based. So it seems that maybe there is a way to use Ray through asyncio? So I do not care how it is internally implemented. But I would love if I could use it inside async functions where blocking would be async blocking and not thread blocking.

**Comment by robertnishihara** [comment]
Not the same thing, but related to #1883.

The UI actually no longer uses `asyncio`. It's currently just a Jupyter notebook.

I think making Ray compatible with asyncio and generally to allow more reactive-style programming is doable and worthwhile. I haven't looked into what it would take to support this, but if anyone is interested in hacking together a prototype then that would be cool, and would allow us to start thinking through what the APIs should be.

**Comment by robertnishihara** [comment]
Turning a Ray object ID into an async future may be fairly straightforward. I was thinking of a prototype implementation.

**Comment by robertnishihara** [comment]
Yes, `tune.run_experiments` is blocking. cc @richardliaw

**Comment by mitar** [comment]
Should we open a new issue or reopen this one?

**Comment by edoakes** [comment]
https://ray.readthedocs.io/en/latest/async_api.html
