### ISSUE TITLE
[tune] "metric" parameter not found

### ISSUE THREAD

**Issue by ludc** [ray-project/ray#4930]
Hi,

When installing ray (using pip install, or pip install -U [last version]), the version of pbt.py in ray.tune.schedulers is not the same than the one in the GIT repository. For instance, I can't use PopulationBasedTraining.__init__ with the parameters called 'metric' since it was not existing in the previous version. So it seems that the pip package contains an old version of tune. 

 How can I fix it ?

**Comment by richardliaw** [comment]
Ah you'll need to install master. Can you try installing with the wheel links here?

https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master

**Comment by ludc** [comment]
Hi, it did not work even if I install from the wheel links (I tested for python 3.6 and python 3.7)

**Comment by richardliaw** [comment]
I think the wheel links are not being routed correctly; can you try this for now? `pip install -U` despite the lower version: 

https://ray-wheels.s3-us-west-2.amazonaws.com/latest/ray-0.7.1-cp36-cp36m-manylinux1_x86_64.whl
https://ray-wheels.s3-us-west-2.amazonaws.com/latest/ray-0.7.1-cp37-cp37m-manylinux1_x86_64.whl

**Comment by ludc** [comment]
I am using MacOS.... I tried this link : https://ray-wheels.s3-us-west-2.amazonaws.com/latest/ray-0.7.1-cp37-cp37m-macos_10_6_intel.whl

 But the error is now: ERROR: ray-0.7.1-cp37-cp37m-macos_10_6_intel.whl is not a supported wheel on this platform.

**Comment by richardliaw** [comment]
Try adding `x` to `macos`? 

https://ray-wheels.s3-us-west-2.amazonaws.com/latest/ray-0.7.1-cp37-cp37m-macosx_10_6_intel.whl

**Comment by ludc** [comment]
Cool, it works now.

**Comment by richardliaw** [comment]
Closed by #4937 and #4941 !
