### ISSUE TITLE
Ray not installing on Raspberry Pi

### ISSUE THREAD

**Issue by ghost** [ray-project/ray#4946]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Strech 9 Lite (Raspberry Pi Zero W)
- **Ray installed from (source or binary)**: Binary (via pip)
- **Ray version**: Latest wheel (built off of master)
- **Python version**: 3.5
- **Exact command to reproduce**: `sudo pip3 install -U ray`

### Describe the problem

I can't install Ray on my Raspberry Pi. I tried updating the packages, pip as well, but I couldn't fix it. 

### Source code / logs

sudo pip3 install -U ray
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ray
  ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray

**Comment by 1beb** [comment]
The Pi requires ARM based architecture, you would have to build from source and there's no guarantee it would work. You might be able to emulate i386 and then run it (again after building from source)

**Comment by sumit1223** [comment]
@1beb  I tried to build ray from source on Jetson Tx2 (which also has ARM architecture), it got stuck while fulfilling the requirement of pyarrow 
"ERROR: No matching distribution found for pyarrow==0.14.0.RAY". 
Can you suggest if there is some way to overcome this issue and if not are you looking to build Ray for ARM architecture in future.

**Comment by 1beb** [comment]
There are no ARM builds for pyarrow. I suppose you could try to compile pyarrow yourself and then change the dependency for a local source build of ray. Zero guarantee it would work. Related: https://jira.apache.org/jira/browse/ARROW-2599. 

Even if you get that working there may be more dependencies that do not have ARM builds. I'd check before wasting time with the above. 

Interesting little board you have there. What's your use case?

**Comment by sumit1223** [comment]
Thanks, my usecase is "Driver safety using video analytics".  I tried multiprocessing library also but multiprocessing.Queue.put() and get() functions are taking too much time for large variables( for me it is 400*400 rgb image).

**Comment by 1beb** [comment]
Hard to provide further comment here. Bottlenecks happen for a number of reasons. Maybe try some profiling to see memory, CPU and I/O use. Perhaps you're running more processes than you have memory for.400x400px is very small and on that Jetson, should be very quick if it's anything close to what's advertised.
