### ISSUE TITLE
[rllib] Image observations with TD3

### ISSUE THREAD

**Issue by inconst** [ray-project/ray#4947]
Hello! I have an environment with image observation space and continuous action space, so I've decided to use TD3 algorithm for training. But I receive an error, because critic tries to concatenate observations and actions. Is there some workaround?

**Comment by ericl** [comment]
Cc @joneswong

**Comment by ericl** [comment]
Looks like this is supported by setting use_state_preprocessor: True:
```
    # Apply a state preprocessor with spec given by the "model" config option
    # (like other RL algorithms). This is mostly useful if you have a weird
    # observation shape, like an image. Disabled by default.
    "use_state_preprocessor": False,
```

**Comment by inconst** [comment]
This option works, but I have several questions:
1) As specified [here](https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ddpg/ddpg_policy.py#L406) model outputs single value if `use_state_preprocessor` is True. In case we have image observation, VisionNetwork will be used ([this line](https://github.com/ray-project/ray/blob/master/python/ray/rllib/models/catalog.py#L264)), which consists only of convolutional layers. Won't it decrease our model's ability to learn if we output just a single value from convolutional network?
2) Can I use GPU with TD3 to accelerate training? Does setting `num_gpus: 1` means that GPU will be used for convolutions?
3) Do images get normalized to range [0, 1] somewhere along pipeline?

**Comment by ericl** [comment]
> As specified here model outputs single value if use_state_preprocessor is True. In case we have image observation, VisionNetwork will be used (this line), which consists only of convolutional layers. Won't it decrease our model's ability to learn if we output just a single value from convolutional network?

Potentially -- though using the last layer feature embedding is pretty standard and can actually help learning. You can also define a custom model that returns an arbitrary feature tensor.

> Can I use GPU with TD3 to accelerate training? Does setting num_gpus: 1 means that GPU will be used for convolutions?

Yes, I think that will do it.

> Do images get normalized to range [0, 1] somewhere along pipeline?

Not by default. You can enable "observation_filter" config to do so, but I don't think it's normal to standardize images (it hurts atari perf at least).
