### ISSUE TITLE
Discuss on cleaning up GCS tables.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#4957]
For supporting long running cluster, it's necessary to cleanup GCS when a driver exiting.

We'd like to purpose a scenario to implement this according to the suggestions from @stephanie-wang  and @raulchen .

1. For task tables and object tables,  we'd like to encode `driverID` to `taskID` and `ObjectID`.
We can use 2 bytes to store driverID. because it's too short, we should generate it in GCS to avoid duplication. 
```
             4B            2B            10B  
    +-----------------------------------------------+
    |  object_index  | driver_id  |     unique      |
    +-----------------------------------------------+
```

 And there should be a background thread in raylet to scan them with using the `driverID` as prefix.
```shell
SCAN RAYLET_TASK_\xs\xf*
```

2. For actor tables,if we don't encode `driverID` to `actorID`, I'd like to add an index for actors and then use `SSCAN` to collect the garbage of actor table in the background thread.

**Comment by ericl** [comment]
Shouldn't the unique bit be a prefix for even sharding?

**Comment by stephanie-wang** [comment]
> Shouldn't the unique bit be a prefix for even sharding?

Yes, we should do that (we do this already for object and task IDs).

@jovany-wang, I think this proposal makes sense. For actor tables, though, I think it would be okay to store the driver ID locally with the actor information in the raylet's `actor_registry_`. We don't currently store that information, but we could easily do it based on the actor creation task. This would let us maintain the actor index directly in the raylets without having to scan the GCS or store the index separately in the GCS.

Another question is who should be doing the `SCAN`. Maybe it makes sense to have this be done initially by the raylet where the driver was connected, but this won't work if that raylet disconnects from the cluster before it finishes GC.

**Comment by jovany-wang** [comment]
> Another question is who should be doing the SCAN. Maybe it makes sense to have this be done initially by the raylet where the driver was connected, but this won't work if that raylet disconnects from the cluster before it finishes GC.

I think the GCS can make the decision about which raylet to perform the `SCAN` for a given driver.

Let's add a filed `maintained_drivers` for `ClientTableData` in `gcs.fbs`, and put `maintained_drivers` from one client entry to another client entry once a client exited. This operation can be done in GCS.

Every raylet only need to care about its `maintained_drivers`. Raylet need to append the driver id to `maintained_drivers` if the local driver connected, and remove the driver id from `maintained_drivers` once it finishes the GC.

**Comment by raulchen** [comment]
We can simply store the attached node id in `driver_table`. When a raylet disconnects before it finishes GC, any other raylet can notify that and do the GC instead. (Not sure if it's possible to do scan inside the redis module's background thread. If that's possible, things would be much easier.)
BTW, I think we can encode driver id in actor id as well.

**Comment by jovany-wang** [comment]
> Shouldn't the unique bit be a prefix for even sharding?

@ericl I'm sorry that I can't see why the unique bits should be a prefix. Could you please bring more explanation?

**Comment by raulchen** [comment]
> Shouldn't the unique bit be a prefix for even sharding?

don't we use id's hash to decide sharding?

**Comment by rkooo567** [comment]
@raulchen This must've been done right?

**Comment by rkooo567** [comment]
Please reopen if it is not.
