### ISSUE TITLE
[rllib] PPO Continuous Control with LSTM: ValueError: Variable default_policy/log_std already exists

### ISSUE THREAD

**Issue by pethor** [ray-project/ray#4962]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 9.9
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.1
- **Python version**: 3.6
- **Exact command to reproduce**: `rllib train -f mountaincarcontinuous-ppo-lstm.yaml`

Contents of `mountaincarcontinuous-ppo-lstm.yaml`:
```
# This configuration can expect to reach 90 reward in 10k-20k timesteps
mountaincarcontinuous-ppo:
    env: MountainCarContinuous-v0
    run: PPO
    stop:
        episode_reward_mean: 90
        time_total_s: 600 # 10 minutes
    config:
        vf_share_layers: True
        model:
            use_lstm: True
            free_log_std: True
```

### Describe the problem

As soon as I try to start training with the given config file above, ray crashes with the following error seen in the log. I don't think that these options are mutually exclusive; I think it might be a bug. I have confirmed this issue exists in a clean new conda install with just `tensorflow` and `gym[atari]` installed.

### Source code / logs

```
ValueError: Variable default_policy/log_std already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/path/to/conda/env/lib/python3.6/site-packages/ray/rllib/models/model.py", line 94, in __init__
    initializer=tf.zeros_initializer)
  File "/path/to/conda/env/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 267, in _get_model
    num_outputs, options)
  File "/path/to/conda/env/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 227, in get_model
    seq_lens)
```

**Comment by garibarba** [comment]
Any progress here? I guess this should eventually be fixed through the migration to tf2.0 / pytorch, but I wonder if this is being tracked / tested.
