### ISSUE TITLE
serving a deep learning model on a server using ray actor.

### ISSUE THREAD

**Issue by gliese581gg** [ray-project/ray#4967]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.1
- **Python version**: 3.6.7
- **Exact command to reproduce**:

### Describe the problem

Hi!

I'm thinking about serving a deep learning model on a server using ray actor.

My idea is

1. Start ray on the server
2. Create an inference actor on the server
3. Pickle the actor handler objectID and redis info then save them as files
4. Clients download the pickled files and unpickle them to get the redis info and the actor handler
5. Clients initialize ray with unpickled info and use actor for neural net inference

In this case, clients will have poor computing power so I want the actor inference only uses

resources of the server. If I make an actor in one machine, then do the actor methods

use only that machine's resources? What I'm guessing is true if I don't use another

ray.remote in the actor methods. Is it correct?

**Comment by richardliaw** [comment]
cc @simon-mo

**Comment by richardliaw** [comment]
try out ray serve: https://docs.ray.io/en/latest/serve/index.html
