### ISSUE TITLE
Is there a reason not to allow remote functions to return an objectid directly?

### ISSUE THREAD

**Issue by gravitywp** [ray-project/ray#4983]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by raulchen** [comment]
Previously, there was a bug about serialization of ObjectID. But the bug is already fixed. I think we should remove [this check](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L373), and allow returning object ids now.

@robertnishihara are you aware of any other issues?

**Comment by richardliaw** [comment]
closing because stale - please reopen if still an issue.
