### ISSUE TITLE
[docs] Multi GPU not supported for Keras Models?

### ISSUE THREAD

**Issue by bionicles** [ray-project/ray#4988]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04)
- **Ray installed from (source or binary)**: pip
- **Ray version**: latest
- **Python version**: 3.6.8
- **Exact command to reproduce**: reading docs

### Describe the problem
https://github.com/ray-project/ray/blob/master/doc/source/rllib-models.rst
reads: _Keras custom models are not compatible with multi-GPU (this includes PPO in single-GPU mode). This is because the multi-GPU implementation in RLlib relies on variable scopes to implement cross-GPU support._

This is unclear because it's hard to know if this means **all models created with tf.keras.Model via functional API or only model subclasses.**

Keras is the default high level api for tensorflow, and has a built in Attention layer in versions 1.14rc and 2.0b, would it be possible to revisit this or find a workaround so we can scale keras models to multiple graphics cards easily with Ray? Keras is super nice and easy and has many implemented models...it would be wonderful to scale these models with Ray!

**Comment by ericl** [comment]
This is coming soon, with ModelV2! https://github.com/ray-project/ray/pull/4926

**Comment by bionicles** [comment]
Thank you @ericl
