### ISSUE TITLE
[rllib] should not apply l2 regularization to untrainable variables

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5010]
### Describe the problem

In DDPG, l2 regularization is applied to all variables in self.policy_vars and self.q_func_vars.
It seems that these lists include both trainable and untrainable variables because they are created by calling _scope_vars() without trainable_only=True.

### Source code / logs

https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ddpg/ddpg_policy.py#L222

**Comment by ericl** [comment]
I guess this affects the reported loss, but shouldn't have any effect on optimization, correct?

**Comment by joneswong** [comment]
yes, as they are still untrainable.
