### ISSUE TITLE
AttributeError in signal API breaks local mode

### ISSUE THREAD

**Issue by rueberger** [ray-project/ray#5013]
### System information
- **OS Platform and Distribution**: ubuntu 16.04
- **Ray installed from**: binary
- **Ray version**: 0.7.0
- **Python version**: 3.5.2
- **Exact command to reproduce**: run signal tests in local mode

### Describe the problem

Using `ray.experimental.signal.send` in local_mode results in:

```

~/.local/lib/python3.5/site-packages/ray/experimental/signal.py in send(signal)
     73 
     74     encoded_signal = ray.utils.binary_to_hex(cloudpickle.dumps(signal))
---> 75     ray.worker.global_worker.redis_client.execute_command(
     76         "XADD " + source_key + " * signal " + encoded_signal)
     77 

AttributeError: 'Worker' object has no attribute 'redis_client'
```

**Comment by pcmoritz** [comment]
@rueberger Thanks for reporting, do you want to submit a fix? The right thing to do here I think is to detect if we are in local mode and if yes, store/retrieve the signal from a local hashtable instead of redis.

**Comment by rueberger** [comment]
Sorry, I probably won't be able to be much help with this.

**Comment by jsuarez5341** [comment]
Seems like this hasn't seen much attention -- note that as a workaround, you can check if an ErrorSignal is returned and print ErrorSignal.error. This at least allows you to develop without breaking print debugging (still breaks pdb)
