### ISSUE TITLE
Confusion about action embedding in parametric_action_cartpole.py

### ISSUE THREAD

**Issue by yangysc** [ray-project/ray#5017]
### Describe the problem

Dear all,
  I want to ask about hot to **make the action embedding trainable,** instead of making them initialized randomly. Since my valid action space is large, should I put them into the model to learn them,  instead of the env?  If they are put in the env, when I set **num_workers** > 0, there would be  multiple envs. Under this situation, are the **action embeddings are different across the different envs**? They should be the same, right?

Thanks in advance.

**Comment by ericl** [comment]
I think one solution here is to make the embedding network part of the model itself. That way, synchronization is taken care of automatically.

One way this could work is if the action are represented in the environment as just a number. Then, in the model there can be an embedding layer that transforms this into the action embedding.

**Comment by yangysc** [comment]
Thanks for your help.  I think that is a nice solution.
