### ISSUE TITLE
Instead of warning about deadlocks, detect them and abort

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#5019]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu Bionic
- **Ray installed from (source or binary)**: pip binary
- **Ray version**: 0.6.5
- **Python version**: 3.6.7

### Describe the problem

I have a multi-threaded application where a thread submits a Ray task and then waits for it. I see such warning:

```
Calling ray.get or ray.wait in a separate thread may lead to deadlock if the main thread blocks on this thread and there are not enough resources to execute more tasks
```

This is nice but not really user friendly. I have no idea where is the call which is triggering this. If I see this once, then it is only in one case of me calling ray.get or ray.wait? So this is not really actionable in a large multi-threaded app.

Or should I simply not use ray.get or ray.wait at all in any non-main thread?

I would suggest that Ray instead detects the deadlock when it happens and aborts one of the blocking threads with an exception. That would then help me know if this is happening and where exactly it is happening, so that I could debug and remove the potential for a deadlock.

Deadlock tracking might be expensive, so it would be enabled explicitly. Like `ray.get(..., abort_on_deadlock=True)`.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by rkooo567** [comment]
It looks like we don't have this warning anymore. What error other deadlock messages are you seeing for this case?

**Comment by mitar** [comment]
Oh, when was this changed/removed?
