### ISSUE TITLE
Odd behavior when importing ray_get_and_free

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#5020]
Using ray 0.7.1. Adding the following line to my code completely changes the speed that the workers process data at:
`from ray.rllib.utils.memory import ray_get_and_free`

I am not even using the actual function! Just adding the above completely changes how the code executes. Somehow workers are a lot slower, while the main thread runs much faster. I also get a ton of msgs in the beginning (about OPM?):
```
(pid=5105) OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
(pid=5105) OMP: Info #213: KMP_AFFINITY: cpuid leaf 11 not supported - decoding legacy APIC ids.
(pid=5104) OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
(pid=5104) OMP: Info #213: KMP_AFFINITY: cpuid leaf 11 not supported - decoding legacy APIC ids.
(pid=5096) OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
(pid=5096) OMP: Info #213: KMP_AFFINITY: cpuid leaf 11 not supported - decoding legacy APIC ids.
(pid=5105) OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info
(pid=5105) OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-15
(pid=5105) OMP: Info #156: KMP_AFFINITY: 16 available OS procs
(pid=5105) OMP: Info #157: KMP_AFFINITY: Uniform topology
(pid=5105) OMP: Info #159: KMP_AFFINITY: 1 packages x 1 cores/pkg x 16 threads/core (1 total cores)
(pid=5105) OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
(pid=5105) OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 thread 0 
(pid=5105) OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 thread 1 
(pid=5105) OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 thread 2 
(pid=5105) OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 thread 3 
...
```

What's going on here? How come the workers perform so much slower? And the main thread so much faster? Again, I don't even use the ray_get_and_free function, this is all changed just by importing the call. And what do the OPM messages signal? Can it be safely ignored? Can I disable these messages?

**Comment by ericl** [comment]
That's quite odd, I don't see anything in that file that should do anything on import.

Do you have a small before / after script that can reproduce this problem?

**Comment by NikEyX** [comment]
While I was coding up the example for you, I eventually figured out the exact failure point. :)

The problem is that I had the `OMP_NUM_THREADS` environment variable set to 1, due to some other thing I tried a while ago. It had no impact on performance at all which is why I left it there. However, it starts making a difference when I try to do `from ray.rllib.utils.memory import ray_get_and_free` (even without using it), at which point performance is affected significantly (in a weird way). I don't really understand what OpenMP is changing here. The optimizations per second go way up, but the FPS for each worker go way down.

Here an output example before importing the ray_get_and_free function:
```
(pid=2576) [0:00:38 @ 67677] Episodes: 74, FPS: 1754.8, OPS: 79.7, Mean Rewards: -20.28
(pid=2576) [0:00:38 @ 68627] Episodes: 75, FPS: 1776.7, OPS: 79.7, Mean Rewards: -20.28
```
And here after:
```
(pid=4001) [0:00:38 @ 22761] Episodes: 25, FPS: 590.5, OPS: 138.4, Mean Rewards: -20.52
(pid=4001) [0:00:43 @ 23782] Episodes: 26, FPS: 550.8, OPS: 132.4, Mean Rewards: -20.50
```
And of course it comes with all the OMP warning messages - where I still don't know if that's good or bad. 

I've attached my simple model - the wrappers.py file is just the atari wrappers. 

[ompIssue.zip](https://github.com/ray-project/ray/files/3317476/ompIssue.zip)

**Comment by ericl** [comment]
That makes a lot of sense actually. It's possible that the import triggers
loading of some modules that read OMP_NUM_THREADS (i.e., creating internal
thread pools). Those modules might be loaded at a later time if the
ray_get_and_free import is not present. I would guess moving the import to
later (i.e., inside AddTransitionsLoop), or, setting the env var earlier
before the import, would change the behaviour.

Eric
