### ISSUE TITLE
[ci] Jenkins to test Py3.6 instead of 2.7?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5021]
### Describe the problem

Over the past year, many libraries have been dropping Python2.7 support. Current libraries that we cannot test integrations with due to our 2.7 dependency include `atari_py`, `nevergrad` and `ax/botorch` (facebook optimization libraries). This will be even more important as TF, Numpy drops 2.7 next year.

Moving forward, [atari_py seems to only support 3.6](https://pypi.org/project/atari-py/0.2.0/#files).

```
Collecting atari_py~=0.2.0 (from gym[atari])
  Could not find a version that satisfies the requirement atari_py~=0.2.0 (from gym[atari]) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7)
No matching distribution found for atari_py~=0.2.0 (from gym[atari])
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install gym[atari] opencv-python-headless tensorflow lz4 keras pytest-timeout smart_open' returned a non-zero code: 1
```

Our Jenkins testing currently only tests on 2.7; would it be reasonable to move Jenkins to only test 3.6 instead? 

@robertnishihara @ericl @pcmoritz

**Comment by pcmoritz** [comment]
Yeah, we should move Jenkins to 3.6! Do you want to submit a PR?

**Comment by richardliaw** [comment]
yes! #5022

**Comment by raulchen** [comment]
+1 for dropping py2 support

**Comment by pcmoritz** [comment]
Note that we are not dropping py2 support for core ray though ;)
