### ISSUE TITLE
[tune] Unexpected arguments to schedulers

### ISSUE THREAD

**Issue by himat** [ray-project/ray#5026]
### System information
Linux Ubuntu 16.04
Ray installed from binary (pip)
Ray version 0.7.1
Python version 3.6.5

### Describe the problem

I'm getting a keyword error on `metric` and `mode` when I try to use a scheduler. I tried both asynchyperband and populationbasedtraining, and got the error on both of them.
When I comment out `metric` and `mode`, then there are no syntax errors.

```
async_hb_scheduler = schedulers.AsyncHyperBandScheduler(
    time_attr='training_epoch', #'training_iteration'
    metric='mean_loss',
    mode='min',
    max_t=3,
    grace_period=1,
    reduction_factor=3,
    brackets=3
)

all_trials = tune.run(
    tune_trainable,
    name="tuner",
    scheduler=async_hb_scheduler,
    stop={"mean_f1": 99},
    config={"lr": tune.grid_search([0.0002, 0.05]), }
)
```

It also looks like `reward_attr` is not documented in the [docs](https://ray.readthedocs.io/en/latest/tune-schedulers.html#asynchronous-hyperband)?

### Source code / logs

```
2019-06-24 15:48:45,830 WARNING worker.py:1331 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setpr
ctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-06-24 15:48:45,830 INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-24_15-48-45_830395_4096/logs.
2019-06-24 15:48:45,939 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:49551 to respond...
2019-06-24 15:48:46,050 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:33743 to respond...
2019-06-24 15:48:46,052 INFO services.py:806 -- Starting Redis shard with 3.34 GB max memory.
2019-06-24 15:48:46,070 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-24_15-48-45_830395_4096/logs.
2019-06-24 15:48:46,071 INFO services.py:1442 -- Starting the Plasma object store with 5.0 GB memory using /dev/shm.
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    main()
  File "main.py", line 62, in main
    run_tune(train)
  File "main.py", line 110, in run_tune
    brackets=3
TypeError: __init__() got an unexpected keyword argument 'metric'
```

**Comment by kiddyboots216** [comment]
To get your example running, I think you would want to run your current code, replacing all instances of:
`"metric"` with `"reward_attr"`
`"mode"` with `"time_attr"`
Note that hyperband will utilize `"time_attr"` for whatever you pass in as `"max_t"` and `"grace_period"`, whereas PBT will utilize `"time_attr"` for whatever you pass in as `"perturbation_interval"`

The larger issue here is that https://ray.readthedocs.io/en/latest/tune-schedulers.html#population-based-training-pbt is not updated. @richardliaw I can take this as a PR to update docs

**Comment by richardliaw** [comment]
@himat can you install a snapshot of master? https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master

`metric` and `mode` are available in the latest versions of Ray (and `mode` doesn't correspond with `time_attr`).

@kiddyboots216, I think the docs are up-to-date. Thanks for the offer!

**Comment by himat** [comment]
@richardliaw For some reason, I'm not able to install a snapshot.

```
$ pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.8.0.dev1-cp36-cp36m-manylinux1_x86_64.whl
ray-0.8.0.dev1-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is on an AWS EC2 machine: 
```
$ cat /proc/version
Linux version 4.4.0-1085-aws (buildd@lcy01-amd64-020) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #96-Ubuntu SMP Tue Jun 11 09:08:32 UTC 2019
```

I instead just followed the [stable](https://ray.readthedocs.io/en/stable/tune-schedulers.html#asynchronous-hyperband) API docs instead these had different parameters documented? I didn't realize that the docs default to the [latest] version.

I get no error now by using `reward_attr='neg_mean_loss'` instead.
