### ISSUE TITLE
[tune] Perturbation of continous variables should respect bounds of hyperparameter

### ISSUE THREAD

**Issue by timonbimon** [ray-project/ray#5035]
Not sure if this is a bug or feature request, but I have the following problem.

I want to use PBT to find a dynamic schedule for a hyperparameter that can be between 0 and 1.
If I provide a hyperparameter_mutation that samples a value uniformly between 0 and 1: because PBT perturbs a continous variable by a factor of 0.8 or 1.2, if I am unlucky (and it gets perturbed by a factor of 1.2 multiple times) the hyperparameter can get set to values larger than 1. It would be great if there was a way for PBT to respect the bounds of a hyperparameter during perturbation.

**Comment by richardliaw** [comment]
Good point; maybe it makes sense to reimplement the mutations field to take in a range for continuous values?

**Comment by ericl** [comment]
You can use a categorical field instead to emulate this, for example [0.0, 0.2, 0.4, 0.6, 0.8, 1.0].

**Comment by timonbimon** [comment]
Yes the categorical field works, but it seems like a workaround. I think having continuous variables that have to stay within some bound is a pretty common use-case...

**Comment by richardliaw** [comment]
close due to staleness; feel free to open again.

**Comment by smanolloff** [comment]
Just bumped into the same problem, did you manage to find any workaround?
