### ISSUE TITLE
Create a Ray Operator for Kubernetes

### ISSUE THREAD

**Issue by devonkinghorn** [ray-project/ray#5044]
Ray is a great project but requires a lot of babysitting to set up and tear down clusters on demand. 

It would be nice if you had a kubernetes operator to make it trivial to spin up and tear down ray clusters much like the [spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator)

It would also solve the issue of autoscaling. The operator would manage the scale of individual ray clusters on kubernetes.

**Comment by richardliaw** [comment]
This sounds good; I've never done this before; do you know if there is a minimal example of a k8s operator? The spark operator seems a bit involved.

**Comment by devonkinghorn** [comment]
I don't. Sorry I've never written one. But here is a repository with a lot of examples. https://github.com/operator-framework/awesome-operators

**Comment by caitengwei** [comment]
@richardliaw Hi Richard, we've implemented a simple version of ray operator. And it's beta-ing inside Ant Financial. I think we can share it in next few weeks, see if it fits the requirements. cc @raulchen

**Comment by liucimin** [comment]
@richardliaw 
Hi richard,when i first time see the ray i think there maybe a kubernetes operator for this great project.
If u agree, i will take a pr for this requirment.
