### ISSUE TITLE
[tune] RuntimeError: Restore from checkpoint failed for Trial Hyperband

### ISSUE THREAD

**Issue by Kn15263ss** [ray-project/ray#5045]
# System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Ray installed from (source or binary)**:
- **Ray version**: 0.6.4
- **Python version**: 3.6.7
- **Exact command to reproduce**:

### Describe the problem
When I tune the ray schedulers of Hyperband, it's have a little problem 
""""
RuntimeError: Restore from checkpoint failed for Trial HyperTrain_30_factor=0.53654,lr=0.001074,momentum=0.42374,weight_decay=5.3161e-05.
""""
I don't know why to encounter this problem ...
Thanks for your help.

### Source code / logs
![image](https://user-images.githubusercontent.com/22387638/60231342-86459180-98cb-11e9-8ddd-b2aceee67ce0.png)
![image](https://user-images.githubusercontent.com/22387638/60231376-9b222500-98cb-11e9-9ab4-163c6e1dbc97.png)
![Screenshot from 2019-06-27 11-14-53](https://user-images.githubusercontent.com/22387638/60231803-16d0a180-98cd-11e9-9015-b3fda6df9e7e.png)
![Screenshot from 2019-06-27 11-15-58](https://user-images.githubusercontent.com/22387638/60231805-19cb9200-98cd-11e9-8770-839a2eebbc7e.png)
![Screenshot from 2019-06-27 11-16-10](https://user-images.githubusercontent.com/22387638/60231807-1b955580-98cd-11e9-84d6-dcc42fc57680.png)
![Screenshot from 2019-06-27 11-18-39](https://user-images.githubusercontent.com/22387638/60231897-6f07a380-98cd-11e9-9b4b-045efbbc6eb0.png)

**Comment by richardliaw** [comment]
Should be fixed on latest master... please provide a repro script if not.
