### ISSUE TITLE
[rllib] Redundant coefficient for l2 regularization

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5047]
### Describe the problem

According to TF documents, tf.nn.l2_loss has considered the coefficient 0.5:

> output = sum(t ** 2) / 2

But ddpg_policy.py still multiplied it by 0.5

### Source code / logs

https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/ddpg/ddpg_policy.py#L226

**Comment by joneswong** [comment]
@ericl  hi eric, any comment?

**Comment by ericl** [comment]
Yeah I don't know why there is an 0.5 there...
