### ISSUE TITLE
Access Jupyter notebook in ray-head on Kubernets

### ISSUE THREAD

**Issue by gp4r** [ray-project/ray#5052]
Hello, I just installed Ray on Kubernetes and was wondering if I can access the Jupyter notebook in ray-head pod from outside world.

When I got into ray-head pod, I saw the jupyter notebook was running on 8888.
```
root@ray-head-7d9d8d7fc5-8h6rl:/ray# ps -aux | grep jupyter
```
```
/opt/conda/bin/python /opt/conda/bin/jupyter-notebook --no-browser --port=8888 --ip=0.0.0.0 --NotebookApp.iopub_data_rate_limit=10000000000 --NotebookApp.open_browser=False --NotebookApp.token=d226a5a903fe0c4b10950a36ed9be9b219af3c7406bc4fb3 --allow-root
```

And it's service for ray-head

```
[root@k8s-dev-master jhub]# kubectl get svc | grep ray-head
ray-head      ClusterIP   10.100.19.93   <none>        6379/TCP,6380/TCP,6381/TCP,12345/TCP,12346/TCP   155m
```

Need to create a new service with port 8888 and set ingress for it?

Can anyone help me how to expose Jupyter notebook in ray-head on k8s to outside?

Thank you.

**Comment by edoakes** [comment]
Please see the `--port-forward` argument to `ray exec`
