### ISSUE TITLE
Supporting fixed number of training/testing episodes?

### ISSUE THREAD

**Issue by peterhcyuen** [ray-project/ray#5071]
Is this framework supporting to have a fixed number of training/testing episodes? As I added a stop criteria when running tune.run() method, for example, stop={"episodes_total": 100}, but the final result showed that it ran for more than 100 episodes.

**Comment by ericl** [comment]
It will stop once the number of episodes exceeds that threshold. There is no way to do an exact stop, but the approximate value should be good enough.
