### ISSUE TITLE
Fixing yaml.load() warnings

### ISSUE THREAD

**Issue by 1beb** [ray-project/ray#5072]
As per: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation 

- Using yaml.load() without a Loader argument results in a warning that will soon become an error. 

I will gladly update and submit a PR for these arguments globally if someone tells me which is the preferred Loader.

**Comment by richardliaw** [comment]
I think `FullLoader` would be fine.
