### ISSUE TITLE
[rllib] Save the trained model to run a few hand-picked states on it

### ISSUE THREAD

**Issue by EyalSel** [ray-project/ray#5073]
### System information
- Linux Ubuntu 18.04
- Ray install from binary
- Ray v0.7.1
- Python version 3.6.8

### Describe the problem
I'd like to save a trained model and run a few hand-picked states on it (getting the corresponding actions). I'm using the `tune.run` API, which requires a Trainable class passed in for checkpointing to work (https://ray.readthedocs.io/en/latest/tune-usage.html?highlight=checkpoint_freq#trial-checkpointing). The class I passed in is PPOTrainer, which extends Trainer which extends tune.Trainable, but I'm getting an error shown below.

### Source code / logs
Code:
```from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import ray.rllib.agents.ppo as ppo
import ray
from ray import tune

def main():
    # Can also register the env creator function explicitly with:
    # register_env("corridor", lambda config: SimpleCorridor(config))
    ray.init()

    config = ppo.DEFAULT_CONFIG.copy()
    config["num_workers"] = 6
    config["vf_clip_param"] = 100.0
    config["env"] = MetisEnv
    trainer = ppo.PPOTrainer(config=config, env=MetisEnv) # MetisEnv not shown in this snippet

    tune.run(
        trainer,
        # "PPO",
        stop={"timesteps_total": 200000},
        checkpoint_at_end=True,
        config={
            # "horizon":
            # "sample_batchsize" : 200
            "env": MetisEnv,  # or "corridor" if registered above
            # "model": {"custom_model": "my_model"},
            "num_workers": 6,  # parallelism
            # "num_envs_per_worker":4,
            "vf_clip_param": 100.0,
        },
    )


if __name__ == "__main__":
    main()
```
error:
``````  File "rllib_run.py", line 248, in <module>
    main()
  File "rllib_run.py", line 241, in main
    "actuation_delay": 5.0,
  File "/home/ubuntu/miniconda3/envs/py36/lib/python3.6/site-packages/ray/tune/tune.py", line 217, in run
    restore=restore)
  File "/home/ubuntu/miniconda3/envs/py36/lib/python3.6/site-packages/ray/tune/experiment.py", line 93, in __init__
    run_identifier = Experiment._register_if_needed(run)
  File "/home/ubuntu/miniconda3/envs/py36/lib/python3.6/site-packages/ray/tune/experiment.py", line 177, in _register_if_needed
    raise TuneError("Improper 'run' - not string nor trainable.")
ray.tune.error.TuneError: Improper 'run' - not string nor trainable.```

**Comment by ericl** [comment]
Checkpointing works fine with just "PPO" actually, that's referencing a trainable class.

By the way, the reason the example is not working is because you aren't passing in a class but a class instance. Passing "PPO" or PPOTrainer will work.

**Comment by EyalSel** [comment]
That worked! Thanks

**Comment by kakawinwin** [comment]
> That worked! Thanks

Hi EyaSel, I'd like to do the same thing like you. Save the trained model and  run a few hand-picked states on it. Could you help share your code?

**Comment by oasfuyou** [comment]
change the code "trainer = ppo.PPOTrainer(config=config, env=MetisEnv)",to "trainer = ppo.PPOTrainer",the config in the tune.run will instance a new trainer
