### ISSUE TITLE
[tune] Set environment variable for each new process

### ISSUE THREAD

**Issue by tawe141** [ray-project/ray#5080]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.7.1
- **Python version**: 3.6

### Describe the problem
It looks like I need to set `PYTHONPATH` for each new process that's created by Tune, as it's not finding my data set. I've tried setting this in the train function like so:
```
import os
os.environ['PYTHONPATH'] = "."
```
but this does not fix the problem. Any ideas?

**Comment by richardliaw** [comment]
Can you try doing that in the trainable?

**Comment by tawe141** [comment]
I've tried that in the PyTorch Dataset. 

It looks like the CWD is in `~/ray_results`, so setting the PYTHONPATH to "." won't actually fix it anyway. I ended up setting an absolute path, which works, but is there a way to pass the CWD of the process that's running Tune to the children processes doing the actual training?

**Comment by richardliaw** [comment]
One option would be to pass it through the config, like `{"driver_cwd": os.getcwd()}`. This may run into problems in the distributed mode though.

**Comment by tawe141** [comment]
This is the error I get when I set "driver_cwd" in config:

```
Traceback (most recent call last):
  File "/home/erictaw/PycharmProjects/experimental_uv_vis/models/pytorch_geometric/hyperparameter_opt.py", line 115, in <module>
    tune.run(train_fn, search_alg=algo, scheduler=scheduler, **config)
TypeError: run() got an unexpected keyword argument 'driver_cwd'
```

**Comment by tawe141** [comment]
Never mind -- passing `{"driver_cwd": os.getcwd()}` in `config['config']` that gets passed into `tune.run()` works. In the train function, I did `os.chdir(config['driver_cwd'])`.
