### ISSUE TITLE
Training and checkpointing multiple agents from a custom Trainable

### ISSUE THREAD

**Issue by FedericoFontana** [ray-project/ray#5081]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.7.1
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem
I've created a custom trading environment which allows agents to trade against historical data (i.e. an offline dataset). I want to train agents using [walk-forward optimization](https://en.wikipedia.org/wiki/Walk_forward_optimization), which can be summarized by the following picture. So an agent is trained on the first optimization fold and assessed on the test fold. A new second agent is initialized from scratch or not (e.g. transfer learning from previously trained agent) and the process continues until when all fold pairs have been used.
![image](https://user-images.githubusercontent.com/23344446/60457649-76fc7600-9c34-11e9-9b0e-d2225a44e098.png)
Following the example at [curriculum-learning](https://ray.readthedocs.io/en/latest/rllib-training.html#example-curriculum-learning), I've implemented a custom `Trainable` and it runs, but I'm a bit lost when I need to save/checkpoint/restore these multiple agents within the same `Trainable` as it seems that ray overrides all agents in a single checkpoint path.

**Goal:**
Curriculum learning with args passes to `tune.run` applied to each agent trained in each phase of curriculum learning (e.g. if `checkpoint_at_end=True`, then before changing phase the agent is checkpointed in a dedicated folder)

**Questions:**
- What's the recommended checkpoint path or directory should be used to save and restore multiple agents within a single `Trainable`?
- Is `agent.save` the only thing needed to save everything that could possibly be saved of the trained agent (weights, parameters, config, etc)?

### Attempt
The solution will probably consist of handling in a better way the paths/dirs passes to the methods at the bottom, but I'm not finding any reference in ray's docs about how paths are/should be handled.

    class WalkForward(Trainable):
        """Walk forward optimization for custom environments."""

        def _setup(self, config):
            self.config = config.copy()
            self.phase = 0
            self.phase2folds = config['env_config']['phase2folds']
            self._agents: PPOTrainer = {
                0: self._make_agent(),
            }
            self.tot_num_steps_trained = 0

        @property
        def agent(self) -> PPOTrainer:
            return self._agents[self.phase]

        def _make_agent(self) -> PPOTrainer:
            config = self.config.copy()
            config['env_config']['folds'] = self.phase2folds[self.phase]
            agent = PPOTrainer(config=config, env=config['env'])
            return agent

        def _update_phase(self, report: dict):
            # No walk-forward, never go to the next step.
            next_phase = self._report2phase(report)
            if self.phase != next_phase:
                self._agents[next_phase] = self._make_agent()
            self.phase = next_phase

        def _report2phase(self, report: dict) -> int:
            """after 50k steps, next phase without transfer learning"""
            next_phase = self.phase
            if report['info']['num_steps_trained'] >= 50000:
                next_phase += 1
                # TODO: need to save?
            return next_phase

        def _train(self) -> dict:
            report = self.agent.train()
            self.tot_num_steps_trained += report['timesteps_this_iter']
            report['tot_timesteps'] = self.tot_num_steps_trained
            self._update_phase(report)
            return report

        def _save(self, checkpoint_dir):
            self.agent._save(checkpoint_dir)

        def _restore(self, checkpoint_path):
            self.agent._restore(checkpoint_path)

        def _log_result(self, result):
            self.agent._log_result(result)

        def _stop(self):
            self.agent._stop()

        def _export_model(self, export_formats, export_dir):
            self.agent._export_model(export_formats, export_dir)

**Comment by ericl** [comment]
> What's the recommended checkpoint path or directory should be used to save and restore multiple agents within a single Trainable?

Could you make subdirectories for each agent, and save into each of those? Then, restore could read each subdirectory and restore the individual agents from that.

> Is agent.save the only thing needed to save everything that could possibly be saved of the trained agent (weights, parameters, config, etc)?

Yep, all state you want to checkpoint should be included in save -- though the config is provided already before the restore so that's optional.
