### ISSUE TITLE
[rllib] a question on rollout

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5086]
### Describe the problem

In rollout() function of rllib/rollout.py, `action_init` is initialized (assigned) in the first branch while no `action_init` in the second branch (see https://github.com/ray-project/ray/blob/master/python/ray/rllib/rollout.py#L133 ). My script crashed due to no `action_init` when it was used in the while loop (see https://github.com/ray-project/ray/blob/master/python/ray/rllib/rollout.py#L152 )

### Source code / logs

https://github.com/ray-project/ray/blob/master/python/ray/rllib/rollout.py#L120

**Comment by ericl** [comment]
Looks like a bug, seems like we should init it to some random actions in that branch as well, or avoid referencing actions_init.
