### ISSUE TITLE
[rllib] Deep Exploration via Bootstrapped DQN

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5087]
### Describe the problem

Last year's winner of NIPS RL Challenge (on Prosthetics Simulator) declared that [Deep Exploration via Bootstrapped DQN](https://arxiv.org/abs/1602.04621) is very effective in exploring such a huge space and results in very natural gait of their human model. As this year's NIPS RL Challenge has began, I think it is necessary for RLLib to provide such an important facility in case some participants want to try this.

### Source code / logs

@ericl  Do you have any suggestion in developing this exploration strategy? I think it is like the Tompson sampling in bandit where more than one networks are ensembled. Concretely, each time for taking an action, one network is sampled to make inference. And different mini-batches are sampled to train each network respectively. I can take this development task but I want to respect your design.

**Comment by ericl** [comment]
Hm, with the new ModelV2 formulation of DQN, I wonder if this can be done pretty simply with a custom model with multiple heads. A random mask based on the data can be used to train heads with different portions of the dataset.

The only change that needs to be added to the algorithm is make sure the same mask is used for the duration of a single episode to enable deep exploration.

**Comment by joneswong** [comment]
Yes, what you described is a good design! Actually, users can try different kinds of bootstrap distributions, which requires the replay buffer to store additional field. Here, for simplicity, I think we could just assume a all-one bootstrapped mask, indicating that all heads can consume each (s, a, r, s'). Thus, in each update, we randomly update one head. This is theoretically equivalent to ensemble.

**Comment by joneswong** [comment]
I prefer to implement it and propose a pull-request as a feature (option) for DQN&DDPG users. Do you allow this? @ericl

**Comment by richardliaw** [comment]
Yes, propose a pull-request!

**Comment by MasterScrat** [comment]
@joneswong were you able to make any progress in this direction?
