### ISSUE TITLE
[rllib] Custom metrics that are not in state space

### ISSUE THREAD

**Issue by antoine-galataud** [ray-project/ray#5088]
Hi!

What would be the best way to create custom metrics (as described in https://ray.readthedocs.io/en/latest/rllib-training.html#callbacks-and-custom-metrics) that are not based on observations? Examples show the use of `info["episode"]`, so I guess the way to go would be to register and fill custom metrics through this structure?

Thanks

**Comment by ericl** [comment]
Yep, you have full access to the episode object (and you can use the episode as a place to store attributes from other callbacks as well).
