### ISSUE TITLE
[rllib] Example Rllib: custom_train_fn.py 

### ISSUE THREAD

**Issue by mkrech** [ray-project/ray#5089]
Hi RLlib Team,
I have an Error Message "'Resources' object has no attribute 'to_json'" when I executed the example Script: custom_train_fn.p.py.

Perhaps you have an Idea how to solve it.

Cheers
Michael

### System information
- **OS Platform and Distribution Ubuntu 16.04.6 LTS**:
- **Ray installed from (binary)**:
- **Ray version**: 0.7.1
- **Python version**: 3.6.8
- **Exact command to reproduce**: python custom_train_fn.py

### Describe the problem
Starting the the example script custom_train_fn.py, it  ends with following 
Error description:

Traceback (most recent call last):
  File "/home/michaelmkrech@bku.db.de/sbs_phase_2/projects/sbs_0202_tune_010/src/custom_train_fn.py", line 45, in <module>
    resources = PPOTrainer.default_resource_request(config).to_json()
AttributeError: 'Resources' object has no attribute 'to_json'

https://github.com/ray-project/ray/blob/master/python/ray/rllib/examples/custom_train_fn.py

**Comment by richardliaw** [comment]
This should work; can you provide a longer stack trace? Or print the class/file of ` PPOTrainer.default_resource_request(config)`?

**Comment by ericl** [comment]
I think you probably have an older version of ray installed, which does not have that function.

**Comment by mkrech** [comment]
Hi,
thank you @ericl.

pip install -U ray  helps.

I installed now ray 0.7.2. and the Error disapear.

Cheers
Michael
