### ISSUE TITLE
[tune] Confusing behaviour of ExperimentAnalysis when multiple experiments_state*.json are present

### ISSUE THREAD

**Issue by sotte** [ray-project/ray#5090]
### System information
- **OS Platform and Distribution**: Ubuntu 19.04
- **Ray installed from (source or binary)**: binary, pip
- **Ray version**: 0.7
- **Python version**: 3.7

### Describe the problem
In general, I find the behaviour of `ExperimentAnalysis` a bit odd. One can specify the folder for experiments (not the `experiment_state*.json`), then `ExperimentAnalysis` globs for all `experiment_state*.json` in that folder, and then it drops all but the last (i.e. max) experiment without any warning.

This makes it impossible to analyze any experiment except the newest/max.

My initial assumption was that one has to specify one concrete `experiment_state.json` file and all trials of that experiment are loaded. Alternatively, when a folder is specified, all experiments and all trials would be loaded. This is clearly not the case.

I'm suggesting that `ExperimentAnalysis` only accepts `experiment_state.json` files, not folders. What do you think?

(`ExperimentAnalysis` would also benfit from a nice `__repr__` and other convenient methods like `__len__` and `__getitem__`.)

**Comment by richardliaw** [comment]
Hi @sotte, this is a good idea. I'll take a crack at this today. Would you be willing to provide some feedback on the PR? 

At a high level, I'll introduce a new `Analysis` object that will read all experiments and trials in the folder, and scope the `ExperimentAnalysis` object to only read `experiment_state.json` files.

**Comment by richardliaw** [comment]
For now, #5115 can address your suggestion. I'll implement the Analysis class later.

**Comment by sotte** [comment]
Hey @richard4912, thanks for the quick reply and yes, I'm more than happy to give some feedback in #5115.
