### ISSUE TITLE
[SGD] Deprecate old TF SGD code

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#5093]
### Describe the problem

`ray.experimental.sgd` is current borken. We can't run the `mnist_example.py` because `plasma.build_tensorflow_op` is failing with:
```
subprocess.CalledProcessError: Command '['g++', '-std=c++11', '-g', '-shared', '/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/tensorflow/plasma_op.cc', '-o', '/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/tensorflow/plasma_op.so', '-DNDEBUG', '-I/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow/include', '-L/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/pyarrow_files/pyarrow', '-lplasma', '-larrow_python', '-larrow', '-fPIC', '-I/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=0', '-L/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow', '-ltensorflow_framework', '-O2', '-DGOOGLE_CUDA']' returned non-zero exit status 1.

 /usr/bin/ld: cannot find -lplasma
 /usr/bin/ld: cannot find -larrow_python
 /usr/bin/ld: cannot find -larrow
```

@pcmoritz suggests we should deprecate the parts that's currently not working. 

@pschafhalter can you take a look at this can deprecate the part that's no longer needed?

**Comment by pcmoritz** [comment]
The plan going forward is to do something similar to https://github.com/ray-project/ray/pull/4797 for TensorFlow.

**Comment by pschafhalter** [comment]
If it's broken, I'd personally favor removing the old tensorflow implementation since no one is developing it currently.

@pcmoritz, do you think this is a good idea? I wouldn't want to diminish any past contributions by other developers.

**Comment by richardliaw** [comment]
Yes, let's please remove the old tf implementation. I'm 💯 for that.
