### ISSUE TITLE
format.sh script returns illegal option -o pipefail

### ISSUE THREAD

**Issue by 1beb** [ray-project/ray#5094]
### System information
- Ubuntu 19.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: Master branch
- **Python version**: 3.7.3
- **Exact command to reproduce**: `sh scripts/format.sh`

### Describe the problem

When trying to run sh scripts/format.sh receive an error: 

```
Received an error trying to run it: 6: set: Illegal option -o pipefail
```

I could not diagnose the problem as shell is not my forte, but recommend you look into it as other contributors may suffer from the same problem. Removing the option led to a builtin not found complaint.

**Comment by simon-mo** [comment]
`bash scripts/format.sh` should work.

**Comment by 1beb** [comment]
Without attempting to sound malicious, I wouldn't have posted if it worked
with an error that I could have solved by way of a simple Google search. I
can provide any additional information you require.

**Comment by 1beb** [comment]
My bad, I'll try it.

**Comment by simon-mo** [comment]
Sorry I should be more clear. Ubuntu sh is linked to `dash` not `bash`.  `pipefail` is a bash utility.

```
ubuntu@ip-172-31-23-126:~$ cat /etc/os-release | grep VERSION
VERSION="19.04 (Disco Dingo)"
VERSION_ID="19.04"
VERSION_CODENAME=disco
ubuntu@ip-172-31-23-126:~$ cat test.sh
set -eo pipefail
echo "done"
ubuntu@ip-172-31-23-126:~$ bash test.sh
done
ubuntu@ip-172-31-23-126:~$ sh test.sh
test.sh: 1: set: Illegal option -o pipefail
```

**Comment by 1beb** [comment]
Worked, closing. Perhaps the default "I have run scripts/format.sh" on PR should be updated to say "use bash not sh".
