### ISSUE TITLE
[tune] How to install tune CLI

### ISSUE THREAD

**Issue by bfortuner** [ray-project/ray#5096]
Hey, this might be a silly question, but how I install the tune cli show here?

https://ray.readthedocs.io/en/latest/tune-usage.html#tune-cli-experimental

```
$ tune --help
No command 'tune' found
```
I pip installed ray, my version is:
ray==0.7.0

**Comment by richardliaw** [comment]
Hm, that's odd ... the CLI was introduced in 0.6.5 - maybe try uninstalling ray multiple times and then re-installing; it's possible that there is just some odd path lookup that's missing it.

**Comment by bfortuner** [comment]
Hilariously that worked. Thanks!!
