### ISSUE TITLE
[tune] Missing keep_checkpoints_num arg in tune

### ISSUE THREAD

**Issue by morgangiraud** [ray-project/ray#5105]
Hi everybody,

Thanks a lot for this lib, I've been using for the past few weeks with TF2 and it works pretty well!

In my current use case, I'm checkpointing regularly to ensure a minimal loss in the face of OOM. I do control TF checkpoints manually to avoid filling my disk space but I still need to dump some ray metadata (iterations count, etc.).
I've noticed that ray create folders like `checkpoint_{iter}` to store those but from `tune` there is no way to tell him that I don't need to keep dozens of folder.
I also noticed that `experiment`, and `trial` classes have the perfect argument: `keep_checkpoints_num`.

Sadly this argument is missing from the `tune` config. 
Is there any reasons why it is missing from `tune` arguments?

Have a nice day.

**Comment by richardliaw** [comment]
No particular reason, we just missed it - would you be willing to make a PR?

**Comment by morgangiraud** [comment]
👍   I've linked the PR to the issue.
