### ISSUE TITLE
Unsupported (continuous) action space for DDPG -- request for extended action space

### ISSUE THREAD

**Issue by NickMcCarthy101** [ray-project/ray#5107]
**System Information**

- **OS Platform and Distribution (e.g., Linux, Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**: 0.7.1
- **Python version**: 3.6 

**Command to reproduce**: 
I am attempting to run the following experiment, as so. 

`experiment = tune.Experiment(
    name='2folds-DDPG',
    run=rllib.agents.ddpg.DDPGTrainer,
    stop={"timesteps_total": 1000000},
    config=deepcopy(config),
    num_samples=1,
    local_dir='logs',
    checkpoint_at_end=True,
    max_failures=0,
    loggers=[CustomLogger])
`

`trials = tune.run_experiments(
    experiments=experiment,
    search_alg=tune.suggest.BasicVariantGenerator(),
    scheduler=tune.schedulers.FIFOScheduler(),
    verbose=1,
    reuse_actors=False,
    resume=False,)
`

with the following configuration: 

`config = [rllib.agents.ddpg.DEFAULT_CONFIG.copy()]
config['callbacks']['on_train_result'] = tune.function(calculate_tearsheet)
config['num_workers'] = 6
config['gamma'] = 0 # tune.grid_search([0])
config['use_lstm'] : False
config['batch_mode'] = 'complete_episodes'
config['sample_batch_size'] = tune.grid_search([1])
config['train_batch_size'] = tune.grid_search([256])
`

**NOTE:** The environment is a custom-built environment with a continuous action space, for which a limited amount of information can be given. However, in brief the class inherits from `gym.extra_spaces.Simplex`, with arguments: 
- shape = number of actions 
- concentration = the alpha parameter in np.random.dirichlet 
- dtype= np.float32 

**Example**:
![Screenshot 2019-07-03 at 00 37 24](https://user-images.githubusercontent.com/32033079/60553331-be652e00-9d2a-11e9-9b08-43c41e562c73.png)
 

If you feel like you need more information about the type of action-space that I am using, please let me know and I will endeavour to give you more information. 

**Issue at hand**: 

While there are a few lines of code that can be commented out in Ray (lines 74-77 in ddpg_policy.py), which of course is never the best idea anyway, that bypass the raised exceptions (that state that the provided state-action space is not supported by the current DDPG agent), It seems that the problem exists deeper into the code and the way in which the DDPG action-space is constructed. 

With this in mind, could I request a feature for this agent: namely, to extend the allowed action-spaces to more than just the Box gym space that it currently supports. 

**Traceback error**:

<img width="663" alt="Screenshot 2019-07-03 at 00 18 51" src="https://user-images.githubusercontent.com/32033079/60553358-de94ed00-9d2a-11e9-86fa-296d61fd8f1a.png">

<img width="664" alt="Screenshot 2019-07-03 at 00 19 03" src="https://user-images.githubusercontent.com/32033079/60553361-e2c10a80-9d2a-11e9-98c5-524ff202b202.png">

**Comment by ericl** [comment]
Yeah, DDPG currently only supports Box. @joneswong do you think it would be hard to support other types of action spaces?

**Comment by NickMcCarthy101** [comment]
Hi Eric (and the Ray team), 

Thank you very much for your continued work on Ray — it’s extremely impressive and find it very useful. 

I am also hoping to use the incoming SAC implementation (https://github.com/ray-project/ray/pull/3677 <https://github.com/ray-project/ray/pull/3677>) when it is successfully merged, however I am a little unsure of it’s current progress — and was curious if there is anything that I can do to help the process along. I’ve been in contact with Kristian (https://github.com/hartikainen <https://github.com/hartikainen>), who outlined what needs to be done, but has yet to respond with any large amount of details. 

I look forward to hearing back from you. 


Best regards, 

Nick

**Comment by ericl** [comment]
@NickMcCarthy101 The current PR has some performance regressions on Pendulum. Perhaps the best thing to do would be reproduce the exact numerical gradients etc. of the softlearning repo here: https://github.com/rail-berkeley/softlearning/blob/master/README.md. This would require setting the same seeds, using identical samples from the replay buffer, etc.

**Comment by josjo80** [comment]
Isn't Box used for continuous action space?  Each element is one of the N-dimensions in the array with their own upper and lower limits.  Valid values should fall within those limits.
