### ISSUE TITLE
[ray] failed to install from source

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5113]
### System information
- **CentOS 7**:
- **Ray installed from source**:
- **master**:
- **Python 3.6**:
- **pip install -e . --verbose**:

### Describe the problem

ERROR: /home/jones.wz/.cache/bazel/_bazel_jones.wz/aba1f08e07de240a5638439726886107/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:29:5: **no such package '@boringssl//'**: java.io.IOException: thread interrupted and referenced by '//external:libssl'
DEBUG: Rule 'plasma' modified arguments {"shallow_since": "1561760344 +0900"}
ERROR: Analysis of target '//:ray_pkg' failed; build aborted: Analysis failed

**Comment by simon-mo** [comment]
@pcmoritz any idea?

**Comment by joneswong** [comment]
I am not sure what exactly is the CentOS version. Actually, it is customized by Alibaba. I think there must be some very low-level issue. Even though I have tried installing openssl, there is still the issue. I have to use Ubuntu as a workaround. Thanks anyway!
