### ISSUE TITLE
Import thread error when new workers are started (regression from 0.7.1 -> 0.7.2)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5125]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: DLAMI, latest
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.6
- **Exact command to reproduce**: ci/long_running_tests/workloads/impala.py

### Describe the problem

When the number of workers in the impala stress tests are large enough that new worker processes must be created by the raylet, this causes the following import thread errors. The errors disappear when no new workers need to be started.

### Source code / logs

![Screenshot from 2019-07-05 12-07-18](https://user-images.githubusercontent.com/14922/60741403-14e68e00-9f1e-11e9-9b4d-2f6fd8b68f47.png)

![Screenshot from 2019-07-05 12-05-07](https://user-images.githubusercontent.com/14922/60741399-10ba7080-9f1e-11e9-8888-1a3e792018f7.png)

**Comment by ericl** [comment]
This appears to be a regression in 0.7.2 (0.7.1 works fine). @raulchen @guoyuhong do you know of any changes that might have caused this in 0.7.2?

**Comment by ericl** [comment]
```
(tensorflow_p36) ubuntu@ip-172-30-0-247:~/ray$ git bisect bad
0131353d42f20f28034480d45918130525fb0377 is the first bad commit
commit 0131353d42f20f28034480d45918130525fb0377
Author: Hao Chen <chenh1024@gmail.com>
Date:   Wed Jun 26 05:31:19 2019 +0800

    [gRPC] Migrate gcs data structures to protobuf (#5024)

:100644 100644 da36eec0cf577c17c74de0f175ff9d43c2a6dfbc bc9e6bcd8006f38cd67d4aa0f2df59997af43cdd M      BUILD.bazel
:040000 040000 4b1fa13ff9d5b9d6e6cf2b4d7f87602f05246c0a 2ba22642cc7ee141dd6fb2862dbc4e7cae933c94 M      bazel
:040000 040000 b22194922dc6dbf98781defefaf34f5ede4d9b55 88031d808a342e518f77f717f90e8ce39b1e2b30 M      doc
:040000 040000 4db0d325f3372333a7d7266e47653e13baf3e7de f7b0f35b554b96337592b32b77f1f1a17f14f60b M      java
:040000 040000 eba3fb4cc20cdb432140b1c55f18eb918224d719 83025f577ea9eb234352b52dfd2d8d1cba6bc479 M      python
:040000 040000 0acec8a9958badb7d56cc1bb9bedacc101ff9ae8 cfc1a4a0be3d42d66c1e3343957eeb0754f639d3 M      src
```

**Comment by ericl** [comment]
@raulchen it seems that https://github.com/ray-project/ray/pull/5024 causes this failure.

Interestingly, it seems that previous PRs have some of the exceptions printed as warnings, but it doesn't cause an actual crash. Only after 0131353d42f20f28034480d45918130525fb0377 do crashes actually occur.

**Comment by raulchen** [comment]
I'll take a look today.

**Comment by raulchen** [comment]
When I added `import ray.rllib.evaluation.sampler` before [this line](https://github.com/ray-project/ray/blob/master/python/ray/import_thread.py#L131), the issue is gone. 

I think this is because when serializing the function (which is `register_class_for_serialization` ), `RolloutMetrics` is already imported. But when deserializing the function, but when deserializing the function, that class isn't imported yet. 

I think this should had existed before. But don't understand why my PR triggered it.

**Comment by ericl** [comment]
@robertnishihara is the import supposed to be automatically taken of by the import thread? I assume that this is a normal situation that should be handled by deserialization. Maybe the import thread is not processing the imports.

**Comment by ericl** [comment]
I'm reading `import_thread.py`, and is it possible that new workers aren't executing the same set of keys in _process_key after that PR due to some string comparison issue?

**Comment by raulchen** [comment]
> I'm reading `import_thread.py`, and is it possible that new workers aren't executing the same set of keys in _process_key after that PR due to some string comparison issue?

You mean [this key](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L763)? I debugged this locally and printed this key. The key at this line is the same as the key that `import_thread` received. 

Also, that PR only touches GCS table API. While the import thread uses Python redis client directly. It shouldn't be impacted.

**Comment by raulchen** [comment]
I'm now able to reproduce this issue with the following script.
```python
@ray.remote(num_cpus=0)
def f():
    from ray.rllib.evaluation.sampler import RolloutMetrics
    return RolloutMetrics(1, 2, 3, 4, 5)


ray.init(num_cpus=1)

results = [f.remote() for _ in range(10)]
print(ray.get(results))
```
This script won't fail, but I can see following error messages.
```
2019-07-11 12:42:32,926 ERROR worker.py:1676 -- Traceback (most recent call last):
  File "/Users/haochen/code/ant_ray/python/ray/import_thread.py", line 131, in fetch_and_execute_function_to_run
    function = pickle.loads(serialized_function)
AttributeError: Can't get attribute 'RolloutMetrics' on <module 'ray.rllib.evaluation.sampler' from '/Users/haochen/code/ant_ray/python/ray/rllib/evaluation/sampler.py'>
```

I think this is what happened:
1. The first worker that executes the `f` method will trigger [this line](https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L322), and then hit `run_function_on_all_workers`. 
2. For other workers, if they receive the task before receiving `FunctionsToRun`, it's okay. If the order is reversed, [this line](https://github.com/ray-project/ray/blob/691c9733f95a28d9a1ceeb291eda94a2ffd93cdd/python/ray/import_thread.py#L131) will fail because `RolloutMetrics` hasn't been imported yet.

**Comment by robertnishihara** [comment]
@raulchen do you understand why this line
https://github.com/ray-project/ray/blob/691c9733f95a28d9a1ceeb291eda94a2ffd93cdd/python/ray/import_thread.py#L131
would fail if `RolloutMetrics` hasn't been imported? It should automatically be imported in by cloudpickle if it is needed. Is this a potential bug in cloudpickle (that wouldn't be surprising), or is this behavior expected?

**Comment by raulchen** [comment]
cloudpickle should automatically handle imports. 

It seems that something specific to `RolloutMetrics` caused this issue. I tried changing `RolloutMetrics` to another dummy `namedtuple`, the issue was gone.

@ericl do you know what is contained in `RolloutMetrics`?

**Comment by ericl** [comment]
RolloutMetrics is just an extension of named_tuple. It could be that, or some bug handling the nested import. Either way, it seems reasonable to avoid the nested import for now since that's kind of a more advanced case.

Could you try this diff out to see if the error disappears if the nested import is removed?

```
diff --git a/python/ray/rllib/evaluation/metrics.py b/python/ray/rllib/evaluation/metrics.py
index 341327608..3bba8c392 100644
--- a/python/ray/rllib/evaluation/metrics.py
+++ b/python/ray/rllib/evaluation/metrics.py
@@ -15,6 +15,11 @@ from ray.rllib.utils.memory import ray_get_and_free
 
 logger = logging.getLogger(__name__)
 
+RolloutMetrics = collections.namedtuple("RolloutMetrics", [
+    "episode_length", "episode_reward", "agent_rewards", "custom_metrics",
+    "perf_stats"
+])
+
 
 @DeveloperAPI
 def get_learner_stats(grad_info):
@@ -161,8 +166,6 @@ def summarize_episodes(episodes, new_episodes, num_dropped):
 def _partition(episodes):
     """Divides metrics data into true rollouts vs off-policy estimates."""
 
-    from ray.rllib.evaluation.sampler import RolloutMetrics
-
     rollouts, estimates = [], []
     for e in episodes:
         if isinstance(e, RolloutMetrics):
diff --git a/python/ray/rllib/evaluation/sampler.py b/python/ray/rllib/evaluation/sampler.py
index 47964c3c5..f87639bd2 100644
--- a/python/ray/rllib/evaluation/sampler.py
+++ b/python/ray/rllib/evaluation/sampler.py
@@ -10,6 +10,7 @@ import threading
 import time
 
 from ray.rllib.evaluation.episode import MultiAgentEpisode, _flatten_action
+from ray.rllib.evaluation.metrics import RolloutMetrics
 from ray.rllib.evaluation.sample_batch_builder import \
     MultiAgentSampleBatchBuilder
 from ray.rllib.policy.tf_policy import TFPolicy
@@ -24,11 +25,6 @@ from ray.rllib.policy.policy import clip_action
 
 logger = logging.getLogger(__name__)
 
-RolloutMetrics = namedtuple("RolloutMetrics", [
-    "episode_length", "episode_reward", "agent_rewards", "custom_metrics",
-    "perf_stats"
-])
-
 PolicyEvalData = namedtuple("PolicyEvalData", [
     "env_id", "agent_id", "obs", "info", "rnn_state", "prev_action",
     "prev_reward"
```

**Comment by ericl** [comment]
That actually does not fix the issue.

**Comment by ericl** [comment]
I compared the functions executed by import_thread for both actors that succeeded and those that failed (those that started later in response to worker pressure). The sequence of fetches executed by import thread are identical down to the byte. So the issue must be from somewhere else.
