### ISSUE TITLE
Clarification of batch_mode behaviour

### ISSUE THREAD

**Issue by bmazoure** [ray-project/ray#5126]
### System information
**Ubuntu 18.04**
**Ray installed from source: master**
**Python 3.6**

Describe the problem
Not an error per say. From the docs, the behaviour of samples was not immediately clear when `batch_mode=complete_episodes` is set.

For instance, from the description:

> "truncate_episodes": Each call to sample() will return a batch
                    of at most `batch_steps * num_envs` in size. The batch will
                    be exactly `batch_steps * num_envs` in size if
                    postprocessing does not change batch sizes. Episodes may be
                    truncated in order to meet this size requirement.
                "complete_episodes": Each call to sample() will return a batch
                    of at least `batch_steps * num_envs` in size. Episodes will
                    not be truncated, but multiple episodes may be packed
                    within one batch to meet the batch size. Note that when
                    `num_envs > 1`, episode steps will be buffered until the
                    episode completes, and hence batches may contain
                    significant amounts of off-policy data.

From this, I infer the following structure of the batch given to `compute_gradients` with a batch size of B:
```
   |(s_t,a,r,s_tp1,done=False,weight) ----> t=0
   |(s_t,a,r,s_tp1,done=False,weight) ----> t=1
B  ...
   |(s_t,a,r,s_tp1,done=True,weight) ----> t=T (Episode ends here)
   |(s_t,a,r,s_tp1,done=False,weight) ----> t=0 (New episode starts)
```

Is that correct?

**Comment by ericl** [comment]
It basically determines if episodes get truncated/chopped up into multiple unrolls. For some algorithms such as PPO, this will cause the value estimate at the end of that unroll to be determined by the value function.

Here's a figure: https://ray.readthedocs.io/en/latest/rllib-training.html#specifying-resources

This does not affect really the batches given to compute_gradients/learn_on_batch, which are of size at least `train_batch_size` and may contain multiple unrolls. In complete episodes mode, in some cases the episode lengths may be long enough to force train batch size to be larger to fit them all.

**Comment by bmazoure** [comment]
Thank you for the clarification, I'll close the issue.
