### ISSUE TITLE
[tune] keep_checkpoints_num logic should be in trainable

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5127]
Right now, `keep_checkpoints_num` has multiple actor calls that block the control loop. All of this can be implemented on the worker, having the Trainable keep track of the checkpoint history, and removing checkpoints as needed. The driver should also mirror this by using `rsync --delete`.

**Comment by richardliaw** [comment]
cc @dulex123

**Comment by dulex123** [comment]
Agreed, will get to it as soon as I can
