### ISSUE TITLE
Using custom env without gym.Env

### ISSUE THREAD

**Issue by AmrMKayid** [ray-project/ray#5137]
### System information
- **OS Platform and Distribution**: macOS Mojave Version 10.14.5
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.1
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem

Is there a way to use other rl environments like Unityagents or DeepMind Control Suite instead of gym environment?
and How can we register these environments?

**Comment by FedericoFontana** [comment]
The answer appears to be negative ([source](https://ray.readthedocs.io/en/latest/rllib-env.html#rllib-environments)). However, a workaround might be to wrap unsupported environments within `gym.Env`.

**Comment by ericl** [comment]
You could write a wrapper that implements VectorEnv or BaseEnv, but it's probably easier in many cases to wrap it in a gym.Env.

**Comment by AmrMKayid** [comment]
@FedericoFontana @ericl Thank you very much for your replies.

@ericl regarding the VectorEnv, are there any examples on how to register them?
Also, for each unity env, I need to assign a different worker_id how can it be implemented to work with parallel algorithms like PPO?

**Comment by ericl** [comment]
@AmrMKayid regarding VectorEnvs, they can be registered directly the same as gym.Env (the make_env function can return any of gym.Env, VectorEnv, BaseEnv, etc. types).

For the worker ids, you can get that from the env_config object passed to the env constructor. ``env_config.worker_index`` uniquely identifies the worker: https://ray.readthedocs.io/en/latest/rllib-env.html#configuring-environments

**Comment by AmrMKayid** [comment]
@ericl Thank you very much. your replies helped me a lot!
