### ISSUE TITLE
Error linking boost regex on Mac OS.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#514]
Some people are seeing the following error on Mac OS when building Ray. Could be related to #464.

```
ld: library not found for -lboost_regex
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/numbuf/libnumbuf.so] Error 1
make[1]: *** [src/numbuf/CMakeFiles/numbuf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by atumanov** [comment]
as a workaround, you might want to try passing a `-L/usr/local/Cellar/boost/1.62.0/lib/libboost_regex` compiler flag in cmake. The exact path may vary, but you can find out exactly what it is for your brew boost install with `brew list boost`

**Comment by wesm** [comment]
boost_regex is no longer a dependency of Arrow, so you can remove this altogether

**Comment by robertnishihara** [comment]
Can someone who was experiencing this problem confirm that the problem is fixed?

**Comment by akmorrow13** [comment]
Yes it works! For a minute I was having an issue with the hardcoded arrow commit at https://github.com/ray-project/ray/blob/master/src/numbuf/thirdparty/download_thirdparty.sh#L15 (error shown below):

```
+ cd /--/--/--/ray/src/numbuf/thirdparty/arrow
+ git checkout 670612e6fdf699486641ed0d39d22257eb8acdb2
fatal: reference is not a tree: 670612e6fdf699486641ed0d39d22257eb8acdb2
Traceback (most recent call last):
```

Not sure why the error went away, I had internet connection both times. But installation worked.

**Comment by pcmoritz** [comment]
@akmorrow13 This typically means that arrow was not recloned because it already exists, but it is an old version that doesn't have the specific commit. As a workaround, you can delete the directory `ray/src/numbuf/thirdparty/arrow` and try again. To solve the problem, I created a PR here: https://github.com/ray-project/ray/pull/538

**Comment by robertnishihara** [comment]
Thanks for trying that out!
