### ISSUE TITLE
Ray plasma store leaking memory? 

### ISSUE THREAD

**Issue by zygm0nt** [ray-project/ray#5142]
### System information

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS x86_64
* Ray installed from (source or binary): binary (pip install ray)
* Ray version: 0.7.0
* Python version: Python 2.7.0 :: Continuum Analytics, Inc.
* Exact command to reproduce: python main.py

### Describe the problem

With the attached code I see a gradual memory usage increase. After a couple iterations the memory used on the system is almost twice the initial amount. In my observations it lead to an error saying:

```
The task with ID 0000000068bac03de106eacc28a6915dda9a2b80 is a driver task and so the object created by ray.put could not be reconstructed.
```

which seems related to plasma strore memory size. The error seems to be caused by passing big arguments into the remote function - `small_data_1` and `small_data_2`. 

IMO this is related to following issues, however none of the proposed solutions solved my problem.

* https://github.com/ray-project/ray/issues/2430
* https://github.com/ray-project/ray/issues/313

The code attached runs for some time before reaching the described condition, but it can be forced to occur earlier, by setting plasma store memory to lower values. This gives me an error immediatelly, saying:

```
2019-07-08 07:41:52,424 INFO node.py:497 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-08_07-41-52_424605_3614/logs.
2019-07-08 07:41:52,529 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:23041 to respond...
2019-07-08 07:41:52,636 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:61859 to respond...
2019-07-08 07:41:52,638 INFO services.py:806 -- Starting Redis shard with 2.0 GB max memory.
2019-07-08 07:41:52,648 INFO node.py:511 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-08_07-41-52_424605_3614/logs.
2019-07-08 07:41:52,649 INFO services.py:1441 -- Starting the Plasma object store with 2.0 GB memory using /dev/shm.
2019-07-08 07:42:04,170 ERROR worker.py:1678 -- The task with ID 0000000068bac03de106eacc28a6915dda9a2b80 is a driver task and so the object created by ray.put could not be reconstructed.
```

The way I understand this error message is that ray was able to properly serialize function arguments and execute the function but there is not enough space for the returned value in plasma store. If that is correct than seeing this behaviour after multiple iterations is a clear suggestion that there is something not being garbage collected in plasma store.

If my understanding of the issue is flawed, could you provide some hints as to the correct way of approaching the problem?

### Source code / logs

```
import ray
import random
import string
from numpy import ndarray

@ray.remote
def remote_function(x, y, small_data_1, small_data_2, counter, m_batch_id):
    l = x + y
    print("finishing {}-{} batch".format(counter, m_batch_id))
    return ndarray((1486008,),int)

mem = int(10**10)
ray.init(redis_max_memory=mem, object_store_memory=mem)
x_id = ray.put( ndarray((149255272,),int))
y_id = ray.put( ndarray((149255272,),int))

def rand_str(n=100000):
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(n))

for i in range(0, 282):
    result_ids = []
    for micro_batch_id in range(64):
        small_data_1 = rand_str()
        small_data_2 = rand_str()
        result_ids.append(remote_function.remote(x_id, y_id, small_data_1, small_data_2, i, micro_batch_id))
    t = [result for micro_batch_results in ray.get(result_ids) for result in micro_batch_results]
    print("got objects of length {}".format(len(t)))
```

**Comment by zygm0nt** [comment]
Also tried putting all the parameters through plasma store and than explicitly freeeing them after usage, but this seemed like even worse idea. The machine ran out of memory even faster.

**Comment by ericl** [comment]
I think the issue here is that the object store evicts objects LRU. So, the initial x_id put early on in the job could get evicted at some point unluckily.

A workaround would be to pin it in the object store with pin_in_object_store: https://ray.readthedocs.io/en/latest/tune-usage.html#handling-large-datasets

**Comment by zygm0nt** [comment]
@ericl your hint is great! I've added this to me example code and now it runs pretty stable.

Thanks!
