### ISSUE TITLE
Automated client-side linting

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#5152]
There are often problems with linting in PRs, wasting peoples' time and causing an excessive amount of CI failures. To save everyone time, it would be good to have linting run automatically on the client side before pushing changes.

I think the best solution would be to add a git `pre-push` hook that runs the existing `ci/travis/format.sh` script, but open to other suggestions. This would avoid running the linting on every commit, which could get annoying, and is easily bypassed when necessary using `git push --no-verify`.

**Comment by richardliaw** [comment]
I think this would be great; we can also include a message for bypass instructions.

**Comment by edoakes** [comment]
#5154
