### ISSUE TITLE
Issue launching remote actors from multiple sub-processes

### ISSUE THREAD

**Issue by opherlieber** [ray-project/ray#5163]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.1
- **Python version**: 3.6.8
- **Exact command to reproduce**: python -u ray_mp.py

### Describe the problem

When launching actors from sub-processes I am getting some strange behavior where the remote calls seem to be duplicating for each sub-process regardless of which one launched the actor.
I pasted an example below.

### Source code / logs

```
import multiprocessing as mp
import time
import ray

class Actor():
    def __init__(self, i):
        print("Actor",i,"init")

def proc(i):
    ray.init(redis_address = "localhost:6379")    
    print("Launching actor",i)
    actor = ray.remote(Actor).remote(i)
    time.sleep(5)

proc_count = 2
procs = []
for i in range(proc_count):
    p = mp.Process(target=proc, args=(i,))
    p.start()    
    procs.append(p)

print("Started", proc_count,"procs")    
for p in procs:
    p.join()
```

Output:
```
Launching actor 1
Launching actor 0
(pid=16875) Actor 1 init
(pid=16873) Actor 0 init
(pid=16875) Actor 1 init
(pid=16873) Actor 0 init
```

I created 2 actors but got 2 init calls for each one. Also additional remote calls to the actors would also duplicate. 
If I increase to 4 sub-processes I get 4 init calls per actor (16 total)

**Comment by richardliaw** [comment]
This is a great test (and a pretty major bug)! The issue here is that all `ray.init` calls creates individual drivers, and ray currently routes all messages from all workers to all drivers, giving you n^2 outputs.

**Comment by opherlieber** [comment]
Thanks Richard. Just to make sure I understood, the init() isn't actually called 'n' times, just the prints are duplicated right?
