### ISSUE TITLE
[tune] Weird best result

### ISSUE THREAD

**Issue by himat** [ray-project/ray#5165]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary 
- **Ray version**: 0.7.1
- **Python version**: 3.6.5

### Describe the problem

After running tuning with tune, I checked the `exp_name/experiment_state-<timestamp>.json` file, but for some reason, the `best_result` entry is always something like:
```
      "logdir": "./experiments-tune/proj0_data_geosplit_7layers_newdata_downsamp_tune_random_7layer_basiccnn/tune_trainable_53_lr=0.010213,momentum=0.16615,sched_dec
ay=0.96889,sched_step_size=17,weight_decay=0.14387_2019-07-10_06-07-08sdb_83fa",
      "runner": null,
      "result_logger": null,
      "last_debug": 1562739957.0680845,
      "trial_id": "dd66f8de",
      "error_file": null,
      "num_failures": 0,
      "custom_trial_name": null,
      "results": "80049502000000000000004e2e",
      "best_result": "80049502000000000000004e2e",
      "param_config": "80049502000000000000004e2e",
      "extra_arg": "80049502000000000000004e2e",
```
The `last_result` is available though:
```
 "max_failures": 3,
 "last_result": {
   "mean_loss": 0.6932336638371149,
   "mean_f1": 0.2913752913752914,
   "time_this_iter_s": 12.529258966445923,
   "done": true,
   "timesteps_total": null,
   "episodes_total": null,
   "training_iteration": 30,
   "neg_mean_loss": -0.6932336638371149,
   "experiment_id": "3aea1a4c1bd540a98b1f18cc08896877",
   "date": "2019-07-10_05-47-55",
   "timestamp": 1562737675,
   "time_total_s": 368.4967985153198,
   "pid": 787,
```

So why isn't the `best_result` available?

**Comment by richardliaw** [comment]
Ah, because `best` is only used by the `automl` package and for standard Tune usage, it's an empty field.

**Comment by himat** [comment]
So then what is the best way to find the best hyperparameters after an experiment is over?
Is it still what it says in this issue - loading all the json files manually into a df? https://github.com/ray-project/ray/issues/3391

**Comment by richardliaw** [comment]
Ah, no - there's a utility for this now! You can use `ExperimentAnalysis` in Tune: https://ray.readthedocs.io/en/latest/tune-package-ref.html#ray-tune-analysis
