### ISSUE TITLE
[tune] Actor IPs should be fetched from global state.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5168]
### Describe the problem
We call `ray.services.get_node_ip_address()` on Trainables, which can incur a very high latency for some reason. Instead, we can sidestep this by finding out the Raylet the actor is located with and the corresponding IP of the raylet.

This would accelerate node trial restarting under failure (which right now clogs the event loop, though since node failures are expected to be uncommon, shouldn't be a performance hit in the common case).

**Comment by fediazgon** [comment]
Hi, is someone working on it, can I take it?

**Comment by richardliaw** [comment]
Please do! Maybe do an initial overview of the tune code and let me know
your plan of action?

**Comment by fediazgon** [comment]
> Please do! Maybe do an initial overview of the tune code and let me know your plan of action?
It sounds fine to me
