### ISSUE TITLE
What should the behavior of ray.init be when it is called multiple times?

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#517]
`ray.init` currently throws an exception the second time it is called. However, it can be pretty common to call it multiple times (e.g., in an jupyter notebook where it is common to rerun cells).

There are a couple options.
- Throw an exception.
- Do nothing and print a warning.
- If it is called with the same arguments that were called the first time, do nothing, otherwise throw an exception.
- Kill everything from the previous `ray.init` and run it again.

**Comment by xgong** [comment]
I would like to vote the option "Do nothing, and probably print a warning." I did not go through the code base very deeply. But if we have something like, internal state, we should base on the current internal state to make the decision on what is the next action.

**Comment by robertnishihara** [comment]
Thanks! That option will definitely improve the experience of using Ray interactively (e.g., in an interpreter). However, if it happens in a script, then it is probably a bug. That said, it's probably the way to go.

**Comment by pcmoritz** [comment]
Either this option or "If it is called with the same arguments that were called the first time, do nothing, otherwise throw an exception." sound good to me. The second one has the advantage that it can catch some kinds of errors (i.e. having ray.init twice in a script), any downside compared to "Do nothing, and probably print a warning."?

**Comment by mitar** [comment]
Why not having this as an option argument to `ray.init`? Or we could have `ray.init` and `ray.ensure_init`? The first one throws, the second one makes sure it was called once, but then it is happy.

**Comment by robertnishihara** [comment]
An optional argument to `ray.init` might not be so bad, but I'd argue for having a very high bar for adding more functionality and new methods to the API.

**Comment by alok** [comment]
I'd lean towards having an optional argument. I'm not sure what the default to that argument should be, but since people writing scripts are generally more OK with typing a bit more, perhaps we should favor interactive users for this.

**Comment by robertnishihara** [comment]
You can call `ray.init(ignore_reinit_error=True)`, which is a no-op if `ray.init()` has already been called.
