### ISSUE TITLE
[CI] Ray CI Bot Feature List

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#5178]
This issue thread is used to document features to be added for the up coming ray-bot managing PRs. 

It will implement the following features:
- [ ] Detect PR from main repo branches and ask for submitting PR from a fork
- [ ] Detect and summarize test failures
- [ ] Delete jenkins comments and summarize it in test failures thread
- [ ] Report a summary of the changes (what module was changed?) and suggest reviewers. 

Please feel free to add and suggest new features!

**Comment by pcmoritz** [comment]
We will also need a way for people to sign the CLA
