### ISSUE TITLE
[rllib] how does Ray seed different actors

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5194]
### Describe the problem

I noticed that `worker_index` is used to seed environment of each actor. However, I cannot find any invocation of `seed()` method (defined in utils/seed.py). I also try to grep `tf.set_random_seed()` and got only utils/seed.py. So how does Ray seed each actor? Without the different seeds, their noise (for exploration) would be identical and lose the advantage of actor(s)-learner architecture.

**Comment by ericl** [comment]
There is actually no seed, so it is completely random by default.

**Comment by joneswong** [comment]
> There is actually no seed, so it is completely random by default.

When there are many actors, some of them that are instantiated at the same time might behave in the same way due to the identical initial random seed (i.e., time). Although network parameters are synced with the learner periodically, the OU/Gaussian noise samples might be identical which waste these actors. I think we need a mechanism to seed the actors.

**Comment by ericl** [comment]
That makes sense... we could potentially seed by worker_index plus some random seed generated at the trainer.
