### ISSUE TITLE
[rllib] Throughput decreases as the trainer waits for metrics

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5198]
### Describe the problem

I ran APEX-DDPG with parameter space noise (under `completed_episode` setting) on NIPS19 L2M environment. As the simulator has some integral operations and thus is very inefficient. The `collect_metrics` step always takes the maximal time allowed. The throughput of sampling decreases from 550+ to 230+ (where the former is under `truncated_episode` setting). If there a workaround?
I think the concept of training iteration in RLLib is not that natural in Reinforcement semantics and reporting metrics at the end of each training iteration is not necessary. The most natural way is to report the latest *n* metrics once they have been collected. From the system viewpoint, there is no need to have a sync barrier at the end of a training iteration.
So...what are your opinions, my teammates?

### Source code / logs

https://github.com/ray-project/ray/blob/master/python/ray/rllib/evaluation/metrics.py#L63

**Comment by ericl** [comment]
One way of working around this is to only wait for up to a certain period of time. Then, the rest of the metrics can be fetched on the next iteration. Would that work?

**Comment by joneswong** [comment]
Yes, and as the current implementation intended, users can specify a smaller timeout limit for efficiency consideration. The problem is in the if branch I pasted where at least one metrics must be collected or an exception will be raised. I don't think this *if* check is necessary if we allow empty stats of a training iteration.

**Comment by joneswong** [comment]
@ericl  I mean it is more natural to change the *if-raise* into a warning. For users who know the procedure, they won't be curious about the Nan stats. My concern is that whether the timeout-metrics stay in the remote workers so that they could be collected at the end of next iteration. What's your opinion?

**Comment by ericl** [comment]
You can save the object ids that didn't complete in the trainer, to be fetched on the next iteration?
