### ISSUE TITLE
return type documentation for `build_tf_policy` is ambiguous

### ISSUE THREAD

**Issue by billyzs** [ray-project/ray#5200]
Not sure if it's just me, but I do find the documentation of `build_tf_policy` a bit confusing. The function seem to return a class that's a subclass of `DynamicTFPolicy` (and the mixins supplied in the arguments) that you then have to call `__init__` on to get an actual instance of; with how the docstring is written now,
https://github.com/ray-project/ray/blob/734211771057a4ccce5b7c70d874b2bd34b4f9aa/python/ray/rllib/policy/tf_policy_template.py#L101
it sounds like the function returns an instance of that class. It misled me on the wrong path for a little while.

Would it make sense to change the wording to something like "Return a subclass of the mixins and `DynamicTFPolicy`"?

**Comment by ericl** [comment]
Agreed, this is bad wording. Do you want to make a fix here?

**Comment by billyzs** [comment]
@ericl yeah I can do it, does my above wording (calling the return value "a subclass of DynamicTFPolicy and the mixins supplied in the arguments") sound OK?

2 other factory methods are worded similarly: 
https://github.com/ray-project/ray/blob/734211771057a4ccce5b7c70d874b2bd34b4f9aa/python/ray/rllib/agents/trainer_template.py#L75
https://github.com/ray-project/ray/blob/734211771057a4ccce5b7c70d874b2bd34b4f9aa/python/ray/rllib/policy/torch_policy_template.py#L56
shall I reword those too?

**Comment by ericl** [comment]
That sounds good.
