### ISSUE TITLE
[tune] Does Tune not load everything into memory at the start 

### ISSUE THREAD

**Issue by himat** [ray-project/ray#5203]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.8.0.dev2
- **Python version**: 3.6.5

### Describe the problem

I was running a Tune experiment, and then I switched my git branch, but this then started resulting in many errors because some variables were now changed. Does Tune not load everything it needs from the files into memory at the beginning? When I run a normal pytorch project for example, even if I switch git branches, it won't affect the already running code.

I would assume that this shouldn't be a problem for Tune to do either, or is there some reason why it needs to always re-read from the files?

**Comment by richardliaw** [comment]
Hi @himat, trials that are started later will not have the variables loaded in memory. This is because we start new processes every time a trial starts, so it's possible that if your trial depends on a repo and you change the repo code mid experiment, the experiment may error.

Hope that helps!

**Comment by richardliaw** [comment]
closing because stale.
