### ISSUE TITLE
[rllib] MARWIL action placeholders are inconsistent

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5205]
### Describe the problem

The algorithm only requires that the policy is a stochastic one. The action space can be either discrete or continuous. However, in our current implementation, the action placeholder for inference purpose is constructed according to the corresponding action space, while that for training purpose is hard-coded for discrete actions.

### Source code / logs

https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/marwil/marwil_policy.py#L93
https://github.com/ray-project/ray/blob/master/python/ray/rllib/agents/marwil/marwil_policy.py#L113

**Comment by ericl** [comment]
Is the fix just to call get_action_placeholder() in both settings?
