### ISSUE TITLE
[tune] Unexpected upload location

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#5206]
## System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: https://github.com/ray-project/ray/pull/5191/commits/16c27d0bffd54e21e7da5f4980aa4ac6d8a1689a
- **Python version**: 3.7
- **Exact command to reproduce**: n/a

### Describe the problem
I'm running Tune experiment with:
```
tune.run(
    ...,
    local_dir='~/ray_results/gym/Ant/v3',
    upload_dir='gs://ray/results/',
    ...)
```

Previously, I would see the results getting uploaded to `gs://ray/results/gym/Ant/v3/[experiment-id]/[trial-id]`, whereas nowadays they get uploaded to `gs://ray/results/[experiment-id]/[trial-id]`. Is this expected change? I think the new behavior probably makes more sense, but I got a bit confused by it at first and wanted to make sure that it's the expected behavior.

cc @richardliaw

**Comment by richardliaw** [comment]
Ah yeah, now `local_dir` is synced with `upload_dir`. Should have added an logging message...

**Comment by hartikainen** [comment]
Sounds good, I think this makes sense.
