### ISSUE TITLE
Cannot load-balance actors with resource requirements

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#5209]
### System information
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7
- **Python version**: 3.7.3

### Describe the problem
I am trying to load-balance some actors across multiple nodes. I set each actor's lifetime resource requirement to be 1 CPU, start some nodes locally with the `Cluster` util that have 1 CPU each, then start as many actors as nodes. Then, I cannot send tasks to all of the actors.

### Source code / logs
Code:
```python
import ray
from ray.tests.cluster_utils import Cluster

cluster = Cluster()
cluster.add_node(num_cpus=0)
num_nodes = 4
for i in range(num_nodes):
    node = cluster.add_node(num_cpus=1)
ray.init(redis_address=cluster.redis_address)
print(len(ray.state.state.client_table()), "clients")

@ray.remote(num_cpus=1)
class Actor(object):
    def __init__(self):
        pass
    def ping(self):
        import time
        time.sleep(1)

actors = [Actor.remote() for _ in range(num_nodes)]
ray.get([a.ping.remote() for a in actors])
```
This code times out. In the raylet logs with `DEBUG`, I see the actor creation task getting spilled back between 2 nodes.

**Comment by richardliaw** [comment]
Try out #5191

**Comment by stephanie-wang** [comment]
Thanks, it works now! Opened a PR to add a regression test for this issue.
