### ISSUE TITLE
Make RayOutOfMemoryError threshold configurable? 

### ISSUE THREAD

**Issue by MQQ** [ray-project/ray#5211]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: pip
- **Ray version**: 0.7.1
- **Python version**: 3.6.8
- **Exact command to reproduce**: N/A

### Describe the problem
Ray now reports that more than 95% of the memory is used and raises RayOutOfMemoryError. But the problem is that if I run this in a container, it will raise the error based on the memory usage of the host. In the following example, the host had ~400G memory, and there were still more than ~15G memory available on the host, which is more than enough for the job. But the job got killed due to the 95% threshold.    

It seems that this threshold config is not exposed. I wonder if this can be configurable and if this can also provide an option to set it as an absolute value, e.g. raise when less than x GB is available. 

### Error logs
```
File "/usr/local/lib/python3.6/site-packages/ray/memory_monitor.py", line 78, in raise_if_low_memory
   self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node xxxxxxxx is used (380.32 / 397.05 GB). The top 5 memory consumers are:

PID    MEM    COMMAND
1    7.57GB    python scripts/run.py
160    4.2GB    ray_worker
159    3.91GB    ray_worker
163    3.25GB    ray_worker:some.job.run
1225    2.17GB    ray_worker:some.job.run
```

**Comment by ericl** [comment]
Oops, this probably should be detecting based on the container limit, not the host. @edoakes do you know if there's a way to check that instead of the host memory size?

**Comment by ericl** [comment]
To answer the original question, you can set RAY_DEBUG_DISABLE_MEMORY_MONITOR to disable the check entirely: https://github.com/ray-project/ray/blob/master/python/ray/memory_monitor.py#L72

There's no way to configure it otherwise currently but a PR would be welcome.

**Comment by MQQ** [comment]
The container memory limit, if set, can be found in cgroup config usually under `/sys/fs/cgroup/memory/memory.limit_in_bytes`. 
But the container memory limit is not necessarily set. How a container job is configured and scheduled can be uncertain. That's why I feel an explicit config can be useful. 

@ericl Thanks for pointing out that env var! I will see what I can do to for a PR.

**Comment by ericl** [comment]
Ah I see, then potentially `/sys/fs/cgroup/memory/memory.usage_in_bytes / min(/sys/fs/cgroup/memory/memory.limit_in_bytes, avail_memory)` could be used as a more robust indicator.
