### ISSUE TITLE
Issue with CUDA and num_gpus

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#5214]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Ray installed from (source or binary)**: source  
- **Ray version**: https://github.com/ray-project/ray/commit/6e0641845da9854ad3ce8d28e480cd741d5d5816
- **Python version**: 3.7.3
- **Exact command to reproduce**:

Boot a cluster with one `p3.2xlarge` worker (ie. a GPU worker), and a CPU head node (`m5.4xlarge`), then run the following on the head node:

```
@ray.remote(num_cpus=5)   # num_cpus=5 guarantees the function gets scheduled on the worker
def do_torch_stuff():
    return torch.cuda.get_device_name(0)
ray.get(do_torch_stuff.remote())
```

### Describe the problem

We get an error message:

```
---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
<ipython-input-9-9cd97e1bae4b> in <module>
----> 1 ray.get(do_torch_stuff.remote())

~/conda/envs/venv/lib/python3.7/site-packages/ray/worker.py in get(object_ids)
   2196             if isinstance(value, RayError):
   2197                 last_task_error_raise_time = time.time()
-> 2198                 raise value
   2199 
   2200         # Run post processors.

RayTaskError: ray_worker:__main__.do_torch_stuff() (pid=3040, host=<WORKER IP>)
  File "<ipython-input-8-4b251c513668>", line 3, in do_torch_stuff
  File "/home/ubuntu/conda/envs/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 277, in get_device_name
    return get_device_properties(device).name
  File "/home/ubuntu/conda/envs/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 299, in get_device_properties
    init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/ubuntu/conda/envs/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 145, in init
    _lazy_init()
  File "/home/ubuntu/conda/envs/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp:51
```

...even though the error comes from the worker's IP (ie. the machine with the GPU). Note that the worker has CUDA / torch set up correctly in the sense that `torch.cuda.get_device_name(0)` returns the correct GPU  when run directly on the worker node, in the virtualenv etc.

If we add `num_gpus=1` into the remote decorator, then the function works as expected.  Furthermore, subsequent invocations of the function continue to work, even if `num_gpus` is removed.  If the worker node is restarted then it once again fails unless `num_gpus` is passed (ie. it seems as if running once with `num_gpus=1` permanently affects some aspect of the worker node/process).

So two questions:
- Is it expected that we should pass `num_gpus`  in order for a given worker function to "see" a GPU, or is it just an abstract resource as with `num_cpus`?
- Is the "sticky" behaviour of `num_gpus` a bug?  It seems surprising that the behavior of running with `remote(num_cpus=5)` should change depending on whether i've previously run with `remote(num_cpus=5, num_gpus=1)`

**Comment by richardliaw** [comment]
> Is it expected that we should pass num_gpus in order for a given worker function to "see" a GPU, or is it just an abstract resource as with num_cpus?

Yeah, you need to pass it in to expose it. I'll make sure this is clear in the documentation.

> Is the "sticky" behaviour of num_gpus a bug? It seems surprising that the behavior of running with remote(num_cpus=5) should change depending on whether i've previously run with remote(num_cpus=5, num_gpus=1)

Can you show mean what you mean here? One possible thing to try out is `ray._submit(num_gpus=1)`.

**Comment by edoakes** [comment]
Automatically closing stale issue. Please re-open if still relevant.
