### ISSUE TITLE
Hard to debug: This worker was asked to execute a function that it does not have registered. You may have to restart Ray.'

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#5218]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.8

### Describe the problem

I am getting the `This worker was asked to execute a function that it does not have registered. You may have to restart Ray.'` error. But it does not provide enough information to really debug this. Which function? Could there be at least some name or Python path provided?

Because it seems the message is originating in C code it is not really possible to put in some temporary prints to see what is happening.

**Comment by jovany-wang** [comment]
How about adding a function descriptor to the warning_message here? https://github.com/ray-project/ray/blob/master/python/ray/function_manager.py#L547

like this:
```python
warning_message = ("This worker was asked to execute a "
                                   "function that it does not have "
                                   "registered. You may have to restart "
                                   "Ray. function descriptor is {}".format(function_descriptor))
```

**Comment by mitar** [comment]
Oh, it is not C code. Let me try that.

**Comment by mitar** [comment]
OK, that helped. It looks like in my case importing is very delayed because the worked is initializing using a function from `run_function_on_all_workers`. So it the timeout occurs, but eventually initialization finishes, so all functions get imported and things are resolved.

**Comment by ehknight** [comment]
@mitar do you know if you could elaborate a bit? I'm seeing a similar problem, so anything you might've done to help it would be awesome to hear.

**Comment by mitar** [comment]
Not sure what you mean. Change the code as seen above and you will be able to see which function is problematic.

**Comment by ehknight** [comment]
@mitar, I mean, even if I know which function is causing the issue, how did you resolve it? Did you add a delay, and if so, at what point in your code (i.e. where on the driver script or function actually being executed)?

**Comment by mitar** [comment]
No, delay is the reason for this warning.

I have not done anything. I now know that it is a false warning I do not have to care about.

I think Ray should fix this so that this warning does not happen while Ray it initializing through `run_function_on_all_workers`.

**Comment by waldroje** [comment]
I've been able to create this error with a toy example, although it is sporadic, and maybe depends on cluster configuration... in generaI I have gotten this error when nesting calls to ray.remote functions, and thus I broke down an example along those lines to see if I could get the error using simple functions with no real overhead, and I do get the error, but just not always... curious if your able to replicate...

[<script src="https://gist.github.com/waldroje/c00eb05be9c162d000309deb48c099f0.js"></script>](url)

**Comment by waldroje** [comment]
The attached link shows a toy example which can create this error, although it does not seem to do it all the time... It seems to occur more often when I raise the number of tasks, or run it consecutively.  This example simplifies the case which I frequently encounter this, which is when using nested ray.remote calls.

https://gist.github.com/waldroje/c00eb05be9c162d000309deb48c099f0

**Comment by anttttti** [comment]
I'm getting this error when sending a large number of mixed tasks to Ray. With Ray 0.7.1 up to 500 processes seem to run well at once, but over that and a lot of tasks are lost due to this. Upgrading to Ray 1.0, the number of processes seems to be half or less of that. This seems to limit how scalable Ray is for complex tasks.
