### ISSUE TITLE
Pyarrow impacts gRPC's initialization

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#5219]
During developing #5120, we encountered a very weird issue.  This issue only happens on some macOS machines.

The direct issue we were seeing was 
```
E0715 10:15:43.952846000 140736026641216 tls_pthread.cc:26]            assertion failed: 0 == pthread_setspecific(tls->key, (void*)value)
Fatal Python error: Aborted
```
Log can be found [here](https://travis-ci.com/ant-tech-alliance/ray/jobs/216040073).

After some investigation, we found the reason was because gRPC wasn't correctly initialized in the Python process. 

The initialization is done by [GrpcLibraryInitializer](https://github.com/grpc/grpc/blob/4ed3738d4285d7d7ee61012a6991a1581e4d7bbd/include/grpcpp/impl/grpc_library.h#L39). There is a static `GrpcLibraryInitializer` [object](https://github.com/grpc/grpc/blob/62b8a783fa376d6bfe277d6e1877b31f89e16553/src/cpp/client/secure_credentials.cc#L42) in gRPC code.  This object should be initialized when Python loads the `_raylet` shared lib. And this [g_gli object](https://github.com/grpc/grpc/blob/4ed3738d4285d7d7ee61012a6991a1581e4d7bbd/include/grpcpp/impl/grpc_library.h#L43) should be created. **However, `new GrpcLibrary()` only allocates memory but doesn't execute `GrpcLibrary`'s constructor.**  (I verified this by adding a log in `GrpcLibrary`'s constructor.) And it results in gRPC incorrectly initialized.

After more investigation, we found the issue is related to pyarrow. In `ray/__init__.py`, if we import `_raylet` before `pyarrow` (which means loading `_raylet` shared lib before `pyarrow` shared lib), the issue is gone. 

@pcmoritz @robertnishihara are you aware of anything in `pyarrow` that could cause this weird bug?

**Comment by robertnishihara** [comment]
Could it be related to the fact that Arrow also uses gRPC in its "flight" library? https://github.com/apache/arrow/search?q=grpc&unscoped_q=grpc

@pcmoritz, do we build flight as part of our pyarrow wheels?

**Comment by raulchen** [comment]
thanks. Also, could this be related to `dlmalloc`, which might impact `new` operator?

**Comment by edoakes** [comment]
Automatically closing stale issue. Please re-open if still relevant.
