### ISSUE TITLE
Unclear how to suppress "Possible unhandled error from worker"

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#5240]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.8

### Describe the problem

When my task fails, I leave the exception to propagate out of the task itself. Then, I catch it when I do `ray.get` and handle the exception. But I still get a bit later a message `Possible unhandled error from worker`. How exactly one should handle the error to not get this message? I assumed that this message would be shown only if I have not done `ray.get` in a reasonable time.

**Comment by ericl** [comment]
You have to execute the ray.get within 5 seconds of the error occurrence, could it be that's not enough time?

**Comment by mitar** [comment]
Pretty sure I do that. I made an example there I raise a text exception inside a task, recording the timestamp:

* Timestamp of the exception: `Exception: Test 2019-07-21 19:27:19.490948`
* When the logging arrives to the driver, mentioning that task failed: `2019-07-21 19:27:19,49`
* When I get the result and log the error once more: `2019-07-21 19:27:19,494`
* When I get `Possible unhandled error from worker`: `2019-07-21 19:27:24,510`

**Comment by ericl** [comment]
Does this work for you without any of those messages printed?
```
import time
import ray

ray.init()

@ray.remote
def foo():
    raise Exception("oops")

i = 0
while True:
    i += 1
    time.sleep(1)
    print(i)
    try:
        ray.get(foo.remote())
    except:
        pass
```

**Comment by mitar** [comment]
The code you provided works and does not have those messages printed. But I modified it and the following code has those messages printed:

```
import threading
import time
import ray

ray.init()

@ray.remote
def foo():
    raise Exception("oops")

@ray.remote
def main():
    i = 0
    while True:
        i += 1
        time.sleep(1)
        print(i)
        try:
            ray.get(foo.remote())
        except:
            pass

ray.get(main.remote())
```

**Comment by ericl** [comment]
Ah, that makes sense then, the error is handled in a worker but not the
driver, so the driver still prints it out. How about adding an environment
variable to suppress the worker errors, unless you can think of a better
way? I'd be happy to review such a PR.

**Comment by mitar** [comment]
Wouldn't it be better if we distribute information that the error has been handled from the worker to the driver?

**Comment by ericl** [comment]
That could be pretty tricky, since you'd need to tell the driver the error has been handled (for some definition of handled).

**Comment by mitar** [comment]
We already have a definition of handled: `ray.get` was called on it. So, every `ray.get` on an exception it should also log centrally that the exception has been handled. If it is also logging centrally that there was an exception in the first place.

I am not really sure how useful is this feature anyway in almost all except the very basic setups. I mean, most setups have tasks which run other tasks which can fail, no?

**Comment by snownus** [comment]
Will this affect the final performance if such error occurs? @mitar and @ericl , thanks

**Comment by mitar** [comment]
This is just cosmetic.

**Comment by snownus** [comment]
Thanks. @mitar

**Comment by snownus** [comment]
@mitar thanks a lot for your reply. However, my log error is like this: 
`
ERROR worker.py:1612 -- Possible unhandled error from worker: ray_RayModel:restore_from_object() (pid=24887, host=4GPU)
UnreconstructableError: Object bf2495b140d49c2a06e85e15968cbeae01000000 is lost (either evicted or explicitly deleted) and cannot be reconstructed.
`
It seems try to load from a model.

Will it affect the final error? Sorry that I am new to Ray. I don't know many things...

**Comment by mitar** [comment]
I do not think this is related to this issue, so I suggest to or open a new issue or (it looks more like an user issue) write to the mailing list.

**Comment by mimoralea** [comment]
@snownus did you solve that `UnreconstructableError`? I'm having the same issue.

**Comment by mitar** [comment]
Unstale.

**Comment by mitar** [comment]
Unstale.

**Comment by rkooo567** [comment]
@mitar This should've been resolved in the latest master. Can you check again?

**Comment by mitar** [comment]
I am unable to try latest master because I am lacking a migration guide: https://github.com/ray-project/ray/issues/14399

**Comment by mitar** [comment]
I am unable to check because I am lacking migration guide: https://github.com/ray-project/ray/issues/14399
