### ISSUE TITLE
Restore functionality seems broken

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#5246]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  RHEL 7.6
- **Ray installed from (source or binary)**:  source
- **Ray version**:  0.8.0.dev2
- **Python version**:  3.6.8
- **Exact command to reproduce**:
Can be duplicated using the code supplied below

### Describe the problem

When restoring from a checkpoint, although screen output and progress.csv reflect training has resumed from checkpoint, all future checkpoint output seems to simply copy the restored data.

### Source code / logs

    ray.init(log_to_driver=False, local_mode=False, logging_level=logging.ERROR)
    config1={
        "env": "CartPole-v0",  
    } 
    _save_dir = Path("/tmp/ray_results")
    _save_dir.mkdir(parents=True, exist_ok=True)
    _name = "checkpoint_test"
    tune.run("DQN", name=_name, stop={"training_iteration": 2},
        config=config1, checkpoint_at_end=True, 
        local_dir= _save_dir.as_posix(), verbose=0)
    _restore = list(_save_dir.joinpath(_name).glob("*/checkpoint_2/checkpoint-2"))[0]
    data = pickle.load(open(_restore.as_posix(), 'rb'))
    print(data['optimizer'])
    print(pickle.loads(data['worker'])['state']['default_policy'][0].sum())
    tune.run("DQN", name=_name, stop={"training_iteration": 4},
        config=config1, checkpoint_at_end=True, 
        local_dir= _save_dir.as_posix(), restore=_restore.as_posix(), verbose=0)
    _restore = list(_save_dir.joinpath(_name).glob("*/checkpoint_4/checkpoint-4"))[0]
    data = pickle.load(open(_restore.as_posix(), 'rb'))
    print(data['optimizer'])
    print(pickle.loads(data['worker'])['state']['default_policy'][0].sum())

**Comment by ericl** [comment]
Thanks for reporting this, https://github.com/ray-project/ray/pull/5257 should fix it.

**Comment by waldroje** [comment]
Much appreciated, thx

**Comment by waldroje** [comment]
This is breaking on my install... there is no "trainer_state" key in my state variable...

**Comment by ericl** [comment]
That's an old checkpoint right? The new ones should have it?

Eric

**Comment by waldroje** [comment]
Yes, I figured that out of course right after I posted...
