### ISSUE TITLE
Request: prevent writing of params.pkl

### ISSUE THREAD

**Issue by saltypeanuts** [ray-project/ray#5255]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**: 0.7.2
- **Python version**: 3.5.3
- **Exact command to reproduce**: Run any ray training model

### Describe the problem
When passing through large arrays (gb+) to custom environments, the params.pkl file can be exceedingly large. When iterating through a number of models + parameters, this can eat up a lot of space on a disk without providing much useful information. There should be a user parameter to opt to not write the params.pkl to file when a model is run.

```
events.out.tfevents.1563902107.DESKTOP-53D6NM7
26 minutes ago1.09 kB
log_synclawpmn0a.log
28 minutes ago0 B
params.json
28 minutes ago25.9 kB
params.pkl
28 minutes ago964 MB
progress.csv
26 minutes ago28.3 kB
result.json
26 minutes ago28.8 kB
```

**Comment by richardliaw** [comment]
Oh, one option is to do `obj_id = ray.put(array)` on the driver and then `ray.get(obj_id)` in the environment, and just pass the obj_id around via the config. This should avoid serialization and also make Ray faster to start.

**Comment by saltypeanuts** [comment]
How is that constructed?

Right now I have it set up as
```
class my_env(gym.Env):
    def __init__(self, env_config):
        self.df = env_config['df']

...

    config = {"env_config: {"df": df}}
...

```

**Comment by saltypeanuts** [comment]
Ah got it:
```
if __name__ == "__main__":
    ray.init(ignore_reinit_error=True)
    test_df = ray.put(df))

...

class my_env(gym.Env):
    def __init__(self, env_config):
        self.df = ray.get(test_df)
```

**Comment by richardliaw** [comment]
Nice!
