### ISSUE TITLE
[rllib] Handling of MultiAgent info dictionary

### ISSUE THREAD

**Issue by Lorenzo-Giardi** [ray-project/ray#5256]
### System information
- **OS**: Linux Mint 19.1
- **Ray installed from**: binary
- **Ray version**: 0.8.0.dev2 
- **TF version**:  1.14.0
- **Python version**: 3.6.8

### Describe the problem
Hello. I think that there might be some bug in tune/rllib which causes an error during training whenever the environment returns an info dictionary that contains anything rather than empty curly brackets {}.

The error code says:
AttributeError: 'str' object has no attribute 'get' 
(or 'int' or 'float' depending on the content of the info dictionary)

The code is a simple Tune DQN training on a custom multi-agent environment, compliant with rllib API for multi-agent environments, and everything works fine if the info dictionary is empty.

### Source code / logs
This works fine.
```        
info = dict()
for i in self.agents:
      info.update({i:{}})
return self.obs, rew, dones, info
```
This returns an error.
```        
info = dict()
for i in self.agents:
      info.update({i:3.14})
return self.obs, rew, dones, info
```
[error_2019-07-23_22-02-00.txt](https://github.com/ray-project/ray/files/3423914/error_2019-07-23_22-02-00.txt)

**Comment by ericl** [comment]
Try {i: {"somevalue": 3.14}}.

**Comment by Lorenzo-Giardi** [comment]
Thank you Ericl, in that that way it works fine.
