### ISSUE TITLE
[tune] Logs after trial fail and restore are missing

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#5263]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source @ 3e0ad11
- **Ray version**:
- **Python version**: 3.7
- **Exact command to reproduce**: n/a

### Describe the problem
If a trial fails (e.g. due to node preemption/failure) and gets automatically restored by Tune, no logs are being appended even when the trial runs otherwise fine.

**Comment by hartikainen** [comment]
I tried replicating this in the cluster tests (see https://github.com/ray-project/ray/pull/5264/commits/f4eaa8e9f931bb1457c284c3fe5ac393a021b478#diff-c30156beb5a899cfbd6e4c07692ce544R205), but it does not seem to fail.

**Comment by richardliaw** [comment]
What happens at `logger.on_result` after failure?

**Comment by hartikainen** [comment]
The root cause for this is that we sync the whole trial folder from head to worker when doing the recovery. Thus the worker has an old `progress.csv` on it and later we keep constantly overriding the head's `progress.csv` by rsyncing things back from worker to the head.

**Comment by ujvl** [comment]
@hartikainen this is _probably_ fixed now; let us know if you continue to run into it.

**Comment by richardliaw** [comment]
Closing this for now, but I think the solution we want to step towards is having people log to EFS or S3.
