### ISSUE TITLE
[autoscaler] uptime command fails due to exit(1)

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#5265]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: source @ 60f59639c1356a1a9982d06cb95bdea87c5811bc
- **Ray version**:
- **Python version**: 3.7
- **Exact command to reproduce**: n/a

### Describe the problem
Autoscaler sporadically fails when calling uptime. This is caused by the change in https://github.com/ray-project/ray/pull/5238 where we tried to clean up the autoscaler error messages. The change works generally fine, but for the uptime command we actually do need to raise instead of exiting because the error is expected to be caught on a higher level.

**Comment by richardliaw** [comment]
Turns out if you raise `click.ClickException`, you don't show a huge stack trace but you also raise an exception.

**Comment by richardliaw** [comment]
Closing this issue for now as we've resolved this with #5266. Honestly, this isn't going to be sustainable unless we have a nice testing framework for this.
