### ISSUE TITLE
Cannot connect to remote node (or redis server)

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5275]
I'm running ray head node and no matter what I do I can't connect to it. I have an Ubuntu machine with the head node, and a mac machine as a worker node.

I've even tried to connect to just the redis server as suggested elsewhere:

```
$ redis-cli -p x.x.x.x:6379
Could not connect to Redis at 127.0.0.1:132: Connection refused
```

(where x.x.x.x is my head node IP).

The error message always says 127.0.0.1:132.

I've open all possible ports on my ubuntu head machine:
```
sudo ufw allow 6379
```
Any tips???

**Comment by drozzy** [comment]
In fact, it seems redis is started in a mode that only allows local connections.
If I run `netstat -nlpt | grep 6379` I get:
```
tcp  0  0  0.0.0.0:6379 0.0.0.0:* . LISTEN .  16044/redis-server
tcp6  0 0  :::6379  :::* .  LISTEN  16044/redis-server
```

**Comment by drozzy** [comment]
Oh ok, nevermind, this works:

```redis-cli -c [ip-address]```

**Comment by drozzy** [comment]
Now I keep getting:

```
E0726 Connection to IPC socket failed for pathname /tmp/ray/session_xxx/sockets/plasma_store, retrying xxx more times
```

**Comment by drozzy** [comment]
Are you sure this should be the "remote" ip and not localhost?
```
import ray
ray.init(redis_address="<redis-address>")
```

**Comment by drozzy** [comment]
Closing in favour of SO question: https://stackoverflow.com/questions/57224312/cannot-setup-manual-ray-cluster

**Comment by richardliaw** [comment]
When you run `ray.init` on the head node, what happens? Can you provide the logs?

**Comment by drozzy** [comment]
Ok, it started working all of a sudden...
