### ISSUE TITLE
[Tune] Allow files to be synced directly to cloud

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#5276]
Tune currently transfers experiment files from the worker nodes to the head node, mainly in order to allow users to access (e.g. visualize) the results in a centralized fashion through the head. In order to do this, Tune rsyncs *everything* in the trial folders on the workers back to the head node. Syncing everything is sometimes useful and feasible if you don't save a lot of extra data along with the training results. However, the trial folders often contain data, such as training videos, images, or replay pools, that take a lot of disk space and are not needed on the head node but should only be saved to the cloud.

I think we should consider allowing Tune file syncing to happen directly from workers to cloud. It might even be fine to sync all the files directly to cloud and only have the results go through the head node, but if not, maybe we could add some settings to configure which files should be transferred over to the head before syncing to cloud.

Any thoughts @richardliaw @ericl?

**Comment by richardliaw** [comment]
This is done in #6376.
