### ISSUE TITLE
[Tune] The logdir string of Trial is always truncated

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#5280]
For now, the logdir string of a trial is created by `Trial.create_logdir`: https://github.com/ray-project/ray/blob/6f737e6a500dc9f500d4cf7ba7b31f979922a18b/python/ray/tune/trial.py#L373-L389

The `identifier` is always be truncated to a length of `MAX_LEN_IDENTIFIER`. This should be configurable since the max length of file names could be 256 in some systems.
@richardliaw

**Comment by richardliaw** [comment]
Can you make a PR? Maybe just set it to an environment variable?

**Comment by llan-ml** [comment]
Yeah, I'll try.
