### ISSUE TITLE
[Tune] Too much overhead between `Trainable.train` calls

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#5283]
I wrote a simple script to count the amount of time between `train` calls in `ray==0.6.0` and `ray==0.7.0`.

Results of `0.6.0`:

![image](https://user-images.githubusercontent.com/22030149/61944887-4f00f800-afd1-11e9-8c7d-265777be7551.png)

Results of `0.7.0`

![image](https://user-images.githubusercontent.com/22030149/61945220-0bf35480-afd2-11e9-8e11-d3e73fbbf967.png)

I only tested with these two versions, and am not sure if the performance regression was introduced before `0.7.0`.

Here is the script to reproduce the above results, and the performance regression happens only when there are many trials to be run (e.g., `num_samples=1000`).
<pre>
# -*- coding: utf-8 -*-
# @Author  : Lin Lan (ryan.linlan@gmail.com)

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import time
import ray
from ray.tune import Trainable, run_experiments
from ray.tune.trial import Resources

class Foo(Trainable):
    @classmethod
    def default_resource_request(cls, config):
        return Resources(cpu=2.0, gpu=0.0)

    def _setup(self, config):
        self.total_between_time = 0.0

    def _train(self):
        self.start_time = time.time()
        if hasattr(self, "end_time"):
            time_between_call = self.start_time - self.end_time
        else:
            time_between_call = 0.0
        time.sleep(1.5)
        self.end_time = time.time()
        self.total_between_time += time_between_call
        result = {
            "time_between_call": time_between_call,
            "total_between_time": self.total_between_time
        }
        return result

ray.init()

run_experiments({
    f"{ray.__version__}": {
        "run": Foo,
        "stop": {"training_iteration": 1000},
        "num_samples": 1000
    }
})
</pre>
@richardliaw

**Comment by richardliaw** [comment]
This might be because experiment checkpointing. Can you also run on the
latest snapshot of master?

Thanks! This is really helpful.

**Comment by llan-ml** [comment]
The issue disappears on the master.
