### ISSUE TITLE
ray.get stuck if there is 'space' in environment path

### ISSUE THREAD

**Issue by ashraaghav** [ray-project/ray#5288]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.8
- **Exact command to reproduce**:  (given below)

### Describe the problem

I was running the test example (given below) given in the documentation to test my installation on a fresh virtual environment. But my code was stuck in `ray.get()` of a ray.remote method. 

On digging deeper, I noticed that having a "space" in the environment path was causing the issue. eg: `~/env folder/venv`

I created a new virtual environment and executing the same commands from a path with no space and it worked cleanly. eg: `~/env_folder/venv`

I am not sure if this is an expected behaviour but it was weird to see why the path should affect performance.

### Source code / logs

To create virtual envs
```
$ cd env\ folder/
$ virtualenv testenv --no-site-packages --python=python3
```
Source code tested:
```
import ray 
import time

@ray.remote
def f():
    time.sleep(1)
    return 1


ray.init()
results = ray.get([f.remote() for i in range(4)])
```

PS: I can also provide the logs from `raylet.err` if required. It was too long, so I am not including now.

**Comment by richardliaw** [comment]
cc @pcmoritz
