### ISSUE TITLE
What does `source activate ray` do?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5289]
In this script there is a `source activate ray` command:
https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml#L26

What does it do? I get an error during that.

**Comment by richardliaw** [comment]
Thanks for making this issue! The local cluster config needs to be updated.

@drozzy can you try out this YAML here? https://github.com/ray-project/ray/pull/5290

Let me know if you run into issues.

**Comment by drozzy** [comment]
Wait.. this uses docker...
This seems like extra level of complexity. Is there some sort of intro to this? (I mean I know docker - but I'm not sure wether I need to mount some directories or install specific images?)

**Comment by drozzy** [comment]
Maybe using kubernetes will be easier than writing your own cluster manager?

**Comment by drozzy** [comment]
Oh ok, found the docs on docker etc. here:
https://ray.readthedocs.io/en/latest/autoscaling.html#common-cluster-configurations

**Comment by richardliaw** [comment]
Docker is commented out, so it is not needed.

**Comment by drozzy** [comment]
I'm not really understanding how to run this (like what must be installed on each machine etc.)... for now I'm sticking to manual cluster setup without a script.

I'll come back to this later probably.
