### ISSUE TITLE
How to lunch webui in cluster?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5291]
I don't understand how to launch the webui in a cluster, as per instructions here:
https://ray.readthedocs.io/en/stable/webui.html#running-the-web-ui

When I run `ray start --head --redis-port=6379 --include-webui` what I get back is a url of this form: "x.x.x.x:8080/?token=xxxx" which shows just the "hostname", "uptime", "workers", "RAM", "Disk"... and basically doesn't look anything like this "http://localhost:8889/notebooks/ray_ui92131.ipynb?token=89354a314e5a81bf56e023ad18bda3a3d272ee216f342938" 

This is what I see:
![IMG_3011](https://user-images.githubusercontent.com/140710/61978958-9632bd00-afc0-11e9-8597-c27668e9bc1c.JPG)

Am I missing something?

**Comment by drozzy** [comment]
It is not clear whether I need to include the `include-webui` flag in the shell command or in the python command...

I guess I'm not really clear wether shell command does the same as the python command or not?

**Comment by robertnishihara** [comment]
It looks like you've gotten it running successfully. The web UI documentation is really out of date, thanks for pointing that out! (cc @richardliaw)

Note the UI is very minimal at the moment, but we will be making a lot of improvements to it.

**Comment by drozzy** [comment]
Oh ok.. But my workers are still at zero (0).
How do I know if my ray tasks are running on the cluster or not?
Is there some way to check?

Thanks.

**Comment by drozzy** [comment]
In fact, if I check for any PIDs inside of each of the nodes - nothing shows up. It's almost as if my:
![Screen Shot 2019-07-30 at 3 21 49 PM](https://user-images.githubusercontent.com/140710/62158708-15d0cc80-b2de-11e9-88f9-2a6eb322bdf2.png)

```
ray.init(redis_address='XXXXX:6379')
```
doesn't do anything - and just spawns a local training, no distributes it over the cluster.

**Comment by drozzy** [comment]
The number of workers never goes up above 0... :(

Posted SO question here:
https://stackoverflow.com/questions/57317529/ray-local-cluster-web-ui-shows-0-works
