### ISSUE TITLE
[tune] support nested results for CSVLogger

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#5294]
`Trainable._train` may return a nested dictionary, e.g., 

```
{
  "train": {"loss": 1.0, "acc": 0.6, "f1": 0.5},
  "test": {"acc": 0.6, "f1": 0.5}
}
```

Currently, `CSVLogger` regards nested dictionaries as strings and directly writes them into file. It would be convenient for follow-up analysis to parse the nested dictionaries like this function [to_tf_values](https://github.com/ray-project/ray/blob/a62c5f40f67785439a143c6151f8dc8599351e94/python/ray/tune/logger.py#L109-L123).

Then, the header will be something like `train/loss,train/acc,train/f1,test/acc,test/f1`.

**Comment by richardliaw** [comment]
Oh that's a good idea! Would you be interested in this patch? There's a `flatten_dict` function in `tune/utils.py`, and putting that in the CSVLogger would only be a 5 line change. If not, I could take it later.
