### ISSUE TITLE
What does this error indicate?

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#5298]
```2019-07-27 18:43:47,742	ERROR worker.py:1672 -- The task with ID 325f2d1b6061adb27bb34c5de18709c4 is a driver task and so the object created by ray.put could not be reconstructed.```

What is happening here? This seems to be happening somewhat random? Could it be related to the plasma store size? or redis size?

**Comment by richardliaw** [comment]
Maybe try increasing your plasma store size.
