### ISSUE TITLE
[rllib] custom env import error.

### ISSUE THREAD

**Issue by HanwGeek** [ray-project/ray#5311]
### System information
- **OS Platform and Distribution**: 8 * Linux Ubuntu 16.04 with 2GPU per machine
- **Ray installed from (source or binary)**: binary
- **Ray version**:0.7.2
- **Python version**:3.6.8
- **Exact command to reproduce**: See below

### Source code / logs

We use 8 machine to deploy a reinforcement learning project with RLlib. In this project, we custom our env with unity as a class `UnityEnv`. However, when we deploy our program on the cluster. The nodes cannot find the `UnityEnv` class file. The detailed information are as follows:
```python
ray.exceptions.RayTaskError: ray_RolloutWorker:sample() (pid=165332, host=host7)
  File "pyarrow/serialization.pxi", line 461, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 424, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 275, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 174, in pyarrow.lib.SerializationContext._deserialize_callback
ModuleNotFoundError: No module named 'UnityEnv'
```

**Comment by ericl** [comment]
This is probably because the UnityEnv libraries are not installed on the cluster workers. While the serialization of Ray can handle small dependencies such as local functions and classes, for larger libraries they have to be manually installed on workers.

**Comment by HanwGeek** [comment]
> This is probably because the UnityEnv libraries are not installed on the cluster workers. While the serialization of Ray can handle small dependencies such as local functions and classes, for larger libraries they have to be manually installed on workers.

The `UnityEnv` class is a single file class defined by myself as a local class. And I registry the custom env like this:
``` python
def env_creator(env_config):
  return UnityEnv(env_config)
register_env("unity_env", env_creator)
```
But it still not work.

**Comment by ericl** [comment]
Yep, in this case you will have to copy the file with UnityEnv to all the remote machines. If the class was _inline_ in that script it might work -- but in general you have to replicate all the dependencies to be sure.

One way of making sure this is the case is to use the autoscaler, which will setup all the machines the same way: https://ray.readthedocs.io/en/latest/autoscaling.html

**Comment by HanwGeek** [comment]
I fixed this problem but encountered another one.
Can ray deployed with [ml-agents](https://github.com/Unity-Technologies/ml-agents)?
```python
ray.exceptions.RayTaskError: ray_RolloutWorker:sample() (pid=45151, host=host1)
  File "/home/racer/anaconda3/envs/py36/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 253, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "/home/racer/anaconda3/envs/py36/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 788, in <lambda>
    register_env(name, lambda config: env_object(config))
  File "/home/racer/DeepCampEnv_ver1/UnityEnv.py", line 26, in __init__
    self.env = UnityEnvironment(file_name=env_config["env_directory"], worker_id=env_config["worker_id"], seed=1, no_graphics=env_config["no_graphics"])
  File "/home/racer/DeepCampEnv_ver1/ml-agents/ml-agents/mlagents/envs/environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/racer/DeepCampEnv_ver1/ml-agents/ml-agents/mlagents/envs/environment.py", line 527, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/racer/DeepCampEnv_ver1/ml-agents/ml-agents/mlagents/envs/rpc_communicator.py", line 61, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Scene
         The environment and the Python interface have compatible versions.
```

**Comment by HanwGeek** [comment]
I fixed this problem. Thanks a lot!

**Comment by jasonfiacco** [comment]
Hello, How did you end up fixing this?

**Comment by mpgussert** [comment]
https://xkcd.com/979

@HanwGeek what did you see!?!
