### ISSUE TITLE
When will you achieve high availability

### ISSUE THREAD

**Issue by WangYiPengPeter** [ray-project/ray#5314]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

when redis server is broken down, the cluster is inavailabe anymore. I can't find way to solve this problem by set some HA property such like zookeeper . Will you implement it in the near future?

**Comment by jovany-wang** [comment]
We're starting working on the high available of GCS these days.

**Comment by WtyFile** [comment]
you are outstanding.        please hurry,        we are waiting for your to do it.      thanks.

**Comment by wangli1426** [comment]
@jovany-wang May I ask if there is any recent update about this HA feature?

**Comment by xhudik** [comment]
i thinks, the answer for Ray's HA is under development planned/described here: https://github.com/ray-project/ray/milestone/8. Maybe Ray developers might update the milestone here ...
