### ISSUE TITLE
[tune] Can't access nested keys in PBT

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#5315]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem

I was looking to access the "evaluation" key values in training results for PTB, as I have an out of sample data set being used which helps optimize out of sample performance rather than in sample... but it seems the PopulationBasedTraining class "reward_attr" is limited to top level keys, and "evaluation" results are nested... 
it might be fairly trivial to just check if self._metric (reward_attr) is a 'str' or a 'list', and if it's a list, do something like 

```
    def on_trial_result(self, trial_runner, trial, result):
        time = result[self._time_attr]
        state = self._trial_state[trial]

        if time - state.last_perturbation_time < self._perturbation_interval:
            return TrialScheduler.CONTINUE  # avoid checkpoint overhead

        def extract(_metric, result):
            from functools import reduce
            from operator import getitem
            return reduce(getitem, _metric, result)

        if isinstance(self._metric, str):
            score = self._metric_op * result[self._metric]
        elif isinstance(self._metric, list):
            score = self._metric_op * extract(self._metric, result)
.........
```

Will just return KeyError if incorrect, which would be the same behavior currently if metric supplied is not available. Plenty of ways to implement, but figured I'd log the request...

**Comment by richardliaw** [comment]
There's a `flatten_dict` operator in `tune/util.py`. Maybe we can use that by default?

**Comment by waldroje** [comment]
yes!, i figured you'd have a better solution... that looks perfect...

**Comment by richardliaw** [comment]
Closing this in favor of #5340
