### ISSUE TITLE
Ray dashboard main.js absolute paths break relocation

### ISSUE THREAD

**Issue by andraxin** [ray-project/ray#5319]
### System information
Irrelevant.

### Problem
Employing URL rewriting rules to relocate the Ray dashboard to a different path results in breakage due to absolute paths in `main.js`.

### Solution
`sed -i s@/api/@api/@ ray/python/ray/dashboard/res/main.js`

**Comment by pcmoritz** [comment]
@mitchellstern Should we do anything about this?

**Comment by mitchellstern** [comment]
`python/ray/dashboard/res/main.js` was removed in https://github.com/ray-project/ray/pull/7028. If this is still an issue with the new dashboard, please open a new issue and let us know, thanks.
