### ISSUE TITLE
How to verify my training is running on a cluster and not just locally?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5321]
How can I verify that my training is running on a cluster and not just locally?

I've setup a cluster and it seems to see all the workers:
![Screen Shot 2019-07-30 at 3 21 49 PM](https://user-images.githubusercontent.com/140710/62158708-15d0cc80-b2de-11e9-88f9-2a6eb322bdf2.png)

But as you can see, there are no PIDs inside of each of the nodes - nothing shows up (this is after I run a PPO Atari training job on one of the nodes).

I init ray with the address of the master node like this:
```
ray.init(redis_address='XXXXX:6379')
```
But it seems like it  doesn't do anything - and just spawns a local training, not distributes it over the cluster.

Is there a way to test this?

**Comment by ericl** [comment]
Did you configure your job to use the appropriate number of workers? For example, if you configure "num_workers": 130 then there is no way it is running on one machine.

It should be reported in the training output `Resources requested: 3/8 CPUs, 0/0 GPUs` for example. So you can see the number of CPUs used / total.

**Comment by robertnishihara** [comment]
You could look at the Ray timeline (run `ray timeline` from the command line and then open the resulting JSON file in chrome://tracing).

You could also have each task manually check `ray.services.get_node_ip_address()` and print that or return it.

**Comment by drozzy** [comment]
> 130

I asked for 120 workers and it did cause increase in memory on other nodes.

However, there is so much output that I'm not sure where the "resource requested" line is (I get sooo many duplicate warnings about some TF stuff... :( )

**Comment by drozzy** [comment]
> ray timeline

I see a lot of workers in the trace... but how do I know they are distributed across machines and not just from a single machine?

**Comment by drozzy** [comment]
![Screen Shot 2019-07-30 at 4 21 31 PM](https://user-images.githubusercontent.com/140710/62162365-1ff6c900-b2e6-11e9-99a0-25f2995c1d0e.png)

**Comment by drozzy** [comment]
Also getting this:
```
2019-07-30 16:17:47.135841: W tensorflow/core/framework/allocator.cc:107] Allocation of 2702278656 exceeds 10% of system memory.
```

**Comment by richardliaw** [comment]
What's being printed? Are you seeing `(pid=XXX, ip=XX.XX.XX.XX)` as a prefix? If not, I think this may be an issue

**Comment by drozzy** [comment]
Ok, I see that two different IPs are being printed:
```
(pid=32403, ip=XX.118) Prefer Variable.assign which has equivalent behavior in 2.X.                                     
(pid=34104, ip=XX.119) W0801 13:19:27.401390
```

I'm guessing this means nodes are participating!

Thanks!

**Comment by drozzy** [comment]
I still can't really be sure it is running on a local cluster.

If I do "cluster" (`ray.init(redis_address=''`) vs. local (`ray.init()`) training - I get very similar performance.

**Comment by drozzy** [comment]
Another thing, is this type of python file sufficient to launch my training on a cluster? (Given that my nodes are connect to redis of the head node) or do I need to incorporate `@remote` decorator somehow?

```
import ray
import ray.rllib.agents.ppo as ppo
import logging

def main():

        ENV_NAME = 'BreakoutNoFrameskip-v4'
        ray.init(redis_address='132.246.113.173:6379')
        #ray.init()
        config = ppo.DEFAULT_CONFIG.copy()
        config["num_gpus"] = 1
        config["num_workers"] = 96
        # Atari observation shape is (250, 160, 3)
        config["model"]= {"dim" : 84, "conv_filters": [[32, [8, 8], 4], [32, [4, 4], 4], [64, [3, 3], 4]]}

        trainer = ppo.PPOTrainer(config=config, env=ENV_NAME)

        # Can optionally call trainer.restore(path) to load a checkpoint.
        for i in range(1000):
           # Perform one iteration of training the policy with PPO
           result = trainer.train()

           if i % 100 == 0:
               checkpoint = trainer.save()
               print("checkpoint saved at", checkpoint)

if __name__ == '__main__':
        main()
```

**Comment by drozzy** [comment]
Another thing, when I run it via tune on a cluster like so:
```
import ray
from ray import tune

ray.init(redis_address='XX.XX:6379')
tune.run(
    "PPO",
    stop={"episode_reward_mean": 200},
    config={
        "env": "CartPole-v0",
        "num_gpus": 0,
        "num_workers": 1,
        "lr": tune.grid_search([0.01, 0.001, 0.0001]),
    },
)
```

I only get messages that all my work is scheduled only on one node at a time:

```
               
RUNNING trials:    
 - PPO_CartPole-v0_0_lr=0.01:   RUNNING, [95 CPUs, 0 GPUs], [thoth-02  pid=36999], 105 s, 5 iter, 94000 ts, 192 rew
```

Even though my cluster consists of two nodes `thoth-01` and `thoth-2` each of 48 CPU cores (plus a head node - but I set its cpu count to 0/40).

```
expected (actual=18800, train_batch_size=4000). This may be because you have many workers or long episodes in 'complete_episoes' batch mode.
```

**Comment by drozzy** [comment]
Perhaps PPO does not scale to multiple machine CPUs?

**Comment by drozzy** [comment]
Web-UI now displays another info with 0.8:
```
ray config
{
  "min_workers": 0,
  "max_workers": 0,
  "initial_workers": 0,
  "autoscaling_mode": "default",
  "idle_timeout_minutes": 5,
  "head_type": "unknown",
  "worker_type": "unknown"
}
```

Is it normal for it to be set to zero?

![Screen Shot 2019-08-02 at 12 53 45 PM](https://user-images.githubusercontent.com/140710/62386042-a698e980-b524-11e9-8258-e248a02e3fce.png)

**Comment by drozzy** [comment]
Closing until I need it again.
