### ISSUE TITLE
[tune] MedianStoppingRule dependent only on complete trials

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#5335]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem

I'm looking to implement some of the different schedulers.. and the MedianStoppingRule by the docs seems like it should implement an early stopping rule... but when running it, the median_result seems to be dependent on values from a list of trials which only get added "on_trial_complete"... which doesn't really make sense to me, as shouldn't the median be updating all along with iteration results?

**Comment by waldroje** [comment]
Forget it... i I understand what it's doing... I actually think the version I'm thinking of might be useful as well, more like PBT updating in parallel and dropping trials that are below a median value... in this case I guess it's more of a sequential process of running trials, rather than in parallel.

**Comment by richardliaw** [comment]
I think this is actually supposed to be addressed in https://github.com/ray-project/ray/pull/4119 but we never merged it because we haven't gotten around to fixing the tests.

You're welcome to try that one out though!

**Comment by waldroje** [comment]
That's excellent Richard, thank you... I created a new class and incorporated those changes.  I also added to it the PBT style pausing/selecting of trials to allow all trials to stay in step, and the combination of those two gives me exactly what I'm looking for... I also added an extra argument to control the evaluation interval, similar to "perturbation_interval" as well as adding an optional parameter to take from the end of the list of results, thus the median calculated can be from a list of means constructed of tail_length... rather than the entire training history to reflect more recent performance.

A question I have is, when running PBT or MedianStopping using APEX DQN... when a trial is PAUSED... what happens to the replay buffer?  I'm trying to understand what the limitations might be regarding running multiple trials in a distributed fashion, which I have a decent idea when just outright training, but not sure if one is to PAUSE & CONTINUE along the way with this type of scheduling.

here is what my current version looks like... it seems to be doing what I expected...

class MedianTrialState(object):

    def __init__(self, trial):
        self.orig_tag = trial.experiment_tag
        self.last_eval_time = 0

    def __repr__(self):
        return str((self.last_eval_time,))

class MedianStoppingResult(FIFOScheduler):

    def __init__(self,
                 time_attr="time_total_s",
                 reward_attr=None,
                 metric="episode_reward_mean",
                 mode="max",
                 grace_period=60.0,
                 eval_interval=600.0,
                 min_samples_required=3,
                 hard_stop=True,
                 verbose=True,
                 tail_length= None):
        assert mode in ["min", "max"], "`mode` must be 'min' or 'max'!"

        if reward_attr is not None:
            mode = "max"
            metric = reward_attr
            logger.warning(
                "`reward_attr` is deprecated and will be removed in a future "
                "version of Tune. "
                "Setting `metric={}` and `mode=max`.".format(reward_attr))

        FIFOScheduler.__init__(self)
        self._stopped_trials = set()
        self._completed_trials = set()
        self._grace_period = grace_period
        self._eval_interval = eval_interval
        self._min_samples_required = min_samples_required
        self._metric = metric
        if mode == "max":
            self._metric_op = 1.
        elif mode == "min":
            self._metric_op = -1.
        self._time_attr = time_attr
        self._hard_stop = hard_stop
        self._verbose = verbose
        self._tail_length = tail_length

        self._trial_state = {}
        self._results = collections.defaultdict(list)

    @property
    def _trials_beyond_grace_period(self):
        trials = [
            trial for trial in self._results if (trial.last_result.get(
                self._time_attr, -float('inf')) > self._grace_period)
        ]
        return trials

    def on_trial_add(self, trial_runner, trial):
        self._trial_state[trial] = MedianTrialState(trial)

    def on_trial_result(self, trial_runner, trial, result):
        """Callback for early stopping.

        This stopping rule stops a running trial if the trial's best objective
        value by step `t` is strictly worse than the median of the running
        averages of all completed trials' objectives reported up to step `t`.
        """

        if trial in self._stopped_trials:
            assert not self._hard_stop
            return TrialScheduler.CONTINUE  # fall back to FIFO

        state = self._trial_state[trial]
        time = result[self._time_attr]
        self._results[trial].append(result)
        
        if time - state.last_eval_time < self._eval_interval:
            return TrialScheduler.CONTINUE  # avoid overhead

        state.last_eval_time = time
        median_result = self._get_median_result(time)
        best_result = self._best_result(trial)
        if self._verbose:
            logger.info("Trial {} best res={} vs median res={} at t={}".format(
                trial, best_result, median_result, time))
        
        if best_result < median_result and time > self._grace_period:
            if self._verbose:
                logger.info("MedianStoppingResult: "
                            "early stopping {}".format(trial))
            self._stopped_trials.add(trial)
            if self._hard_stop:
                return TrialScheduler.STOP
            else:
                return TrialScheduler.PAUSE
        else:
            for _trial in trial_runner.get_trials():
                if _trial.status in [Trial.PENDING, Trial.PAUSED]:
                    return TrialScheduler.PAUSE  # yield time to other trials

            return TrialScheduler.CONTINUE



    def on_trial_complete(self, trial_runner, trial, result):
        self._results[trial].append(result)
        self._completed_trials.add(trial)

    def on_trial_remove(self, trial_runner, trial):
        """Marks trial as completed if it is paused and has previously ran."""
        if trial.status is Trial.PAUSED and trial in self._results:
            self._completed_trials.add(trial)

    def debug_string(self):
        return "Using MedianStoppingResult: num_stopped={}.".format(
            len(self._stopped_trials))

    def _get_median_result(self, time):
        scores = []
        for trial in self._trials_beyond_grace_period:
            scores.append(self._running_result(trial, time))
        if len(scores) >= self._min_samples_required:
            return np.median(scores)
        else:
            return float("-inf")

    def _running_result(self, trial, t_max=float("inf")):
        results = self._results[trial]
        if self._tail_length is not None:
            results = results[-self._tail_length:]
        return self._metric_op * np.mean(
            [flatten_dict(r)[self._metric] for r in results \
                if flatten_dict(r)[self._time_attr] <= t_max])


    def _best_result(self, trial):
        results = self._results[trial]
        if self._tail_length is not None:
            results = results[-self._tail_length:]        
        return max([self._metric_op * flatten_dict(r)[self._metric] for r in results])

    def choose_trial_to_run(self, trial_runner):

        candidates = []
        for trial in trial_runner.get_trials():
            if trial.status in [Trial.PENDING, Trial.PAUSED] and \
                    trial_runner.has_resources(trial.resources):
                candidates.append(trial)
        candidates.sort(
            key=lambda trial: self._trial_state[trial].last_eval_time)
        return candidates[0] if candidates else None

**Comment by richardliaw** [comment]
I think the entire replay buffer gets serialized.

**Comment by richardliaw** [comment]
BTW, this change looks really neat - would you be interested in creating a
PR with these changes?

**Comment by waldroje** [comment]
I’m happy to give it a shot... I should have some time later today, early tomorrow...

**Comment by richardliaw** [comment]
@waldroje did you end up getting around to this?

**Comment by waldroje** [comment]
Not yet, been tied up, haven’t ever done a PR, so was looking into linting and tests... I have a few days that I’m free this week, was hoping to get to it.
