### ISSUE TITLE
[minor] Tune results should be flattened

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5340]
### Describe the problem
Tune results should be flattened before passing into trial schedulers, search algs, and stopping criteria. They should not be flattened in `last_result` and prints..?

**Comment by bfortuner** [comment]
Agree on the latter, I find the flattening inconvenient when I want to resume an experiment from a dictionary or plot columns. I assume this is a pandas thing.

**Comment by richardliaw** [comment]
What do you mean when you say “resuming an experiment from a dictionary”?
