### ISSUE TITLE
Remove worker-to-raylet heartbeats over grpc

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#5343]
### System information
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.2

### Describe the problem
Worker-to-raylet heartbeats add additional messages onto the raylet event loop but are not necessary to detect worker liveness. Instead, we can just detect a socket failure for the connection between the worker and the raylet.

**Comment by stephanie-wang** [comment]
cc @pcmoritz @raulchen @zhijunfu @jiangzihao2009, what do you guys think?

**Comment by zhijunfu** [comment]
Yes I agree that it's more desirable if we can detect it via socket failure. The problem is currently we don't find a way to retrieve this information from grpc, so we ended up using heartbeats for the failure detection. If there is a better approach of doing this, it definitely can be replaced.

**Comment by raulchen** [comment]
Another issue is that gRPC internally manages a connection pool. So we can not detect failure from one single connection.
Instead of using heartbeats, or detecting connection failure, another (quicker and more reliable) way may be just to monitor the worker processes.
