### ISSUE TITLE
Logging before flag parsing goes to stderr

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5344]
I get so many warnings of this type.... they just clutter the screen.

Is there something I can do to disable them?

![Screen Shot 2019-08-01 at 2 50 07 PM](https://user-images.githubusercontent.com/140710/62319449-fa93c780-b46b-11e9-82fb-aa298f9eed64.png)

**Comment by simon-mo** [comment]
Sadly this is tensorflow's logging issue. My experience with this is that they are hard to turn off. The best way is to try the following code and run it on all nodes and all workers:

```python
@ray.remote
def disable_tf_logging_in_each_worker():
    import os
    os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
	
    import tensorflow as tf
    if type(tf.contrib) != type(tf):
        tf.contrib._warning = None
    tf.logging.set_verbosity(tf.logging.ERROR)
	
    import logging
    logging.getLogger("tensorflow").setLevel(logging.ERROR)

ray.get([disable_tf_in_each_worker.remote() for _ in range(NUM_CORES)])
```

**Comment by drozzy** [comment]
Closing as I don't need it anymore.
