### ISSUE TITLE
How to compare performance?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5345]
What is a good metric to use to compare performance in terms of number of timesteps/second of two runs (e.g. with different number of workers)?

1. Can I use `tune/timesteps_this_iter`? 
2. Or do I also need to take into account `tune/time_this_iter_s`? 
3. In which case should I maybe use `timesteps_this_iter / time_this_iter_s` ?

**Comment by richardliaw** [comment]
cc @ericl

**Comment by drozzy** [comment]
Hm... above always gives me similar measurements.

I guess another way is to look at `tune/info/num_steps_trained` and look at the relative time it took to get, say 10k, steps.

**Comment by drozzy** [comment]
What I usually end up doing is switching the tensorboard to the "Relative" mode and compare "step" value at the same point on any graph.
