### ISSUE TITLE
ray tune callback

### ISSUE THREAD

**Issue by pinakigupta** [ray-project/ray#5355]
I am trying to do curriculam learning using ray tune as exemplified in the docs, for my custom env. While **I can use ray tune with my env with no issues,** when I try to give a very simple callback function I get errors. 
 
Here is my callback func and tune config, 
def on_episode_start(info):
    print(info.keys())  # -> "env", 'episode"

    ray.tune.run(
        "PPO",
        name="pygame-ray",
        stop={"training_iteration": int(num_timesteps)},
        # scheduler=pbt,
        checkpoint_freq=int(num_timesteps)//10,
        checkpoint_at_end=True,
        local_dir=local_dir_path,
        # upload_dir=upload_dir_path,
        verbose=True,
        queue_trials=False,
        resume=True,
        **{
            "num_samples": 1,
            "config": {
                "num_gpus_per_worker": 0,
                "num_cpus_per_worker": 1,
                # "gpus": 0,
                "gamma": 0.85,
                "num_workers": delegated_cpus,
                "env": train_env_id,
                "callbacks": {
                                "on_episode_start": ray.tune.function(on_episode_start),
                             },
            },
        }
    )

Following is the error trace. Although I think it is not giving any meaningful info.

....
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
 Batch iteration  1
(rank , size) =  (0, 1)
save_in_sub_folder is  /workspaces/rl_baselines_ad/ray_results/20190802-143654
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/0 GPUs
Memory usage on this node: 11.3/33.5 GB

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 11/12 CPUs, 0/0 GPUs
Memory usage on this node: 11.3/33.5 GB
Result logdir: /workspaces/rl_baselines_ad/ray_results/20190802-143654/pygame-ray
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - PPO_two-way-v0_0:    RUNNING

(pid=13821) WARNING: Logging before flag parsing goes to stderr.
(pid=13821) W0802 14:36:58.418845 140349177390912 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/compat/v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=13821) Instructions for updating:
(pid=13821) non-resource variables are not supported in the long term
(pid=13821) pygame 1.9.4
(pid=13821) Hello from the pygame community. https://www.pygame.org/contribute.html
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0802 14:36:59.482606 13930 raylet_client.cc:341] IOError: [RayletClient] Connection closed unexpectedly. [RayletClient] Failed to push profile events.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 492, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 550, in _connect
    raise err
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 10.184.11.59:44446. Connection refused.

Original exception was:
Traceback (most recent call last):
  File "baselines_run.py", line 78, in <module>
    ray_train(save_in_sub_folder=save_in_sub_folder)
  File "/workspaces/rl_baselines_ad/raylibs.py", line 254, in ray_train
    "on_episode_start": ray.tune.function(on_episode_start),
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 255, in run
    runner.step()
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 266, in step
    self._process_events()  # blocking
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 430, in _process_events
    trial = self.trial_executor.get_next_available_trial()  # blocking
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 299, in get_next_available_trial
    [result_id], _ = ray.wait(shuffled_results)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 2322, in wait
    worker.current_task_id,
  File "python/ray/_raylet.pyx", line 269, in ray._raylet.RayletClient.wait
  File "python/ray/_raylet.pyx", line 60, in ray._raylet.check_status
Exception: [RayletClient] Raylet connection closed.

**Comment by richardliaw** [comment]
Does this happen repeatedly?

**Comment by pinakigupta** [comment]
yes all the time. 
If I just comment the callback in the config it works though.

**Comment by richardliaw** [comment]
Which version of ray are you using? Can you try a latest snapshot of Ray? https://ray.readthedocs.io/en/latest/installation.html#trying-snapshots-from-master

**Comment by pinakigupta** [comment]
Actually I am installing ray inside my docker container using "pip install -U ray". Since I doing the docker build regularly I suspect I have a recent version of ray. 
Anyway pip freeze | grep ray  gives me ray==0.7.2
