### ISSUE TITLE
[autoscaler] supporting multiple compute instances in cluster

### ISSUE THREAD

**Issue by pinakigupta** [ray-project/ray#5357]
So I can successfully launch a cluster (aws) with Ray. 
However I can do so by specifying one type of compute instance types for all workers. like below,

worker_nodes:
    InstanceType: c5.18xlarge
    ImageId: ami-024c28da9b15ecda5 #024c28da9b15ecda5 

Is it possible to support multiple instance types, so that the auto scaler can optimize based off the compute load ? AWS batch for example supports multiple instance types,

So I wanted something like below.
worker_nodes:
    InstanceType: **c5.18xlarge, c4 (family), p2.xlarge**
    ImageId: ami-024c28da9b15ecda5 #024c28da9b15ecda5

**Comment by richardliaw** [comment]
Do you mean something like https://aws.amazon.com/blogs/aws/ec2-fleet-manage-thousands-of-on-demand-and-spot-instances-with-one-request/? 

I'd be really interested in hearing your use case. I think there's no current planned support for this, but you could probably defer this to EC2 fleets for the time being. 

Let me know what you think!

**Comment by pinakigupta** [comment]
That is what I mean exactly. cloud price is the main reason. The base nodes in my cluster are c5.18x (aws), but as the autoscaler decides to ask for more incremental resource I don't want them to immediately as for another c5.18x, if something smaller can do the job.

**Comment by lenassero** [comment]
Hi all ! I think this would be a great feature. Using a fleet allows to have way less spot instances interruptions on AWS. And grouping the worker nodes in a fleet request totally makes sense.

An example using only one instance type (`m5.16xlarge`) in a fleet:

![image](https://user-images.githubusercontent.com/21358816/86377799-18c00400-bc89-11ea-9aaa-4a2add1ce34e.png)

vs a fleet with similar instance types:

![image](https://user-images.githubusercontent.com/21358816/86378221-b4517480-bc89-11ea-80ae-1efb3101558e.png)

![image](https://user-images.githubusercontent.com/21358816/86378184-a8fe4900-bc89-11ea-8e3b-e291df2cf348.png)

Is this planned? 
@richardliaw what do you mean by "defer this to EC2 fleets for the time being"?

Thank you!

**Comment by rkooo567** [comment]
cc @wuisawesome I will assign it to you!

**Comment by rkooo567** [comment]
@wuisawesome Isn't it supposed to be supported now?

**Comment by wuisawesome** [comment]
Yes this is now supported. See https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-multi-node-type.yaml

**Comment by lenassero** [comment]
Hi, thanks a lot for this feature!
Is this available on a given wheel ?

**Comment by wuisawesome** [comment]
It's in the latest nightlies for now and should make it into the next release.


https://docs.ray.io/en/latest/installation.html#latest-snapshots-nightlies
