### ISSUE TITLE
[autoscaler] cluster job submission usability

### ISSUE THREAD

**Issue by pinakigupta** [ray-project/ray#5358]
Like I said in another thread Ray cluster (aws) is working fine for me. But I felt like there were few manual process involved. So I tried to write a simple shell script to automate the process. 

Steps where I am facing issues are commented in bold below. 
If there are any simpler solutions I would like to know about them.

------------------------------------------------------------------------------------------------------------------------------
```
#!/bin/sh

# use yaml config file as specified in the argument or else use the default yaml file
if [ $# \> 0 ]
  then
    ray_yaml_file=$1
  else
    ray_yaml_file="Ray-Cluster.yaml"
fi

# log terminal display in this text file
outputfile="output_cluster.txt"

ray up -y $ray_yaml_file # Start cluster using config file. The nodes run docker containers on a custom AMI in aws

sleep 500 # **Ideally I want to have some feedback that my cluster is up and fully ready (min/init nodes are all up and initialized)
#For now I am using this simple timeout.
#Also tried some python API to check in my code (next step) to not start the job until the number of ray.nodes() match my init/min node
# config (by reading the yaml file in python). However the ray.node() API doesn't give enough info about the state of the node (init vs running)**

ray exec --docker $ray_yaml_file "docker attach $(docker ps -aqf "name=ray_docker");cd rl_baselines_ad;./run_baseline.sh" 2>&1 | tee  $outputfile # **This 
# is a step which works if I do this manually by sshing to the head node and typing the command. 
# However if I try to run this through this shell script it is always killing other workers, and only running the head node.
# Script looks at Ray python API to see how much cluster resource is available and spins out workers accordingly.**

bash ray_sync.sh $ray_yaml_file # Custom script to download ray_results directory from head node to local machine. Working well. If details on this is
# needed I can provide them.

ray down -y $ray_yaml_file # Tear-down the cluster
```

**Comment by richardliaw** [comment]
Hi @pinakigupta,

Sorry for the late reply. Here are some thoughts:

```
# use yaml config file as specified in the argument or else use the default yaml file
if [ $# \> 0 ]
  then
    ray_yaml_file=$1
  else
    ray_yaml_file="Ray-Cluster.yaml"
fi
```
This looks useful. cc @ericl @hartikainen.

> sleep 500 

Does `ray get_worker_node_ips` work for you?

>ray exec --docker $ray_yaml_file "docker attach $(docker ps -aqf "name=ray_docker");cd rl_baselines_ad;./run_baseline.sh

Why do you need to docker attach when you are already running `exec --docker`?

> bash ray_sync.sh $ray_yaml_file
Does this use `ray rsync-down`?

**Comment by hartikainen** [comment]
```
# use yaml config file as specified in the argument or else use the default yaml file
if [ $# \> 0 ]
  then
    ray_yaml_file=$1
  else
    ray_yaml_file="Ray-Cluster.yaml"
fi
```
> This looks useful. cc @ericl @hartikainen.

Agreed. I do a similar thing in softlearning: https://github.com/rail-berkeley/softlearning/blob/master/examples/instrument.py#L352

**Comment by pinakigupta** [comment]
Thanks for the tips I got it somewhat working. But more needs to be done to standardize to a broader use case. 
@richardliaw I remember why I was using docker attach. I think using it along with the --docker prompt was a silly mistake. the automatic cluster up and down script (like this one) should work irrespective of docker usage. So I was trying to use a general ray exec (without --docker). But I think I gave up at some point.
Also I got around using the dumb sleep 500 by using the following method in my script. However as I mention in my launcher shell script I would not want to do this check in python, as then the user needs to add this to the user code.

Finally bash ray_sync.sh $ray_yaml_file does use "ray rsync-down". But it also looks at the ray cluster yaml file to get the remote path. There are still some room for improvement (ex: searching the ray_results folder location automatically both remote and locally , assuming that is what you want to sync, before tearing down the cluster)

I have attached my files as it stands today.
[ray_cluster_launch.zip](https://github.com/ray-project/ray/files/3473238/ray_cluster_launch.zip)

 

def ray_cluster_status_check(init=True):
    import yaml
    with open("Ray-Cluster.yaml", 'r') as stream:
        try:
            yaml_data = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    min_cluster_nodes = yaml_data['min_workers']+1 #one for head node
    init_cluster_nodes = yaml_data['initial_workers']+1 #one for head node
    if init:
        min_cluster_nodes = max(min_cluster_nodes,init_cluster_nodes)
    while True: #run waiting for the entire cluster to be initialized (or something else is wrong ?)
        available_nodes = len(ray.nodes())
        if available_nodes >= min_cluster_nodes:
            print("All nodes available. min_cluster_nodes count ", min_cluster_nodes,
                  "available_nodes count ", available_nodes)
            break
        else:
            print("available nodes count ", available_nodes," min cluster nodes required",
            min_cluster_nodes)

--------------------------------------------------------------------------------------------
                 ray_cluster_launch.sh
------------------------------------------------------------------------------------------
#!/bin/sh

if [ $# \> 0 ]
  then
    ray_yaml_file=$1
  else
    ray_yaml_file="Ray-Cluster.yaml" # Your default cluster yaml file
fi

if [ $# \> 1 ]
  then
    exec_cmd=$2
  else
    exec_cmd="cd rl_baselines_ad;./run_baseline.sh" # Your default ray exec cmnd
fi


outputfile="output_cluster.txt"

ray up -y $ray_yaml_file 
clear
# Python API ray_cluster_status_check() checks against ray_yaml_file to see if 
# min number of nodes are up or waits (embedded within the exec cmd step)
# Ideally we want to take this decision in shell before launching the ray exec
# command. Otherwise this will need to be put inside the dev code (ray_cluster_status_check())
ray exec --docker $ray_yaml_file "$exec_cmd"  2>&1 | tee  $outputfile
bash ray_sync.sh $ray_yaml_file 
ray down -y $ray_yaml_file

**Comment by pinakigupta** [comment]
In addition to my last comment ,
in brief I am looking for ray.nodes( ) equivalent in cli to have a better launch script. 
any suggestions ?

**Comment by richardliaw** [comment]
Sorry for the late response - you can use something like `ray get-worker-ips`
