### ISSUE TITLE
can not start ray workers in cluster nodes in docker container on different machines

### ISSUE THREAD

**Issue by WtyFile** [ray-project/ray#5371]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:linux
- **Ray installed from (source or binary)**:pip install ray
- **Ray version**:0.7.2
- **Python version**:3.6
- **Exact command to reproduce**:

### Source code / logs

I tried in 4 machines with ray.It works well.When i use ray in 4 docker container on different machine,it is wrong.
I deploy the ray example-full.yaml ,the same as i did in 4 machine and change the ip.
I use weave to make docker container ssh each other.The master container ip i use weave to set up is 192.168.0.101.The master container eth0 ip is 172.17.0.2.When i use container ray up ...local/example-full.yaml,then ray stop,then ray start --head --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml,it says 

Started Ray on this node. You can add additional nodes to the cluster by calling
    ray start --redis-address 172.17.0.2:6379 .
but the ip 172.17.0.2:6379  only can be used in one machine.it doesn't work at other machine.
When i ray start  --redis-address=192.168.0.101:6379 in cluster node 192.168.0.102 ,ray-worker can not start.$ps -ef|grep ray can not find worker.
When i see the raylet.err,it says
|||
I0805 11:07:11.566303  7679 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
W0805 11:07:11.568672  7679 redis_context.cc:208] Failed to connect to Redis, retrying.
W0805 11:07:11.568672  7679 redis_context.cc:208] Failed to connect to Redis, retrying.
...
Could not establish connection to redis 172.17.0.2:60403 (context.err = 1)
...
|||
i guess ray didn't connect to 192.168.0.101:60403,so it can't start ray-worker.How could i make it use 192.168.0.101:6379 .

**Comment by simon-mo** [comment]
I seems like the docker network must accessible from the outside. This can be achieved via ```
docker run --network=host ...
```

Note that the `redis-address` ip needs to the actual node ip (so it's accessible), instead of what ray says inside docker container.

**Comment by WtyFile** [comment]
Can't it be binded to 192.168.0.101?
Network=host seems to have problems when starting spark.Thanks for your reply. @simon-mo

**Comment by WtyFile** [comment]
Spark and hdfs works well in my docker container. They all use 192.xxx:ports. Only ray reids use 172.17.0.2:6379. Isn't there any way to set ray-redis-address to 192.168.0.101:6379?

**Comment by WangYiPengPeter** [comment]
in function get_node_ip_address() in ray.services.py  ,the way to get node_ip_address is using `s.connect(......)`   ，you can use the way in it's exception `socket.gethostbyname`  to get the ip address in your package.  @simon-mo

**Comment by WtyFile** [comment]
I use the way which @WangYiPengPeter says. It works well. Just change the function (socket.gethostbyname) in ray/services.py.
Just change the         
\\
        s.connect((ip_address, int(port)))
        node_ip_address = s.getsockname()[0]
\\
into 
\\
        hostname = socket.gethostname()
        node_ip_address = socket.gethostbyname(hostname)
\\
@simon-mo

**Comment by simon-mo** [comment]
@richardliaw do you think this will fix the docker networking issue in autoscaler?

**Comment by mattip** [comment]
This issue is closed, but did you try using [`ray start --node-ip-address`](https://docs.ray.io/en/latest/cluster/cli.html?highlight=node-ip-address#ray-start)?
