### ISSUE TITLE
All the doc links are broken :-(

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5388]
Googling ray now comes up with broken links:

https://ray.readthedocs.io/en/latest/plasma-object-store.html

**Comment by robertnishihara** [comment]
Maybe we can use something like https://docs.readthedocs.io/en/stable/automatic-redirects.html#redirecting-to-a-page to solve it.

**Comment by robertnishihara** [comment]
Thanks @drozzy for pointing this out. FYI the change that introduced this was https://github.com/ray-project/ray/pull/5175.

**Comment by richardliaw** [comment]
Fixed; for proper reference, you can also look at 0.7.3 docs.
