### ISSUE TITLE
`sphinx-build` in CI linting fails

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#5395]
The linting CI job is failing with:
```
/home/travis/build/ray-project/ray/doc/source/inspect.rst:43:Pygments lexer name 'ipython3' is not known

The command "sphinx-build -W -b html -d _build/doctrees source _build/html" exited with 2.
```

Seems like this it introduced in https://github.com/ray-project/ray/commit/a08ea097602b661b92dbd3074a2ce58e386ad061. @richardliaw can you please take a look?

**Comment by richardliaw** [comment]
I think we already fixed that - https://github.com/ray-project/ray/pull/5383. Can you maybe pull from master again? Thanks!
