### ISSUE TITLE
[rllib] Custom Loss Example Fails

### ISSUE THREAD

**Issue by brollb** [ray-project/ray#5398]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux (kernel 4.20.7-arch1-1-ARCH)
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.1
- **Python version**: 3.7.3
- **Exact command to reproduce**: 
First, I ran the train script for a little while to generate some data (as described in the top of the `custom_loss.py` file):
`python ./train.py --run=PG --config='{"output": "/tmp/cartpole"}' --env=CartPole-v0`
Then I tried to train the model using the custom loss:
`python examples/custom_loss.py --input-files=/tmp/cartpole`

### Describe the problem
I am trying to run the custom loss example (`ray/rllib/examples/custom_loss.py`) but am getting an error:
```
(pid=4952) Traceback (most recent call last):
(pid=4952)   File "/home/brbroll/.local/lib/python3.7/site-packages/ray/rllib/offline/json_reader.py", line 105, in _try_parse
(pid=4952)     return _from_json(line)
(pid=4952)   File "/home/brbroll/.local/lib/python3.7/site-packages/ray/rllib/offline/json_reader.py", line 154, in _from_json
(pid=4952)     return SampleBatch(data)
(pid=4952)   File "/home/brbroll/.local/lib/python3.7/site-packages/ray/rllib/policy/sample_batch.py", line 132, in __init__
(pid=4952)     assert len(set(lengths)) == 1, "data columns must be same length"
(pid=4952) AssertionError: data columns must be same length
```

Am I missing something?

**Comment by ericl** [comment]
This works on 0.7.3 for me?

**Comment by brollb** [comment]
Strange. I updated to 0.7.3 and it still failed. Maybe I can replicate it in a docker container or something

**Comment by ericl** [comment]
One that that would be helpful is attaching the data file that you saved. There seems to be some malformed batch in there.

**Comment by brollb** [comment]
Here is the cartpole data from /tmp/cartpole: https://drive.google.com/file/d/1NJbckYnLOUojAkmpehLu_zKpLQzagOIQ/view?usp=sharing

**Comment by ericl** [comment]
Ah, it seems to be since you don't have `lz4` installed. There is a bug in the batch encoder where if you don't have lz4, it encodes it as a string which then decodes improperly: https://github.com/ray-project/ray/pull/5421

**Comment by shortstheory** [comment]
I am having the same issue with the PPO Policy when I set `eager: true` in the configuration file. I have lz4 installed both through pip and vcpkg. 

## System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): KDE Neon 5.18
Ray installed from (source or binary): binary
Ray version: 0.8.5
Python version: 3.6.10

## Problem

```
ray.init()
ModelCatalog.register_custom_model(
        "ppo_model", PPOCustomNetwork)
        

config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0
config["num_workers"] = 4
config["vf_share_layers"]=False
config["eager"] = True
config["train_batch_size"] = 128
config["monitor"]="DEBUG"

# Environment parameters
config["env_config"]={
   "distribution": "uniform",
   "ep_length": 100,
   "dist":'normal',
   "phase": 1,
   "rho": 0.55,
   "flag_plot": False,
   "flag_output": False,
   "traj_seed": 0
}

config["model"] = {"custom_model": "ppo_model",
                   "conv_filters": [[32, [3,1],1], [64,[3,1],1], [64, [3,1],1]],
                   "fcnet_hiddens": [512, 512, 256],
                   "fcnet_activation": "relu",
                   'vf_share_layers': 'false'
                    }


trainer = ppo.PPOTrainer(config=config,env=DroneCARLLibOneStepCLEnv)
```

I get the same error `assert len(set(lengths)) == 1, "data columns must be same length"` in `sample_batch.py`. Am I missing something?
