### ISSUE TITLE
[tune] Add back the `status` column

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5408]
Awesome! That PR fixed it for me. Would it be possible to add back the `status` column? Which tells me which trial is RUNNING/TERMINATED, etc?

```
python python/ray/tune/scripts.py list-trials --filter "width > 50"  --sort width --columns width,opt_metric --desc True /tmp/tune/studies/hello_world_pelxg
+--------------+---------+
|   opt_metric |   width |
|--------------+---------|
|      56.5585 | 93.3237 |
|      15.5017 | 81.9795 |
|      94.1378 | 56.2671 |
|      96.8194 | 52.3797 |
|      25.2801 | 50.102  |
+--------------+---------+
```

_Originally posted by @bfortuner in https://github.com/ray-project/ray/issues/5376#issuecomment-518814398_

**Comment by bfortuner** [comment]
This extends to the Analysis/ExperimentAnalysis, too. Right I can't find a good way to figure out which trials failed? Previously, I could filter by status and see which hyperparam combinations caused failures.

**Comment by richardliaw** [comment]
Yeah, I need to get to this soon. I’ll cc you once I open a PR.
