### ISSUE TITLE
[autoscaler] dry-run

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#5410]
Does autoscaler has a `--dry-run` mode? If not, would it be difficult to implement it? 

I want to see all the commands to be ran but not run them.

**Comment by simon-mo** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
@hartikainen has something similar but no, not in repo right now

**Comment by richardliaw** [comment]
(And I don't think it would be hard to implement - you can just accumulate all of the `ssh_cmd` inputs instead of running them).

**Comment by edoakes** [comment]
Automatically closing stale issue. Please re-open if still relevant.
