### ISSUE TITLE
Check fail on scheduling_queue.cc:398]  Check failed: erased == 1

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5411]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**: 0.7.3
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

CHECK fail:
```
F0808 09:35:30.615465 56676 scheduling_queue.cc:398]  Check failed: erased == 1 
*** Check failure stack trace: ***
    @           0x71f99a  google::LogMessage::Fail()
    @           0x720d83  google::LogMessage::SendToLog()
    @           0x71f6c2  google::LogMessage::Flush()
    @           0x71f8b1  google::LogMessage::~LogMessage()
    @           0x54fa52  ray::RayLog::~RayLog()
    @           0x48daca  ray::raylet::SchedulingQueue::RemoveBlockedTaskId()
    @           0x475913  ray::raylet::NodeManager::HandleTaskUnblocked()
    @           0x47da7e  ray::raylet::NodeManager::HandleNotifyUnblockedRequest()
    @           0x434410  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc14ServerCallImplINS4_20RayletServiceHandlerENS4_22NotifyUnblockedRequestENS4_20NotifyUnblockedReplyEE13HandleRequestEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    @           0x4253ad  boost::asio::detail::scheduler::run()
    @           0x40f7a0  main
    @     0x7f9c83708830  __libc_start_main
    @           0x41ff81  (unknown)
```

**Comment by ericl** [comment]
I was running IMPALA on a multi-node cluster and run into this after a day. cc @stephanie-wang @pcmoritz

**Comment by pcmoritz** [comment]
Is this on the latest master? I think this is because of GRPC message reordering, we also ran into it with https://github.com/ray-project/ray/pull/5342. It will be fixed by https://github.com/ray-project/ray/pull/5385 but that will take a while until it is ready. Before that we won't be able to release unfortunately :(

**Comment by ericl** [comment]
This is 0.7.3. I'll close it for now then.

**Comment by pcmoritz** [comment]
Wait, that's bothersome. 0.7.3 was released without GRPC.

**Comment by ericl** [comment]
Ah, nevermind, it was actually 0.8.0dev3.

**Comment by simon-mo** [comment]
Yeah I ran into this as well before the release.

However, Jenkins did fail with 0.7.3 right before the release. due to some issue with module `mrand` not found: https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/15944/consoleFull
