### ISSUE TITLE
[tune] how to elegantly create pbt policy that changes over time

### ISSUE THREAD

**Issue by amazlz** [ray-project/ray#5424]
Is there a way to create an exploration function for population based training that is dependent on either time or performance metrics of the trained models

**Comment by richardliaw** [comment]
What is an example `exploration` function that you'd like to use? Right now there isn't a way, but we can provide a quick fix to make `custom_explore_fn` more flexible.

**Comment by amazlz** [comment]
For example restrict the learning rate distribution range as learning progresses, either as function of number of iterations or as function of the accuracy metric

**Comment by richardliaw** [comment]
One quick workaround is the use the ExperimentAnalysis object inside the explore function. This will enable you to read the logs for all the results and trials thus far, and make a decision of what to and how to explore based off of that. 

```python
local_dir = "..."

def custom_explore(config):
    analysis = ExperimentAnalysis(max(glob.glob(os.path.join(local_dir, "*.json")))
    df = analysis.dataframe()
    ...
```
The above code reads the state of the most recent experiment and obtains a dataframe of the most recent results.

If this works for you, we can introduce an API like `ExperimentAnalysis.most_recent_experiment()` which would make this less out-of-band.

**Comment by amazlz** [comment]
yes, this can work. Having access to the latest train result will also do the job.

Thanks
