### ISSUE TITLE
[rllib/tune] PBT with RLlib does not work when reuse_actors=True 

### ISSUE THREAD

**Issue by concretevitamin** [ray-project/ray#5425]
May need a way forward for expensive environments + PBT.  

/cc @richardliaw @ericl

**Comment by krfricke** [comment]
PBT works with reuse actors in the latest release. Feel free to re-open if there's something missing.

**Comment by richardliaw** [comment]
ah RLlib actually doesn't work out of the box with reuse_actors - I'll adjust the issue title.

**Comment by cfusting** [comment]
This also does not appear to work with ax. Is this expected?

**Comment by richardliaw** [comment]
No, that is not expected @cfusting -- could you open a new issue and post the stack trace?

Thanks a bunch!

**Comment by cfusting** [comment]
Sure, although there is no stack. Rather it looks like setup is being called for each new trial rather than reset_config.

**Comment by richardliaw** [comment]
got it, let's follow up on a separate issue!

**Comment by cfusting** [comment]
Apologies @richardliaw but I am not going to be able to meet the requirements to post a fully reproducible script and have hence not opened an additional issue. Is there a lighter "bug suspected" issue I can open? <g>.

**Comment by richardliaw** [comment]
Yeah! Maybe just open a thread on `discuss.ray.io` .
