### ISSUE TITLE
PPO-ES experiment in rllib

### ISSUE THREAD

**Issue by nanxintin** [ray-project/ray#5431]
Hi @ericl,
I am very interested in your Rllib project. When I read your rllib paper, I notice that you conduct a PPO-ES experiment in Section 3.4. I am doing similar work on combining RL and ES, while I cannot found the relative code in rllib. Would you please give me some suggestions on this work and tell me how to find the code ?

Looking for your reply.
Thanks a lot.

**Comment by ericl** [comment]
There's some pseudocode here: https://arxiv.org/pdf/1712.09381v1.pdf

However, this is probably not going to run in the latest RLlib. It is not an officially supported algorithm.
