### ISSUE TITLE
Local machine connecting to Ray Cluster Issue

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#5437]
### System information
- Arch Linux
- installed from binary
- ray 0.7.3
- python 3.7.4

### Describe the problem
Is it possible to create a ray cluster and connect to it from my local PC? I have no problem creating a head-node on a server and connecting to it from another server (and executing ray.put() without problems), as long as they are on the same network. However, I'd like to connect to the same cluster from my home PC (as I want to use my own graphics card for optimizations and only use the cluster for CPU rollouts). This doesn't seem to work. I opened all ports and followed the instructions as described [here](https://github.com/ray-project/ray/issues/4090#issuecomment-468480592) and [here](https://github.com/ray-project/ray/issues/4393#issuecomment-478729221) on all servers. I also opened the ports locally (via UFW) and on my router. I also made sure that I started the ray-head-node (I tested connecting to it from another server on the same network) and launched "ray start" on my local pc via: 

`ray start --redis-address=HEAD-NODE-IP:6379 --node-manager-port=12345 --object-manager-port=12346`

However, when I then want to connect in python via `ray.init(redis_address=HEAD-NODE-IP)` it results in this error:
```
Exception: Redis has started but no raylets have registered yet.
```

What am I doing wrong? 

Thanks!

**Comment by NikEyX** [comment]
It doesn't even seem to register my local PC as new client when I run `ray start` - it doesn't matter whether it provide --node-ip-address or not.

The `client_table` in `get_address_info_from_redis_helper` (where it eventually fails when I try to do ray.init(..) from my PC) looks like this:

```
{'ClientID': '7225c4bd140a645a6d69fd26e33ef2a551a7be26', 'IsInsertion': True, 'NodeManagerAddress': '10.128.0.XXX', 'NodeManagerPort': 12345, 'ObjectManagerPort': 12346, 'ObjectStoreSocketName': '/tmp/ray/session_2019-08-12_01-14-31_546746_16042/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2019-08-12_01-14-31_546746_16042/sockets/raylet', 'Resources': {'CPU': 8.0}}

{'ClientID': 'cb30337e5ac7f440266c3a7330f06b5f7d3ef68a', 'IsInsertion': True, 'NodeManagerAddress': '10.128.0.YYY', 'NodeManagerPort': 12345, 'ObjectManagerPort': 12346, 'ObjectStoreSocketName': '/tmp/ray/session_2019-08-12_01-14-31_546746_16042/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2019-08-12_01-14-31_546746_16042/sockets/raylet', 'Resources': {'CPU': 12.0}}
```

This includes (1) the head-node and (2) the test-node connecting from the same network. However, the client table does not seem to have registered my client from my local machine even though running `ray start` did not report any errors.

Is it even possible to have a node outside of the local network in ray?

**Comment by simon-mo** [comment]
Is `HEAD-NODE-IP` public IP? Because by default, `ray` uses python's `socket` library to find the current IP address of the machine, however, this is most likely the private IP address that works within the same router. There is a publicaly accessible IP, try to start ray head node with 
```
--node-ip-address <head-node-ip>
```
so it will advertise the public IP.

**Comment by NikEyX** [comment]
Yes that fixed it. Thanks! The head-node-ip has to be the external IP, not internal, then it works.
