### ISSUE TITLE
Failed to connect to all addresses

### ISSUE THREAD

**Issue by NikEyX** [ray-project/ray#5442]
### System information
- **OS Platform and Distribution**: Arch Linux
- **Ray installed from**: binary
- **Ray version**: 0.7.3
- **Python version**: 3.7.4

### Describe the problem
Connecting from my private PC to a head-node on GCP. Simple tests like putting and receiving objects work, even for Actors. However, somewhere along the line my scripts fail. The `raylet.err` file contains these msgs:
```
I0813 05:36:36.739015 11309 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
I0813 05:36:36.740854 11309 redis_gcs_client.cc:145] RedisGcsClient::Connect finished with status OK
I0813 05:36:36.742856 11309 grpc_server.cc:26] ObjectManager server started, listening on port 12346.
I0813 05:36:36.758617 11309 grpc_server.cc:26] NodeManager server started, listening on port 12345.
W0813 05:37:34.544533 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e4ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544592 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e6ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544602 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e5ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544611 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e7ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544620 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e9ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544629 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7eaffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
W0813 05:37:34.544637 11309 object_manager.cc:261] Send pull 0369a14bc595e08cfbd508dfaa162cb7e8ffffff request to client 80177b7503bb5ea42ae5be4ba8cf4bdc2ba0a795 failed due tofailed to connect to all addresses
.....
```

Any idea what causes that? the 4 ports in question are open on the server, the home PC, and the router, so not sure why it "failed to connect"?

Also is it possible to give a python path or working folder directly to the nodes? Since I have various files (which are not necessarily a package), I'd like them to be available to each worker. Currently I fixed this by adding the path to the files manually using  `sys.path.append` in `__main__` of `default_worker.py` - that kinda seemed to work, but maybe this is directly related to the above issue.

Thank you in advance!

**Comment by simon-mo** [comment]
For the second question, you can use the autoscaler local mode to sync your files from local laptop to the cluster. See [here](https://github.com/ray-project/ray/blob/1376f1ae60e1ce20fc3902d6a56ae25d352b6a7f/python/ray/autoscaler/local/example-full.yaml#L50-L55) for files mounts instruction, and see [here](https://ray.readthedocs.io/en/latest/autoscaling.html) for autoscaler commands useage.

For the first question, it's quite like that one of the object manager was unable to talk to
(1) object managers on _any_ other nodes
(2) the redis running in head node.

**Comment by NikEyX** [comment]
Is it possible to upload files without the autoscaler, e.g. just with normal rsync? Where do I put them? Any files I need to adapt? 

Any suggestion on how to best debug the object manager issue? Any files or error messages that are useful?

**Comment by NikEyX** [comment]
Ok, I fixed it. In case people are facing the same issues at some point: 

1) There does not seem to be a specific ray folder or anything of the like. Given that the ray examples work even without uploading any files specifically, I figured there would be some path where the content is automatically put, but I guess it's just cloudpickled and unpickled in memory or something like that. Anyways, that was the cause of my confusion. Given that there is no ray specific code folder, it doesn't matter where you rsync your stuff to (or if you want to use the autoscaler then you can just use the yaml file). You just need to add the contents onto the PYTHONPATH. At least that's my understanding.

2) If you want to connect your local PC to an external ray cluster like I wanted, then "ray start" needs to be provided with --node-ip-address, being the **external** ip, not the internal one.  I did this previously only for the head-node and did not expect this to be relevant for the non-head-nodes as well. In short: every node needs to be provided with its own external ip address. In my opinion this should really be mentioned when the ray node gets started - currently it only says: `If you have trouble connecting from a different machine, check that your firewall is configured properly` and makes no mention of external ips. Maybe something easy to improve? Speaking of firewall, you will also need to open port 12345 and 12346 on your router/firewall. In addition to all that you need to restart both the ray head-node and remaining ray nodes (i.e. on your local PC) after you do these changes, otherwise you will get the most random errors that lead you nowhere. After that you should be able to connect from your local PC to the cluster by running `ray.init(redis_address=<HEAD-NODE-EXTERNAL-IP>, node_ip_address=<LOCAL-NODE-EXTERNAL-IP>)`. I would also recommend putting a password on the server - you'll need to use `redis_password` for that (again on all nodes + driver).

**Comment by Julianbaozi** [comment]
@NikEyX 
Hi, I saw your answer about exposing your public IP. Is your computer connected to a router? Did you do any IP forwarding? Because I'm using my laptop and using a public wifi so I can't set forwarding rules.
