### ISSUE TITLE
[rllib] In addition to ignore_worker_failures, add option to restore original number of workers

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5451]
### Describe the problem
We should add a config option that restores the original number of workers whenever any of them fail. This is valuable for very error-prone environments, such as the minerl environment. This amounts to modifying some code in the `_try_recover()` method in `agents/trainer.py` involving the following lines, after calling reset:
```
if config["restore_workers"]:
    num_healthy_workers = len(self.optimizer.workers.remote_workers())
    self.optimizer.workers.add_workers(config["num_workers"]-num_healthy_workers)
```
In addition, the worker indexes might need to be changed. 

As far as I can tell `worker_index`, an argument to the `RolloutWorker` class, influences `EnvContext`/`env_creator`, as well as the environment seed, and `IOContext`, but I am unable to judge its importance (would appreciate input here). If it needs to be changed, we can include a `created_workers` counter in `Trainer`, as well as an additional starting index argument in `add_workers`.

**Comment by ericl** [comment]
Incrementing the worker index sounds reasonable, if we can't replace the original failed worker index exactly. The latter would be somewhat better since certain algorithms like Apex use it to set the distribution of explorations.

**Comment by simonsays1980** [comment]
@ArturNiederfahrenhorst I think we can close this one as `recreate_failed_workers`, `ignore_failed_workers` and `restart_failed_sub_environments` account for this now
