### ISSUE TITLE
[rllib] Add algorithms for imitation learning and hierarchical RL

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5455]
There is a noticeable lack of such algorithms implemented. I would be happy to contribute. Open to suggestions. Will add some papers here if anyone else is interested.

**Comment by richardliaw** [comment]
Can you add some papers?

**Comment by ericl** [comment]
That would be great. Note that there is MARWIL (which is kind of an IL).

**Comment by pimpke** [comment]
@jon-chuang Hi Jon, could you add the papers you thought of? I'm also interested in adding this.

**Comment by jon-chuang** [comment]
Here are some papers:

Hierarchical:
HIRO (https://papers.nips.cc/paper/7591-data-efficient-hierarchical-reinforcement-learning.pdf)
HAC (https://github.com/andrew-j-levy/Hierarchical-Actor-Critc-HAC-)
Optimal Rep Learning (of goals) for Hierarchies (https://arxiv.org/pdf/1810.01257.pdf)

Imitation Learning (just a name drop):
GAIL (and improvements, as configs), SQIL, Normalised Actor-Critic, BC pipeline

**Comment by kivo360** [comment]
Is this gonna happen? I use a different library to do hierarchical learning on the side. Having something integrated would be nice.

**Comment by saeid93** [comment]
> Is this gonna happen? I use a different library to do hierarchical learning on the side. Having something integrated would be nice.

Hi, could you please send the link to the library you use for hierarchical learning?

**Comment by safdark** [comment]
Has this been abandoned? Hopefully not...
