### ISSUE TITLE
Java tests require compile step

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#5457]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04, Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: latest master
- **Python version**: N/A
- **Exact command to reproduce**: Run `java/test.sh`

### Describe the problem

If I set up openjdk-8 and run `bash java/test.sh`, I get the following error:

```
(base) ubuntu@ip-172-31-18-253:~/ray-1$ ./java/test.sh
+++ dirname ./java/test.sh
++ cd ./java
++ pwd
+ ROOT_DIR=/home/ubuntu/ray-1/java
+ pushd /home/ubuntu/ray-1/java/..
~/ray-1 ~/ray-1
+ echo 'Linting Java code with checkstyle.'
Linting Java code with checkstyle.
+ bazel test //java:all --test_tag_filters=checkstyle --build_tests_only
INFO: Analyzed 7 targets (0 packages loaded, 0 targets configured).
INFO: Found 7 test targets...
INFO: Elapsed time: 0.232s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//java:org_ray_ray_api-checkstyle                               (cached) PASSED in 6.5s
//java:org_ray_ray_runtime-checkstyle                           (cached) PASSED in 4.3s
//java:org_ray_ray_runtime_test-checkstyle                      (cached) PASSED in 3.0s
//java:org_ray_ray_streaming-checkstyle                         (cached) PASSED in 5.0s
//java:org_ray_ray_streaming_test-checkstyle                    (cached) PASSED in 2.7s
//java:org_ray_ray_test-checkstyle                              (cached) PASSED in 4.4s
//java:org_ray_ray_tutorial-checkstyle                          (cached) PASSED in 3.8s

INFO: Build completed successfully, 1 total action
+ echo 'Running tests under cluster mode.'
Running tests under cluster mode.
+ ENABLE_MULTI_LANGUAGE_TESTS=1
+ run_testng java -cp /home/ubuntu/ray-1/java/../bazel-bin/java/all_tests_deploy.jar org.testng.TestNG -d /tmp/ray_java_test_output /home/ubuntu/ray-1/java/testng.xml
+ java -cp /home/ubuntu/ray-1/java/../bazel-bin/java/all_tests_deploy.jar org.testng.TestNG -d /tmp/ray_java_test_output /home/ubuntu/ray-1/java/testng.xml
Error: Could not find or load main class org.testng.TestNG
+ exit_code=1
+ '[' 1 -ne 2 ']'
+ '[' 1 -ne 0 ']'
+ exit 1
Could not find or load main class org.testng.TestNG
```

```
java -cp /home/ubuntu/ray/java/../bazel-bin/java/all_tests_deploy.jar org.testng.TestNG -d /tmp/ray_java_test_output /home/ubuntu/ray/java/testng.xml
```

and I think the reason is that `/home/ubuntu/ray/java/../bazel-bin/java/all_tests_deploy.jar` doesn't exist.

cc @raulchen @zhijunfu @jovany-wang

**Comment by pcmoritz** [comment]
As a workaround, running `bazel build java/all_tests_deploy.jar` manually makes it work. Probably some bazel dependency is not specified correctly.

**Comment by raulchen** [comment]
@pcmoritz did you build java before running the test script? `./build.sh -l python, java`

**Comment by pcmoritz** [comment]
Thanks, that solves to problem too yeah. I'll leave this open since we should probably make sure that bazel tests (re)compile stuff if the source change (i.e. make sure the dependencies in bazel are complete).

**Comment by raulchen** [comment]
@pcmoritz We used to recompile code in this test script. However, this made the test too slow. Because sometimes bazel may discard cache and re-compile the whole project (e.g., when the `PATH` env var changes).
I think maybe a better way is to print a warning when code needs recompile. But I'm not sure what is the best way to determine if code needs recompile.

**Comment by raulchen** [comment]
Update: this is no longer the case. Compiled binaries (mac + Linux) are included in the jar and wheel files.
