### ISSUE TITLE
[rllib] Add Support for Memory Modules

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5471]
We should add support for various memory modules:
MERLIN - buffer of memory encodings through predictive coding and retroactive updating 
(https://arxiv.org/pdf/1803.10760.pdf)
SPTM - topological memory (graph) of vision embeddings for optimal path planning and localisation 
(https://arxiv.org/pdf/1803.00653.pdf)
Episodic curiosity through reachability (siamese network reachability metric) 
(https://arxiv.org/pdf/1810.02274.pdf)
Relational Memory Core - fixed-sized buffer with a recurrent transformer forward pass 
(https://arxiv.org/pdf/1806.01822.pdf, https://arxiv.org/pdf/1806.01830.pdf) (Relation to Capsules, transformer-XL? Difference from RNN: Transformer architecture allows arbitrary buffer sizes, but hard to tell just how many it scales to from papers) 

These are all Deepmind papers :)
They seem to think that memory is a vital component in future agents. IMHO, I think we should too :)

Neural Map - cheats with ground truth agent position, though this can be approximated with dead reckoning/other SLAM techniques to correct for error. However, I prefer the topological memory approach, which circumvents this. 
(https://arxiv.org/pdf/1702.08360.pdf)

I would be interested to see comparisons of performance in various navigation environments.

**Comment by jon-chuang** [comment]
Dear admins, I would like to request that this issue be deleted, it turned into a long rant which I will put elsewhere; instead I will open another issue that is clearer and with fewer misconceptions, on the topic of memory modules in RL, namely RMC, MERLIN and Reachability, and their extensions. Thank you.

**Comment by kivo360** [comment]
I could see the need for this too.

**Comment by kivo360** [comment]
I was able to create a bootleg version of memory. I'm pickling the state and storing it by reference inside of an episode. I can then reconstruct the memory by selecting which memories. I have no idea if this idea will be tracked further by the RLLib team, though I'm an advocate for crafting your own solution.
