### ISSUE TITLE
[rllib] Add automatic autoregressive action builder

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5475]
We should support automatic autoregressive action model builder, for now for discrete actions, that supports parametricity in child spaces (choose a child space based on action selected in parent space), which takes as input a specification of an action dependence tree. (We are not referring to variable length action spaces conditioned on observations).

Here we take elements in a list to be independently sampled actions, and tuples, which must be of even length, express parent child dependencies, so that the even entries (counting from 0) represent the parents, and children lie in the odd entries, with tuples of length > 2 expressing parametric decomposition. 

The builder will then collect the results and return the indices of the selected actions in the same format, where `None` will replace entries where parametric actions were not selected. 

In addition, standard function calls such as entropy and kl will be built automatically, although due to the nested structure we might want to support either a mean over samples approach or explicit computation to get a more accurate estimate of the respective quantities. 

A possible caveat is that the gym action space datatypes don't seem to support such a return format. 

Example specification:
```
[(19, [5,5], 1, [15]), 8]
```
Example results:
```
[(8, [3,3], None, None), 6]
[(None, None, 1, 12), 8]
```
In a simple a2|a1 scenario, both
```
(2,2)
[(2,2)]
```
should be fine. 

The models will by default be conditioned on a context input, and built and stored in the following format, with branching conditioned determined by the above tree structure. (Perhaps I should use an actual tree instead of this "DSL"). Parametric child spaces will introduce a special intermediate index, which is bracketed.
```
[(models["0"], models["0(0)0"], models["0(0)1"], models["0(1)0"]), models["1"]]
```

**Comment by jon-chuang** [comment]
@ericl to check, an action distribution has to be vectorized over a batch?
This would present some problems for parametric child spaces. But I can resort to using masks to combine the results.

**Comment by ericl** [comment]
Yeah, it does have to be vectorised.

**Comment by jon-chuang** [comment]
There exist a straightforward solution where all the results in each parametric subspace are computed regardless of the parent sample, and where here we feed the entire parent sample into each child network, and it is up to the context which calls for a sample to process it properly; for instance, entropy and kl computations must mask child spaces that are not selected for by a parent sample.

**Comment by ericl** [comment]
Can you elaborate? I'm under the impression autoregressive sampling can be
vectorised trivially along with the parameterization mask or dot product,
which is already vectorized itself.

**Comment by ericl** [comment]
Ok I see, I think it makes sense to always compute and then mask any unused child spaces. Or, the actions of those spaces could always be fixed so they don't have any gradient with respect to entropy or kl.

This should also be compatible with gym spaces correct?

**Comment by jon-chuang** [comment]
For the gym spaces I was thinking using Dict with the above model indexing could work. 

I will think about a better way to write down the specification so that it includes labels like "a1", "a2", so the dict can index that way and presents a more human readable interface. 

Also, there is currently no way to merge branches. This is a feature as you might want parent actions to a given child space to be sampled independently. It can't be handled by the above indexing rule.

**Comment by jon-chuang** [comment]
This is the format I've settled on:
```
{"a1": {"action_space": {0: 19, 1: 1}, 
    "dependents": {0: [a3, a4], 1: [a5]}
},
 "a2": {"action_space": 8},
 "a3": {"action_space": 5},
 "a4": {"action_space": 5},
 "a5": {"action_space": 15}
}
```
If action space is parametric, it is a dict. Else it is an int. The input and return formats will be dicts with the given action keywords.

**Comment by ericl** [comment]
Can you provide some different examples? It is quite hard to understand the proposal as is.

**Comment by jon-chuang** [comment]
Sure. I've written most of the code, will submit a pull request soon. I'll try to use a hypothetical starcraft II env as an example, which has a huge nested action space.

https://github.com/deepmind/pysc2/blob/master/docs/environment.md#actions
https://arxiv.org/abs/1708.04782 (section 4.2)

**Comment by jon-chuang** [comment]
I will expose an option for both a sampling based estimator, for continuous (which I will support soon) or exponentially large action spaces and full computation for small discrete action spaces of the AR KL and entropy. The default will be sampling based estimation.

**Comment by jon-chuang** [comment]
I will add support for both torch and tf models.
@ericl I'm not sure about the interface. For instance, I am not sure if I should expose a tf-style API with a torch backend, to allow for compatibility with the PPO/IMPALA/APE-X pipelines.
I'm wondering if we should try to write all pipelines in a framework-agnostic style. Thoughts?

**Comment by jon-chuang** [comment]
If I have time I will try to implement MADE (https://arxiv.org/pdf/1502.03509.pdf) and compare performance.

**Comment by jon-chuang** [comment]
Hi @ericl, need some advice in terms of implementation; should I convert a categorical sample to float, one-hot or just retain `tf.int32` as is when feeding to child action space models?

**Comment by jon-chuang** [comment]
I will write a comprehensive set of unit tests; including checking the entropy and kl lie within certain bounds given some dummy inputs w/ randomly initialised weights; just a sanity check for the correctness. I will write tests to check that input verification steps throw errors on malformed inputs. @ericl advice on which are most necessary?

**Comment by SuhitK** [comment]
@jon-chuang were you able to complete this for the starcraft environment? I am working on a problem that requires this and would be useful if there is a template I could follow.

**Comment by RocketRider** [comment]
Did you get it running? 
I am trying to implement something very similar, but running into training issues.
