### ISSUE TITLE
[rllib] A vision for RLLib

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5478]
Although RLLib was started as a way to scale RL pipelines to arbitrary distributed training setups, apart from the algorithms already available, it seems to me the learning curve for configuring the pipeline, models, and adding additional components is quite steep. 

For this reason, I propose a second vision for RLLib: to make prototyping, iteration and deployment of arbitrary RL setups and models pain free. In this way, I envision RLLib becoming the one stop shop for RL reproducibility in research and production. 

To achieve this, it seems we need more abstractions that help capture the inclusion of auxiliary components and models as well as more diverse pipelines. We should also provide more reusable, configurable components, especially those that are ordinarily difficult to implement and integrate, e.g. memory, distributional value approximation, we enable the community to experiment and get a better understanding of how component choices ultimately affect performance. This might also draw wider interest as it is a contribution opportunity. 

To provide more flexibility, I propose to implement a model builder that automatically builds models based on some specifications, rather than to maintain a collection of disparate models in `model_catalogy.py`. For instance, the variations that go into making rainbow.

In addition, we should expose an easier to configure user-facing interface that makes combining the components pain free. Finally, documentation should provide clear visualisations about how these components combine. We also need to include a configuration flowchart, which guides users through a process of configuring the various components in a step by step fashion. In addition, this flowchart should include some data-backed advice for choices under different RL demands (sample-efficiency, wall-clock, robustness, sparse rewards, navigation, metaRL, continuous control, first-person control, hierarchical, multi-agent)

The only pain points that should remain are configuring the interface between data/env and RLLib. This way, researchers are freed to pursue creative ideas once these are setup.

**Comment by jon-chuang** [comment]
An example of a clean, hassle free configuration would be that of Flambe's, which has ray as a dependency :) 
https://github.com/Open-ASAPP/flambe

**Comment by richardliaw** [comment]
@jon-chuang thanks for these suggestions! For this proposal, can you post some ideal code API/workflows?

**Comment by jon-chuang** [comment]
Hi @richardliaw, will work towards this step by step and post some work products once they are ready.
Perhaps as some goals, we should aim to accomodate complicated workflows/model dependencies such as this: 
CURIOUS:  Intrinsically Motivated Modular
Multi-Goal Reinforcement Learning (https://arxiv.org/pdf/1810.06284.pdf)
