### ISSUE TITLE
[rllib] Add support for hyperbolic discounting and multi-horizon value prediction

### ISSUE THREAD

**Issue by jon-chuang** [ray-project/ray#5480]
As described here:
https://arxiv.org/pdf/1902.06865.pdf

**Comment by kivo360** [comment]
Did you start creating a contribution for this. I'm doing something similar outside of the RLlib agent and would like to reduce the amount of code I have to watch.

**Comment by jon-chuang** [comment]
Sorry, no, been busy with other projects these days.

**Comment by kivo360** [comment]
Mkay
