### ISSUE TITLE
[rllib] Hypothetical -  Attribute actions to reward out of order with PolicyClient

### ISSUE THREAD

**Issue by kivo360** [ray-project/ray#5483]
I have some questions about using the `PolicyServer` and `PolicyClient`.

I recall there was a statement that the model looks for a reward to be given directly after an action has been generated. Let's say however, that I'm getting actions and rewards out of order. So instead of getting my action, then pushing that action into an outside environment to immediately give it a reward.

For instance, a synchronized example might look like:
```py
action = client.get_action(episode_id, observation)
reward = externalenvironmet.input_action(action)
client.log_reward(episode_id, reward)
```

The out-of-order method might look like:
```py
action1 = client.get_action(episode_id, observation1)
action2 = client.get_action(episode_id, observation2)
action3 = client.get_action(episode_id, observation3)
action4 = client.get_action(episode_id, observation4)

reward1 = externalenvironmet.input_action(action1)
reward2 = externalenvironmet.input_action(action2)

client.log_reward(episode_id, reward1)
reward3 = externalenvironmet.input_action(action3)

client.log_reward(episode_id, reward3)
reward4 = externalenvironmet.input_action(action4)

client.log_reward(episode_id, reward2)
client.log_reward(episode_id, reward4)
```

Where the reward inputted into the system would be very much out of sync from when the action was generated.

I'm going through simple reward shaping right now and I'm realizing that while I'm somewhat getting the results I want, the agent is also somewhat confused about what is relevant to what. I'm guessing that the reason to that is that the agent on the server is expecting the reward to be inputted immediately after the action is generated. 

How can I can attribute the reward to the action for the `PolicyServer/Client`? I was looking at the samplebatch builder that was in the offline data example. It seems as though it has the capacity to state the previous action and reward as well as the current action and reward, so the RL algorithm could understand the order of events.

**Comment by ericl** [comment]
You can do this with a custom postprocessing callback (and putting the reward data into info for the callback. On the dev list there are some threads related to backdating rewards like this.

**Comment by kivo360** [comment]
Is there a link to any other issue to show how this would work? I haven't done a callback before.

Would I store the action_id and evaluate how that action played out via the action_id?

I found this so far.
https://ray.readthedocs.io/en/latest/rllib-training.html#callbacks-and-custom-metrics

**Comment by kivo360** [comment]
I was able to figure something out. I plan on asking another question about PopArt in another forum.
