### ISSUE TITLE
[tune] Median stopping rule never do early stopping in realistic conditions

### ISSUE THREAD

**Issue by alexeypiex** [ray-project/ray#5485]
https://github.com/ray-project/ray/blob/99a2f9fab39f2d05f70498f4c27b09d96f2b72fe/python/ray/tune/schedulers/median_stopping_rule.py#L130

Best current result (for example loss) is compared to median of MEAN results averaged from the very start. So if you have a huge value of loss function on step 1 for all configurations and during iterations it decays fast averaging through all values will give big average loss and => big median average loss. So even mediocre configurations will pass this condition and will be run till the end making this scheduler equivalent to FIFO scheduler

**Comment by richardliaw** [comment]
I think #5402 should fix this (though that PR needs to be cleaned up).

**Comment by richardliaw** [comment]
Should be closed by #5402.
