### ISSUE TITLE
[tune] Torch - Key already registered with the same priority: C10

### ISSUE THREAD

**Issue by Omegastick** [ray-project/ray#5488]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Wheel
- **Ray version**: 0.8.0.dev3
- **Python version**: 3.6.5
- **Exact command to reproduce**: N/A

### Describe the problem
When importing a module built using Libtorch and PyBind11, Ray Tune gives the following error:
```
Key already registered with the same priority: C10
```

This doesn't happen in local mode.

### Source code / logs
Source code:
```python
import ray
import ray.tune as tune
import my_libtorch_module

def train(_):
    pass

def main():
    ray.init()
    tune.run(train,
             name="test",
             num_samples=10)

if __name__ == '__main__':
    main()
```

Logs:
```
2019-08-20 20:29:05,484	INFO function_runner.py:254 -- tune.track signature detected.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs
Memory usage on this node: 6.4/16.5 GB

2019-08-20 20:29:07,162	WARNING logger.py:255 -- Could not instantiate <class 'ray.tune.logger.TFLogger'> - skipping.
Key already registered with the same priority: C10
```

**Comment by richardliaw** [comment]
This looks odd; what if you put the `import my_libtorch_module` inside `def train`?

**Comment by Omegastick** [comment]
When I put the import inside the training function, I get the following error:
```
ImportError: /home/omega/dev/pytorch/torch/lib/libtorch.so: undefined symbol: _ZNK3c1010TensorImpl13is_contiguousENS_12MemoryFormatE
```

Importing the same library works fine in a non-ray script. I'd guess that there's some problem in my Libtorch setup somewhere. I'll keep looking into it.

**Comment by Omegastick** [comment]
I tried building the latest Ray from source, but no changes there.
It works fine on another computer I tried, which is also running the latest Ray wheel, telling me that this is 99% a problem with my PyTorch install on this computer.

**Comment by richardliaw** [comment]
I'll close this for now; but if this is an issue, please reopen/comment again.

**Comment by sc779733661** [comment]
Has anyone encountered and solved this problem?I have the same problem

**Comment by VasilijKolomiets** [comment]
> Has anyone encountered and solved this problem?I have the same problem

https://discuss.pytorch.org/t/importerror-key-already-registered-with-the-same-priority/86271
