### ISSUE TITLE
Specify `---log-dir` when `ray start`

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#5495]
Before https://github.com/ray-project/ray/pull/4605, we can specify the log dir by given a fixed `temp-dir`.
After it, we have no option to specify a fixed log-dir.

I'd like to have a command like this to specify a fixed log dir.
```
ray start --log-dir "a/b/c"
```

**Comment by jovany-wang** [comment]
@suquark  @robertnishihara  cc

Does this make sense?

**Comment by edoakes** [comment]
@jovany-wang that would be great, do you want to make a PR for this?
