### ISSUE TITLE
[autoscaler] `ray up` only launches Docker container on head

### ISSUE THREAD

**Issue by ethanabrooks** [ray-project/ray#5496]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Head node: OSX Mojave
Workers: Ubuntu 16.04
- **Ray installed from (source or binary)**: Source
- **Ray version**: 0.7.3
- **Python version**: 3.7.4
- **Exact command to reproduce**:
```
ray up tune.yaml
ray submit --docker tune.yaml tune_script.py
```
`tune.yaml`: https://github.com/ethanabrooks/ppo/blob/tune-task/tune.yaml
`Dockerfile`: https://github.com/lobachevzky/ppo/blob/tune-task/Dockerfile
`tune_script.py`: https://github.com/lobachevzky/ppo/blob/tune-task/tune_script.py

### Describe the problem
I am trying to use the Ray library to launch runs on multiple remote machines with Docker. Per the docs, I use `ray up CONFIG_YAML` to set up my cluster and `ray submit [OPTIONS] CLUSTER_CONFIG_FILE SCRIPT` to run a script on them. The problem is that the process/container only launches on the head node and nothing runs on the workers.

Examining the source, `ray up CONFIG_YAML` calls the function `create_or_update_cluster` and `ray submit [OPTIONS] CLUSTER_CONFIG_FILE SCRIPT` calls `submit`. Neither of these appear to interact with any node except the head.

**Comment by richardliaw** [comment]
Do you have the output of the `ray exec YAML '/tmp/...monitor.*` logs?

**Comment by ethanabrooks** [comment]
The output is ongoing but here is what prints out in the first few minutes: https://gist.github.com/ethanabrooks/f9cbd36276e4e87b7358052cdcfc6d9a

**Comment by richardliaw** [comment]
I see; it's still trying to log in to the other machine (`141.212.113.254`). Can you check that you can ssh into `141.212.113.254` from `141.213.3.4`?

**Comment by vtomenko** [comment]
In my case installing ssh-client in docker helped

**Comment by ijrsvt** [comment]
The 'general requirements' of Autoscaler are highlighted in the [`base-deps/Dockerfile`](https://github.com/ray-project/ray/blob/master/docker/base-deps/Dockerfile):
