### ISSUE TITLE
Cant import ray on GCP due to pyarrow

### ISSUE THREAD

**Issue by ghost** [ray-project/ray#5497]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9 
- **Ray version**: 0.7.3
- **Python version**: 3.5.3

### Describe the problem

Same as 'philwinder' commented on 25 Jun, only on GCP AI Platform.

After running:

!pip install -U ray
import ray

I get the error message:

ImportError: Ray must be imported before pyarrow because Ray requires a specific version of pyarrow (which is packaged along with Ray).

Running the recommended fix 

!pip install tensorflow  # or tensorflow-gpu
!pip install ray[rllib]  # also recommended: ray[debug]
!pip uninstall -y pyarrow

doesnt solve the problem.

**Comment by richardliaw** [comment]
@kiddyboots216 didn't you solve this issue?

**Comment by kiddyboots216** [comment]
@richardliaw the Colab solution (which I use) apparently doesn't work for him, so no. @douglasuff0 are you doing this in an IPYNB on GCP or in a Python process? if IPYNB, you would need to restart the kernel after installing/uninstalling anything. If Python process, you may need to uninstall/reinstall the 'google' package, I'm not sure...

**Comment by douglasuff0** [comment]
@kiddyboots216 I'm using a IPYNB. I tried restarting the kernel after running the Colab solution, with no success.

**Comment by kiddyboots216** [comment]
Jupyter version?

**Comment by douglasuff0** [comment]
!jupyter --version

jupyter core     : 4.5.0
jupyter-notebook : 5.7.8
qtconsole        : 4.5.1
ipython          : 7.6.1
ipykernel        : 5.1.1
jupyter client   : 5.2.4
jupyter lab      : 0.35.5
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2

**Comment by richardliaw** [comment]
this should work now with ray 1.0
