### ISSUE TITLE
[rllib] Retrain or predict multiagent environment with different number of agents

### ISSUE THREAD

**Issue by marclipoff** [ray-project/ray#5498]
I have an environment where agents place bids for online advertising. I've modeled this after the central_critic_2 example. In that example, there are 2 agents. In my environment there are an arbitrary number of agents. 

The workflow I intend to implement is the following:
a) Train a baseline model with an environment with X agents, using generic reward and observation functions. Ideally, the model would learn things like, if you bid higher amount, you spend more money. 
b) For my specific problem, I use the baseline model, and re-train it, using an environment with Y agents. This, ideally, would have a short training time, as it would already have an understand of the basic problem/environment.
c) Then, I predict -- or determine the optimal actions -- for those Y agents for some T timesteps in the future.

My question is two-fold: 
1) Is it possible to create a "baseline" model, and re-train it using a slightly different environment? 
2) Would this workflow work? Do you have an examples of similiar workflows?

**Comment by ericl** [comment]
So one constraint of the gym env spaces is that the observation has to be a fixed size. This makes handling a different number of agents a bit difficult, though you could potentially still do it by introducing padding up to some max number of agents. You would have to change your network model to handle the padding and dynamic number of agents though via e.g., pooling.

Other than that, I think the proposed fine-tuning workflow sounds pretty good.

**Comment by marclipoff** [comment]
That makes sense. Do you have any examples or snippets of schemes that implement that type of network model -- ie, handling padding or dynamic number of agents? My initial thought is to use a max pooling layer.
