### ISSUE TITLE
[tune] BOHB failing to load checkpoint

### ISSUE THREAD

**Issue by Michiel29** [ray-project/ray#5501]
OS: Linux Ubuntu 16.04
Ray version: 8.03
Python version: 3.6

Issue: Since switching from async hyperband with hyperopt to BOHB, I am occasionally getting Exceptions in the assert in https://github.com/ray-project/ray/blob/master/python/ray/tune/schedulers/hyperband.py line 386. 

I have attempted to track down the cause. As far as I can ascertain, what is happening is that sometimes a trial is resumed without loading the checkpoint. This sets the time iteration to 0, which leads to a negative delta compared to the last result. 

As far as I can tell, this happens only for the very last trial in a bracket, and only sometimes. Possibly related to on_trial_result in https://github.com/ray-project/ray/blob/master/python/ray/tune/schedulers/hb_bohb.py, though I'm not certain about that. 

I am working on a minimum failing example, but that's turning out to be quite difficult, so I am wondering if the problem is obvious to either of you. 

@richardliaw @lisadunlap

**Comment by richardliaw** [comment]
What bracket size/reduction factor are you using?

Also, hm, does the pausing just not work?

**Comment by Michiel29** [comment]
Bracket size is endogenously determined, but I'm using a reduction factor of 3 and 10 epochs, leading to a 'large' bracket with 10 trials. Pausing and restoring after does work in general, it just sometimes fails for the last trial in a  bracket. It appears that in the cases where it fails, restore is not called in the ray_trial_executor, the trial does have a checkpoint. Currently verifying / tracking further upstream

**Comment by Michiel29** [comment]
Update: restore is called in the trial runner, but it's not called in the trainable, it goes straight to training the next epoch

**Comment by richardliaw** [comment]
Restore should always go through the ray_trial_executor right?

**Comment by Michiel29** [comment]
Pardon, yes, that's what I mean. It's called in ray_trial_executor, and I see trial.runner.restore_from_object.remote(value) being executed, and from that point the Trainable._save is never called and instead _train is immediately called.

**Comment by richardliaw** [comment]
Ah, can you try using
tune.util.validate_save_restore(use_object_store=True) to see if any errors
are raised?

**Comment by Michiel29** [comment]
Apologies for the delay, was OOO. I tried it and it worked without error. Also edited that script to allow for the use of GPU and no errors with that either.

**Comment by krfricke** [comment]
There's been a number of new releases since this issue was originally filed. If the problem persists, please re-open with a usable replication script, and we will try to solve the problem.
