### ISSUE TITLE
Fails to install from source in NVIDIA Jetson

### ISSUE THREAD

**Issue by blitzvb** [ray-project/ray#5512]
# System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04 / Jetpack 4.2.1
- **Ray installed from (source or binary)**:
master or 0.7.3
- **Ray version**:
- **Python version**:
3.6
- **Exact command to reproduce**:

sudo ./build.sh --python "/usr/bin/python3.6"

### Describe the problem
Fail during the build

### Source code / logs

```
ERROR: /media/goview/goview/devel/lib/ray/BUILD.bazel:124:1: in _generate_cc rule //:_node_manager_cc_grpc_grpc_codegen:
Traceback (most recent call last):
	File "/media/goview/goview/devel/lib/ray/BUILD.bazel", line 124
		_generate_cc(name = '_node_manager_cc_grpc_grpc_codegen')
	File "/home/goview/.cache/bazel/_bazel_root/0434614404a21bffca0a3d3eea6f535c/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 44, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.check_deps_sources]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
DEBUG: Rule 'com_google_googletest' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1534270723 -0700"
DEBUG: Call stack for the definition of repository 'com_google_googletest' which is a git_repository (rule definition at /home/goview/.cache/bazel/_bazel_root/0434614404a21bffca0a3d3eea6f535c/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /media/goview/goview/devel/lib/ray/bazel/ray_deps_setup.bzl:48:5
 - /media/goview/goview/devel/lib/ray/WORKSPACE:5:1
ERROR: Analysis of target '//:ray_pkg' failed; build aborted: Analysis of target '//:_node_manager_cc_grpc_grpc_codegen' failed; build aborted
```

**Comment by marsbars33** [comment]
@blitzvb Were you able to resolve this issue by any chance? I'm experiencing a similar failure when running setup.py. However, it seems to be stemming from the direct actor gRPC lib in BUILD.bazel on my end. Thanks!

**Comment by blitzvb** [comment]
No i tried many many things but I finally gave up :/

**Comment by marsbars33** [comment]
@blitzvb I managed to install it! Have you tried adding the following to the build config section in ray/.bazelrc?
`build --incompatible_depset_is_not_iterable=false`

**Comment by acxz** [comment]
It seems as if the newest releases have that fix: https://github.com/ray-project/ray/blob/master/.bazelrc#L37

I believe this issue can be closed.

**Comment by acxz** [comment]
@pcmoritz I think this issue can be closed.
