### ISSUE TITLE
How to disable adaptive KL-penalty in PPO ?

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#5514]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubunut 18.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.7.2
- **Python version**: 3.6.8

### Describe the problem
 Hi,

According to PPO [paper](https://arxiv.org/pdf/1707.06347.pdf), adaptive or fixed KL penalty objective function doesn't perform as good as just clipped PPO version. Therefore, I was trying to turn off KL penalty in rllib PPO also. However, I could not able to figure out what should be the configuration file for the same. One possible config file which I could think of is given. Please help.

```
    "kl_coeff": 0.0,
    "kl_target": 0.00,
```

Also, I have one more question.
1. Which parameter(s) affects the performance most in PPO. I asked this because there are tons of parameters. I tried to change many, however, it didn't improved much. 

Thanks :) .

**Comment by iceman126** [comment]
Just set `"kl_coeff": 0.0` would do. This is the way I do it.
