### ISSUE TITLE
Falling back to cludpickle when serializing a GPU torch tensor

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#5519]
```
import ray
import torch
ray.init()
a = torch.randn(5)
b = a.cuda()
ray.put(b)
```

will print

```
2019-08-23 20:39:14,208	WARNING worker.py:436 -- WARNING: Serializing the class <class 'torch.Tensor'> failed, falling back to cloudpickle.
```

**Comment by pcmoritz** [comment]
Oddly enough, this seems to be working (with the same definitions as above):

```
import pyarrow
context = list(ray.worker.global_worker.serialization_context_map.values())[0]
pyarrow.serialize(b, context=context)
```

**Comment by pcmoritz** [comment]
This error is eaten up by the following try/catch block:
```
https://github.com/ray-project/ray/blob/master/python/ray/worker.py#L426
```

**Comment by pcmoritz** [comment]
attempt for workaround: https://github.com/ray-project/ray/pull/5521

**Comment by robertnishihara** [comment]
@dhroth suggested that we just raise an error and tell people to call `.cpu()` on the tensor. I think this makes sense as it's not clear what the expected behavior is. E.g.,should the deserialized tensor live in CPU or GPU memory? What if the worker that deserializes the tensor doesn't have access to a GPU? Etc.

**Comment by Mmdixon** [comment]
Is there a way to separate these two cases?
I.e. one where GPU memory doesn't need to be copied to CPU memory via GPU IPC shared memory.
Two, the other case where the processes don't share a GPU so it will have to be shared over the CPU.

The idea is coming from how [torch.multiprocessing](https://pytorch.org/docs/stable/multiprocessing.html) handles serializing tensors and cuda tensors.
