### ISSUE TITLE
Numpy double_scalars and Mean of empty slice warnings in experimental.sgd

### ISSUE THREAD

**Issue by arunesh-mittal** [ray-project/ray#5520]
### System information

- **OS Platform and Distribution**:

```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

- **Ray installed from (source or binary)**:
Source 

- **Ray version**:
0.8.0.dev3

- **Python version**:
Python 3.6.5 :: Anaconda, Inc.

- **Exact command to reproduce**:
https://github.com/ray-project/ray/blob/239c177fe8e10c1ca91657bd488132a8d7c57712/python/ray/experimental/sgd/examples/train_example.py#L23

### Describe the problem
Executing the example code above leads to the following numpy warnings. Was unable to track what is causing it. I tried executing run multiple times and I only get this warning the first time. But the training seems to perform the desired behavior. 

### Source code / logs
```
2019-08-23 21:02:47,423 INFO pytorch_trainer.py:73 -- Using gloo as backend.
success! 
(pid=49814) /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
(pid=49814)   out=out, **kwargs) 
(pid=49814) /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars 
(pid=49814)   ret = ret.dtype.type(ret / rcount)
 ```

**Comment by richardliaw** [comment]
Thanks; I'll take a look into this.

BTW, do you have any feedback regarding the `PytorchTrainer` API? It was recently released, and it'd be great to get any thoughts or comments or suggestions.

**Comment by arunesh-mittal** [comment]
Yes, the CPUs are for dataloading. I was trying to get PyTorchTrainable to play well with torch vision: https://github.com/pytorch/vision specifically, fasterRCNN. Took me a while to wrap my head around the core ray structure. But seems like the only thing that needs to be updated is the criterion in train/val methods in utils called by each worked.remote(). 

PyTorch `DataParallel` does not  allow for different image sizes and number of targets for object detection. But `DistributedDataParallel1 does. So the distributed train/tune is super useful! :) 

The updated docs regarding best practices is very useful for writing dataloaders. Will probably spend some more in a couple of weeks to get fasterRCNN working with Tune.

**Comment by layssi** [comment]
Same issue:
Python version:
Python 3.6.5 :: Anaconda, Inc.

Ray Build version: 
ray-0.8.0.dev6-cp36-cp36m
To duplicate: 

rllib train \
    --run=PG \
    --env=CartPole-v0 \
    --config='{"output": "/tmp/cartpole-out", "output_max_file_size": 5000000}' \
    --stop='{"timesteps_total": 100000}'

rllib train \
    --run=DQN \
    --env=CartPole-v0 \
    --config='{
        "input": "/tmp/cartpole-out",
        "input_evaluation": [],
        "exploration_final_eps": 0,
        "exploration_fraction": 0}'

**Comment by devinbarry** [comment]
Same issue:
Python version:
Python 3.7.5 (Conda)
ray==0.8.0 (Installed via pip)

I have had this issue on several environments, but the example from @layssi works perfectly to show it:

```
rllib train --run=DQN --env=CartPole-v0 --config='{"input": "/tmp/cartpole-out", "input_evaluation": [], "exploration_final_eps": 0, "exploration_fraction": 0}'
```

**Comment by 123mitnik** [comment]
Same issue in several environments 
Python version:
Python 3.6.5 :: Anaconda, Inc.

Ray Build version:
ray-0.8.0.dev6-cp36-cp36m

**Comment by richardliaw** [comment]
This should be fixed for RaySGD but not for RLlib.

**Comment by richardliaw** [comment]
Closing this for now. If this is still an issue, please reopen a new issue and *be sure to include the specific Ray library (rllib, raysgd, etc) in the title*.
