### ISSUE TITLE
Cannot serialize numpy arrays with negative strides

### ISSUE THREAD

**Issue by YutingZhang** [ray-project/ray#5531]
- **OS Platform and Distribution**:  Ubuntu 16.04
- **Ray installed from**: pip
- **Ray version**: 0.7.3
- **Python version**: 3.6.6
- **Exact command to reproduce**: 

```python
import numpy as np
a=np.zeros([500,600,3])
b=a[:,:,::-1]
```

Then array `b` cannot be serialized because of the negative stride. 

This is actually a problem of Apache Arrow. I have submitted a ticket there, but not sure how promptly it could be resolved. I am thinking if ray can provide a way to workaround this (e.g., do `np.array(b, copy=True)` if a negative stride is used). 

This link to the Arrow's ticket.
https://issues.apache.org/jira/projects/ARROW/issues/ARROW-6349

**Comment by pcmoritz** [comment]
This should be fixed now that we use cloudpickle for serialization!
