### ISSUE TITLE
[tune] Unique trial identifier

### ISSUE THREAD

**Issue by bask0** [ray-project/ray#5535]
ray version 0.7.3

I am looking for a nice solution to create and access a unique identifier (UID) inside the `ray.tune.Trainable` class that is restored when resuming the model. It needs to be present when calling `ray.tune.Trainable._setup`, also when resuming the model.

The problem I want to solve: I use [wandb](https://www.wandb.com) to monitor the model training. To restore the wandb logger, I need a UID that is accessible from within the `ray.tune.Trainable` class such that `wandb.init(..., id=UID)` appends to an existing trial. wandb is initialized and resumed in `ray.tune.Trainable._setup`, not in `ray.tune.Trainable.resume(...)`.

Is there an easy way to achieve this? So far I just came up with ugly hacks (e.g. deriving the UID from `config` passed to `ray.tune.Trainable._setup`). I am sure there are other use-cases for this.

**Comment by ericl** [comment]
Why not re-initialize wandb after restore()? Currently there is no unique id available at setup time, nor does it really make sense to add it since we don't know the id ahead of time prior to resume.

**Comment by richardliaw** [comment]
There is a unique id `Trainable._experiment_id` currently available but using it in `_setup` doesn't quite fit your bill, as Eric mentioned.

The way I would do this right now if I didn't want to modify the framework would be to do the initialization in either `_train` or `_log_result`, where you initialize the wandb logger only if you haven't initialized already..

Maybe we can expose a "before_training" hook on Trainable, but that seems a bit cumbersome?

**Comment by bask0** [comment]
Thank you both. I like the suggestion to initialize wandb in `Trainable._train`. I can reinitialize if  `Trainable._iterations_since_restore` == 0. It is still not a very "clean" solution, but should work.

Do we know if the model is initialized for the first time or resumed inside `Trainable._setup`? This would help, I could initialize wandb in `Trainable._setup` only when starting the trial, save a UID, and then resume, get the UID and reinitialize wandb.

**Comment by bask0** [comment]
> Hm, I'm not totally sure what the suggestion is, but `Trainable._setup` is called on the first time a model is created, and also when a model is resumed. It is called before `Trainable._restore`.

Yea and I wondered if we know if the function is called to create the model or to restore it, but I guess it is not. Anyway, I could solve the problem by using the above suggestion to initialize inside `Trainable._train`, thanks.
