### ISSUE TITLE
Missing Custom_Metrics in progress.csv Tune Log Dir.

### ISSUE THREAD

**Issue by mkrech** [ray-project/ray#5539]
## System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**:  binary
- **Ray version**: 0.73
- **Python version**: python 3.6

### Describe the problem
Hi,
we are using the custom_metrics variabel to store our results in on_episode_end event,
to analyse later our RL progress. 

ray 0.7.2 stores the result in the logdir in progress.csv and result.json.
ray 0.7,3 the column for custom_metrics disappear in progress.csv but in result.json it is available :).

It looks like a bug :)

Regards 
Michael

**Comment by richardliaw** [comment]
feel free to reopen if still an issue.
