### ISSUE TITLE
[Question] How to obtain the action embedding for avail_action ?

### ISSUE THREAD

**Issue by soloist96** [ray-project/ray#5540]
This is a general question about parametric action space but I think people here may know the solution. I try to embed the action but in the toy model given by rllib, the available action embedding are generated randomly in the env. Shouldn't be the embeddings learned? For example, for word2vec, it's learned from corpus.  For a more practical RL problem, how could we obtain those embeddings?  Thank you.

**Comment by ericl** [comment]
You want to go from action (0..N index) to a fixed size embedding (size M)
right? The typical way to do this is to multiply by a matrix of size (NxM),
which can be learnable. This gives you your action embeddings.

**Comment by ericl** [comment]
Yes, it should be part of your model weights and is trained via backprop?

**Comment by soloist96** [comment]
Yeah, I agree! Thanks a lot!

**Comment by nMack429** [comment]
@soloist96 Interesting discussion. Did you find an easy way of doing the suggested embedding training technique?
