### ISSUE TITLE
Progressbar (e.g. tqdm)

### ISSUE THREAD

**Issue by davidweioct** [ray-project/ray#5554]
Is there a way to integrate ray with tqdm( or other progress bar) to show the working progress? I tried by adding the progress bar in the sub-function which is decorated by @ray.remote. As expected, the progress bar re-displayed line by line with updated (pid = ***). 

Thank you so much!

**Comment by richardliaw** [comment]
Unfortunately this is not straight forward to do in the remote process; you'll have to do everything in the driver.

**Comment by alexkreidler** [comment]
Any updates on this? It'd be an awesome feature!

**Comment by richardliaw** [comment]
Ah, I didn’t see the followup. I think this shouldn’t be hard (using ray.wait). I’ll post a snippet later today or tomorrow (and feel free to ping if I forget!)

**Comment by wrosko** [comment]
Any update on your snippet @richardliaw ? Was kind of serendipitous to come across the new messages here right when they're happening.

**Comment by richardliaw** [comment]
```
import ray
import tqdm

def test():
    import time
    time.sleep(1)
    return 1

test_r = ray.remote(test)

ray.init()

def to_iterator(obj_ids):
    while obj_ids:
        done, obj_ids = ray.wait(obj_ids)
        yield ray.get(done[0])
from tqdm import tqdm

obj_ids = [test_r.remote() for i in range(100)]
for x in tqdm(to_iterator(obj_ids), total=len(obj_ids)):
    pass

obj_ids = [test_r.remote() for i in range(100)]
for x in tqdm(to_iterator(obj_ids)):
    pass
```

**Comment by wrosko** [comment]
This was very helpful, thank you and apologies for my tardy reply.

**Comment by richardliaw** [comment]
Closing this for now; seems like people like the above solution.

**Comment by alexmascension** [comment]
Hi!

I'm trying your code but it doesn't seem to work for me. I've included a function that requires some arguments just to try.

```python
@ray.remote
def test(x):
    return np.array([x**3] * x)

ray.init(ignore_reinit_error=True, num_cpus=5)

def to_iterator(obj_ids):
    while obj_ids:
        done, obj_ids = ray.wait(obj_ids)
        yield ray.get(done[0])

obj_ids = [test.remote(i) for i in range(30000)]
for x in tqdm(to_iterator(obj_ids), total=len(obj_ids)):
    pass

ray.shutdown()
```

Non-parallelized it takes nearly a minute. When I parallelize it without the bar it takes around 20s. With the bar it takes nearly two and a half minutes, so something must be wrong.

Thanks!

**Comment by richardliaw** [comment]
Interesting... Can you profile this and open a new issue?

**Comment by sgbaird** [comment]
In case anyone is looking to store all the results via a list comprehension https://stackoverflow.com/a/54564836/13697228, here is a modified version of the example from https://github.com/ray-project/ray/issues/5554#issuecomment-558397627:
```python
import ray
from tqdm import tqdm

def test():
    import time
    time.sleep(0.05)
    return 1

test_r = ray.remote(test)

ray.init()

def to_iterator(obj_ids):
    while obj_ids:
        done, obj_ids = ray.wait(obj_ids)
        yield ray.get(done[0])

obj_ids = [test_r.remote() for i in range(100)]

results = [result for result in tqdm(to_iterator(obj_ids))]
```

**Comment by steveepreston** [comment]
What is the latest trick for this?

**Comment by zschaller27** [comment]
@steveepreston This can be done by invoking a [remote tqdm Actor](https://discuss.ray.io/t/use-tqdm-ray-in-remote-tasks/11175/2).
