### ISSUE TITLE
Fix skipped Java test cases in direct actor call mode 

### ISSUE THREAD

**Issue by kfstorm** [ray-project/ray#5559]
### Describe the problem

In #5504, we added support of direct actor call in Java. However, there are cases/features not welly supported by direct actor call. I list them below and will address them later.

* If the returned object of an actor task was deleted by LRU, attempts to get the object should fail with an `OBJECT_UNRECONSTRUCTABLE` error (in Java, the `UnreconstructableException`). This is covered by Java test case `testUnreconstructableActorObject`. Currently the error is generated by raylet and in direct actor call mode raylet is not involved in actor tasks, so this error will not be put into object store and the attempts to get the object will hang.
* Cross-language calls with byte array arguments. Byte array arguments are serialized with metadata `RAW` during cross-language calls, and direct actor call only supports passing parameters by value. So metadata cannot be passed to the callee. This is covered by Java test case `testCallingPythonActor` and is addressed in #5527.
* Java test case `testActorProcessDying` hangs when tearing down test case, specificly, when destroying native core worker. The stack trace shows that the destructor of `ClientCallManager` hangs at joining the `polling_thread_` thread, and the thread is waiting for `cq_.Next` to return. This is a case we don't know the reason. However, we tried to replace direct actor call connection from gRPC to asio, and it got fixed. So the bug should be gRPC specific.

**Comment by edoakes** [comment]
@kfstorm we want to remove the non-direct-call codepath as soon as possible, but it's failing some Java tests. From what I can tell, none of the above should be a problem anymore (we fixed 1 & 3 when implementing direct calls in Python and it looks like you've fixed 2).

I think the best way forward is to remove the option for non-direct-calls from both Python and Java first and then remove the code entirely from the backend. Do you think you could make a PR that makes all actors and tasks direct call in Java?
