### ISSUE TITLE
[tune] (KeyError: 'acc'): regression task: mse / mae as metric

### ISSUE THREAD

**Issue by martsalz** [ray-project/ray#5560]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux 7
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.3
- **Python version**: Python 3.6

### Describe the problem

With Keras I wrote an neural network for a regression task based on this example (classification):

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_keras.py

The following procedure:
- Train function: neural network replaced
- Train function: metric: `mse` or `mae` specified

If the metric is `mse` or `mae` instead of `acc`, the following error message appears after execution:

self.reporter(keras_info=logs, mean_accuracy=logs["acc"])
KeyError: 'acc'

Are there other Keras examples specifically for regression tasks?

**Comment by martsalz** [comment]
Thanks. 
What does the code look like if I don't use `AsyncHyperBandScheduler` or `PopulationBasedTraining`? i.e.:

```
analysis = tune.run(train_vanilla, config=search_space, num_samples=100, resources_per_trial={
        "cpu": 2,
        "gpu": 1
    })
```

**Comment by richardliaw** [comment]
Looks fine.

**Comment by martsalz** [comment]
But where do I specify `metric="keras_info/mse"`?

**Comment by richardliaw** [comment]
It’s not needed if you aren’t using a scheduler or search algorithm. Sorry
for the confusion.

**Comment by martsalz** [comment]
If I just do the following function call (metric: mse or mae specified):

`analysis = tune.run(train_vanilla, config=search_space, num_samples=100, resources_per_trial={
        "cpu": 2,
        "gpu": 1
    })`

then the error message appears:

self.reporter(keras_info=logs, mean_accuracy=logs["acc"])
KeyError: 'acc'

Despite your suggested solution, this error message appears if I do not specify a scheduler or search algorithm.

**Comment by richardliaw** [comment]
Hm, are you using the right callback?

My above solution does not have that line.
```diff
+ self.reporter(keras_info=logs, mean_accuracy=logs.get("acc"))
- self.reporter(keras_info=logs, mean_accuracy=logs["acc"])
```

**Comment by krfricke** [comment]
The Keras callback got updated in #10509. If the issue persist, please re-open with a reproducible script, and we will try to solve the problem.
