### ISSUE TITLE
[tune] Feature request: tune.sample_from does not support callable objects. 

### ISSUE THREAD

**Issue by asford** [ray-project/ray#5567]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.2
- **Python version**: 3.2
- **Exact command to reproduce**: See below

### Describe the problem

The `tune` sample_from interface is strictly limited to function objects, such as lambdas. This serves most use cases, but there are a number of instances where it's very useful to define a callable object to yield samples. (See trivial example below.) At the moment, providing a callable object returns errors from within tune variant generation, as the non-function-based `sample_from` entries are processed in grid entries. This can be resolved by changeing the sample/grid check from a direct check for `FunctionType` (Source location: https://github.com/ray-project/ray/blob/fadfa5f30bb654a74c781eaf8396a35af3ab7760/python/ray/tune/suggest/variant_generator.py#L116) to the builtin function `callable`.

I'm not entirely clear if this is an intentional limitation, and changing this logic will likely require expansion of tune's tests and documentation to cover the new behavior. I would be happy to open a PR for this if a maintainer gives the feature a 👍.

### Source code / logs

```python

import random

import ray.tune as tune
from ray.tune.suggest.variant_generator import generate_variants

class Normal:
    def __call__(self, _config):
        return random.normalvariate(mu=0, sigma=1)


grid_config = {"grid": tune.grid_search(list(range(2)))}
sample_config = {"normal": tune.sample_from(Normal())}


print(grid_config)
print(list(generate_variants(grid_config)))

print(sample_config)
print(list(generate_variants(sample_config)))

```

Results:

```
{'grid': {'grid_search': [0, 1]}}
[('grid=0', {'grid': 0}), ('grid=1', {'grid': 1})]
{'normal': tune.sample_from(<__main__.Normal object at 0x7f08ed1d0f50>)}
Traceback (most recent call last):
  File "sample_error.py", line 19, in <module>
    print(list(generate_variants(sample_config)))
  File "/work/home/lexaf/workspace/alphabeta/.conda/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 43, in generate_variants
    for resolved_vars, spec in _generate_variants(unresolved_spec):
  File "/work/home/lexaf/workspace/alphabeta/.conda/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 123, in _generate_variants
    for resolved_spec in grid_search:
  File "/work/home/lexaf/workspace/alphabeta/.conda/lib/python3.7/site-packages/ray/tune/suggest/variant_generator.py", line 193, in _grid_search_generator
    while value_indices[-1] < len(grid_vars[-1][1]):
TypeError: object of type 'Normal' has no len()
```

**Comment by hartikainen** [comment]
I just had a case where I would've needed this feature too.
