### ISSUE TITLE
[ray] Out of memory error is raised as a less useful error

### ISSUE THREAD

**Issue by kiddyboots216** [ray-project/ray#5572]
Context: I'm putting ~10 GB in the object store at initialization in the driver and then taking them out one at a time and updating them using tasks. After everything is updated once, I start seeing errors. The total memory used on the machine seems to be increasing, but the memory used by the task itself isn't increasing so I believe maybe /dev/shm is running out of memory.
Stacktrace:
```
This worker was asked to execute a function that it does not have registered. You may have to restart Ray.
The task with ID acb1c229fc06c8950ef56a75282e6bd2 is a driver task and so the object created by ray.put could not be reconstructed.
(continues printing above error indefinitely)
```
Problem: I'm sure there's more useful information that ray could give me, like what line caused this error, but the process never exits and the printed error is not useful.

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
Can you send a patch? It might also already be fixed in master.

**Comment by kiddyboots216** [comment]
I'm using the latest ray as installed with -U [whatever latest wheel is on the install page]
Wdym by send a patch

**Comment by richardliaw** [comment]
Open a PR, push a fix?

**Comment by kiddyboots216** [comment]
I have no clue how to even begin fixing this.

**Comment by richardliaw** [comment]
As a first pass, you can raise a better error!

**Comment by kiddyboots216** [comment]
I think @ericl is correct and this has been fixed on master -however, the nightly snapshot build seems out of date.
