### ISSUE TITLE
noise parameters variables requires registration for creating custom model subclassing DDPG_model

### ISSUE THREAD

**Issue by karim174** [ray-project/ray#5573]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.3
- **Python version**:  3.7.4
- **Exact command to reproduce**: using a custom model with DDPG requires the registration of parameter noise variables where forward function is overridden due to the check in the modelcatalog get_model_v2

### Source code / logs
 `ValueError: It looks like variables {<tf.Variable 'default_policy/ddpg_model/action_net/parameter_noise_sigma:0' shape=() dtype=float32_ref>, <tf.Variable 'default_policy/ddpg_model/action_net/default_policy/ddpg_model/action_net/fully_connected/weights_noise:0' shape=(256, 400) dtype=float32_ref>, <tf.Variable 'default_policy/ddpg_model/action_net/default_policy/ddpg_model/action_net/fully_connected_1/weights_noise:0' shape=(400, 300) dtype=float32_ref>, <tf.Variable 'default_policy/ddpg_model/action_net/default_policy/ddpg_model/action_net/action_out/bias_noise:0' shape=(1,) dtype=float32_ref >, <tf.Variable 'default_policy/ddpg_model/action_net/default_policy/ddpg_model/action_net/action_out/kernel_noise:0' shape=(300, 1) dtype=float32_ref>} were created as part of <__main__.CustomDDPGModel object at 0x7f7a9919c250> but does not appear in model.variables() ({<tf.Variable 'default_policy/my_layer2/bias:0' .....`

**Comment by ericl** [comment]
Can you provide a reproduction script?

**Comment by karim174** [comment]
`
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse

import ray
from ray import tune
from ray.rllib.models import ModelCatalog
from ray.rllib.models.tf.tf_modelv2 import TFModelV2
from ray.rllib.agents.ddpg.ddpg_model import DDPGModel
from ray.rllib.utils import try_import_tf
from tensorflow import initializers
import numpy as np

tf = try_import_tf()
from tensorflow.keras.layers import Dense, Conv2D, Concatenate, Activation


class CustomDDPGModel(DDPGModel):
    """Custom model for DDPG"""


    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name, **kw):
        super(CustomDDPGModel, self).__init__(obs_space, action_space, num_outputs, model_config, name, **kw)
    
        self.inputs = tf.keras.Input(
            shape=obs_space.shape, name="states")
        x = self.inputs
        layer_1 = tf.keras.layers.Dense(
            128,
            name="my_layer1",
            activation=tf.nn.relu,
            kernel_initializer=initializers.he_normal())(x)
    
        layer_2 = tf.keras.layers.Dense(
            128,
            name="my_layer2",
            activation="relu",
            kernel_initializer=initializers.he_normal())(layer_1)
    
        layer_3 = tf.keras.layers.Dense(
            128,
            name="my_layer3",
            activation="relu",
            kernel_initializer=initializers.he_normal())(layer_2)
        print('output number', num_outputs)
        layer_out = tf.keras.layers.Dense(
            num_outputs,
            name="my_out",
            activation="relu",
            kernel_initializer=initializers.he_normal())(layer_3)
        self.base_model = tf.keras.Model(self.inputs, layer_out)
        self.register_variables(self.base_model.variables)
    
        
    # Implement the core forward method
    def forward(self, input_dict, state, seq_lens):
        model_out = self.base_model(input_dict["obs"])
        return model_out, state


if __name__ == "__main__":
    ModelCatalog.register_custom_model("custom_plain_model", CustomDDPGModel)
    ray.init()
    tune.run(
        "DDPG",
        stop={"episode_reward_mean": -5},
        config={
            "env": "MountainCarContinuous-v0",
            "parameter_noise": True,
            "batch_mode": 'complete_episodes',
            "log_level":"DEBUG",
            "num_gpus": 0,
            "model": {
                "custom_model": "custom_plain_model"
            }
        })
`

**Comment by ericl** [comment]
Thanks, I think https://github.com/ray-project/ray/pull/5581 should fix it

**Comment by karim174** [comment]
you are welcome Eric
