### ISSUE TITLE
[ray] Ray is deleting objects that it shouldn't be deleting

### ISSUE THREAD

**Issue by kiddyboots216** [ray-project/ray#5586]
Addresses #5572 
OS: Steropes
Python: 3.7
Ray: 0.7.4 (most up-to-date as per Richard's link in #ray-on-prem)
Code to reproduce:
```
import ray
import time
ray.init(object_store_memory=int(1e8))
import torch
from collections import Counter
import numpy as np
n_clients = 100
n_clients_to_select = 4
@ray.remote(num_gpus=1)
def test(big_vec):
    return big_vec+1
x = ray.put(torch.randn(int(1e5)))
data = [x for _ in range(n_clients)]
start = 0
while True:
    #indices = np.random.choice(n_clients, n_clients_to_select, replace=False)
    indices = np.arange(start % n_clients, (start + n_clients_to_select) % n_clients)
    new_data = ray.get([test.remote(data[idx]) for idx in indices])
    for i, idx in enumerate(indices):
        data[idx] = new_data[i]
    start += 4


    obj_store = ray.objects()
    c = Counter()
    for objid, info in obj_store.items():
        if "DataSize" in info:
            c[info["DataSize"]] += 1
        else:
            c["nosize"] += 1
    print(c)
    print(f"Object store size: {sum([val['DataSize'] if 'DataSize' in val else 0 for key, val in obj_store.items()])}")
    print()
```
Every time test.remote() is called, big_vec sticks around in the object_store. Even though we can never access or use it again. This eventually fills up the object_store, so Ray starts evicting items according to LRU.
When the line which sets ```indices``` is iterating through the array in sequential order, no errors occur; when too many of the big_vecs fill the object_store, ones which were used a while ago are evicted and because we never refer to them, we're fine.
However! In any usecase where random selection of these tensors is necessary, i.e. if the line which sets indices is setting it to a random selection of tensors, then we do observe an error:
```
Traceback (most recent call last):
  File "minimal_failure.py", line 18, in <module>
    new_data = ray.get([test.remote(data[idx]) for idx in indices])
  File "/data/ashwineep/anaconda3/envs/comm-efficient/lib/python3.7/site-packages/ray/worker.py", line 2332, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=2584, host=steropes)
ray.exceptions.UnreconstructableError: Object ffffffffffffffffffff01000000008001000000 is lost (either evicted or explicitly deleted) and cannot be reconstructed.

2019-08-29 21:58:13,361 ERROR worker.py:1791 -- The task with ID ffffffffffffffffffff01000000 is a driver task and so the object created by ray.put could not be reconstructed.
```
This happens because with randomness, we may not select one of these datapoints for a very long time, so it and every object ID in its lineage get evicted, forcing Ray to attempt to reconstruct from the ray.put() which is in the driver, which fails.

We can fix this easily by making x the tensor itself and not the object ID of the tensor. However, when doing this, the time taken to do each iteration steadily increases, because of the above phenomenon.

**Comment by kiddyboots216** [comment]
@richardliaw @ericl tracked down the error which causes the 'unhelpful' error. I think the fixes are; 1) raise a memory error instead of this so the user understands that they're filling up the object store 2) don't keep things around which are passed in as parameters if there's no reference to them any longer 3) don't evict anything which still has a reference -the error occurs because Ray is evicting things which definitely still have a reference in favor of keeping objects around which were more recently used but no longer have a reference available in the code.

**Comment by richardliaw** [comment]
cc @stephanie-wang

**Comment by ericl** [comment]
Can you try this fix: https://github.com/ray-project/ray/pull/5590/files

**Comment by kiddyboots216** [comment]
@ericl This doesn't fix the issue. The objects that I believe should be evicted don't have any references to them remaining. They are large tensors which were placed into the object store becaused they were passed into remote functions as arguments, and then they never get evicted, although they're never going to be used again, so Ray starts evicting objects which *do* have references to them remaining.

**Comment by ericl** [comment]
What you're describing is much harder to implement; however the put ref counting does fix at least your test case.

**Comment by kiddyboots216** [comment]
@ericl There's only 1 ray.put() in this test case, and whether I pass weakref=True or weakref=False, the test case still fails. With weakref=True it fails almost immediately, and with weakref=False it takes a bit longer, but still fails either way. Not sure how I'm supposed to use the code you added in the PR to fix the test case?

**Comment by stephanie-wang** [comment]
I tried running your script (as is, but without `num_gpus=1` in the decorator) on master and didn't see any errors. Are you still getting the same error message as before, for both weakref=True and weakref=False?

**Comment by kiddyboots216** [comment]
Nope, it works on master as-is! Not sure why it wasn't working on the version of master right after the PR was merged.
