### ISSUE TITLE
[rllib] ES Agent not compatible with RLlib.rollout

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#5588]
I found that ES agent not fully compatible with rllib.rollout.

## compute_action

Rllib assume all agents have `compute_action` which take
```
a_action, _, a_info = agent.compute_action(
    a_obs,
    prev_action=prev_actions[agent_id],
    prev_reward=prev_rewards[agent_id],
    policy_id=policy_id,
    full_fetch=True
)
```
as input.

While ES agent only take one argument.

```
    def compute_action(self, observation):
        return self.policy.compute(observation, update=False)[0]
```

So therefore the same codes in rollout cannot be used to run ES agent.

## initial action, state and others

`rollout` will build some factory function to generate the initial action,

like:

```
    if hasattr(agent, "workers"):
        ......
        policy_map = agent.workers.local_worker().policy_map
        state_init = {p: m.get_initial_state() for p, m in policy_map.items()}
        use_lstm = {p: len(s) > 0 for p, s in state_init.items()}
        action_init = {
            p: m.action_space.sample()
            for p, m in policy_map.items()
        }
```

However, since ES Agent do not have "workers" attributes, the `action_init, state_init` will not be defined, which lead to error in the other codes.

## local mode

If running on local mode, error happens:

```
  File "/xxx/anaconda3/envs/uber/lib/python3.6/site-packages/ray/rllib/agents/es/es.py", line 61, in __init__
    assert self.noise.dtype == np.float32
AttributeError: 'LocalModeObjectID' object has no attribute 'dtype'
```

**Comment by ericl** [comment]
Mind making a fix? I think it would work to just avoid those arguments for ES and ARS
