### ISSUE TITLE
[ray] numpy arrays become read-only, and no copy on write (after ray.get())

### ISSUE THREAD

**Issue by seb314** [ray-project/ray#5592]
System information
Linux Ubuntu 18.04.3 LTS
ray istalled from binary binary (pip)
ray==0.7.3
Python 3.6.7

- **Exact command to reproduce**:
`
import ray
import numpy as np
ray.init()
a = np.array([1,2])
a2 = ray.get(ray.put(a))
a2[0] = 5

**prints:**
ValueError                                Traceback (most recent call last)
<ipython-input-1-4784730ec72f> in <module>
      4 a = np.array([1,2])
      5 a2 = ray.get(ray.put(a))
----> 6 a2[0] = 3

ValueError: assignment destination is read-only
`

### Describe the problem
numpy objects are (intentionally) read-only when retrieved from the object store via ray.get, as described [in the documentation](https://ray.readthedocs.io/en/latest/object-store.html?highlight=serialization#serialization-numpy-arrays).
However, writeable copies should be created when a write access is attempted, and according to the documentation, ray does this.
However, a write attempt fails (see example above).

**Comment by richardliaw** [comment]
cc @pcmoritz?

**Comment by pcmoritz** [comment]
While this behavior might be desirable, this is not how it works. Objects obtained with ray.get are read-only. If the user wants to modify it, they need to create a copy themselves. The documentation should be fixed here.

**Comment by pcmoritz** [comment]
It would be fairly easy to implement copy on write by using the `MAP_PRIVATE` flag for mmap, but we should have a discussion before we do this. It might be confusing to users as they may expect that modifying the object will modify it globally.

**Comment by richardliaw** [comment]
Fixed in #5610

**Comment by seb314** [comment]
Ok. 
One issue with *not* doing such a copy-on-write is that this breaks the transparent behaviour of put/get with (possibly nested) objects: Any object that internally relies on mutable numpy arrays will break when passed to a ray remote-function or actor. 
In performance-critical cases, custom serialization of the object's internals may be required anyway, but shouldn't the default be compatible with code that is not customized for use with ray when possible?

**Comment by brukau** [comment]
it seems like this behavior is not the same anymore since ray==0.7.7, i.e. running the same code in 0.7.6 and 0.7.7 returns different results

System information
Linux Ubuntu 18.04.3 LTS
ray istalled from binary binary (pip)
ray==0.7.7
Python 3.7.5
