### ISSUE TITLE
[rllib] How to obtain the neural network within the trained DQN agent?

### ISSUE THREAD

**Issue by asylin2018** [ray-project/ray#5595]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 18.3
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5.3
- **Python version**: 3.6.5
- **Exact command to reproduce**:

### Describe the problem

I have already trained a DQN agent and have saved the .tune_metadata and .extra_data files on the disk. I can restore the DQN agent with these files. Is there a way that I can get the neural network model instead of the DQNAgent object, as I need to perform some analysis on the trained neural network within the DQN agent?

Also, I notice that the DQNAgent object has the get_weights() method and I can get the graph by DQNAgent.local_evaluator.tf_sess.graph. I am wondering if I can populate the weights into a neural network. Thank you!

**Comment by ericl** [comment]
Please upgrade to a newer ray version and use the APIs here: https://ray.readthedocs.io/en/latest/rllib-training.html#accessing-policy-state

For example, `trainer.get_policy().model`

**Comment by asylin2018** [comment]
Thanks for replying! I am able to obtain the model object now. However, it is a 'ModelV1Wrapper_as_DistributionalQModel' object. Is there a way to convert it to keras or tf model object, as I would like to perform some model transparency analysis with some packages which are compatible with keras or tf model only? Thanks a lot!

**Comment by ericl** [comment]
Ah, I think in the nightlies it will be a modelv2 that actually has an
embedded Keras model (you can inspect the code to get it). Or, you can
define a custom model that supports whatever methods you want.
