### ISSUE TITLE
PBT runs out of memory

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#5622]
This happens in the long running stress test pbt.py:

<img width="1273" alt="Screen Shot 2019-09-03 at 10 07 46 AM" src="https://user-images.githubusercontent.com/113316/64193839-85346180-ce32-11e9-9f10-4ba30b09a2a8.png">

**Comment by pcmoritz** [comment]
Heap profile:
```

**Comment by pcmoritz** [comment]
This was introduced in https://github.com/ray-project/ray/pull/5547

**Comment by richardliaw** [comment]
Should be fixed by #5629

**Comment by pcmoritz** [comment]
fixed by #5629
