### ISSUE TITLE
Unknown trainable: PPO

### ISSUE THREAD

**Issue by veredhalperin** [ray-project/ray#5636]
hi
when I run
trials = run_experiments({
    flow_params["exp_tag"]: {
        "run": alg_run,
        "env": gym_name,
        "config": {
            **config
        },
        "checkpoint_freq": 1,  # number of iterations between checkpoints
        "checkpoint_at_end": True,  # generate a checkpoint at the end
        "max_failures": 999,
        "stop": {  # stopping conditions
            "training_iteration": 1,  # number of iterations to stop after
        },
    },
})

with alg_run='PPO' I get a Unknown trainable: PPO error (same thing  happend with DQN)
~/ray/python/ray/tune/trial.py in _registration_check(cls, trainable_name)
    207             from ray import rllib  # noqa: F401
    208             if not has_trainable(trainable_name):
--> 209                 raise TuneError("Unknown trainable: " + trainable_name)

**Comment by guyue5** [comment]
I also got the problem, have you solved?

**Comment by veredhalperin** [comment]
No

בתאריך יום ד׳, 30 באוק׳ 2019, 15:35, מאת guyue5 ‏<notifications@github.com>:

**Comment by richardliaw** [comment]
Can you try `from ray import rllib` before `run_experiments`?

**Comment by veredhalperin** [comment]
Hi, sorry didn't work in the last month and now I came back
I run  from ray import  rllib, it still throw the same expection after

בתאריך יום ד׳, 30 באוק׳ 2019, 20:21, מאת Richard Liaw ‏<
notifications@github.com>:
