### ISSUE TITLE
[rllib] DDPG training of tuned examples episode mean rewards decrease suddenly

### ISSUE THREAD

**Issue by kifarid** [ray-project/ray#5638]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.3
- **Python version**: 3.7.4
- **Exact command to reproduce**:  rllib train -f pendulum-td3.yaml

### Describe the problem

I noticed that some of the tuned examples reach the expected values or become close to it but suddenly learning curves produce unexpected results after some number of steps  is that normal ?
### Source code / logs

![image](https://user-images.githubusercontent.com/23289286/64310643-28a38480-cfa1-11e9-9121-a7afb15b9ea4.png)

**Comment by ericl** [comment]
There was an exploding q values bug in DDPG in 0.7.3. This was just reverted in master to fix it. So master or 0.7.2. should work.
