### ISSUE TITLE
[rllib] Figure out why DDPG refactor caused exploding Q values, undo revert

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5639]
See  https://github.com/ray-project/ray/pull/5626 -- the refactored DDPG somehow doesn't work on certain tasks such as MountainCar.

**Comment by batzner** [comment]
Hi @ericl, is the 0.7.2 version possibly affected by this issue?

**Comment by ericl** [comment]
No, that should work fine. You can check the code wasn't affected by the
reverted commit.

**Comment by batzner** [comment]
Thank you for your fast response!
