### ISSUE TITLE
[rllib] Model Variable Management

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#5640]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: around 073
- **Python version**: 3.6
- **Exact command to reproduce**: `python examples/custom_keras_model.py --run DQN`

### Describe the problem

I ran the command and got:

> ValueError: It looks like variables {<tf.Variable 'default_policy/q_func/action_value/hidden_0/kernel:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/state_value/dense/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/state_value/dense_1/kernel:0' shape=(256, 1) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/action_value/dense/kernel:0' shape=(256, 2) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/state_value/dense/kernel:0' shape=(256, 256) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/action_value/hidden_0/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/state_value/dense_1/bias:0' shape=(1,) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/action_value/dense/bias:0' shape=(2,) dtype=float32_ref>} were created as part of <__main__.MyKerasQModel object at 0x7f0279bfaef0> but does not appear in model.variables() ({<tf.Variable 'default_policy/my_out/kernel:0' shape=(128, 256) dtype=float32>, <tf.Variable 'default_policy/my_layer1/bias:0' shape=(128,) dtype=float32>, <tf.Variable 'default_policy/my_layer1/kernel:0' shape=(4, 128) dtype=float32>, <tf.Variable 'default_policy/my_out/bias:0' shape=(256,) dtype=float32>}). Did you forget to call model.register_variables() on the variables in question?

If I add `hiddens: []` in my configuration, the unregistered vars would be less:

>ValueError: It looks like variables {<tf.Variable 'default_policy/q_func/state_value/dense/bias:0' shape=(1,) dtype=float32_ref>, <tf.Variable 'default_policy/q_func/state_value/dense/kernel:0' shape=(2, 1) dtype=float32_ref>} were created as part of <__main__.MyKerasQModel object at 0x7f2bb209bd68> but does not appear in model.variables() ({<tf.Variable 'default_policy/my_layer1/kernel:0' shape=(4, 128) dtype=float32>, <tf.Variable 'default_policy/my_out/kernel:0' shape=(128, 2) dtype=float32>, <tf.Variable 'default_policy/my_layer1/bias:0' shape=(128,) dtype=float32>, <tf.Variable 'default_policy/my_out/bias:0' shape=(2,) dtype=float32>}). Did you forget to call model.register_variables() on the variables in question?

If I further add `dueling: False` in my configuration, the issue would be resolved.
Without `dueling: False`, I found that this [line](https://github.com/ray-project/ray/blob/releases/0.7.3/python/ray/rllib/agents/dqn/distributional_q_model.py#L150) would be executed. However, [here](https://github.com/ray-project/ray/blob/releases/0.7.3/python/ray/rllib/agents/dqn/distributional_q_model.py#L172), the `self.state_value_head.variables` is still an empty list.

I have no idea that it is keras mechanism that vars defined in Lambda would not be instantiated immediately or sth wrong made by myself. Could you give me a hand?

**Comment by ericl** [comment]
What tensorflow version? I think there is some issue with variable scopes that is fixed in 1.14. (The example runs fine in jenkins on TF 1.14) 

I would also try on latest, we fixed some bugs with the handling there.

**Comment by joneswong** [comment]
I am using TF1.12

**Comment by joneswong** [comment]
I just changed to TF1.14 and then the issue disappeared...It seems that they fixed the var management issue of LAMBDA.
