### ISSUE TITLE
[tune] Create an advanced walkthrough example with PBT and Trainable API

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#5660]
The Trainable API should be surfaced more, since more advanced algorithms depend on it. 

This walkthrough should show how to use the Trainable API and cover PBT integration. Consider also developing this on a notebook.

**Comment by hhbyyh** [comment]
I haven't found ongoing work related to this. @richardliaw Do you mind if I give it a try.

**Comment by richardliaw** [comment]
Yes! Here's a notebook you can start with -
https://github.com/ray-project/tutorial/blob/master/tune_exercises/exercise_3_pbt.ipynb
It'd
be great to get this into a RST (or sphinx-gallery) format so that we can
show it on the documentation page.

Feel free to reach out on slack if you have any questions! More than
happy to help.

**Comment by hhbyyh** [comment]
Thanks for the reference. The notebook is pretty neat by itself. I'll prepare a corresponding rst. 

Can I know what's the recommended place for the walkthrough, an independent page or a new section like https://ray.readthedocs.io/en/latest/tune-tutorial.html#early-stopping-with-asha? Thanks!

**Comment by richardliaw** [comment]
An independent page like tune-advanced-tutorial.html would be good.

Hopefully, we'll make the sidebar less cluttered soon :)

**Comment by hhbyyh** [comment]
@richardliaw I almost finished the draft, but met some issues during the development. I listed some of them (https://github.com/ray-project/ray/issues/6237 and https://github.com/ray-project/ray/issues/6239) and probably will report more later. I'm interested in some of the issues and will try to fix if possible. 

Shall I include DCGAN (or part of it) in the walk through?

**Comment by richardliaw** [comment]
Yep! A DCGAN inclusion in example would be fine!

**Comment by hhbyyh** [comment]
posted the dcgan code in https://github.com/hhbyyh/ray_test/blob/master/dcgan_pbt.ipynb. Still working on further tuning and visualization. Appreciate early feedback and suggestions.

**Comment by richardliaw** [comment]
Looks good! Do you have access to multiple GPUs (or even a cluster)? Maybe it actually makes sense to extend the Ray Distributed PyTorch API to make this easier for you/reduce boilerplate.

**Comment by richardliaw** [comment]
Done with #6400
