### ISSUE TITLE
How to parser the results of PopulationBasedTraining ?

### ISSUE THREAD

**Issue by yichuan9527** [ray-project/ray#5661]
Hellow, I run the tune example `pbt_example.py`. I get three results files `pbt_global.txtx`, `pbt_policy_1.txt`, `pbt_policy_2.txt` and `pbt_policy_3.txt`. For example, in `pbt_policy_1.txt`:
```
["2_decay=1e-06", "1_decay=1e-06", 19, 16, {"epochs": 1, "batch_size": 32, "lr": 0.0001, "decay": 1e-06, "dropout": 0.5}, {"epochs": 1, "batch_size": 32, "lr": 0.0001, "decay": 1e-06, "dropout": 0.6}]
["1_decay=1e-06", "2_decay=1e-06", 169, 176, {"epochs": 1, "batch_size": 32, "lr": 0.0001, "decay": 1e-06, "dropout": 0.5}, {"epochs": 1, "batch_size": 32, "lr": 0.0001, "decay": 1e-06, "dropout": 0.6}]
```
What does each item denote ? And how I pasrer them and reconstruct the searching schedule?

**Comment by kiddyboots216** [comment]
Hi, please see https://github.com/ray-project/ray/issues/5489#issuecomment-523829610
