### ISSUE TITLE
Worker count on rllib with on the ray dashboard

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#5670]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Ray installed from (source or binary)**: 
- **Ray version**:
- **Python version**: 3.7.2
- **Exact command to reproduce**:

### Describe the problem

When running rllib the worker processes have names starting with `ray_RolloutWorker`:

```
$ ps faux | grep `ray_RolloutWorker:`
ubuntu   12646 79.6  0.5 27711376 1120804 ?    Rl   16:44   2:09  \_ ray_RolloutWorker:sample_with_count()
ubuntu   12647 83.1  0.5 27641916 1147220 ?    Rl   16:44   2:15  \_ ray_RolloutWorker:sample_with_count()
ubuntu   12652 80.6  0.6 27896544 1245764 ?    Rl   16:44   2:11  \_ ray_RolloutWorker:sample_with_count()
ubuntu   12657 82.3  0.5 27775760 1132308 ?    Rl   16:44   2:14  \_ ray_RolloutWorker:sample_with_count()
```

...however the code for the ray dashboard only "sees" worker processes whose name starts with `"ray_worker"`. See `running_worker` in `python/ray/reporter.py`:

```
def running_worker(s):
    if "ray_worker" not in s:
        return False

    if s == "ray_worker":
        return False

    return True
```

 I could just modify this function to include `"ray_RolloutWorker"`, however it would be good to add something more robust.  Is there a robust way to identify ray worker processes?

**Comment by ericl** [comment]
How about "ray_*"? Otherwise, perhaps you could look and see if the parent process is the raylet, though that could be more involved.

**Comment by mitchellstern** [comment]
@mattearllongshot This should be fixed in the recent dashboard update (https://github.com/ray-project/ray/pull/5730).

See https://github.com/ray-project/ray/pull/5730/files#diff-bc889dcbe0d5fa415e6bf5a3da09f485R51.

We're now checking for processes whose names start with `"ray_"`  in order to detect workers and actors to display in the dashboard.
