### ISSUE TITLE
How come HyperOpt example does not reach best solution?

### ISSUE THREAD

**Issue by ilan-seebo** [ray-project/ray#5691]

**Comment by ilan-seebo** [comment]
**System information**
OS Platform and Distribution: macOS 10.14.6
Ray installed from (source or binary):binary
Ray version: 0.7.3
Python version: 3.7.2
Exact command to reproduce:
python /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ray/tune/examples/hyperopt_example.py
**Describe the problem:**
I am running the example for hyperOpt in: ray/tune/examples/hyperopt_example.py
But the best result, even after 1000 iterations does not reach the best solution for mean_loss=0, 
While trying to run this simple function in HyperOpt only, without tune, get solved in less than 10 iterations.
**Source code**
https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperopt_example.py

**logs**
TERMINATED trials:
 - easy_objective_1_activation=tanh,height=2.0,iterations=100,width=4.0:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78431], 2 s, 100 iter, 99 ts, 143 loss
 - easy_objective_2_activation=relu,height=2.0,iterations=100,width=1.0:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78426], 2 s, 100 iter, 99 ts, 142 loss
 - easy_objective_3_activation=tanh,height=98.986,iterations=100,width=8.4335:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78427], 0 s, 10 iter, 9 ts, 7.22e+03 loss
 - easy_objective_4_activation=relu,height=-20.559,iterations=100,width=7.8831:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78429], 0 s, 10 iter, 9 ts, 1.19e+03 loss
 - easy_objective_5_activation=relu,height=32.214,iterations=100,width=16.33:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78435], 0 s, 10 iter, 9 ts, 318 loss
 - easy_objective_6_activation=tanh,height=73.656,iterations=100,width=9.8074:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78434], 0 s, 10 iter, 9 ts, 3.55e+03 loss
 - easy_objective_7_activation=tanh,height=44.26,iterations=100,width=1.0668:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78432], 0 s, 10 iter, 9 ts, 914 loss
 - easy_objective_8_activation=relu,height=-32.983,iterations=100,width=7.9468:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78433], 0 s, 10 iter, 9 ts, 2.2e+03 loss
 - easy_objective_9_activation=relu,height=-49.28,iterations=100,width=19.828:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78425], 0 s, 10 iter, 9 ts, 3.99e+03 loss
 - easy_objective_10_activation=relu,height=98.217,iterations=100,width=14.884:	TERMINATED, [1 CPUs, 0 GPUs], [pid=78430], 0 s, 10 iter, 9 ts, 7.08e+03 loss
...

**Comment by ilan-seebo** [comment]
Thank you very much for taking the time to reply, but I still do not understand something.
In my example, when I use max_evals=1000, the run takes about 1sec, on single core and reaches a good score,
Trying to do the same with tune:
With 1 sample and 1000 iterations I get a very bad score
With 1000 samples and 1 iterations, the run takes at least few minutes (with  max_concurrent=8)

I am sorry for sounding picky, but we really want to use Tune in our system, we already use Ray and it working great, but we currently feel we cannot get Tune to work well enough.

**Comment by richardliaw** [comment]
This function is a bad example, since Tune/Ray spawns a new process for
each evaluation. By default, Tune targets heavier workloads like DL/RL.

If you really want to optimize a function like the example, one way to work
around this, because the function evaluation is so fast, is to set
ray.init(local_mode=True) before tune.run

1 sample + 1000 iteration only actually samples 1 configuration (no
sequential optimization). Iteration is in the function.

Let me know if you have any questions.

**Comment by ilan-seebo** [comment]
Yeah of course the function we really need is much more complected, real ML with hounders of features. Just wanted to make sure I understand your simple example before refactoring my code. It is much clearer now thanks to you,  the part with the inner 'for' loop on the iterations which only work with the Async scheduler was very confusing.
