### ISSUE TITLE
Poor auto-scaling

### ISSUE THREAD

**Issue by wjaskowski** [ray-project/ray#5696]
### System information
- **Ray version**: 0.7.4

### Describe the problem
The auto-scaling mechanism seems quite unintuitive for me. I spent a considerable amount of time to understand it, so let me share my troubles here. Take an example. I have a head node with 2 cpus and 20 computing nodes with 8 cpus each and 50 long tasks to be computed, each using 8 cpus. If I set to have initially 3 workers then with autoscalling fraction of 0.8 no new nodes will be ever spawned for me. Why? 

This is because the NumNodesUsed will be always 3.0 and the code reads:
```
ideal_num_nodes = int(np.ceil(cur_used / float(target_frac)))
ideal_num_workers = ideal_num_nodes - 1  # subtract 1 for head node
```
ceil(3.0 / 0.8 - 1) = 3.

So, *regardless* of the number of jobs waiting for completion, I will be stuck with only 3 computational nodes. 

I am not sure what should be a solution but I find that quite unfortunate. If I had a slurm here, the slurm would spawn as many nodes as it could to handle concurrently as many tasks as possible.

EDIT: Actually, the `-1` for the head node should take most of the blame since it is implicitly assumed that the head node is fully used and has the same capacity as the working nodes. Actually, I would love to have an option to exclude the head node from computations at all. 
But this is a more general problem: in general, if jobs cannot fit the currently running nodes but the nodes are not fully utilized, a similar situation could happen.

**Comment by ericl** [comment]
The latest wheels should be updated in a few hours... mind trying out the fix?

**Comment by wjaskowski** [comment]
> Thanks for reporting. I think https://github.com/ray-project/ray/pull/5702/files should fix the issue in the general case. If any node in the cluster ends up with a queue of pending tasks, the autoscaler will now assume all partially loaded nodes are 100% utilized, plus one for the head node.

Does that mean that if I set `target_frac` to `0.999`, and require `{gpu: 0.9}` for each job then, in practice:
1) every time a new job will be in the queue, a new instance is get launched and
2) at the same time, new nodes won't be created if on every worker there is a job running?

I run a bunch of long jobs using ray tune and spot AWS instances. I would like to make sure that:
1) at any time there is enough computational nodes to handle the jobs (autoscaling), also in a case that some workers (spot instances) got randomly terminated.
2) no idle nodes are present (I don't want to pay for them)

**Comment by wjaskowski** [comment]
@ericl Any comments on this? I think this is quite a common scenario.

**Comment by thavlik** [comment]
I am having issues scaling up as well. Not sure if it's related to this, but this is the most relevant issue I could find.
