### ISSUE TITLE
try_import_tf should not live in rllib

### ISSUE THREAD

**Issue by mehmetbasbug** [ray-project/ray#5698]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Debian 10
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.3
- **Python version**: 3.7
- **Exact command to reproduce**: python -c "from ray.experimental.tf_utils import TensorFlowVariables"

### Describe the problem
try_import_tf should not live in rllib. There are ray users who are not using rllib. A simple solution is to move try_import_tf into ray.experimental.tf_utils.

Related to this issue, please get rid of cv2 dependency. It does not make sense to have such a heavy dependency just to scale images. There are rllib users who are not working with image data.

### Source code / logs
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/apps/anaconda3/lib/python3.7/site-packages/ray/experimental/tf_utils.py", line 8, in <module>
    from ray.rllib.utils import try_import_tf
  File "/opt/apps/anaconda3/lib/python3.7/site-packages/ray/rllib/__init__.py", line 12, in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
  File "/opt/apps/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.rollout_worker import RolloutWorker
  File "/opt/apps/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 12, in <module>
    from ray.rllib.env.atari_wrappers import wrap_deepmind, is_atari
  File "/opt/apps/anaconda3/lib/python3.7/site-packages/ray/rllib/env/atari_wrappers.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by karthikbhat13** [comment]
Hey, can I take this up?

**Comment by richardliaw** [comment]
@karthikbhat13 sure

**Comment by hhbyyh** [comment]
@karthikbhat13 do you still plan to work on the issue? 
I'm not sure if moving `try_import_tf` to `ray.experimental.tf_utils` is the best solution, since it's adding an experimental package as the dependency of `rllib`. If `try_import_tf` is function used by multiple modules, we might consider to put it into a lower position, like `python/ray/utils.py`. Appreciate your suggestion.

**Comment by karthikbhat13** [comment]
@hhbyyh I'm not in a position to work on this at the moment. I would not mind if it is picked up by someone else. 
Thanks!

**Comment by walterddr** [comment]
Hi here. was wondering if anyone is taking this beginner task. can I try tackling this?

**Comment by hhbyyh** [comment]
@walterddr I guess you can. And it's better if you would like to share the outline about the change here, e.g. what's the new location.

**Comment by walterddr** [comment]
I think moving to `ray.experimental.tf_utils` might not be a bad idea since it is already being imported by multiple policies.

However I think you also made a good point that it is making `rllib` depending on experimental package (in fact the `tf_utils` is the only dependencies i can find within `rllib` so far). On a side note I think maybe tf_utils can be moved to a more higher level? e.g. `python/ray/tf_utils` instead?

**Comment by anooprh** [comment]
Slightly off topic.. But would it help if we add a unit test to this ?

**Comment by hhbyyh** [comment]
I guess if we have to change it, then moving try_import_tf to ray utils seems OK. The priority is not high though if we don't plan to use try_import_tf in ray core or ray tune. 

@walterddr I would check with committers before implementing it, the change is not trivial and they might have better ideas.

**Comment by walterddr** [comment]
@hhbyyh most of the items in `python/ray/utils` are very basic and supporting general ray core functionalities. there're `gcs_utils` and `cluster_utils` that are more specific to a particular aspect. so I think adding it to utils seems a bit odd. (hence I created a [proposal commit](https://github.com/walterddr/ray/commit/665697c70e0268ecc2e50c7e24344801ea6d8287) for creating a `tf_utils`)

but yes I think other committers might have better idea @ericl @richardliaw ?

@anooprh are you referring to adding tests for generic utils? I would think that to be a good idea as well

**Comment by richardliaw** [comment]
`try_import_tf` is an RLlib internal function, so users should not be using it nor should they be moving it. 

If you are trying to use Ray with TF, why not just `import tensorflow`? That should work fine too for users not using TF. 

If anyone is interested, they can work on changing the cv2 dependency, but actually I think that should be a different issue altogether.

**Comment by walterddr** [comment]
thanks for the explanation @richardliaw I will create an issue for decoupling the cv2 dependency.
