### ISSUE TITLE
Autoscaler: wait until nodes are ready?

### ISSUE THREAD

**Issue by wjaskowski** [ray-project/ray#5703]
### System information
- **Ray version**: 0.7.4

### Describe the problem
As far as I am concerned, there is currently no robust way to wait until at least one of the nodes of the autoscaled cluster is active/ready for computations (let me know if I am wrong). 

I want to do 
```ray up && ray submit script```
but `ray submit` fails with unavailable resources if none node is ready yet so maybe we need a flag like ```ray up --wait-for-workers```, which would block the command until all initial workers are up and running?

**Comment by richardliaw** [comment]
This would be nice.

As a workaround, in your script, you can call `ray.cluster_resources()` and just check if you have the right quantity ready before executing.

**Comment by wjaskowski** [comment]
Works. Thx for the hint!

**Comment by wjaskowski** [comment]
Let me close this issue since in ray 0.8dev6 the problem is resolved if you use `queue_trials=True`.
