### ISSUE TITLE
ES Agent take up all GPU memory even ray do not provide GPU for it

### ISSUE THREAD

**Issue by pengzhenghao** [ray-project/ray#5712]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Ray installed from (source or binary)**: pip install -U wheel
- **Ray version**: 0.7.4
- **Python version**: 3.6
- **Exact command to reproduce**:

```
import ray
from ray.rllib.agents.es import ESTrainer

ray.init(num_gpus=0)
ray.available_resources() -> {'object_store_memory': 263.0, 'memory': 8954.0, 'CPU': 32.0}

agent = ESTrainer(env="BipedalWalker-v2")
```

![image](https://user-images.githubusercontent.com/22206995/64937265-33f18c80-d88c-11e9-8fed-5350d053cf86.png)

### Describe the problem

This is really strange and not seen before in the previous version.

**Comment by Skylark0924** [comment]
I have the same problem

**Comment by pengzhenghao** [comment]
The truth is that, you should not use GPU at all during the training of EA!
