### ISSUE TITLE
Ray is hijacking worker's output

### ISSUE THREAD

**Issue by wjaskowski** [ray-project/ray#5718]
### System information
- **Ray version**: 0.7.4

### Describe the problem
I am using ray together with sacred (https://github.com/IDSIA/sacred/). Sacred logs my experiment results in some database. It also captures the standard output of my experiments and logs it. Unfortunately, Ray somehow interferes with the sacred standard output hijacking and a sacred experiment when executed inside a ray.remote doesn't capture any stdout anymore.

I tried `ray.init(log_to_driver=False)` however it doesn't help. Can I prevent ray from messing up with the standard output of the workers?

**Comment by richardliaw** [comment]
You can maybe forcefully reset `sys.stdout = sys.__stdout__`?

**Comment by wjaskowski** [comment]
Thanks for the hint. Eventually, I solved the problem in sacred by finding this workaround https://github.com/IDSIA/sacred/issues/195.
