### ISSUE TITLE
[Kubernetes] Build and update rayproject docker images in Travis CI

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#5728]
Build and push rayproject docker images in travis CI.

**Comment by simon-mo** [comment]
Maybe set updated builds on dockerhub.

**Comment by edoakes** [comment]
@simon-mo we're pushing commit releases now, but we need to do it for releases as well. Let's do it for the upcoming 0.8.3 release.

**Comment by simon-mo** [comment]
Closing this old issue. Thanks @ijrsvt for the great work
