### ISSUE TITLE
[Tune] Trial Checkpoint/Restore Broken?

### ISSUE THREAD

**Issue by bfortuner** [ray-project/ray#5734]
Haven't been able to resume trials since version 0.7.2. I think it has to do with how we're checkpointing. The `last_result` doesn't seem to be persisted in the checkpoint after version 0.7.2. It doesn't show up in experiment_state.json, for example.

I'm able to repro with the logging example here:
https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/logging_example.py

Setup
Python: 2.7
Linux: Ubuntu 14.01
Ray: 0.7.4 and 0.8.0.dev4 (both exhibit same behavior)

Summarized issues and logs here:
https://gist.github.com/bfortuner/3eae14b23591d726cc2e6bea6a6695e8

For both 0.7.2 and 0.8.0.dev, I did the following using the above script in the gist:

I ran 7 iterations, checkpointing every 2 iterations. I stopped the sweep, and then resumed it passing in `resume=True`. 0.7.2 restores from the checkpoint at timestep=6, while 0.8.0.dev4 starts over again from timestep=0. My `_restore()` function is never called.

**Comment by richardliaw** [comment]
Does this fail on the latest master wheels too?

**Comment by bfortuner** [comment]
Yes, just tried again on latest nightly build available here. Python2.7
https://ray.readthedocs.io/en/latest/installation.html

**Comment by richardliaw** [comment]
Ah I see what you mean; can you try setting the `tune.run(global_checkpoint_period=0, ...)`? This was done because users would complain that `tune` was too slow when trying out some very fast functions.

**Comment by bfortuner** [comment]
Ah I see now. Just saw this PR: https://github.com/ray-project/ray/pull/4859. Yep that fixes it! I'll play around with it some more for our other studies, but feel free to close in the meantime.

**Comment by richardliaw** [comment]
Awesome!
