### ISSUE TITLE
[autoscaler] Should have pool of stopped nodes (rather than terminating them)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5739]
### Describe the problem
A lot of the overhead of instance initialization is only paid the first time the instance is booted, since it needs to populate the EBS blocks, etc. This is easily seen since something like "import tensorflow" takes a very long time. However if you stop and start the instance, it is fast the second time.

In the autoscaler context, many times a lot of state such as library dependencies, etc. also only need to be installed the first time.

When scaling up and down rapidly (or starting a new cluster), the current strategy of terminating nodes results in a lot of time wastage. We should stop nodes instead of terminating them, and launch nodes from this pool of stopped nodes if possible.

The main downside is stopped nodes still incur some cost to maintain their EBS volumes. However, this is often much less than the node cost.

cc @hartikainen @ls-daniel @richardliaw

**Comment by ericl** [comment]
To put the cost tradeoff in context, m4.16xl is $3.20 an hour, 100GB EBS is $0.01 an hour.

**Comment by richardliaw** [comment]
I would use this; `ray suspend`?

**Comment by ericl** [comment]
To be clear this would be in the context of normal autoscaling too.
