### ISSUE TITLE
ray has no attribute init

### ISSUE THREAD

**Issue by thebeancounter** [ray-project/ray#5743]
I am using ray on a linux server, installed it using pip 
and when using 

```
import ray 
ray.init()
```

I keep getting 

> ray has no attribute init 

What am i missing here?

**Comment by richardliaw** [comment]
looks like ray was installed incorrectly; can you try uninstalling ray multiple times and checking `ray.__file__` (site-packages) to see that it's really gone?

**Comment by thebeancounter** [comment]
@richardliaw I am using a conda env, and looking for ray.__file__ using sudo find / -name ray.__file__ and there is nothing on the machine with that name, is that sufficient for validating the removal?

**Comment by thebeancounter** [comment]
@richardliaw p.s istalled it again using this[https://anaconda.org/bioconda/ray]
and tried to install pip specific to that conda env. Still no luck, same issue

**Comment by thebeancounter** [comment]
@richardliaw when I go to the python stub for ray (using ctrl+click) on the import I get to an empty init file. Is it possible that the conda env is not installing properly for some reason?

**Comment by richardliaw** [comment]
This isn’t maintained by us, unfortunately... can you use pip?

**Comment by thebeancounter** [comment]
@richardliaw I installed is using pip on a conda env. 
source env 
pip install ray 

Still the same problem...

**Comment by thebeancounter** [comment]
@richardliaw 

shame on me, had another directory named ray in the project, interpreter found it and mapped it to path running over the real ray. 

removed it, now its working
