### ISSUE TITLE
AttributeError: module 'ray' has no attribute 'remote' 

### ISSUE THREAD

**Issue by hokiegeek2** [ray-project/ray#5768]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave, version 10.14.6
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.7.4
- **Python version**: 3.7.1 (Anaconda)
- **Exact command to reproduce**:

### Describe the problem
AttributeError: module 'ray' has no attribute 'remote' is raised when I attempt to import the following class:
```
@ray.remote
class RemoteExecutor(Executor):

    def execute(self, params=None):
        
        print('executing with {}'.format(params))
        return ReturnObject(params)'
```

**Comment by hokiegeek2** [comment]
Also, the code

```
import ray


def main():

    ray.init(num_cpus=4, memory=1e+8, object_store_memory=1e+9)

if  __name__ == '__main__':
    main()
```
raises the following error:

```
AttributeError: module 'ray' has no attribute 'init'
```

**Comment by hokiegeek2** [comment]
OBE, I fixed it

**Comment by swicaksono** [comment]
Hi @hokiegeek2, I have the same issue. How did you solved this?
