### ISSUE TITLE
Multi-discrete action space support for Pytorch? 

### ISSUE THREAD

**Issue by flyinskybtx** [ray-project/ray#5770]
Or could there be any work around alternatives for this demand?

I am working on a project that requires multi-channel action space as control output and for some reason I have to rely on pytorch. However i found that pytorch only support Box or Discrete action space in action_dist.

I have considered to rollout my actionspace however it is quite large 28^6, and it hinders me from adding constraints on different channels. 

So  could there be any work around alternatives for Multi-discrete action spaces with Pytorch? and Will Ray support Multi-dicrete for Pytorch in the future?

Thanks in advance to  any helps! Thank you

**Comment by ericl** [comment]
You could perhaps try specifying a custom action distribution? https://ray.readthedocs.io/en/latest/rllib-models.html#custom-action-distributions

Btw, why the pytorch dependency---would translating the code to TF eager work instead?
