### ISSUE TITLE
Actor class attributes not visible in actor methods?

### ISSUE THREAD

**Issue by johann-petrak** [ray-project/ray#5774]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: pip install under per-user Anaconda installation
- **Ray version**:  0.7.4
- **Python version**: 3.6.8
- **Exact command to reproduce**: N/A see code below

### Describe the problem

I tried to use and existing class as an actor with ray. That class assigns a number of constant values to class-level attributes and then uses those constants 
with the class methods, like so:

```python
class C:
    CONST1 = 123
    def method(self):
        tmp = CONST1  
    ...
```

When I use that class with Ray, when calling the class method, I get the exception "AttributeError: 'ActorClass' object has no attribute 'CONST1'"

### Source code / logs

Here is a full example ready to try and run. The class wrapped as an actor is not able to access the class-level attribute:

```python
import ray
ray.init()

class Test0:
    X = 1
    def __init__(self):
        print("Test 0 initialised")
    def run(self):
        print("Test 0 called")
        return Test0.X
t0 = Test0()
print("Test0 result:", t0.run())

class Test1:
    X = 1
    def __init__(self):
        print("Test 1 Initialised" )
    def run(self):
        print("Test 1 Called")
        return Test1.X

print("Test1 defined, X=", Test1.X)
Test1 = ray.remote(Test1)

t1 = Test1.remote()
print("Test1 result:", ray.get(t1.run.remote()))

@ray.remote
class Test2:
    X = 1
    def __init__(self):
        print("Test 2 Initialised" )
    def run(self):
        print("Test 2 Called")
        return Test2.X

t2 = Test2.remote()
print("Test2 result:", ray.get(t2.run.remote()))
```

**Comment by pcmoritz** [comment]
Thanks a lot for reporting this and also for the reproduction code which is very useful! This is indeed a bug, let me look into it. As a workaround for now you can do this:

```
class Test1:
    X = 1
    def __init__(self):
        print("Test 1 Initialised" )
    def run(self):
        print("Test 1 Called")
        return self.X

Test1 = ray.remote(Test1)
t1 = Test1.remote()

In [7]: print("Test1 result:", ray.get(t1.run.remote()))                                                     
Test1 result: 1
```

i.e. replace the Test1.X with self.X, which works.

**Comment by johann-petrak** [comment]
The problem is that that workaround then makes the class break when used without Ray.

Another symptom of probably the same underlying problem is that static methods do not work:

Running this:
```
class Test0:
    @staticmethod
    def m():
        return 2
    def __init__(self):
        print("Test 0 initialised")
    def run(self):
        print("Test 0 called")
        return Test0.m()
t0 = Test0()
print("Test0 result:", t0.run())

@ray.remote
class Test1:
    @staticmethod
    def m():
        return 2
    def __init__(self):
        print("Test 1 Initialised" )
    def run(self):
        print("Test 1 Called")
        return Test1.m()

t1 = Test1.remote()
print("Test1 result:", ray.get(t1.run.remote()))
```
causes an exception "Methods must take a 'self' argument, but the method 'm' does not have one."

This is a real problem for classes outside of the direct control of the programmer but also awkward for own classes because it means that all static classes must be copied to fake instance methods, invocation from outside the class and inside has to be made slightly different etc. 

Maybe I am unlucky but I am hitting this problem quite frequently.

**Comment by pcmoritz** [comment]
@johann-petrak The fix has now been merged into master, do you want to check if it solves your problems? You can install and try it out from https://ray.readthedocs.io/en/latest/installation.html#latest-snapshots-nightlies
