### ISSUE TITLE
How to implement a KV store/Embedding server with ray?

### ISSUE THREAD

**Issue by VoVAllen** [ray-project/ray#5779]
How to implement a KV store/Embedding server with ray?

Since I didn't see how I can ensure the object to be kept or removed from object store.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

**Comment by virtualluke** [comment]
What is the more specific use case you have in mind that makes you want to implement a KV store with ray?

**Comment by VoVAllen** [comment]
Thanks for reply. It's something like a distributed plasma storage, which could store huge embeddings, and would be updated by row each time. The case here is embedding may have millions or billions entries, therefore full update is not preferred. I expect it's something like a kv store that we can only update partial rows for the full embedding matrix.
