### ISSUE TITLE
Is there a way to alter model size in PBT?

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#5788]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux RHEL 7.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem

One of the parameters which would be interesting to optimize while hyper parameter sweeping would be the size of the network... but when I currently try the below, I get an error during the preturb step when trying to restore... 

AssertionError: Passed weight does not have the correct shape.

Is there a way to make this work?  If not, any suggestions where to best try? Seems like there would need to be some form of policy_sync between trial.runners...
Below code reproduces....

### Source code / logs

```
hyperparam_mutations= {
    "model": {"fcnet_hiddens": [[64, 32], [128, 32]]}
}

pbt = PopulationBasedTraining(
    time_attr="training_iteration",
    reward_attr="episode_reward_mean",
    perturbation_interval=2,
    hyperparam_mutations= hyperparam_mutations
)


ray.tune.run("DQN",
    name="cp-pbt",
    verbose=1,
    scheduler= pbt,
    stop= {"training_iteration": 500},
    num_samples= 4,
    config={
        "env": "CartPole-v0",
        "model": MODEL_DEFAULTS
    }

)
```

**Comment by richardliaw** [comment]
maybe you have to write a custom Model for rllib? cc @ericl

**Comment by waldroje** [comment]
i realize the error in my thinking... one just has to initially create trials via the model_config and "grid_search"  and num_samples such that your initial trials contain a good representation of network sizes, and then let normal hyperparam_mutations impact them, rather than allow network sizes be a hyperparam mutation itself., everything seems to run fine doing it that way....
