### ISSUE TITLE
Problems with resource deadlock warning.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#5790]
The resource deadlock warning will fire spuriously (some fraction of the time) during the following workload.

```python
import ray

ray.init(num_gpus=2, num_cpus=2)

@ray.remote(num_gpus=1) 
def f(): 
    return 

@ray.remote(num_gpus=1) 
def g(): 
    ray.get(f.remote())

ray.get([g.remote(i) for i in range(2)])
```

The reason is that it is waiting for a worker to start up.

If we then subsequently run something which actually does deadlock, like

```python
@ray.remote(num_gpus=1) 
def f(): 
    return 

@ray.remote(num_gpus=1) 
def g(): 
    ray.get(f.remote())

ray.get([g.remote(i) for i in range(2)])
```

it may not print any warning because the warning happens at most once every `debug_dump_period_` milliseconds.

**Comment by robertnishihara** [comment]
https://github.com/ray-project/ray/issues/5789 is related.

**Comment by robertnishihara** [comment]
cc @edoakes

**Comment by ericl** [comment]
This is working as designed -- a warning will eventually show up. But feel free to ignore them if the cluster is still scaling up.

**Comment by ericl** [comment]
Also, is the second case supposed to work? Not sure if GPU resources are released on the blocking get call.

**Comment by robertnishihara** [comment]
The behavior seems to have changed here. Now if I run

```python
import ray

ray.init(num_gpus=2, num_cpus=2)

@ray.remote(num_gpus=1) 
def f(): 
    return 

@ray.remote(num_gpus=1) 
def g(): 
    ray.get(f.remote())

ray.get([g.remote() for _ in range(2)])
```

it deadlocks (as it should), but there is no warning (either in stdout or in the dashboard).
