### ISSUE TITLE
Bug with Ray's packaged PyArrow: Parquet read_table error in Python3.7: pyarrow.lib.ArrowInvalid: Column data for field with type list<...> is inconsistent with schema list<...>

### ISSUE THREAD

**Issue by TheVinhLuong102** [ray-project/ray#5795]
I have Parquet files with certain complex columns of type List<item: double>, List<item: string>, etc. and am using PyArrow to process them. My libraries also make use of Ray extensively.

The problem I'm having is that the PyArrow 0.14.0.RAY packaged with Ray and loaded upon importing Ray has a bug while reading such complex Parquet files, and returns errors of the kind "pyarrow.lib.ArrowInvalid: Column data for field 0 with type list<item: double> is inconsistent with schema list<element: double>".

When try loading these files with stand-alone PyArrow 0.14.0 or 0.14.1, there are no such errors. So the bug is indeed inside PyArrow 0.14.0.RAY.

Please let me know what are the options for getting out of this situation.

**Comment by wesm** [comment]
Bundling unreleased versions of Apache Arrow in Ray exposes users to a great deal of risk. I've warned about this before

**Comment by virtualluke** [comment]
Does it involve the interaction with ray and pyarrow or do you see the issue with the specific pyarrow whl that aligns with the ray whl (if such is sitting around somewhere).

**Comment by wesm** [comment]
My understanding is that Ray includes a complete copy or pyarrow inside its wheel. So if you have both installed, depending on the import order you will be using a different one.

**Comment by pcmoritz** [comment]
@TheVinhLuong102 Thanks for the report and sorry to hear about the inconvenience! Do you want to try running your workload with this patch: https://github.com/ray-project/ray/pull/5798 and pyarrow 0.14.1 from pip? If you don't work TensorFlow or pytorch, that should work out of the box.

This is also the longer term direction are moving towards, but before we can do it a few more things need to happen :)

**Comment by TheVinhLuong102** [comment]
@pcmoritz thanks for your patch. Yes, I also figured out last night that those were the related lines of code, so I did indeed manually commented out those lines to make my current workloads work, for now. :)

**Comment by rostyboost** [comment]
I also hit this issue with `pyarrow==0.15.0`:
```
Column data for field 3 with type list<item: int64 not null> is inconsistent with schema list<element: int64 not null>
```
I write these parquet files from a Spark job (so `parquet-mr` writer, `1.9.1`).

Note that in my case, read with `pyarrow==0.14.1` also fails for this column.
I _suspect_ it's because the values of my column can be large (meaning, very long arrays), because I've read `array<float>` columns in `pyarrow==0.14.1` in the past without issues.

**Comment by walter-rover** [comment]
I also have the issue with `pyarrow==0.15.0` but not `pyarrow==0.14.1`. Specifically like @rostyboost mentioned this error arrises when writing parquet files using Spark then reading them using pandas.

```pyarrow.lib.ArrowInvalid: Column data for field 6 with type list<item: int32> is inconsistent with schema list<element: int32>```

The issue resolves around how the Spark writer writes the schema when a column has a more complex type like a List of integers. When pyarrow attempts to read the column it compares the schema specified in the parquet file with its interpreted value using a direct string equals comparison `"list<item: int32>" == "list<element: int32>"` which resolves to `False`
