### ISSUE TITLE
one gpu per worker

### ISSUE THREAD

**Issue by 7starsea** [ray-project/ray#5796]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **Ray installed from (source or binary)**:
- **Ray version**: 0.7.5
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem

start ray and worker on one machine with 4gpus
```
ray start --head --redis-port=6379 --num-cpus=1 --num-gpus=1 --resources='{"gpu_id": 0}'
ray start --redis-address 127.0.0.1:6379 --num-cpus=1 --num-gpus=1 --resources='{"gpu_id": 1}'
ray start --redis-address 127.0.0.1:6379 --num-cpus=1 --num-gpus=1 --resources='{"gpu_id": 2}'
ray start --redis-address 127.0.0.1:6379 --num-cpus=1 --num-gpus=1 --resources='{"gpu_id": 3}'

```
and here is my driver:
```
import ray, time, torch
ray.init(redis_address="127.0.0.1:6379")

@ray.remote(num_gpus=1, max_calls=1)
def g(i):
    x = torch.rand(100, 100, device='cuda')
    print("ray.get_gpu_ids(): {} {}".format(ray.get_gpu_ids(), i))
    time.sleep(1.01)

a = ray.get([g.remote(i) for i in range(12)])
```

Q1. I would expect that each worker would use one gpu, but the testing result is that all four workers only use the first gpu.
Q2. How could I get resources specified by cmd line (e.g.  `--resources='{"gpu_id": 3}'`) in the remote function(e.g. `def g(i)`) ?

**Comment by richardliaw** [comment]
You only need to call ray start --head once (and without gpu_id=0). You can also specify gpus via `--num-gpus `
