### ISSUE TITLE
Fix ray.wait for timeouts > 2**30

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#58]
Right now, we limit the maximum timeout for ray.wait to be 2**30 us. This is ~1000s, which is too short. We should track down the problem in here:

https://github.com/ray-project/ray/pull/42

And make the timeout a 64-bit number.

**Comment by robertnishihara** [comment]
This bug is still present for legacy Ray, right? But when we switch to x-ray it should be gone (though I haven't tried it).
