### ISSUE TITLE
docker build delpoy error

### ISSUE THREAD

**Issue by caowei012136** [ray-project/ray#5804]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7.3
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.4
- **Python version**: 3.6.5
- **Exact command to reproduce**: RUN pip install -e .

when i run follow command:
docker build --no-cache -t deploy deploy
the console print the follow errror info:
  [1,025 / 1,179] Compiling external/com_google_absl/absl/time/duration.cc; 0s processwrapper-sandbox ... (2 actions running)
    ERROR: /ray/BUILD.bazel:649:1: Executing genrule //:python/ray/_raylet.pyx_cython_translation failed (Exit 1) bash failed: error executing command
      (cd /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/sandbox/processwrapper-sandbox/1152/execroot/com_github_ray_project_ray && \
      exec env - \
        PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin \
      /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 ${PYTHON_BIN_PATH} external/cython/cython.py --cplus python/ray/_raylet.pyx --output-file bazel-out/k8-fastbuild/bin/python/ray/_raylet.cpp')
    Execution platform: @bazel_tools//platforms:host_platform

    Use --sandbox_debug to see verbose messages from the sandbox: bash failed: error executing command
      (cd /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/sandbox/processwrapper-sandbox/1152/execroot/com_github_ray_project_ray && \
      exec env - \
        PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin \
      /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PYTHONHASHSEED=0 ${PYTHON_BIN_PATH} external/cython/cython.py --cplus python/ray/_raylet.pyx --output-file bazel-out/k8-fastbuild/bin/python/ray/_raylet.cpp')
    Execution platform: @bazel_tools//platforms:host_platform

    Use --sandbox_debug to see verbose messages from the sandbox
    /bin/bash: PYTHON_BIN_PATH: unbound variable
    Target //:ray_pkg failed to build
    INFO: Elapsed time: 473.831s, Critical Path: 14.02s
    INFO: 1151 processes: 1151 processwrapper-sandbox.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/ray/python/setup.py", line 180, in <module>
        license="Apache 2.0")
      File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/ray/python/setup.py", line 73, in run
        subprocess.check_call(command)
      File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/opt/conda/bin/python']' returned non-zero exit status 1.

    ----------------------------------------
Command "/opt/conda/bin/python -c "import setuptools, tokenize;__file__='/ray/python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /ray/python/
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

[Uploading build_ouput.txt…]()

**Comment by edoakes** [comment]
Automatically closing stale issue. Please re-open if still relevant.
