### ISSUE TITLE
Custom policy optimizer in rllib

### ISSUE THREAD

**Issue by yannbouteiller** [ray-project/ray#5812]
Hello,

I am a (multiagent) RL research student and I am currently discovering rllib (very nice project by the way). I have found the documentation helpful about how to implement custom environments and custom policies, but my main interest is to use rllib with custom policy optimizers and I didn't find any documentation about how to implement these.

Did I miss something, please?

Best regards,
Yann.

**Comment by ericl** [comment]
Check this out: https://ray.readthedocs.io/en/latest/rllib-concepts.html#policies

**Comment by yannbouteiller** [comment]
Oh I see, thanks @ericl !
