### ISSUE TITLE
[tune] TypeError: can't pickle Connection objects

### ISSUE THREAD

**Issue by yukiego** [ray-project/ray#5817]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Mojave 10.14.6
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6.8
- **Exact command to reproduce**:

```tune.run(
    tuner,
    scheduler=my_sched,
    name=my_experiment_name,
    config=my_config,
    search_alg=my_algo,
    verbose=my_vernose,
    stop=my_stop,
    num_samples=my_num_samples)
``` 

### Describe the problem
The above code returns `TypeError: can't pickle Connection objects` in Python 3.6.8 but works well on 3.5.7.  

I detected the exact source of the error is `https://github.com/ray-project/ray/blob/master/python/ray/tune/registry.py#L91`.  

Here is an example output in my debugger.  

```
self = <ray.tune.registry._Registry object at 0x11a42f320>
category = 'trainable_class'
key = 'tuner'
value = <class 'ray.tune.function_runner.wrap_function.<locals>.WrappedFunc'>
def register(self, category, key, value):
    if category not in KNOWN_CATEGORIES:
    self._to_flush[(category, key)] = pickle.dumps(value)
!!! TypeError: can't pickle Connection objects
```

**Comment by richardliaw** [comment]
Ah, sorry for the late reply. Can you paste your `tuner`?

**Comment by yukiego** [comment]
Hi,

I can't paste the actual code but here's our mock code.

```
def tuner(config, reporter):
    model = load_model_class()
    history = model.model.fit(x=x,
                              y=y,
                              validation_data=validation_data,
                              epochs=epochs,
                              verbose=verbose,
                              batch_size=batch_size,
                              callbacks=[TuneCallback(reporter)])
    val_loss = history.history['val_loss'][-1]
    save_val_loss(val_loss)
```
where `load_model_class` load `tf.keras` model class that we predefined, and `save_val_loss` to save results to our database.

and here is out `TuneCallBack`

```
import tensorflow as tf

class TuneCallback(tf.keras.callbacks.Callback):
    def __init__(self, reporter):
        self.reporter = reporter
        self.iteration = 0
        super(TuneCallback, self).__init__()

    def on_epoch_end(self, epoch, logs=None):
        """
        This records val_loss at the end of each epoch
        """
        self.reporter(
            timesteps_total=self.iteration, val_loss=logs['val_loss'])
```

Again this works on Python 3.5.7 but not on 3.6.8.
Thanks!

**Comment by richardliaw** [comment]
Does the `save_val_loss` have a database connection? can you try creating the database connection inside `def tuner`?

**Comment by yukiego** [comment]
Yes it does, our database connection is based on `MySQLdb` class

**Comment by yukiego** [comment]
But the db connection has nothing to do with this issue I suppose.
It looks to me it's coming from `pickle.dumps(value)` where value is `<class 'ray.tune.function_runner.wrap_function.<locals>.WrappedFunc'>`.

**Comment by richardliaw** [comment]
The wrappedfunc is the tuner function - I think if you comment out “save_val_loss” it will work. I think Tune is trying to pickle a db connection (which is necessary for it to run “tuner” on different machines”).

Alternatively, if you are trying to write, why not use a custom logger?

**Comment by yukiego** [comment]
Looks like you are right.
Thanks, will try a custom logger ;)

**Comment by richardliaw** [comment]
Feel free to contribute a MySQLLogger btw!
