### ISSUE TITLE
MLFlow parameter error using rllib agents

### ISSUE THREAD

**Issue by fatenghriss** [ray-project/ray#5821]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.7.5
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem

When I tried to integrate MLFlow to my experiment that uses a DQN agent, I get the following error:
```
    Trainable.__init__(self, config, logger_creator)
  File "/python3.7/site-packages/ray/tune/trainable.py", line 96, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/python3.7/site-packages/ray/rllib/agents/trainer.py", line 478, in _setup
    self._allow_unknown_subkeys)
  File "/python3.7/site-packages/ray/tune/util.py", line 160, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter mlflow_experiment_id 
```

It seems like the agent's config is quite frozen, and there doesn't seem to be an explicit way to allow new keys to that config.

When I digged a bit in the code, I found, in the `rllib/agents/trainer.py` that there's an argument to the deep_update function that merges configs together called `allow_unknown_configs` and that is by default set to False. When I set it to True, for testing purposes, it worked.
So maybe we should add an abstraction layer to that so that it can easily be set from the experiment itself.

### Source code / logs

This is part of the source code of when I ran the experiment on a DQN agent. I got the error above

```
   tune.run(
        ...
        config={
            "mlflow_experiment_id": experiment_id,
            ...
    )
```

**Comment by sotte** [comment]
I have a similar, but not MLflow related, problem. The basic question is the same: How do you pass arguments via the config if the agent does not allow additional config values.

Maybe an abstraction layer to allow additional parameters makes sense.
Or maybe allowing a field like `"custom_config"` should be allowed all the time.

**Comment by hcch0912** [comment]
I have the same issue, I have to hack the code in trainer.py 
put `_allow_unknown_configs=True`. Only in this way I am able to use MLflow 
@fatenghriss

**Comment by cbpr** [comment]
Similarly stumbled over this while trying to hand-over further values to MyOwnGymEnv

    tune.register_env("MyOwnGymEnv", lambda config: MyOwnGymEnv(config))
How else such is meant to work?

**Comment by cbpr** [comment]
@fatenghriss maybe you could reword the issue topic?
