### ISSUE TITLE
Unknown instability with kubernetes cluster

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#5843]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Redhat 7.6
- **Ray installed from (source or binary)**: binary
- **Ray version**:  0.7.4 -0.8.0dev5
- **Python version**: 3.7.3
- **Exact command to reproduce**:

### Describe the problem

The kubernetes cluster has nodes related to ray jobs that freeze up on pod termination and result in the nodes in question crashing.  Unfortunately,  I don't have many details here.  

I am using a cluster.yaml that is basically equivalent to the one in the docs.  On job completion the cluster is killed and this works as expected 99.9% of the time but we have seen twice now in the last 4 months after the job completes and the ray pods are in a terminating state that the pods get stuck in terminating state and the nodes become unstable.  We haven't found any logging pointing to the underlying issue. The nodes in question have a system load that climbs without any obvious reason until the node freezes up and needs a hard reboot to recover.

This may not have anything to do with ray per se as the ray job is finished (successfully) and the pod is in terminating state.  It could be some edge case where cleanup of a large dshm (say > 256GB) is not always happening correctly (just speculation).

Sorry I don't have more to go on.

**Comment by gehring** [comment]
Would you be able to share the config files used to run the ray deployments?

**Comment by richardliaw** [comment]
Hey @gehring the one in the docs is here: https://github.com/ray-project/ray/tree/master/doc/kubernetes

**Comment by gehring** [comment]
I guess my question was more, did they use the ones from the docs as is (apart from changing cpu/ram/gpu)? It might also help to know what version of kubernetes they are running and if they have any alpha features enabled.

I don't really know what could cause the issue they describe but my initial guess would be an issue on the kubernetes side. That's not to say that we can't avoid it on the ray side. If some aspect of the deployment is stressing some component of kubernetes in unexpected ways, we could probably find ways to mitigate that.

**Comment by edoakes** [comment]
@virtualluke I believe we addressed this issue but can't remember 100%. Can you please re-open if still relevant?
