### ISSUE TITLE
Rllib Trainer.save not saving the .tune_metadata

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#5855]
When calling checkpointing with a custom path: `trainer.save("checkpoint")` it does not save the `.tune_metadata` files with it.

So if you later do: 

```
trainer = impala.ImpalaTrainer(config=config, env=ENV_NAME)
trainer.restore("checkpoint1")
```
You get this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint1.tune_metadata'
```

The `tune_metadata` is still stored in `~/ray_results` directory.

**Comment by richardliaw** [comment]
Is the issue here that you're using `checkpoint` for save and then `checkpoint1` for restore?

**Comment by drozzy** [comment]
Didn't try this yet, and will re-open if I need it again.
For now, I'm using default paths just fine.
