### ISSUE TITLE
[rllib] PPO Gamma Configuration

### ISSUE THREAD

**Issue by hcch0912** [ray-project/ray#5873]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**:  0.7.5
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem

Would like to set the gamma of the PPO algorithms. Now there's only option for Lambda and using GAE or not.

**Comment by richardliaw** [comment]
You can still set `gamma`; see `rllib/agents/trainer.py` (it is folded into the base_config).
