### ISSUE TITLE
[multi-tenancy] Outdated env vars and functions

### ISSUE THREAD

**Issue by drivenow** [ray-project/ray#5874]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:  pip install
- **Ray version**: 0.7.3
- **Python version**: python3.6
- **Exact command to reproduce**:

### Describe the problem

It's convinient for ray applications to connect an exsiting ray cluser by passing a redis address, 
and making it possible for multiple users to run their applications on the same ray cluster.

With that in mind, **we deploy a ray cluster by kubernetes, and provide a long-time ray cluster for multiple users.** <br>
Users can upload their codes to ray cluster，and add some environment variable to their tasks run as desired.

**Because sharing the same ray cluster by users has two advantages:** <br>
(1) increase resource usage, because once one user's task finishes and cpu is free, other users' tasks can run then;
(2) easy to monitor, because only need to care about only one ray cluster, just like the use of spark cluster.

As a ray cluster has long-time workers to increase the throughput of tasks,  **it causes some problems at the same time**:
(1)**Outdated environment variables**: the former user's tasks may add some environment variable which may cause conflicts on later user's tasks.
(2) **Outdated function definitions**: just like "https://ray.readthedocs.io/en/latest/troubleshooting.html" metions, it will not work at once if users change their code and upload to ray cluster.

**So is there a way to clean these outdated information after every task finishes?**
**Or is there any better way for multiple users to share the same ray cluster?**

**Comment by richardliaw** [comment]
Currently, the multi-tenant cluster support is not well-tested. 

There is some limited support for refreshing workers and avoiding this leaked state, such as `max_calls` for remote tasks: https://ray.readthedocs.io/en/latest/package-ref.html#ray.remote

**Comment by drivenow** [comment]
It works！Thanks！
