### ISSUE TITLE
Soft actor critic error: "Number of elements was larger than representable by 32-bit output type"

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#5897]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.4 
- **Python version**: 3.6.5
- **Exact command to reproduce**: N/A

### Describe the problem
Running a soft actor critic algorithm with the following hyperparams and 32 workers, I got the attached error. I can't give the command because it was run in a custom env. 

            
[error_2019-10-12_21-09-55-1.txt](https://github.com/ray-project/ray/files/3721180/error_2019-10-12_21-09-55-1.txt)
config['tau'] = tune.grid_search([5e-3, 5e-4])
            config['optimization']['actor_learning_rate'] = tune.grid_search([5e-3, 5e-4])
            config['optimization']['critic_learning_rate'] = tune.grid_search([5e-3, 5e-4])
            config['optimization']['entropy_learning_rate'] = tune.grid_search([5e-3, 5e-4])
            config['no_done_at_end'] = tune.grid_search([True, False])

**Comment by eugenevinitsky** [comment]
Some other notes that might help, I can run it locally, it only breaks when I run it on EC2 across 5 nodes.

**Comment by eugenevinitsky** [comment]
Also, if it helps I'm attaching the corresponding run script and the command I ran it with is:
"ray exec ray_autoscale.yaml \
"python flow/examples/rllib/velocity_bottleneck.py centralized_0pen_SAC --num_iters 5000 --av_frac 0.1 --multi_node --sims_per_step 2 --sim_step 0.5 --warmup_steps 100 \
--num_samples 1 --grid_search --n_cpus 36 --use_s3 --rollout_scale_factor 2.0 --horizon 1000 --low_inflow 1200 --high_inflow 3000 --life_penalty 0.0 --algorithm SAC" \
--start --stop --cluster-name exp3 --tmux"
[velocity_bottleneck.txt](https://github.com/ray-project/ray/files/3721191/velocity_bottleneck.txt)

**Comment by eugenevinitsky** [comment]
@hartikainen would you happen to have encountered this error in your use of SAC?

**Comment by hartikainen** [comment]
Hey @eugenevinitsky, unfortunately, I have never seen this error before. It looks like this is a tensorflow issue with the inputs being too large, which is why I'm not sure if this is specific to SAC. Do you know if your example fails in the same way with, for example, DDPG?

**Comment by annaluo676** [comment]
I encountered this once on EC2 with SAC. But I wasn't able to reproduce it as it looked fine after re-submitting the job.

**Comment by eugenevinitsky** [comment]
Thanks to you both! I have not tested it yet with DDPG but will give it a try and see what happens.

**Comment by josjo80** [comment]
I also recently saw this error with SAC and haven't seen it with other algos.  My install is TF 2.0 and Ray[RLlib] 0.7.6.  It was reproducible with a very high `"sample_batch_size": 100000, "train_batch_size": 10000`.  When I lowered both to 10k and 5k respectively it seemed to work.  My environment is a custom env wrapped in Gym.  Hope that helps with debugging.
