### ISSUE TITLE
[Tune] About fractional GPU

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#5902]
### System information
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6.5

### Describe the problem

For now, Tune allocates fractional GPU in terms of the total number of GPUs. For example, if one `Trainable` requires `0.15` gpu, there will be `floor(8/0.15)=53` trials in a 8-GPU machine. This would be problematic in practice because the memory of different GPUs is separate.

The expected number of trials is `8*floor(1/0.15)=48`.

**Comment by richardliaw** [comment]
Thanks for raising this issue @llan-ml! 

Would it be reasonable to just assert that if you have a fraction for `resources_per_trial`, it must exactly equal to 1 by some integer multiplication?

**Comment by ericl** [comment]
Can the calculation be fixed?

**Comment by richardliaw** [comment]
The floor operator doesn’t make sense if we assume trials can have
different resource quantities.

**Comment by llan-ml** [comment]
The max number of trials in a GPU is not determined. It would waste some GPU resources if we assert that.

**Comment by richardliaw** [comment]
I think without any overly complicated mechanism it won't be easy to support this, but maybe I'm wrong. Imagine if you have `cpu=0.3` and `extra_cpu=0.4`, (extra_cpu is used in distributed trials). I have 4 CPUs. How do you calculate the expected number of trials?

**Comment by llan-ml** [comment]
I would calculate the number as `floor(4/(0.3+0.4))=5` under the assumption that the system memory is large enough. However, the GPU memory is relatively scarce. If we do not have a floor operator, the program will raise OOM error. In my practice, I set `num_gpus` in terms of the GPU memory a program will occupy.

I'm not sure how Ray/Tune allocates a GPU to a process/trial. Imagine that we have `num_gpus=0.4` and 2 GPUs. For now, we will have 5 running trials. However, after we have had 4 trials, the available gpu resource of both GPUs should be 0.2. Which GPU will be assigned to the 5-th trial? Could you first explain this?

**Comment by llan-ml** [comment]
The issue may be just about float precision? Here is a script:
```
import ray
import time
import random
from ray import tune


ray.init(num_gpus=2)


class Foo(tune.Trainable):
  def _train(self):
    time.sleep(5)
    return {}


tune.run(
  Foo,
  name="foo",
  stop={"training_iteration": 5},
  num_samples=50,
  resources_per_trial={"gpu": 0.35}
)

```

The log is
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/64 CPUs, 1.75/2 GPUs
Memory usage on this node: 9.9/201.4 GB
Result logdir: /home1/lanlin/ray_results/foo
Number of trials: 50 ({'RUNNING': 5, 'PENDING': 45})
PENDING trials:
 - Foo_5:       PENDING
 - Foo_6:       PENDING
 - Foo_7:       PENDING
 - Foo_8:       PENDING
 - Foo_9:       PENDING
 - Foo_10:      PENDING
 - Foo_11:      PENDING
  ... 31 not shown
 - Foo_43:      PENDING
 - Foo_44:      PENDING
 - Foo_45:      PENDING
 - Foo_46:      PENDING
 - Foo_47:      PENDING
 - Foo_48:      PENDING
 - Foo_49:      PENDING
RUNNING trials:
 - Foo_0:       RUNNING, [1 CPUs, 0.35 GPUs], [pid=3656], 15 s, 3 iter
 - Foo_1:       RUNNING, [1 CPUs, 0.35 GPUs], [pid=3652], 15 s, 3 iter
 - Foo_2:       RUNNING, [1 CPUs, 0.35 GPUs], [pid=3676], 10 s, 2 iter
 - Foo_3:       RUNNING, [1 CPUs, 0.35 GPUs], [pid=3674], 10 s, 2 iter
 - Foo_4:       RUNNING
```
Although there are 5 running trials, the trial `Foo_4` is actually pending. Thus, it will not raise OOM error as I mentioned above. A better way is to put `Foo_4` into the pending queue, but the current behavior is also okay.

**Comment by richardliaw** [comment]
@llan-ml, thanks for the reply! so right now, the task is launched but will not OOM - Ray will take care of the placement and avoiding this overflow.

> I would calculate the number as floor(4/(0.3+0.4))=5 under the assumption that the system memory is large enough. 

This is different from your original proposal of `8*floor(1/0.15)=48` right? In any case, we should be able to avoid OOMs. 

Can you explain why you are opposed to "if you have a fraction for resources_per_trial, it must almost equal (`np.isclose`) to 1 by some integer multiplication"?

If you have 0.4, no matter what, you will still have at most 2 trials on the GPU. So why not force 0.5?

**Comment by ericl** [comment]
How about this?
```
>>> def roundup(f):
   rem = f % 1
   return math.floor(f) + (1./math.floor(1./rem) if rem > 0 else 0)
>>> roundup(0.15); roundup(1.0); roundup(1.15); roundup(0.7)
0.16666666666666666
1
1.1666666666666667
1.0
```

**Comment by richardliaw** [comment]
Is this only for `Resources(cpu, gpu)`? if so, that sounds good. Otherwise, it's not clear to me any rounding/integration makes sense for extra_cpu/extra_gpu. If you have 3 GPU workers each wanting 0.25, you set extra_gpu=0.75. `round_up` wouldn't make sense on `extra_gpu` then right?

**Comment by llan-ml** [comment]
> This is different from your original proposal of `8*floor(1/0.15)=48` right? In any case, we should be able to avoid OOMs.

Yes. At the beginning, I thought GPU could be oversubscribed, but those trials are actually pending. So, I think the issue is only about correctly displaying the number of running trials now.

> Can you explain why you are opposed to "if you have a fraction for resources_per_trial, it must almost equal (`np.isclose`) to 1 by some integer multiplication"?

I didn't get your point yesterday. Now, I think the constraint is okay when we only set `gpu`, and we can just set it as `gpu=1/expected_number_per_gpu`. But if we use `gpu` and `extra_gpu` at the same time? Is the constraint applied to them respectively or to the sum? For example, a trainable needs `1/4 gpu` and `1/6 extra_gpu`. If the sum, it's not straightforward for users to satisfy the constraint.

> I think without any overly complicated mechanism it won't be easy to support this, but maybe I'm wrong.

Agree. Either the sum or respectively, when we use fractional resource and `gpu` and `extra_gpu`, it may be hard to calculate the expected number of trials.

**Comment by richardliaw** [comment]
Thanks for the discussion! Looks like this is mostly resolved (it would be hard to actually get the PENDING to show up correctly because the task placement is handled by Ray, not by Tune). Closing for now, but feel free to reopen.
