### ISSUE TITLE
[tune] Understanding checkpointing & resuming?

### ISSUE THREAD

**Issue by andmib** [ray-project/ray#5904]
Hello all,

I would like to run a parameter sweep using the Hyperopt-based search functionality. My model is not serializable (because I am using Sacred). If I run a parameter sweep over (for example) 10 trials with no checkpointing, and these results are saved in `~/ray_results/sweep`, and then run another 10 trials, will Ray tune automatically utilize the original 10 trials to narrow the search space for the subsequent 10? If not, is there a way to do this without having a serializable model.

Thanks

**Comment by richardliaw** [comment]
You can do this by running `hyperoptsearch.save(logdir)` and `hyperoptsearch.restore(logdir)`. See https://ray.readthedocs.io/en/latest/_modules/ray/tune/suggest/hyperopt.html#HyperOptSearch

I am currently rewriting the documentation to better describe this.

**Comment by andmib** [comment]
Thank you! That's exactly what I'm looking for.

With that being said, if I'm passing the `hyperoptsearch` object to `tune.run_experiments`, at what point do I run `hyperoptsearch.save()` & `restore`?

I.E., if I put it at the end of the code below, I assume it will save at the very end of the `num_samples` I run. But is it possible to save the current state of `hyperoptsearch` after each successful trial?

**Comment by richardliaw** [comment]
We have #5773 in progress, which saves on a periodic time interval. That should work for you?

**Comment by andmib** [comment]
Yes thank you!
