### ISSUE TITLE
Low cpu usage on a simple run using PPO

### ISSUE THREAD

**Issue by heeryerate** [ray-project/ray#5921]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise 7.5 
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6.8
- **Exact command to reproduce**: rllib train --env=CartPole-v0 --run=PPO --config='{"num_workers": 15, "train_batch_size": 400000}

### Describe the problem

I try to run rllib PPO algorithm to train my env/agent using multiple cpus on an aws ec2 instance. It in general shows very low cpu usage like below 7% on average. I therefore moved to a standard example as 
```python
rllib train --env=CartPole-v0 --run=PPO --config='{"num_workers": 15, "train_batch_size": 400000}
``` 
However, the same low cpus usage appears again, sample log result attached below

### Source code / logs

```text
    load_time_ms: 134.904
    num_steps_sampled: 2400000
    num_steps_trained: 2400000
    sample_time_ms: 229389.761
    update_time_ms: 137.899
  iterations_since_restore: 6
  node_ip: 100.69.17.210
  num_healthy_workers: 15
  off_policy_estimator: {}
  pid: 62967
  policy_reward_max: {}
  policy_reward_mean: {}
  policy_reward_min: {}
  sampler_perf:
    mean_env_wait_ms: 0.05171635093368347
    mean_inference_ms: 8.018696828278953
    mean_processing_ms: 0.2614188626566532
  time_since_restore: 3395.460640668869
  time_this_iter_s: 540.4876708984375
  time_total_s: 3395.460640668869
  timestamp: 1571148888
  timesteps_since_restore: 2400000
  timesteps_this_iter: 400000
  timesteps_total: 2400000
  training_iteration: 6
  trial_id: 325ebe78
  
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 16/72 CPUs, 0/0 GPUs, 0.0/96.53 GiB heap, 0.0/12.84 GiB objects
Memory usage on this node: 20.5/137.3 GiB
Result logdir: /home/cloudapp/ray_results/default
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - PPO_CartPole-v0_0:   RUNNING, [16 CPUs, 0 GPUs], [pid=62967], 3395 s, 6 iter, 2400000 ts, 199 rew
```
If I monitor `top`, when the agent collects samples, ray_RolloutWork uses around 18%CPU per core, and when it updates, all other processes suspended and ray_PPO:train() uses around 700%CPU on one core. In total, the instance cpu usage is around 6%. 

I have tried to adjust OMP_NUM_THREADS, batch-size, cpu_per_each_worker, env_per_each_worker, but not seeing improvement.  Could anyone suggest how should I diagnose and resolve the problem? Thanks!

**Comment by heeryerate** [comment]
> This seems pretty normal since PPO is a synchronous algorithm, and the training is bottlenecked on SGD (try using a GPU?). Those hyperparams are also probably not very good, trying starting off with a more tuned example like HalfCheetah PPO: https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/halfcheetah-ppo.yaml
> 
> There is also APPO which does asynchronous optimization.

Thanks! I understood the SGD bottlenecked behavior for PPO. I'm wondering if I have sample size (train batch size) large enough, e.g., CartPole-v0 with 400000 samples collected at each iteration, the computation is quite heavy... should I expect such high sampling overhead, making it use only around 18% cpu per core for a while?

I will also try on the tuned example and APPO to verify :)

**Comment by richardliaw** [comment]
Yeah That sounds fine. Closing now, fee free to reopen.
