### ISSUE TITLE
rllib: TorchModelV2 and torch.nn.Module have conflicting __call__ methods

### ISSUE THREAD

**Issue by mawright** [ray-project/ray#5922]
### Describe the problem
It is suggested in the documentation that a user's Pytorch neural net subclass both rllib's TorchModelV2 and torch.nn.Module. TorchModelV2 overrides __call__ by inheriting ModelV2's __call__. However, torch.nn.Module also has a __call__ method that handles some settable hooks around the forward and backward passes https://github.com/pytorch/pytorch/blob/19d83ab8007aa5f295b3d69e8283bfbb994a011a/torch/nn/modules/module.py#L531. 

As it is, for a class that subclasses both TorchModelV2 and torch.nn.Module, only one of the two __call__ methods actually executes. One fix would be to have TorchModelV2 subclass both ModelV2 and torch.nn.Module (rather than requiring that subclasses of TorchModelV2 also subclass torch.nn.Module) and have its own __call__ that handles calls to both of the superclasses' __call__ methods.

**Comment by richardliaw** [comment]
sounds like a good idea - could you push a patch?

**Comment by mawright** [comment]
Sure, I will see when I get a chance
