### ISSUE TITLE
eager tf policies incompatible with RNN

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#5926]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6.5
- **Exact command to reproduce**: Run any RNN model in eager and local mode

### Describe the problem
If you run an RNN policy in eager mode, in eager_tf_policy line 474 it will call self.get_state_init(). This defaults to get_state_init of the policy class which returns an empty list.

**Comment by eugenevinitsky** [comment]
@richardliaw this explains the issue we were having this evening.

**Comment by richardliaw** [comment]
can you actually just post a simple thing I can copy paste?
