### ISSUE TITLE
models trained with conv_filters are not restored correctly

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#5928]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary 
- **Ray version**: 0.7.5
- **Python version**: 3.6.5
- **Exact command to reproduce**: N/A

### Describe the problem
If you train a model with conv_filters on, when you call agent.restore it errors out when restoring the weights because it does not initialize a model with convolutional layers and instead defaults to instantiating a [256, 256] FC net.

**Comment by arunavo4** [comment]
@eugenevinitsky You can get around this behavior by registering your custom model in `rollout.py`

**Comment by eugenevinitsky** [comment]
Thanks! Yep, that's what we wound up doing. The bug occurs if you're not using a custom model, just passing the conv_filters to the config.
