### ISSUE TITLE
[rllib] [tune] Not tensorboard output for tensorflow 1.12.0

### ISSUE THREAD

**Issue by pschafhalter** [ray-project/ray#5930]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: wheels
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.6.8
- **Exact command to reproduce**: 
   1. `rllib train --run DQN --env CartPole-v0 --local-dir=~/ray_results/cartpole`
   2. `tensorboard --inspect --logdir=~/ray_results/cartpole/`
        Result: `No event files found within logdir ~/ray_results/cartpole/`

### Describe the problem

When using tensorflow 1.12.0, RLlib/Tune does not create valid event files. As a consequence, users cannot track performance and view graphs via tensorboard.

This line of the console output might be relevant:
`2019-10-16 00:49:56,384	WARNING logger.py:343 -- Could not instantiate tf2_compat_logger: module 'tensorflow.compat' has no attribute 'v1'.`

### Source code / logs

[rllib_log.txt](https://github.com/ray-project/ray/files/3733089/rllib_log.txt)
[tensorboard_log.txt](https://github.com/ray-project/ray/files/3733090/tensorboard_log.txt)

**Comment by richardliaw** [comment]
Created #5931 in response.
