### ISSUE TITLE
[docs] Issue on `installation.rst`: Additional dependencies required for dashboard support

### ISSUE THREAD

**Issue by stackedsax** [ray-project/ray#5938]
# Documentation Problem/Question/Comment

Regarding the optional dashboard support, I think it's worth mentioning a couple other dependencies here:

 * https://ray.readthedocs.io/en/latest/installation.html#optional-dashboard-support

When I ran ray with `include_webui=True` the first time, it prompted me with this message:

> ImportError: Failed to start the dashboard. The dashboard requires Python 3 as well as 'pip install aiohttp psutil'.

Happy to add a line in the docs to read:

``` bash
pip install aiohttp psutil
```

**Comment by richardliaw** [comment]
can you make a pr? Thanks! @stackedsax
