### ISSUE TITLE
How to change ssh port when using cluster.yaml to set up a cluster?

### ISSUE THREAD

**Issue by gohsyi** [ray-project/ray#5950]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

I have a private cluster and I want to use ray on it. However, the ssh ports of my servers are not 22.
I wonder how to change `ray/python/ray/autoscaler/local/example-full.yaml` to specify that ssh port.

**Comment by richardliaw** [comment]
Can you edit the .ssh/config on each node instead? https://askubuntu.com/questions/1001830/is-there-a-way-to-change-default-ssh-connect-port

**Comment by gohsyi** [comment]
> Can you edit the .ssh/config on each node instead? https://askubuntu.com/questions/1001830/is-there-a-way-to-change-default-ssh-connect-port

Thank you for your reply! I want to try this, but port 22 is occupied for other purpose and I'm not allowed to change that. (The servers actually belong to my laboratory)

So, does ray provide any way to change ssh port ?

**Comment by richardliaw** [comment]
The autoscaler currently does not support this right now, but feel free to make a patch! What is the proper `ssh` command that you usually run to connect to a server?

On the other hand, you should then use the [Manual Cluster Setup](https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html) if the autoscaler is not usable.

**Comment by gohsyi** [comment]
> The autoscaler currently does not support this right now, but feel free to make a patch! What is the proper `ssh` command that you usually run to connect to a server?
> 
> On the other hand, you should then use the [Manual Cluster Setup](https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html) if the autoscaler is not usable.

Thanks! Maybe I'll try the manual way.
I usually add -p<port> to connect to the servers.
