### ISSUE TITLE
pip install ray not working on raspberrypi

### ISSUE THREAD

**Issue by miguelwon** [ray-project/ray#5959]
I can't install ray with `pip install ray`. Pip does not find it. I'm using Raspbian 10 with pip version 19.3

> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
> ERROR: No matching distribution found for ray

### System information
- **Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux**:
- **pip 19.3 from /home/pi/raspcamera/env/lib/python3.7/site-packages/pip (python 3.7)**

**Comment by simon-mo** [comment]
Ray is not compiled to ARM processor right now. We only have pre-built x86 binaries. However, you can try [build from source](https://ray.readthedocs.io/en/latest/installation.html#building-ray-from-source) on raspberrry pi.

**Comment by gimzmoe** [comment]
I took at stab at building but failed, but I'm not exactly proficient...
I think this would be an appealing use, especially with the [turing pi 2](https://turingpi.com/turing-pi-2-announcement/) coming out soon.

**Comment by simon-mo** [comment]
Thanks for taking a stab, @gimzmoe, can you post the error?
