### ISSUE TITLE
Test failure with python3 on ubuntu 14.04

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#596]
With the system python3 on ubuntu 14.04, the following fails, which makes runtest.py fail:

```
import re
regex = re.compile(r"\d+\.\d*")
assert pickle.loads(pickle.dumps(regex)) == regex
```

Thanks @cbfinn for reporting this!

**Comment by cbfinn** [comment]
FYI, I encountered this error with system python 3 and ubuntu 16.04. (rather than 14.04)

**Comment by pcmoritz** [comment]
Thanks, good to know! It actually also happens on 14.04, I tried it on EC2.
