### ISSUE TITLE
[rllib] [tune] No tensorboard summary using tensorflow 2.0.0

### ISSUE THREAD

**Issue by Coac** [ray-project/ray#5963]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Build from source (master branch 26a724c5e6fa82dcb166e14170731aee0dd51807)
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.7
- **Exact command to reproduce**: `python custom_env.py`

### Describe the problem

Running the the provided rllib example `custom_env.py` without error, there is no tf summary in `ray_results/PPO/PPO_SimpleCorridor_*`

### Source code / logs
 https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py

**Comment by richardliaw** [comment]
which tensorflow version are you using?

**Comment by richardliaw** [comment]
Sigh this is so painful - can you try this? https://github.com/ray-project/ray/pull/5953/files

**Comment by Coac** [comment]
I checked your branch, using the script `custom_env.py`  it's working now, there are summaries :+1:
