### ISSUE TITLE
HyperOptSearch (and SuggestionAlgorithms) restore with empty generator and empty live_trials

### ISSUE THREAD

**Issue by Michiel29** [ray-project/ray#5968]
Currently, the trial generator is not part of the saved state for HyperOptSearch. #5773 adds save/restore of the search algorithm to the trial runner. However, upon resuming an experiment the trial runner skips adding an experiment to the search algorithm. The trial generator is normally created in the call to add_experiment (this is the case more generally for SuggestionAlgorithms) and so the restored search algorithm has an empty generator and generates no further trials. 

Not sure what the best solution is, maybe also call add_experiment from trial runner for resumed trials and have the generator creation depend on the state of the search alg?

Also, HyperOptSearch maintains its own live_trial_mapping, but this is not part of the saved state, leading it to suggest too many trials on resuming an experiment.

**Comment by richardliaw** [comment]
cc @hershg

**Comment by richardliaw** [comment]
This is now supported on the latest Ray release.
