### ISSUE TITLE
SAC performance on mujoco

### ISSUE THREAD

**Issue by kapsl** [ray-project/ray#5974]
Hi,
I find it difficult to figure out working parameters for SAC. Is there just some standard examples like e.g. in the original softlearning environment?

**Comment by ericl** [comment]
@hartikainen

**Comment by kapsl** [comment]
I also have the problem, that my environment trains well on the softlearning repo, it works with ppo in ray, but not with sac at ray?!

**Comment by kapsl** [comment]
Hi @hartikainen,
my values in ray are:
`config={
"horizon": 201,
"num_workers": 5,
}`

elseway I go with the standard settings. (The same in softlearning, i have not altered the standard settings).

Could one reason be action normalization? Actually in softlearning I use the NormalizeActionWrapper. I never really understood this way of normalization. But when i use normal min max scaling, sac's performance in softlearning is really poor.

Actually in RAY - without that wrapper i get actions that are very close to each other, which seems that no exploration is taking place. (But also with this normalizationwrapper it doesn't work). 

The learning curve starts at some Point and then DEGRADE continuously.

**Comment by ericl** [comment]
The ray port does normalization internally in `unsquash_actions`. I tried commenting out `unsquash_actions` and using NormalizeActionsWrapper around the env as follows, but get pretty much the same performance. So it probably is something else:

```
from ray import tune
from ray.tune import register_env
from ray.rllib.agents.sac import SACTrainer
import numpy as np
import gym
from gym import spaces

class NormalizeActionWrapper(gym.ActionWrapper):
    """Rescale the action space of the environment."""

    def action(self, action):
        if not isinstance(self.env.action_space, spaces.Box):
            return action

        # rescale the action
        low, high = self.env.action_space.low, self.env.action_space.high
        scaled_action = low + (action + 1.0) * (high - low) / 2.0
        scaled_action = np.clip(scaled_action, low, high)

        return scaled_action

    def reverse_action(self, action):
        raise NotImplementedError


register_env("pendulum_norm", lambda _: NormalizeActionWrapper(gym.make("Pendulum-v0")))
tune.run(SACTrainer, config={
  "evaluation_interval": 1,
  "soft_horizon": True,
  "metrics_smoothing_episodes": 10,
  "env": "pendulum_norm",
})
```

![image](https://user-images.githubusercontent.com/14922/67515571-c0ddf180-f653-11e9-9c9f-e6404a0479a9.png)

FYI @michaelzhiluo if you were also looking into this

**Comment by kapsl** [comment]
Also when I use your configuration. There is the problem that the actions step by step are very close. E.g. if I have action bounds [0, 1]. I get e.g. for action 0 0.4342435 and for action 1 0.435234. The actions only deviate in the third place after the comma, normally.

**Comment by ericl** [comment]
I see actions that are spread out:

When running tuned pendulum with --eager and this patch:
```
diff --git a/rllib/agents/sac/sac_policy.py b/rllib/agents/sac/sac_policy.py
diff --git a/rllib/agents/sac/sac_policy.py b/rllib/agents/sac/sac_policy.py
index 8d5aa770b..346b89bd2 100644
--- a/rllib/agents/sac/sac_policy.py
+++ b/rllib/agents/sac/sac_policy.py
@@ -104,6 +104,7 @@ def build_action_output(policy, model, input_dict, obs_space, action_space,
         action_range = (action_space.high - action_space.low)[None]
         low_action = action_space.low[None]
         unsquashed_actions = action_range * sigmoid_out + low_action
+        print("unsquash", actions, "->", unsquashed_actions)
 
         return unsquashed_actions
 
```

I see actions like this:
```
(pid=32642) unsquash tf.Tensor([[-0.10791472]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.2149955]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.0902499]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.18001139]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.06439959]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.12862146]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.1127058]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.22446191]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.6811169]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-1.18449]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.16414352]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.32537007]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.61371136]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-1.0934687]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.2277152]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.44771826]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.24431877]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.4791417]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.2892143]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.56282306]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.51953614]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.9546838]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.354599]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.6808957]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[0.35615247]], shape=(1, 1), dtype=float32) -> tf.Tensor([[0.6836412]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[-0.4115974]], shape=(1, 1), dtype=float32) -> tf.Tensor([[-0.7796564]], shape=(1, 1), dtype=float32)
(pid=32642) unsquash tf.Tensor([[0.06167246]], shape=(1, 1), dtype=float32) -> tf.Tensor([[0.12318873]], shape=(1, 1), dtype=float32)
```

Which covers a decent range of the action space [-2, 2]?

**Comment by kapsl** [comment]
I'm currently trying different stuff - seems like during training the values are different - but for the evaluation trials they are very similiar. It's clear, that there is no exploration noise, but so similiar?! 

I'm currently also testing with a different nr. of workers, my first impression is, that it works (also when much slower then softlearning) with one worker, but has a bad performance with 6. But I need to investigate this further.

**Comment by kapsl** [comment]
Ok the performance seems to be the same with 6, but is actually even slowing down the hole process compared to 1 worker. The learning curve seems pretty much the same like with one, but streteched - and even slower!!!

**Comment by hartikainen** [comment]
Thanks a lot for fixing this @michaelzhiluo!
