### ISSUE TITLE
Restoring a non-eager agent in eager mode throws an error

### ISSUE THREAD

**Issue by dmadeka** [ray-project/ray#5983]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.8.0dev6
- **Python version**: 3.6
- **Exact command to reproduce**:

Calling `agent._restore` on a saved checkpoint (which was trained without eager) with an `eager==True` config raises the error:

```python
~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ray/rllib/policy/eager_tf_policy.py in set_weights(self, weights)
    357             variables = self.model.variables()
    358             assert len(weights) == len(variables), (len(weights),
--> 359                                                     len(variables))
    360             for v, w in zip(variables, weights):
    361                 v.assign(w)

AssertionError: (18691, 16)
```

**Comment by ericl** [comment]
@dmadeka can you try out https://github.com/ray-project/ray/pull/6001 ? I think that should fix it. You might have to generate a new checkpoint though, since this is changing the non-eager mode to be similar to eager.
