### ISSUE TITLE
[FR] low-level API for controlling job placement

### ISSUE THREAD

**Issue by SsnL** [ray-project/ray#5990]
### Describe the problem
Currently job and actor placements are automatically determined, which is great for a high-level easy-to-use abstract API. However, in many cases we want certain tasks to only run a subset of nodes, due to different machine configurations (e.g., IO access, missing libraries, CPU/GPU type). The two hacky solutions I can see working currently are:
1. custom resources. 
2. keep trying until it gets assigned to that node.

But all these isn't necessary if a set of low-level APIs can be provided.

**Comment by simon-mo** [comment]
Custom resource are designed to do this. See @atumanov's blog here https://rise.cs.berkeley.edu/blog/ray-scheduling/

**Comment by SsnL** [comment]
This still seems quite inflexible. What if I want start multiple pairs of actors, where the actors of each pair only need to collocate, and I do not care which node they do? AFAICT, there is no way to achieve this without race risk or retrying, because of the lack of ways to "transfer" resources to an actor.

**Comment by istoica** [comment]
@SsnL You can actually use custom resources to implement the above example as well. Say you want 1 GPU for each actor of the pair:
1) For each pair, create a shadow actor that allocates resources needed by both actors in the pair, i.e., 2GPUs. This shadow actor does not use any of the GPU resources. In addition, the shadow actor creates a unique custom resource X with capacity 2.
2) Launch each actor in the pair requesting 0 GPUs and custom resource X with capacity 1.

**Comment by SsnL** [comment]
@istoica Wait, I thought the actor takes resources throughout its lifetime, which means that 
1. if I launch the pair inside the shadow actor, the pair cannot "take away" X from the shadow actor
2. if the shadow actor/remote_fn returns the node ID, and I have another custom node-specific resource, and launch the pair from the node ID gotten from the shadow actor, I can end up in the race condition where some other process/thread request the pair in between these two events.

**Comment by SsnL** [comment]
@istoica I think the key is in this sentence of yours
> In addition, the shadow actor creates a unique custom resource X with capacity 2.

I was not aware of ways to create custom resource on the fly programmatically. The only way I know is to specify those for each node when launching the cluster. It would be great if I am wrong!

**Comment by simon-mo** [comment]
Ray has support for:
1. Creating dynamic resource on the fly:
- [ray.experimental.set_resource](https://github.com/ray-project/ray/blob/master/python/ray/experimental/dynamic_resources.py)
- [Usage](https://github.com/ray-project/ray/blob/master/python/ray/tests/test_dynres.py)

2. Overriding actor's resource requirement with dynamic resource [parameter](https://ray.readthedocs.io/en/latest/advanced.html#dynamic-remote-parameters)

**Comment by SsnL** [comment]
@simon-mo Thanks! Didn't know about (1). I think a bunch of experimental APIs are great (named_actors is another one). If only they could be documented in the doc website....

**Comment by SsnL** [comment]
So, IIUC, the process is to 
```py
class RealActor:
  ...

@ray.remote(actual_resource=2)  # I know this isn't the correct syntax
class ShadowActor:
  def create_actors(self):
    custom_resource_name = uuid.uuid4()
    ray.experimental.set_resource(custom_resource_name, 2)
    remote_actor_cls = ray.remote({custom_resource_name: 1})(RealActor)
    actual_resource_indices = ray.get_resource_ids()['actual_resource']
    self.a1 = remote_actor_cls.remote(actual_resource_indices[0])
    self.a2 = remote_actor_cls.remote(actual_resource_indices[1])
    a1name = uuid.uuid4()
    a2name = uuid.uuid4()
    ray.experimental.named_actors.register_actor(a1name, self.a1)
    ray.experimental.named_actors.register_actor(a2name, self.a2)
    return a1name, a2name


# main node
creator = ShadowActor.remote()
a1name, a2name = ray.get(creator.create.remote())
a1 = ray.experimental.named_actors.get_actor(a1name)
a2 = ray.experimental.named_actors.get_actor(a2name)
```

Question: Do I have to keep `creator` reference alive in main node so that `actual_resource` is taken, or is it automatically kept alive by `a1` and `a2`?

I'd argue that this is still not very clean....

**Comment by simon-mo** [comment]
With respect to keeping it alive, we just merged detached actor that might help: https://ray.readthedocs.io/en/latest/advanced.html#detached-actors

With respect to cleanliness of the snippet above, I would agree that this might be really clean and a higher level placement library can make our live easier. 

Lastly, you can use `actor_cls.options`API to make the code a bit cleaner:
https://github.com/ray-project/ray/blob/3f83b2daa95baf0de88b161399cf086d9b6e4a51/python/ray/actor.py#L329-L339

**Comment by edoakes** [comment]
Automatically closing stale issue. Please re-open if still relevant.
