### ISSUE TITLE
[Tune] Installing gputil can cause an error if nvidia-smi is not installed

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#5994]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.6.6
- **Exact command to reproduce**: Running any experiment with gputil installed

### Describe the problem
If gputil is installed, tune attempts to perform gpu monitoring by default, even if no GPUs are available on the machine. If no GPUs are available on the machine, there's a really good chance nvidia-smi is not installed. If so, you'll get the attached error.

### Source code / logs
(pid=4166) 2019-10-23 23:38:41,797      INFO trainable.py:102 -- _setup took 454.466 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(pid=4166) Exception in thread Thread-1:
(pid=4166) Traceback (most recent call last):
(pid=4166)   File "/home/ubuntu/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=4166)     self.run()
(pid=4166)   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/util.py", line 93, in run
(pid=4166)     self._read_utilization()
(pid=4166)   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/util.py", line 69, in _read_utilization
(pid=4166)     for gpu in GPUtil.getGPUs():
(pid=4166)   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/GPUtil/GPUtil.py", line 102, in getGPUs
(pid=4166)     deviceIds = int(vals[i])
(pid=4166) ValueError: invalid literal for int() with base 10: "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

**Comment by richardliaw** [comment]
Should be fixed.
