### ISSUE TITLE
Switch to absl::Mutex / absl::MutexLock instead of std::mutex / std::lock_guard

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#5995]
We should switch to using absl's locks so that we can leverage the thread annotations (e.g., GUARDED_BY). Apparently these work on bazel clang build (works on mac at least, and presumably on linux if you install clang).

Some parts of the raylet are already using absl::Mutex.

cc @zhijunfu @edoakes

**Comment by zhijunfu** [comment]
@ericl Sounds like a good idea! Thread safety analysis provided by this lib should help to avoid unintended bugs.
