### ISSUE TITLE
Ray Java could not build

### ISSUE THREAD

**Issue by compete369** [ray-project/ray#6011]
I got to build Ray Java  through Docker with the ENV  RAY_BUILD_JAVA=1     , however the exception appeared like this: 
- /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/rules_jvm_external/defs.bzl:59:5
     - /root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/com_github_ray_project_ray/java/dependencies.bzl:4:5
     - /ray/bazel/ray_deps_build_all.bzl:12:3
     - /ray/WORKSPACE:9:1
    ERROR: An error occurred during the fetch of repository 'maven':
       Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
    Analyzing: 28 targets (69 packages loaded, 1394 targets configured)
    ERROR: /ray/java/BUILD.bazel:50:1: no such package '@maven//': Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
     and referenced by '//java:org_ray_ray_runtime_test'
    ERROR: /ray/java/BUILD.bazel:50:1: no such package '@maven//': Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
     and referenced by '//java:org_ray_ray_runtime_test'
    ERROR: /ray/java/BUILD.bazel:50:1: no such package '@maven//': Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
     and referenced by '//java:org_ray_ray_runtime_test'
    ERROR: /ray/java/BUILD.bazel:50:1: no such package '@maven//': Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
     and referenced by '//java:org_ray_ray_runtime_test'
    ERROR: Analysis of target '//java:org_ray_ray_runtime_test' failed; build aborted: no such package '@maven//': Error while fetching artifact sources with coursier: Error getting scaladex infos:
      download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 403 for URL: https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=true&target=JVM&scalaVersion=2.12.7
    INFO: Elapsed time: 27.772s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (69 packages loaded, 1394 targets configured)
    FAILED: Build did NOT complete successfully (69 packages loaded, 1394 targets configured)

Pls advice me, thanks very much!

**Comment by jin** [comment]
rules_jvm_external 1.2 was broken by some upstream changes, https://github.com/ray-project/ray/pull/6033 fixes this.
