### ISSUE TITLE
Ray serve could not work as desired

### ISSUE THREAD

**Issue by compete369** [ray-project/ray#6012]
The first simple echo.py,  but I got the following error:

{
    "error": "Path /echo not found. Please ping http://.../ for routing table"
}

...Sleeping for 2 seconds...
(pid=11809) INFO: ('127.0.0.1', 34444) - "GET /echo HTTP/1.1" 404
{
    "error": "internal error, please use python API to debug"
}

**Comment by richardliaw** [comment]
cc @simon-mo

**Comment by simon-mo** [comment]
Should be fixed on latest master, if not please reopen
