### ISSUE TITLE
time_this_iter_s >> sample_time_ms + grad_time_ms + update_time_ms

### ISSUE THREAD

**Issue by gohsyi** [ray-project/ray#6029]
# Describe the problem

In my experiment, `time_this_iter_s` is much larger than `sample_time_ms + grad_time_ms + update_time_ms`. 

I wonder how these time intervals are computed, what are the exact meanings of them, and on what the remaining time `time_this_iter_s - sample_time_ms - grad_time_ms - update_time_ms` spends.

**Comment by internetcoffeephone** [comment]
The same happens for me. I did some initial profiling using [yappi](https://github.com/sumerc/yappi), but I'm not seeing any obvious culprit yet.

An interesting detail is that when I reduce the complexity of my model from 120000 trainable parameters to <100, the model trains at the same speed.

This leads me to believe that either I'm just running into a wall of overhead, or my custom environment is exceedingly slow. Any recommendations on how to tease this out?

**Comment by internetcoffeephone** [comment]
The reason for my training speed hardly reacting to trainable parameter reduction turned out to be unrelated - it was the following: [Vectorization within a single process](https://ray.readthedocs.io/en/latest/rllib-env.html#performance), providing a 4-5x speedup:

> Vectorization within a single process: Though many envs can achieve high frame rates per core, their throughput is limited in practice by policy evaluation between steps. For example, even small TensorFlow models incur a couple milliseconds of latency to evaluate. This can be worked around by creating multiple envs per process and batching policy evaluations across these envs.
> You can configure {"num_envs_per_worker": M} to have RLlib create M concurrent environments per worker. RLlib auto-vectorizes Gym environments via VectorEnv.wrap().
