### ISSUE TITLE
[rllib] Add examples for attention network models

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6030]
For example, the Numpad / memory maze experiments in https://arxiv.org/pdf/1910.06764.pdf

cc @gehring

**Comment by waldroje** [comment]
that would be awesome if you guys tackled this... would love to see such an example....

**Comment by gehring** [comment]
@waldroje This is a priority for us so, barring anything major, it will get done! I can't give you a concrete estimate for when this will be completed but it should be relatively soon, hopefully within a month or so.

**Comment by waldroje** [comment]
Looking forward to checking out the Transformer! Thanks a lot for all the hard work!
