### ISSUE TITLE
[core worker] Python runtime should return RayObject* for returns instead of putting directly

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6031]
As a followup for https://github.com/ray-project/ray/pull/5991, we should avoid doing puts for task returns from the Python runtime directly. We should instead return RayObject* back to the core worker runtime, as is done for direct actor calls.

This has to be done for several types of objects handled in Python code right now: pyarrow, pickle5, raw bytes.

cc @zhijunfu @edoakes

**Comment by edoakes** [comment]
Agreed, that would be great. What we need to do to keep the same low-cost serialization is (1) add a `WriteTo(buffer)` method to the `RayObject` interface and then implement it in cython by pulling in the `SerializedPyObject` from pyarrow and whatever the equivalent is in pickle5.
