### ISSUE TITLE
Performance regression testing.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#606]
We should set up automated tests to catch performance regressions. A tool like https://github.com/spacetelescope/asv may be the way to go.

**Comment by gycn** [comment]
What type of benchmarks should be run?

**Comment by robertnishihara** [comment]
Things like.

1. Given a remote function

    ```python
    @ray.remote
    def f():
        return 1
    ```

    How long does it take to call `f.remote()`? How about `ray.get(f.remote())`. How about `ray.get([f.remote() for _ in range(10000)])`

2. How long does it take to call `x_id = ray.put(1)`? How about `ray.get(x_id)`? Try using other objects (including large objects) intstead of `1`.

3. How long does it take to create an actor? How long does it take to create an actor, submit one task, and get the result?

I'd start with a few microbenchmarks like the above. As a first pass, it's not important to be comprehensive. Instead we should get the framework in place so that more benchmarks can be added.

I'd take a look at how Arrow uses ASV https://github.com/apache/arrow/search?utf8=%E2%9C%93&q=asv&type=.

**Comment by gycn** [comment]
Should the ASV website be hosted on Github Pages?

**Comment by robertnishihara** [comment]
That's a reasonable option. I'd look into what Arrow and other projects do.

**Comment by gycn** [comment]
It looks like Arrow doesn't host the actual ASV website. I'll take a look at other projects.

**Comment by robertnishihara** [comment]
We can also separate out setting up the framework from hosting it. E.g., hosting it can be done as a later, but if we can already run the tests that'd be useful.

**Comment by gycn** [comment]
Ok, I'll finish up writing up the tests and make a pull request.

**Comment by gycn** [comment]
Should I add the ASV files to the Ray codebase or add instructions to clone the repo from github and set it up?

**Comment by robertnishihara** [comment]
The `setup.py` should probably stay where it currently is. Can you take a look at how Arrow handles this? Because Arrow's `setup.py` is not in the root directory, so there should be a way to get it to work.

And I'd suggest adding the ASV files to the Ray codebase (along with instructions for how to use ASV).

**Comment by robertnishihara** [comment]
The basic infrastructure for this has been set up now. https://github.com/ray-project/ray/tree/master/python/benchmarks
