### ISSUE TITLE
Create minimal web UI for debugging and for understanding performance.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#607]
We had an earlier attempt at a web UI, but no one used it, so we removed it in #554. Some problems with the previous UI:

- Installing it was difficult because it depended on node/polymer/bower.
- It required Python 3 which was a source of headaches.
- We had limited javascript expertise, so development was slow.

However, having a good UI is extremely valuable (e.g., see the UI's for Spark, Dask, TensorFlow, rllab). For example, we should be able to use the UI to answer questions like the following.

- My application failed, what went wrong?
- My application is slow, how can I make it faster?

We should create a simple UI to get something up and running that can help answer those questions. Note that the short-term solution may be different from the long-term solution. For example, maybe the "right" way to do it in the long run is React + D3. But it may still make sense to build a simpler version (e.g., based on a Jupyter notebook or Bokeh) to help flesh out the design and understand the requirements even if we end up rewriting it later.

cc @ericl @yifanwu

**Comment by mitar** [comment]
I would use node.js + Vue, reading from Redis directly. Depending how much information is kept in Redis?

I might be interested in helping here. I have quite some web experience. :-)

**Comment by robertnishihara** [comment]
There could potentially be tons of information in Redis (e.g., if a workload starts a million tasks, then there might be a gigabyte of data).

We're still working on figuring out what information to show, and @alanamarzoev has been thinking about this a lot. At a high level, the information needs to answer the questions 

1. Why is my application failing and how can I fix it?
2. Why is my application slow and how can I fix it?

Concretely, this includes things like the following.

- Log files for all the workers and other processes (and mechanisms for searching these logs).
- Timeline information about which tasks were scheduled on which workers/machines, when they were scheduled, and how long they took. Further breakdowns of how much time each task spent executing the task versus storing results in the object store.
- Error messages for tasks that threw exceptions. Links to the relevant places in the log files from these tasks.
- A graph depicting the dependencies between the tasks.
- Statistics to show how well balanced the load was across machines.
- Statistics to show much much data was transferred.
- Statistics to show how much time was spent doing computation.
- Statistics about the slowest tasks.
- Information about which objects live on which machines.
- For each "job", information about whether the job succeeded, failed, is still in progress, how long it took.
- Information about how many nodes are in the cluster, how many CPUs/GPUs there are.
- Information about nodes that have died and been removed from the cluster.

A lot of this information is available in Redis, though some of it is currently not (e.g., we aren't logging statistics about object transfers at the moment).

**Comment by robertnishihara** [comment]
The initial Jupyter notebook based solution is working and is fairly feature complete. There are things that could be added of course, but those can be tracked in separate issues.

cc @alanamarzoev

**Comment by gatapia** [comment]
@robertnishihara can you post a link to the jupyter notebook you mentioned?

**Comment by robertnishihara** [comment]
Yes, that's it.
