### ISSUE TITLE
Actor doesn't return promptly when it is passed to handles

### ISSUE THREAD

**Issue by zachary62** [ray-project/ray#6077]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google cloud OS image  Deep Learning Image: TensorFlow 1.15.0 m38 TensorFlow 1.14.0 with CUDA 10.0 and Intel® MKL-DNN, Intel® MKL.
- **Ray installed from (source or binary)**:  binary
- **Ray version**: 0.7.6
- **Python version**: 3.5.3
- **Exact command to reproduce**: run Passing Around Actor Handles from https://ray.readthedocs.io/en/latest/actors.html

### Describe the problem

Counter values aren't printed in real-time (one per second). It gets stuck for a long while until all the counter handles f finish their increments and print the counter value of Counter at the moment it was called.  
My version is a quicker test. If I execute all the codes below at one time, ray.get waits for 10 seconds and returns small value like 2. If I call ray.get again, it immediately returns 20. It seems that ray.get already has the right value at that moment but doesn't return promptly and waits for a long while.

The problem doesn't appear if I only pass counter to one handle.

### Source code / logs

```
@ray.remote
class Counter(object):
    def __init__(self):
        self.counter = 0

    def inc(self):
        self.counter += 1

    def get_counter(self):
        return self.counter
@ray.remote
def f(counter):
    import time
    for _ in range(10):
        time.sleep(1)
        counter.inc.remote()

counter = Counter.remote()
f.remote(counter)
f.remote(counter)

ray.get(counter.get_counter.remote())
```

**Comment by zachary62** [comment]
It turns out to be the cluster setting problem. I used a cluster with two nodes and the scheduler doesn't switch tasks while sleeping. Now I add another node and the handle returns promptly.

However, I'm still a bit confused why, for the small cluster, it returns the small value. Shouldn't it wait until all handles to finish and return 20?

**Comment by llan-ml** [comment]
When you call `f.remote(counter)`, the main process is not stuck. Thus, when you call `ray.get(counter.get_counter.remote())`, the counter is still counting.

**Comment by zachary62** [comment]
> 
> 
> When you call `f.remote(counter)`, the main process is not stuck. Thus, when you call `ray.get(counter.get_counter.remote())`, the counter is still counting.

Yeah, I understand that remote() function is asynchronous and counter is counting in the background. My problem is how the ray.get(counter.get_counter.remote()) is scheduled.

One possibility is that all cores are busy and get counter is waiting for the previous tasks to finish. Therefore, the process should look like:

Counter +1
Counter +1
...
Get Counter

However, in this case, Get Counter should wait a long while and return 20.

Another scenario (when there are enough cores):

Counter +1
Counter +1
Get Counter
...
Counter +1

In this case, Get Counter should wait a short while and return 2.

What confuses me is that, when there are not enough cores for my cluster, Get Counter wait a long while and return 2. How come?
