### ISSUE TITLE
[rllib] setup-dev.py creates bad symlinks

### ISSUE THREAD

**Issue by sytelus** [ray-project/ray#6089]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubutu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0
- **Python version**: 3.7.8
- **Exact command to reproduce**: /ray/python/setup-dev.py

### Describe the problem
I'm following [instructions to run setup-dev.py](https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install). After running `ray/python/ray/setup-dev.py` and entering yes for all confirmations, I get the following. Notice that symlinks point to itself causing infinite recursion for all symlinks except for rllib. So trying to ls in to tune or autoscaler fails as shown at the end of the image.

![image](https://user-images.githubusercontent.com/2096835/68182649-d2c26d00-ff4e-11e9-8ffd-576741f1ae24.png)

Am I running setup-dev.py incorrectly or is this expected behavior?

### Source code / logs
Looking at [the code](https://github.com/ray-project/ray/blob/master/python/ray/setup-dev.py), `do_link` function has `local_path` defaulted to `''` which explains symlink pointing to itself.

**Comment by ericl** [comment]
I think this is since you already have a source install. Probably if you only had a binary install it would link to the right paths?

**Comment by sytelus** [comment]
After installing ray from source as [these instructions](https://ray.readthedocs.io/en/latest/installation.html), rllib is already symlinked: `rllib -> ../../rllib/`.

So I suppose if you followed above instructions, `setup-dev.py` is not required. It would be nice to document and clarify [here](https://ray.readthedocs.io/en/latest/rllib-dev.html#development-install) exactly how to use rllib in development mode, i.e., installed from source. I think many folks would want to tweak algos/model or understand code by tweaking so this would avoid going through unnecessory hoops.
