### ISSUE TITLE
[rllib] significant performance difference between Torch and TF policy

### ISSUE THREAD

**Issue by zplizzi** [ray-project/ray#6102]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.4
- **Python version**: 3.6.4
- **Exact command to reproduce**: test provided

### Describe the problem

Running the same A3C policy evaluation gives dramatically different performances using the Torch vs the TF policy. Below I provide a test script that performs an experiment computing the iteration time to generate a batch of samples on 1 and 4 remote workers (on the same machine) between Torch and TF. Results are summarized here:

1 worker, TF: .44 sec/batch
4 worker, TF: .55 sec/batch
1 worker, Torch: .62 sec/batch
4 worker, Torch: **18.04 sec/batch**

I suspect that the issue is due to thread contention in Torch - when I run the 1 worker example in TF, I only see one thread executing, but in Torch it saturates all the cores on my machine. I've tried `set_num_threads(1)` but this doesn't seem to get applied to remote workers, and I'm not sure how to do that.

The test was performed on an AWS machine with 8 vCPUs (4 cores).

### Source code / logs
```python
import time
import ray

import ray.rllib.evaluation
import gym
from ray.rllib.models.catalog import MODEL_DEFAULTS
from ray.rllib.agents.ppo.appo import DEFAULT_CONFIG
from ray.rllib.agents.a3c.a3c_torch_policy import A3CTorchPolicy
from ray.rllib.agents.a3c.a3c_tf_policy import A3CTFPolicy

##

def build_worker(policy, remote=True):
    model_config = MODEL_DEFAULTS
    model_config["dim"] = 42
    model_config["framestack"] = True
    policy_config = DEFAULT_CONFIG

    if remote:
        constructor = ray.rllib.evaluation.RolloutWorker.as_remote().remote
    else:
        constructor = ray.rllib.evaluation.RolloutWorker

    worker = constructor(
        env_creator=lambda _: gym.make("PongNoFrameskip-v4"),
        policy=policy,
        model_config=model_config,
        policy_config=policy_config,
        batch_steps=128,
        num_envs = 1)

    return worker

def sample(workers, remote):
    if remote:
        samples = [worker.sample.remote() for worker in workers]
        samples = [ray.get(sample) for sample in samples]
    else:
        samples = [worker.sample() for worker in workers]
    return samples


def run_exp(num_workers, policy, remote, n):
    workers = [build_worker(policy = policy, remote=remote) for _ in range(num_workers)]
    # Warm up
    for i in range(5):
        sample(workers, remote)

    # Run test
    start = time.time()
    for i in range(n):
        sample(workers, remote)
    iter_time = (time.time() - start) / n
    print(f"Results: {num_workers}, {policy}, {remote}, {n}: {iter_time}")


ray.init(ignore_reinit_error=True)

run_exp(1, A3CTFPolicy, remote=True, n = 10)
run_exp(1, A3CTorchPolicy, remote=True, n = 10)

run_exp(4, A3CTFPolicy, remote=True, n = 10)
run_exp(4, A3CTorchPolicy, remote=True, n = 10)
```

**Comment by zplizzi** [comment]
Looks like it was the threading issue. If I substitute in the following class, the performances are as follows:

```python
class RolloutWorkerFix(ray.rllib.evaluation.RolloutWorker):
      def __init__(self, env_creator, policy, model_config, policy_config,
                   batch_steps, num_envs):
          torch.set_num_threads(1)
          super().__init__(env_creator, policy, model_config=model_config,
                           policy_config=policy_config, batch_steps=batch_steps,
                           num_envs=num_envs)
```

1 worker, TF: .41 sec/batch
4 worker, TF: .51 sec/batch
1 worker, Torch: .42 sec/batch
4 worker, Torch: .53 sec/batch

Is there a more elegant way to do this?

**Comment by ericl** [comment]
Perhaps we should be automatically setting torch num threads in the rollout worker? There is a similar issue with TensorFlow, which we have worked around by setting the TF op parallelism to 2 on workers and 8 on the trainer only.

**Comment by zplizzi** [comment]
Yeah I'm not really certain what the exact failure mode is (seems surprising that threads thrashing around would cause 40x perf penalty) - but setting a safe default and perhaps allowing a flag to override seems reasonable to me.
