### ISSUE TITLE
out-of-memory due to all actors are constructed on just one machine in a Ray-enabled cluster of 4 machines.

### ISSUE THREAD

**Issue by albertghtoun** [ray-project/ray#6106]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0.dev5
- **Python version**: 3.6.9
- **Exact command to reproduce**: N/A

### Describe the problem

I encountered out-of-memory error when I am using Ray to train parameter servers with vgg model. I created 16 workers  (16 actors in Ray) to compute gradients for the training. While all 16 actors are constructed successfully but the compute_gradient() function causes the out-of-memory error. I looked into the behavior of Ray in terms of where actors methods are executed. As far as
I know of, the actor methods are invoked at the same machine where the actor object was constructed.  However, all 16 actors are constructed at the same machine even though my Ray cluster has 4 machines. I am wondering if you can let me know how I can change Ray such that the machine on which to construct actors can be spread to all Ray-enabled machines in my cluster instead of all constructed on the same machine.

Thanks!

**Comment by richardliaw** [comment]
How many CPUs are in each machine? You can specify so that your each actor has 1/4 of a machine's resources.

**Comment by albertghtoun** [comment]
Thanks for the quick response! 

In our cluster, each machine has 16 cpus and 64 GB memory. In my driver python program, I specified that each actor uses 10 GB / 64 GB memory  by placing @ray.remote(memory=10240 * 1024 * 1024) decorator ahead of each actor class definition.  Also, I am planning to create 16 such actors, hoping that some actor can be constructed on other machines in the ray cluster (4 connected machines).  But I encountered the following errors popped up when running my driver program:

> 2019-11-12 01:52:53,939 WARNING worker.py:1619 -- The actor or task with ID ffffffffffff2223f7ff01000000 is pending and cannot currently be scheduled. It requires {memory: 10.009766 GiB} for execution and {CPU: 1.000000}, {memory: 10.009766 GiB} for placement, but this node only has remaining {CPU: 16.000000}, {memory: 6.250000 GiB}, {object_store_memory: 12.500000 GiB}. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster.
