### ISSUE TITLE
Cyclic reference in modified numpy arrays causes object store pinning

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#6112]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.14.6
- **Ray installed from (source or binary)**: Both
- **Ray version**: 0.6.0 onwards
- **Python version**: Python 3.7.4
- **Exact command to reproduce**: See example below.

### Describe the problem
The below script should run successfully because previous iterations' objects should be evicted to make room for the new ones once the object store is filled. However, the objects are mistakenly pinned so they can't be evicted and the loop fails after a few iterations.

This only happens when a numpy array is input into the function, modified, and returned. It seems to be caused by a cyclic dependency because adding the `gc.collect` call solves the issue.

### Source code / logs
```
import numpy as np

import ray
ray.init(object_store_memory=10 * 1024 * 1024)

@ray.remote
def shuffle(input):
    x = np.random.shuffle(input)
    # If the below line is uncommented, the object isn't pinned.
    # import gc;gc.collect()
    return x

for _ in range(10):
    ray.get(shuffle.remote(np.zeros(2 * 1024 * 1024, dtype=np.uint8)))
```

**Comment by edoakes** [comment]
cc @pcmoritz

**Comment by edoakes** [comment]
Note that using the new pickle serialization also solves the issue, so we should prioritize enabling that by default.

**Comment by ericl** [comment]
Does it make sense to merge https://github.com/ray-project/ray/pull/6114 as a workaround?

**Comment by pcmoritz** [comment]
Yeah, I think so!
