### ISSUE TITLE
Passing ObjectID as a function argument in local_mode is broken

### ISSUE THREAD

**Issue by alex-petrenko** [ray-project/ray#6115]
### System information
- **OS Platform and Distribution**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.7
- **Exact command to reproduce**: see below

### Describe the problem
The argument passing behavior with local_mode=True vs False seems to be different.
When I run the code snippet below:

```import ray
ray.init(local_mode=True)  # Replace with False to get a working example

@ray.remote
def remote_function(x):
    obj = x['a']
    return ray.get(obj)


a = ray.put(42)
d = {'a': a}
result = remote_function.remote(d)
print(ray.get(result))
```

With local_mode=False I get output `42`, as expected.
With local_mode=True I get the following error:

```
Traceback (most recent call last):
  File "/home/alex/all/projects/doom-neurobot/playground/ray_local_mode_bug.py", line 13, in <module>
    print(ray.get(result))
  File "/home/alex/miniconda3/envs/doom-rl/lib/python3.7/site-packages/ray/worker.py", line 2194, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): /home/alex/miniconda3/envs/doom-rl/bin/python /home/alex/all/projects/doom-neurobot/playground/ray_local_mode_bug.py (pid=2449, ip=10.136.109.38)
  File "/home/alex/miniconda3/envs/doom-rl/lib/python3.7/site-packages/ray/local_mode_manager.py", line 55, in execute
    results = function(*copy.deepcopy(args))
  File "/home/alex/all/projects/doom-neurobot/playground/ray_local_mode_bug.py", line 7, in remote_function
    return ray.get(obj)
  File "/home/alex/miniconda3/envs/doom-rl/lib/python3.7/site-packages/ray/local_mode_manager.py", line 105, in get_objects
    raise KeyError("Value for {} not found".format(object_id))
KeyError: 'Value for LocalModeObjectID(89f92e430883458c8107c10ed53eb35b26099831) not found'
```
It looks like the LocalObjectID instance inside `d` loses it's field `value` when it gets deep copied during the "remote" function call (currently it's `local_mode_manager.py:55`). It's hard to tell why exactly that happens, looks like a bug.

**Comment by alex-petrenko** [comment]
Indeed, this example seems to confirm that it might be a `deepcopy` problem:

```
import ray
ray.init(local_mode=True)

a = ray.put(42)

from copy import deepcopy
a_copy = deepcopy(a)
print(ray.get(a))
print(ray.get(a_copy))
```

I get `42` printed and then an error upon attempting to `ray.get(a_copy)`. Is this intended?

**Comment by richardliaw** [comment]
Related to #5853?

**Comment by alex-petrenko** [comment]
It is related, and I agree that local_mode should mimic normal operation as closely as possible.
Although probably there's an easier fix for this small issue.

**Comment by alex-petrenko** [comment]
Fixed it temporarily by implementing `__deepcopy__` on `LocalModeObjectID`:

```
    def __deepcopy__(self, memodict={}):
        obj_copy = copy.copy(self)
        content_copy = copy.deepcopy(self.__dict__, memodict)
        obj_copy.__dict__.update(content_copy)
        return obj_copy
```

**Comment by edoakes** [comment]
@alex-petrenko this should be fixed the PR above, can you test it out with the latest wheels once they've built?
