### ISSUE TITLE
Improve MessageWrapper interface

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#6120]
### Describe the problem
The [MessageWrapper](https://github.com/ray-project/ray/blob/master/src/ray/common/grpc_util.h#L13) design has some pretty bad gotchas.

First, it wraps a shared_ptr to a protobuf, which means we're (probably unnecessarily) incrementing/decrementing the pointer every time we copy a `MessageWrapper`. We do this a lot for things like capturing a task spec in a lambda.

Second, you can modify the protobuf underneath by calling a [const method](https://github.com/ray-project/ray/blob/master/src/ray/common/grpc_util.h#L42)! This means that you can be given a `const TaskSpecification &` and then do arbitrary things with it.

We should change this to use a unique_ptr instead of a shared_ptr, and `GetMutableMessage()` should not be a const method.

cc @ericl @edoakes

**Comment by ericl** [comment]
This could be a little tricky since in several places we do actually require sharing references to a TaskSpecification (for example, in WorkerThreadContext).

**Comment by ericl** [comment]
Well, at least the `const` part was easy to fix, so added to https://github.com/ray-project/ray/pull/6075
