### ISSUE TITLE
[autoscaler] Docker fails when re-using cached node

### ISSUE THREAD

**Issue by AdamGleave** [ray-project/ray#6128]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.7.6
- **Python version**: 3.7
- **Exact command to reproduce**:

1. Use Docker with autoscaler on AWS.
2. Wait for a node to be stopped due to being idle.
3. Run any command that will consume resources causing node to be restarted.
4. `ray start` will fail on the new node.

### Describe the problem

Recently support was added in https://github.com/ray-project/ray/pull/5741 to the `AWSNodeProvider` to stop rather than terminate nodes, and then reuse the stopped nodes.

Upon restarting a stopped node, the `initialization_commands`, `head_setup_commands` and `worker_setup_commands` are skipped: only `head_start_ray_commands` or `worker_start_ray_commands` are executed.

Unfortunately, this interacts poorly with `autoscaler/docker.py`: the command to start the Docker container is placed in `head_setup_commands` or `worker_setup_commands`, which is not executed. So the `{head,worker}_start_ray_commands` fail, as no Docker container is currently executing.

This can be fixed by moving the Docker start command into `{head,worker}_start_ray_commands`, but a more fundamental problem is Docker containers are not designed to be persistent. So anything that ran in `{head,worker}_setup_commands` will also need to be re-run.

Thanks to @ericl and @edoakes for discussion on Slack.

### Possible solution

I'm happy to attempt a PR to fix this but am unsure on the best way so would like to get consensus on the API first.

The easiest option is to just disable caching when Docker is used. This would lose some performance as @ericl pointed out on Slack.

An alternative proposal is to change the config to better support this use case. 

In particular, there are three types of commands needed:
  1. Commands that should be run exactly once for a given node, and will persist across reboots. For example, installing a package.
  2. Commands that should be run each time a node is restarted. For example, mounting a remote file share.
  3. Commands that should be run each time Ray is restarted.

Currently `initialization_commands` and `{head,worker}_setup_commads` are both (1), and `{head,worker}_ray_start_commands` are (3). There is no way to specify (2).

When using Docker, we also need to distinguish between commands that should run outside of Docker and commands that should run inside. (1) should never run in Docker as containers are non-persistent. (2) may need to run inside and outside Docker. (3) I think should usually run in Docker but there may be use cases to run it outside as well.

One proposal would be to map 1) onto `initialization_commands`, 2) onto `{head,worker}_setup_commands` and 3) onto `{head,worker}_start_ray_commands`. The difference from the current implementation would be that we now always run 2) after resume.

To distinguish between Docker and non-Docker commands, we could:
  - Introduce an extra key, e.g. `{head,worker}_setup_commands_host`. 
  - Introduce a dummy command, e.g. `no_docker`, which would instruct `docker.py` not to prefix the command with `docker exec`.

**Comment by ericl** [comment]
Thanks for looking at this! At a glance, the proposed change seems quite reasonable. To summarize my understanding of the new semantics:
- Init commands are run once for a given node
- Setup commands are run each time the node restarts
- Start ray commands are run each time Ray restarts

A couple questions about docker:
- Instead of having docker be handled by the autoscaler, does it make sense for the user to explicitly spell out the docker exec? I.e., "docker exec command_to_run" for each docker setup command? We could provide a macro to make this easier.
- What do init commands currently do, are they the host (non-docker) setup commands?

I'm also wondering if this is the right time to clear up the naming of these commands. A straw man would be to remove "init" commands and have:
- {head,worker}_setup_commands: commands run once to setup the node
- on_{head,worker}_restart: commands to run every time a node freshly starts or is rebooted
- start_ray_{head,worker}: commands to run to restart ray

**Comment by richardliaw** [comment]
> Instead of having docker be handled by the autoscaler, does it make sense for the user to explicitly spell out the docker exec? I.e., "docker exec command_to_run" for each docker setup command? We could provide a macro to make this easier.

What would the macro be? I think explicitly spelling out the `docker exec ENVVARS CONTAINERNAME /bin/sh -c '{CMD}'`  is very painful.

**Comment by ericl** [comment]
How about $IN_DOCKER?

**Comment by richardliaw** [comment]
Sounds ok to me; cc @hartikainen @edoakes ?

**Comment by hartikainen** [comment]
Just to make sure I understand correctly: we would have 3 different command options that are all run on the host:
`{head,worker}_setup_commands`
`{head,worker}_restart_commands`
`{head,worker}_start_ray_commands`

And then the user would run docker commands manually by doing:

```yaml
worker_setup_commands:
    - echo "do stuff on the host"
    - $IN_DOCKER echo "do stuff in the container"
```
Should the user be able to define the behavior of `$IN_DOCKER`?

**Comment by ericl** [comment]
Yeah, that sounds good.

**Comment by AdamGleave** [comment]
I'm a little concerned that requiring `${IN_DOCKER}` be specified explicitly will make it hard for new users to set up. Right now for basic configs enabling Docker is as simple as adding a `docker:` section. With this change users would also need to change all of the rest of their setup and start commands. This makes me lean slightly towards instead having a macro `${ON_HOST}` to force things to run not-in-Docker, although the implementation of this would be slightly more magical.

Having said that, I'm OK with `${IN_DOCKER}` too -- in fact I'd slightly prefer it for my own usage.

**Comment by ericl** [comment]
We could also add a 4th docker commands section instead? I.e.
docker_setup_commands.

**Comment by AdamGleave** [comment]
> We could also add a 4th docker commands section instead? I.e. docker_setup_commands.

When would these be run, on restart? 

To confirm I understand, is the idea that we'd have (in the new nomenclature suggested by @hartikainen):
  - `{head,worker}_setup_commands` which always run on the host, exactly once
  - `{head,worker}_restart_commands` which always run on the host, after power cycle
  - `{head,worker}_docker_restart_commands` which always run inside Docker, after power cycle
  - `{head,worker}_start_ray_commands` which run inside Docker if available, otherwise on the host, whenever Ray is restarted

I think this could work OK. Then enabling Docker could be as simple as renaming `*_restart_commands` to `*_docker_restart_commands` in the config.
