### ISSUE TITLE
SyncReplayOptimizer (DQN) time_this_iter_s increases drastically with rising no steps

### ISSUE THREAD

**Issue by carlbalmer** [ray-project/ray#6131]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.6.5
- **Exact command to reproduce**: `rllib train --run=DQN --env=BattleZone-v0`

### Describe the problem
When running DQN `time_this_iter_s` steadily increases with the no of timesteps.

For example in `BattleZone-v0`:

| timesteps_total  | time_this_iter_s (GPU) | time_this_iter_s (CPU)
| ------------- | ------------- | ------------- |
| 10k  | 6 | 18  |
| 1M  | 13  | 24  |
| 2M  | 21  | na  |

The increase seems to happen at the same rate for both GPU and CPU training (and also smaller models e.g. 3-layer MLP). Also the memory usage of the driver increases steadily from ~700MB@step=0 to ~3000MB@step=2M.

I've tried to profile this but without any meaningful insights. The increasing memory usage is strange... **Shouldn't the memory max out when the replay buffer reaches max size?**

**Does someone have an idea what could be causing this?**

### Source code / logs
![Screenshot from 2019-11-10 11-38-39](https://user-images.githubusercontent.com/6771285/68542598-aecbb500-03ae-11ea-9153-d89b0c4cb3cd.png)

- red: BattleZone-v0 CPU
- blue: BattleZone-v0 GPU
- pink: custom env with 3-layer MLP (hidden_size=256)

## Logs
[ray_results_DQN_BattleZone-v0.zip](https://github.com/ray-project/ray/files/3828327/ray_results_DQN_BattleZone-v0.zip)

**Comment by ericl** [comment]
Is it just shared memory usage? That's normal since Ray will max out object store size before garbage collecting any objects.

Slowing down is not expected though. Can you retry with TF 1.15 and the latest wheels and see if this still happens?

**Comment by carlbalmer** [comment]
`Is it just shared memory usage?`
Yes it probably is. I didn't know about the garbage collection.

`Can you retry with TF 1.15`
This is with TF 1.15

`and the latest wheels`
Do you mean he latest wheels of Ray? Where do i get them? Im already on 0.7.6.

**Comment by ericl** [comment]
This is what I see on latest with BattleZone / GPU. I'll let it keep running and see how it goes:

![image](https://user-images.githubusercontent.com/14922/69371032-e90d4000-0c53-11ea-837a-3956e9ea5ad6.png)

You can find the latest wheels here https://ray.readthedocs.io/en/latest/installation.html (pip install -U WHEEL).

**Comment by carlbalmer** [comment]
I can confirm that the slowdown is present on 0.7.6 but no on 0.8.0.dev6.
