### ISSUE TITLE
[rllib] Low utilization GPU

### ISSUE THREAD

**Issue by Magicskys** [ray-project/ray#6132]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 18.04
- **Ray installed from (source or binary)**: pip install ray
- **Ray version**:0.7.6
- **Python version**: 3.6.8
- **Exact command to reproduce**:

### Describe the problem

I have use ray lib to running tensorflow-gpu 1.14 to Deep Reinforcement Learning. However, the
program just only about 10% utilization on GPU. Could I ask how to make high utilization GPU on the running.

### Source code / logs

tune.run(
        'DDPG',
        resume=args.resume_training,
        max_failures=10,
        num_samples=args.num_samples,
        config={'num_workers':1,
        'num_gpus=１}')  

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/4 CPUs, 1/1 GPUs, 0.0/3.91 GiB heap, 0.0/1.32 GiB objects
Memory usage on this node: 10.0/15.6 GiB
Result logdir: /root/ray_results/rllib_example
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - DDPG_CompetitionEnv_0_seed=320:	RUNNING, [2 CPUs, 1 GPUs], [pid=11139], 823 s, 12 iter, 12000 ts, 6.88 rew

**Comment by josjo80** [comment]
@Magicskys I would take a look at the RLlib printout statements during training to see where the time for each iteration is being consumed.  For example, below you can see that most of the time in my training run is spent sampling my custom environment, 397s.  Most likely, you have low GPU utilization because most of your time is spent spinning up and stepping through your environment.
```
info:
    grad_time_ms: 1181.233
    learner:
      Agent_01:
        cur_kl_coeff: 2.541098841762901e-21
        cur_lr: 0.0003000000142492354
        entropy: 0.34306764602661133
        entropy_coeff: 0.009999999776482582
        kl: 0.0038458537310361862
        policy_loss: 0.0016277877148240805
        total_loss: -0.0018028896301984787
        vf_explained_var: 0.9999988675117493
        vf_loss: 1.6113968968056724e-06
    load_time_ms: 93.701
    num_steps_sampled: 10000000
    num_steps_trained: 10000000
    sample_time_ms: 397469.881
    update_time_ms: 20.976
```
