### ISSUE TITLE
Understanding resource allocation `tune.run` vs. `agents.trainer.COMMON_CONFIG`

### ISSUE THREAD

**Issue by mimoralea** [ray-project/ray#6149]
Can someone help me understand how these two resource allocation sections interact?

Here is the `resource_per_trial` variable of the `run` function.
https://github.com/ray-project/ray/blob/master/python/ray/tune/tune.py#L111-L114

These config values are for the `trainer` process.
https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L132-L147

**Comment by ericl** [comment]
The trainer uses the config settings to set resources per trial (in fact, it will raise an error if you try to set the tune resources manually). The resources requested are defined in the various trainer classes by the default_resource_request method.

**Comment by mimoralea** [comment]
Thanks, @ericl. 

A follow-up question. How do the `ray.init` and the `config` settings interact?

I was trying to run a Population-based Training using parallel trials and it worked only when passing the overall resources to `ray.init` and only the resources per trial to `run` function.

For instance, say I have 32 CPUs and 4 GPUs in a machine, then I set the overall resources with:

`ray.init(num_cpus=31, num_gpus=4)`

Then, say I want to run 5 concurrent trials, then I pass to the run function:

```
<...>
    # tunning -1 = 30
    "num_cpus_for_driver": 1,
    # CPUs per worker, to keep it simple: x1
    "num_cpus_per_worker": 1,
    # Workers used for parallelism, 30/5 concurrent trials = 6 workers available
    "num_workers": 6,
    # GPUs for trainer process, (only 1 training process per trial!?!?!?!?!?) 4/5 = 0.8
    "num_gpus": 0.8,
    # Number of GPUs to allocate per worker. (what is this used for? For policy inference in the actors?)
    "num_gpus_per_worker": 0,
<...>
```

Is this the correct way of doing this? Also, can you confirm that a "trial" is the running of a full training process, whatever the number of episodes, whatever the number of steps, correct?

Thanks again for the help.

**Comment by ericl** [comment]
That's right, one trial is one training run / learning curve.

I think the issue you're seeing is that when you request 0.8 GPUs, Ray is
trying to find a GPU that is 80% unallocated. But since all GPUs are 80%
full there is no space left... You would need to do 0.5 GPUs in order to
get more than 4 concurrent trials.

**Comment by mimoralea** [comment]
Ahhh, that's interesting!

Thanks, @ericl. I appreciate you time and insight.
