### ISSUE TITLE
AsyncIO Actor Implementation Plan

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#6153]
This issue documents design for asyncio based actors. We should enable the following behavior:

```python
@ray.remote
class AsyncActor:
	async def async_task(self):
		print("running task")
		await asyncio.sleep(10)
		print("done running task")

actor = AsyncActor.options(is_direct_actor=True, is_async=True).remote()

for _ in range(3):
	actor.async_task.remote()
```

It should print out:
```
running task
running task
running task
... # 10 seconds later
done running task
done running task
done running task
```

All async methods will be running in the same python asyncio event loop.

**Comment by ericl** [comment]
Is async def required, or can any ordinary method be run into the event loop?

**Comment by simon-mo** [comment]
We can choose to 
1. Run ordinary method directly and return the result
2. Wrap ordinary method as async and run in the same event loop.

**Comment by ericl** [comment]
I see, the latter probably makes more sense, so that you can have a single class def and choose between threaded and event loop execution with just a config option change.

**Comment by simon-mo** [comment]
Here are two approaches:

### Approach 1, split _raylet.pyx:execute_task into start_execute and finish_execute.

The call stack of direct actor call is as follows:
1. direct_actor_transport.h::SchedulingQueue::ScheduleRequests:

https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/src/ray/core_worker/transport/direct_actor_transport.h#L270-L275

2. The `request.Accept` calls a `accept_callback` which is set to lambda in `CoreWorkerDirectTaskReceiver::HandlePushTask`

https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/src/ray/core_worker/transport/direct_actor_transport.cc#L253-L301

3. The `task_handler_` variable was set from constructor, which was set from CoreWorker's constructor:
https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/src/ray/core_worker/core_worker.cc#L112-L113

4. CoreWorker's constructor was called inside `_raylet.pyx`

https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/python/ray/_raylet.pyx#L714-L720

4. The `task_execution_handler` function was also inside `_raylet.pyx` and it wraps `execute_task`
https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/python/ray/_raylet.pyx#L626-L641

5. `execute_task` is a long function with several layers of try catch and context manager. https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/python/ray/_raylet.pyx#L480-L487

6. Finally the function getting called is a closure wrapper actor:
https://github.com/ray-project/ray/blob/f3f86385d631de254c66ea910c1e086587e5429f/python/ray/_raylet.pyx#L549-L550

-----------

The advantage of splitting task_execution into two pieces is that we can be fully asynchronous. But this changes at least three stacks (direct_call, core_worker, python) and might bring unexpected bugs. Here is another proposal that requires less change.

------------

### Approach 2: Running two event loops. 
- We can host a single thread in cpp (just like boost::asio::thread_pool) for concurrent call. This thread will run many `request.Accept()` with [boost::fiber](https://www.boost.org/doc/libs/1_67_0/libs/fiber/doc/html/index.html). `boost::fiber` is user land threads with cooperative context switching. 
- The python worker also need to host an event loop to run coroutines. 
- We just need to make the following changes:

    1. In `request.Accept`, run it inside a fiber in the fiber runner thread. 
    2. The fiber will yield when the async actor method was enqueued into a python event loop. 
    3. The enqueued task should return a python asyncio future, we add a done_callback to the future to awaken the fiber and we can continue the execution like storing results. 

------------

This approach has minimal code path changes and should be straightforward to implement.

**Comment by simon-mo** [comment]
Going with Approach #2, will worry about ray.get inside the coroutine because if it goes through direct actor call, direct actor call might have some locks/mutexs.

**Comment by simon-mo** [comment]
General idea:

![Async Actor Call](https://user-images.githubusercontent.com/21118851/68906508-5b809c00-06f9-11ea-9797-f5c8791b4d80.png)

**Comment by raulchen** [comment]
It seems that the main goal is to **execute multiple actor tasks concurrently in an event loop**, right?

 Do we also want to support **await-calling ray APIs**, e.g. `await ray.async_get(...)`, and `ray.async_wait(...)`? Because we need to make sure all Ray APIs are async compatible, otherwise they will block the event loop.

**Comment by ericl** [comment]
Ideally, a normal ray.get would yield the fiber. This ensures that existing Ray code can be run transparently within the async API.

For advanced users, we should also have a version of get that returns a future. This allows for composition with other async primitives, but requires the user to write code explicitly targeting async actors.

**Comment by pcmoritz** [comment]
This has been implemented.
