### ISSUE TITLE
Does BayesOptSearch support tuning discrete parameters??

### ISSUE THREAD

**Issue by JiayuanSternLi** [ray-project/ray#6167]
### System information
- Linux Ubuntu 16.04)
- **Ray installed from  binary
- **Ray version**: 0.8.0dev6
- **Python version**: 3.7.4
- **Exact command to reproduce**:

### Describe the problem

From the source code of both [https://github.com/fmfn/BayesianOptimization](BayesOpt) and ray.tune, the "space" argument of BayesOptSearch could only be the continues function. Thus our ray.tune currently doesn't support tuning discrete hyper-parameters like optimizer_choice, activation_choice, loss_function_choice, right??
And a better way to tuning all hyper-parameters is to random search discrete parameters combined with bayesopt the continues parameters. Is my understanding correct or do we have any better approaches?

**Comment by richardliaw** [comment]
Looks like the BayesOpt authors suggest that you just treat it as continuous parameter - https://github.com/fmfn/BayesianOptimization/blob/d34f890cfbe4125b1da76790970c3838e9fd5a21/examples/advanced-tour.ipynb

**Comment by JiayuanSternLi** [comment]
> Looks like the BayesOpt authors suggest that you just treat it as continuous parameter - https://github.com/fmfn/BayesianOptimization/blob/d34f890cfbe4125b1da76790970c3838e9fd5a21/examples/advanced-tour.ipynb
It only works for those discrete numerical parameters like layer numbers, but doesn't work for True or False, and strings
