### ISSUE TITLE
"Ray start" outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by JovanCe** [ray-project/ray#6196]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.6 LTS (Xenial Xerus)
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.5
- **Python version**: 3.7.3
- **Exact command to reproduce**: ray start

### Describe the problem
When I start ray with "ray start" (with or without --head) and it runs successfully, it always logs the redis address info and instructions to stderr instead of stdout. Is this intended behaviour?

**Comment by JovanCe** [comment]
If I start a node with "--include-webui" then everything is logged to stderr, except the webui url which is logged to stdout. This doesn't make sense to me. I'm writing a script for cluster management on our local servers and I'm relying on these outputs to track errors and parse for address and other relevant info.

**Comment by richardliaw** [comment]
Yep, this is expected behavior to avoid cluttering application outputs.
