### ISSUE TITLE
[tune] Tensorboard without tensorflow

### ISSUE THREAD

**Issue by jacekplocharczyk** [ray-project/ray#6206]
Hi,
I started to play around with ray and I have some issues with using it in docker container without tensorflow installed.

The problem is that tensorboard doesn't show any data without tensorflow installed even on PyTorch examples. I've checked the log dir (`ray_results`) and there weren't any `tfevents` files.

I've prepared example from your documentation and sufficient enough Docker container - 
https://github.com/MIMUW-RL/ray-examples/tree/tensorboard-fail

To see not working example just run the commend from the README file.

If you replace `mnist_test.sh` file by `mnist_test_working_tensorboard.sh` (which at the start install tensorflow) tensorboard will show the data.

Could you provide a way to use tensorboard with tensorflow installed?

Thanks!

**Comment by richardliaw** [comment]
Can you try using the TensorBoardX logger? https://ray.readthedocs.io/en/latest/tune-usage.html#tbxlogger-tensorboardx

**Comment by ericl** [comment]
^^ Yeah, we should consider making tbx the default logger.

**Comment by jacekplocharczyk** [comment]
Hi,
Thanks for you responses.
I've just tried using TensorBoardX and I failed. I can't install `tensorboardx` and I couldn't find similar problem on web.

What I did:
1. I've added `tensorboardx` in `requirements.txt` to install it with pip
2. I've built new docker image
3. I've added `from ray.tune.logger import TBXLogger
` and `loggers=[TBXLogger]` argument to `tune.run(*)` 

What I get is ImportError:
```
  File "/root/examples/tune/mnist_hyperparameters/mnist_hyperparameters.py", line 4, in <module>
    from ray.tune.logger import TBXLogger
```

I've updated failing branch if you want to look closer https://github.com/MIMUW-RL/ray-examples/tree/tensorboard-fail

**Comment by richardliaw** [comment]
The tensorboardx installation can be found here: https://github.com/lanpa/tensorboardX#install

Your import error can be mitigated if you install the latest nightly version of Ray - https://ray.readthedocs.io/en/latest/installation.html. Tensorboardx support was added recently.

**Comment by richardliaw** [comment]
Can you try updating/using the latest version and then letting me know if it works?

**Comment by jacekplocharczyk** [comment]
@richardliaw it worked. Thanks!

I get some warning of tensorflow missing but it's OK.
```
2019-11-22 11:28:01,239 WARNING logger.py:413 -- Could not instantiate tf2_compat_logger: No module named 'tensorflow'.
```
