### ISSUE TITLE
`ray down` stops the nodes instead of terminating

### ISSUE THREAD

**Issue by wjaskowski** [ray-project/ray#6207]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.8dev6
- **Python version**: 3.7
- **Exact command to reproduce**: ray up & ray down

### Describe the problem
In ray 0.7.4 the `ray down` command was terminating nodes but now (in 0.8dev6) it is stopping them (ec2 AWS). Is that an intended behavior? I would prefer terminating nodes, personally.

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
There's still the option to terminate (it will print out the message telling you to disable node caching). Most users want caching for performance, as the cost if stopped nodes is quite minimal.

**Comment by wjaskowski** [comment]
Thanks for the info! 

Indeed, there is an info but I did not notice it since ray usually generates a lot of logs and I read them only if something fails, which is, of course, my fault. 

```INFO node_provider.py:344 -- AWSNodeProvider: stopping nodes ['i-001b5084517a59d44', 'i-0ac43786a7b1b1571']. To terminate nodes on stop, set 'cache_stopped_nodes: False' in the provider config.
```

Let me just say (which you probably already know) that as far as I can see this option is documented only here in the source https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/autoscaler.py#L88

**Comment by wjaskowski** [comment]
@ericl I get the idea of reusing instances but I noticed that when reusing instances the `setup_commands` of ray autocluster are not executed, so this makes things uncovenient when you changed your code and have setup commands that download the code. 

So, is there a good reason for not executing setup commands when reusing instances?

**Comment by ericl** [comment]
Yep, that's a known issue, https://github.com/ray-project/ray/pull/6182 is
addressing it.
