### ISSUE TITLE
ray::Language is too broad

### ISSUE THREAD

**Issue by jonhoo** [ray-project/ray#6212]
For Python, any Python worker can execute any Python task. However, that is not the case for compiled languages. To see why, consider two applications, A and B, that have both been compiled and linked against a hypothetical `libray`, each producing a binary (call them `a` and `b` respectively). Tasks submitted by an A driver will refer to compiled code in `a`, and hence cannot be executed by `b`, and vice-versa. Since Ray currently establishes the legal values for `ray::Language` at compile-time, A and B must both use the same language (let's use a hypothetical `ray::Language::Native`). When a call to `submit_task` now comes in with `language == ray::Language::Native`, Ray needs to find a worker to schedule that task on. However, Ray has no way of doing so. Ray does not know how to spawn a new worker. It has no association between `ray::Language::Native` and `a` or `b`. And even if it did, it would not have a way to distinguish between tasks that should be sent to an `a` worker and those that should be sent to a `b` worker.

I propose that the `ray::Language` discriminator be replaced with a `ray::WorkerTarget`. The new type will be an integer, but _not_ an enum whose variants are dictated at compile-time. Certain well-known values may be established, such as for the default Python worker (which all Python programs would use). At runtime, it should then be possible to register a new `ray::WorkerTarget`. To do so, a command-line argument list should be provided, and Ray will assign it a unique `ray::WorkerTarget` value. Ray will internally associate the two such that if a task ever arrives with the assigned `ray::WorkerTarget`, it will spawn a new worker using the given command if necessary, and route the task to one worker spawned that way. To save implementors some work, it may be useful to have some "auto-added" command-line arguments along the lines of those provided to the Python worker:
https://github.com/ray-project/ray/blob/33c768ebe414c2a2f93a8b8f8637e02b387bb7ea/python/ray/services.py#L1153-L1158

**Comment by stephanie-wang** [comment]
Thanks! This sounds like a good plan.

It seems like each new driver should register its `WorkerTarget` when it first connects. [This](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L995) could be a good place to do it. It writes some information about a newly connected driver that gets broadcasted to all nodes.

**Comment by ericl** [comment]
This sounds great, and is relevant for unrelated features such as multi-tenancy (different users might want be using different Python versions / conda envs, etc).
