### ISSUE TITLE
Resource allocation/return for direct actor call & direct task call

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#6220]
### Describe the problem

@ericl @stephanie-wang 

There were some discussions on this in #6177, but this probably worth a separate discussion so I moved it here:

Traditionally all the tasks are submitted to raylet, and after receiving a task raylet checks for its resource requirement and will only assign it to a worker after the required resources are fulfilled.  By default for a general task we require 1 CPU, for an actor we require 0 CPU for its lifetime source, and 1 CPU for each actor method invocation. @stephanie-wang Please correct me in case of mistakes.

Right now, we already have `direct actor calls` and `direct task calls`, and eventually all the calls are going to be direct. In this case, checking resource requirement for a task via raylet is not possible, since these tasks are no longer going through raylet. 

1. direct actor call:
All the tasks for an actor is submitted directly to that actor, without going through raylet at all. Only the actor creation task will be submitted to raylet.

For this we currently only support lifetime resource requirements for actors, which are specified during actor creation, and per method resources are not supported. And by default we can assume 1 CPU for lifetime resource and 0 CPU for method invocations. Thus we don't need to interact with raylet for the direct actor tasks, which seems fine.

2. direct task call:
We lease a worker for a period of time, and keep sending tasks (of compatible resource requirements) to that worker directly within the lease period, without going through raylet. 

In this case it is natural for raylet to check resource requirements when it receives a request to lease worker. And probably we don't need to return/allocate resources for the subsequent tasks sent within the worker lease?  A trickier part is after we support spillback, in that case a worker can be redirected to a remote raylet and then get a worker lease on that node, then whether the current worker is blocked (e.g. when getting an object) it would be interesting which raylet we want to return the resource to in that case, we leased a worker from a remote raylet, but the leased worker can be still running on the remote node thus it is incorrect to return resources in that case.

**Comment by ericl** [comment]
> but the leased worker can be still running on the remote node thus it is incorrect to return resources in that case.

I think this isn't a problem, since you only block/unblock with your local raylet. So there is never a need to tell a remote raylet that you are blocked.

**Comment by zhijunfu** [comment]
> > but the leased worker can be still running on the remote node thus it is incorrect to return resources in that case.
> 
> I think this isn't a problem, since you only block/unblock with your local raylet. So there is never a need to tell a remote raylet that you are blocked.

Yep, I mean, in that case it should be a NO-OP I think, since we shouldn't return resources to local raylet either.

**Comment by ericl** [comment]
That can cause resource deadlock though: suppose you have one task waiting
on another, but only 1 CPU available.

**Comment by zhijunfu** [comment]
Should be ok for direct task calls? Since raylet checks for resource requirements when we require a worker lease, after that we can keep pushing tasks to the worker, and the worker can execute these tasks, within the lease. 

> That can cause resource deadlock though: suppose you have one task waiting on another, but only 1 CPU available.

**Comment by zhijunfu** [comment]
Sounds like for general tasks (no matter if it's direct) we need to block/unblock as long as the worker is talking to a local raylet.

**Comment by ericl** [comment]
Yeah, otherwise you risk deadlock when-ever you ray.get in a resource constrained graph of tasks.

You can in principle get the same issue with actors, but if they are all created up-front then deadlock is impossible.
