### ISSUE TITLE
[tune] "Resume from local directory" doesn't start new trials

### ISSUE THREAD

**Issue by tamkaho** [ray-project/ray#6227]
I'm optimising some hyperpermeters with hyperopt. I find that if I resume the hyperopt search it would continue to run the existing trials that had been terminated but doesn't start new trials.
How do you get resume to continue creating new trials?

My code is as below:

```
algo = HyperOptSearch(space, max_concurrent=opts.max_concurrent, metric="loss", mode="min")
analysis = tune.run(trainable, num_samples=opts.ntrials, search_alg=algo, resources_per_trial={"cpu": opts.cpu_fraction, "gpu": opts.gpu_fraction},
                        name=opts.name, scheduler=ASHAScheduler(metric=opts.metric, mode="min"),
                        raise_on_failed_trial=False, resume="PROMPT", stop=Stopper().stop, checkpoint_at_end=True)
```

**Comment by richardliaw** [comment]
This is a known issue because Search Algorithms currently does not support resuming. We are working to fix this in #5773.

**Comment by rherman9** [comment]
Hey @richardliaw any update on implementing resuming and starting of new trials when using other Search Algorithms? Like AxSearch or BayesOpt?

**Comment by richardliaw** [comment]
@rherman9 this is actually now supported in master and will be GA in Ray 1.0.
