### ISSUE TITLE
Ray leaks processes on shutdown

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6241]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**: master
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

Try running some command like `./train.py --run=ES --env=CartPole-v0 --config='{"num_workers": 2}'`, and Ctrl-C it after a few seconds. There will be a bunch of processes left alive in the background, which require a `ray stop` to kill.

**Comment by ericl** [comment]
@edoakes is this a known issue for 0.7.7?

**Comment by edoakes** [comment]
Verified solved by #6253
