### ISSUE TITLE
Building from source fails due to `-fuse-ld=--enable-gold` instead of `-fuse-ld=gold`

### ISSUE THREAD

**Issue by sytelus** [ray-project/ray#6256]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: Yes
- **Ray version**: Latest from GitHub source
- **Python version**: 3.7.3
- **Exact command to reproduce**: `pip install -e .`

### Describe the problem
I cloned latest source from GitHub, followed installation instruction exactly as in [docs](https://ray.readthedocs.io/en/latest/installation.html#building-ray-from-source) but the command `pip install -e .` errored out with the following message buried deep inside:

```
x86_64-conda_cos6-linux-gnu-cc: error: unrecognized command line option '-fuse-ld=--enable-gold'; did you mean '-fuse-ld=gold'?
    Target //:ray_pkg failed to build
```
I have gcc 7.4.0. Full build log is attached.

Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1455767

Full log: [build_log.txt](https://github.com/ray-project/ray/files/3883320/build_log.txt)

**Comment by guyk1971** [comment]
I also encountered the same error (similar system setup except with python 3.7.6)

**Comment by olivierp9** [comment]
same with python 3.6.10

**Comment by jonmmease** [comment]
FWIW, I haven't dug in very far but I think this is coming from Bazel: https://github.com/bazelbuild/bazel/issues/9392
