### ISSUE TITLE
[tune] Adding train_acc and eval_acc tag in the layout of result table

### ISSUE THREAD

**Issue by JiayuanSternLi** [ray-project/ray#6270]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**:source 
- **Ray version**: 0.8.0dev
- **Python version**: 3.6
- **Exact command to reproduce**:

### Describe the problem

![image](https://user-images.githubusercontent.com/33815430/69534534-fc523f80-0fb4-11ea-90e4-eacf6af87e1f.png)
what is the acc in the last column, train_acc or test_acc? 
Can we edit the table layout like adding train_acc and eval_acc ?
Thanks

**Comment by ujvl** [comment]
`acc` here refers to `mean_accuracy`, which is whatever you set it to in the `result`.

> Can we edit the table layout like adding train_acc and eval_acc ?

Currently it isn't possible to add custom metrics but I agree that could be useful to have.
