### ISSUE TITLE
Bundled version of Bazel isn't sufficient to install Ray from source

### ISSUE THREAD

**Issue by arkapal1** [ray-project/ray#6274]
Hello,

The docs for building Ray from source (https://ray.readthedocs.io/en/latest/installation.html#install-ray) suggest using the bundled Bazel installer; however, the version of this install is 0.2.3, which is too low to actually build the current version of Ray (0.7.6, also 0.7.5). Bazel's latest release is 1.2.0; after manually installing that, building Ray from source worked fine.

Arka

**Comment by pcmoritz** [comment]
Hey @arkapal1 thanks for the report. I'm not sure if I understand, the bundled Bazel installer should install bazel 1.1.0 (see https://github.com/ray-project/ray/blob/master/ci/travis/install-bazel.sh#L21). There was an older version of that script that installed 0.2.3, but that should not be around any more.

**Comment by robertnishihara** [comment]
Closing. Please feel free to reopen if it's still an issue.
