### ISSUE TITLE
ray submit working directory

### ISSUE THREAD

**Issue by wjaskowski** [ray-project/ray#6288]
Currently, the script in `ray submit [script]` is executed with the working directory somewhere deep in the ray package. This is unexpected if you write some logs for example from the script.

Thus, I propose to change this behaviour and set `$HOME` as the default working directory. 

Would be also nice to have a command-line option to `ray submit` to specify a different working directory where the script should be executed.

**Comment by richardliaw** [comment]
I think the script is already set to execute at `python ~/script.py`?

Can you provide some error logs?

**Comment by wjaskowski** [comment]
Actually, in 0.8dev6 this was changed and the script is executed in an appropriate directory in the `local_dir` ('Local dir to save training results to'). This is probably fine.
