### ISSUE TITLE
[docs] Issue on `deploying-on-slurm.rst`

### ISSUE THREAD

**Issue by lemairecarl** [ray-project/ray#6289]
# Documentation Problem/Question/Comment

This SLURM example seems to assume that `/tmp` is a directory shared by all the nodes. I think this is not generally true. 

While testing this example, I got errors of the kind "could not connect to IPC socket", because the nodes did not share the same temp directory, which contain the communication sockets. To make it work, I had to set `--temp-dir` to a shared location.

(Created directly from the docs)

**Comment by richardliaw** [comment]
Hi @lemairecarl, this is a good point! Would you be interested in patching the docs to point this out? I'd be happy to merge.

**Comment by lemairecarl** [comment]
Sure, I added this to my to do list.

**Comment by jan-matthis** [comment]
Ray seems to work fine for me in a cluster setup without having `temp_dir` set to a shared location. 

Is it generally required that `temp_dir` is shared between nodes, and if so, where is this documented?

**Comment by richardliaw** [comment]
Yeah, we need to clean up these docs. 

`temp_dir` doesn't need to be shared. In fact, nothing actually needs to be shared; files can be moved around using rsync.

**Comment by lemairecarl** [comment]
Doesn't the `temp_dir` contain the communication sockets? If that's the case, the folder obviously needs to be shared.

Since I'm not using Ray myself (I was doing support for someone else), I don't think I'm qualified to drill down on this and/or edit the docs. I'm withdrawing.
