### ISSUE TITLE
Kubernetes Docker Container untagged

### ISSUE THREAD

**Issue by immesys** [ray-project/ray#6294]
The container used by the kubernetes manifests (rayproject/autoscaler) doesn't have any useful tags. Furthermore the contents of the container are actually built using github.com/edoakes/ray and the container is two months old.

It might be better to properly tag the containers with versions and ensure they are built from the main repo (by travis) so that there aren't small differences in the code and it stays up to date.

**Comment by robertnishihara** [comment]
cc @edoakes

**Comment by edoakes** [comment]
#6233 :)
