### ISSUE TITLE
Leaking Worker Memory ignores cap set by ray.init(memory=cap)

### ISSUE THREAD

**Issue by weidler** [ray-project/ray#6310]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18 LTS
- **Ray installed from (source or binary)**: pip installation
- **Ray version**: 0.76
- **Python version**: 3.6.8
- **Exact command to reproduce**: -

### Describe the problem
I am running 6 parallel workers collecting data by exploring gym environments, and saving the collected data into TFRecordFiles. Each worker returns a namedtuple instance with some statistics about the collection. On the main process I initialize ray as follows:

```python
ray.init(local_mode=self.debug, num_cpus=6, logging_level=logging.DEBUG,
           object_store_memory=object_store_memory, memory=(1024.0 ** 3) * 0.5)
```

where object_store_memory is simply my own heuristic that however gives more or less the same as the default one. In a loop of n iterations (where n should in theory be possibly infinitely high) I create workers and get the statistics as follows:

```python
split_stats = ray.get([collect.remote(model_representation, self.horizon, self.env_name, self.discount, self.lam, self.tbptt_length, pid) for pid in range(self.workers)])
```

Now, I have observed that after some number of iterations, my script crashes because there is no more available memory, because the workers take up too much of it. However, what I would expect to happen if together the workers need too much memory in one iteration, it would crash immediately, not after say 200 iterations. I therefore monitored the memory development and indeed memory usage by workers grows with time. Why could this happen? The processes should be absolutely independent of each other, and I expect the memory of a worker to be flushed after finishing its process? The parameters of collect are in order a tuple of a string and a dict with tensorflow model weigths, an integer, a string, a float, another float, an integer and the process id.

I also tried capping the memory with the memory flag in `ray.init()`, but the memory just grows over it anyways. I have attached examples for this.

### Source code / logs
![Selection_136](https://user-images.githubusercontent.com/11197008/69827673-aaa9ef00-1218-11ea-8b28-bf6d68746f67.png)
![Selection_137](https://user-images.githubusercontent.com/11197008/69827675-ad0c4900-1218-11ea-8109-3319f5b58b52.png)

**Comment by ericl** [comment]
Please see: https://ray.readthedocs.io/en/latest/memory-management.html

I suspect all you need to do is set object_store_memory to some lower value like 1GB. Memory growing over time is almost always object store shared memory growth (unless your program is leaking memory).

**Comment by weidler** [comment]
(Sorry for the late reply, was reworking the code that produced the issue)

I do not think that the object_store_memory is the issue. As you can see in the image attached to the issue, the problem are the individual workers. But as I understand the documentation, object_store_memory is shared amongst all workers. In fact, if I limit it to 1GB, the workers memory happily grows over 1GB still, throwing the same error. Maybe this helps:

```
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node weidler-work is used (22.6 / 23.47 GB). The top 10 memory consumers are:

PID     MEM     COMMAND
22126   1.87GiB ray_worker:agent.gather.collect()
22128   1.87GiB ray_worker:agent.gather.collect()
22131   1.87GiB ray_worker:agent.gather.collect()
22124   1.86GiB ray_worker:agent.gather.collect()
22248   1.8GiB  ray_worker:agent.gather.collect()
22298   1.8GiB  ray_worker
22241   1.8GiB  ray_worker:agent.gather.collect()
22255   1.79GiB ray_worker:agent.gather.collect()
2880    1.36GiB /home/weidler/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.5662.18/jbr/bin/java -classpath
22024   0.6GiB  python train.py CartPole-v1 --model rnn --cpu

In addition, up to 0.27 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray, and the max Redis size with `redis_max_memory`. Note that Ray assumes all system memory is available for use by workers. If your system has other applications running, you should manually set these memory limits to a lower value.
```
The shared memory is pretty small actually, but the workers are leaking. However I see no reason how each worker could leak as I would assume their memory is cleared either by pythons gc or the ray backend?

**Comment by ericl** [comment]
Your diagnosis looks right to me (so each worker is using >1.8GiB of memory in the Python heap, not connected to the object store). Is it possible your actor class is holding on to long lived objects that accumulated after each iteration? Actor processes persist forever in Ray.

You can also try using a python memory profiler on the actor class to see which lines are increasing heap memory usage.

**Comment by weidler** [comment]
I am not using an actor class, but only a remote function. So I assume there is nobody (no class) who could hold on to anything? Are the return values of a remote function getting discoupled from the worker with the call to ray.get()?

**Comment by ericl** [comment]
It's possible somehow there is a leak since Ray re-uses workers... You can force Ray to recycle the workers after a number of calls with `@ray.remote(max_calls=5)`.

**Comment by weidler** [comment]
That works! Thank you.

Profiling with guppy revealed that the issue is most likely connected to the interaction between tensorflow and ray. But given that the max_calls argument causes no noticeable execution time, this is a more than valid workaround.

**Comment by eugenevinitsky** [comment]
@ericl, @richardliaw  is there a way to force worker reuse in rllib or tune? I'm wondering if this would solve the issue I am having with memory growth in ray.
