### ISSUE TITLE
Build failure on boost dependency for ppc64

### ISSUE THREAD

**Issue by alanpeixinho** [ray-project/ray#6312]
It seems no default condition is set on attribute defines for boost dependency build

/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/external/boost/BUILD.bazel:1576:1: Configurable attribute "defines" doesn't match this configuration (would a default condition help?).

**Comment by xdever** [comment]
Please see issue https://github.com/ray-project/ray/issues/4309 I opened back in March (still not fixed).
