### ISSUE TITLE
export_policy_model runs slower and slower.

### ISSUE THREAD

**Issue by h8907283** [ray-project/ray#6324]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.7
- **Exact command to reproduce**: python export_test.py

### Describe the problem

Dear Ray developers,

I'm trying to export a SavedModel after each alg.train(). The problem is, alg.export_policy_model() is getting slower and slower. Please see the code below. It's a simplified version of rllib/examples/export/cartpole_dqn_export.py. After the first train step, exporting a SavedModel takes a small fraction of a second (e.g. 0.15s). However, the export_policy_model() call gets slower and slower. After 100 train steps, it takes more than 1 second.

Is there a way for ray to export a SavedModel in constant time?

### Source code / logs

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import ray
import time

from ray.rllib.agents.registry import get_agent_class
from ray.rllib.utils import try_import_tf

tf = try_import_tf()
ray.init()

def train_and_export(algo_name, num_steps, model_dir):
    cls = get_agent_class(algo_name)
    alg = cls(config={}, env="CartPole-v0")
    for i in range(num_steps):
        alg.train()
        ts_start = time.time()
        alg.export_policy_model('%s_%d' % (model_dir, i))
        ts_end = time.time()
        print(ts_end - ts_start)

if __name__ == "__main__":
    algo = "DQN"
    model_dir = "/tmp/model_export_dir"
    num_steps = 100
    train_and_export(algo, num_steps, model_dir)
```

**Comment by ericl** [comment]
@xutianming have you seen this before?

**Comment by xutianming** [comment]
@h8907283 Could you check whether the exported model get larger and larger?

**Comment by h8907283** [comment]
@xutianming @ericl Thanks for the quick responses from both of you. The exported model, saved_model.pb does get larger and larger.

I notice that in TensorFlow's `Saver`, there is a flag that allows a `Saver` to remove nodes from previous Savers, `clear_extraneous_savers`. The flag is set to `False` by default. Just as an experiment, I set it to `True` and run the test case in the above. Unfortunately, that doesn't do anything. `export_policy_model` runs slower and slower and `saved_model.pb` gets larger and larger.

So just out of curiosity, I change the test case above from using `DQN` to `SAC`, `CartPole-v0` to `Pendulum-v0`. With `clear_extraneous_savers=True`, the size of saved_model.pb remains unchanged. But `exported_policy_model` continues to run slower and slower.

The list of saveable variables doesn't grow, regardless of the value of `clear_extraneous_savers`, `DQN` or `SAC`, `CartPole` or `Pendulum`.

It looks like `clear_extraneous_savers` can clear enough from the graph when `SAC` is used in order to make the size of `saved_model.pb` constant, but it doesn't clear enough from the graph to make the export time constant. Something accumulates after each train iteration?

**Comment by ericl** [comment]
Is it possible to print out the graph nodes after each iteration?

I would also try master, we recently fixed some leaked metrics ops in DQN.

**Comment by h8907283** [comment]
@ericl  I'll try to print the nodes out. I'll get back to you asap.

**Comment by xutianming** [comment]
https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/Builder#save

This is the API used to export saved_model.pb. It saves both variables and graph nodes for serving. The model you used might keep adding TensorFlow ops into the graph.

**Comment by h8907283** [comment]
> The model you used might keep adding TensorFlow ops into the graph.

The question is, where in ray keeps adding TF ops? My speculation is that Saver adds nodes after each save. `clear_extraneous_savers=True` prevents saver nodes from going into saved_model.pb, but it doesn't remove the nodes from the graph. Should ray remove the extra nodes in export_policy_model after save?

**Comment by xutianming** [comment]
@h8907283 Perhaps the better way to use this API is to export after finish training ?
Exporting model after each iteration is not common.

**Comment by richardliaw** [comment]
closing because stale
