### ISSUE TITLE
Ray Operator Proposal and Implementation Plan

### ISSUE THREAD

**Issue by JingGe** [ray-project/ray#6328]
Since Kubernetes has been becoming the de facto standard open-source container-orchestration system for automating application deployment, scaling, and management of containerized apps, which could prevent the potential vendor lock-in issue. Within the Kubernetes world, the operator pattern has been widely accepted to manage stateful applications. There was a nice experimental operator project for ray which shows the interest of the ray community. Now it is a good timing to provide a more robust operator at enterprise level that will leverage the core design concepts of Kubernetes. We have been working on this ray operator for more than 6 months with the following features:

- A CRD of RayCluster used for the desired state
- Support the ray cluster with heterogeneous Pods
- Dynamic scaling by leveraging the Reconciliation Loop.
- Update the desired state following the Declarative API design concept.
- HA for Ray Operator.

This ray operator has been running very stable in our production environment for more than 4 months. We are thrilled to be able to contribute it back to the community. The CR(Custom Resource defined in Kubernetes) and the controller we propose will allow users to customize almost all the Kubernetes and Ray configurations.  Here is our two steps contribution plan:

1. The first Pull Request would contain 
    - the Ray Operator source code
    - A comprehensive description which could be considered as the user manual. 
    - Three examples yaml files as show cases for a mini ray cluster, a heterogeneous ray cluster, and a sophisticated ray cluster. 
    - A simple demo to submit Ray Operator and ray cluster with kubectl.

2. The second one would integrate the new Ray Operator with the built-in ray autoscaler.

For more information in details please refer to the following docs:
Ray Operator: https://docs.google.com/document/d/1vfXnwft1fY6HTKw2PUDFOh581KDt4zI2GBHhC1ji_uE
Ray Autoscaler integration: https://docs.google.com/document/d/1lhy9XjNrExKSrY8NuPUtJ7D9MX4wSyX9CDg0KVcZgUY

**Comment by gaocegege** [comment]
I think we can close it since it is already merged into upstream.
