### ISSUE TITLE
Cryptojacking attack when running Ray

### ISSUE THREAD

**Issue by ducalpha** [ray-project/ray#6336]
I used ray nightly (0.8.0dev6) on my private cluster with the default port 3679. I found that the port has been used by a process called `xmrig-notls`.  `htop` shows the following command is occupying all the CPU cores.

```
xmrig-notls -o pinto.mamointernet.icu:4444 -u ver1 -p ver1 --max-cpu-usage 100 --donate-level 1 -B
```

The symptom is like this issue [Cryptojacking attack via Redis container](https://github.com/laradock/laradock/issues/2346). The cause seems to be a vulnerability of Redis.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 18.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.8.0.dev6-cp37-cp37m-manylinux1_x86_64.whl
- **Python version**: 3.7
- **Commands to reproduce**:
`ray up` and `ray submit`

**Comment by ericl** [comment]
Ray does not secure any of its internal services, it is up to you to not expose them to the public internet.

Note that the default security group settings for the autoscaler block all inbound traffic except on the SSH port. However cluster nodes can freely talk to each other on any port. We recommend similar configurations for private clusters.

**Comment by robertnishihara** [comment]
@ducalpha you can start Ray with `--redis-password=...` (and pass `redis_password=...` into `ray.init`) as well. This can help if you must expose the ports to the world. However, it is not a complete solution.
