### ISSUE TITLE
Make putting certain large python objects work

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#634]
In `test/jenkins_tests/multi_node_tests/large_memory_test.py` we used to have

```python
D = (2 ** 30 + 1) * ["h"]		
d = ray.put(D)		
assert ray.get(d) == D		
del D		
del d		
print("Successfully put D.")		
	
E = (2 ** 30 + 1) * ("i",)		
e = ray.put(E)		
assert ray.get(e) == E		
del E		
del e		
print("Successfully put E.")
```

commented out, which we should make work.

**Comment by pcmoritz** [comment]
see https://github.com/ray-project/ray/pull/632

**Comment by robertnishihara** [comment]
Ok, I just ran the script successfully. It took 15-20 minutes and used 50-100GB.

Probably too big/slow for our Jenkins tests in its current form.

There's probably a ton of room for improvement here.

For comparison, note that creating `D` and `E` take about 2-7s.

Given that it seems to work given sufficient time/memory, should we close the issue?

**Comment by pcmoritz** [comment]
Let's merge https://github.com/ray-project/ray/pull/636 and then close this issue
