### ISSUE TITLE
Cannot run distributed workers using tune

### ISSUE THREAD

**Issue by sebastiangonsal** [ray-project/ray#6340]
I am consistently getting serialization errors on running tune.run. I have removed almost everything and i cant make out why this error is happening at all. I am using version 0.7.6. 

Following up on the recommendations in another issue #5077  i first started with replacing everything that had a `from` with an `import`. It didn't solve the issue and now i am with the code below.

```
import os
import argparse
import ray
import ray.tune

@ray.remote
def train(config, reporter=None):
    acc = 20

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--redis-address")
    args = parser.parse_args()
    ray.init(redis_address=args.redis_address)
    config = {
        "l1": ray.tune.grid_search([0.001, 0.01, 0.1]),
    }
    ray.tune.run(train.remote, config=config)
```

The serialization error i am getting is the following:
```
Traceback (most recent call last):
File "/lib/python3.6/site-packages/ray/worker.py", line 458, in _try_store_and_register
self.store_and_register(object_id, value)
File "/lib/python3.6/site-packages/ray/worker.py", line 321, in store_and_register
pyarrow.serialize(value, serialization_context),
File "pyarrow/serialization.pxi", line 358, in pyarrow.lib.serialize
File "pyarrow/serialization.pxi", line 150, in pyarrow.lib.SerializationContext._serialize_callback
File "/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 1123, in dumps
cp.dump(obj)
File "/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle.py", line 482, in dump
return Pickler.dump(self, obj)
File "/lib/python3.6/pickle.py", line 409, in dump
self.save(obj)
File "/lib/python3.6/pickle.py", line 496, in save
rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
``

**Comment by sebastiangonsal** [comment]
Also can using `load_code_from_local` get around the serialization issue. From the docstring, it looked like it could but there was no information except for passing the flag to `ray.init`. I made sure that all worker nodes had the file and ran this code with the flag but it resulted in the program never terminating.

**Comment by richardliaw** [comment]
Can you do the following?

```
def train(config, reporter=None):
    acc = 20
    reporter(acc=acc)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--redis-address")
    args = parser.parse_args()
    ray.init(redis_address=args.redis_address)
    config = {
        "l1": ray.tune.grid_search([0.001, 0.01, 0.1]),
    }
    ray.tune.run(train, config=config)

**Comment by sebastiangonsal** [comment]
Your code does not have the `ray.remote` decorator. Without that decorator, the code that i posted works fine without errors.
However, after putting the decorator both yours and mine code gives the error that i posted earlier.

**Comment by ujvl** [comment]
@sebastiangonsal you don't need the decorator for tune functions/Trainables since we create the ray actor internally.

we should probably raise a more informative error in this case

**Comment by sebastiangonsal** [comment]
That's great. Another question: I need to create a tracking session to do track log. However, if i do `track.log` outside the train function it still gives me error complaining that no track session found. But if i do the following, i am creating a tracking session for every hyperparam value. Does the below sound right:

```
def train(config, reporter=None):
    track.init('track_session')
    track.log(acc=acc)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--redis-address")
    args = parser.parse_args()
    ray.init(redis_address=args.redis_address)
    config = {
        "l1": ray.tune.grid_search([0.001, 0.01, 0.1]),
    }
    ray.tune.run(train, config=config)
```
