### ISSUE TITLE
[docs] Adopt a cleaner layout for the docs 

### ISSUE THREAD

**Issue by deanwampler** [ray-project/ray#6348]
### System information
The following don't really matter (that much) for the proposed documentation changes:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Catalina
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.8.0-dev6
- **Python version**: 3.7.4
- **Exact command to reproduce**: N/A

### Describe the problem
The current documentation is somewhat hard to navigate and a bit overwhelming visually. This issue is to suggest switching to the Sphinx Alabaster theme, which has a less-cluttered visual appearance, reorganize the navigation to be more hierarchical and easier to navigate, then address specific text improvements, such as a more compelling landing page. The latter changes will be addressed with  different issue numbers, as they will be ongoing.

### Source code / logs
N/A

**Comment by richardliaw** [comment]
fixed :)
