### ISSUE TITLE
how can i use db connection in a remote function.

### ISSUE THREAD

**Issue by 513090336** [ray-project/ray#6356]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Centos 7.2
- **Ray installed from (source or binary)**:source
- **Ray version**:0.7.6
- **Python version**:3.6
- **Exact command to reproduce**:

### Describe the problem

I wanna use ray to calculate some questions.I write 3 layers nested remote function according to its logic.What bothers me is that i must use some data in remote function so that i must connect database.i don't know how can i use db connection in a remote function.it turns out TypeError: can't pickle _thread.lock objects

**Comment by 513090336** [comment]
@ericl @rshin @yaroslavvb @sotte  hello, anyone helps me?

**Comment by 513090336** [comment]
@mitar hello, i saw your answer in #2713. i am trying to use MongoDB in remote function.But i can't solve it.Could you teach me how to do ?

**Comment by mitar** [comment]
You just connect to MongoDB like you would connect otherwise in Python.

**Comment by 513090336** [comment]
> You just connect to MongoDB like you would connect otherwise in Python.

i need to start many remote tasks. so these tasks should use same MongoDB connection .But when i use the connection in remote function, it turns out TypeError: can't pickle _thread.lock objects. i know why but i can't find a better way to solve

**Comment by richardliaw** [comment]
No matter what, it doesn't look like you'll be able to make multiple mongodb calls via the same connection _in parallel_.

You should use Actors in this case. This should help you persist the same MongoDB connection across remote invocations.

**Comment by 513090336** [comment]
Thank you! I know how to solve it ! @richardliaw

**Comment by abhalawat** [comment]
Hey,I am facing issue while connecting mongodb into remote function.Could guide me how to do that?
