### ISSUE TITLE
bytearray serialization

### ISSUE THREAD

**Issue by Mmdixon** [ray-project/ray#6361]
### System information
- **OS Platform and Distribution**: Ubuntu 18.04.3 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.7.3

### Describe the problem
`WARNING worker.py:348 -- WARNING: Falling back to serializing objects of type <class 'bytearray'> by using pickle. This may be inefficient.`

A library I am using outputs a `bytearray` which is then shared or passed through `ray`. However, I get the above warning. Is there a better way to serialize `bytearray`'s?
Is it worth doing something like:
```
sample = bytearray(b"test")
sample_np = np.array(sample, copy=False)
```
Then deserialization just use the numpy array or make a copy back to `bytearray` if an interface needs that type?

### Source code / logs
```
sample = bytearray(b"test")
ray.put(sample)
```

**Comment by edoakes** [comment]
As of version `0.7.7` we have changed the serialization so this should be faster now. Using numpy will still be faster, but upgrading to the latest version should give you some performance improvement.

Just ray a test, and it looks like it takes ~`1.1ms` to serialize a 1MiB bytearray vs ~`800us` to serialize a 1MiB numpy array
