### ISSUE TITLE
[>=0.7.4] ray start --head --block kills redis server

### ISSUE THREAD

**Issue by ChromoX** [ray-project/ray#6368]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker debian stretch slim
- **Ray installed from (source or binary)**: pip binary
- **Ray version**: >=0.7.4, no issues <0.7.4
- **Python version**: 3.7.2
- **Exact command to reproduce**:

Run the following command:
```ray start --head --block```
the command will print the usual Ray startup message followed by:
```
2019-12-05 05:02:19,114	ERROR scripts.py:398 -- Ray processes died unexpectedly:
2019-12-05 05:02:19,115	ERROR scripts.py:401 -- 	reporter died with exit code 1
2019-12-05 05:02:19,115	ERROR scripts.py:402 -- Killing remaining processes and exiting...
```
From what I can tell this is caused by the internal redis server being sent the kill signal. From the redis.out log:
```
15:C 05 Dec 2019 05:02:17.845 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
15:C 05 Dec 2019 05:02:17.845 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=15, just started
15:C 05 Dec 2019 05:02:17.845 # Configuration loaded
15:M 05 Dec 2019 05:02:17.846 # Server initialized
15:signal-handler (1575522139) Received SIGTERM scheduling shutdown...
15:M 05 Dec 2019 05:02:19.357 # User requested shutdown...
15:M 05 Dec 2019 05:02:19.357 # Redis is now ready to exit, bye bye...
```
Any ideas?

**Comment by edoakes** [comment]
This is actually because the `reporter.py` process is dying so `ray start` is killing the rest of the processes. Could you try upgrading to latest and seeing if there's still an issue?

**Comment by ChromoX** [comment]
Upgraded to 0.8.0. Not seeing this issue anymore. Thanks for your help @edoakes!
