### ISSUE TITLE
Error on building from source

### ISSUE THREAD

**Issue by esquires** [ray-project/ray#6373]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: master or tag ray-0.7.6
- **Python version**: 3.6.9
- **Exact command to reproduce**:

```bash
# from here: https://ray.readthedocs.io/en/latest/installation.html#building-ray-from-source
cd ray/python
pip install -e . --verbose  # Add --user if you see a permission denied error.
```

### Describe the problem
The issue appears to be that a dependency doesn't exist on github. In particular, this [file](https://github.com/jovany-wang/prometheus-cpp/archive/master.zip) does not exist. It is required in `bazel/ray_deps_setup.bzl`. There is a note in that file that a different repository will be used when a [PR](https://github.com/jupp0r/prometheus-cpp/pull/225) is merged but it appears that it has been closed.

### Source code / logs
```Created temporary directory: /tmp/pip-ephem-wheel-cache-2sfor_24
Created temporary directory: /tmp/pip-req-tracker-koee7h10
Created requirements tracker '/tmp/pip-req-tracker-koee7h10'
Created temporary directory: /tmp/pip-install-pmv1h4ic
Obtaining file:///home/esquires/repos/rl/temp/ray/python
  Added file:///home/esquires/repos/rl/temp/ray/python to build tracker '/tmp/pip-req-tracker-koee7h10'
    Running setup.py (path:/home/esquires/repos/rl/temp/ray/python/setup.py)
    egg_info for package from file:///home/esquires/repos/rl/temp/ray/python
    Running command python setup.py egg_info
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
  Source in /home/esquires/repos/rl/temp/ray/python has version 0.7.6, which
  satisfies requirement ray==0.7.6 from file:///home/esquires/repos/rl/temp/ray/python
  Removed ray==0.7.6 from file:///home/esquires/repos/rl/temp/ray/python from build tracker '/tmp/pip-req-tracker-koee7h10'
Requirement already satisfied: numpy>=1.14 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (1.17.4)
Requirement already satisfied: filelock in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (3.0.12)
Requirement already satisfied: jsonschema in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (3.2.0)
Requirement already satisfied: funcsigs in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (1.0.2)
Requirement already satisfied: click in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (7.0)
Requirement already satisfied: colorama in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (0.4.1)
Requirement already satisfied: pytest in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (5.3.1)
Requirement already satisfied: pyyaml in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (5.2)
Requirement already satisfied: redis>=3.3.2 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (3.3.11)
Requirement already satisfied: six>=1.0.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (1.13.0)
Requirement already satisfied: protobuf>=3.8.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from ray==0.7.6) (3.11.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from jsonschema->ray==0.7.6) (0.15.6)
Requirement already satisfied: setuptools in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from jsonschema->ray==0.7.6) (42.0.2)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from jsonschema->ray==0.7.6) (1.2.0)
Requirement already satisfied: attrs>=17.4.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from jsonschema->ray==0.7.6) (19.3.0)
Requirement already satisfied: packaging in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from pytest->ray==0.7.6) (19.2)
Requirement already satisfied: more-itertools>=4.0.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from pytest->ray==0.7.6) (8.0.0)
Requirement already satisfied: py>=1.5.0 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from pytest->ray==0.7.6) (1.8.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from pytest->ray==0.7.6) (0.13.1)
Requirement already satisfied: wcwidth in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from pytest->ray==0.7.6) (0.1.7)
Requirement already satisfied: zipp>=0.5 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema->ray==0.7.6) (0.6.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/esquires/.venvs/venv-temp/lib/python3.6/site-packages (from packaging->pytest->ray==0.7.6) (2.4.5)
Installing collected packages: ray
  Running setup.py develop for ray
    Running command /home/esquires/.venvs/venv-temp/bin/python3 -c 'import sys,
    setuptools, tokenize; sys.argv[0] =
    '"'"'/home/esquires/repos/rl/temp/ray/python/setup.py'"'"';
    __file__='"'"'/home/esquires/repos/rl/temp/ray/pyth
on/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing ray.egg-info/PKG-INFO
    writing dependency_links to ray.egg-info/dependency_links.txt
    writing entry points to ray.egg-info/entry_points.txt
    writing requirements to ray.egg-info/requires.txt
    writing top-level names to ray.egg-info/top_level.txt
    reading manifest file 'ray.egg-info/SOURCES.txt'
    writing manifest file 'ray.egg-info/SOURCES.txt'
    running build_ext
    + set -e
    +++ dirname ../build.sh
    ++ cd ..
    ++ pwd
    + ROOT_DIR=/home/esquires/repos/rl/temp/ray
    ++ uname
    + unamestr=Linux
    + [[ Linux == \L\i\n\u\x ]]
    + PARALLEL=1
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + PYTHON_EXECUTABLE=
    + BUILD_DIR=
    + [[ 2 -gt 0 ]]
    + key=-p
    + case $key in
    + PYTHON_EXECUTABLE=/home/esquires/.venvs/venv-temp/bin/python3
    + shift
    + shift
    + [[ 0 -gt 0 ]]
    + [[ -z /home/esquires/.venvs/venv-temp/bin/python3 ]]
    + echo 'Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.'
    Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.
    ++ PATH=/home/esquires/.venvs/venv-temp/bin:/home/esquires/bin:/usr/local/bin:/home/esquires/.local/bin:/home/esquires/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/esq
uires/repos/CodeChecker/build/CodeChecker/bin:/home/esquires/repos/fzf/bin:/home/esquires/.bazel/bin
    ++ which bazel
    + BAZEL_EXECUTABLE=/home/esquires/bin/bazel
    + echo 'Using Bazel executable /home/esquires/bin/bazel.'
    Using Bazel executable /home/esquires/bin/bazel.
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + bash /home/esquires/repos/rl/temp/ray/setup_thirdparty.sh /home/esquires/.venvs/venv-temp/bin/python3
    + set -e
    +++ dirname /home/esquires/repos/rl/temp/ray/setup_thirdparty.sh
    ++ cd /home/esquires/repos/rl/temp/ray
    ++ pwd
    + ROOT_DIR=/home/esquires/repos/rl/temp/ray
    + [[ -z /home/esquires/.venvs/venv-temp/bin/python3 ]]
    + PYTHON_EXECUTABLE=/home/esquires/.venvs/venv-temp/bin/python3
    + echo 'Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.'
    Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.
    + RAY_BUILD_PYTHON=YES
    + RAY_BUILD_JAVA=NO
    + /home/esquires/repos/rl/temp/ray/thirdparty/scripts/setup.sh /home/esquires/.venvs/venv-temp/bin/python3
    + set -e
    +++ dirname /home/esquires/repos/rl/temp/ray/thirdparty/scripts/setup.sh
    ++ cd /home/esquires/repos/rl/temp/ray/thirdparty/scripts
    ++ pwd
    + TP_SCRIPT_DIR=/home/esquires/repos/rl/temp/ray/thirdparty/scripts
    + TP_DIR=/home/esquires/repos/rl/temp/ray/thirdparty/scripts/..
    + mkdir -p /home/esquires/repos/rl/temp/ray/thirdparty/scripts/../build
    + mkdir -p /home/esquires/repos/rl/temp/ray/thirdparty/scripts/../pkg
    + [[ -z /home/esquires/.venvs/venv-temp/bin/python3 ]]
    + PYTHON_EXECUTABLE=/home/esquires/.venvs/venv-temp/bin/python3
    + echo 'Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.'
    Using Python executable /home/esquires/.venvs/venv-temp/bin/python3.
    + [[ NO == \Y\E\S ]]
    + [[ YES == \Y\E\S ]]
    + echo 'Python library will be built.'
    Python library will be built.
    ++ uname
    + unamestr=Linux
    + BUILD_DIR=/home/esquires/repos/rl/temp/ray/build/
    + '[' '!' -d /home/esquires/repos/rl/temp/ray/build/ ']'
    + pushd /home/esquires/repos/rl/temp/ray/build/
    ~/repos/rl/temp/ray/build ~/repos/rl/temp/ray/python
    + '[' -z '' ']'
    + /home/esquires/.venvs/venv-temp/bin/python3 -m pip install -q
    --target=/home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files pyarrow==0.14.0.RAY --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/516e15028091b5e
287200b5df77d77f72d9a6c9a/index.html
    ERROR: astroid 2.3.2 has requirement six==1.12, but you'll have six 1.13.0 which is incompatible.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/numpy-1.17.4.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/numpy already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/pyarrow already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/__pycache__ already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/pyarrow-0.14.0.RAY.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/six.py already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/six-1.13.0.dist-info already exists. Specify --upgrade to force replacement.
    WARNING: Target directory /home/esquires/repos/rl/temp/ray/python/ray/pyarrow_files/bin already exists. Specify --upgrade to force replacement.
    + export PYTHON_BIN_PATH=/home/esquires/.venvs/venv-temp/bin/python3
    + PYTHON_BIN_PATH=/home/esquires/.venvs/venv-temp/bin/python3
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + /home/esquires/bin/bazel build //:ray_pkg --verbose_failures
    Loading:
    Loading: 0 packages loaded
    INFO: Call stack for the definition of repository 'com_github_jupp0r_prometheus_cpp' which is a http_archive (rule definition at /home/esquires/.cache/bazel/_bazel_esquires/e70ce9bf9c68530edaf0d7a0c580442c/external/bazel_tools/t
ools/build_defs/repo/http.bzl:229:16):
     - /home/esquires/repos/rl/temp/ray/bazel/ray_deps_setup.bzl:96:5
     - /home/esquires/repos/rl/temp/ray/WORKSPACE:5:1
    ERROR: An error occurred during the fetch of repository 'com_github_jupp0r_prometheus_cpp':
       java.io.IOException: Error downloading [https://github.com/jovany-wang/prometheus-cpp/archive/master.zip] to /home/esquires/.cache/bazel/_bazel_esquires/e70ce9bf9c68530edaf0d7a0c580442c/external/com_github_jupp0r_prometheus_c
pp/master.zip: GET returned 404 Not Found
    INFO: Call stack for the definition of repository 'com_github_grpc_grpc' which is a http_archive (rule definition at /home/esquires/.cache/bazel/_bazel_esquires/e70ce9bf9c68530edaf0d7a0c580442c/external/bazel_tools/tools/build_d
efs/repo/http.bzl:229:16):
     - /home/esquires/repos/rl/temp/ray/bazel/ray_deps_setup.bzl:105:5
     - /home/esquires/repos/rl/temp/ray/WORKSPACE:5:1
    ERROR: error loading package '': in /home/esquires/repos/rl/temp/ray/bazel/ray_deps_build_all.bzl: Encountered error while reading extension file 'repositories.bzl': no such package '@com_github_jupp0r_prometheus_cpp//': jav
a.io.IOException: Error downloading [https://github.com/jovany-wang/prometheus-cpp/archive/master.zip] to /home/esquires/.cache/bazel/_bazel_esquires/e70ce9bf9c68530edaf0d7a0c580442c/external/com_github_jupp0r_prometheus_cpp/master.
zip: GET returned 404 Not Found
    ERROR: error loading package '': in /home/esquires/repos/rl/temp/ray/bazel/ray_deps_build_all.bzl: Encountered error while reading extension file 'repositories.bzl': no such package '@com_github_jupp0r_prometheus_cpp//': jav
a.io.IOException: Error downloading [https://github.com/jovany-wang/prometheus-cpp/archive/master.zip] to /home/esquires/.cache/bazel/_bazel_esquires/e70ce9bf9c68530edaf0d7a0c580442c/external/com_github_jupp0r_prometheus_cpp/master.
zip: GET returned 404 Not Found
    INFO: Elapsed time: 0.267s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/esquires/repos/rl/temp/ray/python/setup.py", line 196, in <module>
        license="Apache 2.0")
      File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/esquires/repos/rl/temp/ray/python/setup.py", line 94, in run
        subprocess.check_call(command)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/esquires/.venvs/venv-temp/bin/python3']' returned non-zero exit status 1.
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-koee7h10'
ERROR: Command errored out with exit status 1:
/home/esquires/.venvs/venv-temp/bin/python3 -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/home/esquires/repos/rl/temp/ray/python/setup.py'"'"'; __file__='"'"'/home/esquires
/repos/rl/temp/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the
 logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 851, in install
    install_options, global_options, prefix=prefix,
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 700, in install_editable
    cwd=self.unpacked_source_directory,
  File "/home/esquires/.venvs/venv-temp/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit
status 1: /home/esquires/.venvs/venv-temp/bin/python3 -c 'import sys, setuptools,
tokenize; sys.argv[0] = '"'"'/home/esquires/repos/rl/temp/ray/python/setup.
py'"'"'; __file__='"'"'/home/esquires/repos/rl/temp/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exe
c'"'"'))' develop --no-deps Check the logs for full command output.


```

**Comment by esquires** [comment]
It looks like I can build from source as of tag ray-0.8.0 (0afe14f2). Closing

**Comment by nanxintin** [comment]
Hi @esquires, I have a similar error. Do you have any suggestion?
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
Ray installed from (source or binary): source
Ray version: master or tag ray-0.8.0
Python version: 3.5.2

    + /home/shaokun/projects/fightGameAI/bin/python3 -m pip install -q --target=/home/shaokun/projects/fightGameAI/ray/python/ray/pyarrow_files pyarrow==0.14.0.RAY --find-links https://s3-us-west-2.amazonaws.com/arrow-wheels/3a11193d9530fe8ec7fdb98057f853b708f6f6ae/index.html
    ++ /home/shaokun/projects/fightGameAI/bin/python3 -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'
    + PYTHON_VERSION=3.5
    + [[ 3.5 == \3\.\6 ]]
    + [[ 3.5 == \3\.\7 ]]
    + export PYTHON3_BIN_PATH=/home/shaokun/projects/fightGameAI/bin/python3
    + PYTHON3_BIN_PATH=/home/shaokun/projects/fightGameAI/bin/python3
    + export PYTHON2_BIN_PATH=/home/shaokun/projects/fightGameAI/bin/python3
    + PYTHON2_BIN_PATH=/home/shaokun/projects/fightGameAI/bin/python3
    + '[' NO == YES ']'
    + '[' YES == YES ']'
    + /home/shaokun/.bazel/bin/bazel build //:ray_pkg --verbose_failures
    WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
    Starting local Bazel server and connecting to it...
    INFO: Writing tracer profile to '/home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/command.profile.gz'
    Loading:
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    Loading: 0 packages loaded
    INFO: Call stack for the definition of repository 'com_github_jupp0r_prometheus_cpp' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:203:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    WARNING: Download from https://github.com/jupp0r/prometheus-cpp/archive/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    ERROR: An error occurred during the fetch of repository 'com_github_jupp0r_prometheus_cpp':
       java.io.IOException: Error downloading [https://github.com/jupp0r/prometheus-cpp/archive/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip] to /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/com_github_jupp0r_prometheus_cpp/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    INFO: Call stack for the definition of repository 'com_github_nelhage_rules_boost' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:121:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    INFO: Call stack for the definition of repository 'com_github_checkstyle_java' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:98:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    INFO: Call stack for the definition of repository 'rules_jvm_external' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:84:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    INFO: Call stack for the definition of repository 'com_github_grpc_grpc' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:215:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    INFO: Call stack for the definition of repository 'rules_proto_grpc' which is a http_archive (rule definition at /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:68:9
     - /home/shaokun/projects/fightGameAI/ray/bazel/ray_deps_setup.bzl:226:5
     - /home/shaokun/projects/fightGameAI/ray/WORKSPACE:5:1
    ERROR: no such package '@com_github_jupp0r_prometheus_cpp//bazel': java.io.IOException: Error downloading [https://github.com/jupp0r/prometheus-cpp/archive/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip] to /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/com_github_jupp0r_prometheus_cpp/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    ERROR: no such package '@com_github_jupp0r_prometheus_cpp//bazel': java.io.IOException: Error downloading [https://github.com/jupp0r/prometheus-cpp/archive/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip] to /home/shaokun/.cache/bazel/_bazel_shaokun/55a7696bf0d3d67eb836437804bf124a/external/com_github_jupp0r_prometheus_cpp/60eaa4ea47b16751a8e8740b05fe70914c68a480.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    INFO: Elapsed time: 26.024s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
    FAILED: Build did NOT complete successfully (0 packages loaded)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/shaokun/projects/fightGameAI/ray/python/setup.py", line 210, in <module>
        license="Apache 2.0")
      File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/shaokun/projects/fightGameAI/ray/python/setup.py", line 99, in run
        subprocess.check_call(command)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['../build.sh', '-p', '/home/shaokun/projects/fightGameAI/bin/python3']' returned non-zero exit status 1
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-xe7thv1v'
ERROR: Command errored out with exit status 1: /home/shaokun/projects/fightGameAI/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shaokun/projects/fightGameAI/ray/python/setup.py'"'"'; __file__='"'"'/home/shaokun/projects/fightGameAI/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 802, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/shaokun/projects/fightGameAI/lib/python3.5/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/shaokun/projects/fightGameAI/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/shaokun/projects/fightGameAI/ray/python/setup.py'"'"'; __file__='"'"'/home/shaokun/projects/fightGameAI/ray/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by nflu** [comment]
I also have this problem. "Check the logs for full command output." Does anyone know where the logs are? I tried running pip with a log file but I think that just captures the same output we see here.
