### ISSUE TITLE
track.log does not use the track.init from master node

### ISSUE THREAD

**Issue by sebastiangonsal** [ray-project/ray#6386]
In ray, `track.init` has to be done before calling `track.log`. However, if i do `track.log` outside the function that defines the actor it gives me error complaining that no track session found. But if i do the following, i am creating a tracking session for every hyperparam value. Does the below sound right (doesnt look good to me since we are creating one tracking session per track.log)

```
def train(config, reporter=None):
    track.init('track_session')
    track.log(acc=acc)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--redis-address")
    args = parser.parse_args()
    ray.init(redis_address=args.redis_address)
    config = {
        "l1": ray.tune.grid_search([0.001, 0.01, 0.1]),
    }
    ray.tune.run(train, config=config)
```

**Comment by ujvl** [comment]
yes this is the correct way to use `track.log`, a session exists for each trial
