### ISSUE TITLE
[tune] Overlapping logs across multiple runs

### ISSUE THREAD

**Issue by hhbyyh** [ray-project/ray#6391]
Right now multiple runs are sharing the same folder and the logs are mixed. And for PBT the appending logs across multiple runs do not make much sense (pbt_global).

IMO one approach is to create a new log folder for each run. e.g.
ray_result/pbt_example_23fh8
ray_result/pbt_example_e42ef
where the suffix are unique ids for experiment.

At least we should avoid appending pbt_global and policy* for PBT.

Ray version: 0.8.0dev7

**Comment by richardliaw** [comment]
You can change to log folder via `tune.run(name=...)`.

**Comment by hhbyyh** [comment]
Thanks. That should work!
Yet I still feel asking users to change name for every run is error-prone. The default behavior ought to separate logs across multiple experiments.

**Comment by richardliaw** [comment]
That sounds reasonable to me. Can you push a fix?

**Comment by krfricke** [comment]
This has been addressed in #11104 - thanks for your input here!
