### ISSUE TITLE
Ray actors hang after some time of running

### ISSUE THREAD

**Issue by zplizzi** [ray-project/ray#6392]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: 3.6.8

The following code sample is a mockup of a replay buffer.
It initially runs as expected, printing output like:

```
(pid=20614) worker stepped
got batch
(pid=20615) worker stepped
got batch
(pid=20614) worker stepped
got batch
(pid=20615) worker stepped
got batch
(pid=20614) worker stepped
(pid=20615) worker stepped
```

but after some time (5-10 mins), one of the workers will hang, and the output will become like
```
(pid=20614) worker stepped
got batch
got batch
(pid=20614) worker stepped
got batch
got batch
```

and after some more time (~10 mins on my system), both workers will be hung, and the output will just be:
```
got batch
got batch
got batch
got batch
```

There are no errors or warnings in the output - the workers just silently stop printing their "worker stepped".

I'm testing on an AWS p3.2xlarge instance, FWIW.

### Source code / logs
```python3
import collections
import random
import torch
import time
import ray


class Storage:
    def __init__(self):
        self.buffer = collections.deque(maxlen=20000)
        self.buffer.append("first item")

    def save_samples(self, samples):
        for sample in samples:
            self.buffer.append(sample)

    def sample_batch(self):
        batch = [self.sample() for _ in range(200)]
        return batch

    def sample(self):
        return random.sample(self.buffer, k=1)[0]


class Worker:
    def __init__(self, storage):
        self.storage = storage

    def run(self):
        while True:
            self.step()

    def step(self):
        samples = [torch.rand((32, 96, 96)) for _ in range(32)]
        ray.get(self.storage.save_samples.remote(samples))
        print("worker stepped")
        time.sleep(.05)


if __name__ == "__main__":
    ray.init()
    storage = ray.remote(Storage).remote()
    workers = [ray.remote(Worker).remote(storage) for _ in range(2)]
    [w.run.remote() for w in workers]
    while True:
        batch = ray.get(storage.sample_batch.remote())
        print("got batch")
```

**Comment by zplizzi** [comment]
It seems like this issue is related somehow to memory.

At one extreme (buffer maxlen = 20000, ray init object_store_memory = 1*1024**3), the script fails properly with out of object store memory errors.

At another extreme (buffer maxlen = 5000, object_store_memory = 25*1024**3), things seem to run smoothly and nothing hangs after 20+ mins.

But in a relatively wide middle, it seems to reliably hang with no errors raised as described above. Here's some configurations that caused hanging:
buffer maxlen = 20000, object_store_memory = 13.88*1024**3 (my system default)
buffer maxlen = 20000, object_store_memory = 25*1024**3

**Comment by richardliaw** [comment]
cc @ericl

**Comment by ericl** [comment]
That's odd you don't get an error if the object store is full. What is the output of `ray stack` when it is hanging?

By the way you can try replacing `self.buffer.append(sample)` with `self.buffer.append(sample.copy())` to avoid using object store memory. The original samples is a shared memory object but copying it will make it a normal numpy array.

**Comment by zplizzi** [comment]
Here's the output of `ray stack`: https://gist.github.com/zplizzi/0677c2dc986db8941251e727c640796a

I did figure out that copying trick and it seems to be working fine with that.
