### ISSUE TITLE
Inconsistency in Diagonal Gaussian between log probability and entropy

### ISSUE THREAD

**Issue by eugenevinitsky** [ray-project/ray#6393]
In the DiagonalGaussian action distribution the logp is calculated like so:

`        return (-0.5 * tf.reduce_sum(
            tf.square((x - self.mean) / self.std), reduction_indices=[1]) -
                0.5 * np.log(2.0 * np.pi) * tf.to_float(tf.shape(x)[1]) -
                tf.reduce_sum(self.log_std, reduction_indices=[1]))`

Here the term  tf.reduce_sum(self.log_std, reduction_indices=[1])) is supposed to compute the part of the logprobability due to the determinant of the covariance matrix. The diagonals of the covariance matrix are the squared standard deviations, so the absence of the 0.5 in front of the term makes sense. But, then, in that case the entropy

`tf.reduce_sum(
            .5 * self.log_std + .5 * np.log(2.0 * np.pi * np.e),
            reduction_indices=[1])`

<img width="310" alt="image" src="https://user-images.githubusercontent.com/7660397/70380361-ed418a80-18ee-11ea-917f-0f266b48ada5.png">

should also not have a 0.5 in front of the log-std term and should be
`tf.reduce_sum(
            self.log_std + .5 * np.log(2.0 * np.pi * np.e),
            reduction_indices=[1])`

**Comment by ericl** [comment]
I see, should we be reverting https://github.com/ray-project/ray/pull/2968 then?
cc @pcmoritz

**Comment by richardliaw** [comment]
cc @michaelzhiluo, as he was the one who mentioned this change I think?

**Comment by JiahaoYao** [comment]
I agree that `0.5` should be removed because of using `log_std` not the `log_variance`.

**Comment by michaelzhiluo** [comment]
I also agree that `0.5` should not be in front of `self.log_std` in entropy since there is a 2x term factoring out of the variance terms in the covariance matrix.

**Comment by richardliaw** [comment]
@eugenevinitsky do you mind pushing a fix?

**Comment by eugenevinitsky** [comment]
Yeah, one sec!
