### ISSUE TITLE
No tensorboard summary

### ISSUE THREAD

**Issue by jheffez** [ray-project/ray#6397]
Not seeing tensorboard files while running the example:
` rllib train --run=DQN --env=CartPole-v0`

Fresh install of ray on Ubuntu 18.04
```
ls ~/ray_results/default/DQN_CartPole-v0_0_2019-12-08_13-35-467ihs5fyq
params.json  params.pkl  progress.csv  result.json
``
python -m pytest -v ./37env/lib/python3.7/site-packages/ray/tests/test_mini.py:
platform linux -- Python 3.7.5, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /root/37env/bin/python
cachedir: .pytest_cache
rootdir: /root
collected 3 items


37env/lib/python3.7/site-packages/ray/tests/test_mini.py::test_basic_task_api PASSED [ 33%]
37env/lib/python3.7/site-packages/ray/tests/test_mini.py::test_put_api PASSED [ 66%]
37env/lib/python3.7/site-packages/ray/tests/test_mini.py::test_actor_api PASSED [100%]
```
Package                Version    Location 
---------------------- ---------- ---------
absl-py                0.8.1      
ai-benchmark           0.1.1      
alembic                1.3.1      
astor                  0.8.0      
attrs                  19.3.0     
bayesian-optimization  1.0.1      
boto                   2.49.0     
boto3                  1.10.34    
botocore               1.13.34    
cachetools             3.1.1      
certifi                2019.11.28 
chardet                3.0.4      
Click                  7.0        
cloudpickle            1.1.1      
cma                    2.7.0      
colorama               0.4.3      
colorclass             2.2.0      
configparser           4.0.2      
ConfigSpace            0.4.10     
Cython                 0.29.14    
databricks-cli         0.9.1      
decorator              4.4.1      
docker                 4.1.0      
docutils               0.15.2     
entrypoints            0.3        
filelock               3.0.12     
Flask                  1.1.1      
funcsigs               1.0.2      
future                 0.18.2     
gast                   0.2.2      
gitdb2                 2.0.6      
GitPython              3.0.5      
google-auth            1.7.2      
google-auth-oauthlib   0.4.1      
google-pasta           0.1.8      
gorilla                0.3.0      
grpcio                 1.25.0     
gunicorn               20.0.4     
gym                    0.12.1     /root/gym
h5py                   2.10.0     
hpbandster             0.7.4      
hyperopt               0.1.2      
idna                   2.8        
importlib-metadata     1.2.0      
itsdangerous           1.1.0      
Jinja2                 2.10.3     
jmespath               0.9.4      
joblib                 0.14.0     
jsonschema             3.2.0      
Keras                  2.3.1      
Keras-Applications     1.0.8      
Keras-Preprocessing    1.1.0      
lightgbm               2.3.1      
lz4                    2.2.1      
Mako                   1.1.0      
Markdown               3.1.1      
MarkupSafe             1.1.1      
mlflow                 1.4.0      
more-itertools         8.0.2      
netifaces              0.10.9     
networkx               2.4        
nevergrad              0.2.3      
numpy                  1.17.4     
oauthlib               3.1.0      
opencv-python-headless 4.1.2.30   
opt-einsum             3.1.0      
packaging              19.2       
pandas                 0.25.3     
patsy                  0.5.1      
Pillow                 6.2.1      
pip                    19.3.1     
pip-check              2.5.2      
pkg-resources          0.0.0      
pluggy                 0.13.1     
protobuf               3.11.1     
psutil                 5.6.7      
py                     1.8.0      
py-cpuinfo             5.0.0      
py-spy                 0.3.0      
pyasn1                 0.4.8      
pyasn1-modules         0.2.7      
pyglet                 1.4.8      
pymongo                3.9.0      
pyparsing              2.4.5      
Pyro4                  4.77       
pyrsistent             0.15.6     
pytest                 5.3.1      
python-dateutil        2.8.0      
python-editor          1.0.4      
pytz                   2019.3     
PyYAML                 5.2        
querystring-parser     1.2.4      
ray                    0.7.6      
redis                  3.3.11     
requests               2.22.0     
requests-oauthlib      1.3.0      
rsa                    4.0        
s3transfer             0.2.1      
scikit-learn           0.22       
scikit-optimize        0.5.2      
scipy                  1.3.3      
serpent                1.28       
setproctitle           1.1.10     
setuptools             42.0.2     
sigopt                 5.3.1      
simplejson             3.17.0     
six                    1.13.0     
smart-open             1.9.0      
smmap2                 2.0.5      
SQLAlchemy             1.3.11     
sqlparse               0.3.0      
statsmodels            0.10.2     
tabulate               0.8.6      
tensorboard            2.0.2      
tensorflow             2.0.0      
tensorflow-estimator   2.0.1      
tensorflow-probability 0.8.0      
termcolor              1.1.0      
terminaltables         3.1.0      
tqdm                   4.40.1     
typing                 3.7.4.1    
typing-extensions      3.7.4.1    
urllib3                1.25.7     
wcwidth                0.1.7      
websocket-client       0.56.0     
Werkzeug               0.16.0     
wheel                  0.33.6     
wrapt                  1.11.2     
xgboost                0.90       
zipp                   0.6.0

**Comment by richardliaw** [comment]
Update to the latest wheels?

**Comment by jheffez** [comment]
This is a fresh install. Please clarify which wheels you are reffering to??
