### ISSUE TITLE
[ray] no module named 'ray.experimental.ui'

### ISSUE THREAD

**Issue by JiayuanSternLi** [ray-project/ray#6410]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6
TF2.0
ubuntu16.04

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*
ray version 0.8.0dev

### Reproduction
`
import ray.experimental.ui as ui
ui.task_timeline()
`
I ran the tutorial code from intel+ray course, but error shows no module named ray.experimental.ui. There is no relevent bug report after searching for google and stackoverflow

**Comment by robertnishihara** [comment]
The Intel + Ray course uses a slightly older version of Ray, so the call to the timeline is a bit out of date.

You can generate the timeline by doing `ray.timeline()`. This generates a JSON file that you can view through chrome://tracing. Soon you'll be able to view it through the Ray UI.
