### ISSUE TITLE
[tune] Allow Trainable constructors with arguments and setting them in tune.run

### ISSUE THREAD

**Issue by nlgranger** [ray-project/ray#6417]
This is a follow-up to #1762 which was concerned by the functional API and reported a different use-case.
We often have options that are not hyperparameters (directory of the dataset files, batch size, number of data loader workers, ...). It would be nice to have an option in `tune.run` for parameters to be picked-up by the Trainable subclass constructor instead of `_setup()`. Something like an `init_args` argument in `tune.run` taking a tuple or a dict of constructor arguments.

Here is a bunch of arguments to support this idea:
- constructor arguments being passed to the constructor is more idiomatic
- static code analysis tools treat attribute assignment in the constructor as being part of the class interface, so using the constructor to initialize instance attributes is preferable.
- constructor arguments can be passed once while `_configure` can be called multiple times, this enables users to put slow operations in the constructor (for example loading a dataset, starting custom worker processes) and then have the Trainable re-used efficiently across multiple training iterations/configurations.

The following workarounds to implement the above idea have drawbacks:
- Use global variables
  - leads to variable name collisions
  - Cannot handle different sets of options
- Put the options in the config passed to `_setup` 
  - it is cleaner to keep them separated, the config will often be a python source file, but options such as dataset dir may change depending on the server the code runs on, and therefore is more easily set via command line arguments.
  - no explicit re-use across iterations (although one could check for earlier configuration assignments)
- Create a subclass on the fly with hardcoded `__init__` arguments (see example below)
  - this is not pretty
  - I think ray/tune serializes the Trainable and I'm not sure dynamically created classes play well with that, at the very least it will be confusing.

```python
args = argparser.parse_args()

class C(MySubclassOfTraining):
    def __init__(self):
        super().__init__(args.data_dir, dataset, args.num_workers)
```

**Comment by richardliaw** [comment]
What about the following?

```python
class TrainableV2():
    def __init__(self):
        pass

class YourSubClass(TrainableV2):
    """Training class.

    __init__ is called once. `configure` can be called between 
    train_steps. For restoring, we will see the following order of method
    invocation:

         __init__ -> configure -> restore

	"""
    def __init__(self, data, dataset, dataloaders):
        TrainableV2.__init__(self)

    def configure(self, config):
        pass

    def train_step(self, info={}):
        pass

    def save(self, checkpoint):
        pass

    def restore(self, checkpoint):
        pass
```

**Comment by nlgranger** [comment]
Yes this would be nice.

**Comment by krfricke** [comment]
With #10679 we now have a general utility to pass arbitrary objects via the Ray object store to tune trainables. If this does not solve your use-case, feel free to re-open.
