### ISSUE TITLE
reporter.py using large amounts of CPU in get_workers()

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6419]
### What is the problem?

reporter.py uses a lot of CPU on machines with many processes running. The culprit from profiling is get_workers:
```
    memory_info (psutil/_pslinux.py:1608)
    wrapper (psutil/_pslinux.py:1402)
    memory_info (psutil/__init__.py:1048)
    wrapper (psutil/_common.py:342)
    as_dict (psutil/__init__.py:527)
    <listcomp> (ray/reporter.py:118)
    get_workers (ray/reporter.py:117)
    get_all_stats (ray/reporter.py:143)
    perform_iteration (ray/reporter.py:152)
    run (ray/reporter.py:163)
    <module> (ray/reporter.py:205)
```

The get workers call is this:
```
    @staticmethod
    def get_workers():
        return [
            x.as_dict(attrs=[
                "pid", "create_time", "cpu_percent", "cpu_times", "name",
                "cmdline", "memory_info", "memory_full_info"
            ]) for x in psutil.process_iter(attrs=["cmdline"])
            if is_worker(x.info["cmdline"])
        ]
```

We call this twice a second by default.

cc @pcmoritz @mitchellstern

**Comment by ericl** [comment]
@edoakes does this also affect the current release?

**Comment by zplizzi** [comment]
I see this issue also in 0.7.6. I have a training job involving ~8 actors, and get informed on launch that there are something like 25 ray workers. `reporter.py` typically consumes like 75% of a CPU core, see this typical screenshot from htop:

![image](https://user-images.githubusercontent.com/5598968/71216232-d85de300-226e-11ea-8ca8-e2e29b21a8be.png)

For a quick fix, is there a way to just disable reporter? It's pretty annoying to have to kill the process each time you need all your cores.

**Comment by zplizzi** [comment]
Whoops, didn't notice there was a new release. It seems marginally better in 0.8.0, around 50% cpu on the same example:

![image](https://user-images.githubusercontent.com/5598968/71216982-11975280-2271-11ea-9087-fc66a2edf9bc.png)
