### ISSUE TITLE
[direct call] Child actors get leaked when their parent dies

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6422]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
This branch:  https://github.com/ray-project/ray/pull/6367

https://github.com/ray-project/ray/blob/master/ci/long_running_tests/workloads/actor_deaths.py

will leak "Child" actors. After a while, the number of "Child" counts here will rise above 25, which indicates a leak: `ps aux | grep ray::Parent | grep -v grep | wc -l; ps aux | grep ray::Child | grep -v grep | wc -l`

This never happens if RAY_FORCE_DIRECT=0.

Note that this is despite the explicit __ray_terminate__ calls to the child actors, so it is likely a race condition between killing the parent and child.

**Comment by edoakes** [comment]
@ericl do you know if this is fixed? Else @simon-mo will test/fix for release.

**Comment by ericl** [comment]
@stephanie-wang says it is fixed (for all task types).
