### ISSUE TITLE
[docs] Add brief instructions for installing Ray when using Conda.

### ISSUE THREAD

**Issue by deanwampler** [ray-project/ray#6426]
### Describe your feature request
It would be good to provide the few commands required to install Ray when using Anaconda. While not difficult for experienced Anaconda users, they might first try `conda install ray`, which doesn't work, then have to install `pip`, then `ray`. Just showing these commands eliminates this tiny bit of friction for them. Eventually, we should add a Conda Forge package (another ticket).

**Comment by richardliaw** [comment]
Merged.
