### ISSUE TITLE
[rllib] doc: typo: on_postprocess_batch -> on_postprocess_traj

### ISSUE THREAD

**Issue by Maltimore** [ray-project/ray#6437]
### What is the problem?
In the documentation it says "on_postprocess_batch" instead of "on_postprocess_traj" in this sentence: "Note that in the on_postprocess_batch callback you have full access to the trajectory batch [...]." (https://ray.readthedocs.io/en/latest/rllib-training.html)
It's just a minor mistake but it seriously threw me off, searching the docs and the code for quite a while for the "on_postprocess_batch" function.

*Ray version and other system information (Python version, TensorFlow version, OS):*
0.7.6
*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*
does not apply

I'd be happy to make a pull request.

**Comment by pcmoritz** [comment]
Thanks for reporting this, making a pull request would be really great :)
