### ISSUE TITLE
[tune] mnist_pytorch example: TypeError: run() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by ManosMagnus** [ray-project/ray#6440]
### What is the problem?
Missing `reporter` parameter in [mnist_pytorch.py](https://github.com/ray-project/ray/blob/3db8faab0d5c2fa86dd3439eea0b5cd65877d221/python/ray/tune/examples/mnist_pytorch.py#L94) example. 

If provide to `tune.run` only one parameter you get the following error:

```
(pid=23357) Traceback (most recent call last):
(pid=23357)   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=23357)     self.run()
(pid=23357)   File "_env/lib/python3.6/site-packages/ray/tune/function_runner.py", line 116, in run
(pid=23357)     raise e
(pid=23357)   File "_env/lib/python3.6/site-packages/ray/tune/function_runner.py", line 97, in run
(pid=23357)     self._entrypoint()
(pid=23357)   File "_env/lib/python3.6/site-packages/ray/tune/function_runner.py", line 145, in entrypoint
(pid=23357)     return self._trainable_func(config, self._status_reporter)
(pid=23357)   File "_env/lib/python3.6/site-packages/ray/tune/function_runner.py", line 261, in _trainable_func
(pid=23357)     output = train_func(config, reporter)
(pid=23357) TypeError: run() takes 2 positional arguments but 3 were given
```

### How to fix it?

Change the current method signature to `train_mnist(config, reporter)`

I could prepare a PR if you confirm that is an actually issue.

Thank you.

**Comment by hhbyyh** [comment]
Hi @ManosMagnus Could you please share the code to repro the issue? 
I cannot find the usage of reporter in master mnist_pytorch example.
