### ISSUE TITLE
Pyarrow GLIBC_2.14 not found

### ISSUE THREAD

**Issue by harplife** [ray-project/ray#6451]
Hello,

Problem
- Tried to import Ray, got ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found

Environment 
- CentOs 6.10
- Python 3.6
- Conda/Anaconda3
- Ray 0.7.3
- Modin 0.6.3
- Pyarrow 0.15.1
- GLIBC 2.12

Steps to replicate
1. create conda environment with python 3.6
2. conda install modin[ray]
3. import ray

I realize the issue is quite straight-forward,
obviously I need GLIBC 2.14.
In order to solve this problem,
I've installed GLIBC 2.14 - but I have no idea how I'm going to tell Ray or Pyarrow to look for it.

I raised the same issue on [Pyarrow](https://github.com/apache/arrow/issues/6012),
and their answer is that I should reach Ray instead.

Please help!

**Comment by mehrdadn** [comment]
I think #7146 removed the dependency on PyArrow, so this issue may be resolved.

Would you mind checking and letting us know if this issue still occurs?

**Comment by mehrdadn** [comment]
Oh, sorry, this is not released yet. We'll see if we can have this in the next release; if not, it should happen in the following release. If the issue still comes up when the PyArrow dependency is removed please do let us know.

**Comment by gveda** [comment]
I just installed ray on an RHEL 6.8 system with glibc 2.12, and encountered the same error on importing ray. @mehrdadn 's comment above seems to suggest that I should not see this error. Can you please suggest a resolution?
The output of pip install ray was:
Successfully installed aiohttp-3.6.2 async-timeout-3.0.1 filelock-3.0.12 google-2.0.3 idna-ssl-1.1.0 multidict-4.7.6 py-spy-0.3.3 **ray-0.8.5** redis-3.4.1 typing-extensions-3.7.4.2 yarl-1.4.2

**Comment by bibbygoodwin** [comment]
I'm having the same issue: ray 0.8.5 installed via pip, but running any script that uses it results in `OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /users/me/miniconda3/envs/ray_env/lib/python3.7/site-packages/ray/_raylet.so)`

**Comment by mehrdadn** [comment]
@bibbygoodwin What OS/version are you running?

@bibabolynn, @gveda: Would you mind running `ldd python/ray/_raylet.so` and letting me know the output?

**Comment by wzmucas** [comment]
Dear @mehrdadn 
I  got the same problem when install pay with pip. 

- Red Hat Enterprise Linux Server release 6.10 (Santiago)
- Python 3.7.3
- Ray 0.8.5

After using `python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so`, I got some **no found** results:
`python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so:` /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/users/zmwu/python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by python/miniconda3/lib/python3.7/site-packages/ray/_raylet.so)
        linux-vdso.so.1 =>  (0x00007ffe8dac0000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f7a1e6a1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7a1e41c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7a1e1ff000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f7a1dff7000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7a1dde0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7a1da4c000)
        /lib64/ld-linux-x86-64.so.2 (0x00005571697ab000)`

when `strings /usr/lib64/libstdc++.so.6 | grep GLIBC`, I got result like this:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by mehrdadn** [comment]
Thank @wzmucas. Note that the original issue here was the question of how to make Ray work _after_ glibc 2.14 is installed. But if my understanding of the issue is correct, our builds depend on glibc 2.14, and you don't appear to have glibc 2.14 installed at all.

Is this correct?  
If so, can you install glibc and see if this works?  
If not, where is the shared library for glibc 2.14 currently installed on your system (since Ray appears unable to find it)?

**Comment by bibbygoodwin** [comment]
> @bibbygoodwin What OS/version are you running?

Scientific Linux 6.5. I see on closer inspection of the original question that @mehrdadn is right: this is about Ray not finding GLIBC even after installation. Sorry if I derailed a little.

Having installed GLIBC 2.14 locally, the problem is now similar, but instead with `OSError: /lib64/libc.so.6: version 'GLIBC_2.15' not found`. Clearly there's no reason why the Ray maintainers should be expected to help with dependency issues, but I wonder whether someone wiser than me might be able to suggest which version of GLIBC Ray actually requires? I don't want to have to increment 2.x by .1 until I hit a match!

**Comment by mehrdadn** [comment]
@bibbygoodwin I'm not entirely sure but I do see the following from the latest nightly wheels:

```
$ find -name "*.so" | xargs -r objdump -T | grep "GLIBC" | awk '{ print $5 }' | sort -V | uniq
GLIBCXX_3.4
GLIBCXX_3.4.9
GLIBCXX_3.4.11
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
```

So perhaps try installing 2.17 to see if that covers everything?

**Comment by bibbygoodwin** [comment]
Thanks so much for the quick reply @mehrdadn. Looks like I was only 2 trial-and-errors away! I will try with `GLIBC_2.17` and report back, including build instructions for anyone else coming across this issue.

**Comment by serbinsh** [comment]
@bibbygoodwin did you ever solve this issue? I have RHEL 6.10 and am running into a similar issue in a conda environment.  You can see the issue here: https://github.com/isofit/isofit/issues/130

I built two new glibc versions, 2.17 and 2.19 but because of all of the depends on glibc enabling these break many other things, like conda!  I was hoping there might be a way to point ray to a specific lib dir but not actually enable the newer glibc?  Or is there another way around this in conda?  

Agreed, dependency issues arent really your issue but I was hoping it may be an easy work around as given the current situation, updating our cluster to a later LTS OS isnt high priority or easy to do

**Comment by nirvana-msu** [comment]
In case it helps someone, here's a recipe on how one could build Ray `manylinux2010` wheels, compatible with RHEL / CentOS 6.

Similar to [Building manylinux2014 wheels](https://github.com/ray-project/ray/blob/35ec91c4e04c67adc7123aa8461cf50923a316b4/python/README-building-wheels.md#building-manylinux2014-wheels) guide, we'd be building using manylinux dococker image, but in this case we need `quay.io/pypa/manylinux2010_x86_64` image.

e.g. to build Ray 1.2.0 the steps are:

1) `git checkout b87fc1be5505c577f01807fd342e0cdb2e129081`
2) Add [build-wheel-manylinux2010.sh](https://gist.github.com/nirvana-msu/7b3efdea7d18044143f7c74b67f366a6) build script.
3) `docker run -e TRAVIS_COMMIT=b87fc1be5505c577f01807fd342e0cdb2e129081 --rm -w /ray -v `pwd`:/ray -ti quay.io/pypa/manylinux2010_x86_64  /ray/python/build-wheel-manylinux2010.sh`

The build script is almost the same as that for `manylinux2014` wheels, with the key changes:
1) Node version changed to 11, which is [the latest](https://github.com/nodejs/node/blob/v11.x/BUILDING.md#supported-platforms) that works with glibc 2.12.
2) Bazel has to be built from source, e.g. as described [here](https://github.com/bazelbuild/bazel/issues/5893#issuecomment-817383403). We should build same Bazel version as the one declared as `SUPPORTED_BAZEL` in `setup.py`, i.e. `3.2.0` for Ray `1.2.0`.
3) Also uncommented the line `echo "build --config=manylinux2010" >> /root/.bazelrc` and obviously renamed the wheel to `manylinux2010`.
