### ISSUE TITLE
local scheduler: don't try to start workers or dispatch tasks when num_cpus is zero

### ISSUE THREAD

**Issue by atumanov** [ray-project/ray#648]
There's a common use case for starting the local scheduler with zero cpus to ensure that all tasks submitted by the local driver go remotely (e.g., from your laptop to the cloud).
This currently works, but the local scheduler will still call dispatch_tasks and attempt to start a worker even though the configured number of cpus is zero. As an optimization, we should make sure no workers are started, perhaps by returning early from dispatch_tasks when `num_cpus == 0`.
As a smaller sub-issue, we shouldn't log any warning messages about the missing start worker command either, since the correct behavior is for the local scheduler *not* to attempt to start any workers in this case.

Symptomatically, you will see something like this:
```
$ python python/ray/global_scheduler/test/test.py 
test_integration_many_tasks (__main__.TestGlobalScheduler) ... 67258:M 07 Jun 16:44:33.107 # Server started, Redis version 3.9.102
Waiting for redis server at 127.0.0.1:61372 to respond...
67259:M 07 Jun 16:44:33.216 # Server started, Redis version 3.9.102
Waiting for redis server at 127.0.0.1:62734 to respond...
Allowing the Plasma store to use up to 1GB of memory.
[WARN] (/Users/atumanov/devrepo/github/ray-mydev/src/local_scheduler/local_scheduler.cc:321) No valid command to start a worker provided, local scheduler will not start any workers.
Allowing the Plasma store to use up to 1GB of memory.
[WARN] (/Users/atumanov/devrepo/github/ray-mydev/src/local_scheduler/local_scheduler.cc:321) No valid command to start a worker provided, local scheduler will not start any workers.
[WARN] (/Users/atumanov/devrepo/github/ray-mydev/src/local_scheduler/local_scheduler.cc:223) No valid command to start worker provided. Cannot start worker.
[WARN] (/Users/atumanov/devrepo/github/ray-mydev/src/local_scheduler/local_scheduler.cc:223) No valid command to start worker provided. Cannot start worker.
```

This is both self-inconsistent (i.e., warning says no workers will be started and then fails to start it) and sub-optimal (i.e., should not be trying to start a worker).

**Comment by robertnishihara** [comment]
I think this is fixed.
