### ISSUE TITLE
Getting list of failed actors

### ISSUE THREAD

**Issue by sebastiangonsal** [ray-project/ray#6482]
How do i get a list of failed actors?

**Comment by sebastiangonsal** [comment]
Something like `ray.get` but where i can get everything and filter on the state.

**Comment by richardliaw** [comment]
`ray.wait` will allow you to process actors one by one. Then, you can call `ray.get` and catch the exception.

**Comment by richardliaw** [comment]
Closing for now; feel free to reopen.
