### ISSUE TITLE
[ray] passing object ID to remote function in local_mode: docs & reality don't match

### ISSUE THREAD

**Issue by petrock99** [ray-project/ray#6483]
### What is the problem?
macOS Catalina 10.15.2 + python 3.7.4 + ray 0.7.6.  The [docs](https://ray.readthedocs.io/en/latest/walkthrough.html#remote-functions-tasks) state:

> Object IDs can also be passed into remote functions. When the function actually gets executed, the argument will be a retrieved as a regular Python object.

So if I pass an object ID to remote_function.remote() I would expect to get the value the object ID represents when remote_function is actually executed. However, when I run my python script in local_mode, I get a LocalModeObjectID not the value the object ID represents. If I try to pass this LocalModeObjectID to ray.get() I get this error:

> KeyError: 'Value for LocalModeObjectID(59272c2e47dd8d007979ee0bb4d2504375dc15cb) not found'

### Reproduction
```
import ray

@ray.remote
def remote_function(x):
    print(x)
    return 44
    
ray.init(local_mode=True)
x_id = ray.put({"X": 22})
func_id = remote_function.remote(x_id)
val = ray.get(func_id)
```
### Result
    Expected: {"X": 22} is printed
    Actual: LocalModeObjectID(7349b5614fc73159a9f5ded0a5b4000000000000) is printed

**Comment by edoakes** [comment]
This is fixed as of `0.7.7`. Please try upgrading ray and let us know if it's still an issue.
