### ISSUE TITLE
How to perform reward wrapper for MultiAgentEnv

### ISSUE THREAD

**Issue by sxyd** [ray-project/ray#6491]
### What is your question?
Ray has provided reward wrapper for `gym.Env `(https://github.com/openai/gym/blob/master/gym/wrappers/transform_reward.py). But I find it cannot be applid to `MultiAgentEnv `(`from ray.rllib.env.multi_agent_env import MultiAgentEnv`). So, how to perform reward wrapper for MultiAgentEnv?

*Ray version and other system information (Python version, TensorFlow version, OS):*
- Python 3.7
- Tensorflow 2.0
- Ray 0.8.0 dev6

**Comment by josjo80** [comment]
For a MultiAgentEnv, the reward needs to be returned to the policy optimizer as a dictionary.  I think you'd have to rewrite the wrapper to iterate through `reward`, which assumes it is passed in as a list.
```
def reward(self, reward):
    rews = {i: self.f(reward[i]) for i in range(len(reward))}
    return rews
```

**Comment by edoakes** [comment]
Stale - please open new issue if still relevant
