### ISSUE TITLE
Use hiredis to decode redis outputs for python 3.

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#652]
In Python3, using the standard Redis Client will encode all strings as a byte literal. Working with these byte literals in DataFrames is quite a hassle, since values such as strings and integers retain their byte format.

Using the client to automatically decode Redis responses will help the user experience, especially when working with the Global State. However, in Python3, the redis-py client's PythonParser throws many errors when working with the decoding. Installing `hiredis` can sidestep these errors.

Example code:
```
import ray
import redis

ray.init()
addr, port = ray.worker.global_worker.redis_address.split(":")
rc = redis.StrictRedis(host=addr, port=port, decode_responses=True)
print(rc.keys())
```
This code will work with hiredis but not without.

**Comment by robertnishihara** [comment]
What about Python 2? If this only works for Python 3 then it may not simplify the code too much.

**Comment by richardliaw** [comment]
Good point. 

`rc.keys()` will only print with hiredis in both python3 and python2. 

On the other point, in python3, there's the added benefit that byte literals will be automatically decoded. However in python2, this isn't the case - byte literals are still left as byte literals.

**Comment by robertnishihara** [comment]
Closing for now since the Python 2 issue may make it more of a hassle than it's worth. We can revisit this if it seems like the right solution.
