### ISSUE TITLE
[rllib] PrioritizedReplayBuffer.update_priorities on overwritten samples?

### ISSUE THREAD

**Issue by zplizzi** [ray-project/ray#6534]
From reviewing the source of PrioritizedReplayBuffer.update_priorities, it doesn't seem like there's any mechanism to keep track of samples that have been overwritten in the buffer.

The failure scenario would be:
1) Sample a batch of samples with indices `idxs` from the buffer for training
2) train on the batch and get updated priorities
3) while training on the batch, new samples have been received from the game-play workers. some of the indices in `idxs` may have now been replaced by new samples, due to the fact that `ReplayBuffer` is a fixed-size ring buffer
4) call `buffer.update_priorities()` with the new priorities for `idxs`. some of these indices no longer correspond to the data sample they originally did when they were sampled, so the priority will be incorrect when applied to the new sample.

**Comment by ericl** [comment]
Good catch! Maybe we can explicitly track the version of the data we are overwriting or something?
