### ISSUE TITLE
Timeline for dropping Python 2 support

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#6580]
With the end of Python 2 nearing at a rapid pace (https://pythonclock.org/), we are looking into dropping Python 2 support for new releases after Jan 1, 2020. The main benefit would be that quite a bit of our code could be simplified (especially serialization). Several of the new features we're developing (Ray serve and the Ray dashboard) already don't support Python 2.

If you have a project using Ray/planning to use Ray that crucially depends on Python 2 support for new releases, please let us know about it. See also https://python3statement.org/.

**Comment by robertnishihara** [comment]
Dropped in #6601.

**Comment by richardliaw** [comment]
@robertnishihara is it ok to pin this issue (or at least a note that we have officially dropped Py3) until the next release? 

It was really only visible for 7 days (and during holiday season).

**Comment by robertnishihara** [comment]
@richardliaw done.
