### ISSUE TITLE
Some flake cases failed on master

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#6582]
Some cases in auto scaling test some times failed on current master. @ericl Could you take a look?

AutoscalingTest.testSetupCommandsWithNoNodeCaching
AutoscalingTest.testSetupCommandsWithStoppedNodeCaching

https://travis-ci.com/ray-project/ray/jobs/269096956
https://travis-ci.com/ray-project/ray/jobs/269160225

**Comment by micafan** [comment]
Hi @ericl, could you take a look at those test, I found it appears a lot in my PR's ci.
