### ISSUE TITLE
Too many open files problem

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#6583]
### What is the problem?

On unchanged scripts that have been used for months I am now getting the following error at the beginning of the job:

`'COULD NOT CREATE A LOGGINGFILE 20191223-013101.1509162!Could not create logging file: Too may open files" `

This is on a cluster where the boxes in the cluster had a fresh reboot before installing the ray whl was installed and ray jobs are the only thing running on the cluster.  

Ray is started on each node with a ulimit -n 262144;ray start ....  line. 

Fix:  On the box where I launch the program if I set ulimit -n 100000 (sure could be less) then I can run the programs fine.  I have never needed to set ulimit for the driver program shell before.  

This was not an initial issue with this version of ray, I have been running dozens of jobs over the last few days with no issues.  Something after some period of time isnt releasing files?  The only solution I have tried is increasing the ulimit -n.  I am guessing that a reboot of the box would also clean things up but have not been able to do that.

Version: Ray whl from master on 20 Dec 2019, python from miniconda 3.7.5, linux redhat 7.6

### Reproduction
Any script, ray fails almost immediately not able to log to a file

**Comment by virtualluke** [comment]
any thoughts on what changed?

**Comment by edoakes** [comment]
@virtualluke is this still a problem on latest builds? Also, could you please post the output of `ls /tmp/ray/session_latest/logs/`?
