### ISSUE TITLE
[rllib] Testing an agent in another environment than the one it is trained on?

### ISSUE THREAD

**Issue by alversafa** [ray-project/ray#6589]
How can we train an agent in one environment and evaluate it in another? Say I want to train an agent in Pong and display its performance in Breakout. (Assuming that state and action dimensions are the same.)

**Comment by eugenevinitsky** [comment]
If you look at the rollout script, you can pass the different env in as an argument: https://github.com/ray-project/ray/blob/master/rllib/rollout.py.
Look at the argparse arguments. Hope that helps!

**Comment by alversafa** [comment]
Thanks, it is helpful. However, as far as I understand this is for the case where we first fully train on an environment and test on another. What I was trying to ask was whether if there is a way to test an agent in a different environment while training on its own. So in this case, we regularly evaluate the agent on a different environment during the training process.

**Comment by alversafa** [comment]
Could it be possible that this can somehow be done with `evaluation_config`? I couldn't find any documentation on this.

**Comment by alversafa** [comment]
The conversation continues with issue #4614 .
