### ISSUE TITLE
autoscalar, webui, python2, python3 confusion!

### ISSUE THREAD

**Issue by johncleveland** [ray-project/ray#6609]
using python 3.7.3, ubuntu 18.04.3 

### What is your question?
How do I get the webui to work using the local autoscaler yaml file?

It appears that the webui requires python3 however, the local autoscaler starts a python2 process.

I have tried to add --include-webui to the local example-full.yaml  on both the head and worker sections for start up.
If I start a process from the command line and then open a REPL and try to join the cluster using
ray.init( redis_address ="", include_webui=True)  the webui part is ignored.

thanks john

**Comment by richardliaw** [comment]
Sorry for the late response.

We've deprecated Python2. To use the Webui with the autoscaler, you should be able to do `ray dashboard [yaml]`.

The web UI should now start automatically.

Feel free to reopen this issue if you have any more questions!
