### ISSUE TITLE
[master] Actor calls hang forever after creation task failure

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#6612]
### What is the problem?

This occurs on master after https://github.com/ray-project/ray/pull/6570/files

### Reproduction
```
import os
import random
import ray


@ray.remote(max_reconstructions=0)
class Actor(object):
    def __init__(self):
        if random.random() < 0.8:
            print("crash")
            os._exit(0)
        else:
            print("no crash")

    def f(self):
        return "ACTOR OK"

ray.init()

a = Actor.remote()
ray.get(a.f.remote())  # this hangs forever after the change
```

**Comment by ericl** [comment]
Note that if `max_reconstructions` > 0, then the hang will occur after resubmissions fail. I think the issue is that the owner is no longer publishing the actor death if the task fails.

**Comment by zhijunfu** [comment]
yes, thanks for the catch. I've verified the hang issue is fixed with this PR.

https://github.com/ray-project/ray/pull/6617
