### ISSUE TITLE
Node didn't show in web UI after instantiate ray actor

### ISSUE THREAD

**Issue by fahadh4ilyas** [ray-project/ray#6619]
## System information

* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 18.04.3 LTS
* **Ray installed from (source or binary):** binary
* **Ray version:** 0.8.0
* **Python version:** 3.6.7

## Describe the problem

I have a Keras model instantiate inside a class to predict something and I'm using ray to create ray actors of the classes. Before I create the ray actors, there are still worker that is in idle position based on web UI. After I created the ray actor, number of workers slowly decreased and finally all gone (I created for each workers one ray actor). But, if I check using `htop`, the workers are still there running `className.__init__()`. I already installed all package for ray such as `psutil`. `setproctitle`, `aiohttp`, `libgcc`. The problem however didn't show if I'm using ray version `0.7.6`.

## Source code / logs

```python
# here is script for instantiate the ray actors
from script_name import className
import ray
ray.init()

className = ray.remote(className)

# parameter i is used for set which core is used for the ray actors
# there is a 64 cores CPU in my computer
models = [ className._remote(kwargs={'i':i},num_cpus=1) for i in range(64)]

# some command after here
```

**Comment by edoakes** [comment]
@fahadh4ilyas Is this still an issue on the latest release/master? If not, could you please post a fully runnable reproducible script?
