### ISSUE TITLE
Permissions issues when running on cluster

### ISSUE THREAD

**Issue by alanamarzoev** [ray-project/ray#662]
When running Ray on a multi-user cluster, there are instances where you aren't able to write to files that other users have created (e.g. - 'tmp/raylogs'). Currently, the fix is to manually change the hard coding of what file to write to.

**Comment by robertnishihara** [comment]
I believe the issue here is the same as in #526 and should be fixed by #532.

In this case, maybe someone was using Ray on the same cluster before #532 was merged.
