### ISSUE TITLE
Build error using bazel 1.0.0 version in CLion

### ISSUE THREAD

**Issue by Jiayi-Liao** [ray-project/ray#6626]
I'm using bazel 1.0.0 version to build master branch in CLion with bazel plugin but it fails with message below:

```
ERROR: /xx/projects/ray/BUILD.bazel:760:1: no such target '@plasma//:cpp/src/plasma/format/common.fbs': target 'cpp/src/plasma/format/common.fbs' not declared in package '' defined by /private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/plasma/BUILD.bazel and referenced by '//:common_fbs_srcs'
ERROR: /Users/xx/projects/ray/BUILD.bazel:760:1: no such target '@plasma//:cpp/src/plasma/format/common.fbs': target 'cpp/src/plasma/format/common.fbs' not declared in package '' defined by /private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/plasma/BUILD.bazel and referenced by '//:common_fbs_includes'
ERROR: /private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/local_config_cc/BUILD:48:1: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on cc_toolchain_suite rule @local_config_cc//:toolchain: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/local_config_cc/BUILD", line 48
                @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect(...)
        File "/private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/intellij_aspect/intellij_info_bundled.bzl", line 53, in _aspect_impl
                intellij_info_aspect_impl(target, ctx, semantics)
        File "/private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/intellij_aspect/intellij_info_impl.bzl", line 785, in intellij_info_aspect_impl
                collect_c_toolchain_info(target, ctx, semantics, ide_info, <2 more arguments>)
        File "/private/var/tmp/_bazel_xx/0dbee3530b4b132aa2c4b01c8e9a1aae/external/intellij_aspect/intellij_info_impl.bzl", line 365, in collect_c_toolchain_info
                cc_common.configure_features(cc_toolchain = cpp_toolchain, requ..., ...))
Incompatible flag --incompatible_require_ctx_in_configure_features has been flipped, and the mandatory parameter 'ctx' of cc_common.configure_features is missing. Please add 'ctx' as a named parameter. See https://github.com/bazelbuild/bazel/issues/7793 for details.

```

I've tried bazel 1.2.1 and 0.29 and it doesn't work also. Does anyone know how to fix this?

Thanks in advance.

**Comment by jovany-wang** [comment]
Try it again with bazel 1.1?

**Comment by buptljy** [comment]
> Try it again with bazel 1.1?

@jovany-wang Thanks for your attention on this. I've tride both bazel 1.1. and 1.0, but they both didn't work. It seems there're two errors here:

1. no such target '@plasma....'
2. Incompatible flag --incompatible_require_ctx_in_configure_features.

For the first error, do I need to do something else to include the plasma target?

BTW, do you have any guide for compiling the project?

**Comment by pcmoritz** [comment]
@buptljy Bazel 1.1.0 should definitely work, you can compile the project as described in https://ray.readthedocs.io/en/latest/installation.html#install-ray. Let us know if the steps in the description don't work for you (and what your OS and environment is).

**Comment by buptljy** [comment]
> @buptljy Bazel 1.1.0 should definitely work, you can compile the project as described in https://ray.readthedocs.io/en/latest/installation.html#install-ray. Let us know if the steps in the description don't work for you (and what your OS and environment is).

Thanks. There is no error messages if I follow the guide in the link. But what I want to do is reading the source codes of this project instead of installing it. 

I'm sorry that I think I've misguided you in the description. The message in the description comes from CLion when I compile the project in CLion with bazel plugin. And the IDE cannot index the codes if the building fails.

OS: macOS
CLion: 2018.2
Python: 3.7.4(anaconda)

**Comment by mattip** [comment]
I think we should close this. Ray now builds with bazel 4.2.2.
