### ISSUE TITLE
RLlib: stop condition not met 

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#6627]
rllib
### What is the problem?
if you give "stop":{"episodes_total":X} and X is smaller than train_batch_size then it terminates after train_batch_size without any warning that something is wrong with the parameters. This is problematic when debugging and the train_batch_size and other parameters are implicit.
*Ray version and other system information (Python version, TensorFlow version, OS):*

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*

### Reproduction
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

**Comment by edoakes** [comment]
@AmeerHajAli please provide a reproducible script (or fix this in rllib)

**Comment by AmeerHajAli** [comment]
here is a simple example:
```
import ray
from ray import tune
ray.init()
tune.run(
    "PPO",
    stop={"timesteps_total": 10},
    config={
        "env": "CartPole-v0",
        "lr": tune.grid_search([1e-3,1e-4])
    })
```
this will run for 4000 steps rather than 10 steps.
