### ISSUE TITLE
Dashboard link printed in ray.init slightly off in Jupyter.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#6635]
I was just running the parameter server gallery example https://ray.readthedocs.io/en/latest/auto_examples/plot_parameter_server.html, and I noticed that when we print the dashboard URL, Jupyter thinks the link is *"http://127.0.0.1:8265."* (including the period at the end) instead of *"http://127.0.0.1:8265"*. As a result, when you click on it, it doesn't work.

See the attached screenshot.

<img width="745" alt="Screen Shot 2019-12-29 at 8 23 33 PM" src="https://user-images.githubusercontent.com/249517/71568147-b720a200-2a79-11ea-905f-f84be9edd3a1.png">

**Comment by harrisonfeng** [comment]
I fix this with #6683
