### ISSUE TITLE
Any plans to support DECENTRALIZED DISTRIBUTED PPO?

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#6636]
Any plans to support DECENTRALIZED DISTRIBUTED PPO algorithm?
Best wishes,
Simon

**Comment by ericl** [comment]
Multi-node PPO has been on the backlog for a while, though afaik most of our current users are happy enough with multi GPU on a single node.

Do you have a use case that requires >16 GPUs?

**Comment by forhonourlx** [comment]
Hi Eric,
For me, I am mainly using RL for financial decision with medium-large action space and complex environment. It is hard to say whether these tasks require mininum 16 GPUs.
DD-PPO exhibits high efficiently scaling speedup and  shows the ability of continous improvement, which I really need. It implies the productivity of conversion time to quantity and quality.
In my opinion, if any flexible and easy-to-use multi-nodes RL framework is born, then the needs of scaling RL will be activated and emerges.
Hoping RLlib be the first multi-nodes distributed RL framework ready to use.

**Comment by ericl** [comment]
Makes sense. There are some questions on how to best implement.

We could use torch.DistributedDataParallel as in the DD-PPO paper, but that would only work for torch policies. Maybe we could use MultiWorkerMirroredStrategy for TF training.

**Comment by forhonourlx** [comment]
Hi @ericl,
Another question: I notice the wide gap between IMPALA and PPO with RLlib, what's your opinion of whether DD-PPO or distributed IMPALA is stronger?
Will RLlib implement a multi-node IMPALA?

Best wishes,

**Comment by ericl** [comment]
@forhonourlx you can try out https://github.com/ray-project/ray/pull/6918, I haven't benchmarked it in a cluster yet but it does train for PyTorch PPO.

> DD-PPO or distributed IMPALA is stronger

You can check out some analysis of PPO vs IMPALA (and how to combine their strengths) here: https://openreview.net/forum?id=BJeGlJStPr

> Will RLlib implement a multi-node IMPALA?

Possibly, though not in the short term.
