### ISSUE TITLE
[tune] How to represent categorical and nested variable in config space?

### ISSUE THREAD

**Issue by ben-arnao** [ray-project/ray#6651]
I want to use Tune because it supports BOHB but i am unsure of how to incorporate categorical and nested parameters into the search space.

Nested parameterization is pretty common for optimization of multi-layer networks as the # of parameters will change will the number of layers. Is there any support for this kind of optimization?

**Comment by ujvl** [comment]
you can specify conditional distributions as done here https://ray.readthedocs.io/en/latest/tune-usage.html#tune-search-space-default

**Comment by kifarid** [comment]
I am not sure if the question is closed, It is still not clear how to use conditional distributions with BOHB or how to specify a nested CS. For example, how can I use BOHB to tune the parameters and number of layers of the model when using PPO as a trainable?
1- the tune.sample_from does not work with BOHB for me 
2- using the ConfigurationSpace supports conditions, which is nice, but how can I specify a nested Hyperparameter like "fcnet_hiddens" in "model" in the configs of PPO
