### ISSUE TITLE
[rllib] How to support multiple observations? 

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#6657]
Happy New Year Everyone!
I notice that the RL papers of real-time strategy games or MOBA games give an algorithm illustration having different network components for observation of different data-structure(low-dim or high-dim).
Some auxiliary observations have great impacts in many RL environments.
Could RLlib apply multiple network components to multiple observations?
Thanks in advance.

**Comment by ericl** [comment]
You can use a `Dict` or `Tuple` observation space to support complex observations. To customize the network processing use custom models: https://ray.readthedocs.io/en/latest/rllib-models.html
