### ISSUE TITLE
[tune] Handle nan case for AsynchScheduler

### ISSUE THREAD

**Issue by hugwi** [ray-project/ray#6659]
To deal with the case of recording nan values i would suggest changing from np.percentile to np.nanpercentile in this line.

https://github.com/ray-project/ray/blob/f7455839bf5686cf990c9e6625c6ada9a3ffd7c8/python/ray/tune/schedulers/async_hyperband.py#L145-L148

As stated in https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanpercentile.html#numpy.nanpercentile any time a nan result is recorded this will result in the cutoff being nan.

>>> array([[10.,  nan,   4.],
      [ 3.,   2.,   1.]])
>>> np.percentile(a, 50)
nan

Ultimately leading to this line evaluating to false, preventing any following trial from stopping. 
https://github.com/ray-project/ray/blob/f7455839bf5686cf990c9e6625c6ada9a3ffd7c8/python/ray/tune/schedulers/async_hyperband.py#L157-L158

**Comment by hhbyyh** [comment]
I think the change is good. cc @richardliaw to confirm. Thanks for reporting the issue.

@hugwi would you want to create a pull request for it? perhaps with a unit test.

**Comment by richardliaw** [comment]
This change sounds good! @hugwi could you push a PR?

**Comment by edoakes** [comment]
@richardliaw @hugwi any follow up on this?

**Comment by hugwi** [comment]
Yeah, sorry haven't had time. Should be able to push a PR at the weekend @richardliaw @edoakes
