### ISSUE TITLE
[client]  External access to remote multiple node cluster?

### ISSUE THREAD

**Issue by frosk1** [ray-project/ray#6673]
I have a question concerning the access of a ray multi node cluster:

Considering a deployed cluster on AWS or kubernetes, how can a seperate python process from outside the cluster run tasks on the cluster?

e.g. A Web client tries to invoke python tasks,that should run within the Remote cluster.

Is there a Ray native API(maybe python) to connect to a remote cluster from within a python process running on a computer/server outside of the actual cluster?

If the actual documentation does offer an answer to this question, it is unfortunately not very clear (please correct me if I am wrong) . All I see is to connect to a node within the cluster and than invoke a python process on that node with: 'ray.init(address="auto")'. Is there no way to attach a local driver running on a external node to a remote cluster on a different node? Why is there no API that connects a local python process to an external cluster via ray.init(adress of external cluster )?

**Comment by ferrine** [comment]
same question

**Comment by richardliaw** [comment]
This is basically supported with Ray Client now: https://docs.ray.io/en/master/ray-client.html
