### ISSUE TITLE
rsync_up should have an option to sync with the workers

### ISSUE THREAD

**Issue by miguelvr** [ray-project/ray#6693]
The `rsync_up` would be a lot more useful if it synced not only between the local host and the head node, but also with the worker nodes.

If there is a mapped path between all the nodes, I don't see any reason for this not to be feasible.

The tools seem to be in place for this feature to happen, so I guess the changes just need to be done to the CLI.

Usage example
`ray rsync_up --sync-workers cluster.yaml`

**Comment by richardliaw** [comment]
Does `ray up cluster.yaml --restart-only` work for you?

**Comment by miguelvr** [comment]
I don't think it does. But, anyway, IMO it makes sense that rsync_up supports this
