### ISSUE TITLE
zsh: no matches found: ray[tune]

### ISSUE THREAD

**Issue by tom-doerr** [ray-project/ray#6696]
When trying to execute
```
pip install ray[tune] torch torchvision filelock
```
from the tune Quick Start guide (https://ray.readthedocs.io/en/latest/tune.html) I get the error message 
`zsh: no matches found: ray[tune]`. Zsh apparently tries to match some pattern. Is the package literally called ray[tune] or is it enough to install ray?
By the way: The package name `tune` seems to be still available, so it might make sense to use that name.

**Comment by misterdev** [comment]
I had the same problem with zsh treating `[]` as special characters, you can disable zsh globbing for pip adding  `alias pip='noglob pip'` to your `.zshrc`

**Comment by ujvl** [comment]
you can also just get around this with `pip install 'ray[tune]'`

**Comment by tom-doerr** [comment]
Thanks @misterdev @ujvl ! I would suggest changing the installation instructions to 
```
pip install 'ray[tune]' torch torchvision filelock
```
in the 'Quick Start' section. This does not seem to have any drawbacks and fixes the issue for ZSH-users.

**Comment by richardliaw** [comment]
Should be fixed!

**Comment by carvalhoamc** [comment]
It worked for me.

**Comment by yukiiwong** [comment]
Thanks @ujvl
