### ISSUE TITLE
[rllib] Best practices for loading/inferencing with trained policy?

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#6700]
I don't know if this constitutes a question or a documentation 'bug', but the title stands:

I've trained a model in RlLib, and it's saved in params.pkl. I'd like to load this, and inference with it so I can use it to play the game it's learned. There's no documentation or examples on how to inference that I can find, and the only documentation about loading saved policies is with .restore(), which it describes as being part of the trainer class and only used for restoring during training (which is very different than what I want to do).

Should I use ray.get()? That's what you use in non-RL cases at least, but it's described nowhere in the reference to RlLib.

**Comment by ericl** [comment]
Can you try https://ray.readthedocs.io/en/latest/rllib-training.html#computing-actions ?

**Comment by justinkterry** [comment]
Thanks! Are there any examples that use it?

**Comment by justinkterry** [comment]
That works, thank you.

**Comment by michaelliutt** [comment]
> That works, thank you.

I am actually working on the same idea. Could you have explain how you made it work?
