### ISSUE TITLE
Exception: Version mismatch. anybody help me?

### ISSUE THREAD

**Issue by gogo03** [ray-project/ray#6707]
when I using cond env,the error occurs like the following:
(keras-py36) ...@gnode005:/.$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> ray.init("168.168.2.131:6379")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ghpccgio/home/xiaoyouqing/.local/lib/python3.6/site-packages/ray/worker.py", line 801, in init
    if _internal_config else {})
  File "/ghpccgio/home/xiaoyouqing/.local/lib/python3.6/site-packages/ray/worker.py", line 1158, in connect
    raise e
  File "/ghpccgio/home/xiaoyouqing/.local/lib/python3.6/site-packages/ray/worker.py", line 1155, in connect
    ray.services.check_version_info(worker.redis_client)
  File "/ghpccgio/home/xiaoyouqing/.local/lib/python3.6/site-packages/ray/services.py", line 574, in check_version_info
    raise Exception(error_message)
Exception: Version mismatch: The cluster was started with:
    Ray: 0.8.0
    Python: 3.6.5
    Pyarrow: 0.14.0.RAY
This process on node 168.168.2.131 was started with:
    Ray: 0.8.0
    Python: 3.6.7
    Pyarrow: 0.14.0.RAY

system env is:
pci@pci:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
pci@pci:~$ which python
/home/pci/anaconda3/bin/python

could anybody help me??

**Comment by richardliaw** [comment]
It looks like you didn't start Ray in the conda environment?

**Comment by ijrsvt** [comment]
Please reopen if you are still having issues.

**Comment by chuckhope** [comment]
> It looks like you didn't start Ray in the conda environment?

Hi there, I use ray commit to run the .py file. I have changed the env to my conda but still, the command  " ray commit" uses default python to connect to the cluster which causes the mismatch error. Do you have any ideas? Thanks a lot. I think it may be related to the "ray.init()" in my .py file.
