### ISSUE TITLE
[tune] trial executor should use available_resources API when _update_avail_resources

### ISSUE THREAD

**Issue by JasonWayne** [ray-project/ray#6713]
### Describe your feature request
Accoding to the [code](https://github.com/ray-project/ray/blob/76c986bdc7c85a9efc42a19dd8c043c35f831ef8/python/ray/tune/ray_trial_executor.py#L422), tune use `ray.cluster_resources()` API in the trial executor's `_update_avail_resources` method.

```python
    def _update_avail_resources(self, num_retries=5):
        for i in range(num_retries):
            try:
                resources = ray.cluster_resources()
            except Exception:
                # TODO(rliaw): Remove this when local mode is fixed.
                # https://github.com/ray-project/ray/issues/4147
                logger.debug("Using resources for local machine.")
                resources = ResourceSpec().resolve(True).to_resource_dict()
            if not resources:
                logger.warning(
                    "Cluster resources not detected or are 0. Retrying...")
                time.sleep(0.5)
            .......
```
Currently, if there are other remote tasks running in the ray cluster and some resources are actually unavailable, tune will not know that.

I think we should use `ray.available_resources()` API here to support running many tune tasks or other remote tasks in the same ray cluster at the same time.

**Comment by richardliaw** [comment]
This doesn't quite work because it doesn't take into the current resources that Tune is using. Ideally, there's a way to track this "group" of actors and be able to isolate their resource usage.

**Comment by ujvl** [comment]
> Currently, if there are other remote tasks running in the ray cluster and some resources are actually unavailable, tune will not know that.

Hmm that's a good point. 

I think its not as simple as replacing `cluster_resources()` with `available_resources()` though due to staleness. but maybe in has_resources() doing something like taking `max(available_resources, cluster_resources - committed)` (the latter being what we currently use) would prevent overestimating available resources. cc @rliaw

**Comment by JasonWayne** [comment]
@ujvl Thks for the reply. I also see the doc in the `available_resources()` methoned that `this information can grow stale as tasks start and finish`. But could not figure out why. Could you please explain why `available_resources()` will go stale and how much time will the value be outdated..?
