### ISSUE TITLE
Discuss on supporting long running job

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#6715]
## Current Approach
Currently, the most jobs of the production environment are long running in our experiences. Because it's often used, it's very important to add an appropriate and easy-to-use API for this.

I have noticed that @simon-mo implemented a relevant feature called `detached actor` in the PR #6036.  But there might be some issues in `detached actor`:
1) It doesn't work for normal tasks.
2) The cost that users rewrite a normal job to a long running job is too expensive. They should add the `detached_actor` flags for every actor creation.(Please correct me if I'm wrong.)
3) Because users should do a `dummy call and get` for the actor to make sure it is created, users have to know more about the details of the ray. It's not in line with `Simply` principle.

## Another Proposal
According to what we have been using for a long time, we'd like to support this in another approach.

**Add a flag `clean_up` for the `ray.shutdown()` method to indicate whether we will clean up everything of this job.**
```python
# It will not clean up the things of this job even if this driver exits immediately.
ray.shutdown(clean_up=False)
```
Then there're 2 ways to drop the job from cluster if we want:
```bash
# execute a drop command
ray drop address="redis_address" job-id=xxxxxx
```
or drop it in another job with `ray.drop` API:
```python
ray.init(address="xxxx")
ray.drop(job_id=xxxxx)
```
ps: It will be more natural if we enable job-name for a job.

If you think the API `ray.shutdown(clean_up=False)` is a bit weird, it will make more sense to put the flag to `ray.init` like:
```python
ray.init(long_running=True)
```
Any other proposal is  welcome.

@simon-mo @stephanie-wang @robertnishihara  cc

**Comment by robertnishihara** [comment]
Thanks @jovany-wang, can you provide some more details about the use case? For example
- Why not just keep the driver alive? Is the concern that the driver is a possible point of failure for the job? Are there any other concerns?
- Can you give a concrete use case?

>Because users should do a dummy call and get for the actor to make sure it is created, users have to know more about the details of the ray. It's not in line with Simply principle.

That's a good point.

**Comment by ericl** [comment]
> If you think the API ray.shutdown(clean_up=False) is a bit weird, it will make more sense to put the flag to ray.init like:

I like doing this on shutdown, it ensures that the job will be cleaned properly up if it crashes at any point prior to the shutdown() call.

I agree with having a name for the job though, maybe there can be a call like `ray.detach_job(job_name="my_streaming_job")`?

**Comment by jovany-wang** [comment]
> * Can you give a concrete use case?

Yes, there're several concrete cases actually.  One case is our streaming job. A driver is used to create some actors with certain responsibilities, and the actors both are long running to do their work.

Other online cases like serving are also need this requirement: A driver is used to create some long running serving actors to receive requests from users.

> * Why not just keep the driver alive? Is the concern that the driver is a possible point of failure for the job? Are there any other concerns?

The major reason for not keeping driver alive is the lack of driver's fail-over ability as you said. Another point is there's no graceful way to keep driver alive. Both `dummy get` or `while True: sleep` are too weird.

**Comment by jovany-wang** [comment]
@ericl 
User shouldn't call `ray.detach_job(job_name="a")` in job `b`, because we're not able to guarantee job `a` is done.
So if we use `ray.detach_job`, it should be with no `job_name` parameter. Because we can only call it in the same job.


How to define the behavior of the following code:
```python
# driver
ray.init(address=xxx)

ray.shutdown() # do clean up
ray.detach_job() # The job is cleaned up
```

**Comment by ericl** [comment]
I mean the name to be assigning a name to the job. How about this:
```
ray.init(address="..", job_name="my job name")
ray.shutdown(detach=True)
```

**Comment by jovany-wang** [comment]
> I mean the name to be assigning a name to the job. How about this:
> 
> ```
> ray.init(address="..", job_name="my job name")
> ray.shutdown(detach=True)
> ```

This looks good to me as well.

**Comment by robertnishihara** [comment]
@jovany-wang what is the intended way to clean up a detached job?

What about just `ray.detach_job()` and nothing else? This has the benefit that @ericl mentioned about not detaching the job if it crashes before that line.

**Comment by pcmoritz** [comment]
My mental model of a detached actor is a little bit different from everybody else's I think, instead of making all the actors in an application detached, there should be a single detached actor that then launches all the other (non-named) actors. In that view, detached drivers and detached actors are roughly similar. The advantage of the detached actor is that we already need an API to kill actors, so that would be a natural one to terminate detached actors too. Normal tasks launched from a detached actor should also only be cleaned up when the detached actor is cleaned up.

For the point 3. in the original post, I'm not sure if I understand. It should be enough to just call the constructor of the detachable actor, that will make sure it gets executed. No get should be needed (if it is that sounds like a bug).

**Comment by pcmoritz** [comment]
It shouldn't make too much difference from the applications perspective which of the two solutions we end up going with, i.e. should be quite easy to take all the code from one of your detached drivers and call it in the constructor of a detached actor for example, and vice versa, having a detached driver that starts a single actor is equivalent to having a detached actor.

**Comment by ashione** [comment]
> My mental model of a detached actor is a little bit different from everybody else's I think, instead of making all the actors in an application detached, there should be a single detached actor that then launches all the other (non-named) actors. In that view, detached drivers and detached actors are roughly similar. The advantage of the detached actor is that we already need an API to kill actors, so that would be a natural one to terminate detached actors too. Normal tasks launched from a detached actor should also only be cleaned up when the detached actor is cleaned up.
> 
> For the point 3. in the original post, I'm not sure if I understand. It should be enough to just call the constructor of the detachable actor, that will make sure it gets executed. No get should be needed (if it is that sounds like a bug).

Maybe it isn't quite good solution to manage all actors by a detached driver actor.
Let us image a case in streaming:
A driver launchers a streaming job including job master (actor) and wokers( a lot of stateful actors).
The driver actor should not handle all recovery operations because of all if it's killed or lost,
which is side effect.
@jovany-wang

**Comment by jovany-wang** [comment]
@pcmoritz 

Let's image that we have almost 100 actors in our APP, and then we create these around 100 actors in another detached actor(call it `my-detached-actor`):
```python
@ray.remote
class MyDetachedActor:
  def __init__(self):
      # create my 100 actors.

# driver code:
my-detached-actor = MyDetachedActor.remote(detached=true)
```
Some issues are introduced now:
1. In this APP, there is a  `my-detached-actor` actor which is doing nothing and just for submitting the 100 work-actors. It looks too weird for users I think.

2. For user, I must consider the failure cases of `my-detached-actor`, which will introduce more mental burden to user.

@pcmoritz 
>should be quite easy to take all the code from one of your detached drivers and call it in the constructor of a detached actor for example, and vice versa, having a detached driver that starts a single actor is equivalent to having a detached actor.

I can get the point as you said that users can use detached-actor to implement it and then we needn't to provide another `drop job` API. I'd like to address the root issue instead of doing it with reluctance.

Thanks :)

**Comment by raulchen** [comment]
> Normal tasks launched from a detached actor should also only be cleaned up when the detached actor is cleaned up.
@pcmoritz Currently, if we kill the detached root actor, those normal tasks won't be cleaned up, right?  However, if we terminate a job, Ray will clean up all related resources.  Considering this, having detached drivers + a kill job API sounds better than having detached actors + a kill actor API.

**Comment by jovany-wang** [comment]
@ All,

If we both agree the API(`ray.shutdown(detach=True)`) proposed by @ericl , I‘m going to do it.

**Comment by pcmoritz** [comment]
As I indicated above, I'm ok with the `ray.shutdown(detach=True)`, it is a good API I think :)

**Comment by robertnishihara** [comment]
Me too.

A couple things.
- For now, there will not be any way to clean up a detached job?
- We will need to clarify the semantics around detached actors. For example, if an actor or task is created by a detached actor, what happens to that actor or task when the original job finishes.

**Comment by jovany-wang** [comment]
> For now, there will not be any way to clean up a detached job?

There is no way to clean up it now. we should support it via:
    a. `ray.drop job-name/job-id` command
b. `ray.drop(job_name/job_id)` API in another driver.

> We will need to clarify the semantics around detached actors. For example, if an actor or task is created by a detached actor, what happens to that actor or task when the original job finishes.

Agree with you on this point.

**Comment by jovany-wang** [comment]
Hi @ericl @kfstorm ,
We're planing to contribute long-running flag to community. Things look like:
1. Flag is in job_config. so the API should look like:
```python
 job_config = ray.job_config.JobConfig(long-running=True)
 ray.init(job_config=job_config)
```
2. The behavior of long running job is making actors created in driver as detached. And then the the job is not offlined even if the driver exits.

3. We can use job submission pages and APIs, or Ray command line tool to offline a long running job.

**Comment by ericl** [comment]
> We're planing to contribute long-running flag to community. Things look like:

Could we make this an experimental API initially? One option is allowing the default actor lifetime to be overriden, for example:

```
ray.init(_default_actor_lifetime = "detached")
launch_actors()
```

**Comment by kfstorm** [comment]
I think the long-running flag doesn't solve the problem that we don't have a mechanism to kill a job and clean up things that belong to the job, e.g. detached actors, running normal tasks, idle workers, runtime env, etc. We may need a new API in the dashboard to kill and clean up a job forcibly (maybe we need to introduce a new job state). With this new API, the long-running flag is just like syntactic sugar. It's not a must-have.

**Comment by ericl** [comment]
Given that we have namespaces, how about adding an API to cleanup by
namespace id?

**Comment by jovany-wang** [comment]
> Given that we have namespaces, how about adding an API to cleanup by

I don't think so. Image that there might be 2 jobs may in the same namespace.

**Comment by ericl** [comment]
Why not put the jobs in separate namespaces then? By default, the
namespace is randomized per job, so there is a unique one per job. It
can also be set to be the same as the job id for convenient cleanup.

**Comment by jovany-wang** [comment]
There're different concepts.
We provide namespace concept for isolation accessibility. If users don't specify it, it will be generated a random one. But there're still some users that want to put 2 jobs in one namespace for accessibility because we have provided the way to specify it.
Shortly, dropping a job is orthogonal to namespace.

**Comment by kfstorm** [comment]
Ideally, I believe that killing a job is a valid feature request. Killing a namespace maybe valid too.

**Comment by ericl** [comment]
I agree that killing a job or cleaning up its detached actors is a reasonable feature. But, I don't see why we need a long-running job concept.

Currently, we can already have a job with detached actors. Why not instead add a `cleanup detached actors` API for these jobs? We can also add a status / check if there are any detached actors for a job that still exist.

That way we don't need to introduce any new concepts, but can still do all the necessary detached actor operations.

**Comment by raulchen** [comment]
@ericl Instead of a "clean up detached actors in job" API, I'd like to have an API that "completely cleans up all resources in the job" and mark the job as "truly finished". 
IIRC, we discussed this before, and the conclusion was to mark the job state as "driver_exited" when the driver exits and there are detached actors. And when the "kill job" API is called, the job state become "finished". 
The benefits are 1) easier to tell the job state; 2) make sure no resources (workers, objects, runtime envs, etc) are leaked; 3) for short-running jobs, the "kill job" API can also used to kill the driver.

**Comment by ericl** [comment]
> IIRC, we discussed this before, and the conclusion was to mark the job state as "driver_exited" when the driver exits and there are detached actors. And when the "kill job" API is called, the job state become "finished".

It sounds good. Just want to clarify the semantics more formally, is this what you had in mind?
- When the driver exits and there are detached actors, the state is DRIVER_EXITED.
- When all detached actors exit, the state becomes FINISHED.
- There is a `KillJob(job_id, kill_detached_actors=True)` API that kills the job, disconnecting the driver, and optionally kills detached actors. When the detached actors are removed, the state auto transitions to FINISHED.

**Comment by jovany-wang** [comment]
> `KillJob(job_id, kill_detached_actors=True)` 

Why we need the 2nd parameter?  I think it's unnecessary to have `KillJob(job_id, kill_detached_actors=False)` since `KillJob()` should be indicated as killing everything of the job.

And after discussed with @kfstorm offline , we think it's a bit confused that what the job state should be if the detached actor dead. It should be JOB_DEAD or JOb_FINISHED? Normally, if an actor dead, the job state should be DEAD, but if we introduce the semantic `When all detached actors exit, the state becomes FINISHED`, the job state should be FINISHED.

**Comment by ericl** [comment]
> Why we need the 2nd parameter? I think it's unnecessary to have KillJob(job_id, kill_detached_actors=False) since KillJob() should be indicated as killing everything of the job.

Fair enough.

> we do think it's a bit confused that what the job state should be if the detached actor is dead. Should it be JOB_DEAD or JOb_FINISHED

I would think it enters the same terminal state whether it dies naturally or via kill command. Personally I think FINISHED or TERMINATED is more common terminology (dead sounds a bit violent).

**Comment by jovany-wang** [comment]
Do you agree that the end users need to know whether the job is finished normally or dead?

If it's FINISHED, end users know his job is green(PASSED), otherwise it's red(some thing wrong), and they need to debug his application.

**Comment by ericl** [comment]
From Ray's POV, I don't think exit status of internal jobs is needed. We can track "Ray Job" status (status of a submitted bundle of code) separately in the Job Submission API built on top of Ray: https://docs.ray.io/en/master/ray-job-submission/overview.html

For Jobs with detached actors, whether they are terminated successfully or not also seems of dubious value; a platform built on top of Ray can probably assign a better status. In general, I think Ray should provide minimal UX/status reporting here; stuff built on top of Ray can manage that separately.

**Comment by raulchen** [comment]
> > IIRC, we discussed this before, and the conclusion was to mark the job state as "driver_exited" when the driver exits and there are detached actors. And when the "kill job" API is called, the job state become "finished".
> 
> It sounds good. Just want to clarify the semantics more formally, is this what you had in mind?
> 
> * When the driver exits and there are detached actors, the state is DRIVER_EXITED.
> * When all detached actors exit, the state becomes FINISHED.
> * There is a `KillJob(job_id, kill_detached_actors=True)` API that kills the job, disconnecting the driver, and optionally kills detached actors. When the detached actors are removed, the state auto transitions to FINISHED.
> 
> Separately, we can add `ray.init(_default_actor_lifetime = "detached")`. These two changes together will meet all requirements?

Yeah, that's what I was thinking. This should be able to meet all the requirements I can think of.

**Comment by jovany-wang** [comment]
Hi all, I create a new issue for our conclusions https://github.com/ray-project/ray/issues/21128

Feel free to discuss at the new issue.

**Comment by rkooo567** [comment]
I actually have one comment regarding "kill_job".

Currently, "job" is not an exposed concept. I think we recently added a new support to "Ray job", but they are not 1:1 matching to the internal terminology job. This will be the official terminology "job" in Ray.

It seems like the proposal changes the definition of internal term job. From "driver" -> "A set of resources that belong to a job id". I think this is reasonable (and supporting jobs that are not fate sharing with driver makes sense. That's what Serve implements in a higher layer).

And here, I feel like introducing API such as "kill_job" can confuse users. Since we already have a different concept "job". Users might confuse this term with our newly created concept/term job.

That says, why don't we rename APIs like "kill_detached_actors(job_id="") without including "job" in the name of the API?

**Comment by jovany-wang** [comment]
> That says, why don't we rename APIs like "kill_detached_actors(job_id="") without including "job" in the name of the API?

What if other things? such as detached placementgroup?

**Comment by ericl** [comment]
I think we should just align the job ids between "Ray jobs" and "job server". That will, kill will work as you'd expect in both cases.
