### ISSUE TITLE
Error message on ray init when run inside Jupyter: setpgrp failed, processes may not be cleaned up properly

### ISSUE THREAD

**Issue by mc-allen** [ray-project/ray#6718]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 0.8.0
Python 3.6
Ubuntu 18.04

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*

Yes, with ray-0.9.0.dev0.

### Reproduction
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

I am running juypyterlab 1.2.4 within docker, using an 18.04 base image. To reproduce, simply import ray and call ray.init.

```python
import ray
ray.init()
```

And the error message will be generated.

```
2020-01-06 17:54:50,339	WARNING services.py:595 -- setpgrp failed, processes may not be cleaned up properly: [Errno 1] Operation not permitted.
```

PID, PGID, PPID, and SID all have the same value in this case. Outside of Jupyter, this error does not occur.

**Comment by edoakes** [comment]
Thanks for reporting this @mc-allen. After looking into this a bit, I was only able to reproduce in jupyterlab and unfortunately am not able to find a workaround.

This shouldn't cause any significant problems, it just means that if the python process that called `ray.init()` (the jupyter notebook in this case) is terminated via `SIGKILL`, there may be some background processes left up. If this does happen for some reason, you can always clean these processes up manually using `ray stop`.

**Comment by mc-allen** [comment]
Is "ray stop" the same effect as "ray.shutdown()"?

**Comment by edoakes** [comment]
`ray stop` is a bash command and will stop all ray processes running on the machine (started by `ray.init()` in python or `ray start` on the command line.

`ray.shutdown()` will stop all ray processes started by a previous `ray.init()` call in the current python process.

**Comment by mc-allen** [comment]
I see. I'm looking for something I can call from python that will release all ray resources, including object store shared memory, and ideally redis too, and kill all tasks. This is needed in the event of a crash or restart of a script.

**Comment by edoakes** [comment]
If ray was started from within the process that crashed, resources should be cleaned up automatically.

Also, not sure if this exactly fits the bill, but if you call `ray start` with `--block`, it will clean up all processes started by ray of any of them die (e.g., if redis goes down or the raylet crashes)

**Comment by mc-allen** [comment]
Sorry if this is the wrong place to continue this conversation, but...

In my experience, it seems like ray.shutdown() does not clear ray's usage of /dev/shm. Is there a surefire way to accomplish this?

**Comment by edoakes** [comment]
The `/dev/shm` usage will be cleared once the object store goes down. This should be done by `ray.shutdown()` if you called `ray.init()` in the same process, otherwise you'll have to call `ray stop`.

**Comment by hubcity** [comment]
This looks very similar to this [os.setsid](https://stackoverflow.com/questions/25701333/os-setsid-operation-not-permitted) question where python raises an exception if the value is already set.

Could this be a simple as changing
`    os.setpgrp()`
to
`    if os.getpgrp() != os.getpid(): os.setpgrp()`

This worked for me on Ubuntu 18.04.

**Comment by edoakes** [comment]
Thanks @hubcity!

@mehrdadn do you think you could take a look when you have a chance?

**Comment by mehrdadn** [comment]
Yeah I'll try to think about it, it seems like a nontrivial problem but there might be a solution.

**Comment by mehrdadn** [comment]
I a PR that should fix this (similar idea to @hubcity's solution) @edoakes.

Please let me know if you see any potential issues with this solution. Thanks!

**Comment by GoingMyWay** [comment]
@edoakes Hi, should I add `ray.shutdown()` in my code when finishing my task?
