### ISSUE TITLE
Fail to compile Ray dashboard client

### ISSUE THREAD

**Issue by nqbao** [ray-project/ray#6739]
### What is the problem?

When I compile the nodejs for the dashboard, i get the following message

```
Definition for rule '@typescript-eslint/consistent-type-assertions' was not found
```

It turns out that we need to update react-scripts to 3.1.2 as mention [here](https://github.com/facebook/create-react-app/issues/7711)

*Ray version and other system information (Python version, TensorFlow version, OS):*

master

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
git clone https://github.com/ray-project/ray.git

# Install Bazel.
ray/ci/travis/install-bazel.sh

# Optionally build the dashboard (requires Node.js, see below for more information).
pushd ray/python/ray/dashboard/client
npm ci
npm run build
popd
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.

**Comment by pcmoritz** [comment]
Thanks for the report! I can't reproduce the error on my machine, but more than happy to upgrade `react-scripts` to 3.1.2 if that makes it work on your machine. Feel free to try out https://github.com/ray-project/ray/pull/6769 or submit a PR that fixes the issue for you :)

**Comment by nqbao** [comment]
Yup, #6769 works for me. Thank you @pcmoritz !
