### ISSUE TITLE
[Streaming]Runtime Scheduler and JobMaster

### ISSUE THREAD

**Issue by JingGe** [ray-project/ray#6745]
As we knew, Ray's scheduling focuses more on how tasks are assigned to actors on different nodes. In comparison, the allocation of actors is not that fine-grained: Ray will randomly select one of the nodes satisfying the required resource condition and create an actor process on it.

For the streaming application built on ray,  Ray’s random actor allocating strategy may cause excessive resource (CPU/GPU/Memory) occupation of some nodes, which may lead to application probability deployment failure or raising OOM exception. At the same time, optimization strategies like co-locating and load balancing cannot be well supported.

We are planning to open source the streaming JobMaster written in Java. Briefly speaking, the JobMaster has three components: GraphManager, JobScheduler, ResourceManager. The JobScheduler will use the ExecutionGraph built by the GraphManager and the resource provided by the ResourceManager to schedule the Worker in the cluster based on the pluggable scheduling strategy. The strategy could be rule based for now and could turn into AI model based in the future. The main goal is to improve the overall performance and use the cluster more efficiently. 

The contribution plan contains the following steps:

1. Refactoring the current code for the upcoming PRs that contain new features.
2. Configuration 
3. GraphManager
4. ResourceManager
5. Scheduler and JobMaster

For more information about the architecture, please refer to http://expanddocs.google.com/document/d/1rchL3M0Dp_jzOzT4qJplb1cIV1TyU6GTbN4bh3szkJM

This feature request is focusing on the "Scheduling" mentioned in [Ray Streaming implementation plan](https://github.com/ray-project/ray/issues/6184)

**Comment by BalaBalaYi** [comment]
PRs:
- [x] Configuration - https://github.com/ray-project/ray/pull/6687
- [ ] JobGraph - https://github.com/ray-project/ray/pull/6712
- [ ] ExecutionGraph - https://github.com/ray-project/ray/pull/6666

**Comment by chaokunyang** [comment]
Close this issue as it's finished
