### ISSUE TITLE
[projects] ray session stop does not kill pods

### ISSUE THREAD

**Issue by Nintorac** [ray-project/ray#6762]
### What is the problem?

Using ray 0.9.0dev0

Ray projects does not delete pods associated with the project when running `ray session stop`

### Reproduction (REQUIRED)

When launching the cluster with `ray session start <command>` the name of the cluster supplied in the `cluster.yml` is overwritten with the name of the project. However the same replacment is not made when running `ray session stop`. 

A temporary workaround is possible by running `ray session stop --name project_name`

refer to the stop code here
https://github.com/ray-project/ray/blob/master/python/ray/projects/scripts.py#L327

refer to the start code here
https://github.com/ray-project/ray/blob/master/python/ray/projects/scripts.py#L352

### Potential fix

Alter the stop function to the following

```
def stop(name):

   if not name:
        name = project_definition.config["name"]

    project_definition = load_project_or_throw()
    teardown_cluster(
        project_definition.cluster_yaml(),
        yes=True,
        workers_only=False,
        override_cluster_name=name)
```

I think however it would be neater if the config loader did the replacement i.e here https://github.com/ray-project/ray/blob/master/python/ray/projects/projects.py#L49

**Comment by Qstar** [comment]
Thanks for attention, I will reproduce and fix it if it's a bug.

**Comment by pcmoritz** [comment]
@Nintorac @Qstar Thanks for pointing this out and offering to fix it, let me know if you need help! The proposed fix looks great to me :)

**Comment by Qstar** [comment]
> @Nintorac @Qstar Thanks for pointing this out and offering to fix it, let me know if you need help! The proposed fix looks great to me :)

Please review the PR related, thanks~
