### ISSUE TITLE
[rllib] use_lstm seems not working when using a custom_model

### ISSUE THREAD

**Issue by asylin2018** [ray-project/ray#6766]
### What is your question?
I am trying to add a fully connected network on top of the LSTM network in http://ray/rllib/examples/rock_paper_scissors_multiagent.py as below. However, it seems like the lstm network is not applied when I add the  "custom_model".

I have attempted to confirm whether lstm network is added to the last layer of the fully connected network by adding "raise(2==100)" to def _build_layers_v2(self, input_dict, num_outputs, options) of LSTM class in ray/rllib/models/tf/lstm_v1.py. However, the raise exception was not triggered at all. If I remove the "custom_model" from the code below, this exception was triggered.

I am wondering if I am doing it correctly to add a fully connected network on top of LSTM. If not, would you please let me know how to add a fully connected network on top of LSTM? Thank you!

    from ray.rllib.models.tf.fcnet_v2 import FullyConnectedNetwork
    ModelCatalog.register_custom_model("fullyconnmodel", FullyConnectedNetwork)

    tune.run(
        trainer,
        stop={"timesteps_total": 40000},
        config={
            "env": RockPaperScissorsEnv,
            "gamma": 0.9,
            "num_workers": 4,
            "num_envs_per_worker": 4,
            "sample_batch_size": 10,
            "train_batch_size": 200,
            "multiagent": {
                "policies_to_train": ["learned"],
                "policies": {
                    "always_same": (AlwaysSameHeuristic, Discrete(3),
                                    Discrete(3), {}),
                    "beat_last": (BeatLastHeuristic, Discrete(3), Discrete(3),
                                  {}),
                    "learned": (None, Discrete(3), Discrete(3), {
                        "model": {
                            "custom_model": "fullyconnmodel",
                            **"fcnet_hiddens": [16, 16, 3],**
                            "use_lstm": use_lstm
                        }
                    }),
                },
                "policy_mapping_fn": select_policy,
            },
        })

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.7.5
Python version: 3.6.9
TensorFlow version: 1.14
OS: linux mint 19

**Comment by ericl** [comment]
I think that option does not work for custom models. You can try using a custom LSTM model instead.

**Comment by asylin2018** [comment]
> I think that option does not work for custom models. You can try using a custom LSTM model instead.

Thanks for your advice. I am able to use the default fully connected network by removing "custom_model": "fullyconnmodel" and just set fcnet_hiddens": [16, 16, 3]. By using a custom LSTM model, do you mean I create a fully connected network on top of a LSTM network in the custom LSTM model?

BTW, I am confused on how to sequential data got processed by the LSTM network if i set "use_lstm" to True. The observation in the step function is a snapshot of current status at time, t. It's then saved to the replay buffer along with the reward obtained at time t as well. After several time steps, the agent will randomly select a batch of samples from the replay buffer to train the fully connected network + LSTM network. How can we make sure that a sequence of samples are used to train the network? For example, if I set "max_seq_len" to 20, I want to make sure that the past 20 time steps of observations are used to train the network, not just a random sample of obs at multiple time points.

I will appreciate it if you could explain to me on how the data flows in the training process when setting "use_lstm" to true. Thanks!
