### ISSUE TITLE
Support retry for failed actor tasks

### ISSUE THREAD

**Issue by zhijunfu** [ray-project/ray#6773]
For direct actors, right now we only support retry of the creation task (via a limited number of retries). It would probably be desirable to extend the retry support to actor tasks too, so that it would be consistent with non-actor tasks, and also it would make it easier for users to use actors. There are also some [brief discussions](https://github.com/ray-project/ray/pull/6698#discussion_r363164498) previously. 

There's a possibility that the actor is still alive but some actor tasks fail, we probably shouldn't retry in this case, as this could be difficult to handle considering the ordering requirements. The problem is that a failure RPC callback doesn't tell us whether the actor is still alive or not, since the status could be filled by grpc or the actor. One possible way is to add more information to the reply to indicate if it's sent by actor (in which case the non-ok status is not because of actor death). 

It might be possible that the grpc connection breaks while the worker is still alive, in that case grpc reply callbak would report a non-ok status. In this case we probably also need a timeout, so that if we don't receive gcs reconstruction notifcation for the actor after a period of time, we still need to write exception objects for these failed tasks, to make sure the workers calling ray.get() on these objects will not be blocked forever. Currently we don't have this for non-actor-task resubmission, but it might be ok in that case.

Roughly this can be:
- add an option in ActorCreationOption to indicate whether this is enabled for the specific actor
- only support actor task retry for failures due to actor death
- need a way to differentiate the root cause of task failure (maybe add info to rpc reply)
- for actor task failures, if it's due to actor death, then queue the future tasks for this actor and retry until receiving the alive notification from gcs (if actor is allowed to reconstruct); otherwise treat the failed task as failure as today.
- (maybe later) use a timer to limit the time for workers to wait for actor reconstruction events, in case that we got failure from grpc but the actual worker is alive.
 
Thoughts? 

@robertnishihara @ericl @stephanie-wang @raulchen

**Comment by zhijunfu** [comment]
There's a possibility that the grpc connection breaks while the worker is still alive, in that case grpc reply callbak would report a non-ok status. (I'm not exactly sure when this would happen, but this might be possible). In this case we probably also need a timeout, so that if we don't receive gcs reconstruction notifcation for the actor after a period of time, we still need to write exception objects for these failed tasks, to make sure the workers calling `ray.get()` on these objects will not be blocked forever.

**Comment by ericl** [comment]
This is fixed now.
