### ISSUE TITLE
Fully utilizing GPUS with synchronous algorithms (e.g. PPO/A2C)

### ISSUE THREAD

**Issue by internetcoffeephone** [ray-project/ray#6774]
For PPO, A2C and other synchronous algorithms, it would be nice to use the same GPU for the driver, as well as for the workers. I'm aware that you can assign a portion of the GPU to the driver, and the rest to workers, however:

As it stands, whenever the workers are sampling, any GPU (or GPU fraction) assigned to the driver is idle. This goes the other way around too: when a driver is processing samples, it cannot make use of any GPU assigned to the workers.

Is it somehow possible to always make full use of all GPU capacity with synchronous methods? Or does something in ray/tf's design prevent us from easily doing so?

**Comment by ericl** [comment]
Synchronous algorithms always can't fully utilize the GPU since they have two distinct phases of optimization. You can try IMPALA or APPO to increase utilization with asynchronous execution.

**Comment by internetcoffeephone** [comment]
I'm not sure whether I understand the fundamentals here. From my limited experience with shader programming, it's not that expensive to load a set of instructions/data to the GPU, especially not compared to the time involved spent sampling/optimizing.

Maybe an example would help here, e.g. PPO, which has 2 phases: sample & update. Let's consider the 1 GPU case, which would currently be:
`[0.5 GPU sample][0.5 GPU update][0.5 GPU sample][0.5 GPU update]...`
This permanently leaves half of the GPU unused (unless you're running 2 experiments at the same time)
Why can't this be:
`[1 GPU sample][1 GPU update][1 GPU sample][1 GPU update]...`

Or in the 2 GPU case:
`[2 GPU sample][1 GPU update][2 GPU sample][1 GPU update]...`

This would of course only be possible if your GPU memory allows for this. What am I missing here that doesn't allow for this?

**Comment by ericl** [comment]
Oh, what you described before will work just fine -- Ray doesn't enforce any constraint on the GPUs. So if you request 0.5, but actually use 1, that will utilize the full GPU during that phase.

**Comment by internetcoffeephone** [comment]
Ah, thanks for the clarification.

The [docs](https://ray.readthedocs.io/en/latest/rllib-training.html#specifying-resources) are a bit misleading then:

> The number of GPUs can be a fractional quantity to allocate only a fraction of a GPU. For example, with DQN you can pack five trainers onto one GPU by setting num_gpus: 0.2.

Additionally, this means the best way to do this for an arbitrary amount of workers (restricting ourselves to single-GPU driver algorithms) would be the following:

Given 4 GPUs in your machine:
`gpu_count = 4`
`num_gpus = 0.0001 # This is the driver GPU` 
`num_gpus_per_worker = (gpu_count - num_gpus) / num_workers`

This seems a bit contrived for a fairly common use case. Don't you think this should happen by default, letting driver/worker GPU sharing be the default in algorithms that support it? (Perhaps through some setting in each algorithm's DEFAULT_CONFIG).
