### ISSUE TITLE
_unpack_obs should be able to use custom preprocessors

### ISSUE THREAD

**Issue by nicofirst1** [ray-project/ray#6783]
### Code Flow
When the [call method](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/modelv2.py#L143) for a model is called then it will call the [restore_original_dimensions function](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L204) which will then use the [_unpack_obs](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L237)

### Problem description
When using custom [Preprocessor](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/preprocessors.py#L17) there is a chance that your action space will be a dictionary with _n_ values but you only need a subset as observation space.
If you do so then you will get a [shape error here](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L255) since the function [loads](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L251)  the  default preprocessors instead of using custom ones when given.

### Feature Descrition
It wuld be nice to get the custom preprocessor in the model call function and pass it first to the [restore_original_dimensions function ](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L204) and then to the  [_unpack_obs](https://github.com/ray-project/ray/blob/a950e95c7d38df32311da90b20208e2d35b7aa08/rllib/models/model.py#L237) one as an optional parameter. 
Finally execute a simple check in the latter function, something like:
```
def _unpack_obs(obs, space, tensorlib=tf, preprocessor=None):
    """Unpack a flattened Dict or Tuple observation array/tensor.
    Arguments:
        obs: The flattened observation tensor
        space: The original space prior to flattening
        tensorlib: The library used to unflatten (reshape) the array/tensor
        preprocessor: Custom preprocessor
    """

    if (isinstance(space, gym.spaces.Dict)
            or isinstance(space, gym.spaces.Tuple)):
        if id(space) in _cache:
            prep = _cache[id(space)]
        else:

            # Execute check on custom preprocessor
            if preprocessor is None:
                prep = get_preprocessor(space)(space)
            else:
                prep=preprocessor
 
....
```

The only problem I can think about is actually grabbing the custom preprocessor in the call method but it shouldn't be too hard

**Comment by ericl** [comment]
Yeah, this is a bug.

As a workaround, you can try doin the preprocessing in your environment with a gym wrapper (or similar) instead, and not using a custom preprocessor. This should allow the same functionality.

**Comment by nicofirst1** [comment]
I am already using a gym wrapper on my original env. 
Would you accept a pull request?

**Comment by ericl** [comment]
Sure

**Comment by nicofirst1** [comment]
How should i get the preproc in the call method?

**Comment by ericl** [comment]
Hmm, you would have to pass it to the model constructor. This could get a bit messy --- on second thought, it may be better to deprecate custom preprocessors, since you can always implement the same functionality with a env wrapper (you can just add another one on top of your existing one).

**Comment by nicofirst1** [comment]
Can't it be called with the registry by the model option dict?

**Comment by nicofirst1** [comment]
I don't get how can you be able to do it with a wrapper.
I'm using a wrapper around my env already to implement [parametric actions](https://ray.readthedocs.io/en/latest/rllib-models.html#variable-length-parametric-action-spaces) so that my observation will be a dict having:
```
agend_id: {
    avail_action:list(),
    action_mask:list(),
    actual_observation:gym.spaces.Dict(),
}
```
In the preprocessor I am trying to tell the model that only the size of _actual_observation_ will be the input while the other two are used exclusively in the model forward method.

**Comment by ericl** [comment]
Doesn't using a custom model (like in the param actions example) that only processes actual_obs do that without needing a custom preprocessor?

**Comment by nicofirst1** [comment]
No, since the model input size will be decided by the default preprocessor, the dict one, which will flatten every observation entry giving a larger size than the one i need.

**Comment by ericl** [comment]
I'm not sure I follow, are you using obs_flat for some reason? The flattened dict will be unpacked by unpack_obs, and your custom model will see the dict of tensors. Then, in the custom model you can use / not use any parts of the obs batch.

**Comment by nicofirst1** [comment]
The problem is with the size check in the model.
Using the default preprocessor with the extended observation I'll get a size which is the sum _avail_action + action_mask + actual_observation_. 
 But I only need _size(actual_observation)_ as input.

**Comment by nicofirst1** [comment]
Precisely I get the error:
```
File "/usr/local/anaconda3/envs/ww/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 65, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range'....
```

This is given in the [sampler function](https://github.com/ray-project/ray/blob/2bcf72e306a5f3e0abd20ee692dbef820c0fd874/rllib/evaluation/sampler.py#L403) when transforming raw observation.
During the transformation the [DictFlatteningPreprocessor](https://github.com/ray-project/ray/blob/2bcf72e306a5f3e0abd20ee692dbef820c0fd874/rllib/models/preprocessors.py#L230) checks for shape equivalence between the given observation (_actual_observation_) and the extended one.
Since they do not match it yield error.

**Comment by ericl** [comment]
> Observation outside expected value range

This actually means your observation values are too high or low... try increasing the Box() lo/hi bounds. It doesn't mean the size of the observation.

> But I only need size(actual_observation) as input.

Why not ignore the parts of the observation you don't need in the custom model?

**Comment by nicofirst1** [comment]
> This actually means your observation values are too high or low... try increasing the Box() lo/hi bounds. It doesn't mean the size of the observation.

Actually the error comes from [the sampler](https://github.com/ray-project/ray/blob/a0dc02042b6585b2476da597efc33e04b978dcd8/rllib/evaluation/sampler.py#L403) when the preprocessor transforms the input.
Since my input is a dictionary with

```
{
    avail_action:list(),
    action_mask:list(),
    actual_observation:gym.spaces.Dict(),
}
```
The _DictFlatteningPreprocessor_ will be called and it will [check](https://github.com/ray-project/ray/blob/a0dc02042b6585b2476da597efc33e04b978dcd8/rllib/models/preprocessors.py#L230) for the observation to be compatible with the shape. It will not be compatible since the actual input shape is the _actual_observation_ rather then the whole thing. So that's why the error is originated.

>Why not ignore the parts of the observation you don't need in the custom model?

I do ignore it in the model but there is no way to ignore it in [the sampler](https://github.com/ray-project/ray/blob/a0dc02042b6585b2476da597efc33e04b978dcd8/rllib/evaluation/sampler.py#L403) without a custom preprocessor.

**Comment by nicofirst1** [comment]
I finally got what you where saying about the ignoring the obs in the model and now it works.
Regarding the deprecation of custom preprocessors I think it is a good idea since they introduce more problems that they try to solve.
