### ISSUE TITLE
Using Pycharm debugger?

### ISSUE THREAD

**Issue by Riddim** [ray-project/ray#6789]
Is is not possible to use the PyCharm debugger within Rlib?

I am trying the windy maze example.

**Comment by Riddim** [comment]
So you can attache to another process with:
https://www.jetbrains.com/help/pycharm/attaching-to-local-process.html#

I also needed to run:
`sudo sysctl kernel.yama.ptrace_scope=0
`

**Comment by KyunghyunLee** [comment]
@Riddim 
Hi, I have same issue with this. 
I tried to attach another process, but I don't know which process to attach. 
Actually, I tried all processes listed, but failed. 
Can you please describe more details?
And I also run "sysctl" command you mentioned.

**Comment by Luukgr** [comment]
It is not working anymore in version 0.8.2. It should work in 0.8.1, but the dashboard packages should be uninstalled. If it is working, you should be able to find to process id, which is printed in the console.
e.g.:
`(pid=6265) episode 715949637 ended with 161.0`
The best way to debug is to debug without Tune. 
Debugging without tune is possible by just using:
`trainer.train()`
It
