### ISSUE TITLE
[Tune] Access trial name from within trainable class

### ISSUE THREAD

**Issue by Nintorac** [ray-project/ray#6796]
It would be useful to be able to access the trial name from within a `Trainable`.

Current solution:

```
class RayWorker(tune.Trainable):
    def _setup(self, config):
        self.trial_name = self._logdir.split('/')[-1].split('_')[0]

```

However this will only work when the default logging setup is used

**Comment by richardliaw** [comment]
Ah @Nintorac, here's a really hacky workaround for now.

```python
from ray.tune.schedulers import FIFOScheduler
# Note that you can use any scheduler here as a superclass
class ModifiedFIFO(FIFOScheduler):
    def on_trial_add(self, trial):
        trial.config["trial_name"] = str(trial)
        super().on_trial_add(trial)

class YourTrainable(Trainable):
    def _setup(self, config):
        trial_name = config["trial_name"]
        # put it into mlflow if you want
        ...

tune.run(... scheduler=ModifiedFIFO())
```

**Comment by Nintorac** [comment]
https://github.com/ray-project/ray/blob/master/python/ray/tune/trial.py#L223

Would there be any issues if it was injected here?

**Comment by richardliaw** [comment]
Hm, ideally we preserve the config and don't overload it with other parameters/values. Let me push a better fix for this soon.

**Comment by richardliaw** [comment]
You can now access the trial name in the trainable.

**Comment by LianShuaiLong** [comment]
> You can now access the trial name in the trainable.


class ESMMTrainable(tune.Trainable):
    def setup(self, config):#config for ray.tune.run
        import tensorflow as tf
        config_ray = config
        self.trial_name = config_ray['trial_name']
        #self.trial_name = self._logdir.split('/')[-1].split('_')[0]
        tf.logging.set_verbosity(tf.logging.INFO)
i want to get trial name within class trainable ,but get error:
self.trial_name = config_ray['trial_name']
KeyError: 'trial_name'
why?

**Comment by LianShuaiLong** [comment]
> ```python
> scheduler 
> ```

when i use as follows:

class ModifiedAsyncHyperBandScheduler(AsyncHyperBandScheduler):
    def on_trial_add(self, trial):
        trial.config["trial_name"] = str(trial)
        super().on_trial_add(trial)
i get another error:
TypeError: on_trial_add() takes 2 positional arguments but 3 were given

**Comment by richardliaw** [comment]
you can access trial name via ```self.trial_name```

**Comment by LianShuaiLong** [comment]
> you can access trial name via `self.trial_name`

cool!!!!

**Comment by ndrwnaguib** [comment]
@richardliaw how about accessing it from a trainable function?

**Comment by sluo1250** [comment]
what about in a simple trainable function that only takes a config as argument.
