### ISSUE TITLE
[Rllib] The example code for MADDPG is not being maintained

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#6803]
The example code for how to actually use MADDPG, as listed in the documentation, is here: https://github.com/wsjeon/maddpg-rllib/pull/7

Based on the issues there, the code example couldn't have even been tested before submission, PR key fixes for basic functionality aren't being merged/looked into. I understand that maddpg is still /contrib, but this is a real problem, and needs to be moved to someones library who will merge PRs, etc. I'm happy to fork @wsjeon 's code, fix the instructions, set up an accurate requirements.txt, include the PRs, etc. if you guys would want to change the official pointer to my fork. (I've been doing a ton of work with the MADDPG library recently).

cc @ericl

**Comment by ericl** [comment]
Thanks for looking at this @justinkterry . I think we can make a doc update to point to the new maintained repo as an update over the original -- feel free to submit a PR for this once is ready.

**Comment by justinkterry** [comment]
close via PR #6831
