### ISSUE TITLE
[rllib] run model at test time

### ISSUE THREAD

**Issue by esquires** [ray-project/ray#6809]
### What is your question?
I have trained a PPO agent and would like to run it on its test environment outside of rllib. I see that I can initialize an agent [here](https://ray.readthedocs.io/en/latest/rllib-training.html#python-api) but that API requires that I provide an environment. Is there an easy way to use a trained model given a checkpoint without having to provide the environment it was trained on? I don't necessarily need to initialize a trainer, just the model so that I can get actions given observations.

I also found [this](https://github.com/robertnishihara/ray-tutorial-docker/blob/master/rl_exercises/rl_exercise03.ipynb) but it looks like it may be for an older api.

other info:
* ray version (0.8.0)
* tensorflow version (1.14.0)
* os: ubuntu 18.04

**Comment by acxz** [comment]
[Here](https://github.com/ray-project/tutorial/blob/master/rllib_exercises/rllib_exercise02_ppo.ipynb) is an example of PPO from the ray-project's [tutorial](https://github.com/ray-project/tutorial) repo.
A couple differences from the link you provided:
- `PPOAgent` is now `PPOTrainer`
- The config is now the first argument when creating a `PPOTrainer`
Like so:
`test_agent = PPOTrainer(trained_config, 'CartPole-v0')`

**Comment by ericl** [comment]
> without having to provide the environment it was trained on

If you can't provide the original env class for some reason, it's possible to substitute a dummy env that has just `action_space` and `observation_space` defined. You can create the trainer with `num_workers: 0` in the config, and the env will never be stepped.

**Comment by esquires** [comment]
Thanks! I created ended up creating a dummy environment.
