### ISSUE TITLE
[tune] Global Stopping Criteria

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#6819]
### Describe your feature request
Often times, one might have a time control and that want the process to finish after it has run either N samples or ran up until the time control.

**Comment by thavlik** [comment]
Something like "given the average iteration/second, perform early stopping such that *all* trials complete within the given time window"?

**Comment by thuijskens** [comment]
Although that could be a cool feature too, the way I was thinking about it was more as follows: Run trials until the time control is hit, and then stop (PENDING and PAUSED trials are not executed, and RUNNING trials finish their current training iteration and stop, no further trials are scheduled).

The idea here being that as a practitioner I just want to find the best possible configuration given the total computation time I have (e.g. 2 hours, 1 day, ...).

**Comment by thuijskens** [comment]
Actually, after digging a bit more through it I realised TRIALRUNNER_WALLTIME_LIMIT does not implement a meaningful time control.. The time tracker is updated in the `_process_trial` method of `TrialRunner` by using the `time_this_iter_s` attribute of the trial that is being processed (line 437). So the time control tracks total computational time rather than wall clock time.

**Comment by richardliaw** [comment]
Thanks for your patience, @thuijskens @thavlik! Opened https://github.com/ray-project/ray/issues/6819 to address this. Does this look right for your use case? Please let me know.

**Comment by thuijskens** [comment]
@richardliaw Thanks for the short turn-around time on this one! At first glance, this looks like it would allow for what I was personally looking for. Curious to hear if this is also the case for others like @thavlik. I'll see if I can find some time to test the PR on my end.

**Comment by richardliaw** [comment]
No problem! Good to know the API is what you want. the PR is a bit broken
right now, but I’ll ping you when it’s ready.

**Comment by thavlik** [comment]
The API is super clean! Thank you!!
