### ISSUE TITLE
[AsyncAPI] Running docs example raises TypeError

### ISSUE THREAD

**Issue by zzyunzhi** [ray-project/ray#6821]
### What is the problem?

Running the example for Async Python and Async Ray reports error
`TypeError: unhashable type: 'list'`

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Thanks for reporting this - we should make sure our docs and examples run in Ci.

**Comment by simon-mo** [comment]
can you specify which example and the traceback?

**Comment by zzyunzhi** [comment]
Running `Async Python` or `Async Ray` Example gives
`TypeError: unhashable type: 'list'`
