### ISSUE TITLE
[tune] Allow `num_samples` sample index to be accessible in the variant config

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#6843]
### Describe your feature request

Would be nice if the sample id would be accessible in the config, i.e. when doing `tune.sample_from` in the variant generation. That way some of the variants could be dependent on the sample.

**Comment by richardliaw** [comment]
BTW, what do you mean by sample ID? Do you mean trial_id?

**Comment by hartikainen** [comment]
Ah, sorry, that was a bit ambiguous. I meant the index from `num_samples`.

**Comment by richardliaw** [comment]
Hm, this is a bit hard to support. For example, if I do:
```
x: grid_search([1, 2])
y: tune.sample_from(distribution())
z: grid_search([4, 5, 10])
``` 

this will generate six configurations, but there's no guaranteed ordering. What are you trying to do specifically? Maybe we can use a different API.

**Comment by hartikainen** [comment]
In the above, example, you have 6 configurations, but then with `num_samples=3`, you'd have 18 trials. Each of those 6 configs would effectively be run through another grid search over the `num_samples`, so there shouldn't be a problem with passing the sample index to the config? I might be wrong to.

But you're right, I was kinda misusing this. I was trying to get the seed to match the sample index. The right way, in this case, is obviously to just set `"seed": tune.grid_search([1, 2, 3])` and `num_samples=1`, but I was wondering that there might be cases where we'd actually need to know the sample index. Maybe there aren't.

**Comment by richardliaw** [comment]
Will close this for now, but we can revisit this.
