### ISSUE TITLE
Performance Warning 

### ISSUE THREAD

**Issue by sabyUWO** [ray-project/ray#6854]
### What is your question?
I am getting this warning while performing hyperparameter tuning with Bayesian Optimization, and the program is taking very long time (actually never completes)

The `start_trial` operation took 41.45643973350525 seconds to complete, which may be a performance bottleneck.

Any suggestion?
 
*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by richardliaw** [comment]
Can you provide a reproducible script?
