### ISSUE TITLE
[rllib] rollout with custom env

### ISSUE THREAD

**Issue by rusu24edward** [ray-project/ray#6860]
### What is your question?

Does ray support rollout with custom environments, something like:
```
rllib rollout --env MyCustomEnv
```
This was briefly mentioned in #5700, but got closed because a workaround was found. I can do the workaround, but it would be nice to have this feature built in.

If not from the command line, is there an equivalent rollout for a .py file? For example, [the docs](https://ray.readthedocs.io/en/latest/rllib-training.html#python-api) say that in order to train a custom environment, we just use the Pyhton API. Is rollout supported in the Python API? I need this for visualizing the policies that get learned.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6.9
Ray 0.8.0
TensorFlow 1.14 
Ubuntu 18

**Comment by ericl** [comment]
You can uncomment these lines and put your env here: https://github.com/ray-project/ray/blob/master/rllib/rollout.py#L33

**Comment by jaimegonzalezj** [comment]
Is the rollout also possible with the multi-agent interface? Thanks

**Comment by rusu24edward** [comment]
@jaimegonzalezj I don't believe it is possible with native RLlib. I've created a wrapper in [Abmarl](https://abmarl.readthedocs.io/en/latest/) that can rollout custom simulations, including multi-agent interface.
