### ISSUE TITLE
Tensorboard graphs screwed up with ASHAScheduler

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#6870]
For some reason, I keep getting these types of graphs with tensorboard. I'm using ASHAScheduler:

![Screenshot from 2020-01-20 18-06-28](https://user-images.githubusercontent.com/140710/72763018-c940bc80-3baf-11ea-90d1-7f8412ace61d.png)

Any idea what might cause this?

**Comment by richardliaw** [comment]
that's very weird; I've never seen that before. Can you provide a script for repro?

**Comment by drozzy** [comment]
Give me some time to come up with min working example.

All I know for now is I am setting the `timesteps_this_iter` manually:

```
    dr, dh, steps, mean_reward, mean_length = self.do_exploration()
    results['timesteps_this_iter'] = steps
    return results
```

**Comment by richardliaw** [comment]
What is the x-axis of your provided chart? Any more systems details/failures?

**Comment by richardliaw** [comment]
Also, did you set any logging parameters?

**Comment by drozzy** [comment]
The x-axis I assume is the total timesteps so far, which is made up from the sum of all the `timesteps_this_iter` values I returned.
https://github.com/ray-project/ray/blob/master/python/ray/tune/trainable.py#L279

I don't plot it myself - I just let the tune plot it from results dict.

I did not set any logging parameters.

**Comment by drozzy** [comment]
Hold on, I have an idea of what be happening.

**Comment by drozzy** [comment]
Hm... setting `grace_period=10` seems to get rid of this.
Perhaps something to do with restoring a trial - and me not setting the config values correctly?
I'll see if it comes up again and under what conditions.

**Comment by drozzy** [comment]
I've no idea why this happened... Seems ok now.
If I manage to reproduce will re-open.
