### ISSUE TITLE
Deploy jars to maven central repository

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#6876]
- [ ] Finalize the Java APIs. 
- [ ] Make sure the functionalities of Java part are enough to distribute a Java SDK:
        1.  Make sure that pure Java users can run local mode and cluster mode with a single Jar.
       2. Run the benchmarks and stress tests of Java part.
Note that we don't support cross-language calls in this version. That means  `cross-language-calls` feature is an experimental feature now. (This should be supported in next several versions.)

- [ ] Bump Java version to `0.8.0` and freeze the merging operations until bumping to `0.8.1-SNAPSHOT`.

ps: We should release Java part with the major releasing-process of Ray. That means for the next releasing of Ray, we should release wheel, and maven jars both.

After this release, I think we should improve our Java document as well. This seems an important issue for pure Java users now.

@ericl @raulchen @kfstorm  Please point out if I missed some thing.

**Comment by jovany-wang** [comment]
Hi, I'm planing to deploy Ray Jars with the version 0.8.0 to maven central repository , If I remember it correctly, we should provide a group-id  with our domain like org.ray  or io.ray (I assume that we use io.ray):
```xml
     //  Used by Ray Java users here.
     <dependency>
        <groupId>io.ray</groupId>
        <artifactId>ray-api</artifactId>
        <version>0.8.0</version>
     </dependency>
     <dependency>
        <groupId>io.ray</groupId>
        <artifactId>ray-runtime</artifactId>
        <version>0.8.0</version>
     </dependency>
```
Please let me know whether we have the full privileges of the domain ray.io .
@robertnishihara @pcmoritz

**Comment by raulchen** [comment]
Thanks. Looks good overall. A few things to notice:
1) we should package binaries of both Linux and macOS to the jar.
2) make sure we update Java version together with python version in the future.

**Comment by kfstorm** [comment]
We have an initial plan to update the Ray call API for Java for both cross and non-cross languages. If we released the jars to maven central repository before the API update is finished, we may encounter API break.

**Comment by raulchen** [comment]
@kfstorm yeah, we should finalize the API before officially release Java.
