### ISSUE TITLE
[Tune] Does resources_per_trial={'gpu':4} in tune equal to  tf.distribute.MirroredStrategy("4 GPUs")

### ISSUE THREAD

**Issue by JiayuanSternLi** [ray-project/ray#6887]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.0dev
python: 3.5
Tensorflow 2.1.0
Ubuntu 16.04

I wonder if resources_per_trial={"gpu":4} with num_samples = 1 using tune equal to tf.distribute.MirroredStrategy("4 GPUs") with a custom training loop without tune?  I am trying to count the time cost under varied GPUs number but get different results from them.

Custom training loop without tune: more GPUs, less time/epoch cost
tune API: more GPUs, almost same time cost (even increating a little more time/epoch)

Why??

**Comment by ericl** [comment]
The GPUs are just assigned via CUDA_VISIBLE_DEVICES, it doesn't actually do anything unless your code is using them (for example, using tf.distributed.MirroredStrategy).

**Comment by JiayuanSternLi** [comment]
> for example, using tf.distributed.MirroredStrategy

Can we combine MirroredStrategy with Tune?
