### ISSUE TITLE
[RLlib] Problematic usage of "iteration"

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#6893]
Using "iteration" in the documentation isn't ideal, because it doesn't clearly refer to step or iteration (the terms usually formally used), and a goal ought to be set somewhere to pull that out when doing documentation improvements. It seems like it should imply step, and is generally used as such throughout, but there are two genuine problems arising from this:

1) 
![tensorboard_episodes](https://user-images.githubusercontent.com/19422700/72952881-41021900-3d61-11ea-9ef7-c347e470a7d2.png)

As shown above, there's a logging variable called "episodes this iteration." If iterations mean episodes, this is meaningless, and if iterations means steps, this is backwards (i.e. it should be "iterations this episode"). I assume the second is the case.

2) All throughout the tune documentation, checkpoint_freq exclusively described as the "iterations" between checkpoints. When running it though, at least with MADDPG (in RLlib), it's treating the number as episodes. This is problematically unclear, given that elsewhere iterations is used to mean steps, and iterations seems to imply steps more than episodes.

cc @ericl

**Comment by justinkterry** [comment]
Surely the specific issues in 1 and 2 constitute legitimate bugs/problems, not just a proposed future upgrade?

**Comment by ericl** [comment]
Iterations means number of times we have executed a distributed train() step (neither environment timesteps nor episodes).

What would be a better name? We can't really drop it since this is the interval at which we record metrics and setting this incorrectly results in either not granular enough metrics or too much disk space usage.

**Comment by ericl** [comment]
Hmm `metric_window`?

**Comment by justinkterry** [comment]
`training_iterations` makes the most sense to me based on your description. I also literally can't find the place in the documentation where iteration is defined. 

Also, train() is normally called after every episode? That was my understanding at least.

**Comment by ericl** [comment]
There may be anything from a fraction (partial episodes) to a large number of episodes per iteration depending on the algorithm and settings.

**Comment by justinkterry** [comment]
Right. In that case I definitely thing `training_iterations` would resolve the ambiguity.

**Comment by surajp92** [comment]
Is there a way to change the number of environment time steps in one iteration, i.e number of times environment step() function gets called when you execute the trainer.train() function? In my custom environment, number of time steps per episode is fixed? Also, when does the environment state gets reset? at the end of each episode or at the beginning of the trainer.train() function? Thank you.
