### ISSUE TITLE
[RLlib] Right way to do CNN policies for MADDPG (PR)

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#6903]
I need to use MADDPG with a CNN policy, which doesn't currently support them. I'm willing to do a PR, but first I'd like to know what adding this the "right" way would look like?

**Comment by ericl** [comment]
It looks like MADDPG works with the standard rllib models API if you set "use_state_preprocessor": true, so you should be able to plug in any custom model: https://github.com/ray-project/ray/blob/master/rllib/contrib/maddpg/maddpg_policy.py#L360

Ex: https://github.com/ray-project/ray/blob/master/rllib/models/torch/visionnet.py
