### ISSUE TITLE
[rllib] How to compute custom metrics with episodes from evaluation stage?

### ISSUE THREAD

**Issue by coreylowman** [ray-project/ray#6917]
### What is your question?

When I say evaluation I mean the evaluation that is run based on the `evaluation_interval` configuration:

```
    # === Evaluation Settings ===
    # Evaluate with every `evaluation_interval` training iterations.
    # The evaluation stats will be reported under the "evaluation" metric key.
    # Note that evaluation is currently not parallelized, and that for Ape-X
    # metrics are already only reported for the lowest epsilon workers.
    "evaluation_interval": None,
    # Number of episodes to run per evaluation period.
    "evaluation_num_episodes": 10,
    # Extra arguments to pass to evaluation workers.
    # Typical usage is to pass extra args to evaluation env creator
    # and to disable exploration by computing deterministic actions
    # TODO(kismuz): implement determ. actions and include relevant keys hints
    "evaluation_config": {},
```

I'm running a MultiAgentEnvironment and want to access the episodes from the evaluation step to compute a custom metric score that will appear in tensorboard.

Specifically, I have N policies that are trained in a 2 player MultiAgentEnv. I want to run evaluation episodes between all the policies, and then based on the results of ALL the episodes from the evaluation, compute an ELO score for each of the policies using bayesian elo. I'd like this metric to be reported in tensorboard.

I already have code to compute ELO given the results of an episode, so I just need to figure out how to get access to the episodes and then how to put the metric in tensorboard. How do I go about this?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.8.0
Python version: 3.6.0

**Comment by ericl** [comment]
The only way to do this currently would be overriding the _evaluate() method of the Trainer class (you can check out the current impl to see what the it does).
