### ISSUE TITLE
[rllib] Consistent output handling with python API

### ISSUE THREAD

**Issue by rusu24edward** [ray-project/ray#6924]
### Describe your feature request

The command line interface for `rllib train` has a very nice `local-dir` option that saves all the files into that directory. I've been trying to accomplish the same with the Python API, but have not found a consistent way to handle it. So far, I've found that I can set `output` in the trainer config and also use the `trainer.save()` arg to get the output files into a specific directory, but it still doesn't get everything.

It would be nice if there was a single, consistent way to specify which output I want to use in the Python API, just like in the command line interface.

**Comment by ericl** [comment]
Does using `tune.run` or `tune.run_experiments` to run the Trainer do what you want? That is what train.py does under the hood (see https://github.com/ray-project/ray/blob/master/rllib/train.py)

**Comment by rusu24edward** [comment]
No, unfortunately this does not do what I want.

```
import ray
from ray import tune

ray.init()
tune.run(
    "PPO",
    stop={"episode_reward_mean": 200},
    config={
        "env": "CartPole-v0",
        "num_gpus": 0,
        "num_workers": 1,
		"output": 'path-that-I-want',
    },
)
```

This saves some files to the path that I want, but it still creates a ray_results in my home directory and saves files to there.

**Comment by rusu24edward** [comment]
Setting local_dir kwarg to tune.run does what I want. Thank you!
