### ISSUE TITLE
[tune] Expose experiment parameters (e.g. experiment name) to logger/config

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#6927]
See https://github.com/wandb/client/issues/801

**Comment by krfricke** [comment]
Hi @hartikainen, with the [new wandb integration](https://docs.ray.io/en/master/tune/tutorials/tune-wandb.html) wandb logging should be fine. The trial names are inferred automatically, but the project is not and has to be set separately. Is this something you would still like to see?

**Comment by richardliaw** [comment]
Think this is better supported now.
