### ISSUE TITLE
[tune] `tune.run` hangs for "long-running" functions

### ISSUE THREAD

**Issue by cbalaf** [ray-project/ray#6930]
`tune.run` works fine for optimization functions that exit quickly but hangs for longer running functions. 
The following script runs fine:
```
from time import sleep

import numpy as np
from ray import tune
from ray.tune import track
from ray.tune.schedulers import AsyncHyperBandScheduler

np.random.seed(123)
def dummy(config):
    duration = 20
    sleep(duration)
    mean_err = np.random.uniform()
    print('Simulated long task over')
    track.log(mean_err=mean_err)


if __name__ == '__main__':
    search_space = {'var1': tune.randint(2, 32),
                    'var2': tune.loguniform(1e-6, 1)}
    tune.run(dummy, num_samples=20, config=search_space,
             scheduler=AsyncHyperBandScheduler(metric="mean_err", mode="min"))
```

However, setting `duration=40` will cause ray to hang after the first pass of concurrent trials and never moves forward or completes the `progress.csv` and `result.json` files for the trials that kicked off.

MacOS 10.13.6
Python 3.7.4
ray 0.8.0

Any advice on how to get ray to run for a trial that takes longer than 30-ish seconds?

**Comment by richardliaw** [comment]
Hi @cbalaf, thanks for opening this issue! One question - is it possible break up the "simulated long task" into chunks? i.e.,


```
from time import sleep

import numpy as np
from ray import tune
from ray.tune import track
from ray.tune.schedulers import AsyncHyperBandScheduler

np.random.seed(123)
def dummy(config):
    duration = 20
    sleep(5)
    print('Simulated small portion of task over')
    track.log(mean_err=np.random.uniform())
    sleep(5)
    print('Simulated small portion of task over')
    track.log(mean_err=np.random.uniform())
    sleep(5)
    print('Simulated small portion of task over')
    track.log(mean_err=np.random.uniform())
    sleep(5)
    print('Simulated small portion of task over')
    track.log(mean_err=np.random.uniform())


if __name__ == '__main__':
    search_space = {'var1': tune.randint(2, 32),
                    'var2': tune.loguniform(1e-6, 1)}
    tune.run(dummy, num_samples=20, config=search_space,
             scheduler=AsyncHyperBandScheduler(metric="mean_err", mode="min"))
```

**Comment by richardliaw** [comment]
(BTW, setting duration to a higher duration in the above works for me fine)

**Comment by cbalaf** [comment]
@richardliaw thank you very much for your response!

Breaking the task down worked, though I can imagine situations where that is not possible or meaningful. Any advice there?

Also, out of curiosity, what system/environment did you use to get it to work with a higher duration?

**Comment by richardliaw** [comment]
I'm using a latest snapshot of master (https://ray.readthedocs.io/en/latest/installation.html) on a Mac 10.15 with py3.7.3. 

> Breaking the task down worked, though I can imagine situations where that is not possible or meaningful. Any advice there?

Agree, in theory, you should be able to use arbitrarily long duration tasks with Ray Tune.

**Comment by richardliaw** [comment]
@cbalaf thanks for closing - do feel free to open if this becomes an issue later down the road.
