### ISSUE TITLE
[Tests] Format script does not error when libraries are not installed

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#6934]
### What is the problem?
If flake8-comprehensions and flake8-quotes libraries are not installed, then running ci/travis/format.sh does not make the necessary checks. The script should give instructions on how to install the necessary libraries if they are not already installed.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run ci/travis/format.sh
If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by edoakes** [comment]
@rkooo567 is this fixed by your PR? If so could you close this issue? If not could you ask address this?

**Comment by rkooo567** [comment]
@holli Close it thanks to your PR! :)
