### ISSUE TITLE
[RlLib] Strange behavior surrounding episode reward vs policy reward in multiagent environments

### ISSUE THREAD

**Issue by justinkterry** [ray-project/ray#6970]
I have two similar multiagent RL environments, that I'm learning using a single policy network in the multiagent spec.

In environment A, everytime a good cooperative goal happens, every agent gets a reward. In this case my environment reward is the total reward given to all the agents ever, and my policy reward is that divided by the number of agents. This seems like the expected behavior.

In environment B, everytime an agent touches a good thing, it gets an individual reward in the reward dict. In this case, the policy reward is the total sum of rewards, and the environment reward is some number much larger than the individual reward that I'm not sure how is computed.

I've watched the reward dict outputs of every game, and played trained policies and manually added the rewards to confirm that the reward metrics I say are correct are correct.

What could be going on here?  This is either a bug or a major documentation problem. Relatedly, I can't find any documentation regarding what policy_reward actually is, and the code defining it when I referred to source was rather opaque.

Any ideas @ericl ?

Edit: I can't publicly include this code because it's going to ICML, but I can privately share it if needed.

**Comment by ericl** [comment]
The environment reward should be (mean) sum of all _agent rewards_ per episode.

Each policy reward will be the (mean) sum of all _agent rewards_, for agents assigned to that policy, per episode.

(and we don't track individual agent rewards since envs may have infinite number of randomly generated agent ids, etc.)

Let me know if that is not what you're seeing.

**Comment by justinkterry** [comment]
That's not what I'm seeing, and this is with the general multi agent API not MADDPG. Note here that there's only one policy for many agents.

For env A) policy reward appears to be mean of rewards per episode, env reward is sum of rewards per episode
For env B) policy reward appears to be sum of rewards per episode, env reward is some number of unclear origin or meaning larger than policy reward.

Both have the exact same learning code, and I looked through a bunch of printed reward dicts and computed the total reward on a trained policy to confirm all that behavior.

**Comment by justinkterry** [comment]
Also, this different between the two should be in the documentation and isn't

**Comment by ericl** [comment]
(B) does sound odd. You can see how the metric logic works in `metrics.py`:

```
        for (_, policy_id), reward in episode.agent_rewards.items():
            if policy_id != DEFAULT_POLICY_ID:
                policy_rewards[policy_id].append(reward)
```

Maybe adding some debugging code here would help. The `summarize_episodes` function is passed the full record of rewards for each agent in the env (for each episode, a map from (agent_id, policy_id) -> total reward for the agent), so you should be able to track down any calculation discrepencies just in this function.

> Also, this different between the two should be in the documentation and isn't

Yep, we should better document this. Want to submit a patch (after icml?)

**Comment by justinkterry** [comment]
I'll take a look into that. There's one other piece of potentially relevant information- tensorboard can't recognize the log file folders for env B, but they look completely normal to everyone else I've shown them to. I just kinda gave up on the issue.

**Comment by justinkterry** [comment]
Also, just to be clear, the reward the policy learns with is the policy_reward right? Because if that's the case then this is an "after ICML" problem.

**Comment by ericl** [comment]
Yeah, policies always learn on their own rewards, never the global one .
