### ISSUE TITLE
build.sh should be more specific about the allowed Python version

### ISSUE THREAD

**Issue by deanwampler** [ray-project/ray#6985]
I ran into an issue where `build.sh` dutifully detected I have Python 3.8 installed, but then the build mysteriously failed when it couldn't find the `0.14.0.RAY` wheel for `pyarrow`. That happened because no wheel exists at this time for Python 3.8.

So, 

1. `build.sh` should only allow versions of Python that are supported, i.e., for which artifacts exist.
2. As an extra sanity check, if the `pyarrow` wheel can't be found, suggest that the user verify they are using a supported version or Python (or similarly helpful message).

**Comment by edoakes** [comment]
@mehrdadn maybe you could take a look at this when you have a chance? No rush.
