### ISSUE TITLE
[Question][rllib] Stochastic Game tensorboard separate rewards

### ISSUE THREAD

**Issue by rusu24edward** [ray-project/ray#6986]
### What is your question?

I am designing a simple stochastic game wherein I have two agents. The first agent (the good guy) is rewarded according to some task. The second agent (the adversary) is rewarded negative proportional to the first. This is to encourage the adversary to screw up the good guy.

As a first pass, I just set the reward of the adversary equal to negative the reward of the good guy. This seems to cause some issue with tensorboard, however, because it looks like the rewards are summed together, which results is a reward of 0 for each iteration.

It would be nice to be able to visualize the rewards of each agent individually. I imagine that this would be very useful for other MARL scenarios, not just SG. Is this something that is possible?

Thank you!

python3.7
tensorflow2.1
ray0.8.1
mac10.14

**Comment by ericl** [comment]
Are you using separate policies for each agent? You can view the individual policy scores under the `policy_X_reward_mean` etc keys.

**Comment by rusu24edward** [comment]
I am using separate policies for each agent. I'm not sure what you mean by `policy_x_reward_mean` key. Is that something in the tensorboard interface?

**Comment by ericl** [comment]
Yep, you should be able to find those in tensorboard, `result.json`, or printed to stdout if you use the `-v` flag.

**Comment by rusu24edward** [comment]
Nice! I found them. For me, they are a few pages in stored as `policy_reward_mean/<policy_name>`

Thank you!
