### ISSUE TITLE
Allow `ray up` to take URL as argument.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#6993]
To get started with the autoscaler, we tell people to run a line like `ray up ray/python/ray/autoscaler/aws/example-full.yaml`. In practice, the steps are

1. Figure out that this means you have to clone the Ray repository.
2. Clone the Ray repository.
3. Figure out the new correct relative file path based on where you cloned it.
4. Run `ray up ...`.

Instead, we could let people just copy and paste the following command:

```
ray up https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/aws/example-full.yaml
```

In this blog post https://towardsdatascience.com/10x-faster-parallel-python-without-python-multiprocessing-e5017c93cce1, I posted benchmarks at the end that they could run with the autoscaler, but they still have to `wget` the relevant file. It'd be much easier if they could just use the URL.

Could also just write stuff like the following, but one line would be better.

```
wget https://raw.githubusercontent.com/ray-project/ray/master/python/ray/autoscaler/aws/example-full.yaml
ray up example-full.yaml
```

**Comment by richardliaw** [comment]
Actually, even better, maybe we can have default cluster profiles available. 

For example, 

```
ray up examples.tune
ray up examples.sgd
ray up examples.small
```

**Comment by simon-mo** [comment]
The url thing is a standard practice in kubernetes world. for example https://aws.amazon.com/premiumsupport/knowledge-center/eks-cluster-kubernetes-dashboard/

**Comment by robertnishihara** [comment]
@richardliaw the thing I like about the URL approach is that it is extensible, so if I write a blog post, I can host my own cluster yaml somewhere and then give people one command to run to reproduce the experiments.

**Comment by JosephTLucas** [comment]
This might be within my capability (found via `good first issue` tag).  Can someone reference me to the `ray up` section of the codebase?

**Comment by simon-mo** [comment]
Sure! Here's the code that correspond to `ray up` 

https://github.com/ray-project/ray/blob/b23b6addfcfd4be7a27e58aefbecb3fd7dd6510c/python/ray/scripts/scripts.py#L523-L566

https://github.com/ray-project/ray/blob/b23b6addfcfd4be7a27e58aefbecb3fd7dd6510c/python/ray/scripts/scripts.py#L999

**Comment by JosephTLucas** [comment]
Thanks! Yeah, I think I can do that.  I'll take a stab over the weekend and get you a PR.
