### ISSUE TITLE
[tune] tune.run does not contain progress_reporter as indicated in documentation

### ISSUE THREAD

**Issue by jiahao87** [ray-project/ray#7008]
Using the latest 0.8.1 version of ray, but looking at the tune.py script in my local site-packages, the function run seems different from the one in Github. E.g., the run function does not contain progress_reporter parameter. I was also not able to perform "from ray.tune import CLIReporter". Terminal reported "ImportError: cannot import name 'CLIReporter'". Tried upgrading many times by "pip install -U ray" as well but above issues remain. Any solution?

**Comment by richardliaw** [comment]
This problem should be gone if you install the latest wheels for the master branch. https://ray.readthedocs.io/en/latest/installation.html

**Comment by richardliaw** [comment]
I've also enabled the 0.8.1 docs to match with the release. Feel free to reopen if you run into any more issues.

**Comment by thavlik** [comment]
FYI I installed the latest wheel (0.8.1) and still encountered this issue.
