### ISSUE TITLE
[tune] End-to-end wandb example for model training

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7017]
There's no way to use `wandb.watch(my_model_instance)` with tune. This call is to track gradient and save the model graph, to show sth. like this
![image](https://user-images.githubusercontent.com/17963619/65387321-d0c69500-dd78-11e9-8238-422e3d0bf3bc.png)
The problem [user] encountered is `watch` should called after `init`, but if we put `watch` in logger like below, we can't catch the model instance it needs.
```
class ... (trainable):
   def _setup(self, config):
       m = Model().cuda()
       self.config['my_model'] = m

class wandblogger(tune.logger):
  def __init__(self):
      wandb.init(...)
      wandb.watch(config[my_model]) # pyarrow: ... can't pass cuda ... cpu memory, 
```
And we can't just do `init` and `watch` in `trainable` or `outside`, cuz it seems they and logger are in different process.

_Originally posted by @richardyy1188 in https://github.com/ray-project/ray/issues/4289#issuecomment-533878980_

**Comment by sumanthratna** [comment]
was this fixed in 0.8.7? #9725

**Comment by richardliaw** [comment]
Yep this is fixed!

**Comment by ColdFrenzy** [comment]
Hi @richardliaw,
I know that the issue is old, but could you provide some info on how to watch the model in wandb with tune.run if it's possible?
