### ISSUE TITLE
[tune?] Performance Bottleneck warnings - operation took x seconds [...]

### ISSUE THREAD

**Issue by antonwnk** [ray-project/ray#7018]
### Describe your feature request

After seeing ``The `step_name` operation took x.xx seconds to complete, which may be a performance bottleneck.`` warnings several times with different step names and time ranges I'm not sure whether the warnings are supposed to tell me my steps are running too long or too short.
I think the warning message could be made more instructive by including that information as well. I imagine it should be easy to add, since the warning logic is there already.

Not sure if the issue is tune-specific but it's the only way I've been using Ray so far.

**Comment by richardliaw** [comment]
OK got it; this is usually if the steps are *too long*. Feel free to add something more actionable to the warning message and push a PR.

**Comment by antonwnk** [comment]
I left this untended, sorry.
Can you explain/point me towards the rationale behind how long a tasks and its steps should be?
I'm trying to get a bit more context before starting a PR
