### ISSUE TITLE
Deprecate `._remote()` and replace all instances with `.options()` for remote functions and actors.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#7040]
Given a remote function like

```python
@ray.remote
def f():
    pass
```

We switched from syntax like

```python
f._remote(num_cpus=2)
```

to 

```python
f.options(num_cpus=2).remote()
```

Regarding deprecating `._remote`, their are several steps

1. Start logging a warning that tells people to use `.options()` instead.
2. In a subsequent release, change the warning to an exception.
3. In a subsequent release, remove the method entirely.

**Comment by richardliaw** [comment]
The completion of this issue also needs _documentation_ and thorough examples.

**Comment by deanwampler** [comment]
+1 This is a much more expressive, "fluent" API, easy to grasp and use.

**Comment by Pranav2612000** [comment]
I'll like to work on it.

**Comment by richardliaw** [comment]
@Pranav2612000 got it; please open a PR within the next couple of days!

**Comment by Pranav2612000** [comment]
> Regarding deprecating ._remote, their are several steps
> 
> Start logging a warning that tells people to use .options() instead.
> In a subsequent release, change the warning to an exception.
> In a subsequent release, remove the method entirely.

Right now, I should just log a warning, right?

**Comment by robertnishihara** [comment]
@Pranav2612000 yes, that sounds good.

**Comment by Pranav2612000** [comment]
Is this the function in question:-

>     def _remote(self,
>                 args=None,
>                 kwargs=None,
>                 num_return_vals=None,
>                 is_direct_call=None,
>                 num_cpus=None,
>                 num_gpus=None,
>                 memory=None,
>                 object_store_memory=None,
>                 resources=None,
>                 max_retries=None):

Should I add a line to log a warning message at the first line of the function?

**Comment by robertnishihara** [comment]
You can try that, but I believe that is called under the hood when we do `f.remote`, so you'll need to find a way to suppress that error when we call `f.remote`. One option would be to add an extra boolean argument to `_remote` indicating whether it is called directly or called from `f.remote`. Does that make sense?

**Comment by Pranav2612000** [comment]
Yes.` f.options().remote()` call the` _remote` function here:

>         class FuncWrapper:
>             def remote(self, *args, **kwargs):
>                 return func_cls._remote(args=args, kwargs=kwargs, **options)
> 
>         return FuncWrapper()
So I change to _remote function to the following:
> def _remote(self,
>                 args=None,
>                 kwargs=None,
>                 suppress_warnings = false,
>                 num_return_vals=None,
>                 is_direct_call=None,
>                 num_cpus=None,
>                 num_gpus=None,
>                 memory=None,
>                 object_store_memory=None,
>                 resources=None,
>                 max_retries=None)

and will add a line to log warnings if the variable `suppress_warnings` is false.
I changed the `remote` function to pass `suppress_warnings` as true to `_remote` so that no warnings will be logged in this case.
@robertnishihara Is that what were you suggesting? 
Any other changes or should I complete it this way?

**Comment by landcold7** [comment]
Hi, I added code to solve this issue, please take a look. @robertnishihara

**Comment by landcold7** [comment]
@robertnishihara Really needs your expertise to help me solve this issue, if you can have a moment, please take a look this PR https://github.com/ray-project/ray/pull/7676.
