### ISSUE TITLE
[Tune] BrokenPipeError when setting torch.dataloaders num_workers > 0 

### ISSUE THREAD

**Issue by sherylwang** [ray-project/ray#7047]
Hi，

I'm using tune PopulationBasedTraining with pytorch. I found when setting num_workers > 0 in dataloader with num_sample > 1, it will raise "BrokenPipeError: [Errno 32] Broken pipe" error. 
When don't use ray or just running the ray model, the error won't appear.
My ray[tune] version is 0.8.0, installed with pip, pytorch version is 1.2.0 cuda10.

**Comment by richardliaw** [comment]
Can you try deleting your custom dataloader? I think you can do this by putting `del {DataLoader}` in `_stop`. 

If you are using `reuse_actors`, you'll have to do it in `reset_config`.

**Comment by sherylwang** [comment]
Hi richardliaw. Thanks for your advice. I'm using the pbt scheduler, so I tried to delete the dataloader in reset_config function. When setting num_workers = 1, the broken pipe error still occurs in the first epoch(before the reset_config function be performed).

**Comment by sherylwang** [comment]
Actually, I found even  just warpped my pytorch model in ray.tune.Trainable. Then call the _train function to simply train the model, the num_workers in torch.utils.data.DataLoader seem not work, the data fetching time significantly increased compared to the raw torch model and training.

**Comment by richardliaw** [comment]
Can you provide a stack trace and repro script?

**Comment by sherylwang** [comment]
![image](https://user-images.githubusercontent.com/10609885/73902199-f7244180-48cf-11ea-9227-53dd0bbaaf27.png) This is the broken pipe error @richardliaw

**Comment by sherylwang** [comment]
I found the error  occurs due to improper data fetching method of torch's dataloader, the "next(iter(dataloader))" format actually makes the data fetching slow.

**Comment by sherylwang** [comment]
> Actually, I found even just warpped my pytorch model in ray.tune.Trainable. Then call the _train function to simply train the model, the num_workers in torch.utils.data.DataLoader seem not work, the data fetching time significantly increased compared to the raw torch model and training.

This is not caused by the Trainable wrapper, sorry. I've found the reason.

**Comment by richardliaw** [comment]
OK great; I'll close this issue then.

**Comment by koushikam** [comment]
Hi I am also getting the broken pipe error at Dataloader. I have 2 data train dataset and 2 testdata to load. Here is the snippet of the code:

E_trainloader = DataLoader(dataset=Energy_train, batch_size=int(config["batch_size"]),shuffle=True,num_workers=4)#,pin_memory=True)
    E_testloader =  DataLoader(dataset=Energy_test, batch_size=Ntotal-Ntrain,shuffle=True,num_workers=4)#,pin_memory=True)
    F_trainloader = DataLoader(dataset=Force_train, batch_size=int(config["batch_size"])*force_to_energy_ratio,shuffle=True,num_workers=4)#,pin_memory=True)
    F_testloader = DataLoader(dataset=Force_test, batch_size=Ntotal_force-Ntrain_force,shuffle=True,num_workers=1)#,pin_memory=True)
