### ISSUE TITLE
[tune] Copy this code at the time of experiment into results dir

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7049]
It would be really nifty to have the exact code that the experiment was run with copied to the results directory, just like in [sacred](https://sacred.readthedocs.io/en/stable/collected_information.html#source-code).

> Source Code
> To help ensure reproducibility, Sacred automatically discovers the python sources of an experiment and stores them alongside the run. That way the version of the code used for running the experiment is always available with the run.

Because when you run a lot of experiments it can be hard to tell what code change each experiment corresponds to.
I found that copying source was extremely helpful (especially for weeks old experiments).

**Comment by richardliaw** [comment]
Thanks for opening this issue! I've written something like this before but didn't find it useful (though I probably wasn't logging the right thing).

what would you like specifically here? the code of the trainable?

**Comment by hartikainen** [comment]
+1 for something like this. I personally don't need other than the git diffs to be copied over, but I guess copying over the whole sources wouldn't hurt anything. If I remember correctly, the wandb logger actually copied the git diffs over, which is great.

**Comment by richardliaw** [comment]
Oh nice; would you be open to pushing a PR @drozzy ?

**Comment by drozzy** [comment]
I think this could be easily achieved with Weights and Biases.
They provide the ability to [save](https://docs.wandb.com/library/save) code and mode and other data during runtime:
<img width="729" alt="Screen Shot 2020-05-23 at 3 11 45 AM" src="https://user-images.githubusercontent.com/140710/82724312-24d89f00-9ca3-11ea-8909-b0ee0725fe11.png">

I've been using it for my logging and so far so good.

I'm going to close this for now as I actually think that adding this will make it ray/rllib too bloated I think.
