### ISSUE TITLE
[rllib] Key set for obs and rewards must be the same

### ISSUE THREAD

**Issue by rusu24edward** [ray-project/ray#7056]
# What is your question?

I'm implementing a stochastic game, where two players take turns performing actions to modify the state of the game. In order to make this happen, I use the following logic in `step`:
```python
step(self, action_dict):
    if action_dict.get(player_1) is not None:
        state = update_from_player_1()
        reward = {'player1': reward_for_your_action()}
        obs = {'player2': new_state()}
    if action_dict.get(player_2) is not None:
        state = update_from_player_2()
        reward = {'player2': reward_for_your_action()}
        obs = {'player1': new_state()}
    return obs, reward, done, info
```
This makes the most sense to me since I think of the reward as being an environment's response to an action (in addition to an updated state), and the player who receives that reward should be the player who acted. Thus, even though the output is for the next player, the reward should be for the player that acted.

Trying to do it this way results in the error: `Key set for obs and rewards must be the same`. So I would have to modify the reward so that the player who is receiving the next state is also receiving a reward. I can still work with this consistently by storing the reward and applying it on opposite turns (i.e. the reward from player_2's turn gets applied during player_1's turn), but this just *feels weird*. It seems that the reward should be applied with the action, not with the next observation.

Am I thinking about this incorrectly? What as the reason behind designing it this way?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.1
Python 3.7
TF 2.1
Mac 10.14

**Comment by ericl** [comment]
Yeah, I agree this is undesirable.

Would automatically buffering the reward to the next time-step for that agent work for you? We can raise an error if no reward is specified, or if two different rewards are given for an agent on one of its own steps.

**Comment by rusu24edward** [comment]
> Would automatically buffering the reward to the next time-step for that agent work for you?

Can you explain to me a little bit about what this means?

**Comment by sven1977** [comment]
I guess what @ericl meant is that your Env should store player1's reward (when it returns player2's obs), not returning it, until the next time step and then return reward1 together with obs1. So in other words: rewards are always delayed by 1ts, but always go together with the corresponding player obs.

**Comment by rusu24edward** [comment]
Ah, I see. Yes, that's effectively what I am doing now and it seems to be working correctly.

**Comment by coreylowman** [comment]
What happens when the game ends on one player's turn and both players need rewards? (I'm thinking about this from a board game stand point, like chess, where the game might end and both players might need to get rewards). Ideally the reward would be retroactively applied to the non-turn player?

**Comment by ericl** [comment]
I think you can always return obs (a noop obs for the last step) and
rewards as long as done hasn't been sent yet to the agent.

**Comment by rusu24edward** [comment]
Just for the record, I don't think **automatically** buffering the reward is the right thing to do because it violates some basic principles of MDP's (I explain a bit [here](https://github.com/ray-project/ray/issues/9029#issuecomment-704006748)). This may be something that a user wants to try out, but this should not be the default behavior.
