### ISSUE TITLE
[tune] Hyperopt IndexError: list index out of range

### ISSUE THREAD

**Issue by akurniawan** [ray-project/ray#7058]
### What is the problem?
On space dictionary below, if I use hp.uniform everything run smoothly. However, if I change it to hp.choice I got **IndexError: list index out of range**

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python: 3.7
OS: Catalina 10.15.2
Ray: 0.8.1

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```py
"""This test checks that HyperOpt is functional.

It also checks that it is usable with a separate scheduler.
"""
import ray
from ray.tune import run, Trainable
from ray.tune.schedulers import AsyncHyperBandScheduler, HyperBandScheduler
from ray.tune.suggest.hyperopt import HyperOptSearch


class TestingTrainable(Trainable):
    def _setup(self, config):
        self.activation = config["activation"]
        self.width = config.get("width", 10)
        # self.height = config["height"]

    def _train(self):
        assert type(self.activation) == str, \
            "Config is incorrect: {}".format(type(self.activation))
        # return {"mean_loss": (self.height - 14)**2 - abs(self.width - 3)}
        return {"mean_loss": 10}

    def _save(self, checkpoint_dir):
        return checkpoint_dir

    def _restore(self, checkpoint_path):
        pass


if __name__ == "__main__":
    import argparse
    from hyperopt import hp

    parser = argparse.ArgumentParser()
    parser.add_argument("--smoke-test",
                        action="store_true",
                        help="Finish quickly for testing")
    args, _ = parser.parse_known_args()
    ray.init()

    space = {
        # "width": hp.uniform("width", 0.001, 1),
        "width": hp.choice("width", [1]),
        # "height": hp.choice("height", [1, 2, 3]),
        # "height": hp.uniform("height", -100, 100),
        "activation": hp.choice("activation", ["relu", "tanh"]),
    }

    current_best_params = [
        {
            "width": 1,
            # "height": 2,
            "activation": 0,  # Activation will be relu
        },
        {
            "width": 4,
            # "height": 2,
            "activation": 1,  # Activation will be tanh
        }
    ]

    config = {
        "num_samples": 10 if args.smoke_test else 1000,
        "stop": {
            "training_iteration": 100
        },
    }
    algo = HyperOptSearch(space,
                          max_concurrent=4,
                          metric="mean_loss",
                          mode="min",
                          points_to_evaluate=current_best_params)
    scheduler = AsyncHyperBandScheduler(metric="mean_loss", mode="min")
    run(TestingTrainable, search_alg=algo, scheduler=scheduler, **config)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Hi @akurniawan, thanks a bunch for opening this issue. This seems like a big issue; I'll take a look at this later this week.

**Comment by richardliaw** [comment]
BTW @akurniawan, sorry for taking so long; I'll get to this on the weekend. If you want to take a crack at addressing the bug, you might want to start here: https://github.com/hyperopt/hyperopt/issues/615 which seems relevant.

**Comment by magdapoppins** [comment]
I am also occasionally getting the same issue when calling `randint_via_categorical_lpdf(sample, p)` via `rec_eval()`. In my case `sample` will contain values like 259, although the length of p[0] is only 131. (In hyperopt/tpe.py line 72.) Would be happy to share more details if needed.

**Comment by krfricke** [comment]
The problem here lies in your specification of the `current_best_params` dict. With a `hp.choice()` parameter, the best param should refer to the _index_ of the best parameter, not the value. If you use

```
    current_best_params = [
        {
            "width": 0,  # Width will be 1
            "activation": 0,  # Activation will be relu
        },
        {
            "width": 0,  # Width will be 1
            "activation": 1,  # Activation will be tanh
        }
    ]
```

it runs smoothly.

We will discuss if it makes sense to change this to a value-based setting.
