### ISSUE TITLE
[tune] Optional GPU allocation per trial when available

### ISSUE THREAD

**Issue by seanbow** [ray-project/ray#7078]
If i have some objective function I'm trying to optimize that can be accelerated with a GPU but doesn't require one, it appears that there's no way to tell tune to allocate a process a GPU only if one is available. Setting resources_per_trial['gpu'] > 0 refuses to start running a trial unless a GPU is available. 

Is there any way to tell ray.tune to allocate a GPU if it is available, otherwise only allocate the CPUs requested? Right now I'm stuck underutilizing the hardware resources I have available.

**Comment by richardliaw** [comment]
Hm, can you tell me more about your use case? 

I guess preemptively, one option may be to use https://github.com/anderskm/gputil and try something like the following?

```
# find the right call here?
resources_per_trial={"gpu": 1 if GPUtil.has_available_gpu() else 0}
```

**Comment by seanbow** [comment]
Sure. I'm trying to optimize the hyperparameters of a relatively simple neural network that can absolutely be run on a CPU but is large enough to get a fairly decent speedup on the GPU. I'm using ray::Tune with the hyperopt search algorithm.

Because my computer has 16 cores and only 1 GPU, and my GPU only has enough memory to fit ~3 instances of the network in it at the largest network hyperparameter settings, I'm left with the choice of either running 3 parallel jobs on the GPU (with `resources_per_trial = {'gpu': 0.3}`) or ~16 on the CPU.

`has_available_gpu()` will be evaluated before `ray.tune.run` and thus will be set to `resources_per_trial = {'gpu': 1}` then, no? Resulting in only one job being run at a time.

**Comment by richardliaw** [comment]
In this situation, I would just have a check in `_setup` to see if a GPU is available and acquire a Filelock to make sure only one training worker can keep it. I would also set `resources_per_trial = {"CPU": 1}` and handle the GPU allocation (cuda visible devices) out of band.
