### ISSUE TITLE
[tune] tensorflow2 and resources_per_trial

### ISSUE THREAD

**Issue by scarrazza** [ray-project/ray#7092]
What is the proper way to limit thread usage by trials stated in `resources_per_trial` when using tensorflow>=2 code? Should the user or ray care about limiting the intra/inter number of threads?

My tests on a single machine show that ray does not virtualize/sandbox the number of requested cpus per trial thus tensorflow runs with its default configuration on all available machine threads.

* Ray 0.8.1, Tensorflow 2.0.0

**Comment by richardliaw** [comment]
Good point; I think this is the API - https://www.tensorflow.org/api_docs/python/tf/config/threading

Feel free to push a fix to the docs.
