### ISSUE TITLE
Why is PyArrow packaged inside of Ray instead of as a dependency?

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#7097]
### What is your question?

Why is PyArrow packaged inside of Ray instead of as a dependency?

**Comment by richardliaw** [comment]
cc @pcmoritz

**Comment by pcmoritz** [comment]
@holdenk We are working on changing that, but it takes some time. The last part that needs work is removing the dependency from https://github.com/ray-project/ray/blob/master/python/ray/experimental/async_api.py and https://github.com/ray-project/ray/blob/master/python/ray/experimental/async_plasma.py, that's something @simon-mo is working on. He should be able to comment on an ETA.

**Comment by simon-mo** [comment]
@ijrsvt is working on porting async plasma to cpp side so we can remove pyarrow dependency. as for an ETA, we might be able to get it in by the Feb release, otherwise it will be in the March release. I will comment on this thread when we remove it from nightly release.

**Comment by simon-mo** [comment]
The nightly build removed pyarrow dependency. https://ray.readthedocs.io/en/latest/installation.html#latest-snapshots-nightlies

**Comment by simon-mo** [comment]
Fixed by commit https://github.com/ray-project/ray/commit/2116fd3bcaf9552b2273cbc10e90cc6d66e904a8

**Comment by holdenk** [comment]
So with that change, does ray not use pyarrow anymore?

**Comment by simon-mo** [comment]
Ray directly use arrow via cpp bindings.

**Comment by holdenk** [comment]
Cool, is there somewhere the version of Arrow is specified for folks looking to integrate?
