### ISSUE TITLE
[RLlib] Errors originating from environment workers cause training to stall

### ISSUE THREAD

**Issue by elpollouk** [ray-project/ray#7106]
### What is the problem?

Ray: 0.8.0/0.8.1
OS: Ubuntu 16.04/18.04

Errors originating from environment `step()` or `reset()` functions cause training to stall when using  `AsyncSamplesOptimizer` (e.g. IMPALA) even if `ignore_worker_failures: True` is set in the experiment config.

If an environment request fails, the generator returned by `TaskPool.completed_prefetch()` never runs to completion and so `self._fetching` isn't cleared down properly. This results in stale object ids being used on the next training iteration causing #7105 to manifest itself, stalling the experiment.

### Reproduction

1. Set up an IMPALA experiment with external environments
2. After a few training iterations, kill one of the external environments

#### Result:

After `Trainer._try_recover()` has black listed the failed worker, the experiment will stall with the following call stack:
```
Thread 46562 (idle): "MainThread"
    get_objects (ray/worker.py:318)
    get (ray/worker.py:1450)
    ray_get_and_free (ray/rllib/utils/memory.py:33)
    _augment_with_replay (ray/rllib/optimizers/aso_aggregator.py:170)
    iter_train_batches (ray/rllib/optimizers/aso_aggregator.py:117)
    _step (ray/rllib/optimizers/async_samples_optimizer.py:178)
    step (ray/rllib/optimizers/async_samples_optimizer.py:136)
    _train (ray/rllib/agents/trainer_template.py:129)
    train (ray/tune/trainable.py:176)
    train (ray/rllib/agents/trainer.py:433)
    actor_method_executor (ray/function_manager.py:766)
    main_loop (ray/worker.py:433)
    <module> (ray/workers/default_worker.py:118)
```

### Potential Fix

Rather than using a list for `self._fetching` in `TaskPool`, you can use a queue so that items that are going to be freed are automatically removed from the list of tasks to be fetched. This also ensures that the fetching list is always up to date, even if the generator is stopped early.

Here's a example fix that I'm currently testing:
[actors.py.diff](https://gist.github.com/elpollouk/1d0cb83bd98c7a9fa4c9226c66ea07ee)

I haven't dug into the access pattern for `TaskPool` beyond my current scenario, so I'm not sure if a lock should be added around modifications to `self._fetching`. I'm also unaware if there are any subtle side effects of removing items from the fetching list that the original authors were considering when implementing the current logic, so any thoughts here would be greatly appreciated.

**Comment by ericl** [comment]
@elpollouk could you try out the latest wheel and see if this is still an issue? The hang fix is merged in master as of https://github.com/ray-project/ray/pull/7117

**Comment by elpollouk** [comment]
Trying the latest nightly and the experiment does continue to run after knocking out workers.

However, it does appear that you're still re-using object ids for sample batches you've already processed after an error. Is this a concern?

The issue I was attempting to fix with my patch was that you are relying on the `completed_prefetch` generator to run to completion in order to maintain correct state in the `TaskPool`. However, generator completion is never guaranteed as iteration can be stopped at any time either by an exception or other halting condition. Although fixing the symptom of #7105 is working now, that fact that it possible for `TaskPool` to get itself into an inconsistent state will likely manifest itself again in the future via other non-obvious bugs.

**Comment by ericl** [comment]
The patch makes sense. Do you want to make a PR for it?

**Comment by elpollouk** [comment]
PR submitted, have fun!
