### ISSUE TITLE
Turn off OMP_NUM_THREADS warnings? 

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#7112]
Can we just turn off the warnings on each ray.init? We can't force everyone to set the environment variable. 

https://github.com/ray-project/ray/blob/3f99be8dad5e0e1abfaede1f25753a0af74f1648/python/ray/__init__.py#L16-L21

**Comment by simon-mo** [comment]
I promoted this to release blockers because many users may find this warning annoying. (cc @pcmoritz @robertnishihara )

**Comment by robertnishihara** [comment]
How about we change the log level to INFO?

**Comment by simon-mo** [comment]
@robertnishihara sounds good. PR here https://github.com/ray-project/ray/pull/7114
