### ISSUE TITLE
Failed to submit task to AWS cluster

### ISSUE THREAD

**Issue by borovikovd** [ray-project/ray#7122]
### What is the problem?

Ray: 0.8.1
Python: 3.6.9
OS: macOS 10.15

I am trying to submit a script using a command `ray submit tune-default.yaml tune_script.py --start --args=”localhost:6379”` but this command fails with a message:

`subprocess.CalledProcessError: Command '['ssh', '-i', '/Users/denis/.ssh/ray-autoscaler_eu-west-1.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_c3875d07f4/3b4bd7258f/%C', '-o', 'ControlPersist=10s', 'ubuntu@XX.XX.XX.XX', 'bash', '--login', '-c', '-i', "'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray stop'"]' returned non-zero exit status 1.`

I tried to run this command manually and the result is:

`bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell`

It seems that ray is trying to run bash in interactive mode (-i argument) which requires a terminal device allocated (-t flag for ssh).

I tried to minimise the command to debug the problem and this is what I got:

`ssh -i /Users/denis/.ssh/ray-autoscaler_eu-west-1.pem ubuntu@XX.XX.XX.XX bash -c -i 'echo test'`

It fails with the same message:

`bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell`

### Reproduction (REQUIRED)

`ray submit tune-default.yaml xxx.py --start --args=”localhost:6379”`

where tune-default.yaml  is:

```
cluster_name: tune-example
provider: {type: aws, region: eu-west-1}
auth: {ssh_user: ubuntu}
min_workers: 3
max_workers: 3
# Deep Learning AMI (Ubuntu) Version 21.0
head_node: {InstanceType: c5.xlarge, ImageId: ami-078d068af898f9114}
worker_nodes: {InstanceType: c5.xlarge, ImageId: ami-078d068af898f9114}
setup_commands: # set up each node.
    - pip install ray torch torchvision tabulate tensorboard
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Thanks for opening this issue, @borovikovd! 

First, `bash: cannot set terminal process group (-1): Inappropriate ioctl for device bash: no job control in this shell` is actually harmless, and doesn't seem to be the real issue here.


```
subprocess.CalledProcessError: Command '['ssh', '-i', '/Users/denis/.ssh/ray-autoscaler_eu-west-1.pem', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlMaster=auto', '-o', 'ControlPath=/tmp/ray_ssh_c3875d07f4/3b4bd7258f/%C', '-o', 'ControlPersist=10s', 'ubuntu@XX.XX.XX.XX', 'bash', '--login', '-c', '-i', "'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray stop'"]' returned non-zero exit status 1.
```

means that this actually failed on `ray stop`. If you ssh into the node and run `ray stop`, does it actually return an exit code of 0? 

Please let me know! I'll update the docs to make this better.

**Comment by borovikovd** [comment]
Thanks, @richardliaw! The stop command was indeed failing. Maybe it's something I didn't expect 'cause there was no actual error message shown. Just some ideas on how it could be improved:

1) I think if a remote command fails it's quite weird to see a stack trace. A stack trace makes me think that the tool you are running has a bug. I.e. I would rather show a nice error message with explanation of what happened.

2) It would way mich easier to debug if ray showed the original error message (in this case error of running ray stop) back to the user.
