### ISSUE TITLE
ray + jupyterhub on Kubernetes

### ISSUE THREAD

**Issue by bodikp** [ray-project/ray#7123]
Hi,
I'm running ray on a kubernetes cluster and ray.init(address='...') succeeds when running on the head node or the workers. However, I'm also running JupyterHub on the same cluster and would like to connect to ray from the pods that are spawned by JupyterHub.

Running ray.init from the JupyterHub container fails with "2020-02-11 16:53:01,783	WARNING services.py:172 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?"

What are the requirements to get this scenario to work? Do I need to "ray start" on the JupyterHub container?

I tried that but that fails with the following:
Exception: Version mismatch: The cluster was started with:                                                                                                                                  Ray: 0.9.0.dev0                                                                                                                                                                         Python: 3.6.8                                                                                                                                                                           Pyarrow: 0.14.0.RAY                                                                                                                                                                 This process on node 10.240.0.106 was started with:                                                                                                                                         Ray: 0.8.1                                                                                                                                                                              Python: 3.7.6                                                                                                                                                                           Pyarrow: 0.14.0.RAY                 

I tried to get the ray versions to match, but 1) don't know which rayproject/autoscaler image has ray 0.8.1 and 2) don't know how to install ray 0.9.0.dev0 on the JupyterHub container.

Thanks for any help on this.

**Comment by bodikp** [comment]
I installed ray 0.9.0.dev0 on the JupyterHub container, did 'ray start ...' and now I can connect. Is that the right way to do this?

Does ray support multiple users calling ray.init() and launching their own tasks?

**Comment by richardliaw** [comment]
@bodikp yep that should work. Alternatively, for kubernetes, the recommended way to use ray is for each person to start a new cluster.

**Comment by rmkohlman** [comment]
I am as well having a hard time trying to connect to ray head from jupyterhub notebook.
env : k8s on docker desktop Mac 
installed  : ray k8s operator, k8s jupyterhub. 
ray cluster :  example-cluster2-ray-head (example from operators on ray.io page)

error I get:
2021-03-02 05:46:36,099	INFO worker.py:113 -- Waiting for Ray to become ready on the server, retry in 5s...
2021-03-02 05:46:46,074	INFO worker.py:113 -- Waiting for Ray to become ready on the server, retry in 10s...
2021-03-02 05:47:01,094	INFO worker.py:113 -- Waiting for Ray to become ready on the server, retry in 15s...
...
...
ConnectionError: ray client connection timeout


![image](https://user-images.githubusercontent.com/45956230/109605237-1052ee00-7ae2-11eb-91b4-a1788c733f4e.png)
