### ISSUE TITLE
Ray start failed on worker nodes for DeprecationWarning

### ISSUE THREAD

**Issue by luigiw** [ray-project/ray#7127]
### What is the problem?

Ray version 0.8.1

When running ray start on worker nodes with --redis-address option, the command fails for DeprecationWarning, whereas ray start head works with the same option.

I understand redis-address will be deprecate eventually, but failing on a warning is very weird behavior, and breaks existing code.  

### Reproduction (REQUIRED)

Start ray head 

ray start --head --redis-port=6379 --redis-shard-ports=6380,6381 --object-manager-port=12345 --node-manager-port=12346 --num-cpus=2

Start ray worker

ray start --object-manager-port=12345 --node-manager-port=12346 --redis-address=localhost:6379 --num-cpus=2

I'm seeing below error on worker,

Traceback (most recent call last):
  File "/home/hanchi/.local/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/hanchi/.local/lib/python3.5/site-packages/ray/scripts/scripts.py", line 896, in main
    return cli()
  File "/home/hanchi/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hanchi/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hanchi/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hanchi/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hanchi/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hanchi/.local/lib/python3.5/site-packages/ray/scripts/scripts.py", line 244, in start
    raise DeprecationWarning("The --redis-address argument is "
DeprecationWarning: The --redis-address argument is deprecated. Please use --address instead.

If we cannot run your script, we cannot fix your issue.

- [x ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Deprecation warning is an exception, so I think the behavior is fine - https://docs.python.org/3.7/library/exceptions.html#DeprecationWarning

Maybe we can raise `ValueError` instead?

**Comment by luigiw** [comment]
So starting from 0.8.1, --redis-address can't be used at all? I tested the same commands with 0.8.0, no issue there. 
I guess another confusing part is that ray start head works but ray start doesn't.

**Comment by luigiw** [comment]
> Deprecation warning is an exception, so I think the behavior is fine - https://docs.python.org/3.7/library/exceptions.html#DeprecationWarning
> 
> Maybe we can raise `ValueError` instead?

So starting from 0.8.1, --redis-address can't be used at all? I tested the same commands with 0.8.0, no issue there.
I guess another confusing part is that ray start head works but ray start doesn't.

**Comment by richardliaw** [comment]
You should `--address` instead.
