### ISSUE TITLE
[rllib] MultiagentEnv with two Trainers and shared experiences

### ISSUE THREAD

**Issue by jose-amendola** [ray-project/ray#7130]
First of all, congratulations for the work!Very resourceful!

I am attempting to train a Hierarchical RL agent, where the high level agent is trained with DDPG and the low level agent is trained with DQN. From the examples, I tried calling train() method from both trainers in sequence at each loop iteration, but the experiences are collected separately. Any hints of how should I use different trainers with shared sampling? Do I need to implement a custom trainer?

Thanks in advance.

**Comment by sven1977** [comment]
A very interesting setup, but I don't think we support hierarchical RL yet. I'm guessing you would like to pass the outputs of the high-level trainer down to the low-level one (kind of like picking an option/skill), and probably only from time to time. It also seems like the low-level trainer needs to operate on a different observation space (including the high level output).
Just out of curiosity: Which algo/paper are you trying to implement?

**Comment by jose-amendola** [comment]
Actually, RLLIB brings the example hierarchical_rl.py, where it uses MultiAgentEnv structure. However, it trains both agents using the same trainer. The observation and action spaces are indeed different and the action from the high-level-agent implies a new set-point for the low-agent to track. I think the paper which would mostly suit as my benchmark right now is "Hierarchical Deep Reinforcement Learning:Integrating Temporal Abstraction and Intrinsic Motivation" although I do not strictly follow the implementation details.

**Comment by ericl** [comment]
I think you would have to write a custom trainer right now -- right now we don't have a good story for how to auto-compose these two different training workflows.

**Comment by sven1977** [comment]
Cool stuff. I remember that paper. From the times, where everyone tried to get better results on Monetzuma (as it was the worst in DQN2015 :) ).
Discussing this internally right now. Will get back to you on this one.
