### ISSUE TITLE
How to submit a task which is implemented in a  separate module?

### ISSUE THREAD

**Issue by maxCodeVector** [ray-project/ray#7133]
## Evironment
- python version: 3.7.6
- ray version: 0.8.1
- OS of driver: ubuntu 18.04
- OS of worker: ubuntu 18.04

Hi, I met a problem recently when I was using ray. I want to let my remote function run in the remote node. This function was not written in the main script file but in a separate file. However, I get a exception said: `This function was not imported properly`.

This is what my script is written:
```python
## module-test.py

import ext_module
import ray

@ray.remote
def other_module():
    return ext_module.cac_sqrt3()

if __name__ == '__main__':
    ray.init(address='auto', redis_password='5241590000000000')
    res = other_module.remote()
    print("result is:", ray.get(res))

## ext_module.py

def cac_sqrt3():
    return 1.732
```

I build a cluster of three nodes (one head node and two other nodes),
to make sure the task is not run in the local machine when I connect the cluster, I set num-cpus=0
```
ray start --address='xxxxxxx' --redis-password='5241590000000000' --num-cpus=0
```

This is what the error log like:
```
2020-02-12 12:12:23,627	WARNING worker.py:1063 -- Failed to unpickle the remote function '__main__.other_module' with function ID bb6e6179f5b2ef0eb388e72b4492bf508bc9ed39. Traceback:
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/ray_dev/lib/python3.7/site-packages/ray/function_manager.py", line 402, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/home/xxx/miniconda3/envs/ray_dev/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py", line 1136, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'ext_module'


Traceback (most recent call last):
  File "module-test.py", line 20, in <module>
    print("result is:", ray.get(res))
  File "/home/xxx/anaconda3/envs/ray_dev2/lib/python3.7/site-packages/ray/worker.py", line 1492, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::__main__.other_module() (pid=16330, ip=xxxxxx)
  File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
Exception: This function was not imported properly.
```

What should I do to make it run normally?

**Comment by rkooo567** [comment]
Can you try this?
https://github.com/ray-project/ray/issues/3116

**Comment by maxCodeVector** [comment]
@rkooo567 Thank you for your advice. I check that issue. After synchronizing the two files in the remote node at the same path which has been contained in the `sys.path`, it works normally. Thanks.

**Comment by Julianbaozi** [comment]
@maxCodeVector I have ran into the same issue. I add the path to the module into sys.path. It still cannot be found. Do you have any suggestions?

**Comment by maxCodeVector** [comment]
You could try to copy the corresponding files to the same path in the remote server.



---Original---

**Comment by Julianbaozi** [comment]
Thank you for your response.

**Comment by tmsss** [comment]
I have the same problem running with a local script, I've added the path, but I still run into a ModuleNotFoundError. Is there any workaround?

**Comment by maxCodeVector** [comment]
You might want to copy the relative scripts to easy nodes of the cluster.&nbsp;


发自我的iPhone

------------------ Original ------------------

**Comment by jseppanen** [comment]
also this patch to cloudpickle might help: https://github.com/cloudpipe/cloudpickle/pull/391

**Comment by MartinBubel** [comment]
I encountered this issue as well. I found a workaround which might be far away from a best-practice style but might be helpful for anyone looking for a simple fix:<br>
For me, moving the `sys.path.append` and the respective `import ...` to the `@ray.remote` function
```
@ray.remote
def some_function():
    sys.path.append('...')
    import ...
    ...
```
fixed the issue. That workaround for sure is inefficient and kind of ugly but may do the job for anyone simply trying to get some code running on a cluster.

**Comment by architkulkarni** [comment]
Runtime Environments should be the best-practice solution this issue--please let us know if there's any gap in the functionality! https://docs.ray.io/en/latest/handling-dependencies.html#runtime-environments. (See the `working_dir` and `py_modules` fields)
