### ISSUE TITLE
How to customize observation space?

### ISSUE THREAD

**Issue by dxu23nc** [ray-project/ray#7138]
I have read some examples. It seems that if we want to customize the observation and action, we have to change the code of the gym. Am I correct?

**Comment by yutaizhou** [comment]
You don't change gym code itself, there are already some gym spaces that you can use. use this interface to tailor your environment to have the proper representation.
https://github.com/openai/gym/tree/master/gym/spaces

**Comment by dxu23nc** [comment]
Thanks for the reply. 

 The sample() function is to extract the observation that we need from the raw observation, it is like getting the first 56 unit from the raw 128byte RAM considered an atari game.   The gym does not give enough examples to show how to use that. So is my understanding right?

Thanks in advance.

**Comment by yutaizhou** [comment]
sample() doesn't extract observation, it merely draws a random value from whichever gym space you used. So if you do 
`gym.spaces.Discrete(5).sample()`

That is equivalent to uniformly sampling for the discrete values 0-4. 

Extracting observation is to be handled by you as part of the reset() or step() methods from gym.

**Comment by dxu23nc** [comment]
Thanks.

**Comment by yutaizhou** [comment]
@dxu23nc please close this issue if your problem has been resolved.
