### ISSUE TITLE
Inconsistent sample count for MultiAgentEnv [rllib], [tune]

### ISSUE THREAD

**Issue by vivecalindahlericsson** [ray-project/ray#7153]
### What is the problem?
Assertion error triggered for MultiAgentEnv
```
assert next_sample.count >= sample_batch_size * num_envs_per_worker
``` 

* Ray 0.8.1, tensorflow 2.0.0,  Mac OS/Ubuntu

### Reproduction (REQUIRED)
[mockenv-debug.zip](https://github.com/ray-project/ray/files/4198196/mockenv-debug.zip)

Do `./mockenv-debug.zip`

The bug can be avoided by ensuring `batch_size % end_time== 0`, where `end_time` equals the number of steps per episode (see script).

It also gets triggered when running in local mode.

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [x ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by ericl** [comment]
Thanks for the repro. I think the assertion is incorrect, fixed here: https://github.com/ray-project/ray/pull/7157

**Comment by vivecalindahlericsson** [comment]
thanks, I hope the fix is really that simple :)
