### ISSUE TITLE
talk about some potential improvements of ray

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#716]
（1）As far as i know, in the architecture of parameters server and worker of tensorflow, computing gradients and transfering gradients to parameters server are doing simultaneously in order to speed up. However, ray does this in a serial mode which may affect the performance a lot especially when the model is big.
（2）The concept of driver in ray is similar to parameters server when collecting gradients to driver, it has an potential risk of having an out of memory error because all gradients are collecting to driver. In tensorflow, there are more than one parameters server. The gradients of multiple points are transmitted to a point, the speed is limited by the bandwidth of the single point network card.

I am not very sure the advises are true for ray. If so, Is there a good way or plan to overcome these problems? 

Thank you

**Comment by robertnishihara** [comment]
The main difference between our object store and a parameter server is that objects in the object store are "immutable" once they have been written. There are probably some performance gains that could be obtained for certain applications (e.g., A3C) by mutating and reusing the same shared-memory buffers (however, I'm not sure exactly how large these gains are). When you're doing dense updates anyway, the extra copy is often not a big deal. However, we'd need to figure out the best way to expose mutable objects through the API (e.g., what are the semantics on multiple machines, do we want to do anything to prevent the data from being corrupted by non-atomic writes, etc).

As for running out of memory, that could certainly happen if you collect more arrays together on one driver than you have room for. It's possible that we could get around this by implementing an efficient all reduce or something like that.

**Comment by robertnishihara** [comment]
Closing for now.
