### ISSUE TITLE
[rllib] A way to add more info to the input_dict?

### ISSUE THREAD

**Issue by alversafa** [ray-project/ray#7161]
What would be the easiest way to add `prev_dones` (as like `prev_rewards` and `prev_actions`) to the `input_dict`?

This is for the case where `lstm_use_prev_action_reward = True`.

**Comment by ericl** [comment]
Hmm wouldn't you never see a prev_done since the episode?

If it's some special thing from the env you can put it in the observation space (use a Dict or Tuple space).

**Comment by alversafa** [comment]
I was thinking for a setting where you chain multiple episodes to form a trial.

How would we use a dict? I wrapped the environment so that it returns an observation dict of the form `{'obs': ..., 'done': ...}`, however, I don't seem to be getting it on the forward method of the model?

**Comment by alversafa** [comment]
I was thinking for a setting where you chain multiple episodes to form a trial.

How would we use a dict? I wrapped the environment so that it returns an observation dict of the form {'obs': ..., 'done': ...}, however, I don't seem to be getting it on the forward method of the model?

**Comment by alversafa** [comment]
Made it possible by putting it in the observation vector.
