### ISSUE TITLE
[rllib]: SAC fails with MultiAgentEnv and "normalize_actions" set to True (default)?

### ISSUE THREAD

**Issue by yannbouteiller** [ray-project/ray#7173]
Hello,

I am having the following issue when letting the "normalize_actions" of SAC to True and using a subclass of MultiAgentEnv:

> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-b623dc3951e1> in <module>
>       1 # rllib trainer:
> ----> 2 trainer = agents.sac.SACTrainer(env="my_multiagent_env", config=config)
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py in __init__(self, config, env, logger_creator)
>      81 
>      82         def __init__(self, config=None, env=None, logger_creator=None):
> ---> 83             Trainer.__init__(self, config, env, logger_creator)
>      84 
>      85         def _init(self, config, env_creator):
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py in __init__(self, config, env, logger_creator)
>     395             logger_creator = default_logger_creator
>     396 
> --> 397         Trainable.__init__(self, config, logger_creator)
>     398 
>     399     @classmethod
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/tune/trainable.py in __init__(self, config, logger_creator)
>     170 
>     171         start_time = time.time()
> --> 172         self._setup(copy.deepcopy(self.config))
>     173         setup_time = time.time() - start_time
>     174         if setup_time > SETUP_TIME_THRESHOLD:
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py in _setup(self, config)
>     526 
>     527         with get_scope():
> --> 528             self._init(self.config, self.env_creator)
>     529 
>     530             # Evaluation related
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py in _init(self, config, env_creator)
>     100             else:
>     101                 self.workers = self._make_workers(env_creator, policy, config,
> --> 102                                                   self.config["num_workers"])
>     103             if make_policy_optimizer:
>     104                 self.optimizer = make_policy_optimizer(self.workers, config)
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/agents/trainer.py in _make_workers(self, env_creator, policy, config, num_workers)
>     571             config,
>     572             num_workers=num_workers,
> --> 573             logdir=self.logdir)
>     574 
>     575     @DeveloperAPI
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py in __init__(self, env_creator, policy, trainer_config, num_workers, logdir, _setup)
>      58             # Always create a local worker
>      59             self._local_worker = self._make_worker(
> ---> 60                 RolloutWorker, env_creator, policy, 0, self._local_config)
>      61 
>      62             # Create a number of remote workers
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py in _make_worker(self, cls, env_creator, policy, worker_index, config)
>     214             seed=(config["seed"] + worker_index)
>     215             if config["seed"] is not None else None,
> --> 216             _fake_sampler=config.get("_fake_sampler", False))
> 
> ~/anaconda3/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py in __init__(self, env_creator, policy, policy_mapping_fn, policies_to_train, tf_session_creator, batch_steps, batch_mode, episode_horizon, preprocessor_pref, sample_async, compress_observations, num_envs, observation_filter, clip_rewards, clip_actions, env_config, model_config, policy_config, worker_index, monitor_path, log_dir, log_level, callbacks, input_creator, input_evaluation, output_creator, remote_worker_envs, remote_env_batch_wait_ms, soft_horizon, no_done_at_end, seed, _fake_sampler)
>     366                         self.policy_map) +
>     367                     "{} is not a subclass of BaseEnv, MultiAgentEnv or "
> --> 368                     "ExternalMultiAgentEnv?".format(self.env))
>     369 
>     370         self.filters = {
> 
> ValueError: Have multiple policies {'policy1': <ray.rllib.policy.tf_policy_template.SACTFPolicy object at 0x7f5104319320>}, but the env <NormalizeActionWrapper<environments.rllib_multiagent_compatibility_wrapper.RllibMultiAgentEnv object at 0x7f51042f0fd0>> is not a subclass of BaseEnv, MultiAgentEnv or ExternalMultiAgentEnv?
> 

When I set "normalize_actions" to False, this issue disappears.
I am not sure whether this is a bug or if I am doing something wrong?

Ray version: 0.8.1

Regards,
Yann

**Comment by ericl** [comment]
It looks like NormalizeActions does not support multi-agent (this needs a better error message).

**Comment by Guoth** [comment]
hey, I can't use NormalizeAction in the MultiAgentEnv,too. I tried to add it to the MultiAgentEnv, but failed.  have you fixed it? @yannbouteiller

**Comment by yannbouteiller** [comment]
> hey, I can't use NormalizeAction in the MultiAgentEnv,too. I tried to add it to the MultiAgentEnv, but failed. have you fixed it? @yannbouteiller

No sorry, I didn't retry since.

**Comment by mimoralea** [comment]
Same issue. Solved it by overriding the `__class__` method to return the rllib `MultiAgentEnv` class, like so:

```
import gym
from ray.rllib.env.multi_agent_env import MultiAgentEnv


class MyActionWrapper(gym.ActionWrapper):

    def __init__(self, env):
        super().__init__(env)

    def action(self, action):
        return action

    @property
    def __class__(self):
        return MultiAgentEnv
```
