### ISSUE TITLE
Numpy arrays are mutable in object store in ray >=0.8

### ISSUE THREAD

**Issue by betelguez** [ray-project/ray#7174]
My first ever github post and hopefully I am doing this right...

### System information
OS Platform: Linux RHEL7
Ray installed from binary
Ray version: 0.8.x onwards
Python version: 3.7.4
Exact command to reproduce: See example below.

### Describe the problem
Numpy arrays (and pandas dataframes) were immutable in 0.7.6, as described in the documentation. Any modification to a numpy array fetched with ray.get would result in error (`"ValueError: assignment destination is read-only"`). In 0.8 (tested 0.8.1 and 0.9.0 dev), remote numpy arrays are no longer immutable.

### Example

``` python
import ray
import numpy as np
ray.init("auto")  #  initialize as necessary in your local install

x = np.full((2, 2), 1.)
o = ray.put(x)
y = ray.get(o)
y[0, 0] = 9.
# no error

print(ray.get(o))

```
prints
[[9. 1.]
 [1. 1.]]

expected
[[1. 1.]
 [1. 1.]]

**Comment by suquark** [comment]
This could be related to the new serializer we are using. I am going to fix it.
