### ISSUE TITLE
[rllib] GPU memory leak until out of memory when using local_mode with ray in pytorch PPO

### ISSUE THREAD

**Issue by pmacalpine** [ray-project/ray#7182]
### What is the problem?
When running pytorch PPO with `ray.init(local_mode=True)` rllib steadily uses up all the GPU memory due to what appears to be a memory leak (the attached log shows a constant linear increase in vram usage until it nears 100% and eventually runs out of memory) when training on atari (breakout).  The CPU memory leak in #6962 is also still present, but in this case is much slower than the GPU memory leak.  Note that I don't see the GPU memory leak if I don't run ray with local_mode=True in which case GPU memory usage is constant.  I also don't see this GPU memory leak with tensorflow when I run ray with local_mode=True.

![vram](https://user-images.githubusercontent.com/7802157/74600766-e780c780-504a-11ea-8a96-8a9fe83c5ec4.PNG)

*Ray version and other system information (Python version, TensorFlow version, OS):*
python: 3.7.6
ray: 0.9.0.dev0
OS: Ubuntu 18.04.03 LTS
torch: 1.3.0
tensorflow: 2.0.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
In the attached files I added a command line argument for local mode to train.py which is needed when running the following command to recreate the problem:
`python train.py --ray-local-mode true -v -f atari-ppo-pt.yaml`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).
[attachments.tar.gz](https://github.com/ray-project/ray/files/4209431/attachments.tar.gz)

**Comment by sven1977** [comment]
Thanks for opening this! This is the same issue as #6962 . We are currently working on a fix. I will close this one.
