### ISSUE TITLE
ERROR: No matching distribution found for ray

### ISSUE THREAD

**Issue by zfavourite99** [ray-project/ray#7183]
### ERROR: No matching distribution found for ray?
Python version: 3.8.1
OS: Ubuntu 18.04 TLS

**Comment by CavalloneChen** [comment]
> ### ERROR: No matching distribution found for ray?
> Python version: 3.8.1
> OS: Ubuntu 18.04 TLS

Seems that ray is not yet compatible with py3.8. Downgrading to py3.7 will resolve this issue.

**Comment by edoakes** [comment]
@CavalloneChen is correct
