### ISSUE TITLE
[autoscaler] Slim down docker images

### ISSUE THREAD

**Issue by holdenk** [ray-project/ray#7187]
### Describe your feature request

The ray images are larger than they need to be, for example, we include apt cache information which we probably don't need most of the time.

**Comment by richardliaw** [comment]
These are great suggestions! BTW @holdenk would you be willing to join the ray slack? I can send you an invite; we'll be able to communicate faster there.

**Comment by simon-mo** [comment]
@wuisawesome might be interested in doing this?

**Comment by wuisawesome** [comment]
Yeah, this sounds like a good idea. Keeping images small will eventually be useful for improving how quickly the autoscaler can spin up new workers.

**Comment by wuisawesome** [comment]
I can try to do this some at some point, but if someone beats me to it, there's a easy things that siginificantly decrease vm/container size. 

(Taken from https://github.com/Berkeley-CS162/vagrant) 
``That can be done by running sudo apt clean, sudo dd if=/dev/zero of=/EMPTY bs=1M, and sudo rm -f /EMPTY inside the VM. You may also choose to clear the history with history -c (and clear the .bash_history if it is present). ``

**Comment by whiletruelearn** [comment]
anyone working on this ?  Chaining some commands in 
https://github.com/ray-project/ray/blob/master/docker/autoscaler/Dockerfile
could reduce the size maybe

**Comment by wuisawesome** [comment]
I don't think anyone is working on it. Do you want to give it a shot/submit a PR?

**Comment by whiletruelearn** [comment]
Looks like a PR has been started already. I will find another issue to contribute .

**Comment by ramanNarasimhan77** [comment]
@whiletruelearn @wuisawesome 
I have chained RUN commands wherever possible and also removed apt, pip caches. 
Docker image size for the autoscaler after the change is 5.11GB, before the change it was 6.74GB

Please review PR #8683 and also guide me on the next steps

**Comment by ramanNarasimhan77** [comment]
There are some test failures on PR #8683, I am not sure if the changes to the Dockerfiles caused these failures.

**Comment by ramanNarasimhan77** [comment]
Thanks @simon-mo for reviewing and merging the PR. Glad that I could help.
