### ISSUE TITLE
Question about nested actors resource allocation

### ISSUE THREAD

**Issue by hkvision** [ray-project/ray#7195]
### What is your question?

[updated]

Hi, 

I'm under the following scenario to use ray for parallelism:
I have created several ray actors, say each actor is on one node and occupies some resources on this node. In each actor, I am creating several nested actors (or remote functions) to perform tasks. The outer actor would collect results returned by inner actors followed by its own tasks.
Want to ask the following questions:
- From my experiments, inner actors are placed randomly on any node in the cluster. In the case where there are enough remaining resources on every node, would it have better performance if inner actors are placed on the same node with the outer actor that creates them to avoid data transfer across different nodes?
- Seems inner and outer actors don't share resources. Am I doing wrong or is there a better way to achieve that the inner actors use the resources of the outer actor if the outer actor is doing nothing else at that time?
Thanks so much for the help in advance!

**Comment by richardliaw** [comment]
You should use something like placement groups for this (colocation, and having a concept of "grouped resources").
