### ISSUE TITLE
Authentication to Ray workers and TLS on connections

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#720]
I am not sure if this is already there, but I have not noticed anything in documentation.

I wonder if I have Ray workers on public IPs, does this mean that anyone can connect to them? Maybe there should be some way to authenticate connections? Maybe just a shared symmetric key?

And are connections encrypted?

**Comment by robertnishihara** [comment]
So, you can't connect to Ray *worker* processes, but certain processes can be connected to (mostly the redis servers but also the plasma manager). The connections are not encrypted.

It's possible to configure Redis to require clients to authenticate with a password.

Right now there aren't any security guarantees if you're running it on publicly accessible machines.

**Comment by mitar** [comment]
I think we will just use private overlay network and encrypt communication there. Probably using Docker Swarm.

But maybe this should be documented/noted somewhere.

**Comment by robertnishihara** [comment]
Closing for now. Please reopen if there are more questions here.
