### ISSUE TITLE
[rllib] I am running a PPO trainer with horizon=15000 for an environment that will run "forever", i.e. it should always terminate due to hitting the horizon, i.e. episode_length = horizon. By visualizing in Tensorboard, it however looks like episode _length < horizon after some time, see screenshot. How can this happen?

### ISSUE THREAD

**Issue by vivecalindahlericsson** [ray-project/ray#7208]
### What is your question?

I am running a PPO trainer with `horizon=15000` for an environment that will run "forever", i.e. it should always terminate due to hitting the horizon, i.e. `episode_length = horizon`. By visualizing in Tensorboard, it however looks like  `episode _length < horizon` after some time, see screenshot. How can this happen?

<img width="353" alt="Screenshot 2020-02-18 at 22 12 02" src="https://user-images.githubusercontent.com/56680529/74778451-e4304a80-529b-11ea-88e9-ca8f31c3c111.png">

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray v 0.8.0

Thanks.

**Comment by ericl** [comment]
You might be running with batch_mode: truncate_episodes. Try batch_mode: complete_episodes?

**Comment by vivecalindahlericsson** [comment]
Thanks, that's a good hint!

**Comment by vivecalindahlericsson** [comment]
I'm having problems understanding how truncating episodes affects the measured episode length. My (maybe unusual) case is: PPO, using defaults `train_batch_size=4000`, sample_batch_size=200, `truncate_episode=True`,  horizon=150000, `num_workers=2`. 

I  understand that each training iteration will work on truncated episodes. But the environment is not `reset` due to the truncation AFAICT, so why/how does truncation affect the episode length? (steps in between resets).

**Comment by sven1977** [comment]
That's correct. Running with `truncated_episodes` (e.g. = 10) should not reset episodes always after 10ts. It's just saying that the samples sent to the learner are all 10ts long (in case of PPO: with value-estimates at the end or 0 if an actual `done` is encountered, which is not the case in your endless env).
Not sure. Did you test the env separately to see how it behaves? Maybe it does return `done` after some time.
Could you try to reproduce this issue using our `rllib/exampes/random_env::RandomEnv` (set p_done=0.0 in the config)?

**Comment by vivecalindahlericsson** [comment]
Thanks for putting me on the right track. Indeed, my simulator was ending prematurely due to running low on resources!
