### ISSUE TITLE
[rllib] Impala with V-Trace evaluation

### ISSUE THREAD

**Issue by lychanl** [ray-project/ray#7212]
Is it possible to run evaluation when using Impala with V-Trace?

From what I found in code, evaluation worker's config has `batch_mode` set to `complete_episodes` which makes v-trace config validation fail on assertion `config["batch_mode"] == "truncate_episodes"`.

Here is the full config that I used:
```
{
    'timesteps_per_iteration': 1000,
    'evaluation_num_episodes': 1, 
    'evaluation_interval': 1, 
    'evaluation_config': {
        'exploration_fraction': 0, 
        'evaluation_num_workers': 0, 
        'evaluation_num_episodes': 1, 
        'batch_mode': 'truncate_episodes', 
        'horizon': inf, 
        'sample_batch_size': 1, 
        'collect_metrics_timeout': inf
    },
    'train_batch_size': 32,
    'decay': 0.99,
    'grad_clip': 40.0,
    'opt_type': 'rmsprop',
    'lr': 0.0006,
    'lr_schedule': [[0.0006, 0], [10000, 0]],
    'entropy_coeff': 0.01,
    'momentum': 0.0,
    'epsilon': 0.01, 'vf_loss_coeff': 0.5,
    'num_workers': 24, 
    'min_iter_time_s': 0, 
    'batch_mode': 'truncate_episodes', 
}
```

for the `SpaceInvaders-v0` environment

**Comment by ericl** [comment]
I think what we can do is disable that check in VTrace policy if in evaluation mode. The experiences won't be usable for training, but that is probably fine.

**Comment by ericl** [comment]
Try https://github.com/ray-project/ray/pull/7217/files ?

**Comment by lychanl** [comment]
This fix works fine, thanks
