### ISSUE TITLE
The issue of "ModuleNotFoundError: No module named 'tensorflow'" in Use Actors for Parallel Models

### ISSUE THREAD

**Issue by wangqipeng** [ray-project/ray#7223]
hi，guys：
i deploy a cluster based two machines. then i try to run the following code which is a example provide by the "Best Practices: Ray with Tensorflow"：

    import os
    import sys
    import ray
    import numpy as np

    ray.init(address="10.27.1.29:6379")

    def create_keras_model():
        from tensorflow import keras
        from tensorflow.keras import layers
        model = keras.Sequential()
        #Adds a densely-connected layer with 64 units to the model:
        model.add(layers.Dense(64, activation="relu", input_shape=(32, )))
        #Add another:
        model.add(layers.Dense(64, activation="relu"))
        #Add a softmax layer with 10 output units:
        model.add(layers.Dense(10, activation="softmax"))

    model.compile(
        optimizer=keras.optimizers.RMSprop(0.01),
        loss=keras.losses.categorical_crossentropy,
        metrics=[keras.metrics.categorical_accuracy])
    return model

    def random_one_hot_labels(shape):
        n, n_class = shape
        classes = np.random.randint(0, n_class, n)
        labels = np.zeros((n, n_class))
        labels[np.arange(n), classes] = 1
       return labels

     @ray.remote
     class Network(object): 
       def __init__(self):
            self.model = create_keras_model()
            self.dataset = np.random.random((1000, 32))
            self.labels = random_one_hot_labels((1000, 10))

       def train(self):
           history = self.model.fit(self.dataset, self.labels, verbose=False)
           return history.history

       def get_weights(self):
           return self.model.get_weights()

       def set_weights(self, weights):
            #Note that for simplicity this does not handle the optimizer state.
            self.model.set_weights(weights)

    NetworkActor = Network.remote()
    result_object_id = NetworkActor.train.remote()
    ray.get(result_object_id)

but， i got the following error:

Traceback (most recent call last):
  File "tf.py", line 64, in <module>
    ray.get(result_object_id)
  File "/home/wangqipeng1/project/test/ray/ray-master/python/ray/worker.py", line 1522, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ModuleNotFoundError): ray::Network.__init__() (pid=33428, ip=10.27.1.29)
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 445, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 447, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 425, in ray._raylet.execute_task.function_executor
  File "tf.py", line 44, in __init__
  File "tf.py", line 13, in create_keras_model
ModuleNotFoundError: No module named 'tensorflow'

the address : 10.27.1.29 is the ip of remote machine which had installed tensorflow. So how to solve this problem?

**Comment by richardliaw** [comment]
Should be solved by #14019
