### ISSUE TITLE
[docs] Question on `rllib-algorithms.rst`

### ISSUE THREAD

**Issue by vishalshar** [ray-project/ray#7236]
# Documentation Problem/Question/Comment

I am trying to reduce "episodes_per_iteration" for DDQ algorithm but it seems to be default at 250. I tried playing with "sample_batch_size", "train_batch_size", "target_network_update_freq" but I am not sure not to set "episodes_per_iteration". Can someone please help ?

(Created directly from the docs)

**Comment by drozzy** [comment]
> I am trying to reduce "episodes_per_iteration" ... but I am not sure not to set "episodes_per_iteration"

Not sure what you're trying to accomplish?

**Comment by vishalshar** [comment]
I am trying to change "episodes_per_iteration" for DDQ algorithm which is default set to 250. I want to change it to say 10. I do not see that config parameter in the config params. Can you please help how to do it ?

**Comment by drozzy** [comment]
I see this:
```
 # Minimum env steps to optimize for per train call. This value does
    # not affect learning, only the length of iterations.
    "timesteps_per_iteration": 1000,
```

here:

https://ray.readthedocs.io/en/latest/rllib-algorithms.html#deep-q-networks-dqn-rainbow-parametric-dqn

**Comment by vishalshar** [comment]
You are a life saver
