### ISSUE TITLE
Simple Demo?

### ISSUE THREAD

**Issue by jzf2101** [ray-project/ray#724]
@robertnishihara The tutorial and examples, while detailed, don't neatly tie together using ray into a single end-to-end example for a cluster.  It may help users to see how all the parts fit together in a simple toy demo for running ray on multiple machines, like a multi-cpu AWS instance, using one of the ML examples.

**Comment by robertnishihara** [comment]
Thanks for the suggestion! Would documenting how to run the example applications on a multi-node cluster help? Or did you have something else in mind?

**Comment by jzf2101** [comment]
Yes that would be helpful @robertnishihara .  The examples are clear but how to set up the machines to run them isn't clear.  While the documentation for running clusters could be improved, code examples often explain better.

**Comment by robertnishihara** [comment]
Closing since this is slightly out of scope for now. We would like to provide more scripts/utilities (e.g., along the lines of the spark-ec2 script https://github.com/amplab/spark-ec2) for starting up clusters. But we can track those separately.
