### ISSUE TITLE
[RLlib] A2C torch has a memory leak.

### ISSUE THREAD

**Issue by sven1977** [ray-project/ray#7244]
A2C torch has a memory leak, reproducible by:
```
rllib train --run A2C --env SpaceInvadersNoFrameskip-v4 --torch --config '{"num_gpus": 1, "num_workers": 15}'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
rllib train --run A2C --env SpaceInvadersNoFrameskip-v4 --torch --config '{"num_gpus": 1, "num_workers": 15}'
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by sven1977** [comment]
The leak is less severe than it was before we fixed PPO (and A2C to some extend) here (Issue #6962).

**Comment by avnishn** [comment]
@sven1977 can we close this issue?

**Comment by avnishn** [comment]
I don't seem to remember us discussing this anytime recently, so I'm going to close it, but please reopen if necessary.
