### ISSUE TITLE
[doc][docs] Broken Links

### ISSUE THREAD

**Issue by hubcity** [ray-project/ray#7246]
There are some broken links in your documentation.  These are mostly due to the facts that you changed the way that some files are named (multiagent to multi_agent) and some external websites have rearranged things.

I will submit a pull request soon.

**Comment by hubcity** [comment]
If the PR above is accepted there are still two broken links in doc/source/rllib-offline.rst that reference specific lines of code in  https://github.com/ray-project/ray/blob/b8a9e3f1064c6f8d754884fd9c75e0b2f88df4d6 - a blob that no longer exists.  I didn't know the proper way to fix it.

**Comment by richardliaw** [comment]
Thanks for this PR; sorry for taking so long to get around to it.

**Comment by richardliaw** [comment]
RE: missing reference, one fix would just be to remove it.
