### ISSUE TITLE
[rllib] multiagent example fails on 'explore' error

### ISSUE THREAD

**Issue by hubcity** [ray-project/ray#7270]
### What is the problem?
From the current nightly, running `ray/rllib/examples/rock_paper_scissors_multiagent.py` results in a 'Trials did not complete' error message:

```
    ray/rllib/utils/exploration/stochastic_sampling.py:79 _get_tf_exploration_action_op
        if explore:
    tensorflow/python/framework/ops.py:690 __bool__
        raise TypeError("Using a tf.Tensor as a Python bool is not allowed. "

    TypeError: Using a tf.Tensor as a Python bool is not allowed. Use if t is not None: instead of if t: to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray - nightly https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
python - 3.6.9
tensorflow - 1.14.0
OS - Ubuntu 18.04.4

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by ericl** [comment]
Oops, looks like we forgot to add this to the tests. cc @sven1977

**Comment by hubcity** [comment]
I don't believe this error is specific to the multiagent example.  You would see the same thing any time that 'explore' is not included in your trainer config or if it is set to None.

**Comment by ericl** [comment]
I think this may be specific to TF 1.14 -- I have 2.0 and it seems to work there. We are supporting 1.14, so this should probably be fixed.

@sven1977 this looks like it could be a bug in the `tf_function` impl.

**Comment by sven1977** [comment]
Yes, looks like a tf version issue. ...

**Comment by sven1977** [comment]
Hmm, it also works fine on py3.6 tf1.14.0 on MacOS. But I do remember seeing this on Travis sometimes (after which I fixed it so tests would pass). Are you sure you are on the latest master branch? I'm adding this example script to our tf1.14 suite, see what'll happen.

**Comment by sven1977** [comment]
`StochasticSampling` is not using `tf_function` anymore exactly because of this error. We are back to using tf.cond everywhere with specific checks on whether `explore` is a python bool or not.

**Comment by sven1977** [comment]
Running fine in Travis under Linux as well:
https://travis-ci.com/ray-project/ray/builds/150870030

**Comment by hubcity** [comment]
Thanks for checking.  I downloaded the latest from https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl and it works!

I could have sworn that I was using the latest when I filed this, but evidently not.  Thanks again.

**Comment by sven1977** [comment]
Doesn't happen in Travis Linux either. With tf1.14:
https://travis-ci.com/ray-project/ray/jobs/291864685
`//rllib:examples/rock_paper_scissors_multiagent                          PASSED in 20.2s`

**Comment by sven1977** [comment]
Ah, just saw your comment. Thanks for checking. No problem at all :)
