### ISSUE TITLE
 assert issubclass(model_cls, TFModelV2) when trying to use pytorch model

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7279]
I'm trying to use a custom model (pytorch [visionnet](https://github.com/ray-project/ray/blob/60d4d5e1aaa9fde3cf541ee335e284d05e75679c/rllib/models/torch/visionnet.py)) for a DQN policy.

When I try this:
```
ModelCatalog.register_custom_model("my_model", VisionNetwork)
register_env("zzz", env_creator)

tune.run(DQNTrainer, 
		config={"env": "zzz", 
		"model": {
			"custom_model": "my_model",
			"dim": 150,
			"conv_filters": [[16, [4, 4], 2], [32, [4, 4], 2], [32, [4, 4], 2], [32, [4, 4], 2], 
			[512, [10, 10], 1]]
		
      }
	})
```

I get this errror:
<pre>assert issubclass(model_cls, TFModelV2), model_cls
AssertionError: &lt;class &apos;my_model_pytorch.VisionNetwork&apos;&gt;
</pre>

**Comment by ericl** [comment]
I guess this will get fixed once DQN supports torch. cc @sven1977

**Comment by drozzy** [comment]
Closing, as I'm seeing pytorch slowy emerging as part of rllib.
