### ISSUE TITLE
[docs] "Feature Compatibility Matrix" should be easier to find

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7281]
I always want to click on "RLlib Algorithms" when I'm looking for "Feature Compatibility Matrix".

Does anyone else have this problem?

I think the "Feature Compatibility Matrix" warrants its own menu entry - or maybe it should be moved to the "Algorithms" section (with a link to it from "environments" section)?

**Comment by ericl** [comment]
This is a good idea, I often have to search for it too. Do you want to make a PR to move it?

**Comment by drozzy** [comment]
This is good to me now!
