### ISSUE TITLE
[ray] Make memory units explicit

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7282]
_I was commenting on #7099, but I thought this might make a nice wholesome issue._

It is really hard to read the docs and understand memory units without explit units.
Maybe we can use something like [bitmath](https://github.com/tbielawa/bitmath):

```
from bitmath import GB, MB
 @ray.remote(
      memory = GB(2),
      object_store_memory = MB(200)
...

```
This will make all of the code self-documenting.

The documentation and code make it really hard to know if units are in Bits/bits, bytes, kb, or megabytes... especially for object store, which seems like it should be huge (200000000) but in reality is only 200MB.

That's why I like standard lib/reference like this that new users can refer to:
https://bitmath.readthedocs.io/en/latest/classes.html

when they see:

`MB(200)`

they immeidately know that is (or can go to the referenced library to look it up).

There is even an argparse integration:

`ray start --head --redis-port=6379 --object-store-memory=200MB`

as:

```
import bitmath
parser = argparse.ArgumentParser()
parser.add_argument('--object-store-memory',
                    type=bitmath.integrations.BitmathType,
                    required=True)

results = parser.parse_args()
print(f"Parsed: {results.object_store_memory}")

> Parsed: 200.0 MB
```

**Comment by edoakes** [comment]
@drozzy I think this is a good idea but I'm wary of introducing a separate package as part of the API. Maybe we could support both byte integers or human-readable strings and then parse them in the backend (possibly using `bitmath`)?

If this solution sounds good to you, would you be interested in working on a PR for it? :)

**Comment by drozzy** [comment]
> wary of introducing a separate package

Yeah, that is a valid concern. I am not so convinced my idea is worth doing either... so I think I'll hold off.
Perhaps simply adding a comment to the code or docs that "this unit is in MB" or something along those lines would be much better.

**Comment by drozzy** [comment]
Closing for now.
