### ISSUE TITLE
[rllib] PPO torch super slow again as OMP_NUM_THREADS not being set to 1

### ISSUE THREAD

**Issue by pmacalpine** [ray-project/ray#7287]
### What is the problem?

Seeing the same exact slowdown problem again as in #6962 (but not the memory leak reported in that bug).  The same fix works again by setting OMP_NUM_THREADS=1.  This issue was originally fixed by setting OMP_NUM_THREADS=1 by default in #7006, but now it looks like #7254 removed the fix so that the bug is back.

It would be great if there were a regression test to catch this bug so it doesn't accidentally reappear again.

*Ray version and other system information (Python version, TensorFlow version, OS):*
See #6962

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
See #6962

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by ericl** [comment]
Thanks. Reverting, and added a test so it doesn't happen again.
