### ISSUE TITLE
Multiple Agents with different RL algorithms 

### ISSUE THREAD

**Issue by Degiorgio** [ray-project/ray#7289]
In RLlib Is is it possible to have multiple agents with different RL algorithms? For instance, one agent who behaves   according to a  reactive policy learned by DQN an other agent that behaviors   according to a policy learned by PPO

If so, can you point me to basic example of this setup? Thank you!

**Comment by ericl** [comment]
There's a basic example of this here: https://github.com/ray-project/ray/blob/master/rllib/examples/multi_agent_two_trainers.py

However, it requires alternating training. We're working on making it easier to compose real concurrent training with different agents, but this won't be for a couple releases.

**Comment by Degiorgio** [comment]
Great example, thanks @ericl !

**Comment by ericl** [comment]
It's because they are using two different trainers in different processes that don't weight share, so they have to be independently updated and synced.

**Comment by Degiorgio** [comment]
@ericl one more thing, is it possible to use tune with this setup (i.e. with multiple agents and different RL algorithms)?

**Comment by ericl** [comment]
You can try using the tune function API: https://ray.readthedocs.io/en/latest/tune-usage.html#tune-function-based-api
