### ISSUE TITLE
enable ray.list capability

### ISSUE THREAD

**Issue by hokiegeek2** [ray-project/ray#7297]
### Describe your feature request
In analogy to pyarrow PlasmaClient.list, I recommend adding a ray.list capability. 

I am am running Ray in head mode, submitting jobs in async (non-blocking) mode, and periodically checking to see if there are any Ray jobs that have completed. I've implemented a list-like capability by storing the ObjectIDs returned from Ray upon job submission in Redis. I periodically pass the list of ObjectIDs in Redis to Ray.get and pull the objects from Ray that are analytic job results. Would prefer to have list be added to the Ray client API so that I am not doing this two-step process.

**Comment by rkooo567** [comment]
Could you elaborate how it is different from `ray.wait()`?

**Comment by hokiegeek2** [comment]
@rkooo567 because ray.wait blocks. I submit the job to Ray and then another process checks periodically if there are any completed jobs.

**Comment by pengzhenghao** [comment]
You can set timeout to a very small number in `ray.wait(object_ids, num_returns=1, timeout=None)`. So that `ray.wait` does not block anything.

**Comment by richardliaw** [comment]
Yeah, ray.wait(timeout=some_tiny_number) should work here.

**Comment by hokiegeek2** [comment]
@richardliaw sounds good, thank you!
