### ISSUE TITLE
[tune] HParams Dashboard shows no data when using Histogram Dashboard.

### ISSUE THREAD

**Issue by Hailey-Liu** [ray-project/ray#7300]
### What is your question?

HParams dashboard shows no data when using Histogram dashboard.
![Screen Shot 2020-02-24 at 3 57 51 PM](https://user-images.githubusercontent.com/44219935/75191208-e6712980-571f-11ea-9349-f918e1a6f79b.png)

![Screen Shot 2020-02-24 at 3 57 33 PM](https://user-images.githubusercontent.com/44219935/75191225-ee30ce00-571f-11ea-9cd9-e0c765db0ef9.png)

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.9.0.dev0
Python version: 3.7.5
TensorFlow version: 2.1.0

### Reproduction
I modified the [mnist_pytorch_trainable.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mnist_pytorch_trainable.py) to log model parameters to tensorboad. 

Modification as follow:
```
def _train(self):
        train(self.model, self.optimizer, self.train_loader)
        acc = test(self.model, self.test_loader)
        result = {"mean_accuracy": acc}
        for tag, value in self.model.named_parameters():
                    tag = tag.replace('.', '/')
                    result[tag] = value.data.cpu().tolist()
        return result
```

If I removed the modification, the HParams dashboard is back to normal.
![Screen Shot 2020-02-24 at 4 12 08 PM](https://user-images.githubusercontent.com/44219935/75191712-ddcd2300-5720-11ea-8ab4-d0600b61f007.png)

Am I doing in the wrong way?

**Comment by richardliaw** [comment]
Made a PR to fix - thanks for the bug report.
