### ISSUE TITLE
[tune] would like a replay capability for particular PBT trace

### ISSUE THREAD

**Issue by utke1** [ray-project/ray#7307]
When I run PBT I have in the end a collection of hyper parameter traces, one of which I may want to declare the winner.
I understand that everything is “logged” so I can inspect that to find that info.
It isn’t obvious to us if there is already a facility in tune by which I can extract and ‘replay’ just the winner’s trace as a single training run.  
This would be useful for reproducibility without having to manually extract the trace or eat the cost of redoing the entire PBT run.

**Comment by krfricke** [comment]
We added a replay utility in #9953
