### ISSUE TITLE
[tune] PBT hyperparam_mutations does not allow for nested dicts any more

### ISSUE THREAD

**Issue by timonbimon** [ray-project/ray#7313]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2

Just recently a new check that hyperparam_mutations are either a list or a callable was introduced. (https://github.com/ray-project/ray/blob/master/python/ray/tune/schedulers/pbt.py#L182) 

Unfortunately the configs I use with my Experiments are nested dicts and I can now no longer use PBT to tune parameters in those nested dicts. 

Is there a reason that nested dicts are no longer allowed? :(

**Comment by richardliaw** [comment]
Ah, sorry that is a regression. Let me push a patch..

**Comment by timonbimon** [comment]
Awesome, thanks! Can you make a quick bug fix release for this or do we have to wait another month for the next normal release? :)

**Comment by ujvl** [comment]
@timonbimon you can use the nightly wheels https://ray.readthedocs.io/en/latest/installation.html#latest-snapshots-nightlies
