### ISSUE TITLE
Why Are Rewards only Reported Upon Episode Termination? [tune][rllib]

### ISSUE THREAD

**Issue by RaedShabbir** [ray-project/ray#7319]
### What is your question?
When running PPO with Ray Tune on a custom gym environment episode rewards remain NaN until the episode terminates. This has the effect of raising multiple numpy divides by zero warnings as the reporter tries to calculate reward but ends up dividing zero as there are no rewards. Is there a way to have rewards reported throughout the episode to eliminate these errors and allow for better tensorboard logging.

**Comment by ericl** [comment]
This isn't possible, since the reward may only occur at the end. In this case, reporting intermediate rewards would misleadingly give zero, which may be much higher or lower than the true episode reward.

**Comment by mcrowson** [comment]
Having the same experience. Is it normal that trial lengths would be shorter than episode lengths? Should I be having smaller episodes or longer trials for PPO?
