### ISSUE TITLE
What Java function must return for Tune

### ISSUE THREAD

**Issue by pranasblk** [ray-project/ray#7331]
Can one explain what Java function must return to be useful for hyper parameters optimisation via Tune?

Thanks!

**Comment by richardliaw** [comment]
Tune is currently only available for Python... feel free to contribute a Java version.

**Comment by pcmoritz** [comment]
It might be possible to get something up and running with https://github.com/ray-project/ray/pull/6709 but it would be pretty experimental for now. Maybe @fyrestone can say more?

**Comment by pranasblk** [comment]
My pro Python is zero level. Is there some kind of Redis schema description
for storing results of algo parameters and metrics?
I would be more than happy to contribute in Java code base.

Thanks!

**Comment by pranasblk** [comment]
There's a link explaining Python returned data structure, but it's broken - https://github.com/ray-project/ray/blob/48e2adbc21ff08cdd8ba5bd07a20c804e804e1d8/doc/source/tune-usage.html#auto-filled-results

From https://github.com/ray-project/ray/blob/48e2adbc21ff08cdd8ba5bd07a20c804e804e1d8/doc/source/tune-usage.rst:
> Tune will run this function on a separate thread in a Ray actor process. Note that this API is not checkpointable, since the thread will never return control back to its caller. tune.track documentation can be [found here](https://github.com/ray-project/ray/blob/48e2adbc21ff08cdd8ba5bd07a20c804e804e1d8/doc/source/tune-usage.html#auto-filled-results).

**Comment by fyrestone** [comment]
I think we still have some work to let tune support Java trainable:

- `tune` accepts Python function or class as trainable, but not support remote function or actor as trainable.
- currently, only bytes can be passed across different languages. (I am working on cross language serialization now)
- Java does not have tune APIs, e.g. `tune.track.log`
