### ISSUE TITLE
[rllib]RLLib CPU Parallel Combined with Numerical Simulators

### ISSUE THREAD

**Issue by soloist96** [ray-project/ray#7369]
Hi, I am trying to use numerical simulators to provide observations and states. However, I can only access the numerical simulator output by post-processing the simulation files, which means that different folders need to be created during parallel. Does rllib have a mechanism to handle that? e.g., passing parallel seed to create subfolders for numerical simulations. Thank you!

**Comment by ericl** [comment]
The worker number can be retrieved with `env_config.worker_index`, does this help?

**Comment by soloist96** [comment]
Thank you Eric. That's very helpful. I also want to make sure if a single worker with a certain worker index runs all the way to the end of the trajectory (finite MDP).  Thank you!
