### ISSUE TITLE
PPO PyTorch Bool Multiply Float type Issue

### ISSUE THREAD

**Issue by jiarongqiu** [ray-project/ray#7370]
### What is the problem?
https://github.com/ray-project/ray/blob/3fc162f93c0ead3d9d53719795f2349f2bc85cef/rllib/agents/ppo/ppo_torch_policy.py#L118 This line assigns Bool type to the mask. 
And according to https://github.com/ray-project/ray/blob/3fc162f93c0ead3d9d53719795f2349f2bc85cef/rllib/agents/ppo/ppo_torch_policy.py#L79, mask times a float type when calculating the loss. This will cause 
```
expected device cuda:0 and dtype Float but got device cuda:0 and dtype Bool
```

**Comment by sven1977** [comment]
Thanks for filing this issue, @jiarongqiu !
This has been fixed. Could you try again with the latest master branch?

Here is the PR, where this was addressed: https://github.com/ray-project/ray/pull/7398

Please let me know, if it still doesn't work.

**Comment by jiarongqiu** [comment]
I just saw the latest released version is 9 days ago. Should I clone the repo and do pip install . inside the python folder? I am a little confused about the lib setup procedure.

**Comment by ericl** [comment]
See here for how to install the latest snapshot: https://ray.readthedocs.io/en/latest/installation.html

**Comment by sven1977** [comment]
I'm closing this issue.
