### ISSUE TITLE
[rllib] Thread lock for Environment

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#7375]
### What is your question?
I have a simulator that reads a .dat file, performs the simulation based on the .dat file parameters, and returns an accuracy rating. I have currently got rllib training on this task by using the gym environment to interact with the simulator. The step() function takes an action, modifies the .dat file, runs the external simulator.exe, reads the output file from this simulator and uses the results to calculate a reward. 

This process appears to be working correctly, but the simulator.exe takes up to 30 seconds to run each iteration, making each episode quite long. I would like to speed this up using multiple workers, however this presents the issue of the read&write to the .dat file (multiple workers accessing the file at the same time). Is there a way to create a worker lock within the Environment class so that subsequent workers wait until the lock is released before attempting to read & write from the file?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6
Centos 7
TensorFlow 1.14

**Comment by richardliaw** [comment]
Yeah; why not use like:
```
from filelock import FileLock 

class CustomEnv():
... 
    def step(self, ...):
        with FileLock(os.path.expanduser("~/.sim.lock")):
            ...
```
