### ISSUE TITLE
Jupyter notebook web UI fails to import Ray

### ISSUE THREAD

**Issue by crystalzyan** [ray-project/ray#739]
When I tried to access the web UI on jupyter notebook, I was able to log in. However, running the first code block to initialize the web UI gets an import error.

<img width="931" alt="84 ray web ui import error" src="https://user-images.githubusercontent.com/10648572/28243222-023b5bc0-6977-11e7-9289-5d113470c752.png">

I think this is likely due to the fact that I have multiple versions of both Python and Anaconda installed on my system. Running python from the terminal is able to import Ray, however my jupyter uses a python from a different anaconda bin than the python I run from terminal, and is unable to import Ray.

<img width="401" alt="85 multiple anaconda bins" src="https://user-images.githubusercontent.com/10648572/28243245-e59f6c30-6977-11e7-8abf-895eed00e8c3.png">

It appears "most likely that the jupyter notebook is using a different version of Python for which ray has not been installed. We should fix this."

**Comment by robertnishihara** [comment]
Good catch!

I wonder what the best option is here. Perhaps we should make sure to start the jupyter notebook using the same version of Python that is being used to run Ray. Perhaps we could try

```python
import os
import sys

os.path.join(sys.exec_prefix, 'bin/jupyter')
```

though I'm not sure how robust that would be (would need to check that it works inside of virtual environments and things like that).

**Comment by robertnishihara** [comment]
Looks like this has been figured out.
