### ISSUE TITLE
Does DQN "rollout.py" have exploration turned off?

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7394]
When I call "rollout.py" I am not sure if exploration is turned off or not. I've looked over the file and can't seem to find `explore=False` anywhere.

So, when we evaluate trained policy (e.g. DQN) with rollout script - does it actually turn off random actions or not?

Thanks.

**Comment by ericl** [comment]
I don't think it's actually turned off by default right now.

**Comment by sven1977** [comment]
The default config for DQN for evaluation is `exploration=False` (greedy action selection).

**Comment by sven1977** [comment]
However, in rollout.py, we do not use the evaluation_config, which is something, we should probably change.

**Comment by sven1977** [comment]
Then again, rollout.py picks up an already trained DQN, so its timesteps should already be past the epsilon exploration period, which then means it's (almost) not exploring anymore (if `final_epsilon` is 0.0, it won't explore at all). So for your specific DQN case, it should be fine (as in: not picking random actions anymore). What's your `exploration_config`?

**Comment by sven1977** [comment]
The above PR makes sure that rollout.py always uses the evaluation_config (which for DQN, is explore=False).
In the meantime, you can add `--config '{"explore": false}'` to your rollout.py command line to make sure, your algo picks only greedy acitons.

**Comment by drozzy** [comment]
Awesome.
