### ISSUE TITLE
[rllib] TorchDiagGaussian doesn’t handle multiple actions correctly.

### ISSUE THREAD

**Issue by soundway** [ray-project/ray#7397]
This is not a contribution.

Ray version: 0.8.2
Python version: 3.6.8
Pytorch version: 1.4
OS: Ubuntu 18.04 Docker

TorchDiagGaussian doesn’t handle multiple actions correctly. As a result, training PPO with Pytorch will crash when the action space has more than 1 action. Here’s minimal reproduction script:

```python
import gym
from gym.spaces import Box
from ray import tune

class ContinuousEnv(gym.Env):
   def __init__(self, config):
       self.action_space = Box(0.0, 1.0, shape=(2,))
       self.observation_space = Box(0.0, 1.0, shape=(1, ))

   def reset(self):
       return [0.0]

   def step(self, action):
       return [0.0], 1.0, False, {}

tune.run(
   "PPO",
   config={"env": ContinuousEnv, "use_pytorch": True, "num_workers": 1})
```

**Comment by sven1977** [comment]
Thanks for filing this. Taking a look ...

**Comment by sven1977** [comment]
Please try this PR for a fix. This will go into master within the next few days.
https://github.com/ray-project/ray/pull/7398

**Comment by soundway** [comment]
This works. Thanks for the quick fix!

**Comment by omri-axon-vision** [comment]
Had the same problem, now the bug happens in the GAE calculation
  File "/home/spider-sense01/PycharmProjects/multi-agent-emergence-environments/.venv/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo_torch_policy.py", line 105, in __init__
    vf_loss_coeff * vf_loss - entropy_coeff * curr_entropy)
RuntimeError: The size of tensor a (512) must match the size of tensor b (2) at non-singleton dimension 1
