### ISSUE TITLE
[rllib] Unable to train SAC in custom gym MuJoCo environment

### ISSUE THREAD

**Issue by btjanaka** [ray-project/ray#7401]
# What is your question?

> **tl;dr What is the proper way to train SAC in a custom gym MuJoCo environment? I am running into an issue where SAC does not terminate or print its progress during training in a custom environment based on `Ant-v2`.**

When I train the default RLlib implementation of SAC in the `Ant-v2` environment for 1000 timesteps, I can see that it prints its progress to the console and terminates after 1000 timesteps, as expected. However, when I register a custom environment called `AntJump-v0` (which is intended to train the ant to jump) and try to train SAC in it for 1000 timesteps, it does not print its progress, and it does not terminate.

I have printed out the total timesteps from the step function of the `AntJump-v0` environment, so I can see that it is clearly being called, but the number of calls far exceeds 1000, and I end up having to interrupt the process to make it terminate. Below is the code to reproduce this.

I should also note a few other things I tried:
- When copying over the `AntEnv` environment from the `gym` repository (https://github.com/openai/gym/blob/master/gym/envs/mujoco/ant.py) and using it in place of `AntJumpEnv` (in the code below), the issue persists, even though this should be the same as `Ant-v2`. Does `rllib` do something "special" for the MuJoCo environments that come built-in with `gym`?
- I tried using the `AntJump-v0` with PPO (`ray.rllib.agents.ppo`) and it seems to work (for 1000 timesteps, at least). I see the progress output and termination. This may indicate that the problem is unique to SAC?

```
import argparse

from gym.envs.mujoco import AntEnv

import numpy as np

import ray
from ray import tune
from ray.tune.logger import pretty_print
from ray.tune.registry import register_env
import ray.rllib.agents.sac as sac

# Step counter for debugging AntJumpEnv
total_steps = 0


class AntJumpEnv(AntEnv):

    def step(self, a):
        # ====================================================================
        # Un-comment these lines, and We can see that the steps are clearly
        # increasing
        # ====================================================================

        #  global total_steps
        #  print("Steps:", total_steps)
        #  total_steps += 1

        # Still working on this part, but the specifics should not matter too much.
        self.do_simulation(a, self.frame_skip)
        height_reward = self.get_body_com("torso")[2]
        ctrl_cost = .5 * np.square(a).sum()
        contact_cost = 0.5 * 1e-3 * np.sum(
            np.square(np.clip(self.sim.data.cfrc_ext, -1, 1)))
        survive_reward = 1.0
        reward = height_reward - ctrl_cost - contact_cost + survive_reward
        state = self.state_vector()
        notdone = np.isfinite(state).all() \
            and state[2] >= 0.2 and state[2] <= 1.0
        done = not notdone
        ob = self._get_obs()
        return ob, reward, done, dict(reward_height=height_reward,
                                      reward_ctrl=-ctrl_cost,
                                      reward_contact=-contact_cost,
                                      reward_survive=survive_reward)


if __name__ == "__main__":
    register_env("AntJump-v0", lambda config: AntJumpEnv())

    env_name = "AntJump-v0"
    total_steps = 1000

    tune.run(sac.SACTrainer,
             stop={"timesteps_total": total_steps},
             config={
                 "env": env_name,
                 "num_workers": 3,
             })
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
```
ray==0.8.1
python==3.7.1
gym==0.15.6
numpy==1.18.1
tensorflow==2.1.0
```

**Comment by sven1977** [comment]
Could you try this PR? It makes sure that SAC uses the same evaluation settings as all other Trainers by default. Also, if your env does never terminate (which is the case for your env!), there is a warning that explains what to change.
https://github.com/ray-project/ray/pull/7448

**Comment by btjanaka** [comment]
Hi Sven, I tried adding termination by using the `TimeLimit` wrapper from `gym` (https://github.com/openai/gym/blob/master/gym/wrappers/time_limit.py), and everything seemed to work. Would you still like me to try the PR?

Thanks for your help!

**Comment by sven1977** [comment]
Hey @btjanaka , no that's fine, thanks for your help!
Most importantly, terminating (at some point) fixed the issue for you. Our PR above is already merged anyway.
Closing this issue.
