### ISSUE TITLE
"restore" deletes the restored from checkpoint

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7412]
If I specify a checkpoint in the `tune.run(DQNTrainer, restore=X)` - the checkpoint `X` gets deleted!

So if there is a bug or something during the initialization, I loose my checkpoint and can no longer restart from it!

**Comment by lennardsnoeks** [comment]
When I restore from a checkpoint in the following way, the checkpoint is not deleted for me:
`tune.run("DDPG", restore=checkpoint_path)`

I'm on ray v0.8.2 and tensorflow 2.0.0

**Comment by drozzy** [comment]
Hm... are you setting check-pointing to be done during this trial? E.g.:
```

tune.run(DQNTrainer, 
   restore=checkpoint,
   checkpoint_freq=5, checkpoint_at_end=True, checkpoint_score_attr='episode_reward_mean', keep_checkpoints_num=10)
```

Because when I restore it starts a new trial and starts saving checkpoints in a different trial directory (under `~/ray_results`), but for some reason it deletes the last checkpoint from the old directory.

**Comment by richardliaw** [comment]
cc @ujvl

**Comment by ujvl** [comment]
@drozzy thanks for flagging this, will push a fix this weekend.
