### ISSUE TITLE
how to fix listen ip of raylet

### ISSUE THREAD

**Issue by guyue5** [ray-project/ray#7418]
Now, raylet port is all 0 listening. I want to fix the ip, but I cannot find a way.

### What is your question?
![image](https://user-images.githubusercontent.com/42839519/75774107-2e302a80-5d8a-11ea-9e54-faeba977146b.png)

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by edoakes** [comment]
Try setting `node_ip_address` in `ray start`

**Comment by guyue5** [comment]
I have tried it, but didn't work. node_ip_address seems to have nothing to do with this listening IP
