### ISSUE TITLE
[rllib] Using only offline data for training without defining any envs

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#7420]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
Python: 3.6
TF: 2.0
OS: macOS

I have defined a customized model and also policy. I want to use only offline data (real world problem that without a simulator or env) to train my policy. However, I cannot find a way to load the offline data to `train_batch`?

How can I set the customized training process function that I can feed the train_batch from the offline data to the model without a simulator or an environment?

**Comment by frozenxia** [comment]
I have encountered the same problem, does anybody have an idea ?

**Comment by gradpratik** [comment]
Any updates on this?

**Comment by felipeeeantunes** [comment]
In our use case we are using a dummy environment just to set the structure of action and state spaces:
```python
from ray.rllib.examples.env.random_env import RandomEnv

config = {
            "framework": "tf",
            "explore": False,
            "env_config":{
                "action_space": Discrete(12),
                "observation_space": Box(high=np.array([10000]*46), low=np.array([-10000]*46))
            }
        }

env = RandomEnv(config["env_config"])
```
