### ISSUE TITLE
[tune] ray.tune's interaction with pytorch device

### ISSUE THREAD

**Issue by daveboat** [ray-project/ray#7426]
Forgive me if this question has already been asked, but I don't understand how ```tune.run(..., resources_per_trial={'cpu'=#, 'gpu'=#})``` interacts with pytorch's device (cpu, cuda).

For example, what exactly is happening if I run the following example code (note ```resources_per_trial={'cpu': 2, 'gpu': 0}``` and and ```'use_gpu': True``` are passed to ```tune.run```):
```
import torch
from torch.optim import SGD
from ray import tune
from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test

def train_mnist(config):
    train_loader, test_loader = get_data_loaders()
    device = torch.device('cuda' if config.get('use_gpu') and torch.cuda.is_available() else 'cpu')
    model = ConvNet().to(device)
    optimizer = SGD(model.parameters(), lr=config["lr"], momentum=config['momentum'])
    for i in range(10):
        train(model, optimizer, train_loader, device)
        acc = test(model, test_loader, device)
        tune.track.log(mean_accuracy=acc)

analysis = tune.run(train_mnist, name='test_mnist',
                    config={'lr': tune.loguniform(0.001, 0.1),
                            'momentum': tune.uniform(0.1, 0.9), 'use_gpu': True},
                    resources_per_trial={'cpu': 2, 'gpu': 0},
                    verbose=1, num_samples=10)
```
The above code runs without any errors, and shows the model running on the GPU even though I didn't assign any GPU resources to ```tune.run```.

The inverse is also confusing: what happens if I set ```resources_per_trial={'cpu': 0, 'gpu': 1}``` and ```'use_gpu': False```? In this case, tune runs happily, but ```nvidia-smi``` shows that nothing is actually running on any GPUs. I'm confused about how ```tune``` is supposed to interact with the device that pytorch's tensors live on.

**Comment by richardliaw** [comment]
Ah I see why this is confusing.

`use_gpu` is just a user-level configuration parameter. `resources_per_trial={gpu...}` is actually used by Ray. 

In the example, you'll have to set `use_gpu` and `resources_per_trial` for it to work properly. A more clearer example would be to remove `config["use_gpu"]` completely and detect GPU presence on the worker at runtime.

Does that help? Also, feel free to push a PR if you have any suggestions for improving the examples.

**Comment by daveboat** [comment]
Ah, I understand how it works then. ```ray``` manipulates things under the hood so that , when an instance of ```train()``` is spawned, it has access to the CPU and GPU resources that ```ray``` assigns. So if I were to run the example with ```resources_per_trial={'cpu': 2, 'gpu': 0}```, then in ```train_mnist()```, ```torch.cuda.is_available()``` is False.

In that case, you're right that the whole ```config["use_gpu"]``` parameter is redundant and confusing in the examples.

**Comment by daveboat** [comment]
Also, this line:
https://github.com/ray-project/ray/blob/3a134c7224c7d66155097973e968a1a2f3c30186/python/ray/tune/examples/pbt_convnet_example.py#L135
should be ```best_checkpoint = max(analysis.get_trial_checkpoints_paths(best_trial, "mean_accuracy"), key=lambda trial: trial[1])```. Currently you're taking the max of a list of [string, float], which gives a meaningless string max index.

**Comment by richardliaw** [comment]
Ah thanks for that catch. Feel free to push a fix, but otherwise, I'll try to get to this soon.
