### ISSUE TITLE
[multiprocessing.Pool]  Documentation Error

### ISSUE THREAD

**Issue by roshmath** [ray-project/ray#7451]
*Ray 0.9.0.dev0

from ray.util.multiprocessing import _**Pool**_

def f(index):
    return index

pool = Pool()
for result in pool.map(f, range(100)):
    print(result)

This import statement will fail as the actual module is not named  _**Pool**_ but  _**pool**_

Also just wondering if converting a program with existing multiprocessing with this module will be as efficient as manually changing the program to conform to ray's documentation

**Comment by edoakes** [comment]
I don't think this is a bug (I just tried it locally and it works). `Pool` is a class that's exposed in `__all__` for `ray.util.multiprocessing`.

Not sure I understand your question exactly - are you asking if parallelizing your program with the `Pool` API will be as fast as using the underlying Ray API? Using the Ray API directly should be faster, but how much depends on the workload.

**Comment by roshmath** [comment]
Thanks for the quick reply! It looks like I unnecessarily went into `ray.util.multiprocessing.Pool` to import the Pool class when I should have just imported `ray.util.multiprocessing`! 

And yes, asking if parallelizing with the `Pool API `will be as fast as using the underlying `Ray API ` So something like resizing 100 GBs of multidimensional ndimages with `scipy.ndimage.interpolation.zoom` would benefit from writing this into `Ray API`?

Thanks again!

<img width="651" alt="Screen Shot 2020-03-04 at 1 56 42 PM" src="https://user-images.githubusercontent.com/26006140/75912964-0e4b4600-5e20-11ea-8376-723372dcf631.png">

**Comment by edoakes** [comment]
If each image is relatively large (e.g., MiBs), the extra overhead in the `Pool` library shouldn't make much of a difference.
