### ISSUE TITLE
Understanding `obs` field from the output file specified in the env `config`

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#7457]
I recently got help in try to log the value at each timstep for each episode here: https://github.com/ray-project/ray/issues/7353

I would like to associate these values with the actions and the observations however. In the output json file I can see the values of the action, but the obs entry is listed in some alphanumeric sequence. Is this some binary form of a numpy array? If so how would I parse it?

**Comment by ericl** [comment]
This is since it's compressed. You can either (1) specify "output_compress_columns": [] to disable compression, or use rllib.utils.compression.unpack() or rllib.offline.json_reader.JsonReader to read and decompress the data.

**Comment by acxz** [comment]
Thanks for the quick response, let me give these methods a try!

**Comment by acxz** [comment]
Got it to work! I have one quick question tho, are the episode IDs representative of when the episode was simulated, i.e. will larger episode IDs correspond to later iterations of the training process?

**Comment by acxz** [comment]
@ericl Sorry to ping u about this again, but was wondering if you have a quick answer (or link for futher reading) to my above quesition.

**Comment by ericl** [comment]
They are random: 
```
        self.episode_id = random.randrange(2e9)
```

**Comment by acxz** [comment]
ah sweet thx for the quick response as always!
