### ISSUE TITLE
[tune] tune_mnist_keras.py is confusing

### ISSUE THREAD

**Issue by letmaik** [ray-project/ray#7458]
I'm trying to understand https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/tune_mnist_keras.py.

If I understood tune correctly then a single `training_iteration` in this case would mean running a full training loop since that's what `model.fit` does. It is *not* an epoch or a batch, it is a full training run for a given model configuration. Correct?

If the unit of `training_iteration` here is a full training run, then why is the stop condition set to `"training_iteration": 5 if args.smoke_test else 300`? Wouldn't this train the same model configuration repeatedly many times? If so, why is that useful?

**Comment by richardliaw** [comment]
`training_iteration` this case should actually be 1 batch. This is the frequency set via `TuneReporterCallback`. 

It would probably make sense to expose that callback in this example. Let me know if you have any questions.

**Comment by letmaik** [comment]
I see, that wasn't quite obvious from the docs and examples. I got two more questions:

Why is the default frequency batch and not epoch? Is this just to report more frequently? Any downsides to that?

How is tune able to stop training early? Is it simply killing the worker process?

**Comment by richardliaw** [comment]
1. The default frequency is set just to report more frequently; though I would recommend you subclassing the callback for your own problem. The downside would be that you might have large variance in your batch.
2. Tune stops training early by killing the worker process. If you use the `trainable` class API, you'll be able to gracefully terminate.

**Comment by letmaik** [comment]
I see, makes sense. I'm just looking at https://github.com/ray-project/ray/blob/5ab395236ba97b66627e86de78ed10e24f9c41b8/python/ray/tune/tests/test_api.py#L824-L844

and was wondering why `"timesteps_total": 100` is defined. Wouldn't it stop/finish anyway after the `train` function returns (without forcefully killing the worker early)? Also, any reason why `timesteps_total` is used here instead of `training_iteration`?

**Comment by richardliaw** [comment]
"timesteps_this_iter" is a rllib-specific construct that we aggregate on internally. I think this test specifically evaluates that. 

Generally, you should be using `training_iteration`.
