### ISSUE TITLE
[rllib] Creating sparse_placeholder in TF

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#7463]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
Python: 3.6
TF: 2.0
OS: macOS

How can I set sparse_placeholder in rllib?

**Comment by sven1977** [comment]
Which algorithm are you using? And for which input (observation, hidden state, actions, prev_actions, etc..) would you want this placeholder?
If you override TFPolicy, you can pass in your own placeholders. Otherwise, all placeholders are created automatically (see rllib/policy/dynamic_tf_policy.py) and when creating a new Policy via `build_tf_policy()`.

**Comment by GoingMyWay** [comment]
@sven1977  I am using algorithms I proposed. The data is from our own customized environments. Yes, as you mentioned, I override the TFPolicy and passed our own placeholders.  The demo code is in this issue https://github.com/ray-project/ray/issues/7468

**Comment by GoingMyWay** [comment]
> Which algorithm are you using? And for which input (observation, hidden state, actions, prev_actions, etc..) would you want this placeholder?
> If you override TFPolicy, you can pass in your own placeholders. Otherwise, all placeholders are created automatically (see rllib/policy/dynamic_tf_policy.py) and when creating a new Policy via `build_tf_policy()`.

Dear, I found `postprocess_fn` for `Placeholder setup: postprocess_fn`, but it is also used to

> postprocess_fn (func): optional experience postprocessing function
            that takes the same args as Policy.postprocess_trajectory()

Now, I am very confused by `postprocess_fn` are there any working examples on customizing placeholders. I real-world problems, data is complex, sparse placeholders are necessary, and there are many inputs as the obs.

Thank you very much.
