### ISSUE TITLE
[rllib] Relationship between iterations and number of episodes played

### ISSUE THREAD

**Issue by Degiorgio** [ray-project/ray#7466]
I am training two agents in a multi-agent  environment (with different trainers, one using DQN an one using PPO), for both agents I am using the default configurations. I noticed that the number of episodes executed per iteration is different between these two algorithms. I am getting 4 episodes per iteration for DQN and 1 episode per iteration for PPO.    

My question is, what determines exactly how many episodes get 'played' per iteration? is this algorithm specific?  and is there anyway to control it? 

Note: by iterations here I mean:

```
  for i in range(ITERATIONS):
        # improve first policy
        trainer0.train()
        # improve second policy
        trainer1.train()  
        .... 
```

**Comment by sven1977** [comment]
It's the Trainer's default config settings. You probably won't be able to force the exact number of episodes per train iteration, if your env produces different episode lengths:

PPO's default:
sample_batch_size=200, batch_mode=truncate_episodes, training_batch_size=4000 -> workers collect batches of 200 ts (per worker), then the policy network gets updated using the 4000 last ts (in n minibatch-chunks of 128 (`sgd_minibatch_size`)).

DQN's default:
train_batch_size=32, sample_batch_size=4, timesteps_per_iteration=1000 -> workers collect chunks of 4 ts and add these to the replay buffer (of size `buffer_size` ts), then at each train call, at least 1000 ts are pulled altogether from the buffer (in batches of 32) to update the network.
