### ISSUE TITLE
[tune][rllib] _InactiveRpcError Deadline Exceeded

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#7467]
### What is your question?
I have VirtualBox running on Centos 7 and I am having trouble initializing Ray. After I run ray.init(), I get an _InactiveRpcError due to a Deadline Exceeded exception. What info should I provide in order to troubleshoot this error?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.2
redis 3.4.1
Python 3.6
Centos 7 on VirtualBox

**Comment by Leonolovich** [comment]
Running ray.init(local_mode=True) allows me to continue without errors to my tune.run() step, but I havent been able to resolve the Inactive Rcp Error. This is not ideal as I can only get one worker to perform training when using local_mode=True.

**Comment by richardliaw** [comment]
Can you please try again on the latest Ray version?

**Comment by Leonolovich** [comment]
That appears to have made the issue go away. For documentation, I was having the issue on version 0.8.2 or Ray and I no longer have the issue on version 0.8.4.

Thanks
