### ISSUE TITLE
[rllib]Resuming training with APE-X DDPG

### ISSUE THREAD

**Issue by Jimpachnet** [ray-project/ray#7472]
Hello,

I am training an DDPG agent using the APE-X implementation provided by rllib. The configs can be found here: (https://pastebin.com/z07UJvqb , https://pastebin.com/9vRU10WK). When reloading the agent using
`    experiment_name = env_name + "_APEX_" + t
    tune.run_experiments({
        experiment_name: {
...
            "restore": restore_path
        },
    })`

and even after implementing #7449 , the restarted training degenerates immediately and the performance drops to almost zero. This happens even if I fill the replay buffer using an absurdly high value for `learning_starts`. In my opinion, this "biased" replay buffer should not impede learning since the training remains stable when training the original agent for hours after reaching the optimal reward and thereby overwriting the replay buffer with the same "biased" samples after some time.
The attached image shows the drop in performance, the blue line marks the point at which the training started. The initial reward is skewed by `pure_exploration_steps`.

When setting the learning rate of the critic to 0, the learning remains stable and the policy can even improve slightly. By increasing the critic's lr, one can see how the training degenerates faster and faster. The training also degenerates when disabling target network updates. 

My question is if there are any internal processes or curricula implemented that I am not aware of that are not restored by a checkpoint.
Thank you in advance.

EDIT: When using Adadelta or GD instead of Adam, the training stalls in a similar fashion.

EDIT2: 

> When setting the learning rate of the critic to 0, the learning remains stable

It is also clearly visible that the calculated max_q and mean_q values collapse as soon as the training starts, even before the policy breaks.

![training](https://user-images.githubusercontent.com/6762456/76029248-64111280-5f34-11ea-8fa5-81f1cdb78299.png)

**Comment by ericl** [comment]
FWIW I think is a quite serious Ape-X bug in the most recent version: https://github.com/ray-project/ray/issues/7478

Not sure if it's related to this though. It may be worth trying 0.8.0/0.8.1 just in case.

**Comment by Jimpachnet** [comment]
Thank you for the fast reply, the problem also occurs with v 0.8.1.

**Comment by Jimpachnet** [comment]
The problem even remains when restoring every single `ReplayActor` in addition to implementing #7449 .

**Comment by ericl** [comment]
Note: may want to hold off until https://github.com/ray-project/ray/pull/8221 is merged, which swaps out the execution backend for Apex-DDPG.

**Comment by avnishn** [comment]
going to close this issue for now, as it is stale, and it needs a repro script.
