### ISSUE TITLE
[rllib] Ape-X explorations / rewards incorrectly calculated in 0.8.2

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#7478]
### What is the problem?

0.8.2 seems to have the following bug:
- All per-worker exploration epsilons are set to the same value, instead of being spread across a distribution of epsilons
- We report rewards from all workers instead of just the 1/3 of workers with the lowest epsilons.

Oddly, Ape-X still passed the regression test for Breakout training--- in fact, it did better (perhaps suspiciously better).

**Comment by ericl** [comment]
cc @sven1977

**Comment by richardliaw** [comment]
@ericl we can unpin this now right?

**Comment by ericl** [comment]
No, it's not fixed.
