### ISSUE TITLE
[doc]Official website document information error

### ISSUE THREAD

**Issue by GOnion** [ray-project/ray#7481]
In the official website tutorial, Under this directory ---Using Ray / AsyncIO / Concurrency for Actors / Async Actor,When introducing the 'max_concurrency' flag, in the sample code below it is 'max_concurreny', The 'max_concurreny' missing one letter

**Comment by edoakes** [comment]
@GOnion thanks for pointing this out! Do you want to make a PR to fix it?

**Comment by landcold7** [comment]
I added a PR to fix this issue, please take a look. @edoakes
