### ISSUE TITLE
[ray,tune] How to set different gpu resources in different gpu card

### ISSUE THREAD

**Issue by jamestszhim** [ray-project/ray#7486]
I have 2 gpu cards with different memory: 

- **cuda:0** has **8GB** memory and 
- **cuda:1** has **16GB** memory. 

Running a single job requires max. **4GB** memory. 

If I set the gpu resources per trial in <code>tune.run</code> to **0.25** on **cuda:1**, I can run 4 jobs in parallel. But the **0.25** gpu resources setting cannot be applied to **cuda:0**. Can I specify the different gpu split for different cuda devices in ray? Thanks.

**Comment by richardliaw** [comment]
If on the same node, you may want to start ray twice (`CUDA_VISIBLE_DEVICES=0 ray start --head` and then `CUDA_VISIBLE_DEVICES=1 ray start --address`) and assign them custom resources of 8GB and 16GB memory. See the docs for more information (search "custom resources").

More generally, this isn't actually a Tune problem but a Ray problem (of not being able to elegantly handle heterogeneous resources on a single node).

**Comment by richardliaw** [comment]
I'm going to pre-emptively close this issue for now, but please reopen if you run into any problems/have any questions!
