### ISSUE TITLE
[rllib] How to read the checkpoint saved by Ray without installing Ray?

### ISSUE THREAD

**Issue by codelast** [ray-project/ray#7489]
Hi everyone, I'm a newbie here and have a (maybe) simple question:

I got a **checkpoint** file(a DDPG model) saved by Ray trainer from someone else, and I want to read the checkpoint and export the network weight & bias in the checkpoint on a machine which **has no Ray installed**, then I can use the weight & bias to do inference by myself.

**I don't want to install Ray**, so can I still read the checkpoint to get weight & bias? How?
Example codes are better. 

Thank you so much !

**Comment by codelast** [comment]
After reading some very limited Ray src code, I found that Ray uses Python pickle to save the checkpoint:
```python
with open(checkpoint_path, "wb") as f:
    pickle.dump(checkpoint, f)
```

so I use pickle to read it back:
```python
import pickle

checkpoint = '/xxx/checkpoint-1'

with open(checkpoint, 'rb') as f:
    model = pickle.load(f)
    f.close()

print(model)
```

What I got is a long string which is mainly consist of hex values, e.g.
> {'worker': b'\x80\x03}q\x00(X\x07\x00\x00\x00filtersq\x01}q\x02X\x0e\x00\x00\x00default_policyq\x03cray.rllib.utils.filter\nNoFilter\nq\x04)\x81q\x05sX\x05\x00\x00\x00stateq\x06}q\x07h\x03]q\x08(}q\t(X"\x00\x00\x00default_policy/policy/dense/kernelq\ncnumpy.core.multiarray\n_reconstruct\nq\x0bcnumpy\nndarray\nq\x0cK\x00\x85q\rC\x01bq\x0e\x87q\x0fRq\x10

Can anyone tell me what's the problem? Thanks!

**Comment by hybug** [comment]
`trainer.get_policy().export_checkpoint()` OR `trainer.get_policy().export_model()` maybe can help you, the forward export ckpt files, the behind export pd files.

**Comment by littlesevenmo** [comment]
Hi, 

You are almost done! 

In your example, `model` is a `dict`. `worker` is one of its keys.

The value of `worker` is also a hex value. You can use `pickle.loads()` to get the text value.

For example, 
```
import pickle

checkpoint = '/xxx/checkpoint-1'

with open(checkpoint, 'rb') as f:
    model = pickle.load(f)
    f.close()

# print(model)

value = model["worker"]
weights=pickle.loads(value)

print(weights)
```
weights are all in `np.array`

if you do not want `.` in print result, you can use
```
np.set_printoptions(threshold=np.inf)
```

so your code should like this:
```
import pickle
import numpy as np

checkpoint = 'xxxx/checkpoint_1/checkpoint-1'  

with open(checkpoint, 'rb') as f:
    model = pickle.load(f)
    f.close()

value = model["worker"]
weights=pickle.loads(value)

np.set_printoptions(threshold=np.inf)
print(weights)
```
