### ISSUE TITLE
[rllib] model_config is not used for initializing a model in RolloutWorker

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#7491]
### What is the problem?

Question: model_config is not used for initializing a model in RolloutWorker

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
Python: 3.6
TF: 2.0
OS: macOS Catalina

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

In the docs,

> model_config (dict): Config to use when creating the policy model.

However, in the code of RolloutWorker, model_config is not used to create a policy model, but to create an env,

```
        if isinstance(self.env, MultiAgentEnv) or \
                isinstance(self.env, BaseEnv):

            def wrap(env):
                return env  # we can't auto-wrap these env types
        elif is_atari(self.env) and \
                not model_config.get("custom_preprocessor") and \
                preprocessor_pref == "deepmind":

            # Deepmind wrappers already handle all preprocessing
            self.preprocessing_enabled = False

            if clip_rewards is None:
                clip_rewards = True

            def wrap(env):
                env = wrap_deepmind(
                    env,
                    dim=model_config.get("dim"),
                    framestack=model_config.get("framestack"))
                if monitor_path:
                    from gym import wrappers
                    env = wrappers.Monitor(env, monitor_path, resume=True)
                return env
        else:

            def wrap(env):
                if monitor_path:
                    from gym import wrappers
                    env = wrappers.Monitor(env, monitor_path, resume=True)
                return env
```
And, it is never used to create a policy model.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

Instead, I think `policy_config` is used to create a model and other configs of the running settings,

![image](https://user-images.githubusercontent.com/9346460/76112222-c0e7f800-601c-11ea-926f-22ff603ffc62.png)

**Comment by ericl** [comment]
Policy config includes the model config, so you get can it there within the policy still.

**Comment by GoingMyWay** [comment]
> Policy config includes the model config, so you get can it there within the policy still.

Exactly, thank you very much.
