### ISSUE TITLE
[raysgd] Utility Function for dataloaders

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7495]
As a nice addition, we could provide a dataloader decorator over a function that returns a dataset. 

This would be useful for people who are starting from scratch and do not want to wrangle another dataloader by themselves.

```python
from ray.util.sgd.torch import wrap_dataloader, BATCH_SIZE # or TOTAL_BATCH

# In this decorator, batch_size can be left as None. If so,
# it will be overridden by (config[BATCH_SIZE] / num_workers)
@wrap_dataloader(batch_size=None, **data_loader_args) 
def data_creator(...):
    train_dataset = LinearDataset(2, 5, size=config.get("data_size", 1000))
    val_dataset = LinearDataset(2, 5, size=config.get("val_size", 400))
    return train_dataset, val_dataset

trainer = TorchTrainer(
    data_creator=data_creator,
    config={BATCH_SIZE: 128},
    num_workers=4, # or 64
)
trainer.train() 
    
```

cc @maximsmol

_Originally posted by @richardliaw in https://github.com/ray-project/ray/pull/7384_

**Comment by amogkam** [comment]
This doesn't seem relevant anymore with the new Ray SGD changes. Going to close this issue.
