### ISSUE TITLE
Support num_return_vals argument for actor methods.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#750]
Currently, we allow remote functions to return multiple object IDs using the following syntax.

```python
@ray.remote(num_return_vals=3)
def f():
    return 1, 2, 3
```

Then `f.remote()` returns

```
[ObjectID(071b78e52bbe1e2c14e89c823fa3662ba11ee264),
 ObjectID(041b78e52bbe1e2c14e89c823fa3662ba11ee264),
 ObjectID(051b78e52bbe1e2c14e89c823fa3662ba11ee264)]
```

However, there is no equivalent at the moment for actor methods, so actor methods always return a single object ID.

We should allow actor methods to return multiple object IDs. What should the syntax be (since we don't decorate the individual actor methods)? There are a couple options.

1. Add a decorator for actor methods that return multiple object IDs, e.g.,

    ```python
    @ray.remote
    class Foo(object):
        @ray.multiple_return_vals(3)
        def method(self):
            return 1, 2, 3
    ```

2. Make it an argument to the remote function invocation.

    ```python
    foo.method.remote(__ray_num_return_vals__=3)
    ```

**Comment by mitar** [comment]
I would go with decorator.

**Comment by robertnishihara** [comment]
One good point that was brought up in #856 by @suquark is that sometimes the number of return values is different for each method invocation. You could imagine allowing the number of return values to vary by doing something like

```python
@ray.remote
class Foo(object):
    def method(self, n):
        return n * (0,)

f = Foo.remote()

id1 = f.method.remote()

id1, id2 = f.method.remote(__ray_num_return_vals__=2)

id1, id2, id3 = f.method.remote(__ray_num_return_vals__=3)
```

I'm not a huge fan of that syntax.. maybe there's a better option.

**Comment by salsasepp** [comment]
I just stumbled over the lack of this feature, too. 
+1 for the decorator.

**Comment by robertnishihara** [comment]
Done by #1296. You can decorate an actor method with `ray.method(num_return_vals=3)`.
