### ISSUE TITLE
[rllib] Trial name hash is always 0

### ISSUE THREAD

**Issue by janblumenkamp** [ray-project/ray#7517]
### What is the problem?

This is only a minor cosmetic issue, but when running RLLib with tune, the checkpoints and parameters are stored in the `ray_result` directory with a different hash for each new trial to identify it. Since a few days, this hash is always 0, which makes identifying the trial difficult.

- Ray version 0.9.0.dev0 (latest wheel)
- TensorFlow version 2.1.0 (GPU)
- Python version 3.6.9
- Linux 5.3.0-28-generic 30~18.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### Reproduction (REQUIRED)
```
rllib train --run=PPO --env=CartPole-v0
```
Output:
```
[...]
== Status ==
Memory usage on this node: 10.2/62.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 3/32 CPUs, 0/1 GPUs, 0.0/32.52 GiB heap, 0.0/11.23 GiB objects
Result logdir: /home/jb2270/ray_results/default
Number of trials: 1 (1 RUNNING)
+-----------------------+----------+-------+
| Trial name            | status   | loc   |
|-----------------------+----------+-------|
| PPO_CartPole-v0_00000 | RUNNING  |       |
+-----------------------+----------+-------+

```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by janblumenkamp** [comment]
This was introduced in 1ea05a2c088419d9adf84dd14ed11a7cffc97499 through [this line](https://github.com/ray-project/ray/commit/1ea05a2c088419d9adf84dd14ed11a7cffc97499#diff-926f38437c1a69a0942c4a01ab280706R76).
@ericl what is the reason for that? It looks like something that was accidentally committed.

**Comment by richardliaw** [comment]
Hey @janblumenkamp, sorry for the late followup. Can you provide a screenshot for where this is annoying/nuisance? Is it on tensorboard or in your shell or somewhere else?

**Comment by janblumenkamp** [comment]
No problem, this is not urgent at all! :)
Currently, my workflow consists of plenty of trial and error. I start a trial, change something in my environment and if it actually runs without any problems I let it run for some time to get back to it later. Now for each time I started a trial, I will have a new directory containing the results of the trial in `ray_results`, right? How do I now quickly identify a certain trial? Previously I just copied the random trial hash from my shell (as seen in the initial message in this commit) in a text file for my own reference to get back to it later, but I can not do this anymore as each newly started trial id is identical (i.e. `PPO_CartPole-v0_00000`).

**Comment by ericl** [comment]
I agree this is an annoying problem. We could probably revert it to the random hash without too much effort--- it was changed to a deterministic counter for the sake of easier testing.

I've assigned the issue to myself.

**Comment by janblumenkamp** [comment]
Thanks for fixing this! What I originally hoped to be able to do though is knowing what is the corresponding directory from the id shown in the terminal (and correspondingly also corresponding experiment id in tensorboard). It looks like the random string shown in the trial name in the terminal has nothing to do with the actual folder name created.
For example, I start an experiment and in the terminal it is shown to me as `<algorithm>_<environment>_<random-string-a>_<experiment-index>` while the corresponding folder created is names `<algorithm>_<environment>_<experiment-index>_<date-time><random-string-b>`. I would like `random-string-a` and `random-string-b` to be identical, which is currently not the case.
