### ISSUE TITLE
[autoscaler] How to install docker within the setup yaml file?

### ISSUE THREAD

**Issue by preeth1** [ray-project/ray#7519]
I want to install docker and run my ray cluster on it. This is what my initialization commands look like:
```
initialization_commands: [
    "sudo apt update",
    "sudo apt install docker.io -y",
    "sudo usermod -a -G docker ubuntu",
    "sudo service docker restart",
    # Docker should be restarted here, but I do not know how
   "docker login -u $DOCKER_USER -p $DOCKER_PW",
]
```
Docker needs to be restarted, or `newgrp docker` has to be run, but I do not know how to do it in this context, because any command that does this like `newgrp` opens up a subshell and breaks the functionality here.

How do I do this?

Here is a stackoverflow question I posted to the same effect: https://stackoverflow.com/questions/60609535/how-to-install-and-use-docker-in-one-shell-script

**Comment by Servon-Lee** [comment]
Hi, @preeth1. Do you solve the problem?
