### ISSUE TITLE
[rllib] How to realize a group reward for distinct policies?

### ISSUE THREAD

**Issue by janblumenkamp** [ray-project/ray#7524]
### What is your question?

I have an environment with four agents and I want these four agents to work in two groups of two. In particular, I would like to learn four distinct policies for these four agents, but the reward of the agents of the two groups should be considered as a group and not individually. I understand that this is what the grouping feature is for. At the same time I am not sure how I would make sure that the agents of a group are able to learn different policies (I want the agents within a group to cooperate and not perform the same task).

For example, I have the four agents `a_0, a_1, b_0, b_1` and the group mapping
```
groups = {
    "a": ["a_0", "a_1"],
    "b": ["b_0", "b_1"]
}
```
With this grouping, I can now define the policies
```
# obs_space and act_space for a single agent
policies = {
    "policy_0": (Policy, spaces.Tuple((obs_space, obs_space)), spaces.Tuple((act_space, act_space)), {}),
    "policy_1": (Policy, spaces.Tuple((obs_space, obs_space)), spaces.Tuple((act_space, act_space)), {}),
}
policy_mapping_fn = lambda agent: {"a": "policy_0", "b": "policy_1"}[agent]
```
So obviously I would only learn two policies for the two teams, but the behaviour for all agents in the team would be similar, correct? How can I obtain different behaviours within the same team with both agents acting on the cumulative reward of the team? Or do I just have to hope that the collective team policy learns to differentiate between the team members and then performs different actions based on their states?

**Comment by ericl** [comment]
With the grouping config, you are learning two policies that each control two agents (i.e., centralized training / centralized execution). Each agent's output action is computed from a separate head of the policy, so the behavior should differ.

Another way of doing this is to have 4 separate policies, but give the team-mates a joint reward calculated in the environment to encourage cooperation (decentralized training, decentralized execution). With separate policies you may also want to add a centralized critic to improve learning (for centralized training, decentralized execution): https://ray.readthedocs.io/en/latest/rllib-env.html#implementing-a-centralized-critic

Hope this helps.

**Comment by janblumenkamp** [comment]
Thanks a lot, that definitely helped!
