### ISSUE TITLE
[tune][autoscaler] Why is the end-to-end duration for tune.run() significantly longer than the total time spent on trials?

### ISSUE THREAD

**Issue by dorcus01** [ray-project/ray#7535]
# What is the problem?
I ran the ray/python/ray/autoscaler/aws/example_full.yaml and tune_example.py script on AWS autoscaler, with a p3.2xlarge as head and no worker, specifying 1 gpu for each trial. Hence all the trials should be run in sequential. I have attached the screen shots of results in two scenarios, namely, tuning with 1 sample and tuning with 20 samples. You'll see that the end-to-end duration printed for tune.run() is significantly longer than the total time spent on the trials in both scenarios. Also, with an increasing number of samples for tuning, you will see a significant increase in the end-to-end duration. 
Where has the time gone within tune.run() spent apart from training and validation? If it's purely because of saving checkpoints, how to disable checkpoints for trials?

<img width="629" alt="Screenshot 2020-03-10 at 11 23 41" src="https://user-images.githubusercontent.com/61154565/76307916-a2565b00-62c1-11ea-9cff-ec2e96cac39a.png">
<img width="629" alt="Screenshot 2020-03-10 at 11 21 52" src="https://user-images.githubusercontent.com/61154565/76307822-73d88000-62c1-11ea-92e3-3459e260e661.png">
<img width="629" alt="Screenshot 2020-03-10 at 11 21 37" src="https://user-images.githubusercontent.com/61154565/76307844-7f2bab80-62c1-11ea-86bf-da7b6c9aa288.png">

*Ray version: ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
*Python version: python3.6
*Torch version: 1.4.0
*Cloud: AWS autoscaler

**Comment by richardliaw** [comment]
The main reason for this is because `total_time_s` only tracks the time spent _during training_. It may be more intuitive to track uptime instead of training time...
