### ISSUE TITLE
[tune][raysgd] Why is the multi-GPU tuning overall slower than the single-GPU?

### ISSUE THREAD

**Issue by dorcus01** [ray-project/ray#7536]
# What is your question?
I ran two tuning tests with AWS autoscaler:
* p3.2xlarge for head, no worker. Use 1 GPU for each trial.
* p3.8xlarge for head, no worker. Use 4 GPUs for each trial.
Both tests run 10 trials (samples), and each trial has 2 training iterations, each iteration trains on 3200 images and validates on 2 images. The batch_size fed to TorchTrainable(TorchRunner or DistributedTorchRunner) is 32*num_replicas. The two results are shown below.

**Why is the 4-GPU tuning (fig. 2) slower than the single-GPU (fig. 1) in terms of the end-to-end duration of tune.run(), although the time for each trial is a lot shorter?**

<img width="707" alt="Screenshot 2020-03-10 at 11 45 09" src="https://user-images.githubusercontent.com/61154565/76311343-aa65c900-62c8-11ea-849c-845888e5128b.png">
<img width="707" alt="Screenshot 2020-03-10 at 11 45 28" src="https://user-images.githubusercontent.com/61154565/76311348-ad60b980-62c8-11ea-8542-b6e730959d71.png">

# Environment
*Ray version:  ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
*Torch: 1.4.0
*Cloud: AWS autoscaler

# Run command
ray submit autoscaler-aws.yaml examples/tune_test.py --start --args="--address=localhost:6379 --num-replicas=1 --use-gpu"

ray submit autoscaler-aws.yaml examples/tune_test.py --start --args="--address=localhost:6379 --num-replicas=4 --use-gpu"

# Code (examples/tune_test.py)
```
import os
import time
import argparse
import numpy as np
import torch
import torch.nn as nn

import ray
from ray import tune
from ray.util.sgd.torch.torch_trainer import (TorchTrainer,TorchTrainable)
from torch.utils.data import Dataset
import torchvision.models as models

def initialization_hook():
    print("NCCL DEBUG SET")
    # Need this for avoiding a connection restart issue
    os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
    os.environ["NCCL_LL_THRESHOLD"] = "0"
    os.environ["NCCL_DEBUG"] = "INFO"

class RandomDataset(Dataset):

    def __init__(self,  length):
        self.len = length
        self.data = torch.randn(length, 3, 224, 224)
        self.target = torch.LongTensor(length).random_() % 1000

    def __getitem__(self, index):
        return self.data[index,:,:,:], self.target[index]

    def __len__(self):
        return self.len


def model_creator(config):
    return models.__dict__[config.get("model_name")](pretrained=False)


def optimizer_creator(model, config):
    """Returns optimizer."""
    return torch.optim.SGD(model.parameters(), lr=1e-2)


def data_creator(config):
    """Returns training dataloader, validation dataloader."""
    batch_size = config.get("batch_size")
    num_steps = config.get("num_steps")
    return RandomDataset(batch_size * num_steps), RandomDataset(2)

def tune_example(num_replicas=1, use_gpu=False, num_steps=100, batch_size=32, fp16=False, model_name='resnet34', test_mode=False):
    config = {
        "model_creator": model_creator,
        "data_creator": data_creator,
        "optimizer_creator": optimizer_creator,
        "loss_creator": lambda config: nn.CrossEntropyLoss(),
        #"train_function": train,
        #"validation_function": validate,
        "num_replicas": num_replicas,
        "initialization_hook": initialization_hook,
        "use_gpu": use_gpu,
        "batch_size": batch_size * num_replicas,
        "config": {
            "lr": tune.choice([1e-4, 3e-4, 1e-3, 5e-3, 1e-2, 5e-2]),
            "test_mode": test_mode,
            "model_name": model_name,
            "num_steps": num_steps,
            "batch_size": batch_size
        },
        "backend": "nccl" if use_gpu else "gloo"
    }

    analysis = tune.run(
        TorchTrainable,
        queue_trials=False,
        num_samples=10,
        config=config,
        stop={"training_iteration": 2},
        verbose=0,
        global_checkpoint_period=500)

    return analysis.get_best_config(metric="mean_accuracy", mode="max")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--address",
        required=False,
        type=str,
        help="the address to use for Ray")
    parser.add_argument(
        "--num-replicas",
        "-n",
        type=int,
        default=1,
        help="Sets number of replicas for training.")
    parser.add_argument(
        "--use-gpu",
        action="store_true",
        default=False,
        help="Enables GPU training")
    parser.add_argument(
        "--num-steps",
        type=int,
        default=100,
        help="Sets number of steps for training per iter.")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=32,
        help="Sets batch size for training per GPU.")
    parser.add_argument(
        "--fp16",
        action="store_true",
        default=False,
        help="Enables FP16 training with apex. Requires `use-gpu`.")
    parser.add_argument(
        "--model",
        type=str,
        default='resnet34',
        help="Sets model name.")  
    parser.add_argument(
        "--smoke-test",
        action="store_true",
        default=False,
        help="Finish quickly for testing.")

    args, _ = parser.parse_known_args()

    ray.init(address=args.address, log_to_driver=False)

    start = time.time()
    tune_example(
            num_replicas=args.num_replicas,
            use_gpu=args.use_gpu,
            num_steps=args.num_steps,
            batch_size=args.batch_size,
            fp16=args.fp16,
            model_name=args.model,
            test_mode=args.smoke_test)
    end = time.time() - start
    print("---- total time for tuning (s): ", end)
```

**Comment by richardliaw** [comment]
The reason for this is because the setup for the distributed job actually takes quite a long time (25 seconds). Obviously, if your training run takes 1 hour, this will not be an issue.

I'm working on a PR that exposes this profiling information; would you be interested in reviewing?

**Comment by dorcus01** [comment]
Sure, I'd be interested in reviewing the profiling info. Also, does the setup take this long for each trail in hyperparameter tuning?

**Comment by richardliaw** [comment]
well, setup for TorchTrainer can take quite a long time (30 seconds).

**Comment by dorcus01** [comment]
I've noticed that`DistributedDataParallel` is used in the way as Single-Process Multi-GPU where each process will operate on all the GPUs of the node, coded as `model = DistributedDataParallel(model)`.  Why not choose the more efficient way as Multi-Process Single-GPU where each of the process operates on a single GPU? Is it because the GPUs have not been allocated at this stage?

**Comment by richardliaw** [comment]
Each process operates on 1 GPU. The GPUs are isolated by CUDA_VISIBLE_DEVICES, which is set to 1 per worker process (in trainer.py, at `ray.remote(num_gpus=1)`).

**Comment by dorcus01** [comment]
I see. To get the ID of the GPU where the process is running, I can use ray.get_gpu_ids(), right?

**Comment by richardliaw** [comment]
Yep; on the actor (or TrainingOperator, depending on how much you've forked), you can call `ray.get_gpu_ids`.
