### ISSUE TITLE
[rllib] Use of multi agent environment degrades performance / obtained reward

### ISSUE THREAD

**Issue by lennardsnoeks** [ray-project/ray#7540]
### What is your question?
I mentioned this in issue #7422, but it wasn't really relevant to the question and my explanation wasn't the best, so I thought to open a new question.

My goal is to do crowd generation with a multi agent approach, for which I use one policy that all agents use (agents are homogeneous). I have created a single agent environment that controls one moving agent. When I test this environment in the following way, I get good results:

    config = ddpg_config.DDPG_CONFIG.copy()
    config["gamma"] = 0.95
    config["num_workers"] = 0
    config["num_gpus"] = 0
    config["eager"] = False
    config["exploration_should_anneal"] = True
    config["exploration_noise_type"] = "ou"
    config["observation_filter"] = "MeanStdFilter"
    config["clip_actions"] = True
    config["env_config"] = {
        "sim_state": sim_state
    }

    register_env("single_agent_env", lambda _: SingleAgentEnv(config["env_config"]))
    config["env"] = "single_agent_env"

    ray.init()
    stop = {
        "training_iteration": iterations
    }
    run("DDPG", checkpoint_freq=iterations, stop=stop, config=config)

![50_single](https://user-images.githubusercontent.com/17469736/76319705-e0fb0e00-62df-11ea-8710-a5d50cbdcf0f.png)

For the multi agent approach, the environment contains X amount of single agent environments for the amount of moving agents. 'sim_state" contains the agents, obstacles etc.. This object is passed to all agents as reference so they can know positions of other agents:

    class MultiAgentEnvironment(MultiAgentEnv):
    
        def __init__(self, env_config):
            self.sim_state: SimulationState = env_config["sim_state"]
            self.env_config = env_config
    
            self.load_agents()
    
        def load_agents(self):
            self.original_sim_state = copy.deepcopy(self.sim_state)
    
            self.agents = []
            for i in range(0, len(self.sim_state.agents)):
                self.env_config["agent_id"] = i
                self.agents.append(SingleAgentEnv(self.env_config))
    
        def step(self, action_dict):
            obs, rew, done, info = {}, {}, {}, {}
    
            for i, action in action_dict.items():
                obs[i], rew[i], done[i], info[i] = self.agents[i].step(action)
                if done[i]:
                    self.dones.add(i)
            done["__all__"] = len(self.dones) > 0
    
            return obs, rew, done, info
    
        def reset(self):
            self.resetted = True
            self.dones = set()
            self.sim_state = copy.deepcopy(self.original_sim_state)
    
            # redistribute shared state
            for agent in self.agents:
                agent.load_params(self.sim_state)
    
            return {i: a.reset() for i, a in enumerate(self.agents)}

Because I want to use curriculum learning, I tested the multi agent environment for 1 agent and the same test case as for the single agent environment in the following way:

    config = ddpg_config.DDPG_CONFIG.copy()
    config["gamma"] = 0.95
    config["num_workers"] = 0
    config["num_gpus"] = 0
    config["eager"] = False
    config["exploration_should_anneal"] = True
    config["schedule_max_timesteps"] = 100000
    config["exploration_noise_type"] = "ou"
    config["observation_filter"] = "MeanStdFilter"
    config["clip_actions"] = True
    config["env_config"] = {
        "sim_state": sim_state
    }

    env_config = config["env_config"]
    single_env = SingleAgentEnv(env_config)
    obs_space = single_env.get_observation_space()
    action_space = single_env.get_action_space()

    config["multiagent"] = {
        "policies": {
            "policy_0": (DDPGTFPolicy, obs_space, action_space, {"gamma": 0.95})
        },
        "policy_mapping_fn": lambda agent_id: "policy_0"
    }

    register_env("multi_agent_env", lambda _: MultiAgentEnvironment(config["env_config"]))
    config["env"] = "multi_agent_env"

    ray.init()
    stop = {
        "training_iteration": iterations
    }
    run("DDPG", checkpoint_freq=checkpoint_freq, stop=stop, config=config)

I expected similar results, but performance was way down, as can be seen:
![50_multi](https://user-images.githubusercontent.com/17469736/76319945-39caa680-62e0-11ea-8712-a89e718088ec.png)

Looking at episodes completed, for the single env we are at over 800, while the multi environment only completed 3.
![reward_comparison](https://user-images.githubusercontent.com/17469736/76320017-5535b180-62e0-11ea-856d-c2d6b35f9bc3.png)
![episodes_total](https://user-images.githubusercontent.com/17469736/76320023-56ff7500-62e0-11ea-994d-99688395e512.png)

I verified if everything happens correctly in the multi agent environment (reset, redistribute the shared state variable "sim_state", ...)

I expected similar behaviour but got big differences. What could this be caused by?  Related to exploration?  Is the declaration of the policy in the multiagent part of the config wrong, or is it not the same as with the DDPG trainer in a single agent approach?

_Ray version and other system information (Python version, TensorFlow version, OS):_
python v3.7.4
ray v0.8.2
tensorflow v2.0.0

**Comment by ericl** [comment]
I'm not able to reproduce this in a simpler setting:
```
import gym
from ray import tune
from ray.rllib.env import MultiAgentEnv

class MultiTest(MultiAgentEnv):
    def __init__(self, _):
        self.cartpole = gym.make("CartPole-v0")
        self.observation_space = self.cartpole.observation_space
        self.action_space = self.cartpole.action_space

    def reset(self):
        return {"agent1": self.cartpole.reset()}

    def step(self, actions):
        a = actions["agent1"]
        obs, rew, done, info = self.cartpole.step(a)
        return {"agent1": obs}, {"agent1": rew}, {"__all__": done}, {}


#tune.run("PPO", config={"env": MultiTest})
tune.run("PPO", config={"env": "CartPole-v0"})
```
![image](https://user-images.githubusercontent.com/14922/76362988-59150400-62df-11ea-806a-31bd23fa344b.png)

I would recommend starting with something simple that works and trying to narrow down the cause, which could be some specific config option or bug in the env.

**Comment by lennardsnoeks** [comment]
Was indeed an environment related bug, my apologies.

**Comment by ericl** [comment]
No problem :)

**Comment by jlin816** [comment]
Hi @lennardsnoeks! I'm running into the same issue actually — what was the environment bug you had? Wondering if I might be making the same mistake.
