### ISSUE TITLE
[rllib] Adding curiosity bonuses?

### ISSUE THREAD

**Issue by alversafa** [ray-project/ray#7549]
In the documentation it says that model-based curiosity bonuses can be added to the rewards: https://ray.readthedocs.io/en/latest/rllib-training.html#rewriting-trajectories

How do we define the `on_postprocess_traj` callback to achieve this? I guess we have to somehow add the model losses to the `pre_batch` rewards. But how do we do this?

(By adding curiosity bonuses, I am specifically talking about the following study: https://pathak22.github.io/noreward-rl/)

**Comment by ericl** [comment]
You can get a reference to the current rollout worker (including policies etc. and their models) via get_global_worker(): https://github.com/ray-project/ray/blob/master/rllib/evaluation/rollout_worker.py#L49

**Comment by alversafa** [comment]
Just to make sure, when we call `get_global_worker()`, is it turning back the worker who generated the specific trajectory that we have in `on_postprocess_traj`?

**Comment by alversafa** [comment]
By the way just noticed that `info['pre_batch']` returns a tuple where the first element is a policy and the second one is a dict that contains info about the trajectory.

Given that we already have access to the policy, is it necessary to call `get_global_worker()`?

**Comment by ericl** [comment]
> Just to make sure, when we call get_global_worker(), is it turning back the worker who generated the specific trajectory that we have in on_postprocess_traj?

Yep, the callback is run in the rollout worker that generated the experience, prior to the samples being returned to the learner. The reference to that worker is accessible via the global variable.

> Given that we already have access to the policy, is it necessary to call get_global_worker()?

Ah I guess not! I forgot we already included the policy in that field (guess the API needs some improvements for clarity here).

**Comment by alversafa** [comment]
Thanks for the clarification. I have implemented the following callback:

```
def on_postprocess_traj(info):
  curiosity_rews = info["pre_batch"][0].model.cur_loss
  info["pre_batch"][1]['rewards'] += curiosity_rews
```

However, I see no difference from the case that I don't use it. 

Am I missing something here?

**Comment by ericl** [comment]
Ah, you want post_batch. The pre batch is just there for reference but is
not actually used for learning.

**Comment by alversafa** [comment]
Even if I do it with the `post_batch` key, I still do not see any difference.

**Comment by ericl** [comment]
Even if you set it to zero there isn't any difference in learning?

Note that the episode_reward_mean metric is reported directly from the env and postprocessing will affect it.

**Comment by alversafa** [comment]
Surprisingly, yes, even if I do `info["post_batch"]['rewards'] *= 0.0` in `on_postprocess_traj`, there is no difference in learning.

**Comment by ericl** [comment]
I think this is since some algos like PPO have already computed the advantages by then, so reward is not used.

Instead of using a callback you can customize the PPO policy to use a custom postprocessor (override `postprocess_ppo_gae`). See https://ray.readthedocs.io/en/latest/rllib-concepts.html#extending-existing-policies

**Comment by alversafa** [comment]
> I think this is since some algos like PPO have already computed the advantages by then, so reward is not used.

Yes, probably. I am using PPO btw.

I did what you have suggested, however, I am puzzled from where I can get the numerical outputs of the model? That is, where can I obtain for instance the logit values of my model?

 (I am asking this as I am planning to return the curiosity rewards from the `forward()` of the model.)

**Comment by ericl** [comment]
Check out function passed fro `extra_action_fetches=` here: https://github.com/ray-project/ray/blob/master/rllib/agents/ppo/ppo_tf_policy.py#L161

Those keys show up in the batch, and if you add more entries they will show up too.

**Comment by alversafa** [comment]
I have managed to add the curiosity rewards. Thank you!

**Comment by maraoz** [comment]
@alversafa mind sharing the code that worked, if you don't mind? I'm very interested :)

**Comment by alversafa** [comment]
@maraoz I implemented it back then, however, I deleted that part of the code since I no longer needed it. I believe that you will be able to implement it if you follow this issue. @ericl's pointers were very useful.
