### ISSUE TITLE
Actor call latency

### ISSUE THREAD

**Issue by ConeyLiu** [ray-project/ray#7550]
### What is your question?

I have read the report http://anyscale.io/wp-content/uploads/2020/02/Edward-Oakes-Anyscale-RayMeetup-20200130-3.pdf. It's very amazing about the ray's latency and scaling. I have benchmarked locally with `ray microbenchmark`. The scaling results almost equally with the released notes. But I can't find any scripts about the latency benchmark scripts. I test it with the following code.
```python
@ray.remote
class LatencyActor:
    def __init__(self):
        import time
    
    def func():
         return time.time()


actor_handler = LatencyActor.remote()
start = time.time()
duration = ray.get(actor_handler.func.remote()) - start  # this needs 0.43 ms for local actor and 0.68 ms for remote actor

start = time.time()
ray.get(actor_handler.func.remote())
duration = time.time() - start  # this needs 0.7x ms for local actor and larger than 1ms for remote actor
```

The latency seems much larger than the report shows. So could someone tell me the measure methods about the actor call latency? 

*Ray version and other system information (Python version, TensorFlow version, OS):*

The ray version is 0.8.1. And the network is 10gb. OS `Linux 3.10.0-862.el7.x86_64`

**Comment by ConeyLiu** [comment]
cc @carsonwang

**Comment by ericl** [comment]
I believe this was the result of `TESTS_TO_RUN="1:1 actor calls sync" ray microbenchmark` on a machine with high CPU clock, which can give 4-5k calls per second. For example I got

```
1:1 actor calls sync per second 4345.6 +- 312.3
```

on my laptop.

**Comment by ConeyLiu** [comment]
thanks for the explanation.
