### ISSUE TITLE
Is there any idea to put ray and horovod working together?

### ISSUE THREAD

**Issue by firejq** [ray-project/ray#7552]
e.g.  Run ray on CPUs and run horovod on GPUs.  May this idea bring some benefits ?

**Comment by richardliaw** [comment]
Please take a look at https://github.com/ray-project/ray/blob/master/python/ray/util/sgd/torch/examples/benchmarks/README.rst#multi-node-results and let me know what you think.

**Comment by crypdick** [comment]
@richardliaw those examples were certainly helpful for launching clusters. What I still don't understand is how to make `ray.tune.run()` launch a Horovod trainer with different hyperparams (and get the results of `ray.tune.track.log()` back to the tuner).

Right now, I launch my Horovod script with `horovodrun -np 4 python train.py <args>`

**Comment by richardliaw** [comment]
Resolved offline on Slack - the suggestion is to use RaySGD instead. Thanks!
