### ISSUE TITLE
[rllib] How to decode weight matrix?

### ISSUE THREAD

**Issue by ZekiDorukErden** [ray-project/ray#7559]
Hello,

When try to look at the weights in a trained (PPO) policy by using Trainer.get_weights(), the return dictionary has one-dimensional arrays as weights for multi-layer networks. Is there any way to know how to map these 1-D arrays to weights (and biases) to specific layers, e.g. which indices are the weights connecting first layer to second, which are biases of first layer, etc.

I work on Google Colab.

**Comment by Rohan138** [comment]
Closing; `get_weights` now returns a dictionary with the required information.
