### ISSUE TITLE
[tune] passing batches of results to loggers

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#7562]
When the execution time of one train call is very small, we need to wrap multiple train calls into one `Trainable._train` to avoid overheads, which I think is often encountered. However, in such cases, we are only able to return the results of the last call, which are then logged in csv format or using tensorboardx. 

What if we want to log all results of these wrapped train calls? Towards this, some custom loggers need to be implemented, but it would be nice if tune supports this functionality natively.

**Comment by ujvl** [comment]
Hmm one way to do this might be to support returning a list (representing a batch of results), and log each result but only make scheduling/checkpointing decisions based on the last result.

cc @richardliaw
