### ISSUE TITLE
[rllib] PPO, Actor-Critic, where are models?

### ISSUE THREAD

**Issue by Degiorgio** [ray-project/ray#7571]
With regards to the PPO algorithm, when using the  default configurations (i.e with use_critic=True) where in the repository is the policy network defined? Similarly where is the network that is used to estimate the value baseline defined?

Also,  if use_critic=False, then would  it be correct to state that   PPO  will simply not use the value baseline when computing the advantage function?

**Comment by ericl** [comment]
Check out the value_function() definitions: https://github.com/ray-project/ray/search?q=%22def+value_function%22&unscoped_q=%22def+value_function%22

> Also, if use_critic=False, then would it be correct to state that PPO will simply not use the value baseline when computing the advantage function?

That's right.

**Comment by BFAnas** [comment]
Hello,
I want to set "actor_hiddens" a.k.a the hidden layers of the policy network of PPO, and be able to set their weights. Is this possible? If yes please tell me how?
Thanks.

**Comment by DZ9** [comment]
> Check out the value_function() definitions: https://github.com/ray-project/ray/search?q=%22def+value_function%22&unscoped_q=%22def+value_function%22
> 
> > Also, if use_critic=False, then would it be correct to state that PPO will simply not use the value baseline when computing the advantage function?
> 
> That's right.

so is this means if use_critic=False, the advantage is actually q value, which is computed like it in REINFORCE?

**Comment by DZ9** [comment]
or it means it would still compute q(s) = r(s)+v(s+1), but just not minus v(s)?

**Comment by jiahao-shen** [comment]
I have the same question, why we cannot set the model for PPO and A2C like this: `"actor_hiddens": [256]`
`"critic_hiddens": [256] `

**Comment by amadou1998** [comment]
I have been comming around the same issue. I used centralized critic A3C and by changing the critic network architecture with a centralized crititc I got dramatically better results than for parameter sharing. This would be a fine addittion to ray 2.3.0

**Comment by lyzyn** [comment]
> 我一直在遇到同样的问题。我使用了集中式 critic A3C，通过使用集中式 crititc 更改了 critic 网络架构，我得到了比参数共享更好的结果。这将是对 ray 2.3.0 的一个很好的补充

I happen to also want to use centralized critical. Do you need to set some options to True when using centralized critical? Is there anything similar to centralized_ A setting like cric=True? Or do I just need to write the custom network from the following website into the program? I have been troubled by this recently and look forward to your reply. Thank you!
https://github.com/ray-project/ray/blob/master/rllib/examples/centralized_critic.py#L242
