### ISSUE TITLE
[tune] HyperBand MaxSize and Milestone changing

### ISSUE THREAD

**Issue by semin-park** [ray-project/ray#7576]
### What is the problem?

Because of #7011, I tried downgrading ray to 0.8.0 and ran HyperBand again. (On 0.8.1 and 0.8.2 #7011 shows up) But now it seems like `Max Size` and `Milestone` are changing during the course of training for some reason. 

I ran [hyperband_example.py](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperband_example.py)
At the start of training, the log shows this. Notice the values on `Max Size` and `Milestone`.
```
== Status ==
Memory usage on this node: 123.7/251.6 GiB
Using HyperBand: num_stopped=0 total_brackets=3
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=100, completed=0.0%): {PENDING: 4, RUNNING: 1}
  Bracket(Max Size (n)=8, Milestone (r)=33, completed=0.0%): {PENDING: 8}
  Bracket(Max Size (n)=15, Milestone (r)=11, completed=0.0%): {PENDING: 7}
```

However, the next log that is shown at the end of training shows this:
```
== Status ==
Memory usage on this node: 122.0/251.6 GiB
Using HyperBand: num_stopped=10 total_brackets=3
Round #0:
  Bracket(Max Size (n)=5, Milestone (r)=100, completed=100.0%): {TERMINATED: 5}
  Bracket(Max Size (n)=3, Milestone (r)=67, completed=100.0%): {TERMINATED: 8}
  Bracket(Max Size (n)=2, Milestone (r)=67, completed=100.0%): {TERMINATED: 7}
```

Why did `Max Size` for the second and third bracket change from 8 to 3 and 15 to 2, respectively?
`Milestone` has changed from 33 and 11 to 67 as well. Why is that?

*Ray version and other system information (Python version, TensorFlow version, OS):*

**ray 0.8.0**
macOS 10.15.3
python 3.7

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperband_example.py

Run the above example.

- [x] I have verified my script runs in a clean environment and reproduces the issue.

**Comment by richardliaw** [comment]
BTW, can you try the latest master? I'm hoping this is fixed.

**Comment by richardliaw** [comment]
BTW, it's possible that the milestones are changing because the number of elements in the new bracket are less.
