### ISSUE TITLE
New pickle5 Error breaks examples

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7590]
#### Versions
- Latest ray on master
- numpy==1.16.3

Error:
```
╰─ python hyperband_example.py
Traceback (most recent call last):
  File "hyperband_example.py", line 10, in <module>
    import ray
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/__init__.py", line 12, in <module>
    raise ImportError("Ray must be imported before pickle5 because Ray "
ImportError: Ray must be imported before pickle5 because Ray requires a specific version of pickle5 (which is packaged along with Ray).
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run `python ray/python/ray/tune/examples/hyperband_examples.py`. 

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

cc @simon-mo

**Comment by simon-mo** [comment]
hmmm I can't reproduce this using:
- Python 3.7.6
- numpy==1.16.3
- latest master

**Comment by richardliaw** [comment]
What pickle5 version were you using? I uninstalled pickle5 and it seemed to work for me.

**Comment by simon-mo** [comment]
We actually bundle pickle5 i believe. 
https://github.com/ray-project/ray/blob/35a4bfc885dda3bd4bf9837d29d0012925d394c5/build.sh#L121-L130

**Comment by richardliaw** [comment]
I understand; but I'm saying I had a separate installation of pickle5 and removing it fixed my issue.

**Comment by simon-mo** [comment]
oh i see. I don't have a separate installation of pickle5 so it's whatever end up in the bundle.
