### ISSUE TITLE
It's about the evalution for policy during training. 

### ISSUE THREAD

**Issue by dxu23nc** [ray-project/ray#7599]
After each training iteration, Ray will report the mean_reward of the current policy. 
I want to ask: when evaluation, how did Ray get the mean_reward? 
Does it follow the following steps:
1. start multi new episodes.
2. Each episode uses the policy to get the right action to act.
3. When all the episodes reach the terminate state, sum all the rewards and get the mean reward.

Thanks in advance.

**Comment by ericl** [comment]
It goes more like this:
1. Continue episode rollouts (if in batch_mode: truncate_episodes).
2. Collect final rewards of any terminated episodes.
3. If there are less than `config.metrics_smoothing_episodes` rewards collected, add in episode metrics from the previous iteration until this number is met.
4. Compute the mean over those episodes.

**Comment by dxu23nc** [comment]
Thanks for your reply. 

So the mean reward actually depends on how many rollout workers that we started. Because more rollout workers, more accurate the mean reward will be.

**Comment by ericl** [comment]
That's right. I you require an accurate-in-time evaluation, I would recommend setting `evaluation_interval`: https://ray.readthedocs.io/en/latest/rllib-training.html#customized-evaluation-during-training

**Comment by dxu23nc** [comment]
Got it! 
Thanks

**Comment by dxu23nc** [comment]
Hi,
I just thought one thing.
To calculate the mean reward, rllib first collects the episode from the "already started" rollout workers. The transitions for (0, k) in the episode maybe not come from the "current policy" that we want to evaluate. This setting could have some important impact on the mean reward. Am I correct?

Thanks in advance.

**Comment by ericl** [comment]
That's right. If you want accurate evaluation you should use the evaluation API, otherwise the running mean will eventually converge to the expected reward.

**Comment by dxu23nc** [comment]
If i set:
`
"   evaluation_interval": 2,
    "evaluation_num_episodes": 10,
    "evaluation_config": {
        "explore":False,
    },
    "evaluation_num_workers":10,
`
then, every 2 iterations, rllib will evaluate the policy with 10 episodes (Here, I have 10 workers, so each worker will run one episode?)  Am I correct? 
And from the description from Train.py, 
`# Customize the evaluation method. This must be a function of signature
    # (trainer: Trainer, eval_workers: WorkerSet) -> metrics: dict. See the
    # Trainer._evaluate() method to see the default implementation. The
    # trainer guarantees all eval workers have the latest policy state before
    # this function is called.
    "custom_eval_function": None,
`
Where can I found an example of "custom_eval_function"?

Thanks in advance.

**Comment by ericl** [comment]
That's right. Note that you probably don't need that many workers unless
your episodes are super long.

Btw, check the docs for more examples:
https://ray.readthedocs.io/en/latest/rllib-training.html#customized-evaluation-during-training

**Comment by Arthur-Null** [comment]
I still have some doubts. So if I set batch_mode: complete_episodes and collected over "metrics_smoothing_episodes" episodes in this iteration. Then the mean is computed over all episodes collected in this iteration?

**Comment by gjoliver** [comment]
these parameters are deprecated. we should use evaluation_duration and evaluation_duration_unit to specify the kind of evaluation run we want.
the comments have a lot of info:
https://github.com/ray-project/ray/blob/858d607b195f12969776479439c4c6639d1cc12e/rllib/agents/trainer.py#L339-L351
