### ISSUE TITLE
[rllib] offline dataset example doesnt work ("NaN of Inf found in input tensor")

### ISSUE THREAD

**Issue by guyk1971** [ray-project/ray#7606]
### What is the problem?
Trying to run the 2 command lines in the offline dataset example : 
first to create the offline dataset (which completes successfully):
`rllib train  --run=PG --env=CartPole-v0 --config='{"output": "/tmp/cartpole-out",\ "output_max_file_size": 5000000}' --stop='{"timesteps_total": 100000}'`

and then : 
`rllib train --run=DQN --env=CartPole-v0 --config='{"input": "/tmp/cartpole-out",\
        "input_evaluation": [],"explore": false}'`

and this command runs but doesnt train because of a warning:
"WARNING:root:NaN or Inf found in input tensor."

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version : 0.9.0.dev0 (the latest wheel version)
python: 3.7.6
tensorflow 2.0.0
Ubuntu 18.04

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
no script. simply follow your example on offline dataset. as written above. 
I also tried to change the algorithm that generates the data to ppo and dqn. all behave the same.

If we cannot run your script, we cannot fix your issue.

- [v ] I have verified my script runs in a clean environment and reproduces the issue.
- [v ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by ericl** [comment]
The warning seems to be a red herring, it seems to be working when I tried it (in offline mode reward is always a NaN unless you have "simulation" included in "input_evaluation". You can try https://github.com/ray-project/ray/pull/7611/files which suppresses the warning.

**Comment by guyk1971** [comment]
Eric, thanks a lot for the prompt and effective response ! indeed, my bad for not reading the documentation carefully (maybe worth a note in the offline dataset documentation section about the exepected warning if not feeding 'simulation' mode) . 
BTW, I'm exploring rllib after trying other libraries (coach, tf-agents, baselines...) and it looks like great framework so far. keep up the great work ! (In the near term I'll be looking into batch rl and will try to implement the recent algorithms that was found effective for it like BCQ/ DBCQ). Thanks a lot for the help !!  
what's next ? should I close this issue ?

**Comment by ericl** [comment]
Yeah good point! I'll make sure to update that. Feel free to file any other issues that come up.

**Comment by Catypad** [comment]
´Hi @ericl! Why is the reward always NaN in an offline mode? Can you explain, please?
