### ISSUE TITLE
[tune] high overhead between train calls when running 4000 trials

### ISSUE THREAD

**Issue by llan-ml** [ray-project/ray#7608]
### What is the problem?

I have an experiment consisting of about 4000 trials to be run. With `ray==0.7.6` and `ray==0.8.2`, the time that tune internally costs between two consecutive train calls varies a lot, ranging from 0.x second to tens of seconds.

However, when I run the code with `ray==0.7.3`, the time cost is always smaller than 2 seconds (most of times smaller than 1 second).

Is there a recommended number of trials that we should have? In addition, I would suggest to add a new result entry that records the internal time tune takes between two train calls. Sometimes, it is confusing that users see `TIME_TOTAL_S` is a relatively small number but the trial runs slowly.

### Reproduction (REQUIRED)
For now, I still do not have a tiny script to report this.

**Comment by richardliaw** [comment]
For now, I would recommend something like order of hundreds of trials. Let me look into this issue though.

**Comment by richardliaw** [comment]
This should be fixed in the latest release.
