### ISSUE TITLE
Warning always printed when connecting to a running cluster

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#7647]
### What is the problem?

Every time I connect to a running cluster, the following warning is printed:
```
2020-03-18 11:03:07,711 WARNING worker.py:802 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

`ray start --head`

```python
import ray
ray.init(address="auto")
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by edoakes** [comment]
I `git bisect`ed this and it seems to have been introduced by https://github.com/ray-project/ray/pull/7410.

**Comment by maxiwelian** [comment]
Is this warning an issue or not? I am seeing the same thing.

**Comment by edoakes** [comment]
@maxiwelian this should not be an issue, it's just an overzealous warning. Will be removed soon when we refactor how we handle propagating the internal config (cc @rkooo567).

**Comment by wuisawesome** [comment]
Closing because this doesn't happen anymore.
