### ISSUE TITLE
[sgd] Fast Autoscaling

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7664]
### Describe your feature request

We should allow for ``TorchTrainer(num_workers=-1)`` to automatically use all available resources on the cluster. Further, when more resources are available, it should automatically resize the number of workers to claim those resources. 

To do this quickly, we need to:
1. not terminate the existing workers.
2. check resources when possible.
3. Make it so that we can somehow specify `resources_per_worker`.

**Comment by anabranch** [comment]
How does this interact with the autoscaler, as in if I say -1 will it try to spin up those new nodes too?

**Comment by richardliaw** [comment]
This will depend on your autoscaling policy; if autoscaling is enabled, the autoscaler will spin up more nodes.

**Comment by amogkam** [comment]
Closing this as automatically determining the number of workers for ray train is being tracked here: https://github.com/ray-project/ray/issues/21987 and elastic training for ray train is being tracked here: https://github.com/ray-project/ray/issues/20647
