### ISSUE TITLE
[rllib][Question] Eager mode save model

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#7673]
### What is your question?

I found in `eager_tf_policy.py `, 

```
        @override(Policy)
        def export_model(self, export_dir):
            pass

        @override(Policy)
        def export_checkpoint(self, export_dir):
            pass
```
The two functions are not implemented in the `Policy` class in `policy.py`.  Maybe it is the reason I cannot save the model. Could you please help me?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.8.2
TF: 2.1
OS: macOS

**Comment by billyzs** [comment]
bump, any update on this? v1.0.0 still doesn't implement these 2 functions
