### ISSUE TITLE
[tune] Mlflow example does not track loss to mlflow.

### ISSUE THREAD

**Issue by brechtmann** [ray-project/ray#7677]
OSX
Ray installed from pip    
Ray version: 0.7.5
Python version: 3.7.3
Exact command to reproduce:

https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mlflow_example.py

The problem can be solved by making the loss a float by adding a dot.
` mean_loss=(config["height"] - 14.)**2 - abs(config["width"] - 3))`

This issue occurs due to the fact, that only floats, but no integers are passed to mlflow:
https://github.com/ray-project/ray/blob/master/python/ray/tune/logger.py#L90

Below one can see the data generated by mlflow. Run `1` is with the original example notebook 
and run `2` with the float modification. As one can see run `2` has files tracking the `mean_loss` but run `1` does not. 

Maybe this could be changed, so that integers can be tracked.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/37140213/77179320-9c822600-6ac8-11ea-89d7-12b3a2247b9e.png">

- [ x ] I have verified my script runs in a clean environment and reproduces the issue.

**Comment by richardliaw** [comment]
Ah; would you be open to pushing a fix?

**Comment by brechtmann** [comment]
I will give it a try.

**Comment by brechtmann** [comment]
Sorry but I have a bunch of other things to do and don't know your code base at all, so I will leave this to you. Sorry

**Comment by richardliaw** [comment]
@brechtmann No problem! Appreciate you letting me know. I'll get your PR merged in a couple days.
