### ISSUE TITLE
[dashboard] GPU usage

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#7697]
### Describe your feature request

Trials often require GPU usage; it would be great if we could see the GPU memory and utilization in the dashboard for all nodes.

**Comment by richardliaw** [comment]
OK really - the dashboard is basically useless for any training/deeplearning workload. 

I really just can't tell what's going on (if my actors are working or not).

**Comment by richardliaw** [comment]
cc @rkooo567 @wuisawesome

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/8564

**Comment by wuisawesome** [comment]
this is done now right?

**Comment by richardliaw** [comment]
yeah
