### ISSUE TITLE
Merge Search Algorithms and Trial Schedulers

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#7730]
It is not clear what the difference is between [Search Algorithms](https://ray.readthedocs.io/en/latest/tune-searchalg.html) and [Trial schedulers](https://ray.readthedocs.io/en/latest/tune-schedulers.html).

~~For example, the  [HyperOpt](https://ray.readthedocs.io/en/latest/tune-searchalg.html#hyperopt-search-tree-structured-parzen-estimators) search algorithm does early stopping, which is one of the things I thought only Trial schedulers do.~~

I feel like the distinction is unnecessary - or at least fail to grasp it.

Additionally, it is not very clear which search algorithms can be used with which trial schedulers. Perhaps a matrix/table of compatibility would be useful.

**Comment by richardliaw** [comment]
Hey @drozzy, thanks a bunch for the feedback.

`use_early_stopped_trials` indicates whether you want to feed the stopped trials back into the optimization result. It itself does not manage early stopping (so your original thought of TrialSchedulers is right).

Any thoughts on how to improve docs here?

**Comment by drozzy** [comment]
Ok, that's a bad example.

I am just saying that it seems sometimes one does the same thing as the other.

A better example might be [PBT](https://ray.readthedocs.io/en/latest/tune-schedulers.html#population-based-training-pbt) which basically does hyper-parameter search.

**Comment by richardliaw** [comment]
Right, I think PBT is the only exception though. The other ones are pretty straight forward - either it does early stopping, or it does black box optimization.

**Comment by drozzy** [comment]
Closing, until I can come up with more convincing argument :-)
