### ISSUE TITLE
Why actor methods cannot be called directly?

### ISSUE THREAD

**Issue by cloudhan** [ray-project/ray#7737]
When calling a actor method, that is, call the `__call__` method of an `ActorMethod` object. And this method is implemented as raise an `Exception` directly
```
Exception: Actor methods cannot be called directly. Instead of running 'object.get()', try 'object.get.remote()'
```

But why is it necessary? Why it can't be

```python
class ActorMethod:
    ...
    def __call__(self, *args, **kwargs):
        return ray.get(self._remote(args, kwargs))
    ...
```

Then in some case, If do the following:
```python
class Foo(object):
    def foo(self):
        return "foo"

class Bar(object):
    def bar(self, foo_obj):
        return foo_obj.foo()
 
RayFoo = ray.remote(Foo)
RayBar = ray.remote(Bar)

if __name__ == "__main__":
    f = Foo()
    b = Bar()
    print(b.bar(f))

    ray.init(log_to_driver=False)
    rf = RayFoo.remote()
    rb = RayBar.remote()
    print(rb.bar(rf))
```
with the original `__call__` implementation, this is not possible, but with the proposed one, this works perfectly.

Is there any design consideration?

**Comment by richardliaw** [comment]
This is a design decision we made a couple years ago. The reason is to remain consistent across the API - tasks, methods, and class invocations.

The high level goal is to safeguard against user errors. I should note that commonly, new users often complain about the verbosity of this decision :)

**Comment by cloudhan** [comment]
Are there any design pattern to walkaround the issue I mentioned, that is, what if I want to support both local and Ray decorated types. How to avoid implementing those types twice?

**Comment by ericl** [comment]
You can do that with a wrapper class that automatically invokes .remote() under the hood, e.g., `h = Wrapper(handle)`.

**Comment by cloudhan** [comment]
Tried to hack a new decorator that replace the object constructor with a wrapper and then which replace the actor_method_obj.__call__ method with a new wrapper that return ray.get(actor_method_obj.<method_name>.remote()), too convoluted, will use @ericl 's wrapper.

BTW, it is viable to add an option to allow this type of behavior, e.g.
```python
@ray.remote(allow_non_remote_calls=True)
class Foo(object): ...
```
