### ISSUE TITLE
Can we separate training and running? 

### ISSUE THREAD

**Issue by kikikio** [ray-project/ray#7738]

**Comment by kikikio** [comment]
training on cloud and return parameters to local host to control running.

**Comment by richardliaw** [comment]
Can you provide more context?

**Comment by kikikio** [comment]
I applied DQN to network anomaly detection, but the detection speed was slow. So I plan to separate training and running. We take data and train it on cloud, and then return the parameters to the local.    We control the local running  based on that parameters.

**Comment by kikikio** [comment]
the terminal transmits data to the cloud server, the server trains, and then sends the parameters back to update the local  neural network

**Comment by ericl** [comment]
It sounds like you can use the external connector: https://ray.readthedocs.io/en/latest/rllib-env.html#external-application-clients

i.e., create a client with `client = PolicyClient("<addr>:<port>", inference_mode="local")` which will cache the policy locally and periodically update it from the server
