### ISSUE TITLE
non-ascii characters in remote function crash ray

### ISSUE THREAD

**Issue by kyang922** [ray-project/ray#7755]
I am using ray 0.8.2 and encountered a problem when using non-ascii characters in my remote function. this problem seems have been solved once but in 0.8.2 and 0.8.3 it appear again.

for detail, please see the following link.
[Support non ascii characters in the source code](https://github.com/ray-project/ray/pull/4047#issuecomment-604373744) 

this post was posted 1 year ago so I open a new issue to remind you.

**Comment by anabranch** [comment]
What version of python are you using?

**Comment by kyang922** [comment]
I am using Python 3.7, thanks!
