### ISSUE TITLE
[rllib] Parameter sharing not possible from v0.8.3?

### ISSUE THREAD

**Issue by lennardsnoeks** [ray-project/ray#7761]
### What is your question?
I want to use parameter sharing where each agent learns the same policy. I have a policy mapping where each agent in the MultiAgentEnv has the same policy as follows:

     config["multiagent"] = {
        "policies": {
            "policy_0": (DDPGTFPolicy, obs_space, action_space, {"gamma": 0.95})
        },
        "policy_mapping_fn": lambda agent_id: "policy_0"
    }

     class MultiAgentEnvironment(MultiAgentEnv):
    
        def __init__(self, env_config):
            self.sim_state: SimulationState = env_config["sim_state"]
            self.env_config = env_config
    
            self.load_agents()
    
        def step(self, action_dict):
            obs, rew, done, info = {}, {}, {}, {}
    
            for i, action in action_dict.items():
                obs[i], rew[i], done[i], info[i] = self.agents[i].step(action)
                if done[i]:
                    self.dones.add(i)
    
            done["__all__"] = len(self.dones) > 0
    
            return obs, rew, done, info
    
        def reset(self):
            self.resetted = True
            self.dones = set()
            return {i: a.reset() for i, a in enumerate(self.agents)}

        def load_agents(self):
            self.agents = []
            for i in range(0, len(self.sim_state.agents)):
                self.env_config["agent_id"] = i
                self.agents.append(SingleAgentEnv(self.env_config))

The step method of the MultiAgentEnv will only train / update one agent instead of all of them. The agents are all present, but the action dictionary seems to only contain actions for 1 single agent. This behavior is not present in v0.8.2, but it is in v0.8.3 and v0.9.0dev. Is this intentional?

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray v0.8.3 and onwards
python v3.7.4

**Comment by ericl** [comment]
That shouldn't be the case. Can you create a reproduction script (see bug issue template)?

**Comment by lennardsnoeks** [comment]
I investigated a bit further, and it only seems to occur for DDPG. Here is a reproduceable script. If you run it for DDPG, the printed action_dict only contains items for the first agent with id 0. For PPO it prints actions for all 10 agents.

    import ray
    import gym
    import numpy as np
    import math
    from ray.rllib import MultiAgentEnv
    import ray.rllib.agents.ddpg as ddpg
    import ray.rllib.agents.ppo as ppo
    from ray.tune import register_env, run
    from gym.spaces import Box
    from random import uniform
    
    
    class SingleAgentEnvironment(gym.Env):
    
        def __init__(self):
            self.observation_space = Box(low=0, high=1000, shape=(2,))
            self.action_space = Box(low=-1, high=1, shape=(2,))
    
            self.pos_X = 0
            self.pos_Y = 0
    
            self.goal_X = uniform(0, 1000)
            self.goal_Y = uniform(0, 1000)
    
            self.previous_distance = math.hypot(self.goal_X - self.pos_X, self.goal_Y - self.pos_Y)
    
        def step(self, action):
            done = False
    
            x = action[0]
            y = action[1]
    
            self.pos_X += x
            self.pos_Y += y
    
            if self.pos_X < 0:
                self.pos_X = 0
            if self.pos_Y < 0:
                self.pos_Y = 0
            if self.pos_X > 1000:
                self.pos_X = 1000
            if self.pos_Y > 1000:
                self.pos_Y = 1000
    
            distance = math.hypot(self.goal_X - self.pos_X, self.goal_Y - self.pos_Y)
    
            reward = 2 * (self.previous_distance - distance)
    
            self.previous_distance = distance
    
            if self.pos_X == self.goal_X and self.pos_Y == self.goal_Y:
                done = True
    
            obs = np.array([self.pos_X, self.pos_Y])
    
            return obs, reward, done, {}
    
        def reset(self):
            obs = np.array([0,0])
            return obs
    
        def render(self, mode='human'):
            pass
    
        def get_action_space(self):
            return self.action_space
    
        def get_obs_space(self):
            return self.observation_space
    
    
    class MultiAgentEnvironment(MultiAgentEnv):
    
        def __init__(self, num_agents):
            self.num_agents = 10
    
            self.agents = []
            for i in range(0, num_agents):
                self.agents.append(SingleAgentEnvironment())
    
        def step(self, action_dict):
            obs, rew, done, info = {}, {}, {}, {}
    
            print(action_dict)
    
            for i, action in action_dict.items():
                obs[i], rew[i], done[i], info[i] = self.agents[i].step(action)
                if done[i]:
                    self.dones.add(i)
    
            done["__all__"] = len(self.dones) > 0
    
            return obs, rew, done, info
    
        def reset(self):
            self.resetted = True
            self.dones = set()
            return {i: a.reset() for i, a in enumerate(self.agents)}
    
        def initial_visualization(self, visualization):
            visualization.run()
    
    
    def main():
        #config = ddpg.DEFAULT_CONFIG.copy()
        config = ppo.DEFAULT_CONFIG.copy()
    
        single_env = SingleAgentEnvironment()
        obs_space = single_env.get_obs_space()
        action_space = single_env.get_action_space()
    
        config["multiagent"] = {
            "policies": {
                "policy_0": (None, obs_space, action_space, {"gamma": 0.95})
            },
            "policy_mapping_fn": lambda agent_id: "policy_0"
        }
    
        register_env("multi_agent_env", lambda _: MultiAgentEnvironment(10))
        config["env"] = "multi_agent_env"
    
        ray.init()
    
        #run("DDPG", config=config)
        run("PPO", config=config)
    
    
    if __name__ == "__main__":
        main()
