### ISSUE TITLE
Out of order episodes with RLLib Policy Client/Server

### ISSUE THREAD

**Issue by kivo360** [ray-project/ray#7816]
### How to run RLLib Policy Client/Server Out of Order ?

*RLLib, Ray version: 0.8.3, Ubuntu 20.04*

I'm running a cartpole experiment and I'm attempting to run the episodes at random instead of a sequential order. It's to mirror an asynchronous run environment. The code I'm running looks exactly like the example from PolicyClient. Only it register's the episodes immediately then runs through each episode in a random order. 

```py
_env = gym.make("CartPole-v0")
client = PolicyClient(
    "http://localhost:9900", inference_mode="local")

episode_ids = [uuid.uuid4().hex for _ in range(10000)]

episode_obs = {}
episode_reward = {}
individual_env = {}

for eid in episode_ids:
    client.start_episode(episode_id=eid)
    individual_env[eid] = copy.deepcopy(_env)
    episode_obs[eid] = individual_env[eid].reset()
    episode_reward[eid] = 0


while True:
    if len(episode_ids) == 0:
        break
    eid = random.choice(episode_ids)
    current_obs = episode_obs[eid]
    action = client.get_action(eid, current_obs)
    obs, reward, done, info = individual_env[eid].step(action)
    episode_reward[eid] += reward
    client.log_returns(eid, reward, info=info)
        
    if done:
        print("Total reward:", episode_reward[eid])
        del episode_obs[eid]
        del episode_reward[eid]
        episode_ids.remove(eid)
        client.end_episode(eid, obs)
```

I'm finding there are issues with this concept. I'm going to write them in list formatting for organizational reasons:
1. These will all be for `inference_mode="remote"`. I understand that you might be seeing `local` instead, that's so I could get an example to work. Though in real life I'd like to run remote so I don't have issues with out of date policies on different machines.
2. The episode ends immediately for each item. I'm therefore forced to generate many episodes, how can I force the environment to continue?
3. I periodically end up pushing the wrong observation type to the server, where it says: `ValueError: ('Observation outside expected value range', Box(4,), array([-3.68777547, -2.62304109,  7.16275509,  3.41793433]))`. I'm getting the observation space directly from the environment, and I honestly can't figure out why it's giving me the error it is. Is there some kind of casting issue I need to get through?

What am I doing wrong here?

**Comment by ericl** [comment]
Hmm, it runs ok for me when I change episodes_ids from 10000 to a smaller value like 1000. It's possible you're hitting the internal limit on number of active episodes which is set to 100 by default (though it should be raising an error if it's hit).

E.g., if I set 10 episodes, "local" inference mode", and add `print("current eps", eid, current_obs, action, "done=", done)` after the step, the output finishes:

```
current eps d41be4f0f88e4273b72a799900df2498 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps 090b63d13cbf4bac84fe05c2b2f3aa4c [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps d030d0fc543f40bbbb587885cc01f5a3 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps d030d0fc543f40bbbb587885cc01f5a3 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps 090b63d13cbf4bac84fe05c2b2f3aa4c [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps d41be4f0f88e4273b72a799900df2498 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= True
Total reward: 9.0
current eps 090b63d13cbf4bac84fe05c2b2f3aa4c [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps 090b63d13cbf4bac84fe05c2b2f3aa4c [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= True
Total reward: 9.0
current eps d030d0fc543f40bbbb587885cc01f5a3 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps d030d0fc543f40bbbb587885cc01f5a3 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= False
current eps d030d0fc543f40bbbb587885cc01f5a3 [0.00367234 0.02174809 0.00396283 0.00597577] 0 done= True
Total reward: 9.0
```

Are you seeing something different?

**Comment by kivo360** [comment]
Hi @ericl I managed to figure out why my original example didn't work. It was a problem largely because I wasn't duplicating and creating a separate environment for each episode. By the time I pasted this code snippet I had done that without running the code and believed the problem was not fixed. This won't be a problem in a live environment.
