### ISSUE TITLE
Type annotation for Ray

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#7820]
### Describe your feature request
As Python static type checker is gaining popularity, Ray should be able to start to add type annotation in its API. A preliminary annotation can be implemented via generics:

```python
from typing import TypeVar, Generic

T = TypeVar('T')

class ObjectID(Generic[T]):
    pass

def put(obj: T) -> ObjectID[T]:
    pass

def get(oid: ObjectID[T]) -> T:
    pass

def take_int(inp: int): pass
def take_str(inp: str): pass

int_oid = put(1)
take_int(get(int_oid)) # pass
take_str(get(int_oid)) # fail
```

Output
```
a.py:19: error: Argument 1 to "take_str" has incompatible type "int"; expected "str"
Found 1 error in 1 file (checked 1 source file)
```

Please upvote this issue (via github reactions) if you want it to be implemented in Ray. (or contribute!)

**Comment by walterddr** [comment]
+1. I find static type checking a very useful tool to understand "platform/lib" code. This would be extremely user-friendly

**Comment by pcmoritz** [comment]
Another related question here (which would be the most useful first pass even before we do typing for ObjectIDs) is how to type `ray.remote` such that the type of

**Comment by ijrsvt** [comment]
The typing of arguments appears to be enforced at runtime. The result from both:
```
f.remote(1,1)
f.remote(1,ray.put(1)) #or this
```
is 
```
File "python/ray/_raylet.pyx", line 460, in ray._raylet.execute_task
    outputs = function_executor(*args, **kwargs)
TypeError: must be str, not int
```

**Comment by simon-mo** [comment]
Interesting. Can you find the lines of code that perform this check?

**Comment by rkooo567** [comment]
This is partially supported by this https://github.com/ray-project/ray/pull/9574/files. We will keep having progress towards.
