### ISSUE TITLE
Is it possible to use the policy server/client structure with APEX-DQN in [rllib]?

### ISSUE THREAD

**Issue by ebilgin** [ray-project/ray#7821]
I am trying to run the cartpole_server.py example with APEX-DQN. 

`

    env = "CartPole-v0"
    connector_config = {
        # Use the connector server to generate experiences.
        "input": (
            lambda ioctx: PolicyServerInput( \
                ioctx, SERVER_ADDRESS, SERVER_PORT)
        ),
        # Use a single worker process to run the server.
        "num_workers": 0,
        # Disable OPE, since the rollouts are coming from online clients.
        "input_evaluation": [],
    }

    if args.run == "DQN":
       ...
    elif args.run == "PPO":
        ...

    elif args.run == "APEX":
        trainer = ApexTrainer(
            env=env,
            config=dict(
                connector_config
            ))

    else:
        raise ValueError("--run must be DQN or PPO")

    checkpoint_path = CHECKPOINT_FILE.format(args.run)

    # Attempt to restore from checkpoint if possible.
    if os.path.exists(checkpoint_path):
        checkpoint_path = open(checkpoint_path).read()
        print("Restoring from checkpoint path", checkpoint_path)
        trainer.restore(checkpoint_path)

    # Serving and training loop
    while True:
        print(pretty_print(trainer.train()))
        checkpoint = trainer.save()
        print("Last checkpoint", checkpoint)
        with open(checkpoint_path, "w") as f:
            f.write(checkpoint)
`
which gives me an assertion error since num_workers is 0. 

`
Traceback (most recent call last):
  File "cartpole_server.py", line 88, in <module>
    print(pretty_print(trainer.train()))
  File "/home/enbilgin/ws/envs/ray083/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 505, in train
    raise e
  File "/home/enbilgin/ws/envs/ray083/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 491, in train
    result = Trainable.train(self)
  File "/home/enbilgin/ws/envs/ray083/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/enbilgin/ws/envs/ray083/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 154, in _train
    fetches = self.optimizer.step()
  File "/home/enbilgin/ws/envs/ray083/lib/python3.7/site-packages/ray/rllib/optimizers/async_replay_optimizer.py", line 141, in step
    assert len(self.workers.remote_workers()) > 0
AssertionError
`

If I increase it, I run into port allocation issues. How can I use APEX-DQN with the policy server structure?

- RLlib 0.8.3
- Ubuntu 18.04

**Comment by ericl** [comment]
This is a bug; Ape-X is asserting that it requires at least one worker, which is reasonable when collecting experiences, but not when using the server input source.

For now, I would consider using normal DQN (you can configure it with hyperparams quite similar to Ape-X).

**Comment by ebilgin** [comment]
Thank you!

**Comment by ebilgin** [comment]
> This is a bug; Ape-X is asserting that it requires at least one worker, which is reasonable when collecting experiences, but not when using the server input source.
> 
> Should be easy to fix, though not trivial since we still need the distributed replay actors. I would consider using normal DQN with changed hyperparams for now.

Thank you!
