### ISSUE TITLE
How to save and load Pytorch checkpoint of a custom model?

### ISSUE THREAD

**Issue by omri-axon-vision** [ray-project/ray#7831]
It seems from the repo it is not implemented yet:

https://github.com/ray-project/ray/blob/e4bd5db4d848b9fd6fd52b7f9e5e271d0468eaeb/rllib/policy/torch_policy.py

It there any way for the torch people to save/load their trained weights somehow?

**Comment by ttumiel** [comment]
I think it is implemented in line 202. It's just a little complicated but the Trainer calls _restore which calls restore for all the workers which calls set_weights which calls line 202 load_state_dict. So just using the `restore` kwarg in tune.run will restore your model from the checkpoint. Saving is done similarly with the checkpoint_at_end and checkpoint_freq args to tune.run and similarly uses get_weights in the same file.
