### ISSUE TITLE
How to view the MultiAgentEnv reward per agent?

### ISSUE THREAD

**Issue by Nicholaz99** [ray-project/ray#7832]
### What is your question?
Hi, So I'm trying to train my custom multi-agent environment with PPO Algorithm. Is it possible to print the rewards per agent? I only notice episode rewards, but I need the details reward per agent. Thank you very much for your help

**Comment by ericl** [comment]
You should be able to see the mean reward per policy (reported under policy_reward_mean key).

**Comment by Nicholaz99** [comment]
> You should be able to see the mean reward per policy (reported under policy_reward_mean key).

It weird because my policy_reward_mean is always an empty dict {}. Could you explain to me what is the expected value for the policy_reward_mean_key dictionary?

**Comment by Nicholaz99** [comment]
> You should be able to see the mean reward per policy (reported under policy_reward_mean key).

But actually, is it possible to see the reward per agent per episode? I use PPO and I want to make the reward plot for each agent on each episode, to see how good the agents development. Thank youuu

**Comment by ericl** [comment]
You'll need custom metrics for that (see the documentation).

**Comment by Nicholaz99** [comment]
Ah I see, Thank you for the information!!
