### ISSUE TITLE
GCS Resolves to Wrong Address

### ISSUE THREAD

**Issue by ijrsvt** [ray-project/ray#7837]
### What is the problem?
GCS Resolves Hostname to incorrect address on MacOS. This causes a variety of problems with actors and ray functionality.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: 0.84
OS: MacOS Catalina

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
import ray
ray.init()
@ray.remote
class Actor:
    def G(self):
        return 30
act = Actor.remote()
ray.get(act.G.remote())
```
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
Does 't this resolve the issue? 
https://github.com/ray-project/ray/pull/7822

**Comment by ijrsvt** [comment]
No, it's more of a MacOS configuration problem.

**Comment by ijrsvt** [comment]
Solution:
Get the current `LocalHostName` by running: 
`sudo scutil --get LocalHostName`

Set the `HostName` to the result above with `.local` appended to it. 
`sudo scutil --set HostName <name_from_above>.local`

**Comment by rkooo567** [comment]
Just let you know I could use Ray on Mac without the setup you commented (I also don't have `.local` appended to my host name).

**Comment by simon-mo** [comment]
Yes this only happen to some Mac machines for weird reasons

**Comment by ijrsvt** [comment]
@rkooo567  and @simon-mo . What IP Address does it resolve to? 
It should be in `gcs_server.out`, on this line: 
 `gcs_server.cc:182] Finished setting gcs server address: 192.168.1.<x>:<port_num>`

**Comment by rkooo567** [comment]
`I0331 17:14:34.556454 470506944 gcs_server.cc:181] Finished setting gcs server address: 192.168.1.82:54262`
```
$sudo scutil --get LocalHostName
SangBins-MacBook-Pro
```

**Comment by richardliaw** [comment]
BTW, the fix that still consistently works for me is `RAY_GCS_SERVICE_ENABLED=0`. Right now without it on the latest master, I get the following on my mac: 

```
print(ray.cluster_resources())
# {}
```

cc @raulchen @micafan

**Comment by richardliaw** [comment]
BTW @ijrsvt is it ok to reopen this issue? I think it's better to have a Ray that works out of the box (then for the user to need to run sudo commands).

**Comment by ijrsvt** [comment]
@richardliaw I'm reopening this. PR (#7842) should fix this (within ray).
