### ISSUE TITLE
DQN Offline Training Parameter Settings

### ISSUE THREAD

**Issue by strider2king** [ray-project/ray#7845]
### What is your question?
Thank you so much for developing such a wonderful package!!!

I am not sure how to properly set up the parameters in the DQN config. 

How the InputReader is dealing with the offline trajectories in the *.json files, do we still need to specify the "rollout_fragment_length"?  

if the rollout_fragment_length is smaller than the length of trajectories, will the input_reader continue reading the remaining transitions? 

what do we mean by "iteration" here in this package? what do we do in one iteration, is it just one SGD update (or this is just one step?)

Sorry to have so many stupid questions...

I essentially mean how can we properly setup the parameters so that we can do a Fitted Q iteration? Many thanks!

**Comment by sluo198912** [comment]
By the way, can we have some advice about how to properly setup the ray.init memory and object_store_memory, num_cpus? Thank you~~~
