### ISSUE TITLE
[rllib] Unable to configure exploration parameters in PPO: Unknown config parameter `explore`

### ISSUE THREAD

**Issue by ZekiDorukErden** [ray-project/ray#7849]
Hello,

I am unable to configure exploration parameters when trying to create a PPO trainer. Dictionary entries "explore" and "exploration_config" is said to be unknown. Below are the relevant trainer definition and the traceback.

`trainer = PPOTrainer(
                      env=env_title,
                      config={
                          
                        "explore": True,
                        "exploration_config": {
                          "type": "EpsilonGreedy",
                          # Parameters for the Exploration class' constructor:
                          # "initial_epsilon"=1.0,  # default is 1.0
                          # "final_epsilon"=0.05,  # default is 0.05
                          "epsilon_timesteps": max_steps,  # Timesteps over which to anneal epsilon, defult is int(1e5).
                        },

                        "num_workers": 5,
                        "num_gpus": 2,
                        "model": nw_model,
                        "multiagent": {
                          "policy_graphs": policy_graphs,
                          "policy_mapping_fn": policy_mapping_fn,
                          "policies_to_train": ["ppo_policy{}".format(i) for i in range(n_agents)],
                        },
                        "callbacks": {
                          "on_episode_start": tune.function(on_episode_start),
                          "on_episode_step": tune.function(on_episode_step),
                          "on_episode_end": tune.function(on_episode_end),
                        },
                        "log_level": "ERROR",
                      })`

Full traceback:

`Exception                                 Traceback (most recent call last)
<ipython-input-9-252111d46b85> in <module>()
    121                           "on_episode_end": tune.function(on_episode_end),
    122                         },
--> 123                         "log_level": "ERROR",
    124                       })
    125 

4 frames
/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer_template.py in __init__(self, config, env, logger_creator)
     88 
     89         def __init__(self, config=None, env=None, logger_creator=None):
---> 90             Trainer.__init__(self, config, env, logger_creator)
     91 
     92         def _init(self, config, env_creator):

/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer.py in __init__(self, config, env, logger_creator)
    370             logger_creator = default_logger_creator
    371 
--> 372         Trainable.__init__(self, config, logger_creator)
    373 
    374     @classmethod

/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py in __init__(self, config, logger_creator)
     94         self._restored = False
     95         start_time = time.time()
---> 96         self._setup(copy.deepcopy(self.config))
     97         setup_time = time.time() - start_time
     98         if setup_time > SETUP_TIME_THRESHOLD:

/usr/local/lib/python3.6/dist-packages/ray/rllib/agents/trainer.py in _setup(self, config)
    476         merged_config = deep_update(merged_config, config,
    477                                     self._allow_unknown_configs,
--> 478                                     self._allow_unknown_subkeys)
    479         self.raw_user_config = config
    480         self.config = merged_config

/usr/local/lib/python3.6/dist-packages/ray/tune/util.py in deep_update(original, new_dict, new_keys_allowed, whitelist)
    158         if k not in original:
    159             if not new_keys_allowed:
--> 160                 raise Exception("Unknown config parameter `{}` ".format(k))
    161         if isinstance(original.get(k), dict):
    162             if k in whitelist:

Exception: Unknown config parameter `explore` `

I am using Google Colab and Tensorflow 2.

**Comment by sven1977** [comment]
Hi, you are probably on an older version of ray? What's your version number?
For now, try to remove these two keys (`exploration_config `and `explore`) altogether. You probably should not run PPO with EpsilonGreedy anyways.

**Comment by ZekiDorukErden** [comment]
Thanks for the reply! Apparently I am using version 0.8.0.dev5 (I copied the code block for dependencies in Google Colab tutorial without changing).

**Comment by sven1977** [comment]
Ok, cool. So it's working now?

**Comment by ZekiDorukErden** [comment]
Yes, when I run without the exploration settings, it worked. Thanks for the help!
