### ISSUE TITLE
Ray Remote Invocation Runs Process Rather Than Returning an ID

### ISSUE THREAD

**Issue by DLWCMD** [ray-project/ray#7858]
I am attempting to build my own parallelized hyper parameter selection function, based on your example, https://ray.readthedocs.io/en/latest/auto_examples/plot_hyperparameter.html, which I have installed and run successfully.

The method below is analogous to the _evaluate_hyperparameters_ in your example, even including a _trainmodel_ call.
`@ray.remote(num_cpus=4)`
`def perform_single_rs(srch_num, X_train, X_test, y_train, y_test,
                      model=None, params=None,sample_weights=None, best_model_path=None, data_CNN=None):`
    `print('Search {0:3d}'.format(srch_num))`
   ` model = create_model_cnn(params)`
`X_train_CNN, X_test_CNN = trainmodel(X_train, X_test, y_train, y_test, model=model,
                                       # params=params, sample_weights=sample_weights, data_CNN=data_CNN)`
    `best_model = load_model(best_model_path)`
`results = {'best model': best_model,'params':params, 'X_train_CNN': X_train_CNN, 'X_test_CNN': X_test_CNN}`
   ` return results`

However, when I invoke the above method, rather than return a set of ids that I can then use either with ray.get or ray.wait, as was used in your example, model training (=fitting) begins. Here's a snippet of console output:
(pid=45299) Epoch 1/300
(pid=45299) Epoch 2/300
(pid=45301) Epoch 2/300
(pid=45299) Epoch 3/300
(pid=45301) Epoch 3/300
(pid=45301) Epoch 4/300

I would appreciate any suggestions. Thanks.

David Wilt

Ray version: 0.8.3, Python 3.6.1, Mac OS Catalina, TF 2.1

**Comment by rkooo567** [comment]
Can you write your code with three `? Your code will be formatted better in that way. For example,
\```python3
[Your Code Here]
\```

Also, the function is scheduled and run on an available worker (process) as soon as you invoke the remote function from your driver script. So, that's the right behavior!

**Comment by DLWCMD** [comment]
First, thanks for your response, and my apologies for the code formatting. I tried to apply the three backward apostrophes, but apparently I didn't succeed.

As to the behavior of my code, since my posting, I have tested several of the methods in my application with remote invocation. All of them, except _fitmodel_ shown below, behave as expected: the call to ...remote() generates a set of ids (futures), to which I can apply ray.get() as follows. In this case, the method reads and returns four data sets.
```
 while remaining_ids:
        # Use ray.wait to get the object ID of the first task that completes.
        done_ids, remaining_ids = ray.wait(remaining_ids)
        # There is only one return result by default.
        result_id = done_ids[0]
        xtr, xts, ytr, yts   = ray.get(result_id)
```

However, the method below **both** returns futures and then immediately begins to execute the _model.fit_ function.
```
@ray.remote
def fitmodel(params, data_CNN, y_train, sample_weights, y_cv, es=None, rlp=None, mcp=None):
    model = create_model_cnn(params)
    history = model.fit(data_CNN['X_train'],
                        y_train,
                        epochs=params['epochs'],
                        verbose=50,
                        batch_size=params['batch_size'], shuffle=True,
                        validation_data=(data_CNN['X_cv'], y_cv),
                        #callbacks=[es, mcp, rlp],
                        sample_weight=sample_weights
                        )
    return history
```
Here is a snippet of console output that results from fitting the model, which begins **without** using ray.get() to initiate.

(pid=30401) Epoch 1/300
(pid=30404) Epoch 1/300
(pid=30405) Epoch 1/300
(pid=30402) Epoch 1/300
(pid=30406) Epoch 1/300
(pid=30401) Epoch 2/300
(pid=30404) Epoch 2/300
(pid=30405) Epoch 2/300
(pid=30402) Epoch 2/300

Can you suggest why this one method is behaving differently than expected for ray? Thanks.

**Comment by DLWCMD** [comment]
To further clarify the method's behavior, the screen shot below shows processing has halted (blue line break point) before any IDs are selected for execution with ray.get(). Nevertheless, model fitting is being executed.

<img width="623" alt="Screen Shot 2020-04-03 at 1 55 05 PM" src="https://user-images.githubusercontent.com/48808570/78390554-c2242a80-75b2-11ea-9000-2d1d9c113637.png">

**Comment by rkooo567** [comment]
@DLWCMD sorry. It seems like I for some reason forgot about answering the issue. Is this resolved or still relevant!
