### ISSUE TITLE
[rllib] modifying columns with the "on_postprocess_traj" may have no effect.  

### ISSUE THREAD

**Issue by t-roloft** [ray-project/ray#7866]
### What is the problem?

When using the "on_postprocess_traj" callback, modifications to 1-dimensional columns of info["post_batch"] are not incorporated into the SampleBatch returned by the worker.  Modifications to two 2-dimensional columns do have an effect.  Therefore, modifying observations has an effect, but modifying advantage estimates or value predictions does not.

The reason appears to be that the batch is added to the SampleBatchBuilder just before the "on_postprocess_traj" callback is executed.  SampleBatchBuilder.add_batch() uses list.extend to append each column of the new batch to its existing columns.  list.extend() behaves differently for 1d numpy arrays than for higher dimensional arrays.  For 1d arrays, the data is copied to the list's buffer, so no reference to the original numpy buffer is retained.  For 2d arrays, we get a list of references to 1d numpy arrays, which themselves refer to the existing numpy buffer.  Therefore, modifications to the observation space as in the "centralized_critic_2.py" example have an effect, while modifications to rewards, advantages, or value estimates are ignored.

Versio info:
Ubuntu 18.04
python 3.6.8
numpy==1.18.2
ray>=0.8.0

### Reproduction (REQUIRED)

```
import ray
from ray.tune import run_experiments
from ray.rllib.evaluation.postprocessing import Postprocessing
from ray.rllib.policy.sample_batch import SampleBatch


def blank_observations(info):
    info["post_batch"][SampleBatch.CUR_OBS].fill(0.0)


def blank_advantages(info):
     info["post_batch"][Postprocessing.ADVANTAGES].fill(0.0)


if __name__ == '__main__':
    EXPERIMENTS = {
        "PPO_REPRO_ERROR": {
                "run": "PPO",
                "env": "CartPole-v0",
                "stop": {
                    "episodes_total": 500,
                },
                "config": {
                    "callbacks": {
                        # This should cause learning to fail, but it doesn't
                        "on_postprocess_traj": blank_advantages
                        # This does cause learning to fail
                        # "on_postprocess_traj": blank_observations
                    }
                },
            },
        }

    ray.init(num_cpus=4)
    run_experiments(EXPERIMENTS, verbose=0)
```

**Comment by ericl** [comment]
Thanks! I think this should be fixed as part of https://github.com/ray-project/ray/pull/7862/files , can you  confirm?

**Comment by t-roloft** [comment]
So it looks like this has fixed the issue, as both test cases now fail to learn at all (which is what should happen), while removing the callbacks altogether allows it to to find a good policy.  Thanks for your help with this!
