### ISSUE TITLE
[tune][rllib] Custom TensorBoard metrics for standard RLLib agent

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#7871]
### What is your question?
I am running the DQN policy from the standard RLLib agents folder. It provides several metrics when I run TensorBoard but I would like to extend the logging output to include my environment reward after every timestep. How can I log this on top of the already logged metrics?

from ray.rllib.agents.dqn import DQNTrainer
config = ray.rllib.agents.dqn.DEFAULT_CONFIG.copy()
config["env"] = my_dqn_gym_env.Environment
ray.init()
tune.run(DQNTrainer, name='testname',
                         stop={"training_iteration": 1000},
                         config=config,
                         # local_dir=train_checkpoint_save_loc,
                         checkpoint_freq=1,
                         resume=False)

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6
Centos 7

**Comment by ruben39x2** [comment]
You can implement a class that inherits from `DefaultCallbacks` and use the custom callbacks to add values to `episode.custom_metrics`. They will be automatically added to the logdir and you can see them on Tensorboard.

Follow this example and you should be ready to go in less than an hour or so https://github.com/ray-project/ray/blob/0c80efa2a37f482494fbffbe9e81f61586b03ecb/rllib/examples/custom_metrics_and_callbacks.py
