### ISSUE TITLE
End Iteration after Episode is done

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#7874]
### What is your question?
Before attempting to switch over to using Ray and RLlib, my team had a solution that would conclude the iteration either when done=True or when current_step > max_steps. Now that I am trying out RLlib, Ive gotten everything to work (Though I havent compared the training to my previous baseline). The only thing is that I noticed the iteration always goes until the total timesteps are reached and then there is an episodes per iteration counter. 

I am not sure how this affects training but in my baseline implementation before RLlib, the policy update happened after the end of the iteration (when episode done=True or max_steps), and now with RLlib it happens at the end of the iteration (only at max_steps)? Is there a way to make my new implementation with RLlib work like before or is it fine like this?

Thanks

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6
Centos

**Comment by sofyanajridi** [comment]
Does anyone have a solution for this? I am running into the same issue.
