### ISSUE TITLE
Ray for imread

### ISSUE THREAD

**Issue by ajitjohnson** [ray-project/ray#7882]
### What is your question?
Is it possible to use ray to speed up reading large single images (>80GB) into memory?

Currently, I use the following which takes a really long time.

```
image = tifffile.imread(image_path)
```

Thank you.

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by wuisawesome** [comment]
I don't think we have an out of the box replacement for reading images, but there might be some way to speed this up if your bottleneck is disk i/o and you're able to replicate beforehand. 

Are you able to share anything about your use case?

**Comment by ajitjohnson** [comment]
Thanks Alex. In my case I work on image analysis using large multi-layer images (TIFF or OME-TIF). I use  napari to visualize the images and in order to launch Napari from python, I need to load the image as a numpy array into memory. Is this why you were looking for?

**Comment by ajitjohnson** [comment]
I have used the below to parallelize the import of different layers. Yet to test in a large image to see if it improves the speed but please do let me know if you think there is a better solution. Thank you.

```
    ray.init(ignore_reinit_error=True)
    @ray.remote
    def load_image (image_path,key):
        image = skimage.io.imread(image_path, key=key)
        return image
    futures = [load_image.remote(image_path=image_path, key=i) for i in range(40)]
    perm = ray.get(futures)
    ray.shutdown()
```
