### ISSUE TITLE
[ray] build error: ERROR: Unrecognized option: --incompatible_depset_is_not_iterable=false

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#7884]
### What is the problem?
I am trying to build/install ray from source, but ran into the following error:
```
ERROR: Unrecognized option: --incompatible_depset_is_not_iterable=false
```

It seems as if in the latest bazel version, they have removed that flag: https://github.com/bazelbuild/bazel/commit/9f9f5ec10fed81362c35c50eeb4515bbe5bf8bce

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 0.8.4
python: 3.8.2
os: Arch Linux
bazel: 2.2.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

The above does not apply.

**Comment by devinbarry** [comment]
Ive been having this same issue every time I try to run the build. I have to delete that flag whenever I pull the latest code
