### ISSUE TITLE
[raySGD] PyTorch Mixed Precision Training w/out Apex

### ISSUE THREAD

**Issue by yutaizhou** [ray-project/ray#7890]
### Describe your feature request
According to [this very recent update from PyTorch](https://twitter.com/ptrblck_de/status/1245610083964170241), native mixed precision training is now available. The lack of need for Apex makes this a great addition to [FP16 Training for RaySGD](https://ray.readthedocs.io/en/latest/raysgd/raysgd_pytorch.html#mixed-precision-fp16-training)!

**Comment by richardliaw** [comment]
Yeah, saw this! I think this probably just simplifies our codebase. I'd expect to merge in changes once the next Pytorch release lands.

**Comment by amogkam** [comment]
Pytorch native mixed precision has been added to Ray Train as of https://github.com/ray-project/ray/pull/22227 and will be included in Ray 1.12!
