### ISSUE TITLE
[ray][rllib] what is the advantage of using multiple default policies in a MultiagentEnvironment 

### ISSUE THREAD

**Issue by suprmat95** [ray-project/ray#7897]
### What is the advantage of using multiple default policies in a MultiagentEnvironment 
I'm working on building a custom multiagent environment about stock trading. I'm using PPO algorithm to train my agent. I wonder what the advantage can be in using more "default policy".

For example If I want train 10 agents which are completely equal, and I bound five agents to policy1 (PPODefaultPolicy) and five agents to policy2 ( the same PPODefaultPolicy). I could observe different behaviour than using a single policy?

Really thank you Matteo.

**Comment by ericl** [comment]
Each policy will have a different set of trainable weights. In your configuration, policy1's weights will be different from policy2. So every agent controlled by policy1 will be weight-sharing, same for policy2.
