### ISSUE TITLE
[rllib] Custom workflow for stepping the environment

### ISSUE THREAD

**Issue by Achin17** [ray-project/ray#7905]
I want to use the action computed by the SAC policy to use in an optimization process which would then be used to step the environment. I am planning to use ROS services to get this done as my optimization routine is in C++. I went through the documentation to see how this can be achieved using Rllib but couldn't find anything relevant. 
Is there any example you can refer me to? Or just pin point me to main files or the methods I would have to change to get this accomplished. Any help would be greatly appreciated.

**Comment by ericl** [comment]
Can you do this with a custom environment class? Not sure the requirements of the ROS services.

**Comment by Achin17** [comment]
Thanks for the reply! I already have the optimization routine in ROS which might be non trivial to get rid of. Considering time constraints, it would be better if I can find an example of a custom environment class which already has the ROS functionality

**Comment by ericl** [comment]
Maybe via http://wiki.ros.org/ROS/Tutorials/Using%20a%20C%2B%2B%20class%20in%20Python ?
