### ISSUE TITLE
Can ray tune.run() be called recursively ?

### ISSUE THREAD

**Issue by andrewv99** [ray-project/ray#7906]
Is this recursive use of ray tune.run() possible:

- I want to create a ray tune Experiment instance called experiment1, and I pass the Experiment constructor an instance of a matching Trainable1 class.
- The Trainable1._train() method body creates a second Experiment instance called experiment2 , and experiment2 would be passed a reference to another Trainable -  Trainable2 class. Each tune.run(experiment2) called in Trainable1._train() would block until experiment2 was fully completed, before returning.
- Trainable2._train() would NOT call tune.run() yet again, it would only perform some synchronous processing and return.

I am using ray 0.77 on Ubuntu 18.04 LTS

If not possible in ray 0.77, is this functionality supported in a later version of ray, or a planned feature ?

Thanks

**Comment by richardliaw** [comment]
Hypothetically, this should be possible.

Are you just trying to run multiple experiments simultaneously?

**Comment by andrewv99** [comment]
Thanks for responding quickly :)

I have 2 levels in the overall experiment structure:
The top level is the standard ray/tune hyperparameter search.
The next level Experiment2 that uses Trainable2._train() (and launched within each Trainable1._train()) is run with the experiment2 Experiment() parameters:
  resources_per_trial = {"cpu": 1, "gpu": 0}
  num_samples=1,
  stop={"training_iteration": 1},
that you previously showed me how to set up in another question I asked. I can run each of these two levels of experiments on their own ok, but I was wanting to combine them hierarchically as explained. Importantly, I need the final results of each experiment2, before the experiment1 Trainable1._train() can return a result to the top level ray.tune hyperparameter search.

Thanks

**Comment by richardliaw** [comment]
Got it. Basically, this _is_ possible but requires a custom TrialExecutor for the lower level experiment (https://github.com/ray-project/ray/blob/master/python/ray/tune/trial_executor.py). This is mainly because TrialExecutors currently assume they can use the entire cluster, but in this case, the lower level experiment can only use a _partition_ of the cluster.
