### ISSUE TITLE
[tune][docs] Search Algorithm Example w/ HyperOpt isn't better than random search

### ISSUE THREAD

**Issue by jonmorton** [ray-project/ray#7907]
The example at https://ray.readthedocs.io/en/latest/tune-tutorial.html#search-algorithms-in-tune for using HyperOpt is not better than random search, according to my understanding.

The default `n_inital_points` for the HyperOpt searcher is `20`, which I think means the first 20 trials are drawn randomly. Since the example in the docs uses `num_samples=10`, this isn't really illustrating search with HyperOpt -- or am I missing somethig?

**Comment by richardliaw** [comment]
Ah yeah the doc was written to illustrate usage, but I didn't carefully check all the parameters. Do you want to push a fix? happy to merge.

**Comment by richardliaw** [comment]
We actually updated the example recently, so this shouldn't be the case anymore.
