### ISSUE TITLE
Failed to put object A in object store because it is full. Object size is B bytes.

### ISSUE THREAD

**Issue by yeshenpy** [ray-project/ray#7908]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray version 0.8.3
Tensorflow version 1.15.0

Recently, I have encountered a very difficult problem and need your help.
My script works every time, but after a while, it appears"Failed to put object A in object store because it is full. Object size is B bytes." the strange thing in this is that when I set lru_evict to False, B will be very large. By doing the work of free memory over and over again,  still end up with a big problem with B.

`   Part of the code

    rollouts = [w.work.remote(weights_id_list[0],weights_id_list[1],num_need) for w in workers]### w is a class which used for collecting data for traning
    red_data = []
    blue_data = []
    race_info = []
    for r in rollouts:
        info = ray.get(r)### get data , info contain image data(84 *84 * n ) and other info
        new_info = np.copy(info)
        del info 
        del r
        red_data.append(new_info[0])
        blue_data.append(new_info[1])
        race_info.append(new_info[2])
    del rollouts
    gc.collect()`# I try to delete for clearing the obj store

B gets really big   lru_evict is False.
`plasma_store_provider.cc:108] Failed to put object aa6988f2b04aa5cd7e0a4dfc010000c801000000 in object store because it is full. Object size is 7194909736 bytes.`

B is normal  lru_evict is True.

`plasma_store_provider.cc:108] Failed to put object d7a28e66380b60e100fbe75e010000c801000000 in object store because it is full. Object size is 6226744224 bytes.. Waiting 1000ms for space to free up...`

However, the following situation can lead to a continuous increase in memory usage.
as a result , this will lead 
 `ray.exceptions.UnreconstructableError: Object 35ff9f488f79b58aad8ff367010000c801000000 is lost (either LRU evicted or deleted by user) and cannot be reconstructed. Try increasing the object store memory available with ray.init(object_store_memory=<bytes>) or setting object store limits with ray.remote(object_store_memory=<bytes>). See also: https://ray.readthedocs.io/en/latest/memory-management.html`

Normally, I thought Ray would clean up the Object store automatically when it was full, but I used the top command and found that all the workers and drivers were taking up more and more memory until they ran out of resources,even though I set object_store_memory and redis_max_memory.

Another question is, can you manually empty the Object store meory?Is there any way to monitor Object Strore memory usage? I didn't find any functions or instructions in the documentation,Perhaps manual release can alleviate the memory increase.

Thanks.

**Comment by rkooo567** [comment]
You can monitor object store memory usage using `ray memory` from Ray 0.8.3.

**Comment by yeshenpy** [comment]
Thanks for your replay .
I'm providing some "ray memory" results, and I'm afraid I have a problem understanding them.
It's basically a cycle .I start 5 Actors to collect Image data . 
The first :
![image](https://user-images.githubusercontent.com/43668853/78560367-9ae68b00-7848-11ea-9875-4f2616b6fdce.png)

the second :
![image](https://user-images.githubusercontent.com/43668853/78560386-9e7a1200-7848-11ea-8bf1-127d740ccad1.png)

or
![image](https://user-images.githubusercontent.com/43668853/78560412-a3d75c80-7848-11ea-9f51-af70d25be7ef.png)

And then we cycle this process

the 595 line is 
` workers = [Worker.remote(i) for i in range(NUM_WORKERS)] # init 5 Actor`
the 565 line is 
`rollouts = [w.work.remote(weights_id_list[0],weights_id_list[1],num_need) for w in workers]  # send arg to work method of Actor`

the 588 line is to get tensorflow graph id 

the 570 line is 
` info = ray.get(r)  # get Image data from work method of 5 Actors `

I've been puzzled by this question for a week.I even added ray.actor.exit_actor() to the Actor to free up resources (at regular intervals), but it still didn't work.

However, I will still encounter the above problems. Is there any problem in my understanding? Looking forward to your reply.

**Comment by robertnishihara** [comment]
What is `info`? My guess is that `new_info = np.copy(info)` is doing a shallow copy as opposed to a deep copy and so the elements of `new_info` still live in the plasma object store.

**Comment by yeshenpy** [comment]
the copy of numpy  is  deep copy ,not a shallow copy , the copy that comes with python is shallow copy . Take a look at the documentation [https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html](url)

**Comment by yeshenpy** [comment]
Thanks for your reply ,
I'll give you some details .Here's the main content of work function , and I've tried to delete everything that can be del  . I try "obj.show_growth()" and "show_most_common_types()"(functions to check for memory leaks)  ,I found that no new objects are found.
 
the self.red_ppo and self.blue_ppo is the attribute of the class (deep nn),Basically this function is play and get play data for training.(mainly collect data and calculate the discount reward)

`    def work(self,ppo_weights_red,ppo_weights_blue, need_num_steps):
    
        gc.collect()
        show_memory_info()
        
 
        self.init_info()
        self.red_ppo.set_weights(ppo_weights_red)
        self.blue_ppo.set_weights(ppo_weights_blue)
        
        del ppo_weights_red
        del ppo_weights_blue
        
        
        buffer_value,buffer_next_value , buffer_done, buffer_s,buffer_next_s, buffer_a, buffer_r =[],[],[], [], [],[], []
        
        while True :
            if self.steps>= need_num_steps:
                break
            s = np.copy(self.env.reset())
            self.observation_s = np.zeros((N_STEP,2,S_DIM),dtype=np.uint8)
            self.observation_s = self.__observation_update([s,s], self.observation_s)
            one_game_num = 0
            one_game_red_reward = 0
            one_game_blue_reward = 0
            step_step = 0
            while True:
                step_step +=1
                red_one = self.red_ppo.choose_action(self.observation_s[:,0,:])
                blue_one = self.blue_ppo.choose_action(self.observation_s[:,1,:])
                #print("red_one :",red_one)
                next_obs,r, self.done  = np.copy(self.env.step(red_one[0],blue_one[0]))
                buffer_done.append(self.done)
                one_game_num += 1
                self.red_one_score += r[0]
                self.blue_one_score += r[1]
                one_game_red_reward += r[0]
                one_game_blue_reward += r[1]
                buffer_s.append([preprocess_state(self.observation_s[:,0,:]),preprocess_state(self.observation_s[:,1,:])])
                buffer_a.append([red_one,blue_one])
                buffer_r.append([r[0],r[1]])
                self.observation_s = self.__observation_update([next_obs,next_obs], self.observation_s)
                # s = get_state(self.env)
                buffer_next_s.append([preprocess_state([self.observation_s[:,0,:]]),preprocess_state([self.observation_s[:,1,:]])])
                self.last_state = [preprocess_state([self.observation_s[:,0,:]]),preprocess_state([self.observation_s[:,1,:]])]
                if self.done :
                    self.game_num += 1
                    tackler_list = self.env.get_tackler_num()
                    self.red_tackler_num +=tackler_list[0]
                    self.blue_tackler_num +=tackler_list[1]

                    self.steps += one_game_num
                    self.red_score_total += one_game_red_reward
                    self.blue_score_total += one_game_blue_reward

                    if self.env.judge_red_win() == 1:
                        self.red_win_num += 1
                    elif self.env.judge_red_win() == -1:
                        self.blue_win_num += 1
                    else:
                        self.tied_num += 1
                    break
        buffer_next_s,buffer_s,buffer_done,buffer_a,buffer_r =np.array(buffer_next_s),np.array(buffer_s),np.array(buffer_done),np.array(buffer_a),np.array(buffer_r)
        for i, ppo in enumerate(self.total_ppo):
            buffer_value.append(np.copy(ppo.get_v(np.reshape(buffer_s[:,i,:],[-1,N_STEP,S_DIM]))[:,0]))
        
        buffer_value = np.array(buffer_value)
        for i, ppo in enumerate(self.total_ppo):
            buffer_next_value.append(np.copy(ppo.get_v(np.reshape(buffer_next_s[:,i,:],[-1,N_STEP,S_DIM]))[:,0]))
        buffer_next_value = np.array(buffer_next_value)
        
        new_buffer_value = []
        for i in range(buffer_value.shape[1]):
            new_buffer_value.append(np.copy(buffer_value[:,i]))
        buffer_value = np.array(new_buffer_value)

        new_buffer_next_value = []
        for i in range(buffer_next_value.shape[1]):
            new_buffer_next_value.append(np.copy(buffer_next_value[:, i]))
        buffer_next_value = np.array(new_buffer_next_value)

        total_steps = len(buffer_s)
        assert  len(buffer_a) == len(buffer_done) == len(buffer_s)


        lastgaelam = [0.0,0.0]

        buffer_adv = []
        for t in reversed(range(total_steps)):
            nextnonterminal = 1.0 - float(buffer_done[t])
            nextvalues = buffer_next_value[t,:]
            delta =  buffer_r[t] + np.asarray(GAMMA) * nextvalues *np.asarray(nextnonterminal) - buffer_value[t,:]
            lastgaelam = delta +np.asarray( GAMMA) * np.asarray(lam) * np.asarray(nextnonterminal) *  np.asarray(lastgaelam)
            buffer_adv.append(np.copy(lastgaelam))
        buffer_adv.reverse()
        buffer_adv = np.array(buffer_adv)
        buffer_returns = buffer_adv + buffer_value
        info = self.total_race_info()

        gc.collect()
        RED_DATA_ONE = np.hstack([buffer_s[:,0],buffer_a[:,0],buffer_returns[:,0][:,None],buffer_adv[:,0][:,None]])
        BLUE_DATA_ONE = np.hstack([buffer_s[:,1],buffer_a[:,1],buffer_returns[:,1][:,None],buffer_adv[:,1][:,None]])
        return [RED_DATA_ONE,BLUE_DATA_ONE,info]`



the show_memory_info function is used to see memory info 
`
def show_memory_info():

    pid = os.getpid()
    p = psutil.Process(pid)
    info = p.memory_full_info()
    u_memory = info.uss/1024./1024
    print(f"{pid} memory used: {u_memory} MB ")`

When I went through this function, I found that the memory was always increasing for a certain number of rounds of initial training.After a certain number of rounds will be relatively stable, the growth rate slows down.
The first data collection:
![image](https://user-images.githubusercontent.com/43668853/78586496-1b6bb280-786e-11ea-9eea-8ad404d74d90.png)

The second data collection:
![image](https://user-images.githubusercontent.com/43668853/78586658-5241c880-786e-11ea-8acb-14419bdfb16c.png)

The Third data collection:
![image](https://user-images.githubusercontent.com/43668853/78586689-6259a800-786e-11ea-8743-788474a3dfa9.png)

The 30th data collection:
![image](https://user-images.githubusercontent.com/43668853/78586764-7f8e7680-786e-11ea-8d4c-b6114607d5d9.png)

I'm not sure why this is the case, but I've been able to delete all the indexes that can be dropped, and the rest are all local variables.

If more detailed information is needed, I can provide it. I hope to get help.

Thanks .

**Comment by wangzelong0663** [comment]
Have you solved your problem? I meet the same problem and still donnot know how to solve it...

**Comment by rkooo567** [comment]
Hey sorry that it was out of my radar. Did you guys figure out the issue?

**Comment by DanielWicz** [comment]
Also I would like to ask the same question, because in my case also the problem is present

**Comment by rkooo567** [comment]
@DanielWicz are you in the public slack channel? I'd like to pair debugging to help you out if it is okay for you (the issue is a bit stale and there are too many scattered information).

**Comment by DanielWicz** [comment]
> @DanielWicz are you in the public slack channel? I'd like to pair debugging to help you out if it is okay for you (the issue is a bit stale and there are too many scattered information).

I'm not, but I didn't know about your Slack's channel. So I'll subscribe meanwhile. Nevertheless, I've solved the problem with issue #9504.

**Comment by rkooo567** [comment]
This issue must not exist in the master anymore because the object spilling is on by default
