### ISSUE TITLE
[docs] Issue on `rllib-env.rst`

### ISSUE THREAD

**Issue by ceteri** [ray-project/ray#7917]
# Documentation Problem/Question/Comment

The discussion about how to "register a custom env creator function" includes a partial source code example that omits some magic. It would likely be better to show actual working sample code. For example, the path to reach a constructor for custom `gym` environment may be difficult to find, and also the way to handle a `config` argument that's shown doesn't appear to work correctly in practice.

Here's a minimal working example:

  - https://github.com/DerwenAI/rllib_tutorials/blob/master/app_triv.ipynb
  
Based on the trival `gym` at <https://github.com/DerwenAI/gym_trivial>

(Created directly from the docs)

**Comment by rkooo567** [comment]
Thanks for reporting this! Please feel free to make the PR!
