### ISSUE TITLE
Ray in Slurm deployment error

### ISSUE THREAD

**Issue by pengyuan-zhou** [ray-project/ray#7933]
Hi guys, 

I've been trying to run Rllib in slurm with multiple nodes, as shown below, I can init the head and
the workers. 

However the program seems to fail immediately after that, caused by this error:

*File "PROGRAM/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known*

I've tried as the suggestions in #6573 but haven't got luck to work it out.

I'm using  ray 0.7.3 and the slurm nodes are running on Centos 7.7.

Any advice would be appreciated.
Thanks.

<pre>
INFO scripts.py:289 -- Using IP address 128.214.XX.XX for this node.
INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
INFO services.py:409 -- Waiting for redis server at 128.214.XX.XX:6379 to respond...
INFO services.py:409 -- Waiting for redis server at 127.0.0.1:6379 to respond...
INFO services.py:409 -- Waiting for redis server at 127.0.0.1:48948 to respond...
INFO services.py:809 -- Starting Redis shard with 10.0 GB max memory.
INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
2020-04-06 09:25:40,964	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
INFO services.py:1476 -- Starting the Plasma object store with 54.04 GB memory using /dev/shm.
INFO scripts.py:319 -- 
Started Ray on this node. You can add additional nodes to the cluster by calling

ray start --redis-address 128.214.XX.XX:6379 --redis-password XXXXXXXXXXXXXXXXXXXXXXXx

from the node you wish to add. You can connect a driver to the cluster from Python by running

import ray
ray.init(redis_address="128.214.XX.XX:6379", redis_password="XXXXXXXXXXXXXXXXXXXXXXXx")

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

ray stop
INFO services.py:414 -- Failed to connect to the redis server, retrying.
INFO services.py:409 -- Waiting for redis server at 128.214.XX.XX:6379 to respond...
INFO scripts.py:363 -- Using IP address 128.214.XX.199 for this node.
INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
2020-04-06 09:25:41,123	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
INFO services.py:1476 -- Starting the Plasma object store with 54.04 GB memory using /dev/shm.
INFO scripts.py:371 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

ray stop
INFO services.py:409 -- Waiting for redis server at 128.214.XX.XX:6379 to respond...
INFO scripts.py:363 -- Using IP address 128.214.XX.200 for this node.
INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
2020-04-06 09:25:42,363	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
INFO services.py:1476 -- Starting the Plasma object store with 54.04 GB memory using /dev/shm.
INFO scripts.py:371 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

ray stop

skip...

INFO services.py:409 -- Waiting for redis server at 128.214.XX.XX:6379 to respond...
INFO scripts.py:363 -- Using IP address 128.214.XX.221 for this node.
INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
2020-04-06 09:27:07,525	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
INFO services.py:1476 -- Starting the Plasma object store with 54.04 GB memory using /dev/shm.
INFO scripts.py:371 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

ray stop
INFO services.py:409 -- Waiting for redis server at 128.214.XX.XX:6379 to respond...
INFO scripts.py:363 -- Using IP address 128.214.XX.222 for this node.
INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-25-40_049064_8595/logs.
2020-04-06 09:27:13,269	WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
INFO services.py:1476 -- Starting the Plasma object store with 54.04 GB memory using /dev/shm.
INFO scripts.py:371 -- 
Started Ray on this node. If you wish to terminate the processes that have been started, run

ray stop
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
PROGRAM/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float3[0m
warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2020-04-06_09-28-02_453911_9098/logs.
INFO services.py:409 -- Waiting for redis server at 127.0.0.1:57253 to respond...
Traceback (most recent call last):
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
sock = self._connect()
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 511, in _connect
socket.SOCK_STREAM):
<b>File "PROGRAM/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known</b>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "PROGRAM/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
connection.send_command(*args)
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
self.send_packed_command(self.pack_command(*args))
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
self.connect()
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to 128.214.XX.XX:6379:57253. Name or service not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
sock = self._connect()
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 511, in _connect
socket.SOCK_STREAM):
File "PROGRAM/lib/python3.6/socket.py", line 745, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train.py", line 282, in <module>
ray.init(num_cpus= num_cpus, node_ip_address=os.environ["ip_head"], object_store_memory=int(9.5**11))
File "PROGRAM/lib/python3.6/site-packages/ray/worker.py", line 1429, in init
head=True, shutdown_at_exit=False, ray_params=ray_params)
File "PROGRAM/lib/python3.6/site-packages/ray/node.py", line 143, in __init__
self.start_head_processes()
File "PROGRAM/lib/python3.6/site-packages/ray/node.py", line 501, in start_head_processes
self.start_redis()
File "PROGRAM/lib/python3.6/site-packages/ray/node.py", line 354, in start_redis
redis_max_memory=self._ray_params.redis_max_memory)
File "PROGRAM/lib/python3.6/site-packages/ray/services.py", line 607, in start_redis
primary_redis_client.set("NumRedisShards", str(num_redis_shards))
File "PROGRAM/lib/python3.6/site-packages/redis/client.py", line 1171, in set
return self.execute_command('SET', *pieces)
File "PROGRAM/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
connection.send_command(*args)
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
self.send_packed_command(self.pack_command(*args))
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
self.connect()
File "PROGRAM/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to 128.214.XX.XX:6379:57253. Name or service not known.
</pre>

**Comment by rkooo567** [comment]
Can you show us logs in a directory, `/tmp/ray/session_2020-04-06_09-28-02_453911_9098/logs/`? It'll be great if you can show us all of them except workers.

**Comment by zpymyyn** [comment]
> Can you show us logs in a directory, `/tmp/ray/session_2020-04-06_09-28-02_453911_9098/logs/`? It'll be great if you can show us all of them except workers.

Hi, unfortunately those files don't exist anymore, could be auto-removed by the system, I'm not sure. 

Is there a way to manually config & change the tmp path for logs? 
Thanks.

**Comment by richardliaw** [comment]
Yeah, there should be a `--temp-dir` or `temp_dir` argument you can set.

**Comment by richardliaw** [comment]
Can you try upgrading Ray to the latest version?

**Comment by zpymyyn** [comment]
> Can you try upgrading Ray to the latest version?

Unfortunately that seems not doable recently, since the program I'm running is dependent on that version of ray

**Comment by zpymyyn** [comment]
> Can you show us logs in a directory, `/tmp/ray/session_2020-04-06_09-28-02_453911_9098/logs/`? It'll be great if you can show us all of them except workers.

Hi, I've changed the log dir as recommended by @richardliaw , the redis.err is iteratively repeating the following error:
```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'requirepass'
Bad directive or wrong number of arguments
```
Other files are empty.
