### ISSUE TITLE
Increasing the number of workers slows down the learning.

### ISSUE THREAD

**Issue by xlnwel** [ray-project/ray#7935]
For the toy example in the end, if I set `n_workers=1`, the printed time is around `.25` on my local machine. If I increase it to 6, the time is around `.35`. Why would the learning time increases as the number of workers increases? (My machine has 6 physical(12 logical) cpus and 1 gpu.)

Also, if I decorate `_learn` with `@tf.function`, I will receive an error message as follows. It seems `tf.function` introduces some locks, but this error does not happen in my real project. How can I get rid of it?

> Traceback (most recent call last):
>   File "ray_test.py", line 89, in <module>
>     main()
>   File "ray_test.py", line 84, in main
>     learner = Learner.remote()
>   File "/home/aptx4869/.conda/envs/drl/lib/python3.7/site-packages/ray/actor.py", line 326, in remote
>     return self._remote(args=args, kwargs=kwargs)
>   File "/home/aptx4869/.conda/envs/drl/lib/python3.7/site-packages/ray/actor.py", line 479, in _remote
>     meta.modified_class, meta.actor_method_names)
>   File "/home/aptx4869/.conda/envs/drl/lib/python3.7/site-packages/ray/function_manager.py", line 578, in export_actor_class
>     "class": pickle.dumps(Class),
>   File "/home/aptx4869/.conda/envs/drl/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 68, in dumps
>     cp.dump(obj)
>   File "/home/aptx4869/.conda/envs/drl/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 557, in dump
>     return Pickler.dump(self, obj)
> TypeError: can't pickle _thread.lock objects

 
```python
import time
import psutil
import ray
import gym
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers


@ray.remote(num_cpus=4, num_gpus=1)
class Learner(tf.Module):
    def __init__(self):
        gpus = tf.config.list_physical_devices('GPU')
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        resources = ray.get_resource_ids()
        cpus = [v[0] for v in resources['CPU']]
        psutil.Process().cpu_affinity(cpus)
        tf.config.threading.set_intra_op_parallelism_threads(4)
        tf.config.threading.set_inter_op_parallelism_threads(4)

        conv2d = lambda *args, **kwargs: layers.TimeDistributed(layers.Conv2D(*args, **kwargs))
        self.conv1 = conv2d(32, 8, strides=4, padding='same')
        self.conv2 = conv2d(64, 4, strides=2, padding='same')
        self.conv3 = conv2d(128, 3, strides=1, padding='same')
        self.conv4 = conv2d(128, 3, strides=1, padding='same')
        self.lstm = layers.LSTM(256, return_sequences=True)
        self.dense1 = layers.Dense(256)
        self.dense2 = layers.Dense(1)
        self.opt = tf.keras.optimizers.Adam(lr=1e-4)
    
    def learn(self):
        for _ in range(10):
            t = time.time()
            for _ in range(10):
                self._learn(tf.random.normal((32, 10, 64, 64, 3)))
            print(f'Time: {time.time() - t}')

    # @tf.function
    def _learn(self, x):
        with tf.GradientTape() as tape:
            x = self.conv1(x)
            x = tf.nn.relu(x)
            x = self.conv2(x)
            x = tf.nn.relu(x)
            x = self.conv3(x)
            x = tf.nn.relu(x)
            x = self.conv4(x)
            x = tf.nn.relu(x)
            shape = tf.concat([tf.shape(x)[:-3], [tf.reduce_prod(x.shape[-3:])]], 0)
            x = tf.reshape(x, shape)
            x = self.lstm(x)
            x = self.dense1(x)
            x = tf.nn.relu(x)
            x = self.dense2(x)

            loss = tf.reduce_mean((x - 1)**2)
        grads = tape.gradient(loss, self.variables)
        self.opt.apply_gradients(zip(grads, self.variables))

@ray.remote(num_cpus=1) 
class Worker(tf.Module):
    def __init__(self):
        resources = ray.get_resource_ids()
        cpus = [v[0] for v in resources['CPU']]
        psutil.Process().cpu_affinity(cpus)
        self.env = gym.make('PongNoFrameskip-v4')

    def start(self):
        env = self.env
        s = env.reset()
        while True:
            s, r, d, _ = env.step(env.action_space.sample())
            if d:
                s = env.reset()

def main():
    ray.init()
    workers = []
    n_workers = 1
    for _ in range(n_workers):
        w = Worker.remote()
        workers.append(w)
        w.start.remote()
    learner = Learner.remote()
    ray.get(learner.learn.remote())
    ray.shutdown()

if __name__ == "__main__":
    main()

```

**Comment by rkooo567** [comment]
Hi, @xlnwel. I have no clue why it slows down, but you can probably check out this page. https://rise.cs.berkeley.edu/blog/ray-tips-for-first-time-users/
