### ISSUE TITLE
[Tune] Why does Tune become slower when using BayesOpt several times by `for` loop?

### ISSUE THREAD

**Issue by Servon-Lee** [ray-project/ray#7937]
I optimize my task by using BayesOpt, running it several times in three ``for`` loops like:
```python
for i in range(7):
    tune.run(..., search_alg=bayesopt, ...)

for i in range(7):
    tune.run(..., search_alg=bayesopt, ...)

for i in range(7):
    tune.run(..., search_alg=bayesopt, ...)
```
The running time is longer and longer, as shown in the figure below:
![image](https://user-images.githubusercontent.com/29559374/78802146-0d459f80-79f0-11ea-8bde-636e28495b7f.png)
The blue line indicates the first for loop, which is reasonable, but the other lines are so strange.  So then I use ``cProfile`` to point out where time was wasted. 

The first for loop:
![image](https://user-images.githubusercontent.com/29559374/78803345-78dc3c80-79f1-11ea-883e-2872be20b6d3.png)
The second for loop:
![image](https://user-images.githubusercontent.com/29559374/78803373-842f6800-79f1-11ea-80f2-2170814fea53.png)
The third for loop:
![image](https://user-images.githubusercontent.com/29559374/78803423-93161a80-79f1-11ea-9e76-a6ecc9cbdbb5.png)
where shows that method ``wait`` of workers wasted lots of time. The three for loops optimize exactly the same task, so who can tell me what's the problem? Thanks in advance.

**Comment by richardliaw** [comment]
Can you provide a reproducible script with a simple trainable (like a trainable that just sleeps?)

I know that `bayesopt` itself can take longer once more points are added; but the time wasted should not be in `wait`...

**Comment by Servon-Lee** [comment]
Please try this!

```python
def ackley(calc_num, x):
    for _ in range(calc_num):
        bias = 0.2
        ave_seq = sum([(i - bias) * (i - bias) for i in x]) / len(x)
        ave_cos = sum([np.cos(2.0 * np.pi * (i - bias)) for i in x]) / len(x)
        value = -20 * np.exp(-0.2 * np.sqrt(ave_seq)) - np.exp(ave_cos) + 20.0 + np.e
    return value

def ackley_objective(config, reporter):
    for i in range(config["iterations"]):
        reporter(
            timesteps_total=i,
            mean_loss=ackley(config["calc_num"], [config["x0"], config["x1"]]))

def foo(calc_num):

    space = {"x0": (-100, 100), "x1": (0, 20)}

    config = {
        "num_samples": 100,
        "config": {
            "iterations": 1,
            "calc_num": calc_num,
        },
        "stop": {
            "timesteps_total": 1
        }
    }

    algo = BayesOptSearch(
        space,
        max_concurrent=8,
        metric="mean_loss",
        mode="min",
        utility_kwargs={
            "kind": "ucb",
            "kappa": 2.5,
            "xi": 0.0
        })

    start_time = time.time()
    run(ackley_objective,
        name="bayesopt",
        search_alg=algo,
        **config)

tune_time_tmp1 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp1 = foo(i)
    print("run first =", i)
    tune_time_tmp1.append(tmp1)

tune_time_tmp2 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp2 = foo(i)
    print("run second =", i)
    tune_time_tmp2.append(tmp2)

tune_time_tmp3 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp3 = foo(i)
    print("run third =", i)
    tune_time_tmp3.append(tmp3)

print(tune_time_tmp1)
print(tune_time_tmp2)
print(tune_time_tmp3)
tune_time = []

for i in range(7):
    tmp = (tune_time_tmp1[i] + tune_time_tmp2[i] + tune_time_tmp3[i]) / 3
    tune_time.append(tmp)
print(tune_time)

import matplotlib.pyplot as plt

x = [1000, 3000, 6000, 10000, 30000, 60000, 100000]

np.savetxt("bayes_time_tmp1.txt", tune_time_tmp1)
np.savetxt("bayes_time_tmp2.txt", tune_time_tmp2)
np.savetxt("bayes_time_tmp3.txt", tune_time_tmp3)

plt.plot(x, tune_time_tmp1, label='bayes_time_tmp1')
plt.plot(x, tune_time_tmp2, label='bayes_time_tmp2')
plt.plot(x, tune_time_tmp3, label='bayes_time_tmp3')
plt.legend()
plt.savefig('bayes_tune_time.png')
```

**Comment by Servon-Lee** [comment]
Hi, there! For this problem, I tried inserting ``ray.shutdown()`` and ``ray.init()`` between ``for`` loops, like:
```python
tune_time_tmp1 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp1 = foo(i)
    print("run first =", i)
    tune_time_tmp1.append(tmp1)

ray.shutdown()
ray.init()

tune_time_tmp2 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp2 = foo(i)
    print("run second =", i)
    tune_time_tmp2.append(tmp2)

ray.shutdown()
ray.init()

tune_time_tmp3 = []
for i in [1000, 3000, 6000, 10000, 30000, 60000, 100000]:
    tmp3 = foo(i)
    print("run third =", i)
    tune_time_tmp3.append(tmp3)
```

Then the problem is gone, so is it possible that too many actors are created but they are not collected? Because I found something in the [document](https://ray.readthedocs.io/en/latest/troubleshooting.html#crashes) as follows:

> **Starting many actors**: Workloads that start a large number of actors all at once may exhibit problems when the processes (or libraries that they use) contend for resources. Similarly, a script that starts many actors over the lifetime of the application will eventually cause the system to run out of file descriptors. This is addressable, but currently we do not garbage collect actor processes until the script finishes.

Thanks for your time :)

**Comment by Servon-Lee** [comment]
@richardliaw

**Comment by richardliaw** [comment]
Ah sorry for not getting back to you. theoretically, at the end of `tune.run` all actors should be removed. It might be a regression...

Does the timing regression still show up if you do not use bayesOptSearch?

**Comment by Servon-Lee** [comment]
Really appreciate your help! I tried ``zoopt`` and ``hyperopt`` search algorithms. Both show up the timing regression. To figure out why this happens, I also checked out CPU load. I found the CPU load would be reducing as training. I think maybe they are related.
