### ISSUE TITLE
[tune] [dashboard] Excessive memory usage in dashboard when old tune results are on disk

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#7944]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray master, Ubuntu

### Reproduction (REQUIRED)

Unfortunately, it's taking too long to recreate the issue, but I believe it can be reproduced by running many Tune jobs locally, then running any Ray script that starts the dashboard. The dashboard then shows results in the Tune tab even though there are no Tune experiments running. Also, the process (`python/ray/dashboard/dashboard.py`) shows a lot of memory usage. When I saw this earlier, the size of `~/ray_results` was in the MBs, but the dashboard was using GBs of RAM.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by stephanie-wang** [comment]
cc @richardliaw @aannadi

**Comment by simon-mo** [comment]
@aannadi It looks like a tensorboard bug https://github.com/tensorflow/tensorboard/issues/766

Can we make tensorboard opt-in? Only when user click "Show Tensorboard", we will issue the request to launch it in the background and open an iframe.

**Comment by richardliaw** [comment]
Should be temporarily closed by #8121
