### ISSUE TITLE
[rllib] Custom environment observations always have the dtype float32

### ISSUE THREAD

**Issue by internetcoffeephone** [ray-project/ray#7946]
ray[rllib] 0.8.3
Python 3.6
tensorflow-gpu 2.1.0

### What is the problem?
When using a custom environment with an observation with a dtype other than float32, e.g. uint8, the observation type is changed to float32. This causes models that expect other data types to fail.

This happens due to a hardcoded float32 in [dynamic_tf_policy.py](https://github.com/ray-project/ray/blob/22ccc43670dac93eb7fe81520a84cf3979d05693/rllib/policy/dynamic_tf_policy.py#L119).

When using a Dict observation space (a set of simpler gym spaces), it also happens in [preprocessors.py](https://github.com/ray-project/ray/blob/5ac5ac9560b1cfa182ed39fcab9931bccaf45bbf/rllib/models/preprocessors.py#L76).

### Reproduction
```
import numpy as np
import ray
from gym.spaces import Box, Dict, Discrete
from ray import tune
from ray.rllib.env import BaseEnv
from ray.rllib.utils import try_import_tf
from ray.tune.registry import register_env

tf = try_import_tf()


class TestEnv(BaseEnv):
    def poll(self):
        return {}, [], [], [], []

    def send_actions(self, action_dict):
        pass

    observation_space = Dict({"curr_obs": Box(low=0, high=255, shape=(1, 1), dtype=np.uint8)})
    action_space = Discrete(1)


def env_creator(_):
    return TestEnv()


env_name = "test_env"
register_env(env_name, env_creator)

ray.init(local_mode=True)
tune.run("PPO", config={"env": env_name})
```

Note: You will have to set the breakpoints in the affected lines yourself. I wanted to provide a simple custom model that takes in only uint8, but couldn't get it to work.

**Comment by internetcoffeephone** [comment]
It seems that incorrect sample dtypes are used in other places as well:
- [~~ModelCatalog~~](https://github.com/ray-project/ray/blob/releases/0.8.5/rllib/models/catalog.py#L214) Solved by https://github.com/ray-project/ray/pull/8424
- [TupleFlatteningPreprocessor](https://github.com/ray-project/ray/blob/releases/0.8.5/rllib/models/preprocessors.py#L198)
- [DictFlatteningPreprocessor](https://github.com/ray-project/ray/blob/releases/0.8.5/rllib/models/preprocessors.py#L231)
- [Deterministic action sampling](https://github.com/ray-project/ray/blob/releases/0.8.5/rllib/models/tf/tf_action_dist.py#L56)
- [Action sampling](https://github.com/ray-project/ray/blob/releases/0.8.5/rllib/models/tf/tf_action_dist.py#L84)
- [Sample batch builder](https://github.com/ray-project/ray/blob/releases/0.8.4/rllib/evaluation/sample_batch_builder.py#L16)

**Comment by internetcoffeephone** [comment]
Comment to remove stale label.

**Comment by internetcoffeephone** [comment]
This comment is to remove the stale label.

**Comment by internetcoffeephone** [comment]
This comment is to remove the stale label.

**Comment by avnishn** [comment]
closing because after running the repro script, it looks like we chased this bug away.
