### ISSUE TITLE
Ray with ssh tunneling

### ISSUE THREAD

**Issue by JanKalkan** [ray-project/ray#7954]
Hi there,

we have a [project](https://github.com/ml-tooling/lazycluster) going on which aims to simplify the cluster setup for various distributed ML frameworks like Dask, hyperopt etc. We heavily leverage ssh tunneling, i.e. ssh port forwarding for this purpose. We would also really like (and already tried) to support Ray as well. But we eventually failed to set up Ray using ssh port forwarding. What we need is a mean to control the used IPs + Ports. We found the arguments for manually setting those, but this did not work, because as far as we could see [127.0.0.1 is always translated to the node IP address](https://github.com/ray-project/ray/blob/061043229f279a3c9d9b1934d62c337f439b0d77/python/ray/services.py#L288). 

Is there any way to setup Ray using ssh tunnels or are you able to provide something here? We would really appreciate your support.

Thank you!

**Comment by rkooo567** [comment]
@wuisawesome

**Comment by wuisawesome** [comment]
Hey @JanKalkan can you describe what you're trying to do in a bit more detail? I'm not sure I understand why translating 127.0.0.1 to the ip address is problematic

**Comment by JanKalkan** [comment]
Hey @wuisawesome,

thanks for taking care. In order to support Ray, we need the possibility to start a Ray cluster using ssh tunnels (i.e. port forwarding) for the communication between the hosts. 

For example, we have 3 hosts (A,B,C). We start the Ray head node on host A and port p1. Additionally, we start one Ray worker node on host B port p2 and one host C port p3. We establish ssh tunnels between the hosts to enable the communication between the Ray entities. **This means that all traffic on host A to the ports 127.0.0.1:p2 and 127.0.0.1:p3 is forwarded to the same ports on the respective hosts.** The traffic on port p1 and p3 on host B is also forwarded to the respective ports on host A and C and so on. Therefore, we are manually setting the node ip address to 127.0.0.1, which gets automatically translated to the external IP of the node. 

Hence, it seems it is not possible to start a Ray cluster using ssh tunnels for the communication at the moment. As far as I understood, this address translation was only implemented as convenience so that the user can just use localhost and does not need to look up the external one itself. Maybe it would be beneficial to not translate an IP address if the user manually passes in an IP address and switch to an implicit translation, what do you think? I am also willing to support here or implement a fix in alignment with you guys.
