### ISSUE TITLE
support mixed precision training with tensorflow policy

### ISSUE THREAD

**Issue by nanxintin** [ray-project/ray#7959]
Hi, do you have any plan to support mixed precision training with tensorflow policy in the rllib?
Thanks.

**Comment by richardliaw** [comment]
Can you talk a bit more about your usecase? How big is the network that you are training?

**Comment by nanxintin** [comment]
Hi @richardliaw, the network is not very big with several Conv and Fully-connected layers. I want to see if there are some differences with the training performance and speed when using mixed precision training.
