### ISSUE TITLE
[ParallelIterator] Cannot pass local iterator into remote function

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#7975]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: lastest master
python: 3.7.4
OS X: 10.15.3

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

```
import ray
from ray.util import iter

@ray.remote
def print_stuff(x):
    print(list(x))

ray.init()
p_iter = iter.from_range(10)
ray.get(print_stuff.remote(p_iter.get_shard(0)))
```

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @amogkam

**Comment by wuisawesome** [comment]
This may have actually been https://github.com/ray-project/ray/issues/5240
