### ISSUE TITLE
 [rllib]How to connect my own environment to rllib？

### ISSUE THREAD

**Issue by GOnion** [ray-project/ray#7996]
I have a simulation environment myself, and I now want to connect it to rllib, so I added a new file named **custom_env** in the env folder, but when I import it in **base_env**, the error  **ModuleNotFoundError: No module named 'ray.rllib.env.xsim_env'** is displayed，So how do I expand my own simulation environment?   What other files should I modify？

**Comment by ttumiel** [comment]
You can set the env by the classname, or if you register the environment with tune you can call it by the string name.

See here for examples, particularly line 72 and 81: https://github.com/ray-project/ray/blob/master/rllib/examples/custom_env.py

**Comment by GOnion** [comment]
@ttumiel ，thanks for the explanation!
