### ISSUE TITLE
[docs] "Testing for C++ development" documentation is broken

### ISSUE THREAD

**Issue by PovelikinRostislav** [ray-project/ray#7999]
### What is the problem?
I've tried to use command from Testing for C++ development documentation page: `bazel test $(bazel query 'kind(cc_test, ...)')` and it doesn't work

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ubuntu 18.04, ray 0.8.4 release tag

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
```
$ TEST_TMPDIR=/rpovelik/bazel-cache bazel test $(bazel query 'kind(cc_test, ...)')
$TEST_TMPDIR defined: output root default is '/rpovelik/bazel-cache/' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
ERROR: error loading package 'deploy/ray-operator': Unable to find package for @bazel_gazelle//:def.bzl: The repository '@bazel_gazelle' could not be resolved.
Loading: 4 packages loaded
    currently loading: deploy/ray-operator/api/v1alpha1 ... (8 packages)
Loading: 4 packages loaded
    currently loading: deploy/ray-operator/api/v1alpha1 ... (8 packages)
$TEST_TMPDIR defined: output root default is '/rpovelik/bazel-cache/' and max_idle_secs default is '15'.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 test targets...
INFO: Deleting stale sandbox base /rpovelik/bazel-cache/_bazel_rpovelik/1f467dedf3fee849bb07e81452d9e8ec/sandbox
INFO: Elapsed time: 0.737s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @simon-mo

**Comment by simon-mo** [comment]
@mehrdadn can you take a look? looks like the real issue is 
```
ERROR: error loading package 'deploy/ray-operator': Unable to find package for @bazel_gazelle//:def.bzl: The repository '@bazel_gazelle' could not be resolved.
```

**Comment by mehrdadn** [comment]
@PovelikinRostislav Operator is a separate workspace . By using `...` you're including more than one workspace. I would suggest `bazel test "//:*"` since that only includes targets in the current workspace. I don't know why Operator is failing unfortunately; it's not something I work on. But I believe this is a known issue (#7257, #6218), so I'll close this one.

@chenk008 would you know why the build fails for Operator? Is it something that can be fixed easily?

**Comment by chenk008** [comment]
> @chenk008 would you know why the build fails for Operator? Is it something that can be fixed easily?

Sorry for missed.I  will take a look
