### ISSUE TITLE
Bad Warning - "A worker died or was killed while executing task" on program exit

### ISSUE THREAD

**Issue by PovelikinRostislav** [ray-project/ray#8000]
### What is the problem?
Each time I run RaySGD samples from [Medium ](https://medium.com/distributed-computing-with-ray/faster-and-cheaper-pytorch-with-raysgd-a5a44d4fd220) post, the sample is finishing with the message that worker has died (44 workers on 1 machine with 44 cores).
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [01:35<00:00,  5.32s/batch, loss=2.11]
{'num_samples': 50028, 'batch_count': 18, 'val_loss': 2.35442571170307, 'last_val_loss': 2.343980312347412, 'val_accuracy': 0.11257695690413369, 'last_val_accuracy': 0.10204081632653061}
2020-04-13 15:35:00,032 WARNING worker.py:1072 -- A worker died or was killed while executing task ffffffffffffffff45b95b1c0100.
success!
```

The same problem for the `train_example.py` from the RaySGD samples but for the workers amount more than one:
```
$ python train_example.py --num-workers 2
2020-04-13 15:49:27,165 INFO resource_spec.py:204 -- Starting Ray with 120.31 GiB memory available for workers and up to 55.56 GiB for objects. You can adjust these settings with ray.init(me
mory=<bytes>, object_store_memory=<bytes>).
2020-04-13 15:49:27,512 INFO services.py:1146 -- View the Ray dashboard at localhost:8265
{'num_samples': 1000, 'epoch': 1, 'batch_count': 125, 'train_loss': 8.86761321914196, 'last_train_loss': 1.8336668014526367}
{'num_samples': 1000, 'epoch': 2, 'batch_count': 125, 'train_loss': 1.0310969891548156, 'last_train_loss': 0.687195897102356}
{'num_samples': 1000, 'epoch': 3, 'batch_count': 125, 'train_loss': 0.3158087512999773, 'last_train_loss': 0.12316954880952835}
{'num_samples': 1000, 'epoch': 4, 'batch_count': 125, 'train_loss': 0.09606185332685709, 'last_train_loss': 0.09029536694288254}
{'num_samples': 1000, 'epoch': 5, 'batch_count': 125, 'train_loss': 0.026974349456839262, 'last_train_loss': 0.017229171469807625}
{'num_samples': 400, 'batch_count': 50, 'val_loss': 0.014072768320329488, 'last_val_loss': 0.010623875074088573, 'val_accuracy': 0.0, 'last_val_accuracy': 0.0}
trained weight:  2.04, bias:  4.77
success!
2020-04-13 15:49:30,516 WARNING worker.py:1072 -- A worker died or was killed while executing task ffffffffffffffff45b95b1c0100.
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.4,
python 3.8
Ubuntu 18.04
PyTorch 1.4.0
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
`python pytorch.py` where `pytorch.py` is a script saved from your [Medium](https://medium.com/distributed-computing-with-ray/faster-and-cheaper-pytorch-with-raysgd-a5a44d4fd220)
OR
`python train_example.py --num-workers 2`
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by PovelikinRostislav** [comment]
`cifar_pytorch_example.py` produces the warning too with 44 workers on 44 cores

**Comment by richardliaw** [comment]
@PovelikinRostislav thank you for opening this issue!

@ericl @edoakes is it possible to remove this warning? It can be quite confusing to users.

**Comment by PovelikinRostislav** [comment]
Hi @richardliaw,
So it's not an issue and the results of the sample are correct?

By the way, this confuses me in addition to `tune_example.py` results with summary table of TERMINATED statuses.

I saw three states of phases: RUNNING, PENDING, TERMINATED. Does TERMINATED mean successfully finished?

**Comment by richardliaw** [comment]
The results of the sample are correct.

In Tune, TERMINATED means successfully finished.

**Comment by PovelikinRostislav** [comment]
@richardliaw, thanks for the explanation!

**Comment by edoakes** [comment]
@richardliaw how are you terminating the actors? I believe this only happens if you use `ray.kill()` or exit the process manually. We could certainly add an API to call from within the actor to prevent the warning from showing up.

**Comment by richardliaw** [comment]
@edoakes we should only be calling `__ray_terminate__` to shutdown actors.

**Comment by edoakes** [comment]
Can you file another issue with a script I can use to reproduce?

**Comment by PovelikinRostislav** [comment]
@edoakes what exactly are you looking for?
I added scripts I used to reproduce in the issue. Basically, I used sgd samples and Medium post sample.
