### ISSUE TITLE
[docs] documentation is not aligned with latest release

### ISSUE THREAD

**Issue by PovelikinRostislav** [ray-project/ray#8001]
### What is the problem?
RaySGD documentation refers to Semantic Segmentation, CIFAR10 RayTune examples, but all mentioned files are absent in ray0.8.4 release tag.
![image](https://user-images.githubusercontent.com/20692004/79122254-e8f71380-7d9f-11ea-8636-171b5a909f96.png)

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.4
Ubuntu 18.04
Torch 1.4.0

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by robertnishihara** [comment]
@PovelikinRostislav the documentation is built from the master branch of Ray. If you install the Ray nightly wheels (see https://docs.ray.io/en/latest/installation.html#latest-snapshots-nightlies), then it should match.

**Comment by PovelikinRostislav** [comment]
Hi @robertnishihara,

Is it a best known method to build doc from master, not the latest released?

I suppose that most of the people uses Ray installing it from the pip, thus expecting the doc to be aligned with it.

**Comment by richardliaw** [comment]
@PovelikinRostislav this is a good suggestion. Let me look into this...

**Comment by richardliaw** [comment]
@PovelikinRostislav - thanks for the suggestion; I've addressed this in #8010.

**Comment by PovelikinRostislav** [comment]
Thanks, it works!
