### ISSUE TITLE
[RLlib] & [Tune] Tensorboard No Longer Works in Ray 0.8.4

### ISSUE THREAD

**Issue by josjo80** [ray-project/ray#8007]
### Tensorboard no longer works in Ray 0.8.4

Linux 18.04
Python 3.6.9
Tensorflow 2.1.0
Tensorflow-gpu 2.1.0
Ray 0.8.4
Tensorboard 2.1.0

I updated my packages to reflect the latest builds but I can no longer see training run results in Tensorboard.  I am not using Tune to perform the training routine.  I'm iterating through the trainer as below (see #6669 ):
```
for i in range(args.num_iters):
    print(pretty_print(ppo_trainer.train()))
```
I followed the release notes from release 0.8.2, issue #6836 , however, after installing `tensorboardX` I still could not see training results.  I then uninstalled `tensorboard`, thinking that there was a namespace clash.  I again entered: ` tensorboard --logdir=~/ray_results --host=0.0.0.0` however I got the following error:
`-bash: /home/johnson/miniconda3/envs/rlenv2/bin/tensorboard: No such file or directory`

I then uninstalled tensorboardX and reinstalled tensorboard 2.1.0 and am back to the original problem that I can't see the training results.

I noticed that when I look at an older training run (using Ray0.8.0) in `~/ray_results/experiment_xxx` it includes a file like the following: `events.out.tfevents.1586553975.cassini`.  Whereas with the updated packages I no long see such a file in the experiment folder.

I have also flipped the flag `"monitor"` to `True` in the config settings per the new release.  That does not appear to help either.

**Comment by richardliaw** [comment]
Hm, so you definitely need TensorboardX. Can you try uninstalling everything (you should have a `tensorboard: No such file...` error), and only  installing `tensorboardX`?
