### ISSUE TITLE
[sgd] Implement Fault Tolerance for Validation

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#8009]
### What is the problem?

`trainer.validate` currently does not use the fault-tolerance code path. We should make sure we have the same code path so that validate doesn't fail during training either.

**Comment by amogkam** [comment]
Closing this as Ray SGD is now deprecated. With Ray Train, all the training logic (both training and validation) are contained in the same function, and there will be fault tolerance when executing this function, so this will no longer be an issue!
