### ISSUE TITLE
[rllib] PPO centralized critic implementation details "truncate_episodes"

### ISSUE THREAD

**Issue by lennardsnoeks** [ray-project/ray#8011]
### What is your question?

For my multi-agent crowd simulation problem, I would like to implement a centralized critic approach for PPO. There are a N pedestrians present in the crowd, and each pedestrian will have a corresponding a policy. 

I was looking at example [https://github.com/ray-project/ray/blob/master/rllib/examples/centralized_critic.py]( https://github.com/ray-project/ray/blob/master/rllib/examples/centralized_critic.py), and it raised some questions.

For the model, should **opp_obs** and **opp_act** contain all observations and actions for N-1 pedestrians in the crowd? Also, should observation and action space be flattened for this? Currently, my obs_space and act_space for 1 pedestrian are: **Tuple(Box(2,), Box(3,21), Box(3,21))** and **Box(2,).** I'm unsure what shape=() would be in those cases.

Also should the number of units for **central_vf_dense** be adjusted, or is it good at 16?

Then for the postprocessing part. Is this also possible to implement for **batch_mode="truncate_episodes"**?
I tried some things in the example code following both the example and the PPO policy code, but I'm unsure how OPPONENT_OBS and such should be handled. Should you just stack the batches in other_agent_batches? How should centralized_critic_postprocessing be adjusted to properly support multiple other agents, and to work for "truncate_episodes" as postprocess_ppo_gae does?

    def postprocess_ppo_gae(policy,
                            sample_batch,
                            other_agent_batches=None,
                            episode=None):
        """Adds the policy logits, VF preds, and advantages to the trajectory."""
    
        completed = sample_batch["dones"][-1]
        if completed:
            last_r = 0.0
        else:
            next_state = []
            for i in range(policy.num_state_tensors()):
                next_state.append([sample_batch["state_out_{}".format(i)][-1]])
            last_r = policy._value(sample_batch[SampleBatch.NEXT_OBS][-1],
                                   sample_batch[SampleBatch.ACTIONS][-1],
                                   sample_batch[SampleBatch.REWARDS][-1],
                                   *next_state)
        batch = compute_advantages(
            sample_batch,
            last_r,
            policy.config["gamma"],
            policy.config["lambda"],
            use_gae=policy.config["use_gae"])
        return batch

    def centralized_critic_postprocessing(policy,
                                          sample_batch,
                                          other_agent_batches=None,
                                          episode=None):
        if policy.loss_initialized():
            assert sample_batch["dones"][-1], \
                "Not implemented for train_batch_mode=truncate_episodes"
            assert other_agent_batches is not None
            [(_, opponent_batch)] = list(other_agent_batches.values())
    
            # also record the opponent obs and actions in the trajectory
            sample_batch[OPPONENT_OBS] = opponent_batch[SampleBatch.CUR_OBS]
            sample_batch[OPPONENT_ACTION] = opponent_batch[SampleBatch.ACTIONS]
    
            # overwrite default VF prediction with the central VF
            sample_batch[SampleBatch.VF_PREDS] = policy.compute_central_vf(
                sample_batch[SampleBatch.CUR_OBS], sample_batch[OPPONENT_OBS],
                sample_batch[OPPONENT_ACTION])
        else:
            # policy hasn't initialized yet, use zeros
            sample_batch[OPPONENT_OBS] = np.zeros_like(
                sample_batch[SampleBatch.CUR_OBS])
            sample_batch[OPPONENT_ACTION] = np.zeros_like(
                sample_batch[SampleBatch.ACTIONS])
            sample_batch[SampleBatch.VF_PREDS] = np.zeros_like(
                sample_batch[SampleBatch.ACTIONS], dtype=np.float32)
    
        train_batch = compute_advantages(
            sample_batch,
            0.0,
            policy.config["gamma"],
            policy.config["lambda"],
            use_gae=policy.config["use_gae"])
        return train_batch

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by josjo80** [comment]
Hi @lennardsnoeks .  A fellow researcher here.  I've implemented multi-agent PPO policies with a centralized critic.  I'll take a stab at some of your questions.

For the model, should opp_obs and opp_act contain all observations and actions for N-1 pedestrians in the crowd?
Yes.  You'll want to take in obs from all other agents in the environment and feed them to the critic.  This will help the critic get the full picture of what is taking place and better estimate the actions of the agent.  I decided to leave out the actions of the other agents, which then turns the critic into a state-value function, V(s) rather than an action value function, Q(s,a).  This was more simple to implement at the time and still appears to enable learning quite well.

Also, should observation and action space be flattened for this? 
Yes.  At worst case if you don't know your input dimension, just put a dimension in there as a placeholder.  You'll get an error something like "Expected input dimension was (W, X) but got (Y,Z)."  Go back to your model definition and plug in (Y,Z).

Also should the number of units for central_vf_dense be adjusted, or is it good at 16?
I used 512 for my model but it will be based on the number of agents in the environment and complexity of the environment.

Below is code used in the forward pass of the model.  You can see that I flattened the inputs for the policy to get the action logits.  For the value function I simply used "obs+flat" which returns all the sub-dictionary observations as a flattened vector:
```
    @override(RecurrentTFModelV2)
    def forward(self, input_dict, state, seq_lens):
        """Adds time dimension to batch before sending inputs to forward_rnn().
        You should implement forward_rnn() in your subclass."""
        action_mask = input_dict["obs"]["action_mask"]
        action_logits, new_state = self.forward_rnn(
            add_time_dimension(tf.concat([input_dict["obs"]["own_obs"],input_dict["obs"]["visibility"]],1), seq_lens), state,
            seq_lens)
        
        action_logits = tf.reshape(action_logits, [-1, self.num_outputs])
        
        # Mask out invalid actions (use tf.float32.min for stability)
        inf_mask = tf.maximum(tf.log(action_mask), tf.float32.min)
        masked_logits = inf_mask + action_logits
        
        # Pass forward through separate value function
        self._value_out, _ = self.value_model({
            "obs": input_dict["obs_flat"]
         }, state, seq_lens)
        
        return masked_logits, new_state
```

I'm not sure about your question of batch_mode="truncate_episodes" for the opponent observations.  Truncating the episodes will lop off then end of the episode sequence that doesn't fit within a "rollout_fragment_length".  So, it will rely on the actual reward at the end of the episode rather than the value function's estimate of it.

**Comment by lennardsnoeks** [comment]
Hi @josjo80, thanks for the answer!

So in the following code. The observation space and action space passed are for a single agent, right. The print results give (128,) for obs en (2,) for action (indeed for a single agent). So should I multiply these amounts by the (number of agents - 1), so it accounts for all other agents? I tried to fill in some shapes but no errors appeared. 

I'm not sure what I should do for the forward method.

Also for the central_value_function method, do I need to adjust the depth for the one-hot encoding?

Sorry if some of these questions are very basic, just can't seem to grasp some stuff.

    class CentralizedCriticModel(TFModelV2):
        def __init__(self, obs_space, action_space, num_outputs, model_config,
                     name):
            super(CentralizedCriticModel, self).__init__(obs_space, action_space, num_outputs, model_config, name)
            # Base of the model
            self.model = FullyConnectedNetwork(obs_space, action_space, num_outputs, model_config, name)
            self.register_variables(self.model.variables())
    
            print(obs_space)
            print(action_space)
            acts_opp_num = (num_agents - 1) * 2
            obs_opp_num = (num_agents - 1) * 128
    
            obs = tf.keras.layers.Input(shape=obs_space.shape, name="obs")
            opp_obs = tf.keras.layers.Input(shape=(obs_opp_num, ), name="opp_obs")
            opp_act = tf.keras.layers.Input(shape=(acts_opp_num, ), name="opp_act")
    
            # Central VF maps (obs, opp_obs, opp_act) -> vf_pred
            concat_obs = tf.keras.layers.Concatenate(axis=1)(
                [obs, opp_obs, opp_act])
            central_vf_dense = tf.keras.layers.Dense(
                256, activation=tf.nn.tanh, name="c_vf_dense")(concat_obs)
            central_vf_out = tf.keras.layers.Dense(
                1, activation=None, name="c_vf_out")(central_vf_dense)
            self.central_vf = tf.keras.Model(
                inputs=[obs, opp_obs, opp_act], outputs=central_vf_out)
            self.register_variables(self.central_vf.variables)
    
        def forward(self, input_dict, state, seq_lens):
            return self.model.forward(input_dict, state, seq_lens)
    
        def central_value_function(self, obs, opponent_obs, opponent_actions):
            return tf.reshape(
                self.central_vf(
                    [obs, opponent_obs,
                     tf.one_hot(opponent_actions, 2)]), [-1])
    
        # not in use, replaced by central_value_function
        def value_function(self):
            return self.model.value_function()

**Comment by lennardsnoeks** [comment]
@ericl would it be possible to make it work for truncate_episodes as well / how would I best approach that?

**Comment by ericl** [comment]
@lennardsnoeks I believe the change you need to make is to compute the estimated value at the end of the trajectory fragment, and then pass it to `last_r` for `compute_advantages()`, i.e., change:

```
    train_batch = compute_advantages(
        sample_batch,
        0.0,
        policy.config["gamma"],
        policy.config["lambda"],
        use_gae=policy.config["use_gae"])
```

to 

```
    value_estimate = [compute it here for the obs at the end of the trajectory]
    train_batch = compute_advantages(
        sample_batch,
        value_estimate,
        policy.config["gamma"],
        policy.config["lambda"],
        use_gae=policy.config["use_gae"])
```

**Comment by josjo80** [comment]
@lennardsnoeks I think you followed the "PPO with centralized critic on two-step game" example whereas I followed the "Centralized critic in env" example.  However, it looks like your input shapes are correct to me.  `acts_opp_num` and `obs_opp_num` are correct.  Forward pass method looks good.  The depth of the one_hot encoding is the length of the action space, so if you have 2 actions you should be good.  Seems like you should be able to train with this model.

**Comment by lennardsnoeks** [comment]
@josjo80 hmm alright thanks! I'll have to adjust some things to the loss and postprocessing parts of my implementation.

@ericl so I just have to compute last_r with the central value function and also put this value in VF_PREDS as follows?

Also does the centralized_critic.py example still work? If I run this and set mode to truncate_episodes, the assert in the postprocessing method is not activated. Also, if I put some print statements in that method, they are never printed?

    def centralized_critic_postprocessing(policy,
                                          sample_batch,
                                          other_agent_batches=None,
                                          episode=None):
        last_r = 0.0
    
        if policy.loss_initialized():
            completed = sample_batch["dones"][-1]
            [(_, opponents_batch)] = list(other_agent_batches.values())
    
            sample_batch[OPPONENT_OBS] = opponents_batch[SampleBatch.CUR_OBS]
            sample_batch[OPPONENT_ACTION] = opponents_batch[SampleBatch.ACTIONS]
    
            if not completed:
                next_state = []
                for i in range(policy.num_state_tensors()):
                    next_state.append([sample_batch["state_out_{}".format(i)][-1]])
    
                last_r = policy.compute_central_vf(sample_batch[SampleBatch.CUR_OBS],
                                                   sample_batch[OPPONENT_OBS],
                                                   sample_batch[OPPONENT_ACTION])
    
                # also record the opponent obs and actions in the trajectory
                sample_batch[OPPONENT_OBS] = opponents_batch[SampleBatch.CUR_OBS]
                sample_batch[OPPONENT_ACTION] = opponents_batch[SampleBatch.ACTIONS]
    
                # overwrite default VF prediction with the central VF
                sample_batch[SampleBatch.VF_PREDS] = last_r
        else:
            # policy hasn't initialized yet, use zeros
            sample_batch[OPPONENT_OBS] = np.zeros_like(
                sample_batch[SampleBatch.CUR_OBS])
            sample_batch[OPPONENT_ACTION] = np.zeros_like(
                sample_batch[SampleBatch.ACTIONS])
            sample_batch[SampleBatch.VF_PREDS] = np.zeros_like(
                sample_batch[SampleBatch.ACTIONS], dtype=np.float32)
    
        train_batch = compute_advantages(
            sample_batch,
            last_r,
            policy.config["gamma"],
            policy.config["lambda"],
            use_gae=policy.config["use_gae"])
        return train_batch

**Comment by lennardsnoeks** [comment]
@ericl The issue that the custom policy was not being used was fixed by using #7855 (however the example code still has the action_space and model_config parameters for the PPOLoss creation that should be removed).

I still have some questions regarding the centralized critic:

* Should I just use compute_central_value to compute last_r as in the code above?
* Then where do I assign SampleBatch[VF_PREDS]? I ask this because if VF_PREDS is assigned as in the code above, compute_advantages will just concatenate the same value in this code:
    
          vpred_t = np.concatenate([rollout[SampleBatch.VF_PREDS], np.array([last_r])])

          delta_t = (traj[SampleBatch.REWARDS] + gamma * vpred_t[1:] - vpred_t[:-1])`


* In the centralized critic, VF_PREDS  is initialized with zeros to the same size as the number of actions (or number of agents?). Also, the result of calling compute_central_value consists of 2 values.  I don't understand quite what each of these values are, does compute_central_value return a value for each agent? Should I take the value meant for the current agent and assign this to last_r and pass this to compute_advantages?

Sorry if these are some beginner questions but I only just started with this and I'm trying to understand and use it.

**Comment by ericl** [comment]
That looks right to me (setting last_r = the central vf prediction). You might want to try TF eager with the use_eager config for debugging / prints.

> Then where do I assign SampleBatch[VF_PREDS]

The `centralized_critic_postprocessing` is already creating this with the frozen central vf predictions from model that computed the action:
```
        # overwrite default VF prediction with the central VF
        sample_batch[SampleBatch.VF_PREDS] = policy.compute_central_vf(
            sample_batch[SampleBatch.CUR_OBS], sample_batch[OPPONENT_OBS],
            sample_batch[OPPONENT_ACTION])
```

I don't think you need to change this part of the code, the only thing missing is setting last_r with the last VF prediction (sample_batch[SampleBatch.VF_PREDS][-1]).

> VF_PREDS is initialized with zeros to the same size as the number of actions

It should just be shape [BATCH, 1] (scalar value to go prediction given state of all agents); the action shape just happens to be this for cartpole. You can also ignore the zero-init code for the most part; that's only needed to infer placeholder shapes for setting up TF graph mode. It's not used during actual training.

**Comment by ericl** [comment]
Maybe check out https://github.com/ray-project/ray/pull/8073/files (seems to train but haven't checked performance).

**Comment by lennardsnoeks** [comment]
@ericl thanks for the explanation!

However, got some more problems.

So I have two continuous action values for each agent, so one hot encoding should not be used logically in my case. If I remove it however, I get an error on shape incompatibility. 

`raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?,) and (?, 2) are incompatible`

When the loss is initialized, the shape mask used to check compatibility is derived from the advantages shape, so I think it is connected to the zero initialization of VF_PREDS. What exactly is the BATCH value? I don't quite understand what you mentioned.  Also was getting "Rollout stack incorrectly!" (before i removed one hot encodig) the first time compute_advantages is called after the zero initialization, so I assume my VF_PREDS zero initialization is wrong.

**Comment by ericl** [comment]
Does this fix to the example clear it up? https://github.com/ray-project/ray/pull/8073/commits/5eb730ddb6bc37f42a071d53df4eefa853996964

The example was misleading before, the action tensor just happened to be the right shape. I switched it to copy the rewards tensor which should be compatibly shaped.

**Comment by lennardsnoeks** [comment]
Thanks! 

I got it to train but it can be very inconsistent. Sometimes my pedestrian agents just stay in the same place, and other times they train normally. Not really sure if its related to the config options I use.

Another issue I found however, is when an agent is done for that episode (he has to wait till all agents are done), he will most likely not have the amount of samples specified, so the following error will be thrown:

`ValueError: Cannot feed value of shape (7, 128) for Tensor 'arg_0:0', which has shape '(10, 128)'
`

I guess this could be fixed by appending zeros to fill up the sample batch? 

Also, when I add more than 2 agents, should using sample_batch[SampleBatch.REWARDS] still hold to fill the VF_PREDS shape? Had some more rollout stack incorrectly errors.

**Comment by asaidarahas** [comment]
Hi @ericl. I am facing a similar issue when feeding the value from `policy.compute_central_vf(sample_batch[SampleBatch.CUR_OBS], sample_batch["opponent_obs"], sample_batch["opponent_action"])` to `sample_batch[SampleBatch.VF_PREDS]` in the above example, adopted for own game setting.
```
sample_batch[SampleBatch.VF_PREDS] = policy.compute_central_vf(
                sample_batch[SampleBatch.CUR_OBS], sample_batch["opponent_obs"],
                sample_batch["opponent_action"])
```
The inconsistency seems to be in the batch size (initially `sample_batch[SampleBatch.VF_PREDS].shape[0]` or `sample_batch[SampleBatch.REWARDS].shape[0]`), which happens to change (not sure why), in my case, as the environment gets reset. However, the shape of `sample_batch[SampleBatch.VF_PREDS]` remains constant hence the error. Apparently, `sample_batch[SampleBatch.VF_PREDS]` is initialized _only once_ in the given example i.e., when the _policy hasn't been initialized yet_.
```
else:
    # Policy hasn't been initialized yet, use zeros.
    sample_batch["opponent_obs"] = np.zeros_like(
        sample_batch[SampleBatch.CUR_OBS])
    sample_batch["opponent_action"] = np.zeros_like(
        sample_batch[SampleBatch.ACTIONS])
    sample_batch[SampleBatch.VF_PREDS] = np.zeros_like(
        sample_batch[SampleBatch.REWARDS], dtype=np.float32)
```  
It makes sense, but is there any workaround to, for example, keep the batch size constant?

**Comment by amadou1998** [comment]
This is somewhat unrelated, but I am looking to dynamically determine the number of agents from the input, or more the input size needed for the critic network. Is there a way to do this?

**Comment by lyzyn** [comment]
> 量恰好是正确的形状。我将其切换为复制奖励张量，该张量应该是兼容

I happen to also want to use centralized critical. I have encountered the same doubts as you. Besides, I am using heterogeneous agents with different numbers of state actions. What should I do?Do you need to set some options to True when using centralized critical? Is there anything similar to centralized_ A setting like cric=True? Or do I just need to write the custom network from the following website into the program? I have been troubled by this recently and look forward to your reply. Thank you!I have just started learning this part. If there are any low-level questions, please forgive me！
https://github.com/ray-project/ray/blob/master/rllib/examples/centralized_critic.py#L242
