### ISSUE TITLE
Locks/Mutexes in ray

### ISSUE THREAD

**Issue by csandmann** [ray-project/ray#8017]
I am finally migrating from `multiprocessing` to `ray` and I am wondering, if and how locks/mutexes are supported.

**Background**
I want to run two functions in parallel *only on the CPU*. However, both functions are doing some work on the GPU, which gets painfully slow if it is shared. Using the `multiprocessing` framework I can mutex the GPU with a `multiprocessing.Lock`, however I have not found a corresponding object in ray. What is recommended way to achieve this? Should I use the `asyncio` framework?

**Comment by rkooo567** [comment]
cc @edoakes

**Comment by ericl** [comment]
Yeah, you can use asyncio actors to implement a lock / semaphore actor around a GPU.

Another approach is to break up the computation into parts and let the Ray scheduler deal with resource acquisition, e.g.:

```
a = cpu_phase.remote()
b = gpu_phase.remote(a)
ray.get(b)
```

or with a persistent GPU actor
```
gpu_actor = GPUActor.remote()
a = cpu_phase.remote()

# in cpu_phase
return gpu_actor.process.remote(a)
```

**Comment by csandmann** [comment]
Thank you so much for the pointers and the quick response. I tried to work with `asyncio.Lock`, but unfortunatly this seems to make problems during serialization. If this should be the wrong approach, I would be glad to know!
I'll try to work around it using your proposed solutions.

**Comment by kostrykin** [comment]
Why have you closed this issue? Can you please share, how you used `asyncio.Lock` in ray?

**Comment by csandmann** [comment]
Due to serialization issues, I was not able to use a `asyncio.Lock` in Ray. Since  `multiprocessing` came with too high of data transfer costs and splitting the code as proposed did not work for my scenario, I decided to port everything to C++.

**Comment by kostrykin** [comment]
FTR, I found two different solutions. I think both require POSIX. The simplest is to use a inter-process mutex:
```python
class SystemMutex:
    def __init__(self, name):
        self.name = name

    def __enter__(self):
        lock_id = hashlib.md5(self.name.encode('utf8')).hexdigest()
        self.fp = open(f'/tmp/.lock-{lock_id}.lck', 'wb')
        fcntl.flock(self.fp.fileno(), fcntl.LOCK_EX)

    def __exit__(self, _type, value, tb):
        fcntl.flock(self.fp.fileno(), fcntl.LOCK_UN)
        self.fp.close()
```
In a ray worker, this can be used as simple as:
```python
import ray, os

@ray.remote
def run_job():
    with SystemMutex('critical-section'):
        print(f'Process {os.getpid()} has exclusive access to the critical section!')
```

The same can also be done using a system-wide semaphore:
```python
import posix_ipc

class SystemSemaphore:
    def __init__(self, name, limit):
        self.name  = name
        self.limit = limit

    def __enter__(self):
        if np.isinf(self.limit):
            self.lock = None
        else:
            kwargs = dict(posix_ipc.O_CREAT, mode=384, initial_value=self.limit)
            self.lock = posix_ipc.Semaphore(f'/{self.name}', **kwargs)
            self.lock.acquire()

    def __exit__(self, _type, value, tb):
        if self.lock is not None:
            self.lock.release()
```
Its usage in a ray worker is just the same:
```python
import ray, os

@ray.remote
def run_job():
    with SystemSemaphore('critical-section', 1):
        print(f'Process {os.getpid()} has exclusive access to the critical section!')
```
Note that for some strange reason I had to use `mode=384` (decimal 384 is octal 600) for `posix_ipc.Semaphore` when using it from inside a ray worker. This keyword argument is not required if the semaphore is used from inside the main process.

Hope this helps someone in the future finding this issue on google (like I did).
