### ISSUE TITLE
num_local_objects grows without bound on 0.8.4 (seems worse than 0.8.2)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8029]
### What is the problem?

Running the ARS script in https://github.com/ray-project/ray/issues/7976 shows that the local object count increases to the millions. This could be one reason for the slowdown. In earlier versions, I also see the count grow, but not as much (80k vs 1.8m).

```
(tensorflow_p36) ubuntu@ip-172-30-2-171:~$ ray stat | grep num_local
2020-04-15 06:03:35,291	INFO scripts.py:933 -- Connecting to Ray instance at 172.30.2.171:52496.
2020-04-15 06:03:35,291	WARNING worker.py:792 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
2020-04-15 06:03:35,361	INFO scripts.py:943 -- Querying raylet 172.30.2.171:45827
    num_local_objects: 1896662
    tags: "JobName:raylet,Version:0.8.4,NodeAddress:172.30.2.171,ValueType:num_local_objects"
    tags: "JobName:raylet,Version:0.8.4,NodeAddress:172.30.2.171,ValueType:num_local_objects"
```

### Reproduction (REQUIRED)
You can reproduce this locally by running `[f.remote() for _ in range(1000)]` where f is a trivial remote function and then using `ray stat | grep num_local`.

**Comment by ericl** [comment]
@stephanie-wang @edoakes this looks like a possible leak in the local memory store / distributed ref counting? What would be a good way to confirm, are there some flags I can flip off?

Note that it takes a few hours for the slowdown to occur so it's somewhat hard to reproduce, though I can provide a running VM for debugging if helpful.

**Comment by stephanie-wang** [comment]
Unfortunately I don't think there's a way to turn off ref counting completely without recompiling, but you might be able to flip this flag to False: https://github.com/ray-project/ray/blob/master/python/ray/_raylet.pyx#L657
