### ISSUE TITLE
Trying to setup Ray on custom cluster using Docker

### ISSUE THREAD

**Issue by LucaCappelletti94** [ray-project/ray#8033]
Hello everyone!

First of all, thank you for creating this truly amazing library.

### What is the problem?
Even though all the cluster nodes are available in the dashboard and do not show any error, executing ray-related python code on the head node makes only the head node available, while on the nodes it starts outputting:

```bash
WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
```

*Ray version and other system information (Python version, TensorFlow version, OS):* 3.6.5, None (not installed at this time), Ubuntu 18.04

### Reproduction
As of the title, I am trying to setup Ray on a custom cluster using Docker containers. The idea is to start getting my feet wet on a small cluster and afterwards when I learn how to use the library, to deploy it on a SLURM cluster ([and I have already seen there is a small tutorial on that](https://ray.readthedocs.io/en/latest/deploying-on-slurm.html)). 

My small setup is detailed [in a repository I have created just for this](https://github.com/LucaCappelletti94/experimenting_on_ray): basically it [uses the docker images as provided from this tutorial for the documentation](https://ray.readthedocs.io/en/latest/installation.html#docker-source-images) and then installs other tools such as byobu mainly for debugging purposes.

After building the [ServerDockerfile](https://github.com/LucaCappelletti94/experimenting_on_ray/blob/master/ServerDockerfile) I launch the container as follows:

```bash
docker run --shm-size=16GB -t --tty --interactive --network host experimenting_on_ray_server
```

From within the container then I launch ray with:

```bash
ray start --head
```

This will output:

```bash
2020-04-15 20:08:05,148	INFO scripts.py:357 -- Using IP address xxx.xxx.xxx.xxx for this node.
2020-04-15 20:08:05,151	INFO resource_spec.py:212 -- Starting Ray with 122.61 GiB memory available for workers and up to 56.56 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-04-15 20:08:05,629	INFO services.py:1148 -- View the Ray dashboard at localhost:8265
2020-04-15 20:08:05,633	WARNING services.py:1470 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 17179869184 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
2020-04-15 20:08:05,669	INFO scripts.py:387 -- 
Started Ray on this node. You can add additional nodes to the cluster by calling

    ray start --address='xxx.xxx.xxx.xxx:53158' --redis-password='5241590000000000'

from the node you wish to add. You can connect a driver to the cluster from Python by running

    import ray
    ray.init(address='auto', redis_password='5241590000000000')

If you have trouble connecting from a different machine, check that your firewall is configured properly. If you wish to terminate the processes that have been started, run

    ray stop
```

Where xxx.xxx.xxx.xxx is the public IP of this machine, as the Docker container has been started with the `--network` option. I cannot figure out why the warning appears, as in the [ray docker tutorial from the documentation](https://ray.readthedocs.io/en/latest/installation.html#docker-source-images) it states `Replace <shm-size> with a limit appropriate for your system, for example 512M or 2G`, and here I am using 16GB. How much should be enough?

At this point, via SSH port forwarding, I can see that the dashboard is online and shows the following:

<img width="1792" alt="Schermata 2020-04-15 alle 22 16 45" src="https://user-images.githubusercontent.com/7738570/79384348-fdd1d380-7f66-11ea-8e9a-187d8dd0d0df.png">

Since it all seems nominal, I proceed to build the [ClientDockerfile](https://github.com/LucaCappelletti94/experimenting_on_ray/blob/master/ClientDockerfile) which at this point is in all intents and purposes identical to the server. Then I start it by running:

```bash
docker run --shm-size=16GB -t --tty --interactive --network host experimenting_on_ray_client
```

Now I can run the command provided in the head node to attach another node to the cluster, hence I execute:

```bash
ray start --address='xxx.xxx.xxx.xxx:53158' --redis-password='5241590000000000'
```

Where again, `xxx.xxx.xxx.xxx` is the public IP of the machine where I am running the head Docker container with the `--network` flag.

This command seems to run successfully: if I go to the dashboard now I can see the second node available. Here `xxx.xxx.xxx.xxx` is the IP of the head node while `yyy.yyy.yyy.yyy` is the IP of the worker node.

<img width="1233" alt="Schermata 2020-04-15 alle 22 23 33" src="https://user-images.githubusercontent.com/7738570/79384803-d6c7d180-7f67-11ea-8a03-0906b03c5edf.png">

Finally, I can try to execute some ray code! So I try to execute [the code provided in the documentation](https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html) and in the head node the following code when executed in a python dashboard:

```python
import ray
ray.init(address='auto', redis_password='5241590000000000')

import time

@ray.remote
def f():
    time.sleep(0.01)
    return ray.services.get_node_ip_address()

# Get a list of the IP addresses of the nodes that have joined the cluster.
set(ray.get([f.remote() for _ in range(1000)]))
```

Outputs:

```bash
{'xxx.xxx.xxx.xxx'}
```

But to my understanding we were expecting:

```bash
{'xxx.xxx.xxx.xxx', 'yyy.yyy.yyy.yyy'}
```

If I run the very same code on the worker node I get a very different output (or more like, a lack of any output). After executing the first two lines:

```python
import ray
ray.init(address='auto', redis_password='5241590000000000')
```

I get:

```bash
2020-04-15 20:29:53,481	WARNING worker.py:785 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
2020-04-15 20:29:53,486	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-15 20:29:54,491	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-15 20:29:55,496	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-15 20:29:56,500	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2020-04-15 20:29:57,505	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ray/python/ray/worker.py", line 802, in init
    connect_only=True)
  File "/ray/python/ray/node.py", line 126, in __init__
    redis_password=self.redis_password)
  File "/ray/python/ray/services.py", line 204, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/ray/python/ray/services.py", line 187, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.
```

No additional information is provided in the dashboard, where everything keeps looking nominal. I have tested the reproducibility of the issue numerous times, while I was hoping to have misconfigured something the local network or for the two docker images. The two docker containers run on two different machines in the same local network, that is with an IP that looks like `same.same.same.different`. 

I have also tried to reproduce the error by running the two dockers on the same machine. The issue appears also within this setting.

What other information may I provide that can be of help?

Again, thank you very much for making this library.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by lizelive** [comment]
I am also effected by this issue.
I was able to connect to ray cluster from command line for whatever reason.
`subprocess.call(('ray','start', '--address=10.0.0.4:6379', '--redis-password=5241590000000000'))`
Maybe that will work for you?

**Comment by ericl** [comment]
Reclassifying as a question since it's not clear the issue is a Ray bug.

**Comment by ijrsvt** [comment]
Hmm, I tried reproducing this and have been unable to get the same bug. I am currently a different error instead. Are you still having this issue on the most up-to-date version of Ray.

The error that I am seeing from calling `ray.init(address='auto', redis_password='524159000000000')` on the client.
```
E0518 23:42:54.422583   308 io.cc:212] Connection to IPC socket failed for pathname /tmp/ray/session_2020-05-18_23-26-23_466696_16/sockets/plasma_store, retrying 80 more times
```
One note: 
The warning about `SHM size` will go away if the space of `/dev/shm` is enough to hold the entire memory store. In your case that would be 56.56 GB as per the second line of output.

Also, when you run it on the same machine, what exactly fails?

**Comment by LucaCappelletti94** [comment]
@ijrsvt It fails with the very same error. I have currently moved to use this directly on SLURM, as I was unable to investigate the nature of the issue further on the Docker containers.

**Comment by ijrsvt** [comment]
@LucaCappelletti94 I tried this on two different AWS machines and was unable to reproduce this bug. The setup was the same as what you had, but the two nodes were able to communicate. You should try installing `apt-get install redis` on the client and seeing if you can connect to Ray's  Redis server using `redis-cli -h <xxx.xxx.xxx.xxx> -p <ray_port_no>` and then running Redis with `redis-cli` and finally authenticating with `auth <password>`.

Also, if you run `ray.nodes()` in ipython, it provides a more detailed output of what nodes are connecting.

**Comment by LucaCappelletti94** [comment]
Thank you @ijrsvt for your time. I will be trying to reproduce again the issue locally and do the tests you have suggested as soon as I get the time.

**Comment by ijrsvt** [comment]
Thanks @LucaCappelletti94 !

**Comment by songpengwei** [comment]
I have the same issue, and I'm sure the firewall was closed and could access the redis in the worker.

**Comment by BrandonEscamilla** [comment]
@songpengwei how did you know if it is the firewall? I have the same issue

**Comment by nirandaperera** [comment]
I am facing the same issue from version from 0.8.2 through 0.8.7

**Comment by muhammadsyahyas** [comment]
Have anybody managed to solve this issue in Linux machine?

**Comment by ijrsvt** [comment]
@muhammadsyahyas What problems are you encountering?

**Comment by chenhai1030** [comment]
I am facing the same issue.

**Comment by chenhai1030** [comment]
run docker  using host network is a solution.

**Comment by colobas** [comment]
I'm still facing this issue, both on 1.11 and 1.12.

One additional thing I noticed was in the `ray_client_server.err` log file:
```
[2022-04-27 08:17:53,088 I 393 573] global_state_accessor.cc:357: This node has an IP address of 172.18.0.6, while we can not found the matched Raylet address. This maybe come from when you connect the Ray cluster with a different IP address or connect a container.
```

The listed IP address is *not* the one I initiated ray with. And it is the container's IP in docker's network interface.
