### ISSUE TITLE
[rllib] free_log_std does not support modelV2?

### ISSUE THREAD

**Issue by Jungdam** [ray-project/ray#8041]
### What is your question?

Previously, free_log_std was supported and was implemented in "rllib/models/model.py".

Now, I was not able to find similar ones anywhere else in "rllib/models/modelv2.py" and its tf and torch extensions. I am curious whether free_log_std was deprecated or was just missing for some reason.

Thanks!

**Comment by ericl** [comment]
This looks like an unintended omission. I'm not sure if this would affect performance much though, since the logstds will still end up learnable, but connected to more units.

**Comment by Jungdam** [comment]
Thank for the reply.

I'll assume our policy is a Gaussian policy.

In theory, there would be similar eventually, however, there are some environments that show differences in performance in practice. The environments affected by the free_log_std option are usually ones that require careful exploration such as physically-simulated agents or robot controls. If logstd depends on the state of agent, the sampled actions could be too aggressive because logstd could be really large at some (unknown) states, which easily gets off the safe action range for agents. So, some of literatures in physically-simulated agents or robot controls reported that using state-independent logstd (like free_log_std) or constant logstd showed better performances. 

I currently implemented state-independent logstd and constant logstd myself, they showed better performances, and the convergences are more stable than state-dependent logstd. 

It would be great if you guys consider that both state-indendent and constant logstd are included as default functionalities in the future.

**Comment by ericl** [comment]
That's a good point. @sven1977 this could be relevant during benchmarking.

**Comment by Jungdam** [comment]
And also it would be good if users can assign the initial values for constant/learnable log_std. 

The implementation existed in the previous version initializes log_std as 0.0, which means 1.0 std and covers approximately 1/4 range given a mean value. In my experience, some environments required more careful exploration by setting lower values than 1.0 std. 

And, I guess that #7923 is probably related to this problem. I also got NaN eventually in my environment when I run the experiment by using state_dependent log_std.

**Comment by MoggeM** [comment]
Did you implement this for rllib? If so, would you mind sharing how you did it?

Im also experiencing NaN problems which I suspect is caused by this.

> I currently implemented state-independent logstd and constant logstd myself, they showed better performances, and the convergences are more stable than state-dependent logstd.

**Comment by MoggeM** [comment]
Just updating that changing to free_log_std solved this for me, having very similar issues as in #7923

**Comment by ericl** [comment]
https://github.com/ray-project/ray/pull/8380/files should fix this, please give it a try!

**Comment by Jungdam** [comment]
Sorry for the late reply. Thanks for adding this and I leave a comment in TF implementation part.
Thanks again!
