### ISSUE TITLE
Ray on Windows

### ISSUE THREAD

**Issue by lefig** [ray-project/ray#8042]
Hi there,

I am struggling to install Ray on Windows with python 3.6.7. Pip does not seem to be able to find a version that fits. And I can't locate any unofficial wheels. 

So my question is - will it be possible to support Windows in a future release?

Thanks in advance

Fig

**Comment by rkooo567** [comment]
cc @mehrdadn

**Comment by mehrdadn** [comment]
Windows support is still under development. Feel free to #631 for updates!

**Comment by robertnishihara** [comment]
For anyone interested in trying out Ray on Windows, we have experimental support now (at least for Ray core and some (but not all) of the libraries).

You can try the nightly wheels at https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies.

**Comment by mehrdadn** [comment]
Please see [#631](/ray-project/ray/issues/631#issuecomment-648980254) for recent updates on Windows support!
