### ISSUE TITLE
[tune] can't pickle _thread.lock objects with TensorFlow 2

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#8047]
### What is the problem?
When running `tune.run` on a method that calls a `tf.function`, I get the following error:
```
  File "cli.py", line 280, in hparams
    mode="min"
  File "...site-packages/ray/tune/tune.py", line 246, in run
    run_identifier = Experiment.register_if_needed(exp)
  File "...site-packages/ray/tune/experiment.py", line 203, in register_if_needed
    register_trainable(name, run_object)
  File "...site-packages/ray/tune/registry.py", line 70, in register_trainable
    _global_registry.register(TRAINABLE_CLASS, name, trainable)
  File "...site-packages/ray/tune/registry.py", line 112, in register
    self._to_flush[(category, key)] = pickle.dumps(value)
  File "...site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "...site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.lock objects
```
- python 3.6.8
- ray 0.8.4
- tensorflow 2.1.0
- macOS 10.15.5 Beta

### Reproduction
```python
import tensorflow as tf
from ray import tune

@tf.function 
def f(x, y): 
    return x ** 2 + y 

def trainable(config):
    avg = tf.math.reduce_mean(f(*config.values()))
    tune.track.log(avg=avg.numpy())

analysis = tune.run(trainable)
```
And I get the same error as above. From the docs, it looks like I need to use Ray actors, but I'm new to Ray so I don't understand where to put them or what they do. 

Note: the following works (excuse the poor formatting, I wrote it in nano):
```python
from ray import tune

def f(x, y):
    return x ** 2 + y

def trainable(config):
    num = f(*config.values())
    tune.track.log(num=num)

analysis = tune.run(trainable, config={'x': tune.grid_search(list(range(4, 6))), 'y': tune.grid_search(list(range(4, 6)))})
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sumanthratna** [comment]
Note: in my project I've switched to autograph with Tensorflow 2 using `tf.function` and I get a different error. It seems like the pickle error is only with eager execution.

**Comment by richardliaw** [comment]
This is because tensorflow can't be easily serialized. 

Consider defining the `f` function inside the trainable.
