### ISSUE TITLE
Need Documentation on Using a remote Cluster

### ISSUE THREAD

**Issue by eaparnell** [ray-project/ray#8054]
This issue has been entered before but I cannot find an answer that works. I have a remote cluster with ports 8000-9000 open. I am using the following to start the head:
```bash
ray start --head --redis-port=8100 --webui-host=0.0.0.0 --redis-shard-ports=8130 --node-manager-port=8110 --object-manager-port=8120
```
I can run jobs locally on the head machine just fine.

However, from my local workstation I get the famous:
2020-04-16 11:00:29,385	WARNING services.py:211 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
Begin
Traceback (most recent call last):
  File "/Users/eaparnell/Documents/python/ray_test.py", line 5, in <module>
    ray.init(address='172.31.20.82:8100', redis_password='5241590000000000')
  File "/usr/local/lib/python3.7/site-packages/ray/worker.py", line 809, in init
    connect_only=True)
  File "/usr/local/lib/python3.7/site-packages/ray/node.py", line 126, in __init__
    redis_password=self.redis_password)
  File "/usr/local/lib/python3.7/site-packages/ray/services.py", line 204, in get_address_info_from_redis
    redis_address, node_ip_address, redis_password=redis_password)
  File "/usr/local/lib/python3.7/site-packages/ray/services.py", line 187, in get_address_info_from_redis_helper
    "Redis has started but no raylets have registered yet.")
RuntimeError: Redis has started but no raylets have registered yet.

python is 3.6.8, ray is 0.8.4. I think we need better doc on this setup (or is it not recommended or supported?). I will volunteer to update the doc if you point me to a working solution.

**Comment by rkooo567** [comment]
Can you show us logs from `/tmp/ray/session_latest/logs/raylet.err` & `raylet.out`?

**Comment by eaparnell** [comment]
raylet.out:
```
I0416 10:58:27.640067 15904 stats.h:62] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
I0416 10:58:27.840943 15904 redis_gcs_client.cc:171] RedisGcsClient Connected.
I0416 10:58:27.853477 15904 grpc_server.cc:64] ObjectManager server started, listening on port 8120.
I0416 10:58:27.856739 15904 grpc_server.cc:64] NodeManager server started, listening on port 8110.
```
raylet.err is empty.
When I run the test, I don't get any additional messages to rayout.out.

**Comment by eaparnell** [comment]
Regarding the stackoverflow reference, when I added another node I too got errors in the logs which basically I interpreted as the head couldn't talk to the worker node, even though the worker showed up on the dashboard. After poking around looking which ports were being used by ray, I changed my firewall config to open ports 30000 to 50000 on the worker node. Then, I was able to execute jobs from head node and have them run on BOTH the head node and worker node(s). 
Again, this leads me to believe that we need to document the ports being used by all the ray processes so that firewalls can be configured appropriately.

**Comment by rkooo567** [comment]
That makes sense. I guess this commit will be able to resolve the issues as well. https://github.com/ray-project/ray/commit/9f751ff8c4d5d3c4282200ca5dfef9b9e5ff60e1 

I definitely agree we should document this part better. I will take a look at writing a doc in the meatime, but please feel free to make a PR for modifying documents

**Comment by rkooo567** [comment]
This will be documented by this issue https://github.com/ray-project/ray/issues/9147
