### ISSUE TITLE
[tests] Github actions should not use wheel

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#8055]
### What is the problem?
Currently, Github action dockers are built off of the latest Ray wheel. We should build Ray from scratch to make sure test failures are caught upon breakage.

cc @simon-mo

**Comment by simon-mo** [comment]
to be clear this was the original implementation in jenkins. You actually want to build it from source?

**Comment by richardliaw** [comment]
I don't think that's true... see this commit before the github actions migration (`run_multi_node_test` is what runs on Ray-PRB):

https://github.com/ray-project/ray/blob/3bd82d0bcde525f47f9b2d04a0e3470204bb216a/ci/jenkins_tests/run_multi_node_tests.sh#L14-L16

and build-docker.sh builds from source:

https://github.com/ray-project/ray/blob/3bd82d0bcde525f47f9b2d04a0e3470204bb216a/build-docker.sh

`run_multi_node_test.sh` then calls `run_tune_test.sh` with the SHA provided:

https://github.com/ray-project/ray/blob/3bd82d0bcde525f47f9b2d04a0e3470204bb216a/ci/jenkins_tests/run_multi_node_tests.sh#L25

Now, `run_tune_test.sh` will only build from wheel _if_ no SHA is provided, which is not the case if you're on Jenkins:

https://github.com/ray-project/ray/blob/3bd82d0bcde525f47f9b2d04a0e3470204bb216a/ci/jenkins_tests/run_tune_tests.sh#L22-L30

**Comment by richardliaw** [comment]
(sorry, it's a bit confusing... feel free to ask questions)

**Comment by simon-mo** [comment]
🤦 i see. oh wow this is complicated.

**Comment by richardliaw** [comment]
@simon-mo sorry - let me know if there's anything I can help with
