### ISSUE TITLE
[rllib] Exported Tensorflow models cannot be served by tensorflow-serving when using DQN with EpsilonGreedy

### ISSUE THREAD

**Issue by 5cp** [ray-project/ray#8062]
### What is the problem?

When training using DQN with EpsilonGreedy exploration, the resulting Tensorflow model fails to load in tensorflow-serving with the following error:
```
2020-04-16 21:25:36.137202: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:333] SavedModel load for tags { serve }; Status: fail: Invalid argument: No OpKernel was registered to support Op 'PyFunc' used by {{node default_policy/PyFunc}}with these attrs: [Tout=[DT_DOUBLE], token="pyfunc_0", _output_shapes=[<unknown>], Tin=[DT_INT32]]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[default_policy/PyFunc]]. Took 37487 microseconds.
```

Changing exploration_type to 'StochasticSampling' results in a Tensorflow model that successfully loads into tensorflow-serving:
```
2020-04-16 21:25:50.590837: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:203] Restoring SavedModel bundle.
2020-04-16 21:25:50.625754: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:333] SavedModel load for tags { serve }; Status: success: OK. Took 75142 microseconds.
```

The issue appears to be related to the use of `tf.py_function` in [Schedule.py](https://github.com/ray-project/ray/blob/master/rllib/utils/schedules/schedule.py#L44). According to the [Tensorflow docs for tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function):

> The body of the function (i.e. func) will not be serialized in a GraphDef. Therefore, you should not use this function if you need to serialize your model and restore it in a different environment.

*Ray version and other system information (Python version, TensorFlow version, OS):*
```
Ray 0.8.2 / Ray 0.8.4 / 0.9.0dev0
Python 3.6.6 :: Anaconda, Inc.
Tensorflow 2.1.0
TensorFlow ModelServer: 2.1.0-rc1+dev.sha.5029f06
Ubuntu 18.04.4 LTS
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
from ray import tune
from ray.rllib.agents.dqn import DQNTrainer, DEFAULT_CONFIG
import tempfile

config = DEFAULT_CONFIG.copy()
good_model_dir = tempfile.NamedTemporaryFile().name + "_good"
bad_model_dir = tempfile.NamedTemporaryFile().name + "_bad"

# Train and export 'bad' model with expected failure:
trainer = DQNTrainer(env="CartPole-v0", config=config)
for it in range(3):
    trainer.train()
trainer.get_policy().export_model(bad_model_dir + "/1")

# Train and export 'good' model with expected success:
config['exploration_config'] = { 'type': 'StochasticSampling' }
trainer = DQNTrainer(env="CartPole-v0", config=config)
for it in range(3):
    trainer.train()
trainer.get_policy().export_model(good_model_dir + "/1")

print("Good model: ", good_model_dir)
print("Bad model: ", bad_model_dir)
```
* Install tensorflow-serving as per https://www.tensorflow.org/tfx/serving/setup
* Run the above reproduction script
* Try the 'good' model:
`tensorflow2_model_server --model_base_path=PATH_TO_GOOD_MODEL`
* Try the 'bad' model:
`tensorflow2_model_server --model_base_path=PATH_TO_BAD_MODEL`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels] <- yes, but reproduction script currently fails because `ray.rllib.execution` appears to be missing from wheel

**Comment by sven1977** [comment]
I see. Sorry about that. We'll try to change this to not use tf.py_function in our Schedules.

**Comment by sven1977** [comment]
I put this on my next sprint to be fixed, starting Monday.

**Comment by sven1977** [comment]
Hey @5cp Could you try it with this PR here?
https://github.com/ray-project/ray/pull/8304
None of our Schedules uses py_function anymore, such that they should all be differentiable now.
Please let me know, if this doesn't fix your issue and feel free to re-open it.
