### ISSUE TITLE
Dashboard uses huge amount of memory

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8078]
### What is the problem?

When I run rllib, the dashboard starts at 5GB of memory used and quickly climbs to >10GB, crashing my machine.

@mitchellstern 

### Reproduction (REQUIRED)
`rllib train --run=APEX --env=CartPole-v0 --config='{"num_gpus": 0, "num_workers": 2, "min_iter_time_s": 5, "timesteps_per_iteration": 1000, "target_network_update_freq": 1000, "learning_starts": 1000}'`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
This issue is redundant with #7944

**Comment by richardliaw** [comment]
(feel free to reopen if different; I've moved the labels over, and there is an open PR addressing it.)
