### ISSUE TITLE
[tune] [documentation] Installation instructions for dragonfly are incorrect

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#8084]
https://github.com/dragonfly/dragonfly/blob/master/docs/install.md says dragonfly should be installed via `pip install dragonfly-opt`. 

https://ray.readthedocs.io/en/latest/tune-searchalg.html#dragonfly-search says dragonfly should be installed via `pip install dragonfly`. Further, `pip install dragonfly` errors due to a syntax error in a file imported in `setup.py`.

**Comment by richardliaw** [comment]
Thanks for the catch, @sumanthratna -- would you be open to pushing a small fix?

**Comment by sumanthratna** [comment]
Yup, I'll do that now!

**Comment by richardliaw** [comment]
thanks!
