### ISSUE TITLE
Automatic cluster setup issue 

### ISSUE THREAD

**Issue by aneesh3397** [ray-project/ray#8089]
**System info:**

ray version: 0.8.4
python version: 3.8
OSX version: 10.14.5

New Ray user here, I am trying to follow the tutorial on setting up a ray cluster on AWS (https://ray.readthedocs.io/en/latest/autoscaling.html). The ray up command works fine, I am able to ssh into the cluster as well as run commands remotely. I can even see the ec2 instance that is created on my ec2 dashboard. However when I try running a python script with ray.init(address='auto') I get the following error:

**ConnectionError: Could not find any running Ray instance. Please specify the one to connect to by setting `address`.**

I tried manually entering the address as well but I get timed out. Any ideas on what might be causing this behavior? 

Thanks!

**Comment by anabranch** [comment]
It seems like you're running that script on your local machine, not on the cluster. Are you running it on that instance or your local machine?

**Comment by aneesh3397** [comment]
I see, that was indeed the issue. Thanks for the quick response!
