### ISSUE TITLE
[rllib] What's the default optimizer for PPO?

### ISSUE THREAD

**Issue by KarlXing** [ray-project/ray#8091]
### What's the default optimizer for PPO and How to change it?
Hi,  I'm new to Ray/rllib. I'm trying to run PPO algorithms, but didn't find the way to set optimizer type such as adam or rmsprop after checking the common config and default ppo config. Could someone please help to point out where it is set and how to change it?

I'm now using Ray 0.8.4. Thanks.

**Comment by skkuai** [comment]
I think I found it. The default optimizer is Adam.

ray > rllib > policy > torch_policy.py

`@DeveloperAPI
    def optimizer(
            self
    ) -> Union[List["torch.optim.Optimizer"], "torch.optim.Optimizer"]:
        """Custom the local PyTorch optimizer(s) to use.

        Returns:
            The local PyTorch optimizer(s) to use for this Policy.
        """
        if hasattr(self, "config"):
            optimizers = [
                torch.optim.Adam(
                    self.model.parameters(), lr=self.config["lr"])
            ]
        else:
            optimizers = [torch.optim.Adam(self.model.parameters())]
        if getattr(self, "exploration", None):
            optimizers = self.exploration.get_exploration_optimizer(optimizers)
        return optimizers`
