### ISSUE TITLE
[tune] Save and resume training

### ISSUE THREAD

**Issue by zefang-shen** [ray-project/ray#8096]
### What is your question?
Are there any ways to save a training and resume it later? I tried _save() and _store() in a Trainable but it didn't work.

*Ray 0.84 and other system information (Python 3.6, TensorFlow 2.2, Ubuntu 18.04):

**Comment by richardliaw** [comment]
Turn on `checkpoint_at_end`. This is for `tune.run` right?

**Comment by ZefangShen** [comment]
Thanks Richard,
After I set checkpoint_at_end=True, I got the following error. And the trials are not able to run correctly. 

![image](https://user-images.githubusercontent.com/56578912/79812874-b30feb80-83ac-11ea-9082-15bbffd92f9e.png)

By the way, what's the difference between num_samples and interactions in Tune? I am using tune with hyperopt, do I only need to set num_samples? Thanks
