### ISSUE TITLE
GcsServerAddress error

### ISSUE THREAD

**Issue by pmacalpine** [ray-project/ray#8112]
### What is the problem?
When I try and run anything I get the following error:
```
F0420 23:07:59.585644 78855 service_based_gcs_client.cc:89]  Check failed: num_attempts < RayConfig::instance().gcs_service_connect_retries() No entry found for GcsServerAddress
*** Check failure stack trace: ***
    @     0x7f1b5fd568ed  google::LogMessage::Fail()
    @     0x7f1b5fd57d5c  google::LogMessage::SendToLog()
    @     0x7f1b5fd565c9  google::LogMessage::Flush()
    @     0x7f1b5fd567e1  google::LogMessage::~LogMessage()
    @     0x7f1b5fae14c9  ray::RayLog::~RayLog()
    @     0x7f1b5f90339a  ray::gcs::ServiceBasedGcsClient::GetGcsServerAddressFromRedis()
    @     0x7f1b5f9037dd  ray::gcs::ServiceBasedGcsClient::Connect()
    @     0x7f1b5f8a23e3  ray::CoreWorker::CoreWorker()
    @     0x7f1b5f8a61e4  ray::CoreWorkerProcess::CreateWorker()
    @     0x7f1b5f8a675b  ray::CoreWorkerProcess::CoreWorkerProcess()
    @     0x7f1b5f8a6c5b  ray::CoreWorkerProcess::Initialize()
    @     0x7f1b5f81e594  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
    @     0x7f1b5f81f675  __pyx_tp_new_3ray_7_raylet_CoreWorker()
    @     0x55b34b5d7dc9  _PyObject_FastCallKeywords
    @     0x55b34b627e8f  _PyEval_EvalFrameDefault
    @     0x55b34b57d030  _PyEval_EvalCodeWithName
    @     0x55b34b5c2917  _PyFunction_FastCallKeywords
    @     0x55b34b6240a6  _PyEval_EvalFrameDefault
    @     0x55b34b5c24fb  function_code_fastcall
    @     0x55b34b6276c9  _PyEval_EvalFrameDefault
    @     0x55b34b57c6f9  _PyEval_EvalCodeWithName
    @     0x55b34b57d5f4  PyEval_EvalCodeEx
    @     0x55b34b57d61c  PyEval_EvalCode
    @     0x55b34b67e974  run_mod
    @     0x55b34b688cf1  PyRun_FileExFlags
    @     0x55b34b688ee3  PyRun_SimpleFileExFlags
    @     0x55b34b689f95  pymain_main
    @     0x55b34b68a0bc  _Py_UnixMain
    @     0x7f1b727b5830  __libc_start_main
    @     0x55b34b632990  (unknown)
Aborted (core dumped)
```

This problem appears to have been caused by #7842 (that's the commit where I first see this problem).

*Ray version and other system information (Python version, TensorFlow version, OS):*
Running on Azure NC6s_v2 machine
ray: 0.9.0.dev0 (latest wheels installed on 4/20/20)
python: 3.7.6 (also saw with 3.6)
tensorflow: 2.1
torch: 1.4.0
OS: Ubuntu 16.04.6 LTS

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Whenever I try and run anything I seem to get this error such as
```
python ray/rllib/examples/custom_env.py
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ffbin** [comment]
@pmacalpine Hi, I can run "python ray/rllib/examples/custom_env.py" successfully on mac, Can this problem be replicated on Mac? And can you show me the gcs_server.err and gcs_server.out, thanks.

**Comment by pmacalpine** [comment]
I don't have a mac to run things on, only linux.  This failure happens during ray.init(), and I don't see any logs being written out (nothing in ray_results).  Where would I find gcs_server.* assuming they are written somewhere?

**Comment by ffbin** [comment]
@pmacalpine Hi, we can find logs in /tmp/ray/session_latest/logs, thanks

**Comment by pmacalpine** [comment]
Got it, here are all the logs: [logs.tar.gz](https://github.com/ray-project/ray/files/4508340/logs.tar.gz)

**Comment by ffbin** [comment]
@pmacalpine 
Hi, I guess connect google public DNS server may take a long time, which a timeout needs to be set. Can you ping 8.8.8.8 in your linux machine?
![image](https://user-images.githubusercontent.com/13081808/79840664-c9d43380-83e8-11ea-9e76-8fc93ab73ba3.png)

**Comment by pmacalpine** [comment]
It's taking less than 10ms to ping 8.8.8.8.
```
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=48 time=6.54 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=48 time=5.84 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=48 time=6.57 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=48 time=8.25 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=48 time=5.87 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=48 time=5.73 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=48 time=5.76 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=48 time=5.84 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=48 time=5.88 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=48 time=7.05 ms
--- 8.8.8.8 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9015ms
rtt min/avg/max/mdev = 5.731/6.336/8.252/0.773 ms
```

**Comment by ffbin** [comment]
Hi, @pmacalpine Can you help add some logs and run again, i am confused that if your linux machine ping 8.8.8.8 successfully, it will get local ip and set it to redis. But now i can not find "Gcs server address =" log. Thanks.
![image](https://user-images.githubusercontent.com/13081808/79852563-669ecd00-83f9-11ea-9dd1-d2d7f29ac56e.png)

**Comment by pmacalpine** [comment]
It doesn't reach the code you want to add logging to.
Basically it fails with this [check](https://github.com/ray-project/ray/blob/fa7eecf48a208329c0d42d0329be9b14ec023dad/src/ray/gcs/gcs_client/service_based_gcs_client.cc#L89) while still within socket.connect() and then is done.  I've tried increasing the timeout and number of retries but that didn't help.

**Comment by ffbin** [comment]
@pmacalpine I think the reason for the failure is that socket.connect will block until the connection is successfully made or an error occurs. We should use AsyncClient to connect instead of socket.connect. Can you help try again? Thanks.

**Comment by pmacalpine** [comment]
Using AsyncClient doesn't block and looks to fix to the problem!  I hacked some code together that works for my case, but if you can send me code that still works for the mac case I can test it on my linux system.

**Comment by ffbin** [comment]
@pmacalpine Hi, i have submit fix PR, https://github.com/ray-project/ray/pull/8126 pls help check it, Thanks.

**Comment by pmacalpine** [comment]
Your change causes the gcs server address to be 127.0.0.1 which I guess runs, but is not the same as the previous behavior which used the machine's ip address.   The reason for this is that the error code [here](https://github.com/ant-tech-alliance/ray/blob/b098cd2e4c9b223ec08f1aae13f02b383ad1efd1/src/ray/common/network_util.h#L125) is `system:0` and not `boost::system::errc::host_unreachable`, and so the original code to look up the machine's ip address that still works is not run.

**Comment by ffbin** [comment]
@pmacalpine I think we need to check whether the connection times out or the error code is host_unreachable, resolve local ip is required in both cases. What's your suggestion? Thanks

**Comment by pmacalpine** [comment]
I'm really not sure as the the error code is system:0 which I think means success.  Note that is_timeout is set to true in AsyncClient, however that value is not reported outside the class.  Maybe you could report the is_timeout value and then use that as an indicator of whether to resolve the local ip.

**Comment by ffbin** [comment]
Hi, i have get the is_timeout value from AsyncClient, thanks.

**Comment by pmacalpine** [comment]
This code works for me now with the machine's ip being resolved correctly.  Thanks!
