### ISSUE TITLE
Control timeout and number of reconnection-attempts for Redis

### ISSUE THREAD

**Issue by Kuurusch** [ray-project/ray#8130]
Hallo, 

As I mentioned concerning the Bug https://github.com/ray-project/ray/issues/8080 and even if it seems to be fixed in Ray 0.8.4, it would be helpful to control the timeout and the number of reconnection-attempts, in case it still happens. Because as I also described there, it actually still happens, only that the currently apparently fixed number of reconnection attempts was sufficient in my case.

**Comment by richardliaw** [comment]
We added this recently -- should be fixed on master.
