### ISSUE TITLE
Make warning through logging not print

### ISSUE THREAD

**Issue by nmatthews-asapp** [ray-project/ray#8136]
https://github.com/ray-project/ray/blob/89aa47012a2e77c7ddcf5b82e1dcdb2fd1d0bed1/python/ray/memory_monitor.py#L95

Current behavior: the statement referenced prints out a warning message that you need psutil very time you run ray (usually multiple times a run). This can't be filtered because a print statement is used.

Proposed solution: log this warning with warnings.warn or logger.warn so that the logging level is taken into account. Unless a user is debugging they often would like to see only logs at level ERROR=40 or above, especially in the console.

**Comment by richardliaw** [comment]
This sounds good to me. Can you push a draft PR with the changes you want to see? 

I can help clean up the PR and get it to pass tests.

**Comment by nmatthews-asapp** [comment]
done.

(apologies, I forgot to open it as a "draft pr" but hopefully that's not too big of deal!)

**Comment by richardliaw** [comment]
No problem. Merged - thanks a bunch!
