### ISSUE TITLE
How to access last step observation in `on_episode_step` callback? [rllib] [tune]

### ISSUE THREAD

**Issue by vivecalindahlericsson** [ray-project/ray#8142]
### What is your question?

I have a multiagent system where not all agents return observables at each `step()`. I want to write a callback function to log the mean of the observables, following `rllib/examples/custom_metrics_and_callbacks.py`. However, from the `info` arg I can only get the last observation of each agent and it is not reset at each step AFAICT. To be able to calculate the mean I would therefore have to detect a _change_ in the observation to see if that agent got a new sample in that step. This would also only count two identical samples in a row as one. 

The `info['env']` object doesn't look like it's useful either, since it doesn't keep the last observation.

I could of course add information about which agents got new samples to the `info` return dict of `step`() but I'd rather not modify the env.

Is there a better way to achieve what I want?

-- Viveca

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by ericl** [comment]
You should have a handle to the "episode" object, which has methods to get other state such as the last obs of other agents: https://github.com/ray-project/ray/blob/master/rllib/evaluation/episode.py

**Comment by vivecalindahlericsson** [comment]
I wasn't asking for the last obs of the agent, but the obs of the last step. Assuming this is not possible then?

**Comment by ericl** [comment]
Hmm more historical steps should be stored in the batch builder of the
episode object. It should always be accessible in complete episodes mode.

I would also consider changing the env to add this as part of the
observation straight out if needed.

**Comment by vivecalindahlericsson** [comment]
Ok, I didn't have a look at the batch builder yet. In the end I added a variable in the env, `env.last_agent_ids`. Nonetheless, averages of observations for the general multiagent case seems like a reasonable feature to support as this is the direct generalization of the [custom metrics example](ray/rllib/examples/custom_metrics_and_callbacks.py). Currently, a naive change of `env` to a `multiagentenv` for that example only works correctly for agents that report observations at regular step intervals (or else certain observations will get larger weight in the average). But perhaps this is the most common case.

**Comment by trevor-a-mccants** [comment]
Where did the `episode.last_observation_for` function go in episode_v2? I want to do the same thing as this thread is suggesting, but I feel like the answer has changed with the new version.
