### ISSUE TITLE
[tune]add 'last-n-avg' option for scope parameter in get_best_* methods

### ISSUE THREAD

**Issue by cocorosiekz** [ray-project/ray#8147]
### Describe your feature request
As described in the [Google Groups](https://mail.google.com/mail/u/0/#inbox/FMfcgxwHMZGcqCZltQQjfxMpKMWpXKdK), it makes sense to evaluate model on every batch of time series data (like _hour-01, hour-02, ..., hour-23_) when we are doing some online learning stuff (for example ads\feeds recommending).
When dealing with such situation, it's better to take **average of last n or all** steps' metric of one trial into consideration when we are retrieving the best trial.
So I sugguest add **'avg'**, **'last-n-avg'** options to the **scope** parameter in following methods

- ray.tune.ExperimentAnalysis.get_best_trial
- ray.tune.ExperimentAnalysis.get_best_config
- ray.tune.ExperimentAnalysis.get_best_logdir

**Comment by richardliaw** [comment]
cc @krfricke

**Comment by richardliaw** [comment]
@cocorosiekz we've just merged `avg`. Working on `last-n-avg` next.

**Comment by krfricke** [comment]
I added a PR for `last-5-avg` and `last-10-avg`. These n are currently hardcoded to avoid tinkering with the `Trial` object and the `run` API too much. @cocorosiekz is this useful for you, or do you need more control over the number of steps to consider?

**Comment by cocorosiekz** [comment]
hi @krfricke , I think `last-5-avg` and `last-10-avg` is enough for my use cases. Maybe we can take more control in the future if there's more need from other users.

**Comment by richardliaw** [comment]
This is addressed in #8731
