### ISSUE TITLE
Enabling Tune Tab in Dashboard

### ISSUE THREAD

**Issue by athenawisdoms** [ray-project/ray#8148]
Hello, when I visit the web dashboard when the Tune trials are running, the _Tune_ tab is not seen. How can we enable it? I am using tune 0.8.4 installed using `conda`.

Thank you!

```
ray.init()
analysis = tune.run(
    train_mnist, config={"lr": tune.grid_search([0.001, 0.01, 0.1])})
```

**Obtained:**

![image](https://user-images.githubusercontent.com/6615285/80120363-dd061100-8558-11ea-8074-e0a836f7767c.png)

**Expected:**

![image](https://user-images.githubusercontent.com/6615285/80120401-eb542d00-8558-11ea-9a62-db8463ca2030.png)

**Comment by rkooo567** [comment]
Can you make sure you have tensorboard as dependency?

**Comment by richardliaw** [comment]
Also, do you have any files at ~/ray_results?
