### ISSUE TITLE
How to place workers onto specific GPU in heterogenous environments?

### ISSUE THREAD

**Issue by neuronflow** [ray-project/ray#8163]
### What is your question?
Hi I have multiple systems with diverse hardware in my portfolio. For example this system with 3 GPUs.

Cuda device 0 has 1gb VRAM
Cuda device 1 has 16gb VRAM
Cuda device 2 has 48gb VRAM

How can I configure ray to only do calculations on cuda devices 1 and 2?

My current example model has a size of 11gb. So I can load it once on Cuda device 1 but four times on cuda device 2. How to configure for this with the fractional gpus?
Is there a way to allocate memory on an absolute gb scale?
Or is there a flag so ray automatically figures out the paralellization under the hood?

I had an intense look through the docs but failed to understand:
https://ray.readthedocs.io/en/latest/using-ray-with-gpus.html#fractional-gpus

*Ray version and other system information (Python version, TensorFlow version, OS):*
latest

**Comment by rkooo567** [comment]
Ray doesn't innately support this for now. (It currently does not support resource isolation). You should probably find a way to pin each task to GPU. For example, when you want to pin CPU, you can do sth like this https://stackoverflow.com/questions/61051911/how-to-ensure-each-worker-use-exactly-one-cpu. (I am not that familiar with GPU, but I assume there should be a  way to do). @robertnishihara Do you know any way to do this?

**Comment by alvitawa** [comment]
Has this now become possible?
For instance, can I specify how much vram a task needs such that ray reserves that amount on a given gpu?
