### ISSUE TITLE
[Ray general] Tons of irrelevant messages are sent to nodes very frequently once starting ray on cluster.

### ISSUE THREAD

**Issue by Servon-Lee** [ray-project/ray#8166]
### What is your question? 
When I use ``ray start --head --redis-port=6379`` to start Ray on a head node (IP: 10.188) and then run ``ray start --address='192.168.10.188:6379' --redis-password='5241590000000000'`` on other two nodes (IP: 10.94 and 10.181), I notice something like this photo below where I captured some packets:
![image](https://user-images.githubusercontent.com/29559374/80221127-71669580-8677-11ea-81f2-38a1603db58f.png)

My first question is why the head node (IP: 10.188) sends to 10.94 packets that include info for 10.181? And this also happens on those packets sent to 10.188 but include info for 10.94.

My second question is who and why a head node always sends this kind of ``message`` to all nodes within a very short time even though there's no one task?  What's the meaning of these messages?
![q2](https://user-images.githubusercontent.com/29559374/80222841-01a5da00-867a-11ea-9e7f-885451c004f2.jpg)

I guess this may be a polling mechanism, but why this need to do that so frequently?

In my test, I tried to connect 500 private nodes to one head node, and then they consumed lots of network bandwidth. As I said, tons of irrelevant messages were sent to nodes very frequently.

Any help is really appreciated.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.4  Python 3.6.9

**Comment by rkooo567** [comment]
Hi, @Servon-Lee ! Would you mind sharing your discovery here? It'll be great for future users who will encounter the same question!

**Comment by Servon-Lee** [comment]
The problem I found is that lots of network resources will be used when I connect 512 worker nodes to a head node without running any task, i.e., running ``ray start --head --redis-port=6379`` at the head node (10.188) and ``ray start --address='192.168.10.188:6379' --redis-password='5241590000000000'`` at other nodes.

As the number of nodes increases, the network traffic is used like the following pic.

![image](https://user-images.githubusercontent.com/29559374/80669433-0386f780-8ad7-11ea-8d1e-3aab6b6cb63a.png)

Besides those tests mentioned at first, I figured out that those messages are sent by redis-server via port 6379.

![image](https://user-images.githubusercontent.com/29559374/80669765-c3744480-8ad7-11ea-879f-ebab2ccb2421.png)

Inspired by @rkooo567, I think the problem is the ``raylet_monitor`` process. When I kill this process, the below messages will disappear (head node no longer transmit messages to other nodes), **BUT if starting tasks, they cannot be scheduled properly.**

![image](https://user-images.githubusercontent.com/29559374/80670783-6d54d080-8ada-11ea-9d7d-d5520d848cdc.png)

I also tried disabling the dashboard by ``ray start --head --redis-port=6379 --include-webui=False`` at the head node, but it doesn't work.

I guess it's because worker nodes need to get info of all other nodes via GCS for scheduling? I'm not that familiar with GCS as well as Redis, so don't hesitate to tell me if there is anything wrong.

Any help would be appreciated! @rkooo567 @richardliaw @edoakes @stephanie-wang

**Comment by Servon-Lee** [comment]
Thanks a ton! I think that's what I'm looking for. But can I change ``raylet_heartbeat_timeout_milliseconds`` in CLI?  For now, I have to connect all nodes through CLI and then run ray init()...

**Comment by stephanie-wang** [comment]
Yes, you can do that! It's a bit ugly, but you just have to pass in a flag like this to the `ray start` command (make sure to do it on both the head and worker nodes):
```
ray start --internal-config="{\"raylet_heartbeat_timeout_milliseconds\":1000}"
```

**Comment by Servon-Lee** [comment]
COOL!!! It works! Thank u so much!

**Comment by Servon-Lee** [comment]
@stephanie-wang Hi Stephanie, long time no see. The args `--internal-config` and `--memory` have been deprecated in Ray 1.0, how can I do something like:
```
ray start --internal-config="{\"raylet_heartbeat_timeout_milliseconds\":1000}"
```

**Comment by edoakes** [comment]
@Servon-Lee `--internal-config` was renamed to `--system-config`

**Comment by mirekphd** [comment]
Note that since July 2021 this exact setting of 1000 ms won't work, as it was hard-coded as a new default in order to reduce pressure on the GCS server:
https://github.com/ray-project/ray/commit/ef195e5108effd9afb857d7ea02c359c8dd614d6#diff-66e8718c71d8ec5383a5cc83b0ade4d1aa8bad17d7ced811928bb666b4b63165L30

See also the reasoning:
https://github.com/ray-project/ray/pull/14203#issuecomment-802449550

**Comment by mirekphd** [comment]
And this is some explanation why the undocumented `ray start --system-config` (still) works:
https://github.com/ray-project/ray/pull/13860#issuecomment-1236303419
