### ISSUE TITLE
Questions about cluster setup and dependencies on Ray?

### ISSUE THREAD

**Issue by gimzmoe** [ray-project/ray#8167]
cluster setup

### What is your question?
I've been excited to use Ray, and perhaps I got ahead of myself.  I've noticed there are a few things the seem to be prerequisite, but I can't find them explicitly stated as such.

For instance, reading about "ray on a cluster" it assumes a few things, but it doesn't assume that I have copies of my program (at least the clustered parts) in the same file location on all of the cluster clients.  However, that appears to be very necessary, have I got that correct?  I'm curious what else is required and that I'm not aware that I'm doing.   I'm also curious why the cluster-worker/clients need local copies, my impression from the docs is that the code is 'uploaded' to the cluster when I first call it, which implies to me that it wouldn't be necessary for cluster-workers to have local copies on the disk.

https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html
*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by rkooo567** [comment]
Thanks for asking the question! I have some clarification questions before answering them.

> I'm also curious why the cluster-worker/clients need local copies
What do you mean by local copies? Can you explain a bit more?

> I have copies of my program (at least the clustered parts) in the same file location on all of the cluster clients
You don't need to have it because Ray will import functions with @ray.remote to other nodes in the cluster under the hood. When you run your remote functions, they will be retrieved and run in different processes in the cluster.

**Comment by gimzmoe** [comment]
I apologize, I didn't see a response.
What I mean by local copies, is that to get my client-ray workers to run the program, I have to pre-position all of the files on each host in the same absolute path, otherwise the client-ray worker complains that they don't exist.  
To ask my question in a more specific way, what pre-conditions are necessary to execute, assuming I have nothing but a "virgin" ray cluster running?

**Comment by richardliaw** [comment]
While it is possible to get a Ray cluster working without the following, it is easiest to get ray working if:

1. all cluster machines have the same import files
2. all imported files (libraries) can be found on the standard `sys.path`. 

The actual ray entrypoint script only needs to be located on the head node.
