### ISSUE TITLE
Intercept logging, tf.logging, and stdout/stderr

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#817]
Maybe I am missing something, or it is just not documented, but what is good practice of outputing some debugging information during task execution? For example, currently we use Python logging package to do so. There is also TensorFlow `tf.logging`, and probably some tasks just output to stdout and stderr.

It would be great if besides the result of a task, one could obtain also all the logging information, stdout/stderr during the call. Ideally maybe even, that one could get push notifications about that.

My main question is though more: do you think this should be something done by Ray, or should we do something about this internally inside our task?

cc @suquark

**Comment by robertnishihara** [comment]
So, stdout/stderr are currently redirected to files under `/tmp/raylogs/` (one stdout file and one stderr per process). The files will appear on the same machine that the process is on.

To view the logfiles through the Ray API, you can run `ray.global_state.log_files()`.

Note that stdout/stderr are not always flushed immediately, but this can be addressed by adding calls like

```python
import sys
sys.stdout.flush()
sys.stderr.flush()
```

Does that help with what you want to do?

**Comment by mitar** [comment]
Not really. :-)

I mean, that gave me idea that we could also probably just hijack `sys.stdout` and `sys.stderr` for the execution of a task to collect all potential output.

So we can probably do this ourselves inside a task. To configure logging and stdout/stderr to collect all output. But maybe this could be also something Ray could collect? And make it available remotely. For example, log files are not available for me remotely. I would have my task collect them and give them to me. And mostly I want only log entries associated with one task running, not also previous tasks.

**Comment by mitar** [comment]
So suggestion for API could be `ray.get_logs(object_id)`. Which would return all stdout, stderr, and logging associated with the `object_id` task (hm, or is there a task id as well?).

Anyway, we will probably do this ourselves for now. But just an idea.

**Comment by robertnishihara** [comment]
If you try it out let me know how the feature works for you. I like the idea a lot.

**Comment by robertnishihara** [comment]
Closing for now.
