### ISSUE TITLE
[Ray] cpprb - replay buffers with Cython 

### ISSUE THREAD

**Issue by ermekaitygulov** [ray-project/ray#8170]
### What is your question?

Hello. Is it possible to create remote actor from cpprb.ReplayBuffer class? I've tried to follow advice from [Advanced usage](https://docs.ray.io/en/releases-0.8.4/advanced.html#cython-code-in-ray), but following code failed

```
import cpprb
import ray

ray.init()
rb_remote = ray.remote(cpprb.ReplayBuffer) 
```
<details>
    <summary>Traceback</summary>

     File "/home/airan/projects/Rozum/RobotArm/cython_test.py", line 5, in <module>
    rb_remote = ray.remote(cpprb.ReplayBuffer)
     File "/home/airan/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1818, in remote
    return make_decorator(worker=worker)(args[0])
     File "/home/airan/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1726, in decorator
    max_reconstructions)
     File "/home/airan/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 910, in make_actor
    num_gpus, memory, object_store_memory, resources)
    File "/home/airan/miniconda3/lib/python3.7/site-packages/ray/actor.py", line 340, in _ray_from_modified_class
    self = DerivedActorClass.__new__(DerivedActorClass)
    File "cpprb/PyReplayBuffer.pyx", line 756, in cpprb.PyReplayBuffer.ReplayBuffer.__cinit__
   TypeError: __cinit__() takes at least 1 positional argument (0 given) 
</details>

*Ray version and other system information (Python version, TensorFlow version, OS):*
-  Python 3.7
- Ray 0.8.4
- cpprb 8.4.2

**Comment by richardliaw** [comment]
What is cpprb?

**Comment by ermekaitygulov** [comment]
[Cpprb](https://ymd_h.gitlab.io/cpprb/) - it is realization of replay buffers for rl on Cython.

**Comment by rkooo567** [comment]
Are you trying to use the buffer class as an actor?

**Comment by ermekaitygulov** [comment]
Yes. I'm not sure that it is normal practice) It samples some batches, sends it to learner, than starts sampling again, while learner updates. I'll try to use it not like actor today and if it won't slow down update frequency I'll close issue.

**Comment by ermekaitygulov** [comment]
> I'll try to use it not like actor today and if it won't slow down update frequency I'll close issue.
It worked for me. Thank you. But I've got another little question) Numpy arrays are stored as read-only objects. Is there any way to store some arrays as read-write object to avoid copying of arrays?
