### ISSUE TITLE
[tune] Support passing in a list of parameters

### ISSUE THREAD

**Issue by anthonyhsyu** [ray-project/ray#8171]
Currently developing on [tune-sklearn](https://github.com/ray-project/tune-sklearn).

Example of what we'd like to get working [here](https://scikit-learn.org/stable/auto_examples/compose/plot_compare_reduction.html), where there's a list of two dictionaries to perform grid search on.

We want to do a grid search over a list of parameter configurations into Tune.

**Comment by richardliaw** [comment]
I will close this in lieu of https://github.com/ray-project/ray/issues/9159
