### ISSUE TITLE
[docs] suggestions for `deploying-on-slurm.rst`

### ISSUE THREAD

**Issue by wizardfishball** [ray-project/ray#8181]
# Make sure head node start before worker node

For the example at **Deploying on Slurm** doc to work, `ray start` on any worker node needs to happen after `ray start --head` has succeeded on the head node. It'd be helpful to suggest people to adjust the sleep time after `ray start --head` to ensure this order.

**Comment by rkooo567** [comment]
This is really good advice! Please feel free to create a PR if you want some contribution to the documentation!

**Comment by wizardfishball** [comment]
@rkooo567 will do! 👌
