### ISSUE TITLE
[RLlib] How can I turn off exploration for a while when training?

### ISSUE THREAD

**Issue by yskim5892** [ray-project/ray#8189]
### What is your question?

I want to turn exploration on and off while training(in custom Optimizer or something). For example in DDPG, I wanna remove gaussian noise in action for some amount of steps. But how can I do that?

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by sven1977** [comment]
You should be able to set the config of the Policy directly like so:
```
trainer.get_policy().config["explore"] = False
```
After this, every time the trainer calls `compute_actions` on the policy, the policy will compute a "non-explore" action.
Let me know if this doesn't work.

**Comment by yskim5892** [comment]
It worked for me, thank you very much!
