### ISSUE TITLE
general question: how does Ray compare with Tensorflow distributed

### ISSUE THREAD

**Issue by weiliu620** [ray-project/ray#819]
This is not an issue but more like a general question: TF also has some distributed computing capability. How Ray compare with TF for that? Given a task that I want to use distributed CPU + GPU, how do I choose Ray or TF?

I use TF, though not its distributed features. I'm new to Ray and is excited to find it recently. 

Thank you for the great work,

**Comment by robertnishihara** [comment]
Hi! We also use tensorflow a bunch, including it's distributed capabilities. Depending on the situation, we find it convenient to either use TensorFlow on a single GPU (e.g., define a neural net within an actor) and then use Ray to do data parallel training across multiple GPUs or multiple machines.

It also makes sense to define a one actor per machine and within each actor to use TensorFlow's distributed capabilities to parallelize the neural net computations over all of the GPUs on a single machine (and then to use Ray to handle distribution across multiple machines).

**Comment by robertnishihara** [comment]
Closing for now.
