### ISSUE TITLE
[rllib] rllib/agents/trainer not able to normalize actions for env which extends rllib/env/externalEnv

### ISSUE THREAD

**Issue by deepaksharma36** [ray-project/ray#8194]
Ray 0.8.4
TensorFlow 1.14.0
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04

Dear Developers,

I am using an env which extends external env for training. In the ray 8.4.0, for performing the action normalization an env should extend gym.Env. Since my env extends external env it does not extends gym.Env and I get a run time error during training for the same. Of course, for now, I can disable normalization, or I can implement my custom normalization method in my env. But I was wondering is there any plans you have for improving the action normalization step so that it can address both types of envs which extends gym.Env or ExternalEnvs. 

https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L561

https://github.com/ray-project/ray/blob/master/rllib/env/external_env.py#L9

**Comment by ramondalmau** [comment]
Hey, did you solved this issue? I am experiencing the same problem with SAC and MultiAgentEnv

**Comment by deepaksharma36** [comment]
I am not normalizing it, I have my own custom normalization method for it
in the rllib/agents/trainer.py
             def normalize(env):
                    return env

**Comment by aalbinati** [comment]
> Hey, did you solve this issue? I am experiencing the same problem with SAC and MultiAgentEnv

It appears to be an issue with action normalization support. It is now only supported for Gym environments.

Try setting normalize_actions to False in the config. Next step is to normalize the actions yourself to keep them in between the real action bounds. I am doing this by setting the action space bounds as [-inf,inf] and applying my own normalization inside the environment step.

Hope this helps ;)
