### ISSUE TITLE
Lots of "INFO worker.py:439 -- ray.get_gpu_ids() currently does not work in LOCAL MODE." messages printed in local mode

### ISSUE THREAD

**Issue by pmacalpine** [ray-project/ray#8203]
### What is the problem?
When I run in local mode I see lots of the following message being printed many times such that the console isn't really useable:
```
INFO worker.py:439 -- ray.get_gpu_ids() currently does not work in LOCAL MODE.
```
I'm not sure why this message is being printed as I'm not using a GPU (num_gpus=0, although my machine does have a GPU enabled).  As I recall some time ago I was running in local mode and found that the GPU was being used when it wasn't supposed to be however. I first see this message printed with code version 9bfc2c4b5462871f0fe669b3aabc5f2772bc3a6f, and so assume it was caused by #7670.  I'm not sure why this message is being printed when I shouldn't be using a GPU, and also I think the message should only be printed once and then suppressed in future instances when it would otherwise be printed

*Ray version and other system information (Python version, TensorFlow version, OS):*
Running on Azure NC6s_v2 machine
ray: 0.9.0.dev0 (latest wheels installed on 4/27/20)
python: 3.7.6 
tensorflow: 2.1
torch: 1.4.0
OS: Ubuntu 16.04.6 LTS

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

I'm just running the following example, but changing `ray.init()` to `ray.init(local_mode=True)`
```bash
python examples/custom_env.py
```
If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
cc @ijrsvt - can we mute this warning?

**Comment by ijrsvt** [comment]
Yes we can
