### ISSUE TITLE
Threads and Ray

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#824]
So I assume that Ray runs everything in one thread. Especially because of [this code](https://github.com/ray-project/ray/blob/dbe3d9351cbd3dd98270d5d7297d2706c5fca743/python/ray/worker.py#L905).

This is important for us, because then we can know that we can for example capture all output in #817.

But, playing a bit, there are some thread issues. For example, the following snippet:

```python
from pip.utils import logging as pip_logging

import ray

ray.init()

@ray.remote
def f():
  with pip_logging.indent_log():
    pass
  
  return "foobar"

print(ray.get(f.remote()))
```

fails with:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(ray.get(f.remote()))
  File ".../lib/python3.5/site-packages/ray/worker.py", line 1603, in get
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "test.py", line 9, in f
    with pip_logging.indent_log():
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File ".../lib/python3.5/site-packages/pip/utils/logging.py", line 34, in indent_log
    _log_state.indentation += num
AttributeError: '_thread._local' object has no attribute 'indentation'
```

`_thread._local` is a thread-local dict. The code [itself could be improved to not have this issue](https://github.com/pypa/pip/pull/4654), but the question is why does not initialize it correctly, and how could I make it initialize correctly this module?

(An easy way is to move `from pip.utils import logging as pip_logging` inside `f`, but the issue is that we are importing those all around the code, so it is already imported somewhere else when we get to `f`.)

**Comment by mitar** [comment]
cc @suquark

**Comment by robertnishihara** [comment]
I'd like to run the example and take a look. Where is `logger` defined?

**Comment by mitar** [comment]
Oh, I was trying to simplify example and I forgot it in. I removed that reference now. See above.

**Comment by mitar** [comment]
(Otherwise, it is `logger = logging.getLogger()`.

**Comment by robertnishihara** [comment]
Interesting, so each worker actually has two threads.

1. The "main thread" executes an infinite loop in which it blocks while waiting for a new task from the local scheduler. When it gets the task, it executes it. Then it issues another blocking request to the local scheduler for a new task, and this repeats.

2. The "import thread", which in the background waits for notifications about new remote function definitions, fetches the pickled remote functions from Redis, and unpickles them.

Unpickling a remote function (using cloudpickle in this case) will cause the relevant modules to be imported, and presumably some initialization is happening there on the "import thread". And then the stuff is getting used from the "main thread" which is causing problems. Does that sound like what's happening to you?

**Comment by mitar** [comment]
> Does that sound like what's happening to you?

Yes, this sounds good.

One question. In our case, we do not really need all this magic importing of function context. We expect all workers to have exactly the same code available. Is there a way to say to pickle only a method, but no global context? We would then have all imports inside a method.

**Comment by robertnishihara** [comment]
It may take some experimentation to get it to work, but it's possible that simply putting the imports inside of the remote function would be enough (especially if the import hasn't been done outside of the remote function).

Oh, actually, if you have a function `helper_function` defined in a file `some_file.py`, and then you define the remote function

```python
import some_file

@ray.remote
def f():
    some_file.helper_function()
```

Then when `f` is pickled, I think cloudpickle will not introspect in `some_file`. It will just try to import `some_file` when it unpickles `f`. But any context that is used inside of `some_file` won't be pickled.

Let me know if that works for you.

**Comment by mitar** [comment]
> especially if the import hasn't been done outside of the remote function

Sadly, this is the case in our case. Some other modules higher up in hierarchy of our code loads that module.

So this is how we discovered the issue. We were just loading things in outer module, and outside of the function.

> It will just try to import some_file when it unpickles f.

But that will happen in the wrong thread, no?

**Comment by robertnishihara** [comment]
So, when `f` is unpickled, cloudpickle will try to import `some_file`. But if `some_file` doesn't do `from pip.utils import logging as pip_logging` at the top and instead does it inside of `helper_function`, then I think it should work. Do you think something like that will work?

**Comment by mitar** [comment]
Yes. If there is no import before, then it works. This was my comment in initial post was about:

> (An easy way is to move from pip.utils import logging as pip_logging inside f, but the issue is that we are importing those all around the code, so it is already imported somewhere else when we get to f.)

**Comment by mitar** [comment]
So I think the issue is that `pip.utils.logging` is already imported when we get to this module. And it was imported on a wrong thread.

Or, maybe I understand what you are saying. Let me test. :-)

**Comment by mitar** [comment]
In fact, this is exactly how we have it, and it does not work.

**Comment by mitar** [comment]
So we have a hierarchy of modules: `foo.bar.ray`. And then `ray.py` imports `foo.bar.code` and has a function `f` which calls `foo.bar.code.run()` inside `f`. That `code` imports the logging module, and `run` calls the `indent_log`. And fails. Because our `foo` already imports the logging module. And it seems that happens on the wrong thread, so that when `code` comes around to import it, it is already imported.

**Comment by mitar** [comment]
We found another issue with loading Python modules and state which is retained globally. We are using TensorLayer and it keeps a global state of layers and their names [here](https://github.com/zsdonghao/tensorlayer/blob/master/tensorlayer/layers.py#L26). So when one task creates layers with some names, and then another task tries to create layers with same names it complains that names already exist. Now we can use `max_calls` to get process to be created new after each task, but that is then probably more a workaround and inefficient?

**Comment by robertnishihara** [comment]
Creating a new process (using `max_calls`) is probably a good option. Defining a neural net is likely time consuming. The minimum cost for starting a new Python process is about 100ms, and we have some additional overhead on top of that, so it all depends how much time your tasks take.

Also, I'm not sure if this will help with TensorLayer, but with normal TensorFlow usage you can avoid a lot of these problems by creating a new "graph" each time.

**Comment by mitar** [comment]
I have encountered this again. This time a package I am trying to use is trying to register signals. But this fails on workers because:

```
ValueError: signal only works in main thread
```

**Comment by SoundsSerious** [comment]
I am using some 3D meshing code which also requires the use of a signal similar to @mitar's example. Unfortunately this code is not really trivial to rewrite as `gmsh` is quite an involved application

It would be great to have a way to handle these situations
