### ISSUE TITLE
[ray] upload osdi18 slides

### ISSUE THREAD

**Issue by ucasFL** [ray-project/ray#8245]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Hi, where can i find Ray: A Distributed Framework for Emerging AI Applications paper's presentation slides on OSDI18, i look up in usenix website, but didn't find it.

**Comment by josephlucas-arc** [comment]
https://rise.cs.berkeley.edu/wp-content/uploads/2017/07/Ray-BDDRISE-MiniRetreat-201705.pdf

**Comment by JosephTLucas** [comment]
https://rise.cs.berkeley.edu/wp-content/uploads/2017/07/Ray-BDDRISE-MiniRetreat-201705.pdf

**Comment by rkooo567** [comment]
Btw, many implementation of that paper became obsolete. Just keep this in mind while you are reading it!

**Comment by richardliaw** [comment]
Oh jeez that presentation is old! 

I'm supposed to be the one responsible for sending this to the usenix folks... I'll take care of this in a couple days.

Here's a version of the slides of the talk we gave at OSDI.
[2018-10-10 - Ray talk at OSDI (no backup).pdf](https://github.com/ray-project/ray/files/4561692/2018-10-10.-.Ray.talk.at.OSDI.no.backup.pdf)
