### ISSUE TITLE
Training reward and the evalution reward in stdout?

### ISSUE THREAD

**Issue by xuehui1991** [ray-project/ray#8247]
### What is your question?
Dear ray team,
I just run a apex-dqn pong example  in ray, the config file could found here:
https://github.com/ray-project/ray/blob/master/rllib/tuned_examples/pong-apex.yaml

Here is the result:
== Status ==
Memory usage on this node: 13.9/503.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 5/28 CPUs, 1/8 GPUs, 0.0/93.12 GiB heap, 0.0/32.13 GiB objects
Result logdir: /root/ray_results/pong-apex
Number of trials: 1 (1 RUNNING)
+-------------------------------+----------+----------------------+--------+------------------+-------+----------+
| Trial name                    | status   | loc                  |   iter |   total time (s) |    ts |   reward |
|-------------------------------+----------+----------------------+--------+------------------+-------+----------|
| APEX_PongNoFrameskip-v4_00000 | RUNNING  | 10.198.141.203:23844 |      1 |           40.204 | 39200 |      -21 |
+-------------------------------+----------+----------------------+--------+------------------+-------+----------+

== Status ==
Memory usage on this node: 16.7/503.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 5/28 CPUs, 1/8 GPUs, 0.0/93.12 GiB heap, 0.0/32.13 GiB objects
Result logdir: /root/ray_results/pong-apex
Number of trials: 1 (1 RUNNING)
+-------------------------------+----------+----------------------+--------+------------------+-------+----------+
| Trial name                    | status   | loc                  |   iter |   total time (s) |    ts |   reward |
|-------------------------------+----------+----------------------+--------+------------------+-------+----------|
| APEX_PongNoFrameskip-v4_00000 | RUNNING  | 10.198.141.203:23844 |      2 |          72.6085 | 78000 | -20.8913 |
+-------------------------------+----------+----------------------+--------+------------------+-------+----------+

Here is my question:
The reward is the training reward or the evaluation reward(with no explore policy)?

Thank you~

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by Glaucus-2G** [comment]
I want to know how you run it? Use 'rllib train -f  pong-apex.yaml'
