### ISSUE TITLE
[rllib] Pretrain with expert dataset / optimal agent?

### ISSUE THREAD

**Issue by Alwinator** [ray-project/ray#8248]
#### Short version
How do I pretrain my agent using the optimal agent?
(Similar to [StableBaselines .pretrain method](https://stable-baselines.readthedocs.io/en/master/guide/pretrain.html))

#### Long version
I have an expert dataset created by a python script including the optimal agent. Now I want to use this dataset to pretrain my agent, that the "real" training doen't take that long. Maybe it is possible using a [Offline Dataset](https://docs.ray.io/en/latest/rllib-offline.html). 

P.S. I am new to rllib, so I am sorry if this question is useless / already in the documentation

#### If needed, here are my versions:
Ray version: 0.9.0.dev0
Tensorflow-GPU: 2.1.0
Python version: 3.7.7
OS: Ubuntu 18.04.2

**Comment by Alwinator** [comment]
## Still important!
@ericl @robertnishihara @richardliaw @pcmoritz @edoakes @mehrdadn @sven1977 @stephanie-wang @simon-mo @rkooo567 @ffbin

**Comment by BrunoBSM** [comment]
Any news on this? I've been having a hard time saving the model from one trainer and loading into another (like going from BC to PPO).

**Comment by Alwinator** [comment]
> Any news on this? I've been having a hard time saving the model from one trainer and loading into another (like going from BC to PPO).

Unfortunately, I still haven't found any solution. But I also have to say that I didn't have time to work on this.

**Comment by ericl** [comment]
@sven1977 I think this is possible by saving/restoring the keras model weights, do we have any existing example code? Perhaps adding an explicit API like stable baselines (mentioned above) would be useful: https://stable-baselines.readthedocs.io/en/master/guide/pretrain.html

Also cc @michaelzhiluo for any thoughts.

**Comment by BrunoBSM** [comment]
The Ray team answered me about this, I put the solution into the discussion forum. Basically just use the get.weights() and set.weights() methods to go from one trainer to the other (Make sure the model configurations match!). Here is the [link to discussion](https://discuss.ray.io/t/how-to-pretrain-a-model-with-behavior-cloning/278)
