### ISSUE TITLE
[tune] Does tune support distributed training in each trial?

### ISSUE THREAD

**Issue by pingsutw** [ray-project/ray#8264]
### What is your question?
We have a large dataset, and I use distributed TF training in my machines.
I know tune can distribute each trial in different single machines. 
Is it possible to run each trail in two or three machines?
If yes, are there any examples?

**Comment by richardliaw** [comment]
@pingsutw, yep this should work. Here's a high level for how you can make it work: https://docs.ray.io/en/master/tune/api_docs/trainable.html#advanced-resource-allocation


We do this for pytorch already: https://docs.ray.io/en/master/raysgd/raysgd_pytorch.html

You can build your own using the RaySGD TFTrainer.

**Comment by pingsutw** [comment]
@richard4912 Great. Thanks for the help.
This is what I looked for.

**Comment by richardliaw** [comment]
great! @pingsutw is you end up getting it to work, would you be interested in contributing an example?

**Comment by pingsutw** [comment]
@richardliaw sure, it's my pleasure.
I will do it.
