### ISSUE TITLE
default_worker.py: no module named redis

### ISSUE THREAD

**Issue by weiliu620** [ray-project/ray#827]
Uubntu 14.04 with python 3.4. Installed Ray from Pypi.

When `ray.inint()`, got error: 

```
...
No module named redis
ImportError: No module named redis
Traceback (most recent call last):
  File "/home/weiliu/.local/lib/python3.4/site-packages/ray/workers/default_worker.py", line 8, in <module>
    import redis
ImportError: No module named redis
Traceback (most recent call last):
  File "/home/weiliu/.local/lib/python3.4/site-packages/ray/workers/default_worker.py", line 8, in <module>
    import redis
ImportError: No module named redis
```
I can import redis form console, no error: 
```
In [3]: import redis

In [4]: redis.__version__
Out[4]: '2.10.5'
```
When I set up Ray on another RedHat Linux system, I can also init without error. 

No experience in debugging distributed system. Any steps to follow, or other information to provide?

Thanks,

**Comment by robertnishihara** [comment]
Hey, I think the problem is the same one described in #778. Can you see if the solutions there work?

This should be solved by #760, but that hasn't made it's way into the wheels on PyPI yet.

**Comment by weiliu620** [comment]
Yes,  I use python 3.4 to init ray, but system default is python 2.7. After downloading the whl file in #778, I can init without error. 

Thank you very much.

**Comment by robertnishihara** [comment]
Great! Let me know if you run into more problems.
