### ISSUE TITLE
[GCS] Actor creation / kill Performance Regression. Stress Test, `test_dead_actors.py` became slower with GCS service. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#8292]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
nightly

There was performance regression (`test_dead_actors.py` was 4 times slower) with GCS service on. We will turn off the GCS service for the release 0.8.5. We need investigation on this.

## GCS ON
```
Finished in: 450.6354160308838s
Average iteration time: 4.506352145671844s
Max iteration time: 35.391873836517334s
Min iteration time: 0.10686612129211426s
```

## GCS OFF
```
Finished in: 103.75814247131348s
Average iteration time: 1.037579414844513s
Max iteration time: 2.213489055633545s
Min iteration time: 0.09523892402648926s
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

https://github.com/ray-project/ray/tree/master/ci/regression_test/stress_tests
`test_dead_actors.py`. Autoscaler cluster configuration is in `ray-project` folder.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
This wouldn't cause issues for most of workflow. Will move it to P1.

**Comment by ericl** [comment]
Downgrading to P3 since the performance of actor launch is not typically important.
