### ISSUE TITLE
[tune] close logger after updating Trial status

### ISSUE THREAD

**Issue by ThomasLecat** [ray-project/ray#8307]
### Describe your feature request

Several experiment tracking systems, such as [neptune](https://neptune.ai/) or [Weights&Biases](https://www.wandb.com/) offer to categorize experiments as "Succeeded" or "Failed". This status is set when closing the logger.

Today, the `RayTrialExecutor._stop_trial` method closes the loggers before updating the status of the trial and updating its `trial.error_msg` attribute. When loggers are closed, it is impossible to know whether the trial is terminated normally or with an error, and therefore to set correct status in the experiment trackers.

To me, the solution seems as simple as moving these two lines:
https://github.com/ray-project/ray/blob/8625e09067a0f87b9951b2b41a7c7e0fead66f6e/python/ray/tune/ray_trial_executor.py#L259-L260
at the end of the `_stop_trial` method.

Is there any reason to close logger at the beginning of `_stop_trial`? 
Happy to create a PR otherwise!

Thanks,

**Comment by richardliaw** [comment]
Yeah that sounds good - in the finally block right?

A PR would be really appreciated - thanks!

**Comment by ThomasLecat** [comment]
Thanks @richardliaw for approving and merging the associated PR, much appreciated!
