### ISSUE TITLE
[rllib] Vectorization & multi-agent are broken in DDPG (both TF and Torch)

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8319]
### What is the problem?

`./train.py --run=DDPG --env=MountainCarContinuous-v0 --config='{"num_envs_per_worker": 2}'`
and
`./train.py --run=DDPG --env=MountainCarContinuous-v0 --config='{"num_envs_per_worker": 2}' --torch`

both currently crash. The issue seems to be that while the input to compute_actions() is a batch of N observations, only 1 action is returned as output. I ran into this while debugging a hang in a multi-agent test case (hung due to a bug in the env triggered by vectorization returning 1 action instead of N actions).

**Comment by ericl** [comment]
git bisect run script.sh

script:
```
cd python
sudo SKIP_THIRDPARTY_INSTALL=1 SKIP_PYARROW_INSTALL=1 python setup.py develop
cd -
cd rllib
./train.py --run=DDPG --env=MountainCarContinuous-v0 --config='{"num_envs_per_worker": 2}' --stop='{"timesteps_total": 1}'
```



```
83e06cd30a45245c2cb0e9f4bd924224b1581554 is the first bad commit
commit 83e06cd30a45245c2cb0e9f4bd924224b1581554
Author: Sven Mika <sven@anyscale.io>
Date:   Sun Mar 1 20:53:35 2020 +0100

    [RLlib] DDPG refactor and Exploration API action noise classes. (#7314)
```

**Comment by ericl** [comment]
@sven1977 probably some trivial bug in the new ddpg pol that breaks batching

**Comment by sven1977** [comment]
Taking a look ...

**Comment by sven1977** [comment]
Got it, will PR today ...

**Comment by sven1977** [comment]
Here is the PR: https://github.com/ray-project/ray/pull/8324

**Comment by sven1977** [comment]
Leaving this open until merged.
