### ISSUE TITLE
[rllib][tune] How should I calculate memory usage for Ape-X DDPG?

### ISSUE THREAD

**Issue by lacerdamarcelo** [ray-project/ray#8325]
Hello everyone.

I've been trying to understand why do I run out of memory when running Ape-X DDPG with tune. I've used Population Based Training with 8 samples and 16 workers each. My actor and critic networks have 4 hidden layers with 400 neurons each, with 8 continuous action variables. My buffer size is 45000 and my observables array has 254 itens (floating points).

I've used a cluster with 128 GB of RAM. I tried to calculate the amount of memory the algorithm should be using according to what I understood about both Ape-X DDPG (and its implementation in Ray) and PBT but the numbers don't get even close to the total amount of memory I have available. So I'm pretty sure I'm missing something and I would really appreciate if anyone could help me on that.

Thanks!

Ray version: 0.8.4
Tensorflow-GPU: 2.1.0
Python version: 3.6.6
OS: CentOS 7

**Comment by noprohuangqi** [comment]
May be you can find something int this #[issue](https://github.com/ray-project/ray/issues/10890)

**Comment by lacerdamarcelo** [comment]
Thank you @noprohuangqi! I'll take a look!
