### ISSUE TITLE
[tune] I cannot reproduce the results of ray with simple running of function

### ISSUE THREAD

**Issue by mahsa91** [ray-project/ray#8332]
I'm using the latest version of ray with pytorch for tuning parameters. I've used grid_search and found a good config with the highest accuracy. But when I try to run the training process with that config without ray, I get different results from ray. Is there any suggestion that can help me with my problem? I use the following pattern for running:

`tune.run(train, config=config, name='experiment_grid_tadpoe6')`

**Comment by richardliaw** [comment]
Can you provide some code for reproduction?

**Comment by mahsa91** [comment]
> Can you provide some code for reproduction?

That's my problem that it's a code of the project and I cannot provide it. I'm suspicious of seed and randomness. I've set seeds but maybe running with ray uses different seeds.

**Comment by richardliaw** [comment]
https://docs.ray.io/en/master/tune/tutorials/overview.html#how-can-i-reproduce-experiments should work.
