### ISSUE TITLE
[rllib] torch GPU acceleration broken for PPO

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#8339]
### What is the problem?
rllib Regression test result from PPO looks slower. The exact cause it uncertain, but it seems like torch GPU acceleration doesn't work as expected (everything else looks fine weirdly)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

run regression test PPO workload. https://github.com/ray-project/ray/tree/master/ci/regression_test/rllib_regresssion_tests

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by pmacalpine** [comment]
Maybe this is related to #8335 where using a gpu with torch fails with an error (in that case with a custom policy but I see the same error with PPO).

**Comment by sven1977** [comment]
This is probably due to torch==1.5.0 installed. Try `pip install torch==1.4`.
Closing this issue.

**Comment by rkooo567** [comment]
Is it possible to restrict the torch version when using this? I think we should create a PR for that before we close it.

**Comment by ericl** [comment]
Isn't 1.5 newer? So we don't support latest torch?

**Comment by 51616** [comment]
> This is probably due to torch==1.5.0 installed. Try `pip install torch==1.4`.
> Closing this issue.

I tried downgrading to torch 1.4 but the issues still occur. Is there any quick workaround for now?
