### ISSUE TITLE
[tune] Continue Hyperparameter Search

### ISSUE THREAD

**Issue by AlanHassen** [ray-project/ray#8351]
I was skimming through the examples and was wondering if I can pause and resume a hyperparameter optimization task with tune? In the examples it seems, you start the process once and get a result afterwards.

My main motivation is the usage of anytime algorithms. BOHP for example produces valid solutions at any time and one of these solutions might already be good enough.

**Comment by richardliaw** [comment]
This now works for most search algorithms (but does not yet work for BOHB).
