### ISSUE TITLE
[ray] Avoid extra copy and specify location of object storage

### ISSUE THREAD

**Issue by VoVAllen** [ray-project/ray#8360]
### What is your question?

I want to use ray to build a distributed embedding server. In my settings, there are several servers holding parts of embeddings each (say server 1 holds 0-99, server 2 holds 100-199 etc), with large memory. And there are several workers fetching the embedding needed by id and updates those embeddings later. 

The tricky thing here is that I only want to preserve one copy of those embeddings, ideally on the server sides, at most times to save memory consumption. Can I ensure embedding always exists on server and the local storages on workers are evicted based on LRU with ray? Or if I didn't manually arrange the object location, will ray automatically transfer objects from one full-memory machine to another vacant machine?

Thanks!

**Comment by VoVAllen** [comment]
Is the `lru_evict` option cluster-wise or node-wise(per plasma store)?
If I have one object id alive, and it stays in two machines plasma store, can I only preserve one of them?

**Comment by rkooo567** [comment]
cc @stephanie-wang

**Comment by stephanie-wang** [comment]
Despite the name, `lru_evict` is probably not what you want here. What that means is that if your cluster is completely out of memory, including after any unnecessary object copies have been removed, objects will begin to be evicted in LRU order. This can potentially evict an object that is actually still needed. When `lru_evict` is not enabled, you will instead get an OutOfMemoryError.

I think the default ray memory options should work for your use case, but maybe not exactly the way you want. Here is how ray memory is allocated for objects:
1. The object is pinned in shared memory on the same node as the worker that created the memory, either through `ray.put` or returning a large object from a task. This copy of the object will only be evicted after all references to the object have been deleted.
2. While the object is still in reference, other copies of the object may be created in shared memory on other nodes, by copying from the original. This can happen, for example, if a task executing on another node calls `ray.get` on the object, or if it takes in the object as an argument. These additional copies are not pinned and may be evicted at any time based on LRU, even when the object is still in scope. Note that this LRU eviction will only kick in if that particular node is under memory pressure. Once all references to the object have gone out of scope, these copies will also soon be evicted.

So to answer your questions:

> The tricky thing here is that I only want to preserve one copy of those embeddings, ideally on the server sides, at most times to save memory consumption. Can I ensure embedding always exists on server and the local storages on workers are evicted based on LRU with ray?

You can ensure that the "main copy" exists on the server by making sure that whatever task creates the object executes on the server. If workers copy the object to their local storage, they will eventually get LRU-evicted, but only if that particular worker is under memory pressure.

> Or if I didn't manually arrange the object location, will ray automatically transfer objects from one full-memory machine to another vacant machine?

Right now, we do not support migrating the main copy of an object. This is something that we're considering adding support for in the backend, but we don't currently have concrete plans for it. Is this something you'd be interested in, and can you say more about what your requirements are?
