### ISSUE TITLE
`requests` dependency missing on `import ray.rllib.agents.ppo`

### ISSUE THREAD

**Issue by andyk** [ray-project/ray#8373]
### What is the problem?
After creation of a new conda env (python=3.7.3, pip=19.0.3) and only installing ray[rllib], i run `from ray.rllib.agents.ppo import PPOTrainer` and get error saying that I need to install `requests`.

It looks like import and where the error is thrown in [web_server.py lines 15-12](https://github.com/ray-project/ray/blob/304e31b7e56ebd33f7099d97233e3feb37f495c9/python/ray/tune/web_server.py#L15) assumes you are trying to use the tune client if you import web_server.py. I'm not familiar with the code, but from ten thousand feet, I find that a bit confusing, since I'd expect the client code to be separated from the web_server code if it has special dependencies that require manual installation. I'm not trying to use the tune client just by importing the ppo package, so it seems either `requests` should be added as a dependency or this check (and subsequent error throwing) should be removed.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Tried this with Ray 0.8.5 and 0.8.0
python=3.7.3
pip=19.0.3

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
conda create -n test_ray python=3.7.3 pip=19.0.3
conda activate test_ray
pip install ray[rllib]
python -c 'from ray.rllib.agents.ppo import PPOTrainer'
```
Output:
```
Couldn't import `requests` library. Be sure to install it on the client side.
Couldn't import `requests` library. Be sure to install it on the client side.
Traceback (most recent call last):
  File "/Users/andyk/miniconda3/envs/test_ray/lib/python3.7/site-packages/ray/tune/web_server.py", line 16, in <module>
    import requests  # `requests` is not part of stdlib.
ModuleNotFoundError: No module named 'requests'
Couldn't import `requests` library. Be sure to install it on the client side.
```

If we cannot run your script, we cannot fix your issue.

- [ x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
@richardliaw do we just need to make this INFO log instead of logger.exception()?

**Comment by richardliaw** [comment]
Yeah, thatd work.
