### ISSUE TITLE
Can't connect the head node from another SpinServer machine

### ISSUE THREAD

**Issue by Julianbaozi** [ray-project/ray#8395]
### What is your question?
I want to run a python script with two different machines together. I can run it on my laptop and parallel it with ray. Now I want to extend it to a server I just bought.
I use 

ray start --head --redis-port=6379 --redis-shard-ports=6380 --node-manager-port=12345 --object-manager-port=12346 --redis-password="" 

to setup head node on my laptop. The versions are Ubuntu 18.04, Ray 0.8.4, python 3.6. Then on my SpinServer, I ran

ray start --address=172.30.7.83:6379  --node-manager-port=12345 --object-manager-port=12346 --redis-password=""

the result is 

2020-05-10 21:26:52,585	INFO services.py:563 -- Failed to connect to the redis server, retrying.

And I can't set the head node with the public id of my laptop. It says

Error 110 connecting to 76.80.178.3:6381. Connection timed out.

**Comment by rkooo567** [comment]
Maybe your laptop has a firewall setup, and your server is not reachable to Redis running in your laptop. Can you check if you can reach to the Redis in your laptop from your server?

**Comment by Julianbaozi** [comment]
how to check that?

**Comment by Julianbaozi** [comment]
both ufw are inactive.
And also if I check the port from browser, it gets
-ERR wrong number of arguments for 'get' command

**Comment by Julianbaozi** [comment]
When I set my vm server as head node, my laptop can connect.
When I set my laptop as head server, the vm can't connect.
It is the same with Redis.
Redis on my laptop is set to 172.30.xx.xx, with bind 0.0.0.0, not protected. On VM it says connection denied, for the public IP, and connection timeout for private IP.
The firewalls are inactive on both machine.

**Comment by rkooo567** [comment]
I think in general laptop needs a special setup to get incoming requests. For example, if you use MacOS, you can do this https://support.apple.com/en-us/HT201642.
