### ISSUE TITLE
[tune] HParams failed - unsupported type NoneType

### ISSUE THREAD

**Issue by antonwnk** [ray-project/ray#8399]
### What is the problem?
Scikit-learn sometimes takes `None` as a parameter. This does not seem to agree with TensorBoard's HParams, as an error pops up when `None` is sampled from my parameter space.
Not sure how this should be handled &ndash; detect and replace it with `str(None)`? 😀
 
(running on ray 0.8.0, performing hyperparameter search with HyperOpt)

### Reproduction (REQUIRED)
No script as it's kind of straightforward: define a hyperparameter space with the value `None` in it.

**Comment by richardliaw** [comment]
Hm, can you try running the latest version of Ray? This should be fixed.
