### ISSUE TITLE
rllib - Support for Recording videos using gym monitor for MultiAgentEnv

### ISSUE THREAD

**Issue by nilabha** [ray-project/ray#8403]
### Question

I see in the line 307-311, the monitor wrapper is not done for MultiAgentEnv. Code section below

```python
        if isinstance(self.env, MultiAgentEnv) or \
                isinstance(self.env, BaseEnv):

            def wrap(env):
                return env  # we can't auto-wrap these env types
```

I tried enabling it but it seems that it doesn't work with my multi-agent set up. Is there any specific reason for disabling this. Do we plan to have support for it in future?

**Comment by rfali** [comment]
Relevant [PR](https://github.com/ray-project/ray/pull/14796) that has potentially fixed this.
