### ISSUE TITLE
Running some workers on Python 2.7 and some on Python 3

### ISSUE THREAD

**Issue by mitar** [ray-project/ray#841]
It seems that we have some libraries which require Python 2.7, and we have some code which requires Python 3. Would it be possible to run workers with different versions of Python and route tasks based on versions to them?

**Comment by robertnishihara** [comment]
I don't think you can just serialize something with cloudpickle in Python 3 and then try to deserialize it with cloudpickle in Python 2 (I just tried with a simple function and it didn't seem to work).

That's probably a surmountable barrier, though I'm not sure what the best approach is at the moment.

Which libraries are you using that require Python 2 and 3?

**Comment by mitar** [comment]
I do not know yet. Our external partners are developing that code and we were just informed about that. :-(

In our case, we have the same function/task which we call, and then that code determines what to import and so on. So it would be just a question how to get that wrapper function to be called on multiple workers. In our case, we do not even have to pickle the code, the code should be available on workers anyway.

**Comment by robertnishihara** [comment]
This is a bit of a hack, but you could do the following.

Suppose you're using Python 3 and you want to execute some Python 2 code. One option is to define a remote function that just starts a Python 2 process, e.g.,

Suppose there is a Python 2 script called `helper.py` defined as

```python
import json

# Run some python 2 specific libraries and then print the output to stdout.
print json.dumps([1, 2, 3])
```

```python
import json
import ray
import subprocess

ray.init()

@ray.remote
def f():
    out = subprocess.check_output(["python2", "helper.py"])
    return json.loads(out)

ray.get(f.remote())  # This should be [1, 2, 3]
```

**Comment by mitar** [comment]
Hm. But then memory sharing will not necessary work. Or maybe if we connect to plasma store from helper.py.

Anyway, I think that for now we will just not run code which requires Python 2 and leave to partners to update their code.

Maybe in the future we could have some labels on workers (like custom resource we made for datasets) to mark them as python 2.7 or python 3 and then route tasks according to that. Only pickling of a task would then be a problem, but there might also be a way to go around that.

**Comment by robertnishihara** [comment]
So, the data would still be handled efficiently through shared memory (the data returned by `f` in the example I gave). But you're right there is an inefficiency because it gets piped to STDOUT first and serialized/deserialized using json.

Something like what you suggest with labeling workers probably could work, though with everybody dropping Python 2 support in 2020 it may become less important as time goes on.

**Comment by mitar** [comment]
2020 is after our grant runs out, so we might have to have python 2.7 support. ;-)

**Comment by robertnishihara** [comment]
Closing for now. Let us know if this issue continues to arise and we can revisit it.
