### ISSUE TITLE
auto-scaling issues

### ISSUE THREAD

**Issue by shreyagu** [ray-project/ray#8410]
Hello,
I currently have an AWS cluster with 3 nodes and 2 CPUs each but face auto-scaling issues.
 To start my ray cluster and run on it i did include the following steps:
1. ray up cluster.yaml
2. in my code i include
ray.init(address='auto', redis_password=*****)
tune.run(resources_per_trial = {"cpu": 3}) 

When i tune.run( resources_per_trial ={"cpu":3}), instead of auto-scaling to another node in the cluster i get the following error: 

```ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 3 CPUs, 0 GPUs but the cluster has only 2 CPUs, 0 GPUs, 4.35 GiB heap, 1.46 GiB objects (1.0 node:172.31.44.212). Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available. ```

I don't understand why this happens? Can someone please help me out with this?

**Comment by shreyagu** [comment]
@richardliaw @robertnishihara

**Comment by richardliaw** [comment]
This happens because 'cpu' = 3 means that 3 CPUs must be available for a SINGLE trial on a SINGLE machine.

**Comment by shreyagu** [comment]
oh, then how do i auto-scale? does just doing ray.init() and tune.run() automatically run it on all nodes in the cluster?

**Comment by shreyagu** [comment]
Following the steps mentioned above, i still keep getting this error message while running your `bayesopt_example.py` with `(resources_per_trial = {"cpu": 2})`
```(pid=raylet, ip=172.31.32.31) *** Aborted at 1589305604 (unix time) try "date -d @1589305604" if you are using GNU date ***
(pid=raylet, ip=172.31.32.31) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.31) *** SIGTERM (@0x3e800003428) received by PID 13232 (TID 0x7fdd938a3800) from PID 13352; stack trace: ***
(pid=raylet, ip=172.31.32.31)     @     0x7fdd92d5b890 (unknown)
(pid=raylet, ip=172.31.32.31)     @     0x7fdd9264cbf9 __poll
(pid=raylet, ip=172.31.32.31)     @     0x55e6da51efe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.31)     @     0x55e6da51f4e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.31)     @     0x55e6da520817 redisConnect
(pid=raylet, ip=172.31.32.31)     @     0x55e6da43eed7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da440ee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da444f21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da446991 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da3dfb56 ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da3a343a ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=172.31.32.31)     @     0x55e6da2b7e8a main
(pid=raylet, ip=172.31.32.31)     @     0x7fdd92559b97 __libc_start_main
(pid=raylet, ip=172.31.32.31)     @     0x55e6da2c8d81 (unknown)

**Comment by richardliaw** [comment]
Can you provide a longer stack trace?

**Comment by shreyagu** [comment]
This is the longer stack trace @richardliaw :
`== Status ==
Memory usage on this node: 1.7/7.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 4/2 CPUs, 0/0 GPUs, 0.0/4.35 GiB heap, 0.0/1.46 GiB objects
Result logdir: /home/ubuntu/ray_results/MNISTTrainable
Number of trials: 360 (356 PENDING, 2 RUNNING, 2 TERMINATED)
+----------------------+------------+--------------------+-----------+-------+--------+------------------+
| Trial name           | status     | loc                |   hiddens |   acc |   iter |   total time (s) |
|----------------------+------------+--------------------+-----------+-------+--------+------------------|
| MNISTTrainable_00004 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00005 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00006 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00007 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00008 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00009 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00010 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00011 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00012 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00013 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00014 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00015 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00016 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00017 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00018 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00019 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00002 | RUNNING    | 172.31.44.212:8208 |       128 | 95.14 |     40 |         105.164  |
| MNISTTrainable_00003 | RUNNING    |                    |        32 |       |        |                  |
| MNISTTrainable_00000 | TERMINATED |                    |        32 | 94.57 |     50 |          93.2348 |
| MNISTTrainable_00001 | TERMINATED |                    |        64 | 95.19 |     50 |         108.816  |
+----------------------+------------+--------------------+-----------+-------+--------+------------------+
... 340 more trials not shown (340 PENDING)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589307393 (unix time) try "date -d @1589307393" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e800005e1b) received by PID 23971 (TID 0x7fad7c413800) from PID 24091; stack trace: ***
(pid=raylet, ip=172.31.32.178)     @     0x7fad7b8cb890 (unknown)
(pid=raylet, ip=172.31.32.178)     @     0x7fad7b1bcbf9 __poll
(pid=raylet, ip=172.31.32.178)     @     0x5619f5b45fe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.178)     @     0x5619f5b464e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.178)     @     0x5619f5b47817 redisConnect
(pid=raylet, ip=172.31.32.178)     @     0x5619f5a65ed7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.178)     @     0x5619f5a67ee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x5619f5a6bf21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x5619f5a6d991 ray::gcs::RedisClient::Connect()
== Status ==
Memory usage on this node: 1.7/7.5 GiB
Using FIFO scheduling algorithm.
Resources requested: 4/2 CPUs, 0/0 GPUs, 0.0/4.35 GiB heap, 0.0/1.46 GiB objects
Result logdir: /home/ubuntu/ray_results/MNISTTrainable
Number of trials: 360 (356 PENDING, 2 RUNNING, 2 TERMINATED)
+----------------------+------------+--------------------+-----------+-------+--------+------------------+
| Trial name           | status     | loc                |   hiddens |   acc |   iter |   total time (s) |
|----------------------+------------+--------------------+-----------+-------+--------+------------------|
| MNISTTrainable_00004 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00005 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00006 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00007 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00008 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00009 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00010 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00011 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00012 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00013 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00014 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00015 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00016 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00017 | PENDING    |                    |       128 |       |        |                  |
| MNISTTrainable_00018 | PENDING    |                    |        32 |       |        |                  |
| MNISTTrainable_00019 | PENDING    |                    |        64 |       |        |                  |
| MNISTTrainable_00002 | RUNNING    | 172.31.44.212:8208 |       128 | 95.29 |     42 |         110.304  |
| MNISTTrainable_00003 | RUNNING    |                    |        32 |       |        |                  |
| MNISTTrainable_00000 | TERMINATED |                    |        32 | 94.57 |     50 |          93.2348 |
| MNISTTrainable_00001 | TERMINATED |                    |        64 | 95.19 |     50 |         108.816  |
+----------------------+------------+--------------------+-----------+-------+--------+------------------+
... 340 more trials not shown (340 PENDING)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589306436 (unix time) try "date -d @1589306436" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e8000046da) received by PID 18018 (TID 0x7f1b74258800) from PID 18138; stack trace: ***
(pid=raylet, ip=172.31.32.178)     @     0x7f1b73710890 (unknown)
(pid=raylet, ip=172.31.32.178)     @     0x7f1b73001bf9 __poll
(pid=raylet, ip=172.31.32.178)     @     0x563c8310ffe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.178)     @     0x563c831104e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.178)     @     0x563c83111817 redisConnect
(pid=raylet, ip=172.31.32.178)     @     0x563c8302fed7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.178)     @     0x563c83031ee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x563c83035f21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x563c83037991 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x563c82fd0b56 ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x563c82f9443a ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x563c82ea8e8a main
(pid=raylet, ip=172.31.32.178)     @     0x7f1b72f0eb97 __libc_start_main
(pid=raylet, ip=172.31.32.178)     @     0x563c82eb9d81 (unknown)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589306401 (unix time) try "date -d @1589306401" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e8000045fe) received by PID 17798 (TID 0x7f33262db800) from PID 17918; stack trace: ***
(pid=raylet, ip=172.31.32.178)     @     0x7f3325793890 (unknown)
(pid=raylet, ip=172.31.32.178)     @     0x7f3325084bf9 __poll
(pid=raylet, ip=172.31.32.178)     @     0x55d29eab3fe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.178)     @     0x55d29eab44e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.178)     @     0x55d29eab5817 redisConnect
(pid=raylet, ip=172.31.32.178)     @     0x55d29e9d3ed7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e9d5ee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e9d9f21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e9db991 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e974b56 ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e93843a ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55d29e84ce8a main
(pid=raylet, ip=172.31.32.178)     @     0x7f3324f91b97 __libc_start_main
(pid=raylet, ip=172.31.32.178)     @     0x55d29e85dd81 (unknown)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589306826 (unix time) try "date -d @1589306826" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e800005054) received by PID 20442 (TID 0x7fa2a7137800) from PID 20564; stack trace: ***
(pid=raylet, ip=172.31.32.178)     @     0x7fa2a65ef890 (unknown)
(pid=raylet, ip=172.31.32.178)     @     0x7fa2a5ee0bf9 __poll
(pid=raylet, ip=172.31.32.178)     @     0x556fa519cfe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.178)     @     0x556fa519d4e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.178)     @     0x556fa519e817 redisConnect
(pid=raylet, ip=172.31.32.178)     @     0x556fa50bced7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.178)     @     0x556fa50beee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x556fa50c2f21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x556fa50c4991 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x556fa505db56 ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x556fa502143a ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x556fa4f35e8a main
(pid=raylet, ip=172.31.32.178)     @     0x7fa2a5dedb97 __libc_start_main
(pid=raylet, ip=172.31.32.178)     @     0x556fa4f46d81 (unknown)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589305695 (unix time) try "date -d @1589305695" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e8000034b9) received by PID 13377 (TID 0x7fa156cd2800) from PID 13497; stack trace: ***
(pid=raylet, ip=172.31.32.178)     @     0x7fa15618a890 (unknown)
(pid=raylet, ip=172.31.32.178)     @     0x7fa155a7bbf9 __poll
(pid=raylet, ip=172.31.32.178)     @     0x55856aa47fe2 redisContextWaitReady
(pid=raylet, ip=172.31.32.178)     @     0x55856aa484e9 _redisContextConnectTcp
(pid=raylet, ip=172.31.32.178)     @     0x55856aa49817 redisConnect
(pid=raylet, ip=172.31.32.178)     @     0x55856a967ed7 ray::gcs::ConnectWithRetries<>()
(pid=raylet, ip=172.31.32.178)     @     0x55856a969ee9 ray::gcs::RedisContext::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55856a96df21 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55856a96f991 ray::gcs::RedisClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55856a908b56 ray::gcs::RedisGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55856a8cc43a ray::gcs::ServiceBasedGcsClient::Connect()
(pid=raylet, ip=172.31.32.178)     @     0x55856a7e0e8a main
(pid=raylet, ip=172.31.32.178)     @     0x7fa155988b97 __libc_start_main
(pid=raylet, ip=172.31.32.178)     @     0x55856a7f1d81 (unknown)
(pid=raylet, ip=172.31.32.178) *** Aborted at 1589305942 (unix time) try "date -d @1589305942" if you are using GNU date ***
(pid=raylet, ip=172.31.32.178) PC: @                0x0 (unknown)
(pid=raylet, ip=172.31.32.178) *** SIGTERM (@0x3e800003ac0) received by PID 14920 (TID 0x7fde0ce6c800) from PID 15040; stack trace: ***`


**This is an excerpt from the monitoring logs** 

 
`2020-05-12 11:12:06,382	INFO log_timer.py:17 -- NodeUpdater: i-09a347e492422f2ca: Ray start commands completed [LogTimer=2577ms]
2020-05-12 11:12:06,382	INFO log_timer.py:17 -- NodeUpdater: i-09a347e492422f2ca: Applied config e0de0455092ab5343c27bc4a61e25a6c2f3b3fdf [LogTimer=3343ms]
2020-05-12 11:12:08,071	INFO autoscaler.py:617 -- StandardAutoscaler: 4/4 target nodes (0 pending) (1 updating)
2020-05-12 11:12:08,071	INFO autoscaler.py:618 -- LoadMetrics: MostDelayedHeartbeats={'172.31.32.31': 35.56552076339722, '172.31.32.178': 15.295864343643188, '172.31.37.136': 10.178477048873901, '172.31.44.157': 5.1179986000061035, '172.31.44.212': 0.2572019100189209}, NodeIdleSeconds=Min=0 Mean=0 Max=0, NumNodesConnected=1, NumNodesUsed=1, ResourceUsage=2.0/2.0 CPU, 0.0 GiB/4.67 GiB memory, 0.0/1.0 node:172.31.44.212, 0.0 GiB/1.57 GiB object_store_memory, TimeSinceLastHeartbeat=Min=0 Mean=13 Max=35
2020-05-12 11:12:08,071	INFO autoscaler.py:77 -- Node 172.31.32.31 is newly setup, treating as active
2020-05-12 11:12:08,133	INFO autoscaler.py:617 -- StandardAutoscaler: 4/4 target nodes (0 pending)
2020-05-12 11:12:08,134	INFO autoscaler.py:618 -- LoadMetrics: MostDelayedHeartbeats={'172.31.32.178': 15.358659505844116, '172.31.37.136': 10.241272211074829, '172.31.44.157': 5.180793762207031, '172.31.44.212': 0.31999707221984863, '172.31.32.31': 0.06205034255981445}, NodeIdleSeconds=Min=0 Mean=0 Max=0, NumNodesConnected=1, NumNodesUsed=1, ResourceUsage=2.0/2.0 CPU, 0.0 GiB/4.67 GiB memory, 0.0/1.0 node:172.31.44.212, 0.0 GiB/1.57 GiB object_store_memory, TimeSinceLastHeartbeat=Min=0 Mean=6 Max=15
2020-05-12 11:12:08,922	INFO log_timer.py:17 -- AWSNodeProvider: Set tag ray-node-status=up-to-date on ['i-09a347e492422f2ca'] [LogTimer=132ms]
2020-05-12 11:12:09,045	INFO log_timer.py:17 -- AWSNodeProvider: Set tag ray-runtime-config=e0de0455092ab5343c27bc4a61e25a6c2f3b3fdf on ['i-09a347e492422f2ca'] [LogTimer=123ms]
2020-05-12 11:12:13,103	INFO autoscaler.py:617 -- StandardAutoscaler: 4/4 target nodes (0 pending)
2020-05-12 11:12:13,103	INFO autoscaler.py:618 -- LoadMetrics: MostDelayedHeartbeats={'172.31.32.178': 20.32809853553772, '172.31.37.136': 15.210711240768433, '172.31.44.157': 10.150232791900635, '172.31.32.31': 5.031489372253418, '172.31.44.212': 0.27751612663269043}, NodeIdleSeconds=Min=0 Mean=0 Max=0, NumNodesConnected=1, NumNodesUsed=1, ResourceUsage=2.0/2.0 CPU, 0.0 GiB/4.67 GiB memory, 0.0/1.0 node:172.31.44.212, 0.0 GiB/1.57 GiB object_store_memory, TimeSinceLastHeartbeat=Min=0 Mean=10 Max=20`

from my understanding the `StandardAutoscaler: 4/4 target nodes`  means that all 4 of my nodes are being utilized however the autoscaler load metrics show `NumNodesConnected=1, NumNodesUsed=1, ResourceUsage=2.0/2.0 CPU,` does this mean only 1 node is actually working? if yes, why isn't auto-scaling automatically shutting off the nodes not in use

**Comment by shreyagu** [comment]
can someone please respond @richardliaw @robertnishihara @ericl

**Comment by mfitton** [comment]
@shreyagu sorry, realize it's been a while now but I came across this searching for another issue. If you switch to using a different "instance type" in your autoscaler YAML file (specifically an instance type that has 3 or more cores), then the system that Ray spins up will be able to run the job.

**Comment by richardliaw** [comment]
closing because stale.
