### ISSUE TITLE
[sgd] Can TorchTrainer print out something every one or several iterations?

### ISSUE THREAD

**Issue by hkvision** [ray-project/ray#8413]
Seems by default TorchTrainer only returns stats after train() finishes? During the training, is there a way I get some information (for example loss values, or just something to indicate the training is happening in the background?) for each iteration or every several iterations?
Otherwise if one epoch training takes a lot of time, then I probably don't know what's going on. I may doubt whether the program crashes indeed or the training is just long.

@richardliaw

**Comment by richardliaw** [comment]
You can specify `num_steps`, which allows you to short-circuit the training. Also, `use_tqdm=True` is usually what I use.

**Comment by hkvision** [comment]
> You can specify `num_steps`, which allows you to short-circuit the training. Also, `use_tqdm=True` is usually what I use.

Thank you so much! @richardliaw Sorry for the late reply. `use_tqdm` works great!
If I specify `num_steps`, then every call for `train` only trains several batches, and would it be the case that some data won't get trained?

**Comment by richardliaw** [comment]
Ah yes; there's a workaround but we should push this. I'll make a new PR.
