### ISSUE TITLE
[tune][rllib] Evaluation using rollout through script

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#8415]
My team finished training and have a checkpoint file. I would like to evaluate the trained model from within Python so that I can set up breakpoints and analyze whats going on; I was getting some errors because I received the checkpoint file from my coworker that generated it on another computer and I am using it to evaluate on new data on my system. The only way I have seen to use rollout to evaluate is to use .rollout.py or use CLI, but I cannot set up break points using these methods. How can I call rollout.run() from within a script?

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.9
Python 3.6
Centos7

**Comment by janblumenkamp** [comment]
Maybe [this example](https://github.com/ray-project/ray/pull/8376/files) is helpful?
