### ISSUE TITLE
2 machines are not working together

### ISSUE THREAD

**Issue by Julianbaozi** [ray-project/ray#8417]
I set up two computers to communicate with each other. One is head node and one is worker. What should I do If I want to utilize resources from both machine for my computation? Should I run the script on both machines? I ran the script but it seems that only the head node is doing computations because almost all cpu was taken for the head node. And the maximum number of process is almost the same as when I use just one machine.

In my script, I fetch different github repositories data using github API, query them using ElasticSearch, and save the query results locally. In this process, do you have any suggestions that Ray can be useful?

**Comment by edoakes** [comment]
@Julianbaozi you'll need to start ray first on the head node, then on the worker to connect to the head node. The following documentation page should help:
https://docs.ray.io/en/master/using-ray-on-a-cluster.html#starting-ray-on-each-machine

**Comment by Julianbaozi** [comment]
Thank you for your reply. But I already set the two nodes by following the documentation page. It's still not working. In the web UI I can see the two nodes. But when I run only the cpu of head node is taken up.
