### ISSUE TITLE
Importing functions

### ISSUE THREAD

**Issue by Julianbaozi** [ray-project/ray#8419]
When I run script on the head node, it cannot import the function I defined on head node for the other worker node
![Screenshot from 2020-05-12 21-35-30](https://user-images.githubusercontent.com/44662651/81771847-ec61e580-9498-11ea-9af1-5a53511dd050.png)

following is 
![Screenshot from 2020-05-12 21-39-31](https://user-images.githubusercontent.com/44662651/81771900-229f6500-9499-11ea-810d-3576dd32aa53.png)

I'm using the same location but the user name is different. And I added the location to sys.path

**Comment by rkooo567** [comment]
Can you post a reproducible script? Also, I knew you already tried this, but I will leave this issue as a reference. https://github.com/ray-project/ray/issues/3116

**Comment by Julianbaozi** [comment]
I thought it was a different issue so I didn't try. I changed from...import... to import... and put it inside remote function. Now I can import the module but still cannot connect to my computer.

![Screenshot from 2020-05-12 23-02-42](https://user-images.githubusercontent.com/44662651/81776979-c04c6180-94a4-11ea-8427-283e97268836.png)

**Comment by Julianbaozi** [comment]
I guess it might because my laptop is using a public wifi? Thus others can't find me through both public IP or private iP?

**Comment by rkooo567** [comment]
@Julianbaozi I will close the issue because I believe it should've been resolved. Please reopen the issue if you think it is not! (And let's keep the conversation :) )
