### ISSUE TITLE
ray.get_resource_ids() is broken for actors

### ISSUE THREAD

**Issue by simon-mo** [ray-project/ray#8425]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
`ray.get_resource_ids()` works for tasks but not actors

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
ray.init()

@ray.remote
def a():
    print("task", ray.get_resource_ids())
a.remote()

@ray.remote
class A:
    def b(self):
        print("actor", ray.get_resource_ids())
a = A.remote()
a.b.remote()
```

output:
```
(pid=42139) actor {}
(pid=42138) task {'CPU': [(15, 1.0)]}
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
This isn't a bug, the actor has zero resources by default (need to set num_cpus=1). This is so infinite numbers of actors can be created.

**Comment by simon-mo** [comment]
ohhhh i see. got it
