### ISSUE TITLE
Load ray dashboard through a reverse proxy

### ISSUE THREAD

**Issue by franreysaycon** [ray-project/ray#8432]
### Describe your feature request
We need to be able to do a way to assign a base url or prefix for the requests the dashboard is making. It defaults to root which causes 404 errors under a reverse proxy path.

**Comment by rkooo567** [comment]
@allenyin55

**Comment by JoshBroomberg** [comment]
bump on this. We need to load ray inside a juypter server deploy on a subroute. We can do this using jupyter server proxying but the ray app is broken without the ability to add a base path

**Comment by richardliaw** [comment]
cc @mfitton can you look into this?

**Comment by mfitton** [comment]
Yep, I'll take a look, thanks for bringing it to my attention

**Comment by JoshBroomberg** [comment]
@mfitton any progress or advice on a work around for this?

If you give me some guidance, I would consider dedicating some of our resources to contributing a fix for this.

**Comment by mfitton** [comment]
Hey @JoshBroomberg I just looked into it, should be a pretty simple patch. I'm writing it up now and I'll mention this issue in the PR.

**Comment by mfitton** [comment]
If you change this line: https://github.com/ray-project/ray/blob/master/python/ray/dashboard/client/src/api.ts#L1 and rebuild the front-end, you can have it hit a custom URL. Instructions to build the dashboard are in the docs under installing from source: https://docs.ray.io/en/latest/installation.html  Normally in production, it hits `window.location.origin` 
I would have expected that if you loaded the app through the reverse proxy, then it should also hit the reverse proxy with its requests.

**Comment by ddl-kevin** [comment]
I haven't looked at modifying `window.location.origin`, but the blocker I run into is that the static assets mentioned in the `index.html` that is first loaded assume that the application is served from the root path. This appears to be a known issue / simple fix with the `create-react-app` framework. 

https://create-react-app.dev/docs/deployment#building-for-relative-paths

**Comment by JoshBroomberg** [comment]
@ddl-kevin - yeah so it seems like using `window.location.origin` means that after that initial load, things should work. But we need those initial loads to work.

**Comment by mfitton** [comment]
I see, so it seems like the Dashboard web server needs to be able to be mounted at urls other than `/`. It isn't just an issue with the static assets I don't think because the dashboard API server would give 404s even if the static asset was loaded.

**Comment by JoshBroomberg** [comment]
Yeah that sounds like the solution to the issues we're seeing

**Comment by sergeivolodin** [comment]
Made a hacky reverse proxy script that replaces the URLs in the html/js/css files of the dashboard at runtime. This way, one does not need to re-build the dashboard (in some setups it is impossible, for example, without npm and with limited disk space)

https://gist.github.com/sergeivolodin/2362e14fea8eca20ae271033d7b124ce

**Comment by niole** [comment]
Anyone mind if I take a stab at this? The reverse proxy solution works all right for us (@JoshBroomberg & I), but since some of the routes that the dashboard hits clash with the rest of our app. An in-code solution would definitely be a more stable/less disruptive solution in our use case

**Comment by niole** [comment]
Anyone mind if I take a stab at this? An in code change to this issue would help us (@JoshBroomberg  & I) create a stable solution to this problem

**Comment by rkooo567** [comment]
Hey currently we have no one who’s working on the issue. If you can make a pr that can have a stable fix, that’ll be awesome$

**Comment by rkooo567** [comment]
We just need to allow users to specify the root api path right?

**Comment by niole** [comment]
@rkooo567 pretty much. I think the most minimal definition of the solution is "Users should be able to add a prefix to api calls". It would probably be nice to not have to build the app in order to get the prefix in there, but I think that that is probably not completely possible bc of how url are determined for the static assets.

**Comment by niole** [comment]
@rkooo567 quick question: why is axios used on its own sometimes and other times this get (the wrapped fetch get) is used https://github.com/ray-project/ray/blob/master/dashboard/client/src/api.ts#L9? I want to write something that fits your best practices

**Comment by niole** [comment]
Also, I can't push up a branch to this repo. Can someone give my user the right permissions to open a pr so I can get some feedback on what I have so far? @rkooo567 
```sh
ERROR: Permission to ray-project/ray.git denied to niole.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

**Comment by allenyin55** [comment]
Hi @niole, we should [fork this repo ](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo#propose-changes-to-someone-elses-project) and make a PR from there instead of trying to push to this one.

**Comment by scottsun94** [comment]
IIUC, this issue has been fixed? Shall we close it now? @franreysaycon @JoshBroomberg @niole

**Comment by scottsun94** [comment]
I assume that this has been fixed due to no response. Closing it.
