### ISSUE TITLE
MPI APIs in Ray

### ISSUE THREAD

**Issue by programmerlwj** [ray-project/ray#844]
Hey,

I'm using the mpi4py API like AllReduce, Bcast etc, and I think these are really easy to use. For example, I can use the gather and reduce within the actor (actually is the actor with rank 0).

However, it seems that gather and reduce APIs should be outside the actors if I use ray. So I have to define another class except the actor's class to deal with gather or broadcast, is that right?

Thanks.

--Wanjun

**Comment by robertnishihara** [comment]
Are you running your mpi4py jobs from the commandline using the `mpirun` command? If so, it may not be straightforward to integrate that into a script that uses Ray.

In Ray, the equivalent of a broadcast at the moment is simply to pass an object ID into a bunch of remote function calls. For example

Gather can also be implemented simply by calling `ray.get` on a bunch of object IDs to collect them all in one place.

```python
import numpy as np
import ray

ray.init()

@ray.remote
def f(x):
    # Do something with x
    return 1

x = np.zeros(1000000)

# Put x in the object store and pass the ID into some remote functions.
# This basically implements a broadcast.
x_id = ray.put(x)
results = [f.remote(x_id) for _ in range(100)]

# Call ray.get to implement a gather operation.
ray.get(results)
```

That's how I'd do it through the Ray API. Note it may be possible to implement more optimized broadcast/gather operators. See the related discussion in #842.

**Comment by robertnishihara** [comment]
Closing this so we can have the conversation in #842.
