### ISSUE TITLE
[rllib] Set log_dir to something other than ~/ray_results?

### ISSUE THREAD

**Issue by jangkj09** [ray-project/ray#8440]
### What is your question?
This is a simple question, but somehow I am unable to find a straightforward answer, is there a way to change the default log_dir from ~/ray_results to something else?

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by stefanbschneider** [comment]
What was the answer?

**Comment by mimoralea** [comment]
I realize this is a pretty old question, but for those looking for the answer `local_dir` is what you want:

```
tune.run(trainable, num_samples=2, local_dir="./results", name="test_experiment")
```
