### ISSUE TITLE
[rllib] [tune] Iteration vs. Episode explanation

### ISSUE THREAD

**Issue by Leonolovich** [ray-project/ray#8458]
### What is your question?
I have a simple question, the answer for which that I could not find in the documentation. I am not familiar with using iterations in reinforcement learning, as I've previously seen that the train step ends when the episode is done. In the rllib case, it looks like the train step continues until the iteration is done? I am not clear on how iterations are used. 

Also, when is the network updated; after an episode or after an iteration?

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by ericl** [comment]
Iterations are just for metrics reporting. They have no connection with episodes; many episodes are executing concurrently and may span one or more iterations.

**Comment by Morphlng** [comment]
> I tried running only for 30 episodes by using this "stop={"episodes_total": 30}" but it ran for 40 episodes. I tried changing it to 10 and it ran for 20 episodes. How to control for how many episodes the tne.run() should execute? How to set number of iterastions?

The extra episodes may due to evaluation? You can try setting `evaluation_interval=0` to disable it.
