### ISSUE TITLE
Policy gradient implementation gives NaNs when rewards are all 0.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#846]
The problem is in the line here where we call `std()` on an array of all zeros.

https://github.com/ray-project/ray/blob/ea8da13938f28694f1364cb50899ba5833a9680e/python/ray/rllib/policy_gradient/policy_gradient.py#L152

**Comment by robertnishihara** [comment]
@pcmoritz was this fixed in #849?

**Comment by pcmoritz** [comment]
Yeah
