### ISSUE TITLE
Bump msgpack to 1.0.0 for Python

### ISSUE THREAD

**Issue by alecbrick** [ray-project/ray#8464]
We've started bumping msgpack to 1.0.0 in some of our repos at our company. However, some of our repos use Ray, which doesn't support version 1.0.0 for msgpack. We're hoping that Ray could support msgpack 1.0.0 - it doesn't look like there are too many breaking changes, and it looks like both major versions 0 and 1 can be supported. Thanks!

**Comment by rkooo567** [comment]
cc @simon-mo.

Thanks for reporting this @alecbrick . We will see if we can have time to work on this, but always feel free to contribute!
