### ISSUE TITLE
Ray. Remote using another python env

### ISSUE THREAD

**Issue by arita37** [ray-project/ray#8481]
### Describe your feature request

Allows execution function with different python env than parent ones, enabling fully distribution

**Comment by simon-mo** [comment]
Hi @arita37 can you elaborate on this requirement? Do you want different Python? Do they have different package requirements? Would there be version conflicts among different environments? 

Thanks!

cc @ijrsvt @edoakes

**Comment by arita37** [comment]
Thanks !

I have few python Env (ie conda) where I want to run for one model per environnement (!)
due to packages constraints... (TF 1.x with TF12.x,....). You can imagine other conflicts...


Is this possible with @remote ?


Was thinking to build my own subprocess launcher... (but best is to re-use Ray.... and not re-inventing the wheels).

**Comment by edoakes** [comment]
@arita37 this is now possible using new support for specifying environment variables for actors/tasks. Check out how we did this in Ray Serve:
https://github.com/ray-project/ray/pull/11743
