### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zzcNEU** [ray-project/ray#8482]
ray 0.8.5,when I try to use ray， it occurs  Ray must be imported before pickle5 because Ray requires a specific version of pickle5 (which is packaged along with Ray.

I want to know it must import  pickle5 before import ray,  Right?

**Comment by suquark** [comment]
yes, we are using an internal version of pickle5, because the current pickle5 has memory leak issues. so we have to import ray before importing the pickle5 library.

I have created a PR in the upstream (pickle5-backport), it would address the problem once merged.
