### ISSUE TITLE
[rllib] Allow JsonReader to read output files w/o a loop

### ISSUE THREAD

**Issue by acxz** [ray-project/ray#8496]
### Describe your feature request
I am currently using the [Output API](https://docs.ray.io/en/latest/rllib-offline.html#output-api) to log data throughout the training iterations. However, when trying to parse the output *.json data files, I need to use the `JsonReader.next()`. Since I do not know the number of sample batches in the json output files I call the `JsonReader.next()` an arbitrarily high amount of times. However, after a certain point the JsonReader will start looping back and data will be repeated. 

Ideally I would like for JsonReader to include a method that can read through the *json output files in one shot and return the data as a dict.

**Comment by Catypad** [comment]
Hi @acxz ! Do you already know how to solve this problem? Thank you!

**Comment by acxz** [comment]
Nope I haven’t gotten around to figuring this out.

**Comment by acxz** [comment]
@ericl do you have any suggestions on this issue?

**Comment by annaprok** [comment]
@acxz @ericl @Catypad  Did you manage to solve the issue? I am having the same problem :(

**Comment by acxz** [comment]
@annaprok sorry I never got the time to visit this again, I haven't been using rllib with my research lately so this issue is very low on my radar. I'd suggest opening up another issue to get better visibility than commenting on a closed issue.
