### ISSUE TITLE
pickle5

### ISSUE THREAD

**Issue by zzcNEU** [ray-project/ray#8497]
hello，Ray version is 0.8.5 and pickle5 is 0.0.9 on my local pc. But,
![image](https://user-images.githubusercontent.com/38434094/82282513-932d1100-99c6-11ea-9f22-1f15f0026e8e.png)
I have imported the pickle5. SO, CAN YOU HELP ME?

**Comment by pcmoritz** [comment]
Hey @zzcNEU thanks for reporting this! We are upstreaming our changes to pickle 5 (https://github.com/pitrou/pickle5-backport/pull/15 and https://github.com/pitrou/pickle5-backport/pull/16) and will update Ray to use that version, so this error will go away soon.

**Comment by pcmoritz** [comment]
@suquark fixed this now on the latest master!
