### ISSUE TITLE
[docs] Issue on `index.rst`

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#8505]
Just my 2c as an initial reaction to the new warning at the top:
<img width="720" alt="Screen Shot 2020-05-19 at 1 28 26 PM" src="https://user-images.githubusercontent.com/140710/82358515-a21ac000-99d4-11ea-8bbe-08c8febc9208.png">

The box at the top of the documentation is very confusing (especially to new users):

The two options are:

- This document is for the master branch. Visit the latest pip release documentation here.
- This document is for the latest pip release. Visit the master branch documentation here.

But why is it a warning? This implies I'm on the wrong page. I click the link and end up on another page with a **warning** again.

Which version should a (new) user look at?
Present the user with a reason to switch to either version.

It is not clear that master is not also the latest release. Also the word "latest" vs. "stable" makes it confusing as to what "latest" refers to here.

**Comment by ericl** [comment]
What if we changed `warning` => `tip`, and renamed "latest pip release" to "stable release"

@richardliaw

**Comment by richardliaw** [comment]
Sounds good!

**Comment by drozzy** [comment]
One more nitpick: it's not really clear what one needs to do to install `rllib` from master.
Seems like just installing ray from the wheel works. Is that correct?

**Comment by drozzy** [comment]
Due to the new documentation this is no longer an issue.
