### ISSUE TITLE
Need to use port 8888

### ISSUE THREAD

**Issue by pitoupitou** [ray-project/ray#8513]
Hi

I need to use port 8888 on my cluster in order to use a particular Library.
But Ray is using port 8888 by default for metrics, how can I change this to another port ?

Thank you

**Comment by ericl** [comment]
Unfortunately I don't think this is possible to set at the moment, you have to change this value here and recompile: https://github.com/ray-project/ray/blob/a76434ccde61bef853cb7655b22a5d67739a4913/src/ray/raylet/main.cc#L48

**Comment by pitoupitou** [comment]
Thanks for your amazing support Eric

**Comment by rkooo567** [comment]
@mfitton We should probably remove this default port assignment because it is not used at all.

**Comment by ericl** [comment]
Labeling as P1 since afaik this just breaks Ray / other applications when port 8888 is used, which is pretty common.

**Comment by ericl** [comment]
@rkooo567 is this fixed?

**Comment by rkooo567** [comment]
We will remove this port from this PR as a part of new metrics infra. https://github.com/ray-project/ray/pull/9361#diff-78dfceb75ccec71df2e6e33be6d58830L47 So you can just close it.
