### ISSUE TITLE
Reusing resources between training and evaluation.

### ISSUE THREAD

**Issue by cpn** [ray-project/ray#8515]
### Describe your feature request

For now setting the `evaluation_num_workers` to a stricly positive number allocates additional CPUs for the evaluation workers. Is this because the evaluation and training happen in parallel? If not would it be possible to reuse the resources?

**Comment by ericl** [comment]
The reason is that the workers are stateful. For example, they may contain partial episode rollouts. It would be potentially misleading to reuse the same set of workers for evaluation without flushing this state, which would impact training. Hence, the separation of train/eval workers.

**Comment by cpn** [comment]
@ericl Thank you for your answer. Nonetheless, why is it not possible to reuse the resources themselves, not the workers? The same CPUs for example. Since, as far as I understand, the evaluation does not happen in parallel with the training, just reuse CPUs during the evaluation that one used during the training.

**Comment by ericl** [comment]
Ah, that is doable. One thing you could do is to create more fake CPUs in Ray, by setting ray.init(num_cpus=N). This will allow more workers than real CPUs to be created.
