### ISSUE TITLE
How to set lock?

### ISSUE THREAD

**Issue by Julianbaozi** [ray-project/ray#8516]
I want to set lock to a command inside a class method.

from threading import Lock
lock = Lock()
class ....:
  def ...:
        with lock:
            self.feed_items(items)

It gets:
TypeError: can't pickle _thread.lock objects

**Comment by rkooo567** [comment]
I am not sure if I understood what you were asking. Would you mind a script that I can run with  ? triple backticks? Example: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

```python3
Code here.
```

**Comment by rkooo567** [comment]
Actually, if what you meant is adding a lock defined outside the class to be used within ray actor or tasks, that’s not possible because locks are not serializable. Consider initiating the lock within a task or actor instead.
