### ISSUE TITLE
Upload wheels that we build in Travis.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#853]
Now that we're building all of the wheels every time Travis runs (as of #852), we should upload all of the wheels somewhere (where?). That way, if we're trying to figure out when a bug first appeared, we can programmatically iterate through the commit history, install ray from each wheel, and see when the bug appeared. It also would allow people to use the latest features more easily without waiting for the next release.

We would need to do the following.
1. Figure out where to store the wheels.
2. Make sure to only upload them from builds on the master branch and not from PRs.

**Comment by xhochy** [comment]
Have a look at https://github.com/xhochy/pyarrow-macos-wheels/blob/master/.travis.yml#L53 There we upload all wheels to bintray. Sadly you cannot use bintray as a python package index but at least it is something compatible with Travis and free for opensource projects.

**Comment by robertnishihara** [comment]
Thanks for the tip! We'll check that out.
