### ISSUE TITLE
Is there a way to block via the ray CLI until the ray submit python script has finished ?

### ISSUE THREAD

**Issue by andrewv99** [ray-project/ray#8534]
Environment:

ray 0.7.7
OS: Ubuntu 18.04
Python: 3.6.8
Using autoscaler on AWS

Background: I am trying to automate the execution of a ray tune job with other tasks.

Is there a way using the ray CLI to block until the script being executed by 'ray submit' has finished running (or poll/monitor something on the head until the script has finished running) ?

If not possible via the ray CLI, is there a short Python script I can use that will effectively do the same thing ?

Thanks for any help you can provide.

**Comment by rkooo567** [comment]
@richard4912

**Comment by richardliaw** [comment]
Doesn't `ray submit` work already?

**Comment by richardliaw** [comment]
It should block until the script is finished.
