### ISSUE TITLE
Potential discrepancy in `max_failures` default value

### ISSUE THREAD

**Issue by mimoralea** [ray-project/ray#8538]
The documentation says `max_failures` defaults to 3.

https://github.com/ray-project/ray/blob/9a83908c460a8bdf38b665c290a003e492a87e16/python/ray/tune/tune.py#L176

But in the function, the default value is 0.

https://github.com/ray-project/ray/blob/9a83908c460a8bdf38b665c290a003e492a87e16/python/ray/tune/tune.py#L87

**Comment by rkooo567** [comment]
@richard4912

**Comment by richardliaw** [comment]
This is fixed :)
