### ISSUE TITLE
[ray] Nightly wheel is not updated

### ISSUE THREAD

**Issue by AnanthHari** [ray-project/ray#8542]
### What is the problem?

I am using the latest nightly wheel: Downloaded on May 21 at 10 pm EDT. 
Ray version: 0.9.0.dev0
Python version: 3.7.6
OS: Ubuntu 19.10

There are three tests present in `ray/rllib/agents/dqn/tests` directory on the `master` branch. 

In the latest nightly wheel, the `tests` directory itself is absent. We can see that the earliest commit in `tests` occurs on Feb 10, 2020: https://github.com/ray-project/ray/commits/master/rllib/agents/dqn/tests

Is there a regularly updated version that contains all of the latest commits? I would like to not miss the improvements/bug fixes that were made during the past several months.

Thank you!

**Comment by rkooo567** [comment]
@mehrdadn

**Comment by mehrdadn** [comment]
I'm not sure unfortunately. cc @ericl

**Comment by ericl** [comment]
We don't include the test packages. Please reopen if you can confirm via the code that the wheel is really out of date.
