### ISSUE TITLE
[ray] Is it bad practice to use sockets (pyzmq) to communicate between ray remote functions?

### ISSUE THREAD

**Issue by cyoon1729** [ray-project/ray#8545]
I have a `send()` function that generates random numpy arrays at every time step, and a `recv()` function that receives and prints those generated arrays. I am using `zmq` for sending/receiving the numpy arrays across the processes, and `pyarrow` to serialize and deserialize arrays. I wasn't able to find any examples using ray and zmq together, so I would like to know whether this is bad practice. If so, is there a recommended way to have the distributed-ly running processes communicate with each other using ray?

Thank you so much! 

Pasted below is minimal working code (on Ubuntu 18.0.4, python=3.6.9, pyzmq=19.0.1, ray=0.8.5, pyarrow=0.17.1):

```python
import numpy as np
import pyarrow as pa
import ray
import zmq
ray.init()


@ray.remote
def send():
    port = 5556
    context = zmq.Context()
    send_socket = context.socket(zmq.PUSH)
    send_socket.bind(f"tcp://127.0.0.1:{port}")

    while True:
        msg = np.random.rand(1, 3) # this could be larger, e.g. numpy-ed torch neural network weights
        object_id = pa.serialize(msg).to_buffer()
        send_socket.send(object_id)

@ray.remote
def recv():        
    port = 5556
    context = zmq.Context()
    recv_socket = context.socket(zmq.PULL)
    recv_socket.connect(f"tcp://127.0.0.1:{port}")

    while True:
        object_id = recv_socket.recv()
        msg = pa.deserialize(object_id)
        print(msg)


if __name__ == "__main__":
    ray.wait([send.remote(), recv.remote()])
```
## Note:
I had to use pyarrow for serialization since ray object id's (obtained via `ray.put()`) could not be passed through zmq sockets; doing so gives the error below:  
```
ObjectID(45b95b1c8bd3a9c4ffffffff0100008801000000) does not provide a buffer interface.
```

**Comment by rkooo567** [comment]
Ray already handles inter-process communication as well as serialization using Pyarrow. You can just do.

```python3
import ray
ray.init()

@ray.remote
class ReceiveServer:
    def recv(self, msg):
        print(msg)

@ray.remote
def send(receive_server_handle):
    while True:
        msg = np.random.rand(1, 3)
        receive_server_handle.recv.remote(msg)

recv_server_handle = ReceiveServer.remote()
ray.wait(send.remote(recv_server_handle))
```
This should do the same thing.

**Comment by cyoon1729** [comment]
@rkooo567 Thank you so much! Will give it a try.

**Comment by cyoon1729** [comment]
@rkooo567 Thank you so much for your response and the example above. I would like to ask another question:
 
Say, for instance, I have the `ReceiveServer` above to store the `msg` in an internal storage `self.storage (deque)` when `recv()` is called in `send()`, while continuously (as in a `while: True` loop) sampling data from `self.storage` and processing it in another member function `process()`.

If I were to run `process.remote()` asynchronously with respect to `send()`, would a mutual exclusion of `ReceiveSercer.storage` be enforced? Is this legal? 

The code below implements what I tried to describe, but does not print anything:
```python
import ray
import numpy as np
from collections import deque
import random

ray.init()

@ray.remote
def send(receive_server_handle):
    while True:
        msg = np.random.rand(1, 3)
        receive_server_handle.recv.remote(msg)


@ray.remote 
class ReceiveServer:
    def __init__(self):
        self.storage = deque(maxlen=2000)

    def recv(self, data):
        self.storage.append(data)
        
    def process(self):
        while True:
            if len(self.storage) > 0:
                data = random.sample(self.buffer, 1)
                
                # do something to data
                # ...

                print(data)  # does not print anything 

receive_server = ReceiveServer.remote()
ray.wait([send.remote(receive_server), receive_server.process.remote()])
```
If it is indeed acceptable to use ray, pyarrow, and zmq together as in the first example, I would like to proceed with that. Are there any glaring issues with doing so? 

Thank you so much again for your time.

**Comment by rkooo567** [comment]
It doesn't print anything because Actor (class with @ray.remote) is running in a single process, and `recv` will never run because `process` is occupying the process (because it is running a while loop). 

mutual exclusion of ReceiveSercer.storage be enforced? Is this legal?: Yes. Ray handles this issue and you never need to worry about locking. 

There's nothing wrong with using zmq and pyarrow if you have the right reason. It is just not efficient because what you try to achieve using zmq and pyarrow is what Ray exists for. Ray is a distributed computing framework that abstracts inter-process communication problems (and many others).    

You can make this work in this way.  
```python3
import ray
import numpy as np
from collections import deque
import random
import asyncio

ray.init()

@ray.remote
def send(receive_server_handle):
    while True:
        msg = np.random.rand(1, 3)
        receive_server_handle.recv.remote(msg)


@ray.remote 
class ReceiveServer:
    def __init__(self):
        self.storage = deque(maxlen=2000)

    async def recv(self, data):
        self.storage.append(data)
        
    async def process(self):
        while True:
            await asyncio.sleep(0.0)
            if len(self.storage) > 0:
                data = random.sample(self.buffer, 1)
                
                # do something to data
                # ...

                print(data)  # does not print anything 

receive_server = ReceiveServer.remote()
ray.wait([send.remote(receive_server), receive_server.process.remote()])
```

**Comment by cyoon1729** [comment]
Thanks @rkooo567! This was very helpful.

**Comment by ajaybabu20** [comment]
@uchiiii ya I think it uses Plasma store to store the data and use between the each workers
https://arrow.apache.org/blog/2017/08/08/plasma-in-memory-object-store/
