### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by furunding** [ray-project/ray#8547]
When build docker in terminal, the building process report an error as follows：
(base) inspur@inspur-NF5468M5:~/frd/ray$ ./build-docker.sh 
+ [[ 0 -gt 0 ]]
+ '[' ']'
+ docker build -t ray-project/base-deps docker/base-deps
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM ubuntu:xenial
 ---> 005d2078bdfa
Step 2/4 : RUN apt-get update     && apt-get install -y         git         wget         cmake         build-essential         curl         unzip         libgtk2.0-dev         zlib1g-dev         libgl1-mesa-dev     && apt-get clean     && echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh     && wget         --quiet "https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh"         -O /tmp/anaconda.sh     && /bin/bash /tmp/anaconda.sh -b -p /opt/conda     && rm /tmp/anaconda.sh     && /opt/conda/bin/conda install -y         libgcc python=3.6.9     && /opt/conda/bin/conda clean -y --all     && /opt/conda/bin/pip install         flatbuffers         cython==0.29.0         numpy==1.15.4
 ---> Using cache
 ---> 842e44a9fa92
Step 3/4 : RUN /opt/conda/bin/pip uninstall -y dask
 ---> Using cache
 ---> e2eddf697c9c
Step 4/4 : ENV PATH "/opt/conda/bin:$PATH"
 ---> Using cache
 ---> 56af432ed516
Successfully built 56af432ed516
Successfully tagged ray-project/base-deps:latest
+ git rev-parse HEAD
++ git rev-parse HEAD
+ git archive -o ./docker/deploy/ray.tar ed2f434593e27a9a72feb4eeadd96e20ba895287
+ '[' ']'
+ docker build --no-cache -t ray-project/deploy docker/deploy
Sending build context to Docker daemon  61.72MB
Step 1/8 : FROM ray-project/base-deps
 ---> 56af432ed516
Step 2/8 : ADD ray.tar /ray
 ---> ac50236363c8
Step 3/8 : ADD git-rev /ray/git-rev
 ---> f91890b2aa34
Step 4/8 : RUN /ray/ci/travis/install-bazel.sh
 ---> Running in ffc86927f952
Platform is Linux (or WSL).
**_fatal: Not a git repository (or any of the parent directories): .git_**

Anybody can help?

**Comment by rkooo567** [comment]
cc @ijrsvt

**Comment by ijrsvt** [comment]
@furunding does it actually stop there, or does it keep running?

In my experience it prints this message, hangs for a couple seconds and then continus.
