### ISSUE TITLE
[tune] A spreadsheet of final results from each trial

### ISSUE THREAD

**Issue by alexzhou907** [ray-project/ray#8548]
I wonder whether we can create a spreadsheet in the base dir and on each trial's exit we log the trial's final metric to the spreadsheet. I tried to figure out how to do a workaround but it seems there's no exposed interface that allows logging to any files in the base dir on each trial's trial exit.

**Comment by richardliaw** [comment]
You should be able to do this via the Logger interface: https://docs.ray.io/en/master/tune/api_docs/logging.html

**Comment by richardliaw** [comment]
(logger.close) is what you want.
