### ISSUE TITLE
[Dashboard] Integrate TensorBoard in Dashboard

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#8554]
### Describe your feature request

I have been using Ray for over 6 months, I used the dashboard only less than 5 times. If you can integrate TB into the dashboard, it would be great I think, for example, auto-config TB and run it in the dashboard. Since as you know, it is very annoying to launch TB manually every time by setting the port host and other settings and users can monitor the CPU/memory/disk usage in the Dashboard. When running the ray task, it launches the dashboard with TB integrated and shows the links in the logs. it would be great if the dashboard with TB still running background even the Ray task exits.

Since remembering the link (the port) of the Dashboard is not very easy every time if many tasks are launched.  I think maybe the Dashboard can launch the main site like localhost:2039, and there are many tabs which show each ray tasks, users can stop the tabs. When a ray task launches, it can auto-config on the main process of the dashboard can users can open the corresponding tab to monitor the task.

**Comment by rkooo567** [comment]
Based on @richard4912 You should be able to access tensorboard through the Tune dashboard.
