### ISSUE TITLE
Use an external redis server for ray

### ISSUE THREAD

**Issue by avinayak** [ray-project/ray#8557]
Hi,
I'm trying to use an external redis server that's accessible by all machines in my cluster. So, I'd expect, something like 
`$ ray start --head --address='redis.internal.net:6379'` to work, but instead I get,

`Exception: If --head is passed in, a Redis server will be started, so a Redis address should not be provided.`

Any way I can make this work? 
Thanks

**Comment by rkooo567** [comment]
The master shard of Redis should be started in the head node for now unfortunately. 

However, we are currently in active progress supporting standalone and pluggable GCS (Redis is GCS in your case), so that you can use standalone Redis or other storages like SQL as GCS.
