### ISSUE TITLE
[core] Remote task cancellation not working as expected.

### ISSUE THREAD

**Issue by allenyin55** [ray-project/ray#8565]
### What is the problem?
Ray task cancellation returns error `TypeError: No owner found for object.` when cancelling the task from a different function.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: latest master (2e5e789294dccaa53b34abc6e46925a9041f9681)
Python: 3.7.4
OS: macos 10.15.3 

### Reproduction (REQUIRED)
The following script doesn't work
```python
import os
import ray
import time

ray.init()
FILE_NAME = "db"

@ray.remote
def save():
    time.sleep(100)


def write():
    with open(FILE_NAME, "wb") as f:
        object_id = save.remote()
        f.write(object_id.binary())
       

def read():
    with open(FILE_NAME, "rb") as f:
        binary_id = f.read()
        object_id = ray.state.binary_to_object_id(binary_id)
        ray.cancel(object_id)


if __name__ == "__main__":
    write()
    try:
        read()
    finally:
        os.remove(FILE_NAME)
```

If we return the object_id in `write`, then it works.
```python
import os
import ray
import time
ray.init()
FILE_NAME = "db"

@ray.remote
def save():
  time.sleep(100)

def write():
  with open(FILE_NAME, "wb") as f:
    object_id = save.remote()
    f.write(object_id.binary())
    return object_id ####NEW

def read():
  with open(FILE_NAME, "rb") as f:
    binary_id = f.read()
    object_id = ray.state.binary_to_object_id(binary_id)
    ray.cancel(object_id)

if __name__ == "__main__":
  x = write() ####NEW
  try:
    read()
  finally:
    os.remove(FILE_NAME)
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ijrsvt** [comment]
Hey @stephanie-wang , it looks like this could be a problem with `ReferenceCounter::GetOwner`, but I'm not 100% sure.

**Comment by stephanie-wang** [comment]
This behavior is expected. ObjectIDs that are serialized and deserialized out-of-band (using object_id.binary() instead of something like pickle.dumps(object_id)) are not expected to work properly and none of the normal operations like ray.get will work either.

**Comment by allenyin55** [comment]
Is my script expected to work if I use `pickle.dumps(object_id)` & `pickle.loads(binary_id)` to serialize and deserialize?

I tried and it still gave the same error `TypeError: No owner found for object.`

```python
import os
import ray
import time
import pickle

ray.init()
FILE_NAME = "db"

@ray.remote
def save():
    time.sleep(100)


def write():
    with open(FILE_NAME, "wb") as f:
        object_id = save.remote()
        f.write(pickle.dumps(object_id))
       
def read():
    with open(FILE_NAME, "rb") as f:
        binary_id = f.read()
        object_id = pickle.loads(binary_id)
        ray.cancel(object_id)


if __name__ == "__main__":
    write()
    try:
        read()
    finally:
        os.remove(FILE_NAME)
```
