### ISSUE TITLE
ray failed to build when checking out pickle5-backport commits

### ISSUE THREAD

**Issue by yunqu** [ray-project/ray#8567]
### What is the problem?
This is on Ray-0.8.5 tag.  This line failed:
https://github.com/ray-project/ray/blob/ray-0.8.5/build.sh#L134
when I try to build the wheel. 

I think this only happens recently - maybe the pickle5-backport github breaks something. I used to be able to build the wheel without issues.

### Reproduction (REQUIRED)

To reproduce:
```
git clone https://github.com/suquark/pickle5-backport
cd pickle5-backport
git checkout 8ffe41ceba9d5e2ce8a98190f6b3d2f3325e5a72
```
Gives the following error:
```
fatal: reference is not a tree: 8ffe41ceba9d5e2ce8a98190f6b3d2f3325e5a72
```

If we cannot run your script, we cannot fix your issue.

- [x ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by suquark** [comment]
@yunqu I have recovered the revision 8ffe41ceba9d5e2ce8a98190f6b3d2f3325e5a72. Could you try it again?

**Comment by yunqu** [comment]
@suquark  Thank you very much. It has been resolved now.
