### ISSUE TITLE
[rllib] Pass kwargs to Environment instead of a config dict

### ISSUE THREAD

**Issue by drozzy** [ray-project/ray#8570]
Presently the arguments are passed as a config to the environment class.
This makes it really hard to:

1. See what the arguments to the constructor are
2. Provide default values as part of the constructor 

I suggest a better implementation is to pass the config to the environment constructor as `**config`. This way it is converted to keyword args.

So instead of this:

```
class SimpleCorridor(gym.Env):
    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(0.0, self.end_pos, shape=(1, ))
 ```

we have this:

```
class SimpleCorridor(gym.Env):
    def __init__(self, corridor_length):
        self.end_pos = corridor_length
        self.cur_pos = 0
        self.action_space = Discrete(2)
        self.observation_space = Box(0.0, self.end_pos, shape=(1, ))
 ```

Note that this wouldn't change the calling signature at all, you would still do:
```
tune.run(
    "PPO",
    config={
        "env": SimpleCorridor,
        "num_workers": 4,
        "env_config": {"corridor_length": 5}})
```

**Comment by ericl** [comment]
This is pretty sensible, though we'd have to figure out to do it in a backwards compatible way.

One straw man is to deprecate `env_config` and replace it with `env_kwargs`, though this would be making the config temporarily messier.

**Comment by drozzy** [comment]
Closing this as it is no longer relevant to me. I've gotten used to config as it is.

**Comment by Mark2000** [comment]
For anybody else who encounters this as I did transitioning from SB3/gymnasium workflows to Ray, a quick workaround is this environment wrapper function:
```
def unpack_config(env):
    class UnpackedEnv(env):
        def __init__(self, env_config):
            super().__init__(**env_config)

    return UnpackedEnv
```
The environment can then be set with
```
    config = config.environment(
        env=unpack_config(EnvClassThatUsesKwargs),
        env_config=env_kwarg_dict,
    )
```
