### ISSUE TITLE
SEED RL implementation

### ISSUE THREAD

**Issue by jarlva** [ray-project/ray#8578]
SEED (Scal-able, Efficient Deep-RL), a recent RL google development, managed to perform much faster than [any other framework to-date](https://arxiv.org/pdf/1910.06591.pdf). It's distributed architecture  seems a perfect fit for Ray. 
Would it be possible to port the [current implementation](https://github.com/google-research/seed_rl) (with Gym support) into Ray (preferably in pytorch)?

**Comment by ChrisChiasson** [comment]
I noticed this paragraph in the [scaling guide](https://docs.ray.io/en/master/rllib-training.html#scaling-guide):

> Finally, if both model and environment are compute intensive, then enable remote worker envs with async batching by setting remote_worker_envs: True and optionally remote_env_batch_wait_ms. This batches inference on GPUs in the rollout workers while letting envs run asynchronously in separate actors, similar to the SEED architecture. The number of workers and number of envs per worker should be tuned to maximize GPU utilization. If your env requires GPUs to function, or if multi-node SGD is needed, then also consider DD-PPO.
