### ISSUE TITLE
Use ray as a distributed task runner

### ISSUE THREAD

**Issue by aefn** [ray-project/ray#8580]
I want to use the distributed feature of ray to run my code in a cluster of computers.
First I was trying to use python multiprocessing module to achieve my goal but then I got familiar with ray. It sounds awesome at the beginning. I add a ray.remote at top of my class and then run my code in parallel. I thought that achieved my goal. It works for 5 objects at a same time.
Then I tried to create more than 5 objects from my class and run them in parallel.
I face with two issue:

1. I got a warning 
`
WARNING worker.py:1090 -- WARNING: 6 PYTHON workers have been started. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
`
2. Each worker consume 30 to 50 mb of ram which I think it is a lot and I don't know how can I reduce it.

now let me to clarify my scenario:
I want to load test a remote API. I have a class sensor which calls the API.
I want to create 1000 sensor object and distribute them and start sending my packets at the same time.
As you know each computer has a limit in bandwidth for that reason I need to distribute my objects and the distribution feature of ray is what I want to get benefit of.

Scenario:
- create 1000 sensor object
- results = 1000 obj connect in parallel
- sendResults = if all connect then 1000 obj start to send packets in parallel
- if all sent 1000 obj disconnect

for you consideration:
- I am aware about load testing frameworks like locust, unfortunately I could not use it
- I could implement my scenario in one computer by using multiprocessing, I have to be able to distribute my code.

**Comment by rkooo567** [comment]
This is a pretty cool use case btw! 

1. If you add @ray.remote to classes, that means that you are creating an actor. Actor is a class that is occupying each worker (process). You received the warning because you tried to create 1000 actors meaning you tried to create 1000 Ray workers (which is 1000 processes). 
2. Ray's idle worker consumes 20~30mb memory (and it will reduce the memory usage later if you don't do anything). It is because each Ray worker has cpp and Python threads running concurrently to coordinate cluster level parallelism.

**Comment by aefn** [comment]
@rkooo567 thanks for your answer. I knew about the actors and as I said I implemented my scenario  by using multiprocessing module too. What I want to achieve is using the maximum available bandwidth that I have. For one pc I did that by creating multiple processes and each process in parallel is using my internet connection.
Now my question is that can I use ray to do the same but distributed?
As actor are processes if I create a cluster with 4 node and distribute my actors into the cluster.
Do you think I achieved my goal?

**Comment by rkooo567** [comment]
Yes. That's exactly what Ray is about! You might need to figure out how to reduce overhead as it sounds like you will have 250 workers per node though. Let us know if you need any other help!
