### ISSUE TITLE
[rllib] Exporting Ray RLlib Policy Models for simple out of the box loading and evaluation

### ISSUE THREAD

**Issue by rtolsma** [ray-project/ray#8583]
I have a PPO policy based model that I train with RLLib using the Ray Tune API on some standard gym environments (with no fancy preprocessing). I have model checkpoints saved which I can load from and restore for further training.

I want to export my model for production onto a system that should ideally have no dependencies on Ray or RLLib. Is there a simple way to do this?

I know that there is an interface `export_model` in the `rllib.policy.tf_policy` class, but it doesn't seem particularly easy to use. For instance, after calling `export_model('savedir')` in my training script, and in another context loading via `model = tf.saved_model.load('savedir')`, the resulting `model` object is troublesome (something like `model.signatures['serving_default'](gym_observation)` doesn't work) to feed the correct inputs into for evaluation. I'm ideally looking for a method that would allow for easy out of the box model loading and evaluation on observation objects

**Comment by mcrowson** [comment]
Similar to #9123 Simple flow for train, save, load, test would be really appreciated.

**Comment by matdoering** [comment]
I would also be interested in this. Is there a way to serve the Tensorflow model that is trained by RLlib without explicitly using RLlib? There seems to be the `export_model` function but the reports indicate that there seems to be a problem with the exported model. Is that true? In any case how would the output encode the optimal actions in a multi-agent setting?

**Comment by strategynet123** [comment]
ExportFormat.H5 should serialise the model at each checkpoint, the resulting .h5 file is portable and can be used to load a model in isolation of ray/rllib for independent inference and evaluation.  But in the latest version it doesn't create any model files, nor does it generate a warning - it could be in the way I'm using it.  Generally the documentation on how to load a model is very sparse or is buried somewhere.

    results = tune.run(args.run, 
                        config=config, 
                        # stop={"training_iteration": 2}, 
                        checkpoint_freq=1, 
                        **export_formats=[ExportFormat.H5],** 
                        checkpoint_at_end=True
                    )

**Comment by chunky** [comment]
I'm in exactly the same boat; the tools in ray rllib are fabulous for training up effective agents [I'm using the command-line "rllib" tool, no code even necessary]. I'd like to then deploy the trained agents without needing the ray infrastructure; in particular, I'd like to deploy to standalone TFLite.

A sample that demonstrates how to export the model, and then an example of how to actually uses it with the gym, would be wonderful. [I'm the Modeling & Sim guy, more than an AI guy; the Gym is my centerpiece, and I'm pretty uncomfortable with the rest of the tensorflow stuff].

I notice that rllib train command line has "--export-formats EXPORT_FORMATS", but unfortunately that only exports at the end of the experiment. How effective the training is [and so, how long the experiment needs to be] varies wildly with a bunch of other parameters in my Gym. Automatically doing that export in association with *every* checkpoint, not just the last one, would really improve my project lifecycle [and shrink the development OODA loop from "days" to "grab exports as they become ready while training, for experimenting with the next steps"]

**Comment by chunky** [comment]
For what it's worth, I got so frustrated by this specific issue that I moved to stable-baselines3, which culminated in a longer-but-smoother export process: https://github.com/chunky/sb3_to_coral

**Comment by antoine-galataud** [comment]
I came across the same situation (needed fast and lightweight inference from a trained policy). I started working on it, check [here](https://github.com/airboxlab/rllib-fast-serve) and don't hesitate to report bugs/enhancement requests.
