### ISSUE TITLE
Cannot overwrite named actor even after killing it

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8593]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Latest ray

There doesn't seem to be a way to reuse an actor name.

### Reproduction (REQUIRED)
```
>>> b = Bar.options(name="bar").remote()
>>> b = ray.get_actor("bar")
>>> ray.kill(b)
>>> b = Bar.options(name="bar").remote()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/Desktop/ray/python/ray/actor.py", line 397, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **options)
  File "/home/eric/Desktop/ray/python/ray/actor.py", line 496, in _remote
    "ray.get_actor('{name}')".format(name=name))
ValueError: The name bar is already taken.
Please use a different name or get the existing
actor using ray.get_actor('bar')
```

**Comment by ericl** [comment]
@edoakes

**Comment by rkooo567** [comment]
This has been an issue from long time ago actually. I was planning to work on fixing this issue next sprint. Is it urgent to fix it?

**Comment by ericl** [comment]
It's not urgent, but does seem like a regression from the previous experimental implementation of named actors.

**Comment by rkooo567** [comment]
Related issue here. https://github.com/ray-project/ray/issues/7591

**Comment by rkooo567** [comment]
This is urgent for @allenyin55 and we will work on it next week.
