### ISSUE TITLE
func.remote() does not seem to run in parallel

### ISSUE THREAD

**Issue by neuromechanist** [ray-project/ray#8598]
Hi,
I am very new to Python and ray in particular, sorry if my question is basic.
I have some trouble with setting up ray to do parallel computing.

I am calling **func1** inside a module. **func1** then calls **func2** , that has `ray.remote()` decorator, in a loop. So the module looks like this (I summarized the functions of course):
``` python
import numpy as np
import ray

def func1(a_multi_index_DF, ref_time):
    ray.init()
    result_id = {i:[] for i in multi_index_level0}
    for i in multi_index_level0:
        result_id[i] = func2.remote(level1_DF[i], ref_time[i])
    output = {i:[] for i in multi_index_level0}
    for i in multi_index_level0:
        output1[i] = ray.get(result_id[i])
    return output1

@ray.remote
def func2(level1_DF, ref_time):
    # some interpolation of DF based on ref_time
   return output2
```
The code runs successfully and the results seem valid. However, it just takes as much time as it would without using ray parallelization. Looking at the Ray Dashboard, `ray.init()` seems to successfully create 32 workers on my workstation, but the workers remain IDLE all the time during running the code. I tried using the *ray* examples and they worked just fine, so I wonder where I am making the mistake.

I tried having `ray.init()` up top, but it creates a problem when calling the module multiple times, even when the function that needs ray is not being called.

I am using VSCode and run my code via SSH on a remote WSL. The code runs on Python 3.8.2.

**Comment by rkooo567** [comment]
https://rise.cs.berkeley.edu/blog/ray-tips-for-first-time-users/
This could be good resource to understand why it happens. Most likely reason is that your `func2` is fast enough that the overhead incurred by Ray is bigger than the function itself, so there's no speedup.

**Comment by neuromechanist** [comment]
Thanks. The time for the `func2.remote()` loop is about 1 sec and for the `func2.get()` loop is > 230 sec. But, putting some error in `func2`, I could see the error on multiple workers, so the job is already distributed.
I think for a reason that I still don't know, the jobs are running serially.

Thanks again for your time 😊.
