### ISSUE TITLE
How to disable preprocessing for a policy?

### ISSUE THREAD

**Issue by houcharlie** [ray-project/ray#8600]
### What is your question?
I have a few learned policies as well as one hard-coded policy.  I instantiated the hard-coded policy using the Policy interface.  I'd like to know how to disable the observation preprocessing for this policy only; couldn't find anything for this in the docs.

For instance, in the rock-paper-scissors example, the observations are automatically converted to one-hot-encodings. https://github.com/ray-project/ray/blob/master/rllib/examples/policy/rock_paper_scissors_dummies.py 

But I'd like to be able to operate directly on the states 0,1,2 for rock, paper scissors.

**Comment by houcharlie** [comment]
Answer: you can make the state space for the hard-coded policy be a gym.spaces.Box regardless of whether the state space is actually continuous or not; rllib does not perform any preprocessing for Box spaces.  This is a pretty hacky solution though, would be nice to see a cleaner one.

**Comment by sven1977** [comment]
Got you. Yes, setting preprocessing to off shouldn't even do one-hot'ing anymore. I'll take a look.

**Comment by mehes-kth** [comment]
Has this been addressed in a non-hacky way?
Why is automatic preprocessing turned on by default, anyway?

I see a `preprocessor_pref` in `TrainerConfDict`, but based on the rather sparse documentation,
only 2 values are (or, _may be_?) supported: `"deepmind"` or `"rllib"`.  Would setting this to `None`
turn off preprocessing?  I guess I better test...

**Comment by mehes-kth** [comment]
In the end, the `custom_preprocessor` approach worked.  Eventually, deprecation may force the use of a wrapper.

Just in case anyone finds it useful, here's a snippet that transforms boolean vector observations from
the original `gym.spaces.Tuple((gym.spaces.Discrete(2),)*dimension)` to `gym.spaces.Box(0, 1, (dimension,), dtype=int)`:

```python
import gym
import numpy as np
from ray import rllib

class BooleanVectorPreprocessor(rllib.models.preprocessors.Preprocessor):
    def _init_shape(self, observation_space, options=None):
        return (len(observation_space.spaces),)

    def transform(self, observation):
        return np.array(observation)
    
    @property
    def observation_space(self):
        space = gym.spaces.Box(0, 1, self.shape, dtype=int)
        space.original_space = self._obs_space
        return space

rllib.models.ModelCatalog.register_custom_preprocessor('boolean_vector', BooleanVectorPreprocessor)
```

**Comment by ArturNiederfahrenhorst** [comment]
Thanks for adding to this @andras-kth !
