### ISSUE TITLE
[rllib] Is it possible to use multiple CPUs for the learner?

### ISSUE THREAD

**Issue by Arthur-Null** [ray-project/ray#8603]
### What is your question?
I was trying to use a CPU-only server with 64 cores to train an agent with a slighted complicated model. I used PPO and set num_workers to 63 and the experience collection was fast but the learner became the bottleneck as it only utilized one core.
I am wondering whether can I use all the resources for both experience collection and model training.

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ubuntu 18.04
python 3.8
pytorch 1.5
ray 0.8.5

**Comment by chphch** [comment]
I'm also in the same situation. Is there any update on this issue?
I'm using ray 1.11.0, Ubuntu 20.04, python3.6
