### ISSUE TITLE
[rllib] PyTorch and SampleAsync validation

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#8614]
### What is the problem?

PyTorch is supposed to be thread-safe, as long as you don't write a tensor using multiple threads. Please see https://discuss.pytorch.org/t/is-pytorch-supposed-to-be-thread-safe/36540/2 

It might be worth removing the validation of sample_async and use_pytorch for A3C (and maybe others?).

Ray Version 0.9.0dev (but this applies to any ray version actually)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Thanks for filing this issue @roireshef .
Removed the restriction in A3C. Re-testing everything. ...

**Comment by sven1977** [comment]
Looks good. Thanks again @roireshef Please see this PR here: https://github.com/ray-project/ray/pull/8617
Closing the issue.
