### ISSUE TITLE
[tune] How to resume SearchAlgorithm and Scheduler?

### ISSUE THREAD

**Issue by bitosky** [ray-project/ray#8621]
I use ray[tune] 0.8.4, AxSearch.
When I execute `tune.run(...., resume=True)`, only trials are resumed. 
How to resume `SearchAlgorithm` and `Scheduler`?
I noticed that `SuggestionAlgorithm` has some `NotImplementedError` functions:
```
    def save(self, checkpoint_dir):
        raise NotImplementedError

    def restore(self, checkpoint_dir):
        raise NotImplementedError
```
It's that means there are some APIs can handle the problem?

**Comment by richardliaw** [comment]
SearchAlgorithm is now supported. Schedulers will be supported later.
