### ISSUE TITLE
ValueError: ('Observation outside expected value range'

### ISSUE THREAD

**Issue by Tabbi7** [ray-project/ray#8623]
While training some envs in Flow (especially merge and bottleneck) I got the following problem:

  File "/Users/fabianafierro/flow/flow/flow/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 61, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Box(25,), array([ 2.68858156e-01,  7.31141844e-01,  1.00000000e+00,  5.52634464e-02,
        1.04249668e-02,  1.22664420e-01,  1.02354694e-02,  2.84399871e-02,
        3.09940105e-02,  5.72170222e-03,  2.15490226e-02,  1.21143535e-01,
        7.20732391e-02, -6.26750902e-03,  3.55421292e-03,  2.00290047e-06,
        2.11247699e-02,  4.01990513e-03, -5.67311404e-03,  2.71293272e-03,
        1.52663006e-01,  5.45304107e-02,  1.07229621e-02, -1.93326491e-02,
        7.81898266e-03]))

I found the same error in some issues in 2019 and now we are in 2020. How can I solve this?

**Comment by Tabbi7** [comment]
Where do I have to define them? I'm using the default env provided by SUMO with no modifications and it is supposed to work because officially released.

**Comment by Catypad** [comment]
Hi @ericl, @Tabbi7! I'm having the same error, and I have some questions:
1) is wrong if the value is equal to the low bound or to the high bound?
2) the low and the high bounds can be any values that we want? That is, it possible to put -1000, 1000 for every variable although my variables never have that value?

**Comment by ericl** [comment]
Yeah, you can set the bounds to anything on the observation space. It's
only used for validation.

**Comment by Catypad** [comment]
And the only reason for this error to appear is because of some limit is wrong? I already verified twice and is everything ok!

**Comment by xiboli** [comment]
> Where do I have to define them? I'm using the default env provided by SUMO with no modifications and it is supposed to work because officially released.
check the file under flow/flow/envs/merge.py or some others.
