### ISSUE TITLE
Is Tune able to resume grid search (don't train configs previously trained)?

### ISSUE THREAD

**Issue by alexzhou907** [ray-project/ray#8647]
Suppose I stop my machine and restart the run, can Tune resume so that it does not repeat previous trials and continue searching unsearched configs?

**Comment by richardliaw** [comment]
This should work via tune.run(resume=True)?

**Comment by alexzhou907** [comment]
Is there code example of this? When I tried resume=True, it still starts from the beginning, so all the parameters searched before is unnecessarily searched again

**Comment by krfricke** [comment]
There is logging already for that in place, so closing this.
