### ISSUE TITLE
[rllib] How to access true_obs_shape in custom parametric actions model? 

### ISSUE THREAD

**Issue by forhonourlx** [ray-project/ray#8653]
Hi Ray Team,
I notice that in `rllib\examples\parametric_actions_cartpole.py`:
```
self.observation_space = Dict({
            "action_mask": Box(0, 1, shape=(max_avail_actions, )),
            "avail_actions": Box(-10, 10, shape=(max_avail_actions, 2)),
            "cart": self.wrapped.observation_space,
        })
```
in `rllib\examples\models\parametric_actions_model.py`:
`obs_space: Box(34, )`

In my custom model, `true_obs_shape=(4, )` could not be specified in advance, only that custom env is initialized. How to access true_obs_shape before observation_shape is flatten, and where's the implementation of product shape flatten.

Thanks in advance.

**Comment by forhonourlx** [comment]
`obs_space` has `original_space`:
```
obs_space:Box(34,),
obs_space.original_space:Dict(action_mask:Box(10,), avail_actions:Box(10, 2), cart:Box(4,))
```

```
from ray.rllib.models.model import _unpack_obs
```

**Comment by ericl** [comment]
Can you compute it as a function of the custom env parameters and pass it in through as a custom model config?

Otherwise, I think the obs_space.original_space trick would work.
