### ISSUE TITLE
[rllib] Cooperative Multi-Agent env - best way to train based on summed rewards across all agents? 

### ISSUE THREAD

**Issue by rbala19** [ray-project/ray#8669]
### What is your question?

1. I'm considering converting my centralized model which governs multiple moving entities into a multi-agent model where the model learned based on the summed rewards of all agents. While looking through the various examples on the repo, I encountered an example for summing rewards per agent across timesteps using a specified "postprocessing_fn", as well as a centralized critic model that trained over opponent actions in combination with self rewards. However, I did not come across an example of a system that trained over summed rewards across multiple agents - could you point me to an example that does this or show me how I could accomplish this using a centralized value function or centralized loss function? 

2. A little broader of a question - My application informs the movements of agents to accomplish a certain condition within their environment; it aims to be resilient to the case of agents becoming unresponsive, still fulfilling the aforementioned condition using the reduced agent count. Is there a means of training my model on a multi-agent environment without specifying a specific amount of participating agents? Or is the best way to produce several trained models, each corresponding to specific agent counts?

**Comment by ericl** [comment]
> trained over summed rewards across multiple agents

I think the best way is to do this in the environment, by doing the summing explicitly and then giving the same summed reward to each agent.

> specifying a specific amount of participating agents

Absolutely, in RLlib the number of agents can vary over time and agents can act at different timescales. The only requirement is the number of policies is fixed. If an agent isn't present in the obs dict at a certain time step, no action will be computed for it.

Hope this helps!
