### ISSUE TITLE
How to check if rllib using tensorflow gpu?

### ISSUE THREAD

**Issue by Nicholaz99** [ray-project/ray#8680]
Hi, Is it possible to check whether rllib using tensorflow gpu or not? I try to run ray tune with PPO Algorithm and num_gpus = 1, but It only using 1GB /16GB of my GPU. Is this because the rllib using tensorflow CPU instead of GPU?

**Comment by rkooo567** [comment]
@mfitton

**Comment by ericl** [comment]
RLlib will raise an error if GPU support isn't working actually. The reason it's only using 1GB is since your model/batch size is small. For RL, it's very uncommon to use lots of GPU memory.
