### ISSUE TITLE
How can I connect to the dashboard of a cluster on AWS from my pc?

### ISSUE THREAD

**Issue by aefn** [ray-project/ray#8684]
Dear Experts,
I didn't know how to run the auto scaler on AWS. For this reason I asked one of my colleagues to deploy the cluster for me on AWS. He gave me the ip address of the head node and the key for ssh. I don't have access to him until Tuesday and I need your help.
Now I can ssh to the head server but I don't know how can I see the dashboard remotely.
I have seen the command ```ray dashboard``` but I couldn't figure out how to use it.
let say that I have the public ip of the head node and also I can ssh to it.
How should I use this cluster now?
I appreciate your help in advance.

I should mention that I used this: ```<public ip of head node>:8265``` but nothing comes up

**Comment by rkooo567** [comment]
@wuisawesome

**Comment by edoakes** [comment]
@aefn you can run 'ray dashboard' to forward the port to your local machine. While it's running, open localhost:8265 in your browser to view the dashboard.

**Comment by aefn** [comment]
> @aefn you can run 'ray dashboard' to forward the port to your local machine. While it's running, open localhost:8265 in your browser to view the dashboard.

@edoakes could you please give me an example?    
the signature of ``` ray dashboard``` is like this ``` ray dashboard [OPTIONS] CLUSTER_CONFIG_FILE```

as I said I don't have that CLUSTER_CONFIG_FILE, I just have the ip of head node and I can ssh to it.
now I would appreciate if you could guide me what can I do with these to open the dashboard in my pc locally.

**Comment by rkooo567** [comment]
`CLUSTER_CONFIG_FILE` is needed to deploy Ray using an autoscaler. Can you ask your colleague to provide a cluster config file and try using `ray dashboard`?

**Comment by aefn** [comment]
> `CLUSTER_CONFIG_FILE` is needed to deploy Ray using an autoscaler. Can you ask your colleague to provide a cluster config file and try using `ray dashboard`?

I can but I need to wait until Tuesday. There is not any other way to doing that. For example with doing some trick with ssh?

**Comment by rkooo567** [comment]
We implemented this through port forwarding. I am not familiar with how this works, but you can probably take a look at this code. https://github.com/ray-project/ray/blob/d8a081a185271cf9fa352f7ae2c93abdbef6858a/python/ray/autoscaler/updater.py#L244

Can you try `ssh -L "[remote_port]:localhost:[local_port]"`?

**Comment by rkooo567** [comment]
@aefn Did it work? Let me know how it works!

**Comment by aefn** [comment]
> @aefn Did it work? Let me know how it works!

I think it will work, but another big problem is raised for me. The node is unreachable, I don't know what happened but I think now I have to wait until Tuesday :((   
I will give you the feedback when I can test it.   
Btw, thank you again for your help.

**Comment by aefn** [comment]
> We implemented this through port forwarding. You can probably take a look at this code.
> 
> https://github.com/ray-project/ray/blob/d8a081a185271cf9fa352f7ae2c93abdbef6858a/python/ray/autoscaler/updater.py#L244
> 
> It seems like it just runs a ssh command.
> Can you try `ssh -L "[remote_port]:localhost:[local_port]"`?
> 
> Sorry. It has several more options. Let me figure out the command and get back to you.
> 
> I think it must be this => `ssh -L "[remote_port]:localhost:[local_port]" -i [private key] [user]@[ip]`.

It works. Thank you again

**Comment by abhishek12tri** [comment]
> We implemented this through port forwarding. You can probably take a look at this code.
> 
> https://github.com/ray-project/ray/blob/d8a081a185271cf9fa352f7ae2c93abdbef6858a/python/ray/autoscaler/updater.py#L244
> 
> It seems like it just runs a ssh command. Can you try `ssh -L "[remote_port]:localhost:[local_port]"`?
> 
> Sorry. It has several more options. Let me figure out the command and get back to you.
> 
> I think it must be this => `ssh -L "[remote_port]:localhost:[local_port]" -i [private key] [user]@[ip]`.

Please correct it the command:

It is: `ssh -L "[local_port]:localhost:[remote_port]" -i [private key] [user]@[ip]`
[local_port] should come 1st, then [remote_port]

Thanks @rkooo567 , helped me
