### ISSUE TITLE
[rllib] valuation script tryies  to convert pytorch cuda tensor to numpy

### ISSUE THREAD

**Issue by PgLoLo** [ray-project/ray#8688]
When using rllib and turning on evaluation, rllib tries to convert pytorch cuda tensor to numpy and fails with exception "TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first."

Simple reproduced script:
```python
from ray import tune
from ray.rllib.agents.dqn import ApexTrainer


ray.init()


tune.run(
    ApexTrainer,
    stop={"episode_reward_mean": 20000},
    config={
        "env": "SpaceInvaders-v0",
        "num_gpus": 1,
        "num_workers": 16,
        "use_pytorch": True,
        "evaluation_interval": 1,
    },
)
```

Is that really a bug or am I doing something wrong? Any workarounds?

**Comment by PgLoLo** [comment]
Full exception:
```

**Comment by ericl** [comment]
I think we just forgot to call .cpu() first. Unfortunately I'm not sure how to test this is always correct since pytorch has no way to mock GPUs.

**Comment by sven1977** [comment]
Working on this now ...

**Comment by sven1977** [comment]
This PR will have a fix for this problem. For now, just change line ~380 in dqn_tf_policy.py to
```
        new_priorities = (
            np.abs(td_errors.cpu()) + policy.config["prioritized_replay_eps"])
```

**Comment by sven1977** [comment]
https://github.com/ray-project/ray/pull/9497

**Comment by sven1977** [comment]
@PgLoLo

**Comment by sven1977** [comment]
This will be merged later today. ...
Closing this now. Feel free to re-open should the above fix not work on your end.
Thanks for filing this!
