### ISSUE TITLE
Java `Ray.get` and `Ray.wait` should work with covariant generic types

### ISSUE THREAD

**Issue by raulchen** [ray-project/ray#8694]
### What is the problem?

Right now, `Ray.get` only works with `List<RayObject<T>>`. This requires all objects to have the same generic type. We should make it with `List<RayObject<? extends T>>`. 

This bug was reported by https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ray-dev/lfrksM2OcUs/cGKtkYGGAQAJ

**Comment by rkooo567** [comment]
@raulchen `triage` label means we should define its priority level. For Java issues, would you mind tagging java tasks with `java` label and define the priority levels (like P0, P1, P2, and etc.) whenever you have time?

**Comment by raulchen** [comment]
@rkooo567 thanks for reminding. Just added that.

**Comment by jovany-wang** [comment]
How to solve this issue?

```java
List<?> results = Ray.get(objs);
results.get(1).hello();      // This should be red hint because `results.get(1)` is typed as `Object`.
```
