### ISSUE TITLE
[webui] make it easier to bring up the ui

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#870]
At the moment if I want to see the ui, I have to do the following:

- ssh to the remote machine with port forwarding
- go to /tmp/raylogs and do "ls -lrt | grep ui" and find the latest webui.err file
- copy the link with the authentication code
- navigate to it in the browser
- klick on the right .ipynb file

We should try to make this easier.

@alanamarzoev @Wapaul1

**Comment by robertnishihara** [comment]
Fixed by #887.
