### ISSUE TITLE
[rllib] Getting the env object from trainer

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#8700]
### How to get the `env` object from the trainer instance?

Say we have the usual training loop

```
def env_creator():
    # some logic here

register_env("my_env", env_creator)

config = dqn.DEFAULT_CONFIG.copy()
trainer = dqn.DQNTrainer(config=config, env="my_env")

for i in range(100):
    result = trainer.train()
    # how to access the env object here
```

How can we access the env instance inside the loop?

We can access `trainer._env.id`, but how can that help us retrieve the environment object? https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L424
 

*Ray 0.8.5, TensorFlow 2.2.0,  Python 3.8.3, Ubuntu 18.04*

**Comment by ericl** [comment]
Try trainer.workers.local_worker().env

**Comment by nyxynyx** [comment]
Thanks!

**Comment by ruturajsambhusvt** [comment]
Hello, I am facing the same issue. I am using PPO to train a real hardware system and want to use the same environment for evaluation. As of today, the trainer.workers.local_worker().env returns None. Great if the team can help!

**Comment by simonsays1980** [comment]
How do you connect your hardware with RLlib? Did you build a `gym.Env` around it or an RLlib `ExternalEnv`, `Policy Server/Client Setup`? 

I guess the latter could possibly be the easiest form to evaluate your policy on the same environment as 'RolloutWorker`s sample on.

**Comment by ruturajsambhusvt** [comment]
Hello, thanks for getting back!
We have used gym.Env setup as of now. When the PPOAgent is reloaded from the checkpoint, the env is instantiated. And for rollout, another env is instantiated which won't work since the hardware is already talking to the earlier one.
We will look into the ExternalEnv/PolicyServer/Client setup, thank you!

**Comment by Farquhar13** [comment]
I wanted to echo the problem @ruturajsambhusvt mentioned: `trainer.workers.local_worker().env` works for some algorithms, but not for PPO (at least on my version of Ray 2.4.0).

How can I get the environment object from the PPO object I create with `PPOConfig`?
