### ISSUE TITLE
[rllib] Make reverb available as a type of replay actor?

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8706]
### Describe your feature request

https://deepmind.com/research/open-source/Reverb looks like it could be potentially quite efficient as a replay buffer implementation. Currently our replay buffer code is written in Python / numpy.

**Comment by yutaizhou** [comment]
Hey Eric, could you comment on the relationship between DM's acme and ray/rllib? i.e, what one has that the other doesn't, and how the two can interoperate, if possible

**Comment by ericl** [comment]
@yutaizhou, from a brief look, these are the differences that stand out to me:

(1) target users -- acme is explicitly targeted at research reproducibility, and has more extensive support for DM benchmark suites. RLlib is more generally targeted at complex applied RL and multi-agent use cases. However both are fairly general libraries, much more than others I think.

(2) architecture choices -- there are a couple things, the first being "push vs pull" of experiences. RLlib pulls experiences from RolloutWorkers (unless you are using client/server mode). Acme pushes them from individual un-managed env loops. The managed rollout generation in RLlib enables multi-agent and optimizations such as inference vectorization. The second difference is that RLlib builds on a general purpose distributed system, whereas Acme relies on Reverb for distributed coordination.

(3) framework support -- RLlib supports TF(2) / PyTorch, Acme supports TF2 / JAX.

With respect to interop, leveraging reverb is a possible integration point (similar to how DD-PPO leverages torch.distributed in RLlib). In the ideal world, users would be able to write policies that can execute in either RLlib / acme without too much fuss. Whether this is possible requires more investigation.

**Comment by sven1977** [comment]
We will take a look at possibly adding JAX support to RLlib.
