### ISSUE TITLE
[ParallelIterator] for_each_concur leaks memory

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#8713]
### What is the problem?

`for_each_concur` appears to leak memory. After iterating over items, they appear to remain pinned in memory. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
from ray.util.iter import from_items
import numpy as np

ray.init()

def expand(x):
    print("Expanding...")
    return np.array([x for _ in range(2**26)])

def reduce(x):
    return np.sum(x)/x.shape[0]

it = from_items(list(range(1000)))
it = it.for_each(expand, max_concurrency=2)

for x in it.gather_async():
    print(reduce(x))
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@wuisawesome Would you mind taking over this issue? For P1 tasks, each assignees will be responsible for resolving them within a month.
