### ISSUE TITLE
[Core] Removing `with core_worker.profile_event` introduces substantial performance improvement.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#8726]
### Describe your feature request
While I was playing with timeline, I found out removing `with core_worker.profile_event` from `raylet.pyx` introduces substantial performance improvement. Here is the result of `ray microbenchmark` with / without the profiling inside `raylet.pyx`

With profile
<img width="869" alt="Screen Shot 2020-05-31 at 11 20 20 AM" src="https://user-images.githubusercontent.com/18510752/83495780-0164df80-a46d-11ea-82a5-c8299f5924e8.png">

Without profile
<img width="866" alt="Screen Shot 2020-05-31 at 11 20 24 AM" src="https://user-images.githubusercontent.com/18510752/83495787-03c73980-a46d-11ea-8f37-f9b8cb36b79d.png">

Performance improvement
<img width="1072" alt="Screen Shot 2020-05-31 at 11 24 36 AM" src="https://user-images.githubusercontent.com/18510752/83495794-06299380-a46d-11ea-9820-bff7523a28e8.png">

Code modification
<img width="790" alt="Screen Shot 2020-05-31 at 11 28 38 AM" src="https://user-images.githubusercontent.com/18510752/83496165-8d770700-a46d-11ea-8690-8f0a505e73ad.png">

There are 2 possibilities. 
- `with core_worker.profile_event` innately has high overhead.
- `with core_worker.profile_event` has some issues that introduce high overhead in some scenario.

Regardless of what's the cause, as getting profiling events is not a common use case (it seems to be used only for timeline), it'd be great if we can make this optional.

**Comment by rkooo567** [comment]
@ericl

**Comment by virtualluke** [comment]
Is this section of code new? Just asking because of the slowdown of the current version compared with 0.8.0 for example and wondering if this may be the reason?

**Comment by rkooo567** [comment]
@simon-mo Possibly. We should definitely spend some time in the future to figure out the root cause. Also, the easiest solution is to make it feature-flagged as 99% users don't utilize profile info. I have a plan to do this as a part of metrics infrastructure.

@virtualluke This existed from long time ago actually. I think slowdown happens because we introduced a new concept around 0.8.0 that makes Ray way faster, and it keeps slowing down a bit as we added more features such as better memory management or fault tolerance (so it is kind of expected slowdown). We will spend some time in the future versions to improve performance.

**Comment by stephanie-wang** [comment]
Is there a way we can still support the timeline? It is very useful in some scenarios.

**Comment by rkooo567** [comment]
@stephanie-wang Yes! The initial goal is to make it configurable (so that you can turn it on & off).

**Comment by rkooo567** [comment]
Eventually, we'd like to share the new metrics infrastructure. In this case, we need more scoping to support timeline & better profiling. But it is out of scope of this issue.

**Comment by rkooo567** [comment]
Closed because performance improvement doesn't seem to substantial in Linux. This will be improved when we have proper profile infrastructure in the sooner future.
