### ISSUE TITLE
Question about ray head node HA

### ISSUE THREAD

**Issue by acmore** [ray-project/ray#8758]
Hi,

I tried ray yesterday, it's amazing. Thanks for providing us such a good framework.

I deployed it on bare metal machines, and I found that ray head node only has one copy. So if the machine running the ray head node components is down, the cluster will be gone. How could we deploy a cluster with high availability?

**Comment by rkooo567** [comment]
cc @raulchen Please let us know if there's a way to make the head node fault tolerant for now. 

The only component that makes distinction from head node and other nodes is called GCS (Redis in the head node). We are currently under active development in making this component fault tolerant.

**Comment by raulchen** [comment]
Hi @acmore. As @rkooo567 has explained above, GCS fault tolerance is actively under active development. We expect to finish the basic functionalities within this month.

The new implementation of GCS depends on an external (and customizable) storage for fault tolerance. For now, we only support Redis. And we also plan to support SQL databases in the future. 

So, if you have a reliable and Redis-compatible database, GCS will be fault tolerant by the end of this month. If you want to use MySQL as the backend, it will take more time. If you want to use your own database, you can write your own storage plugin for GCS.

**Comment by acmore** [comment]
Thank you @raulchen. Looking forward to the new feature.

**Comment by acmore** [comment]
Hey @raulchen may I know the status of this new feature?

**Comment by raulchen** [comment]
@acmore Code is done, we are currently doing tests and fixing bugs. We plan to fully enable the new GCS service in the next release. However, as I mentioned above, if you want to use MySQL or other database as the backend, there is still some work to be done.

**Comment by raulchen** [comment]
Update: GCS HA is done.  And it is enabled and works well in Ant's internal prod environment.

**Comment by vannitorelli** [comment]
Hello,

I would like to have an update on this. At the current state of the HA feature, if the cluster has one head node and one worker node and the head node goes down, is the worker node automatically elected as the new head node?

Thanks, Vanni

**Comment by rmkohlman** [comment]
Hi, 

I would as well like an update on this feature. Ray is being used in a K8 cluster, with operator,  leveraged for its distributed serverless like architecture. Goal is to laugh detached actors and would be great to have full HA, so wondering when Ray will have HA for the head nodes a K8 cluster.

cheers,
Rob
