### ISSUE TITLE
[autoscaler]  When does autoscaling happen in a cluster?

### ISSUE THREAD

**Issue by aefn** [ray-project/ray#8779]
Dears,
I am running my code in a cluster. 
What I did is that I uploaded my code to the head node and in my code used ```ray.init(address="auto",redis_password="11")```
now when I run my code it works and I can see in the dashboard that my tasks are running.
but when I increase the number of my tasks, my code crashes.
I expect that another node should be run and my extra tasks be added to that new node, but it does not happen. [due to this](https://docs.ray.io/en/latest/autoscaling.html#autoscaling)
What am I missing here? Did I do any thing wrong?

ps: I should mention that running many tasks is my desired behavior. It is the nature of the operation that I want to do.

```
Setting | Value
-- | --
Autoscaling mode | default
Head node type | t3.medium
Worker node type | t3.medium
Min worker nodes | 0
Initial worker nodes | 0
Max worker nodes | 2
Idle timeout | 5 minutes
```

**Comment by rkooo567** [comment]
@aefn Did you happen to figure this out?

**Comment by aefn** [comment]
> @aefn Did you happen to figure this out?

No, as I didn't get any answer after 7 days, I closed this.
I solved my issue by running the ray cluster manually. I start ray manually in each node.
