### ISSUE TITLE
CoreWorkerProcess::instance_->global_worker_ is sometimes NULL on Windows

### ISSUE THREAD

**Issue by mehrdadn** [ray-project/ray#8788]
As of commit e372c0625752e32c80168c03e381271aab412d0f, `CoreWorkerProcess::GetCoreWorker()` can end up executing `return *instance_->global_worker_;` when `instance_->global_worker_ == NULL`. It seems that when this happens, `CreateProfileEvent` ends up calling `ProfileEvent`'s constructor with a `NULL` `CoreWorker`.

This can be reproduced semi-consistently on optimized builds (`bazel test -c opt //:ray_pkg`) when `ray/tests/test_basic.py::test_background_tasks_with_max_calls` is run on Windows (as shown below), but it may not be specific to Windows or to optimized builds.

The stack trace is similar to the following:
```
> python -c "import os, sys; os.environ.update(GLOG_logtostderr='1', RAY_BACKEND_LOG_LEVEL='warning'); import colorama, ray, pytest; colorama.init(); pytest.main(sys.argv[1:])" -s -v -q --full-trace ray/tests/test_basic.py::test_background_tasks_with_max_calls
F0604 13:42:29.469534 10076 22868 core_worker.cc:159]  Check failed: instance_->global_worker_ global_worker_ must not be NULL
    @   00007FFB28EE2CEC  google::LogMessage::~LogMessage
    @   00007FFB28D57B54  ray::RayLog::~RayLog
    @   00007FFB28CA1C46  ray::CoreWorkerProcess::GetCoreWorker
    @   00007FFB28C2CD1D  __pyx_pw_3ray_7_raylet_10CoreWorker_51profile_event
    @   00007FFB38C160B6  PyNumber_AsSsize_t
```

It's unclear to me why this condition might occur or how to properly prevent it.

Possibly related PR (based on `GetCoreWorker` history): #7623

**Comment by rkooo567** [comment]
This is a known issue. I actually have an open issue. It happens because some Python threads are still running when cpp core workers are cleaned up, and it tries to access it through a create_profile function. This happens only when it tear downs, so it is not the high priority task for now.

**Comment by mehrdadn** [comment]
@rkooo567 Oh I see! If you already have an issue for it, let's close it and mark it as a dupe. Which issue is it? I did a quick search and couldn't tell what issue might be already open for it.

**Comment by rkooo567** [comment]
This is the related issue! https://github.com/ray-project/ray/issues/8291
