### ISSUE TITLE
In RLlib, rename PolicyGradient -> ProximalPolicyOptimization and other name changes.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#879]
We should make the naming in RLlib more consistent.

What about the following?

```python
from ray.rllib.ppo import PPOAgent
from ray.rllib.es import ESAgent
from ray.rllib.a3c import A3CAgent
from ray.rllib.dqn import DQNAgent
```

Note the change `Algorithm` -> `Agent`.

cc @ericl @richardliaw @pcmoritz

**Comment by pcmoritz** [comment]
Yeah, definitely!

**Comment by richardliaw** [comment]
Yep - that's good.

**Comment by ericl** [comment]
Sounds good.

**Comment by ericl** [comment]
You could also consider dropping the *Agent suffix on the implementations,
for brevity.
