### ISSUE TITLE
about Ray serialization doesn’t work 

### ISSUE THREAD

**Issue by 57334502** [ray-project/ray#8794]
### What is your question?

*Ray version and other system information (Python version, TensorFlow version, OS):*
2020-06-05 13:18:57,042	WARNING worker.py:792 -- When connecting to an existing cluster, _internal_config must match the cluster's _internal_config.
[ObjectID(7e4833dcf204864b8ba9f5ea040000c801000000), 
2020-06-05 13:18:57,225	WARNING worker.py:1072 -- Failed to unpickle actor class 'ChildClass' for actor ID 8ba9f5ea0400. Traceback:

RuntimeError: The actor with name ChildClass failed to be imported, and so cannot execute this method.
(pid=4630) 2020-06-05 13:12:06,799	ERROR function_manager.py:497 -- Failed to load actor class ChildClass.
(pid=4630) Traceback (most recent call last):
(pid=4630)   File "/root/anaconda3/lib/python3.7/site-packages/ray/function_manager.py", line 495, in _load_actor_class_from_gcs
(pid=4630)     actor_class = pickle.loads(pickled_class)
(pid=4630) ModuleNotFoundError: No module named 'mytest'

```
import ray


class BaseClass:
    pass

@ray.remote
class ChildClass(BaseClass):
    def __init__(self):
        self.name = "hello wolrd"

    @ray.remote
    def compute(self, x):
        print(x)
        return 1

    # @ray.remote
    def compute1(self, x):
        res = []
        for _ in range(10):
            res.append(self.compute.remote(self, 1))
        ray.get(res)
        return x
# --------------------------------------------
ray.init(address="192.168.0.210:6379")

# ray.init()

foo1 = ChildClass.remote()
# foo1 = ChildClass()
result = []
for _ in range(10):
    result.append(foo1.compute1.remote(_))
print(result)
a = sum(ray.get(result))
print(a)
```

**Comment by rkooo567** [comment]
Can you format your code with backtick? It is a bit hard to see the script.

**Comment by pcmoritz** [comment]
The example you posted is working for me. Where is the `mytest` module here?

**Comment by robertnishihara** [comment]
@57334502 I think the issue is that the `my_test` module needs to be installed on all nodes in the cluster.

We need a better error message here...

**Comment by 57334502** [comment]
thank you! I found the answer.


My solution is: I have each node share a network disk (this disk saves my code, and then add the directory to the environment variable $pythonpath),restart ray .&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Robert Nishihara"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 凌晨2:33
收件人:&nbsp;"ray-project/ray"<ray@noreply.github.com&gt;;
抄送:&nbsp;"江南烟雨楼"<57334502@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ray-project/ray] about Ray serialization doesn’t work  (#8794)





 
@57334502 I think the issue is that the my_test module needs to be installed on all nodes in the cluster.
 
We need a better error message here...

**Comment by rkooo567** [comment]
Close as the issue is resolved

**Comment by BBDrive** [comment]
@57334502 I also encountered the same problem. Can you tell me in detail how you share the network disk?
