### ISSUE TITLE
[rllib] How to set a seed when training agent?

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#8796]
### How can we set a seed when training RLlib agents?

This can help with reproducibility...

```
import ray
import ray.rllib.agents.dqn as dqn

ray.init()
trainer = dqn.DQNTrainer(config=dqn.DEFAULT_CONFIG.copy(), env='CartPole-v0')
for i in range(1000):
    result = trainer.train()
```

*Ray 0.8.5, TensorFlow 2.2.0, Python 3.8.3, Ubuntu 18.04*

**Comment by pmacalpine** [comment]
A seed parameter is one of the [common parameters](https://docs.ray.io/en/master/rllib-training.html#common-parameters) you can add to the config.  It sets a seed value for each worker as well as for the environment.  Try the following code:
```python
myConfig=dqn.DEFAULT_CONFIG.copy()
myConfig.update({'seed': 123})
trainer = dqn.DQNTrainer(config=myConfig, env='CartPole-v0')
```

**Comment by maziarg** [comment]
It looks like in RLlib when we build a config file then we cannot modify it as building "Freezes this config object, such that no attributes can be set anymore", would you know any solution to this so we can change the env seed after each training iteration?

**Comment by maziarg** [comment]
This the error I get: "AttributeError: Cannot set attribute (seed) of an already frozen AlgorithmConfig!"
