### ISSUE TITLE
Can we run experiments without a  head node?

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#8807]
If we use doodad, https://github.com/justinjfu/doodad/, 
We can run pre-emptible instances which sync to s3. 

There is no need for a head-node. Which saves a bit of $.

**Comment by richardliaw** [comment]
You can make the headnode a super cheap instance (like a c5.2xlarge). This will make the cost negligible.

**Comment by richardrl** [comment]
It seems like it could add up... I guess it depends on what the purpose of the head node is. It seems like the cheapest on-demand instance comes out to $60/month. If 20 members in a lab at $60/month, that's an additional $1200/month.

**Comment by richardliaw** [comment]
The head node should exist only when the experiment is running. Do you know what is the scale and duration of a typical hyperparameter tuning run in your lab?
