### ISSUE TITLE
`hyperopt_adaptive` example keeps fake `best_hyperparameters`

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#881]
https://github.com/ray-project/ray/blob/4db45c9c547dac0a8c54dd493d62e6f667a06284/examples/hyperopt/hyperopt_adaptive.py#L100-L108

I think L108 should be `previous_info["hyperparameters"]` which is the true best hyperparameters instead of `hyperparameters`.

**Comment by robertnishihara** [comment]
That's a good catch, thanks for finding that! Want to submit a pull request fixing it?

**Comment by suquark** [comment]
PR made.
