### ISSUE TITLE
Background function call?

### ISSUE THREAD

**Issue by JohnEmhoff** [ray-project/ray#8812]
### What is your question?

If I call a remote function from a script and then immediately exit the script, it looks like the job gets killed immediately. I'd like to be able to just submit a job and have it run without needing to keep the interpreter state around (i.e., I want to run the function purely for the side effects). Can I do this in ray?

Alternatively, is it important that the job handle not get GC'd, or is it enough to just have the interpreter that spawned the job stick around?

*Ray version and other system information (Python version, TensorFlow version, OS):* 
ray 0.8.5

**Comment by rkooo567** [comment]
1. For the long running job, the recommended way is to use "detached actor". https://docs.ray.io/en/latest/advanced.html#detached-actors The idea is that you run an actor that is independent from the lifetime of your driver (Python script). In this case, make sure to connect actors to the existing Ray cluster through `ray.init(address='auto')`.

We are probably also going to support something like "long-running jobs" in the future, but this idea is not currently under active development.

2. I am not sure about what you meant by "Job handle". If it means the "actor handle" that is returned after you create an actor, it is GC'ed when it goes out of scope. The way to avoid GC is to use detached actor I mentioned above.

**Comment by JohnEmhoff** [comment]
Thanks, I somehow missed the detached actors in the docs.

For 2), I was asking (in a poorly-worded fashion) if my remote function was getting killed because the future that `func.remote()` was returning was GC'd, or if it was because the interpreter exited.

**Comment by rkooo567** [comment]
ah I see. For (2), the result from f.remote(), is called ObjectID. ObjectIDs are GC'ed in the same way as Python objects are GC'ed (meaning it is GC'ed when you don't / cannot use them anymore).

**Comment by rkooo567** [comment]
Close since it looks like there's no followup. Please feel free to reopen it!
