### ISSUE TITLE
Is this a Plasma Store bug?

### ISSUE THREAD

**Issue by suquark** [ray-project/ray#8813]
### What is the problem?

On linux without huge_page enabled, plasma store would shrink the memory size according to the shared memory limit. However, in the plasma store code, it just forgets to call `SetFootprintLimit`, so this never takes effect (instead it just changes a local variable):

https://github.com/ray-project/ray/blob/b160b83d3ec399a086f3c44271eb85812924914a/src/ray/plasma/store.cc#L1295

I am not sure if some memory overflow was related to this. If there were, then this is a serious bug.

**Comment by ericl** [comment]
I think we also check the shm limit this separately during ray init, so it might not matter that it's not set by plasma.

**Comment by ericl** [comment]
Fixed
