### ISSUE TITLE
Interest in integrating with Flyte as a task type

### ISSUE THREAD

**Issue by kumare3** [ray-project/ray#8814]
### What is your question?
I see that you have a kubernetes operator for Ray. This looks very interesting and might become very useful to some of our users. I wanted to see if you are open to a potential collaboration, where we can add a Ray Plugin to Flyte.

We can discuss more details in a conversation.

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by richardliaw** [comment]
Yeah this would be super cool! Can you reach to rliaw [at] anyscale.com?
