### ISSUE TITLE
[tune][autoscaler] WrappedFunc.Train() issues with autoscaling down

### ISSUE THREAD

**Issue by markgoodhead** [ray-project/ray#8819]
### What is the problem?

Sometimes when the autoscaler is bringing down nodes whilst a Tune experiment has been started, the WrappedFunc.Train() remote call logs the following errors:

`2020-06-06 10:04:24,701	INFO trainable.py:217 -- Getting current IP.
E0606 10:04:44.849920  7793 direct_task_transport.cc:240] Retrying attempt to schedule task at remote node. Error: IOError: 14: failed to connect to all addresses`

It appears that the trainable call is expecting certain nodes to be there which no longer exist (due to them being autoscaled down)

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.5
Ubuntu 18
Python 3.8

### Reproduction (REQUIRED)
Apologies, it's very hard to reproduce given the distributed nature of the issue!

**Comment by markgoodhead** [comment]
@richardliaw Added as requested on Slack 👍

**Comment by richardliaw** [comment]
Got it; does this cause trials to error? What if you turn on checkpointing?

**Comment by markgoodhead** [comment]
No the trials eventually continue, it looks like there's some ~500s timeout that happens then it carries on. I haven't tried checkpointing as I'm using the functional API at the moment - do you expect that to help?

**Comment by ericl** [comment]
I think this is expected behaviour (this isn't an error, just an info message).
