### ISSUE TITLE
Remote function and actor definitions are not garbage collected when drivers exit, so memory increases in cluster setting

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#8822]
Migrating from https://github.com/ray-project/ray-legacy/issues/448. cc @Kuurusch

The issue can be reproduced as follows.

First start Ray with

```
ray start --head
```

Then run the following repeatedly

```python
import ray

ray.init(address='auto')

@ray.remote
def f():
    pass

ray.get(f.remote())

@ray.remote
class Bar:
    pass

b = Bar.remote()

redis_client = ray.worker.global_worker.redis_client
print('NUM EXPORTS:', redis_client.llen('Exports'))  # This number grows continuously.

ray.shutdown()

# As a hack, you might be able to address the issue (or test if this is the
# issue that you are seeing) by uncommenting the following code. This
# only has any hope of working if you are running one driver at a time. If
# multiple drivers are running concurrently, this will fail.
"""
redis_client.ltrim('Exports', 1, 0)
for key in redis_client.keys('ActorClass:*'):
    redis_client.delete(key)
for key in redis_client.keys('FunctionTable:*'):
    redis_client.delete(key)
for key in redis_client.keys('RemoteFunction:*'):
    redis_client.delete(key)
"""
```

The number of "exports" grows continuously. We need to garbage collect this state when a driver exits.

**Comment by robertnishihara** [comment]
@Kuurusch can you check if this is the same issue that you are seeing?

**Comment by Kuurusch** [comment]
@robertnishihara I would say yes, but I don't understand the second ray.remote:

    @ray.remote
    class Bar:
         pass

    b = Bar.remote()

**Comment by robertnishihara** [comment]
@Kuurusch that's just creating an actor. Some state (the actor class definition) is currently "leaked" between drivers, so we need to make sure to clean that up.

**Comment by JerryLeeCS** [comment]
Is this solved?

**Comment by concretevitamin** [comment]
We're hit by this issue.  Our multi-driver cluster will have its GCS OOM-killed in ~4 days of usage.  Upon inspection on the redis table's keys (using `rdb -c memory ./dump.rdb --bytes 128 -f memory.csv`), we see 
* a lot of 1-10MBs of `FunctionTable:xxx` entries, of `quicklist` type 
* as well as a lot of `RemoteFunction:xxx` keys, 2KB each, of `hashtable` type

This seems exactly caused by many drivers entering and exiting the cluster.

Any mitigation we can use rather than letting it crash and restart?

BTW, if it helps, our remote functions are just 1 or 2 -- same code, just invoked with different arguments.

cc @franklsf95 @ericl

**Comment by michaelzhiluo** [comment]
@iycheng Would you have time this or next sprint to tackle this issue? Been getting reports of this bug from more than two users.

**Comment by richardliaw** [comment]
More importantly, the usability issue also raises a warning like: 
```
The actor 'PPO' has been exported 100 times. It's possible that this warning is accidental, but this may indicate that the same remote function is being defined repeatedly from within many tasks and exported to all of the workers. 
```
which is hard to act upon.

**Comment by spolcyn** [comment]
We're having the same problem on Ray 1.8.0 (noticed the issue in #21016) -- it only takes a few hours sometimes for the head to reach max memory and crash, as seen in the Grafana image below (mem usage cliff marks where we experienced client failures).

![Screen Shot 2021-12-16 at 14 45 59](https://user-images.githubusercontent.com/7889440/146438468-3f26590f-02d9-4b0b-a35c-8e8508ad966a.png)
.

**Comment by rkooo567** [comment]
Is this memory usage happening when you run a single driver? Or do you run multiple over time? (I am thinking if we can recommend a workaround until it is fixed. It will be a very high priority for us to fix in the beginning of next year).

**Comment by franklsf95** [comment]
@rkooo567 FWIW I've seen "xxx has been exported 100 times" from single driver runs.

**Comment by ericl** [comment]
We'll take this as a high priority task next year.

> @rkooo567 FWIW I've seen "xxx has been exported 100 times" from single driver runs.

In this scenario, as a workaround you could reduce the leak speed a lot by exporting the function only once (at the start of your program). Each export takes an amount of memory equal to the function size.

**Comment by spolcyn** [comment]
@rkooo567 We typically run a single driver, though occasionally up to 2-3.

**Comment by rkooo567** [comment]
@spolcyn Ray re-imports the function definition whenever you do 

```
@ray.remote
def f():
    # blah
```

This means if you have code such as 

```python3
def run():
    @ray.remote
    def f():
        pass
    ray.get(f.remote())

for _ in range(10):
    run() # This will imports f 10 times.
```

Another potential memory increase could be due to object capture. For example,

```
obj = A()

@ray.remote
def f():
    print(obj) # Now the obj == A() has been captured, and the size of function is (func_size + size of A())
```

**Comment by spolcyn** [comment]
Thanks @rkooo567! That makes sense to me -- I'll take a look at our code and see if we have something like that.
