### ISSUE TITLE
Alternatives to Tensorboard

### ISSUE THREAD

**Issue by vertangelx** [ray-project/ray#8826]
### What is your question?

Are there any alterantives to tensorboard that is supported by Ray or rllib? 

Ideally one that requires minimal changes to code, maybe just pointing it to to ~/ray_results is sufficient, like Tensorboard.

Examples: Neptune, MLflow, Comet, Sacred, Weights & Bases.

**Comment by sumanthratna** [comment]
Neptune: it's definitely possible but I don't think there are any open-source examples

MLflow: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/mlflow_example.py

Comet: not sure, but probably the same case as Neptune

Sacred: this *might* work https://gitlab.com/SumNeuron/extune

Weights & Biases: https://docs.wandb.com/library/integrations/ray-tune

---
If you go with Neptune or Comet, I'd recommend you look at WandB's [custom logger](https://github.com/wandb/client/blob/master/wandb/ray/__init__.py#L12-L43)—it's really just a shim API from Ray to WandB.

**Comment by kamil-kaczmarek** [comment]
hey @vertangelx and @sumanthratna,

Here is Kamil from neptune.ai. We are now working on integration with tune.

Do you have any specific needs regarding it? - it's really great time to share a bit about your needs :)

Integration will work as a tune logger (similar to MLFlow), so you can use it with minimal code changes, like any other Logger. It will naturally work with rllib.

**Comment by mathpluscode** [comment]
Hi, @kamil-kaczmarek, we are using Neptune with RLLIB in our projects currently. Are there any updates on the integration with tune? We are really looking forward to this feature! Especially now wandb has been supported ;) Thanks!

**Comment by kamil-kaczmarek** [comment]
Hi @mathpluscode,

We are working on it in Neptune. I hope that we will be able to release it in the upcoming weeks. Very happy to hear that you use Neptune with RLlib!

**Comment by JonathanRaynerMonumo** [comment]
@kamil-kaczmarek Did anything every come of the neptune-ray possible integration?

**Comment by kamil-kaczmarek** [comment]
@SiddhantSadangi ^^

**Comment by SiddhantSadangi** [comment]
Hello @JonathanRaynerMonumo ,

Siddhant here, from neptune.ai 👋 
An integration with ray-tune is quite high on our backlog. However, there is no ETA currently.

I would invite you to submit your request on our [public roadmap](https://portal.neptune.ai/tabs/15-in-development) to prioritize our development effort.

Please let me know if there's anything else I can help with meanwhile :)

**Comment by JonathanRaynerMonumo** [comment]
Gotcha, thanks!
