### ISSUE TITLE
[rllib] Restore from checkpoint

### ISSUE THREAD

**Issue by nyxynyx** [ray-project/ray#8827]
### What is your question?

[From the docs](https://docs.ray.io/en/latest/rllib-training.html#basic-python-api), a simple example of restoring a trained agent from a checkpoint can be done using

```
ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0
config["num_workers"] = 1
config["eager"] = False
trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")
trainer.restore(checkpoint_path)
```

Question 1: Is it possible to restore it without knowing the type of agent used, such as `ppo.PPOTrainer` in this example. In other words, can `.restore` be called from a [base agent/trainer instance](https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L666-L669)?

Question 2: When restoring the agent, is it necessary instantiate `ppo.PPOTrainer` using the config parameters like `gamma`, `lr` if it was previously trained using non-default values, which means that we are required to have saved this set of config data previously? Or are the config data saved along with the checkpoint file/directory?

**Comment by chiangqiqi** [comment]
you can check `trainer.get_config` out, it prints out the config you currently use.

**Comment by sven1977** [comment]
The config is actually not saved when doing Trainer.save(). We only save the model weights and some limited "other" policy state, like the optimizer's own variables. You should always keep the config around and `restore()` from within an "equally setup" Trainer object.
