### ISSUE TITLE
AWS Secure Key 

### ISSUE THREAD

**Issue by richardrl** [ray-project/ray#8872]
For using Tune and AWS:
It is more secure to pull AWS access keys from the environment variables instead of putting directly in YAML. One way is to pull the keys from the local machine environment variables on "ray submit ...". Not sure if there are other ways.

**Comment by ericl** [comment]
You can put your keys in the boto config, no need to hardcode them in the yaml. Actually any method supported by boto works.

**Comment by richardliaw** [comment]
(closing because stale)
