### ISSUE TITLE
trainer.restore() does not get the consistent action results as the trained trainer 

### ISSUE THREAD

**Issue by feng-pan8014** [ray-project/ray#8873]
I am using the following code to save and restore a trained trainer using checkpoint.

```
ray.shutdown()
ray.init()

dqn_trainer = DQNTrainer(
    env = LOREnv1,
    config = {}
)

for _ in range(100):
    results = dqn_trainer.train()
    print(results["episode_reward_mean"])

dqn_trainer.save("./game1_v2_checkpoint")

dqn_trainer2 = DQNTrainer(
    env = LOREnv1,
    config = {}
)

dqn_trainer2.restore('./game1_v2_checkpoint/checkpoint_100/checkpoint-100')

```

The compute_action() output between dqn_trainer and dqn_trainer2 are not consistent (not even close).

When I run

```
h = {0:0, 1:0, 2:0, 3:0, 4:0}
for _ in range(500):
    a = dqn_trainer.compute_action(
         observation = (np.array([1,2]),np.array([2,2]),np.array([3,1]))
        )
    h[a] += 1
    
print(h)
```

I got {0: 2, 1: 4, 2: 2, 3: 2, 4: 490}

But when I run

```
h = {0:0, 1:0, 2:0, 3:0, 4:0}
for _ in range(500):
    a = dqn_trainer2.compute_action(
         observation = (np.array([1,2]),np.array([2,2]),np.array([3,1]))
        )
    h[a] += 1
    
print(h)
```

I got {0: 76, 1: 81, 2: 102, 3: 82, 4: 159}

Am I missing some steps in save() and restore()?

**Comment by wallneradam** [comment]
I've had similar problem...
I think, the reason is that DQN has random exploration. You can turn it off by config parameter:
```python
dqn_trainer2.get_policy().config['explore'] = False
```

**Comment by feng-pan8014** [comment]
thanks, I will try it. I was expecting random explore to only have limited affect, not causing a completely different distribution.  Is there a way to set the exploration rate in the config?
