### ISSUE TITLE
Renamed function in ProximalLossPolicy breaks PolicyGradient

### ISSUE THREAD

**Issue by dcrankshaw** [ray-project/ray#888]
#849 renamed the function in [this line](https://github.com/ray-project/ray/blob/e1831792f846dd0869b472e8b932f6b677ed0ca2/python/ray/rllib/policy_gradient/loss.py#L85) from `compute_actions` to `compute`.

When the function is [called from policy_gradient.py](https://github.com/ray-project/ray/blob/e1831792f846dd0869b472e8b932f6b677ed0ca2/python/ray/rllib/policy_gradient/policy_gradient.py#L270) the function is now called with the wrong name and it causes an error.

I fixed it by just changing the function name back to `compute_actions` which works for my use case, but I didn't look into whether anything else calls the function with the new name.

Relevant stacktrace:
```
Traceback (most recent call last):
  File "pong_model_container.py", line 33, in <module>
    test()
  File "pong_model_container.py", line 30, in test
    print(p.predict([s]))
  File "pong_model_container.py", line 23, in predict
    actions = [str(self.algorithm.compute_action(s)) for s in states]
  File "/Users/crankshaw/miniconda2/envs/pong-rl/lib/python2.7/site-packages/ray/rllib/policy_gradient/policy_gradient.py", line 258, in compute_action
    return self.model.common_policy.compute_actions(
AttributeError: 'ProximalPolicyLoss' object has no attribute 'compute_actions'
```

cc @robertnishihara: This broke the pong exercise we're putting together.

**Comment by pcmoritz** [comment]
This is fixed on the latest master I think: https://github.com/ray-project/ray/blob/e1831792f846dd0869b472e8b932f6b677ed0ca2/python/ray/rllib/policy_gradient/policy_gradient.py (see the bottom)

Let me know if it doesn't work!
