### ISSUE TITLE
[rllib] Pong PPO and IMPALA Broken

### ISSUE THREAD

**Issue by michaelzhiluo** [ray-project/ray#8906]
# What is the problem?

Pong for PPO and IMPALA are currently broken on the current Ray build. They fail to breach positive reward. Details are provided below:

<img width="1403" alt="Screen Shot 2020-06-11 at 12 51 12 PM" src="https://user-images.githubusercontent.com/20640975/84432881-4cf05980-abe2-11ea-8c54-68e0507baa31.png">

Same runs with different seeds:
<img width="849" alt="Screen Shot 2020-06-10 at 2 27 42 PM" src="https://user-images.githubusercontent.com/20640975/84432926-5d083900-abe2-11ea-94f0-480d825808c3.png">
<img width="880" alt="Screen Shot 2020-06-10 at 2 27 27 PM" src="https://user-images.githubusercontent.com/20640975/84432950-6691a100-abe2-11ea-9725-df33745a6f63.png">

### Reproduction (REQUIRED)
You just need to run in the directory `ray/rllib`:

`python train.py -f tuned_examples/ppo/pong-ppo.yaml`

`python train.py -f tuned_examples/impala/pong-impala-vectorized.yaml`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
I'm not able to reproduce this on tensorflow_p36 with TF1.15. These are plots for 4 trials each on 0.8.4, 0.8.5, and master:

![image](https://user-images.githubusercontent.com/14922/84725605-e3ed4680-af3f-11ea-8adb-923b26e30f5a.png)

@michaelzhiluo @sven1977 how were you able to reproduce the problem?
