### ISSUE TITLE
[rllib] Should remove vf_clip param from PPO

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#8908]
### Describe your feature request

According to https://arxiv.org/pdf/2006.05990.pdf, we should remove VF clipping since it doesn't help. VF clipping has historically been a common cause of user problems in RLlib anyways, so this might be a nice double win.

Note: it seems the paper only evaluates relatively small epoch sizes (at most 4096 steps), whereas many of our examples are tuned for much higher batch sizes (up to 320k steps), which tend to reach higher final rewards. We might want to re-benchmark these to make sure VF clipping still doesn't matter.

cc @eugenevinitsky  @sven1977

**Comment by ericl** [comment]
Note: it seems the paper only evaluates relatively small epoch sizes (at most 4096 steps), whereas many of our examples are tuned for much higher batch sizes (up to 320k steps), which tend to reach higher final rewards. We might want to re-benchmark these to make sure VF clipping still doesn't matter.

**Comment by avnishn** [comment]
I'm going to go ahead and close this for now, as it seems that we're going to stick with vf clipping see #22171
