### ISSUE TITLE
[Tune] ProgressReporter default_columns is shared across instances

### ISSUE THREAD

**Issue by TomVeniat** [ray-project/ray#8913]
### What is the problem?
When adding a new column to a ProgressReporter that used the `DEFAULT_COLUMNS` during its creation, this column will be added to the actual default dictionary. This can cause several unexpected behaviors.
For instance, when creating several experiments with custom columns for each of them, using the same column multiple times will break (see reproduction).

### Reproduction (REQUIRED)
```python
from ray.tune import CLIReporter

reporter = CLIReporter()
reporter.add_metric_column('custom column')
reporter = CLIReporter()
reporter.add_metric_column('custom column')
```
Thows a `ValueError: Column custom column already exists.`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### Solution
A solution is to copy this default parameter each time it is used [here](https://github.com/ray-project/ray/blob/4b31b383f379dad5514f4d93a9776db6b3caa38c/python/ray/tune/progress_reporter.py#L90).
I can send a PR is this is okay for you.

**Comment by richardliaw** [comment]
Sorry; I totally missed your comment at the bottom. A PR would be great!
