### ISSUE TITLE
[rllib] rllib train ... --checkpoint-at-end flag is ignored

### ISSUE THREAD

**Issue by deanwampler** [ray-project/ray#8919]
### What is the problem?

Ray 0.8.5
Python 3.7
MacOS Catalina
PyTorch 1.4.0

No checkpoint is produced when the `--checkpoint-at-end` flag is used. Adding `--checkpoint-freq 10` does cause checkpoints to be saved.

### Reproduction (REQUIRED)

```shell
rllib train --run PPO --env CartPole-v0 --stop='{"training_iteration": 25}' --ray-address auto --checkpoint-at-end
```

No checkpoint directory exists under `~/ray_results/default/PPO...`

Add the `--checkpoint-freq 10` flag:

```shell
rllib train --run PPO --env CartPole-v0 --stop='{"training_iteration": 25}' --ray-address auto --checkpoint-at-end --checkpoint-freq 10
```

Now there are `checkpoint_10` and `checkpoint_20` directories, but not a `checkpoint_25` at the end. 

Could the choice of stop criteria, `training_iteration`, have something to do with it?

> **Note:** Being persnickety, it bugs me that the final directory path for the checkpoints is `.../checkpoint_20/checkpoint-20` (underscore vs. dash). How about one or the other?

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Thanks @deanwampler for filing this!
PR https://github.com/ray-project/ray/pull/8933
fixes this issue. Closing it now.
