### ISSUE TITLE
fatal error: 'plasma/common.h' file not found when Building Ray from source

### ISSUE THREAD

**Issue by liamlee** [ray-project/ray#892]
<img width="868" alt="plasma" src="https://user-images.githubusercontent.com/781297/29859937-ec79452e-8d96-11e7-8ec4-177f4882bc20.png">

**Comment by robertnishihara** [comment]
My guess is that CMake cached certain information and maybe you did a `git pull` at some point which changed the code structure enough that some cached values become out of date.

Can you try removing the whole directory, recloning it, and rebuilding it? If that persists, could you share the entire output of the installation?

**Comment by liamlee** [comment]
Ok, reclone and rebuild work it out.
