### ISSUE TITLE
[ray] Raylet logs is blasting output 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#8923]
### What is your question?
Can we improve the logging mechanisms and output for `ray.init`? 

With such verbose output, it is hard to seamlessly integrate Ray into a library that actually cares about output.

2020-06-12 19:19:13,519 INFO resource_spec.py:212 -- Starting Ray with 4.98 GiB memory available for workers and up to 2.51 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-12 19:19:13,743 WARNING services.py:923 -- Redis failed to start, retrying now.
2020-06-12 19:19:13,948 INFO services.py:1165 -- View the Ray dashboard at localhost:8265
(pid=raylet) I0612 19:19:13.981485 24354 409001408 store_runner.cc:44] Allowing the Plasma store to use up to 2.69557GB of memory.
(pid=raylet) I0612 19:19:13.981541 24354 409001408 store_runner.cc:58] Starting object store with directory /tmp and huge page support disabled
(pid=raylet) I0612 19:19:13.982936 24354 409001408 grpc_server.cc:74] ObjectManager server started, listening on port 55476.
(pid=raylet) I0612 19:19:13.996219 24354 409001408 node_manager.cc:166] Initializing NodeManager with ID 8685342a66581942e80ece7f2d0c00b3061f39ee
(pid=raylet) I0612 19:19:14.003435 24354 409001408 grpc_server.cc:74] NodeManager server started, listening on port 64310.
(pid=raylet) I0612 19:19:14.037457 24354 409001408 service_based_accessor.cc:739] Received notification for node id = 8685342a66581942e80ece7f2d0c00b3061f39ee, IsAlive = 1
(pid=raylet) I0612 19:19:14.037865 24354 409001408 service_based_accessor.cc:739] Received notification for node id = 8685342a66581942e80ece7f2d0c00b3061f39ee, IsAlive = 1

^ I don't need to know about any of this!

**Comment by ericl** [comment]
This isn't the first time this has regressed. We should add a unit test checking the output.

**Comment by rkooo567** [comment]
Cannot reproduce it from 0.8.6 so far. I will remove release blocker. But we should definitely fix this before 0.8.7, so I will keep P0

**Comment by suquark** [comment]
@ericl I have created a PR to fix the issue. but I am not sure about how to create unit tests.

**Comment by ericl** [comment]
Could we use subprocess to run and check the output of a noop ray script? I
think we have a couple tests that do that already for testing multiple
drivers, for instance.
