### ISSUE TITLE
Creating Queue for Transfering Data from One Group of Actors to Another

### ISSUE THREAD

**Issue by fahadh4ilyas** [ray-project/ray#8946]
## System information

* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
* **Ray installed from (source or binary)**: source
* **Ray version**: 0.9.0.dev0
* **Python version**: 3.6.6

## Describe the problem

I have 2 classes, they are processing data in order like this:
```python
instance1 = FirstClass()
instance2 = SecondClass()

first_result = FirstClass.process(data)
last_result = SecondClass.process(first_result)
```
The first class is using core more intensively than the second class. I have two nodes in ray cluster which the first node is for creating actors of the first class and the second node is for creating actors of the second class. Because the first class is using core more intensively, the actors of the first class will be fewer than the actors of the second class.

Is there any way to create queue between those actors so that actors from the first node could transfer their result to actors from the second node? My idea is to create a dummy actor like this

```python
@ray.remote(num_cpus=0)
class Dummy:
    def __init__(self):
        self.data = []

    def add_data(self, data):
        self.data.append(data)

    def get_data(self):
        try:
            return self.data.pop(0)
        except:
            return None
```

This dummy act like queue while the actors of the first class will transfer data using `dummy_actor.add_data.remote(first_result)` and the actors of the second class will get data using `dummy_actor.get_data.remote()`. But somehow I think this looks hideous. Is there any better way?

**Comment by rkooo567** [comment]
The clearest way is to use detached actor. https://docs.ray.io/en/latest/advanced.html#detached-actors

```python3
@ray.remote(num_cpus=0)
class Queue:
    def __init__(self):
        self.data = []

Queue.options(name="data-queue").remote()
```
And you can get this actor handle from other scripts using `ray.get_actor("data-queue")`
