### ISSUE TITLE
Kubernetes: Resource Detection is not correct

### ISSUE THREAD

**Issue by arunmk** [ray-project/ray#8958]
### What is the problem?

Ray 0.8.0, 0.8.5

### Reproduction (REQUIRED)
This is simple, use a kubernetes install wherein the pod CPU does not match the host CPU. In the pod, run a python shell (`kubectl exec -it <pod name> -- python`) and try:
`
ray.available_resources()
ray.cluster_resources()
`
These will report the host resources and not the pod resources. The incorrect details are for CPU, memory and GPU.

**Comment by rkooo567** [comment]
@ijrsvt Probably related to the Docker issue that doesn't show the correct resources information?

**Comment by richardliaw** [comment]
cc @wuisawesome

**Comment by ijrsvt** [comment]
I"m looking into this

**Comment by wuisawesome** [comment]
Btw this is somewhat strange, because we attempt to explicitly check for this. Maybe we just aren't doing it correctly? https://github.com/ray-project/ray/blob/2589309cf0beed938e54665e35a73bba87841f9b/python/ray/utils.py#L406

**Comment by ijrsvt** [comment]
@wuisawesome  That appears to work locally--in the sense that when Ray starts the correct amount is printed. The data for `cluster_resources()` and `available_resources()` comes from GCS.

**Comment by ijrsvt** [comment]
Actually, for what it's worth if I run `ray.cluster_resources()` on my computer (*no container*), I actually get incorrect information :/

**Comment by rkooo567** [comment]
Could be related: https://github.com/ray-project/ray/issues/8983#issuecomment-646316576
https://github.com/ray-project/ray/issues/8983#issuecomment-646450764

Also, (I guess we already calculate this programmatically, but just in case) 
```
Worker heap: memory used by your application (e.g., in Python code or TensorFlow), best measured as the resident set size (RSS) of your application minus its shared memory usage (SHR) in commands such as top. The reason you need to subtract SHR is that object store shared memory is reported by the OS as shared with each worker. Not subtracting SHR will result in double counting memory usage.
```

**Comment by arunmk** [comment]
@ijrsvt to be clear, the issue is that the containers report resources on the host. I give 2 containers 2 cores each but the API reports 24 instead of 4. My host has 24 cores.

**Comment by virtualluke** [comment]
In kubernetes you might be putting resource requests and limits for 2 CPUs, but this is soft and not seen for real inside the pod, it just sees what the host has. If you want ray to respect the 2 CPU you would need ray to read what you set in the pod definition under resources or set that as an env variable that ray uses.

**Comment by arunmk** [comment]
@virtualluke that is also done. For example, my worker spec is as follows:
`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ray-worker
spec:
  # Change this to scale the number of worker nodes started in the Ray cluster.
  replicas: 2
  selector:
    matchLabels:
      component: ray-worker
      type: ray
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: ray-worker
        type: ray
    spec:
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: gcp-credentials
          secret:
            secretName: user-gcp-sa
      containers:
        - name: ray-worker
          image: continual/engine
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args:
            - "ray start --redis-password='password' --num-cpus=$MY_CPU_REQUEST
              --num-gpus=$MY_GPU_REQUEST --memory=8589934592
              --object-store-memory=4294967296 --node-ip-address=$MY_POD_IP
              --address=${RAY_HEAD_SERVICE_HOST}:${RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY}
              --object-manager-port=12345 --node-manager-port=12346 --block"
          ports:
            - containerPort: 12345 # Ray internal communication.
            - containerPort: 12346 # Ray internal communication.
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: gcp-credentials
              mountPath: /secret/gcp-credentials
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            # This is used in the ray start command so that Ray can spawn the
            # correct number of processes. Omitting this may lead to degraded
            # performance.
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
            - name: MY_GPU_REQUEST
              value: "0"
          resources:
            requests:
              cpu: 2000m
              memory: 10Gi
---

`

**Comment by virtualluke** [comment]
in your example I believe what you would want is $MY_CPU_REQUEST matching what you have in your yaml under resources (where you have 2000m), except my guess is the behavior you want is for it to match not under resources->requests but resources->limits (which you don't have).

**Comment by arunmk** [comment]
@virtualluke yes, exactly. In ray-head, I want the sum of all of the limits values of the workers joined into the cluster for cluster_resources().

**Comment by ijrsvt** [comment]
@arunmk can you show the full output from `cluster_resources()`?

**Comment by arunmk** [comment]
@ijrsvt this is what I get from prints from ray-head pod:

`^[[2m^[[36m(pid=225)^[[0m 2020-06-16 01:52:25 INFO     Available ray resources: [{'CPU': 23.0,
^[[2m^[[36m(pid=225)^[[0m  'memory': 883.0,
^[[2m^[[36m(pid=225)^[[0m  'node:172.17.0.12': 1.0,
^[[2m^[[36m(pid=225)^[[0m  'object_store_memory': 304.0}]
^[[2m^[[36m(pid=225)^[[0m 2020-06-16 01:52:25 INFO     Ray resources currently: [{'CPU': 24.0,
^[[2m^[[36m(pid=225)^[[0m  'memory': 883.0,
^[[2m^[[36m(pid=225)^[[0m  'node:172.17.0.12': 1.0,
^[[2m^[[36m(pid=225)^[[0m  'object_store_memory': 304.0}]`

**Comment by ijrsvt** [comment]
Okay--thanks and what is your head spec?

**Comment by arunmk** [comment]
@ijrsvt attached.

[ray-head-deployment.yaml.txt](https://github.com/ray-project/ray/files/4820620/ray-head-deployment.yaml.txt)
[ray-worker-deployment.yaml.txt](https://github.com/ray-project/ray/files/4820622/ray-worker-deployment.yaml.txt)
[start_ray_driver.sh.txt](https://github.com/ray-project/ray/files/4820623/start_ray_driver.sh.txt)

**Comment by edoakes** [comment]
@arunmk when you're calling `ray.cluster_resources()` are you calling `ray.init(address="auto")` to connect to the running cluster? One reason you might be seeing all CPUs used is if you're just calling `ray.init()`.

**Comment by arunmk** [comment]
@edoakes that did the trick! Thanks!

My fundamental issue was with getting the right number of GPUs. Will this API call provide accurate GPU numbers as well?

**Comment by arunmk** [comment]
@edoakes thanks, I can now see the GPUs as well, but the count is incorrect. I have a GCP node with 2 V100 GPUs connected to it. I have a small ray cluster which has one ray head and two workers. Each worker uses one GPU:
`  
- args:
    - ray start --redis-password='password' --num-cpus=$MY_CPU_REQUEST --num-gpus=$MY_GPU_REQUEST
      --memory=8589934592 --object-store-memory=4294967296 --node-ip-address=$MY_POD_IP
      --address=${RAY_HEAD_SERVICE_HOST}:${RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY} --object-manager-port=12345
      --node-manager-port=12346 --block
    command:
    - /bin/bash
    - -c
    - --
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: MY_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.cpu
    - name: MY_GPU_REQUEST
      value: "1"
    image: continual/engine
    imagePullPolicy: IfNotPresent
    name: ray-worker
    ports:
    - containerPort: 12345
      protocol: TCP
    - containerPort: 12346
      protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        cpu: "2"
        memory: 10Gi
        nvidia.com/gpu: "1"
`

However the available and cluster resources shows 4 GPUs:
`
(pid=23, ip=172.17.0.8) 2020-06-24 00:54:58 INFO     Available ray resources: [{'CPU': 3.0,
(pid=23, ip=172.17.0.8)  'GPU': 4.0,
(pid=23, ip=172.17.0.8)  'memory': 1194.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.4': 1.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.6': 1.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.8': 1.0,
(pid=23, ip=172.17.0.8)  'object_store_memory': 411.0}]
(pid=23, ip=172.17.0.8) 2020-06-24 00:54:58 INFO     Ray resources currently: [{'CPU': 4.0,
(pid=23, ip=172.17.0.8)  'GPU': 4.0,
(pid=23, ip=172.17.0.8)  'memory': 1194.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.4': 1.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.6': 1.0,
(pid=23, ip=172.17.0.8)  'node:172.17.0.8': 1.0,
(pid=23, ip=172.17.0.8)  'object_store_memory': 411.0}]
`

Do you know what could be going on?

**Comment by arunmk** [comment]
@edoakes I tried without any GPUs mentioned in the kubernetes yamls. On a gpu enabled machine, I still see the GPUs of the host. (2GPUs):
`(pid=24, ip=172.17.0.10) 2020-06-24 01:34:57 INFO     Available ray resouces: [{'CPU': 3.0,
(pid=24, ip=172.17.0.10)  'GPU': 2.0,
(pid=24, ip=172.17.0.10)  'memory': 1194.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.10': 1.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.5': 1.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.9': 1.0,
(pid=24, ip=172.17.0.10)  'object_store_memory': 411.0}]
(pid=24, ip=172.17.0.10) 2020-06-24 01:34:57 INFO     Ray resources currently: [{'CPU': 4.0,
(pid=24, ip=172.17.0.10)  'GPU': 2.0,
(pid=24, ip=172.17.0.10)  'memory': 1194.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.10': 1.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.5': 1.0,
(pid=24, ip=172.17.0.10)  'node:172.17.0.9': 1.0,
(pid=24, ip=172.17.0.10)  'object_store_memory': 411.0}]`

**Comment by YuejiYang** [comment]
May I ask a related question.
What is the unit for 'object_store_memory'? It seems not equal to the bytes in 'ray start' above. 'ray start --redis-password='password' --num-cpus=$MY_CPU_REQUEST --num-gpus=$MY_GPU_REQUEST --memory=8589934592 **_--object-store-memory=4294967296_** ....'

**Comment by arunmk** [comment]
@YuejiYang it is in bytes I think. Is there some documentation on what it should be set to and how one goes about estimating these values?

**Comment by anonymousssssss** [comment]
@arunmk After several testing, I found the ray.cluster_resource() returns object_store_memory in 100MB per unit and memory in 50MB per unit.  It is in bytes for "ray start --object-store-memory=.......".

I did not find any related documentation:(. So it is confusing. Could you please refer me to any documentation if you saw any. Thank you!

**Comment by ijrsvt** [comment]
`ray.cluster_resources()` and `ray.available_resources()` will be in bytes/gigabytes soon.

**Comment by YuejiYang** [comment]
@arunmk After several testing, I found the ray.cluster_resource() returns object_store_memory in 100MB per unit and memory in 50MB per unit.  It is in bytes for "ray start --object-store-memory=.......".

I did not find any related documentation:(. So it is confusing. Could you please refer me to any documentation if you saw any. Thank you!

**Comment by Servon-Lee** [comment]
@arunmk Hi there. I encountered the same problem that the number of GPUs is showed incorrectly. Do you fix it?
Concretely, when I specify `ray start --num-gpus=x`, `ray.cluster_resources()` is always showing the whole GPUs in my host. However, if I specify 'ray.init(num_gpus=x)', then `ray.cluster_resources()` shows correct resources.
Is there any way to make `ray start --num-gpus=x` start correct resources?

**Comment by nlnjnj** [comment]
> @arunmk Hi there. I encountered the same problem that the number of GPUs is showed incorrectly. Do you fix it?
> Concretely, when I specify `ray start --num-gpus=x`, `ray.cluster_resources()` is always showing the whole GPUs in my host. However, if I specify `ray.init(num_gpus=x)`, then `ray.cluster_resources()` shows correct resources.
> Is there any way to make `ray start --num-gpus=x` start correct resources?

I got the same issue seems only the --num-cpus works fine the memory and num-gpus do not work.

**Comment by rkooo567** [comment]
@barakmich I will assign it to you now since you asked last time!
