### ISSUE TITLE
[autoscaler] AWS Autoscaler CloudWatch Integration

### ISSUE THREAD

**Issue by pdames** [ray-project/ray#8967]
This issue tracks a set of improvements to enable automatic creation of CloudWatch logs, metrics, and dashboards when provisioning AWS Autoscaling clusters. Successful implementation of these improvements will allow AWS Autoscaler users to:

* Write, monitor, and query their cluster's CloudWatch log streams.
* Emit and monitor durable CloudWatch metrics for their clusters.
* Configure CloudWatch metric and composite alarms for their clusters.
* Get rapid insights into their cluster state via CloudWatch dashboards.

A project to achieve these goals is currently in progress at Amazon, and we would like to propose the following priority-ordered improvements for contribution back to open source:

1. **Unified Agent Integration**: To support basic log and metric collection, we will allow users to request on-demand installation of the CloudWatch Unified Agent on each cluster node. Users will control CloudWatch Agent installation through explicit specification of an AWS Autoscaler provider config key requesting that the agent be initialized with either a default or custom CloudWatch Agent configuration file.

2. **Custom Metric Collection**: To support the collection of both Ray core system metrics and user-defined application metrics, we will investigate exposing them to the CloudWatch Agent via the StatsD protocol. Assuming that a centralized, pluggable Ray Dashboard API is developed to support the export of such metrics, we would also like to investigate a prospective integration with it.

3. **Cluster Dashboard Creation**: To ensure that users can quickly derive critical insights into their current or historic Ray cluster state, we will allow users to create customizable CloudWatch dashboards containing a targeted subset of available metrics and alarms.

**Comment by pdames** [comment]
Associated design doc: 
https://docs.google.com/document/d/1uz9b6TvfdzOY9mISkeB_28anHtvBs3srZj1CpnR4YjQ/edit?usp=sharing

**Comment by rkooo567** [comment]
cc @wuisawesome

**Comment by pdames** [comment]
FYI, CloudWatch integration with Ray is included in the AMIs released by Amazon at https://github.com/amzn/amazon-ray. 

Launching your cluster from one of these AMIs is currently recommended over installing the CloudWatch agent either out-of-band or as part of `ray up` since this process may take ~15-60 minutes on the latest Ubuntu Deep Learning AMIs (due to waiting for dpkg locks to be released by the OS package updater that runs whenever these instances are launched).

We are currently working on a PR to emit all Ray Prometheus metrics to CloudWatch at https://github.com/amzn/amazon-ray/pull/30, and expect to follow this work with additional changes that allow you to update your Ray cluster's CloudWatch metrics, logs, dashboards, and alarm configuration as part of `ray up`.

**Comment by wuisawesome** [comment]
I think we want to leave this open until #22070 ?
