### ISSUE TITLE
Ray gh-pages are not rendering properly.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#897]
After merging #895, I followed the instructions in https://github.com/ray-project/ray/blob/master/site/README.md to push the `site` folder to the `gh-pages` branch. However, doing that made the website (at https://ray-project.github.io/ray/) render in a funny way (and the links don't work).

I tried reverting to before #895 and pushing again but that didn't fix the problem.

Strangely, when I pushed the same stuff to my fork of Ray, it seemed to render properly (though the links still didn't work).

Not totally sure what's going on here. Some tips for troubleshooting are here https://help.github.com/articles/troubleshooting-github-pages-builds/.

**Comment by pcmoritz** [comment]
I have the same problem on my fork i.e. the site doesn't work.

**Comment by jzf2101** [comment]
I'm still seeing issues with the website :(

See : https://ray-project.github.io/ray/2017/05/20/announcing-ray.html

**Comment by pcmoritz** [comment]
Thanks for reporting! The jekyll server seems to have gotten into a bad state somehow, it is not clear what exactly happened. I got it working by doing some changes and then re-pushing the old version. I also moved the site to https://ray-project.github.io/ now

See https://github.com/ray-project/ray/pull/963

**Comment by robertnishihara** [comment]
Fixed by #963.
