### ISSUE TITLE
Bazel options written to .bashrc instead of .bazelrc in deploy Dockerfile

### ISSUE THREAD

**Issue by jkhlr** [ray-project/ray#8974]
https://github.com/ray-project/ray/blob/fa0a677aacf90d73514a813cb95c26b122fde5cd/docker/deploy/Dockerfile#L9

This leads to the following error when running the `deploy` docker image:
```
$ docker run -it ray-project/deploy bash
bash: build: command not found
bash: build: command not found
```

**Comment by rkooo567** [comment]
cc  @ijrsvt

**Comment by ijrsvt** [comment]
Thanks for catching this @jkhlr!
