### ISSUE TITLE
[BUILD]trivial bug in check_import_order.py 

### ISSUE THREAD

**Issue by WangTaoTheTonic** [ray-project/ray#8982]
### What is the problem?

in check_import_order.py we check if codes import ray before importing psutil/setproctitle using the line number we found in single file.

but the line number always point to the last line the import at. for example we have  real  `import ray` in file header and another `import ray` in functions like run_string_as_driver. we need add extra but unnecessary `import setproctitle` if we have a `import setproctitle` in file header. like this:

```
import ray
import setproctitle

....

def funciton_udf(file):
    driver = run_string_as_driver("""
import ray
import setproctitle (this one is not necessary but we must add it, otherwise the check import order will throw a check failed message)
.....
ray.init()
.....
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

just use run_string_as_driver in any file that already has psutil/setproctitle imported.

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
great issue! would you be ok with pushing a fix?

**Comment by WangTaoTheTonic** [comment]
> great issue! would you be ok with pushing a fix?

Pull request filed. Please help to check if the fix is right :)
