### ISSUE TITLE
[Ray] Correctly detect CPUs and RAMs in Docker

### ISSUE THREAD

**Issue by GoingMyWay** [ray-project/ray#8983]
### Describe your feature request

When running tasks in Docker, Ray detects CPUs and RAM of the host machine, regardless of CPUs and RAM assigned to docker tasks, could you please use `nproc` to detect CPUs and RAM correctly? The detecting method can incur bugs like this

```
The actor or task with ID ffffffffffffffff45b95b1c0100 is pending and cannot currently be scheduled. It requires {CPU: 1.000000} for execution and {CPU: 1.000000} for placement, but this node only has remaining {node:9.146.140.151: 1.000000}, {CPU: 180.000000}, {memory: 198.681641 GiB}, {object_store_memory: 61.474609 GiB}. In total there are 0 pending tasks and 4 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale
```

References: 
* https://github.com/ray-project/ray/issues/8326
* https://stackoverflow.com/questions/49151296/how-many-cpus-does-my-docker-container-have/49153003#49153003

**Comment by rkooo567** [comment]
cc @ijrsvt Seems like this should be a high priority?

**Comment by ijrsvt** [comment]
@GoingMyWay do you have a simple reproduction script? Also, is this from you using Tune or Core Ray?

**Comment by GoingMyWay** [comment]
> @GoingMyWay do you have a simple reproduction script? Also, is this from you using Tune or Core Ray?

I was not using Tune, I used RLlib and found this issue happened frequently.

**Comment by GoingMyWay** [comment]
> @GoingMyWay do you have a simple reproduction script? Also, is this from you using Tune or Core Ray?

You can run RLlib examples in Docker where there are many Docker tasks running on the host machine. The main issue is Ray cannot correctly detect how many CPUs and RAM assigned to the Docker container it is running in.

**Comment by mrfox321** [comment]
It should not be possible to see outside of the isolation that Docker provides.  It seems unlikely that ray can somehow access state in the machine that hosts the container.

**Comment by rkooo567** [comment]
This could be related. https://github.com/ray-project/ray/issues/8326#issuecomment-630614991 

I found in the past using `multiprocessing.cpu_count()` (which we are using) can have problems reading resource information from cgroup.

**Comment by GoingMyWay** [comment]
> This could be related. [#8326 (comment)](https://github.com/ray-project/ray/issues/8326#issuecomment-630614991)
> 
> I found in the past using `multiprocessing.cpu_count()` (which we are using) can have problems reading resource information from cgroup.

Good, will you fix it in the newest Ray?

**Comment by rkooo567** [comment]
@GoingMyWay  We need more investigation to make sure this is the actual cause @ijrsvt is spending his time to fix this issue, so it would be fixed sooner. The next release won't include this change (The branch cut already happened, and the next release will happen before the fix is applied).

**Comment by GoingMyWay** [comment]
> @GoingMyWay We need more investigation to make sure this is the actual cause @ijrsvt is spending his time to fix this issue, so it would be fixed sooner. The next release won't include this change (The branch cut already happened, and the next release will happen before the fix is applied).

Good, thanks, hope this issue will be fixed future releases.
