### ISSUE TITLE
ES CartPole training seems to hang

### ISSUE THREAD

**Issue by compressed** [ray-project/ray#901]
Hi,
First, thanks for the project! It looks quite exciting. I've been using it by building from source. However, when updating to the latest master (7a36430) and trying to run the cartpole example, it hangs at 980 steps for some reason.

```
python train.py --env CartPole-v0 --alg ES

....

Collected 920 episodes 20686 timesteps so far this iter
Collected 940 episodes 21084 timesteps so far this iter
Collected 960 episodes 21484 timesteps so far this iter
Collected 980 episodes 21895 timesteps so far this iter
```

Attempting to kill the process (ctrl-C), also doesn't close cleanly, some process is still stuck. Not sure if there is more information I can give, but let me know.

Thanks!

**Comment by robertnishihara** [comment]
Great, thanks for trying stuff out! Running the command you posted seems to work for me (on Mac with Anaconda Python 3.6). What OS and Python version are you using?

One thing to try is adding some print statements into the file `ray/python/ray/rllib/es/es.py` and se where it is hanging. I'll let you know if I have more ideas.

**Comment by compressed** [comment]
Thanks for the quick response. I'm using pyenv with python 3.6.2 under ubuntu 16.04.02.

Good idea to add print statements to `es.py`! I was able to track it down at least where it is hanging:

Once the result loop is complete (I believe this would be after `1000` iterations, from here: https://github.com/ray-project/ray/blob/7a36430399dfcdfbf50ccdedea363ebbddb21af1/python/ray/rllib/es/es.py#L37) it reaches this point in the code: https://github.com/ray-project/ray/blob/7a36430399dfcdfbf50ccdedea363ebbddb21af1/python/ray/rllib/es/es.py#L279

which calls https://github.com/ray-project/ray/blob/7a36430399dfcdfbf50ccdedea363ebbddb21af1/python/ray/rllib/es/utils.py#L57 which is where it just seems to stop. It never returns from that `np.dot` call for the first iteration of the loop there...

**Comment by compressed** [comment]
So I think this has something to do with a messed up numpy install. Even a simple dot product seems to fail (just in the regular python interpreter). Strange though, because it was working on older version of ray. I'll do some more digging tomorrow, but I don't think this a ray issue.

**Comment by robertnishihara** [comment]
Wow that's interesting, thanks for looking into it! If it turns out to be a Ray issue please reopen the issue and let us know what you find out.

**Comment by compressed** [comment]
So I got this working today. Definitely was an issue with my setup. Somehow numpy + openblas didn't play well together. I ditched pyenv and went with anaconda which installed the mkl-optimized version of numpy. No more hangs!

Thanks for your help.

**Comment by robertnishihara** [comment]
Excellent, glad to hear it!
