### ISSUE TITLE
Ray SGD / Jenkins CI broken in the latest master.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9016]
### What is the problem?

1. Github Action Ray SGD build is broken. (ex, https://github.com/ray-project/ray/runs/783840946)
2. Jenkins CI is broken (you can see it is broken from all the PRs created recently). (ex, https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/27293/)
3. Jenkins CI is not running in the master build. (Not sure if it is intended).

**Comment by mehrdadn** [comment]
I see

    Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory

Did some CUDA thing change recently?

**Comment by rkooo567** [comment]
@richard4912 Is this addressed?

**Comment by richardliaw** [comment]
Yes, iirc. Do you still see this?
