### ISSUE TITLE
MLflow artifacts

### ISSUE THREAD

**Issue by santiagoolivar2017** [ray-project/ray#9021]
Why is MLflow artifact logging support not included?

With the current version of ray is it possible to somehow save the model artifacts within the mlruns main directory or am I forced to use my trainable's _logdir?

Currently all my metrics and parameters are saved in a general mlruns folder where I can use the mlflow ui, but I am forced to save my artifacts within the my trainable's _logdir so I am not able to build a consolidated mlruns folder where all the models, metrics and parameters are in the same place.

Currently my _save function looks like this

```
def _save(self, checkpoint_dir):
    ...
    ...
    mlflow.pytorch.log_model(self.model, "models")
```

Which saves the object within each _logdir so I end up with many mlruns folders for the artifacts, one per trained model

**Comment by richardliaw** [comment]
instead of `mlflow.pytorch.log_model(self.model, "models")` can you use an absolute path for the artifact path?

**Comment by richardliaw** [comment]
@rkooo567 the formatting for the bot is off

**Comment by rkooo567** [comment]
My bad. Let me fix rn. (Will double check with markdown)
