### ISSUE TITLE
[Slurm] Unable to connect to Redis

### ISSUE THREAD

**Issue by pengyuan-zhou** [ray-project/ray#9028]
Env: CentOS Linux 
Platform: Slurm
Release: ray 0.7.3

Hi all,
I posted the issue two months ago and now migrate it here.
The error seems to be about: `    raise Exception("Unable to connect to Redis. If the Redis instance is "
Exception: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.
srun: error: ukko2-04: task 0: Exited with exit code `

Please check the [err file](https://bitbucket.org/pengyuanzhou/ray/src/master/foobar-singleagent.err) and the [logs](https://bitbucket.org/pengyuanzhou/ray/src/master/session_2020-06-19_07-40-32_545003_36249/).

Thank you.
BR,
Pengyuan

**Comment by rkooo567** [comment]
All ray processes at each node needs to be able to reach to the Redis running in the Ray head node. This error means for some reasons, Ray processes cannot reach to that process. It is usually environment specific, so it is extremely hard for us to troubleshoot. One thing you can probably try is

1. Try sending a request from one of Ray worker nodes to the head node Redis.
2. Most likely you will fail to do this. Figure out why it is not connected. There can be many possible reasons such as firewall settings, unopened ports, or etc.

**Comment by pengyuan-zhou** [comment]
> All ray processes at each node needs to be able to reach to the Redis running in the Ray head node. This error means for some reasons, Ray processes cannot reach to that process. It is usually environment specific, so it is extremely hard for us to troubleshoot. One thing you can probably try is
> 
> 1. Try sending a request from one of Ray worker nodes to the head node Redis.
> 2. Most likely you will fail to do this. Figure out why it is not connected. There can be many possible reasons such as firewall settings, unopened ports, or etc.

Thanks for the quick reply. Any doc I could look at the command of doing that?

**Comment by pengyuan-zhou** [comment]
> All ray processes at each node needs to be able to reach to the Redis running in the Ray head node. This error means for some reasons, Ray processes cannot reach to that process. It is usually environment specific, so it is extremely hard for us to troubleshoot. One thing you can probably try is
> 
> 1. Try sending a request from one of Ray worker nodes to the head node Redis.
> 2. Most likely you will fail to do this. Figure out why it is not connected. There can be many possible reasons such as firewall settings, unopened ports, or etc.

Hi SangBin @rkooo567 , I've consulted the slurm admin and he suggests me to check whether ray is using Infiniband (RDMA) interface. If it's using ethernet (tcp), then that could be the issue. 
Thank you.

**Comment by richardliaw** [comment]
@pengyuan-zhou thank you for posting this! Ray does not use infiniband interface; it only uses TCP to communicate between workers.

**Comment by pengyuan-zhou** [comment]
> @pengyuan-zhou thank you for posting this! Ray does not use infiniband interface; it only uses TCP to communicate between workers.

Hi Richard, thanks for the reply. In that case, does ray support put head and a sole worker in a same node?
BR

**Comment by piggybox** [comment]
I'm following the ray-serve example in the github page and got the error right away on Mac. Totally confused about the error msg as I'm just running it locally. Hope this part can be more friendly to newbies

**Comment by richardliaw** [comment]
@piggybox can you open a new issue for this?
