### ISSUE TITLE
[tune] access tune result asynchronously

### ISSUE THREAD

**Issue by smilesun** [ray-project/ray#9048]
### What is your question?
Ray 0.8.5, pytorch 1.0, ubuntu 18

I found from the demo that once could analyze the tuning result with the following code, but the code below is synchronous, which means one has to wait until the whole tuning finishes before one could access the dataframe containing the hyper-parameter vs performance table. 

```
analysis = tune.run(
    train_mnist, config={"lr": tune.grid_search([0.001, 0.01, 0.1])})
print("Best config: ", analysis.get_best_config(metric="mean_accuracy"))
# Get a dataframe for analyzing trial results.
df = analysis.dataframe()
```

After search for quite a while, I did not find out if there is any docs showing asynchrnous ways  to look at tuning results. 
For example, one could open a python console, and then load some registry name (where to get this registry name?), and then fetch the up to now available tuning result as a dataframe.  Is it possible to do that?

**Comment by richardliaw** [comment]
I think you can try manually creating the `ExperimentAnalysis` object: https://docs.ray.io/en/latest/tune/api_docs/analysis.html#experimentanalysis

**Comment by richardliaw** [comment]
You can do this with the Ray Client API (https://docs.ray.io/en/master/tune/api_docs/client.html#tune-client-api).
