### ISSUE TITLE
Repeated puts in Ray

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#905]
One pattern that comes up frequently is the following:

```
weights = np.mean([some model weights])
training_results = [training_function.remote(weights, data) for data in data_list]
```

Here weights will be put into the object store multiple times. A better way to do it is

```
weights = ray.put(np.mean([some model weights]))
training_results = [training_function.remote(weights, data) for data in data_list]
```

The question is if we can make this automatic so users don't have to think about it?

(A) One very performant way to solve the problem is to keep a hashmap of PyObject* in the python interpreter and only put the object if it hasn't been put before.

One downside of this is that it won't be correct if the object has been modified between put calls.

(B) A correct solution is to hash the object content and keep a hashtable based on that. This will only make the operation a little bit faster since hashing objects is expensive but reduces RAM consumption of the Plasma store.

(C) Another option is to give a warning based on PyObject* pointer comparison as in (A) and do the put anyways, which would be correct and points the user to the correct fix.

**Comment by istoica** [comment]
I'd evaluate the performance of (b), and  if it is indeed high overhead, I would do (c) right away. 

The reason for evaluating (b) is because, as far as I remember from the Plasma experiments, computing the object hash was much faster than creating the object.

The for (c) is because, I suspect, passing by reference as well as memory allocation subtleties are not very familiar to most Python users.

**Comment by robertnishihara** [comment]
Yeah, `A` worries me for correctness reasons.

I think `B` requires following all the pointers and completely serializing the object so may not help with speed (definitely worth evaluating though). It could help with memory consumption if we implement object ID aliasing in the Plasma store.

`C` makes sense though I would consider doing the following to cut down on verbosity.
- Don't do it for certain types (e.g., ints, floats, strings, `None`, etc).
- Clear the set of pointers every time a new task starts.

**Comment by robertnishihara** [comment]
A related issue mentioned by @stephanie-wang, which may be solvable using the same solution is when you want to do something like

```python
@ray.remote
def foo(x):
    print(x.shape)  # Use x in some way.
    pass

@ray.remote
def bar(x):
    print(x.shape)  # Use x in some way.
    foo.remote(x)

x = # something very big
ray.get(bar.remote(x))
```

Then `x` will be serialized twice. Ideally, the call to `foo.remote` would reuse the object ID created by calling `bar.remote`.

**Comment by virtualluke** [comment]
In addition to (c), perhaps documentation for awareness of best practices and how to be efficient with ray mechanisms?
