### ISSUE TITLE
[tune] AsyncHyperBandScheduler has different default brackets than the original paper

### ISSUE THREAD

**Issue by goulou** [ray-project/ray#9058]
### What is the problem?

In current (0.8.7) version of Ray, the default bracket count is not that of the [original Paper.](https://arxiv.org/abs/1810.05934) 

Citation of the paper :

> Selecting ASHA default settings. Our experiments in Section 4 and the experiments conducted by Li et al. (2018) both show that aggressive early-stopping is effective across a variety of different hyperparameter tuning tasks. Hence,using both works as guidelines, we propose the followingdefault settings for ASHA:
> 
>   * Elimination rate:  we set η=  4 so that the top 1/4 of configurations are promoted to the next rung
>   * Maximum early-stopping rate: we set the maximum early-stopping rate for bracket s0 to allow for a maximum of 5 rungs which indicates a minimum resource of r = (1/4^4)*R = R/256.
> Then the minimum resource perconfiguration for a given bracket s is rs=rη^s
>   * Brackets to run: to increase robustness to misspecification of the early-stopping rate, we default to running the threemost aggressively early-stopping brackets **s= 0, 1, 2** of ASHA. We exclude the two least aggressive brackets (i.e. s4 with r4=R and s3 with r3=R/4) to allow for higher speedups from early-stopping. We define this default set of brackets as the ‘standard’ set of early-stopping brackets, though we also expose the options for more conservative or more aggressive bracket sets.
> 

Here is the constructor code :
```
    def __init__(self,
                 time_attr="training_iteration",
                 reward_attr=None,
                 metric="episode_reward_mean",
                 mode="max",
                 max_t=100,
                 grace_period=1,
                 reduction_factor=4,
                 brackets=1):

```

Here, the default number of bracket is 1 while it was proposed to be 3 in the paper. I cannot find any logical explanation to that.

I am not 100% sure about the maximum early-stopping rate, which is translated in the _rung calculation code ( `self._rungs = [(min_t * self.rf**(k + s), {}) for k in reversed(range(MAX_RUNGS))]`) because of the `k` factor, but it seems OK.

**Comment by richardliaw** [comment]
Hey, @goulou this was an intentional change after speaking with the ASHA authors, who mentioned that s=0 performs best in practice. 

If you look at their experiments, their results and benchmarks all use s=0.

**Comment by goulou** [comment]
OK, thanks for the anwser. I can close the issue if you want, but maybe you want to add a comment in the code or documentation explaining that detail?

**Comment by richardliaw** [comment]
Hm, yeah that would be a good idea. Would you be willing to open a small PR to the docs? Happy to help merge it.

**Comment by chanshing** [comment]
@richardliaw @goulou Does `brackets=3` also include the case for 0, 1, 2? Or do we need to pass `brackets=[0,1,2,3]`?
Also, what if I have one of those "slow winners" performance curves, where it starts off very low but ultimately achieves the best performance? Does increasing `brackets` help?
