### ISSUE TITLE
Cloning catapult takes way too long. Speed this up.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#906]
Currently when using the web UI, the first time you click on "View Task Timeline", the catapult repository https://github.com/catapult-project/catapult will be cloned. This takes on the order of **minutes**. This needs to be faster.

Some thoughts and questions:
1. A quick looks suggests that the catapult repo is about 270MB, and 265MB of that is in the .git file, so if we could just clone a snapshot of the repo at the right commit without getting the git history that would help a lot (the remaining 5MB seems to be scattered around large html files).
2. Naively packaging catapult in our wheels would make our wheels enormous and slow to download, however, it should be ok if we first remove the git history.
3. Question, how much of catapult do we actually need?

So, if possible, a great short-term fix would be to figure out how to get only a snapshot of the repo without the git history.

Later, we should just the repo with our wheels after we've removed the git history and ideally other unnecessary files as well. For people building Ray from source, we can clone catapult in `build.sh` and cache it.

@alanamarzoev @Wapaul1 any thoughts about this?

**Comment by alanamarzoev** [comment]
@robertnishihara afaik, you should only need catapult tracing. 

I think that just taking a snapshot of the repo should work.

**Comment by robertnishihara** [comment]
Right. I googled a little bit and didn't find a way to do that, but I'm sure there is one..

**Comment by Wapaul1** [comment]
`git clone --depth=1` on catapult results in a reduction of 160 MB in the `.git` directory to a total download size of 107 MB. While this is better, we may want to consider forking catapult and keeping all the important files.

**Comment by ericl** [comment]
It would also be nice to print "this might take a while" in the UI so that users don't get confused.

**Comment by pcmoritz** [comment]
We should look into speeding it up by extracting/minifying the relevant parts and deploying with the python wheel, bower should have an option for that.

**Comment by alanamarzoev** [comment]
I think that either cloning catapult or extracting the relevant files from catapult and including them with the python wheel/in the build.sh script would be better than what we're currently doing. Even if it ends up not being significantly faster, it at least wouldn't interfere with the perceived interactivity of the UI.
