### ISSUE TITLE
[ray] Make Ray compatible with latest redis

### ISSUE THREAD

**Issue by mirekphd** [ray-project/ray#9069]
### Describe your feature request

When you try to combine latest `ray` and `ray[tune]` py packages from PyPI  with the latest `redis` py package (also from PyPI) you get an error, caused by `ray` pinning its Redis dependency in a rather restrictive, non-future-proof way (with a rarely seen "less" inequality sign) blocking Redis from any future upgrades or patches.

`pip` error message:
```
ERROR: ray 0.8.5 has requirement redis<3.5.0,>=3.3.2, but you'll have redis 3.5.3 which is incompatible.
```

**Comment by rkooo567** [comment]
It is because of this issue https://github.com/ray-project/ray/issues/8257. We need some refactoring to unpin the Redis version (and we didn't get to have bandwidth to do so). Please feel free to submit a PR!
