### ISSUE TITLE
Less confusing parameter names for run(resources_per_trial): cpu -> num_physical_cpus and init(): num_cpus -> num_threads

### ISSUE THREAD

**Issue by mirekphd** [ray-project/ray#9070]
Setting `resources_per_trial={'cpu': 8, 'gpu': 0}` parameter in `tune.run()` will not prevent Ray from using all CPU threads in all available CPUs (note there may be up to 4 per server, perhaps more). Such high level of concurrency interferes with other users and is usually slower than running training on the optimized number of threads, which is usually lower than the maximum, depending on the currently used algorithm. 

Apparently, the only way to limit global CPU usage (amount of concurrency) is to issue `ray.shutdow()` and set `ray.init(num_cpus=8)` prior to calling `tune.run()`. In that light `resources_per_trial()` looks totally ineffective, so it perhaps should be made to work or be deprecated, because currently it is much easier to find the ineffective solution than the working one (given that the ineffective one is a parameter of the most frequently used function `run()`).

**Comment by mirekphd** [comment]
OK, so through trial and error I found out that `cpu` in `resources_per_trial` param of `run()` refers to *physical* CPUs, increasing which above 1 will reduce model training performance in algos such as GBDTs. The similarly named `num_cpus` in `init()` refers to threads, and this can / should be indeed optimized. 

Some of my results:
```
# 1000 runs, n_jobs=1, num_physical_cpus=1:
# - ray_num_cpu_threads=4: executed in 3m 33s, finished 18:46:43 2020-06-21
# - ray_num_cpu_threads=8: executed in 1m 56.5s, finished 18:41:33 2020-06-21
# - ray_num_cpu_threads=16: executed in 1m 28.2s, finished 18:17:59 2020-06-21
# - ray_num_cpu_threads=32: executed in 1m 22.3s, finished 18:28:52 2020-06-21
# - ray_num_cpu_threads=64: executed in 1m 23.4s, finished 18:35:33 2020-06-21

# 1000 runs, n_jobs=1, num_physical_cpus=2:
# - ray_num_cpu_threads=4: executed in 6m 55s, finished 20:02:37 2020-06-21
# - ray_num_cpu_threads=8: 
# - ray_num_cpu_threads=16: executed in 1m 56.2s, finished 19:10:01 2020-06-21
# - ray_num_cpu_threads=32: 
# - ray_num_cpu_threads=64: executed in 1m 33.6s, finished 20:09:42 2020-06-21

# 1000 runs, n_jobs=1, num_physical_cpus=4:
# - ray_num_cpu_threads=4: executed in 16m 13s, finished 19:48:44 2020-06-21
# - ray_num_cpu_threads=8: 
# - ray_num_cpu_threads=16: executed in 3m 11s, finished 19:21:56 2020-06-21
# - ray_num_cpu_threads=32: 
# - ray_num_cpu_threads=64: executed in 1m 37.6s, finished 20:07:03 2020-06-21
```

**Comment by mirekphd** [comment]
To avoid confusion, I therefore propose the following parameter name changes:
```
run(resources_per_trial={'cpu': n})  --> run(resources_per_trial={'num_physical_cpus': n})
```
and 
```
init(num_cpus=n) --> init(num_threads=n)
```

**Comment by richardliaw** [comment]
Hey @mirekphd thanks for opening this issue. For some context, can you describe what you're trying to do? 

To clarify, Ray does not actually do CPU isolation. `num_cpus` and `resources_per_trial` are related in that `num_cpus` dictates the total number of "CPU resources" you plan to use, and `resources_per_trial` indicates how "CPU resources" should be given to each individual trial. 

That being said, CPU resource is strictly for bookkeeping.

**Comment by mirekphd** [comment]
> That being said, CPU resource is strictly for bookkeeping.

Strange, because the timings above indicate scaling typical for multi-threaded computations where a Kubernetes / Openshift orchestrator restricts CPU threads usage proportionally to the user-specified limits, but.,. using all CPUs (in small fractions adding up to the desired total).

Yesterday I got an an unambiguous error message to do with "physical CPUs" when I set it to a number exceeding the number of physical CPU sockets, but today, after several stability improvements, I cannot reproduce the error message...

The problem of poor scaling above seems to arise from the assumption of just a single CPU socket is available to the python kernel, because when I increased the number of sockets (assuming for a while that it actually worked like that), performance deteriorated as a function of the number of sockets.

From my earlier experiences with multi-threaded GBDT's algos (catboost, xgboost, lightgbm, H2O GBM), on multi-socket servers where process isolation is provided by Docker containers (cgroups) rather than strongly isolating VM's, all sockets are available during model training, to the detriment of computation time, so one has to rely on the threading built into the algos in order to limit the cores rather than on the orchestrator's CPU throttles.

Or is just that multithreading is more efficient than multiprocessing in such scenarios? Trying to pin multiple threads (as set by the `n_jobs` parameter) at 100% utilization for as long as reasonably possible turns out to be an efficient approach, and is used by both lightgbm (believed to be the best-scaling GBDT algo) and xgboost.

Here's a quick but surprisingly difficult to beat benchmark for Ray Tune: LightGBMs built-in threading mechanism (relying only on its built-in threading limits set by the `n_jobs` parameter passed to the train function). It builds on your own hyperparameter example for lightgbm:

```
lgbm_num_cpu_threads=64

results_list=[]

for i in range(1000):
    
    try:
        results_list.append(train_lgbm(hyperparams=random_hyperparams_dict, 
                                       n_jobs=lgbm_num_cpu_threads))        
    except:
        print("Error in run %d" % i)

sorted(results_list)

# lgbm_num_cpu_threads=4 # executed in 36.4s, finished 21:51:41 2020-06-22
# lgbm_num_cpu_threads=8 # executed in 35.5s, finished 22:16:53 2020-06-22
# lgbm_num_cpu_threads=16 # executed in 42.0s, finished 22:20:08 2020-06-22
# lgbm_num_cpu_threads=32 # executed in 54.9s, finished 22:22:03 2020-06-22
# lgbm_num_cpu_threads=64 # executed in 1m 47.3s, finished 22:24:11 2020-06-22    
```

vs.

```
results = tune.run(
    train_breast_cancer,
    config=hyperparams_dict,
    num_samples=num_experiments,
    # caution: this will still use all cores! use ray.init(num_cpus=) instead
    # resources_per_trial={'cpu': 1, 'gpu': 0}, 
    resources_per_trial={'cpu': num_physical_cpus, 'gpu': num_physical_gpus},     
    scheduler=ASHAScheduler(metric=cur_metric, mode=cur_metric_dir),
    verbose=0)

# 1000 runs, n_jobs=1, num_physical_cpus=1:
#
# - ray_num_cpu_threads=8: executed in 1m 56.5s, finished 18:41:33 2020-06-21
# - ray_num_cpu_threads=8: executed in 2m 2s, finished 22:28:34 2020-06-22
# - ray_num_cpu_threads=8: executed in 2m 0s, finished 22:33:54 2020-06-22
# - ray_num_cpu_threads=8: executed in 2m 0s, finished 22:36:16 2020-06-22
#
# - ray_num_cpu_threads=16: executed in 1m 28.2s, finished 18:17:59 2020-06-21
# - ray_num_cpu_threads=16: executed in 1m 33.9s, finished 20:35:09 2020-06-22
# - ray_num_cpu_threads=16: executed in 1m 32.9s, finished 20:41:46 2020-06-22
# - ray_num_cpu_threads=16: executed in 1m 30.2s, finished 20:43:31 2020-06-22

```

**Comment by richardliaw** [comment]
Yeah, good point - RayTune is going to incur multi-processing startup overheads between different models, AND ipc calls during training (for reporting intermediate progress). That's probably why you're seeing a large slowdown. 

What's the benchmark when if you set 
 1. `resources_per_trial` = 64, and 
 2. `ray.init(num_cpus=64)` and
 3. lgbm_num_cpu_threads=64?
