### ISSUE TITLE
[tune][rllib] Tune does not work with PolicySeverInput

### ISSUE THREAD

**Issue by nfusionz** [ray-project/ray#9075]
### What is the problem?
We are trying to perform hyper parameter tuning with the PolicyServer/Client architecture. However, Tune appears to create multiple instances of the PolicyServer, resulting in port conflicts. The following is output for the state of the various trials before running a client.
```
Number of trials: 3 (1 ERROR, 2 TERMINATED)                                 
+-----------------------+------------+-------+--------+                     
| Trial name            | status     | loc   |     lr |                     
|-----------------------+------------+-------+--------|                     
| PPO_CartPole-v0_00000 | TERMINATED |       | 0.01   |                     
| PPO_CartPole-v0_00001 | TERMINATED |       | 0.001  |                     
| PPO_CartPole-v0_00002 | ERROR      |       | 0.0001 |                     
+-----------------------+------------+-------+--------+                     
Number of errored trials: 1                                                 
+-----------------------+--------------+------------------------------------
----------------------------------------------------------+                 
| Trial name            |   # failures | error file                         
                                                          |                 
|-----------------------+--------------+------------------------------------
----------------------------------------------------------|                 
| PPO_CartPole-v0_00002 |            1 | /home/xieo/ray_results/PPO/PPO_Cart
Pole-v0_2_lr=0.0001_2020-06-21_20-14-28y56ya29k/error.txt |                 
+-----------------------+--------------+------------------------------------
----------------------------------------------------------+ 
```
The corresponding error file contains a traceback with `OSError: [Errno 98] Address already in use`.

Interestingly, the clients still manage to run one of the trials before their connection is reset, and the server crashes with the following message:
```
Traceback (most recent call last):                                          
  File "env_server.py", line 24, in <module>                                
    tune.run(                                                               
  File "/home/xieo/git/benedict/venv/lib/python3.8/site-packages/ray/tune/tu
ne.py", line 347, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_CartPole-v0_00000
])
```
In addition, trying `ray.init(local_mode=True)` results in the server failing silently after the first trial.

We've also tried this on Windows 10 & WSL (Ubuntu), where instead, the server runs each trial one by one, and the client needs to be rerun to complete all three trials. No error messages are output then.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ubuntu Info:
Ray: 0.8.5
Python: 3.8.0
TensorFlow: 2.2.2
OS: Ubuntu 18.04

Windows Info:
Ray: 0.8.5
Python: 3.8.2
TensorFlow: 2.2.2
OS: Windows 10 (WSL, Ubuntu 20.04)

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray

from ray import tune
from ray.tune.logger import pretty_print
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.env.policy_server_input import PolicyServerInput

SERVER_ADDRESS = "localhost"
SERVER_PORT = 9900

if __name__ == "__main__":
    ray.init(local_mode=False)
    config = {
        "input": (lambda ioctx: PolicyServerInput(
            ioctx, SERVER_ADDRESS, SERVER_PORT)
        ),
        "num_workers": 0,
        "input_evaluation": [],
        "env": "CartPole-v0",
        "batch_mode": "complete_episodes",
        "lr": tune.grid_search([0.01, 0.001, 0.0001]),
    }

    tune.run(
        "PPO",
        stop={"episode_reward_mean": 100},
        fail_fast=True,
        config=config,
    )
    print("Done!")
```

```
import gym

from ray.rllib.env.policy_client import PolicyClient

if __name__ == "__main__":
    env = gym.make("CartPole-v0")
    client = PolicyClient("http://localhost:9900")

    eid = client.start_episode(training_enabled=True)
    obs = env.reset()
    rewards = 0

    while True:
        action = client.get_action(eid, obs)
        obs, reward, done, info = env.step(action)
        rewards += reward
        client.log_returns(eid, reward, info=info)

        if done:
            print("Reward: {}".format(rewards))
            rewards = 0
            client.end_episode(eid, obs)
            obs = env.reset()
            eid = client.start_episode(training_enabled=True)
```

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

Edit: Remove extra error message with 0.9.0.dev0, as the example (before the edit) used the deprecated policy_client.

**Comment by sereysethy** [comment]
Hi, I also tried to use tune with custom environment, and I faced the same issue. There is only one instance running (in my case) from what I understand and Tune reported that the `OSError: [Errno 48] Address already in use`.

```
Number of trials: 1 (1 ERROR)
+------------------------+----------+-------+
| Trial name             | status   | loc   |
|------------------------+----------+-------|
| DQN_custom_env_00000 | ERROR    |       |
+------------------------+----------+-------+
Number of errored trials: 1
+------------------------+--------------+----------------------------------------------------------------------------------------+
| Trial name             |   # failures | error file                                                                             |
|------------------------+--------------+----------------------------------------------------------------------------------------|
| DQN_custom_env_00000 |            1 | /home/stouch/ray_results/DQN/DQN_custom_env_0_2020-06-23_21-27-2379gt2u54/error.txt |
+------------------------+--------------+----------------------------------------------------------------------------------------+

 ```

**Comment by edoakes** [comment]
This is not currently supported

**Comment by gramhagen** [comment]
what if you change the lambda function `lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)`

to something like this:

```
import itertools

SERVER_ADDRESS = "localhost"
SERVER_PORT = itertools.count(start=9900)

if __name__ == "__main__":
    ray.init(local_mode=False)
    config = {
        "input": lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, next(SERVER_PORT)),
...
```

then you can spin up clients to talk to each port-parameter pairing

**Comment by alexenos** [comment]
> what if you change the lambda function `lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, SERVER_PORT)`
> 
> to something like this:
> 
> ```
> import itertools
> 
> SERVER_ADDRESS = "localhost"
> SERVER_PORT = itertools.count(start=9900)
> 
> if __name__ == "__main__":
>     ray.init(local_mode=False)
>     config = {
>         "input": lambda ioctx: PolicyServerInput(ioctx, SERVER_ADDRESS, next(SERVER_PORT)),
> ...
> ```
> 
> then you can spin up clients to talk to each port-parameter pairing

I tried @gramhagen suggestion, and it did not work for me. 

Regardless, I am also interested in support for using tune with external applications through the `PolicyServerInput`

**Comment by sephirxth** [comment]
Hi, same problem. I use ZMQ (connect a cpp client and a RAY policy server) and a customized env inherited from ExternalEnv. Tune will try to create more than one env, even I use ray.init(local_mode = True) and  max_concurrent=1. 

My external env cannot be parallelized,  I just need the Tune runs trails sequentially.

**Comment by simonsays1980** [comment]
There are two solutions at this point that worked out so far: 

1. Try to wrap your environment into an `ExternalEnv` and avoid the `PolicyInputServer` completly.
2. Inherit from `PolicyInputServer` and start `Actor`s that contain your environment logic and start your external simulator. Here you have to also implement the fault intolerance to deal with the external simulator, i.e. a plan how to deal with actor crashes (do not start any new actor, try to recreate the same actor, just start a new actor).
