### ISSUE TITLE
[docs] Issue on `tune/api_docs/grid_random.rst`

### ISSUE THREAD

**Issue by ElektroChan89** [ray-project/ray#9084]
# Documentation Question
Hey guys,
I'm new to ray and tune and reading the docs at the moment.
I have a question regarding the following code example from the docs:

```
# 13 different configs.
tune.run(trainable config={
    "x": tune.choice([0, 1, 2]),
    }
)
```

Why is tune running 13 different trials here? ``` num_samples ``` is not set, so by default it should be 1 trial.

Best regards 

(Created directly from the docs)

**Comment by richardliaw** [comment]
I think that's a typo; can you help push a fix? Thanks!
