### ISSUE TITLE
[tune] Bring HParams to PyTorch training

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#9089]
### Describe your feature request

AFAIK the following is only supported if TF is used. It be great to have a PyTorch support as well.
https://docs.ray.io/en/master/_images/tune-hparams-coord.png

**Comment by richardliaw** [comment]
@roireshef what version of Ray are you on? I think this should work all the time now!

**Comment by roireshef** [comment]
@richardliaw thanks for your response. Last time I checked this was on 0.8.5. I'll check again. What version is it on for PyTorch from?

**Comment by richardliaw** [comment]
Can you try installing `pip install 'ray[tune]'`? It worked for torch 1.4 at a minimum.
