### ISSUE TITLE
[rllib] How to collect training results?

### ISSUE THREAD

**Issue by stefanbschneider** [ray-project/ray#9104]
### What is your question?

I'm using RLlib with `results = tune.run(custom_train,...)` to train a PPO agent.
I've been struggling for hours now to somehow get a list of all episode rewards after training.
In the results, there is `hist_stats/episode_reward`, but this only seems to include the last 100 rewards or so. 

I tried making my own list inside the `custom_train` function but I can't seem to get it out of the function. My only success was writing it back into the results dict that is then called `reporter(**results)`. But in the end, that gave me not a list of numbers, but a huge string representing the list; so it's not usable.

I simply want a list of all episode rewards so that I can plot a learning curve. If there's any utility function for that, that would also be perfect. I know there is tensorboard, but I want to plot and save the learning curve automatically.

Any help is appreciated.

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Ray 0.8.5
* Tensorflow 2.2.0
* Python 3.8.3
* OS: Ubuntu 20.04 on WSL (Win 10)

**Comment by chokosabe** [comment]
Been wondering about this as well. a couple of hints in the code but would be nice to develop some docs that address this specifically

**Comment by josephcarmack** [comment]
I'm using Rays RLLib and training runs get saved off to a file name "progress.csv" which has lots of stats on rewards and other things. Maybe trying to use RLLib would make it easier for you in the short term.

**Comment by stefanbschneider** [comment]
Yes, that's what I'm doing now. `progress.csv` also contains stats on my custom metrics, so this works fine.

**Comment by aelyacho** [comment]
Hi @stefanbschneider, do you mind sharing the part of your code with the custom metrics/ callback function for episode rewards? My callback function returns an error claiming that some values are Nans, but I can't figure out where this is coming from. Thanks for your help.

**Comment by stefanbschneider** [comment]
@aelyacho Sure, here's my callback implementation logging my custom metrics `'scalar_metrics'`, which I save inside my `info` dict: https://github.com/CN-UPB/DeepCoMP/blob/master/deepcomp/util/callbacks.py
