### ISSUE TITLE
[raySGD][question] Can we support multi-GPU for one TFRunner? 

### ISSUE THREAD

**Issue by gaocegege** [ray-project/ray#9113]
### Describe your feature request

It seems that we only create TFRunner with 1 GPU here https://github.com/ray-project/ray/blame/master/python/ray/util/sgd/tf/tf_trainer.py#L54

```python
        # Generate actor class
        # todo: are these resource quotas right?
        # should they be exposed to the client codee?
        Runner = ray.remote(num_cpus=1, num_gpus=int(use_gpu))(TFRunner)
```

If I understand right, one TFRuner is for one TF worker. Can we support multi-GPU for one TFRunner?

I'd appreciate it if @richardliaw or @ConeyLiu could help (Last changes are commited by you two)

Thanks!

**Comment by ConeyLiu** [comment]
Right now, we don't support it. However, I think add the support is easy. What is your usage scenario? Can't the model fit into a GPU?

**Comment by gaocegege** [comment]
Just wanna make sure that if there is any limitation or not implemented yet.

**Comment by ConeyLiu** [comment]
OK, I can add support. Wait for @richardliaw opinion.

**Comment by richardliaw** [comment]
Agree! Easy to support. Ce Gao why do you ask? are you adding Ray to
kubeflow 🤩?

**Comment by gaocegege** [comment]
I am **always** trying to support Ray on Kubeflow (Deploying Ray cluster in Kubeflow deployments, or having great integration with Kubeflow components)

Recently in Kubeflow community, we have a new operator https://github.com/kubeflow/fate-operator for Federated ML. It introduces two CRDs (one is for Federated ML Cluster, the other is for FML Job). Users can:

- Create a new FML cluster on Kubernetes
- Use this FML cluster to run FML jobs

I am trying to investigate if we can support Ray like this:

- Create a new Ray cluster using https://github.com/ray-project/ray/tree/master/deploy/ray-operator
- Use a new CRD `RayDriverJob` or `RayJob` to run Ray programs on the created Ray cluster on Kubernetes.

Although it is not related to this issue. This issue is to make sure that I am on the same page with ray community about distributed training with Ray and DL frameworks.

**Comment by anencore94** [comment]
> support Ray on Kubeflow 

Is there any progress or tracking issue with this feature @gaocegege  ?

**Comment by gaocegege** [comment]
> > support Ray on Kubeflow
> 
> Is there any progress or tracking issue with this feature @gaocegege ?

Ray now has its own operator https://github.com/ray-project/ray/tree/master/python/ray/ray_operator, thus we do not have the future plan to do it.

**Comment by gaocegege** [comment]
I am closing the issue since it is stale.
