### ISSUE TITLE
Ray doesn't run with Unicode file paths on Windows

### ISSUE THREAD

**Issue by mehrdadn** [ray-project/ray#9117]
### What is the problem?

Unicode file paths can cause problems on Windows.

### Reproduction (REQUIRED)

Create a username with non-ASCII characters, then try installing Ray:
```
> python -m pip install ray
```
This may produce an error due to character encoding issues. However, it may succeed on subsequent runs.

Once it succeeds, run Ray:
```
> python -c "import ray; ray.init()"
2020-06-23 21:34:52,720 INFO resource_spec.py:204 -- Starting Ray with 2.88 GiB memory available for workers and up to 1.44 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-23 21:34:52,830 WARNING services.py:923 -- Redis failed to start, retrying now.
...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 719, in init
    _global_node = ray.node.Node(
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\node.py", line 180, in __init__
    self.start_head_processes()
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\node.py", line 681, in start_head_processes
    self.start_redis()
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\node.py", line 491, in start_redis
    process_infos) = ray.services.start_redis(
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\services.py", line 752, in start_redis
    port, p = _start_redis_instance(
  File "C:\Users\? ?\AppData\Roaming\Python\Python38\site-packages\ray\services.py", line 947, in _start_redis_instance
    raise RuntimeError("Couldn't start Redis. "
RuntimeError: Couldn't start Redis. Check log files: C:\Users\? ?\AppData\Local\Temp\ray\session_2020-06-23_21-34-52_720718_2092\logs\redis.out C:\Users\? ?\AppData\Local\Temp\ray\session_2020-06-23_21-34-52_720718_2092\logs\redis.err
```

The only non-empty file is `redis.out`, which contains:

	# Module C:\Users\? ?\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\core/src/ray/gcs/redis_module/libray_redis_module.so failed to load: "C:\Users\? ?\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\core\src\ray\gcs\redis_module\libray_redis_module.so": The specified module could not be found.
	# Can't load module from C:\Users\? ?\AppData\Local\Programs\Python\Python38\lib\site-packages\ray\core/src/ray/gcs/redis_module/libray_redis_module.so: server aborting

N‍‍ote that other issues are also likely; this is just one instance.

## Related issue number

#9114

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rightx2** [comment]
Did you solve it?

**Comment by mehrdadn** [comment]
@rightx2 Not yet. This might not be solved in the short term, I'm not sure. But if this negatively impacts you, you should upvote the question to help the team prioritize looking into it.

**Comment by rightx2** [comment]
@mehrdadn why don't you run `sudo pkill redis-server && sudo pkill redis && sudo service redis-server stop`?

**Comment by mehrdadn** [comment]
@rightx2 What does that have to do with Unicode on Windows?

**Comment by rightx2** [comment]
@mehrdadn Oops, I was trying to give you solution about `RuntimeError: Couldn't start Redis`. Have no idea about unicode. Sorry

**Comment by mehrdadn** [comment]
This bug is definitely not fixed...

**Comment by pcmoritz** [comment]
Thanks for trying to reproduce this! Let's close this then until somebody has a more detailed reproduction (maybe the exact user name and locality setting). If there is a reproduction please feel free to re-open :)

**Comment by mehrdadn** [comment]
I would try a username that's "far" from English, like say Chinese or Arabic. If you merely used a letter like é then that might not work, because Windows's default 8-bit charset supports some characters in the range 0x80-0xFF.

**Comment by mattip** [comment]
I tried a username in Hebrew

**Comment by mehrdadn** [comment]
Ah interesting, ok. Have you set Windows to UTF-8 by any chance? It was an experimental new feature they added in Windows 10, it might affect what you're seeing: https://superuser.com/a/1451686

**Comment by mattip** [comment]
I succeeded both ways: with and without the utf-8 beta setting.
