### ISSUE TITLE
[tune]Change variable name in ray/tune/progress_reporter.py's CLIReporter class

### ISSUE THREAD

**Issue by jCrompton** [ray-project/ray#9125]
I got confused by the CLIReporter's (ray/tune/progress_reporter.py) param name 'max_report_frequency' as this really in my opinion is more of a period, also goes in hand with some of the bottleneck warnings to increase the reporting period.
Not a big deal but may help future debugging if 'max_report_frequency' was changed to something like 'report_period'.

I am also happy to make the change if possible, happy to help in general where I can.

@richardliaw

**Comment by richardliaw** [comment]
Hey, thanks for making this issue @jCrompton! 

Would you be willing to push a PR? If so, just ping me on the PR when you do. Thanks!

**Comment by jCrompton** [comment]
Yea would be happy to @richardliaw, I'm assuming there is no rush here. Will follow up with the PR
