### ISSUE TITLE
[tune] Large "core" files generated whenever resume=True is used

### ISSUE THREAD

**Issue by ejunprung** [ray-project/ray#9127]
Hi, I was curious to know what these core files are used for and why they are so large. I suspect it's the training data for the model but I'm not sure.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.7.6
Python 3.7.3
TF 1.15.0
Debian

These large core files seem to be generated only after a resume is triggered. This can happen >2 times during training for our setup. It's hard to create a repo script so I hope this is enough information.

![image](https://user-images.githubusercontent.com/5703667/85623330-1ae8e980-b61d-11ea-9722-c696a124028d.png)

**Comment by richardliaw** [comment]
This seems odd, can you try upgrading ray?

**Comment by ejunprung** [comment]
Gotcha. We're upgrading Ray soon so I'll re-open this if it continues to be an issue. Thanks!

**Comment by ZedRover** [comment]
I'm sorry to say that I have the same problem today. I'm using the latest ray-ml docker,Ubuntu 18.04. And the version of raty is 2.1.0 and pytorch is 1.13.0, tensorflow is 2.6.2. There came large core.xxxx files once I started training agents.
![image](https://user-images.githubusercontent.com/29392414/200496755-cdb503ae-f863-41b0-9ac1-3ad24aa6c71f.png)
