### ISSUE TITLE
[tune][rllib] Windows: FileExistsError when running rllib tune job

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9128]
### What is the problem?
My script (available below) runs fine on Linux but does not fully run yet on Windows.
I can't tell exactly what went wrong, but the two major errors I see is:
`TypeError: len() of unsized object`
`FileExistsError: [WinError 183] Cannot create a file when that file already exists`

Full error log:
https://gist.github.com/juliusfrost/acbca090259610a176847e7026dd6d30

### Reproduction
Run on Windows OS
Install pytorch
Install the latest `ray` and `rllib` versions
Install `atari-py` if necessary
Download `train_a2c.py` from https://gist.github.com/juliusfrost/61b8be67d33b9bc9ab1faf7ada9d2ae3
Run `python train_a2c.py BreakoutNoFrameskip-v4`
if you don't have a gpu add `--gpus 0`

**Comment by juliusfrost** [comment]
#9114 Seems related

**Comment by edoakes** [comment]
cc @mehrdadn

**Comment by mehrdadn** [comment]
Thanks for the report! I added this to the list.

**Comment by mehrdadn** [comment]
Apparently the `TypeError: len() of unsized object` is already resolved in #8918; it's just not included in the latest release.
