### ISSUE TITLE
Ray should remove ssh fingerprints from known_hosts when tearing down a cluster

### ISSUE THREAD

**Issue by henktillman** [ray-project/ray#9131]
### Describe your feature request
When Ray kills a node or tears down a cluster, it should remove the ssh fingerprints for the corresponding IP addresses from ~/.ssh/known_hosts. GCP often reuses IP addresses, so if you delete and reprovision a node, it is common for GCP to give you the same IP. Because it's a new VM, the fingerprint is going to be different than the last node's fingerprint. This triggers `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!`, which ruins the current action. This issue probably hasn't been noticed until now because AWS rarely gives you the same IP. Currently I've been fixing this by manually deleting entries from known_hosts, but it would be nice if this happened automatically (e.g. by executing `ssh-keygen -R $DEST`). This should also happen if Ray notices that the cluster has been deleted through the GCP/AWS console.

**Comment by rkooo567** [comment]
cc @thomasdesr This seems to be that scary error that I've seen sometimes?
