### ISSUE TITLE
[webui] Generating a new task timeline requires moving the slider.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#914]
It should be sufficient to click "View task timeline" again. But it seems like you have to move the slider.

Moving the slider is probably triggering queries to the global state API, which is unnecessary (in the case of the timeline).

@Wapaul1 @alanamarzoev

**Comment by ericl** [comment]
I actually cannot reproduce this. Clicking "View task timeline" always triggers a re-render for me, which seems to include the latest tasks.

**Comment by robertnishihara** [comment]
Can you try it on this file https://github.com/ray-project/tutorial/blob/master/exercises/exercise03.ipynb?

On that notebook it feels like I have to jiggle the sliders and click on "View task timeline" multiple times before the timeline is rendered properly.

The bug might be different from what I initially described however because initially none of the `create_data` tasks showed up and only four of the `aggregate_data` tasks showed up.

**Comment by robertnishihara** [comment]
Closing because the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
