### ISSUE TITLE
ray 0.8.6 cluster not worked

### ISSUE THREAD

**Issue by yankerssnh** [ray-project/ray#9143]
In new version 0.8.6 cluster dont start

Start as in 0.8.5 version:
ray up examle-config.yml

Dashboard cant open.
Python:
import ray
ray.init(address='auto', redis_password='5241590000000000',)
cause error that cant find any ray instance

But
if I manually start ray, all OK

**Comment by mfitton** [comment]
Could you please provide some more information?
What systems are you running on?
Are you using the Ray autoscaler, then trying to connect to a dashboard on a remote head node from your local machine?

Are you in the Ray slack? My handle is @Max Fitton there if you prefer discussing there.

**Comment by RocketRider** [comment]
could be related to my issue? https://github.com/ray-project/ray/issues/9135

**Comment by yankerssnh** [comment]
> could be related to my issue? #9135

Yes, also 0.8.6 dont show workers on child nodes. It show while workers in IDLE state. But when workers goto another states, they hide

**Comment by yankerssnh** [comment]
Troubles info:
Head OS: Linux Ubuntu 19.04
examle-config.yml same as in gihub, only head and workers IPs changed.

`
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port 6379  --webui-host 0.0.0.0 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=$((200 * 1024 * 1024)) --memory=$((100 * 1024 * 1024)) --num-cpus=3

worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-store-memory=$((200 * 1024 * 1024)) --memory=$((100 * 1024 * 1024)) --num-cpus=4
`

Cant connect dash board from any - local and outside

And interested thing. If I run commands from example-config.yml directly on head and worker, cluster works! (without normal works of dashbboard)

This bugs in 0.8.6 version. 0.8.5 version worked fine!

**Comment by rkooo567** [comment]
Maybe related to https://github.com/ray-project/ray/issues/9317

**Comment by richardliaw** [comment]
Closing because fixed.
