### ISSUE TITLE
[ray] ray.init() -> "Redis failed to start, retrying now"

### ISSUE THREAD

**Issue by anqixu** [ray-project/ray#9148]
### What is the problem?

A seemingly spurious message is printed when starting `ray.init()` on Ray 0.8.5/0.8.6:

```bash
...
Successfully installed ray-0.8.6
(tune_test) mimic@MIMIC-5530-UB1804:~$ python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
r>>> ray.init()
2020-06-25 15:48:47,421	INFO resource_spec.py:212 -- Starting Ray with 5.57 GiB memory available for workers and up to 2.8 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-06-25 15:48:47,647	WARNING services.py:923 -- Redis failed to start, retrying now.
2020-06-25 15:48:47,839	INFO services.py:1165 -- View the Ray dashboard at localhost:8265
{'node_ip_address': '192.168.0.140', 'raylet_ip_address': '192.168.0.140', 'redis_address': '192.168.0.140:6379', 'object_store_address': '/tmp/ray/session_2020-06-25_15-48-47_419180_29165/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2020-06-25_15-48-47_419180_29165/sockets/raylet', 'webui_url': 'localhost:8265', 'session_dir': '/tmp/ray/session_2020-06-25_15-48-47_419180_29165'}
```

Ray continues to work as expected though, so this is likely a spurious message.

*Ray version and other system information (Python version, TensorFlow version, OS):*
* ray[tune] 0.8.5 & 0.8.6
* Ubuntu 18.04 (also seen on Windows 10 WSL2 with Ubuntu 18.04)
* Python 3.6.9
* tf 2.1.0

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
This should've been in the latest master.

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/commit/508149b3c3004ee5ef8b02bd797e26ceaac896b2
