### ISSUE TITLE
[Rllib] Calling sample remotely on evaluation workers jumbles episode executions

### ISSUE THREAD

**Issue by dennismalmgren** [ray-project/ray#9150]
### What is the problem?
I'm trying to run evaluations in a multi-agent setting, and I want to fix which actual agent interactions are tested/mapped before distributing the work to workers. When doing this I had off-by-one array errors where evaluation workers wanted to run more episodes than I called sample for, but still returned results for as many episodes as I called sample for.

It turned out that the evaluation worker starts another episode, maybe to ensure it has reached the end of an episode, before returning results from sample. The results from the final episode is not included in the results for that evaluation round. However, the state isn't reset so when the next evaluation round comes, the old results also linger.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version 0.86, Tensorflow 2.0, python 3.7.7, Ubuntu 20.04

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

I've slightly adjusted the custom_eval example script in rllib to add callbacks. If you run the script you'll see "episode start/end/start" for the first evaluation. When reaching the second evaluation, it will start with a "episode end" instead.

If we cannot run your script, we cannot fix your issue.

- [x ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

[test_custom_eval.txt](https://github.com/ray-project/ray/files/4833621/test_custom_eval.txt)

**Comment by edoakes** [comment]
cc @ericl
