### ISSUE TITLE
[dashboard] 0.8.6 two nodes with same name cause flickering

### ISSUE THREAD

**Issue by RocketRider** [ray-project/ray#9157]
I have two Ubuntu 19.10 with the exact same config (0.8.6) and name. Just the IP is different (I cloned a VM).
Then in the dashboard it shows only one of both. It switches between both (IP is changing).

Start head:
ray start --head --port=6379

worker:
ray start --address='192.168.40.129:6379' --redis-password='5241590000000000'

As soon as I changed the name of the second vm, it works as expected.

**Comment by edoakes** [comment]
@mfitton maybe we should append the IP to the node name?

**Comment by rkooo567** [comment]
@edoakes I still cannot assign @mfitton to issues. @robertnishihara Do you know how we can enable this?

**Comment by mfitton** [comment]
@edoakes that's an option. We could also perform the grouping by IP in the first place but display by hostname, since I think that is more unique than hostname.

**Comment by mfitton** [comment]
FYI, this issue is fixed in the new dashboard backend, which will be released with 1.0.2 and is currently in the nightly.
