### ISSUE TITLE
[tune] Ray-Tune Explicit Hyperparameter Initialization

### ISSUE THREAD

**Issue by leimao** [ray-project/ray#9159]
### What is your question?

Hello, I have a question about Ray-Tune hyperparameter initialization. 

This is a piece of code copied from the official [Ray-Tune tutorial](https://docs.ray.io/en/master/tune/tutorials/tune-advanced-tutorial.html).
```
    analysis = tune.run(
        PytorchTrainble,
        name="pbt_test",
        scheduler=scheduler,
        reuse_actors=True,
        verbose=1,
        stop=stopper,
        export_formats=[ExportFormat.MODEL],
        checkpoint_score_attr="mean_accuracy",
        checkpoint_freq=5,
        keep_checkpoints_num=4,
        num_samples=4,
        config={
            "lr": tune.uniform(0.001, 1),
            "momentum": tune.uniform(0.001, 1),
        })
```

We specified the population size to be 4, each of the population would sample initial hyperparameters randomly for lr and momemtum from uniform distribution (0.001, 1). I wonder if there is any way to explicitly specify the initialization. For example, I would like the initial hyperparameters for the 4 samples to be:

[{"lr": 0.1, "momentum": 0.9}, {"lr": 0.2, "momentum": 0.8}, {"lr": 0.3, "momentum": 0.7}, {"lr": 0.4, "momentum": 0.6},]

Thank you.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.9.0dev
Python 3.6

**Comment by richardliaw** [comment]
Yeah, having this support would be nice. An easy case to get working would be:

```
    analysis = tune.run(
        PytorchTrainble,
        name="pbt_test",
        config=[{"lr": 0.1, "momentum": 0.9}, {"lr": 0.2, "momentum": 0.8}, {"lr": 0.3, "momentum": 0.7}, {"lr": 0.4, "momentum": 0.6},])
```

**Comment by krfricke** [comment]
We are adding support for this in #12916 (though with a slightly different API to match existing behavior in other searchers).
