### ISSUE TITLE
[rllib] Restoring from a checkpoint captured in a previous Ray version throws an obscure exception

### ISSUE THREAD

**Issue by deanwampler** [ray-project/ray#9160]
### What is the problem?

I saved a checkpoint from a `PPOTrainer` for the Bipedal Walker gym environment, using Ray 0.8.5. I attempted to restore it later using the same code, but Ray 0.8.6. The following exception was thrown:

![rllib-error](https://user-images.githubusercontent.com/3991/85878862-3cb5ae00-b78e-11ea-85e9-faba61beedae.png)

However, when I recreated the checkpoint with 0.8.6, I could successfully restore from it.

There are a few possible resolutions, in order of difficulty and user convenience:

1. Handle checkpoints across versions (hard).
2. Detect that the checkpoint was created with another version of Ray and provide an informative error message.
3. Catch the exception and offer suggestions for fixing it, like ensuring that the same version of Ray is used, etc.

### Reproduction (REQUIRED)

See above.

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by edoakes** [comment]
This is not currently supported, but we should probably throw a better error (cc @richardliaw)

**Comment by giancds** [comment]
Hi

I think I'm going through a similar error using DQN, pytorch and ray 0.8.6. 

When I try to restore the checkpoint create with version 0.8.5 I get

```
RuntimeError: Error(s) in loading state_dict for FullyConnectedNetwork_as_DQNTorchModel:
	Unexpected key(s) in state_dict: "advantage_module.Q.weight", "advantage_module.Q.bias". 
```

Is it possible to post an example on how you managed to recreate the checkpoint @deanwampler?
