### ISSUE TITLE
[RLlib] Torch export model doesn't work

### ISSUE THREAD

**Issue by bbalaji-ucsd** [ray-project/ray#9164]
### Describe your feature request
https://github.com/ray-project/ray/blob/b7cc1e78d74c5f67b59450708501ce58d29dbfdb/rllib/policy/torch_policy.py#L426 

The torch export model API is not yet implemented. Would really help to have this for saving the model trained in RLlib. Thanks!

**Comment by edoakes** [comment]
@bbalaji-ucsd great suggestion! Would you be willing to make a PR for this?

**Comment by bbalaji-ucsd** [comment]
Apologies, I won't have the bandwidth for this. I'm going to use TF models until this is available.

**Comment by cedros23** [comment]
Hello, 

Is there any update about this issue?
If not, it would be beneficial to give some hints about the potential implementation so that I can give it a try.

Thanks!
