### ISSUE TITLE
[rllib] Allow for a mixture of sampler and InputReader input

### ISSUE THREAD

**Issue by liquidnode** [ray-project/ray#9174]
It seems like the following configuration is invalid:

```
def input_reader():
   #this function returns a rllib.offline.InputReader
config["input"] = {
        "sampler": 0.5,
        input_reader: 0.5
    }
```

It would be nice to skip the creation of json files and directly use a custom InputReader in this scenario.

Also a related question: "sampler" means that in this example 50% of data in the ReplayBuffer comes from the interaction of a continuously updated policy with the environment?

**Comment by cedros23** [comment]
Hello, 

In https://github.com/ray-project/ray/issues/9167 , I was asking a similar question in a long way :) When we use the example above, if sampler works with its own replay buffer, it also updates the priorities and exchanges old experience with the new ones?

**Comment by sven1977** [comment]
It's slightly different @cedros23:
The "sampler" doesn't have a replay buffer. The buffer lives inside the central (e.g. DQN) trainer.
So the buffer is filled each "rollout" with 50% env samples and 50% rows from the input file.
Then, the Trainer takes n samples from this (mixed) buffer and learns.
