### ISSUE TITLE
[tune] Ray-Tune Specifying Results Directory

### ISSUE THREAD

**Issue by leimao** [ray-project/ray#9177]
### What is your question?
The Ray-Tune results seem to be always in the `/ray_results/`. How do I specify the custom directory for Ray-Tune results? Thank you.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.9.0dev
Python 3.6

**Comment by richardliaw** [comment]
@leimao thanks for opening this issue! You can set it via `local_dir` (https://docs.ray.io/en/master/tune/api_docs/logging.html#log-directory)

**Comment by leimao** [comment]
> @leimao thanks for opening this issue! You can set it via `local_dir` (https://docs.ray.io/en/master/tune/api_docs/logging.html#log-directory)

@richardliaw Thank you for the prompt reply.

**Comment by reemagit** [comment]
Can't find anything on how to se the local_dir in the linked page, has there been some update in the documentation?

**Comment by richardliaw** [comment]
@reemagit ah, it must have changed. Here is the new link: https://docs.ray.io/en/releases-1.4.0/tune/user-guide.html?highlight=local_dir#logging

**Comment by reemagit** [comment]
Great, thank you very much.

**Comment by hahahumble** [comment]
Code Example:
```python
tuner = tune.Tuner(
    trainable,
    tune_config=tune.TuneConfig(
        num_samples=10,
    ),
    param_space=config,
    run_config=air.RunConfig(local_dir="./results", name="test_experiment")  # Specify results directory in `local_dir`
)
```

**Comment by hahahumble** [comment]
> 

Reference: https://docs.ray.io/en/latest/tune/tutorials/tune-output.html
