### ISSUE TITLE
[rllib] evaluation reward and training reward inconsistent

### ISSUE THREAD

**Issue by yshao44** [ray-project/ray#9198]
I am kinda new here. I was training a small model and realized that there are some inconsistency between the training episode mean reward and evaluation episode mean reward. In the beginning of the training (after 300k time steps) when the training reward is relatively low and still improving (say 70), the evaluation can achieve a high reward (say 91) even the episode reward max hasn't reached, and at the end of the training when the training reward is quite high (say 97), the evaluation reward is still at the same level (91) without improving. I wonder why these situations occur and whether they are normal. I really appreciate your help.

**Comment by aronium97** [comment]
I was wondering the same thing. 
Might it have something to do with the exploration setting?
