### ISSUE TITLE
[rllib] Efficient hyper-parameter search

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#920]
RLlib should include a utility to search for reasonable hyper-parameters, e.g. via Hyperband: https://arxiv.org/abs/1603.06560 that implements early stopping of un-promising candidates.

cc @richardliaw

**Comment by robertnishihara** [comment]
Should this be RLlib specific? Or should it be general purpose?

**Comment by richardliaw** [comment]
General purpose, but a first version would probably be closely tied to RLLib agent interfaces.

**Comment by ericl** [comment]
I think we can probably aim for something general purpose, but perhaps with some constraints. For example, we might assume the training process is very expensive (minutes to hours), you can get intermediate results, and the number of experiments total in a run isn't too large (at most hundreds to thousands).

When we get into the realm of many fast experiments, that's something other systems e.g. hyperopt will much better at (though as the hyperopt example in the docs show you can still use Ray as the execution backend).

**Comment by ericl** [comment]
Superceded by ray.tune
