### ISSUE TITLE
[docs] Common Workarounds Page for `Pickling`/`Cloudpickle` errors

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#9200]
### What is the problem?

Serialization is one of the most common problems/gotchas for new users in Ray. 

This typically occurs when a user includes non-serializable objects within a Ray function/class. The user will create the function and expect it to work magically with Ray. The error message raised is often also non-interpretable ("Pickling Error failed").

"ray.put/ray.get" calls are actually NOT the main source of errors here.

Three things we need to do to mitigate this issue:
1. Better, actionable, detailed errors. Perhaps link to the documentation.
2. Have a guide for how to address commonly seen/raised exceptions regarding serialization.
3. After errors are improved, add tests in CI to make sure that we don't regress on 1).

cc @suquark @rkooo567

**Comment by rkooo567** [comment]
As fixing error messages is crucial for us now, I will bump up the priority.

**Comment by rkooo567** [comment]
I believe this should've been fixed by https://github.com/ray-project/ray/pull/19691. If you see other uninterpretable error, please create an issue.
