### ISSUE TITLE
[rllib] RNN support for off-policy algorithms

### ISSUE THREAD

**Issue by iamhatesz** [ray-project/ray#9206]
### Describe your feature request

I propose to use this issue to discuss about work packages that have to be done to provide support for recurrent neural networks in off-policy algorithms (DQN, DDPG, SAC).

Up till now, I have found following existing tickets regarding this topic (please add more if I missed some):
* https://github.com/ray-project/ray/issues/3148 (R2D2 concept)
* https://github.com/ray-project/ray/issues/8627 (request for implementation, some initial investigation)
* https://github.com/ray-project/ray/issues/8213 (request for graceful check whether a given algorithm support RNNs or not)
* https://github.com/ray-project/ray/issues/6078 (request for implementation)

I propose to start with a simple DRQN (thus without R2D2 tricks, just sum/average/max TD-error on a trajectory (sequence of steps)), then extend ApeX DQN and DDPG with R2D2 improvements, then finally extend RNN support in SAC (probably with the similar R2D2 concepts). 

I've already implemented R2D2 on my own in the past, and I am fine spending a few days on it trying to implement this in RLlib, but I'd appreciate your initial support and tips how to start. I'd like to start with my first question: is storing sequences in a replay memory currently supported?

**Comment by juliusfrost** [comment]
Hi, I am also interested in this request and am able to help with implementation. Would love to see progress on this!
