### ISSUE TITLE
[rllib] Get rid of opencv2

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#922]
It often causes problems during installation on Linux. Also on Jenkins recently, see https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/1759/console.

**Comment by robertnishihara** [comment]
The Jenkins problems are fixed by #926, but we should really just get rid of `opencv-python`. It's too heavy of a dependency.

**Comment by richardliaw** [comment]
I think we can close this for now, given the relative lack of issue it has caused us (and can open later if issues arise again).

**Comment by robertnishihara** [comment]
Are you sure about that? Every time I do a `pip install opencv-python` and try to use Ray I immediately get the error in #923 and I have to downgrade it. Actually I've been meaning to change `setup.py` so that `pip install[rllib]` gets the right version of `opencv-python`.

**Comment by richardliaw** [comment]
I see; I was unaware of that. It would be very helpful if there was an issue to describe that particular problem and how to reproduce it. After all, Insights show that #923 is our most frequently visited page (by far).

Regardless, getting rid of `opencv-python` means we need some alternative (like PIL) to do image rescaling (not numpy, which I think is a lot slower than opencv). PIL might introduce it's own set of problems.

**Comment by RaviSolanki01** [comment]
thank you.

**Comment by arduinepo** [comment]
Sorry for digging, but I've been facing these last few dayq the same conflict dependencies between cv2 and Ray : the trouble with PIL is, it's much, much slower than cv... I even wonder if PIL running in parallel with Ray is faster than cv. running cv with Ray would be great
