### ISSUE TITLE
[Dashboard] Logical view broken when I create / delete actors.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9229]
### What is the problem?

Dashboard logical view shows more than required number of actors when I keep creating / deleting actors.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Open the logical view and don't renew the page. After the script is done, you can see there are more than 10 actors (which we created) from the logical view. Once you renew the page, it shows the correct number.

```python3
import ray
import time

ray.init()
time.sleep(5) # open your dashboard

@ray.remote
class A:
    pass

for _ in range(5):
    a = A.remote()
    b = A.remote()
    del a
    del b

time.sleep(50)
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @mfitton

**Comment by mfitton** [comment]
@rkooo567 when I run your example, it shows 10 dead actor entries. Is that what it shows for you?
For some reason, when I refresh the page, it then only shows 6 dead actor entries.

**Comment by mfitton** [comment]
I'm going to try again and see if I can recreate the case where there are more than 10 entries.

**Comment by mfitton** [comment]
I'm able to reproduce the 10 dead actor entries -> refresh -> 6 dead actor entries every time actually.

**Comment by mfitton** [comment]
Sang helped me reproduce. Looking into the root cause.

**Comment by mfitton** [comment]
Please see explanation and fix here: https://github.com/ray-project/ray/pull/9959
