### ISSUE TITLE
Jenkins test failure: ImportError: libSM.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#923]
The following error has been occurring in the Jenkins tests. For example in https://amplab.cs.berkeley.edu/jenkins/job/Ray-PRB/1761/console.

```
+ docker run --shm-size=10G --memory=10G b89dd0880131c728bc0c693bd4c00759c6e0e77ef6e182c457304ada4a01f293 python /ray/python/ray/rllib/train.py --env PongDeterministic-v0 --alg A3C --num-iterations 2 --config '{"num_workers": 16}'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/ray/python/ray/rllib/train.py", line 15, in <module>
    import ray.rllib.dqn as dqn
  File "/opt/conda/lib/python2.7/site-packages/ray-0.2.0-py2.7-linux-x86_64.egg/ray/rllib/dqn/__init__.py", line 5, in <module>
    from ray.rllib.dqn.dqn import DQNAgent, DEFAULT_CONFIG
  File "/opt/conda/lib/python2.7/site-packages/ray-0.2.0-py2.7-linux-x86_64.egg/ray/rllib/dqn/dqn.py", line 15, in <module>
    from ray.rllib.dqn.common.atari_wrappers_deprecated \
  File "/opt/conda/lib/python2.7/site-packages/ray-0.2.0-py2.7-linux-x86_64.egg/ray/rllib/dqn/common/atari_wrappers_deprecated.py", line 5, in <module>
    import cv2
  File "/opt/conda/lib/python2.7/site-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
Build step 'Execute shell' marked build as failure
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/1761/
Test FAILed.
Finished: FAILURE
```

cc @ericl @pcmoritz any idea where this was introduced? It looks like new `opencv-python` wheels were uploaded today https://pypi.python.org/pypi/opencv-python/3.3.0.10. Maybe that is the problem.

**Comment by pcmoritz** [comment]
this is a duplicate of https://github.com/ray-project/ray/issues/922

My guess is that the version of opencv2 is different now or something related.

**Comment by robertnishihara** [comment]
Fixed by #926.

**Comment by benliu91** [comment]
see https://github.com/conda/conda/issues/1051

**Comment by richardliaw** [comment]
Got this issue in Docker when installing `opencv-python`; fixed it with 
`apt update && apt install -y libsm6 libxext6 libxrender-dev`

**Comment by nabeelpredmac** [comment]
same issue solved by
with root user 
apt update && apt install -y libsm6 libxext6 libxrender-dev

**Comment by AyazSaiyed** [comment]
> Got this issue in Docker when installing `opencv-python`; fixed it with
> `apt update && apt install -y libsm6 libxext6 libxrender-dev`

This Worked for me while getting these error     ** import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 3, in <module>**
