### ISSUE TITLE
Fine Tuning Hyperparameters (Ray - Tune): TypeError: 'SGD' object is not iterable

### ISSUE THREAD

**Issue by BilalKacel** [ray-project/ray#9249]
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.8.6
Python version: 3.6.9
Torch version: 1.5.1+cu101
Platform: Google Colab

**Contexte:**
I'm working on a Sequence Tagging with Pytorch through a Bi-LSTM architecture.
Everything works well.
I'd like to fine tune the Hyperparameters using TUNE module of Ray in order to get the best values.
I got an error and I didn't find a solution about it.

**Code**:
import numpy as np
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

from ray import tune

def train_bilstm(config):
    
    model = BrownTagger(embedding_dim=EMBEDDING_DIM, hidden_dim=HIDDEN_DIM, vocab_size=VOCAB_SIZE, tagset_size=TAGSET_SIZE
              , num_layers=NUM_LAYERS
              , batch_size=BATCH_SIZE
              , bidirectional=BIDRECTIONAL
              , dropout=DROPOUT
              , debug_mode=DEBUG_MODE
            )
    
    model.to(DEVICE)
    
    train_loader, test_loader = train_dataloader, test_dataloader
    
    optimizer = optim.SGD(
        model.parameters(), 
        lr=config["lr"])
    
    for i in range(10):
        train(model, train_loader, optimizer)
        acc = evaluate(model, test_loader)
        tune.track.log(mean_accuracy=acc)
        if i % 5 == 0:
            # This saves the model to the trial directory
            torch.save(model, "./model.pth")

search_space = {
    "lr": tune.choice([0.001, 0.01, 0.1])
}

analysis = tune.run(train_bilstm, config=search_space, resources_per_trial={'gpu': 1})

### What is the problem?
When I run the code just above, I got the following detailed messages.
The error you can find at the end is: **_TypeError: 'SGD' object is not iterable_**

2020-07-01 15:42:45,589	ERROR logger.py:196 -- pip install 'ray[tune]' to see TensorBoard files.
2020-07-01 15:42:45,590	WARNING logger.py:328 -- Could not instantiate TBXLogger: No module named 'tensorboardX'.
2020-07-01 15:42:46,856	WARNING worker.py:1047 -- Warning: The actor ImplicitFunc has size 14818976 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
2020-07-01 15:42:46,876	WARNING util.py:137 -- The `start_trial` operation took 1.2884998321533203 seconds to complete, which may be a performance bottleneck.
== Status ==
Memory usage on this node: 6.3/12.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 1/2 CPUs, 1/1 GPUs, 0.0/7.08 GiB heap, 0.0/2.44 GiB objects
Result logdir: /root/ray_results/train_bilstm
Number of trials: 1 (1 RUNNING)
Trial name	status	loc	lr
train_bilstm_81e89_00000	RUNNING		0.01

(pid=1805) 2020-07-01 15:42:50,015	ERROR function_runner.py:115 -- Runner Thread raised error.
(pid=1805) Traceback (most recent call last):
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 109, in run
(pid=1805)     self._entrypoint()
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 163, in entrypoint
(pid=1805)     return self._trainable_func(config, self._status_reporter)
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 273, in _trainable_func
(pid=1805)     output = train_func(config)
(pid=1805)   File "<ipython-input-75-7641c0b73580>", line 32, in train_bilstm
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/examples/mnist_pytorch.py", line 38, in train
(pid=1805)     for batch_idx, (data, target) in enumerate(train_loader):
(pid=1805) TypeError: 'SGD' object is not iterable
(pid=1805) Exception in thread Thread-1:
(pid=1805) Traceback (most recent call last):
(pid=1805)   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
(pid=1805)     self.run()
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 128, in run
(pid=1805)     raise e
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 109, in run
(pid=1805)     self._entrypoint()
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 163, in entrypoint
(pid=1805)     return self._trainable_func(config, self._status_reporter)
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 273, in _trainable_func
(pid=1805)     output = train_func(config)
(pid=1805)   File "<ipython-input-75-7641c0b73580>", line 32, in train_bilstm
(pid=1805)   File "/usr/local/lib/python3.6/dist-packages/ray/tune/examples/mnist_pytorch.py", line 38, in train
(pid=1805)     for batch_idx, (data, target) in enumerate(train_loader):
(pid=1805) TypeError: 'SGD' object is not iterable
(pid=1805) 
2020-07-01 15:42:54,204	INFO (unknown file):0 -- gc.collect() freed 206517 refs in 1.5711514619997615 seconds
2020-07-01 15:42:55,204	ERROR worker.py:987 -- Possible unhandled error from worker: ray::ImplicitFunc.train() (pid=1805, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 217, in _train
    self._report_thread_runner_error(block=True)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 262, in _report_thread_runner_error
    .format(err_tb_str)))
ray.tune.error.TuneError: Trial raised an exception. Traceback:
ray::ImplicitFunc.train() (pid=1805, ip=172.28.0.2)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 109, in run
    self._entrypoint()
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 163, in entrypoint
    return self._trainable_func(config, self._status_reporter)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py", line 273, in _trainable_func
    output = train_func(config)
  File "<ipython-input-75-7641c0b73580>", line 32, in train_bilstm
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/examples/mnist_pytorch.py", line 38, in train
    for batch_idx, (data, target) in enumerate(train_loader):
TypeError: 'SGD' object is not iterable

**Comment by richardliaw** [comment]
`train` is a helper function, and here is the signature:

```
def train(model, optimizer, train_loader, device=None):
```
Note that optimizer is the second argument, while in yours:
```
train(model, train_loader, optimizer)
```
I think the arguments are flipped in your usage. Hope that helps!

**Comment by BilalKacel** [comment]
Hi @richardliaw 

Thanks a lot.
Indeed, it was not correct.
What about the signature of 'test()' ?

Thank you again,
BKL

**Comment by richardliaw** [comment]
here: 
```
def test(model, data_loader, device=None)
```

**Comment by BilalKacel** [comment]
Perfect. 
Thank you.

@richardliaw : 
- You can close the issue.
- Another question: is there a way to make the execution more verbose ?

**Comment by richardliaw** [comment]
More verbose? hmm what exactly are you trying to see?

**Comment by BilalKacel** [comment]
I mean, when I run the small part of code to get the best hyperparameters, I take, more and less, a lot of time ... in this case, I just want to see more information about the intermediate combinations

**Comment by richardliaw** [comment]
`tune.run(verbose=2)`?

**Comment by BilalKacel** [comment]
All right !!!
Thanks. That's it.

**Comment by richardliaw** [comment]
great!
