### ISSUE TITLE
Relation between training_batch_size/ rollout_fragment_length and number of workers for assessing the scalability of RL algorithms

### ISSUE THREAD

**Issue by surajp92** [ray-project/ray#9250]
[rllib]

I want to assess the scalability of my training with APPO algorithm on 32,64,128 cores/CPUs. As per my understanding, in distributed reinforcement learning, the environment is run in parallel in a distributed manner, and then then the batches of training samples are collected. The neural network is then trained using this data. The documentation says "Sample batches of this size (`rollout_fragment_length`) are collected from rollout workers and combined into a larger batch of `train_batch_size` for learning."

My question is whether the `rollout_fragment_length` affects the training significantly or not? For example, if `rollout_fragment_length` is 20 and I am using 32 workers, then 640 (32*20) samples will be collected for training the neural network. With the same `rollout_fragment_length` and 128 workers, it will be 2560 (128*20) samples. Shall I use the same sample batch size (`rollout_fragment_length`) irrespective of the number of workers, or do I need to change the sample batch size as I increase the number of workers?

Thank you. 

*Ray 0.7.6, Python 3.6.8, Tensorflow 1.14.0, Numpy 1.16.1*

**Comment by ericl** [comment]
It shouldn't matter too much here, basically you want to set it small enough so that the train batch isn't bigger than expected due to multiple workers, but not too small since VF bootstrapping is done at rollout fragment boundaries. Also setting it too small adds system overhead.

**Comment by surajp92** [comment]
Thank you.
