### ISSUE TITLE
Ray Local Mode Version

### ISSUE THREAD

**Issue by ksettaluri6** [ray-project/ray#9254]
I currently need the capability to run Ray locally without Redis, and I found a particular commit that appears to do this (https://github.com/ray-project/ray/pull/2795). I have Ray set up on a remote machine, where I do not have sudo, and attempted to install the latest snapshot using the command: 

`pip install -U ray-0.9.0.dev0-cp35-cp35m-manylinux1_x86_64.whl`

The files on here, however, don't have the modifications to run local mode. Could you point me to the particular wheel that has this? Is the only way to get the update to build from source? 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python: 3.5.6
Tensorflow: 1.10.1 (This is the only version of TF that currently works on the remote machine)
OS: x86_64 GNU/Linux

**Comment by richardliaw** [comment]
#2795 is quite old - I think `ray.init(local_mode=True)` should work out of the box now on the snapshot you posted! If not, can you post a stack trace?

**Comment by ksettaluri6** [comment]
Ah I see, the new version of Ray I have installed from the wheel: 0.9.0.dev0. This is the error that I get:

`In [1]: import ray

In [2]: ray.init(local_mode=True)
2020-07-01 12:19:57,334	INFO resource_spec.py:221 -- Starting Ray with 3.22 GiB memory available for workers and up to 1.62 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-932fd16fa4af> in <module>()
----> 1 ray.init(local_mode=True)

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/worker.py in init(address, redis_address, redis_port, num_cpus, num_gpus, memory, object_store_memory, resources, driver_object_store_memory, redis_max_memory, log_to_driver, node_ip_address, object_id_seed, local_mode, redirect_worker_output, redirect_output, ignore_reinit_error, num_redis_shards, redis_max_clients, redis_password, plasma_directory, huge_pages, include_java, include_dashboard, dashboard_host, dashboard_port, job_id, configure_logging, logging_level, logging_format, plasma_store_socket_name, raylet_socket_name, temp_dir, load_code_from_local, java_worker_options, use_pickle, _internal_config, lru_evict)
    725             shutdown_at_exit=False,
    726             spawn_reaper=True,
--> 727             ray_params=ray_params)
    728     else:
    729         # In this case, we are connecting to an existing cluster.

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/node.py in __init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    182         # Start processes.
    183         if head:
--> 184             self.start_head_processes()
    185             redis_client = self.create_redis_client()
    186             redis_client.set("session_name", self.session_name)

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/node.py in start_head_processes(self)
    730         assert self._redis_address is None
    731         # If this is the head node, start the relevant head node processes.
--> 732         self.start_redis()
    733 
    734         self.start_gcs_server()

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/node.py in start_redis(self)
    514              password=self._ray_params.redis_password,
    515              include_java=self._ray_params.include_java,
--> 516              fate_share=self.kernel_fate_share)
    517         assert (
    518             ray_constants.PROCESS_TYPE_REDIS_SERVER not in self.all_processes)

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/services.py in start_redis(node_ip_address, redirect_files, resource_spec, port, redis_shard_ports, num_redis_shards, redis_max_clients, redirect_worker_output, password, use_credis, include_java, fate_share)
    777         stdout_file=redis_stdout_file,
    778         stderr_file=redis_stderr_file,
--> 779         fate_share=fate_share)
    780     processes.append(p)
    781     redis_address = address(node_ip_address, port)

/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/services.py in _start_redis_instance(executable, modules, port, redis_max_clients, num_retries, stdout_file, stderr_file, password, redis_max_memory, fate_share)
    962                                stdout_file.name if stdout_file is not None else
    963                                "<stdout>", stderr_file.name
--> 964                                if stdout_file is not None else "<stderr>"))
    965 
    966     # Create a Redis client just for configuring Redis.

RuntimeError: Couldn't start Redis. Check log files: /tmp/ray/session_2020-07-01_12-19-57_328632_15067/logs/redis.out /tmp/ray/session_2020-07-01_12-19-57_328632_15067/logs/redis.err
`
I also get a syntax problem when I try to run Ray as well, without the local_mode flag:
`  File "/prj/mlsoc2/conda/users/ksettalu/envs/circuitenv/lib/python3.5/site-packages/ray/rllib/evaluation/episode.py", line 55
    self.new_batch_builder: Callable[
                          ^
SyntaxError: invalid syntax
`
I'm assuming this is due to my Python version, with type casting? But I'm not too sure.

**Comment by richardliaw** [comment]
@ijrsvt is there a reason why we need redis for local mode?

**Comment by ksettaluri6** [comment]
Is there any reason why I don't see the local_mode updates in the files that I have locally? (i.e https://github.com/ray-project/ray/pull/4138/files, and looking at those files on my version of Ray, and those updates don't exist)

**Comment by richardliaw** [comment]
hmm really? that looks odd.. can you compare your files to master?

**Comment by ksettaluri6** [comment]
Ah so I think I know the problem. I think my ray[rllib] is not updated, as the local_mode options for Ray tune I can see on my end, but not the file changes for rllib. The commands I used for rllib were: 
`pip install -U ray-0.9.0.dev0-cp35-cp35m-manylinux1_x86_64.whl`

And upon running this, I was told to re-install rllib as I had the wrong version, with
`pip install -U ray[rllib]`

Is there a version I should be pointing to with ray[rllib]?

**Comment by ksettaluri6** [comment]
Hmm I think that ray[rllib] is fine actually, the only file that is not updated upon checking both local mode file updates for ray and tune is: python/ray/experimental/internal_kv.py from https://github.com/ray-project/ray/pull/2795/files.

**Comment by ksettaluri6** [comment]
One other note, in ray/worker.py, when I set the local flag to true, self.mode is None when I run the code. This should be set to LOCAL_MODE if the flag is being set correctly?

**Comment by ksettaluri6** [comment]
Also might be useful to state what feature I want: due to security issues, I need to make sure everything in Ray runs locally without using Redis or external packages that might store data externally. I figured local_mode was the way to do this, though it seems like it also makes everything run sequentially?

**Comment by richardliaw** [comment]
RE: code from master; can you try pip uninstalling ray a couple times, and making sure the code you're accessing is no longer there? It sounds like you might have multiple ray installations lying around. 

RE: Ray + Redis; redis shouldn't be storing data externally - it's an in-memory storage. Unfortunately, Ray depends on Redis to coordinate its parallelism. 

Are you worried that Redis is insecure? Or is it that you simply can't use redis?

**Comment by ksettaluri6** [comment]
Mostly worried about Redis being insecure. I am currently at a company that does not allow any external storage of data, or anything being put on the cloud. I've never used Redis before, and have used default Ray settings in the past. Could you point me to any resources about how exactly Ray uses Redis? I have been going through the manual.

**Comment by richardliaw** [comment]
https://ray.io/whitepaper will help!
