### ISSUE TITLE
Reported KL divergence negative in PPO [rllib]

### ISSUE THREAD

**Issue by houcharlie** [ray-project/ray#9261]
### What is the problem?
Is it possible for reported KL values in PPO to be negative?
![Screen Shot 2020-07-01 at 8 24 19 PM](https://user-images.githubusercontent.com/15848908/86303118-da6b0c00-bbd8-11ea-98d4-59cd601ad26b.png)
I thought that the reported number was supposed to be the expectation over states of the KL-divergences of the action probabilities at each state.  So it shouldn't be negative, right?
*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.5

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Unsure what causes such low KL divergences, since this is supposed to mean that the strategy is changing very little between iterations; other environments I've tried within PPO examples don't seem to have this issue.  

However, reported relative frequency (e.g. # of times agent chose this action divided by the total # of steps) of a particular action being chosen isn't staying constant despite the KL divergence staying low.
![Screen Shot 2020-07-01 at 8 28 53 PM](https://user-images.githubusercontent.com/15848908/86303319-801e7b00-bbd9-11ea-8586-ab6e9967d279.png)

If it helps, you can clone the repo I've been using here https://github.com/wuwuz/SquirRL/tree/master/MultiAgent

And you can run it with `python3 bitcoin_game.py --alphas .3875 --OSM 1 --workers (your workers setting) --players 2 --save_path none`

Edit: Is there perhaps something funky going on with np.inf's?  I implemented a parametric action space, following the example https://github.com/ray-project/ray/blob/e0d8b58969728054d1800abc925aa5352882baa8/rllib/examples/models/parametric_actions_model.py#L16

**Comment by houcharlie** [comment]
Is there perhaps something funky going on with np.inf's?  I implemented a parametric action space, following the example https://github.com/ray-project/ray/blob/e0d8b58969728054d1800abc925aa5352882baa8/rllib/examples/models/parametric_actions_model.py#L16

**Comment by rkooo567** [comment]
Continuous distribution can provide negative entropy. 

cc @ericl

**Comment by houcharlie** [comment]
(1) Sorry, I should've mentioned that the action space I used is discrete, so that shouldn't be a concern.
(2) Differential entropy can be negative, but differential KL divergence cannot be negative.  Check out the [proof](https://en.wikipedia.org/wiki/Gibbs%27_inequality) (under the "alternative proofs" section).  This proof is also valid for continuous distributions.
