### ISSUE TITLE
Unable to run multiple instances of Ray at once on Windows kernel

### ISSUE THREAD

**Issue by mehrdadn** [ray-project/ray#9265]
Running multiple instances of Ray simultaneously fails on Windows due to a Redis error, but completes successfully on other platforms. A repro for this is running two tests at once:
```
import subprocess, sys
procs = [
	subprocess.Popen([sys.executable, "../rllib/tests/test_exec_api.py"]),
	subprocess.Popen([sys.executable, "../rllib/tests/test_catalog.py"]),
]
[proc.communicate() for proc in procs]
```

This fails on WSL as well (though not entirely in the same way). This is likely caused by differing socket behavior on the Windows kernel (e.g. see the [different `SO_REUSEADDR` behavior on Windows](https://stackoverflow.com/a/14388707)). We should probably find a different solution that works on Windows.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mehrdadn** [comment]
#9114

**Comment by czgdp1807** [comment]
I am able to reproduce the error in a conda environment on Windows. Below is the exact error generated in logs,

```bash
[2021-09-21 10:23:34,841 C 5640 8024] service_based_gcs_client.cc:74:  Check failed: GetGcsServerAddressFromRedis( redis_client_->GetPrimaryContext()->sync_context(), &current_gcs_server_address_, RayConfig::instance().gcs_service_connect_retries()) Failed to get gcs server address when init gcs client.
*** StackTrace Information ***
```
