### ISSUE TITLE
[GCS Actor Management] Removing actor as soon as it creates them doesn't work as expected.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9267]
### What is the problem?

If you remove your actors as soon as you create them, it should be properly killed. That means the dashboard should show that both of actors are in dead states. 

```python3
import ray
ray.init()

@ray.remote
class A:
    pass

a = A.remote()
b = A.remote()

del a
del b
import time
time.sleep(100)
```
This example should show both `a` and `b` are in DEAD state in the dashboard. It works as expected when GCS actor management is turned off.

But if it is on, you can see both of actors are still alive in the dashboard.

Another example is this.
```python3
import ray
ray.init()

@ray.remote
class A:
    pass

a = A.remote()
b = A.remote()

ray.kill(a)
ray.kill(b)
import time
time.sleep(100)
```
You can also see if the gcs actor management is off, both of actors are killed from the dashboard.

But, if you create turn this on, you can see only one of actors are reported as DEAD state. The other actor wasn't even created.

**Comment by rkooo567** [comment]
This must be the race condition.

**Comment by ffbin** [comment]
![image](https://user-images.githubusercontent.com/13081808/86467066-4e3b1f00-bd67-11ea-8dd7-d87a95de4065.png)
@rkooo567 I can not reproduce the problem.
