### ISSUE TITLE
[tune] Parameters from `tune.choice()` do not get logged to TensorBoard when integers

### ISSUE THREAD

**Issue by dcfidalgo** [ray-project/ray#9268]
### What is the problem?
When providing parameters via `tune.choice()` that include integers, the values are not logged to TensorBoard's HPARAMS section. 
The issue is that `numpy.random.choice([1, 2, 3])` (for example) returns `numpy.int32`/`numpy.int64` and those types are not included in the `VALID_HPARAMS = (str, bool, int, float, list)` tuple (python/ray/tune/logger.py). 
Since TensorBoard has no issues with logging `numpy.int32/64`, one simple solution would be to just include those types in the tuple above. Happy to provide a PR if you think this is the way to go.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray: 0.8.6
python: 3.7.7
tensorboard: 2.2.2
ubuntu: 20.04

### Reproduction (REQUIRED)
```python
from ray import tune

def trainable(config):
    tune.report(score=config["a"])

config_dict = {"a": tune.choice([1, 2, 3])}

tune.run(trainable, config=config_dict, num_samples=1)
```
- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
yes! that'd be great - could you push a PR and ping me?

**Comment by richardliaw** [comment]
Thanks a bunch for making this PR!
