### ISSUE TITLE
[rllib] What is the concret difference between "batch_mode": "truncate_episodes" or "complete_episodes"?

### ISSUE THREAD

**Issue by klausk55** [ray-project/ray#9270]
For example, for DQN optimizer "rollout_fragment_length": 4 and my maximally possible episode length is 32.

What is the concret difference on sample batches if I use "batch_mode": "truncate_episodes" or "complete_episodes"?

**Comment by sven1977** [comment]
Hey @klausk55, thanks for filing this question. For questions like this, you can also use our slack channel (https://docs.google.com/forms/d/e/1FAIpQLSfAcoiLCHOguOm8e7Jnn-JJdZaCxPGjgVCvFijHB5PLaQLeig/viewform).

"truncate_episodes": There could be more than one episodes in the train_batch (a SampleBatch instance). The last episode in the batch might be truncated (ended by a `done` = False).
"complete_episodes": There are always only completed episodes in the train_batch (a SampleBatch instance). All trajectories found in the batch must end with a `done` = True.

Closing this issue.

**Comment by klausk55** [comment]
Thanks for your response @sven1977, but I am still not fully clear and next time I will change to the slack channel.

Please correct me if I am wrong:
Say `train_batch_size` is 32, then we train on batches which are all concatenated of 8 rollout_fragments (where `rollout_fragment_length=4`).

If an episode early ends after, e.g., 7 steps and there are two fragments (with length 4 resp. 3).
What then happens if `"batch_mode": "truncate_episodes"`? Will the second fragment be "filled up" with one step from the succeeding episode?

**Comment by sven1977** [comment]
Correct:
```
Say train_batch_size is 32, then we train on batches which are all concatenated of 8 rollout_fragments (where rollout_fragment_length=4).
```

Also correct: If batch_mode=truncate_episodes, the batches generated by one RolloutWorker always have the rollout_fragment_length size! Not more and not less. It doesn't matter, whether some fragments end without an episode being done (hence "truncate_episodes").
```
If an episode early ends after, e.g., 7 steps and there are two fragments (with length 4 resp. 3).
What then happens if "batch_mode": "truncate_episodes"? Will the second fragment be "filled up" with one step from the succeeding episode?
```
