### ISSUE TITLE
Worker memory limit ineffective in ray

### ISSUE THREAD

**Issue by cyber42** [ray-project/ray#9273]
I'm relatively new to ray. I run a large pandas based numerical optimization on ray 0.8.6, Python 3.7.6 (default, Feb 26 2020, 20:54:15) with [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on Amazon Linux 2. I'm also using joblib 0.13.2 as a cache for the data needed on the workers with a memmap on `/dev/shm`. My hardware is an r5d.metal instance on EC2 with 96 cores and 768 GB of RAM.

The optimization works fine for approximately 800000 calls to ray (in batches of 64 remotes being calculated), but gradually uses more and more memory on the workers, despite limiting memory in `ray.init()` and regularly calling `gc.collect()` on the workers. When all RAM is consumed I get:
```
/home/user/src/project/loadersonray.py in raymap(f_partial, args)
   3238             
   3239             # Get the results
-> 3240             results = ray.get(result_ids)
   3241             
   3242             

~/environments/amazon_2_python3.7/lib64/python3.7/site-packages/ray/worker.py in get(object_ids, timeout)
   1472                     worker.core_worker.dump_object_store_memory_usage()
   1473                 if isinstance(value, RayTaskError):
-> 1474                     raise value.as_instanceof_cause()
   1475                 else:
   1476                     raise value

RayTaskError(RayOutOfMemoryError): ray::__main__.evaluate_fs() (pid=13531, ip=172.32.27.190)
  File "python/ray/_raylet.pyx", line 408, in ray._raylet.execute_task
  File "/root/environments/amazon_2_python3.7/lib64/python3.7/site-packages/ray/memory_monitor.py", line 128, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node ip-172-32-27-190.us-east-2.compute.internal is used (717.87 / 755.57 GB). The top 10 memory consumers are:

PID     MEM     COMMAND
13523   8.7GiB  ray::__main__.evaluate_fs()
13510   8.48GiB ray::__main__.evaluate_fs()
13509   8.4GiB  ray::__main__.evaluate_fs()
13504   8.37GiB ray::__main__.evaluate_fs()
13484   8.35GiB ray::__main__.evaluate_fs()
13486   8.33GiB ray::__main__.evaluate_fs()
13485   8.32GiB ray::__main__.evaluate_fs()
13487   8.32GiB ray::__main__.evaluate_fs()
13533   8.31GiB ray::__main__.evaluate_fs()
13565   8.3GiB  ray::__main__.evaluate_fs()

In addition, up to 129.79 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---

```

`ray.available_resources()` returns:
```
{'memory': 61.0,
 'CPU': 96.0,
 'object_store_memory': 1413.0,
 'node:172.32.27.190': 1.0}
```

joblib cache uses 91GB of memory in /dev/shm.

I initialize the whole optimization once in the beginning using:
```
ray.init(
    object_store_memory=100*1024*1024*1024,  # plasma
    # Please note that relying on this is not recommended - instead, if possible you should try to remove references as they’re no longer needed in your application to free space in the object store:
    lru_evict=True,
    include_webui=True,
    # Works per worker?
    memory=3*1024*1024*1024,  # The amount of memory (in bytes) that is available for use by workers requesting memory resources. By default, this is automatically set based on available system memory.
)
```

Both plasma and the workers use up more RAM then expected, although the real problem seems to be the workers reaching approximately 96 x 8GB.

Is this a bug or it is expected to some extent? Do you have suggestions for smart ways to analyse the issue further?

**Comment by ericl** [comment]
My best guess is it's some kind of Python memory leak (might not be Ray related). Or it could be some internal data structure leaking in Ray. Is it possible to create a minimal reproduction script that causes say 1 worker's memory to continually increase when it shouldn't?

**Comment by ericl** [comment]
Btw, I would consider removing those Ray flags you have set. The recommendation is to use just `ray.init()` and not set any of those other parameters.
