### ISSUE TITLE
[autoscaler] Option in `ray up` to wait until all (or some) worker nodes have been synced

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#9277]
### Describe your feature request

`ray up` currently waits until the head node is fully setup, but the worker nodes may not be. This can be a bit annoying to work with when either a job requires a certain number of nodes to run. I think it can also lead to inconsistencies when a subsequent `ray up` command leads to a concurrent `rsync` to the worker nodes.

It'd be nice to be able to wait until all of the worker nodes are set up. I'm not sure of the best interface, since the number of worker nodes could be variable. Maybe just something like `ray up --wait-for N`?

**Comment by stephanie-wang** [comment]
@ericl, what do you think?

cc @pcmoritz

**Comment by ericl** [comment]
I think in the future this is solved with placement groups, i.e., the placement group won't be scheduled until the cluster is up. Will that work out?

Btw, file sync is not an issue, since the head node manages consistent replication of the file mounts.

**Comment by stephanie-wang** [comment]
Oh I see, I didn't realize that the file syncing was consistent. I was thinking of a dev setup where the head node recompiles the ray binaries and rsyncs to the worker nodes. But it seems like this should work then?

**Comment by ericl** [comment]
Yeah, in this case if the hash of the head files changes, any workers not up to date will get the new files and will be restarted. Though, there might be a brief period of time in which some workers are running the old Ray.

**Comment by stephanie-wang** [comment]
Okay cool, I think that should work for my use case then.
