### ISSUE TITLE
[autoscaler]  how to set `ssh_user` if `worker_ips` usernames are all different each other?

### ISSUE THREAD

**Issue by rightx2** [ray-project/ray#9288]
In local configuration, It looks like `ssh_user`  in `configuration.yaml` should be set as the user of `head_node`, right?

But what if the `worker_node`'s username is different with `head_node`, say head_node's user name is `user1` and `worker_node`'s is `user2`? How does `head_node` find out worker's username when connecting via ssh?

When the nodes are connected within the same networks(192.168.1.x) and I submitted some jobs to the head node, only head node worked hard and nothing happened in workers.

In this situation, should I run ray manually in each worker?  like `ray start --address=<address>` ?

**Comment by richardliaw** [comment]
Yep! In this situation, starting ray manually is the way to go.

**Comment by rightx2** [comment]
@richardliaw  Thanks. I've solved the problem.
