### ISSUE TITLE
[autoscaler] how many ports should I open for using ray? 

### ISSUE THREAD

**Issue by rightx2** [ray-project/ray#9298]
I'm trying to use ray cluster in local scaling mode.

Nodes are connected in same network, but they use firewall so only port 22 is open each other.

Since ray uses 6379 port for redis, I exclude that port from firewall but it still doesn't work.

After I checked `ray start`'s usage, I found out some ports it uses:

```
  --redis-shard-ports TEXT        the port to use for the Redis shards other
                                  than the primary Redis shard
  --object-manager-port INTEGER   the port to use for starting the object
                                  manager
  --node-manager-port INTEGER     the port to use for starting the node
                                  manager
  --min-worker-port INTEGER       the lowest port number that workers will
                                  bind on. If not set, random ports will be
                                  chosen.
  --max-worker-port INTEGER       the highest port number that workers will
                                  bind on. If set, '--min-worker-port' must
                                  also be set.
```

In this case, should I specify all these port with specific numbers and exclude them from the firewall?

**Comment by rkooo567** [comment]
cc @edoakes

**Comment by rkooo567** [comment]
As of Ray 0.8.7, you should open

```
--port # only for head node
--redis-shard-ports # only for head node
-- object-manager-port
--node-manager-port
--min-worker-port
--max-worker-port # Note that from min-worker-port ~ max-worker-port should be all open
--gcs-server-port # only for head node
```

I will keep it updated as soon as I find new ones.

**Comment by manishagarwal23** [comment]
How to get what all ports should i open.
Also does these ports change once i restart ray ?

**Comment by rkooo567** [comment]
All of values above are port numbers that can be specified by ray start. Once you specify, I believe port numbers won’t be changed
