### ISSUE TITLE
Current PopulationBasedTraining scheduler let trials mutate asynchronously, cause unfairly comparison between differenet trial iters

### ISSUE THREAD

**Issue by Haijunlv** [ray-project/ray#9301]
### Describe your feature request

environment: ray[tune] == 0.8.4
issue:
    Current PopulationBasedTraining scheduler let trials mutate asynchronously.
    When resources is limited, some trails will have to wait for the resource, then hyperparameters will have to mutate between different trial iters.  
     For examples, trial TrainableAutoAug_00005 have to wait for resources,  then when trial TrainableAutoAug_00005 starts to train, probably it will always get other trails hyperparameters, which is unfairly.
    Does PopulationBasedTraining support trial sync mutation mode? I think this sync mode is more reasonable.

![image](https://user-images.githubusercontent.com/28926237/86504734-0cee5200-bdef-11ea-9410-817018a1a723.png)

**Comment by richardliaw** [comment]
@Haijunlv hey sorry for the slow reply; I think we should support this. Would you be willing to push a PR?

**Comment by amogkam** [comment]
Hi @Haijunlv, we just added a synchronous mode for PBT in Ray 1.0! Give it a try; it makes sure that perturbations only occur after all trials are synced at the same epoch so mutations are happening fairly.
