### ISSUE TITLE
[webui] Catapult timeline offset should not be zero if tasks are filtered.

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#931]
Currently if you filter the tasks, e.g. between "45s -> 60s", the catapult timeline timestamps will start from "0s" again. This is confusing when you are shifting between different time offsets, hopefully there is a way to get it to start from the right offset ("45s" in this case).

**Comment by ericl** [comment]
cc @alanamarzoev you might know how to fix this

**Comment by robertnishihara** [comment]
Closing because this aspect of the UI has changed substantially (in the current master), see https://github.com/ray-project/ray/pull/4066.
