### ISSUE TITLE
[tune] Only stop when all stopping conditions are met 

### ISSUE THREAD

**Issue by JamieMair** [ray-project/ray#9312]
### What is your question?
tune.run includes an argument for stopping conditions, however, the training stops when any one of these conditions is met:

> stop (dict) – The stopping criteria. The keys may be any field in the return result of ‘train()’, whichever is reached first. Defaults to empty dict.

Is there any way to ensure that tune only stops when _all_ conditions are met?

**Comment by richardliaw** [comment]
You can implement a custom stopper: https://docs.ray.io/en/master/tune/api_docs/execution.html#stopper-tune-stopper

**Comment by JamieMair** [comment]
That's very useful thanks.
