### ISSUE TITLE
How to log from custom code with logging?

### ISSUE THREAD

**Issue by iamhatesz** [ray-project/ray#9320]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 0.8.6 + latest wheels, Ubuntu 20.04 LTS

### Reproduction (REQUIRED)

I've seen standard `logger = logging.getLogger(__name__)` definition inside multiple Ray modules, so I thought this can be used to log my own messages. Unfortunately, with the following code, nothing appears in the output. Am I missing something?

```python
import logging

import ray
from ray import tune
from ray.rllib.agents.callbacks import DefaultCallbacks

logger = logging.getLogger(__name__)

class Callbacks(DefaultCallbacks):
    def on_train_result(self, trainer, result: dict, **kwargs):
        logger.info("Iteration finished!")

if __name__ == '__main__':
    ray.init(logging_level=logging.INFO)

    logger.info("Hello, Ray!")

    tune.run("PPO", config={
        "env": "CartPole-v0",
        "framework": "torch",
        "callbacks": Callbacks,
        "log_level": logging.INFO,
    })
```

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @richardliaw

**Comment by richardliaw** [comment]
Can you see if this https://github.com/ray-project/ray/pull/9319 helps?

**Comment by saswatac** [comment]
I looked at the solution in https://github.com/ray-project/ray/issues/9030 , which seems to be require the logging to be configured in the remote function / actor. Instead of this, i was wondering if there was any hooks or callbacks available which gets executed during ray.init on the workers. Such a mechanism could be used to initialise the logger for the worker.

**Comment by iamhatesz** [comment]
My understanding was that there is a default logger initialized on each worker, so when I write `logger.info(...)`, the output is redirected to the driver and finally printed in the console. I've seen multiple `logger = logging.getLogger(__name__)` statements in the rllib code, so I thought this is enough to have that kind of functionality. But the code I posted above doesn't work as I expected. So, the question is: whether this is a bug or not?

**Comment by HJasperson** [comment]
For anyone who runs across this:
Ray creates many loggers whose names you can get with 
`print([name for name in logging.root.manager.loggerDict])`. 
You can use whichever one you want (e.g. `logger = logging.getLogger('ray.rllib')`). 

The critical step is to **set the log level**. The loggers are generally set to WARNING, so you'll either need to make all your messages `logger.warning()` or set the log level lower with `logger.setLevel('INFO')`.
