### ISSUE TITLE
np.load('vgg16.npy',encoding='latin1', allow_pickle=True) getting  error "Ran out of input"

### ISSUE THREAD

**Issue by suvicharsadhana** [ray-project/ray#9328]
### What is the problem?
np.load('vgg16.npy',encoding='latin1', allow_pickle=True) getting  error "Ran out of input" , using tensor-flow in python 3.5

**Comment by richardliaw** [comment]
Is this a ray bug?

**Comment by suvicharsadhana** [comment]
No, actually i am new in github, i am trying this in tensor-flow. by mistake i put error in this project
