### ISSUE TITLE
[autoscaler] Support LaunchTemplate/NetworkInterfaces in Node Config

### ISSUE THREAD

**Issue by BrentSouza** [ray-project/ray#9334]
### Describe your feature request

We have some LaunchTemplates configured for our EC2 instances that we would like to use with the autoscaler config in AWS. This way our engineering teams can configure the AWS environment and our research team does not have to be overly concerned with the AWS configuration. 

This doesn't seem to work currently because `config.py` expects to find certain items like the `IamInstanceProfile`, `KeyPair`, `SubnetId`, and `SecurityGroupIds` within the node configuration directly, and if they aren't there it creates some default items which negates the purpose of using a LaunchTemplate. It would be swell if it also checked for these items in a LaunchTemplate definition.

To that end, I've started work locally on modifying the code and will submit a PR in the near future. I wanted to open the issue to see if there was general guidance/feedback on why a LaunchTemplate configuration option should not be supported.

**Comment by richardliaw** [comment]
cc @thomasdesr

**Comment by pdames** [comment]
Thanks for opening this issue @BrentSouza! Adding LaunchTemplate support to the AWS Autoscaler is something that we've previously discussed and determined to be a valuable improvement. It is also being tracked as milestone [8] of https://github.com/ray-project/ray/issues/8420. I'd be happy to serve as a resource to help review the changes in your PR and to answer any questions that may arise in the course of design/implementation.

**Comment by BrentSouza** [comment]
Thanks @pdames! I'm working on writing some tests for the PR now. I'll update the PR checklist and description with a little bit more explanation behind reasons for the changes I've made. Good news is that testing locally, I do have the autoscaler configuration working with LaunchTemplates.

**Comment by lenassero** [comment]
Hi all ! I have the same issue when trying to use a network interface. Basically the subnet id is set by the autoscaler which conflicts with the one of the network interface. This results in the following error:
```
botocore.exceptions.ClientError: An error occurred (InvalidParameterCombination) when calling the RunInstances operation: Network interfaces and an instance-level subnet ID may not be specified on the same request
```

My config looks like the following:

````
head_node:
    InstanceType: m5.large
    ImageId: ami-xxx

    NetworkInterfaces:
        - NetworkInterfaceId: eni-xxx
          DeviceIndex: 1

   # This is not set
   # SubnetId: xxx
```

**Comment by pdames** [comment]
Thanks for the info @lenassero! For the record, I've also verified that both default security group IDs and subnet IDs set by the autoscaler will conflict with any present in custom NetworkInterfaces today (regardless of whether those NetworkInterfaces are provided directly in the top-level head/worker node config, or as part of a EC2 launch template).
