### ISSUE TITLE
[RaySGD] Support for Pytorch samplers in Dataset class  

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#9337]
The RaySGD [built-in Dataloader class](https://docs.ray.io/en/master/raysgd/raysgd_ref.html#dataset) does not support using a [PyTorch Sampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.Sampler). Samplers are a must for imbalanced datasets.

**Comment by richardliaw** [comment]
cc @wuisawesome

**Comment by amogkam** [comment]
We have now deprecated Ray SGD and have replaced with with [Ray Train](https://docs.ray.io/en/latest/train/train.html) which provides a more flexible API for distributed deep learning training on Ray!

With Ray Train, you can now directly use Pytorch Datasets/DataLoaders/Samplers when doing distributed training. 

If you are using Ray Datasets to load in the data, you can add a Pytorch sampler inside your training function to the torch dataset returned by `train.get_dataset_shard.to_torch()`. See the Ray Datasets+Ray Train integration for more information! (https://docs.ray.io/en/latest/train/user_guide.html#distributed-data-ingest-ray-datasets)
