### ISSUE TITLE
[tune] Expose hook to track experiment-level metrics

### ISSUE THREAD

**Issue by RodgerLuo** [ray-project/ray#9339]
### Describe your feature request
Can we have a feature to automatically reconstruct learning curve of PBT runs that can be visualized in TensorBoard?

**Comment by richardliaw** [comment]
(resolved offline) - We want to provide the ability to just visualize the best model performance across time for each hyperparameter sweep.

**Comment by richardliaw** [comment]
This is also done via the new Callbacks API!
