### ISSUE TITLE
[rllib] Asynchronous Performance Improvements Inspired by Sample Factory [ICML 2020]

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9360]
### Describe your feature request

Hi, I recently came across [Sample Factory: Egocentric 3D Control from Pixels at 100000 FPS with Asynchronous Reinforcement Learning](https://arxiv.org/abs/2006.11751) at ICML 2020 which beats the rllib implementation of IMPALA. I was wondering if we could add support for the performance improvements described in their implementation. Their code is publicly available: https://github.com/alex-petrenko/sample-factory

![image](https://user-images.githubusercontent.com/33183774/86936596-3a4b4080-c10c-11ea-9018-d1a5963326c4.png)

![image](https://user-images.githubusercontent.com/33183774/87565104-34ff7000-c68f-11ea-963e-0f506f765238.png)

![image](https://user-images.githubusercontent.com/33183774/87565124-3af55100-c68f-11ea-8780-fa2e385eef57.png)

**Comment by ericl** [comment]
Integrating a high performance sampler certainly makes sense. Maybe we can leverage sample factory directly in rllib, if the data formats are compatible. Cc @sven1977

**Comment by rkooo567** [comment]
cc @sven1977

**Comment by juliusfrost** [comment]
This feature would still be great to have. I'm willing to work on it if I had the time.

**Comment by rkooo567** [comment]
Nice! I will mark it as p2 (then it won’t be marked as stale in any case). Cc @sven1977

**Comment by Rohan138** [comment]
Closing since we now have an optimized version of APPO (similar to SampleFactory) based on the IMPACT paper: https://arxiv.org/abs/1912.00167
