### ISSUE TITLE
[rllib] how to store/get information globally to all envs

### ISSUE THREAD

**Issue by Phirefly9** [ray-project/ray#9362]
I want to store certain parameters in a global storage available to all environments, Each environment would read from the storage and read information during the reset function.  During the on_train_result I may modify those parameters based on the metrics that come back.

Is this possible with stock rllib?

There doesn't seem to be an easy way for an environment to hook into the underlying redis storage from the docs, and the examples didn't show a way to do this.  Maybe a custom workflow would allow it?  If at all possible I would like to stay in the environment class/callbacks.

**Comment by Phirefly9** [comment]
https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py#L445 

using the trainer global variables would be one way to do it, but would like input if there is a better way.

**Comment by ericl** [comment]
I would use a named actor for this, see https://docs.ray.io/en/master/rllib-training.html#global-coordination

**Comment by Phirefly9** [comment]
oh, that looks perfect. Thanks!
