### ISSUE TITLE
[tune] Handling exceptions for the analysis module when encountering nans

### ISSUE THREAD

**Issue by Nicolaus93** [ray-project/ray#9364]
Hi, after running some experiments with tune I was trying to get the best configuration/log dir using `get_best_config` and `get_best_logdir` from the analysis module. Unfortunately, I had some `nan` values in the metric I was measuring, and both methods returned an error related to Pandas. After checking the code, I found that the line causing the error is in the function `_retrieve_rows`:
https://github.com/ray-project/ray/blob/4da0e542d54c7977aae5bda5242cab15ab3f344b/python/ray/tune/analysis/experiment_analysis.py#L164
In particular, if there are `nan` values then the variable `idx` will be equal to `nan` and that will cause the following: `TypeError: Cannot index by location index with a non-integer key`.
I was wondering if you could add an exception for this case, warning the user that the experiment returned some `nan` values. I had to spend some time understanding what was wrong.

**Comment by richardliaw** [comment]
Thank you for opening this issue! Sorry about this - I think we're not handling nans correctly throughout the system. 

We'll get to this next week, and I'll ping you once we have a patch merged (or feel free to push a PR too).

Thanks!
