### ISSUE TITLE
[branch] which brach's example should I follow?

### ISSUE THREAD

**Issue by rightx2** [ray-project/ray#9369]
I'm trying to follow up `mnist_pytorch_trainable.py` but codes are different between the `master` branch and `0.8.6` branch, which is the latest

The one said I should override `_train`, `_step` but the other,  just `step`, `setup`.

And `pytorch-lightning` example is implemented only in the `master` branch.

I cloned the repo and compared both branch's histories but it looked like they are not merged for a long time (they have different commits history and don't have cross commit")

Traditionally, the `release` tag or branch used to come out from `master` only when they are about to be released, but `ray` seems not to be.

Could you explain that please? Which one should I choose in this case, stable or latest?

**Comment by richardliaw** [comment]
Sorry about this; the absolute latest is master, and the wheels for master can be found https://docs.ray.io/en/master/installation.html#latest-snapshots-nightlies
