### ISSUE TITLE
The question about the train in gym environment

### ISSUE THREAD

**Issue by hecong97** [ray-project/ray#9372]
When I use the command “python train.py --run A3C --env PongNoFrameskip-v4”, there is the error "ray.tune.error.TuneError: ('Trials did not complete', [A3C_PongNoFrameskip-v4_04ccf_00000])". It's same on the Breakout environment.
How can I solve it? Thanks!

**Comment by hcch0912** [comment]
Do you have a more detailed log to post here, please? The error message is general when ray tune stops, so we couldn't tell anything from it.

**Comment by hecong97** [comment]
I used the old version Ray that cause the error,and the bug has been fixed in the newest version. Thanks for your respond.
