### ISSUE TITLE
Inefficient serialization for some non-primitive objects

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#938]
The current serialization is slow for types other than primitives and lists, tuples, and dicts.  A simple example with sets shows the inefficiency:

```
import ray
import pickle

ray.init()

d = dict()

for i in range (100000):
    d[i] = set(["test"+str(i),"test10"+str(i)])

%time s1 = pickle.dumps(d) # 333 ms

%time s2 = ray.put(d) # 4.57s
```

**Comment by robertnishihara** [comment]
Thanks for bringing this up, this is an important problem.

Copying the below from https://github.com/ray-project/ray/issues/907#issuecomment-327563088.

Our serialization code is written in C++ and is normally quite fast when mapping Python objects to the Arrow format. However, the C++ code only handles primitive types and lists/dicts/tuples. So when it encounters something it doesn't know how to serialize (e.g., a set), then it falls back to using cloudpickle (so it leaves C++ and goes back to Python).

There are a couple things that could be done.
- Add a special case for sets in the C++ code (this probably makes sense, but it won't work if you replace the sets in your example with some custom Python class).
- We need to generally optimize this code path more.

**Comment by pcmoritz** [comment]
Hey Luke,

thanks for the bug report! I just implemented faster set serialization here:

https://github.com/apache/arrow/compare/master...pcmoritz:serialize-sets

I agree either this is the way to go or optimizing arbitrary custom defined iterables. The numbers with the new implementation are as follows now:

```
import pyarrow

d = dict()
for i in range (100000):
    d[i] = set(["test"+str(i),"test10"+str(i)])

import pickle
%time s1 = pickle.dumps(d) # 312 ms

import pyarrow
%time s2 = pyarrow.serialize(d).to_buffer() # 122ms
```

It will take a bit to get this or a similar change merged into Arrow and Ray. Meanwhile if you need the performance, you can edit https://github.com/ray-project/ray/blob/master/src/thirdparty/download_thirdparty.sh to point to my branch above.

**Comment by virtualluke** [comment]
thanks.   One thing I am curious about is that if ray.put() is falling back on cloudpickle when it doesn't know something better why is ray.put() much slower than pickle ever?  I am trying to understand the internals better.

**Comment by robertnishihara** [comment]
So a couple differences that I just noticed.

```python
import pickle
import cloudpickle

l = [set([i]) for i in range(10 ** 5)]
```

Pickle is pretty fast in this case.

```python
%time result = pickle.dumps(l)  # 168 ms
```

It looks like **cloudpickle may be much slower than pickle** in this case.

```python
%time result = cloudpickle.dumps(l)  # 1.86 s
```

**Ray (via Arrow) is actually doing something like the following** where it fails to serialize each individual element of the list and so falls back to cloudpickle many many times.

```python
%time result = [cloudpickle.dumps(s) for s in l]  # 2.93 s
```

**Comment by robertnishihara** [comment]
#957 should fix the issue with serializing sets, although the general problem remains.

**Comment by robertnishihara** [comment]
Closing this since the issue was fixed for sets. If there are other non-primitive types that cause issues (which I'm sure there are), then we should track those in separate issues.
