### ISSUE TITLE
Confuse about the usage of rollout worker and env

### ISSUE THREAD

**Issue by Privilger** [ray-project/ray#9390]
### What is your question?
When scaling the training, I'm confused about these two cases:

1. 1 Worker with 5 Env
2. 5 Worker, each Worker contains 1 Env

What is the difference between these two cases? I think both of them are running 5 instances of training Env. They looks same. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray version: 0.8.6
Python version: 3.6

**Comment by ericl** [comment]
In the second case, there will be 5 processes each with a separate copy of the policy. If the envs are slow to step this increases parallelism.

**Comment by Privilger** [comment]
Thanks, ericl. 

How about the step() function?  Is it called parallel in both cases?
