### ISSUE TITLE
[docs] Issue on `actors.rst`

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#9395]
# Documentation Problem/Question/Comment
ActorPool documentation is missing; it seems like we're not rendering something properly.

(Created directly from the docs)

**Comment by xiwen1995** [comment]
It looks like this issue has been fixed. 
<img width="818" alt="ActorPool" src="https://user-images.githubusercontent.com/20164475/87386362-4ef56180-c56e-11ea-9c05-03c17fdf8bc4.png">

**Comment by richardliaw** [comment]
closed in #9433  - thanks!
