### ISSUE TITLE
The bug when using lstm[rllib]

### ISSUE THREAD

**Issue by hecong97** [ray-project/ray#9397]
**In the Pong environment, when I change the "use_lstm" to True in the default model setting, there is an error:**

Number of trials: 1 (1 ERROR)
+---------------------------------------+----------+-------+
| Trial name                            | status   | loc   |
|---------------------------------------+----------+-------|
| IMPALA_PongNoFrameskip-v4_84a1d_00000 | ERROR    |       |
+---------------------------------------+----------+-------+
Number of errored trials: 1
+---------------------------------------+--------------+-------------------------------------------------------------------------------------------------+
| Trial name                            |   # failures | error file                                                                                      |
|---------------------------------------+--------------+-------------------------------------------------------------------------------------------------|
| IMPALA_PongNoFrameskip-v4_84a1d_00000 |            1 | /root/ray_results/pong-impala/IMPALA_PongNoFrameskip-v4_0_2020-07-10_14-56-45xy6qgned/error.txt |
+---------------------------------------+--------------+-------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "/usr/local/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/scripts.py", line 34, in cli
    train.run(options, train_parser)
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/train.py", line 225, in run
    concurrent=True)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 413, in run_experiments
    return_trials=True)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py", line 349, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [IMPALA_PongNoFrameskip-v4_84a1d_00000])

I wonder to know why the lstm setting would lead the error and how to solve that.

**Comment by sven1977** [comment]
Can you try with the latest wheel (master)? This has been fixed recently.

**Comment by sven1977** [comment]
See this test case here: ray.rllib.agents.ppo.tests.test_ppo.py:
```
        for _ in framework_iterator(config):
            for env in ["CartPole-v0", "MsPacmanNoFrameskip-v4"]:
                print("Env={}".format(env))
                for lstm in [True, False]:
                    print("LSTM={}".format(lstm))
                    config["model"]["use_lstm"] = lstm  # <- we test both True and False here
                    config["model"]["lstm_use_prev_action_reward"] = lstm
```

**Comment by sven1977** [comment]
Ok, confirmed. All NaNs. But makes sense, if input is a file, then there are no samplers, hence no actual env. We should probably have sampling for the evaluation workers, though to indicate actual learning progress. ...
