### ISSUE TITLE
[rllib] Best practice for normalizing observations with running mean

### ISSUE THREAD

**Issue by stefanbschneider** [ray-project/ray#9399]
### What is your question?

I want to normalize my observations without knowing the exact range up front; hence, I think using a running mean for normalization would be best. I only want to apply this normalization to parts of my dict observation space.

What's the recommended way to do that? 

The [RLlib documentation](https://docs.ray.io/en/latest/rllib-models.html#custom-preprocessors) points to [Gym wrappers](https://github.com/openai/gym/tree/master/gym/wrappers), but I didn't see any wrapper for running mean normalization of observations (possible that I missed sth).
Other frameworks have their own utility class for this, eg, [OpenAI baselines](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/vec_normalize.py) and [stable baselines](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#vecnormalize).

Does RLlib have something similar that I could use out of the box? Or do I need to implement it myself (what would be the best starting point)?

**Comment by stefanbschneider** [comment]
It seems like there is an option in the configs to set a `MeanStdFilter`: https://docs.ray.io/en/latest/rllib-training.html?highlight=observation_filter#common-parameters

```python
config['observation_filter'] = "MeanStdFilter"
```

Not sure how I could test if it does what I want? Where/how could I see/log the normalized observations?

**Comment by NJannasch** [comment]
> It seems like there is an option in the configs to set a `MeanStdFilter`: https://docs.ray.io/en/latest/rllib-training.html?highlight=observation_filter#common-parameters
> 
> ```python
> config['observation_filter'] = "MeanStdFilter"
> ```
> 
> Not sure how I could test if it does what I want? Where/how could I see/log the normalized observations?

Found some details for the MeanStdFilter in [rllib/utils/filter.py](https://github.com/ray-project/ray/blob/60d4d5e1aaa9fde3cf541ee335e284d05e75679c/rllib/utils/filter.py)

Additional filters might be added into the _get_filter_ function. But its also marked as ToDo.
