### ISSUE TITLE
check_compute_single_action

### ISSUE THREAD

**Issue by zzcNEU** [ray-project/ray#9405]
rllib

I have download your github code and I wanna run it on my local PC. But in you rl ALgrithoms, just as ppo, I run the test_ppo.But there is an error.
It  can not from ray.rllib.utils.test_utils import check, check_compute_single_action

But I hava cd to the dir. Do you knw why?

**Comment by hcch0912** [comment]
have you done the installation?

**Comment by richardliaw** [comment]
Try installing ray (pip install ray). Feel free to reopen this if there's an issue.
