### ISSUE TITLE
[rllib] Oddities in handling observation_filter

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#941]
1. Unclear if intentional, but `observation_filter` and `reward_filter` parameters are unused here. https://github.com/ray-project/ray/blob/master/python/ray/rllib/ppo/rollout.py#L99
2. For stateful filters, `compute_action` (which seems to be the standard non-training endpoint for the model) may want to default to non-updating (set `update=False`) https://github.com/ray-project/ray/blob/master/python/ray/rllib/ppo/ppo.py#L271

cc: @pcmoritz @ericl

**Comment by ericl** [comment]
Fixed in https://github.com/ray-project/ray/pull/1018
