### ISSUE TITLE
ray.init - could not connect to socket

### ISSUE THREAD

**Issue by ronan-keane** [ray-project/ray#9410]
### What is the problem?
Unable to ray.init() on windows. This is the printout 
>E0710 18:04:36.314152 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 1, num_retries = 10)
E0710 18:04:38.343468 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 2, num_retries = 10)
E0710 18:04:40.370450 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 3, num_retries = 10)
E0710 18:04:42.397589 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 4, num_retries = 10)
E0710 18:04:44.418875 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 5, num_retries = 10)
E0710 18:04:46.452200 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 6, num_retries = 10)
E0710 18:04:48.497956 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 7, num_retries = 10)
E0710 18:04:50.513307 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 8, num_retries = 10)
E0710 18:04:52.528875 11144 212 raylet_client.cc:69] Retrying to connect to socket for pathname tcp://127.0.0.1:64430 (num_attempts = 9, num_retries = 10)
F0710 18:04:53.541085 11144 212 raylet_client.cc:78] Could not connect to socket tcp://127.0.0.1:64430
*** Check failure stack trace: ***
@ 00007FF828A83A8C public: __cdecl google::LogMessage::~LogMessage(void) __ptr64
@ 00007FF8288F8954 public: virtual __cdecl google::NullStreamFatal::~NullStreamFatal(void) __ptr64
@ 00007FF82893351B public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
@ 00007FF828935B5E public: void __cdecl google::NullStreamFatal::`vbase destructor'(void) __ptr64
@ 00007FF828843B98 public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
@ 00007FF828841C00 public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
@ 00007FF8288400ED public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
@ 00007FF82883F9C3 public: class google::LogMessageVoidify & __ptr64 __cdecl google::LogMessageVoidify::operator=(class google::LogMessageVoidify const & __ptr64) __ptr64
@ 00007FF8287BF179 public: virtual __cdecl google::LogSink::~LogSink(void) __ptr64
@ 00007FF86262682F _PyObject_FastCallKeywords
@ 00007FF86262663A _PyObject_FastCallKeywords
@ 00007FF86262E65E _PyMethodDef_RawFastCallKeywords
@ 00007FF86262F042 _PyEval_EvalFrameDefault
@ 00007FF86261B2F6 _PyEval_EvalCodeWithName
@ 00007FF86262E62C _PyMethodDef_RawFastCallKeywords
@ 00007FF86262F789 _PyEval_EvalFrameDefault
@ 00007FF86272128B _PyStack_UnpackDict
@ 00007FF862676B1B PyErr_NoMemory
@ 00007FF86262F042 _PyEval_EvalFrameDefault
@ 00007FF86261B2F6 _PyEval_EvalCodeWithName
@ 00007FF86260AD14 PyImport_Import
@ 00007FF86260ABD9 PyImport_Import
@ 00007FF86262DA10 _PyMethodDef_RawFastCallKeywords
@ 00007FF86262E577 _PyMethodDef_RawFastCallKeywords
@ 00007FF86262EC3F _PyEval_EvalFrameDefault
@ 00007FF8626177F0 _PyObject_GetAttrId
@ 00007FF8626779A0 PyErr_NoMemory
@ 00007FF8626177F0 _PyObject_GetAttrId
@ 00007FF8626779A0 PyErr_NoMemory
@ 00007FF8626177F0 _PyObject_GetAttrId
@ 00007FF86262DA31 _PyMethodDef_RawFastCallKeywords
@ 00007FF86262E3BC _PyMethodDef_RawFastCallKeywords

python.exe, pythonw.exe, redis-server all have exceptions for windows firewall, I also added exceptions to the tcp ports 64000-65535 so I'm not sure why it's saying it can't connect. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
windows 10 enterprise
ray 0.8.6
tensorflow 2.2.0
python 3.7.3

- [ X] I have verified my script runs in a clean environment and reproduces the issue.
- [ X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @mehrdadn

**Comment by mehrdadn** [comment]
Thanks for reporting! I can't reproduce this with your information unfortunately. Would you mind pasting the output of this command?

    python -c "import sys; print(sys.version)"

Would you mind running [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and showing the portion of the screenshot that shows everything running under the Python process?

Also, is there any other information that you think might be helpful/relevant in reproducing this? Maybe an antivirus system or other something else that might be interfering?

**Comment by ronan-keane** [comment]
I tried disabling my antivirus (malwarebytes) real time protection and that actually fixed the issue. Strange because malwarebytes wasn't giving me any notifications it was blocking anything.

**Comment by mehrdadn** [comment]
Ahh I see, thanks!

**Comment by stefanbschneider** [comment]
I just upgraded to 0.8.7 on WSL on Windows and I also have this error. Disabling my antivirus didn't help.

**Comment by mehrdadn** [comment]
@stefanbschneider: Does this help? https://github.com/ray-project/ray/issues/10655#issuecomment-689164890

**Comment by stefanbschneider** [comment]
Hm, so the error occurred with my antivirus disabled via GUI and Python 3.8.3 on WSL 1 on Windows 10 for ray[rllib] 0.8.7.

I downgraded to 0.8.6 and the problem is resolved. That's more convenient for me than trying to completely disable my antivirus (which I don't want).

**Comment by mehrdadn** [comment]
@stefanbschneider Ah I see, okay thanks. @richardliaw/@rkooo567 just a heads up; not sure if you guys want to reopen the issue.
