### ISSUE TITLE
[rllib] Strange shape mismatch error with custom model and custom environment

### ISSUE THREAD

**Issue by arkose** [ray-project/ray#9423]
### What is the problem?

When I run a custom model / custom environment in tune, there is a ValueError: Expected output shape of [None, 16], got (?, 8). It is not clear where this doubled value for action shape is coming from, as both the model and the environment's action specification have shape (8,). Is this a bug?

Ray version 0.9.0.dev0 from wheel
Python3 version 3.8.2
Tensorflow 2.2
Ubuntu

Error output.
[error.txt](https://github.com/ray-project/ray/files/4908015/error.txt)

### Reproduction (REQUIRED)

Rename to Minimal.py and run.
[Minimal.txt](https://github.com/ray-project/ray/files/4908017/Minimal.txt)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by ericl** [comment]
Probably it is since PPO's continous action distributions are parameterized by mean and stds, doubling the number of outputs required. Your model should make sure to obey the `num_outputs` argument and not look directly at the action space.

**Comment by arkose** [comment]
Thank you, I didn't realize.
