### ISSUE TITLE
[rllib]The use of conv_filter

### ISSUE THREAD

**Issue by hecong97** [ray-project/ray#9425]
### What is the problem?
**When I add the conv_fliter parameter in the config,the error would appear.**
The ray is the latest wheel.
And the config I set is that:
```
config = {'gamma': 0.9,
          'lr': 1e-2,
          'num_workers': 1,
          'num_envs_per_worker': 1,
          'train_batch_size': 512,
          'num_gpus': 8,
          'model': {
              'dim': 84,
              'framestack': False,
              'no_final_linear': False,
              'conv_filters': [
                  [16,8,4],
                  [32,4,2]
              ],
              'fcnet_hiddens': [256, 256],
              'use_lstm': True,
              'lstm_cell_size': 256,
          }}
trainer = agents.impala.ImpalaTrainer(env='BreakoutNoFrameskip-v4', config=config)
```
The error is in the visionnet.py in 87 line.
```
      if vf_share_layers:
            last_layer = tf.keras.layers.Lambda(
                lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
````
and the error is :
Can not squeeze dim[1], expected a dimension of 1, got 9 for 'default_policy/lambda/Squeeze' (op: 'Squeeze') with input shapes: [?,9,9,32]. 
Is there some probles on the conv_fliter out to the next layer?

**Comment by sven1977** [comment]
Hi @hecong97 thanks for filing this. For a quick fix, try adding yet another conv2d filter that results in a [B, 1, 1, n] output, so it's squeezable, like so (but we should automate this):

```
              'conv_filters': [
                  [16,8,4],
                  [32,4,2],
                  [64,11,1]
              ],
```

**Comment by baleksey** [comment]
Have the same error and I don't know hot to fix.

"ValueError: Can not squeeze dim[1], expected a dimension of 1, got 8 for 'default_policy/lambda/Squeeze' (op: 'Squeeze') with input shapes: [?,8,8,1]."

Using config:
'model': {	
	'conv_activation': "relu",
	'dim': 10, 
	
	'conv_filters': [  	
		 [32, [3, 3], 1], 
		 [16, [3, 3], 1],
	],
	
	'fcnet_hiddens': [256], 
	'fcnet_activation':'tanh'
	},

**Comment by zzchuman** [comment]
> ### 问题是什么？
> **当我在配置中添加conv_fliter参数时，将出现错误。**
> 射线是最新的轮子。
> 我设置的配置是：
> 
> ```
> config = {'gamma': 0.9,
>           'lr': 1e-2,
>           'num_workers': 1,
>           'num_envs_per_worker': 1,
>           'train_batch_size': 512,
>           'num_gpus': 8,
>           'model': {
>               'dim': 84,
>               'framestack': False,
>               'no_final_linear': False,
>               'conv_filters': [
>                   [16,8,4],
>                   [32,4,2]
>               ],
>               'fcnet_hiddens': [256, 256],
>               'use_lstm': True,
>               'lstm_cell_size': 256,
>           }}
> trainer = agents.impala.ImpalaTrainer(env='BreakoutNoFrameskip-v4', config=config)
> ```
> 
> 错误在87行的visionnet.py中。
> 
> ```
>       if vf_share_layers:
>             last_layer = tf.keras.layers.Lambda(
>                 lambda x: tf.squeeze(x, axis=[1, 2]))(last_layer)
> ```
> 
> 错误是：
> 无法挤压dim [1]，预期尺寸为1，输入形状为[？，9,9,32]的'default_policy / lambda / Squeeze'（op：'Squeeze'）得到9。
> 在conv_fliter上是否存在一些问题，可以扩展到下一层？

Hello, have you solve it？ Actually, I want to use the lstm and conv_filter together. Can you tteach me how to set it?
