### ISSUE TITLE
[rllib] lr_schedule no longer working in IMPALA?

### ISSUE THREAD

**Issue by waldroje** [ray-project/ray#9428]
### What is the problem?
I haven't used it in a while, but it seems to me that the `lr_schedule `no longer get's applied when running IMPALA, the attached script works as expected with PPO, but the reported `lr `remains constant for IMPALA, unless it's just a reporting issue.

*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.6, python 3.6.8, tf 2.2, os rhel 7.6

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

[cart-pole-impala.zip](https://github.com/ray-project/ray/files/4908400/cart-pole-impala.zip)

**Comment by sven1977** [comment]
Could you provide a simple reproduction script including the used config and everything needed to reproduce this issue?
Thanks.

**Comment by waldroje** [comment]
I did, it’s attached to the original submission… cart-pole-impala.zip… just needs to be unzipped… the platform rejects .py files… so I zipped it.

**Comment by sven1977** [comment]
ok, sorry, will check this ...
