### ISSUE TITLE
DDPG Ray TUNE Hyperparameter Tuning problem

### ISSUE THREAD

**Issue by ernest2015** [ray-project/ray#9430]
Hello,
I run grid search for tuning hyperparameters "critic_lr" and "actor_lr" (see the code bellow)
I expected to follow a learning progress for all 4 samples (num_samples=4) in parallel.  The problem is that the next sample starts only when the previous ends. So in tensorboard you cannot see the progress of all four "episode_reward_mean" curves in parallel but in a sequence (when first ends after 350000 steps in my case, the second sample starts).

As you can see in the screen shot bellow, the next trial starts only when the previous terminates - they don't run in parallel.
![image](https://user-images.githubusercontent.com/16582809/87254335-3740af00-c482-11ea-812b-a801475f80cf.png)

Is that the problem for DDPG algorythm? (It seems to me that I have successfully tested  this for PPO.)

I also have the same problem with PBT hyperparameters settings with DDPG alg.

Thanks,
Ernest

    ray.init()
    trials=tune.run(
        "DDPG",
        name="DDPG_TEST_GridSearch_1",
        stop={"timesteps_total": 350000},
        num_samples=4,
        local_dir="~/ray_results",
        checkpoint_freq=1,
        checkpoint_at_end=True,
        
        config={

            "critic_lr": tune.grid_search([0.0001,0.001, 0.01, 0.1]),
            "actor_lr": tune.choice([0.0001,0.001, 0.01, 0.1]),

            "env": SpiceEnv,
            "num_gpus": 0,   
            "num_workers": 7                 
        })

    print("Best config: ", analysis.get_best_config(metric="mean_loss"))

    # Get a dataframe for analyzing trial results.
    df = analysis.dataframe()`

**Comment by richardliaw** [comment]
how many CPUs are on your machine?

**Comment by ernest2015** [comment]
Thanks for a quick response! After resetting a machine (a server) it looks that the problem has gone. Now all samples again run in parallel.

**Comment by ernest2015** [comment]
Hello @richardliaw, there's no problem with early stopping algorithms like PBT and ASHA (ex. scheduler=pbt or scheduler=asha; only these two were tested), but the problem without scheduler tune.grid_search or tune.choice (mentioned above) remains!?

**Comment by richardliaw** [comment]
There are 8 cores but you are starting 7 workers per trial; so you shouldn't be seeing any parallelism.

**Comment by ernest2015** [comment]
Thanks @richardliaw, it's working. It confused me, because when I starts PBT then after each checkpoint, next trial (next line in a table) starts..., but when using grid-search then the whole training finishes and only then the next trial (next line in a table) starts.
![image](https://user-images.githubusercontent.com/16582809/87413513-b17c4b00-c5ca-11ea-8f2d-0ae6a5f0626c.png)

It was my misunderstanding, I hope now I understand;  Because there are separate "train" and "rollout" workers - one rollout worker per train worker. 11 workers and 8 cores; 3 workers should wait. 

![image](https://user-images.githubusercontent.com/16582809/87414349-f5238480-c5cb-11ea-990c-76c81abba418.png)

If I add only a fraction of a core per worker  ("num_cpus_per_worker": 0.1) then all workers run:
![image](https://user-images.githubusercontent.com/16582809/87417711-decbf780-c5d0-11ea-985e-c833130ec053.png)

![image](https://user-images.githubusercontent.com/16582809/87417425-70873500-c5d0-11ea-8727-e03bff54ab73.png)
Thanks!
