### ISSUE TITLE
[rllib]The problem on IMPALA 

### ISSUE THREAD

**Issue by hecong97** [ray-project/ray#9436]
### What is the problem?
When I use the impala.Imapla.trainer with the default model config. The error appears:

```
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 75 values, but the requested shape has 50
  File "/usr/local/lib/python3.6/dist-packages/ray/rllib/execution/concurrency_ops.py", line 132, in base_iterator
    raise RuntimeError("Error raised reading from queue")
RuntimeError: Error raised reading from queue
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
The ray is the newest wheel.

**Comment by sven1977** [comment]
Could you provide a simple repro script including a config and everything needed to reproduce this issue?
Thanks.

**Comment by hecong97** [comment]
The code is:
```
import ray
from ray.rllib import agents
ray.init() 
config = {'num_workers': 32,
          'num_envs_per_worker': 4,
          'train_batch_size': 512,
          'num_gpus': 8,
          'model': {
              'dim': 84,
              'framestack': False,
              'conv_filters': [
                  [16,8,4],
                  [32,4,2],
                  [64,11,1]
              ],
              'fcnet_hiddens': [256, 256],
              'use_lstm': False,
              'lstm_cell_size': 256,
          }
          }
#trainer = agents.ppo.PPOTrainer(env='BreakoutNoFrameskip-v4', config=config)
#trainer = agents.impala.ImpalaTrainer(env='PongNoFrameskip-v4', config=config)
trainer = agents.impala.ImpalaTrainer(env='BreakoutNoFrameskip-v4', config=config)
while True:
    results = trainer.train()
    print(results)
```
Even I set the model config as default, the error wouldn't disappear. But When I set the lstm is true, The error is solved.

**Comment by sven1977** [comment]
Hmm, interesting. Also only seems to happen if num_gpus > 0. ...

**Comment by andrew-rosenfeld-ts** [comment]
Just noting this also affects APPO (being based on IMPALA).

**Comment by DianaLi96** [comment]
I met this problem when the GPU nums set to 8, have you find the reason behind the error?

**Comment by karstenddwx** [comment]
got the same issue with IMPALA, happens sporadically (0.8.6 and 0.8.7), I'm not using GPU (num_gpus=0)

**Comment by Maxwell2017** [comment]
@DianaLi96 @hecong97 Have you guys solved this problem？

**Comment by guytenn** [comment]
having the same problem, seem to happen randomly
