### ISSUE TITLE
[tune] progress.csv missing header when training interrupted

### ISSUE THREAD

**Issue by ejunprung** [ray-project/ray#9444]
Hi, is there a way to ensure that headers are always generated in progress.csv. 

In some cases, training is interrupted (i.e. stop/resume) before the csv header can be generated. We use progress.csv to plot training progress in our application so the headers are necessary.

**Versions**
Ray 0.8.5
Tensorflow 1.15.0
Python 3.7.3
Debian OS

**Comment by richardliaw** [comment]
Headers should be generated whenever the trial starts running. If a trial has not started running, we try to not to create the csv file. 

If you want to change behavior, you may way to either provide a custom logger or in your application check for file existence?

**Comment by ejunprung** [comment]
We ended up doing exactly that but it's good to hear that you have the same recommendation. The problem seems to be fixed now!
