### ISSUE TITLE
We plan to  use Ray in Large-scale commercial scene at about June 2018

### ISSUE THREAD

**Issue by raopku** [ray-project/ray#945]
Will Ray have a stable version before that time? How can we contribute to Ray?
We plan to use Ray as a distributed execution engine of reinforcement learning application platform in Large-scale commercial scene at about June 2018

**Comment by robertnishihara** [comment]
Great! It should be production ready in about 9 to 12 months.

As for contributing, I'd like to do a couple things.
- Organize the github issues with a label indicating which ones are good for contributions, kind of like tensorflow does at https://github.com/tensorflow/tensorflow/labels/stat:contributions%20welcome?page=2&q=is%3Aopen+label%3A%22stat%3Acontributions+welcome%22
- We just added a mailing list for discussing development (as well as usage) https://groups.google.com/forum/#!forum/ray-dev
- Make sure all of the important tasks are documented in github issues

**Comment by robertnishihara** [comment]
Closing for now. Please reopen if you have more questions.
