### ISSUE TITLE
uneven distribution of load

### ISSUE THREAD

**Issue by virtualluke** [ray-project/ray#946]
I see the following kind of behavior on a 10 node ray cluster (each box: 56 cores, 256GB RAM, centos 7.3, Anaconda python3 latest):

I have a main process that launches 20-50 remote workers and each worker launches 10-30 remote workers which in turn may each launch 5-10 remote workers (different blocking stages of processing).  

The box I launch the program from gets a huge portion of the initial workers and this causes a large discrepancy in the load of the boxes over the time of the work.  It seems like the global scheduler is loading the initial box up quite a bit before assigning workers to other boxes.  Is there a setting to make the initial distribution more round-robin across nodes or similar?

**Comment by robertnishihara** [comment]
The "remote workers" you're referring to are "actors", right?

How are you checking where the actors are created? If you do `ray.global_state.actors()`, you'll get a list of information about the different actors. Each actor dictionary will have a `local_scheduler_id` field which identifies the node that the actor is on.

Is it possible that the driver program is creating some actors before some of the nodes have successfully connected to the cluster and so it is only choosing from the nodes that have connected?

**Comment by virtualluke** [comment]
I have a helper ray_log function that I am logging to disk and each log line includes the hostname which is how I could tell what box the functions were working from.  

No actors involved, just remote function calls. Sorry for that confusion.  It just so happened that my remote function in this case is called worker.  I was adapting some multiprocessing code to ray where the function was called worker.

All the nodes are connected to the cluster (started with a pssh ray start script right after boot).

**Comment by robertnishihara** [comment]
Oh, do the functions execute very quickly? If the remote functions are finishing almost instantaneously, then the local scheduler may choose to schedule most of the tasks locally because it's faster to do so.

If you add a `import time; time.sleep(0.01)` into the remote function, does that change the behavior?

**Comment by virtualluke** [comment]
Sorry for the delay getting back to this.

So here is some example code that counts the number of records in parquet files for a given day where the data is distributed in a log directory organized by year/month/day/hour.  For the attached logfile (which is just from entries generated from the ray_log function in the code), there were 3000-4000 parquet files per day and the code was run over a month of data.

```
import time
import glob
from fastparquet import ParquetFile
import os
import ray
import inspect

def ray_log(msg=''):
    log_file = "/data/log_output/raylog"
    with open(log_file, "a") as f:
        f.write(time.asctime() + ' box:' + os.getenv('HOSTNAME').split('.')[0] + ' function: ' + inspect.currentframe().f_back.f_code.co_name + ": " + msg + "\n")

@ray.remote
def process_chunks(chunks):
    ray_log()
    chunk_record_count = 0
    for f in chunks:
        chunk_record_count += ParquetFile(f).count
    return(chunk_record_count)

@ray.remote
def chunker(dirname):
    ray_log('beginning')
    chunksize = 15
    file_list=glob.glob(dirname+'/*')
    # chunk files in chunksize for parallelization
    chunks = [file_list[x:x+chunksize] for x in range(0,len(file_list),chunksize)]
    results = ray.get([process_chunks.remote(ch) for ch in chunks])
    hour_total= 0
    for r in results:
        hour_total += r
    ray_log('end')
    return(hour_total)

ray_log('----BEGIN----'+__file__)
ray.init(redis_address="10.0.0.100:6379")

for month in range(7,8):
    for day in range(1,32):

        path = '/data/logs/parquet/web/2017/{0:02d}/{1:02d}/*'.format(month,day)
        files_to_work = glob.glob(path)

        results = ray.get([chunker.remote(f) for f in files_to_work])

        day_total = 0
        for r in results:
            day_total += r

        path_split = path.split('/')
        output_file = '/data/output/parquet_daily_count_'+'_'.join(path_split[-5:-1])
        ray_log('writing daily_count')
        with open(output_file,'w') as fout:
            fout.write(str(day_total)+'\n')
```

As you can see from the attached logfile (raylog.txt), the server where the code was launched from (server26) dominates the amount of work.  For the 12 machines in the current ray cluster (56 cores each), each shows up (by line count) in the log around 400 times, except for server26 showing up 3300 times. I put time.sleep(.1) in both chunker and process_chunks and got similar results.

[raylog.txt](https://github.com/ray-project/ray/files/1303805/raylog.txt)

**Comment by concretevitamin** [comment]
(Totally missed the party, but I'm wondering what happens if the strategy is changed from "driver launches all tasks per day -> wait for those -> write" to "driver launches all tasks -> for each day, wait and write"?  E.g.:

```python
def Path(m, d):
    return '/data/logs/parquet/web/2017/{0:02d}/{1:02d}/*'.format(m, d)

results_dict = {}
for month in range(7, 8):
    for day in range(1, 32):
        files_to_work = glob.glob(Path(month, day))
        results_dict[(month, day)] = [chunker.remote(f) for f in files_to_work]

for month in range(7, 8):
    for day in range(1, 32):
        results = ray.get(results_dict[(month, day)])
        day_total = sum(results)
        path_split = Path(month, day).split('/')
        output_file = '/data/output/parquet_daily_count_' + '_'.join(
            path_split[-5:-1])
        ray_log('writing daily_count')
        with open(output_file, 'w') as fout:
            fout.write(str(day_total) + '\n')
```
I guess this depends on whether the cluster can handle 4000\*30\*2 tasks being submitted at roughly the same time.)

**Comment by virtualluke** [comment]
I had thought about doing it that way but was hoping to have some finer control over the parallelism by knowing it was split 24 times at the first level.  Also, the load on the boxes can be "tuned" for different workloads based on chunksize.  I am using this model a lot whether it is a aggregation across fields, roll-up pivot on different fields, etc so getting the parallelism right and load balanced is something I'm keen to get "right" (whatever that means).  Appreciate your comment and will think about it and give it a try.

**Comment by robertnishihara** [comment]
Most likely addressed now.
