### ISSUE TITLE
[rllib] marwil

### ISSUE THREAD

**Issue by zzcNEU** [ray-project/ray#9471]
hello， I want to use the marwil on rllib. 

First, I try to run the rllib test_marwil.py. But, it reminds me that no module of from ray.rllib.utils.test_utils import framework_iterator,check_compute_single_action . I dont kon why, Can you teach me?

And, your docs is simple! Can you wirite a tips or example teach me how to set the offline datasets to meet the MARWIL.

And I test it  MARWIL. But, MARWIL rewards is NAN.

Thanks you!
Hope you well!

**Comment by rkooo567** [comment]
cc @sven1977

**Comment by 09wakharet** [comment]
I can run test_marwil.py as is, and it train properly. Make sure that your ray installation is up to date (sudo pip install ray[rllib] --upgrade). Make sure to specifically install ray[rllib]. To train on new datasets, you'll have to update the data_file variable with your own dataset.
