### ISSUE TITLE
'ray memory' fails with invalid password error when cluster is started with redis-password option

### ISSUE THREAD

**Issue by kocic11** [ray-project/ray#9474]
### What is the problem?
When ray cluster is started using redis-password option ray memory always fails with invalid password error.
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
Start a cluster:
```
ray start --head --webui-host=0.0.0.0 --redis-port=55555 --redis-password="password"
```
Run a command:
```
ray memory
```
Error:
```
redis.exceptions.AuthenticationError: invalid password
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
You should be able to resolve this after this PR is merged. https://github.com/ray-project/ray/pull/9492

**Comment by kocic11** [comment]
Thanks. I noticed the PR was merged but it's not part of any release. I guess I could build ray or wait for the next release. 

Do you have any timeline for the next release? When will it be available?

**Comment by rkooo567** [comment]
We are planning to have the next release in the beginning of August!

**Comment by richardliaw** [comment]
@kocic11 you could also try using the latest nightly snapshot of master (https://docs.ray.io/en/latest/installation.html)

**Comment by ankur6ue** [comment]
This issue is still not resolved in the latest version of the code..

**Comment by rkooo567** [comment]
Did you try ray memory --redis-password=""? Can you explain more about how it is not resolved and how to reproduce the issue?
