### ISSUE TITLE
[rllib][Question] How do you export the MARWILTorchPolicy to ONNX ?

### ISSUE THREAD

**Issue by aditya-khant** [ray-project/ray#9476]
Hi,

 I have been running the MARWIL trainer with the default settings and am having trouble exporting it to ONNX. Any ideas/suggestions on how to do it?

**Comment by zzcNEU** [comment]
hello, I want to train model by offline datasets. on the example cartpole. But, my reward is always nan.
Do you know the reason?

**Comment by aditya-khant** [comment]
have you checked the rewards in the offline dataset?

**Comment by zzcNEU** [comment]
Hello, Itrain the mode las follows:
![image](https://user-images.githubusercontent.com/38434094/87744358-e3d1b680-c81d-11ea-825f-b427e1c6b3fc.png)
![image](https://user-images.githubusercontent.com/38434094/87744371-efbd7880-c81d-11ea-8f22-dac363142e27.png)
First, online train rewards is 190...
But,offline is nan
