### ISSUE TITLE
All objects returned by method stay pinned in memory even if only reference to one is kept

### ISSUE THREAD

**Issue by thatGreekGuy96** [ray-project/ray#9504]
### What is the problem?
We use ray to parallelise genetic algorithms. We noticed that in certain cases objects stay pinned in ray memory which sometimes fills up and causes the program to crash.

The reproduction script does not crash but running `ray memory` will show the leak (objects listed as `PINNED IN MEMORY` will increase). The number of objects still in memory scales with the number of generations (`N_GENS`). Also, the issue is not reproduced when  everything below `i==0` is removed (i.e. there is no subset of the returned evaluated solutions stored in memory). Finally, the issue also fails to reproduce for smaller returned arrays (`N_SOLUTIONS= 20`) or smaller elements of those arrays (`N_ARRAY_ELEMENTS=20`). [See screenshots attached]

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray version: 0.8.6
Python version: 3.7.6
OS: MacOS Catalina 10.15.5

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
import itertools
import numpy as np #essential to reproduce the issue

N_GENS = 20
N_ARRAY_ELEMENTS = 200
N_SOLUTIONS = 200

@ray.remote
class RayEvaluator:

    def evaluate_solutions(self):
        return [np.random.uniform(-1, 1, size=(N_ARRAY_ELEMENTS, )) for _ in range(N_SOLUTIONS)]

n_cpus = 8
ray.init(num_cpus=n_cpus)

for i in range(N_GENS):
    actors = [RayEvaluator.remote() for i in range(4)]
    futures = [actor.evaluate_solutions.remote() for j, actor in enumerate(actors)]
    results = list(itertools.chain.from_iterable([ray.get(future) for future in futures]))
    if i == 0:
        population = results
    else:
        random_indices = np.random.choice(np.arange(len(results)),
                                          size=2, replace=False).astype(int)
        for index in random_indices:
            population[index] = results[index]
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

![no_leak_no_population_replacement](https://user-images.githubusercontent.com/42438403/87576786-cdb2e180-c6c9-11ea-8d4c-a5a3ff763727.png)
No Leak: No population replacement 

![leak_10_generations](https://user-images.githubusercontent.com/42438403/87576800-d1deff00-c6c9-11ea-8b35-b7b089d336a8.png)
Leak: 10 generations run 

![leak_20_generations](https://user-images.githubusercontent.com/42438403/87576804-d3a8c280-c6c9-11ea-94d4-0cfee6f1ded9.png)
Leak: 20 generations run 

![no_leak_20_array_elements](https://user-images.githubusercontent.com/42438403/87576811-d60b1c80-c6c9-11ea-8215-5e95cebc2e96.png)
No leak: `N_ARRAY_ELEMENTS` set to 20

**Comment by ericl** [comment]
Seems like there is a very subtle issue here: Ray will treat the return of the remote call as one object. Even if it deserializes into multiple numpy arrays. So if you keep a reference to even a single element of that array, the entire return will be pinned in memory.

An easy fix is to np.copy() the result, which adds a bit of overhead but I'm guessing it doesn't matter for this application.
