### ISSUE TITLE
`test_multi_node.py::test_multi_driver_logging` hangs when GCS actor management is turned on. 

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9505]
### What is the problem?

test_multi_node.py::test_multi_driver_logging hangs when GCS actor management is on.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run test_multi_node.py::test_multi_driver_logging

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
cc @stephanie-wang

i don't think this test should deadlock (always a chance i messed it up). 

 i wonder if this has anything to do with the fact that this test uses detached async actors which block/wakeup from different drivers (see `test_utils.Semaphore`)

**Comment by rkooo567** [comment]
It is highly likely there is some race condition from GCS sides.
