### ISSUE TITLE
Handling thousands of jobs using ray

### ISSUE THREAD

**Issue by darthveda-ai** [ray-project/ray#9507]
[autoscaler]

### If thousands of jobs are to be executed, would the recommendation be

- To have a single ray autoscale cluster and submit all thousand jobs to it. With my given understanding of ray, for this to work in kubernetes, launch a autoscale ray cluster using `ray up cluster.yaml` command and submit the jobs to this ray cluster using `kubectl create -f job.yaml`. Couple of questions with this approach
  - Is this how Ray was envisioned to be used?
  - With the single Ray Head node, would the execution of thousands of jobs become a bottleneck?
  - How does the RAY_HEAD_NODE_IP or RAY_HEAD_SERVICE_HOST discovery work for a submitted job?
- To launch a ray cluster for each distributable job and delete it, on completion of the job? Is there any restrictions w.r.t this approach?

**Comment by richardliaw** [comment]
The best way to do this is to have different jobs correspond to different Ray clusters (for now).
