### ISSUE TITLE
[core] How to manage the number of actors of a given kind inside of a cluster

### ISSUE THREAD

**Issue by kivo360** [ray-project/ray#9529]
I'm creating actors from different processes. I want to ensure I don't over subscribe the number of ray actors inside of a cluster. I would create an actor based on number of CPUs in a cluster. How do I ensure I don't create too many actors from separate processes.

**Comment by richardliaw** [comment]
Hey @kivo360, can you give more details about what you're doing? i.e., do you know roughly how many ray actors you want to create (per separate "process")?

**Comment by kivo360** [comment]
Okie dokie. Let me clarify. I love lists because they help me organize my thoughts:
1. Assuming that we're using python we'll call a separate process a newly initiated interpreter. That can be either done through the `multiprocessing` module or by starting the same program elsewhere.
2. We're going to assume that we call `ray.init()` at the beginning if each process as well as initialize the actors.

Example:

```py
import ray
ray.init()

class ActorManager(object):
    ACTORS = None

    def __init__(self):
        pass

    
    def init_actors(self):
        if self.ACTORS is None:
            # Actor doesn't exist yet. Initialize them
            self.ACTORS = [
                AllocationActor.remote() for x in range(CPU_NUM // 2)
            ]

    def get_actors(self):
        # Initialize actors if you haven't already
        self.init_actors()
        return random.choice(self.ACTORS)
try:
    actors = ActorManager()
    actors.init_actors()
    # Do arbitrary work here
except Exception:
    ray.shutdown()
```

`ActorManager` is declared in a module so it's globally accessible much like the ray has a global object that's accessed through the main methods.

The actors themselves are referred to using a local variable. If I started the same instance again, I'd immediately allocate more actors, even if the prior ones weren't `shutdown`. 

1. How to I ensure there's a limit to the number of actors of a given class as I instantiate more interpreters? 
2. Would I create some kind of reference list that would exist between the new interpreters?

**Comment by richardliaw** [comment]
Got it! Can you tell me a bit more about the user application that you're trying to build using this architecture? (it would help me to get a bit more context!)

> Would I create some kind of reference list that would exist between the new interpreters?

2. You can maybe use a "detached actor" - https://docs.ray.io/en/master/advanced.html#detached-actors

**Comment by kivo360** [comment]
Oh, this is for trading software. I split a single environment between parts and connected them together again using [kafka](https://faust.readthedocs.io/en/latest/).  The intention is to have a long-running fault-tolerant pipeline that I can replay later if I needed to. I use event sourcing so I can replay events later if I needed to, and I want to use Ray and RLLib combined to train an agent completely out of order so I scale the number of assets I'm monitoring.


The overall pipeline is finished and I'm now working on using the [asyncio features](https://medium.com/distributed-computing-with-ray/scaling-python-asyncio-with-ray-aaf42ee03a8e) you all have in tandem with kafka to scale up what's there. 

It uses the partitions inside of Kafka to work. To utilize those partitions you need to have separate processes running.

**Comment by richardliaw** [comment]
Got it. It's probably preferable to make those interpreter sessions/processes just ray actors. 

To go back to your original question:

> How to I ensure there's a limit to the number of actors of a given class as I instantiate more interpreters?

You can probably use something like Custom Resources to do this: https://docs.ray.io/en/master/actors.html#resources-with-actors

**Comment by kivo360** [comment]
What do you mean when you say that? Remove Kafka?

**Comment by kivo360** [comment]
Closing due to lack of response. I'll just experiment.

**Comment by rkooo567** [comment]
> How to I ensure there's a limit to the number of actors of a given class as I instantiate more interpreters?

You can ensure this by allocating resources to each actor. For example,

1. Start Ray on a node you want to connect. (Note command given here is not exactly accurate. You might need more options to start it correctly).
```
ray start --num-cpus=16 # This means this node will use max 16 cpus.
```

And assign 1 cpu for each actor. In this way, you can only create num-cpus actors in the cluster. 
```python3
@ray.remote(num_cpus=1)
class AllocationActor:
    pass

allocation_actor = AllocationActor.remote()
```
This now requires 1 cpu to be created. If you create more than num-cpus in your cluster, it will be pending creation.

> Would I create some kind of reference list that would exist between the new interpreters?
Ray uses ownership model to manage lifecycle of actors. That says actor's lifetime is bound to the creator of actors. 

That means when you run multiple drivers, there's no way to pass actor handles around to each other. In this case, you can use detached actor (which Richard showed you) to access actors created by other drivers.
