### ISSUE TITLE
[Rllib] Random policy masking non-allowed actions

### ISSUE THREAD

**Issue by spig95** [ray-project/ray#9536]
Hello everyone,

I wanted to implement a random policy masking the non-allowed actions, modifying this implementation (https://chuacheowhuan.github.io/RLlib_rand_policy/).

My code for `compute_actions` inside `Policy` is the following (`action_mask_list` is the core part, the one of which I am unsure):

```Python

def compute_actions(self, obs_batch, state_batches=None, prev_action_batch=None, prev_reward_batch=None, **kwargs):
        mask_len = self.action_space.n

        # I assume that the first mask_len elements are the action mask (which is the case for me, but is it general?)
        action_mask_list = [obs[: mask_len] for obs in obs_batch]
        
        actions_list = []
        for mask in action_mask_list:
            allowed_actions = [idx for idx, allowed in enumerate(mask) if allowed]
            actions_list.append(random.sample(allowed_actions)) # Sample only among the allowed ones

        return np.array(actions_list), [], {} 
```

Here I rely on the fact that `obs_batch` is a flattened version of the observation given by the environment, which is of the from

```Python

obs = {"real_obs": real_obs, "action_mask": action_mask}

```

I have tried to avoid the line

```Python

action_mask_list = [obs[: mask_len] for obs in obs_batch]

```
relying on `restore_original_dimensions` or `_unpack_obs` (importing them from `ray.rllib.models.modelv2`), but I was not able to retrieve the observations divided in action mask and real observation.

This implementation is working smoothly in my case. However:

- Do you think this is the proper way to define a random policy taking only allowed actions?
- In particular, is it general? I am unsure that each element in `obs_batch` will have the action mask at the beginning. I'd like to know  if taking the action mask as `obs[: mask_len]` is robust to changes in the environment.

Thanks!

**Comment by sven1977** [comment]
It's entirely up to your environment to define rules about masked actions and how these show up in the observations.
You can take a look at the QMIX example: `rllib/examples/two_step_game.py --run QMIX` to check how the TwoStepGame env does this. QMIX internally makes sure then that actions that are masked are never sampled (neither in the random (epsilon) case, nor from the Q-values (which are -inf for masked actions)).

**Comment by spig95** [comment]
I am not sure this is what you meant, however, looking at the `rllib/agents/qmix/qmix_policy.py`, I found a call to `_unpack_obs`
with `tensorlib=np`. I think this is what I needed! I was calling it with `tensorlib=tf` and I was having problems.

Now I can use it, and the result is an ordered dict with the keys defined inside my environment. So, I defined a random policy like this:

```python
    from ray.rllib.models.modelv2 import _unpack_obs

    @override(Policy)
    def compute_actions(self, obs_batch,  **kwargs):
       
       # Working call to _unpack_obs
        unpacked_obs = _unpack_obs(
            np.array(obs_batch, dtype=np.float32),
            self.observation_space.original_space,
            tensorlib=np)

        # My environment returns observation of the form: {agent_id: {'real_obs': real_obs, 'action_mask': action_mask}}
        action_masks = unpacked_obs['action_mask']

        actions_list = []
        for mask in action_masks:
            allowed_actions = [idx for idx, allowed in enumerate(mask) if allowed]
            actions_list.append(random.sample(allowed_actions)) # Sample only among the allowed ones
        return np.array(actions_list), [], {} 
```

I think it should be a robust implementation to changes in the observation returned by the environment. As long as 'action_mask' key is present in the observation.
