### ISSUE TITLE
Garbage collecting keys in Redis.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#954]
One serious problem with long-running jobs is that the Redis servers fill up with metadata which never gets evicted. In practice, this can mean that a Ray cluster needs to be restarted periodically, which is a bit of a deal breaker.

cc @imzhenyu

**Comment by virtualluke** [comment]
Is there an easy way to tell if this is happening? Our ray cluster definitely gets in a bad state after awhile and a cluster restart seems to rectify things.

**Comment by robertnishihara** [comment]
This should only be an issue if you are submitting tons and tons of tasks. Each task probably has several hundred bytes of metadata associated with it, but let's say 1 kilobyte. Then a million tasks would require 1GB memory in Redis. So one thing to look at is how much memory Redis is using, and also think about how many tasks are being submitted.

Note that there are multiple Redis servers started (the default is 2) and you can find them with `ps aux | grep "redis-server"`.

**Comment by imzhenyu** [comment]
One problem here is that it is not easy to know whether an object is going to be used further in a long running driver, meaning we have to be very careful about removing its information (and the dependent lineage information) in redis safely. Maybe we need to introduce new API to let the developers make the final choices? Or we can reuse the garbage collection facilities in Python/Java to trigger the execution?

**Comment by robertnishihara** [comment]
A number of partial things could help, but the full solution requires more thought.

- Being able to flush keys for a given driver (this does not address the case of very long-running driver).
- Potentially allowing the GCS to spill over to disk.
- Reducing the amount of stuff that is logged to Redis in the first place (@pcmoritz has a number of ideas about this).

cc @concretevitamin

**Comment by robertnishihara** [comment]
#994 should garbage collection some (but not all) of the state associated with a driver when the driver exits.

**Comment by robertnishihara** [comment]
We'll need a better strategy down the road, but LRU is working for now.
