### ISSUE TITLE
[core] Raylets in local cluster do not log to separate files

### ISSUE THREAD

**Issue by stephanie-wang** [ray-project/ray#9553]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 0.9dev

When multiple raylets are started locally, it used to be that they would each log to a separate file, e.g., `raylet.1.out`, `raylet.2.out`, etc. Now, they all log to `raylet.out`, which makes it harder to debug.

### Reproduction (REQUIRED)

Any checked in pytest that starts a local cluster. For example, `RAY_BACKEND_LOG_LEVEL=debug pytest -sv python/ray/tests/test_advanced.py::test_wait_cluster`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by stephanie-wang** [comment]
I believe this was caused by #8885, @wuisawesome.

**Comment by clarkzinzow** [comment]
@stephanie-wang That was another regression I noticed, adding a `unique=True` argument to `get_log_file_names` [here](https://github.com/ray-project/ray/blob/5881417ec4a993194ba6d64b156ad6b5ffbca97c/python/ray/node.py#L650) should do the trick:
```
raylet_out_name, raylet_err_name = self.get_log_file_names("raylet", unique=True)
```

**Comment by stephanie-wang** [comment]
> @stephanie-wang That was another regression I noticed, adding a `unique=True` argument to `get_log_file_names` [here](https://github.com/ray-project/ray/blob/5881417ec4a993194ba6d64b156ad6b5ffbca97c/python/ray/node.py#L650) should do the trick:
> 
> ```
> raylet_out_name, raylet_err_name = self.get_log_file_names("raylet", unique=True)
> ```

Ah, nice find!

**Comment by wuisawesome** [comment]
Nice catch, I may have made this same mistake in a few places. @clarkzinzow do you want to submit a PR for this? If not, I'll try to get around to it in a week or so.

**Comment by clarkzinzow** [comment]
@wuisawesome Sure I can submit a PR for that, I'm already in this code for [another PR](https://github.com/ray-project/ray/pull/9547) so it's not much of a context switch.
