### ISSUE TITLE
[tune] Ray Cluster deployed in Kubernetes unable to sync checkpoint directories to the driver node

### ISSUE THREAD

**Issue by vish0910** [ray-project/ray#9558]
### What is the problem?

Getting the following error (Stacktrace attached):
```
2020-07-17 21:53:48,101	ERROR trial_runner.py:550 -- Trial TrainExample_fd24b_00001: Error handling checkpoint /root/ray_results/TrainExample/TrainExample_1_randomforestclassifier__n_estimators=5_2020-07-17_21-53-462l3hkjfs/checkpoint_1/
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 546, in _process_trial_save
    trial.on_checkpoint(trial.saving_to)
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trial.py", line 448, in on_checkpoint
    self, checkpoint.value))
ray.tune.error.TuneError: Trial TrainExample_fd24b_00001: Checkpoint path /root/ray_results/TrainExample/TrainExample_1_randomforestclassifier__n_estimators=5_2020-07-17_21-53-462l3hkjfs/checkpoint_1/ not found after successful sync down.
```

This is output of `ray_random_forest.py`. From investigation it looks like the checkpoint directories ie. **checkpoint_1, checkpoint_2** that were created in other nodes (workers) of the cluster do not get synced back to the driver node (from where I am running the python script).
Rest of the files in the Trial directories seem to be in sync. 

This problem is not reproducible by running it on a single-machine with a cluster started up using bare `init()`. My guess is because all the workers point to the same file-system, and thus, the `os.path.exist()` returns True (This is reference to the line of code which checks and throws the above error)

Taking a look at `validate_save_restore()` to validate a Trainable, I have written a bare-bone script which proves that `checkpoint` directories are not synced across workers.

The stacktrace from `checkpoint_validation_failed.py`
```
Traceback (most recent call last):
  File "code/checkpoint_validation_failed.py", line 115, in <module>
    _main()
  File "code/checkpoint_validation_failed.py", line 94, in _main
    print(f"VALIDATE TRAINABLE CLASS: {validate_save_restore(TrainExample)}")
  File "code/checkpoint_validation_failed.py", line 67, in validate_save_restore
    restore_check = ray.get(trainable_2.restore.remote(old_trainable))
  File "/opt/conda/lib/python3.6/site-packages/ray/worker.py", line 1526, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FileNotFoundError): ray::TrainExample.restore() (pid=2704, ip=172.17.0.8)
  File "python/ray/_raylet.pyx", line 471, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 424, in ray._raylet.execute_task.function_executor
  File "/opt/conda/lib/python3.6/site-packages/ray/tune/trainable.py", line 444, in restore
    with open(checkpoint_path + ".tune_metadata", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/ray_results/2020-07-17_21-43-17dbvo01tp/checkpoint_3/.tune_metadata'
command terminated with exit code 1
```

Here, Worker X is trying to restore checkpoint created by Worker Y.

*Ray version and other system information (Python version, TensorFlow version, OS):*

Setup:
- Ray cluster running in K8s.
- Ray version
`pip list | grep ray
ray 0.9.0.dev0`
- Docker image: 
`
REPOSITORY                                                       TAG                 IMAGE ID            CREATED             SIZE
rayproject/autoscaler                                            latest              3f8d747cb8af        7 days ago          5.25GB
`

Playing with `sync_to_driver`, `sync_on_checkpoint` parameters did not help.

Thanks!

### Reproduction (REQUIRED)
Step 1. Spin-up a Ray cluster using `ray-cluster.yaml` in a namespace called `ray`. ie 
1.  `kubectl create -f ray-namespace.yaml`
2.  `kubectl apply -f ray-cluster.yaml`

Step 2. Copy the python script to any worker node.

1. `kubectl -n ray get pods`.
2. Copy WORKER_1_POD_NAME
3. Exec into pod `kubectl -n ray exec -it <WORKER_1_POD_NAME> -- bin/bash`
4. `mkdir code`
5. Copy the python script `kubectl -n ray cp checkpoint_validation_failed.py  <WORKER_1_POD_NAME>:/code/checkpoint_validation_failed.py`
6. Exit pod
7. Execute script `kubectl -n ray exec <WORKER_1_POD_NAME> -- bin/bash -c "python code/checkpoint_validation_failed.py`

You can do the same steps to run `ray_random_forest.py`.
[ray_issue_related_files.zip](https://github.com/ray-project/ray/files/4940566/ray_issue_related_files.zip)

The above zip contains:
1. ray-cluster.yaml
2. ray-namespace.yaml
3. checkpoint_validation_failed.py
4. ray_random_forest.py

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Do you have an NFS for your kubernetes cluster? That might save you a lot of trouble.

**Comment by vish0910** [comment]
Hello @richardliaw,

Thank you for a quick reply.

No, I do not have NFS for the cluster. Does it have to be a NFS? How does ray sync files like
1. events.out.tfevents.1595022826.ray-worker-6d9f6b9b8d-g4zvk
2. params.json
3. params.pkl
4. progress.csv
5. result.json

But not `checkpoint_1`, `checkpoint_2` etc.?

**Comment by richardliaw** [comment]
The files are actually generated on the driver, not on the node. Do you have access to S3? S3 could work too.

**Comment by vish0910** [comment]
Okay. So what gets synced on `sync_on_checkpoint`?

sync_on_checkpoint (bool) – Force sync-down of trial **checkpoint** to driver. If set to
False, checkpoint syncing from worker to driver is asynchronous and best-effort. This does
not affect persistent storage syncing. Defaults to True. 

In the above documentation snippet I am interpreting **checkpoint** as the `checkpoint_N` directories described above. 

Would the suggested S3 solution involve implementing DurableTrainable rather than Trainable?
Also I wanted to clarify, is the above issue a bug in Ray Tune and a network/cloud storage a work-around for it?

**Comment by richardliaw** [comment]
Checkpoints (directories) are synced on sync_on_checkpoint, yep.

The above is just a limitation of our file-transfer mechanism; we use rsync to move files between VMs, but I think that mechanism breaks down on kubernetes. 

The two approaches to workaround this limitation are to use 1. a networked storage or 2. to implement your own file-transfer protocol (check out `sync_to_driver`). 

Does that make sense? Let me know if you have any further questions!

**Comment by vish0910** [comment]
Thank you Richard for this clarification.

Upon searching more, I found this: https://serverfault.com/questions/741670/rsync-files-to-a-kubernetes-pod
I see similar solution applied to `KubernetesCommandRunner` in Ray. Maybe we can do the same for sync-checkpoint mechanism to resolve this issue. Or, we just implement it as a custom file-transfer protocol and make it part of the pallet. 

On a side note, I have taken your suggestion to use a NFS. It has unblocked me from aggregating all my checkpoints. 

Thanks once again.

**Comment by richardliaw** [comment]
Great! yeah, KubernetesCommandRunner is what we will want to use. More than happy to accept a PR if you want to take a quick pass! 

Otherwise, we'll try to get to this in the next couple of weeks.

**Comment by vish0910** [comment]
I spent sometime last-week to understand if I can fix it, but for me it was not a going to be a quick pass. So I will defer it to the team. Thanks once again Richard. :)

**Comment by Carterbouley** [comment]
Hi Guys,

I am currently using a cluster and similarly want to save checkpoints. I didn't fully understand the conversation above, could someone point me in the direction of documentation or advice on a work-around to fix the above problem?
