### ISSUE TITLE
[rllib] Train script overwrites framework field in experiment config argument

### ISSUE THREAD

**Issue by konradkalita** [ray-project/ray#9568]
[rllib]

### What is the problem?

Framework setting passed to training script via config argument is ignored, because training script uses separate arguments for this field (`--torch`, `--eager`). If none of these args is passed to the script the framework is set to `tf`, regardless of options passed in `--config` argument.

### Expected behavior

Script should use default value for `framework` field only if it is not already present in `config` dict (it can be passed as cmd argument or be loaded from file).

### Reproduction (REQUIRED)
Run `rllib train --run DQN --env CartPole-v0 --config "{\"framework\": \"tfe\"}"` - script uses `tf` instead of `tfe`

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
This PR should fix it. https://github.com/ray-project/ray/pull/9572
To patch for now (until this is merged): Remove the entire else block in line 188 (ray/rllib/train.py). This way, it'll:
1) Use torch iff --torch
2) Use tf-eager iff --eager
3) Use config framework (or default `tf` if not specified in config).
