### ISSUE TITLE
[tune] Do not change working directory to logdir

### ISSUE THREAD

**Issue by AlkaidCheng** [ray-project/ray#9571]
### What is your question?
By default, Tune will change the current working directory when calling tune.run to the logging directory which is not very desirable if one has relative paths in the training script. Is it possible to disable it?

*Ray version and other system information (Python version, TensorFlow version, OS):*

**Comment by richardliaw** [comment]
As a quick workaround, you could `os.chdir` back to the preferred directory at the start of your training script?

**Comment by mi-lad** [comment]
The documentation is clear about this in case of class-based API but I think if you're using functional API the directory still changes to what you'd pass `local_dir` in `tune.run`. It'd be good if this was also made clear in the documentation.

**Comment by mi-lad** [comment]
Perhaps each tune process could at least define an environment variable set to original path on that node. That way I can safely convert my relative paths to absolute ones when running in a tune session.

**Comment by richardliaw** [comment]
Hmm, is this generally a very unintuitive design decision?

**Comment by yanghoonkim** [comment]
I have also suffered from the issue and agree with @AlkaidCheng

**Comment by richardliaw** [comment]
@xwjiang2010 @krfricke if you have the chance, I think the suggestion of setting an environment variable to the original path  makes sense as a first workaround.

**Comment by richardliaw** [comment]
I've assigned this as P1 as it has become one of the top voted issues on the entire repository.

**Comment by xwjiang2010** [comment]
Thanks for raising the issue.

Dumb question, why do we want to have working_dir == log_dir? Is it to protect against the scenario where we have multiple trials scheduled on the same physical node and we are, for example, downloading some data to `~/data` in training script? We don't want them to step on each other? (in this case, worker1 will download to ~/ray_results/exp/trial000 while worker2 will download the same data to ~/ray_results/exp/trial001. They are not interfering with each other)

If this is the rationale behind this design choice, changing working_dir == project_dir could easily let users shoot themselves on the foot. i.e. they may not fully realize that there can be multiple workers on the same node.

Thoughts?

**Comment by Chunpai** [comment]
Agreed with AlkaidCheng. It is annoying when the code uses relative paths.

**Comment by krfricke** [comment]
To follow up from @xwjiang2010, there are two main reasons why we switch to a per-trial directory:

1. If trial write artifacts, we want to avoid conflicts (see @xwjiang2010 answer - if both write to "artifact.bin", they would overwrite this files).
2. In distributed settings, we cannot guarantee that the working directory from the driver script exists on the remote host. But we can guarantee that the trial directory exists.

Because of this, we will keep the functionality as is with switching to a trial-specific directory. However, I agree with @richardliaw that we should expose the original working directory via an environment variable. Users can then use e.g.

```
def train(config):
    os.chdir(TUNE_ORIG_WORKING_DIR)
    ...
```

to switch back to their original working directory.

**Comment by worldveil** [comment]
I also hit this issue and was hung up for a while on it.

Could we add this (above) snippet to the docs too, along with a small reason for the rationale? 

the rationale is good, but when you're just trying to read a checkpoint or something, this feels annoying as a user to get caught on this.

**Comment by aoot** [comment]
For those who stumbles on this issue and unsure where the documentation is at, like me, [here](https://docs.ray.io/en/latest/tune/api/doc/ray.tune.Trainable.html) is the documentation.
