### ISSUE TITLE
[rllib] Driver process spawns evaluation environment even when not used

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9576]
### What is the problem?

The driver process spawns an evaluation environment even when not used. When `evaluation_interval: None`, no evaluation environment should be created, but is currently not the case. This bug can cause resource issues when the environment is expensive to run.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
cc @sven1977

**Comment by ericl** [comment]
I don't think this is the case, we only spawn evaluation workers when evaluation_interval is set: https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py

Probably you're just seeing the env created for the local worker. Reset() will never be called on this env though, so you can just defer expensive initialization to the first reset.

**Comment by juliusfrost** [comment]
> I don't think this is the case, we only spawn evaluation workers when evaluation_interval is set: https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py
> 
> Probably you're just seeing the env created for the local worker so we can get the action and obs space. Reset() will never be called on this env though, so you can just defer expensive initialization to the first reset.

The environment that I am working with is expensive to create and hogs resources when running. The problem is that even if the environment is not used (reset and step is not called), it will still take resources in the background. Is there a reason for keeping this around other than the spaces? You could possibly clone the spaces for later access but terminate the environment instance to save resources.

**Comment by ericl** [comment]
You can defer env init until reset is called, to avoid using resources at
all. We could potentially fix the interface to allow action spaces etc to
be passed in separately, though it is more cumbersome for the common case.

**Comment by juliusfrost** [comment]
Thanks for your quick response!

I am not the creator of the environment so I don't have control over initialization. I doubt that the developers of the environment would want to change the initialization process as it is very intricate. I have not come across the design pattern of leaving initialization to reset() before and I'm uncertain that other users would find it intuitive to keep this in mind when creating custom environments. One example when this is not feasible is when the action/observation space is tied to expensive initialization and cannot be decoupled. 

A possible solution that focuses on compatibility would be to leave the environment initialization completely to the workers used for training and evaluation and not the local worker. If you need the action/observation space information, then you refer those workers for access. 
For example, assume there are 2 remote workers, 1 env per worker, and evaluation_interval is None, then 1 of the remote workers initializes an environment to get information for things like model initialization (although I'm not sure when these things exactly happen), after that the workers initialize the rest of the environments as necessary for sampling. Alternatively, initialization could happen simultaneously across workers with caution.  
Although this may seem complicated, I think that mitigation like this is sufficiently necessary as one cannot always make assumptions on the environment design and resource consumption. I appreciate the feedback and I am willing to help with any of the implementation!

**Comment by ericl** [comment]
Note that you can always wrap the environment (create self.env on reset,
and just forward the step calls to self.env), so with a trick like this
initialization can be deferred.

I agree with your plan though, maybe we can create a fake env locally or
something that grabs the action spaces from the remote workers, and only
creates the real env on reset.

**Comment by sven1977** [comment]
This has been addressed in the master branch. The driver process now does not create an env anymore, if not needed.
It'll only create an env, iff:
a) num_workers=0 (driver has to do the sampling)
OR
b) config[create_env_on_driver] = True

Closing this issue. Please feel free to re-open, should this not address your problem.

**Comment by sven1977** [comment]
Here is the PR:
https://github.com/ray-project/ray/pull/11307
