### ISSUE TITLE
Specifying Actor placement?

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#959]
It would be nice to allow for a feature where developers can specify actor placement. For example, in A3C, all actors for the runners should be placed on the same node as the parameter server, or else performance suffers.

**Comment by robertnishihara** [comment]
We will likely introduce some label-based scheduling (e.g., see #695). E.g., a local scheduler can be started with a set of user-defined labels, and then remote functions and actors can be constrained to run on nodes with certain labels.

Do you think that would that be sufficient for this use case? Or is locality a cleaner abstraction in this case?

**Comment by richardliaw** [comment]
#761 doesn't seem to be quite enough, but label-based scheduling looks pretty neat. However, it might become a little awkward (but still usable), as I could see myself writing something programmatically like such:

Given nodes with ip address or some label 1, 2, 3,
```
class Runner():
    # do something

node_ips = [1, 2, 3]
for ip in node_ips:
   RemoteRunner = ray.remote(Runner(), custom_label=ip)
   RemoteRunner.remote(...)
   ...
```

**Comment by robertnishihara** [comment]
Possible with custom resources, though still not convenient for specifying colocation.
