### ISSUE TITLE
[tune] Memory crash

### ISSUE THREAD

**Issue by mike179179** [ray-project/ray#9591]
### Ray shuts down, workers crash with [Error 111 connecting to <head_node_ip_address>:6379. Connection refused.]

ray 0.8.0; python 3.6.7; ubuntu 18.04

### Setup
I run my script on a cluster of 4 machines. (Each has 1.3 TB RAM, 1024Gb Swap, 3 GPU, 24 CPU).
Start ray on a head node via 
`ray start --num-cpus=22 --num-gpus=3 --head --redis-port 6379 --temp-dir='/home/<username>/ray_temp_dir' --object-store-memory=$((450 * 1024 * 1024 * 1024)) --redis-max-memory=$((650 * 1024 * 1024 * 1024)) &`

on other nodes:
`ray start --num-cpus=22 --num-gpus=3 --redis-address=<head_node_ip_address>:6379 --temp-dir='/home/<username>/ray_temp_dir' --object-store-memory=$((450 * 1024 * 1024 * 1024)) --redis-max-memory=$((650 * 1024 * 1024 * 1024)) & `

I run a hyper parameters optimization script (on my head mode), my dataset is ~120GB, each worker uses 1 GPU and 4 CPU.
I operate with 12 concurrent workers.

Basically what happens is: 
1. workers on my head node start up (3 workers, using 360 GB RAM)
2. memory usage on my head node starts rising as the state is being transferred to other 3 nodes
3. after a couple of minutes, ray has used up all 1.34TB RAM and 400GB Swap, and script suddenly crashes 

Tracebacks are:
`redis.exceptions.ConnectionError: Error 111 connecting to <head_node_ip_address>:6379. Connection refused.`

and the following is taken from error.txt
```
  File "python/ray/_raylet.pyx", line 815, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 171, in ray._raylet.check_status
ray.exceptions.RayletError: The Raylet died with this message: [RayletClient] Connection closed unexpectedly.
```

Also:
`dmesg -T` shows:
`redis-server[3976]: segfault at 28 ip 000000000043df00 sp 00007ffd11a88db0 error 4 in redis-server[400000+189000]`

### Conclusion
I believe the crash is memory related as the script works perfectly when I use a smaller dataset. 
I might be missing something obvious, but I don't really understand, why ray seems to eat up so much memory.
Is there a way to still run 12 concurrent workers, or I will have to lower this number?

I can attach ray logs and netdata screenshots if needed.

**Comment by richardliaw** [comment]
Can you try the following:

1. updating to 0.8.6 or the latest? 
2. Don't set the redis max memory? Redis should never be using more than a couple hundred mb of memory.
3. use ray.put/ray.get to move your dataset around?
