### ISSUE TITLE
rllib + tensorflow 2.2.0: eager execution of ray::tune fails when local_mode=True 

### ISSUE THREAD

**Issue by matdoering** [ray-project/ray#9592]
### What is the problem?

After updating to tensorflow 2 and updating to ray 0.86 calls to ray::tune started failing for PPO when local_mode was activated. This is because, in local_mode, eager execution seems to be active. As a consequence, `RolloutWorker.py` does not generate a tensorflow session here:

https://github.com/ray-project/ray/blob/bc842a7888100de9e7689e3f7d82486dbd45adc5/rllib/evaluation/rollout_worker.py#L386

It seems that currently there is some work being done in cleaning things up in this sector (tf1, tf differentiation), which is why I'm not providing a reproducible example. It would be great, if you could ensure that the local mode works for Tensorflow 2 again.

A quick fix for the problem is to disable eager execution:

```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```

Interestingly, setting `framework: "tfe"` in the `tune` configuration also does away with the problem

*Ray version and other system information (Python version, TensorFlow version, OS):*

* Python 3.7.6 w/ tensorflow 2.2.0, ray 0.86

### Reproduction (REQUIRED)
- Run tune with PPO using local_mode and Tensorflow 2.2.0

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
hey @sven1977 can you take a look? this might be a bigger issue

**Comment by ericl** [comment]
Since local mode runs everything in one process, it's difficult to control the TF behaviour (it will basically be set to whatever tf was configured at). So basically this isn't supported.

**Comment by eicnix** [comment]
This issue still is still current to this day and cost me a bit of time to figure out. It would be great there was a warning when the combination of `local_mode=True` and `framework=tfe` to expect this behavior.
