### ISSUE TITLE
questions about ASHA and TensorBoard

### ISSUE THREAD

**Issue by junliangyu96** [ray-project/ray#9603]
I'm using ASHA scheduler. 

```
scheduler = AsyncHyperBandScheduler(
        time_attr="training_iteration",
        metric="mean_accuracy",
        mode="max",
        grace_period=10,
        max_t=400,
        
    )
    
analysis = tune.run(cv_wrapper, num_samples=256, scheduler=scheduler, config=parameters, resources_per_trial={'cpu':1})

```
cv_wrapper is my function.

The testing result of every iteration becomes very confusing..

it directly start with

(pid=20695) Average loss in 74th epoch was : 1.1255990920698336
(pid=20695) Accuracy was : 0.8181818181818182
(pid=21373) Average loss in 73th epoch was : 0.8030315004314882
(pid=21373) Accuracy was : 0.7636363636363637
(pid=20691) Average loss in 74th epoch was : 1.0108404824890542
(pid=20691) Accuracy was : 0.8181818181818182
(pid=20684) Average loss in 75th epoch was : 1.3658368397310696
(pid=20684) Accuracy was : 0.6545454545454545
(pid=20706) Average loss in 75th epoch was : 1.03848163095844
(pid=20706) Accuracy was : 0.7818181818181819
(pid=20720) Average loss in 247th epoch was : 0.44879652139888715
(pid=20692) Average loss in 72th epoch was : 0.8866115418991108
(pid=20692) Accuracy was : 0.7818181818181819
(pid=20720) Accuracy was : 0.7090909090909091
(pid=20689) Average loss in 72th epoch was : 1.4077228518952936
(pid=20689) Accuracy was : 0.6909090909090909
(pid=20695) Average loss in 75th epoch was : 1.1157517298697246
(pid=20695) Accuracy was : 0.8181818181818182
(pid=21373) Average loss in 74th epoch was : 0.810408315428832

is it running different task together? And to my understanding, ASHA should gradually drop off poorly performing configs. But how can I know which is dropped? there is not any information about where I'm at. 

![Screenshot from 2020-07-20 22-36-53](https://user-images.githubusercontent.com/64705790/88017004-8ff2f600-cad9-11ea-8de4-74a98157bafa.png)
And this is my tensorboard. After running for 30 minutes, it shows nothing but this. How should i understand it..does it include all the tasks I ran today?

**Comment by richardliaw** [comment]
@junliangyu96 did you fix the issue?

**Comment by junliangyu96** [comment]
yes. I changed the way of cross validation. I trained all the sub models at
the same time and report together.

I have another problem. Is there a way to return something from target
function? Tune.run can only return analysis or trial names. But if i
trained a model and i want to return it, what should i do? is there any
other functions that can help me?

Thanks
