### ISSUE TITLE
zsh:4: command not found: cp

### ISSUE THREAD

**Issue by wumuzi520** [ray-project/ray#9608]
### What is the problem?
![image](https://user-images.githubusercontent.com/2016670/88035509-da758080-cb74-11ea-87ac-e010e3289c57.png)

The `path` variable is reserved in zsh, which is bind with `PATH`, so the `path` should not be used as a common variable in the script.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by mehrdadn** [comment]
Thanks for reporting. I'll change it, but I don't believe we actually support zsh yet; these are meant to be Bash scripts—there are a number of incompatibilities (like brackets) that we've never accounted for. So you

**Comment by wumuzi520** [comment]
> Bazel is supposed to call Bash

My OS is `macOS Catalina` which make zsh as a default shell tool. So I think it will block many developers.
