### ISSUE TITLE
Ray error logs should be printed to stdout 

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#9616]
### What is the problem?

c++ errors should be printed to the driver's stdout but aren't. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Put a `RAY_LOG(ERROR) << "dfasdf";` in `CoreWorker::ExecuteTask` and in `NodeManager::HandleWorkerLeaseRequest`. Neither will will be printed. 

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by wuisawesome** [comment]
@mehrdadn I think this is caused by this change. https://github.com/ray-project/ray/blob/dcec26ac7badf0bb224773a4c09e4d9b70ca0e43/src/ray/util/logging.cc#L285

**Comment by mehrdadn** [comment]
Thanks! I'll take a look.

**Comment by richardliaw** [comment]
Shouldn't they go to stderr?

**Comment by wuisawesome** [comment]
The existing behavior is that raylet's stderr is redirected to the driver's stdout. The behavior has been that way for quite some time (years), but there is some unused code that suggests that it wasn't always this way...
