### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by semiter1** [ray-project/ray#9637]
### What is your question?

Hi I am new to Ray and TensorFlow. I am trying to parallelize a simple neural network problem. When the training data is small (300 MB), I had no problem running, although I still get the following warning: 

> 2020-07-22 10:18:09,186	WARNING worker.py:1047 -- Warning: The remote function __main__.nn1 has size 749505929 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.

When I use a larger training data (~2GB), the program stopped with the following error message: 

> 2020-07-22 10:18:09,186	WARNING worker.py:1047 -- Warning: The remote function __main__.nn1 has size 749505929 when pickled. It will be stored in Redis, which could cause memory issues. This may mean that its definition uses a large array or other object.
> Traceback (most recent call last):
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\connection.py", line 700, in send_packed_command
>     sendall(self._sock, item)
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\_compat.py", line 8, in sendall
>     return sock.sendall(*args, **kwargs)
> 
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-38-71ac0ae4d4d4>", line 3, in <module>
>     ids = [nn1.remote(Xtrain_id, ytrain_id,  Xtest_id, lbd_list_id,lr_list_id, ne, nl, nlr) for ne in range(1)]
> 
>   File "<ipython-input-38-71ac0ae4d4d4>", line 3, in <listcomp>
>     ids = [nn1.remote(Xtrain_id, ytrain_id,  Xtest_id, lbd_list_id,lr_list_id, ne, nl, nlr) for ne in range(1)]
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\ray\remote_function.py", line 95, in _remote_proxy
>     return self._remote(args=args, kwargs=kwargs)
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\ray\remote_function.py", line 176, in _remote
>     worker.function_actor_manager.export(self)
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\ray\function_manager.py", line 152, in export
>     "max_calls": remote_function._max_calls
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\client.py", line 3023, in hmset
>     return self.execute_command('HMSET', name, *items)
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\client.py", line 877, in execute_command
>     conn.send_command(*args)
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\connection.py", line 721, in send_command
>     check_health=kwargs.get('check_health', True))
> 
>   File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\redis\connection.py", line 713, in send_packed_command
>     (errno, errmsg))
> 
> ConnectionError: Error 10054 while writing to socket. An existing connection was forcibly closed by the remote host.

Can someone please help how I can resolve this issue? Thanks. 

My code is below: 

```
ray.shutdown()
ray.init(ignore_reinit_error=True, num_cpus=10, memory=28000 * 1024 * 1024, object_store_memory=14000*1024*1024)

@ray.remote
def nn1(Xtrain, ytrain, ne):
    import tensorflow as tf
    from tensorflow import keras
    from tensorflow.keras.optimizers import Adam #maybe put this at the top of your file
    import os

    #tf.random.set_seed(ne)
    tf.random.set_random_seed(ne)
    lbd = 0.01
    lr  = 0.01
    print(lbd, lr)
    NEP =1
    batch_size= 10000
    ptc = 5  
    early_stopping_cb = keras.callbacks.EarlyStopping(patience=ptc, restore_best_weights=True)
  
    model = keras.models.Sequential([  
    keras.layers.Dense(32,activation='relu', input_shape=Xtrain.shape[1:], kernel_initializer='he_normal',
                       kernel_regularizer = keras.regularizers.l1(lbd)),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1, activation='linear',  kernel_initializer='he_normal',kernel_regularizer = keras.regularizers.l1(lbd))
    ])

    opt = Adam(lr=lr)  
    model.compile(optimizer=opt, loss='mse')

    history = model.fit(Xtrain, ytrain, epochs=NEP, validation_data=(Xvalid, yvalid),
                        callbacks=[early_stopping_cb], batch_size = batch_size)

    return os.getpid()

Xtrain_id = ray.put(Xtrain)
ytrain_id = ray.put(ytrain)

ids = [nn1.remote(Xtrain_id, ytrain_id, ne) for ne in range(10)]
```
*Ray version and other system information (Python version, TensorFlow version, OS):*

Python version: 3.7.7
TensorFlow version: 1.14.0
OS: windows 10 
RAM: 76 GB
Logical processors: 24

**Comment by richardliaw** [comment]
cc @mehrdadn it looks like somehow data that is supposed to go to Plasma is ending up in Redis

**Comment by semiter1** [comment]
Thanks, richardliaw. Is there anything I can do about it?

**Comment by richardliaw** [comment]
@mehrdadn can help you, he's the windows expert :)

**Comment by semiter1** [comment]
> )

Got it. Thanks!

**Comment by mehrdadn** [comment]
Thanks for reporting! I'll try to see if I can repro. Just to confirm: how much free RAM do you have? And how big of a pagefile (swap)?

Also, if you have Linux running (WSL?) and can occur the same code doesn't trigger that behavior on there, that would be great. But if not then no worries.

**Comment by mehrdadn** [comment]
Okay thanks, I'll take a look. (Btw I deleted your email reply from your answer; it had your personal email address.)

**Comment by mehrdadn** [comment]
@semiter1 Your repro doesn't run unfortunately. You haven't imported `ray` (which I did myself) but I'm not sure what to set `Xtrain` and `ytrain` to in order to reproduce the issue. If you could post a self-contained repro script that would be great. Thanks!
```
Traceback (most recent call last):
  File "temp.py", line 36, in <module>
    Xtrain_id = ray.put(Xtrain)
NameError: name 'Xtrain' is not defined
```

**Comment by semiter1** [comment]
I figured out the issue. I used Xvalid and yvalid in the validation_date for early stopping, but I never convert them using ray.put, so ray is creating a copy of these two variables for each process. However, it is not intuitive that why it creates an error "[WinError 10054] An existing connection was forcibly closed by the remote host. "

Many thanks for your help, @mehrdadn!

**Comment by mehrdadn** [comment]
Ah thanks for sharing the info! Glad you solved it.
