### ISSUE TITLE
--redis--shard-ports unknown argument

### ISSUE THREAD

**Issue by Vysybyl** [ray-project/ray#9648]
### What is the problem?

Ubuntu 20.04
Python 3.8
Ray 0.8.6

### Reproduction (REQUIRED)

`ray start      --head      --port=6379      --redis--shard-ports=6380      --object-manager-port=8076`

will fail, but

`ray start --help`

will list --redis--shard-ports among possible arguments

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
You have a typo - `--redis-shard-ports` not `--redis--shard-ports`
