### ISSUE TITLE
[GCS]Java testcase crash

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#9649]
### What is the problem?
Testcase is MultiThreadingTest.

Stack: [0x0000700002740000,0x0000700002840000],  sp=0x000070000283e190,  free space=1016k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcore_worker_library_java.dylib+0x18ccf0]  _ZNSt3__113unordered_mapIN3ray7ActorIDENS_8functionIFvRKNS3_IFvNS1_6StatusEEEEEEENS_4hashIS2_EENS_8equal_toIS2_EENS_9allocatorINS_4pairIKS2_SA_EEEEEixERSH_+0x70
C  [libcore_worker_library_java.dylib+0x18c500]  _ZN3ray3gcs29ServiceBasedActorInfoAccessor14AsyncSubscribeERKNS_7ActorIDERKNSt3__18functionIFvS4_RKNS_3rpc14ActorTableDataEEEERKNS6_IFvNS_6StatusEEEE+0x3b0
C  [libcore_worker_library_java.dylib+0x2dcef]  _ZN3ray12ActorManager14AddActorHandleENSt3__110unique_ptrINS_11ActorHandleENS1_14default_deleteIS3_EEEEbRKNS_6TaskIDERKNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_3rpc7AddressERKNS_7ActorIDERKNS_8ObjectIDE+0x15f
C  [libcore_worker_library_java.dylib+0x2e527]  _ZN3ray12ActorManager17AddNewActorHandleENSt3__110unique_ptrINS_11ActorHandleENS1_14default_deleteIS3_EEEERKNS_6TaskIDERKNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKNS_3rpc7AddressEb+0x107
C  [libcore_worker_library_java.dylib+0x45c90]  _ZN3ray10CoreWorker11CreateActorERKNS_11RayFunctionERKNSt3__16vectorINS4_10unique_ptrINS_7TaskArgENS4_14default_deleteIS7_EEEENS4_9allocatorISA_EEEERKNS_20ActorCreationOptionsERKNS4_12basic_stringIcNS4_11char_traitsIcEENSB_IcEEEEPNS_7ActorIDE+0x4b0
C  [libcore_worker_library_java.dylib+0x220bd]  Java_io_ray_runtime_task_NativeTaskSubmitter_nativeCreateActor+0x11d
j  io.ray.runtime.task.NativeTaskSubmitter.nativeCreateActor(Lio/ray/runtime/functionmanager/FunctionDescriptor;ILjava/util/List;Lio/ray/api/options/ActorCreationOptions;)[B+0
j  io.ray.runtime.task.NativeTaskSubmitter.createActor(Lio/ray/runtime/functionmanager/FunctionDescriptor;Ljava/util/List;Lio/ray/api/options/ActorCreationOptions;)Lio/ray/api/BaseActorHandle;+79
j  io.ray.runtime.AbstractRayRuntime.createActorImpl(Lio/ray/runtime/functionmanager/FunctionDescriptor;[Ljava/lang/Object;Lio/ray/api/options/ActorCreationOptions;)Lio/ray/api/BaseActorHandle;+46
j  io.ray.runtime.AbstractRayRuntime.createActor(Lio/ray/api/function/RayFunc;[Ljava/lang/Object;Lio/ray/api/options/ActorCreationOptions;)Lio/ray/api/ActorHandle;+27
*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
fixed?
