### ISSUE TITLE
[rllib] There is a problem with the ‘policies_to_train ’ of MADDPG, and my solution

### ISSUE THREAD

**Issue by SunnyWangGitHub** [ray-project/ray#9651]
### What is the problem?
MADDPG cannot use 'policies_to_train' to specify the training policy (except policy_0).

For example, when I set

                 "multiagent": {
                     "policies_to_train": ["policy_3"],
                     "policies": policies,
                     "policy_mapping_fn": ray.tune.function(
                         lambda i: policy_ids[i]
                     )
                 },

An error will be thrown after running the code：

      .../policy/sample_batch.py", line 194, in __getitem__
               return self.data[key]
               KeyError: 'new_actions_3'

When I locate the corresponding samplebatch, I find the dict_keys of samplebatch is like this

        dict_keys(['obs_3', 'actions_3', 'rewards_3', 'new_obs_3', 'dones_3', 'weights_3', 'batch_indexes_3', 'new_actions_0']) 

In the  function:before_learn_on_batch    of maddpg.py, I found the cause of this bug:

    target_act_sampler_n = [p.target_act_sampler for p in policies.values()]
    feed_dict = dict(zip(new_obs_ph_n, new_obs_n))

    new_act_n = p.sess.run(target_act_sampler_n, feed_dict)
    samples.update(
        {"new_actions_%d" % i: new_act
         for i, new_act in enumerate(new_act_n)})

    # Share samples among agents.
    policy_batches = {pid: SampleBatch(samples) for pid in policies.keys()}
    return MultiAgentBatch(policy_batches, train_batch_size)

The current code will cause the new_actions_ key to start from 0 by default. For example, in the example I cited above, if policies_to_train specifies policy_3 for training, the new_actions_ here will be new_actions_0 instead of new_actions_3, which causes an error

Here is how I solved this problem:

    def before_learn_on_batch(multi_agent_batch, policies, train_batch_size):
        samples = {}
        policies_to_train = []
        # Modify keys.
        for pid, p in policies.items():
            i = p.config["agent_id"]
            policies_to_train.append(i)
            keys = multi_agent_batch.policy_batches[pid].data.keys()
            keys = ["_".join([k, str(i)]) for k in keys]
            samples.update(
                dict(
                    zip(keys,
                        multi_agent_batch.policy_batches[pid].data.values())))

        # Make ops and feed_dict to get "new_obs" from target action sampler.
       new_obs_ph_n = [p.new_obs_ph for p in policies.values()]
       new_obs_n = list()
       for k, v in samples.items():
            if "new_obs" in k:
                new_obs_n.append(v)

       target_act_sampler_n = [p.target_act_sampler for p in policies.values()]
       feed_dict = dict(zip(new_obs_ph_n, new_obs_n))

       new_act_n = p.sess.run(target_act_sampler_n, feed_dict)

       samples.update(
            {"new_actions_%d" % i: new_act
             for i, new_act in zip(policies_to_train,new_act_n)})

       # Share samples among agents.
       policy_batches = {pid: SampleBatch(samples) for pid in policies.keys()}
       return MultiAgentBatch(policy_batches, train_batch_size)

**Comment by richardliaw** [comment]
cc @sven1977
