### ISSUE TITLE
Can't reduce num_workers for local node provider

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#9662]
Consecutive calls to `ray up` with a reduced number of workers for local node provider crashes.

steps to reproduce:
1) ray up example-full.yaml
2) //remove one worker
3) ray up example_full.yaml

This triggers the following assert:
https://github.com/ray-project/ray/blob/993ff5fd81fa2b7bda70a43ab3067ec754ceb5c7/python/ray/autoscaler/local/node_provider.py#L60

I will fix that in an upcoming PR.

**Comment by richardliaw** [comment]
thanks! this is a pretty important issue, agree
