### ISSUE TITLE
Speed up runtest.py

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#967]
The test suite in `runtest.py` takes way too long. We should speed this up. Or alternatively we should create a simpler streamlined test suite that we tell people to use.

**Comment by concretevitamin** [comment]
At a quick glance `runtest.py` doesn't seem to only re-run tests that are
affected.

One suggestion: consider (incrementally) adopting https://bazel.build/.  It
achieves the above, runs tests/builds in parallel, supports a variety of
languages, and is used by Google :)

**Comment by concretevitamin** [comment]
A good example project where this is used is TensorFlow (C++, Python, etc).

**Comment by robertnishihara** [comment]
Nice, @rshin actually did a version of this a long time ago at ray-project/ray-legacy#408.

**Comment by rshin** [comment]
One immediate issue with using Bazel might be that Bazel now requires Java 8, and maybe it's hard to get that inside the Docker image for building wheels, although I haven't looked into that at all.

**Comment by robertnishihara** [comment]
Closing. Now that we run tests together with `pytest`, we can see what the slowest ones are and improve them. Also https://github.com/ray-project/ray/pull/4271 will help with test speeds.
