### ISSUE TITLE
[tune] Random Search under time constraint

### ISSUE THREAD

**Issue by flokde** [ray-project/ray#9679]
Dear ray.tune team,

I've been trying to utilise tune to optimise over a rather awkward search space and I want to implement random search as a baseline. If I use a tune.Stopper to set a time limit, tune.run will start the specified number of trials (through num_samples) and then keep doing iterations on them until the time limit is reached. These additional iterations don't help me as the sampled parameter configuration is the same for each iteration in a trial. My current solution is to use a custom Stopper, that stops each trial after the first iteration and has an overall stopping condition, when the time limit is reached. This way I still have to manually choose a reasonable value for num_samples and the solution seems too complicated for such a simple task. 

What I am looking for is a random search that keeps sampling from the parameter space and running the Trainable for each sampled configuration once until the time limit is reached. This way I can benchmark random search against other search algos. Is there a more intuitive/elegant solution for this?

Thank you very much in advance for you help!
Florian

**Comment by richardliaw** [comment]
@flokde sorry for the slow reply! This is actually now possible - see https://github.com/ray-project/ray/pull/12156
