### ISSUE TITLE
Add documentation on using Ray with PyTorch.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#968]

**Comment by richardliaw** [comment]
@pcmoritz Are there any hiccups with Plasma <-> PyTorch? If not, then I can write a small docs page for this.

**Comment by robertnishihara** [comment]
I think they issues with 0.4 have been fixed now. I think you still have to register custom serializers for GPU backed tensors.

**Comment by richardliaw** [comment]
We've added some of this in #5175
