### ISSUE TITLE
[Tune Documentation] Fix Logging Docs

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#9686]
### What is the problem?

The Tune Logging page (https://docs.ray.io/en/master/tune/api_docs/logging.html) in the master docs still has references to `tune.track` which is now deprecated. This has led to some confusion with users https://github.com/ray-project/ray/issues/9685. We need to update the docs to show proper logging using the functional API.

**Comment by richardliaw** [comment]
yeah this is good - can you push a fix?
