### ISSUE TITLE
[GCS Actor Management] `test_dead_actors` release test is flaky. GCS fails with check failures.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9698]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*
![image](https://user-images.githubusercontent.com/18510752/88437114-9d9acb00-cdba-11ea-9318-8336fdb40462.png)

Tests occasionally failed with check failures. There must be a hidden race condition here. Could be related to flaky `test_multi_node`. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run `test_dead_actors.py` with the specified cluster configuration.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @ffbin @stephanie-wang Maybe just removing check there is sufficient? I remember I saw the same race condition in the past I couldn't reproduce after a certain point. Probably the same thing.

**Comment by ffbin** [comment]
@rkooo567 You can assign this issue to me. I have encountered it before.

**Comment by rkooo567** [comment]
@ffbin I think this must be fixed if you just return when actor is null. I will anyway assign it to you! Can you request me the review later?
