### ISSUE TITLE
[tune] Finding best checkpoint without finished trials

### ISSUE THREAD

**Issue by javadan** [ray-project/ray#9702]
Hi,

I'm trying out PBT & ARS/PPO for basic locomotion in my robot simulation, where I'm rewarding moving forward and not falling over.

I'm on my i3 laptop.  Learning is slow, and I need a workflow that makes more sense.

I currently leave it running overnight with the GUI off, then I kill it, enable the GUI, and have it set up to start off from the last checkpoint.  

From tensorboard I can see the reward mean is going up and down, and occasionally it makes it past the first step.  Most of the time it just fidgets around and falls over.

So I want to rather start training again from a peak in training, where the policy checkpoint has learned to take a step forward.

All the docs for finding the best checkpoints are for finished trials though.
Should I rather limit trial lengths, and get the best checkpoint through the trial analysis object?

Or is there an API way to restore from the best checkpoint for an unfinished trial?
I see progress.csv keeps track of episode_mean_reward, so I can probably work out something, but would rather do things 'correctly'.

Thanks for the help
Regards

**Comment by javadan** [comment]
I've tried ending trials at reward goals with a custom stopper and checkpoint_at_end=True, and then starting off from that checkpoint, with a new goal, but the trial is set to TERMINATED and won't run.

**Comment by javadan** [comment]
Ok I solved the issue.  Turned out it is documented
https://docs.ray.io/en/latest/tune/tutorials/tune-usage.html#stopping-trials
Custom stoppers stop the whole experiment.

**Comment by javadan** [comment]
Ok no, experiment is TERMINATED with the stop={...} too.  What is the trick to restoring a checkpoint that was created with checkpoint_at_end?

**Comment by javadan** [comment]
So I'm checkpointing the n best rewards, and then the trial finishes.

My planned workflow was to start the next trial using the best checkpoint from the previous trial.

**Comment by richardliaw** [comment]
You can use `tune.run(restore=checkpoint_path)` to achieve the desired effect, iirc.

**Comment by javadan** [comment]
Sorry, mis-clicked the close button. Added some clarification. Still having this issue.

**Comment by javadan** [comment]
Restoring a checkpoint from a finished trial terminates after one training iteration. That's the issue.

**Comment by richardliaw** [comment]
The key is not to use `resume`, but `restore`. Can you provide your restore script?

**Comment by javadan** [comment]
I had resume set.   That does make sense.  Thanks
