### ISSUE TITLE
[ray] Actor cannot inherit from ABC

### ISSUE THREAD

**Issue by 51616** [ray-project/ray#9705]
### What is the problem?

Seems like the actor class cannot be inherited from ABC superclass.

### Reproduction (REQUIRED)
```
class A(ABC):
    def __init__(self,x):
        self.x = x

@ray.remote
class B(A):
    def __init__(self,x):
        super().__init__(x)

b_instance = B.remote(1)
```
![image](https://user-images.githubusercontent.com/20886355/88460417-5863bf80-cec6-11ea-8387-a699c9f8b873.png)

PS. The issue does not appear if class A does not inherit the ABC

**Comment by rkooo567** [comment]
What version of Ray are you using? I could not reproduce it.

**Comment by 51616** [comment]
ray 0.8.5 + python 3.7
is this fixed in 0.8.6?

**Comment by rkooo567** [comment]
From the latest master, I couldn’t reproduce the issue. Can you try out?

**Comment by 51616** [comment]
The issue doesn't occur in 0.8.6. Closing the issue.
