### ISSUE TITLE
Detect remote functions for which the system overhead dominates

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#972]
Sometimes users define remote functions that are very fast, for which the system overhead of scheduling, serialization and putting objects into the object store dominates the execution cost. We should give a warning in this case.

**Comment by robertnishihara** [comment]
One subtlety is that there are sometimes good reasons to run very small tasks (e.g., to benchmark performance and stuff like that). If we have one warning per task, that will probably be really annoying. If it's at most one warning per job then that is probably fine.
