### ISSUE TITLE
ray.tune.error.TuneError: ('Trials did not complete'）

### ISSUE THREAD

**Issue by guoxuxu** [ray-project/ray#9726]
### What is the problem?
The only error is "
File "/home/guoxu/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 349, in run
raise TuneError("Trials did not complete", incomplete_trials)
"
Don't know how to figure out where is the problem. Is there a way to point to the line which triggered this error?

Code:
ray.init(num_cpus=os.cpu_count(), num_gpus=torch.cuda.device_count(), temp_dir='path/ray_log')
sched = ASHAScheduler(
        time_attr="training_iteration",
        metric="macro_f1",
        mode='max',
    )
analysis = tune.run(
        train,
        name="grl_adda_lys",
        scheduler=sched,
        verbose=True, #
        stop={"macro_f1": 0.30, "training_iteration": num_iters},
        resources_per_trial={"cpu": 1, "gpu": 0.5},
        num_samples=1,
        config=configargs,
    )

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.7
OS: linux

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by bergen288** [comment]
I have the same error.  Is there any fix/workaround?
