### ISSUE TITLE
[autoscaler] Monitor/autoscaling processes not starting properly 

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#9734]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

ray services/cluster don’t seem to be starting up properly for me (the ray start command is executed but the services don’t seem to stay alive). 

You can reproduce this by starting an automatic Ray cluster with Linux + V100 GPUs (p3.2xlarge, p3.8xlarge). Somehow it works fine for `c5` instances.

### Investigation so far:

 - This seems to be a problem regardless of changes made in commit=101c21. 
 - It also doesn't seem to go away even if I revert back to our old process startup mechanism:

```
    process = subprocess.Popen(
        command,
        env=modified_env,
        cwd=cwd,
        stdout=stdout_file,
        stderr=stderr_file,
    )
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run ray up with this:
https://gist.github.com/richardliaw/686f4f92d0035f48c1dd1ea82684d045

If we cannot run your script, we cannot fix your issue.

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [X] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
I think this is actually not an issue; it only arises if the local laptop ray is not consistent with the cluster version of Ray.

**Comment by richardliaw** [comment]
Reopening because this seems to be occurring on my cluster again.

**Comment by richardliaw** [comment]
One fix for this is to disable interactive ssh - `ray up --use-normal-shells`.

**Comment by wuisawesome** [comment]
Marking this as P1 since the scope seems to be much more limited now. Feel free to make this a release blocker if I'm misunderstanding the scope/you think it's important enough

**Comment by richardliaw** [comment]
sg, I'll test run this later.
