### ISSUE TITLE
[rllib] Multiagent policies - action of one agent visible to another

### ISSUE THREAD

**Issue by SyedBilalMehdi** [ray-project/ray#9736]
I am trying to implement a hierarchical RL agent such that at each time step, both the higher-level agent and the lower-level agent select their respective actions. Furthermore, the action chosen by the higher-level agent is visible to the lower-level agent. That is, at each time step, the higher level agent uses (i) the observations and (ii)  (possibly) its own state to select an action. Then, the lower-level agent uses (i) the same observation, (ii) the action selected by the higher-level agent, and (iii) possibly its own state own in order to choose its own action.

According to my understanding of rllib, such an implementation is not currently available and new contributions would be required to make this work.

I wanted to know if my assessment is correct. If that is the case, can I please be guided on what's the best way forward? I assume the rollout_workers would need to be edited in some way. I would like to know if I am going in the best direction.

Thanks in advance!

**Comment by raphaelavalos** [comment]
Hello,

This used case is described [here](https://docs.ray.io/en/master/rllib-env.html#hierarchical-environments).

You need to wrap your environment in a MultiAgentEnv and instead of having both agent acting at the same time they act one after the other. Then you can pass the action of the higher agent to the lower agent using the observation space.

Hope that helps :)

**Comment by SyedBilalMehdi** [comment]
Thank you for the response.

I am not sure if the case that's in the documentation is the same as what I wanted to implement. Specifically, as the documentation mentions, the lower-level agents pop in existence at the start of higher-level steps, and terminate when their higher-level action ends. This is different from what I am trying to implement in which both higher level and lower level agent choose and action at every time step.

One workaround that I do see now is that I could set "done" to be true for the lower level agent at every time step. This way, at the next time step, the higher level agent will act again and choose a different action. Later, I can postprocess the data to remove all the extra "dones" in the lower level agent's data.  am concerned if this will end up adding a lot of overhead, however.  I'd appreciate any comments on this approach.

Thanks!

**Comment by raphaelavalos** [comment]
Hello,

From what I understand, your higher agent observes o_1 and take action a_h,1  then the lower agent observes [o_1, a_h,1] and takes [a_l,1]. Making it two different steps. Am I missing something?

**Comment by SyedBilalMehdi** [comment]
You're right. We can consider it two steps that way. However, what I was concerned about was the fact that in the _standard_ hierarchical reinforcement learning example (such as [here](https://docs.ray.io/en/master/rllib-env.html#hierarchical-environments)), the higher level agent isn't called until the episode for the lower level agent has ended.

In my case, since both agents need to be called one after another, I'll have to set done = True every time the lower level agent is called. Would you agree?
This, I believe, will make sure that the higher level agent is called the next time step. The artificial 'done = True' would then need to be removed in the post processing.
Furthermore, it seems like a new low level agent is created every time the higher level agent is called [here](https://docs.ray.io/en/master/rllib-env.html#hierarchical-environments). I wonder if this would cause a lot of overhead.

**Comment by raphaelavalos** [comment]
Whether you want to set done to true for the lower agent depends on your rl algorithm as the agent's done is used for creating the agent's episode.

In a MultiAgentEnv the observation determines which agent need to act at the next time step and not the done flag. As RLlib considers hierarchical RL a multi-agent problem I would recommend to read the documentation on multiagent [here](https://docs.ray.io/en/master/rllib-env.html#multi-agent-and-hierarchical).

**Comment by SyedBilalMehdi** [comment]
> In a MultiAgentEnv the observation determines which agent need to act at the next time step 

That was a very helpful note. It made things pretty simple on our end. Thank you for pointing that out! I think we have a working implementation now where the high-level agent and low-level agents are called alternatively without any complications.

Best regards!
