### ISSUE TITLE
Understand train 

### ISSUE THREAD

**Issue by Catypad** [ray-project/ray#9748]
Hi! When I train an agent with

```
for _ in range(10):
     trainer.train()
```

how many time steps are taken in one iteration? In offline RL does an iteration mean going through all the episodes that exist in the dataset? If anyone can help me, I appreciate it very much!

**Comment by stefanbschneider** [comment]
As far as I understand, it depends on the `train_batch_size` that you can set in the `config`: https://docs.ray.io/en/latest/rllib-training.html?highlight=observation_filter#common-parameters
In one iteration, it takes at least as many steps as the size of the train batch size (sometimes a bit more).
