### ISSUE TITLE
[rllib] local logdir always set to /tmp/ray

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#976]
I wanted to specify a local directory to save my results via the `upload_dir` semantics, but I couldn't find the directory because `/tmp/ray` is hard-coded. Is this intentional?
https://github.com/ray-project/ray/blob/master/python/ray/rllib/common.py#L117

**Comment by ericl** [comment]
This sounds like a bug to me.

**Comment by pcmoritz** [comment]
Yeah, it should probably be upload_dir

**Comment by pcmoritz** [comment]
https://github.com/ray-project/ray/pull/977
