### ISSUE TITLE
[tune], [rllib] PyTorch 1.6 AMP support

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9760]
### Describe your feature request

PyTorch just released their new version 1.6, which comes with automatic mixed precision (AMP) training. This can sometimes speed up training and decrease memory requirements. The features requested would be implemented with flags in the training scripts.

References:
https://github.com/pytorch/pytorch/releases
https://pytorch.org/blog/pytorch-1.6-released/

**Comment by sven1977** [comment]
@juliusfrost, hearing you! We may just jump directly from 1.4 to 1.6 for our testing suite, then.

**Comment by kjabon** [comment]
Hi, has anyone made any progress on this front? Thanks
