### ISSUE TITLE
[Placement Group] Support fault tolerance of Placement Group Manager&Scheduler

### ISSUE THREAD

**Issue by ffbin** [ray-project/ray#9772]

**Comment by rkooo567** [comment]
@ffbin @ericl Can I take this? I think it'll be fairly simple to implement this with our atomic creation (unlike actor stuff which is much more complicated with many states).

**Comment by rkooo567** [comment]
@ffbin I heard from hao you guys are already working on this.  Should I pass it to you again?

**Comment by rkooo567** [comment]
https://github.com/ray-project/ray/pull/10998

The first step.

**Comment by rkooo567** [comment]
cc @ffbin Do you think we can close it?

**Comment by ffbin** [comment]
> cc @ffbin Do you think we can close it?

Yeah, i think we can close it now.
