### ISSUE TITLE
[RLlib] Error if tensorflow is not installed

### ISSUE THREAD

**Issue by raphaelavalos** [ray-project/ray#9784]
The annotations introduced in the PR #9676 make RLlib crash if TensorFlow is not installed. The crash appears because the namespace tf1 does not have FIFOQueue attribute. 

https://github.com/ray-project/ray/blob/156067b423ef327682fa6639c3a9936bf8fa7ea9/rllib/offline/input_reader.py#L95

The same error might also appear elsewhere

@michaelzhiluo maybe you can have a look. Thanks :)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
This should be fixed in the most recent master.
To patch this on your end for now: Just do:
```
queue: tf1.FIFOQueue 
```
