### ISSUE TITLE
[Placement Group] Recover placement groups after failure of a bundle

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9794]
If a bundle disappears, the placement group scheduler should try to recover the group by rescheduling the bundle. This should have higher priority than trying to place other placement groups.

Add unit and integration tests for this scenario.

**Comment by ffbin** [comment]
@ericl a bundle disappears-- do you mean node of the bundle is dead?

**Comment by ericl** [comment]
Yep, I guess the only scenario that should cause this is node failure
