### ISSUE TITLE
[Placement Group] Add way to wait on status of placement group

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9795]
Add a mechanism to wait for a placement group to become ready. It should be possible to (1) wait on multiple groups, and (2) wait on groups at the same time as other Ray tasks.

A possible implementation is to generate a dummy task that waits for any bundle (or all bundles) to become placed. Once the group is placed, then the task executes and returns the result. Example:

```
pg = ray.experimental.placement_group(...)
ray.get(pg)
ray.wait([pg], timeout=N)
```

This will be easier to implement once https://github.com/ray-project/ray/issues/9807 is done.

We might also need some way of getting the status of a placement group (e.g., pending scheduling, placed, recovering, deleted, etc).

**Comment by rkooo567** [comment]
I will take it in the next sprint.

**Comment by ericl** [comment]
I think this can be implemented via a dummy task. The dummy task tries to schedule itself in the placement group, so a ray.wait() successfully on the task means the placement group has been created.

**Comment by rkooo567** [comment]
That makes perfect sense! I was originally just thinking to ping GCS, but that solution sounds more natural to fit in ray.get & ray.wait!
