### ISSUE TITLE
[Placement Group] Port to new scheduler

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9801]
Port the placement group handling to the new scheduler.

**Comment by ericl** [comment]
@wuisawesome can you sync with @clay4444 on the work in progress so far?

**Comment by wuisawesome** [comment]
Ok, I’ve cleaned up it up a bit. Here’s the current status:
* I’ve implemented adding/removing custom dynamic resources in the ClusterResourceScheduler and the unit test for it. I think we can pull this out as a separate PR right now actually.
* I’ve implemented HandlePrepare and HandleCommit, but haven’t written test cases yet.
* We currently pass the first few basic tests in test_placement_groups.py
* I have not implemented Cancel or Release.
The PR is here: https://github.com/ray-project/ray/pull/12510

**Comment by ericl** [comment]
Thanks @clay4444 !!!
