### ISSUE TITLE
[Placement Group] Guarantee atomic visibility of bundles

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9807]
Currently when a placement group is created, we create the bundles one by one. This allows some tasks to start getting placed before the group is fully created.

A common failure case here is that resources in the cluster get claimed by some other task before the GCS server can reserve them for the placement group. This leads to a placement group creation failure even if no nodes have failed. Instead, we should implement a two phase protocol:

1. Send resource reservation prepare requests to all nodes.
2. Once all nodes have acknowledged the resource claims, commit the reservations and make them visible.

This means the node manager interface needs to go from
```
  void HandleRequestResourceReserve(const rpc::RequestResourceReserveRequest &request,
  void HandleCancelResourceReserve(const rpc::CancelResourceReserveRequest &request,
```

to

```
  void HandlePrepareResourceReserve(const rpc::RequestResourceReserveRequest &request,
  void HandleCommitResourceReserve(const rpc::RequestResourceReserveRequest &request,
  void HandleCancelResourceReserve(const rpc::CancelResourceReserveRequest &request,
```

**Comment by rkooo567** [comment]
Hey @ericl Can I take this & https://github.com/ray-project/ray/issues/9795
