### ISSUE TITLE
[Placement Group] Capture children tasks and actors in the same placement group

### ISSUE THREAD

**Issue by ericl** [ray-project/ray#9808]
There should be an option to contain nested tasks and actors in the same placement group. For example, with Ray Tune, the trial scheduler expects to create a placement group of a given size, and contain the actors of the trial within the group.

Example:
```
@ray.remote
def f():
   g.remote()  # implicitly, the placement group of g will be set that of f
   g.options(placement_group=None).remote()  # break out of the placement group

f.options(placement_group=group).remote()
```

**Comment by ericl** [comment]
@rkooo567 shall we prioritize this for next week? Either you or I can do it.

**Comment by rkooo567** [comment]
I can definitely do that. Let me know if you don't have bandwidth next week!
