### ISSUE TITLE
[rllib] ModelCatalog: Support custom registered Preprocessors etc.

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#981]
Currently we only support preprocessors, action distributions and policies that are shipped with RLLib. This should be extended to support arbitrary user-registered ones.

**Comment by pcmoritz** [comment]
Proposed API:

```
ModelCatalog.register_action_dist(env_name, dist, dist_dim)
ModelCatalog.register_model(env_name, model_class)
ModelCatalog.register_preprocessor(env_name, preprecessor_class)
```

A custom environment could register these in their __init__.py, similar to how we are registering it with OpenAI gym at the moment.

Let me know what you think, I might implement this since it is required for making the text summarization example work smoothly on the master.

**Comment by ericl** [comment]
+1

**Comment by richardliaw** [comment]
Question - why specify preprocessor for a specific env_name, `ModelCatalog.register_preprocessor(env_name, preprecessor_class)`?

**Comment by pcmoritz** [comment]
In my case I need it, because for the TextSummarization example I need a special preprocessor (which creates word vectors from tokens); it is the option that leaves the most freedom to the user I think at the cost of having too much verbosity and a separate register call for each environment.

**Comment by richardliaw** [comment]
Sure; I think this could be fine for now. At some point it'd be nice to have an option also to register for all environments at once.

**Comment by robertnishihara** [comment]
Done by #985.
