### ISSUE TITLE
[rllib] How to: my environment state space include a time series window or time dimension

### ISSUE THREAD

**Issue by jamartinh** [ray-project/ray#9813]
### My environment state space include a time series window or time dimension, as well as the action space

*gym state and action spaces:*

Hi, probably this is not only an issue of RLLib, however I can't figure out how this will be handled by rllib.

I have a state space of the form shape= (n_timesteps, n_variables_float), i.e. a matrix whose rows are time series of observations

Also an action space that should return a curve of continuous actions

Will RLlib understand this state space definition?

I was reading the [CustomRNN examples](https://github.com/ray-project/ray/blob/master/rllib/examples/custom_rnn_model.py)  

It seems that the CustomRNN handles time dimension by itself holding internaly the previous states? 
So the environment just need to only emmit one time step?

Commonly, environments for dealing with RGB images are easily defined since you can define a Box(low,high,shape) however in this case low and high are different for each varibable and gym envs does not allows to define shape when low and high are arrays

How is the way to go with RLLib on this matter?

**Comment by sven1977** [comment]
You can either:
1) pretend that your Env's time-dim is just "another" dim in your observation space and then process everything with a non RNN.
2) Make your Env emit single timesteps only and process everything with an RNN (which will take care of the time dim automatically by keeping an "internal state", which it learns to manipulate and read from automatically over training).

You will not succeed with option 1) if your environment is non-Markovian, meaning that one (n time-steps) observation does not hold enough information to capture the entire state of the simulation.

On the gym box los/high problem: I think it does work; I just tried this:
```
>>> from gym.spaces import Box as b
>>> b
<class 'gym.spaces.box.Box'>
>>> import numpy as np
>>> b(np.array([1.0, 2.0]), np.array([5.0, 10.0]), shape=(2,))
D:\Programs\Anaconda3\envs\ray\lib\site-packages\gym\logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Box(2,)
>>> box = b(np.array([1.0, 2.0]), np.array([5.0, 10.0]), shape=(2,))
>>> box.sample()
array([1.1191947, 4.746241 ], dtype=float32)
>>> box.sample()
array([3.543729, 7.206219], dtype=float32)
>>> box.sample()
array([2.9265711, 5.644465 ], dtype=float32)
>>> box.sample()
array([3.1741917, 2.0503893], dtype=float32)
>>>
```

**Comment by jamartinh** [comment]
Thank you very much!!!
I will try both approaches.
I have currently a model with 60 time steps that seems enough at least for
my reward signal.

Cheers,
Jose

**Comment by 51616** [comment]
I have some questions related to this.
How can I implement an RNN model that handle a batch of sequences of images from the environment? I went with the second approach @sven1977 suggested making the environment emit only the images part while letting the model handle the sequencing part. This does not work out of the box since I have trouble translate the example code `examples/custom_keras_rnn_model.py` into my custom environment.

This is my custom convolution RNN model which based on the example file above.
```
class ConvRNNPG(RecurrentTFModelV2):
    """Example of using the Keras functional API to define a RNN model."""

    def __init__(self,
                 obs_space,
                 action_space,
                 num_outputs,
                 model_config,
                 name):
        super(ConvRNNPG, self).__init__(obs_space, action_space, num_outputs, model_config, name)
        self.cell_size = cell_size = 64 # cell_size
        hiddens_size = 64

        # Define input layers
        input_layer = tf.keras.layers.Input(shape=obs_space.shape, name="observations")
        state_in_h = tf.keras.layers.Input(shape=(cell_size, ), name="h")
        state_in_c = tf.keras.layers.Input(shape=(cell_size, ), name="c")
        seq_in = tf.keras.layers.Input(shape=(), name="seq_in", dtype=tf.int32)
        print('Input shape:',input_layer.shape)
        # Preprocess observation with a hidden layer and send to LSTM cell
        conv1 = tf.keras.layers.Conv2D(filters = 25, kernel_size = 5, padding = 'same', activation=tf.nn.leaky_relu, name="conv1")(input_layer)
        conv2 = tf.keras.layers.Conv2D(filters = 25, kernel_size = 3, padding = 'same', activation=tf.nn.leaky_relu, name="conv2")(conv1)
        conv3 = tf.keras.layers.Conv2D(filters = 25, kernel_size = 3, padding = 'valid', activation=tf.nn.leaky_relu, name="conv3")(conv2)
        print('Conv network output shape:',conv3.shape)

        flat = tf.keras.layers.Flatten()(conv3)
        fc4 = tf.keras.layers.Dense(64,activation=tf.nn.leaky_relu,name="fc4")(flat)
        fc5 = tf.keras.layers.Dense(64,activation=tf.nn.leaky_relu,name="fc5")(fc4)
        print('fc5 output shape:',fc5.shape)

        lstm_out, state_h, state_c = tf.keras.layers.LSTM(
            cell_size, return_sequences=True, return_state=True, name="lstm")(
                inputs=fc5,
                # mask=tf.sequence_mask(seq_in),
                # initial_state=[state_in_h, state_in_c]
                )
        print('lstm')

        # Postprocess LSTM output with another hidden layer and compute values
        logits = tf.keras.layers.Dense(num_outputs, activation=None, name="logits")(lstm_out)

        values = tf.keras.layers.Dense(1, activation=None, name="values")(lstm_out)

        # Create the RNN model
        self.rnn_model = tf.keras.Model(
            inputs=[input_layer, seq_in, state_in_h, state_in_c],
            outputs=[logits, values, state_h, state_c])
        
        self.register_variables(self.rnn_model.variables)
        self.rnn_model.summary()

```

I investigated this a little bit, it seems like the inputs do not have sequence dimension.
I tried both convolution and fully-connected networks but they produce the same shaping problem.

This is the output of the print statement:
```
Input shape: (?, 84, 84, 4)
```
which does not include the added time dimension.

And this is the error
```
ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, 64]
```
