### ISSUE TITLE
[sgd] Why TorchTrainer doesn't have a predict method?

### ISSUE THREAD

**Issue by hkvision** [ray-project/ray#9816]
Just want to ask how to do distributed inference using RaySGD?
I can't find a predict method for TorchTrainer. Is it because collecting all the prediction results back to the master would be costly? So it only supports training or validation for now?
BTW, seems I can't find an example from official PyTorch for distributed inference using DDP...
@richardliaw

**Comment by richardliaw** [comment]
Interesting; what are you trying to do in particular? 

BTW, thanks a bunch for opening these issues. Would you be willing to jump on a call sometime next week? I would love to learn more about your usage of Ray!

**Comment by hkvision** [comment]
I'm thinking of distributed inference; just wondering why predict is not supported in RaySGD.

My team is working on RayOnSpark, mainly enabling Ray to easily handle large scale production data, as you may have probably heard of. We have posted several guest blogs at RiseLab's site. I will check with my team and reach back to you later to have a further chat! Thanks so much Richard!
