### ISSUE TITLE
[RLlib] Error if tensorflow is not installed

### ISSUE THREAD

**Issue by raphaelavalos** [ray-project/ray#9819]
Hello,

When TensorFlow is not installed RLlib crashes because tf is not None and but it doesn't have a keras attribute.

https://github.com/ray-project/ray/blob/01125b8fcfce88472c2e20d116bc6662032088e0/rllib/models/tf/layers/gru_gate.py#L6

Thank you for your work :)

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by sven1977** [comment]
Hmm, `tf` should be None, because it can't be imported, no?
What's the value of `tf` in your case.

**Comment by raphaelavalos** [comment]
PyCharm left the TensorFlow package directory after removing its content so it was importing an empty package.
All works now thx
