### ISSUE TITLE
Typo/bug with the Dirichlet distribution 

### ISSUE THREAD

**Issue by gradpratik** [ray-project/ray#9820]
https://github.com/ray-project/ray/blob/e540e425e4aee15706f4f3da4e6a0f7d73dbb52c/rllib/models/tf/tf_action_dist.py#L512

The

>  self.dist = tf.distributions.Dirichlet

 should be **"tfp.distributions" and not tf.distributions** --> 512         
```
self.dist = tf.distributions.Dirichlet(
    513             concentration=concentration,
    514             validate_args=True,

AttributeError: module 'tensorflow' has no attribute 'distributions'
```

**Comment by simon-mo** [comment]
cc @sven1977
