### ISSUE TITLE
Hyperthreading not disabled in Ray 0.8.6 

### ISSUE THREAD

**Issue by snmhaines** [ray-project/ray#9821]
This relates to the pull request "Force OMP_NUM_THREADS=1 if unset #6998" from February (also "Always set OMP_NUM_THREADS even on low core machines #7006").  I left a comment on the former, but I am not sure that anyone will have been notified.  I also posted a question on Stackoverflow: "Disabling Hyperthreading on Nodes in an AWS EC2 Cluster through Ray Configuration".

I have updated to 0.8.6, but OMP_NUM_THREADS isn't defined on the head-node (c5.24xlarge).  If the change has not been made in the current version, then this is not a bug, and I just need advice on how to get the variable set through the config.

**Comment by snmhaines** [comment]
P.S.  I have managed to set OMP_NUM_THREADS=1 on the head-node and workers, through the config file, but it is has made disappointingly little difference.

**Comment by richardliaw** [comment]
Can you provide a repro script? That'd help us better understand the problem!

**Comment by snmhaines** [comment]
I am attaching the configuration file that I have been using.  You can see that I have a line in the setup that sets OMP_NUM_THREADS=1.  The application that I want to run on this cluster is a rather large 1-D CFD simulation that is started by a Python3 script that initiates Ray to run 90 instances of this in parallel.  I have checked that each worker does get the environmental variable set with that ray_config.yaml, so the immediate problem should be reproducible by removing line 61 and spinning up the cluster, then logging into the head node to see whether OMP_NUM_THREADS exists.

Meanwhile, I am running some diagnostic tests that AWS suggested to try to positively identify the cause of my application bogging down with larger numbers of workers.  One theory, that I cannot yet completely eliminate, is that the way I am commanding HT to be switched off is not actually taking effect.

Yours,
Steven Haines


[ray_conf.zip](https://github.com/ray-project/ray/files/5009146/ray_conf.zip)

**Comment by snmhaines** [comment]
Success!  I used the suggestion from here: https://aws.amazon.com/blogs/compute/disabling-intel-hyper-threading-technology-on-amazon-linux/, but also had to give the user permissions to overwrite all the cpu online flags:-

setup_commands:
    - sudo chmod -R 777 /sys/devices/system/cpu/*
    - for cpunum in $(cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | cut -s -d, -f2- | tr ',' '\n' | sort -un); do echo 0 > /sys/devices/system/cpu/cpu$cpunum/online; done

My application now runs on 90 tasks as fast as one.  It seems that OMP_NUM_THREADS is ineffective.  

Also, I would suggest that if you intend to simplify the disablement of hyperthreading, then it is implemented as an option in the config file (as in the Matlab Cloud Center cluster configuration), because the need to do it is application-specific, not a function of number of CPUs in the instance.  The problem of two CPUs fighting over one FPU arises, even on only one core, if the application's floating-point usage is heavy enough.

... Steven Haines

**Comment by richardliaw** [comment]
Any recommendation on what we should add to the documentation?
