### ISSUE TITLE
[rllib] ParallelRollouts ignores local worker, ExternalEnv reports queue empty exception

### ISSUE THREAD

**Issue by BBLN** [ray-project/ray#9823]
### What is the problem?
After debugging issue #7830, I found a bug in the ParallelRollouts class.
In worker_set.py of rllib a _local_worker is always created in WorkerSet __init__.
In ParallelRollouts, if a remote worker exists, no sampling made for the local worker, resulting in empty action queue.
After the timeout (60 seconds) the local worker raises the queue empty exception and shuts down.

A fix would be to also treat the local_worker, but I'm not sure ParallelIterator can treat both the local and remote workers.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.6, tensorflow 2.1.0 on both Linux & Windows

### Reproduction (REQUIRED)
```
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print
from ray.rllib.env import ExternalEnv
import gym

class AsyncCartPole(ExternalEnv):
    def __init__(self, config):
        self.env = gym.make('CartPole-v0')
        # Actions
        self.action_space = self.env.action_space

        # Positions
        self.observation_space = self.env.observation_space
        super(AsyncCartPole, self).__init__(self.action_space, self.observation_space)

    def run(self):
        eid = self.start_episode()
        self.env.reset()
        obs, reward, finished, info = self.env.step(self.action_space.sample())
        while True:
            print("calling get action")
            action = self.get_action(eid, obs)
            print("got action")
            obs, reward, finished, info = self.env.step(action)
            self.log_returns(eid, reward, info)
            if finished:
                self.end_episode(eid, obs)
                eid = self.start_episode()
                self.env.reset()
ray.init()
config = ppo.DEFAULT_CONFIG.copy()
config["num_gpus"] = 0.00002
config["num_workers"] = 1
trainer = ppo.PPOTrainer(config=config, env=AsyncCartPole)

for i in range(100):
    # Perform one iteration of training the policy with PPO
    result = trainer.train()
    print(pretty_print(result))

    checkpoint = trainer.save()
    if i % 10 == 0:
        print("checkpoint saved at", checkpoint)
```

**Comment by BBLN** [comment]
Why isn't this considered a bug?

**Comment by BBLN** [comment]
@sven1977 Also happens on 0.8.7, seems like a waste of resources on main thread

**Comment by bkusenda** [comment]
Even though the local worker isn't being used, it creates one or more instances of the environment.  This is a problem for environments that have expensive initialization cost.   If this behavior is intended, perhaps it should be in the main documentation.

**Comment by guyue5** [comment]
> @sven1977 Also happens on 0.8.7, seems like a waste of resources on main thread
I also encountered this, have u solved?

**Comment by guyue5** [comment]
I also encountered this, have u solved?

**Comment by bkusenda** [comment]
@guyue5
My current workaround is to use an environment wrapper which doesn't perform any heavy initialization until the first call to "reset".  This only resolves the expensive initialization costs issue I point out not that it's a waste of resources and generally poor design.

**Comment by bkusenda** [comment]
@guyue5 I just ran into this in the documentation.

    # When `num_workers` > 0, the driver (local_worker; worker-idx=0) does not
    # need an environment. This is because it doesn't have to sample (done by
    # remote_workers; worker_indices > 0) nor evaluate (done by evaluation
    # workers; see below).
   "create_env_on_driver": False,

Snipped from https://docs.ray.io/en/master/rllib-training.html

I haven't tested this but it appears to be addressing the issue.
