### ISSUE TITLE
Support efficient panda dataframes serialization via shared memory

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#984]
If a pandas dataframe is part of a Python object, it should be serialized efficiently and possible to share the memory between processes via shared memory, in a similar manner as numpy arrays are currently handled.

see also https://issues.apache.org/jira/browse/ARROW-1503

**Comment by mitar** [comment]
So https://issues.apache.org/jira/browse/ARROW-1503 has just been merged in. Does this mean this issue is also resolved?

**Comment by pcmoritz** [comment]
Not quite yet, we need to update the arrow sha1 checkout hash. I can do that now.

**Comment by mitar** [comment]
BTW, does this mean that there is also efficient serialization of Pandas which have for its values object dtype, and each value is a numpy array?

**Comment by pcmoritz** [comment]
That's a good question, we didn't write the code that converts pandas data structures to arrow. [1] suggests that for 1d arrays it is indeed the case, but I don't know about multi dimensional ones. If you have a specific configuration in mind, please try it and if it is not fast, report an issue.

[1] https://github.com/apache/arrow/blob/208e79812b5d98f9cd31f4f9ed9e74e6f76f24fd/python/pyarrow/tests/test_convert_pandas.py#L243

**Comment by pcmoritz** [comment]
also with more nesting: https://github.com/apache/arrow/blob/208e79812b5d98f9cd31f4f9ed9e74e6f76f24fd/python/pyarrow/tests/test_convert_pandas.py#L600

**Comment by robertnishihara** [comment]
Possibly fixed with #1102, but I'll leave the issue open until we've verified this.
