### ISSUE TITLE
How to save only the best model parameters?

### ISSUE THREAD

**Issue by guoxuxu** [ray-project/ray#9840]
### What is your question?

As I am looking into how to save only the best model parameters. I'm curious about ```ray/tune/time_since_restore```,  ```ray/tune/time_this_iter_s```, ```ray/tune/iterations_since_restore``` and ```ray/tune/timesteps_since_restore```.  Could you explain according to the parallel coordinates view shown below? 

![image](https://user-images.githubusercontent.com/29363464/89022516-c0962380-d354-11ea-9c37-2e62af98c1ae.png)

I'm using a trainable class with some functions as follows. 

```
    def _save(self, checkpoint_dir):
        checkpoint_path = os.path.join(checkpoint_dir, "model.pth")
        torch.save(self.model.state_dict(), checkpoint_path)
        return checkpoint_path

    def _restore(self, checkpoint_dir):
        checkpoint_path = os.path.join(checkpoint_dir, "model.pth")
        self.model.load_state_dict(torch.load(checkpoint_path))

    def reset_config(self, new_config):
        for param_group in self.optimizer.param_groups:
            if "lr" in new_config:
                param_group["lr"] = new_config["lr"]
        self.model = bert_clf.cuda()
        self.config = new_config
        return True
```

About the initialization code, I'm only using the line ```ray.init()``` now. The documentation about ```validate_save_restore``` is not clear to me and it‘s also unsuccessful to add the two lines directly.
```
        # ray.shutdown()  # Restart Ray defensively in case the ray connection is lost.
        ray.init(num_cpus=os.cpu_count(), num_gpus=torch.cuda.device_count(), temp_dir=temp_dir)
        # validate_save_restore(Train, config=space)
        # validate_save_restore(Train, config=space, use_object_store=True)
        # print("Success!")
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
OS: Linux
Python: 3.7.4
Ray: 0.8.5

**Comment by richardliaw** [comment]
@guoxuxu I would just ignore those parameters, they're more like metadata.

**Comment by guoxuxu** [comment]
Thanks very much
