### ISSUE TITLE
[serve]/[core] Workers running in different virtualenvs

### ISSUE THREAD

**Issue by dsuess** [ray-project/ray#9842]
Is it possible to run workers inside different virtual environments (but with the same python version)? 

For example, is it possible to use ray-serve to compose two models, one of which requires Tensorflow 1 while the other requires Tensorflow 2? Since it doesn't seem possible to run multiple nodes on the same machine, I'd be happy with running nodes in separate containers, which have the necessary python libraries installed.

**Comment by anabranch** [comment]
Hey @dsuess !
Thanks for this question. We're doing some work in this area of Ray and it'd be great to make sure that we'll support your use case. Could we setup a quick 30 minute call in the next week or so to go over your use case and requirements? Please ping me at my first name @ anyscale.com and we can setup a call.

Look forward to chatting with you!

**Comment by dsuess** [comment]
Hi @anabranch, thanks for the offer! I've send you a mail. Looking forward chatting with you!
