### ISSUE TITLE
[autoscaler] Provide IAM policy for ray autoscaling on AWS

### ISSUE THREAD

**Issue by jieru-hu** [ray-project/ray#9848]
### What is your question?
 Could we get a list of all the AWS IAM permission polices needed to run ray autoscaler? Right now I'm attaching AmazonEC2FullAccess & IAMFullAccess to my IAM user. But a more detailed documentation would be ideal/awesome!

Thanks!

**Comment by VishDev12** [comment]
It's not comprehensive, but this might be a good starting point: #9327
