### ISSUE TITLE
[docs] Issue on `cluster/launcher.rst`

### ISSUE THREAD

**Issue by alexcoca** [ray-project/ray#9874]
# Documentation Problem/Question/Comment

The [page ](https://docs.ray.io/en/master/cluster/launcher.html#ref-automatic-cluster)directs the reader [here](https://docs.ray.io/en/master/package-ref.html) to read more about `ray up` and `ray exec` but these are not documented on this page (currently the `The Ray Command Line API` section is empty).

(Created directly from the docs)

**Comment by richardliaw** [comment]
@alexcoca should be fixed now!
