### ISSUE TITLE
[Docs] Some doc strings aren't generating website documentation

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#9877]
### What is the problem?

Some doc strings aren't generating documentation in the package reference on RTD. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

For example, `ParallelIterator::transform` isn't generated. Its documentation can be found here: https://github.com/ray-project/ray/blob/c741d1cf9c78f8cd60b40d58b88e8d3e4d636906/python/ray/util/iter.py#L196

But not here https://docs.ray.io/en/latest/iter.html#module-ray.util.iter

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
Looks fine to me - https://docs.ray.io/en/master/iter.html#ray.util.iter.ParallelIterator.transform

**Comment by wuisawesome** [comment]
oh nvm, i thought this made it into 0.8.6 but it looks like it might not have.
