### ISSUE TITLE
With 6 workers, Ape-X trains faster than interacting with the environment?

### ISSUE THREAD

**Issue by xlnwel** [ray-project/ray#9890]
I run this [project](https://github.com/aicrowd/neurips2020-procgen-starter-kit) using `APEX` from ray, and noticed that the learning step is incredible fast. How does ray achieve that?

All I've done is to replace [this file](https://github.com/AIcrowd/neurips2020-procgen-starter-kit/blob/master/experiments/impala-baseline.yaml) with the following configuration

```python
procgen-ppo:
    env: procgen_env_wrapper  # Change this at your own risk :D
    run: APEX
    stop:
        timesteps_total: 8000000

    checkpoint_freq: 100
    checkpoint_at_end: True
    keep_checkpoints_num: 5

    config:
        env_config:
            env_name: coinrun
            num_levels: 0
            start_level: 0
            paint_vel_info: False
            use_generated_assets: False
            center_agent: True
            use_sequential_levels: False
            distribution_mode: easy

        use_pytorch: False

        model:
            custom_model: impala_cnn_tf
            custom_options: {}

        num_workers: 6
        num_envs_per_worker: 1
        rollout_fragment_length: 100

        batch_mode: truncate_episodes

        num_cpus_per_worker: 1
        num_gpus_per_worker: 0
        num_cpus_for_driver: 1

        num_gpus: 0.5
        explore: True,

        observation_filter: "NoFilter"
        synchronize_filters: True
        compress_observations: False
        timesteps_per_iteration: 0
        seed: null
```

Here's a snapshot from tensorboard

![image](https://user-images.githubusercontent.com/10184153/89243266-1b21cf00-d636-11ea-806d-fb6dfa00f4f7.png)

In the same training time, the `num_steps_trained`(the number of training steps? if I understand it right) is 10+ times more than `num_steps_sampled`(the number of interactions between the agent and environment?). How's it even possible as `procgen` is already a fast environment? Or am I misunderstand something?

Also, I noticed the target network update frequency is extremely large in Ape-X's default configuration. It's up to 500000 training steps as [this line](https://github.com/ray-project/ray/blob/b4c527b3f3e61bbea72b15706a9958fd337c93a6/rllib/agents/dqn/apex.py#L39) shows. While recent papers recommend this value to be thousands of training steps.

**Comment by ericl** [comment]
Yep this is since replay can proceed asynchronously with respect to environment sampling. If you want to enforce a rate limit at which learning can occur with respect to environment steps samples, there is the training_intensity option which will fix a ratio of train to sampled steps.

**Comment by xlnwel** [comment]
Hi @ericl. Thanks for answering. But I still feel like I'm misunderstanding something. I manually calculate the training steps per second from the following snapshot

![image](https://user-images.githubusercontent.com/10184153/89263702-4cb18f00-d664-11ea-8230-006ae7afbed6.png)

it's `(1.2*10**7)/(37*60)=5400` training steps per second. While my own implementation of Ape-X using nature CNN on atari games also based on `ray` but not on `rllib` can only achieve around 80 training steps per second. There are several differences I know between my implementation and `rllib`:

1. I define the replay as a standalone ray actor
2. I define a separate actor for the learner with `num_cpus=3, num_gpus=.5`. I specify 3 cpus here because I use `tf.data.Dataset` to fetch data from the replay center, which often requires more than one cpu from monitoring `top`.
3. I use 64 batch size in my own implementation, while rllib use 512 as the default batch size. 

Do you think these would cause such a huge difference? 

Also, I'm confused about why the training process is faster than the environment interaction? `Procgen` is designed to be faster, and I've already specify 6 workers for data collection.

**Comment by ericl** [comment]
RLlib measures steps in environment transitions, not batches, so I believe it's 80*64=5120 vs 5400, which is pretty similar.

I'm not surprised training is faster, since it occurs in much larger batches than inference (which is typically just 1 step at a time unless you use vectorized envs).

**Comment by xlnwel** [comment]
I see. That makes sense. Thank you. @ericl
