### ISSUE TITLE
run as_future from thread

### ISSUE THREAD

**Issue by endremborza** [ray-project/ray#9893]
### Ray actor remote as_future can not be called from a new thread

I'm building a small scheduler that uses ray actors and queues in different python threads, but I ran into an issue I couldn't really deal with and eventually went a different way. However, I thought I'd share, as it may be relevant. If not, please close the issue.

this is from ray 0.8.6, the latest on pip, python3.7

### MWE

```python

from threading import Thread
import time

import ray


ray.init()

@ray.remote
class Example:
    def __init__(self, x):
        self.x = x

    def get(self):
        return self.x

    
e = Example.remote(5)

l = []

class Cons(Thread):
    
    def run(self):
        e.get.remote().as_future().add_done_callback(lambda x: l.append(x.result()))

c = Cons()
c.start()
c.join()

```

this gives `RuntimeError: There is no current event loop in thread 'Thread-n'.`

it works great without the `as_future()`, but this is still hard to pinpoint, and there are no available examples I could find

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by simon-mo** [comment]
Hi @endremborza, thanks for raising this issue. Ray ObjectRef's future is an `asyncio.Future` not `concurrent.Future`. The two has [subtle differences](https://docs.python.org/3/library/asyncio-future.html). I would recommend using asyncio.Queue instead of threading queues. is there a particular reason python threads are necessary?

**Comment by endremborza** [comment]
I ended up going the asyncio way, and replaced threads with async functions, it worked well that way. I used threads at first because I found it easier to track and kill them, but it worked with asyncio just as well, after a bit of getting used to.
