### ISSUE TITLE
[raySGD] input an IterableDataset in validation dataloader cause TypeError

### ISSUE THREAD

**Issue by yushan111** [ray-project/ray#9899]
ray version: 0.8.6
The error of _TypeError: object of type 'MyIterableDataset' has no len()_ occurs on https://github.com/ray-project/ray/blob/releases/0.8.6/python/ray/util/sgd/torch/distributed_torch_runner.py#L156-L157
It can be reproduced by input an IterableDataset as validation data loader.
And I fixed that by changing to 
```python
if self.validation_loader is not None and should_wrap_dataloader(
                self.validation_loader)
```

**Comment by richardliaw** [comment]
hmm @yushan111 can you push a fix?

**Comment by yushan111** [comment]
> hmm @yushan111 can you help open a PR? Thanks!

Sure

**Comment by richardliaw** [comment]
Great - please ping me when you do! thank you!

**Comment by yushan111** [comment]
@richardliaw I have opened PR #9952
