### ISSUE TITLE
[sgd] What's the purpose of LocalRunner in TorchTrainer

### ISSUE THREAD

**Issue by hkvision** [ray-project/ray#9901]
Want to ask what's the purpose of always keeping a runner on the local driver node instead of making all runners actors?
As I go through code, is it because it is easier to get the trained model without pickling from remote nodes? If so, does it mean it is difficult to serialize/deserialize models in ray?

Thanks so much! @richardliaw

**Comment by richardliaw** [comment]
We should get rid of this because it causes quite a bit of problems :) The reason was previously for interactive workloads + debugging, but it seems like the costs outweigh benefits.

**Comment by hkvision** [comment]
So you mean you are going to remove local runner and all use actors in the future?
Then in this case if I want to get the trained model, I need to choose one remote worker and get the model to driver? In the current TorchRunner, seems there is no get_model method, models is just a property of the runner. How to retrieve the attributes of actors in Ray actually?

**Comment by hkvision** [comment]
I saw this issue has been fixed by adding a `use_local` flag. Closing this issue. Thanks so much!
