### ISSUE TITLE
Long running test `pbt.py` seems to OOM after running for a day.

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#9921]
### What is the problem?

Long running test `pbt.py` seems to OOM after running for a day.

![image](https://user-images.githubusercontent.com/18510752/89354845-ca7a9800-d66e-11ea-9b9b-6f3b6656553b.png)

You can see some of workers use lots of memory (5GB). 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Run pbt.py for a long time.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
cc @richard4912

**Comment by richardliaw** [comment]
^ again, wrong richard :)

**Comment by ericl** [comment]
Closing stale issue since the latest release passes. Please re-open if it is still a problem.
