### ISSUE TITLE
[tune] Initial guess for hyperparameters

### ISSUE THREAD

**Issue by crypdick** [ray-project/ray#9922]
## Request:
Optional "initial guess" parameter for sampling, similar to `x0` kwarg [in scipy optimizers](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html), e.g. `tune.loguniform(1e-6, 1e-1, x0=1e-4)`

## Motivation:
Tune experiments dramatically speed up after the first "reasonable" baseline config is found: subsequent "unreasonable config" trials are quickly terminated. Almost always, the first randomly sampled configs are far from optimal, and thus the first few hours of tuning are wasted training bad configs until a baseline is found.

If I could set a reasonable `x0`, it would quickly establish a baseline and enable exploring wider ranges without wasting too much time.

**Comment by richardliaw** [comment]
which Search Alg are you using?

**Comment by crypdick** [comment]
@richardliaw async hyperband

**Comment by krfricke** [comment]
Solved by https://github.com/ray-project/ray/pull/12790
