### ISSUE TITLE
[Tune] Long running distributed test failing

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#9923]
### What is the problem?

The RaySGD+Tune long running distributed test is failing due to this error:

![image](https://user-images.githubusercontent.com/8068268/89367475-f78a7300-d68d-11ea-8aeb-7b27ecf2ab2d.png)

We need to modify either the test or the kill_node command to not kill any nodes if there is only one node left in the cluster.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

bash ci/long_running_distributed_tests/run.sh --workload=pytorch_pbt_failure

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by amogkam** [comment]
@rkooo567

**Comment by ericl** [comment]
Closing stale issue since the latest release passes. Please re-open if it is still a problem.

**Comment by amogkam** [comment]
This error happens again in the latest release
