### ISSUE TITLE
how to get start from scratch as a DEVELOPER of Ray?

### ISSUE THREAD

**Issue by loveJasmine** [ray-project/ray#9925]
specially, any details about the modules like plasma, arrow etc.

**Comment by rkooo567** [comment]
Hi, @loveJasmine Thanks for your interest in becoming a Ray contributor!! I'd like to suggest a couple ways to start! Learning about core components like Plasma store or other parts of systems are a little tricky now, but we will have more resources online out there sooner or later, so stay tuned :). 

- Use Ray! Think about what's the problem and propose fixes! Joining our slack is also good idea.
- Start from fixing small issues. There are bunch of issues tagged with `good-first-issue`, which are created for beginner contributors!
