### ISSUE TITLE
[rllib] ARS trainer doesn't work with evaluation workers

### ISSUE THREAD

**Issue by jyotishp** [ray-project/ray#9933]
### What is the problem?

ARS trainer fails when evaluation workers are used. Throws the following error:

```
AttributeError: 'ARSTrainer' object has no attribute '_policy'
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
- Ray version: 0.8.6
- Tensorflow: 2.3.0
- Python 3.7
- OS: Linux

### Reproduction (REQUIRED)
```python
import ray
from ray.tune.tune import run_experiments

experiments = {
    "cartpole-ars": {
        "env": "CartPole-v0",
        "run": "ARS",
        "stop": {"timesteps_total": 10000},
        "config": {
            "num_workers": 1,
            "num_envs_per_worker": 5,
            "evaluation_interval": 1,
            "evaluation_num_workers": 1,
            "evaluation_num_episodes": 1
        }
    }
}

ray.init(num_cpus=3)
run_experiments(
    experiments,
    verbose=True,
)
```

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by jyotishp** [comment]
What I tried?

```python
from ray.rllib.agents.ars import ARSTrainer
from ray.rllib.agents.ars.ars import get_policy_class

class ARSTrainerFixed(ARSTrainer):
    def _init(self, config, env_creator):
        super()._init(config, env_creator)
        self._policy = get_policy_class(config)
```

Then I get

```
ValueError: policy must be a rllib.Policy class
```

**Comment by sven1977** [comment]
Taking a look ...

**Comment by sven1977** [comment]
@jyotishp Thanks for filing this issue!

This PR fixes it:
https://github.com/ray-project/ray/pull/11308
