### ISSUE TITLE
[rllib] Accessing the reward of other agents in custom multi-agent algorithm

### ISSUE THREAD

**Issue by ericzhao28** [ray-project/ray#9949]
### What is your question?

My goal is to implement a custom multi-agent algorithm. However, to update the policy for any individual agent requires access to the rewards of other agents. Is there any way to access the rewards issued to other agents? I imagine this may be similar to the problem of accessing the observation of other agents, which seems to be an open problem (see #7341, #4748).

**Comment by sven1977** [comment]
Yeah, we are not fully there yet, but are working on a generic API to enable easy set up of things like this in any RLlib agent. The project is called "Trajectory View API" and we have some solutions for LSTM/framestacking, but not multi-agent yet (this will be the last thing we'll add to this API). A rough time estimate, on when this will be done is this Q3, but can't make promises.

**Comment by MiladInk** [comment]
Is this possible in rllib now?
