### ISSUE TITLE
[rllib] Offline API takes too much memory

### ISSUE THREAD

**Issue by juliusfrost** [ray-project/ray#9961]
### What is the problem?

When using a relatively large offline dataset, the offline API (json reader) continuously loads more data from storage even when memory is at full capacity. Possible solutions could involve a queue of some sort so that not all of the data is in memory.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: nightly
Python 3.7
Tensorflow 2.2
PyTorch 1.6

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

New reproduction script:
https://github.com/juliusfrost/rllib-offline-test

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
cc @sven1977

**Comment by ericl** [comment]
Can you provide a reproduction script? This shouldn't be happening since the data is read lazily on-demand, though it's possible there is some memory leak here.

**Comment by juliusfrost** [comment]
I found that this happens with MARWIL and when num_gpus: 1
I do not have a reproduction script right now as it is coupled with a lot of data preprocessing I can't share feasibly yet.

**Comment by juliusfrost** [comment]
@ericl I provided a new reproduction script. I still get memory leaks with both cpu and gpu

**Comment by ericl** [comment]
Hey @juliusfrost I'm happy to look at this, but can you trim it down so the repro script is self-contained as the bug template specifies? This means (1) one script that runs, with (2) no library dependencies. It's fine to have some data files since that's required in this case.

**Comment by juliusfrost** [comment]
I'm not sure how to separate the library that because you need it to download the data

**Comment by ericl** [comment]
Yeah, in that case I would try to reproduce it with CartPole-v0 or Pong-v0. You can use this script to quickly generate a bunch of fake data: https://docs.ray.io/en/master/rllib-offline.html#example-converting-external-experiences-to-batch-format

**Comment by juliusfrost** [comment]
Okay, I updated the repro script to with Pong: https://github.com/juliusfrost/rllib-memory-leak

**Comment by richardliaw** [comment]
Maybe this might also be an instance related to #10890 and its corresponding fix #10905

**Comment by ericl** [comment]
Thanks, I'll take a look!

**Comment by ericl** [comment]
@juliusfrost it turns out there isn't a leak after all-- just misleading documentation on the replay buffer size. The size is controlling the number of batches, not steps, so 100k will lead to essentially infinite memory usage. Setting the replay buffer to a smaller value (like 20) fixes the issue.

**Comment by juliusfrost** [comment]
Interesting. Thanks for figuring that out! Does it make sense to keep the `replay_buffer_size` measured in batches and not steps? Because one might not know the exact number of steps in each replay batch if they have different episode lengths. Maybe it should be `replay_buffer_size` repurposed to cap the measure on steps and `replay_batch_size` to denote the number of batches loaded into replay. Also, should this be additionally documented in the [input API](https://docs.ray.io/en/master/rllib-offline.html#input-api) or is this specific to MARWIL?

**Comment by ericl** [comment]
I think we should change it to always cap on steps and remove / deprecate sizing in batches since it is quite confusing. Timesteps always corresponds fairly intuitive to memory usage.
