### ISSUE TITLE
Register for Ray Summit

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#9963]
We will be hosting a (free) virtual [**Ray Summit**](https://events.linuxfoundation.org/ray-summit/?utm_source=Robert&utm_medium=GitHub&utm_campaign=github_issue#featuredspeakers) from September 30 to October 1.

The conference will be about **scalable Python and scalable machine learning** and will feature keynotes from prominent members of the Python and machine learning communities!

This inaugural, two-day conference will showcase Ray best practices, real-world case studies, and the latest research in AI and other scalable systems built on Ray. We hope you can [**join us there**](https://events.linuxfoundation.org/ray-summit/?utm_source=Robert&utm_medium=GitHub&utm_campaign=github_issue#featuredspeakers) to learn more about how companies are using Ray and the Ray ecosystem in production!

[<img width="1348" alt="Screen Shot 2020-08-06 at 11 22 54 AM" src="https://user-images.githubusercontent.com/249517/89567872-42fc6880-d7d7-11ea-8083-4ef4f9e9070f.png">](https://events.linuxfoundation.org/ray-summit/?utm_source=Robert&utm_medium=GitHub&utm_campaign=github_issue#featuredspeakers)

**Comment by josjo80** [comment]
How will our Tuesday, Anyscale Academy, tickets be associated with our accounts?  I signed up for the education sessions before creating my account.
Thanks.

**Comment by robertnishihara** [comment]
The talks are available at https://www.youtube.com/playlist?list=PLzTswPQNepXlr2L75tZt7l8tyVZkO-RVt.
