### ISSUE TITLE
Access to previous compiled Ray releases?

### ISSUE THREAD

**Issue by mnicstruwig** [ray-project/ray#9978]
### What is your question?

Are there wheels available for previous releases of Ray? This bug of mine hasn't been addressed: https://github.com/ray-project/ray/issues/8643, and as a result I'm forced to rely on version of Ray <=0.8.1 for my academic research until it's been fixed. 

Unfortunately, it appears as if previous version of Ray are no longer available on PyPi, and I'm struggling to find build instructions to build the 0.8.1 release from source.

Thanks!
Michael.

**Comment by richardliaw** [comment]
https://pypi.org/project/ray/0.7.7/ seems like previous versions are still available. Maybe try downgrading your python version?

**Comment by mnicstruwig** [comment]
Thanks! I didn't realize I was using Python 3.8 -- thank you!
