### ISSUE TITLE
How to make Ray shared memory writeable?

### ISSUE THREAD

**Issue by Colafroth** [ray-project/ray#9979]
A little bit of context:
I am writing a stock back test program which subscribes to a websocket feed that streams data for over 100 stocks 1 minute candle. Since this is a back test program, it actually get fed by my local data.

I am trying to utilise Ray for multiprocessing.

So it will receive stock data in a loop locally, for example, A, B, C .... A, B, C... continuously until end of time period. Currently my set up with Ray is call `handleStock.remote()` asynchronously for each of the stock data. For performance reason, each time it process same stock but different time, there should be some cache to help process faster. But due to each of the stock per time is running as a completely new process/worker in Ray, I can't have a place to share memory and also write to it. I tried Ray `put` method but it's read only.

Is there a way to resolve this or a different tool to run this back test?

**Comment by rkooo567** [comment]
cc @robertnishihara
