### ISSUE TITLE
[Feature request] AWS Lambda support

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/ray#9983]
Are there any plans to include support for deploying Ray clusters using AWS lambda?

**Comment by edoakes** [comment]
Might be an interesting thing to hack on and try to get working but it's unlikely we'd add support for this. Lambda isn't built to be a deployment layer for higher-level services and doesn't even support direct communication via TCP/UDP between processes, so you'd need to do some magic like STUN to get around the NAT.

**Comment by rohan-gt** [comment]
@edoakes I was thinking that maybe you could use it to run a large no. of embarrassingly parallel processes like batch processing data or even as a backend for ray.tune where you can asynchronously call a 1000 lambdas to parallelly run multiple hyperparameter combinations instead of using the system's cores for multiprocessing
