### ISSUE TITLE
[core] Ray on slurm cluster hangs after running a while.

### ISSUE THREAD

**Issue by angshine** [ray-project/ray#9999]
### What is your question?
I'm running ray on a slurm cluster with 5 nodes. One node is used as the head node without any computing work. Each worker node launch 8 Tasks, each requires 1 gpu and 4 cpus cores to do some heavy computing. However, some Tasks hang after running a while and other Tasks work properly. I've tested the code on a local machine with 2 Tasks and it works with no problem. What might be the cause of this problem? Besides this problem, I find that the log within each Task is repeatedly logged on all worker nodes, but I think that each Task should only be run on one node, why I receive repeated logs?

**Code to launch the tasks:**
```python
ray_worker_ids = []
for w_idx in range(args.n_task):
    ray_worker_ids.append(process_with_single_worker.remote(work_loads[w_idx], args, w_idx))
```

**Decorator of the task:**
```python
@ray.remote(num_cpus=4, num_gpus=1, resources={"worker_node": 1})
def process_with_single_worker(work_loads, args, worker_id):
    # some heavy works...
```
**Slurm script:**
```shell
#!/bin/bash

#SBATCH --mem=128
#SBATCH --gres=gpu:8
#SBATCH --cpus-per-task=64
#SBATCH --nodes=5
#SBATCH --tasks-per-node 1
#SBATCH --exclusive

worker_num=4 
num_gpus=8  
num_cpus=32  # num cpus per node

nodes=$(scontrol show hostnames $SLURM_JOB_NODELIST) # Getting the node names
nodes_array=( $nodes )

node1=${nodes_array[0]}

ip_prefix=$(srun --nodes=1 --ntasks=1 -w $node1 hostname --ip-address) # Making address
suffix=':6379'
ip_head=$ip_prefix$suffix
redis_password=$(uuidgen)

export ip_head # Exporting for latter access by trainer.py

srun --nodes=1 --ntasks=1 -w $node1 ray start --block --head --redis-port=6379 --redis-password=$redis_password --num-gpus=$num_gpus --num-cpus=2 \
    --internal-config='{"initial_reconstruction_timeout_milliseconds": 100000}' \
    --num-redis-shards 8 & # Starting the head
sleep 30
# Make sure the head successfully starts before any worker does, otherwise
# the worker will not be able to connect to redis. In case of longer delay,
# adjust the sleeptime above to ensure proper order.

for ((  i=1; i<=$worker_num; i++ ))
do
  node2=${nodes_array[$i]}
  srun --nodes=1 --ntasks=1 -w $node2 ray start --block --address=$ip_head --redis-password=$redis_password --num-gpus=$num_gpus --num-cpus=$num_cpus \
      --memory=$((128 * 1024 * 1024 * 1024)) \
      --resources='{"worker_node": 100}' \
      --internal-config='{"initial_reconstruction_timeout_milliseconds": 100000}' & # Starting the workers
  # Flag --block will keep ray process alive on each compute node.
  sleep 30
done

python -u ./script_name.py --redis_password=$redis_password --n_task=32
```

**Comment by rkooo567** [comment]
> I find that the log within each Task is repeatedly logged on all worker nodes, but I think that each Task should only be run on one node, why I receive repeated logs?

@wuisawesome Do you have any idea why?

What version of Ray are you using? Also, can you show us logs from /tmp/ray/session_latest/logs/gcs_server.err?

**Comment by amogkam** [comment]
Is this still an issue @angshine? Could you also send over the console output you are seeing on all the nodes as well as your python script?
